### ISSUE TITLE
Extension content script should do manifest discovery

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#100]
As Dion recommended, the extension can be a passive PWA inspection tool, lighting up as active when a manifest is detected.

I investigated using the `chrome.declarativeContent` API for this, however it is limited to _visible_ elements, and a `<link>` element is not one. 

The best solution appears to be a small content script, as `"run_at": "document_idle"`, which looks for the manifest `<link>` in the DOM and sets the page action icon/badge accordingly.

Does that sound about right to folks?

**Comment by brendankenny** [comment]
This is OK, but I'm a big fan of minimum permissions. Any chance of getting `<link>` added to the list of queryable elements?

**Comment by paulirish** [comment]
@brendankenny nope. it uses Blink's core CSS style calculation engine, which quickly discards display:none elements as they don't matter.

It's possible to change the platform, but it'd be a kinda gross hack.


Also.. our `chrome.debugger` permissions is arguably the largest permission available. Okay not arguably. It literally doesn't get any bigger than that. :)

**Comment by paulirish** [comment]
I think this fell off our priorities. TBH these days I think a dedicated PWA discovery extension would be better than tossing it into lighthouse. It requires a content script that runs everywhere, so its pretty distinct than our usecases.

closing.
