### ISSUE TITLE
Support for HTTP/2 Server Push

### ISSUE THREAD

**Issue by naveedahmed1** [GoogleChrome/lighthouse#10009]
#### What is the current behavior?
It seems that at the moment PSI and LH has partial support fro HTTP/2 Server push and it only supports pushing css files from server.

If we push other contents, for example fonts, scripts and images, these files are ignored by LH and these requests are counted twice. As a result it negatively affect the LH score.

#### What is the expected behavior?
Support for HTTP/2 Server push should be improved.

#### Environment Information
* Lighthouse version: Current version on http://web.dev/ and https://developers.google.com/speed/pagespeed/insights/
* Chrome version: all
* Node.js version: all
* Operating System: all

**Comment by patrickhulce** [comment]
Thanks for filing! You are correct, it is not supported at all currently in PSI, see #7326 for progress.

**Comment by naveedahmed1** [comment]
One question, if LH/PSI doesn't support this at the moment does this mean that Google crawler doesn't support this as well? In Google I/O and Chrome Dev Summit they mentioned that the crawler is now evergreen and uses latest version of Chrome.

**Comment by josescasanova** [comment]
> One question, if LH/PSI doesn't support this at the moment does this mean that Google crawler doesn't support this as well? In Google I/O and Chrome Dev Summit they mentioned that the crawler is now evergreen and uses latest version of Chrome.

Great question, curious about if the crawler doesn't support this as well.

**Comment by connorjclark** [comment]
We don't comment on how Google crawls the web.
