### ISSUE TITLE
🎉🎉👯‍♂💡🏠👯‍♂🎉🎉 

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#10000]
:P

**Comment by patrickhulce** [comment]
Hahahaha, how long have you been monitoring for this? :)

**Comment by connorjclark** [comment]
oh wow I nearly took it myself without realizing https://github.com/GoogleChrome/lighthouse/pull/9999

**Comment by brendankenny** [comment]
![i-can-be-your-lighthouse](https://user-images.githubusercontent.com/316891/69502803-4e299580-0ee1-11ea-8d2e-7aabd428faf7.gif)
