### ISSUE TITLE
[web.dev/measure] 301/307 to HTTPS result in 'Does not use HTTPS'

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [GoogleChrome/lighthouse#10008]
#### Provide the steps to reproduce
1. Run LH on http://fructosedb.org
  
#### What is the current behavior?
Reports 'Does not use HTTPS'

#### What is the expected behavior?
Should recognize the redirection from HTTP to HTTPS

#### Environment Information
* Affected Channels: https://web.dev/measure/
* Lighthouse version: 5.6.0

**Comment by patrickhulce** [comment]
Thanks for filing @s-h-a-d-o-w! If you audit an `http` site there will always be at least 1 insecure request even if it ends up redirecting to `https`, we consider this specific audit behavior WAI but plan to address your concern by adding a warning in the UI if the page ending up redirecting #9969 #1917.

**Comment by s-h-a-d-o-w** [comment]
Ah, I see, fair enough - thanks! :)
