### ISSUE TITLE
Add pagespeed.green to Lighthouse Integrations

### ISSUE THREAD

**Issue by alexgreencode** [GoogleChrome/lighthouse#10012]
I would like to add my project -[ PageSpeed Green](https://pagespeed.green) to Lighthouse Integrations section.

**Comment by exterkamp** [comment]
We usually take these as PR's (e.g. #5732, #9954, #9753, #9743), also I can't get https://pagespeed.green/ to load?

**Comment by alexgreencode** [comment]
@exterkamp Thanks - will make PR. Should work - I've just checked.

**Comment by exterkamp** [comment]
Not for me 😉 
![image](https://user-images.githubusercontent.com/6392995/69486410-4e059900-0e00-11ea-86cc-c7499a5f52f2.png)

**Comment by alexgreencode** [comment]
Good catch, thanks for that - can you tell me please where are you located?

**Comment by exterkamp** [comment]
> where are you located?

California

**Comment by alexgreencode** [comment]
Thanks - I'll fix it and after that will create PR.
