### ISSUE TITLE
NO_FCP for webGL page from Lighthouse, but there is FP in console

### ISSUE THREAD

**Issue by rubyzhao** [GoogleChrome/lighthouse#10015]
## Provide the steps to reproduce
1. Clone it from https://github.com/rubyzhao/Three_MyChart_Line
2. Open LineBufferGeometry.html with Live Server
3. lighthouse http://127.0.0.1:5500/LineBufferGeometry.html --view --output-path=LightHouse_Output\Canvas.html --output=html

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/12829001/69496802-0f96d980-0ee7-11ea-9406-89fd39281d4d.png)
For more detail, refer to [Canvas.zip](https://github.com/GoogleChrome/lighthouse/files/3883753/Canvas.zip)
Also tried Audits in DevTools, got the same result as above.

#### But there is FP from console:

![image](https://user-images.githubusercontent.com/12829001/69496839-787e5180-0ee7-11ea-8c0e-a4e3d4b33263.png)

#### Environment Information

* Lighthouse version: 5.6.0
* Chrome version: 78.0.3904.108 (Official Build) (64-bit)
* Node.js version: 12.11.1
* Operating System: Win10X64 1083
* Live Server: 5.6.1
* VS Code: 1.40.1

**Comment by patrickhulce** [comment]
Thanks for filing @rubyzhao! I think this page legitimately does not have a first contentful paint. The screenshot of performance entries first paint is a different spec event from first contentful paint and while [non-white canvas renders](https://web.dev/first-contentful-paint/#what-fcp-measures) *should* be included, it looks like it's not :/

Might need to file a crbug to get this addressed.

**Comment by brendankenny** [comment]
> Might need to file a crbug to get this addressed.

@patrickhulce that sounds like the kind of thing you would have already filed

https://crbug.com/991228 :P

**Comment by patrickhulce** [comment]
Haha, I thought we had solved this already!! That certainly explains it 😆

**Comment by rubyzhao** [comment]
Thanks @patrickhulce and @brendankenny. I even changed the full background to no-white color, still can't get FCP. Hope they can fix the bug soon. Is there any workaround for the page with webGL?

**Comment by patrickhulce** [comment]
The only workaround I'm aware of would be to inject some other content at the same time as your webGL paint, like some text or an `<img>`

**Comment by rubyzhao** [comment]
@patrickhulce, Haha add anything in body at the beginning, for example <h1>test</h1> will fool lighthouse. But it will not work at bottom of body. For example, add it below <script src="r110/three.min.js"></script>, will not work. Interesting.

**Comment by patrickhulce** [comment]
Hm, that's definitely unexpected that it wouldn't work below a script unless that script document.write a comment or something odd.

**Comment by connorjclark** [comment]
No movement on the crbug ... should we ping someone?

**Comment by 0xbkt** [comment]
Having the same thing here.

**Comment by patrickhulce** [comment]
This has been fixed upstream 🎉 

https://melodic-class.glitch.me/fcp-canvas-3js.html
