### ISSUE TITLE
Wildly inconsistent results in headless mode

### ISSUE THREAD

**Issue by rdsubhas** [GoogleChrome/lighthouse#10014]
#### Provide the steps to reproduce

1. Run without headless mode: `lighthouse --view "https://www.omio.com.br"` a few times

<img width="742" alt="image" src="https://user-images.githubusercontent.com/1570745/69495799-3d6e2500-0ecb-11ea-9114-37ff7d3af2db.png">

2. Run in headless mode: `lighthouse --view --chrome-flags="--headless" "https://www.omio.com.br"`

<img width="738" alt="image" src="https://user-images.githubusercontent.com/1570745/69495803-4ced6e00-0ecb-11ea-9afe-db978e08a32a.png">
  
#### What is the current behavior?

More than `300%` difference between headless and non-headless modes.

#### What is the expected behavior?

Regular lighthouse variance, less than `40%`.

A lot of community/CI tools run using puppeteer, which defaults to chrome headless mode. So would be useful to at least have prominent documentation saying headless mode is not recommended.

#### Environment Information

* Affected Channels: CLI
* Lighthouse version: 5.6.0
* Chrome version: 78.0.3904.108
* Node.js version: v10.16.2
* Operating System: MacOS 10.14.6

#### Related issues

* https://github.com/sitespeedio/plugin-lighthouse/issues/38

**Comment by patrickhulce** [comment]
Thanks for filing @rdsubhas! That URL returns a bot-specific interstitial page with status code 405 when requested by headless Chrome. If the page is intentionally varying its output, then obviously you'll get variable results when measuring it.


**Example Screenshot**
![image](https://user-images.githubusercontent.com/2301202/69500053-4f48cb80-0ebd-11ea-9614-bb925a16681f.png)

**Comment by rdsubhas** [comment]
Ah great thanks!
