### ISSUE TITLE
Protocol_TimeOut

### ISSUE THREAD

**Issue by JaybeeClassical** [GoogleChrome/lighthouse#10026]
Was trying to run an audit on my site but unfortunately, the audit didn't go through rather reported an error message below:

Channel: DevTools
Initial URL: https://iamjude.xyz/
Chrome Version: 78.0.3904.108
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@4b26898a39ee037623a72fcfb77279fce0e7d648/audits_worker/audits_worker_module.js:1250:210)
```

**Comment by NigelRS** [comment]
Having a similar problem with a task run today

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://lifetoolsdigital.com/5days/
Chrome Version: 88.0.4324.104
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:454:772
```
