### ISSUE TITLE
Icon font compatibility 

### ISSUE THREAD

**Issue by RickyOnGit** [GoogleChrome/lighthouse#10022]
Hello everyone, the question is about lighthouse tests and icon font compatibility.
In my opinion, loading the icons as if they were a font is one of the simplest and fastest methods. Why doesn't lighthouse support this method ?

I did lighthouse tests with all the font-display options available 
(font-display:swap; font-display:fallback; font-display:auto; font-display: block; font-display:optional; )
in this website: [odisseo web performance](https://odisseo.io)

The [lighthouse test](https://googlechrome.github.io/lighthouse/viewer/?gist=aa40c581d1dbdde767c0b71883abd066) return me always the same issue: **Ensure text remains visible during webfont load** 
_Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading_
URL: [https://odisseo.io/wp-content/themes/generatepress/fonts/generatepress.woff2](https://odisseo.io/wp-content/themes/generatepress/fonts/generatepress.woff2)

There is no way to make lighthouse algorithm  understand that  are icon fonts and prevent this error message from appearing ?

The only alternative at the moment; would be to load the icons with another method (eg via svg), the question is: is it really worth it?

Thank you !!!

**Comment by patrickhulce** [comment]
Thanks for filing! We certainly don't want to discourage icon font usage, if your font is properly declared with block, fallback, optional, or swap, it should pass that audit.

https://github.com/GoogleChrome/lighthouse/blob/0f600e0cd3b6f1bd8be10d5b4ede9edcfc4940fb/lighthouse-core/audits/font-display.js#L10

The font-face declaration on the page currently does not declare any `font-display` which is why it is failing, so I'm not able to reproduce the described behavior.

(Great job on the 99 perf score btw! 😃 )

**Comment by RickyOnGit** [comment]
Thank you Patrick ;)  @patrickhulce 
At line number 63 on the page, there is, inside internal css style, the @font-face rule:
**@font-face { font-family:GeneratePress; src: local('GeneratePress'), url(https://odisseo.io/wp-content/themes/generatepress/fonts/generatepress.woff2) format('woff2'); font-display:swap; }**

I don't know, maybe something wrong in the  font-face declaration ?
![code](https://user-images.githubusercontent.com/39222627/69610357-edf33a80-102b-11ea-80d5-611994bedc62.png)
?

**Comment by patrickhulce** [comment]
Yes but on line 47 the inline stylesheet that declares the font with *all* formats, not just woff2, is missing the font-display value.

If you set font-display on that declaration, the audit should pass.

**Comment by RickyOnGit** [comment]
Thank you Patrick @patrickhulce
The fonts declared are all computers/devices local system fonts ( -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol") and the item of the [lighthouse test](https://googlechrome.github.io/lighthouse/viewer/?gist=aa40c581d1dbdde767c0b71883abd066) **was referring to the generatepress.woff2** .  ![fontface_1](https://user-images.githubusercontent.com/39222627/69708580-2b26fd80-10fc-11ea-8323-98c69b744c70.png).
**Anyway now I have declared at line 9, for all fonts, the font-face rule and the audit  didn't pass.** 

--
  | @font-face { font-family:-apple-system; src: local("-apple-system"); font-display:swap; }
  | @font-face { font-family:system-ui; src: local("system-ui"); font-display:swap; }
  | @font-face { font-family:BlinkMacSystemFont; src: local("BlinkMacSystemFont"); font-display:swap; }
  | @font-face { font-family:"Segoe UI"; src: local("Segoe UI"); font-display:swap; }
  | @font-face { font-family:Helvetica; src: local("Helvetica"); font-display:swap; }
  | @font-face { font-family:Arial; src: local("Arial"); font-display:swap; }
  | @font-face { font-family:sans-serif; src: local("sans-serif"); font-display:swap; }
  | @font-face { font-family:"Apple Color Emoji"; src: local("Apple Color Emoji"); font-display:swap; }
  | @font-face { font-family:"Segoe UI Emoji"; src: local("Segoe UI Emoji"); font-display:swap; }
  | @font-face { font-family:"Segoe UI Symbol"; src: local("Segoe UI Symbol"); font-display:swap; }


This is the [new lighthouse test](https://googlechrome.github.io/lighthouse/viewer/?gist=4cc272a6afa28adede68daef4a90c437) with the font-face rule declared for all fonts.

Trust me ;) I think, there is  **a problem related to icon fonts and lighthouse audit**. On another web project I developed for a company ([trj](https://trj.it/)) with the [wordpress magaz theme](https://themeforest.net/item/-aspire-news-magazine-clean-wordpress-theme/15086977) that also uses fonts icon, I encountered in the same problem. In this project, then, in the end, I had to delete the font icon and replace all the icons with png images. I increased the weight of the pages in order to pass the lighthouse test but this is an absurdity in my opinion to see the thing. 
This is the [lighthouse test for trj website](https://googlechrome.github.io/lighthouse/viewer/?gist=c5defcfe3dbebb6efa6ce183503546fc) 

I use lighthouse tests a lot during web development, this takes a lot of time and hard work. Following lighthouse, almost to the letter, I always obtained excellent performance results for my works so I really care that they are reliable. This thing about icon fonts seems to me a paradox and I hope it can be solved as soon as possible. I don't think I made any mistake in declaring code, because on two web projects I tried everything to fix them.

**Comment by patrickhulce** [comment]
> the item of the lighthouse test was referring to the generatepress.woff2

I'm aware of that @RickyOnGit :) I wasn't referring to the system fonts, you definitely don't need to declare font-display for those. I was referring to the fact that this page has duplicate declarations for "GeneratePress", one of which lists all font formats and does not have a font-display attribute, even if the other one you referenced on what used to be line 63 does.

Here is a screenshot of the declaration I was talking about that is missing `font-display` (line 59 on the updated page)

![image](https://user-images.githubusercontent.com/2301202/69737268-bb177800-10f9-11ea-960d-9c3d3bd58baa.png)

> In this project, then, in the end, I had to delete the font icon and replace all the icons with png images. I increased the weight of the pages in order to pass the lighthouse test but this is an absurdity in my opinion to see the thing.

I'm so sorry you felt you had to do this. This is absolutely not what the audit is trying to suggest that you do. If there is a version of this other site with the icon font issue, we'd love to check it out to make sure there's nothing wrong, but on https://odisseo.io/, there is definitely a font-face declaration missing `font-display`.

**Comment by RickyOnGit** [comment]
@patrickhulce You are right, sorry !!! Is the internal css style of the main theme. Ok understand everything. 
Thank you ;)

**Comment by RickyOnGit** [comment]
Ok Patrick, thank you very much, **solved!!!** I write what i did (could be useful for someone else).  I removed the parent (Generatepress) file theme function : 
wp-content\themes\generatepress\inc\css-output.php 
line: 706 
`add_action( 'wp_enqueue_scripts', 'generate_enqueue_dynamic_css', 50 );

function generate_enqueue_dynamic_css() {
	if ( ! get_option( 'generate_dynamic_css_output', false ) || is_customize_preview() || apply_filters( 'generate_dynamic_css_skip_cache', false ) ) {
		$css = generate_base_css() . generate_font_css() . generate_advanced_css() . generate_spacing_css();
	} else {
		$css = get_option( 'generate_dynamic_css_output' ) . '/* End cached CSS */';
	}

	$css = $css . generate_no_cache_dynamic_css() . generate_do_icon_css();

	wp_add_inline_style( 'generate-style', $css );
}` 
**IN THIS WAY:** 
In the child theme function I have add:
`add_action('wp','on_off');
function on_off(){
remove_action( 'wp_enqueue_scripts', 'generate_enqueue_dynamic_css',50 );}

add_action( 'wp_enqueue_scripts', 'genchild_enqueue_dynamic_css', 49 );

function genchild_enqueue_dynamic_css() {
	if ( ! get_option( 'generate_dynamic_css_output', false ) || is_customize_preview() || apply_filters( 'generate_dynamic_css_skip_cache', false ) ) {
		$css = generate_base_css() . generate_font_css() . generate_advanced_css() . generate_spacing_css();
	} else {
		$css = get_option( 'generate_dynamic_css_output' ) . '/* End cached CSS */';
	}

	$css = $css . generate_no_cache_dynamic_css() . genchild_do_icon_css();

	wp_add_inline_style( 'generate-style', $css );
}

function genchild_do_icon_css() {
	$output = false;

	if ( 'font' === generate_get_option( 'icons' ) ) {
		$url = trailingslashit( get_template_directory_uri() );

		$output = '@font-face {
			font-family: "GeneratePress";
			src:  url("' . $url . 'fonts/generatepress.eot");
			src:  url("' . $url . 'fonts/generatepress.eot#iefix") format("embedded-opentype"),
				  url("' . $url . 'fonts/generatepress.woff2") format("woff2"),
				  url("' . $url . 'fonts/generatepress.woff") format("woff"),
				  url("' . $url . 'fonts/generatepress.ttf") format("truetype"),
				  url("' . $url . 'fonts/generatepress.svg#GeneratePress") format("svg");
			font-weight: normal;
			font-style: normal;
                        font-display:swap;
		}';

		if ( defined( 'GENERATE_MENU_PLUS_VERSION' ) ) {
			$output .= '.main-navigation .slideout-toggle a:before,
			.slide-opened .slideout-overlay .slideout-exit:before {
				font-family: GeneratePress;
			}

			.slideout-navigation .dropdown-menu-toggle:before {
				content: "\f107" !important;
			}

			.slideout-navigation .sfHover > a .dropdown-menu-toggle:before {
				content: "\f106" !important;
			}';
		}
	}

	if ( 'svg' === generate_get_option( 'icons' ) ) {
		$output = 'button.menu-toggle:before,
		.search-item a:before,
		.dropdown-menu-toggle:before,
		.cat-links:before,
		.tags-links:before,
		.comments-link:before,
		.nav-previous .prev:before,
		.nav-next .next:before,
		.generate-back-to-top:before {
			display: none;
		}';
	}

	if ( $output ) {
		return str_replace( array( "\r", "\n", "\t" ), '', $output );
	}
}
`
 so I could add the font-display declaration: swap;

And now the audit pass of the [lighthouse test](https://googlechrome.github.io/lighthouse/viewer/?gist=3c2e84f683566f5f7a158a96938bb3cb)

**Comment by atomicf4ll** [comment]
Hey, I'm dealing with exactly the same issue. I don't really understand what and where you changed. Could you please explain that? P.S: the code you wrote above probably isn't formatted right as it should be.
