### ISSUE TITLE
Doctype check misses some quirky doctypes

### ISSUE THREAD

**Issue by zcorpan** [GoogleChrome/lighthouse#10030]
https://github.com/GoogleChrome/lighthouse/pull/5274 introduced a check for the doctype.

> Page has the HTML doctype
> Specifying a doctype prevents the browser from switching to quirks-mode. Read more on the [MDN Web Docs page](https://developer.mozilla.org/en-US/docs/Glossary/Doctype)

https://doctype-html-foo.glitch.me/ is a test page that uses `<!DOCTYPE html foo>`, which triggers quirks mode but passes the Lighthouse check.

While that exact doctype is maybe unlikely to happen, there are other variants that are more likely, such as `<!DOCTYPE html />` or `<!DOCTYPE html PUBILC "-//W3C//DTD HTML 4.01//EN">` (note the typo) or `<!DOCTYPE html PUBLIC ”-//W3C//DTD HTML 4.01//EN”>` (smart quotes).

#### Provide the steps to reproduce
1. Run LH on https://doctype-html-foo.glitch.me/
  

#### What is the current behavior?
"Page has the HTML doctype" passes.

#### What is the expected behavior?
"Page has the HTML doctype" should fail when `document.compatMode` is `BackCompat`.

#### Environment Information
* Affected Channels: tested DevTools
* Lighthouse version:
* Chrome version: 78.0.3904.97 (Official Build) (64-bit)
* Node.js version:
* Operating System:

**Related issues**

**Comment by connorjclark** [comment]
I'm interested in this for correctness-sake, and I want to learn more, but I think this is likely a low-impact change.

**Comment by k99sharma** [comment]
Hey! I read about it and I tried the lighthouse test on the above example and it passed the audit for "Page has HTML doctype" but the document is rendered in `BackCompat` mode i.e quirks mode. So I got that we need to perform a check for this condition.
So, If this issue is still open I would like to solve it!

**Comment by k99sharma** [comment]
Hey! I was just checking my PR and found there were a lot of problems with it. So this time I ran tests and fixed everything. I hope this one works out.
