### ISSUE TITLE
Scoring documentation is outdated

### ISSUE THREAD

**Issue by AymenLoukil** [GoogleChrome/lighthouse#10035]
I think that the scoring documentation is outdated here 
https://github.com/GoogleChrome/lighthouse/blob/d2ec9ffbb21de9ad1a0f86ed24575eda32c796f0/docs/scoring.md#how-are-the-scores-weighted

**Comment by connorjclark** [comment]
rolling into https://github.com/GoogleChrome/lighthouse/issues/9774
