### ISSUE TITLE
AMP Stackpack: Incorrect advice to run AMP Optimizer on AMP pages which are already optimized

### ISSUE THREAD

**Issue by westonruter** [GoogleChrome/lighthouse#10045]
When running Lighthouse on an AMP page being served from the Cache, which is already serving Optimized AMP, the AMP stackpack is nevertheless suggesting to use the AMP Optimizer:

![image](https://user-images.githubusercontent.com/134745/69772791-b973a180-1145-11ea-97ad-01339a870edc.png)

So this is not good advice because running the AMP Optimizer will have no effect since it is already optimized.

This stackpack suggestion for AMP should not be offered when the `html` element has the `transformed` attribute present.

#### Provide the steps to reproduce
1. Run LH performance audit on https://elsoberano-org.cdn.ampproject.org/c/s/elsoberano.org/constitucion/denuncian-que-walmart-esta-pidiendo-mas-represion-para-proteger-sus-ganancias/

This is the optimized AMP Cache version of https://elsoberano.org/constitucion/denuncian-que-walmart-esta-pidiendo-mas-represion-para-proteger-sus-ganancias/

#### What is the current behavior?

On an optimized AMP page, Lighthouse is advising: “Use tools such as AMP Optimizer to server-side render AMP layouts.”

#### What is the expected behavior?

No such advice should be offered.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.7.0
* Chrome version: 80.0.3977.4 (Official Build) canary (64-bit)
* Operating System: MacOS

**Comment by connorjclark** [comment]
This is WAI unfortunately, I don't think we've discussed detecting the tools suggested in stack packs. At the moment stack-specific advice is always given when a specific stack is detected.

**Comment by patrickhulce** [comment]
This is the same root issue as https://github.com/GoogleChrome/lighthouse/issues/2832 and should be resolved when the proposed solution is implemented. De-duping into it.
