### ISSUE TITLE
Worked before enabling Centos6 Caches

### ISSUE THREAD

**Issue by headlydotcom** [GoogleChrome/lighthouse#10041]
The report worked prior to enabling Centos6 memcache/socache, which was one of the features the report suggested that I enable. Now the report fails with Lighthouse returned error: FAILED_DOCUMENT_REQUEST at the 80% mark

**Comment by connorjclark** [comment]
Where does lighthouse suggest `memcache`?

**Comment by headlydotcom** [comment]
Hello,

There is no suggestion about memcache but I ran the page speed test
numerous times across numerous websites prior to the error. After the
lighthouse suggested to enable caches, on the server (dedicated) i enabled
memcache and socache which did significantly increase the speed of page
loads, but now lighthouse bombs at the 80% mark on the test. If you'd like
I can rebuild without the cache and retest but that was the only change
before the test routinely fails.

Thank you for the follow up, I do not believe this is related to #2784

Sincerely,

Glenn

**Comment by connorjclark** [comment]
Sorry for the delay in response. If you are getting `FAILED_DOCUMENT_REQUEST`, I'd expect the site to fail on `curl` too. Can you confirm? And can you provide a public URL?

**Comment by headlydotcom** [comment]
Hi,
No worries, please close, likely a firewall issue, has been resolved.
Thank you
Glenn
