### ISSUE TITLE
Keep track of audit progress and/or listenning to Lighthouse logs

### ISSUE THREAD

**Issue by TAnas0** [GoogleChrome/lighthouse#10043]
Hey all,

I am using Lighthouse as an NPM package in a serverless environment. I would love to keep track of the progress of the audit, more specifically a progress score to fill a progress bar on the frontend.

Previously, my app was ran inside a Docker container, and was using Lighthouse as a CLI command. Since I was using [NodeJS process commands](https://nodejs.org/api/child_process.html), I was able to listen to Lighthouse's logs and deduce a "progress score" by parsing what it is outputting.

Now that I migrated to a serverless environment, I was wondering if there is a way to listen to Lighthouse's logs as they are printed. Unfortunately, I couldn't find any configuration for `lighthouse-logger` except for its logging level.

The ideal for me would be listening to the logs and execute a function on each line.

There are many limitations that are not relevant to Lighthouse itself, and more related to my serverless environment or NodeJS in general. That's why I thought of stopping my dirty hacking attempts for a second and ask the community for help before I am too deep into the rabbit's hole. Maybe someone else has already solved this. So any help/pointers would be greatly appreciated.

Cheers

**P.S:** If this is a feature you guys are interested in, if it is not too complicated or too entangled with the code base, I would be up for landing a helping hand

**Comment by patrickhulce** [comment]
Neat idea @TAnas0! 

`lighthouse-logger` emits events for each status update 

https://github.com/GoogleChrome/lighthouse/blob/105f30db7f407007fcf1b83121a26034c68f9f1a/lighthouse-logger/index.js#L131-L134

and exports that event emitter as `.events`

https://github.com/GoogleChrome/lighthouse/blob/105f30db7f407007fcf1b83121a26034c68f9f1a/lighthouse-logger/index.js#L233-L241


This means you should be able to listen to the lighthouse status events with...
```js
require('lighthouse-logger').events.on('status', console.log)
```

**Comment by TAnas0** [comment]
Not the first time I ask something in here, and not the first time you solve my problem so quickly.

Thank you @patrickhulce for everything!!

I will be having fun with that piece of code.
