### ISSUE TITLE
 URL is not defined

### ISSUE THREAD

**Issue by Thinking80s** [GoogleChrome/lighthouse#10057]
`lighthouse --only-categories=performance https://google.com`

**Comment by Thinking80s** [comment]
![image](https://user-images.githubusercontent.com/338079/69901163-2e9add00-13b9-11ea-801f-fc589e732830.png)

**Comment by patrickhulce** [comment]
Per [docs](https://github.com/GoogleChrome/lighthouse#using-the-node-cli), minimum node version is v10 LTS, you're using 8.9.0.
