### ISSUE TITLE
Lighthouse Plugin Unable to Crawl Staged/Development Sites

### ISSUE THREAD

**Issue by kristenmajor** [GoogleChrome/lighthouse#10052]
We are encountering an issue where sites that are gated - such as staging websites / development websites - are not able to be crawled by the latest update to the Chrome plugin for Lighthouse.

It is returning the following error:
ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 401)

**Comment by connorjclark** [comment]
You'll need to use DevTools for that use case now. The extension uses an external service now.
