### ISSUE TITLE
'Defer offscreen images' doesn't consider 'loading=lazy' attribute

### ISSUE THREAD

**Issue by brightonmike** [GoogleChrome/lighthouse#10053]
I'm seeing some odd behaviour with Native Lazy Loading that has a JS fallback.

The source code we use is:

```
<img src="placeholder.jpg" data-src="image.jpg" loading="lazy" alt="" class="">
```

The JS identifies images with `loading=lazy`. If there's native support it makes the `data-src` the `src` and does nothing else. We then use Intersection Observer for other browsers.

However, Lighthouse is flagging images that are using this pattern as not being lazy loaded.

It does seem to be the case that images outside of the viewport are indeed loaded before they're seen, so on page load. These are the images that Lighthouse picks up on. That said, they are loaded with a low priority and only fetched after the onload event.

We can't control this behaviour. This is hammering our performance scores so it would be amazing to shed some light on why (or, indeed, are we doing something wrong). It feels unfair that a mechanism we can't control is being flagged as an issue by Lighthouse. Unless we are doing something wrong here. 

Unfortunately if I can't resolve this issue I have to move back to JS lazy loading. An example site that has this issue can be found here: https://www.drakes.com/clothing

**Comment by patrickhulce** [comment]
Thanks for filing @brightonmike and for the public URL for us! This is a high priority item for us to fix (https://github.com/GoogleChrome/lighthouse/issues/9767), but to address your immediate concern...

> This is hammering our performance scores

The opportunities have no direct impact on the performance score, the score is purely based on the metrics. The default lazy loading behavior of the browser should not be radically impacting your performance metrics. Hopefully this clears things up a bit!

If there's nothing else to add for us, we'll probably merge this issue into 9767 in our next cycle :)

**Comment by brightonmike** [comment]
That's super strange. I was comparing two different sites and it seemed to be the major flag on the one that has native lazy loading. Thanks for clarifying, there must be other reasons for the score.

**Comment by Lofesa** [comment]
Hi
Sorry if thi´s considered spaming this issue cause is not the same thing but seems to be related.
In PSI I get a Speed index about 1,3s and in web.dev is about 2,3s. Both test are run at same time.
The image that show in viewport has the loading="eager" attribute so accordling with the docs is: "Load the resource immediately, regardless of where it's located on the page".
In PSI the image is showed at the first frame but in web.dev seems to be delayed.

PSI:
![Captura](https://user-images.githubusercontent.com/22342793/69901348-a4368700-1380-11ea-8d4e-d93a5b0506f5.jpg)

Web.dev:
![Captura1](https://user-images.githubusercontent.com/22342793/69901354-ba444780-1380-11ea-8940-1c978ea2157e.JPG)

**Comment by paulirish** [comment]
If someone is using loading=lazy on an image we definitely shouldn't flag that in offscreen-images.

web.dev/blog offers a repro for this.

To be consistent with our caching audit, etc, we should filter out any image that has a valid `loading` attribute value. (Those appear to be `lazy`, `eager` or `auto`.)


(Also on web.dev/blog, i saw one of those was in-viewport, which is odd, but secondary IMO)

**Comment by Malvoz** [comment]
@paulirish, @jazyan The `auto` value has been removed (for now) from the specification, see https://github.com/whatwg/html/pull/3752#issuecomment-555328635.

**Comment by domfarolino** [comment]
It is true "auto" has been removed from the spec (for now), but we're planning on re-introducing it later on. Just for completeness, Chrome ships (and defaults to) "auto". For more info see https://github.com/GoogleChrome/web.dev/pull/1971#issuecomment-565630653.
