### ISSUE TITLE
AMP issues detected on https://bestssdlaptop.com/

### ISSUE THREAD

**Issue by mikilnarayani** [GoogleChrome/lighthouse#10061]
Search Console
AMP issues detected on https://bestssdlaptop.com/

To the owner of https://bestssdlaptop.com/:

Search Console has identified that your site is affected by 1 AMP issues:

Top Errors

Errors can prevent your page or feature from appearing in Search results. The following errors were found on your site:

A tag on this page requires an AMP component 'script' tag, which is missing.

We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

**Comment by patrickhulce** [comment]
Thanks for filing @mikilnarayani but this isn't the place for Search Console/AMP issues, if you have a Lighthouse issue feel free to follow our [bug template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)  :)
