### ISSUE TITLE
Integration with UI testing

### ISSUE THREAD

**Issue by Swazimodo** [GoogleChrome/lighthouse#10071]
**Feature request summary**

Integration with a UI testing framework like lighthouse.

**What is the motivation or use case for changing this?**
Currently lighthouse does not work well with SPA (single page applications). With only testing the landing page it just validates a loading screen. If it integrated with something like cypress you could validate the app as it was malipulated to make sure you had good coverage.

**How is this beneficial to Lighthouse?**
Would add support for SPAs

**Comment by paulirish** [comment]
@Swazimodo thanks for filing the issue.

We've been thinking about this too and agree this is underserved.

Could you provide some details on your intended usecases?  Are you mostly interested in performance metrics? Or accessibility details?

**Comment by Swazimodo** [comment]
My main concern is around accessibility. Performance in test environments does not often replicate prod and I put less value in that type of testing.

**Comment by connorjclark** [comment]
There is certainly value in measuring in controlled test environments (we call it Lab) vs prod (we call it Field). See this for more: https://web.dev/vitals-tools/

**Comment by Swazimodo** [comment]
I agree but you asked for my use case. Checking if an app feels slow is something that can be more easily tested other ways. However, with accessibility it is rare that someone will test with a screen reader or notice contrast issues that are slightly under the threshold. I order to manually check all these things has a high cost to do on an ongoing basis.

**Comment by BioPhoton** [comment]
Hi @Swazimodo, would User flows help here? 
Or plain puppeteer scripts?

**Comment by Swazimodo** [comment]
I'm not sure what the team needs to make progress 🤷‍♂️ This is my first request to this project.

**Comment by connorjclark** [comment]
We cover this today with userflows, yes. see https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md
