### ISSUE TITLE
ECONNREFUSED 127.0.0.1:9222

### ISSUE THREAD

**Issue by trevsewell** [GoogleChrome/lighthouse#10080]
#### Provide the steps to reproduce
1. Execute the following in AWS Lambda via a chromium layer

#### What is the current behavior?
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "Error: connect ECONNREFUSED 127.0.0.1:9222",
  "trace": [
    "Runtime.UnhandledPromiseRejection: Error: connect ECONNREFUSED 127.0.0.1:9222",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:210:5)",
    "    at processPromiseRejections (internal/process/promises.js:201:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:94:32)"
  ]
}

#### What is the expected behavior?
Return valid JS-consumeable output

#### Environment Information
* Affected Channels: Node, AWS Lambda
* Lighthouse version: 5.6.0
* Chrome version: chrome-aws-lambda v2.0.1 & Chromium v79.0.3945.0
* Node.js version: 12
* Operating System: N/A

```
const lighthouse = require('lighthouse')
const chromium = require("chrome-aws-lambda")

async function launchChromeAndRunLighthouse(url, opts = {}, config = null) {
    let browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
    }).then((browser) => {
        opts.port = browser.port;
        return lighthouse(url, opts, config).then(results => {
          return browser.close().then(() => results.lhr)
        });
    });
}

module.exports.report = (event, context, callback) => {
  launchChromeAndRunLighthouse('https://domain.com').then(results => {
    console.log(results);
  });
}
```

**Comment by patrickhulce** [comment]
That error just means that Chrome is not available on the port you said it should be on. This is not a bug in Lighthouse. Verify that Chrome is working correctly in your environment and exposed the correct DevTools port before trying to integrate Lighthouse with it.

FWIW, we've also seen really, really poor results with AWS lambda and burstable instance types even after one manages to get Chrome to run correctly there. If you have any other environment options, I'd definitely suggest going another route.
