### ISSUE TITLE
Speed index Calculation Issue

### ISSUE THREAD

**Issue by murali-krishnamoorthy** [GoogleChrome/lighthouse#10082]
Hi i have been running similar test in both webpagetest and PSI and i see a big difference in the speed index ( The intent is not to compare both the tools , but i am seeing big difference score ).
The webpagetest was run using the same bandwidth and RT as PSI Desktop based test . ( 10 MBPS , 40ms RTT ) 

Here is page that i am trying to test 
URL : https://www.thermofisher.com/order/catalog/product/1223-1000

When i run the test in PSI i get a speed score of 2.7 ( in-fact if i look at the images the screen is progressively getting loaded and the entire above the fold content is loaded in 3 seconds and the final screenshot captured in 3.8 seconds ) . Attached the PSI JSON 
[PSI JSON .txt](https://github.com/GoogleChrome/lighthouse/files/3940525/PSI.JSON.txt)

With the webpagetest i see a speed index of 1.8 where the entire above the fold content is loaded in around 4.5 seconds. 
Webpage Test Check : https://www.webpagetest.org/result/191209_H3_daa7325659ccdec9022e27f6664b6707/

**Comment by murali-krishnamoorthy** [comment]
Hi is there an update on this issue .

**Comment by patrickhulce** [comment]
Hi @murali-krishnamoorthy,

A difference of <1s for speed index is not very large and given these tests are being run in two completely different environments, even if the emulated connection settings are similar, this is fairly expected based on [natural variation](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md).

**Comment by murali-krishnamoorthy** [comment]
Hi @patrickhulce - The key question is not around the difference , the page that load slower in webpagetest compared to PSI has a better score . So i am not sure if PSI treats anything differently compared to WPT for speedindex calculation

**Comment by patrickhulce** [comment]
Ah gotcha! PSI does have a slightly different method of calculating speed index that blends a simulated Speed Index with the raw observation. It tracks the layout impacting events more closely than raw Speed Index does, so for this page the large layout jank at the end that doesn't affect the colors very much but greatly affects the layout impacts PSI's speed index moreso than WPT's.

Here is the implementation of the simulated speed index in Lighthouse:

https://github.com/GoogleChrome/lighthouse/blob/4c4f48817c2ea46071c97d3567e728cc42613b66/lighthouse-core/computed/metrics/lantern-speed-index.js#L107-L144
