### ISSUE TITLE
Random "Invalid dependency graph created, cycle detected"

### ISSUE THREAD

**Issue by chriswdmr** [GoogleChrome/lighthouse#10098]
#### Provide the steps to reproduce
I run LH programmatically from 6 different locations in parallel.
When I do that, all reports are correct and without any errors except for 1 or 2.
They show a "Invalid dependency graph created, cycle detected". This is very odd since all other tests/reports are passing.

URL which I tested: https://www.netlify.com

If needed, I can provide all 6 reports.

#### What is the current behavior?
Sometimes a random "Invalid dependency graph created, cycle detected" occurs.

#### What is the expected behavior?
No random "Invalid dependency graph created, cycle detected" errors

#### Environment Information
* Lighthouse version: 5.6.0
* Chrome version: 79.0.3945.0
* Node.js version: 10
* Puppeteer version: 2.0.0

**Comment by patrickhulce** [comment]
Thanks for filing @wolle404! Would you be able to provide the *trace* of one of these instances? The trace is `.trace.json` file produced by running from CLI with `--save-assets` or the file you open by clicking `View Trace` in DevTools.

**Comment by wolle404** [comment]
Hey @patrickhulce, I've created a gist with the report and the trace.

https://gist.github.com/wolle404/100a71ce6cf95b6a0257dd1ab9b6da8a

**Comment by patrickhulce** [comment]
Thanks very much for the gist @wolle404!

**Comment by patrickhulce** [comment]
Hm @wolle404 this is from one of the runs that failed? I'm not able reproduce that error with this trace and devtools log :/

**Comment by wolle404** [comment]
Hey @patrickhulce, yes that should be the correct trace.
The trace is extracted from the lighthouse function I call. I trigger lighthouse with/through puppeteer. 
I got each trace from `artifacts`:
```javascript
const { lhr, artifacts } = await createLighthouseReport(url)
```

Is this right? I can provide more data if needed.

I also created a repo with all reports and traces I get:
https://github.com/wolle404/lh-issue-10098

**Comment by rgembalik** [comment]
I see similar results when running inside an AWS lambda. The Page I am testing is some random shop - https://www.chewy.com/. This produces an Invalid dependency graph at least in half of the executions. The execution itself takes much longer than with other sites. Any idea of how could one prevent such errors from occurring? I do have reports and trace available (the trace is stringified JSON from artefacts). The trace is quite long, so I have no idea how to read it and extract any info from it on my own.

**Comment by patrickhulce** [comment]
@rgembalik do you still get this behavior with 5.6.0? Many of the cyclic graph errors were fixed between 4.3.1 and 5.6.0. 

If you do, would you be able to capture the `devtoolslog.json` in addition to the trace? I'd be happy to take a look at what's going on.

**Comment by wolle404** [comment]
I'm using ^5.6.0 in my app.

@rgembalik can you give an example how to get the `devtoolslog.json`?

Thanks!

**Comment by patrickhulce** [comment]
@wolle404 you provided both already I just couldn't reproduce the error message with the artifacts you gave me. I'll try again with your repo.

@rgembalik 's report was produced with 4.3.1 which is why I asked to try with 5.6.0.

**Comment by patrickhulce** [comment]
Ah, found your bug with one of your other traces thanks @wolle404! 🎉 PR incoming

**Comment by rgembalik** [comment]
@patrickhulce Unfortunately the issue persists. Still, there is a seemingly random chance of report being broken. I am including the results package. 

[invalid-dep-graph-chewy-5.6.0.zip](https://github.com/GoogleChrome/lighthouse/files/4138440/invalid-dep-graph-chewy-5.6.0.zip)

Could you, please, tell me how can I get `devtoolslog.json` from within the artifacts key? I am operating on the remote environment, so I have no possibility to launch the LH reporting via CLI.

**Comment by patrickhulce** [comment]
> Could you, please, tell me how can I get devtoolslog.json from within the artifacts key? 

it should be the value in `devtoolsLogs.defaultPass`

**Comment by rgembalik** [comment]
@patrickhulce Hey, sorry for the delay and thank you for hinting the correct key. Here's report + trace + devtoolsLog from the faulty test:
[invalid-dep-graph-chewy.zip](https://github.com/GoogleChrome/lighthouse/files/4146959/invalid-dep-graph-chewy.zip)
If I can do anything else to help to analyse this issue, please let me know.

**Comment by andrii-pukhalevych** [comment]
Also just got this:
LanternError: Invalid dependency graph created, cycle detected
    at PageDependencyGraph.createGraph (node_modules/@paulirish/trace_engine/models/trace/lantern/graph/PageDependencyGraph.js:481:19)
    at Module.createGraph (node_modules/@paulirish/trace_engine/models/trace/LanternComputationData.js:366:46)
    at #createLanternContext (node_modules/@paulirish/trace_engine/models/trace/Processor.js:255:46)
    at #computeInsights (node_modules/@paulirish/trace_engine/models/trace/Processor.js:458:53)
    at TraceProcessor.parse (node_modules/@paulirish/trace_engine/models/trace/Processor.js:122:38)
    at async TraceEngineResult.runTraceEngine (node_modules/lighthouse/core/computed/trace-engine-result.js:38:5)
    at async TraceEngineResult.compute_ (node_modules/lighthouse/core/computed/trace-engine-result.js:245:7)

**Comment by connorjclark** [comment]
@andrii-pukhalevych What Lighthouse version? What url? Also, please open new issues rather than bumping resolved ones: this issue was closed over 5 years ago.
