### ISSUE TITLE
Improvement of First Contentful Paint (FCP)  for the site

### ISSUE THREAD

**Issue by centuryweb01** [GoogleChrome/lighthouse#10092]
How to increase First Contentful Paint (FCP) and what are the steps to take for it

Please see the screen shot for the same
https://www.screencast.com/t/graeT6pm

Please suggest the best number for these points 
First Contentful Paint
Speed Index
Time to Interactive
First Meaningful Paint
First CPU Idle
Max Potential First Input Delay

**Comment by paulirish** [comment]
> How to increase First Contentful Paint (FCP) and what are the steps to take for it


https://web.dev/fcp/#how-to-improve-fcp


> Please suggest the best number for these points

these are what'd you need for a consistent score of 90:


    'first-contentful-paint': 2310,
    'first-meaningful-paint': 2310,
    'largest-contentful-paint': 2310,
    'speed-index': 3350,
    'estimated-input-latency': 57.8,
    'total-blocking-time': 283,
    'max-potential-fid': 129,
    'first-cpu-idle': 3530,
    'interactive': 3740
