### ISSUE TITLE
How to save assets in code

### ISSUE THREAD

**Issue by kimsangsoo** [GoogleChrome/lighthouse#10102]
const lighthouseRun = async (browser, url, exec) => {
  const opts = {
    logLevel: 'info',
    **saveAssets: true,**
    outputPath: "./",
    output: "html",
    port: new URL(browser.wsEndpoint()).port,
    throttlingMethod: "simulate",
    throttling: {
      rttMs: exec.latency,
      downloadThroughputKbps: exec.downloadThroughput / 1000,
      uploadThroughputKbps: exec.uploadThroughput / 1000
    }
  };

how to save devtools log and trace ??? and how to set directory

**Comment by patrickhulce** [comment]
Please see [the docs](https://github.com/GoogleChrome/lighthouse/tree/master/docs#differences-from-cli-flags). This flag is not used programmatically, use the `.artifacts` property as you need instead.
