### ISSUE TITLE
Lighthouse warming up forever

### ISSUE THREAD

**Issue by MacJSkinner** [GoogleChrome/lighthouse#10103]
Hi

Whenever i try to run a report in chrome using the lighthouse add in we only ever get "Lighthouse is warming up" Can someone tell me why?

Thanks

**Comment by alejagapatrick** [comment]
> Kumusta
> 
> Tuwing sinusubukan kong magpatakbo ng isang ulat sa chrome gamit ang parola idinagdag sa aming nakakuha lamang tayo ng "Nagpapainit ang Lighthouse" Maaari bang sabihin sa akin ng isang tao kung bakit?
> 
> Salamat

**Comment by exterkamp** [comment]
What OS and chrome version are you running?

**Comment by MacJSkinner** [comment]
Hi

Its windows 7 and Version 79.0.3945.79 (Official Build) (64-bit) of chrome.

Thanks


Macaulay Skinner
_______________
Infrastructure Systems Administrator
Group Technology & Change

Royal London Group, 1 Thistle Street, Edinburgh, EH2 1DG

**Comment by MacJSkinner** [comment]
This may help ☺

[cid:image001.jpg@01D5B35B.44AC0E20]

**Comment by exterkamp** [comment]
Okay, looking more at #9484 it is cross-OS and Windows 10 is on that thread, so I will de-dupe this issue into that one.

Also, side note: I doubt we'll support Win 7 specifically, as Microsoft is done supporting it as well. If we do solve the issue for Win 10, I don't think we'll look into Win 7 if it is still unsolved.

**Comment by MacJSkinner** [comment]
Ah ok that’s cool.

Yeah that’s fair enough hopefully it’s a little less OS based and it will work for both.

Let me know how you get on ☺

Thanks

Macaulay Skinner
_______________
Infrastructure Systems Administrator
Group Technology & Change

Royal London Group, 1 Thistle Street, Edinburgh, EH2 1DG

**Comment by MacJSkinner** [comment]
Hi

Have you guys gotten any further with this?

Thanks

Macaulay Skinner
_______________
Infrastructure Systems Administrator
Group Technology & Change

Royal London Group, 1 Thistle Street, Edinburgh, EH2 1DG

**Comment by Mavrick2020** [comment]
Doesn't work for me. 
Chrome: Google Chrome is up to date
Version 85.0.4183.83 (Official Build) (32-bit)
OS: Windows 10
Lighthouse:100.0.0.0
