### ISSUE TITLE
NaN/100 ;(

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/lighthouse#1010]
I guess it is due to first meaningful paint being `-Infinityms`. Any idea why?

I can reproduce with Chrome 54 (Stable) and Chrome 57 (Canary).

![screen shot 2016-11-22 at 2 37 18 pm](https://cloud.githubusercontent.com/assets/634478/20525777/475ea1a4-b0c1-11e6-8a72-e0af94ea47d9.png)

**Comment by ebidel** [comment]
Likely related to #890 and should be addressed when https://github.com/GoogleChrome/lighthouse/issues/618 is implemented.

Looks like the current implementation [looks for](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/first-meaningful-paint.js#L180) an event named `firstContentfulPaint`. I don't see that event in the trace list, but `firstMeaningfulPaint` is now there that m54 is out.

One run on https://airhorner.com/:

```
TracingStartedInPage
navigationStart
fetchStart
requestStart
responseEnd
unloadEventStart
unloadEventEnd
domLoading
requestStart
requestStart
domInteractive
domContentLoadedEventStart
domContentLoadedEventEnd
FrameView::performLayout
FrameView::performLayout
FrameView::performLayout
FrameView::performLayout
firstLayout
Paint
paintNonDefaultBackgroundColor
firstPaint
firstMeaningfulPaint
navigationStart
responseEnd
domLoading
domInteractive
domContentLoadedEventStart
domContentLoadedEventEnd
domComplete
navigationStart
fetchStart
responseEnd
domLoading
domInteractive
domContentLoadedEventStart
domContentLoadedEventEnd
domComplete
loadEventStart
loadEventEnd
FrameView::performLayout
FrameView::performLayout
firstLayout
requestStart
requestStart
domComplete
loadEventStart
loadEventEnd
requestStart
requestStart
requestStart
requestStart
requestStart
requestStart
requestStart
requestStart
requestStart
```

What's also interesting (and probably explains #890) is that another run of airhorner contained neither of these events:

```
TracingStartedInPage
navigationStart
fetchStart
requestStart
responseEnd
unloadEventStart
unloadEventEnd
domLoading
requestStart
requestStart
domInteractive
domContentLoadedEventStart
domContentLoadedEventEnd
navigationStart
responseEnd
domLoading
domInteractive
domContentLoadedEventStart
domContentLoadedEventEnd
domComplete
navigationStart
fetchStart
responseEnd
domLoading
domInteractive
domContentLoadedEventStart
domContentLoadedEventEnd
domComplete
loadEventStart
loadEventEnd
FrameView::performLayout
FrameView::performLayout
firstLayout
requestStart
FrameView::performLayout
FrameView::performLayout
FrameView::performLayout
FrameView::performLayout
firstLayout
requestStart
requestStart
requestStart
requestStart
requestStart
requestStart
requestStart
requestStart
domComplete
loadEventStart
requestStart
loadEventEnd
requestStart
```

In those cases, https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/first-meaningful-paint.js#L182 is never defined and we surface this in the report :(

**Comment by paulirish** [comment]
fixed in master
