### ISSUE TITLE
output raw html of the url

### ISSUE THREAD

**Issue by ashwin31** [GoogleChrome/lighthouse#10125]
Yes I am trying 5.6.0

This relate to chrome flags and I see no relevant flag to get raw HTML of the URL processed.

**Feature request summary**

I want to run custom metrics on the URL and don't want to hit the URL again to minimise load.
I need raw HTML processed by lighthouse to do that. 

Yes, but I am new to lighthouse development. I don't know where to modify the code, 

**What is the motivation or use case for changing this?**
I want to run other tests on the HTML of the URL for seo purposes like identifying keywords, H1 tags,.. etc.

**How is this beneficial to Lighthouse?**
It's already there, all I want to know is a flag to get it out.

**Comment by patrickhulce** [comment]
Use the `--save-artifacts` CLI flag and then look at the `MainDocumentContent` property of the `artifacts.json` file that is produced.

**Comment by ashwin31** [comment]
Thank you very much @patrickhulce got it.
