### ISSUE TITLE
can we get information about Safe Browsing

### ISSUE THREAD

**Issue by sravanthi97** [GoogleChrome/lighthouse#10140]
can we get the information about HTML Compression/GZIP, Safe Browsing, Server Signature, Directory Browsing in the lighthouse result?

**Comment by patrickhulce** [comment]
There are a lot of things in that list that don't seem necessarily related to me :)

> HTML Compression/GZIP

Lighthouse already covers this.

> Safe Browsing

As in, the site doesn't serve malware and isn't blacklisted by [Google's Safe Browsing list](https://safebrowsing.google.com/)? That seems like another level compared to Lighthouse as there's not really a chance a well-intentioned web developer just accidentally starts serving malware. There's also already a dedicated tool for it, so I'm not sure the cost of serving the entire blacklist in Lighthouse core is worth it. Seems like great territory for a Lighthouse plugin though if anyone thinks this is valuable :)

> Server Signature
> Directory Browsing

What do you mean by these? Please fill out the entirety of the [feature request issue template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Feature_request.md) if you'd like to suggest new features.
