### ISSUE TITLE
testing working on local but not web.dev or PageSpeed Insights API

### ISSUE THREAD

**Issue by Ayresmic** [GoogleChrome/lighthouse#10142]
Lighthouse is failing for www.petco.com on web.dev. and page speed insights API.

FALED_DOCUMENT_REQUEST

![image](https://user-images.githubusercontent.com/46111285/71428132-afc15900-2673-11ea-9399-6f6653cf9f8a.png)

![image](https://user-images.githubusercontent.com/46111285/71428170-f1520400-2673-11ea-8627-3e49c509cf5c.png)

Trying to do large scale production testing for lighthouse and struggling. 

The lighthouse testing works in my browser and CLI, but it doesn't scale.

Have to give up a computer to do the necessary testing volume and would prefer not to. 

Best, 

Mike

**Comment by connorjclark** [comment]
I've created a ticket in our internal bug tracker. We'll update this thread when we have more information.

**Comment by Ayresmic** [comment]
much appreciated, happy holidays!

**Comment by connorjclark** [comment]
doesn't repro anymore
