### ISSUE TITLE
Which one is True Lighthouse generated report from commandline or Google insight??

### ISSUE THREAD

**Issue by nik0811** [GoogleChrome/lighthouse#10144]
I am continuously working on the server-side to increase the google insight page speed, but each time I am seeing different report, I know there is a bug in the result of google insight, if not then at least It should be constant but know, there is a huge difference in the report generate by lighthouse command from terminal and google insights. I have wasted 2-3 days and night 😴 in analyzing the behavior and finally got  tired, I have done every thing possible from server side to boost the performance but nothing happening.

**Comment by stayshungry83** [comment]
Well I really couldn't tell you because there has a lot of strange
activities lately with my devices. So If you need more assistance with
anything, in would really appreciate it.

**Comment by nik0811** [comment]
The problem is at the end I will become culprit as the developer will not accept their fault from the code side as I have got even more than 75 scores on the mobile device from google insight and suddenly It got dropped to 23-32 and when I am using lighthouse command line It is showing nearby 45-50, On Gtmetrix am geting scores up to 77%.

**Comment by nik0811** [comment]
Need one help,

`#!/bin/bash

while true; do
        cd pagespeed/
        lighthouse  https://frontendpreprd.fullertonindia.com/ --chrome-flags="--headless" --view > /dev/null
        rm -rf *
done&
`
I am running even lighthouse in loop event the performance is varying each time ??

**Comment by connorjclark** [comment]
You should read this: https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md

**Comment by nik0811** [comment]
Thanks, Man at least I got few words which actually was revolving around my mind from your shared documents, but still the results are not as much appropriate when your client is completely dependent and reliable on google insight page score.

**Comment by nik0811** [comment]
Hey am closing this issues, as I have found the root cause of the problems am facing with my website, by applying lazy loading without releasing the static content actually solved our issues.
