### ISSUE TITLE
Audit errors (syntax, runtime) are being swallowed

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1015]
Add a syntax error to an audit:

<img width="556" alt="screen shot 2016-11-22 at 9 09 21 am" src="https://cloud.githubusercontent.com/assets/238208/20533728/65892448-b093-11e6-8001-44673687ddf8.png">

The console shows no errors and the errors are surfaced directly on the report:

<img width="450" alt="screen shot 2016-11-22 at 9 08 12 am" src="https://cloud.githubusercontent.com/assets/238208/20533683/43995920-b093-11e6-835d-f9401626e4c9.png">

**Comment by wardpeet** [comment]
@ebidel how would you want this to be fixed? eslint not building? or just keep throwing the error so the audit stops

**Comment by brendankenny** [comment]
closing in favor of #1512
