### ISSUE TITLE
Lighthouse for dynamic URLs.

### ISSUE THREAD

**Issue by FahdJamy** [GoogleChrome/lighthouse#10150]
**Summary**
I am trying to write a programmatic lighthouse function that can run on my authenticated pages.

These authenticated pages are also dynamic meaning URLs are the majority of my pages use a ProjectID.
Example URL: `http://localhost:3000/project/<projectId>/monitoring` the Id in the URL has to be a Valid one else this URL will fail.

How can I write a lighthouse function for this?????

**Note**
I am using puppeteer since lighthouse does not support running on authenticated pages out of the box.

Thanks.

**Comment by patrickhulce** [comment]
Thanks for filing @FahdJamy but this isn't really a Lighthouse question as much as it is a general programming question. You know your API for how to get a `projectId` to build that URL and Lighthouse wouldn't be involved in determining it. This step happens before Lighthouse. 

See the [authenticated pages docs](https://github.com/GoogleChrome/lighthouse/blob/a41b5727205d9c1c57bb6c9b1214cbc796a5be24/docs/authenticated-pages.md) for more on Lighthouse and you can refer to the [lighthouse-ci puppeteer docs](https://github.com/GoogleChrome/lighthouse-ci/blob/3a34a7b0a9f57b78ec1d5c1be5263262408c61fa/docs/cli.md#using-puppeteer-scripts) and [examples](https://github.com/GoogleChrome/lighthouse-ci/blob/master/scripts/ci-dogfood-get-urls.js) that do exactly what you're talking about.
