### ISSUE TITLE
Please look into the Issue, pagespeed version is 1.13.35.2

### ISSUE THREAD

**Issue by nik0811** [GoogleChrome/lighthouse#10152]
2019/12/27 20:59:01 [warn] 11262#13893: [ngx_pagespeed 1.13.35.2-0] [1227/205901:WARNING:unicodetext.cc(360)] Unicode value 0x90 is not valid for interchange
2019/12/27 20:59:01 [warn] 11262#13893: [ngx_pagespeed 1.13.35.2-0] [1227/205901:WARNING:unicodetext.cc(360)] Unicode value 0x81 is not valid for interchange
2019/12/27 20:59:01 [warn] 11262#13893: [ngx_pagespeed 1.13.35.2-0] [1227/205901:WARNING:unicodetext.cc(360)] Unicode value 0x90 is not valid for interchange
2019/12/27 20:59:01 [warn] 11262#13893: [ngx_pagespeed 1.13.35.2-0] [1227/205901:WARNING:unicodetext.cc(360)] Unicode value 0x81 is not valid for interchange
2019/12/27 20:59:01 [warn] 11262#13893: [ngx_pagespeed 1.13.35.2-0] [1227/205901:WARNING:unicodetext.cc(360)] Unicode value 0x90 is not valid for interchange
2019/12/27 20:59:01 [warn] 11262#13893: [ngx_pagespeed 1.13.35.2-0] [1227/205901:WARNING:unicodetext.cc(360)] Unicode value 0x90 is not valid for interchange

**Comment by connorjclark** [comment]
you want https://github.com/apache/incubator-pagespeed-ngx
