### ISSUE TITLE
error on scanning damettoluca.com

### ISSUE THREAD

**Issue by LucaTheHacker** [GoogleChrome/lighthouse#10164]
## Provide the steps to reproduce 
1. Run LH on damettoluca.com
2. Run LH on user.damettoluca.com

#### What is the current behavior?
```
Lighthouse returned error: INTERNAL: Extension result empty. Lighthouse calling Page.navigate with http://damettoluca.com/ Uncaught (in promise) Error: Extension timed out. No call to exit() before render timeout. at wrs.Extension.onTimeout_ (http://ghost-rider/devtools_script_api.js:5555:13) at http://ghost-rider/devtools_script_api.js:708:9 at Map.forEach (<anonymous>) at chromium.DevTools.Connection.dispatchMessage (http://ghost-rider/devtools_script_api.js:707:76) at chromium.DevTools.Connection.onJsonMessage_ (http://ghost-rider/devtools_script_api.js:689:65) at <anonymous>:1:40 
```
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://damettoluca.com/
Chrome Version: 79.0.3945.88
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@c2a58a36b9411c80829b4b154bfcab97e581f1f3/audits_worker/audits_worker_module.js:1268:229)
```
for damettoluca.com
and a normal result for user.damettoluca.com

#### What is the expected behavior?
LH should return my website infos and stats in damettoluca.com and user.damettoluca.com

#### Environment Information
* Affected Channels: All, also the one from google pagespeed insights
* Lighthouse version: latest (?)
* Chrome version: 79.0.3945.88 (official build) (64 bit)
* Node.js version: 12.14.0
* Operating System: windows 10 1909 64bit

**Comment by LucaTheHacker** [comment]
#cringe for that bot, the #6512 had problems just on his device, this one extends also on pagespeed insights, lol.

**Comment by exterkamp** [comment]
Page JS seems to be pausing devtools?

![image](https://user-images.githubusercontent.com/6392995/71654728-e2fd8b00-2cf8-11ea-8f8b-4a81d6179e19.png)

From a `setInterval` overload?

```javascript
setInterval(function() {
    var _0x3b8f6f = {};
    _0x3b8f6f[_0x1c61('0x4f')] = function(_0x3670d0) {
        return _0x3670d0();
    }
    ;
    _0x3b8f6f[_0x1c61('0x4f')](_0x5f5a7e); // Top of stack trace
```

Can't tell too much without a source map, but that `debugger` pausing seems to be causing LH to hang.

**Comment by LucaTheHacker** [comment]
Oh, okay, I've found the "error", the js code is encrypted to prevent dumping and re-use, so it stops the debugger. 
In that case I just should remove the anti-debug function from my code. 
Idk why it cannot load without executing in the normal way the js code and check just the website functionality.

**Comment by patrickhulce** [comment]
>  that debugger pausing seems to be causing LH to hang.

Hm @exterkamp I wonder why. That shouldn't be pausing at all since we `setSkipAllPauses`...

https://github.com/GoogleChrome/lighthouse/blob/648248e270deeef33e1b16b3420b43cc97230a97/lighthouse-core/gather/driver.js#L1346

**Comment by exterkamp** [comment]
@patrickhulce it might be that the pausing is hiding the underlying driver hang from us?

Are you saying that if I put a `debugger` in the console mid run it _shouldn't_ stop a run, because it seems to for me?

**Comment by LucaTheHacker** [comment]
> Are you saying that if I put a `debugger` in the console mid run it _shouldn't_ stop a run, because it seems to for me?

The problems is that I've used a system to stop debuggers, so it's normal that he cannot execute the debugger.

**Comment by patrickhulce** [comment]
> Are you saying that if I put a debugger in the console mid run it shouldn't stop a run, because it seems to for me?

I'm saying if the page has a regular `debugger` statement in the middle of a run, Lighthouse should not pause for it. If a user action in console injects a debugger statement, that's probably a different story (it'd be smart of DevTools to re-enable pauses if the user adds a debugger statement like that for example, so maybe that's happening?) 

Now it sounds like @LucaTheHacker's approach is specifically to spam and lock up DevTools whenever it's inspected, so I'd think all bets are off there.

> Idk why it cannot load without executing in the normal way the js code and check just the website functionality.

 Because in order to tell you *debug* information about the page like Lighthouse does, we need to *debug* the page! 😉

**Comment by connorjclark** [comment]
Lighthouse requires Devtools debugging to work on a page. Don't attack debuggers and Lighthouse will work for you.
