### ISSUE TITLE
Page Speed Insights returns ERRORED_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by naveenrajbu** [GoogleChrome/lighthouse#10169]
my site: http://ezyleads.in shows  
Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests.
but my website works fine and it doesn't show any error if I use http://ezyleads.in/index.php, I developed it with CodeIgniter. 
Help me out here.

**Comment by naveenrajbu** [comment]
necessarily-wide-alpaca

**Comment by patrickhulce** [comment]
I'm not able to reproduce this issue. 

![image](https://user-images.githubusercontent.com/2301202/71732332-9acf8d00-2e0c-11ea-8287-a0a3260373f4.png)

![image](https://user-images.githubusercontent.com/2301202/71732440-e1bd8280-2e0c-11ea-8291-6a292d75bb6d.png)



Note that as #2784 describes, this error message will appear if the server fails to respond or responds with an error, if this error is intermittent it might indicate that the server has intermittent load or geo-based failures.

**Comment by naveenrajbu** [comment]
> I'm not able to reproduce this issue.
> 
> ![image](https://user-images.githubusercontent.com/2301202/71732332-9acf8d00-2e0c-11ea-8287-a0a3260373f4.png)
> 
> ![image](https://user-images.githubusercontent.com/2301202/71732440-e1bd8280-2e0c-11ea-8291-6a292d75bb6d.png)
> 
> Note that as #2784 describes, this error message will appear if the server fails to respond or responds with an error, if this error is intermittent it might indicate that the server has intermittent load or geo-based failures.

I used DirectoryIndex index.php and the error stopped I exactly don't know why that happened in Godaddy hosting I had no problem running it in other hostings. But thank you for your effort
