### ISSUE TITLE
LH runs into infinite loop while analyzing

### ISSUE THREAD

**Issue by dominiklenne** [GoogleChrome/lighthouse#10165]
#### Provide the steps to reproduce
1. Run LH on <https://astiko.de/>
  

#### What is the current behavior?

Analysis running since 5+ minutes.
Progress indicator in progress bar on top is jumping back and forth.
accessibility and best practices analyses are finished.
Performance analysis shows red "error" hints all over the place.

#### What is the expected behavior?

Finish analysis with some kind of meaningful output within 2 minutes or so.

#### Environment Information
* Affected Channels: DevTools (Lighthouse installed as standalone extension works well)
* Lighthouse version: 5.5.0
* Chrome version:  79.0.3945.88
* Node.js version: n/a
* Operating System: Windows 10

**Related issues**

**Comment by patrickhulce** [comment]
Thanks very much for filing @dominiklenne! 

I'm able to reproduce this on stable Chrome (it seems to get into an infinite redirect loop), but it seems to already be fixed in Chrome Canary and from the latest CLI. Current Lighthouse should make its way to stable in the coming weeks (~Feb 4 [it seems](https://chromiumdash.appspot.com/schedule))

**Comment by dominiklenne** [comment]
Happy to read this , thx.

Von: Patrick Hulce 
Datum: Donnerstag, 2. Januar 2020 16:25
An: GoogleChrome/lighthouse 
Cc: dominiklenne ; Mention 
Betreff: Re: [GoogleChrome/lighthouse] LH runs into infinite loop while analyzing (#10165)

Thanks very much for filing @dominiklenne!

I'm able to reproduce this on stable Chrome (it seems to get into an infinite redirect loop), but it seems to already be fixed in Chrome Canary and from the latest CLI. Current Lighthouse should make its way to stable in the coming weeks (~Feb 4 it seems)
