### ISSUE TITLE
font-display swap is not detected correctly

### ISSUE THREAD

**Issue by georgeboot** [GoogleChrome/lighthouse#10178]
#### Provide the steps to reproduce
1. Run LH on https://boxoffice.computicket.com/events/15d30cbb-9492-40b9-b09d-a1e33ef720c5
  
#### What is the current behavior?
Lighthouse reports ` Ensure text remains visible during webfont load`.

#### What is the expected behavior?
Since the page is using Google Fonts with `&display=swap`, it should pass this test.

#### Environment Information
Test was ran using https://web.dev/measure/ (`Generated by Lighthouse 5.6.0`)

**Comment by patrickhulce** [comment]
Thanks for filing @georgeboot!

You have two Google Font stylesheets on that page, one of them is using `font-display: swap` but the other is not.

![image](https://user-images.githubusercontent.com/2301202/71833089-e20a8780-3071-11ea-84e6-2ffbc14c7853.png)

**Comment by georgeboot** [comment]
Ahh thanks @patrickhulce!

The support widget we use (Groove) does that. It doesn't show on my dev env, hence I didn't notice.
