### ISSUE TITLE
Report: some DBW best practices should be "recommendations"

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1017]
Some of our best practices are fairly new or subjective (single use event listeners, no `Date.now()`). Instead of listing all of these under "Best Practices", it would be nice to have a new section of "Recommendations" or "Things to look at".

**Comment by sandstrom** [comment]
Agree, `Date.now()` has many legitimate uses (it's an easy way to grab the unix time, for date calculations).

Current:

> Site does not use Date.now() in its own scripts

Suggestion:

> Site does not use Date.now() to time page-loading (it's alright to use it for time/date calculations).

**Comment by paulirish** [comment]
The Date.now() audit in particular is pretty controversial, as a lot of its use is not for measuring durations but getting wall time. I would favor moving the date.now check out of the default config in the meantime.

**Comment by brendankenny** [comment]
Even the current string is reported too strongly. I think the initial motivation for this sort of thing was that it would be nice to have a section of the report that just alerted you to new APIs that you could (not necessarily should) be using.

Rather than **Best Practices**, it could be under **Fancy-pants Stuff That Could Help You Out, Read These Links**

**Comment by ebidel** [comment]
Agreed. Many of the DBW suggestions will be future facing for most users, for some time. But they're meant to raise awareness of newer stuff.

Better labeling is probably the way to go, rather than removing audits. It shouldn't be too hard to regroup things and create a new aggregate.

**Comment by ebidel** [comment]
I can prioritize this before the next release if we feel strongly about it.

**Comment by ebidel** [comment]
How do we feel about this:

<img width="1053" alt="screen shot 2016-11-30 at 11 53 30 am" src="https://cloud.githubusercontent.com/assets/238208/20768676/a4a1a1a8-b6f3-11e6-9521-71d5d2b0bd35.png">
