### ISSUE TITLE
Lighthouse Extension Error

### ISSUE THREAD

**Issue by MichaelBrimer** [GoogleChrome/lighthouse#1018]
**Lighthouse Version**: 1.2.0
**Chrome Version**: 54.0.2840.99
**Error Message**: {"code":-32000,"message":"Result of the evaluation is not a promise"}
**Stack Trace**:
 ```undefined```

**Comment by patrickhulce** [comment]
duplicate #966

**Comment by MichaelBrimer** [comment]
Running an Angular 2 app, all chrome extensions except Lighthouse are deactivated
