### ISSUE TITLE
Lighthouse Extension Error

### ISSUE THREAD

**Issue by wfortin** [GoogleChrome/lighthouse#1019]
Trying to test my application I get this error with the chrome extension.
**Lighthouse Version**: 1.2.0
**Chrome Version**: 54.0.2840.98
**Error Message**: {"code":-32000,"message":"Result of the evaluation is not a promise"}
**Stack Trace**:
 ```undefined```

**Comment by wfortin** [comment]
Looks like a duplicate of #1000 though ?

**Comment by brendankenny** [comment]
> Looks like a duplicate

yes. We'll try and get a patch release out today so this'll be less of an issue (#1000 may have to wait, though)
