### ISSUE TITLE
Integration with Chrome Devtools Coverage

### ISSUE THREAD

**Issue by jackyef** [GoogleChrome/lighthouse#10195]
[Chrome Devtools Coverage](https://developers.google.com/web/tools/chrome-devtools/coverage)

**Summary**
Is it possible for to make lighthouse integrate with Chrome Devtools Coverage?
Basically, this is how I imagine it would be:
1. Run lighthouse against an url, like usual
2. Along with the usual outputs, lighthouse will also output a coverage.json from Chrome devtools
3. Lighthouse can use this information to show the unused codes in each assets in its report
4. Bonus: Lighthouse could show a visualisation from the coverage json using available source map (if exists), like what [source-map-explorer](https://github.com/danvk/source-map-explorer/releases/tag/v2.2.0) did recently.

I couldn't find if it's actually possible currently to do this. Apologies if it already exists 🙏

**Comment by connorjclark** [comment]
We have the `unused-javascript` audit, which shows how much code is unused. It's not granular yet, but #10090 is working on that.

re: 4- #10064 is a preview of what we're doing with source maps. We have a working demo for using `source-map-explorer`, with plans to show coverage data too.

**Comment by jackyef** [comment]
Whoa, that is awesome! Can't wait to see it live!
