### ISSUE TITLE
Lighthouse - Accessibility report - works on which web guideline

### ISSUE THREAD

**Issue by Babban22** [GoogleChrome/lighthouse#10202]
**Summary**

Need to know accessibility report generated by lighthouse 5.5.0 works on what web guidelines and level
Example is it give result based on (Web Content Accessibility Guidelines) WCAG 2.1 AA level guideline?

**Comment by patrickhulce** [comment]
The accessibility category uses the [axe rules](https://dequeuniversity.com/rules/axe/3.4) that are tagged with `wcag2a` or `wcag2aa` with a [few modifications](https://github.com/GoogleChrome/lighthouse/blob/ff87d69d6378ad69116574ec537ab649f302cd66/lighthouse-core/gather/gatherers/accessibility.js#L34-L47). 

The relationship of each audit to WCAG guidelines is covered in the `Learn More` link that accompanies each. Example below.

![image](https://user-images.githubusercontent.com/2301202/72082217-6dc82200-32c5-11ea-8b89-5727e242ee58.png)


Note that no *fully* automated accessibility test will guarantee *complete* conformance with any useful set of accessibility guidelines.

**Comment by Babban22** [comment]
Many Thanks @patrickhulce , could you please help me to know where we can see Compliance data and impact? I checked learn more link but found other details with absent Compliance data and impact details

**Comment by patrickhulce** [comment]
@Babban22 ah if you're using latest Lighthouse and the Learn More links are taking you to `web.dev` you can click on the "(Deque University)" link at the bottom of the page to see the data I'm talking about in that screenshot.

**Comment by Babban22** [comment]
Many Thanks @patrickhulce
