### ISSUE TITLE
consider attaching log to generated issue reports

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1020]
In #966 it was the hand-copied log that was most useful in diagnosing the problem, and even more helpful in realizing there was a bigger problem with polyfills (#1000).

It would be relatively easy to add some sort of circular buffer (maybe truncating messages) to [`log.js`](https://github.com/GoogleChrome/lighthouse/blob/fcf697c8655c129a079977e80770726d39673cc9/lighthouse-core/lib/log.js) and then have the error handler in the extension copy it to the generated issue.

Are there downsides here? For privacy for whatever site was being tested, we would probably want to elide `--verbose` messages with actual trace or network data, but results returned by protocol commands may be trickier since they may private stuff but also may be essential to debugging whatever issue is at hand. At the very least we could log what command was issued and if it returned with error or not.

Alternatively we could make the issue reporting process slightly more complicated by having a checkbox that opted in to attaching the log.

**Comment by addyosmani** [comment]
To subvert concerns about privacy, I wonder if we could model this around the way Chrome currently handles submitting error reports (note `Send system information`).

![](https://i.imgur.com/FgBFP3K.jpg)

The user is given fields that are either populated or free-form to add in their details which Lighthouse could probably include details of, including a checkbox for uploading log information or URLs. We'd probably need a privacy statement of some sort just in case sensitive info was included in the trace.

We could go granular and say "Include trace and network data (may reference URLs)" or similar for anything we needed that couldn't be sanitized. We can then post a new GitHub issue filling in a template with an inlined report or similar.

**Comment by wardpeet** [comment]
@brendankenny @ebidel is still relevant? Looks like we get enough info from extension

**Comment by ebidel** [comment]
Yea I think we can close. The stacktrace and URL are helpful and when we need more info, users are providing it :)
