### ISSUE TITLE
Can't get Lighthouse to work on my site - PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by liebbe10** [GoogleChrome/lighthouse#10219]
I'm trying to test my site https://www.jungelinke.at/ with chrome and the Lighthouse report system, but I get no results. After reaching 50-60% it slows down and after a while I get an error message. When using the Google PageSpeed Insights Website I also only get results for the mobile version (and they are very poor). I tried to follow some optimization guides but the score didn't really increase much...
If anybody could help me, I would appreciate it a lot!

Greetings Ben

**Comment by connorjclark** [comment]
Can you try removing the `debugger` statements?

**Comment by patrickhulce** [comment]
Deduping into #6512
