### ISSUE TITLE
Were any changes made between 10/15/2019 and 11/19/2019 that would have affected Google PageSpeed Scores?

### ISSUE THREAD

**Issue by jayeshkataria** [GoogleChrome/lighthouse#10226]
**Summary** 
Hello, we wanted to find out if any changes were released between 10/15/2019 and 11/19/2019 that might have affected [Google Pagespeed Insight](https://developers.google.com/speed/pagespeed/insights/) Scores? There's a single release of lighthouse v5.6.0 on 10/17/19. However, we saw between these 2 dates that pagespeed scores for few of our tracked pages increased and got really spiky, and settled again to previous levels after 11/19. Below are 2 graphs that display what changed:

**Individual Scores**
<img width="1078" alt="Screen Shot 2020-01-14 at 4 21 29 PM" src="https://user-images.githubusercontent.com/2548093/72383853-51275200-36ea-11ea-92ad-17e404fc905c.png">

**Average Scores**
<img width="921" alt="Screen Shot 2020-01-14 at 4 20 47 PM" src="https://user-images.githubusercontent.com/2548093/72383828-410f7280-36ea-11ea-9ea9-1736a1e7a50b.png">

We're trying to investigate these spikes and wanted to see if any changes in Lighthouse or Google PageSpeed around this time might have contributed to this. Any help or pointers would be greatly appreciated!

Thanks!

**Comment by exterkamp** [comment]
Yup! There was an underlying networking issue that happened during that period, here is the post mortem: https://github.com/GoogleChrome/lighthouse/issues/9902#issuecomment-556414195

**Comment by jayeshkataria** [comment]
This explains it... thanks a lot @exterkamp !
