### ISSUE TITLE
FP and FCP from lighthouse are not equal to ones from PerformanceNavigationTiming API

### ISSUE THREAD

**Issue by xuchaobei** [GoogleChrome/lighthouse#10235]
#### Provide the steps to reproduce
1. Run Chrome devtools Audit on www.google.com  (Select **No throttling**)

2. The result is as below. FP and FCP are both 0.6s.
![image](https://user-images.githubusercontent.com/5110783/72505436-e35e6000-387a-11ea-994d-0fce3c495774.png)

3. Switch to the console tab of current Chrome devtools.  Use `PerformanceNavigationTiming`
API  to get FP and FCP，the result is as below.  FP and FCP are both 287ms.
![image](https://user-images.githubusercontent.com/5110783/72505784-962ebe00-387b-11ea-8d7a-f1b359cae56f.png)

#### What is the current behavior?
FP and FCP from lighthouse are not equal to ones from `PerformanceNavigationTiming`
API.

#### What is the expected behavior?
FP and FCP from lighthouse should be equal to ones from `PerformanceNavigationTiming`
API.

#### Environment Information
* Affected Channels:  DevTools
* Lighthouse version: 5.5.0
* Chrome version: 79.0.3945.117
* Node.js version:  v10.15.3
* Operating System: MacOS Catalina (10.15.2)

**Comment by patrickhulce** [comment]
Thanks for filing @xuchaobei! 

The "No throttling" option has been removed from DevTools in the latest version and I'm not able to reproduce the issue with the CLI.

Also note that the page is reloaded after being analyzed from DevTools so the performance timings you'll read from the console are from a different page load than the one analyzed by Lighthouse and some variation is to be expected. (~300ms is easily within the realm of possibility for server times to vary)

**Comment by xuchaobei** [comment]
@patrickhulce I did't notice that the page would be  reloaded after  being analyzed from DevTools. That should be the reason. Thanks for your explaination!
