### ISSUE TITLE
aria-toggle-field-name doc link 404's

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#10243]
> lighthouse-core/audits/accessibility/aria-toggle-field-name.js

```javascript
...
  description: 'When a toggle field doesn\'t have an accessible name, 
screen readers announce it with a generic name, making it unusable 
for users who rely on screen readers. 
[Learn more](https://web.dev/aria-toggle-field-label/).',
...
```

[https://web.dev/aria-toggle-field-label](https://web.dev/aria-toggle-field-label/) is broken, should be [https://web.dev/aria-toggle-field-name/](https://web.dev/aria-toggle-field-name/).

**Comment by wardpeet** [comment]
This looks like to be covered, thanks @msomji
