### ISSUE TITLE
Roll 6.0 to DevTools

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10241]
- [x] Roll 6.0
- [x] Use Moto G4 ([code](https://source.chromium.org/chromium/_/chromium/devtools/devtools-frontend/+/b5315e84d143e54e0238299709f208d36e4b4e57:front_end/audits/AuditsPanel.js;l=349;drc=51474196c064bb27ace486155996ba7405161f16?originalUrl=https:%2F%2Fcs.chromium.org%2F))
- [x] set flags that were removed in entry https://github.com/GoogleChrome/lighthouse/commit/0f600e0cd3b6f1bd8be10d5b4ede9edcfc4940fb#diff-e599d8b0b3dc3216321f22cfd73e3659

**Comment by Ornhoj** [comment]
Are there any news regarding the ETA 6.0 implementation in DevTools?

**Comment by connorjclark** [comment]
We're hoping to release 6.0 in the next two weeks. It'll be in Chrome Canary shortly after landing in npm. Watch this issue for the exact moment :)

**Comment by connorjclark** [comment]
> We're hoping to release 6.0 in the next two weeks.

ahhhh, and of course priorities changed, as they tend to. truly, we plan on releasing 6.0 in a month. in the meantime, we have a beta release on npm.

**Comment by paulirish** [comment]
CL is ready: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2197239
