### ISSUE TITLE
Lighthouse incorrectly reports that Lo-Dash is being used on a website

### ISSUE THREAD

**Issue by alexmahan** [GoogleChrome/lighthouse#10240]
## Provide the steps to reproduce
Unfortunately, the Shopify page is currently password-protected, but when I run a Lighthouse audit on the Shopify site in an Incog window, it says that Lo-Dash 4.5.1 has a security vulnerability. I'm not using Lo-Dash anywhere, so not sure why Lighthouse is saying this. See attached screenshot for behavior. Incidentally, in Dark Mode, the link to Lo-Dash is unreadable because it's blue on a black background.

#### What is the current behavior?
Under the "Best Practices" tab, Lighthouse indicates that the site "Includes front-end JavaScript libraries with known security vulnerabilities 4 vulnerabilities detected" and says that Lo-Dash 4.5.1 is the culprit. However, Lo-Dash is used nowhere on the site and isn't being imported by any code. 

#### What is the expected behavior?
No JS libraries with security vulnerabilities should be detected by Lighthouse.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.6.0? Not sure where to check.
* Chrome version: 79.0.3945.130
* Operating System: MacOS 10.14.6

<img width="555" alt="Screen Shot 2020-01-20 at 3 48 46 PM" src="https://user-images.githubusercontent.com/140830/72765816-1d916f80-3ba3-11ea-9007-61cb510a3a8e.png">

**Comment by patrickhulce** [comment]
Thanks for filing @alexmahan! Some third-party (even Shopify possibly?) is probably adding lodash without your knowledge. This only fires if `_` is in global scope with the `chain` method on it that wraps a value with a `__wrapped__` property, which is very lodash specific.

See detection code. 
https://github.com/johnmichel/Library-Detector-for-Chrome/blob/357a4d49c6a177ca7df853160e270cd77beb7140/library/libraries.js#L600-L609

If you're very confident this isn't the case, the false lodash detection is reproducible with just [Library Detector for Chrome](https://chrome.google.com/webstore/detail/library-detector/cgaocdmhkmfnkdkbnckgmpopcbpaaejo?hl=en), and you're able to produce a publicly available example, an issue upstream to get resolved would be very much appreciated by that team I'm sure :) ([repo link](https://github.com/johnmichel/Library-Detector-for-Chrome))

**Comment by alexmahan** [comment]
Thanks for the update @patrickhulce. Will use library detector and see what I can find. Shopify actually looked at it and said they couldn't detect it, and they're not adding it anywhere, so I'll let you know if it's giving a false positive. Once the site is launched, it will be publicly available for easier debugging.

**Comment by remibergsma** [comment]
Hi alexmahan, did you find the cause of this? I'm hitting the same issue. Reported to use Lo-dash `4.5.1` but can't find it in the source. Also on Shopify. Thanks!

**Comment by alexmahan** [comment]
@remibergsma Unfortunately, I just let it be because I couldn't solve it, either at the Shopify end or the Lighthouse end. Disappointing that this is still an issue.

**Comment by remibergsma** [comment]
Thanks @alexmahan for your quick response. Too bad it was never found and fixed. I'll see if I can find any more hints else I'll also let it be ;-)

**Comment by samkirkbride-wonderagency** [comment]
Hi @alexmahan and @remibergsma 

I don't know if you are both still having this issue, but I was having the same problem, but I believe I was able to resolve it. 

My Shopify website is using the "debut" theme, and while I couldn't find any direct references to Lodash in any of the theme files, when I searched my theme files for the version number (4.5.1), I was able to find it in my vendor.js file included with the theme. 

The code that was near this was on the same line as a library called "Zoom". More details of which can be found about Zoom here: http://www.jacklmoore.com/zoom

Looking through the Zoom library code, I saw no references to lodash, but I found the end of the Zoom code ended before the lodash version number that I had previously found on the same. 

For reference, the end of the Zoom code is `e.fn.zoom.defaults=t}(window.jQuery)`

While I can't confirm 100%, the code following this looks very similar to the lodash core minified js. I have replaced the code with the latest version of lodash (https://cdn.jsdelivr.net/npm/lodash@4.17.21/core.min.js) and I no longer get the vulnerability notice from the lighthouse report. 

I am currently checking to see if the change has had any negative effect on my website, but so far so good.

**Comment by alexmahan** [comment]
Interesting, thanks @samkirkbride-wonderagency! Pretty sure my wife used Zoom on the Shopify site she built, so will check and see if that needs updating.

**Comment by ddrnero** [comment]
Hey Guys!

I have updated the Zoom Code with the following: https://cdnjs.com/libraries/jquery-zoom/1.6.1.
Give it a Try, it worked for me ;-) .

Kind Regards

**Comment by ddrnero** [comment]
Newest Version: https://cdnjs.cloudflare.com/ajax/libs/jquery-zoom/1.7.21/jquery.zoom.js

**Comment by erickadalberto** [comment]
[](https://github.com/GoogleChrome/lighthouse/tree/8efad1d24d0a4ee9cf8d881ad7d3727ea7bbbccc)

**Comment by erickadalberto** [comment]
https://github.com/GoogleChrome/lighthouse/tree/8efad1d24d0a4ee9cf8d881ad7d3727ea7bbbccc
