### ISSUE TITLE
LHR dings 12 points giving 88/100 for just 0.15s in estimated savings

### ISSUE THREAD

**Issue by anuragphadke** [GoogleChrome/lighthouse#10268]
1. Run LH on https://beta.webfast.co/computertechsupp-com/home-computer-repair.html

#### What is the current behavior?
The page is AMP compatible and loads pretty fast, expectation was a 90+ score
#### What is the expected behavior?
LHR's suggestion is to properly size image, there's only one image with estimated saving of 0.15sec, but it dings 12 points for this one, giving a 88/100 score

#### Environment Information
* Lighthouse version:  5.6.0
* Chrome version: Using LHR on https://web.dev/measure

**Related issues**
#8932

**Comment by patrickhulce** [comment]
> there's only one image with estimated saving of 0.15sec, but it dings 12 points for this one, giving a 88/100 score

The opportunities do not count for any points. The score is purely based on the metrics, and while following the suggestion for the image would indeed improve the score a little for the 0.15s savings, the primary reason the score is low is for late paints (FCP, FMP, SI, LCP) requiring a half dozen or so AMP javascript files which are unrelated to this image.

![image](https://user-images.githubusercontent.com/2301202/73139697-4b106a00-4036-11ea-8987-ef87a6ff5e95.png)

88 is still a good score, but usage of more AMP components does have the potential to push into the low 90s or high 80s like in this case.

**Comment by anuragphadke** [comment]
@patrickhulce : thx for the above, super helpful to understand how LHR computes the scores.
question: How did you generate the above image? I tried playing around with developer tools  (performance tab) but wasn't able to generate one.

**Comment by anuragphadke** [comment]
nm, found it, it's under Performance => Network.
