### ISSUE TITLE
Energy consumption / battery life metrics?

### ISSUE THREAD

**Issue by ehmprah** [GoogleChrome/lighthouse#10269]
I'd like to see metrics regarding the energy consumption and battery usage and maybe even respective savings. Speed and a high performance score might correlate with low energy consumption and this somewhat fuzzy metric probably spans across audits or even categories, but I'm missing it all the same.

**Comment by patrickhulce** [comment]
Thanks for filing @ehmprah! If you'd like to see new battery life audits in Lighthouse would you mind filing out the [new audit proposal questionnaire](https://github.com/GoogleChrome/lighthouse/blob/master/docs/new-audits.md) about how it differentiates from performance metrics? 

Unless we see a completed proposal we'll likely close for the same [reasons given previously](https://github.com/GoogleChrome/lighthouse/issues/490#issuecomment-259230186).

**Comment by connorjclark** [comment]
My thoughts are here- https://github.com/thegreenwebfoundation/lighthouse-plugin-greenhouse/issues/7

**Comment by ehmprah** [comment]
I don't think that a completely new category makes sense for metrics that are mostly handled in the performance audit anyway. 

Adding two more audits under performance makes sense though: one showing memory usage (would be interesting regardless of sustainability) and one showing battery usage as per @connorjclark's suggestion.

I'd love for this to be a metric under performance, but I do realize it's hard to measure or compare – as opposed to values like TTI. Maybe it would be interesting to take a few seconds after TTI and measure how much CPU time, memory and battery we use then. It's probably is a bit atypical for Lighthouse, but would help identify usability and performance issues caused by badly written frontend code. If that would be an option, the whole "Energy Consumption" might deserve to be an audit in and of itself. Either way I think ...

- measuring memory and battery would make Lighthouse more informative and useful
- it would increase awareness for energy consumption and a sustainable web
- it would improve battery life for mobile devices
- it might improve front-end performance after TTI

As such, I'd boldly say this would a lot of developers; at least everyone who's interested in mobile performance and battery life.

**Comment by sirdmon** [comment]
@ehmprah 
Knowing the importance of today of auditing sustainability practices on the web, I have released [DAS](https://github.com/digital-audits/sustainability) that measures the energy consumption of a given page, among other things that shares with LH. 

So far, the algorithm oversimplifies it a bit by taking on the page transfer size and also on server-side considerations like the energy source for computing the kWh metric, but surely it might be a start point for putting sustainability right on the web.

Give it a try, I'll be glad to hear your feedback.

**Disclaimer**
Needlessly to say that I'm the founder.

**Comment by patrickhulce** [comment]
> Unless we see a completed proposal we'll likely close for the same reasons given previously.

We haven't seen a completed proposal here, so we're going to close for now, but if someone is passionate here with a complete proposal go for it and we'll reopen :)

In general, we're more open to the idea of battery life metrics for user experience reasons as the impact for overall sustainability is smaller (see https://github.com/thegreenwebfoundation/lighthouse-plugin-greenhouse/issues/7)
