### ISSUE TITLE
Extension Error: Unexpected token C in JSON at position 0

### ISSUE THREAD

**Issue by MGrin** [GoogleChrome/lighthouse#1026]
**Lighthouse Version**: 1.2.1
**Chrome Version**: 53.0.2785.143
**Error Message**: Unexpected token C in JSON at position 0
**Stack Trace**:
 ```SyntaxError: Unexpected token C in JSON at position 0
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:8113:31)```

**Comment by brendankenny** [comment]
Not sure if this is the cause of the issue, but we require at least Chrome 54 (current stable version)
