### ISSUE TITLE
Repeatedly getting score of 0 for performance in Page Speed Insights

### ISSUE THREAD

**Issue by zacknotes** [GoogleChrome/lighthouse#10264]
For this page:

https://aarrowsignspinners.com/

And using this tool:

https://developers.google.com/speed/pagespeed/insights/

I repeatedly get a score of 0 

I am reporting this as a bug according to the instructions here: 

https://developers.google.com/web/tools/lighthouse/v3/scoring

"If you see a 0 score repeatedly, please file a bug on the Lighthouse repo"

**Comment by connorjclark** [comment]
I get a zero from Chrome DevTools too, so this isn't an issue with PSI (which we do have). You'll have to follow the advice given in the report to get a score higher than zero.

**Comment by patrickhulce** [comment]
Confirmed this page legitimately receives a 0 performance score. For additional context, those docs are for v3 which handled errors by assigning a score of `0`. In PSI and current Lighthouse (v5) you'll see a `?` for the score instead of a 0 for the case where we'd appreciate a bug report.

**Comment by zacknotes** [comment]
OK, thank you Patrick for confirming.

I like the ? solution

Cheers!

-Zack
