### ISSUE TITLE
Double-Dollar assertion is overly aggressive

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#10285]
The double dollar assertion: https://github.com/GoogleChrome/lighthouse/blob/e87a8b76e66208be0266c6e3a3b648dbebe79521/lighthouse-core/scripts/i18n/collect-strings.js#L344

Is a bit aggressive, it should check for basic `$$` but allow `$ICU_0$$ICU_1$`. This should be validated with regex like `\$([^$]*?)\$` and asserting that each capture group isn't empty instead of a more basic `\$\$`.

**Comment by connorjclark** [comment]
"good first issue" what is this even

**Comment by patrickhulce** [comment]
Wait yeah if Connor and I both have no clue what this is talking about this is gotta be "good shane-only issue" ;)

**Comment by piotrzarycki** [comment]
soo, it's possible to take care of it? :P

**Comment by connorjclark** [comment]
@piotrzarycki go for it. work involved is indeed "good first issue" assuming it is just doing what Shane said.

**Comment by exterkamp** [comment]
Sorry. From the Chromium slack:

> Oh, hm. I think this is an overly aggressive assertion. We are trying to catch "$$" as an escape sequence for "$". So something like "$5.00" being escaped as $$5.00 leads to a problem because that "placeholder" is empty and causes issues. But, as I read the internal comment on this check, it specifically calls out adjacent placeholders as valid like $ICU_0$$ICU_1$ . This is actually an error with the naive check in Lighthouse.

So, this test in Lighthouse is checking for `$$` naively, when it really needs to be checking for `$$` but not `$ICU_0$$ICU_1$` which is valid.
