### ISSUE TITLE
How to fix 'Eliminate render blocking resource' in Lighthouse Audit

### ISSUE THREAD

**Issue by sathyamahes** [GoogleChrome/lighthouse#10287]
I was trying to fix the 'Eliminate render blocking issue' from Lighthouse audit for my web application.I have read from many articles about defer and async as the solution for this warning. I had tried it both but still nothing helps me to increase my app's performance. I am still finding the same warning.

Following are the different way I have tried so for:

```
<link rel="stylesheet" href="https://example.com/v2/_assets/css/theme.css" media="all" async>
<link rel="stylesheet" href="https://example.com/v2/_assets/css/theme.css" media="all" defer>
<link rel="prefetch" href="https://example.com/v2/_assets/css/theme.css" media="all" as="style">
<script src="https://example.com/v2/sample.js" defer>
```

Is there anything i have missed out? Can anyone help me to get out solution for this? 

Thanks in advance:)

**Comment by patrickhulce** [comment]
`defer` and `async` are for scripts, not stylesheets. The [web.dev docs explain how to defer CSS](https://web.dev/defer-non-critical-css/#optimize).

**Comment by sathyamahes** [comment]
@patrickhulce  Thank you for your reply.
I have tried defer and async for script but still am getting same warning.
And for stylesheet I have tried like below :

```
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="prefetch" as="style" />
```
And for script :
```
<script src="https://unpkg.com/axios/dist/axios.min.js" defer></script>
```
Is there any item I have missed out?

**Comment by patrickhulce** [comment]
That's still not the correct format for `<link>` loading, please follow the documentation.

We're not able to provide 1:1 support for this sort of thing, sorry. Try StackOverflow if you're still having problems following the docs.
