### ISSUE TITLE
Best Practices Error version.match is not a function

### ISSUE THREAD

**Issue by KevinDonaldson** [GoogleChrome/lighthouse#10294]
There appears to be an error with the way the lighthouse audit tool is detecting versions on some websites. I'm specifically seeing this error on Magento 2 websites but may effect others.

See https://www.sigmabeauty.com/

Magento 2 utilizes require.js and has built in JS bundling that may impact the way that the Chrome Library Detector detects vulnerable versions. 

Attached is a screenshot of the error.

![Screen Shot 2020-02-04 at 10 26 41 AM](https://user-images.githubusercontent.com/7206317/73780219-e6929080-4742-11ea-86be-24c7a9d875ed.png)

**Comment by patrickhulce** [comment]
Thanks very much for filing @KevinDonaldson! I can reproduce this as well and can confirm it's specific to Magento 2 sites 👍
