### ISSUE TITLE
Document does not have a meta description

### ISSUE THREAD

**Issue by kbi-user** [GoogleChrome/lighthouse#10291]
Lighthouse issue: 
Document does not have a meta description. Meta descriptions may be included in search results to concisely summarize page content. Learn more. 

Failure: 
Document has a meta description, less than 256 chars, more than 140 chars in the head section. Document source: https://faq-howto.com/

Lighthouse Chrome plugin - both versions current.

**Comment by paulirish** [comment]
i can also see the meta description in your page source so I agree lighthouse should give you credit for that. but when i try, lighthouse is reporting that audit as passing. 

can you post a screenshot?

i tried both the chrome extension and devtools, and both have that audit passing on https://faq-howto.com/

**Comment by kbi-user** [comment]
Turns out there was a conflict with a wrong script insertion

**Comment by Fernandomr88** [comment]
> Turns out there was a conflict with a wrong script insertion

I'm having the same issue, how did u fix it?

**Comment by qstudio** [comment]
We see this same failure, source code shows what looks like a very valid meta desc:

`<meta name="description" content="Q Studio is an offbeat outfit. We produce bulletproof WordPress applications for clients around the World." />`

But Lighthouse gives a failure with message:

`Document does not have a meta description`

URL: [qstudio.us](https://qstudio.us)

**Comment by patrickhulce** [comment]
@qstudio that meta description isn't in the `<head>` though. It's in the `<body>` which doesn't count.

**Comment by qstudio** [comment]
@patrickhulce - thanks for the feedback, we'll take a look at this, perhaps the hook we were using to add this via WP changed.

**Comment by amirpak** [comment]
I moved the meta description to the first line after <head>, which solved the issue for me. I previously had it under <head> also, but towards the very end of <head>. Guess Google wants it at the very top?
