### ISSUE TITLE
Check on rel="noopener" does not work if the rel attribute contains multiple values

### ISSUE THREAD

**Issue by pantaluna** [GoogleChrome/lighthouse#1029]
About section Avoiding APIs that harm the user experience => Performance: Site opens external anchors using rel="noopener".

The check works fine if the rel attribute contains the single value rel='noopener'.

But the check does not work properly if the HTML contains a rel attribute with multiple values e.g. <a rel='nofollow noopener' target='_blank' href='http://'>text</a>. The check concludes incorrectly that the rel="noopener" is absent.

**Comment by brendankenny** [comment]
fixed in #1035

**Comment by brendankenny** [comment]
@pantaluna thanks for catching this for us :)
