### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by Abhixxx** [GoogleChrome/lighthouse#10306]
In lighthouse audit, in SEO it has mentioned that meta description is not added to page but I have mentioned the meta description to the document. Please elaborate on this issue.

**Comment by patrickhulce** [comment]
Please elaborate in your bug report. There is a [template of required information](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) to fill out.
