### ISSUE TITLE
How to fix 'Ensure text remains visible during webfont load' for CDN package

### ISSUE THREAD

**Issue by sathyamahes** [GoogleChrome/lighthouse#10307]
I was trying to fix the 'Ensure text remains visible during webfont load' issue from Lighthouse audit for my web application.I have read from many articles about `font-display:swap` as the solution for this warning. Its working fine for the font I have added in my application.

But am getting this warning for the third party resources like fontawesome and font.gstatic.com.I have attach the screenshot below:

![webfont_audit](https://user-images.githubusercontent.com/30695458/74035049-88360e00-49df-11ea-955e-7f05ec1341bb.png)

I have added font-awesome icon plugin for my app. And I am founding this fontawesome-webfont  inside font-awesome.min.css. 

How can I fix this issue? Can someone help me out of this warning?

Thanks in Advance:)

**Comment by patrickhulce** [comment]
Google Fonts: Easy fix https://css-tricks.com/google-fonts-and-font-display/

Font Awesome: Open feature request, feel free to +1 https://github.com/FortAwesome/Font-Awesome/issues/16077
