### ISSUE TITLE
Run lighthouse on mobile device using alternative forwarded port

### ISSUE THREAD

**Issue by mschilling** [GoogleChrome/lighthouse#1030]
Is it possible to run Lighthouse CLI on a mobile device using an alternative port (e.g. **port 9224**)?

Currently it uses port 9222.

**Comment by patrickhulce** [comment]
@mschilling have you tried using the `--port` flag in the CLI?
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-cli/bin.ts#L123

**Comment by mschilling** [comment]
@patrickhulce I've tried it, didn't work. However, after upgrading Lighthouse to latest version (1.2.1) it works fine!

```shell
lighthouse --disable-device-emulation --disable-cpu-throttling --port 9224 https://airhorner.com
```

Thanks, I will close this issue.
