### ISSUE TITLE
New "Ready to (automatically) publish in app stores" badge for PWA

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChrome/lighthouse#10300]
Companies like Microsoft and Samsung are experimenting with publishing PWA to their app stores.

See https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/microsoft-store and https://medium.com/samsung-internet-dev/introducing-progressive-web-apps-to-samsung-galaxy-store-47ecd317725b for more info.

Bing web crawler use the info from web app manifest to decide that PWA should be considered for automatic inclusion in the Microsoft Store.

Currently, to add PWA to Samsung Galaxy Store you need to send the URL to pwasupport@samsung.com. Samsung Internet team requests all the necessary info from you.

The process of publishing PWA to app stores will be automated and significantly improved in the foreseeable future.

In order to automatically publish PWA to app stores (so that they look like the rest apps in store) the following fields must be included in the web app manifest:

* [name](https://w3c.github.io/manifest/#name-member)
* [icons](https://w3c.github.io/manifest/#icons-member)
* [description](https://w3c.github.io/manifest/#description-member)
* [screenshots](https://w3c.github.io/manifest/#screenshots-member)
* [categories](https://w3c.github.io/manifest/#categories-member)
* [iarc_rating_id](https://w3c.github.io/manifest/#iarc_rating_id-member)

What about a new "Ready to (automatically) publish in app stores" badge for PWA that have the fields above in web app manifest?

**Comment by FluorescentHallucinogen** [comment]
It seems like I could develop a [custom audit recipe](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit) for that.

@diekus @aarongustafson WDYT?

**Comment by FluorescentHallucinogen** [comment]
As an idea, search engines and app stores could use [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci) + this custom audit recipe under the hood to decide should PWA be considered for automatic inclusion or not.

**Comment by patrickhulce** [comment]
Neat idea @FluorescentHallucinogen! I think the `description`, `screenshots`, `categories` and `iarc_rating_id` are the pieces missing from Lighthouse currently.

cc @egsweeny do we have any signals from PWA council on these properties and Chrome's stance on them?

**Comment by diekus** [comment]
This might be related, we've discussed in the past, I think something like this is needed to easier automate publication/discoverability of PWAs.

https://github.com/w3c/manifest/issues/849

**Comment by patrickhulce** [comment]
We could proceed with an audit like this in the "PWA Optimized" category if anyone is interested in helping out here :)

It would look somewhat similar to #10370 adding manifest parser support and a new audit.

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
