### ISSUE TITLE
How to fix 'Serve static assets with an efficient cache policy' lighthouse audit for CDN

### ISSUE THREAD

**Issue by sathyamahes** [GoogleChrome/lighthouse#10308]
What is the efficient way to cache javascript,html and css files? Where we need to configure this cache-control if we are using pagespeed ?

And also, When I configured cache-control with max age one year in .htaccess file most of the file showing in the audit warning removed except third partyu resources. Is there any way to increase cache period for CDN?

I have attach the screenshot below:
![staticasset_audit](https://user-images.githubusercontent.com/30695458/74037671-c255de80-49e4-11ea-8052-c6777bd49463.png)

Thanks in  advance.

**Comment by patrickhulce** [comment]
There is not a way for you to increase the cache control value of a resource served from a CDN other than contacting the CDN operator to modify their cache control policy. If it's a URL that isn't versioned, then it's likely intentional to have a low or non-existent cache policy but there are signals that should be sent to indicate this.


Lighthouse core, what are your thoughts on restricting this audit to only look at files that contain a version or hash-like part in their URL to increase the signal:noise ratio?

**Comment by connorjclark** [comment]
> Lighthouse core, what are your thoughts on restricting this audit to only look at files that contain a version or hash-like part in their URL to increase the signal:noise ratio?

I think that may be getting too clever. But if we were to consider a "verisoned hash" as a signal, shouldn't we also enforce the TTL is 1 year (the max spec'd)?

**Comment by patrickhulce** [comment]
> shouldn't we also check the TTL is 1 year (the max spec'd)?

That's basically what we already check for :)

**Comment by kbi-user** [comment]
> There is not a way for you to increase the cache control value of a resource served from a CDN other than contacting the CDN operator to modify their cache control policy. If it's a URL that isn't versioned, then it's likely intentional to have a low or non-existent cache policy but there are signals that should be sent to indicate this.

You can always choose another CDN or not use the CDN or where possible host it locally.

> Lighthouse core, what are your thoughts on restricting this audit to only look at files that contain a version or hash-like part in their URL to increase the signal:noise ratio?

If I may drop in and add: using another provider's resources (even Google) is a choice anyone with a website does. Actually I observe sometimes severe "hickups" and in some countries CDN availability is poor except for Metropolitan areas (especially Australia no matter which CDN provider).

Bottom line: deferred or at least asynced resources, which dont change the (mobile) experience and dont stop interactivity like ganalytics, tag manager,... can be safely ignored by LH (arent they already?). All others including fonts with short expiration as well as "bad" CDNs for js/css libraries with high latency or too short TTL should be penalized. Its all about choices...

**Comment by paulirish** [comment]
Thanks!
