### ISSUE TITLE
Backend time is seemingly ignored when using simulated throttling

### ISSUE THREAD

**Issue by SevInf** [GoogleChrome/lighthouse#10317]
#### Provide the steps to reproduce
1. Run LH on https://tti-test.now.sh/api/example. Use simulated throttling.

```
lighthouse  https://tti-test.now.sh/api/example --view 
```

Source code of this page:

```js
'use strict';

module.exports = function(req, res) {
    res.writeHead(200, {
        'Content-Type': 'text/html'
    });
    res.write(' ');
    setTimeout(() => {
        res.end('<!DOCTYPE html><html><head><title>Hello</title></head><body><h1>Hello</h1></body></html>');
    }, 5000);
};
```

Repo: https://github.com/SevInf/tti-test

  What we are doing here is imitating backend time by delaying response for 5 seconds. We still output and empty space straight away to have incomplete response straight away, but the actual html is delayed.

#### What is the current behavior?

TTI, FCI and FMP are all below 5s and green:
![image](https://user-images.githubusercontent.com/603056/74164985-c1ab8b00-4c24-11ea-83eb-eb315ecb9d16.png)

#### What is the expected behavior?

All metrics should be at least 5s:
- Per definition, TTI can't happen before DOMContentLoaded. 
- Per definition, FCI should happen when visible content gets rendered. Space we send before the delay is not visible.
- FMP can't happen before FCP.

with `--throttling-method devtools`, metrics look correct. If we remove `res.write(' ')` before delay, simulated metrics also look correct.

#### Environment Information
* Affected Channels: all of them, i think.
* Lighthouse version: 5.6.0
* Chrome version: 82.0.4054.0 (Official Build) canary (64-bit)
* Node.js version: v12.14.1
* Operating System: macOS 10.15.2

**Related issues**

**Comment by patrickhulce** [comment]
You are correct and this is WAI. One of the goals of simulated throttling is to reduce variance. Variable server response times on shoddy shared hosting are a key contributor to FCP variance, so simulated throttling essentially throws out outlier response times. If you'd like to stick with observed metrics, `--throttling-method=provided` or `devtools` is what you're looking for. The [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md) and [variance](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) documentation covers this in greater detail.

FWIW, there is also even [a plan](https://github.com/GoogleChrome/lighthouse/pull/9920) to take this further and completely ignore all observed network timings by default. If you have any thoughts on this direction feel free to chime in there.

**Comment by SevInf** [comment]
Thank you for clarification!
