### ISSUE TITLE
TTI reporting higher value than the audit

### ISSUE THREAD

**Issue by zacknotes** [GoogleChrome/lighthouse#10319]
I ran a Chrome performance audit on this page, and I got over ~ 70,000 ms for TTI. 

However, the audit completed after ~ 27,000 ms. How is that possible?  

https://www.aarrowsignspinners.com/locations/houston/

**Comment by patrickhulce** [comment]
[Simulated throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md#types-of-throttling).

Lighthouse watched the page load under faster conditions and estimated how long it would take to load under slower conditions.

**Comment by zacknotes** [comment]
Ahh ok makes sense. Thanks Patrick
