### ISSUE TITLE
InstallabilityErrors protocol format changed

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#10318]
The artifact shape does not match the typedef

**Actual** (taken from `latest-run/artifacts.json`)
```json
  "InstallabilityErrors": {
    "installabilityErrors": [
      {
        "errorId": "no-matching-service-worker",
        "errorArguments": []
      }
    ]
  },
```

**Declared**
```typescript
        export interface GetInstallabilityErrorsResponse {
            errors: string[];
        }
```

#### Provide the steps to reproduce
1. Run LH on https://www.optyx.app

 
#### What is the current behavior?

PWA category errors with `?` score

#### What is the expected behavior?

PWA category displays that the site is not a PWA

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: master
* Chrome version: 82.0.4054.0

**Related issues**
It appears that the team's doc (https://github.com/GoogleChrome/lighthouse/pull/10168#issuecomment-577886962) might not have been true afterall :/

**Comment by connorjclark** [comment]
/cc @chruxin

> The strings that are currently present in installable_logging.cc will be
moved to the DevTools frontend. They'll remain in place so we are backwards
compatible.

They _should_ be on the protocol. I'll double check something silly isn't happening in Lighthouse.

**Comment by connorjclark** [comment]
This is why: https://chromium-review.googlesource.com/c/chromium/src/+/2026381

**Comment by patrickhulce** [comment]
> https://chromium-review.googlesource.com/c/chromium/src/+/2026381

Hahaha, that's hilarious. Deprecated and then removed in record time, same milestone even! 😆

**Comment by connorjclark** [comment]
We'll need to support both now.
