### ISSUE TITLE
Disabled compression on the dev server

### ISSUE THREAD

**Issue by vojtechjelinek** [GoogleChrome/lighthouse#10321]
Hi, we at [Oppia](https://github.com/oppia/oppia) want to create our custom Lighthouse CI that would run Lighthouse for all of our PRs, check the scores and check the audits. 

The problem is that since we use App Engine and can't afford to deploy the server for all of our PRs we need to check the Lighthouse score on the dev server, but the dev server doesn't compress the served data, that means that all the metrics have very bad numbers, we can check just the audits (except for the compression) and skip the metrics but then we are missing quite a lot of info.

I know that this is mostly a problem with the App Engine dev server but I wanted to ask if there would be a possibility to solve this by some configuration/changes in the Lighthouse end.

**Comment by patrickhulce** [comment]
@vojtechjelinek are you using [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci/) or rolling your own system?

To get accurate metrics, the app will need to be served through a server with compression, there's no real workaround in Lighthouse. But a thin nodejs proxy server with compression is a simple and reasonable alternative if you can't enable compression on your dev server. ([Untested example](https://github.com/axiak/filternet#options) found after brief search)

**Comment by vojtechjelinek** [comment]
@patrickhulce We are not sure yet. But using and prox that will compress the files seems like a good idea, thanks.
