### ISSUE TITLE
Update "time between visits"

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/lighthouse#1033]
I believe the time between visits is not five minutes anymore. Please update:

> While users can manually add your site to their homescreen in the browser menu, the <a href=\"https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android?hl=en\">prompt (aka app install banner)</a> will proactively prompt the user to install the app if the below requirements are met and the user has visited your site at least twice **(with at least five minutes between visits)**.

**Comment by ebidel** [comment]
Another good catch!

@kaycebasques can you take this? The heuristics are changing on the install banner.

**Comment by paulirish** [comment]
I poked around the source to find the answer. It appears it's not timebased at all any longer and instead built on [site engagement](https://www.chromium.org/developers/design-documents/site-engagement).

* June 2016: [Issue 2024953005: Allow app banners to be triggered by increases in site engagement. - Code Review](https://codereview.chromium.org/2024953005)
* December 2016: [Issue 2553013004: Remove the app banner navigation heuristic. - Code Review](https://codereview.chromium.org/2553013004)

Tracking bug: https://bugs.chromium.org/p/chromium/issues/detail?id=616322

---------

Currently: https://cs.chromium.org/chromium/src/chrome/browser/banners/app_banner_settings_helper.cc?sq=package:chromium&dr=CSs&rcl=1483532378&l=42

**A site engagement score (which can be 0-100) of >= 2 is required.**

details on site engagement: https://www.chromium.org/developers/design-documents/site-engagement.

You can see by opening  `chrome://site-engagement/` in your browser.

(lastly, i updated the other A2HS prompt heuristics over in [the original a2hs issue](https://github.com/GoogleChrome/lighthouse/issues/23#issuecomment-270453303).)

**Comment by sbirch** [comment]
It looks like this text is still out of date & the Chromium bug there is closed. Should there be a separate issue to update the description in Lighthouse? Or should we just remove it altogether and reference documentation?

**Comment by kaycebasques** [comment]
looks like someone fixed it

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/webapp-install-banner.js#L41
