### ISSUE TITLE
Update viewer to mention web.dev/measure or PSI

### ISSUE THREAD

**Issue by staabm** [GoogleChrome/lighthouse#10335]
the lighthouse-viewer supports loading lighthouse reports based on PSI data.

this is kind of a hidden feature as you need to know the url to trigger these.

Example: https://googlechrome.github.io/lighthouse/viewer/?psiurl=https://www.kunzmann.de/de/&category=accessibility&category=performance&category=pwa&category=best-practices&category=seo&strategy=mobile

it would be great if the landing page https://googlechrome.github.io/lighthouse/viewer would offer an additional/optional url input field which can be used to type a url and load reports from PSI data.

**Comment by staabm** [comment]
something like 
![image](https://user-images.githubusercontent.com/120441/74419973-fc8f0800-4e4a-11ea-984a-ad391b435624.png)

**Comment by patrickhulce** [comment]
Why not use the web.dev/measure or PSI insights UI directly that functions like this? :)

We wanted to avoid turning the viewer into yet another web UI for invoking PSI and this hidden support is primarily just to open reports from the extension.

**Comment by paulirish** [comment]
On the one hand... we totally could do what you said and it'd make it easier for folks.

But we're also balancing that with our product positioning. We don't want to create another resource that people go to, when they can already do the same at other tools we already own. :)

its fun

**Comment by staabm** [comment]
I see. Wasnt aware of web.dev/measure to be honest. Maybe just add the suggested text and do some cross linking between the tools could help instead of duplicating the functionality? Wdyt?

**Comment by paulirish** [comment]
@staabm wannna give us a pull request?

i'm thinking some text like your mock but...

> You can also use the Lighthouse browser extension (Chrome/Firefox) or web.dev/measure to get a fresh report.

(with the appropriate things linked.)  wdyt?

**Comment by staabm** [comment]
Sure thing
