### ISSUE TITLE
three.js different results and error

### ISSUE THREAD

**Issue by sanprieto** [GoogleChrome/lighthouse#10334]
**Feature request summary**

Hello I have created a new project with three.js and bootstrap. I check with audit and insights and I have a very different results.
Are the special features of this library (three.js) being taken into account while doing the analysis?
Sometimes shows this error:

`Lighthouse returned error: INTERNAL: Extension result empty. Lighthouse calling Page.navigate with https://sanprieto.es/newProject/ Uncaught (in promise) Error: Extension timed out. No call to exit() before render timeout. at wrs.Extension.onTimeout_ (http://ghost-rider/devtools_script_api.js:5567:13) at http://ghost-rider/devtools_script_api.js:669:9 at Map.forEach (<anonymous>) at chromium.DevTools.Connection.dispatchMessage (http://ghost-rider/devtools_script_api.js:668:76) at chromium.DevTools.Connection.onJsonMessage_ (http://ghost-rider/devtools_script_api.js:650:65) at <anonymous>:1:40`

**Are you willing to work on this yourself?**
I'm not sure if i have enough level but yes I am.

**What is the motivation or use case for changing this?**
Because currently there are a lot of project create with three.js

**How is this beneficial to Lighthouse?**
Because with a good analysis is possible to improve the project.

Run LH on https://sanprieto.es/newProject/

**versions**
chrome  80.0.3987.100
├── stats.js@0.17.0
├── three@0.113.2
└── three-orbitcontrols@2.110.3
bootstrap 4.4

**Comment by patrickhulce** [comment]
I couldn't reproduce that exact behavior but that page definitely has abnormal behavior on PSI. We'll look into it.

![image](https://user-images.githubusercontent.com/2301202/75291530-053af300-57e8-11ea-8ac1-c45aac54270a.png)

**Comment by connorjclark** [comment]
LR infra must do webgl in software, that is why it's so slow :(

one option would be to disable webgl in WRS - canvas might be faster?

**Comment by connorjclark** [comment]
We could possibly detect heavy webgl usage and emit a warning in PSI.

**Comment by pttsky** [comment]
Hi guys, just FYI this page is not only one. Most of websites using WebGL animations have the same problem and same numbers. I shared my tests long time ago but I will share them here once again.

https://docs.google.com/spreadsheets/d/1Z9g0pLB3Y-2xdfZXXNtpcUrcjI-NMl8JrJKnK2mXhCU/edit?usp=sharing

**Comment by connorjclark** [comment]
duping into #8557
