### ISSUE TITLE
Consider marking HTTP/2 audit `notApplicable` on `localhost`

### ISSUE THREAD

**Issue by mauriciabad** [GoogleChrome/lighthouse#10330]
This audit always fails "[Does not use HTTP/2 for all of its resources](https://web.dev/uses-http2)".

I don't choose this setting. Shouldn't it be HTTP/2 by default?

**Comment by paulirish** [comment]
There's a few things that are different on localhost (we don't expect gzip either)

Then again both gzip and h2 are possible on localhost, but certainly a pain in the ass.

We'd prefer to not special-case localhost here as we'd also have to carry that policy across for a bunch of other things.

**Comment by paulirish** [comment]
I was so very wrong.

**Comment by mauriciabad** [comment]
So what? 
Is it reasonable to mark HTTP/2 as `notApplicable` on `localhost`? Or what other options do you consider? 😄

**Comment by paulirish** [comment]
> Is it reasonable to mark HTTP/2 as `notApplicable` on `localhost`? yup we'll do that.

**Comment by paulirish** [comment]
fixed by #11766
