### ISSUE TITLE
Lighthouse crashes when testing internal only sites

### ISSUE THREAD

**Issue by Adam-Young** [GoogleChrome/lighthouse#10340]
#### Provide the steps to reproduce
1. Run LH on any non publicly available URL
  
Effects all pages on multiple different development domains and systems (jquery Mobile older site, bootstrap site) but also many 3rd party tracking scripts causing performance concerns 

#### What is the current behavior?
Crashes after warmup with the following error:
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: ***masked***
Chrome Version: 79.0.3945.130
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@e22de67c28798d98833a7137c0e22876237fc40a/audits_worker/audits_worker_module.js:1268:229)
```

Attempted to remove throttling, clearing cache etc, all result in the same error, 

#### What is the expected behavior?
That it will work without requiring the site to be publicly available 

#### Environment Information
* Affected Channels:Extension, DevTools
* Lighthouse version: Unknown
* Chrome version: 79.0.3945.130 (64-bit)
* Node.js version: N/A
* Operating System: Windows 10

**Comment by connorjclark** [comment]
The extension can only audit public sites.

DevTools should be able to hit any page you can yourself. If you get Protocol timeouts, then that's gonna be the same root issue as the bot says.
