### ISSUE TITLE
PageSpeed Insights SPEEDINDEX_OF_ZERO error on Desktop version

### ISSUE THREAD

**Issue by polart** [GoogleChrome/lighthouse#10350]
#### Provide the steps to reproduce
1. Run PageSpeed Insights on https://preply.com/en/skype/english-tutors
2. Open Desktop tab

Direct link https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpreply.com%2Fen%2Fskype%2Fenglish-tutors&tab=desktop
  

#### What is the current behavior?
"Speed Index" throws an error `SPEEDINDEX_OF_ZERO` for Desktop verision.
![image](https://user-images.githubusercontent.com/27948118/74678208-03a77480-51c3-11ea-82fd-9d97c8fdc0a9.png)

At the same time Mobile version works just fine.

The same error appears by calling PageSpeed Insights API:
```
https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://preply.com/en/skype/english-tutors&category=PERFORMANCE&strategy=DESKTOP
```
here is a response from the API call (the reponse is in JSON, extension changed to txt so it can be attached in GH) [lr-lh.txt](https://github.com/GoogleChrome/lighthouse/files/4215533/lr-lh.txt)
```json
...
      "speed-index": {
        "id": "speed-index",
        "title": "Speed Index",
        "description": "Speed Index shows how quickly the contents of a page are visibly populated. [Learn more](https://web.dev/speed-index).",
        "score": null,
        "scoreDisplayMode": "error",
        "errorMessage": "Chrome didn't collect any screenshots during the page load. Please make sure there is content visible on the page, and then try re-running Lighthouse. (SPEEDINDEX_OF_ZERO)"
      }
...
```

Running LH via cli works fine: [cli-lh.txt](https://github.com/GoogleChrome/lighthouse/files/4215619/cli-lh.txt)

```
lighthouse https://preply.com/en/skype/english-tutors --output=json --output-path=./cli-lh.json --chrome-flags='--headless' --only-categories=performance --emulated-form-factor=desktop --throttling-method=provided
```

And running LH from Chrome DevTools also works fine (Device: Desktop, Audits: Performance, Throttling: No throttling): [devtools-lh.txt](https://github.com/GoogleChrome/lighthouse/files/4215630/devtools-lh.txt)

The error happens only with this page, another pages work fine, e.g. https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpreply.com%2Fen%2Fskype%2Fenglish-tutoring-jobs&tab=desktop

These pages are written with NextJS.

#### What is the expected behavior?
"Speed Index" and "Performance score" are calculated properly.

#### Environment Information
* Affected Channels: lr
* Lighthouse version: 5.6.0
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**
#9545
#5815

**Comment by connorjclark** [comment]
Thanks for the detailed report. Confirmed everything you said - only broken in PSI api for desktop.

@paulirish and I explored this in detail.

First of all, speed index is zero because the last frame we give speedline is a blank frame. Which is odd, because all the frames besides the first one are not blank. This results in us determining the speedindex to be zero no matter what.

We learned that, even outside the PSI api, there is a noticeable flash towards the end of the page. We got a trace from LR and noticed that the girls in the rendered frame changes.

To me, this points to an error in hydration from server side rendering. The expectation is that the props given to the server should match what is given to the client. If that is not true, the DOM will need to be reconstructed. This is a pretty heavy operation. I guess it takes just long enough for it to still be occurring when Lighthouse determines that is should stop the audit.

@polart can you confirm if this site is using server side rendering, and if the props given on the client side differ in any way from the server? perhaps some nondeterminism?

**Comment by connorjclark** [comment]
or perhaps it is this

![image](https://user-images.githubusercontent.com/4071474/75300409-9dd37200-57ec-11ea-99ed-062c40b39b2f.png)

**Comment by paulirish** [comment]
> or perhaps it is this

oops that was actually object.create polyfill from core-js.  my bad, it's not that.

but I have a feeling it is happening as part of all the jostling during hydration. here's what appears to be some associated next.js code: 

![image](https://user-images.githubusercontent.com/39191/75300982-62d23e00-57ee-11ea-8cd5-b4f97d45294c.png)

We don't know this particular setup of Lighthouse triggers this bad case of seeing the body as `display:none` (or something like that), but that appears to be what's happening. We haven't run into this before, fwiw.

**Comment by polart** [comment]
> We learned that, even outside the PSI api, there is a noticeable flash towards the end of the page. 

Do you mean in other lighthouses like devtools and cli? Or simply in the browser?
We're loading Roboto font closer to the end, but it simply does font swap.
I don't observe a noticeable flash in my browser.

>  We got a trace from LR and noticed that the girls in the rendered frames change.

This is actually another strange behaviour that happens only in PSI and it started to appear about two days ago. And sometimes it works fine, sometimes not - this is judging by mobile test, since desktop gives an error and doesn't expose screenshots. 

> @polart can you confirm if this site is using server side rendering, and if the props given on the client side differ in any way from the server? perhaps some nondeterminism?

Yes, we're using server side rendering. The props should not differ, but these cases hypothetically can trigger change of props on the client and thus rehydration:
* we use `bowser` on server and client to determine which chunks of code and features to include depending on user agent, and some parts of the page are rendered on client for desktop version
* we're running a lot of A/B tests, maybe somehow experiment gets retriggered on client

The problem is that I cannot reproduce this behaviour in browser - it happens only on PSI.

**Comment by polart** [comment]
> but I have a feeling it is happening as part of all the jostling during hydration. here's what appears to be some associated next.js code:
> 
> We don't know this particular setup of Lighthouse triggers this bad case of seeing the body as `display:none` (or something like that), but that appears to be what's happening. We haven't run into this before, fwiw.

This is from `react-dom` and looks like it's hiding the first tutor card for some reason. Maybe because of this
> we use IntersectionObserver to load only visible avatars and trigger react rehydration only for visible tutor cards

**Comment by polart** [comment]
We took response from the server and stored it in HTML file served from S3.
It's available on URL https://preply.com/id/guru-bahasa-prancis/skype

And in such case, PSI for desktop works perfectly fine 🤔  https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpreply.com%2Fid%2Fguru-bahasa-prancis%2Fskype&tab=desktop

**Comment by polart** [comment]
We started optimising our site and this error disappeared, so I guess it was site-specific.
