### ISSUE TITLE
Inconsistent image weight detection

### ISSUE THREAD

**Issue by garethjax** [GoogleChrome/lighthouse#10352]
#### Provide the steps to reproduce
1. RUN LH on https://www.garethjax.net/wp-content/uploads/2017/12/call-center-spam-600x270.jpg
  

#### What is the current behavior?

the image weight detect by LH is higher than the actual weight detected by the inspect tool

#### What is the expected behavior?
They should be the same, i think.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.7
* Chrome version: 80.0.3987.100 (Build ufficiale) snap (a 64 bit)
* Node.js version: 10.16.0
* Operating System: Pop_os eoan (Ubuntu 19.10)

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @garethjax! I'm not seeing this behavior though, the Lighthouse reported size matches the Network panel reported size.

![image](https://user-images.githubusercontent.com/2301202/74751090-62580700-5232-11ea-96bd-dc8b4475b558.png)
![image](https://user-images.githubusercontent.com/2301202/74751133-71d75000-5232-11ea-9ba8-4b19850231fc.png)

Any additional information you can provide to help us reproduce?

(Btw, you can't run Lighthouse on individual images, so I assumed you meant to highlight that image on the run of your homepage)

**Comment by garethjax** [comment]
Hello!

i've used my blog as test area, but i'm seeing the same behaviour on other projects!
I've choosen that image in particular, but it's happening on all the images.

As a test i've run a desktop query and this is the result, as you can see all the images are detected as larger.

Tell which other details i can supply and i will comply ! 

![immagine](https://user-images.githubusercontent.com/3459602/74801872-a0285e80-530a-11ea-85b5-9cf58a1969f2.png)

**Comment by patrickhulce** [comment]
Thanks for the additional info! I can reproduce in DevTools desktop both stable and Canary now. Very strange that the sizes seem to be random and change every run of Lighthouse ranging from 1x-2x the actual transfer size. I don't see this behavior from the CLI where the numbers appear to be accurate.

This will take some investigation.

**Comment by patrickhulce** [comment]
A root cause has been found and being fixed as part of https://github.com/GoogleChrome/lighthouse/issues/11415
