### ISSUE TITLE
unclear that byte / resource sizes are "transfer size"

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10357]
the following parts of the report display KBs which refer to the _transferSize_ (not _resourceSize_) of a resource:

* performance budgets (resource-summary)
* all of the byte efficiency audits

Not only do we not explicitly say "these values are transfer sizes", we also have copy that is misleading. "File Size" makes me think these would be resource sizes.

![image](https://user-images.githubusercontent.com/4071474/74885366-361fb180-532a-11ea-8d3b-feb5a0c49561.png)

We should make it clear what these values are (post-compression / wire size / w.e).

____

Instead of just improving the copy, what if we displayed both (or had a toggle)? I find thinking of CSS / JS / anything in terms of transfer size to be unintuitive. For JS specifically, I think resource size might correlate better with performance than transfer size does (IG has an article supporting this https://instagram-engineering.com/making-instagram-com-faster-code-size-and-execution-optimizations-part-4-57668be796a8)

**Comment by connorjclark** [comment]
cc @khempenius

**Comment by patrickhulce** [comment]
I think the inconsistency between `File Size` for budgets and `Size` for byte efficiency audits should definitely be resolved 👍 

I like the idea of a toggle 👍 though I fear for what that means for the shape of details (I also think we should consider any change to details shape that makes a critical part of the report unrenderable a breaking change at this point)

> For JS specifically, I think resource size might correlate better with performance than transfer size does

Definitely true but not what the audits are reporting on at this point. If we changed the audits to attempt to account for parse/execution time I'd def be on board with that framing 👍 (we've talked about this since the audits first were written and I'd love to move to this but it's just hard)

**Comment by khempenius** [comment]
Re: Misleading Copy

Are you sure? At least for the resource-summary & performance-budget audits, I only see transfer size used a column headers and I think it's always been that way.

<img width="931" alt="Screen Shot 2020-02-20 at 12 54 49 PM" src="https://user-images.githubusercontent.com/6076184/74963782-4db97180-53e0-11ea-8fd9-2b6481a089e0.png">

<img width="911" alt="Screen Shot 2020-02-20 at 12 54 43 PM" src="https://user-images.githubusercontent.com/6076184/74963787-4f833500-53e0-11ea-924f-c30faa350e68.png">

^ Though "set budget for... transfer size of page resources" is probably better wording.

More broadly though, I'm definitely in agreement that exposing info on resource size could be useful. Offering that option in budget.json has been on my mind.

**Comment by connorjclark** [comment]
> Are you sure? 

no :) I was looking at the images in the PR, my mistake. should have looked at least looked at now deployment

it's certainly unclear for our byte audits, tho

![image](https://user-images.githubusercontent.com/4071474/74967419-c82cc600-53cd-11ea-83a7-9abbc07cd87a.png)

**Comment by paulirish** [comment]
After group triage:

Let's make 'Size' unambiguous.. either "File Size" or "Transfer Size".

Also sometimes (like in unused JS) you maybe want to see the Resource/File sizes instead. Is that a toggle or something?

**Comment by paulirish** [comment]
> After group triage:
> 
> Let's make 'Size' unambiguous.. either "File Size" or "Transfer Size".

After todays discussion.. we decided "Resource Size" is more correct than "File Size". And that's what Devtools network panel uses anyway.

So.. "Resource Size" and "Transfer size" are the strings.
