### ISSUE TITLE
How to fix 'Serve static assets with an efficient cache policy' lighthouse audit

### ISSUE THREAD

**Issue by blesson-bridge** [GoogleChrome/lighthouse#10353]
#### Provide the steps to reproduce
1. Run LH on www.bridge-global.com
  

#### Current Behaviour
For 88 resources, cache TTL is found to be None.
![screenshot-googlechrome github io-2020 02 18-17_24_43](https://user-images.githubusercontent.com/56107307/74734034-ae776b80-5273-11ea-95fc-951302611f3c.png)
Already set the required cache expires and headers for images and js files via htaccess.
While checking from the networks tab, it shows that the images are loaded from memory cache and in the response headers , we have Cache-Control: public,max-age=1209600 . 
But when we use LH to analyze, we get Cache TTL  as None. Why this is happening?
Please find the below screenshots :
![Untitled](https://user-images.githubusercontent.com/56107307/74734952-b0422e80-5275-11ea-82d1-d4ae73546b33.png)

![Untitled](https://user-images.githubusercontent.com/56107307/74734476-a23fde00-5274-11ea-8d0e-4062bfdb1d92.png)

 

#### What is the expected behavior?
Cache TTL showing right value

#### Environment Information
* Chrome version: Version 80.0.3987.106
* Server Operating System:Linux

**Comment by patrickhulce** [comment]
Thanks very much for filing @blesson-bridge! I'm not able to reproduce this behavior in that Chrome version though :/ 
![image](https://user-images.githubusercontent.com/2301202/74751643-31c49d00-5233-11ea-951d-0b804a5c7dad.png)

Any additional information you could provide that could help us reproduce? 

(Btw, you listed Linux as your OS but there is an "Activate Windows" overlay in your screenshot, were the screenshots taken on different machines?)

**Comment by blesson-bridge** [comment]
Hi,
Thank you for the support, @patrickhulce , But the issue persists. Sorry, I am using the Windows Operating system. The results still showing TTL for images as none.
Please find the attached screenshot.
![Untitled](https://user-images.githubusercontent.com/56107307/74801419-8253fd00-52fc-11ea-9c4a-8dfce3d2a627.png)

**Comment by blesson-bridge** [comment]
While checking from the Audits tab, the cache TTL shows the right value, but the whole report differs from what I get in https://googlechrome.github.io/lighthouse/viewer.
Another issue is like under unused CSS , 
…css/main.css and …css/master.css is listed. But these CSS files are used for the homepage.
Please find the attached screenshot.
![Untitled](https://user-images.githubusercontent.com/56107307/74802852-060fe880-5301-11ea-8f05-cb212e8f773c.png)

Also, is that true Google is planning to give slow websites a new badge of shame in Chrome based on reports from PAGE INSIGHTS and Lighthouse ?

**Comment by blesson-bridge** [comment]
https://github.com/GoogleChrome/lighthouse/issues/10353

**Comment by patrickhulce** [comment]
> The results still showing TTL for images as none.

I'm sorry but I still can't reproduce this :/ The only resources I see without a cache TTL are coming from olark.com

![image](https://user-images.githubusercontent.com/2301202/74850128-35255a80-52ff-11ea-96c0-77a54d831c6c.png)

You mentioned this isn't happening in Audits panel, how are you running Lighthouse when you do see it?

> Another issue is like under unused CSS ,
…css/main.css and …css/master.css is listed. But these CSS files are used for the homepage.

I don't understand the problem here. Yes, some of the CSS is used for the homepage but much of the stylesheet is unused (37 / 42 KB) which is exactly what the audit is flagging.
