### ISSUE TITLE
Feedback loop for document.write()

### ISSUE THREAD

**Issue by Hydra9268** [GoogleChrome/lighthouse#10360]
I was going through and implementing noted Best Price improvements. One of those is document.write() for google's pagead conversion script.
https://i.imgur.com/wCbI2eL.png

Thought I could get around it by placing an async on the script tag. Unfortunately, this happens
https://i.imgur.com/EO43doQ.png

The TL;DR is Google needs to remove instances of document.write from their conversion.js file. I could do it, but I don't want to host and maintain the file... or an exception needs to be made in Lighthouse to flag this is as OKAY.

**Comment by paulirish** [comment]
I think you want to migrate to the global site tag: https://support.google.com/google-ads/answer/6331314?hl=en

That one is asynchronous and safe, whereas the conversion.js file is legacy and uses this bad pattern.

**Comment by Hydra9268** [comment]
Oh, wow. Duly noted. I'll proceed forward with that solution. Thank you, Paul.

**Comment by patrickhulce** [comment]
Glad you got this working @Hydra9268!
