### ISSUE TITLE
Narrow the unique ID attribute audit to just affected forms/table headers

### ISSUE THREAD

**Issue by onepack** [GoogleChrome/lighthouse#10374]
#### Provide the steps to reproduce
1. Run LH on dochorse.nl

#### What is the current behavior?

[id] attributes on the page are not unique
The value of an id attribute must be unique to prevent other instances from being overlooked by assistive technologies. Learn more.
Failing Elements
--
span#product-price-7393.price-wrapper
span#product-price-7369.price-wrapper
span#product-price-7372.price-wrapper
span#product-price-7352.price-wrapper
span#product-price-7332.price-wrapper
span#product-price-7423.price-wrapper
span#product-price-7416.price-wrapper
span#product-price-7418.price-wrapper
span#product-price-7408.price-wrapper
span#product-price-7413.price-wrapper

#### What is the expected behavior?
They are unique!
They have a unique number. Searching source of the page for a duplicate gives me only 1/1 hit.
So how can it be a duplicate?

#### Environment Information
* Affected Channels: 
* Lighthouse version: No idea where to find this info, it's build into the browser dev tools.
* Chrome version: 80.0.3987.116
* Node.js version:
* Operating System: Windows10

**Related issues**

**Comment by connorjclark** [comment]
![image](https://user-images.githubusercontent.com/4071474/75191627-8b333d00-5707-11ea-998d-c9b01cc632f1.png)

**Comment by connorjclark** [comment]
oops, didn't mean to close

team, maybe we could list (at most 2) the duplicate elements in the report? we just show+linkify  one atm.

**Comment by onepack** [comment]
Thank you for your swift reply.
My wrong! I see now it's the dynamic rendering of the carousel items that creates duplicates.
Looking for the duplicates in the the static source of the page will never work then.

**Comment by patrickhulce** [comment]
@connorjclark to report our concerns to axe :)

**Comment by connorjclark** [comment]
dequelabs/axe-core#1097 they already did the narrowing we want :)

**Comment by connorjclark** [comment]
so we use `duplicate-id-aria` and `duplicate-id-active`. should we just turn of `duplicate-id`?

**Comment by connorjclark** [comment]
LOL we already do this. nvm.
