### ISSUE TITLE
Allow file URI schema on CLI

### ISSUE THREAD

**Issue by hemanth** [GoogleChrome/lighthouse#10372]
![image](https://user-images.githubusercontent.com/18315/75089230-a76a8a80-550b-11ea-94ee-1076f2eb1111.png)

**What is the motivation or use case for changing this?**
With `--gather-mode` it is nice to have `./test.html` or `file://` to be respected, so custom plugins can be tested easily.

**How is this beneficial to Lighthouse?**
Easier custom plugin testability.

**Comment by patrickhulce** [comment]
Thanks for filing @hemanth! But the requirement of a real URL goes beyond `--gather-mode`. Lighthouse and browser behavior in general on `file:` pages is substantially different than when it will be served over `http`, so it's simply unsupported no matter what flags you may or may not be using (loading signals are different, browser events are different, "network" requests are different, etc that would all affect gatherer behavior).

While testing out a gatherer you'll need to `python -m SimpleHTTPServer 8080`/`npx http-server` in the background to audit local files.

**Comment by hemanth** [comment]
I felt so, ended up serving the file too.

One thing we could do is use something like `serve` (node module) serve it and then open that URL?

Too much of a deviation for the scope of lighthouse?

**Comment by patrickhulce** [comment]
Yeah IMO this is better left for extending packages rather than lighthouse core. [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci/) already does something like this with `staticDistDir` for example.

Though we are considering some features found there as candidates for bringing into the standard CLI in the future.

**Comment by patrickhulce** [comment]
We discussed in eng meeting and agree this is outside scope of lighthouse-core though if you're interested in improving the lhci experience or another package to do nice LH things definitely let us know :)
