### ISSUE TITLE
First Contentful Paint - 4.6 s

### ISSUE THREAD

**Issue by hamza-00** [GoogleChrome/lighthouse#10375]
**Summary**
How I can improve this First Contentful Paint - 4.6 s of my wordpress website? I need helps by developers to guide me the steps to take for improvement.

**Comment by connorjclark** [comment]
Start by following the advice in the report?

**Comment by hamza-00** [comment]
Yes, How Can I start? with hummingbird plugin or any other way to fix these issues?

**Comment by connorjclark** [comment]
https://web.dev/measure/
