### ISSUE TITLE
Question: How can I add ability to use custom preset rules for accessibility audit

### ISSUE THREAD

**Issue by mohanraj-r** [GoogleChrome/lighthouse#10386]
**Feature request summary**
 **Describe what you want to be added**
Ability to choose a custom ruleset axe config for the accessibility audit 

**Are you willing to work on this yourself?**
Yes. Currently working on adding the ability to the extension. Planning to finally refactor it as a custom audit/plugin if possible. 
Right now one of the issues I am facing is that I can't figure out the workflow from clients/extension/scripts/popup.js to lighthouse-core/gather/gatherers/accessibility.js. I am not able to find any code directly calling the `Accessibility` Gatherer. Can you please explain how this works? I have looked at the arch doc. Is it called as part of the online viewer? If so is it possible to deploy and use a local instance of the viewer instead? Not able to find how to go about that in the deployment doc. 

**What is the motivation or use case for changing this?**
We have custom curated axe rulesets that we use in our automated workflows. Ability to use them with the extension would offer the same rulesets for local developer manual  testing workflows and thus aid in triaging/fixing issues found in automated workflows by being able to replicate them locally.

**How is this beneficial to Lighthouse?**
Adds more flexibility and configurability to the accessibility audit thus potentially covering more use cases.

**Comment by patrickhulce** [comment]
Thanks very much for filing @mohanraj-r! This is equivalent steps necessary for  https://github.com/GoogleChrome/lighthouse/issues/10247. Would you be willing to put some of your thoughts down in that issue so we can collect the details in one place? :)

**Comment by patrickhulce** [comment]
(regarding your questions on how the Accessibility gatherer is called, you might want to read the [architecture](https://github.com/GoogleChrome/lighthouse/blob/master/docs/architecture.md), [configuration](https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md), and [custom audit](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit) docs)

**Comment by mohanraj-r** [comment]
Thanks @patrickhulce - responded in https://github.com/GoogleChrome/lighthouse/issues/10247#issuecomment-592723806
