### ISSUE TITLE
Inconsistent measurements

### ISSUE THREAD

**Issue by drorp24** [GoogleChrome/lighthouse#10383]
#### Provide the steps to reproduce
1. On Audit tab, Run LH on https://drorpoliakfull.herokuapp.com/
2. Click View Trace and view Performance tab
3. On Performance tab, click Record, reload page, wait for 10s then stop recording (do not click 'Start profiling and reload page')
4. On Application tab, click 'Clear storage' then on Network tab, right-mouse Reload icon and select 'Empty Cache and Hard Reload'
5. On Console tab, look for the last line: it's GoogleChromeLabs' calculation of TTI  
6. Run LH as Chrome extension
7. Run LH as CLI
  
#### What is the current behavior?
1. In Audit tab, LH measures 2.3s for First Meaningful Paint (FMP) and 7.4s for Time to Interactive(TTI) (screenshot enclosed).
2. View Trace shows FMP at 600ms and last long task finishing around the same time (screenshot enclosed). 
3. Extended Performance tab recording shows no other long tasks after that one, and no n/w requests either other than google map's (n < 2), implying a TTI of around 600ms (screenshot enclosed).
4. Network tab further verifies that no n/w activity other than service-worker's precaching and google maps occured after 600ms (screenshot enclosed).
5. Console screenshot shows tti-polyfill-debug's measurements, logging the last long task finishing at 602ms, each of the n/w requests occuring since and its own TTI calculation of 602ms.
6. Next screenshot shows LH as Chrome extension, measuring 1.7 for FMP and 4.3 for TTI.
7. Last screenshot shows LH as CLI, measuring 1.0 for FMP and 4.3 for TTI.

#### What is the expected behavior?
- LH's FMP and TTI measurements to be in line with what Performance and Network tabs show.
- LH's measurements to be consistent with one another regardless of whether run in DevTool, Extension, CLI or as GoogleChromeLabs' tti-polyfill.

#### Environment Information
* Affected Channels: CLI, Extension, DevTools
* Lighthouse version: 5.7.0 (DevTools)
* Chrome version: 80
* Node.js version: N/A
* Operating System: Mac OSX Catalina

#### Note
- The response to a '/' is a server-rendered page with little inline CSS, an embedded svg and a button which requires minimal hydration to be interactive
- No code split on the server as loadable-components requires configuring webpack and babel which CRA won't allow doing
- The code is at https://github.com/drorp24/full

#### Screenshots (numbered according to the steps above) 
1. Audit tab
<img width="908" alt="Screen Shot 2020-02-26 at 15 03 46" src="https://user-images.githubusercontent.com/594441/75354035-fe2de680-58b4-11ea-90fc-9a87b5ff893a.png">
2. Performance tab
<img width="908" alt="Screen Shot 2020-02-26 at 15 06 00" src="https://user-images.githubusercontent.com/594441/75354078-143ba700-58b5-11ea-9455-62cd98fa8a68.png">
3. Performance tab (extended recording)
<img width="908" alt="Screen Shot 2020-02-26 at 15 08 05" src="https://user-images.githubusercontent.com/594441/75354152-2fa6b200-58b5-11ea-9f9c-68f262eef6c5.png">
4. Network tab
<img width="914" alt="Screen Shot 2020-02-26 at 15 32 12" src="https://user-images.githubusercontent.com/594441/75354678-0f2b2780-58b6-11ea-9bf6-167ec1455487.png">
5. Console tab (GoogleChromeLabs' tti-polyfill measurements)
<img width="914" alt="Screen Shot 2020-02-26 at 16 12 34" src="https://user-images.githubusercontent.com/594441/75355096-a5f7e400-58b6-11ea-8d51-3d8db6eef7b8.png">
6. Chrome extension measurements
<img width="1191" alt="Screen Shot 2020-02-26 at 15 13 01" src="https://user-images.githubusercontent.com/594441/75355184-c32cb280-58b6-11ea-805f-b06beefd1455.png">
7. CLI measurements
<img width="1191" alt="Screen Shot 2020-02-26 at 15 15 37" src="https://user-images.githubusercontent.com/594441/75355203-cde74780-58b6-11ea-8581-1708e9f8e5a0.png">

**Comment by drorp24** [comment]
Can you please open it?
Why did you close it?

**Comment by patrickhulce** [comment]
Because 28 minutes ago it was an empty issue with no information. Now that it's been edited with supporting information, sure :)

**Comment by patrickhulce** [comment]
Summary:

1. The trace/network panel and Lighthouse don't match because performance metrics are *simulated* by default. If you want the traces to match, use *applied* throttling (uncheck the "Simulated throttling" checkbox in DevTools, use `--throttling-method=devtools` from CLI). [Learn more about throttling options](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md). The TTI polyfill will essentially report the value of TTI without throttling (`--throttling-method=provided`).
2. Performance metrics are variable for a large number of reasons [best explained in this document](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md).

Running that URL in DevTools I get: 80, 85, 83, 85, 84  ✅ Within expected variance range
Running that URL from CLI I get: 82, 83, 87, 82, 84 ✅ Within expected variance range

While it's certainly a goal to be as repeatable as possible and we're making efforts in this area (#9887), variation is still going to be expected in performance measurement.

**Comment by drorp24** [comment]
According to GoogleChromeLabs's tti-polyfill it's 602ms. According to LH on DevTools it's 7.4s.

Which of these measurements is right and which is wrong?

I think the TTI is more towards 600ms and not 7.4s because:
1. There's clearly no long task after the one on 602ms and no more than 2 concurrent network requests after that. tti-polyfill-debug verifies that, and so do Performance tab and Network tab. According to the very clear definition in https://web.dev/tti/, the TTI is 600ms.
2. If you clear application cache, then Empty Cache and Hard Reload, you'll be able to click the button and get it to link you to the next page in less than a second.  

What is the TTI then? Is it 600ms or 7.4s?

**Comment by patrickhulce** [comment]
It's both. It's 600ms when observed on your machine without any throttling whatsoever. It's 7.4s when simulating the characteristics of a mediocre mobile phone on a slow 4G network connection.

Again...

> The trace/network panel and Lighthouse don't match because performance metrics are simulated by default. If you want the traces to match, use applied throttling (uncheck the "Simulated throttling" checkbox in DevTools, use --throttling-method=devtools from CLI). Learn more about throttling options. The TTI polyfill will essentially report the value of TTI without throttling (--throttling-method=provided).

Please read [the linked throttling documentation](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).

**Comment by drorp24** [comment]
With Simulated throttling *unticked*, and network and CPU manually throttled in DevTools to match Lighthouse's defaults, the LH audit results now *do match* what Performance and Network tab show. 

The linked throttling documentation indeed explains why the results of LH audit differed so much from those of the Performance tab, how (AFAIU) they can currently become consistent only when Simulated throttling is unticked and how you plan to make the two audits always consistent with one another without needing to untick Simulated throttling (which will become the only option). 

Maybe other people confused by that inconsistency as I was, would tackle this issue and understand like I eventually did.

Thanks so much for helping me out with this (non) issue.

**Comment by MickeyKay** [comment]
Thanks for digging in! I just ran into this as well and will be disseminating for my team as well, as there's been some confusion there.

**Comment by MickeyKay** [comment]
That said. . . even with throttling enabled, Lighthouse numbers don't seem to match the linked trace. For example. . .

Here's my Lighthouse TTI metric:
![image](https://user-images.githubusercontent.com/3189678/77271641-739a9600-6c6c-11ea-983f-ba6fbc7ce68c.png)

However when I click the View Trace link, my entire trace is only ~15s long:
![image](https://user-images.githubusercontent.com/3189678/77271658-785f4a00-6c6c-11ea-8c5e-a00861b5ec30.png)

Is there a better way to ensure the LH #'s match up with Chrome dev tools' trace so that I can do some more granular analysis of what's pushing key metrics out?

**Comment by MickeyKay** [comment]
Ah, scratch that. Just read https://github.com/GoogleChrome/lighthouse/blob/9931d2438fe0d0c4cbb477bf9cec2dd52a3bad61/docs/throttling.md#devtools-audits-panel-throttling
