### ISSUE TITLE
says no meta name viewport in audit. It's there. 

### ISSUE THREAD

**Issue by webgurumike** [GoogleChrome/lighthouse#10393]
says no meta name="viewport" in PWA audit. It's there.  Also says page load is 14.7 seconds. Not seeing such terrible loads. Is it referring to any and all activity, even XHR?

**Comment by wardpeet** [comment]
Hi @webgurumike!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to share the site url with us.

**Comment by patrickhulce** [comment]
Like @wardpeet said, we have a [complete bug report template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) so we can see what you're talking about ;)

**Comment by patrickhulce** [comment]
re: page load. Yes, all of a page's activity is considered, and performance is reported for mobile conditions by default. See the [docs](https://web.dev/lighthouse-performance/) to learn what the different metrics are measuring.

**Comment by patrickhulce** [comment]
If you have a bug to file, please complete bug report template and file a new one.
