### ISSUE TITLE
<iframe> with no `title` should use ancestor element's `title`

### ISSUE THREAD

**Issue by maxlever** [GoogleChrome/lighthouse#10406]
Iframes with no title but with an ancestor with a title are marked as errors, yet this spec says that `title` can be inherited from parent: https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute:
> If this attribute is omitted from an element, then it implies that the title attribute of the nearest ancestor HTML element with a title attribute set is also relevant to this element. 

In my particular case, `<amp-iframe>`s should be able to propagate their title to `<iframe>`s. Please let me know if I am mistaken about the specification.

#### Provide the steps to reproduce
1. Run LH on https://www.axios.com/carbon-emissions-rate-slower-2019-f235af5a-fbd8-46fc-a196-228233f20f16.html, or on any snippet containing, for example
```html
<div title="iframe title">
  <iframe src="http://placekitten.com/100" ></iframe>
</div>
```
2. Observe that there is an A11Y error saying that the `<iframe>` does not have a `title` attribute, and yet its <amp-iframe> parent has a `title` attribute should be applied to it.

#### What is the current behavior?
iframes that are missing an explicit `title` but have a parent with a `title` are marked as missing a `title`.

#### What is the expected behavior?
iframes with a parent `title` should be marked as valid.

#### Environment Information
All environments

**Related issues**
https://github.com/ampproject/amphtml/issues/17308#issuecomment-426399152

**Comment by patrickhulce** [comment]
Thanks very much for filing @maxlever! We receive this failure directly from [axe-core](https://github.com/dequelabs/axe-core). Since this appears to be reproducible with axe alone (and an intentional decision based on their [documentation](https://dequeuniversity.com/rules/axe/3.0/frame-title)), would you find filing there for discussion?

Apologies for the 3rd trip for this issue :) But we'll end up respecting whatever is decided there on the next update!

**Comment by maxlever** [comment]
@patrickhulce ok, thanks for the info! I have posted the same issue here: https://github.com/dequelabs/axe-core/issues/2071

**Comment by maxlever** [comment]
@patrickhulce closing this issue as [axe-core says this is working as intended](https://github.com/dequelabs/axe-core/issues/2071) -- the HTML spec says that the ancestor element's title is "relevant" but not inherited.

**Comment by patrickhulce** [comment]
Thanks very much for following through on this @maxlever! 👍
