### ISSUE TITLE
PWA audit: warn if maskable icon is transparent

### ISSUE THREAD

**Issue by NotWoods** [GoogleChrome/lighthouse#10409]
**Feature request summary**

Add an audit that warns if a maskable icon has transparent pixels (if a maskable icon is provided).

**Are you willing to work on this yourself?**
Yes

**What is the motivation or use case for changing this?**
[Maskable icons](https://web.dev/maskable-icon/) are meant to be fully opaque, since icons on Android Oreo and up and iOS cannot have transparent regions. When transparent icons are provided, the browser fills the space with a color of its choosing, which varies depending on the browser and tool.

**How is this beneficial to Lighthouse?**
Optimal "add to homescreen" functionality is part of building a great PWA, and should therefore be reflected in the PWA audit scoring. Using transparent regions results in undefined fill colours and can cause confusion for developers.

**Comment by connorjclark** [comment]
You say that [android does a white backdrop](https://web.dev/maskable-icon/#what). Is that changing?

We currently don't fetch the icon ourselves, and only know about errors fetching w/e Chrome decides to fetch. So at the limit we are confined to checking the transparency of a single icon (we don't want to fetch everything).

Some problems I anticipate:

* We currently don't know _which icon Chrome chose_, but we could just use `Page.getManifestIcons` and then fetch it.
* Finding transparency would involve some canvas / image data hack, probably nbd

Maybe it makes sense for this to be done in DevTools, perhaps via the new issues panel.

**Comment by NotWoods** [comment]
I would say that providing transparent maskable icons is an easy mistake and would lead to surprising results. Developers adopt maskable icons so they can control the entire icon appearance, but might end up with a white background in their icon because of the use of transparency. I've previously had folks ask me about the issue.

I'd be happy to see this in DevTools instead if makes more sense for the feature, I wasn't aware of the image fetching limitations.

**Comment by connorjclark** [comment]
yea we think decoding images in LH is gonna be slow. better fit in devtools.

Could you follow up w/ this on the devtools dev mailing list? `devtools-dev@chromium.org`.

**Comment by NotWoods** [comment]
Filed an [issue for DevTools](https://bugs.chromium.org/p/chromium/issues/detail?id=1113532), is it possible to CC the mailing list there? Apologies for the late follow up.
