### ISSUE TITLE
Manifest: "found icons sizes" debugString should be displayValue

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/lighthouse#1040]
How come the `--poor-color` is so bright and highlighted in our reports?
It is used for `Found icons of sizes: 152x152,144x144,192x192,256x256,512x512"

Can we use a more subtle color there?

![screenshot 2016-11-24 at 9 45 14 am](https://cloud.githubusercontent.com/assets/634478/20591805/b7dc22ca-b22a-11e6-812f-5f41c49946d9.png)

**Comment by ebidel** [comment]
Typically those are `debugString` explanations for failures. In these cases, they're not really failures and we shouldn't be red.

Instead we should move the found sizes to `displayValue` (e.g. the websql audit) so the values are presented, but don't appear like they're errors.
