### ISSUE TITLE
Lighthouse is not responding and stuck

### ISSUE THREAD

**Issue by kunjsanghavi** [GoogleChrome/lighthouse#10405]
![NSJkrcuxRR+GUaS+ydVk2Q_thumb_1](https://user-images.githubusercontent.com/48124145/75571823-f7070400-5a7f-11ea-9f08-3cd187f4cc57.jpg)

Sorry cannot provide url of the webapp being tested

**Comment by patrickhulce** [comment]
Duplicate of #10103, see workarounds mentioned there for resolution.
