### ISSUE TITLE
NO_TTI_CPU_IDLE_PERIOD error - Unsure why

### ISSUE THREAD

**Issue by Connor-Moran** [GoogleChrome/lighthouse#10410]
I'm running Google Lighthouse via a program that launches a console window and uses CLI commands to run lighthouse.

For some reason, however, specifically with Amazon's website, (https://www.amazon.co.uk/ and related pages) I get a NO_TTI_CPU_IDLE_PERIOD error some of the time. Out of every 10 audit reports I generate, 4 of them or so will result in this error, giving me a null performance value and causing my program to throw an exception.

The main thing that confuses me here is that it happens seemingly at random and I can't see why. If it always failed it would be a little better, but I'm not sure what is causing this.
Running Google Lighthouse via Chrome DevTools works perfectly fine with no issues.

I know what this is caused by but I can't seem to understand why it works seemingly half the time.
https://www.debugbear.com/docs/lighthouse-problems

Any ideas?

**Comment by patrickhulce** [comment]
Thanks for filing! I'm assuming this program is using `--throttling-method=devtools` or `--throttling-method=provided`? This error most commonly happens for 1 of 2 reasons.

1) The page took too long to load and we hit our load timeout before the page settled down.
2) The `PerformanceObserver` in the page thought the page was quiet, so Lighthouse stopped tracing.

In the case of amazon I'm betting it's the latter. If so, you can try manually increasing the `cpuQuietThresholdMs` in the config of the `defaultPass` to something much larger like `10000`

https://github.com/GoogleChrome/lighthouse/blob/2d287eb4131f49e2f4e1b92f61ae88f9d9b4f1ac/lighthouse-core/config/default-config.js#L125-L127

If it's the first case, then you can fix it by increasing --max-wait-for-load to something very large like 120000.

If it's using `--throttling-method=simulate` then this is very unexpected and a very strange bug that we'd love to investigate if you could get us copies of the `devtoolsLog` and `trace` from `--save-assets`

**Comment by Connor-Moran** [comment]
This is using `--throttling-method=provided`.

I'll try fiddling with `cpuQuietThresholdMs` and see what happens.

Thanks!

**Comment by Connor-Moran** [comment]
Okay so I tried setting `cpuQuietThresholdMs` to 120000 and that didn't work. Seemed to fail just as frequently. I'll try using the `--max-wait-for-load` command.

**Comment by Connor-Moran** [comment]
Nope. Still failing with the `--max-wait-for-load` set to 120000.
This is the command I'm running:

`lighthouse "https://www.amazon.co.uk/" --view --disable-storage-reset --output=json --output-path="C:\Users\User\Work\Projects\GoogleLighthouse\AmazonTest.json" --chrome-flags="--headless" --emulated-form-factor=desktop --throttling-method=provided`

**Comment by patrickhulce** [comment]
Just to confirm, how were you setting `cpuQuietThresholdMs`? If you successfully set it to `100000` you should have seen warnings in your logs that the whole run was timing out because the page took too long.

Did you see those warnings before you changed `--max-wait-for-load`?

**Comment by Connor-Moran** [comment]
Oh I tried changing the `default-config.js` file directly. Was that not the right way?

And nope. No warnings for `--max-wait-for-load`.

**Comment by patrickhulce** [comment]
Ah then it's not taking effect :) This should definitely fix the problem, so let's try to get it working.

The expected way to do this would be to create a custom config that modifies this and pass that to Lighthouse through `--config-path`

**custom-config.js**
```js
module.exports = {
  extends: 'lighthouse:default',
  passes: [
    {passName: 'defaultPass', cpuQuietThresholdMs: 120000}
  ]
}
```

```
lighthouse "https://www.amazon.co.uk/" --config-path=./custom-config.js

**Comment by Connor-Moran** [comment]
This seems to have worked thanks. :)

This seems to be affecting the performance score though, what would you recommend I set it as?

**Comment by patrickhulce** [comment]
> This seems to be affecting the performance score though

This is expected. The scenario where we're we were previously erroring is the case where TTI is much higher and CPU activity didn't quiet down. There are likely non-deterministic late JS executions that are causing the metrics to vary. When the tasks occur within 5s of the rest of the app, the score is worse but when they happen just late enough that we don't notice them the score is better.

 I'd suggest something in the realm of `7000` for `cpuQuietThresholdMs` going up to `10000` if things still aren't smooth.

**Comment by Connor-Moran** [comment]
7000 and 10000 both aren't smooth. Going to try 20000. Amazon really is being a pain here, no other site has issues other than them.

**Comment by patrickhulce** [comment]
> 7000 and 10000 both aren't smooth.

This is very surprising to me! I'll try to dig in a bit too to see if there's something extra we could be doing.

**Comment by Connor-Moran** [comment]
20000 seems to do it. Very strange.
It was certainly getting better, but it still nulled every so often.

**Comment by Connor-Moran** [comment]
It seems to have resolved itself, just stopped nulling now. :)
