### ISSUE TITLE
Why is Pagespeed from Google Dev showing half TTI speed?

### ISSUE THREAD

**Issue by schroef** [GoogleChrome/lighthouse#10426]
Im trying to optimize a site and im reading up upon all data about omtomizing files. Started reading tons of Google dev articles and noticed a different page speed test 
https://developers.google.com/speed/pagespeed/insights/

the results of this test show a TTI of about half the time of Lighthouse. Ive also noticed that light house results reallu jump up and down. Below 2 runs, i got this effect all the time
![Screen Shot 2020-03-04 at 18 45 13](https://user-images.githubusercontent.com/6923008/75930135-5c743f80-5e48-11ea-9f75-584e9fb455b7.png)
![Screen Shot 2020-03-04 at 18 44 59](https://user-images.githubusercontent.com/6923008/75930137-5d0cd600-5e48-11ea-9c75-6a353f780ba9.png)

im testing this page promotiespullen.com
![Screen Shot 2020-03-04 at 18 48 23](https://user-images.githubusercontent.com/6923008/75930326-bffe6d00-5e48-11ea-8d4e-d673d44f1306.png)

**Comment by connorjclark** [comment]
have you read https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md

**Comment by schroef** [comment]
I also feel Lighthouse times are not as live site. The google speedtest feels more like real time measurements.

**Comment by schroef** [comment]
I entered this form through a link and it was blanco, i didnt not see the template. Im using incognito window, but that shouldnt make a difference. 

Its actually from the main page, see below
https://github.com/GoogleChrome/lighthouse/issues/new
it should be:
https://github.com/GoogleChrome/lighthouse/issues/new/choose

![Screen Shot 2020-03-04 at 18 52 44](https://user-images.githubusercontent.com/6923008/75930637-65b1dc00-5e49-11ea-93aa-8b33ba872d86.png)

That links to a blanco issue form, it bypasses the template selection part
![Screen Shot 2020-03-04 at 18 54 02](https://user-images.githubusercontent.com/6923008/75930691-8c701280-5e49-11ea-97c0-e9501f31aa6a.png)
![Screen Shot 2020-03-04 at 18 53 52](https://user-images.githubusercontent.com/6923008/75930693-8da13f80-5e49-11ea-903c-41ce85566719.png)

**Comment by connorjclark** [comment]
thank you @schroef and sorry for my assumptions! I'll fix that now.

For your issue, is this a correct summary? You are seeing much better metrics PageSpeed Insights, but locally you see lower and results with much more variance.

What settings are you using local (that's Chrome DevTools, right? What version of Chrome? chrome://version )

**Comment by schroef** [comment]
Sorry for late response Connor, had to put it aside for couple days. Im using 1.0.4044.43 (Official Build) beta (64-bit)
What exactly do you mean by "use locally", did you meant my Chrome version or my networks specs?

Indeed im seeing better results using the page speed test from Chrome Developer site vs Lights Performance test in Chrome DevTools. Also the chrome link to the page speed test is way more consistent, where Lighthouse varies a lot. I did read that link about possible influences. But if that is through how can it even be measured then? One would need to do say 10 tests and use an average of that and then still its not proper. I wonder why the Chrome page speed test is more consistent while using same network same everything concerning hardware.

**Comment by patrickhulce** [comment]
Thanks for providing the URL @schroef!

While the score does move around a bit, the results I see locally using identical settings to PSI (clean Chrome profile, simulated default throttling, mobile, no extensions, etc) reflect the variability I see in the page itself and are within the expected variation described in [the docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md). I'd double check all of your settings are the same, that the device meets the guidelines for minimum hardware in that document, and as you said, run multiple times.
