### ISSUE TITLE
Status code: 504

### ISSUE THREAD

**Issue by bomberg** [GoogleChrome/lighthouse#10429]
#### Provide the steps to reproduce
1. Run LH on https://www.intelligent-protection.co.uk/bodyguard-services-monaco.html
  

#### What is the current behavior?
I am getting this message on this page only https://www.intelligent-protection.co.uk/bodyguard-services-monaco.html:

There were issues affecting this run of Lighthouse:
Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 504)

I had recently changed the images over from .jpg to ,webp and doing some tests on page speed.

#### What is the expected behavior?
To not have this issue...

* Chrome version:

**Comment by patrickhulce** [comment]
Thanks for filing @bomberg. This means there was a temporary server issue with `www.intelligent-protection.co.uk`. This is not a Lighthouse bug. 

> Make sure [...] that the server is properly responding to all requests. (Status code: 504)

504 Gateway Timeout typically means the proxy server couldn't get a response from whatever was supposed to serve the page in time and is usually temporary.

See #2784 for more details on the different types of common server failures.
