### ISSUE TITLE
how to get the value of median and falloff in scoring spreadsheet

### ISSUE THREAD

**Issue by wanghongjuan** [GoogleChrome/lighthouse#10432]
**Summary**
I am learning how to convert time into scores in lighthouse, but I'm not clear that how to get the value of "Metric Scoring Median" and "Metric Scoring Falloff" in [scoring spreadsheet](https://docs.google.com/spreadsheets/d/1up5rxd4EMCoMaxH8cppcK1x76n6HLx0e7jxb0e0FXvc/edit#gid=283330180), and what's the "Potential value"? Is there a detailed explanation document? Many thanks for your help.

**Comment by paulirish** [comment]
@wanghongjuan do you really need those values? they are more for our internal calculations than something you need.

try https://paulirish.github.io/lh-scorecalc/ . we think it's a better UI for working with the perf scores.

**Comment by exterkamp** [comment]
Closing. If you have a concrete need for this reopen.
