### ISSUE TITLE
My site is responsive, how can I speed it up?

### ISSUE THREAD

**Issue by koradz** [GoogleChrome/lighthouse#10438]
Hello
We have a sports site

[]([](https://www.kora.news/))
[](https://www.kora.news/
)Responsive to all devices, but the speed is slow
How do I speed it up
Thank you

**Comment by koradz** [comment]
link site
https://www.kora.news/

**Comment by exterkamp** [comment]
Have you run Lighthouse on the site and followed the "Learn More" links? Running Lighthouse in Chrome DevTools will give you a report on the site's performance.

*or*

Running that site in [Pagespeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.kora.news%2F&tab=mobile) will have some details on the largest Performance opportunities. There will be links labeled "Learn More" with links to documentation.
![image](https://user-images.githubusercontent.com/6392995/76153330-59af5f80-607f-11ea-9b3f-f497f8b1c963.png)

*or*

Also try running your site in https://web.dev/measure/ which will give you links to documentation right there in web.dev about how to fix the problems that Lighthouse has found.
