### ISSUE TITLE
"Properly size images" incorrectly shown as "Passed"

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/lighthouse#10431]
#### Provide the steps to reproduce
1. Run LH on https://use-media-queries-unoptimized.glitch.me/

The site requests the same [background image](https://use-media-queries-unoptimized.glitch.me/images/background-desktop.jpg) of **1006KB** regardless of the screen size.

#### What is the current behavior?

The [properly size images](https://web.dev/uses-responsive-images/) opportunity is shown as passed:

![properly_size](https://user-images.githubusercontent.com/15170359/75995676-c6cdc400-5eca-11ea-8503-138a07707fd7.png)

#### What is the expected behavior?

On previous versions of Lighthouse (I don't have the version number), this opportunity was marked as not passed:

![properly_size_failed](https://user-images.githubusercontent.com/15170359/75995797-f086eb00-5eca-11ea-9638-f2ddd570582a.png)

That should be the expected behavior, given the size of the image and the way is being displayed (same image for all devices).

#### Environment Information
* Affected Channels: 
* Lighthouse version: Tested it in 5.6.0 ([the one](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https://use-media-queries-unoptimized.glitch.me/) that's running in Web.dev) and in 5.7.0 in Chrome.
* Chrome version: 80.0.3987.122
* Operating System: Mac OS

**Related issues**
A [similar issue ](https://github.com/GoogleChrome/lighthouse/issues/9726) has been already reported, but  in that case the tool was working properly.

**Comment by patrickhulce** [comment]
Thanks for filing @demianrenzulli! We [started intentionally ignoring CSS background images](https://github.com/GoogleChrome/lighthouse/pull/8940) because of the false positive rate for spritesheet assets and the significant complexity in properly handling responsive image declarations in CSS compared to `<picture>`.

Sorry that this is one of the cases where it still would've been useful to have around.

**Comment by demianrenzulli** [comment]
Thank you @patrickhulce! It makes sense.

The reason I'm using that demo, is because we are about to release a [Optimize CSS Background Images with Media Queries guide](https://github.com/GoogleChrome/web.dev/issues/1013) on Web.dev, and we were using the results of the Lighthouse tests to show the before / after of the optimization.

Since this is a known limitation, and it's not going to change, it seems like the best we can do is to eliminate the use of Lighthouse for this guide, and rely exclusively on DevTools.

cc // @kaycebasques

**Comment by patrickhulce** [comment]
Aw bummer. Yeah unfortunately manual inspection with DevTools is probably the best way to navigate this now.

**Comment by demianrenzulli** [comment]
Thanks for the context @patrickhulce! Closing this one now 👍
