### ISSUE TITLE
CSS Animations influence On FID

### ISSUE THREAD

**Issue by nechita** [GoogleChrome/lighthouse#10430]
How big of an influence can CSS animations have on FID, if we apply CSS classes to elements via JS?

We are looking for ways to improve FID, because the website is flagged as having slow pages on mobile by Google Search Console and big FID is the main offender in our case (over 350ms).

I have the following behavior on the website:
- we display content cards in the form of a table or in the form of a grid, depending on a cookie.
- the grid/table layout gets a "fade in" effect via a CSS class added to the element by JS code based on the value we read from the cookie

This is a quite common case, where you apply a specific change to the layout of your page based on a stored cookie.

**Comment by patrickhulce** [comment]
A CSS animation itself should not have any effect on FID. The JS where the CSS classes are added to the elements might be having a significant impact though. When you trace the page in question in DevTools Performance tab you're looking for the large yellow blocks. That's what you need to breakup to reduce FID.

You could also instrument your page using the advice in the [FID documentation](https://web.dev/fid/) to find out more specifically when your delays are occurring.

**Comment by nechita** [comment]
@patrickhulce thanks! TIL.
