### ISSUE TITLE
Run lighthouse report at each step in an Angular SPA

### ISSUE THREAD

**Issue by harish2rock** [GoogleChrome/lighthouse#10435]
I am using Puppeteer to crawl through my SPA. On page load, there are only two radio buttons. On selecting either of them, new html is added to the DOM. How do I create a lighthouse report at each of these steps? One report on page load, and another report when puppeteer clicks the button and generates new html.

Here is the snippet - 
```
await page.goto(opts.url); 

 await page.screenshot({
                path: 'audit-images/before_audit.png',
                fullPage: true
            });

//Generate Lighthouse Report here.

//Click a radio option
await page.click('input[id=appt-yourself]');
            console.log("Successfully clicked yourself");
            await page.screenshot({
                path: 'audit-images/after click yourself.png',
                fullPage: true
            });

//
Generate Lighthouse Report here.

//Currently, I have only this at the end - 
await lighthouse(opts.url, opt, null).then(results => { 
//this basically generates report when the url is loaded, but not at each step.
});
```

**Comment by connorjclark** [comment]
We have some advanced puppeteer examples:

* https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/integration-test
* https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/auth

These should help.

**Comment by harish2rock** [comment]
Thanks @connorjclark . The  examples suggest running audits on different urls like here - https://github.com/GoogleChrome/lighthouse/blob/master/docs/recipes/auth/example-lh-auth.js#L64 

In my application,  I only have on URL and dynamic html is generated based on user actions, something like a form wizard. How to run audit in each scenario in this case where there are no multiple URLs?

**Comment by connorjclark** [comment]
We don't have a good way to do that. You'd need to create a custom config with a custom gatherer that sets up the page as you wish. Clearly, that's not very convenient - we just haven't devoted resources to such SPA use cases.

Some alternatives:

* You could configure your app to have a URL per-view.
* If you were to do the complicated setup I described, it seems you'd just be getting additional a11y information. You may have a better time installing the [axe extension](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US) and viewing the issues it generates as you control the page yourself.

**Comment by harish2rock** [comment]
@connorjclark - Thanks! I came across https://github.com/GoogleChrome/lighthouse/blob/master/docs/recipes/custom-gatherer-puppeteer/custom-gatherer.js and implemented a custom gatherer of my own using puppeteer and do a series of page clicks. 
Now how do I  run an accessibility report on the newly generated html based on these clicks?

**Comment by peterwilliams-atl** [comment]
@harish2rock did you end up solving this?

**Comment by paulirish** [comment]
https://github.com/addyosmani/puppeteer-webperf just came out and should hook you up. 👍

**Comment by harish2rock** [comment]
@paulirish -  Awesome..will test that. thanks!

**Comment by peterwilliams-atl** [comment]
@paulirish Thanks for the update, that resource does look awesome! I think from those examples I can work out how to setup Puppeteer to load the page, perform some actions, and then run various tracing and perf-related reports (things someone might've previously used Lighthouse for). 

But what about Lighthouse a11y audits? The examples with Lighthouse and Puppeteer don't include any Puppeteer page setup actions, and it looks like Lighthouse would just open up a fresh load of `url`. I'm interested in automating audits for pages that require some user interaction to finish loading (scrolling to reveal lazily-rendered components, expanding panels, closing modals, etc).

There's a longer-running discussion about that possibility in this other issue: https://github.com/GoogleChrome/lighthouse/issues/3837

Is there a solution for that in https://github.com/addyosmani/puppeteer-webperf that I've overlooked? Or is that still a pending feature request?

**Comment by harish2rock** [comment]
> @paulirish Thanks for the update, that resource does look awesome! I think from those examples I can work out how to setup Puppeteer to load the page, perform some actions, and then run various tracing and perf-related reports (things someone might've previously used Lighthouse for).
> 
> But what about Lighthouse a11y audits? The examples with Lighthouse and Puppeteer don't include any Puppeteer page setup actions, and it looks like Lighthouse would just open up a fresh load of `url`. I'm interested in automating audits for pages that require some user interaction to finish loading (scrolling to reveal lazily-rendered components, expanding panels, closing modals, etc).
> 
> There's a longer-running discussion about that possibility in this other issue: #3837
> 
> Is there a solution for that in https://github.com/addyosmani/puppeteer-webperf that I've overlooked? Or is that still a pending feature request?

I would agree with this. Is there a way to perform a11y audit at each user interaction that is included in https://github.com/addyosmani/puppeteer-webperf ?

**Comment by patrickhulce** [comment]
You can write this sort of thing manually using a combination of addy's repo and the Lighthouse accessibility gatherer.


Something sorta like

```js
const axeLibSource = fs.readFileSync(require.resolve('axe-core/axe.min.js'), 'utf8');

it('should be accessible', async () => {
  const axeFn = `(() => {
    ${axeLibSource};
    return window.axe.run(document, {
      elementRef: true, 
      runOnly: {type: 'tag', values: ['wcag2a', 'wcag2aa']},
      resultTypes: ['violations'],
    })
  })()`;

  const axeResults = await page.evaluate(axeFn);
  expect(axeResults.violations).toHaveLength(0);
})
```

DISCLAIMER: untested

**Comment by harish2rock** [comment]
@patrickhulce  - That's what I ended up doing. I made use of axe-puppeteer from https://github.com/dequelabs/axe-puppeteer to generate a11y report, when user interactions are performed after the page has loaded. My working example is like - 

      await page.goto(opts.url);

        /*----Someone Else Flow----*/
        await page.waitFor(100);

        //click someone else
        await page.click('input[id=appt-someone]');
    
        console.log("Successfully clicked someone else");
        await page.screenshot({
            path: 'audit-images/someone-else-click.png'
        });

        await page.click('input[id=firstname]');
        await page.keyboard.type('test user');

        console.log('running axe accessibility audit');

        //run axe puppeteer
        const results = await new AxePuppeteer(page).analyze();
         console.log(results);

Would have loved to integrate this with lighthouse report. 
I now have  two different reports - a perf report from lighthouse and a a11y report from axe.
