### ISSUE TITLE
NO_FCP on http://www.sevamed.net/

### ISSUE THREAD

**Issue by aliveupstairs** [GoogleChrome/lighthouse#10440]
#### Provide the steps to reproduce
1. Run LH on http://www.sevamed.net/
  

#### What is the current behavior?

LH gives errors on all fronts.

	There were issues affecting this run of Lighthouse:
		• Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)

#### Environment Information
* Affected Channels: DevTools
* Chrome version: 82.0.4062.3
* Operating System: Linux manjaro 5.5.7-1-MANJARO

Note: Taking a look at the DOM, it seems that the website is a frameset of another pefectly Lighthousable website.

**Comment by patrickhulce** [comment]
Thanks very much for filing @aliveupstairs and for pointing out the frameset point! We'll de-dupe this into https://github.com/GoogleChrome/lighthouse/issues/3654 which tracks separate frameset failure identification.
