### ISSUE TITLE
pagespeed insights default throttling

### ISSUE THREAD

**Issue by bogdanaslt** [GoogleChrome/lighthouse#10445]
I think in 2020 Google should increase default throttling configuration for PageSpeed insights and Lighthouse (web.dev). 150ms latency is too high for any network, 1.6Mbps download speed is to low for any provider (as noted in https://www.speedtest.net/global-index average speed for mobile is 30Mbps) 

**What is the motivation or use case for changing this?**
To deliver more accurate information for end-users

**How is this beneficial to Lighthouse?**
More usable tool to inspect website speed

**Comment by paulirish** [comment]
> 150ms latency is too high for any network

We think this is representative of an ~85-90th percentile mobile connection. 

We're open to reviewing recent global network diagnostic data of real-world connections.

**Comment by dsozzi** [comment]
Thanks @paulirish but I think LH should have a better configuration for desktop tests. It seems many issues are opened regarding the misleading “simulated throttling” flag and unexpected results which are very much lower than old LH (chrome v. < 80). I understand the reasons behind the changes regarding the throttling options but it would be nice to have test for desktop version with no network cap or cpu slow down. When testing mobile version then it’s fine to have the current config in my opinion.

**Comment by patrickhulce** [comment]
@dsozzi the desktop change in Chrome was unintentional and there's a separate bug for that (https://github.com/GoogleChrome/lighthouse/issues/10315). It's been fixed but unfortunately it won't make it to Chrome stable for a bit.

**Comment by dsozzi** [comment]
Oh great @patrickhulce. Thanks

**Comment by pentago** [comment]
Can we revisit this again, after 2 years now? As said, used throttling is way too steep and likely doesn't represent the real situation.
