### ISSUE TITLE
[Question] How to enable stack specific messages on lighthouse cli?

### ISSUE THREAD

**Issue by jmdelacerna** [GoogleChrome/lighthouse#10455]
**Summary**
How could we enable stack specific messages on lighthouse cli report?
tried --gather-mode, stack was detected but when generating a report, no stack specific message is displayed. How to enable it? Lighthouse ver 5.6.0

**Comment by patrickhulce** [comment]
Thanks for filing @jmdelacerna! I'm not sure what you mean though. 

What stack messages are you expecting to see in the report? Are you referring to the react/wordpress/"stack pack" advice that appear on certain individual audits?

**Comment by jmdelacerna** [comment]
Hello @patrickhulce thank you for your response, yes that is what I was referring to.

**Comment by patrickhulce** [comment]
They will automatically appear on the applicable audits when the stack is detected, there is no action that should need to be taken. If you think you've found a site that should be displaying them, but isn't, the URL with the [bug report template details](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) would be much appreciated!

**Comment by jmdelacerna** [comment]
@patrickhulce thank you, I will fillup the bug report template. I tried comparing the audits with pagespeed insight and the audit in chrome dev tools, however both reports show stack specific advice.
