### ISSUE TITLE
Chrome’s native lazy load for images interferes with Lighthouse results.

### ISSUE THREAD

**Issue by ivanbechevmrf** [GoogleChrome/lighthouse#10468]
Hello, I implemented loading - lazy attributes and removed all javascript, previously responsible for the lazy loading. Now when the browser to decide when to load images, this started to interfere with the Lighthouse performance test. The audit is giving me recommendations to “Consider lazy-loading offscreen and hidden images after all critical resources have finished loading to lower time to interactive.” It looks like Lighthouse does not respect the decisions that the browser has made in relation to when to load images, that are below the fold. 

<img width="756" alt="Screenshot 2020-03-16 at 21 06 41" src="https://user-images.githubusercontent.com/53761301/76795699-28930580-67ca-11ea-9d59-5d7c4d6063b0.png">

* Lighthouse version:
* Chrome version: 80.0.3987.132
* Operating System: MacOS Catalina 10.15.2

**Comment by patrickhulce** [comment]
Thanks for filing @ivanbechevmrf! This has been fixed but just not published to all channels yet :)

See https://github.com/GoogleChrome/lighthouse/issues/10259 for details.

**Comment by ivanbechevmrf** [comment]
Thanks for the quick response @patrickhulce
