### ISSUE TITLE
offscreen-images: allow eager loading within three viewports 

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#10471]
[`offscreen-images`](https://github.com/GoogleChrome/lighthouse/blob/ee7cb3ba9371428b71d4a7b3696525712a32f7d2/lighthouse-core/audits/byte-efficiency/offscreen-images.js) suggests lazy loading any images outside of the initial viewport (plus a little leeway on all sides).

After discussion in https://github.com/ampproject/amphtml/issues/25682 and in the latest eng meeting, we've decided to bump that up to three viewports. It's still a little arbitrary, but the impact is minimal, it lines up with the leniency of other lazy loading approaches (like the very large buffer in native lazy loading), and it's arguably a better user experience.

----

whatwg discussion on this issue: https://github.com/whatwg/html/issues/5408

**Comment by addyosmani** [comment]
To add one small note from the sync: one of the nice things about the three viewports solution is that it doesn't require us to introduce special-casing for every lazy-loading solution (which could get a bit out of hand over time...). Instead, this should be lenient enough to cater for a number of approaches as Brendan mentioned.
