### ISSUE TITLE
Diff between PSI and web.dev

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#10484]
**Summary**
When run PSI  and web.dev over the same url, PSI report 3 images and web.dev report 7, This diff maybe is due diferennces on how lazyload works in both channels, but... both reports the same size, and 3 images don´t weigth the same as 7.
![tempsnip](https://user-images.githubusercontent.com/22342793/77112387-32ff0a80-6a29-11ea-8518-ae94f2b05d12.jpg)
![tempsnip1](https://user-images.githubusercontent.com/22342793/77112391-34303780-6a29-11ea-8152-2b30c515f925.jpg)

**Comment by connorjclark** [comment]
URL? As text, please.

**Comment by Lofesa** [comment]
Sure: https://intersindicalrm.org/
Maybe related with #10390 ?

**Comment by connorjclark** [comment]
Cool, thanks for the background info. Let's dedupe this issue and discuss in #10390.
