### ISSUE TITLE
Lighthouse v6: cumulativeLayoutShift is rounded to 0 in metrics section

### ISSUE THREAD

**Issue by alekseykulikov** [GoogleChrome/lighthouse#10486]
#### Provide the steps to reproduce
Run LH 6.0.0.beta on any URL

```bash
lighthouse https://www.apple.com/
```  

#### What is the current behavior?

`audits.metrics.details[0].cumulativeLayoutShift` is 0

But `audits.cumulative-layout-shift.numericValue` is `0.19574185519748266.`

#### What is the expected behavior?

I expect the value rounded to 3 decimals, like in the HTML Report: `0.196`, because [a good CLS value](https://web.dev/cls/#what-is-a-good-cls-score) is `0.1` and it's a first float value in `metrics`.

The problem is related to this line of code: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/metrics.js#L41 

#### Environment Information
* Affected Channels: All
* Lighthouse version: v6.0.0.beta
* Chrome version: v83.0.4090.0
* Node.js version: v12
* Operating System: Mac

**Comment by paulirish** [comment]
Great catch. I'll take care of this.

**Comment by paulirish** [comment]
@patrickhulce could you take this?  should be quick

**Comment by patrickhulce** [comment]
sure thing 👍
