### ISSUE TITLE
Add context to extension error reporting

### ISSUE THREAD

**Issue by wardpeet** [GoogleChrome/lighthouse#1049]
It would be nice if we could add url & perhaps some audits that were unchecked to the github reporting so we have more context on solving these bugs

**Comment by ebidel** [comment]
https://github.com/GoogleChrome/lighthouse/commit/34eedfb002041e56bbdfd8b9496289fb0e61a79a will give us better insight. Can we use https://github.com/GoogleChrome/lighthouse/issues/1020 for making the extension bug reporting better?

**Comment by wardpeet** [comment]
I will close this, there are better issues improving this :)
