### ISSUE TITLE
Seems inaccurate

### ISSUE THREAD

**Issue by MrVibe** [GoogleChrome/lighthouse#10492]
I am testing my PWA and the whole report is generated in less than 15 seconds and it states the site's first contentful paint is 44 s. The site does not even take 1 second to load.

See video : https://www.screencast.com/t/NM1pQoo1AcGr

Something's not correct. I am using color picker and loom browser extensions on chrome.

**Comment by patrickhulce** [comment]
The performance metrics reported are simulating a load on a mobile device and typical mobile network conditions. I'm guessing the blocking resources and/or the main page you have is very large which takes no time to download on `localhost` but would take ~45s to download on slow 4G connection.

Read more about [Lighthouse throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md)

**Comment by MrVibe** [comment]
Thank you makes sense.
