### ISSUE TITLE
CLI should warn if Node version < 5.x

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#105]
(orig reported at #73 )

Since we're using a bunch of es2015 features, node 4 isn't supported.

The cli should error and exit if you're not running using a 5.x runtime.

question: Should the error message recommend using nvm?

**Comment by paulirish** [comment]
>> question: Should the error message recommend using nvm?

@gauntface sez:

> I think a message to upgrade or use NVM if you need older node versions too is a safe bet

sg

**Comment by samccone** [comment]
telling people what software to install gets really messy fast, we already know the CLI tool will be for a more "Experienced" dev, so I think just throwing a nice message saying `<Lighthouse requires node 5.9..>` will be more than enough.

**Comment by deepanjanroy** [comment]
Is it ok to add in a dependency like https://www.npmjs.com/package/node-version-compare? In that case we can have a nice minVersion variable and change that in the future. Otherwise I can just look at the first/second char of the string and make sure there's something >= 5 there.

**Comment by samccone** [comment]
checkout the semver module. That is what we will want to use here :sparkles:

**Comment by deepanjanroy** [comment]
sweet thanks :)
