### ISSUE TITLE
NO_TTI_CPU_IDLE_PERIOD if the page has a slow FCP but is idle immediately after it (devtools/provided throttling only)

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#10503]
#### Provide the steps to reproduce

I most consistently get the error in DevTools:

1. Got to https://persistent-friendly-authority.glitch.me/?delayFcpMs=1700
2. Open DevTools
3. In Lighthouse settings untick "Simulated throttling"
4. Click "generate report"

I get it with the CLI as well, but only about 1 in 4 times or so. Since the issue seems to happen for certain timings you might have to play with the `delayFcpMs` query param. (I also used a locally hosted server with an FCP delay of 2000ms.)

1. Go to https://persistent-friendly-authority.glitch.me/?delayFcpMs=1700 to wake up the Glitch page
2. Run `node lighthouse-cli/index.js  --view --throttlingMethod provided  https://persistent-friendly-authority.glitch.me/\?delayFcpMs\=1700`

#### What is the current behavior?

Lighthouse reports no performance score and shows a NO_TTI_CPU_IDLE_PERIOD error.

![Screenshot 2020-03-25 at 10 11 42](https://user-images.githubusercontent.com/1303660/77525514-0f9ceb00-6e81-11ea-8832-23b9c292bf0a.png)

If a 400ms loop is added after setting the body HTML the error no longer occurs.

#### What is the expected behavior?

There shouldn't be an error.

#### Environment Information
* Affected Channels: All
* Lighthouse version: 5.7.1 (Canary DevTools), master 1457b4ce
* Chrome version: 83.0.4094.0 + others
* Node.js version: v10.15.3
* Operating System: macOS Catalina 10.15.3

**Comment by patrickhulce** [comment]
Ahhhh thanks very much @mattzeunert I think this might explain https://github.com/GoogleChrome/lighthouse/issues/10410 as well. We wait 5250 ms after load, CPU quiet, and network quiet, but if FCP was after all of those then we'll bump into this error.

You might already be aware but increasing `cpuQuietThresholdMs`/`pauseAfterLoadMs`/`networkQuietThresholdMs` in the defaultPass config should fix this in the meantime.
