### ISSUE TITLE
Audit on locally hosted page failed

### ISSUE THREAD

**Issue by quantuumsnot** [GoogleChrome/lighthouse#10502]
#### Provide the steps to reproduce
1. Run LH on 127.0.0.1:8000
(attaching a zip since GitHub breaks html code formatting)
[index.zip](https://github.com/GoogleChrome/lighthouse/files/4380063/index.zip)

#### What is the current behavior?
Lighthouse fails like this:
![lighthouse chrome bug](https://user-images.githubusercontent.com/12394810/77522301-b8047c80-6e8c-11ea-870b-3a7a77e144b9.png)

#### What is the expected behavior?
Obviously to work

#### Environment Information
* Chrome version: 80.0.3987.116 (Official Build) (64-bit)
* Operating System: Windows 8.1 x64

**Comment by patrickhulce** [comment]
Thanks for filing @quantuumsnot! What is the specific error message that is being shown in the screenshot (if you scroll the window it should give you a more specific error with a stack trace)?

I'm not able to reproduce this issue on your provided HTML :/

![image](https://user-images.githubusercontent.com/2301202/77548221-3c023880-6e7c-11ea-96af-b1aca1b498b3.png)

**Comment by quantuumsnot** [comment]
> What is the specific error message that is being shown in the screenshot (if you scroll the window it should give you a more specific error with a stack trace)?

In fact I cannot scroll that small window, seems it's stuck

**Comment by patrickhulce** [comment]
Hm, and a full restart of Chrome doesn't resolve the issue?

**Comment by quantuumsnot** [comment]
Ok, after full restart it works then after 30 or minutes it doesn't. Fully restarted again but with new user and no add-ons - it works, then again after 30 or more minutes it doesn't

**Comment by patrickhulce** [comment]
Very strange, we really would need the error that it's giving you to be able to help more :/ It's really not scrollable?

As a hack, you could undock devtools (Ctrl+P, "Undock into separate window"), open DevTools *on* Devtools (Ctrl+Alt+I), and either report the error from the console or find the DOM element of the modal that you can't scroll and get the error that way.

**Comment by quantuumsnot** [comment]
Thanks for undocking idea, I'll do it and write when this behavior occurs again
