### ISSUE TITLE
Continued 0 score in Lighthouse Report

### ISSUE THREAD

**Issue by nvanhuis** [GoogleChrome/lighthouse#10504]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
This URL receives a legitimate performance score of 0. Lighthouse *is* producing an accurate report already. A large number of render-blocking resources and high script execution times cause the page to perform very poorly on all performance metrics.

![image](https://user-images.githubusercontent.com/2301202/77549501-e9298080-6e7d-11ea-8e6a-fbb6b51ff33b.png)

If you're the owner of this page, try following the guidance in the rest of the performance section to improve the metrics (fwiw, in the new scoring system of 6.0.0-beta.0 this page receives a score of ~3, not 0).
