### ISSUE TITLE
Briane Greene's website (www.briangreene.org) needs debugging for forensic analysis

### ISSUE THREAD

**Issue by IbrahimBRammaha** [GoogleChrome/lighthouse#10512]
Instead of showing www.briangreene.org , it shows http://box2193.bluehost.com/suspended.page/disabled.cgi/www.briangreene.org

**Comment by patrickhulce** [comment]
I'm not quite sure why you submitted this here @IbrahimBRammaha, but this is for bugs or feature requests in the Lighthouse tool for assessing website performance and quality, not general web debugging help.

Sounds like you should tell Brian Greene his bluehost account is suspended...
