### ISSUE TITLE
Extension Error: Unexpected token , in JSON at position 45

### ISSUE THREAD

**Issue by gankwokwei** [GoogleChrome/lighthouse#1051]
**Lighthouse Version**: 1.2.1
**Chrome Version**: 57.0.2931.0
**Error Message**: Unexpected token , in JSON at position 45
**Stack Trace**:
 ```SyntaxError: Unexpected token , in JSON at position 45
    at JSON.parse (<anonymous>)
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:8113:31)```

**Comment by ebidel** [comment]
If you can reproduce this reliably, can you generate a report for us and paste it here? The URL you tested would also be really helpful.

**Comment by brendankenny** [comment]
this appears to be the same as #1028, which was fixed in Chrome. Now that Chrome 55 is stable, should be fixed everywhere.
