### ISSUE TITLE
PWA manifest icons: error messages for invalid mimetypes

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10518]
Originally filed: https://bugs.chromium.org/p/chromium/issues/detail?id=957732

If the `type` property is an invalid mimetype (such as `img/png` instead of `image/png`), the error is just: `Failures: Manifest does not have a PNG icon of at least 512px.`

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
