### ISSUE TITLE
Lighthouse commandline utility doesnt display results under categories

### ISSUE THREAD

**Issue by waniparag** [GoogleChrome/lighthouse#10514]
Run the following command
lighthouse "https:\\www.xxx.com" --only-categories=SEO --only-categories=Performance --only-categories=Accessibility --only-categories=Best Practices --output html --outputpath C:\sample\
Lighthouse commandline utility doesnt display details of categories
Report doesnt display  results under the categories 

![image](https://user-images.githubusercontent.com/53806666/77615266-f9775380-6f82-11ea-8849-4cda88dfc7ae.png)

**Comment by paulirish** [comment]
you were so close!

run `--help` and you'll see the valid arguments:

```
  --only-categories              Only run the specified categories. Available categories: accessibility, best-practices, performance, pwa, seo
```

basically instead of "Best Practices" you want "best-practices", etc..

so you want 

```
lighthouse "https:\\www.xxx.com" --only-categories=seo --only-categories=performance --only-categories=accessibility --only-categories=best-practices --output html --outputPath C:\sample\sample.html
```
