### ISSUE TITLE
Report is appearing different

### ISSUE THREAD

**Issue by kishorenrll** [GoogleChrome/lighthouse#10525]
Try to generate report in console > Audit section ,check result
Now for the same page try to generate report using this url https://developers.google.com/speed/pagespeed/insights/ and check result values

Different result values are appearing in both the views.
<img width="1419" alt="Screen Shot 2020-03-30 at 10 16 11 AM" src="https://user-images.githubusercontent.com/33752837/77876517-d09bda80-7270-11ea-9d1b-2b7edc83ffec.png">
<img width="1093" alt="Screen Shot 2020-03-30 at 10 16 23 AM" src="https://user-images.githubusercontent.com/33752837/77876522-d4c7f800-7270-11ea-88f8-36bdd0ef691c.png">

**Comment by patrickhulce** [comment]
That's odd I get nearly identical results and nothing that low. What URL were you trying?

![image](https://user-images.githubusercontent.com/2301202/77925696-cbd42800-726a-11ea-883f-885198bb8331.png)

![image](https://user-images.githubusercontent.com/2301202/77925830-f8883f80-726a-11ea-9996-56492c8d2034.png)

**Comment by kishorenrll** [comment]
i am trying for this url : https://www.vedantu.com/superkids
Every time i am getting different reports

**Comment by patrickhulce** [comment]
Have you already read through the [variability explainer](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) to help maximize reproducibility locally?

Locally I get very consistent results for that URL, but the TTI metric does differ from PSI enough to swing the score about ~20 points which is higher than expected. That's a case of #6708
