### ISSUE TITLE
charset audit needs web.dev doc

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10545]
audit: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/dobetterweb/charset.js

right now we just link to https://www.w3.org/International/questions/qa-html-encoding-declarations

cc @kaycebasques

**Comment by Beytoven** [comment]
Should be done as part of https://github.com/GoogleChrome/web.dev/issues/2402

**Comment by exterkamp** [comment]
Is this "waiting-on-upstream" in addition to being "P1"?

**Comment by paulirish** [comment]
fixed by #10689
