### ISSUE TITLE
Some reports not receiving a warning for Chrome extension use

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#10556]
#### Provide the steps to reproduce
1. Run LH on these assets
[report.zip](https://github.com/GoogleChrome/lighthouse/files/4447483/report.zip)

#### What is the current behavior?

A toplevel run warning is placed that there was extensive chrome extension behavior interfering

#### What is the expected behavior?

No such warning is there and 1000ms of the script execution is "Unattributable" instead of being blamed on the extension

#### Environment Information
* Affected Channels: *
* Lighthouse version: 6.0.0-beta.0

**Related issues**
taken from https://github.com/GoogleChrome/lighthouse/issues/10446#issuecomment-610673140

**Comment by patrickhulce** [comment]
Turns out this is a Chrome bug on inspecting the trace, the trace itself doesn't contain extension references, it's a mislabeling 😨

**Comment by connorjclark** [comment]
Did you happen to file a chromium bug or is this a known issue?

**Comment by patrickhulce** [comment]
> Did you happen to file a chromium bug or is this a known issue?

In the past DevTools policy for displaying traces collected with a mishmosh of trace categories like ours not via DevTools UI was just "best effort", so I didn't, but happy to file the crbug for the trace if new policy is different :)
