### ISSUE TITLE
Lighthouse report viewer in CI/CD Jenkins and docker container.

### ISSUE THREAD

**Issue by asifapasha** [GoogleChrome/lighthouse#10552]
It displays only the 1st report in the viewer even though ​multiple reports are present.
Whenever we try to run light house batch on two different web pages to audit via jenkins file and trigger the scripts
in a docker container to capture two diffrent reports for each. Example: Report 1(url 1) & Report 2(url 2)

We can see that two reports have been generated but when you open and read url name, both the Url names are the same.
That is it whichever Url is given in first place (eg: Url 1) generates two reports with same Url 1.

#### Provide the steps to reproduce
1. < Jenkins internal server>
2.  Run the jenkins file with the declarative pipeline syntax to run in a container and generate html report for two Urls.
3.  Provide two different Url parameters (Url 1 & Url 2) in the Jenkins.
4.  Build it to generate reports
5.  Open the report and analyse the Url names
#### What is the current behavior?

Repeats the same Url report at the end of the build while giving two different Urls in Jenkins.
Eg: (Url 1 & Url 1)
#### What is the expected behavior?

Should generate two different reports with two different Url names as per the given parameters in the Jenkins.
Eg: (Url 1 & Url 2)

#### Environment Information
* Affected Channels: 
* Lighthouse version:5.6.0
* Chrome version: 79.0.3945.79
* Node.js version:v12.13.1
* Operating System:Linux (docker container)
* Jenkins:2.214

**Comment by patrickhulce** [comment]
Thanks for filing @asifapasha but it's not clear how this is a Lighthouse bug. It sounds like the Jenkins job that calls Lighthouse is buggy and not using the two different URLs.

**Comment by exterkamp** [comment]
+1 to @patrickhulce this seems like a Jenkins problem.

**Comment by nishant-gupta** [comment]
hi @asifapasha 
you can use https://github.com/jenkinsci/lighthouse-report-plugin, there is open PR to allow multiple reports to be supported

**Comment by asifapasha** [comment]
Hi there,

Sure, will try it. Thank you :)
