### ISSUE TITLE
Chrome Audit no longer works with authenticated pages

### ISSUE THREAD

**Issue by JasonMongue** [GoogleChrome/lighthouse#10562]
The Clear Storage option was removed from Chrome/DevTools/Audits, thus it is not possible to run audits on authenticated pages. Starting an audit appears to clear storage, which has the effect (on many/most websites) of removing the user's authenticated state (if it's stored in a cookie)

**Comment by JasonMongue** [comment]
FOUND IT!! It got moved to the settings.

![image](https://user-images.githubusercontent.com/11543031/78825955-9bd90300-7995-11ea-88a5-a6877cd7a7f3.png)

**Comment by connorjclark** [comment]
Sorry - we changed our panel's UI to match the other panels a little better :)
