### ISSUE TITLE
Github workflow `yarn build-all` produces error but doesnt fail step

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10565]
![image](https://user-images.githubusercontent.com/4071474/78851049-aca56b00-79cd-11ea-9aab-bb0450d69f6f.png)
https://github.com/GoogleChrome/lighthouse/pull/10564/checks?check_run_id=572688284

doesn't happen in travis  or appveyor

**Comment by patrickhulce** [comment]
I'm suspecting the parallelization + `& wait`, for the smokehouse error itself it seems like we need to introduce *some* ordering of those build deps to prevent them from clobbering each other

**Comment by brendankenny** [comment]
@connorjclark Checking now, I'm not seeing this error in recent PRs. Was the bug that the build error was happening or that an error can happen and the build step doesn't fail (and we should fix it so it should)?

**Comment by paulirish** [comment]
Pretty sure we resolved this a while ago. Some linking/unlinking stuff. Brendan says it hasnt happened recently. We are probably good. ;)
