### ISSUE TITLE
Remove unused extendedInfo field from audits

### ISSUE THREAD

**Issue by Beytoven** [GoogleChrome/lighthouse#10567]
A handful of audits are still setting the extendedInfo in their return value. Since extendedInfo has been wholly replaced by 'details' and 'debugData', it's no point in keeping it since it doesn't even make it into the LHR json.

**Comment by paulirish** [comment]
the legacy JS audit can move from extendedInfo to the debugData & table pattern that we see in axe-audit. 

many of the rest i quickly saw are already captured in details.
if there's any that aren't, we'll need to figure out how to handle those.

and yah i saw some tests that'll need updates, too.
