### ISSUE TITLE
Workbox error logged to the console during report

### ISSUE THREAD

**Issue by cyrilf** [GoogleChrome/lighthouse#10577]
#### Provide the steps to reproduce
1. Run LH on https://animal-kill-counter.luseeds.com/
  

#### What is the current behavior?

Under the "Best Practices" category I get a score of 93 because there is a "Browser errors were logged to the console".

| URL | Description |
|-|-|
| https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-strategies.prod.js | no-response: no-response :: [{"url":"https://animal-kill-counter.luseeds.com/"}] at a.makeRequest (https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-strategies.prod.js:1:2145) |

![Screenshot from 2020-04-13 22-36-56](https://user-images.githubusercontent.com/1302282/79159327-27102980-7dd8-11ea-83c3-13e84a6c17ed.png)

#### What is the expected behavior?

This error shouldn't occur. 
It seems like it is not related to my website and comes only when a report is generated. :thinking: 

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.7.0
* Chrome version: 81.0.4044.92 (Official Build) (64-bit)
* Node.js version: v13.9.0
* Operating System: Linux / Ubuntu

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @cyrilf! This is exactly the behavior I see in the console if I try to load your page with an empty cache and then try to visit the page again offline (which is what Lighthouse does). Your site uses workbox in its service worker, so it is coming from code you've referenced even if you're not the maintainer of workbox or nuxt :)

My guess is there's been a misconfiguration somewhere along the line with the offline cache strategy.

**Comment by cyrilf** [comment]
Thanks for the quick answer @patrickhulce 
You're totally right, this seems to be a known issue with nuxt/workbox. For instance it's mentioned on this [github issue](https://github.com/nuxt-community/pwa-module/issues/176#issuecomment-570233391).

Thanks and I close as it's not related to lighthouse! :v:

**Comment by trevor-ofarrell** [comment]
@cyrilf did you ever find a way to solve this? I'm getting the same issues.

**Comment by cyrilf** [comment]
@trevor-ofarrell no I haven't checked in a while. But if you have a look at [the github issue](https://github.com/nuxt-community/pwa-module/issues/176#issuecomment-570233391) I've linked in my previous comment you might find some answers. :+1:
