### ISSUE TITLE
TTFB scoreDisplayMode is "binary" instead of "numeric"

### ISSUE THREAD

**Issue by mehulkar** [GoogleChrome/lighthouse#10573]
The `scoreDisplayMode` value for `time-to-first-byte` is "binary" in LH reports, but it has a numericValue. Should it be `numeric` instead?

#### Environment Information
* Lighthouse version: 5.6.0
* Chrome version: 
* Node.js version:
* Operating System:

**Comment by patrickhulce** [comment]
Nope :) `scoreDisplayMode` is about how to interpret the *score* and is (mostly) unrelated to whether a `numericValue` exists. In this case, the audit score is about whether the `numericValue` is above or below the failure threshold and has no shades of grey, so the `scoreDisplayMode` is `binary` and not `numeric`.

From the [docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/understanding-results.md#audits)...

> scoreDisplayMode - A string identifying how the score should be interpreted for display i.e. is the audit pass/fail (score of 1 or 0), should it be ignored, or are there shades of gray (scores between 0-1 inclusive). If set as informative, notApplicable, manual, or error, then score will be null and should be ignored.

**Comment by mehulkar** [comment]
Aha! Thanks for the link to the docs, I couldn't find those before. Closing this out.
