### ISSUE TITLE
Performance score of 0

### ISSUE THREAD

**Issue by assman** [GoogleChrome/lighthouse#10576]
Current Behavior:

Lighthouse is reporting a performance score of 0 when I test an Ionic PWA running on localhost.

Expected Behavior:

Expecting a non zero score because the page does load relatively fast.

Chrome version: Version 81.0.4044.92
Lighthouse version: 5.6.0

**Comment by patrickhulce** [comment]
tl;dr - the app probably receives a score of 0.

See https://github.com/GoogleChrome/lighthouse/issues/10504 and https://github.com/GoogleChrome/lighthouse/issues/10539 as examples.

> Expecting a non zero score because the page does load relatively fast.

On what throttling settings and what metric values does Lighthouse report? Lighthouse simulates fast 4G network and mobile hardware which will be very different than how it performs on a developer machine.

**Comment by assman** [comment]
<img width="980" alt="Screen Shot 2020-04-13 at 11 33 19 PM" src="https://user-images.githubusercontent.com/14093665/79133787-2fb82e00-7ddf-11ea-9152-875a6d40c9f6.png">
These are the settings

**Comment by patrickhulce** [comment]
So yes that's a throttled load. The metrics we're reporting are going to be much worse than what you see as it loads on your machine. Are all the metric values in the performance section red numbers? If so, this is working as intended.

**Comment by assman** [comment]
Yes the metrics like FCP are showing values in red. May I know how to change the throttling settings?

**Comment by patrickhulce** [comment]
Sure, but you won't be able to do it in DevTools. Refer to the [throttling docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md) and the [CLI configuration docs](https://github.com/GoogleChrome/lighthouse/#cli-options).
