### ISSUE TITLE
Screenshots don't match with first meaningful paint 

### ISSUE THREAD

**Issue by jantimon** [GoogleChrome/lighthouse#10580]
#### Provide the steps to reproduce

Vist https://jantimon.github.io/css-framework-performance/ or

```js
git clone https://github.com/jantimon/css-framework-performance
cd css-framework-performance
npm i
npm run reports
```

Internally it executes the following command:

```bash
  lighthouse
    http://127.0.0.1/
    --throttling.cpuSlowdownMultiplier=4
    --chrome-flags="--headless"
```

#### What is the current behavior?

For the default throttling settings the screenshot and the `first meaningful paint` don't match at all: 

<img width="650" alt="screenshots" src="https://user-images.githubusercontent.com/4113649/79199092-bc410b80-7e34-11ea-950b-6861885fbae7.png">

The screenshots are all the same inside "screenshot-thumbnails".

https://github.com/jantimon/css-framework-performance/blob/49e86ee318bb90070f3d80aa711836efa2f92f51/reports/4g/vanilla/index-0.report.json#L110

Full report as html:

https://github.com/jantimon/css-framework-performance/blob/49e86ee318bb90070f3d80aa711836efa2f92f51/reports/4g/vanilla/index-0.report.html

#### What is the expected behavior?

`first meaningful paint` should match screenshots like in this example (the first meaning full paint is 1.3s and the screenshot thubmnails show it around the same time): 

<img width="626" alt="screenshots" src="https://user-images.githubusercontent.com/4113649/79235747-4e183b00-7e6c-11ea-81c7-316ca968ee8f.png">

To generate the second image I added `--throttling-method=devtools`

#### Environment Information
* Affected Channels:  "@lhci/cli": "0.3.12",
* Lighthouse version: 5.5.0
* Chrome version: HeadlessChrome/80.0.3987.149
* Operating System: ubuntu-18.04

**Comment by patrickhulce** [comment]
Thanks for filing @jantimon! 

The screenshot timestamps will only match the metric values timestamps in the performance section if an observed throttling method is used (`--throttling-method=devtools` or `--throttling-method=provided`). When the metrics are simulated the metric value is going to be shown based on what it was like when we logically replayed the load under different network and CPU conditions. Learn more about [the throttling options in Lighthouse](https://github.com/GoogleChrome/lighthouse/blob/ac186d0ecbdce739961b7be086dc8f3dbf86f4fa/docs/throttling.md).

**Comment by jantimon** [comment]
After reading https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md I thought throtteling is always active:

> The mobile network throttling preset
> This is the standard recommendation for mobile throttling:
> 
> Latency: 150ms
> Throughput: 1.6Mbps down / 750 Kbps up.
> Packet loss: none.
> 
> **These exact figures are used as Lighthouse's throttling default**

> Simulated throttling remains the default setting. This matches the setup of PageSpeed Insights and the Lighthouse CLI default, so this provides cross-tool consistency.

But I guess I was wrong and it is not the default for the CLI but only for the UI - is that correct?

**Comment by patrickhulce** [comment]
> But I guess I was wrong and it is not the default for the CLI but only for the UI - is that correct?

No, throttling *is* always active by default you were right the first time, but the point is that the default throttling is *simulated* and not *applied*. It doesn't substantially change the metric values reported *but* it does change whether the *trace* will look like it was throttled or not. Simulated throttling does not actually apply throttling but happens later in Lighthouse when we "replay" the load logically under different conditions.

From that same document just a smidge further down...

> Simulated throttling, which Lighthouse uses by default, uses a simulation of a page load, based on **the data observed in the initial unthrottled load**.

**Comment by jantimon** [comment]
Okay I see.

So to get the default throtteling from [docs/throttling.md](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md) I would have to use the following values:

```
 lighthouse
    http://127.0.0.1/
    --throttling.cpuSlowdownMultiplier=4
    --chrome-flags="--headless"

    --throttling-method=devtools
    --throttling.requestLatencyMs=150
    --throttling.downloadThroughputKbps=1600
    --throttling.uploadThroughputKbps=750
```

Or is there an easier way to use the default preset?

**Comment by patrickhulce** [comment]
> So to get the default throtteling from docs/throttling.md I would have to use the following values

I think there's still a misunderstanding. You don't need to do anything to get the default throttling listed in docs/throttling.md. That's why it's the default.

**If you want the trace to match the reported metric values _and_ use default throttling preset**, then you need to use `--throttling-method=devtools`

**Comment by jantimon** [comment]
Thank you so much for taking so much time for this.  
I will close this issue :)
