### ISSUE TITLE
Javascript and CSS is blocked when reports are run, leaving flat html document

### ISSUE THREAD

**Issue by jgcrunden** [GoogleChrome/lighthouse#10589]
#### Provide the steps to reproduce
1. Run LH on https://pianissami.co.uk
  

#### What is the current behavior?
While the report is being generated, the website renders in the browser as expected. However, once the report generation completes, the CSS and JS are dropped from the website in the browser, leaving a flat html document. An icon in the search bar appears saying "Javascript Blocked: Javascript was blocked on this page". Checking "Always allow" and clicking "Done" has no effect. This does not happen when the page is loaded normally in the browser.
There is no explanation as to why this block is applied.

#### What is the expected behavior?
Running the report on other websites: the block is not applied and the page renders correctly once the report is generated.
Not sure what is happening specifically with my website that is causing this to happen. Any help would be greatly appreciated.

#### Environment Information
* Affected Channels: Audit
* Lighthouse version: The one that comes packaged with Chrome
* Chrome version: 81.0.4044.92
* Node.js version: N/A?
* Operating System: Windows (also reproducible on MacOS (same build))

**Related issues**

**Comment by jgcrunden** [comment]
I've just come across this, which I think answers my question:
https://developers.google.com/web/tools/lighthouse/audits/no-js
I have written my site so that it is blank when loaded then javascript is used to show specific parts of the same html document when you navigate through it (the give the illusion of multiple html pages, when in fact there is only one, to speed navigation).

**Comment by patrickhulce** [comment]
Thanks for filing @jgcrunden! We've heard reports of this but haven't gotten a reproducible URL. 

You're correct that that audit loads the page without JavaScript but the original page is supposed to load after Lighthouse is done, so this is a bug.

**Comment by jgcrunden** [comment]
Glad I've helped to provide a reproducible URL :)

Thanks for your explanation regarding page loading without JavaScript. For reference, I've changed my code around a bit, so if the page is loaded without the index.js file, it will now display content (rather than a blank page, as I mentioned it my comment above).

I've run the Lighthouse Report again. Whatever change I made must have improved the loading significantly as I now have a much better performance score (result!).

However, the bug of blocked JavaScript from browser still exists when the report is run.
If you need any other information from me in fixing this bug, don't hesitate to ask!

Many thanks
Josh

**Comment by jgcrunden** [comment]
Also, I came across Lighthouse through the Google Search Console.
https://search.google.com/search-console
Interesting, one thing that prompted me to start running the reports was the result I got from the "Mobile Usability" report from the Google Search Console. It flagged 2 issues:
"Text too small to read"
"Clickable elements too close together"
I thought that was odd because I've tested my site on my mobile and the text size and proximity of the links seems okay to me (I appreciate there is an element of subjectivity here)

I don't know what connection there is between Lighthouse and Google Search Console, but I wonder whether the Mobile Usability errors I'm getting might related to the bug where JavaScript and CSS is being blocked when reports are run. When it leaves just the plain html document, the text is show at its default (small) size and the links as close together as there is no css padding.
Is it possible these are related?

**Comment by patrickhulce** [comment]
> might related to the bug where JavaScript and CSS is being blocked when reports are run. When it leaves just the plain html document, the text is show at its default (small) size and the links as close together as there is no css padding.
Is it possible these are related?

No these are unrelated. Lighthouse loads the page several times. It is intentional that one of these loads blocks JS and CSS (the audit you found the documentation for). The only bug here is that we don't properly cleanup after that final load when we're done. The results of the text too small and elements too close are computed on a regular load of the page before that happens.

**Comment by jgcrunden** [comment]
Okay. I'll have a look at my mobile formatting again to see if I can make it more mobile friendly.
Unless it is something with my own content, I wonder if it could be picking up on the reCAPTCHA v2 element. I notice there are "Privacy" and "Terms" links in the element, which when viewed on a mobile are very small and close together...

**Comment by patrickhulce** [comment]
P2 because this seems annoying and definitely unexpected, but doesn't seem to affect everyone and has a simple workaround.

**Comment by jgcrunden** [comment]
I've tried generating a report recently and it appears this bug has been fixed. The page renders as expected. I'm happy for this to be closed if you are happy it is fixed.

**Comment by patrickhulce** [comment]
Glad to hear it, thanks for following up @jgcrunden! 🎉
