### ISSUE TITLE
New artifact: Collect issues from CDP

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10592]
`Audits.issueAdded` has been added to support the Issues Panel.

We should have a singular artifact that collects all the issues reported by DevTools:

```
Issues: {
	SameSiteCookieIssue?: SameSiteCookieIssueDetails[],
	MixedContentIssue?: MixedContentIssueDetails[],
} // issue code => array of detail objects
```

Each event only has one issue of each type. Should aggregate to an array so that audits can easily iterate the issues it cares about.

See: https://chromedevtools.github.io/devtools-protocol/tot/Audits/#event-issueAdded

Will need to update the devtools protocol dependency so we get the new types for the Issue event.

**Comment by patrickhulce** [comment]
Do we have a plan to do anything user-visible with any of these issues? Just curious why it would be a P1 otherwise  :)

**Comment by connorjclark** [comment]
Yes, we will be using this for T&P audits.

**Comment by brendankenny** [comment]
> `Audits.issueAdded` has been added to support the Issues Panel.

why was this not named the `Issues` domain :/
