### ISSUE TITLE
launch-chrome.sh should support chromium on linux

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#106]
(orig reported at #73 )

We can probably just use some basic bash hackery of `if hash chromium 2>/dev/null` etc etc.

**Comment by deepanjanroy** [comment]
Linux doesn't have chrome canary. Can we just use the regular google chrome instead? I tested and it works fine even if chrome is already running.

**Comment by paulirish** [comment]
Hmm.. We're going to need latest builds, so lets prefer chromium.

**Comment by paulirish** [comment]
fixed by #119 and #124
