### ISSUE TITLE
DBW: audit to check for notification prompt on page load

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1060]
Similar to https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/dobetterweb/geolocation-on-start.js, we should have an audit that checks
if a site is prompting for notifications without any user input.

audit anme: notification-on-start.js
site example that demonstrates this behavior: https://tiki.vn/

**Comment by patrickhulce** [comment]
I can take this

**Comment by patrickhulce** [comment]
Fun fact btw: tiki.vn actually doesn't request permission for notifications when run in lighthouse because we emulate mobile. This might not be super useful if most other sites behave similarly

**Comment by brendankenny** [comment]
fixed in #1064
