### ISSUE TITLE
cache control for webp

### ISSUE THREAD

**Issue by Nil-av** [GoogleChrome/lighthouse#10602]
Hi,

I use image with webp format and when I run the Lighthouse Chrome plugin, I get the warning "Serve static assets with an efficient cache policy" for webp.

But, if I check my headers (PHP), I have a good cache control (cache-control: max-age=31536000) and  after refresh, web images are well and truly in memory cache like jpg image, etc. So, I think the problem is in Lighthouse.

**Comment by patrickhulce** [comment]
Thanks for filing @Nil-av!

If you're trying to file a bug can you please fill out the [bug issue template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md), namely the reproduction steps/URL?

**Comment by Nil-av** [comment]
Hi, sorry, I'm not a big github user and not a very technical profile. (worst, I'm french ^^)

My website is in development stage, but I can send you the URL in private message if it's possible in Github.

#### Provide the steps to reproduce

1. I use the last version of [Lighthouse addon for Chrome](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=fr)
2. On my page, I have several webp image in source tag like that (in a picture node), the img tag is used by a jpg or png version for compatibility reasons : 
`<source type="image/webp" srcset="/wp-content/uploads/sekiro-shadows-die-twice-pc/screenshot-20181011-02-medium-jpg.webp" media="(max-width: 480px)">`
3. I generate a Lighthouse report with all categories and desktop device
4. The report said with all occurences.

> Serve static assets with an efficient cache policy 14 resources found
> A long cache lifetime can speed up repeat visits to your page. Learn more.

URL | Cache TTL | Size
-- | -- | --
…sekiro-shadows-die-twice-pc/screenshot-20181011-02-jpg.webp([mywebsitedomain]) | None | 212 KB

5. But my cache control is good, response headers:
> cache-control: max-age=31536000
> content-length: 216648
> content-type: image/webp

6. I refresh, my webp images are in memory cache of Google Chrome. So, I suppose it's a false positive from Lightouse.


  


#### What is the current behavior?
I have a warning about cache control

#### What is the expected behavior?
All clear.

#### Environment Information
* Affected Channels: Extension
* Lighthouse version: 100.0.0.0
* Chrome version: 80.0.3987.163 
* Node.js version: ?
* Operating System: Windows 10

**Comment by Nil-av** [comment]
I close the issue, I find corrupted files in my Wordpress install, I reinstalled the last Wordpress update and my false positive is over.
