### ISSUE TITLE
Lighthouse audit fails for https://web.dev/ 

### ISSUE THREAD

**Issue by mum-never-proud** [GoogleChrome/lighthouse#10604]
Initially i ran lighthouse for my Website but it ran into an error, tried with a fresh profile without any tabs still the same problem.

#### Provide the steps to reproduce
1. Run LH on https://web.dev/, only for performance and device as desktop
  

#### What is the current behavior?
Ah, sorry! We ran into an error.

#### What is the expected behavior?
Should provide the report

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version:
* Chrome version: 84.0.4115.5 (Official Build) dev (64-bit)
* Node.js version:
* Operating System: MAC OS Catalina

**Comment by patrickhulce** [comment]
Thanks for filing @mum-never-proud! 

But I'm not able to reproduce this behavior with those versions and to be actionable we really need reproducible steps or at least the error message that you're getting. Can you tell us more?

**Comment by mum-never-proud** [comment]
Sure, [i have uploaded the recording to my G drive](https://drive.google.com/open?id=1WoLQ3Y9GfEf_CdTDN_od2FrkMzcLJyp2)

hmm is it possible that chrome is lacking necessary permissions?

cc @patrickhulce

**Comment by patrickhulce** [comment]
Ah, that error means that internal Chrome tracing errors occurred. It's unknown to us when and why it occurs and is almost always intermittent. The only known workaround is basically what the advice says, to completely quit Chrome and try again :/

**Comment by mum-never-proud** [comment]
cool, i did restarted my chrome, but i am still getting the same error, i haven't restarted the machine (got lot of other things open), would restarting the machine solve the problem?

also this is a clean chrome install and i do have edge browser as well, lighthouse works on edge and not on chrome.

i don't think there's gonna be any conflict between chromium base Edge and Chrome

**Comment by patrickhulce** [comment]
> i don't think there's gonna be any conflict between chromium based Edge and Chrome

There shouldn't be any conflict between Edge and Chrome but if there are multiple Chrome profiles open all will need to be quit for Chrome to fully shutdown.

As a verification that this is the problem, are you able to successfully use the "Performance" tab in DevTools by recording a trace of a page load?

**Comment by mum-never-proud** [comment]
a blind guess that this might be the issue

![image](https://user-images.githubusercontent.com/58324637/79709696-85f60700-82e0-11ea-9170-27b1a5ed8ebb.png)

I am not sure if it makes sense

**Comment by patrickhulce** [comment]
Wait @mum-never-proud the bug was originally filed for `https://web.dev/` does this happen only on your site? When are you shown this "Access to the file was denied"? We will definitely be unable to audit whatever shows you that message :)

**Comment by mum-never-proud** [comment]
no, it happens on `https://web.dev/` as you can see it in the video previously attached, today I just tried opening the local file on chrome and I got this, I was just wondering if lighthouse saves the attributes to a local file and while trying to access it the error is thrown?


hope I am clear

**Comment by patrickhulce** [comment]
Thanks @mum-never-proud we're going to dedupe this into #1091  which is the root error going on.
