### ISSUE TITLE
Inconsistent handling of non-ending trace events

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#10616]
It's very common (increasingly common, even?) to have a trace where some Begin (phase `B`) events do not have their partnered End (phase `E`) events. We'll call these "non-ending trace events".

Here's one such trace: [Profile-20200420T122902.json.zip](https://github.com/GoogleChrome/lighthouse/files/4506792/Profile-20200420T122902.json.zip). Captured in Chrome DevTools UI. The "Rasterize Paint" aka `RasterTask` events are [complete events](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit#heading=h.puwqg050lyuy) (phase `X`), normally, except for when they don't end. Then, they are just `B` events.

Here's a more complex trace with plenty of the same behavior. [trace_Mon_Apr_20_2020_3.09.45_PM.json.zip](https://github.com/GoogleChrome/lighthouse/files/4506793/trace_Mon_Apr_20_2020_3.09.45_PM.json.zip) It was captured using the new perfetto pipeline. 

That same trace rendered in both traceviewer and devtools: 
![image](https://user-images.githubusercontent.com/39191/79809042-5ff25600-8324-11ea-9b32-4a4448281dc2.png)
The new perfetto viewer also doesn't elongate the pending events: 
![image](https://user-images.githubusercontent.com/39191/79809103-96c86c00-8324-11ea-863d-0e6cf2e0b0cf.png)
In fact, you can zoom in and see the green parent (which is non-ending) is visually shown as an instant event, even when it has a child that starts after and has a real duration: 
![image](https://user-images.githubusercontent.com/39191/79809279-d4c59000-8324-11ea-884f-4fc945c367c0.png)

----------

Here's the current state of how our tools handle this situation:

- **Perfetto parsing**: knows the "slice" isn't ended, but not much special handling. Doesn't set an end time, but [they're thinking about it](https://github.com/google/perfetto/blob/dfa48135f294574c49213e528bf8582f4c041967/src/trace_processor/importers/common/slice_tracker.cc#L259-L263).
- **Perfetto UI**: renders non-ended events like an instant event (with a 0 duration)
- **traceviewer parsing**: sets the `duration` to be [the maxTrackTimestamp](https://chromium.googlesource.com/catapult/+/refs/heads/master/tracing/tracing/model/slice_group.html#236), and keeps a `didNotFinish` flag on it. maxTrackTimestamp is the last known `end` time for that track (where "track" ~= thread)
- **traceviewer UI**: [adds "(Did not finish)" in the flamechart UI](https://user-images.githubusercontent.com/39191/79809890-81ecd800-8326-11ea-8b17-f9a11497bc9c.png), but not in the details. 
- **devtools parsing**: sets all non-ended events to [end at the end of the trace](https://source.chromium.org/chromium/_/chromium/devtools/devtools-frontend/+/97713d6f163e086aad0560246b1e68e3b673115f:front_end/sdk/TracingModel.js;l=982-984;drc=9edf7517be6ec8de61bba37ed8d85746adffe7e1;bpv=1;bpt=0). 
- **devtools UI**: makes it look like REALLY long events, but yeah they're almost certainly not.
- **lighthouse/tracehouse parsing**: we consider it `unbounded` and [end the event at trace end](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/tracehouse/main-thread-tasks.js#L188-L191). _Update: i was wrong, see patrick's comment_

-----------

I'd like to suggest a few actions:

1. Trace capturing is broken somehow. Honestly feels like the last trace event (per thread) isn't being captured. (off by one error?) Report this to the relevant chrome/perfetto folks
1. Lighthouse should adopt the same end/duration handling as traceviewer
1. DevTools should also the same thing  (though due to [crbug.com/1030639](https://bugs.chromium.org/p/chromium/issues/detail?id=1030639), perhaps devtools will defer completely to perfetto's parsing)
1. Perfetto/Traceviewer folks should pick which of their 2 ways they want to handle this.

ref https://github.com/GoogleChrome/lighthouse-ci/issues/276#issuecomment-616629822
ref https://github.com/GoogleChrome/lighthouse/pull/9491

**Comment by patrickhulce** [comment]
> lighthouse/tracehouse parsing: we consider it unbounded and end the event at trace end.

Only kind of, sorry if I confused things with jokes :) Since https://github.com/GoogleChrome/lighthouse/pull/9785 we will always truncate the event at the end of the parent task and be very forgiving.

https://github.com/GoogleChrome/lighthouse/blob/9a6afb37a9814be5003bee8788437a4145ec82c0/lighthouse-core/lib/tracehouse/main-thread-tasks.js#L268-L271

Because we only look at events inside toplevel tasks (which are "complete" `X` events that don't have this problem), trace end is effectively never used as the end of a task in practice *in the context of lighthouse* (but other folks using tracehouse for arbitrary traces might need to care).

> Lighthouse should adopt the same end/duration handling as traceviewer
> traceviewer parsing: sets the duration to be the maxTrackTimestamp, and keeps a didNotFinish flag on it. maxTrackTimestamp is the last known end time for that track (where "track" ~= thread)

This sounds *less* forgiving than where we stand right now. `unbounded` is effectively our `didNotFinish` flag. Seems like we might not need to take any action?

**Comment by paulirish** [comment]
> 1. Trace capturing is broken somehow. Honestly feels like the last trace event (per thread) isn't being captured. (off by one error?) Report this to the relevant chrome/perfetto folks

I'm working on a repro/bisect here. The most reproducible case I have is that on a CompositorTileWorker, the last ["RasterTask"](https://source.chromium.org/chromium/chromium/src/+/master:cc/tiles/frame_viewer_instrumentation.cc;l=41-52;bpv=1;bpt=1?q=%20trace_event.*rastertask&ss=chromium) is often missing its END. Debugging right now, but it might be correlated to if the `toplevel` category is on or not.

**Comment by paulirish** [comment]
> This sounds _less_ forgiving than where we stand right now. `unbounded` is effectively our `didNotFinish` flag. Seems like we might not need to take any action?

Oh fantastic. Okay so,

1. Lighthouse is fine right now. No action needed
2. DevTools must change their handling of these
3. Ideally, tracing folks fix the core issue of lost events in thread pool threads

**Comment by paulirish** [comment]
> DevTools must change their handling of these. @paulirish to file a bug.


captured the full story for devtools in https://bugs.chromium.org/p/chromium/issues/detail?id=982252#c11

**Comment by paulirish** [comment]
It seems like this may finally be fixed in Chromium. https://bugs.chromium.org/p/chromium/issues/detail?id=1021571#c25
