### ISSUE TITLE
AUDITS EXPAND PRINT HamburgerMenu NOT COLLAPSING

### ISSUE THREAD

**Issue by gatsbify** [GoogleChrome/lighthouse#10612]
Greetings

Pls assist me with this,

I am trying to print pdf the lighthouse audit report but the Hamburger menu does not collapse prior to the print popup being shown, hence the menu is now also visible on the pdf report.

See attachment
![Screen Shot 2020-04-20 at 13 44 37](https://user-images.githubusercontent.com/60381194/79748297-7e008c00-830d-11ea-93d0-2d5945a874e2.png)

Regards

Flo

#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks very much for filing @gatsbify! This has been fixed in 6.0.0-beta.0 if you'd like to install it from the command line `npm install -g lighthouse@next`. Otherwise it will appear in other channels when 6.0.0 becomes final.

**Comment by gatsbify** [comment]
Thank You!
