### ISSUE TITLE
Low score colors misleading

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/lighthouse#1061]
![screen shot 2016-11-28 at 10 17 39 am](https://cloud.githubusercontent.com/assets/1066253/20680545/5145ba6c-b554-11e6-9a29-4b313a1c6a7a.png)

It seems like the scores of 22, 21, and 48 should be red/orange to indicate they're negative values.

**Comment by brendankenny** [comment]
fixed in #1070
