### ISSUE TITLE
Getting Performance Score as 0

### ISSUE THREAD

**Issue by anishjohnrc** [GoogleChrome/lighthouse#10618]
Hi,

When I am running the audit for www.mediknit.org, I am getting a performance score of 0. Whatever I do, it is not changing. Is it a bug?

**Comment by connorjclark** [comment]
Not a bug in Lighthouse. All of the top opportunities in the report are legitimate.

![image](https://user-images.githubusercontent.com/4071474/79829425-e5dbc480-8357-11ea-82c4-847dabdb7e9c.png)

For example, the largest JS file is ~3MB, and isn't even compressed. You should be using gzip or brotli on your resources.

![image](https://user-images.githubusercontent.com/4071474/79829508-1ae81700-8358-11ea-8b62-e30416e4c595.png)
