### ISSUE TITLE
Found icons color looks like an error

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/lighthouse#1062]
![screen shot 2016-11-28 at 10 19 03 am](https://cloud.githubusercontent.com/assets/1066253/20680562/6a8ae704-b554-11e6-960d-fb058c3069a0.png)

The "Found icons of sizes..." text looks like an error (I wondered if maybe i shouldn't have a 512 icon) but I think it's just informational? Compare to the actual error in the next column. Suggest making informational stuff black

**Comment by wardpeet** [comment]
@ebidel any guidelines on this issue? (I suppose this can be a good first bug as well?)

**Comment by brendankenny** [comment]
that was fixed in #1044

<img width="557" alt="screen shot 2016-11-28 at 11 25 39" src="https://cloud.githubusercontent.com/assets/316891/20682576/69b9302a-b55d-11e6-8748-ee3a45e343f0.png">
