### ISSUE TITLE
Why I have diferent scores on different devices?

### ISSUE THREAD

**Issue by sorax93** [GoogleChrome/lighthouse#10628]
I check the domain: https://kharkovclimat.com.ua/, on two laptops and a phone, and get different ratings.

on one of the laptops scores: for mobile - 71, for computer - 74

on another laptop and phone: for mobile - 95, for computer - 97

how to understand which grade is correct? and why is this happening?

**Comment by patrickhulce** [comment]
Thanks for filing!  

In short, [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md). That URL loads *very* slowly from North America, so if the devices were in even slightly different geographic locations I would expect that to immediately explain it, but all of the factors in that doc are in play as well.

You can also check the `CPU/Memory Power` at the bottom of the report to see if the device it was being run on was underpowered and doesn't meet the [minimum recommended hardware](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md#run-on-adequate-hardware).
