### ISSUE TITLE
100% CPU on https://tiki.vn/ causes CLI to hang

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1063]
Running 1.2.1 against https://tiki.vn/ in Canary  57.0.2935.0 causes the CLI to hang on the Accessibility/ContentWidth audit. Looking at the task manager in Chrome, the CPU for that tab is up to 100%

This is what I ran:

`npm run fast -- --output=html --output-path=results.html https://tiki.vn/`

One time I got this error, but it seems sporadic:

<img width="1010" alt="screen shot 2016-11-28 at 10 33 22 am" src="https://cloud.githubusercontent.com/assets/238208/20680939/2cddf660-b556-11e6-9ced-853062d02e45.png">

**Comment by ebidel** [comment]
Running the Extension in Chrome 54 stable does seem to work, although it's very slowwwwwwww.

**Comment by patrickhulce** [comment]
Seems to apply to the desktop version of their site since re-enabling device emulation fixes the issue for me

**Comment by ebidel** [comment]
Confirming that things look better using:

    npm run start -- --output=html --output-path=results.html https://tiki.vn/
