### ISSUE TITLE
Unable to modify window size in node module after puppeteer handoff

### ISSUE THREAD

**Issue by klewiscse** [GoogleChrome/lighthouse#10638]
#### Provide the steps to reproduce
1. Run Puppeteer to navigate to local domain web application
2. Login to web app with puppeteer and handoff to Lighthouse
3. Programmatically iterate audits on all of the web application's primary pages
4. Observe that each audit is being ran in another tab with the default 800x600 window size despite the browser running maximized.
  

#### What is the current behavior?
Every audit gets ran with 800x600 window size. I assume this is because the node module ignores any chromeFlags passed to it (as stated in the docs), and doesn't inherit the chromeFlags from chromium launched by Puppeteer. 

#### What is the expected behavior?
The node module version of lighthouse should fit to size of the browser that it's in if we're not going to be able to modify any options. However I'm curious about the decision to not allow those to be set in the node module, but set in the CLI..

Although I could be missing something, as I am new to lighthouse.

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 5.6.0
* Chromium version: Whatever is downloaded with lighthouse 5.6.0
* Node.js version: 10.20.1
* Operating System: Windows 10

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @klewiscse! A think there's a misunderstanding with puppeteer here, did my best to explain what's going on below.

> doesn't inherit the chromeFlags from chromium launched by Puppeteer.

Chrome flags are only about *launching the browser* and not about creating individual tabs, any chrome flags you used to launch chrome with puppeteer will still be in effect when lighthouse runs.

> Every audit gets ran with 800x600 window size. 

This is expected puppeteer behavior. If you don't want new tabs to be created at 800x600, change the [defaultViewport in puppeteer](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions). You can also use the lighthouse option `emulatedFormFactor` to have lighthouse manage the viewport for you instead.

> lighthouse should fit to size of the browser that it's in if we're not going to be able to modify any options

It does when `emulatedFormFactor=none`, you're just happening to use a library that overrides this behavior :)

> However I'm curious about the decision to not allow those to be set in the node module, but set in the CLI.

The node module doesn't launch Chrome, so setting `chromeFlags` at that point is not possible. The `chromeFlags` are going to be whatever you used to launch chrome yourself.

> Chromium version: Whatever is downloaded with lighthouse 5.6.0

Lighthouse doesn't download any version of Chromium so this will be whatever puppeteer downloaded if you used puppeteer to launch Chromium. Note that older versions of puppeteer can use older chromium versions that aren't compatible with latest lighthouse, so just something to keep in mind as time goes on.

**Comment by klewiscse** [comment]
Whoops! I meant puppeteer not lighthouse in regards to downloading Chromium.. sorry it was like 4:30am when I wrote this.

Thanks for the explanations though I feel like that helps my understanding a bit. I already had the default viewport set, and that didn't work but changing emulatedFormFactor = none worked! However this doesn't seem to work for headless.. is that expected?

**Comment by klewiscse** [comment]
Update: Setting the default viewport + the emulatedFormFactor = none wasn't working in conjunction with the chromeFlag "--set-maximized". Explicitly setting the window size with chromeFlag "--window-size=1920,1080" works in headless mode. Thanks @patrickhulce !
