### ISSUE TITLE
Screen resolution impact on speedIndex

### ISSUE THREAD

**Issue by octoxalis** [GoogleChrome/lighthouse#10642]
**Summary**

Why is there such a big difference between testing a site on my 4K display
+ @ 3840x2160 - speddIndex: ~1700
+ @ 1280 x 1024- speddIndex: ~950

**Comment by patrickhulce** [comment]
Impossible to say without more information (URL, LH version, LH settings, chrome version, OS, machine specs, etc)

The most probable answer to me is that whatever device you're running on actually takes that much longer to push 4x the pixels. Rendering 4K ain't free :)

**Comment by octoxalis** [comment]
That's what I imagine too. However, the frame capture is not done in 4K, but only on a tiny portion of it and wouldn't it be independent of the display resolution?

**Comment by paulirish** [comment]
@octoxalis do you want to share the traces?  
alternatively you can run https://github.com/paulirish/speedline yourself which may help to diagnose what's going on.

**Comment by patrickhulce** [comment]
Considering this WAI for now.

If you're able to share traces where `speedline` does not match what `lighthouse` says, we'd love to hear from you again 👍
