### ISSUE TITLE
PageSpeed Insights and Lighthouse Devtools disagree on whether an image is lazyloaded, Lighthouse is correct

### ISSUE THREAD

**Issue by mikesherov** [GoogleChrome/lighthouse#10647]
#### Provide the steps to reproduce
1. Run LH on https://www.skillshare.com with Nexus 5X emulation
2. Run PageSpeedInsights on https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.skillshare.com%2F&tab=mobile
3. Look at the Defer offscreen images section

#### What is the current behavior?

LH doesn't list tablet-mockup.png as an image to defer. 
PSI's mobile tab does list tablet-mockup.png as an image to defer.
LH is correct because when I view the network tab with Nexus 5X emulation, I don't see the image being loaded.

#### What is the expected behavior?

LH doesn't list tablet-mockup.png as an image to defer. 
PSI's mobile tab doesn't list tablet-mockup.png as an image to defer.

#### Environment Information
* Affected Channels: Devtools, PSI
* Lighthouse version: Generated by Lighthouse 5.7.0

```
Google Chrome | 80.0.3987.149 (Official Build) (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
JavaScript | V8 8.0.426.27
Flash | 32.0.0.363 
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome -psn_0_524416 --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox
```

**Comment by paulirish** [comment]
Yup. PSI is still running LH 5.6.0, and 5.7.0 fixed loading=lazy handling (#10117 )

so a new deploy of PSI will sort things out.

**Comment by mikesherov** [comment]
@paulirish thanks for the info. If I understand the referenced pull request, this will prevent Lighthouse from reporting it as an image to defer the loading of, but will it affect my TTI or other simulated TTI scores. I guess I'm more concerned about whether whatever underlying version of Chrome is loading up the image or not, during the test.

**Comment by exterkamp** [comment]
Lighthouse 6.0.0 is deployed to PSI. Is this still happening?

I don't see ` tablet-mockup.png` in the images to defer anymore, is that the desired state?

**Comment by mikesherov** [comment]
Hi @exterkamp yes, it's the desired state, thanks! Although I do still have one question: 

> If I understand the referenced pull request, this will prevent Lighthouse from reporting it as an image to defer the loading of, but will it affect my TTI or other simulated TTI scores. I guess I'm more concerned about whether whatever underlying version of Chrome is loading up the image or not during the test.

To restate the question: I'm curious how PSI works. I was under the impression that it used a version of Chrome to load the page, then inspected the results to make recommendations. In the pull request @paulirish references, it appears as if it simply would no longer reports the image as once to add lazyloading, whereas I thought it shouldn't even have a record of tablet_mockup.png in the first place if PSI was using a version of Chrome that supports lazyloading. 

I hope that makes sense.

**Comment by exterkamp** [comment]
>I was under the impression that it used a version of Chrome to load the page, then inspected the results to make recommendations.

Yup, this is how it works!

>it appears as if it simply would no longer report the image as one to add lazyloading to

That PR looks for `loading=lazy` attributed images and then ignores them for the purposes of deferring offscreen images because the browser makes sure they are deferred via that attribute, so we can safely ignore them. The audit isn't "adding" lazyloading to the images themselves, it is reading the attribute.

>whereas I thought it shouldn't even have a record of tablet_mockup.png

IIRC there is an intricacy of how simulated throttling works where sometimes we grab them on accident and that PR stops this by ignoring them even when that happens. 

@paulirish keep me honest.
