### ISSUE TITLE
TTI seems 3-4x higher than it should be

### ISSUE THREAD

**Issue by ssherman** [GoogleChrome/lighthouse#10651]
We have a blank page no images or text, that includes our javascript app. From looking at the lighthouse trace the main thread has no long tasks and very little activity after around 600ms. The Network tab has zero activity after around 500ms.

The TTI is being reported as around 3s. This is with default throttling on mobile, 90th percentile with 100 lighthouse runs.

We do have a setTimeout that executes some javascript every 1 second, but it takes a max of 1ms to execute, and from looking at the definition of TTI, it shouldn't affect it. 

Any ideas or thoughts?

**Comment by patrickhulce** [comment]
> From looking at the lighthouse trace the main thread has no long tasks and very little activity after around 600ms. The Network tab has zero activity after around 500ms.

What throttling settings in DevTools are you using when you see these numbers? A site that loads in 600ms with no throttling could very easily load in 3000ms "with default throttling on mobile" in Lighthouse.

**Comment by ssherman** [comment]
> > From looking at the lighthouse trace the main thread has no long tasks and very little activity after around 600ms. The Network tab has zero activity after around 500ms.
> 
> What throttling settings in DevTools are you using when you see these numbers? A site that loads in 600ms with no throttling could very easily load in 3000ms "with default throttling on mobile" in Lighthouse.

The 600ms is with the default simulated throttling. The default settings I believe are:

- Emulated Form Factor: 'mobile'
- Http Round Trip Time: 150 Ms
- Request Latency: 562.5 Ms
- Throughput (download): 1474.56 Kbps
- Throughput (upload): 675 Kbps
- CPU Slowdown Multiplier: 4x

without throttling it's way less than 600ms when all our JS stops processing

**Comment by paulirish** [comment]
@ssherman could you share a trace with us?  you can share to paulirish AT google if you don't want to post it publicly. 

we could then figure out what sort of TTI "makes sense" for this trace. :)

**Comment by patrickhulce** [comment]
Assuming this came down to the simulated throttling misunderstanding. If there's something deeper going on here that you can share the trace of, feel free to reopen.
