### ISSUE TITLE
100/100 Dark Theme with Fireworks

### ISSUE THREAD

**Issue by stallionseo** [GoogleChrome/lighthouse#10650]
Is the dark theme with fireworks display a new feature or has it been part of LightHouse for a while?

Been using LightHouse for a while and wasn't until recently (around 10 days ago) I started seeing the dark theme with fireworks output when a page gets 4X 100/100 + PWA ticked.

I took a screenshot of one of my sites with the dark theme and fireworks at https://seo-gold.com/seo-gold-coast/pagespeed-score-100/

I like it, so also made a gif.

![LightHouse Fireworks Gif](https://user-images.githubusercontent.com/1963927/80482303-e83bb100-894b-11ea-8641-e9c55c9cae9d.gif)

Sadly I've only seen it on my own websites, so few webmasters have put the work in for removing all LightHouse issues reported.

**Comment by patrickhulce** [comment]
Congrats on your 100s! 🎉 It's been around for about a year (https://github.com/GoogleChrome/lighthouse/pull/5455) I too would love to see more fireworks around the web :)

**Comment by paulirish** [comment]
So glad you like it! 
![ba-awesome-colorful-fireworks-animated-gif-image-s](https://user-images.githubusercontent.com/39191/80534600-5a17f880-8954-11ea-9148-574ee82a8391.gif)
