### ISSUE TITLE
DBW: audit for explaining that your main page is too big!

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1065]
https://tiki.vn is a great example of a main page that is WAY too big. **3.2MB, 398kb gzip**.

The main page payload should to be slim for FMP and fit within one 

We need to decide on what the sweet spot is, but I recall from [Rules of Thumb for h2 push](https://docs.google.com/document/d/1K0NykTXBbbbTlv60t5MyJvXjqKGsCVNYHyLEXIxYMv0/edit) that something like ~14KB is the recommendation because it fits within one cwnd on slow connections.

> Modern TCP implementations use an initial cwnd of about 14KB

A lot of folks bloat the main page. Let's DBW!

**Comment by ebidel** [comment]
cc @igrigorik

**Comment by slightlyoff** [comment]
I like the idea of something like the Web Bloat Score as a first-read metric for this: http://www.webbloatscore.com/

**Comment by igrigorik** [comment]
If we go down this path, you'd want to work backwards from a target load time, not KB. For example, if the `L` target is 1 second, then you must deliver all the critical path assets in <1s. From there, the KB threshold is a function of roundtrip time - e.g. see https://developers.google.com/speed/docs/insights/mobile for a deep dive.

So, one implementation of such audit could be a table of likelihoods that the page will load in <1s, broken out by network type / mobile generation:

- Consume the critical path graph and determine the longest chain.
- Identify number of handshakes required to resolve said chain: this should include dns, tcp, tls, and content download. 
- Once you know the longest RTT chain, multiply by expected latency numbers for each generation, and you arrive at the time to first render.. 

Related: https://hpbn.co/building-blocks-of-tcp/#ss-time

**Comment by patrickhulce** [comment]
+1 to adding the original page to the critical request chain and examining it more deeply.
We don't even show the original page's stats in the Performance Metrics today.

As an aside for the curious, how material is the HTML parse/DOM cost that we should care about the ungzipped size vs. size on the wire? (other than if it's inlined script that needs parsing I suppose)

**Comment by paulirish** [comment]
fixed by #1759!

**Comment by nhoizey** [comment]
As I commented in #584, it would be great if this audit also waited for a Service Worker to install and activate, to see if there is a lot of precached assets:
https://github.com/GoogleChrome/lighthouse/issues/584#issuecomment-272042112

I know this issue is closed, so please tell me if this comment should be a new issue.

**Comment by patrickhulce** [comment]
thanks @nhoizey that's probably worth a separate issue for discussion. i.e. a new audit that does "total byte weight" but for the service worker.

**Comment by nhoizey** [comment]
@patrickhulce ok, done: #9493
