### ISSUE TITLE
@font-face {   font-family: 'Pacifico';   font-style: normal;   font-weight: 400;   src: local('Pacifico Regular'), local('Pacifico-Regular'), url(https://fonts.gstatic.com/s/pacifico/v12/FwZY7-Qmy14u9lezJ-6H6MmBp0u-.woff2) format('woff2');   font-display: swap; }

### ISSUE THREAD

**Issue by rempahiris** [GoogleChrome/lighthouse#10667]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Please stop filing issues without an explanation @rempahiris. If you have a bug to report, please fill out the entire template.
