### ISSUE TITLE
TBT not measured properly on @6.0.0-beta.0?

### ISSUE THREAD

**Issue by jackyef** [GoogleChrome/lighthouse#10671]
#### Provide the steps to reproduce
1. Run LH@6 on https://m.tokopedia.com/ 

#### What is the current behavior?
With the following conditions:
![image](https://user-images.githubusercontent.com/7252454/80573360-0081fd80-8a2a-11ea-8b97-22c7ad99ac49.png)

I almost always get TBT in the range of 1000+ms
![image](https://user-images.githubusercontent.com/7252454/80573415-1db6cc00-8a2a-11ea-82d6-42a559100eb5.png)

#### What is the expected behavior?
Unless I am misunderstanding the way TBT is measured, the TBT shouldn't be that high. Profiling (using chrome devtool, clear all cookies and unregister service worker) on the same device with `fast 3g` and `4x CPU slowdown` doesn't show many block of tasks that takes more than 50ms. The biggest task block here (the gray block below DCL, a bit to the left) took only around 111ms.

![image](https://user-images.githubusercontent.com/7252454/80573789-d846ce80-8a2a-11ea-804c-ad8c9f2c06d7.png)

#### Environment Information
* Affected Channels: `lighthouse-cli@6.0.0-beta.0`
* Lighthouse version: `lighthouse-cli@6.0.0-beta.0`
* Chrome version: `80.0.3987.163`
* Node.js version: N/A
* Operating System: `macOS 10.14.6`

**Comment by patrickhulce** [comment]
Hm, I see that trace pattern behavior on Chrome Canary but not Chrome stable 
![image](https://user-images.githubusercontent.com/2301202/80603158-a49d8180-89f5-11ea-861e-1ba400a14482.png)

From my quick tests it looks like the CPU throttling dropdown in Chrome Canary *is not actually throttling* so the profile you're looking at isn't throttled which explains the discrepancy. Would you be able to confirm this by profiling with 6x throttling and without and see if there's a difference? If so, a bug filed at crbug.com would be very much appreciated.

**Comment by jackyef** [comment]
Ah you're right. The CPU throttling option in the version of chrome I was using doesn't seem to affect anything. Updating chrome seems to get it working properly now. The numbers now look similar. Sorry for the false report!
