### ISSUE TITLE
What does network-requests "endTime" indicate

### ISSUE THREAD

**Issue by EXPEpaher** [GoogleChrome/lighthouse#10673]
**Summary**
Which one of these best describes the **endTime** under network-requests section. 
1) round trip time + server latency
2) round trip time + server latency + time to download the entire response

If none of these is correct, please can you explain what endTime includes. 

https://github.com/GoogleChrome/lighthouse/blob/e55fcd2f015fc8edaa00e85d88bb7e0a997b036a/lighthouse-core/audits/network-requests.js#L52

Also, here I have assumed rtt does not include the server latency (i.e the time taken by the server to create the response). If this assumption of mine is incorrect please correct me. 

Looking forward to the answers, thanks!

**Comment by patrickhulce** [comment]
> Which one of these best describes the endTime under network-requests section.

Closest to the 2nd, round trip time + server latency + time to download the entire response.

endTime is the moment when there is nothing further left to do with this request.

> here I have assumed rtt does not include the server latency (i.e the time taken by the server to create the response). If this assumption of mine is incorrect please correct me.

I'm not sure I understand this assumption. `startTime` is the moment when the browser first tries to start issuing this request not including queueing, i.e. Chrome is about to start doing DNS lookups (if necessary), opening a TCP connection (if necessary), sending the request payload, etc. `endTime` is when *everything* for the request is done. `endTime - startTime` is the amount of time taken to complete the entire request start to finish, possibly multiple RTTs for DNS, TCP handshake, SSL handshake, and the request itself + server time taken to create the response + response download time
