### ISSUE TITLE
Pagespeed Insights and Chrome User Experience Report data accuracy

### ISSUE THREAD

**Issue by peixotorms** [GoogleChrome/lighthouse#10687]
Hi,

I have to ask, how accurate is the Chrome User Experience Report (CRuX) data shown on Google Pagespeed Insights and how does it relate with the "Experimental" speed issues listed on the webmaster tools search console?

For example, when testing google.com
`https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.google.com%2F`

we can see that

> Field Data Over the last 30 days, the field data shows that this page has a **Slow** speed compared to other pages in the Chrome User Experience Report. We are showing the 75th percentile of FCP and the 95th percentile of FID.

So my first question is, if google itself is considered **slow**, what hopes normal sites have to be fast? Does anyone know of any site that scores fast in the CRuX reports?

---

The second question is about a disparity between the data taken from the CRuX reports listed on Pagespeed Insights and the Webmaster Tools search console page.

For example:

On the Webmaster Tools Search Console page:
https://i.imgur.com/h82UR36.png

I noticed that the search console page marks some website as slow, but when testing on Pagespeed Insights, it reports as "The Chrome User Experience Report does not have sufficient real-world speed data for this page." and "The Chrome User Experience Report does not have sufficient real-world speed data for this origin.".

So... if they are both using the same source, why do their values differ and why some sites say that there is no information available, when that information is clearly available on the console search?

Also can someone clarify what's the difference between Field Data and Origin Summary ?
Is Origin Summary the whole website average and the Field Data that specific page?

**Comment by Lofesa** [comment]
> Is Origin Summary the whole website average and the Field Data that specific page?
That´s true

**Comment by Rost19802020** [comment]
Пока деньги не вернете - идите в дупу;
5 мая 2020 г. 7:25 PM пользователь "Lofesa" <notifications@github.com>
написал:

**Comment by brendankenny** [comment]
Sorry, this should have been answered long ago. For anyone still looking, theres a lot more published information these days in the [CrUX docs](https://developer.chrome.com/docs/crux/).
