### ISSUE TITLE
Scoring Calculator

### ISSUE THREAD

**Issue by jmdelacerna** [GoogleChrome/lighthouse#10685]
The [Scoring calulator](https://docs.google.com/spreadsheets/d/1up5rxd4EMCoMaxH8cppcK1x76n6HLx0e7jxb0e0FXvc/edit#gid=283330180) without editing, the calculator works fine playing around with actual metrics from audit of device type mobile, but it seems like values are way off when using metrics from actual desktop audit. Where can we find the actual metric scoring median and metric scoring falloff for both mobile and desktop?

**Comment by patrickhulce** [comment]
Thanks for filing @jmdelacerna! Those old spreadsheet calculators have been superceded by the shiny new [interactive scoring calculator](https://paulirish.github.io/lh-scorecalc/). Desktop curves were never part of the calculator, but it'd be a great feature request [over in that repo](https://github.com/paulirish/lh-scorecalc/) :)

**Comment by jmdelacerna** [comment]
@paulirish , thank you! I will move it as a feature request in the said repo.
