### ISSUE TITLE
Contains some content when JavaScript is not available - possible bug

### ISSUE THREAD

**Issue by raffa1993** [GoogleChrome/lighthouse#10681]
After running an Audit with Google Lighthouse on my website, I get the error in the subject, even if I've added to every html file of my website:
<noscript>
  <p>Some text<a href="">Some link</a></p>
</noscript>
Could it be an error from Lighthouse?
Thanks in advance,
Raffaele

**Comment by patrickhulce** [comment]
Thanks for filing @raffa1993! Please fill the entirety of the [bug report template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) with an example URL, environment information, etc
