### ISSUE TITLE
is-on-https is returning 0 when redirects-http is returning 1

### ISSUE THREAD

**Issue by moerazem** [GoogleChrome/lighthouse#10684]
If a site was tested using http:// URL, which actually redirects to https://, Lighthouse results are correctly reporting `redirects-http` as score 1.
However, `is-on-https` is being reported as score 0. Even though the final tested URL was the https:// one because of the redirect.

Am I missing something in the configuration? Shouldn't the `is-on-https` audit return score 1 because it was redirected to https://?

**Comment by connorjclark** [comment]
That may be correct for the `finalUrl`, but I don't think you can ignore the `initialUrl`. If you really want to audit the load experience of a `http:` URL that redirects to a secure context, you should consider that going to that URL would allow an attacker to snoop on the initial request. They could redirect you anywhere, even a `https:` URL that looks similar to where you are trying to go. IMO `is-on-https` scores if the URL is a secure URL, guaranteed to provide content served by the certificate holder. This isn't true if you first go to `http:`.

#10157 landed in the 6.0 beta, which will show a warning in the top of the report if there was a redirect. That extra roundtrip effects performance scores, so we wanted to encourage users to input the correct URL.

**Comment by patrickhulce** [comment]
This is now WAI in 6.0 with the warning 🎉 

See @connorjclark's response for why `is-on-https` does not pass.
