### ISSUE TITLE
Lighthouse returned error: INTERNAL: APP::1: Abnormal renderer termination, status = crashed exit_code = 1

### ISSUE THREAD

**Issue by sanctuxm** [GoogleChrome/lighthouse#10696]
#### Provide the steps to reproduce
1. Run LH on` https://sozer.com/`
  

LH works as a npm package, and chrome local audit function, but it doesn't works on Google PageSpeed: `https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsozer.com%2F`
#### What is the current behavior?
LH returns an error when progress bar is about 60% full.
#### What is the expected behavior?
Not returning an error.

#### Environment Information
* Affected Channels:  `https://developers.google.com/speed/pagespeed/insights/`
* Lighthouse version: `5.6.0 (local machine)`
* Chrome version: `81.0.4044.129 (Official Build) (64 bit) (cohort: Stable)`
* Node.js version: `v12.16.1`
* Operating System: `Windows 10 OS Version 1803 (Build 17134.648)`

**Related issues**
[This guy's problem](https://github.com/GoogleChrome/lighthouse/issues/10547)

**Comment by patrickhulce** [comment]
Thanks for filing @sanctuxm! Looks like you already found the correct issue so we'll merge these :)
