### ISSUE TITLE
It's OK to have SVG Favicons

### ISSUE THREAD

**Issue by dtruffaut** [GoogleChrome/lighthouse#10698]
**Feature request summary**

SVG Favicons should not trigger negative feedback on Lighthouse

**What is the motivation or use case for changing this?**

Currently, having a SVG favicon triggers negative feedback on Lighthouse

![lighthouse](https://user-images.githubusercontent.com/381852/80981548-6c010c00-8e2a-11ea-84c4-4521d12ec884.png)

**How is this beneficial to Lighthouse?**

Collection of PNG icons from 16x16 to 512x512 : 250 kB
A single 512x512 SVG favicon : 1,5 kB 
SVG favicons are lighter.

SVG favicons are supported in Edge, Firefox, Chrome, Safari, Opera.
https://caniuse.com/#feat=link-icon-svg

Lighthouse should consider SVG favicons as a positive signal.

**Comment by tomayac** [comment]
Note that Android still requires PNGs, which is why the installability requirements (`<ins>on Android</ins>`) are not fulfilled, which is what the test is trying to say.
