### ISSUE TITLE
Unrecognized Content-Security-Policy directive 'require-trusted-types-for'

### ISSUE THREAD

**Issue by aashutoshrathi** [GoogleChrome/lighthouse#10699]
**Describe the bug**
The directive `'require-trusted-types-for'` is legit, but it says unrecognized CSP directive.

**To Reproduce**
1. Go to web.dev
2. Test https://aashutosh.dev
3. In report click on best practices.
4. It shows this error.

**Expected behavior**
I think no browser error should log (due to `'require-trusted-types-for'`) while web.dev is visiting the site for report generation.

**Screenshots**
![image](https://user-images.githubusercontent.com/21199234/80571522-64042f00-8a1a-11ea-9654-3e07e5b3d057.png)

PS: Please correct me if I misinterpreted something completely.

**Comment by paulirish** [comment]
@aashutoshrathi it looks like you removed this directive from your CSP, right?

**Comment by connorjclark** [comment]
If the console logged it, this is coming from Chromium. I suggest making an issue on crbug.com if this doesn't align with your expectations.

looks like it's an experimental feature in chrome. https://caniuse.com/#feat=mdn-http_headers_csp_content-security-policy_trusted-types

**Comment by paulirish** [comment]
The article indicates they're supported in Chrome 83. Stable is still 81. It's very possible chrome stable emits this browser error into the console. (Not ideal, but that's how it goes sometimes.. forward compat is hard.)

This isn't a Lighthouse error, though. We're just reporting that Chrome's console has errors in it.

**Comment by aashutoshrathi** [comment]
Yeah, @paulirish I currently commented that particular CSP Directive.

![image](https://user-images.githubusercontent.com/21199234/81036089-5d166a00-8ebb-11ea-85ad-4e69424246fe.png)

Thanks for the quick followup. @connorjclark and @paulirish
