### ISSUE TITLE
First-party scripts on *.org.uk domains reported as "Research Online" third-party scripts.

### ISSUE THREAD

**Issue by dave-johnson-netcel** [GoogleChrome/lighthouse#10709]
#### Provide the steps to reproduce
1. Run LH on https://www.girlguiding.org.uk/ or https://www.landmarktrust.org.uk/

#### What is the current behavior?

The "Reduce the impact of third-party code" section of the report lists an entry for "Research Online" at the top:

![image](https://user-images.githubusercontent.com/19838981/81166377-80a8e580-8f8b-11ea-8a43-1dd3a800118c.png)

This is an erroneous entry - no such third-party script exists on either of the sites.

#### What is the expected behavior?

The "Research Online" entry should not be present.

#### Notes

This can likely be fixed by updating the **third-party-web** package dependency from 0.11.0 to 0.11.1.

The "Research Online" attribution is caused by an incorrect domain pattern, which was fixed in the following commit:

https://github.com/patrickhulce/third-party-web/commit/af5bfdb649fd7ffb8a4d117a6e56cfb617b951d4

![image](https://user-images.githubusercontent.com/19838981/81167235-cf0ab400-8f8c-11ea-9dd8-58b3b9923443.png)
 
#### Environment Information
* Affected Channels: Devtools, possibly others
* Lighthouse version:
* Chrome version: Version 81.0.4044.138 (Official Build) (64-bit)
* Node.js version:
* Operating System: Windows 10

**Comment by patrickhulce** [comment]
Thanks for filing @dave-johnson-netcel and for highlighting the fix! Our current requirement should mean that new installations of lighthouse do not suffer from this issue, but it is ironic that we were defeated by our own yarn.lock here 😆 we'll update 👍

**Comment by connorjclark** [comment]
> but it is ironic that we were defeated by our own yarn.lock here

hoisted by our own petard 😆
