### ISSUE TITLE
Network_requests audit Not giving all the network request details.

### ISSUE THREAD

**Issue by ssivanatarajan** [GoogleChrome/lighthouse#10707]
The Lighthouse network request audit is not proving all the network requests. For multiple runs of the same Url, some requests are missed in the report. I tried to find new requests between the two builds.
#### Provide the steps to reproduce
 internal URL can't expose it.
1. Run LH on <affected url>
  

#### What is the current behavior?

 For Multiple LH runs Some of the resources are missed in the network requests audit. 
#### What is the expected behavior?
For Every LH runs the network requests should be the same.

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 5.9.0
* Chrome version: 
* Node.js version: v11.15.0
* Operating System: Linux

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @ssivanatarajan but without a URL or any ability to reproduce this, we have to assume it's just [page variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) which causes this to happen naturally quite often. 

The most likely explanation beyond that is that the requests are just on the edge of our network quiet threshold. You can try running Lighthouse with a custom config that increases the [`networkQuietThresholdMs`](https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md#options-1).

Hope this helps.

**Comment by ssivanatarajan** [comment]
@patrickhulce Can I change the networkQuietThresholdMs value via node API?

**Comment by patrickhulce** [comment]
Yes, you can use a custom config with the node API, see the [referenced documentation](https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md#usage) from my previous post.
