### ISSUE TITLE
Lighthouse score thresholds do not match Web.Dev docs

### ISSUE THREAD

**Issue by CymruUSA** [GoogleChrome/lighthouse#10710]
Using Lighthouse 5.6.0 the test results do not correlate with the WebDev docs.

Webdev docs state the following;

TTI score - 0–5.2 | Green (fast) | 75–100
FCI score - 0–4.7 | Green (fast) | 75–100 (Deprecates as of v6.0)

That would imply a TTI score of 4.5 would show green (fast) but it is showing orange (moderate) same is true for First CPU Idle but I see FCI will be deprecated as of v6.0.

Docs can be found here;
https://web.dev/interactive/
https://web.dev/first-cpu-idle/

**Comment by patrickhulce** [comment]
Thanks for filing @CymruUSA ! You're right the docs are incorrect here. 

It was a [known issue](https://github.com/GoogleChrome/web.dev/issues/1344#issuecomment-524661106) but it looks like it got accidentally closed in the partial fix. 

@kaycebasques I wonder if in 6.0 we should start to move the metric docs scoring to point to the calculator so we don't have to track down all the updates lingering. It's going to be tough to track down everywhere we've talked about scoring 😅

**Comment by CymruUSA** [comment]
Same is true for Max Potential First Input Delay

https://web.dev/lighthouse-max-potential-fid/

**Comment by patrickhulce** [comment]
@brendankenny has fixed this 🎉
