### ISSUE TITLE
Reduce the length of HTML snippets

### ISSUE THREAD

**Issue by Beytoven** [GoogleChrome/lighthouse#10717]
In the audits where we show HTML snippets in detail tables, there are cases where the snippet can be extremely large. I've added a screenshot of one such example. I propose we either:

1. Truncate the HTML snippet in the same way that we do the nodeLabel field.
2. Strip down the HTML snippet to a specific set of attributes like {class,id,src} for example.

Also open to any other suggestions.

<img width="995" alt="Screen Shot 2020-05-06 at 4 22 21 PM" src="https://user-images.githubusercontent.com/27858957/81238057-e8742600-8fb5-11ea-8f9d-e5ea06022613.png">

**Comment by connorjclark** [comment]
idea: for when class is super long, we could just show the first n characters and on a tooltip show everything (in case the additional info would be useful).

**Comment by paulirish** [comment]
10820 also gave an example of data URIs.

how about we show all attributes, but the attribute values are elided at N characters?  I prefer this in case you have `<img src=usedatauri srcset=longggg class="useful-info">`

**Comment by paulirish** [comment]
oh https://github.com/GoogleChrome/lighthouse/issues/9062 covers some of this ground as well. and #6683 before it discussed similar issues

@Beytoven you're taking this one ya?

**Comment by connorjclark** [comment]
we may also want to elide more if #10716 is done, since an image is pretty good about identifying an element. or not.

**Comment by Beytoven** [comment]
> oh #9062 covers some of this ground as well. and #6683 before it discussed similar issues
> 
> @Beytoven you're taking this one ya?

I am. I like the idea of shortening attribute values to N characters. What would be a good value for N though? I'm thinking 10-20 but don't know if that's too restrictive.

**Comment by paulirish** [comment]
yah those would be too small. even in the LH report we have class attributes longer than that. :)

looking around i think we should cap at 150 or 200.  Even at 100 we'd drop some useful stuff.

**Comment by connorjclark** [comment]
fixed with #10984
