### ISSUE TITLE
Update yargs-parser dependency

### ISSUE THREAD

**Issue by PatoBeltran** [GoogleChrome/lighthouse#10722]
#### Environment Information
* Lighthouse version: 5.6.0

Hi, I'm trying to resolve some npm vulnerabilities gotten from `npm audit` on my project and there are some that are coming from this package.

```
 Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   lighthouse

  Path            lighthouse > chrome-launcher > mkdirp > minimist

  More info       https://npmjs.com/advisories/1179


  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   lighthouse

  Path            lighthouse > mkdirp > minimist

  More info       https://npmjs.com/advisories/1179


  Low             Prototype Pollution

  Package         yargs-parser

  Patched in      >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2

  Dependency of   lighthouse

  Path            lighthouse > yargs-parser

  More info       https://npmjs.com/advisories/1500
```

I've been looking and your dependency tree and it seems like you are locked into the `yargs-parser` version, you use a legacy version of `mkdirp` and `chrome-launcher` seems to use this same version. I want to remove this vulnerabilities but I don't want to update this packages and have them break your usages. What is your guidance to fix this issue?

**Comment by patrickhulce** [comment]
Thanks for filing @PatoBeltran! There is not a lighthouse 7.0.0 published to npm and the vulnerabilities in transitive deps should be fixed in 6.0.0-beta.0.

No further action from you should be necessary after updating your lighthouse version. 6.0.0 final should be released later this month.

**Comment by patrickhulce** [comment]
Oh, hang on yargs-parser wasn't patched.

**Comment by PatoBeltran** [comment]
You are right, I messed up, the lighthouse version I use is `5.6.0` the `yargs-parser` was the one that was `7.0.0` but needed to be updated. My bad.

**Comment by PatoBeltran** [comment]
@patrickhulce does `v6.0.0` also fixes the transitive dependency of `chrome-launcher` using an old version of `mkdirp`?

**Comment by patrickhulce** [comment]
Yes, see https://github.com/GoogleChrome/lighthouse/pull/10535

**Comment by Ajayyy18** [comment]
> You are right, I messed up, the lighthouse version I use is `5.6.0` the `yargs-parser` was the one that was `7.0.0` but needed to be updated. My bad.

How to update yargs-parser to the latest version??

**Comment by patrickhulce** [comment]
@Ajayyy18 #10723 does this, there's nothing for you to do on your end.
