### ISSUE TITLE
Proposal: rename time-to-first-byte to server-response-time

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#10720]
Our [`time-to-first-byte`](https://github.com/GoogleChrome/lighthouse/blob/24c0c734ee45a8d551cb151617dc836e30138077/lighthouse-core/audits/time-to-first-byte.js) opportunity isn't what is usually meant by "time to first byte" and is closer to a measure of [just the server response time (leaving out DNS, redirects, TLS)](https://github.com/GoogleChrome/lighthouse/blob/24c0c734ee45a8d551cb151617dc836e30138077/lighthouse-core/audits/time-to-first-byte.js#L47).

It's still a good Opportunity, but the name collision might get awkward as TTFB is getting more prominent in the general web vitals push (as part of the ["other [non-Core] Web Vitals"](https://web.dev/vitals/#other-web-vitals)).

I'm proposing we move the existing `time-to-first-byte` to something like `server-response-time` (or a better name than that) in time for 6.0, and we can consider if/when we should tackle a more inclusive TTFB audit in the future (we already track redirects in [`redirects`](https://github.com/GoogleChrome/lighthouse/blob/24c0c734ee45a8d551cb151617dc836e30138077/lighthouse-core/audits/redirects.js), but there are things like #6182 we could also look at).

Fun historical note: @patrickhulce suggested we not name it `time-to-first-byte` back in its original PR in https://github.com/GoogleChrome/lighthouse/pull/2126#discussion_r114598460 but we didn't follow through :)

Downsides: it's an unscored opportunity so probably not a ton of people tracking it in particular, but I assume a pain for Lighthouse CI and other downstream tooling?

**Comment by patrickhulce** [comment]
SGTM, I stand by my 2017 comment that it doesn't really make sense as TTFB so much :)

For Lighthouse CI specifically, we don't special case this audit ID, so it doesn't really matter if the structure isn't changing. 

Might be a pain for @benschwarz @mattzeunert @alekseykulikov if they specifically look for this ID in results somewhere? But even that should be a simple string fix. I was much more concerned when non-opportunity details header keys were being renamed :)

**Comment by paulirish** [comment]
Let's do it. I'm 👍
