### ISSUE TITLE
assert.strict doesn't work in bundle

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10732]
With some extra error logging, the Lightrider bundle shows this:

![image](https://user-images.githubusercontent.com/4071474/81448493-4da15600-9133-11ea-8f38-2f6c297a8fe5.png)

I'm sure the devtools bundle would show the same.

For now, let's remove the `strict` bit from critical request chains and `uses-long-cache-ttl.js`. Maybe later we'll see if we can't bundle `assert.strict` somehow. Or just remove these assertions.

related: #10606
cc @brendankenny

**Comment by connorjclark** [comment]
why didn't `yarn test-bundle` catch this

**Comment by brendankenny** [comment]
can we just turn the two `assert.ok` calls into if statements? Don't need a comment then :)
