### ISSUE TITLE
Docs say we don't test for valid colors

### ISSUE THREAD

**Issue by stephaneeybert** [GoogleChrome/lighthouse#10730]
I get this message saying the CSS color code is invalid:
`Failures: The theme-color meta tag did not contain a valid CSS color.`
I beg to differ. It's a valid CSS color code.

Whereas the Google dev page says:
`Lighthouse does not test whether the values are valid CSS color values.`
But that's contrary to what the audit complains about.

I also [published on SO ](https://stackoverflow.com/q/61566237/958373)for the record.

I can reproduce the issue by doing a Lighthouse audit of my [PWA application.](https://stephaneeybert.github.io/stephaneeybert/musicng/)

#### What is the current behavior?
I get this message saying the CSS color code is invalid:
`Failures: The theme-color meta tag did not contain a valid CSS color.`

#### What is the expected behavior?
Having no such error message.

#### Environment Information
* Chrome version: Google Chrome 81.0.4
* Operating System: Linux Lubuntu, iMac iOS

**Comment by patrickhulce** [comment]
The docs are wrong, Lighthouse does validate the color.

Can I ask why you wouldn't want to be warned about your meta color being `undefined`? :)

![image](https://user-images.githubusercontent.com/2301202/81414141-23886d80-910c-11ea-9c7e-c66da59908d7.png)

**Comment by stephaneeybert** [comment]
Spot on ! But then I have to find out why viewing the page source gives me the actual hard coded template code I have: `<meta name="theme-color" content="#E8EAF6"/>` in my `index.html` file. Somehow this template hard coded code is overwritten then.

**Comment by patrickhulce** [comment]
Js overrides it.

![image](https://user-images.githubusercontent.com/2301202/81430143-9271c080-9124-11ea-981c-9eec36bfd0fe.png)

You need to ignore the themeColor in set metadata or change https://github.com/stephaneeybert/musicng/blob/cadf9a68ed6ef198679b4bd26382339111dd6851/src/app/app.component.ts#L30-L34

to have the `color: '#E8EAF6'` :)

**Comment by stephaneeybert** [comment]
The issue was my poor understanding of the `setMetaData` method.
