### ISSUE TITLE
Audits tab of the chrome dev tools is giving different results when dev tool window is detached

### ISSUE THREAD

**Issue by kumarranjansingh** [GoogleChrome/lighthouse#10737]
---
name: Audits tab of the chrome dev tools is giving different results when dev tool window is detached

---

#### Provide the steps to reproduce
1. Run LH on any universal react app from the docked out dev tool and docked in dev tool.

  
#### What is the current behavior?
Checking from the docked out window gave results which is much lower or no result from the tool.

Error: Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)

#### What is the expected behavior?
Should give identical results.

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 81.0.4044.129
* Node.js version:
* Operating System: mac os

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @kumarranjansingh! I tried that but I got identical results. 

Could you please fill out *the entire* [bug report template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)? Very specifically what is different, what URL were you testing, etc.

**Comment by kumarranjansingh** [comment]
@patrickhulce, I have updated the bug.

**Comment by patrickhulce** [comment]
Did you fully occlude the window you were auditing after you undocked DevTools?

macOS will background them and Chrome will not paint any windows that are occluded. The page needs to be visible while being audited.

**Comment by kumarranjansingh** [comment]
@patrickhulce, Not fully occlude, But its a random issue, as you rightly pointed out, could be macOS issue where it stops the window from painting. Thanks.

**Comment by connorjclark** [comment]
possible related: #9650
