### ISSUE TITLE
utm_medium on PSI links is set to "unknown"

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/lighthouse#10747]
#### Provide the steps to reproduce
1. Run an audit using PSI
2. Click a link in the report to web.dev
  
#### What is the current behavior?
The utm_medium on the link is set to unkown

#### What is the expected behavior?
The utm_medium should be set to 'psi' or something similar.

**Comment by connorjclark** [comment]
@exterkamp


https://github.com/GoogleChrome/lighthouse/blob/4f6170d74b6ce608c381cf288e3d88163ae250ef/lighthouse-core/report/html/renderer/report-renderer.js#L48

are we setting the channel in LR/PSI?

**Comment by connorjclark** [comment]
just checked LHR from LR–`channel` is set to psi.

i know the rendering for PSI is unique, does it even call `renderReport`?

**Comment by brendankenny** [comment]
I believe @paulirish was looking at this and saw that `psi.js` needs to call `dom.setLighthouseChannel()`. Not sure how he wanted to delegate the fix, though :)

**Comment by connorjclark** [comment]
not an issue anymore.
