### ISSUE TITLE
Auth via API not working

### ISSUE THREAD

**Issue by jmartinezpoq** [GoogleChrome/lighthouse#10755]
Looking info about how to test web under auth I found [this info](https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md) on the readme

Reading this I understand that to auth via API you must pass the param `extra-header` with the next format on the value:
```
"{\"Authorization\":\"Basic HASH_AUTH\"}"
```

But when I'm passing this param the auth doesn't work 
#### Provide the steps to reproduce
1. Run LH on the page with auth
  
```
https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=URL&key=API_KEY&strategy=mobile&extra-headers="{\"Authorization\":\"Basic AUTH_HASH\"}"&category=performance
```
#### What is the current behavior?
The current response is:
```
{
  "error": {
    "code": 500,
    "message": "Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 401)",
    "errors": [
      {
        "message": "Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 401)",
        "domain": "lighthouse",
        "reason": "lighthouseError"
      }
    ]
  }
}
```

#### What is the expected behavior?
Doing the test correctly.

For clarification, the problem is not on the URL to test the auth works fine.

#### Environment Information
* Affected Channels: API
* Version: 5

**Comment by jmartinezpoq** [comment]
necessarily-wide-alpaca

**Comment by connorjclark** [comment]
--extra-headers is for the CLI. There is no way to do auth via the PSI API.

**Comment by jmartinezpoq** [comment]
Thank you for the info.
@connorjclark
