### ISSUE TITLE
Phantom overflow menu displaying when attempting to print report (Summary or Expanded) (Chrome Extension)

### ISSUE THREAD

**Issue by gtallen1187** [GoogleChrome/lighthouse#10752]
#### Provide the steps to reproduce
1. Run LH on https://www.indigoag.com
  

#### What is the current behavior?

Currently, when attempting to print the Lighthouse report (both the Summary and the Expanded version) it looks as though the contents of the opened overflow menu are being overlaid on top of the actual report.  I've included screenshots below of how this looks when attempting to print both the Summary and Expanded report.

**Print Summary**

 > ![image](https://user-images.githubusercontent.com/4712768/81628667-47c7a100-93cf-11ea-84e9-4c97238da891.png)

**Print Expanded**

 > ![image](https://user-images.githubusercontent.com/4712768/81628796-937a4a80-93cf-11ea-9312-5b06ed5c8dd6.png)

The actual lighthouse report runs perfectly fine.  This issue is related to the Print features, both the 

#### What is the expected behavior?

The expected behavior is that when printing the Lighthouse report from the overflow menu using the Chrome extension, the report should print without including this overlaid phantom menu.

#### Environment Information
* Affected Channels: Extension
* Lighthouse version: Chrome Extension v100.0.0.0
* Chrome version: 83.0.4103.44 (Official Build) beta (64-bit)
* Node.js version: N/A
* Operating System: macOS version 10.15.4 (19E287)

**Related issues**

**Comment by brendankenny** [comment]
Hi @gtallen1187,

Yes, sorry about that. This was fixed in #10216 and will available in the upcoming 6.0 release (available via the extension very soon).

**Comment by paulirish** [comment]
The 6.0 release is now out. ;) https://github.com/googlechrome/lighthouse/releases
