### ISSUE TITLE
Use custom css in lighthouse plugin

### ISSUE THREAD

**Issue by arnoldczhang** [GoogleChrome/lighthouse#10753]
**Summary**

The style of `Performance` category is pretty good, like this:

![image](https://user-images.githubusercontent.com/7811147/81635485-ea216c00-9443-11ea-814e-646b19a906aa.png)

So can I use these styles in a lighthouse plugin?

I have tried these codes in the plugin,

```js
const performance = {
  audits: [
  ],
  category: {
    auditRefs: [
      {id: 'first-contentful-paint', weight: 3, group: 'metrics'},
      {id: 'first-meaningful-paint', weight: 2, group: 'metrics'},
      {id: 'speed-index', weight: 4, group: 'metrics'},
      {id: 'interactive', weight: 5, group: 'metrics'},
      {id: 'first-cpu-idle', weight: 2, group: 'metrics'},
      {id: 'max-potential-fid', weight: 2, group: 'metrics'},
    ],
    description: 'description',
    title: 'title',
  },
  groups: {
    metrics: {
      title: 'metrics',
    },
  },
};

export = performance;
```

which come out like this:

![image](https://user-images.githubusercontent.com/7811147/81635280-741d0500-9443-11ea-97d2-39de180ecdff.png)

Please tell me how to modify this, thanks.

**Comment by connorjclark** [comment]
Unfortunately, no. Performance category uses a custom renderer defined here: https://github.com/GoogleChrome/lighthouse/blob/master/report/renderer/performance-category-renderer.js which the plugins don't have access to.
