### ISSUE TITLE
Remove FCP bound from Max FID

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#10760]
**Feature request summary**

[Max Potential First Input Delay](https://web.dev/lighthouse-max-potential-fid/) documents the following behavior:

> Tasks before First Contentful Paint are excluded because it's unlikely that a user will attempt to interact with your page before any content has been rendered to the screen, which is what First Contentful Paint measures.

I'd like to see this boundary removed because FID in the wild could feasibly happen at any time during page load, including before FCP and when there are no interactive elements on the page.

Because this metric is explicitly named "max potential FID" I think it's right that it represents all of the worst case scenarios, including those in which the longest task is before LCP.

**What is the motivation or use case for changing this?**

Alignment with how FID is implemented to account for inputs earlier than LCP.

**How is this beneficial to Lighthouse?**

The metric would be more inclusive of long tasks that could feasibly lead to worse FID than previously reported.

**Comment by rviscomi** [comment]
@philipwalton do you agree with this change?

**Comment by paulirish** [comment]
fwiw, mpFID isn't visible in 6.0 so this certainly isn't as important.

Outside of that, I'd argue that FID shouldn't consider tasks before FCP, but I recognize that's a larger conversation. :)

**Comment by paulirish** [comment]
We're going to leave this as a Known Issue.

But maxFid isn't in the LH 6.0 report anymore so it's not worth it to resolve the inconsistencies. :)

**Comment by rviscomi** [comment]
SGTM. FWIW the same applies to TBT which I understand is still in v6.

**Comment by brendankenny** [comment]
> SGTM. FWIW the same applies to TBT which I understand is still in v6.

@rviscomi is there somewhere this discussion is taking place? AFAIK TBT isn't standards track and Lighthouse and Chrome impls both use FCP as the start time.

**Comment by patrickhulce** [comment]
> FID in the wild could feasibly happen at any time during page load, including before FCP and when there are no interactive elements on the page.

@rviscomi do you mind linking to an example where this is happening? I was unable to reproduce a FID event via `PerformanceObserver` on a test page before FCP, but I filed https://github.com/WICG/event-timing/issues/84 either way.

**Comment by rviscomi** [comment]
I'm seeing the behavior in the Web Vitals extension, based on web-vitals.js, if that matters. But it's hard to reproduce.

**Comment by patrickhulce** [comment]
Ah, OK so we got clarification that Chrome itself ignores all click events before the first paint, so by inheritance FID does too.

But if you click between FP and FCP or use the *keyboard* before FCP then those will get counted as FID.
