### ISSUE TITLE
How I can execute the java-script in the browser console if browser is launched through nodejs/lighthouse driver library

### ISSUE THREAD

**Issue by SajjadSPG** [GoogleChrome/lighthouse#10769]
**How I can execute the java-script in the browser console if a browser is launched through nodejs/lighthouse driver library**

When the browser is launched I want to run a script in the console and wanted to get some stats. But the lighthouse is using nodejs driver launcher which seems not having .execute_javascript("function f(){ return something like this since selenium has this facility. 

Can you kindly guide me, once the browser is opened and performance is being captured how i can execute a function in the console and fetch some stats?

**Comment by patrickhulce** [comment]
Could you share a little more of your context here?

Are you writing a custom gatherer for Lighthouse?
Do you need to execute this javascript in the same run as Lighthouse or can it be separate?
Do you care about the Lighthouse results too or are you just trying to use Lighthouse to capture these stats?

The answer will change based on your answers but if you're using Lighthouse's driver, then you want `driver.evaluateAsync("function f() { ...")` if you are just looking for a way to capture your stats from a page load then [puppeteer](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args) is probably what you're looking for.

**Comment by SajjadSPG** [comment]
> Could you share a little more of your context here?
> 
> Are you writing a custom gatherer for Lighthouse?
> Do you need to execute this javascript in the same run as Lighthouse or can it be separate?
> Do you care about the Lighthouse results too or are you just trying to use Lighthouse to capture these stats?
> 
> The answer will change based on your answers but if you're using Lighthouse's driver, then you want `driver.evaluateAsync("function f() { ...")` if you are just looking for a way to capture your stats from a page load then [puppeteer](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args) is probably what you're looking for.

Thanks for replying back on time.

I wanted to execute the custom script when the page loading is completed while lighthouse is done with capturing the stats. So the idea is one of the internal performance stats calculation is done and it is printing the stats in the console. Idea is that once lighthouse is done with the performance before killing the browser wanted to execute the javascript in the console a function something like app_performance.duration which will return our own calculation. I am trying to do it in the custom gatherer under afterPass method. 

Once I have these stats, I will fetch those stats in seconds and will push back to the final report where along with Google lighthouse stats a bubble will appear having these numbers that are it. No further detailed capture only one bubble to see what is the internal system calculation duration is there.

**Comment by patrickhulce** [comment]
Are you asking me how to handle `Promise`s? I'm afraid that's beneath the scope of GitHub issues here.

FWIW, you don't want to try to read your stats from the `console` output in case that's the direction you were hoping to head. That's going to be much, much harder. Have `layer.simple.js` put whatever stats you care about onto the `MILoggingStats` global object (or whatever global object you like) and read them through `evaluateAsync`. 

Our recipes have examples for how to handle the Promise-based return value.

https://github.com/GoogleChrome/lighthouse/blob/f625ab798b3a50298a59feb86df2da63ab4bc0ec/docs/recipes/custom-audit/searchable-gatherer.js#L14-L28

**Comment by connorjclark** [comment]
if you use the User Timings API, Lighthouse will present those results in one of our diagnostic audits.

https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API
