### ISSUE TITLE
Continually different scores when no changes made to site. Confused.

### ISSUE THREAD

**Issue by GigaMick** [GoogleChrome/lighthouse#10772]
My domain: https://songbox.rocks

I can run the lighthouse test back to back and get scores that vary from high 60s to high 80s. I've had a few 95s but I've no idea how to get them again haha.

I'm wondering if Lighthouse tests different random subsets of criteria each time?

Also... if I may. I keep getting the "defer offscreen images" flag against the same two images. These images have the same "loading='lazy'" on them as all the other images, but these two keep getting flagged.

The site is hosted on Heroku, if that makes any difference.

Would really love some insight. Thanks :-)

Here are two tests that I just ran on the same site no more than 30 seconds apart:

<img width="966" alt="Screenshot 2020-05-13 at 21 51 47" src="https://user-images.githubusercontent.com/22120297/81864157-251ac100-9564-11ea-8935-2a6c614da122.png">

<img width="996" alt="Screenshot 2020-05-13 at 21 52 11" src="https://user-images.githubusercontent.com/22120297/81864167-2815b180-9564-11ea-841a-25228a77f39a.png">

**Comment by patrickhulce** [comment]
Thanks for filing @GigaMick! Please see the [variability docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) as this topic has been extensively covered there.

> These images have the same "loading='lazy'" on them

See #6677. 

> The site is hosted on Heroku, if that makes any difference.

If you're on the lower tiers of heroku and the app had been asleep, the server will take several full seconds to startup and that will *definitely* impact the results.

**Comment by GigaMick** [comment]
Thanks for the reply! No I'm using paid dynos so the server doesn't sleep. I'll look into your other points.

Once again thank you for the very quick response.
