### ISSUE TITLE
Performance test -> crashes the debug tools? 

### ISSUE THREAD

**Issue by Schuer84** [GoogleChrome/lighthouse#10777]
When I run the perfomance test on a local site, it crashes. 

![image](https://user-images.githubusercontent.com/389703/81872574-45ee1100-957a-11ea-8791-f4c687af7e1b.png)

![image](https://user-images.githubusercontent.com/389703/81872603-53a39680-957a-11ea-90c4-b3960d8d24c7.png)

What is that test doing? I'm only able to reproduce this crash with the performance test, the other tests work fine. Any ideas/suggestions? 

I also notice that, after a crash, i have to manualy start my service worker. 
![image](https://user-images.githubusercontent.com/389703/81873062-420ebe80-957b-11ea-8338-64d688e4382d.png)

**Comment by connorjclark** [comment]
URL?

**Comment by Schuer84** [comment]
https://localhost:5001/ ...

**Comment by Schuer84** [comment]
@connorjclark https://mailhelper-dev-api.azurewebsites.net/

**Comment by connorjclark** [comment]
cool, that helps!

Simply opening that page in devtools hangs the tab... sometimes.

I get protocol timeout errors in LH report.

Same when running the latest master CLI

turns out `CSSUsage` take realllllly long

![image](https://user-images.githubusercontent.com/4071474/81874044-e835d680-9531-11ea-94e5-cfa1a16df361.png)

**Comment by connorjclark** [comment]
is there any sort of devtools detection on this page?

**Comment by Schuer84** [comment]
CSSUsage? dont you mean JsUsage? thats +42s in your image?  
Devtools detection, not that I'm aware off.

**Comment by connorjclark** [comment]
> CSSUsage? dont you mean JsUsage? thats +42s in your image?

the timestamps are misleading. the number is how long the previous log output took.

You have 4MB of CSS which I guess breaks LH and DevTools :) closing / opening devtools consistently hangs the page for me.

Seems like before you can use LH you will need to reduce your CSS. I blocked `main.css` in the network panel and LH worked.

> For my understanding.. how do you generate these stats?

It's just our Node CLI.

https://github.com/GoogleChrome/lighthouse#using-the-node-cli

**Comment by Schuer84** [comment]
Aha, yeah it's still work in progress. Atleast now I know where to look. 
Thanks for the feedback! Much appreciated!

**Comment by connorjclark** [comment]
sure thing!

btw team, here is what the LH report looks like when CSSUsage times out:

![image](https://user-images.githubusercontent.com/4071474/81874745-66df4380-9533-11ea-8acb-8a3798568d7d.png)

I don't think there's anything else we could do in this case, so closing.
