### ISSUE TITLE
Lighthouse-batch gatherer example

### ISSUE THREAD

**Issue by Preethi0689** [GoogleChrome/lighthouse#10782]
Hi Team,

Lighthouse is really helpful.But we would like to know an example of a login page and passing formdata to the next url via gatherer.It will be really helpful.Please assist.

**Comment by patrickhulce** [comment]
Hi @Preethi0689 we're not affiliated with `lighthouse-batch`. Did you mean to file on their repo (https://github.com/mikestead/lighthouse-batch)?

**Comment by paulirish** [comment]
@Preethi0689 this may be more of what you want to do? https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md
