### ISSUE TITLE
Request: add the option for developers to report abusive sites to host

### ISSUE THREAD

**Issue by I-Cat** [GoogleChrome/lighthouse#10797]
**Summary**
<p>
<a>
When Testing via light house. I would like to also have the option to report abusive web sites to hosts
example would be a virus ad pop up or an ad that redirects you to malicious web sites.
Thank you 
<a/>
<p/>

**Comment by patrickhulce** [comment]
Thanks for filing @I-Cat! Could you clarify who you want to report abusive sites too? 

If you're referring to a report to a shared webhost provider, I'm not sure how Lighthouse helps there.

**Comment by I-Cat** [comment]
> Thanks for filing @I-Cat! Could you clarify who you want to report abusive sites too?
> 
> If you're referring to a report to a shared webhost provider, I'm not sure how Lighthouse helps there.

That's why I was asking. Because I don't know Whom To report a malicious web sites to.

**Comment by connorjclark** [comment]
Why are you using Lighthouse on sites you think are malicious?

**Comment by I-Cat** [comment]
> Why are you using Lighthouse on sites you think are malicious?

So we can report them

**Comment by Malvoz** [comment]
Google's [Safe Browsing](https://safebrowsing.google.com/) has a [report malware](https://safebrowsing.google.com/safebrowsing/report_badware/?hl=en) and a [report phishing](https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en) page.

**Comment by connorjclark** [comment]
There's a large disconnect here between what Lighthouse does and what you want it to do. @Malvoz has pointed you in a better direction.
