### ISSUE TITLE
SPA with manifest.json console.log Best practices error

### ISSUE THREAD

**Issue by rasmus0201** [GoogleChrome/lighthouse#10809]
#### Provide the steps to reproduce
1. Run LH on https://www.google.com/
  

#### What is the current behavior?
Under "Best practices" the following error is present when running audits in incognito mode in Chrome `"Browser errors were logged to the console"`. This is not something that is controllable by the website, and shouldn't be punished for it in the audit.

#### What is the expected behavior?
LH will not count the console.log generated from the browser i.e the `Site cannot be installed: Page is loaded in an incognito window` error

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.7.0
* Chrome version: 81.0.4044.138
* Node.js version:
* Operating System: MacOS Mojave 10.14.6

**Comment by patrickhulce** [comment]
Thanks for filing @rasmus0201!

> the Site cannot be installed: Page is loaded in an incognito window error

I cannot reproduce this error on the provided URL in incognito on either Chrome stable or canary. Any other steps missing you can provide to help?

> LH will not count the console.log generated from the browser

In *general* this is not a statement we would agree with. If the browser is logging *an error* while it tries to load your page, Lighthouse should generally warn you about that. But the case about incognito which we encourage you to use for a clean environment is definitely an exception we'd like to fix if we can reproduce it :)

**Comment by rasmus0201** [comment]
Thanks for quickly replying. 

Glad to hear you are open to fix this. But after further debugging I found that chrome only triggers this error when the flag "Bypass user engagement checks" is enabled (chrome://flags/#bypass-app-banner-engagement-checks).


So I guess this is a special case, though nonetheless frustrating with this unexpected behavior, but the flag is very useful when testing PWAs and native android app banners.

**Comment by patrickhulce** [comment]
Ah gotcha. Yeah definitely a special case. Honestly I'm inclined to push back on Chromium itself making this an *error*. It is pure noise throwing it in there even if the page has absolutely no interest in being installed.

It's just about prompting for install which is a sortof optional thing anyway. I'd argue this should be warn and even then only if the page has a manifest.

**Comment by patrickhulce** [comment]
Filed upstream 👍  https://bugs.chromium.org/p/chromium/issues/detail?id=1084599

**Comment by rasmus0201** [comment]
@patrickhulce Perfect! Thanks 🥇
