### ISSUE TITLE
Client CPU v. network usage balancing point

### ISSUE THREAD

**Issue by alystair** [GoogleChrome/lighthouse#10803]
I've been mulling over build tools for a web framework and came to the following thought:

Pre-processing/rendering:
* reduces JS init/CPU time on per-client basis
  * but generates a larger initial network transfer
* reduces total JS necessary
  * but increases library code uniqueness, thus less global/public CDN friendly

Are there any thoughts about this?

**Comment by patrickhulce** [comment]
Thanks for filing @alystair! 

> reduces JS init/CPU time on per-client basis but generates a larger initial network transfer

We attempt to balance the overall performance score with metrics that address these different concerns. For example, prerendering will tend to decrease FCP but you pay a cost for the hydration step by increasing TTI. We feel pretty good that whatever strategy increases the overall performance score in LH tends to be the correct tradeoff (unless you've already hit the edges on a metric and can't get any better/worse). If you find any counter examples, we'd love to address them in future iterations :)

> increases library code uniqueness, thus less global/public CDN friendly

*Without a doubt, reduce your total JS footprint*. It's largely a performance myth that using a shared library from a CDN increases performance. Users infrequently get to reuse CDN assets from other domains and all major browsers are moving to a double-keyed cache (Safari has already doneso) where you *can't* reuse CDN assets initiated by another origin. See [Chrome's intent to implement](https://groups.google.com/forum/#!msg/mozilla.dev.platform/eFx-93iBPpU/4HQ2UFN9DgAJ) from late 2019.

**Comment by alystair** [comment]
Thanks for your input, will definitely go with the 'render once' approach in this case!

For context I've been working on a full stack SPA solution in stealth for past few years and will soon open sourcing a v0 (just library portion for now). No React/Vue/etc... Perfect Lighthouse v6 scores across the board before any optimization, although I still worry about CLS :^)

**Comment by patrickhulce** [comment]
Great! Be sure to @____lighthouse on Twitter with those straight 100s when you release ;)
