### ISSUE TITLE
Lighthouse always times out (80s+) for this URL

### ISSUE THREAD

**Issue by DanShappir** [GoogleChrome/lighthouse#10811]
This is a Wix site: https://www.bramhallgrill.com/

PSI always fails with an error:
Lighthouse returned error: INTERNAL: Extension result empty. Lighthouse calling Page.navigate with https://www.bramhallgrill.com/ Uncaught (in promise) Error: Extension timed out. No call to exit() before render timeout. at wrs.Extension.onTimeout_ (http://ghost-rider/devtools_script_api.js:5567:13) at http://ghost-rider/devtools_script_api.js:669:9 at Map.forEach (<anonymous>) at chromium.DevTools.Connection.dispatchMessage (http://ghost-rider/devtools_script_api.js:668:76) at chromium.DevTools.Connection.onJsonMessage_ (http://ghost-rider/devtools_script_api.js:650:65) at <anonymous>:1:40

Canary LH occasionally fails with an error.

**Comment by exterkamp** [comment]
Thanks for filing! I made an update to PSI that hopefully makes this error a bit more clear.

![image](https://user-images.githubusercontent.com/6392995/95134649-18b42200-0718-11eb-9f44-e8de1a24012c.png)

This site takes too long to analyze, even locally in DevTools, this site takes 80 seconds plus, which will timeout on Pagespeed, so this is WAI from a Pagespeed perspective. But this is something to look into on the Lighthouse side!

**Comment by connorjclark** [comment]
This seems to work now for this URL.
