### ISSUE TITLE
Lighthouse report has more than 10000px worth of warnings

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#10812]
## Provide the steps to reproduce
1. Run LH on https://www.bramhallgrill.com/

#### What is the current behavior?
Fonts audit adds about a bazillion warnings that cannot be collapsed
![image](https://user-images.githubusercontent.com/2301202/82340349-c070c380-99b4-11ea-92d5-7d5e8bb7c0db.png)

#### What is the expected behavior?
Not that.

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/10811

**Comment by connorjclark** [comment]
lol

related: https://github.com/GoogleChrome/lighthouse/issues/9775

**Comment by brendankenny** [comment]
rolling into #9775 which is already p1 and is assigned.
