### ISSUE TITLE
Ability to run multiple times to deal with variability

### ISSUE THREAD

**Issue by mehulkar** [GoogleChrome/lighthouse#10825]
**Feature request summary**
To deal with variability, the docs [recommend running lighthouse multiple times][1] and aggregating values. It would be great to add this as a feature to `lighthouse` itself.

**What is the motivation or use case for changing this?**

There are many ways to aggregate values, but choosing a good strategy requires a decent understanding of both lighthouse and statistics. Consolidating these knowledge into lighthouse itself would be very valuable.

This work is being [reproduced][3] in [user land][4] and every new user has to implement their own algorithm. This not only makes results harder to compare, it wastes valuable developer time that could instead be spent making the web faster.

**How is this beneficial to Lighthouse?**

Lighthouse CI already implements an algorithm to find ["representative runs"][2] based on FCP and TTI, so there is evidence that the team already thinks this is a beneficial feature. Moving this to the core module would allow the lighthouse team to retain this algorithm and also change it when needed (e.g. with the 6.0 release)

[1]: https://github.com/GoogleChrome/lighthouse/blob/v6.0.0/docs/variability.md#run-lighthouse-multiple-times
[2]: https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/utils/src/representative-runs.js
[3]: https://github.com/palfi-ltd/pagespeed-score
[4]: https://github.com/samdutton/multihouse

**Comment by connorjclark** [comment]
We've always opted to leaving this for other tools, to keep this tool simpler. It's a goal of our to reduce variability as much as we can on our side–we simulate the network requests in a way that it mostly doesn't matter how long things take (there are some edge cases where this doesn't exactly work out, for example any JS that does scheduling that results in network requests isn't taken into account)

> There are many ways to aggregate values, but choosing a good strategy requires a decent understanding of both lighthouse and statistics. Consolidating these knowledge into lighthouse itself would be very valuable.

But this is a fairly convincing point :) I'll mark this as an item to discuss in our next eng meeting.

**Comment by mehulkar** [comment]
@paulirish pointed me to https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/utils/src/representative-runs.js, so pinging him as well.

As a case study, my first stab at this was to take median values of each audit individually. It took me ~2 weeks to understand the LHR json output and then implement the code to get median values of each audit, before I realized that it was a flawed strategy, since audits would no longer be comparable (might be from different test runs). 

I realize that it'll be tricky to do this if categories/audits are customized though, so I'm not sure what to do about that.

**Comment by paulirish** [comment]
Aye. Just for posterity... this was a thread in the webperf slack: https://webperformance.slack.com/archives/C04BK7K1X/p1590090290208600

For multiple runs, the easy way is to use lhci locally for that:

```sh
npx -p lighthouse-ci lhci collect --url http://example.com -n 5
```  
and then look at your `.lighthouseci` folder

**Comment by paulirish** [comment]
plans:

- add docs in variability to use this technique (& syntax)
- move representativeRuns to core
- Rough Future: pursue a lh-tools library/product where this/compare-runs/lh-swiss all live
