### ISSUE TITLE
Data URLs aren't truncated in node snippet previews

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#10820]
#### Provide the steps to reproduce
1. Run LH on a URL with a massive data URL that's missing an `alt` attribute
  
#### What is the current behavior? 
![image](https://user-images.githubusercontent.com/2301202/82462581-5ffb8800-9a81-11ea-9c6e-39767a2a8e78.png)

https://twitter.com/_dsanderson/status/1262975552886996992

#### What is the expected behavior?

Report elides the data URL in the node preview

**Comment by paulirish** [comment]
dupe into #10717
