### ISSUE TITLE
Extension Error: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by NoNameProvided** [GoogleChrome/lighthouse#1082]
**Lighthouse Version**: 1.2.2
**Chrome Version**: 54.0.2840.98
**Error Message**: Cannot read property 'message' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'message' of undefined
    at collectUsage.then.e (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:4444:23)
```

I tried to run it on hwsw.hu

**Comment by patrickhulce** [comment]
should hopefully be fixed when #1037 lands

**Comment by wardpeet** [comment]
@NoNameProvided @patrickhulce fixed?

**Comment by patrickhulce** [comment]
yeah #1037 ensures that all failures become error objects, so we should be covered here
