### ISSUE TITLE
Link to https://web.dev/image-size-responsive/ returns 404

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#10839]
**Summary**
When you run LH v6.0.0 in Chrome Canary or wpt channel, in the "Best Practices" section, "Display Images with appropiate size", the link "learn more" that point to https://web.dev/image-size-responsive/ returns a 404.

**Comment by patrickhulce** [comment]
Thanks for filing @Lofesa ! We updated the link in core to not send the user there (#10801) and https://github.com/GoogleChrome/web.dev/issues/2402 tracks solving the 404 issue on the web.dev side.
