### ISSUE TITLE
Improving the PWA 'all groups passing' badge

### ISSUE THREAD

**Issue by alystair** [GoogleChrome/lighthouse#10831]
**Feature request summary**
I was recreating/optimizing the Lighthouse scoring SVG for a demo page, so I came up with a neater looking version.

![image](https://user-images.githubusercontent.com/159109/82719959-ff389f00-9c7c-11ea-946d-1189ed60544d.png)

**What is the motivation or use case for changing this?**
As seen on [scoring.md](https://github.com/GoogleChrome/lighthouse/blob/master/docs/scoring.md)
![image](https://user-images.githubusercontent.com/159109/82719942-e7611b00-9c7c-11ea-8a48-7e5bce6f918f.png)

I realized the 'perfect' version of the PWA badge is pretty dull compared to the other ones...

**How is this beneficial to Lighthouse?**

Nothing motivates folks like a shiny badge. Bonus points if it could be teased :)

**Comment by brendankenny** [comment]
Thanks for filing! This looks good but isn't something we're going to consider right now as it would also require evaluating in the context of the surrounding score gauges for other categories, text, etc. Added the `report` label so we can come back to this issue the next time we're looking at the PWA badge.
