### ISSUE TITLE
Slow open of my site

### ISSUE THREAD

**Issue by Pratik8299** [GoogleChrome/lighthouse#10837]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by Pratik8299** [comment]
I m opening my site it takes lot of time for loading pls check my site 
www.cellfact.blogspot.com
And fix my isse or give my step to fix it myself

**Comment by patrickhulce** [comment]
That's not what this forum is for. Follow the advice and steps in the report to improve your site. If you don't know where to start, read some of the guides and documentation on https://web.dev/
