### ISSUE TITLE
Run lighthouse by Goolge Cloud Functions and artifact required for the audit is missing or error.

### ISSUE THREAD

**Issue by phivh** [GoogleChrome/lighthouse#10834]
**Summary**
I got this runner warning and eventually it throw an error.
all artifacts got error when collecting the data.

{
...
 textPayload: "Sat, 23 May 2020 17:53:21 GMT GatherRunner:error DNS servers could not resolve the provided domain. http://web.dev/
...
}

{
...
 textPayload: "Sat, 23 May 2020 16:17:07 GMT Runner:warn devtoolsLogs gatherer, required by audit is-on-https, did not run."  
...
}

Infrastructure:
Node runtime: 8
Chrome headless puppeteer.
"dependencies": {
    "lighthouse": "^5.6.0",
    "puppeteer": "^2.0.0",
    "firebase": "^7.14.3",
    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.6.1"
  }

**Comment by brendankenny** [comment]
- can you clarify where you were running Lighthouse and ran into this error?
- can you load http://web.dev/ in a browser on its own? Some people have had DNS issues with the `.dev` TLD, which would explain why it couldn't be loaded
- note that Lighthouse requires Node 10 as a minimum version, which is unlikely to cause a DNS problem but could be causing other errors.

**Comment by phivh** [comment]
> * can you clarify where you were running Lighthouse and ran into this error?
> * can you load http://web.dev/ in a browser on its own? Some people have had DNS issues with the `.dev` TLD, which would explain why it couldn't be loaded
> * note that Lighthouse requires Node 10 as a minimum version, which is unlikely to cause a DNS problem but could be causing other errors.

Hi @brendankenny , i solved this problem, the cause is I'm used free account which means firebase doesn't allow to connect the network for open chromium-browser on there.

Thanks for your time.
