### ISSUE TITLE
How to interpret timestamps

### ISSUE THREAD

**Issue by mwhitaker** [GoogleChrome/lighthouse#1083]
Hi there,
I am sorry if this is not the right place to ask, but I was wondering if you can point me in the right direction about how to interpret **timestamps**, as they don't seem be based on Unix time?

"extendedInfo": {
        "formatter": "speedline",
        "value": {
          "first": 1162,
          "complete": 4974,
          "duration": 6809,
          "frames": [
            {
              "timestamp": **428716523.56**,
              "progress": 1.936135711528325
            },

Thank you for a great project!
Michael

**Comment by ebidel** [comment]
@paulirish @brendankenny aren't these from https://github.com/pmdartus/speedline#frame?

**Comment by paulirish** [comment]
hey @mwhitaker. the timestamp in here is the high-resolution timestamp: https://w3c.github.io/hr-time/

If you also have a high-res timestamp of NavStart then you can figure out the delta here.

These values come over from speedline. If you wanted them provided as relative to navigationStart, that could make sense. it'd be a feature request at speedline. :)

**Comment by brendankenny** [comment]
I'm going to close as it appears the question was answered. Feel free to reopen if that wasn't sufficient :)
