### ISSUE TITLE
Impact of animations on lighthouse v6? 

### ISSUE THREAD

**Issue by kuworking** [GoogleChrome/lighthouse#10833]
*In relation to Lighthouse v6 (in Chrome Canary)

I've seen much worse ratios that what I can obtain with v5.6, and what I'm finding is a big impact on any animations present in the front page, where these animations are merely visual

I believe to see that the `Largest Contentful Paint` (in mobile) seems to finish when any animation ends, as I see in the report a `LCP` value of ~7s (in this case), even though later in `Performance` I can see the label `LCP` appearing at ~800ms

Perhaps somebody could explain a little bit what would be the best way to add animations on the first page without affecting LCP, or if the suggested attitude is to eliminate any animation from the front page (?)

**Comment by patrickhulce** [comment]
Thanks for filing @kuworking! LCP should not care about any animations and I'm not able to reproduce this behavior on a test page (https://melodic-class.glitch.me/animation.html). Do you have a specific URL that we can look at?

> even though later in Performance I can see the label LCP appearing at ~800ms

Where do you see this? It's almost certainly a bug.

What I think is going on is that LCP *does* care about images being *fully* loaded and the time that's reported is when the image is completely loaded and not when it is first visible. This time can be different due to progressive images and iterative paints.

**Comment by kuworking** [comment]
@patrickhulce 🙋‍♂️

With regard to the animations, I need to update the repo and then I'll post here
With regard to the discrepancy between the report and the view trace (which I've come to think that the trace is what my computer sees without throttling), I do see it with this gatsby starter (not mine)

https://parmsang.github.io/gatsby-starter-ecommerce/

I paste here what I've seen in my chrome canary just now (LCP at 1.2s in viewTrace, 6.4s in the report, I've assumed they refer to the same thing)

** Also, when you say ` images being fully loaded`, it is true that if I remove the images then time reduces a lot, they are small images (<50 o even 20K), but it is difficult to assert from the devtool that they are indeed being still downloaded or (re)painted
This is actually something I ignore, I assumed that when they appear as downloaded in the devtool then that's it
Do you have more info about what you've just said that I can read? 

Thanks!

![image](https://user-images.githubusercontent.com/4474004/82735068-3eb7c780-9d1f-11ea-95ad-90292d458eae.png)

![image](https://user-images.githubusercontent.com/4474004/82735077-58f1a580-9d1f-11ea-91c7-c39ba97697cb.png)

**Comment by patrickhulce** [comment]
Ah! So not in the Lighthouse report but in viewing the raw trace, this is an artifact of [*simulated throttling*](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md#devtools-audits-panel-throttling). The default mode loads the page quickly and then simulates what it would have looked like on an actual phone. To get matching numbers you can use *applied* throttling in DevTools instead.

> This is actually something I ignore, I assumed that when they appear as downloaded in the devtool then that's it
Do you have more info about what you've just said that I can read?

https://web.dev/lcp/#when-is-largest-contentful-paint-reported is probably the most straightforward explanation if you haven't already read through that one.

**Comment by kuworking** [comment]
Thanks for the information!

So, after a while experimenting, you were right that animations don't seem to affect LCP

The major impact is for the images, and when running the `Performance` tab with throttled cpu then it is clear that the image is still not loaded (this was what mislead me at the beginning since the `View Trace` button didn't show the throttled connection)

I close the issue, many thanks!

**Comment by ciekawy** [comment]
hey @kuworking! 

could you elaborate more on "forever rasterization" - could it affect the lighthouse performance metrics and what are the options to deal with it?
I got here with pretty similar problem - lighthouse shows very bad performance and my impression was it's related to hero animations and I see very similar performance diagnostic profile with nothing else but rasterization potentially affecting the measured metric.

**Comment by kuworking** [comment]
@ciekawy I didn't go deeper there

I can say that in my hands having an image (no animation) without React (with 11ty) causes going from 100s to 90s

But with React (with Gatsby) scores are more vulnerable, if I'm between 70s and 80s when there are images involved I'm happy. This is an ongoing issue though

*If you're using Gatsby, there's an opened issue about this

**Comment by FractalHQ** [comment]
All of my Svelte websites with hero animations are showing 10s+ LCP.  Some don't even have images.  The actual load times are < 100ms, and this has been driving me bonkers.  If there is anything I can do to help get to the bottom of this, some advice would be greatly appreciated!
