### ISSUE TITLE
Report Score not matching the Calculator Score (webpagetest.org) - desktop

### ISSUE THREAD

**Issue by fvpDev** [GoogleChrome/lighthouse#10836]
#### Provide the steps to reproduce
1. Run LH via webpagetest.org on https://sanity-www-fenaw9fjm.now.sh/
  

#### What is the current behavior?
The score report and score calculator do not match.
Here are the results:
WPT Desktop Test: https://www.webpagetest.org/result/200523_SN_5c9583ca40eccaa61ef6bbc7392cc3fb/
LH Desktop Report: https://www.webpagetest.org/lighthouse.php?test=200523_SN_5c9583ca40eccaa61ef6bbc7392cc3fb&run=2

![lighthouse_6 0 0-report_score_not_matching_calculator_score](https://user-images.githubusercontent.com/10249425/82742641-b80ae680-9d2e-11ea-894b-4f255f548986.png)

Calculator: https://googlechrome.github.io/lighthouse/scorecalc/#first-contentful-paint=1114.902&speed-index=1839&largest-contentful-paint=1898.038&interactive=1851.684&total-blocking-time=17.261999999999944&cumulative-layout-shift=0.007962289589066526&first-cpu-idle=1851.684&first-meaningful-paint=1114.902&device=none&version=6.0.0

![lighthouse_6 0 0-report_score_not_matching_calculator_score-calc](https://user-images.githubusercontent.com/10249425/82742657-e25ca400-9d2e-11ea-996d-933b7ce0d822.png)

#### What is the expected behavior?
I should have a score displayed of 99 (according to score calculator)

#### Environment Information
* Affected Channels: WebPageTest (idk what they are using)
* Lighthouse version: 6.0.0
* Operating System: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

![lighthouse_6 0 0-report_score_not_matching_calculator_score-settings](https://user-images.githubusercontent.com/10249425/82742677-1e900480-9d2f-11ea-818e-285f95d1d14b.png)

**Related issues**

**Comment by paulirish** [comment]
@fvpDev thanks for filing. 

It's a known issue that the score calc doesn't support desktop yet.  https://github.com/paulirish/lh-scorecalc/pull/10

We'll be fixing this soon.

**Comment by fvpDev** [comment]
I should have mentioned that it was a desktop run in WPT...and should have included the link to the whole run...
WPT Test: https://www.webpagetest.org/result/200523_SN_5c9583ca40eccaa61ef6bbc7392cc3fb/

Just a confirmation for y'all: I had no problems with running a mobile test btw...here it is (running a mobile WPT Test ran a mobile lighthouse test):

WPT Test: https://www.webpagetest.org/result/200524_6M_73eab15be593686a20003c338e435cc0/
Report: https://www.webpagetest.org/lighthouse.php?test=200524_6M_73eab15be593686a20003c338e435cc0&run=3

![lighthouse_6 0 0-report_score_not_matching_calculator_score-mobile_report](https://user-images.githubusercontent.com/10249425/82769193-772fd200-9e01-11ea-87a5-fd520ed04428.png)


Calculator: https://googlechrome.github.io/lighthouse/scorecalc/#first-contentful-paint=765.172&speed-index=770&largest-contentful-paint=923.13&interactive=1026.675&total-blocking-time=184.87299999999993&cumulative-layout-shift=0&first-cpu-idle=1026.675&first-meaningful-paint=765.172&device=none&version=6.0.0

![lighthouse_6 0 0-report_score_not_matching_calculator_score-mobile_calc](https://user-images.githubusercontent.com/10249425/82769227-a21a2600-9e01-11ea-8e59-944481de6eaf.png)

Here are the settings:

![lighthouse_6 0 0-report_score_not_matching_calculator_score-mobile_settings](https://user-images.githubusercontent.com/10249425/82769246-af371500-9e01-11ea-9b88-403847f29aa5.png)

**Comment by paulirish** [comment]
@fvpDev thanks for the great bug report. There was indeed a problem with the LH configuration in WPT. It should be all fixed by https://github.com/WPO-Foundation/wptagent/pull/297 which landed a few days after you filed this issue.

For any new run on WPT, the scores should be correct and matching now. I just checked myself on WPT and they seem good. Can you verify?

**Comment by connorjclark** [comment]
Let us know if you see a mismatch, we think we fixed it.
