### ISSUE TITLE
"Lighthouse" View Trace and "Performance" tabs data are not connected

### ISSUE THREAD

**Issue by h3d0** [GoogleChrome/lighthouse#10842]
#### Provide the steps to reproduce

1. Run LH on any url using the default config:

![image](https://user-images.githubusercontent.com/7346327/82891288-254c9080-9f56-11ea-8e84-75d4428a9e13.png)

2. Get the result, for example:

![image](https://user-images.githubusercontent.com/7346327/82891335-385f6080-9f56-11ea-8328-61da6501e481.png)

3. Click the "View Trace":

![image](https://user-images.githubusercontent.com/7346327/82891357-4319f580-9f56-11ea-843d-6927c69a8d51.png)

4. Compare parameters
  
#### What is the current behavior?

"Lighthouse" shows "First Contentful Paint" as 0.8s:

![image](https://user-images.githubusercontent.com/7346327/82891621-b7ed2f80-9f56-11ea-98a4-f35728c14877.png)

while "Performance" as 195.4ms

![image](https://user-images.githubusercontent.com/7346327/82891640-bde31080-9f56-11ea-9506-b3e8d535d131.png)

#### What is the expected behavior?

"Lighthouse" tab and "Performance" tag (via "View Trace" clicked) are supposed to show the same data. For example, "First Contentful Paint".

#### Environment Information
* Affected Channels: Node, DevTools
* Lighthouse version: 5.7.1 (DevTools, Chrome 83), 6.0.0 (NPM)
* Chrome version: 83
* Node.js version: 12.6.3
* Operating System: Linux Ubuntu 20.10

#### Comments

The "Performance" and "Lighthouse" tabs seem to live their own lives:

Modifying "Application" affects "Performance" (does not affect "Lighthouse"):

![image](https://user-images.githubusercontent.com/7346327/82891809-0dc1d780-9f57-11ea-9cd1-bba789121af2.png)

Modifying "Network Condition" affects "Performance" (does not affect "Lighthouse"):

![image](https://user-images.githubusercontent.com/7346327/82891895-2d590000-9f57-11ea-8d61-b06346c3ed60.png)

The data shown after clicking Lighthouse > View Trace is completely different from the report:

![image](https://user-images.githubusercontent.com/7346327/82892556-56c65b80-9f58-11ea-8cb5-91866d0ef381.png)

Here the LCP timestamp is 435ms.

**Related issues**

**Comment by patrickhulce** [comment]
You are correct @h3d0 Lighthouse runs differently from Performance panel. Throttling is *simulated* by default (won't slow down the load or show up in the trace, see [throttling docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md)), storage is cleared before running for a cold load, and service worker settings are reset to test PWA install.

Everything I see here is WAI though the documentation for each item you see is spread throughout our docs rather than in a single location.

**Comment by h3d0** [comment]
Thank you for clarification.

In my case, turning off the _Simulated throttling_ option resolved the issue:
- I was able to jump into _View Trace_ and see what is going on.
- Forget about cache and SW options (since everything is cleared for me).

Unless I am missing something, there is no benefit in using _Simulated throttling_ while debuggin the app performance.

**Comment by patrickhulce** [comment]
> there is no benefit in using Simulated throttling while debuggin the app performance.

The benefit is that you do not need to wait for the page to actually load on a slow connection. It will load it quickly and then simulate the performance on a slower connection. For sites that have poor performance this can save ~20-40s. If your site is already very fast, there is not much benefit.
