### ISSUE TITLE
 [id] attributes on the page are not unique 

### ISSUE THREAD

**Issue by mataski** [GoogleChrome/lighthouse#10856]
### Provide the steps to reproduce
1. Run LH on https://www.worldcannabisinc.com/

#### What is the current behavior?
It says IDs on menu items are not unique, but they are.

![image](https://user-images.githubusercontent.com/62036912/83038789-0c230d00-a046-11ea-8fff-a5deb4ac59da.png)

#### What is the expected behavior?
To pass the test

#### Environment Information
* Affected Channels: using this Firefox addon https://addons.mozilla.org/en-US/firefox/addon/google-lighthouse/
* Lighthouse version: 5.6.0
* Chrome version: Using Firefox
* Node.js version: n/a
* Operating System: Ubuntu 19.04

**Comment by patrickhulce** [comment]
But they aren't... 😉 

![image](https://user-images.githubusercontent.com/2301202/83041675-5a182080-a006-11ea-9c9d-68af1b0aad72.png)

It only seems to affect the mobile version of this page if that helps debug.

**Comment by mataski** [comment]
Shouldn't it show the duplicates in the report?

**Comment by connorjclark** [comment]
#10396 :)

**Comment by mataski** [comment]
Thanks for response, the duplicates are generated by a third party module for Drupal.
