### ISSUE TITLE
False positive "Does not provide fallback content when JavaScript is not available" if url path="/services"

### ISSUE THREAD

**Issue by derykmarl** [GoogleChrome/lighthouse#10854]
#### Provide the steps to reproduce
1. Run LH on https://dev.leds.co.uk/services
 
#### What is the current behavior?
Fails PWA checks with "Does not provide fallback content when JavaScript is not available"

#### What is the expected behavior?
Check should pass, as the page does produce output with Javascript disabled.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.7.1
* Chrome version: 83.0.4103.61 (Official Build) (64-bit) (cohort: 83_61_Win)
* Node.js version: n/a
* Operating System: Windows 10

This appears to be a bug related to having "/services/" as the URL.  If I rename the exact same directory to /svcs/ temporarily, it passes.  Other pages underneath /services/ also pass.

The same issue happens in Edge with Lighthouse 5.7.0.

**Comment by patrickhulce** [comment]
Thanks for filing @derykmarl! Is this an internal only URL? I'm not able to visit it from the US.

![image](https://user-images.githubusercontent.com/2301202/83034305-b88cd100-9ffd-11ea-9d7e-8712660e1f9d.png)

**Comment by derykmarl** [comment]
Sorry about that!  It's a development site and I just made a faulty DNS change which has gone through quicker than they normally do.

It's reverted now but if it's not propagated yet it'll need either a temporary hosts file edit of
`139.162.236.75 dev.leds.co.uk`
or I give this a nudge in 24 hours...

**Comment by patrickhulce** [comment]
Thanks @derykmarl! I can reproduce this now we'll have to look into it.

**Comment by derykmarl** [comment]
Right I've just had the same thing come up on /news/ so I don't think it's to do with the word "services".  I can't fathom why my test of renaming to "svcs" worked.

It's a gatsby site using gatsby-plugin-offline for the service worker and I have been able to produce a blank page by disabling javascript and refreshing the page.  But if I go into incognito mode, disable javascript and **then** open up the site, nothing produces a blank page. 

If I had to guess, I'd say it's an issue related to Gatsby's tendency not to care whether there's a trailing slash in the URL or not (news and services are both structured as directories, so that's the obvious pattern) and the service worker is confusing itself in some way.  As it's not present in incognito, neither is the issue.  I did notice when using Lighthouse that it added a trailing slash to my URL during its tests as I had to tweak the navbar to take this into account.

Unfortunately I'm *very* new to this way of building websites so thus far I'm only working off a hunch and an understanding of service workers that is rudimentary at best, and hoping I'm not wasting anyone's time.

**Comment by derykmarl** [comment]
I think it may be a manifestation of this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=656516
in relation to Gatsby's offline worker: https://github.com/gatsbyjs/gatsby/issues/9166

I noticed the same thing.  If Javascript is disabled via chrome://settings then everything works fine.  But if it's disabled via the dev console (sources, ctrl-shift-p, disable javascript) then there are blank pages unless the cache is bypassed with shift-refresh.

Lighthouse normally appears to behave as if Javascript was disabled via chrome://settings (correctly) but if there's a trailing slash then it's behaving as if it was disabled via the dev console.

**Comment by patrickhulce** [comment]
Ah great find @derykmarl! This is going to be really tricky for us to fix in Lighthouse then. We might be able to work around that Chromium bug by bypassing the service worker for network in the redirect pass.

**Comment by paulirish** [comment]
We plan on removing this audit, so unfortunately we wont be fixing this.
