### ISSUE TITLE
Extension Error: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by DanGthatRokGallery** [GoogleChrome/lighthouse#1085]
**Lighthouse Version**: 1.2.2
**Chrome Version**: 54.0.2840.99
**Error Message**: Cannot read property 'message' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'message' of undefined
    at collectUsage.then.e (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:4444:23)```

**Comment by ebidel** [comment]
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1082
