### ISSUE TITLE
Enable smoke tests for Layout Shift Elements audit and InspectorIssues gatherer

### ISSUE THREAD

**Issue by Beytoven** [GoogleChrome/lighthouse#10866]
Both of these smoke tests are currently disabled as they depend on features not available in the current stable Chrome version. Creating this issue as a reminder to enable them once the features that the smoke tests depend on are available.

**Comment by connorjclark** [comment]
it actually should be in m83 I think. the problem is that appveyor seems to be using an old chromium.

**Comment by Beytoven** [comment]
Done in #10976.
