### ISSUE TITLE
Define custom thresholds for category score in report

### ISSUE THREAD

**Issue by mashruravi** [GoogleChrome/lighthouse#10860]
**Feature request summary**

I see from the documentation that the color of the category score in the HTML report is calculated based on these thresholds:
* 0 to 44 (poor): Red
* 45 to 74 (average): Orange
* 75 to 100 (good): Green

It would be nice if there was a way to define a custom thresholds at which the HTML report would show the category score as good/average/poor.

Also, it would be nice to define the threshold when an audit is considered passed/failed by the HTML report.

**What is the motivation or use case for changing this?**
I am using custom audits that I want to declare as "passed" only if the score is 100, and "failed" otherwise.

Currently, I can achieve this by specifying a score of 0/1 from the custom audit, but then I lose the value of the actual score that I want to see on the HTML report.

**How is this beneficial to Lighthouse?**

Custom audits can define their own thresholds for when the audit is considered passed/failed, and also thresholds for when the score is good/average/poor.

**Comment by patrickhulce** [comment]
Thanks for filing @mashruravi! Would you mind linking where you saw that documentation so we can fix it? It is incorrect. The score color coding goes `0-49`, `50-89`, `90-100` (see [perf scoring docs](https://web.dev/performance-scoring/#color-coding)).

As for the feature request, I think it's unlikely we will offer this functionality as we want scores to be interpreted consistently. We have similar cases to what you describe in Lighthouse core and there we just ensure that `1` is used for passing and reinterpret `0-0.9` as the linear scale of all other scores, i.e. scores of `0.9-0.99` are impossible to achieve.

**Comment by mashruravi** [comment]
Thanks for the info @patrickhulce! I got the thresholds from the [Lighthouse v2 Scoring Guide](https://developers.google.com/web/tools/lighthouse/scoring) and assumed they would be the same for custom audits.

I understand the color coding isn't configurable so that they can be interpreted consistently.

However, is there some way to achieve a custom value at which we say an audit has passed or failed in the HTML report?

The reason this is important is as a project evolves, we may have changing KPIs. e.g., when a project just starts we may say a score of >60 is okay for an audit to pass. And after a few months, when the project is more mature, we expect a score of >80 for the audit to pass.

**Comment by mashruravi** [comment]
> Ah v2 was many years ago we're on v6 now :)

Oh boy, looks like I travelled back in time there :)

> You're absolutely right to want to do this here, and our answer to this is using [assertions in CI](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#assert). You can assert failure thresholds independent of the Lighthouse report styling that your team should be meeting.
> 
> If you really want this reflected in the HTML report though, then changing the audit definition to manipulate the score is the only option you really have.

Cool, makes sense. Thanks :)
