### ISSUE TITLE
High CLS But No Element Found Under Diagnostics

### ISSUE THREAD

**Issue by ScottTravisHartley** [GoogleChrome/lighthouse#10862]
I took my website through Page Speed Insights ran it got a high CLS rating of .366, I went under diagnostics under the avoid large layout shifts tooltip and was given "no elements found". 

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.sertmedia.com%2F&tab=mobile

#### Provide the steps to reproduce
1. Run LH on https://www.sertmedia.com/
  
#### What is the current behavior?
Currently, I am given a high  CLS without much feedback as to what is the root cause of it and no elements are provided under the diagnostics tab. 

#### What is the expected behavior?
I expect the Diagnostics tab to provide me with an element or really anything to go off of. 

**Related issues**
I also ran the test locally using the latest version of Chrome Canary and I am getting a considerably lower number consistently instead of a CLS of .366 I am getting .042 on the mobile test. 

Chrome Canary was being run in Incognito Mode for the test.

**Comment by patrickhulce** [comment]
Thanks for filing @ScottTravisHartley! I'm not sure what's going on with PSI but these are the elements I see locally

![image](https://user-images.githubusercontent.com/2301202/83172859-d3cf0d80-a0dd-11ea-9cef-3034715205aa.png)

Do you not receive any elements found locally either?

**Comment by ScottTravisHartley** [comment]
I did not on my Canary runs I will try it again here in a few minutes to see if I can figure out why I wasn't getting anything on it.

**Comment by ScottTravisHartley** [comment]
I fixed this  by reinstalling Chrome Canary I tried running a few retests wouldn't spit anything out so I uninstalled and reinstalled the browser and it worked without a hitch and listed the 5 items.

**Comment by connorjclark** [comment]
re: canary devtools, perhaps the previous installation of Canary had a pending update? If it was old enough (A few weeks i think ...) it'd be missing required features for LH to grab the CLS element (@Beytoven can correct me if I'm misremembering)

I'll dig into the PSI issue.

**Comment by ScottTravisHartley** [comment]
I want to follow up and it looks like the PSI team has patches this. 

I am still getting a higher CLS on average when testing from psi instead of lighthouse but the diagnostics information is atleast showing.

**Comment by jazyan** [comment]
@ScottTravisHartley you're correct, a fix was rolled out last Thursday. I'll close this for now, but feel free to reopen if needed!
