### ISSUE TITLE
'Bypass for network' breaks the offline-start-url audit

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#10865]
repro:

* open https://airhorner.com/ and open devtools. 
* run LH / PWA. '
   - confirm `start_url responds with a 200 when offline` is passing as it should.
* now go to Application panel → Service Workers and check the box for 'bypass for network'
* rerun LH / PWA.
  - now note that `start_url does not respond with a 200 when offline` is FAILING

![image](https://user-images.githubusercontent.com/39191/83169958-a4fa6c80-a0c8-11ea-8de4-742f8bfe562a.png)

@michaelsolati found this.

**Comment by shervintravel** [comment]
### **DanDeveloper** ###
**[Click Here](https://dandeveloper.carrd.co)**

**Comment by patrickhulce** [comment]
Offline start URL audit has been removed. This is Chromium's realm now.
