### ISSUE TITLE
Heading order test

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#10861]
**Summary**
I have 2 url:
https://intersindicalrm.org/tratado-de-la-carta-de-la-energia/
This fail the heading order
https://intersindicalrm.org/el-engano-del-pacto-para-la-reactivacion/
but this not
The headings structure in both url are
1 H1
1 H2
2 or more H3 
in these order.
Why the test is bypassed by one url but not the other?
Tested in chrome Versión 85.0.4158.1 (Build oficial) canary (64 bits)

**Comment by patrickhulce** [comment]
https://intersindicalrm.org/el-engano-del-pacto-para-la-reactivacion/

has an extra `h2` higher up in the tree compared to the other URL

![image](https://user-images.githubusercontent.com/2301202/83161741-73849f80-a0ce-11ea-93a4-f5b248354937.png)

vs.
![image](https://user-images.githubusercontent.com/2301202/83161772-7da69e00-a0ce-11ea-96a5-ccd9f71d6b38.png)

My guess is that the first h2 is not higher in the tree, but I'm not sure. 

This rule comes from [axe-core](https://github.com/dequelabs/axe-core). If you have believe there is a bug in the implementation, I'm sure they'd appreciate an issue on that repo with an example.

**Comment by Lofesa** [comment]
My fault.
The test fail when in mobile and not when in desktop mode, in both url.
For test purposes I have changed the 2nd h2 to h3 too.

**Comment by patrickhulce** [comment]
Ah OK glad you figured it out @Lofesa!
