### ISSUE TITLE
Framehole: LCP ignores iframes

### ISSUE THREAD

**Issue by natedev** [GoogleChrome/lighthouse#10874]
#### Provide the steps to reproduce
1. Run `lighthouse https://webvitalsfail.b-cdn.net/ --view`
2. Run `lighthouse https://webvitalsfail.b-cdn.net/image-100.html --view`
  

#### What is the current behavior?
The second URL has a substantially higher LH score than the first URL. In our testing it was a performance score of 60 versus 99. The largest contributor to this is that the LCP calculation for the second URL ignores the iframe element and instead is now calculated for the `<h1>` text.
**https://webvitalsfail.b-cdn.net/**
![https://webvitalsfail.b-cdn.net/](https://user-images.githubusercontent.com/886657/83288788-f6325b00-a1b1-11ea-8b6b-6fbd63e582b1.png) 
**https://webvitalsfail.b-cdn.net/image-100.html**
![https://webvitalsfail.b-cdn.net/image-100.html](https://user-images.githubusercontent.com/886657/83288831-03e7e080-a1b2-11ea-915d-8cffc4b54880.png)

#### What is the expected behavior?
The LCP should be reported based on the LCP of the embedded iframe if that iframe is the largest element in the original URL. Otherwise this exempts embedded elements from being reported as impacting LCP performance. It incentives the usage of embeds as they become _free_ when it comes to performance.

If there are limitations which prevent this aggregated calculation for LCP, then Lighthouse should error out when the iframe would be the largest element with an explanation that accurate results cannot be calculated at this time. Showing a wildly inaccurate score when there is a known limitation does not seem like the correct route to go especially with heavy scoring weight that LCP has in total score.

For an extreme example, run:
```
lighthouse https://webvitalsfail.b-cdn.net/anything-100.html --view
```
On our runs this achieves a 100 performance score by simply embedding the initial page from above inside a full-screen iframe.

We provide additional examples in this deep dive: https://buzz.swarmify.com/how-to-get-a-100-score-on-lighthouse-pagespeed-in-one-easy-step/

#### Environment Information
* Affected Channels: CLI, Pagespeed Insights
* Lighthouse version: 6.0.0
* Chrome version: lighthouse cli
* Node.js version: 12.10.0
* Operating System: 10.15.5

**Comment by patrickhulce** [comment]
Thanks for filing @natedev nice work on the investigation :)

The root cause is much broader than LCP and revolves around the spec of all these metrics. We've decided to track adding "Page Performance" as an exploration topic discussed in https://github.com/GoogleChrome/lighthouse/issues/11311#issuecomment-680060415 but no immediate plans to address this.
