### ISSUE TITLE
web.dev consistently errors on Network.getResponseBody for main content

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#10876]
- run `node lighthouse-cli/index.js https://web.dev --only-categories best-practices --view`
- get `Properly defines charset – Error!`

(also happens in DevTools and PSI)

<img width="695" alt="lighthouse error" src="https://user-images.githubusercontent.com/316891/83295066-647c1b00-a1bc-11ea-8b02-75383653f580.png">

[Example report](https://googlechrome.github.io/lighthouse/viewer/?gist=3fbaa5e4dc0e864c3e25b7ca8aeeb583)

The error is

`Required MainDocumentContent gatherer encountered an error: Protocol error (Network.getResponseBody): No resource with given identifier found`

and occurs [here in `driver`](https://github.com/GoogleChrome/lighthouse/blob/9035d4ffed95a9ab652bbacfb647341009fa897a/lighthouse-core/gather/driver.js#L1184) when called from [`main-document-content`](https://github.com/GoogleChrome/lighthouse/blob/9035d4ffed95a9ab652bbacfb647341009fa897a/lighthouse-core/gather/gatherers/main-document-content.js).

It seems unusual that the main document content wouldn't be available for the backend. @robdodson does mention some unusual things done with the service worker and "an app shell that pulls in an index.json of the page content when you go to other pages. We essentially replace main content area with this new content" that could be causing trouble (maybe the request really didn't have any content?).

**Comment by rpong** [comment]
We are experiencing the same issue with the lighthouse npm package. leaving a comment to follow this thread.

**Comment by robdodson** [comment]
btw I noticed that our service worker was being too aggressive (https://github.com/GoogleChrome/web.dev/issues/3089). @brendankenny I tried to use canary to audit our staging server (https://web-dev-staging.appspot.com/) since it doesn't install the sw, but got an error
![image](https://user-images.githubusercontent.com/1066253/83577617-87bf0700-a4e9-11ea-8df8-09eddb306192.png)

**Comment by connorjclark** [comment]
@robdodson https://github.com/GoogleChrome/lighthouse/issues/10883

should get fixed for next chromium canary

**Comment by Vadorequest** [comment]
Running into this too for the first time today. I got scored 0 for "Best Practices" when analyzing this website: https://nrn-v2-mst-aptd-at-lcz-sty-c1-ah8bmgx1e.vercel.app/en

LH Report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnrn-v2-mst-aptd-at-lcz-sty-c1-ah8bmgx1e.vercel.app%2Fen#best-practices

![image](https://user-images.githubusercontent.com/3807458/88483193-92849e00-cf66-11ea-9bed-2172b8bf9eb7.png)


![image](https://user-images.githubusercontent.com/3807458/88483114-0a05fd80-cf66-11ea-8f46-d4e025be4bf7.png)

**Comment by thepassle** [comment]
We're also running into this problem at modern-web.dev:
![image](https://user-images.githubusercontent.com/17054057/91189315-9553e980-e6f2-11ea-9431-38cf9c50cdb2.png)

It seems like disabling the service worker 'fixes' the problem. We dont do anything fancy with our service worker — we either load an index.html either from network or from cache, we dont do any transformations on the html or anything like that. I really fail to see the connection between the service worker and defining a charset in the html ☹️

**Comment by patrickhulce** [comment]
> I really fail to see the connection between the service worker and defining a charset in the html ☹️

Certain service workers mean that Lighthouse cannot fetch the HTML document to check for a charset. `Error!` means a Lighthouse bug, not something the page needs to fix (see https://github.com/GoogleChrome/lighthouse/issues/9968)

**Comment by thepassle** [comment]
We debugged a little bit more, we use a code snippet to reload the page when a new service worker has taken over:

```js
if("serviceWorker"in navigator){let e;navigator.serviceWorker.addEventListener("controllerchange",()=>{e||(e=!0,window.location.reload())})}
```

❌ **With** that piece of code:

<img width="1552" alt="Screenshot 2020-08-28 at 12 55 47" src="https://user-images.githubusercontent.com/17054057/91554328-35965200-e92f-11ea-9c54-17d53e65a59a.png">

✅ **Without** that piece of code:

<img width="1511" alt="Screenshot 2020-08-28 at 13 02 51" src="https://user-images.githubusercontent.com/17054057/91554353-3d55f680-e92f-11ea-9d20-4388520d4b38.png">

It seems that the reload is causing the best practices to error, hope that helps 🙂

**Comment by patrickhulce** [comment]
Ah thanks @thepassle that helps a lot! I *think* this is happening because Chrome might only keep the network resources from the current page load in the memory cache which is what Lighthouse relies on to get the response body of the root document. We can do a bit more digging but this is a great head start 👍 

related #8984  #11027

**Comment by robdodson** [comment]
We use a similar snippet on web.dev

**Comment by frankii91** [comment]
I have the same problem, it's not only visible on my website. I have a more extensive worker service. Which is only a transitional version anyway. Can anyone help me solve the coding problem or improve the worker code? My website https://i-meble.eu

**Comment by adamraine** [comment]
@frankii91 The issue is not reproducible on that site

**Comment by frankii91** [comment]
Strange, the problem occurs all the time, I use the plugin in Chrome

![Zrzut ekranu 2023-09-29 212823](https://github.com/GoogleChrome/lighthouse/assets/14099566/f913400b-2114-4a2e-9191-30e2aba47d5e)

**Comment by adamraine** [comment]
The fix appears in version 11.1.0, PSI and the Chrome extension still use 11.0.0

**Comment by tunetheweb** [comment]
[@adamraine got another report for this site: https://leverx.com/

Testing it locally in Chrome (on 11.3.0) the error still shows. Any ideas why?

**Comment by adamraine** [comment]
@tunetheweb looks like a different issue that is reproducible without Lighthouse. I'll open a new issue since this one is pretty old.
