### ISSUE TITLE
Incorrect hyperlink on help docs

### ISSUE THREAD

**Issue by CymruUSA** [GoogleChrome/lighthouse#10875]
Using the lighthouse extension 100.0.0.0 (Lighthouse 6.0.0) on Version 83.0.4103.61 (Official Build) (64-bit) and W10 and after running a lighthouse report, the "Learn More" link associated with "Displays images with inappropriate size" directs to a 404. The WebDev link is https://web.dev/image-size-responsive/?utm_source=lighthouse&utm_medium=lr

Thank you.

**Comment by patrickhulce** [comment]
Thanks for filing @CymruUSA ! See https://github.com/GoogleChrome/lighthouse/issues/10839 for explanations of the fixes in progress :)
