### ISSUE TITLE
How is it possible to get better performances with React?

### ISSUE THREAD

**Issue by CYB3RL1F3** [GoogleChrome/lighthouse#10882]
Hello,
I meet a problem that I don't have any clue and solutions.
I'm actually finishing an application with React, MobX, Mapbox, audio, and Webpack.
I did all the necessary to have it performing : 
* Use lazy loading for all my major components (routes + some heavy ones like mapbox)
* Prefetch all calls
* Using memo
* Use functional components with hooks
* Use PureComponent when functional components not possible (and it's really few)
* Split chunks : all my node_modules are asyncally loaded on demand
* Clean all dependencies, change some libs for lighter
* Use Gzip compression
* Use http2 with spdy
* Minify and mangling with terser
* Using CDN for ressources
* Using CSS for animations
* Did a performing clean code with not unreachable statements and optimized architecture, optimized modules

After those, I checked out other ways to improve perfs, but found nothing better than what is written here, and did all of this: https://medium.com/better-programming/https-medium-com-mayank-gupta-6-88-21-performance-optimizations-techniques-for-react-d15fa52c2349

Despite this, I'm having a scoring with only 65%!
First contentful paint is loaded in 1.1s
First meaningful paint: 1.2s
Speed index: 2.8s

But I'm harassed by the "time to interactive", stuck at 13.5s!!
Script evaluation is evaluated to 2,393 ms but the main script is light (my main bundle is 604ko, I tried to split it but seems not working, and the content is quite consequent, the rest is between 10 and 350ko for the biggest dependency that is react-dom. Mapbox is loaded separately).

Do you have a clue how I could make my main bundle lighter and improve my script evaluation, or maybe check whether the result of lighthouse is realistic according the fact that's a multimedia application with videos, audio, transitions, etc...?

Thanks a lot!

**Comment by patrickhulce** [comment]
Thanks for filing @CYB3RL1F3! We don't really use this forum to give 1:1 performance advice though.

I will say a few general principles though:

1. Follow all the opportunities in the report. (Sounds like you may have already tried to do this if you're filing it here?)
2. It sounds like you're loading *a lot* of JavaScript.

> (my main bundle is 604ko, I tried to split it but seems not working, and the content is quite consequent, the rest is between 10 and 350ko for the biggest dependency that is react-dom. Mapbox is loaded separately)

That's already at least 1MB of JavaScript and if those are compressed numbers it's more like several MB of JavaScript. When we talk about code splitting, the goal isn't to just split up one file into smaller files while still using all of it, we aim to reduce the amount of code necessary to render each view (by splitting out unused code for view A into a separate file only loaded for view B).

If you're looking for open source examples of performant yet complex apps made with a similar stack, checkout [Squoosh](https://squoosh.app/) (41 KiB of script), [Proxx](https://proxx.app/) (40 KiB of script), and [LHCI](https://lhci-canary.herokuapp.com/app/projects) (30KiB of script).
