### ISSUE TITLE
I want to know the relationship between lighthouse and httparchive.

### ISSUE THREAD

**Issue by hongsy12** [GoogleChrome/lighthouse#10889]
**Summary**

Is the result of the web page I checked collected in Chrome(google)?

Or Does the lighthouse provide the report results to httparchive ?

I want to know the relationship between lighthouse and httparchive.

**Comment by patrickhulce** [comment]
HTTPArchive runs the Lighthouse CLI on the URLs in its dataset every month. 

The data from reports you collect locally using the CLI or DevTools is not reported or sent to Google, HTTPArchive, or anywhere else.

**Comment by hongsy12** [comment]
> HTTPArchive runs the Lighthouse CLI on the URLs in its dataset every month.
> 
> The data from reports you collect locally using the CLI or DevTools is not reported or sent to Google, HTTPArchive, or anywhere else.

Thank you @patrickhulce  for your quick response! And i have one more question. 
<img width="375" alt="performance" src="https://user-images.githubusercontent.com/66245137/83466383-e8325200-a4b1-11ea-97e5-7bbb237aa751.PNG">

When i see "web.dev" site, Lighthouse performance aubits is based on data from the HTTP Archive. 

In addition to performance, does accessibility/SEO/pwa compare with httparachive data?

**Comment by connorjclark** [comment]
> When i see "web.dev" site, Lighthouse performance aubits is based on data from the HTTP Archive.

To be clear, just the scoring curve is derived from all of HTTPArchive. Not based on a particular origin, but the entire web.

> In addition to performance, does Accessibility/Best Practices/SEO/PWA compare with httparachive data?

No.

**Comment by hongsy12** [comment]
> > "web.dev"사이트를 볼 때 Lighthouse 성능 지원은 HTTP Archive의 데이터를 기반으로합니다.
> 
> 분명히, 점수 매기기 곡선은 모든 HTTPArchive에서 파생됩니다. 특정 출처가 아니라 전체 웹을 기반으로합니다.
> 
> > 성능 외에도 접근성 / 모범 사례 / SEO / PWA는 httparachive 데이터와 비교됩니까?
> 
> 아니.

Thank you @connorjclark
