### ISSUE TITLE
LCP element and ALLS diagnostics give an Error though working on web.dev/measure

### ISSUE THREAD

**Issue by exkalation** [GoogleChrome/lighthouse#10893]
#### Provide the steps to reproduce
1. Run LH on https://web.dev/optimize-cls/ (without any flags, but also with ```--preset perf``` as well as headless)

#### What is the current behavior?

The diagnostics for
* Largest Contentful Paint element
* Avoid large layout shifts

both show "Error!" as can be seen in this screenshot:

![lighthouse_lcp-alls_web dev-optimize-cls_error-local-cli_2020-06-01](https://user-images.githubusercontent.com/233206/83450375-6ca2b780-a455-11ea-9a42-6f6c36258374.png)

There are some errors/warnings on stdout that seem to be related:
```  status Gathering: ResponseCompression +42ms
  status Gathering: TagsBlockingFirstPaint +6ms
  status Gathering: TraceElements +4ms
  method <= browser ERR:error DOM.resolveNode  +33ms
  status Disconnecting from browser... +56ms
  status Analyzing and running audits... +13ms
  status Auditing: First Contentful Paint +6ms
  ...
  status Auditing: Minimize third-party usage +1ms
  status Auditing: Largest Contentful Paint element +98ms
  Runner:warn TraceElements gatherer, required by audit largest-contentful-paint-element, encountered an error: Protocol error (DOM.resolveNode): Node with given id does not belong to the document +1ms
  status Auditing: Avoid large layout shifts +0ms
  Runner:warn TraceElements gatherer, required by audit layout-shift-elements, encountered an error: Protocol error (DOM.resolveNode): Node with given id does not belong to the document +1ms
  status Auditing: Uses efficient cache policy on static assets +1ms
  status Auditing: Avoids enormous network payloads +2ms
```

#### What is the expected behavior?
* "Largest Contentful Paint element" should say "1 element found", giving the respective HTML
* "Avoid large layout shifts" should say "No elements found"

As can both be seen in this screenshot taken from a report generated on https://web.dev/optimize-cls/, where this seems to work despite this issue:

![lighthouse_lcp-alls_web dev-optimize-cls_ok-on-web dev-measure_2020-06-01](https://user-images.githubusercontent.com/233206/83450435-89d78600-a455-11ea-8431-7166b23eee4b.png)

Full web.dev report available here:
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fweb.dev%2Foptimize-cls%2F

#### Environment Information
* Affected Channels: CLI (PowerShell, as well as on WSL1)
* Lighthouse version: 6.0.0
* Chrome version: 83.0.4103.61 (Official Build) (64-bit) (cohort: Stable)
* Node.js version: 12.17.0
* Operating System: Windows 10, Build 1909

**Related issues**
Potentially https://github.com/GoogleChrome/lighthouse/issues/10869

**Comment by patrickhulce** [comment]
Thanks for filing @exkalation! #10873 is related and #10877 fixes this.

**Comment by exkalation** [comment]
Thank you @patrickhulce for your quick response. Can you confirm whether this issue has an impact on any measured metrics?

**Comment by patrickhulce** [comment]
Confirmed this issue has no impact on the performance score or the metric values themselves, it just makes it harder to debug why they are what they are :)

**Comment by exkalation** [comment]
Very good, thank you very much!
