### ISSUE TITLE
Differents LCP timings in PSI/Web.dev vs Dev-Tools

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#10898]
**Summary**
Maybe is a dumb question, But...
I found a 400-600ms increase in PSI/Web.dev vs LH in Chrome Dev-Tools
Take this url https://intersindicalrm.org/spublicos/mal-ambiente-en-medio-ambiente/
In PSI/web.dev the LCP time is consistently between runs measured as 2.1ms but in chrome canary is consistently measured as 1.6ms, in this case the diff is 500ms and it persist between runs.
In other url´s the diff are 400ms or 600ms and are persistens between runs.
PSI/web,dev add some time to LCP that dev-tools not?
Is this diff in the normal range for variability?
When I run Performance throttled to Fast 3g and 4x slow down I get the same times that LH does.

Chorme 85.0.4162.2 (Build oficial) canary (64 bits)

P.S: I have tried it on WPT and the LCP timming is more like the Chrome DT than the PSI/web.dev

**Comment by patrickhulce** [comment]
A difference of ~0.5s is well within the realm of expected variability for different environments. See the referenced materials in [the variability docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md), for more information.
