### ISSUE TITLE
The results of Lighthouse's audits do not match data from performance analysis

### ISSUE THREAD

**Issue by hugonteifeh** [GoogleChrome/lighthouse#10890]
Ever since I've updated the version of chrome from 79 to 83.0.4103.61 I've noticed a drastic decrease in the scores. One thing that particularly caught my attention is that the time for First Contentful Paint has gotten way longer than before although it's the same code and content on the page. Last time I ran Lighthouse it showed **3.5 s** for **First Contentful Paint**, clicking on `view trace`, I see that under the timings section, the FCP marker has the timestamp  **126.6 ms**. I don't get why I get such a mismatch? What am I missing?

**Comment by patrickhulce** [comment]
tl;dr - Simulated throttling.

See [FAQs](https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me) and the [throttling docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).

From 5.x to 6.0 several bugs in FCP were fixed where FCP was being estimated incorrectly. It affected ~9% of pages so your page might be one of them.
