### ISSUE TITLE
CLS increased when 1 px gif replace with image inside presized block

### ISSUE THREAD

**Issue by User756675678** [GoogleChrome/lighthouse#10896]
#### Provide the steps to reproduce
1. Run LH on https://output.jsbin.com/foyajoqaha/1

```
  <div style="height: 400px">
    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" 
        id="img" />    
  </div>
  <script>
  	setTimeout(function() {
	    document.getElementById('img').src = 'http://jsforcats.com/images/yarnify.png';
	}, 100);
  </script>
  <p>some other content</p>
```
Image height is 400 px;
  
#### What is the current behavior?
CLS increased and not zero (0.001).

#### What is the expected behavior?
CLS is zero because no actual shift happens.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 6.0.0
* Chrome version: Canary 85.0.4161.0 32-bit
* Node.js version:
* Operating System:

Also if I left src not set, CLS is not increased, but it is bad solution.
https://output.jsbin.com/lolirexivo/

In real code image wrapped with link with specified width and height. Image can not be more from link. But it can be different aspect ratio. In any case it is cause CLS metric increase, but for user no any issue present here. Nor layout shift, nor mis-click.
I think LH must understand that while calculate CLS metric.

**Comment by patrickhulce** [comment]
Thanks for filing @User756675678 ! I can reproduce this but it is flaky and I see a CLS of .005 when it is non-zero (the JSbin has expired, so I rehosted on [glitch](https://melodic-class.glitch.me/cls.html)). I too am confused why there would be any layout shift. What is extra interesting is that if I replace the 1x1 GIF with a 100x100 JPEG, the layout shift goes away (CLS back to 0). These layout shifts come straight from Chrome, so it requires an upstream fix. I'm not sure what's going on.

**Comment by patrickhulce** [comment]
Wait, I have figured this out and CLS is working as intended :)

The fact that the GIF is 1x1 means it is not displayed at the top left corner of the div. It's offsetTop is 21. When an image larger than the `line-height` loads in, it shifts up to have offsetTop 8.
![image](https://user-images.githubusercontent.com/2301202/83541983-f7200100-a4bf-11ea-9546-cb9f2943cb09.png)
![image](https://user-images.githubusercontent.com/2301202/83542016-030bc300-a4c0-11ea-98bb-e10f9978d5ed.png)


This also explains why the problem goes away when I used a 100x100 JPEG instead. If you set an explicit height or position on the 1x1 GIF, the layout shift goes away.

**Comment by User756675678** [comment]
Okey. What if outer is not a div but `A` tag? How it impact user experience? How user can "click on wrong" (reason of introduce CLS)?

**Comment by User756675678** [comment]
This metric not self existence thing. CLS targeted to prevent miss click user, right?
So what is miss cliked with link?
Even with div - what miss clicked here? Someone want click on 1px gif and miss? Sounds as completely nonsense.
What point CLS in this case?

**Comment by patrickhulce** [comment]
It's not just missed clicks but shifting content, period. Have you never been trying to read an article and the text shifts out from under you? It's frustrating.

Either way, I agree that a 1x1 shifting pixel is not a big deal at all, who cares. The CLS metric also agrees with you. 0.005 is still a perfect score. There are legitimate concerns with CLS (see #10873) but this is not one of them.

**Comment by User756675678** [comment]
What shift content? You not notice explicit set height of parent block?
No content shifted. Or 1px shifted is too content?

How this related to your example with shifted text? What similar?
It is there 0.005. When you have one image. I have 144 lazy loaded images with reserved space on parent block. now say me what about 0.005 * 144 = 0.72 CLS - it is small? Perfect score? Maybe period?

**Comment by User756675678** [comment]
Of course I can use `img` without `src`. If Google want make web more worst. But I think reason add this metrics make web better. Not make a bunch of hacks for proper work this artificial metrics, nothing more.

**Comment by patrickhulce** [comment]
> No content shifted. 

This statement is not true. The placeholder image did shift. The fact that it's a transparent GIF is not captured by the metric. All metrics have limitations, but if this were anything other than a transparent GIF it would have a user impact that is exactly what CLS is attempting to measure.

> Of course I can use img without src

This is not the suggested action. It's a fairly established best practice to ensure all images have fixed dimensions. In fact we intend there to be a Lighthouse audit for it soon. If the images had fixed dimensions, instead of only their containers, then this wouldn't be an issue.

> I have 144 lazy loaded images with reserved space on parent block 0.005 * 144 = 0.72 CLS

Only the viewport-visible images should be affecting CLS. All 144 of these images are above-the-fold primary content? If not, then there's something else going on.

**Comment by User756675678** [comment]
Shift of one pixel really not important for user. Even if it is not a transparent.

> All 144 of these images are above-the-fold primary content? 
No. It is loaded when user scroll. So shift again and again.
Even if LH collect metrics only during page load it looks no good.

For example 
case 1: we use transparent gif.
case 2: we no set src at all.
User: no any difference.
LH: case 1 produce some CLS > 0, case 2 produce CLS = 0.
Web standards: case 1 - not violated, case 2 - violated.
What need choose for satisfy Google req for fast pages? Of course case 2. Because CLS can be measured  at edge.
What conclusion? In this case violate web standards make Google happy.

Also real case on FHD monitor include above fold around 10 or 15 such images. 0.005*15 = 0.075 3/4 of allowed 0.1 for fast pages by Google report.
