### ISSUE TITLE
LH warns of "Warnings: A preload <link> was found for [...]" incorrectly, when using crossorigin="anonymous"

### ISSUE THREAD

**Issue by Vadorequest** [GoogleChrome/lighthouse#10892]
#### Provide the steps to reproduce
1. Run LH on https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-izza69ujx.now.sh/fr

LH report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnrn-v2-mst-aptd-gcms-lcz-sty-c1-izza69ujx.now.sh%2Ffr
  
Using the following code at :

```
      {/* Perf optimisation (preload normal and bold fonts because they're the most used) - See https://web.dev/uses-rel-preload*/}
      <link rel="preload" as="style" href={'/static/fonts/NeuzeitGrotesk/font.css'} crossOrigin="anonymous" />
      <link rel="preload" as="font" href={'/static/fonts/NeuzeitGrotesk/NeuzeitGrotesk-bold.woff'} type="font/woff" crossOrigin="anonymous" />
      <link rel="preload" as="font" href={'/static/fonts/NeuzeitGrotesk/NeuzeitGrotesk-bold.woff2'} type="font/woff2" crossOrigin="anonymous" />
      <link rel="preload" as="font" href={'/static/fonts/NeuzeitGrotesk/NeuzeitGrotesk-black.woff'} type="font/woff" crossOrigin="anonymous" />
      <link rel="preload" as="font" href={'/static/fonts/NeuzeitGrotesk/NeuzeitGrotesk-black.woff2'} type="font/woff2" crossOrigin="anonymous" />
```

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/3807458/83442049-d1571580-a447-11ea-8271-22c6777f5fec.png)

> Warnings: A preload <link> was found for "https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-izza69ujx.now.sh/static/fonts/NeuzeitGrotesk/font.css" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

#### What is the expected behavior?

It shouldn't throw such warning, the font is using `crossorigin="anonymous"`, the [link](https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-izza69ujx.now.sh/static/fonts/NeuzeitGrotesk/font.css) is valid.

Everything looks fine to me.

I didn't have that issue before using the `crossorigin` attribute. See [previous report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnrn-v2-mst-aptd-gcms-lcz-sty-c1-85zxarrqg.now.sh%2Ffr) of [previous deployment](https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-85zxarrqg.now.sh/fr) before [this commit](https://github.com/UnlyEd/next-right-now/commit/4bd923d1a91308edb85a9a28391babeb8cd0f9e1).

**Comment by Vadorequest** [comment]
> It the previous report should not have told you to preload the font itself if you were already preloading it though. That would be a bug, but I cannot reproduce it on the previous deployment URL you provided :/

Using [this report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnrn-v2-mst-aptd-gcms-lcz-sty-c1-85zxarrqg.now.sh%2Ffr) I get:

![image](https://user-images.githubusercontent.com/3807458/83453566-015be400-a45b-11ea-99a9-333917a5e29b.png)


Which led me to add 
```html
<link rel="preload" as="font" href={'/static/fonts/NeuzeitGrotesk/NeuzeitGrotesk-bold.woff2'} type="font/woff2" crossOrigin="anonymous" />
```

But I'm confused about `crossOrigin="anonymous"` being necessary for the fonts, but not for the style?

Here is the [full PR](https://github.com/UnlyEd/next-right-now/pull/81#issuecomment-637026595), with all commits. It should be easier to understand.

I'll remove all `crossOrigin="anonymous"` and see what happens, my understanding is that it should stop warning about `preload`.

**Comment by Vadorequest** [comment]
Here is a new [report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnrn-v2-mst-aptd-gcms-lcz-sty-c1-2wq94khp9.now.sh%2Ffr) for this [commit](https://github.com/UnlyEd/next-right-now/pull/81/commits/de9fe8cc2e848fdb352fe12f9438e0b94ef54c80) with this [url](https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-2wq94khp9.now.sh/fr)

![image](https://user-images.githubusercontent.com/3807458/83454958-4bde6000-a45d-11ea-9143-b1ff98364d4b.png)

![image](https://user-images.githubusercontent.com/3807458/83454980-5862b880-a45d-11ea-91d4-aeeef40133de.png)

So, the error about the `<link rel="preload" as="style" href={'/static/fonts/NeuzeitGrotesk/font.css'} />` has vanished, which is good. But now it complains about the fonts.

I'm not sure about what I'm doing here, with preloading fonts. Is it necessary?
I'll try again without font preloading.

**Comment by Vadorequest** [comment]
Here is a new [report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnrn-v2-mst-aptd-gcms-lcz-sty-c1-gbkuavf45.now.sh%2Ffr) for this [commit](https://github.com/UnlyEd/next-right-now/pull/81/commits/2b98ab5eec5d27bee7c739e1d78cb79865da9aa9) with this [url](https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-gbkuavf45.now.sh/fr)

![image](https://user-images.githubusercontent.com/3807458/83458344-a9c17680-a462-11ea-8c25-694c82e51658.png)

I believe this may be related with https://github.com/typekit/webfontloader/issues/403

I'm using WebFontLoader to load the font and apply a css class in `body` when the font has been loaded.

This avoids FOUT effect on browsers that don't support the `font-display: swap;`. (I'm using `font-display: swap;` too)

**Comment by Vadorequest** [comment]
@patrickhulce Do you have any advice/knowledge/feedback regarding this issue? 

I'm kinda lost between many various recommendations, would you know if the use of WebFontLoader is actually necessary/useful nowadays?

**Comment by patrickhulce** [comment]
Yes, thanks for following up.

You were so close :)

You *don't* want `crossorigin` on your *stylesheets*.

You *do* want `crossorigin` on your *fonts*.

For reasoning see the [MDN docs on preload](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Cross-origin_fetches)

I would expect the below to preload everything correctly and pass Lighthouse.

```html
<link rel="preload" as="style" href={'/static/fonts/NeuzeitGrotesk/font.css'}>	
<link rel="preload" as="font" href={'/static/fonts/NeuzeitGrotesk/NeuzeitGrotesk-bold.woff'} type="font/woff" crossOrigin="anonymous" />	  
<link rel="preload" as="font" href={'/static/fonts/NeuzeitGrotesk/NeuzeitGrotesk-bold.woff2'} type="font/woff2" crossOrigin="anonymous" />
<link rel="preload" as="font" href={'/static/fonts/NeuzeitGrotesk/NeuzeitGrotesk-black.woff'} type="font/woff" crossOrigin="anonymous" />
<link rel="preload" as="font" href={'/static/fonts/NeuzeitGrotesk/NeuzeitGrotesk-black.woff2'} type="font/woff2" crossOrigin="anonymous" />
```

**Comment by Vadorequest** [comment]
Awesome, thank you Patrick!

I just tested locally and online and I don't get any warnings anymore :)

https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnrn-v2-mst-aptd-at-lcz-sty-c1-nb8luf83o.now.sh%2Ffr

**Comment by prdt3e** [comment]
@patrickhulce
Can you still change your example, remove the correct spelling of crossorigin and parentheses?
I think it would be great for copiers :)

**Comment by halburgiss** [comment]
Just seeing this and am seeing the same original issue. I have 3 variants, all 3 result in the lighthouse warning ... "A preload <link> was found...", and the lighthouse score goes up 10 points. Version 85.0.4183.83 (Official Build) (64-bit)

	<link rel="preload" href="/library/fonts/maven/mavenpro-bold.woff2" as="font" type="font/woff2">
	<link rel="preload" href="/library/fonts/maven/mavenpro-regular.woff2" as="font" type="font/woff2" crossorigin=>
	<link rel="preload" href="/library/fonts/maven/mavenpro-black.woff2" as="font" type="font/woff2" crossorigin="anonymous">

None work. Is there another option?

**Comment by patrickhulce** [comment]
@halburgiss do you have an repro URL?

**Comment by halburgiss** [comment]
For the code I am trying to improve on??? No ... sorry.

**Comment by halburgiss** [comment]
There is actually 4 fonts, and they get loaded twice (with the warning shown in lighthouse):
￼
mavenpro-bold.woff2	200	http/1.1	methodsmachine.loc	font	(index)	24.9 kB	28 ms
￼mavenpro-regular.woff2	200	http/1.1	methodsmachine.loc	font	(index)	24.9 kB	9 ms
￼mavenpro-black.woff2	200	http/1.1	methodsmachine.loc	font	(index)	24.7 kB	13 ms
￼mavenpro-medium.woff2	200	http/1.1	methodsmachine.loc	font	(index)	24.8 kB	17 ms
￼mavenpro-bold.woff2	200	http/1.1	methodsmachine.loc	font	style-front-page-1599660170746.min.css	24.9 kB	35 ms
￼mavenpro-regular.woff2	200	http/1.1	methodsmachine.loc	font	style-base-1599660170746.min.css	24.9 kB	33 ms
￼mavenpro-black.woff2	200	http/1.1	methodsmachine.loc	font	style-base-1599660170746.min.css	24.7 kB	32 ms
￼mavenpro-medium.woff2	200	http/1.1	methodsmachine.loc	font	style-base-1599660170746.min.css	24.8 kB	7 ms
