### ISSUE TITLE
Can I reset cookies between each petition

### ISSUE THREAD

**Issue by Serginyu** [GoogleChrome/lighthouse#10897]
My lighthouse give me different scripts sizes per ru. The problem is that after the first run the cookies policy is accepted, so the next run will load external scripts.

I'm trying to clear all cookies between each petition, is it possible?

**Comment by patrickhulce** [comment]
Are you using DevTools? Cookies are always excluded by Lighthouse to avoid clearing login credentials. In DevTools you can clear cookies yourself in the Application panel between runs. For other channels, a fresh Chrome should be used for each run, so might need a little more information. 

![image](https://user-images.githubusercontent.com/2301202/83537128-c0df8300-a4b9-11ea-8f27-2288c02b7acd.png)

**Comment by adamraine** [comment]
@Serginyu if this is still an issue then we can reopen.
