### ISSUE TITLE
Don't use base64 source

### ISSUE THREAD

**Issue by jimmywarting** [GoogleChrome/lighthouse#10909]
**Feature request summary**

base64 takes up ~33% more memory, would it makes sense to cut off some few points for not using object urls instead made from a Blob or a File? 

The issue: `<img src="data:image/png;base64,iVBORw...`

**What is the motivation or use case for changing this?**
To reduce memory usage. and time spent on encoding/decoding

I have seen a couple of developer using fileReader.readAsDataURL on a `<input type="file">` on stackoverflow and in the wild just to show some preview image of what you just selected. instead of just creating a direct pointer to the file on the user's disk and consume `file.size * 1.33` more memory

object urls loads faster since you would not have to decode it to base64 using readAsDataURL and then decode it back to binary again by `<img>`.

But with it comes also the responsibility that you also sometime have to revoke it also. another con is that you can't cache or save the page since the blob url don't work after a reload. base64 also have a different origin then blob's so then there is also that to take into consideration if this rule got added

I don't know if there are good usecases for having base64 data urls but if there is then mabe just show it as an recommendation and don't cut of some points?

**Comment by adamraine** [comment]
If anyone is interested in working on a complete proposal we can reopen.
