### ISSUE TITLE
Next.js "Remove unused JavaScript" warning - False-positive/Regression?

### ISSUE THREAD

**Issue by Vadorequest** [GoogleChrome/lighthouse#10904]
Hi, several Next.js users have recently noticed a drop in LightHouse score regarding their Next.js app.

See https://github.com/vercel/next.js/discussions/13682

Apparently, even the official example suffers from this. 

Is this due to a regression in LightHouse? Or maybe in Next.js?

**Comment by patrickhulce** [comment]
This is not a regression in Lighthouse but a new feature in 6.0 that highlights files that have a considerable amount of unused JavaScript. This is working as intended, and I'll reply to that issue in next.js.
