### ISSUE TITLE
Terms of service while using PSI API

### ISSUE THREAD

**Issue by daviddarke** [GoogleChrome/lighthouse#10917]
Hi there, first off thanks for all the work on PSI. Tools like this are truly invaluable for improving the web.

---

We have a small internal dashboard tool that records the overall PSI score and plots overall results on a graph for our clients. We would love to open this up for others to use. However, reading the term of service I see this, in theory, it is prohibited: https://developers.google.com/terms#e_prohibitions_on_content

I can see using a self-installed version of the PSI library on a performant cloud platform would mitigate these terms of service issues due to its open-source nature and data not running through Google API services.

**I know you aren't lawyers** and I'm not asking for free legal advice. I'm just curious if anyone has experience of Google's own PSI API being allowed to be used on the platform such as this without breaking terms of service.

**Comment by patrickhulce** [comment]
This is a great point @daviddarke thanks for filing!

This is definitely concerning for use of PSI to track one's scores (including LHCI production monitoring). Users are currently not allowed to "create permanent copies of such content [returned from APIs]". Not being allowed to store the LHRs is a major limitation...

**Comment by daviddarke** [comment]
Thanks for taking an interest. I would love to know if there is an agreement allowing a service like https://treo.sh to cache the API, they even say they use the API on their homepage:

<img width="569" alt="Screenshot 2020-06-05 at 22 31 43" src="https://user-images.githubusercontent.com/1636310/83924507-c4566100-a77c-11ea-9817-392fea55712b.png">

... so they must have something in place right?

**Comment by exterkamp** [comment]
Okay, so I talked to our lawyers. It is Google's intention is for you to be able to use the information as you've described.

I've reached out to our legal team to update the language in our ToS to reflect this position.

**Comment by daviddarke** [comment]
Wow that's fantastic. Thank you for looking into this.

**Comment by adamraine** [comment]
@exterkamp Any update from legal?

**Comment by exterkamp** [comment]
We've been unable to get further updates.

> It is Google's intention is for you to be able to use the information as you've described.

This is still our stance. We're closing this issue as _fixed_. If this is insufficient we can re-open, but we've been pretty unsuccessful getting more out of legal than this attestation.
