### ISSUE TITLE
Help with understanding LCP metrics

### ISSUE THREAD

**Issue by ElForastero** [GoogleChrome/lighthouse#10928]
Hi 👋

We are facing with large LCP metrics on `www.powerthesaurus.org`. And we even can't get why does this happens.

According to the trace that I see in the Lighthouse report, almost all the content is shown right after page load (especially the main content). But LCP is postponed far away.

[Profile-20200608T190653.json.zip](https://github.com/GoogleChrome/lighthouse/files/4746809/Profile-20200608T190653.json.zip)

![image](https://user-images.githubusercontent.com/5102818/84046970-d114c800-a9bb-11ea-9046-987a30b8a9cc.png)

Can you give us a bit of advice from where to start?

**Comment by patrickhulce** [comment]
Thanks for filing @ElForastero!

Two things:

1. First a general tip. If you record a performance trace manually and then mouse over the "LCP" label you circled, it should highlight the element it's talking about in the page. See screenshot.
![image](https://user-images.githubusercontent.com/2301202/84049172-bc134700-a971-11ea-9655-ffcf68d8cbc5.png)

1. I'm guessing this is a SSR/SSG app with a hydration step client-side (as evidenced by my dark mode render in that example). If so, LCP is highlighting the fact that the hydration step is removing the original and recreating everything. If you're using angular it's a known bug the team is working on (https://github.com/angular/angular/issues/13446).

**Comment by ElForastero** [comment]
@patrickhulce Wow, it was the quickest answer I've got so far on GitHub issues.

Thanks for the clarifications 🙏

Yes, this is a React SSR app with hydration.

**Comment by patrickhulce** [comment]
Ah something is amiss with the SSR hydration then React should already do this when used correctly. I'd start there.

From the [React docs](https://reactjs.org/docs/react-dom-server.html#rendertostring)...

> If you call ReactDOM.hydrate() on a node that already has this server-rendered markup, React will preserve it and only attach event handlers, allowing you to have a very performant first-load experience.

**Comment by ElForastero** [comment]
@patrickhulce Finally, the root of the problem was found. We had an extra top-level `<Suspense />` component in our App that shouldn't be in the production build. Despite the fact, there weren't any async-loading components during initial rendering, this extra `<Suspense />` caused such strange behavior.

![image](https://user-images.githubusercontent.com/5102818/84109554-fa713a80-aa33-11ea-9e81-092599387004.png)

I hope this will help someone facing a similar issue.

Now LCP metrics look truthfully.

![image](https://user-images.githubusercontent.com/5102818/84109856-b2064c80-aa34-11ea-8335-031c8b5cf7f6.png)

The only question I have now is why this highlighted header block is treated as LCP? Probably we can just ignore this.

**Comment by patrickhulce** [comment]
Glad you found the issue!

> The only question I have now is why this highlighted header block is treated as LCP?

That appears to legitimately be the largest text node on the page and there are no large images.

If there are no further problems, I'm going to go ahead and close this out but feel free to come back if you believe there's something Lighthouse needs to change :)
