### ISSUE TITLE
LCP with CLI not matching web-vitals JS lib or Chrome extension

### ISSUE THREAD

**Issue by jasonmorita** [GoogleChrome/lighthouse#10929]
Note: If this is the wrong place to report this, please let me know where is best. Thank you.

#### Provide the steps to reproduce
1. Run LH on https://www.nationalgeographic.com/
(this is a site chosen at random, this holds true for any site I have tested)

`lighthouse https://www.nationalgeographic.com/ --chrome-flags='--headless --no-sandbox' --emulated-form-factor=desktop --view`

#### What is the current behavior?
Lighthouse LCP is about 5+ times longer for every site I have tested.

#### What is the expected behavior?
I expect LCP reported by Lighthouse to match web-vitals lib and extension.

#### Environment Information
* Affected Channels: CLI, Node, Extension, web-vitals JS lib
* Lighthouse version: 6.0
* Chrome version: 81-83
* Node.js version: 10, 12, 14
* Operating System: macOS 10.15.4

![image](https://user-images.githubusercontent.com/1566888/84083241-1920f400-a996-11ea-9d2d-68307d3efa17.png)

![image](https://user-images.githubusercontent.com/1566888/84083273-2a6a0080-a996-11ea-9e56-7668bd5cfb9b.png)

![image](https://user-images.githubusercontent.com/1566888/84083428-6e5d0580-a996-11ea-82e0-e0b20298cf0b.png)

![image](https://user-images.githubusercontent.com/1566888/84083446-79179a80-a996-11ea-828e-5e9536204f26.png)

**Comment by patrickhulce** [comment]
Thanks for filing @jasonmorita! See https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me.

The CLI flags for form factor and throttling are separate. If you want to run in CLI disabling throttling you also need to use `--throttling-method=provided`.

**Comment by jasonmorita** [comment]
@patrickhulce Thanks for that link. I don't see `--throttling-method=provided` in the docs provided; and using it, I still see an LCP many times larger than the extension reports. 

What is the best way to get these apples to apples for the same machine?

**Comment by patrickhulce** [comment]
`lighthouse https://www.google.com --throttling-method=provided --emulated-form-factor=desktop`  *is* the apples to apples comparison for the web vitals extension. That command gives nearly identical results to the web vitals extension for me.

![image](https://user-images.githubusercontent.com/2301202/84086570-ceab7180-a9ad-11ea-83d3-048430fb4f42.png)

What are you seeing?

**Comment by jasonmorita** [comment]
I am going to try with the original site since it is a little slower than Google :)

`lighthouse https://www.nationalgeographic.com/ --emulated-form-factor=desktop --view --only-categories=performance --throttling-method=provided`

LCP via CLI is 4.1s
LCP via ext is 1.46s

![image](https://user-images.githubusercontent.com/1566888/84087173-6ef99a00-a99e-11ea-8b1b-225101bc1074.png)
![image](https://user-images.githubusercontent.com/1566888/84087280-981a2a80-a99e-11ea-9007-902794e89730.png)

**Comment by patrickhulce** [comment]
Are you sure you're visiting the page with the Web Vitals extension with a cold cache? I see nothing that fast for that URL from web vitals extension in a fresh chrome profile

![image](https://user-images.githubusercontent.com/2301202/84087476-cbb18080-a9af-11ea-9114-f404c96bc609.png)

**Comment by jasonmorita** [comment]
@patrickhulce The more sites I test, the closer they look. I appears the NatGeo site is kind of an outlier.

But one thing that is consistent for me is that CLI LCP is always a little longer. 

Can you please confirm this is the closest I can get to the extension stats?:
`lighthouse <url> --emulated-form-factor=desktop --view --only-categories=performance --throttling-method=provided`

I really appreciate your time on this and this is a great tool.

**Comment by patrickhulce** [comment]
Yep `lighthouse <url> --emulated-form-factor=desktop --view --only-categories=performance --throttling-method=provided`

is exactly what the web vitals extension is reporting to you except with a completely clean Chrome profile (which will always be slower than a warm load).

**Comment by jasonmorita** [comment]
Thank you!
