### ISSUE TITLE
Request list of checks Lighthouse does to write an up to stack pack

### ISSUE THREAD

**Issue by ayumi-cloud** [GoogleChrome/lighthouse#10927]
Hello,

Where can I download a list of all the latest Lighthouse checklists to be able to write our cms pack.

I can give an extra of what I'm talking about, the Wordpress pack says the following:

### Metrics

- Estimated Input Latency
- First Contentful Paint
- First CPU Idle
- First Meaningful Paint
- Time to Interactive
- Speed Index

However this is out of date as Google has since created new and exciting metrics such as the `Cumulative Layout Shift` API etc.

Where can I get a list of all the Lighthouse checks to be able to write an up to date stack pack and also be able to update it with new checks being added in future releases.

Thanks.

---

Just going to link this issue to our cms to make tracking easier: https://github.com/octobercms/october/issues/4959

----

I ask here, as the stack pack repo seems dead and very quiet.

**Comment by patrickhulce** [comment]
Thanks for filing @ayumi-cloud!

The source of truth for the list of checks is the `default-config.js` file in this repo.

https://github.com/GoogleChrome/lighthouse/blob/0002a58b56531a32e7d3c2e40fcb04af97165ef6/lighthouse-core/config/default-config.js#L418-L462

Anything there you can write a custom description for in a stack pack.

If you're referring to https://github.com/GoogleChrome/lighthouse-stack-packs it's not dead but definitely not as heavily monitored as this one. Make sure you can satisfy the [contributing requirements](https://github.com/GoogleChrome/lighthouse-stack-packs/blob/master/CONTRIBUTING.md#submitting-a-new-stack-pack) there with your stack pack if you haven't already before investing! :)

**Comment by ayumi-cloud** [comment]
@patrickhulce thank you
