### ISSUE TITLE
Drastically different LCP values with Lighthouse in canary and PSI

### ISSUE THREAD

**Issue by bodbdigr** [GoogleChrome/lighthouse#10931]
#### Provide the steps to reproduce
1. Run LH on https://www.mother.ly/trending-topics
 
#### What is the current behavior?

When I run lighthouse locally in latest chrome canary (85.0.4166.0), "Low end mobile" profile and moto g4 device I get LCP value of 2.4 seconds and for the same page on PSI I get 4.1 seconds. I understand that it depends on hardware it's running on but what seems strange to me is that all other metrics are more or less the same. For instance I would assume if my network emulation would be far off from network profile on PSI I would get drastically different values for FCP and/or SI, the same goes for CPU profile - if drastically different TBT and TTI would be very different but they aren't.

see screenhots:

local canary version - https://jumpshare.com/v/nBUE08ynINLNC4M7QIIb
PSI version - https://jumpshare.com/v/ceaWZHDoUVavhVRa1gl5

#### What is the expected behavior?

LCP values to be more in line or at least understanding why difference is so striking 

#### Environment Information
* Affected Channels: Extension, DevTools
* Lighthouse version: 6.0 
* Chrome version: 85.0.4166.0
* Node.js version: -
* Operating System: MacOS 10.15.4

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @bodbdigr! This appears to just be [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md). Running PSI a few times gives me different numbers around the 3.0s - 4.0s range. Locally 2.4s-3.1s.

![image](https://user-images.githubusercontent.com/2301202/84156873-a5cbc080-aa2f-11ea-875f-86fc38c853e3.png)

As to why the other numbers aren't changing as much, LCP is a moment later in the load and depends on more CPU tasks/resources. Generally in page performance the more random variables (which aren't IID and in fact are often highly correlated) affecting the metric the greater the opportunity for variance.
