### ISSUE TITLE
Inconsistencies in measuring LCP

### ISSUE THREAD

**Issue by OllysCoding** [GoogleChrome/lighthouse#10941]
Hi 👋 

We're doing some web optimisations over at our site and struggling with measuring and improving LCP.

Specifically the issue we're facing is that when running a lighthouse speed test (whether through dev tools or PSI) we're seeing that the while LCP is reported at the same timestamp as FCP in the trace, we are seeing vastly different times in the Metrics; 

[localhost_3000-20200610T124428.json.zip](https://github.com/GoogleChrome/lighthouse/files/4758202/localhost_3000-20200610T124428.json.zip)
![image](https://user-images.githubusercontent.com/9575458/84263924-44cbe780-ab18-11ea-8bde-fbf8b709a5bf.png)

Trace:
![image](https://user-images.githubusercontent.com/9575458/84263985-590fe480-ab18-11ea-8783-b6f85516e46a.png)
![image](https://user-images.githubusercontent.com/9575458/84264012-6200b600-ab18-11ea-8897-f6ce4862f1d5.png)

We see the same results in a performance profile we run it manually (FCP and LCP are the same)

The difference's are typically amplified in PSI (1-3s FCP, 5-10s LCP)

Is anyone able to point in the right direction for beginning to resolve this?

**Comment by andy-feldman** [comment]
> The short story: When performance is stretched out by throttling, paints are less likely to be coalesced into a single moment.

@patrickhulce Would you say that trace frame screenshots should still accurately represent the moments in which FCP/LCP take place even during a throttled Lighthouse 6.0 test?  Because I have seen many tests where either the FCP and LCP are far apart without any change in frame screenshots, or FCP & LCP are significantly delayed in the timeline long after frame screenshots have already shown that full painting has been completed.

**Comment by patrickhulce** [comment]
> Would you say that trace frame screenshots should still accurately represent the moments in which FCP/LCP take place even during a throttled Lighthouse 6.0 test?

I would not say this for simulated throttling. It's significantly more common than not that the screenshots of the progression of a page loaded on a fast network will be different than the progression of a page when loaded on a slow network. This is why so much effort had to go into recreating a synthetic speed index estimate for simulated throttling to be paired with the observed speed index.

Please see https://github.com/GoogleChrome/lighthouse/issues/11014#issuecomment-650215488 for further explanation.

The questions in this particular issue center around the mismatch of an unthrottled trace with simulated performance metric values, which is already documented, so I'll go ahead and close this out.
