### ISSUE TITLE
Update axe-core to 3.5.5

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10948]
tracking issue for https://github.com/dequelabs/axe-core/issues/2280

**Comment by brendankenny** [comment]
Is this different than #10908?

**Comment by simonmaass** [comment]
@connorjclark came here to report exactly that - please update <3

**Comment by patrickhulce** [comment]
We are still waiting on axe-core to publish 3.5.5 to npm @simonmaass

**Comment by simonmaass** [comment]
@patrickhulce is this already deployed now to https://web.dev/measure/?

**Comment by patrickhulce** [comment]
@simonmaass no, it will go out with Lighthouse 6.1 later this week and make its way to PSI some time after that.
