### ISSUE TITLE
Page Speed Insights Ignores CloudFlare's Rocket Loader

### ISSUE THREAD

**Issue by ScottTravisHartley** [GoogleChrome/lighthouse#10947]
Cloudflare has a tool for website's dubbed the Rocket Loader. 
Doc: https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-

The tool effectively will optimize the website by renaming all <script> related tags to something like the following. 

`<script src='/wp-includes/js/jquery/jquery.js' type="text/javascript"></script>
`
to the following

`<script src='/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp' type="4906178bed34d3d402cc70b3-text/javascript"></script>
`
It also rewrites inline scripts so the opening <script> tag is rewritten to something like: 
`<script type="4906178bed34d3d402cc70b3-text/javascript">
`
The concept is quite simple all the JS on the page is effectively deferred including inline JS. This is particularly useful when an application has an in-line script that is dependent on another file loading in a render-blocking fashion. 

However, Page Speed Insights ignores this completely. 

For instance on my domain: https://www.sertmedia.com/

You can run a test using Page Speed Insights and it will get flagged as JQuery being render-blocking. 
![image](https://user-images.githubusercontent.com/45110039/84441077-bed79b80-ac00-11ea-8148-cd1746dff1fc.png)

However, if you run the same test in Lighthouse (on Chrome Canary) 
![image](https://user-images.githubusercontent.com/45110039/84441152-e2024b00-ac00-11ea-84e5-2a831b7350d4.png)

It is properly detected as no longer being render-blocking. The issue, of course, is this can have a fairly drastic impact on performance between lighthouse local and page speed insights. Also, I tested the site on web.dev as well just for reference and it acts the same as page speed insights.

**Comment by ScottTravisHartley** [comment]
In my mind lighthouse is correct because the JS is no longer render-blocking and this is verifiable in chrome dev tools and some of the other testing tools GTMetrix, and Pingdom also register it as no longer being render-blocking. 

But the discrepancy can be quite large when testing lighthouse local due to the rocket loader being ignored on page speed insights. One website, in particular, I have been working on using this same tech gets locally around a 65-75 on mobile whereas on Page Speed Insights it scores around a 30-45.

**Comment by connorjclark** [comment]
PSI is just using a headless Chrome with a specific user agent. It seems the RocketLoader service from CF has disabled* itself from requests made by this useragent (`Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3963.0 Mobile Safari/537.36 Chrome-Lighthouse`).  If that's the case, the discrepancy lies with CF. Can it be configured to run for any UA you want?

\* I confirmed this by checking for `rocket-loader.min.js` in the main HTML response body in our internal PSI tool–it did not appear. But I see it from locally in Chrome DevTools.

[CF](https://blog.cloudflare.com/we-have-lift-off-rocket-loader-ga-is-mobile/) directly references Lighthouse in their blog post for Rocket Loader, so if you bring this to their attention they may prioritize this.

**Comment by ScottTravisHartley** [comment]
I am not able to, this is probably control on their side I will see if I can bring this to their attention since that's a silly thing to do on their part. My guess this was probably a workaround for old-school PSI when it wasn't running on lighthouse.

**Comment by connorjclark** [comment]
Feel free to comment if you have any information to share from CF. Gonna close this as there's no action item for LH.

**Comment by sejoker** [comment]
We are planing to allow Page Speed Insights to run RocketLoader.

**Comment by KeesCBakker** [comment]
> We are planing to allow Page Speed Insights to run RocketLoader.

Any news on a time line?

**Comment by sejoker** [comment]
> > We are planing to allow Page Speed Insights to run RocketLoader.
> 
> Any news on a time line?

Rocket Loader should run during Page Speed Insights testing.
