### ISSUE TITLE
Issue with Preload Key Requests

### ISSUE THREAD

**Issue by johncarlson21** [GoogleChrome/lighthouse#10951]
## Provide the steps to reproduce
1. Run LH on https://www.magicmurals.com/

#### What is the current behavior?
First run shows to preload a font file: https://www.magicmurals.com/static/frontend/Magic/ultimo/en_US/fonts/Blank-Theme-Icons/Blank-Theme-Icons.woff2

After adding preload for font and running LH again, it shows a warning of:
Warnings: A preload <link> was found for "https://www.magicmurals.com/static/frontend/Magic/ultimo/en_US/fonts/Blank-Theme-Icons/Blank-Theme-Icons.woff2" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

if you click the dropdown to expand the preload section, it still shows that I should preload this file.

#### What is the expected behavior?
Should not show warning and should not show to preload the resource again.

#### Environment Information
* Affected Channels: DevTools/Page Speed Insights
* Lighthouse version:6
* Chrome version: Version 83.0.4103.97
* Operating System: MacOS Mojave 10.14.6

**Comment by patrickhulce** [comment]
Thanks very much for filing! Lighthouse is correct here. The preload this page added isn't actually being used. 

> Warnings: A preload was found for "https://www.magicmurals.com/static/frontend/Magic/ultimo/en_US/fonts/Blank-Theme-Icons/Blank-Theme-Icons.woff2" but was not used by the browser. Check that you are using the crossorigin attribute properly.

This page isn't using the `crossorigin` attribute properly. Fonts require the use of `crossorigin` even if the font is on the same origin. [See the docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Cross-origin_fetches). The warnings are generally there for a reason ;)

**Comment by johncarlson21** [comment]
Thank you.. man I read that a million times and missed it..
