### ISSUE TITLE
DBW: Page uses too many DOM elements

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1096]
Profiling Google Apps, they use < 1000 DOM nodes. Too many can hurt performance. It's especially a problem for users of web components where many custom elements are deep within shadow roots.

Let's get a baseline of how many is too many and create an audit for it.

from @esprehn

**Comment by ebidel** [comment]
> These days most apps are 5000+, ideally your page is closer to 1500 if
possible. The engine itself is optimized max ~60 element wide, and max ~32
element deep documents. We handle things better, but you're in the sweet
spot if you're inside that box.

**Comment by XhmikosR** [comment]
Definitely a must have audit!
