### ISSUE TITLE
On Import: Error: ENOENT: no such file or directory, open '//report-template.html'

### ISSUE THREAD

**Issue by MorphinIO** [GoogleChrome/lighthouse#10963]
# Error: ENOENT: no such file or directory, open '//report-template.html'

<img width="928" alt="Screen Shot 2020-06-15 at 1 50 42 PM" src="https://user-images.githubusercontent.com/65057493/84689602-37936c00-af0f-11ea-8e2d-8a77cfab8df0.png">

#### Provide the steps to reproduce
1. On the `node:12.18.0-alpine3.12` docker image, create hello-world express app and import lighthouse
2. Build the image and run the container

#### What is the current behavior?
Lighthouse crashes my server on import.

#### What is the expected behavior?
Lighthouse imports correctly and the server runs.

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 6.0.0
* Chrome version: 83.0.4103.97
* Node.js version: node:12.18.0-alpine3.12 (Docker base image)
* Operating System: MacOS 10.15.4

**Related issues**
Couldn't find any 😬 

Thanks for any help in advance! 😁

**Comment by patrickhulce** [comment]
Thanks for filing @MorphinIO! But why are you running Lighthouse through webpack on your server?

Lighthouse cannot be used client-side. It's a node package designed for server-side usage.

As the error shows, we use `fs` to read report assets on the local filesystem which won't work once webpack'd unless you're using some fancy filesystem shim that rewrites paths, but that's not going to be something to fix in lighthouse core.

**Comment by MorphinIO** [comment]
We are using webpack because we are delivering a React App via SSR. We are importing lighthouse inside the node JS server.

**Comment by MorphinIO** [comment]
Here is my webpack file:
```
const path = require('path');
const Dotenv = require('dotenv-webpack');
const WebpackShellPlugin = require('webpack-shell-plugin');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: './server/bin/www.js',

  target: 'node',

  externals: [nodeExternals()],

  output: {
    path: path.resolve('server-build'),
    filename: 'index.js'
  },
  plugins: [
    new Dotenv(),
    new WebpackShellPlugin({onBuildStart:['echo "Webpack Start"'], onBuildEnd:['echo "Webpack End"']})
    ],
  module: {
    rules: [
      {
          use: 'babel-loader',
          test: /\.js?$/,
          exclude:/node_modules/,
          resolve: {
              extensions: ['.jsx', '.js', '.json']
          }
      },
      {
        test: /\.css$/,
        use: [
          'isomorphic-style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1
            }
          },
          'postcss-loader'
        ]
      }
    ]
  }
};
```

**Comment by MorphinIO** [comment]
> Thanks for filing @MorphinIO! But why are you running Lighthouse through webpack on your server?
> 
> Lighthouse cannot be used client-side. It's a node package designed for server-side usage.
> 
> As the error shows, we use `fs` to read report assets on the local filesystem which won't work once webpack'd unless you're using some fancy filesystem shim that rewrites paths, but that's not going to be something to fix in lighthouse core.

So I am going through my code and your last statement doesn't make sense to me. This is because we are importing fs and reading files with fs.readFile. We are successfully doing this in the same file and after we import lighthouse the error appears.

**Comment by patrickhulce** [comment]
webpack seems to replace `__dirname` with `/` when bundling your code which forces this error. Lighthouse core is not going to be attempting to support arbitrary bundling. 

You're welcome to use the well-maintained [official client bundles](https://github.com/GoogleChrome/lighthouse/tree/553ca03cdef903b6e7516e36b1b9a01e80eac04b/clients) if bundling is important to your use case, but I'd definitely recommend against doing so on the server-side.

**Comment by MorphinIO** [comment]
Thanks a lot! I'll look into those client bundles!
