### ISSUE TITLE
Proposal to extend the existing hreflang audit

### ISSUE THREAD

**Issue by umaar** [GoogleChrome/lighthouse#10973]
This could also be a brand new audit, but since an existing SEO [hreflang](https://web.dev/hreflang/) audit exists, maybe it could just be extended upon?

The current hreflang audit checks that [valid](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/valid-langs.js) `hreflang` codes are used. Like with any audit, we could further strengthen/widen the scope so that more things are validated. Here are some suggestions for enhancements:

1. If a canonical URL exists, then ensure that URL is referenced by one of the `hreflang`'s [source](https://yoast.com/hreflang-ultimate-guide/#hreflang-canonical)
2. Country based language variations are fine, e.g. `en-gb`. But could also do a _general language version_ so an english speaker in canada still benefits, like `en`. So if we see hreflang codes of `en-US` and `en-AU`, this audit could suggest an additional hreflang of `en`. [source](https://delante.co/hreflang-language-version-tag/)
3. Use utf-8 encoding in URLs: if a link href refers to `http://vélo.com`, that should instead be `http://v%C3%A9lo.com` [source](https://support.google.com/webmasters/answer/183668?visit_id=637279156799049152-687967856&rd=1)
4. The audit could check that a fully-qualified URL is being used - so no relative URLs [source](https://support.google.com/webmasters/answer/189077?hl=en)

Any thoughts on these? Happy to add these in if we feel these would be useful.

Google webmaster docs [here](https://support.google.com/webmasters/answer/189077?hl=en).

**Comment by paulirish** [comment]
> This could also be a brand new audit, but since an existing SEO [hreflang](https://web.dev/hreflang/) audit exists, maybe it could just be extended upon?
> 
> The current hreflang audit checks that [valid](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/valid-langs.js?rgh-link-date=2020-06-16T15%3A25%3A59Z) `hreflang` codes are used. Like with any audit, we could further strengthen/widen the scope so that more things are validated. Here are some suggestions for enhancements:
> 
> 1. If a canonical URL exists, then ensure that URL is referenced by one of the `hreflang`'s [source](https://yoast.com/hreflang-ultimate-guide/#hreflang-canonical)

didnt expect this but yeah a rel=alternate pointing back to itself is [considered correct](https://support.google.com/webmasters/answer/189077). sure then.

> 2. Country based language variations are fine, e.g. `en-gb`. But could also do a _general language version_ so an english speaker in canada still benefits, like `en`. So if we see hreflang codes of `en-US` and `en-AU`, this audit could suggest an additional hreflang of `en`. [source](https://delante.co/hreflang-language-version-tag/)

hmmm. doesn't seem like a huge deal, but yeah i get the reasoning. i'm a little worried about all the cases we'd complain about somewhat needlessly.. (like a page using ja-JP... or ko-KO..). 

given that, the implementation here seems the most involved. I took a look at the various google guidance on this stuff and they dont explictly make this recommendation. https://webmasters.googleblog.com/2014/07/troubleshooting-hreflang-annotations-in.html  https://support.google.com/webmasters/answer/6059209?visit_id=637279156799049152-687967856&rd=1  

> 3. Use utf-8 encoding in URLs: if a link href refers to `http://vélo.com`, that should instead be `http://v%C3%A9lo.com` [source](https://support.google.com/webmasters/answer/183668?visit_id=637279156799049152-687967856&rd=1)

seems good. i suppose this is true for all href's/src's on the page.

> 4. The audit could check that a fully-qualified URL is being used - so no relative URLs [source](https://support.google.com/webmasters/answer/189077?hl=en)

https://webhint.io/docs/user-guide/hints/hint-no-protocol-relative-urls/ is worthwhile and we should also have this. it makes sense for all href's/src's IMO.

so i'm thinking 3 and 4 are separate audits that check everything. and 1 sounds good.. not sure how to really extend the current one with it, but.. i'd prefer that a bit over creating a new one.

2 i think i'd rather hold off on since the guidance from google is fairly weak.

**Comment by brendankenny** [comment]
> > 1. Use utf-8 encoding in URLs: if a link href refers to `http://vélo.com`, that should instead be `http://v%C3%A9lo.com` [source](https://support.google.com/webmasters/answer/183668?visit_id=637279156799049152-687967856&rd=1)
> 
> seems good. i suppose this is true for all href's/src's on the page.

That page is making a stronger suggestion than just utf-8, though. It's saying utf-8 encoded and then escaped so urls contain only ascii characters.

The doc seems to be for sitemaps, though. It's common to escape non-ascii characters (and browsers still generally handle it well if you don't), but the [HTML spec is ok with not doing that](https://url.spec.whatwg.org/#url-code-points) in URLs.

**Comment by umaar** [comment]
Ah cool thanks for the quick feedback. Not wedded to those 4 points, they're just the result of me reading through random hreflang articles to see what recommendations Lighthouse can make. Just to double check:

1. We're good to enhance the existing hreflang audit to validate that when a canonical URL is specified & a `hreflang` link exists, we ensure that the canonical URL is referenced in at least one of the `hreflang` links.

> not sure how to really extend the current one with it, but.. i'd prefer that a bit over creating a new one.

Same, not sure but will have a look 👍🏼️

2. Recommend general language versions (`en` in addition to `en-US`)

> guidance from google is fairly weak.

I saw it in this [video](https://youtu.be/8ce9jv91beQ?t=440) - but, that's a very __old__ video and maybe not important anymore. Holding off on this sounds good.

3. Use utf-8 encoding in all `href`'s and `src`'s

New audit that checks everything makes sense, can make a new audit issue so discussions (including Brendan's comment) can continue there.

4. Check that a fully-qualified URL is being used - so no relative URLs

Same again, happy to make a new audit issue to continue discussions there.

**Comment by patrickhulce** [comment]
> Check that a fully-qualified URL is being used - so no relative URLs
> https://webhint.io/docs/user-guide/hints/hint-no-protocol-relative-urls/ is worthwhile and we should also have this. it makes sense for all href's/src's IMO.

I think we're talking about two separate issues here. For SEO, they want no relative URLs at all, not just no *protocol-relative* URLs

> Alternate URLs must be fully-qualified, including the transport method (http/https), so:
 https://example.com/foo, not //example.com/foo or /foo

I don't think we want to ban `/foo` in all href/src attributes.

**Comment by umaar** [comment]
True good distinction Patrick! Yep the point was for the purposes of SEO, and with the hreflang audit in mind, there's a recommendation to keep URLs as fully-qualified, and I was seeking thoughts on validating that within the audit.

> I don't think we want to ban /foo in all href/src attributes.

That's exactly what I was going to ask about, as in, do we want a predefined list of elements which are checked for having non-relative URLs - as part of a new audit?

Alternatively, we could start out with validating fully-qualified URLs for `hreflang` links only, and the idea of doing it to all URLs (within a predefined list of elements) can be a future discussion?

**Comment by patrickhulce** [comment]
IMO there's two separate audits to have for 3.

1. SEO-specific audit, no relative links for `hreflang`
2. Best Practices audit, no protocol-relative links anywhere

@paulirish is that what you were thinking too?

**Comment by paulirish** [comment]
yup sg

**Comment by exterkamp** [comment]
Did #11022 resolve this issue?

**Comment by umaar** [comment]
Yep thanks!
