### ISSUE TITLE
Performance test speed index issue

### ISSUE THREAD

**Issue by susilogic** [GoogleChrome/lighthouse#10974]
When set "Simulated throttling" ->off, then the performance result is the same as when switched on

LH settings:
- Device ->Desktop
- Categories ->All
- Simulated throttling ->off

1. Run LH on 
https://google.com/
--->Speed index: 1.7 1.6 1.7 1.6
https://sinngewinn.ch/

2.  set "Simulated throttling" ->on and run LH again
https://google.com/
--->Speed index: 1.8 1.5 1.5 1.4 1.5
https://sinngewinn.ch/

To load such a site like google.com must be 0.4-0.7sec since there is no image to load.

System:
- win7
- chrome Version 83.0.4103.106 (Official Build) (64-bit)
- Lighthouse 5.7.1

I appreciate your tool and run it all the time for debug my templates. The older versions before 1.2020 worked just as expected, but since the January version, LH results were unreal, i ran the December version till now.
Today i installed the newest version of google chrome, but the speed index bug is still there.

**Comment by patrickhulce** [comment]
Thanks for filing @susilogic! This was fixed in 6.0 and is available in Chrome Canary already. It will take a bit for it to make its way through to Chrome stable.

See https://github.com/GoogleChrome/lighthouse/issues/10315 for details
