### ISSUE TITLE
Pass parameters to beforePass

### ISSUE THREAD

**Issue by htr751** [GoogleChrome/lighthouse#10972]
I would like to pass parameters to my custom gatherers but I can't find how to do it. Is there any way to do so? If not is there an alternative to pass data to it?

**Comment by patrickhulce** [comment]
Thanks for filing @htr751! Would you mind explaining a little more of your use case? What parameters do you want to pass? Where are they coming from?

**Comment by htr751** [comment]
I wanted to pass some script (as a string) so I will be able to evaluate it in the context of the tested site. thought about passing it when I call lighthouse with the url of the site.

**Comment by patrickhulce** [comment]
well you have full control over your custom gatherer so you have plenty of options here just as you would with any other node code.

you could...

- read arguments from `process.argv` and find a custom flag you use
- read from local filesystem using `fs`
- read from environment variables using `process.env`

When you don't need to bundle the gatherer for the browser like we do in core you have a lot of flexibility here :)

Proper support for gatherer options is tracked by https://github.com/GoogleChrome/lighthouse/issues/10247

**Comment by patrickhulce** [comment]
We consider this problem solved by the options outlined in https://github.com/GoogleChrome/lighthouse/issues/10972#issuecomment-645369552.
