### ISSUE TITLE
"Device" option not mentioned + report...

### ISSUE THREAD

**Issue by iAmOren** [GoogleChrome/lighthouse#10991]
https://developers.google.com/web/tools/lighthouse/?utm_source=devtools#devtools

24
Performance
91
Accessibility
86
Best Practices
95
SEO
Progressive Web App
0–49
50–89
90–100
24
Performance
Metrics

First Contentful Paint
2.4 s
Speed Index
11.9 s
Time to Interactive
22.9 s
First Meaningful Paint
3.8 s
First CPU Idle
13.1 s
Max Potential First Input Delay
1,510 ms
View Trace
Values are estimated and may vary. The performance score is based only on these metrics.
Screenshot
Screenshot
Screenshot
Screenshot
Screenshot
Screenshot
Screenshot
Screenshot
Screenshot
Screenshot
OpportunitiesThese suggestions can help your page load faster. They don't directly affect the Performance score.
Opportunity
Estimated Savings
Properly size images
53.24 s
Defer offscreen images
0.56 s
Remove unused CSS
0.56 s
Preconnect to required origins
Warnings:
A preconnect <link> was found for "https://www.google-analytics.com" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preconnect <link> was found for "https://fonts.googleapis.com" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preconnect <link> was found for "https://apis.google.com" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preconnect <link> was found for "https://fonts.gstatic.com" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
0.31 s
DiagnosticsMore information about the performance of your application. These numbers don't directly affect the Performance score.
Avoid enormous network payloads Total size was 15,925 KB
Minimize main-thread work 31.3 s
Ensure text remains visible during webfont load
Warnings: Lighthouse was unable to automatically check the font-display value for the following URL: https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxPKTU1Kg.ttf.
Reduce the impact of third-party code Third-party code blocked the main thread for 6,600 ms
Reduce JavaScript execution time 9.3 s
Serve static assets with an efficient cache policy 11 resources found
Avoid chaining critical requests 10 chains found
User Timing marks and measures 22 user timings
Keep request counts low and transfer sizes small 172 requests • 15,925 KB
Passed audits (11)
91
Accessibility
These checks highlight opportunities to improve the accessibility of your web app. Only a subset of accessibility issues can be automatically detected so manual testing is also encouraged.
ARIAThese are opportunities to improve the usage of ARIA in your application which may enhance the experience for users of assistive technology, like a screen reader.
[role]s do not have all required [aria-*] attributes
ContrastThese are opportunities to improve the legibility of your content.
Background and foreground colors do not have a sufficient contrast ratio.
Additional items to manually check (11) These items address areas which an automated testing tool cannot cover. Learn more in our guide on conducting an accessibility review.
Passed audits (20)
Not applicable (13)
86
Best Practices
Links to cross-origin destinations are unsafe
Browser errors were logged to the console
Passed audits (13)
95
SEO
These checks ensure that your page is optimized for search engine results ranking. There are additional factors Lighthouse does not check that may affect your search ranking. Learn more.
Mobile FriendlyMake sure your pages are mobile friendly so users don’t have to pinch or zoom in order to read the content pages. Learn more.
Tap targets are not sized appropriately 37% appropriately sized tap targets
Additional items to manually check (1) Run these additional validators on your site to check additional SEO best practices.
Passed audits (12)
Progressive Web App
These checks validate the aspects of a Progressive Web App. Learn more.
Fast and reliable
Page load is not fast enough on mobile networksYour page loads too slowly and is not interactive within 10 seconds. Look at the opportunities and diagnostics in the "Performance" section to learn how to improve. Interactive at 22.9 s
Current page responds with a 200 when offline
start_url responds with a 200 when offline
Installable
Uses HTTPS
Registers a service worker that controls page and start_url
Web app manifest meets the installability requirements
PWA Optimized
Redirects HTTP traffic to HTTPS
Configured for a custom splash screen
Sets a theme color for the address bar.
Content is sized correctly for the viewport
Has a <meta name="viewport"> tag with width or initial-scale
Contains some content when JavaScript is not available
Provides a valid apple-touch-icon
Additional items to manually check (3) These checks are required by the baseline PWA Checklist but are not automatically checked by Lighthouse. They do not affect your score but it's important that you verify them manually.
Runtime Settings
URL
https://developers.google.com/web/tools/lighthouse/?utm_source=devtools#devtools
Fetch time
Jun 18, 2020, 10:53 AM GMT+3
Device
Emulated Nexus 5X
Network throttling
150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
CPU throttling
4x slowdown (Simulated)
User agent (host)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
User agent (network)
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse
CPU/Memory Power
302
Generated by Lighthouse 5.7.1 | File an issue

**Comment by patrickhulce** [comment]
Thanks for filing @iAmOren!

It is but just down at the bottom.

> Fetch time
Jun 18, 2020, 10:53 AM GMT+3
_**Device
Emulated Nexus 5X**_
Network throttling
150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)

#9379 tracks making this more prominent and immediately obvious and we're working on it 👍

**Comment by iAmOren** [comment]
In Chrome and on that page, there is no mention/description of device and
what it's for/how to use.
I didn't mean in the report...
Thanks for the quick response!
Oren. :)
