### ISSUE TITLE
Improve extension npm install time

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#110]
fewer dependencies?

**Comment by paulirish** [comment]
@samccone what were you thinking here?

**Comment by samccone** [comment]
i am going to remove as many things as possible

**Comment by samccone** [comment]
After some significant trimming:

![image](https://cloud.githubusercontent.com/assets/883126/14295784/e66a64fa-fb2b-11e5-9b9b-4bafe5ed6372.png)
