### ISSUE TITLE
Remove unused JavaScript (must be a bug)

### ISSUE THREAD

**Issue by okankck** [GoogleChrome/lighthouse#11007]
Remove unused JavaScript error appears all results. There is no any unused js file. Even my site is an amp site.
![amp-site-pagespeed](https://user-images.githubusercontent.com/19880585/85406832-09470980-b56b-11ea-91bb-35ef9947744a.jpg)

**Comment by patrickhulce** [comment]
Thanks for filing @okankck!

> There is no any unused js file.

It is not saying the entire file is not used. It is saying a significant chunk of the file is unused. AMP usage does not make one immune to performance opportunities even if it helps significantly to reach performance metric targets.

> Remove unused JavaScript error appears all results.

Nearly all sites have unused JavaScript ;)

To the core of your concern though, we've landed #10906 to make it less noisy which would only flag one of the files in your screenshot. See https://github.com/GoogleChrome/lighthouse/issues/10872 for more discussion on this audit and the decisions made.
