### ISSUE TITLE
Lighthouse CLI scores with basic auth are dramatically different from Lighthouse browser version scores

### ISSUE THREAD

**Issue by dimanech** [GoogleChrome/lighthouse#11002]
#### Provide the steps to reproduce

1. Run LH on some url with basic auth

```
npx lighthouse https://login:password@powerful-thicket-58084.herokuapp.com --emulated-form-factor=none --view --only-categories=performance --chrome-flags='--window-size=1920,1080'
```
```
npx lighthouse https://powerful-thicket-58084.herokuapp.com --emulated-form-factor=none --view --only-categories=performance --extra-headers="{\"Authorization\":\"Basic bG9naW46cGFzc3dvcmQ=\"}" --chrome-flags='--window-size=1920,1080'
```
![Screenshot from 2020-06-21 23-17-38](https://user-images.githubusercontent.com/1180050/85234359-8a8c8800-b415-11ea-91e6-665e988748b1.png)
[report-cli.pdf](https://github.com/GoogleChrome/lighthouse/files/4810207/1.pdf)

2. Run with Google Chrome beta 84.0.4147.56
![Screenshot from 2020-06-21 23-26-38](https://user-images.githubusercontent.com/1180050/85234549-ba885b00-b416-11ea-81c9-db42fab667a5.png)
[report-browser.pdf](https://github.com/GoogleChrome/lighthouse/files/4810211/2.pdf)

3. Compare the results

#### What is the current behavior?

Scores from Google Chrome are different from CLI version with basic auth passed through URL encode or header.

#### What is the expected behavior?

Scores will be the same - so run from CLI or CI will be equal to run from browser development tools.

#### Environment Information
* Affected Channels: CLI, Node, DevTools
* Lighthouse version: 6.0.0
* Chrome version: 84.0.4147.56
* Operating System: Linux Fedora 32

**Comment by patrickhulce** [comment]
Thanks for filing @dimanech! If you want the scores to be similar you'll need to use the same settings in each environment.

The CLI controls form factor emulation and throttling separately. If you're using simulated throttling then match the [desktop settings](https://github.com/GoogleChrome/lighthouse/blob/553ca03cdef903b6e7516e36b1b9a01e80eac04b/lighthouse-core/config/constants.js#L43-L50) or use `--throttling-method=provided` if using applied throttling in DevTools.
