### ISSUE TITLE
Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_LCP)

### ISSUE THREAD

**Issue by lvorcool** [GoogleChrome/lighthouse#11003]
> 

**Summary**
### excuting an order
`node /home/test/software/node-v12.18.0-linux-x64/lib/node_modules/lighthouse/lighthouse-cli https://kaiwu.lagou.com/test_engineer.html --chrome-flags="--incognito --headless" --only-categories=performance --emulated-form-factor=desktop --throttling-method=provided --disable-storage-reset`

**report error**
![image](https://user-images.githubusercontent.com/21286480/85260861-eef32a00-b49d-11ea-80c8-34f2a5a799fa.png)

**specific error**
[report.html.zip](https://github.com/GoogleChrome/lighthouse/files/4811822/report.html.zip)

**machine**
os : centos Red Hat 4.8.5-36
lighthouse： 6.0.0
node: v12.18.0
npm: 6.14.4
google chrome: 83.0.4103.97

I execute it on the server, and the parameter value of the obtained Metrics is very different from the parameter value of the Metrics of the local computer, please take a look, why?

**my computer**
os : macOs  Mojave 10.14.4
lighthouse： 6.0.0
node:v11.11.0
npm: 6.9.0
google chrome: 83.0.4103.106

**The results show normal**
![image](https://user-images.githubusercontent.com/21286480/85261997-afc5d880-b49f-11ea-8a16-47c26e407c3a.png)

local execution results:
[kaiwu.lagou.com_2020-06-22_15-44-19.report.html.zip](https://github.com/GoogleChrome/lighthouse/files/4811866/kaiwu.lagou.com_2020-06-22_15-44-19.report.html.zip)

I don’t know why the same url is executed, but the difference in the results of the same command is so big. I have excluded the machine’s bandwidth network, CPU and other reasons.

Help me see this problem, thanks

**Comment by alaatarek95** [comment]
I am facing the same issue the performance gives error in both lighthouse and google page insights

**Comment by patrickhulce** [comment]
Thanks for filing @lvorcool!

I'm guessing the server is not located in the same place as your computer. Here's an example from my machine for that command which is probably what your server is seeing too.

![image](https://user-images.githubusercontent.com/2301202/85299937-89864580-b46b-11ea-96b2-36a1e26aafd5.png)

Please refer to the [variability documentation](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) on the different factors that will affect performance results as we're not able to troubleshoot individual environment issues.

As for the LCP problem, it's likely related but https://github.com/GoogleChrome/lighthouse/issues/10869 tracks waiting for NO_LCP that should also help here.

**Comment by Sharpshooter-Dublin** [comment]
The duplicate doesn't deal with the no_lcp error, if I'm not mistaken. I'm getting the same error with 'Largest Contentful Paint element – 0 elements found' even though I have .SVGs in <img> elements and a background image loaded via the url() fuction.

**Comment by patrickhulce** [comment]
NO_LCP portion of this is tracked by  #10869 as mentioned in https://github.com/GoogleChrome/lighthouse/issues/11003#issuecomment-647559561.

If you're not seeing NO_LCP but have a different issue with LCP, feel free to file a different issue :)
