### ISSUE TITLE
Improve Colorblind Score Shapes Usability 

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#11005]
The scoring shapes are made to be colorblind friendly, but we never say which shape means which score...

I think that the legend we already surface can be modified easily to provide this information, something like:
![image](https://user-images.githubusercontent.com/6392995/85316216-40d18b00-b471-11ea-83dc-ca03f8666cde.png)

This way it shows the 1.) color and 2.) shape at once.

**Comment by jimoong** [comment]
I think this is really great idea. Looks good to me.
