### ISSUE TITLE
cannot find module printer

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1101]
![image](https://cloud.githubusercontent.com/assets/39191/20848206/ed8ec7d6-b885-11e6-9dc1-bca2da02db82.png)

**Comment by wardpeet** [comment]
Can't reproduce, i'm on latest master, did a new tsc build just to be sure and no error

**Comment by paulirish** [comment]
I didn't do a tsc build, but I was expecting the helpful message of https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-cli/compiled-check.js to show up rather than this exception.

**Comment by wardpeet** [comment]
i'll have a look :)

**Comment by wardpeet** [comment]
I could reproduce this with the following case:
`cd lighthouse-cli;npm run build;rm printer.js;cd ..;`

now run lighthouse and you will see the error. The reason for this is that we only check if bin.js exists. `require('./compiled-check.js')('bin.js');` We could do this check for each js file in the cli but not sure if this will happen to our users.
