### ISSUE TITLE
Lighthouse reverted to 5.7.1 in Chrome Canary?? How it is possible?

### ISSUE THREAD

**Issue by afanjul** [GoogleChrome/lighthouse#11029]
I've got astonish today when (after using Chrome Canary for several weeks), now I see that the version of lighthouse was reverted to 5.7.1 (from 6.0), how is this possible? (Just yesterday it was 6.0 😳)
![image](https://user-images.githubusercontent.com/2046424/85845051-eb181e00-b7a3-11ea-8189-bdca337c44f1.png)

**Comment by brendankenny** [comment]
It's possible something went wrong, but I just checked 85.0.4183.0 on my Mac ([current as of today](https://omahaproxy.appspot.com/)) and I'm still seeing 6.0.0 there.

Can you give the version of Canary and the OS you're running? It's available either right above the screenshot you gave (in the `User agent (host)` box) or found by visiting `about:version`.

**Comment by patrickhulce** [comment]
Could be that the remote modules builder went down and LH used the fallback revision. We should probably update the fallback revision to use 6.0

**Comment by afanjul** [comment]
> Can you give the version of Canary and the OS you're running? It's available either right above the screenshot you gave (in the `User agent (host)` box) or found by visiting `about:version`.

I tested in Mac and Windows 10 with both 85.0.4183.0 (Official Build) Chrome canary (64-bit)

> Could be that the remote modules builder went down and LH used the fallback revision. We should probably update the fallback revision to use 6.0

That seems right, because now is 6.0 again... what is a surprise and new for me, is that I was thinking that the lighthouse engine/report was part of the "browser" and it's built inside it, not outside it with an external engine...😳

**Comment by connorjclark** [comment]
> That seems right, because now is 6.0 again... what is a surprise and new for me, is that I was thinking that the lighthouse engine/report was part of the "browser" and it's built inside it, not outside it with an external engine...😳

It's still built alongside Chromium, it's just set aside from the main distribution binary and downloaded lazily. We have no ability to push arbitrary releases ;)

**Comment by sqlpac** [comment]
Hi All.

Same issue, both Chrome 85.xx, 86.xx. Sometimes it is Lighthouse 6.0, sometimes Lighthouse 5.7.1. Just today, it has reverted once again to Lighthouse 5.7.1 - Version 86.0.4201.0 (Build officiel) canary (64 bits), it was Lighthouse 6.0 yesterday.

**Comment by lioralon326** [comment]
Same Here, 
Canary 86.0.4201.0, lighthouse 5.7.1

**Comment by patrickhulce** [comment]
Thanks @sqlpac and @lioralon326 I can reproduce as well.

Lighthouse needs to be built for every Canary revision and when it hasn't been built yet Chrome falls back to whatever was compatible with previous Chrome (which in this case is 5.7.1). It's possible it's just running behind, but it's also possible something went wrong and now it's stuck. Either way it's about time to bump the fallback revision to 6.0

@paulirish I think this issue is more common than we would like to believe :)

**Comment by sqlpac** [comment]
Sorry, I hate sending issues but I am solving my very very bad CLS scores (more than 1.5). It is a very new great metric to take in account (user's experience), never did it before (unexpected layout shifts surprising users). Congratulations for this new feature

**Comment by connorjclark** [comment]
ref #10883
