### ISSUE TITLE
Remove ambiguous words from link text disallow list

### ISSUE THREAD

**Issue by devngl** [GoogleChrome/lighthouse#11026]
I'm receiving this warning about a link not being descriptive enough. The weird thing is it only happens on some pages, but that same link is everywhere on the site.

On the other hand the text is "Inicio" which translates to "Homepage/Home", I wonder how is that not descriptive enough? 🤔

**Comment by patrickhulce** [comment]
Thanks for filing @devngl! The non-English words were contributed from the community, so there could definitely be room for improvement, and I'm certainly not much of an expert. 

Is it possible the connotation is different between spanish and portugese? I see they were added to add Portuguese support but were left out of spanish, but we didn't consider words that have different *web* meanings in different languages :/ Probably best to remove it either way?

**Comment by devngl** [comment]
Hello,

I think the main problem with the word is the multiple connotations you can give to it depending on the context. "Inicio" could translate to: start, home, the beginning, and probably more. The most common use I've seen in spanish sites is for "Home" or "Homepage", not sure about portuguese.

Maybe it should use one set of words depending on the lang attribute of the html tag?

**Comment by IgorWilbert** [comment]
@devngl @patrickhulce as a native Portuguese speaker, I think the main usage of the word "Início" is to make reference to "Home"  or "Homepage" of the website. I think the idea of using a set of words depending on the language would be better. I would like to take this issue if nobody is willing to work on it, but I think I'll need some guidance since I don't know the codebase very well.

**Comment by patrickhulce** [comment]
> Maybe it should use one set of words depending on the lang attribute of the html tag?

That's a neat idea! For now though, let's just remove `Início` from the audit as it sounds like it's not following the purpose of the audit in *any* language (Home links are fine, we don't want "Click here" style links).
