### ISSUE TITLE
Lighthouse audit from Incognito mode

### ISSUE THREAD

**Issue by parvathypurushothaman1** [GoogleChrome/lighthouse#11055]
**Summary**
I am trying to run lighthouse audit from my automation script using puppeteer.  I run my script in the incognito mode. When I am running lighthouse API, the audit is happening in the initial window, not the incognito window. Can someone please help?

```
report = await lighthouse(page.url(), {
        port: (new URL(page.browser().wsEndpoint())).port,
        output: 'json',
        logLevel: 'info',
        disableDeviceEmulation: true,
        onlyCategories: ['accessibility'],
        chromeFlags: ['--disable-mobile-emulation']
      }, config);
```

**Comment by patrickhulce** [comment]
Lighthouse CLI/node doesn't support creating the page it audits in an incognito context.

Why are you running it in incognito? Maybe there's a workaround for your use case. 

related https://github.com/GoogleChrome/lighthouse/issues/3837

**Comment by parvathypurushothaman1** [comment]
Thanks  @patrickhulce for the quick response.
We are running our scripts in inCognito mode to maintain the login sessions when executing the tests in parallel.

**Comment by patrickhulce** [comment]
@parvathypurushothaman1 I would just use different Chrome browser instances with different profiles (--user-data-dir flag) for that then. It would solve the Lighthouse problem and still keep all the sessions separate.

**Comment by parvathypurushothaman1** [comment]
Thanks for the suggestion. I will try that.

**Comment by theronpatrick** [comment]
there is now a chrome flag to start in incognito, so you should be able to accomplish this by adding

`chromeFlags: ['--incognito']`
