### ISSUE TITLE
LCP and TTI scores much higher in Mobile LH test. DevTools shows

### ISSUE THREAD

**Issue by nicpederson** [GoogleChrome/lighthouse#11051]
#### Provide the steps to reproduce
1. Run LH on hotelta.co
2. Desktop Performance scores 96
3. Mobile Performance scores 50-80 with abnormally high LCP & TTI
4. Verify actual LCP in Performance tab of DevTools (both Desktop & Mobile are very low)
  

#### What is the current behavior?
Score is drastically different on mobile LH test than what is seen on Desktop test and in DevTools

#### Environment Information
* Lighthouse version: 6.1.0
* Chrome version: Version 86.0.4190.2 (Official Build) canary (64-bit)
* Node.js version:
* Operating System: OSX 10.15.5

**Related issues**
Desktop LH score
![desktop-lh](https://user-images.githubusercontent.com/641886/86420942-034cd900-bc8d-11ea-836e-7c255399ce0a.png)

Mobile LH Score
![mobile-lh](https://user-images.githubusercontent.com/641886/86420989-211a3e00-bc8d-11ea-8f79-50e92169ca91.png)

Mobile DevTools - Performance 
![mobile-devtools](https://user-images.githubusercontent.com/641886/86421011-35f6d180-bc8d-11ea-9435-b8f58552b959.png)

**Comment by patrickhulce** [comment]
Thank you for taking the time to file an issue. Please refer the FAQs for the explanation here https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me

**Comment by nicpederson** [comment]
That link you sent me doesn't make sense in this case. Please see my edit above with images. I ran another DevTool test on a mobile device with "Slow 3G" AND "6x slowdown" throttling. Even with these extremely conservative settings, LCP is just over 3 seconds. LH tool consistently shows this metric MUCH higher (6-10 seconds). Tests were run back-to-back.

**Comment by patrickhulce** [comment]
The network requests in that trace do not look actually throttled, I'm guessing they're being pulled from the cache or something.

This is what the performance of that page looks like on a real phone with real throttling on a cold load (what Lighthouse is attempting to simulate).

https://webpagetest.org/lighthouse.php?test=200703_2E_5b54b5872838f30608af82b4103f7486&run=1

![image](https://user-images.githubusercontent.com/2301202/86478785-7fd4cb80-bd10-11ea-95c7-2a79481d48fe.png)

And this is the median of 5 runs I get in DevTools (differences between your machine and mine will be explained in the [variance docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md))

![image](https://user-images.githubusercontent.com/2301202/86478813-93803200-bd10-11ea-9432-5f8e685850ec.png)



Simulated throttling is meant to provide an approximation of the performance on a real phone from any device and is doing a satisfactory job here. If anything it's being too *lenient*.

**Comment by nicpederson** [comment]
Can you advise how to simulate these results in DevTools so that I can optimize appropriately? The Network and throttling were indeed set to the most conservative settings, so are there other settings I can adjust to simulate what LH is using to produce their results?

**Comment by patrickhulce** [comment]
The [throttling guide linked in the FAQ](https://github.com/GoogleChrome/lighthouse/blob/159cb8428cfb91452b1561ecaa0e8415e9eba742/docs/throttling.md#how-do-i-get-packet-level-throttling) is the extent of our documentation on more reproducing more accurate throttling locally. The throttling in DevTools unfortunately does not accurately throttle HTTP/2 or HTTP/3 connections, so you'll need to use the "packet-level throttling" techniques mentioned there if you plan to test HTTP/2 or HTTP/3 sites (this inaccuracy is just one of the reasons Lighthouse made the transition to simulated throttling).

http://webpagetest.org/lighthouse can also provide a reliable test environment if the page is web accessible.

**Comment by nicpederson** [comment]
ok.. Can you explain what LH is showing when you hit "View Trace" in the LH results? It creates a new timeline session in the Performance tab. Shouldn't this data match what LH is showing me? Otherwise, it seems pretty useless. It would be very helpful if I could actually view the trace that produced the results LH is showing me. That would remove the need for me to reproduce on my own end.

**Comment by patrickhulce** [comment]
It's showing you what Lighthouse saw, not what was [simulated](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md). It's on the backlog to warn about this discrepancy and link to the explanations I've already posted here.

https://github.com/GoogleChrome/lighthouse/issues/9971 has more discussion on this :)
