### ISSUE TITLE
Repeated words used. 

### ISSUE THREAD

**Issue by Devraj06** [GoogleChrome/lighthouse#11058]
In Light house report  Accessibility>>Tables and lists>> Repeated words used in description. 
![LHERROR](https://user-images.githubusercontent.com/5065043/86591805-e75c7680-bfaf-11ea-89b1-0e245ec34458.JPG)

**Comment by patrickhulce** [comment]
Thanks for filing @Devraj06! Interested in a PR? 😃  It's a great first issue :)

**Comment by simeon4real** [comment]
Can I send a PR @patrickhulce ?

**Comment by robintom** [comment]
Can I give this a try ? @patrickhulce Could you please assign this to me?

**Comment by patrickhulce** [comment]
Go for it @robintom ! :)

**Comment by robintom** [comment]
@patrickhulce I have submitted a PR #11099 . Please do have a look and let me know in case of any issues.

**Comment by Devraj06** [comment]
> Thanks for filing @Devraj06! Interested in a PR? 😃 It's a great first issue :)

Sure!! why not Patrick. Love to 👍

**Comment by patrickhulce** [comment]
Thanks for offering @Devraj06 , but I think #11099 fixed this already. Next time ;)
