### ISSUE TITLE
"Defer offscreen images" triggers for images with `loading=lazy`

### ISSUE THREAD

**Issue by cramforce** [GoogleChrome/lighthouse#11063]
#### Provide the steps to reproduce
1. Run LH on https://www.industrialempathy.com/posts/design-docs-at-google/

#### What is the current behavior?

LH recommends to "Defer offscreen images" even though the images have lazy loading activated via the attribute.

#### What is the expected behavior?

Chromium's built-in lazy loading should be synced with LH in terms of thresholds that trigger loading.

#### Environment Information
* Affected Channels: Stable
* Lighthouse version: 5.7.1
* Chrome version: 83.0.4103.116

**Comment by patrickhulce** [comment]
Thanks @cramforce! We fixed this in 6.0 which is landed in M84

See https://github.com/GoogleChrome/lighthouse/issues/10259 for the full story :)
