### ISSUE TITLE
Confusing evaluation heading: "Address bar matches brand colors"

### ISSUE THREAD

**Issue by dandv** [GoogleChrome/lighthouse#1106]
When generating a report on [this URL](https://www.reservationcounter.com/hotels-pwa/show/152625/golden-nugget-hotel-and-casino/), Lighthouse suggests that the address bar matches the brand colors:

![image](https://cloud.githubusercontent.com/assets/33569/20856575/d479a2ac-b8c6-11e6-96b0-ac6f59028878.png)

In actuality, [the site's manifest.json](https://www.reservationcounter.com/manifest.json) has:

```
"background_color": "#1C3A6A",
"theme_color": "#FFFFFF"
```

The HTML `theme-color` is matched by the manifest's `background_color`, but the manifest `theme_color` is different (#FFFFFF, and Android renders the notification area in grey color).

![image](https://cloud.githubusercontent.com/assets/33569/20856698/981d3d92-b8ca-11e6-98e5-c45322c71875.png)

Related: #25.

**Comment by paulirish** [comment]
Ah we only care that it's defined, but we don't need anything to "match". Yes. agree the wording isn't ideal.

Maybe...

> Address bar theming is defined

> Address bar theme color applied

**Comment by paulirish** [comment]
@kaycebasques wdyt on the name here. we just want these colors defined somewhere. that's it. And honestly we have no idea what your REAL brand colors are. :)

**Comment by pardismusic** [comment]
hi

i uesd these 

<meta name="theme-color" content="#228f21">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

and this inside my style : 

{"theme_color": "#228f21" ...}

but i will get Address bar does not match brand colors (The browser address bar can be themed to match your site.)

what i have to do for fixing this ? 
this is my website address : pardis music . me

**Comment by patrickhulce** [comment]
@pardismusic have you read the [documentation](https://developers.google.com/web/tools/lighthouse/audits/address-bar)? Do you have the meta tag?

**Comment by pardismusic** [comment]
> 
> 
> @pardismusic have you read the [documentation](https://developers.google.com/web/tools/lighthouse/audits/address-bar)? Do you have the meta tag?


Hi 

yes its 👍 
<meta name="theme-color" content="#228f21">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

**Comment by pardismusic** [comment]
> 
> 
> @pardismusic have you read the [documentation](https://developers.google.com/web/tools/lighthouse/audits/address-bar)? Do you have the meta tag?


hi
yes i used these 👍 
< meta name="theme-color" content="#228f21" >
< meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" >

**Comment by patrickhulce** [comment]
You don't have a manifest @pardismusic.

![image](https://user-images.githubusercontent.com/2301202/49388678-17fc7000-f6ea-11e8-90dc-1cf140bd5ca8.png)

https://developers.google.com/web/tools/lighthouse/audits/manifest-exists#recommendations

**Comment by pardismusic** [comment]
> 
> 
> You don't have a manifest @pardismusic.
> 
> ![image](https://user-images.githubusercontent.com/2301202/49388678-17fc7000-f6ea-11e8-90dc-1cf140bd5ca8.png)
> 
> https://developers.google.com/web/tools/lighthouse/audits/manifest-exists#recommendations

i really didnt undrestand how to make manifest

is there any video to showing that ? or any site example

**Comment by brendankenny** [comment]
fixed in #6494!
