### ISSUE TITLE
How to run multiple passes and tailor response to reduce size

### ISSUE THREAD

**Issue by emexelem** [GoogleChrome/lighthouse#11077]
**Summary**

Hi, 
thanks for this great tool.
We are starting to use lighthouse programmatically and want to run it multiple times on the same url and compute some averages as we observed some variance in the results.
The first naive option i implemented is to run LH multiple time sequentially, it works fine but
- the aggregated responses is quite big (1.5MB for 5 runs)
- i noticed [a pass object in the configuration](https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md#passes-object ) that allows loading the page multiple times

Do you have any recommendations and examples on how running LH multiple times on the same url, using passes or something else?
How can we strip some parts of the response, such as screenshot-thumbnails? I guess we can post process the response to remove the part that we don't need before returning it to the caller, but maybe there's something in LH config to not return these thumbnails at first, while keeping the performance scores that we're interested in?

Thanks,
MX

**Comment by patrickhulce** [comment]
Have you already read [through the docs](https://github.com/GoogleChrome/lighthouse/blob/3acd4035e4e68d3fdd87b3e98c96ad9d4639e0f0/docs/variability.md#run-lighthouse-multiple-times)? 

Passes is not meant for collecting multiple times. You'll only ever get 1 set of performance results no matter how many passes you make.

As for stripping parts of the response, that's really up to you. Just strip out whatever you don't want to save. If you don't care about screenshots, remove them :)

**Comment by exterkamp** [comment]
Closing b/c answered 👍
