### ISSUE TITLE
Lighthouse"  "Performance" tabs data are not coming  it is showing always 0

### ISSUE THREAD

**Issue by pankaj89chauhan** [GoogleChrome/lighthouse#11070]
![image](https://user-images.githubusercontent.com/67691103/86940382-61cbf880-c160-11ea-8fe3-2d36b6c2c898.png)

**Comment by patrickhulce** [comment]
Then the page is getting a 0 score for Performance :)

Following the advice in the opportunities to improve the metrics will raise the score.

**Comment by pankaj89chauhan** [comment]
removed the opportunity error but same issue

**Comment by patrickhulce** [comment]
> removed the opportunity error but same issue

You've made every single one of the opportunity audits pass and you're still getting a 0 for performance? Then please fill out the complete information in the [bug report template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) *with the URL* so we can take a look.
