### ISSUE TITLE
DevTools yields very different result from CLI

### ISSUE THREAD

**Issue by bemyhre** [GoogleChrome/lighthouse#11075]
#### Provide the steps to reproduce
1. Run cli lighthouse on https://ramshacklepantry.com/ and/or https://ramshacklepantry.com/bacon-wrapped-grilled-sweet-potato-fries/ (one has an image an LCP and the second a paragraph element) and view render screengrabs compared to elements.
2. Perform the same in Canary Lighthouse Performance and compare LCP to trace, both the actual LCP timing marker and the frames.
  

#### What is the current behavior?

In each case review the visual render vs the LCP, they don't match up. Similar results (particularly on image) if you run this in LH in Canary and view the trace.

Paragraph element is LCP: 

![image](https://user-images.githubusercontent.com/5705561/87034681-de38f880-c1ad-11ea-8f17-19a03301666e.png)

Image Element (the largest image) is LCP: 

![image](https://user-images.githubusercontent.com/5705561/87034721-f14bc880-c1ad-11ea-812a-2143120d98ad.png)

Here is from Canary LH:

![image](https://user-images.githubusercontent.com/5705561/87035562-24428c00-c1af-11ea-8148-9383b4a2232b.png)

And the Trace:

![image](https://user-images.githubusercontent.com/5705561/87035641-3c1a1000-c1af-11ea-8056-191268c0e18a.png)

#### What is the expected behavior?

The LCP to coincide with the frames or visual experience. I have noticed similar things with the LCP on several websites where it appears to be measuring much slower than actuality (even when throttled), even when simple, non-formatted, text elements that are right in WP's the_content.

#### Environment Information
* Affected Channels: CLI, DevTools, Canary -->
* Lighthouse version: Lighthouse 6.1.0 for Canary and 6.1.1 for cli
* Chrome version: 83.0.4103.116 and canary Version 86.0.4197.0
* Node.js version: v12.16.3
* Operating System: Catalina 10.15.5 

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @bemyhre! Sorry I'm a little confused what the expectation here is. 

Are you saying CLI is correct and Canary DevTools is wrong? Or that everything is wrong? If you think everything is wrong what do you think the correct value is and what tool told you it was this value?

Note that the trace and associated screenshots *won't* match the metrics when using simulated throttling. This is expected and by design. See #9971 for discussion and what we plan to do about it. If this was the only problem, does it still occur with applied throttling?

**Comment by bemyhre** [comment]
@patrickhulce thanks for the response!

It appears to be an issue in CLI, the GPSI tool, and Canary. Everything. 

Based on what you are saying, it looks like the expected behavior is that when you click the 'view trace' button, the performance trace FROM the lighthouse report runs without throttle. Understood. 

When, however,  run this directly from the performance tab in Canary (or most recent live version) WITH it throttled at Fast 3g and 4x slow, it renders both in the frames and the Timings metric for FCP as much faster than pulls in any of the normal lighthouse methods (GPSI, cli, dev tools)

![image](https://user-images.githubusercontent.com/5705561/87047962-c61ea480-c1c0-11ea-80f1-50aa16780238.png)

I am using my site as an example, but I work several other food sites (who tend to have pretty similar layouts/themes/etc) and I see the LCP running super slow for many folks. Folks that I know are running fast servers and where it might be rendering something as simple as a paragraph element as the LCP. I can't speak to the exact specifics for them, but what I am seeing on my sight is that the LCP metric that shows on our normal tools doesn't seem to match up with the actual user experience, even when throttling.

**Comment by patrickhulce** [comment]
Gotcha thanks for explaining.

Something does seem to be going on with Canary DevTools and PSI, not sure what's happening there. We'll have to dig in.

The CLI seems to be working exactly as expected though. Simulated throttling certainly isn't perfect, but it's pretty darn close in this case, and I can't reproduce anything here very out of the ordinary. Explanations below.

Lighthouse isn't trying to tell you the performance as DevTools throttling estimates it, it's trying to tell you how it works on a real phone, so let's check that.

[WebPageTest says ~4.1s](https://webpagetest.org/result/200709_BM_84a2b7f5605920eb9057805399987098/), that's our source of truth.

![image](https://user-images.githubusercontent.com/2301202/87057358-60d0b080-c1cc-11ea-9978-f35f53e1d7e4.png)


DevTools throttling also isn't perfect and doesn't correctly throttle HTTP/2 (which this site and many other sites use at this point). Still, I see LCP of ~3.1s there.
![image](https://user-images.githubusercontent.com/2301202/87056116-cc198300-c1ca-11ea-9418-e0663bb15fa3.png)

10 runs of Lighthouse CLI locally for me yield LCP of 3.9s-4.8s and a median of 4.5s.
Simulated throttling overestimates LCP by ~0.4s and DevTools throttling underestimates LCP by ~1s, couldn't hope for much better than that. (Not to mention local Lighthouse is actually *underestimating* the other main-thread based metrics compared to real phone so the score overall is still favorable)
![image](https://user-images.githubusercontent.com/2301202/87056659-90cb8400-c1cb-11ea-8a33-af0f84a01471.png)

**Comment by bemyhre** [comment]
Thanks so much for looking. Also, I didn' know webpagetest was the source of truth. Good to know!

**Comment by patrickhulce** [comment]
> I didn' know webpagetest was the source of truth. Good to know!

I'll caveat this with WebPageTest metrics isn't *always* in sync with Lighthouse metric definitions (it should be generally), but the source of truth is definitely how it works on an *actual* phone and WebPageTest has those freely available for testing :)

**Comment by patrickhulce** [comment]
I'm no longer able to reproduce this DevTools/CLI discrepancy issue in latest Chrome. 

![image](https://user-images.githubusercontent.com/2301202/93271451-e8144480-f778-11ea-8355-dd19548ef182.png)

vs.

![image](https://user-images.githubusercontent.com/2301202/93271640-653fb980-f779-11ea-9fe3-dc9e92c74c60.png)


We'll consider this closed without a consistent repro.
