### ISSUE TITLE
PageSpeed giving ERR_CONNECTION_FAILED Only on production

### ISSUE THREAD

**Issue by david-lorenzo88** [GoogleChrome/lighthouse#11081]
We have our development page giving correct score on page speed insights.

https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fdev.techtitute.com

But our production page always returns scan error:
```
Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)
```

https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fwww.techtitute.com

The strange thing is that web.dev (which also uses Lighthouse under the hoods) is giving correct score for both pages, also gtmetrix, pingdom and Chrome dev tools Lighthouse tab.

Both pages have the exact same code, both are running on windows Azure App Service. The only differences are:

On production we are injecting Google Tag Manager scripts with analytics, fb pixel, linkedin and others (we have tested disabling this scripts and nothing changes, it continues to give us error in production and correct score in development).

Also we have an azure traffic manager to distribute traffic based on geolocalization of the user (Latam and Rest of the World).

We have tried to simulate this geolocalization environment with another domain in dev and page speed gives us correct score, while in production domain continues the error.

What would you think could be the problem of production page giving that error? I don't see too much differences except for the domain name itself...

Thank you!!
David

**Comment by patrickhulce** [comment]
> The strange thing is that web.dev (which also uses Lighthouse under the hoods) is giving correct score for both pages

More than that web.dev actually uses the PSI API itself, so they're identical in every way other than the geographic test location. web.dev nearly always runs in North America.

As this is the only difference, my best guess is that the server is rejecting requests with the PSI user agent from specific geographic areas.

**Comment by david-lorenzo88** [comment]
Yes we finally solved it by changing azure traffic manager routing type from Geographic to Performance. In this casi is Azure itself which select the optimal endpoint based on latency tables between DNS servers and Azure region where you have the differents endpoints.
By doing this change, google page speed insights is now returning correctly the score.

Thanks all for the support!

David
