### ISSUE TITLE
First Contentful Paint Score exceeds what

### ISSUE THREAD

**Issue by corey-bailey** [GoogleChrome/lighthouse#11086]
#### Provide the steps to reproduce
1. Run lighthouse - performance only - desktop for url:  https://insightcr.manheim.com/cr-display?conditionOrderId=19451362&simpleCr=false
  

#### What is the current behavior?
First Content Paint and First Meaningful Paint metrics exceed the time of the trace took.    

#### What is the expected behavior?
Looking at the Trace i would think that both metrics would b much lower.

#### Environment Information
* Affected Channels: Dev Tools
* Lighthouse version: Lighthouse 5+
* Chrome version: Version 83.0.4103.116 (Official Build) (64-bit)
* Node.js version: 10+
* Operating System: Mac and Linux

**Related issues**

**Comment by connorjclark** [comment]
We simulate a slower device.

See the [FAQ](https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me) and [throttling documentation](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).

**Comment by corey-bailey** [comment]
i will read the manual :)  thanks!
