### ISSUE TITLE
Lighthouse observedLoad smaller than firstMeaningfulPaint or interactive

### ISSUE THREAD

**Issue by AlinaKIRIC** [GoogleChrome/lighthouse#11084]
Hi! I am using Lighthouse 6 CLI and it has some strange behavior. Somehow Fulload of the page(observedLoad) more than firstMeaningfulPaint or interactive. I checked, observedLoad same as in Developer tool, so this is incorrect value if FirstMeaningfulPaint or interactive more then time of full load.

Probably it can be problem of throttling (I use simulate method).  Can you please help me, how to create scenario for correct metrics.

I am checking site https://youtube.com and use folowing arguments --only-categories=performance,pwa  --emulated-form-factor=mobile  --max-wait-for-load 60000

**Comment by connorjclark** [comment]
Can you share your the resultant LHR (the json)?

If simulating, `observedLoad` is what Chrome saw and all the `firstMeaningfulPaint`, etc are simulated in our Lantern simulation. You shouldn't compare the two. Only the other `observed*` values are comparable with `observedLoad`.

**Comment by patrickhulce** [comment]
@AlinaKIRIC as Connor explained, this is expected behavior for simulated throttling (which your command is using).

See the [FAQ](https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me) and [throttling documentation](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).

**Comment by AlinaKIRIC** [comment]
Hi! Thanks for your reply, I just started to using lighthouse and have lot of questions, I hope you can help me with my misunderstanding=)

I compare all metrics in json, because of that I got some misunderstanding. I need to check all metrics in case of full page load, but I am not sure how to do that in correct way with lighthouse. Can you please clarify me some points:
1. If I understand you correctly, all metrics without observe is metrics with simulation. But where I can find data about full load in case of simulation(we have only observedLoad). Maybe I can calculate it from some exist metrics. 
Also we have all metrics what i need with observed(FirstContentfulPaint,FirstMeaningfulPaint,LargestContentfulPaint) but not interactive. Maybe it can be also calculated somehow from exist metrics. (ressimulate.json in attach)
![image](https://user-images.githubusercontent.com/68123547/87218620-1af72200-c35d-11ea-8292-154a3cce02b8.png)
2. If I use throttling method provided(To check emlation of device but without throttling) for checking results in case of observedLoad metric from Json file, I also got some strange behavior:
a. Looks like I have all throttling settings in Json, need I disable it or it doesn't work with this method?
b. In Json file, metrics also strange.    "observedLoad": 1205,    "interactive": 1514, "largestContentfulPaint": 1224. So interactive and largestContentfulPaint somehow higher than full load, I am not sure that this is correct. (resprovided.json in attach)
![image](https://user-images.githubusercontent.com/68123547/87218628-264a4d80-c35d-11ea-9983-66538723fcd0.png)
[json_examples.zip](https://github.com/GoogleChrome/lighthouse/files/4906412/json_examples.zip)

Thanks in advance for your help=)

**Comment by patrickhulce** [comment]
I think there's a misunderstanding about what the metrics represent.

`load` is the load event in the browser, which can often fail to coincide with anything meaningful from the user's perspective, especially on script-heavy pages.

The other metrics you've highlighted represent important moments in the user experience which can certainly occur after `load` (in the case of TTI *usually* after `load`). You can read about [each of their definitions in the web.dev docs.](https://web.dev/metrics/)

**Comment by oshell** [comment]
1 year later, but I have exactly the same questions. the answers given here were not really helpful.

in the results of lighthouse we have metrics like `observedFirstContentfulPaint` and it's counterpart `firstContentfulPaint`
for `observedLoad` and `observedDomContentLoaded` however, we do not have any counterpart.

is there any way to get values for `load` and `DomContentLoaded` from lighthouse api?

**Comment by patrickhulce** [comment]
> is there any way to get values for load and DomContentLoaded from lighthouse api?

Use `--throttling-method=devtools`. If by "lighthouse API" you're referring to PageSpeed Insights, then no, it is not possible to get those values, nor do we encourage any weight being given to them as performance indicators.
