### ISSUE TITLE
Preload and CSP conflict

### ISSUE THREAD

**Issue by peterpeterparker** [GoogleChrome/lighthouse#11093]
#### Provide the steps to reproduce
1. Run LH on https://deckdeckgo.com

#### What is the current behavior?

When I run a Lighthouse analysis on our app https://deckdeckgo.com the following errors are reported:

```
A preload <link> was found for "https://deckdeckgo.com/build/p-04ffa570.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
```

Indeed the `<link/>` does not contains the attribute `crossorigin` but it is a file of the app served on the same domain.
Moreover, I tried to specify this `crossorigin`  attribute  but it ain't modified the report.

```
<link rel="modulepreload" href="/build/p-04ffa570.js">
```

On the other hand, we do have a Content Security Policy specified in our header and if I do remove it (for test purpose), the Lighthouse results does not display the error.

Finally, if I observe the Network Tab of the Chrome debugger, I do notice that these scripts indicated as being in error are actually the first scripts load by the browser.

That's why I tend to think that it may be a mistake of the report. I can obviously be totally wrong, it's an assumption.

Thank you in advance for your time.

#### What is the expected behavior?

No conflicts between `preload` links and CSP.

#### Environment Information
* Chrome version: 83.0.4103.116

**Related issues**

Related issue and how to reproduce locally: https://github.com/deckgo/deckdeckgo/issues/780

Repo: https://github.com/deckgo/deckdeckgo/tree/master/studio

**Comment by patrickhulce** [comment]
Thanks for filing @peterpeterparker ! I can't reproduce this in Lighthouse 6.1.0 but I can in 5.7.1, so I think it's likely been fixed. You might have to wait awhile to get it in stable Chrome but you can use the CLI in the meantime `npm install -g lighthouse`

**Comment by peterpeterparker** [comment]
I spent quite some time debugging before actually opening the issue, almost a relief to hear it was actually one.

Thank you for the quick answer @patrickhulce and for the "workaround" with the CLI, that does the job.
