### ISSUE TITLE
'Page.getInstallabilityErrors' wasn't found

### ISSUE THREAD

**Issue by brntsllvn** [GoogleChrome/lighthouse#11102]
#### Provide the steps to reproduce
Run LH on https://www.zillow.com/ 
(Note: via AWS Lambda through VPC)

#### What is the current behavior?
Fails to produce LH performance report. Exits immediately. 

{ Error: Protocol error (Page.getInstallabilityErrors): 'Page.getInstallabilityErrors' wasn't found
    at Function.fromProtocolMessage (/opt/nodejs/node_modules/lighthouse/lighthouse-core/lib/lh-error.js:129:19)
    at callback.resolve.Promise.resolve.then._ (/opt/nodejs/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:124:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  protocolMethod: 'Page.getInstallabilityErrors',
  protocolError: '\'Page.getInstallabilityErrors\' wasn\'t found',
  friendlyMessage: undefined }

#### What is the expected behavior?
LH performance report

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 6.1.1
* Chrome version: Chromium 75.0.3738.0
* Puppeteer-core 1.14.0
* Node.js version: v10.20.0
* Operating System: linux 4.14.165-102.205.amzn2.x86_64 (this is admittedly opaque...)

#### More info via the DevTools Protocol debug endpoint...
* Browser: HeadlessChrome/75.0.3738.0   
* Protocol-Version: 1.3   
* User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3738.0 Safari/537.36  
* V8-Version: 7.5.59   
* WebKit-Version: 537.36 (@08744312109bd6daf5a2fc396fa15b07f6d2b0a6)

#### Misc...
* I am able to run a LH performance report in incognito mode manually in the browser without issue (stated version is 5.7.1 which is not available on npm)
* [Page/#method-getInstallabilityErrors](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-getInstallabilityErrors) marked as EXPERIMENTAL 
* Page.getInstallabilityErrors not included in [1.3 DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/1-3/Page/)
* Recent nearby change (reverting to an earlier version does not solve the problem) https://github.com/GoogleChrome/lighthouse/issues/10318

**Comment by connorjclark** [comment]
That Chrome is too old for LH 6.1.1 Can you update in AWS lambda?

**Comment by patrickhulce** [comment]
Also [don't run on lambda](https://github.com/GoogleChrome/lighthouse/blob/54ea6d594ea3cabd450ad85f443038287a5f1e05/docs/variability.md#run-on-adequate-hardware) :)

**Comment by brntsllvn** [comment]
> That Chrome is too old for LH 6.1.1 Can you update in AWS lambda?

Not easily. Is there a version of LH that is compatible with Chromium 75.0.3738.0?

**Comment by patrickhulce** [comment]
v5.1.0 should work with 75

**Comment by brntsllvn** [comment]
> Also [don't run on lambda](https://github.com/GoogleChrome/lighthouse/blob/54ea6d594ea3cabd450ad85f443038287a5f1e05/docs/variability.md#run-on-adequate-hardware) :)

ah, good to know!

**Comment by brntsllvn** [comment]
> v5.1.0 should work with 75

Confirmed: v5.1.0 works with 75 

For my benefit: is there a LH to chromium compatibility mapping available anywhere? Thx.

**Comment by patrickhulce** [comment]
There is not such a mapping anywhere I'm aware of. If you find anyone who has created one we'd be happy to add it :)
