### ISSUE TITLE
Service Worker detection fails on 3G

### ISSUE THREAD

**Issue by amedina** [GoogleChrome/lighthouse#1111]
Running LH on a 3G connection often yields a negative result regarding the detection of the SW registration. See attached snapshot. The SW of same site on faster connections is detected properly.

![lh-gin3g-nothrottling](https://cloud.githubusercontent.com/assets/506089/20897749/7e16e28a-bad8-11e6-8b10-2aad1e7cb730.png)

**Comment by wardpeet** [comment]
Url to reproduce on?
Not sure but could it be something to do with our trace stopping after xx seconds. As you can see we couldn't even measure tti

**Comment by ebidel** [comment]
Hey @amedina what version of LH did you run this with? Looks like an older version. Can you also provide the URL you tested against?

**Comment by ebidel** [comment]
Marking this as a dupe of #1815.
