### ISSUE TITLE
Incorrectly flag lang="zxx" as invalid

### ISSUE THREAD

**Issue by Blightwidow** [GoogleChrome/lighthouse#11111]
#### Provide the steps to reproduce
1. Run LH on https://www.thefork.com/restaurant/moom-mam-r546835
  

#### What is the current behavior?
Flag `<span lang="“zxx”">Yums</span>` as invalid language

#### What is the expected behavior?
`<span lang="“zxx”">Yums</span>` is a valid [non-linguistic](https://www.w3.org/International/questions/qa-no-language) attribute value. It indicates that this is a made up word and should not be translated for example.

#### Environment Information
* Lighthouse version: 6.1.0 on web.dev

**Comment by patrickhulce** [comment]
Thanks for filing @Blightwidow! But lighthouse is correct here. `zxx` is a valid language as you point out but `“zxx”` with directed quotations is *not*. Change the span to `<span lang="zxx">Yums</span>` and it passes (example: https://melodic-class.glitch.me/lang-zxx.html)
