### ISSUE TITLE
Throttling config differences with newer version 6.

### ISSUE THREAD

**Issue by DinakarC-practise** [GoogleChrome/lighthouse#11114]
Hello lighthouse,
After upgrading chrome browser to 84 I have ran some lighthouse tests and seen a huge difference in TTI score from 17 sec to 5 sec. I see the difference in throttling configurations as per the screenshot
![Screen Shot 2020-07-16 at 2 12 26 PM](https://user-images.githubusercontent.com/50386746/87708814-4c168e80-c771-11ea-8447-8049f5b552e3.png)
. I tried to research for the reason behind these config changes. Please redirect me to the exact reason for the config changes and I want to know what throttling config to be followed if these configs keep on changing. 
TTI scores
![Screen Shot 2020-07-16 at 2 35 29 PM](https://user-images.githubusercontent.com/50386746/87709028-a283cd00-c771-11ea-9eca-321dc74bd075.png)

**Comment by patrickhulce** [comment]
Thanks for filing @DinakarC-practise . There was a bug for desktop throttling profiles not selecting the right settings. This was fixed in Lighthouse 6.0. See #10315 for details.
