### ISSUE TITLE
Lighthouse functionality 

### ISSUE THREAD

**Issue by vishal-lko** [GoogleChrome/lighthouse#11127]
I was actually looking into some tool which can browse through the different pages in the application and provide me:
 Page Load time
 Browser interaction time (time taken to load css, js and images)
 Server error rate (any pages responding with HTTP 5XX code)
 JS errror rate (any pages responding with javascript error in the browser console)

Can this tool help me get that information?

**Comment by patrickhulce** [comment]
Yes this information is available in the Lighthouse report. This and all the other information available in the report is [covered in the documentation](https://web.dev/learn/#lighthouse).
