### ISSUE TITLE
full-page-screenshot: handle elements beyond MAX_SCREENSHOT_HEIGHT

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#11121]
ref https://github.com/GoogleChrome/lighthouse/pull/10716#issuecomment-657904592 and #11118 

i made https://output.jsbin.com/koqamuh/4/quiet as a test page for us. it has a (CSS) pixel ruler running down the side.

Here's a report of the page: https://marked-cable.surge.sh/color-contrast-over16000px-koqamuh.html

The elem screenshots start failing between 6200 and 6300 px

![image](https://user-images.githubusercontent.com/39191/87830901-f4daf180-c836-11ea-9c81-19e11c15149f.png)

---------

#### DPR stuff..

6300  is  roughly 16384 / 2.625.. so  it's to do with some DPR adjustments.. (I'm capturing this on my imacpro with a native dpr of 2.)

FWIW i tried removing the `/ dpr` in maxScreenshotHeight: 
https://github.com/GoogleChrome/lighthouse/blob/06d3e1b8d69c9b7eb0a9b94c08632b097eb1eeec/lighthouse-core/gather/gatherers/full-page-screenshot.js#L75

and after doing that, [it cut out](https://marked-cable.surge.sh/color-contrast-over16000px-koqamuh-nodprdivisor.html) at 16300 . (right before 16384, the real max)

![image](https://user-images.githubusercontent.com/39191/87831174-8c404480-c837-11ea-93dd-07f1bd5c1243.png)

that much seems good.
of course, the placement of the markers are off because of some other dpr math I didnt account for.

**Comment by connorjclark** [comment]
> that much seems good.

I did the same, and I noticed that while yes, the highlight now shows for >6200px, the image itself is _repeating_ the content starting at 6200px. I tried tweaking multiple parameters in the screenshot protocol method, but nothing resulted in an image that didn't repeat (w/o tweaking the DPR, which as you pointed out, we probably don't want to do).

It seems the original behavior is what we want, except for in the report, we should simply not show the element image if out of bounds of screenshot?

**Comment by patrickhulce** [comment]
> w/o tweaking the DPR, which as you pointed out, we probably don't want to do

I'm still a little unclear why this is off limits but making a page with a 16000px tall scroll window is fine 🤔 

In my limited experience, infinite scroll mutations and visibility observers that mutate are *far* more common than fundamental changes to the page based on DPR-specific art direction media queries.

The most likely repercussion of a DPR change to me seems to be a lower resolution image being swapped in, which would likely look pretty similar on a super low quality JPEG screenshot like ours even if our logic manages to wait for the new one to load in off the network.

**Comment by paulirish** [comment]
I believe this is fixed after #11538 and #11688. cc @connorjclark for confirmation
