### ISSUE TITLE
Extension Error: Unexpected token c in JSON at position 0

### ISSUE THREAD

**Issue by sesn** [GoogleChrome/lighthouse#1112]
**Lighthouse Version**: 1.2.2
**Chrome Version**: 54.0.2840.98
**Error Message**: Unexpected token c in JSON at position 0
**Stack Trace**:
 ```SyntaxError: Unexpected token c in JSON at position 0
    at JSON.parse (<anonymous>)
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:8168:31)```

**Comment by ebidel** [comment]
Can you post the url you were testing against?

**Comment by brendankenny** [comment]
I believe this was also #1028, which is fixed if you run Chrome 55 or later (details in that issue).
