### ISSUE TITLE
Adding preload to font resources causes error on Pagespeed report

### ISSUE THREAD

**Issue by tomasts248** [GoogleChrome/lighthouse#11130]
This is the error:
Warnings:

> Lighthouse was unable to automatically check the font-display value for the following URL

this is the code in header:
`<link rel="preload" href="fonts/Fontname-Light.woff2" as="font" type="font/woff2" crossorigin>
`

**Comment by patrickhulce** [comment]
Thanks for filing @tomasts248 but this isn't an error, and doesn't require any action. It's just a warning telling you that Lighthouse couldn't automatically check the values from that URL. It does not impact any score or the failure state of the audit. In some situations Lighthouse just won't be able to to get the content of certain stylesheets in a timely manner.
