### ISSUE TITLE
Assets from gstatic.com & googleapis.com should also be excluded from audit results

### ISSUE THREAD

**Issue by carl-alberto** [GoogleChrome/lighthouse#11134]
#### Provide the steps to reproduce
1. Run LH on https://developers.google.com/speed/pagespeed/insights/?url=games.lol (or any sites that has gstatic.com or googleapis.com assets)

#### What is the current behavior?
Google assets from gstatic.com or googleapis.com do no follow their own audit rules and being flagged in Lighthouse

![Screen Shot 2020-07-21 at 8 34 57 PM](https://user-images.githubusercontent.com/5098765/88056690-8a59e680-cb93-11ea-83c2-3539bc40b3f0.png)

![Screen Shot 2020-07-21 at 8 49 06 PM](https://user-images.githubusercontent.com/5098765/88057385-98f4cd80-cb94-11ea-824a-2c0e5aab0c51.png)

#### What is the expected behavior?
As per issue https://github.com/GoogleChrome/lighthouse/issues/6140, Google assets do no follow their own audit rules and should be excluded, but gstatic.com & googleapis.com seems not to be included on the excluded assets raised from that GH issues,  should they also be excluded too?

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 6.1.0

**Related issues**
 https://github.com/GoogleChrome/lighthouse/issues/6140
Possibly also related:
https://github.com/GoogleChrome/lighthouse/issues/4516
https://github.com/GoogleChrome/lighthouse/issues/9256
https://github.com/GoogleChrome/lighthouse/issues/8955

**Comment by brendankenny** [comment]
> As per issue #6140, Google assets do no follow their own audit rules and should be excluded, but gstatic.com & googleapis.com seems not to be included on the excluded assets raised from that GH issues, should they also be excluded too?

Hi @carl-alberto, I think maybe the discussion in #6140 was misconstrued? The decision was not to exclude assets from gstatic from the Lighthouse report, it was to make sure they could be hidden by unchecking the "Show 3rd party resources" checkbox to see things from just the origin being tested. Resources from Google aren't treated any differently than resources from anywhere else for the render-blocking audit.

As for the checkbox, I'm not able to reproduce the behavior you have in your screenshot when I run against that site in DevTools. The checkbox is available and correctly filters out the resources from gstatic and cloudfront if unchecked.

<img width="702" alt="render-blocking Lighthouse audit screenshot" src="https://user-images.githubusercontent.com/316891/88064513-610c6c80-cb39-11ea-945d-5dc23c979ef8.png">

**Comment by carl-alberto** [comment]
Thanks for the reply @brendankenny

any reason why the checkbox for "show 3rd-party resources" enabled only from the `eliminate render-blocking resources` section only

![Screen Shot 2020-07-21 at 10 32 29 PM](https://user-images.githubusercontent.com/5098765/88067849-11ae5680-cba2-11ea-9008-f5b7f9bb3c47.png)


And not available under `remove unused javascript` section
![Uploading Screen Shot 2020-07-21 at 10.33.16 PM.png…]()

**Comment by patrickhulce** [comment]
@carl-alberto the checkbox will be disabled when *all* resources in the table are 3rd party resources, i.e. we don't allow you to filter down to an empty table.
