### ISSUE TITLE
Question: Huge difference in "Total Blocking Time" in desktop vs mobile?

### ISSUE THREAD

**Issue by saurabhnanda** [GoogleChrome/lighthouse#11145]
I'm serving the exact same JS on desktop and mobile views. A bunch of JS widgets are initialized with the help of intersection-observers (i.e. only when the relevant `div` comes into the viewport). Therefore, in the first 5-10 sec, the desktop view ends up executing **more JS**, not less, just because more `div`s are in the viewport. Yet, the "Total blocking time" is 10-13x higher for mobile.

Does Lighthouse (and/or PageSpeed Insights), slow down the processor speed to emulate underpowered (compared to desktops) mobile hardware?

Any other reason why this could be the case?

**Comment by patrickhulce** [comment]
> Does Lighthouse (and/or PageSpeed Insights), slow down the processor speed to emulate underpowered (compared to desktops) mobile hardware?

[Yes](https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me)
