### ISSUE TITLE
Cannot add dependency on itself (PageSpeed Insights)

### ISSUE THREAD

**Issue by femesq** [GoogleChrome/lighthouse#11147]
I'm randomly getting "Cannot add dependency on itself" error, which "hides" the scores:
![image](https://user-images.githubusercontent.com/1899668/88180353-a39a7b80-cc03-11ea-9837-9565d36c59ef.png)

The strange thing is that after a few (10-20) runs, sometimes it works on one or both analysis scenarios (mobile/desktop):
![image](https://user-images.githubusercontent.com/1899668/88181634-89fa3380-cc05-11ea-9292-b01a36a9dab1.png)

The index path (link provided on steps to reproduce), frequently presents this error.
But in its sibling pages (language specific path like: `/en/`, `/pt/` and `/es/`) it works normal.

#### Provide the steps to reproduce
1. https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.webproject.com.br&tab=desktop
  
#### What is the current behavior?
Intermittent (but frequent) error.

#### What is the expected behavior?
No error or provide additional information on error.

#### Environment Information
* Affected Channels: PageSpeed Insights
* Lighthouse version: 6.1.0
* Analysis time: 7/22/2020, 10:20:59 AM

**Comment by patrickhulce** [comment]
Thanks very much for filing @femesq! I can reproduce this locally as well without PSI, we'll look into it 👍
