### ISSUE TITLE
Reports appear different everytime a report is taken

### ISSUE THREAD

**Issue by balasiddhartha-t** [GoogleChrome/lighthouse#11146]
#### Provide the steps to reproduce
1. Run LH on www.jeep-india.com
  

#### What is the current behavior?
Lighthouse tool metrics differ vastly from time to time when the reports are taken. At least 5% shift in the metrics is observed even though no builds are taken and the internet connection being stable
#### What is the expected behavior?
the metrics are supposed to be near when there is no change done to the page.

#### Environment Information
* Affected Channels: 
* Lighthouse version: v6.1.1
* Chrome version:  84
* Node.js version: 12
* Operating System: Windows

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing! Please refer to our [extensive variability documentation](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md). 5% is well within the expectations.
