### ISSUE TITLE
Usin remote chrome instance instead of subprocess

### ISSUE THREAD

**Issue by DrPyser** [GoogleChrome/lighthouse#11157]
**Feature request summary**

Hi!

I'm trying to use lighthouse in a production backend setup. 
We want to scan many urls on a periodic schedule. 
I'm currently using a containerized app that runs lighthouse and the chrome subprocess. 

In order to allow for a more scalable architecture, would it be possible for lighthouse to connect to an already running chrome instance through the debugging protocol?
For example, I could use [browserless/chrome](https://hub.docker.com/r/browserless/chrome/) to deploy a remotely accessible headless chrome, and tell the lighthouse cli to this connect this instance?

That way, instead of running `n` chrome instances to scan `n` urls, I would only have 1 or a few headless, remote chrome instances.
Beside reducing resource usage, this should enable me to run many lighthouse processes concurrently?

Thanks.

**What is the motivation or use case for changing this?**
Allow a more scalable usage of lighthouse cli, run many lighthouse scans concurrently.

**How is this beneficial to Lighthouse?**
More scalability.

**Comment by patrickhulce** [comment]
You can already do this today (see the [CLI options](https://github.com/GoogleChrome/lighthouse#cli-options) `--port` and `--hostname`) though [we strongly recommend against sharing a single machine](https://github.com/GoogleChrome/lighthouse/blob/8b4803d3c82ae679c5a62d8a30dbe98b8ed07162/docs/variability.md#run-on-adequate-hardware) to gather results if you care about the performance section.

**Comment by DrPyser** [comment]
@patrickhulce Thanks! I did try using those options, but it wasn't working. I thought I'd misunderstood their purpose. I'll try again.
