### ISSUE TITLE
Add generic audit for accessible names

### ISSUE THREAD

**Issue by eps1lon** [GoogleChrome/lighthouse#11155]
#### Provide a basic description of the audit

Audit if roles that require an [accessible name](https://www.w3.org/TR/accname-1.1/#dfn-accessible-name) have one (e.g. `dialog` or `tree`)

#### How would the audit appear in the report? 

`title`: Elements have an accessible name
`failureTitle`: Elements do not have an accessible name
`description`: When a `$ROLE_NAME_HERE` does not have an accessible name screen readers announce it with a generic name, making it unusable for users who rely on screen readers. 

The documentation should distill https://www.w3.org/TR/wai-aria-practices-1.1/#name_calculation into a format that applies on a per-role basis. The original section is quite complex.

#### How is this audit different from existing ones?

- `button-name` only warns on buttons
- `label` only on form controls

Though I suspect both just check for existence of the accessible name.

#### What % of developers/pages will this impact? 

I can't make an estimate. Some roles with accessible name required are probably more common (`dialog`) while more complex widgets are likely rarer (such as `tree`)

#### How is the new audit making a better web for end users?

People using screen readers get a more meaningful announcement when navigating e.g. `dialog` or `tree`.

#### What is the resourcing situation? 

Would like to help. I guess the biggest problem is that this new rule doesn't interfere with existing naming audits so that users don't get flooded with redundant errors.

Though it might be better to add audits/docs for each role instead.

#### Any other links or documentation that we should check out?

**Comment by patrickhulce** [comment]
Thanks for filing @eps1lon! This sounds like a great candidate for [axe-core](https://github.com/dequelabs/axe-core) which is what Lighthouse uses under the hood. Have you already discussed it with that team? I'm sure they'd be able to shed more light on where this is in their roadmap, if they've considered it before, etc :)

**Comment by eps1lon** [comment]
> This sounds like a great candidate for [axe-core](https://github.com/dequelabs/axe-core) which is what Lighthouse uses under the hood. Have you already discussed it with that team?

Tracked in https://github.com/dequelabs/axe-core/issues/2421

**Comment by eps1lon** [comment]
> > This sounds like a great candidate for [axe-core](https://github.com/dequelabs/axe-core) which is what Lighthouse uses under the hood. Have you already discussed it with that team?
> 
> Tracked in [dequelabs/axe-core#2421](https://github.com/dequelabs/axe-core/issues/2421)

Can be closed once `lighthouse` uses [`axe-core@^4.1.0`](https://github.com/dequelabs/axe-core/releases/tag/v4.1.0).

**Comment by connorjclark** [comment]
Dedupe #11207. watch #11661 for updates.

**Comment by patrickhulce** [comment]
@connorjclark https://github.com/GoogleChrome/lighthouse/pull/11661 doesn't add the new audits for new rules in axe, so maybe we should leave this open instead of deduping?

Thanks for following up @eps1lon!

**Comment by connorjclark** [comment]
I'm adding them now.
