### ISSUE TITLE
Lighthouse can unnecessarily wait up to 5 seconds before exiting

### ISSUE THREAD

**Issue by chosak** [GoogleChrome/lighthouse#11153]
#### Provide the steps to reproduce
1. Run Lighthouse against any URL (for example `lighthouse http://example.com`).
2. Once the run is complete, in the logs you'll see a message like `ChromeLauncher Killing Chrome instance 40651 +0ms` (with whatever Chrome PID is used), and Chrome will close.
3. Lighthouse will keep running for several (5) seconds, with no additional logging, before exiting.

#### What is the current behavior?

The problem is this code in [`potentiallyKillChrome`](https://github.com/GoogleChrome/lighthouse/blob/f96cbb42e4af99e1e390ff7d63c3ceeb0d189252/lighthouse-cli/run.js#L171):

https://github.com/GoogleChrome/lighthouse/blob/f96cbb42e4af99e1e390ff7d63c3ceeb0d189252/lighthouse-cli/run.js#L174-L179

Although the first Promise (`launchedChrome.kill()`) finishes right away, allowing `potentiallyKillChrome` to resolve, the parent process has to wait for the second Promise to finish before it can exit (see Node docs [here](https://nodejs.org/en/docs/guides/timers-in-node/#leaving-timeouts-behind) which imply this). This makes Lighthouse unnecessarily hang out for up to 5 seconds before exiting.

#### What is the expected behavior?

Ideally, the timeout should be cancelled once Chrome exits, with something like:

```js
let timer = null;

return Promise.race([
  launchedChrome.kill(),
  new Promise((_, reject) => timer = setTimeout(reject, 5000, 'Timed out.')),
]).then((value) => {
  clearTimeout(timer);
  return value;
}).catch(err => {
  throw new Error(`Couldn't quit Chrome process. ${err}`);
});
```

In practice this small change can significantly speed up Lighthouse execution in cases where 5 seconds represents a large part of the total runtime.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: Latest, 6.1.1
* Chrome version: 83.0.4103.116 (Official Build) (64-bit)
* Node.js version: v12.18.1
* Operating System: macOS Mojave

**Comment by patrickhulce** [comment]
Great catch @chosak! Interested in a PR? :)

**Comment by chosak** [comment]
@patrickhulce thanks; I needed to investigate the SLA process but I see you have beaten me to the PR. Thank you for moving this fix forward.

**Comment by patrickhulce** [comment]
Oh sorry @chosak! I assumed there wasn't interest and didn't know you were already looking into it, my bad 😬 just didn't want to let such a high impact fix linger too long and get forgotten. We really appreciate the detailed report! 🎉
