### ISSUE TITLE
[Q] Can Lighthouse be used with Android WebView-based browser?

### ISSUE THREAD

**Issue by 4ntoine** [GoogleChrome/lighthouse#11156]
I have an app (browser) based on Android WebView and i'd like to audit it with Lighthouse. I'm able to connect to Chrome Android app but fail with my browser app with enabled devtools access (with `WebView.setWebContentsDebuggingEnabled(true)`):
```
adb forward tcp:9222 localabstract:chrome_devtools_remote
lighthouse --port=9222 --emulated-form-factor=none --throttling.cpuSlowdownMultiplier=1 https://example.com
  config:warn IFrameElements gatherer requested, however no audit requires it. +0ms
  config:warn InspectorIssues gatherer requested, however no audit requires it. +1ms
  status Connecting to browser +11ms
  CriConnection:warn Cannot create new tab; reusing open tab. +13ms
  status Disconnecting from browser... +8ms
  CriConnection:error sendRawMessage() was called without an established connection. +1ms
  GatherRunner disconnect:error sendRawMessage() was called without an established connection. +1ms
Runtime error encountered: Cannot create new tab, and no tabs already open.
Error: Cannot create new tab, and no tabs already open.
    at /usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:45:35
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Driver.connect (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:180:5)
    at async Function.run (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:624:7)
    at async Function._gatherArtifactsFromBrowser (/usr/local/lib/node_modules/lighthouse/lighthouse-core/runner.js:215:23)
    at async Function.run (/usr/local/lib/node_modules/lighthouse/lighthouse-core/runner.js:81:21)
    at async runLighthouse (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:209:26)

```

Is it meant to be supported too/not working for sure/ smth in between?

UPDATE: i've been testing ^ with real hardware.

When testing with "WebView Browser Tester N" app in emulator i'm getting different output (it connect but hangs):
```
lighthouse --port=9222 --emulated-form-factor=none --throttling.cpuSlowdownMultiplier=1 https://example.com
  config:warn IFrameElements gatherer requested, however no audit requires it. +0ms
  config:warn InspectorIssues gatherer requested, however no audit requires it. +1ms
  status Connecting to browser +11ms
  status Resetting state with about:blank +115ms
  status Benchmarking machine +232ms
  status Initializing… +511ms
  status Running defaultPass pass CSSUsage, JsUsage, ViewportDimensions, RuntimeExceptions, ConsoleMessages, AnchorElements, ImageElements, LinkElements, MetaElements, ScriptElements, IFrameElements, MainDocumentContent, AppCacheManifest, Doctype, DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility, TraceElements, InspectorIssues, SourceMaps +50ms
  status Resetting state with about:blank +1ms
  status Setting up network for the pass trace +72ms
  status Cleaning browser cache +9ms
  status Beginning devtoolsLog and trace +95ms
  status Loading page & waiting for onload +18ms
```

**Comment by patrickhulce** [comment]
Thanks for filing @4ntoine! I run into this error sometimes if I don't already have Chrome open and in the foreground. Does that workaround fix this issue for you?

**Comment by 4ntoine** [comment]
@patrickhulce Hi, Patrick. What workaround do you mean? I was unable to make it working (neither with my browser nor with WebView Browser Tester app)

**Comment by patrickhulce** [comment]
The "workaround" being only execute those commands after the stable Chrome app is open and in the foreground of the mobile device without anything else running that could interfere.

Also just general checklist make sure Chrome is up-to-date with latest stable. Lighthouse won't work with older Android WebView as we only support stable Chrome.

**Comment by 4ntoine** [comment]
@patrickhulce Not sure i understand. I'm trying to make Lighthouse working with my Android browser app based on a WebView (83.something). I've tried it with Chrome just to make sure i forwarded the ports correctly (and did not do some silly mistakes) and it can work at all. Is there anything i can check or try to do?

**Comment by patrickhulce** [comment]
Oooooh, sorry for the misunderstanding. You can't really do this unfortunately :/ 

There's a set of assumptions baked into the way Lighthouse communicates with the process that won't work in a non-Chrome setting. Once we tackle #1769 this *might* be able to work with a subset of the audits, but it's blocked for now. Sorry!

**Comment by 4ntoine** [comment]
@patrickhulce Thanks for the explanation anyway.
