### ISSUE TITLE
Invalid score for speed-index: NaN

### ISSUE THREAD

**Issue by dKab** [GoogleChrome/lighthouse#11154]
#### Provide the steps to reproduce
1. Run LH on https://kabardinovd.com
  
#### What is the current behavior?

Performance Audit Error:

Speed Index                           Error!
Invalid score for speed-index: NaN

#### What is the expected behavior?

Performance audit should show a numeric score

#### Environment Information
* Affected Channels: DevTools (At least)
* Lighthouse version: 6.0.0
* Chrome version: 84.0.4147.89 (Official Build) (64-bit) (cohort: Stable)
* Node.js version: v12.18.2
* Operating System: Windows 10 Pro

**Comment by patrickhulce** [comment]
Thanks for filing @dKab ! I can't reproduce reliably this though :/

Only 1 of 10 runs gave me this, was this what you observed?

![image](https://user-images.githubusercontent.com/2301202/88344980-86040980-cd0a-11ea-829e-18a0017d74e9.png)

**Comment by mdnelles** [comment]
I am getting this too locally and online: https://romantic-mahavira-1e7c3a.netlify.app

<img width="925" alt="Screen Shot 2020-07-24 at 12 12 45 PM" src="https://user-images.githubusercontent.com/26289863/88412109-0a0bcf00-cda7-11ea-8cb0-e1ecb79ac15f.png">

**Comment by dKab** [comment]
@patrickhulce 
![изображение](https://user-images.githubusercontent.com/6264291/88413769-6e00b880-cde4-11ea-8fce-6bd626c9967c.png)

**Comment by Karthik9321** [comment]
I'm facing the same issue as well. Same with another product from our company. Both of them are NextJs apps hosted on vercel, if it helps. It used to work fine on the same domain a few days ago, nothing significant has changed since then in terms of new code.
![Screenshot 2020-07-24 at 11 51 59 PM](https://user-images.githubusercontent.com/24381468/88423142-f3965f80-ce08-11ea-83ab-bfc47a377b88.png)

**Comment by patrickhulce** [comment]
Hm, I'm not sure what's going on I can't reproduce this on any of the provided URLs in stable, canary, windows, or mac :/

Definitely concerning that so many of you seem to have run into this though. Anything in particular you can share about your setup or repro steps that might be unique or relevant?

**Comment by leodeslf** [comment]
> Anything in particular you can share about your setup or repro steps that might be unique or relevant?

Same issue here.

**When it happens?**
It only happens when I run audit with **no extensions enabled**.

**Where and How I've tested?**
Tested [here](https://leodeslf-portfolio.netlify.app/) for both mobile and desktop, on Chrome ([see screenshot here](https://i.imgur.com/9JVLI7z.png)) and Edge ([see screenshot here](https://i.imgur.com/meEBqcZ.png)), Win 10. Under Incognito, Guest, or an Account (logged to Google acc. or not). So I'm assuming it's not a profile or acc. related problem.

**Context**
Auditing my work in progress portfolio in a "clean" environment to ensure there isn't any negative impact to the performance, I disabled all my extensions, and surprise! **speed-index: NaN** happens 😅

Let me know if I can help you with any further information.

**Comment by patrickhulce** [comment]
Thanks @leodeslf ! That's a good extra tip about the extensions but I still couldn't reproduce it :/ Does it happen every time you run?

Also would someone experiencing this be willing to share the *trace* file that resulted? 

You can get the trace by...

1. Clicking "View Trace" in the Performance section after the run completes.
![image](https://user-images.githubusercontent.com/2301202/88443208-04c97700-cddd-11ea-93a7-5db2510d42cf.png)

2. Clicking the download trace button "Save profile..." in the performance panel
![image](https://user-images.githubusercontent.com/2301202/88443251-2cb8da80-cddd-11ea-9007-b3f2194e542a.png)

3. Uploading that JSON file here to github :)

**Comment by leodeslf** [comment]
Yes, at the moment it happens every time in that conditions.

[Here](https://github.com/GoogleChrome/lighthouse/files/4974682/Profile-20200724T212637.zip) is my trace file.

**Comment by patrickhulce** [comment]
Thanks @leodeslf! Speed index itself worked on that trace without any problems, and I'm not sure what else I can do at this point :/

Anyone else on Lighthouse able to reproduce this behavior?

**Comment by mrjohnsly** [comment]
Chrome Version 84.0.4147.89 (Official Build) (64-bit)
Lighthouse 6.0.0

I'm seeing the same issue but only when running as 'Device: **Desktop**' running as 'Device: **Mobile**' works correctly.

**Desktop**
<img width="546" alt="Lighthouse Device Desktop" src="https://user-images.githubusercontent.com/220305/88481819-8ba15f80-cf55-11ea-9aeb-9c9259e2b3be.png">

**Mobile**
<img width="548" alt="Lighthouse Device Mobile" src="https://user-images.githubusercontent.com/220305/88481823-922fd700-cf55-11ea-8b0a-962e3ae6618a.png">


May be a separate issue but the tooltip for both mobile and desktop reads "Apply mobile emulation during auditing"

<img width="554" alt="Lighthouse Tooltip" src="https://user-images.githubusercontent.com/220305/88481707-e1293c80-cf54-11ea-8fd9-69714c04f1c9.png">

**Comment by patrickhulce** [comment]
Finally able to repro thanks to #11173 so we've got a fix in play now 🎉

**Comment by anandgupta193** [comment]
> Finally able to repro thanks to #11173 so we've got a fix in play now 🎉

Welcome @patrickhulce

**Comment by Divlo** [comment]
Yep same issue, seems like it works when auditing with mobile.

**Comment by anandgupta193** [comment]
@patrickhulce - Is the issue fixed?

**Comment by patrickhulce** [comment]
@anandgupta193 yes but you won't see it in Chrome for quite some time. Probably in the CLI and PSI in ~3 weeks

**Comment by eperret** [comment]
I am still seeing the issue with Version 85.0.4183.83 (Official Build) (64-bit) on Ubuntu 18.04

**Comment by anandgupta193** [comment]
@patrickhulce - Is this issue fixed and shipped to latest chrome lighthouse?

**Comment by patrickhulce** [comment]
Yes it should be fixed in Chrome Canary and is part of Chrome 86 (becomes stable in October).

**Comment by Albert-Gao** [comment]
Meanwhile, a workaround, 

1. click the `See calculator.` link
![image](https://user-images.githubusercontent.com/18282328/93551070-0b313500-f9c1-11ea-8d4e-733e48941749.png)

2. in the opening page, try moving the Nah Speed index slider a little bit. You will see the number being populated correctly
![image](https://user-images.githubusercontent.com/18282328/93551123-3156d500-f9c1-11ea-9547-3e5ee3e6429b.png)
