### ISSUE TITLE
Is there any step necesary for getting Field Data and Origin Summary to show stats

### ISSUE THREAD

**Issue by tomasts248** [GoogleChrome/lighthouse#11159]
I already have search console  and google analytics, is there an additional step in order to display in the future those indicators?

**Comment by patrickhulce** [comment]
I assume you're referring to Page Speed Insights showing the field data for your URL and origin? AFAIK, there are no steps for you to take other than increase the traffic to the page as only pages with enough data to anonymize are included in the Chrome UX report.

**Comment by tomasts248** [comment]
Alright understood! Thanks for explaining :)

**Comment by exterkamp** [comment]
Thanks @patrickhulce for answering 🎉
