### ISSUE TITLE
Add subitem headers to "Reduce the impact of third-party code" breaking down impact by script

### ISSUE THREAD

**Issue by warrengm** [GoogleChrome/lighthouse#11165]
**Feature request summary**
It would be great to breakdown of the "Reduce the impact of third-party code" audit by script. Sometimes it's hard to pinpoint which scripts have the most impact on metrics. I realize that the "Minimize main thread work" audit already has script breakdowns, but the data isn't grouped by third party and the audit doesn't contain blocking time. (Relatedly, maybe it's worth having separate audits for first party and third party JS?)

I imagine doing this by adding a sub-item for each script owned by each party. To limit the report size/noise, we may want to only show the top 3 scripts by impact.

I'd be willing to work on this feature if it sounds like a good idea.

**What is the motivation or use case for changing this?**
Some third parties have multiple scripts on the page which makes it hard to identify the culprit script(s) for third parties with large impact.

**How is this beneficial to Lighthouse?**
It would make attribution to individual scripts easier which can simplify analysis

**Comment by patrickhulce** [comment]
Great idea @warrengm! We were already planning something similar with script source URLs too, so I think this is a natural stepping stone. Happy to review if you submit a PR :)

**Comment by connorjclark** [comment]
Agreed. We are planning sub items for GTM once they add special data for us to determine specific tags. It seems straightforward to make that a special case of a more general "show scripts as sub items" feature.

**Comment by warrengm** [comment]
Sounds good! I'll get started when I have some time

I was coming at this from the Google Ads side. Right now, Google Ads is a big umbrella for many scripts so script attribution would helpful to distinguish publisher tags from creative scripts, for example. (Especially when creative scripts are often non-deterministic.) For GTM, I think they usually load only one script so there shouldn't be a conflict with their tag breakdown.

**Comment by exterkamp** [comment]
Was this fixed with #11219, or is it now waiting on something else?

**Comment by warrengm** [comment]
Yep, it's fixed! Thanks for the ping
