### ISSUE TITLE
The failure "Displays images with incorrect aspect ratio" is reported on images displayed with correct aspect ratio

### ISSUE THREAD

**Issue by cindyli** [GoogleChrome/lighthouse#11169]
**Describe the bug**
The failure "Displays images with incorrect aspect ratio" is reported on images displayed with correct aspect ratio.

**To Reproduce**
1. Go to [https://dev--wecount.netlify.app/initiatives/](https://dev--wecount.netlify.app/initiatives/) using Chrome;
2. Open Developer Tool, on "lighthouse" tab, select "mobile" device, click "generate report";
3. Click on the score of Best Practices;
4. In "User experience" section, the failure "Displays images with inappropriate size" is reported on an image, the screenshot is attached below;
5. Click "Learn more". The explanation page says this failure `flags any image with a rendered aspect ratio 5 percent or more different from its natural ratio`;
6. Looking at 3 sizes on the report, their calculated aspect ratios are:
* Displayed size: 306 X 160; aspect ratio: 1.9125
* Actual size: 360 X 188; aspect ratio: 1.9148
* Expected size: 918 X 480; aspect ratio: 1.9125

The difference between aspect ratios is nowhere near 5%.

**Expected behavior**
This error should not be reported.

A question: does this failure also indicate a larger image is expected to be displayed? If it does, why?

**Screenshots**
<img width="1062" alt="Screen Shot 2020-07-27 at 2 40 12 PM" src="https://user-images.githubusercontent.com/572877/88580170-40508500-d019-11ea-8ebd-440ecdb6afd4.png">

**Comment by patrickhulce** [comment]
Thanks for filing @cindyli this was fixed in 6.1.0  (https://github.com/GoogleChrome/lighthouse/pull/10801) and will be in Chrome shortly.
