### ISSUE TITLE
[Security] outdated jpeg-js with vulnerability

### ISSUE THREAD

**Issue by Potato-coder** [GoogleChrome/lighthouse#11166]
Hi is there any plans to update jpeg-js npm package to 0.40 or higher due to vulnerability associated with it. https://github.com/advisories/GHSA-w7q9-p3jq-fmhm

**Comment by patrickhulce** [comment]
We can update for the security warning to go away, but Lighthouse doesn't use jpeg-js to parse arbitrary user input, so it's not  exposed to this particular attack currently anyhow.

**Comment by Potato-coder** [comment]
Thanks 🙏 !
