### ISSUE TITLE
my problem is Lighthouse returned error: INTERNAL: Extension result empty in pagespeed insights

### ISSUE THREAD

**Issue by carlos0205** [GoogleChrome/lighthouse#11178]
my error is my is Lighthouse returned error: INTERNAL: Extension result empty in pagespeed insights

Lighthouse returned error: INTERNAL: Extension result empty. Lighthouse calling Page.navigate with https://www.elpais.com.co/ Uncaught (in promise) Error: Extension timed out. No call to exit() before render timeout. at wrs.Extension.onTimeout_ (http://ghost-rider/devtools_script_api.js:5606:13) at http://ghost-rider/devtools_script_api.js:655:11 Puedes actualizar para volver a intentarlo

**Comment by exterkamp** [comment]
I get intermittent results. Mobile loaded, but Desktop timed out.

![image](https://user-images.githubusercontent.com/6392995/94609368-890ffe80-0253-11eb-964a-f62cea4b4b9c.png)

![image](https://user-images.githubusercontent.com/6392995/94609435-a2b14600-0253-11eb-9cc5-32182347ec5a.png)

We can't do much about the timeouts, it usually means that the page is still making lots of requests late in the load and Lighthouse can never finish. The old `extension timeout` errors (which should be gone now) were a bad error, but indicated a timeout as well.

If the page takes >60s to analyze, PSI will timeout. I recommend using devtools/node cli to run Lighthouse in that case.

**Comment by patrickhulce** [comment]
Chromium takes 10+ seconds to send us a trace for this page, which isn't good, but everything else is fast. As @exterkamp noted in https://github.com/GoogleChrome/lighthouse/issues/11178#issuecomment-700955203 there's not much we can do here, so we're going to go ahead and close.
