### ISSUE TITLE
Expose Lighthouse audits to be consumed programmatically

### ISSUE THREAD

**Issue by christian-bromann** [GoogleChrome/lighthouse#11185]
**Feature request summary**

It would be great if Lighthouse could expose its audits from an NPM package. I'ld suggest two of the following options:

1. allow importing these audits directly from LH, e.g.

    ```js
    import { MainThreadWorkBreakdown, ServerResponseTime, ... } from 'lighthouse-core'
    ```

2. or maybe even separate gathering and audit logic into independent sub packages, e.g.

    ```js
    import { MainThreadWorkBreakdown, ServerResponseTime, ... } from 'lighthouse-audits'
    ```

I am not sure how much logic is shared between LH core and the individual audits themselves. The first option is totally viable and would work for us.

**What is the motivation or use case for changing this?**

We at the [Webdriver.io](https://webdriver.io/) project use Lighthouse to allow performance tests for automated WebDriver based tests. This allows user to capture metrics for various page loads along a user journey (e.g. a checkout flow). You can read for information about this in our [docs](https://webdriver.io/docs/devtools-service.html#performance-testing).

The way it works in that WebdriverIO has a parallel CDP connection and intercepts the automation steps so that it properly traces the page load and captures all necessary information to feed into Lighthouse audit classes. The current problem is that these audits aren't very safe to use as we have to [import the files directly](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-devtools-service/src/auditor.js#L1-L12) from the package. If file names change or parameters are updated it will likely break our logic as update lighthouse without expecting such breaking changes (which are actually not breaking for "standard" LH users).

This idea could be further extended to also export various of gatherers into their own independent modules. They only need a puppeteer instance and can expose unified interface to be run before/after a page load. This would also tremendously help us to uniformly capture the information needed for the audits.

**How is this beneficial to Lighthouse?**

Lighthouse is used in different contexts, e.g. as Chrome DevTools feature or as CLI tool. They allow mostly to capture performance of a specific page load from a pristine browser session. Many WebdriverIO use the Lighthouse integration to go beyond that and include performance tests as part of e2e user scenario. Making the integration of internally build logic easier, helps with the adoption of Lighthouse for different use cases.

Additionally making the code more modular helps to maintain the code better as there are clear contracts between different interfaces and modules.

**Comment by patrickhulce** [comment]
Thanks for filing @christian-bromann ! IIUC, this is basically #9519 but asking for one step further to break out audits (and maybe gatherers?) as well?

Given the end result in #9519 of declining to increase the public API surface on a much smaller subset of the codebase, I'm not optimistic we'll be taking on an even larger set anytime soon. Worth discussing though :)

**Comment by christian-bromann** [comment]
> but asking for one step further to break out audits (and maybe gatherers?) as well?

Yeah .. I am more interested in breaking out audits and make them modular so that they eat data from the gatherer and return metrics.

I am happy to contribute to this work ☺️

**Comment by paulirish** [comment]
We discussed this and right now we're not going to add additional API surface this.  Of course, you can reach in and uses these yourself, but that use is up to you.

Thanks!
