### ISSUE TITLE
How to setup Lighthouse timings budgets and/or throttling if your lab and field data differs a lot?

### ISSUE THREAD

**Issue by Zrce** [GoogleChrome/lighthouse#11181]
I want to optimize LCP for the real users, so luckily it's possible to collect some field data. But now if I want to setup a pre deployment test against a budget I run into the problem of having a huge difference in e.g. LCP with Lighthouse's lab vs. field data.

My guess is that LCP in field data is much better than lab tests LCP because devices and connections of my real users are better. 

If https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md is still correct Lighthouse lab tests run with 
Latency: 150ms
Throughput: 1.6Mbps down / 750 Kbps up.
Packet loss: none.

How to deal now with testing before deployment? I tend to set the budget.json file for the lab test to the "good", "needs improvements" thresholds of web vitals. As a result running with a default config of lighthouse I'm always overBudget.

Do you recommend to change the throttling or adapt budgets, to get somewhere close to not overBudget? I thought about tracking https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation to get some user connection speed, but the cpu throttling is still unsolved like this. In addition an x times slowdown option of the CPU in Lighthouse is not really accurate. 

It would be good to have something like a template for lab test throttling setup per region / country to test agains as a starting point. Some best practice how to find and keep a throttling setup realistic for our users would also be interesting.

**Comment by patrickhulce** [comment]
Thanks for filing @Zrce!

> My guess is that LCP in field data is much better than lab tests LCP because devices and connections of my real users are better.

Some of your users definitely are, but the gap is explained by a confluence of many factors. Faster users browse more (that's the point of working on performance after all ;)), Lighthouse only reports the cold load while field is typically comprised of a lot of repeat visits with cached assets, and abandonment for the slowest loads means they're not captured at all.

As for what to do about it, my personal recommendation: set achievable targets for where you are right now even if it's higher than the CWV "good" thresholds and aim to slowly improve them over time.

**Comment by exterkamp** [comment]
Re-open if you have a follow up, otherwise closing b/c question was answered 😄
