### ISSUE TITLE
Extracting Web-Vitals as part of a user's browser session

### ISSUE THREAD

**Issue by rikonor** [GoogleChrome/lighthouse#11187]
**Feature request summary**
I'd like to know if there is a way, as part of a real user's browser session, to extract Web-Vitals, such as TID, LCP, etc, so that they can be reported as RUM data.

This would serve a similar function to libraries like [Perfume.js](https://github.com/Zizzamia/perfume.js), but with the benefit of having parity with the actual Lighthouse library, rather than relying on an independent implementation.

I had dug around a bit trying to see if this was currently possible but ran into some hurdles. It seems like [lighthouse-core/audits/metrics.js#L36](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/metrics.js#L36) would allow retrieving the calculated metrics, but it requires a `artifacts` and `context` inputs, which I wasn't able to figure out how to create/derive.

I also saw there was some effort underway to expose different packages, and thought this might fit well under that effort (See https://github.com/GoogleChrome/lighthouse/issues/9519).

I would be willing to work on this, potentially, if there was s a clear way to implementing it.

**What is the motivation or use case for changing this?**
This would allow using Lighthouse metrics calculation as part of a real browser session and provide field data, which would be complementary to lab data.

**Comment by patrickhulce** [comment]
Thanks for filing @rikonor! Collecting these metrics in the field relies on completely different APIs than what Lighthouse uses to collect these in the lab, so it wouldn't really make sense for this work to live inside Lighthouse.

There is, however, an official Chrome-backed library for exactly what you're looking for. `web-vitals` reports the three core web vitals metrics. You can find the code and more examples over at https://github.com/GoogleChrome/web-vitals


**Example Usage**

```js
import {getCLS, getFID, getLCP} from 'web-vitals';

function sendToAnalytics(metric) {
  const body = JSON.stringify(metric);
  // Use `navigator.sendBeacon()` if available, falling back to `fetch()`.
  (navigator.sendBeacon && navigator.sendBeacon('/analytics', body)) ||
      fetch('/analytics', {body, method: 'POST', keepalive: true});
}

getCLS(sendToAnalytics);
getFID(sendToAnalytics);
getLCP(sendToAnalytics);
```

**Comment by rikonor** [comment]
Thanks a ton @patrickhulce. I glanced over at that package previously and I don't know why it didn't click that it was exactly what I was looking for. Will use that instead!

Feel free to close this.
