### ISSUE TITLE
Huge difference in blocking time on Windows vs. Mac

### ISSUE THREAD

**Issue by MKJJJ** [GoogleChrome/lighthouse#11183]
I've just run lighthouse (from the dev console) for the very same site on a Windows 7 machine and on a Mac. I see a HUGE difference in blocking time. On Windows it is around 10.000 ms, and on Mac it is around 700 ms. On Windows I see the "Reduce the impact of third-party code" warning, while I don't get this message on the Mac. The Mac is obviously the much more powerful machine. However, could this be the reason for such a huge difference? It's the same when loading the site in the network tab of the dev console. On Windows loading time is around 6 seconds, while it is under 2 seconds on Mac (both tested in Chrome private mode).

**Comment by patrickhulce** [comment]
Thanks for filing @MKJJJ !

> could this be the reason for such a huge difference?

Yes, this is definitely the reason :) See the [variability documentation](https://github.com/GoogleChrome/lighthouse/blob/c75f1ba97989af60713e8401c770e5e28b10313b/docs/variability.md) for complete explanations of what can affect the results and #9085 for more discussion on our plan to try to automatically warn about this situation.

**Comment by MKJJJ** [comment]
Thanks for the feedback. I checked it again, and indeed: CPU load on my Windows machine increases to 57% on page reload. On the Mac is barely any difference noticeable. OK, lessons learned. I've never thought that websites can be so CPU intensive.
