### ISSUE TITLE
Move remaining travis tests to github actions

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#11194]
I thought there was an existing issue for this but maybe not.

- [x] `yarn test-viewer`
- [x] code coverage
  - unit
  - smoke
  - upload to codecov, maybe coveralls if we still want it
- [x] lantern test https://github.com/GoogleChrome/lighthouse/pull/11767#issuecomment-741995619
- [x] retire travis?

anything else?

**Comment by brendankenny** [comment]
open question: GitHub Actions is currently just Node 10. What should we do about Node 12/14 (and generally LTS vs latest in the future)?

**Comment by patrickhulce** [comment]
> What should we do about Node 12/14 (and generally LTS vs latest in the future)?

I'd say we just add the unit tests/basics for latest node so we're aware of any major issues, but other than that just keep everything on our lowest acceptable node version.
