### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by arsalan244** [GoogleChrome/lighthouse#11196]
I am facing these issue on my website.
(devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1453:229)

**Comment by patrickhulce** [comment]
Please fill out the correct [issue template](https://github.com/GoogleChrome/lighthouse/issues/new/choose) if you'd like  the Lighthouse team to respond.

**Comment by exterkamp** [comment]
Re-open if you have more details to help us debug!
