### ISSUE TITLE
Largest Contentful Paint (LCP) BUG in Google Pagespeed

### ISSUE THREAD

**Issue by leonardosedevic** [GoogleChrome/lighthouse#11204]
Tested on Firefox version 79.0 (64-bit) & Chrome Version 84.0.4147.105 (Build officiel) (64 bits)

#### Provide the steps to reproduce
1. Run LH on <https://www.stop-it.be/>

#### What is the current behavior?
The results on GooglePage speed are wrong 
#### What is the expected behavior?
The results have to MATCH Chrome Lighthouse !

#### Environment Information
* Affected Channels: 
* Lighthouse version: Chrome Version 84.0.4147.105 (Build officiel) (64 bits)
* Chrome version: 84.0.4147.105
* Node.js version: 
* Operating System: windows 10

**Related issues**
![bug_pagespeed01](https://user-images.githubusercontent.com/13037737/89122690-bc3f4700-d4c9-11ea-909e-99515926d81f.jpg)
![results_lighthouse](https://user-images.githubusercontent.com/13037737/89122692-be090a80-d4c9-11ea-91fb-7904045d0c95.jpg)

**Comment by patrickhulce** [comment]
Thanks for filing @leonardosedevic! Those screenshots are comparing [lab and field data which are very different](https://web.dev/how-to-measure-speed/#lab-data-vs-field-data). Also see [the variability documentation](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) for why comparing lab data in different environments may yield different results.
