### ISSUE TITLE
LHError: PROTOCOL_TIMEOUT at eval lighthouse_worker_module.js:1453:229

### ISSUE THREAD

**Issue by jameswilson** [GoogleChrome/lighthouse#11215]
#### Provide the steps to reproduce
1. Run LH on https://mru.org with the default options specified:

<img width="304" alt="Screen Shot 2020-08-04 at 11 34 11 AM" src="https://user-images.githubusercontent.com/243532/89319949-7491fa00-d646-11ea-945f-fe4b13b4768c.png">

#### What is the current behavior?

LH hangs on the "warming up" step for ~30 seconds, then times out, and finally the following warning message appears in a dialog window:

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://mru.org/
Chrome Version: 84.0.4147.105
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1453:229)
```

Line 1453 contains the following code:

```
sendCommandToSession(method,sessionId,...params){const timeout=this._nextProtocolTimeout;this._nextProtocolTimeout=DEFAULT_PROTOCOL_TIMEOUT;return new Promise(async(resolve,reject)=>{const asyncTimeout=setTimeout(()=>{const err=new LHError(LHError.errors.PROTOCOL_TIMEOUT,{protocolMethod:method});reject(err);},timeout);try{const result=await this._innerSendCommand(method,sessionId,...params);resolve(result);}catch(err){reject(err);}finally{clearTimeout(asyncTimeout);}});}
```

column 229 is where this code block starts:

```new LHError(LHError.errors.PROTOCOL_TIMEOUT,{protocolMethod:method})```

which is less than useful information.

#### What is the expected behavior?

LH should provide a clear message about what URL caused the timeout, and the stack trace or console output to help identify what triggered the issue.

#### Environment Information
* Affected Channels:  DevTools (untested with other channels). 
* Lighthouse version: I'm unsure how to figure out the lighthouse version bundled with Chrome 84, but I assume this affects lighthouse 5, since 6 just came out for Chrome 85(?)
* Chrome version: 84.0.4147.105
* Node.js version: 
* Operating System: MacOS Mojave 10.14.6 (18G6020)

**Related issues**

#6512

The following should be marked as Duplicates because they do not follow the requested issue template.

#11196
#11201 
#11160

**Comment by patrickhulce** [comment]
> LH should provide a clear message about what URL caused the timeout, and the stack trace or console output to help identify what triggered the issue.

If Chrome made this information available to us then we wouldn't need to throw a PROTCOL_TIMEOUT error ;) #6512 is the correct place for this.
