### ISSUE TITLE
https://magni.strumpur.net/Map/indexMain.html << error on every result

### ISSUE THREAD

**Issue by Magnithor** [GoogleChrome/lighthouse#11213]
There were issues affecting this run of Lighthouse:

Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)

this is simple map program. It use WebGl to draw
url: https:///magni.strumpur.net/Map/indexMain.html
I have also webworker instance of this page https://magni.strumpur.net/Map/indexWorker.html but same result

* Affected Channels: 
* Lighthouse version:
* Chrome version: 84.0.4147.105 64 bit
* Node.js version:
* Operating System: Windows 10.0.18363

**Comment by patrickhulce** [comment]
Thanks for filing @Magnithor! You've found a bug in Chromium 👍 

Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1112857

**Comment by connorjclark** [comment]
crbug was fixed a few weeks ago, but I still see NO_FCP in chrome canary.

**Comment by patrickhulce** [comment]
Hm yeah that's odd. The FCP event does fire via the observer in the page though, so maybe this is back on Lighthouse now.

**Comment by patrickhulce** [comment]
Investigated, while the WebGL2 canvas fix worked for the some repro cases, it still doesn't cover the linked page :/ Pinged annie for clarification there. It's also worth noting that even once this is resolved, LCP *intentionally* ignores canvases so we'll still fail to provide a performance score for this URL in an unresolvable way 😞

**Comment by connorjclark** [comment]
There's nothing for us to do on LH's side, so if you are interested in this fix I suggest you follow https://bugs.chromium.org/p/chromium/issues/detail?id=1112857
