### ISSUE TITLE
queryselector

### ISSUE THREAD

**Issue by ssivanatarajan** [GoogleChrome/lighthouse#11214]
#### Provide the steps to reproduce
1. Run LH on Node API
  

#### What is the current behavior?
In lighthouse 5.6 i was able to use driver.querySelectorAll  method. It is not working in latest version. Seems the function was removed.
#### What is the expected behavior?
Any other method to get the dom nodes?  I have used this queryselectorAll to identify the broken links in anchor tags.
#### Environment Information
* Affected Channels: CLI ,Node
* Lighthouse version:6.1.1
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
All internal uses in Lighthouse now use `driver.evaluateAsync` combined with this in-page function `getElementsInDocument`

https://github.com/GoogleChrome/lighthouse/blob/40baa221b87ae44c3184f9e6587ef173590ef595/lighthouse-core/lib/page-functions.js#L86-L106

Example:

https://github.com/GoogleChrome/lighthouse/blob/40baa221b87ae44c3184f9e6587ef173590ef595/lighthouse-core/gather/gatherers/anchor-elements.js#L108-L120
