### ISSUE TITLE
Doesn't detect that page doesn't load due to bad SSL interstitial

### ISSUE THREAD

**Issue by Janpot** [GoogleChrome/lighthouse#1123]
Maybe this is a bit contrived. But I ran a lighthouse review

```
lighthouse https://www.cnn.com
```

Which times out because the library doesn't detect that the insecure content warning is set.
Similarly:

```
lighthouse https://www.some-none-existing-domain.com
```

Which happily reviews the chrome error page. Shouldn't the library detect these errors and show a userfriendly message?

**Comment by paulirish** [comment]
These are good bugs. :)
Thanks for reporting them.

You interested in trying a fix yourself? We can point you the way.

**Comment by Janpot** [comment]
@paulirish I actually came to lighthouse to find inspiration for fixing these in my own project, which is very similar to lighthouse. If I have some free time I might be interested to take a look for lighthouse as well.
In the meantime I think I figured it out for the first one. I'd have to listen for `Network.securityStateChanged` and check the `SecurityState` (I'm using `chrome-remote interface`, not `devtools-frontend`). At least when it's `'insecure'` the error page is shown. Not sure for the other values. Is this the right direction?
Still have to do research for the second class of errors so but I guess it's just listening for `Network.onResponseReceived` on the main resource and check the statuscode.

**Comment by paulirish** [comment]
Ah cool. Cc @lgarron about detecting the interstitial via he protocol.

The second case is probably looking at status code and or looking and the redirected URL. We'll see.

Awesome to hear you're building on top of cri. Can you tell us a bit more about your project?

**Comment by Janpot** [comment]
Sure, My company automated making SEO/usability reviews. Specifically I'm rebuilding what would be our 'gather' phase. For starters I'm just interested in a HAR capture, original source and rendered html. our existing pipeline can use that to do what you call audit and aggregate.
Originally I started out by building on top of lighthouse but it didn't feel flexible enough so I rolled my own. I still reuse your `chrome-launcher` so breaking this out in its own module would be a nice change for me.
In the future I'm also looking into gathering screenshots (doesn't seem to be ready enough yet in the devtools API) and executing some javascript to get some insights in what the page executes (no priority right now).
Planning to run the thing in docker, preferably with headless_shell.

**Comment by Janpot** [comment]
And in my free time I could definitely be interested in contributing. Been closely following the project for a few weeks now.

**Comment by lgarron** [comment]
I don't recall if there is a straightforward way; detecting navigations is already pretty hacky.
If there isn't, that's work I would group with Q1.

**Comment by wardpeet** [comment]
@Janpot  you can look at https://hub.docker.com/r/justinribeiro/chrome-headless/ mentioned by @paulirish on https://github.com/GoogleChrome/lighthouse/issues/698#issuecomment-264594706

**Comment by Janpot** [comment]
@wardpeet thanks for the pointer, that project is indeed on my radar. For me, ideally, there'd be an "official" snapshot of the shell so I don't have to rely on the maintainer of that project. Been building it myself too but I prefer to automate.

@lgarron Do you know if there's a relation between showing the interstitial in chrome and a property in the `Network.securityStateChanged` event in the devtools protocol?

**Comment by lgarron** [comment]
> @lgarron Do you know if there's a relation between showing the interstitial in chrome and a property in the Network.securityStateChanged event in the devtools protocol?

There should definitely be a `Security.SecurityStateChanged` event, but I think there is no (fully safe) semantic way to tell it corresponds to an interstitial right now.

**Comment by lgarron** [comment]
Oh wait, you guys aren't talking about what we call (SSL) interstitials, but about network error pages.
We have not put in any work to support those, and from a glance it appears the look like HTTP pages Security.SecurityStateChanged (but also end up with a failed request).

crbug.com/504499 is our main bug for this; also see crbug.com/543857

**Comment by Janpot** [comment]
Talking about this page:
<img width="629" alt="screen shot 2016-12-09 at 07 46 42" src="https://cloud.githubusercontent.com/assets/2109932/21040208/c01afb7c-bde3-11e6-9f66-c42233e06fb6.png">
Another option for me would be starting Chrome with a switch that disables this page, if such switch exists.

**Comment by paulirish** [comment]
Thanks for the details on this. I'm folding it into #2784
