### ISSUE TITLE
"Displays images with inappropriate size" is incorrectly reported.

### ISSUE THREAD

**Issue by enmcewan** [GoogleChrome/lighthouse#11238]
#### Provide the steps to reproduce
1. Run LH on https://lauris-webdev.com/cust/cfts4z/ with Device set to Mobile
 
#### What is the current behavior?
Best Practices reports: Displays images with inappropriate size for 
…images/new-logo-clipped-30.png(lauris-webdev.com) | 30 x 30 | 30 x 30 | 90 x 90

![image](https://user-images.githubusercontent.com/28487893/89720198-4b9a9d80-d995-11ea-8df1-283113bc646e.png)

#### What is the expected behavior?
The physical file size is 30 x 30 and even with height & width attributes set to 30px, the same is reported. There's no CSS size transform.
The issue is not reported when LH is run with Device set to Desktop.

This seems to be recent, I've run LH with the last few weeks and not noticed this problem before.

#### Environment Information
* Lighthouse version: 6.0.0
* Chrome version: 84.0.4147.105 (Official Build) (64-bit)
* Operating System: Win10 Pro 10.0.18363 Build 18363

**Comment by patrickhulce** [comment]
Thanks for filing @enmcewan! This is the intended behavior though. Please see https://github.com/GoogleChrome/lighthouse/issues/10802#issuecomment-630233444, https://github.com/GoogleChrome/lighthouse/issues/11169#issuecomment-664693157

**Comment by enmcewan** [comment]
@patrickhulce ah OK, got it. Thanks for the feedback. I did initially search for existing issues but did not see this.
