### ISSUE TITLE
Lighthouse dies on AWS Lambda without any error not getting any audit

### ISSUE THREAD

**Issue by Deepak546** [GoogleChrome/lighthouse#11245]
I am trying to run Lighthouse on Lambda, but Lighthouse appears to die quite early in the test, with no error message, and without throwing an error in the function. Lambda finishes after around 8 seconds, and as far as AWS is concerned, it was successful.

I'm not sure if this is a Lighthouse issue, or Chrome AWS Lambda issue. So, will start here as this seems most logical based on the fact other Puppeteer based code has worked, but Lighthouse is the script that seems to fail.

sometimes lighthouse run complete some website like https://yes.com . but most of cases it is breakdown after getting gathering not collecting audit on aws lambda

**Comment by Deepak546** [comment]
leave a comment if whatever necessary

**Comment by patrickhulce** [comment]
Thanks for filing @Deepak546!

[We can't guarantee support for lambda](https://github.com/GoogleChrome/lighthouse/blob/8b978219bbc53deafe0f705e54b9f47eb1dd89f6/docs/variability.md#run-on-adequate-hardware) though. Some folks have gotten it to work on a subset of sites with a combination of flags, but it's not something we can offer assistance with.
