### ISSUE TITLE
"Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)"

### ISSUE THREAD

**Issue by philraymond** [GoogleChrome/lighthouse#11242]
Lighthouse works on my home page ( https://app.students-helping-students.org/version-test/ ) but not on this page ( https://app.students-helping-students.org/version-test/blank ).

**Comment by philraymond** [comment]
It seems it was because my page was blank. I added a word to the page and then Lighthouse worked again.

**Comment by patrickhulce** [comment]
Thanks for filing @philraymond! This is working as intended. Lighthouse cannot report any performance metrics on page that did not have any content.
