### ISSUE TITLE
Transfer size much bigger than Network Transferred Size or Resource Size on localhost

### ISSUE THREAD

**Issue by enmcewan** [GoogleChrome/lighthouse#11241]
#### What is the current behavior?
LH reports the following:

![image](https://user-images.githubusercontent.com/28487893/89737670-63772d80-da38-11ea-9d2d-b90d16fce30f.png)

Dev Tools Network reports:
![image](https://user-images.githubusercontent.com/28487893/89737714-ca94e200-da38-11ea-8388-1b70c506d8af.png)
which matches the physical file size.

The Remove Unused CSS issue is not reported for this resource when the site is running on a web server so I don't know what the value is there.
The Network Transfer size is down to ~3.5k (due to compression I assume), maybe the check is skipped below a certain threshold?
Other resources are closer in Transfer Size to Network Transfer size but not the same on the web server

All this is confusing and time consuming, trying to reconcile the file sizes and check on the LH reported issue.

#### What is the expected behavior?
Transferred size should match the network transferred size on localhost.

* Lighthouse version: 6.0.0

**Comment by patrickhulce** [comment]
Thanks for filing @enmcewan! 

We don't really have any information to be able to act on this as-is. The transfer size can be different in different environments for many valid reasons. Development environments are often very different from production ones w.r.t file size, common examples to check: compression differences, minification differences, geo differences, UA-sniffing, mobile v. desktop.

If you have a public URL where the number of bytes reported by Lighthouse does not match the number of bytes in DevTools *while matching the same UA, DPR, and server* then we'll happily take a look to fix it.

> maybe the check is skipped below a certain threshold?

Yes, it is that might explain the difference there.

**Comment by enmcewan** [comment]
The [web server](https://lauris-webdev.com/cust/cfts4z/) DevTools shows a resource size of 14.3kB:
![image](https://user-images.githubusercontent.com/28487893/89787942-fe791180-dae3-11ea-922c-4502287d0a9c.png)

This matches the localhost values shown in the original comment, and also the disk size. I don't get why LH comes up with 28k on localhost.

**Comment by patrickhulce** [comment]
This is also exactly what Lighthouse sees. 

![image](https://user-images.githubusercontent.com/2301202/89795828-7cdab100-daee-11ea-9edf-32553662dbc7.png)


I can't see your localhost, but Lighthouse learns about transfer size from exactly the same source as DevTools. If there is a difference from when you load it outside of Lighthouse, it means that *something* made the server return a different payload.  

Is there anywhere publicly accessible where this happens?

**Comment by enmcewan** [comment]
The only thing I can think of would be to get you the site files for you to test locally, could make a repo for you if that works

**Comment by patrickhulce** [comment]
Before you do that, what does the output of 

```
curl -vvvv http://localhost/dist/toolkit-supermin.1.home.css --compressed | wc -c
```

and 

```
curl -vvvv http://localhost/dist/toolkit-supermin.1.home.css -H 'User-Agent: Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Mobile Safari/537.36 Chrome-Lighthouse' --compressed | wc -c
```

tell you? 

You should get two numbers 
1. transfer size printed by `content-length: XXXX` / `{ XXXX bytes of data }`
2. resource size printed by `wc -c`

**Comment by enmcewan** [comment]
< Content-Length: 14327
< Date: Mon, 10 Aug 2020 15:51:32 GMT
< Connection: keep-alive
<
{ [14327 bytes data]
100 14327  100 14327    0     0  2331k      0 --:--:-- --:--:-- --:--:-- 2331k
14327

< Content-Length: 14327
< Date: Mon, 10 Aug 2020 15:54:29 GMT
< Connection: keep-alive
<
{ [14327 bytes data]
100 14327  100 14327    0     0  1748k      0 --:--:-- --:--:-- --:--:-- 1748k
14327

**Comment by patrickhulce** [comment]
Hm, alright then yes a reproducible environment would work. 

The zipped contents of the `latest-run` folder if you run Lighthouse from the command line with `lighthouse http://localhost/ -G` would be even better.

**Comment by enmcewan** [comment]
Here you go
[latest-run.zip](https://github.com/GoogleChrome/lighthouse/files/5052147/latest-run.zip)

**Comment by patrickhulce** [comment]
Thanks @enmcewan! But that report does not have result you describe. Compression is off, but the transfer size is exactly what you expect.

![image](https://user-images.githubusercontent.com/2301202/89814919-87567400-db09-11ea-9207-d39b535f9c7e.png)
![image](https://user-images.githubusercontent.com/2301202/89814962-9b9a7100-db09-11ea-8d5d-25b094772da9.png)

**Comment by enmcewan** [comment]
I see that.
I tried incognito mode, all extension off but still get the 28k in Chrome
![image](https://user-images.githubusercontent.com/28487893/89816177-b241c780-db0b-11ea-8f0a-acc743559f2b.png)

What else to try here, out of ideas

**Comment by enmcewan** [comment]
and since 'the data never lies':
{
            "url": "http://localhost:8044/dist/toolkit-supermin.1.home.css",
            "totalBytes": 28926,
            "wastedMs": 753
          }

**Comment by patrickhulce** [comment]
Heh, I believe you @enmcewan. That's clearly what the value in the report says  :)

The part that I find unlikely is that Chrome isn't receiving a 28KiB asset. We've seen a lot of weird things interfere with results and haven't yet found a case where the size was actually wrong. At this point I'm also running out of ideas but here's what we commonly see that has this effect...

- Brittle UA parsing
- Enterprise Policy
- Browser Extensions
- Software that hijacks Chrome's network stack (Anti-virus most commonly, but also random things like an old HP Printer driver companion)

**Comment by enmcewan** [comment]
I tried incognito + no extensions + anti-virus off  + removed my only printer drive but no luck

**Comment by patrickhulce** [comment]
We might have found the root cause in https://github.com/GoogleChrome/lighthouse/issues/11415 which is DevTools specific, I'll dedupe this issue into that one. Thanks @enmcewan for working with us here!
