### ISSUE TITLE
Logo is reported as having an inappropriate size with an expected size of 97x97px, even though it renders as its actual size.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [GoogleChrome/lighthouse#11240]
#### Provide the steps to reproduce
1. Run LH on https://www.aleksandrhovhannisyan.com/
2. Note that the Best Practices score is 92.
3. Note that one of the images is my logo, which is 32x32px. Lighthouse claims the expected size was 97x97px.
  
![image](https://user-images.githubusercontent.com/19352442/89735700-67a04c80-da32-11ea-835a-c6aa947d186b.png)

#### What is the expected behavior?

The image's actual size is 32x32px, and its rendered size is 32x32px. I'm not sure why Lighthouse is expecting it to be 97x97px.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version:  6.0.0
* Chrome version: 84.0.4147.105 (Official Build) (64-bit) (cohort: Stable)
* Node.js version: N/A
* Operating System: Windows 10 OS Version 1903 (Build 18362.778)

**Comment by patrickhulce** [comment]
Thanks for filing @AleksandrHovhannisyan !

> I'm not sure why Lighthouse is expecting it to be 97x97px.

DPR

Please see https://github.com/GoogleChrome/lighthouse/issues/11238, https://github.com/GoogleChrome/lighthouse/issues/10802#issuecomment-630233444, https://github.com/GoogleChrome/lighthouse/issues/11169#issuecomment-664693157

**Comment by AleksandrHovhannisyan** [comment]
Sounds good, thank you! @patrickhulce
