### ISSUE TITLE
Report: FF rendering issues

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1124]
Lots of cleanup to do in FF.

- The Beta banner is gone
- the check/x's are gone in FF. That's probably because we're using some `-webkit-mask-image` action. They should really just be background images with `background-size: contain`.
- The help toggles are checkboxes instead of images

<img width="1080" alt="screen shot 2016-12-08 at 10 37 46 am" src="https://cloud.githubusercontent.com/assets/238208/21022732/825e0510-bd32-11e6-9d80-ffdf22e16e7c.png">

**Comment by wardpeet** [comment]
what about using autoprefixer?

**Comment by ebidel** [comment]
Autoprefixer is available internally at Google, so we could use it if we wanted to.

For the checkbox issue, I think we'll need a different solution than `-webkit-mask-image`. That's a webkit-only feature.

This would work. Get rid of the mask stuff and use:

```
background: url(data:image/svg+xml;utf8,<svg width="12" height="12" viewBox="0 0 12 12" xml…L2.33 3.66l1.33-1.33 2.335 2.335z" fill="#FFF" fill-rule="evenodd"/></svg>) no-repeat 50% 50%;
background-size: 12px;
```

**Comment by Janpot** [comment]
For the beta banner, it starts working when I url encode the svgs. Seems like firefox chokes on `#`. (http://stackoverflow.com/a/37683760)
Tried autoprefixer but it looks like `mask` isn't well supported yet.
`background` would work but that will lose the flexibility of styling them.

another nice option is inlining them as symbols in the html, then reference them through `<use xlink:href="...">` (https://css-tricks.com/svg-symbol-good-choice-icons/)

**Comment by XhmikosR** [comment]
Has anybody started working on this? I'm a Firefox user and I could put together a patch to switch to just background image or whatever else you prefer.

We could also just use the `:after` pseudo selector with the unicode characters in its `content`.

**Comment by wardpeet** [comment]
no one did :) feel free to start

**Comment by XhmikosR** [comment]
I'll do, in the next days. :)

**Comment by XhmikosR** [comment]
OK, so I experimented with this.

The easiest solution is to do what @Janpot suggested above: URL encode the SVGs.

So far, all SVGs display properly except for the checkbox.

So with [this](https://github.com/GoogleChrome/lighthouse/compare/master...XhmikosR:viewer-ff-fixes) branch this is what I get:

**Before**
![before](https://cloud.githubusercontent.com/assets/349621/21841565/62c0985c-d7eb-11e6-9be0-8d621de73941.png)

**After**
![after](https://cloud.githubusercontent.com/assets/349621/21841574/673c920a-d7eb-11e6-8f48-14216c1c7089.png)

Is that an acceptable solution? If so, I'll make a PR.

**Comment by Janpot** [comment]
maybe something that can/should? be done by a CSS postprocessor?

**Comment by ebidel** [comment]
Since we only have a few of these, introducing new tooling to urlencode seems overkill.

I was able to get this working in FF:

```
background: url('data:image/svg+xml;utf8,<svg width="12" height="12" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg"><title>poor</title><path d="M8.33 2.33l1.33 1.33-2.335 2.335L9.66 8.33 8.33 9.66 5.995 7.325 3.66 9.66 2.33 8.33l2.335-2.335L2.33 3.66l1.33-1.33 2.335 2.335z" fill="white"/></svg>') no-repeat 50% 50%;

FF seems to be happy with the quotes are the data url and moving from `#fff` => "white" for the fill color fixes the urlencoding issue. We can use color names for the others.

I'd be up for using `::after` `content` with the unicode values if we can make that look decent.

**Comment by XhmikosR** [comment]
I'll experiment with the pseudo selectors solution for the symbols when I
have some time.

**Comment by wardpeet** [comment]
I can have a look as well if you like @XhmikosR but feel free to do so, it's not urgent :)

**Comment by XhmikosR** [comment]
@wardpeet: I made some progress in my branch but needs more work. See https://github.com/GoogleChrome/lighthouse/compare/master...XhmikosR:viewer-ff-fixes

Do you want me to make a PR so that you can push too?
