### ISSUE TITLE
Is there any reason for getting lower performance score when running lighthouse programatically? 

### ISSUE THREAD

**Issue by cagilan** [GoogleChrome/lighthouse#11252]
**Summary**
**My Desktop/Mobile test script config:**
```
const lighthouseConfig = {
  settings: {
    extends: 'lighthouse:default',
    settings: {
      onlyCategories: ['performance'],
    },
  },
  disableNetworkThrottling: true,
  disableStorageReset: false,
  emulatedFormFactor: 'desktop / mobile //(switch to run for desktop or mobile)',
  throttlingMethod: 'provided',
  output: 'html',
  chromeFlags: [
    '--headless',
  ]
};
```
I'm using this config for my lighthouse scripts to see the performance of my web page.

I noticed 2 different behaviors when running my script with this config. 

1. I see around 70-80% of the performance score for mobile and see only 50-60% of the score for desktop. 

2. I see really good score when I run the lighthouse from the chrome developer tool manually rather than do it via my test scripts using the lighthouse as an npm package.

Note: I'm running my lighthouse scripts in my local machine where I do start my own server, then run my lighthouse scripts, get performance score, and assert the score using the Jest framework.

**Comment by patrickhulce** [comment]
`throttlingMethod: 'provided'` basically says "all consistency bets are off I am carefully managing my own throttling settings". You might also be interested in the [variability documentation](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) which describes many of the factors that result it different performance scores.

**Comment by cagilan** [comment]
What will be the correct or advisable config to run lighthouse scripts programmatically for mobile and desktop? 

Im using this below config,

const lighthouseConfig = {
  settings: {
    extends: 'lighthouse:default',
    settings: {
      onlyCategories: ['performance'],
    },
  },
  disableNetworkThrottling: true,
  disableStorageReset: false,
  emulatedFormFactor: 'desktop',
  throttlingMethod: 'provided',
  output: 'html',
  chromeFlags: [
    '--headless',
  ]
};

I see the really good score when I run lighthouse audit using chrome dev tools for my localhost application whereas I see low scores when I run my scripts programmatically... 

Is it also related to variability factors?

**Comment by patrickhulce** [comment]
> Is it also related to variability factors?

Yes it almost definitely is. 

This is desktop throttling settings used by DevTools if you'd like to try to match it as closely as possible.

https://github.com/GoogleChrome/lighthouse/blob/79ea8cc970ca8feab72b530b29268f134a254799/lighthouse-core/config/constants.js#L41-L50

**Comment by cagilan** [comment]
Thanks I will try with this config @paulirish

**Comment by Lewiscowles1986** [comment]
@patrickhulce where did you get that profile `desktopDense4G` from?

I'm having issues and would like to directly mimic what the google chrome lighthouse is doing for mobile & desktop
