### ISSUE TITLE
Bulk analysis for CLS optimization audits

### ISSUE THREAD

**Issue by lemcardenas** [GoogleChrome/lighthouse#11256]
**Summary**
As a restricted intern, I was informed by someone with techstop that I likely won't be able to run GCP scripts `lighthouse-core/scripts/gcp-collection`.

In order to analyze the recent and upcoming `unsized-images`, `jankless-font`, and `unsized-iframes` audits for false positives, false negatives, and CLS correlation, among other things, I would appreciate if someone with access to lighthouse's GCP instances ran the `lighthouse-core/scripts/gcp-collection`, with `lighthouse-core/scripts/gcp-collection/urls.txt` replaced with [this](https://pastebin.com/pLbp0FiX) list of URLs.

I would then just need the zip of all the lhrs and can do the analysis on my local machine!

**Comment by connorjclark** [comment]
Googlers: https://drive.google.com/drive/folders/1YtHGYlKgLx4QcTBjbQ9JRHBmCwAfLj_t?usp=sharing

**Comment by patrickhulce** [comment]
@connorjclark took care of this like a boss 🕴️
