### ISSUE TITLE
Make the large-javascript-libraries audit a performance opportunity

### ISSUE THREAD

**Issue by saavannanavati** [GoogleChrome/lighthouse#11265]
**Summary**
This would entail estimating the *actual* network cost of using the library that we suggest replacing for a particular website (to account for tree-shaking) versus the *theoretical* network cost of our suggested replacement library (in its entirety, since we can't know what to tree-shake). The difference between these two values would be the `estimated savings` for the performance opportunity.

**Comment by patrickhulce** [comment]
We're closing this in favor of the feedback in #11423
