### ISSUE TITLE
Do not emit “The page does not contain a skip link” warnging on 1kb pages.

### ISSUE THREAD

**Issue by dilyanpalauzov** [GoogleChrome/lighthouse#11264]
**Describe the bug**
I “scan” at https://web.dev/measure/ for https://x.bapha.be/s/0/f78e45c4d256da187e946199fc2625c553f46cdf_bg.html .  

The report says: Accessibility: “The page does not contain a heading, skip link, or landmark region”.

Since the scanned page is 1kb, there is no point to include a skip-link in it. In this case the Accessibility hint is not justified.

**Comment by robdodson** [comment]
You could resolve this test by adding a `main` landmark element to your page:

```
<body>
  <main>
    ...
  </main>
</body>
```

I don't think Lighthouse can really determine whether it's valid or not to suggest an accessibility fix based on page size (you could have a 1kb page that really does need a heading or main element). The tests are meant as suggestions and we recommend folks always verify whether the warnings are valid by manually checking their site.
