### ISSUE TITLE
aria-valid-attr-value: allow numbers with comma as decimal separator

### ISSUE THREAD

**Issue by placetobejohan** [GoogleChrome/lighthouse#11263]
Numbers that use a comma as decimal separator - eg **aria-valuenow="68885,8"** - now trigger the [[aria-*] attributes do not have valid values](https://web.dev/aria-valid-attr-value/) error.

I wonder if it's possible to allow the comma as a decimal separator, perhaps based on the current UI culture?

**Comment by patrickhulce** [comment]
Thanks for filing @placetobejohan! Have you tried to search for answers in [axe-core](https://github.com/dequelabs/axe-core/)? The logic for the accessibility audits is all controlled by that project. We'll respect whatever they decide there.

**Comment by placetobejohan** [comment]
Thanks for the swift reply, I've filed the issue there: https://github.com/dequelabs/axe-core/issues/2450
