### ISSUE TITLE
Establish an audit naming guide

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#11266]
**Summary**

With a lot of new audits recently we've had to discuss audit names several times. I think it'd be cool to formalize this into specific guidance on naming and attempt to standardize our existing audit names as much as possible :)

Doing a quick review...

- noun of the stuff/topic being surfaced e.g. `dom-size`, `deprecations`, `non-compsitable-animations`, `unsized-images`, `doctype`
  - def the most common, shoot for this?
- phrase that describes the behavior the page or developer *should* exhibit e.g. `no-vulnerable-libraries`, `works-offline`, `external-anchors-use-rel-noopener`, `uses-http2`
  - mostly complete the phrase "ideally, the page ..."
  - some complete the phrase "ideally, the developer of the page ..."
  - some complete the phrase "ideally, the page uses/has ..."
  - some are complete phrases on their own

**Comment by paulirish** [comment]
Good call raising this.

> phrase that describes

👎.  the verbs in some of our audits (eg "uses-preload", etc) kill me. okay looks like it's okay "uses" and "use". 

i also don't think the "no-" prefix is terribly useful and ideally we'd drop it, but no biggie.

> noun of the stuff/topic being surfaced

👍 . I also really like when there are common keywords between the failureTitle and audit.  `bootup-time` and `mainthread-work-breakdown` give me a hard time regularly since they dont share much with their titles.

**Comment by patrickhulce** [comment]
> the verbs in some of our audits (eg "uses-preload", etc) kill me
> give me a hard time regularly since they dont share much with their titles.

😢 but, but, the `uses-blah` is exactly during the phase of trying to align the audits with their titles

> okay looks like it's okay "uses" and "use".

I got lost here 😆 is `uses-` ok afterall? 😃 

In general I agree I generally prefer the noun of the stuff/topic being surfaced but for all the ones that are `uses-X` it's where the natural way to describe the thing being surfaced is the *opposite* direction, i.e. people never really talk about "non-responsive images" we just talk about "responsive images" so "uses-responsive-images" feels better than "non-responsive-images". I would ideally want to avoid a situation where we're consistent on nouns but then keep flip flopping on whether it's the positive or negative form and get back into the title confusion situation all over again.

**Comment by paulirish** [comment]
We'll only be applying this policy going forward. 

Breaking changes break hearts. ❤️ 🔨 


----

Policy: no `no-`, no verbs. Adjective modifiers are acceptable.

**Comment by paulirish** [comment]
TODO: Add to contributing/new-audits documentation.
