### ISSUE TITLE
async css pattern results in recording duplicate network requests

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11269]
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="styles.css" media=none></link>
</head>
<body>
  hi

  <script>
    setTimeout(() => {
      document.querySelector('link').media = 'all';
    }, 300);
  </script>
</body>
</html>
```

```css
body {
  background-color: blue;
}

```

![image](https://user-images.githubusercontent.com/4071474/90280970-6f486280-de31-11ea-9a2a-948ee9055cd8.png)
![image](https://user-images.githubusercontent.com/4071474/90280989-78d1ca80-de31-11ea-9966-88d72565bff6.png)

Change the timeout to 0 and only one styles.css is recorded.

**Comment by patrickhulce** [comment]
On first blush this sounds like a Chromium bug @connorjclark was there a Lighthouse action item to take? :)

**Comment by connorjclark** [comment]
> On first blush this sounds like a Chromium bug @connorjclark was there a Lighthouse action item to take? :)

Not yet. We'll see.

https://bugs.chromium.org/p/chromium/issues/detail?id=1116544

**Comment by patrickhulce** [comment]
The upstream bug was closed as WAI due to the cache headers of the provided URL. If browser perspective will load these resources twice, then Lighthouse should reflect them that way too 👍
