### ISSUE TITLE
Working service worker, but Lighthouse does not recognize

### ISSUE THREAD

**Issue by a-tonchev** [GoogleChrome/lighthouse#11262]
#### Provide the steps to reproduce
1. Run LH on https://shop.human-by-definition.com/
  
#### What is the current behavior?
Service worker is registered and running, can Install PWA on mobile device and PC, but Lighthouse say that there is no PWA

#### What is the expected behavior?
Lighthouse should recognize the active service worker

#### Environment Information
* Lighthouse version: Inbuild in Chrome
* Chrome version: 84.0.4147.125

I have a production build based on CRA, service worker is registered and works proper:

![image](https://user-images.githubusercontent.com/54528540/90114228-1d350d80-dd5b-11ea-843a-59e9b0d753a6.png)

But lighthouse does not recognize it:

![image](https://user-images.githubusercontent.com/54528540/90114327-3ccc3600-dd5b-11ea-9c76-9bc980395975.png)

Where could be the problem. In early project with same CRA everything works perfect...

**Comment by patrickhulce** [comment]
Thanks for filing @a-tonchev! I can reproduce this we'll have to look into it.

**Comment by a-tonchev** [comment]
@patrickhulce After investigation I think the problem is that my site has too many chunks, when the website opens and service worker try to pick all resources, there are 100+ requests to the server, and I think the server does not allow so many requests.

**Comment by a-tonchev** [comment]
That was also the problem:

https://github.com/GoogleChrome/lighthouse/issues/11262#issuecomment-673591709

Problem solved
