### ISSUE TITLE
Programatically run lighthouse with self-signed cert to TLS secure website

### ISSUE THREAD

**Issue by melvida** [GoogleChrome/lighthouse#11281]
I'm using 6.2.0

**Feature request summary**

I would like to run lighthouse plugin against a web app that has self-signed certificates. While trying to run against a local server with self-signed certificates, lighthouse returns audit scores that are 0. 

I would like to pass my certificate as chrome-flag to lighthouse so it can still run the performance and accessibility scores.

**What is the motivation or use case for changing this?**
My web app is secure with self-signed certificates and I cannot run lighthouse either programatically or at the CLI against it even with the chrome-flag --ignore-certificate-errors
**How is this beneficial to Lighthouse?**
Lighthouse can audit secure websites and return performance and accessibility scores for websites that have self-signed certs.

**Comment by patrickhulce** [comment]
Thanks for filing @melvida! This should work already could you provide repro steps for the bug you're seeing?

`lighthouse https://self-signed.badssl.com/ --chrome-flags=--ignore-certificate-errors` works just fine in 6.2.0 on my machine.

**Comment by patrickhulce** [comment]
I'm going to go ahead and assume https://github.com/GoogleChrome/lighthouse/issues/11281#issuecomment-678330654 fixed the issue, but if you still think there's a bug here, please feel free to come back with more info to reopen :)
