### ISSUE TITLE
"contribute to CLS" => "increase CLS"?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#11287]
This is somewhat nitpicky, but it would be good to align our phrasing.

The `non-composited-animations` audit says "Animations which are not composited can be janky and contribute to CLS." To me, "…increase CLS" makes more sense. An increasing CLS score is the bad thing that you want to avoid.

**Comment by patrickhulce** [comment]
Do you want to just update this in your PR? https://github.com/GoogleChrome/lighthouse/pull/11258 :)
