### ISSUE TITLE
Error! in 3 diagnostics sections

### ISSUE THREAD

**Issue by brentlogan** [GoogleChrome/lighthouse#11297]
#### Provide the steps to reproduce
1. Run LH on https://brentlogan.com/
  
#### What is the current behavior?
* The first three dianotics items are resulting in an Error! message

![image](https://user-images.githubusercontent.com/14060692/90843106-bf359680-e315-11ea-998b-4707dc1f6c13.png)

#### What is the expected behavior?
* No errors

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 6.2.0
* Chrome version: 86.0.4239.0 (Official Build) canary (x86_64)
* Node.js version: N/A
* Operating System: macOS Catalina Version 10.15.6

**Related issues**

**Comment by connorjclark** [comment]
Thanks for the report!

![image](https://user-images.githubusercontent.com/4071474/90850496-6b3ba980-e337-11ea-8503-50a61603f6b5.png)

cc @adamraine
