### ISSUE TITLE
Minify JavaScript audit false positives with ES2015 code

### ISSUE THREAD

**Issue by clydin** [GoogleChrome/lighthouse#11295]
#### Provide the steps to reproduce

A newly generated [Angular CLI](https://github.com/angular/angular-cli) project with routing enabled will generate a minify JavaScript audit failure.
Steps:
1) `npx @angular/cli@10.0 new test-project --routing --style=css`
2) `cd test-project`
3) `npm run ng serve -- --prod --no-live-reload`
4) `lighthouse --view http://localhost:4200/` 

#### What is the current behavior?

The Minify JavaScript audit will be reported for the default ES2015 output even though the files are minified.
If the application is changed to target ES5 (within `tsconfig.base.json`) the audit does not report any minify JS issues.

The issue may be related to nested string template literals; potentially in combination with other code structures.

Further analysis can be found in the following repository: https://github.com/clydin/lighthouse-test (README has an overview)

#### What is the expected behavior?

The minify JavaScript audit passes for both an ES2015 targeted and ES5 targeted production application.

#### Environment Information
* Affected Channels: All
* Lighthouse version: 6.2.0
* Chrome version: 84.0.4147.135
* Node.js version: 12.18.2
* Operating System: Any

**Related issues**

**Comment by rrdlpl** [comment]
any news on this?  I'm also affected by this issue

**Comment by patrickhulce** [comment]
I can reproduce this, we'll look into it. [Here's the JS file](https://gist.github.com/patrickhulce/cfd00e2cfe3ac7de32a6d7e5bad51d80) that Lighthouse thinks can be minified further even though it's already minified.

**Comment by patrickhulce** [comment]
heh, this is a good one :) the minification estimator doesn't support nested template literals, i.e. strings of the form

```js
const myString = `foo${`bar${`baz${`bam`}`}`}`
```

it's a really tricky technical change to convert from our set of booleans of JS parse state to a stack but the test case is clear and its in a pretty self contained area of the codebase if anyone is interested in an impactful contribution

Basically we want the following test case to pass in `lighthouse-core/test/lib/minification-estimator-test.js`

```js
it('should handle nested template literals', () => {
  const nestedTemplates = 'window.myString=`foo${` bar ${` baz ${` bam `} `} `} `';
  expect(computeJSTokenLength(nestedTemplates)).toEqual(nestedTemplates.length);
});
```

**Comment by rafa-as** [comment]
@clydin when will it be published to PageSpeed Insights ?

![Screenshot 2021-01-18 at 10 26 46](https://user-images.githubusercontent.com/594574/104896676-beae3400-5977-11eb-9a36-0b622965ed3f.png)
