### ISSUE TITLE
Protocol error (Page.getInstallabilityErrors): PWA not implemented in Opera

### ISSUE THREAD

**Issue by biswabijaya** [GoogleChrome/lighthouse#11309]
Protocol error (Page.getInstallabilityErrors): PWA not implemented in Opera
```
Channel: DevTools
Initial URL: https://acadedge.com/home/
Chrome Version: 84.0.4147.105
Stack Trace: Error: Protocol error (Page.getInstallabilityErrors): PWA not implemented in Opera
    at Function.fromProtocolMessage (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1898:121)
    at eval (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1417:246)
```
![ERROR Screenshot 2020-08-25 at 3 28 43 AM](https://user-images.githubusercontent.com/22062430/91100699-4ae75400-e683-11ea-9b18-e1aa2560e797.png)

**Comment by patrickhulce** [comment]
Thanks for filing @biswabijaya! This is an Opera issue. Please [file an Opera bug](https://help.opera.com/en/computer-bug-wizard/). See #11293

**Comment by borisdiakur** [comment]
I don't think this is entirely an Opera Issue. As you can see in the attached screenshot I'm executing accessibility tests only. I would expect PWA related tests to be run only if the PWA option is selected.

![Screenshot 2021-05-04 at 11 30 31](https://user-images.githubusercontent.com/527049/116986064-a2879600-accd-11eb-80f7-c3a1e1db599b.png)

**Comment by patrickhulce** [comment]
@borisdiakur it is an Opera issue. Opera has removed methods that Lighthouse needs by default, on every run, regardless of the category selected.
