### ISSUE TITLE
Speed Index is NaN

### ISSUE THREAD

**Issue by xorgy** [GoogleChrome/lighthouse#11314]
#### Provide the steps to reproduce
1. Run LH on https://qui.suis.je/

#### What is the current behavior?
The Speed Index field is Not a Number, which errors out the whole Performance section.

#### What is the expected behavior?
The Speed Index should be a number.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 6.0.0
* Chrome version: 84.0.4147.125 (Official Build)
* Operating System: Arch Linux (64-bit)

**Related issues**
![trace](https://user-images.githubusercontent.com/1272018/91194287-8a478c00-e6e7-11ea-80bb-b45d640ff248.png)

**Comment by patrickhulce** [comment]
Thanks for filing @xorgy! This has already been fixed and should arrive in Chrome in the coming weeks.

see https://github.com/GoogleChrome/lighthouse/issues/11154

**Comment by xorgy** [comment]
Sorry, wasn't able to find it. Thank you. :+ )
