### ISSUE TITLE
can't test the multiple pages in same url

### ISSUE THREAD

**Issue by vishal-lko** [GoogleChrome/lighthouse#11312]
I need help in running tool in my website, in my website it has multiple pages option but also when i go from one page to another the url does not change only there is switch from one frame to another, this makes the lighthouse to check only home page but i want to check multiple pages, so could u please help.

**Comment by patrickhulce** [comment]
Lighthouse does not yet support what you're describing you'll need to make each page that you want to audit accessible via a unique URL.

We're just kicking off an effort to address this request though, you can follow along at https://github.com/GoogleChrome/lighthouse/issues/11313 :)
