### ISSUE TITLE
Display "<1" when rounding down to 0

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#11316]
This came up in https://github.com/GoogleChrome/lighthouse/pull/11290:

![image](https://user-images.githubusercontent.com/6752989/91225993-689fd200-e6f2-11ea-81bb-2a28b9bc72c5.png)

The granularity is 1 so the transfer sizes of some payloads get rounded down to 0.  In these cases I think it would be better to display something like "<1 KiB" to make it clear that Lighthouse didn't bug out and some small amount of data was fetched.  I think this applies to pretty much any unit but are some units better displayed as is?

**Comment by patrickhulce** [comment]
Great idea for the report to do this when value isn't truly 0 👍 

9/10 though I would say it's a bug in the audit that it's trying to surface something that had 0 KiB :)

**Comment by connorjclark** [comment]
does i18n complicate this?

**Comment by paulirish** [comment]
> 9/10 though I would say it's a bug in the audit that it's trying to surface something that had 0 KiB :)

yeah i think we should be filtering out any items have have 0 in both columns.

**Comment by adamraine** [comment]
> does i18n complicate this?

Looks like we can't be sure what format the number will be coming out of `Intl.NumberFormat`:
https://github.com/GoogleChrome/lighthouse/blob/7e2ce68df6caaede7e0f5c07007e169a0b651015/lighthouse-core/report/html/renderer/i18n.js#L42-L50
It's still possible to implement this if putting a "<" in front of a number makes sense for all languages, but I'm willing to bet that the "<1" format is not universal.

> yeah i think we should be filtering out any items have have 0 in both columns.

@paulirish Are you talking about items that display 0 or have an original value which is exactly 0?

**Comment by Haugf** [comment]
@adamraine are we waiting to confirm if <1 is universal before moving forward with resolving this?

**Comment by adamraine** [comment]
@Haugf yes.

**Comment by connorjclark** [comment]
We prefer to not show items with such small byte/time values in the first place, but trimming inside the audit class.
