### ISSUE TITLE
Always showing Aspect Ratio (Actual) as 300x150 (2.00) for AVIF files

### ISSUE THREAD

**Issue by BillGoldstein** [GoogleChrome/lighthouse#11315]
#### Provide the steps to reproduce
1. Run LH on a page with an AVIF file
  
#### What is the current behavior?
Best Practices warning "Displays images with incorrect aspect ratio"
Always showing Aspect Ratio (Actual) as 300x150 (2.00) for AVIF files

#### What is the expected behavior?
Use the real AVIF aspect ratio

#### Environment Information
* Affected Channels: Lighthouse DevTools
* Lighthouse version: 5.71
* Chrome version: Chromium snapshot morning of 2020-08-25 
* Node.js version:
* Operating System: Win10/64

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @BillGoldstein!

> Run LH on a page with an AVIF file

This does not seem to be a sufficient repro. Do you have a specific URL?

https://reachlightspeed.com/blog/using-the-new-high-performance-avif-image-format-on-the-web-today/ for example does not report this issue and uses AVIF.

**Comment by BillGoldstein** [comment]
Sorry about that...repro's 100% on my test system, but on its live production system, Lighthouse doesn't even get that far.
Will work on getting a reduced test case.  Snagged a copy of the .avif file on the page you mentioned, too. Mine was created by an online converter, but displays fine in FF/Chromium&derivatives/Irfanview/Win10 Paint, FWIW.

**Comment by thierryk** [comment]
I ran into this issue using `srcset` with x-descriptors; I created [this page](https://thierryk.github.io/AVIF/) to show the problem.

**Comment by patrickhulce** [comment]
Thanks very much for the example page @thierryk! I can reproduce that one. Even though it's not an aspect ratio problem in your case, I suspect that the underlying problem about fetching natural size dimensions is the same 👍

**Comment by patrickhulce** [comment]
Hm, actually I cannot reproduce this issue on https://thierryk.github.io/AVIF/ anymore :/ Did you happen to change the underlying page at all @thierryk? Can you still reproduce this?

**Comment by paulirish** [comment]
https://github.com/thierryk/AVIF/commits/master indicates nothing about the test page changed afer you viewed it  there's just a populated readme now: https://github.com/thierryk/AVIF

also hi @thierryk ! 👋  really good to see you.

**Comment by patrickhulce** [comment]
> https://github.com/thierryk/AVIF/commits/master indicates nothing about the test page changed afer you viewed it there's just a populated readme now

True but after your cross-repo deploy magic that I thought was impossible @paulirish I take the git history of the repo as `github.io` evidence with a grain of salt 😆 

The root cause for the bug would've most likely been that Lighthouse received unexpected `naturalHeight`/`naturalWidth` values for the AVIF image. Maybe Chrome fixed an AVIF related issue here? (Though I don't see it with stable either :/) 

I mean can you reproduce this result on https://thierryk.github.io/AVIF/ @paulirish?

**Comment by thierryk** [comment]
I cannot reproduce either. :tada:

@paulirish :vulcan_salute: Thanks! Happy to cross path with you again.

**Comment by patrickhulce** [comment]
Great, thanks very much for the repro all the same @thierryk! Not sure who we have to thank for the fix but glad it's working now 😄
