### ISSUE TITLE
Avoid Long Main Thread Tasks retrieves and reports the same resources multiple times

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/lighthouse#11320]
Windows 8.1
Chrome Canary Version 87.0.4244.0 (Official Build) canary (64-bit)
Incognito Mode
Lighthouse 6.2.0
Mobile Audit
All Categories Selected
Site audited: https://thomasbrodhead.com

**Avoid Long Main Thread Tasks** reports the same resources being retrieved twice, the **…minified-modules/common.min.202….mjs** resource twice and the domain itself (https://thomasbrodhead.com) twice:

…minified-modules/common.min.202….mjs(thomasbrodhead.com) | 8,832 ms | 124 ms
https://thomasbrodhead.com | 2,022 ms | 109 ms
…minified-modules/common.min.202….mjs(thomasbrodhead.com) | 8,689 ms | 96 ms
https://thomasbrodhead.com | 1,907 ms | 78 ms
/analytics.js(www.google-analytics.com) | 10,647 ms | 62 ms

That shouldn't be the case. This duplication also happens when I run the current PageSpeed Insights, which uses Lighthouse 6.1.0. Notice that it retrieves and demerits the **…minified-modules/common.min.202….mjs** resource **3** times:

https://thomasbrodhead.com | 993 ms | 164 ms
/analytics.js(www.google-analytics.com) | 9,720 ms | 107 ms
…minified-modules/common.min.202….mjs(thomasbrodhead.com) | 7,855 ms | 99 ms
…minified-modules/common.min.202….mjs(thomasbrodhead.com) | 7,764 ms | 91 ms
https://thomasbrodhead.com | 930 ms | 63 ms
…minified-modules/common.min.202….mjs(thomasbrodhead.com) | 7,710 ms | 54 ms
/gtag/js?id=UA-141…-1(www.googletagmanager.com) | 8,823 ms | 53 ms

When I record a page load of this site in DevTools, the network only shows these resources being retrieved once each. Why is Lighthouse apparently erroneously retrieving them multiple times, and then counting those duplicate retrievals against my score?

(This is not new to Chrome Canary 87, it's something I've notice for some time but only am now getting around to investigating.)

**Comment by patrickhulce** [comment]
Thanks for filing @tmb-github but this is intentional. It's not reporting individual resources to you it's reporting the *tasks* on the main-thread that those resources caused. 

Is there a description other than "Lists the longest tasks on the main thread" that would've made this clearer?

**Comment by tmb-github** [comment]
@patrickhulce The problem isn't the description, it's that the same resource is being reported multiple times. For each offending resource, could you not just list it once?

But maybe I'm misunderstanding things. You say that tasks are being created by each listed resource. So, is the order of resources in the report the order of the tasks that are long-running? So, for the .mjs script that reappears multiple times in my reports, is it that it is triggering/executing tasks that then are considered long running, and each time the script kicks off a long-running process, that process then triggers an entry in the report?

**Comment by patrickhulce** [comment]
> it's that the same resource is being reported multiple times

This table is not reporting resources to you. It is reporting *long tasks*. A single script can create an infinite number of long tasks. 

**forever.js**
```js
setInterval(() => {
  const start = Date.now();
  while (Date.now() - start < 100) ;
}, 1000)
```

These rows are not duplicates. Every row is a different long task that was created by the listed script. (Their start times and durations are unique)

**Comment by tmb-github** [comment]
@patrickhulce  It would be helpful to be able to correlate the resource listed with the long-running task it is generating, such as what the Performance tab provides in DevTools via recording a page load. 

With that tool, we can see what's taking a long time to run. and often pinpoint precise routines in our JavaScript that are the culprit. But the present test doesn't offer that info, and running the page load after the test isn't helpful, because it records it with different settings and provides different values than what is shown in Lighthouse (we'd have to guess which network speeds to use, etc., before performing the test, etc.)

Wouldn't it be more helpful, in addition to indicating the resource with the long-running process, to provide screenshots of the kinds of diagrams shown after the page load Performance tab test in DevTools?

In the case of the report I provided in my initial message, my site itself is listed twice (see that it simply says https://thomasbrodhead.com with millisecond counts), and that's not helpful at all: what on my site is causing the slow down? The JavaScript? The CSS? The loading of resources?

It's great that the tool indicates that there are areas that could be improved, but currently it doesn't help the user identify precisely what is taking place that needs attention. Some kind of graph like that generated by the page load Performance tab test would be helpful.

**Comment by patrickhulce** [comment]
> Wouldn't it be more helpful, in addition to indicating the resource with the long-running process, to provide screenshots of the kinds of diagrams shown after the page load Performance tab test in DevTools?

> Some kind of graph like that generated by the page load Performance tab test would be helpful.

That is exactly the plan, someone is already working on it https://github.com/GoogleChrome/lighthouse/issues/10806
