### ISSUE TITLE
LHError: TRACING_ALREADY_STARTED on cucumber/protractor setup

### ISSUE THREAD

**Issue by ajoecker** [GoogleChrome/lighthouse#11321]
We try Lighthouse in our company (i cannot post url/code for that :( ) with a cucumber / protractor setting. 

When running Lighthouse it fails with the following message:

```
Wed, 26 Aug 2020 07:43:00 GMT method => browser:verbose Storage.clearDataForOrigin
    × failed
      LHError: TRACING_ALREADY_STARTED
          at Function.fromProtocolMessage (C:\dev\ui\e2e\node_modules\lighthouse\lighthouse-core\lib\lh-error.js:134:14)
          at C:\dev\cui\e2e\node_modules\lighthouse\lighthouse-core\gather\connections\connection.js:124:25
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
Wed, 26 Aug 2020 07:43:00 GMT method <= browser OK:verbose Storage.clearDataForOrigin
Wed, 26 Aug 2020 07:43:00 GMT statusEnd:verbose Disconnecting from browser...
```
Full log
[lighthouse.log](https://github.com/GoogleChrome/lighthouse/files/5128437/lighthouse.log)
#### Environment Information
* Lighthouse version: 6.2.0
* Chrome version: 84.0.4147.135
* Node.js version: 12.18.3
* Operating System: Windows 10 / Ubuntu 20.04 LTS

**Related issues**

**Comment by ajoecker** [comment]
I do not believe this is a duplicate - I cannot restart Chrome, as chrome is started automatically as part of the automated testing solution.

**Comment by patrickhulce** [comment]
@ajoecker this is a duplicate, but there's a new solution try using the Chrome flag `--force-fieldtrials=*BackgroundTracing/default/`. I'll add this suggestion to that issue.

**Comment by ajoecker** [comment]
thanks @patrickhulce for the input - the flag did unfortunately not change anything

**Comment by patrickhulce** [comment]
Just double checking @ajoecker  but you were using this flag for *Chrome* not Lighthouse, correct?

**Comment by ajoecker** [comment]
@patrickhulce yes
```
 chromeOptions: {
      args: ['--test-type=browser', '--no-sandbox', '--remote-debugging-port=4445', '--force-fieldtrials=*BackgroundTracing/default/'],
```

**Comment by patrickhulce** [comment]
Oh what is using that `chromeOptions`? Is it another library that could have started tracing already? Chrome can only be told to start tracing by one connection at a time.

**Comment by ajoecker** [comment]
this comes from the `protractor.cucumber.conf.js` for our protractor/cucumber setup. I cannot say whether this already start tracing - if possible - is it possible to switch it off for lighthouse ? Or does it make it not functional ?

thanks so much @patrickhulce for helping

**Comment by patrickhulce** [comment]
> is it possible to switch it off for lighthouse ? Or does it make it not functional ?

It mostly breaks Lighthouse. You could run a limited subset of Lighthouse without tracing though. `--only-categories=accessibility` for example might work.

**Comment by ajoecker** [comment]
this fails then with

```
Wed, 09 Sep 2020 07:54:03 GMT status:verbose Create config
Wed, 09 Sep 2020 07:54:03 GMT status:verbose Requiring gatherers
Wed, 09 Sep 2020 07:54:03 GMT statusEnd:verbose Requiring gatherers
Wed, 09 Sep 2020 07:54:03 GMT status:verbose Requiring audits
Wed, 09 Sep 2020 07:54:03 GMT statusEnd:verbose Requiring audits
    × failed
      TypeError: categoryIds.forEach is not a function
          at Function.filterCategoriesAndAudits (C:\dev\ui\e2e\node_modules\lighthouse\lighthouse-core\config\config.js:611:17)
          at Function.filterConfigIfNeeded (C:\dev\ui\e2e\node_modules\lighthouse\lighthouse-core\config\config.js:569:54)
          at new Config (C:\dev\ui\e2e\node_modules\lighthouse\lighthouse-core\config\config.js:355:12)
          at generateConfig (C:\dev\ui\e2e\node_modules\lighthouse\lighthouse-core\index.js:59:10)
          at lighthouse (C:\dev\ui\e2e\node_modules\lighthouse\lighthouse-core\index.js:43:18)
```

at one point i simply might give up - it does not seem to be efficient and working for me :(

**Comment by patrickhulce** [comment]
Are you invoking Lighthouse via node? `onlyCategories` needs to be an array `onlyCategories: ['accessibility']`

And sorry to hear that @ajoecker but it's a hard limitation of Chromium atm that only one tool can be tracing at a time, splitting up the runs so LH runs separately is the only path forward I see to this not being so painful.
