### ISSUE TITLE
 Inconsistency between Panel Performance and LCP time

### ISSUE THREAD

**Issue by javier-fernandez** [GoogleChrome/lighthouse#11322]
Lighthouse determines an LCP time of almost 3 seconds, but the Performance panel shows much less data.

**Lighthouse**

![image](https://user-images.githubusercontent.com/1269864/91290677-32b32a00-e794-11ea-8f39-19a429b13b2c.png)

**Performance Panel**

![image](https://user-images.githubusercontent.com/1269864/91290694-3a72ce80-e794-11ea-9052-97dab57ec737.png)

Other additional information in case they are of interest:
- I use a picture tag to display adapted images.
- preload the image with a link in the <head>

Capture data is from the same test in Lighthouse 6.2

That could be happening?

**Comment by patrickhulce** [comment]
Thanks for filing @javier-fernandez!

I'm betting this is #9971 :) Let us know if you think there's something else going on.
