### ISSUE TITLE
Utility function for parsing Lighthouse Audits JSON

### ISSUE THREAD

**Issue by ssivanatarajan** [GoogleChrome/lighthouse#11335]
**Summary**
Is there Any utility function available to parse the lighthouse report JSON to get the audit details and metrics? I want to store the results of the audits and scores in the Database to identify the changes over the period of time.

**Comment by patrickhulce** [comment]
What do you want this utility function to do? The results are pretty easy to navigate as-is `lhr.audits.auditid`, see [understanding results docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/understanding-results.md)

You also might be interested in https://github.com/GoogleChrome/lighthouse-ci for tracking changes over time.
