### ISSUE TITLE
Installing Lighthouse

### ISSUE THREAD

**Issue by hanzchiziterem** [GoogleChrome/lighthouse#11337]
### Hello, Wonderful Developers on google 
![Capture2](https://user-images.githubusercontent.com/66650409/91422183-bc273280-e84e-11ea-9957-297683704337.PNG)
### I always have this **issue** above when **trying to install lighthouse**

I would really appreciate it if you help me out with this **issue**

**Comment by patrickhulce** [comment]
Thanks for filing @hanzchiziterem! This seems like an npm bug that failed to finish fetching a package.json. 

Can you share the debug log?
