### ISSUE TITLE
Negative 0 ms is displayed in "Main-Thread Blocking Time" of other resources

### ISSUE THREAD

**Issue by ryoAccount** [GoogleChrome/lighthouse#11339]
#### Provide the steps to reproduce
1. Run LH on https://www.coursehero.com/
  

#### What is the current behavior?
About "Reduce the impact of third-party code".
Negative 0 ms is displayed in "Main-Thread Blocking Time" of other resources.

![image65](https://user-images.githubusercontent.com/20512477/91500223-087d7b80-e8fe-11ea-8095-c8ce5fa60bf8.png)

Apparently, the total block time of sub-items is just a little larger than the block time of the summary.
It does not always occur. Is it possible that the blocking time will be negative?

#### What is the expected behavior?
0 ms is displayed in "Main-Thread Blocking Time" of other resources.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 6.3.0
* Chrome version: 84.0.4147.135
* Node.js version: v14.7.0
* Operating System: Windows 10

**Related issues**
N/A

**Comment by patrickhulce** [comment]
Thanks for filing @ryoAccount! 

> Is it possible that the blocking time will be negative?

No, it's just that -0 and +0 are [two different numbers in JavaScript](https://stackoverflow.com/questions/7223359/are-0-and-0-the-same) depending on the sequence of operations performed. This report is trying to say there was 0 blocking time for other resources from this third-party. :)

**Comment by ryoAccount** [comment]
Thanks @patrickhulce 

I would like to improve this bug.

**Comment by patrickhulce** [comment]
That'd be great thanks @ryoAccount! :)

You'll probably need to poke around here https://github.com/GoogleChrome/lighthouse/blob/ccbc8002fd058770d14e372a8301cc4f7d256414/lighthouse-core/report/html/renderer/i18n.js#L67-L70

**Comment by ryoAccount** [comment]
> You'll probably need to poke around here

Thank you for teaching me. 
confirm.
