### ISSUE TITLE
lighthouse report conversion

### ISSUE THREAD

**Issue by vishal-lko** [GoogleChrome/lighthouse#11348]
hey , how do i convert lighthouse report into google sheets?

**Comment by connorjclark** [comment]
try `--output csv`

**Comment by vishal-lko** [comment]
Can it not be done in browser extension method.?

**Comment by patrickhulce** [comment]
> Can it not be done in browser extension method.?

Not automatically. You're always free to download the JSON and construct CSV yourself though.
![image](https://user-images.githubusercontent.com/2301202/91757000-51019700-eb93-11ea-8cf8-b1f3d56c7fc6.png)

**Comment by paulirish** [comment]
> > Can it not be done in browser extension method.?
> Not automatically. You're always free to download the JSON and construct CSV yourself though.


this is our JSON -> CSV method. you can use this as a basis for your own.

https://github.com/GoogleChrome/lighthouse/blob/e9215f144a5ed1993b3d55f2ffb457eafe00acf6/lighthouse-core/report/report-generator.js#L50-L86
