### ISSUE TITLE
add markdown linting

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11345]
https://github.com/gaurav-nelson/github-action-markdown-link-check

would be cool.

would have prevented #11089

**Comment by andreizet** [comment]
Hey, can I take this one?

**Comment by paulirish** [comment]
@andreizet sure

**Comment by emiliogarza** [comment]
Looks like this was solved with #11358

**Comment by connorjclark** [comment]
That only checks for broken links.

**Comment by soumik2012** [comment]
Is this issue is still open ??

**Comment by connorjclark** [comment]
on second thought, the link linter is probably sufficient. i think a markdown style enforcer may be more annoying than helpful.
