### ISSUE TITLE
Questions regarding lazy-third-party audit as an opportunity

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#11344]
Eventually we want to turn the lazy loading third party Lighthouse audit (https://github.com/GoogleChrome/lighthouse/pull/11290) into an opportunity by comparing the third party resource size to the size of the recommended facade alternative.

In theory we could just do `totalThirdPartySize - totalFacadeSize` to calculate the potential savings but there are a few complications:
- We probably want to fetch the facade sizes in a ThirdPartyWeb script so the sizes can be updated easily if the facade repos are updated.  This isn't a problem on it's own but the next two points might make it difficult.
- [Lite youtube](https://github.com/paulirish/lite-youtube-embed#other-lite-embeds) can be included as an npm module and loaded through the main resource domain, so the CSS and JS are first party resources.  Should we use `totalThirdPartySize - totalFacadeSize` for potential savings or just `totalThirdPartySize` since the new resources will be first party?
- What would be the best way to calculate a `totalFacadeSize` for react elements such as [React Live Chat Loader](https://github.com/calibreapp/react-live-chat-loader)?

**Comment by patrickhulce** [comment]
Given our future plans for specificity in opportunities (#11279) I would say we should just consider the entire cost of the third party to be saved. If the facade's aren't essentially free in comparison to the third-party then we probably shouldn't be recommending people go through the effort to bring in that facade in the first place :)

A tricky part of this though is that the existing opportunities are mostly designed to report savings on reducing the size resources and not eliminating them completely. You can use the render-blocking-resources opportunity as a bit of a model here, but we'll probably want to report the overall time savings of the TTI graph with all of the entity's resources removed. Long term with #11279 we can hopefully report TBT, LCP, etc separately.

**Comment by patrickhulce** [comment]
We actually discussed this today in a sync and decided to leave this as a diagnostic for the time being. If we decide to return to an opportunity in the future, the comments in https://github.com/GoogleChrome/lighthouse/issues/11344#issuecomment-683101636 are a decent starting point.
