### ISSUE TITLE
Get only scores for some categories ?

### ISSUE THREAD

**Issue by gyaaniguy** [GoogleChrome/lighthouse#11357]
I am interested in only the final 'scores' of categories. 
Simply using onlyCategories: ['performance', 'accessibility', 'seo', 'best-practices'], returns a whole lot of data and makes things slow.
I just need the score of all these ? Any other suggestions to make things faster ?

Thanks
PS: I found the docs to be a bit difficult to figure out.

**Comment by patrickhulce** [comment]
The score is the aggregated and summarized result of running all of the audits. There is no way to get the complete scores without running the analysis within the categories. If you really wanted to shave off time you could use `skipAudits` to skip everything that has a score weight of `0`, but it's not going to be an order of magnitude faster or anything *too* significant.

https://github.com/GoogleChrome/lighthouse/blob/22f227b5f6f042a05a6f36414aae6bab53a965af/lighthouse-core/config/default-config.js#L436-L478

**Comment by gyaaniguy** [comment]
Thanks
