### ISSUE TITLE
Lighthouse Not working on Intranet sites having authentication. 

### ISSUE THREAD

**Issue by Mavrick2020** [GoogleChrome/lighthouse#11368]
Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)
    at viewer.js:16

Environment Information
Google Chrome is up to date
Version 85.0.4183.83 (Official Build) (32-bit)
OS: Windows 10
Lighthouse:100.0.0.0

**Comment by Mavrick2020** [comment]
necessarily-wide-alpaca

I do not see any resolution. 
I am trying to measure for the intranet site which authenticate user at the time of accessing page.

**Comment by patrickhulce** [comment]
Have you already taken a look at the [Working with Authenticated Pages](https://github.com/GoogleChrome/lighthouse/blob/6e0dbad670e794dc3a3af027a695eb2bed85bb8a/docs/authenticated-pages.md) docs?
