### ISSUE TITLE
Gatsby/Netlify Remove Unused JS + Cache Policy 

### ISSUE THREAD

**Issue by trueblood12** [GoogleChrome/lighthouse#11378]
We have a Gatsby site deployed through Netlify.

Our site is connected to Google Tag Manager which fires tags for our Facebook Pixel, Hotjar, Hubspot account integrations.

Upon running Google Lighthouse (which we love by the way), the output for performance has us wondering how we can go about resolving (or trying to resolve as best we can) the finding report of Google Lighthouse.

For "Remove unused Javascript", is there anything we can do about these?

For "Serve static assets with an efficient cache policy", is there anything we can do about these as well? Ultimately, these are fired via Google Tag Manager

Appreciate your help in advance!

![google-lighthouse](https://user-images.githubusercontent.com/25647094/92160221-ab516080-edfc-11ea-81e0-9b2d3d4192d9.jpg)

**Comment by patrickhulce** [comment]
Thanks for filing @trueblood12! Unfortunately there's not really anything you can do to fix these. It's up to the third-party provider to address these issues.

Lighthouse still presents them to make the site owner aware of the impact these third-parties are having on your page (though they have no direct impact on the score, only the metric values are used in the performance score).

**Comment by JulienKode** [comment]
@trueblood12 Have you try to use preact ? 

I've try it and it removes this on warning for "Remove Unused JS"

**Comment by patrickhulce** [comment]
@JulienKode these results are for assets that @trueblood12 doesn't actually control. Switching to preact will not do anything there.
