### ISSUE TITLE
'Efficiently encode images' showing wrong sizes / potential savings

### ISSUE THREAD

**Issue by Jossnaz** [GoogleChrome/lighthouse#11379]
before going at length to create a repo I'll just post without and have you guys quickly look

Chrome Version 83.0.4103.61 (Official Build) (64-bit)
In lubuntu linux

I get the warning:
Efficiently encode images
![image](https://user-images.githubusercontent.com/2072058/92159488-1d24ac80-edf3-11ea-8db1-1ac6a444f30a.png)

So i click on the link (top one), download and check the size
![image](https://user-images.githubusercontent.com/2072058/92159577-404f5c00-edf3-11ea-8d53-e05a3b3f9289.png)

its ~100kb big. Not ~200kb

not sure where that comes from? the other image has the same problem, it is in reality smaller.

I reran the tests a couple times, sometimes it doesn't show, sometimes it does.

**Comment by patrickhulce** [comment]
Thanks for filing @Jossnaz! Can you not share the URL with us?

Usually this means that the server is discriminating based on the user-agent that Lighthouse uses to serve a different asset.

**Comment by Jossnaz** [comment]
@patrickhulce this is da interwebz. I cannot share you that URL no. 

Maybe in DM? Maybe in DM I can share it.

it's a static site, there are no different assets for different resolutions / devices or magic involved. Static HTML. There is no second asset of the image, or srcset or anything like that.

The test doesn't always agree with itself either.
I ran it twice within 40 seconds one test right after another
once I scored 21:

**no complaints about wrong origin in preconnect**
But: Efficiently encode images

the second run, 40 seconds later, I scored 32
now It complaints
> A preconnect <link> was found for "https://www.gstatic.com" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

but that was the same as before.
> Efficiently encode images
 was once again the problem as well.

I ran it a third time now
scoring 23
preconnect still a problem and Efficiently encode images

I cann add the preconnect attribute like so:
`    <link rel="preconnect" crossorigin href="https://www.gstatic.com">`

or remove it
`    <link rel="preconnect" href="https://www.gstatic.com">`

in both cases, lighthouse will complain eventually.

**Comment by patrickhulce** [comment]
There will always be [variability issues](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) with web performance measurement, so those sound quite normal. I'm most interested in the image size difference :)

[DM](https://twitter.com/patrickhulce) or [email me](mailto:patrick.hulce@gmail.com) the link?

**Comment by Jossnaz** [comment]
seems like a problem with my extensions / apps activated. Not sure.
