### ISSUE TITLE
im getting a ? in score and LCP as ERROR  url https://www.esakal.com/paschim-maharashtra/tourist-car-flow-water-near-koyna-dam-204624 please help  Thank you

### ISSUE THREAD

**Issue by SaadAnsari-sankey** [GoogleChrome/lighthouse#11383]
im getting a ? in score and LCP as ERROR 
url https://www.esakal.com/paschim-maharashtra/tourist-car-flow-water-near-koyna-dam-204624
please help 
Thank you

**Comment by patrickhulce** [comment]
Thanks for filing @SaadAnsari-sankey! I can reproduce this. We'll have to dig in here, but I suspect that there might be a problem with LCP invalidation logic.

For future readers of this issue, the page does something like...

Paint of size 10000
Paint of size 15000
INVALIDATION
Paint of size 12000

We never receive any candidates after the invalidation even though there were more paints. Unclear if it's a LH-side bug in our understanding of LCP events or a Chromium bug for not emitting another candidate.

**Comment by connorjclark** [comment]
Doesn't repro anymore.
