### ISSUE TITLE
PSI CLS values on elements out of the viewport

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#11389]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  https://intersindicalrm.org/om/

#### What is the current behavior?
CLS measures elements that are out of the viewport
#### What is the expected behavior?
As far as the CLS come from an element out of the viewport, the value must be 0

#### Environment Information
* Affected Channels: PSI
* Lighthouse version: 6.1.0
* Chrome version: N/A
* Node.js version: N/A
* Operating System: N/A

**Related issues**
The same url in chrome Versión 85.0.4183.83 (Build oficial) (64 bits) LH version 6.0.0 don´t report CLS
and in chrome Versión 87.0.4255.0 (Build oficial) canary (64 bits) LH version 6.3.0 too.
The issue is wiht the desktop device.
![Captura](https://user-images.githubusercontent.com/22342793/92305892-b7b7f380-ef8b-11ea-879d-a12c6f8526dd.jpg)

**Comment by patrickhulce** [comment]
Thanks for filing @Lofesa!

It is in viewport before the image loads though. CLS is correct here. This is what it looks like before the image loads. 
![image](https://user-images.githubusercontent.com/2301202/92491198-96d3e600-f1b7-11ea-97bd-ae4f24688c5e.png)

If it helps, it's much more obvious if you load the page with "Slow 3G" enabled so you can pause script execution and poke around a bit.

**Comment by Lofesa** [comment]
Thank you @patrickhulce for pointing to this.
I will clode this.
