### ISSUE TITLE
Extension Error: Cannot access a chrome-extension:// URL of different exte...

### ISSUE THREAD

**Issue by fvant** [GoogleChrome/lighthouse#1138]
**Lighthouse Version**: 1.2.2
**Chrome Version**: 55.0.2883.54
**Error Message**: Cannot access a chrome-extension:// URL of different extension
**Stack Trace**:
 ```Error: Cannot access a chrome-extension:// URL of different extension
    at Object.chrome.debugger.attach._ [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7470:29)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ebidel** [comment]
Can you post the URL you were testing against and let us know how to reproduce?

**Comment by ebidel** [comment]
Chrome doesn't allow extensions to access other `chrome-extension://` pages. I suspect you were trying to run lighthouse on an internal chrome page or another page created by a chrome extension. Please reopen if that's not the case.

**Comment by Nucito** [comment]
> Chrome doesn't allow extensions to access other `chrome-extension://` pages. I suspect you were trying to run lighthouse on an internal chrome page or another page created by a chrome extension. Please reopen if that's not the case.

1 - I apologize for commenting on such an old issue.
2 - Is there no way to inject codes into a page opened by another extension? I just needed to make the extension click on a button that appears on the page.

**Comment by connorjclark** [comment]
You should follow #9402
