### ISSUE TITLE
Disable Chrome Extensions before testing 

### ISSUE THREAD

**Issue by Artik-Man** [GoogleChrome/lighthouse#11391]
![image](https://user-images.githubusercontent.com/6566395/92331794-d4ceee00-f081-11ea-92b4-3ab52b46ae1f.png)

Lighthouse swears at browser extensions.

Please, make it possible to disable all extensions before testing

**Comment by patrickhulce** [comment]
Thanks for filing @Artik-Man! Lighthouse actually used to do this but it broke lots of extension behavior and we had to revert it (at this point we know several extension owners to actually use Lighthouse to evaluate their extensions too). Instead Lighthouse just adds a warning in the page to run in incognito or in a fresh profile if you don't want the influence of extensions.
