### ISSUE TITLE
Incorrect report unused CSS

### ISSUE THREAD

**Issue by BernardA** [GoogleChrome/lighthouse#11393]
#### Provide the steps to reproduce
1. Run LH on https://quiamo-client.vercel.app/

The code is available at https://github.com/BernardA/quiamo-client
  

#### What is the current behavior?

Shows unused CSS that's actually used on the page. 

It shows this file as being unused -> https://quiamo-client.vercel.app/_next/static/css/6d22697a7651bfde15e3.css.
I did not check all rules, but the rule below present on the above file certainly shows on dev tools:

       body {
         font-size: 1rem;
         line-height: 1.5;
         min-height: 100vh;
         place-content: center;*/
         margin: 0 2rem;
         color: #333;
         min-width: 320px;
    }

#### What is the expected behavior?

Should not report it as unused. 

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 85.0.4183.83 (Official Build) (64-bit)
* Node.js version: 12.16.0
* Operating System: mac OS

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @BernardA! It's telling you that 30KiB of that file was unused, not that the *entire* file was unused. DevTools confirms ~90% of this file is not used and you can use the "Coverage" panel to see what rules don't get triggered on page load.

![image](https://user-images.githubusercontent.com/2301202/92503226-9131cc80-f1c6-11ea-9446-5075c7815580.png)

**Comment by BernardA** [comment]
Thanks for your explanation. I understand what is going on there now.  Ql-editor not been used is a NextJS issue actually. 

I did not manage to visualize the formatted CSS, only the minimized version. If you have a recipe you could share I would appreciate.
