### ISSUE TITLE
Include category score in CSV output

### ISSUE THREAD

**Issue by emersonthis** [GoogleChrome/lighthouse#11398]
**Feature request summary**
When the output format is CSV, the report has a row for each individual metric. However, it does not include the overall category score. In case I'm using the wrong term here, the following screenshot shows what I'm calling the "overall category score".
<img width="1867" alt="Screen Shot 2020-09-08 at 5 15 43 PM" src="https://user-images.githubusercontent.com/1728139/92539750-44b2b500-f1f7-11ea-8330-33dcb2653e33.png">
 
This data appears in the HTML version of the report, and I also see it in the JSON formatted output.

**What is the motivation or use case for changing this?**
We are using Node.js CLI to run reports for multiple pages of a site and then aggregating the individual report(s) data into a single spreadsheet. This is easy to do with CSV-formatted data. This workflow helps us identify the best/worst performing pages by sorting by a specific metric. However, it would be equally valuable to be able to sort by the overall category score.

**How is this beneficial to Lighthouse?**
The category scores are extremely important, and right now they aren't included in one of the most portable output formats.

**Comment by patrickhulce** [comment]
Thanks for filing @emersonthis good point! 

This would be a straightforward first-time contribution if anyone is interested :)

https://github.com/GoogleChrome/lighthouse/blob/2bf89fba2a5e3457b369fda653af214ec9c5ad08/lighthouse-core/report/report-generator.js#L71-L73

**Comment by pujitha7** [comment]
Hi, I would like to pick this one as my first issue!

**Comment by patrickhulce** [comment]
great thanks @pujitha7! should be able to just add a line in the referenced section above that outputs the category score for each, and add a test to match :)

**Comment by emersonthis** [comment]
Thanks @pujitha7 !

@patrickhulce Do you know of any workarounds for this that might work in the short-term? Is the JSON output currently the only place where the category scores are exposed? For context, here's what my code currently looks like:
```
const runReport = async (url, outputFormat) => {

  const {status = -1, stdout} = spawnSync('node', [
    lighthouseCli,
    url,
    `--output=${outputFormat}`,
    `--output-path=stdout`,
    `--emulated-form-factor=mobile`,
    `--only-categories=performance`,
    `--chrome-flags="--headless"`
  ]);

  if (status !== 0) {
    console.error(`Lighthouse report failed for: ${url}`);
    return false;
  }

  console.log('Report is done for', url);
  return stdout;
};
```

**Comment by connorjclark** [comment]
Have you read https://github.com/GoogleChrome/lighthouse/blob/master/docs/understanding-results.md ?

**Comment by emersonthis** [comment]
@connorjclark I have. But I'm not clear about where the `lhr` object is exposed if/when I'm running `lighthouse` as a child process.

**Comment by connorjclark** [comment]
You might as well use the node API directly (`const lighthouse = require('lighthouse') ...`) if you're spawning a synchronous process, then you don't need to worry about a buffer.

**Comment by patrickhulce** [comment]
@emersonthis 

>  I think I need to toString() the buffer output. If I switch the --output to json I think this would give me a serialized version of the lhr object. Am I on the right track?

You're also on the right track with this direction. You can also use the [`encoding` option of `spawnSync`](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) to get stdout as a string :)

**Comment by emersonthis** [comment]
@patrickhulce thanks for the tip!

@connorjclark I'm not sure I understood your suggestion. I'm running `lighthouse` on a large list of urls and I read on several different issues, that a child process is necessary to do this reliably. Indeed, my first implementation used the node module inside a loop and I learned the hard way this doesn't work in a single process. I spawned a synchronous child process with the hopes of avoiding resource limitations that might result from lots of `lighthouse`s running in parallel. Does this context change your advice? If not, can you clarify how the node API might solve my use case?
