### ISSUE TITLE
Chrome Lighthouse 6 Always displays Light House is Warming Up

### ISSUE THREAD

**Issue by Mavrick2020** [GoogleChrome/lighthouse#11399]
**Describe the bug**
On intranet site it always shows message "Light House is Warming Up". The site requires authentication to access a page.
![image](https://user-images.githubusercontent.com/68216830/91990499-6de2c980-ed4f-11ea-9403-c32845d4a4ad.png)

**To Reproduce**
1. Go to secure intranet site
2. login and access a page after login
3. open chrome developer tool
4. navigate to lighthouse tab and click on generate report. Chrome developer tools always shows message - Light House is Warming Up.

**Expected behavior**
Lighthouse analysis 

**Screenshots**
![image](https://user-images.githubusercontent.com/68216830/91990508-72a77d80-ed4f-11ea-8cf5-222375bf55af.png)

Chrome: 85
OS: Windows 10

**Comment by patrickhulce** [comment]
Thanks for filing @Mavrick2020! This is best described by #10103 and means that Chrome is being blocked from downloading Lighthouse to run it.
