### ISSUE TITLE
The same h2 element appears three times

### ISSUE THREAD

**Issue by ryoAccount** [GoogleChrome/lighthouse#11397]
#### Provide the steps to reproduce
1. Run LH on https://ryocv.online/univers/
  

#### What is the current behavior?
About "Avoid large layout shifts".
The same h2 element appears three times.

![image89](https://user-images.githubusercontent.com/20512477/92526368-55e3dc00-f260-11ea-9628-a7f58e356774.png)

However, the page has only one h2 element.

The CLS Contribution values are different.
So, did the h2 element contribute to CLS three times?

#### What is the expected behavior?
The h2 element appears once.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 6.3.0
* Chrome version: 85.0.4183.102
* Node.js version: 14.7.0
* Operating System: Windows 10

**Related issues**
N/A

**Comment by patrickhulce** [comment]
> The CLS Contribution values are different.
So, did the h2 element contribute to CLS three times?

Yep that's exactly what it means right now :)

**Comment by ryoAccount** [comment]
Thank you for teaching me.
One element may make multiple contributions to CLS!

It was my lack of recognition, withdraw the issue.
