### ISSUE TITLE
Include Overall Score in the JSON output of API

### ISSUE THREAD

**Issue by padam2403** [GoogleChrome/lighthouse#11403]
When the output comes out from API in the form of JSON, then we don't have the overall score of the page which is present at the top when we check in the online tool.
API Used: https://pagespeedonline.googleapis.com/pagespeedonline/v5/runPagespeed
Language Used: Python
![image](https://user-images.githubusercontent.com/26092727/92735668-38fdf480-f397-11ea-9eb8-7908d21d5d79.png)

Kindly add this highlighted calculated overall score in the output coming from API.

**Comment by patrickhulce** [comment]
Thanks for filing @padam2403!

It is included though. This is just the score of the performance category. `lighthouseResult.categories.performance.score * 100`

**Comment by padam2403** [comment]
Thanks @patrickhulce.
