### ISSUE TITLE
CPU throttling

### ISSUE THREAD

**Issue by jaouher2** [GoogleChrome/lighthouse#11412]
Hello,

I can't desactivate the CPU throttling. It displays "4x slowdown (DevTools)".

#### Environment Information
* Affected Channels: 
* Lighthouse version: Lighthouse 5.7.0
* Chrome version: 80.0.3987.106
* Node.js version:
* Operating System: Windows

**Related issues**

**Comment by jaouher2** [comment]
Hello,
Thank you for your reply.

I want to test a public website (visitors use desktop device only).
Can you advise me please which throttling configuration I should apply in my situation?

Thank you

**Comment by patrickhulce** [comment]
Wait, if you're just measuring desktop than there's no CPU throttling to be deactivated in the first place. Update to a version of Chrome that has Lighthouse 6.x and you're good to go 👍 (Latest stable Chrome 85 has this)

**Comment by jaouher2** [comment]
OK, Thanks a lot 👍
