### ISSUE TITLE
automate updating bundlephobia data

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11419]
We don't want our size data to be stale.

**Comment by patrickhulce** [comment]
Orrrrr, how about we convert this audit to only flag bundles and/or CDN-served dedicated moment files to report 100% accurate transfer size instead of estimates that could be wrong if they optimized the library already :)

**Comment by connorjclark** [comment]
We're probably gonna take an approach that removes this data entirely.
