### ISSUE TITLE
data:image/png;base64 => ERR_INVALID_URL

### ISSUE THREAD

**Issue by black-snow** [GoogleChrome/lighthouse#11429]
#### Provide the steps to reproduce
1. Run LH on a page containing:

```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42‌​mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=" alt="" />
```
  
#### What is the current behavior?

```
Failed to load resource: net::ERR_INVALID_URL
```
 

#### What is the expected behavior?

No such error logged.

#### Environment Information
* Affected Channels: devtools
* Lighthouse version: 6.0.0
* Chrome version: 85.0.4183.102
* Node.js version: ?
* Operating System: Win 10 64bit

**Related issues**
-

**Comment by patrickhulce** [comment]
Thanks for filing @black-snow! That is an invalid URL though and Chrome itself logs this error. There are invisible unicode characters in between `EQVR42` and `mNgYAA`. If you remove those invalid characters, the proper 1x1 PNG renders as expected without the error in the console.

**Comment by black-snow** [comment]
Oh, will give it a shot and report back

**Comment by black-snow** [comment]
yep, that did the trick, thanks for spotting it

**Comment by edgaras1002** [comment]
bleeee

**Comment by Chelamahendrajati** [comment]
nnn  n n n
