### ISSUE TITLE
Always display decimal places in JS library size comparison

### ISSUE THREAD

**Issue by acutmore** [GoogleChrome/lighthouse#11422]
**Feature request summary**
 
Currently in the 'Large JavaScript libraries' view, the 'Transfer size' column values omit the decimal place for round sizes. i.e. `18 KiB` is displayed instead of `18.0 KiB`.

This ticket proposes to always display the digit after the decimal place, even if it is `0`.

I am happy to make the necessarily changes if the feature is agreeable with the team 🙂

**What is the motivation or use case for changing this?**

For people who struggle with their vision this can make it harder to compare the numbers across the rows, as the digit columns do not line up. For example in the below image it can look like `date-fns` is `18 KiB` while `luxon` is `204 KiB`.

![lighthouse-sizes](https://user-images.githubusercontent.com/4369552/93003763-4eab1f80-f539-11ea-9268-12324624de08.jpeg)

**How is this beneficial to Lighthouse?**

Improve accessibility.

**Comment by patrickhulce** [comment]
Thanks for filing @acutmore! I agree when the granularity is set to tenths all numbers should be displayed to the tenth 👍

**Comment by connorjclark** [comment]
The relevant code is various functions within https://github.com/GoogleChrome/lighthouse/blob/ec69e56f06b61932712db239c3db1804d260a16a/lighthouse-core/report/html/renderer/i18n.js 

NumberFormatter apparently accepts a minimum significant digits: https://tc39.es/ecma402/#conformance

**Comment by acutmore** [comment]
thanks @patrickhulce and @connorjclark. I'll have a go at making the change within the next few days.

**Comment by connorjclark** [comment]
also, Math.log10 will be your friend :) 
![image](https://user-images.githubusercontent.com/4071474/93132632-9e096100-f69b-11ea-8737-09e04b88e0b1.png)
