### ISSUE TITLE
large-javascript-libraries feedback

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11423]
- [ ] Drop "unnecessarily" from the copy. add "analyze", "consider", etc..
- [ ] Look into pushing some Google funds into the libraries we suggest (also for the largest library!)
- [ ] Reach out to library maintainers (and before any new additions)
- [ ] Maybe rename audit to `smaller-javascript-libraries`?
- [ ] Make "informational" (never fail)
- [ ] Mention "Bundlephobia" in audit description

**Comment by patrickhulce** [comment]
> Maybe rename audit to smaller-javascript-libraries?

Why this one? If a library isn't large it shouldn't be in here in the future no matter how much smaller the alternatives :)

**Comment by addyosmani** [comment]
Thanks Connor 👍 Capturing some other feedback from the recent tweet discussions on this audit in case not included above yet.

- Soften the language (tweaking unnecessarily is a good start, do we want to also refine language to focus on these just being suggestions?)
- Explore a column/doc listing feature differences between alternatives (size is just one factor). This isn't something BundlePhobia does yet, but there are resources like YouMightNotNeedMoment we could link to for comparison?
- Make it clearer recommendations are based on BundlePhobia and we are short-term focused on Moment & Lodash. I think folks are concerned we will go as far as recommendations for replacing frameworks. Clarity on the roadmap for this audit could help.

**Comment by patrickhulce** [comment]
> & Lodash

Perhaps I misremembered my position as agreement 😅 , but we discussed this in the design doc, and I thought we agreed this wouldn't apply to lodash? There our proposed solution is not recommending another library, but just tweaking import statements for the same package.

**Comment by connorjclark** [comment]
Suggesting this approach:

* Keep name `large-javascript-libraries`
* Diagnostic
* In addition to Stacks, use source maps to determine libraries in use
* * hard code how big libraries we can detect in Stacks are
* * If a library is found in a source map, ignore and Stack for it
* Make no suggestions in the report, just link to bundlephobia page
* If library is >XX KB, list in audit

**Comment by ljharb** [comment]
bundlephobia paints an inaccurate picture, and per its name, drives fear-based thinking. The bundled size delta of adding a dependency can't be measured unless you have the *entire app* available to bundle, before and after, including any optimizations your bundler config includes.

**Comment by connorjclark** [comment]
Our usage of source maps allows us to exactly count how many bytes a dependency adds. We'd only use the size provided by BP if there is no source map, and even then the only impact would be that we list the library higher in a table than it should be. There'd be no score associated with this audit.

We should also ignore any library considered a framework (react, angular, etc..)

**Comment by patrickhulce** [comment]
> Keep name large-javascript-libraries
Diagnostic
In addition to Stacks, use source maps to determine libraries in use
Make no suggestions in the report, just link to bundlephobia page

SGTM

> hard code how big libraries we can detect in Stacks are

I'm not entirely sure what this means, like drop the fetching of data from Bundlephobia and manually create an entry in a map of the size for each detectable library?

> If library is >XX KB, list in audit

Does this mean it will be flagged regardless of available alternatives?

**Comment by ljharb** [comment]
@connorjclark "listing higher than it should be" is an outsized and imo unacceptable impact for google to make on an otherwise free marketplace of libraries.

**Comment by patrickhulce** [comment]
I'm really surprised that is your hill to die on @ljharb. The relative ranking of libraries being flagged as too large seems downright trivial compared to whether a large library is flagged in the first place. If limiting unreasonable influence on a free marketplace of libraries is your actual goal, shouldn't the criteria for being marked as large be where discussion should be focused?

**Comment by ljharb** [comment]
@patrickhulce I don't think it's appropriate for a web browser to get involved *whatsoever* in those criteria, is the problem (nor npm/github). The criteria will be different for everyone, and will vary over time, and it's important that everyone is equally free to make those choices for themselves.

If there's ever two libraries that do *exactly* the same thing, and one is smaller, then the smaller one is a better choice, but also the larger one could surely make changes and reduce its size, removing that criteria - but that's not likely to ever be the case. There's always tradeoffs - correctness, performance, features, browser/engine support, maintainer reliability, etc - and presenting one metric (size, whether bundle or disk) in such a way as to imply it's more important than the others (especially when it often is not) is not helpful to the ecosystem.

**Comment by patrickhulce** [comment]
Gotcha! So just to be clear, there is no value of `X` such that you would feel it is reasonable for any entity to suggest looking at alternatives to libraries that are larger than `X KB`?

Or, formulated differently, there is no value of `Y` such that it's reasonable to suggest looking at alternatives if `Y KB` of the library is being unused.

**Comment by ljharb** [comment]
@patrickhulce on an app-specific basis, there is always a value of X or Y. In the general case? No, I don't think such a value exists (assuming the premise that no two libraries have precisely the same identical tradeoffs, capabilities, performance, maintainership, scale of review, etc).

**Comment by patrickhulce** [comment]
Bummer, then we've reached an impasse w.r.t your concerns. Duly noted!

**Comment by connorjclark** [comment]
Deferring to #12296



---


EDIT( by @paulirish, 2025-10): A couple years later, the https://github.com/es-tooling/module-replacements effort has similar goals to this effort and is a more canonical list of alternatives.
