### ISSUE TITLE
Question: Can audit url with redirects?

### ISSUE THREAD

**Issue by jmdelacerna** [GoogleChrome/lighthouse#11430]
Question: Does lighthouse audit urls with redirects? 
If yes, is there a maximum number of redirects it can handle?
Will the final url be audited instead?

**Comment by brendankenny** [comment]
> Does lighthouse audit urls with redirects?

yes

> If yes, is there a maximum number of redirects it can handle?

whatever Chrome can handle ([looks like it's 20](https://source.chromium.org/chromium/chromium/src/+/master:net/url_request/url_request.h;l=90-93;drc=5c860faff8acca32094b87f229b630519326372e))

> Will the final url be audited instead?

Yes, as that's where the actual page content will end up coming from. There will be a message at the top of the report suggesting auditing the final URL instead in the future, but it isn't required.
