### ISSUE TITLE
Update library-detector version to remove asset-manifest.json request

### ISSUE THREAD

**Issue by dwsmart** [GoogleChrome/lighthouse#11444]
I'm seeing lighthouse, and pagespeed insights, requesting asset-manifest.json from the root. Not really an issue, but curious, is this to help in detecting react frameworks to make framework specific recommendations?

**Comment by patrickhulce** [comment]
Thanks for filing @dwsmart! 

To clarify, you're referring to an asset manifest similar to the one [webpack or another bundler generates?](https://webpack.js.org/concepts/manifest/). Lighthouse doesn't explicitly request a `asset-manifest.json`, so my best guess is that something else is requesting it as a result of the Lighthouse loading process (a service worker maybe?). An example URL where this is happening would be easiest to tell for sure :)

**Comment by dwsmart** [comment]
Hey @patrickhulce 
When running a PageSpeed Insights test, or lighthouse 6.3 there is a request made for /asset-manifest.json This doesn't seem to be the case for 6.0 (run in chrome 85)

Some examples: https://tamethebots.com/blog-n-bits/detect-click-in-iframe - built in svelte / sapper with roll-up, no other agents request this file, here's a log file entry from the test:
```
66.249.93.208 - - [17/Sep/2020:15:42:03 +0100] "GET /asset-manifest.json HTTP/1.1" 404 2490 "https://tamethebots.com/blog-n-bits/detect-click-in-iframe" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Safari/537.36 Chrome-Lighthouse" "-" "gzip,deflate,br"
```

Same happens with https://www.silver-heart.co.uk, which is a php (magento) site, this does utilise a service-worker though

Also checked against a 'standard' wordpress site, this also gets a request.

**Comment by patrickhulce** [comment]
Ah thanks for the extra info it looks like this is one of our dependencies https://github.com/johnmichel/Library-Detector-for-Chrome/issues/158

They've since [removed that check](https://github.com/johnmichel/Library-Detector-for-Chrome/blob/5f38d75295a2db46fb1076ef85cf303ed806ea9a/library/libraries.js#L1771-L1790) though, so this should be resolved next time we update.

**Comment by dwsmart** [comment]
Ah! Mystery solved! Thank you @patrickhulce
