### ISSUE TITLE
Cannot redirect HTTP traffic to HTTPS

### ISSUE THREAD

**Issue by GlenKPeterson** [GoogleChrome/lighthouse#11455]
We don't allow HTTP traffic.  Port 80/HTTP is closed at the firewall/router.  Only port 443/HTTPS is open.  How do I pass this test?

For reference, the production version of the site (not a PWA yet) is https://memoryjoggerlibrary.com/

I'm not sure, but it looks as if this error may prevent me from achieving any score at all for PWA.  I just have a question-mark where the score would go.

**Comment by patrickhulce** [comment]
Thanks for filing @GlenKPeterson!

> How do I pass this test?

You can't. The only real option to pass would be getting [added to the HSTS preload list](https://hstspreload.org/), but that's quite overkill and a long-term commitment to never serving content over HTTP across all subdomains.

> I'm not sure, but it looks as if this error may prevent me from achieving any score at all for PWA. I just have a question-mark where the score would go.

That would be my expectation based on the way this domain handles the firewall rules. I would expect Lighthouse to always flag a connection *timeout* as an error that could not be computed even in a hypothetical future version of an audit that wanted to pass sites that *rejected* port 80 connections.

**Comment by GlenKPeterson** [comment]
Thank you for your quick response!

Can I still make a progressive web app for this site without allowing HTTP traffic?  I mean, does this Lighthouse test failure mean my site failed, or that Lighthouse just doesn't handle this situation?

**Comment by brendankenny** [comment]
This audit was removed in #12643 (in the 9.0 release). There's a proposal to revive it in #13548, but it would no longer fail in this case (it only applies if the tested URL was `http` and didn't redirect to `https`, so wouldn't apply for test URLs that are `https` from the start), so I'm going to close this issue.

**Comment by GlenKPeterson** [comment]
@brendankenny Sounds like a good solution!
