### ISSUE TITLE
Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by thejav-perpetualny** [GoogleChrome/lighthouse#11453]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  
#### What is the current behavior?
Running lighthouse fails with error Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
#### What is the expected behavior?
Reduce memory utilization or throw an error if exceeding memory

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 6.1.1
* Chrome launcher version: 0.13.4
* Node.js version: 12
* Operating System: mac, Centos,  Ubuntu docker

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @thejav-perpetualny! This report is missing reproduction steps though. Would you be willing to provide the example URL, more machine environment information, etc, so we can look into it?

I guarantee that 100% of all Lighthouse runs on all URLs do not end with an OOM ;)

**Comment by thejav-perpetualny** [comment]
@patrickhulce https://www.entresto.com/info/patient-stories.jsp is the Url I'm running LH on. Using CLI works fine. Running using node modules errors out

**Comment by patrickhulce** [comment]
> Running using node modules errors out

What else are you doing in this node process and are you running Lighthouse many times? The CLI is just using the node module under the hood. Note that for running Lighthouse multiple times we highly recommend [using a child process](https://github.com/GoogleChrome/lighthouse/blob/2bf89fba2a5e3457b369fda653af214ec9c5ad08/docs/variability.md#run-lighthouse-multiple-times).

**Comment by thejav-perpetualny** [comment]
I run it multiple times but they are all sequential.
here is the code that executes it.
```
return chromeLauncher.launch({chromeFlags: opts.chromeFlags}).then(chrome => {
        const options = {
            output: 'json',
            onlyCategories: ['best-practices', 'seo', 'performance',  'accessibility'],
            port: chrome.port
        };
        const config = {
            extends: 'lighthouse:default',
            settings: {
              emulatedFormFactor: device.toLowerCase(),
              throttling: getThrottlingConfig(network_profile.toLowerCase())
            },
          };
        return lighthouse(url, options, config).then(results => {
            const reportJSON = JSON.parse(results.report);
            let output = {
                ...reportJSON
            }
            const fileName =  'test.json';
            return uploadToS3(fileName, JSON.stringify(output))
            .then( res => {
                console.log(`Completed Writing: ${fileName}`);
                return chrome.kill().then(() => {})
            })
        });
    })
    .catch( err => {
        console.log("Error during lighthouse run: " +  JSON.stringify(err));
    });
```

**Comment by patrickhulce** [comment]
Ah OK, are you unable to run Lighthouse in a child process?

All primary integrations of Lighthouse run in disposable execution contexts and so we don't officially guarantee there are no memory leaks or issues with running many times. I would expect you to be able to run it a low number of times without any problems, but long-lived attempts should definitely use a child process.

**Comment by thejav-perpetualny** [comment]
No, I haven't used the child process yet. I will look into moving it to child process and see how it goes
