### ISSUE TITLE
Displays images with inappropriate size

### ISSUE THREAD

**Issue by andymathieson** [GoogleChrome/lighthouse#11450]
<img width="728" alt="Screenshot 2020-09-17 at 14 06 46" src="https://user-images.githubusercontent.com/26063385/93576560-eaea8180-f992-11ea-867b-ca64c87ae7b1.png">

When running an audit on mobile, or if I run an audit on a 4k or 5k monitor where the DPI is 2x, we get marked down on our score. 

In the screengrab above, you can see that lighthouse is expecting an image of 2198x2150. You can also see that the image being served has the dimensions of 2200x1252. However, the displayed size and actual size don't correspond. 

I get a 100 if testing on a standard dpi monitor.

**Comment by patrickhulce** [comment]
Thanks for splitting this out into another issue @andymathieson! 

I can reproduce this on http://melodic-class.glitch.me/image-srcset.html which reports the 800x400 source image as only 360x180.

**Comment by patrickhulce** [comment]
@andymathieson are your images also served after a redirect from the original `src` attribute? If so we've found the same root cause.

**Comment by andymathieson** [comment]
Hi @patrickhulce 

We do use lazyloading from a Src Set. So we actually have a data-src-set. I can understand it if lazyloading threw a bug, but that should also happen at a standard DPI should it not?

**Comment by patrickhulce** [comment]
I'm not sure I understand your response. I'm asking if the image URLs you reference in your src/srcset/data-srcset return a 301/302 redirect to the underlying resource (as many image CDNs seem to do).

If they do, then I have found the cause of the bug. 

If they don't, then I cannot reproduce what you're talking about and there's more than one issue going on here (so we'll need a public URL or more detailed reproduction information from you in order to help).

**Comment by andymathieson** [comment]
No problem. I can't post to a clients website but I will build a little mockup in the next day or two. Thanks

**Comment by patrickhulce** [comment]
> No problem. I can't post to a clients website but I will build a little mockup in the next day or two. Thanks

Does this mean those images do not redirect then? :/

And awesome, thank you that would be great if it's different!

**Comment by andymathieson** [comment]
I have tested 2 systems. 1 with CDN, one without. The results are the same. We use cloudfront for CDN and I havent added any redirects unless Amazon does it of its own accord. That wouldn't explain the non-CDN version tho.
