### ISSUE TITLE
Report: clearer iconography in Perf metrics and Fancier Stuff

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1146]
The [warning icon](https://material.io/icons/#ic_warning) might be good for things in the Fancier stuff section that fails. The current red X is a bit harsh for these. We can keep the green checkbox when the audit passes.

For the perf metrics section, the current icons also don't make sense. Green check for "you've added user timing metrics". Yay! We could use the [info icon](https://material.io/icons/#ic_info) and warning icon for this section since it's mostly informative and not scored.

![screen shot 2016-12-12 at 11 43 27 am](https://cloud.githubusercontent.com/assets/238208/21114245/55cb9724-c061-11e6-9faa-15304bd6a766.png)

**Comment by wardpeet** [comment]
can only say that this would be great :)

**Comment by sendilkumarn** [comment]
Can we handle this with changing `Json` structure change for both adding a boolean variable that will help to identify which one to display.

something like, 
`informative` for `items` ( as in perf metrics section)
```js
if ( informative ) 
     show info / warning
else 
    show pass / error
```

`additional` for `aggregations` ( as in fancier stuffs )

```js
if ( additional ) 
     show pass / warning
else 
    show pass / error
```

if it is okay I will do a PR.
