### ISSUE TITLE
Lighthouse won't execute on Chrome Canary 87

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/lighthouse#11467]
Chrome Canary: Version 87.0.4269.0 (Official Build) canary (64-bit)
Windows 8.1
Lighthouse Version: unknown, because the process doesn't complete to the end.

Lighthouse hangs on initial "Lighthouse is warming up..." screen. I've tried it on my own sites and on www.example.com.

Lighthouse fails to execute both for the Mobile and Desktop audits, and in regular and incognito mode.

Try performing the audit on www.example.com and see if it hangs there for you as it does for me.

**Comment by patrickhulce** [comment]
Thanks for filing @tmb-github! It's a known Chromium bug and the team is working on it (https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2418431, ref #9484)
