### ISSUE TITLE
Parameters used in PageSpeedInsight

### ISSUE THREAD

**Issue by cantacell** [GoogleChrome/lighthouse#11479]
Using Lighthouse from Google Chrome the results of my project is 80 - 90.
Using Lighthouse 6.3.0 from npm and this command "**https://... --only-categories=performance --output=html,json --output-path=./report save-assets --view --quiet**" the results is 66 - 73.
Using Lighthouse 6.3.0 from npm and this command "**https://... --only-categories=performance --output=html,json --output-path=./report save-assets --view --quiet  --chrome-flags="--headless**" the results is 48 - 51.
So, what are the parameters we MUST use for compare with PageSpeedInsight???
....Don't drive us crazy....

**Comment by cantacell** [comment]
Ok, but #10657 is more generic. Should we use for our projects with or without **--chrome-flags="--headless**?

**Comment by patrickhulce** [comment]
When you can, you should test without headless as your real users won't be using in a headless browser :)

Headless is useful when you don't have an alternative and you just need to compare against itself (like in CI)
