### ISSUE TITLE
Black text on white background flagged as insufficient contrast

### ISSUE THREAD

**Issue by morganwdavis** [GoogleChrome/lighthouse#11477]
#### Provide the steps to reproduce
1. Run LH on https://www.jeromes.com

#### What is the current behavior?

Note accessibility issue: "Background and foreground colors do not have a sufficient contrast ratio."

The elements flagged are these (see yellow highlight):

![image](https://user-images.githubusercontent.com/4434533/94107867-2520ac80-fdf3-11ea-84b3-969c19db5a0d.png)

#### What is the expected behavior?

These contrast issues seem to be something new in LH 6.0.0 as that design of the site has been a fixture for years and LH never flagged them before.  The site had a 100 score for accessibility.  Now it is 98.

#### Environment Information
* Affected Channels: 
* Lighthouse version: 6.0.0
* Chrome version: 
* Node.js version:
* Operating System: Windows 10

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @morganwdavis!

I can't reproduce this with Lighthouse 6.3.0, perhaps it's been fixed already?

![image](https://user-images.githubusercontent.com/2301202/94157660-1cf25c80-fe47-11ea-8ef7-e8969c9dc9a3.png)


For accessibility issues, if you can reproduce the problem with just [axe-core](https://github.com/dequelabs/axe-core) please file an issue with them and Lighthouse will pick it up automatically when it gets fixed :)

**Comment by connorjclark** [comment]
Please let us/axe know if you can get a repro.

**Comment by morganwdavis** [comment]
Will do.  Oddly, this issue has suddenly resolved itself.  LH 6.0.0 in Microsoft Edge is no longer reporting any accessibilities issues:

![image](https://user-images.githubusercontent.com/4434533/94680058-01b79f00-02d6-11eb-82b6-92eb10259cf7.png)

We have the same black text on white background as before....  Strange.

**Comment by lloydjatkinson** [comment]
This is still an issue for white on red.

https://uxmovement.com/buttons/the-myths-of-color-contrast-accessibility/

![image](https://user-images.githubusercontent.com/5633938/182255605-5d8fc7fd-4eb9-4531-9316-8a02c35ebe54.png)


Now with a real world example:

![image](https://user-images.githubusercontent.com/5633938/182255518-3afc94ff-665b-4e67-87e9-006f1ca73376.png)
