### ISSUE TITLE
Images have good ratio, yet LightHouse flags as inappropriate size

### ISSUE THREAD

**Issue by drriot13** [GoogleChrome/lighthouse#11485]
Sometimes when I do a LightHouse audit, some images are flagged as having inapproprites sizes/aspect ratios when everything actually seems fine. I have an example of what has been flagged in a mobile audit. I do not understand why it would expect an image size larger than the screen reading it
![lighthouse-image-size](https://user-images.githubusercontent.com/52941119/94482281-03cf1000-01a7-11eb-8f60-82e0ac617f62.JPG)

**Comment by patrickhulce** [comment]
Thanks for filing @drriot13!

> I do not understand why it would expect an image size larger than the screen reading it

In short, DPR. See https://github.com/GoogleChrome/lighthouse/issues/11240, https://github.com/GoogleChrome/lighthouse/issues/11238, https://github.com/GoogleChrome/lighthouse/issues/10802#issuecomment-630233444, https://github.com/GoogleChrome/lighthouse/issues/11169#issuecomment-664693157
