### ISSUE TITLE
Speed Index NaN

### ISSUE THREAD

**Issue by nmcin** [GoogleChrome/lighthouse#11498]
#### Provide the steps to reproduce
1. Run LH on <heyclass.cl>
  

#### What is the current behavior?
Report fails to show performance index, caused by an error in the speed index calculation (NaN).

#### What is the expected behavior?
Report calculating a numeric Speed Index and showing the performance index.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 6.0.0
* Chrome version: 85.0.4183.121 (Official Build) (64-bit)
* Node.js version:
* Operating System: Linux, Pop OS (Ubuntu based)

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @nmcin! This was fixed awhile back and is slowly making its way to Chrome stable. Use Canary for an immediate fix.

See #11154 #11173 #11314
