### ISSUE TITLE
High TTI / Blocking time without real world consequences, is it possible ?

### ISSUE THREAD

**Issue by NanoPish** [GoogleChrome/lighthouse#11501]
#### Provide the steps to reproduce
If you run LH on [this url](https://www.soleilvacances.com/mentions-legales/)
```

#### What is the current behavior?

you get a huge TTI / javascript main thead (bad) score. e.g.

```
Time to Interactive
38.6 s
Total Blocking Time
24,240 ms

#### What is the expected behavior?

Why is the score so bad, when running this page on a 512mb ram nexus s android studio emulator in instantaneous ?
In the trace we see a recurrent function call takes more than 50ms multiple times, causing the bad score. But it doesn't seem to affect the real speed of the page loading.

#### Environment Information
* Affected Channels:  CLI, extension
* Lighthouse version: 6.3 and 6.0
* Chrome version: Version 85.0.4183.121 (Official Build) (64-bit)
* Node.js version:
* Operating System: Ubuntu 18

**Comment by patrickhulce** [comment]
Thanks for filing @NanoPish!

TTI and TBT don't measure anything related to the *visual* state of the page. You might want to learn more about what they measure in the documentation ([TTI](https://web.dev/tti/), [TBT](https://web.dev/tbt/))

**Comment by NanoPish** [comment]
> Thanks for filing @NanoPish!
> 
> TTI and TBT don't measure anything related to the _visual_ state of the page. You might want to learn more about what they measure in the documentation ([TTI](https://web.dev/tti/), [TBT](https://web.dev/tbt/))

I believe I understand the metrics and that they are related in my case to event listening causing > 100ms function calls, making the thread considered blocked.
The issue is in this case, it does not feel like the page is blocked, even if the third party script causes such function calls.

**Comment by patrickhulce** [comment]
> it does not feel like the page is blocked

But it is... 😅 I'm not sure what else to say. That's what large JS execution tasks do, block the main thread.

**Comment by NanoPish** [comment]
Okay thanks.
