### ISSUE TITLE
Safari Compatibility

### ISSUE THREAD

**Issue by svkrclg** [GoogleChrome/lighthouse#11507]
Just curious to know, why lighthouse doesn't work for Safari browsers.
Is there any other way to get the same metrics for safari?

**Comment by patrickhulce** [comment]
You can find some explanations in https://github.com/GoogleChrome/lighthouse/issues/6032#issuecomment-422123139 and https://github.com/GoogleChrome/lighthouse/issues/2406#issuecomment-579457485. Bottom-line: the advice in Lighthouse should be applicable to performance best practices in *all* browsers and (even if certain performance hints are not implemented in all of them yet). While *measuring* these metrics *using* other browsers isn't possible given their available protocol API surface, the performance score and metric values are fairly browser agnostic, nothing about the UX that these metrics capture is Chrome-specific.

**Comment by svkrclg** [comment]
Okay got it. But if we are not getting this LightHouse centric metric directly, is there some other way around to use the metric provided by safari and mapping it to our LH metrics (with some marginal error obviously ).
Just an idea

**Comment by patrickhulce** [comment]
> is there some other way around to use the metric provided by safari

No, the problem is that Safari does not provide these metrics yet or even the data necessary to compute them. See #6032 and #2406.
