### ISSUE TITLE
Regression in Lighthouse 6.4.0 – .tmp folder adds extra 50MB to the npm package

### ISSUE THREAD

**Issue by alekseykulikov** [GoogleChrome/lighthouse#11511]
It's a regression in Lighthouse 6.4.0.
Published `.tmp` folder adds extra 59MB to the module size on disc (without any value).

```bash
du -sh node_modules/lighthouse/.tmp
 59M    node_modules/lighthouse/.tmp
```

<img width="400" src="https://user-images.githubusercontent.com/158189/94925292-42264100-04bf-11eb-8e9c-6d97157a6c00.png">

Bonus: If we are on topic of cutting the package, `__snapshots__` add extra 7MB as well 😀

**Comment by patrickhulce** [comment]
Ouch, thanks for bringing to our attention @alekseykulikov!

**Comment by patrickhulce** [comment]
> __snapshots__ add extra 7MB as well

I can't see this though. Snapshots are only 42KB locally, what specific directory were you referencing @alekseykulikov ?

```bash
$ pkgfiles | grep snapshots
lighthouse-cli/test/cli/__snapshots__/index-test.js.snap                                       43.2 kB  0%
lighthouse-cli/test/cli/__snapshots__/                                                         43.2 kB  0%
```

**Comment by alekseykulikov** [comment]
Thank you for the fix!

I was experimenting with [`yarn autoclean`](https://classic.yarnpkg.com/en/docs/cli/autoclean/) and adding `__snapshots__` saved 7MB. But I can't reproduce it now.  I am sorry for the confusion.
