### ISSUE TITLE
Runtime error encountered: Invalid output mode:

### ISSUE THREAD

**Issue by ksoutherland** [GoogleChrome/lighthouse#11528]
When trying to generate reports from the CLI it gives me **Runtime error encountered:** Invalid output mode: only when I'm trying to output multiple file types.
![LightHousePowershell Error](https://user-images.githubusercontent.com/72516153/95360868-a10a0280-0891-11eb-9a3f-e54bd6aed17b.png)
However when my co-worker runs the same script on his system it works perfectly fine.

`$urls = Get-Content "\\Lighthouse\urls.txt" -Raw | ConvertFrom-Json

$counter = 0

foreach($url in $urls) {
    $counter += 1
    ""
    "Starting report for: $($url.url)"
    lighthouse $url.url --config-path="\\location\custom-config.js" --chrome-flags="--headless --user-agent='PCC ISC'" --emulated-form-factor none --output "html","csv" --output-path "\\location\$($url.fileName)" --quiet
    "Finished report for: $($url.url)"
}`

**Comment by patrickhulce** [comment]
Thanks for filing! Replace `--output "html","csv"` with `--output=html --output=csv`.
