### ISSUE TITLE
Address high-volume Sentry errors

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11524]
We have a handful of Sentry errors with >10k instances. We should open an issue for each.

**Comment by connorjclark** [comment]
It'd be nice to clear all the old errors from Sentry. I tried to make a search query to identify issues that haven't been seen in new releases, but it doesn't seem to be possible... the obvious thing to try was [this](https://sentry.io/organizations/google-lighthouse/issues/?project=174697&query=is%3Aunresolved+%21release%3A7%2A&statsPeriod=90d), but I can [find](https://sentry.io/organizations/google-lighthouse/issues/853389652/tags/?project=174697&query=is%3Aunresolved+%21release%3A7%2A&statsPeriod=90d) issues here that do have 7.*.* releases, so no good. Maybe we could just clear the entire backlog and let new issues roll in?

**Comment by connorjclark** [comment]
I resolved all the open issues. They will re-open as they happen again.

**Comment by brendankenny** [comment]
@connorjclark can we close this? Add it to the bug bash list or something?
