### ISSUE TITLE
Adsense and Analytics scripts are hurting Performance score

### ISSUE THREAD

**Issue by MtDalPizzol** [GoogleChrome/lighthouse#11527]
Hi, everyone.

My company is working hard to match all of Google's expectations about performance on our websites.
We followed every single article relevant to our pages at web.dev and pratically rebuilt our code base as a whole.
Our performace score DID got better and the improvements on user experience are perceptible.

However, we couldn't get our pages to enter the "green score". We can't get them to a 90 or higher score, no matter what we do.

Analysing Lighthouse repport, we can see that we have 2 main problems remaining: Time To Interactive and Total Blocking Time are to high.

The problem is that Lighthouse is complaining exactly about the execution time of Google's Adsense and Analytics scripts. It also says that gtag's script are not used.

You can see this on [this Lighthouse repport](https://ibb.co/KhG0Cf0) snapshot.

So, I'd like to know if we missed something. If there's a specific way to load this scripts other than with "async" or "defer".

It's really frustrating because Google pratically tells us to remove all of our javascript from the pages, then requires the only scripts on the page to be the Google ones, but these same scripts prevent the pages form being considered "fast" by Google.

**Comment by patrickhulce** [comment]
Thanks for filing @MtDalPizzol! Glad to hear you were able to make many improvements :) I'll try to go through your points...

> The problem is that Lighthouse is complaining exactly about the execution time of Google's Adsense and Analytics scripts.

The analytics contribution would still be low enough to get you green, Google Ads are the real problem here for the metrics.

> It also says that gtag's script are not used.

If you're only using GTM for Google Analytics, this is fixable by following their [analytics.js installation guide](https://developers.google.com/analytics/devguides/collection/analyticsjs/) (which is annoyingly buried behind three clicks of the default installation I know 😞 ).

> then requires the only scripts on the page to be the Google ones

Is there something in Lighthouse that led you to believe this? We definitely aren't trying to tell anyone that and would happily fix it if there's something we missed that says this.

> these same scripts prevent the pages form being considered "fast" by Google.

I understand and share your frustration that Google Ads are responsible for this page not being considered fast. That is their impact on the metrics though, so Lighthouse will continue to surface this information.

**Comment by MtDalPizzol** [comment]
Hey @patrickhulce .

Thanks for the quick response.

> then requires the only scripts on the page to be the Google ones`

Sorry for this. This was an exageration. I understand that Lighthouse doesn't mandate us to remove all of our scripts. What I meant was that in Lighthouse, Google is kind of draconian with the way we handle our own scripts at the same time that Google doesn't provide a way to ad AdSense to our page without hurting performance. So, we get into this strange place where Google requires something from developers at the sime time it doesn't stick to its own rules when providing scripts for AdSense.

My concern is that, because of this, our SEO, Google Discover and Google New results end up hurt, since Google is now using Core Web Vitals for its recommendations . Do you see where I'm getting? This is a scenario where Google will rank our pages lower because we don't match it's expectations BECAUSE OF A GOOGLE SCRIPT.

Sorry to go on and on about this, but we're really obsessed with this since our traffic vanished in the last two months and we believe that one of the causes was that our websites were really bad at CLS assessments and we're trying catch up with Google's requirements.

**Comment by patrickhulce** [comment]
> My concern is that, because of this, our SEO, Google Discover and Google New results end up hurt, since Google is now using Core Web Vitals for its recommendations . Do you see where I'm getting? This is a scenario where Google will rank our pages lower because we don't match it's expectations BECAUSE OF A GOOGLE SCRIPT.

I get exactly what you're saying, and I know it's frustrating, especially for the lack of performant alternatives if the site relies on ad revenue. If it's any consolation though, TBT and TTI are not *technically* core web vitals, FID is. If your field data for FID is passing the thresholds, then I wouldn't let this concern be your highest priority. 

Maybe it's comforting, maybe it's not, but continuing to surface this data in Lighthouse is what's most likely going to be able to create incentives for third-party code (like Google Ads) to limit their performance impact moving forward. Doing something to hide their impact in Lighthouse would not change the impact they have on the core web vitals metrics in the field, so I think you might agree there's nothing to change within the lab measurement side of things.

**Comment by MtDalPizzol** [comment]
Ok, then. Thanks for the support!
