### ISSUE TITLE
Would be great to be able to give reports a name when creating a new one

### ISSUE THREAD

**Issue by landwire** [GoogleChrome/lighthouse#11543]
**Feature request summary**

Would be great to be able to give reports a name!

**What is the motivation or use case for changing this?**

**How is this beneficial to Lighthouse?**
Comparing desktop and mobile reports, old and new quickly for instance.

**Comment by paulirish** [comment]
@landwire how would this work? are you using the Lighthouse CLI or something else?

**Comment by brendankenny** [comment]
Closing as inactive, but happy to open again if it's still worth discussing.

**Comment by landwire** [comment]
Oops, never saw the comment from Paul Irish. I am using just the browser.
