### ISSUE TITLE
"Displays images with inappropriate size" reports images although the correct src is loaded

### ISSUE THREAD

**Issue by landwire** [GoogleChrome/lighthouse#11542]
#### Provide the steps to reproduce
1. Run LH on https://beate-kampel.de/
  

#### What is the current behavior?
Reports the 2 images as expected a bigger size.

#### What is the expected behavior?
Not reproting, as the browser uses the correct srcset (3x dpi)

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 85.0.4183.102
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @landwire! This has been fixed in latest Lighthouse and will just take a while to make its way to Chrome stable :)

![image](https://user-images.githubusercontent.com/2301202/95626671-5bd80300-0a40-11eb-95af-d333c8e1a42a.png)

**Comment by landwire** [comment]
oh great! Thank you!
