### ISSUE TITLE
<amp-youtube not being recognized for accessibility

### ISSUE THREAD

**Issue by Frenchomatic** [GoogleChrome/lighthouse#11553]
Adding title tags to amp-youtube such as  <amp-youtube title="this is my description" gets flagged as not being accessible. The accessibility error is given as **<frame> or <iframe> elements do not have a title**.  

However, using <amp-iframe title="this is my description" would appear to meet the necessary criteria so something strange is going on.  I imagine this is a straightforward thing to fix as accessibility is very important and particularly in legal contexts such as healthcare and the ADA laws. 

In the meantime, youtube videos can be embedded into <amp iframe ... but it would be better to just have this fixed unless adding a title tag is insufficient.

**Comment by patrickhulce** [comment]
Thanks for filing @Frenchomatic! This sounds like a legitimate accessibility problem with the amp-youtube element though. 

If you'd like this fixed in AMP, consider filing this with the [amphtml project](https://github.com/ampproject/amphtml)?

**Comment by Frenchomatic** [comment]
I would file it but I had a dispute with one of their team a few years back and they banned me for arguing.

Looks like the way round this is to use the AMP iframe with a title tag instead. I will try that. 

I will also talk with the ampforwp plugin people. They may be able to get things fixed. Thanks for your efforts.

**Comment by patrickhulce** [comment]
Alright, best of luck tracking it down! We're going to close because there is no action for Lighthouse here.
