### ISSUE TITLE
Recommended config for desktop performance test

### ISSUE THREAD

**Issue by ask-imran** [GoogleChrome/lighthouse#11555]
Hey, 
Am sorry if this has been documented somewhere, I couldn't find any.

I tried with the following config https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/perf-config.js  but didn't receive similar results with the result ran from lighthouse extension. 

I have been trying to test my site inside a docker container for performance metric, unfortunately each run results in different results. Although I could see the  `CPU/Memory Power` different, it makes it hard for me to baseline.

This is my current config,

`  settings: {
    onlyCategories: ['performance'],
    emulatedFormFactor: 'desktop',
    maxWaitForFcp: 15 * 1000,
    maxWaitForLoad: 35 * 1000,
    throttling: desktopDense4G,
    channel: 'devtools'
  },`

Is it okay to add `channel` as devtools when am running from node ? also do I need to have `throttlingMethod` to devtools ?

`desktopDense4G` is the same as [here ](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/constants.js#L43)

**Comment by patrickhulce** [comment]
Thanks for filing! That is the correct closest config for desktop results. The rest is [variance](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) :)

> Is it okay to add channel as devtools when am running from node ?

It won't affect any results.

> also do I need to have throttlingMethod to devtools ?

Not if you'd like to match the extension as closely as possible.
