### ISSUE TITLE
Lo sentimos. No pudimos encontrar ese dominio. MI SITE IS NOT AT THINK GOOGLE!

### ISSUE THREAD

**Issue by wwwresponsable** [GoogleChrome/lighthouse#11559]
When trying to check my site https://seresponsable.com/ at Think Google
an advices shows as
WE CANT FIND YOUR SITE .. why???

[https://seresponsable.com/](https://seresponsable.com/)

**Comment by patrickhulce** [comment]
I don't know @wwwresponsable, sorry :/ 

Is there something that pointed you to file an issue here about it? This repo isn't for UI problems with Test My Site.
