### ISSUE TITLE
Usage of Lighthouse offline ->"Lighthouse is warming up"

### ISSUE THREAD

**Issue by MarLaDuu** [GoogleChrome/lighthouse#11556]
I downloaded the latest Chrome Version 86.0.4240.75
It has lighthouse integrated in the developer Tools.
I saw the Google developer Addy Osmany affirming that Lighthouse is supposed to work offline. (on Twitter)
In my application, Lighthouse is supposed to work mostly without Internet Connection, some of these PC's don't ever see the light of Internet, and that's not up to me.
I tested a page in a Virtual Machine without Internet connection, to verify it's usability. It only shows "lighthouse is warming up" for an hour now.
The machines network adapter is active, the operating system is Windows 7 (on other machines it will be Windows 10)
Is there any kind of download Lighthouse is attempting? Maybe I can manually provide missing stuff (although I am not a programmer). 

My Colleague tested this in his VM (Windows 10) after I asked him, and he had the same issue.

(I found similar issues... no hint I tested helped)

Is there somehow a way, I can generate a Lighthouse USB Stick?
Any tutorials, anything?
Any thoughts on the topic would be greatly appreciated!

**Comment by patrickhulce** [comment]
Thanks for filing @MarLaDuu!

> don't ever see the light of Internet

If they *never* see the internet, then Lighthouse won't work in DevTools for Chrome versions before m88. Lighthouse is fetched from a remote server and isn't bundled with Chromium, every new Chrome update prior to m88 needs to fetch Lighthouse when it's run.

Options for machines that never have internet access:

1. Install node on these machines and then use the node CLI (copy over the node installer exe and `node_modules` folder from another machine after `npm install lighthouse`).
2. Use Chromium 88 or later (Currently Chrome Canary) on these machines.

**Comment by MarLaDuu** [comment]
OK, thanks for clarification. So unless I want to make some stunts (node CLI) I better wait until January 2021, thats what I got from your answer. Although I don't know what m88 means. I guess you mean Chrome Version 88.
Thanks anyway.

**Comment by patrickhulce** [comment]
> So unless I want to make some stunts (node CLI) I better wait until January 2021

You could also use Chrome Canary to get it working today, but yes those are your options.

**Comment by MarLaDuu** [comment]
Thanks, I wanted to test this, but wasted one hour trying to find a way to get a standalone setup for canary. But as it seems there is no offline installer. What am I missing?

**Comment by patrickhulce** [comment]
https://www.google.com/chrome/?extra=canarychannel&standalone=1
