### ISSUE TITLE
no_lcp when there's only an svg in the body

### ISSUE THREAD

**Issue by RCopeland** [GoogleChrome/lighthouse#11551]
I was working on a pen on codepen.io and I noticed that I get a no_lcp error when running a lighthouse performance audit.
If I add another element, the score returns normally.

Maybe related? https://github.com/GoogleChrome/lighthouse/issues/10869

<img width="1658" alt="Screen Shot 2020-10-11 at 11 51 11 AM" src="https://user-images.githubusercontent.com/412903/95683399-f3606180-0bb8-11eb-97f6-382577079cf3.png">
Svg is the only thing in the pen

<img width="1667" alt="Screen Shot 2020-10-11 at 11 49 56 AM" src="https://user-images.githubusercontent.com/412903/95683394-ec395380-0bb8-11eb-8b2f-0d502612cec8.png">

Added a 
```
<p> 
```
with some lorem ipsum text

#### Provide the steps to reproduce
Run LH on https://codepen.io/robcopeland/pen/eYzNmwe. 
  
#### What is the current behavior?
Lighthouse returns a ? for the performance score, reports a no_lcp error for lcp sub section.

#### What is the expected behavior?
Lighthouse would report a score for lcp and also for performance in total.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version:
* Chrome version: Version 85.0.4183.83 (Official Build) (64-bit)
* Node.js version: runs on codepen.io
* Operating System: MacOS 10.15.3

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/10869

**Comment by patrickhulce** [comment]
Thanks very much for filing @RCopeland! This is tracked by https://github.com/GoogleChrome/lighthouse/issues/11326 and is unfortunately due to the spec itself not recognizing SVG as content for LCP. See the updates on #11326 for references to the upstream discussion.
