### ISSUE TITLE
"Avoids an excessive DOM size" audit shows NaN when it exceeds 1000

### ISSUE THREAD

**Issue by sisidovski** [GoogleChrome/lighthouse#11562]
#### Provide the steps to reproduce
1. Run LH on https://www.yahoo.co.jp/ with desktop mode like this `./lighthouse-cli/index.js https://www.yahoo.co.jp/ --view --emulated-form-factor=desktop`
1. See dom-size audit in HTML report
  

#### What is the current behavior?

When the number of total DOM size proceeds 1000, the Lighthouse HTML results shows NaN in the table.

![Screen Shot 2020-10-14 at 19 03 05](https://user-images.githubusercontent.com/1642255/95975380-0c833f80-0e51-11eb-8ba2-6fc8463f77e4.png)

#### What is the expected behavior?

Formatted number should be appeared, which is `1,114`

I think it can be fixed by removing _i18n.formatNumber_ in the audit from [here](https://github.com/GoogleChrome/lighthouse/blob/8caa938b41f3330c393fcf2a1226ffb4afe89b55/lighthouse-core/audits/dobetterweb/dom-size.js#L103). Currently _formatNumber_ is called twice in here and [details-renderer](https://github.com/GoogleChrome/lighthouse/blob/8caa938b41f3330c393fcf2a1226ffb4afe89b55/lighthouse-core/report/html/renderer/details-renderer.js#L186), which is injected to HTML report.

#### Environment Information
* Affected Channels: Node, DevTools etc
* Lighthouse version: 6.4.1
* Chrome version: 86.0.4240.75
* Node.js version: v12.16.1
* Operating System: MacOS

**Related issues**

**Comment by adamraine** [comment]
@sisidovski I think your assessment is correct. Looks like we need to address this `TODO`.
https://github.com/GoogleChrome/lighthouse/blob/8caa938b41f3330c393fcf2a1226ffb4afe89b55/lighthouse-core/audits/dobetterweb/dom-size.js#L98-L104
