### ISSUE TITLE
dell.com inspection freezes Lighthouse

### ISSUE THREAD

**Issue by mazalgarab-git** [GoogleChrome/lighthouse#11567]
#### Provide the steps to reproduce
1. Run LH on <https://www.google.com/search?sxsrf=ALeKk02PZyh5xfU8ckA3LVNko0U-Qbm3Zg%3A1602818852724&ei=JBOJX-PWK67H5gLy9r_IDQ&q=dell.com&oq=dell.com&gs_lcp=CgZwc3ktYWIQAzIECCMQJzIECCMQJzIFCAAQyQMyBwgAEBQQhwIyBwgAEBQQhwIyAggAMgIIADICCAAyAggAMgIIADoFCAAQkQI6CAgAELEDEIMBOgsILhCxAxDHARCjAjoECAAQQzoHCCMQyQMQJzoHCAAQsQMQQzoKCAAQyQMQFBCHAlCS3sMBWL7mwwFgqOfDAWgAcAF4AIABygKIAfUKkgEHMC41LjEuMZgBAKABAaoBB2d3cy13aXrAAQE&sclient=psy-ab&ved=0ahUKEwjj-OvClbjsAhWuo1kKHXL7D9kQ4dUDCA0&uact=5>
  - Get google.com (using an account or not).
  - Insert dell.com to get browsing results.
  - Get Chrome inspection
  - Get a report of Lighthouse

#### What is the current behavior?
The inspection freezes the platform.
#### What is the expected behavior?
Get a report.

#### Environment Information
* Affected Channels:  Inspection tools available for Chrome
* Lighthouse version: 
* Chrome version:  Version 86.0.4240.75 (Official Build) (64-bit)
* Node.js version:  v12.19.0 (but after the event)
* Operating System: Windows 10 Pro; (c) 2020 Microsoft Corporation. All rights reserved. 

**Related issues**
A comment on the issue has been delivered using VirusTotal.com as a contribution for a well-called dell.com - Google Search; the contribution is available at the following link: https://www.virustotal.com/gui/url/7aa366cb87a05054fbdde4c9a7f1e5b185672c2bd21729a756d2639801c74dae

**Comment by patrickhulce** [comment]
Thanks for filing @mazalgarab-git! I can't reproduce this though.

![image](https://user-images.githubusercontent.com/2301202/96270177-ebc20380-0f90-11eb-8e86-5faef60b6003.png)


Could you please be more specific on what you mean by "freezes the platform"? Is any message displayed? Does Chrome crash? etc

**Comment by mazalgarab-git** [comment]
Nonetheless, you may consider the log or usage timing when running an application or software or hardware. Consequently, it is possible that the issue was fixed after a short time (just in the case the issue be corresponding); it can be also deemed as a particular event subjected to certain factors; for instance, it could be an issue of the Internet Service Provider (ISP). In brief, the exposed event requires validation given the usage in a particular and unrepeatable time.

**Comment by patrickhulce** [comment]
I'm sorry I didn't understand that @mazalgarab-git. What are you saying Lighthouse should be doing?

Chrome crashes are automatically logged periodically reported if the user opted in, Lighthouse logs from DevTools are never uploaded them but you can in fact access them if you experience something like this (open DevTools on DevTools). Are these what you were talking about?

**Comment by mazalgarab-git** [comment]
The initial-post purpose was to share a crash experience (i.e. in other words a sort of frozen platform after conducting an inspection). I do not get the output of the Lighthouse inspection. In my view, Lighthouse logs are subjected to be queried due to the runtime settings that are stated; what is more, the data management is possible under development tasks. The post was on a user experience not a developer one. In brief, it is on a crash event; I did not deepen in the event as a Chrome DevTools developer.

**Comment by patrickhulce** [comment]
I understand, and thank you for sharing it.

What I'm trying to communicate is that we don't upload user logs anywhere out of respect for privacy, and I cannot reproduce the crash you were experiencing given the steps you listed. 

Without any actionable information, there's not anything we can really do. Unless there's additional steps missing or more information about the type of crash you can provide that enables us to reproduce, we'll likely have to close.
