### ISSUE TITLE
Big differences of performance metrics between CLI and DevTools

### ISSUE THREAD

**Issue by coslex** [GoogleChrome/lighthouse#11568]
#### Provide the steps to reproduce
1. Run LH on https://developers.google.com/
2. Run LH with the script from https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically using the same url (https://developers.google.com/) and slightly different options:
```
const options = {
      output: "html",
      port: chrome.port,
      emulatedFormFactor: "desktop",
      onlyCategories: ["performance"],
};
```

#### What is the current behavior?
Getting different results for weeks. 

Results in Chrome looks like this:
<img width="1625" alt="Bildschirmfoto 2020-10-16 um 15 25 37" src="https://user-images.githubusercontent.com/56072794/96263955-f2b63980-0fc3-11eb-8374-52ae43a18b4c.png">

And with the CLI like this:
<img width="1374" alt="Bildschirmfoto 2020-10-16 um 15 25 18" src="https://user-images.githubusercontent.com/56072794/96263936-ea5dfe80-0fc3-11eb-9246-a45d02b7f930.png">

#### What is the expected behavior?
The performance metrics are nearly the same.

#### Environment Information
* Affected Channels: CLI, DevTools
* Lighthouse version: Tested with 6.4.1/6.4.0/6.3.0/6.2.0
* Chrome version: 86.0.4240.80 and 85.0.4183
* Node.js version: 13.11.0
* Operating System: macOS Catalina 10.15.6

I have testet with different sites but experiencing the same behavior on each of them.

**Comment by patrickhulce** [comment]
Thanks for filing @coslex! The config you shared is not using the same settings as what is run in DevTools. You can refer to the [desktop config](https://github.com/GoogleChrome/lighthouse/blob/63106556bef14821c0714d12365965b9a0abf020/lighthouse-core/config/lr-desktop-config.js) for the throttling settings used. You can also refer to the [variability docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) for more on why these will be unlikely to match.

**Comment by coslex** [comment]
@patrickhulce thanks for the fast answer. Somehow I missed to set the config for desktop. Now its working as expected.
