### ISSUE TITLE
Lighthouse incorrectly identifies sub bullets with “Lists do not contain only <li> elements and script supporting elements”

### ISSUE THREAD

**Issue by SSA-Steel** [GoogleChrome/lighthouse#11565]
Lighthouse incorrectly identifies sub bullets with “Lists do not contain only `<li>` elements and script supporting elements”

Example HTML:

<ul>
<li>Bullet 1</li>
<li>Bullet 2</li>
<li>Bullet 3</li>
	<ul>
	<li>Sub Bullet 1</li>
	</ul>
</ul>

Test on https://www.ssa-corp.com/en/Ti-6Al-4V-Titanium-AMS-4928-UNSR56400.php

Chrome version: 86.0.4240.75 64-bit
Lighthouse version: 6.2.0
Windows 10 & 7

**Comment by patrickhulce** [comment]
Thanks for filing @SSA-Steel! This is working as intended though the markup is incorrect. The nested `<ul>` should be contained within an `<li>` element. See the [working with nested lists on MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals#Lists) and the axe [documentation](https://dequeuniversity.com/rules/axe/4.0/list).

**Comment by SSA-Steel** [comment]
Excellent, so simple.  Thanks!
