### ISSUE TITLE
ERR_CONNECTION_REFUSED no promise rejection 

### ISSUE THREAD

**Issue by dman777** [GoogleChrome/lighthouse#11569]
>   GatherRunner:error Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_REFUSED)

For this error, I am not getting any promise rejections. Is this the intended behavior or am I doing something wrong? I would like to have my automation set up to where it exits if the server was mistakenly not running and I get false positives on everything from it.

**Comment by patrickhulce** [comment]
Yes, this is the intended behavior, nothing went wrong *in Lighthouse* while checking the page and there's still some information Lighthouse was able to learn and return in the Lighthouse result object. This message means that the server refused to respond to Lighthouse's request. You can check [the `runtimeError` property](https://github.com/GoogleChrome/lighthouse/blob/63106556bef14821c0714d12365965b9a0abf020/docs/understanding-results.md#properties) of the LHR for critical page-related circumstances that made the page unauditable.

**Comment by dman777** [comment]
Thank you for the reply. 

How can I catch this error so I can have automation stop and exit?

**Comment by patrickhulce** [comment]
> You can check the runtimeError property of the LHR for critical page-related circumstances that made the page unauditable.

😉 

```js
const {lhr} = await lighthouse('https://example.com')
if (lhr.runtimeError) throw new Error(`Lighthouse had a runtime error: ${lhr.runtimeError.message}`)
```

CLI should already be exiting with a non-zero exit code, if that's where you're experiencing this then just respect the existing exit code :)

> I get false positives on everything from it.

When this happens, every single audit should be failing, so if you're doing anything with the results it should be hard to miss...

**Comment by dman777** [comment]
Thank you! :)

**Comment by dman777** [comment]
@patrickhulce  Just to confirm, please,... is ` const {lhr, artifacts, report} = runnerResult;` meant for public consumption? I didn't see it in documentation and I didn't know if there could be breaking changes in the future if they were not meant for public consumption.

**Comment by patrickhulce** [comment]
Yep, it's the [public API](https://github.com/GoogleChrome/lighthouse/tree/master/docs#using-programmatically).

Many of our examples try to use child processes with the CLI instead since devs have gotten themselves into trouble using the node module in ways that won't work, but you can rely on those properties not changing between minor/patch versions 👍
