### ISSUE TITLE
Different audit['resource-summary'] values: computeMedianRun vs individual test

### ISSUE THREAD

**Issue by leonardofaria** [GoogleChrome/lighthouse#11566]
1. Run LH on https://perf-site.thinkific-staging.com/courses/cooking-hotdog-with-performance-matters

#### What is the current behavior?

I have a node script running Lighthouse 5 times. After these runs, I use `computeMedianRun` to get the median results out of times. Here is an example

```js
for (let i = 1; i <= RUNS_PER_URL; i += 1) {
  try {
    printInfo(`       Running test ${i}/${RUNS_PER_URL}`);
    lh = await lighthouse(site.url, lighthouseOptions);

    results.push(lh.lhr);
  } catch (e) {
    printError(`Error testing ${site.url}`);
    printError(lh.lhr.runWarnings.join(`\n`));
    printError(e);
    process.exit(1);
  }
}

printInfo(`       Computing median runs and saving reports \n`);
const median = computeMedianRun(results);
``` 

Down in my script I persist the results of `report.audits['resource-summary']`, example: 

```js
const resourceSize = {};
report.audits['resource-summary'].details.items
  .filter(({ transferSize }) => transferSize > 0)
  .forEach(({ resourceType, transferSize }) => {
    resourceSize[resourceType] = transferSize;
  });
```

This snippet gives me an object like:

```js
{total: 725, document: 592, other: 133, third-party: 133}
```

#### What is the expected behavior?

These numbers are too low. If you run a single test using the CLI (`lighthouse https://perf-site.thinkific-staging.com/courses/cooking-hotdog-with-performance-matters --output=json --output-path=result.json --quiet` you will see the data stored is very different.

Another way to see this:

`report.audits['resource-summary'].displayValue` returns "23 requests • 1 KiB" when computeMedianRun is used and "24 requests • 693 KiB" when the CLI is used.

Side note, is this the best way to get a break down of what is loaded in the page? 

#### Environment Information
* Affected Channels: CLI, node
* Lighthouse version: 6.4.1
* Chrome version: 88 (Canary) and Chromium
* Node.js version: 12.16.2
* Operating System: macOS Catalina (10.15.7)

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @leonardofaria! 

`computeMedianRun` does not mutate any results, it only sorts and returns one of them, so whatever you're collecting is different from the CLI. I would double check that your `lighthouseOptions` are actually the same as the CLI and that the page is actually being audited correctly when you run it from node (and not receiving say an error or bot page).

See [variability docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) for more information on what could be causing differences in environments.

> Side note, is this the best way to get a break down of what is loaded in the page?

The `network-requests` audit actually lists every URL that was requested for you to break down any way you like if resource summary isn't sufficient for your use case.

**Comment by leonardofaria** [comment]
Thanks for the quick reply @patrickhulce.

I was previously using the `network-requests` but for my case, only the totals are enough. Thanks for clarifying this. 

Your message added some light to my problem. Decided to build a quick script to post here and it looks like the `disableStorageReset` option was messing the results. Here is the script for future reference:

```js
/* eslint-disable no-console, no-await-in-loop */
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');

const {
  computeMedianRun,
} = require('lighthouse/lighthouse-core/lib/median-run.js');

const processLighthouseResults = (report) => {
  const resourceSize = {};

  report.audits['resource-summary'].details.items
    .filter(({ transferSize }) => transferSize > 0)
    .forEach(({ resourceType, transferSize }) => {
      resourceSize[resourceType] = transferSize;
    });

  return resourceSize;
};

(async () => {
  const RUNS_PER_URL = 2;
  const URL = 'https://web.dev';
  const chrome = await chromeLauncher.launch({ chromeFlags: ['--headless'] });
  const lighthouseOptions = {
    // disableStorageReset: true,
    port: chrome.port,
    output: 'html',
    emulatedFormFactor: 'desktop',
  };
  const results = [];
  let lh;

  for (let i = 1; i <= RUNS_PER_URL; i += 1) {
    try {
      console.log(`Running test ${i}/${RUNS_PER_URL}`);
      lh = await lighthouse(URL, lighthouseOptions);

      results.push(lh.lhr);
    } catch (e) {
      console.log(e);
      process.exit(1);
    }
  }

  const median = computeMedianRun(results);
  console.log(processLighthouseResults(median));

  await chrome.kill();
})();
```

I'm closing this issue
