### ISSUE TITLE
Analizing website with an user and an googlebot version

### ISSUE THREAD

**Issue by wagnermeyer** [GoogleChrome/lighthouse#11575]
Hello! 

My website has a conditional accessing rule: if the access is being made by the Googlebot I deliver a page fully rendered by the server (**server-side** rendering). 

Otherwise, if the access is being made by a human being I deliver a page with SPA features (**client-side** rendering). 

**My question is:** In my last analysis using PageSpeed Insights (Lighthouse) I noticed that the results were based on the **client-side** rendering version. In this case, should I consider that the website performance result will be judged by Google by the **client-side** version? 

I'm a little bit confused about this behavior. 

Thanks :)

**Comment by Lofesa** [comment]
Hi
Maybe you test it with the UA? PSI don´t have a UA GoogleBot related.
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Safari/537.36 Chrome-Lighthouse"

**Comment by patrickhulce** [comment]
Thanks for filing @wagnermeyer! We don't really discuss explicit ranking signals here though, sorry! You can try official search communication channels if that's your primary concern.

From our perspective though, you should absolutely optimize the site that your end-users actually use, which is what PSI is already measuring :)
