### ISSUE TITLE
Lighthouse only works on alternate days somehow!

### ISSUE THREAD

**Issue by JRC21** [GoogleChrome/lighthouse#11588]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by JRC21** [comment]
Lighthouse only works on an alternate day to generate a report and its the latest version

**Comment by JRC21** [comment]
Hello,
I was only able to use it after downloading xamp , so, it's not working
smoothly with external support.

**Comment by patrickhulce** [comment]
Lighthouse is very unrelated to XAMPP, if that's what you're referring to here.

Can you fill out the bug report template that's in this issue? What specific behavior are you seeing? What environment are you trying to use? Why do you believe xamp is related? Without concrete information, we will be closing the issue.
