### ISSUE TITLE
Robots.txt

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#11582]
**Summary**
I have a robots.txt file that permit some bots to crawl the site and a default rule to block the crawl. Some like this:

```
Sitemap: https://path/to/file/sitemap_index.xml

user-agent: Some-bot
user-agent: Some-bot
user-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
User-agent: Some-bot
Allow: */path-to-file
Disallow: */path-to-file
Disallow: */path-to-file
Disallow: */path-to-file
Disallow: */path-to-file
Disallow: */path-to-file
Disallow:


User-agent: *
Disallow: /

```
The page has this meta in the html:

`<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1">`

Then run LH 6.2.0 and 6.4.0 from chrome dev tools and the SEO panel show this:
```
Search engines are unable to include your pages in search results if they don't have permission to crawl them. Learn more.
Blocking Directive Source
--
/robots.txt:32
```
I know that LH fails if not open to ALL bots (Even "bad" bots?) as stated here: https://web.dev/is-crawable/
I think this can be a recomendation but should not be taken in account for score. People from LH decide in what search engine a web owner decides to appear on?

**Comment by patrickhulce** [comment]
> People from LH decide in what search engine a web owner decides to appear on?

Of course not :) developers are welcome to block any search engine they like from discovering the page. It seems reasonable though that if a page blocks at least one potential search engine from discovering the page, the SEO score suffers.

I believe the thinking here was this: bad actors are bad actors, robots.txt isn't a tool to stop them, it's a tool to ask responsible actors to not send you traffic. The most likely impact of a *global* disallow on SEO is that smaller, responsible crawlers the site owner doesn't know about are now prevented from discovering the page, which is worthy of a score drop.

**Comment by Lofesa** [comment]
But ... I think that if a meta tag allows all bots to crawl the site, the robots.txt file should not be checked or even if it is checked, if there is more than one rule, and any of them allow crawling, scoring should not suffer.
What is the point for all the robots.txt grammar if, in short, to have a good score you have to have a single rule, whose last sentence is a Disallow:
At the very least it's a somewhat controversial punctuation decision.

**Comment by patrickhulce** [comment]
>  I think that if a meta tag allows all bots to crawl the site, the robots.txt file should not be checked or even if it is checked, if there is more than one rule, and any of them allow crawling, scoring should not suffer.

I think there's misunderstanding about robots.txt here. If a page is disallowed in robots.txt, a responsible actor would never even fetch the page to see the `meta` declaration. Disallowing the page in robots.txt [prevents its crawlability, period](https://support.google.com/webmasters/answer/7424835?hl=en). It does not matter what is set elsewhere.

> What is the point for all the robots.txt grammar if, in short, to have a good score you have to have a single rule, whose last sentence is a Disallow:

What led you to believe this? That's only true if there's nothing on the whole site to disallow, but then you don't even need a robots.txt at all. The specific problem here is a global disallow that includes the page in question, not that you must allow every route on the server to be crawlable.

**Comment by Lofesa** [comment]
> I think there's misunderstanding about robots.txt here. If a page is disallowed in robots.txt, a responsible actor would never even fetch the page to see the `meta` declaration. Disallowing the page in robots.txt [prevents its crawlability, period](https://support.google.com/webmasters/answer/7424835?hl=en). It does not matter what is set elsewhere.
> 
No, there is not a misunderstanding about robots.txt. I know that bad actors must be blocked in other ways, and mostly of these bad actors even don´t read robots.txt. 

> What led you to believe this? That's only true if there's nothing on the whole site to disallow, but then you don't even need a robots.txt at all. The specific problem here is a global disallow that includes the page in question, not that you must allow every route on the server to be crawlable.

With this decision about scoring, you only need 1 robots.txt rule, some like

```
user-agent: *
Disallow: */path-to-file
Disallow: */path-to-file
Disallow:
```
the point here is not about the role of robots.txt, it is about the free decision to appear, or not,  in a search engine and (note the and) get a good score. In order not to lose points on the scale, you cannot decide where to appear and let be crawled for search engines you don´t have interest (for whatever reason) in it and bear their traffic (and the cost).

Well, is a LH team decision and you can agree with it, or not.
Thx for your time.

**Comment by patrickhulce** [comment]
> No, there is not a misunderstanding about robots.txt. I know that bad actors must be blocked in other ways, and mostly of these bad actors even don´t read robots.txt.

Sorry for the miscommunication, I wasn't talking about a bad actor misunderstanding. I was a responding to your request to have Lighthouse give a free pass to sites that allow indexing in `meta[name=robots]` with an explanation of why that wouldn't work.

Thanks for your understanding!
