### ISSUE TITLE
Finalize naming for the preload LCP audit

### ISSUE THREAD

**Issue by Beytoven** [GoogleChrome/lighthouse#11599]
A concern was brought up in #11486 by @patrickhulce that it may be better to come up with an audit title that doesn't use the metric name "Largest Contentful Paint" as an adjective. So as not to block the PR, any further discussion can be had here and a decision can reached later on, ideally before the audit is moved from experimental to default.

**Comment by paulirish** [comment]
it moved into default config in #11612. so we can close this
