### ISSUE TITLE
Mark redirects-http as notApplicable on localhost

### ISSUE THREAD

**Issue by mathe42** [GoogleChrome/lighthouse#11598]
**Feature request summary**

The redirects-http audit should be disabled or pass when useing http and localhost. (e.g. `http://localhost:3000`).

**What is the motivation or use case for changing this?**
The 100 score should be posible in local testing without https.
In production I use a reverse proxy so in CI with LH-CI it is only http.

**How is this beneficial to Lighthouse?**
Better UX for local testing.

**Comment by tirtharajghosh** [comment]
Hi @paulirish I'd like to claim this issue. Could you please assign it to me?

**Comment by patrickhulce** [comment]
Thanks @tirtharajghosh! Let us know if you run into any stumbling blocks :)
