### ISSUE TITLE
Webp images not detected as such in Pagespeed

### ISSUE THREAD

**Issue by tomasts248** [GoogleChrome/lighthouse#11605]
PS returns the following warnings:

![121425_28102020](https://user-images.githubusercontent.com/32283036/97455962-2758b800-1917-11eb-946a-4272bfbe6e5e.jpg)

While this images are already in webp format (By using the following library https://github.com/rosell-dk/webp-convert)

![121012_28102020](https://user-images.githubusercontent.com/32283036/97455433-9b469080-1916-11eb-817c-2dae6fa7aa41.jpg)

**Comment by patrickhulce** [comment]
Thanks for filing @tomasts248! The resource that was served to Lighthouse is not what you're showing the second screenshot (that file is 42.8 KB, Lighthouse received one that's 168KiB). If there's some sort of UA sniffing going on to serve a webp file when a `.png` is requested, then I'd look into that to make sure it's actually working on the Lighthouse (and other users) UA strings.

**Comment by tomasts248** [comment]
Alright, so the htaccess file is not redirecting properly I suppose, I contacted the hosting and they will look into it. Thanks!
