### ISSUE TITLE
Best Practice bad report score impacted by google-analytics uri

### ISSUE THREAD

**Issue by aladeuil** [GoogleChrome/lighthouse#11618]
Hi !
When I use Lighthouse [on example here](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fwww.kortic.com%2Fphotographie%2Fbrouillard.html&strategy=desktop&category=performance&category=accessibility&category=best-practices&category=seo&utm_source=lh-chrome-ext#best-practices), the best practice score is impacted by google-analytics uri (!sic). But on the local console there is no log…
(Sorry for my poor english :-) )
Thank you.
![image](https://user-images.githubusercontent.com/3920497/97838054-b717b100-1cdf-11eb-8d98-b557b2b20f3b.png)

**Comment by patrickhulce** [comment]
Thanks for helping us by filing @aladeuil! 

This is the same root cause as https://github.com/GoogleChrome/lighthouse/issues/10362 so we'll go ahead and track progress over there though. Feel free to subscribe to that issue for any updates :)
