### ISSUE TITLE
AMP Video - Failed to load resource: net::ERR_CONNECTION_FAILED

### ISSUE THREAD

**Issue by Frenchomatic** [GoogleChrome/lighthouse#11624]
This simple amp code for rendering a video is giving two failed to load error messages and  a third error message which is  /null  ( www.mydomain.com)  Failed to load resource: the server responded with a status of 404 (Not Found)

`<amp-video controls width="1920" height="1080"  layout="responsive" title="Bla bla"><source src="/assets/files/cpf.webm" type="video/webm" /><source src="/assets/files/cpf.mp4" type="video/mp4" /><div fallback><p>Your browser cannot show this video.</p></div><div placeholder="" class="placeholder">
                  <div class="spinner">
                     <em></em>
                     <em></em>
                     <em></em>
                  </div>
               </div>
</amp-video>`

Page runs fine and is fast on several devices where it has been tested.

**Comment by Frenchomatic** [comment]
Sorry - I see why . A poster image needs to be put into the code and then these errors go away. In other words

<amp-video controls width="1920" height="1080" layout="responsive" title="Bla bla" poster="some-image.jpg>

**Comment by Frenchomatic** [comment]
I spoke to soon and clearly jumped the gun.  I am still getting the two main errors on the source video files.

**Comment by patrickhulce** [comment]
We can reopen if you're willing to share the URL here @Frenchomatic :)

**Comment by Frenchomatic** [comment]
ok. Here we go https://www.lechatterbox.com/formation-anglais-cpf.html

**Comment by connorjclark** [comment]
Is this still an issue? I don't see the error in PSI anymore.

**Comment by patrickhulce** [comment]
This appears to be resolved on PSI side, if it starts happening again, please feel free to reopen.
