### ISSUE TITLE
Move renderer bundle (for devtools) to use ES module exports

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/lighthouse#11628]
I am working on trying to run TypeScript on the `front_end/lighthouse` files in DevTools, but I am running into several problems. Most prominently, LightHouse puts several types on the global scope, such as `ReportRenderer` and `ReportUIFeatures` (see the declarations in https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/front_end/lighthouse/LighthouseReporterTypes.js;l=28-30;drc=1e10f8546c3cd94438e2046711e302a9dc771394)

To make consumption easier for DevTools and potentially improve tree-shaking and all, could we consider changing the way LightHouse exports symbols to use ES exports instead? E.g. rather than putting symbols on the global scope, make them `export class` definitions that DevTools can then import. This should be possible, now that LightHouse is bundled and several other infrastructure improvements have been made on the DevTools side.

**Comment by paulirish** [comment]
After discussion: we plan to change our bundling so that we'll expose the renderer/report-generator via a ESM `export`.  We'll do this with some clever concat/bundling but not converting our renderer source files to ESM (yet).

**Comment by paulirish** [comment]
Related: [Export lighthouse report renderer as a standalone ES Module · Issue #10926](https://github.com/GoogleChrome/lighthouse/issues/10926)

**Comment by connorjclark** [comment]
@TimvdLippe WIP here, requesting some feedback/help. https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2939422/1#message-5216dc86d872fa96a921b4a2cbd330c7f94dc3b7
