### ISSUE TITLE
Why am I getting "low resolution" warnings for images that are a prefectly adequit resolution?

### ISSUE THREAD

**Issue by JacobDB** [GoogleChrome/lighthouse#11630]
Really stumped on this one. The displayed size of my slideshow is reported as 360 x 206, yet Lighthouse insists that it wants the image to be 1080 x 618. What's going on here?

https://framework.jacob.rocks/

**Comment by patrickhulce** [comment]
Thanks for filing @JacobDB! 

>  What's going on here?

DPR :)

See https://github.com/GoogleChrome/lighthouse/issues/10802, https://github.com/GoogleChrome/lighthouse/issues/11238, https://github.com/GoogleChrome/lighthouse/issues/11169#issuecomment-664693157 for explanation and discussion.

**Comment by JacobDB** [comment]
Ah! I suspected as much, but the numbers didn't seem to add up, I see now that it's asking for 3x... thanks!

**Comment by patrickhulce** [comment]
Great! FYI the 3x was indeed a mistake and latest Lighthouse versions should only be advising 2x moving forward (might take awhile to reach stable Chrome though).
