### ISSUE TITLE
Devtools test are timing out locally

### ISSUE THREAD

**Issue by Beytoven** [GoogleChrome/lighthouse#11632]
Both `yarn test-devtools` or `yarn update:test-devtools` fail due to the tests timing out.

<img width="839" alt="Screen Shot 2020-11-05 at 9 49 54 AM" src="https://user-images.githubusercontent.com/27858957/98277829-a750d480-1f4c-11eb-9c32-f373633a06d9.png">

**Comment by connorjclark** [comment]
Might be `don't hide output of http server (blocked port hangs)` (ref #11414). Is port 8000 busy? You can delete the stdout redirection here https://github.com/GoogleChrome/lighthouse/blob/e7cb72dcb1c94550351b7634a671ba55416626e0/lighthouse-core/test/chromium-web-tests/web-test-server.sh#L30 to see.

**Comment by Beytoven** [comment]
The issue looks to have been my node version. I was using Node V15.02. I've switched back to Node 14 and I'm no longer encountering timeouts. Gonna go ahead and close this issue.
