### ISSUE TITLE
The 'Ah, sorry! We ran into an error.' error message is shown during the auditing

### ISSUE THREAD

**Issue by serafimovichvlad** [GoogleChrome/lighthouse#11640]
**Preconditions:** 
1. Clear the browser's cache and cookies

**Steps to reproduce:** 
1. Open https://cleeng.com/hi5-ott-customer-care
2. F12 - Lighthouse - Desktop - Generate report

**Actual behavior:** 
The error appears 

**Expected behavior:** 
The audit should be completed.

**Environment:** 
OS: Windows 10
Browser: Chrome 86.0.4240.183

**Comment by patrickhulce** [comment]
Thanks for filing @serafimovichvlad!

Could you try starting Chrome with `--force-fieldtrials=*BackgroundTracing/default/` flag? You might be opted into an experiment that prevents Lighthouse from running which there's not much we can do about :/
