### ISSUE TITLE
Lighthouse Error

### ISSUE THREAD

**Issue by loka365** [GoogleChrome/lighthouse#11644]
I just submitted my new website in Google Pagespeed Insights for a website speed audit. But it is returning an error as follows:

Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_FAILED).

The website https://blueheronhealthnewsreviews.com/ absolutely has no issue & load perfectly at present but still returning the above error.

**Comment by loka365** [comment]
"necessarily-wide-alpaca"

**Comment by patrickhulce** [comment]
Thanks for filing @loka365! I am unable to reproduce this.

![image](https://user-images.githubusercontent.com/2301202/98681440-56fcbc80-2328-11eb-87de-0bb8addcbbb0.png)

The reasons listed in #2784 can be temporary.

**Comment by loka365** [comment]
Thanks for your review. I think the problem was temporary, I also found no issue in PageSpeed Insights at present.
