### ISSUE TITLE
axe-core: update and evaluate all the enabled checks

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#11643]
axe 4.0!

also remove video-description, etc. https://github.com/GoogleChrome/lighthouse/pull/10128

-----

see last times we did this: 

- [evaluate new axe audits for inclusion · Issue #7127 · GoogleChrome/lighthouse](https://github.com/GoogleChrome/lighthouse/issues/7127)
- [Clean up aXe audits · Issue #6169 · GoogleChrome/lighthouse](https://github.com/GoogleChrome/lighthouse/issues/6169)

**Comment by patrickhulce** [comment]
Let's double check that #11649 is fixed by updating to axe 4 once this is done, if not we can reopen that issue :)

**Comment by connorjclark** [comment]
![image](https://user-images.githubusercontent.com/4071474/98996748-02f50200-24f9-11eb-90b0-2f301f38a328.png)

yayyyyy this gonna be fun

maybe will add a new build step to transpile this to commonjs, keep in `third_party`

actually this would be better: let's merge #11442, so we don't import this file directly from source.

**Comment by brendankenny** [comment]
for importing es modules into commonjs, need to use `import()`, not `require()`:

https://nodejs.org/api/esm.html#esm_interoperability_with_commonjs

**Comment by brendankenny** [comment]
(this can be annoying, however, because then it has to be `async`)

**Comment by connorjclark** [comment]
closed by #11661
