### ISSUE TITLE
Optimizing images sizes behind another one using position absolute causes PageSpeed score to decrease

### ISSUE THREAD

**Issue by tomasts248** [GoogleChrome/lighthouse#11651]
So the optimized images (inside red square) are behind the screen svg.. Sometimes PageSpeed reports up to 80points in mobile and others only 50, it has this erratic behavior ever since y optimized the image sizes, also before doing it didn't complain about them. Before the score was around 70points.

![171849_10112020](https://user-images.githubusercontent.com/32283036/98728878-d4e8b400-2378-11eb-89c1-1e69b8de6e90.jpg)

Code for non optimized version
```
<div class="contenido-imagenes mx-auto" style="width: 300px;">
                                                  <img class="imagen-pantalla-modulo mx-auto" src="<?php bloginfo('template_url'); ?>/img/pantallamodulo.svg">

                                                  <picture>
                                                    <?php $image2xretina = wp_get_attachment_image_src(get_field('imagen_modulo'), 'original'); ?>
                                                    <?php $image1xretina = wp_get_attachment_image_src(get_field('imagen_modulo'), 'original'); ?>
                                                      <source srcset="<?php echo $image2xretina[0]; ?>" media="(min-width: 1600px)">
                                                      <source srcset="<?php echo $image1xretina[0]; ?> 1x, <?php echo $image2xretina[0]; ?> 2x">
                                                      <img class="thumbnail imagen-modulo" srcset="<?php echo $image2xretina[0]; ?>" alt="<?php the_title(); ?>">
                                                   </picture>
                                                 </div>
```
Code for optimized version:
```
<div class="contenido-imagenes mx-auto" style="width: 300px;">
                                                  <img class="imagen-pantalla-modulo mx-auto" src="<?php bloginfo('template_url'); ?>/img/pantallamodulo.svg">

                                                  <picture>
                                                    <?php $image2xretina = wp_get_attachment_image_src(get_field('imagen_modulo'), 'medium_large'); ?>
                                                    <?php $image1xretina = wp_get_attachment_image_src(get_field('imagen_modulo'), 'medium'); ?>
                                                      <source data-srcset="<?php echo $image2xretina[0]; ?>" media="(min-width: 1600px)">
                                                      <source data-srcset="<?php echo $image1xretina[0]; ?> 1x, <?php echo $image2xretina[0]; ?> 2x">
                                                      <img class="thumbnail imagen-modulo lazyload" data-srcset="<?php echo $image2xretina[0]; ?>" alt="<?php the_title(); ?>">
                                                   </picture>
                                                 </div>
```
You can see the differences are the use of lazyload and smaller image sizes, before original size images were used.

Here's the link to the live page where this issue happens
https://www.institutocalma.org/vivir-en-en-calma-abierto-t/

**Comment by patrickhulce** [comment]
Thanks for filing @tomasts248! 

We don't really investigate code changes to find out what happened to pages though, sorry :/ 

If you have a minimal before/after repro of an issue that should obviously improve a particular performance metric but doesn't then we'll be happy to take a look. Without the direct comparison and a specific metric to look at though, this sounds a lot like [standard variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md).

**Comment by tomasts248** [comment]
Well I can make a codepen, one before and another after.. also maybe can you verify on your end that images behind other images are not properly detected? Here it is the first codepen (not optimized one)

**Comment by patrickhulce** [comment]
> maybe can you verify/confirm on your end that images behind other images are not properly detected as in the following codepen

Images with dimensions of `0` are excluded from the "Properly size images" audit. If the change you're talking about switched from having dimensions to not having dimensions (as part of lazy loading) then that would explain this behavior, but it does not mean the images were suddenly more performant.

If that's not it, then I'm not really sure what is being asked. In that case, explicit "expected" and "actual" behavior with specific audits or scores and accompanying codepen would be much appreciated :)
