### ISSUE TITLE
Extension Error: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by yoanmarchal** [GoogleChrome/lighthouse#1165]
**Lighthouse Version**: 1.2.2
**Chrome Version**: 57.0.2952.0
**Error Message**: Cannot read property 'message' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'message' of undefined
    at collectUsage.then.e (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:4444:23)```

**Comment by ebidel** [comment]
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1147
