### ISSUE TITLE
Animations using WebAnimations reports "Unsupported CSS property"

### ISSUE THREAD

**Issue by bakura10** [GoogleChrome/lighthouse#11658]
#### What is the current behavior?

Lighthouse reports me some issue in the performance panel with "Unsupported CSS property" (without even more details on which property is invalid):

![image](https://user-images.githubusercontent.com/1198915/98923606-347cc600-2517-11eb-9cfa-175f38eadb8e.png)

The only rather unusual thing here is that I am using WebAnimations JS. Here is for instance the animation I am doing:

```
imageElement.animate({
        visibility: 'visible',
        clipPath: ['inset(100% 0 0 0)', 'inset(0 0 0 0)']
      }, {
        duration: 800,
        easing: 'cubic-bezier(0.5, 0.06, 0.01, 0.99)',
        fill: 'forwards'
      });
```

Is Lighthouse not compatible with WebAnimation JS or is the elements I animate indeed cannot be composited (if that's the case they should not be reported by the tool?

Thanks :)

#### Environment Information
* Lighthouse version: 6.2
* Chrome version: 
* Operating System: OS X

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @bakura10!

"Unsupported CSS Property" is trying to tell you that one of the properties you're animating prevents the animation from being composited. Was this your interpretation? Whether the animation is scheduled via JS or CSS shouldn't really make a difference here.

> the elements I animate indeed cannot be composited

It is this case.

> if that's the case they should not be reported by the tool

I think there's a misunderstanding about this audit. The exact purpose of this audit is trying to surface to you animations that cannot be composited by the browser :) The aim is that by being aware of the problem you can try to find an alternative that *can* be composited. If there's no alternative that satisfies your use case, it comes down to a judgement call about how much (if any) layout shift it causes and if it's worth it.

**Comment by bakura10** [comment]
Hi,

But should not the tool give me more information about why it cannot be composited (like which property exactly)? i am using the WebAnimations JS API and using an animation on clipPath only. Does this mean that the clipPath animation cannot be composited?

**Comment by bakura10** [comment]
Even if I try to animate only the visibility property (not even the clip path) the tool flag it as a "non composited animation". Doing the same animation in pure CSS instead of WebAnimation JS does not flag any issue, which is why I thought there may be an issue with this audit with WebAnimations JS.

I will try to set up a minimal example that exhibit the issue :)

**Comment by bakura10** [comment]
After some further testing, it appears that both visibility and clip path indeed cannot be composited. If I replace the WebAnimations by a simple "opacity" the error disappear. Still, I believe it would be useful if the tool could provide the properties that cannot be composited and would link to a doc that would give a bit more info about which properties can and cannot be composited :)

**Comment by patrickhulce** [comment]
> Still, I believe it would be useful if the tool could provide the properties that cannot be composited and would link to a doc that would give a bit more info about which properties can and cannot be composited

[v6.3.0 has this links to this documentation](https://web.dev/non-composited-animations/) that answers these questions. If you have ideas on how to further improve it, please feel free to chime in on [that repo](https://github.com/GoogleChrome/web.dev/) :)
