### ISSUE TITLE
Lighthouse not working on my site w/ CLI, Chrome Dev, Chrome Canary, Chrome etc

### ISSUE THREAD

**Issue by LoopStrong** [GoogleChrome/lighthouse#11654]
#### Provide the steps to reproduce
1. Run LH on <https://www.casinobonus360.de> (All pages)
  

#### What is the current behavior?
Lighthouse loads a screenshot of a page in the first run, then returns an Error code: STATUS_ACCESS_VIOLATION
Opening DevTools shows images returning 404s, but they're 200 live on the site.
![hmmmm](https://user-images.githubusercontent.com/74291958/98787333-ab26a000-23ff-11eb-9856-842f589cbaa7.PNG)

#### What is the expected behavior?
Complete Lighthouse run with full results.

#### Environment Information
* Affected Channels: <! CLI, Chrome Dev, Chrome Canary, Chrome etc>
* Lighthouse version: 6.2, 6.4
* Chrome version: Version 86.0.4240.183 (Official Build) (64-bit)
* Node.js version:
* Operating System: Windows (tried with Mac too)

**Related issues**

**Comment by LoopStrong** [comment]
Sidenote, I followed all of the steps from the Google doc, RE clearing cookies, cache etc and it didn't work

**Comment by pineshmenat** [comment]
Try running it through [https://developers.google.com/speed/pagespeed/insights/](https://developers.google.com/speed/pagespeed/insights/)

**Comment by patrickhulce** [comment]
Thanks for filing @LoopStrong! This appears to be Chromium bug with renderer crashes and I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1147917 to take a look.

**Comment by LoopStrong** [comment]
@patrickhulce Thanks for raising a ticket. I do not have access to it. Will you be able to keep me posted? - So the main thing is that this is not a site issue, but a lighthouse issue? 

Cheers

**Comment by patrickhulce** [comment]
> Will you be able to keep me posted?

Subscribing to this issue should receive updates when they're posted here 👍 

> So the main thing is that this is not a site issue, but a lighthouse issue?

Yes, and not a Lighthouse issue, but a Chrome issue :)

**Comment by patrickdemooij9** [comment]
Hi @patrickhulce,
We are also facing this issue. What is the current progress on fixing the issue?

**Comment by patrickhulce** [comment]
The Chromium bug that this specific site is facing is being worked on by V8 team, but Chrome can crash for many different reasons so if you have a separate crash it's somewhat unlikely they're the exact same problem :) 

If you have a reproducible way to crash Chromium, an issue over at crbug.com with your crash ID details from `chrome://crashes` and repro steps would be great.

**Comment by adamraine** [comment]
The upstream Chromium bug has been marked as fixed, and I'm not seeing a crash on https://www.casinobonus360.de/. I think we can close this.
