### ISSUE TITLE
Memory/CPU consumption & a lot of processes spawned [Question]

### ISSUE THREAD

**Issue by victor-ponamariov** [GoogleChrome/lighthouse#11652]
Hello!

When I run lighthouse from cli I got this picture in `htop` output.

![image](https://user-images.githubusercontent.com/6241595/98729393-e39c8e80-23ab-11eb-8145-099a59da2cfb.png)

My aim is to run a lot of lighthouse reports (~300-400 per hour). So I need to optimize the process.

As you can see, both cpu + memory have high usage.  I'm not sure I know which characteristics should CPU/Memory have for such a task though. 

But what confuses me is the number of processes.

Plus, the task itself takes quite a lot of time (~1 min).

So, is there any recommendation about how to optimize the process? I need to get scores for all categories, since I plan to monitor their value across the time.

Thank you so much, Victor.

**Comment by patrickhulce** [comment]
Thanks for filing @victor-ponamariov! We've outlined the hardware and scaling recommendations in [our variability docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md#run-on-adequate-hardware).

It looks like you've spawned many lighthouse processes on the same machine, by default each one will create a separate instance of Chrome which will each have many processes. We highly recommend not doing this, see the same docs linked above :)

There's not really going to be a magic shortcut here, sadly, spinning up browsers and analyzing webpages is going to be resource intensive.

**Comment by victor-ponamariov** [comment]
Oh well, the thing is I'm pretty sure I ran single lighthouse command. I'll dig into it more.
In the meanwhile, I've just seen that there is google API which does the same.

I'm building an app that monitors the lighthouse scores. So if I'm right I'd better use google API for this purpose, am I right? :)

**Comment by patrickhulce** [comment]
> Oh well, the thing is I'm pretty sure I ran single lighthouse command. I'll dig into it more.

All the `node` processes have distinct PIDs (and several running for different lengths of time), so I would be very surprised by this. Whatever method used to invoke might be calling node more times than you think and/or failing to cleanup or wait for the previous.

> I'm building an app that monitors the lighthouse scores. So if I'm right I'd better use google API for this purpose, am I right? :)

I don't know the specifics of your app and if it meets the terms of the API but if you're just trying to gather results of sites you own for use by you and your team, the API key limits should support your capacity AFAIK.
