### ISSUE TITLE
Enable share/copy/export buttons in main report

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1166]
The buttons are already in the report but we should also move their functionality to the core report. That way chrome extension and cli users can get the benefits.

We can use handlebars to conditionally load the script tags based on the context. Right now, DevTools is the only one that should leave them out.

**Comment by ebidel** [comment]
This was done.

**Comment by dandv** [comment]
The Export option is gone from 2.0.0. Was this intended (#2338)?

![image](https://cloud.githubusercontent.com/assets/33569/26609957/6a84028c-4559-11e7-802e-02cfe2a347d7.png)

**Comment by ebidel** [comment]
Yes. https://github.com/GoogleChrome/lighthouse/issues/2338 is tracking bringing back the button for 2.0.
