### ISSUE TITLE
lighthouse-export-run.js silent failure

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#11678]
I'm running ` yarn test-devtools` but with extra logging. 

I'm seeing this:

```
 IN: http://127.0.0.1:8000/devtools/lighthouse/lighthouse-export-run.js\n
OUT: Content-Type: text/plain\n
OUT: Tests that exporting works.\n
OUT: \n
OUT: ++++++++ testExportHtml\n
OUT: TEST ENDED IN ERROR: TypeError: Cannot read property 'get' of undefined\n
OUT:     at Object.get REPORT_JAVASCRIPT [as REPORT_JAVASCRIPT] (http://localhost:8000/inspector-sources/third_party/lighthouse/report-assets/report-generator.js:29:28)\n
OUT:     at Function.generateReportHtml (http://localhost:8000/inspector-sources/third_party/lighthouse/report-assets/report-generator.js:79:50)\n
OUT:     at LighthouseReportUIFeatures.getReportHtml (http://localhost:8000/inspector-sources/lighthouse/LighthouseReportRenderer.js:148:39)\n
OUT:     at LighthouseReportUIFeatures.onDropDownMenuClick (http://localhost:8000/inspector-sources/third_party/lighthouse/report-assets/report.js:3111:30)\n
OUT:     at testExportHtml (http://127.0.0.1:8000/devtools/lighthouse/lighthouse-export-run.js:27:58)\n
OUT:     at http://127.0.0.1:8000/devtools/lighthouse/lighthouse-export-run.js:51:9\n
OUT: \n
OUT: #EOF\n
OUT: #EOF\n
ERR: #EOF\n
```

Though interestingly, i'm not seeing this test failing at the end. (as of the runtime error was swallowed)

This is likely related to #11628 though I think we may need a solution prior to doing ESM.

**Comment by connorjclark** [comment]
The export feature creates a standalone html file. Do we really want it to use esm?

**Comment by Realistman** [comment]
> I'm running ` yarn test-devtools` but with extra logging.
> 
> I'm seeing this:
> 
> ```
>  IN: http://127.0.0.1:8000/devtools/lighthouse/lighthouse-export-run.js\n
> OUT: Content-Type: text/plain\n
> OUT: Tests that exporting works.\n
> OUT: \n
> OUT: ++++++++ testExportHtml\n
> OUT: TEST ENDED IN ERROR: TypeError: Cannot read property 'get' of undefined\n
> OUT:     at Object.get REPORT_JAVASCRIPT [as REPORT_JAVASCRIPT] (http://localhost:8000/inspector-sources/third_party/lighthouse/report-assets/report-generator.js:29:28)\n
> OUT:     at Function.generateReportHtml (http://localhost:8000/inspector-sources/third_party/lighthouse/report-assets/report-generator.js:79:50)\n
> OUT:     at LighthouseReportUIFeatures.getReportHtml (http://localhost:8000/inspector-sources/lighthouse/LighthouseReportRenderer.js:148:39)\n
> OUT:     at LighthouseReportUIFeatures.onDropDownMenuClick (http://localhost:8000/inspector-sources/third_party/lighthouse/report-assets/report.js:3111:30)\n
> OUT:     at testExportHtml (http://127.0.0.1:8000/devtools/lighthouse/lighthouse-export-run.js:27:58)\n
> OUT:     at http://127.0.0.1:8000/devtools/lighthouse/lighthouse-export-run.js:51:9\n
> OUT: \n
> OUT: #EOF\n
> OUT: #EOF\n
> ERR: #EOF\n
> ```
> 
> Though interestingly, i'm not seeing this test failing at the end. (as of the runtime error was swallowed)
> 
> This is likely related to #11628 though I think we may need a solution prior to doing ESM.

**Comment by paulirish** [comment]
This was caused by having a stale checkout of devtools frontend within `.tmp`. Our current setup doesn't update it. #11414
