### ISSUE TITLE
Unable to run lhci command

### ISSUE THREAD

**Issue by waniparag** [GoogleChrome/lighthouse#11675]
Hi I have tried installing lhci using the following command

npm install @lhci/cli (version .6) as mentioned in the documentation.

When i try to run the lhci autorun command for eg : C:\lighthouse\lighthouse-ci>lhci autorun it gives me a error everytime. it used to work in the past but i am not able to run it now, I have tried to add path to environment variables,restarted my machine few times but no luck. Can you please guide why this is happening @patrickhulce ?
![lhcierror](https://user-images.githubusercontent.com/53806666/99328948-3a84f500-28d1-11eb-8de8-fc395010d13a.png)

**Comment by patrickhulce** [comment]
Filing at https://github.com/GoogleChrome/lighthouse-ci/issues/493 is already sufficient.
