### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by acohenOT** [GoogleChrome/lighthouse#11682]
#### Provide the steps to reproduce
1. Run LH on https://file360demo.otxlab.com/File360Web/
2. Examine report 
[file360demo.otxlab.com-20201118T114642.zip](https://github.com/GoogleChrome/lighthouse/files/5561457/file360demo.otxlab.com-20201118T114642.zip)
  

#### What is the current behavior?
For Performance opportunities, displays error *Cannot read property 'length' of undefined*
![image](https://user-images.githubusercontent.com/34688558/99560291-b8a9d000-2993-11eb-92b6-94690af367ba.png)

#### What is the expected behavior?
No error. Shows the estimated savings.

#### Environment Information
* Affected Channels: Chrome 86 (stable) and Chrome beta 87 
* Lighthouse version: 6.4.0
* Chrome version: Version 87.0.4280.63 (Official Build) beta (64-bit) 
* Node.js version:
* Operating System: Windows 10 x64 20H2

**Related issues**

**Comment by connorjclark** [comment]
Can't repro with master or 6.4 `npx -p lighthouse@6.4.0 lighthouse https://file360demo.otxlab.com/File360Web --view`

Team: We really need the stack to accompany errors. error.message just isn't enough ...

**Comment by brendankenny** [comment]
from the sentry logs, looks like this was fixed by the `line === undefined` in https://github.com/GoogleChrome/lighthouse/pull/10449

**Comment by paulirish** [comment]
we're 90% confident this was fixed by #10449 which shipped in LH 6.5.0  

sorry this broke on you and please let us know if you still run into this in LH 6.5.0, which is currently in Chrome 89 devtools.
