### ISSUE TITLE
mod_pagespeed lazy loaded images not recognized

### ISSUE THREAD

**Issue by Cruiser13** [GoogleChrome/lighthouse#11686]
#### Provide the steps to reproduce
1. Run LH on https://pringuin.de
 
#### What is the current behavior?
Lighthouse gives me the opportunity to "defer offscreen images" which would save up to 18 seconds.

#### What is the expected behavior?
We're actually deferring our images using mod_pagespeed module by apache. Using my browser I can see source code like this on our site for the exactly same images Pagespeed Insights does complain about (in this case about image.png.pagespeed.ce.BPup_jOUJ2.png):
`<img data-pagespeed-lazy-src="/path/image.png.pagespeed.ce.BPup_jOUJ2.png" alt="" title="" src="/pagespeed_static/1.JiBnMqyl6S.gif" onload="pagespeed.lazyLoadImages.loadIfVisibleAndMaybeBeacon(this);" onerror="this.onerror=null;pagespeed.lazyLoadImages.loadIfVisibleAndMaybeBeacon(this);"/> `

Lighthouse should recognize that these images are lazyloaded.

#### Environment Information
* Affected Channels: Pagespeed Inisghts, DevTools
* Lighthouse version: 6.4.0
* Chrome version: 87.0.4280.66 (Offizieller Build) (64-Bit) (cohort: 87_66_Win)
* Operating System: Windows 10

**Related issues**
In case this is something to be fixed in mod_pagespeed: https://github.com/apache/incubator-pagespeed-mod/issues/2051

**Comment by patrickhulce** [comment]
Thanks for filing @Cruiser13! 

This appears to be a bug in mod_pagespeed and I've commented over there https://github.com/apache/incubator-pagespeed-mod/issues/2051#issuecomment-730557285.
