### ISSUE TITLE
Different result from CLI and chrome extension

### ISSUE THREAD

**Issue by akhilsingla123** [GoogleChrome/lighthouse#11687]
Hi,

OS : MAC OS 10.14.6
Node version : v14.1.0
lighthouse : 6.4.1
lighthouse chrome extension : 100.0.0.0

Currently we are seeing different results when running lighthouse as:
a) chrome extension
b) Programmatically and CLI

Issue:

When executed below command through terminal/programmatically , getting performance **score less then 20**

lighthouse https://www.acko.com/lp/amazon --only-categories=performance --emulated-form-factor=desktop 

When try to achieve same through chrome extension, getting performance **score more than 80**.
a) Open chrome (Version 86.0.4240.193) 
b) Opne https://www.acko.com/lp/amazon
c) Open Dev tools and run lighthouse

Using config:

**config_desktop.js**

module.exports = {
    extends: 'lighthouse:default',
    settings: {
        onlyCategories: ['performance'],
        emulatedFormFactor : 'desktop'
    },
  };

**lighthouse:**
const { lhr } = await lighthouse(url, {
        port: new URL(browser.wsEndpoint()).port,
        output: "json",
        logLevel: "info",
      }, config_desktop);

**Comment by patrickhulce** [comment]
Thanks for filing @akhilsingla123!

If you want to match DevTools desktop, then you need to match all of [DevTools configuration](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/lr-desktop-config.js).
