### ISSUE TITLE
Difference in LCP measurements in web-vitals library and Lighthouse (No throttling)

### ISSUE THREAD

**Issue by AnchalGupta3** [GoogleChrome/lighthouse#11699]
I ran the LH on https://perf.oyorooms.com/

<img width="1440" alt="Screenshot 2020-11-23 at 3 19 56 PM" src="https://user-images.githubusercontent.com/70004243/99949136-8f78ad80-2da0-11eb-990e-a515699a37ca.png">
<img width="1440" alt="Screenshot 2020-11-23 at 3 20 16 PM" src="https://user-images.githubusercontent.com/70004243/99949159-98697f00-2da0-11eb-90ae-b55aaed5ee07.png">

I had implemented the web-vitals library in the website and ran lighthouse from dev tools. As shown in the screenshots, for the same run, web-vitals library is reporting LCP at 4.2s, whereas Lighthouse is reporting LCP at 7.9s. Could you please tell me, why am I getting different results in the same run?

**Comment by patrickhulce** [comment]
Thanks for filing @AnchalGupta3!

> Could you please tell me, why am I getting different results in the same run?

Of course! See [FAQs](https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me).

**Comment by AnchalGupta3** [comment]
<img width="702" alt="Screenshot 2020-11-24 at 2 15 22 PM" src="https://user-images.githubusercontent.com/70004243/100070244-b3e78f00-2e5f-11eb-961d-bf15b2077e24.png">

The LCP image is getting painted in 4s but the LCP is getting reported at 8s with applied throttling. Why is this happening?

**Comment by AnchalGupta3** [comment]
<img width="868" alt="Screenshot 2020-11-24 at 2 30 18 PM" src="https://user-images.githubusercontent.com/70004243/100072014-b945d900-2e61-11eb-9fcd-db7d907bd0d7.png">

My LCP image is getting painted around 4s, but LCP is reported at 7-8s. Why is this happening with applied throttling?

**Comment by patrickhulce** [comment]
LCP isn't the first paint time of an image, it's roughly equivalent to onload. Also note in Chrome versions earlier than 88, if the element is removed and readded to the DOM the earlier time will be invalidated.

See [LCP explainer](https://github.com/WICG/largest-contentful-paint) for more.
