### ISSUE TITLE
Significant LCP discrepancy between Chrome Dev Tools and WebPageTest

### ISSUE THREAD

**Issue by CraigBusfield** [GoogleChrome/lighthouse#11706]
Hi,

Just wanted some clarification on something I've spotted, not sure if there's a logical explanation for it or if I'm simply losing my mind 😂 

Running https://www.gaborshoes.co.uk/homepage-ssr-runtime-updated.html through Lighthouse via Dev Tools on Chrome 87.0.4280.67 and also Chrome Canary (Version 89.0.4335.0) gives an LCP of **~1.3s**.

However, running the same page through Lighthouse via WebPageTest consistently gives an LCP of **~3.6s** for my server of choice (e.g. https://www.webpagetest.org/lighthouse.php?test=201124_DiP3_ace5fcbc2b7ea3ed9c12a1833df24e6a&run=1). Page Speed Insights often shows **~3.7s** for LCP when testing.

Of course, there's a difference due to network latency and other factors and I expect that to be reflected in the LCP metric but what I'm struggling to understand is that when I look at the Performance timelines, the Chrome ones credit the LCP at exactly the time the LCP element is first fully visible on screen, yet the WPT timeline credits it over 2 seconds later - I've tried to show this in the screenshots below:

## From Dev Tools
Screenshot showing LCP element fully visible from ~650ms, LCP recorded as 631.0 ms

![Screenshot 2020-11-24 at 16 58 31](https://user-images.githubusercontent.com/5079679/100126847-60347000-2e76-11eb-8668-2f3c677323f0.png)

## From WebPageTest
Screenshot showing LCP element fully visible from ~1330ms, LCP recorded as 3571.8 ms

![Screenshot 2020-11-24 at 16 56 36](https://user-images.githubusercontent.com/5079679/100126980-8a862d80-2e76-11eb-90c1-8c7fbff7d691.png)

I'm not aware of the element being removed from the DOM and re-added at any point, which I initially assumed might be the issue. Not sure if it helps or makes a difference but this page is (or at least should be!) AMP-valid and was generated via the PHP AMP Optimizer.

Any advice on this would be massively appreciated, as I'm not sure how to improve this metric any further at the minute, and its send me a little crazy 😄 

P.S. I have attached the respective timelines here in case they are of any use: [perf_timelines.zip](https://github.com/GoogleChrome/lighthouse/files/5591522/perf_timelines.zip)

**Comment by patrickhulce** [comment]
Thanks for filing @CraigBusfield!

I can't reproduce what you're talking about in *stable* Chrome, but I know exactly what the issue is when comparing Canary Chrome DevTools with WebPageTest.

> I'm not aware of the element being removed from the DOM and re-added at any point, which I initially assumed might be the issue.

I think this exactly the case and has been a common unexpected problem with many framework SSR hydration implementations.

In Chrome 88, Largest Contentful Paint was updated to no longer invalidate the timing when an element is removed. In Chrome stable I see LCP at a hydration point while in Chrome canary I see LCP on the first render of your LCP element. Your WebPageTest examples were being run with Chrome 87 which does not have this change.

Hope this helps!

**Comment by CraigBusfield** [comment]
Thanks @patrickhulce, that's great news! Thanks for the explanation that makes sense, I guess we'll just wait it out until January, but good to know that there's nothing else we need to do here 👍
