### ISSUE TITLE
Use new `captureBeyondViewport` param for full page screenshot

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11708]
https://chromium-review.googlesource.com/c/chromium/src/+/2470876

Might be better than the current workaround (emulate a really tall screen). Need to wait for this to land in stable (M89, ~March 2).

**Comment by patrickhulce** [comment]
This is amazing 🎉

**Comment by dylanb** [comment]
I cannot get that parameter to work, anyone had more success https://bugs.chromium.org/p/chromium/issues/detail?id=1198576

**Comment by connorjclark** [comment]
Did setting the clip parameters work?

**Comment by dylanb** [comment]
yes, biggest problem is pages that have scrollable content where the `documentElement.scrollHeight` (same as the layoutMetrics) is not accurate

Case in point https://broken--deque-workshop.netlify.app/

**Comment by dylanb** [comment]
Update: some pages, like nytimes.com are causing problems - see the ticket for details

**Comment by connorjclark** [comment]
This doesn't seem to work, and it seems like even if it did there's nothing in the backend that would wait for newly-visible resources to load like we do, so let's close.
