### ISSUE TITLE
[Audit] Warn if a page uses both async and defer on script tags

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#11714]
It appears that 11.43% of pages in HTTPArchive leverage both `async` and `defer` on `<script>` tags, despite this potentially being an [anti-pattern](https://twitter.com/rick_viscomi/status/1331735033481207809). There may be value in us digging into the performance implications of using both attributes more deeply - this might inform whether we explore a Lighthouse audit for these cases (i.e "just use one").

cc @paulirish @patrickhulce @connorjclark as you may be interested.

![image](https://user-images.githubusercontent.com/110953/100290148-7baf8180-2f2f-11eb-81b1-c1ff74d5febd.png)

With thanks to @rviscomi for his HTTPArchive analysis that provided the above insight and Harry for [prompting](https://twitter.com/rick_viscomi/status/1331735033481207809) this discussion.

**Comment by rviscomi** [comment]
Here's the list of top culprits and the query to generate it: (warning: 638.8 GB)

```sql
SELECT
  APPROX_TOP_COUNT(REGEXP_EXTRACT(script, r'src=[\'"]?([^\s\'"\?]+)'), 10) AS src
FROM (
  SELECT
    page,
    script,
    REGEXP_CONTAINS(script, r'(?i)\basync\b') AS async,
    REGEXP_CONTAINS(script, r'(?i)\bdefer\b') AS defer
  FROM
    `httparchive.almanac.summary_response_bodies`
  LEFT JOIN
    UNNEST(REGEXP_EXTRACT_ALL(body, r'(?i)(<script[^>]*>)')) AS script
  WHERE
    date = '2020-08-01' AND
    client = 'mobile' AND
    firstHtml)
WHERE
  async AND defer
```



src | count|
|-|----|
|https://www.google.com/recaptcha/api.js | 133241 |  
| https://stats.wp.com/e-202034.js | 73105 |  
| https://stats.wp.com/e-202033.js | 71468 |  
| https://stats.wp.com/e-202032.js | 65874 |  
| //stats.wp.com/w.js | 47383 |  
| https://apis.google.com/js/platform.js | 45308 |  
| https://maps.googleapis.com/maps/api/js | 25235 |  
| //assets.pinterest.com/js/pinit.js | 20811 |  
| null | 16458 |  
| https://stats.wp.com/e-202031.js | 16135

**Comment by connorjclark** [comment]
> `null`

hmmm wonder if this is a lazy loading technique ( `<script data-src="...">` then something sets `src` later in page load) or trying to async&defer an inline script (huh?)

**Comment by rviscomi** [comment]
Even `data-src` should be picked up by this regex. I wonder if it could be used on inline script blocks, for example:

```html
<script async defer>
function () {...}
</script>
```

**Comment by patrickhulce** [comment]
To me this always fell into the bucket of "frequently misunderstood, but doesn't really matter" :) I mean what is this really costing, like 5 bytes for an unnecessary `defer` attribute? 

If you're putting `async` on a script (whether it's in combination with `defer` or not) you should be prepared for the weaker async execution guarantees. In my experience talking with developers the misconception has been about which is the fallback for which and all they're trying to say is "do this later and I don't care when". 

Should it be mentioned in docs and removed from examples? Sure. Could I go so far as a static lint rule somewhere? I guess. But I'm not sure it meets the impact bar for Lighthouse to tell you to go fix it (especially when many of these are going to be third-party examples).

**Comment by connorjclark** [comment]
Hi 2020 people, it's me, 2023 person

what Patrick points out rings true, the cost here is just some small number of extra bytes in the HTML. the developer probably doesn't have a rock-solid knowledge on what defer and async do, but their intent is probably matched regardless.

If someone has additional insight that would indeed suggest this is a performance win, please comment and we can re-open.
