### ISSUE TITLE
The measured LCP is significantly higher as we can see it on the film stripe

### ISSUE THREAD

**Issue by nagyt234** [GoogleChrome/lighthouse#11712]
The LCP measured by lighthouse is significantly higher as we can see it on the film stripe and what our experience shows.

Generally our speed scores at Google's Page Speed Insight is not extremely good, because of the LCP measured by lighthouse. It should be below 2.5 seconds. Let's  see an example, one of our page:

[https://www.diet-health.info/es/recetas/ingredientes/in/wl9405-grano-de-trigo](https://www.diet-health.info/es/recetas/ingredientes/in/wl9405-grano-de-trigo)

The loading of the page seems to be fast, even on my old Samsung S4 mini mobile. The full Page appears in much less then 2 seconds. But if we are analyzing the page in Google's Page Speed Insight, we get always an LCP about 4 seconds:

[https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.diet-health.info%2Fes%2Frecetas%2Fingredientes%2Fin%2Fwl9405-grano-de-trigo](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.diet-health.info%2Fes%2Frecetas%2Fingredientes%2Fin%2Fwl9405-grano-de-trigo)

The general scoring is quite good, it is varying between 84 and 88, however it could be better if LCP would not be measured as about 4 seconds. However it can be seen on the lighthouse film stripe, that the page is totally rendered between the 2 first frame. It is not stated, what is the resolution of this film stripe, but I'm assuming 1 frame pro seconds.

![PageSppeInsight](https://user-images.githubusercontent.com/1257088/100260493-bd4d2600-2f49-11eb-9a97-5bf8f0333e91.png)

I tried the same test with the lighthouse in my Chrome browser, with the same result, but there it is possible to see a film stripe with higher resolution pressing "View Trace", which shows, that the page is rendered totally in about 1.4 seconds:

![LightHouseInChrome](https://user-images.githubusercontent.com/1257088/100260632-ec639780-2f49-11eb-9c78-155576410e8d.png)

I do not understand this big difference between our real experience, the film stripes and the measured value of LCP.

**Comment by patrickhulce** [comment]
Thanks for filing @nagyt234! You're in luck there's an [FAQ on this very topic](https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me) :)
