### ISSUE TITLE
Lighthouse always hangs on debugger statements

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#11725]
#### Provide the steps to reproduce
1. Run LH on http://melodic-class.glitch.me/debugger.html
  
#### What is the current behavior?

Lighthouse hangs and crashes with our friend PROTOCOL__TIMEOUT

#### What is the expected behavior?

Lighthouse completes the run successfully.

We send [`Debugger.setSkipAllPauses`](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setSkipAllPauses) with [`skip: true`](https://github.com/GoogleChrome/lighthouse/blob/5c5de46ffce484f969ea5df8d71bce26dbc27ed6/lighthouse-core/gather/driver.js#L921), but that doesn't seem to work anymore. We should work around this while the Chromium side is investigated.

#### Environment Information
* Affected Channels: All 😱 
* Lighthouse version: 6.4.1

**Related issues**
#6512

**Comment by mattzeunert** [comment]
Was this ever reported to the Chrome bug tracker? The current fix works fine if there's an occasional debugger statement, but if there's a lot of them the page never loads.

`setSkipAllPauses` seems to work sometimes, haven't been able to find a good simple repro yet.

**Comment by patrickhulce** [comment]
It was not reported in a crbug, though we probably should :)

If you end up getting a repro that doesn't work with LH today I'm happy to take a look.

**Comment by patrickhulce** [comment]
ah turns out there already is one! https://bugs.chromium.org/p/chromium/issues/detail?id=990945&q=setSkipAllPauses&can=2

it's navigation related, so that gives us a clue as to how we can workaround it 👍 

repro script for the curious

```js
const puppeteer = require('puppeteer')

;(async () => {
  const browser = await puppeteer.launch({headless: false})
  const page = await browser.newPage()
  const session = await page.target().createCDPSession()
  await session.send('Debugger.enable')
  await session.send('Debugger.setSkipAllPauses', {skip: true})
  await page.goto('http://melodic-class.glitch.me/debugger.html')
  await new Promise(r => setTimeout(r, 10000))
  await browser.close()
})()
```

**Comment by mattzeunert** [comment]
I think there are still bugs that aren't related to navigation. Take [this page](http://mattzeunert.surge.sh/debugger.html) as an example: 

```
<!DOCTYPE html>
<html>
  <body>
    <script type="text/javascript">
    for (var i=0;i<100000;i++) {
      debugger
    }
    document.write("<h1>Loaded</h1>")
    </script>
  </body>
</html>
```

(I think people do this kind of stuff as an anti-automation measure, Lighthouse finishes with NO_FCP.)

Running `lighthouse http://mattzeunert.surge.sh/debugger.html --verbose --view` shows a lot of debugger pauses:

```
  <= event:verbose Debugger.resumed {} +0ms
  <= event:verbose Debugger.paused {"callFrames":[{"callFrameId":"7890160225556676681.4.0","functionName":"","functionLocation":{"scriptId":"14","lineNumb +0ms
  method => browser:verbose Debugger.resume  +0ms
  method <= browser OK:verbose Debugger.resume {} +1ms
```

Maybe it's because its an inline script? And `setSkipAllPauses` is only set a little bit after the document is loaded?

**Comment by patrickhulce** [comment]
Lighthouse doesn't `setSkipAllPauses` *after* the document is loaded, which is the problem here. I think we should be able to issue `Debugger.setSkipAllPauses` on every navigation to resolve the example you just gave.
