### ISSUE TITLE
Accessibility audit error on color contrast step

### ISSUE THREAD

**Issue by benNek** [GoogleChrome/lighthouse#11721]
Axe tool is able to correctly find color contrast errors without errors

#### Provide the steps to reproduce
1. Run LH accessibility audit on https://www.kayak.com/Cheap-New-York-Car-Rentals.15830.cars.ksp and it does not calculate overall score properly because of error happening

#### What is the current behavior?
Error happens on finding color contrast issues
![image](https://user-images.githubusercontent.com/10724694/100370775-73c70e80-300f-11eb-8ca3-d98d77fdab38.png)

#### What is the expected behavior?
Accessibility score is being calculated properly without the errors

#### Environment Information
* Affected Channels: All of them (CLI, Node, DevTools)
* Lighthouse version: 6.4.1
* Chrome version: 87.0.4280.67 (happens on CLI and canary too)
* Node.js version: v12.15.0
* Operating System: macOS Catalina

**Related issues**
It only happens on mobile audit, desktop works fine. Tried to debug from webpage side and it happens on sidenav (document.querySelector('[class$=-nav-container]')) when there are too many icons/SVGs. Seems very cryptic, as removing random two of the icons seem to fix the problem.

Is it possible to find logs of those errors? I coulnd't find any

**Comment by patrickhulce** [comment]
Thanks for filing @benNek!

I'm not able to reproduce axe providing color contrast results on the mobile webpage.

![image](https://user-images.githubusercontent.com/2301202/100639329-a49e9080-32fa-11eb-9c65-f23eeb7b41ec.png)

Would you be willing to share this URL with the [axe-core project](https://github.com/dequelabs/axe-core/issues/new) for them to fix?

**Comment by benNek** [comment]
Sure thing @patrickhulce -> https://github.com/dequelabs/axe-core/issues/2674

**Comment by jason-r2r** [comment]
I am having the same issue on https://www.rome2rio.com/s/Mumbai/Delhi (run via web.dev):
![image](https://user-images.githubusercontent.com/37677849/101421494-7ea36c80-3948-11eb-91a7-bff3ed1334bf.png)

When running locally I can consistently reproduce the issue and I notice if I remove a `overflow-x: scroll` style attribute from two sections (Things to do, Places to stay) then the error goes away and I get this result (run locally from Chrome):
![image](https://user-images.githubusercontent.com/37677849/101421592-bad6cd00-3948-11eb-98d6-0f9deb10aa20.png)

**Comment by patrickhulce** [comment]
@jason-r2r that appears to be a different axe issue. Filed https://github.com/dequelabs/axe-core/issues/2681 with that information.

**Comment by connorjclark** [comment]
this will be fixing in v7

dupe #10644
