### ISSUE TITLE
Lighthouse doesn't work when it is running from an undocked separate Dev Tools window

### ISSUE THREAD

**Issue by vladimir-marek** [GoogleChrome/lighthouse#11722]
#### Provide the steps to reproduce
1. Open Developer Tools
2. Open "three dots" item in the top nav
3. Select Dock side = Undock into separate window
4. Make Dev Tools window full screen
5. Run LH on https://www.google.com/
  

#### What is the current behavior?
* Lighthouse shows this error message 
"There were issues affecting this run of Lighthouse:
There may be stored data affecting loading performance in this location: IndexedDB. Audit this page in an incognito window to prevent those resources from affecting your scores.
Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)"
* All collected metrics shown an error, example:
"First Contentful Paint Error! Required traces gatherer did not run."

#### What is the expected behavior?
Lighthouse shows generated report with real performance data.

#### Reproducibility note
When Dev Tool's "Dock Side" setting is set to any of the three remaining options (Dock to left, Dock to bottom, Dock to right), Lighthouse works like a charm.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: N/A
* Chrome version: 87.0.4280.66 (Official Build) (64-bit) (cohort: 87_66_Win)
* Node.js version: N/A
* Operating System: Windows 10 OS Version 1909 (Build 18363.1198)

**Related issues**

**Comment by connorjclark** [comment]
Is the devtools window full screen and hiding the page being audited's window the entire run? maybe #9650

**Comment by vladimir-marek** [comment]
Yes, I reproduced it ONLY with the dev tools window full screen. Not reproducible if Dev Tools is in a separate window which is not full screen. I updated the steps to reproduce.

**Comment by patrickhulce** [comment]
Thanks very much for filing @vladimir-marek! As @connorjclark mentioned, this is a known issue for which Lighthouse can do little other than explain that the page cannot be hidden while Lighthouse runs (Chromium limitation). https://github.com/GoogleChrome/lighthouse/pull/11579, #9650 and https://github.com/GoogleChrome/lighthouse/issues/4139 capture this quite well already, so we'll go ahead and close this as a duplicate.

Your helpful additional details will be automatically linked in those issues :)
