### ISSUE TITLE
Update yargs to >4.0.0 to remediate y18n Prototype Pollution high severity vulnerability

### ISSUE THREAD

**Issue by arielperez82** [GoogleChrome/lighthouse#11720]
See: https://snyk.io/test/npm/lighthouse/6.4.1

**Feature request summary**
Need to update yargs dependency to at least 4.0.0 to resolve the y18n < 5.0.5 [Prototype Pollution](https://app.snyk.io/vuln/SNYK-JS-Y18N-1021887) high severity vulnerabilty.

**What is the motivation or use case for changing this?**
Closing a security gap

**How is this beneficial to Lighthouse?**

My company's automatic scanning tools are blocking lighthouse from being installed as a dependency because of this vulnerability. I'm certain it's the same at many other companies.

**Comment by neharica** [comment]
Please update the angular V9 LTS packages also accordingly with the updated yargs version in dependencies. Example: @angular/compiler-cli - 9.1.12 (which is latest) has yargs dependency of v4 which has security vulnerability.

**Comment by patrickhulce** [comment]
@neharica this project is not affiliated with that package, please file an issue with angular if you'd like any movement on that.
