### ISSUE TITLE
LCP fluctuates wildly on slower machines with simulated throttling

### ISSUE THREAD

**Issue by kelvin-d-zhu** [GoogleChrome/lighthouse#11737]
#### Provide the steps to reproduce
1. Run LH on https://template-standard-bailard-demo.squarespace.com in Docker container from a Kubernetes pod.

#### What is the current behavior?
The LCP value is jumping from 6 seconds to 15 seconds. My estimation is 20% of the time Lighthouse output ~6s timing and 80% of the time 15s. It is consistently on either end of around 6s or 15s and not in between.

[Here](https://gist.github.com/kelvin-d-zhu/263b36a96eb36b8d2d80d08964abb2c7) is the lighthouse report json with wrong LCP value of 6 seconds.
[Here](https://gist.github.com/kelvin-d-zhu/45eed3aa13e9a4c0e8b83182c73d97ab) is the lighthouse report json with expected LCP value of 15 seconds.

#### What is the expected behavior?
Lighthouse should always output consistent LCP value and this value is expected to be close to 15 seconds.

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 6.4.1
* Chrome version: Chrome/84.0.4143.7
* Node.js version: v14.15.1
* Operating System: Debian GNU/Linux 9 (stretch) (Running in a docker container from a Kubernetes pod)

**Related issues**

**More information**
- This fluctuation of LCP value only happens in simulated throttling and not reproducible when using devtools throttling. 
- Testing shows this occurs only when running in machines that produces benchmarkIndex value of less than 1450 in LH report. When benchmarkIndex value is more than 1450, LCP is constant about 15s and no big LCP fluctuation is observed.
- This issue is not reproducible on my local machine.
- I also have pumped [pauseAfterNetworkQuietMs and networkQuietThresholdMs](https://gist.github.com/kelvin-d-zhu/263b36a96eb36b8d2d80d08964abb2c7#file-lhr-json-L4051) to 40seconds in settings, but it does not make a difference. The report also shows the request for LCP image is [completed](https://gist.github.com/kelvin-d-zhu/263b36a96eb36b8d2d80d08964abb2c7#file-lhr-json-L1048).
- The LCP image request happens after DOMContentLoaded event. It does not appear to be an issue if LCP image is not the last request.

**Comment by patrickhulce** [comment]
Thanks for filing @kelvin-d-zhu! This is a known issue captured in part by https://github.com/GoogleChrome/lighthouse/issues/11460#issuecomment-695211106 and the [variability documentation](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md). 

There is very little that can be done here on the Lighthouse side in simulated throttling when Chromium groups paints differently and using applied throttling is the appropriate workaround. We'll update our variability docs to reflect the fact that simulated throttling exacerbates browser nondeterminism variance with the introduction of LCP as a metric (those docs and analyses were written before LCP existed).

**Comment by kelvin-d-zhu** [comment]
@patrickhulce thanks for the quick response and confirming this is related to browser nondeterminism variance!
