### ISSUE TITLE
Regression: `Runtime.evaluate` errors on polyfilled Promises

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1173]
Getting `Protocol error (Runtime.evaluate): Result of the evaluation is not a promise` for all `driver.evaluateAsync` calls on test angular site like e.g. https://material2-app.firebaseapp.com/

#1037 handles this case (and we've tested it pretty thoroughly in the past), so need to investigate how this regressed.

**Comment by patrickhulce** [comment]
:(

**Comment by patrickhulce** [comment]
Found it. Looks like however Angular2 polyfills promise goes above and beyond what the smokehouse promise polyfill does and removing the `new __nativePromise` layer during feedback broke it for angular but not smokehouse. In a nutshell, there doesn't seem to be a way around explicitly constructing a new promise since returning a polyfilled Promise within a native Promise `.then` doesn't *always* work, just when you're testing ;)

**Comment by brendankenny** [comment]
looks like the problem was that zone.js not only overwrites the global `Promise`, it *also* overwrites `Promise.prototype.then` on the *original* global.

So even though we were using our `window.__nativePromise`, we were getting the polyfilled `window.__nativePromise.prototype.then`, which returns a non-native promise :(

**Comment by brendankenny** [comment]
fixed in #1178

**Comment by paulirish** [comment]
some history from #11190  ... 

 > Lighthouse backstory:
 > Zone aggressively polyfills promises including rewriting Promise.prototype.then which caused
 > problems for our evaluateAsync code where we rely on a `Promise` to work.
 > We serve this file in dbw_tester.html to make sure evaluateAsync, etc all works great
 > Serving this file via node_modules was a pain so we've replaced it with our own.
 > @see https://github.com/GoogleChrome/lighthouse/issues/1173
 > @see https://github.com/GoogleChrome/lighthouse/pull/1178
 > We were serving zone.js@0.7.3 from node_modules but that introduced complexity, so it was
 > vendored into a third_party folder.
 > @see https://github.com/GoogleChrome/lighthouse/pull/9672
 > Later we decided to stop using this fancy file altogether so we can just ignore drama from both
 > third_party placement and node_modules imports.
 > @see https://github.com/GoogleChrome/lighthouse/pull/11043
 > This promise polyfill isn't as aggressive as zone as it doesn't patch every interface
 > that returns a promise (https://github.com/angular/zone.js/blob/v0.7.3/dist/zone.js#L1589-L1611)
 > But we think that's ok.


but 11190 was a pain to land and the earlier annoyances calmed down.
