### ISSUE TITLE
"Avoid an excessive DOM size" returned even when none of the three listed criterea are met

### ISSUE THREAD

**Issue by JacobDB** [GoogleChrome/lighthouse#11746]
#### Provide the steps to reproduce
1. Run LH on https://www.oswegolandparkdistrict.org/programs-events/run-oswegoland/
2. Expand "Performance" section of Lighthouse report
3. Observe warning "Avoid an excessive DOM size"
  

#### What is the current behavior?

On a page with 1,160 elements, depth of 25 nodes, and maximum child elements of 51, I get a warning "Avoid an excessive DOM size"

#### What is the expected behavior?

> Lighthouse flags pages with DOM trees that:
> 
> - Have more than 1,500 nodes total.
> - Have a depth greater than 32 nodes.
> - Have a parent node with more than 60 child nodes.
> 
> https://web.dev/dom-size/#how-the-lighthouse-dom-size-audit-fails

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 6.4.0
* Chrome version: Version 87.0.4280.66 (Official Build) (64-bit)
* Node.js version: N/A
* Operating System: Windows 10 Pro (64-bit) 20H2 (OS Build 19042.662)

**Comment by patrickhulce** [comment]
Thanks for filing @JacobDB! The docs are out of date on this topic. Anything with over ~800 DOM nodes will start the be surfaced by this audit and will cross from the orange warning color to the red failure color at around ~1400 DOM nodes.

We'll update the docs.

**Comment by JacobDB** [comment]
Ah, that explains it! Thanks for the clarification.
