### ISSUE TITLE
Remove h2 'push' suggestion from audit description

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11741]
https://github.com/GoogleChrome/lighthouse/blob/378a31f8117d20c852562514612c80ea12892c54/lighthouse-core%2Faudits%2Fdobetterweb%2Fuses-http2.js#L31

The general consensus is that h2 push was a mistake. At best, it is very hard to get right, and easy to accidentally result in worse performance.

the web.dev article doesn't even mention push.

**Comment by brendankenny** [comment]
Good catch! Don't think it even needs discussion, it should definitely go :)
