### ISSUE TITLE
Skip HTTPS tests when running a 127.0.0.1 or localhost or .local URL

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#1175]
The following tests could be skipped for local URLs:

- Site is on HTTPS 
- Site redirects HTTP traffic to HTTPS
- Security: Site is on HTTPS

I'm also not sure if the HTTP/2 test makes sense for localhost, can you test H/2 on local origin?

**Comment by wardpeet** [comment]
Might be ok to do this because we do this as well for localhost.
```
if (!parsedURL.protocol.includes('https') && parsedURL.hostname !== 'localhost') {
      log.warn('Lighthouse', 'The URL provided should be on HTTPS');
      log.warn('Lighthouse', 'Performance stats will be skewed redirecting from HTTP to HTTPS.');
}
```

**Comment by XhmikosR** [comment]
I'd be interested in this. One note though: this should skip the tests if `127.0.0.1` is being used too.

**Comment by patrickhulce** [comment]
I'd be interested in hearing more about the workflow of using lighthouse on internal/local servers. Is it generally production builds on a staging or development server for the developer to feel out performance iteratively? Is it for CI where a failure can't just be ignored and should fail the build?

Interested to hear what options would typically be set as I'd prefer to make config changes more visible/easier instead of one-off `if` checks for various hostnames :)

**Comment by gauntface** [comment]
The reason I raised this issue initially was that gut checking changes on Lighthouse via the extension is somewhat skewed by the fact that there are results I can't pass on localhost / aren't worth making work on localhost.

I have been using it for CI of a "production version" of my site (Write up here: https://medium.com/@gauntface/the-old-rebuild-chestnut-4210e389647#.xpj3zm3za) The tests actually filter out some audit results because the scores fail / have invalid scores (i.e. a tti of -1). So for CI. this is easy enough to side-step the troubling audits.

**Comment by patrickhulce** [comment]
Great writeup thanks @gauntface! Do you happen to have the lighthouseWrapper you described available anywhere? Maybe we'd be able to address some of the issues you're facing.

And interesting, so basically looking for automatically unchecking the "Network connections are secure" option in the extension?

**Comment by gauntface** [comment]
Sure, the wrapper is here: https://github.com/gauntface/gf-site/blob/v3/test/utils/lighthouse-wrapper.js

For the most part it's just wrapping launching, using and killing chrome.

**Comment by ebidel** [comment]
In theory, dev and prod are as similar as developers can make it. In practice, that's a lot harder for the 3 reasons Matt points out and others like lack of resource bundling, no server push, service worker not caching things when on localhost (IIRC, sw-toolbox does this to prevent frustrating developers on `localhost`).

Doing one-offs for `localhost` does seem like it could get messy though. I can imagine folks testing against a local server and being confused on why new audits are failing in prod/staging.

One idea: we could still include these audits when testing against `localhost` but grey out the results in the report or have an obvious `debugString` that explains said audits will never pass when testing locally.

TBH, we should probably have a big warning at the top of the report saying "Looks like you're testing on a local development server. Performance numbers may not be as expected."

Showing more upfront info on the user's setup: https://github.com/GoogleChrome/lighthouse/pull/1485, https://github.com/GoogleChrome/lighthouse/issues/568, https://github.com/GoogleChrome/lighthouse/issues/836, https://github.com/GoogleChrome/lighthouse/pull/784

**Comment by gauntface** [comment]
+1 @ebidel's comments. Greying out would make much more sense than a fail. It also could be used as an incentive to run on the live site (which would have the performance differences as well).

**Comment by gkalpak** [comment]
So, assuming one wants to run lighthouse against a local build without HTTPS support and get results that are as close as possible to production, what is the recommended way/work-around? Currently, we would lose several points due to the `redirects-http` check and are working around it by [setting the weight to 0] (which feels more hacky than necessary 😟).

Any suggestions/insights?

[1]: https://github.com/angular/angular/blob/1fc0d055651f94cf60419ab102b96801ca9bec9e/aio/scripts/test-pwa-score.js#L57-L71

**Comment by ebidel** [comment]
@gkalpak when https://github.com/GoogleChrome/lighthouse/pull/2539 lands you'll be able to easily skip audits by writing a custom config. Extend the LH config to run all the audits, but filter out the ones you don't care about. 

config-dev.js:

```javascript
module.exports = {
  extends: 'lighthouse:default',
  settings: {
    skipAudits: ['redirects-http']
  }
};
```
Use it:
```
lighthouse --config-path=config-dev.js https://example.com
```

Would that work for dev?

cc @patrickhulce

**Comment by gkalpak** [comment]
Sounds great! Thx, @ebidel 
(fyi @filipesilva)

**Comment by stixaw** [comment]
Is there a document that shows all the options for the skipAudits option in a config file?
