### ISSUE TITLE
"document.write()" line number is 0-indexed instead of 1-indexed

### ISSUE THREAD

**Issue by ryoAccount** [GoogleChrome/lighthouse#11761]
#### Provide the steps to reproduce
1. Run LH on https://www.freepik.com/
  

#### What is the current behavior?
The line of code where "document.write()" appears will be 0.

![image98](https://user-images.githubusercontent.com/20512477/101105745-b8efcf80-3611-11eb-8e04-ba6ceb52c461.png)

Does this indicate that "document.write()" is not being used?
Or is the line of code wrong?

#### What is the expected behavior?
If you are not using "document.write()", I don't think it should be output to the audit.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: v6.5.0
* Chrome version:  86.0.4240.198
* Node.js version: v12.18.4
* Operating System: Windows10

**Related issues**
NA

**Comment by connorjclark** [comment]
It's zero indexed (oops), and that JS is presumably minified, so somewhere on the first line must be a `document.write`.

**Comment by ryoAccount** [comment]
Thank you for your reply!!

Looking at the comments in the source code, I thought the location pointed to a line of code, but is the array index correct?

https://github.com/GoogleChrome/lighthouse/blob/ba75d8d4a5f8b1fd3ccb4f1824a083bb019e7e67/lighthouse-core/lib/i18n/i18n.js#L75-L76

**Comment by patrickhulce** [comment]
It is pointing to a line of code @ryoAccount 👍  We're saying that the line it's pointing to is the *first* line and that the source that tells Lighthouse what line it's on is reporting the lines on a 0-index basis, which we'll want to fix.
