### ISSUE TITLE
Google Light House not capturing the Data for the Same web application and had different behavior to capture the Data in Google report

### ISSUE THREAD

**Issue by sreesatty1** [GoogleChrome/lighthouse#11780]
#### Provide the steps to reproduce
1. Run LH on <affected url> This is an internal Customer application where the URL cant be shared. I'll upload the report for reference.
  

#### What is the current behavior? The current behaviour in the application report page is as follows:
**
Another flow for the same application(Launch URL--> Login--> Click) is working fine where as the flow where Launch URL --> Login and select product is failing with below symptoms.
1. There were issues affecting this run of Lighthouse:
2. Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)
3. The entire report is filled with ? with no valid data in Google Light House Report stating "Required traces gatherer did not run."
**

#### What is the expected behavior?

1. Expected behaviour is to see the Google light house report with analyzed data about the page.

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**
[product selection_Error.zip](https://github.com/GoogleChrome/lighthouse/files/5655491/product.selection_Error.zip)
[Click on product master listing under data maintenance.zip](https://github.com/GoogleChrome/lighthouse/files/5655499/Click.on.product.master.listing.under.data.maintenance.zip)

**Comment by connorjclark** [comment]
https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md
