### ISSUE TITLE
offline-ready.html getting warn-not-offline-capable installability error

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#11800]
offline-ready.html has a service worker which should allow it to pass the new functional test.
but we're seeing it fail: https://github.com/GoogleChrome/lighthouse/pull/11799

background on warn-not-offline-capable: https://bugs.chromium.org/p/chromium/issues/detail?id=965802#c46 and 
https://github.com/GoogleChrome/lighthouse/issues/10515#issuecomment-693013839

Need a Chrome that's => 89.0.4351.0

I could reproduce this locally with ToT chromium and the `#check-offline-capability` chrome flag.

![image](https://user-images.githubusercontent.com/39191/101691858-29d52400-3a24-11eb-8d3f-668dc028e3bb.png)

**Comment by paulirish** [comment]
I've packaged up a little repro of our offline-ready page. It does repro:

[offline-page-falsepositive-demo.zip](https://github.com/GoogleChrome/lighthouse/files/5668938/offline-page-falsepositive-demo.zip)

(i don't think the icon error is related, but i kept it anyhow)

![image](https://user-images.githubusercontent.com/39191/101692869-acaaae80-3a25-11eb-9375-3a1a6682ef4f.png)

**Comment by paulirish** [comment]
Filed upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1157242

**Comment by paulirish** [comment]
A CL to fix is prepared, but not yet landed: https://bugs.chromium.org/p/chromium/issues/detail?id=1157242#c6

**Comment by brendankenny** [comment]
Reminder to revisit this after the 7.0 hustle: from the description of https://chromium-review.googlesource.com/c/chromium/src/+/2583674, seems like some of our `start_url` issues in #10237 might reappear from this change?

We should verify if it's a problem or if the Chrome offline check is able to be more sophisticated than our old one (e.g. both the page and SW are taken offline) and avoid these problems.

**Comment by paulirish** [comment]
> A CL to fix is prepared, but not yet landed: [bugs.chromium.org/p/chromium/issues/detail?id=1157242#c6](https://bugs.chromium.org/p/chromium/issues/detail?id=1157242#c6)

It's landed now. I think we have a smoketest result or two that'll change now.
