### ISSUE TITLE
Full page screenshot crashes Chrome on certain URLs

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#11814]
#### Provide the steps to reproduce
1. Run LH on https://www.theverge.com

#### What is the current behavior?

Chrome crashes when taking the full page screenshot.

#### What is the expected behavior?

Chrome doesn't crash.

#### Other Notes

I'm not sure how widespread this sort of failure is (all my other typical test URLs seem fine), but probably worth kicking off a GCP run on a larger list *without* failure retries to see how many are affected if we need a workaround before v7.  

I spent a bit of time investigating and here's what I found.

I originally suspected the unlimited size change so I tried reducing the max height param.
4000px tall Chrome crashes
2000px tall Chrome crashes
1000px tall *renderer* crashes
800px tall *works*

Clearly not a file size issue because the normal screenshot is 640px tall at 2.5x the DPR. The fact that there's a difference in size between Chrome entirely crashing and just the renderer crashing is interesting though. I reported all the crashes through `chrome://crashes` so hopefully Chromium can work on the issue from their side as well 🤷 

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: master
* Chrome version: canary *and* stable :/
* Node.js version: 12.18.1
* Operating System: macOS Catalina

**Comment by paulirish** [comment]
oof.

are these GCP runs headless or w/ xvfb?

**Comment by connorjclark** [comment]
`xvfb-run`

**Comment by patrickhulce** [comment]
> are these GCP runs headless or w/ xvfb?

This was just on my local mac, but I was suggesting we try to do a GCP run to see if we can repro on more sites too. I imagine we'd want to prioritize xvfb-run as that's how more less technical users knowledgable of workarounds will experience things.

**Comment by paulirish** [comment]
Might be relevant; https://github.com/GoogleChrome/lighthouse/pull/11536#issuecomment-730632423

**Comment by patrickhulce** [comment]
On a much broader list of URLs using our GCP scripts I could not reproduce this full page screenshot fatal error on any of them (though 4% of runs did fail with PROTOCOL_TIMEOUT, alarming result compared to my previous inability to repro PROTOCOL_TIMEOUT on GCP, but maybe encouraging for resuming our potential investigation there?)

I suspect whatever was triggering this locally for me is similar to the mac GPU quirkiness @paulirish and @connorjclark experienced in #11536. Either way I don't think it's worth blocking the release over as I don't have much evidence to say this is a widespread issue that justifies a workaround.

Any differing opinions feel free to comment and reopen :)

**Comment by patrickhulce** [comment]
Wait hang on, I take it back.

**Comment by ikifar2012** [comment]
Still ab issue

**Comment by patrickhulce** [comment]
@ikifar2012 on https://theverge.com? Do you have reproduction details? I'm no longer able to repro.

**Comment by ikifar2012** [comment]
I was just trying to get a full page screenshot on CBC.ca and my browser crashed

**Comment by ikifar2012** [comment]
Interestingly I cannot recreate it with the verge
