### ISSUE TITLE
Incorrect 'low resolution' image warning

### ISSUE THREAD

**Issue by adityapatadia** [GoogleChrome/lighthouse#11838]
When I analyse the page: https://web.smsdevel.cz/ I get low resolution image warning. The reality is that image is perfectly sized and DPR and everything is already taken into account.

I have already checked https://github.com/GoogleChrome/lighthouse/issues/11630 and https://github.com/GoogleChrome/lighthouse/issues/10802 but it seems this is a real bug.

**Comment by patrickhulce** [comment]
Thanks for filing @adityapatadia!

This is an interesting case the team will have to discuss how to handle. The audit is correct that the resolution of this image is low **for its displayed size**. While the DPR is taken into account in requesting the right `src`, the displayed size is not set which results in scaling the image to be 3x as large in each dimension as it should be instead. 

The fix we would want the developer of this page to take though is not further increasing the resolution of this image, that would just make everything worse. The correct fix is actually using `srcset` correctly and setting explicit dimensions on the image without changing the image's resolution.

Perhaps we need to merge in the existing audit for image lacking dimensions which catches this? Maybe just a docs update?

**Comment by adityapatadia** [comment]
The page uses javascript library made by our company which always requests correct image size during run-time. This means that the size loaded is actually correct and bigger one is not needed at all. May be your suggestion about modifying audit for images which lack dimensions is a good idea.

As per my knowledge the recommendation should not be shown because if developer increases size, it will certainly make it worse.

**Comment by patrickhulce** [comment]
> The page uses javascript library made by our company which always requests correct image size during run-time. This means that the size loaded is actually correct and bigger one is not needed at all.

Just to be clear the library requests the correct size **if the image were sized appropriately, but it isn't**. 

![image](https://user-images.githubusercontent.com/2301202/102378949-f6e2e100-3f8b-11eb-8952-072a9f4f8ef7.png)

Notice how the width is *supposed* to be the width of the screen (360px) but instead the image is just enormous and gets clipped offscreen instead. This is not the correct behavior.

The audit is definitely flagging a mistake, it's just that the documentation is pointing developers in the wrong direction on how to fix it, which we definitely want to address 👍

**Comment by adityapatadia** [comment]
Yes, the library finds correct width and puts `w=360` but also appends `dpr=3.0` parameter due to screen being high DPR. You are also correct that the developer should put width on image itself to prevent it from overflowing. I will leave to your team to decide how to get this fixed.

**Comment by patrickhulce** [comment]
After discussion we've decided to ignore images in the low resolution DPR audit that extend beyond the viewport.
