### ISSUE TITLE
problem with lighthouse ssl to postgres - hopefully better description using Custom SSL Certificate for Database Connection

### ISSUE THREAD

**Issue by bradyma1** [GoogleChrome/lighthouse#11831]
I am attempting to covert a non ssl existing and working lighthouse-ci server running on a docker instance connecting to a postgres database to an ssl configuration.  When using the configuration updates shown in the example   Custom SSL Certificate for Database Connection (https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#custom-ssl-certificate-for-database-connection), I am getting the following error. 
lhci server --config=./lighthouse.js
Unexpected token

Steps - 
npm install @lhci/server @lhci/cli
lighthouserc.js  from example with my parameters filled in - 
const fs = require('fs');

module.exports = {
  ci: {
    server: {
      storage: {
        storageMethod: 'sql',
        sqlDialect: 'postgres',
        sqlConnectionSsl: true,
        sqlConnectionUrl: postgres://posrgres@1.2.3.4/lhci,
        sqlDialectOptions: {
          ssl: {
            ca: fs.readFileSync('./certs/ca.crt', 'utf8'),
            key: fs.readFileSync('./certs/key.key', 'utf8'),
            cert: fs.readFileSync('./certs/client.crt', 'utf8'),
          },
        },
      },
    },
  },
};
docker image build -t lhci .
docker container run --publish 9001:9001 --mount 'lhci-data,target=/data' --detach lhci

Expected - 
docker instance comes up
Actual -
lhci server --config=./lighthouse.js
Unexpected token

Observations -
 I noticed that modules.exports has  navigate-to-project.js and setup.js.  I am guessing I need to pull these down as part of the custom code.  Sorry missed this.  My next requst for a little more detail on where this might go.  Thanks for your help and patience.

**Comment by patrickhulce** [comment]
Please do not file duplicate issues in the core repo about this @bradyma1. https://github.com/GoogleChrome/lighthouse-ci/discussions/510 reflects the best place to seek further help from the community.
