### ISSUE TITLE
Lighthouse CLI command gives error "Unable to open X display" although running headless

### ISSUE THREAD

**Issue by alex4200** [GoogleChrome/lighthouse#11857]
#### Provide the steps to reproduce

Command line:

` lighthouse google.com --chrome-flags=”--headless”`

## Expected behavior

I was expecting that `lighthouse` runs a test on the specified webpage `google.com` <just for testing purposes>

#### What is the current behavior?

It looks like `lighthouse` is trying to start the browser, but it finally ends with an error message. Complete output:

```
$ lighthouse google.com --chrome-flags=”--headless”
? We're constantly trying to improve Lighthouse and its reliability.
  Learn more: https://github.com/GoogleChrome/lighthouse/blob/master/docs/error-reporting.md 
  May we anonymously report runtime exceptions to improve the tool over time?  No
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +509ms
  <repeating output ommitted>
  ChromeLauncher Waiting for browser................................................................................................. +501ms
  ChromeLauncher Waiting for browser................................................................................................... +503ms
  ChromeLauncher Waiting for browser..................................................................................................... +502ms
  ChromeLauncher Waiting for browser....................................................................................................... +503ms
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:42673 +1ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.JPyVQIm/chrome-err.log +1ms
  ChromeLauncher:error [562:562:1218/170736.943695:ERROR:browser_main_loop.cc(1434)] Unable to open X display.
  ChromeLauncher:error  +0ms
Unable to connect to Chrome
```

#### What is the expected behavior?

I was expecting that `lighthouse` runs a test on the specified webpage `google.com` <just for testing purposes>

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 7.0.0
* Chrome version: 87.0.4280.88
* Node.js version: v12.20.0
* Operating System: Ubuntu 20.04.1

I am remotely working on this machine, so I cannot open a X-display (which is the reason I want to run a headless version of `lighthouse`).

**Comment by patrickhulce** [comment]
Thanks for filing @alex4200! 

I can't reproduce this issue. If you ran the command that's in this issue verbatim, I would expect the angled quotes to be causing this.

``` 
$ docker run -it --entrypoint /bin/bash patrickhulce/lhci-client
$ npm install -g lighthouse@7.0.0
$ lighthouse http://www.example.com --chrome-flags="--headless --no-sandbox"
# completes successfully
```

**Comment by alex4200** [comment]
Thanks @patrickhulce, with your example it did work in fact. Yes, maybe it was the angles quotes. Not sure where I got them from!
