### ISSUE TITLE
Late prefetch resource hints get added to lcp graph

### ISSUE THREAD

**Issue by LukasAuerMstage** [GoogleChrome/lighthouse#11856]
#### Provide the steps to reproduce
1. Run LH on https://www.cbd-vital.at/
  
This page inserts some prefetch resource hints for bundles which might be needed for later navigations. (For example: checkout-cart-index.js) These hints get added with some delay by a js script so that they dont compete with other, more necessary, resources. While debugging the LCP score i found that these resources get added to the lcp graph on some occasions, but in my opinion they cannot be render blocking for the lcp element, as the start time of the bundles is past the lcp timestamp.

While researching these entries i found that the reportet endTime for these NetworkNodes is negative while the start time is still a valid timestamp, which actually looks like a potential bug to me. Example:

URL: https://www.cbd-vital.at/static/frontend/Vitrasan/cbd/de_DE/bundles/checkout-index-index.js 
startTime: 185410134082.00003 
endTime: -1000000 
paintTs (LCP): 185407907391

In this case the startTime is past the LCP paint timestamp but the the node still gets included in both the optimistic as well as the pessimistic graph.

I think normal scripts with a negative endTime and a startTime past the timestamp would get sortet out in `lighthouse-core/computed/metrics/lantern-first-contentful-paint.js` as they would get added to the `definitelyNotRenderBlockingScriptUrls` array. But these urls do net get added due to the fact that while collection the possibly render blocking urls LH explicitly checks for resources with type script (in `lighthouse-core/computed/metrics/lantern-metric.js` function `getScriptUrls`). These resource hints however do not get collected as their type is `other`.

The second condition that might should apply for resources like this is also in `lighthouse-core/computed/metrics/lantern-first-contentful-paint.js` but in this case the negative endTime comes into play:

`// Exclude all nodes that ended after paintTs (except for the main document which we always consider necessary)`
`if (node.endTime > paintTs && !node.isMainDocument()) return false;`

Judging from the comment i would assume that if scripts that finish after the timestamp should get excluded, scripts that even started after the timestamp should be excluded as well.

#### What is the current behavior?
Prefetch resource hints, which have a startTime beyond the LCP timestamp, get added to both the optimistic as well as the pessimistic LCP graph.

#### What is the expected behavior?
These resources should probably be excluded from the graph, as they are not render blocking for the LCP element.

#### Environment Information
* Affected Channels: Node, probably other channels as well
* Lighthouse version: latest
* Chrome version: 87.0.4280.88 (as well as the latest canary build: 89.0.4359.0)
* Node.js version: v12.16.1
* Operating System: Windows 10

Maybe i am missing something here and this is, in fact, expected behaviour but from my point of view it looked weird that low priority prefetch hints which get added past the LCP timestamp are present in the graph.

Note: I cannot reproduce this behaviour on every run and that might be because the prefetch hints get added too late for LH to capture them at all.

**Comment by patrickhulce** [comment]
Thanks for filing @LukasAuerMstage and great job poking around the code to find the root of this issue! Amazing find! :)

**Comment by LukasAuerMstage** [comment]
@patrickhulce Thanks for the quick feedback! I would suggest the following simple change:
https://github.com/LukasAuerMstage/lighthouse/commit/e70c27a691a9ce81df3b3c5bb85d2bfbcc606db7

The additional check if the startTime is past the paintTs would actually be more strict than the existing condition (endTime) and therefore i don't think that it would have any negative impact on other cases but it will still catch network nodes that have a negative endTime. WDYT?

**Comment by patrickhulce** [comment]
Sounds great, want to put up the PR for it? :)

**Comment by LukasAuerMstage** [comment]
Sure :)
