### ISSUE TITLE
lighthouse CLI gives "Unexpected token" error on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by alex4200** [GoogleChrome/lighthouse#11854]
#### Provide the steps to reproduce

1. I installed lighthouse on Ubuntu Linux 20.04.1 as follows:

```
 sudo npm install -g lighthouse
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/lighthouse -> /usr/local/lib/node_modules/lighthouse/lighthouse-cli/index.js
/usr/local/bin/chrome-debug -> /usr/local/lib/node_modules/lighthouse/lighthouse-core/scripts/manual-chrome-launcher.js
npm WARN notsup Unsupported engine for lighthouse@7.0.0: wanted: {"node":">=12.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: lighthouse@7.0.0
```

2. Running `lighthouse google.com` results in the following error message:
/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:68
  _traceCategories = Driver.traceCategories;
                   ^

```
SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/runner.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

#### What is the current behavior?

I get an error message

#### What is the expected behavior?

Command runs without error message.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: Unclear
* Chrome version: 87.0.4280.66 
* Node.js version: v10.19.0
* Operating System: Ubuntu 20.04.1

**Related issues**

**Comment by pdr** [comment]
I think this could be your issue:
`npm WARN notsup Unsupported engine for lighthouse@7.0.0: wanted: {"node":">=12.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})`

**Comment by pdr** [comment]
I ran into the same problem and upgrading to node 12 worked.

**Comment by alex4200** [comment]
Thanks, upgrading to node 12 also fixed the issue on my side. 
Upgrade guide for Ubuntu: [HERE](https://computingforgeeks.com/how-to-install-nodejs-on-ubuntu-debian-linux-mint/)

**Comment by patrickhulce** [comment]
@pdr is right the v7 release just upgraded the minimum node version to 12 👍
