### ISSUE TITLE
Lighthouse doesn't pick the right image from srcset (probably)

### ISSUE THREAD

**Issue by VeeK727** [GoogleChrome/lighthouse#11855]
#### Provide the steps to reproduce
1. Run LH on www.notaloss.com
  
#### What is the current behavior?
I'm getting unusually long times on LCP which seems to be an image. Here's the code I used
```
// LCP is 7.7s. Image loaded size 194kb (larger image)
<img src="img/banners/hero-banner.png"
	srcset="img/banners/hero-banner-0.5x.png 500w, img/banners/hero-banner.png 1000w"
	sizes="(max-width: 600px) 500px, 1000px"
	alt="Preview of Reports" id="hero-banner">
```
Alternatively
```
// LCP is 5.3s. Image loaded size 63kb
<img src="img/banners/hero-banner-0.5x.png"
	alt="Preview of Reports" id="hero-banner">
```
I've ran a few other tests and I'm thinking Lighthouse is not picking the smaller image on mobile test.

#### What is the expected behavior?
On mobile test, the smaller image should be selected.

#### Environment Information
* Affected Channels: DevTools
* Chrome version: 87.0.4280.88
* Operating System: Windows 10

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/11251

**Comment by patrickhulce** [comment]
Thanks for filing @VeeK727! The larger image will definitely get selected by the browser on mobile (2.625 DPR * 324px wide = 850px). We're considering suggesting to Chrome to only ever download 2x images on mobile (see #11518), but even that would still end up selecting the larger image based on the two existing breakpoints. To disregard pixel density you could use `<picture>` and differentiate the source on width-alone if that was what you were trying to achieve?

This behavior is going to happen for the vast majority of mobile users today though, so Lighthouse is accurate here.

**Comment by VeeK727** [comment]
`picture` tag did work out the way I wanted. Thanks.
