### ISSUE TITLE
tap-targets causes CSP violation by injecting style sheet

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/lighthouse#11862]
#### Provide the steps to reproduce
1. Run LH 7 on https://almanac.httparchive.org/en/2020/

#### What is the current behavior?

Note that it [gets 93% on Best Practices audit due to Content Security Policy issue](https://www.webpagetest.org/lighthouse.php?test=201220_DiGY_f16b0100aac4fae06afc5f67957f8584&run=3#best-practices):
![CSP issue affecting Best Practices Audit](https://user-images.githubusercontent.com/10931297/102724310-9266af80-4306-11eb-9c72-137daff1c0b8.png)

#### What is the expected behavior?

Running Lighthouse in Chrome (v6.4.0) does indeed show a CSP violation but Lighthouse v6.4.0 doesn't complain about this while 7.0.0 does:

![CSP violation in console](https://user-images.githubusercontent.com/10931297/102724364-f4271980-4306-11eb-99b8-b9bbedea995f.png)

Digging into this more, the inline style is inserted by Lighthouse itself:

https://github.com/GoogleChrome/lighthouse/blob/2cbbd289be33a586462ed248179df7d7b692ca53/lighthouse-core/gather/gatherers/seo/tap-targets.js#L160-L177

Bit unfair to complain about a problem you are creating 🙂

#### Environment Information
* Affected Channels: CLI (as used by WebPageTest) only for now as 7.0.0 has not rolled out much yet
* Lighthouse version: 7.0.0
* Chrome version: N/A - running Lighthouse outside of Chrome as 7.0.0 not release yet.
* Node.js version: N/A
* Operating System: N/A

**Related issues**

**Comment by patrickhulce** [comment]
Aye, thanks @bazzadp :)

**Comment by connorjclark** [comment]
I ran Lighthouse for https://almanac.httparchive.org/en/2020/, here's what I found.

[index](http://lh-issue-runner-11862.surge.sh)
✅ [html](http://lh-issue-runner-11862.surge.sh/lighthouse@7.0.0.report.html) [json](http://lh-issue-runner-11862.surge.sh/lighthouse@7.0.0.report.json) [output](http://lh-issue-runner-11862.surge.sh/lighthouse@7.0.0.output.txt) lighthouse@&#8203;7.0.0
✅ [html](http://lh-issue-runner-11862.surge.sh/lighthouse@6.5.0.report.html) [json](http://lh-issue-runner-11862.surge.sh/lighthouse@6.5.0.report.json) [output](http://lh-issue-runner-11862.surge.sh/lighthouse@6.5.0.output.txt) lighthouse@&#8203;6.5.0
✅ [html](http://lh-issue-runner-11862.surge.sh/lighthouse@5.6.0.report.html) [json](http://lh-issue-runner-11862.surge.sh/lighthouse@5.6.0.report.json) [output](http://lh-issue-runner-11862.surge.sh/lighthouse@5.6.0.output.txt) lighthouse@&#8203;5.6.0
✅ [json](http://lh-issue-runner-11862.surge.sh/PSI.report.json) [output](http://lh-issue-runner-11862.surge.sh/PSI.output.txt) PSI
✅ [html](http://lh-issue-runner-11862.surge.sh/lighthouse@master-96eda6.report.html) [json](http://lh-issue-runner-11862.surge.sh/lighthouse@master-96eda6.report.json) [output](http://lh-issue-runner-11862.surge.sh/lighthouse@master-96eda6.output.txt) lighthouse@&#8203;master-96eda6

**Comment by connorjclark** [comment]
I ran Lighthouse for https://almanac.httparchive.org/en/2020/, here's what I found.

[index](http://lh-issue-runner-11862.surge.sh)
✅ [html](http://lh-issue-runner-11862.surge.sh/lighthouse@7.0.0.report.html) [json](http://lh-issue-runner-11862.surge.sh/lighthouse@7.0.0.report.json) [output](http://lh-issue-runner-11862.surge.sh/lighthouse@7.0.0.output.txt) lighthouse@&#8203;7.0.0
✅ [html](http://lh-issue-runner-11862.surge.sh/lighthouse@6.5.0.report.html) [json](http://lh-issue-runner-11862.surge.sh/lighthouse@6.5.0.report.json) [output](http://lh-issue-runner-11862.surge.sh/lighthouse@6.5.0.output.txt) lighthouse@&#8203;6.5.0
✅ [html](http://lh-issue-runner-11862.surge.sh/lighthouse@5.6.0.report.html) [json](http://lh-issue-runner-11862.surge.sh/lighthouse@5.6.0.report.json) [output](http://lh-issue-runner-11862.surge.sh/lighthouse@5.6.0.output.txt) lighthouse@&#8203;5.6.0
✅ [json](http://lh-issue-runner-11862.surge.sh/PSI.report.json) [output](http://lh-issue-runner-11862.surge.sh/PSI.output.txt) PSI
✅ [html](http://lh-issue-runner-11862.surge.sh/lighthouse@master-96eda6.report.html) [json](http://lh-issue-runner-11862.surge.sh/lighthouse@master-96eda6.report.json) [output](http://lh-issue-runner-11862.surge.sh/lighthouse@master-96eda6.output.txt) lighthouse@&#8203;master-96eda6

**Comment by bazzadp** [comment]
Interesting. So it didn't penalise the Best Practices score in 5.6.0, but did in 6.5.0 and 7.0.0.

We run 6.2.0 as part of our GitHub integration and never showed up as an issue there (wasn't even shown as a warning), and still doesn't as still using 6.2.0, but just waiting with baited breath for this to start failing our pipeline.

So guess something changed between 6.2.0 and 6.5.0. I'm guessing #11409 which went live in 6.5.0.

But either way it's still a problem Lighthouse is introducing - and then complaining about!

**Comment by brendankenny** [comment]
> So guess something changed between 6.2.0 and 6.5.0. I'm guessing #11409 which went live in 6.5.0.

Exactly, that audit didn't exist before then :)

There are two problems here:
- `inspector-issues` including issues in Lighthouse-injected code
- CSP blocking Lighthouse-injected code

we could fix the first one by filtering `inspector-issues`, but the second point means that some audits aren't behaving as they should. e.g. `tap-targets` in this example thinks it has completed correctly (the CSP violation doesn't throw when the stylesheet is added to the page), but the filtering of `fixed`/`sticky` elements didn't occur. Other gatherers could be more severely affected.

**Comment by connorjclark** [comment]
We might be able to ignore this particular error in the `inspector-issues` audit, by filtering issues with `url: ''`, which is anything (I think?) that we call with Runtime.Evaluate.

Otherwise, maybe there is a way to do what tap-targets does w/o creating a style element?

**Comment by alystair** [comment]
Managed to snag a screenshot of the console error before its wiped, as the error in full doesn't appear in the Lighthouse results. This only happens when 'SEO' is selected. Appears in Canary/Beta - haven't tested stable.

![image](https://user-images.githubusercontent.com/159109/112219271-23497180-8bfb-11eb-84ea-ea09c670b8f5.png)

OCR'd (ish) minus own internal hashes:
```Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'report-sample' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-TyNUDnhSZIj6eZZqS6qqchxBN4+zTRUU+TkPeIxxT1I='), or a nonce ('nonce-...') is required to enable inline execution.```

**Comment by connorjclark** [comment]
FYI there's an option to preserve console logs: 
![image](https://user-images.githubusercontent.com/4071474/112228165-db2c4e00-8bfe-11eb-89eb-8e7e13bbabec.png)

it's off by default

**Comment by brendankenny** [comment]
One option for avoiding the issue in `tap-targets` in particular is replacing our gatherer with the new UKM instrumentation: https://chromium-review.googlesource.com/c/chromium/src/+/2643673

Maybe DevTools is interested in using this information as well? That would make it easy to get it through the protocol in that case.

**Comment by longtimedeveloper** [comment]
![2021-05-21_15-54-36](https://user-images.githubusercontent.com/79998776/119191711-0390c700-ba4d-11eb-8bcd-92f7866ad1fb.png)

My website uses CSP.  Lighthouse reports 93 best practices instead of 100 because Lighthouse is attempting to dynamically insert styles or JS into my site which is violating my CSP policy.  See the above image console error.

<meta http-equiv="Content-Security-Policy" content="default-src 'self';">

When I turn off SEO for Lighthouse I get 100 for best practices.

Developers should not have to open up CPS security to enable the tooling to report properly.

Additionally, when I ship my production website to customers, they may use Lighthouse to see if they are getting the great results I promised them.  This issue spoils their expectations.

If there was a way to open the CSP policy ONLY for Lighthouse, I would do that, but don't know how to accomplish this.  Suggestions?

I hope the Chrome Team can sort this out for us.

Thank you!

Karl

**Comment by anisse** [comment]
Hi, my website is affected by this issue:

https://anisse.astier.eu

https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fanisse.astier.eu

**Comment by shaunbruno** [comment]
Thanks for adding a patch to this @paulirish  - was puzzling over this issue today (June 20, 2021)
