### ISSUE TITLE
Use native Node URL parsing after Node 7.2.1 errors resolved

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1186]
I'm getting URL parsing errors in `audits/dobetterweb/uses-http2.js` that weren't present before https://github.com/GoogleChrome/lighthouse/pull/997.

When running:

    npm run fast -- --output=html --output-path=results.html http://www.univision.com

Think it's failing on `http://5321212.fls.doubleclick.net/activityi;src=5321212;type=unvsn_un;cat=unvsn_uv;ord=7762287885264.98?`

<img width="910" alt="screen shot 2016-12-20 at 2 52 39 pm" src="https://cloud.githubusercontent.com/assets/238208/21371058/f8f13392-c6c3-11e6-92ee-9be9fa32652f.png">

**Comment by ebidel** [comment]
@wardpeet you mind investigating?

Also happening on https://www.healthcare.gov. The url that it is upset about is `https://166688199.log.optimizely.com/event?a=166688199&d=166688199&y=true&src=js&s171652904=false&s171674651=none&s171946972=gc&s172159083=direct&s2417020537=true&tsent=1482274480.426&n=https%3A%2F%2Fwww.healthcare.gov%2F&u=oeu1482274480406r0.6877701290450859&wxhr=true&time=1482274480.425&f=7763110370,8016731066,7884071307,8073890089,7980150122,7763860875,7767800396,4681340685,7162490510,7975554292,7989202617,7768580538,8072450782&g=2177170222,2435330307&cx2=95f459d8`

**Comment by Janpot** [comment]
Coincidentally I ran into this issue too a few days ago: https://github.com/nodejs/node/issues/10306
a fix is on the way but updating the tests revealed more issues: https://github.com/nodejs/node/pull/10317

**Comment by ebidel** [comment]
Thanks @Janpot. Looks like a Node issue. I'm also using 7.2.1

**Comment by wardpeet** [comment]
@ebidel I could use whatwg instead of url for node 7 until it is fixed

**Comment by wardpeet** [comment]
closing this one, fixed by #1187

**Comment by brendankenny** [comment]
I actually wanted to leave this open since we want to turn back on native node URL parsing when they fix their code. Changing the issue title to match that.

**Comment by paulirish** [comment]
k. The compliance issues that Jan pointed out earlier [have landed in `v7.4.0`](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#commits), which shipped yesterday.

Shall we add a "Compat:" comment indicating we can retire the `whatwg-url` module when < 7.4.0 is unsupported?
It will be many months, so I'd prefer that as our TODO rather than keeping this issue open. :)

**Comment by wardpeet** [comment]
good for me! :)
we might even do a  version check in the file to use url when node > 7.4

**Comment by brendankenny** [comment]
Should be obsolete by Node 8 reaching LTS
