### ISSUE TITLE
Errors in unweighted audits produce a `null` category score

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11872]
Noticed this in: https://github.com/GoogleChrome/lighthouse/pull/11871/files#diff-09cd5d246b94b3c67132390d8e55b17af0a48f52b7054f52949c61548891fd96R5539

Using `null` in this case doesn't seem necessary.

**Comment by brendankenny** [comment]
Those should be filtered out:

https://github.com/GoogleChrome/lighthouse/blob/7dba76fb0cc025df8d21472564ef0674f6794ca5/lighthouse-core/scoring.js#L25-L26

**Comment by connorjclark** [comment]
I mistakenly thought `inspector-issues` was weighted 0. It's not, it's weighted 1. Nevermind.
