### ISSUE TITLE
For mobile ，LH report LCP not mapping  with original trace？

### ISSUE THREAD

**Issue by NeilShang** [GoogleChrome/lighthouse#11880]
in original trace（performance） LCP not mapping with report
my test url is https://ofertasvtr.cl/
![image](https://user-images.githubusercontent.com/26372974/102970576-b8709780-4532-11eb-954b-cf45b45528b4.png)
and I think  original trace had already limit cpu and network，so it‘s should be same as report？

**Comment by adamraine** [comment]
This is expected behavior https://github.com/GoogleChrome/lighthouse/issues/9971
