### ISSUE TITLE
Remove usage of {{{ }}} in the html report

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1188]
In some places we use `{{{}}}` to render our own data ([example](https://github.com/GoogleChrome/lighthouse/blob/7c0d6aa1b0fd1b5d10657b1967d725741d05dd73/lighthouse-core/report/templates/report-template.html#L26)). Those are fine.

However, we should remove `{{{ }}}` in places where we render user data ([example](https://github.com/GoogleChrome/lighthouse/blob/7c0d6aa1b0fd1b5d10657b1967d725741d05dd73/lighthouse-core/report/templates/report-template.html#L90)]. Those are there to render code snippets and links in `helpText` and audit descriptions. Instead, we should create Handlebar helpers to render links and code snippets.

http://handlebarsjs.com/reference.html#base-escapeExpression

This works today if it appears in json loaded into the app:

`"helpText": "<img src=\"test.gif\" onerror=\"alert('oops')\"> Text..."`

**Comment by wardpeet** [comment]
Are you going to take this @ebidel ? :)

**Comment by ebidel** [comment]
Yea. started in on it.
