### ISSUE TITLE
LH audits fails when developer tools is on a seperate window

### ISSUE THREAD

**Issue by uzenith360** [GoogleChrome/lighthouse#11884]
#### Provide the steps to reproduce
1. Run LH on  http://todolistme.net/

#### What is the current behavior?
- Open developer tools on a seperate window and run LightHouse
- Lighthouse audit runs and returns results

#### What is the expected behavior?
- Open developer tools on a seperate window and run LightHouse
- Lighthouse audit fails and returns errors for every perfomance metric

#### Environment Information
URL: http://todolistme.net/
Fetch Time: Dec 23, 2020, 8:32 PM GMT+1
Device: Emulated Desktop
Network throttling: 40 ms TCP RTT, 10,240 Kbps throughput (Simulated)
CPU throttling: 1x slowdown (Simulated)
Channel: devtools
User agent (host): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
User agent (network): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Safari/537.36 Chrome-Lighthouse
CPU/Memory Power: 854
Axe version: 3.5.5

**Related issues**

**Comment by connorjclark** [comment]
dupe #6154
