### ISSUE TITLE
TBT appears to be incorrect (sum of blocking portions of long tasks is much lower than indicated TBT) 

### ISSUE THREAD

**Issue by bramcou** [GoogleChrome/lighthouse#11890]
**Describe the bug**
After running Lighthouse 6.4.0 (mobile device) in Chrome 87 DevTools, the indicated Total Blocking Time is 330ms. According to the documentation, the TBT should be the sum of all blocking portions of long tasks between FCP and TTI. In this example (screenshots below) there are two long tasks, one of which only one is after FCP, it takes 160ms, so 110ms blocking time, not 330ms.

I tried 10 different websites and on none of the websites I got a (somewhat) accurate match between my calculated TBT and the indicated TBT.

Furthermore, some interesting things:

1. If I run the same websites through https://web.dev/measure/ (which is on fast 3g and 4x cpu slowdown, according to the footer) the TBT figure is much more accurate with 150ms in comparison to my calculated TBT's. You can't however open the original performance trace in web.dev so it's not possible to verify that figure there. Also, according to the footer of web.dev, they're on version 6.3.0 of LH whereas Chrome is on 6.4.0

2. FCP on the lighthouse report is way off from the FCP as indicated in the Performance trace. In the screenshots attached the FCP on the lighthouse report is 1.4 seconds. In the original trace (accessed through the View Original Trace button) the FCP is somewhere around 0.5 seconds.

3. LCP is also very different between the Lighthouse report and the performance trace belonging to the report.

**To Reproduce**
1. Navigate to any website in Chrome 87, run Lighthouse in DevTools with the Mobile profile
2. Note the TBT
3. Click on "View original trace"
4. Sum the amount of blocking times of long running tasks (sum time of all long running tasks - (50 * number of long running tasks).
5. Compare the above figure with the indicated TBT.

**Expected behavior**
I'd expect the TBT and the FCP in the Lighthouse report to be the same as they are in the corresponding performance trace.

**Screenshots**
![image](https://user-images.githubusercontent.com/20993769/103143666-368f9280-471b-11eb-8c86-f0c94598aa92.png)
![image](https://user-images.githubusercontent.com/20993769/103143667-38595600-471b-11eb-811f-03686ae04e0d.png)

**Comment by benschwarz** [comment]
@bramcou, the original trace is taken from the browser during the load phase of the page.

Lighthouse's Lantern mode is a simulation that's applied _after_ the initial load. TBT doesn't line up with the trace because it is inferred from the trace + simulated throttling.

**Comment by bramcou** [comment]
Hi Ben, thanks for the explanation. Interesting that the trace doesn't actually belong to the run simulation. So does it first run the audit, doing all checks and calculating all figures and then, thereafter, throttle/cpu it back as if you're on a Moto with 25% cpu power and fast 3G?

Also, how should I read this, compared with the results from https://web.dev/measure, which consistently shows 150ms~ TBT and also states it's running the throttled version?

**Comment by benschwarz** [comment]
> So does it first run the audit, doing all checks and calculating all figures and then, thereafter, throttle/cpu it back as if you're on a Moto with 25% cpu power and fast 3G?

Yep!

> compared with the results from https://web.dev/measure, which consistently shows 150ms~ TBT and also states it's running the throttled version

Comparing local results to web.dev will mostly not be helpful as it's run on different hardware from a different location. You will not see the same metrics.

**Comment by bramcou** [comment]
Okay, thanks @benschwarz for your info. I'll close the issue of course.
