### ISSUE TITLE
Getting GatherRunner:error while running lighthouse programmatically

### ISSUE THREAD

**Issue by gbajpeyee** [GoogleChrome/lighthouse#11896]
While running the lighthouse programmatically, I am getting error "GatherRunner:error The page provided is not HTML (served as MIME type ). https://www.google.com/". I am getting same error for other urls are well.I am using lighthouse version ^6.4.1 and chrome launcher version ^0.13.4 in my package.json. Please see the code snippet below that I use to run the lighthouse.

```
async function getLighthouseResults(url) {
    try {
        const chrome = await chromeLauncher.launch({ chromeFlags: ['--headless'] });
        const options = { logLevel: 'info', output: 'html', onlyCategories: ['performance'], port: chrome.port };
        const runnerResult = await lighthouse(url, options);
        const reportHtml = runnerResult.report;
        logger.info('Report is done for', runnerResult.lhr.finalUrl);
        logger.info('Performance score was', runnerResult.lhr.categories.performance.score * 100);
        await chrome.kill();
        return reportHtml;
    } catch (error) {
        logger.error('Error encountered during lighthouse', url, error);
        return error;
    }
}

const result = getLighthouseResults('https://www.google.com/');
```

**Comment by patrickhulce** [comment]
Thanks for filing @gbajpeyee! This error means that "The page provided is not HTML" 😉 

Lighthouse can only audit true HTML pages. The fix here would be on the server-side of the pages being audited to serve HTML with the proper MIME type. (When a major site like Google sends something like this to an automated request, it's typically their bot detection page and not the actual content you were intending to audit).

**Comment by gbajpeyee** [comment]
Thanks a lot @patrickhulce for your response. Well same code worked fine for same url on other machines and CI/CD environment :)
Apparently this issue happening only in my local machine.
