### ISSUE TITLE
Warnings: Lighthouse was unable to automatically check the `font-display` value for the origin https://collegeadmission.co. Please help me for this issue fix it...

### ISSUE THREAD

**Issue by rajeshkrish** [GoogleChrome/lighthouse#11894]
Warnings: Lighthouse was unable to automatically check the `font-display` value for the origin https://collegeadmission.co. Please help me with this issue to fix it...
Already checking with...Below Given...

link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Open+Sans&display=block
link rel="preload" as="font" href="https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFVZ0bf8pkAg.woff2" type="font/woff" crossorigin="anonymous" 

@font-face {
font-family:'Open Sans';
	src: url(https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFVZ0bf8pkAg.woff2) format("woff2");
	font-display: auto;
}

![image](https://user-images.githubusercontent.com/5756147/103191588-8cbb2c00-48fb-11eb-9c8f-a59711022fbb.png)

**Comment by patrickhulce** [comment]
What would you like help with @rajeshkrish?

The warning is telling you that this is a case Lighthouse couldn't automatically check. It does not necessarily require any action on your part.
