### ISSUE TITLE
Lighthouse "Best Practice" Bug?

### ISSUE THREAD

**Issue by Sven74Muc** [GoogleChrome/lighthouse#11907]
I tested my website with https://web.dev
URL: https://dlgo.de/111

Within the "Best Practice" section Lighthouse shows an "error".

Here is the screen from Lighthouse, the website are and the source code: https://dlgo.de/lighthouse.jpg. 

As you see in the screenshot, Lighthouse is marking only the first of the 4 images with an error... However all 4 images are having same size and same resolution. I changed the jpg quality for digital.jpg several times im Photoshop.

1. Why is Lighthose marking this error?
2. Why is lighthouse marking only the first of the four images?

For me the only explanation I have is, that this could be a bug.... Hope someone can help. ;-)

**Comment by Sven74Muc** [comment]
I tested it also in Chrome. The Lighthouse report is showing the same there.

**Comment by patrickhulce** [comment]
Thanks for filing @Sven74Muc! All those links 404 for me, so I'm not sure what you're looking at, but my guess is that it's "Low resolution" audit and the reason is mostly likely that the images aren't taking into account the 2x DPR of the Lighthouse test device (i.e. using `srcset` or `picture`)
