### ISSUE TITLE
--skip-audits flag excludes full-page-screenshot

### ISSUE THREAD

**Issue by alekseykulikov** [GoogleChrome/lighthouse#11913]
#### Provide the steps to reproduce
1. Run LH on any URL
  
```bash
# all is good
lighthouse https://www.example.com/ --output=json --chrome-flags="--headless"

# excludes redirects-http and full-page-screenshot
lighthouse https://www.example.com/ --skip-audits=redirects-http --output=json --quiet --chrome-flags="--headless" 
```

#### What is the current behavior?

Lighthouse excludes `full-page-screenshot` when `--skip-audits` flag is set with different audits.

#### What is the expected behavior?

Lighthouse shouldn't exclude `full-page-screenshot`, and should only skip specified audits. 

#### Environment Information
* Affected Channels: CLI, Node
* Lighthouse version: v7.0.0

#### Related issues 
It seems related to https://github.com/GoogleChrome/lighthouse/issues/11531 when `full-page-screenshot` is not part of any category.

**Comment by alekseykulikov** [comment]
A quick fix for this issue is to add `full-page-screenshot` to the [default-config.js](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/default-config.js#L482):
```js
{id: 'full-page-screenshot', weight: 0},
```

@patrickhulce I can make a pull request if this is enough.

**Comment by patrickhulce** [comment]
Thanks @alekseykulikov we actually special case this in default-config https://github.com/GoogleChrome/lighthouse/blob/b7e24b39e236db5461ce33de14e5d62dc69bc6c9/lighthouse-core/config/config.js#L511-L517

If you're up for a change there to add the cases where *any* filtering is happening like this `skip-audits` we'd love a PR :)
