### ISSUE TITLE
Run Google Lighthouse from an AWS Lambda Function

### ISSUE THREAD

**Issue by R-Studios** [GoogleChrome/lighthouse#11912]
**Summary**
Hello. I would like to run Google Lighthouse from an AWS Lambda Function.
I'm using Serverless to deploy the Lambda Function.

Currently I'm using this package:
https://github.com/Footage-Firm/serverless-lighthouse
The package consists of a single js file that provides a runLighthouse method: https://github.com/Footage-Firm/serverless-lighthouse/blob/master/index.js

It's generating a report and returns the json in the response.
The problem is that the config is not applied.
Example: If I provide

> onlyCategories: ['performance']

as a function parameter inside the lighthouseConfig, the value in the returned report is

> onlyCategories: null

Can anyone explain why this is happening? If you managed to run Google Lighthouse from an AWS Lambda function with Serverless, please let me know.

Thanks!

**Comment by patrickhulce** [comment]
Thanks for filing @R-Studios!

> If I provide
onlyCategories: ['performance']
as a function parameter inside the lighthouseConfig, the value in the returned report is
onlyCategories: null
Can anyone explain why this is happening?

Are you doing 

```js
const config = {extends: 'lighthouse:default', onlyCategories: ['performance']}
```

or

```js
const config = {extends: 'lighthouse:default', settings: {onlyCategories: ['performance']}}
```

The latter I would expect to work while the former would never work. I can't really definitely answer questions about how to properly use the API of another wrapper project though.


> If you managed to run Google Lighthouse from an AWS Lambda function with Serverless, please let me know.

Just as an FYI sidenote, we [highly recommend you don't do this](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md#run-on-adequate-hardware) and can't really support any issues that result :)

**Comment by R-Studios** [comment]
Thank you for your quick response @patrickhulce!
I will look into this further on Friday. Can you please leave the issue open until then?

I know that what I am trying to do is not recommended. I would like to schedule performance tests in the future and
currently I don't see any other option than using a Lambda function or an on-premise server running all the time.
If you have another idea, please let me know.
Thank you.

**Comment by R-Studios** [comment]
Hi @patrickhulce!
Today I had time to look into this again.
What you mentioned, was the problem. Thank you for taking some time to look into it.
If you still have a better solution on scheduled performance tests, please let me know.
Have a nice day! 🎉
