### ISSUE TITLE
在vue项目中使用lighthouse编译报错

### ISSUE THREAD

**Issue by wenxuehai** [GoogleChrome/lighthouse#11910]
为什么我在vue项目中用编程方式使用Lighthouse，项目一直编译报错。
有人遇到过这种情况吗，求问

错误日志：
Failed to compile with 7 errors                   
error  in ./node_modules/lighthouse/lighthouse-core/lib/lh-error.js

Module parse failed: Unexpected token (121:80)
You may need an appropriate loader to handle this file type.
|     // Add additional properties to be ICU replacements in the error string.
|     // `code` is always added as `errorCode` so callers don't need to specify the code multiple times.
|     this.friendlyMessage = str_(errorDefinition.message, {errorCode: this.code, ...properties});
|     this.lhrRuntimeError = !!errorDefinition.lhrRuntimeError;
|     if (properties) Object.assign(this, properties);

 @ ./node_modules/lighthouse/lighthouse-core/gather/connections/cri.js 12:24-56
 @ ./node_modules/lighthouse/lighthouse-core/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/HelloWorld.vue
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/lighthouse/lighthouse-core/lib/network-recorder.js

Module parse failed: Unexpected token (224:6)
You may need an appropriate loader to handle this file type.
|     // Update/finish the previous network request and create a new one for the redirect.
|     const modifiedData = {
|       ...data,
|       // Copy over the initiator as well to match DevTools behavior
|       initiator: originalRequest.initiator,

 @ ./node_modules/lighthouse/lighthouse-core/computed/network-records.js 9:24-61
 @ ./node_modules/lighthouse/lighthouse-core/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/HelloWorld.vue
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/lighthouse/lighthouse-core/runner.js

Module parse failed: Unexpected token (349:8)
You may need an appropriate loader to handle this file type.
|       const auditContext = {
|         options: auditOptions,
|         ...sharedAuditContext,
|       };
|

 @ ./node_modules/lighthouse/lighthouse-core/index.js 8:15-37
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/HelloWorld.vue
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/lighthouse/lighthouse-core/lib/i18n/i18n.js

Module parse failed: Unexpected token (373:25)
You may need an appropriate loader to handle this file type.
|    * @type {Record<string, string>}
|    */
|   const mergedStrings = {...UIStrings, ...fileStrings};
|
|   /**

 @ ./node_modules/lighthouse/lighthouse-core/config/config.js 11:13-45
 @ ./node_modules/lighthouse/lighthouse-core/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/HelloWorld.vue
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/lighthouse/lighthouse-core/config/config-plugin.js

Module parse failed: Unexpected token (65:19)
You may need an appropriate loader to handle this file type.
|
|     return auditsJson.map(auditDefnJson => {
|       const {path, ...invalidRest} = auditDefnJson;
|       assertNoExcessProperties(invalidRest, pluginName, 'audit');
|

 @ ./node_modules/lighthouse/lighthouse-core/config/config.js 17:21-50
 @ ./node_modules/lighthouse/lighthouse-core/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/HelloWorld.vue
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/lighthouse/lighthouse-core/gather/driver.js

Module parse failed: Unexpected token (68:19)
You may need an appropriate loader to handle this file type.
| class Driver {
|   /** @private */
|   _traceCategories = Driver.traceCategories;
|
|   /**

 @ ./node_modules/lighthouse/lighthouse-core/index.js 69:29-58
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/HelloWorld.vue
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/lighthouse/lighthouse-core/config/budget.js

Module parse failed: Unexpected token (70:33)
You may need an appropriate loader to handle this file type.
|    */
|   static validateResourceBudget(resourceBudget) {
|     const {resourceType, budget, ...invalidRest} = resourceBudget;
|     Budget.assertNoExcessProperties(invalidRest, 'Resource Budget');
|

 @ ./node_modules/lighthouse/lighthouse-core/config/config.js 18:15-37
 @ ./node_modules/lighthouse/lighthouse-core/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/HelloWorld.vue
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by patrickhulce** [comment]
Thanks for filing @wenxuehai! You can't use Lighthouse client-side in a bundle with webpack. It's a node developer tool that you use to evaluate your client-side code once deployed on a server.

**Comment by wenxuehai** [comment]
> Thanks for filing @wenxuehai! You can't use Lighthouse client-side in a bundle with webpack. It's a node developer tool that you use to evaluate your client-side code once deployed on a server.

谢谢，问题已解决

**Comment by looking-goood** [comment]
@wardpeet

**Comment by looking-goood** [comment]
__

**Comment by looking-goood** [comment]
@patrickhulce

**Comment by looking-goood** [comment]
> @patrickhulce

**Comment by xunji0715** [comment]
if i want to use lighthouse with webpack or as a server，how to do it

**Comment by wenxuehai** [comment]
> if i want to use lighthouse with webpack or as a server，how to do it

你不能在webpack中使用lighthouse，如果想要使用，可以尝试在服务端中使用它，比如与通过node.js使用。
lighthouse 是一个 node 节点模块，我们只能在服务器当中运行它（比如可以使用 nodejs），不能在类似于 vue 等项目当中引用它。
