### ISSUE TITLE
LargestContentfulPaint - Data for .element, .rendertime and .load time

### ISSUE THREAD

**Issue by sgaurav7867** [GoogleChrome/lighthouse#11919]
Hi Team,

I am trying to debug LCP issues. 
Checking to see if there is a way to pull data for LargestContentfulPaint.element, LargestContentfulPaint.renderTime and LargestContentfulPaint.loadTime.

**Comment by paulirish** [comment]
You can see the element specifically in the "LCP Element" audit..  but we don't have the renderTime/loadTime.  While those are in the webperf api, we get our data from chrome trace events, where we don't have that data.

but the LCP event should be the same for both, so repeating in your own browser should be gathering it.

you can also add some usertiming yourself to identify these times.  all usertiming is reported in the Lighthouse result JSON.
