### ISSUE TITLE
Need Immediate attention | Not Working | Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)

### ISSUE THREAD

**Issue by pushpikasj** [GoogleChrome/lighthouse#11911]
#### Steps to reproduce
1. Run LH on <affected url>http://atsmore.com/
2. Click on the “Generate Report” (Selected Category: Performance)

#### Current behavior?

![Div1](https://user-images.githubusercontent.com/9498899/103507007-22b6ff80-4e84-11eb-96bb-e76efdc1ccd3.png)
![Div2](https://user-images.githubusercontent.com/9498899/103507013-2480c300-4e84-11eb-9ae2-fcda7df91292.png)

![Div3 Document_001](https://user-images.githubusercontent.com/9498899/103507313-e59f3d00-4e84-11eb-9232-b639e148d481.jpg)
![Div3 Document_002](https://user-images.githubusercontent.com/9498899/103507385-0cf60a00-4e85-11eb-98d7-b8ec11231db9.jpg)
![Div3 Document_003](https://user-images.githubusercontent.com/9498899/103507395-12535480-4e85-11eb-9bbc-65440f88a588.jpg)
![Div3 Document_004](https://user-images.githubusercontent.com/9498899/103507403-18e1cc00-4e85-11eb-9a80-a97429a16142.jpg)
![Div3 Document_005](https://user-images.githubusercontent.com/9498899/103510049-70cf0180-4e8a-11eb-9218-82971e0054fa.jpg)

Always Shows "There were issues affecting this run of Lighthouse:

Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)"

Expected behavior?

Lighthouse Run With No Errors

Environment Information
* Affected Channels: DevTools
* Lighthouse version: 6.4.0
* Chrome version: Google Chrome	87.0.4280.88 (Official Build) (64-bit) (cohort: Stable)
* Node.js version: ?
* Operating System: OS	Windows 10 OS Version 1909 (Build 18363.1256)

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @pushpikasj! Don't fullscreen the developer tools over the page you're auditing, instead dock them to right, bottom, or partially covering the page while it's loading. If the page you're loading is fully occluded then Chrome and the OS will not render it.

**Comment by connorjclark** [comment]
ref #9650
