### ISSUE TITLE
Largest Contentful Paint error

### ISSUE THREAD

**Issue by mevsimtente** [GoogleChrome/lighthouse#11924]
Hi I am getting this error. Wonder what could be the reason
Largest Contentful Paint error

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmevsimtente.com%2Fkategori%2Furunlerimiz&tab=desktop

erorr url https://mevsimtente.com/zemin-kat-mafsalli-tente.html

Thank you

**Comment by paulirish** [comment]
> [developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmevsimtente.com%2Fkategori%2Furunlerimiz&tab=desktop](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmevsimtente.com%2Fkategori%2Furunlerimiz&tab=desktop)


the page you're testing here is a 404. so the analysis doesnt complete. do you have the URL correct?


> erorr url [mevsimtente.com/zemin-kat-mafsalli-tente.html](https://mevsimtente.com/zemin-kat-mafsalli-tente.html)
> 

testing this one works for me and i don't see an LCP error

![image](https://user-images.githubusercontent.com/39191/113768459-b80c9e80-96d4-11eb-864c-ed9df2e1c17e.png)

g'luck!
