### ISSUE TITLE
Running lighthouse on Nodejs server: using official example: ECONNREFUSED

### ISSUE THREAD

**Issue by andreidiaconescu** [GoogleChrome/lighthouse#11927]
I have been trying to run Lighthouse programatically using the official example (from https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically), with very little change:

```
    const chrome = await chromeLauncher.launch({
      chromeFlags: ["--headless"],
    });

    // console.log("LightHouseService.runForUrl chrome.port", chrome.port);
    // const options = {
    //   logLevel: "info",
    //   output: "json",
    //   onlyCategories: ["accessibility"],
    //   port: chrome.port,
    // };
    // const runnerResult = await lighthouse(urlToAudit, options);
    // await chrome.kill();

```

Most of the code is commented out, so only the first part executes

I get the following error:
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 38985

How could i proceed ?

**Comment by doooom2018** [comment]
No, it's not like this way, wait for me and I'll show you it

في الخميس، 7 يناير 2021 5:47 م Andrei Diaconescu <notifications@github.com>
كتب:

**Comment by patrickhulce** [comment]
Thanks for filing @andreidiaconescu!

This means Chrome is crashing on startup. Try starting Chrome without any of this involved to find what's going wrong (it's usually a sandbox or missing dependency problem that can be fixed with some extra flags or `apt-get install` commands).

**Comment by JvyG** [comment]
it happens to me too, but when i remove the headless flag it works

**Comment by gengbingbing** [comment]
去掉await也会遇到相同的问题

**Comment by paulirish** [comment]
> 去掉await也会遇到相同的问题

yes, but await is required. (or switch to using `.then()`)

these are asynchronous operations
