### ISSUE TITLE
Multi-Page Reports?

### ISSUE THREAD

**Issue by InDieTasten** [GoogleChrome/lighthouse#11928]
**Summary**
Are there plans for supporting multi-page reports?
Eg. traversing links of the same domain to test an entire website, instead of individual pages?
I know it's possible programmatically, but maybe it would be helpful to have this kind of functionality available in the Lighthouse DevTools tab directly? It's quite tedious to run a report on every page manually.
A summary report of multiple pages would also be helpful I think. It would also allow for some accessibility audits regarding navigability, eg. https://www.w3.org/WAI/WCAG21/Understanding/multiple-ways.html which revolves around linking between pages.

**Comment by patrickhulce** [comment]
Thanks for filing @InDieTasten! 

Some concepts around expressing the results of multiple pages in a single report are being explore as part of #11313. Eventually this might work as some sort of "site-wide" report though no concrete plans to do so at this time. 

The crawling piece though has already been explored by the community with varying levels of success (https://github.com/github/lightcrawler, https://www.npmjs.com/package/lighthouse-crawler, https://fluxguard.com/how-to-guides/run-google-lighthouse-audits-on-a-single-page-or-an-entire-site)

**Comment by doooom2018** [comment]
The problem is confusion in the mouth

**Comment by adamraine** [comment]
This is possible now with flow reports, check out https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md.
