### ISSUE TITLE
Background and foreground colors have a sufficient contrast ratio Error!

### ISSUE THREAD

**Issue by bhaskar1603** [GoogleChrome/lighthouse#11923]
Lighthouse shows "Background and foreground colors have a sufficient contrast ratio Error!" error on Accessibility of my website gurugramproperty.in for mobile report

**Comment by patrickhulce** [comment]
Thanks for filing @bhaskar1603! I can't reproduce that result with the latest version of Lighthouse. If you weren't testing with 7.0, it's likely been fixed.

![image](https://user-images.githubusercontent.com/2301202/103790451-d5af6680-5006-11eb-9d33-6167853e78c1.png)

**Comment by bhaskar1603** [comment]
It has error for mobile report

**Comment by bhaskar1603** [comment]
It has error for mobile report

**Comment by patrickhulce** [comment]
That report in the screenshot was for mobile. 

If you still believe there is a bug here, please fill out the *entirety* of the [bug report template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) including environment information such as the Lighthouse version and channel used.

**Comment by bhaskar1603** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/61049327/103802452-2a89c600-5075-11eb-9c0f-c48c339f1c62.png)
![Screenshot (3)](https://user-images.githubusercontent.com/61049327/103802459-2c538980-5075-11eb-9c02-e423e40ee337.png)


here is the screenshot for environment info and issue

**Comment by scotty6435** [comment]
Axe reports that the share buttons have insufficient contrast. You have some odd generated classes and styles but the effective background of #1877F2 is not contrasting enough with #fff as a foreground colour at anything less than very large text sizes. https://webaim.org/resources/contrastchecker/

**Comment by bhaskar1603** [comment]
> Axe reports that the share buttons have insufficient contrast. You have some odd generated classes and styles but the effective background of #1877F2 is not contrasting enough with #fff as a foreground colour at anything less than very large text sizes. https://webaim.org/resources/contrastchecker/

thnks scotty
