### ISSUE TITLE
Spell check category

### ISSUE THREAD

**Issue by InDieTasten** [GoogleChrome/lighthouse#11926]
**Feature request summary**
Add a spell checker, ideally something licensed MIT, and check the pages text for spelling mistakes.

**What is the motivation or use case for changing this?**
I regularly run lighthouse on my pages to identify problems of any kind. Spelling mistakes are one of the problems that cannot be found using Lighthouse at the moment.  Good spelling is important for professional web sites. Many mistakes can also lead to reduced SEO Ranking?

**How is this beneficial to Lighthouse?**
Lighthouse is a tool used to identify problems with web pages. A professional website shouldn't contain spelling mistakes, so pointing out those mistakes in the report will be helpful for Lighthouse users.

**Challenge**
Spell checking is no easy task for sure. There will be false positives. Therefor I propose to have a separate category for spelling, rather than including it in the SEO category of audits.

**Comment by doooom2018** [comment]
O my love, I know not to use it by research, do I make my pain laugh? I
know the use of correcting my spelling, so do not go far. If you were like
this, I did not share with you. Or, please be reminded

في الخميس، 7 يناير 2021 5:37 م NDTSTN <notifications@github.com> كتب:

**Comment by InDieTasten** [comment]
> O my love, I know not to use it by research, do I make my pain laugh? I know the use of correcting my spelling, so do not go far. If you were like this, I did not share with you. Or, please be reminded  @doooom2018 

I'm not sure if this is lyrical excellence, you messing with me or just some machine translated text, but I'm ready for more 😄

**Comment by doooom2018** [comment]
> **Feature request summary**
> Add a spell checker, ideally something licensed MIT, and check the pages text for spelling mistakes.
> 
> **What is the motivation or use case for changing this?**
> I regularly run lighthouse on my pages to identify problems of any kind. Spelling mistakes are one of the problems that cannot be found using Lighthouse at the moment.  Good spelling is important for professional web sites. Many mistakes can also lead to reduced SEO Ranking?
> 
> **How is this beneficial to Lighthouse?**
> Lighthouse is a tool used to identify problems with web pages. A professional website shouldn't contain spelling mistakes, so pointing out those mistakes in the report will be helpful for Lighthouse users.
> 
> **Challenge**
> Spell checking is no easy task for sure. There will be false positives. Therefor I propose to run have a separate category for spelling, rather than including it in the SEO category of audits.

Yes, correct my mala hahahahahahahahahahaha

**Comment by doooom2018** [comment]
https://github.com/GoogleChrome

**Comment by patrickhulce** [comment]
Thanks for filing @InDieTasten!

Great idea! In practice I fear the false positive rate would likely be too high to be acceptable in Lighthouse core though. The language support question would also be thorny for the core team to handle. My feeling is that this is ideal territory for [a Lighthouse plugin](https://github.com/GoogleChrome/lighthouse/blob/master/docs/plugins.md) that site owners can optionally add rather than a core feature. 

Plugins are far more flexible in their bundle size, implementation, and subjective recommendations and easy to get started with! We'd be happy to add a spellcheck plugin to the main README section if one takes off in the community :)

**Comment by doooom2018** [comment]
Waiting for it I have to dismantle it Strong lifting protection

في الخميس، 7 يناير 2021 7:21 م Patrick Hulce <notifications@github.com> كتب:

**Comment by doooom2018** [comment]
I dirty my backhttps://support.google.com/accounts/thread/6562670?hl=en&msgid=6562670

**Comment by InDieTasten** [comment]
Thank you for your timely and helpful response @patrickhulce 

I did not know about the plugin system. I will take a look in the ecosystem and/or might take a stab at this myself.
