### ISSUE TITLE
Best practices problem (Serves images with low resolution)

### ISSUE THREAD

**Issue by bciach** [GoogleChrome/lighthouse#11936]
Hey, I am having problem with best practices section. It's telling me to resize photo due to problem - Serves images with low resolution. However its perfectly fine, the size of img was created by graphic designer specially for this purpose. Can you have a look please - its main photo, with blue background. Don't you think it's a kind of bug? 

To reproduce just simply navigate to https://bciach.com and run lighouse in dev tools

Every help is highly appreciated.

**Comment by patrickhulce** [comment]
Thanks for filing @bciach! I can't reproduce given just those steps.

![image](https://user-images.githubusercontent.com/2301202/104130289-7d91a080-5335-11eb-9eb5-8811d27d9a81.png)


Would you be able to fill out the entirety of [the bug report reproduction steps template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)? (Settings used, lighthouse version, Chrome version, etc)

**Comment by bciach** [comment]
First of all thanks a lot for your prompt response! 

Operating System: MacOS Catalina 10.15.7
Chrome Version: 87.0.4280.14
Computer: Macbook Pro 15' (2016)
Node: 12.11.1v
Lighthouse: 6.4.0



![Screenshot 2021-01-10 at 18 55 39](https://user-images.githubusercontent.com/13520099/104131239-8ace7f80-5375-11eb-9df2-2ac5341f5d75.png)

**Comment by patrickhulce** [comment]
Thanks for the additional info. Hm, I still can't reproduce the issue on that URL, but this looks exactly like a DPR difference.


See https://github.com/GoogleChrome/lighthouse/issues/11630,
https://github.com/GoogleChrome/lighthouse/issues/11238, 
https://github.com/GoogleChrome/lighthouse/issues/11240, https://github.com/GoogleChrome/lighthouse/issues/10802#issuecomment-630233444, https://github.com/GoogleChrome/lighthouse/issues/11169#issuecomment-664693157

**Comment by Sven74Muc** [comment]
I have exactly the same issue.

I have 4 teaser in one row. Each has on top an image. All sizes and the entire code is the same for each teaser.

![grafik](https://user-images.githubusercontent.com/27951109/104182663-134e2e00-5411-11eb-8f94-d5cac10fb8de.png)

URL: https://dlgo.de/111

What can we do?

**Comment by bciach** [comment]
I solved my problem by adding srcset.

**Comment by bsahins** [comment]
> I solved my problem by adding srcset.

How exactly?

**Comment by bciach** [comment]
> > I solved my problem by adding srcset.
> 
> How exactly?

Just add attribute srcset to your <img> element

https://html.com/attributes/img-srcset/

**Comment by issahassan5555** [comment]
I have this problem and others in the Best Practices section and this is my blog url: https://chemiall24.blogspot.com
Other problems are:
1. Displays images with incorrect aspect ratio
2. Browser errors were logged to the console
