### ISSUE TITLE
Bug with compressing file reccomendations and its time spending evaluation

### ISSUE THREAD

**Issue by Andrii256** [GoogleChrome/lighthouse#11945]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fglockapps.com%2F

There are recommendation: "Enable text compression" and there are few files. But when you open any of those files, they are minimized. And there are installed minimizing plugin.
This is bug

**Comment by patrickhulce** [comment]
Thanks for filing @Andrii256! 

This is not a bug in Lighthouse. Those files are *minified* but they are **not** *compressed*. Text compression is different from minification. You can learn more about this difference in the [audit's documentation](https://web.dev/uses-text-compression/?utm_source=lighthouse&utm_medium=unknown#how-to-enable-text-compression-on-your-server).

**Comment by Andrii256** [comment]
yes, problem was with gzip compression. But why did you call this "text compression" if there are more suitable "gzip compression"

**Comment by patrickhulce** [comment]
> But why did you call this "text compression" if there are more suitable "gzip compression"

It would ordinarily just be called "compression" but the *text* part differentiates it from the other audits that specifically target other encoding-specific types of compression such as image or video compression. Everything that's left that uses gzip that we target is text. Also, ideally we don't want you to use gzip, we want you to use an even better compression like brotli :)
