### ISSUE TITLE
Remove abandoned Magento module "baler" from suggestions

### ISSUE THREAD

**Issue by Leland** [GoogleChrome/lighthouse#11954]
**Summary**

Hi there! The Magento software baler is now [abandoned](https://github.com/magento/devdocs/pull/7876), and has been removed from all official Magento 2 documentation. It is still recommended in Lighthouse notices, however:

https://github.com/GoogleChrome/lighthouse/blob/a30953caea5e397ff1bb8b4a543674108dfa63c2/lighthouse-core/lib/i18n/locales/en-US.json#L2157

I'd strongly encourage that that recommendation be removed from all Lighthouse notices – the software is woefully out of date and doesn't support modern Magento 2 or PHP versions. I'd remove them myself, but I noticed that it was translated into many different languages (and alas I speak but English and 3 years worth of Spanish 😀)

**Comment by patrickhulce** [comment]
Thanks very much @Leland ! These messages are managed in the [stack packs repo](https://github.com/GoogleChrome/lighthouse-stack-packs) by community experts, it sounds like you're one of them and a PR there would be awesome! :)

**Comment by Leland** [comment]
Aha, apologies for the issue noise! Closing 🙏

**Comment by patrickhulce** [comment]
No worries at all, we appreciate your help in improving Lighthouse's advice! :)
