### ISSUE TITLE
Avoid document.write() error - optimisation

### ISSUE THREAD

**Issue by koskinpark** [GoogleChrome/lighthouse#11969]
#### Provide the steps to reproduce
1. **html**:
```
<script type="text/javascript" src="/path/to/beautiful.js"></script>
<link type="text/css" rel="stylesheet" href="/path/to/beautiful.css" />
<!-- just a beautiful comment -->
```
**beautiful.js**:
```
if (someCondition) {
  document.write('<!--');
}
```
if condition of the script passed, then result is:
```
<script type="text/javascript" src="/path/to/beautiful.js"></script><!--
<link type="text/css" rel="stylesheet" href="/path/to/beautiful.css" />
<!-- just a beautiful comment -->
```

#### What is the current behavior?
Lighthouse report:
```
Avoid document.write() 
For users on slow connections, external scripts dynamically injected via `document.write()` can delay page load by tens of seconds.
```

#### What is the expected behavior?
Since `document.write()` is the best (and fastest) way to "comment" unneeded `<link>`, document.write() should pass lighthouse diagnostic. But actually, it was all - just an example. I'm thinking if lighthouse can calculate amount of usages things to avoid and look into it more detailed. In my case - it is just 4 text-symbols that `document.write` adds, so, ideas?

#### Environment Information
* Lighthouse version: 100.0.0.0
* Chrome version: 87.0.4280.141
* Node.js version: 12.16.2
* Operating System: macOS Catalina 10.15.7

**Comment by patrickhulce** [comment]
Thanks for filing @koskinpark!

The few characters of text that the `document.write` call adds is not the concern. The problem with `document.write` is that it changes the result of HTML parsing. In the example case you provide, the [stylesheets are still going to be downloaded](https://www.webpagetest.org/result/210118_Di22_3c40bb71ac9415fc77d2a879f2140672/1/details/#waterfall_view_step1) thanks to the preparser which results in wasted bandwidth. It's a best practice to rewrite your conditional inclusion of the stylesheet in a way that does not result it the file being downloaded unnecessarily. Lighthouse is working as intended in this case.

**Comment by paulirish** [comment]
document.write is very much not-recommended. https://developers.google.com/web/updates/2016/08/removing-document-write
