### ISSUE TITLE
Runtime Error: Method: Emulation.setScriptExecutionDisabled

### ISSUE THREAD

**Issue by ast-hao** [GoogleChrome/lighthouse#11973]
When I run the command try to batch proceed URLs, after the first URLs successfully run, error occurs in the some of the rest URLs in the list:

The command is:
```
@echo off
for /f “delims=” %a in (D:\Sites.txt) DO (
ECHO Line is: %a
lighthouse --output="csv" –-quiet --preset=desktop –-chrome-flags=”–-headless” %a
)
```

The error is occurred in some of the rest URLs,
![image](https://user-images.githubusercontent.com/77451683/104969287-65b5be80-59be-11eb-81c7-e92c3a08e769.png)

The problem is: there will be no .csv file output for the URL with error occurred, the rest URLs without error have .csv file.

When I remove "pwa" from category by using `--only-categories`, no error any more.

After investigating, it seems because of the PWA checking on the URL returns "too slowly".
![image](https://user-images.githubusercontent.com/77451683/104971401-0f984980-59c5-11eb-982d-1391445e7ea1.png)

Hopefully this can be considered in command line, which means build "error message" inside of .csv but not during the process and skip the .csv report.

Thanks.

**Comment by patrickhulce** [comment]
Thanks for filing @ast-hao! See https://github.com/GoogleChrome/lighthouse/issues/6512 for more on this error (Useful to know that PWA is related, but that red text in the screenshot you shared is a different sort of timeout that isn't related to the `setScriptExecutionDisabled` PROTOCOL__TIMEOUT)

As to your request for the CSV to still be produced. This error is so fatal and produces no useful information that we feel it important to exit with an error from the CLI without producing the requested output. There are still ways this error can be processed from a batch script (writing stderr to adjacent files, processing the exit code, etc) that we're comfortable with this decision.

**Comment by gkatsanos** [comment]
hey @paulirish , @patrickhulce . I'm running lighthouse-ci server on a docker container (integration with Github actions) , get the same error, and I am unable to find any valuable info in #6512 . 

notably: 
- image : `cypress/browsers:node14.17.0-chrome91-ff89` 
- node 14.17.0 (clearly)
- error: 
```
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/src/collect/node-runner.js:120:21)
    at ChildProcess.emit (events.js:376:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Sun, 10 Oct 2021 21:42:41 GMT ChromeLauncher Waiting for browser.
Sun, 10 Oct 2021 21:42:41 GMT ChromeLauncher Waiting for browser...
Sun, 10 Oct 2021 21:42:41 GMT ChromeLauncher Waiting for browser.....
Sun, 10 Oct 2021 21:42:41 GMT ChromeLauncher Waiting for browser.....✓
Sun, 10 Oct 2021 21:42:42 GMT config:warn IFrameElements gatherer requested, however no audit requires it.
Sun, 10 Oct 2021 21:42:42 GMT config:warn FormElements gatherer requested, however no audit requires it.
Sun, 10 Oct 2021 21:42:42 GMT status Connecting to browser
Sun, 10 Oct 2021 21:42:42 GMT status Resetting state with about:blank
Sun, 10 Oct 2021 21:42:42 GMT status Benchmarking machine
Sun, 10 Oct 2021 21:42:43 GMT status Initializing…
Sun, 10 Oct 2021 21:42:43 GMT status Running defaultPass pass CSSUsage, JsUsage, ViewportDimensions, ConsoleMessages, AnchorElements, ImageElements, LinkElements, MetaElements, ScriptElements, IFrameElements, FormElements, MainDocumentContent, GlobalListeners, AppCacheManifest, Doctype, DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility, TraceElements, InspectorIssues, SourceMaps, FullPageScreenshot
Sun, 10 Oct 2021 21:42:43 GMT status Resetting state with about:blank
Sun, 10 Oct 2021 21:42:43 GMT status Cleaning browser cache
Sun, 10 Oct 2021 21:42:43 GMT status Preparing network conditions
Sun, 10 Oct 2021 21:42:43 GMT status Beginning devtoolsLog and trace
Sun, 10 Oct 2021 21:42:43 GMT status Loading page & waiting for onload
Sun, 10 Oct 2021 21:43:28 GMT waitFor:warn Timed out waiting for page load. Checking if page is hung...
Sun, 10 Oct 2021 21:43:29 GMT waitFor:warn Page appears to be hung, killing JavaScript...
Sun, 10 Oct 2021 21:43:59 GMT status Disconnecting from browser...
Sun, 10 Oct 2021 21:43:59 GMT ChromeLauncher Killing Chrome instance 540
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)
LHError: PROTOCOL_TIMEOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/gather/driver.js:322:21)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
```

the page/server is accessible and working when I access it in a "normal" browser.
