### ISSUE TITLE
Is Lighthouse using "Lab Data"?

### ISSUE THREAD

**Issue by ast-hao** [GoogleChrome/lighthouse#11974]
Read from several documents and articles, they state that Lighthouse is using Lab Data only.
However, when I use command line to get score on same site, they got huge difference.

Here is an interesting example come from a coincidence.
When I test https://support.apple.com, it's noticed that, the **CLS** (Cumulative Layout Shift) **was 0.13** **at one time**, in the **rest times**, the **value is 1**.
To replicate it, I tried to visit https://support.apple.com some times. **At one time, I found a "you are invited to survey" banner appears on the top of the page after it is loaded,** which will apparently impact the CLS. 

So, back to the question, is Lighthouse using "Lab Data" under Performance?
If not, is there a way to choose to use "Lab Data". Otherwise, if the coincidence happen again, the data will not accurate.

Thanks for reading.

**Comment by patrickhulce** [comment]
Thanks for filing @ast-hao! Yes, Lighthouse produces lab data, and lab data does not mean results are always the same. See [variability docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) and #10657 for more.

**Comment by ast-hao** [comment]
> Thanks for filing @ast-hao! Yes, Lighthouse produces lab data, and lab data does not mean results are always the same. See [variability docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) and #10657 for more.

Hi Patrickhulc,

Thanks for your reply. I read the 2 links referred in your reply.
But it seems they might different "reason" to my posted case. 
The posted case here is maybe a random come-up banner heavily impacted the performance result on CLS (1 to 0.13), which means the banner may display in some visits at 1 time, and not-display in the rest visit.
As a result, when I run a test, it just coincidently simulated a visit with banner which caused the significant CLS, then in next run lighthouse, it simulated another visit without banner. 
I have run everything at same machine on same configuration, in some data / URL, performance score got slightly different, e.g. 0.94 to 0.83, etc., but that one is the only one have so heavily different, 1 to 0.13, and appears 0.13 only one time for my 10 times run of lighthouse.

Just further explanation to the situation I met. Hope it could help to further development.
Thank you.

**Comment by patrickhulce** [comment]
That's called [Page non-determinism](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md#page-nondeterminism) and will never be accounted for in Lighthouse (in fact it's a *feature* of Lighthouse, the page is delivering different experiences that have different performance characteristics. It would be a bug if Lighthouse didn't notice 😃 ). It's up to the page to deliver the same experience.

Tools like [WPRgo](https://github.com/catapult-project/catapult/tree/master/web_page_replay_go) can help with this situation if you don't control the page that is changing that you're trying to measure.

**Comment by ast-hao** [comment]
> That's called [Page non-determinism](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md#page-nondeterminism) and will never be accounted for in Lighthouse (in fact it's a _feature_ of Lighthouse, the page is delivering different experiences that have different performance characteristics. It would be a bug if Lighthouse didn't notice 😃 ). It's up to the page to deliver the same experience.
> 
> Tools like [WPRgo](https://github.com/catapult-project/catapult/tree/master/web_page_replay_go) can help with this situation if you don't control the page that is changing that you're trying to measure.

very clear! thank you @patrickhulce
