### ISSUE TITLE
Google lighthouse Enterprise Support Request

### ISSUE THREAD

**Issue by Ketki123-tech** [GoogleChrome/lighthouse#11981]
Our organization wants to use google lighthouse open source for identifying accessibility issues as it solves a lot of problems we are facing with Siteimprove but the only limitation we find in doing that is there is no enterprise level support provided which we would want since in future if we use this tool there will be a security audit within our organization before we use it in production and those security findings we may or may not be able to fix. In such scenarios enterprise level support will be helpful. we are ready to pay but there is no such feature offered, I sincerely think if that is provided it maybe the best tool. so let me know if there is any option to get payed support apart from Github ?

**Comment by patrickhulce** [comment]
Thanks for filing @Ketki123-tech!

There is no official paid enterprise support tier for Lighthouse. If you're mostly concerned about accessibility support, the accessibility issues in Lighthouse are powered by axe which is built by [deque](https://www.deque.com/) and does offer something like what I think you're looking for (but only for the accessibility issues).

> there will be a security audit within our organization before we use it in production and those security findings we may or may not be able to fix

We generally try to keep the security audit violations in Lighthouse at 0. If `npm audit` returns anything, a regular issue filed here should be sufficient to resolve it in a future release.

**Comment by Ketki123-tech** [comment]
Can you also help with google lighthouse plugin 7.0 version since in chrome webstore we only get the 6.0 version which is not fetching correct results as below. Also does lighthouse plugin cannot work with authenticated pages ?

There were issues affecting this run of Lighthouse:

The page may not be loading as expected because your test URL (https://careersmarketplace.ciostage.accenture.com/) was redirected to https://login.microsoftonline.com/f3211d0e-125b-42c3-86db-322b19a65a22/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=45a75928-4ad3-44b5-a439-83eade7f161c&redirect_uri=https%3A%2F%2Fcareersmarketplace.ciostage.accenture.com%2F&state=eyJpZCI6ImZmY2NhMDEyLTUyYTMtNGY5MC1iNWRmLWIyZjg2OTYxNmNhNyIsInRzIjoxNjExMjIzNjk3LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0%3D&nonce=dac2784d-f046-414c-8e41-0cd1e27c2f8f&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.1&client-request-id=5ce6c526-b8c0-48ba-bee2-955c73be060e&response_mode=fragment. Try testing the second URL directly.
Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_TIMED_OUT)

**Comment by patrickhulce** [comment]
See [testing authenticated pages](https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md).
