### ISSUE TITLE
CSS image-set triggers a Largest Contentful Paint (NO_LCP) Error and performance ? on mobile

### ISSUE THREAD

**Issue by Dominik-Giroux** [GoogleChrome/lighthouse#11984]
Hello, I've been running several lighthouse test using both chrome dev tools and https://web.dev/measure/ recently.
I'm trying to optimize images for performance and my CDN delivers jpg and webp formats.
Since my images are in css, within background-image, I've been using the new property image-set for webp fallbacks.

So for my classes, I use both background-image: url(CDN) and background-image(image-set(url(CDN)));
This works and load the proper format depending on browsers and when I run a lighthouse audit in desktop, I get 100 on every categories, however when I do it in mobile, performance gives me ? and some errors.

![Screenshot 2021-01-20 at 3 52 49 PM](https://user-images.githubusercontent.com/15654751/105233329-b56bc580-5b37-11eb-9a4b-aec4f49e0f42.png)

Here's the desktop one.

![Perfect lighthouse](https://user-images.githubusercontent.com/15654751/105233428-d7fdde80-5b37-11eb-9def-483b4f23902e.png)

As soon as I stop using image-set, It doesn't trigger any errors and give me an actual performance score.

**Comment by connorjclark** [comment]
Can you provide a minimal repro (host it on surge.sh or just paste the HTML here)?
