### ISSUE TITLE
Chrome throttling of background timers means every page times out in DevTools

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChrome/lighthouse#11983]
#### Provide the steps to reproduce
1. Run LH on https://www.koolsol.com/?lang=fr

#### Current behavior : a message appears 

"Cette exécution de Lighthouse a rencontré des problèmes :
Le chargement de la page a été trop lent et a dépassé la limite de temps. Il est possible que les résultats soient incomplets."

translated in english, it should be :

This Lighthouse run has encountered issues:
The page load was too slow and exceeded the time limit. The results may be incomplete.

See image below

#### expected behavior? 
No message.
This url shows a 100% on all scores on 
chrome Version 88.0.4324.96 (Build officiel) (64 bits)
lighthouse 6.4.0

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: Generated by Lighthouse 7.0.0
* Chrome version: Version 90.0.4394.2 (Build officiel) canary (64 bits)
* Node.js version: v10.16.3
* Operating System: window 10

![2021-01-20-lighthouse](https://user-images.githubusercontent.com/26767344/105179780-02489f80-5b2a-11eb-930a-f400e65f5bf9.png)

**Comment by patrickhulce** [comment]
Thanks for filing @hugues-koolsol! I'm not able to reproduce this with the provided settings. Is it possible there's an extension, plugin, anti-virus, *something* else running on the machine? Lighthouse waits for all activity to finish in the page. If there are non-page resources that sit pending, it could trigger this message.

**Comment by hugues-koolsol** [comment]
Hello, thank you for your reply.
I have tried with avast disabled and it is the same result. 
No other extension is installed on my computer/browser.
Only canary is running with only one tab opened.

The difference I have noticed is : 
With canary and lighthouse 7.0, I cannot see the reload of the page with javascript disabled around the end of the test. 
With chrome and lighthouse 6.4, I can see it the reload of the page with javascript disabled because a waiting css spinner appears.

Anyway, I am wondering if this message should pop up when the performance test result is over 90 like in this case ?

**Comment by patrickhulce** [comment]
Hm, OK I was able to reproduce 1/10 times. Does it occur for you on every attempt?

> Anyway, I am wondering if this message should pop up when the performance test result is over 90 like in this case ?

It should. When the page had resources that timed out and didn't finish, the page might not actually have a score of 90+, and the warning is serving its intended purpose. The point of this warning is that Lighthouse didn't observe all of the page's resources, so there might have been more to this page that Lighthouse didn't see (and therefore the score might be lower on the actual page than the partial load that Lighthouse is analyzing)

We're open to tweaking the wording to make that clearer if you have suggestions :)

**Comment by hugues-koolsol** [comment]
Hello Patrick, thank you for your reply.
I had this message 5/5 times 

Your wording is perfect :) I have nothing better to say about it when there is a real slow down.

Now, the fact that I do not see the intermediate screen triggers me ( load without javascript enabled on canary90/lighthouse7.0) .
I see it on  chrome88/lighthouse6.4, ( below the capture  ) , 
and perhaps this message comes from this difference !

![2021-01-21-lighthouse-on-chrome](https://user-images.githubusercontent.com/26767344/105332896-67a59a80-5bd5-11eb-9148-30150f67d893.png)
Hugues

**Comment by patrickhulce** [comment]
Since our convo, I've seen this message now on many simple sites (like example.com) too that definitely shouldn't be triggering the message. It's flaky for me, but something must have changed about the network request events that Lighthouse isn't catching anymore. We'll look into it 👍

**Comment by patrickhulce** [comment]
F, so the [new throttling of chained background timers](https://developer.chrome.com/blog/timer-throttling-in-chrome-88/) has destroyed our CPU idle check. Our timeouts always appear to have taken more than a long task, so we wait for more data until the user actually clicks onto the page again (because apparently having devtools open on the page still backgrounds the page). 

We can push a workaround out for our use case but this is also going to heavily skew perf numbers. Long-term we *really*, *really* need a way to force the page into the foreground from DevTools protocol.
