### ISSUE TITLE
Preload key requests audit still showing linked resources that have been placed in the head with preload parameters

### ISSUE THREAD

**Issue by Surf-And-Sand** [GoogleChrome/lighthouse#11982]
#### Provide the steps to reproduce
1. Run LH on https://gogonihon.com/en/
  
#### What is the current behavior?
Lighthouse audit for preload key requests has 3 fonts recommended to be preloaded.

#### What is the expected behavior?
I would expect that there are no fonts showing in the preload key requests audit, since they've already been place in the head with preload parameters.

#### Environment Information
* Affected Channels: DevTools - Lighthouse
* Lighthouse version:
* Chrome version: Version 87.0.4280.141 (Official Build) (x86_64)
* Node.js version:
* Operating System: OSX Big Sur 11.1

**Related issues**
I've also tried removing those fonts from my stylesheet, and the issue persists where Lighthouse keeps saying to preload these font resources.

**Comment by patrickhulce** [comment]
Thanks for filing @Surf-And-Sand!

I'm not seeing any existing preload elements in the head. 

![image](https://user-images.githubusercontent.com/2301202/105203187-72462e00-5b08-11eb-9ba7-12de04cd97ce.png)


These fonts come from the autooptimize.css and do block rendering of the text on the page. That being said we are re-evaluating our preload advice in #11960 that might hide these suggestions in the future.

**Comment by Surf-And-Sand** [comment]
That is bizarre. It's in my header file, but it's appearing in the body!

I've got to check the code on my side. Sorry about that.

________________________________

**Comment by Surf-And-Sand** [comment]
OK, so I've moved my font preloads to the correct place, and now they're in the header as suggested by the lighthouse tool. I'm still getting the audit flag.

[cid:9d59b57f-4e54-4421-865d-8aea196c3f92]
[cid:d0eb5483-a0e3-455e-839a-9facec714b00]

________________________________

**Comment by InfiniteSpirals** [comment]
It looks like you are using a non-standard double quote in the href of your preload. When you follow from the source it resolves to  https://gogonihon.com/en/%E2%80%9D/wp-content/themes/gogoworld/assets/font/Roboto/Roboto-Bold.ttf which 404's...

**Comment by Surf-And-Sand** [comment]
Thanks! Amazing support! I copied the code from a blog article and just replaced my source, but I must have missed the non-standard quotes.

In any case, I've replaced the offending quotes with standard ones. They now resolve to the correct asset, but the audit flag still persists.

We plan on replacing the locally sourced fonts soon, but I want to learn more about why the lighthouse audit keeps getting flagged first.

________________________________

**Comment by InfiniteSpirals** [comment]
Hey @Surf-And-Sand,  looks like you are now serving the assets from a CDN url in your preload (https://mk0gogonihonsps6abbx.kinstacdn.com), but your css is still requesting these from the root domain as well. Source of those requests is https://mk0gogonihonsps6abbx.kinstacdn.com/wp-content/cache/autoptimize/css/autoptimize_798817135892f595448cc27c320cc9cf.css you can see this in the network tab if you filter by fonts.

![image](https://user-images.githubusercontent.com/3270714/105471592-d0068180-5c92-11eb-9c19-8c6fde10b0f9.png)

**Comment by looking-goood** [comment]
___

**Comment by looking-goood** [comment]
> It looks like you are using a non-standard double quote in the href of your preload. When you follow from the source it resolves to  https://gogonihon.com

**Comment by looking-goood** [comment]
- [ ] -

**Comment by looking-goood** [comment]
-

**Comment by Surf-And-Sand** [comment]
I was able to pass the lighthouse audit by putting the requested assets explicitly (full uri) in both the head and style files. 

Thanks for your assistance folks!
