### ISSUE TITLE
Fail immediately if the server is unavailable

### ISSUE THREAD

**Issue by bob-zs** [GoogleChrome/lighthouse#11996]
Using the example in the README
https://github.com/GoogleChrome/lighthouse/blob/a6738e0033e7e5ca308b97c1c36f298b7d399402/docs/readme.md#using-programmatically

Here, lighthouse runs on `http://localhost:8080/'`, and assume the server is not up.

```
const unavailableServerURL = 'http://localhost:8080/';
const fs = require('fs');
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');

(async () => {
  const chrome = await chromeLauncher.launch({chromeFlags: ['--headless']});
  const options = {logLevel: 'info', output: 'html', onlyCategories: ['performance'], port: chrome.port};
  const runnerResult = await lighthouse(unavailableServerURL, options);

  // `.report` is the HTML report as a string
  const reportHtml = runnerResult.report;
  fs.writeFileSync('lhreport.html', reportHtml);

  // `.lhr` is the Lighthouse Result as a JS object
  console.log('Report is done for', runnerResult.lhr.finalUrl);
  console.log('Performance score was', runnerResult.lhr.categories.performance.score * 100);

  await chrome.kill();
})();
```

Without having the localhost server up, it still runs, and we have to wait for it to finish without knowing the problem was it could not connect to the server.

```
node unavailableServer.js 
  status Connecting to browser +0ms
  status Resetting state with about:blank +15ms
  status Benchmarking machine +71ms
  status Initializing… +1s
  status Running defaultPass pass CSSUsage, JsUsage, ViewportDimensions, ConsoleMessages, ImageElements, LinkElements, ScriptElements, DOMStats, OptimizedImages, ResponseCompression, TagsBlockingFirstPaint, TraceElements, SourceMaps, FullPageScreenshot +31ms
  status Resetting state with about:blank +1ms
  status Setting up network for the pass trace +8ms
  status Cleaning browser cache +1ms
  status Beginning devtoolsLog and trace +18ms
  status Loading page & waiting for onload +76ms
  status Gathering in-page: CSSUsage +30s
  status Gathering in-page: JsUsage +0ms
  status Gathering in-page: ViewportDimensions +0ms
  status Gathering in-page: ConsoleMessages +0ms
  status Gathering in-page: ImageElements +1ms
  status Gathering in-page: LinkElements +0ms
  status Gathering in-page: ScriptElements +0ms
  status Gathering in-page: DOMStats +0ms
  status Gathering in-page: OptimizedImages +0ms
  status Gathering in-page: ResponseCompression +0ms
  status Gathering in-page: TagsBlockingFirstPaint +0ms
  status Gathering in-page: TraceElements +0ms
  status Gathering in-page: SourceMaps +0ms
  status Gathering in-page: FullPageScreenshot +0ms
  status Gathering trace +0ms
  status Gathering devtoolsLog & network records +79ms
  GatherRunner:error Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_REFUSED) http://localhost:8080/ +3ms
  status Disconnecting from browser... +0ms
  status Analyzing and running audits... +12ms
  status Auditing: First Contentful Paint +2ms
  Runner:warn traces gatherer, required by audit first-contentful-paint, did not run. +1ms
  status Auditing: Largest Contentful Paint +3ms 

```

Is there a way to have lighthouse just throw an error  and kill the process and let us know that it could not connect before it runs these audits?

Also, asking the chrome-launcher engineers if  the process can just end or throw an error if it can't connect or if the server is unavailable:
https://github.com/GoogleChrome/chrome-launcher/issues/233

**Comment by connorjclark** [comment]
we'll need some more investment from you. say more? are you unhappy with the current timeout behavior?

**Comment by bob-zs** [comment]
@connorjclark is there a way to just have the process throw an error or kill itself if it senses the server is not on? That way, no needing to wait for all these audits.

And what's the timeout behavior?

**Comment by patrickhulce** [comment]
@bob-zs just to be clear here, are you concerned about the few hundred ms of Lighthouse cleaning up after it tries to load the page and sees that the server is down?

The entire process takes ~4s on my machine for a localhost URL that's down and most of that is waiting for setup pieces. Is the issue that you don't want to launch Chrome in the first place if the URL isn't available? That's up to whoever owns the script you shared :)


```js
(async () => {
  // We don't know if the URL is bad and we *really* hate wasting a few seconds.
  const url = new URL(unavailableServerURL)
  await new Promise((resolve, reject) => {
    const socket = new net.Socket()
      .on('error', reject)
      .on('connect', () => { resolve(); socket.close(); })
      .connect(url.port, url.hostname)
  })

  const chrome = await chromeLauncher.launch({chromeFlags: ['--headless']});
})()
```
(untested example, might have bugs, no support available :D)

**Comment by bob-zs** [comment]
@patrickhulce, when using lighthouse in testing, it’s more that it would be clearer to see a test fails because it can’t connect to a server instead of thinking the application is regressing.

I take back it just being about having to wait for the process to end. I thought it be clearer if there was a way to just end the process for not connecting to the server and say it fails because of that and not because the audits themselves are failing.

**Comment by patrickhulce** [comment]
> it’s more that it would be clearer to see a test fails because it can’t connect to a server instead of thinking the application is regressing

That's what the `runtimeError` property is for. The toplevel warning that says "Make sure you are testing the correct URL and that the server is properly responding to all requests" is also thrown into the report in case folks miss the `runtimeError` property. I'm still unsure what behavior you'd like to see instead.

**Comment by bob-zs** [comment]
Oh thanks for that tip. It seems to be working with our tests. Thanks
```
  const results = await lighthouse(url, opts, config);
  if (results.lhr.runtimeError) {
    const runtimeError = results.lhr.runtimeError;
    throw new Error(runtimeError.code);
  }
```
