### ISSUE TITLE
Synthetix.io Meta Mask (fake) discovered in code

### ISSUE THREAD

**Issue by LinkTheLion** [GoogleChrome/lighthouse#12028]
https://synthetix.io/

The code is written so that it wont re-occour every time, but it will load a fake message masking itself as your meta mask pop up and tell you it is needing the recovery phrase. 
  
Here is the debug of the website home page. you can see it splits off into other routes. And the part where it says wolf2 that is what the person named the image that pops up on the fake meta mask. 
Maximum critical path latency: 4,400 ms
Initial Navigation
https://synthetix.io
/css2?family=Inter&display=swap(fonts.googleapis.com)
…v3/UcCO3FwrK….woff2(fonts.gstatic.com) - 40 ms, 17.12 KiB
/fonts/GT-Americ….woff2(synthetix.io) - 50 ms, 35.64 KiB
/fonts/GT-Americ….woff2(synthetix.io) - 40 ms, 36.41 KiB

I dove into the code, its definitely not something MIT wrote. But the scammer started stealing from my meta mask. So i moved all the ETH off the acct, even after he deposited more lol. I just dont want others to be falling for this trick so it be worth looking at other websites too that he may put this mask on the website. 

In the debug report one of the links  listed here ( …chunks/10.446e0a9….js(synthetix.io)  ) you'll find alot of the written walk through of the code where he mentions a 2 times... 

return n.PropTypes=n,n}},function(e,t,n){"use strict";e.exports="SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED"},function(e,t,n){(e.exports=n(12)(!1)).push([e.i,"@keyframes fade-in {\n  from {\n    opacity: 0;\n    visibility: hidden;\n  }\n  to {\n    opacity: 1;\n    visibility: visible

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36

Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Mobile Safari/537.36 Chrome-Lighthouse

[synthetix.it meta  mask trap.pdf](https://github.com/GoogleChrome/lighthouse/files/5899552/synthetix.it.meta.mask.trap.pdf)

* Node.js version:
* Operating System:

**Related issues**

**Comment by LinkTheLion** [comment]
![fake](https://user-images.githubusercontent.com/72988353/106381919-02e30080-638a-11eb-865f-57798e34d575.jpeg)

**Comment by patrickhulce** [comment]
Thanks for filing @LinkTheLion that's very sneaky! I'd report this to the [SafeBrowsing phishing team](https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en). This is for Lighthouse which doesn't handle stuff like that.
