### ISSUE TITLE
All frame CLS should use weighted score to account for frame size

### ISSUE THREAD

**Issue by anniesullie** [GoogleChrome/lighthouse#12023]
I saw that @adamraine added support for CLS in all frames in #11713. Awesome!

But it looks like that code just adds up the individual layout shift scores for all frames? Iframes should use the weighted score, which accounts for their size. For example, if a 10x10 pixel iframe had a shift across its entire viewport, the score of the shift is 1, but the weighted score is much lower to take into account that the user only saw the shift in a tiny area of the viewport.

The weighted score was just added to the trace in chromium today in https://chromium-review.googlesource.com/c/chromium/src/+/2659157

It will be in M90; let us know if we should request a merge to M89!

**Comment by adamraine** [comment]
Thanks for the heads up @anniesullie!

If it's not too much extra work, I think merging to M89 is a good idea. We may want the corrected results to be queryable in HTTP archive sooner.

**Comment by anniesullie** [comment]
Requested a merge in crbug.com/1173139
