### ISSUE TITLE
*Question* - Can we use this on the fly?

### ISSUE THREAD

**Issue by VatsaDev** [GoogleChrome/lighthouse#12027]
# Can we use this on the fly?

My question is, can I call this in the browser on a certain event, and get the values as JSON or xml and display?

*example* - like check the quality of an IFrame when the user keyups and then alert the values?

**Comment by connorjclark** [comment]
You can do most anything with puppeteer scripting. See our docs for examples.

**Comment by VatsaDev** [comment]
ok then ill check
