### ISSUE TITLE
ARIA IDs are not unique - detecting "for" in <label> as duplicate

### ISSUE THREAD

**Issue by jimmackinlt** [GoogleChrome/lighthouse#12022]
Hi,

Lighthouse reports **ARIA IDs are not unique** for fragments like the one below.
Searching the source shows **xyz0020** in only these 2 elements.

```
<span class="fancytree-title">
   <input type="checkbox" id="xYz0020" checked="" tabindex="-1">
   <label for="xYz0020" class="sc tabE1">Christmas 12/25 &amp; Holiday (739)</label>
</span>
```  

#### What is the expected behavior?
AXE does not report this as a problem.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 6.4.0
* Chrome version: 88.0.4324.104 (Official Build) (64-bit) (cohort: Stable)
* Node.js version:
* Operating System: Windows 10 OS Version 1909 (Build 18363.1316)

The live version of the page is here:
https://www.leanintree.com/christmas-cards.html

Many thanks,
- Jim

**Comment by patrickhulce** [comment]
Thanks for filing @jimmackinlt! I'm not able to reproduce that issue with Lighthouse 7.0.0 in Canary nor am I able to find those elements in the page when inspecting manually. Are you 100% sure that URL is the one that reproduces this issue?

**Comment by jimmackinlt** [comment]
Hi Patrick,

Yes, here's a screenshot of the lighthouse report.  The offending id's are in the side menu that takes a few seconds to appear and review via inspect.  They are all xYz####.

Since my browser is on LH 6.4.0, it may have already been fixed.

![screenshot_lighthouse_aria_dup](https://user-images.githubusercontent.com/5083640/106325735-855bab00-6238-11eb-9506-6ca5106bc2a3.png)

Thanks,
- Jim

**Comment by patrickhulce** [comment]
Ah, is this only on the desktop version of the page? I'm still not able to reproduce in latest version, but I do so the markup now. I'm guessing it's been fixed already. You can try with Chrome Canary if you'd like as a workaround?

That page crashes Chrome entirely on stable for me, so I'm unable to test there.

**Comment by jimmackinlt** [comment]
Yes, Patrick.  

Canary is fine, so we'll consider it fixed.  

Many Thanks,
Jim
