### ISSUE TITLE
Crashes on Certain URLs when running inside an EC2 instance. 

### ISSUE THREAD

**Issue by gkemp94** [GoogleChrome/lighthouse#12021]
I'm running lighthouse tests inside an EC2 instance,  m5.large (as recommended), with the latest lighthouse (7.0.1). I'm seeing a handful of sites crash the process, and not complete. Not sure what these sites have in common, but can't seen to find a way to prevent it from happening. 

#### Provide the steps to reproduce
1. Using a EC2 instance (m5.large) w/ Lighthouse version 7.0.1 attempt to run lighthouse via the node module with headless, no sandbox enabled.
2. Run LH on https://slack.com 

  

#### What is the current behavior?
Lighthouse crashes at a certain point.

#### What is the expected behavior?
Lighthouse runs the test fully.

#### Environment Information
* Affected Channels:  Node
* Lighthouse version: 7.0.1
* Chrome version: 
* Node.js version: 14.x.x
* Operating System: Amazon Linux 2 - EC2 Instance - m5.large

<img width="1125" alt="Screen Shot 2021-01-29 at 8 29 01 AM" src="https://user-images.githubusercontent.com/24573792/106294576-9098e180-620c-11eb-8d38-90a80150af28.png">

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @gkemp94! Those logs indicate that *Chrome* is crashing. Have you already explored uploading those crash reports to Chromium?

**Comment by gkemp94** [comment]
@patrickhulce , where would be the best place to do that? Thanks.

**Comment by patrickhulce** [comment]
`chrome://crashes` gives you list of all the crashes to upload if you have the ability to use the UI through remote desktop or some local linux repro.

https://crbug.com/ will let you file with a manual crash dump file generated by `--enable-crash-reporter --crash-dumps-dir=<your_dump_dir>`
