### ISSUE TITLE
Lighthouse says image sizes could be reduced while browser is selecting the right size.

### ISSUE THREAD

**Issue by PascalPixel** [GoogleChrome/lighthouse#12036]
#### Provide the steps to reproduce
1. Run LH on https://curb-f7oxf3kp4.vercel.app/
  

#### What is the current behavior?
Given this code, that should pick the *closest to 100px on all screen sizes*:
```html
<img
  alt="Inside of a Home"
  src="https://ik.imagekit.io/y669gok8iu/rapmls//sfarmls/listingpics/bigphoto/2020/08/02/740e9d1f-de8d-4fe6-8832-e3f04b9ae0f8.jpg?tr=w-1536,q-30"
  decoding="async"
  sizes="(max-width: 640px) 100px, (max-width: 768px) 100px, (max-width: 1024px) 100px, (max-width: 1280px) 100px, 100px"
  srcset="
    https://ik.imagekit.io/y669gok8iu/rapmls//sfarmls/listingpics/bigphoto/2020/08/02/740e9d1f-de8d-4fe6-8832-e3f04b9ae0f8.jpg?tr=w-80,q-30     80w,
    https://ik.imagekit.io/y669gok8iu/rapmls//sfarmls/listingpics/bigphoto/2020/08/02/740e9d1f-de8d-4fe6-8832-e3f04b9ae0f8.jpg?tr=w-160,q-30   160w,
    https://ik.imagekit.io/y669gok8iu/rapmls//sfarmls/listingpics/bigphoto/2020/08/02/740e9d1f-de8d-4fe6-8832-e3f04b9ae0f8.jpg?tr=w-320,q-30   320w,
    https://ik.imagekit.io/y669gok8iu/rapmls//sfarmls/listingpics/bigphoto/2020/08/02/740e9d1f-de8d-4fe6-8832-e3f04b9ae0f8.jpg?tr=w-640,q-30   640w,
    https://ik.imagekit.io/y669gok8iu/rapmls//sfarmls/listingpics/bigphoto/2020/08/02/740e9d1f-de8d-4fe6-8832-e3f04b9ae0f8.jpg?tr=w-768,q-30   768w,
    https://ik.imagekit.io/y669gok8iu/rapmls//sfarmls/listingpics/bigphoto/2020/08/02/740e9d1f-de8d-4fe6-8832-e3f04b9ae0f8.jpg?tr=w-1024,q-30 1024w,
    https://ik.imagekit.io/y669gok8iu/rapmls//sfarmls/listingpics/bigphoto/2020/08/02/740e9d1f-de8d-4fe6-8832-e3f04b9ae0f8.jpg?tr=w-1280,q-30 1280w,
    https://ik.imagekit.io/y669gok8iu/rapmls//sfarmls/listingpics/bigphoto/2020/08/02/740e9d1f-de8d-4fe6-8832-e3f04b9ae0f8.jpg?tr=w-1536,q-30 1536w
  "
/>

```
Because Lighthouse uses a 3x DPI screen, this 100px target becomes 300px.

The image Lighthouse uses is the 320px one.

However, Lighthouse's Image Size Savings warning uses 100px width as the base to calculate saved size, instead of 300px:

| Resource Size | Potential Savings |
|--------------- | ------------------|
| 101.3 KB           | 90.7 KB                |

#### What is the expected behavior?

Lighthouse, when making this judgement, should use the 3x DPI of its own simulated mobile screen as the base savings calculation.

If I misunderstand how to implement sizes and srcset, I apologize, and would be very happy to see an example that works.

At the moment, this is leading us to simply drop srcset entirely, while we understand it's supposed to be the right thing to use for web standards going forward?

#### Environment Information
* Affected Channels: DevTools, web.dev
* Lighthouse version: ?
* Chrome version: 88.0.4324
* Node.js version: v15
* Operating System: macOS Big Sur

**Related issues**
- https://github.com/GoogleChrome/lighthouse/issues/10802
- https://github.com/GoogleChrome/lighthouse/issues/11838

**Comment by patrickhulce** [comment]
Thanks for filing @PascalPixel! Two things I see that are going wrong here.

1. The images aren't actually displayed at 100px wide, they're displayed at ~74px wide. This seems like a mistake in the sizes definition.
2. The server isn't returning 320px *wide* images for the URL at `320w`, it's returning images that are 480px wide and ~320px *tall*. I don't know if this is a bug on the server or a mistake in the definition, but it seems odd to me :)

![image](https://user-images.githubusercontent.com/2301202/106627174-2484e900-653e-11eb-9c3e-f3d96a99f4fd.png)


When you combine these two things, we're looking at  `1 - 1 / (480 / 74 * 3) ^ 2 ~= 80%` wasted pixels even after you factor a DPR of 3 into the mix. The 90% number might be a slightly different image than the screenshot here, but the ballpark certainly seems correct from my investigation.

**Comment by PascalPixel** [comment]
The issue was indeed just a simple double `?` to start parameters! Fixed! Thank you Patrick!
