### ISSUE TITLE
An audit that warns if lazy-loaded images are rendered above the fold

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/lighthouse#12031]
Images that are rendered above the fold should not be lazy-loaded. Harry Roberts has [shared](https://twitter.com/csswizardry/status/1346477682544951296) a manual method for detecting this mistake (giving lazy-loaded images a red outline and then checking if any such images are rendered above the fold). It would be useful if Lighthouse performed this check.

**Comment by patrickhulce** [comment]
Thanks for filing @simevidas, neat idea! Would you be willing to answer the [new audit request questions](https://github.com/GoogleChrome/lighthouse/blob/master/docs/new-audits.md#process-for-creating-a-new-audit)?

**Comment by patrickhulce** [comment]
We're going to tackle part of this in https://github.com/GoogleChrome/lighthouse/issues/12785 🎉
