### ISSUE TITLE
links not crawlable warning when no href on an anchor

### ISSUE THREAD

**Issue by dbquarrel** [GoogleChrome/lighthouse#12030]
#### Provide the steps to reproduce
1. Run LH on yuhindo.com
  

#### What is the current behavior?

SEO rating is 93, it seems all related to "links are not crawlable" errors.

#### What is the expected behavior?

The <a> element is ANCHOR, it is not by definition a hyperlink element so should not be treated as such unless HREF is present. It is not a link element, it is an anchor element. 

ANCHOR properly refers to either the *start* (contains HREF) or a *destination* of a link (no HREF). Lighthouse assumes that it is always for the start of a link.

Reference: https://www.w3.org/MarkUp/1995-archive/Elements/A.html

Destination anchors of the form:

    <a id=start>

Lighthouse is treating these as origin links and complaining they are not crawlable, and then docking the SEO score as a result. 

Correct behavior is:

1. call these anchors and not links
2. check if HREF is present, if there is none it is a destination and should be ignored
3. if HREF is present, then it is an origin and can be checked and processed if there are errors or the HREF is not reachable

"HREF on anchor element cannot be followed" is more correct but I am knowingly being pedantic on this. However the destination anchors should definitely not raise errors and count against SEO score which is the issue at hand.

#### Environment Information
* Affected Channels: lr
* Lighthouse version: 6.3.0
* Chrome version: 87.0.4280.88 (Official Build) (x86_64)
* Node.js version: n/a
* Operating System: macOS Big Sur

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @dbquarrel! This pattern is already supported exactly as you describe but for anchors that use the more common `name` attribute as a link target instead of `id`. CC @avgp if there is any reason that `id` should continue to be excluded or if Lighthouse should treat it similarity to `name` as @dbquarrel suggests.

The distinction between anchor and link is well known to this audit and goes through several checks before judging that its most likely a mistaken link rather than a destination anchor.

> check if HREF is present, if there is none it is a destination and should be ignored

This would defeat the purpose of the audit. The whole point here is to catch the mistaken use of `onclick="window.open`, forgotten `href` attributes, and other such patterns that are accidental uncrawlable links. 

See https://github.com/GoogleChrome/lighthouse/blob/5c32e645d4cee10731cd8cd20f3b65cb41341ea6/lighthouse-core/test/audits/seo/crawlable-anchors-test.js#L41 for the WAI behaviors if you're curious.

**Comment by dbquarrel** [comment]
Also, in this case it is wrong in terms of the example site which is 
coded correctly.

It's a wrong approach in terms of understanding the HTML spec.

No correct and functional code should be flagged as wrong.

So, I understand the desire to catch broken links, but the word is 
"overzealous" when the desire to correct mistakes falls into flagging 
code that matches the spec as bad code. You need to ramp that down somehow.

You can make it a user option to go aggressive on link hunting.

Most importantly, is the attitude of the project one that overlaps and 
attacks good code everywhere with the idea of making sure it can get 
more mistakes? You can imagine if that is adopted as an approach 
everywhere. Nobody would use the tool in the end because of too many 
false positives.

Doctors don't do that.

First rule is: do no harm.

Been like that for 2,800 years and there is a good reason it stuck 
around as a model.

- darcy

**Comment by dbquarrel** [comment]
https://www.w3.org/TR/html401/struct/links.html#h-12.2.3

In HTML4 at least id and name are interchangeable.

Discussion here from html5:

https://stackoverflow.com/questions/484719/should-i-make-html-anchors-with-name-or-id

HTML5 looks preferentially at "id" before "name".

HTML5 also says that the decision of what kind of anchor you are looking 
at should be based only on presence of href or not href. So if href is 
missing you can't assume it's a bad link and a mistake and then lower 
scores.

It's correct syntax and correct use and it functions as designed, so 
really it should be adopted to score it properly.

- darcy

**Comment by patrickhulce** [comment]
> No correct and functional code should be flagged as wrong.

This is fundamentally at odds with the concept of "best practices." If the only goal is to get something that works as spec'd then Lighthouse is definitely not the right tool to be using :)

The rest of the discussion is out of my hands. I've already cc'd the relevant SEO expert for whether this was an intentional decision to exclude `id` or whether it was an oversight. From my knowledge this seems like an oversight and we'll fix, but that's not really our call to make. We'll obviously respect whatever the real best practice is here in Lighthouse.

**Comment by dbquarrel** [comment]
>
> The distinction between anchor and link is well known to this audit 
> and goes through several checks before judging that its most likely a 
> mistaken link rather than a destination anchor.
>
>     check if HREF is present, if there is none it is a destination and
>     should be ignored
>
> This would defeat the purpose of the audit. The whole point here is to 
> catch the mistaken use of |onclick="window.open|, forgotten |href| 
> attributes, and other such patterns that are accidental uncrawlable links.
>

The purpose of the audit is to get people to write performant and 
correct code.

This sounds stubborn.

If you flag correct code as wrong, and you encourage people to use 
obsolete code in its place in order to pass your audit, you essentially 
have a bad audit.

The previous suggestion that "name" should be used in place of "id" 
raises html validation errors with w3c''s validator.*Warning*

#

: The |name| attribute is obsolete. Consider putting an |id| attribute 
on the nearest container instead.

Perhaps you should reconsider the position in spite of this being "well 
known" to you. It's arbitrary and in spite of your stated desire to find 
broken links, your ability to detect those is bad if it is generating 
errors on things coded to spec. Honestly it's kind entry level 
programmer stuff.

- darcy

**Comment by patrickhulce** [comment]
I'm sensing quite a bit of hostility Darcy, but I'm not sure more you want here. We've already requested that the author of the rules here to weigh in and I already agreed it's likely an oversight. Is there something specific you're upset about that hasn't already been done?

I'm happy to further explain how the advice of an ID attribute on the nearest container is consistent with the position we've taken, but for some reason I get the feeling it won't really matter ;)

**Comment by sidhunavtej** [comment]
I would like to optimize  index page 
reduce response times
some fonts issue
optimize images [not the property]
css

**Comment by dontliem1** [comment]
Sooo... any news on this @connorjclark?

Sometimes you have link to homepage wrapping logo in the header of site, or an active link in navigation, and you don't want it to be active now, but do want to keep semantics that it would become a link. So the easiest and absolutely [valid](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) way is to take away it's `href`.

**Comment by amalitsky** [comment]
Still an issue, folks. IMO `id` support needs to be added.

cc @AVGP

**Comment by dgnemo** [comment]
Can we reopen this issue?

**Comment by cosmocatalano** [comment]
I would also like to re-open this issue

**Comment by adamraine** [comment]
I was able to confirm the SEO impact of anchors w/ @AVGP. `<a id="something">` *does not* have SEO impact so we should account for this.

**Comment by Hibrix-net** [comment]
> Having the same issue with Lighthouse and links. We use a href links for some navigation within the site but sometimes just disable them or remove the href value to make them disabled as they are then rendered as an inactive button/link. But Lighthouse still complains about this empty href even if you put disabled on the link and even aria-hidden="true" on it. Its not even tabbable in the layout so why is Lighthouse complaining about the empty href?
> 
> Yes I know this should likely be a button and not a link but it is very common to use a class="btn" all over the place in many applications, even if their href is basically navigating within the application itself and is not an actual link as per se.

It complaints because it is ambiguous and not really accessible. Even if its valid HTML, using an "a" as a placeholder will imply more let's say "explanations" to understand the final intention.
So, just put a role="button" attribute in your "a" tag and the error will disappear.

Kind regards,
