### ISSUE TITLE
PROTOCOL ERROR

### ISSUE THREAD

**Issue by binsta** [GoogleChrome/lighthouse#12035]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: PROTOCOL_TIMEOUT
* Lighthouse version:
* Chrome version: 88.0.4324.104
* Node.js version:
* Operating System:Windows 10 
devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:454:772
**Related issues**

**Comment by jeancharlesamey** [comment]
Same error ? 👍 

`Protocol error (Page.getInstallabilityErrors): PWA not implemented in Opera
```
Channel: DevTools
Initial URL: https://marinaaisa.com/
Chrome Version: 87.0.4280.141
Stack Trace: Error: Protocol error (Page.getInstallabilityErrors): PWA not implemented in Opera
    at Function.fromProtocolMessage (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:539:617)
    at devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:448:341
````
Environment Information
Affected Channels: PROTOCOL_TIMEOUT
Lighthouse version:
Chrome version: 88.0.4324.104
Node.js version:
Operating System:Windows 10
devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:454:772
Related issues

**Comment by patrickhulce** [comment]
@jeancharlesamey that is not the same error. That error is telling you that Opera has explicitly disabled PWA functions that Lighthouse uses. You'll need to use a Chromium-based browser that doesn't disable necessary APIs in order to use Lighthouse.

**Comment by patrickhulce** [comment]
@binsta see #6512
