### ISSUE TITLE
Core Web Vital indicator: FID is not included?

### ISSUE THREAD

**Issue by ast-hao** [GoogleChrome/lighthouse#12037]
There are 3 indicators, CLS, LCP, FID in GSC>Core Web Vitals, but the FID is not in lighthouse. - I see TBT is said well correlated with FID.
Is there a reason and what's the difference of TBG & FID? Not sure if FID can be added in lighthouse.
Thanks.

**Comment by patrickhulce** [comment]
See https://web.dev/fid/#how-to-measure-fid :)

> FID is a metric that can only be measured in the field, as it requires a real user to interact with your page.

> FID requires a real user and thus cannot be measured in the lab. However, the Total Blocking Time (TBT) metric is lab-measurable, correlates well with FID in the field, and also captures issues that affect interactivity. Optimizations that improve TBT in the lab should also improve FID for your users.

**Comment by ast-hao** [comment]
Thank you @patrickhulce
