### ISSUE TITLE
Invalid image request: url is shorten and contains an ellipsis (...)

### ISSUE THREAD

**Issue by kptdobe** [GoogleChrome/lighthouse#12048]
#### Provide the steps to reproduce

1. Run LH on https://hlxsite-kptdobe.hlx.page/lcp.html

#### What is the current behavior?

The page is really simple and only contains one image: `https://lighthouse--theblog--adobe.hlx.page/hlx_a5361f1d1b8813389084556c9f6ab76af159f3ad.jpeg`

On our server access logs, we see a request coming in for image: `https://lighthouse--theblog--adobe.hlx.page/hlx_a5361f1d1b8813389084556c9f%E2%80%A6`. Decoded, this is `https://lighthouse--theblog--adobe.hlx.page/hlx_a5361f1d1b8813389084556c9f...` which is the shorten version of the url. 

"Something" on the Lighthouse side requests the url with the ellipsis and I do not know if this has an impact on the score computation.

#### What is the expected behavior?

All requests to the image should be valid.

#### Environment Information
* Lighthouse version: 6.3.0 (current online version)
* Chrome version: 88.0.4324.96 (Official Build) (x86_64)
* Operating System: macOS Version 10.15.7 (Build 19H114)

**Comment by patrickhulce** [comment]
Thanks for filing @kptdobe! This has been fixed in Lighthouse 7 in https://github.com/GoogleChrome/lighthouse/pull/11503 🎉
