### ISSUE TITLE
Pagespeed Insights fails to load video

### ISSUE THREAD

**Issue by Diklla** [GoogleChrome/lighthouse#12050]
#### Provide the steps to reproduce
1. Run LH via PSI on https://m.youtube.com/watch?v=14pb8t1lHws (https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fm.youtube.com%2Fwatch%3Fv%3D14pb8t1lHws)

#### What is the current behavior?
For the mobile results - the screenshot shows an error stating that "Your browser can't play this video"

#### What is the expected behavior?
Video loading and the preview image showing

#### Environment Information
* Affected Channels: PSI
* Lighthouse version: 6.3.0
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by connorjclark** [comment]
dupe #11413
