### ISSUE TITLE
PageSpeed Insights API: missing metrics from json response (loadingExperience)

### ISSUE THREAD

**Issue by Chatim94** [GoogleChrome/lighthouse#12055]
I am using **PageSpeed Insights API** to grab speed metrics of different websites and integrate the data to graphite,  I tried a query using the API it works for just one website for other websites i got a response json that not include the same information some information is just missing in **"loadingExperience"** object.

here is the response : 

`{
  "captchaResult": "CAPTCHA_NOT_NEEDED",
  "kind": "pagespeedonline#result",
  "id": "https://url",
  "loadingExperience": {
    "initial_url": "https://url"
  },
  "lighthouseResult": {
    "requestedUrl": "https://url`

**Comment by patrickhulce** [comment]
Thanks for filing @Chatim94!

`loadingExperience` in the PSI API is the field data from the Chrome UX report and not part of the lighthouse result. Only the most popular URLs will have loading experience data available in the Chrome UX report. Read more in the [docs](https://web.dev/chrome-ux-report-api/).
