### ISSUE TITLE
PageSpeed Insights lab data erroneously showing CLS and LCP delays compared to cli, dev tools, performance in dev tools, webpagetest, and chrome web vitals extention

### ISSUE THREAD

**Issue by bemyhre** [GoogleChrome/lighthouse#12053]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### What is the current behavior?
I run https://www.bowlofdelicious.com/ through GPSI and encounter the following

![image](https://user-images.githubusercontent.com/5705561/107033150-7f0a8900-677a-11eb-8a92-e3d716e7a352.png)

#### What is the expected behavior?

When I run it through the cli tool, I see the following :

![image](https://user-images.githubusercontent.com/5705561/107033222-9a759400-677a-11eb-9388-c047c1d18e06.png)

I get similar results if I run it right in the chrome dev tools or performance tab. I tracked down where the page was shifting (font loading) and put an important style element in the header with a browser safe font to test... it eliminated nearly any of the registering LS in the performance tab, but the PSI Lab Data score didn't improve. I had to remove that element. 

If I watch the filmstrip in preferences or webpagetest or run it through a third party tool like https://defaced.dev/tools/layout-shift-gif-generator/, the CLS in PSI just does not match up. Similarly with LCP. 

It just seems like PSI lab data is flat out wrong for some pages (I test multiple pages per day)

#### Environment Information
* Affected Channels: 
https://developers.google.com/speed/pagespeed/insights/
* Lighthouse version:
It does look like PSI is not using the latest version?
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by maryfranharper** [comment]
> #### Provide the steps to reproduce
> 1. Run LH on
> 
> #### What is the current behavior?
> I run https://www.bowlofdelicious.com/ through GPSI and encounter the following
> 
> ![image](https://user-images.githubusercontent.com/5705561/107033150-7f0a8900-677a-11eb-8a92-e3d716e7a352.png)
> 
> #### What is the expected behavior?
> When I run it through the cli tool, I see the following :
> 
> ![image](https://user-images.githubusercontent.com/5705561/107033222-9a759400-677a-11eb-9388-c047c1d18e06.png)
> 
> I get similar results if I run it right in the chrome dev tools or performance tab. I tracked down where the page was shifting (font loading) and put an important style element in the header with a browser safe font to test... it eliminated nearly any of the registering LS in the performance tab, but the PSI Lab Data score didn't improve. I had to remove that element.
> 
> If I watch the filmstrip in preferences or webpagetest or run it through a third party tool like https://defaced.dev/tools/layout-shift-gif-generator/, the CLS in PSI just does not match up. Similarly with LCP.
> 
> It just seems like PSI lab data is flat out wrong for some pages (I test multiple pages per day)
> 
> #### Environment Information
> * Affected Channels: 
>   https://developers.google.com/speed/pagespeed/insights/
> * Lighthouse version:
>   It does look like PSI is not using the latest version?
> * Chrome version:
> * Node.js version:
> * Operating System:
> 
> **Related issues**

**Comment by maryfranharper** [comment]
how do i fix this

**Comment by adamraine** [comment]
Hi @maryfranharper thanks for filing!

It looks like the differences in LCP might just be from normal variance while testing the page. As for CLS, I found that throttling the page in the performance panel yielded different layout shifts. It seems like long processing times on slower CPUs may introduce additional layout shifts.

LH run with DevTools throttling (4x CPU throttling):
![Screen Shot 2021-02-08 at 1 38 27 PM](https://user-images.githubusercontent.com/6752989/107266166-2570bb80-6a13-11eb-9519-00d3603c4976.png)

Check out our variability docs for more info https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md.
