### ISSUE TITLE
Lighthouse hangs when running asp.net project on localhost using https

### ISSUE THREAD

**Issue by GaryWayneNelson** [GoogleChrome/lighthouse#12063]
Environment: Microsoft Visual Studio Professional 2019
Version 16.8.3 ASP.NET in localhost.

Lighthouse works fine auditing Asp.Net projects  as long as I use http. 

If I create a project using https it invariably hangs. This only happens in localhost. If I upload the project to the server it works fine.

To test this I created a new project with just one html button and no code. Lighthouse fails to finish the audit.

This happens with lighthouse both in Chrome and Edge.

**Comment by adamraine** [comment]
I'm not able to reproduce this on my machine.

It's difficult to diagnose this issue without access to your test environment. Could you try running LH from the CLI and provide a log of the output?

**Comment by adamraine** [comment]
Make sure you have the `http` url set up when testing. LH may be hanging because it is trying to check if the `http` url redirects to the `https` url.

**Comment by GaryWayneNelson** [comment]
Yes, I believe you are right. Just a question. How do I set it up so that the http redirects to https?

**Comment by adamraine** [comment]
I don't know off hand, but hopefully this will be helpful:
https://pleasantsolutions.com/info/pleasant-password-server/a-install/redirect-http-requests-to-https/redirect-from-http-to-https-iisexpress
