### ISSUE TITLE
Вoes not pass the full list of tests.

### ISSUE THREAD

**Issue by jicalad** [GoogleChrome/lighthouse#12061]
I cannot test the site through the built-in tool in the browser Lighthouse, it constantly gives an error: sigill. But if you test on only one parameter, the test passes. The site with which the error https://amulex.ru
What could be the mistake? 
![Снимок экрана от 2021-02-08 17-20-11](https://user-images.githubusercontent.com/78733521/107231948-ee5dd280-6a31-11eb-85de-add17c84f12c.png)

**Comment by connorjclark** [comment]
Works on my end here in 2022 :)
