### ISSUE TITLE
minification-estimator reports incorrect results 

### ISSUE THREAD

**Issue by EYHN** [GoogleChrome/lighthouse#12060]
#### Provide the steps to reproduce

Use the following javascript code and run lighthouse, it will report that javascript is not minified.

```
switch(true){case/^hello!/.test("hello!"):document.write("///<any content>");}
```
  

#### What is the current behavior?

The javascript is minified.

#### What is the expected behavior?
<img width="723" alt="图片" src="https://user-images.githubusercontent.com/13579374/107198291-e309a780-6a2f-11eb-9f07-37c232294188.png">

#### Environment Information
* Affected Channels:  DevTools
* Lighthouse version: 87.0.4280.88

#### Reason

In `lighthouse/lighthouse-core/lib/minification-estimator.js` the function named `hasPunctuatorBefore`.
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/minification-estimator.js#L21-L35

`hasPunctuatorBefore` function incorrectly identifies the "/" after "case" as a division, not a regular expression. Then the first "/" in the string as the end of the regular expression, and the next "//" as the beginning of the comment , causing all the code after that to be treated as a comment.

#### Possible Solution

Add keyword `case` to the `PUNCTUATOR_REGEX`

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/minification-estimator.js
```diff
// https://www.ecma-international.org/ecma-262/9.0/index.html#sec-punctuators
// eslint-disable-next-line max-len
- const PUNCTUATOR_REGEX = /(return|{|\(|\[|\.\.\.|;|,|<|>|<=|>=|==|!=|===|!==|\+|-|\*|%|\*\*|\+\+|--|<<|>>|>>>|&|\||\^|!|~|&&|\|\||\?|:|=|\+=|-=|\*=|%=|\*\*=|<<=|>>=|>>>=|&=|\|=|\^=|=>|\/|\/=|\})$/;
+ const PUNCTUATOR_REGEX = /(return|case|{|\(|\[|\.\.\.|;|,|<|>|<=|>=|==|!=|===|!==|\+|-|\*|%|\*\*|\+\+|--|<<|>>|>>>|&|\||\^|!|~|&&|\|\||\?|:|=|\+=|-=|\*=|%=|\*\*=|<<=|>>=|>>>=|&=|\|=|\^=|=>|\/|\/=|\})$/;
const WHITESPACE_REGEX = /( |\n|\t)+$/;

/**
 * Look backwards from `startPosition` in `content` for an ECMAScript punctuator.
 * This is used to differentiate a RegExp from a divide statement.
 * If a punctuator immediately precedes a lone `/`, the `/` must be the start of a RegExp.
 *
 * @param {string} content
 * @param {number} startPosition
 */
function hasPunctuatorBefore(content, startPosition) {
  for (let i = startPosition; i > 0; i--) {
    // Try to grab at least 6 characters so we can check for `return`
    const sliceStart = Math.max(0, i - 6);
    const precedingCharacters = content.slice(sliceStart, i);
    // Skip over any ending whitespace
    if (WHITESPACE_REGEX.test(precedingCharacters)) continue;
    // Check if it's a punctuator
    return PUNCTUATOR_REGEX.test(precedingCharacters);
  }

  // The beginning of the content counts too for our purposes.
  // i.e. a script can't start with a divide symbol
  return true;
}
```

**Comment by EYHN** [comment]
I have created a repo to reproduce this bug, if needed please download the file and open it with a local http 1.x server.
Note: I found that in the http2 protocol, lighthouse does not report this issue.

https://github.com/EYHN/lighthouse-error-reproduced

**Comment by patrickhulce** [comment]
Thanks very much for filing the repro and the deep investigation @EYHN!

Seems like you've already done quite a bit of work here, would you be interested in closing the loop with a PR for the test case you outline and your fix? 😃

**Comment by EYHN** [comment]
My pleasure, I will submit the pr as soon as possible, probably tomorrow. By the way my time zone is utc+8.
