### ISSUE TITLE
Improve generalized/sourcemap fetcher

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#12070]
https://github.com/GoogleChrome/lighthouse/pull/9459 landed our generalized fetcher (with an iframe). 

We may have some areas where it can be improved.

**CSP sensitivity**.. I didn't test, but I believe a `frame-src` directive would introduce problems for this technique. 

**content-type sensitivity**. In #12064 we see that if a map is served with `application/octet-stream` it'll trigger a user-visible download while Lighthouse is fetching it. DevTools, meanwhile, doesn't have that behavior when it fetches.

## devtools generalized loading…

There's been some updates.. 

Sigurd [added the `Network.loadNetworkResource`](https://chromium-review.googlesource.com/c/chromium/src/+/2027416) protocol method for sourcemaps. He recently [added metrics](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2622195) to record how various load attempts succeed/fail. 

AFAICT, there are currently **four** different types of fetch attempts... you can see them in  [`PageResourceLoader.js`'s](https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/front_end/sdk/PageResourceLoader.js) `_dispatchLoad()` in the devtools source.

Here's the [umbrella crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=1069378).

You can also see some of this in the new "Developer Resources" drawer panel in devtools:

![image](https://user-images.githubusercontent.com/39191/107433930-e445dd80-6ade-11eb-924b-741dc5abd532.png)

**Comment by adamraine** [comment]
> CSP sensitivity.. I didn't test, but I believe a `frame-src` directive would introduce problems for this technique

It does https://github.com/GoogleChrome/lighthouse/pull/12044#issuecomment-788274938

**Comment by connorjclark** [comment]
`Network.loadNetworkResource` was added in M87, stable is currently M88. We might consider checking the chrome version and using the current implementation as a fallback for awhile.

**Comment by brendankenny** [comment]
> `Network.loadNetworkResource` was added in M87, stable is currently M88. We might consider checking the chrome version and using the current implementation as a fallback for awhile.

What are y'all thinking for a timeline for this? Stable is now m89, earliest #12199 could land is m91, so the main reason to hold back is CLI users using an old stable Chrome/specific Chromium build?

**Comment by connorjclark** [comment]
yea, exactly. It seems people using docker builds are eternally a few more versions behind than you'd expect..

**Comment by paulirish** [comment]
> **content-type sensitivity**. In #12064 we see that if a map is served with application/octet-stream 

https://proxx.app/ also reproduces this behavior.

**Comment by connorjclark** [comment]
We're using the new protocol method to fetch resources now, but we need to keep the old one around for LR: #13006

Let's track in #13394 – next month we should be able to drop the iframe fetcher completely.
