### ISSUE TITLE
networkUserAgent not being set in some cases.

### ISSUE THREAD

**Issue by Bryze** [GoogleChrome/lighthouse#12072]
On some urls that are being tested for page speed via lighthouse (in docker), following is the snippet of the JSON being returned
```
{
	"userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/88.0.4324.150 Safari/537.36",
	"environment": {
		"networkUserAgent": "",
		"hostUserAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/88.0.4324.150 Safari/537.36",
		"benchmarkIndex": 1450,
		"credits": {}
	}
}
```
this is happening, post explicitly setting the user agent by `emulatedUserAgent` 

Here's a sample json where it prints correctly,
```
{
	"userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/88.0.4324.150 Safari/537.36",
	"environment": {
		"networkUserAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Safari/537.36 Chrome-Lighthouse",
		"hostUserAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/88.0.4324.150 Safari/537.36",
		"benchmarkIndex": 1424,
		"credits": {
			"axe-core": "4.1.1"
		}
	}
}
```

Any leads as to what is going wrong?

Here is the gist to the source codes of the two webpages generated by lighthouse
https://gist.github.com/Bryze/2c36f2edb289d35dd6a44434befef050

**Environment Details**
Lighthouse: 7.0.1
Node: 12.20.1

**Comment by connorjclark** [comment]
Can you run again with `-GA` and upload the contents of `latest-run`?

**Comment by Bryze** [comment]
Here is the gist to the docker logs 
(updated two sets which I found were problematic)
https://gist.github.com/Bryze/55d97aa29ee0e67056e4c739682c661b

**Comment by connorjclark** [comment]
> Can you run again with -GA and upload the contents of latest-run?

I'll need this information to help you.

**Comment by brendankenny** [comment]
Going to close because there's been no movement on this issue. If you do want to pursue this, please comment with the requested information and we can re-open.
