### ISSUE TITLE
When will an updated version of Lighthouse ship to PageSpeed Insights?

### ISSUE THREAD

**Issue by kurttomlinson** [GoogleChrome/lighthouse#12087]
PageSpeed Insights currently reports that it is using version 6.3.0 of Lighthouse.

Lighthouse version 7.0.1 was released on 2021-01-26 (17 days ago).
Lighthouse version 7.0.0 was released on 2020-12-17.
Lighthouse version 6.5.0 was released on 2020-12-01.
Lighthouse version 6.4.0 was released on 2020-09-30.

All of these Lighthouse releases say "We expect this release to ship ... to PageSpeed Insights within 2 weeks."

It has been months since the last Lighthouse update in PageSpeed Insights. When will an updated version of Lighthouse ship to PageSpeed Insights?

**Comment by connorjclark** [comment]
pretty soon. We had unexpected regressions. We're hopeful of a release within the next week.

**Comment by kurttomlinson** [comment]
I see. Thanks for the update!

**Comment by kurttomlinson** [comment]
It looks like an updated Lighthouse landed in PageSpeed Insights recently. Thanks!

![image](https://user-images.githubusercontent.com/1914753/108865842-a1e1cd80-75c1-11eb-8ff9-060b3f7278fb.png)
