### ISSUE TITLE
Best practices problem (Serves images with low resolution)

### ISSUE THREAD

**Issue by CjrRbt** [GoogleChrome/lighthouse#12094]
There is a problem with Best Practices test from Lighthouse. The report say that image is low resolution even though it have fixed size. Check the print screen image.

![RbtBet-pic5](https://user-images.githubusercontent.com/79173904/108130472-64a8a780-70b8-11eb-82e6-5280ffd80833.jpg)

* Lighthouse version: 6.4.0 
* Chrome version: 88.0.4324.182 (Official Build) (64-bit)
* Operating System: Win 10
* Only visible on Mobile test
* It can be reproduced on this simple page: RbtBet.com/simulation/value-bets

**Comment by adamraine** [comment]
This is intended behavior for a high DPR. See https://github.com/GoogleChrome/lighthouse/issues/10802.
