### ISSUE TITLE
SVG elements below the fold affect CLS when running from dev tools

### ISSUE THREAD

**Issue by idanen** [GoogleChrome/lighthouse#12093]
SVGs elements below the fold are causing (invisible) layout shifts, that hurts CLS score.

#### Steps to reproduce
1. Run LH on https://svg-cls.multiscreensite.com/
2. Check CLS - over 0.4, though no visible layout shift in screenshots
3. Run LH on https://no-svg-cls.multiscreensite.com/ (same site but without SVG widget below the fold)
4. Check CLS - consistently 0
5. On PageSpeed Insights, CLS is 0 on both (expected behavior)

Running performance audit on the https://svg-cls.multiscreensite.com/ site marks the svg element as the one causing layout shift, although it's out of view:
![svg-cls-below-fold](https://user-images.githubusercontent.com/1687893/108059945-e66be700-705e-11eb-8d36-9a2401fa7b1c.jpg)
![svg-cls](https://user-images.githubusercontent.com/1687893/108059420-25e60380-705e-11eb-97dc-4ffe2e666749.jpg)

#### What is the current behavior?

Lighthouse checks all SVGs on the page for CLS calculations

#### What is the expected behavior?

Lighthouse should not take out of view SVGs into CLS considerations

#### Environment Information
* Lighthouse version: 6.4.0
* Chrome version: 88.0.4324.150
* Operating System: MacOS

**Comment by adamraine** [comment]
I can reproduce this, it appears to be a bug in Chrome stable (M88).

Testing the page in Canary gives a CLS of 0, so it looks like this has been fixed in M90.

**Comment by mohamedkofta** [comment]
> تتسبب عناصر SVG الموجودة أسفل الجزء المرئي في حدوث تحولات (غير مرئية) في التخطيط ، مما يضر بنتيجة CLS.
> 
> #### خطوات التكاثر
> 1. قم بتشغيل LH على https://svg-cls.multiscreensite.com/
> 2. تحقق من CLS - أكثر من 0.4 ، على الرغم من عدم وجود تغيير واضح في التخطيط في لقطات الشاشة
> 3. قم بتشغيل LH على https://no-svg-cls.multiscreensite.com/ (نفس الموقع ولكن بدون أداة SVG أسفل الجزء المرئي من الصفحة)
> 4. تحقق من CLS - باستمرار 0
> 5. في PageSpeed ​​Insights ، يكون CLS صفرًا في كليهما (السلوك المتوقع)
> 
> يؤدي إجراء تدقيق الأداء على موقع https://svg-cls.multiscreensite.com/ إلى تحديد عنصر svg باعتباره العنصر الذي يتسبب في تغيير التخطيط ، على الرغم من أنه خارج العرض:
> ![svg-cls-under-fold](https://user-images.githubusercontent.com/1687893/108059945-e66be700-705e-11eb-8d36-9a2401fa7b1c.jpg)
> ![svg- cls](https://user-images.githubusercontent.com/1687893/108059420-25e60380-705e-11eb-97dc-4ffe2e666749.jpg)
> 
> #### ما هو السلوك الحالي؟
> يتحقق Lighthouse من جميع SVGs على الصفحة لحسابات CLS
> 
> #### ما هو السلوك المتوقع؟
> لا يجب على Lighthouse إخراج SVGs من العرض إلى اعتبارات CLS
> 
> #### معلومات البيئة
> * Lighthouse version: 6.4.0
> * Chrome version: 88.0.4324.150
> * Operating System: MacOS
