### ISSUE TITLE
When I run lighthouse...

### ISSUE THREAD

**Issue by wikieeyoyo** [GoogleChrome/lighthouse#12090]
**Summary**

![image](https://user-images.githubusercontent.com/12537879/107871620-34a5ac80-6ede-11eb-9aa6-56115a6eab6c.png)

**Comment by patrickhulce** [comment]
Thanks for filing @wikieeyoyo!

What happens if you run Lighthouse with the flag `--hostname=127.0.0.1`?

**Comment by wikieeyoyo** [comment]
I'm sorry but the same as above.

**Comment by patrickhulce** [comment]
With exactly the same output? Then the flag wasn't used. At the very least you should see the error message of the failed connection change. How *exactly* are you invoking Lighthouse?

The general debugging process here is to get Chrome to work without Lighthouse involved, then add in Lighthouse once you're sure that's working.

Intermediate steps:

- Run Chrome with `--remote-debugging-port=9222`, try to visit `localhost:9222` in a browser.
    - If that doesn't work, you've got a Chromium problem.
    - If that does work, run Lighthouse `lighthouse https://example.com --port=9222 --hostname=127.0.0.1`.
        - If that works, you've got a bad CHROME_PATH, set it to the Chrome that worked in the first step.
        - If that doesn't work, we can look into a potential lighthouse bug with [the entire template filled out](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) and try to repro on another machine.

Other things to check, make sure you're using stable or newer Chrome version.

**Comment by wikieeyoyo** [comment]
Thank you so much, it proved to be a Chromium problem.
