### ISSUE TITLE
Lighthouse requests truncated URLs with '…´ %E2%80%A6

### ISSUE THREAD

**Issue by rcanavan** [GoogleChrome/lighthouse#12102]
#### Provide the steps to reproduce
1. Run LH on http://unimportant-site.com/lighthousetest.html

#### What is the current behavior?

During at least one run, Lighthouse requests URLs that are truncated, apparently after 74 characters (protocol + hostname + path), but with '…' appended (encoded as %E2%80%A6 in the request). This results in a flurry of 404 responses, and, presumably, a questionable lighthouse result. We have observed this with various sites operated by different customers on different platforms on different domains. The site at http://unimportant-site.com/lighthousetest.html is an entirely static copy of one customer site and does not contain '…' as far as I can tell.

Example of one untruncated URL, as well as the truncated version, as requested by Lighthouse on the test site given above, and the (anonymized, but correct length) customer's URL:

```
http://unimportant-site.com/media/image/50/ae/48/Stussy-Speckled-Wool-Low-Pro-Cap-Rust_200x200.jpg
http://unimportant-site.com/media/image/50/ae/48/Stussy-Speckled-Wool-Low-%E2%80%A6
https://www.xxxx-xxxxx.com/media/image/50/ae/48/Stussy-Speckled-Wool-Low-P%E2%80%A6
```

#### What is the expected behavior?

No unsolicited modification of URLs.

#### Environment Information

* Affected Channels: DevTools, PageSpeed Insights
* Lighthouse version: 6.3.0
* Chrome version: 88.0.4324.150
* Operating System: Ubuntu 20.10, others
* Lighthouse User-Agent: Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Mobile Safari/537.36 Chrome-Lighthouse
* source IPs: 66.249.81.22, 66.249.93.74 etc.

**Comment by connorjclark** [comment]
Fixed in #11503. PSI is pending a release, and this is fixed in canary Chrome.
