### ISSUE TITLE
Problem with PSI

### ISSUE THREAD

**Issue by Sternfeldguy** [GoogleChrome/lighthouse#12108]
Hi all,

I've got an issue with Google Page Speed Insights and I would be happy for your help.

This is my website: https://www.stickyland.co.il/ 

since yesterday, every time that I check it with Google Page Speed Insights I've got this message:

**Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)** 

You can see this message in real-time at[ this link ](https://developers.google.com/speed/pagespeed/insights/?en&url=https%3A%2F%2Fwww.stickyland.co.il%2F&tab=desktop)

The strangest part is that on Google lighthouse via chrome dev tool it's working.  

PSI and Google lighthouse should be the same thing, isn't it? 

Please help me to figure out this issue..

Thanks!

**Comment by connorjclark** [comment]
Works for me, is it still an issue for you?

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.stickyland.co.il%2F&tab=desktop
