### ISSUE TITLE
Performance returns null most of the time.

### ISSUE THREAD

**Issue by wafendy** [GoogleChrome/lighthouse#12101]
![Screenshot 2021-02-18 at 5 26 03 PM](https://user-images.githubusercontent.com/387000/108348356-a81c2680-721c-11eb-8b63-7e1b76808f3d.png)
![Screenshot 2021-02-18 at 5 25 49 PM](https://user-images.githubusercontent.com/387000/108348378-ae120780-721c-11eb-9e3f-22448061e135.png)

#### Provide the steps to reproduce
1. I created a public repo to help reproduce the problem https://github.com/wafendy/aws-lambda-lighthouse-docker

#### What is the current behavior?
Sometimes Performance will return a score, most of the time it will not. 

#### What is the expected behavior?

Expected behavior is Performance will always return a score

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 7.1.0
* Chrome version: 90.0.4403.0
* Node.js version: 12
* Operating System: AWS Lambda

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @wafendy!

Lambda isn't a supported environment. Some of Lighthouse might work and some community packages attempt to make it more stable, but we can't commit to ensuring everything works as expected, see [Run on Adequate Hardware docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md#run-on-adequate-hardware).
