### ISSUE TITLE
Use HTTP/2 audit on pagespeed insights

### ISSUE THREAD

**Issue by peixotorms** [GoogleChrome/lighthouse#12113]
Testing any site, including google for example, returns the "Use HTTP/2" opportunity.
This wasn't there yesterday, so some new code must have been deployed for the past 24h.
Not sure if regional, I'm testing from europe.

`https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fcloud.google.com%2F&tab=mobile`

`https://i.imgur.com/1mzACLL.png`

**Comment by connorjclark** [comment]
It's a bug, we're releasing a fix soon.

**Comment by connorjclark** [comment]
It's fixed now.

**Comment by paulirish** [comment]
@peixotorms thanks for reporting this!  always appreciate the extra pair of eyes.

we updated PSI to LH 7.1 today. release notes here: https://developers.google.com/speed/docs/insights/release_notes?hl=en-US

**Comment by peixotorms** [comment]
Thanks for the release notes and fixing!

**Comment by jsanz1209** [comment]
It seems the bug goes on happening.
