### ISSUE TITLE
http2 works in browser, but lighthouse web ui reports http2 is not working.

### ISSUE THREAD

**Issue by iMakedonsky** [GoogleChrome/lighthouse#12110]
http2 works in browser, but lighthouse web ui reports http2 issues for static assets.
Http2 shows correctly when I run LH tests from chrome dev tools
#### Provide the steps to reproduce
1. Run LH test on https://www.padsplit.com

#### What is the current behavior?
http2 issues
#### What is the expected behavior?
No http2 issues

See screenshot: https://gyazo.com/cea9ba218474edf2bc05c9b0320f47c3

#### Environment Information
* Affected Channels: web ui
* Lighthouse version: 7.1.0
* Chrome version: 
Google Chrome | 88.0.4324.182 (Official Build) (x86_64)
Revision | 73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}
OS | macOS Version 11.2.1 (Build 20D74)

**Comment by patrickhulce** [comment]
Thanks for filing @iMakedonsky! This is a known issue captured by https://github.com/GoogleChrome/lighthouse/issues/7326. It requires changes to PSI infrastructure not a part of this repo. Feel free to follow that issue for updates :)
