### ISSUE TITLE
Telling different results - Lighthouse vs. GSC

### ISSUE THREAD

**Issue by ast-hao** [GoogleChrome/lighthouse#12121]
Recently I run lighthouse on batch URLs, but seems getting interesting result. (Focusing on Performance part, especially 3 core web vital metrics)
Lighthouse results tell us the Desktop performance is better than Mobile, however, when I check in GSC, it tells reverse result.

Following is one sample of single report on same tested URL:
![image](https://user-images.githubusercontent.com/77451683/108732713-3554c900-7504-11eb-8235-3d1ee2228b8c.png)

Following chart is the aggregated average Core Web Vital indicators result includes all tested URLs:
![image](https://user-images.githubusercontent.com/77451683/108733048-806edc00-7504-11eb-9ffa-09ff6948c546.png)

from above 2 screens, seems they are telling the mobile performances on core web vital metrics are worse.

Following is the screen capture in GSC, which tells we have better result on mobile version.
![image](https://user-images.githubusercontent.com/77451683/108733305-c3c94a80-7504-11eb-9e1e-84ccedb59746.png)

Any ideas?
Thank you & have a safe day.

**Comment by connorjclark** [comment]
You're comparing two different things here.

1) The Lighthouse score is a 0-100 indicator of how good a site is, based on a synthetic load of the page. For mobile, Lighthouse uses a more strict grading curve, so mobile scores will _always_ be worse. (big assumption: the same site is served to mobile and desktop user agents)
2) The GSC graphs are triaging real user traffic based on form factor + "how good was it" (3 different levels). This can tell you where your attention might be best spent. In this case, traffic between mobile and desktop is pretty evenly split, and the three buckets are nearly similar, so it doesn't suggest one or the other to give extra focus to.

In your case, using the desktop or the mobile Lighthouse report is fine, the problems they identify should improve the graph you see in GSC when resolved.

**Comment by ast-hao** [comment]
Thanks for reply connorjclark.
I think it may because GSC and Lighthouse are using different way to emulate on mobile test, as you mentioned, lighthouse may use more strict grading curve, e.g. running settings, such as Network throttling 
Mobile:  Network throttling 150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated) 
Desktop:  Network throttling 40 ms TCP RTT, 10,240 Kbps throughput (Simulated) 


About the score, 
according to what I can read, I think Lighthouse and GSC are using same scoring method.
![image](https://user-images.githubusercontent.com/77451683/108792856-a45c0d00-7558-11eb-8fdf-19825dcac604.png)


Lighthouse is giving 0-100 grading upon the test result of how many seconds on the TBT, CLS, LCP. Let's say 4.1s on LCP, then the score will be in 50-89, which I highlight with color "Orange" in OP.
GSC is using similar way, but just giving "Needs improvement" - Orange level.

As a result,  they shall be matched unless they are giving different score to same time result, e.g. LCP 3.9s, Lighthouse is giving under 90 but GSC is giving "Good", OR, GSC considers score 90 is "orange" when Lighthouse considers "green", etc.

So, looking at the whole picture, comparing Mobile and Desktop, if there are lower score in Mobile than Desktop, it means more URLs fall into score 0-49 in Mobile test, then, there would be more URLs in "Poor" in GSC-Mobile than Desktop, which is different to OP.


> You're comparing two different things here.
> 
> 1. The Lighthouse score is a 0-100 indicator of how good a site is, based on a synthetic load of the page. For mobile, Lighthouse uses a more strict grading curve, so mobile scores will _always_ be worse. (big assumption: the same site is served to mobile and desktop user agents)
> 2. The GSC graphs are triaging real user traffic based on form factor + "how good was it" (3 different levels). This can tell you where your attention might be best spent. In this case, traffic between mobile and desktop is pretty evenly split, and the three buckets are nearly similar, so it doesn't suggest one or the other to give extra focus to.
> 
> In your case, using the desktop or the mobile Lighthouse report is fine, the problems they identify should improve the graph you see in GSC when resolved.

**Comment by connorjclark** [comment]
> GSC considers score 90 is "orange" when Lighthouse considers "green",

What do you mean GSC considers 90 to be orange?

**Comment by ast-hao** [comment]
> > GSC considers score 90 is "orange" when Lighthouse considers "green",
> 
> What do you mean GSC considers 90 to be orange?

Emm, you may consider to this as a whole:

> As a result, they shall be matched unless they are giving different score to same time result, e.g. LCP 3.9s, Lighthouse is giving under 90 but GSC is giving "Good", OR, GSC considers score 90 is "orange" when Lighthouse considers "green", etc.

To interpret that is:
"If LCP 3.9s, if LH is giving under 90 but GSC is giving "Good", OR any score 90 in LH is considered as "Green" in GSC, that's saying same result is giving different score/level in GSC and LH."
"But as long as above sample is giving same result in LH and GSC, then that shall not be the reason of why GSC and LH is telling different story (which is saying the reason may because they are using different way to simulate".

Sorry to make it hard to understanding...

**Comment by paulirish** [comment]
Yes.. Lighthouse desktop is giving you a better desktop score than a mobile score and GSC generally seems them differently.

Ultimately this comes down to the difference between lab and field. https://developers.google.com/web/fundamentals/performance/speed-tools#understanding_lab_vs_field_data

As you note, Lighthouse uses emulation under two different settings:

> Mobile: Network throttling 150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
> Desktop: Network throttling 40 ms TCP RTT, 10,240 Kbps throughput (Simulated)

However GSC is summarizing a bunch of field data. For each URL, GSC is using hundreds/thousands of measurements from real users brwosers in the field. And then on top of that, it's summarizing thousands of URLs together.

While the exact thresholds of <= X seconds == "good" may be similar, the way all this data is gathered is wildly different. 

---------

You shouldn't expect results from lab and field to match numerically. However after some changes, if you see significant improvement (or regression) in one (lab, for example), you should expect to also see it in the field (as the 28 day summary catches up).

What you should do is work on improving your desktop lighthouse score by implementing the suggestions. Lets say you brought an average lighthouse desktop score of 35 to a 70.. After that's deployed, (and the [28-day field data summary](https://tamethebots.com/blog-n-bits/monitoring-search-console-core-web-vitals) catches up), you should see changes in your GSC dashboards.

Good luck
