### ISSUE TITLE
Lighthouse/Chrome Web Vitals for Ads?

### ISSUE THREAD

**Issue by prathamesh-gharat** [GoogleChrome/lighthouse#12124]
I'm just sharing a case. I'm not from the "Ads" side of world so in case networks like AdSense already have some optimization practices and metrics in place then please point me to them.

Case: Clients & developers do all things possible to improve the PageSpeed/CWV score. But when it comes to ads, I do not see support for things like Next-gen image formats (WebP), minimize unused JS, etc.

For example; after getting a website PageSpeed score into 90s it's always the ads which hamper the score. It's a trade off between the Lighthouse recommendations & Ad revenue when trying to show even the small 300x50 ad above the fold.

The only solution which works in such cases is to not have ads on the 1st fold on mobile devices + lazy loading the ads (inject the scripts) on scroll event.

For these reasons, I think many would love to see a Lighthouse for Ads which would help advertisers optimize their creatives; and enable website owners to maintain an optimized website.

Note: This is not about how to load ads in an optimized way, but more about pushing the advertisers (or ad networks) to optimize their creatives & scripts.

**Comment by paulirish** [comment]
Checkout https://developers.google.com/publisher-ads-audits and https://developers.google.com/publisher-ads-audits/reference/

It's not lighthouse-scoped-for-ad-assets, but close. 


Also,  you can always run lighthouse on HTML page where the only content is an ad. So... that's always available. :)
