### ISSUE TITLE
CLI tries to launch a Chrome instance even when given a remote hostname

### ISSUE THREAD

**Issue by tkindy** [GoogleChrome/lighthouse#12137]
#### Provide the steps to reproduce
1. Run LH on any URL via the CLI, passing `--hostname` and `--port` to point at a remote Chrome instance
  

#### What is the current behavior?

Lighthouse launches a local Chrome instance, but ignores it and connects to the remote instance anyways. If this isn't possible because Chrome isn't installed (for example, in CI environments), the entire Lighthouse run crashes out.

#### What is the expected behavior?

Lighthouse doesn't launch a local Chrome instance (and fail the run if it isn't installed); it just connects to the remote instance.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 7.2.0
* Chrome version: N/A
* Node.js version: 14.15.4
* Operating System: macOS Catalina 10.15.7

**Related issues**

https://github.com/GoogleChrome/lighthouse/issues/2727

**Comment by tkindy** [comment]
Support for connecting to Chrome instances on remote hosts was added in #2728. However, while the parameter was added as a CLI argument, it appears the code path through `ChromeLauncher` was never tweaked to actually use the parameter, so it's silently ignored.

https://github.com/GoogleChrome/lighthouse/blob/fb18dfe70e89d752a46deabe2de8a21b414ceb7e/lighthouse-cli/run.js#L74-L79

**Comment by RegattaNick** [comment]
First time using LH as part of a CD pipeline, and this issue has hit me today, thought I was going mad, but glad to know it's not a PEBCAK. Any ideas about how to get this working in the interim?

**Comment by RegattaNick** [comment]
Looking at chrome launcher is it even possible to specify a hostname with chrome launcher?

**Comment by patrickhulce** [comment]
Thanks for filing @tkindy! 

No this issue is really somewhat unrelated to chrome-launcher, if a hostname other than localhost is used, then lighthouse shouldn't even be trying to launch Chrome.

AFAICT, lighthouse should still respect the hostname setting *but* you'll have a useless Chrome launched and sitting around on your localhost *as well* (and this might fail if Chrome can't be started on your machine).

https://github.com/GoogleChrome/lighthouse/blob/fb18dfe70e89d752a46deabe2de8a21b414ceb7e/lighthouse-core/index.js#L38-L45

Either way we'll want to fix that up on the lighthouse side.

**Comment by patrickhulce** [comment]
The new `isLikeLocalhost` method in #11766 should make this an easy fix if anyone is interested in a good first PR :D

**Comment by RegattaNick** [comment]
> (and this might fail if Chrome can't be started on your machine).
Yup
` ChromeLauncher No debugging port found on port 9514, launching a new Chrome. +0ms
Runtime error encountered: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.
Error
    at new LauncherError (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:37:22)
    at new ChromePathNotSetError (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:44:9)
    at Object.linux (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
    at Function.getFirstInstallation (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:131:51)
    at Launcher.<anonymous> (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:168:47)
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:11:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`

Not a Node expert, but kudos to whoever picks this up 🙏

**Comment by tkindy** [comment]
> AFAICT, lighthouse should still respect the hostname setting _but_ you'll have a useless Chrome launched and sitting around on your localhost _as well_

Ah, good call @patrickhulce! It does appear Lighthouse itself ends up connecting to the remote Chrome instance assuming the creation of the local Chrome instance works. I tested locally and the launched local Chrome instance sat at `about:blank` even as the Lighthouse run executed in my terminal.

I'm happy to pick this one up!

**Comment by tkindy** [comment]
I updated the issue title and description to reflect @patrickhulce's findings.

**Comment by connorjclark** [comment]
Thanks for taking this, Tyler! let us know if you have any questions.
