### ISSUE TITLE
Document does not have a meta description

### ISSUE THREAD

**Issue by Mareszke** [GoogleChrome/lighthouse#12138]
**Summary**
Hello, 
I use on my website the Yoast SEO plugin, but the Lighthouse can not recognize the meta description, when I put it extra in the head section of my website, for Lighthouse is OK, but in SemRush SEO tool and Bing webmaster I recieve an error message that I have duplicate meta description. Could you, please help me, how is correct. Here is my link: https://bofoxdesign.com/
Thank you in advance. 
Best regards, Maria Szabo

**Comment by adamraine** [comment]
The meta description needs to be in `<head>` for the audit to pass.

![Screen Shot 2021-02-26 at 1 36 36 PM](https://user-images.githubusercontent.com/6752989/109340936-a7e0e400-7837-11eb-8235-0b7df2fe3dc7.png)

FWIW [web.dev documentation](https://web.dev/meta-description/?utm_source=lighthouse&utm_medium=devtools#how-the-lighthouse-meta-description-audit-fails) could be a little clearer about that.

**Comment by BStephenBB** [comment]
I'm getting a similar issue, but my `meta` tag is in the head and lighthouse is still saying that my site is missing a meta description:

![image](https://user-images.githubusercontent.com/36211879/195687482-5c349580-473c-4818-b59a-11f05ae30c29.png)

Oddly enough, on other pages of my site (that have the exact same meta tag) lighthouse correctly registers the tag.
