### ISSUE TITLE
Browserify can't handle Node 12 language features in certain situations

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#12134]
## Summary
Lighthouse's keeping up with latest LTS is [starting to bump into outdated browserify deps](https://github.com/GoogleChrome/lighthouse/pull/12129/checks?check_run_id=1965787179#step:6:26). This issue tracks solving them without the need for workarounds, but also documents how to solve them.

## Workarounds

In #12129 I bumped into two scenarios where browserify fails with relatively cryptic error messages that took a fair bit of time to decipher, so capturing here in case others run into them too. 

### `Error: Parsing file file.js: visitor[(override || node.type)] is not a function`

```js
class MyClass {
  instanceField = require('./some-dependency.js').someValue
}
```

#### Fix
Move the require outside of the instance field definition.

```js
const someValue = require('./some-dependency.js').someValue;

class MyClass {
  instanceField = someValue;
}
```

### `TypeError: baseVisitor[type] is not a function while parsing file`

```js
const someContent = fs.readFileSync('../path/to/file.js');

class MyClass {
  instanceField = 1;
}
```

```js
/** @type {string} */
// @ts-ignore
const x = 1;

class MyClass {
  instanceField = 1;
}
```

#### Fix
Revert back to older `constructor` assignment

**Comment by connorjclark** [comment]
we've rid of browserify
