### ISSUE TITLE
Form elements do not have associated labels

### ISSUE THREAD

**Issue by quantuumsnot** [GoogleChrome/lighthouse#12139]
[WebDev Labels](https://web.dev/label/)

Corresponding to this article, the following code should validate:

`<label for="test"><input type="test" id="test" name="test" required placeholder="TEST" autofocus min="0"></label>`

But it's not:

> Form elements do not have associated labels

It validates only when there's innerText in the label, like this:
`<label for="test">BLABLABLA<input type="test" id="test" name="test" required placeholder="TEST" autofocus min="0"></label>`

Care to share if this is required by W3C standards or not? Thanks in advance

**Comment by connorjclark** [comment]
Labels without any text are rather useless. This seems WAI.

**Comment by quantuumsnot** [comment]
Yeah, but most don't need any text at all except screen readers
Seems this fixes that
[Note on hiding elements](https://www.w3.org/WAI/tutorials/forms/labels/#note-on-hiding-elements)

**Comment by connorjclark** [comment]
> except screen readers

That's what this audit is for!

> Corresponding to this article, the following code should validate:
> <label for="test"><input type="test" id="test" name="test" required placeholder="TEST" autofocus min="0"></label>

The article does not explicitly say this. It says you can wrap a label around an input, but the example it gives shows the label (as expected) has inner text.

**Comment by quantuumsnot** [comment]
Ok, then
