### ISSUE TITLE
Output from cmd  isn't JSON file

### ISSUE THREAD

**Issue by AmirZimhony** [GoogleChrome/lighthouse#12147]
**Describe the bug**
When I activate the Lighthouse audit from the cmd line I get a html file with the full report instead of a JSON file.

**To Reproduce**
1. Go to Python 
2. Write a script for auditing a web page with the Lighthouse cli, setting the desired outcome type as JSON
3. Run the script
4. See how the output is a html file instead of a JSON.

**Expected behavior**
I expected to receive a JSON file as the output of the Lighthouse audit from the cli.

**Screenshots**
![image](https://user-images.githubusercontent.com/63413362/108605649-2cf27600-73be-11eb-810e-0f0c438cc511.png)
![image](https://user-images.githubusercontent.com/63413362/108605677-60350500-73be-11eb-935d-316ac2ffe27e.png)

**Comment by connorjclark** [comment]
This seems like a generic Python question, not specific to Lighthouse. We don't have bandwidth to assist in programming problems not specifically related to LH...especially when not even given the full code to debug.
