### ISSUE TITLE
PSI returning "Lighthouse returned error: Something went wrong." with no results for some sites

### ISSUE THREAD

**Issue by czarnechmurki** [GoogleChrome/lighthouse#12144]
#### Provide the steps to reproduce
Run PSI using any of the following URLs:

https://www.usatoday.com/
https://www.freep.com/
https://www.indystar.com/
http://www.azcentral.com/
https://www.usatoday.com/story/travel/airline-news/2021/02/26/faa-fines-delta-air-lines-passenger-flight-attendant-assault/6836145002/

#### What is the current behavior?

Receive an error message "Lighthouse returned error: Something went wrong."

<img width="851" alt="Screen Shot 2021-02-26 at 3 49 31 PM" src="https://user-images.githubusercontent.com/9894552/109358990-4d04b800-784a-11eb-9da5-b34f35868586.png">
<img width="873" alt="Screen Shot 2021-02-26 at 3 39 48 PM" src="https://user-images.githubusercontent.com/9894552/109359011-55f58980-784a-11eb-8d26-649f29ffd65d.png">

This seems to be occurring very consistently (I have not seen any successful runs for those URLs on PSI with version 7.1.0).

#### What is the expected behavior?

I would expect the test to complete without an error. I do not recall ever experiencing this issue with PSI on version 6.3.0, but do not know whether it started with 7.1.0 or some version between 6.3.0 and 7.1.0.

#### Environment Information
* Affected Channels: PageSpeed Insights
* Lighthouse version: 7.1.0

**Comment by cadalt** [comment]
i work for a big media corp and we have seen this recently on our sites as well.  Lighthouse in the console works but the website just returns "Lighthouse returned error: Something went wrong"
in the console we see a bunch of 500 errors from https://www.googleapis.com/pagespeedonline/v5/runPagespeed endpoints

**Comment by paulirish** [comment]
I'm presuming you saw this start around Feb 19th.

If that's the case, then I suspect these are timeouts. The operation can't finish in 60 seconds and it gets cut off.  The complexity of the page being tested is what drives the overall duration up.

Good news though.. I'm rolling out some changes this week which will relax the current 60s timeout so it's a much better chance these will complete.

**Comment by cadalt** [comment]
Yes, we started to see the behavior around the time 7.1.0 came out
but its not 60 seconds... ours dies after about 15 seconds
check kcra.com for example
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.kcra.com%2F

**Comment by paulirish** [comment]
@cadalt kcra is a really interesting situation and it ends up causing a browser crash in some circumstances. apologies, but for the moment we don't have a good answer for you. I have a tracking issue in Chromium, but it's currently not public.  I'm hoping a future version of Chrome will contain a fix.

@czarnechmurki  thanks for providing those URLs. I rolled out changes to our timeouts today however all of the URLs you provided still end up with errors. I'm still investigating…

**Comment by paulirish** [comment]
@czarnechmurki update! it turns out the exact same problem I mentioned to @cadalt affects the URLs you provided as well.  I'm escalating the bug in question.

**Comment by stnvh** [comment]
I believe this may be related to Content-Security-Policy and/or insecure requests being prevented, since implementing a CSP on our website lighthouse (and pagespeed) stopped working

**Comment by cadalt** [comment]
@paulirish thanks for continuing to look!  i don't know if it will help your investigation but Lighthouse in the chrome dev console works... just the pagespeed insight page doesn't

**Comment by czarnechmurki** [comment]
Thanks @paulirish!

In case it helps, there are a number of incredibly similar sites to those I linked to above that do not experience this issue at all. Some examples:

https://www.statesman.com/
https://www.jacksonville.com/
https://www.recordonline.com/
https://www.news-journalonline.com/

**Comment by anforowicz** [comment]
FWIW, I've opened https://crbug.com/1184318 to track this issue from the Chromium side (it does seem that the root cause is somewhere in Chromium, although this assessment is at this point based mostly on gut feeling rather than hard evidence).

**Comment by anforowicz** [comment]
BTW: I am not sure how Chromium command flags can be specified when using Chromium for headless/lighthouse mode, but it should be possible to work around this issue by using `--disable-features=RequestInitiatorSiteLockEnfocement`

**Comment by connorjclark** [comment]
you can do `--chrome-flags="--disable-features=RequestInitiatorSiteLockEnfocement"`

**Comment by rfaler** [comment]
We are also experiencing this issue with the following
https://www.usmagazine.com/
https://www.mensjournal.com/
https://www.muscleandfitness.com/
https://people.com/

**Comment by kristiewahlquist** [comment]
We have been experiencing this as well on 
https://www.crosswalk.com/
https://www.biblestudytools.com/

**Comment by kristiewahlquist** [comment]
All - we removed a script from liveintent and it worked again for us. we are looking into this

**Comment by paulirish** [comment]
Summary: there was a set of URLs (often publisher sites with lots of iframes) that triggered a problem, resulting in the "Something went wrong" fatal failure.

It was identified to be a problem in Chromium's `CorsURLLoaderFactory`: crbug.com/1184318
Fixing it necessitated bumping the Chrome version behind PSI from 88 to 90. This was blocked by two other separate bugs, but finally it was completed and deployed as of 2021-05-24 19:00 PT last night. 

Trying the repro urls like https://www.kcra.com/ on PSI no longer cause a problem. 

Disclaimer: some urls may still encounter _other_problems, but the core issue here that ended up with a "Something went wrong" fatal failure is resolved.
