### ISSUE TITLE
When I run my site through web.dev it fails Google Analytics

### ISSUE THREAD

**Issue by GeorgesCourses** [GoogleChrome/lighthouse#12146]
On my client's site calltelecom.com I have inserted the old GA code in my header.php file. I lose3 points on performance. If I insert the new GA code I lose 7 points on Best Practice. This is down to unused JS. I have fedback this issue to multiple Google departments but no-one pays any attention.

If in my company one team member was highlighting operational failings from another team member I would investigate immediately.

I do come from an ISO Auditing background so hate to see recurring failures.

Please communicate with the relevant depts and try to get Google Analytics & Google Web Dev to play nice together please.

p.s. Sitekit plugin also knocks 3% off of Performance.

![image](https://user-images.githubusercontent.com/79656245/109185684-267e4880-7788-11eb-9f94-5675a25fdd76.png)

**Comment by brendankenny** [comment]
> Please communicate with the relevant depts and try to get Google Analytics & Google Web Dev to play nice together please

Lighthouse treats all sources of extra JS overhead the same, but communicating performance tradeoffs to everyone (including teams at Google) is one of the core functions of Lighthouse as a tool.
