### ISSUE TITLE
Does not use HTTPS

### ISSUE THREAD

**Issue by skarensmoll** [GoogleChrome/lighthouse#12159]
Hi there,

I'm running the lighthouse report on my page that relies heavily on third party resources which does not use the https protocol, and the report is lowering down the **best practices** metrics because of this. is there anything I can do ? since I don't have control on those libraries?

Thanks in advance!

**Comment by connorjclark** [comment]
You could rehost those libraries on your own site, confident that they are behind https and can't be modified by a MITM attack.

What third parties are you relying on that don't support https?

**Comment by skarensmoll** [comment]
Thanks for your quick answer @connorjclark these are the libraries:

http://www.gstatic.com/external_hosted/gsap/v1_18_0/TweenMax.min.js
https://www.google.com/js/gweb/analytics/autotrack.js
https://www.google-analytics.com/u/ga_debug.js

**Comment by connorjclark** [comment]
They all work on https- just change http to https and your page should still work.

**Comment by skarensmoll** [comment]
ok thanks a lot!
