### ISSUE TITLE
Set headers doesn't work in CustomTabsIntent

### ISSUE THREAD

**Issue by Arman-Hosseini** [GoogleChrome/lighthouse#12165]
**Summary**
Hello. This issue is not about this repo, and I do not know where the appropriate repository is to raise this issue.
Please forgive me if I am in the wrong place and if you can guide me.

I use this code to send a Authorization header and it works in older browsers, but it doesn't work in newer browsers. Is there a way to send the header???
I also posted this issue on stackoverflow but did not receive a response. 

    CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
    CustomTabsIntent customTabsIntent = builder.build();

    Bundle headers = new Bundle();
    headers.putString("Authorization", ApiKey.getToken());
    customTabsIntent.intent.putExtra(Browser.EXTRA_HEADERS, headers);
    customTabsIntent.launchUrl(this, Uri.parse(url));

**Comment by adamraine** [comment]
Looks like this is related to Android SDK. Maybe try:
https://androidforums.com/forums/android-development.28/
