### ISSUE TITLE
CashApp Runaround: I had them email me an access code and when i put it in I keep getting rerouted to an initial account setup. Somebody look in to it!

### ISSUE THREAD

**Issue by MikeGutcher** [GoogleChrome/lighthouse#12164]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by connorjclark** [comment]
who do you think we are
