### ISSUE TITLE
disableFixedAndStickyElementPointerEvents Fail if CSP is active

### ISSUE THREAD

**Issue by francogp** [GoogleChrome/lighthouse#12161]
#### Provide the steps to reproduce
1. Run LH on cevt.ar

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/2739706/109824731-dc79e480-7c17-11eb-9e78-9865586c72f0.png)

#### What is the expected behavior?
to not fail if CSP directive is active

#### Environment Information
* Chrome version:  89.0.4389.72
* Operating System: Ubuntu 20.04.2 LTS

**Comment by connorjclark** [comment]
please see #11862
