### ISSUE TITLE
Pages incorrectly pass the link text audit

### ISSUE THREAD

**Issue by Malvoz** [GoogleChrome/lighthouse#12162]
Pages incorrectly pass the [link text](https://web.dev/link-text/) audit:

- The following HTML passes the audit:

  ```html
  <!doctype html>
  <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Link does not have descriptive text</title>
  </head>
  <body>
    <!-- This link should be flagged -->
    <a href="#">here</a>
  </body>
  </html>
  ```

- The "here" link in the Capabilities section passes the audit:
  https://maps4html.org/web-map-doc/#:~:text=can%20be%20found%20here

OTOH the URL provided in https://github.com/GoogleChrome/lighthouse/issues/6737#issue-388363336 is correctly flagged for (multiple) failing elements:
https://joelhsmith.github.io/debug-examples/lh-tests/index.html

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 7.0.0
* Chrome version: 89.0.4389.72
* Operating System: Windows 10.0.19042

**Comment by connorjclark** [comment]
This audit is in SEO category, so we explicitly ignore any links internal to the document as they are not relevant for search engines.

**Comment by Malvoz** [comment]
That's a bit unfortunate as these are also accessibility issues. I'll close this, feel free to continue discussion and/or re-open.

**Comment by Malvoz** [comment]
WebAIM describes how to "Avoid uninformative link phrases" due to accessibility concerns: https://webaim.org/techniques/hypertext/link_text#text

**Comment by connorjclark** [comment]
I agree, but for Lighthouse all of our a11y concerns atm come to us via axe, and we aren't looking to make our own advice at the moment. I suggest opening an issue there–they're the experts. We'll surface whatever they suggest in Lighthouse.

**Comment by Malvoz** [comment]
I'm a bit confused, it seems there is an axe rule for this as @robdodson mentioned in https://github.com/GoogleChrome/lighthouse/issues/12241#issuecomment-797843533.
