### ISSUE TITLE
without-javascript always use HTTP

### ISSUE THREAD

**Issue by johanholmerin** [GoogleChrome/lighthouse#1217]
The `Page contains some content when its scripts are not available`
 audit fails when run against a HTTPS site that doesn't redirect from HTTP.

The gatherer, `HTMLWithoutJavaScript`, returns whitespace even though the site has content.

**Comment by patrickhulce** [comment]
@johanholmerin do you have a test URL you're willing to share? I wasn't able to reproduce on a local test that used https but didn't redirect.

**Comment by johanholmerin** [comment]
Created a repo: [johanholmerin/lighthouse-1217](https://github.com/johanholmerin/lighthouse-1217)

https://localhost:3000/ doesn't pass the test while http://localhost:3001/ does.

**Comment by patrickhulce** [comment]
Ah I see you have no server responding over http at all on the given host?

**Comment by brendankenny** [comment]
possibly #2784

**Comment by peller** [comment]
bump.
