### ISSUE TITLE
net::ERR_CONNECTION_FAILED on all server domains

### ISSUE THREAD

**Issue by EFBergamo** [GoogleChrome/lighthouse#12216]
all domains of server started with problems on March 4th

domain example: www.kboingfm.com.br

https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fwww.kboingfm.com.br

Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)

**Comment by EFBergamo** [comment]
necessarily-wide-alpaca

**Comment by connorjclark** [comment]
Thanks for the report. We see the exact same error with #12219 so you can follow along there.
