### ISSUE TITLE
How to remove Drupal 8 meta tag from WordPress

### ISSUE THREAD

**Issue by copperreflections** [GoogleChrome/lighthouse#12217]
I have a WordPress website and I have this on the header. How can I remove it? I will appreciate your advice, Tony

<meta name="Generator" content="Drupal 8 (https://www.drupal.org)" /><meta name="MobileOptimized" content="width" /><meta name="HandheldFriendly" content="true" /><meta name="MobileOptimized" content="width" /><meta name="HandheldFriendly" content="true" />

**Comment by connorjclark** [comment]
Please try a Drupal support forum.
