### ISSUE TITLE
Title tag not detected 

### ISSUE THREAD

**Issue by cnxsoft** [GoogleChrome/lighthouse#12215]
#### Provide the steps to reproduce
1. Run LH on <https://www.cnx-software.com/2021/03/07/quicklogics-hearable-reference-design-enables-alexa-voice-initiated-devices/amp/>
  

#### What is the current behavior?
Lighthouse reports the "Document doesn't have a <title> element"

#### What is the expected behavior?
I should detect the title element shown in the source "<title>QuickLogic’s Hearable Reference Design enables Alexa Voice-Initiated Devices</title>"

I've tested it with axe, but there's no such message.

#### Environment Information
* Affected Channels:Extension
* Lighthouse version: 6.4.0
* Chrome version: 88.0.4324.182 (Official Build) (64-bit)
* Node.js version: N/A
* Operating System: Ubuntu 20.04.2 LTS

**Related issues**

**Comment by adamraine** [comment]
I see the title in the source code, but when the page loads I cannot find it. `document.querySelector('title')` returns `null`.

I think the title element is getting removed when the page loads somehow.

**Comment by cnxsoft** [comment]
@adamraine Thanks. So does that mean the web browser (Chrome in this instance) removes the title element during rendering?

**Comment by adamraine** [comment]
Looks like the page includes the title element for desktop, but not for mobile. LH does pass the title audit for the desktop page.

I would check to see if the page is serving different content for each form factor.

**Comment by cnxsoft** [comment]
Yes, the content on desktop, and mobile is different. That's normal, and I can't change it due to current commercial arrangements.

The title will properly detected when I run the following code in the Chrome console:

```
var element = document.querySelector('title');
alert(element.text);
```

**Comment by adamraine** [comment]
> The title will properly detected when I run the following code in the Chrome console

I'm guessing you are running that code on the desktop version of the page. That same code will not detect the title on the mobile page. Lighthouse tests the mobile page by default.
