### ISSUE TITLE
PageSpeed Insights suddenly returning FAILED_DOCUMENT_REQUEST on Square sites

### ISSUE THREAD

**Issue by privatenumber** [GoogleChrome/lighthouse#12210]
Apologies if this is not the right place to report PageSpeed Insights related bugs.

Multiple Square sites I was monitoring via the PageSpeed Insights API suddenly started returning `FAILED_DOCUMENT_REQUEST` on March 3rd, 2021 15:40 EST. I assume this is affecting _all_ Square sites.

#### Provide the steps to reproduce
[Enter `https://benchmarks-empty-site.square.site/`](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbenchmarks-empty-site.square.site%2F) on PageSpeed Insights

Another example: [`https://boba-guys.square.site/`](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fboba-guys.square.site%2F)

#### What is the current behavior?
<img width="1008" alt="Screen Shot 2021-03-05 at 9 36 57 PM" src="https://user-images.githubusercontent.com/1075694/110192290-09d2b800-7dfb-11eb-806b-0cd5921e2720.png">

Error:
> Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)

#### What is the expected behavior?
For a successful page speed report to be returned. There were no changes on the site, and Lighthouse runs fine on them via Chrome and lighthouse CLI.

I checked the [PSI release notes](https://developers.google.com/speed/docs/insights/release_notes?hl=en-US&utm_source=PSI&utm_medium=incoming-link&utm_campaign=PSI) but no red flags.

#### Environment Information
* Affected Channels: PageSpeed Insights
* Lighthouse version: Confirmed working on v7.2.0
* Chrome version:  Confirmed working on Version 88.0.4324.192 (Official Build) (x86_64)
* Node.js version: v14.15.4
* Operating System: macOS 11.2.1

**Related issues**

**Comment by privatenumber** [comment]
necessarily-wide-alpaca

**Comment by privatenumber** [comment]
(https://github.com/GoogleChrome/lighthouse/issues/2784 is a Lighthouse issue, where as this is a PSI issue)

**Comment by privatenumber** [comment]
After checking our access logs, it seems like PSI tries to access the `http` version of the URL (despite `https` being specified), hits the 302 redirect to `https`, but doesn't follow the redirect (just stops).

Logs prior to March 3rd show that PSI was following the 302 redirect to `https`.

**Comment by connorjclark** [comment]
please follow #12222

also related is #12210

**Comment by privatenumber** [comment]
This was marked [resolved](https://github.com/GoogleChrome/lighthouse/issues/12222#issuecomment-797189432) but the problem still persists for me.

Try: [https://benjerrytakeout.square.site/](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbenjerrytakeout.square.site%2F)
(Different Square site just to make sure there's no cache hit or whatever)

<img width="1008" alt="Screen Shot 2021-03-11 at 10 38 08 PM" src="https://user-images.githubusercontent.com/1075694/110888861-0f2c7880-82bb-11eb-9e36-e983ffd9a2cb.png">

**Comment by connorjclark** [comment]
It seems to be working now. Or maybe it is flaky?

**Comment by privatenumber** [comment]
Yes, flaky for me too. Got a success and a failure:

<img width="1008" alt="Screen Shot 2021-03-12 at 6 36 12 PM" src="https://user-images.githubusercontent.com/1075694/111009570-fc20b380-8361-11eb-8211-4c512dfb0595.png">
<img width="1008" alt="Screen Shot 2021-03-12 at 6 36 46 PM" src="https://user-images.githubusercontent.com/1075694/111009572-fcb94a00-8361-11eb-9aeb-32f152ba1a1d.png">


Thanks for re-opening.

**Comment by privatenumber** [comment]
Seems to be working consistently as of a day or two ago. Yesterday, I was able to make 14 successful PSI audits for Square sites consecutively.

Thank you for investigating, @connorjclark and Lighthouse team!
