### ISSUE TITLE
PageSpeed Insights HTTP/2 Issue

### ISSUE THREAD

**Issue by niftylettuce** [GoogleChrome/lighthouse#12228]
I have HTTP/2 enabled on https://forwardemail.net, and just about a week or two ago ago PageSpeed Insights is now reporting it wrong and saying H2 is not enabled, though it clearly is (try the site out in Lighthouse locally).  There's a major issue with H2 x PageSpeed Insights... obviously this is a bug!

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fforwardemail.net&tab=desktop

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fforwardemail.net&tab=mobile

**Comment by connorjclark** [comment]
please follow #7326
