### ISSUE TITLE
Use HTTP/2

### ISSUE THREAD

**Issue by adabotonjic38** [GoogleChrome/lighthouse#12239]
**Describe the bug**
HTTP/2 of websites hosted on Siteground is not recognized by Lighthouse.

**To Reproduce**
1. Go to https://web.dev/measure/
2. Insert a website  https://test.delittopergioco.it/
3. Click on "Run audit"
4. See error "Does not use HTTP/2 for all of its resources"

**Expected behavior**
If you look at the dev tools of chrome, you can see that there is http/2. So I would expect that also Lighthouse recognise it.

**Comment by connorjclark** [comment]
please follow #7326
