### ISSUE TITLE
Lighthouse Report via web.dev loads blank page with no results

### ISSUE THREAD

**Issue by DeviceDesign** [GoogleChrome/lighthouse#12247]
#### Provide the steps to reproduce
1. Run LH on https://www.gaebler.com
2. See LH metrics. Click on View Report.
3. New window launches but report is blank. URL for report is https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.gaebler.com
4. Refresh new window. Still blank.

Identical behavior on Chrome Version 89.0.4389.90 and Firefox 86.0.1.
Relaunching browsers has no effect.
Viewing the report via Incognito has no effect.

I ran the steps above (1-3) for another URL. No problem. I see the report. It's just not working for this URL, as far as I can tell.
  
#### What is the current behavior?

LH report is blank.

#### What is the expected behavior?

LH report is not blank, and tells me what I need to work on and how to fix my issues.

#### Environment Information

* Lighthouse version: Not sure, accessed via Web.dev.
* Chrome version: 89.0.4389.90
* Operating System: Windows 10

Thanks if somebody can assist and apologies if I'm in the wrong place.

**Comment by DeviceDesign** [comment]
If it's helpful, these are the Chrome Dev tools errors that are showing up on the blank report:

compiled-reportrenderer.js:812 Uncaught Error: query a not found
    at DOM.find (compiled-reportrenderer.js:812)
    at DetailsRenderer.renderSourceLocation (compiled-reportrenderer.js:1511)
    at DetailsRenderer._renderTableValue (compiled-reportrenderer.js:1263)
    at DetailsRenderer._renderTable (compiled-reportrenderer.js:1422)
    at DetailsRenderer.render (compiled-reportrenderer.js:1081)
    at CategoryRenderer.populateAuditValues (compiled-reportrenderer.js:3210)
    at CategoryRenderer.renderAudit (compiled-reportrenderer.js:3166)
    at CategoryRenderer._renderGroupedAudits (compiled-reportrenderer.js:3357)
    at CategoryRenderer.renderUnexpandableClump (compiled-reportrenderer.js:3375)
    at CategoryRenderer.render (compiled-reportrenderer.js:3564)

This error is not there when I view the report for other URLs.

**Comment by DeviceDesign** [comment]
I've installed the Chrome extension for Lighthouse and that does give me site-specific errors, so I am no longer blocked. But the original error (and possibly bug) remains. Again, apologies if this was the wrong place for this bug report. If there's a better place, let me know. Thanks.

**Comment by brendankenny** [comment]
This was fixed in Lighthouse in #11299, but web.dev hasn't picked up that change yet. I opened a PR to update web.dev to the latest lighthouse renderer in https://github.com/GoogleChromeLabs/lighthouse-keeper/pull/30. Everything should be good when that lands. Thanks for the report!

**Comment by brendankenny** [comment]
The repro link now looks good. Thanks again for filing.
