### ISSUE TITLE
Invalid Error: The page provided is not HTML (served as MIME type application/xhtml+xml).

### ISSUE THREAD

**Issue by jabcreations** [GoogleChrome/lighthouse#12245]
We at JAB Creations code strict to save time so we use the XML parser (application/xhtml+xml) to render HTML5. I just ran Lighthouse and encountered this erroneous error:

`The page provided is not HTML (served as MIME type application/xhtml+xml).`

This shouldn't be occurring.

**Comment by connorjclark** [comment]
dupe https://github.com/GoogleChrome/lighthouse/issues/11482
