### ISSUE TITLE
Getting `We ran into an error` everytime when I am testing

### ISSUE THREAD

**Issue by prashantkjha** [GoogleChrome/lighthouse#12251]
![image](https://user-images.githubusercontent.com/57619403/111271217-e4457a00-8656-11eb-8db5-21b9ae7a529e.png)

#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by adamraine** [comment]
Dupe https://github.com/GoogleChrome/lighthouse/issues/6512
