### ISSUE TITLE
Filter Wasm out of ScriptParsed events

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#12264]
see [Reporting WebAssembly Scripts via CDP](https://docs.google.com/document/d/15zdqhthcAwra1bpX6imAtdV4223E8wxPxwyX1e08gYs/edit)

https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#event-scriptParsed

We'll need to check the `scriptLanguage` in our JsUsage and probably SourceMaps gatherers

**Comment by connorjclark** [comment]
> JsUsage

.wasm doesn't show up here.

> SourceMaps

`ScriptParsedEvent` has sourceMapURL and debugSymbols, for JS/Wasm respectively.
