### ISSUE TITLE
Pagespeed Insights results differ from Chrome to Firefox

### ISSUE THREAD

**Issue by KachadurianH4H** [GoogleChrome/lighthouse#12272]
**Summary**
When I run the check on Firefox everything is Groovy. 92% The same test with Chrome is 77%

What in my site is making Chrome hang? 

Our site is: https://habitatgtr.org/

**Comment by connorjclark** [comment]
PSI runs the test on google machines, your browser does not matter.

see our docs on variance https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md
