### ISSUE TITLE
The page provided is not HTML (served as MIME type ).

### ISSUE THREAD

**Issue by aruku** [GoogleChrome/lighthouse#12283]
I know there are other issues with a similar name, but they didn't have a lot of things to try and neither of those worked.

#### Provide the steps to reproduce 
I can't setup a repo to reproduce it, but I'm attaching the output of `curl -vvvv` as I saw was asked in another thread.
[test.log](https://github.com/GoogleChrome/lighthouse/files/6185627/test.log)
AFAICK, the Content-Type is always _text/html; charset=UTF-8_.

#### What is the current behavior?
Lighthouse works fine on several URLs of our app, but there is one where it fails with the following message no matter what we do:
_The page provided is not HTML (served as MIME type )._
(The type is missing in the message.)

#### What is the expected behavior?
The audits finish.

#### Environment Information
* Affected Channels: CLI and DevTools
* Lighthouse version: 7.2.0 and 7.0.0 respectively
* Chrome version: 89.0.4389.90 (Official Build) (x86_64)
* Node.js version: 15.5.1
* Operating System: macOS Catalina

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/12125
https://github.com/GoogleChrome/lighthouse/discussions/12097

**Comment by brendankenny** [comment]
Is there a testable URL that you can share? Nothing immediately jumps out to me as problematic in that log, but it would be a lot easier to debug by seeing Chrome make the real request.

**Comment by aruku** [comment]
The URL is not public, unfortunately.

Do you mean the regular browsing request?
I can attach the HAR file.

**Comment by aruku** [comment]
Sorry, I should have asked. Would attaching the HAR file help you, @brendankenny?

**Comment by aruku** [comment]
Closing this as I just discovered this is caused by some timeout in this particular page for our dev environment.

`--max-wait-for-fcp=45000` did the trick.

**Comment by brendankenny** [comment]
Ah, that's great! I was really having trouble seeing any issue in the curl log and wasn't sure what other debugging avenues I could explore :)
