### ISSUE TITLE
CSP issues were/not logged in the issues panel

### ISSUE THREAD

**Issue by PRProd** [GoogleChrome/lighthouse#12286]
#### Provide the steps to reproduce
1. Run LH on https://myalliance.church/

#### What is the current behavior?
Best Practices section indicates that Issues were logged in the Issues panel in Chrome Devtools.  The issue type listed is "Content security policy".  While a quick flash of an 'issue' in the issues panel appears and disappears during the audit, normal page loads do not log anything into the issues panel.

#### What is the expected behavior?
If an issue is not normally logged in the issues panel, it should not show up in the audit.  If there is an issue that needs addressing during normal page load, it should show up during the audit and during a normal page load.

#### Environment Information
* Affected Channels: DevTools 
* Lighthouse version: 7.0.0
* Chrome version: Chromium	89.0.4389.90 (Official Build) snap (64-bit)  Revision	62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{1534}
* Node.js version: N/A
* Operating System: Linux Ubuntu 20.10

![LH-issuesPanel](https://user-images.githubusercontent.com/25486599/112185407-31cd6400-8bce-11eb-950f-fc9ba67ae096.jpg)

**Comment by adamraine** [comment]
Lighthouse injects a style element while testing the page. This is an existing issue, you can follow along here https://github.com/GoogleChrome/lighthouse/issues/11862.
