### ISSUE TITLE
Serve image in next-gen format eventhough they are

### ISSUE THREAD

**Issue by rkirouchenaradjou** [GoogleChrome/lighthouse#12290]
Uses-webp-images audit result varies for every scan and I am trying to find out the reason behind it.

Description:
LH result varies for every scan i.e. at some times it lists images and their potential savings and at a certain time the audit passes.
Note: The image is served in webp format - attached the below snapshot to indicate that the image's extension is webp and  the content type is image/webp
![image](https://user-images.githubusercontent.com/43122543/112338161-f184e900-8c94-11eb-9e29-ec0c93583560.png)

![image](https://user-images.githubusercontent.com/43122543/112338231-0497b900-8c95-11eb-9dc0-49b8fc647384.png)

When I try to scan the URL - the first run it passes
 ```
"audits": {
    "uses-webp-images": {
      "id": "uses-webp-images",
      "title": "Serve images in next-gen formats",
      "description": "Image formats like JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG, which means faster downloads and less data consumption. [Learn more](https://web.dev/uses-webp-images/).",
      "score": 1,
      "scoreDisplayMode": "numeric",
      "numericValue": 0,
      "numericUnit": "millisecond",
      "displayValue": "",
      "warnings": [],
      "details": {
        "type": "opportunity",
        "headings": [],
        "items": [],
        "overallSavingsMs": 0,
        "overallSavingsBytes": 0
      }
    }
  }
```

And now when I scan the same domain - the result varies :/ 

````
"audits": {
    "uses-webp-images": {
      "id": "uses-webp-images",
      "title": "Serve images in next-gen formats",
      "description": "Image formats like JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG, which means faster downloads and less data consumption. [Learn more](https://web.dev/uses-webp-images/).",
      "score": 0.45,
      "scoreDisplayMode": "numeric",
      "numericValue": 1180,
      "numericUnit": "millisecond",
      "displayValue": "Potential savings of 259 KiB",
      "warnings": [],
      "details": {
        "type": "opportunity",
        "headings": [
          {
            "key": "url",
            "valueType": "thumbnail",
            "label": ""
          },
          {
            "key": "url",
            "valueType": "url",
            "label": "URL"
          },
          {
            "key": "totalBytes",
            "valueType": "bytes",
            "label": "Resource Size"
          },
          {
            "key": "wastedBytes",
            "valueType": "bytes",
            "label": "Potential Savings"
          }
        ],
        "items": [
          {
            "url": "https://www.tidyplaces.com/hubfs/tidy-places-owner.png",
            "fromProtocol": true,
            "isCrossOrigin": false,
            "totalBytes": 232500,
            "wastedBytes": 215728
          },
          {
            "url": "https://www.tidyplaces.com/hubfs/tidy-places-home-advisor-approved.png",
            "fromProtocol": true,
            "isCrossOrigin": false,
            "totalBytes": 28487,
            "wastedBytes": 21947
          },
          {
            "url": "https://www.tidyplaces.com/hubfs/tidy-places-home-advisor-award.jpg",
            "fromProtocol": true,
            "isCrossOrigin": false,
            "totalBytes": 21869,
            "wastedBytes": 18333
          },
          {
            "url": "https://www.tidyplaces.com/hubfs/tidy-places-angies-list-award-2017.png",
            "fromProtocol": true,
            "isCrossOrigin": false,
            "totalBytes": 15081,
            "wastedBytes": 9019
          }
        ],
        "overallSavingsMs": 1180,
        "overallSavingsBytes": 265027
      }
    }
  }
```

Any help on this greatly appreciated 🙏

**Comment by adamraine** [comment]
Just to confirm, is the URL you are testing https://www.tidyplaces.com?

**Comment by rkirouchenaradjou** [comment]
> Just to confirm, is the URL you are testing https://www.tidyplaces.com? I'm unable to reproduce this on that URL.

Hi, @adamraine  thanks for looking into it. Yes that's the URL and it happens sporadically - like few runs it passes and then suddenly it flags the images though its in the right format

**Comment by adamraine** [comment]
I'm still not able to reproduce this, can you provide the following information:

- Operating system
- Chrome version
- Lighthouse version
- Affected channel (DevTools, CLI, etc.)

**Comment by rkirouchenaradjou** [comment]
> I'm still not able to reproduce this, can you provide the following information:
> 
> * Operating system
> * Chrome version
> * Lighthouse version
> * Affected channel (DevTools, CLI, etc.)

@adamraine Please find the below details:
1. OS: macOS Catalina 10.15.7
2. Chrome version: Version 89.0.4389.90
3. Lighthouse version: 6.3.0 
4. Affected channel: CLI

Note: To re-iterate the issue: the images on the site: https://www.tidyplaces.com are being served in webp format ( the content type being in image/webp) but it is getting flagged at times (sporadically)

**Comment by adamraine** [comment]
Thanks! I can reproduce this on LH 6.3.0, but not on the latest version. This is probably worth a bisect.

**Comment by connorjclark** [comment]
https://github.com/GoogleChrome/lighthouse/blob/20c8080/lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js#L55-L56 is where we consider if an image is optimizable. We ignore webp here. But we read the `mimeType` of the network record. For some reason, this mimeType is not webp as expected (defined by the record's content type). Chrome must be saying it is png (based on the resource path extension).

>  but not on the latest version

I'm guessing this is flaky; did you try enough times with the latest version to be reasonably sure?

**Comment by connorjclark** [comment]
Can you give us the entire LH report? there is data elsewhere (in network requests) that can help debug.

**Comment by adamraine** [comment]
> I'm guessing this is flaky; did you try enough times with the latest version to be reasonably sure?

I couldn't reproduce in ~10 runs on the latest version. Got it on the second try with v6.3.0:

[www.tidyplaces.com_2021-03-25_13-28-39.report.html.txt](https://github.com/GoogleChrome/lighthouse/files/6206790/www.tidyplaces.com_2021-03-25_13-28-39.report.html.txt)

**Comment by connorjclark** [comment]
Looking at the network log when this audit has entries, we can see that the failing audits have `"content-type": "image/png"` header. This seems to be a bug on the server.

Please consider using a `picture` element instead; it's more straightforward than having the server change the type of image. It's backwards compatible with old browsers too.
