### ISSUE TITLE
Lighthouse times out waiting for page load on Versions >6.5

### ISSUE THREAD

**Issue by cklemczykExp** [GoogleChrome/lighthouse#12293]
For any Lighthouse version from 6.5 up to and including the current latest 7.3, lighthouse times out waiting for onload resulting in excessively long  test times and questionable results.  Automation execution runs that would typically take ~  30 seconds now take 160 seconds or more.  This happens for  numerous urls in our automation suite.
related to PWA perhaps?
This has meant we have not been able to update the test system to any lighthouse version past 6.5 since test passes will not complete.
 
#### Provide the steps to reproduce
1. Run LH on https://www.expedia.com  
  
 lighthouse "https://www.expedia.com/"  --preset=desktop  --throttling.cpuSlowdownMultiplier=1 --output-path=./test73/desktop --output=json --output=html --chrome-flags="--ignore-certificate-errors --window-size=1400,1200

#### What is the current behavior?
log shows this behavior
  status Loading page & waiting for onload +135ms
  waitFor:warn Timed out waiting for page load. Checking if page is hung... +45s

#### What is the expected behavior?
Lighthouse detects that page has successfully finished loading and continues n in a timely fashion

#### Environment Information
Host OS: Windows and Amazon linux
test env:  npm modules/CLI
Chrome versions:  auto updated current latest
LH versions: all versions >= 6.5

**Comment by connorjclark** [comment]
I ran Lighthouse for https://www.expedia.com, here's what I found.

[index](http://lh-issue-runner-12293.surge.sh)
❌ [html](http://lh-issue-runner-12293.surge.sh/lighthouse@7.3.0.report.html) [json](http://lh-issue-runner-12293.surge.sh/lighthouse@7.3.0.report.json) [output](http://lh-issue-runner-12293.surge.sh/lighthouse@7.3.0.output.txt) lighthouse@&#8203;7.3.0
❌ [html](http://lh-issue-runner-12293.surge.sh/lighthouse@6.5.0.report.html) [json](http://lh-issue-runner-12293.surge.sh/lighthouse@6.5.0.report.json) [output](http://lh-issue-runner-12293.surge.sh/lighthouse@6.5.0.output.txt) lighthouse@&#8203;6.5.0
❌ [html](http://lh-issue-runner-12293.surge.sh/lighthouse@5.6.0.report.html) [json](http://lh-issue-runner-12293.surge.sh/lighthouse@5.6.0.report.json) [output](http://lh-issue-runner-12293.surge.sh/lighthouse@5.6.0.output.txt) lighthouse@&#8203;5.6.0
✅ [json](http://lh-issue-runner-12293.surge.sh/PSI.report.json) [output](http://lh-issue-runner-12293.surge.sh/PSI.output.txt) PSI
❌ [output](http://lh-issue-runner-12293.surge.sh/lighthouse@master-c7772c.output.txt) lighthouse@&#8203;master-c7772c

**Comment by cklemczykExp** [comment]
I believe I should have said  >= version 6.5   We are currently running 6.1.1 successfully

**Comment by brendankenny** [comment]
Hmm, I'm hitting the timeout even going back to 5.6.0.

Turning on `--verbose`, it looks like the page still has three to six active requests by the end of the default timeout, two of them considered critical by the browser. Lighthouse's heuristics for waiting for load finish allows up to two active requests, none of them critical (though the critical requirement was [only added in 7.0](https://github.com/GoogleChrome/lighthouse/pull/11738)).

From some hints in the resource paths (e.g. `evaluateExperimentsAndLog`, `stream=true`) maybe these are intended to be long-lived connections and something changed in their number and/or durations?

**Comment by cklemczykExp** [comment]
The critical request flagging in 7.0  makes sense.  I only saw the bad behavior when I upgraded from 6.1.1 to 7.0 and it went away  upon reverting.

**Comment by brendankenny** [comment]
I meant I'm hitting the timeout with your example command in LH 6.1.1 and all the way back to 5.6.0 (I didn't test before that, but the max-two-network-request heuristic has been around since maybe even 1.0). The same result is in the auto-generated results @connorjclark posted above, e.g. open [the 5.6.0 json](http://lh-issue-runner-12293.surge.sh/lighthouse@5.6.0.report.json) and search for `lh:gather:loadPage-defaultPass`, it took 45011.98ms.

**Comment by cklemczykExp** [comment]
understood.  In my data I  can see scattered evidence of timeout errors in the html reports for 6.11, but universal occurrence in 7.0  Ironically, the performance scores are better with 7.0

**Comment by brendankenny** [comment]
I'm not sure there's much more we can do here @cklemczykExp, since it seems like the waiting for timeout is working correctly from the Lighthouse side. Is there any change you'd like to see that I'm missing?

**Comment by cklemczykExp** [comment]
Thanks, We will try to address the "unfinished" status of the requests on our side by reading the reading the response body.

**Comment by brendankenny** [comment]
Sounds good. I'll close but feel free to comment or open a new issue if you run into problems!
