### ISSUE TITLE
Lighthouse Report shows device name as Emulated Moto G4

### ISSUE THREAD

**Issue by kdp88** [GoogleChrome/lighthouse#12297]
Got this integrated with protractor
running locally on a win10 box

conf file snippet

```
chromeOptions: {
            useAutomationExtension: false,
            args: [
                "--headless",
                "--disable-gpu",
                "--window-size=1920,1080",
                "--no-sandbox",
                "--disable-dev-shm-usage",
                '--allow-insecure-localhost',
                '--ignore-certificate-errors',
                "--remote-debugging-port=4444"
            ]
```

finally when my report is generated  i get something along the lines of 

```
Fetch Time
Mar 25, 2021, 2:13 PM EDT
Device
Emulated Moto G4
Network throttling
150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
CPU throttling
4x slowdown (Simulated)
```
Focusing on the Device portion, I am trying to figure out how to not emulate a Moto G4?
I am thinking some chromeOption but i have tried the following with no luck
```
 "--preset=desktop",
 "--print-config",
```

**Comment by connorjclark** [comment]
`--screenEmulation.disabled --no-emulatedUserAgent` is probably what you want

**Comment by connorjclark** [comment]
Oh, I assumed that config was a Lighthouse config. I have no idea what `chromeOptions` or protractor is, but you need a way to configure the Lighthouse run, not Chrome.

**Comment by kdp88** [comment]
@connorjclark Thanks for the quick response, I see what you are saying, I will keep digging thanks!
