### ISSUE TITLE
Links do not have a discernible name - Bug

### ISSUE THREAD

**Issue by RScodeSec** [GoogleChrome/lighthouse#12299]
Hello, I am testing my page, in the result in **ACCESSIBILITY**, I get: **links do not have a disernible name.**
but according to the web.dev guide in the Images as links and inputs section, it tells me that it should be as follows:
![image](https://user-images.githubusercontent.com/70410425/112566732-8aa72300-8dad-11eb-8c2d-9eb28739b478.png)
taking that guide as a reference and comparing with my code follow the same structure;
![image](https://user-images.githubusercontent.com/70410425/112567133-4bc59d00-8dae-11eb-99a4-b6e522523261.png)
I am visualizing that the test tool keeps throwing me the mentioned error; Thanks I listen to possible solutions, have a good day
![image](https://user-images.githubusercontent.com/70410425/112567481-e4f4b380-8dae-11eb-8cfb-2da6fc492a6d.png)

#### Provide the steps to reproduce
1. I am using from the extension for chrome
2. Run LH on <https://www.neonhouseled.com/>

#### What is the current behavior?
me sale: links do not have a discernible name.
#### What is the expected behavior?
First it is worth mentioning that I am an apprentice and according to me I would not issue any warning.

#### Environment Information
![image](https://user-images.githubusercontent.com/70410425/112568247-26d22980-8db0-11eb-91ad-e61507552aa8.png)

**Comment by RScodeSec** [comment]
Hello

**Comment by brendankenny** [comment]
Is it possible you made a typo? The link closest to the example you gave that I could find in your test page was

```
<img class="mapa__img" src="public/imagenes/as.webp"  alt="">
```
when I manually add alt text there it's no longer flagged for me.

You may also find the axe-core docs for that check useful for the other discernible link text failures in that page: https://dequeuniversity.com/rules/axe/4.1/link-name
