### ISSUE TITLE
Chrome's PWA CheckOfflineCapability has been disabled

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#12311]
This was disabled due to performance issues for some PWAs. See https://crbug.com/1187668 and the discussion of next steps in https://crbug.com/1187668#c22. Chrome 91 only for now, but from https://crbug.com/965802#c97 it seems very possible this will get merged into Chrome 90.

This means there's no `warn-not-offline-capable` signal. We were only using that as a warning for now, not scored, so audit pass/fail results should be unchanged. But this means we don't have any offline signal at all now after all the PWA changes in 7.0.

**Comment by brendankenny** [comment]
From https://crbug.com/1187668 it seems like the performance issue is largely from trying to do the offline check while the user/service worker is trying to do other work. If there's not a good workaround, I wonder if Lighthouse and DevTools could still make use of the check by manually triggering it via the protocol.

**Comment by ASSIAPLI** [comment]
A https://pwa.app.vc/pramed-ASSIAPLI#/home  a mesma PROCAMEDURGSUA-ASSIAPLI  em ação e desenvolvimento na web, como da mesma  temos  aqui a https://pwa.app.vc/pramed-ASSIAPLI#/auth  agradecemos,  é esse são todos nossos métodos de acesso com a https://pwa.app.vc/pramed-ASSIAPLI#/signin procurar medir o desenvolvimento urgente em serviços unindo o social e levar oportunidades aos novos developers e vestibulandos.

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
