### ISSUE TITLE
Why different result for LCP ob Lighthouse CI and PageSpeedInsight?

### ISSUE THREAD

**Issue by Orolll** [GoogleChrome/lighthouse#12326]
HI! Could you please tell me , wy the  LCP results from PageSpeed is different from Lighthouse-ci? and how can I fix it?
I`m trying to fix it by changing trolling, but ofcourse it change all metrics, and another metrics are +- the same

Results from PageSpeed:
First Contentful Paint
2,0 s
Speed Index
8,8 s
**Largest Contentful Paint
4,2 s**
Time to Interactive
16,7 s
Total Blocking Time
3 190 s
Cumulative Layout Shift
0,003

Results from Lighthouse-CI:
First Contentful Paint
2.0 s
Speed Index
7.3 s
**Largest Contentful Paint
9.9 s**
Time to Interactive
16.3 s
Total Blocking Time
2,920 ms
Cumulative Layout Shift
0.076

**Comment by connorjclark** [comment]
We have docs on this: https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md

You're also maybe not even comparing the same version of Lighthouse.
