### ISSUE TITLE
NO_LCP

### ISSUE THREAD

**Issue by tonybatts** [GoogleChrome/lighthouse#12332]
For 6 months or so every time I run a lighthouse audit or pagespeed insight I get a performance error (NO_LCP). Before I was getting straight 100's.

https://www.tonybatts.com/

<img width="836" alt="Screen Shot 2021-04-04 at 8 48 32 PM" src="https://user-images.githubusercontent.com/44176115/113535034-2f341c80-9587-11eb-823a-a5e8ad474cd3.png">

**Comment by adamraine** [comment]
Looks like you already commented on https://github.com/GoogleChrome/lighthouse/issues/10869. I think will just merge into that.
