### ISSUE TITLE
await chromeLauncher.launch方法只能够执行一次，再次执行就没有反应

### ISSUE THREAD

**Issue by gengbingbing** [GoogleChrome/lighthouse#12331]
const runLightHouse = async (strParams) => {
    const chrome = await chromeLauncher.launch({ chromeFlags: ['--headless'] })
    const params = JSON.parse(strParams)

    const options = {
        logLevel: 'info',
        output: 'html',
        // ['accessibility', 'best-practices', 'performance', 'pwa', 'seo']
        onlyCategories: params.type,
        port: chrome.port
    };
    const runnerResult = await lighthouse(params.url, options);

    // `.report` is the HTML report as a string
    const reportHtml = runnerResult.report;
    fs.writeFileSync(`${params.name}.html`, reportHtml);

    // `.lhr` is the Lighthouse Result as a JS object
    console.log('runnerResult', runnerResult);
    console.log('报告地址：', runnerResult.lhr.finalUrl);
    console.log('分数:', runnerResult.lhr.categories.performance.score * 100);

    // await chrome.kill();
    await chromeLauncher.killAll();
}

export default runLightHouse

runLightHouse方法只能够执行一次，再次执行就没有反应

**Comment by brendankenny** [comment]
I don't see a question here so I'm going to close, but if I'm missing something please comment further and we can re-open.
