### ISSUE TITLE
Regarding the cache-control: max-age =  n, wherein the Chrome Audit Tool is detecting the resource as not cacheable due to extra space before and after the equal-to symbol, but the browser actually caches it.

### ISSUE THREAD

**Issue by neetika24** [GoogleChrome/lighthouse#12335]
Regarding the cache-control: max-age =  n , wherein the Chrome Audit Tool is detecting the resource as not cacheable due to extra space before and after the equal-to symbol, but the browser actually caches it.

**#### Provide the steps to reproduce
1. Run LH on https://dir.indiamart.com/impcat/hdpe-bottle.html
2. Check Chrome Audit Tool is detecting the resource as not cacheable due to extra space before and after the equal-to symbol, but the browser actually caches it.**

These resources (images) should be cacheable  in chrome Audit tools

![2021-03-15](https://user-images.githubusercontent.com/82078053/113817853-9d016380-9794-11eb-94f2-70fb090b7e64.png)
![2021-03-15 (1)](https://user-images.githubusercontent.com/82078053/113817857-9ecb2700-9794-11eb-8755-76cd2123ce76.png)

![2021-03-15 (2)](https://user-images.githubusercontent.com/82078053/113817754-74796980-9794-11eb-82dd-e1aa43878bf8.png)

**Comment by neetika24** [comment]
Any insights on this?

**Comment by adamraine** [comment]
All the examples I can find show `Cache-Control` used without the extra spaces. Do you need them for some reason, it's probably just the preferred/required syntax?
