### ISSUE TITLE
Lighthouse audit throwing error - PROTOCOL_TIMEOUT ERROR 

### ISSUE THREAD

**Issue by nacerious** [GoogleChrome/lighthouse#12343]
#### Provide the steps to reproduce
1. Run LH on https://www.vivanuncios.com.mx/s-venta-inmuebles/v1c1097p1 with progressive web app category selected.
  

#### What is the current behavior?
When selecting progressive web app category, the audit throws an PROTOCOL_TIME error. 
below is the screenshot:
![Screen Shot 2021-04-08 at 10 37 07 PM](https://user-images.githubusercontent.com/1772857/114133501-054a6500-98bb-11eb-9711-deee6ff37c95.png)

#### What is the expected behavior?
It should show the result of the audit.

#### Environment Information
* Affected Channels: DevTools 
* Chrome version: Version 89.0.4389.114 (Official Build) (x86_64)

P.S: This works fine with the lighthouse chrome extension. Also the issue has started to happen since Feb 28th on our end.

**Comment by nacerious** [comment]
@brendankenny I'm just wondering what is the status on this issue? Thank You. Really do appreciate it.

**Comment by adamraine** [comment]
This is a common issue, you can follow along here https://github.com/GoogleChrome/lighthouse/issues/6512
