### ISSUE TITLE
Some passed checks are not green

### ISSUE THREAD

**Issue by TheHunterDog** [GoogleChrome/lighthouse#12346]
#### Provide the steps to reproduce
1. Run LH on any website
2. go to passed checks in performance

#### What is the current behavior?

The passed check is not green but gray

#### What is the expected behavior?

A passed check is something that is good so I would everything to be green

#### Environment Information
* Affected Channels: devtools
* Lighthouse version: Lighthouse 7.0.0 
* Chrome version: 89.0.4389.114
* Node.js version: v14.15.4 
* Operating System: Windows 10

**Comment by adamraine** [comment]
This is intentional. Grey checks in the performance section are informative.

**Comment by TheHunterDog** [comment]
isn't that a bad practice for colorblind people?

**Comment by adamraine** [comment]
I agree, we have an issue tracking this already https://github.com/GoogleChrome/lighthouse/issues/12231.

**Comment by TheHunterDog** [comment]
Thank you
