### ISSUE TITLE
How can I retrieve Accessibility and Best Practices scores from JSON response?

### ISSUE THREAD

**Issue by alienopolis21** [GoogleChrome/lighthouse#12352]
Hello, I am integrating some of Lighthouse scores on my portfolio. I have managed to find everything I needed like Performance Score and CLS, however I'm struggling to find where Accessibility and Best Practices value are stored. Can you please help me? Thank you.

**Comment by connorjclark** [comment]
https://github.com/GoogleChrome/lighthouse/blob/master/docs/understanding-results.md#categories
