### ISSUE TITLE
So much difference between Chrome Audit and Lighthouse CLI running it from the same machine

### ISSUE THREAD

**Issue by javigomez** [GoogleChrome/lighthouse#12374]
#### Provide the steps to reproduce
1. Go to Chrome Devtools -> Audits and run and audit as Desktop at for example https://admin.typeform.com/login
You will get something like this Peformance Score:
<img width="1011" alt="Screenshot 2021-04-19 at 17 47 19" src="https://user-images.githubusercontent.com/1375475/115265175-42beb600-a137-11eb-9612-36c6c7e4af82.png">
2. Now install lighthouse in your local `npm install -g lighthouse` and run the same check `lighthouse https://admin.typeform.com/login`

You will get muuuuuch lower score:
<img width="989" alt="Screenshot 2021-04-19 at 17 48 46" src="https://user-images.githubusercontent.com/1375475/115265406-78fc3580-a137-11eb-85d9-a64427f25468.png">

I am aware we use different Default Config when running it via CLI, and I guess Chrome flags when launched from Puppeteer are different. I also have checked https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md#score-variability. But still the difference from 77% to 13% is so huge that I think there must be something we can do, over just saying that there are different running configurations. 

#### What is the current behavior?
CLI returns substantially lower performance score.

#### What is the expected behavior?
CLI  execution and Chrome Devtools returns similar performance scores by default

#### Environment Information
* Affected Channels: CLI and  DevTools
* Lighthouse version: 7.3.0
* Chrome version: 89.0.4389.128
* Node.js version: v14.15.0
* Operating System: MacOs Big Sur

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @javigomez!

> over just saying that there are different running configurations.

Can you share why you have this expectation? It sounds like you've already discovered exactly why they're so different. You're testing one with a completely different configuration. If you load a page on a slow mobile network and then again on a fast fiber desktop, it is definitely expected that the performance experience of the two will be different.

**Comment by javigomez** [comment]
Thanks for your quick answer @patrickhulce

Exactly that is my point. Is not that there is a bug but if we could make both _default configurations_ similar, so there are no so much difference in default execution.

In my case we created a tool that uses Lighthouse to evaluate the pages of the company in production. The results of my tool were so different and low in comparison with the ones my colleagues were getting in their browsers that they were not trusting them.

Could you point me from these configurations here https://github.com/GoogleChrome/lighthouse/tree/bfa5351639f81ea8a034bed6fb752864ff71f580/lighthouse-core/config  is the one most similar to Chrome default one? I haven't found the Chrome configuration. 

Thanks very much

**Comment by patrickhulce** [comment]
> Is not that there is a bug but if we could make both default configurations similar, so there are no so much difference in default execution.

Those aren't both the default executions though. The DevTools one has been *changed* to audit **desktop** while the CLI uses mobile by default (like DevTools does until someone changes the radio button to desktop).

This config https://github.com/GoogleChrome/lighthouse/blob/bfa5351639f81ea8a034bed6fb752864ff71f580/lighthouse-core/config/lr-desktop-config.js is the same as the desktop option in Chrome. Every option that can be changed in the Chrome DevTools Lighthouse panel will affect the config and performance results.

**Comment by javigomez** [comment]
closing! I found a bug in my execution that was not properly loading the right desktop config. Thanks for your time
