### ISSUE TITLE
wrongful FCP ni devtools

### ISSUE THREAD

**Issue by goldylucks** [GoogleChrome/lighthouse#12371]
#### Provide the steps to reproduce
1. Run LH on https://mybiteshares.com/
  
#### What is the current behavior?
FCP is 10.3s

#### What is the expected behavior?
FCP should be less than 1s, if you go to the page you can see it loads instantly. Even when you run lighthouse you can see the content immediatly

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 7.0.0
* Chrome version: 89.0.4389.114
* Node.js version: n/a
* Operating System: ubuntu 20.0.4

**Comment by adamraine** [comment]
Lighthouse applies throttling settings after the page loads by default. Check out https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md for more info.
