### ISSUE TITLE
Time to Interactive

### ISSUE THREAD

**Issue by venkatcherry21** [GoogleChrome/lighthouse#12383]
**Feature request summary**

First Contentful Paint
3.0 s
Speed Index
5.6 s
Largest Contentful Paint
5.5 s
Time to Interactive
11.4 s
Total Blocking Time
650 ms`

**What is the motivation or use case for changing this?**

**How is this beneficial to Lighthouse?**

**Comment by erickadalberto** [comment]
https://github.com/GoogleChrome/lighthouse/tree/8efad1d24d0a4ee9cf8d881ad7d3727ea7bbbccc[](https://github.com/GoogleChrome/lighthouse/tree/8efad1d24d0a4ee9cf8d881ad7d3727ea7bbbccc)
