### ISSUE TITLE
FCP to LCP discrepancy between profiling and lighthouse

### ISSUE THREAD

**Issue by MarcoGlauser** [GoogleChrome/lighthouse#12387]
#### Provide the steps to reproduce
1. Run LH on https://followalice.com
  
#### What is the current behavior?
Lighthouse shows me vastly longer LCP than FCP. However, when I investigate the issue by profiling in Chrome, FCP and LCP are always equal, no matter which network or cpu throttling settings.
In regard to this [angular issue](https://github.com/angular/angular/issues/13446), it should now be possible to have the same FCP and LCP for angular universal apps. I have double checked all the mentioned pitfalls in that issue but none apply to our website.

**Profiling example** FCP and LCP are both at 2550.3 ms 
![Screenshot from 2021-04-21 09-14-20](https://user-images.githubusercontent.com/924855/115520647-a9a0b400-a28a-11eb-81ab-57299a62224a.png)

**Lighthouse** FCP is at 1.7s and LCP is at 2.8s
![image](https://user-images.githubusercontent.com/924855/115520431-7100da80-a28a-11eb-8c89-521c1eb49595.png)

#### What is the expected behavior?
LCP and FCP should be the same in lighthouse aswell.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 7.2.0
* Chrome version: 90.0.4430.72
* Node.js version:
* Operating System:

**Comment by adamraine** [comment]
> Lighthouse shows me vastly longer LCP than FCP. However, when I investigate the issue by profiling in Chrome, FCP and LCP are always equal, no matter which network or cpu throttling settings.

Lighthouse clears the cache before running so the LCP image must redownload before it can be painted. When the page is loaded through the performance panel, the image can be fetched from the cache and painted in time for FCP.

You can get a performance trace without using the network cache by going to the network panel and checking "Disable cache".

**Comment by MarcoGlauser** [comment]
Thanks for the tip! The "Disable cache" was already checked. Toggling it twice solved the issue and the timings are now the same as lighthouse.
