### ISSUE TITLE
How Can i Improve pagespeed-insights score with Google Adsense ads?

### ISSUE THREAD

**Issue by viratnvn** [GoogleChrome/lighthouse#12397]
Hey i just saw a site with Google Adsense ads and i surprised to see that his pagespeed-insights Score is 90+ Both on mobile as well as desktop.
Please help me to get such an amazing score.
![Screenshot_2021-04-23-16-43-13-778_com android chrome](https://user-images.githubusercontent.com/68674638/115863406-05b63480-a453-11eb-8725-0ce15ff006d6.jpg)

**Comment by adamraine** [comment]
The Lighthouse and pagespeed reports are more than just a score. The opportunities and diagnostics should give you actionable advice to improve your site's performance.

Checkout [this doc](https://web.dev/performance-scoring/) for more on how the performance score is calculated.
