### ISSUE TITLE
Hi was doing the light house test the other day 

### ISSUE THREAD

**Issue by AryHerr111** [GoogleChrome/lighthouse#12401]
I fix the links and still show that is the same error giving me a low score when the suggestion is already resolved. 
**How is this beneficial to Lighthouse?**
If the test can show right away that we did fix the issue you recommend will be cool 

Also, the 48px to 48px suggestion regarding best practices sometimes affects the design sometimes the website element is not a square but like a rectangular or frame shape. Best regard Ary Herr

**Comment by connorjclark** [comment]
> I fix the links and still show that is the same error giving me a low score when the suggestion is already resolved.

We need way more details to help you. URL? Which audit is failing, and why shouldn't it be failing anymore?

> Also, the 48px to 48px suggestion regarding best practices sometimes affects the design sometimes the website element is not a square but like a rectangular or frame shape. Best regard Ary Herr

Are you referring to tap targets? It doesn't need to be a square to pass that audit, each dimension just needs to be at least 48 pixels, otherwise it's small enough to be troublesome on mobile.

**Comment by AryHerr111** [comment]
https://googlechrome.github.io/lighthouse/viewer/?psiurl=http%3A%2F%2Fjamieherr.com%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext#seo


The link doesn't show as a 3d parties at the back end but linked to a page

The link button but the link is linked to a page I use the same method to
fix one but the other one is still showing

Links do not have descriptive text 1 link found
Descriptive link text helps search engines understand your content. Learn
more <https://web.dev/link-text/?utm_source=lighthouse&utm_medium=lr>.
 Show 3rd-party resources (0)
Link destination
Link Text
/about/ <http://jamieherr.com/about/>
(jamieherr.com)
LEARN MORE
Additional items to manually check (1) Run these additional validators on
your site to check additional SEO best practices.
Passed audits (13)
Progressive Web App
<https://googlechrome.github.io/lighthouse/viewer/?psiurl=http%3A%2F%2Fjamieherr.com%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext#pwa>
These checks validate the aspects of a Progressive Web App. Learn more
<https://developers.google.com/web/progressive-web-apps/checklist?utm_source=lighthouse&utm_medium=lr>
.

Waiting for Lighthouse results ...
