### ISSUE TITLE
Does not work with application/xhtml+xml pages

### ISSUE THREAD

**Issue by hlandau** [GoogleChrome/lighthouse#12438]
**Describe the bug**
Example URL: `https://www.devever.net/~hl/`
Results in:
```
Error: Lighthouse returned error: NOT_HTML. The page provided is not HTML (served as MIME type application/xhtml+xml).
```

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/11482

**Comment by ForbiddenEra** [comment]
Closed as completed..?

This is still an issue on pagespeed.web.dev and chrome current??

**Comment by connorjclark** [comment]
It's marked as duplicate. Go to https://github.com/GoogleChrome/lighthouse/issues/11482
