### ISSUE TITLE
Lighthouse isn't recognising button names

### ISSUE THREAD

**Issue by kellyvanderveen** [GoogleChrome/lighthouse#12433]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  
http://booking.com/attractions

#### What is the current behavior?

Following an analysis of the Booking.com Attractions website (http://booking.com/attractions), Google’s Lighthouse and PageSpeed reports flag that buttons do not have an accessible name (https://web.dev/button-name/). This issue is not limited to our Attractions page, but also occurs on other pages that use a similar header (e.g. flights.booking.com).

The recommended suggestion from Google's documentation is to ensure that buttons have an aria-label attribute providing information to screen readers. The button elements have an aria-describedby attribute referencing a tooltip that contains text describing the button elements. For screen readers, this implementation should enable them to read the tooltip information. However on the Lighthouse report it does not pass the checks. As such, booking.com/attractions and other pages’ accessibility scores are penalised.

#### What is the expected behavior?

The current implementation of our button elements should be recognised by the Lighthouse report as they are on screen readers.

#### Environment Information
* Affected Channels: 
* Lighthouse version: 7.2.0
* Chrome version: Version 90.0.4430.93 (Official Build) (x86_64)
* Node.js version: n.a.
* Operating System: n.a.

**Related issues**

**Comment by brendankenny** [comment]
This check comes from [`axe-core`](https://github.com/dequelabs/axe-core), and checking the latest version of the axe extension I see the same problem reported on that page, so it makes the most sense to report the issue upstream in https://github.com/dequelabs/axe-core/issues. Lighthouse will pick up the fix if/when axe-core is updated.

One thing I noticed though:

> The button elements have an aria-describedby attribute referencing a tooltip that contains text describing the button elements.

when I run `document.querySelectorAll('[aria-describedby]')` in the page right now I only get a single result, and it's the sign-in icon/link, no buttons. Maybe something is misconfigured in the current version of the page and the button isn't getting the aria attribute it needs?

**Comment by kellyvanderveen** [comment]
Thanks for the swift response @brendankenny! We've filed [a report on the axe-core](https://github.com/dequelabs/axe-core/issues/2915) as recommended. 

Regarding the point on document.querySelectorAll('[aria-describedby]'), is it possible you ran the check on a mobile viewport size? As on desktop we have 3 elements with the attribute, and on mobile we have only one. If the report was run for mobile it would explain why only a single result was returned.

**Comment by brendankenny** [comment]
You're right, I did try using lighthouse's mobile emulation.

From https://github.com/dequelabs/axe-core/issues/2915, it seems like this is good to close?
