### ISSUE TITLE
Passing form data to Page2.aspx, How can I get Lighthouse to check Page2.aspx?

### ISSUE THREAD

**Issue by Steve423** [GoogleChrome/lighthouse#12451]
Currently I have to hard code  the form data in Page2.aspx for lighthouse to check.
As it turns out , I'm having more and more pages to check. 
Suggestions?

TIA

**Comment by connorjclark** [comment]
Have you read https://github.com/GoogleChrome/lighthouse/blob/master/docs/puppeteer.md ?
