### ISSUE TITLE
Lighthouse not returning performance of webpage

### ISSUE THREAD

**Issue by Sapkotaanish** [GoogleChrome/lighthouse#12456]
I tried to get the page speed insights but both gtmetrix and google pagespeed insights returned the error.
So, I installed lighthouse in my device via npm and tested the webpage and noticed that performance score is missing in lighthouse report. The url is:
[https://simply360.com.au/360-examples/Sydney-Harbour-360-2020-Virtual-Tour/index.htm](https://simply360.com.au/360-examples/Sydney-Harbour-360-2020-Virtual-Tour/index.htm)

Here  I have attached screenshot of the report.

![Screenshot_2021-05-08 Lighthouse Report](https://user-images.githubusercontent.com/38289476/117532973-c61e4980-b009-11eb-8300-9dae59e3049f.png)

What is the cause of this error?

**Comment by patrickhulce** [comment]
Thanks for filing @Sapkotaanish! The error is immediately below that in the performance metrics (NO_LCP).

This page is one giant canvas which has no LCP according to the spec. A workaround for this page would be to add some other text or image content (could be something small like a copyright footer) when the canvas has rendered.

The work necessary to make browsers respect canvas content is covered by #11326 and #12309
