### ISSUE TITLE
Relative canonical reported as invalid

### ISSUE THREAD

**Issue by wasshuber** [GoogleChrome/lighthouse#12463]
#### Provide the steps to reproduce
1. Run LH on https://www.lybrary.com/the-royal-road-to-card-magic-p-35.html

#### What is the current behavior?
Reports canonical URL to be invalid because it is a relative URL.

#### What is the expected behavior?
The page defines a base URL with the `<base>` tag. This together with a relative URL in the `<link rel=canonincal>` tag defines unambiguously a complete/absolute URL as the canonical URL. This should not create an invalid response. It is completely standard conformant. The Google crawler correctly picks up this canonical URL without any issues. 

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version:
* Chrome version: 90.0.4430.93 (Official Build) (64-bit)
* Node.js version:
* Operating System:

**Related issues**

**Comment by wasshuber** [comment]
Thanks for the info. I guess my main problem here is the wording 'invalid'. 'Invalid' suggests that some syntax rule or official standard has been violated, which is not the case. Perhaps it should be called 'not recommended'.

**Comment by patrickhulce** [comment]
Yes, good point. Anyone watching interested in a good first bug to add "not recommended" to https://github.com/GoogleChrome/lighthouse/blob/a390c94ad550ca3da4f6d1f7de0fc381967cbce6/lighthouse-core/audits/seo/canonical.js#L35?
:)

**Comment by techguysid** [comment]
I think I can take this up. Let me know if I should.

**Comment by patrickhulce** [comment]
sure @techguysid go for it! :)

**Comment by techguysid** [comment]
@patrickhulce - Thanks! Do you want to replace invalid `explanationInvalid: 'Invalid URL ({url})'` to `explanationNotRecommended: 'URL ({url}) not recommended'` or add a new entry for it ?

**Comment by techguysid** [comment]
Because we would still be using `explanationInvalid: 'Invalid URL ({url})'` for some other cases if not this right? So I think adding new entry will help. Just wanted to double check.

**Comment by patrickhulce** [comment]
No, invalid URLs are still invalid. We're only tweaking the relative URL description to say it's not recommended

**Comment by techguysid** [comment]
Oh ok! `explanationRelative: 'Relative URL ({url})'` should have a not recommended thingy, something like explanationRelative: 'Relative URL ({url}) (not recommended)',

**Comment by techguysid** [comment]
@patrickhulce Here's the PR: https://github.com/GoogleChrome/lighthouse/pull/12479
