### ISSUE TITLE
Correct the 404 "Code Coverage" link within WordPress specific recommendations for "Remove Unused CSS" opportunities

### ISSUE THREAD

**Issue by jamesozzie** [GoogleChrome/lighthouse#12473]
As one user in the [WordPress support forums](https://wordpress.org/support/topic/url-on-the-link-text-code-coverage-is-a-404/#post-14425974) for Site Kit kindly pointed out there is a dead link at present (within the PageSpeed Insights Widget) - with Site Kit using the related PSI/Lighthouse API. I was able to replicate this performing a Lighthouse audit within Chrome (on a WordPress site)

The link at present is: https://developers.google.com/web/updates/2017/04/devtools-release-notes#coverage
The link should possibly be changed to: https://developer.chrome.com/docs/devtools/coverage/

![image](https://user-images.githubusercontent.com/41326532/118145555-9efaba00-b405-11eb-92df-1c4090e7ebb8.png)

#### Provide the steps to reproduce
1. Run LH on a WordPress site using Chrome Dev tools
2. If Unused CSS is listed as an opportunity click on the "Code Coverage" link
  

#### What is the current behavior?
The Code Coverage link points to a dead link

#### What is the expected behavior?
The link should point to an appropriate link

**Related issues**

**Comment by adamraine** [comment]
@paulirish transfer to https://github.com/GoogleChrome/lighthouse-stack-packs?

**Comment by adamraine** [comment]
Transferred to https://github.com/GoogleChrome/lighthouse-stack-packs/issues/74
