### ISSUE TITLE
Aspect Ratio Failing Improperly

### ISSUE THREAD

**Issue by apop880** [GoogleChrome/lighthouse#12499]
#### Provide the steps to reproduce
1. Run LH on https://apop.tech.
  

#### What is the current behavior?
Failing Best Practices check of images with incorrect aspect ratio when checking mobile Lighthouse scores (or when running on web.dev):
```
"items": [
          {
            "url": "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ",
            "displayedAspectRatio": "180 x 280\n        (0.64)",
            "actualAspectRatio": "10 x 16\n        (0.63)",
            "doRatiosMatch": false
          }
        ]
```

#### What is the expected behavior?
The `displayedAspectRatio` and `actualAspectRatio` are within the 5% margin the check says it's looking for, so this ought to be passing.

#### Environment Information
* Affected Channels: DevTools and web.dev
* Lighthouse version: 7.2.0
* Chrome version: 90.0.4430.212
* Node.js version: N/A
* Operating System: Windows 10

**Comment by patrickhulce** [comment]
Thanks for filing @apop880! I'm not sure where the 5% figure came from but the check is not *that* lenient. The displayed image needs to have its dimensions within 2px of the scaled size. The displayed image should have a width of 288, not 280, which is 8px short, so this failure is accurate.

**Comment by apop880** [comment]
@patrickhulce I got the 5% figure from here: https://web.dev/image-aspect-ratio/

"Lighthouse flags any image with a rendered aspect ratio 5 percent or more different from its natural ratio"

That documentation may need to be clarified then. Thank you for the explanation on what the check is looking for!
