### ISSUE TITLE
LinkBlockingFirstPaintAudit doesn't use original page source

### ISSUE THREAD

**Issue by johanholmerin** [GoogleChrome/lighthouse#1249]
`link[rel=preload]` triggers LinkBlockingFirstPaintAudit if the rel is changed before the audit is run, even though it isn't render blocking. This is the pattern used by the Filament Group's loadCSS.

Test page: http://filamentgroup.github.io/loadCSS/test/preload.html

**Comment by ebidel** [comment]
Merging this into #1317
