### ISSUE TITLE
Lighthouse reports issues logged in Issues tab, but no issues are in the tab

### ISSUE THREAD

**Issue by longtimedeveloper** [GoogleChrome/lighthouse#12525]
#### Provide the steps to reproduce
1. opened local website in Chrome
2. ran lighthouse in dev tools
 

#### What is the current behavior?
Lighthouse best practices score 93, states "Issues were logged in the Issues panel in Chrome Devtools"
However, there are no issues in the "Issues" tab.
**See the below image.**

#### What is the expected behavior?
Reported issues would appear in the issues tab

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: ighthouse 7.2.0
* Chrome version: Version 90.0.4430.212 (Official Build) (64-bit)
* Node.js version: v14.15.0
* Operating System: Windows 10 Pro 20H2 19042.985

![2021-05-20_8-41-17](https://user-images.githubusercontent.com/79998776/118981100-fccc5c00-b947-11eb-9a87-54df04f911b0.png)

**Comment by longtimedeveloper** [comment]
@paulirish 

I'm using CSP which is why lighthouse is reporting 93 best practices instead of 100 because lighthouse is attempting to dynamically insert styles or JS into my site.

`<meta http-equiv="Content-Security-Policy" content="default-src 'self';">`

When I turn off SEO for lighthouse I get 100 for best practices.

Seems others had the same issue:  [https://github.com/GoogleChrome/lighthouse/issues/11862](https://github.com/GoogleChrome/lighthouse/issues/11862)

This seems like a **bug in the reporting.**  Developers should not have to open up CPS security to enable the tooling to report properly.

Can this be addressed?

Thank you!

Karl

**Comment by adamraine** [comment]
As you mentioned this is a known bug. Can you preserve console logs (https://github.com/GoogleChrome/lighthouse/issues/11862#issuecomment-805315100) and report the CSP violation? I want to make sure it's one of our existing bugs.

**Comment by longtimedeveloper** [comment]
@adamraine I apologize, I'm not sure what you need me to do.  Are you wanting me to take the content of this issue and add it to 11862 as an additional comment?

Thanks for the guidance.

Karl

**Comment by adamraine** [comment]
I was pointing out how the CSP violation is cleared from the console log by default after Lighthouse runs. You can disable this default behavior in DevTools console settings:
![image](https://user-images.githubusercontent.com/4071474/112228165-db2c4e00-8bfe-11eb-89eb-8e7e13bbabec.png)

Adding the content of the CSP issue in this Github thread would be good. In the case that this is a previously unknown CSP violation caused by Lighthouse, we can keep this thread open.

**Comment by longtimedeveloper** [comment]
@adamraine OK, Preserve Log enabled did the trick, thank you!

I've added a comment to https://github.com/GoogleChrome/lighthouse/issues/11862#issuecomment-846223413

Closing this issue.  Apologies for the duplicate issue.  

Best,

Karl
