### ISSUE TITLE
Running lighthouse for "click" operation redirecting url

### ISSUE THREAD

**Issue by skmvali** [GoogleChrome/lighthouse#12520]
Hi,

Please help me to run lighthouse report after creating one user in my application just after click on save button. Is it possible? I see lighthouse works only for running url  as input. In this case url keeps changing

Thanks
vali

**Comment by patrickhulce** [comment]
Thanks for filing @skmvali! Not yet, but that's what issue #11313 will bring support for. Follow along on that issue to see what it will be supported.
