### ISSUE TITLE
web.dev incorrectly reporting Object tags don't have alt text, even if they do

### ISSUE THREAD

**Issue by robvnet** [GoogleChrome/lighthouse#12528]
web.dev incorrectly reporting Object tags don't have alt text, even if they do.

I have tested this on my page (https://www.robv.net/index.html) with the following object tag:

`          <object alt="Rob Varghese logo" style="pointer-events: none;" data="robv-logo-css.svg" width="70px" height="51px" type="image/svg+xml">
            Rob Varghese logo.
          </object>`

It continually reports the error '<object> elements do not have [alt] text' despite two alternative texts being provided, one in the alt attribute, the other as the object tag text.

I'd expect this error to not be reported when auditing my page through web.dev

**Comment by robvnet** [comment]
Confirmed, same error is reported in lighthouse.

Also, I've tried adding a title and description, plus aria-labelledby attribute to the svg. There's no change to the error being reported.

**Comment by yecril71pl** [comment]
This code triggers a false positive too:
```html
<object>text</object>
```

**Comment by adamraine** [comment]
https://dequeuniversity.com/rules/axe/4.0/object-alt

Looks like the `alt` attribute doesn't qualify for `<object>` elements. You need to use aria labels, `title` or inner text.

Axe doesn't notice the inner text case though, so I will file a bug.

**Comment by adamraine** [comment]
From https://github.com/dequelabs/axe-core/issues/3318#issuecomment-986635761:

Inner text *does not* count as alt text, so this part is WAI.

> Also, I've tried adding a title and description, plus aria-labelledby attribute to the svg. There's no change to the error being reported.

@robvnet  were you adding the attributes to the `<object>` tag or the svg file? Defining `title` or `aria-label` on the `<object>` tag in https://www.robv.net/index.html fixes the issue on my end.

**Comment by robvnet** [comment]
> @robvnet were you adding the attributes to the `<object>` tag or the svg file? Defining `title` or `aria-label` on the `<object>` tag in https://www.robv.net/index.html fixes the issue on my end.

It was the <object> tag. Confirmed using the title or aria-label attribute, stops the error missing alt attribute and resolves this issue. Thanks @adamraine 👍🏾

**Comment by yecril71pl** [comment]
> It was the object tag. Confirmed using the title or aria-label attribute, stops the error missing alt attribute and resolves this issue. Thanks @adamraine 👍🏾

It is inappropriate to set a title just for assistance on an element that is not supposed to have a title when viewed without assistance.  Titles are annoying when everything has one.

**Comment by robvnet** [comment]
> It is inappropriate to set a title just for assistance on an element that is not supposed to have a title when viewed without assistance. Titles are annoying when everything has one.

@yecril71pl then is aria-label appropriate, otherwise what do you recommend as the solution?

**Comment by yecril71pl** [comment]
> > It is inappropriate to set a title just for assistance on an element that is not supposed to have a title when viewed without assistance. Titles are annoying when everything has one.
> 
> @yecril71pl then is aria-label appropriate, otherwise what do you recommend as the solution?

Using `aria-label` is always appropriate; even though it does not make sense for `OBJECT` elements, at least it does not do any harm.  As I said elsewhere, the purpose of the `OBJECT` element is to get replaced with the content taken from elsewhere and, if successfully replaced, the `OBJECT` element should just disappear and its attributes should not matter.  What matters is whether, and how, the *replacing content* supports assistive technology.  That means the accessibility checker has no business messing with `OBJECT` elements *at all*.
