### ISSUE TITLE
issue with web.dev Error: Lighthouse returned error: FAILED_DOCUMENT_REQUEST.

### ISSUE THREAD

**Issue by ganeshmane1** [GoogleChrome/lighthouse#12526]
**Describe the bug**
I tried to use the web.dev tool to scan the website: https://www.no1.digital for possible SEO errors, warnings, issues, and notices.

here is the tool URL: https://web.dev first need to log in with a google account and then visit https://web.dev/measure/

But I get the following error by Google tool:

Error: Error: Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_TIMED_OUT)

======================

As the issue is only with https://www.no1.digital
here is a screenshot of the error: http://prntscr.com/1303vfp

And I am able to use the web.dev tool to scan the website: https://web.dev/
here is an Expected behavior screenshot: http://prntscr.com/13056jh

So, it means the issue is not with my side internet connection, the issue is maybe with my web hosting service provider as I raised a ticket with them too but the issue could be with the Google side too?

**To Reproduce**
1. Go to 'https://web.dev'
2. Click on 'Measure: https://web.dev/measure'
3. Scroll down to 'ENTER A WEBPAGE URL: https://www.no1.digital'
4. See an error, here is a screenshot of the error: http://prntscr.com/1303vfp

**Expected behavior**
My website is fully functional and operational and only my domain https://www.no1.digital is unable to use the web.dev tool but I can use that tool with any other website URLs.

**Screenshots**
here is a screenshot of the error: http://prntscr.com/1303vfp
here is an Expected behavior screenshot: http://prntscr.com/13056jh

**Comment by robdodson** [comment]
it looks like this is failing on PageSpeed insights as well
