### ISSUE TITLE
Data:uri images throw error "Image elements do not have explicit width and height"

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#12529]
**Summary**

Hi, Pagespeed Module has a filter that conver images to inlined images.
As far as I know data:uri spec don´t have dimensions.
When tested with LH  get this "Image elements do not have explicit width and height".

I have said to the user to come here for aditional info.

Pagespeed issue: https://github.com/apache/incubator-pagespeed-mod/issues/2068

**Comment by patrickhulce** [comment]
Thanks for filing @Lofesa! I think there was some confusion about what this audit is asking you to do, I'll comment back on that apache issue.
