### ISSUE TITLE
LightHouse request returning null reponse and sometimes taking too long to respond more than 30 mins

### ISSUE THREAD

**Issue by vishitshah26** [GoogleChrome/lighthouse#12521]
I am having an automation script which will make subsequent requests to lighthouse one after other. I want to process around 5000 urls in a single day and my automation script will run in loop. Get one url wait for response , process the response and go ahead with next url. This automation script will run everyday

Now for some of the urls I get protocol timeout and for some urls it just returns empty response.

Has anyone faced any similar issue or does lighthouse have any limitation #s of responses in a single day?

**Comment by adamraine** [comment]
Are these issues appearing when you run Lighthouse on pages individually? It would help if you provided some info about the URLs that fail.
