### ISSUE TITLE
Lighthouse reporting that Google's Securepubads script contains a document.write()

### ISSUE THREAD

**Issue by jagoncalves14** [GoogleChrome/lighthouse#12531]
I've been working on improving the Lighthouse report results on a website and got stuck with one of the audits failing that says the following:

![Screen Shot 2021-05-21 at 11 19 41](https://user-images.githubusercontent.com/17235977/119122468-7175c800-ba26-11eb-9f86-017d554e5aae.png)

The script that is mentioned there it's being written **exactly** as it's recommended on this article:
https://developers.google.com/publisher-ads-audits/reference/audits/script-injected-tags

`<script async src="https://securepubads.g.doubleclick.net/tag/js/gpt.js" id="gptCode"></script>`

The script itself doesn't have any `document.write()` but it is injecting another `securepubads` script that has.
Here is a closer look at the part where the script that contains the `document.write()`:

![image](https://user-images.githubusercontent.com/17235977/119123276-4b045c80-ba27-11eb-8612-acc2a2a15382.png)

With all this said, is there anyway to go around this? It seems silly that I'm not being able to pass a Google's Lighthouse report audit… due to a Google's own script 😔

Thanks in advance!

**Comment by adamraine** [comment]
> With all this said, is there anyway to go around this? It seems silly that I'm not being able to pass a Google's Lighthouse report audit… due to a Google's own script

I don't think so. Lighthouse is accurately reporting a usage of `document.write`. It does seem weird that it's attributed to a different script though. Can you provide a URL for us to test?
