### ISSUE TITLE
FCP is different with Performance API in devtools even without throttling

### ISSUE THREAD

**Issue by ToughBill** [GoogleChrome/lighthouse#12540]
#### Provide the steps to reproduce
1. disable the 'Simulated throttling' in lighthouse setting
2. Run LH on www.youtube.com
  
#### What is the current behavior?
the FCP value is different with value from window.performance.getEntriesByName('first-contentful-paint')[0].startTime

#### What is the expected behavior?
if disable the throttling, the FCP value from lighthouse should be same with performance API

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 7.2
* Chrome version: 90
* Node.js version:
* Operating System: win10

**Comment by patrickhulce** [comment]
Thanks for filing @ToughBill! Please see https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me :) Unchecking simulated throttling doesn't disable throttling, it just uses *applied* throttling instead.
