### ISSUE TITLE
Error when icon in Manifest is fetched during audit

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/lighthouse#12543]
Windows 8.1
Chrome 92.0.4515.6

The following error message is written to the console during the audit of https://thomasbrodhead.com:

> Error while trying to use the following icon from the Manifest: https://thomasbrodhead.com/favicons/android-chrome-192x192.20200526043913.png (Download error or resource isn't a valid image)

But when the supplied link is clicked, the image is opened without an issue.

Oddly, this error message is not generated when the audit is run in incognito mode.

**Comment by connorjclark** [comment]
Sorry for the delay here–I just tried this on the CLI and didn't see any errors. Did you find a workaround perhaps?

**Comment by tmb-github** [comment]
@connorjclark See screenshot--this doesn't happen in incognito mode, reason unknown:

![Untitled](https://user-images.githubusercontent.com/15718749/128935695-9a9d3a1d-2681-49ae-927a-c3aa32450a5e.jpg)

**Comment by adamraine** [comment]
I can reproduce this in DevTools.

**Comment by connorjclark** [comment]
Can't repro anymore, please re-open if you still get this.
