### ISSUE TITLE
Accessibility audit error on sufficient contrast ratio

### ISSUE THREAD

**Issue by auliamnaufal** [GoogleChrome/lighthouse#12547]
#### Provide the steps to reproduce
1. Run LH on https://github.com/auliamnaufal/Kulinaria and it does not calculate overall accessibility score 
  

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/60921990/119266045-60d67500-bc13-11eb-9a17-8744c8286d73.png)

#### What is the expected behavior?
i get a score 0-100 and a report

#### Environment Information
* Affected Channels: CLI, Node, Extension, DevTools 
* Lighthouse version: 7.2.0
* Chrome version: 90.0.4430.212 (Official Build) (x86_64)
* Node.js version: v14.16.1
* Operating System: macos

**Related issues**

**Comment by adamraine** [comment]
@auliamnaufal Is there a public URL this is deployed at?

**Comment by adamraine** [comment]
Actually, I think this is a duplicate of https://github.com/GoogleChrome/lighthouse/issues/12039

**Comment by auliamnaufal** [comment]
earlier i tried to find the error in my code. and then i change the Hero height section and the clip-path property in my css file, run the LH test again and the accessibility score is 100. idk how this happen but it fix the problem.

![image](https://user-images.githubusercontent.com/60921990/119437307-0ee33b80-bd48-11eb-8679-95f18b394e5c.png)


> @auliamnaufal Is there a public URL this is deployed at?

there's no public url, the app is still in development locally.
