### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by Arham1312** [GoogleChrome/lighthouse#12542]
Hi There, 
I am having this preload issue. I placed the correct link. What should I do? 
A preload `<link>` was found for "http://www.officestationerysupplies.com/wp-content/uploads/2021/05/futura-medium-bt.ttf" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

**Comment by adamraine** [comment]
This is probably an issue with your page using the preload incorrectly. Check out https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload for more info on preloads.

Is this problem specific to Lighthouse?

**Comment by Arham1312** [comment]
> This is probably an issue with your page using the preload incorrectly. Check out https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload for more info on preloads.
> 
> Is this problem specific to Lighthouse?

hi, I tried all this but still same problem

**Comment by adamraine** [comment]
Unfortunately, there doesn't appear to be an issue with Lighthouse here so I don't think we can help. Taking a quick look at http://www.officestationerysupplies.com/ I would say to add `crossorigin="anonymous"` to the preload tag, but it sounds like you already tried that. If you're still encountering issues, you should consult https://stackoverflow.com/.
