### ISSUE TITLE
Device Emulated: Moto G4

### ISSUE THREAD

**Issue by NatjMarch** [GoogleChrome/lighthouse#12564]
**Summary**

hi! why are we using Moto G4 for the device when testing mobile? does anyone even have that phone? lol thanks!

**Comment by connorjclark** [comment]
https://web.dev/lighthouse-whats-new-6.0/#emulation

**Comment by patrickhulce** [comment]
Feel free to replace "Moto G4" in your mind with the "2020 Moto E" :) they have the same performance.
![image](https://user-images.githubusercontent.com/2301202/119712450-3577a400-be26-11eb-8931-f0ffda7fa6d8.png)

The median global phone [isn't actually getting much faster over time](https://infrequently.org/2021/03/the-performance-inequality-gap/).
