### ISSUE TITLE
Protocol error (Page.getInstallabilityErrors): 'Page.getInstallabilityErrors' wasn't found

### ISSUE THREAD

**Issue by AfterThreeYears** [GoogleChrome/lighthouse#12579]
## What is the current behavior?
Fails to produce seo report. Exits immediately.

n248-154-066:~$ lighthouse --chrome-flags="--headless" https://github.com --only-categories=seo
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +505ms
  ChromeLauncher Waiting for browser.....✓ +1ms
  config:warn Trace not requested by an audit, dropping trace in defaultPass +403ms
  status Connecting to browser +10ms
  status Resetting state with about:blank +13ms
  status Benchmarking machine +23ms
  status Initializing… +1s
  status Running defaultPass pass AnchorElements, LinkElements, MetaElements, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility, FullPageScreenshot +12ms
  status Resetting state with about:blank +0ms
  status Cleaning browser cache +20ms
  status Preparing network conditions +3ms
  status Beginning devtoolsLog and trace +2ms
  status Loading page & waiting for onload +0ms
  status Gathering in-page: AnchorElements +9s
  status Gathering in-page: LinkElements +0ms
  status Gathering in-page: MetaElements +0ms
  status Gathering in-page: FontSize +0ms
  status Gathering in-page: EmbeddedContent +0ms
  status Gathering in-page: RobotsTxt +0ms
  status Gathering in-page: TapTargets +1ms
  status Gathering in-page: Accessibility +0ms
  status Gathering in-page: FullPageScreenshot +0ms
  status Gathering devtoolsLog & network records +0ms
  status Gathering: AnchorElements +13ms
  status Gathering: LinkElements +92ms
  status Gathering: MetaElements +9ms
  status Gathering: FontSize +12ms
  status Gathering: EmbeddedContent +2s
  status Gathering: RobotsTxt +6ms
  status Gathering: TapTargets +472ms
  status Gathering: Accessibility +74ms
  status Gathering: FullPageScreenshot +1s
  status Populate base artifacts +607ms
  status Get webapp manifest +0ms
  status Get webapp installability errors +251ms
  method <= browser ERR:error Page.getInstallabilityErrors  +1ms
  status Disconnecting from browser... +1ms
  ChromeLauncher Killing Chrome instance 2702339 +0ms
Runtime error encountered: Protocol error (Page.getInstallabilityErrors): 'Page.getInstallabilityErrors' wasn't found
Error: Protocol error (Page.getInstallabilityErrors): 'Page.getInstallabilityErrors' wasn't found
    at Function.fromProtocolMessage (/usr/lib/node_modules/lighthouse/lighthouse-core/lib/lh-error.js:146:19)
    at /usr/lib/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:141:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

What is the expected behavior?
LH performance report

## Environment Information
Affected Channels: Node
Lighthouse version: 7.5.0
Chromium version: Chromium 73.0.3683.75 built on Debian 9.8, running on Debian 9.11
Node.js version:v12.22.1
Operating System: Linux n248-154-066 4.14.81.bm.15-amd64 #1 SMP Debian 4.14.81.bm.15 Sun Sep 8 05:02:31 UTC 2019 x86_64 GNU/Linu

**Comment by patrickhulce** [comment]
Thanks for filing @AfterThreeYears!

That version of Chromium is *very* old. Lighthouse only supports running on Chrome stable or newer (version 90+).
