### ISSUE TITLE
Should Lighthouse accept rel="canonical" on a different domain as valid given that Bing recommends rel="canonical"? 

### ISSUE THREAD

**Issue by whitep4nth3r** [GoogleChrome/lighthouse#12572]
#### Provide the steps to reproduce
1. Run LH on https://whitep4nth3r.com/blog/future-ecommerce-jamstack-next.js-contentful-shopify
2. View SEO results

#### What is the current behavior?

Lighthouse reports:

Document does not have a valid rel=canonical
Points to a different domain (https://www.contentful.com/blog/2021/05/10/future-ecommerce-jamstack-next.js-contentful-shopify/)

The underlying code states an issue with the rel="canonical" due to the fact that "bing and yahoo don't allow canonical URLs pointing to different domains"

See comment here: https://github.com/GoogleChrome/lighthouse/blob/2d3059bcd676ddf27fccea89425532bde6b5d203/lighthouse-core/audits/seo/canonical.js#L176

#### What is the expected behavior?

I've been doing some reading. 

[Bing Webmaster Guidlines](https://www.bing.com/webmasters/help/webmaster-guidelines-30fba23a) states:

"Do not reuse content from other sources. It is critical that content on your page must be unique in its final form. If you choose to host content from a third party, either use the canonical tag (rel="canonical" to identify the original source or use the alternate tag (rel=" alternate")."

Given that Bing is recommending rel="canonical", and [Yahoo uses results crawled from Bing](https://uk.help.yahoo.com/kb/SLN2213.html), I wonder whether it's more appropriate for Lighthouse to validate canonical links on a different domain.

#### Environment Information

The below is left blank due to no errors, per se.

* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing with such great research @whitep4nth3r! 

The latest citation I can find of Bing not supporting rel=canonical for different domains was [in 2009](https://blogs.bing.com/webmaster/2009/02/12/partnering-to-help-solve-duplicate-content-issues).

Given the webmasters guidance that specific calls for its use *with third-party content* (that by definition, shouldn't be on the same domain), I'm inclined to agree we should remove this advice. I'm not the SEO expert responsible for this section though, so I'll defer to them.

cc @AVGP any knowledge here to share?

**Comment by connorjclark** [comment]
@AVGP any thoughts on this matter? :)

**Comment by connorjclark** [comment]
- https://yoast.com/rel-canonical/#:~:text=the%20canonical%20link%20element%20was%20introduced%20by%20google%2C%20bing%2C%20and%20yahoo!%20in%20february%202009
- https://www.mattcutts.com/blog/canonical-link-tag/

It does seem that in 2009, all the major indexers began to support cross origin canonical urls. We should remove this advice.

**Comment by whitep4nth3r** [comment]
Thanks everyone for your input.

PR submitted here: https://github.com/GoogleChrome/lighthouse/pull/13412

**Comment by paulirish** [comment]
Yup. I can only find some quick discussion of things here: https://github.com/GoogleChrome/lighthouse/issues/3178#issuecomment-350595382

I also agree the cross-domain limitation is dumb.
