### ISSUE TITLE
Page scores a "?" on accessibility

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [GoogleChrome/lighthouse#12573]
#### Provide the steps to reproduce

1. Run Lighthouse on https://www.aleksandrhovhannisyan.com/blog/getting-started-with-jekyll-and-github-pages/
2. Observe that accessibility scores a red `?`.
  
#### What is the current behavior?

Link to report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.aleksandrhovhannisyan.com%2Fblog%2Fgetting-started-with-jekyll-and-github-pages%2F

Accessibility scores a `?`:

![image](https://user-images.githubusercontent.com/19352442/119832950-ad98a500-becc-11eb-88c9-f447a94ea7da.png)

#### What is the expected behavior?

There are no accessibility issues on the page (that I'm aware of). The report cites color contrast issues, but there are none. Also, it's unclear what `?` means. It seems Lighthouse ran into an error. I suspect the page's size may have something to do with this.

#### Environment Information
* Affected Channels: DevTools, PageSpeed Insights, Web.dev
* Lighthouse version: 7.3.0
* Chrome version: 90.0.4430.212 (Official Build) (64-bit) (cohort: Stable)
* Operating System: Windows 10

**Comment by brendankenny** [comment]
This is #12039, which is blocked on an upstream bug in https://github.com/dequelabs/axe-core/issues/2674

(we're also tracking clearer messaging when Lighthouse run into an error in #9968)

**Comment by AleksandrHovhannisyan** [comment]
Gotcha, thanks!
