### ISSUE TITLE
Report unable to find meta description in Wix Website https://www.thenatureinternational.com/

### ISSUE THREAD

**Issue by Ronak-45** [GoogleChrome/lighthouse#12571]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  https://www.thenatureinternational.com/,

#### What is the current behavior?
Report unable to find meta description in Wix Website https://www.thenatureinternational.com/, however, is already available on a website.

#### What is the expected behavior?
Report Should able to find meta description on wix site.

#### Environment Information
* Affected Channels: DevTools 
* Lighthouse version:  **7.3.0**
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**
Report unable to find meta description in Wix Website https://www.thenatureinternational.com/, however, is already available on a website.
![scre](https://user-images.githubusercontent.com/84898492/119782673-18a4a480-beea-11eb-9adc-a67d9919265b.jpg)
![scr1](https://user-images.githubusercontent.com/84898492/119782827-3ffb7180-beea-11eb-956d-f4558d8dded6.PNG)
![scr2](https://user-images.githubusercontent.com/84898492/119782984-69b49880-beea-11eb-8b56-883f4be3c594.PNG)

**Comment by adamraine** [comment]
@Ronak-45 I can't reproduce this, is it still a problem for you?
