### ISSUE TITLE
PSI vs Search console for measuring Field data. Correct way?

### ISSUE THREAD

**Issue by scaledrop** [GoogleChrome/lighthouse#12589]
We keep tracking the Field data through RUM/Crux as well as search console. Recently we noticed, search console numbers are way too off from the CLS/LCP numbers on PSI field data. Sharing examples below;

### **Search Console**
![image](https://user-images.githubusercontent.com/2621312/120304562-84717d80-c2ed-11eb-8101-03f3b0f93deb.png)

### **PSI**
![image](https://user-images.githubusercontent.com/2621312/120304242-3ceaf180-c2ed-11eb-8308-e28bc0f4bda0.png)

### Why Field data?
PSI lab data is too unreliable comparing to WPT and Lighthouse. So, we're not taking PSI lab data into consideration as of now.

**Comment by patrickhulce** [comment]
Thanks for filing @scaledrop! 

Search console and PSI are showing you the results of different pages.

PSI is showing you the CLS of *just that URL*. Search console is showing you the the CLS of the *2838 different URLs that look sorta like that URL*. If you click the question mark of "Similar URLs" you'll see the explanation.

> Each issue is assigned to a group of URLs that have similar content and resources. This is because it is assumed that any performance issues in these similar pages may be due to the same underlying problem (such as an overly large image, or a common slow-loading tab set display). The URL shown in the Examples table is one URL from the group. "Similar URLs" are other URLs in the affected group.

The underlying dataset is the same (Chrome UX Report), so the problematic CLS pages must be some of the other 2837.

**Comment by scaledrop** [comment]
@patrickhulce Thanks and for underlying dataset we can't claim anything. Closing this issue.
