### ISSUE TITLE
Lighthouse again not detecting webp version of images..

### ISSUE THREAD

**Issue by tomasts248** [GoogleChrome/lighthouse#12581]
Example of report
![image](https://user-images.githubusercontent.com/32283036/120038396-339e1400-bfd1-11eb-9c8a-5b15588bf4ba.png)
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.tomastestart.cl%2F

and yet under network tab > latest Chrome version detects images as webp format

![image](https://user-images.githubusercontent.com/32283036/120038579-7fe95400-bfd1-11eb-8249-3ead2693b48e.png)

**Comment by patrickhulce** [comment]
Thanks for filing @tomasts248!

Lighthouse measures cold loads. On cold loads, this page delivers PNGs, not WebPs.

You can try it yourself by opening an incognito window and loading without refresh or the `Disable cache` button checked in Network panel, or by using curl.

![image](https://user-images.githubusercontent.com/2301202/120699675-566b7500-c476-11eb-8e7c-d59aaf5719f5.png)

Gives PNG (normal request, Lighthouse)
```
curl 'https://www.tomastestart.cl/wp-content/uploads/2021/05/PBLTJD1V4Franv7vtrimv2-1024x595.png' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Mobile Safari/537.36' \
  -H 'accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'authority: www.tomastestart.cl' \
  -H 'referer: https://www.tomastestart.cl/' \
  -vvvv
```

Gives WebP (request on a reload) *notice the `cache-control: no-cache` header*
```
curl 'https://www.tomastestart.cl/wp-content/uploads/2021/05/PBLTJD1V4Franv7vtrimv2-1024x595.png' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Mobile Safari/537.36' \
  -H 'accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'authority: www.tomastestart.cl' \
  -H 'referer: https://www.tomastestart.cl/' \
  -vvvv
```
