### ISSUE TITLE
No screenshots found in trace on mobile devices.

### ISSUE THREAD

**Issue by lanjingling0510** [GoogleChrome/lighthouse#1260]
command:

```
lighthouse --disable-device-emulation --disable-cpu-throttling http://m.cqaso.com --output-path=a.json --output=json --perf
```

result: **No screenshots found in trace **

```
Perf metrics
21
100
Page load performance is fast
First meaningful paint: 2305.3ms (target: 1,600ms)  
86
Perceptual Speed Index  
Speed Index shows how quickly the contents of a page are visibly populated. Learn more.
No screenshots found in trace
-1
Estimated Input Latency  
The score above is an estimate of how long your app takes to respond to user input, in milliseconds. There is a 90% probability that a user encounters this amount of latency, or less. 10% of the time a user can expect additional latency. If your score is higher than Lighthouse's target score, users may perceive your app as laggy. Learn more.
Speedline unable to parse trace contents: No screenshots found in trace
-1
Time To Interactive (alpha) (target: 5,000ms)  
Time to Interactive identifies the time at which your app appears to be ready enough to interact with. Learn more.
No screenshots found in trace
```

**Comment by wardpeet** [comment]
You're testing on a real device? Are you running on chrome or canary?

**Comment by lanjingling0510** [comment]
Hi @wardpeet.l run against a real mobile android device on chrome 55.0.2883.91 (WebKit 537.36)
Use the following command：
```
$ adb devices -l
List of devices attached
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
ba1ed23                unauthorized usb:336658432X

adb forward tcp:9222 localabstract:chrome_devtools_remote

lighthouse --disable-device-emulation --disable-cpu-throttling http://www.cqaso.com --perf
```
The results are as follows：
![2016-12-27 15 04 51](https://cloud.githubusercontent.com/assets/11639669/21493290/b7d624ee-cc45-11e6-9b20-22e7551acab7.jpg)

**Comment by wardpeet** [comment]
great will have a look ^^

**Comment by 0xR** [comment]
Having the same issue. Unfortunately this means that I can't use lighthouse to measure performance on real devices.

**Comment by wardpeet** [comment]
Bug filed: https://bugs.chromium.org/p/chromium/issues/detail?id=681988#

**Comment by lanjingling0510** [comment]
Continue to focus on the latest developments.

**Comment by paulirish** [comment]
This is fixed tip of tree chromium (rev 453807): https://bugs.chromium.org/p/chromium/issues/detail?id=681988#c13

The fixed missed the latest Android Canary version just barely. But whenever the next version of Android Canary comes out, it'll have this fix.

That probably means any android chrome version >= 58.0.3026.6

**Comment by wardpeet** [comment]
i'll close this one, it's in canary and can be used until chrome stable is out
