### ISSUE TITLE
Too much variation in PSI Lab data is subject of concern

### ISSUE THREAD

**Issue by scaledrop** [GoogleChrome/lighthouse#12615]
Lab data is subject to variance and changes every time you run. But isn't it a discrepancy if this variation reaches 3x or 4x from actual numbers. 
#### WPT: [Report](https://www.webpagetest.org/result/210603_AiDc8P_c1c698e1929f792fa47ee906cec5f482/) 
where LCP is always under 2.5s. And let's just check its PSI lab score.
#### PSI: [Report 1](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fm.economictimes.com%2Fmarkets)
![image](https://user-images.githubusercontent.com/2621312/120676626-dcf27780-c4b3-11eb-9bcc-a40985f55438.png)
  

#### PSI: [Report 2](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fm.economictimes.com%2Fmarkets)

![image](https://user-images.githubusercontent.com/2621312/120676775-00b5bd80-c4b4-11eb-97ee-c9c27d17083a.png)

### Outcome
Users will get frustrated if it is too way off and questions on its credibility. Eventually they'll have no option but to move away from Google's tooling ecosystem.

**Comment by connorjclark** [comment]
Linking to PSI doesn't preserve the results you saw, FYI. You could use the extension + then click "save to gist" to share. I suspect that if you were to dig into the differing results of those two runs, you'll find a legitimate reason for the huge variance in metrics, as this is far outside the realm of our expected variance.
