### ISSUE TITLE
Background and foreground colors have a sufficient contrast ratio - Error!

### ISSUE THREAD

**Issue by Lucania001** [GoogleChrome/lighthouse#12613]
#### steps to reproduce
1. Run LH on https://zenbears.co.uk/

#### What is the current behavior?

Accessibility score returns an error

#### What is the expected behavior?

Accessibility score should return a score and audit points

#### Environment Information
* Affected Channels: DevTools lighthouse and web.dev
* Lighthouse version: 7.2.0
* Chrome version: 91
* Operating System: MAC OS

**Comment by connorjclark** [comment]
dupe #12039
