### ISSUE TITLE
Suddenly Lighthouse is loading every single script, even those with timeout and defer - score down by 20 points

### ISSUE THREAD

**Issue by avenirer** [GoogleChrome/lighthouse#12611]
#### Provide the steps to reproduce
1. Run LH on https://www.pentalog.com

#### What is the current behavior?

Lighthouse ignores GDPR consent (or rather accepts all cookies), and timeout of GTM, and because of that now all scripts are loaded. Not the same happens when the LH is run from Browser's Web Tools

#### What is the expected behavior?

I guess the expected behavior was not to load all the scripts. Suddenly, in one day the score was down from 64 to 40

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 8
* Chrome version: 90
* Node.js version: ?
* Operating System: Windows 10

**Comment by lennyqevani** [comment]
+1

**Comment by patrickhulce** [comment]
Thanks for filing!

> Lighthouse ignores GDPR consent (or rather accepts all cookies), and timeout of GTM

Lighthouse does not do this, Lighthouse just loads the page. The page is doing this upon detecting lighthouse.

From the cookiehub script...

```js
            isBot: function() {
                var e = new RegExp("(cookiehubscan|googlebot|adsbot|mediapartners|baidu|bingbot|bingpreview|sogou|proximic|duckduckbot|teoma|slurp|yandex|semrush|lighthouse|gtmetrix|pingdom)","i")
                  , t = navigator.userAgent;
                return e.test(t)
            },
```

`isBot` is then used several times to alter behavior. Lighthouse is not responsible for pages deliberately attempting to alter behavior upon detecting Lighthouse.
