### ISSUE TITLE
TS issues in FR Gatherer Meta

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#12619]
A few days ago, we ran into an issue with [distributed conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) on `FRTransitionalContext`. This caused unexpected behavior when defining a gatherer with multiple dependencies.

The issues with `FRTransitionalContext` have been resolved by https://github.com/GoogleChrome/lighthouse/pull/12565 but this popped up again with `GathererMeta`.
https://github.com/GoogleChrome/lighthouse/blob/761e47e066793e18a3bfb7be708326961276c1d5/types/gatherer.d.ts#L98-L101
Multiple dependencies doesn't produce any errors, but the type is too lenient. For example, these are both valid according to our type definition:

```js
/**
 * @type {LH.Gatherer.GathererMeta<'DevtoolsLog'|'Trace'>}
 */
this.meta = {
  supportedModes: ['timespan', 'navigation'],
  dependencies: {DevtoolsLog: DevtoolsLog.symbol, Trace: Trace.symbol},
}
```

```js
/**
 * @type {LH.Gatherer.GathererMeta<'DevtoolsLog'|'Trace'>}
 */
this.meta = {
  supportedModes: ['timespan', 'navigation'],
  dependencies: {DevtoolsLog: DevtoolsLog.symbol},
}
```

Enforcing the expected behavior with square brackets fixes this, but it also opens pandora's box of other type violations. I haven't found a silver bullet to resolve these issues other than to keep the type definition of `GathererMeta`. Are these type violations valid, or can we stick with the weaker definition for `GathererMeta`?

**Comment by adamraine** [comment]
Thanks for fixing this @patrickhulce! Is it worth verifying the behavior of other generic types in Lighthouse that use distributed conditional types?

**Comment by patrickhulce** [comment]
> Is it worth verifying the behavior of other generic types in Lighthouse that use distributed conditional types?

A scary question 😆  

Personally, I don't view it a priority until we've found it not catching something (like you did here). We tend to have a fair number of implicit assumptions in resolving generics with our declarations of types before everything gets dynamically linked anyhow. I couldn't see anything else obvious from a quick `<T.*extends` search in our `.d.ts` but you're welcome to continue the search :)
