### ISSUE TITLE
Failing : Does not redirect HTTP traffic to HTTPS 

### ISSUE THREAD

**Issue by talentedandrew** [GoogleChrome/lighthouse#12620]
1. Run LH on [consumercracy](http://consumercracy.com/)
  
#### What is the current behavior?
This web app redirects HTTP traffic to HTTPS, but still it is showing error.

#### What is the expected behavior?
It should pass the `Does not redirect HTTP traffic to HTTPS` check.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version:7.2.0
* Chrome version: chrome://91.0.4472.77/ 
* Node.js version: nodejs12

**Comment by patrickhulce** [comment]
Thanks for filing @talentedandrew! I'm not able to reproduce this behavior. Can you provide more details on how to reproduce?

![image](https://user-images.githubusercontent.com/2301202/120855204-cdbb0a80-c543-11eb-8e6b-2f52bc716898.png)

**Comment by talentedandrew** [comment]
@patrickhulce Please try it in the incognito window. Check the image below.

![image](https://user-images.githubusercontent.com/15646138/120885642-96ae2d00-c607-11eb-926a-7b2dfde21917.png)

**Comment by talentedandrew** [comment]
Also check this report that I generated.

[report.pdf](https://github.com/GoogleChrome/lighthouse/files/6602230/report.pdf)

**Comment by patrickhulce** [comment]
That was in an incognito window. I already believe you that you're seeing this, I just can't really help unless we can reproduce it :)

Other things to try:

- CLI
- Another machine
- Another geographic location
- Another version of Chrome

If we can locate a difference, I can try it that environment.

**Comment by connorjclark** [comment]
We'll be removing this audit for v9 anyhow :)
