### ISSUE TITLE
Incorrectly says modern image formats aren't being used

### ISSUE THREAD

**Issue by kirupa** [GoogleChrome/lighthouse#12628]
This concerns the guidance around ensuring images are served in a modern format. The code file is here: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/uses-webp-images.js

#### Provide the steps to reproduce
1. Run LH on: https://www.kirupa.com/html5/making_http_requests_js.htm
  
#### What is the current behavior?

When running the site through https://web.dev/measure/, I get flagged for not using modern image formats. Because I use a CDN, while the extension in source may show as being JPG or PNG, what is actually served is a WebP image. I could be wrong here, but it doesn't look like the performance checker catches that.

#### What is the expected behavior?
The check doesn't flag me for not using modern image formats.

#### Environment Information
* Affected Channels: https://web.dev/measure/
* Lighthouse version: N/A
* Chrome version: N/A
* Node.js version: N/A
* Operating System: N/A

**Related issues**

**Comment by connorjclark** [comment]
We only look at the response header Content-Type to identify image types, not the extension. Are you sure the CDN is sending Lighthouse the right assets?

**Comment by paulirish** [comment]
right now i'm seeing this audit only flag the youtube thumbnail (which you don't control)

![image](https://user-images.githubusercontent.com/39191/123859870-0a2b1d80-d8da-11eb-813b-9eb4896e81e1.png)

but perhaps you made some changes in the meantime?

**Comment by patrickhulce** [comment]
Without a repro, there's not much we can do here. If you find a reproducible case where the CDN is *actually* serving a modern image format, a URL example would be much appreciated :)

**Comment by chmelevskij** [comment]
Bumping this with link to real issue. Network tabs shows `content-type: image/webp`, lighthouse score ignores that.

https://www.volvocars.com/dk/v/cars/electric-cars?perf=nogtm

<img width="462" alt="Screenshot 2021-11-18 at 11 29 55" src="https://user-images.githubusercontent.com/7774918/142388679-07da8e92-15d6-418b-8f13-79cb7203171b.png">
