### ISSUE TITLE
Differences between CLI and web.dev

### ISSUE THREAD

**Issue by Janpot** [GoogleChrome/lighthouse#12629]
#### Provide the steps to reproduce
1. Run LH on https://www.businessinsuranceusa.com/
  

#### What is the current behavior?

When running through the CLI/node:
https://gist.github.com/Janpot/dccf7896d32d87efbb379925d9b75f5f

![Screenshot 2021-06-08 at 11 40 54](https://user-images.githubusercontent.com/2109932/121162698-702e0300-c84e-11eb-9a60-e0661b18da4e.png)

When running in the devtools, or on web.dev:
https://gist.github.com/Janpot/d9498c2561bdb0ca64d1c4383b6a3886

![Screenshot 2021-06-08 at 11 31 23](https://user-images.githubusercontent.com/2109932/121161623-77084600-c84d-11eb-88eb-363d5f87f06a.png)

#### What is the expected behavior?

The website seems to have a viewport meta tag defined, so I guess the devtools/web.dev behavour is the correct one.

#### Environment Information
* Affected Channels: CLI, Node
* Lighthouse version: 8.0
* Chrome version: 93.0.4535.0 (Official Build) canary (x86_64)
* Node.js version: v14.16.0
* Operating System: MacOs

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @Janpot!

That's because this page serves different (broken) content to Lighthouse from the CLI.

When requested from Chromium normally it returns

```html
<!--<noscript><!--<meta http-equiv="refresh" content="0; url=non.php" /> </noscript>-->
```

but when Lighthouse requests this page from the CLI, the server returns (note the additional, incorrect end comment)

```html
<!--<noscript><!--<meta http-equiv="refresh" content="0; url=non.php" />--> </noscript>-->
```

**Comment by Janpot** [comment]
Thanks @patrickhulce , I just noticed the same. I'm sorry for wasting your time. Looks like 
```
curl --compressed -H "user-agent:Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4420.0 Mobile Safari/537.36 Chrome-Lighthouse" -H "accept-encoding:gzip, deflate, br" https://www.businessinsuranceusa.com/
```
produces this result, removing either one of these headers returns the "correct" version. There's two things I don't fully understand yet
1. What's web.dev or the devtools doing differently to get different results? Is it using a different user agent?
2. I can't seem to replicate this in the devtools by overriding the chrome user agent (network conditions), seems like I'm still missing something.

**Comment by patrickhulce** [comment]
Three interesting things I see in the response headers from CLI.

```
"vary":"Accept-Encoding,User-Agent","content-encoding":"gzip","x-server-cache":"true","x-proxy-cache":"HIT"
```

1. This response is cached based on the specific accept-encoding header and the user agent.
2. This response was a cache hit for that combination.
3. accept-encoding isn't set to that exact value when I make the request from DevTools (no clue why, probably a difference in the chrome startup flags or chrome profile data).

Seems like somewhere has a bad cache copy of this page.

**Comment by Janpot** [comment]
Ah good point, indeed, thanks! 👍
