### ISSUE TITLE
CDP 'Network.enable' clears available requests

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#12631]
Example: https://gist.github.com/adamraine/3412959bef2b783ce8e14559403bf246

This is source of the `MainDocumentContent` failure in FR:
https://github.com/GoogleChrome/lighthouse/blob/c1de7aca060c1f13a82b657780f6a55f0507d9fa/lighthouse-core/test/fraggle-rock/api-test-pptr.js#L161-L163
We call `Network.enable` multiple times during a navigation, so the cache is cleared before we can access the main document request body. This appears to be a bug in DevTools:
https://bugs.chromium.org/p/chromium/issues/detail?id=1217661

In the meantime, we can be more cautious about calling `Network.enable` in gatherers. In my mind, this means calling `Network.enable` once at the start of a navigation and never during gathering. We could also just wait for a fix to come in M93 since this only appears to cause issues in FR.

**Comment by brendankenny** [comment]
How does this end up interacting with multiple sessions (if at all)? Does a second session calling `Network.enable` cause the same behavior if then requesting the response body in a first (already `Network.enable`d) session?

**Comment by adamraine** [comment]
I don't think so, this works fine:
```js
const puppeteer = require('puppeteer');

async function run() {
  const browser = await puppeteer.launch({
    headless: false,
  });
  const page = await browser.newPage();
  const session1 = await page.target().createCDPSession();
  const session2 = await page.target().createCDPSession();

  await session1.send('Network.enable');

  const pagePromise = page.goto('https://example.com');
  const requestId = await new Promise(r => {
    session1.on('Network.requestWillBeSent', e => r(e.requestId));
  });
  await pagePromise;

  await session2.send('Network.enable');

  try {
    const body = await session1.send('Network.getResponseBody', {requestId});
    console.log(body);
  } finally {
    await page.close();
    await browser.close();
  }
}
run();
```

**Comment by patrickhulce** [comment]
> I don't think so, this works fine:

Ooooooh I misunderstood in chat then :) This is fine and this will fix itself naturally when we enforce anything enabling new domains to use a dedicated session.

**Comment by brendankenny** [comment]
Ha, that boggles my mind a little. I've wondered the same thing about the [re-request behavior on `CSS.enable`](https://github.com/GoogleChrome/lighthouse/pull/12325#discussion_r614258485). I'm really surprised that the second session wouldn't trigger the same behavior. But these are the mysteries of multi target :)
