### ISSUE TITLE
Uncaught error running programmatically 

### ISSUE THREAD

**Issue by dimension85** [GoogleChrome/lighthouse#12640]
HI, 
I run lighthouse programmatically for some time now and successfully trap protocol timeouts and other issues, such as error not opened etc.

However, recently, some of my tests fail due to a coding issue following a protocol timeout.  I appreciate that a protocol timeout has occurred but it is the fact that it is not caught and presented back to me, for handling.  I have tried to capture the issue in my own code, but am unable to stop this from causing my application to crash and restart.

Unfortunately there is no single web page that causes this to occur so I cannot give you a candidate URL as such, but this occurs around the time of a 'catch' statement processing a detected error such as no known mark: or not opened.  

Hopefully you are able to determine and prevent this from occurring.
 
```
/home/azureuser/node-apps/node_modules/lighthouse/lighthouse-core/gather/driver.js:322
        const err = new LHError(
                    ^

LighthouseError [LHError]: PROTOCOL_TIMEOUT
    at Timeout._onTimeout (/home/azureuser/node-apps/node_modules/lighthouse/lighthouse-core/gather/driver.js:322:21)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  code: 'PROTOCOL_TIMEOUT',
  friendlyMessage: {
    i18nId: 'lighthouse-core/lib/lh-error.js | protocolTimeout',
    values: {
      errorCode: 'PROTOCOL_TIMEOUT',
      protocolMethod: 'Storage.clearDataForOrigin'
    },
    formattedDefault: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Storage.clearDataForOrigin)'
  },
  lhrRuntimeError: true,
  protocolMethod: 'Storage.clearDataForOrigin'
}
```

I am running the latest v8.0.0 Lightouse and HeadlessChrome/91.0.4472.77

Your help is appreciated
Phil

**Comment by dimension85** [comment]
Hi,

Adding some further information to help diagnosis of issue

Run on Ubuntu 18.04 Lighthouse 8.1 
Node Code run with failing URL

let url = "https://www.mandmdirect.com/" ;
const fs = require('fs');
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');

(async () => {
	const chrome = await chromeLauncher.launch({chromeFlags: ['--headless']});
	const options = {logLevel: 'info', output: 'html', onlyCategories: ['performance'], port: chrome.port};
	const runnerResult = await lighthouse(url, options);

	// `.lhr` is the Lighthouse Result as a JS object
	const reportJson = JSON.stringify(runnerResult.lhr) ;
	fs.writeFileSync('lhjson.json', reportJson) ;
	
	// `.report` is the HTML report as a string
	const reportHtml = runnerResult.report;
	fs.writeFileSync('lhreport.html', reportHtml);

	console.log('Report is done for', runnerResult.lhr.finalUrl);
	console.log('Performance score was', runnerResult.lhr.categories.performance.score * 100);

	await chrome.kill();
})();

Resulting error on 8.1
![image](https://user-images.githubusercontent.com/2478174/126063648-465f09b6-a618-4a84-bb9e-db079d68241b.png)

  status Gathering in-page: SourceMaps +0ms
  status Gathering in-page: FullPageScreenshot +0ms
  status Gathering trace +0ms
  status Gathering devtoolsLog & network records +13ms
  status Disconnecting from browser... +30s
/home/ubuntu/node-apps/node_modules/lighthouse/lighthouse-core/gather/driver.js:322
        const err = new LHError(
                    ^

LighthouseError [LHError]: PROTOCOL_TIMEOUT
    at Timeout.<anonymous> (/home/ubuntu/node-apps/node_modules/lighthouse/lighthouse-core/gather/driver.js:322:21)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'PROTOCOL_TIMEOUT',
  friendlyMessage: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.emulateNetworkConditions)',
  lhrRuntimeError: true,
  protocolMethod: 'Network.emulateNetworkConditions'
}

It would be useful to get this JavaScript error resolved, understand the Protocol Timeout is a different issue.

I find this issue as 100% reproducible 

When run in Incognito browser gives the message - so message is faulty too.. 
'There may be stored data affecting loading performance in this location: IndexedDB. Audit this page in an incognito window to prevent those resources from affecting your scores.'

Your help in resolution is appreciated.
Phil

**Comment by connorjclark** [comment]
Do you still get this reproducible error with the latest Chrome and Lighthouse?

**Comment by dimension85** [comment]
Hi Connor,
   
   
    In answer to your question, the problem still exists but is now more random and not as readily recreatable on demand.
   
   
    
   
   
    We run about 500 tests against different websites daily and only a few failures, but some common ones that fail on a regular basis are
   
   
        https://www.elabelz.com 
        https://www.layalina.com 
   
   
    
   
   
    The failures occur when emulating a Moto G4, at 35 ms TCP RTT, 6,144 Kbps throughput and 3x CPU slowdown.
   
   
    
   
   
    Our policy is to drop PWA testing on a second run and these tests always pass on the second run.
   
   
    
   
   
    We are unable to trap the generated error so it causes our processes to fail and then auto restart, therefor it would be great to get a resolution to this problem.
   
   
    
   
   
    We have also observed another symptom error which I will raise as a separate incident over the next day or so..
   
   
    
   
   
    Thank you for coming back to me.
   
   
    Phil
   
   
    
   
   
    
   
   
    This is the current output at failure in our automation processes.
   
   
    
   
   
   
  
  
   
    On 10/08/2021 20:39 Connor Clark ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Do you still get this reproducible error with the latest Chrome and Lighthouse?

**Comment by adamraine** [comment]
I can't reproduce this unfortunately, going to merge this into https://github.com/GoogleChrome/lighthouse/issues/6512
