### ISSUE TITLE
skipAudits disables full-page-screenshot gatherer

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#12642]
#### Provide the steps to reproduce

lighthouse https://web.dev/learn/ --view --skip-audits font-size

#### What is the current behavior?

No element screenshots.

#### What is the expected behavior?

Element screenshots should be shown.

#### More info

skipAudits triggers some filtering logic that's not run normally https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/config.js#L410

So gatherers that aren't required are removed. The full-page-screenshot is never required.

It is added back in if onlyCategories is set, but not for skipAudits https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/config.js#L515

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/11913
