### ISSUE TITLE
No_LCP only on Mobile After Adding NitroPack 

### ISSUE THREAD

**Issue by chrisbiges** [GoogleChrome/lighthouse#12648]
#### Provide the steps to reproduce
1. Run LH on <https://boulos.com/>
 

#### What is the current behavior?
No_LCP for Mobile after installing NitroPack 
#### What is the expected behavior?
Would like to see what is causing this issue as none of my other sites have this issue

#### Environment Information
* Affected Channels: DevTools 
* Lighthouse version: 7.2
* Chrome version:  91.0.4472.101 (Official Build) (64-bit) 
* Node.js version:
* Operating System: Win10

**Related issues**
![image](https://user-images.githubusercontent.com/85704082/121581155-c3d55380-c9ea-11eb-98b4-96c2e4354af2.png)

**Comment by connorjclark** [comment]
Worked for me.

**Comment by chrisbiges** [comment]
@connorjclark My apologies I did not close this myself. There was a conflict with a security plugin that was installed. Once we removed it everything started working.
