### ISSUE TITLE
How Do I Use Lighthouse For Debugging My Website

### ISSUE THREAD

**Issue by enjoyincity** [GoogleChrome/lighthouse#12655]
**Summary**

How to i use lighthouse to debug my website [](https://www.enjoyincity.in) errors. If i am not a web developer and dont know how do i resolve the errors on my website. i have only source code of the website and can upload it on my website hosting.

**Comment by patrickhulce** [comment]
Thanks for filing @enjoyincity!

The target audience for implementing advice in Lighthouse reports is web developers. You might want to contact whoever built your site to see if they can address the issues found there.

**Comment by enjoyincity** [comment]
hello patrickhulce!
Thanks for your reply!
I have built the website by using website designer software coffeecup. and i can do some changes in html and css. could  you please help me out and guiding me?
Thanks
this is the website https://www.enjoyincity.in
