### ISSUE TITLE
 Cannot extend an interface 'NodeJS.EventEmitter'

### ISSUE THREAD

**Issue by CodeEXc** [GoogleChrome/lighthouse#12650]
The current version of lighthouse cannot be compiled in typescript. I've already re-downloaded all node_modules and updated them to the current version. If I implement the EventEmitter with all methods, everything works fine. 

```
PS C:\brighthouse> npx tsc

node_modules/lighthouse/types/enquirer.d.ts:15:25 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

15   class Confirm extends NodeJS.EventEmitter {

Found 1 error.
```

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 8.0.0
* Chrome version: 90.0.4430.93
* Node.js version: v14.15.4
* Operating System: Win10
* Typescript 4.3.2

**Comment by adamraine** [comment]
Can you share more info about how you are using Lighthouse like your tsconfig.json and some example code that uses Lighthouse?
