### ISSUE TITLE
Clarification about "total-byte-weight" audit

### ISSUE THREAD

**Issue by ghisleouf** [GoogleChrome/lighthouse#12664]
Hi there !

We are currently integrating lighthouse in our CI / CD process and running some benchmarks with it, thanks to lighthouse CLI.
On the same report, we have different values for total-byte-weight measure analyzing json file.

Let say that we are performing an audit on a website and we are using the total-byte-weight metric.
For some reasons, I have the total byte weight audit result saying me :

`total-byte-weight: {
id: "total-byte-weight",
title: "Avoids enormous network payloads",
description: "Large network payloads cost users real money and are highly correlated with long load times. [Learn more](https://web.dev/total-byte-weight/).",
score: 1,
scoreDisplayMode: "numeric",
numericValue: 714213,
numericUnit: "byte",
displayValue: "Total size was 697 KiB",`

But, when I look at the totalbyteweight property into audit.diagnostics.details.items, I get the value : 6795874

The "real" page total byte weight is, I think, 6,48MiB.
So, could you please help me understanding the difference with the 2 values ? Could it be related to the service worker on the website ?

You will find attached the json report file.

[strange-tbw.json.zip](https://github.com/GoogleChrome/lighthouse/files/6658122/strange-tbw.json.zip)

Thanks a lot for your help.

**Comment by patrickhulce** [comment]
Thanks for filing @ghisleouf!

The difference here is that `total-byte-weight` excludes requests that never finished (which includes the ~5.8MiB video). I'm not sure that this policy actually makes much sense, so I'm inclined to fix it 👍

**Comment by ghisleouf** [comment]
OK, thanks a lot for your feedback @patrickhulce .

Actually, I'm tracking over days page total byte weight and this metrics includes some unexplained variance (sometimes it completely loads, sometimes not).

Anyway, thank you for your quick answer.

**Comment by patrickhulce** [comment]
> Actually, I'm tracking over days page total byte weight and this metrics includes some unexplained variance (sometimes it completely loads, sometimes not).

This is extremely common. See our [docs on variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md).

Also you might want to check out [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci/) :)
