### ISSUE TITLE
Lighthouse doesn't automatically treat .app or .dev TLDs as HTTPS

### ISSUE THREAD

**Issue by sayrer** [GoogleChrome/lighthouse#12674]
Should these domains not answer on port 80, or should Lighthouse not try to load them?

https://domains.google/tld/dev/

https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=http%3A%2F%2Fweb.dev

**Comment by sayrer** [comment]
Further, what should be done with protocol-free references like "web.dev", which will be linked in any Twitter-like highlighting scheme?

**Comment by sayrer** [comment]
Here's the error I got loading web.dev:
<img width="906" alt="Screen Shot 2021-06-16 at 6 36 43 PM" src="https://user-images.githubusercontent.com/253473/122317149-e7f4d100-ced1-11eb-9ead-3b7e7ac3f319.png">

**Comment by patrickhulce** [comment]
Thanks for filing @sayrer! This is definitely an unexpected result for HSTS TLDs, we'll have to look into it.
