### ISSUE TITLE
Failure to handle application/xhtml+xml

### ISSUE THREAD

**Issue by defanor** [GoogleChrome/lighthouse#12675]
**Describe the bug**
`application/xhtml+xml` MIME type is not handled properly by <https://web.dev/measure/>:

```
Error: Error: Lighthouse returned error: NOT_HTML. The page provided is not HTML (served as MIME type application/xhtml+xml).
```

**To Reproduce**
1. Go to https://web.dev/measure/
2. Enter an URL returning `application/xhtml+xml` content
3. Click "RUN AUDIT"
4. See the error message

**Expected behavior**
[XHTML is parsed](https://html.spec.whatwg.org/#dom-parsing-and-serialization).

**Comment by defanor** [comment]
Sure, <https://defanor.uberspace.net/> serves application/xhtml+xml.

**Comment by patrickhulce** [comment]
Thanks for filing! See #11482 for progress and updates.
