### ISSUE TITLE
Conditional extraHeaders

### ISSUE THREAD

**Issue by tizmagik** [GoogleChrome/lighthouse#12673]
**Feature request summary**

The ability to pass in `extraHeaders` in order to run audits on pages behind auth is extremely valuable. However, from what I understand, the `extraHeaders` functionality means that we're passing along authentication information to _all_ requests made by the page. Ideally, we'd like the ability to restrict these headers to only be passed to specific URLs/origins (e.g. only first-party origins).

I'm happy to work on this myself (if you could point me in the right direction). Would you accept a PR that adds this additional functionality? It could be an extension of extraHeaders that accepts an object map of regex=>extraHeaders, or a separate object map entirely.

**What is the motivation or use case for changing this?**

To avoid including auth info in the headers to 3rd party domains.

**How is this beneficial to Lighthouse?**

Adds additional flexibility and security around lighthouse runs for pages behind auth.

**Comment by connorjclark** [comment]
We're working on an entirely new way to configure Lighthouse, which puts users 100% in control of the page via Puppeteer (Fraggle Rock #11313). We probably won't consider adding more declarative/flexible options like a regex->headers match, and instead defer to a future usecase where you can just use request interception in Puppeteer.

**Comment by tizmagik** [comment]
That's amazing, looking forward to that! Thanks, I'll close.
