### ISSUE TITLE
metric toggle messes up viewport in CDT

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#12683]
before click

![image](https://user-images.githubusercontent.com/4071474/123004449-769d9e00-d369-11eb-9780-ea5ea69ad702.png)

after click

![image](https://user-images.githubusercontent.com/4071474/123004487-7f8e6f80-d369-11eb-8b9c-0dfb8123cf10.png)

(notice margin on bottom and the deleted toolbars up top)

only fixed when tabbing out of / back to LH panel.

**Comment by sidverma32** [comment]
closed with this issue  [12725](https://github.com/GoogleChrome/lighthouse/issues/12725#event-4959548979)

**Comment by connorjclark** [comment]
indeed! thx
