### ISSUE TITLE
 A preload `<link>` was found for "http://localhost:3000/css/icomoon.css" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

### ISSUE THREAD

**Issue by uc-anr** [GoogleChrome/lighthouse#12691]
`<link href="./css/icomoon.css" rel="preload" as="style" onload="this.rel='stylesheet'" />`
this line of code in sapper template.html giving error and not able to apply preload or prefetch on this css.

**Comment by adamraine** [comment]
This error is emitted by DevTools and is not directly related to Lighthouse. I would suggest filing a bug with them.
