### ISSUE TITLE
PWA theme_color rgb

### ISSUE THREAD

**Issue by Gmagoz** [GoogleChrome/lighthouse#12708]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

http://local(URL_not_needed)

### What happened?

theme_color and background_color specified in rgb is not recognised.

### What did you expect?

theme_color and background_color specified in rgb is recognised.

### What have you tried?

in hex or rgba OK

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

7.2.0

**Comment by sidverma32** [comment]
@brendankenny if we convert the `bgColor` and  themeColor from rgb to hex , it becomes this :
- `const bgColor = 'rgb(222, 184, 135)';` //#DEB887
- `const themeColor = 'rgba(5%, 10%, 20%, 0.4)';` // #0d1a33

Let me know if that works @Gmagoz  and @brendankenny  then will add the support for `hex` or is that added in `rgb` intentionally ??

**Comment by Gmagoz** [comment]
Sorry, you (or I) seems to miss the point.
These two are correctly recognised:
bgColor = "rgba(222, 184, 135, 1.0)";
bgColor = "#DEB887";

This is Not recognised:
bgColor = "rgb(222, 184, 135)";

My opinion simply rgb value to rgba value(with alpha 1.0)

**Comment by patrickhulce** [comment]
@Gmagoz thanks for filing!

Can you provide a bit more information about what you mean by "not recognized"? (filling out the fields you skipped with an example URL would be great)

Our manifest parser *does* recognize rgb colors.

https://github.com/GoogleChrome/lighthouse/blob/fe91d5691e6ecbeb8ae1e35c0bc9783443217252/lighthouse-core/test/lib/manifest-parser-test.js#L528-L537

**Comment by Gmagoz** [comment]
I'm sorry. I try explain better:
I have a html file with "embedded inline" manifest.
In manifest I specified [background_color] and [theme_color]. These are correctly detected (and works good) in devtools tab application presentation(section). 
But in tab Lighthouse ProgressiveWebApp(section) PWA Optimized there are:
Failures: Manifest does not have 'background_color', Manifest does not have 'theme_color'.
This last point I mean for not "recognised" by Lighthouse.

**Comment by patrickhulce** [comment]
> I have a html file with "embedded inline" manifest.

Do you have an example URL? I'm not sure what this means. A manifest in a data URL?

**Comment by connorjclark** [comment]
We can reopen if provided more information (an example website that fails your expectations).

**Comment by Gmagoz** [comment]
For anyone finding this old issue: I can confirm the bug was real, 
and it's since been resolved — though not by fixing the original rgb() parsing bug directly.
The manifest parser used to run theme_color/background_color through cssstyle's CSS color validation, which did indeed reject some rgb() strings (like rgb(222, 184, 135) from this issue) while accepting rgba() and hex — so the report here was accurate. 
That validation was removed entirely in [4b8348f](https://github.com/GoogleChrome/lighthouse/commit/4b8348f1f5e4babe7c9c8304b6e91f389721cc0f) / PR #14447 (first shipped in v10.0.0) — the PR notes that Lighthouse's own docs already said colors aren't validated for CSS-correctness, so the (buggy) check was just removed rather than fixed. 
Since then, the manifest parser accepts any string value for these fields without format validation.
Later, the whole PWA audit category (which included themed-omnibox/installable-manifest/splash-screen, where this originally surfaced) was removed from Lighthouse in [7187606](https://github.com/GoogleChrome/lighthouse/commit/718760666) / PR #15455, shipped in v12.0.0.
So on current Lighthouse (v13.x), rgb(222, 184, 135) and rgba(222, 184, 135, 1.0) are both accepted identically — there's no longer any distinction, since color format isn't checked at all.
