### ISSUE TITLE
KADENCE + CODE SNIPPETS + CLOUDWAYS + CLOUDFLARE + WP-ROCKET

### ISSUE THREAD

**Issue by mywebguytaylor** [GoogleChrome/lighthouse#12703]
I am trying to get my Kadence site to pass 90 Page Speed score, and have a few questions. I have a few questions:

1. What are the pros and cons of using CODE SNIPPETS Plugin instead of GTM ? It seems like managing everything would be much easier with CODE SNIPPETS, because I am able to see them inside of my WP admin, however, I am unclear on what the point is for having GTM (Google Tag Manager)? I must be missing something? Most of my sites are smaller sites, and not large corporation sites, so I don't have any problem of getting access to FTP to change scripts, etc, is that the biggest pro for GTM? I want to keep my site as lightweight as possible. I use WP ROCKET, and also, they have ADD ON options which load FB PIXEL and GA locally, and their support staff says it doesn't work with GTM : /

2. How do I add the GA code properly to CODE SNIPPETS? Does it have to be in the head and the body?

3. How do I add the GTM code properly to CODE SNIPPETS, if I decide to use GTM as well?

4. How do I add the Facebook Pixel to CODE SNIPPETS? Should I also install the FACEBOOK FOR WORDPRESS, by Facebook? which one should I use? What are the pros and cons of each ? https://wordpress.org/plugins/official-facebook-pixel/

5. WP ROCKET options has this section called ADD ONS, and I am unsure how this works. Does anyone have any advice ? https://www.mycart123.com/uploads/screenshot31057F93.png

6. WP ROCKET LAZY LOAD, what's the default best practice here, should I check this or no? I thought Wordpress 7.2 is lazy loading all images by default now? Even when I do check this option, I am still getting errors in page speed test saying I should lazy load images on my site, so I am unsure if that even works?

7. Kadence Theme has an option to LOAD GOOGLE FONTS LOCALLY, can anyone offer a simple explanation or some stepwise instructions on how to do that? I am using Digital Ocean Cloudways Hosting. I use CLOUDFLARE for caching.

8. Does anyone have smart suggestions for developing on a WP site and minimizing latency when updating a page?

9. What is the meaning of life? 😉

**Comment by connorjclark** [comment]
This is far too broad and none of these questions seem related to Lighthouse. For example, you should direct your questions about GTM to their docs or support channels.

**Comment by mywebguytaylor** [comment]
> This is far too broad and none of these questions seem related to Lighthouse (except number 9, to which the answer is "gotta go fast"). For example, you should direct your questions about GTM (or Kadence, or whatever you're talking about) to their docs or support channels.

Do not close this topic
