### ISSUE TITLE
Critical Request Chain Failing Test

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#1270]
This is probably me missing something, but with a very basic page that makes no requests I'm getting an error on the critical path:

![](http://i.imgur.com/ekzfUoz.png)

My only guess is that where I have a deferred JavaScript file this is upsetting the chain / the display and causing the error, does that sound possible?

![](http://i.imgur.com/uUvxHeC.png)

**Comment by gauntface** [comment]
Looking through the code for the critical request chain audit, it looks like the "optimalValue" is set to 0, which I'm not sure makes sense given that the the HTML itself is one *required* request.

    let chainCount = 0;
    function walk(node, depth) {
      const children = Object.keys(node);

      // Since a leaf node indicates the end of a chain, we can inspect the number
      // of child nodes, and, if the count is zero, increment the count.
      if (children.length === 0) {
        chainCount++;
      }

      children.forEach(id => {
        const child = node[id];
        walk(child.children, depth + 1);
      }, '');
    }

    walk(chains, 0);

    return CriticalRequestChains.generateAuditResult({
      rawValue: chainCount.length <= this.meta.optimalValue,
      displayValue: chainCount,
      optimalValue: this.meta.optimalValue,
      extendedInfo: {
        formatter: Formatter.SUPPORTED_FORMATS.CRITICAL_REQUEST_CHAINS,
        value: chains
      }
    });

So for a request chain where it's only the HTML:

```
{ '1393.1': 
   { request: 
      { url: 'http://localhost:5123/styleguide/view/title-block/0/',
        startTime: 12843.756905,
        endTime: 12843.91622,
        responseReceivedTime: 12843.915488,
        transferSize: 1168 },
     children: {} } }
```

The walk function will pickup that there are no children and increment the chainCount by one, which will be a failure.

The fix could be to either start the walk function on the original requests children OR set the optimalValue to 1 (Personally in favor of this option).

This works for my case, but I'm entirely sure of where the depth the variable comes in and it feels like it should be used in favor of the childCount.

**Comment by gauntface** [comment]
I also just noticed:

    rawValue: chainCount.length <= this.meta.optimalValue,

where chainCount is a number so '.length' doesn't make sense :(

**Comment by patrickhulce** [comment]
@ebidel / @brendankenny  what was the original motivation behind making critical request chains a failable test (with red x etc)? seems like a good candidate to reframe as just warning/info

**Comment by gauntface** [comment]
Personally a fail seems fair, providing there is a working solution to make
the test pass.

**Comment by patrickhulce** [comment]
Agreed the test should have a failure state if the optimal value were a reasonably determined value backed up by data instead of the current `0` :)

**Comment by ebidel** [comment]
I think the idea was that any critical request longer than 1 is a failure.
Not sure we realize the page itself was a failure. Agreed the optimal value
should probably be set to 1.
