### ISSUE TITLE
axe-core version is out-of-date (with fatal bug)

### ISSUE THREAD

**Issue by mohmadt93** [GoogleChrome/lighthouse#12705]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://hungry-goldwasser-e4dfda.netlify.app/

### What happened?

At the time I ran lighthouse audit before the v8 update and it didn't show this error. 
But since then I get **"Error!" or "?" for SEO audit**. 

Plus:
- when SEO and Accessibility are checked, both audits show an Error,
- Accessibility has 44 Error logs, SEO has 3 Error logs
- Link: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fhungry-goldwasser-e4dfda.netlify.app%2F
<img width="400" src="https://user-images.githubusercontent.com/86134742/123443855-91c11580-d5d6-11eb-89b5-5b65cad6466d.png">

- when SEO is unchecked, Accessibility shows 100%
<img width="400" src="https://user-images.githubusercontent.com/86134742/123444012-b6b58880-d5d6-11eb-971d-e63bb88dbb1d.png">

- when Accessibility is unchecked, SEO still shows Error
<img width="400" src="https://user-images.githubusercontent.com/86134742/123444152-e06eaf80-d5d6-11eb-9e16-5272f1e7d25b.png">

This are the logs for SEO audit
- title does actually exist and is visible in source code
<img width="500"  src="https://user-images.githubusercontent.com/86134742/123444764-891d0f00-d5d7-11eb-9599-bcf6e58e9f1a.png">

So I assume it has something to do with SEO audit, which is somehow linked to Accessibility.
If I run the LH audit in DevTools there is no Error at all.

### What did you expect?

I expected 100% because actually there doesn't seem to be a real issue with the code.

### What have you tried?

-CLI, WebDev Measure, DevTools
- doesn't work for both mobile and desktop audit
- Operating System: macOS Big Sur

### How were you running Lighthouse?

CLI, PageSpeed Insights, Chrome DevTools

### Lighthouse Version

8.0.0

### Chrome Version

91.0.4472.114

**Comment by patrickhulce** [comment]
Thanks for filing @mohmadt93! This is a bug in the accessibility library Lighthouse uses (https://github.com/dequelabs/axe-core/pull/2965) and was fixed recently, we just need to update on our side.

**Comment by mohmadt93** [comment]
> Thanks for filing @mohmadt93! This is a bug in the accessibility library Lighthouse uses ([dequelabs/axe-core#2965](https://github.com/dequelabs/axe-core/pull/2965)) and was fixed recently, we just need to update on our side.

Hey @patrickhulce, I was wondering if the update is already done, because the issue isn't resolved for me. Or can you tell me how I can recognize when it is finished? Kind regards

**Comment by patrickhulce** [comment]
@mohmadt93  The update has been done, but a new version of Lighthouse *stable* hasn't been released yet that includes the change. 

You can use [v8.0.0-dev.20210627](https://www.npmjs.com/package/lighthouse/v/8.0.0-dev.20210627) on npm if you want to test it immediately.
