### ISSUE TITLE
PageSpeed Insights (PSI) shows different scores when checked from different locations

### ISSUE THREAD

**Issue by vimal-here** [GoogleChrome/lighthouse#12710]
Will PSI show different scores from different locations? For me the development team from India develops a product and delivers to Business in UAE. From India, we're getting a score of 26, but from UAE the score is less than half - 17. 

Is this a known issue. Read from some other issues that PSI is not location dependant. 
Any help to mitigate this issue would be much appreciated! We would like to communicate to our Stakeholders what actually is causing this. 

Out-of-topic: Does PSI mobile scores affect search engine ranking? Our sites load fast, but very low PSI scores. PSI reports give suggestions, but we've already considered the major recommendations which we got from Chrome >Dev Tools> Lighthouse audit report itself.

All Best!

**Comment by connorjclark** [comment]
Yes.

**Comment by vimal-mozanta** [comment]
@connorjclark - Thanks for your quick response. 

So I can assume that https://developers.google.com/speed/pagespeed/insights/ cannot be used as a global benchmark tool for performance if the application is used by a userbase from particular region alone, right?

More details: My application is hosted in UAE region and in India I'm getting a better score. Do you think that this is a good use case to not use PSI from India?

**Comment by hazemhagrass** [comment]
I'm facing exact same issue. The performance score is completely diffrent via different locations
