### ISSUE TITLE
Lighthouse PROTOCOL_TIMEOUT error when analyzing www.engadget.com

### ISSUE THREAD

**Issue by pchua** [GoogleChrome/lighthouse#12713]
**Describe the bug**
Getting Lighthouse PROTOCOL_TIMEOUT when testing https://www.engadget.com . Was working the day before but now suddenly giving error.

**To Reproduce**
1. Go to https://developers.google.com/speed/pagespeed/insights/
2. Type https://www.engadget.com and click Analyze
3. See error Lighthouse returned error: PROTOCOL_TIMEOUT. Waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.emulateNetworkConditions) (PROTOCOL_TIMEOUT)Dismiss

1. Go to https://web.dev/measure/
2. Type https://www.engadget.com and click Run Audit
3. See error Lighthouse returned error: PROTOCOL_TIMEOUT. Waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.emulateNetworkConditions) (PROTOCOL_TIMEOUT)Dismiss

**Expected behavior**
No errors, and display results.

**Screenshots**
![image](https://user-images.githubusercontent.com/2768334/123455469-9665d980-d596-11eb-98de-8c7bc4ce7756.png)

![image](https://user-images.githubusercontent.com/2768334/123456072-489da100-d597-11eb-9f00-23d28a566563.png)

**Comment by adamraine** [comment]
I can't reproduce this in either PSI or web.dev. Are you still experiencing this?
