### ISSUE TITLE
How to use lighthouse to process offline performance logs and traces.

### ISSUE THREAD

**Issue by usherfu** [GoogleChrome/lighthouse#1274]
Hi,

First of all, thanks for creating this great tool!

I am trying to use lighthouse to process offline performance logs and traces by following [lighthouse as trace processor](https://github.com/GoogleChrome/lighthouse#lighthouse-as-trace-processor), however, there are several points unclear to me, hoping to get some help.

It is mentioned lighthouse can analyze performance logs and traces collected by other tools, such as webdriver. This is exactly what I want to do, i.e., collecting the performance log in a selenium script, then pass on the log to lighthouse to generate some audit/metrics.    

   My understanding is that I would just need to provide those files as parameter for "performanceLog"  in the config.json.   However, why is it still necessary to provide an URL in the commandline, isn't it offline or maybe I missed something? 
`lighthouse --config-path=config.json http://www.random.url`

The selenium script is very similar to [Michael Klepikov'example](https://gist.github.com/klepikov/5457750), except that it prints LogType.PERFORMANCE instead of LogType.BROWSER.

Thanks and have a great holiday!

**Comment by paulirish** [comment]
Good idea. I have a config for exactly this. I'll add it to examples. :)   

Party on, Wayne.

**Comment by xubin98246** [comment]
so,  what's the exact config for offline performance logs process ? i found the url still needed in latest version 2.8.0 .
is there any update ? Thanks

**Comment by gula123** [comment]
Same confusion from my side. No detailed guide on the required log format (e.g. from the webdriver log) and I don't understand neither why URL is needed. Please give a status.

**Comment by amar-makwana** [comment]
Same here, any updates on this?

**Comment by patrickhulce** [comment]
There have been many changes along the way and very few audits in Lighthouse actually work with only a trace and devtools log anymore (only 10 out of 100+).

If you're still interested in getting the performance metrics out, here's how you can do it in the meantime.

```bash
# note "my-folder" below can be anything you want

# Copy the trace JSON file over, see format https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/test/fixtures/artifacts/perflog/defaultPass.trace.json
cp trace.json my-folder/defaultPass.trace.json
# Copy the devtools log file over, see format https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/test/fixtures/artifacts/perflog/defaultPass.devtoolslog.json
cp devtoolslog.json my-folder/defaultPass.devtoolslog.json
# Create a fake artifacts.json so LH doesn't barf
echo '{"BenchmarkIndex": 0, "fetchTime": 0, "URL": {"requestedUrl": "https://example.com", "finalUrl": "https://example.com"}}' > my-folder/artifacts.json
# Run Lighthouse in "Audit only" mode
lighthouse https://example.com -A my-folder/

**Comment by amarmakwana** [comment]
@patrickhulce thanks for the explanation this helped me, thanks!

**Comment by ajoecker** [comment]
sorry for bringing this up again. Is the example above considered to be still working ?

If I use the examples above and run lighthouse on it I get

```
λ lighthouse https://example.com -A my-folder/                                                                          
  config:warn IFrameElements gatherer requested, however no audit requires it. +0ms                                     
  config:warn InspectorIssues gatherer requested, however no audit requires it. +3ms                                    
  Reading artifacts from disk: C:\dev\lighthouse-off\my-folder +17ms                                                    
Runtime error encountered: Unexpected token ' in JSON at position 0                                                     
SyntaxError: Unexpected token ' in JSON at position 0                                                                   
    at JSON.parse (<anonymous>)                                                                                         
    at Object.loadArtifacts (C:\Users\ajoec\AppData\Roaming\nvm\v14.4.0\node_modules\lighthouse\lighthouse-core\lib\asse
t-saver.js:48:26)                                                                                                       
    at Function.run (C:\Users\ajoec\AppData\Roaming\nvm\v14.4.0\node_modules\lighthouse\lighthouse-core\runner.js:63:32)
    at lighthouse (C:\Users\ajoec\AppData\Roaming\nvm\v14.4.0\node_modules\lighthouse\lighthouse-core\index.js:48:17)   
    at runLighthouse (C:\Users\ajoec\AppData\Roaming\nvm\v14.4.0\node_modules\lighthouse\lighthouse-cli\run.js:209:32)  
    at Object.begin (C:\Users\ajoec\AppData\Roaming\nvm\v14.4.0\node_modules\lighthouse\lighthouse-cli\bin.js:158:10)```

**Comment by ostrovanka** [comment]
I've got the same problem as @ajoecker  - could someone point out what is wrong? Looks like the example provided in this thread is not valid anymore
Thanks!

**Comment by patrickhulce** [comment]
More base artifacts have been added since that example. You'll need an `artifacts.json` that looks more like https://github.com/GoogleChrome/lighthouse/blob/85331168e3c52ff389f7053386f95556cc03049d/lighthouse-core/fraggle-rock/gather/base-artifacts.js#L16-L30
