### ISSUE TITLE
Does Google Tag Manager (GTM) affect PageSpeed Insights (PSI) score?

### ISSUE THREAD

**Issue by vimal-mozanta** [GoogleChrome/lighthouse#12745]
When I tried removing GTM script from my website, it improved the Lighthouse (LH) score for mobile by 5 points. 5 points for mobile is a big margin.
Does Google have any plan to ignore your own scripts in the performance audits (LH & PSI) going forward? 
FYI - I'm using async in my script 

`<script async src={`https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}`} />`

but still, it gives me a performance drop. Any advise on mitigating this issue is highly appreciated. 

Thanks

**Comment by patrickhulce** [comment]
> Does Google have any plan to ignore your own scripts in the performance audits (LH & PSI) going forward?

No, Lighthouse will not be doing this.

> I'm using async in my script, but still, it gives me a performance drop. Any advise on mitigating this issue is highly appreciated.

This is impossible to answer as GTM is really just a vehicle to deliver arbitrary JavaScript from *other* vendors (and possibly the site itself). *That* code should be as performant as possible to eliminate the performance impact here. This is beyond the scope of this issue tracker though, best of luck!

**Comment by vimal-mozanta** [comment]
@patrickhulce - Thanks so much for your response. 

Actually I thought one of the below option would be a possible solution.

1. Add resource hints to the domains of all new tags added by GTM. Minimises RTT - https://www.globaldots.com/resources/blog/googles-web-performance-best-practices-2-minimize-round-trip-times/
2. Develop a REST API which fetches all the JavaScript from external domains and inject it website. See below
`curl --location -g --request GET 'mydomain.com/trackingId={TRACKING_ID}' \
--header 'Accept-Encoding: application/javascript'`
