### ISSUE TITLE
lighthouse reprot genrate give this error : Required traces gatherer did not run

### ISSUE THREAD

**Issue by barotrahulh123** [GoogleChrome/lighthouse#12754]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://lighthouse-json.s3.us-east-2.amazonaws.com/www.toyotaofportland.com/2021-07-07T05%3A30%3A40.813Z.json

### What happened?

While i am trying to generate report usin npm lighhouse somtime gives error **Required traces gatherer did not run**  failed to generate report

### What did you expect?

please resolve this

### How were you running Lighthouse?

node

### Lighthouse Version

8.0.0

### Relevant log output

```shell
Required traces gatherer did not run*
```

**Comment by patrickhulce** [comment]
Thanks for filing @barotrahulh123! This is expected behavior. Please refer to the toplevel warnings property for the explanation as to why.

> Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403)

**Comment by mihuartuanr** [comment]
passes = [
    {
      passName: 'defaultPass',
      recordTrace: true,  // this can work for me, lighthouse version is 7.5.0
      gatherers: [
      ],
    },
  ]

**Comment by mihuartuanr** [comment]
```
passes = [
  {
     passName: 'defaultPass',
     recordTrace: true, // this can work for me, lighthouse version is 7.5.0
     gatherers: [
     ],
  },
]
```
