### ISSUE TITLE
Exporting lighthouse reports from Chrome

### ISSUE THREAD

**Issue by frankodoom** [GoogleChrome/lighthouse#12755]
It will be great if we can export the report from lighthouse, I am currently using screenshots. I believe an export to PDF or any image format will be very useful.

**Comment by adamraine** [comment]
You can print as a PDF using the three dots menu:

![Screen Shot 2021-07-07 at 10 47 08 AM](https://user-images.githubusercontent.com/6752989/124780552-aecbe180-df10-11eb-85b4-88c3dbd6c96a.png)

**Comment by frankodoom** [comment]
> You can print as a PDF using the three dots menu:
> 
> ![Screen Shot 2021-07-07 at 10 47 08 AM](https://user-images.githubusercontent.com/6752989/124780552-aecbe180-df10-11eb-85b4-88c3dbd6c96a.png)

Thanks @adamraine
