### ISSUE TITLE
Update third-party-web

### ISSUE THREAD

**Issue by PsychodelEKS** [GoogleChrome/lighthouse#12750]
"Third-party code" validator, which shows 3p code blocking the main thread, shows different codes aliases (like Amazon Ads, Google Fonts etc.), and for one of our products it displays wrong alias, how/where can this be addressed? 

![image](https://user-images.githubusercontent.com/102100/124497613-c5185700-ddc3-11eb-99ba-4f115a86f472.png)

**Comment by patrickhulce** [comment]
Thanks for filing! A pull request at https://github.com/patrickhulce/third-party-web/ would be greatly appreciated :)

**Comment by PsychodelEKS** [comment]
@patrickhulce regarding the issue, I can see our company listed in the 3rd party codes list where it should be (with matching and correct url masks), but in Chrome built-in Lighthouse, our product is though marked with wrong alias.
Is the source out of sync for aliases in current Chrome build or the issue is in the Lighthouse matching logic which is broken for high-depth sources URIs (PRODUCT.mgr.consensu.org)?

**Comment by patrickhulce** [comment]
> Is the source out of sync for aliases in current Chrome build or the issue is in the Lighthouse matching logic which is broken for high-depth sources URIs (PRODUCT.mgr.consensu.org)?

Ah, I think you're right it is out-of-date. We'll bump to latest 👍
