### ISSUE TITLE
Http to Https  redirection test with different external port numbers

### ISSUE THREAD

**Issue by pemo11** [GoogleChrome/lighthouse#12762]
Hello Developers,

I would like being able to configure the http to https redirection test with different port numbers.

If the http service uses the external port number 19077 for example and the https service the external port number 20077 during the http redirection test Lighthouse tries to access http://service-address:20077 which cannot work.

I am reffering to the Lighthouse report as part of the Chrome Developer tools.

Regards,
Peter

**Comment by adamraine** [comment]
We have plans to remove the http redirection audit entirely (#12614), so I don't see us doing this.

**Comment by pemo11** [comment]
Ok, thats good hear.
