### ISSUE TITLE
Confused about which url that is being audited.

### ISSUE THREAD

**Issue by abobakrd** [GoogleChrome/lighthouse#12763]
Im auditing multiple websites programatically, and noticed a "redirect warning" on the HTML report saying: 

> The page may not be loading as expected because your test URL (https://website.com/) was redirected to https://www.website.com/. Try testing the second URL directly.

The documentation for the PageSpeed Insights API however, says the opposite:
<html>
<body>
<h3>Response</h3>

property: lighthouseResult.finalUrl | type: string | value: The final resolved url that was audited.
-- | -- | --

</body>
</html>

Source: https://developers.google.com/speed/docs/insights/v5/reference/pagespeedapi/runpagespeed

In this case, the initial request URL (w/o `w3`) only responds with a `location` HTTP header (no response body) and audit scores are the same for both URL's, which makes it clear that it is the final URL being audited twice, like the documentation says. 

I also see others working in this repo recommending to test the second URL directly, so are the API docs wrong or right?

**Comment by connorjclark** [comment]
If you, I, or Lighthouse navigates to `https://website.com/` the browser will load the page, see the redirect, and then load that page. Lighthouse does not ignore this redirect and it impacts the score in various ways.

I'm not seeing any discrepancy in the docs you're citing. Is it this?

> The final resolved url ___that was audited___.

Both the initial and final urls are being audited. In your case, if you are seeing the same score I guess that means the direct is super fast and at the DNS level. If done by a slow application, you'll likely always see a score difference.

**Comment by abobakrd** [comment]
> I'm not seeing any discrepancy in the docs you're citing. Is it this?
>> The final resolved url _**that was audited.**_
Yes. That to me, seems like only the final resolved URL is being audited.

So does lighthouse merge all results obtained from each URL it audits? If so, I could see the performance scores being merged as useful (fast/slow redirect f.ex), but other scores being merged, such as HTML markup seems unnecessary because redirects only serves the purpose of redirecting, thus no useful HTML. 

Regardless, It would be really useful if you could pass a parameter to the PageSpeed Insights API that tells whether to audit the final resolved URL or not. It would save a lot of unnecessary API calls and speed up the process a lot.

**Comment by patrickhulce** [comment]
I think there's still some confusion @abobakrd.

Lighthouse analyzes **a single page load** using a URL as a starting point, following any redirects along the way. It does not analyze URLs. It is not possible to audit a URL that redirects without analyzing the redirected URL. Lighthouse is not merging any results, it's just that the performance metrics as defined by the browser are impacted by redirects which is not which most people expect so we add the warning there.

**Comment by abobakrd** [comment]
@patrickhulce Thanks for clarifying. So, lighthouse only analyzes the page load of the final resolved URL, but also includes the time of the redirects (if any) as a dataset of its own in the report, and as a part of the overall pagespeed?

**Comment by patrickhulce** [comment]
> So, lighthouse only analyzes the page load of the final resolved URL, but also includes the time of the redirects (if any) as a dataset of its own in the report, and as a part of the overall pagespeed?

Correct!
