### ISSUE TITLE
flaky smoke tests: bytes and perf

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#12773]
https://github.com/GoogleChrome/lighthouse/runs/3033220617

seems like nearly every run is failing, at least for perf

**Comment by connorjclark** [comment]
![image](https://user-images.githubusercontent.com/4071474/125368987-36aa5500-e330-11eb-8ba0-e578c7f872a4.png)

![image](https://user-images.githubusercontent.com/4071474/125369014-445fda80-e330-11eb-948d-ca499b7a5668.png)

**Comment by paulirish** [comment]
likely fixxed by #12779
