### ISSUE TITLE
Does a website going down affect Lighthouse performance score?

### ISSUE THREAD

**Issue by vimal-mozanta** [GoogleChrome/lighthouse#12774]
**Summary**
My website homepage's mobile performance has gone down from 27 to 12 in one month. There was no changes done to DOM or content in this period. 

The only problem we had was, the website was down for a total of 4 to 5 hours on two days during last 30 days. 

1. Can this affect the performance score? 
1.1. If yes, what would be a good solution to mitigate this? A maintenance page with good CWV scores during the downtime would help? 
1.2. If not, what can be the other possibilities? Marketing team adding more tags to GTM can be an issue?

**Comment by connorjclark** [comment]
No, lighthoise audits the page as it is in the moment.
