### ISSUE TITLE
8.0.0 does not recognize strict-dynamic header sent by site

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/lighthouse#12777]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://thomasbrodhead.com/

### What happened?

Windows 10
Chrome Canary Version 93.0.4573.0

Under Best Practices, Lighthouse fails my site (https://thomasbrodhead.com) for not having a strong CSP, issuing this message: 

Ensure CSP is effective against XSS attacks
A strong Content Security Policy (CSP) significantly reduces the risk of cross-site scripting (XSS) attacks. Learn more

I'm using a robust CSP that includes a script-scr with strict-dynamic. If you audit my site with the Google CSP tester:

https://csp-evaluator.withgoogle.com/

...it will show, among the other headers, 'script-src' with a nonce, like this:

script-src 'unsafe-inline' 'self' http: https: 'nonce-qYxgVxi3d/0zIpqOy2fapE2dVhVMp3ODdxVdXGK+' 'strict-dynamic' ;

I employ two top-level scripts that are nonced, and all subsequent scripts are called by them, making use of 'strict-dynamic'. (I also delete my scripts from the DOM after they've been attached and run.)

Is the Lighthouse auditor not reading the CSP header my site is sending?

### What did you expect?

A passing score on the strong CSP audit.

### What have you tried?

I've double checked my CSP using https://csp-evaluator.withgoogle.com/

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.0.0

### Chrome Version

93.0.4573.0

**Comment by tmb-github** [comment]
@patrickhulce What is the JavaScript source code for this audit?

**Comment by patrickhulce** [comment]
ah thanks for filing @tmb-github! we'll fix this.

FYI @adamraine audits that are `scoreDisplayMode: 'informative'` need to be marked `notApplicable` when they pass if we don't want them to show up. Otherwise they are still displayed in the report with no details. 

Does that make a lot of sense in this case? Not particularly, but that was the paradigm of our performance informative audits that were supposed to be displayed whether they were passing or failing when we developed that policy, they're just information. We can revisit that decision for v9 if you'd like :)

**Comment by tmb-github** [comment]
@patrickhulce FWIW, I think this audit is an excellent addition to Lighthouse. I adopted the 'strict-dynamic' CSP for my sites several years ago, but most developers I know simply give me a blank stare when I mention it. Including it in Lighthouse is a great way of getting the word out that sites need it for front-end security. The irony for me, though, is that the current audit somehow doesn't recognize that my site is employing it. :-(

**Comment by patrickhulce** [comment]
@tmb-github glad you think it will be valuable! 

FWIW, the audit does recognize it as passing (the `score` is `1`, the maximum possible score). It's a display issue that the result isn't being hidden even though the audit is passing.

**Comment by adamraine** [comment]
Right now, the score is set to 0 if there are high severity issues. Medium severity issues should not affect the score. For this reason, I think we should make `notApplicable` based on the number of warnings rather than the score so medium severity warnings aren't completely hidden.
