### ISSUE TITLE
WASM init might be heavily penalized in PSI

### ISSUE THREAD

**Issue by wothke** [GoogleChrome/lighthouse#12775]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.wothke.ch/websid_nogfx/

### What happened?

I am specifically refering to a "Device: Desktop" test (NOT "Device: Mobile"! - I could not care less whether or not my page runs on some old smartphone..)

Just for real-world comparison: When I call the test URL with developer tools enabled and "Disable cache" enabled, the page actually starts to play music in less than 1 second (i.e. EVERTHING must have been completely loaded by then - and the page obviously starts even faster without developer tools). That is on my 10 year old/slow PC running Win10, fetching all the data over a slow DSL copper telephone line from a server in a different country.

Lighthouse gives the page a (Desktop!) "Performance" score of 55 and specifically claims:

```
Metrics:
..
Time to Interactive: 13.1s
Total Blocking Time: 5.690ms
..

Diagnostics:
Minimize main-thread work: 16.5s
Reduce JavaScript execution time: 14.5s
..
```

### What did you expect?

The reported "Performance" numbers are utter garbage and they should at least somewhat correlate to a page that actually loads in less than a second.

In its current form the respective Lighthouse analysis is just totally useless.

### What have you tried?

As mentioned above. The numbers in the report have no correlation to actually observed page loading/startup bahavior.

PS: I wonder if Lighthouse just cannot deal properly with pages using WASM and/or WebAudio and/or "animation frames".

### How were you running Lighthouse?

Page Speed Insights

### Lighthouse Version

 Lighthouse 8.0.0

### Chrome Version

N/A

**Comment by wothke** [comment]
PS: running the test via 
`https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.wothke.ch%2Fwebsid&tab=desktop
`
leads to similar results, i.e. the problem still seems to affect that newer version.

**Comment by patrickhulce** [comment]
Thanks for filing! Unfortunately, as a "clueless Google Chrome idiot" I was unable to reproduce your issue as described in latest stable ;)

![image](https://user-images.githubusercontent.com/2301202/125203944-75f97880-e240-11eb-98aa-76ac3c5f0218.png)


Can you confirm the same?

The PSI issue is likely related to the fact that this page appears to be largely WASM and canvas-driven. PageSpeed Insights does not support hardware acceleration and falls back to software for many graphics APIs (hence the largely inflated main-thread time).

**Comment by wothke** [comment]
I created a stripped version that does no graphics: https://www.wothke.ch/websid_nogfx/  Even without any canvas rendering the effect still seems to be the same, so I'd guess that graphics related hardware accelleration is not the issue here.

I would characterize the page as being largely WebAudio and WASM driven.

How would I test the "latest stable" version without damaging my existing Chrome installation? (It was a pain in the ass to rollback the broken Chrome 90 release - see WebAudio ScriptNodeProcessor bug - which took Google 2 month to fix.. so I am in no mood to try whatever green bananas release Google is currently toying with. I'll rather stick to the older release that works well enough for me). If there is some "portable" release that does not touch my existing Chrome settings I'd be willing to test it.

I wonder if the fact that you cannot reproduce the issue on your machine might be related to the "WebAudio autoplay user engagement" crap.. on my machine the respective step is automatically skipped (I might have turned that useless feature off completely or it might just be due to the fact that I have already called respective pages sufficiently often on my domain.) Supposing that on your machine the page pauses at the intermediate modal "user engagement" dialog that might lead to different Lighthouse measurement behavior.

**Comment by patrickhulce** [comment]
> I wonder if the fact that you cannot reproduce the issue on your machine might be related to the "WebAudio autoplay user engagement" crap.. on my machine the respective step is automatically skipped (I might have turned that useless feature off completely or it might just be due to the fact that I have already called respective pages sufficiently often on my domain.) Supposing that on your machine the page pauses at the intermediate modal "user engagement" dialog that might lead to different Lighthouse measurement behavior.

That's certainly possible.

> How would I test the "latest stable" version without damaging my existing Chrome installation?

You can download the latest main branch Chromium from http://download-chromium.appspot.com/, unzip it to a tmp location, use a temporary profile `--user-data-dir=/tmp/foo` and then delete it when you're done. 

Note though that Lighthouse only supports latest stable without custom flags/experiments turned off. If this is what is causing the issue, we won't have the capacity to look into it.

> PS: what happens when you use the respective https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.wothke.ch%2Fwebsid&tab=desktop link? can you reproduce the issue there?

I can see the ridiculous main-thread time there as well. We'll look into it, since this appears to be unrelated to the graphics issue.

For Lighthouse team investigation, I see this script taking ~38 seconds in PSI but only ~3ms locally.

![image](https://user-images.githubusercontent.com/2301202/125210606-83c1f480-e266-11eb-9966-e28e141c2df4.png)

**Comment by wothke** [comment]
I just repeated my tests with the respective 93.0.4573.0 (Developer Build) (64-bit). And from what I see this version still has the same problem and the different measurement results indeed are caused by whether or not the "user engagement" logic prevents the auto-play:

At the first run the reported "Performance" score was now 96 (i.e. at that point the browser did not auto-play and Lighthouse considered the job done as soon as the respective modal-dialog was shown.. which of course is NOT the relevant test)

I then updated the "Privacy and Security > Site Settings > Sound" settings and added "www.wothke.ch" to the respective "Allowed to play sound" whilelist. When re-running the test, Lighthouse again reports a low "Performance" score around 60. With the same bloated values for: Time to Interactive, Total Blocking Time, Minimize main-thread work & Reduce JavaScript execution time

For good measure I replaced the WASM based impl on the https://www.wothke.ch/websid_nogfx/ page with a plain JavaScript one (i.e. one that I compiled to asm.js instead). Lighthouse's measurement result is not significantly different to the one using the WASM version, i.e. the problem is not WASM related but more likely WebAudio related.

PS: to my chagrin I see that the new Lighthouse version now complains about the deprecation of the "ScriptNodeProcessor" API.. trying to push people to use the unusable green banana "AudioWorkletNode" API instead..  seems some of you Google geniuses never learn :-(

**Comment by patrickhulce** [comment]
Nice find! I am able to reproduce with that option and this is working as intended. This page on my 2020 maxed-out Macbook generates a long task every 350 milliseconds for eternity. The metrics as defined will certainly penalize that heavily.

![image](https://user-images.githubusercontent.com/2301202/125216444-ce9e3500-e283-11eb-936e-26ad17efc0c8.png)

I'll also remind you that this issue tracker has a [code of conduct](https://github.com/GoogleChrome/lighthouse/blob/master/CODE_OF_CONDUCT.md#our-standards). While you're perfectly welcome to be upset about decisions Chromium makes, repeatedly insulting the people trying to help you probably won't get you as far with others in the future as it did here, best of luck to ya :)

**Comment by wothke** [comment]
Let me summarize: In its WebAudio related metrics Lighthouse does NOT consider the amount of audio data generated by an application but only the absolute runtime of one invocation, i.e. an application that uses a larger WebAudio sample buffer is automatically penalized as compared to it using a small sample buffer.
I am sure you are well familiar with the limitations of Chrome's WebAudio impl and are aware that its problems to keep up with continuous playback increase proportionally with decreasing sample buffer sizes (i.e. users will have a good experience while 16k-sample buffers are used, but they will have an abysmal experience with 1024-sample buffers due to the audio stuttering that smaller buffers will cause in Chrome.).

Let me guess - the application would get a great "Performance" score if it chose to use small 256-sample buffers since those could be served in 5ms. (hahahah.. indeed that's exactly what happens! when I use a 256-sample buffer the page gets a great "Performance" score - at the cost of a miserable user experience since Chrome is totally unable to then play those smaller buffers continuously.. )

So the conclusion here sadly is that Lighthouse's "Performance" reports are utterly useless when WebAudio is involved since they acutually advocate just the opposite of what actually leads to a better user experience. Seems there is no point for me to use your tool in the future.


PS: I don't see any "repeated insults" in my above posts - unless "genius" is considered offensive in the Google context.
PSS: you might want to restore my original title since your updated version obvisouly has no relevance to the actual problem
