### ISSUE TITLE
Viewing simulated trace in DevTools is confusing

### ISSUE THREAD

**Issue by tills13** [GoogleChrome/lighthouse#12788]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.alive.com

### What happened?

Run an audit, note the vital metrics displayed at the top of the panel

![image](https://user-images.githubusercontent.com/1269421/125677998-9c17c754-89d1-4ac7-9c14-9d970dffe35f.png)

Click "View original trace", click on one of the vital metrics, note that their timestamp is drastically different from what Lighthouse is reporting

![image](https://user-images.githubusercontent.com/1269421/125678184-a1d71dfc-1710-4a5c-a847-545e4bae575a.png)

### What did you expect?

The numbers in lighthouse match what is reported in the profile, or for there to be some reasonable explanation of this behaviour.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

7.2.0

### Chrome Version

91.0.4472.124

### Node Version

N/A

**Comment by tills13** [comment]
I should note that these numbers are often larger than the total time to render / load the page.

**Comment by tills13** [comment]
Using the following script to measure `lcp` performance events: 

```
new PerformanceObserver((entryList) => {
  for (const entry of entryList.getEntries()) {
    console.log(entry.startTime, entry.element);
  }
}).observe({type: 'largest-contentful-paint', buffered: false});
```

Lighthouse reports 3.2s, the script reports 2031.399.

**Comment by connorjclark** [comment]
Lighthouse by default is simulated. The original trace is without the CPU/network slowdown simulation. Otherwise you'd have to wait 4x longer for a report. There's an option to change this in the Lighthouse panel settings.

https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md

**Comment by connorjclark** [comment]
LH team, note the disclaimer here "Values are estimated and may vary ..."

maybe we can do better? "Values are estimated from a simulated, slower CPU and Network and may vary" iff simulated throttling.

**Comment by tills13** [comment]
Ah ok understood. I should have read that document more carefully when I ticked the box. Thanks for the reply.

**Comment by patrickhulce** [comment]
> maybe we can do better? "Values are estimated from a simulated, slower CPU and Network and may vary" iff simulated throttling.

Sure, SGTM. Given the existing FAQ, checkbox, and docs though, I'm not 100% sure it will be enough to prevent similar issues :)

**Comment by brendankenny** [comment]
I still think just not showing the "View original trace" button when simulated would prevent a lot of confusion. If there's an argument for debugging or for power users who don't want to use the CLI for some reason, the konami code or whatever could still open up the trace :)

**Comment by tills13** [comment]
> Otherwise you'd have to wait 4x longer for a report

Is there an issue with this? Seem like expected behaviour to me to wait longer for a "properly" throttled test.

**Comment by connorjclark** [comment]
You may be overestimating how long people like waiting for better results. Although, I'm not aware of any surveys we've done on the matter. @patrickhulce are you?

**Comment by tills13** [comment]
I'll concede I am a patient person.

**Comment by patrickhulce** [comment]
> Although, I'm not aware of any surveys we've done on the matter. @patrickhulce are you?

https://wpostats.com/tags/bounce%20rate/ people definitely don't like waiting 😉 

Haha, in all seriousness. I don't think we've conducted specific user studies about adding delays into Lighthouse results to see how people react or informal twitter polls. 

The "properly" throttled test metric IMO is WebPageTest. DevTools throttling has its own set of problems, though at least there, yes, the traces would match :)

**Comment by patrickhulce** [comment]
We'll remove the "View Trace" button in DevTools when simulated throttling is used to prevent this confusion in the future 👍

**Comment by tunetheweb** [comment]
Seen a few instances of this lately so would be very much in agreement to show this option only when non-simulated throttling is used (either in DevTools or CI)! Really think it would avoid a lot of confusion.
