### ISSUE TITLE
Repeatable freeze/timeout problem when testing www.telenor.com

### ISSUE THREAD

**Issue by OttoG** [GoogleChrome/lighthouse#12792]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.telenor.com/

### What happened?

I analyzed the website https://www.telenor.com/ (the corporate website of a major Northen European corporation) using the interactive Lighthouse interface. (Tried several times, restarting the browser inbetween.)

The report never finished, and while running, the console accumulated warning messages. In the latest run, I let it log about 140 000 warnings before cancelling (which is not easy, as the cancel button is half-hidden).

The exported log from the console is 47 MB in size, but most items are very similar to the following:

```
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:369
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:382
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:391
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:401
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/ico-menu-search.png"
Image (async)
onerror @ www.telenor.com/:337
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/ico-contrast.png"
Image (async)
onerror @ www.telenor.com/:353
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:360
```

This is what the interface looked like before I cancelled (note the warning count at the middle right):

<img width="1501" alt="Lighthouse-www telenor com" src="https://user-images.githubusercontent.com/5548343/125783628-99e50784-80c4-4734-897a-55dd8f405386.png">

These were the settings in use:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/5548343/125784218-28fd2f3f-42cf-4e53-b1cb-b0b4b7e87b77.png">

### What did you expect?

A finished Lighthouse report was expected.

### What have you tried?

I tried restarting the browser and checking that it is up to date, which it was: Version 91.0.4472.114 (Official Build) (x86_64)

I tried generating reports for multiple other websites, which consistently worked fine.

I also tried running Lighthouse programmatically using the "lighthouse" Node.js module, which gave the following error, after a delay of a minute or so. This might give some clues to where the error occurred. (In this case, however, the Lighthouse version was 8.1.0 – not 7.2.0 as when I ran it interactively.)

```
PROTOCOL_TIMEOUT
Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)
```

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

7.2.0 (and 8.1.0 when running from Node.js)

### Chrome Version

macOS 91.0.4472.114 (Official Build) (x86_64)

### Relevant log output

```shell
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:401
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/ico-menu-search.png"
Image (async)
onerror @ www.telenor.com/:337
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/ico-contrast.png"
Image (async)
onerror @ www.telenor.com/:353
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:360
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:369
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:382
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:391
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:401
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/ico-menu-search.png"
Image (async)
onerror @ www.telenor.com/:337
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/ico-contrast.png"
Image (async)
onerror @ www.telenor.com/:353
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:360
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:369
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:382
Request was blocked by DevTools: "https://www.telenor.com/wp-content/themes/telgr-desktop-theme/img/arrow-white-down.png"
Image (async)
onerror @ www.telenor.com/:391
```

**Comment by OttoG** [comment]
Here is the gzipped log from the browser console, by the way:

[www.telenor.com-1626349269152.log.gz](https://github.com/GoogleChrome/lighthouse/files/6823057/www.telenor.com-1626349269152.log.gz)

**Comment by patrickhulce** [comment]
Thanks for filing! 

This is a known issue caused by misbehaving page behavior (see https://github.com/GoogleChrome/lighthouse/issues/12382#issuecomment-826869326). The action item for Lighthouse is to craft a better error message that explains the page causes Chrome to become unresponsive (see https://github.com/GoogleChrome/lighthouse/issues/12636).
