### ISSUE TITLE
I want to know where the facts come from

### ISSUE THREAD

**Issue by kenakingkong** [GoogleChrome/lighthouse#12823]
**Summary**
I just want to know if I can find a public list of all the facts you guys display when lighthouse is auditing a site and generating a report. 

See example here:
![image](https://user-images.githubusercontent.com/33800408/126826510-63cbb0d9-edac-4199-832a-bbe3afca1597.png)

**Comment by connorjclark** [comment]
https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/panels/lighthouse/LighthouseStatusView.ts
