### ISSUE TITLE
"Open in viewer" is broken in devtools

### ISSUE THREAD

**Issue by joshunger** [GoogleChrome/lighthouse#12841]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.alltrails.com/hawaii/oahu

### What happened?

1. Open devtools > Lighthouse > Run report.
2. Click kebab menu > Open in Viewer.

### What did you expect?

EXPECTED: The current report opens in the Lighthouse Viewer Application.
ACTUAL: Does not open the current report and shows the upload page.
![image](https://user-images.githubusercontent.com/2301847/127873735-0b0fc321-13c2-4328-8c30-346edc7bcf03.png)

### What have you tried?

None.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.1.0

**Comment by connorjclark** [comment]
It isn't meant to be shown in DevTools right now... https://github.com/GoogleChrome/lighthouse/blob/2ecb2ea/lighthouse-viewer/app/styles/viewer.css#L124 should be hiding it, but is not.

#12557 enables support in DevTools, but landed after the 8.1 release. Unfortunately it is too late for Chrome 93. We have until Aug 14 to release a fix for Chrome 94. This will be a problem in stable from Aug 31 - Sep 21.

Could work out why that CSS isn't hiding the tooltip as expected, but the ideal fix here is just to cut another release (which will include #12557 which I know works).

> no longer works in devtools

To be clear, it never worked / was never available in DevTools before.

**Comment by joshunger** [comment]
@connorjclark got it thanks for the help and clarification!

**Comment by connorjclark** [comment]
> got it thanks for the help and clarification! Would you like me to edit the issue text?

No worries, I tweaked the title myself.

In the meantime we are adding a disclaimer to the viewer: #12846

We have a scheduled release on Aug 10, which will fix this issue, so I'll go ahead and close this.
