### ISSUE TITLE
Disable Devtools

### ISSUE THREAD

**Issue by juang93** [GoogleChrome/lighthouse#12842]
Good morning,

I need help with disabling devtools as it is not allowing me to work. Everytime I type in something, it comes up with that annoying window. I have tried in many ways to disable it and does not work. It keeps coming up. Would you please help me to fix it or to have instructions on how disable it?

Thanks

**Comment by adamraine** [comment]
This is not the place for DevTools bugs.

https://bugs.chromium.org/p/chromium/issues/entry
