### ISSUE TITLE
Error in lighthouse-core/gather/driver.js:322 from trying to instantiate new LHError

### ISSUE THREAD

**Issue by galal27** [GoogleChrome/lighthouse#12840]
### FAQ

- [ ] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### What happened?

**Context**: Running analysis on multiple URLs across multiple forked node child_processes. 
If anyone of the URLs in a particular child_process loop hits the following error: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)', the child_process immediately crashes despite being in a try-catch.

Upon further investigation into the logs, I found that the crash may be a result of an error when trying to instantiate a new LHError() in sendCommandToSession() and therefore cannot fail gracefully -- screenshot of log below. 

![Screen Shot 2021-07-30 at 5 43 40 PM](https://user-images.githubusercontent.com/43977732/127716294-3e8e572d-85a1-4567-911f-d929f6f0c4de.png)

I have seen multiple issues referencing analysis crashes due to PROTOCOL_TIMEOUT , mostly here #12837. However, nothing referencing this particular error with the Runtime.evaluate method. Figured I'd raise an issue in case anyone else was facing similar issue. 

**For reference:**

Code extract:
`try {
       const result = await lighthouse("http://" + url, options);
        return result.report;
} catch (e) {
         // WHEN AFOREMENTIONED ERROR OCCURS, DON'T GET HERE
         console.error(`Lighthouse failed to analyse ${url}`, e);
          throw e;
};`
chromeLauncher set up:
`const chrome = await chromeLauncher.launch({
      chromeFlags: [
        "--headless",
        "--no-sandbox",
        "--disable-gpu",
        "--disable-dev-shm-usage",
      ],
    });`

Lighthouse options:
`const options = {
      logLevel: "info",
      output: "json",
      onlyCategories: [
        "best-practices",
        "performance",
        "pwa",
        "seo",
        "accessibility",
      ],
      port: chrome.port,
      maxWaitForFcp: 45000,
      maxWaitForLoad: 60000,
    };`

### What did you expect?

Analysis to run smoothly or for error to fail gracefully thus being caught in catch-block.

### How were you running Lighthouse?

node

### Lighthouse Version

^8.0.0

### Chrome Version

90

### Node Version

16.5

**Comment by connorjclark** [comment]
> Running analysis on multiple URLs across multiple forked node child_processes.

At the same time? Running Chrome is not a trivial task, and running even more than one Lighthouse runs at a time is problematic. Resource contention will either impact the performance score, or in your case, result in timeout errors.

**Comment by galal27** [comment]
> At the same time? Running Chrome is not a trivial task, and running even more than one Lighthouse runs at a time is problematic. Resource contention will either impact the performance score, or in your case, result in timeout errors.

Running one Lighthouse run utilizing one browser at a time per 2 CPU core, I.e. on a 4 core system, there would be up to 2 runs at same time. Would you envision resource contention issues to arise even in that case?

_Removed variability check from FAQ as this issue is now indirectly linked_
