### ISSUE TITLE
Return total score in JSON and Pretty outputs 

### ISSUE THREAD

**Issue by sap1ens** [GoogleChrome/lighthouse#1285]
Right now you can get total lighthouse score only in one output type - HTML. JSON and Pretty output types don't show the total score. 

This makes things more complicated when you want to integrate lighthouse with CI, because in this case you have to parse HTML...

**Comment by lokson** [comment]
Hi @sap1ens, pull request added. One clarification: currently there is no total score for a whole lighthouse report, it is separate for every aggregate with number scores. Only 'Progressive Web App' is such an aggregate right now, but in future there may be more.

**Comment by sap1ens** [comment]
Thanks!
