### ISSUE TITLE
link-text audit: take aria-label or title into account?

### ISSUE THREAD

**Issue by wojtekmaj** [GoogleChrome/lighthouse#12864]
**Feature request summary**

Consider `aria-label` and/or `title` when evaluating links via link-text audit.

**What is the motivation or use case for changing this?**

I have a big, red "button" that says "Start" on the beginning of the application I'm coding. This "button" is rendered as `<a>` as it's handled by React-Router's `Link`. 

Given that's the only action the user can take on this screen I think it's pretty clear what's its purpose. 

link-text marked it, however, as non-descriptive. And I get that. Therefore I added `aria-label` and then `title` to help assistive technologies to further explain its purpose: "Start the application" (as in: thing that applicant is filling, not as in: app). This, however, had no effect on the audit.

**How is this beneficial to Lighthouse?**

For users not requiring assistive technologies, visual clues and context matters a lot and a link that says just "Start" may not only be enough, but can be the best option. 

When auditing link-text, additional attributes made for assistive technologies could be taken into consideration in order not to discourage creating good user experience for users not requiring assistive technologies.

**Comment by patrickhulce** [comment]
Thanks for filing @wojtekmaj! This audit currently is there for SEO purposes which last time we asked, search engines do not end up using aria-label / title on links that otherwise have text content (though I definitely agreed they should).

Until they do use this content, we'll continue to capture the concern expressed to us.
