### ISSUE TITLE
[Question] How to connect Lighthouse CLI to Android's app webview

### ISSUE THREAD

**Issue by wh-gp-ra** [GoogleChrome/lighthouse#12875]
I know how to connect to Google Chrome on Android (by forwarding `tcp:9222 localabstract:chrome_devtools_remote`), but I can't find how to run a lighthouse test for a debuggable webview in an app. Webview is visible in `chrome://inspect` and I can run an audit from there but I need to pass custom config to the LS test. 

Passing a config file through desktop Chrome would be also good enough for my use case but automating it with CLI would be even better.

**Comment by patrickhulce** [comment]
Thanks for filing @wh-gp-ra! You'll need to wait for #11313 to be able to audit existing pages. Right now Lighthouse always creates a *new* target from node/CLI which means you won't be able to audit the webview.

Also note that webviews have subtly different behavior from regular pages and Lighthouse may not work as expected in that context, we only target support of standard tabs.

**Comment by wh-gp-ra** [comment]
@patrickhulce Thank you for your response! Could you please share how does Google Chrome connects to the app's webview when it's not possible with CLI yet? And is there a way to use special config file with Chrome's Lighthouse audit?

**Comment by patrickhulce** [comment]
> Could you please share how does Google Chrome connects to the app's webview when it's not possible with CLI yet?

The DevTools integration is built specifically to keep the existing page intact. It does not use the same target creation path that the node/CLI uses.

> And is there a way to use special config file with Chrome's Lighthouse audit?

Not without *a lot* of work :) You could use a [custom-devtools-frontend](https://chromium.googlesource.com/devtools/devtools-frontend/+/refs/heads/chromium/3965/README.md#run-in-chromium) and modify the config used by Lighthouse, but it'd probably be easier to just redeploy the page in a way that's accessible from proper Android Chrome 😅

**Comment by wh-gp-ra** [comment]
> The DevTools integration is built specifically to keep the existing page intact. It does not use the same target creation path that the node/CLI uses.

Can you share more about that topic or point me to a place where I could learn it myself? I'm really interested _how_ that works. DevTools basically needs to communicate in a way that _should_ be reproducible using CLI Tools - a combination of `adb` and `lighthouse` probably?

> but it'd probably be easier to just redeploy the page in a way that's accessible from proper Android Chrome

That webpage is already exposed but in our hybrid app (webview + native components) we see different Lighthouse scores using DevTools.

**Comment by patrickhulce** [comment]
> Can you share more about that topic or point me to a place where I could learn it myself?

DevTools reimplements [its own custom connection class](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/panels/lighthouse/LighthouseProtocolService.ts;l=30-35) that does not create new targets like the node/CLI path does. 

This is the bit of code used by node/CLI that creates a new target to evaluate when lighthouse connects to Chrome.

https://github.com/GoogleChrome/lighthouse/blob/800ffd6da37e1be6712b04906d9abc701ff49fb6/lighthouse-core/gather/connections/cri.js#L36-L53

You would need to implement your own connection that skips this step in node.

> DevTools basically needs to communicate in a way that should be reproducible using CLI Tools - a combination of adb and lighthouse probably?

As seen above, it's not the communication *method* that's the problem, it's the fact that new targets are created.

**Comment by robertwt7** [comment]
I've been scratching my head a lot about this as well, I have been trying to run multiple lighthouse on different scenarios on webview programmatically since I had to run them 1 by 1. Luckily I found this thread 😅

**Comment by althaf101** [comment]
@patrickhulce 
Looks like [#11313 ](https://github.com/GoogleChrome/lighthouse/issues/11313) has been closed. Can we please re-open this for adding support to run lighthouse on existing web views ?

**Comment by adamraine** [comment]
You can audit an existing page using Puppeteer: https://github.com/GoogleChrome/lighthouse/blob/main/docs/puppeteer.md

Please keep in mind that we don't officially support auditing web views. As Patrick said:

> Also note that webviews have subtly different behavior from regular pages and Lighthouse may not work as expected in that context, we only target support of standard tabs.
