### ISSUE TITLE
[Programmatic Lighthouse] Performance category only run for some url

### ISSUE THREAD

**Issue by josecolella** [GoogleChrome/lighthouse#12887]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://gusto.com

### What happened?

I ran the lighthouse package with the following config:

```js
{
    extends: 'lighthouse:default',
    settings: {
      onlyCategories: ['performance', 'seo'],
      throttlingMethod: 'provided',
      budgets
 }
```

and I'm wondering why I'm only seeing SEO tests, and not seeing performance

`Running test https://gusto.com/tools/salary-paycheck-calculator-iowa?utm_source=lighthouse_test

Reporting to DataDog lighthouse_8.score = 1 [screen:desktop,page:tools_salary_paycheck_calculator_{state},category:seo,group:control]
`

### What did you expect?

I expected to see performance category being run

### What have you tried?

I have tried to specifically state performance as a category in the config.json

### How were you running Lighthouse?

node

### Lighthouse Version

8.2.0

### Node Version

v14.17.4

**Comment by connorjclark** [comment]
```
lighthouse https://www.example.com --view --only-categories=seo,performance
```

works fine for me. Are you sure the issue isn't with the way you send data to DataDog? It'd help if you provided the LHR json of the LH run.

**Comment by josecolella** [comment]
@connorjclark I can provide the json. I'm using the programmatic way of running lighthouse. Is the config.json that I've provided correct?

**Comment by josecolella** [comment]
I was able to fix the issue by using the following config

```js
const desktopConfiguration = require('lighthouse/lighthouse-core/config/desktop-config.js');
const mobileConfiguration = require('lighthouse/lighthouse-core/config/lr-mobile-config.js');
```

and doing 

```js
desktopConfiguration.settings = {...desktopConfiguration.settings, ...{onlyCategories: ['performance', 'seo']}}
```
