### ISSUE TITLE
LH DevTools `INVALID_URL` on some sites

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#12900]
This is happening for me on https://cnn.com and https://espn.com:

In canary, Lighthouse is warming up forever because of an `INVALID_URL` error.

![Screen Shot 2021-08-10 at 5 08 00 PM](https://user-images.githubusercontent.com/6752989/128935234-60047709-6fd1-40c0-8394-a629892f6b9a.png)

**Comment by adamraine** [comment]
Bisect
https://chromium.googlesource.com/chromium/src/+log/a3dbb157f3fa6b17e5e77a5e5756158c39c208c7..c2df1254b2cceff7b03cb8bade08958d7be7a286

**Comment by Mbellsudteen** [comment]
ในวันที่ ส. 2 ต.ค. 2021 00:54 น. Adam Raine ***@***.***>
เขียนว่า:

**Comment by Mbellsudteen** [comment]
ในวันที่ ส. 2 ต.ค. 2021 00:54 น. Adam Raine ***@***.***>
เขียนว่า:
