### ISSUE TITLE
About Lighthouse Treemap Chart

### ISSUE THREAD

**Issue by EYHN** [GoogleChrome/lighthouse#12918]
**Summary**

Hi everyone. I see that the lighthouse treemap is a very useful feature and I love it very much.

No offense, I found the [current treemap report display page](https://googlechrome.github.io/lighthouse/treemap/?debug) is a little sketchy, and I found the new design of the treemap report page in the [treemap todolist](https://github.com/GoogleChrome/lighthouse/issues/11254), and it also mentions 'Zoom in/out cursors' is delayed in completion.

I think I can make some improvements to the charting part of treemap. After my research the most famous treemap charts currently used in the webpack-bundle-analyzer are implemented in closed source and include a watermark. This is obviously unacceptable to us.

For this reason I implemented a webgl-based treemap chart myself. And i can provide a demo here [https://codesandbox.io/s/webgl-v-8kjt8](https://codesandbox.io/s/webgl-v-8kjt8)(scroll to zoom), i plan to open source it and release it to npm.

I would like to ask if you are interested in migrating the treemap charts to another implementation. Maybe I can also do some features based on lighthouse's needs.

Thanks.

**Comment by brendankenny** [comment]
@connorjclark and @paulirish are probably the best folks to answer this, though I'm not entirely sure what you mean by the word "sketchy". Maybe more specific feedback would be more clear?

Another option would be to open an issue on https://github.com/paulirish/webtreemap-cdt, which is the library we use.

**Comment by connorjclark** [comment]
I encourage exploration in additional treemap tooling, it'd be cool to see you work more on this.

Some issues with using WebGL for this, and what made it a non-starter for us, is that you get no help from the DOM wrt. accessibility. We invested in adding keyboard navigation to `webtreemap`, but if we had to build the _entire_ a11y tree it'd have taken a lot more effort to get right.

You could take a look at the LH Treemap data to make your own viz from Lighthouse data: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-treemap/app/debug.json

> Another option would be to open an issue on paulirish/webtreemap-cdt, which is the library we use.

+1 to filing specific issues on how to improve things there
