### ISSUE TITLE
Local Resources(file:///) highlighted as Render Blocking Resources

### ISSUE THREAD

**Issue by hariombalhara** [GoogleChrome/lighthouse#12915]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://local-resource-lighthouse-bug.glitch.me/

### What happened?

Lighthouse suggests removing a local(file:///) resource for an improved critical rendering path. Local Resources are blocked from loading, so this is a wrong suggestion.
<img width="1069" alt="Screenshot 2021-08-14 at 5 04 47 PM" src="https://user-images.githubusercontent.com/1780212/129445134-3bb7aa81-4507-4110-a505-8fcaa2ad36d4.png">

### What did you expect?

Local resources shouldn't be highlighted as Render Blocking Resources.

### What have you tried?

@patrickhulce acknowledged it as a bug.

### How were you running Lighthouse?

CLI

### Lighthouse Version

8.1.0

### Chrome Version

Chrome 90

### Node Version

v16.2.0

**Comment by hariombalhara** [comment]
@patrickhulce Here is the bug.

**Comment by hariombalhara** [comment]
Also, I have a question here. Should it cause an improvement in the Score as well once local resources are excluded?

**Comment by patrickhulce** [comment]
Thanks @hariombalhara !

> Should it cause an improvement in the Score as well once local resources are excluded?

Not directly, but we'll double check that the metrics aren't affected as well 👍
