### ISSUE TITLE
Cumulative Layout Shift get error

### ISSUE THREAD

**Issue by gyh9457** [GoogleChrome/lighthouse#12937]
![2021 08 19_郭延豪 c17654a39e9294595dcd06674f61686e](https://user-images.githubusercontent.com/13557235/130004975-8d221712-9a48-4d47-9fca-63912311b6ae.png)

I use lighthouse in docker , get the error

![image](https://user-images.githubusercontent.com/13557235/130005064-96c90875-3671-4bbf-97e5-b624eaf0be51.png)

I believe this version is high enough

Node Version: 12.20.0

**Comment by connorjclark** [comment]
latest chrome is 92. 81 came out in Apr 21 2020. CLS is a new metric and requires newer chrome.
