### ISSUE TITLE
CI smoke check broken on ToT Chromium download failure

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#12942]
example: https://github.com/GoogleChrome/lighthouse/pull/12940/checks?check_run_id=3375053749

The snapshot URLs have changed due to some recent Chromium infrastructure changed. Not clear if it's WAI or not, but `download-chromium.appspot.com` will have to be updated if an upstream fix to snapshot names isn't in the works. I opened a PR for that: https://github.com/beaufortfrancois/download-chromium/pull/68

We could
- ~wait it out~
- ~disable required ToT testing until fixed~
- hardcode a ToT URL in `lighthouse-core/scripts/download-chrome.sh` until something is fixed
- ~something else?~

**Comment by adamraine** [comment]
> hardcode a ToT URL in lighthouse-core/scripts/download-chrome.sh until something is fixed

This seems like the best option if it's not too much work.

**Comment by brendankenny** [comment]
> > hardcode a ToT URL in lighthouse-core/scripts/download-chrome.sh until something is fixed
> 
> This seems like the best option if it's not too much work.

done: #12943
