### ISSUE TITLE
Displaying First Paint is slow

### ISSUE THREAD

**Issue by nickcartery** [GoogleChrome/lighthouse#12947]
**Summary**
Can you tell me what happened is going on the red square? Have a blank space in there. And I don't know how to reduce it
![image](https://user-images.githubusercontent.com/10054833/130245627-4953070e-c4f2-4954-bbf1-5f1dd090b2de.png)

**Comment by adamraine** [comment]
Is this issue related to Lighthouse? If so can you provide the URL used for this performance trace?

**Comment by jorgellose** [comment]
Newsletter.js finish just in that moment, could be the problem

**Comment by nickcartery** [comment]
> Newsletter.js finish just in that moment, could be the problem

I've set defer for newsletter.js , so I think it's not the issue

**Comment by nickcartery** [comment]
> Is this issue related to Lighthouse? If so can you provide the URL used for this performance trace?

I profiling in Chrome devtools, Lighthouse also use it. I'm not sure it's the Lighthouse issue or not :D Also this project is still in development, so I cannot provide a URL

**Comment by connorjclark** [comment]
Sorry, this isn't a generic help forum, it's our bug tracker.
