### ISSUE TITLE
"URL responds with a 200 when offline" fails incorrectly

### ISSUE THREAD

**Issue by unindented** [GoogleChrome/lighthouse#1296]
**Lighthouse Version**: 1.3.2
**Chrome Version**: 55.0.2883.95

When I run Lighthouse against <https://unindented.github.io/little-yam/>, it fails the "URL responds with a 200 when offline" check, even though the Service Worker is correctly installed, and the page does work offline.

Do you know what could be happening?

**Comment by ebidel** [comment]
This may have something to do with the fact that the request that actually gets cached is for index.html

<img width="774" alt="screen shot 2016-12-25 at 12 53 21 pm" src="https://cloud.githubusercontent.com/assets/238208/21472463/30ec9666-caa1-11e6-9025-b68fbaa7f09f.png">

There's also a redirect to https://unindented.github.io/little-yam/#/login?_k=dt915a on page load, which might be causing https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/offline.js#L28 to fail. e.g. the URL we're looking for to be offline is not the URL you've cached to be offline.

**Comment by unindented** [comment]
@ebidel I'm just using `sw-precache` through [sw-precache-webpack-plugin](https://www.npmjs.com/package/sw-precache-webpack-plugin). Should I be doing anything different?
