### ISSUE TITLE
Lighthouse LCP time is different from Original Trace LCP time in Chrome 95 but matched in Chrome 92

### ISSUE THREAD

**Issue by joshunger** [GoogleChrome/lighthouse#13000]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.alltrails.com/fr/trail/france/haute-savoie/cirque-du-fer-a-cheval-pas-du-boret-le-bout-du-monde

### What happened?

**⚡ Note: We're using React SSR and setting innerHTML in Suspense. I don't know if this is related.**

I ran lighthouse and looked at the lighthouse LCP time. The report showed an LCP time of 4.8 seconds. I clicked on View Original Trace. Clicked on LCP and viewed the Summary tab. The Summary tab showed Timestamp 1731.0 ms. I'm hoping it is 1731.0 ms!

![image](https://user-images.githubusercontent.com/2301847/131594459-dc8db71c-4f8c-4f2f-bdca-68c0d3363faa.png)

![image](https://user-images.githubusercontent.com/2301847/131594437-46963079-5012-4677-8f22-9c457a8c77f3.png)

![image](https://user-images.githubusercontent.com/2301847/131594837-ea977a7a-0e38-435e-986e-12a1d59575ac.png)

### What did you expect?

Shouldn't these numbers match? These numbers did match in Chrome 92.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.3.0 and 7.5.0

**Comment by adamraine** [comment]
This is expected. By default throttling is applied after the performance trace is taken. https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md

**Comment by adamraine** [comment]
If you turn off "Simulated throttling" in the Lighthouse settings, the metrics should match the trace because Lighthouse will use DevTools throttling.

**Comment by joshunger** [comment]
@adamraine verified. They match now. Thank you for the help.

**Comment by joshunger** [comment]
@adamraine If you think a small PR that would add an "*" or a calculation in the details when throttling is turned on would be helpful and it would be a good first PR please let me know and I can submit one.
