### ISSUE TITLE
Audit: Recommend CSP in headers instead of in-HTML

### ISSUE THREAD

**Issue by pmeenan** [GoogleChrome/lighthouse#13004]
Chrome 95 will initiate fetches resources discovered by the preload scanner sooner that previous versions but only if the page was not loaded through app cache (not an issue as app cache is dead) and also if there was no CSP detected in the HTML that was scanned. Otherwise it needs to wait for the main HTML parser to be initialized and to reach and process the CSP tokens.

If the CSP rules are in the HTTP headers then there is no additional delay (which can be on the order of hundreds of ms for slow devices).

An audit that detects in-html CSP and recommends moving it to headers would be a relatively easy performance win for sites. The amount of the speedup can be estimated from the delta between when the response started for the HTML and the first sub-resource fetch started (should reduce close to zero).

If I get some time I can take a crack at adding the audit.

**Comment by patrickhulce** [comment]
Thanks for sharing @pmeenan that's great to know! Sounds like a great perf audit candidate 👍

**Comment by adamraine** [comment]
We already recommend this under best practices in `csp-xss`, but another audit under performance would still be worthwhile imo.

**Comment by adamraine** [comment]
@pmeenan is this still a priority? It seems like the preload scanner issues could be fixed on Chrome's side in this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1458493

https://github.com/GoogleChrome/lighthouse/pull/14878 is currently blocked because this issue isn't well documented. Should we focus on adding documentation or should we expect future updates to Chrome making #14878 obselete?

**Comment by pmeenan** [comment]
FWIW, I think the preload scanner changes have been reverted so a CSP "anywhere" in the document won't break preloading anymore but it still will if it isn't near the beginning of the document.

That said, it can likely be "fixed" on the Chrome side even with the old preload scanner just by queuing up preloads if there is a CSP that is pending being processed so I'm not sure it's worth asking devs to work around the Chrome issues.

**Comment by adamraine** [comment]
Thanks, it seems like a performance audit for this advice is a bit aggressive right now. I'm going to close this, but we can revisit if changes in Chrome cannot address this.
