### ISSUE TITLE
lighthose, show images that not exists on my site

### ISSUE THREAD

**Issue by wilcor** [GoogleChrome/lighthouse#13018]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.limatics.com/

### What happened?

Hello,
When i thest my web page, the result detect images inside picture TAG as JPG or PNG. Also it shows images like this: /829-home_default/modelo-e21a-de-acero-antivandalico-.jpg but i check te webpage source i only see webp format image.

### What did you expect?

That images inside picture tag will be recognized as webp instead jpg. Also remove the image that does not exist on the webpage source.

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools

### Lighthouse Version

100.0.0.0

**Comment by connorjclark** [comment]
dupe #12923
