### ISSUE TITLE
Integrate link content icon check

### ISSUE THREAD

**Issue by John-H-Smith** [GoogleChrome/lighthouse#13026]
**Feature request summary**
In the 'Links do not have a discernible name' issue, the link content is not checked if there is a font awesome icon inside.
As this is a common practice it would be great to get this checked by lighthouse.

**Comment by connorjclark** [comment]
I'm curious, which icons from FA were you hoping to use as link text w/o triggering the LH failure audit?

**Comment by John-H-Smith** [comment]
Right now, I can reproduce it for the following:
```
<a href="https://facebook.com/"><i class="fa fa-facebook"></i></a>
<a href="https://twitter.com/"><i class="fa fa-twitter"></i></a>
<a href="https://pinterest.com/"><i class="fa fa-pinterest"></i></a>
<a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
```

**Comment by connorjclark** [comment]
This check comes from [Axe](https://dequeuniversity.com/rules/axe/4.4/link-name) and is WAI. You should add an `aria-label` to describe the link (just `Facebook` would work), otherwise visually impaired users won't be able to easily discern where these go.
