### ISSUE TITLE
Robots txt audit is flaky in FR smoke tests

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#13024]
**Summary**
I've been starting to see flaky failures of the robots.txt audit in FR smoke tests (example: https://github.com/GoogleChrome/lighthouse/pull/12969/checks?check_run_id=3548610674#step:7:895) if this happens to anyone locally or you find more examples, it'd be good to start collecting for patterns.

**Comment by connorjclark** [comment]
#13010 will help
