### ISSUE TITLE
Can not webpack lighthouse to one single file to run

### ISSUE THREAD

**Issue by spldmanager** [GoogleChrome/lighthouse#13025]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

localhost

### What happened?

I want to webpack lighthouse lib to one single file to run, but when I webpack it and run ,there comes a error

### What did you expect?

1. webpack a.js file which requires lighthouse
2. successully generate one single file b.js
3. node b.js and it runs well

### What have you tried?

1. webpack a.js file which requires lighthouse --> done no error
2. successully generate one single file b.js --> done no error
3. node b.js and it show error below

fs.js:185
  return (stats[1/* mode */] & S_IFMT) === fileType;
               ^

TypeError: Cannot read property '1' of undefined

4. comment “require('lighthouse')” repeat step 1~3, no error

### How were you running Lighthouse?

node

### Lighthouse Version

5.6.0

### Chrome Version

79

### Node Version

14

**Comment by connorjclark** [comment]
See our build-bundle folder for how we do it.

Even then, this won't work as you likely expect. When rubbing Lighthouse in the browser in normal userspace there is no access to the necessary Chrome DevTools protocol.

You can view our git history to find the hacks we did to make the old chrome extension work, but I wouldn't recommend it.
