### ISSUE TITLE
Use fraction score for non-performance categories

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#13022]
Fraggle Rock has this new UI for categories in timespan, snapshot:

![image](https://user-images.githubusercontent.com/39191/133303233-754aca49-5152-4833-aab7-dc1308ed2033.png)
![image](https://user-images.githubusercontent.com/39191/133303306-826ba540-6872-4294-8de4-da1dabb2b1da.png)
![image](https://user-images.githubusercontent.com/4071474/132562230-c68d691a-8940-4f3e-b43e-9d6dd358cf3d.png)

Largely because (for performance): there are not enough metrics to calculate the real performance score and (for others): many audits are just n/a so showing the fraction is revealing the nature of "this is a checklist of things we looked at"

I think we could use this UI for Best Practices, SEO, and A11y in the normal report (and navigation report) too. This would leave Performance as the only category with a report-visible 0-100 score. I think this makes sense because for BP, SEO, A11y... a 100 isn't saying "You did it! job done!"... but rather "We looked at x things and you were good on all x of them", which highlights the checklist nature of what we're doing. Performance is much more objective because it is based off metrics, so a 0-100 score there makes sense.

**Comment by patrickhulce** [comment]
I'm supportive of this direction for v9 👍 

See more discussion in https://github.com/GoogleChrome/lighthouse/pull/13009#issuecomment-914782956

Specifically...

> There's been a lot of pushback on a11y in particular for mistakenly conveying "100" when there's a lot not covered. Switching to a fraction helps alleviate that and remind folks it's not comprehensive.

**Comment by adamraine** [comment]
> See more discussion in #13009

Instead of making snapshot a11y look like navigation a11y, make navigation a11y look like snapshot a11y. SGTM.

**Comment by brendankenny** [comment]
Possible issues:
 - this asks users to understand two different scoring mechanisms and figure out why they're different
 - assumes that `44/44` appears to be less comprehensive coverage of accessibility issues than a score of 100

Neither are necessarily showstoppers but seems like the kind of thing the recent UXR studies have shown are good to put in front of users?

**Comment by connorjclark** [comment]
Paul brought up weights. Adding to #12996, an alternative conclusion besides "make weights in the report more clear" is to drop weights for non-performance category.

**Comment by patrickhulce** [comment]
Our consensus here is that it is too drastic of a change to explore for the standalone report, but we will adopt this pattern for the flow report.
