### ISSUE TITLE
Lighthouse 8.4.0 reports LCP image not lazily loaded, yet it has loading="lazy"

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/lighthouse#13048]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://thomasbrodhead.com/

### What happened?

The Performance Diagnostics report states "Largest Contentful Paint image was not lazily loaded" and identifies an IMG that has loading="lazy", which should pass the audit.

![img01](https://user-images.githubusercontent.com/15718749/132971995-88768a24-b3c5-4407-b771-8ece85ed460b.jpg)

![img02](https://user-images.githubusercontent.com/15718749/132972004-b77afac7-2a25-416c-bd8b-c957b4cbaf26.jpg)

### What did you expect?

The audit should have passed, since the LCP image has loading="lazy" as an attribute.

### What have you tried?

The HTML should make it clear that it's a bug.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.4.0

### Chrome Version

96.0.4639.2

**Comment by patrickhulce** [comment]
Thanks for filing @tmb-github! This is a bug in the display string, but the audit logic is correct.

LCP images should *NOT* be lazily loaded.

#13049 fixes this string description bug.
