### ISSUE TITLE
Report UI: performance metrics are shown too tight when there are additional ones present

### ISSUE THREAD

**Issue by niieani** [GoogleChrome/lighthouse#13070]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

n/a

### What happened?

We run LH multiple times in different configurations and merge the result, since it's still related to a single commit. For most other audits and categories this is fine, but additional performance metrics aren't being rendered well, as you can see in this screenshot:

<img width="762" alt="Screen Shot 2021-09-15 at 2 06 38 PM" src="https://user-images.githubusercontent.com/563469/133509850-58903677-378b-4e3e-ba4e-d7829aa6e46e.png">

### What did you expect?

Instead of only generating columns for other metrics, rows should have been added too so the metrics aren't squished together too tightly. Or an alternative grid-based/responsive metrics list should be explored.

### What have you tried?

n/a

### How were you running Lighthouse?

node

### Lighthouse Version

8.3.0

**Comment by connorjclark** [comment]
Can you provide the JSON/LHR you've made for this? Would like to see what this looks like with our new report (We've yet to release some changes to this metrics table)

**Comment by paulirish** [comment]
fwiw these are the new changes: https://github.com/GoogleChrome/lighthouse/pull/13036. i feel pretty decent that it will render pretty decently for your usecase

**Comment by niieani** [comment]
Here's an example LHR: https://gist.github.com/niieani/6a089c5522e5c81736bc1cc5df5fe15f

Good to know there's some work in progress around the way these metrics are being rendered!

We're actually considering running many more configs and merging them into a single LHR to have a unified picture of the app: definitely at minimum a cached and uncached versions; maybe even various navigations/snapshots using Fraggle Rock.

**Comment by adamraine** [comment]
Latest report looks good with this LHR. Example: https://googlechrome.github.io/lighthouse/viewer/?gist=792d848911899c84d1cba6ab09e82f61.

**Comment by niieani** [comment]
Thanks Adam!
