### ISSUE TITLE
lighthouse audit cumulative-layout-shift gets failed after lighthouse package updation to 8.0.0

### ISSUE THREAD

**Issue by Franklin-Jose** [GoogleChrome/lighthouse#13087]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.w3schools.com/cssref/pr_class_display.asp

### What happened?

error: cumulative-layout-shift audit got failed 
Error: Lighthouse metrics got failed for cumulative-layout-shift

### What did you expect?

In lighthouse package version 7.0.0 audit worked properly and cumulative-layout-shift score is obtained.
After lighthouse package version updation to  8.0.0, cumulative-layout-shift gets failed for all audits.

### What have you tried?

Tried changing flags.formFactor to desktop and mobile.
flags.disableDeviceEmulation = false;
flags.formFactor = "desktop";
flags.throttlingMethod = "provided";
flags.disableScreenEmulation = false;
flags.disableNetworkEmulation = false;
flags.screenEmulation= {disabled : false, mobile:false};

### How were you running Lighthouse?

node

### Lighthouse Version

8.0.0

### Chrome Version

Google Chrome 69.0.3497.100 

### Node Version

v16.9.1

### Relevant log output

```shell
19-09-2021 15:52:16  info: starting audit for url https://www.w3schools.com/cssref/pr_class_display.asp in thread 0
19-09-2021 15:53:16  error: cumulative-layout-shift audit got failed err re-running for the url https://www.w3schools.com/cssref/pr_class_display.asp in thread 0
19-09-2021 15:53:16  error: Exception in runLighthouse method Error: Lighthouse metrics got failed for cumulative-layout-shift
    at runLighthouse (/home/sas/rep/Lighthouse-Reporter/index.js:272:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by adamraine** [comment]
We can't guarantee Lighthouse 8.0.0 supports a Chrome version as old as M69 unfortunately. Lighthouse runs fine on the provided URL with the latest version of Chrome.
