### ISSUE TITLE
The "unsized-images" rule should not trigger on images within <picture> tags

### ISSUE THREAD

**Issue by thurfir** [GoogleChrome/lighthouse#13098]
Images within `<picture>` tags can have multiple ratios, as described by the "What about art direction?" problem described here: https://web.dev/optimize-cls/#images-without-dimensions

> Pages may wish to include a cropped shot of an image on narrow viewports with the full image displayed on desktop.
> 
```
 <picture>
   <source media="(max-width: 799px)" srcset="puppy-480w-cropped.jpg" />
   <source media="(min-width: 800px)" srcset="puppy-800w.jpg" />
   <img src="puppy-800w.jpg" alt="Puppy with balloons" />
 </picture>
```
> 
> It's very possible these images could have different aspect ratios and browsers are still evaluating what the most efficient solution here should be, including if dimensions should be specified on all sources. Until a solution is decided on, relayout is still possible here.

Setting an width/height on the `<img>` override the image ratio for all `<source>` in the `<picture>`.
There is currently no attribute to specify a different width/height for each `<source>`, so this rule should not trigger in that case.

**Comment by patrickhulce** [comment]
Thanks for filing @thurfir! It's true the width/height attribute solution does not work for art direction images, but explicit dimensions/aspect ratios defined in CSS still would (which can reuse the same media breakpoints in your `<picture>`).

I think from Lighthouse's perspective it's still valuable to flag these for this reason and perhaps the right path forward here is updating that article/the docs on how to accomplish this.

**Comment by thurfir** [comment]
Thank you @patrickhulce , I was under the impression this rule was valid for a width+height attributes only!
Updating the error message and the documentation would be great indeed.

For documentation, and from what I understand now from reading the source, to improve the CLS for images we can either:

- Set a width + height attribute
- Set a width + height in CSS (in page or in a non async/deffered file)
- Set a width + aspect ratio in CSS
- Set a height + aspect ratio in CSS

The CSS needs to be inlined or in a non-async/deffered file.
The width can be declared as percent in the CSS.

Am I correct now?

**Comment by patrickhulce** [comment]
Yes, you are correct! If you find Lighthouse still flagging an image that meets those criteria, it's a bug we'd be happy to look into.
