### ISSUE TITLE
ServiceWorker events aren't triggered

### ISSUE THREAD

**Issue by christian-bromann** [GoogleChrome/lighthouse#13127]
**Summary**

Hey,

we are currently working on integrating Google Lighthouse into [WebdriverIO](https://webdriver.io/) so that people can run performance and PWA checks as part of their e2e tests, powered by Lighthouse. We struggle capturing all necessary data for service workers, it seems that some necessary events aren't triggered and/or some domains aren't enabled. If a PWA page is loaded (e.g. [webdriver.io](https://webdriver.io/)), we receive:

```js
{
  versions: [
    {
      versionId: '0',
      registrationId: '0',
      scriptURL: 'https://webdriver.io/sw.js?params=%7B%22offlineMode%22%3Afalse%2C%22debug%22%3Afalse%7D',
      runningStatus: 'starting',
      status: 'new',
      scriptLastModified: 0,
      scriptResponseTime: 0,
      controlledClients: [],
      targetId: '95432B44D4DB8620E7B9509D94E698E7'
    }
  ]
}
```
but for some reason, the Service Worker is never installed. The only way to trigger the SW events to happen is by opening DevTools and trigger a network event (e.g. open a subpage which causes the browser to load more JS files).

Sorry if this is not directly connected to Lighthouse itself but I wonder if you have a clue why the SW is not being installed without opening DevTools and triggering a network event?

**Comment by adamraine** [comment]
LH failed to notice the SW one time on https://webdriver.io/ but I haven't been able to reproduce it on 10+ retries. It's likely that was just some random flake and a separate issue from the consistently reproducible one you're talking about.

I took a quick peak at your PR, https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver/service-workers.js isn't designed to be used externally. Service worker events might only be flushed if `ServiceWorker` domain is enabled after being disabled. I would make sure `ServiceWorker` is disabled when those functions are called. If that doesn't work I would suggest making a min repro and filing a bug with DevTools.

**Comment by christian-bromann** [comment]
Thanks for the response. While trying to work on a reproducible example I found the reason why these events didn't come in. It was because the `GathererDriver` was initiated incorrect, fixed it with:

```js
    const c = session.connection().url()
    const cUrl = new URL(c)
    const connection = new ChromeProtocol(cUrl.port, cUrl.hostname)
    const list = await connection._runJsonCommand('list')
    await connection._connectToSocket(list[0])
    return new Driver(connection)
```

Which allows me to connect to an existing Puppeteer session. Thanks for the helpful response.
