### ISSUE TITLE
Checking a site on a non standard port

### ISSUE THREAD

**Issue by CqN** [GoogleChrome/lighthouse#13126]
I am trying to use lighthouse to audit a url on a non standard port.
https://example.com:5555/sample

Running from ChromiumOs 89 (CloudReady).

I am fairly a new user of LH, so I may be observing something incorrectly. I think currently light house checks for  auto http to https implementation by probing
http://example.com:80/sample

The server does not have an open 80 port. So the above http probe would fail. 

Would it not be more proper to test if
http://example.com:5555/sample responds properly with correcly by ssl?

My experiments show that url
https://example.com:5555/sample
can be installed as a proper pwa on Chromoium Os v89 (CloudReady), and on Android 10 (OxygenOs Version 10.0.1) on ONEPLUS A5010.

**Comment by adamraine** [comment]
We plan to remove the http redirect audit (https://github.com/GoogleChrome/lighthouse/issues/12614) so there probably won't be any changes to the audit.

**Comment by CqN** [comment]
Adam, when do you this removal could take effect on chromeos?


Cordially, Chacko
Fm mobile, often by dictation, pardon the errors.

**Comment by adamraine** [comment]
The change is planned for November 9, and will probably ship with [Chrome 98](https://chromiumdash.appspot.com/schedule)

**Comment by Mbellsudteen** [comment]
ในวันที่ ส. 2 ต.ค. 2021 04:05 น. Adam Raine ***@***.***>
เขียนว่า:

**Comment by Mbellsudteen** [comment]
ในวันที่ ส. 2 ต.ค. 2021 03:58 น. CqN ***@***.***> เขียนว่า:

> Adam, when do you this removal could take effect on chromeos?
>
>
> Cordially, Chacko
> Fm mobile, often by dictation, pardon the errors.
>

**Comment by Mbellsudteen** [comment]
ในวันที่ ส. 2 ต.ค. 2021 03:50 น. Adam Raine ***@***.***>
เขียนว่า:
