### ISSUE TITLE
Service worker registered too late for Lighthouse to detect

### ISSUE THREAD

**Issue by SirJackovich** [GoogleChrome/lighthouse#13138]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://beta.familysearch.org/africa/

### What happened?

I have built a PWA that is installable but when I run the lighthouse check it fails saying it is not installable.

![Screen Shot 2021-09-29 at 9 02 34 AM](https://user-images.githubusercontent.com/6645246/135295676-b3761a66-6811-4cf1-9c00-f2953bf542f5.png)

![Screen Shot 2021-09-29 at 9 03 32 AM](https://user-images.githubusercontent.com/6645246/135295869-8b53ef89-52f3-43da-9d5f-be35a5dff6f7.png)

![Screen Shot 2021-09-29 at 9 03 54 AM](https://user-images.githubusercontent.com/6645246/135295947-53ea4bf7-6549-4142-bf05-e438e9c41b4e.png)

### What did you expect?

I expected the check to pass, the app is installable but for some reason lighthouse does not think it is. 

### What have you tried?

Updating the manifest.json with different config options. 

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.3.0

### Chrome Version

Version 94.0.4606.61 (Official Build) (x86_64)

### Node Version

14

**Comment by rvsheffer** [comment]
@SirJackovich and I are on similar type teams within FamilySearch, and we are experiencing this with our app as well (although it is still very much a work in progress -- in beta -- the link is here: 

[FamilySearch Kids](https://beta.familysearch.org/discovery/kids)

**Comment by Heatmanofurioso** [comment]
Any news on this issue?

I'm also running an app, currently testing PWA capabilities on my QA environment, and the app is installable, the service worker seems to work correctly, but according to Lighthouse, it's missing the service worker

**Comment by connorjclark** [comment]
@Heatmanofurioso Thanks for the report, that error case does look interesting, however without a URL for us to poke and prod at debugging is impossible for us :(

**Comment by Heatmanofurioso** [comment]
Hi @connorjclark 
I can share the url for now, and tomorrow I can do both the cli test and attempt to recreate a small reproducible use-case in an open-sourced repo or gist ‘I’m a bit tight on time for the latter, but I will try’. I did develop this solution using Angular 13 and Angular PWA. Would this be an issue regarding in getting a reproducible use-case?

As for the link for my QA. It is the following `https://gigger.ddns.net`

**Comment by Heatmanofurioso** [comment]
@connorjclark I'd like to confirm that running on the latest Node CLI app, I do get a correct response saying my app is valid as a PWA.

The specs are as following "Same ones used to run the browser app":

- Lighthouse: `9.1.0` 
- Node: `16.13.0`
- OS: `Windows 11 Version 10.0.22000 Build 22000`
- Browser 1: Brave: `Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)`
- Browser 2: Chrome `Version 96.0.4664.45 (Official Build) (64-bit)`
- Also tested on Firefox

**Comment by Heatmanofurioso** [comment]
Any possible news on this issue?

Would it still be useful to make a reproducible example?

**Comment by Heatmanofurioso** [comment]
The issue seems to haven been fixed somehow on Web.dev and running the Chrome tool.

I have made no change to my production code whatsoever

**Comment by connorjclark** [comment]
In the image in your original post, what was the "1 reason" Lighthouse found? Do you recall?

![image](https://user-images.githubusercontent.com/4071474/145091542-20a7fad4-3685-4225-955d-1d845b3ebc41.png)

#13396 details a bug we have running LH in DevTools on pages w/ service workers.

**Comment by adamraine** [comment]
Based on what you've reported it was most likely https://github.com/GoogleChrome/lighthouse/issues/13396.

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
