### ISSUE TITLE
CLS is not capped at 5 seconds inside the Core Web Vitals display in the Rendering tab of Chrome Canary

### ISSUE THREAD

**Issue by fablau** [GoogleChrome/lighthouse#13140]
**Describe the bug**
Core Web Vitals display in the Rendering tab of Chrome Canary is not capping CLS at 5 seconds.

**To Reproduce**
1. Open Developer Tools in Chrome Canary
2. Activate the Core Web Vitals inside the Rendering tab
3. Measure CLS on a webpage where the user can shift its content arbitrarily like the browsing of this sheet music title on this page: https://www.virtualsheetmusic.com/score/Moonlight.html
4. You'll see the CLS measurement keeps accumulating even over 5 seconds.

**Expected behavior**
The CLS measurement should stop at 5 seconds.

**Screenshots**
![CLS_issue](https://user-images.githubusercontent.com/10005316/121128364-23134800-c7e0-11eb-94d4-a499fa7c4c24.jpg)

**Comment by connorjclark** [comment]
@devnook This should be filed under DevTools.  https://bugs.chromium.org/p/chromium/issues/list
