### ISSUE TITLE
installability errors and inspector issues need updating

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#13147]
chromium-synchronization tests are failing:

- [`installability-errors-test.js`](https://github.com/GoogleChrome/lighthouse/blob/35d5b214386ea31cdf814095e477e747c118c0bf/third-party/chromium-synchronization/installability-errors-test.js): `pipeline-restarted` missing in [`installable-manifest` `UIStrings`](https://github.com/GoogleChrome/lighthouse/blob/35d5b214386ea31cdf814095e477e747c118c0bf/lighthouse-core/audits/installable-manifest.js#L13)
- [`inspector-issueAdded-types-test.js`](https://github.com/GoogleChrome/lighthouse/blob/master/third-party/chromium-synchronization/inspector-issueAdded-types-test.js): `InspectorIssueDetails` isn't handling a number of new issue types:
   ```
   'attributionReportingIssueDetails',
   'corsIssueDetails',
   'genericIssueDetails',
   'lowTextContrastIssueDetails',
   'navigatorUserAgentIssueDetails',
   'quirksModeIssueDetails',
   'sharedArrayBufferIssueDetails',
   'twaQualityEnforcementDetails',
   'wasmCrossOriginModuleSharingIssue',
   ```
   - see also #11530

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
