### ISSUE TITLE
user-scalable=no on viewport report but tag removed

### ISSUE THREAD

**Issue by mitchellkrogza** [GoogleChrome/lighthouse#13141]
**Describe the bug**
Despite removing user-scalable=no from the viewport and also setting maximum-scale=5.0 web.dev continued to flag this on multiple sites. I have even set maximum-scale=10.0 to no avail.

`[user-scalable="no"]` is used in the `<meta name="viewport">` element or the `[maximum-scale]` attribute is less than 5. 

**To Reproduce**
You can test on my site living canvas dot co dot za

**Expected behavior**
To pass this test 

**Screenshots**

**Comment by connorjclark** [comment]
I'm not able to repro this in web.dev or Chrome devtools. audit is always passing. still an issue? do you recall where the trouble was?

(I realize it's an old issue but it was only just transferred to us).
