### ISSUE TITLE
Exclude full-page-screenshot audit as part of lighthouse run

### ISSUE THREAD

**Issue by raghavikirouchenaradjou** [GoogleChrome/lighthouse#13153]
**Summary**
I am using LH version -  8.4.0 currently and would like to exclude the audit `full-page-screenshot` as part of my LH run since it would increase the result JSON by 33% as per the notable changes [here](https://github.com/GoogleChrome/lighthouse/releases?after=v7.3.0). Since we cannot pass both skipAudits and onlyAudits flag together, I am looking for a way to not include this `full-page-screenshot` audit.
Example: If I run **only** the audit `errors-in-console`, I see two audit results - errors-in-console and full-page-screenshot

Here is my config:

```
const desktopConfig = {
  extends: 'lighthouse:default',
  settings: {
    maxWaitForFcp: 15000,
    maxWaitForLoad: 35000,
    emulatedFormFactor: 'desktop',
    throttling: {
      rttMs: 40,
      throughputKbps: 10240,
      cpuSlowdownMultiplier: 1,
    },
  },
};
```  
I have ` lighthouse: default ` as part of my config and I guess that's the reason this audit gets automatically included, but looking for a way to exclude this audit.

**Comment by connorjclark** [comment]
> cannot pass both skipAudits and onlyAudits flag together

We should ease up on this constraint iff `skipAudits` is just `full-page-screenshot`

**Comment by amdanielson** [comment]
@raghavikirouchenaradjou am I correct that this full page screenshot that you are referencing is the same one that we show on the results page for Website Grader? Or do we generate the full page screen shot that shows there in a different way? Asking because if it is the same, we will have to reconsider the WSG results page design
![Screen Shot 2021-10-01 at 10 33 29 AM](https://user-images.githubusercontent.com/40045887/135637841-71fd971c-b2d4-4d5d-869e-4641021adbfa.png)
s.

**Comment by Mbellsudteen** [comment]
ในวันที่ ศ. 1 ต.ค. 2021 21:34 น. amdanielson ***@***.***>
เขียนว่า:

**Comment by Mbellsudteen** [comment]
ในวันที่ ศ. 1 ต.ค. 2021 04:52 น. raghavikirouchenaradjou <
***@***.***> เขียนว่า:

**Comment by connorjclark** [comment]
Another approach:

remove the explicit "can't use skipAudits and onlyAudits", but in `filterConfigByExplicitFilters` we sumthin like:

```
const auditIdsToKeep = new Set(
    [
      ...baseAuditIds, // Start with our base audits.
      ...(onlyAudits || []), // Additionally include the opt-in audits from `onlyAudits`.
      ...filterResistantAuditIds, // Always include our filter-resistant audits (full-page-screenshot).
    ]
  );

  // apply skipAudits ... but if anything in skipAudits is not in auditIdsToKeep we _error_ ~~~~
```

**Comment by brendankenny** [comment]
previous discussion on this: https://github.com/GoogleChrome/lighthouse/pull/2539#issuecomment-310480924

`onlyCategories` is one thing that makes it complicated. Maybe `full-page-screenshot` should continue to be special cased (or we should admit it's not an audit, though it'll still need some kind of flag for disabling)

**Comment by paulirish** [comment]
Fixed in `main` branch and v10. (as long as you don't use `--legacy-navigation`).

**Comment by connorjclark** [comment]
FYI @raghavikirouchenaradjou  / others - in 10.0 we plan to move this screenshot data from being an audit to being at the top of the LHR structure, which means to exclude it there will be a new setting. ref #14657
