### ISSUE TITLE
CSP audit does not recognize the `navigate-to` directive

### ISSUE THREAD

**Issue by Seirdy** [GoogleChrome/lighthouse#13164]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://seirdy.one

### What happened?

The CSP-XSS audit contains the following result:

``` json
"items": [
      {
        "severity": "Syntax",
        "description": {
          "type": "code",
          "value": "default-src 'none'; img-src 'self' data:; style-src 'sha256-c7tfd/i7WbwPTbxi2MfuSn2JRsea7zAQwNbEPKDAoUk='; style-src-attr 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'; manifest-src 'self'; upgrade-insecure-requests; navigate-to 'none'"
        },
        "subItems": {
          "type": "subitems",
          "items": [
            {
              "directive": "navigate-to",
              "description": "Unknown CSP directive."
            }
          ]
        }
      }
    ]
```

### What did you expect?

I expected the CSP to be valid, as `navigate-to` is a valid CSP directive documented in the spec for [CSP Level 3](https://www.w3.org/TR/CSP3/#directive-navigate-to), written largely by the Chrome team.

### How were you running Lighthouse?

CLI

### Lighthouse Version

8.5.1

### Chrome Version

96.0.4659.0 (Developer Build) (64-bit), revision 927069

### Node Version

v14.17.6

**Comment by Seirdy** [comment]
A few more points:

- Google's CSP Evaluator tool has the same issue
- I temporarily turned off the `sandbox` directive on my website to run this test, but it can be reproduced on any site that sends a CSP with a `navigate-to` directive.

**Comment by Mbellsudteen** [comment]
ในวันที่ ส. 2 ต.ค. 2021 08:55 น. Rohan Kumar ***@***.***>
เขียนว่า:

**Comment by Mbellsudteen** [comment]
ในวันที่ ส. 2 ต.ค. 2021 08:53 น. Rohan Kumar ***@***.***>
เขียนว่า:

**Comment by adamraine** [comment]
Looks like this is an open bug on CSP evaluator https://github.com/google/csp-evaluator/issues/34

**Comment by Seirdy** [comment]
On Mon, Oct 04, 2021 at 12:25:00PM -0700, Adam Raine wrote:
>Looks like this is an open bug on CSP evaluator https://github.com/google/csp-evaluator/issues/34

The bug was just closed; the master branch of CSP-evaluator now understands the "navigate-to" and "webrtc" CSPv3 diectives.

-- 
Seirdy (https://seirdy.one)

**Comment by adamraine** [comment]
Yeah, I'll ping for an npm release
