### ISSUE TITLE
ERRORED_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by yogendra-ss** [GoogleChrome/lighthouse#13167]
Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 500)Dismiss
our website: https://www.inspireglobalsolutions.com/

Please suggest for this issue , how to resolve ?
yogendra2727@gmail.com

**Comment by yogendra-ss** [comment]
necessarily-wide-alpaca

**Comment by yogendra-ss** [comment]
necessarily-wide-alpaca

**Comment by patrickhulce** [comment]
@yogendra-ss this *is* a duplicate of #2784, so we will not be reopening. As described in the cases there, the server for https://www.inspireglobalsolutions.com/ is returning a 500 status code (Internal Server Error) and is an issue with the server code, not Lighthouse.
