### ISSUE TITLE
Improvements to link-blocking-first-paint audit. Handle async styles.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#1317]
At the moment, I can't see of a way to get lighthouse to handle async styles.

If the page waits until the window 'load' event to then add styles to the head of the page, this *shouldn't* block first render, however, this rule still fails following this approach.

Looking at the info on: https://developers.google.com/web/tools/lighthouse/audits/blocking-resources it doesn't really explain how to add async styles WHILE following this rule.

Is there an expected approach / best practice here?

**Comment by ebidel** [comment]
Related https://github.com/GoogleChrome/lighthouse/issues/1249. We need to figure out a way to deal with this case. Right now, all links are checked with the page first loads and we don't know if they switch `rel` or state later on.

**Comment by gauntface** [comment]
I was wondering if we could compare the window load time and the request
start time. If the request start time is after the window load time then we
can assume it was non-blocking, does that sound right?

**Comment by ebidel** [comment]
Yea, that might work well. We could add that extra check in the gatherer. We have [that info](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js#L68).

We also have the FP/FMP time that we could compare against instead of `load`.

**Comment by ebidel** [comment]
From https://github.com/GoogleChrome/lighthouse/issues/1249:

> `link[rel=preload]` triggers LinkBlockingFirstPaintAudit if the rel is changed before the audit is run, even though it isn't render blocking. This is the pattern used by the Filament Group's loadCSS.

> Test page: http://filamentgroup.github.io/loadCSS/test/preload.html

**Comment by gauntface** [comment]
Would be curious how each of those times compare for these scenarios but
you are right that would make more sense than load. I started looking at
the gatherer but wasn't sure where to grab the extra details from.

**Comment by JacobDB** [comment]
Is this implemented in v1.5.2? I can't figure out why it's still saying my stylesheets are render blocking.

**Comment by patrickhulce** [comment]
@JacobDB yes it should be implemented. Are you using the same technique or another method? Currently if your site loads too quickly (and we can't detect your stylesheet was at one point not `rel="stylesheet"`), we will report a false positive.

**Comment by JacobDB** [comment]
<link rel="preload" href="slow.css.php" as="style" onload="this.rel='stylesheet'">

That way, you mean? Yea, that's how I was originally doing it, and it was throwing an error. Tried another method too, switching from `media="none"` to `media="all"` onload, but same issue. I guess maybe my site's just too fast for it.

**Comment by patrickhulce** [comment]
Hmm, do you have a sample URL you're willing to share so we can double check? Should probably also just not warn about scripts or styles that load very quickly anyway.

**Comment by JacobDB** [comment]
Sure, here you go: https://framework.ghostlyco.de/ (note it's still very much work in progress!)

**Comment by patrickhulce** [comment]
Ah @JacobDB are you running with `--disable-network-throttling`? The audit false positives for loading too quickly when I run with that but lacking the flag works as expected. I'll open an issue for not warning if the delay was too short to differentiate. 👍
