### ISSUE TITLE
LCP of lighthouse test doesn't match it's original trace

### ISSUE THREAD

**Issue by benshabatnoam** [GoogleChrome/lighthouse#13172]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

http://www.toolsvilla.in/browser/oswal-mono-block-pump.html

### What happened?

My lighthouse test showing a LCP score of 6.1 s, while viewing the original trace shows a LCP at Timestamp1635.6 ms.

### What did you expect?

I except the lighthouse test report to have the same LCP as the one in the original trace.
Note: when running a performance test with the same params, I'm getting the same timestamp as the original trance.
Looks like the lighthouse report is getting a different LCP element from some reason.

### What have you tried?

I ran the lighthouse several times and viewed his original score.
I also checked the performance tab running manually tests.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.3.0

### Chrome Version

Version 94.0.4606.61 (Official Build) (64-bit)

**Comment by adamraine** [comment]
This is expected behavior, by default Lighthouse uses simulated throttling which interpolates the metric values *after* the trace is collected. You can check out our [docs on throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md) for more information.

If you need the trace to match the Lighthouse metrics, you can disable simulated throttling in the Lighthouse settings.

**Comment by benshabatnoam** [comment]
Hi @adamraine, I guess you didn't understand my bug description, I'll try to rephrase myself.

The problem (bug) is that the LCP object is deferent in this 2 tests. 
It can be easily seen in the lighthouse test, the FCP and LCP have different timestamps, but they are actually the same object.

I'll appreciate if you could take a second look at this, as I'm pretty sure that this is a bug and it's not the throttling.
Thanks

**Comment by benshabatnoam** [comment]
Hi @patrickhulce, I'm sorry but I don't think you guys understand what I'm trying to say.
Forget about the 'original trace', I'm talking only regarding the lighthouse report.
In the lighthouse report, I'm getting FCP timestamp of 1.6, and a LCP of 6.8. These
