### ISSUE TITLE
statistics for 28 days on FID and LCP

### ISSUE THREAD

**Issue by Lodomesk** [GoogleChrome/lighthouse#13177]
**Summary**

Google does not show statistics for 28 days on FID and LCP, however, FCP and CLS are issued. I assume that CMS or VDS is blocking something. But I didn't make any changes in the settings. The problem is only with the main page of the site. The rest of the pages are fine. Tell me what could be the problem?

![forum](https://user-images.githubusercontent.com/92013115/136152079-7633cc1d-c490-4397-9c88-90da4abf558d.JPG)

**Comment by adamraine** [comment]
What URL are you testing?
