### ISSUE TITLE
aria id are not unique

### ISSUE THREAD

**Issue by nasx21** [GoogleChrome/lighthouse#13189]
I have an issue on the lighthouse that said my website’s aria id is not unique. The failing element is on the website’s menu. So, all pages have the same issues because the menu is displayed on every page. Does anyone know how to fix these issues and where can I find the code to fix them? The website is based on WordPress.

![image](https://user-images.githubusercontent.com/89466775/136402295-e94d8d68-c751-4c11-8048-afae7dea027e.png)

**Comment by patrickhulce** [comment]
Run `document.querySelectorAll('#primary-menu')` in the Developer Console to list all the elements with that ID. You can then click each of them to open the duplicates in the Elements panel to find them.
