### ISSUE TITLE
drop `image-size-responsive` elidedUrl

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#13182]
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/image-size-responsive.js#L149

This is the only audit that saves a separate "elidedUrl" property. All other audits save the result of `URL.elideDataURI` to their `url` property. We should just set `url` to this elided value, and drop `elidedUrl`. Otherwise, data uir images failing this audit will make the LHR larger than intended.

**Comment by Derbdale** [comment]
@connorjclark What are your thoughts on the implications of this on the thumbnail render? Is it reasonable to not render the thumbnail if a data-URL is used - Should a placeholder of some-kind exist for this?

Or does it make more sense to ditch the elided-URL for this and just use the full URL as it's required for the thumbnail?

**Comment by prerana1821** [comment]
Hey @meehawk, yes I'm working on it. Will submit it by tomorrow.

**Comment by prerana1821** [comment]
@connorjclark, please review my PR. #13226

**Comment by paulirish** [comment]
fixed by #13226
