### ISSUE TITLE
Remove usage of `eval` in hreflang.js

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#13205]
see: https://docs.google.com/document/d/10gp-4xzsQuJpdfMdYHPZbf6EYq3lBnu1Adc11bcMQE8/edit#

CDT wants to tighten their CSP, and this came up as an issue. We could revert what https://github.com/GoogleChrome/lighthouse/pull/11442 did–alternatively we could add the list of locales to the Accessibility artifact.

**Comment by brendankenny** [comment]
we're dropping support for Node 12 (and we decided to move past Node 12.17 since last December anyways), so dynamic `import` for hreflang (and reverting back to the old `fs.readFileSync` in the accessibility gatherer) is easily doable for LH9
