### ISSUE TITLE
new_audit: manifest-id

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#13201]
chrome 96 introduces new manifest property: id, for the purposes of persistence when updating a PWA's start url. If no id present, fallback is `start_url`. We want a PWA audit that requires an explicit `id` to be set.

```
Text: “Specifies an id in manifest”
Text when id is not specified: “id is not specified in manifest”
Expanded explanation: "This id is used to generate App Id by the browser to know whether the manifest should be updating an existing application, or a new web app that can be installed. When id is not specified, start_url is used as the App Id. Learn more <link to devrel article>"
```

see:
- https://bugs.chromium.org/p/chromium/issues/detail?id=1222571
- https://developer.chrome.com/blog/pwa-manifest-id/
- https://docs.google.com/document/d/16kWW_MBrdtKOMud41vobrOXUPqIL5tITWGiBk9UIDEs/edit?pli=1&resourcekey=0-I3w9uAOGPk96Uqkn00ZVtw#heading=h.akzf7ifvhmic

CDT ended up just using https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-getAppId and checking for manifest.id directly: https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/panels/application/AppManifestView.ts;l=584?q=AppManifestView.ts&ss=chromium

**Comment by connorjclark** [comment]
We're considering not including this as an audit. Maybe just a mention/link in our [docs](https://developer.chrome.com/docs/lighthouse/pwa/)?

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
