### ISSUE TITLE
Hosted Lighthouse: report testing server location

### ISSUE THREAD

**Issue by sgomes** [GoogleChrome/lighthouse#13209]
**Feature request summary**
For hosted instances of Lighthouse, such as `web.dev/measure` or PageSpeed Insights, it would be extremely useful for the testing server's geographical location to be included in the report.

**What is the motivation or use case for changing this?**
When evaluating site performance, it's extremely important to know where the testing is taking place, in order to account for variables such as network latency, which Lighthouse can't correct for. Different runs may get very different results depending on server location, and surfacing that information in the report would allow for a greater understanding of the conditions that led to a specific score.

**How is this beneficial to Lighthouse?**
It would provide much-needed context to the results, ultimately making them more useful. As it stands, there is a lot of variability between hosted tools (and even different runs on the same tool) that's impossible to account for, which makes it hard to recommend hosted Lighthouse instances as reliable tools.

Note: I was pointed to this repo for this feature request, but I apologise in advance if this is the wrong place for it! Please feel free to close and ignore if that's the case.

**Comment by monu212** [comment]
BCS ganrice incoming

**Comment by connorjclark** [comment]
We added this in the new pagespeed site https://pagespeed.web.dev/

![image](https://user-images.githubusercontent.com/4071474/142073497-a6ea737f-7636-47a6-81d7-d656fd9c056c.png)
