### ISSUE TITLE
Hasil audit pada performance berbeda

### ISSUE THREAD

**Issue by Irtho535** [GoogleChrome/lighthouse#13200]
Hallo, apakah permasalah saya ini bisa di bantu.?

Saya telah menguji 2 situs dengan format https://www.example.com  dalam waktu yang sama, dan permasalahan terbesar dari ke dua situs ini.

> Situs 1 : Elemen gambar tidak memiliki eksplisit.

> Situs 2 : Elemen gambar tidak memiliki eksplisit, dan ukuran dom berlebihan.

Tetapi hasil yang menakjubkan situs 1 memiliki skor performance 99% dan situs 2 memiliki skor performance 100%.

Apakah hasil ini sudah sesuai.?

Saya memiliki hasil tangkapan layar

Tangkapan Layar untuk situs 1
![IMG_20211012_040146](https://user-images.githubusercontent.com/92332546/136844018-69b40bc3-3546-4ec8-95b5-d4b133b5e1bf.jpg)

Tangkapan Layar untuk situs 2
![IMG_20211012_040132](https://user-images.githubusercontent.com/92332546/136844043-db2790b7-ef6a-4279-96cf-0712a7f1c3ef.jpg)

Jika ingin melihat lebih jauh

Saya menyediakan tautan di bawah ini
[Hasil Laporan Situs 1](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.inc-papua.xyz) 

[Hasil Laporan Situs 2](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.saifullah.id)

Terima kasih
Tolong berikan saya tanggapan.

**Comment by paulirish** [comment]
it says in the UI:

> Saran tersebut tidak [secara langsung memengaruhi](https://github.com/GoogleChrome/lighthouse/blob/d2ec9ffbb21de9ad1a0f86ed24575eda32c796f0/docs/scoring.md#how-are-the-scores-weighted) skor Performa.

the Performance score is only determined from the 6 metrics. not the Diagnotik results.

:)
