### ISSUE TITLE
Lighthouse in chrome freezing (CLI throwing errors)

### ISSUE THREAD

**Issue by webdevinci** [GoogleChrome/lighthouse#13223]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://thedirect.com/article/black-panther-wakanda-tribe-actress-dorothy-steel

### What happened?

My company provides ad services to websites. Core web vitals has been a hot topic this past year. With lighthouse having aggressive release cycles, I'm curious if the most recent one has a breaking change.

Full transparency, when removing our ad script (<script id="ramp" data-delay="3000" src="//cdn.intergient.com/ramp.js" async></script>), lighthouse does work just fine. There is probably something in there that lighthouse doesn't like.

**Note**: With our ad script active, I have tried this in incognito with no extensions running and with empty application caches/cookies/indexDB, etc. SOMETIMES removing the app cache each time before running lighthouse makes it not freeze, but rarely.

When running lighthouse on the majority of our pages, Lighthouse won't run while on the page. It just gets stuck.

I have several publishers asking why this is happening recently (past month or so).
See below screen capture.
**Screen capture** https://share.getcloudapp.com/nOu5pgrY

Is there anything that our ad scripts could be adding/executing that would  prevent lighthouse from running in the newest version of lighthouse?

### What did you expect?

When I click "Generate Report", lighthouse should begin its report immediately. Rather we have to refresh the page, and during the refresh, quickly click the "Generate Report" button.

### What have you tried?

I have noticed pages (specifically ones with <meta name="twitter:..."> & <meta name="og:..."> tags) bring down lighthouse scores to a creep. I also have to refresh, and click the "Generate Report" button immediately after refreshing to get lighthouse to even work. When removing those meta tags, the score increase is insanely higher.

Dumping all application cache (indexdb/cookies/storage) will sometimes, but rarely yield lighthouse to generate the report without freezing. 

Removing our ad script <script id="ramp" data-delay="3000" src="//cdn.intergient.com/ramp.js" async></script> allows lighthouse to run properly. Our ad script does a lot: Runs Prebid & Amazon TAM headerbidding, and sends requests to GAM/SpotX and takes ad responses to put display & video ads on a page. 

**NOTE** this hasn't been an issue until one of the more recent lighthouse updates. Wondering what may have changed that could be causing this

![image](https://user-images.githubusercontent.com/4904056/137602308-4283bf36-ecae-4a67-a16c-7db553bc4ee2.png)

### How were you running Lighthouse?

CLI, Chrome DevTools

### Lighthouse Version

6.0

### Chrome Version

94.0.4606.81

### Node Version

14.17.0

### Relevant log output

```shell
Bottom is the most important (errors). Image is in above attachment

LH:status Auditing: `<object>` elements have `[alt]` text +5ms
  LH:status Auditing: No element has a `[tabindex]` value greater than 0 +4ms
  LH:status Auditing: Cells in a `<table>` element that use the `[headers]` attribute refer to table cells within the same table. +4ms
  LH:status Auditing: `<th>` elements and elements with `[role="columnheader"/"rowheader"]` have data cells they describe. +5ms
  LH:status Auditing: `[lang]` attributes have a valid value +5ms
  LH:status Auditing: `<video>` elements contain a `<track>` element with `[kind="captions"]` +3ms
  LH:status Auditing: Custom controls have associated labels +4ms
  LH:status Auditing: Custom controls have ARIA roles +0ms
  LH:status Auditing: User focus is not accidentally trapped in a region +0ms
  LH:status Auditing: Interactive controls are keyboard focusable +0ms
  LH:status Auditing: Interactive elements indicate their purpose and state +0ms
  LH:status Auditing: The page has a logical tab order +0ms
  LH:status Auditing: The user's focus is directed to new content added to the page +0ms
  LH:status Auditing: Offscreen content is hidden from assistive technology +0ms
  LH:status Auditing: HTML5 landmark elements are used to improve navigation +0ms
  LH:status Auditing: Visual order on the page follows DOM order +0ms
  LH:status Auditing: Uses efficient cache policy on static assets +1ms
  LH:status Auditing: Avoids enormous network payloads +17ms
  LH:status Auditing: Defer offscreen images +5ms
  LH:status Auditing: Eliminate render-blocking resources +350ms
  LH:status Auditing: Minify CSS +16ms
  LH:status Auditing: Minify JavaScript +452ms
  LH:status Auditing: Reduce unused CSS +510ms
  LH:status Auditing: Reduce unused JavaScript +368ms
  LH:status Auditing: Serve images in next-gen formats +475ms
  LH:status Auditing: Efficiently encode images +377ms
  LH:status Auditing: Enable text compression +417ms
  LH:status Auditing: Properly size images +373ms
  LH:status Auditing: Use video formats for animated content +370ms
  LH:status Auditing: Remove duplicate modules in JavaScript bundles +371ms
  LH:status Auditing: Avoid serving legacy JavaScript to modern browsers +430ms
  LH:status Auditing: Avoids Application Cache +523ms
  LH:status Auditing: Page has the HTML doctype +1ms
  LH:status Auditing: Properly defines charset +2ms
  LH:status Auditing: Avoids an excessive DOM size +2ms
  LH:status Auditing: Links to cross-origin destinations are safe +2ms
  LH:status Auditing: Avoids requesting the geolocation permission on page load +2ms
  LH:status Auditing: No issues in the `Issues` panel in Chrome Devtools +4ms
  LH:status Auditing: Avoids `document.write()` +2ms
  LH:status Auditing: Avoids front-end JavaScript libraries with known security vulnerabilities +2ms
  LH:status Auditing: Detected JavaScript libraries +12ms
  LH:status Auditing: Avoids requesting the notification permission on page load +1ms
  LH:status Auditing: Allows users to paste into password fields +2ms
  LH:status Auditing: Use HTTP/2 +1ms
  LH:status Auditing: Uses passive listeners to improve scrolling performance +375ms
  LH:status Auditing: Document has a meta description +3ms
  LH:status Auditing: Page has successful HTTP status code +1ms
  LH:status Auditing: Document uses legible font sizes +1ms
  LH:status Auditing: Links have descriptive text +4ms
  LH:status Auditing: Links are crawlable +3ms
  LH:status Auditing: Page isn’t blocked from indexing +2ms
  LH:status Auditing: robots.txt is valid +1ms
  LH:status Auditing: Tap targets are sized appropriately +2ms
  LH:status Auditing: Document has a valid `hreflang` +2ms
  LH:status Auditing: Document avoids plugins +3ms
  LH:status Auditing: Document has a valid `rel=canonical` +1ms
  LH:status Auditing: Structured data is valid +1ms
  LH:status Generating results... +1ms
  LH:Printer html output written to /Users/twilliams/Sites/tyche/thedirect.com_2021-10-16_17-08-54.report.html +109ms
  LH:CLI Protip: Run lighthouse with `--view` to immediately open the HTML report in your browser +1ms
  LH:ChromeLauncher Killing Chrome instance 12427 +0ms
  LH:Driver:error Unhandled event error PROTOCOL_TIMEOUT +18s
  LH:Driver:error Unhandled event error PROTOCOL_TIMEOUT +0ms
  LH:Driver:error Unhandled event error PROTOCOL_TIMEOUT +1ms
```

**Comment by webdevinci** [comment]
@devtools-bot (you're a bot... but): Any priority spoken of?
One added note, FWIW, this is happening more-so on the apple m1 chip than intel

**Comment by connorjclark** [comment]
> Lighthouse Version: 6.0

Are you sure? 6.0 is pretty old.

**Comment by webdevinci** [comment]
Correction: Browser is 8.4.0
and FWIW, CLI is 8.5.1

**Comment by connorjclark** [comment]
Can you repro it with 9.0?

**Comment by webdevinci** [comment]
@connorjclark From what I see, you guys made a major fix! looking great across the board without the 'refresh hack'. Thanks so much!

**Comment by connorjclark** [comment]
Shrug! let us know if it comes up again. thx
