### ISSUE TITLE
Failed in report - net::ERR_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by JuanCruzTrinidad** [GoogleChrome/lighthouse#13221]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.lanacion.com.ar/tema/coronavirus-en-la-argentina-tid67682/

### What happened?

We are working through lhci cli, with tasks in azure devops, with different agents in parallel, a batch of five urls, three runs per url. 3/5 Url does not present any type of problem when displaying the result, but two of them do, the next error appears. I did not find more information about it in a similar issue.

![image](https://user-images.githubusercontent.com/53027244/137552540-b96054c0-0c0f-4ed2-bee2-da75d90bfc12.png)

The executions are carried out through lhci cli, in an agent that uses ubuntu.

### What did you expect?

I hope I can find a solution so that all the information in my tests is reliable.

### What have you tried?

We do local tests, running from the chrome lighthouse.
We performed local tests, with the lhci cli command and the result was as expected.

### How were you running Lighthouse?

CLI, node

### Lighthouse Version

8.0

### Chrome Version

92.0.4515.107-1_amd64

### Node Version

14.x

**Comment by connorjclark** [comment]
Could you share the LHR (the json)? Should be able to copy it from the top-right menu.

Also, if you go to the error'd category and hover over "Error" you can see the error message. It's not great UI :/
