### ISSUE TITLE
Lighthouse test feature in Chrome just stopped working 

### ISSUE THREAD

**Issue by radekandrzejewicz** [GoogleChrome/lighthouse#13237]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://m.warsztat24.pl

### What happened?

I cannot perform lighthouse test on https://m.warsztat24.pl for a few days now... there wasn't any problems before... but now... test runs and runs and runs (messages on popup do change all over the time) and just cannot finish and go to the summary.... 
what can be the reason? please help! 

### What did you expect?

I would like just to get lighthouse test results for https://m.warsztat24.pl.

### What have you tried?

don't know what could I do, as the tests seem continue over and over...

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

don't know because I cannot see any finished report

### Chrome Version

94.0.4606.81

### Node Version

12.16.1

**Comment by mikkopori** [comment]
Hello,

upgrading to 95.0.4638.54 with Lighthouse 84 caused the same issue, hanging forever. Also cancelling after that fails.

OS: Ubuntu 21.04

Will save this answer and try with beta google-chrome-beta amd64 96.0.4664.18-1

**Comment by jamestoalbv** [comment]
- Website: https://portal.bazaarvoice.com/signin
- Chrome Version: Version 95.0.4638.69 (Official Build) (x
- Cleared cache, reinstalled chrome, also tried in incognito mode.
![Screenshot 2021-11-02 at 10 20 42](https://user-images.githubusercontent.com/77396071/139828863-9272acf6-2182-4a5b-9f86-e503be455c38.png)
86_64)

**Comment by barbalex** [comment]
Same here. I can test any site, it always gets stuck at about 95%. Incognito mode or not. Version 95.0.4638.69 (Offizieller Build) (64-Bit). On Windows 11

**Comment by connorjclark** [comment]
original reported url no longer hangs, but instead has an error in installability audit. Tracking #13396
