### ISSUE TITLE
Not able to generate the lighthouse audit report

### ISSUE THREAD

**Issue by rgv9999** [GoogleChrome/lighthouse#13236]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://wheresthebus.com/

### What happened?

I am trying to generate the report but browser keeps on showing that 'Auditing https://wheresthebus.com/', but it is never ending.

### What did you expect?

It should generate report for both desktop & mobile versions.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

Lighthouse 8.4.0

### Chrome Version

Version 95.0.4638.54 (Official Build) (64-bit)

**Comment by ju1ius** [comment]
FWIW, I just had the same issue today, `Chrome 95.0.4638.54 (official build) (64bits) / Linux`.

I'm currently working on a website. Yesterday, audits worked fine. Today I started implementing a service worker, and audits got stuck (showing the same messages posted by @userquin).

I deregistered the SW in devtools, deleted IndexDB & caches, removed SW registration script, then ran an audit in incognito mode, and it started working again.

Definitely seems related to service worker registration.

**Comment by connorjclark** [comment]
Please provide URLs / details on if the problem persists in Canary too. Thanks!

**Comment by notshriram** [comment]
Same issue here, 
Running `MacOS Monterey 12.0.1` and `Chrome Version 95.0.4638.69 (Official Build) (arm64)`

**Comment by 13VF** [comment]
Same for me, MacOs 12.0.1 (21A559), Chrome 95.0.4638.69 and same in Canary Build 97.0.4689.0.

**Comment by userquin** [comment]
On windows also failing Chrome Canary: 

![imagen](https://user-images.githubusercontent.com/6311119/139852188-94d54a68-390b-4caf-a6a5-13d40363c297.png)

![imagen](https://user-images.githubusercontent.com/6311119/139852473-282d939c-e811-4eb2-a009-d65264fdbae9.png)

![imagen](https://user-images.githubusercontent.com/6311119/139852120-eab61c29-c75d-4ba7-b156-8713ef4b8de1.png)


If you want to play with a pwa just go to this repo https://github.com/antfu/vite-plugin-pwa, you will need to have `pnpm` installed globally and `node 14+`, then `pnpm run build` from root folder, then `pnpm run docs:serve` from root folder (will ask for install a localhost certificate that will be generated for you) and open `https://localhost` in browser.

The pwa source code is inside https://github.com/antfu/vite-plugin-pwa/tree/main/docs package/directory, we use `Workbox` to register the service worker, the code can be found here: https://github.com/antfu/vite-plugin-pwa/blob/main/src/client/build/register.ts#L48, `'__SW__'` and `'__SCOPE__'` will be replaced at build time with the `base` and `scope` on pwa plugin configuration on `vite.config.ts` file here: https://github.com/antfu/vite-plugin-pwa/blob/main/docs/vite.config.ts#L63.

By default `'__SW__'` and `'__SCOPE__'` values are `sw.js` and `/` respectivelly.

You can see also the plugin docs deployed on netlify here: https://vite-plugin-pwa.netlify.app/ (on Chrome canary not showing the error, but never finish).

In fact, also failing when the app registers a service worker and unchecking the PWA on Lighthouse.

Lighthouse was working, and now no pwa can be tested, I have more examples, this one also fails with the same error about registering the service worker: https://grid.layoutit.com/ (3 screenshot above). 

![imagen](https://user-images.githubusercontent.com/6311119/139850535-23a3f72e-d29e-40ac-b460-604375d78402.png)

**Comment by ghisleouf** [comment]
Hi there !
Same issue for me :
Mac OS 12.0.1 - Version 95.0.4638.69 (Build officiel) (x86_64)

**Comment by JoelIF** [comment]
If you uncheck the clear cache option in lighthouse options it starts working.

**Comment by userquin** [comment]
> 
> 
> If you uncheck the clear cache option in lighthouse options it starts working.

![imagen](https://user-images.githubusercontent.com/6311119/140181652-fbea1ea4-5aa2-4d82-a595-63b954c716f0.png)

**Comment by userquin** [comment]
@JoelIF thank you very much

**Comment by userquin** [comment]
But it is using the sw, it is not requesting assets from server , so the scores will be always 100

**Comment by emjose** [comment]
> If you uncheck the clear cache option in lighthouse options it starts working.

Same issue here. Version 95.0.4638.69 (Official Build) (x86_64).
Audit still doesn't generate even when "clear storage" is unchecked.

**Comment by Indrico** [comment]
> If you uncheck the clear cache option in lighthouse options it starts working.

Worked for me.
Many thanks.

**Comment by datapolitical** [comment]
That’s helpful, but it also yields different results

**Comment by iamnotapenguin** [comment]
Same issue. 95.0.4638.69. Unchecking "clear storage" did not fix the issue.

**Comment by userquin** [comment]
It seems on Windows fixed, Chrome Versión 96.0.4664.45 (Build oficial) (64 bits)

For example, on mobile:
![imagen](https://user-images.githubusercontent.com/6311119/142245279-5053a5fe-cbb9-4e35-b7b5-4940de5ade2d.png)

**Comment by andreassoegaard** [comment]
Same issue here. Version 96.0.4664.45 (Official Build) (arm64).

**Comment by connorjclark** [comment]
Tracking in #13396, please follow there.

**Comment by egbakou** [comment]
Issue fixed in the current version (97.0.4692.71)

![image](https://user-images.githubusercontent.com/26142591/148185213-0d7559af-03ef-4151-b556-8d08e1198319.png)

Thanks :)
