### ISSUE TITLE
Lighthouse is not working in Chrome

### ISSUE THREAD

**Issue by Dtrav** [GoogleChrome/lighthouse#13257]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.oklahomadriver.com/

### What happened?

Lighthouse gets stuck before finishing and won't complete.

### What did you expect?

Lighthouse to finish gathering scores but instead, it gets stuck.

### What have you tried?

I have tried running Lighthouse on both my Mac and PC and in both regular and incognito windows.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

Can't see the version because it won't finish.

### Chrome Version

Version 95.0.4638.54 (Official Build) (64-bit)

### OS

Multiple on both Mac and Windows.

**Comment by connorjclark** [comment]
no longer hangs in Canary, but instead has an error in installability audit. Tracking #13396

**Comment by TheLeonardTree** [comment]
I have the same issue, it freezes about 90% through
![image](https://user-images.githubusercontent.com/25886530/146479284-349b2131-1d08-4689-975a-aa4303ee88e1.png)
