### ISSUE TITLE
Confusion over FCP and Server Response Time Definition

### ISSUE THREAD

**Issue by aminjabari** [GoogleChrome/lighthouse#13255]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://ux.aminjabari.com/

### What happened?

As I stated in [this question ](https://support.google.com/webmasters/thread/132170135/are-fcp-and-server-response-time-related?hl=en)in the support forum, I think there is confusion in how a FCP and Server Response Time is calculated.

I get 0.4 sec for FCP and 0.6 for LCP in the Pagespeed Insights, but in the recommendations section, it shows an error that my server response time is about 1.6 sec and needs improvement.
I think the server response time is equivalent to TTFB (Time to First Byte). 
But I can't understand how a browser can start loading a page (Showing FCP and LCP indicate that the page loading has been started) before server response? 

Server ResponseTime: 1.6 sec
FCP: 0.4 sec
LCP: 0.6 sec

[According to Web.dev definition about FCP](https://web.dev/fcp/): 

> the First Contentful Paint (FCP) metric measures the time from when the page starts loading to when any part of the page's content is rendered on the screen. 

The question is: Which moment do you define as page loading start? The time a user writes a URL and hits enter or the time the first byte from the server has been received?
Does Server Response Time overlap with FCP and LCP or they are separate?

### What did you expect?

I expect the FCP around 2 sec (according to 1.6 sec server response time).

### What have you tried?

I have seen this issue numerous times and it's not a one-time issue. 

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

8

### Chrome Version

95.0.46...

**Comment by brendankenny** [comment]
> But I can't understand how a browser can start loading a page (Showing FCP and LCP indicate that the page loading has been started) before server response?

You're right that this is incorrect and shouldn't happen. I'm not able to reproduce with your URL but I have found that this does happen and needs to be fixed.

I missed this issue and started commenting in #13296, so we can track over in that bug.
