### ISSUE TITLE
possibly recalibrate throttling multipliers based on benchmark index

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#13259]
First step: @exterkamp / @paulirish to jot down all our thoughts on BI (correlation study b/wn BI and score in LR @adrianaixba; thoughts on disabling low BI warning if we recalibrate throttling)

ref #9085

https://github.com/GoogleChrome/lighthouse/blob/ccbc8002fd058770d14e372a8301cc4f7d256414/docs/throttling.md#calibrating-multipliers

https://github.com/GoogleChrome/lighthouse/blob/25465d99af7439b033385fa17b9984873bf69b02/lighthouse-core/gather/driver/environment.js#L26

**Comment by connorjclark** [comment]
We don't care about this any more. IIRC BI is not a reliable enough signal to use as a stand-in for cpu speed

**Comment by shyamvs1001** [comment]
@connorjclark I am the Product Manager for SpeedLab, a web performance testing tool(on real devices) from BrowserStack. We are about to use Lighthouse Benchmark index for benchmarking the devices and displaying it to users for each device. The decision was based on Lighthouse literature around it.

Could you please give some context on your comment that BI is not reliable signal for cpu speed? 
I tried to find other way to contact you, but couldn't get your email id.

**Comment by connorjclark** [comment]
I don't have anything to add other than what Patrick already spoke about in https://github.com/GoogleChrome/lighthouse/issues/9085

**Comment by paulirish** [comment]
need to drop this link for posterity, as its vaguely related: https://github.com/catchpoint/WebPageTest.agent/pull/644
