### ISSUE TITLE
Lighthouse is not sending Client Hints

### ISSUE THREAD

**Issue by maciejmrozinski** [GoogleChrome/lighthouse#13267]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.google.com

### What happened?

Using Lighthouse locally to test caching strategies based on `sec-ch-ua-mobile` header I've found that Client Hints headers are not sent at all.

### What did you expect?

Lighthouse should send headers from the start as usual browser session (sec-ch-ua, sec-ch-ua-mobile).

### What have you tried?

Debugging Lighthouse locally, confirming that headers are not send and that code shown below and used right now:
```
    await session.sendCommand('Network.setUserAgentOverride', {
      userAgent: /** @type {string} */ (settings.emulatedUserAgent),
    });
```
prevents normal browser behavior (sending Client Hints headers), because there isn't `userAgentMetadata` object provided. I want to mention that I took some time to create branch with necessary changes and I'll more than happy to share my thoughts with you guys.

### How were you running Lighthouse?

CLI

### Lighthouse Version

8.6.0

### Chrome Version

94.0.4606.81

### Node Version

14.16.0

### OS

Linux

**Comment by connorjclark** [comment]
fixed by #13341
