### ISSUE TITLE
Add npm package-lock to lock dependencies (like yarn.lock)

### ISSUE THREAD

**Issue by wardpeet** [GoogleChrome/lighthouse#1327]
Debug library made a breaking change when they did a minor upgrade.
We should add [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) so dependencies & devdependencies are locked so we have full control over our dependencies.

We might look for services like [greenkeeperio](https://github.com/greenkeeperio/greenkeeper) to keep us notified on breaking packages.

**Comment by patrickhulce** [comment]
Is this targeting people installing with `npm install -g lighthouse` or are there spots we don't use yarn yet?

**Comment by wardpeet** [comment]
it's for lighthouse installed through -g or through githug (git clone).

It's for everyone that doesn't use yarn :p

**Comment by brendankenny** [comment]
as an easy first step we can lock our `package.json` dependency versions.

Beyond that, it would be cool to look into tools that sync a yarn.lock file and a shrinkwrap file (preferably using the yarn.lock file as the source of truth since yarn's dependency tree install is deterministic)

**Comment by samccone** [comment]
@kittens any thoughts on autogenerating a shrinkwrap from a yarn.lock (and yes shrinkwrap.json is lossy that is somewhat known)

**Comment by wardpeet** [comment]
It should be enough to run yarn upgrade and do npm shrinkwrap afterwards because shrinkwrap doesn't download any new packages, it just looks in node_modules. Not sure if yarn has some kind of hook to wait for lock file to be created.

ex:
`yarn upgrade; npm shrinkwrap`

**Comment by brendankenny** [comment]
not sure if we want to hold off until all npm5 issues have been sorted or if yarn.lock is sufficient
