### ISSUE TITLE
Process devtools raw data (*.devtools.trace) in lighthouse

### ISSUE THREAD

**Issue by usama6naseer** [GoogleChrome/lighthouse#13300]
I have tons of devtools data and I wanted to run lighthouse "main-thread-tasks" audit on it. Is it possible to directly feed the *.devtools.trace to lighthouse? I wasn't able to get much from the description about "trace processor" in the README. Thanks.  

(apologies if this isn't the right avenue for this question, but I didn't see much activity in the google groups.)

**Comment by connorjclark** [comment]
we have a gist example tucked away for this: https://github.com/GoogleChrome/lighthouse/blob/master/docs/hacking-tips.md#using-audit-classes-directly-providing-your-own-artifacts

we have a main-thread-tasks computed artifact, so you're use case will look like https://gist.github.com/connorjclark/d4555ad90ae5b5ecf793ad2d46ca52db#file-direct-audit-js-L71 where artifacts is just an object with the traces data.

Hope that helps!
