### ISSUE TITLE
DevTools Lighthouse audit not working with Gatsby PWAs

### ISSUE THREAD

**Issue by ansmlc** [GoogleChrome/lighthouse#13313]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://naughty-yonath-344d6c.netlify.app/

### What happened?

Lighthouse audit not working. Infinite loading without ever delivering results. Issue occurs when testing Gatsby PWA-enabled sites. Specifically, the plugin in question that triggers this is the official "gatsby-plugin-offline".  Using Incognito makes no difference.

Rarely, it will finish and show " ? " instead of score, and very rarely it will succeed and show correct scores, but still either it takes very long (up to 10 minutes) to finish the audit or it happens rapidly within a few seconds. Overall erratic behavior.

### What did you expect?

Lighthouse to finish loading and show performance scores

### What have you tried?
Testing on a different computer (MacOS with same Chrome version) produced same results. 
See more: gatsbyjs/gatsby#33837

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.4.0

### Chrome Version

95.0.4638.69

### Node Version

14.15.4

### OS

Windows

### Relevant log output

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.40)
  npmPackages:
    gatsby: ^4.1.0 => 4.1.0 
    gatsby-plugin-manifest: ^4.1.0 => 4.1.0 
    gatsby-plugin-offline: ^5.1.0 => 5.1.0 
  npmGlobalPackages:
    gatsby-cli: 3.8.0
```

**Comment by adamraine** [comment]
Looks like the same issue as https://github.com/GoogleChrome/lighthouse/issues/13273

**Comment by connorjclark** [comment]
Tracking this in #13396, please follow there.
