### ISSUE TITLE
Lighthouse passes inconsistent User Agent on Redirect

### ISSUE THREAD

**Issue by broguinn** [GoogleChrome/lighthouse#13314]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.etsy.com/listing/1041475753

### What happened?

Lighthouse passes a different UA than chrome dev tools, causing subtle odd bugs with device detection.

Lighthouse: `Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4590.2 Mobile Safari/537.36 Chrome-Lighthouse`

Chrome: `Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Mobile Safari/537.36`

### What did you expect?

We see the same user agent exactly for easier debugging.

### What have you tried?

I checked the Etsy server logs to validate that the user agents differ.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.4.0

### Chrome Version

95

### OS

Mac

**Comment by broguinn** [comment]
I'm closing this issue as a mis-diagnosis. I see the same problem with redirects lacking a spoofed UA on Chrome, but not in lighthouse, which seems to report the correct UA. It's a problem on our end, where our third party device detection service (Device Atlas) reports this UA `Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4590.2 Mobile Safari/537.36 Chrome-Lighthouse` as a mobile device, but not a mobile phone.

**Comment by broguinn** [comment]
Re-opening as an issue with mismatched user agents.

**Comment by ashishmondal30** [comment]
No idea, but I have another issue. Check- [Best Tech Club](https://besttechclub.com/)

**Comment by paulirish** [comment]
> I'm closing this issue as a mis-diagnosis. I see the same problem with redirects lacking a spoofed UA on Chrome, but not in lighthouse, which seems to report the correct UA. It's a problem on our end, where our third party device detection service (Device Atlas) reports this UA `Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4590.2 Mobile Safari/537.36 Chrome-Lighthouse` as a mobile device, but not a mobile phone.

the only differences i'm seeing are..

1. the android version
2. the chrome version
3. the ' chrome-lighthouse' suffix on the end.

i doubt its the first two... so.. i'm guessing it's the suffix?  don't know what we can do about that. other folks want us to have this to clearly identify bot traffic. seems like it's deviceatlas's bug (or how you're using it?)

**Comment by xxkayxxmoo** [comment]
hallo

**Comment by xxkayxxmoo** [comment]
not supcrieps to jou men sorry i new

**Comment by xxkayxxmoo** [comment]
<script src="/reactapp/static/js/runtime-main.6fa387b4.js"></script>

**Comment by xxkayxxmoo** [comment]
i live in halland

**Comment by broguinn** [comment]
@paulirish That's a fair estimation of what's going on - DeviceAtlas' return value for any Moto G4 user agent I've tested seems to be a mobile device, but not a mobile phone. And accordingly, we're having to change our internal device identification logic to check either field.

To be clear, I don't think the issue of slight variations between Chrome device emulation's Moto G4 user agent and the one sent by Lighthouse are an issue for our use case. For pure debugging purposes, I was surprised that they weren't identical. If it's relatively simple to sync the android and chrome versions here, that would be a satisfying level of internal consistency.

Thanks a bunch!

**Comment by xxkayxxmoo** [comment]
no problem

**Comment by jamesarosen** [comment]
I'm not sure this is related, but I'm seeing something similar in the mainline release of Chrome:

When using the Device Emulator tab, Chrome sends an emulated (mobile) UA for the first request:
![everlane com](https://user-images.githubusercontent.com/2406/141869353-45478acc-64d9-4fbd-b664-c4e456f1b3d4.png)

Then it sends a non-emulated UA for the redirect request:
![www everlane com](https://user-images.githubusercontent.com/2406/141869385-52f6a825-1f47-487f-a427-020b3fbadff2.png)

I just thought I'd mention it in case it helps someone identify the root cause.
