### ISSUE TITLE
Lighthouse in devtools gets stuck on https://periodex.co/

### ISSUE THREAD

**Issue by carlosjeurissen** [GoogleChrome/lighthouse#13322]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://periodex.co/

### What happened?

Lighthouse gets stuck on https://periodex.co/

### What did you expect?

A lighthouse score

### What have you tried?

Trying pageSpeed insight. it works as expected:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fperiodex.co%2F

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.4.0

### Chrome Version

Version 95.0.4638.69 (Official Build) (x86_64)

### OS

Mac OS

**Comment by adamraine** [comment]
This is probably the same issue as https://github.com/GoogleChrome/lighthouse/issues/13236

**Comment by connorjclark** [comment]
Tracking in #13396, please follow there.
