### ISSUE TITLE
does not not detect redirect to https

### ISSUE THREAD

**Issue by KO81** [GoogleChrome/lighthouse#13329]
![Screenshot at 2021-11-05 03-00-52](https://user-images.githubusercontent.com/65924978/140445833-fc1c8f74-a1ea-4ab4-b498-7d8ff1cd79a9.png)
**Describe the bug**
does not not detect redirect to https.

**To Reproduce**
1. Go and 'test my site 'ko81.eu.ngrok.io'.'
2. Try open my page in http protocol  'internal php redirect makes this it impossible'

**Expected behavior**
error on https://web.dev/measure/ like shown in the attachment.

**Screenshots**
are attached

**Comment by connorjclark** [comment]
The next version of Lighthouse will be removing this audit - #12643
