### ISSUE TITLE
installability status incorrect with chrome headless

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#13327]
On a page that has a valid manifest but **no** SW, when fetching the `installabilityErrors`,  we expect to see `no-matching-service-worker`.

However in Chrome headless, this isn't present and the errors array is empty. Lighthouse currently interprets this as a service-worker that's valid and has offline capability. But that's wrong.

https://blog.tomayac.com/ exhibits this. 
Also https://past-cemetery.surge.sh/

I've filed a chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1267022

-----------

Connor suggested a workaround: 

> if `(global.isLightrider)` could we manually add the `no-matching-service-worker` error code if we don't like what we find in `navigator.serviceWorker.getRegistrations()`

![image (43)](https://user-images.githubusercontent.com/39191/140433511-5f6b80c2-c536-4419-a45f-cbc4a28fc5f1.png)

> we'd have to verify the scope ourselves, and fetch that the file exists
> and wouldn't be able to test the whole "works offline" bit

But yes.. that does seem reasonable.

Adam also suggested we create a new LH-specific error code for this case.

------------

old internal context on headless & pwa: b/119875011

**Comment by connorjclark** [comment]
I confirmed that `node lighthouse-cli https://past-cemetery.surge.sh/ -G --chrome-flags=--headless=chrome` correctly emits an installability error. nice!

But I don't recall if this headless mode is available to us in PSI...

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
