### ISSUE TITLE
Consider using sharp or other async image processing library instead of jpeg-js

### ISSUE THREAD

**Issue by wojtekmaj** [GoogleChrome/lighthouse#13336]
**Feature request summary**

Replace jpeg-js with sharp or other async image processing library.

**What is the motivation or use case for changing this?**

On jpeg-js own home page we can read:

> NOTE: this is a synchronous (i.e. CPU-blocking) library that is much slower than native alternatives. If you don't need a pure javascript implementation, consider using async alternatives like sharp in node or the Canvas API in the browser.

**How is this beneficial to Lighthouse?**

On my machine, Lighthouse takes around 9000 ms to execute, 300ms of which is generating screenshot thumbnails. It's one of the slowest, if not *the* slowest, "audit". Taking advantage of async processing, possibly processing multiple thumbnails at once, has a potential of shaving off quite a few milliseconds from processing.

**Comment by connorjclark** [comment]
Lighthouse runs in Node and the browser, so all of our deps must be able to work in both. `sharp` relies on `libvips`, so we can't use it.

The audit phase is typically less than 10% of the duration of the entire LH run (most takes places in the gather stage). On my run of cnn.com, the audit phase of `screenshot-thumbnails` (where `jpeg-js` is used) takes ~250ms (less than 1% of the total run duration). You can verify this by opening this trace in the Devtools performance panel: https://gist.github.com/connorjclark/7d320ec5cf44535a8820f7e50166500a (generated with https://github.com/GoogleChrome/lighthouse/blob/5271aa539032bf7e7413217b2c92b4e253fa6800/lighthouse-core/scripts/generate-timing-trace.js#L12 )

Given that, I don't believe it makes sense to change our dependency here if the motivation is for speed.
