### ISSUE TITLE
Unintended add '/' to the end in URL after upgrading v9 (PageSpeed Insights) #13373

### ISSUE THREAD

**Issue by toanbku** [GoogleChrome/lighthouse#13378]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.google.com

### What happened?

Follow these URLs:
- https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.google.com
- https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.google.com%2F

It is quite different, but when entering it, the URL at the box of the pagespeed insight is the same (always have the '/' in the end)
![image](https://user-images.githubusercontent.com/28706996/141901663-137abf16-8901-4e9f-ae56-a779a3affb89.png)

This thing is never happening on v7 or v8.

### What did you expect?

Keep the same behavior as previous version

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

v9.0.0

**Comment by adamraine** [comment]
Trailing slashes after the domain shouldn't matter so `https://www.google.com` is the same as `https://www.google.com/`. 

PSI does not force a trailing slash when it does identify a different URL (e.g. `https://web.dev/learn-web-vitals` vs `https://web.dev/learn-web-vitals/`). I think this is WAI.

**Comment by paulirish** [comment]
We have two different places that normalize URLs. And one of them conditionally adds a trailing slash while the other doesn't.

We should make them operate consistently.

Agree with adam that it probably doesn't make a material difference, but since we're getting picky about URLs we should be consistent ourselves.

**Comment by toanbku** [comment]
Hi @adamraine, @paulirish 

With these websites that use Next.js, by default, it will redirect if the URL has trailing '/'. For more detail, please visit the document: https://nextjs.org/docs/api-reference/next.config.js/trailing-slash

Because of redirecting, the URL has trailing '/' have the LOWER score than the URL not having trailing '/'

So please keep the light house same behavior with the previous version

**Comment by toanbku** [comment]
Please see the screenshot below

<img width="1539" alt="Pasted_Image_17_11_2021__09_03" src="https://user-images.githubusercontent.com/28706996/142095760-198fa719-08ed-4e18-a5a0-ab9c4806a8d5.png">

**Comment by connorjclark** [comment]
I had the same misunderstanding you did: yes, `https://nextjs.org/docs/api-reference/next.config.js/trailing-slash` is a different url from `https://nextjs.org/docs/api-reference/next.config.js/trailing-slash/`, but `https://nextjs.org` _does not exist_. You can do `new URL('https://nextjs.org').href` (or `.pathname)` to see that the url path is normalized to be at least `/`, and can never be an empty string.

If you type `https://nextjs.org/docs/api-reference/next.config.js/trailing-slash` in the input box in pagespeed you will see we do not add a slash.

**Comment by jazyan** [comment]
Fix (internal): cl/410531354

**Comment by jazyan** [comment]
This should be fixed, eg https://pagespeed.web.dev/report?url=https://nextjs.org/docs/api-reference/next.config.js/trailing-slash no longer appends a trailing slash to the URL, but feel free to reopen if there's anything missed.
