### ISSUE TITLE
Default to HTTPS if URL has no http:// in URL (PageSpeed Insights)

### ISSUE THREAD

**Issue by alonkochba** [GoogleChrome/lighthouse#13373]
**Feature request summary**
I noticed that if I only enter the URL, e.g. "www.reddit.com", PSI runs on "http://www.reddit.com" - 
https://pagespeed.web.dev/report?url=www.reddit.com

IMO it would make more sense to default to https://www.reddit.com if http:// is not explicitly requested in the URL
https://pagespeed.web.dev/report?url=https://www.reddit.com

**What is the motivation or use case for changing this?**
Over [90% of sites](https://httparchive.org/reports/state-of-the-web#pctHttps) are using HTTPS these days, this should be the default, it's also a bit annoying to go through the redirect from HTTP to HTTPS when running PSI without a protocol.

**How is this beneficial to Lighthouse?**
Encourage HTTPS first, ease of use

**Comment by paulirish** [comment]
Hmmm... Are you sure? 

if you don't type in the protocol, the site adds a `https://` prefix. (not HTTP)

are you seeing something different?

**Comment by connorjclark** [comment]
via the UI it already defaults to https, but yes via the URL it defaults to http. Is that what you mean?

**Comment by paulirish** [comment]
> via the UI it already defaults to https, but yes via the URL it defaults to http. Is that what you mean?

well... i don't know how @alonkochba managed to navigate to https://pagespeed.web.dev/report?url=www.reddit.com (some weird race condition where only some of the JS loaded before the form was submitted?)

.. but i can confirm that if you load that up, PSI is testing the http version. 

And that's inconsistent with what the url bar does when you type in something without a url protocol.


@jazyan this is a fun one for ya

**Comment by paulirish** [comment]
> @jazyan this is a fun one for ya

Found it. cl/410102054

**Comment by alonkochba** [comment]
Ah nice, the UI automatically adds https, I didn't notice that 👏  I think the previous Lighthouse UI didn't add HTTPS by default.

Anyways, this is about how the server handles the URL query parameter without protocol, which is very minor but what @paulirish said :-)

Thanks!

**Comment by connorjclark** [comment]
Will go out with next release.
