### ISSUE TITLE
Manifest.webmanifest giving "Error while trying to use the following icon from the manifest"

### ISSUE THREAD

**Issue by JayantGoel001** [GoogleChrome/lighthouse#13372]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

http://jayantgoel001.github.io/

### What happened?

This is my manifest file: https://jayantgoel001.github.io/manifest.webmanifest

When I run the lighthouse, for an **instance** this error occurs in the console.

![image](https://user-images.githubusercontent.com/54479676/141831065-5f734e88-2476-4426-b18f-23de4c42861e.png)

This happens when icons have a purpose as **any** in the manifest.

PS the above link is a valid image
`https://jayantgoel001.github.io/assets/images/Profile-pic-144x144.png`

Because of the above error, it affects my performance and caching also.

### What did you expect?

This issue should not pop up in the console during the generation of the report of the lighthouse.

### What have you tried?

I tried every combination of **purpose** in the manifest file. But if I make it "maskable" chrome dev tools give an error that one icon should have **any**  as the purpose.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

latest version

### Chrome Version

96.0.4664.45

### OS

Windows

**Comment by JayantGoel001** [comment]
@connorjclark Any update on this?

**Comment by connorjclark** [comment]
I do not see this issue in Stable chrome nor the Node CLI. I do see `Lighthouse could not determine if there was a service worker. Please try with a newer version of Chrome`: for that, follow #13396

**Comment by JayantGoel001** [comment]
> I do not see this issue in Canary chrome nor the Node CLI. I do see in Canary chrome `Lighthouse could not determine if there was a service worker. Please try with a newer version of Chrome`: for that, follow #13396

Hi @connorjclark 
Can you check this video where I recorded the issue?
[link](https://drive.google.com/file/d/1-41YcK9W2pDalzEHVH4QpOAz8mbVX7qV/view?usp=sharing)
At 37th-second above issue occurs and PS I am using the latest version of chrome.

**Comment by connorjclark** [comment]
I see the same Stable chrome. By latest chrome do you mean Canary? https://www.google.com/chrome/canary/ In Canary I get the audit-level error (not a hang) I pasted above

**Comment by JayantGoel001** [comment]
> I see the same in Stable chrome. By latest chrome do you mean Canary? https://www.google.com/chrome/canary/ In Canary I get the audit-level error (not a hang) I pasted above

Nope, I am using the latest version of stable chrome.
