### ISSUE TITLE
Link in 9.0.0 Changelog broken

### ISSUE THREAD

**Issue by henrihelvetica** [GoogleChrome/lighthouse#13376]
["What's new in Lighthouse 9.0 blog post"](https://developer.chrome.com/blog/lighthouse-9-0/) in the Changelog is broken.

**Comment by connorjclark** [comment]
https://deploy-preview-1724--developer-chrome-com.netlify.app/blog/lighthouse-9-0/ for now

**Comment by brendankenny** [comment]
@henrihelvetica the article should be live early tomorrow (for some US time zone)

**Comment by henrihelvetica** [comment]
@brendankenny cool. I was going to share the link, but figured I'd check 1st. Thx.
