### ISSUE TITLE
vendor.bundle.js violates Content Security Policy directive trusted-types

### ISSUE THREAD

**Issue by jplejacq-quoininc-com** [GoogleChrome/lighthouse#13389]
When using lighthouse on a website that enforces a Content Security Policy (CSP) that includes the trusted-type directive as follows:

`content-security-policy: trusted-types; require-trusted-types-for 'script'`

the following error is show in Chrome's console:

```
Refused to create a TrustedTypePolicy named 'dompurify' because it violates the following Content Security Policy directive: "trusted-types ".
W @ vendor.bundle.js:163
e @ vendor.bundle.js:163
(anonymous) @ vendor.bundle.js:163
31699 @ vendor.bundle.js:163
r @ content.bundle.js:62
17605 @ content.bundle.js:31
r @ content.bundle.js:62
48269 @ content.bundle.js:1
r @ content.bundle.js:62
(anonymous) @ content.bundle.js:62
r.O @ content.bundle.js:62
(anonymous) @ content.bundle.js:62
(anonymous) @ content.bundle.js:62
vendor.bundle.js:163 TrustedTypes policy dompurify could not be created.
W @ vendor.bundle.js:163
e @ vendor.bundle.js:163
(anonymous) @ vendor.bundle.js:163
31699 @ vendor.bundle.js:163
r @ content.bundle.js:62
17605 @ content.bundle.js:31
r @ content.bundle.js:62
48269 @ content.bundle.js:1
r @ content.bundle.js:62
(anonymous) @ content.bundle.js:62
r.O @ content.bundle.js:62
(anonymous) @ content.bundle.js:62
(anonymous) @ content.bundle.js:62
```

**Comment by adamraine** [comment]
I can't reproduce this locally on a generic page, are you able to share a URL where this is happening?

**Comment by jplejacq-quoininc-com** [comment]
@adamraine, here's a test site that exhibits the issue.

https://ettyproject.org/

**Comment by adamraine** [comment]
This error is emitted without running Lighthouse, so it's probably not an issue with Lighthouse. I'm not getting the error in incognito, so it might be caused by an extension.

**Comment by jplejacq-quoininc-com** [comment]
I cannot replicate this. When using Chrome 96, I do not get an error in the console or on the server which uses the report-to API.

This is definitely a lighthouse issue. The reported error in console clearly shows it to be in the lighthouse JavaScript library.

**Comment by paulirish** [comment]
Where is this `content.bundle.js` ? 

We don't use that file naming scheme in any lighthouse product deployments.


can you 'reveal in sidebar' on the content.bundle.js so we can see where its coming from? 
![image](https://user-images.githubusercontent.com/39191/142332945-649272fd-d830-456e-a9e2-1e77c81ac647.png)


also, How are you using lighthouse? with chrome devtools?

**Comment by jplejacq-quoininc-com** [comment]
This is indeed not an issue with Lighthouse and the issue can be closed.

You gave me the hint. The console error message was triggered by the axe DevTools extension [1]. Even though I was not using it, loading the page under lighthouse caused execution of the extension. When I disabled the extension, the error went away.

I will file a defect report with the extension vendor. Thank you for your help.

[1] https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US

**Comment by paulirish** [comment]
Sounds good!

Also, I like axe... But I will say that extension has non negligible perf impact on every single page load

**Comment by dylanb** [comment]
@paulirish we have recently moved axe-core into a resource that only gets loaded when used and are making other changes to do the same

**Comment by dylanb** [comment]
@jplejacq-quoininc-com please file a bug here https://github.com/dequelabs/axe-core

**Comment by paulirish** [comment]
> @paulirish we have recently moved axe-core into a resource that only gets loaded when used and are making other changes to do the same

oh sweet! great news.  

@dylanb  And just so i don't look like a total jerk who's badmouthing your project over here... :p  ... Here's my [bug report of this issue](https://github.com/dequelabs/axe-core/issues/679).  And now from the duped issue I see your recent comment saying the same thing. nice stuff!

**Comment by jplejacq-quoininc-com** [comment]
@dylanb , I created issue https://github.com/dequelabs/axe-core/issues/3301

**Comment by dylanb** [comment]
> > @paulirish we have recently moved axe-core into a resource that only gets loaded when used and are making other changes to do the same
> 
> oh sweet! great news.
> 
> @dylanb And just so i don't look like a total jerk who's badmouthing your project over here... :p ... Here's my [bug report of this issue](https://github.com/dequelabs/axe-core/issues/679). And now from the duped issue I see your recent comment saying the same thing. nice stuff!

@paulirish in total contrast to a jerk, we thank you for all of the things you and your team have done to move axe-core forward - thanks and keep pushing us!!
