### ISSUE TITLE
report feature: Copy opportunity resources to CSV

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#13381]
https://twitter.com/aleyda/status/1460569455164014593

> Something that would be amazing to have: The option to download/export (whether as CSV or Google Sheets) the list of resources flagged to generate issues in the "Opportunities" and "Diagnostics" areas. Would make it easier to share!

I guess rows would be our details items and columns their headers. we'd have to deduplicate columns and also add a column for audit. but.. doable.

**Comment by connorjclark** [comment]
Paul you want to close this?

**Comment by paulirish** [comment]
yeah.  if we do anything in this area i want to do something comprehensive and easy to use.. like an 'export to google sheets' and it somehow has *everything*. that'll require some investment to design it well for intended uses.

but i dont' want to take that on in the short term. so we'll close.
