### ISSUE TITLE
Difficulties with new https://pagespeed.web.dev/

### ISSUE THREAD

**Issue by DamonHD** [GoogleChrome/lighthouse#13380]
**Describe the bug**
A couple of immediate usability regressions for me.

**To Reproduce**
1. Go to https://pagespeed.web.dev/ with JavaScript off.
2. Click on the URL entry box.
3. Typing the URL is obscured by the "Enter a web page URL" text.

**Expected behavior**
I expect a page such as this to be fully functional (even if not as pretty) with JS disabled.  By default for security I have JS disabled on most pages and all new ones.

**Notes**
See: https://twitter.com/EarthOrgUK/status/1460514673103708166
Also text seems v small and/or lower contrast at first blush.  Not all users of this page will have perfect eyesight.  This also seems to be a potential a11y issue therefore.

For me entire page seems less usable than before, though some of that will just be the shock of change.

**Comment by DamonHD** [comment]
I went and had another look and saw several places where the text was too grey.  I know low contrast is fashionable, but it makes text hard/slow to read.  Small screens and/or older eyes don't help either.  I suggest keeping all text fully black on white or vv, and adjust size/weight/style instead.  I appreciate you may be following a company-wide style book, but maybe it needs fixing.

At such time as I'm using the page in earnest, if I have any more detail to add I'll post again.

Rgds

Damon

**Comment by paulirish** [comment]
I'd still be interested in hearing about any *specific* places the contrast is bad.  Without that called out, it'd be silly for us to be making changes.

> > Typing the URL is obscured by the "Enter a web page URL" text.
> 
> yeah this is definitely a bug. we have a fix on its way.

this was fixed a while ago now
