### ISSUE TITLE
Can not see the calculator on PageSpeed Insight

### ISSUE THREAD

**Issue by toanbku** [GoogleChrome/lighthouse#13397]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://pagespeed.web.dev/report?url=https%3A%2F%2Fsvelte.dev%2F

### What happened?

When I enter the "See calculator"

<img width="1656" alt="Pasted_Image_19_11_2021__14_52" src="https://user-images.githubusercontent.com/28706996/142585848-083f9dd6-d615-4864-9d27-7e2c07b0c33f.png">

It opens a new tab, but the content is weird, in my case the link is https://googlechrome.github.io/lighthouse/scorecalc/#FCP=2280&TTI=2280&SI=2397&TBT=0&LCP=2280&CLS=0&FMP=2280&device=mobile&version=9.0.0

![image](https://user-images.githubusercontent.com/28706996/142585885-680d5f0d-68e6-4f82-b4db-f61c8f6d3b73.png)

### What did you expect?

Same with v8 version, it should display the calculator

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

v9.0.0

**Comment by adamraine** [comment]
@paulirish move to https://github.com/paulirish/lh-scorecalc? Needs new scoring guide.

**Comment by connorjclark** [comment]
fixed
