### ISSUE TITLE
LH report a text out of the viewport as LCP

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#13405]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://intersindicalrm.org/

### What happened?

On Versión 96.0.4664.45 (Build oficial) (64 bits)  the Lighthouse 8.5.0 report a text as the LCP element, but the reported text is out of the viewport. Mobile test, in Desktop test it reports a image.

### What did you expect?

Report some thing in the viewport as the spec for LCP say "LCP measures when the largest content element in the viewport is rendered to the screen"

### What have you tried?

Runin LH in hrome Dev Tools

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.5.0

### Chrome Version

96.0.4664.45 (Build oficial) (64 bits)

### OS

Windows 11

**Comment by brendankenny** [comment]
@Lofesa I'm not able to reproduce this now. Lighthouse points to an image for LCP in both desktop and mobile. Did the site change or are you similarly seeing it working now?

**Comment by Lofesa** [comment]
@brendankenny 
Have you tested with dev tools?
The text in the image is from the 5 post in the url. These post is out of the viewport.

![Captura de pantalla 2021-12-14 231210](https://user-images.githubusercontent.com/22342793/146087760-85f98c76-f4cb-4696-af4a-b42662926ea8.jpg)


![Captura de pantalla 2021-12-14 232039](https://user-images.githubusercontent.com/22342793/146088661-4192c634-4923-44fb-90a2-fc1ef4395378.jpg)

This text

![Captura de pantalla 2021-12-14 231810](https://user-images.githubusercontent.com/22342793/146088317-56dbbd3b-6ba3-43a7-b159-6718755d3f20.jpg)

**Comment by Lofesa** [comment]
Never mind.  Deletaed all data, uninstalled chrome, installed again and then no issue
