### ISSUE TITLE
Lighthouse is freezing at the start of audit

### ISSUE THREAD

**Issue by rocc-o** [GoogleChrome/lighthouse#13404]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

http://127.0.0.1:8887

### What happened?

Both in Chrome and Microsoft Edge (updated) LIghthouse is freezing forever at the start of audit, stuck at the startup process.
This is happening since the last update of Chrome. Until a few minutes ago it was working on Edge only, as Edge was automatically updated a few minutes ago Lighthouse ceased to work also on Edge.

Chrome
Versione 96.0.4664.45 (Build ufficiale) (a 64 bit)

Microsoft Edge
Versione 96.0.1054.29 (Build ufficiale) (64 bit)

### What did you expect?

To run Lighthouse audit

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

v8.6.0 (I guess this might be the version, in fact I cannot check it on Lighthouse as it is stucked)

### Chrome Version

Versione 96.0.4664.45 (Build ufficiale) (a 64 bit)

### OS

Windows 10 64bit

**Comment by connorjclark** [comment]
probably #13396
