### ISSUE TITLE
Lighthouse returned error: NOT_HTML. The page provided is not HTML (served as MIME type text/plain).

### ISSUE THREAD

**Issue by AjjuRao** [GoogleChrome/lighthouse#13403]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.autumnwish.com/

### What happened?

I have tested my site URL  more than 10 times in last three four days after PSI new update... i am getting this error...
Lighthouse returned error: NOT_HTML. The page provided is not HTML (served as MIME type text/plain).
I have seen that this issue is with almost all shopify URLs. 

### What did you expect?

I Want some solution to test my site speed

### What have you tried?

Nothing yet

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

v9.0.0

### Chrome Version

Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by adamraine** [comment]
Looks like https://github.com/GoogleChrome/lighthouse/issues/13379
