### ISSUE TITLE
dropdown menu does not work in "save as html" report from standalone report

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#13410]
No errors in console either. Clicking on the three dots menu just does nothing.

**Comment by connorjclark** [comment]
same for View Treemap button. and the sticky header does not appear. I suppose all of report ui features are missing

**Comment by connorjclark** [comment]
Ah, clearly it is because https://github.com/GoogleChrome/lighthouse/blob/4059955a2375d01e4fe0f095c82611424738fbe6/report/renderer/report-ui-features.js#L157 is not sufficient. It misses out on all the scripts. it doesn't even have `__LIGHTHOUSE_JSON__`! @paulirish can we just grab the entire document html here like before?

**Comment by paulirish** [comment]
I tried a horribly gross hack for this which allows the standalone HTML report to generate another one of itself by reading the existing classes and `.toString()`ing them: [`reportgenerator-quine`#diff-a6fdb4db7b](https://github.com/GoogleChrome/lighthouse/compare/reportgenerator-quine#diff-a6fdb4db7be3f20cbb5b4aeb5de1ad54bc991b4341647edbd9ce99741c29360cR112)

its gross and i don't think its worth persuing anymore. tho
