### ISSUE TITLE
Why consider explicitly loaded js in LCP?

### ISSUE THREAD

**Issue by oppure** [GoogleChrome/lighthouse#13426]
**Summary**
Hi
I use google recaptcha on a website and I use the explicit render otpion so that the recaptcha.js file is loaded only if the user sets the focus on a certain input of a certain form. Lighthouse always considers the loading of recaptcha.js to compute LCP, I think this is unfair and unrealistic since on 99% of the page views recaptcha.js is never loaded.
Thank you and regards

**Comment by adamraine** [comment]
Are you able to share a URL where this is happening?

[recaptcha docs](https://developers.google.com/recaptcha/docs/display#explicit_render) suggest loading the script inline with extra params. Assuming this is what you're doing, it makes sense for Lighthouse to track it for performance metrics.

**Comment by oppure** [comment]
Hi and thank you for reading my post.

Sorry it seems to be more a recaptha issue with loading recaptcha__xx.js file even when using the explicit rendering. Discussed already here:
https://github.com/google/recaptcha/issues/236
https://github.com/google/recaptcha/issues/331

Thank you and kind regards.
