### ISSUE TITLE
Lighthouse Summary shows wrong device emulation information

### ISSUE THREAD

**Issue by chatur-sriganesh** [GoogleChrome/lighthouse#13436]
### Discussed in https://github.com/GoogleChrome/lighthouse/discussions/13434

<div type='discussions-op-text'>

<sup>Originally posted by **chatur-sriganesh** November 25, 2021</sup>
Hi,
Tried running lighthouse from puppeteer script with device emulation as "puppeteer.devices['iPad landscape']". Also visually i can see that resolution is now changed to that of an ipad.
However the report still shows the following:

"Emulated Moto G4
Slow 4G throttling
4x slowdown"

Any idea if i'm missing something here?

**code snippet i am using:**

const iPad = puppeteer.devices['iPad landscape'];
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  const flow = await startFlow(page, {name: 'Squoosh snapshots'});
  await page.emulate(iPad);
  await page.goto('https://squoosh.app/', {waitUntil: 'networkidle0'});
  await page.emulate(iPad);

</div>

**Comment by adamraine** [comment]
See https://github.com/GoogleChrome/lighthouse/discussions/13434#discussioncomment-1717085
