### ISSUE TITLE
Google PSI bug NOT_HTML. The page provided is not HTML (served as MIME type text/plain) 

### ISSUE THREAD

**Issue by FrankTuit** [GoogleChrome/lighthouse#13435]
@connorjclark 

Do you have an update about this subject? A lot of people depend on this tool and i'm wondering about the progress. Can you give us an estimation of the timeframe this issue gets solved? Hopefully you can answer my question.

Best,

Frank

**Comment by FrankTuit** [comment]
@brendankenny @connorjclark is it possible to update us on this issue?

**Comment by connorjclark** [comment]
https://github.com/GoogleChrome/lighthouse/issues/13379#issuecomment-971918405
