### ISSUE TITLE
Fails to capture screenshot (PROTOCOL_TIMEOUT)

### ISSUE THREAD

**Issue by yukihiko-shinoda** [GoogleChrome/lighthouse#13438]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://mksens.co.jp/

### What happened?

My web page can't be audited by Lighthouse.

### What did you expect?

Complete auditing and display report.

### What have you tried?

Even I run Lighthouse in Google Chrome secret mode, progress bar won't extend from following point no more.

![image](https://user-images.githubusercontent.com/17278878/143686359-1ac5c989-fe27-4700-a055-9a69ef20fe8e.png)

I also tried to debug by npm command line tool.
`PROTOCOL_TIMEOUT` occured when Lighthouse version 9.1.0 .

Note that until Lighthouse version 7.5.0, the process doesn't stop, completed auditing and output report, only following warning log was output:

```console
  LH:status Auditing: Full-page screenshot +6ms
  LH:Runner:warn FullPageScreenshot gatherer, required by audit full-page-screenshot, encountered an error: Protocol error (Page.captureScreenshot): Unable to capture screenshot +0ms
```

### How were you running Lighthouse?

CLI, Chrome DevTools

### Lighthouse Version

9.1.0

### Chrome Version

96.0.4664.45

### Node Version

17.1.0

### OS

WIndows

### Relevant log output

```shell
LH:status Gathering: FullPageScreenshot +194ms
  LH:method <= browser ERR:error Page.captureScreenshot  +128ms
  LH:status Disconnecting from browser... +2m
  LH:status Cleaning origin data +0ms
  LH:ChromeLauncher Killing Chrome instance 28 +1ms
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)
LHError: PROTOCOL_TIMEOUT
    at /usr/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:341:50
    at new Promise (<anonymous>)
    at Driver.sendCommandToSession (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:339:28)
    at Driver.sendCommand (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:362:17)
    at ExecutionContext._evaluateInContext (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/driver/execution-context.js:109:42)
    at ExecutionContext.evaluateAsync (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/driver/execution-context.js:146:25)
    at async Function.afterPass (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:341:7)
    at async Function.runPass (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:616:5)
    at async Function.run (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:509:29)
    at async Function._gatherArtifactsFromBrowser (/usr/lib/node_modules/lighthouse/lighthouse-core/runner.js:237:23)
```

**Comment by connorjclark** [comment]
Can you try on Chrome canary?

**Comment by jirkapinus** [comment]
> 

me on google canary too this error

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://www.slunecno.cz/
Chrome Version: 98.0.4738.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:146:58
    at new Promise (<anonymous>)
    at Driver$1.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:146:10)
    at Driver$1.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:146:257)
    at ExecutionContext$2._evaluateInContext (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:108:795)
    at ExecutionContext$2.evaluateAsync (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:109:403)
    at ExecutionContext$2.evaluate (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:109:772)
    at getBenchmarkIndex$2 (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:98:32)
    at Function.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:212:827)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:358:413)
`
<img width="960" alt="3" src="https://user-images.githubusercontent.com/75752573/144024224-2c35c76e-d0d5-4fa0-b267-0a9759101854.png">
``

**Comment by yukihiko-shinoda** [comment]
Same result on Chrome canary:

![image](https://user-images.githubusercontent.com/17278878/144076362-974b855a-72a4-4833-a736-470d00bfa960.png)

Chrome: 98.0.4738.0（Official Build）canary (64 bit)
Lighthouse: 100.0.0.0
Windows 10

**Comment by brendankenny** [comment]
@yukihiko-shinoda I'm not able to reproduce this in the CLI, DevTools (in Chrome Canary/99) or PSI. Are you still seeing this problem? Did something change on the test site?

**Comment by yukihiko-shinoda** [comment]
At first, it seemed to fix in Chrome Canary (my environment: 99.0.4766.0 (Official Build) canary (64 bit).
Normal Chrome (96.0.4664.93 (Official Build) (64 bit)) and CLI (9.1.0) still reproduce.

## Step to reproduce (CLI)

Dockerfile:

```docker
FROM debian:buster-slim
# Install deps + add Chrome Stable + purge all the things
RUN apt-get update && apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg \
  --no-install-recommends \
  && curl -sSL https://deb.nodesource.com/setup_17.x | bash - \
  && curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
  && apt-get update && apt-get install -y \
  google-chrome-stable \
  fontconfig \
  fonts-ipafont-gothic \
  fonts-wqy-zenhei \
  fonts-thai-tlwg \
  fonts-kacst \
  fonts-symbola \
  fonts-noto \
  fonts-freefont-ttf \
  nodejs \
  --no-install-recommends \
  && apt-get purge --auto-remove -y curl gnupg \
  && rm -rf /var/lib/apt/lists/*

ARG CACHEBUST=1
RUN npm install -g lighthouse@9.1.0

# Add Chrome as a user
RUN groupadd -r chrome && useradd -r -g chrome -G audio,video chrome \
  && mkdir -p /home/chrome/reports && chown -R chrome:chrome /home/chrome

# some place we can mount and view lighthouse reports
VOLUME /home/chrome/reports
WORKDIR /home/chrome/reports

# Run Chrome non-privileged
USER chrome

# Drop to cli
CMD ["/bin/bash"]
```

docker-compose.yml:

```yaml
version: '3.8'
services:
  lighthouse:
    build: .
    image: futureys/lighthouse:development
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./reports:/home/chrome/reports
```

```console
docker-compose run --rm lighthouse
lighthouse --chrome-flags="--headless --disable-gpu" https://mksens.co.jp/
```

cf. [dockerfiles/lighthouse at master · justinribeiro/dockerfiles](https://github.com/justinribeiro/dockerfiles/tree/master/lighthouse)

**Comment by adamraine** [comment]
@yukihiko-shinoda since this is a container environment, can you try running Chrome with the flag `--disable-dev-shm-usage`? I think you would change your command to:

```sh
lighthouse --chrome-flags="--headless --disable-gpu --disable-dev-shm-usage" https://mksens.co.jp/
```

**Comment by yukihiko-shinoda** [comment]
@adamraine Thanks for your advice, then I got succeed to get report.html without any errors.
I checked Google Chrome version in container:

```console
$ google-chrome --version
Google Chrome 96.0.4664.110
```

On the other hand, today I updated Google Chrome (not Canary) of Windows too.
It still reproduces.
Updated version is  96.0.4664.110 (Official Build) (64 bit).
(It's no problem for me, I can use Lighthouse with Chrome Canary.)

**Comment by adamraine** [comment]
> then I got succeed to get report.html without any errors.

Awesome! `--disable-dev-shm-usage` is one of our recommended workarounds for `PROTOCOL_TIMEOUT` when running Lighthouse from a container https://github.com/GoogleChrome/lighthouse/issues/6512#issuecomment-924123935. I think we can consider your issue with the container resolved.

> On the other hand, today I updated Google Chrome (not Canary) of Windows too.
It still reproduces.
Updated version is 96.0.4664.110 (Official Build) (64 bit).
(It's no problem for me, I can use Lighthouse with Chrome Canary.)

Are you running Lighthouse from DevTools on windows? Getting an error in Chrome Stable but not Chrome Canary is probably https://github.com/GoogleChrome/lighthouse/issues/13396 if you are running Lighthouse in DevTools.

**Comment by yukihiko-shinoda** [comment]
> Are you running Lighthouse from DevTools on windows? Getting an error in Chrome Stable but not Chrome Canary is probably #13396 if you are running Lighthouse in DevTools.

Yes, I run from DevTools on Windows. I tryed disabling Clear Storage, then Lighthouse succeed to finish audit.
I'll follow #13396, thanks!
