### ISSUE TITLE
Service-Worker is working but not recognized 

### ISSUE THREAD

**Issue by philipbrembeck** [GoogleChrome/lighthouse#13451]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://vegancheck.me

### What happened?

Chrome does find the service worker and it seems to work fine and it also shows the Install app icon in the address bar.
Lighthouse however comes of with the following error:

> Lighthouse could not determine if there was a service worker. Please try with a newer version of Chrome.

### What did you expect?

Lighthouse not coming up with an error/Lighthouse recognizing my service-worker.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.0.0

### Chrome Version

98.0.4739.0 canary (x86_64)

### OS

Mac

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/13396
