### ISSUE TITLE
Remove update-notifier

### ISSUE THREAD

**Issue by remcohaszing** [GoogleChrome/lighthouse#13453]
**Summary**

Currently lighthouse has 136 production dependencies including indirect dependencies. When `update-notifier` is removed, this is trimmed down to just 76. Of course these numbers don’t say anything about the types of packages it depends on.

I believe this is a lot of dependencies for an unimportant feature. (People should check for outdated packages regularly regardless of a CLI tool telling them to.)

**Comment by paulirish** [comment]
We appreciate the issue. We are very conservative when it comes to dependencies and always happy to reduce the count of transitive deps involved.

At the same time, we appreciate the value that update-notifier brings. Do you know of an alternative that's a bit more lean?

We'll also discuss dropping the feature entirely.

**Comment by remcohaszing** [comment]
As far as I can tell `update-notifier` is the go-to library to use for this feature.

I believe this is a useful feature to have for tools that are installed globally (i.e. `npm` / `yarn`), but most CLI tools, including `lighthouse` tend to be installed locally in a project. Typically such projects have deliberately locked their dependencies, and users manage outdated dependencies through a package manager. For such tools I personally don’t see the added value of `update-notifier` (imagine every other CLI tool in your `node_modules` would use that).

I don’t use `lighthouse` as a dependency directly. Instead it’s a dependency of `@lhci/cli`, which is also maintained by the Google Chrome team.

When comparing the dependencies in [`@lhci/cli/package.json`](https://github.com/GoogleChrome/lighthouse-ci/blob/main/packages/cli/package.json#L15-L31) and [`lighthouse/package.json`](https://github.com/GoogleChrome/lighthouse/blob/master/package.json#L186-L217), you can see they both use a different major version of `update-notifier`. Both pull in a significantly different set of dependencies. If both would use the same version it can be deduped. 

It’s not just `update-notifier` by the way. They also use diffent major versions of `chrome-launcher`, `lighthouse-logger`, `open`, `yargs`,`yargs-parser`, and `inquirer` instead of `enquirer`.

**Comment by paulirish** [comment]
True. This does suggest that us splitting our the CLI package from the node API would probably be useful. 

We did end up doing the exact same thing with speedline for the same reasons. https://github.com/paulirish/speedline/issues/39

**Comment by connorjclark** [comment]
Let's remove it.
