### ISSUE TITLE
Top bar (to generate new report) disappears when clicking on buttons

### ISSUE THREAD

**Issue by dorianmariefr** [GoogleChrome/lighthouse#13466]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://googlechrome.github.io/lighthouse/treemap/?gzip=1#H4sIAAAAAAAAE4WPsYrDMAyGX8VoTkiGmzJ37ZTLVG4QsdIIVNu1lUIpeffaTqfj4Ebp+78f6QWyRhheEOm+UVKyUxQYYFUNQ9eJn1FWn3T46vu+gwYWdij/ZHCzrKm0pjly0FYj0Q1Da1GxrNlm/S/WgLIKZTpWar4Pak4HtXRY7F3OTImsWXw0nw6DIeRQmn3MFW4T+QwnTkHwefa2VLPLzg2VH1QrFVnqtfoMhf+6yGUr48vPvu8NzN4tfB1Jld21WvX/4pFrpxFy6g0lkFanVQEAAA==

### What happened?

I generate a report, click on the performance for instance

### What did you expect?

I can generate a new report

### What have you tried?

I can switch tabs and it will let me generate a new report (and lookup past reports)

https://user-images.githubusercontent.com/58794487/144847733-c35faf89-79dd-42b1-b0e6-d9033e2d82b0.mov

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.5.0

### Chrome Version

96.0.4664.55

### OS

macOS

**Comment by adamraine** [comment]
Hmm that is odd. Unfortunately I can't reproduce with the same Chrome and Lighthouse versions on macOS.

Could you open [DevTools on DevTools](https://stackoverflow.com/questions/12291138/how-do-you-inspect-the-web-inspector-in-chrome) and see if there are any console errors when this happens?

**Comment by dorianmariefr** [comment]
no errors related I think:

<img width="1015" alt="Screenshot 2021-12-06 at 20 53 35" src="https://user-images.githubusercontent.com/58794487/144913205-fa2f9625-2d84-4aca-86fb-642c7c86d9fe.png">

I just got this error earlier:

LH:GatherRunner disconnect:error this._port.close is not a function +12ms

**Comment by connorjclark** [comment]
I've run across this too, but could never consistently repro it.

> LH:GatherRunner disconnect:error this._port.close is not a function +12ms

This is just noise but we've fixed it in the latest version.

**Comment by dorianmariefr** [comment]
The key is to click on the performance button for instance (where it says 88 for instance)

**Comment by connorjclark** [comment]
OK so I can repro it in stable Chrome, but not in my Canary chrome. Do you see it in Canary?

**Comment by connorjclark** [comment]
I'm thinking https://github.com/GoogleChrome/lighthouse/pull/13186 fixed it, which was released in LH 8.6

**Comment by dorianmariefr** [comment]
looks like it's fixed in canary, can't reproduce there and the PR linked seems related
