### ISSUE TITLE
meta viewport not found, but it is there ..

### ISSUE THREAD

**Issue by germmare** [GoogleChrome/lighthouse#13465]
Lighthouse don't find: 
meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes"

nor
meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=yes' /

nor
meta name="viewport" content="width=device-width, initial-scale=1.0"
( https://4nikola.de/aalfflaa/index.php)

**Comment by estradanic** [comment]
I see you closed this, but I'm having the same problem and you didn't comment what fixed it. Help?
