### ISSUE TITLE
NOT_HTML. The page provided is not HTML

### ISSUE THREAD

**Issue by matkellyy** [GoogleChrome/lighthouse#13464]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://secomart.com

### What happened?

We tried to use PageSpeed Insights but we faced an error that "Lighthouse returned error: NOT_HTML. The page provided is not HTML (served as MIME type text/plain)."

We checked everything but we cannot find the issue and solve that.
Please check that.

### What did you expect?

We want to check our website's speed.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

v9.1.0

### Chrome Version

96.0.4664.45

**Comment by connorjclark** [comment]
#13379
