### ISSUE TITLE
lighthouse error

### ISSUE THREAD

**Issue by Leo555** [GoogleChrome/lighthouse#13479]
I use npm install lighthouse, and comes error 

![image](https://user-images.githubusercontent.com/16870698/145524061-4373d994-ab32-4543-ba40-7328011e4e45.png)

ligthhouse version: 9.1.0
system: macOS big sur 11.6
node version: v12.22.1
npm version: 6.14.12

**Comment by gazrobur** [comment]
Which version of [Node.js](https://nodejs.org/en/) you have?

**Comment by connorjclark** [comment]
We don't support Node 12 anymore. min is 14.15
