### ISSUE TITLE
Support APCA contrast method

### ISSUE THREAD

**Issue by carlosjeurissen** [GoogleChrome/lighthouse#13477]
To better determine accessibility when it comes to enough contrast, we should think about moving towards APCA (Advanced Perceptual Contrast Algorithm) as specified in WCAG 3.

See:
https://twitter.com/DanHollick/status/1468958644364402702

**Comment by connorjclark** [comment]
We defer to axe for all thing a11y. Can you file an issue there? https://github.com/dequelabs/axe-core

**Comment by carlosjeurissen** [comment]
> We defer to axe for all things a11y. Can you file an issue there? https://github.com/dequelabs/axe-core

See: https://github.com/dequelabs/axe-core/issues/3325
