### ISSUE TITLE
"Content is sized correctly for the viewport" audit fails despite meeting passing criteria

### ISSUE THREAD

**Issue by maxeisen** [GoogleChrome/lighthouse#13470]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://maxeisen.me

### What happened?

When running a Lighthouse audit on my portfolio website, all PWA audits pass except for "Content is sized correctly for the viewport". No specific reason is cited, but the only criteria listed on the [info page for content width](https://web.dev/content-width/) is "The audit fails if `window.innerWidth` does not equal `window.outerWidth`".

When checking these two values in the Chrome DevTools console, the values are equal

![screenshot of issue](https://user-images.githubusercontent.com/44880676/144961344-ba46d7a3-0236-4e93-8d0b-9e836e480c3c.png)
.

### What did you expect?

I expect this audit to pass as it meets all specified criteria.

### What have you tried?

- Resizing window
- Docking DevTools on the side, bottom and in a separate window
- Checking `window.innerwidth` and `window.outerwidth` values in console
- Modifying the scale of `body` in my CSS

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.5.0

### Chrome Version

96.0.4664.45

### OS

Windows 10 and Mac OS Monterey

**Comment by adamraine** [comment]
This audit is not applicable for the desktop form factor, that's what the hollow gray circle is indicating. The audit is passing when I test your page on mobile form factor :)
