### ISSUE TITLE
PageSpeed Insights API response missing some audits

### ISSUE THREAD

**Issue by faizjamil** [GoogleChrome/lighthouse#13472]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.newsday.com/

### What happened?

Certain audits are not present in the response I get from the PageSpeed Insights API. 
In particular the following audits are missing: 
`"first-cpu-idle", "estimated-input-latency", "uses-webp-images", "uses-http2",  "appcache-manifest", "redirects-http","external-anchors-use-rel-noopener"`

Request URL: `https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://www.newsday.com&category=pwa&category=seo&category=performance&category=accessibility&category=best-practices`

### What did you expect?

I expected to have values or even be able to find the titles of the following audits in the responses I've been getting from the PageSpeed Insights API

`"first-cpu-idle", "estimated-input-latency", "uses-webp-images", "uses-http2",  "appcache-manifest", "redirects-http","external-anchors-use-rel-noopener"`

### What have you tried?

I have tried running multiple requests, changing around the values for `category` and `strategy` in the URL.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

v9.0.0 (If the version in the `lighthouseResult` object in the response is where I find it)

### OS

macOS

### Relevant log output

I would post the JSON response, but I hit the max file size limit on Pastebin.

**Comment by connorjclark** [comment]
Please see our changelog - these audits were either removed or renamed. https://github.com/GoogleChrome/lighthouse/releases

Except for `uses-http2` - that one is explicitly turned off in PSI due to infra issues. #7326
