### ISSUE TITLE
Lighthouse error message

### ISSUE THREAD

**Issue by glewis3280** [GoogleChrome/lighthouse#13486]
**I need to know how to fix this issue**.
I am not an experienced developer.
Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404)

**Comment by adamraine** [comment]
Can you provide the URL where this is happening?

**Comment by glewis3280** [comment]
Sure!https://inspirational-quote-tshirts.com/
Regards,Gene Lewis
 
 
 
-----Original Message-----
From: Adam Raine ***@***.***>
To: GoogleChrome/lighthouse ***@***.***>
CC: GEF6560 ***@***.***>; Author ***@***.***>
Sent: Mon, 13 Dec 2021 16:23
Subject: Re: [GoogleChrome/lighthouse] Lighthouse error message (Issue #13486)

Can you provide the URL where this is happening?—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by adamraine** [comment]
The document request does respond with a 404 status code. Lighthouse doesn't support auditing 404 pages, but you can follow along in https://github.com/GoogleChrome/lighthouse/issues/10493 for updates on that.

**Comment by glewis3280** [comment]
Hello Adam,I have had a look, but still not sure what the solution is to the 404 issue.Any suggestions would be appreciated as I am not a developer.
Regards,Gene Lewis
 
 
-----Original Message-----
From: Adam Raine ***@***.***>
To: GoogleChrome/lighthouse ***@***.***>
CC: GEF6560 ***@***.***>; Author ***@***.***>
Sent: Mon, 13 Dec 2021 17:09
Subject: Re: [GoogleChrome/lighthouse] Lighthouse error message (Issue #13486)

The document request does respond with a 404 status code. Lighthouse doesn't support auditing 404 pages, but you can follow along in #10493 for updates on that.—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by connorjclark** [comment]
That is out of scope for us, sounds like you need to hire a developer or find a generic software help forum.

**Comment by glewis3280** [comment]
Thanks for the response. Much appreciated.
 
 
 
-----Original Message-----
From: Connor Clark ***@***.***>
To: GoogleChrome/lighthouse ***@***.***>
CC: GEF6560 ***@***.***>; Author ***@***.***>
Sent: Mon, 13 Dec 2021 18:38
Subject: Re: [GoogleChrome/lighthouse] Lighthouse error message (Issue #13486)

That is out of scope for us, sounds like you need to hire a developer or find a generic software help forum.—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
