### ISSUE TITLE
jitsulab.no causes mobile LCP test to error

### ISSUE THREAD

**Issue by folknor** [GoogleChrome/lighthouse#13481]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://jitsulab.no

### What happened?

```
Error!
Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_LCP)
```
This happens both on https://pagespeed.web.dev/report?url=https%3A%2F%2Fjitsulab.no%2F (lighthouse 9.0.0) and in chrome devtools 98.0.4750.0 / lighthouse 9.1.0.

### What did you expect?

No error.

### What have you tried?

I ran the test at least 3 times in both. Also ran the test on pagespeed.web.dev using Firefox with the same result.

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools

### Lighthouse Version

9.1.0

### Chrome Version

98.0.4750.0

### OS

Linux

**Comment by connorjclark** [comment]
All the content in the initial viewport is a `video` element (currently not considered as potential LCP element, I think this may come later), or a `nav` with no text and just `svg` (also currently not supported), so there is no contentful element of any size to measure.

https://web.dev/lcp/#:~:text=Note%2C%20restricting%20the%20elements%20to%20this%20limited%20set%20was

____

`grep -i 'largestContentfulPaint' latest-run/defaultPass.trace.json`

```
  {"args":{"main_frame_tree_node_id":2},"cat":"loading","name":"NavStartToLargestContentfulPaint::Invalidate::AllFrames::UKM","ph":"I","pid":56175,"s":"t","tid":259,"ts":67889094589,"tts":781589},
  {"args":{"main_frame_tree_node_id":2},"cat":"loading","name":"NavStartToExperimentalLargestContentfulPaint::Invalidate::AllFrames::UKM","ph":"I","pid":56175,"s":"t","tid":259,"ts":67889094604,"tts":781603},
  {"args":{"main_frame_tree_node_id":2},"cat":"loading","name":"NavStartToLargestContentfulPaint::Invalidate::AllFrames::UKM","ph":"I","pid":56175,"s":"t","tid":259,"ts":67889455048,"tts":819967},
  {"args":{"main_frame_tree_node_id":2},"cat":"loading","name":"NavStartToExperimentalLargestContentfulPaint::Invalidate::AllFrames::UKM","ph":"I","pid":56175,"s":"t","tid":259,"ts":67889455055,"tts":819973},
  {"args":{"main_frame_tree_node_id":2},"cat":"loading","name":"NavStartToLargestContentfulPaint::Invalidate::AllFrames::UKM","ph":"I","pid":56175,"s":"t","tid":259,"ts":67889625627,"tts":842378},
  {"args":{"main_frame_tree_node_id":2},"cat":"loading","name":"NavStartToExperimentalLargestContentfulPaint::Invalidate::AllFrames::UKM","ph":"I","pid":56175,"s":"t","tid":259,"ts":67889625637,"tts":842388},
  {"args":{"main_frame_tree_node_id":2},"cat":"loading","name":"NavStartToLargestContentfulPaint::Invalidate::AllFrames::UKM","ph":"I","pid":56175,"s":"t","tid":259,"ts":67890082197,"tts":913188},
  {"args":{"main_frame_tree_node_id":2},"cat":"loading","name":"NavStartToExperimentalLargestContentfulPaint::Invalidate::AllFrames::UKM","ph":"I","pid":56175,"s":"t","tid":259,"ts":67890082208,"tts":913199},
  {"args":{"main_frame_tree_node_id":2},"cat":"loading","name":"NavStartToLargestContentfulPaint::Invalidate::AllFrames::UKM","ph":"I","pid":56175,"s":"t","tid":259,"ts":67890732187,"tts":963220},
  {"args":{"main_frame_tree_node_id":2},"cat":"loading","name":"NavStartToExperimentalLargestContentfulPaint::Invalidate::AllFrames::UKM","ph":"I","pid":56175,"s":"t","tid":259,"ts":67890732194,"tts":963227},

```
