### ISSUE TITLE
Horizontal slider detected as CLS

### ISSUE THREAD

**Issue by tomasts248** [GoogleChrome/lighthouse#13490]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.otzerling.com/

### What happened?

The background image inside the slider is reported with .3 of CLS

### What did you expect?

To not identify an horizontal slider as layout shift as it is the expected behavior.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

9.0

**Comment by adamraine** [comment]
> The background image inside the slider is reported with .3 of CLS

I don't know what this is referring to. Could you provide some more details about this element and its background image?

**Comment by brendankenny** [comment]
@tomasts248 I'm not able to reproduce the problem with the given URL, so we'd need more information to know what you ran into.

**Comment by tomasts248** [comment]
Okey it happened with render-blocking optimization enabled, so effectively after disabling it problems are gone..
