### ISSUE TITLE
Keyboard doesn't disappear if you tap "Done" since the last Google Chrome update

### ISSUE THREAD

**Issue by anna007108** [GoogleChrome/lighthouse#13493]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://jsfiddle.net/xdtuy6gv/

### What happened?

Hello! I would like to use `contenteditable="true"` for a text. If you type something with a mobile device, and tap then the `Done` of your keyboard, the keyboard should disappear. This works fine with Safari on my iPhone. But since the last update, it doesn't work with Google Chrome anymore. It just stays.

Here is a screenshot to show what button I mean:
<img width="258" alt="dfjkldsfs" src="https://user-images.githubusercontent.com/81040640/145876855-9d17a926-71b9-421d-8c04-8abb43960ee7.png">

Here is the code that I have used:

`<div contenteditable="true">Hello, world!</div>
`

### What did you expect?

The keyboard should disappear after tapping `Done` or elsewhere.

### What have you tried?

I thought about solving this issue with JavaScript. Does it make sense?

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

v9.1.0

### OS

iOS

**Comment by connorjclark** [comment]
This issue tracker is for Lighthouse not Chrome.
