### ISSUE TITLE
byte-efficiency smoke failure in CI

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#13507]
`Chrome ToT, batch 1` is currently reliably failing on three assertions in [`yarn smoke byte-efficiency`](https://github.com/GoogleChrome/lighthouse/blob/4afafaea251074ce41d9cb24749d629e6f6cc50f/lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency.js#L162):

```terminal
 ✘ difference at unminified-javascript audit.details.overallSavingsMs
    expected: ">500"
       found: 330

 ✘ difference at offscreen-images audit.details.items[3].url
    expected: "/large.svg$/"
       found: "http://localhost:10200/byte-efficiency/lighthouse-480x320.webp?lazilyLoaded=true"

 ✘ difference at uses-text-compression audit.details.overallSavingsMs
    expected: ">700"
       found: 480
```

([example log](https://github.com/GoogleChrome/lighthouse/runs/4539275722?check_suite_focus=true#step:10:96))

## Reproducing

I'm not able to reproduce locally in Canary on a Mac today, but I can in a [ToT snapshot](https://download-chromium.appspot.com/), so presumably this will soon be in Canary. To check the problem, run `yarn static-server` for the test server, then:

```
node lighthouse-cli/index.js http://localhost:10200/byte-efficiency/tester.html  --config-path smoke-failure/byte-config.js --quiet --output json | jq '.audits["unminified-javascript"].details.overallSavingsMs'
```

On my machine, if it's less than 400 (usually around 300) it's the new "bad" value, if it's greater than 500 (usually around 600), it's the old "good" value. This lines up with the consistent failure in CI which asserts `>500` for this value.

## Bisect

I was able to bisect to [this range](https://chromium.googlesource.com/chromium/src/+log/718f73492051bccb52cdb936d1b8541ed5f78806..71a3d8e7a37c620907122f5e77a78da3b542d770), then did the individual commit bisect down to this change within that range: [Add NonBlockingCommit feature flag and implementation](https://chromium.googlesource.com/chromium/src/+/8d6308183e71b6312eb7448ac24f3b62ab23a3d3).

Tracking bug for NonBlockingCommit is https://crbug.com/1255972, and I noticed there's a Perf Sheriff flag of this commit in https://crbug.com/1280146#c11.

If you need a known good bisect version, I used `99.0.4766.0`, the version of the Dec 14, 2021 Mac Canary.

## Cause

The `overallSavingsBytes` has _not_ changed between the working `unminified-javascript` and `uses-text-compression`, but the `overallSavingsMs` has, so it looks like the change is happening in the lantern graph.

At least one proximate cause appears to be that the large 2048x1356 webp image gets downloaded later than it did before. Previously it was downloaded at the same time as two other images, but now it starts a full second later. This means there's less contention earlier in the load, which makes the same number of unminified and uncompressed bytes less costly in download time, but I'm not sure if this is the sole cause yet.

Still looking, but happy for others to take a look. Saved good/bad LHRs here: https://gist.github.com/brendankenny/7e08a31de7950894407ded2ebd26bad3

**Comment by adamraine** [comment]
> I'm not able to reproduce locally in Canary on a Mac today, but I can in a ToT snapshot, so presumably this will soon be in Canary.

This would make sense, last canary rls was two days ago: https://chromiumdash.appspot.com/releases?platform=Mac.

**Comment by brendankenny** [comment]
It appears this may be fixed in latest ToT, probably https://chromium-review.googlesource.com/c/chromium/src/+/3342209

**Comment by brendankenny** [comment]
going to call this resolved 😌
