### ISSUE TITLE
Lighthouse is auditing without finishing in Chrome Devtools

### ISSUE THREAD

**Issue by a-tonchev** [GoogleChrome/lighthouse#13512]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://demo2.shopsuy.com/

### What happened?

Lighthouse is auditing but never finishes, it just stay at one position. PageSpeed Insights seems to work and delivers report, but the browser does not deliver any report.

### What did you expect?

Lighthouse to show audit report

### What have you tried?

I tried auditing using different laptops and PCs

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

latest of chrome 96.0.4664.110

### Chrome Version

Version 96.0.4664.110 (Official Build) (64-bit)

### OS

Windows 10

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/13396
