### ISSUE TITLE
 I want to measure websites with access restrictions

### ISSUE THREAD

**Issue by nkoutaka** [GoogleChrome/lighthouse#13516]
Lighthouse, a chrome extension tool, is accessed from the machine on "googlechrome.github.io" and measured
I want to measure websites with access restrictions such as development environments
If lighthouse measures from a machine on "googlechrome.github.io", is there a fixed IP address to access from?
If there is, there is a way to remove the fixed IP address from the my access restriction.
Or is there any other way?

**Comment by connorjclark** [comment]
Use Lighthouse in DevTools. The extension is not running Lighthouse on your local machine.
