### ISSUE TITLE
Bug: Lighthouse ignores the cache policy length even if the `stale-while-revalidate` cache control header is set

### ISSUE THREAD

**Issue by okikio** [GoogleChrome/lighthouse#13514]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://bundle-nabxcjl2c-okikio-dev.vercel.app/

### What happened?

Lighthouse ignores cache policy length if the web app is a PWA which has already cached the necessary resources offline and the `stale-while-revalidate` cache control header is set. Lighthouse warns that the cache policy isn't efficient,

![image](https://user-images.githubusercontent.com/17222836/146663753-ccd3c8bb-0a5f-4b9f-8095-3aee2b5b5962.png)

> This issue was identified as a bug by @patrickhulce on a Twitter conversation I had with him, https://twitter.com/patrickhulce/status/1471973991464251396. The original URL I used when I discovered this issue was, https://bundle.js.org but due to the conversation I had with @patrickhulce I changed the headers, so, https://bundle.js.org URL is not longer a valid URL. The URL I gave you is the snapshot URL which should also suffice for debugging and replicating this issue.

### What did you expect?

What I expect is that if the resources are cached and the `stale-while-revalidate` cache control header is valid, I wouldn't get a cache length policy error on Lighthouse.

### What have you tried?

If I increase the max-age, and remove the `stale-while-revalidate`, this cache policy warning goes away.

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools

### Lighthouse Version

9.1.0

### Chrome Version

99.0.4774.0

### OS

Windows 10

**Comment by adamraine** [comment]
My first idea was to add the `stale-while-revalidate` value to `max-age` when we are computing the cache lifetime. However, I don't think this would get the audit passing on https://bundle-nabxcjl2c-okikio-dev.vercel.app/ because the total cache lifetime would be only 480+360=840s or 14 minutes (at least for the one JS file I looked at).

Additionally, `stale-while-revalidate` [is not supported on Safari or Opera](https://caniuse.com/?search=stale-while-revalidate) so we may not want to count it yet.

**Comment by patrickhulce** [comment]
Regardless of browser support `stale-while-revalidate` is a direct indication that this asset changes and should not be subject an audit asserting a 1 year TTL :)

**Comment by adamraine** [comment]
Discussed offline, stuff with `stale-while-revalidate` will be ignored by this audit.

**Comment by paulirish** [comment]
> Regardless of browser support `stale-while-revalidate` is a direct indication that this asset changes and should not be subject to an audit asserting a 1 year TTL :)

The audit is identifying assets without an "efficient cache policy", not a 1yr ttl, specifically. Given that, it seems fine to consider SWR value as part of the signal on if we flag a response.
