### ISSUE TITLE
Unexpected optional timeout value 2_000 in the fetchResource function argument

### ISSUE THREAD

**Issue by afficiona** [GoogleChrome/lighthouse#13527]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://example.com

### What happened?

I am using cypress-audit library for my Cypress test cases that uses lighthouse internally. Few of my test cases were failing and upon debugging, I saw the error as in the screenshot. It looks like the optional argument object `options` in the function `fetchResource` has the timeout value `2_000`, [line](https://github.com/GoogleChrome/lighthouse/blob/a26c8ee6a6e0a1a012c74685e1bafe00f133e857/lighthouse-core/gather/fetcher.js#L117)
![image](https://user-images.githubusercontent.com/39951703/147481365-f3bd0797-b013-4355-a42b-699780c02944.png)

I was just wondering what is the reasoning behind setting this invalid string/number value to the `timeout` property. This is definitely breaking my cypress test case and hence it is also important for me to have this fixed.

### What did you expect?

The value of timeout should have been a valid string/number representation of some number.

### How were you running Lighthouse?

node

### Lighthouse Version

8.6.0

**Comment by connorjclark** [comment]
It's not invalid. Try upgrading your Node version. Whatever version you are on is below our minimum supported version.

**Comment by afficiona** [comment]
@connorjclark thank you for responding. That makes sense. I seem to have completely missed the version issue.
