### ISSUE TITLE
Troubleshooting NO_FCP error

### ISSUE THREAD

**Issue by leonardofaria** [GoogleChrome/lighthouse#13524]
**Summary**

I have been using the Lighthouse CLI in CI and for each URL I run lighthouse 5 times and after that, I use `computeMedianRun` to get a median result: 

```js
// results is an array of lighthouse runs
median = computeMedianRun(results);
```

There are times that some runs don't have the FCP value, which causes the exception `Some runs were missing an FCP value`.

Then I started investigating which one of the runs don't have the FCP value and why:

```js
fcp: {  
  id: 'first-contentful-paint', 
  title: 'First Contentful Paint', 
  description: 'First Contentful Paint marks the time at which the first text or image is painted. [Learn more](https://web.dev/first-contentful-paint/).', 
  score: null, 
  scoreDisplayMode: 'error', 
  numericValue: undefined, 
  numericUnit: undefined, 
  displayValue: undefined, 
  explanation: undefined, 
  errorMessage: 'Required traces gatherer did not run.', 
  warnings: undefined, 
  details: undefined 
},
runtimeError: {
  code: 'NO_FCP',
  message: 'The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)'
},
runWarnings: [ 
  'The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)' 
]
```

What would be the cause of this? I am using Lighthouse 9.2.0, but noticed this behaviour happening in old versions of Lighthouse. 
I suspect that could be related to VM/connection issues in CI.

Any advice on how to fix the issue?

**Comment by paulirish** [comment]
The browser may not actually paint if it's entirely headless. (we may have some flags that can help, but I don't have them handy)

Are you always getting this error in your VM runs or only sometimes?

**Comment by leonardofaria** [comment]
It happens once or twice a day (Lighthouse is executed at least 100x a day).

The issue only happens in VM in headless mode. 
I will close the issue because it is not a big pain for us and honestly, no need to bother finding these flags :)
