### ISSUE TITLE
Syntax error in lighthouse/lighthouse-core/gather/fetcher.js 

### ISSUE THREAD

**Issue by emalysz** [GoogleChrome/lighthouse#13531]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

n/a

### What happened?

```
 .\node_modules\lighthouse\lighthouse-core\gather\fetcher.js:117
  async fetchResource(url, options = {timeout: 2_000}) {
                                               ^

SyntaxError: Invalid or unexpected token
```

Should this read 2000?

### What did you expect?

No syntax error

### What have you tried?

Reverting to an older version of lighthouse

### How were you running Lighthouse?

CLI

### Lighthouse Version

9.2.0

### Relevant log output

```shell
.\node_modules\lighthouse\lighthouse-core\gather\fetcher.js:117
  async fetchResource(url, options = {timeout: 2_000}) {
                                               ^

SyntaxError: Invalid or unexpected token
```

**Comment by brendankenny** [comment]
Numeric separators have been supported [since at least Node 12.8.1](https://node.green/#ES2021-features--numeric-separators). Lighthouse 9 requires the current Node _maintenance_ LTS, 14.15 or later.
