### ISSUE TITLE
Devtools uses literally 5 GB of RAM and crashes before generating any report

### ISSUE THREAD

**Issue by maoschanz** [GoogleChrome/lighthouse#13536]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

no.

### What happened?

I was trying to audit a website in a pre-production environment (it's protected by a htpasswd so it would be useless to share the url here)

The report generation gets stuck at around 95%, then i have to wait like 10 minutes while both the tested page and the devtools processes slowly use more and more RAM: 
![Capture d’écran de 2022-01-04 12-17-01](https://user-images.githubusercontent.com/19996113/148051607-12a26625-e675-40d3-b178-e60efa819004.png)

And then, suddenly, the devtools process gets killed: idk if it crashes, or is eliminated by Chrome, or even by the OS kernel which may not enjoy this nonsense.

And I don't even have a report, nor a visible error message.

### What did you expect?

Nor using all available RAM, not crashing, generating a pagespeed report, and showing a clear error message if it can't.

### What have you tried?

when running google-chrome from a terminal, i get this trace:

```
<--- Last few GCs --->

[1:0x14e200638000]   304608 ms: Mark-sweep 1996.4 (2068.4) -> 1989.1 (2069.2) MB, 1681.7 / 0.0 ms  (average mu = 0.143, current mu = 0.051) allocation failure scavenge might not succeed
[1:0x14e200638000]   306451 ms: Mark-sweep 1997.2 (2069.4) -> 1989.8 (2069.9) MB, 1694.3 / 0.0 ms  (average mu = 0.110, current mu = 0.080) allocation failure scavenge might not succeed


<--- JS stacktrace --->
```

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

i don't have a report so idk

### Chrome Version

96.0.4664.110

### OS

Ubuntu 20.04

### Relevant log output

```shell
<--- Last few GCs --->

[1:0x14e200638000]   304608 ms: Mark-sweep 1996.4 (2068.4) -> 1989.1 (2069.2) MB, 1681.7 / 0.0 ms  (average mu = 0.143, current mu = 0.051) allocation failure scavenge might not succeed
[1:0x14e200638000]   306451 ms: Mark-sweep 1997.2 (2069.4) -> 1989.8 (2069.9) MB, 1694.3 / 0.0 ms  (average mu = 0.110, current mu = 0.080) allocation failure scavenge might not succeed


<--- JS stacktrace --->
```

**Comment by connorjclark** [comment]
Does this happen in Chrome Canary for you too?

Might be #13396

**Comment by dvelasquez** [comment]
What is the size of the pre-production site?

I've seen this type of error occasionally when you analyse a page in dev mode. Webpack and other bundlers don't tree shake or minimise dependencies, so you end with a page that is around 200 mb in resources.

I also experienced this with a page that had 40mb of third parties and advertisement code.

**Comment by alexnj** [comment]
Closing this old ticket out. Please reopen with more info if the issue still persists.
