### ISSUE TITLE
Best-Practices

### ISSUE THREAD

**Issue by uc-aan** [GoogleChrome/lighthouse#13542]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://appbeta.ucertify.com/p/vcp5-vmware-certified-professional-on-vsphere-5.html

### What happened?

Issue type
SameSite cookie
/sdk/js?client-id=AZBpjpZzT…&components=buttons(www.paypal.com)
/tagmanager/pptm.js?id=…(www.paypal.com)
/ts?pgrp=…(t.paypal.com)
/recaptcha/api.js(www.google.com)
…api2/anchor?ar=…(www.google.com)
…api2/webworker.js?hl=en&v=VZKEDW9ws…(www.google.com)
…api2/bframe?hl=en&v=VZKEDW9ws…&k=6LfX6ZMUA…(www.google.com)

### What did you expect?

suggesting me that how can I resolve these issues or what can I do for this.

### What have you tried?

I tried to keeping CDN in that file where it is use.

### How were you running Lighthouse?

WebPageTest

### Lighthouse Version

6

### Chrome Version

97.0.4692.71

### Node Version

v14.17.4

### OS

windows, mac

**Comment by adamraine** [comment]
There should be more details for you to read in the Chrome DevTools issues panel when this audit fails. Open the issues panel  on your site and make sure the "Include third-party cookie issues" box is checked:

![image](https://user-images.githubusercontent.com/6752989/148326887-fc1516e3-ac75-4efb-bd99-a74e58f54a19.png)
