### ISSUE TITLE
Help with extraHeaders for Authenticated Page (Node.js)

### ISSUE THREAD

**Issue by dongtianqi** [GoogleChrome/lighthouse#13547]
```js
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');

(async () => {
  const chrome = await chromeLauncher.launch({chromeFlags: ['--headless']});
  const options = {logLevel: 'info', output: 'html', onlyCategories: ['performance', 'accessibility', 'best-practices', 'pwa', 'seo'], port: chrome.port, extraHeaders: {
    'Cookie': 'token=xxxxxx;kpn=xxx',
  }};
  const runnerResult = await lighthouse('https://www.mysite.com/path', options);

  // `.report` is the HTML report as a string
  const reportHtml = runnerResult.report;
  fs.writeFileSync(path.join(projectPath, 'lhreport.html'), reportHtml);

  // `.lhr` is the Lighthouse Result as a JS object
  console.log('Report is done for', runnerResult.lhr.finalUrl);
  console.log('Performance score was', runnerResult.lhr.categories.performance.score * 100);

  await chrome.kill();
})();

```

I debug the code up here, see it passed in successfully, and call this function  ，so how to set cookies successfully？

![image](https://user-images.githubusercontent.com/26708377/148480768-d030bb2c-b684-4fca-99a1-c9cbf4efbf2d.png)

**Comment by Poliyawan** [comment]
I have the same problem. After i add "Cookie" in "extraHeaders", it doesn't work as excepted.
By the way, i use the lighthouse in Node.js too.

**Comment by brendankenny** [comment]
That looks correct at first glance, but maybe I'm missing some aspect. Can you be more specific about what's not working? Is the cookie not set on the request?

Be warned that there's an issue with that, where the cookie can easily be clobbered (or clobber an existing cookie). See the note in [Pass custom request headers with Lighthouse CLI](https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md#option-3-pass-custom-request-headers-with-lighthouse-cli) and the other options on and linked from that page. You should also consider the [new user flows](https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md), which will let you more easily script interactions and page setup.
