### ISSUE TITLE
"Image elements do not have explicit width and height" - too generic

### ISSUE THREAD

**Issue by hecktarzuli** [GoogleChrome/lighthouse#13553]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://realtruck.com/c/exterior-accessories/tonneau-covers/

### What happened?

I understand adding h/w to images will help with CLS, but that's only if they don't already have explicit dimensions in CSS (auto etc..)

Here, most of the images in this report have dimensions and don't cause any CLS.

![image](https://user-images.githubusercontent.com/2112282/148802526-b593bdec-8a86-4f68-90ee-26b31a74bdce.png)

https://wpt.speedcurve.com/lighthouse.php?test=220110_XR_9f1f1aed250a05624514e59915484522&run=2

### What did you expect?

To only report on images that don't resolve to a fixed height/width.

### How were you running Lighthouse?

Other

### Lighthouse Version

8.6.0

**Comment by adamraine** [comment]
Should be fixed in the latest Lighthouse https://github.com/GoogleChrome/lighthouse/issues/12001. Most of the reported images do have explicit width and height.
