### ISSUE TITLE
Fix dbw/tap-targets smoke tests on high DPI machines

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#13557]
(the sole remaining bullet point in #12837, I believe)

`full-page-screenshot` in `yarn smoke dbw` and `tap-targets` in `yarn smoke seo-tap-targets` appear to depend on the DPR of the window the test is running in and fail when DPR>1. In both cases it would be easy to loosen the expectations to allow different sizes, but it would be good to know what changed and if it actually means the audits need fixing.

- `yarn smoke dbw` is the more obvious issue
   ```sh 
   ✘ difference at full-page-screenshot audit.details.screenshot.width
               expected: 360
                  found: 720
   ```
   (the screenshot is double the size in width and height on a 2x scaled display), but notably this test passed for about a year when the smoke test was added until ~July 2021. It's unclear what changed.

- `yarn smoke seo-tap-targets` seems like the `overlappingTargetScore` may depend on device resolution, which seems like an audit bug at first glance, but the relationship to resolution is more complicated if so.
   ```sh 
   ✘ difference at tap-targets audit.details.items[0].overlappingTargetScore
               expected: 720
                  found: 696
   ```

**Comment by paulirish** [comment]
I can't repro issues with dbw anymore (and don't see anything changing in the test expectations).

but the `seo-tap-targets` still fails on my hidpi screen.

**Comment by paulirish** [comment]
<details><summary>Here's a gif toggling between a fullpagescreenshot of the seotaptargets page captured with dpi 2 and dpi 1</summary>

![seottim](https://user-images.githubusercontent.com/39191/223558980-1ec4aace-8731-4617-aaa0-aab98443e6d9.gif)

</details>

<details><summary>And a closeup of the top of each. pixels are just slightly off... weird.</summary>

<img width="596" alt="image" src="https://user-images.githubusercontent.com/39191/223559329-77c83f1d-d226-420d-b755-555640fa3ade.png">

</details>
