### ISSUE TITLE
Lighhouse-CLI get visual change array

### ISSUE THREAD

**Issue by OskarLebuda** [GoogleChrome/lighthouse#13567]
**Summary**
Hi, I looking for lighthouse-cli information about the visual change and layout shift.
I found the `observedFirstVisualChange` and the `observedLastVisualChange` but this is only 2 metrics. I'm looking for array of those elements. 
I'm trying to create visual change like timeline with `screenshot-thumbnails` from same object.

**Comment by brendankenny** [comment]
> I found the `observedFirstVisualChange` and the `observedLastVisualChange` but this is only 2 metrics. I'm looking for array of those elements.

I believe those are the only two visual changes recorded in the Lighthouse result. `screenshot-thumbnails` also only saves 10 of the available screenshots in the trace (just in case you didn't already know that).

I don't think there's any way to do this without going back to the original trace. If you're writing a [custom audit](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit), the trace is accessible there and all the `Paint` events are available, including the bounding coordinates of where the paints occurred.

**Comment by brendankenny** [comment]
Something like this should work, assuming `lighthouse` is installed as a dependency:

```js
// all-paint-events.js

const Audit = require('lighthouse').Audit;

class AllPaintEvents extends Audit {
  static get meta() {
    return {
      id: 'all-paint-events',
      title: 'All paint events in page',
      description: 'All paint events in page',
      requiredArtifacts: ['traces'],
      scoreDisplayMode: 'notApplicable',
    };
  }

  static audit(artifacts) {
    // This gets paint/screenshot events from across the entire Chrome instance, so if
    // there are other tabs open at the same time, will need to filter to target tab.
    const trace = artifacts.traces[Audit.DEFAULT_PASS];
    const paintEvents = trace.traceEvents.filter(evt => evt.name === 'Paint');
    const screenshots = trace.traceEvents.filter(evt => evt.name === 'Screenshot');

    return {
      score: null,
      notApplicable: true,
      details: {
        type: 'debugdata',
        paintEvents,
        screenshots,
      },
    };
  }
}

module.exports = AllPaintEvents;
```

```js
// paint-config.js

module.exports = {
  extends: 'lighthouse:default',
  audits: ['all-paint-events'],
  // This hides the audit in the default "performance" category, but could go in any category.
  categories: {
    performance: {
      auditRefs: [{id: 'all-paint-events', weight: 0, group: 'hidden'}],
    },
  },
};
```

Running on the command line like
```
npx lighthouse --config-path=paint-config.js https://example.com --view
```
(or with `--output=json` or [programmatically](https://github.com/GoogleChrome/lighthouse/blob/82772f93645989c9c250c78a0ad10d55f3372beb/docs/readme.md#using-programmatically))

the results will be on `__LIGHTHOUSE_JSON__.audits['all-paint-events'].details`. e.g. for the simple `example.com` case, I get two paint events and two screenshots in that object.

Sorry there's not really a simpler way!
