### ISSUE TITLE
Lighthouse returned error: Failed document request

### ISSUE THREAD

**Issue by Blogendeon** [GoogleChrome/lighthouse#13564]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://jaccountants.co.uk

### What happened?

![image](https://user-images.githubusercontent.com/97610153/149168469-e4d67368-4f8d-47d7-827a-1583dd127346.png)

This is the error that I receive.

### What did you expect?

I expected Lighthouse to scan my page successfully.

### How were you running Lighthouse?

Other

### Lighthouse Version

9.0 I think

**Comment by adamraine** [comment]
Lighthouse runs fine for me on the URL you provided. The report viewer doesn't run Lighthouse, it just renders the report.

Can you provide specific reproduction steps to get this error?

**Comment by connorjclark** [comment]
Error is from PSI. https://googlechrome.github.io/lighthouse/viewer/?psiurl=https://jaccountants.co.uk/ Happened first time I tried.

**Comment by sharath2106** [comment]
I face a similar issue with Lighthouse. The only difference is, that I see ERR_TIMED_OUT instead of CONNECTION_FAILED. 

I could see the issue was raised earlier and then closed - https://github.com/GoogleChrome/lighthouse/issues/2686.

I'm trying to run the audit through the Chrome extension. 

Could you please take a look at this?

**Comment by connorjclark** [comment]
> The only difference is, that I see ERR_TIMED_OUT instead of CONNECTION_FAILED.

So a different issue... please open a new issue and fill out all the required information.

**Comment by alexnj** [comment]
The issue doesn't seem reproducible. Lighthouse runs fine on the URL. Closing this out, please feel free to reopen if the issue still persists.
