### ISSUE TITLE
Unable to get lab data from lighthouse: "500 error - Something went wrong"

### ISSUE THREAD

**Issue by cassidynick** [GoogleChrome/lighthouse#13580]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.skyrizi.com

### What happened?

Lighthouse is giving me an error whenever I try to run the URL linked. First tried running the site on https://pagespeed.web.dev/ earlier last week and it would be stuff "running performance analysis" indefinitely. This week, it appears to now give me the field data for the site, but still is not able to give me any lab data or recommendations. 
![PSI lab data](https://user-images.githubusercontent.com/98038499/150173880-b67b0b1d-da69-432a-bf4f-e8114fbe453a.JPG)
I also tried using the Lighthouse API within ScreamingFrog to crawl the site, and the API just gives me back an error for each URL:
![Screaming Frog Lighthouse API](https://user-images.githubusercontent.com/98038499/150174478-eaf0c868-5811-4862-b42a-4de0c85518ab.JPG)

### What did you expect?

Have been able to run page speed insights and Lighthouse on this site in the past to gather both lab and field data.

### What have you tried?

Reached out to the development team to see if there's anything they know of that might be blocking Lighthouse, which they said they do not. Tried digging through Dev Tools to see if any specific resources might be blocking Lighthouse, but have been unable to identify anything.

Issues do not come up when using other third party tools such as webpagetest.org

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools, web.dev

### Lighthouse Version

v9.2 and maybe also v9.1. Whichever one Page Speed Insights uses.

### OS

Windows

**Comment by brendankenny** [comment]
This errors in the CLI for me as well. Tab crash and eventual `PROTOCOL_TIMEOUT`.

The protocol timeout is on `Runtime.evaluate` on `window.scrollTo(0, 0)` in the [gather-runner scroll reset](https://github.com/GoogleChrome/lighthouse/blob/82772f93645989c9c250c78a0ad10d55f3372beb/lighthouse-core/gather/gather-runner.js#L341) but the actual last command before the crash is [`CSS.stopRuleUsageTracking` in `css-usage`](https://github.com/GoogleChrome/lighthouse/blob/82772f93645989c9c250c78a0ad10d55f3372beb/lighthouse-core/gather/gatherers/css-usage.js#L64).

<details><summary>verbose log</summary>

```
  LH:status Gathering: CSSUsage +1ms
  LH:listen for event =>:verbose CSS.styleSheetAdded  +0ms
  LH:listen for event =>:verbose CSS.styleSheetRemoved  +0ms
  LH:Driver:verbose DOM.enable +0ms
  LH:method => browser:verbose DOM.enable  +0ms
  LH:method <= browser OK:verbose DOM.enable {} +1ms
  LH:Driver:verbose CSS.enable +0ms
  LH:method => browser:verbose CSS.enable  +0ms

  # lots of Network.responseReceived/CSS.styleSheetAdded events

  LH:method <= browser OK:verbose CSS.enable {} +0ms
  LH:method => browser:verbose CSS.startRuleUsageTracking  +0ms
  LH:method <= browser OK:verbose CSS.startRuleUsageTracking {} +10ms
  LH:method => browser:verbose Runtime.evaluate (getComputedStyle(document.body)) +0ms
  LH:<= event:verbose Debugger.scriptParsed {"scriptId":"108","url":"","startLine":0,"startColumn":0,... +5ms
  LH:method <= browser OK:verbose Runtime.evaluate {"result":{"type":"object","value":{"0":... +1ms

  LH:method => browser:verbose CSS.stopRuleUsageTracking  +0ms
  LH:<= event:verbose Target.detachedFromTarget {"sessionId":"55CE8650C9DA02A8EE5A1EB235DCE0A7"... +241ms
  LH:<= event:verbose Inspector.targetCrashed {} +11ms

  LH:method => browser:verbose Runtime.evaluate (window.scrollTo(0, 0))  +30s
  LH:status Disconnecting from browser... +1m
  LH:status Cleaning origin data +0ms
  LH:method => browser:verbose Storage.clearDataForOrigin {"storageTypes":"file_system... +1ms
  LH:ChromeLauncher Killing Chrome instance 6861 +0ms
  LH:<= event:verbose Inspector.detached {"reason":"target_closed"} +10ms
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)
LHError: PROTOCOL_TIMEOUT
```
</details>

**Comment by cassidynick** [comment]
> This errors in the CLI for me as well. Tab crash and eventual `PROTOCOL_TIMEOUT`.
> 
> The protocol timeout is on `Runtime.evaluate` on `window.scrollTo(0, 0)` in the [gather-runner scroll reset](https://github.com/GoogleChrome/lighthouse/blob/82772f93645989c9c250c78a0ad10d55f3372beb/lighthouse-core/gather/gather-runner.js#L341) but the actual last command before the crash is [`CSS.stopRuleUsageTracking` in `css-usage`](https://github.com/GoogleChrome/lighthouse/blob/82772f93645989c9c250c78a0ad10d55f3372beb/lighthouse-core/gather/gatherers/css-usage.js#L64).
> 
> verbose log

Wanted to follow up and say as of today I am no longer experiencing this issue. Wondering if you have any idea what changed? Either way thanks for you help @brendankenny

**Comment by alexnj** [comment]
Closing this old bug report. Feel free to reopen if it's still reproducible.
