### ISSUE TITLE
Get response body into HAR file

### ISSUE THREAD

**Issue by ghisleouf** [GoogleChrome/lighthouse#13592]
Hi there !

I'm playing a little bit with HAR file generation thanks to https://github.com/sitespeedio/chrome-har and powered by Lighthouse.
It works fine with a basic implementation of both lighthouse and chrome-har libraries but I wanted to go a little deeper.

Here is an example:

```
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');
const {writeFileSync} = require('fs');
const {harFromMessages} = require('chrome-har');

const url = 'https://www.google.com/';
const filename = 'google-com';

(async () => {
  const chrome = await chromeLauncher.launch({
    chromeFlags: ['--headless']
  });
  const options = {
    port: chrome.port,
    formFactor: 'mobile',
    output: 'html'
  };

  // using chrome-har
  const result = await lighthouse(url, options);
  const reportHtml = result.report;
  const harEvents = result.artifacts.devtoolsLogs.defaultPass;

  //store report
  writeFileSync('./lighthouse-report/' + filename + '.html', reportHtml);
  // store trace log
  writeFileSync('./lighthouse-report/' + filename + '-trace.json', JSON.stringify(harEvents));

  //create HAR
  const har = harFromMessages(harEvents, {includeTextFromResponseBody: true});
  writeFileSync(filename + '.har', JSON.stringify(har));

  await chrome.kill();
})();
```

Looking a little bit deeper, I would like to include response body into generated HAR file and according to chrome-har library, it is supported : https://github.com/sitespeedio/chrome-har#support-for-response-bodies

But ... and this is my issue, as far as I understand, to integrate this data (response body) into HAR file, it should be available from trace log file, and looking into my generated one, it is not.
So, my question is quite simple, since I'm not really sure about who's responsible on what, is lighthouse able to include this data into trace log, and is there a way to add it (any option or anything else), or do I have to find another way to include it ?

Thanks a lot for your help.

Best !

**Comment by connorjclark** [comment]
Seems like `harFromMessages` [1] parses the devtools logs, not the chrome trace (EDIT: right, you're passing the correct thing here, I was just confused on naming).


EDIT: BTW, some notes on naming things (threw me off a bit so thought I'd mention it):

>   const harEvents = result.artifacts.devtoolsLogs.defaultPass;

These aren't harEvents, they are events from the DevTools Protocol.

>   writeFileSync('./lighthouse-report/' + filename + '-trace.json', JSON.stringify(harEvents));

There is a separate thing called "traces" (also an artifact that LH returns) that come from Chrome.

The library you're using says "harFrom___Messages___", which isn't the name I'd use for the devtools event logs, but you could get away with it as it doesn't conflate with anything else.

_____

Our devtools log should contain everything needed by that function to create a HAR [2]. Does it not hit any of the cases in `switch (method) {`? Did you attach a debugger and walk through what happens?


[1] https://github.com/sitespeedio/chrome-har/blob/main/index.js#L59
[2] https://github.com/GoogleChrome/lighthouse/blob/3cd1441145ca766fa4f59e0cef9161d30e50ba04/lighthouse-core/gather/driver.js#L44

**Comment by paulirish** [comment]
This becomes a feature request for chrome-har (which we don't maintain). To pull it off it'd require changes over here. But i'd prefer for sitespeed to commit to this feature before we ensure the devtoolslog has the response bodies necessary to make this happen.

So... file this upstream with chrome-har and link up connor's comment since he figured out what it'd take :)
