### ISSUE TITLE
Broken link on wordpress-specific "Unused CSS" report

### ISSUE THREAD

**Issue by cgbarros** [GoogleChrome/lighthouse#13609]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.verzdesign.com/

### What happened?

The report showed a Wordpress-specific suggestion to reduce unused CSS with a broken link to code coverage in Chrome DevTools. 
![image](https://user-images.githubusercontent.com/10048414/151793356-d147694e-9ef8-4a64-b751-3c11fa639a60.png)

### What did you expect?

Seems like these platform-specific suggestions come from the Stack Pack repository. Wordpress suggestions come from https://github.com/GoogleChrome/lighthouse-stack-packs/blob/master/packs/wordpress.js. Looking at the file, seems like the link is already updated to the correct destination (https://developer.chrome.com/docs/devtools/coverage/). Maybe Lighthouse is using an outdated version of Stack Packs right now?

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.5.0

### Chrome Version

97.0.4692.99

### OS

Mac

**Comment by adamraine** [comment]
This should be fixed in the latest version.
