### ISSUE TITLE
The score result for pwa is not the same in the browser and in the CLI

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChrome/lighthouse#13607]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://todo.koolsol.app/

### What happened?

In the browser ( chrome dev tools ), the lighthouse pwa score result is 100  
In CLI the lighthouse pwa score result is 90 .

The other scores ( perf, access,... ) are the same in both modes.

### What did you expect?

I expected the same result in CLI and in the browser.
Until last week - 2022-01-22 - the results were the same.

### What have you tried?

I tried on the urls below and until last week - 2022-01-22 -, the score result for pwa was the same in CLI and browser ( 100 )
One url still gives me a 100 on the pwa score in CLI and browser and it is blog.koolsol.app

memory.koolsol.app, sudoku.koolsol.app, minesweeper.koolsol.app

### How were you running Lighthouse?

CLI, Chrome DevTools

### Lighthouse Version

Lighthouse 9.2.0

### Chrome Version

Canary Using Chromium 100.100.4859.0 with devtools

### Node Version

14.16

### OS

Windows 10

**Comment by adamraine** [comment]
I can't reproduce this, PWA score is always 100 for me. Can you share a report where this is happening?

**Comment by hugues-koolsol** [comment]
Hello, thank you for your answer.
This week everything went well, so I think I can close the report.

FYI, I'm running a program in CLI that calculates the lighthouse score for 40 URLs every week
For some unknown reason PWA scores in CLI were very low last week but for 2 years CLI and browser results were about the same

The program I run is here: https://github.com/hugues-koolsol/lighthouse
The result is here: http://www.mypitself.com/lighthouse-score-rank-for-pwa.html

Sorry, next time I will wait 1 week before creating a report
Thank you.
