### ISSUE TITLE
Lighthouse option not showing in dev tools

### ISSUE THREAD

**Issue by pankajpj07** [GoogleChrome/lighthouse#13621]
**Summary**
Hi Team, 

I am unable to find lighthouse in dev tools and can't find the way to bring it back.

**Comment by adamraine** [comment]
Is the panel hidden? You can do ctrl + p / cmd + p and then type ">lighthouse" and click "Show Lighthouse" to open the panel if it's hidden.

**Comment by pankajpj07** [comment]
> Is the panel hidden? You can do ctrl + p / cmd + p and then type ">lighthouse" and click "Show Lighthouse" to open the panel if it's hidden.

I tried that but the lighthouse panel is still not coming

![image](https://user-images.githubusercontent.com/47389183/152399348-81fe9343-187d-444b-95c2-9d4a5eb2f76c.png)

even after clicking on the show lighthouse panel is not showing up

**Comment by adamraine** [comment]
It looks like you moved it to the bottom panel. I'm not sure if this is supposed to be possible. I would suggest filing a bug with DevTools though:

https://bugs.chromium.org/p/chromium/issues/entry?template=DevTools+issue
