### ISSUE TITLE
Why is it dark mode when I use light mode?

### ISSUE THREAD

**Issue by RixInGithub** [GoogleChrome/lighthouse#13631]
Lighthouse, when I make my site perfectly, it turns to dark mode even though I use light mode. What is wrong? Is it meant to be an easter egg? Here's the screenshot ( 0% inspect ) :

![Really?](https://user-images.githubusercontent.com/87478581/152796992-ea485a38-fe1d-4da5-bfe6-f265cbc82b2f.png)

**Comment by adamraine** [comment]
Lighthouse is supposed to do a fireworks animation if you reach all 100s. Part of that animation is forcing the report into dark mode. Unfortunately, fireworks are currently borked https://github.com/GoogleChrome/lighthouse/issues/12563 so all you get is the dark mode switch. I think this confusion might give us a reason to address that P3 bug.
