### ISSUE TITLE
[pagespeed.web.dev] Reduce height of field data section when it's empty

### ISSUE THREAD

**Issue by nhoizey** [GoogleChrome/lighthouse#13632]
When running an audit for a site with no field data, I think the field data section mentioning the lack of data should take less space in the page.

Here are the useful parts on desktop:

![image](https://user-images.githubusercontent.com/78213/142463832-b9ddda27-f2a5-44d6-860c-940e0b7396d2.png)

**Comment by exterkamp** [comment]
We hear you and are actively working on making this better.

We've made some short-term changes to alleviate this by making the field tab shorter when empty:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/6392995/160494321-247dd952-5cb2-45ab-97b7-67c3331be461.png">

More changes to come 😄

**Comment by nhoizey** [comment]
@exterkamp great, thanks! 🙏

**Comment by exterkamp** [comment]
We're rolling out our new UI changes today, which contain a lot of vertical space minimizations that should help this issue a lot. This is the new treatment for `https://exterkamp.codes` which as you can see, wastes a lot less space on the no data found CrUX section 😄

<img width="991" alt="image" src="https://user-images.githubusercontent.com/6392995/167687979-97842030-a1cd-4e46-92e8-be5c2c6b8e77.png">

Hope you like it 🎉

**Comment by nhoizey** [comment]
@exterkamp here's my new experience: https://pagespeed.web.dev/report?url=https%3A%2F%2Fnicolas-hoizey.photo%2Fgalleries%2Ftravels%2Fafrica%2Fkenya%2Fthe-iconic-acacia-tree-in-front-of-mount-kilimanjaro%2F

This is really better, thanks! 🙏

**Comment by exterkamp** [comment]
> This is really better, thanks! 🙏

Yay! I'm glad you like it!
