### ISSUE TITLE
Lighthouse Test Fails to Load Media Content, Affecting Score

### ISSUE THREAD

**Issue by jialiang** [GoogleChrome/lighthouse#13639]
**Describe the bug**
The Lighthouse test on web.dev refuses to load media content, resulting in error in the console log, resulting in lowered score.

I tested a few websites and while I am able to load their mp4 and flac files just fine, web.dev fails to load them during the Lighthouse test.

**To Reproduce**
1. Go to https://web.dev/measure/
2. Run a test on say https://videojs.github.io/autoplay-tests/plain/attr/muted.html
3. In the report, scroll down to the Best Practices section
4. It says "Browser errors were logged to the console" with the error "Failed to load resource: net::ERR_CONNECTION_FAILED" The score for Best Practices is lowered as a result.

**Expected behavior**
The Lighthouse test either load the resource without issue or suppress the error message if it refuses to load media content so as to not affect the score.

**Comment by connorjclark** [comment]
This seems like #11413, so closing.
