### ISSUE TITLE
CSP issues caused by Lighthouse

### ISSUE THREAD

**Issue by jwpgroup** [GoogleChrome/lighthouse#13630]
Hi There

This would seem to be a similar issue to 12525 and 11862, although, in the later case, it has nothing to do with tap targets.

Run this page... https://www.jwp.co.uk/testimonials.html at web.dev and it reports as follows...

**Issues were logged in the Issues panel in Chrome Devtools**
Issues logged to the `Issues` panel in Chrome Devtools indicate unresolved problems. They can come from network request failures, insufficient security controls, and other browser concerns. Open up the Issues panel in Chrome DevTools for more details on each issue.
**Issue type**  Content security policy

In Chrome Dev Tools it says...
"No issues detected so far"

As per the other cases, it's pulling down the score 'Best Practices' score.

Seems like a bug to me.  Thoughts?

**Comment by adamraine** [comment]
Yeah this looks like a bug. Something Lighthouse is doing is being blocked by the CSP. This is related to #11862.
