### ISSUE TITLE
Lighthouse score calculator links don't work correctly

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/lighthouse#13633]
1. Go to https://pagespeed.web.dev/report?url=https%3A%2F%2Fhellosehat.com%2Fparenting%2Fanak-6-sampai-9-tahun%2Fperkembangan-anak%2Fmenyuapi-anak%2F
1. Note the score:

   <img width="447" alt="Screen Shot 2021-11-19 at 12 06 29" src="https://user-images.githubusercontent.com/145676/142612797-ab9aada3-ba21-49d0-8b41-99a4d0c1ef5c.png">
1. Click through to https://googlechrome.github.io/lighthouse/scorecalc/#FCP=1229&TTI=3246&SI=7565&TBT=121&LCP=2160&CLS=0&FMP=1229&device=mobile&version=9.0.0
1. Note how the score calculator is wrong:

   <img width="1063" alt="Screen Shot 2021-11-19 at 12 08 19" src="https://user-images.githubusercontent.com/145676/142612925-cf8d64de-de32-43a3-9c7f-d925cd9b024f.png">

**Comment by adamraine** [comment]
Should be fixed now https://github.com/GoogleChrome/lighthouse/issues/13397
