### ISSUE TITLE
Lighthouse CLI Configuration --emulatedUserAgent

### ISSUE THREAD

**Issue by umang2022** [GoogleChrome/lighthouse#13641]
Hello Team,

I am executing some runs on Lighthouse CLI.  I am providing different  User Agents combinations to mimic different browser, but I am not sure if Lighthouse can really mimic Firefox, Safari browsers even though I am providing different user agents field.
Because I have not seen much variation is Performance category scores though.

PFA the --emulated User agents combinations for different browser

For Chrome: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
For Firefox: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0
For Safari: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15

Kindly, provide me your expert view on "Whether changing user agents does mimic browser behavior?"

**Comment by connorjclark** [comment]
It's an _emulated_ user agent. Setting it only changes how Chrome announces itself to servers with the User-Agent request header. There is no attempt to be like the browser described in the UA string.
