### ISSUE TITLE
Full page screenshot can change page content

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#13642]
[Example report (Legacy navigation)](https://googlechrome.github.io/lighthouse/viewer/?gist=d9659c8f1f72b06e4a467d64a0373380)

In the example above, the page shows different content in the full page screenshot than it does in the timeline frames. The page detects a different viewport width and changes the content (e.g. side margins).

The FPS gatherer should keep the content width fixed so it better reflects the content Lighthouse audited.

<details>
<summary>Images</summary>

| Final Timeline | FPS |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/6752989/153055718-7a4b043c-5405-4fa9-9240-ff06b8df1b0a.png" width="300px"> | <img src="https://user-images.githubusercontent.com/6752989/153055689-09d6f91e-3349-4606-842b-fbbdd29043cb.png" width="300px"> |

</details>

**Comment by paulirish** [comment]
oh that's a good one... @adamraine you still have the CLI invocation you used to capture this?

**Comment by adamraine** [comment]
`lighthouse "https://www.mikescerealshack.co/search?q=call+of+duty" --view`
