### ISSUE TITLE
Lighthouse Report want PNG Cache - BUT .PNG SHOULD NOT BE DONE WITH CACHE

### ISSUE THREAD

**Issue by ggmggm** [GoogleChrome/lighthouse#13640]
Lighthouse Report
https://googlechrome.github.io/lighthouse/viewer/?psiurl=https://www.juwelenmarkt.de

Serve static content with an efficient cache policy 9 resources found

/juwelier.png(www.juwelenmarkt.de) | None | 56 KiB
/b-diamant-schmuck.png(www.juwelenmarkt.de) | None | 5 KiB
/b-armband-uhren.png(www.juwelenmarkt.de) | None | 5 KiB
/0-alle-gelegenheiten.png(www.juwelenmarkt.de) | None | 4 KiB
/paypal.png(www.juwelenmarkt.de) | None | 3 KiB
/b-diamanten-brillanten.png(www.juwelenmarkt.de) | None | 3 KiB
/down.png(www.juwelenmarkt.de) | None | 2 KiB
/top.png(www.juwelenmarkt.de) | None | 2 KiB
/juwelier-home.png(www.juwelenmarkt.de)

According to various Internet comments, .PNG SHOULD NOT BE DONE WITH CACHE
For example:
https://www.dareboost.com/
You should not gzip/deflate PNG images!

Is Lighthouse Report wrong ?

GUNAR

**Comment by adamraine** [comment]
@ggmggm I see where https://www.dareboost.com/ says you shouldn't gzip png images, but I don't see anything suggesting you shouldn't cache png images. I think Lighthouse is correct on this matter.
