### ISSUE TITLE
"Links are not crawlable" - any way to say "it's ok" ?

### ISSUE THREAD

**Issue by nunoperalta** [GoogleChrome/lighthouse#13665]
All my route links have proper `href` attributes.

However, the site also has loads of "action" `<a>` tags that only have an `onclick` attribute, but no `href`.
None of those action tags are for navigation, but Lighthouse is catching every single of them into "Links are not crawlable".

![image](https://user-images.githubusercontent.com/487079/153992625-653d1201-5cb4-4fe2-8bee-f0f79ffb27ff.png)

I'm afraid this might be causing harm to the SEO score of my website, unnecessarily.

Is there any way to "bypass" this, and tell Lighthouse that "these are fine"?
Or... am I not following the best practice here somehow?

Thank you.

**Comment by benschwarz** [comment]
@nunoperalta if there's no `href` attribute it should be a `<button>` rather than an `<a>`.

**Comment by adamraine** [comment]
Ya from the [docs](https://developers.google.com/search/docs/advanced/guidelines/links-crawlable?visit_id=637805374573413458-4244430732&rd=1): `<a onclick="...">` tags are not crawlable. This is WAI, a button would probably be better in this situation.

**Comment by nunoperalta** [comment]
@benschwarz @adamraine Thanks. I did look into that documentation page, but it didn't mention what the alternative would be.
I'll look into `<button>` then, but I didn't know they could look like links.
