### ISSUE TITLE
render blocking file doesn't actually exist / doesn't even look like a file

### ISSUE THREAD

**Issue by hikeislife** [GoogleChrome/lighthouse#13664]
lighthouse is telling me that I should reduce render blocking resources, but when I look at what's listed, one is my css file ~500k, and the other one just says: 

> a[href^="http://www.onclickmega.com/jump/next.php?"] { display: none !important; } ...

15k

and before that 

> [href*="/afu.php"] { display: none !important; } ...

again 15k

> div[id^="gtm-ad-"] { display: none !important; } ...

none of these look like files, but I don't have "afu.php" (it's node app, no php whatsoever) or "onclickmega.com" anywhere in my page/code, so I have no idea where it's coming from. and why does it change from one lighthouse run to another. it's always the same size, and display none, but rest of it...

chorme has no add-on whatsoever, it was installed like a week ago, and I don't really use it, so it's clear

**Comment by adamraine** [comment]
Can you provide a URL where this is happening?

**Comment by Smoqqqq** [comment]
Same problem (visible at https://www.osteopathemassy.fr/) with "afu.php" as well as "timesofindia" ??
![image](https://user-images.githubusercontent.com/61330908/159459656-7a3aa6db-5485-4be7-9bac-6d501c98e149.png)
double checked and there is no link to any of these in the code (Website built using Jekyll so no PHP neither)

Tested on lighthouse chrome extension and https://pagespeed.web.dev/, only happens on the extension.

**Comment by adamraine** [comment]
@Smoqqqq are you able to share a report. I can't reproduce on the chrome extension.

**Comment by connorjclark** [comment]
These look like ad blocker scripts?

What version extension are you using (am wondering if it is old enough that it is running chrome locally instead of via PSI API)

**Comment by Smoqqqq** [comment]
@connorjclark Must have been that, running in icognito or on another browser removed it !

Not sure what is "version extension", running chrome 99.0.4844.82, and I don't even have the lighthouse extension installed (not even sure why)

Thanks anyway for your quick answers Connor & Adam :)

**Comment by connorjclark** [comment]
Great, glad to hear it!

Did you happen to see this warning:

> Chrome extensions negatively affected this page's load performance. [...]

at the top of the report?

**Comment by Smoqqqq** [comment]
Yes, it happens frequently. Probably my ad blocker !
