### ISSUE TITLE
Issue in generating Lighthouse Report - 

### ISSUE THREAD

**Issue by AVenkat2022** [GoogleChrome/lighthouse#13675]
Hi Team,

We did try to generate the lighthouse report for one of the application using Chrome Browser and observed following error. But able to generate the report for other application not for one of the key application. Any thoughts here?

**There were issues affecting this run of Lighthouse:

Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404)**

**Comment by dbltoe** [comment]
I am having the same problem still with getting a lighthouse report for brothersandnoblesDOTcom but ONLY with the home page.

Any other page works just fine.  A check with deadlinkchecker.com shows that the main URL is throwing the 404.  In other words, it's telling me that https://brothersandnoblesDOTcom cannot be found.

Both .htaccess and cPanel are set to force any URL to https://brothersandnoblesDOTcom.

There are no hidden misspellings in the page source for that main page.

Any thoughts?

**Comment by adamraine** [comment]
@dbltoe this issue is over a year old, please file a separate issue in the future.

I went to https://brothersandnobles.com/ and the response code was 404 even though the page loaded content. Please ensure your server is delivering the correct status code.
