### ISSUE TITLE
Should disabling audits still have those audits affect the total score

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/lighthouse#13670]
**Feature request summary**

I run Lighthouse on my website as part of CI. I've disabled some audits which are either too variable, or outside of my control.

For example youtube.com still uses cookies without the SameSite attribute set, so embedding a youtube video on a page fails this audit, and then caps the best Practice Score at 0.92.

I therefore disable that audit, but I still need to **also** reduce the expected Best Practices score to 0.92 or I still flag a failure in CI. Should it just get a "pass" for that part of the score since we've requested that audit to be disabled?

**What is the motivation or use case for changing this?**

If an audit is disabled, it's confusing to still have it enabled in some cases (the total score).

**How is this beneficial to Lighthouse?**

Less confusing/effort to those who disable audits.

**Comment by adamraine** [comment]
> I therefore disable that audit, but I still need to also reduce the expected Best Practices score to 0.92 or I still flag a failure in CI. Should it just get a "pass" for that part of the score since we've requested that audit to be disabled?

I'm not sure I follow what you're saying here. Are you reducing the Best Practices score manually somehow?

Listing an audit in the `skipAudits` config option should prevent it from impacting the category score. For instance, https://example.com scores a 92 for accessibility but scores 100 if `html-has-lang` is disabled using `skipAudits`. Are you saying that skipped audits *should* impact the overall category score?

**Comment by tunetheweb** [comment]
Ohh using just the command line works!:

```
lighthouse https://almanac.httparchive.org/en/2019/mobile-web --skip-audits=inspector-issues --view
```

I was actually using the [Treosh lighthouse-ci-action](https://github.com/treosh/lighthouse-ci-action) and I looking at it closer [I was just excluding it from assertions](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/.github/lighthouse/lighthouse-config-prod.json), not from the actual audits being run. Will configure that better.

Apologies for wasting your time!
