### ISSUE TITLE
FR in DevTools doesnt carry same configuration

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#13680]
It looks like `logLevel`, `channel` and `locale` are not being set when using our FR runners.
https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/entrypoints/lighthouse_worker/LighthouseService.ts;l=109-111;drc=b02aa952522201e4cd63f265c54f1beac872d043

This was apparent because in DT-on-DT we typically have our standard logging calling out all gatherers/audits but when using FR navigation there's nothing.

While that's not userfacing the locale bit is. And channel just affects our analytics. 

At first view it looks awkward to deal with logLevel as its not in sharedflagsettings. adam said: 

> Ya we should probably add a logLevel thing to configContext
Cuz there is a bunch of stuff on legacy flags we don't want
LIke port and hostname
configContext already has settingsOverrides

**Comment by adamraine** [comment]
Side-note: `configContext` is a kinda weird name. I typically think of it as the "step options" so maybe we could rename to something like `stepFlags` or `frFlags`?

**Comment by adamraine** [comment]
Next step is to fix this after DT roll

**Comment by adamraine** [comment]
This is done:
https://chromiumdash.appspot.com/commit/e89a9dee3a29edac9ffcf6baa51b2cd199f7d8f2
