### ISSUE TITLE
Dependency lodash.set has an unpatched CVE

### ISSUE THREAD

**Issue by mhassan1** [GoogleChrome/lighthouse#13694]
The [lodash.set](https://www.npmjs.com/package/lodash.set) package has an open CVE: https://security.snyk.io/vuln/SNYK-JS-LODASHSET-1320032. The maintainer of Lodash will not release a patched version, and he considers the per-method packages [soft-deprecated](https://github.com/lodash/lodash/issues/3793#issuecomment-389774153).

**Comment by mhassan1** [comment]
Thanks, @adamraine. When do we think this will get an NPM release?

**Comment by adamraine** [comment]
Probably this week
