### ISSUE TITLE
Not seeing <meta name="viewport">

### ISSUE THREAD

**Issue by charviis** [GoogleChrome/lighthouse#13691]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://glitch.com/edit/#!/second-selective-wok

### What happened?

I´ve had a project to do website and use Lighthouse, I was told I should get as much points as possible. But as I kept trying I noticed that there is still the same problem with <meta name="viewport">. I tried to put it everywhere and it kept saying it. 

### What did you expect?

Check the code detection of code and flagging.

### What have you tried?

Putting the <meta name="viewport"> literally everywhere. 

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

Generated by Lighthouse 9.1.0

### Chrome Version

Chromium 98.0.4758.102 with devtools

**Comment by connorjclark** [comment]
It goes in the header, not a head element.
