### ISSUE TITLE
Start_url not in ServiceWorker's scope for lighthouse PWA audit "localhost"

### ISSUE THREAD

**Issue by RichardMaher** [GoogleChrome/lighthouse#13700]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://richardmaher.github.io/Brotkrumen/TravelManager.html

### What happened?

Please see https://stackoverflow.com/questions/71232165/start-url-not-in-serviceworkers-scope-for-lighthouse-pwa-audit-localhost for complete details.

TL;DR Audit fails on Windows IIS but is passed on GitHub pages

### What did you expect?

With the given scope and functioning SW configuration PWA lighthouse audit to be the same on IIS as GitHub pages.

### What have you tried?

The audit is the only thing that fails. All PWA functionality (bar installable) works.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.3.0

### Chrome Version

 Version 94.0.4606.61

### OS

Windows 10

### Relevant log output

```shell
Web app manifest or service worker do not meet the installability requirements 1 reason

Failure reason
No matching service worker detected. You may need to reload the page, or check that the scope of the service worker for the current page encloses the scope and start URL from the manifest.
PWA Optimized
Does not register a service worker that controls page and start_urlThis page is controlled by a service worker, however the `start_url` (http://localhost:3333/Brotkrumen/TravelManager.html) is not in the service worker's scope (http://localhost:3333/brotkrumen/)
Redirects HTTP traffic to HTTPS
Configured for a custom splash screen
Sets a theme color for the address bar.
Content is sized correctly for the viewport
Has a <meta name="viewport"> tag with width or initial-scale
Provides a valid apple-touch-icon
Manifest has a maskable icon
```

**Comment by adamraine** [comment]
This is flaky because the service worker is registered too late for Lighthouse to detect sometimes. The audit did pass once when the SW was registered fast enough.

I'm going to merge this into https://github.com/GoogleChrome/lighthouse/issues/13138.

**Comment by RichardMaher** [comment]
Hi @adamraine, I believe you are mistaken in you diagnosis/triage.

Please note: -

1) The exact same code audits when hosted from GitHub pages but not IIS
    a) https://richardmaher.github.io/Brotkrumen/TravelManager.html
    b) Clone from Github to sub-folder /Brotkrumen/ served by IIS
2) Depending on my scope etc I can get the install event but the serviceworker READY is never invoked.
3) please read the error message from Lighthouse

Please re-open

**Comment by adamraine** [comment]
Ah yup. FWIW the GH site *is* also exhibiting the behavior tracked in #13138.

> Does not register a service worker that controls page and start_urlThis page is controlled by a service worker, however the `start_url` (http://localhost:3333/Brotkrumen/TravelManager.html) is not in the service worker's scope (http://localhost:3333/brotkrumen/)

"Brotkrumen" is capitalized on the `start_url` but it's all lowercase on the SW scope. I think it's safe to assume that case matters here.

**Comment by RichardMaher** [comment]
@adamraine 

[FWIW the GH site is also exhibiting the behavior tracked in https://github.com/GoogleChrome/lighthouse/issues/13138.]

It would be worth a lot if it were true but, unless it is a Chrome version issue, you are **_wrong_**.

Please see this in the console log "-

*****Have install event**

This is triggered by: -

        window.addEventListener('beforeinstallprompt', function(e) {
            e.preventDefault();
          // Stash the event so it can be triggered later.
            console.log("***Have install event");
        });

This is **_MY_** lighthouse audit: -

[Progressive Web App](devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@418b78f5838ed0b1c69bb4e51ea0252171854915/&can_dock=true&dockSide=undocked#pwa)
These checks validate the aspects of a Progressive Web App. [Learn more](https://developers.google.com/web/progressive-web-apps/checklist?utm_source=lighthouse&utm_medium=devtools).
Installable
Web app manifest and service worker meet the installability requirements
PWA Optimized
Registers a service worker that controls page and start_url
Redirects HTTP traffic to HTTPS
Configured for a custom splash screen
Sets a theme color for the address bar.
Content is sized correctly for the viewport
Has a <meta name="viewport"> tag with width or initial-scale
Provides a valid apple-touch-icon
Manifest has a maskable icon

Not sure what you are seeing?

["Brotkrumen" is capitalized on the start_url but it's all lowercase on the SW scope. I think it's safe to assume that case matters here.]

 Please see where I specify the sope as "./" where do you suggest the "brotkrumen" is coming from. By the way I have experimented with all combos of scope and path I can think of and still no joy. If you think you have the answer please say "change this to this and it will work". Once again it works on case-sensitive GitHub pages but not tolerant IIS. 

Once again, I submit this bug warrants re-opening.

**Comment by connorjclark** [comment]
start_url/scope looks fine to me. scope is just `./` but that's fine because it resolves to the same location as the start_url.

I suspect the issue is that locally on your windows machine, the folder you are serving your web application from is named `brotkrumen` (lowercase) but your start url has a different case. It could be that it works on github pages because their git checkout has different casing than your local window copy (git can get really annoying about casing on windows and it is possible to get in a bad state re: casing across git checkouts/OSes).

> Please see where I specify the sope as "./" where do you suggest the "brotkrumen" is coming from.

It's in the images from stackoverflow that you shared.

I'm gonna lock this because 1) this seems to clearly be related to filesystem case sensitivity/some subtle local server setup (redirects messing with casing?) and not a Lighthouse bug, but more importantly 2) you're being pretty rude and this isn't a general support forum.
