### ISSUE TITLE
<input> element causes very bad (1+) CLS score 

### ISSUE THREAD

**Issue by danielkolbespecial** [GoogleChrome/lighthouse#13709]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://gdch.app/article/the-myth-of-cancel-culture-in-chemistry-and-science

### What happened?

We had no CLS issues until February 8th 2022. On that date, CLS errors popped up in the Search console.

After some days of very detailed investigation, we found out that the CLS score seems to have problems determining layout shifts. We have a single input element in our hamburger menu which doesn't cause any layout shifts on real devices at all. Even setting it to display:none !important; didn't change the CLS score. Also moving the <input> to other containers didn't do the trick. As soon as we have an input anywhere on the page, the CLS score bumps to 1+.

As soon as we remove the input, everything's back to normal (CLS = 0 or ~0.1). As an input element with display:none !important; really doesn't cause any layout shifts, we're out of ideas because this really looks like a bug with the report.

### What did you expect?

CLS shouldn't be affected by an input with display:none; . CLS should be calculated correctly based on layout shifts.

### How were you running Lighthouse?

Chrome DevTools, web.dev

### Lighthouse Version

9.4.0

**Comment by danielkolbespecial** [comment]
I'm sorry, that URL was a bad example, this one shows the issue better: https://gdch.app/article/the-myth-of-cancel-culture-in-chemistry-and-science

**Comment by adamraine** [comment]
I can't reproduce on that page either, CLS is around 0.2. I haven't seen a CLS of 1+ yet.

Can you please provide an example report and performance trace.
