### ISSUE TITLE
Truncated filenames unhelpful

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/lighthouse#1372]
Proposed change: Don't truncate filenames.

Filenames and extensions are cutoff for files with long pathnames. Losing this information (particularly the filetype), makes it hard to quickly understand what a resource is being used for and whether it needs to be optimized.

This is particularly conspicuous when using Lighthouse with websites that use fingerprinting in their filenames.

![image](https://cloud.githubusercontent.com/assets/6076184/21583567/1c61e372-d03c-11e6-8943-75036dc5de54.png)

**Comment by ebidel** [comment]
The UI needs some work here!

What if we still had an overflow and made the URLs even shorter (so the rest of those lines fit), we could put a `title` attribute on the URLs. When users hover, they'd see the full URL.

**Comment by paulirish** [comment]
We use this eliding for long filenames [in devtools](https://github.com/ChromeDevTools/devtools-frontend/blob/13e562f5b3b918e8a90c068deadf3d2ac6a77458/front_end/components/Linkifier.js#L307): 

```js
urlstring.replace(/([a-f0-9]{7})[a-f0-9]{13}[a-f0-9]*/g, '$1\u2026')
```

For hashes it preserves the first 7 characters of the hash and elides the rest.
I prefer that, as keeping the entire full thing is pretty rough on the eyes.

I tested that on this indiegogo page and it looks to work okay.. you get to see the filename extension clearly. Hows that sound?

**Comment by ebidel** [comment]
That works for me. @khempenius wdyt? 

Should we also do the `title` attr to reveal the entire URL as a tooltip?

**Comment by paulirish** [comment]
> Should we also do the title attr to reveal the entire URL as a tooltip?

ya fo sho

**Comment by khempenius** [comment]
@ebidel That sounds great.
