### ISSUE TITLE
PageSpeed / Lighthouse reports lazy loaded images as not lazy loaded

### ISSUE THREAD

**Issue by tomasts248** [GoogleChrome/lighthouse#13742]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.otzerling.com/

### What happened?

Images of a popup are being detected as not lazy loaded, please take a look here:

![brave2](https://user-images.githubusercontent.com/32283036/158222521-b5cb2082-6124-4136-8bfc-00cf8372051c.jpg)

Further info from Wordpress forum thread regarding explanation of the image being lazy loaded:
https://wordpress.org/support/topic/enable-lazy-load-for-popup-image/

### What did you expect?

No complains from Pagespeed

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

9.3

**Comment by adamraine** [comment]
I think we can merge this into https://github.com/GoogleChrome/lighthouse/issues/13338. Addressing that issue should prevent the stylesheet URL from showing up as an image in this audit.

The other image is fetched during the page load, so the audit is correctly flagging it.

**Comment by tomasts248** [comment]
> think we can merge this into https://github.com/GoogleChrome/lighthouse/issues/13338.

Oh my.. sorry I totally forgot I already posted this issue.

> The other image is fetched during the page load, so the audit is correctly flagging it.

Yes only the 64.4 kb is lazy loaded.

Thank you.
