### ISSUE TITLE
Desktop Metrics very different from Lighthouse Chrome Dev Tools

### ISSUE THREAD

**Issue by SusanaSEO** [GoogleChrome/lighthouse#13745]
I'm trying to use Lighthouse CLI to automate the extraction of certain performance metrics, and mobile seems quite similar to the metrics appearing in Chrome Dev Tools, both using similate or devtools throttling. On the contrary, desktop appears really over.

Metrics mobile Lighthouse using Chrome Dev Tools
LCP: 2.3s
TBT: 0ms
CLS: 0.001

Metrics mobile Lighthouse CLI simulate throttling
LCP: 7.6s
TBT: 1,273ms
CLS: 0.146

I wonder if I'm missing out anything. Many thanks!!

**Example config file for desktop simulate throttling**
```
`const constants = require('./constants.js');


module.exports = {
    extends: 'lighthouse:default',
    settings: {
      output: 'json',
      locale: 'en-GB',
      maxWaitForLoad: 35 * 1000, 
      maxWaitForFcp: 35 * 1000,
      formFactor: 'desktop', 
      onlyAudits: [
          'largest-contentful-paint', 
          'total-blocking-time',   
          'cumulative-layout-shift', 
          'first-contentful-paint', 
          'speed-index', 
          'interactive', 
      ],
      /** Throttlng */
      throttlingMethod: 'simulate', 
      requestLatencyMs: 0, 
      downloadThroughputKbps: 0, 
      uploadThroughputKbps: 0,

      /** Screen Emulation */
      screenEmulation: constants.screenEmulationMetrics.desktop,

      /** User agents */
      emulatedUserAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4420.0 Safari/537.36 Chrome-Lighthouse',
      userAgent: 'qa auto testing',
  },
};`
```

**Comment by adamraine** [comment]
I'm not sure I understand. Was the config you posted used to get either of the metric results?

Please take a look at our variability doc, it covers most issues like this: https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md.

**Comment by SusanaSEO** [comment]
Thanks adamraine!!

**Metrics mobile Lighthouse using Chrome Dev Tools** > those metrics were extracted by using the browser, inspect and then lighthouse inside chrome dev tools
LCP: 2.3s
TBT: 0ms
CLS: 0.001

**Metrics mobile Lighthouse CLI simulate throttling** > those metrics were extracted by using the config shown on previous message. When using devtools instead of simulate throttling the result is very similar.
LCP: 7.6s
TBT: 1,273ms
CLS: 0.146


I have checked the documentation you have shared with me. The two most popular approaches are using those two type of throttling, but both get a very different result than when using the browser.

Then maybe next steps are??:

**1. ensure is running on adequate hardware and it is isolated from other factors**
At the moment, it is running in Jenkins, so maybe needs to ask if it is possible to isolate it

**2. try packet level throttling**
https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md informs that webpagetest uses this type of throttling
is there ay documentation on how to use this type of throttling with lighthouse cli?


Thanks again!!

**Comment by SusanaSEO** [comment]
When using no throttling the measure gets more close to LCP is lower than in the browser.

**Lighthouse CLI with --throttling-method=provided**
LCP: 1.136s
TBT: 183.35ms
CLS: 0.21

But varies a lot in each run, more than when adding the throttling.
Any other suggestions?

**Comment by adamraine** [comment]
Hmm it looks like you may not be setting up your config properly, the throttling settings should go under `settings.throttling` but they are currently just under `settings`.

Change
```
/** Throttlng */
throttlingMethod: 'simulate', 
requestLatencyMs: 0, 
downloadThroughputKbps: 0, 
uploadThroughputKbps: 0,
```
to
```
/** Throttlng */
throttlingMethod: 'simulate',
throttling: {
  requestLatencyMs: 0, 
  downloadThroughputKbps: 0, 
  uploadThroughputKbps: 0,
}
```

Our config doc might help: https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md#settings-objectundefined

**Comment by SusanaSEO** [comment]
Thanks, now it seems more similar to the results on the browser, when using simulate

**Desktop simulate throttling**
LCP = 1.6s
TBT = 2 ms
CLS = 0.15


I have a couple of more questions.

1. I was trying to add the screenEmulation metrics on the configuration so I don't need the constants.js file. But when I try to use it without with the following code I get an error message.


**Code**
```
module.exports = {
  extends: 'lighthouse:default', 
  settings: {
    output: 'json',
    locale: 'en-GB',
    maxWaitForLoad: 35 * 1000, 
    maxWaitForFcp: 35 * 1000,
    formFactor: 'desktop', 
    onlyAudits: [
        'largest-contentful-paint', 
        'total-blocking-time',  
        'cumulative-layout-shift', 
        'first-contentful-paint', 
        'speed-index',
        'interactive', 
    ],
    /** Throttlng */
    throttlingMethod: 'simulate',
    // Using a "broadband" connection type
    // Corresponds to "Dense 4G 25th percentile" in https://docs.google.com/document/d/1Ft1Bnq9-t4jK5egLSOc28IL4TvR-Tt0se_1faTA4KTY/edit#heading=h.bb7nfy2x9e5v
    throttling: {
        requestLatencyMs: 0,  
        downloadThroughputKbps: 0,
        uploadThroughputKbps: 0,
        cpuSlowdownMultiplier: 1, 
    },
    /** Screen Emulation */
    screenEmulation: {
      mobile: true,
      width: 360,
      height: 640,
      // Moto G4 is really 3, but a higher value here works against
      // our perf recommendations.
      // https://github.com/GoogleChrome/lighthouse/issues/10741#issuecomment-626903508
      deviceScaleFactor: 2.625,
      disabled: false,
    },
    /** User agents */
    emulatedUserAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4420.0 Safari/537.36 Chrome-Lighthouse',
    userAgent: 'qa auto testing',
  },
};
```

**Error message:**
 "Runtime error encountered: Screen emulation mobile setting (true) does not match formFactor setting (desktop). See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md"


The code in the constants.js is the following. The only difference I see is the @type, which then redirects to the file lib.es5.d.ts.

Are the contants.js and this file needed? or can you just use the config file?
If they are not needed, how can I overcome this issue so I don't need to add them?

```
/**
 * @type {Required<LH.SharedFlagsSettings['screenEmulation']>}
 */
const MOTOG4_EMULATION_METRICS = {
  mobile: true,
  width: 360,
  height: 640,
  // Moto G4 is really 3, but a higher value here works against
  // our perf recommendations.
  // https://github.com/GoogleChrome/lighthouse/issues/10741#issuecomment-626903508
  deviceScaleFactor: 2.625,
  disabled: false,
};
```




2. In relation to the locale I have not found much information. Are those following the same rules as the hreflang?

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2


Many thanks!!!

**Comment by adamraine** [comment]
> I was trying to add the screenEmulation metrics on the configuration so I don't need the constants.js file. But when I try to use it without with the following code I get an error message.
> ...
> > "Runtime error encountered: Screen emulation mobile setting (true) does not match formFactor setting (desktop). See [https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md](https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md?rgh-link-date=2022-03-18T15%3A14%3A42Z)"

`formFactor` is not a setting on `screenEmulation`, if you look at your config settings you have `formFactor: 'desktop'` but on `screenEmulation` you have `mobile: true`. These settings are in conflict so Lighthouse throws an error. You should change `formFactor: 'desktop'` to `formFactor: 'mobile'`.

> In relation to the locale I have not found much information. Are those following the same rules as the hreflang?

Our full list of locales is in the [settings typedef](https://github.com/GoogleChrome/lighthouse/blob/575e29b8b6634bfb280bc820efea6795f3dd9017/types/externs.d.ts#L137)

**Comment by SusanaSEO** [comment]
Many thanks!!


**1. Where ca I find a more deeper explanation about the locale??**
Which is the purpose of this field?
export type Locale = 'en-US'|'en'|'en-AU'|'en-GB'|'en-IE'|'en-SG'|'en-ZA'|'en-IN'|'ar-XB'|'ar'|'bg'|'bs'|'ca'|'cs'|'da'|'de'|'el'|'en-XA'|'en-XL'|'es'|'es-419'|'es-AR'|'es-BO'|'es-BR'|'es-BZ'|'es-CL'|'es-CO'|'es-CR'|'es-CU'|'es-DO'|'es-EC'|'es-GT'|'es-HN'|'es-MX'|'es-NI'|'es-PA'|'es-PE'|'es-PR'|'es-PY'|'es-SV'|'es-US'|'es-UY'|'es-VE'|'fi'|'fil'|'fr'|'he'|'hi'|'hr'|'hu'|'gsw'|'id'|'in'|'it'|'iw'|'ja'|'ko'|'ln'|'lt'|'lv'|'mo'|'nl'|'nb'|'no'|'pl'|'pt'|'pt-PT'|'ro'|'ru'|'sk'|'sl'|'sr'|'sr-Latn'|'sv'|'ta'|'te'|'th'|'tl'|'tr'|'uk'|'vi'|'zh'|'zh-HK'|'zh-TW';


**2. Thanks the desktop screen emulation did work.**

**Comment by adamraine** [comment]
> Where ca I find a more deeper explanation about the locale?? Which is the purpose of this field?

It's a list of our supported locales, the [wikipedia link](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) you provided can be of some help here. We don't specifically support Canadian english (`en-CA`) / french (`fr-CA`), but you can use `en`/`en-US` for english or `fr` for french.

**Comment by SusanaSEO** [comment]
Many thanks Adam!!

Couple of more questions:


**1. Locale**
The locale in lighthouse, can affect the result?? Is it replicating certain conditions on the browser on certain location? Or which it is the purpose of setting up the locale?

**2. Mobile**
Now the metrics seems pretty similar on desktop but on mobile some metrics appear to be better on simulate and some on devtools.


Example:
**Mobile simulate** cpuSlowdownMultiplier: 0
LCP: 6.25s
TBT: **1,717ms**
CLS: 0.37

**Mobile devtools** cpuSlowdownMultiplier: 4
LCP: **7.73s**
TBT: 2,231ms
CLS: **0.25**

**Mobile Lighthouse on chrome browser**
LCP: 10.1s
TBT: 870ms
CLS: 0.19

**Mobile devtools** cpuSlowdownMultiplier: 3 round 1
LCP: **7.75s**
TBT: **1,855ms**
CLS: **0.25**

**Mobile devtools** cpuSlowdownMultiplier: 3 round 2
LCP: **7.33s**
TBT: **1,070ms**
CLS: **0.25**

By changing the cpuSlowdownMultiplier to 3 seems to be more similar. I guess this is a good approach or any downside to take into consideration? Thanks!!

**Comment by SusanaSEO** [comment]
One more question.

On the browser the chrome and lighthouse versions are different than the ones in the cloud. If now the results are similar with this change of settings can I forget about it? It seems that the browser has older versions.

**Browser**
**Chrome:** Chromium 99.0.4844.51
**Lighthouse:** Lighthouse 9.2.0

**Cloud**
**Chrome:** Google Chrome 92.0.4515.159
**Lighthouse:** Lighthouse 9.5.0

**Comment by tleish** [comment]
Can I get some simple suggestions on how to get similar metrics from browser and CLI?

### Browser Steps

1. Open google chrome in incognito mode (to avoid interference of plugins etc).
2. Navigate to https://www.google.com/
3. Open Chrome Dev Tools > Lighthouse
4. Check Performance (uncheck other metrics)
5. Select Desktop
6. Click “Analyze page Load”

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/1099993/212425453-09cdf77a-1368-46dc-8cb2-99ce0fb849ce.png">

## Browser Results

<img width="998" alt="image" src="https://user-images.githubusercontent.com/1099993/212429829-4c291ae6-1f58-4508-b9ee-7c6937f1a23e.png">

### CLI Steps

```
lighthouse https://www.google.com --preset=desktop --only-categories=performance
```
## CLI Results

<img width="862" alt="image" src="https://user-images.githubusercontent.com/1099993/212429240-bff235d8-9615-4458-b282-bba0c281ebf5.png">

My assumption is the simple defaults of the browser and cli are the same, but I'm guessing I'm wrong and unclear how to align these to be the same.

**Comment by connorjclark** [comment]
@tleish why are you asking in this issue? Please make a new one.

I just tried to repro but could not. What version CLI you using? What Chrome (stable?) Can you try the latest CLI version? Please give this info and whatever is in the new issue template form in a new issue.

**Comment by tleish** [comment]
@connorjclark wrote:

> why are you asking in this issue? 

It seemed related and trying not to duplicate bugs 

> Please make a new one.

Done: https://github.com/GoogleChrome/lighthouse/issues/14681
