### ISSUE TITLE
Cant get frame for filmstrip event

### ISSUE THREAD

**Issue by jajo-shubham** [GoogleChrome/lighthouse#13749]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

android.com

### What happened?

While running lighthouse test via node package, i specified `gatherMode: true` and `auditMode:true` and via cli I did  `--save-assets` but i am not able to find the frame info at the moment a snapshot is captured. I would like to know how the snapshot actually correlates to the page load events when running via node package. 

For example.. when lighthouse is run inside chrome, there is a button called `View original Trace` which gives me required info 
<img width="433" alt="Screenshot 2022-03-15 at 8 14 07 PM" src="https://user-images.githubusercontent.com/52529793/158541798-56c74bde-a0e2-468c-b2a0-6e7d14946d9a.png">
<img width="667" alt="Screenshot 2022-03-15 at 8 08 02 PM" src="https://user-images.githubusercontent.com/52529793/158541857-1d5a26df-4fb0-4716-891c-79cc8001ec22.png">

### What did you expect?

I am able to get more than 10 screenshots from `.artifacts.traces.defaultPass.traceEvents.filter(evt => evt.name === 'Screenshot')`, 
But the object it returns is like 
```
{
  args: {
    snapshot: '<some base 64 value>'
  },
  cat: 'disabled-by-default-devtools.screenshot',
  id: '0x1',
  name: 'Screenshot',
  ph: 'O',
  pid: 38037,
  tid: 259,
  ts: 572296155584
}
```
It does not contain any information with respect to the frame or network event related to this screenshot 

### What have you tried?

I have tried reverse searching in events with this timestamp in `ts` but that also doesn't give anything

### How were you running Lighthouse?

node

### Lighthouse Version

9.2.1

### Chrome Version

98

### Node Version

14.18.2

### OS

OSX Montrey

**Comment by adamraine** [comment]
When you run Lighthouse with `gatherMode: true` (`-G` on the CLI) it will save performance trace to `latest-run/defaultPass.trace.json`.

You can then import the trace file into the DevTools performance panel to get a visual representation:

<img width="333" alt="Screen Shot 2022-03-16 at 6 34 51 PM" src="https://user-images.githubusercontent.com/6752989/158702525-e09e0c67-17d1-4d82-9593-cc1a345f7609.png">

**Comment by jajo-shubham** [comment]
Hey @adamraine What if I want that information programatically? Can I not parse the defaultPass file to know which screenshot corresponds to what event?

**Comment by adamraine** [comment]
The screenshots in the Lighthouse report don't correspond to anything specifically, they are there as a visual representation of what happened during the page load. The performance trace isn't a Lighthouse specific artifact so I don't think I can help much with this.
