### ISSUE TITLE
Lighthouse performance html report loads forever

### ISSUE THREAD

**Issue by Rodot** [GoogleChrome/lighthouse#13785]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://lightlab-stas.vercel.app/

### What happened?

When I run a performance audit, it runs normally and gets stuck at "Almost there! Lighthouse is now generating your report".

![image](https://user-images.githubusercontent.com/4189146/160230513-1af33453-24d4-4358-93be-e787456ccd58.png)

### What did you expect?

The performance should show up at the end of the audit

### What have you tried?

The other audits work normally and show the report as expected.
The issue is present on both mobile and desktop.
The issue is only present on my website https://lightlab-stas.vercel.app/ it runs normally on other websites

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

 9.2.0

### Chrome Version

99.0.4844.84 (Official Build) (64-bit)

### OS

Windows 10

### Relevant log output

```shell
I didn't find lighthouse's log
```

**Comment by Rodot** [comment]
### Update

I tried running lighthouse through CLI. It generates the HTML report, but when I attempt to open it with Chrome, it loads forever.

Here is the report produced.

[lightlab-stas.vercel.app_2022-03-26_09-12-33.report.html.zip](https://github.com/GoogleChrome/lighthouse/files/8354979/lightlab-stas.vercel.app_2022-03-26_09-12-33.report.html.zip)

**Comment by Rodot** [comment]
### Update
I had a 3MB <script> in index.html, since I added async to the <script> tag the lighthouse report is generated properly.
Should I close the issue?

**Comment by adamraine** [comment]
> I had a 3MB <script> in index.html, since I added async to the <script> tag the lighthouse report is generated properly.
Should I close the issue?

This looks like the same issue as https://github.com/GoogleChrome/lighthouse/issues/13613.

**Comment by connorjclark** [comment]
> ### Update
> I tried running lighthouse through CLI. It generates the HTML report, but when I attempt to open it with Chrome, it loads forever.
> 
> Here is the report produced : [lightlab-stas.vercel.app_2022-03-26_09-12-33.report.html.zip](https://github.com/GoogleChrome/lighthouse/files/8354979/lightlab-stas.vercel.app_2022-03-26_09-12-33.report.html.zip)

Thanks for sharing the report file, I also see it fail to render. I paused the JS and see its stuck at this regex:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/4071474/160481014-d794c461-2d69-4d30-819d-68f7b99c0f86.png">

**Comment by connorjclark** [comment]
seems like we could be exiting much earlier / or not doing a lot of this for data urls https://github.com/GoogleChrome/lighthouse/blob/219daf719ed7eecd22126d66364ee869b85a49ef/lighthouse-core/util-commonjs.js#L320

**Comment by connorjclark** [comment]
(but adam is right, the hanging at devtools loading prompt is probably that other issue)
