### ISSUE TITLE
Update Manifest Parser to new Spec

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#13805]
Seems like some of our manifest parsing is out of date, this link warns us about an outdated spec now:
https://github.com/GoogleChrome/lighthouse/blob/589ee41b683b77b851afacb22f5ce5520459080a/lighthouse-core/lib/manifest-parser.js#L114

For example, I don't think `start_url` falls back to the document url anymore.

We get our installability errors over the protocol now, but our own manifest parser is still used in a couple places.

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
