### ISSUE TITLE
replace TableColumnHeading with OpportunityColumnHeading

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#13803]
https://github.com/GoogleChrome/lighthouse/blob/master/types/lhr/audit-details.d.ts#L142

**Comment by brendankenny** [comment]
https://github.com/GoogleChrome/lighthouse/pull/10603 contains my previous attempt at this in its first two commits, then reverted in the last commit. Maybe useful? It wasn't that long ago.

We decided we wanted to give downstream projects with custom report renderers time to adjust, so we probably want to do the same thing here. There's enough 10.0 breaking stuff that we may need to be doing a real beta release and lots of release notes anyways :)
