### ISSUE TITLE
Lighthouse doesn't always report unload listener

### ISSUE THREAD

**Issue by kevinfarrugia** [GoogleChrome/lighthouse#13813]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.ibm.com/docs/en/obi/current?topic=websites-website-monitoring-faq

### What happened?

When running Lighthouse on https://www.ibm.com/docs/en/obi/current?topic=websites-website-monitoring-faq, it does not report any `unload` listeners.

The `beforeunload` event is added from a third-party script https://eum.instana.io/eum.js and prevents bfcache. This can be confirmed by running the Back/forward cache test from the Application tab in Chrome DevTools.

Note that another website (ex: https://sports.tipico.de/de) using the same third-party script reports the issue on Lighthouse.

### What did you expect?

I expected Lighthouse to flag the `unload` listener.

```
"no-unload-listeners": {
      "id": "no-unload-listeners",
      "title": "Registers an `unload` listener",
      "description": "The `unload` event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use `pagehide` or `visibilitychange` events instead. [Learn more](https://web.dev/bfcache/#never-use-the-unload-event)",
      "score": 0,
      "scoreDisplayMode": "binary",
      "details": {
        "type": "table",
        "headings": [
          {
            "key": "source",
            "itemType": "source-location",
            "text": "Source"
          }
        ],
        "items": [
          {
            "source": {
              "type": "source-location",
              "url": "https://eum.instana.io/eum.min.js",
              "urlProvider": "network",
              "line": 25,
              "column": 164,
              "original": {
                "file": "lib/hooks/eventHandlers.js",
                "line": 41,
                "column": 14
              }
            }
          }
        ]
      }
    },
```

### What have you tried?

I have queried the HttpArchive to compare how many websites use this third-party script and how many actually report an `unload` listener in Lighthouse. Less than 1% are reported.

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools, WebPageTest

### Lighthouse Version

9.4.0

### Chrome Version

100.0.4896.60 (Official Build) (64-bit) 

### Relevant log output

```shell
"no-unload-listeners": {
      "id": "no-unload-listeners",
      "title": "Avoids `unload` event listeners",
      "description": "The `unload` event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use `pagehide` or `visibilitychange` events instead. [Learn more](https://web.dev/bfcache/#never-use-the-unload-event)",
      "score": 1,
      "scoreDisplayMode": "binary"
    },
```

**Comment by connorjclark** [comment]
The audit only checks `unload`, not `beforeunload`. Only the former invalidates bfcache, was that your concern? https://web.dev/bfcache/#only-add-beforeunload-listeners-conditionally

**Comment by kevinfarrugia** [comment]
Thank you. I was incorrect and the script does _not_ register an `unload` listener, but another script does and Lighthouse was incorrectly attributing the `unload` to eum.min.js when it originated from another third party file.

I believe this issue occurs because `eum.min.js` is a monitoring tool that extends `addEventListener` and therefore all events are incorrectly attributed to it.

From my end the issue may be considered closed. Thanks.

**Comment by connorjclark** [comment]
I think this issue is related to the problem of attribution: #8526

**Comment by kevinfarrugia** [comment]
For the record, I used `getEventListeners(window)['unload']` to better locate the offending code, although I am not sure if this is always reliable.
