### ISSUE TITLE
Increasing pauseAfterLoadMs also increases Total Blocking Time

### ISSUE THREAD

**Issue by bakiasib** [GoogleChrome/lighthouse#13829]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

Locally

### What happened?

When increasing the pauseAfterLoadMs to 5000 the Total Blocking Time (TBT) increased to 1237ms, which decreased its score to 11%. 
```
module.exports = {
  extends: "lighthouse:default",

  passes: [
    {
      passName: 'defaultPass',
      /** The number of milliseconds to wait after the load event until the page should be considered loaded. */
      pauseAfterLoadMs: 5000,
      gatherers: []
    },
  ],
```

### What did you expect?

TBT should not have been affected by pauseAfterLoadMs

### What have you tried?

I played around with the values of pauseAfterLoadMs; the more I increased them the more the TBT score decreased.

### How were you running Lighthouse?

node

### Lighthouse Version

6.0

**Comment by connorjclark** [comment]
1) you are on a really old version of lighthouse
2) it seems expected behavior that TBT could become worse if you allow lighthouse to inspect the page for a longer period of time.

**Comment by bakiasib** [comment]
@connorjclark  Hi Connor, so increase pauseAfterLoadMs directly affects TBT? Even if the page completely loads in lets say 1s and I increase pauseAfterLoadMs to 5s the TBT score goes down only because of me increasing pauseAfterLoadMs?

**Comment by connorjclark** [comment]
To me it sounds like you have long tasks that start or are more common after page load. Can you provide a URL?

**Comment by bakiasib** [comment]
@connorjclark yes I have a widget that starts during page load. Lighthouse was not waiting long enough for it to load and I wanted to calculate its size so that is why I increased the pauseAfterLoadMs. However the site is interactive even if the widget has not loaded yet, so I would think it wouldn't cause the scores of TBT or Time To Interactive, and First CPU Idle to drop

**Comment by connorjclark** [comment]
Instead of configuring `pauseAfterLoadMs` to maybe capture a later part of the page, I suggest you try our new user flow api and wait for your widget to appear before ending your timespan.

Perhaps because you've now captured this widget loading, the increased TBT is really a signal that the widget had a lot of blocking code associated with it?

https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md
