### ISSUE TITLE
TypeError 'ERR_INVALID_ARG_TYPE' trying to create report from user-flow

### ISSUE THREAD

**Issue by Resolution-of** [GoogleChrome/lighthouse#13825]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://example.com

### What happened?

I was looking into "user-flow" feature as it's commonly used for most of performance analyzing applications.

Please find code example taking from your snapshot article: [https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md#code-2](url)
```
import {writeFileSync} from 'fs';
import puppeteer from 'puppeteer';
import lighthouse from 'lighthouse';

async function main() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  const flow = await lighthouse.startFlow(page);

  await page.click('#expand-sidebar');
  await flow.snapshot();

  await browser.close();

  writeFileSync('report.html', flow.generateReport());
}

main();
```

Faced with an issue with function `writeFileSync('report.html', flow.generateReport());` which is respond such error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
    at writeFileSync (node:fs:2150:5)
    at main (file:///...) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Also, please note `await page.click('#expand-sidebar');` is not working due to the application changes.

It can be my own misunderstanding, but I've tried couple ways to fix it. Maybe there will be any suggestions.

Thanks in advance.

### What did you expect?

I've expected to get HTML report.

### How were you running Lighthouse?

node

### Lighthouse Version

9.5.0

### Node Version

16.14.2

### OS

Linux

**Comment by adamraine** [comment]
`flow.generateReport()` is an async function so it returns a promise for a string not just a string. This was a recent change and we forgot to update our docs, thanks for catching this.

Doing `writeFileSync('report.html', await flow.generateReport());` should fix the problem for you.

**Comment by Resolution-of** [comment]
@adamraine 
It's working. Thanks a lot
