### ISSUE TITLE
Questions regarding Google Lighthouse Results variability 

### ISSUE THREAD

**Issue by daphneyyt** [GoogleChrome/lighthouse#13822]
**Hi. We have a few questions for Google Lighthouse.  We would like to know whether the Lighthouse report results change under the following circumstances:**

**1. Will Google Lighthouse results change each time we run scan?**

1a) testing the same webpage over short intervals (e.g. at least once a day - 8 December 2021, 9 December 2021, 10 December 2021).

1b) testing the same webpage over the course of several months (e.g. once in December 2021, once in January 2022, once in March 2022).

**2. When the simulated throttling option is enabled on Google Lighthouse, does this disregard all network issues (e.g. using lan cable for internet, using wifi for internet)**

**3. Will Lighthouse results vary if we run a Lighthouse scan on different devices? (e.g. 2 different laptops running Google Lighthouse's performance scan on the same webpage)**

In all the above scenarios, simulated throttling is enabled.

Thank you!

**Comment by connorjclark** [comment]
did you see https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md
