### ISSUE TITLE
Lighthouse client bugs on proposed helloworld code in docs

### ISSUE THREAD

**Issue by jlanssie** [GoogleChrome/lighthouse#13857]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://example.com

### What happened?

When running the lighthouse client from my local machine, it bugs on the code lighthouse docs propose: 

## config.js
`module.exports = {
  extends: 'lighthouse:default',
  settings: {
    onlyAudits: [
      'first-meaningful-paint',
      'speed-index',
      'interactive',
    ],
  },
};`

## lighthouse.js 
`const lighthouse = require('lighthouse');
const config = require('./path/to/config.js');
lighthouse('https://example.com/', {port: 9222}, config);`

## Issues

When I run the proposed code, my console throws this error: 

> $ node lighthouse.js

> node:internal/process/promises:279
>             triggerUncaughtException(err, true /* fromPromise */);
>             ^
> Error: connect ECONNREFUSED 127.0.0.1:9222
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
>   errno: -61,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 9222
> }
> Node.js v17.8.0

### What did you expect?

For the code to execute without errors....

### What have you tried?

I tried lighthouse as a command and that works fine. 
Used the same URLs in the lighthouse node-version, but that always bugs.

I also tried simplifying the config.js, omitting the config.js. Simplifying the lighthouse.js, other URLs, other port numbers. 

### How were you running Lighthouse?

node

### Lighthouse Version

9.5.0

### Chrome Version

100.0.4896.88 

### Node Version

17.8.0

### OS

macOS Monterey 12.3.1 (M1 chip)

### Relevant log output

```shell
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222
}

Node.js v17.8.0
```

**Comment by connorjclark** [comment]
Would you like to send a PR?

**Comment by jlanssie** [comment]
No. I figured out the issue. It was not related to lighthouse but to chrome-launcher/puppeteer issue. It happened with a port issue. The chrome port was not correctly set to the lighthouse config.port (being used by lighthouse).

e.g. for puppeteer

```
...
const browser = await puppeteer.launch({
    headless: true,
    defaultViewport: null,
  });
  const options = SOMELIGHTHOUSECONFIG
  options.port = (new URL(browser.wsEndpoint())).port; //this was not correctly set and caused my issue.

const runnerResult = await lighthouse(url, options);
...
```

e.g. for chrome-launcher

```
...
const chrome = await chromeLauncher.launch({chromeFlags: ['--headless']});
const options = SOMELIGHTHOUSECONFIG
options.port = chrome.port //this was not correctly set and caused my issue.
const runnerResult = await lighthouse(url, options);
...
```
