### ISSUE TITLE
lighthouse always open with mobile mode in chronium ARM

### ISSUE THREAD

**Issue by luckhiem** [GoogleChrome/lighthouse#13852]
### FAQ

- [] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

local

### What happened?

I've run lighthouse with the config below, but always open the browser with mobile mode
```
const browser = await puppeteer.launch({
        defaultViewport: null,
        args: [
            "--remote-debugging-port=9222",
            "--disable-device-emulation",
            "--disable-network-throttling",
            "--disable-cpu-throttling"
        ],
        headless: false
    });
const runnerResult = await lighthouse(url, {
        port: 9222,
        disableStorageReset: true,
        output: "html",
        logLevel: 'info',
        config: {
            extends: "lighthouse:default",
            settings: {
                maxWaitForFcp: 15 * 1000,
                maxWaitForLoad: 35 * 1000,
                formFactor: 'desktop',
                screenEmulation: {
                    mobile: false,
                    width: 1350,
                    height: 940,
                    deviceScaleFactor: 1,
                    disabled: false,
                },
            }
        }
    });
    const reportJSON = runnerResult.report;
    const reportName = url.replace(ENV.DOMAIN, "");
    fs.writeFileSync(`./lighthouse-results/report_${reportName.replace("/", "")}_page.html`, reportJSON);
    console.log('Report is done for', runnerResult.lhr.finalUrl);
    await browser.close();
```

### What did you expect?

able to switch desktop mode

### How were you running Lighthouse?

node

### Lighthouse Version

9.5.0

### Chrome Version

Version 100.0.4896.75 (Official Build) (arm64)

### OS

macOS Monterey

**Comment by connorjclark** [comment]
If you're not really using puppeteer you should use `chromeLauncher` instead. see https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically

If you really need to use puppeteer you'll want to use the new user flow API, which is designed to accept a puppeteer-launched browser https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md

If you're still stuck, please provide a reproducible script that I can simply copy, paste and execute.
