### ISSUE TITLE
Error: Something went wrong with recording the trace over your page load.

### ISSUE THREAD

**Issue by youshar** [GoogleChrome/lighthouse#13854]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://essentbiologics.org

### What happened?

PageSpeed Insights and Lighthouse within the Inspector window is erroring on the Desktop analysis specifically under: Largest Contentful Paint

Error Page: https://pagespeed.web.dev/report?utm_source=psi&utm_medium=redirect&url=essentbiologics.org&hl=en&form_factor=desktop

The error that returns is: Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_LCP)

### What did you expect?

I expected a Desktop score

### What have you tried?

Searched Git ad Google. It appears that the error has occurred in the past, but I din't find a fix I could implement to correct the issue. 

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools

### Lighthouse Version

9.3

**Comment by adamraine** [comment]
Looks like the page content loads when the mouse hovers over the page. Lighthouse doesn't simulate the mouse moving during the navigation automatically so the page never loads any content that would qualify as an LCP.

As part of our user flow api, you can simulate a navigation with user interaction, perhaps it can be of some use here: https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md#triggering-a-navigation-via-user-interactions

FWIW I waited a few seconds on the blank page before moving my mouse and realizing the page was waiting for me. This seems like a valid user experience for Lighthouse to test.
