### ISSUE TITLE
Test a public URL programmatically

### ISSUE THREAD

**Issue by aensley** [GoogleChrome/lighthouse#13866]
### Summary

I'm trying to automate performance monitoring of several websites I own/maintain. How do I use the node module to programmatically test a public URL?

### Test Setup

I'm currently trying with a simple script called `lhci-monitor.mjs`:

```JavaScript
import lighthouse from 'lighthouse';
lighthouse('https://somepublicwebsite.com/', {
  port: 443,
  logLevel: 'info',
  output: 'json'
}, {
  extends: 'lighthouse:default',
  settings: { onlyCategories: ['performance'] }
}).then((data) => {
  console.log(data)
});
```

### Output

However, it always tries to connect to localhost:

![image](https://user-images.githubusercontent.com/95717/163825243-944a7dbc-31fe-4336-b153-2ffe5cb20ac4.png)

Output in text for searchability:
```
$ node lhci-monitor.mjs 
  LH:status Connecting to browser +0ms
  LH:CriConnection:warn Cannot create new tab; reusing open tab. +10ms
  LH:status Disconnecting from browser... +3ms
  LH:status Cleaning origin data +0ms
  LH:CriConnection:error sendRawMessage() was called without an established connection. +3ms
  LH:GatherRunner disconnect:error sendRawMessage() was called without an established connection. +1ms
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443
}
```

**Comment by adamraine** [comment]
`port` refers to the Chrome debugging port exposed on your local machine that allows automation software such as Lighthouse to control Chrome programatically. It's not the port Chrome will use to connect to you public URL.

You need to have an instance of Chrome launched with the remote debugging port exposed to 433 for your code to work. Please see our [example for using lighthouse programmatically](https://github.com/GoogleChrome/lighthouse/tree/master/docs#using-programmatically).

**Comment by aensley** [comment]
@adamraine Thank you. I'm up and running now!
