### ISSUE TITLE
UserFlow type export for `UserFlowOptions` missing

### ISSUE THREAD

**Issue by BioPhoton** [GoogleChrome/lighthouse#13889]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

-

### What happened?

I wanted to type my code state starts a user flow correctly:

```typescript 
const options: MissingExportHere = { test: 23};
const flow = startUserFlow(page, options );
```

### What did you expect?

I can type my code state starts a user flow correctly:

```typescript 
const options: UserFlowOptions = { test: 23};
const flow = startUserFlow(page, options );
```

### What have you tried?

Looking up the types in the repo

### How were you running Lighthouse?

CLI

### Lighthouse Version

9

**Comment by adamraine** [comment]
The type is stored in a JSdoc comment:
https://github.com/GoogleChrome/lighthouse/blob/1daf915689682d616cff86529b06a15558693224/lighthouse-core/fraggle-rock/user-flow.js#L15-L20

The type situation in this file is a bit confusing though, we should probably move these types to https://github.com/GoogleChrome/lighthouse/blob/master/types/user-flow.d.ts.

**Comment by BioPhoton** [comment]
Thx for  pointing me there. I'll close the issue

**Comment by BioPhoton** [comment]
@adamraine Maybe a stupid question, but how can I consume them in a ts file? :)

**Comment by adamraine** [comment]
In 9.6.8, I don't think these types can be consumed because we don't publish the generated `d.ts` file for `user-flow.js`.

This is changing in 10.0, the changes I mentioned in https://github.com/GoogleChrome/lighthouse/issues/13889#issuecomment-1105647688 have already been made so I'm going to close this issue. The pattern currently available on `main` is:

```ts
import UserFlow from 'lighthouse/types/user-flow';
type UserFlowOptions = UserFlow.Options;
```

However, the dust hasn't settled yet. Hopefully #14441 will land in the next release so we can publish these types properly:

```ts
import {UserFlow} from 'lighthouse';
type UserFlowOptions = UserFlow.Options;
```

**Comment by BioPhoton** [comment]
Thx!!! I was confused and needed a feedback if I really have to do it that way. 

Just out of curiosity, why is it not like this: 

```typescript 
import {UserFlowOptions, UserFlow} from 'lighthouse';
```

mehrte one is the type and the other one the class that consumes that options?

In any case thx for your answer! And I’m looking forward to use v10 😎

**Comment by devillizard666** [comment]
i just found a google frp bypass
how do i report it and get paid
