### ISSUE TITLE
InspectorIssues protocol no longer contains message strings for deprecations

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#13895]
This is the cause of the current dbw deprecations [smoke failure](https://github.com/GoogleChrome/lighthouse/runs/6118254876?check_suite_focus=true#step:10:710).

These have been deprecated. They were english only, and as part of [i18n work](https://bugs.chromium.org/p/chromium/issues/detail?id=1264960) now clients are expected to provide them (and localize). 

[This CL](https://chromium-review.googlesource.com/c/chromium/src/+/3597476) removed the strings from deprecations. This is the only inspector type for which we rely on a message field.

DevTools frontend hasn't landed these strings yet, but they should end up [here](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/models/issues_manager/DeprecationIssue.ts?q=deprecationIssue&ss=chromium) soon. ([pending CL](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3600576)) We could parse that file for UIStrings in our collect strings script.

**Comment by connorjclark** [comment]
Let's just copy/paste the UIStrings into our source tree. That's what we did for installability errors. And then we don't have to figure out how to `require` the chrome devtools frontend module (which collect-strings would need to do).

**Comment by brendankenny** [comment]
> And then we don't have to figure out how to `require` the chrome devtools frontend module (which collect-strings would need to do)

Sounds terrible 

> Let's just copy/paste the UIStrings into our source tree. That's what we did for installability errors.

Sounds great!
