### ISSUE TITLE
Debug my website

### ISSUE THREAD

**Issue by Johngabz53** [GoogleChrome/lighthouse#13899]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://dkrcmugwedevelopers.online

### What happened?

My url isn't visible in search engines and visible to Google adsense

### What did you expect?

My url to be visible in search engines and visible to Google adsense

### How were you running Lighthouse?

CLI, PageSpeed Insights, Chrome DevTools, WebPageTest

### Lighthouse Version

CLI

**Comment by adamraine** [comment]
I don't see how this is related to Lighthouse. Please seek help on a more general support forum.
