### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by FMJansen** [GoogleChrome/lighthouse#13925]
I noticed the main branch of this repository is still called `master`. I can see multiple repos, like https://github.com/GoogleChrome/web.dev/, have already switched to `main`. The [chrome-devrel-review-bot](https://github.com/chrome-devrel-review-bot) also warns us to not use the word `master`, but that is difficult to do when lighthouse urls still contain that word.

I understand changing the name can have some unexpected impact, like when the devtools change required a code change in this repo (https://github.com/GoogleChrome/lighthouse/pull/13266) and because web.dev links to quite some lighthouse source code. Still, it seems like a good idea to move away from this kind of language and switch to calling it `main`.

**Comment by paulirish** [comment]
@FMJansen Thank you. We intend to do this, but have been slow to make it happen. But we shall.

**Comment by mel-ada** [comment]
@paulirish Wanted to check in because this is super important! Do you have a ballpark timeline? Are there technical blockers?

**Comment by paulirish** [comment]
Thanks ya'll. Apologies for the delay.
