### ISSUE TITLE
Listitem audit description outdated after axe-core update

### ISSUE THREAD

**Issue by FMJansen** [GoogleChrome/lighthouse#13926]
**Feature request summary**
Update the audit description of the listitem test to reflect that axe-core now allows listitems in menu elements.
Will create a PR soon.

**What is the motivation or use case for changing this?**
The `<menu>` element is a semantic alternative to `<ul>`, which means that `<li>` elements are allowed to live inside of it, according to the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu) and [W3 spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element). Axe-core has also acknowledged and fixed this in version 4.4.0 (issues https://github.com/dequelabs/axe-core/issues/3411 and https://github.com/dequelabs/axe-core/issues/3284, PR https://github.com/dequelabs/axe-core/pull/3286). Lighthouse seems to have updated axe-core to at least 4.4.1 (commit https://github.com/GoogleChrome/lighthouse/commit/37a1ceb4bb365fc6df470d1cc172760ae03fffa5) in the upcoming version. I think this means Lighthouse will no longer flag `<li>`s in `<menu>` as problematic, so the audit text should be updated accordingly.

**How is this beneficial to Lighthouse?**
It makes sure the audit description is correct and up-to-date.

**Comment by adamraine** [comment]
Good catch, sounds good.
