### ISSUE TITLE
`update:snapshot-sample-json` should be kept in sync with master

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#13935]
The other samples jsons (normal report, flow report) are verified to have no changes in CI every commit, but not this one.

**Comment by brendankenny** [comment]
Is there a reason there's a separate snapshot one since `flow-sample-json` includes a snapshot step?

If it's just for the sample reports it could be built just for that.

**Comment by adamraine** [comment]
> Is there a reason there's a separate snapshot one since flow-sample-json includes a snapshot step?

It's just for the sample reports. It was a way to see how snapshot reports look in a standalone report format.

**Comment by brendankenny** [comment]
`const snapshotLhr = flowResult.steps.find(step => step.lhr.gatherMode === 'snapshot')?.lhr` could maybe work in build-sample-reports
