### ISSUE TITLE
lighthouse report generated but with all the question marks and "Error"

### ISSUE THREAD

**Issue by toncoolx** [GoogleChrome/lighthouse#13938]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://mytaxppu.iras.gov.sg/estamping/

### What happened?

we are developing our new website currently and like to use google lighthouse (GL) to evaluate our website's Performance, Accessibility and SEO. The report is generated, but all the scores and findings are the question marks (?) and Error.

not sure if you may want to know as well: our website is using angular and its Single page application (SAP). 
the above URL is a login page, and it can only be accessed by whitelisted IP. sorry about that as this is a restricted project. 
When I run the GL, I have already login so should not have the credential issue. 

The Error msg showing in the report is: 
"There were issues affecting this run of Lighthouse:
Lighthouse was unable to reliably load the page you requested. Make sure you are testing the
correct URL and that the server is properly responding to all requests. (Status code: 404)"

<img width="772" alt="Google Lighthouse Report - Sample" src="https://user-images.githubusercontent.com/104117619/165672116-57a8f596-6ceb-4dea-aeb3-c4d833e0b23e.png">

### What did you expect?

to generate a working GL report.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

Lighthouse 9.2.0

### Chrome Version

100.0

**Comment by adamraine** [comment]
> the above URL is a login page, and it can only be accessed by whitelisted IP.

If we can't access this page then it will be difficult to verify that there is a bug.

Your server is probably responding with a 404 page and Lighthouse is accurately reporting that in the error message. Does the site respond with a 404 message without Lighthouse?

**Comment by toncoolx** [comment]
Thanks Adamraine for the reply. Sorry as the site is in a restricted zone and IP will need to be whitelisted before being able to access, I was not able to grant you access. So sorry about that.  

The site is working fine so I run the lighthouse. attaching the screenshot for the site while I running the GL report. 
<img width="960" alt="MicrosoftTeams-image (15)" src="https://user-images.githubusercontent.com/104117619/165882897-4dac16ba-b262-4b37-8e2a-5feeff57a93e.png">
