### ISSUE TITLE
Lighthouse/web.dev metrics do not show correct values compared to the original trace

### ISSUE THREAD

**Issue by mbogunovic** [GoogleChrome/lighthouse#13958]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

http://www.test.komaspec.com/

### What happened?

Go to ['web.dev'](https://web.dev/measure/) and measure https://www.test.komaspec.com/ (mobile)
Run Lighthouse audit from inspect mode in chrome/edge and open up original trace: [2](https://prnt.sc/pB_lVPkD7fxo) (mobile)
Notice how the LCP flag is under 1 second, but in the audit, it says 5 seconds https://prnt.sc/uQLAmZ-_JMex

### What did you expect?

I would expect that the actual audit shows a better score since the actual loading speed is faster than the audit final metrics, I've optimized the website to the point where there is not much to be optimized anymore, but metric results just look wrong.

### What have you tried?

Checked the original trace to see what are the actual metrics and noticed that the actual metrics are way smaller than the ones in the final report. 

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools, web.dev

### Lighthouse Version

9.4.0

### OS

Windows

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/discussions/13779

This is expected. Lighthouse adds throttling *after* the trace is taken by default.
