### ISSUE TITLE
Remove responsiveness timing fallback when m103 is stable

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#13992]
Added in #13985 to work around new EventTiming trace args introduced in https://crrev.com/c/3632661 (released in 103.0.5052.0).

**Comment by adamraine** [comment]
@brendankenny can we do this now?

**Comment by brendankenny** [comment]
in theory yes, but in classic Lighthouse fashion, we have test traces using the old format :/ I think in this case it's just the sample flow artifacts that matter, so maybe next time we update those this can go.
