### ISSUE TITLE
Tap targets audit text description does not correspond with what the code actually tests

### ISSUE THREAD

**Issue by mathisobadia** [GoogleChrome/lighthouse#14006]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://cerulean-cooperative-bladder.glitch.me/

### What happened?

Here is the full description of the [audit on web.dev ](https://web.dev/tap-targets/) 

> Targets that are smaller than 48 px by 48 px or closer than 8 px apart fail the audit

Here is the audit description directly from lighthouse

> Interactive elements like buttons and links should be large enough (48x48px), and have enough space around them, to be easy enough to tap without overlapping onto other elements. [Learn more](https://web.dev/tap-targets/).

But lighthouse does not detect of tap target that is smaller than that as [this site ](https://cerulean-cooperative-bladder.glitch.me/) has a single tap target of size 7x18 px. Looking at [the source code of the audit](https://github.com/GoogleChrome/lighthouse/blob/544144df00dd3ca21732a5657472982c97d328e3/lighthouse-core/audits/seo/tap-targets.js#L282-L285) it is clear why this is. The code finds the tap targets that are too small, but only uses the result as an input to get overlapping targets and if they don't overlap then the test passes. My guess is that the code is right but the description is wrong but I'm not sure which way it is. 

This is not the only issue, as the 8px apart is also false. And not what the code actually checks, code checks that the targets with padding do not overlap by more than 25%. So there is no single fixed value after which the tap targets can be considered far enough as this depends on the tap target size. See this [test code](https://github.com/GoogleChrome/lighthouse/blob/17b7163486b69239689ed49415bdeee6f7766bfa/lighthouse-core/test/audits/seo/tap-targets-test.js#L33-L38) to get an idea what is actual value is depending on tap target size

You can check this using those two examples:
[Tap targets 8px apart](https://east-fragrant-reaction.glitch.me/) => audit fails
[Tap targets 12px apart](https://fearless-friendly-fuchsia.glitch.me/) => audit passes
[Very small tap targets 17px apart](https://marred-versed-bumper.glitch.me) => audit fails

### What did you expect?

The audit description replace and with or
Interactive elements like buttons and links should be large enough (48x48px), and have enough space around them, to be easy enough to tap without overlapping onto other elements. [Learn more](https://web.dev/tap-targets/).
to =>
Interactive elements like buttons and links should be large enough (48x48px), **or** have enough space around them, to be easy enough to tap without overlapping onto other elements. [Learn more](https://web.dev/tap-targets/).

### What have you tried?

Looking at the source code to check actual behaviour of the audit

### How were you running Lighthouse?

web.dev

### Lighthouse Version

9.3.0

### OS

Mac

**Comment by adamraine** [comment]
Thanks for digging in @mathisobadia! Your analysis was correct an we have updated our docs and audit description.

**Comment by mathisobadia** [comment]
@adamraine thank you 🙌
