### ISSUE TITLE
Error rendering html report when running cli performance audit.

### ISSUE THREAD

**Issue by ChristopherPHolder** [GoogleChrome/lighthouse#14001]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://daomaker.com

### What happened?

Running "lighthouse https://daomaker.com/ --view" returns a blank page. 

The console log reveals this error: 

```js
[Error] TypeError: null is not an object (evaluating 'n.width.toString')
	render (daomaker.com_2022-05-13_15-48-53.report.html:102:2731)
	renderNode (daomaker.com_2022-05-13_15-48-53.report.html:118:7083)
	_renderTableRow (daomaker.com_2022-05-13_15-48-53.report.html:118:5168)
	_renderTableRowsFromItem (daomaker.com_2022-05-13_15-48-53.report.html:118:5437)
	_renderTable (daomaker.com_2022-05-13_15-48-53.report.html:118:6201)
	populateAuditValues (daomaker.com_2022-05-13_15-48-53.report.html:81:2151)
	_renderOpportunity (daomaker.com_2022-05-13_15-48-53.report.html:139:1540)
	(anonymous function) (daomaker.com_2022-05-13_15-48-53.report.html:139:5581)
	forEach
	render (daomaker.com_2022-05-13_15-48-53.report.html:139:5538)
	_renderReport (daomaker.com_2022-05-13_15-48-53.report.html:174:5757)
	renderReport (daomaker.com_2022-05-13_15-48-53.report.html:174:1323)
	(anonymous function) (daomaker.com_2022-05-13_15-48-53.report.html:259:821)
	(anonymous function) (daomaker.com_2022-05-13_15-48-53.report.html:259:858)
	Global Code (daomaker.com_2022-05-13_15-48-53.report.html:261)
```

However, "lighthouse https://daomaker.com/ --output=json --output-path=./report.json --save-assets" does return e-report-0.devtoolslog.json report-0.trace.json report.json and does not seem to have any errors. 

The error is also present when using https://pagespeed.web.dev/report?url=https%3A%2F%2Fdaomaker.com%2F where it returns `Error: LHR failed to render`.

However, it does show historical data.

### What did you expect?

An HTML Rendered lighthouse report or a proper error message to help fix the bug in my code.

### What have you tried?

I have tried running the same command on a different domain which worked. 

I have tried adding options to the CLI command and it still failed. The options I tried were:
```js
--screenEmulation.disabled 
--throttling-method=provided 
--no-emulatedUserAgent
--only-categories=performance 
--enable-error-reporting 
--view 
--chrome-flags='--window-size=412,660'"
```

I have also tried downgrading the CLI version and got no results.

### How were you running Lighthouse?

CLI

### Lighthouse Version

"lighthouse": "^9.6.1"

### Chrome Version

Version 101.0.4951.64 (Official Build) (x86_64)

### Node Version

v16.14.2

### Relevant log output

```shell
[Error] TypeError: null is not an object (evaluating 'n.width.toString')
	render (daomaker.com_2022-05-13_15-48-53.report.html:102:2731)
	renderNode (daomaker.com_2022-05-13_15-48-53.report.html:118:7083)
	_renderTableRow (daomaker.com_2022-05-13_15-48-53.report.html:118:5168)
	_renderTableRowsFromItem (daomaker.com_2022-05-13_15-48-53.report.html:118:5437)
	_renderTable (daomaker.com_2022-05-13_15-48-53.report.html:118:6201)
	populateAuditValues (daomaker.com_2022-05-13_15-48-53.report.html:81:2151)
	_renderOpportunity (daomaker.com_2022-05-13_15-48-53.report.html:139:1540)
	(anonymous function) (daomaker.com_2022-05-13_15-48-53.report.html:139:5581)
	forEach
	render (daomaker.com_2022-05-13_15-48-53.report.html:139:5538)
	_renderReport (daomaker.com_2022-05-13_15-48-53.report.html:174:5757)
	renderReport (daomaker.com_2022-05-13_15-48-53.report.html:174:1323)
	(anonymous function) (daomaker.com_2022-05-13_15-48-53.report.html:259:821)
	(anonymous function) (daomaker.com_2022-05-13_15-48-53.report.html:259:858)
	Global Code (daomaker.com_2022-05-13_15-48-53.report.html:261)
```

**Comment by connorjclark** [comment]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/4071474/168323885-608e3a12-cd68-4dbe-87d4-84b170a5b96a.png">

Very unusual. This should never return a non-number value:
  https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/page-functions.js#L436

**Comment by brendankenny** [comment]
is the site overriding `getBoundingClientRect()`? `NaN` gets turned into `null` through `JSON.stringify()`, but it shouldn't be returning `NaN` either.

**Comment by connorjclark** [comment]
uh... yup :)

<img width="560" alt="image" src="https://user-images.githubusercontent.com/4071474/168328810-ed85c705-2589-4295-bc5b-a4fbeb9e6803.png">
