### ISSUE TITLE
Treemap double-counts JS resource reached via redirect

### ISSUE THREAD

**Issue by ukslim** [GoogleChrome/lighthouse#14014]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://retirementcalculator.hsbc.co.uk/

### What happened?

Network tab shows what happens handling the GET request for `https://minerva.wealthwizards.io/pension-guidance/main.js `
The response is a 307 redirect, and the browser goes on to GET `https://minerva.wealthwizards.io/pension-guidance/1.3.35/assets/main.js`

However, Lighthouse's treemap report includes a box for both URLs, assigning the full size of that resource to both.

![image](https://user-images.githubusercontent.com/923002/168818529-8fe26703-fd24-4d7f-a8b9-97993f59629e.png)

### What did you expect?

I would expect to see one box for `https://minerva.wealthwizards.io/pension-guidance/1.3.35/assets/main.js (redirected from https://minerva.wealthwizards.io/pension-guidance/main.js)` 

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.5.0

### Chrome Version

101.0.4951.64 (Official Build) (arm64)

### OS

OSX

**Comment by connorjclark** [comment]
Thanks for the report!

On latest master version of Lighthouse, this is no longer an issue:

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/4071474/168867734-42a42617-ac91-45da-9a1e-b18f6dca4e84.png">

Our 10.0 release (no date yet) will have this fixed.
