### ISSUE TITLE
remove sd-validation audit

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#14016]
#4359 is the original issue structured data issue.

This audit isn't included in any config, but it's still in the repo and tests are still run for it. #14015 had an issue in Node 18 with some usage of Buffers deep in `sd-validation-test` -> `sd-validation` -> `jsonld` -> `http-client` -> `ky-universal` -> `node-fetch` because of an old version of `jsonld` dependencies. They've [landed the fix](https://github.com/digitalbazaar/jsonld.js/pull/484/files) but [the release isn't quite out yet](https://github.com/digitalbazaar/jsonld.js/issues/483), so working around it with a `resolutions` entry for now.

However, if we're not going to ever turn the audit on, should we just remove it? The deps for the audit were moved to devDeps in #12466, maybe it's just time to remove for good now?

**Comment by davidlehn** [comment]
FYI, `jsonld` v6.0.0 was released so that particular node-fetch audit issue should be gone.
