### ISSUE TITLE
[DevTools] "Lighthouse is warming up" after timespan is ended

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#14029]
This is a minor issue, and maybe better over in crbug, but after you end a timespan, the first message in the progress dialog is "Lighthouse is warming up", a holdover from navigation mode.

Can that message be skipped while auditing timespans?

**Comment by adamraine** [comment]
Yeah the loading bar isn't super helpful in timespan/snapshot mode because it looks for page navigation events in the log which timespan/snapshot don't provide. Can we use this issue to track better alignment between the progress dialog and FR modes?

**Comment by adamraine** [comment]
This has been fixed:
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4606355
