### ISSUE TITLE
Pagespeed TBT is different from Lighthouse TBT

### ISSUE THREAD

**Issue by yogeshsharma0** [GoogleChrome/lighthouse#14034]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.careers360.com/premium/top-careers-options-in-political-science-majors?&ici=premium-category-listing_career-counselling&icn=article-108905

### What happened?

We are testing TBT for some of our pages but chrome's dev tools lighthouse TBT is coming as different from pagespeed hosted version, please see attached screenshots, we have tested on multiple devices with same issue, how is lighthouse calculating the TBT ?
TBT on https://pagespeed.web.dev/
<img width="1422" alt="Screenshot 2022-05-20 at 5 05 39 PM" src="https://user-images.githubusercontent.com/87476327/169521010-ff18e7a2-f870-4f95-b2d1-b7747d4cba20.png">

TBT through lighthouse version 9.5.0

<img width="1425" alt="Screenshot 2022-05-20 at 5 07 11 PM" src="https://user-images.githubusercontent.com/87476327/169521030-e6c49162-ea52-415f-8da2-2d1c523e4841.png">

### What did you expect?

TBT Should be same or should not vary this much

### What have you tried?

Running lighthouse on multiple devices

### How were you running Lighthouse?

PageSpeed Insights, web.dev

### Lighthouse Version

9.5.0

**Comment by adamraine** [comment]
Merging into https://github.com/GoogleChrome/lighthouse/issues/6708
