### ISSUE TITLE
Errors installing lighthouse 1.4.0 from npm

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1405]
`npm install -g lighthouse`

<img width="958" alt="screen shot 2017-01-04 at 4 49 33 pm" src="https://cloud.githubusercontent.com/assets/238208/21664814/ca3bd634-d29d-11e6-8051-194e94a1d06c.png">

**Comment by brendankenny** [comment]
@paulirish 

looks like `manual-chrome-launcher.js` wasn't built when publishing. I'll do a 1.4.1, I guess?

**Comment by rpkoller** [comment]
i've received the same error. Might append the debug.log as well.

**Comment by brendankenny** [comment]
thanks, it was just published without one of the typescript files built. We're going to push after fixing a small bug in the report viewer.

**Comment by ebidel** [comment]
Confirming 1.4.1 fixes this. 

```
lighthouse --version
1.4.1
```
