### ISSUE TITLE
No way to find previously run reports after closing chrome

### ISSUE THREAD

**Issue by adarali** [GoogleChrome/lighthouse#14053]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.privatevpnurl.com/why/do/you/need/it/to/report/bugs

### What happened?

I closed chrome then opened it but the reports disappeared

### What did you expect?

the reports to not disappear

### What have you tried?

I don't know. I just closed and opened chrome and the reports disappeared. 

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

The version that comes with chrome 101.0.4951.54

### Chrome Version

101.0.4951.54

### Node Version

no idea.

### OS

Linux

**Comment by connorjclark** [comment]
If you want to save a report from the Lighthouse DevTools panel, you have these options available:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/4071474/170375923-64a862b7-3f8a-4394-ad99-11d79bb3ff48.png">

**Comment by adarali** [comment]
So it's not a bug, it's a feature. I thought it automatically kept a report history. Well, that's a bummer. I've lost lots of reports just by closing chrome. So I need to save every report manually, gotcha!

**Comment by connorjclark** [comment]
Well, non-feature :) Open in viewer -> Save as Gist (in the same menu, but in the viewer webpage) is the fastest way to save a report to a GitHub account FYI.
