### ISSUE TITLE
Safari 15.4 supports manifest-declared PWA icons: "Does not provide a valid apple-touch-icon" warning is now redundant!

### ISSUE THREAD

**Issue by BenjaminAster** [GoogleChrome/lighthouse#14064]
Safari 15.4 (released March 14) [added support for declaring icons in a web app manifest file](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/#:~:text=In%20addition,%20declaring%20icons%20in%20a%20web%20app%20manifest%20file%20is%20now%20supported.). Lighthouse's "Does not provide a valid apple-touch-icon" warning when auditing a PWA is now redundant and should be removed, as it is not necessary anymore for web developers to specify a `<link rel="apple-touch-icon" />`.

**Comment by connorjclark** [comment]
Only about half of Safari users are on a new enough version, perhaps we should wait a bit longer?


<img width="86" alt="image" src="https://user-images.githubusercontent.com/4071474/170886441-71da2a17-daa3-4c47-bfb9-af916cdf64ef.png">


https://caniuse.com/usage-table

**Comment by BenjaminAster** [comment]
@connorjclark I know, I thought about that too. But in my opinion it is the developer's responsibility to consider which browsers and browser versions to support. When you use CSS cascade layers, for example, Chromium doesn't warn you that "Safari < 15.4 does not support this feature" because developers should decide for themselves which browsers they want to support and which not. I think in these cases Lighthouse should always consider the most up-to-date versions of each browser. And don't forget that if this gets removed from Lighthouse now, it won't be upstreamed into Chrome stable until in a few months.

**Comment by BenjaminAster** [comment]
And btw caniuse's usage table isn't up-to-date either; the usage share statistics are from April. Notice how e.g. Chrome's most used version by a wide margin is 100, while Chrome's current version is 102 (which has only 0.02% usage according to caniuse), so that isn't true. Similar thing with Firefox.

**Comment by Seirdy** [comment]
The team will be deleting the audit in v10, as per discussion in [issue 11458](https://github.com/GoogleChrome/lighthouse/issues/11458#issuecomment-1074670276). It was already problematic as it ignored the icon's presence in the site root.

**Comment by connorjclark** [comment]
dupe #11458
