### ISSUE TITLE
Lighthouse not executing JavaScript to load page

### ISSUE THREAD

**Issue by shaunroselt** [GoogleChrome/lighthouse#14071]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.simac.app/

### What happened?

It fails and doesn't do an audit on the website. I suspect this is because there's lots of JavaScript that runs to load the webpage.
![image](https://user-images.githubusercontent.com/5418178/171350492-f8e13bd5-93db-41d8-82f8-539984ae7490.png)
![image](https://user-images.githubusercontent.com/5418178/171350195-815cf2bf-2fb0-40cb-9b60-aa4158065585.png)

### What did you expect?

I expected it to execute all the JavaScript and run the audit on the correct page and give me results.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

v9.6.1

### OS

Windows 11

**Comment by adamraine** [comment]
Lighthouse is getting stuck on this line when `parsedUrl` is an extremely long data URI (length 5960554):

https://github.com/GoogleChrome/lighthouse/blob/202d605b30c6223dcbba24244da76a9ee7293d6b/lighthouse-core/util-commonjs.js#L324

**Comment by adamraine** [comment]
Ah yup this was fixed by https://github.com/GoogleChrome/lighthouse/pull/13791 which was not included in 9.6 but will be in the next release.

**Comment by connorjclark** [comment]
We're gonna push a change to PSI to fix this ASAP.
