### ISSUE TITLE
Incorrect script size calculation in tree map

### ISSUE THREAD

**Issue by AndrijVasyliev** [GoogleChrome/lighthouse#14089]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://parimatch.com

### What happened?

In 9.6.1 version (all versions build from source) some scripts in tree map have doubled (and some tripled) size, if compare to network size in dev tools and to same report from 9.5.0 version of lighthouse.
I.e. https://parimatch.com/shell.js, https://parimatch.com/betbook-recommended-cards/assets/remoteEntry.js is doubled,
where https://parimatch.com/seo-kit/assets/remoteEntry.js is tripled.
Also for https://parimatch.com/shell.js there is one node in tree map, for https://parimatch.com/betbook-recommended-cards/assets/remoteEntry.js is two, and it has one and two requests respectively in chrome devtools.

### What did you expect?

Proper script size calculation.
Anyway, if script downloaded twice, it does not make it as twice bigger. And as for https://parimatch.com/shell.js - it downloaded one time, in ScriptElements  artifact it mentioned only once, but in have 2 child object in JsUsage  artifact. Probably some gatherer bug in case of https://parimatch.com/shell.js.

### What have you tried?

Looked at source codes and saved artifacts.
So in 9.5.0 Script gatherer is used. And size calculation made by scriptId with JsUsage artifact.
But in 9.6.1 ScriptElements gatherer is used, and size is calculated as plain sum of element size (determineLengths in unused-javascript-summary.js) so it makes size double for some script, and gives same unusedBytes value for each same script tree map entry.

### How were you running Lighthouse?

node

### Lighthouse Version

9.6.1

### Chrome Version

Version 102.0.5005.63 (Official Build) (64-bit)

### Node Version

v14.17.5

### OS

Linux

**Comment by connorjclark** [comment]
The size values in the treemap are resource size, not network size. The sites I checked confirmed this still works as intended. I can't test your site, because it is behind a CAPTCHA or something.

**Comment by AndrijVasyliev** [comment]
> indeed this was a bug, and will be fixed in the 10.0 release https://github.com/GoogleChrome/lighthouse/issues/14014#issuecomment-1129099822
If it will fix doubling of script size - it`s great!
