### ISSUE TITLE
FR `oopif-requests` is flaky

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#14099]
example failure: https://github.com/GoogleChrome/lighthouse/runs/6782136731?check_suite_focus=true

<img width="623" alt="image" src="https://user-images.githubusercontent.com/39191/172484109-68b0965e-bc72-493d-ac83-bc5ee4af0b33.png">

seems to be flaky just in FR smoketests. (incl FR bundled)

**Comment by connorjclark** [comment]
No, it isn't. Wasn't meant to close.
