### ISSUE TITLE
Error for you, Error for you, you in the back Error for you! 

### ISSUE THREAD

**Issue by zgonewild** [GoogleChrome/lighthouse#14096]
lol, anyway I cant do a website though the normal page speed insights page, I am able to do one the chromes inspect function / lighthouse function but still get multiple errors when doing so. Anyone have any idea where I might start 
![Screen Shot 2022-06-07 at 11 44 23 AM](https://user-images.githubusercontent.com/106047115/172458934-519f03af-5d20-4b6c-ab38-7a0bad77917e.png)

**Comment by adamraine** [comment]
Please don't spam us when we already have an issue for this https://github.com/GoogleChrome/lighthouse/issues/14045.
