### ISSUE TITLE
Sporadic NO_FCP/NO_LCP errors

### ISSUE THREAD

**Issue by jorgeluislazo** [GoogleChrome/lighthouse#14094]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.carbon60.com/managed-cloud/disaster-recovery-and-backup

### What happened?

When testing this site I sometimes get a NO_FCP error, even though other runs have successfully complete. I'm not sure what is causing the trace to fail.

Here is a zip file with a full LH run that failed (LH HTML file, log, trace and devtoolslog).

[fail.assets.zip](https://github.com/GoogleChrome/lighthouse/files/8847641/fail.assets.zip)

### What did you expect?

A succesful LH report.

Here is a sample successful run, done a few moments before the failed one above (LH HTML file, run log, trace and devtoolslog).

[success.assets.zip](https://github.com/GoogleChrome/lighthouse/files/8847634/success.assets.zip)

### What have you tried?

I tried to look at the log and the trace file, but couldn't pinpoint what is happenning. I can confirm this is not specific to me as other testing tools that use Lighthouse also have this issue, such as GTmetrix

### How were you running Lighthouse?

CLI

### Lighthouse Version

9.3.1

### Chrome Version

102

### Node Version

16.13.0

### OS

Linux

**Comment by adamraine** [comment]
I have not reproed this yet, but it's possibly related to #10869 and #13253 since it looks like the page content is animated in somehow.
