### ISSUE TITLE
Tree map inline script block breakdown structure.

### ISSUE THREAD

**Issue by AndrijVasyliev** [GoogleChrome/lighthouse#14090]
**Feature request summary**

In lighthouse json report in audits.script-treemap-data section in v. 9.5.0 was some breakdown for inline scripts.
Now in v9.6.1 its only one block, without any details.

I compared script-treemap-data,js from both versions and added some code, that brings that breakdown structure back, but for now only for script name and resourceBytes value. So, if feature will be considered useful, I can work on adding unusedBytes.

**What is the motivation or use case for changing this?**
Its was very useful information, so it will be good to return it back.
This breakdown info was really valuable in our project, because we wanted to find out, wat inline scripts was included in about 500 KiB inline script size to work on reducing its total size.

**How is this beneficial to Lighthouse?**
Lighthouse will provide users with more detailed data. So, there will be no need to investigate inline scripts size with other tools, just use  tree map report.

Below is some code, that solves this issue:
![Lighthouse](https://user-images.githubusercontent.com/106868250/172068862-7888033d-9e87-4fe7-a24e-a62ddc05d2b0.PNG)

**Comment by adamraine** [comment]
This feature wasn't added until after 9.5.0 https://github.com/GoogleChrome/lighthouse/pull/13802

It's slated to be released with 10.0. Were you using the latest master checkout rather than the official 9.5.0 release?

**Comment by AndrijVasyliev** [comment]
> Were you using the latest master checkout rather than the official 9.5.0 release?

Probably that is the case,

**Comment by connorjclark** [comment]
It'll be in the 10.0 release. In the meantime, you can use our master branch directly the `lighthouse@next` tag on npm.
