### ISSUE TITLE
Question about Estimated Savings

### ISSUE THREAD

**Issue by daphneyyt** [GoogleChrome/lighthouse#14107]
Hi Lighthouse team

We have a question regarding the time saved by rectifying the opportunities presented on Google Lighthouse.

**Question 1:**
We have embedded an example of a Lighthouse scan from our company's website. 

These are the opportunities identified:
1) Reduce initial server response time (estimated savings: 1.57s)
2) Enable text compression (estimated savings: 1.02s)
3) Reduce unused CSS (estimated savings: 0.72s)
4) Reduce unused JavaScript (estimated savings: 0.55s)
5) Eliminate render-blocking resources (estimated savings: 0.55s)

![Lighthouse Opportunities](https://user-images.githubusercontent.com/75086091/172788108-dcaba252-de78-4d59-b7a0-bc8d61441409.png)

May I understand if assuming all issues addressed by Lighthouse is addressed by our developers, then we should be able to save at least 4 minutes and 41 seconds of performance speed (4m41s is derived by totaling all the estimated savings identified by Lighthouse)?

**Question 2:**
If it is true that I am able to save 4 minutes and 41 seconds of performance speed, which of the 6 metrics do I match this data against?

![Lighthouse Metrics](https://user-images.githubusercontent.com/75086091/172788142-cce9a245-b6fb-43d1-bd44-7faeab930934.png)

Thank you.

**Comment by connorjclark** [comment]
> May I understand if assuming all issues addressed by Lighthouse is addressed by our developers, then we should be able to save at least 4 minutes and 41 seconds of performance speed (4m41s is derived by totaling all the estimated savings identified by Lighthouse)?

1) No, these opportunities are not independent. You can't sum up all the values and get a meaningful result.
2) How are you getting 4+ minutes??

>  If it is true that I am able to save 4 minutes and 41 seconds of performance speed, which of the 6 metrics do I match this data against?

They don't exactly match, but by far the closest correlation is TTI. All the opportunities deal with having the browser do less work, so for the most part all of their "Estimated savings" is a rough indicator, relative to the others, of how impactful they will be.
