### ISSUE TITLE
Bogus Styles Gatherer errors

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1412]
It seems whatever lighthouse is using for CSS parsing chokes with prefixed animation properties.

It's probably https://github.com/tonyganch/gonzales-pe/issues/257 but since I couldn't trace how you are using Gonzales PE I decided to open the issue here which is where I see it.

Example:

```
status Retrieving: Styles +1ms
Styles Gatherer:warn Could not parse content: Parsing error: Please check validity of the block starting from line #182
Styles Gatherer:warn
Styles Gatherer:warn 181 | @-webkit-keyframes bounce {
Styles Gatherer:warn 182*|   0%, 100% {
Styles Gatherer:warn 183 |     -webkit-transform: scale(0);
Styles Gatherer:warn 184 |             transform: scale(0); }
Styles Gatherer:warn
Styles Gatherer:warn Syntax: scss
Styles Gatherer:warn Gonzales PE version: 3.3.1 +68ms
```

Using v1.4.1 on Windows, with `lighthouse --output=pretty https://feimosi.github.io/baguetteBox.js/`

**Comment by ebidel** [comment]
We use the version (3.3.1) that's [bundled](https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/gonzales/gonzales-scss.js) with the chrome devtools frontend. The latest version appears to be [4.0.3](https://www.npmjs.com/package/gonzales-pe).

@paulirish how often does DT rev their module version?  I've various parsing errors on sites that may be fixed with a newer version.

**Comment by XhmikosR** [comment]
I doubt this is fixed in a newer version (see the issue I link above) so it might not be a good idea to update gonzales if it's only for this issue.

**Comment by paulirish** [comment]
Bug filed & patch put up: https://bugs.chromium.org/p/chromium/issues/detail?id=678728

**Comment by ebidel** [comment]
@paulirish is https://codereview.chromium.org/2614023002 ready to submit?

**Comment by XhmikosR** [comment]
Friendly ping :)

**Comment by paulirish** [comment]
@ebidel sorry, yup. landing now.

**Comment by paulirish** [comment]
landed.

chromium rev 448737 

I'll now dupe this ticket into  #1535 cuz its a dependency bump

**Comment by XhmikosR** [comment]
@paulirish: were the tools updated? I don't see the error with v2.0.0 anymore.
