### ISSUE TITLE
Space char on the value of a extra-headers

### ISSUE THREAD

**Issue by andonimuruamendiaraz** [GoogleChrome/lighthouse#14137]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://example.com

### What happened?

I am trying to execute lighthouse from a Powershell.

When I execute:
`lighthouse --chrome-flags="--headless" --extra-headers='{\"Authorization\":\"Bearertokenexample\"}' https://example.com`

Everyting works fine. 

BUT when I add a space char to the value:
`lighthouse --chrome-flags="--headless" --extra-headers='{\"Authorization\":\"Bearer tokenexample\"}' https://example.com`
 
I get the following error:
`Unexpected end of JSON input`

### What did you expect?

I expect to have the possibility to send a string with a space char as a Header.

### What have you tried?

I have tried several ways of scaping the space, the whole json, different types of quotes etc...

### How were you running Lighthouse?

CLI

### Lighthouse Version

9.6.2

### Chrome Version

102.0.5005.115

### Node Version

v16.15.1

### OS

Windows 10

**Comment by adamraine** [comment]
Try `lighthouse --chrome-flags="--headless" --extra-headers='{"Authorization":"Bearer tokenexample"}' https://example.com`

You shouldn't need to escape `"` characters inside of `'...'`

**Comment by adamraine** [comment]
I've noticed some differences between how Powershell and Zsh handle the quotes here.

@andonimuruamendiaraz that doesn't look like a valid Lighthouse version, can you please double check what version you are on?

**Comment by andonimuruamendiaraz** [comment]
> I've noticed some differences between how Powershell and Zsh handle the quotes here.
> 
> @andonimuruamendiaraz that doesn't look like a valid Lighthouse version, can you please double check what version you are on?

Yes my bad, I think I got the npm version instead :(

The correct version number is : 9.6.2 (I have updated it also on the issue´s description)

**Comment by andonimuruamendiaraz** [comment]
> Try
> 
> ```shell
> lighthouse --chrome-flags="--headless" --extra-headers='{"Authorization":"Bearer tokenexample"}' https://example.com
> ```
> 
> You shouldn't need to escape `"` characters inside of `'...'`

Without scaping the inside `"`s,  does not work either:

![image](https://user-images.githubusercontent.com/89006588/174539276-92f8ffcf-c12b-41af-94df-df71cff9fba5.png)

**Comment by connorjclark** [comment]
You can instead use `--cli-flags-path` and define your flags as a JSON file.
