### ISSUE TITLE
Not smart enogh to distingish between text and a color swatch

### ISSUE THREAD

**Issue by Zeioth** [GoogleChrome/lighthouse#14136]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://camisetasguays.com/products/camiseta-mascota-linux-tux-japones

### What happened?

Got the error
"Background and foreground colors do not have a sufficient contrast ratio." in a color swatch selector, and doesn't seem to be a way to correct it.

### What did you expect?

To pass the test correctly after finding the right values.

### What have you tried?

I tried with different levels of color and light for the color blue in
https://webaim.org/resources/contrastchecker/

But none seem to make lighthouse happy.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

v9.6.2

### OS

Arch Linux

**Comment by connorjclark** [comment]
Page doesn't load for me.

**Comment by Zeioth** [comment]
sure thing @connorjclark thank you
![screenshot_2022-06-16_21-45-15_265473516](https://user-images.githubusercontent.com/3357792/174152037-a3ba9924-6720-4bca-b1e9-ad6eed4f6df6.png)
![screenshot_2022-06-16_21-46-35_277541829](https://user-images.githubusercontent.com/3357792/174152233-c6efe3c6-9892-40bc-be2b-c8d349654a2f.png)

**Comment by Zeioth** [comment]
Also: I contacted my DNS and they fixed the issue; it should load correctly for everyone now from any device.

**Comment by connorjclark** [comment]
https://camisetasguays.com/products/crear-camiseta-personalizada?variant=40497816535177

Looks like it's passing now.
