### ISSUE TITLE
Make timing blue color lighter

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1413]
Probably another Windows issue, see the screenshot. "Printer" is sort of readable, but the timing at the end of line is very hard to read.

Windows 7, default Windows console.

![cmd](https://cloud.githubusercontent.com/assets/349621/21671077/a86385b4-d321-11e6-8f5d-cd470cfd1685.png)

**Comment by paulirish** [comment]
the proposal in #1372 might work for this, too.

**Comment by XhmikosR** [comment]
@paulirish: care to elaborate? As far as I can tell that issue is about the filenames' length? Let alone I believe it's for report not CLI output :)

**Comment by XhmikosR** [comment]
Oh, also, I don't think this is an issue with non-Windows judging by Travis CI.

**Comment by paulirish** [comment]
ah i was referring to the "but the timing at the end of line is very hard to read." but now realize you were talking about the "2ms" times rather than the critical chain details. 
Well, #1372 would at least make those crit chain lines not wrap. :)

**Comment by XhmikosR** [comment]
I was trying to see where the color for the timing is set. I only found https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/log.js#L30

I don't get those random numbers :/

**Comment by paulirish** [comment]
The `+2ms` is generated here:
https://github.com/visionmedia/debug/blob/master/src/node.js#L114

and the color for it _seems_ to be done in `selectColor`
https://github.com/visionmedia/debug/blob/master/src/debug.js#L44
where the namespace is actually just the timeDiff as a string. :)

Thats my quick read of it, at least.

**Comment by XhmikosR** [comment]
Thanks for the hints, I'll see if I find a better candidate and make a PR.

About the length for CLI, perhaps it would be better if we didn't use a double Light Horizontal Line, instead use a single one and adapt the code. Just a quick thought.

**Comment by paulirish** [comment]
We're not going to take this on right now. In the future we will likely change the CLI output entirely.
