### ISSUE TITLE
Opportunity - Enable text compression - Misdiagnosis

### ISSUE THREAD

**Issue by PhilixDetroe** [GoogleChrome/lighthouse#14178]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://pastebin.com/raw/4Jh5djec

### What happened?

Lighthouse scan is reporting that text compression is not enabled for the following URL 

( https://www.gstatic.com/recaptcha/releases/4rwLQsl5N_ccppoTAwwwMrEN/recaptcha__en.js ) 

However, text compression is enabled for gstatic.com.

The report states 

"Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes."

URL | Transfer Size | Potential Savings
…4rwLQsl5N_ccppoTAwwwMrEN/recaptcha__en.js(www.gstatic.com) | 362.5 KiB | 220.2 KiB

Checking the above link shows that compression is enabled.

Request:
`GET /recaptcha/releases/4rwLQsl5N_ccppoTAwwwMrEN/recaptcha__en.js HTTP/2`
`Host: www.gstatic.com`
`user-agent: curl/7.74.0`
`accept: */*`
`accept-encoding: gzip, deflate`

Response:
`vary: Accept-Encoding`
`content-encoding: gzip`

### What did you expect?

Lighthouse scan correctly detects the use of text encoding.

### What have you tried?

Checked google chrome - inspect - network - headers to make sure that encoding is enabled in the browser.

Checked from command line to make sure encoding is supported.

`curl https://www.gstatic.com/recaptcha/releases/4rwLQsl5N_ccppoTAwwwMrEN/recaptcha__en.js --silent -H "Accept-Encoding: gzip, deflate" --output /dev/null -vvv`

### How were you running Lighthouse?

CLI, node

### Lighthouse Version

9.6.2

### Chrome Version

Chromium 102.0.5005.115 built on Debian 11.3, running on Debian 11.3

### Node Version

v14.19.3

### OS

Debian 11.3

### Relevant log output

```shell
<details class="lh-expandable-details" open=""> <summary> <div class="lh-audit__header"> <div class="lh-load-opportunity__cols"> <div class="lh-load-opportunity__col lh-load-opportunity__col--one"> <span class="lh-audit__score-icon"></span> <div class="lh-audit__title"><span>Enable text compression</span></div> </div> <div class="lh-load-opportunity__col lh-load-opportunity__col--two"> <div class="lh-load-opportunity__sparkline" title="Potential savings of 220&nbsp;KiB"> <div class="lh-sparkline"><div class="lh-sparkline__bar" style="width: 85%;"></div></div> </div> <div class="lh-audit__display-text" title="Potential savings of 220&nbsp;KiB">2.55&nbsp;s</div> <div class="lh-chevron-container"><svg class="lh-chevron" viewBox="0 0 100 100"> <g class="lh-chevron__lines"> <path class="lh-chevron__line lh-chevron__line-left" d="M10 50h40"></path> <path class="lh-chevron__line lh-chevron__line-right" d="M90 50H50"></path> </g> </svg></div> </div> </div> </div> </summary> <div class="lh-audit__description"><span>Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes. <a rel="noopener" target="_blank" href="https://web.dev/uses-text-compression/?utm_source=lighthouse&amp;utm_medium=cli">Learn more</a>.</span><span class="lh-audit__adorn" title="Relevant to First Contentful Paint">FCP</span><span class="lh-audit__adorn" title="Relevant to Largest Contentful Paint">LCP</span></div> <div class="lh-audit__stackpacks"></div> <style>
    .lh-3p-filter {
      color: var(--color-gray-600);
      float: right;
      padding: 6px var(--stackpack-padding-horizontal);
    }
    .lh-3p-filter-label, .lh-3p-filter-input {
      vertical-align: middle;
      user-select: none;
    }
    .lh-3p-filter-input:disabled + .lh-3p-ui-string {
      text-decoration: line-through;
    }
  </style><div class="lh-3p-filter" hidden=""> <label class="lh-3p-filter-label"> <input class="lh-3p-filter-input" type="checkbox" checked=""> <span class="lh-3p-ui-string">Show 3rd-party resources</span> (<span class="lh-3p-filter-count">1</span>) </label> </div><table class="lh-table lh-details"><thead><tr><th class="lh-table-column--url"><div class="lh-text">URL</div></th><th class="lh-table-column--bytes"><div class="lh-text">Transfer Size</div></th><th class="lh-table-column--bytes"><div class="lh-text">Potential Savings</div></th></tr></thead><tbody><tr class="lh-row--even"><td class="lh-table-column--url"><div class="lh-text__url" title="https://www.gstatic.com/recaptcha/releases/4rwLQsl5N_ccppoTAwwwMrEN/recaptcha__en.js" data-url="https://www.gstatic.com/recaptcha/releases/4rwLQsl5N_ccppoTAwwwMrEN/recaptcha__en.js"><a href="https://www.gstatic.com/recaptcha/releases/4rwLQsl5N_ccppoTAwwwMrEN/recaptcha__en.js" rel="noopener" target="_blank" class="lh-link">…4rwLQsl5N_ccppoTAwwwMrEN/recaptcha__en.js</a><div class="lh-text lh-text__url-host">(www.gstatic.com)</div></div></td><td class="lh-table-column--bytes"><div class="lh-text" title="371,151&nbsp;bytes">362.5&nbsp;KiB</div></td><td class="lh-table-column--bytes"><div class="lh-text" title="225,453&nbsp;bytes">220.2&nbsp;KiB</div></td></tr></tbody></table></details>
```

**Comment by adamraine** [comment]
I can't reproduce this locally using the HTML you provided. It's possible that your localhost environment isn't compressing the text correctly but mine is.

Are you able to provide a publicly accessible URL where this is happening?

**Comment by PhilixDetroe** [comment]
Unfortunately, I don't have any URLs that I can share here.

Lighthouse Version: 9.6.2
Chrome Version: Chromium 102.0.5005.115 built on Debian 11.3, running on Debian 11.3
Node Version: v14.19.3

`{"url":"https://www.gstatic.com/recaptcha/releases/4rwLQsl5N_ccppoTAwwwMrEN/recaptcha__en.js","protocol":"h2","startTime":487.17999999644235,"endTime":581.6299999714829,"finished":true,"transferSize":371975,"resourceSize":371151,"statusCode":200,"mimeType":"text/javascript","resourceType":"Script"}`

Notice the transfer size of 371975 and resource size of 371151 ...

The good news is that after updating Chromium it no longer happens.

Lighthouse Version: 9.6.2
Chrome Version: Chromium 103.0.5060.53 built on Debian 11.3, running on Debian 11.3
Node Version: v14.19.3

`{"url":"https://www.gstatic.com/recaptcha/releases/4rwLQsl5N_ccppoTAwwwMrEN/recaptcha__en.js","protocol":"h2","startTime":887.088000017684,"endTime":968.408000015188,"finished":true,"transferSize":147248,"resourceSize":371151,"statusCode":200,"mimeType":"text/javascript","resourceType":"Script"}`

The transfer size is now smaller than the resource size implying compression is now working.

The message about text compression has also gone.

I would guess this is a Chromium that's resolved by updating.
