### ISSUE TITLE
CRX: investigate CSS light animation showing up in trace.

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1417]
@brendankenny mentioned that "testing your page" light/spinner animation is showing up in traces and could be effecting a page's perf numbers.

Opening this for someone to investigate.

**Comment by paulirish** [comment]
one cool thing we could do is only flip on the animation once the endTrace() has been sent. It'd still be worthwhile anyways.

**Comment by ebidel** [comment]
Marking this as a nice to have, GFB.

**Comment by brendankenny** [comment]
this is still funny, but in practice hasn't been a big deal.
