### ISSUE TITLE
Write into Session/Local Storage?

### ISSUE THREAD

**Issue by JWebDev** [GoogleChrome/lighthouse#14193]
Hi, it is possible to add possibility to write into Session/Local Storage? 
I cannot find any info? 
Maybe this can be a new feature? 
Or Is it completely impossible?

Motivation: 
Many sites perform authentication by writing values to the SessionStorage. Thus, it is impossible to run lighthouse on the pages of secured site, since there is no way to do authentication.

Thanks!

**Comment by adamraine** [comment]
It is possible to run Lighthouse on authenticated pages: https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md.

The examples in that doc don't work of login state is stored in session storage, but you can also use https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md in that case.

**Comment by JWebDev** [comment]
@adamraine Thanks for the quick response.
Yes exactly. The example will only work for sites that do not use Session Storage. Actually, I carefully studied the documentation and use this option.

Regarding the flow, an interesting solution, partially solves the problem, but not 100%.

1. And what is the problem that it is impossible to add this featiure? 
2. I'm sure I'm not the first one looking for a solution to this problem. Or is it technically impossible to do so far?

May I politely ask why you closed the ticket? You did not give me the answer whether this is possible at all? I do not think that the problem is solved in this way, or did you not answer why it is impossible to implement this feature?

**Comment by adamraine** [comment]
> May I politely ask why you closed the ticket? You did not give me the answer whether this is possible at all? I do not think that the problem is solved in this way, or did you not answer why it is impossible to implement this feature.

It should be possible right now with Lighthouse user flows, can you please elaborate on why this doesn't 100% solve the problem?

The normal node API will also be changed in LH 10.0 to support passing in a Puppeteer. Lighthouse will use the provided page in place without opening a new tab (session). Unfortunately we are still working on the documentation and API surface for 10.0 so nothing here is final.

You can follow along in https://github.com/GoogleChrome/lighthouse/pull/14191 and https://github.com/GoogleChrome/lighthouse/pull/14195 to get a preview of how authenticated pages will work for LH 10.0.

This change is related to user flows but I should have mentioned it separately, sorry about that.

**Comment by JWebDev** [comment]
Thanks for the answer.

I have at least 2 reasons.
1. I'm not use a pappeter.
2. As you yourself wrote. Flow has limitations.

If it is technically possible, it should be not difficult to do it, it is just an additional key-value parameter. Same as "--extra-headers".

It would be great if you could add this feature!
Thank you!

**Comment by JWebDev** [comment]
> Is there a reason you can't use Puppeteer?
Yes. The reason is the same as why I use lighthouse from the command line.
I want to automate lighthouse scans a bit. A utility that runs from the command line is enough for me. The utility does what it's supposed to do.
If you write everything in scripts, then why do you need a utility that runs from the command line and has limitations, because you don’t see the point in additional settings.

> That is not what I said. I was speaking about the [default Lighthouse node API](https://github.com/GoogleChrome/lighthouse/tree/master/docs) not the [user flow API](https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md). I'm interested in the limitations you faced when trying to get user flows working on your site :)

Didn't quite understand what you mean by "default Lighthouse node API"? NodeJs API? Puppet API? If not, where can I look at this API? I'm sorry if this is obvious to you, it's not so obvious to me. That's why I try to understand.

In all the examples in the documentation, you are working through puppeter. Do I understand correctly that the console utility does the same in the background when I call it from the command line?

Thanks!
