### ISSUE TITLE
Close tab after we're done with it

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1419]
In the CLI case we spawn a new tab, but then we keep it open we we disconnect.
I keep a `chrome-debug` open while I'm developing or perf testing, but I end up with LOTS of old tabs that I manually clear. 

I think that if we did spawn a new tab, then we should definitely close it when we teardown.
ya?

#goodsecondbug

**Comment by ebidel** [comment]
@gauntface was this your issue today?

**Comment by gauntface** [comment]
No.

Although this would make it look less crazy when tracing can't be started.

**Comment by wardpeet** [comment]
yes!
