### ISSUE TITLE
Inconsistent usage of Chrome ToT vs Chrome Stable in smokes

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#14197]
Once https://github.com/GoogleChrome/lighthouse/pull/14153 lands the CI jobs breakdown as follows:

Stable
- Standard CLI w/ Stable (from matrix)
- Package test

ToT
- Standard CLI w/ ToT (from matrix)
- \* DevTools smokes
- Bundled
- Windows

I like using ToT in most cases since fixes to Chrome will make it into our CI jobs sooner. It also allows us to catch issues with specific environments sooner.

\* DevTools smokes will use the Chrome shipped with DevTools after #14163 lands. Will be close to ToT but not exact.

**Comment by connorjclark** [comment]
FYI once #6557 lands I plan to switch devtools smokes to use the chromium that devtools frontend downloads.

**Comment by brendankenny** [comment]
bundled also ToT?

**Comment by adamraine** [comment]
Ope right, I accidentally did another "Package test" lol. Fixed.
