### ISSUE TITLE
docs(readme): add KeeperApp.io to the list of integrations

### ISSUE THREAD

**Issue by machtigBE** [GoogleChrome/lighthouse#14206]
Hi, please add [KeeperApp.io](https://www.keeperapp.io/) to the list of "Lighthouse Integrations in Web Perf services"

> Periodically test, and keep track of your website's Performance, SEO, Accessibility, Web Core Vitals and more using Google's Lighthouse service. KeeperApp.io offers features aimed at both smaller websites and big corporate sites. We offer multiple paid plans and a free tier perfect for smaller websites and projects!

**Comment by connorjclark** [comment]
Send a PR.
