### ISSUE TITLE
Protocol error (Runntime.evaluate): Cannot find context with specified id ```

### ISSUE THREAD

**Issue by susilogic** [GoogleChrome/lighthouse#14229]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://kueferei.ob-d.com/shop.html

### What happened?

I use Lighthouse frequently but today it creates an error.

It says:
site.webmanifest:1     Manifest: Line: 1, column: 1, Syntax error.

When running Lighthouse on Edge it goes idle and takes muuuuch longer than usually for this smalll code.
Please see below html code and the attached screenshot.

But then after dismiss the error message, a strange html appeard with strange code, like sql injection or something. Please see the attached html file. 

browser to debug: edge and chrome
laptop: thinkpad AMD Ryzen 8core/ Windows 10 (updated)
my project is based on typescript/vanilla and on the server, there is only css, js, html, images and the site manifest. Means it has no server side CMS.

### What did you expect?

Is the html code site.manifest (see below) code generated by Lighthouse? Wonder if the strange code is some injection of sort, because this does not look right.

### What have you tried?

Run LIghthouse again with chrome browser. It could finnish and create the score but under "Best Practices" it failed also with the same error in the site.manifest:

### How were you running Lighthouse?

Chrome DevTools, Other

### Lighthouse Version

9.6.1 

### Chrome Version

Version 103.0.5060.134 (Official Build) (64-bit)

### Node Version

v18.5.0

### OS

Windows 10

### Relevant log output

```shell
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="robots" content="noindex, nofollow">
<title>One moment, please...</title>
<style>
body {
    background: #F6F7F8;
    color: #303131;
    font-family: sans-serif;
    margin-top: 45vh;
    text-align: center;
}
</style>
</head>
<body>
<h1>Please wait while your request is being verified...</h1>
<form id="wsidchk-form" style="display:none;" action="/z0f76a1d14fd21a8fb5fd0d03e0fdc3d3cedae52f" method="get">
<input type="hidden" id="wsidchk" name="wsidchk"/>
</form>
<script>
(function(){
    var west=+((+!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+![])+(+![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])),
        east=+((+!+[]+!![]+!![]+!![])+(+!+[]+!![]+!![]+!![]+!![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!+[]+!![])+(+!+[]+!![]+!![]+[])+(+!+[]+!![])),
        x=function(){try{return !!window.addEventListener;}catch(e){return !!0;} },
        y=function(y,z){x() ? document.addEventListener("DOMContentLoaded",y,z) : document.attachEvent("onreadystatechange",y);};
    y(function(){
        document.getElementById('wsidchk').value = west + east;
        document.getElementById('wsidchk-form').submit();
    }, false);
})();
</script>
</body>
</html>
```

**Comment by susilogic** [comment]
Notice: On my localhost the Lighthouse performs correctly, so i assume i got a bug on the hosting server?

**Comment by susilogic** [comment]
My appologies i forgot to attach the .pn
![ERR_lighthouse](https://user-images.githubusercontent.com/67012145/180334892-0e02cc2c-f630-42cf-b5c1-91ed6c29fbcd.png)
g

**Comment by susilogic** [comment]
Two older project versions on subdomains create also the Error on site.manifest.
https://tut2.ob-d.com/
https://tut1.ob-d.com/

They got seperate directory on the server.

**Comment by susilogic** [comment]
I found this article on stackoverflow:

https://stackoverflow.com/questions/72678180/weird-new-tiktok-browser-javascript-vulnerability

Its exactly the same html code, created by the maleware code

**Comment by connorjclark** [comment]
Not seeing LH take much longer on that page. You still get an issue?
