### ISSUE TITLE
No score improvements after using webp / AVIF

### ISSUE THREAD

**Issue by ShashankaNataraj** [GoogleChrome/lighthouse#14234]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://jsfiddle.net/9reauonc/

### What happened?

Lighthouse seems to be reading the format in the file name rather than in the file output. Thus, for CDN's like contentful, though the network tab shows AVIF or WEBP images being downloaded, the "serve images in next gen formats" suggestion keeps showing up. Also, this doesn't change the scoring to the positive.

Original image URL: https://images.ctfassets.net/u275ja1nivmq/6T6z40ay5GFCUtwV7DONgh/0e23606ed1692d9721ab0f39a8d8a99e/yeti_cover.jpg

WEBP image URL:
https://images.ctfassets.net/u275ja1nivmq/6T6z40ay5GFCUtwV7DONgh/0e23606ed1692d9721ab0f39a8d8a99e/yeti_cover.jpg?fm=webp

AVIF image URL:
https://images.ctfassets.net/u275ja1nivmq/6T6z40ay5GFCUtwV7DONgh/0e23606ed1692d9721ab0f39a8d8a99e/yeti_cover.jpg?fm=avif

My webpage has all AVIF format images:
![image](https://user-images.githubusercontent.com/650317/180659269-ba255bf6-62df-4f90-bb9b-949effa01558.png)

Lighthouse still complains for those exact specific images which are AVIF
![image](https://user-images.githubusercontent.com/650317/180659273-1765774e-afc5-42a3-9fe5-1f458bc5f664.png)

### What did you expect?

- I expect lighthouse to read the format of the image rather than the extension of the file to calculate scores.
- I also expect the score to move towards the positive once formats have been changed to next gen formats as per recommendation

### What have you tried?

I've tried running the same test in web.dev, and on lighthouse. To no avail.
I tried changing the format of the images to WEBP through the query parameter. This didn't change anything.

### How were you running Lighthouse?

Chrome DevTools, web.dev

### Lighthouse Version

9.6.1

### Chrome Version

Version 103.0.5060.114 (Official Build) (64-bit)

### OS

Windows

**Comment by adamraine** [comment]
It seems like there is a production URL where this is happening, are you able to share that?

> I expect lighthouse to read the format of the image rather than the extension of the file to calculate scores.

Using your JSFiddle code, the results from the next gen images audit are correct. The only image we flag is the one that is *actually* formatted as a JPG:

![Screen Shot 2022-07-25 at 11 45 11 AM](https://user-images.githubusercontent.com/6752989/180851240-9dbcf432-d3ea-417c-bffc-40021f3f39a6.png)

Are you seeing different results for this audit on the JSFiddle code?

> I also expect the score to move towards the positive once formats have been changed to next gen formats as per recommendation

The score of this audit does not directly affect your performance score. [Only performance metrics impact the performance score](https://web.dev/performance-scoring/?utm_source=lighthouse&utm_medium=devtools). Following the suggestions in this audit will improve these performance metrics.

**Comment by ShashankaNataraj** [comment]
@adamraine Here is the prod URL where this is happening: https://develop.d337wy32ueusth.amplifyapp.com/
On this site, in lighthouse, you will observe that there are no JPG images shown in the network tab. All of them are AVIF format images. But lighthouse still complains about us not using next gen format images

**Comment by adamraine** [comment]
Thanks for the link, I can repro there. Lighthouse should be looking at the actual image type and not the extension for this audit.

**Comment by adamraine** [comment]
@ShashankaNataraj it looks like the site is serving different images for Lighthouse than it does normally. For example:

This image URL is served when Lighthouse tests the page:
https://images.ctfassets.net/u275ja1nivmq/2xdYbij746MgC2VSH6zbce/7885b2ebb106cf98d9fe4777e4951236/yeti_cover.jpg

However this image URL is served when the page is loaded normally:
https://images.ctfassets.net/u275ja1nivmq/2xdYbij746MgC2VSH6zbce/7885b2ebb106cf98d9fe4777e4951236/yeti_cover.jpg?fm=avif

Notice how `?fm=avif` is missing from the URL when Lighthouse tests it. It is likely that the page is serving different content for Lighthouse. I will try and replicate the behavior without Lighthouse, but this is likely an issue with the page.

**Comment by adamraine** [comment]
Yeah, when I emulate an iPhone SE via DevTools instead of Moto G4, the true JPG version of the image is served.

**Comment by ShashankaNataraj** [comment]
Thanks! That makes a lot of sense, I will modify the page to serve avif for lighthouse!
