### ISSUE TITLE
Code coverage indicating the exact lines that is covered

### ISSUE THREAD

**Issue by sachin7desai7** [GoogleChrome/lighthouse#14235]
**Feature request summary**

Currently the coverage show the percentage of JavaScript that is used, it would be helpful if it also provided the lines of java script that is actually executed.

With some initial help and pointers on how to get started i can work on this.

**What is the motivation or use case for changing this?**
It helps find which part of code can be trimmed saving network bandwidth resulting in overall performance improvement

**How is this beneficial to Lighthouse?**
As this is very front end specific topic with lighthouse being the tool that helps measure the perf score of a page.
It will be beneficial if it points that the specific lines of JavaScript that can be deleted

**Comment by connorjclark** [comment]
Sorry, but this is way too much data to store in a LHR.  Besides, we'd also have to store the code too, and that's wayyyyyy too much data.

This is a job for DevTools. Do you know about the coverage panel?

**Comment by sachin7desai7** [comment]
Thanks @connorjclark .
