### ISSUE TITLE
"Uses deprecated APIs" warning does not provide description or source

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/lighthouse#14233]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://thomasbrodhead.com

### What happened?

When running the Lighthouse (9.6.2), the Best Practices audit throws the "Uses Deprecated APIs" error but does not supply the exact Deprecation/Warning nor the location in the code:

> Deprecation / Warning | Source
> -- | --
> ... | thomasbrodhead.com/:0
> ... | thomasbrodhead.com/:0
> 
![best-practices-audit--deprecation-warning](https://user-images.githubusercontent.com/15718749/180611180-f8dbff48-b65f-4b7c-adbe-a4330d06f804.jpg)

### What did you expect?

Text describing the deprecation, and its source in my site's code.

### What have you tried?

I've tried running the audit in both desktop and mobile mode, and using Standard Navigation as well as Timespan.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.2

### Chrome Version

Version 106.0.5196.0 (Official Build) canary (64-bit)

### OS

Windows 8.1

### Relevant log output

```shell
GENERAL
Uses deprecated APIs 2 warnings found
Deprecated APIs will eventually be removed from the browser. Learn more.
Deprecation / Warning
Source
...
thomasbrodhead.com/:0
...
thomasbrodhead.com/:0
```

**Comment by connorjclark** [comment]
This will be fixed in 10.0. ref #13895
