### ISSUE TITLE
Need .crx file

### ISSUE THREAD

**Issue by smprisco** [GoogleChrome/lighthouse#14246]
In order for my company to install Lighhouse, I need to provide the .crx file. How can I get it?

**Comment by adamraine** [comment]
You shouldn't need a crx file to install Lighthouse. Please see https://github.com/GoogleChrome/lighthouse/blob/master/readme.md.

**Comment by smprisco** [comment]
Unfortunately, I work for the IRS and they do require the crx file

**Comment by adamraine** [comment]
Talk to legal then IDK
