### ISSUE TITLE
Lighthouse not detecting webp version of images and gzip compression

### ISSUE THREAD

**Issue by DanaShelkovnikova** [GoogleChrome/lighthouse#14245]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://taraformula.ae/

### What happened?

After doing a page speed test, we got a very low score. After investigation, we noticed that:

1. Lighthouse gives an error that the pictures are not in webp format, although in the network tab the file type is webp.

![image](https://user-images.githubusercontent.com/69501426/181459431-e5e09153-811a-44e7-b7c7-f95871f9f738.png)

![image](https://user-images.githubusercontent.com/69501426/181459636-bdb1c7fd-b57a-47d3-871a-c962fd71015a.png)

![image](https://user-images.githubusercontent.com/69501426/181459754-d2bb91d2-266f-4b68-884a-38a657de561b.png)

2. Lighthouse also indicates that we need to enable the text compressor for js files, but after checking the network tab we see that it is enabled.

![image](https://user-images.githubusercontent.com/69501426/181459888-e0301b7d-cde2-487b-a171-d9719022ed00.png)

![image](https://user-images.githubusercontent.com/69501426/181460047-f9f5abc4-7911-4503-a981-404b411d7073.png)

```
curl -sSIXGET -HAccept-encoding:gzip https://taraformula.ae/client.8730d70d60a425d11b04.js 
HTTP/2 200 
cache-control: max-age=31557600
content-type: application/javascript
x-debug-info: eyJyZXRyaWVzIjowfQ==
x-platform-server: i-02d59189e8ae15b9f
x-platform-server: i-02d59189e8ae15b9f
x-request-id: 00-170553e259af5fa351038a534f1b73fe-922820ff1c7b9652-00
content-encoding: **gzip**
accept-ranges: bytes
date: Thu, 28 Jul 2022 08:36:17 GMT
age: 173109
x-served-by: cache-lhr6622-LHR, cache-bma1657-BMA
x-cache: HIT, HIT
x-cache-hits: 1, 1
strict-transport-security: max-age=31536000
vary: Accept-Encoding
content-length: 312955
```

```
 curl -sSIXGET -HAccept:image/webp https://taraformula.ae/media/wysiwyg/Global_Mobile_1.jpg?auto=webp&format=pjpg&quality=100
[1] 25521
[2] 25522
[2]+  Done                    format=pjpg
[shcheng@web.us-west-2.prd ~]$ 
[shcheng@web.us-west-2.prd ~]$ HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 284948
Cache-Control: max-age=31536000
Content-Type: image/webp
```

And here is the report link from PageSpeed Insights:
https://pagespeed.web.dev/report?url=https%3A%2F%2Ftaraformula.ae%2F&form_factor=mobile

### What did you expect?

Where might be the problem?

### What have you tried?

-

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools

### Lighthouse Version

DevTools: 9.5.0   Chrome Extension: 100.0.0.0   

### Chrome Version

101.0.4951.64 

### Node Version

-

### OS

Linux

### Relevant log output

```shell
-
```

**Comment by connorjclark** [comment]
Do you get the same results from your webserver if you use the lighthouse user agent string? Issues/mismatches like this are typically because a server decides to respond to Lighthouse differently than real users.

**Comment by connorjclark** [comment]
Let us know if the above didn't point you towards the issue.
