### ISSUE TITLE
PWA Checklist link in DevTools is dead

### ISSUE THREAD

**Issue by davidtimovski** [GoogleChrome/lighthouse#14247]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://compoundinterest.davidtimovski.com/

### What happened?

In the bottom of the PWA section called "ADDITIONAL ITEMS TO MANUALLY CHECK (3)" there's a "PWA Checklist" link that points to a [404](https://developers.google.com/web/progressive-web-apps/checklist?utm_source=lighthouse&utm_medium=devtools).

### What did you expect?

I expected to be redirected to a website with useful information about PWAs.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.1

### Chrome Version

103.0.5060.134

### OS

Windows 11

**Comment by adamraine** [comment]
This has been fixed #14240
