### ISSUE TITLE
Update mobile device preset to match newer devices

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#14256]
https://twitter.com/patrickhulce/status/1554163245937737730

viewport, DPR, UA (but not CPU multiplier)

see also: https://github.com/GoogleChrome/lighthouse/issues/10741#issuecomment-626903508 about DPR. tldr: while lighthouse made some bad calls if our reference device was dpr=3, we (conceivably) fixed that so that shouldn't be a problem anymore.

**Comment by patrickhulce** [comment]
Heh, I was going to file with some supporting evidence if you were lukewarm positive, thank you! :)

**Comment by benschwarz** [comment]
Motorola Moto G Power is a great candidate

**Comment by adamraine** [comment]
Can this be merged into https://github.com/GoogleChrome/lighthouse/issues/12235?

**Comment by connorjclark** [comment]
I feel like our more recent plans have taken precedence over that. @paulirish is that right? Anything from that issue/its doc that you feel we should do / conflicts with our present path of using Motorola Moto G Power?

**Comment by connorjclark** [comment]
#12235 is just network, this is viewport/device, so different issues.

**Comment by connorjclark** [comment]
Moto G Power (2022) 1600x720

[amazon store page](https://www.amazon.com/gp/product/B09SM6GR4B/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1)

window.innerWidth: 412
window.innerHeight: 767
screen.width: 412
screen.height: 915
DPR: 1.75
UA: `Mozilla/5.0 (Linux; Android 11; moto g power (2022)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 Mobile Safari/537.36`

**Comment by connorjclark** [comment]
https://github.com/GoogleChrome/lighthouse/pull/14674 for core, also need to do CDT.

**Comment by connorjclark** [comment]
There's still https://github.com/GoogleChrome/lighthouse/issues/14743 , but this is done now.
