### ISSUE TITLE
Cumulative Layout Shift is too strict

### ISSUE THREAD

**Issue by Whip** [GoogleChrome/lighthouse#14250]
I don't know if I'm completely wrong about this but CLS seems too strict too me. I have this website and I analyzed it on chrome 103.0.5060.134 for performance issues and my CLS comes out to be 0.7. I made a video below that shows this and I'm moving through the timeline to actually show what is shifting.

On Google's pagespeed insights, the calculator suggests you better keep the shifting below 0.2 or you lose a lot of points but if you look at the video it doesn't take a lot to blow through this budget. In my opinion this much shifting would not actually bother any user and either the CLS score should reflect this or pagespeed insights need to rework the calculator.

https://user-images.githubusercontent.com/11595460/182026441-0cbfc129-1493-4798-a0c6-e92e2a830eb0.mp4

**Comment by connorjclark** [comment]
This doesn't seem like a trivial amount of shifting.

**Comment by Whip** [comment]
With all due respect, do you have any market research data that supports this? Or is this your opinion?

**Comment by connorjclark** [comment]
No, I didn't do market research on that shifting example you presented, so this is my opinion. The main text moves around significantly during loading. It may not be an interactive element such that the user is now hitting the wrong thing, but it is still janky!

Anyway, this isn't the place to discuss if CLS is too strict. I'll direct you to https://groups.google.com/a/chromium.org/g/speed-metrics-dev .

**Comment by brendankenny** [comment]
@Whip Lighthouse just measures CLS; it's not the source of how CLS is defined.

As part of Core Web Vitals, https://groups.google.com/g/web-vitals-feedback is probably the better forum to discuss CLS feedback.

You may also want to browse the old issues in https://github.com/WICG/layout-instability/issues/ to see previous discussions on the tradeoffs and goals of measuring layout shifts.

**Comment by Whip** [comment]
I see. Thank you. I was also thinking maybe the score of 0.7 is not the problem, rather Pagespeed insights is too strict saying anything over 0.25 is poor. That suggests that I have nearly 3 times the acceptable layout shift in my example and that sounds ridiculuous.
