### ISSUE TITLE
CRX: show banner/warning about variable results compared to CLI

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1426]
Running LH as the extension can produce different perf results than the CLI. 

Examples:
- https://github.com/GoogleChrome/lighthouse/issues/1417
- https://github.com/GoogleChrome/lighthouse/issues/904
- users can have extensions that interfere with the page, inject scripts, etc. (e.g. `Date.now()` audit)

Should we add a disclaimer to the crx report explaining this? It could also encourage folks to install the CLI.

**Comment by paulirish** [comment]
closing in favor of #8594
