### ISSUE TITLE
main document can be included as an ImageElement

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#14286]
If an element has the style `background: url('')`, the url defaults to that of the main page itself (e.g. on `https://example.com`, that would be equivalent to `background: url('https://example.com')`.

The `ImageElements` gatherer will then happily pick that up as an image, and then any audits that use that image will try to match it to a network record and succeed...because that's just the main document.

Here's [one example report where it happens](https://googlechrome.github.io/lighthouse/viewer/?gist=de1a7e11285293bea797a7ee5ad2c1fe) (check the option to defer the page itself as an offscreen image at `__LIGHTHOUSE_JSON__.audits['offscreen-images'].details.items[2]`).

This seems like it might be a problem in general where the image URL matches an actual network request even if it's an invalid image?

**Comment by adamraine** [comment]
I think this is the same as https://github.com/GoogleChrome/lighthouse/issues/13338

**Comment by brendankenny** [comment]
looks like it
