### ISSUE TITLE
Some deprecated-APIs should not be penalised

### ISSUE THREAD

**Issue by carlosjeurissen** [GoogleChrome/lighthouse#14284]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://periodex.co/

### What happened?

When using the `Expect-CT` header, lighthouse reports this as deprecated API without actually pointing out it's the `Expect-CT` header. This header is penalized.

Then there is the `Feature-Policy` header which lighthouse reports on. Same as the `Expect-CT` header, it doesn't actually point out `Feature-Policy` is the issue.

### What did you expect?

To my understanding `Expect-CT` and `Feature-Policy` (alongside `Permissions-Policy`) can be included to make websites more secure in browsers which don't support the `Permissions-Policy` yet and don't enforce Certificate Transparency for all certificates. Thus, having those headers should not be penalized.

Marked this as "Bug" as it penalizes more secure web apps and lighthouse doesn't point to which specific APIs it sees as troublesome.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.2

**Comment by adamraine** [comment]
What Chrome version are you using? I can repro on Canary (106.0.5241.0) but not stable.

We get our deprecation warnings from Chrome's inspector issues. I suspect these are recently introduced deprecations that we need to pull UI strings for.

**Comment by carlosjeurissen** [comment]
@adamraine Correct, I've used Chrome Canary v106.0.5232.0. Thanks!
