### ISSUE TITLE
Unable to get blocked-url-patterns to work

### ISSUE THREAD

**Issue by jaybytez** [GoogleChrome/lighthouse#14283]
Not sure what I am doing wrong but I have tried many variations of the url patterns and also tried the configuration file and nothing I have done appears to work for blocking specific urls/domains for the lighthouse test:

`lighthouse https://www.test.com/ --view --throttling-method=devtools --blocked-url-patterns=['https://www.googletagmanager.com','https://www.googleadservices.com','https://www.facebook.com']`

Any thoughts on what I am missing here?

**Comment by connorjclark** [comment]
You should be able to pass each value separatly like this:

```
lighthouse https://www.test.com/ --view --throttling-method=devtools --blocked-url-patterns='https://www.googletagmanager.com/' --blocked-url-patterns='https://www.googleadservices.com/'
```

_____

We could also add csv parsing to this property to support `--blocked-url-patterns='https://www.googletagmanager.com/,https://www.googleadservices.com/'`

**Comment by jaybytez** [comment]
Thank you, that worked for me.
