### ISSUE TITLE
manifest `display` property

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#143]
Do we want to suggest or require any specific display property for PWA?

The options, thanks to a [great presentation](https://dev.opera.com/blog/pwa-taipei/) by @brucelawson

### `"display": "standalone"`
![image](https://cloud.githubusercontent.com/assets/39191/14335036/24430a70-fc0d-11e5-95b9-5026c6c8ad72.png)

### `"display": "fullscreen"`
![image](https://cloud.githubusercontent.com/assets/39191/14335025/0839b8ce-fc0d-11e5-93c8-4ea86b6f542a.png)

### `"display": "browser"` (the [default](https://www.w3.org/TR/appmanifest/#dfn-fallback-display-mode))
![image](https://cloud.githubusercontent.com/assets/39191/14335027/123046cc-fc0d-11e5-8b65-22fde872512e.png)

`display: minimal-ui` also exists in the spec, though I'm not sure Chrome supports it.

<hr>

IMO, `standalone` is the preferred UX. (Though I can see uses of `fullscreen`)

Should we require either `standalone` or `fullscreen`, with a strong preference for `standalone`?

wdyt, @owencm @tjsavage?

**Comment by samccone** [comment]
I wonder for apps like moji-brush where I have a bottom menu if full-screen would actually be optimal.

**Comment by PaulKinlan** [comment]
we should be recommending either standalone or fullscreen (anything else should be a warning imo.)  Fullscreen would be frequently used for games, video players etc.

**Comment by paulirish** [comment]
> we should be recommending either standalone or fullscreen (anything else should be a warning imo.) 

1. We could report passively and recommend without affecting your score.
1. We could dock your score and say your work is incomplete without a display prop of either standalone/fullscreen

Preference?

**Comment by paulirish** [comment]
@samccone wanna take this?

**Comment by samccone** [comment]
Sure I can do this.
