### ISSUE TITLE
network requests and preload-lcp-image issues

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#14300]
Went down a couple of rabbit holes in the last few days for `preload-lcp-image` and wanted to record issues I came across before I forget the specifics. Most of these aren't really specific to that audit, though.

- `initiatorPath` length is the request chain length of the LCP image (not including the image). `mainResourceDepth` is similarly the length of the request chain before the main document (not including the main document). Because the `initiatorPath` always has to include the main document, that means it's always at least `mainResourceDepth + 1`, so no images are ever eliminated by the chain length condition:
   https://github.com/GoogleChrome/lighthouse/blob/81689f134b2f3f2c3dc721d2f5b4475fe10bb593/core/audits/preload-lcp-image.js#L60-L61
   (however, I think we can do better than just chain length for the criteria)
- non-images includes in `ImageElements` artifact and used in audits (https://github.com/GoogleChrome/lighthouse/issues/13338)
- redirects on image requests aren't followed and the timing, etc is reported from the 301 (or whatever) request instead. Another job for `image-records`? One [example I was looking at today](https://googlechrome.github.io/lighthouse/viewer/?gist=25764e07a0b5e10c37f8e995e0140783).
- The lantern graph can get confused if frames make the same network requests as each other.

   I haven't looked into if/how this affects the dependency graph in general, but one site had a six-request-long LCP request chain that included the main page and a document redirect from an iframe, and then declined to suggest preloading because the image wasn't from the main frame, even though the LCP event _was_ from the main frame. Turns out the page had an infinite descent of iframes of another page that contained an iframe of the original page (until Chrome cuts it off with an `about:blank` 5 levels deep).

   The dependency graph was using the LCP image request from one of the frames, not the request from the main frame, and so it was being eliminated here:

   https://github.com/GoogleChrome/lighthouse/blob/81689f134b2f3f2c3dc721d2f5b4475fe10bb593/core/audits/preload-lcp-image.js#L62-L63

  [Example report](https://googlechrome.github.io/lighthouse/viewer/?gist=54ec973b333f1d07f2e9edbc1de87295). It's a little flakey (I assume timing is involved with the conflation?), so [artifacts here for easier repro](https://gist.github.com/brendankenny/5134985337ec365a478719f55bbddc41).

added later:
- in certain circumstances Chrome can't track the initiator chain for a request, but the lantern graph [still stitches it to the root request](https://github.com/GoogleChrome/lighthouse/blob/5e6ee16a519616ef40b2a3987869b79338fa1758/core/computed/page-dependency-graph.js#L178-L181) so at least it's still in the graph. One example is a dynamically-loaded image that has `img.loading = 'lazy'` set on it.

   That doesn't make sense to use as a fallback for the `initiatorPath` in `preload-lcp-image`, at least, because whether or not the image was discoverable in the main document is the important part. We should probably double check the LCP request's `initiator` to see if it's empty and not use `initiatorPath` from the lantern graph if so, then...throw an error? Use alternate data? Not sure.

**Comment by connorjclark** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4071474/191579784-28c8c6a7-2cb9-4b07-903f-95b8bb69f245.png">
The initiator path doesn't seem to include the original redirected main doc request, so the way `mainResourceDepth` is calculated to include redirects is faulty. Should we be including the original, redirected request in initiatorPath or should we just use `0` for mainResourceDepth always?

**Comment by brendankenny** [comment]
> *The initiator path doesn't seem to include the original redirected main doc request*

The lantern dependency graph should have the initial redirect chain in general (that's one of the root causes of #8984) Are you talking about [here](https://github.com/GoogleChrome/lighthouse/blob/5e6ee16a519616ef40b2a3987869b79338fa1758/core/computed/page-dependency-graph.js#L409)?

Running `node cli/index.js https://theverge.com --only-audits=preload-lcp-image`, I see 

`mainResource.redirects.map(r => r.url)` -> `https://theverge.com/'`

`initiatorPath.map(n => n.record.url)` -> `['https://www.theverge.com/', 'https://theverge.com/']`

which seems correct.

**Comment by connorjclark** [comment]
Yup. Turns out the initialUrl in the mocked artifacts for preload-lcp-element tests was wrong.
