### ISSUE TITLE
tags-blocking-first-render audit failures

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1431]
Found a few DBW test failures. This is another example where richer smokehouse testing would help (https://github.com/GoogleChrome/lighthouse/issues/964)!

Testing against the dbw_tester.html, we see a few -1s:

<img width="758" alt="screen shot 2017-01-06 at 6 06 34 pm" src="https://cloud.githubusercontent.com/assets/238208/21738504/e1d135d4-d43a-11e6-893c-596c90329173.png">

This is because there are resources in the test page that 404, and therefore this line throws in the gatherer b/c the records don't have a mimetype:

    const isHtml = record._mimeType.indexOf('html') > -1;

---

The other thing that was introduced in https://github.com/GoogleChrome/lighthouse/commit/6fb07ea0aeccef3c90df453d5dfdd8f15f25a773#diff-4766c8512b90da4ff1ec6e67c189e67aR99, is that we now check if the script/stylesheet was initiator by the parser. However, because the stylesheets/scripts in dbw_tester are wrapped in a `<template>` and activated later via script. So their initiator reports as script:

```
url | failed? | mimetype | initiator
http://localhost:8080/dbw_tester.html undefined text/html other
http://localhost:8080/dbw_tester.js undefined application/javascript parser
http://localhost:8080/dbw_partial_a.html undefined text/html script
http://localhost:8080/dbw_tester.css undefined text/css script
http://localhost:8080/dbw_partial_b.html undefined text/html script
http://localhost:8080/dbw_tester.css?delay=true undefined text/css script
```

This one is not an issue with the gatherer per se, but really an issue with how the test page is constructed. https://github.com/GoogleChrome/lighthouse/issues/964 would have helped us caught the errors with the smoketests.

---

@patrickhulce as a result, I'm not sure that https://github.com/GoogleChrome/lighthouse/commit/6fb07ea0aeccef3c90df453d5dfdd8f15f25a773 truly fixed the lazy load case (`<link rel="preload" href="./dbw_tester.css?delay=true" as="style" onload="this.rel = 'stylesheet'">`). It's showing up in the violation list for me:

<img width="607" alt="screen shot 2017-01-06 at 6 41 21 pm" src="https://cloud.githubusercontent.com/assets/238208/21738723/c0252d32-d43f-11e6-9862-8d0b5016c224.png">

This is because of the previous issue. The initiator was `script` because it was wrapped in a `<template>`:

    http://localhost:8080/dbw_tester.css?delay=true undefined text/css script

I'm going to take the first two. @patrickhulce can you look at this last one?

**Comment by patrickhulce** [comment]
Hm strange, this is what I'm seeing on master.
![image](https://cloud.githubusercontent.com/assets/2301202/21775494/36e02f0a-d64b-11e6-9c6a-8c9ad1004269.png)

Good catch on mimeType though thanks for the fix!

**Comment by ebidel** [comment]
Hmm, 1.3.0. Are you sure you're on master? :)

FWIW, I'm also testing without emulation: `npm run fast -- --output=html --output-path=results.html http://localhost:8080/dbw_tester.html`

**Comment by patrickhulce** [comment]
But not always...ran again with no changes or checkouts
![image](https://cloud.githubusercontent.com/assets/2301202/21775709/01b4515c-d64c-11e6-8f04-dcb25b1930f6.png)

**Comment by patrickhulce** [comment]
Haha oops opened the wrong report file on that first one disregard :man_facepalming:

**Comment by patrickhulce** [comment]
The preload link showing up seems to be caused by use of a standard http-server instead of our `static-server.js` that delays assets by 2 seconds that have `delay` in the queryString. Without emulation and delay the sheet loads too quickly for our gatherer to detect that it wasn't there to begin with. @ebidel 's PR should address the other 2 issues

**Comment by ebidel** [comment]
I've added a not in the PR about needing to use `static-server.js` for that `?delay` link to pass.

**Comment by patrickhulce** [comment]
@ebidel safe to close now then?

**Comment by ebidel** [comment]
Yea.
