### ISSUE TITLE
`oopif-requests` flaky on windows

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#14317]
https://github.com/GoogleChrome/lighthouse/runs/8004254136?check_suite_focus=true

I've seen this a few times now.

The player.css seems to be missing entirely.
The iframe request is there but it's marked as `finished: false`

**Comment by MAZK69** [comment]
Good day there...
Actually 17 hours ago to be exact I came across this...Can you check it out?
https://web.mit.edu/~klmitch/Sipb/devel/src/bogofilter-0.10.2/tests/bogofilter/inputs/good.mbx

Thanks in advance
