### ISSUE TITLE
report: line breaks in the middle of the 'sec' unit in opportunities

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#14326]
opportunity display text started breaking mid-unit at some point

<img width="252" alt="The opportunity section of a lighthouse report, showing durations with a line break in between the s and the e in the unit 'sec'" src="https://user-images.githubusercontent.com/316891/187251095-7817e7d9-e171-4fd2-800f-a6c2d29f90b1.png">

This was sort of due to #13830. There's no problem in the 9.x branch, but that's because the times used to be e.g. `1.13 s` instead of the current `1.13 sec`, and the longer unit is getting wrapped.

<img width="264" alt="The opportunity section of an older lighthouse report, showing durations with just the unit 's'" src="https://user-images.githubusercontent.com/316891/187251741-41e60889-3ec7-49f9-a1bf-1ca949119935.png">

**Comment by adamraine** [comment]
`white-space: nowrap` should do the trick
