### ISSUE TITLE
Add total time to output

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/lighthouse#1434]
I mentioned to @ebidel that it might be good to have lighthouse output the total time it took to run so if you're adding a new feature you can quickly see the delta.

**Comment by ebidel** [comment]
Rob, would you want this in the extension, the CLI, or both? I'm thinking it would be most useful in the CLI. If we were to add it to the extension, it would have to somehow surface in the report.

**Comment by robdodson** [comment]
In the CLI

**Comment by wardpeet** [comment]
Are you talking about how long the process took? (`time lighthouse https://www.airhorner.com`) Or rather how long the the Runner ran? (from start until right before report is being built?)

**Comment by robdodson** [comment]
I guess the runner itself? I just want to know, if I add N number of new
audits, how much slower is the Lighthouse CLI

**Comment by ebidel** [comment]
One thing I just though of: If it were part of the report, CI integrations could use that data over time, graph it, etc. It's not immediately obvious why that would be useful, but people find uses for everything!

**Comment by wardpeet** [comment]
we could add an extra line to the output to show how long an audit took. In the json output they can reduce all values into the sum of all audits and do whatever they want with it?

**Comment by brendankenny** [comment]
fixed in #2241
