### ISSUE TITLE
fix CI unit tests on Node 16.x and 18

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#14345]
- Node 16 is currently fixed at 16.17 in #14333
- We've tried and failed (OOM) to get unit+c8 running on Node 18 in #13874 and #14015

-------

## our node version policy:

 we don't support TWO maintenance releases. so when an [LTS](https://nodejs.org/en/about/releases/) newly enters 'maintenance' we drop the older one

eg

![image](https://user-images.githubusercontent.com/39191/189759604-0383d6e6-e34f-4689-aa6a-c44d70ea8f5c.png)

Circa Oct 2022, when 16 enters maintenance we drop all support for 14.

**Comment by adamraine** [comment]
The node 16 thing is currently blocked on https://github.com/testdouble/testdouble.js/issues/498

**Comment by adamraine** [comment]
Is there anything left to do here?

**Comment by brendankenny** [comment]
nope!
