### ISSUE TITLE
AdSense lowers Lighthouse score to 33

### ISSUE THREAD

**Issue by userofit123** [GoogleChrome/lighthouse#14382]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://divuni.com

### What happened?

With the AdSense code on the site, my mobile score is on average at 33.
Removing the AdSense code causes the score to go up to 76-80.

The AdSense code has the biggest toll on the site. It loads images that are not optimized (not next-gen formats), fonts that do not have the display swap setting, and a lot of javascript.

### What did you expect?

I expect that either all of the scripts, fonts, and images that are included and loaded through AdSense to be optimized, or for the site to not get a low score due to their Googles own code.

### What have you tried?

I have researched for the past few days and have not found anything that actually fixes these issues.

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools, WebPageTest

### Lighthouse Version

9.6.6

**Comment by connorjclark** [comment]
We can't do anything about ad sense here...

But you may find this helpful 
https://developers.google.com/publisher-ads-audits
