### ISSUE TITLE
LCP Calculation Issue

### ISSUE THREAD

**Issue by murali-krishnamoorthy** [GoogleChrome/lighthouse#14381]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.thermofisher.com/search/browse/category/us/en/90111022/petri+dishes

### What happened?

Hi PSI Team

This is an issue around PSI showing higher LCP .

I ran test against PSI API to measure mobile score using the API . 
**Here is URL** 
https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://www.thermofisher.com/search/browse/category/us/en/90111022/petri+dishes&key=<<api-key>>&strategy=mobile&category=performance

In the attached file [PSI LCP Bug.txt](https://github.com/GoogleChrome/lighthouse/files/9540567/PSI.LCP.Bug.txt)
, if you look at the "screenshot-thumbnails.details.items" section at 2899 seconds the above the fold content is loaded with the LCP image. 

PSI shows LCP of 7.3 instead of around 2.9 seconds.

In fact the on the same array the image at 7473 seconds is in fact the very same screenshot with no changes that is captured on 2899 seconds . 

I ran a similar test on webpagetest.org just to compare this with another tool and numbers closely match around the 3 seconds expectation. 
https://www.webpagetest.org/result/220909_BiDc1A_27K/

### What did you expect?

I expect the LCP to be around 3 seconds instead of around 7.5 seconds PSI has. 

### What have you tried?

Attached JSON from PSI and also ran similar test on webpagetest.org and attached results. 

### How were you running Lighthouse?

web.dev, WebPageTest, Other

### Lighthouse Version

9.6.6

### Chrome Version

HeadlessChrome/102.0.5005.115

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me

**Comment by murali-krishnamoorthy** [comment]
Hi @adamraine 
I see this is closed with general comment  , but i am not questioning why the score is low . i am questioning why PSI did not take the Lower LCP Number within the test  as the above the fold content image between 2.8 seconds to 7.5 seconds where almost the same. I have provided an example of the json i received as response from the api

**Comment by murali-krishnamoorthy** [comment]
how can i reopen this case

**Comment by adamraine** [comment]
This is working as intended.

By default, Lighthouse will load the page without any throttling and then simulate what the page load would have been like under different network conditions.

The screenshots you see represent the unthrottled page load, while the LCP value is affected by throttling.

**Comment by murali-krishnamoorthy** [comment]
hi @adamraine  thanks for the answer , its bit misleading ? When i run a test , i would expect all the metrics and additional data ( e.g images etc )  to support the reported number.  

Even with throttled conditions  i have run several test with chrome , wpt and the number dont match PSI. 

Not to bug you i am trying to get to the root cause of this , i was using the json and data it provides to troubleshoot these issues and since you mentioned those metrics might not support the reported LCP number ,  If you dont mind would you able to tell what resource is delaying the LCP

**Comment by adamraine** [comment]
Please read our docs on [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) and [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).

The results may be closer to WPT if you use [applied throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md#devtools-lighthouse-panel-throttling) (also known as DevTools throttling)

> If you dont mind would you able to tell what resource is delaying the LCP

It could be a variety of resources delaying LCP. The LCP of the page is an image so slower network conditions could increase the time it takes to download the image.

**Comment by murali-krishnamoorthy** [comment]
Hi @adamraine  if you look at the JSON i sent you the LCP image loaded in 1.8 seconds and all the render blocking css and js loaded around 2.5 seconds .  something is definitely not adding up . Would you be okay for 15 mins call and i can explain the issue

**Comment by murali-krishnamoorthy** [comment]
Here is the url of the page "https://www.thermofisher.com/search/browse/category/us/en/90111022/petri+dishes" would you able to run a test and tell me why its 7.5 seconds , based on the data i get from the response , i dont see a reason why LCP is so high or let me know if you have 15 mins and i can walk through the issue in a call
