### ISSUE TITLE
10.0 release

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#14397]
~Let's use this issue to draft some short explainers for various big changes we are interested in highlighting.~

doc: https://docs.google.com/document/d/1XYTnL4lJBT7xZZy5mIo9Is9sDNMO4hZcBVRQxkcI8Pw/edit?usp=sharing

**Comment by adamraine** [comment]
(some drafting)

## New Config Format

Post-10.0 Lighthouse will not support defining `passes` on the config by default. If you need to load the page multiple times, we recommend using a [user flow](https://github.com/GoogleChrome/lighthouse/blob/main/docs/user-flows.md). Please see our [config docs](https://github.com/GoogleChrome/lighthouse/blob/main/docs/configuration.md#legacy-configs) for instructions on how to convert to the new config format.

## New Gatherer Interface

The new Lighthouse gatherers are designed to work with the new Lighthouse modes in [user flows](https://github.com/GoogleChrome/lighthouse/blob/main/docs/user-flows.md). They are backwards compatible with Legacy navigation mode, however any old gatherers that implement `beforePass` / `afterPass` should be converted to the new format:

- `startInstrumentation`
	- Used to install any instrumentation that analyzes the page over a period of time.
	- Runs in navigation and timespan mode, but not snapshot mode.
- `stopInstrumentation`
	- Used to uninstall any instrumentation that analyzes the page over a period of time.
	- Runs in navigation and timespan mode, but not snapshot mode.
- `getArtifact`
	- Used to analyze the page at the end of the gathering phase, and return the final artifact.
	- Always runs in all three modes.

Please see the [base gather](https://github.com/GoogleChrome/lighthouse/blob/main/core/gather/base-gatherer.js) and our [example custom gather](https://github.com/GoogleChrome/lighthouse/blob/main/docs/recipes/custom-gatherer-puppeteer/custom-gatherer.js) for more info.

**Comment by connorjclark** [comment]
Let's use a google doc.
