### ISSUE TITLE
Remove PWA check "Provides a valid apple-touch-icon"

### ISSUE THREAD

**Issue by strelec** [GoogleChrome/lighthouse#14395]
**Feature request summary**

Safari has supported PWA icons declared in the manifest, for a while now.

Let's remove the "Provides a valid apple-touch-icon" check.
Or, alternatively, actively suggest removal, as now we have standard way to do it.

**What is the motivation or use case for changing this?**

This check was too strict in the first place, as not everyone cares about or targets iOS users.
Moreover, the Apple icon requires specific format (PNG) and specific dimensions, which is more work for developers.

The `apple-touch-icon` also takes precedence, and I do not think it supports maskable icons.

**How is this beneficial to Lighthouse?**

Less code to maintain in Lighthouse.
Shorter and easier to comply-with checks.

**Comment by adamraine** [comment]
#14243 to be released in v10.0
