### ISSUE TITLE
Lighthouse to parse and summarize raw trace logs

### ISSUE THREAD

**Issue by goelayu** [GoogleChrome/lighthouse#14401]
There are enough questions posted here about lighthouse as a trace processor, so apologies if this comes across as a repetition. 

Instead of trying to parse trace logs and run audits on them, I want to summarize the logs to output the timing information per category (rendering, scripting etc) and per event (compilation, GC, evaluation etc). 

To some extent similar to what https://github.com/saucelabs/tracelib does, however it doesn't give information on an `event` level, and extending the tool to do that doesn't seem trivial. 

In similar spirit, if there is another tool out there better suited for this purpose, do kindly point me to that. Thanks

**Comment by connorjclark** [comment]
You can use this (standalone) library: https://github.com/GoogleChrome/lighthouse/blob/master/core/lib/tracehouse/trace-processor.js

Take a look at how our mainthread work breakdown audit aggregates by task category (aka group id): https://github.com/GoogleChrome/lighthouse/blob/0ce84c0feb444964dd8fe1555230e1efd785993d/core/audits/mainthread-work-breakdown.js#L89-L103

**Comment by goelayu** [comment]
Great, thanks a lot. 

For anyone else trying to reproduce the same result, the high level logic is:

1. Parse the raw trace using the trace-processor library
2. Convert the parsed trace to tasks object using the MainThreadTasks library (https://github.com/GoogleChrome/lighthouse/blob/master/core/test/lib/tracehouse/main-thread-tasks-test.js#L34-L35)
3. Finally use the above code snippet ([lighthouse/core/audits/mainthread-work-breakdown.js](https://github.com/GoogleChrome/lighthouse/blob/0ce84c0feb444964dd8fe1555230e1efd785993d/core/audits/mainthread-work-breakdown.js#L89-L103)) to breakdown tasks by category.

**Comment by connorjclark** [comment]
You may find this example useful; how to run Lighthouse audits without explicitly running Lighthouse (you just manually create/provide the artifacts) https://gist.github.com/connorjclark/d4555ad90ae5b5ecf793ad2d46ca52db

**Comment by goelayu** [comment]
That's really helpful. Thanks. Will try some of those modules out.

**Comment by goelayu** [comment]
Hi @connorjclark, I'm reopening this issue, since I couldn't figure out a way to parse the trace when it contains tracing data for multiple frames? 


For e.g., in the below screenshot, the browser captures the trace for all the in-process frames on the page. However, when I parse the trace using the above lighthouse library, it only generates the tasks (and the final breakdown) for the main frame. 

![Screen Shot 2022-09-25 at 9 18 23 PM](https://user-images.githubusercontent.com/31916840/192176036-c6d9e6e0-cbb7-43dd-a9ef-2146f7e9f475.png)

**Comment by brendankenny** [comment]
@goelayu Not sure if this is still helpful several months later, but that's correct, it's designed for one frame at a time. You can use any frame as input, though, so you can iterate over the frames and call the method repeatedly.

Here's an example calling the same MainThreadTasks breakdown but for whatever frame included a user interaction:

https://github.com/GoogleChrome/lighthouse/blob/1826c75036a3f1a6ff98e3a150ca54f5d761c99f/core/audits/work-during-interaction.js#L131-L141

**Comment by goelayu** [comment]
@brendankenny This is helpful, thanks a lot. I haven't toyed with these scripts in a while, but will test this out and report back if I run into any other issue.
