### ISSUE TITLE
Could you change the main branch name to "main"?

### ISSUE THREAD

**Issue by MirandaBrawnerSavannah** [GoogleChrome/lighthouse#14408]
Recently, many companies have been moving away from the use of the word "master" in technology because of the connotations of slavery. When it comes to the root branch that other branches merge into, the new standard is to use "main" instead of "master". We've been switching over our code base in the last few years. At the company I work at, there was one place where we wanted to link to some documentation here at Lighthouse, but it is a problem because of the branch name. Is that something you can fix?

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/14408
