### ISSUE TITLE
Lighthouse complains with cloned graph missing node 

### ISSUE THREAD

**Issue by TheInvoker** [GoogleChrome/lighthouse#14417]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https;//example.com

### What happened?

I get `cloned graph missing node` error in diagnostics. See image below.

I created a vite/vue3/vuetify/vue router/pinia, project.

My html is 

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/png" href="/favicon.png" />
    <link rel="apple-touch-icon" href="/favicon.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="theme-color" content="#6E2D91">
    <meta name="description" content="Sample Web App">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
    
    <link rel="stylesheet" href="/assets/index.4a576584.css">
  </head>
  <body>
    <div id="app"></div>
    <script type="module" crossorigin="" src="/assets/index.79acedba.js" defer async></script>
  </body>
</html>
```

[error](https://i.stack.imgur.com/PCh9V.png)

### What did you expect?

No error in lighthouse.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.2

### Chrome Version

106

**Comment by connorjclark** [comment]
We're likely going to need an actual, full working example to reproduce this. Can you provide one?

**Comment by brendankenny** [comment]
Going to close since we can't debug without an example with which to reproduce the issue. If you're still seeing the issue, please comment and we can re-open.
