### ISSUE TITLE
Too much precision on the DOM size audit

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#14422]
We shouldn't need the `.0`. These values will always be integers

<img width="787" alt="Screen Shot 2022-10-04 at 12 46 14 PM" src="https://user-images.githubusercontent.com/6752989/193911694-2b3affc0-615d-4240-968a-e3ba30e3704c.png">

**Comment by shogohida** [comment]
Hi @adamraine, I wanted to contribute to lighthouse so I decided to work on this issue.

I created a pull request so please review it when you have time!
https://github.com/GoogleChrome/lighthouse/pull/14479
