### ISSUE TITLE
`th-has-data-cells` accessibility audit always shows as passing even in error scenarios

### ISSUE THREAD

**Issue by thibaudcolas** [GoogleChrome/lighthouse#14438]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- ~~[X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).~~

### URL

https://accessibility-experiments-90d5b5.glitch.me/lighthouse-th-has-data-cells-audit/index.html

### What happened?

This is the same issue as #14354, but for the `th-has-data-cells` audit. I’m expecting the problem and solution will be the same, but I haven’t actually checked, hence why I’m opening this separately.

The `th-has-data-cells` audit based on Axe’s [th-has-data-cells rule](https://dequeuniversity.com/rules/axe/4.1/th-has-data-cells) always shows as passing when it’s applicable, even when there are issues on the page that Axe itself detects.

Sample page: <https://accessibility-experiments-90d5b5.glitch.me/lighthouse-th-has-data-cells-audit/index.html>

<details>

<summary>Lighthouse results for th-has-data-cells on this page (JSON export)</summary>

```json
"th-has-data-cells": {
      "id": "th-has-data-cells",
      "title": "`<th>` elements and elements with `[role=\"columnheader\"/\"rowheader\"]` have data cells they describe.",
      "description": "Screen readers have features to make navigating tables easier. Ensuring table headers always refer to some set of cells may improve the experience for screen reader users. [Learn more](https://web.dev/th-has-data-cells/).",
      "score": 1,
      "scoreDisplayMode": "binary",
      "details": {
        "type": "table",
        "headings": [],
        "items": []
      }
    },
```

</details>

<details>

<summary>Axe CLI results for the same page</summary>

Command:

```bash
axe -r th-has-data-cells https://accessibility-experiments-90d5b5.glitch.me/lighthouse-th-has-data-cells-audit/index.html --save th-has-data-cells.json && cat th-has-data-cells.json
```

Output:

```json
[
  {
    "testEngine": {
      "name": "axe-core",
      "version": "4.4.3"
    },
    "testRunner": {
      "name": "axe"
    },
    "testEnvironment": {
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/105.0.5195.125 Safari/537.36",
      "windowWidth": 800,
      "windowHeight": 600,
      "orientationAngle": 0,
      "orientationType": "landscape-primary"
    },
    "timestamp": "2022-10-06T23:22:43.669Z",
    "url": "https://accessibility-experiments-90d5b5.glitch.me/lighthouse-th-has-data-cells-audit/index.html",
    "toolOptions": {
      "runOnly": {
        "type": "rule",
        "values": [
          "th-has-data-cells"
        ]
      },
      "reporter": "v1"
    },
    "inapplicable": [],
    "passes": [],
    "incomplete": [
      {
        "id": "th-has-data-cells",
        "impact": "serious",
        "tags": [
          "cat.tables",
          "wcag2a",
          "wcag131",
          "section508",
          "section508.22.g"
        ],
        "description": "Ensure that <th> elements and elements with role=columnheader/rowheader have data cells they describe",
        "help": "Table headers in a data table must refer to data cells",
        "helpUrl": "https://dequeuniversity.com/rules/axe/4.4/th-has-data-cells?application=webdriverjs",
        "nodes": [
          {
            "any": [],
            "all": [
              {
                "id": "th-has-data-cells",
                "data": null,
                "relatedNodes": [
                  {
                    "html": "<th scope=\"row\">City</th>",
                    "target": [
                      "th:nth-child(3)"
                    ]
                  }
                ],
                "impact": "serious",
                "message": "Table data cells are missing or empty"
              }
            ],
            "none": [],
            "impact": "serious",
            "html": "<table>",
            "target": [
              "table"
            ],
            "failureSummary": "Fix all of the following:\n  Table data cells are missing or empty"
          }
        ]
      }
    ],
    "violations": []
  }
]
```

</details>

### What did you expect?

Lighthouse’s results for `th-has-data-cells` should be consistent with those of Axe. In this instance, Axe reports `th-has-data-cells` as "incomplete", so it shouldn’t be a pass with Lighthouse. I would have expected either a "Additional items to manually check", or an error.

### What have you tried?

I put the demo page together based on Axe’s [bad example in their docs](https://dequeuniversity.com/rules/axe/4.1/th-has-data-cells). This seems like the exact same issue as #14354 as far as I can tell so I didn’t investigate further.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.6

### Chrome Version

108

### OS

Mac

**Comment by adamraine** [comment]
Merging into https://github.com/GoogleChrome/lighthouse/issues/14354
