### ISSUE TITLE
Selecting snapshot for an accessibility audit does the audit and then still reloads the page, losing state

### ISSUE THREAD

**Issue by slauriat** [GoogleChrome/lighthouse#14450]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

google.com

### What happened?

1. Type something into the search box to have the autocomplete pop up
2. Open Lighthouse and select "Snapshot", "Desktop", and only "Accessibility"
3. Run Analyze page state

The analysis runs and then the page refreshes.

### What did you expect?

From [this previous bug](https://github.com/GoogleChrome/lighthouse/issues/1769) about an option to not refresh, it should not refresh and lose the state. I see the dependency noted, so maybe that option should go away until snapshot ability works? Not sure if a regression or a not-yet-fixed issue.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.2

### Chrome Version

106.0.5249.119

### OS

Mac

**Comment by adamraine** [comment]
I agree we shouldn't reload the page for snapshot & timespan modes in DevTools.

**Comment by paulirish** [comment]
Fixed by https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3957614

also,,, this is convenient: 
<img width="879" alt="image" src="https://user-images.githubusercontent.com/39191/196802000-67ab4cea-2ffc-458e-b531-624fb1d945af.png">
