### ISSUE TITLE
how to send the generated reports through mail automatically after running the scripts in typescript

### ISSUE THREAD

**Issue by Yoga-H** [GoogleChrome/lighthouse#14469]
i am executing my lighthouse using puppeteer. I want the reports automatically to email/slack to the team  once after execution.
Kindly help me on how to do it.

// This file is to run lighthouse for the mentioned URLs to audit the CLS and LCP values

const fs = require("fs");
const lighthouse = require("lighthouse");
const puppeteer = require("puppeteer");
const chromeLauncher = require("chrome-launcher");
const reportGenerator = require("lighthouse/report/generator/report-generator");
const request = require("request");
const util = require("util");
const { promisify } = require("util");
const { isPromise } = require("util/types");
const { time } = require("console");
const { syncBuiltinESMExports } = require("module");

const prodURLs = {
  url1: "https://google.com",
  url2: "https://github.com",
  
};

const options = {
  logLevel: "info",
  disableDeviceEmulation: true,
  chromeFlags: ["--disable-mobile-emulation"],
  port: process.env.PORT,
};
const configs = {
  extends: "lighthouse:default",
  settings: {
    onlyAudits: ["largest-contentful-paint", "cumulative-layout-shift"],
  },
};
var today = new Date();

async function lighthouseFromPuppeteer(option = options, config = configs) {
  // Launch chrome using chrome-launcher
  for (const [key, url] of Object.entries(prodURLs)) {
    var date =
      today.getFullYear() +
      "-" +
      (today.getMonth() + 1) +
      "-" +
      today.getDate();
    var time =
      today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
    const chrome = await chromeLauncher.launch(option);
    option.port = chrome.port;

    // Connect chrome-launcher to puppeteer
    const resp = await util.promisify(request)(
      `http://localhost:${option.port}/json/version`
    );
    const { webSocketDebuggerUrl } = JSON.parse(resp.body);
    const browser = await puppeteer.connect({
      browserWSEndpoint: webSocketDebuggerUrl,
    });
    //if (index > 0) await page.waitForTimeout(60 * 1000);
    // Run Lighthouse
    const { lhr } = await lighthouse(url, option, config);
    await browser.disconnect();
    await chrome.kill();

    const path = `lh_reports/CLS_LCP_${date}_${time}`;
    const html = reportGenerator.generateReport(lhr, "html");
    fs.mkdir(path, function () {
      fs.writeFileSync(`./${path}/${key}.html`, html);
    });
  }
}
lighthouseFromPuppeteer();

**Comment by adamraine** [comment]
Lighthouse HTML reports should be pretty easy to pack into an email with other libraries, but this feature is outside the scope of the project.

If you are interested in sending emails via JS, this is one option I found via a quick google search:
https://nodemailer.com/about/

**Comment by connorjclark** [comment]
https://github.com/coursehero/slacktee
