### ISSUE TITLE
Lighthouse not rendering details for Expect-CT deprecated APIs

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#14467]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://github.com/

### What happened?

Run Lighthouse and look at the best practices score.

## Latest main + Chrome 109

![Screenshot 2022-10-25 at 11 40 47](https://user-images.githubusercontent.com/1303660/197752741-2f94e6b5-e527-4cbd-87af-b2ceb15170fd.png)

After expanding it shows this message:

> "The `Expect-CT` header is deprecated and will be removed. Chrome requires Certificate Transparency for all publicly trusted certificates issued after April 30, 2018."

## DevTools in Chrome 106

![Screenshot 2022-10-25 at 11 41 19](https://user-images.githubusercontent.com/1303660/197752830-7e38ea0f-12a8-42c2-aee1-bf2d084d0793.png)

### What did you expect?

The error message should show right away without additional user interaction.

### How were you running Lighthouse?

CLI, Chrome DevTools

### Lighthouse Version

main, 9.6.2

### Chrome Version

106, 109

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/14456

This is fixed but unreleased, the next release will fix it.
