### ISSUE TITLE
Support for iOS

### ISSUE THREAD

**Issue by pedro93** [GoogleChrome/lighthouse#1447]
Is there any kind of support for iOS devices? 
I know of the existence of https://github.com/google/ios-webkit-debug-proxy and https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter that enable the chrome dev tools to inspect the information coming from Safari. 

I have been trying to without success to bridge the communication similarly to android remote debugging.

Is this a fruitless effort, and if so why (I would assume protocol incompatibilities between Safari and [Chrome's protocol](https://developer.chrome.com/devtools/docs/debugger-protocol))?

**Comment by wardpeet** [comment]
to be honest I have no idea but I can have a look to be sure.

But probably @paulirish knows the answer.

**Comment by brendankenny** [comment]
could be duplicated into #2406
