### ISSUE TITLE
Name the deprecated apis that are warned for

### ISSUE THREAD

**Issue by phihochzwei** [GoogleChrome/lighthouse#14478]
**Feature request summary**
When warning about the use of deprecated APIs in the best practice section, it would be really great to know WHICH apis you are warning of

**What is the motivation or use case for changing this?**
In our actual case, we get the warning in the SSR response of an angular project. And the warning simply does not give any information about what the actual problem is

**How is this beneficial to Lighthouse?**
Well, since we all love the tool, it would be great if it gets better :)

**Comment by SmartEliProgrammer** [comment]
Hey, phihochzwei. These are the warnings for the Code.
49 - chromium-browser --user-data-dir=$TMP_PROFILE_DIR
