### ISSUE TITLE
TTFB increases but LCP does not.

### ISSUE THREAD

**Issue by minami-takuya** [GoogleChrome/lighthouse#14473]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://

### What happened?

We have found that pages on our site are slow to respond under certain conditions.
At that time, LightHouse's server response time(TTFB) values increased from normal, but LCP values did not.

normal (TTFB 0.88 LCP 2.3
![スクリーンショット 2022-10-25 10 29 29](https://user-images.githubusercontent.com/49505490/198445106-9b01105e-c9a3-4a72-981f-aae46ba2daa3.png)

when TTFB slowed ( TTFB 3.77 LCP 2.4

![スクリーンショット 2022-10-25 10 26 43](https://user-images.githubusercontent.com/49505490/198453309-466db52b-067d-4bf5-9943-c98232467910.png)

### What did you expect?

LCP also includes server response time, which should also increase.
Is this understanding incorrect?

### What have you tried?

I have tried it on both node and chrome.
Both showed similar results.

### How were you running Lighthouse?

CLI, node

### Lighthouse Version

9.6.7

### Node Version

18.9.1

### OS

node: AmazonLinux2, chrome: Mac

**Comment by adamraine** [comment]
Merging into https://github.com/GoogleChrome/lighthouse/issues/13296
