### ISSUE TITLE
Adopt handlebars precompiled templates

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1448]
Currently we browserify all of handlebars for our extension and report-viewer builds. 
It would make more sense to adopt precompiled templates, which are much smaller and simpler to run: http://handlebarsjs.com/precompilation.html

https://metabroadcast.com/blog/precompilation-of-templates-with-handlebars

In that case, we'd require in the precomplied template + runtime rather than the original template file and all of `handlebars`. 
https://www.npmjs.com/package/gulp-handlebars

This will require some experimenting. Open for anyone to investigate.  ([For example](https://github.com/lazd/gulp-handlebars/pull/53)).. big plus if you've worked with precompiled handlebars before. ;)

**Comment by brendankenny** [comment]
this was closed in #1752
