### ISSUE TITLE
Page contains a CSP defined in a <meta> tag, and in a HTTP header

### ISSUE THREAD

**Issue by craigfrancis** [GoogleChrome/lighthouse#14489]
Ref metaTagMessage "The page contains a CSP defined in a <meta> tag. Consider defining the CSP in an HTTP header if you can."

This shouldn't be an error if there is also a CSP HTTP header, because you can define [multiple Content Security Policies](https://www.w3.org/TR/CSP3/#multiple-policies), and each one will be enforced.

For example, I will often define a strict CSP in a HTTP header; then in the HTML `<head>`, I will define any `<script>` tags I need, then add a `<meta>` CSP (a second policy), which ensures no other JavaScript is defined (e.g. evil attacker finding a way to include a JavaScript file, that's on the allow-list, but should not be run on this page).

```html
<meta http-equiv="Content-Security-Policy" content="script-src 'none'" /> <!-- No scripts after this -->
```

---

I've not tried this, but I assume [/core/audits/csp-xss.js:143](https://github.com/GoogleChrome/lighthouse/blob/4546e0594dde0fefe7b3749a63bd8cab07771131/core/audits/csp-xss.js#L143) could be changed with:

```diff
- if (cspMetaTags.length) {
+ if (cspMetaTags.length > 0 && cspHeaders.length == 0) {
```

**Comment by connorjclark** [comment]
Suggested change looks good to me.

as an alternative... @adamraine should we try running the csp evaluator on the header CSPs + the all the CPSs, and warn only if there's a gap?

**Comment by adamraine** [comment]
@craigfrancis your suggestion seems reasonable for the use case you describe. There is still possible vulnerabilities if the header CSP is *not* strict. I think @connorjclark's suggestion would be reasonable to resolve this issue.

**Comment by craigfrancis** [comment]
Thanks for creating a PR @adamraine (and so quickly).

You're right, having the extra checks is a really good idea.
