### ISSUE TITLE
Include emulated screen dimensions and deviceScaleFactor in report meta block

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#14498]
Could be added to the [`devices` tooltip](https://github.com/GoogleChrome/lighthouse/blob/38cce6a863b3452cee3b28e97a50df3031dfcb34/report/renderer/report-renderer.js#L138-L140) alongside CPU/Memory power, etc
![current Lighthouse meta information with device information in a tooltip](https://user-images.githubusercontent.com/316891/200014647-448642ea-60e7-43b9-952c-9caf33275015.png)

request from https://twitter.com/nhoizey/status/1588534641891352576

cc @tunetheweb

**Comment by nhoizey** [comment]
Great, thanks! 🙏
