### ISSUE TITLE
Performance difference between extension and cli report

### ISSUE THREAD

**Issue by pedro93** [GoogleChrome/lighthouse#1449]
Hi 
I was trying out both the lighthouse extension and NodeJS Cli and noticed that for the same external URL, the reports vary greatly between the two. I made sure to clean caches and be logged out of my account when testing the extension on all executions.

The URL in question was https://github.com

### Extension output:
![screen shot 2017-01-11 at 16 42 59](https://cloud.githubusercontent.com/assets/3718654/21857472/772cdd50-d81d-11e6-9e8c-aaad7f29f51e.png)
![screen shot 2017-01-11 at 16 43 08](https://cloud.githubusercontent.com/assets/3718654/21857473/774b2a6c-d81d-11e6-9e42-e88699b46abe.png)

### Cli output:
![screen shot 2017-01-11 at 16 45 22](https://cloud.githubusercontent.com/assets/3718654/21857487/8a70872c-d81d-11e6-8eb7-737cbf846299.png)
![screen shot 2017-01-11 at 16 44 21](https://cloud.githubusercontent.com/assets/3718654/21857488/8a715f4e-d81d-11e6-8e3c-868e1c3d4a50.png)

Note that reports made by the cli and extensions were consistent amongst themselves, I ran 10 tests on each time, these examples are merely representative, no network connections were changed in the process, nor was any flag/option explicitly used on either case.

### Hardware/Software information:
Macbook Pro (Retina 13" Early 2015)
OS: OS X El Captain v.10.11.6
Chrome: 55.0.2883.95 (64-bit)
Node: 6.9.4
Lighthouse: 1.4.1

Is this a matter of varying execution configurations or a potential bug?

**Comment by patrickhulce** [comment]
It's a known issue that the results are different and we have an issue open to warn about that (see #1426), but it's interesting that your CLI results are much *less* performant than the CRX, counter to previous issues that suggest other extensions, scripts, etc interfere only when using the extension... @ebidel any other reports of CLI producing consistently less performant results?

**Comment by brendankenny** [comment]
There are some things Chrome does at startup that can drain performance from whatever page we're testing. #1416 helps disable a few more of those in the CLI and will be in the next release.

An interesting test to see how well we're eliminating these things would be to run `chrome-debug` to launch Chrome, let it settle for a minute or two (maybe even load an unrelated page and let it settle there, e.g. https://example.com), then see how the numbers compare.

**Comment by ebidel** [comment]
That's a good idea @brendankenny. If it turns out fruitful, we should introduce that slight delay into the CLI. I'm also hopeful #1416 will help consistency.

**Comment by pedro93** [comment]
Thank you @patrickhulce, @brendankenny and @ebidel for the input. 

With regards to using chrome-debug, is there any way I can direct lighthouse to use it and not the default chrome installation in the computer?

I have no problem running the same tests tomorrow with this change and report back.

**Comment by brendankenny** [comment]
`chrome-debug` will do that for you.

By default Lighthouse will connect to any Chrome listening for remote debugging connections before launching its own instance of Chrome. `chrome-debug` (or `npm run chrome` if you're running from a git checkout) will launch Chrome with the right flags for Lighthouse to connect to, so LH will connect to that Chrome won't launch another instance.

**Comment by paulirish** [comment]
@pedro93 thanks VERY much for reporting this. this is the kind of report we really appreciate. 

The chrome-debug workaround might help. Give it a go and see if the numbers are closer.

Also, it's worthwhile to see how much the numbers change when you do multiple runs on the same setup. Network conditions will likely have a +- 300ms variability on things, but hopefully its not changing by more than 500ms each run.

**Comment by pedro93** [comment]
I've just tested the cli with ```chrome-debug``` as suggested and the output is similar to what I previously got.  I cleared all browsing information between runs, reloaded https://example.com, let the browser settle for 2+ minutes.

![screen shot 2017-01-12 at 10 58 09](https://cloud.githubusercontent.com/assets/3718654/21887341/72fe6f06-d8b7-11e6-9a83-59d8ca355c13.png)

![screen shot 2017-01-12 at 10 46 24](https://cloud.githubusercontent.com/assets/3718654/21887345/7621f982-d8b7-11e6-9e38-ea21e52b1817.png)

![screen shot 2017-01-12 at 10 18 37](https://cloud.githubusercontent.com/assets/3718654/21887347/78c5ab3e-d8b7-11e6-8f5c-8831719e4c22.png)

Curiously, out of the 10 executions, only 6 gave me performance profiling data (not sure if it is relevant), which may mean that audits I'm evaluating timeout too soon?

The other four showed the following:

![screen shot 2017-01-12 at 10 20 40](https://cloud.githubusercontent.com/assets/3718654/21887372/923d98c4-d8b7-11e6-97c7-2ee3347b1f0b.png)

**Comment by pedro93** [comment]
I am not familiar with the source code but perhaps there is a code difference between the cli and extension?

@paulirish @patrickhulce, @brendankenny and @ebidel, is there a way to manually install the lighthouse plugin from source in development mode and use chrome dev tools (perhaps in remote debug mode) to debug it and the nodeJS cli version?

**Comment by patrickhulce** [comment]
Just uncovered a huge potential issue while investigating the perf of [this app](https://github.com/PolymerLabs/indie-catalog). The trace from the extension run is totally missing significant layout work that the CLI run contains.

The below screenshots are for the exact same time period of the same site, note that the 400ms purple Layout task is absent from the extension run.

| CLI | Extension |
| - | - |
| ![image](https://user-images.githubusercontent.com/2301202/28650228-0e226314-722f-11e7-8008-65dc7d392a8d.png) | ![image](https://user-images.githubusercontent.com/2301202/28650230-1496cf3c-722f-11e7-955c-f3f114583ae9.png) |
| [trace](https://drive.google.com/open?id=0B_6m1yW__xllVHFINzNQemF6ZW8) | [trace](https://drive.google.com/open?id=0B_6m1yW__xllYl9DS2ppRmFHMHM) |

**Comment by brendankenny** [comment]
duplicate into #1426?
