### ISSUE TITLE
Update the mobile profile specs

### ISSUE THREAD

**Issue by theninthsky** [GoogleChrome/lighthouse#14516]
**Feature request summary**

The mobile profile (**Moto G4** with **slow 4G** network) is completely irrelevant.

As can be seen here: https://worldpopulationreview.com/country-rankings/internet-speeds-by-country
The lowest average mobile network speed can be found in Afghanistan and is 7.2Mbps, which is way higher than the 1.6Mbps Lighthouse's profile has.

Even more severe is the fact that the Moto G4 is a 6.5 years old extinct smartphone , and every mid-tier smartphone nowdays has at least double the CPU speed of the Snapdragon 617.

So please update the profile to match our reality in 2022.

**What is the motivation or use case for changing this?**

Today, when benchmarking mobile client-side rendered apps, they get a very low scores compared to server-side rendered apps.
However, this representation is flawed, since the simulated network speed and device power have no connection to reality.

When switching to the desktop simulation, we can see that both CSR and SSR apps perform almost identically.

**How is this beneficial to Lighthouse?**

It would make Lighthouse a more reliable benchmarking tool.

**Comment by adamraine** [comment]
We have plans to update this already https://github.com/GoogleChrome/lighthouse/issues/12235 https://github.com/GoogleChrome/lighthouse/issues/14256
