### ISSUE TITLE
getting ChromeLauncher Waiting for browser in linux server

### ISSUE THREAD

**Issue by pavanseniorassociate** [GoogleChrome/lighthouse#14522]
### Discussed in https://github.com/GoogleChrome/lighthouse/discussions/14517

<div type='discussions-op-text'>

<sup>Originally posted by **pavanseniorassociate** November 10, 2022</sup>
Hi team,

 Please find the below details and help me

  ### Command 

          lighthouse https://nodejs.org/en/ --chrome-flags=--headless --config-path=./myconfig.js --preset=desktop --output=html --output-path=./Reports_11-10-22.html

I am trying to run this command using python code.

 ###   Linux system details
  ```
        NAME="Red Hat Enterprise Linux Server"
        VERSION="7.9 `(Maipo)"`
        ID="rhel"
        ID_LIKE="fedora"  
        VERSION_ID="7.9"
        PRETTY_NAME="Red Hat Enterprise Linux Server 7.9"
        ANSI_COLOR="0;31"
        CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
        HOME_URL="https://www.redhat.com/"
        BUG_REPORT_URL="https://bugzilla.redhat.com/"
        REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
        REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
        REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
        REDHAT_SUPPORT_PRODUCT_VERSION=7.9
```

I am getting following error 

```
 LH:ChromeLauncher Waiting for browser. +0ms
  LH:ChromeLauncher Waiting for browser... +1ms
  LH:ChromeLauncher Waiting for browser..... +505ms
  LH:ChromeLauncher Waiting for browser....... +504ms
  LH:ChromeLauncher Waiting for browser......... +502ms
  LH:ChromeLauncher Waiting for browser........... +502ms
  LH:ChromeLauncher Waiting for browser............. +502ms
  LH:ChromeLauncher Waiting for browser............... +501ms
  LH:ChromeLauncher Waiting for browser................. +502ms
  LH:ChromeLauncher Waiting for browser................... +502ms
  LH:ChromeLauncher Waiting for browser..................... +502ms
  LH:ChromeLauncher Waiting for browser....................... +502ms
  LH:ChromeLauncher Waiting for browser......................... +502ms
  LH:ChromeLauncher Waiting for browser........................... +501ms
  LH:ChromeLauncher Waiting for browser............................. +501ms
  LH:ChromeLauncher Waiting for browser............................... +502ms
  LH:ChromeLauncher Waiting for browser................................. +501ms
  LH:ChromeLauncher Waiting for browser................................... +502ms
```
</div>

**Comment by adamraine** [comment]
@pavanseniorassociate Is your issue that Chrome never launches?

**Comment by pavanseniorassociate** [comment]
@adamraine Yes

**Comment by adamraine** [comment]
I can't repro this unfortunately, could you please provide this information:
- Lighthouse version
- Node version
- Chrome version

**Comment by pavanseniorassociate** [comment]
1.  lighthouse version   :   9.6.8
2.  Node Version           :   v16.15.0
3. Chrome Version        :   Google Chrome 107.0.5304.110

**Comment by adamraine** [comment]
I was able to reproduce this when I removed the `--chrome-flags=--headless` flag, perhaps headless mode isn't being applied somehow?

@pavanseniorassociate lmk if either of these commands works for you:

```sh
lighthouse https://nodejs.org/en/ --chrome-flags="--headless"
```

If you have Xorg installed:
```sh
xvfb-run --auto-servernum lighthouse https://nodejs.org/en/ --chrome-flags="--headless"
```

**Comment by pavanseniorassociate** [comment]
HI @adamraine 
    
    Below command is not working. getting same error... LH:ChromeLauncher Waiting for browser
        lighthouse https://nodejs.org/en/ --chrome-flags="--headless"

**Comment by JoelLisenby** [comment]
In Windows Subsystem for Linux (WSL2) ubuntu I was experiencing this. 

After installing google-chrome:
`wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`
`sudo apt -y install ./google-chrome-stable_current_amd64.deb`

Find your chrome path
`which google-chrome`

Export CHROME_PATH (swap out the value for your path if different)
`export CHROME_PATH=/usr/bin/google-chrome`

The problem was LH:ChromeLauncher was trying to launch chrome from the following incorrect path by default in my setup, which was the windows path to google chrome instead of the linux path:
`/mnt/c/Program Files/Google/Chrome/Application/chrome.exe`

**Comment by adamraine** [comment]
This still isn't reproducible for me. As @JoelLisenby pointed out you should make sure Chrome is installed correctly and that `CHROME_PATH` points to the Chrome executable that you want to use.
