### ISSUE TITLE
"Deprecated APIs" warning does not provide description or source

### ISSUE THREAD

**Issue by jasonhoward64** [GoogleChrome/lighthouse#14528]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://cleanwithpristine.net

### What happened?

When we run lighthouse, the depreciated API warning shows no source. Issue claimed to be fixed here, but issue is still present:

https://github.com/GoogleChrome/lighthouse/issues/14233

### What did you expect?

Expected to see an indication of the API that is depreciated.

### What have you tried?

Tried updating Chrome. I'm on the latest build.

Chrome is up to date
Version 107.0.5304.107 (Official Build) (64-bit)

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.6

### Chrome Version

107.0.0.0

### OS

Windows 10

**Comment by adamraine** [comment]
The issue was fixed in v9.6.8 which ships with Chrome M109. You are on v9.6.6.
