### ISSUE TITLE
Old v3 LHR fails to render in viewer

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#14549]
https://googlechrome.github.io/lighthouse/viewer/?gist=8d2c72743eb6c28df6bbe9d3c7ac4a5b ([source](https://github.com/GoogleChrome/lighthouse/issues/5273#issuecomment-390747838))

see the LHR in the console. `3.0.0-alpha.2`

```
Uncaught Error: Error rendering report: Cannot read properties of undefined (reading 'rendererFormattedStrings')
```

**Comment by paulirish** [comment]
prettyprint it

pause here:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/39191/203211050-9222540e-c453-42e3-9a91-95ad207c280c.png">

run dis:

```js
e.i18n = {}; e.environment = {benchmarkIndex: 0};
```

and it'll render

**Comment by connorjclark** [comment]
thx i was being lazy 🙈

**Comment by paulirish** [comment]
yw. obv doesn't help folks except us, but... it was quick.
