### ISSUE TITLE
Make NO_LCP error message specific to LCP

### ISSUE THREAD

**Issue by vsteenhoudt** [GoogleChrome/lighthouse#14554]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://jsbin.com/pajibab/edit?html,output

### What happened?

When analyzing page load with mode: navigation, device: mobile and categories: performance there is an error on the LCP metric. 
We receive the following message:
`Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_LCP)`

This error error does not occur when analyzing page load desktop on desktop.

### What did you expect?

Would have expected a similar result as when running the test on desktop. Where the error does not occur.

### What have you tried?

Made a minimal html page with only the image with css style object-fit: cover defined to make sure nothing else might be causing the issue.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.6

### Chrome Version

107.0.5304.110

### OS

Mac

**Comment by adamraine** [comment]
This is intentional and it's not connected to `object-fit`. [Images that fill the entire viewport are not considered LCP candidates.](https://web.dev/lcp/#what-elements-are-considered:~:text=Images%20that%20occupy%20the%20entire%20viewport%20are%20not%20considered%20LCP%20candidates.)

**Comment by romainmenke** [comment]
Thank you @adamraine for this speedy update!

The new message is much clearer imo.
