### ISSUE TITLE
Update perf scoring for v10

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#14565]
See also [core(scoring): rebalance perf metric weightings · #12577](https://github.com/GoogleChrome/lighthouse/pull/12577) https://github.com/GoogleChrome/lighthouse/pull/12577 (for v8)

Details coming…

**Comment by adamraine** [comment]
Is this done now after #14667?

**Comment by connorjclark** [comment]
No,

> Details coming…

Paul wants us to write details I guess. Something like v8-perf-faq.md but less involved

**Comment by connorjclark** [comment]
Closing for https://github.com/GoogleChrome/lighthouse/issues/14586
