### ISSUE TITLE
Differences in results between Lighthouse & PageSpeed Insights

### ISSUE THREAD

**Issue by RubenCargo1** [GoogleChrome/lighthouse#14562]
Hi,
After doing our Lighthouse check, we got some good results for both Mobile as Desktop (see screenshot below) However, I get very different results when I do the same test with PageSpeed Insights (see screenshots below) How is this possible? Hopefully someone can help us clarify these differences.  Hopefully someone can help us clarify these differences. Thanks in advance!

<img width="892" alt="image (5)" src="https://user-images.githubusercontent.com/119037113/203929580-6422f682-0952-4a22-9c8e-0170cfcd8175.png">
<img width="829" alt="image (4)" src="https://user-images.githubusercontent.com/119037113/203929583-6d74230d-f393-4fe6-8b3e-2aacdafff178.png">
<img width="381" alt="image (2)" src="https://user-images.githubusercontent.com/119037113/203929586-15aacd7c-a116-4a08-9c08-866eb52f61b0.png">
<img width="388" alt="image (3)" src="https://user-images.githubusercontent.com/119037113/203929592-9024e90c-993c-4588-ae4a-47b78fb2ec46.png">

**Comment by DanielRuf** [comment]
These are different Lighthouse versions. You can see the used version at the bottom of the page afaik.

**Comment by DanielRuf** [comment]
These are different Lighthouse versions. You can see the used version at the bottom of the page afaik.

Also if you test locally your internet connection might be better and the emulated internet connection speed if different.

**Comment by adamraine** [comment]
I can't reproduce this big of a difference in performance. Please take a look at our [variability docs](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md).

**Comment by RubenCargo1** [comment]
@adamraine thanks! I wil ask our developers to take a look at the document. Which results do you get with Lighthouse and PageSpeed if I may ask?

**Comment by RubenCargo1** [comment]
@DanielRuf thanks! Wil check that too.

**Comment by adamraine** [comment]
This is a report I took from airport wifi: https://googlechrome.github.io/lighthouse/viewer/?gist=ecbd921dd6e13575c29b4db627a4b6c0

My PSI results were similar to yours. 38 on mobile and 82 on desktop.
