### ISSUE TITLE
Why is it classified as 'Not applicable'?

### ISSUE THREAD

**Issue by pokkariii** [GoogleChrome/lighthouse#14575]
**Summary**

I ran two tests on the same page.
In the first test, the accessibility item was marked as 'error'.
However, the second test was marked as 'Not Applicable'.
I couldn't find a difference in the HTML code between two tests. Both have <dt> and <dl> elements.
Why does one test mark as 'Not Applicable'? I need a standard that is classified as 'not applicable'.

![image](https://user-images.githubusercontent.com/78514749/205024131-caeed476-f840-4b5d-8ac1-f089c513ddb1.png)

**Comment by connorjclark** [comment]
If there are no relevant elements on the page, those audits will be marked N/A. Without seeing the URL or the Lighthouse reports/json, we can't know the reason for the difference.
