### ISSUE TITLE
DevTools e2e `CacheStorage.requestCacheNames` error

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#14572]
Doesn't happen all the time. Example:
https://github.com/GoogleChrome/lighthouse/actions/runs/3586036499/jobs/6035045198

**Comment by adamraine** [comment]
Actually, this might be related to the branch.

**Comment by adamraine** [comment]
Never-mind, just saw it on a different branch:
https://github.com/GoogleChrome/lighthouse/actions/runs/3586513398/jobs/6035995757

**Comment by paulirish** [comment]
Ive seen this flake on DevTools patches that are totally unrelated to LH. Seems like a flake thats just... due to DT e2e test harness or something. aka not our fix.
