### ISSUE TITLE
Audit: deprecations and interventions

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1458]
The DT protocol can capture console messages for Chrome's deprecation and intervention warnings. Each of these has a specific source we can check (e.g. `source: 'deprecation'`) in order to differentiate between user console noise and Chrome warnings. 

Already started in on this:

<img width="792" alt="screen shot 2017-01-11 at 9 43 17 pm" src="https://cloud.githubusercontent.com/assets/238208/21878407/fe123dd2-d846-11e6-89d4-431b0c6f90f8.png">

**Comment by RByers** [comment]
I'm excited to see this happen.  Let me know if there's anything I can do to help from the blink side.
I see we need to [fix DeprecationMessageSource to be used consistently](http://crbug.com/680832).

Perhaps we might also want to add some structured data to avoid having to parse the messages?  Eg. removal date, some sort of stable identifier to support prioritization and linking/documentation?  But perhaps that can come after we've got the basics working?

**Comment by ebidel** [comment]
Thanks @RByers. I think for now we can just pass through the deprecation messages as is. In the future, it would be cool to have structure data link doc link, chromestatus link, removal date, removal milestone, etc.

**Comment by RByers** [comment]
Just poked at the current code a bit.  It looks like Lighthouse has two channels today:

1. Console messages [from blink](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/frame/Deprecation.cpp?q=kDeprecationMessageSource&sq=package:chromium&dr=C&l=117) with `kDeprecationMessageSource` all get plumbed into the [deprecations audit](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/deprecations.js)
2. [Calls in blink](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/Document.cpp?type=cs&l=3419) to `PerformanceMonitor::ReportGenericViolation` with type `kDiscouragedAPIUse` get plumbed into the [ChromeConsoleMessages audit](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/chrome-console-messages.js)

This leaves a [few cases](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/inspector/ConsoleTypes.h?type=cs&q=kInterventionMessageSource&l=23) in blink where we're generating console messages with ` kInterventionMessageSource` apparently not hooked up to lighthouse.  Perhaps those should move to using `PerformanceMonitor` (though, like other discouraged API use, they aren't necessary all performance things), and `kInterventionMessageSource` should be removed?  For example, attempts to use the vibration API from a cross-origin iframe hit this path.

I don't understand the tradeoff between the devtools `ConsoleMessage` and `PerformanceMonitor` systems here - when should blink use one over the other?  @pavelfeldman

**Comment by RByers** [comment]
Note that the [chrome-console-messages.js](https://github.com/GoogleChrome/lighthouse/blob/d99778b4f1eb8d353ad54dc7830d286dfe30ba3e/lighthouse-core/gather/gatherers/chrome-console-messages.js#L19) says:

```javascript
/**
 * @fileoverview Gathers console deprecation and intervention warnings logged by Chrome.
 */
```

When in fact it's used only for interventions (deprecations [have their own audit](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/deprecations.js)).  I don't see any good reason to treat these two cases completely separately though.

**Comment by pavelfeldman** [comment]
@RByers we should move this conversation into chromium world - you are referring to the chrome code, elaborating guidelines for reporting violations there, etc. Lighthouse is just one of the clients, don't make it think for the backend.

**Comment by RByers** [comment]
@pavelfeldman, fair enough.  I'm still waiting for a response from you on that via e-mail :-)

**Comment by pavelfeldman** [comment]
@RByers: I have no memory of it, probably archived it by mistake long ago :/

**Comment by paulirish** [comment]
FIXED https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/deprecations.js
