### ISSUE TITLE
Layout-shift-elements score should match CLS score. Add more CLS rootcause analysis

### ISSUE THREAD

**Issue by tunetheweb** [GoogleChrome/lighthouse#14583]
**Feature request summary**

Currently we have two CLS audits: one for not setting height and width on images, and one for the elements causing most shifts.

Take cnn.com, which currently shows this for mobile:

<img width="955" alt="CLS audits highlighting the width and height image audit as failing" src="https://user-images.githubusercontent.com/10931297/205666068-55ef1f79-b4f6-4066-a7bf-c545e062b3f4.png">

And when the "Avoid layout shifts" audit is expanded you get this:

<img width="952" alt="CLS audits with the layout shifts audit expanded" src="https://user-images.githubusercontent.com/10931297/205666006-b329bad4-5993-4a0c-b96c-66acd4499996.png">

You can see here the "Image elements do not have explicit `width` and `height`" audit is not actually contributing to CLS (at least for the above the fold content that Lighthouse shows be default, but a `<div>` **IS** causing CLS - with a massive 0.135 (the entirety of the CLS captured by Lighthouse).

Lighthouse is highlighting the wrong issue here, which can lead to confusion.

I would suggest we reduce the image audit to amber when there are no equivalent images in the layout shifts audit (though keep as amber as it _may_ affect below the fold content), and we highlight the layout shifts audit in red when the total CLS is above the good barrier of 0.1:

<img width="950" alt="CLS audits with the correct area to concentrate on highlighted" src="https://user-images.githubusercontent.com/10931297/205668133-636ae384-b7f6-4283-8ca7-c94147144daa.png">

For bonus points it could highlight the shifts above the 0.1 limit in red (ideally with a warning symbol too as well so it's not just colour highlight).

<img width="955" alt="CLS above 0.1 highlighted in red" src="https://user-images.githubusercontent.com/10931297/205670799-f235af2b-3753-4877-895a-5b38379b135e.png">

**What is the motivation or use case for changing this?**

Lighthouse is currently not highlighting the real issues in these cases.

**How is this beneficial to Lighthouse?**

Allow Lighthouse to more accurately reflect content affecting CLS making it more useful and less prone to falsely identifying non-issues.

**Comment by tunetheweb** [comment]
That’s a very good point!

Thoughts on the second suggestion of promoting the “layout shifts” section beyond “informational” which it’s clearly identifying CLS limit-breaking shifts? Agreed it’s the effect, rather than necessarily the cause but still feels important to highlight more to me.

**Comment by connorjclark** [comment]
Yeah, we should perhaps set the score to be the CLS score to match the metric pass/warn/fail state.

**Comment by connorjclark** [comment]
We're gonna explore what we can do to give a best-guess for root-cause attribution in Lighthouse this quarter. CDT has done some work on this recently, although it's in an internal repo.

**Comment by tunetheweb** [comment]
I think highlighting the shifts themselves more when they are large could be an easier option, and a big win, and avoid the complexities of trying to attribute those fixes.
