### ISSUE TITLE
Merge lighthouse reports

### ISSUE THREAD

**Issue by VadimSvirdoff** [GoogleChrome/lighthouse#14598]
Hi, are there any tools for merging multiple reports into one? Motivation is comparing metrics.
Thanks for your answers!

**Comment by brendankenny** [comment]
Someone else can chime in if there's an easier way to generate standalone report diffs, but [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci/) has such a tool.

There's an [online viewer](https://googlechrome.github.io/lighthouse-ci/viewer/) where you can drag in two Lighthouse JSON results and see a comparison, or you can clone/install lighthouse-ci, `npm run build` and there will be a local version of the online viewer in the `dist/` directory.
