### ISSUE TITLE
User Flow docs are not up-to-date? 

### ISSUE THREAD

**Issue by ChristopherPHolder** [GoogleChrome/lighthouse#14603]
**Summary**

The import path for startFlow on the docs for [**User Flows in Lighthouse**](https://github.com/GoogleChrome/lighthouse/blob/03674e9b100f769367e4f174ba7ca29a5b081912/docs/user-flows.md) are not the same as the current release or the version repo is on now. 

The import path specifies on in the documentation is:

```javascript
import lighthouse from 'lighthouse/core/api.js';
```

The import path for the latest release [**v9.6.8**](https://github.com/GoogleChrome/lighthouse/releases/tag/v9.6.8) is:

 ```javascript
 import lighthouse from 'lighthouse/lighthouse-core/fraggle-rock/api.js';
 ```
 
And the import path on the current repo is:
 
  ```javascript
  import lighthouse from 'lighthouse/core/index.js';
  ```
  
 I can also see the docs have a cool feature `startNavigation` and `endNavigation`.
 
Which is the correct path?

1. Path on current Documentation
2. Path on latest release
3. Path on curent repo main
   
Can I open a pr and update the docs? :)

**Comment by adamraine** [comment]
Thanks for catching this. We should be holding docs changes for the 10.0.0 breaking release in a separate branch that will be merged when 10.0.0 is actually released. Unfortunately some docs changes slipped through the cracks and now the docs don't reflect either the latest release or main branch.

In the latest release v9.6.8 the import path is:

```js
import {startFlow} from 'lighthouse/lighthouse-core/fraggle-rock/api.js';
```

On main branch and the future v10.0.0 release, the import path is:

```js
import {startFlow} from 'lighthouse';
```

**Comment by ChristopherPHolder** [comment]
If the changes I am proposing are accepted, I would be happy to change the docs on the v10.0.0 if you would point out the branch. 

I would be an honour to be able to contribute to `lighthouse` you'll are doing amazing work. 

Please let me know how to move forward.

**Comment by adamraine** [comment]
> If the changes I am proposing are accepted, I would be happy to change the docs on the v10.0.0 if you would point out the branch.

The branch is https://github.com/GoogleChrome/lighthouse/tree/10-docs-staging. I took a look and the user flows doc in that branch should be valid for 10.0. I don't think a PR is necessary for that branch.
