### ISSUE TITLE
Some npm dependencies are obsolete

### ISSUE THREAD

**Issue by tkrotoff** [GoogleChrome/lighthouse#14602]
Some of the npm dependencies are really old:

![image](https://user-images.githubusercontent.com/643434/206780579-c82284fa-d470-4b50-907c-b3fccf2cde67.png)

```
WARN deprecated intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible.
Please use @formatjs/icu-messageformat-parser
```

https://github.com/GoogleChrome/lighthouse/pull/13834

**Comment by connorjclark** [comment]
In general we don't update things just to update them, only when things are broken. Updating incurs some risk assuming our test coverage isn't 100% (Which it never is), and the benefits of spending time on this aren't clear.
