### ISSUE TITLE
Lighthouse Report Treemap not showing indepth information

### ISSUE THREAD

**Issue by anthonylee-drizly** [GoogleChrome/lighthouse#14618]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://drizly.com/

### What happened?

Last week when I ran a lighthouse report. I went into the treemap and the results were very indepth showing what each javascript file entailed. Here is an example of what it looked like.

![image](https://user-images.githubusercontent.com/104843340/207985486-bd1fb1eb-3947-456b-b124-bc8cbfaef9a6.png)

This week when I ran the same light house report, it does not show details indepth anymore.

![image](https://user-images.githubusercontent.com/104843340/207985546-e7a30b9c-bb3e-4507-ac71-6fe776d33541.png)

Am I doing something wrong, or was there an update that is causing this.

### What did you expect?

I am expecting an indepth chart of what each javascript file entails.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.6

### Chrome Version

108.0.5359.98

### OS

Mac

**Comment by connorjclark** [comment]
The scripts on your page no longer have source maps associated with them, which is where all that information came from. Check for some regression in your build pipeline.
