### ISSUE TITLE
eslint regression: use of undeclared variables not caught

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1461]
I've noticed a few things in my editor not being flagged recently, and just confirmed that our lint test doesn't catch them either. I assume this happened when we updated eslint and our configs in #1136

What I've noticed so far (there may be others):
- you can add random `myVar++` or `myFakeFunction(15)` anywhere and they won't be flagged (unused declared variables are still flagged, luckily)
- `for (key in keys) { ... }` (leaving out the `var`/`let`/`const`) won't be flagged as an error even if `keys` isn't defined above, though it'll throw at runtime

   (interestingly `prefer-const` *is* working, as `for (let key in keys) { ... }` will be flagged to change to `const` if `key` isn't altered in the body of the loop)

anyone come across any others?

**Comment by brendankenny** [comment]
(ha, just realized those are the same issue :)

**Comment by patrickhulce** [comment]
sorry @brendankenny this one was too shocking to leave around as first bug haha

**Comment by patrickhulce** [comment]
might be a good time to see what else `eslint:recommended` has been commented out in google https://github.com/google/eslint-config-google/blob/master/index.js#L158

**Comment by brendankenny** [comment]
> might be a good time to see what else eslint:recommended has been commented out in google 

oh dear :S
