### ISSUE TITLE
How can I change the LightHouse mode to snapshot using cli ?

### ISSUE THREAD

**Issue by riyagharde1** [GoogleChrome/lighthouse#14629]
![lighthouse](https://user-images.githubusercontent.com/121165761/208887635-8be9be55-e6bd-4375-935c-8c52f9e4a609.jpg)

**Comment by riyagharde1** [comment]
I am using Lighthouse to analyze the page and I want to change the mode to `snapshot` rather than `navigate`. I am able to do this manually from the browser by doing the following: -

- clicking the Inspect option 
- select Light house tab 
- set the mode to snapshot as shown in the attached screenshot.

Currently I am using the following command from the cli to do the same. 

``` 
lighthouse https://www.google.com --output html --output-path <path> 
```

Thanks, in anticipation.

**Comment by adamraine** [comment]
Unfortunately, it is not possible to use snapshot or timespan mode from the CLI. You will need to construct your own user flow script or use DevTools like you mentioned. https://github.com/GoogleChrome/lighthouse/blob/main/docs/user-flows.md
