### ISSUE TITLE
CLS reported by lighthouse is not the same as the web vitals extension

### ISSUE THREAD

**Issue by news-manishpatel** [GoogleChrome/lighthouse#14621]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.thesun.co.uk/

### What happened?

The lighthouse timespan mode is raising a CLS issue when interacting with a CSS based navigation menu. The same issue is not flagged by the web vitals extension. Wondering which one is correct?

Video running lighthouse user flow. 
https://user-images.githubusercontent.com/91079914/208099069-e5165b8f-8792-42fd-83d2-e958ac7c479c.mp4

Image of web vital extension with same interaction as above
![web-vitals-js](https://user-images.githubusercontent.com/91079914/208099212-eb27579d-feb2-4ef9-bbad-dea15929dbd2.png)

### What did you expect?

No CLS issue to be flagged as the interation was triggered by the user. 

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.6

### Chrome Version

108

### OS

Windows

**Comment by brendankenny** [comment]
There's a few reasons they may differ. Lighthouse loads the page at a specific screen size (which affects both what elements are on screen and what percentage of the window shifting elements would take up) and it only measures CLS up to when the page appears loaded.

The web-vitals extension monitors the page at whatever dimensions you're currently using and for as long as you have it open, so there may be different elements shifting different amounts, and responding to things (e.g. very slow loading ads, animations on a timer, scroll events) after the page has loaded that Lighthouse wouldn't have seen.

This article has more information about lab vs field differences for CLS and in general: https://web.dev/lab-and-field-data-differences/#cls

**Comment by brendankenny** [comment]
I just noticed you're talking about a timespan, sorry, so ignore most of what I just said (though https://web.dev/lab-and-field-data-differences/#cls is still good :)

Are you sure the menu is what's causing the CLS? Can you share the lighthouse report or take a look at what's in the "Avoid large layout shifts" diagnostic below the metrics?

This may be an instance of #14396

**Comment by brendankenny** [comment]
> This may be an instance of https://github.com/GoogleChrome/lighthouse/issues/14396

Looking at the trace, it does seem like it. There are CLS events from the initial resize (how many are legitimate vs should be ignored is unclear), but then the shift events from opening the menu are marked as `had_recent_input: true`, which is ignored but shouldn't be. @adamraine's #14402 would fix this

@news-manishpatel to answer your question, in this case the web-vitals extension is correct and it is a Lighthouse bug.

**Comment by news-manishpatel** [comment]
@brendankenny thanks for the confirmation. I will follow #14402 for updates as well. 

To your previous comment. It does point to the menu as the cause of the layout shift. 

To add to my initial check I only get it if I interact with the burger menu button. If click on the search button CLS stays at 0. Added both LHR below. 

[timespan-search.pdf](https://github.com/GoogleChrome/lighthouse/files/10247766/timespan-search.pdf)
[timespan-burger-menu.pdf](https://github.com/GoogleChrome/lighthouse/files/10247764/timespan-burger-menu.pdf)

**Comment by adamraine** [comment]
I agree this is the same issue as https://github.com/GoogleChrome/lighthouse/issues/14396
