### ISSUE TITLE
Add `interactive-widget` to known viewport properties

### ISSUE THREAD

**Issue by BenjaminAster** [GoogleChrome/lighthouse#14636]
Chromium now [supports](https://developer.chrome.com/blog/viewport-resize-behavior/#opting-in-to-a-different-behavior) the [`interactive-widget` property](https://w3c.github.io/csswg-drafts/css-viewport/#interactive-widget-section) in the viewport meta tag. However, Lighthouse throws a warning when using it.
![Warnings: Invalid properties found: {"interactive-widget":"resizes-content"}](https://user-images.githubusercontent.com/63414473/209482232-121e05c3-8c85-4fc8-ac5b-d3cdddb83faa.png)

**Comment by connorjclark** [comment]
Thanks for the issue!

We'll need to update https://github.com/dontcallmedom/metaviewport-parser/ - an example of adding a new property there:  https://github.com/dontcallmedom/metaviewport-parser/pull/6/files
