### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by anasdooma** [GoogleChrome/lighthouse#14631]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

Magicalring.dk

### What happened?

Hello
I cannot test my website speed on pagespeed insighrs, i get unknown error. I have this problem for about 2 monthes. Can you please tell me how i can fix this.

### What did you expect?

The site speed

### How were you running Lighthouse?

PageSpeed Insights

**Comment by adamraine** [comment]
Thanks I can repro this.

**Comment by panthony** [comment]
Got similar issues on some URLs of `www.visa.com.hk`:

Ex: https://www.visa.com.kh/en_KH/travel-with-visa/destinations/paris.html

Running it on PageSpeed insights too.

**Comment by adamraine** [comment]
@panthony that looks like a separate issue, I moved it to https://github.com/GoogleChrome/lighthouse/issues/14643

**Comment by adamraine** [comment]
I can't repro anymore.
