### ISSUE TITLE
Should I use AMP or not?

### ISSUE THREAD

**Issue by mmhdi** [GoogleChrome/lighthouse#14635]
Hello,
I have a website whose speed on mobile is 600ms and on PC is 190ms, and when I add AMP it becomes slower and its speed on mobile is 900ms and on PC is 360ms.

In general, should I use AMP, and in particular, should I use AMP to improve SEO and AdSense earnings? Is SEO and AdSense based on speed or AMP?

**Comment by adamraine** [comment]
I can't provide general advice about using AMP, and I don't think this is the right place for this question. Perhaps this will help:
https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/optimize_amp
