### ISSUE TITLE
Required ImageElements gatherer encountered an error.

### ISSUE THREAD

**Issue by anuix** [GoogleChrome/lighthouse#14633]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.mountlift.com/

### What happened?

I'm trying to run PageInsights on the website https://www.mountlift.com and I get the following error on Diagnostics section. 

`Required ImageElements gatherer encountered an error: window.__lighthouseNodesDontTouchOrAllVarianceGoesAway.get is not a function`

![image](https://user-images.githubusercontent.com/12616381/209299881-8d5ebabb-3a77-40e9-81c5-2a32bea457e7.png)

I only get this error for that specific website (every page of it) and I want to find out if' it's something in the syntax that isn't right or something wrong with Lighthouse (which I doubt). 

### What did you expect?

To show the Diagnostics.

### How were you running Lighthouse?

web.dev

### Lighthouse Version

9.6.6

**Comment by connorjclark** [comment]
Having trouble reproing

- Was it https://www.mountlift.com/ directly or some subpage?
- Does it always happen for you on https://pagespeed.web.dev/ ?
- Is running Lighthouse from DevTools any different?

**Comment by adamraine** [comment]
I can't repro either.
