### ISSUE TITLE
Static assets with an efficient cache policy

### ISSUE THREAD

**Issue by ohrrkan** [GoogleChrome/lighthouse#14650]
Caching policy can also be made with service worker to replace browser memory cache.
Lighthouse do not recognise the method and give a diagnostic warning to improve cache policy.

Service worker caching method can give more flexibility to cache control and mostly give the same benefit as memory cache.
It is probably a method that should be recommend  or at less recognise by lighthouse analyse

**Comment by paulirish** [comment]
Service worker is super powerful. If you're managing caching for all your users with that (and not setting long ttls in cache-control) then you're on your own. You can ignore this audit's results. (And you'll have to validate that your setup is working great for everyone yourself)
