### ISSUE TITLE
LH Puppeteer union types TypeScript error

### ISSUE THREAD

**Issue by benschwarz** [GoogleChrome/lighthouse#14654]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://no-url.tld

### What happened?

While using Lighthouse from `#main` (`9.5.0-dev.20230105` for example), I receive type failures from `puppeteer`/`puppeteerCore` union types: 

```
> tsc

node_modules/lighthouse/types/puppeteer.d.ts:16:25 - error TS2503: Cannot find namespace 'puppeteerCore'.

16   export type Browser = puppeteerCore.Browser | puppeteer.Browser;
                           ~~~~~~~~~~~~~

node_modules/lighthouse/types/puppeteer.d.ts:16:49 - error TS2833: Cannot find namespace 'puppeteer'. Did you mean 'Puppeteer'?

16   export type Browser = puppeteerCore.Browser | puppeteer.Browser;
                                                   ~~~~~~~~~

node_modules/lighthouse/types/puppeteer.d.ts:17:22 - error TS2503: Cannot find namespace 'puppeteerCore'.

17   export type Page = puppeteerCore.Page | puppeteer.Page;
                        ~~~~~~~~~~~~~

node_modules/lighthouse/types/puppeteer.d.ts:17:43 - error TS2833: Cannot find namespace 'puppeteer'. Did you mean 'Puppeteer'?

17   export type Page = puppeteerCore.Page | puppeteer.Page;
                                             ~~~~~~~~~

node_modules/lighthouse/types/puppeteer.d.ts:18:28 - error TS2503: Cannot find namespace 'puppeteerCore'.

18   export type CDPSession = puppeteerCore.CDPSession | puppeteer.CDPSession;
                              ~~~~~~~~~~~~~

node_modules/lighthouse/types/puppeteer.d.ts:18:55 - error TS2833: Cannot find namespace 'puppeteer'. Did you mean 'Puppeteer'?

18   export type CDPSession = puppeteerCore.CDPSession | puppeteer.CDPSession;
                                                         ~~~~~~~~~

node_modules/lighthouse/types/puppeteer.d.ts:19:28 - error TS2503: Cannot find namespace 'puppeteerCore'.

19   export type Connection = puppeteerCore.Connection | puppeteer.Connection;
                              ~~~~~~~~~~~~~

node_modules/lighthouse/types/puppeteer.d.ts:19:55 - error TS2833: Cannot find namespace 'puppeteer'. Did you mean 'Puppeteer'?

19   export type Connection = puppeteerCore.Connection | puppeteer.Connection;
                                                         ~~~~~~~~~
```

Regardless of if I'm using puppeteer, puppeteer core, or have both installed, this failure is present. 

+cc @adamraine - I think you were looking at types recently?

### What did you expect?

Expected no TypeScript errors

### What have you tried?

Using puppeteer, puppeteer core, ensuring all other TS errors are resolved prior. 

### How were you running Lighthouse?

node

### Lighthouse Version

9.5.0-dev.20230105

### Chrome Version

108

### Node Version

18

### OS

Mac

### References

`tsconfig.json`: 

```
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "composite": true,
    "module": "NodeNext",
    "esModuleInterop": true,
    "target": "esnext",
    "noImplicitAny": false,
    "moduleResolution": "Node",
    "sourceMap": true,
    "outDir": "dist",
    "typeRoots": ["./types", "./node_modules/@types"],
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "baseUrl": ".",
    "resolveJsonModule": true,
    "paths": {
      "*": ["./node_modules/*", "./src/types/*"]
    }
  },
  "include": ["src/**/*"]
}
```

**Comment by adamraine** [comment]
I can't reproduce these exact errors. The missing `puppeteer` dependency should be handled by https://github.com/GoogleChrome/lighthouse/pull/14441 but I've never seen these TS2833 errors before.

Can you provide more environment details like `package.json` and `tsconfig.json`?

**Comment by benschwarz** [comment]
@adamraine I added the `tsconfig.json` for reference. I also checked - using `puppeteer` `19.4.1`, the above error throws, but using `18.2.1` release (same as lighthouse in `package-lock.json`), there is no error.

**Comment by adamraine** [comment]
Thanks that's helpful! I was able to reproduce your errors as well as reproing without Lighthouse. Putting this file in the tsconfig project will produce similar errors:

```ts
import puppeteer from 'puppeteer';

export type Page = puppeteer.Page;
```

I think we can't use the default export from puppeteer to access types, we need to do `import * as puppeteer from 'puppeteer'` for this. I'll add to #14441.
