### ISSUE TITLE
Extension Error: Protocol error (Debugger.enable): Script execution is prohibited

### ISSUE THREAD

**Issue by flowertwig-org** [GoogleChrome/lighthouse#1465]
**Lighthouse Version**: 1.4.1
**Chrome Version**: 55.0.2883.95
**URL**: http://beta.brfskagagard.se/kontakt/
**Error Message**: Protocol error (Debugger.enable): Script execution is prohibited
**Stack Trace**:
 ```Error: Protocol error (Debugger.enable): Script execution is prohibited
    at ExtensionConnection.handleRawError (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7534:11)
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7684:33)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ebidel** [comment]
I was not able to repro this myself using the extension. Do you have any Chrome extensions installed that could be interacting witht he page?

**Comment by flowertwig-org** [comment]
I have set Chrome to block javascript by default on domains I have not specifically enabled it on.
But javascript on beta.brfskagagard.se is enabled and the extension is also working to a point. can it be that the extension is calling a third party domain that require javascript execution?

**Comment by paulirish** [comment]
@flowertwig-org ah interesting. I have a feeling like that setting is going to conflict a bit with how Lighthouse connects to the tab.
AFAICT, there aren't other domains in the mix here, but its more that the setting and the call to debugger.enable don't really know about eachother. :)

**Comment by ebidel** [comment]
Yea interesting. How are you whitelisting JS on some domains? Maybe we could come up with a useful error message.

Generally though, you'll need JS enabled to run lighthouse on a site. We inject and run script on the page and also examine third party scripts for some audits.

**Comment by flowertwig-org** [comment]
@paulirish the interesting part is that it seems (from my view) to do all testing but seems to fail on creating the actual report.

@ebidel I click the information icon in the adress bar and set the site the allow javascript.
By default i have set it to disallow it.

**Comment by flowertwig-org** [comment]
hmm.. I think the problem is that you open the report on this url: blob:chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/6d6a207b-3aa1-4b94-80f4-2a132bdc04b1

Chrome doesn't see blob:chrome-extension as a valid protocol to add it seems

**Comment by flowertwig-org** [comment]
(and yes, if I enable javascript by default it works as expected)

**Comment by patrickhulce** [comment]
not pursuing
