### ISSUE TITLE
Errors running `Page.getResourceTree` in DevTools e2e tests

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#14662]
Examples:
https://github.com/GoogleChrome/lighthouse/actions/runs/3886546524/jobs/6632091706
https://github.com/GoogleChrome/lighthouse/actions/runs/3887332794/jobs/6633815689

This only happens for legacy navigation. I also can't reproduce this outside of the DevTools e2e tests or on e2e tests locally.

These are the only places where `Page.getResourceTree` is called. We only call it to get the main frame id:
https://github.com/GoogleChrome/lighthouse/blob/437eb4d757c52cd19994ccf80e91e872cf2f62c7/core/gather/driver/execution-context.js#L64
https://github.com/GoogleChrome/lighthouse/blob/437eb4d757c52cd19994ccf80e91e872cf2f62c7/core/gather/driver/network-monitor.js#L98

Perhaps we can avoid the error by getting the frame id using a different method.

Related:
https://github.com/GoogleChrome/lighthouse/pull/14660

**Comment by adamraine** [comment]
I think I'm going to try replacing calls to `Page.getResourceTree` with `Page.getFrameTree` to get the main frame id. If the error persists I'll try tracking the main frame id via `Page.frameNavigated` events which we are already tracking in both files.

**Comment by connorjclark** [comment]
Less data is good regardless of if it actually fixes the issue, so +1 on that front.

Can you re-run CI a number of times in this PR to see if it fixed it?
