### ISSUE TITLE
de-dupe screenshot urls in LHR

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#14689]
As suggested in #14679 by @benschwarz – we could save the raw size of the LHR ~100+ KB if we de-duped data url screenshots.

Not just for screenshot-thumbnails, but also `final-screenshot` (which after #14679 would be equivalent to the last screenshot thumbnail). If we went that route, we'd want to add a top-level `screenshots` or `dataUrls`, etc. 

We could go further and drop `screenshot-thumbnails` and `final-screenshot` as audits, and just have a top-level item like:
```ts
screenshots: {
  dataUrls: string[];
  frames: Array<{index: number, timing: number, timestamp: number}>
};
```
(many other ways to slice this)

and the report renderer would just grab from that to do its thing

**Comment by paulirish** [comment]
We have other cases where deduping would be advantageous to JSON size.. like all the URLs... The solution is similar.. Having some big `urls` array and then everything references a `urlIndex`.. More or less.

Going in this direction... 

- we _could_ apply these changes and then formalize the `LH.ReportResult` which is.. like the usable version of the LHR. And it'd undo these space saving changes.
- we could instead maintain a lil side library (a la median/representative runs) to change the LHR into a SlimLHR which.. isn't officially supported but ... we could kinda maintain some optimizations as a community.

---------

however.. right now we're thinking it may be premature to go this route..

in some experiments we've found that compression does a pretty great job on LHRs so.. leaving them brotli'd or zstd'd at rest might be the most cost-effective solution:

<img width="1266" alt="image" src="https://github.com/GoogleChrome/lighthouse/assets/39191/d9006afa-46fc-4b0e-8dcf-052ff5a70ddf">
