### ISSUE TITLE
Image Optimization Audit: add metric mapping bytes saved <-> time saved

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1469]
This has been mentioned a couple of times, but capturing in a bug....

The image optimization audit's "potential savings" for bytes is super useful:

<img width="718" alt="screen shot 2017-01-13 at 4 05 57 pm" src="https://cloud.githubusercontent.com/assets/238208/21949847/524f2efa-d9aa-11e6-8ff7-601406c804b9.png">

It would be great to also include how much time this would save the user.  Something like:

"Optimizing images would save X bytes and load x ms faster"

**Comment by paulirish** [comment]
Thanks for filing. :) What a pro. 

One note: calculating time saved on fmp/TTI/etc requires critical path analysis which is tough. A good start is calculating the possibld change in "milliseconds spent downloading resources" These times will overlap but I think that's ok. Cc @wardpeet

**Comment by ebidel** [comment]
That would also be jive well with the scripts/links blocking first render audit. Those return download times as the metric.
