### ISSUE TITLE
[bug] Protocol error (Debugger.enable): Script execution is prohibited (and sometimes PROTOCOL_TIMEOUT)

### ISSUE THREAD

**Issue by eladkarako** [GoogleChrome/lighthouse#14719]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

any website (tested on https://www.fandom.com/ and https://example.com/)

### What happened?

tried to check some slow website with lighthouse,  
got an error, afterwards I've tried multiple websites all generated the same result. 

I've made both javascript and cookies are enabled https://github.com/GoogleChrome/lighthouse/issues/12464  

I've opened the developer's panel for the developer's panel and extracted the exception from that as well.  

using Chrome dev `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`
and it bundled lighthouse.

<hr/>

![2023-01-26_234802](https://user-images.githubusercontent.com/415238/214959033-5fac833d-eb5f-4b26-9d7a-a517eb735cb6.png)

the page I was testing then redirected to `about:blank`,  
I didn't noticed it at that time and ran lighthouse again,  
and it seems to be working.  
I then noticed the URL is `about:blank` at the "start of the testing",  
before it starts loading the website.  
I've stopped the test and navigated back to the actual testing page.  

and started lighthouse again,  
this time it got a little more,  
and seem to working up until it crashed again.  
but this time it was `PROTOCOL_TIMEOUT`

```
Channel: DevTools
Initial URL: https://www.fandom.com/
Chrome Version: 111.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:842
    at new Promise (<anonymous>)
    at Driver$5.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:794)
    at Driver$5.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:168:33)
    at NetworkMonitor$4.enable (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:191:794)
    at Object.gotoURL$1 [as gotoURL] (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:201:420)
    at GatherRunner$1.loadBlank (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:225:881)
    at GatherRunner$1.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:231:441)
    at async Runner$9._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:353:872)
    at async Runner$9.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:352:738)
```

![2023-01-26_235409](https://user-images.githubusercontent.com/415238/214961065-b7ed0762-058c-4458-8cc2-77faadd7f8c8.png)
![2023-01-27_000321](https://user-images.githubusercontent.com/415238/214961068-8277de7f-5a04-42b7-abd7-0beeb44a7622.png)
![2023-01-27_000442](https://user-images.githubusercontent.com/415238/214961070-3bb8e39c-d86f-481a-8ed4-26689fdbd72a.png)

eventually I just went to `https://example.com` and tried it there,  
which rendered the same result.  

https://user-images.githubusercontent.com/415238/214963151-e56847a0-ca0c-444a-9844-8854b88f7876.mp4

I was wondering if the cause might be dev-tools tries to uploading to the remote address `https://chrome-devtools-frontend.appspot.com/serve_file/@......` and failed..

trying to access that address by itself keeps giving 404,  

but when "devtools-devtools" is wrapping around it is very hard to tell without using some external network inspection tools such as burp or Wireshark,  
![2023-01-27_002416](https://user-images.githubusercontent.com/415238/214964839-d0a9b294-18bb-4007-b912-07637dfbd4da.png)

edit:  

I've just ran burp in the background.  
it does not seems any request is getting out and it does not seems to be blocked in any way.. 

### What did you expect?

...

### What have you tried?

...

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

the one bundled with Chrome 111.0.5545.4

### Chrome Version

111.0.5545.4 (Official Build) (64-bit) 

### OS

Windows

### Relevant log output

```shell
...
```

**Comment by adamraine** [comment]
#6512 is relevant to the `PROTOCOL_TIMEOUT` case you saw.

For the "Script execution is prohibited" errors, https://github.com/GoogleChrome/lighthouse/issues/1465 is more relevant. It's likely that you have JavaScript disabled somehow seeing as LH fails on a very basic page like https://example.com.

**Comment by WebsiteRob** [comment]
I am also having the same problem. Using Brave v1.48.167 on Windows 10.

![2023-02-19_lighthouse-error](https://user-images.githubusercontent.com/24872280/220030482-4ca45cfa-a421-4e78-a4bd-01703beb56fa.png)

Happens with any website, no blocking of any kind on my side. I did notice it only happens when I use Lighthouse -> Navigation as Timespan and Snapshot work without any problem. I can use Lighthouse - Navigation in Edge without any problem.

**Comment by adamraine** [comment]
We don't officially support Brave, it's likely that Brave is doing something to block script execution.
