### ISSUE TITLE
Expand third-party-summary audit results to include sub-items

### ISSUE THREAD

**Issue by alexnj** [GoogleChrome/lighthouse#14737]
We include sub-items in `ThirdPartySummary` audit results only if it exceeds a certain threshold for each (blocking time > 0 or transfer size > 4 KiB). However, the third-party entities themselves are not omitted for these. This makes for a non-actionable audit result, without access to URLs that make up the entity (for example, to identify this entity's request in network panel). 

The tail end of the audit captured from https://theverge.com, for example:

![image](https://user-images.githubusercontent.com/683500/215575756-ba2b55aa-63bf-4891-95c3-3c8b505c36ef.png)

It would be more useful to provide the URLs that make up the summed values. Thoughts?

**Comment by alexnj** [comment]
Additional history: https://github.com/GoogleChrome/lighthouse/pull/11219

**Comment by adamraine** [comment]
Maybe instead of showing 0 resources we show 1 resource and then have an "Others" item?

Would we need to add more data to the LHR or is this just a report thing?

**Comment by alexnj** [comment]
We have a maxSubItems logic, so it might be safe to identify more than 1. This will add additional subItems to LHR.

**Comment by alexnj** [comment]
Summary from the meeting today:
 * Summary rows (entities) should have at least one sub item each. 
 * Favor include all entities, to get a comprehensive view.
 * The logic for deciding what is being dropped from subItems could be revisited as part of this.

**Comment by alexnj** [comment]
Closing as fixed.
