### ISSUE TITLE
Auditing device over adb only works with legacy navigation

### ISSUE THREAD

**Issue by JLUiceman** [GoogleChrome/lighthouse#14746]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

any website

### What happened?

tried to using lighthouse on mobile device and already follow the steps mentioned in "https://github.com/GoogleChrome/lighthouse/blob/main/docs/readme.md#testing-on-a-mobile-device";
It's worked well for first time，but then got error as the pic shows
<img width="725" alt="截屏2023-02-02 18 50 43" src="https://user-images.githubusercontent.com/16129999/216305031-b19ba6be-ffc6-449b-951b-2b73c98eb640.png">

I tried to restart the browser, terminal and kill adb server, but still don't work out;
And I have already search the issues list，but got no clues;

### What did you expect?

lighthouse works as expected

### How were you running Lighthouse?

CLI, node

### Lighthouse Version

9.6.8

### Chrome Version

109.0.5414.119

### Node Version

v16.18.1

### OS

macos

**Comment by adamraine** [comment]
You need to have Chrome open on the android device. We should update the docs to specify this.

I also noticed a couple issues when doing this workflow on `main`:
- It only works with `--legacy-navigation`
- The report failed to render

**Comment by adamraine** [comment]
https://github.com/puppeteer/puppeteer/issues/9625

**Comment by JLUiceman** [comment]
@adamraine I open the chrome on device and try it again，It works！Thanks a lot:)

**Comment by adamraine** [comment]
Update: This appears to work without the `--legacy-navigation` flag on the latest Chrome canary. However I'm still noticing an emulation issue if `--legacy-navigation` is not provided, so we can't close this just yet.
