### ISSUE TITLE
[Integration Web Perf Services] A11yWatch ability to run lighthouse partial concurrently efficiently

### ISSUE THREAD

**Issue by j-mendez** [GoogleChrome/lighthouse#14785]
Hi, I think [A11yWatch Lite](https://github.com/a11ywatch/a11ywatch) is a tool that makes sense to include on the list for projects that use Lighthouse.

It has the ability to run lighthouse concurrently and uses gRPC streams to gather the results handling thousands to millions of  lighthouse vitals within seconds/minutes with the right configurations and OS. The project is a micro-service setup and uses the fastest and most efficient OSS crawler to gather data. A11yWatch Lite is the OSS version of A11yWatch. We actually have a different feature set parody on the main service incentivizing forks to adjust the Lite version to exact needs. Right now it includes accessibility reports outside of Lighthouse, one could remove that feature to just take advantage of the speed for Lighthouse concurrency too. Just putting a note that the gathering of pages is handled concurrently in Rust and not Parallel or in Nodejs.

**Comment by adrianaixba** [comment]
Hi @j-mendez, would you like to submit a PR that adds this to the project list?
