### ISSUE TITLE
PSI Report erroneously displays "Emulated Desktop"

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#14808]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://blog.patrickhulce.com

### What happened?

When looking at the PageSpeed report for Mobile, the info box displays "Emulated Desktop" and lists screen emulation values as undefined.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/2301202/219811104-40628aec-11fe-4978-b0c3-ef6512f5eed1.png">

<img width="319" alt="image" src="https://user-images.githubusercontent.com/2301202/219811287-4faad0e8-653b-4d5f-ab67-7e4da2b44634.png">

### What did you expect?

I expected to see "Emulated Mobile" and the screen resolution / DPR that was used.

### What have you tried?

Shouting out to my favorite Lighthouse team :)

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

9.6.6

**Comment by connorjclark** [comment]
https://googlechrome.github.io/lighthouse/viewer/?gist=9e3e31748ddad6fe33ed84990e1fe94f lhr from PSI

`.screenEmulation` is an empty object, which fails us [here](https://github.com/GoogleChrome/lighthouse/blob/94e43990a05ddc3aa6c02dc0a494287266f8c6f2/report/renderer/report-utils.js#L204).

**Comment by connorjclark** [comment]
Caused by rolling 10.0 renderer, and now we read from `screenEmulation` in the config, which is not represented in the lighthouse proto. Rolling back now.

https://github.com/GoogleChrome/lighthouse/blob/94e43990a05ddc3aa6c02dc0a494287266f8c6f2/report/renderer/report-utils.js#L199-L204

We could do the same thing we did previously for devtools (formFactor is present). Or we could add screenEmulation to the proto.

**Comment by connorjclark** [comment]
Rolled back last Friday, and https://github.com/GoogleChrome/lighthouse/pull/14809 will prevent this in the future.

Thanks @patrickhulce!
