### ISSUE TITLE
How to utilise existing puppeteer page object?

### ISSUE THREAD

**Issue by asambstack** [GoogleChrome/lighthouse#14816]
Hey folks, noticed that with `10.0.0` release, we can pass puppeteer page object directly to lighthouse as the fourth parameter. However I wasn't able to find any docs around the same on how I can utilise it. When I passed the puppeteer page object to lighthouse, I encountered the error `No navigations configured`, thrown from https://github.com/GoogleChrome/lighthouse/blob/89d9fb5f1eb9307c18e856f8b6863bdee221b0e5/core/gather/navigation-runner.js#L276
Could someone help me in what additional options I need to pass to be able to use puppeteer, or link me to any docs that can guide me?

Sample script that I'm using
```
import fs from 'fs';
import lighthouse from 'lighthouse';
import puppeteer from 'puppeteer-core';

(async () => {
    const browser = await puppeteer.launch({headless: false, channel: 'chrome'});
    
    const page = await browser.newPage();
    await page.goto('https://google.com');
    const title = await page.title('');
    console.log(title);

    const options = {logLevel: 'info', output: 'html'};

    const runnerResult = await lighthouse('https://google.com', options, {}, page);
    // `.report` is the HTML report as a string
    const reportHtml = runnerResult.report;
    fs.writeFileSync('lhreport.html', reportHtml);
    
    // `.lhr` is the Lighthouse Result as a JS object
    console.log('Report is done for', runnerResult.lhr.finalDisplayedUrl);
    console.log('Performance score was', runnerResult.lhr.categories.performance.score * 100);

})();
```

**Comment by adamraine** [comment]
I think the issue is on this line:

```js
const runnerResult = await lighthouse('https://google.com/', options, {}, page);
```

You are using `{}` as your config which is an empty config and *not* the same as the default config. I think the desired pattern you want to use is:

```js
const runnerResult = await lighthouse('https://google.com/', options, undefined, page);
```

That being said, the error message here is referring to some internal stuff that I wouldn't expect users to be familiar with. We should change the error in this situation to be more clear.

**Comment by connorjclark** [comment]
Can we also throw if the config given here is just the empty object?
