### ISSUE TITLE
SyntaxError when attempting to use user-flow from lighthouse v10

### ISSUE THREAD

**Issue by ChristopherPHolder** [GoogleChrome/lighthouse#14811]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.example.com

### What happened?

I am not able to use use user-flow from lighthouse version 10. 

I followed the example from the repo [lighthouse/docs/user-flows.md](https://github.com/GoogleChrome/lighthouse/blob/main/docs/user-flows.md#navigations-in-the-nodejs-api) but it throws and error. 

Here is a [minimal reproducible example](https://github.com/ChristopherPHolder/mr-lh-uf-v10).

### What did you expect?

Usual behaviour. I expected lighthouse user-flow to run a navigation audit. 

### What have you tried?

I am using it inside of a project where I wrote a mini jest test to insure its working, that trow an error so I decided to make a minimal reproducible example repo and that throw the same error.

The error from jest was:
```ts
    /Users/christopherholder/Applications/ufo/node_modules/lighthouse/core/index.js:7
    import log from 'lighthouse-logger';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { startFlow } from 'lighthouse';
        | ^
      2 | import { launch } from 'puppeteer';
      3 | import { ResultReports } from 'shared';
      4 |

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (src/lib/user-flow-runner.ts:1:1)
```

The error is the same from the example repo `SyntaxError: Cannot use import statement outside a module` but jest seems to provided more information about its origin.

Error in minimal reproduction: 
```
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

### How were you running Lighthouse?

node

### Lighthouse Version

v10.0.1

### Node Version

v18.12.1 &  v16.16.0 

### OS

Mac

### Relevant log output

```shell
// In Minimal reproduction example repo 
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by adamraine** [comment]
Lighthouse upgraded to use ES modules in 10.0. Try adding `"type": "module"` to your package.json or change the file extension to `.mjs`. That worked for me in your min repro.

Since you're using jest, this might be helpful: https://jestjs.io/docs/ecmascript-modules

**Comment by ChristopherPHolder** [comment]
Thanks for the answer, we can now run the example.

An how can I use it inside of a typescript project? 

In the same example repo we added a minimal typescript setup and are unable to build it. 

https://github.com/ChristopherPHolder/mr-lh-uf-v10/tree/add-ts-version

**Comment by adamraine** [comment]
Looks like you caught a bug in our types, should be a pretty easy fix.

**Comment by adamraine** [comment]
I'm going to file a separate bug for posterity.

**Comment by benschwarz** [comment]
@adamraine On Lighthouse 10.0.2 I'm seeing:

```
node_modules/lighthouse/core/lib/cdt/generated/SourceMap"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

14 import TextSourceMap from '../core/lib/cdt/generated/SourceMap.js';
          ~~~~~~~~~~~~~

  node_modules/lighthouse/core/lib/cdt/generated/SourceMap.d.ts:1:1
    1 export = TextSourceMap;
      ~~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

Similar conditions to what was described above:

`tsconfig.json`: 

```
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "composite": true,
    "module": "ES2022",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "target": "ES2022",
    "noImplicitAny": false,
    "sourceMap": true,
    "outDir": "dist",
    "typeRoots": ["./types", "./node_modules/@types"],
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "baseUrl": ".",
    "resolveJsonModule": true,
    "paths": {
      "*": ["./node_modules/*", "./src/types/*"]
    }
  },
  "include": ["src/**/*"]
}
```

**Comment by adamraine** [comment]
@benschwarz Interesting that line should be fixed now:
https://github.com/GoogleChrome/lighthouse/blob/0f50514f9c7e6e32219947adab71879a2cb933bd/types/artifacts.d.ts#L14

I also verified this on npm:
https://www.npmjs.com/package/lighthouse?activeTab=code

Are you able to verify that you are using Lighthouse 10.0.2 by looking at the `node_modules/lighthouse/package.json`?
