### ISSUE TITLE
Consider failing SEO category when page is blocked from indexing

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#14832]
**Summary**
SEO category bears many similarities to PWA category in that a numeric weighted average score does not accurately reflect the result. e.g. if you've done all the optimization in the world but your robots.txt accidentally blocks the page from being discovered, you _really_ should have a score of 0.

Ideas:

- Just increase the weight of is-crawlable to something very high (dilutes other results though)
- Bespoke logic to give category `0` if is-crawlable fails.
- Something fancier ala old PWA category passing criteria.

Context: https://twitter.com/filrakowski/status/1630246287202484224

**Comment by connorjclark** [comment]
Perhaps a `necessary: boolean` on the scoring config.

**Comment by paulirish** [comment]
after discussion: We'll increase the weighting  of is-crawlable to ensure it's worth at least 31% of the seo score.
