### ISSUE TITLE
When device desktop option is selected  , it shows run mobile emulation during audit

### ISSUE THREAD

**Issue by Vanjikavya** [GoogleChrome/lighthouse#14830]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.flipkart.com/

### What happened?

while selecting desktop option , it show run mobile emulation during audit 

### What did you expect?

It should describe about desktop device 

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.8

**Comment by adamraine** [comment]
I can't repro this. What Chrome version and OS are you using?
