### ISSUE TITLE
Inspector.targetCrashed when using lighthouse programmatically

### ISSUE THREAD

**Issue by piccaso** [GoogleChrome/lighthouse#14831]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://orf.at/

### What happened?

I'm trying to run lighthouse programmatically inside a docker container.
i can reproduce it with this script:

```js
import lighthouse from 'lighthouse';
import chromeLauncher from 'chrome-launcher';

const chrome = await chromeLauncher.launch({chromeFlags: ['--headless=new', '--no-sandbox', '--disable-gpu', '--enable-logging=stdout', '--v=2'], logLevel: 'verbose'});
const options = {logLevel: 'verbose', output: 'html', onlyCategories: ['performance'], port: chrome.port};
const runnerResult = await lighthouse('https://orf.at/', options);

// `.report` is the HTML report as a string
const reportHtml = runnerResult.report;

// `.lhr` is the Lighthouse Result as a JS object
console.log('Report is done for', runnerResult.lhr.finalDisplayedUrl);
console.log('Performance score was', runnerResult.lhr.categories.performance.score * 100);

await chrome.kill();
```
Its the example from the readme with different flags to get verbose output. 
on this website (and some others) it stops with: Inspector.targetCrashed followed by a timeout.

the complete log output can be found here: http://sprunge.us/caY0lI
i was usign this docker image: `cypress/browsers:node18.12.0-chrome107`

### What did you expect?

this does work with an older image that uses lighthouse v6 so i did expect it with v9 too.
or at least a bit more information then just `Inspector.targetCrashed`
I tried to set everything to verbose - please let me know if there is something that i missed

### What have you tried?

different docker images: `apify/actor-node-puppeteer-chrome` for example.
different versions of lighthouse (6, 7, 8, 9) - got 6 to work at some point

### How were you running Lighthouse?

node

### Lighthouse Version

9.6.8

### Chrome Version

107

### Node Version

18.12.0

### OS

Linux (dockerized debian 11)

### Relevant log output

```shell
LH:<= event:verbose Network.dataReceived 
LH:<= event:verbose Network.responseReceived 
LH:<= event:verbose Network.dataReceived 
LH:<= event:verbose Network.dataReceived 
LH:<= event:verbose Network.requestWillBeSentExtraInfo 
LH:<= event:verbose Inspector.targetCrashed 
LH:waitFor:warn Timed out waiting for page load. Checking if page is hung...
LH:method => browser:verbose Runtime.evaluate 
LH:waitFor:warn Page appears to be hung, killing JavaScript...
LH:method => browser:verbose Emulation.setScriptExecutionDisabled 
LH:statusEnd:verbose Loading page & waiting for onload
LH:status Disconnecting from browser...
LH:status Cleaning origin data
LH:method => browser:verbose Storage.clearDataForOrigin 
/src/node_modules/lighthouse/lighthouse-core/gather/driver.js:348
      asyncTimeout = setTimeout(reject, timeout, new LHError(LHError.errors.PROTOCOL_TIMEOUT, {
                                                 ^

LighthouseError [LHError]: PROTOCOL_TIMEOUT
    at /src/node_modules/lighthouse/lighthouse-core/gather/driver.js:348:50
    at new Promise (<anonymous>)
    at Driver.sendCommandToSession (/src/node_modules/lighthouse/lighthouse-core/gather/driver.js:346:28)
    at Driver.sendCommand (/src/node_modules/lighthouse/lighthouse-core/gather/driver.js:369:17)
    at /src/node_modules/lighthouse/lighthouse-core/gather/driver/wait-for-condition.js:476:23
    at async Promise.all (index 0)
    at async Object.gotoURL (/src/node_modules/lighthouse/lighthouse-core/gather/driver/navigation.js:127:26)
    at async GatherRunner.loadPage (/src/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:74:36)
    at async GatherRunner.runPass (/src/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:584:49)
    at async GatherRunner.run (/src/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:507:29) {
  code: 'PROTOCOL_TIMEOUT',
  friendlyMessage: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)',
  lhrRuntimeError: true,
  protocolMethod: 'Emulation.setScriptExecutionDisabled'
}
```

**Comment by adamraine** [comment]
This looks like https://github.com/GoogleChrome/lighthouse/issues/6512#issuecomment-924123935. Try adding the `--disable-dev-shm-usage` Chrome flag as that has fixed this error in container environments for other users.

**Comment by piccaso** [comment]
that fixed it, thanks
