### ISSUE TITLE
Puppeteer authentication example throws TypeError: this._connection.connect is not a function

### ISSUE THREAD

**Issue by cedriclinares123** [GoogleChrome/lighthouse#14847]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://chromestatus.com/features

### What happened?

I tried running this script https://github.com/GoogleChrome/lighthouse/blob/main/docs/puppeteer.md (Option 1) but when I "hand off" the page to lighthouse it throws the error. I can't find any documentation around how to fix this issue. I also don't see documentation about what arguments are available to pass into the lighthouse function. The example in the link is passing 4 arguments

### What did you expect?

I expect lighthouse to perform an audit on the page that was handed off.

### What have you tried?

I tried following the docs and a few other examples I found online but had no success

### How were you running Lighthouse?

node

### Lighthouse Version

5.6.0

### Chrome Version

Version 110.0.5481.177 (Official Build) (x86_64)

### Node Version

v16.14.0

### OS

Mac

### Relevant log output

```shell
~/Documents/lighthouse-example/node_modules/lighthouse/lighthouse-core/gather/driver.js:176
    await this._connection.connect();
                           ^

TypeError: this._connection.connect is not a function
    at Driver.connect (~/Documents/lighthouse-example/node_modules/lighthouse/lighthouse-core/gather/driver.js:176:28)
    at Function.run (~/Documents/lighthouse-example/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:552:20)
    at Function._gatherArtifactsFromBrowser (~/Documents/lighthouse-example/node_modules/lighthouse/lighthouse-core/runner.js:215:42)
    at Function.run (~/Documents/lighthouse-example/node_modules/lighthouse/lighthouse-core/runner.js:81:34)
    at lighthouse (~/Documents/lighthouse-example/node_modules/lighthouse/lighthouse-core/index.js:48:17)
    at file:///~/Documents/lighthouse-example/src/puppeteer-demo.js:23:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  friendlyMessage: undefined
}
```

**Comment by adamraine** [comment]
Are you actually using Lighthouse version 5.6.0? That version is long out of date and wouldn't work with our current docs example.

**Comment by cedriclinares123** [comment]
Yea that was my issue. Sorry about that. Should have checked which versions were available before filing this issue.
