### ISSUE TITLE
Lighthouse audit is too slow (CSSUsage)

### ISSUE THREAD

**Issue by suhasv1995** [GoogleChrome/lighthouse#14846]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.google.com

### What happened?

All of a sudden, today, I started noticing unusually high analysis time on Lighthouse. I'm using lighthouse v10.0.1 as a node module, and puppeteer as the browser handler. On verbose logging, I could see that `LH:artifacts:getArtifact DOMStats` and `LH:artifacts:getArtifact JsUsage` are reporting to take 30s time in every run (screenshot below). While I sense something is definitely wrong, I'm unsure what is.

<img width="456" alt="Screenshot 2023-03-01 at 6 53 43 PM" src="https://user-images.githubusercontent.com/38910004/222152004-16d82c4b-6717-42ce-8ed5-bb7afff343aa.png">

### What did you expect?

The lighthouse analysis step should take reasonable amount of time, should be fast enough.

### How were you running Lighthouse?

node

### Lighthouse Version

v10.0.1

**Comment by paulirish** [comment]
Realllllly interesting. The log output is confusing but its actually CSSUsage that's taking 30s.

Regardless, this is definitely a problem. and thank you for reporting!

try adding `DEBUG="*"` in front of your node invocation. it'll be REALLLLLLLLLY spammy. all the pptr and CDP internals will be logging, but i imagine you'd see if theres a LOT of work happening during that time or 1 thing that's taking forever. I'm curious.


It seems like it'd be hard for us to repro your setup.. But.. if you can help us do that, we could also dig in ourselves. Either way works.

**Comment by connorjclark** [comment]
We can re-open if you're able to run again with `DEBUG="*"`.
