### ISSUE TITLE
Unable to import typescript audit using ts-node

### ISSUE THREAD

**Issue by Ehres** [GoogleChrome/lighthouse#14850]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.google.com

### What happened?

When we try to load a custom audit, with lighthouse v10, written in typescript we got an unable to load module error 
```
Cannot find module '/Users/$$/projects/$$/src/report/audits/has-max-empty-nodes.ts.js' imported from /Users/$$/projects/&&/node_modules/lighthouse/core/config/config-helpers.js
```

### What did you expect?

With lighthouse v9 we could import typescript audit files.

### What have you tried?

In our config we have this without extension (to work in local dev `ts-node` and prod mode `node`):
```ts
 audits: [
    { path: `${srcDir}/report/audits/has-max-empty-nodes` },
    { path: `${srcDir}/report/audits/has-max-element-length` },
  ],
```

We found in lighthouse code (`/core/config/config-helpers.js`) it seems to be impossible to import ts file:
```ts
async function requireWrapper(requirePath) {
  // For windows.
  if (path.isAbsolute(requirePath)) {
    requirePath = url.pathToFileURL(requirePath).href;
  }

  /** @type {any} */
  let module;
  if (bundledModules.has(requirePath)) {
    module = await bundledModules.get(requirePath);
  } else if (requirePath.match(/\.(js|mjs|cjs)$/)) {
    module = await import(requirePath);
  } else {
    requirePath += '.js';
    module = await import(requirePath);
  }
```

I tried to add the `ts` in `match` function like `requirePath.match(/\.(js|mjs|cjs|ts)$/)` but we have this error:
`Unknown file extension ".ts" for /Users/$$/projects/$$/src/report/audits/has-max-empty-nodes.ts`

### How were you running Lighthouse?

node

### Lighthouse Version

10

### Node Version

16.19.1

### OS

Mac OS Ventura

### Relevant log output

```shell
ERROR (66645): Cannot find module '/Users/$$/projects/$$/src/report/audits/has-max-empty-nodes.ts.js' imported from /Users/$$/projects/$$/node_modules/lighthouse/core/config/config-helpers.js
    additionalErrors: []
    location: "tools.js:38"
    error: {
      "kind": "Error",
      "message": "Cannot find module '/Users/$$/projects/$$/src/report/audits/has-max-empty-nodes.ts.js' imported from /Users/$$/projects/$$/node_modules/lighthouse/core/config/config-helpers.js",
      "stack":
          Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/$$/projects/$$/src/report/audits/has-max-empty-nodes.ts.js' imported from /Users/$$/projects/$$/node_modules/lighthouse/core/config/config-helpers.js
              at new NodeError (node:internal/errors:387:5)
              at finalizeResolution (node:internal/modules/esm/resolve:330:11)
              at moduleResolve (node:internal/modules/esm/resolve:907:10)
              at defaultResolve (node:internal/modules/esm/resolve:1115:11)
              at nextResolve (node:internal/modules/esm/loader:163:28)
              at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
              at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
              at ESMLoader.import (node:internal/modules/esm/loader:525:22)
              at importModuleDynamically (node:internal/modules/esm/translators:110:35)
              at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
      "code": "ERR_MODULE_NOT_FOUND"
    }
```

**Comment by paulirish** [comment]
We're sorry this was working but no longer is. Hopefully the docs adam linked to help you out. 

If there's like a 2-line patch that will resolve this (adding that file extension and something else), then .. sure. We'll consider that.

But if it's more involved, we're not excited about ensuring this infrastructure always continues to run with ts-node's runtime.
