### ISSUE TITLE
Adding <video width="1920" height="1080" gerentates SPEEDINDEX_OF_ZERO / NO_LCP

### ISSUE THREAD

**Issue by matheszabi** [GoogleChrome/lighthouse#14852]
Of course, if I remove the width="1920" height="1080" attributes there is no error.
Check removed: https://analizacostbeneficiu.ro/

**Comment by adamraine** [comment]
Images that occupy the entire viewport are not considered to be LCP elements. This is most likely what is happening for you. I can't reproduce this on the url you sent though.

**Comment by paulirish** [comment]
You should add a poster image to the video. Without one, the video element can't qualify for LCP.
