### ISSUE TITLE
why lighthouse pointing on my server every day ?

### ISSUE THREAD

**Issue by mserbouti** [GoogleChrome/lighthouse#14868]
Hello,
I have a problem, I have logs from chrome lighthouse point to my server every day on my access log, like:

**................"-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4590.2 Safari/537.36 Chrome-Lighthouse"**

thanks in advance

**Comment by adamraine** [comment]
Sounds like someone is using Lighthouse or PSI to test your sight. We can't really control who accesses your sight using our tools.
