### ISSUE TITLE
Generation of Lighthouse PWA report breaks PWA install

### ISSUE THREAD

**Issue by targettadams** [GoogleChrome/lighthouse#14867]
I have a React SPA which is hosted in IIS. The server maps the app's URL (https://www.targettadams.co.uk/scorer) to a specific port on the server (that is, the server is operating as a reverse proxy as I have multiple services running side-by-side with the app that I wish to access, at this stage, through the same domain).

I have been migrating the SPA to a PWA and have been using the Lighthouse PWA report to guide me. On the whole, I have got things to work (I can successfully install the PWA). However, I have noticed some strangeness when I have subsequently been trying to run a lighthouse PWA report. The follwoing points basically summarise what I am seeing:

1) When I navigate to the app's URL, I see the PWA download icon in the address bar, and when I press it, it installs the app. When I press this icon, I notice that various logo*.png files are being requested, and successfully so.

2) I run a lighthouse PWA report. I see an error in relation to the service worker being registered:

Does not register a service worker that controls page and start_url. This origin has one or more service workers, however the page (https://www.targettadams.co.uk/scorer) is not in scope.

Basically, I have come to live with this error as the app is installable and I can see that a service worker is being registered successfully (on the Application tab of dev tools). I have assumed it simply does not like the reverse proxy set-up.

3) But now, if I try to install the app, it hangs. Eventually, the requests that are trying to get the logo*.png time out with 502 errors. 

4) If, while it hangs, I clear out the browser's site data/cookies and images, the install icon immediately comes to life and I can install the app. However, the next time I press the install icon, it hangs again, and I have to clear the storage again, and so on. If I open and close the browser, it still hangs. The only way I can return things to a functioning state is to clear out the browser's site data/cookies and images, close down the browser, and reopen (and make sure I don't attempt to generate another Lighthouse report). 

5) I have also noticed, but this is more sporadic and I don't have a proper handle on recreating the issue yet, that, sometimes, in this state of strangeness following the generation of the Lighthouse report, if I reload the page, it takes me to https://www.targettadams.co.uk and not https://www.targettadams.co.uk/scorer. The reverse proxy maps this former URL to a different site which simply serves a default page. I only mention this because it suggests a vague correlation with not been able to locate the logo*.png files anymore.

That's it. Thanks for your patience in reading. It's not too much of a biggie for me at the moment, but it would be good to understand what is going on, and I thought I would flag it just in case it was actually an issue with Lighthouse.

**Comment by adamraine** [comment]
https://www.targettadams.co.uk/scorer isn't installable for me in any scenario, so I can't reproduce the issue you are talking about. Is there some extra action I need to take to get the app to be installable under normal circumstances?

That being said, Lighthouse will clear all service workers before testing the page by default which may be causing the issue you are seeing. If you want to disable to storage reset, you can uncheck "Clear storage" in the Lighthouse panel in DevTools or uses the `--disable-storage-reset` flag on the CLI.

**Comment by targettadams** [comment]
Thanks for the swift response.

Ah, yes - apologies - my set-up is a bit old-school at the moment: it is on a box in my office; accessible to the outside world, but the server is constantly up and down at the moment. I'll leave it on for the next 24 hours. It'll be pretty slow.

Brilliant - yes - unchecking 'clear storage' removes the issue and allows me to generate the report alongside installing the app with no issues. Thanks for that.

Before you close the ticket, do you mind just shedding some light on whether the error in point 2) of my original message is anything to worry about? It doesn't seem to be ...

**Comment by adamraine** [comment]
> Before you close the ticket, do you mind just shedding some light on whether the error in point 2) of my original message is anything to worry about? It doesn't seem to be ...

Yes that is probably you should investigate. It's possible the page is installing a service worker with the wrong [scope](https://web.dev/learn/pwa/service-workers/#scope).
