### ISSUE TITLE
Google PageSpeed ​​Insights  Error

### ISSUE THREAD

**Issue by andreyledenyov** [GoogleChrome/lighthouse#14872]
Our development team uses Google PageSpeed ​​Insights to test site speed https://testsite-mds.metinvest-smc.com/. Intermittently when testing Google PageSpeed ​​Insights I get messages:

1. Could not navigate to https://testsite-mds.metinvest-smc.com/. Check URL is correct 
2. Determine actual site performance - No data 
3. Detect performance issues - Error requesting document. 

Please help me to find the reason for this error.

**Comment by rachelandrew** [comment]
@andreyledenyov I've moved this issue to the Lighthouse repo, as that's a better place to get this one answered. The web.dev repo is for content issues with the web.dev site.

**Comment by andreyledenyov** [comment]
Our development team uses Google PageSpeed ​​Insights to test site speed https://testsite-mds.metinvest-smc.com/. Intermittently when testing Google PageSpeed ​​Insights I get messages:

Could not navigate to https://testsite-mds.metinvest-smc.com/. Check URL is correct
Determine actual site performance - No data
Detect performance issues - Error requesting document.
Please help me to find the reason for this error.

**Comment by adamraine** [comment]
I haven't been able to reproduce this yet. It's possible that the PSI upgrade to Lighthouse 10 this week fixed it. @andreyledenyov are you still seeing this error?

**Comment by andreyledenyov** [comment]
Thanks. now all Working. What fixes have been made?

**Comment by adamraine** [comment]
Not sure, a lot of changes have been made to Lighthouse and PSI as part of that release. I don't think it's worth it to investigate unless this starts happening again.
