### ISSUE TITLE
Chrome v111 with Lighthouse 9.6.8 error - Cannot create new tab, and no tabs already open

### ISSUE THREAD

**Issue by abhinav-saini** [GoogleChrome/lighthouse#14885]
**FAQ**
 Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
 Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

**URL**
Issue is with all domains - https://google.com or any domain

**What happened?**
When using Lighthouse 9.6.8 with Chrome 111.0.5563.64, if you will call Lighthouse scan for any domain, an error saying **Cannot create new tab, and no tabs already open** will be thrown in the second iteration (i=2). The issue does not happen in the first iteration (when i=1).

```
const iterations = 5;
for (let i = 1; i <= iterations; i++) {
        logger.debug(`Running ${i} scan for ${target} - ${correlationId}`);
        const runnerResult = await lighthouse(target, {
          logLevel: 'error',
          output: 'html',
          maxWaitForLoad: 60000,
          // skipAudits: ['full-page-screenshot'],
          onlyCategories: [
            'accessibility',
            'best-practices',
            'performance',
            'pwa',
            'seo',
          ],
          port: this.chrome.port,
          hostname: '127.0.0.1',
        });
        lhrs.push(runnerResult.lhr);
}
```

This issue is not faced if we downgrade to any of the older stable Chrome versions - v110 or below. 
The same code has been working since an year so I can assure that there is nothing wrong with the other logic used in application.

**What did you expect?**
Multiple scans iterations for same chrome instance was supported for v110 or below, same should be working with v111.

**What have you tried?**
Tried downgrading to Chrome v110 and below fixed the issue.

**How were you running Lighthouse?**
Programmatically 

**Lighthouse Version**
9.6.8

**Chrome Version**
111.0.5563.64

**Node Version**
18.12.1

**OS**
Linux

**Relevant log output**
Anyone can replicate it easily using the above shared code with shared versions of Lighthouse and Chrome.

```
debug: Running 1 scan for https://www.google.com/en - f9363d96-a81d-42d2-b1ee-d5e714668fc4
debug: Running 2 scan for https://www.google.com/en - f9363d96-a81d-42d2-b1ee-d5e714668fc4

error: Got error for https://www.google.com/en/ - f9363d96-a81d-42d2-b1ee-d5e714668fc4 - Cannot create new tab, and no tabs already open.
```

**Comment by adamraine** [comment]
I can repro with v9.6.8 but I can't repro with v10.0.2 so I think this has been fixed already.
