### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by andirosu** [GoogleChrome/lighthouse#14882]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://magazinulcolectionarului.ro/

### What happened?

I was using pagespeed.web.dev on multiple site, but on this one specifically, the desktop test shows the message "Unknown error - Lighthouse has encountered an error while loading the requested page."
The mobile test show results. 

### What did you expect?

Output test result for desktop or a more specific error message, so we could try and fix it on our side.

### What have you tried?

Different browser, different website.

**Comment by adamraine** [comment]
I can't reproduce this. Is it happening every time for you?

**Comment by adamraine** [comment]
I'm still not able to reproduce this.

What browser location is report for you on the successful mobile report? You can find it in the report:

![image](https://user-images.githubusercontent.com/6752989/226443475-ab9c949f-f115-469b-84e2-1bb9a27d6809.png)
