### ISSUE TITLE
PSI: fullPageScreenshot in Lighthouse 10

### ISSUE THREAD

**Issue by alekseykulikov** [GoogleChrome/lighthouse#14886]
### What happened?

The newest Lighthouse v10 has been released to PSI today. The PSI response doesn't have `fullPageScreenshot` attribute, which was moved from `audits['full-page-screenshot']` in v10. It's also unspecified in [PSI docs](https://developers.google.com/speed/docs/insights/rest/v5/pagespeedapi/runpagespeed#lighthouseresultv5).

But, it's available at [pagespeed.web.dev](https://pagespeed.web.dev/) as `window.__LIGHTHOUSE_JSON__.fullPageScreenshot`, therefore it's an issue with PSI API response.

```bash
curl "https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://treo.sh/" > treo1.json 
```

### What did you expect?

Add `fullPageScreenshot` to PSI API response.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

10.0.2

**Comment by paulirish** [comment]
Thanks for catching and reporting. We'll fix.

**Comment by ejerskov** [comment]
Has this been fixed? I still dont see the full screenshot in the pagespeed api

**Comment by paulirish** [comment]
Nope. This got held up for annoying reasons but we've been pushing on it. I'm hoping its deployed in the next 12 hrs..

**Comment by paulirish** [comment]
It's rolling out now. 1/4 done. Should be complete within the next 3 hours.

**Comment by alekseykulikov** [comment]
Thanks for the quick fix!
