### ISSUE TITLE
`redirects` audit perhaps too lenient

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#14895]
The `redirects` audit currently always passed when there is a single redirect present, even if significant:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/4071474/225412892-03f0de69-564d-44db-94ae-f6d76bf13e62.png">

It's been this way since it was introduced:

https://github.com/GoogleChrome/lighthouse/pull/3308/files#diff-dd1c921c5fb418fc98a727bbbfca7e0ca696b0441fd5c9b5ebf6353df72b2168R46-R50

The impact of hiding this audit in this case is not so bad, since there will be a very visible warning at the top of the report about a redirect. But, in PSI when `use_original_url=true` is set, the information is hidden away. Also, if we end up grouping audits by LCP phase we're going to want this audit to not show as passing when there is a real problem.

I couldn't work out why an allowance was made for a single redirect, does anyone know?

**Comment by adamraine** [comment]
With our focus on audit impact vs arbitrary scoring criteria, we should definitely do this.
