### ISSUE TITLE
PSI: Ignore redirect as on pagespeed.dev

### ISSUE THREAD

**Issue by ejerskov** [GoogleChrome/lighthouse#14892]
On pagespeed.web.dev its possible to ignore redirects (with the flag &use_original_url=true) - any reason why thats not possible through the Pagespeed API?

**Comment by hjelmdal** [comment]
+1!

**Comment by paulirish** [comment]
We have some magic in the PSI webapp... like.. you can just enter `example.com` and we'll automatically add `https://. And we also have this automation redirect resolving behavior.

In the API, we don't want magic. We want to take the URL you give us and test that. If there's a redirect involved, then you can resolve that yourself (`curl -L`!) and pass that to us.

---

fwiw `use_original_url=true` means _don't_ ignore the redirect. aka include the cost of the redirect. And that is how the API works,.

**Comment by ejerskov** [comment]
Thanks for clarifying @paulirish, however I have just one more question.

So if I want to run at pagespeed test through the API on a page that redirects automatically based on location, there's no way of doing that?
From what I can tell the API is primarily located in the US, which often causes redirects on european sites

**Comment by paulirish** [comment]
cc @jazyan 

Both the website and the API will (currently) route to one of these 4 locations: https://www.debugbear.com/blog/why-is-my-lighthouse-score-different-from-pagespeed-insights

The routing is based off of the IP location that is making the request. (If it's coming from a cloud vm, the location of that vm matters). So.. we try to use european servers for all european requests but... load balancing means we can't guarantee it.

AFAIK that article is correct and our EU location is in .nl (though this may change)... 

But.. Yeah i understand your usecase. (a site that changes content served based on location).. and why you want the behavior to be a bit more deterministic.

Just to make things a tad more annoying for you..... We did add a feature so on the site you can see what location was used: 
<img width="384" alt="image" src="https://user-images.githubusercontent.com/39191/227074442-f75e7cb1-b95f-4328-a46d-bf59c6aa1442.png">
.... however that data is not in the API response. (Though we could add it... just didnt get around to it yet)

> So if I want to run at pagespeed test through the API on a page that redirects automatically based on location, there's no way of doing that?

We can't guarantee which location we're going to use. Sorry

I would suggest you add a url param or hash that your backend handles and _doesnt_ do the typical redirect. That seems like the best solution here.
