### ISSUE TITLE
URL shouldn't be passed into gatherers

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#149]
Once manifest lands, I think it'll only be used in  the "url" gather... 

I _think_ this weird "gather" was to help out the chrome extension, so we probably need to sort that out, but it shouldn't be hard.

**Comment by brendankenny** [comment]
the scheduler can push the url into the artifacts as it does in #148 with network records and the trace

**Comment by paulirish** [comment]
fixed nowadays
