### ISSUE TITLE
11.0 Breaking Changes

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#14909]
Need to have
- [x] https://github.com/GoogleChrome/lighthouse/issues/15060
	-  Done, remaining items are not breaking or not a high priority
- [x] https://github.com/GoogleChrome/lighthouse/pull/15252
	- (followup from #14910) 
- [x] https://github.com/GoogleChrome/lighthouse/pull/15290
	- https://github.com/nodejs/release#release-schedule
	- https://nodejs.org/en/blog/announcements/nodejs16-eol
- [x] https://github.com/GoogleChrome/lighthouse/pull/15279
- [x] https://github.com/GoogleChrome/lighthouse/pull/15257
- [x] New axe rules: http://go/prcpg
- [ ] ~Combine `long-tasks` and `mainthread-work-breakdown`~
	- After some further discussion. These audits are different enough to keep separate.
- [x] https://github.com/GoogleChrome/lighthouse/pull/15299
- [x] https://github.com/GoogleChrome/lighthouse/pull/15285
- [x] https://github.com/GoogleChrome/lighthouse/pull/15219

Nice to have
- [x] https://github.com/GoogleChrome/lighthouse/issues/12788
- [x] https://github.com/GoogleChrome/lighthouse/issues/15163
- [ ] ~(Punt) https://github.com/GoogleChrome/lighthouse/pull/14878~
- [ ] ~(Punt) https://github.com/GoogleChrome/lighthouse/issues/12345~
- [ ] ~(Punt) https://github.com/GoogleChrome/lighthouse/issues/14048~
	- Should be done after we drop legacy 
- [ ] ~(Punt) https://github.com/GoogleChrome/lighthouse/issues/14354~
- [ ] ~(Punt) https://github.com/GoogleChrome/lighthouse/issues/15203~
- [ ] ~(Punt) Drop `third-party-summary` and move blocking time signal somewhere else (`long-tasks`?)~
	- 	Alternatively: just hide it but keep the data
- [ ] ~(Punt) Merge `bootup-time` (JS execution time audit) into `long-tasks`~
- [ ] ~(Punt) Remove `ScriptElements`?~

**Comment by shannawha** [comment]
automune is a big problem dom mutation will give you eye problems there is eye mutation with  3D PORN R AND  IM THINKING THAT WHY THERE IS PROBLEMS WITH THE G2 is becuse you are configuring fcp 3g  to be biger than g2 it isnt think of it like a house with a basement g2 is that house and g3 thinks he has a basementand can face a f5 so when the 11 brakes it is telling you it just got flatenout 11.5 it is nolonger cad but salvation army inorder to fix 11.0  and you are g27 and you have  RCA will kepp the 11 without noise but has captures and if you dont clean it up every day you will start to brake your platform  with your R fcp-3g   you cannot have blueprints you can only  have minitures as soon as you remove thee G3 your G2 will be under supervision and can withstand that f5 then you can add your g3 for other level braking basicly you made your g3 3d reverseable like a bubble boy makes me think r a d porn has restricted by the f5 makeing the storm as big as the man at one time long time ago please please get intouch with the orginal owner of the phone and turn it back to them or turn it into the police i f=dont care please ........

**Comment by brendankenny** [comment]
Node 16 is going [end of life early in September 2023](https://nodejs.dev/en/about/releases/). We should consider dropping support.

**Comment by brendankenny** [comment]
consider revving `lighthouse-logger` to 2.0.0 so the horizon for [unexpected breaking changes](https://github.com/GoogleChrome/lighthouse/issues/15085) is significantly shortened

**Comment by adamraine** [comment]
Address some troubles with unit tests in Node 19+: https://github.com/GoogleChrome/lighthouse/pull/14977/files#r1199641414
