### ISSUE TITLE
Remove FCP (3G)

### ISSUE THREAD

**Issue by Generosus** [GoogleChrome/lighthouse#14905]
Good Day,

It would be great if you guys can update PSI and Lighthouse to [replace FCP (3G) with FCP (4G) testing](https://prnt.sc/2Cedf2IICwBK).

4G population coverage surpassed 85% globally at the end of 2021 and is expected to reach 95% in 2028. Further, [3G networks have already been shut down or will soon.](https://onomondo.com/resource-hub/2g-3g-sunset/#sunset-dates)

Thank you :)

**Comment by adamraine** [comment]
The audit you highlighted is an extra diagnostic that does not contribute to your performance score. The FCP value at the top of the report is calculated for a 4G network.

**Comment by Generosus** [comment]
Hey @adamraine,

Again, thanks for your valuable input. Looks like many are keeping you busy :)

Yeah, we noticed that too. So, if the 3G diagnostic offers no intrinsic value and we  know that the 3G network is nearing Sunset, why not delete it from PSI/LH? For many, it can be confusing and/or stir the pot by forcing web devs (or wannabes) to perform extra work on their site(s) in an attempt to eliminate the 3G "warning." 

We propose deleting it from PSI/LH. Will help simplify things and eliminate all confusion.

Thank you.

**Comment by adamraine** [comment]
Yeah we think it's reasonable to remove this now. Turns out it should have been a hidden audit, so this is actually a bug that went unnoticed for a while.

**Comment by Generosus** [comment]
Hey @adamraine,

That's great news. Looking forward to the update.

Thank you!
