### ISSUE TITLE
Error in fullpagescreenshot gatherer will break the entire report

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#14922]
Saw this in https://github.com/GoogleChrome/lighthouse/pull/14920. Any error thrown in the gatherer should do.

Instead of breaking the whole report, we should just remove the screenshot stuff from the report.

**Comment by paulirish** [comment]
Ah that's good stuff. :)

![image](https://user-images.githubusercontent.com/39191/227069084-b2c5258d-8746-4a07-b6b3-a80697a289ad.png)

![image](https://user-images.githubusercontent.com/39191/227069165-0c6d2cf8-792b-4e8f-8fa6-9dd407bcd7d5.png)
