### ISSUE TITLE
Error: Cannot create new tab, and no tabs already open

### ISSUE THREAD

**Issue by tcottington** [GoogleChrome/lighthouse#14930]
We've had a DevOps pipeline running Lighthouse daily for the past few months until March 17th it suddenly started failing each day.

Here are the commands we use:
cd <to our file path in which the project exists>
npm install --save-dev @types/lighthouse
npm install @azure/cosmos --save
npm install static-server 
node scoreGenerator.js

Score generator kicks off the lighthouse command and starts scoring several websites in one run.

Here is the error we receive, which previously never occurred:

```
LH:status Auditing: Document has a valid `rel=canonical` +1ms
  LH:status Auditing: Structured data is valid +1ms
  LH:status Generating results... +0ms
  LH:status Connecting to browser +180ms
  LH:CriConnection:warn Cannot create new tab; reusing open tab. +21ms
  LH:status Disconnecting from browser... +2ms
  LH:status Cleaning origin data +0ms
  LH:CriConnection:error sendRawMessage() was called without an established connection. +0ms
  LH:GatherRunner disconnect:error sendRawMessage() was called without an established connection. +1ms
(node:41180) UnhandledPromiseRejectionWarning: Error: Cannot create new tab, and no tabs already open.
    at D:\Work\Repo\Testing\Lighthouse\node_modules\lighthouse\lighthouse-core\gather\connections\cri.js:45:35
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Driver.connect (D:\Work\Repo\Testing\Lighthouse\node_modules\lighthouse\lighthouse-core\gather\driver.js:119:5)
    at async Function.run (D:\Work\Repo\Testing\Lighthouse\node_modules\lighthouse\lighthouse-core\gather\gather-runner.js:486:7)
    at async Function._gatherArtifactsFromBrowser (D:\Work\Repo\Testing\Lighthouse\node_modules\lighthouse\lighthouse-core\runner.js:264:23)
    at async Function.gather (D:\Work\Repo\Testing\Lighthouse\node_modules\lighthouse\lighthouse-core\runner.js:170:21)
    at async lighthouse (D:\Work\Repo\Testing\Lighthouse\node_modules\lighthouse\lighthouse-core\index.js:50:21)
    at async D:\Work\Repo\Testing\Lighthouse\scoreGenerator.js:108:26
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:41180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As stated, this has been working for several months up until March 16. Any sort of help is appreciated.

**Comment by adamraine** [comment]
We are going to need more information to reproduce this:

- Lighthouse version
- Chrome version
- Code for a script that can reproduce this

> npm install --save-dev @types/lighthouse

We don't publish a `@types/lighthouse` package. To install the official Lighthouse package do `npm install --save-dev lighthouse`

**Comment by izi-p** [comment]
Hey same error on github action +  @lhci/cli@0.7.x + Node 16.19.1 since Mar. 15th. 

Any update on this?

**Comment by adamraine** [comment]
@izi-p I am not able to reproduce this with the lhci version(s) you mentioned. If you can provide steps to reproduce this error  please share them, otherwise we will have to close this for lack of information.

**Comment by izi-p** [comment]
@adamraine it looks like it is the same as this issue 

https://github.com/GoogleChrome/lighthouse-ci/issues/886

**Comment by adamraine** [comment]
@izi-p that issue has been closed with the latest lighthouse CI release. Can you confirm that this resolves your issue?

**Comment by tcottington** [comment]
> @izi-p that issue has been closed with the latest lighthouse CI release. Can you confirm that this resolves your issue?

I can confirm that the latest lighthouse CI release did not resolve the issue seen. I will be providing better context soon.

**Comment by tcottington** [comment]
> We are going to need more information to reproduce this:
> 
> * Lighthouse version
> * Chrome version
> * Code for a script that can reproduce this
> 
> > npm install --save-dev @types/lighthouse
> 
> We don't publish a `@types/lighthouse` package. To install the official Lighthouse package do `npm install --save-dev lighthouse`

Lighthouse version 10.1.1
Chrome version 112.0.5615.138
Node version 14.16.0

I apologize in advance for the way the code snippet is formatted. For some reason it only formats some of my code.

Here is a stream lined version of the script. What this should do is:

1. read a csv file with full urls to test
2. go through each url and run lighthouse
3. store those scores into a .txt file.

`// Import the required npm packages
const fs = require("fs");
const lighthouse = require("lighthouse");
const chromeLauncher = require("chrome-launcher");

const scoreDate = new Date();

const removeKeys = (obj, keys) =>
  obj !== Object(obj)
    ? obj
    : Array.isArray(obj)
    ? obj.map((item) => removeKeys(item, keys))
    : Object.keys(obj)
        .filter((k) => !keys.includes(k))
        .reduce(
          (acc, x) => Object.assign(acc, { [x]: removeKeys(obj[x], keys) }),
          {}
        );

// Read the csv file and store the
// urls in an array
var array = fs.readFileSync("URLs.csv").toString().split("\n");

// The async await is used to ensure
// non-blocking code execution
(async () => {
  const chrome = await chromeLauncher.launch({ chromeFlags: ["--headless"] });

  // Declaring an object to specify score
  // for what audits, categories and type
  // of output that needs to be generated
  const options = {
    logLevel: "info",
    output: "json",
    onlyCategories: ["performance", "accessibility", "best-practices", "seo"],
    audits: [
      "first-meaningful-paint",
      "first-cpu-idle",
      "byte-efficiency/uses-optimized-images",
    ],
    port: chrome.port,
  };

  const desktopConfig = {
    extends: "lighthouse:default",
    settings: {
      formFactor: "desktop",
      throttling: {
        rttMs: 40,
        throughputKbps: 10 * 1024,
        cpuSlowdownMultiplier: 1,
        requestLatencyMs: 0, // 0 means unset
        downloadThroughputKbps: 0,
        uploadThroughputKbps: 0,
      },
      screenEmulation: {
        mobile: false,
        width: 1350,
        height: 940,
        deviceScaleFactor: 1,
        disabled: false,
      },
      emulatedUserAgent:
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4695.0 Safari/537.36 Chrome-Lighthouse",
    },
  };

  // Traversing through each URL
  for (i in array) {
    //send score to txt file 5 times per website/strategy type
    for (let pass = 0; pass < 5; pass++) {
      // Separate strategy for Mobile
      // and Desktop view
      for (let x = 0; x < 2; x++) {
        let configuration = "";

        let runnerResult;
        //sets the scoring to be mobile or desktop
        if (x == 0) {
          options.strategy = "mobile";
          runnerResult = await lighthouse(array[i], options);
        } else {
          options.strategy = "desktop";
          runnerResult = await lighthouse(array[i], options, desktopConfig);
        }

        let value = {
          id:
            runnerResult.lhr.finalUrl.replace(/https?:\/\/|\/+/g, "") +
            "|" +
            scoreDate +
            "|" +
            options.strategy +
            "|" +
            pass,
          scoreDate: scoreDate.toString(),
          url: runnerResult.lhr.finalUrl,
          report: JSON.parse(runnerResult.report),
        };

        const cleanedVariable = removeKeys(value, ["data"]);

        //push each report(mobile and desktop) to result.
        fs.appendFileSync("lhreport.txt", JSON.stringify(cleanedVariable));
      }
    }
  }
  await chrome.kill();
})();`


the csv file is just urls, no commas for seperation, just a new line

![image](https://user-images.githubusercontent.com/47061729/235497776-96cd0cbb-e840-4a56-ad15-c3e321bd6da2.png)


and then after it does 1 score pass, this is the error I receive:
![image](https://user-images.githubusercontent.com/47061729/235498822-4e1deced-5c4e-4072-abd4-19af3bc076af.png)

**Comment by adamraine** [comment]
@tcottington I was not able to reproduce with the script you have provided, but a few things stand out:

- You say that your node version is 14.16.0, however we haven't supported this version of Node since Lighthouse 10.0. You should be getting a runtime error if you are using Lighthouse 10.1.1 with node 14.
- The script uses `const lighthouse = require('lighthouse')` however this shouldn't be possible with version 10.1.1 since we upgraded to ESM in Lighthouse 10.0
- The console messages in the log you provided come from our legacy navigation runner, which we deprecated in Lighthouse 10.0

It seems like you are using an older Lighthouse version (pre-10.0) than you are expecting. Can you please verify that the Lighthouse version in your `node_modules` directory is what you are expecting?

**Comment by tcottington** [comment]
@adamraine turns out I was using lighthouse 9.6.5, updated that to 10.1.1, and then updated node to 18.16.0. After converting it to ESM I have the script working correctly. You're a life saver!

**Comment by bmerigan** [comment]
It's unfortunate I need to convert code to ESM in order to resolve the issue, but at least there's a way forward.

**Comment by baissinghabhishek** [comment]
@tcottington Hello, I am facing the same issue after the Chrome update. Based on your update I have updated lighthouse and node to the latest. However I am not sure how to convert my typescript to ESM . I am using a script similar to whats here : https://github.com/akagupta9/lighthouse-wrapper.
Little guidance on how to convert it to ESM would be great, thanks in advance.
