### ISSUE TITLE
Runtime error encountered: Unexpected token '||='

### ISSUE THREAD

**Issue by rpong** [GoogleChrome/lighthouse#14944]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://onepropertee.com

### What happened?

This is the exact error we encountered:

```
Runtime error encountered: Unexpected token '||='
SyntaxError: Unexpected token '||='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:149:18)
    at async link (internal/modules/esm/module_job.js:67:21)
```

The Command used is: 
`lighthouse --chrome-flags='--headless --no-sandbox' "https://onepropertee.com" --formFactor=mobile --output-path=./lighthouse-reports/lighthouse-results-v1.0.0.html --quiet --output=html,json`

Our Node version is: v14.21.2

This only happens with lighthouse 10.1.0, it worked again when we downgraded to 10.0.1

### What did you expect?

We expect the lighthouse report to be generated, we instead got the error as above.

### What have you tried?

We downgraded to 10.0.1 which worked.

### How were you running Lighthouse?

node

### Lighthouse Version

10.1.0

### Chrome Version

111.0.0.0

### Node Version

v14.21.2

### OS

MacOS

### Relevant log output

```shell
Runtime error encountered: Unexpected token '||='
SyntaxError: Unexpected token '||='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:149:18)
    at async link (internal/modules/esm/module_job.js:67:21)
```

**Comment by adamraine** [comment]
Our [minimum support Node version is 16.16](https://github.com/GoogleChrome/lighthouse/blob/main/package.json#L13). This operator is not available in Node 14.
