### ISSUE TITLE
Lighthouse CLI --extra-headers issue

### ISSUE THREAD

**Issue by kendzisah** [GoogleChrome/lighthouse#14956]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://example.com

### What happened?

Currently I am trying to run Lighthouse CLI in Powershell. The problem is whenever I try to pass Stringify'd JSON HTTP Header key/value pairs to the --extra-headers query it returns an error stating: "Unexpected token \ in JSON at position 1"

Here is an example of the code I would like to run: 
`lighthouse https://example.com  --extra-headers "{\"Authorization\": \"Bearer abc123\"}" --output=json --output-path="./report.json"    `

 I have also tried to put the object in a json file and pass it to --extra-headers, but it will load the page and take me to a 401 page saying I have unauthorized access.

Any solutions on how I can get past the problem or potentially work around it?

### What did you expect?

I expect the --extra-headers to take the authentication token passed into it to authenticate lighthouse on my website and eventually run a performance test on my website.

### What have you tried?

I have tried passing in a json file, using a json config file, and even '{"Authorization":"Bearer 123"}' and '{"Authorization":"Bearer123"}'

### How were you running Lighthouse?

CLI

### Lighthouse Version

v10.1.0

### Chrome Version

Version 111.0.5563.147

### Node Version

18.12.0

### OS

Windows

### Relevant log output

```shell
Unexpected token \ in JSON at position 1
LH:NavigationRunner:error Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 401)
Unexpected token A in JSON at position 1
```

**Comment by adamraine** [comment]
The command works fine on MacOS, I suspect this has to do with how the windows shell handles the stringified json similar to https://github.com/GoogleChrome/lighthouse/issues/14137. As that issue suggests, try exporting your flags to a json file and load with `--cli-flags-path`.
