### ISSUE TITLE
Low Performance Scores when running lighthouse through cli compared to dev.

### ISSUE THREAD

**Issue by 1ms19is112** [GoogleChrome/lighthouse#14953]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://spark.jllt.com/philosophy/

### What happened?

I am getting low scores of Performance & Accessibility, and metrics such as First Contentful Paint, Speed Index, etc. when running lighthouse through cli as compared with lighthouse through dev. Below is my lighthouse config file.

```
const DEVTOOLS_RTT_ADJUSTMENT_FACTOR = 3.75;
const DEVTOOLS_THROUGHPUT_ADJUSTMENT_FACTOR = 0.9;

const throttling = {
  DEVTOOLS_RTT_ADJUSTMENT_FACTOR,
  DEVTOOLS_THROUGHPUT_ADJUSTMENT_FACTOR,  
  // Using a "broadband" connection type
  // Corresponds to "Dense 4G 25th percentile" in https://docs.google.com/document/d/1Ft1Bnq9-t4jK5egLSOc28IL4TvR-Tt0se_1faTA4KTY/edit#heading=h.bb7nfy2x9e5v
  desktopDense4G: {
    rttMs: 40,
    throughputKbps: 10 * 1024,
    cpuSlowdownMultiplier: 1,
    requestLatencyMs: 0, // 0 means unset
    downloadThroughputKbps: 0,
    uploadThroughputKbps: 0,
  },
};

const DESKTOP_EMULATION_METRICS = {
  mobile: false,
  width: 1350,
  height: 940,
  deviceScaleFactor: 1,
  disabled: false,
};

const screenEmulationMetrics = {
  desktop: DESKTOP_EMULATION_METRICS,
};

const DESKTOP_USERAGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4695.0 Safari/537.36'; // eslint-disable-line max-len

const userAgents = {
  desktop: DESKTOP_USERAGENT,
};

module.exports = {
    extends: 'lighthouse:default',
        settings: {
          onlyCategories: ['performance', 'accessibility','best-practices','seo'],
          formFactor: 'desktop',
          throttling: throttling.desktopDense4G,
          screenEmulation: screenEmulationMetrics.desktop,
          emulatedUserAgent: userAgents.desktop,
      }

}
```

I need to find a way so that my lighthouse reports running through the dev way on incognito window are in sync with the reports running through cli way. 
I have tried to make the settings as same as possible in the emulation environment but the two still differ in values. 

[DEV Report](https://1ms19is112.github.io/dev-report/) 
[CLI Report](https://1ms19is112.github.io/cli-report/) 

### What did you expect?

Expected same values when performing lighthouse through cli as well as lighthouse through dev tools.

### What have you tried?

I have tried multiple different settings but the mentioned settings are the ones that provided me with relatively more closer values to lighthouse through the dev way.

### How were you running Lighthouse?

CLI, Chrome DevTools

### Lighthouse Version

9.6.8

### Node Version

v18.14.2

### OS

Window

**Comment by adamraine** [comment]
We cannot guarantee the exact same performance metrics on every single Lighthouse. This looks like normal page variance.

**Comment by dryabov** [comment]
@1ms19is112 Note the difference in the Initial server response time (450ms vs 600ms) that affects many of other metrics. Also from screenshots it looks like there is a difference in screen sizes (affects LCP and CLS).
