### ISSUE TITLE
PSI Error: generic::internal: Error unmarshalling JSON into proto

### ISSUE THREAD

**Issue by mav-jaspery** [GoogleChrome/lighthouse#14958]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://rainbowcentre.org.sg/

### What happened?

We are using PageSpeed Insights to test our website's performance, then we found only our homepage will get this error but other pages went well(can generate report). We also use devtools and cli to test the homepage locally it also worked, but many of our people have different network conditions so we still want to get report from PSI.
<img width="971" alt="image" src="https://user-images.githubusercontent.com/127826281/230910819-7f2b4032-6695-4610-9d50-15d0891f129c.png">

### What did you expect?

PSI generate report as HTML format for human read, not json.

### What have you tried?

Used lighthouse devtool and nodejs cli version to test this url locally, and it all work and generate the html report, so I believe it's a PSI UI problem.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

10.0.2

### OS

Mac

### Relevant log output

```shell
Oops! Something went wrong.
generic::internal: Error unmarshalling JSON into proto: {"lighthouseVersion":"10.0.2","requestedUrl":"https://rainbowcentre.org.sg/","mainDocumentUrl":"https://rainbowcentre.org.sg/","finalDisplayedUrl":"https://rainbowcentre.org.sg/","finalUrl":"https://rainbowcentre.org.sg/","fetchTime":"2023-04-10T13:30:27.724Z","gatherMode":"navigation","runWarnings":[],"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/111.0.5563.146 Safari/537.36",...
```

**Comment by paulirish** [comment]
@mav-jaspery thanks very much for reporting! 

same issue as #14897  

> "snippet":"<img alt=\"𝗔𝘀 𝗽𝗮𝗿𝘁 𝗼𝗳 𝗼𝘂𝗿 𝗥𝗖𝟯𝟱 𝗮𝗻𝗱 𝗕𝗲𝘆𝗼𝗻𝗱 𝗰𝗮𝗺𝗽𝗮𝗶𝗴𝗻, \ud835…\"

fixed in [v10.1.0](https://github.com/GoogleChrome/lighthouse/releases/tag/v10.1.0)
