### ISSUE TITLE
LHR failed to render.

### ISSUE THREAD

**Issue by collinph** [GoogleChrome/lighthouse#14954]
### URL

https://JamSpiritSites.com

### What happened?

Did some speed improvements to our framework and now we get LHR failed to render errors.
Not sure what the error is.

### What did you expect?

Some results from lighthouse

### What have you tried?

Very few... it's running on your server so I have no idea what to do next.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

Not sure.. whatever is ran on dev.web.com

**Comment by paulirish** [comment]
repro https://pagespeed.web.dev/analysis/https-jamspiritsites-com/otp97siq1z?form_factor=mobile

**Comment by paulirish** [comment]
I broke PSI. Sorry everyone. Rollback on the way.

**Comment by paulirish** [comment]
@collinph Thanks very much for reporting. <3   

The rollback is halfway done. Some folks may see the issue resolved already. In ~10 minutes it'll be fully resolved.

**Comment by paulirish** [comment]
Fix is fully deployed as of 5:00pm (8min ago).
