### ISSUE TITLE
Chrome viewport incorrect w/puppeteer

### ISSUE THREAD

**Issue by benschwarz** [GoogleChrome/lighthouse#14968]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://chromestatus.com/features

### What happened?

Using the [Launch Chrome w/Puppeteer then handoff to LH example](https://github.com/GoogleChrome/lighthouse/blob/main/docs/puppeteer.md), I ran a test against the chrome status site. 

I altered the (aformentioned) example code to write `lhr` to `json`, then copied the JSON into Lighthouse viewer:

![image](https://user-images.githubusercontent.com/924/231949126-c750387e-5bdf-4c3a-9cc6-a0c46c9f940c.png)

All screenshots have incorrect viewport proportions (it appears to screenshot the entire browser window, not the emulated viewport):

![image](https://user-images.githubusercontent.com/924/231949753-a98c6423-6ea1-4c6c-ae3a-c5c420e91d65.png)

I'm uncertain whether this has any negative affect on metrics at this moment.

### What did you expect?

Screenshots to be correctly portioned to the mobile emulated device without any off-canvas rendering.

### What have you tried?

Observed in my own node based code, then used the example code provided as a repro. Failure is 100% consistent. 

### How were you running Lighthouse?

node

### Lighthouse Version

10.1.0

### Chrome Version

112 (Stable)

### Node Version

18.7.X

### OS

Mac

**Comment by adamraine** [comment]
This looks like the same issue as https://github.com/GoogleChrome/lighthouse/issues/12988, can you confirm that `ignoreDefaultArgs: ['--enable-automation']` on pptr launch args fixes the issue.

**Comment by benschwarz** [comment]
@adamraine 👍 Spot on. Thank you.

In the case of my code, I'd set `args` to pptr, so it was very unexpected that _defaults_ are still applied 😵‍💫

I've created #14978 to update the LH pptr example.
