### ISSUE TITLE
bfcache audit passes in HTTP Archive but fails locally

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#14965]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.biography.com/

### What happened?

When we ran this site through WebPageTest via HTTP Archive, it passed the bfcache audit:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/1120896/231499800-92e435a9-c2b6-4e37-bcaa-2042b4c1584a.png">

Test results: https://webpagetest.httparchive.org/lighthouse.php?test=230404_Dx1A5_9W1Y5&run=1

### What did you expect?

The audit should have failed. Running the bfcache eligibility check in DevTools, it fails spectacularly:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/1120896/231500133-7dbd6f8c-a3bb-4d50-b35b-d16e8516347f.png">

### How were you running Lighthouse?

WebPageTest

### Lighthouse Version

10.1.0

**Comment by adamraine** [comment]
@rviscomi any updates? Closing this issue as it looks like just different content between HTTPA and normal Lighthouse.
