### ISSUE TITLE
Why is the build trying to symlink the lighthouse cli into my node bin directory?

### ISSUE THREAD

**Issue by marijanp** [GoogleChrome/lighthouse#14966]
When trying to build lighthouse my build fails (my node bin directory is readonly), because at some point the build tries to symlink the `cli/index.js` into my node bin directory. Which is something I don't understand.

```
An unexpected error occurred: "EACCES: permission denied, symlink '../../../../build/.config/yarn/link/lighthouse/cli/index.js' -> '/nix/store/zwi2cvrkq629ybazsyy7qrvfcvdd88n2-no
```

Also there seems to be a circular dependency as I need a lighthouse package available globally in order to build `lighthouse-plugin-publisher-ads`.

CC @hsjobeki

**Comment by adamraine** [comment]
Seems like this error comes when the build installs the `lighthouse` command globally, can you provide your OS, Node version, and how you are building Lighthouse?

**Comment by marijanp** [comment]
@adamraine I'm currently trying to package it for [nixpkgs](https://github.com/NixOS/nixpkgs) I'm on NixOS. I'm executing `npm run build-all`, Node version is `v18.9.1`.

**Comment by adamraine** [comment]
I haven't reproduced this yet, but seems like this error comes when we run `yarn reset-link` which doesn't install Lighthouse globally but uses a yarn link to make the local package environment available for other packages.

This is required to build some of our bundles, but may not be required for your use case if you don't want to grant permissions. You might be able to avoid this if you remove `yarn build-lr` and `yarn build-devtools` from the `yarn build-all` command.
