### ISSUE TITLE
Odd errors in Pagespeed Insights SEO report

### ISSUE THREAD

**Issue by nagumii** [GoogleChrome/lighthouse#14979]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.rustil.co.il/

### What happened?

Errors:

Document has a valid hreflang Error!
Document has a valid rel=canonical Error!

Text of error: "Required LinkElements gatherer encountered an error: Expected attribute delimiter at offset 90" for both errors.

### What did you expect?

SEO results.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

10.1.0

**Comment by nagumii** [comment]
Adding a link to the report with the error: https://pagespeed.web.dev/analysis/https-www-rustil-co-il/pypdg7t207?form_factor=mobile

**Comment by adamraine** [comment]
This was fixed in #14934, but the latest release hasn't shipped to pagespeed yet.

**Comment by nagumii** [comment]
Thanks, appreciate the response!
