### ISSUE TITLE
Error when loading html report in the browser

### ISSUE THREAD

**Issue by jmpeduto** [GoogleChrome/lighthouse#14971]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://lodging.visithouston.com/

### What happened?

Im running lighthouse report programmatically with node, with other url sites as https://www.google.com it's working fine, but when I test with the url I need to try _https://lodging.visithouston.com/search?Checkin=05/15/2023&Checkout=05/17/2023_ when opening the report in Chrome i'm getting random javascript errors as below and the report never loads.

![image](https://user-images.githubusercontent.com/47331357/232115035-be228645-da42-4a9c-b4fd-47bb534e127e.png)

Ive tried to generate a json report and paste it in the lighthouse viewer but the error is the same.

These are my dependencies at package.json

 "dependencies": {
    "chrome-launcher": "^0.15.1",
    "express": "^4.18.2",
    "lighthouse": "^10.1.0"
  }

### What did you expect?

I expect to have a visible html report from that website

### How were you running Lighthouse?

node

### Lighthouse Version

10.1

### Node Version

19

### OS

linux

**Comment by adamraine** [comment]
Can you provide the HTML report you are trying to render?

**Comment by jmpeduto** [comment]
Thanks @adamraine , sure, here is the report /home/juan/Desarrollo/BoC/docker-setup/lighthouse-reports/lighthouse-report.lodging.visithouston.html and the error is this 
![image](https://user-images.githubusercontent.com/47331357/232227607-b9539dda-d345-4f68-ba65-2df3e0c75b91.png)

**Comment by jmpeduto** [comment]
@adamraine I saw your reference to https://github.com/GoogleChrome/lighthouse/issues/14922 and it seems that setting disableFullPageScreenshot: true is a workaround to solve the issue

**Comment by adamraine** [comment]
Thanks for sharing the report, I can confirm this is the same issue as https://github.com/GoogleChrome/lighthouse/issues/14922 so let's merge into there.
