### ISSUE TITLE
Docs out of date for throttling

### ISSUE THREAD

**Issue by chrislodev** [GoogleChrome/lighthouse#14989]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.discovertasmania.com.au

### What happened?

I wanted to get some more information about the difference between 'Simulated throttling (default)' and 'DevTools throttling (advanced)'. When I click on the 'Learn more' link next to the throttling dropdown in devtools, I'm taken to this link:

https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md#devtools-lighthouse-panel-throttling

However there is no mention at all of 'DevTools throttling (advanced' at all.

It also says to 'uncheck the 'Simulated throttling' checkbox but this appears to be out of date as it's now a dropdown.

### What did you expect?

I expected to see an explanation of the difference between 'Simulated throttling (default)' and 'DevTools throttling (advanced)'.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

10.0.1

### Chrome Version

112.0.5615.121 (Official Build) (arm64)

### OS

Mac

**Comment by adamraine** [comment]
Thanks, we should definitely update the docs.

In the mean time, "Applied Throttling" is the same thing as DevTools throttling. This setting used to be a checkbox in the Lighthouse panel but we changed it to a dropdown. "Uncheck simulated throttling" in the Lighthouse panel should be "Select DevTools throttling in the dropdown".

**Comment by chrislodev** [comment]
Thanks Adam, appreciate it.
