### ISSUE TITLE
aria-describedby attribute not recognised in accessibility

### ISSUE THREAD

**Issue by aksparkle** [GoogleChrome/lighthouse#14999]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://lovesparkle.life

### What happened?

This URL:

https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Flovesparkle.life%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext

gives 88 accessibility score where 6 points are lost under the section:

_[aria-*] attributes are not valid or misspelled_

The tool can't recognise _aria-describedby_ attribute used 6 times on that page. The attribute is entirely valid as per:

https://www.w3.org/TR/wai-aria-1.1/#aria-describedby

Please fix it up asap as we need this score to be higher.

### What did you expect?

We expect not to have this section:

_[aria-*] attributes are not valid or misspelled_

at all and the score to be 94 as it was yesterday before I added _aria-describedby_

### How were you running Lighthouse?

Other

### Lighthouse Version

10.1.1

### OS

Windows

**Comment by adamraine** [comment]
Lighthouse does recognize `aria-describedby`. The audit is failing because you misspelled `aria-label` as `aria-lable`.

It would be nice to add more failure details here though, which is tracked in https://github.com/GoogleChrome/lighthouse/issues/12282.

**Comment by aksparkle** [comment]
Oh my bad then, thanks much for pointing out. All good now!
