### ISSUE TITLE
CSS flexbox audit no longer contains urls

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1500]
Haven't investigated but wanted to file so I don't forget.

The old css flexbox audit no longer has urls in the violations list:

<img width="655" alt="screen shot 2017-01-19 at 11 27 09 pm" src="https://cloud.githubusercontent.com/assets/238208/22140030/d546ccca-de9e-11e6-9b3a-39ddd1f8246d.png">

Testing against the DBW tester.

**Comment by patrickhulce** [comment]
These are the inline stylesheets injected with script, right? Are we sure they originally showed the URL because this is what prompted the inline workaround for me when doing CSS usage.

**Comment by ebidel** [comment]
Yea, fairly positive they were there at some point. It's possible that moving things in/out of `<template>` in dbw tester has changed it or the inline additions to the gatherer.

**Comment by patrickhulce** [comment]
Oh if it used to be out of template then my money's on that. AFAIK it's the
injection of the stylesheet with script that gives an empty
header.sourceURL.

**Comment by ebidel** [comment]
Cool. Thanks for the pointer. 

I'll throw some time into this later today and report back.

**Comment by ebidel** [comment]
This is indeed related to inline styles. I have a PR that will add "inline" to the URL to give context, but it would be good to come up with an attribution solution for inline stylesheets. Filed https://github.com/GoogleChrome/lighthouse/issues/1544 separately.
