### ISSUE TITLE
pantalla negra en cuando quiero usar el buscador de google

### ISSUE THREAD

**Issue by JimenaOcampo** [GoogleChrome/lighthouse#15013]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.google.com/search?q=1&rlz=1C1CHZN_enAR1054AR1054&sxsrf=APwXEdeyxrf3uW9Lmr46gpCHJAbSNNLYjA%3A1682267780712&ei=hF5FZJWMK5DS1sQPxdydoAM&ved=0ahUKEwiV3vHrt8D-AhUQqZUCHUVuBzQQ4dUDCBA&uact=5&oq=1&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIGCCMQJxATMgQIIxAnMgQIIxAnMggILhCKBRCRAjIICAAQigUQkQIyBQguEIAEMggILhCABBDUAjIFCAAQgAQyBQgAEIAEMgsILhCABBDHARDRAzoHCCMQ6gIQJ0oECEEYAFAAWLQLYMkQaAFwAXgAgAHPAYgBzwGSAQMyLTGYAQCgAQGwAQrAAQE&sclient=gws-wiz-serp

### What happened?

![image](https://user-images.githubusercontent.com/129327230/233852553-8ba79460-d256-497e-af8b-e999f3d3b9ae.png)

https://user-images.githubusercontent.com/129327230/233852568-4e35c9ab-759a-45f2-ba53-c57f11670d84.mp4

_**Me aparece un error y no se porque la pagina no me carga!**_

Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests.
9 cookies
2 solicitudes
Más información: Cookies de SameSite explicadas

### What did you expect?

Esperaba que me deje utilizar el buscador,

### What have you tried?

Probe desintalar google, borrar las cokies y las extenciones. 
me deja usar otros buscadores pero el de google hace lo que mostre en el video.
No se mucho de programacion, recien voy arrancando, no se que hacer...

### How were you running Lighthouse?

Other

### Lighthouse Version

Generated by Lighthouse 10.0.1

### Chrome Version

Versión 112.0.5615.138 (Build oficial) (64 bits)

### OS

Windows 11

### Relevant log output

```shell
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
2 fuentes
search:1
app:1
Más información: Reducción de las strings de usuario-agente



Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute
Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests.
9 cookies
Nombre	Dominio & Ruta de acceso
SID	.google.com/
__Secure-1PSID	.google.com/
HSID	.google.com/
SSID	.google.com/
APISID	.google.com/
SAPISID	.google.com/
__Secure-1PAPISID	.google.com/
SIDCC	.google.com/
__Secure-1PSIDCC	.google.com/
1 solicitud
 integrator.js?domain=www.socialmediatrend.net
Más información: Cookies de SameSite explicadas




Page layout may be unexpected due to Quirks Mode
One or more documents in this page is in Quirks Mode, which will render the affected document(s) with quirks incompatible with the current HTML and CSS specifications.
Quirks Mode exists mostly due to historical reasons. If this is not intentional, you can add or modify the DOCTYPE to be `<!DOCTYPE html>` to render the page in No Quirks Mode.
3 elementos
Documento en el árbol del DOM	Modo	URL
document	Quirks Mode	https://accounts.google.com/RotateCookiesPage?og_pid=5&rot=1&origin=https%3A%2F%2Fwww.google.com
document	Limited Quirks Mode	https://www.socialmediatrend.net/search.php?q=1
document	Quirks Mode	https://pagead2.googlesyndication.com/pagead/ads?client=ca-pub-2852864139479299&output=html&h=280&slotname=8976172560&adk=1028704912&adf=1782718074&pi=t.ma~as.8976172560&w=600&fwrn=16&fwrnh=100&rafmt=1&format=600x280&url=https%3A%2F%2Fwww.google.com%2F&ea=0&fwr=0&fwrattr=true&rpe=1&resp_fmts=3&wgl=1&uach=WyJXaW5kb3dzIiwiMTQuMC4wIiwieDg2IiwiIiwiMTEyLjAuNTYxNS4xMzgiLFtdLGZhbHNlLG51bGwsIjY0IixbWyJDaHJvbWl1bSIsIjExMi4wLjU2MTUuMTM4Il0sWyJHb29nbGUgQ2hyb21lIiwiMTEyLjAuNTYxNS4xMzgiXSxbIk5vdDpBLUJyYW5kIiwiOTkuMC4wLjAiXV0sZmFsc2Vd&dt=1682267973622&bpp=1&bdt=279&idt=11&shv=r20230418&mjsv=m202304130102&ptt=9&saldr=aa&correlator=4784755313186&frm=24&ife=1&pv=2&ga_vid=1139144173.1682267974&ga_sid=1682267974&ga_hid=1070755694&ga_fc=0&nhd=1&u_tz=-180&u_his=12&u_h=720&u_w=1280&u_ah=672&u_aw=1280&u_cd=24&u_sd=1.5&dmc=8&adx=-12245933&ady=-12245933&biw=-12245933&bih=-12245933&isw=600&ish=1&ifk=3417222552&scr_x=-12245933&scr_y=-12245933&eid=44759837%2C44759876%2C44759927%2C31071756%2C31074012&oid=2&pvsid=4212448111371120&tmod=473092400&uas=0&nvt=1&brdim=0%2C0%2C0%2C0%2C1280%2C0%2C1280%2C672%2C600%2C1&vis=1&rsz=%7C%7CeE%7C&abl=CS&pfx=0&fu=128&bc=31&ifi=1&uci=1.j8kwreshkf50&fsb=1&dtd=17
Más información: Modo de compatibilidad de documentos
```

**Comment by adamraine** [comment]
I don't understand what the issue is. Can you please explain how this is related to Lighthouse?
