### ISSUE TITLE
API data divergence from pagespeed.web.dev data

### ISSUE THREAD

**Issue by LuizGustavoWT** [GoogleChrome/lighthouse#15030]
Hi @adamraine, thanks for documentation, i read many times it, i understand at documentation, but my problem is:

1 - the metrics, has divergence between in PWA (Mobile) and Desktop (Browser), in the first case the metrics has many divergence in metrics of LCP, but in the second case Desktop the metrics doesn't has divergence between pagespeed.web.dev and GooglePagespeed API.

This problem touch my organization in proccess collect metrics of core web vitals.

PS.: I tested this in weekend, sorry for long time to response

_Originally posted by @LuizGustavoWT in https://github.com/GoogleChrome/lighthouse/issues/15020#issuecomment-1530581385_

**Comment by adamraine** [comment]
Please don't open duplicate issues, we'll keep the discussion in https://github.com/GoogleChrome/lighthouse/issues/15020
