### ISSUE TITLE
Use of shadowrootmode attribute is incorrectly flagged as deprecated

### ISSUE THREAD

**Issue by erickmerchant** [GoogleChrome/lighthouse#15034]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://erickmerchant.com

### What happened?

I am getting a warning under the Issues tab in dev tools saying "Deprecated Feature Used" and "The older, non-standardized shadowroot attribute is deprecated. Please use the new, standardized shadowrootmode attribute instead.". I am using shadowrootmode and not shadowroot. I get the same issue reported when I run Lighthouse.

### What did you expect?

To not receive a warning.

### What have you tried?

I double checked my html and it is correct at least in regards to that attribute.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

10.0.1

### OS

Mac

### Relevant log output

```shell
Deprecated Feature Used
The older, non-standardized shadowroot attribute is deprecated. Please use the new, standardized shadowrootmode attribute instead.
1 source
Learn more: Check the feature status page for more details.
Learn more: This change will go into effect with milestone 112.
```

**Comment by adamraine** [comment]
Hmm, seems like you're using the attribute correctly. I'll file a bug upstream.

**Comment by adamraine** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1442307

**Comment by erickmerchant** [comment]
Great, thank you!

**Comment by adamraine** [comment]
The upstream bug was fixed, you should see a fix in Chrome M115
