### ISSUE TITLE
Audit bug [?]  Site Does Not Use Resources That Delay First Paint

### ISSUE THREAD

**Issue by amedina** [GoogleChrome/lighthouse#1504]
The result of the audit is showing an undefined access error instead of the links blocking first page rendering.

<img width="635" alt="screen shot 2017-01-20 at 11 50 55 am" src="https://cloud.githubusercontent.com/assets/506089/22163258/f38c7ab4-df06-11e6-8460-1ec731035464.png">

**Comment by amedina** [comment]
Here is the [full report](https://gist.github.com/amedina/4fb0cc4bae102d557325a72a449b3d1e) (JSON)

**Comment by ebidel** [comment]
URL is https://m.olx.com.ar/

@amedina, I wasn't able to repro this using the latest extension:

<img width="818" alt="screen shot 2017-01-20 at 12 23 05 pm" src="https://cloud.githubusercontent.com/assets/238208/22164233/40eb7540-df0b-11e6-883b-2c9247e7d2cc.png">

Is it reliable to reproduce?

cc @patrickhulce

**Comment by patrickhulce** [comment]
hmmm, yeah @ebidel you fixed this awhile ago I thought. Doesn't seem possible on master at least as the only use of `indexOf` is guarded for undefinedness.

**Comment by ebidel** [comment]
11 days ago seems like forever ago :) @amedina, This should be fixed in master and in the next release.

https://github.com/GoogleChrome/lighthouse/commit/929d0a81b0d2788b4c82fcff85527f7a79271536

**Comment by amedina** [comment]
@ebidel, @patrickhulce You are correct; it works perfect on the extension; I observed the issue when I ran it via the CLI, which I have at version 1.4.1. I did an `npm update` and the version did not change.

**Comment by ebidel** [comment]
We're planning a new 1.5 release early next week. `npm update` should pick up the fix after that.

**Comment by amedina** [comment]
Thanks!
