### ISSUE TITLE
Viewer: add manifest

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1506]
So it's a PWA...duh!

**Comment by XhmikosR** [comment]
@ebidel: which icons do you want to have?

I made a local patch with all icons 16x16, 32x32, favicon.ico etc generated with http://realfavicongenerator.net/.

**Comment by XhmikosR** [comment]
https://github.com/GoogleChrome/lighthouse/compare/master...XhmikosR:viewer-favicons
