### ISSUE TITLE
Move back to npm --prefix instead of using -C to install components

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1507]
See https://ci.appveyor.com/project/XhmikosR/lighthouse/build/59/job/uis3t57c4558yf18 for an example

What does the `-C` npm flag do exactly?

**Comment by ebidel** [comment]
`-C` is a shorthand for `--prefix` (https://docs.npmjs.com/misc/config), which [we used to use](https://github.com/GoogleChrome/lighthouse/commit/b810242d255468543a7037e5f013414cb8ea43e7).

From your output, it looks like its not installing the extension's package.json and the viewer's extension? Perhaps `-C` doesn't work for windows.

Maybe try `npm --prefix ./lighthouse-extension install ./lighthouse-extension` again to see if it helps? I'm curious.

**Comment by XhmikosR** [comment]
Thanks for the link. I'll experiment more later.

Why do you need prefix anyway? If I cd in the subfolders and do npm install
everything works fine.

**Comment by ebidel** [comment]
Yea, we could also do that as a last resort. IIRC, there were some places we used to cd but moved to `-C`/ `--prefix` for cleanliness.

**Comment by XhmikosR** [comment]
@ebidel: `npm --prefix ./lighthouse-cli install ./lighthouse-cli ` works.

Still, I don't see why you need `--prefix` or `-C`. I mean, sure it's shorter, but it's error prone.

Perhaps instead of `cd` we could use `pushd`/`popd` which is what I use in my AppVeyor branch.

Either way, the solution that is in master is broken for Windows.

**Comment by ebidel** [comment]
I'm not sure it's error prone. I'd expect the node flags to work across platforms and if they don't, that's a bug. 

But finding useful info on `-C` is pretty rough. So pragmatically, I'm ok with going back to `npm --prefix` if that makes Windows happy. Do you want to PR? I've also marked this as a good first bug if anyone else wants to take it.

**Comment by XhmikosR** [comment]
The reason I say it's error-prone is because I end up with the executables in the subfolders and not in node_modules/.bin.

I can make a PR sure.

**Comment by XhmikosR** [comment]
I still find just doing `cd` or `pushd`/`popd` better. That way all deps will be in `./node_modules/` folder.
