### ISSUE TITLE
Lighthouse-logger release 1.4.0 breaks Chrome-Launcher

### ISSUE THREAD

**Issue by jweingarten** [GoogleChrome/lighthouse#15085]
Sorry, but I wasn't sure if I should report this here or not.   Please point me to the right reporting link in case I am wrong.

Lighthouse-logger was released ~2 hours ago. https://www.npmjs.com/package/lighthouse-logger
After the upgrade to 1.4.0 chrome-launcher fails with 

```
node_modules/chrome-launcher/dist/chrome-finder.js:14
00:00:00 const log = require('lighthouse-logger');

Error [ERR_REQUIRE_ESM]: require() of ES Module/node_modules/lighthouse-logger/index.js from /node_modules/chrome-launcher/dist/chrome-finder.js not supported.
```

I had to go back to version 1.3.0.

**Comment by derek** [comment]
I also ran into this issue on a CI job that uses `npx @lhci/cli@0.11.x autorun`

```
const log = require('lighthouse-logger');
            ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /root/.npm/_npx/0961705c731f62b7/node_modules/lighthouse/node_modules/lighthouse-logger/index.js from /root/.npm/_npx/0961705c731f62b7/node_modules/lighthouse/lighthouse-core/gather/fetcher.js not supported.
Instead change the require of index.js in /root/.npm/_npx/0961705c731f62b7/node_modules/lighthouse/lighthouse-core/gather/fetcher.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/root/.npm/_npx/0961705c731f62b7/node_modules/lighthouse/lighthouse-core/gather/fetcher.js:18:13)
    at Object.<anonymous> (/root/.npm/_npx/0961705c731f62b7/node_modules/lighthouse/lighthouse-core/gather/driver.js:8:17)
    at Object.<anonymous> (/root/.npm/_npx/0961705c731f62b7/node_modules/lighthouse/lighthouse-core/runner.js:9:16)
    at Object.<anonymous> (/root/.npm/_npx/0961705c731f62b7/node_modules/lighthouse/lighthouse-core/index.js:8:16)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
```

Looks like it is being fixed @ https://github.com/GoogleChrome/lighthouse/pull/15084

**Comment by hardyjohnson** [comment]
I am seeing something similar which is attached to Netlify builds with their lighthouse plugin. I believe this is the source of the issue though.

**Comment by adamraine** [comment]
Hey folks, apologies for the breakages. The broken version 1.4.0 has been deprecated in npm and 1.4.1 should restore cjs support.

**Comment by akamel1** [comment]
https://github.com/GoogleChrome/chrome-launcher/pull/300/commits/6a47963f0ff8293d13c216ba2143db502407d5d6

**Comment by amrsa1** [comment]
https://github.com/GoogleChrome/chrome-launcher/commit/6a47963f0ff8293d13c216ba2143db502407d5d6

**Comment by hardyjohnson** [comment]
This resolved the issue w/Netlify build testing. Thank you @adamraine

**Comment by adamraine** [comment]
This should be resolved now. Let us know here if you are still affected and we can reopen.
