### ISSUE TITLE
Unhelpful "Other" under Minimizes main-thread work in Pagespeed

### ISSUE THREAD

**Issue by tomasts248** [GoogleChrome/lighthouse#15083]
![image](https://github.com/GoogleChrome/lighthouse/assets/32283036/a985ac8d-8919-4aa3-95b3-28f462c54b6f)

So it could instead point to see further info about what are those items?

**Comment by realjjaveweb** [comment]
My personal guess: this somehow seems to corelate with how long does it take the server to send the complete response. 

Note that this is **different** than "Initial server response time" / "Time to First Byte metric".

But as you've described nicely - I can only guess - even if there are more factors at play, there should be at least a few mentions of the main factors affecting this.

**Comment by adamraine** [comment]
Merging into #11478
