### ISSUE TITLE
Is `$__node_harmony` needed in extension?

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1508]
It's causing issues when building on Windows so I wonder if it's needed for the extension.

Also, would be nice if the package.json `engines` values were consistent across all package.json files.

**Comment by wardpeet** [comment]
no because it's being build as a package. It depends on what version @brendankenny is publishing :)

**Comment by XhmikosR** [comment]
By no, you mean that the flag isn't needed? Because if that's the case, it's one thing closer to proper Windows support :)

**Comment by XhmikosR** [comment]
It is still needed for the extension :/

**Comment by ebidel** [comment]
As of https://github.com/GoogleChrome/lighthouse/issues/449, this will no longer be needed.
