### ISSUE TITLE
Add `requestCount` to `third-party-summary` subitem attributes

### ISSUE THREAD

**Issue by benschwarz** [GoogleChrome/lighthouse#15093]
**Feature request summary**

At the moment, `third-party-summary` [does not display `subitems` when files are "too small"](https://github.com/GoogleChrome/lighthouse/blob/main/core/audits/third-party-summary.js#L161), or there aren't any numbers to report. 

Because of this, it's not currently possible to easily understand the number of requests a given third party made. `mainThreadTime`, `blockingTime`, `transferSize` are already included. Request count seems like a worthy addition.

**Yes**, I am willing to implement if there's a positive signal from team LH.

**Other possible alternatives***

- The `network-requests` audit could be enhanced so that it nominates corresponding LHR `entities` (3Ps). Then it would be quite ergonomic to collect third party requests for further analysis.
- LHR `entities` could be updated to provide some statistics like `requestsCount`. (I don't think this is a good solution, but sharing it as an idea all the same)

**What is the motivation or use case for changing this?**

Adding further understanding to the impacts a given third party makes on a page. 

**How is this beneficial to Lighthouse?**

- Another data point to help describe third party impacts
- Greater appreciation for potentially problematic third parties

**Comment by adamraine** [comment]
> The network-requests audit could be enhanced so that it nominates corresponding LHR entities (3Ps). Then it would be quite ergonomic to collect third party requests for further analysis.

Adding the 3P entity to the network requests seems good. Makes it much easier to do a lookup without using `new URL().orign`.

**Comment by benschwarz** [comment]
Having slept on it for a few nights, I think updating the network requests audit so that it's the primary source of all-request related attributes is a solid improvement. 

Would y'all like me to take a stab at adding third party info to network-requests?

**Comment by adamraine** [comment]
> Would y'all like me to take a stab at adding third party info to network-requests?

Sure!

**Comment by StarSyntaxStatic** [comment]
Mi positi'on no es perfecto. Que yo necessito aqui mas?
