### ISSUE TITLE
Style guide: Thoughts on destructing

### ISSUE THREAD

**Issue by umaar** [GoogleChrome/lighthouse#151]
Thoughts on turning this:

```js
  static audit(artifacts) {
    let hasThemeColor = false;
    const manifest = artifacts.manifest.value;

    if (manifest && manifest.theme_color) {
      hasThemeColor = (!!manifest.theme_color.value);
    }

    return ManifestThemeColor.generateAuditResult(hasThemeColor);
  }
```

Into this?

```js
  static audit({manifest: {value: {theme_color: {value} = {}} = {}}}) {
    return ManifestThemeColor.generateAuditResult(!!value);
  }
```

Or does that make it too unreadable? It uses [destructuring](https://gist.github.com/mikaelbr/9900818#file-destructuring-js-L115).

**Comment by brendankenny** [comment]
I think that particular example is less readable, but I think there are cases where it can improve legibility. We don't have a compile step, though, so we can only use what Node 5 currently supports, which doesn't include destructuring.

**Comment by umaar** [comment]
Oh fair enough, thanks anyway.
