### ISSUE TITLE
Version 10.2.0 fails `Unhandled Rejection. Reason: Error: Cannot extract value when objectId is given`

### ISSUE THREAD

**Issue by Lethgir** [GoogleChrome/lighthouse#15101]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://gensdeconfiance.com/fr

### What happened?

I add headers with the option `--extra-headers=custom-headers.json` but if this file contains a field `User-Agent`, Lighthouse crashes with the following error:
```
Unhandled Rejection. Reason: Error: Cannot extract value when objectId is given
```

See an example `custom-headers.json` file content:
```json
{
  "User-Agent": "random",
  "Cookie": "random-cookie=randomValue"
}
```

### What did you expect?

I expect Lighthouse to use a custom User-Agent and run the analysis without crash.

### What have you tried?

I tried with and without the `User-Agent` field in the extra headers JSON.
This behavior works well with 10.1.0 but not with 10.2.0 version.

### How were you running Lighthouse?

CLI

### Lighthouse Version

10.2.0

### Chrome Version

113

### Node Version

16

### OS

MacOS

### Relevant log output

```shell
lighthouse https://gensdeconfiance.com/fr --extra-headers=".custom-headers.json"
  LH:ChromeLauncher Waiting for browser. +0ms
  LH:ChromeLauncher Waiting for browser... +0ms
  LH:ChromeLauncher Waiting for browser..... +503ms
  LH:ChromeLauncher Waiting for browser.....✓ +1ms
  LH:status Connecting to browser +198ms
  LH:status Navigating to about:blank +5ms
  LH:status Benchmarking machine +7ms
  LH:status Preparing target for navigation mode +1s
  LH:status Navigating to about:blank +11ms
  LH:status Preparing target for navigation +6ms
  LH:status Cleaning origin data +25ms
  LH:status Cleaning browser cache +3ms
  LH:status Preparing network conditions +22ms
  LH:status Navigating to https://gensdeconfiance.com/fr +43ms
Unhandled Rejection. Reason: Error: Cannot extract value when objectId is given
  LH:ChromeLauncher Killing Chrome instance 40446 +928ms
```

**Comment by adamraine** [comment]
I can't reproduce this with the versions given, only thing I found was a [similar bug for puppeteer](https://stackoverflow.com/questions/76283083/puppeteer-throwing-error-cannot-extract-value-when-objectid-is-given). We upgraded our puppeteer dependency in 10.2.0 so that is possibly the source of the bug.

Can you reproduce this with the latest Chrome Canary?

**Comment by adamraine** [comment]
I just reproduced this with the following command:

```
lighthouse https://espn.com -G
```

It seems unrelated to the `User-Agent` header.

**Comment by adamraine** [comment]
https://github.com/puppeteer/puppeteer/issues/10224
