### ISSUE TITLE
Empty href attribute results in “Links are not crawlable” error

### ISSUE THREAD

**Issue by ausi** [GoogleChrome/lighthouse#15127]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://output.jsbin.com/tefuwogeyo

### What happened?

A regular link to the current page itself (`<a href="">`) results in a `Links are not crawlable` message.

<img width="785" alt="Bildschirmfoto 2023-06-02 um 00 24 18" src="https://github.com/GoogleChrome/lighthouse/assets/367169/3fe50d03-2dab-4030-b9e0-fb8ff5222391">

### What did you expect?

Valid HTML links should not be shown as “not crawlable”.

### What have you tried?

I checked the standards for HTML and URLs, and also tested this in all browsers with the same result: all information I checked agrees that `href=""` is a correct and valid anchor the the currently visited page, or to the current `<base href="…">` if set.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

10.2.0

### Chrome Version

113.0.5672.126

### OS

macOS 13.4 (22F66)

**Comment by paulirish** [comment]
True. This is legit. 
We'll change the impl to allow empty href values.

original discussion: https://github.com/GoogleChrome/lighthouse/issues/10590#issuecomment-618393044 and subsequent comments
