### ISSUE TITLE
I use lighthouse running score has been very low

### ISSUE THREAD

**Issue by ZengTianShengZ** [GoogleChrome/lighthouse#15139]
**Summary**

I use puppeteer and lighthouse to perform web page performance analysis on a centos server with 4 core cpu and 2g memory, and the generated performance analysis report `performance` has always been very low.
Even though I improved the CPU and memory configuration, increased the CPU to 6 cores, increased the memory to 4G, and did not limit the CPU current, the performance score is still very low.
![image](https://github.com/GoogleChrome/lighthouse/assets/15622519/161dcba2-54df-437b-97b8-767558d3463a)

![image](https://github.com/GoogleChrome/lighthouse/assets/15622519/b3dcba77-7fe5-42a8-9606-e5371f744deb)

But if I use my local computer, m1, 16g memory, the performance score is very good.
![image](https://github.com/GoogleChrome/lighthouse/assets/15622519/0cf3af33-cd77-4dd2-8b7b-b0b5c1e77100)

![image](https://github.com/GoogleChrome/lighthouse/assets/15622519/b41edddf-1070-4443-bbc8-7a935cba88e4)

How can I configure my server or set up my program to improve the performance score?

my code snippet:

```js
import puppeteer from 'puppeteer';
import lighthouse from 'lighthouse';
import desktopConfig from 'lighthouse/core/config/desktop-config.js';

function createBrowser() {
        return puppeteer.launch({
            args: [
                '--no-sandbox',
                '--show-paint-rects',
                `--window-size=${desktopConfig.settings.screenEmulation.width},${desktopConfig.settings.screenEmulation.height}`,
            ],
        });
    }

function createReportWithBrowser(browser, url, options = { output: 'html', logLevel: 'info' }) {
        const endpoint = browser.wsEndpoint(); // Allows us to talk via DevTools protocol
        const endpointURL = new URL(endpoint); // Lighthouse only cares about the port, so we have to parse the URL so we can grab the port to talk to Chrome on
        return lighthouse(
            url,
            Object.assign(
                {},
                {
                    port: endpointURL.port,
                    throttling: { cpuSlowdownMultiplier: 0 },
                },
                options
            ),
            desktopConfig
        );
    }

const browser = await createBrowser();

const runnerResult = await createReportWithBrowser(browser, url, {output: 'html'});
```

**Comment by adamraine** [comment]
In general, please read or [variability docs](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) for potential mitigations. It's possible that different network conditions are impacting your score.

Also, from the screenshots it appears that the page content is not the same for each report. The change in CLS score in particular is most likely a result of the page loading different content for each report.
