### ISSUE TITLE
Smart Insights - Run performance experiments and suggest changes.

### ISSUE THREAD

**Issue by weiwei-lin** [GoogleChrome/lighthouse#1514]
This is a stand along feature but could serve as an entry point to `--interactive` mode in Perf-X #1143.
The basic idea is figuring out which types of resources have high performance impact so we can give some advice to improve site performance.
We can use some heuristics to find out what type of resources could potentially has high performance impact and run some tests blocking those resources then make suggestions based on the results.
Currently, this is still in experiment phase. I'm trying to figure out which types of resources are likely to have high performance impact and low rendering / functionality impact (so it would be meaningful for us to run the tests without users input).
Update: I did some research and decided not to implement Smart Insights mainly due to its potential low accuracy and the time limit of my internship. Here is the link to the doc: https://docs.google.com/document/d/1BO73_Bk6qr9XuJCBlDollg1SW39t_i5AEnlHI3eQofQ/edit?usp=sharing

**Comment by paulirish** [comment]
Thanks for filing this. We're pulling this into an upcoming vision sprint. 
Hopefully you'll see this on the other side. :)
