### ISSUE TITLE
lighthouse-plugin-publisher-ads plugin doesn't work if I run lighthouse programmatically.

### ISSUE THREAD

**Issue by JWebDev** [GoogleChrome/lighthouse#15140]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.coolthings.com/vanmoof-s5-electric-bicycle-gen5-motor/

### What happened?

Hi all,

I'm running lighthouse programmatically. Everything is fine, but if I add lighthouse-plugin-publisher-ads to my config, then I expect it in generated json categories section.

After that, i should see lighthouse-plugin-publisher-ads in categories object. If I run lighthouse from command line, then generated json has lighthouse-plugin-publisher-ads in categories section. If I run it programmatically, then lighthouse-plugin-publisher-ads does not exists in generated json report in categories object

**configs object**
```
{
   "extends": "lighthouse:default",
   "settings": {
      "formFactor": "desktop",
      "disableFullPageScreenshot": false,
      "locale": "en",
      "screenEmulation": {
         "disabled": true
      },
      "onlyCategories": [
         "performance",
         "accessibility",
         "best-practices",
         "seo",
         "pwa"
      ]
   },
   "plugins": [
      "lighthouse-plugin-publisher-ads"
   ]
}
```

**package.json**
```
  "dependencies": {
    "lighthouse": "^10.2.0",
    "lighthouse-plugin-publisher-ads": "1.5.7-beta",
    "puppeteer": "^19.9.1"
  },
  "overrides": {
    "lighthouse-plugin-publisher-ads": {
      "lighthouse": "$lighthouse"
    }
  }
```

**src**
```
//Launch Chrome
const chrome: LaunchedChrome = await getLaunchedChrome()
console.log('Launched Chrome PID=', chrome.pid)

//Get Puppeter page
const page: Page = await getPuppeteerPage(chrome)

//Build lighthouse configs and flags
const configs = buildConfigs()
const flags = {logLevel: 'info', port: chrome.port, output: ['html', 'json']} as Flags

runnerResult = await lighthouse('https://www.coolthings.com/vanmoof-s5-electric-bicycle-gen5-motor/', flags, configs, page)
```

### What did you expect?

I expect the lighthouse-plugin-publisher-ads plugin to work as described in the documentation.

### How were you running Lighthouse?

node, Other

### Lighthouse Version

10.2.0

### Chrome Version

114.0.5735.106-1

### Node Version

19.9.0

### OS

Debian 11.7

**Comment by adamraine** [comment]
I think your problem is that you define `onlyCategories` on the config, and `lighthouse-plugin-publisher-ads` is not in the list. You need to either add `lighthouse-plugin-publisher-ads` to the list or remove the `onlyCategories` setting from your config entirely.

**Comment by JWebDev** [comment]
Yes, you are right. This is my mistake. This is not a bug, sorry for creating a ticket for this. I should have been more careful about what I was doing. I added the plugin to the categories and everything works. 
Thanks.
