### ISSUE TITLE
disableStorageReset doesn't work if I run lighthouse programmatically.

### ISSUE THREAD

**Issue by JWebDev** [GoogleChrome/lighthouse#15141]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.coolthings.com/vanmoof-s5-electric-bicycle-gen5-motor/

### What happened?

Hi, for some web pages I would like to set localStorage with the help of Puppeteer. 
I can set Puppeteer localStorage only if I open some page. It is fine, I go to localhost and set localStorage. It works.

Then I run the Lighthouse with some URL. After run I look into localStorage and see some variables(Which are probably set by the site we are testing.), but not my `Test` var. 

Based on this logic, I conclude that the `disableStorageReset` I set programmatically simply does not work.

Here is my code and config object.

```
//Launch Chrome
const chrome: LaunchedChrome = await getLaunchedChrome()
console.log('Launched Chrome PID=', chrome.pid)

//Get Puppeter page
const page: Page = await getPuppeteerPage(chrome)

//Build lighthouse configs and flags
const configs = buildConfigs()
const flags = {logLevel: 'info', port: chrome.port, output: ['html', 'json']} as Flags

await page.goto('http://localhost')

await page.evaluate(() => localStorage.setItem("Test", "1234"))

const resultLs = await page.evaluate(() => {
    return JSON.stringify(localStorage)
})
console.log(JSON.parse(resultLs))

runnerResult = await lighthouse('https://www.coolthings.com/vanmoof-s5-electric-bicycle-gen5-motor/', flags, configs, page)

const resultLs1 = await page.evaluate(() => {
    return JSON.stringify(localStorage)
})
console.log(JSON.parse(resultLs1))
```

Config object
```
{
  "extends": "lighthouse:default",
  "settings": {
    "formFactor": "desktop",
    "disableFullPageScreenshot": false,
    "locale": "en",
    "screenEmulation": {
      "disabled": true
    },
    "onlyCategories": [
      "performance",
      "accessibility",
      "best-practices",
      "seo",
      "pwa"
    ],
    "disableStorageReset": true,
    "extraHeaders": {
      "Cookie111": "monster=blue",
      "test": "123"
    }
  }
}
```

### What did you expect?

I expect the disableStorageReset flag to work as described in the documentation. The local storage will not be cleared by the lighthouse.

### How were you running Lighthouse?

node, Other

### Lighthouse Version

10.2.0

### Chrome Version

114.0.5735.106-1

### Node Version

19.9.0

### OS

Debian 11.7

**Comment by adamraine** [comment]
The Lighthouse storage reset should [never affect local storage](https://github.com/GoogleChrome/lighthouse/blob/186e1804ae7757b6a975c9a8b8af1a5e9b67f81e/core/gather/driver/storage.js#L51).

It looks like the [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) isn't being cleared, but the local storage data you add on one origin is not accessible when the page navigates to a different origin. When I change the script to visit the same origin before Lighthouse runs, the data isn't cleared. Can you confirm?

**Comment by JWebDev** [comment]
@adamraine 
Thank you. Yes, I can confirm this. But why is this happening? Local storage must be visible to all pages. Or am I misunderstanding something? Can you give me a tip?  After `page.goto` to localhost I can see my localStorage.
```
runnerResult = await lighthouse('https://www.coolthings.com/vanmoof-s5-electric-bicycle-gen5-motor/', flags, configs, page)

await page.goto('http://localhost')

const resultLs1 = await page.evaluate(() => {
    return JSON.stringify(localStorage)
})

console.log(JSON.parse(resultLs1))
```

**Comment by adamraine** [comment]
It is not visible to all pages. Local storage only allows you to access the storage [for that document's origin](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage#:~:text=The%20localStorage%20read%2Donly%20property%20of%20the%20window%20interface%20allows%20you%20to%20access%20a%20Storage%20object%20for%20the%20Document%27s%20origin%3B).
