### ISSUE TITLE
Cannot open URL programatically with preset desktop

### ISSUE THREAD

**Issue by ankur-lt** [GoogleChrome/lighthouse#15154]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://google.com

### What happened?

I am trying to open a URL programmatically via lighthouse with a  desktop view.

I opened Chromium with the following command:
```sh
Applications/Chromium.app/Contents/MacOS/Chromium --remote-debugging-port=9223 --incognito
```

My lighthouse script is as follows:
```js
const lighthouse = require('lighthouse');

(async () => {
    let options, flags, lighthouseResult, config = {};
    console.log('Opening lighthouse')

    options = {
        output: ['csv', 'html', 'json'],
        onlyCategories: ['performance', 'accessibility', 'best-practices', 'seo', 'pwa'],
        port: 9223,
    };

    config = {
        extends: 'lighthouse:default',
        settings: {
            // formFactor: 'desktop',
            preset: 'full'
        },
    }

    const url = "https://google.com"

    await lighthouse(url, options);
})()

```

Its still opening the webpage in the mobile view. I have tried the `preset` as well as `formFactor` config too.

### What did you expect?

I want to open the webpage with desktop view.

### What have you tried?

I have tried the `preset` as well as `formFactor` config too.

### How were you running Lighthouse?

node

### Lighthouse Version

9.6.8

### Chrome Version

115

### Node Version

v18.16.0

### OS

MacOS Ventura

**Comment by adamraine** [comment]
You need to import the Lighthouse [desktop config](https://github.com/GoogleChrome/lighthouse/blob/main/core/config/desktop-config.js) and use it in your call to `lighthouse`. `--preset` is a CLI flag that will do this for you on the CLI, but there is no equivalent `preset` option when running Lighthouse programatically.

Something like this should work in version 9.6.8:

```js
const lighthouse = require('lighthouse');
const desktopConfig = require('lighthouse/lighthouse-core/config/desktop-config.js');

await lighthouse(url, options, desktopConfig);
```

Note: the location and import strategy of the desktop config changed in version 10.0, so you would do something like this with version 10.x:

```js
import lighthouse, {desktopConfig} from 'lighthouse';

await lighthouse(url, options, desktopConfig);
```

**Comment by ankur-lt** [comment]
Thanks @adamraine , it worked!
