### ISSUE TITLE
Re-weight Best Practices Audits

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#15163]
From https://bugs.chromium.org/p/chromium/issues/detail?id=1454211:

> Are all of the Best Practices sub-scores equal-weighted to come up with the overall score? It seems like some should be more highly weighted than others. In particular, I'd like to call attention to the "Uses deprecated APIs" failure, which I think we should up-weight. For example, using a deprecated API would seem to be at least twice as bad as "Page has the HTML Doctype". The latter results in quirks mode, which is bad but at least specified. The former (using deprecated APIs) represents imminent site breakage. Similarly "Page has valid source maps" doesn't impact users at all, so I'd down-weight that significantly as compared to the site breaking due to deprecated APIs.
> 
> I guess I'd lobby for making the weight of "Uses deprecated APIs" at least high enough to ensure the overall "Best Practices" score is below 90, so it shows up Orange.

We should consider re-weighting some of these

**Comment by mfreed7** [comment]
Thanks for filing this! I'm hoping this is a real possibility. It would really help with all deprecation efforts, which typically hinge on developers hearing about the deprecation **at all** before the removal date. Dinging the lighthouse score seems to be a great place to raise that sort of awareness, and motivate folks to stop using these APIs.

**Comment by mfreed7** [comment]
Thanks! 😄
