### ISSUE TITLE
Run on developer mode the percentage is very low and run on extension mode the performance become good

### ISSUE THREAD

**Issue by Haneefkhan091** [GoogleChrome/lighthouse#15170]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://dripx.iottechnologies.io/login

### What happened?

When running in developer mode, the program experiences a noticeable decrease in performance, whereas switching to extension mode significantly improves its performance.

### What did you expect?

The program exhibits a considerably lower performance when executed in developer mode, but when switched to extension mode, its performance greatly improves.

### What have you tried?

Running the program in developer mode results in a significantly lower performance percentage compared to running it in extension mode, where the performance is noticeably improved.

In developer mode, the program includes additional features such as debugging tools, logging mechanisms, and other monitoring functionalities. These features are essential during the development phase as they help identify and fix issues in the code. However, they consume extra system resources and introduce overhead, which can slow down the program's execution.

On the other hand, when the program is switched to extension mode, it operates without these debugging and monitoring features. This allows the program to utilize more of the available system resources for its core functionality, leading to improved performance. Without the overhead of debugging processes, the program can execute more efficiently and deliver faster results.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

Version 100.0.0.0

### Chrome Version

114

### Node Version

v20.3.0

### OS

window 11

### Relevant log output

```shell
First Contentful Paint
11.4 s
Largest Contentful Paint
12.7 s
Total Blocking Time
240 ms
Cumulative Layout Shift
0.052
Speed Index
16.0 s
```

**Comment by connorjclark** [comment]
What do you mean by developer mode and extension mode?

**Comment by Haneefkhan091** [comment]
Like if i run to check Performace by clicking F12 and then run lighthouse
the results is 25 and on same time if i run my extension on that same page
the result is 65%.

**Comment by connorjclark** [comment]
Still don't know what you mean by "extension".

This might help you? https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md
