### ISSUE TITLE
Typescript compilation issue on lighthouse package 10.3.0

### ISSUE THREAD

**Issue by catalan-adobe** [GoogleChrome/lighthouse#15186]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.adobe.com

### What happened?

Local project does not compile anymore when switching from lighthouse package module 10.2.0 => 10.3.0

### What did you expect?

Local project would compile without errors

### What have you tried?

Created following minimal project 
[test-lh.zip](https://github.com/GoogleChrome/lighthouse/files/11789516/test-lh.zip)
 to confirm the compilation error even when not using any custom code.

1. Unzip archive
2. `npm i`
3. `npm run build`

Notice the compilation error (as shown in "Relevant log output" below)

### How were you running Lighthouse?

node

### Lighthouse Version

10.3.0

### OS

mac

### Relevant log output

```shell
➜  npm run build

> test-lh@1.0.0 build
> tsc

node_modules/lighthouse/core/lib/lh-error.d.ts:64:132 - error TS2304: Cannot find name 'ErrorOptions'.

64     constructor(errorDefinition: LighthouseErrorDefinition, properties?: Record<string, string | undefined> | undefined, options?: ErrorOptions | undefined);
                                                                                                                                      ~~~~~~~~~~~~


Found 1 error in node_modules/lighthouse/core/lib/lh-error.d.ts:64
```

**Comment by adamraine** [comment]
Looks like this type was added in es2022, and you are targeting es2021. `ErrorOptions` isn't a very complicated type so we can probably just typdef it ourselves to keep support for es2021.

@connorjclark do you think this would work? Is there somewhere else we should pull this type in from?

**Comment by connorjclark** [comment]
If adding our own type doesn't conflict when using es2022, it sounds fine to me.
