### ISSUE TITLE
[suggestion] call out which ARIA names / values are missing, required etc.

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#1518]
While writing the a11y audit docs I found myself repeatedly giving instructions on certain tasks, which means that LH users will have to repeat these tasks.

A few of the audits revolve around "this ARIA role needs this required attribute" or "this name is invalid". It would be nice if the audits called out exactly which roles / attributes / values etc. need to be change

**Comment by robdodson** [comment]
I think we're limited by what aXe gives us here. It'll just say 'this element has a bogus aria state' and reference the element.
