### ISSUE TITLE
Variability in CPU throughout the duration of the test.

### ISSUE THREAD

**Issue by prathamesh-gharat** [GoogleChrome/lighthouse#15202]
## Issue Summary
The difference in TBT/CPU-power ratio, compared to the environment's test average ratio varies by a greater degree on pagespeed-insights compared to local PC suggesting the pagespeed-insight's CPUs are under load (benchmark is not reliable).

### Test case
A page that artificially generates a TBT by performing calculations in a loop a fixed number of times.
Link: https://kraftpixel.com/test/tbt-load-test.html
Notes: The test page is a simple html page and has no 3rd-party or external resources, the script is inline to reduce the variability introduced by network.

**Screenshot of data for quick review**: https://i.imgur.com/ryhqigd.png

**Data (Google sheet)**: https://docs.google.com/spreadsheets/d/1RV5SJmBrOGDFy_P6hnlhUCpiZPdJIhFp8PVUdreugUE/edit?usp=sharing

## My understanding of the issue is as follows:
1. Lighthouse runs a small CPU benchmark test **at the start of the lighthouse test** to arrive at a score. The score is labeled as `Unthrottled CPU/Memory Power`
2. During the course of the test the CPU availability might not be guaranteed due to any of the following reasons (please feel free to add other cases)
    1. **Resource Contention**
        1. Is pagespeed insights executing something else (e.g. parallel tests) on the same node/server?
        2. or executing something else on the same physical server? e.g. 12 docker nodes running tests in parallel on a physical server that has only 6 physical CPU cores? These can be difficult to find as one would need to work closely with the data center to identify such cases)
    2. **CPU Throttling**: Are the servers running on a burstable class of servers (where the CPU is not guaranteed all the time?)
    3. **CPUs boost**: can boost for a certain time
3. ~~Lighthouse tries to adjust the score based on the the benchmark score but it does not take into account the variability of the CPU during the course of the entire test.~~ ( its a metric, not a score 🤦‍♂️ )

## Expected Outcome
1. Validation of the data and cause of the issue on https://pagespeed.web.dev/
2. If valid, report issue to pagespeed insights.
   1. Find a way to enable better interpretation of TBT metric, e.g. pagespeed or other services could show the CPU benchmark score besides the TBT metric for better visibility (at least as a hint that something is proportionately affecting reported TBT).

**Comment by prathamesh-gharat** [comment]
Thanks!
I agree about Lighthouse not scaling the TBT metric up/down based on the `CPU benchmark`. Lighthouse scales the metric values based on `CPU slowdown multiplier` though, right? (But that multiplier is always a static 4x in all my tests, so its not likely an issue.)

Let's wait for someone familiar with PSI to reply. 🙂

**Comment by jazyan** [comment]
At a high level, PSI has several jobs, which are spread across different data centers around the world. Each of these jobs has many tasks -- a particular LH run is performed within a single task. In theory, each task is guaranteed a certain amount of CPU and memory. In practice, there is resource contention between tasks within a single job, and the data centers also run other jobs not owned by our team. However, in aggregate, the median benchmark index in PSI is between 1000-1100, and very, very rarely does it fall below the warning threshold.

https://github.com/GoogleChrome/lighthouse/issues/6907 has some good context when this issue was brought up before, and https://github.com/GoogleChrome/lighthouse/issues/9085 has a detailed investigation and mitigations that I believe still hold today for PSI.

**Comment by prathamesh-gharat** [comment]
Thanks for the reply and references @jazyan.
> and the data centers also run other jobs not owned by our team*
I am assuming this is difficult to control because of infrastructure automation (some things get hidden behind virtual servers and are out of one's control / view).

@connorjclark or @jazyan could you also please confirm the following statement for the sake of our understanding?
The CPU benchmark (Unthrottled CPU/Memory Power) is a point-in-time benchmark (at the start of the test), it does not mean/guarantee that the same CPU resource (power) will be available **throughout** the duration of the test.

Could you also please agree / disagree with the following statements? (with comments if you feel it is necessary for us)
1. The online lighthouse tests should be taken with a grain of salt (salt being CPU variability) even after one is able to control the impact of 3rd party scripts / network variability.
2. The eventual source of truth (for effectiveness) would be CRUX and Google search console data since both are based on CWV metrics recorded from visitor's browsers (field data). Pagespeed lab tests results and recommendations should ideally be used as a guide. (This only applies as long as the website has decent traffic, we should fallback to lab tests in the absence of field data)

**Comment by adamraine** [comment]
This has been investigated before as mentioned in https://github.com/GoogleChrome/lighthouse/issues/15202#issuecomment-1611824626 and we have documentation discussing variability in general: https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md

I'm going to close this as I don't see any further actions we can take here.
