### ISSUE TITLE
Lighthouse crashes on all our Implementations

### ISSUE THREAD

**Issue by lemanschik** [GoogleChrome/lighthouse#15206]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://awesome-os.com

## Chromium Platform / All including ChromeOS Android. LaCroOS
the error did not show up on chromium platform it self it simple hangs but google chrome at last returns the below error. Note also That i am Implementing the newst WebAPI's i am platform / operating system engineer. I do not understand the error below as it points out he does not find the target which is simple the tab 

but as this happens in many indipendent chromium builds there must be something.

### What did you expect?

I expected that lighthouse runs and returns any results

#### 3 days before

i did try to look into the puppeteer code as i am familiar with the codebase and the platform side devtools implementation.

#### 06:51 Today
Tried to run lighthouse on other domains also fails looks like a system issue but happening on all chromium builds and even when running containered eg: snap builds. 

Puppeteer node works devtools from extensions via debugger also did work. 

Must be related to Linux Devtools maybe i am not sure if this is a lighthouse issue if it does not get the right tabId  at last on my current linux system which is a near unmodified debian/ubuntu where debian is the reference platform to build chromium it self. 

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

ALL

### Chrome Version

ALL Current including Chromium Platform without chrome 

### Node Version

No Issues

### OS

ChromeOS, FuchsiaOS, LaCroOS, Ubuntu, Debian, Snapd, 

### Relevant log output

```shell
Protocol error (Target.attachToTarget): No target with given id found

Channel: DevTools
Initial URL: https://awesome-os.com/
Chrome Version: 114.0.0.0
Stack Trace: f: Protocol error (Target.attachToTarget): No target with given id found
    at devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:4154
    at new Promise (<anonymous>)
    at Pd.send (devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:4087)
    at Pd._createSession (devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:5363)
    at devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:188840
    at Array.map (<anonymous>)
    at PuppeteerConnectionHelper.connectPuppeteerToConnection (devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:188830)
    at i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a%2F:1:2087)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a%2F:1:2967)
```

**Comment by adamraine** [comment]
This looks like the same issue as https://github.com/GoogleChrome/lighthouse/issues/15161.

What specific Chrome version numbers have you tested on?

**Comment by lemanschik** [comment]
@adamhenson i even build from googlesource in continuous mode via my own goma cluster this happens since more then a month but periodical i do not often run lighthouse tests in that builds via the devtools pannel. but it is a sure thing that it is ~97 till current nightly

**Comment by adamraine** [comment]
Closing as duplicate
