### ISSUE TITLE
iframe long tasks are shown as main thread long tasks but are not included in TBT

### ISSUE THREAD

**Issue by just-jeb** [GoogleChrome/lighthouse#15218]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://rotemy8.wixsite.com/chat

### What happened?

20 long tasks were identified as **main thread** long tasks, with total blocking time of 750ms ([link](https://pagespeed.web.dev/analysis/https-rotemy8-wixsite-com-chat/eqhvv06761?form_factor=mobile) to the specific PSI run)
![image](https://github.com/GoogleChrome/lighthouse/assets/9823087/66ec6c0a-a0b2-4817-aca5-5da85824b7df)

### What did you expect?

A lot of these tasks are coming from an iframe (which is run as a separate thread on Desktop Chrome, even in Mobile emulation mode). 
We know that it's more complicated than that, because on mobile browsers (or at least part of them) iframes also run in the main thread, but it seems that they are not counted towards TBT.  
I would expect one of the two: 
 - Tasks that are coming from iframe are not counted towards TBT (which is how it works now) **and** not shown as main-thread long tasks (which is not how it works now).
 - Tasks that are coming from iframe **are** counted towards TBT (if you sum all the excessive time it sums up to `1157ms` and not `750ms`) and are shown as main-thread long tasks (which is how it works now).  
 
Current state is inconsistent, because on one hand the tasks are listed as main-thread long tasks but OTOH they are not included in TBT, which makes it confusing and less actionable.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

10.2.0

**Comment by adamraine** [comment]
I believe this is how the old headless chrome (and therefore PSI) render iframes because I can get a similar result by running Lighthouse normally with `--chrome-flags="--headless=old"`:

https://trace.cafe/t/fwHOBIGcss

For reference, this is what a trace collected via Lighthouse in headful mode looks like (Notice the extra frame process track):

https://trace.cafe/t/XxmTTFaTTP

**Comment by just-jeb** [comment]
Sorry I might have been unclear about the intent. My issue is inconsistency - it's either the tasks are on the main thread (like with `--chrome-flags="--headless=old"`) and their time is included in TBT, or they are not on the main thread (like in your second trace) and their time is not included in TBT.  
Currently in the same report you get contradictory results - on one hand the iframe tasks are listed as main thread long tasks, on the other hand they are not included in TBT.  

Am I missing something and it's just how it's supposed to work?

**Comment by adamraine** [comment]
The tasks should contribute to TBT in the PageSpeed report you provided, but the total duration of the long tasks is larger than TBT for a couple of reasons:

- The duration of a task is not the same as the blocking time of a task. The blocking time is the task duration minus 50ms.
- [TBT only measures blocking time between FCP and TTI](https://web.dev/tbt/), however the long tasks audit will show long tasks from the entire run.
- PageSpeed insights uses [simulated throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md#types-of-cpu-throttling) interpolates the throttling of main thread tasks *after* loading the page.

**Comment by just-jeb** [comment]
Hey @adamraine, these are valid points, thank you.  
Putting TBT aside - should we consider long tasks that are coming from `iframe` as main-thread long tasks (just like PSI does)? 
This is important, because, even regardless of the TBT window, these might affect INP. 
Up until recently we were sure that the `iframe` long tasks are out of scope, because they run on a different thread, but now we realize it's not the case for Chrome Mobile. So how should we treat the `iframe` long tasks?

**Comment by adamraine** [comment]
Most users should be using a browser implementation that renders iframes in a separate process ([OOPIF](https://www.chromium.org/developers/design-documents/oop-iframes/)) (mobile browsers as well I believe), so for most users the iframes won't contribute to TBT. In general I would say you don't need to treat the long tasks as blocking if they are in an iframe that you know would meet the OOPIF criteria on a normal browser.

There are discussions internally about how we can use a browser implementation in PageSpeed that aligns more with standard Chrome. However, I wouldn't expect much movement on the subject in the near future unfortunately.
