### ISSUE TITLE
PageSpeed Insights API - was `observedTotalCumulativeLayoutShift` removed from response metrics?

### ISSUE THREAD

**Issue by wjh18** [GoogleChrome/lighthouse#15222]
**Summary**
I created/maintain a [Python cli for the PageSpeed Insights API](https://github.com/wjh18/pyspeedinsights) that I use to analyze my site performance in Excel.

I recently noticed that the metrics response data I'm getting from the API no longer includes the `observedTotalCumulativeLayoutShift` metric. There were 41 total metrics provided previously, now 40.

Few questions:

- Was this removed intentionally or as part of a general Lighthouse update?
- Should I expect these to change often or are they relatively set in stone?
- Is there somewhere I can stay up to date on what's included? The documentation doesn't include the information I need. I'm going to build better error handling into my package to prevent fatal errors, however it would be nice to stay abreast of any changes so I can update my documentation for which metrics are available.

Example JSON response from key `lighthouseReult -> audits -> metrics`:

```json
"metrics": {
    "id": "metrics",
    "title": "Metrics",
    "description": "Collects all available metrics.",
    "score": null,
    "scoreDisplayMode": "informative",
    "details": {
        "type": "debugdata",
        "items": [
            {
                "observedTimeOrigin": 0,
                "firstMeaningfulPaint": 173,
                "cumulativeLayoutShiftMainFrame": 0,
                "observedFirstContentfulPaintTs": 1600621774511,
                "interactive": 173,
                "observedLoadTs": 1600621740144,
                "observedTimeOriginTs": 1600621704783,
                "observedLastVisualChange": 67,
                "observedLargestContentfulPaintTs": 1600621774511,
                "observedFirstContentfulPaintAllFrames": 70,
                "observedLastVisualChangeTs": 1600621771783,
                "observedDomContentLoaded": 35,
                "firstContentfulPaint": 173,
                "observedCumulativeLayoutShift": 0,
                "observedFirstContentfulPaintAllFramesTs": 1600621774511,
                "observedCumulativeLayoutShiftMainFrame": 0,
                "observedFirstMeaningfulPaintTs": 1600621774511,
                "observedFirstMeaningfulPaint": 70,
                "cumulativeLayoutShift": 0,
                "largestContentfulPaint": 173,
                "observedNavigationStartTs": 1600621704783,
                "observedLargestContentfulPaintAllFramesTs": 1600621774511,
                "observedFirstPaint": 70,
                "observedLargestContentfulPaint": 70,
                "observedLargestContentfulPaintAllFrames": 70,
                "observedSpeedIndex": 68,
                "observedDomContentLoadedTs": 1600621739524,
                "observedLoad": 35,
                "maxPotentialFID": 16,
                "observedFirstPaintTs": 1600621774511,
                "observedTraceEndTs": 1600624112260,
                "totalBlockingTime": 0,
                "speedIndex": 173,
                "observedNavigationStart": 0,
                "observedFirstVisualChangeTs": 1600621771783,
                "observedFirstVisualChange": 67,
                "observedSpeedIndexTs": 1600621772568,
                "timeToFirstByte": 128,
                "observedFirstContentfulPaint": 70,
                "observedTraceEnd": 2407
            },
            {
                "lcpInvalidated": false
            }
        ]
    },
    "numericValue": 173,
    "numericUnit": "millisecond"
    },
```

**Comment by adamraine** [comment]
> Was this removed intentionally or as part of a general Lighthouse update?

Yes this was removed intentionally in #15122. `observedTotalCumulativeLayoutShift` refers to a modified version of CLS that was never used in the report. It was just there for debug data.

> Should I expect these to change often or are they relatively set in stone?

This audit is not actually displayed in the report, and is used mostly for debug data. The available fields are not set it stone.

> Is there somewhere I can stay up to date on what's included?

Generally the best way to stay up to date is by looking at our release notes. The change that you noticed was released in https://github.com/GoogleChrome/lighthouse/releases/tag/v10.3.0.

**Comment by wjh18** [comment]
Adam, thank you so much for the prompt response. GitHub search failed me on this one. I will keep an eye on those releases.
