### ISSUE TITLE
Page resources being loaded multiple times (eg 19x) resulting in slow audit times, high byte counts etc

### ISSUE THREAD

**Issue by samworm** [GoogleChrome/lighthouse#15265]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.mycarcheck.com/

### What happened?

When using PageSpeed Insights https://pagespeed.web.dev/

Page elements are bring loaded multiple times resulting in reported very slow loading / processing times etc.
Only seen in Mobile report despite the site serving the same content to Mobile and Desktop.

Example https://pagespeed.web.dev/analysis/https-www-mycarcheck-com/jfym0r1y76?form_factor=mobile

"Reduce unused JavaScript", "Avoid enormous network payloads, and other reports all show files being loaded and processed repeatedly. Also clearly visible repetition in tree view.

### What did you expect?

Expected:
An incognito Chrome window generating a Lighthouse (10.1.1) mobile report of https://www.mycarcheck.com/
104 requests • 1,524 KiB

Seen:
Pagespeed insights https://pagespeed.web.dev/analysis/https-www-mycarcheck-com/jfym0r1y76?form_factor=mobile
1,275 requests • 23,083 KiB

### What have you tried?

We have been unable to reproduce the behaviour in user testing or when using Chrome DevTools Lighthouse 

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

10.3.0

### Relevant log output

```shell
https://pagespeed.web.dev/analysis/https-www-mycarcheck-com/jfym0r1y76?form_factor=mobile
```

**Comment by adamraine** [comment]
I can't reproduce this, here is an example report from my testing: https://pagespeed.web.dev/analysis/https-www-mycarcheck-com/t58ynev7qn?form_factor=mobile

Does this happen every time for you?
