### ISSUE TITLE
Very High LCP value 

### ISSUE THREAD

**Issue by sunnybogawat** [GoogleChrome/lighthouse#15278]
I am using this module to measure the performance of my application pages. I have written a small node script that would use this module to measure the performance of the multiple pages of my application. To run the script with the user session I am first opening the Chrome instance in a debug mode and then with the app URL I am establishing the user session and further using the port I am running the script with the CLI command to measure the performance of the application.  The function code is as follows

`
  

    function runLighthouse(url, pageName) {
      return new Promise((resolve, reject) => {
        const reportPath = `report-${encodeURIComponent(pageName)}.html`;
        const chromeFlags = `--window-size=1920,1080`; // Adjust the viewport size as needed
        const lighthouseProcess = spawn('lighthouse', [
          url,
          '--output=html',
          '--only-categories=performance',
          '--port',
          port,
          '--chrome-flags',
          chromeFlags,
          '--max-wait-for-load=60000',
          `--output-path=${reportPath}`
        ]);
       lighthouseProcess.stdout.on('data', (data) => {});
    
        lighthouseProcess.stderr.on('data', (data) => {
          const errorOutput = data.toString();
          console.error(`Lighthouse measurement error: ${errorOutput}`);
        });
    
        lighthouseProcess.on('close', (code) => {
          if (code === 0) {
            console.log(`Lighthouse measurement completed for ${pageName}`);
            resolve(reportPath); // Resolve with the path of the HTML report
          } else {
            console.error(`Lighthouse measurement failed for ${pageName}`);
            reject(new Error(`Lighthouse process exited with code ${code}`));
          }
        });
      })
`

Now the issue I am facing with this is The LCP reading I am getting in the report is very high as compared to when I measure the same using the lighthouse tool. I am not sure through script why that reading is too high?

**Comment by sunnybogawat** [comment]
The Chrome launched in debug mode is needed for me to keep the user session. I am not found any better way to establish a session before I run the lighthouse for the multiple URLs. The window size flags which I added in the scripts are just added for testing purposes. They didn't require me.

**Comment by sunnybogawat** [comment]
Yes I am trying the Option 4: Open a debug instance of Chrome and manually log in

**Comment by sunnybogawat** [comment]
I have tried Puppeteer also but I am unable to cope with authentication and user session problems so go ahead with debug instance of Chrome and manually log in. Using this option my session is resolved but not able to get the correct LCP values

**Comment by sunnybogawat** [comment]
With Chrome launcher I am facing the same issue. When I used the port from the chrome launcher then the LCP values is being captured very high. Thanks for reopening the issue and I hope this would be addressed at the earliest.

**Comment by connorjclark** [comment]
Can you update to the latest version of Lighthouse and see if the issue persists?

What kind of machine are you using?
