### ISSUE TITLE
Authenticated pages behave differently in Lighthouse than regular usage

### ISSUE THREAD

**Issue by acdha** [GoogleChrome/lighthouse#15272]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

internal

### What happened?

I have an old legacy PHP app which uses a messy cookie-based session system, so this might be compatibility with bad code but I found an interesting quirk. Lighthouse reloads the page and that behaves as expected but at some point just as it transitions from the “gathering information about the page” to “preparing the report”, it does something which causes the page to reload _without_ using my existing session cookie, causing it to redirect to the login page.

https://github.com/GoogleChrome/lighthouse/blob/main/docs/authenticated-pages.md makes this claim:

> The Lighthouse panel in Chrome DevTools will never clear your cookies, so you can log in to the target site and then run Lighthouse. If localStorage or indexedDB is important for your authentication purposes, be sure to uncheck Clear storage.

Toggling that setting doesn't make a difference. I did notice from comparing the two requests for the main page URL is that the one which works has the header `sec-fetch-site: none` and the second one (which fails) has `sec-fetch-site: same-origin`, but that server doesn't use that for anything.

The other difference is that the session cookies change, which is a characteristic of this app (the Code Igniter framework has some mid-90s style bugs in its cookie handling), which shouldn't normally be an issue but it made me wonder whether the problem is something along the lines of Lighthouse somehow _using_ the existing cookies but not updating the cookie store with the cookies obtained by the request it makes for analysis.

### What did you expect?

Behaviour identical to regular browsing

### What have you tried?

1. Confirmed that normal browsing works well
2. Configured that both Edge and Chrome are identical in this regard

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

10.1.1

### Chrome Version

114.0.5735.198 (Official Build) (arm64)

### OS

macOS

**Comment by adamraine** [comment]
> Lighthouse reloads the page and that behaves as expected but at some point just as it transitions from the “gathering information about the page” to “preparing the report”, it does something which causes the page to reload without using my existing session cookie, causing it to redirect to the login page

At the end of the Lighthouse run, Lighthouse will navigate away from the page and back to test the [bfcache](https://developer.chrome.com/docs/lighthouse/performance/bf-cache/). The only way to disable this behavior in DevTools is to disable the entire performance category.

If you are using the CLI, you can skip the bfcache audit individually with `--skip-audit=bf-cache`.

For more on this topic: #14336
