### ISSUE TITLE
[Typescript] Cannot find namespace 'LH'

### ISSUE THREAD

**Issue by ittaibaratz** [GoogleChrome/lighthouse#15296]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

n/a

### What happened?

When importing the desktop config, i.e.
```
import lighthouseDesktopConfig from 'lighthouse/core/config/lr-desktop-config';
```

Typescript (v5.0.3) fails to compile my code with the following error:

```
../../node_modules/lighthouse/core/config/lr-desktop-config.d.ts(3,23): error TS2503: Cannot find namespace 'LH'.
```

Workaround: 

Skip lib check (via tsconfig.json)
```
"skipLibCheck": true
```

It's not a major issue as I can use the skip lib check workaround.

### What did you expect?

Typescript should compile with no problems.

### What have you tried?

Tried updating `types` in tsconfig.json but it did not help.

### How were you running Lighthouse?

node

### Lighthouse Version

10.4.0

### Chrome Version

114

### Node Version

18.16.0

### OS

Mac OS

### Relevant log output

```shell
../../node_modules/lighthouse/core/config/lr-desktop-config.d.ts(3,23): error TS2503: Cannot find namespace 'LH'.
```

**Comment by Printpedia1004** [comment]
bug issue

**Comment by adamraine** [comment]
`lr-desktop-config.js` is a special config used by PageSpeed insights. Nothing wrong with using it, but it's slightly different from the general purpose desktop config in `desktop-config.js`. The best way to import the desktop config is from the toplevel entry point:

```js
import {desktopConfig} from 'lighthouse';
```

@ittaibaratz is there a specific reason you need to use `lr-desktop-config.js` instead of the general purpose desktop config?

**Comment by ittaibaratz** [comment]
@adamraine no good reason - I just found it in a blog post and copied. 

Thanks for the quick response, this can be closed now.
