### ISSUE TITLE
Wrong viewport in screenshots with `headless: 'new'`

### ISSUE THREAD

**Issue by sokki** [GoogleChrome/lighthouse#15309]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://example.com

### What happened?

Since we switched to launch puppeteer with `headless: 'new'`, the viewport of the screenshot is wrong. It appears as if it would use the default window size instead of the emulated screen.

Repro: https://github.com/sokki/bug-new-headless-screenshot/blob/main/index.js

With `headless: 'new'`:
![image](https://github.com/GoogleChrome/lighthouse/assets/665748/c84086d1-70fd-47ec-bf80-7d96a137212f)

With `headless: true`:
![image](https://github.com/GoogleChrome/lighthouse/assets/665748/5e17ca7b-eba4-4c5d-b2be-b26e2a40491f)

### What did you expect?

Properly sized screenshot.

### How were you running Lighthouse?

node

### Lighthouse Version

10.4.0

### Chrome Version

115.0.0.0

### Node Version

18

### OS

mac + linux

**Comment by adamraine** [comment]
This looks like the same issue as https://github.com/GoogleChrome/lighthouse/issues/12988

**Comment by adamraine** [comment]
Ah thanks @sokki. Looks like this is an issue with [Chrome for testing](https://developer.chrome.com/blog/chrome-for-testing/) which Puppeteer uses by default now. A workaround would be to specify a path to your own Chrome executable. I will update #12988.

**Comment by thiagowfx** [comment]
It's not a Chrome for Testing issue per se, even vanilla Chrome exhibits it.

Note that https://bugs.chromium.org/p/chromium/issues/detail?id=1277272 was filed even before Chrome for Testing existed.
