### ISSUE TITLE
Get error TypeError: Ni.connect is not a function when generate a Lighthouse Report

### ISSUE THREAD

**Issue by maitrongnhan99** [GoogleChrome/lighthouse#15316]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://zim.vn/on-demand-class

### What happened?

I getting an error right after generate a Lighthouse Report

Channel: DevTools
Initial URL: https://zim.vn/on-demand-class
Chrome Version: 115.0.0.0
Stack Trace: TypeError: Ni.connect is not a function

### What did you expect?

Pls fix this.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

v10.4.0

### Chrome Version

Chrome Version: 115.0.0.0

### OS

Mac OS

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/15300
