### ISSUE TITLE
Do not suggest to eliminate CSS as a render blocking resource when it obviously is required to render

### ISSUE THREAD

**Issue by romainmenke** [GoogleChrome/lighthouse#15322]
A single CSS file is technically blocking first render/paint, but it also IS the first render/paint.

A single CSS file obviously is a dependency for rendering page content.

This warning only nudges web developers towards bad practices.
It should be removed or tuned to only warn when multiple CSS files are loaded.

<img width="745" alt="Screenshot 2023-08-01 at 10 46 10" src="https://github.com/GoogleChrome/lighthouse/assets/11521496/3f2a44ec-6fa4-43cd-a38a-cb5a42dac666">

**Comment by adamraine** [comment]
The audit suggests to inline critical CSS. Would this work in your case?

**Comment by romainmenke** [comment]
Why would you inline CSS if you only have a single CSS file and that CSS file is small enough to be less than 14kb compressed.

Why would you add the extra complexity of extracting and inline critical CSS?
What is the critical CSS with a CMS where a client has full control over the appearance of every page?

Surely there is a tipping point where the current advice becomes bad advice :)

**Comment by adamraine** [comment]
> Why would you inline CSS if you only have a single CSS file and that CSS file is small enough to be less than 14kb compressed.

> Why would you add the extra complexity of extracting and inlining critical CSS?

It is still faster to deliver the CSS inline than it is to make an additional request for it.

> Also what is the critical CSS with a CMS where a client has full control over the appearance of every page?

You mentioned that the stylesheet in question is required for the first paint, so something in that CSS file is clearly critical in your case. There are also tools you can use to identify which styles are used for the initial page render:

https://developer.chrome.com/docs/lighthouse/performance/render-blocking-resources/#how-to-identify-critical-resources

> Surely there is a tipping point where the current advice becomes bad advice :)

The performance benefits are still there even if they are small. This doesn't become bad advice simply because it is too complex to implement in your case. If you don't think the performance improvement is worth the implementation effort then that's your choice.

**Comment by romainmenke** [comment]
But the performance benefit only applies to the first page right?

The second page view would have a cached version of this single CSS file.
At this point the inlined CSS would slow down the html download and parsing.

Correct?

**Comment by paulirish** [comment]
Fetching a resource out of the disk cache isn't free. (Nothing is free though.. you're right that inlining the CSS adds some cost to the HTML download that repeat views have to pay)

if we accept the premise that you want to get to FCP as fast as possible, inline just enough CSS to get there and defer the rest so it won't block.

on 14kb. it comes from TCP slowstart, to fit in the initial roundtrip right as the TCP connection is established: https://hpbn.co/building-blocks-of-tcp/#:~:text=window%3A%2065%2C535%20bytes-,Initial%20congestion%20window,-%3A%2010%20segments%20(

but according to your screenshot.. the css is served from `wp-static.assets.sh`, which is a different origin than your HTML. And since this CSS is render blocking, you're also paying the TCP connection overhead for this origin. Preconnect/preload could help but there's no way its as fast as inlining.


what @adamraine  said earlier is legit:

> The performance benefits are still there even if they are small. This doesn't become bad advice simply because it is too complex to implement in your case. If you don't think the performance improvement is worth the implementation effort then that's your choice.

While our recommendations primary focus on cold load, the majority of poor experiences are on cold load. 

Regardless, you're welcome to try this out and benchmark it. For cold and warm loads. I suspect even on a warm load the inlined approach will be faster, unless the CSS is >100kb. That's what we've seen in our testing.

**Comment by romainmenke** [comment]
> but according to your screenshot.. the css is served from wp-static.assets.sh, which is a different origin than your HTML. And since this CSS is render blocking, you're also paying the TCP connection overhead for this origin. Preconnect/preload could help but there's no way its as fast as inlining.

But that is not what the warning/advice is about.

If the extra TCP connection is the issue then it shouldn't be suggestion to inline/defer the CSS. It should suggest to move this resource to the same origin as the page itself.

------

> While our recommendations primary focus on cold load, the majority of poor experiences are on cold load.
>
> Regardless, you're welcome to try this out and benchmark it. For cold and warm loads. I suspect even on a warm load the inlined approach will be faster, unless the CSS is >100kb. That's what we've seen in our testing.

My issue with the current advice is that it isn't absolutely true.

Adding bloat to each page with inlined critical CSS might make some pages a bit faster but it isn't purely positive. It does add extra weight to each html page.

It also is enormously complex to setup critical CSS inlining unless you have full control over a website. If you have a CMS with a page builder / dynamic layouting you wont know the critical CSS for a given url at build time. It will only be known when a request is handled. Processing this server side, on the fly slows down the response.

I agree that in a simple and ideal setup (i.e. a lab test) inlining CSS will appear to be better. But in real world projects it is not that black and white.

I think the threshold for suggesting inlined CSS should be much higher than it currently is.

**Comment by equinusocio** [comment]
Not to mention that "Inline style" is `style=""` os it's suggesting to put styles on HTML elements, while I guess the suggestion is to move it as embedded with `<style>`. Words matters and anyone who's writing html/css knows that inline style is not the same as embedded, despite the common misusage of the "inline" term.

**Comment by adamraine** [comment]
> But that is not what the warning/advice is about.
>
> If the extra TCP connection is the issue then it shouldn't be suggestion to inline/defer the CSS. It should suggest to move this resource to the same origin as the page itself.

Inlining is still going to be faster than optimizing the origin/preconnect situation to load a blocking request as fast as possible.

> It also is enormously complex to setup critical CSS inlining unless you have full control over a website. If you have a CMS with a page builder / dynamic layouting you can not know the critical CSS for a given url at build time. It will only be known when a request is handled. Processing this server side, on the fly, slows down the response.

Again, If this isn't worth the implementation effort and you can improve your FCP/LCP metrics in other ways then godspeed. The lighthouse score is based on the performance metrics alone, this render blocking audit will not affect the score directly.

You can even measure the performance of a warm load with a [user flow](https://github.com/GoogleChrome/lighthouse/blob/main/docs/user-flows.md).

> I agree that in a simple and ideal setup (i.e. a lab test) inlining CSS will appear to be better. But in real world projects it is not that black and white.

If you're interested in real world impact here is one site doing A/B testing of render blocking resources:
https://philipwalton.com/articles/performant-a-b-testing-with-cloudflare-workers/

It isn't black and white but there are performance benefits measured in the field as well as the lab.

> I think the threshold for suggesting inlined CSS should be higher than it currently is.

https://web.dev/optimize-lcp/#2-eliminate-element-render-delay:~:text=In%20general%2C%20inlining,candidate%20for%20inlining

The impact of caching is more important for larger resources not smaller ones. Even for larger CSS bundles splitting and deferring non-critical CSS should have a better impact on performance than just leaving everything as render blocking and expecting caching to take care of it.

-----

> Not to mention that "Inline style" is style="" so it's suggesting to put styles on HTML elements, while I guess the suggestion is to move it as embed with <style>. Words matter and anyone who's writing html/css since 2010 knows that inline style is not the same as embedded, despite the common misusage of the "inline" term.

You are technically correct but this is off topic, please file a separate issue @equinusocio

**Comment by romainmenke** [comment]
> Again, If this isn't worth the implementation effort and you can improve your FCP/LCP metrics in other ways then godspeed. The lighthouse score is based on the performance metrics alone, this render blocking audit will not affect the score directly.

I never said it didn't score high.
I didn't come here asking to adjust how performance is scored :D

<img width="569" alt="Screenshot 2023-08-02 at 22 02 12" src="https://github.com/GoogleChrome/lighthouse/assets/11521496/4cbb1710-295d-475a-900b-935462b35fa2">

---------------

But it's clear to me by now that there is no intention here to adjust this warning.
That's fair.

**Comment by occupant55** [comment]
https://written9.github.io/pBNy2SYtq7EM6rA1V06gi9K_EpQDEqyR5NnFwQ-n_UmGXgYMh6a1ls-HTSbk0y3cGBYDkfF0vDs/ I located the key

**Comment by equinusocio** [comment]
> You are technically correct but this is off topic, please file a separate issue @equinusocio

I'm technically correct but you refused to fix it, https://github.com/GoogleChrome/lighthouse/issues/15333, which is objectively wrong.  Continuing to spread misleading information about inline and embedded styles.
