### ISSUE TITLE
Wrong lighthouse suggestion about inline style.

### ISSUE THREAD

**Issue by equinusocio** [GoogleChrome/lighthouse#15333]
See https://github.com/GoogleChrome/lighthouse/issues/15322#issuecomment-1661645690
> Not to mention that "Inline style" is style="" so it's suggesting to put styles on HTML elements, while I guess the suggestion is to move it as embed with <style>. Words matter and anyone who's writing html/css since 2010 knows that inline style is not the same as embedded, despite the common misusage of the "inline" term.

![CleanShot 2023-08-03 at 08 37 00](https://github.com/GoogleChrome/lighthouse/assets/10454741/7da05c6b-b9b8-4486-a356-4193b9f10730)

**Comment by connorjclark** [comment]
This audit is going away soon (it should have in 13.0 but was missed), so I'll go ahead and close this.

#16770

**Comment by connorjclark** [comment]
actually the new insight audit also uses the term "inline".

```
Requests are blocking the page\'s initial render, which may delay LCP. ' +
      '[Deferring or inlining](https://developer.chrome.com/docs/performance/insights/render-blocking) ' +
      'can move these network requests out of the critical path.
```

https://developer.chrome.com/docs/performance/insights/render-blocking

"internal" is the correct term.
