### ISSUE TITLE
Update to chrome-devtools-frontend >= 1.0.448737

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1535]
This will fix the destroySSL bug that's described in https://github.com/GoogleChrome/lighthouse/issues/73#issuecomment-270574112

Might as well update to latest module version.

This upgrade will require some work as devtools dropped the "WebInspector" namespace, and now uses 40-ish global namespaces.  I've already done most of that work over in https://github.com/paulirish/devtools-timeline-model/tree/master/lib but it'll need porting to our use in `lib/web-inspector.js` etc

**Comment by paulirish** [comment]
i have a WIP in `bump-devtools` branch for this.

**Comment by paulirish** [comment]
now 1.0.448737 to also upgrade Gonzalez and fix #1412

**Comment by XhmikosR** [comment]
@paulirish: any updates on this? It's been a long time we hit #1412.

**Comment by wardpeet** [comment]
@paulirish mind if I look at your branch and try to get this working? ^^

**Comment by paulirish** [comment]
@wardpeet go for it.

**Comment by paulirish** [comment]
https://github.com/GoogleChrome/lighthouse/tree/bump-devtools has some work from feb 11th that you can start from. 

thanks for helping me out with this. :)

**Comment by wardpeet** [comment]
@paulirish should we close this? as you mentioned this wasn't necessary anymore

**Comment by paulirish** [comment]
good call!
