### ISSUE TITLE
DNS servers could not resolve the provided domain

### ISSUE THREAD

**Issue by Achchheweb** [GoogleChrome/lighthouse#15358]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://unifiedportal-emp.epfindia.gov.in/epfo/

### What happened?
**There was an error running Lighthouse: `DNS servers could not resolve the provided domain.` (code: DNS_FAILURE)**

I have implements lighthouse on local as well as on serve with node. all thing is going good but when it run https://unifiedportal-emp.epfindia.gov.in/epfo/  getting errors DNS_FAILURE but it is working on local system errors only outcomes on serve. what i'm doing wrong with config header or extraHeaders passed in it. i have tried many time but didn't found any way kindly suggest me to what i do 

my config setting is

'extends' => 'lighthouse:default',
            'settings' => [
                'onlyCategories' => ['performance','accessibility','best-practices','seo', 'pwa'],
                'emulatedFormFactor' => 'desktop',
                'emulatedUserAgent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) AppleWebKit/537.36 (KHTML, like Gecko) Gecko/20100101 Chrome/109.0.0.0 Safari/537.36',
                'formFactor' => 'desktop',
                'screenEmulation' => [
                    'mobile' => false,
                    'width' => 1350,
                    'height' => 940,
                    'deviceScaleFactor' => 0.9,
                    'disabled' => false,
                ],
                'output' => ['json', 'html'],
                'skipAudits' => [
                    'uses-http2',
                    'bf-cache',
                ],
                'disableNetworkThrottling' => false,
                'disableCpuThrottling' => false,
                'throttlingMethod' => 'simulate',
                "throttling" => [
                    "rttMs" => 150,
                    "cpuSlowdownMultiplier" => 4,
                    //"requestLatencyMs"=> 40,
                    "downloadThroughputKbps" => 10240,
                    "uploadThroughputKbps" => 10240,
                    "offline" => true
                ],
                'maxAutodiscoverUrls' => 10,
                "extraHeaders" => [
                    'Follow-Redirects' => 'true',
                    'Origin' => $host,
                    "x-User-Agent" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) AppleWebKit/537.36 (KHTML, like Gecko) Gecko/20100101 Chrome/109.0.0.0 Safari/537.36",
                    "x-accept" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Language" => "en-US,en;q=0.5",
                    "Connection" => "keep-alive",
                    "Referer" => $domain_url,
                    "X-TotalFetchedSize" => "*",
                    "Accept-Encoding" => "gzip, deflate",
                    "Content-Encoding" => "gzip, deflate",
                    "Cookie" => "monster=blue;SERVERID=ha105;token=LHCI_TOKEN;Secure",
                    "x-men" => "wolverine",
                    "x-frame-options" => "SAMEORIGIN",
                    'Access-Control-Request-Method' => 'GET',
                    'Access-Control-Request-Headers' => 'X-Requested-With',
                    'Access-Control-Allow-Origin' => "*",
                    'Origin-Agent-Cluster' => '?1',
                    "Access-Control-Allow-Headers" => "Content-Type",
                    "Access-Control-Allow-Credentials" => "true",
                    "Referrer-Policy" => "strict-origin-when-cross-origin",
                    "x-xss-protection" => "1; mode=block",
                    'x-Ignore-Firewall' => "true",
                    'x-Follow-Redirection' => "true",
                    "strict-transport-security" => "max-age=31536000; includeSubDomains; must-revalidate",
                    'Cache-Control' => 'no-cache, max-age=0, immutable, private, no-store, must-revalidate',
                    'Timing-Allow-Origin' => "*",
                    "Continent" => "AS",
                    "content-security-policy" => 'frame-ancestors "self" https://www.google-analytics.com',
                    "Cross-Origin-Resource-Policy" => 'same-site | same-origin | cross-origin',
                    "Vary"=> "Origin",
                    "Pragma"=> "no-cache",
                    "Service-Worker-Navigation-Preload"=> 'true',
                    "X-Content-Type-Options"=>"nosniff",
                ]

### What did you expect?

I want to get the lighthouse reports for this sites i'm not able fetch this url reports like other urls working fines for me except to it.

### What have you tried?

I have tried the referred, Origing all types of parameters passed in header but still it coming. But it's working on local System when i make it live then only this site is not working

### How were you running Lighthouse?

node

### Lighthouse Version

10.3

### Chrome Version

114.0

### Node Version

18.0

### OS

Ubuntu 20.0

### Relevant log output

```shell
All lighthouse reports like performance, Seo, Accessibility, Best-Practices etc
```

**Comment by Achchheweb** [comment]
Hi can you please check this issue ? How can i generate the lighthouse reports for this url : https://unifiedportal-emp.epfindia.gov.in/epfo/
This site is not able to connect with lighthouse getting DNS issue.

**Comment by Achchheweb** [comment]
I don't get it. did you check this  https://unifiedportal-emp.epfindia.gov.in/epfo/ site in  https://frontend-lighthouse.webgarh.net/ ?
you can also check other site in it other sites are working properly. errors only coming for https://unifiedportal-emp.epfindia.gov.in/epfo/  site. If there's issue in my environment then other site will also not work on this https://frontend-lighthouse.webgarh.net/
![image](https://github.com/GoogleChrome/lighthouse/assets/141727306/17321904-5ce5-42dc-a3b0-162fd8abe5fc)
![image](https://github.com/GoogleChrome/lighthouse/assets/141727306/e5e32db4-e6e0-49fb-882c-4fcf4a17e721)

**Comment by Achchheweb** [comment]
@adamraine needs-priority

**Comment by adamraine** [comment]
We don't maintain https://frontend-lighthouse.webgarh.net/ so we can't debug this DNS issue for you sorry.
