### ISSUE TITLE
When can you add INP metrics?

### ISSUE THREAD

**Issue by CanbingChen** [GoogleChrome/lighthouse#15362]
**Feature request summary**

File Path: ./core/audits/metrics/interaction-to-next-paint.js

I want use INP metrics in my report. But it not work.  

Environment Information
Lighthouse version: 11.0.0

**Comment by adamraine** [comment]
INP is available in Lighthouse timespan mode, please see https://github.com/GoogleChrome/lighthouse/blob/main/docs/user-flows.md.

**Comment by CanbingChen** [comment]
Thanks !
