### ISSUE TITLE
SyntaxError: The "start lh:runner:gather" performance mark has not been set

### ISSUE THREAD

**Issue by firsthahaha** [GoogleChrome/lighthouse#15379]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

node server

### What happened?

Using Postman to retrieve local express requests, and requesting multiple different interfaces, the "start lh: runner: gatherer" performance mark has not been set

### What did you expect?

why

### How were you running Lighthouse?

node

### Lighthouse Version

10.4.0

### Node Version

16.18.0

### OS

windows

### Relevant log output

```shell
Using Postman to retrieve local express requests, and requesting multiple different interfaces, the "start lh: runner: gatherer" performance mark has not been set
```

**Comment by connorjclark** [comment]
You haven't given us any relevant information. Is this a problem with using Lighthouse? How are you using it? Please provide reproducible steps.

**Comment by lcw0622** [comment]
@connorjclark  I met same problem. I run 2 lighthouse benchmark at the same time, and one task succeeded, another throw this error. 
this error can be reappear stably.
Here is the error stack:
```
node:internal/per_context/domexception:53
    ErrorCaptureStackTrace(this);
    ^
DOMException [SyntaxError]: The "start lh:runner:gather" performance mark has not been set
    at new DOMException (node:internal/per_context/domexception:53:5)
    at __node_internal_ (node:internal/util:505:10)
    at getMark (node:internal/perf/usertiming:58:11)
    at calculateStartDuration (node:internal/perf/usertiming:141:13)
    at EventTarget.measure (node:internal/perf/usertiming:159:7)
    at Module.exports.stop (/Users/blank/project/backend/node_modules/.pnpm/marky@1.2.5/node_modules/marky/lib/marky.cjs.js:77:24)
    at Function.timeEnd (file:///Users/blank/project/backend/node_modules/.pnpm/lighthouse-logger@2.0.1/node_modules/lighthouse-logger/index.js:144:11)
    at Function.gather (file:///Users/blank/project/backend/node_modules/.pnpm/lighthouse@11.1.0/node_modules/lighthouse/core/runner.js:216:13)
    at runMicrotasks (<anonymous>)
    at runNextTicks (node:internal/process/task_queues:61:5)
```

**Comment by brdaugherty** [comment]
I am able to reliably reproduce this, or something very close to this when `preset` is unset and `plugins` is defined in the options passed to lighthouse. See lines 40,43 of Gist.  The origin being audited matters, not all URIs result in an exception being thrown, see line 36 of Gist.

https://gist.github.com/brdaugherty/3a2b19a46fd94649430800ce0623e3d8

Exception 
```0|gis-lh-plugin-runner  | SyntaxError: The "start lh:runner:gather" performance mark has not been set
0|gis-lh-plugin-runner  |     at new DOMException (node:internal/per_context/domexception:53:5)
0|gis-lh-plugin-runner  |     at __node_internal_ (node:internal/util:664:10)
0|gis-lh-plugin-runner  |     at getMark (node:internal/perf/usertiming:68:11)
0|gis-lh-plugin-runner  |     at calculateStartDuration (node:internal/perf/usertiming:193:13)
0|gis-lh-plugin-runner  |     at measure (node:internal/perf/usertiming:211:7)
0|gis-lh-plugin-runner  |     at Performance.measure (node:internal/perf/performance:135:12)
0|gis-lh-plugin-runner  |     at exports.stop (/var/www/html/gis-lighthouse/node_modules/marky/lib/marky.cjs.js:77:24)
0|gis-lh-plugin-runner  |     at Log.timeEnd (file:///var/www/html/gis-lighthouse/node_modules/lighthouse-logger/index.js:144:11)
0|gis-lh-plugin-runner  |     at Runner.gather (file:///var/www/html/gis-lighthouse/node_modules/lighthouse/core/runner.js:216:13)
0|gis-lh-plugin-runner  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by adamraine** [comment]
This seems like it could be caused by running multiple Lighthouse tests at the same time from the same process. Lighthouse timing information is stored in marky global state, so multiple Lighthouse tests will be using the same performance mark ids.

To run multiple Lighthouse tests at the same time, they need to be in different processes.

**Comment by brdaugherty** [comment]
First, here's what "fixed" it for me: `ps ax | grep lighthouse` and manually issuing`kill`  to all headless chrome processes. 
Since then I've been unable to repro this behavior.

There were 10 or so older headless instances which failed to close for some reason or another -- but certainly some were due to bugs in the node code I've been iterating on during app development. Leaving multiple, older chrome process around by commenting out `chrome.kill()`  had no effect on subsequent audits and tests. 

I wasn't paying attention to node processes when killing the chrome processes, so I do not know if there was one or more parent node process which were then able to terminate as a result of their chrome child process being manually killed.

What I am going to watch out for if this crops up again in the future is multiple node processes using `lighthouse/report/render` modules.  One last thing that I noticed in addition to the exception was the LHReport objects generated when the exception was thrown seemed to be malformed: JS/CSS rendered badly when used as iframe srcdoc contents.

FWIW, I am using pm2 to restart node during app development on Debian.

**Comment by kundan8239** [comment]
I am currently encountering a similar issue with specific domains. 
The domains in question are https://www.chocolatechipcookies.co.uk/ , https://ailes.ez37m.com/. 
Lighthouse: "11.2.0"
Chrome version: "118.0.5993.70-1".
lighthouse version :  11.2.0
chrome version:  "118.0.5993.70-1" 

`   
      this.chrome = await chromeLauncher.launch({
        chromeFlags: [
          '--no-first-run',
          '--headless=new',
          // '--single-process',
          '--no-zygote',
          '--disable-gpu',
          '--no-sandbox',
          '--disable-dev-shm-usage',
        ],
      });
      logger.debug(`Launched chrome on port ${this.chrome.port} and pid ${this.chrome.pid} for ${target} - ${correlationId}`);

      const lhrs = [];
      let demoReport = null;
   for (let i = 0; i < iterations; i++) {
        logger.debug(`Running ${i} scan for ${target} - ${correlationId}`);
        const options = {
          logLevel: 'error',
          output: 'html',
          maxWaitForLoad: 60000,
          // skipAudits: ['full-page-screenshot'],
          onlyCategories: [
            'accessibility',
            'best-practices',
            'performance',
            'pwa',
            'seo',
          ],
          port: this.chrome.port,
          hostname: '127.0.0.1',
        }
        if (device.toLowerCase() === CONSTANT.DESKTOP) {
          options['screenEmulation'] = CONSTANT.DESKTOP_CONFIG.DESKTOP_EMULATION_METRICS;
          options['formFactor'] = CONSTANT.DESKTOP;
          options['throttling'] = CONSTANT.DESKTOP_CONFIG.THROTTLING.DESKTOP_DENSE_4G;
          options['emulatedUserAgent'] = CONSTANT.DESKTOP_CONFIG.EMULATED_USER_AGENT;
        } else
          device = CONSTANT.MOBILE
        let timerObj;
        const runnerResult = await Promise.race([
          new Promise((resolve, reject) => {
            timerObj = setTimeout(async () => {
              reject(new Error('Max execution time exceeded'));
            }, 300000);
          }),
          lighthouse(target, options),
        ]);
        timerObj && clearTimeout(timerObj);

        demoReport = runnerResult;
        lhrs.push(runnerResult.lhr);
      }

      if (demoReport.lhr && demoReport.lhr.environment) {
        logger.debug(`Environment of scan result for ${target} - ${correlationId} - LH:${demoReport.lhr.lighthouseVersion} - NUA:${demoReport.lhr.environment.networkUserAgent} - HUA:${demoReport.lhr.environment.hostUserAgent}`);
      }

      const { mainDocumentUrl, audits, categories: categoryResults } = generateAverageReport(lhrs); // finalurl deprecated in lighthouse 10 in place of finalurl, mainDocumentUrl is used.
   `

![image-20240119-050305 (1)](https://github.com/GoogleChrome/lighthouse/assets/26499928/b18900d6-a5c4-4210-bd91-7cc9f24083ae)
