### ISSUE TITLE
'Links do not have descriptive text' does not take internationalisation into account.

### ISSUE THREAD

**Issue by Jacco-V** [GoogleChrome/lighthouse#15377]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://9cclimbing.be/collections/outlet

### What happened?

Lighthouse flags the word 'start' (the Dutch word for 'home') as a non-descriptive link text. 

According to the list presented in the documentation ([https://developer.chrome.com/docs/lighthouse/seo/link-text/](https://developer.chrome.com/docs/lighthouse/seo/link-text/)), lighthouse flags the following generic link texts:

- click here
- click this
- go
- here
- this
- start
- right here
- more
- learn more

note that: a) these are English texts, b) 'home' is not among the words in the list.

Since the Dutch term for `Home page` is `Start pagina` or `Start` for short. 

The HTML-page in question starts with declaring that the content of the page is Dutch:

```html
<!DOCTYPE html>
   <html lang="nl" (...)>
```

Yet, the Dutch word for 'home' (='start') is flagged as non-descriptive, even though it should not, because the equivalent English term (='home') is not on the list of non-descriptive link texts.

### What did you expect?

I expect lighthouse to take localisation into account, and not flag words from the English list of non-descriptive link texts, as non-descriptive in other languages (where said word have a different meaning).

### What have you tried?

not applicable.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

Aug 14, 2023, 3:45:30 PM

### Chrome Version

not applicable.

### Node Version

not applicable.

### OS

online

### Relevant log output

```shell
Links do not have descriptive text 1 link found
Descriptive link text helps search engines understand your content. Learn how to make links more accessible.
Link destination
	
Link Text
9cclimbing.be
1st party	
https://9cclimbing.be
	
'Start'
```

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/14845
