### ISSUE TITLE
Dom Content Loaded Start and End Time

### ISSUE THREAD

**Issue by ashwinrajanta** [GoogleChrome/lighthouse#15371]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.amazon.com

### What happened?

Dom content loaded start and end time is not displayed in the report!!

### What did you expect?

Dom content loaded start and end time should be displayed in the json report

### What have you tried?

[lighthousereport.pdf](https://github.com/GoogleChrome/lighthouse/files/12320967/lighthousereport.pdf)

### How were you running Lighthouse?

node

### Lighthouse Version

11.0.0

### Node Version

20.5.0

### OS

debian. bullseye

**Comment by ashwinrajanta** [comment]
[dockerfile2.txt](https://github.com/GoogleChrome/lighthouse/files/12321188/dockerfile2.txt)


docker build -t google -f dockerfile2 .
docker run -dit --cap-add=ALL <image_id> bash 

su -c "lighthouse https://www.amazon.com/ --chrome-flags="--headless" --chrome-flags="--ignore-certificate-errors"  --chrome-flags="--disable-dev-shm-usage"  --only-categories=performance --output json --output-path="./lighthousereport.json"  " chrome

**Comment by ashwinrajanta** [comment]
what is this values 
"observedLastVisualChangeTs": 18549157723,
"observedLoadTs": 18536757914,
"observedTraceEndTs": 18549160231,

How do i convert it to human readable format?? 
is it UTC or epoch or what format?

is there any documents clearly mentioned for each metrics  and what it states???

**Comment by ashwinrajanta** [comment]
what is this values 
"observedLastVisualChangeTs": 18549157723,
"observedLoadTs": 18536757914,
"observedTraceEndTs": 18549160231,

How do i convert it to human readable format?? 
is it UTC or epoch or what format?

is there any documents clearly mentioned for each metrcis and what it states???

**Comment by adamraine** [comment]
Dom content loaded is not an official Lighthouse metric. It can be seen in the JSON at `lhr.audits['metrics'].details.items[0].observedDomContentLoaded` although this value will be unthrottled with the default Lighthouse throttling settings.
