### ISSUE TITLE
Lighthouse with headless Chrome failed on EC2 for homedepot

### ISSUE THREAD

**Issue by jethrolam** [GoogleChrome/lighthouse#15409]
On AWS EC2, we failed to run Lighthouse with headless Chrome for `www.homedepot.com`.  This is the command:

    lighthouse https://www.homedepot.com/ --output=json --output-path output.json --chrome-flags="--headless --no-sandbox --disable-gpu --disable-dev-shm-usage --no-first-run" --only-audits=first-contentful-paint --max-wait-for-load=30000

with the following error:

      LH:NavigationRunner:error Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403) https://www.homedepot.com/

Can we conclude that `www.homedepot.com` blocks Lighthouse on AWS EC2?

Notes:
- On the same EC2, we can `curl https://www.homedepot.com` and get HTTP200 successfully
- On the same EC2, we can execute the same lighthouse command on other sites (like amazon.com) and it works
- On my laptop and home network, we can execute exact same lighthouse command and it works
- Per [https://support.speedcurve.com/docs/troubleshooting-lighthouse#:~:text=A%20common%20cause%20of%20failures,Lighthouse%22%20user%2Dagent%20string.](https://support.speedcurve.com/docs/troubleshooting-lighthouse#:~:text=A%20common%20cause%20of%20failures,Lighthouse%22%20user%2Dagent%20string.), we tried adding `--user-agent="Chrome-Lighthouse"` in chrome-flags, but still failed

**Comment by adamraine** [comment]
> Can we conclude that www.homedepot.com blocks Lighthouse on AWS EC2?

This is the only page which returned a 403 error when Lighthouse tries to connect so perhaps it was a combination of EC2+headless that tricked the page into blocking Lighthouse. Unfortunately I can only speculate as to why this is happening since I'm not the site owner.

Perhaps you could try using `--headless=new` instead of `--headless`?
