### ISSUE TITLE
Extension Error: Cannot access contents of the page. Extension manifest mu...

### ISSUE THREAD

**Issue by husinbetawi** [GoogleChrome/lighthouse#1540]
**Lighthouse Version**: 1.4.1
**Chrome Version**: 55.0.2883.87
**URL**: blob:chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/b7fd787e-e559-429f-b69b-41d3447be6fa

**Comment by wardpeet** [comment]
closing in favor of #1863
