### ISSUE TITLE
[question] Date.now() for old browsers

### ISSUE THREAD

**Issue by alvaropinot** [GoogleChrome/lighthouse#1541]
What should be the "fix" for `Date.now()` presence if you have some piece of code that is actually trying to use `performance.now()` but will use `Dante.now()` as a fallback for old browsers?

BTW this is happening inside some code that its outside my control like for example some paper elements from polymer.

Thank you in advance.

**Comment by ebidel** [comment]
A polyfill fallback is a legitimate usage of `Date.now()`. 

This is one of the reasons we moved that audit to "Fancier stuff" and do not include it in the report score. It's a suggestion/recommendation of something to check out. But in some cases, the code is not under your control. I have a similar thing going on over on https://www.chromestatus.com/features (uses polymer).

**Comment by alvaropinot** [comment]
Thank you @ebidel, maybe there should be a way of marking things as skippable or so.

Closing this.
