### ISSUE TITLE
webpagetest integration : how to ?

### ISSUE THREAD

**Issue by abarre** [GoogleChrome/lighthouse#1542]
I see in the **readme** a section describing that `lighthouse` can be integrated with Webpagetest as a trace processor.

> Lighthouse can be used to analyze trace and performance data collected from other tools (like WebPageTest and ChromeDriver). The traces and performanceLog artifact items can be provided using a string for the absolute path on disk.

However, I can't find on this repo or somewhere else on the web any explanations on how it's possible.

Could you share how we can generate the **trace** and **performance data** that are consumed by lighthouse in webpagetest ?

I think that one of the following option should be checked : 
<img width="695" alt="capture d ecran 2017-01-26 a 10 01 52" src="https://cloud.githubusercontent.com/assets/928701/22325474/88ea7614-e3ae-11e6-817b-fb69c3236b9e.png">

**Comment by patrickhulce** [comment]
can record Lighthouse reports with WPT runs now, no longer necessary
