### ISSUE TITLE
`layout-shift-elements` max out at 5 elements

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#15423]
@rviscomi pointed this out today.

We only show the top 5 LS elements in this audit, but there could be more. The display value misleads the user into thinking that these are the *only* 5 layout shift elements.

![Screenshot 2023-08-29 at 4 18 21 PM](https://github.com/GoogleChrome/lighthouse/assets/6752989/6b89e5d6-eca6-40cb-85ca-f76f00f11b34)

We should probably change this message to count *all* LS elements which likely means collecting all LS elements in `TraceElements` and performing the slicing on the audit side.

Alternatives:
- Change message to "Top 5 elements found" or similar
- Remove the 5 element limit entirely and show everything

**Comment by connorjclark** [comment]
We can also show a 6th aggregate table item, that covers all the rest.

We could collect more than 5, but on the gatherer side we may want to modify the loop that calls `session.sendCommand('Runtime.callFunctionOn', ...` to run in parallel. The overhead of issuing commands in series may catch up to us.

**Comment by adamraine** [comment]
> We can also show a 6th aggregate table item, that covers all the rest.

I think we are going to continue with this idea.

**Comment by adamraine** [comment]
Also TODO: Update description to mention these shifts come from all windows not just the maximum CLS window
