### ISSUE TITLE
Chrome bug mp3 download on localhost not working anymore

### ISSUE THREAD

**Issue by remco-pc** [GoogleChrome/lighthouse#15441]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

http://admin.workandtravel.world

### What happened?

my music player 
```html
<audio data-mtime="1694033713.87" crossorigin="anonymous" autoplay="" controls=""><source data-mtime="1694033713.87" src="https://api.workandtravel.local/FileSystem/?url=%2FApplication%2FMount%2FAudio%2Frem_like_8.mp3&amp;key=..." type="audio/mp3"></audio>
```
where local is a local domain on my windows machine targeting a docker container with apache2 and php8.2 which handles the backend. it plays perfectly in the browser, but downloading (I need to sync between systems and users (www-data) is not working anymore.
The last good known version where it was working was: 116.0.5845.179, not anymore in116.0.5845.180.
The remote download is still downloading. could you please fix this ?

### What did you expect?

No check your internet connection

### What have you tried?

these things should be tested and the .local domain should be threated the same as the .world domain

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

v11.0.0

### Chrome Version

116.0.5845.180

### OS

Debian 11

**Comment by connorjclark** [comment]
This is not the place to report Chrome bugs.

https://bugs.chromium.org/p/chromium/issues/list

**Comment by remco-pc** [comment]
sorry what a maze
