### ISSUE TITLE
Attribute inline CSS stylesheets to the appropriate HTML or JS file

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1544]
We have a few CSS audits that report an "inline" attribution when a violation is within a `<style>` tag. An improvement would be to properly attribute these styles to the parent document or JS file that injected them.

**Comment by patrickhulce** [comment]
@ebidel is there a particular reason it's broken out from #1517?

**Comment by ebidel** [comment]
I thought #1517 was your meta bug. It might be useful to track this separately since inline styles spans a few different audits types. Not just the byte-efficiency ones. 

Unless you plan to add that stuff to the no-old-flexbox audit?

**Comment by patrickhulce** [comment]
No good point on cross-cutting concerns just wondering! I guess images are only really used in the efficiency audits for now

**Comment by paulirish** [comment]
Additionally the estimate for bytes used is wildly incorrect.

**Comment by brendankenny** [comment]
closing in favor of #5626 because that has a more specific suggestion for a path forward.
