### ISSUE TITLE
bug - cli: Cannot destructure property 'traceEvents'

### ISSUE THREAD

**Issue by schalkneethling** [GoogleChrome/lighthouse#15450]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://pixalot.co.za

### What happened?

I ran the following command using Lighthouse CLI:

```bash
npx lighthouse https://pixalot.co.za --only-categories accessibility --output-path accessibility.html --chrome-flags="--headless" --save-assets
```

### What did you expect?

The run completes, a report is generated, and relevant assets are written to disk.

### What have you tried?

When executing the command without `--save-assets`, everything works as expected.

### How were you running Lighthouse?

CLI

### Lighthouse Version

lighthouse@11.1.0

### Chrome Version

Version 116.0.5845.187 (Official Build) (arm64)

### Node Version

v20.3.0

### OS

macOS Ventura 13.5.2 (22G91)

### Relevant log output

```shell
This resulted in the following error:


LH:ChromeLauncher Killing Chrome instance 91892 +5ms
Runtime error encountered: Cannot destructure property 'traceEvents' of 'traceData' as it is undefined.
TypeError: Cannot destructure property 'traceEvents' of 'traceData' as it is undefined.
    at traceJsonGenerator (file:///Users/mi-shn001/.npm/_npx/0f94ee7615faf582/node_modules/lighthouse/core/lib/asset-saver.js:355:10)
    at traceJsonGenerator.next (<anonymous>)
    at Async-from-Sync Iterator.next (<anonymous>)
    at pumpToNode (node:internal/streams/pipeline:133:22)
    at pipelineImpl (node:internal/streams/pipeline:373:9)
    at node:stream/promises:31:5
    at new Promise (<anonymous>)
    at Object.pipeline (node:stream/promises:20:10)
    at saveTrace (file:///Users/mi-shn001/.npm/_npx/0f94ee7615faf582/node_modules/lighthouse/core/lib/asset-saver.js:380:26)
    at file:///Users/mi-shn001/.npm/_npx/0f94ee7615faf582/node_modules/lighthouse/core/lib/asset-saver.js:429:11
```
```

**Comment by adamraine** [comment]
Thanks, I can reproduce. There is no trace because you only run the accessibility category, but the asset saver isn't handling that case correctly.
