### ISSUE TITLE
Since v10 I can't use in firebase function. Pinning back to v9.6.8 fixes..   Got response code 400; body Failed to generate manifest from function source: Error [ERR_REQUIRE_ESM]: require() of ES Module \functions\node_modules\lighthouse\core\index.js from \functions\lib\index.js not supported. Instead change the require of \functions\node_modules\lighthouse\core\index.js in functions\lib\index.js to a dynamic import() which is available in all CommonJS modules.

### ISSUE THREAD

**Issue by paulmush1** [GoogleChrome/lighthouse#15457]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.example.com

### What happened?

Trying to build and run lighthouse in a firebase function but cannot require or import the library unless i pin back the version. 

### What did you expect?

to import the library 

### What have you tried?

pinning back the version

### How were you running Lighthouse?

node

### Lighthouse Version

> 10

### Chrome Version

n/a

### Node Version

18.17.1

### OS

windows

### Relevant log output

```shell
Got response code 400; body Failed to generate manifest from function source: Error [ERR_REQUIRE_ESM]: require() of ES Module \functions\node_modules\lighthouse\core\index.js from \functions\lib\index.js not supported. Instead change the require of \functions\node_modules\lighthouse\core\index.js in functions\lib\index.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by adamraine** [comment]
We switched to ES modules in version 10.0, so if you were importing Lighthouse via `require()` then this failure is expected. Have you tried using a dynamic `import()`?

**Comment by paulmush1** [comment]
ok thanks that fixes 👍
