### ISSUE TITLE
"Provided URL did not match initial navigation URL"

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#15487]
I've seen this error message pop up on any URL. It's not fatal so it's not breaking anyone, but it's definitely incorrect and could cause confusion.

![Screenshot 2023-09-20 at 8 49 40 AM](https://github.com/GoogleChrome/lighthouse/assets/6752989/c3a35b22-8559-46a5-84de-0e09c276d027)

cc @benschwarz

**Comment by adamraine** [comment]
This seems to be caused by https://github.com/GoogleChrome/lighthouse/pull/15055. Previously we would enable the network monitor after the `about:blank` jumps but now it gets enabled before. I think we have two options at this point:

- Update the navigation runner so the network monitor is disabled for the about blank jumps
- Remove this error message

**Comment by Harry-Robson** [comment]
Just found this as it was causing me some confusion so definitely an issue!

**Comment by samkingtwentytwo** [comment]
I've just build a batch lighthouse app for work and noticed this!

Is there any way around it until the navigation runner is updated? I merged your recent PR into my project but assuming you've only reduced the number of about:blank jumps and not updated when the network monitor starts?

Only issue for me is it mutates the performance scores so they're rendered unreliable.

Cheers Google Dev Sir!

**Comment by adamraine** [comment]
> Only issue for me is I think it mutates the performance scores. Do you think it would because of some sort of redirect? or?

I doubt https://github.com/GoogleChrome/lighthouse/pull/15397 would change your performance scores. It could just be normal variance or something like that. If/when #15397 lands and you notice a large and consistent difference in perf scores you can file a separate bug.

**Comment by samkingtwentytwo** [comment]
Hey Adam.

I fixed it by specifying custom throttling parameters like stated in the thread here:

https://github.com/GoogleChrome/lighthouse-ci/issues/430

Thanks!
