### ISSUE TITLE
filter irrelevant user timing marks

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1548]
Unclear what basis to do this on (hardcoded?), but google ads, for instance are injecting a bunch of measurements now:

![2017-01-24](https://cloud.githubusercontent.com/assets/316891/22355989/f8a9f004-e3e2-11e6-8c34-cd233fb218c2.png)

**Comment by paulirish** [comment]
We talked to the team behind this yesterday and it looks like this is the start of a few major players using usertiming. Everyone was on board with user-side filtering of these.. aka `str.startsWith('goog_')`

**Comment by rajsite** [comment]
We get a bunch of noise in lighthouse reports for angular marks and measures. Is the right idea to ask them to switch to goog_ or maybe request a lighthouse feature to only show marks and measures for a prefix we define (using the cli tooling):
![image](https://github.com/GoogleChrome/lighthouse/assets/1588923/e2440d23-dcb7-4e01-b6de-867e5cb78b0c)

Example marks and measures from Angular that I've seen soo far: Zone, Zone:ZoneAwarePromise, Zone:toString, Zone:util, Zone:legacy, Zone:timers, Zone:requestAnimationFrame, Zone:blocking, Zone:EventTarget, Zone:MutationObserver, Zone:IntersectionObserver, Zone:FileReader, Zone:on_property, Zone:customElements, Zone:XHR, Zone:geolocation, Zone:PromiseRejectionEvent, Zone:queueMicrotask
