### ISSUE TITLE
Lighthouse 'ERR_REQUIRE_ESM'

### ISSUE THREAD

**Issue by Forsh75** [GoogleChrome/lighthouse#15492]
Hi,

I'm trying to run a Lighthouse solution and I'm getting the attached error. I've spent ages looking but I can't find where the require() function is being used. Also the temp files C:\Users\JoeBloggs\AppData\Local\Temp\lighthouse-net-1848355f9489440d97a6b5d320a934d2.js don't seem to exist. I'm wondering if it's somehow related to the lighthouse logger. I've removed and reinstalled Lighthouse but I still get the error. I'm on version 11.1.0 of Lighthouse and Node 18.16.1. Any help would be greatly appreciated. 

Thanks.
[Lighthouse Error.txt](https://github.com/GoogleChrome/lighthouse/files/12725644/Lighthouse.Error.txt)

**Comment by adamraine** [comment]
Lighthouse uses ES modules since version 10.0. The file you mentioned appears to be using `require('lighthouse')` which is no longer possible because that is CommonJS syntax.
