### ISSUE TITLE
Warn about late, or missing, <meta charset> 

### ISSUE THREAD

**Issue by frankii91** [GoogleChrome/lighthouse#15498]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://i-meble.eu/pl/

### What happened?

Warn about late, or missing, <meta charset> Properly defines charset Error!

I can't diagnose and fix why I have this warning with the error Properly defines charset Error!, I have the right attachments in the right places, but I found one of the unanswered threads on the stack where one of the comments suggested linking the problem to the service worker. However, I still can't solve the problem. Maybe someone can help?

### What did you expect?

Solution.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

Generated by Lighthouse 11.0.0 | File an issue

**Comment by adamraine** [comment]
I can't reproduce this issue, the charset audit passes for me. What Chrome version are you using?

**Comment by frankii91** [comment]
Problem solved in another thread, problem with the lighthouse version in Chrome

**Comment by sebastianhaberey** [comment]
Facing the same problem - which other thread are you talking about, please?

**Comment by frankii91** [comment]
> Facing the same problem - which other thread are you talking about, please?

I can't find the thread but it's a problem in the Lighthouse version that uses Google Chrome.
