### ISSUE TITLE
Largest Contentful Paint 18.3 s and real time is 2.5-5 sec

### ISSUE THREAD

**Issue by frankii91** [GoogleChrome/lighthouse#15500]
Largest Contentful Paint 18.3 s and real time is 2.5-5 sec

Maybe someone can help me and diagnose the problem why the time shows so long, the page actually loads much faster.

I have the impression that either there is an error in the time counting or Ajaxes are added to the time that run in the background but do not affect the display, but I cannot deal with this problem.

![Zrzut ekranu 2023-09-29 222410](https://github.com/GoogleChrome/lighthouse/assets/14099566/636eb877-2c07-44f6-bfe5-b6767c020954)

Anyone help on this matter?

Maybe it's a problem related to what I see in the View Treemap - duplicate items?

![Zrzut ekranu 2023-09-29 222846](https://github.com/GoogleChrome/lighthouse/assets/14099566/e83ff07b-10b5-419f-816f-9207e18fc565)

link:
https://i-meble.eu/pl/meble-drewaniane-bukowe-retro/37570-komoda-drewniana-bukowa-kd439-retro-buk.html#/1504-wybdrewmax-buk_naturalny

**Comment by adamraine** [comment]
This is expected due to the default throttling settings: https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me

Lighthouse will load the page normally and then estimate performance metrics for a slower network connection and device afterwards.
