### ISSUE TITLE
`label-content-name-mismatch` is experimental it's still displayed

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#15519]
Transfer from https://github.com/GoogleChrome/web.dev/issues/10417 which makes a good point that we shouldn't display experimental audits in a11y. A good solution would be to hide this audit until it's non-experimental.

Do we have any additional motivation to display this audit?

cc @jazyan

**Comment by brgibson** [comment]
@adamraine, @jazyan, @brendankenny, @rviscomi what timeline should I communicate to my stakeholders for fixing this issue?

**Comment by brgibson** [comment]
Thanks all! 🙇

**Comment by joe-watkins** [comment]
I've dropped a question with the Axe team to see when asdf might come out of experimental. 

Could Lighthouse users have an option to run Experimental rules if they wanted in the meantime?

https://github.com/dequelabs/axe-core/issues/4324
