### ISSUE TITLE
PSI Test Results Yield Red Exclamation Mark Under Performance

### ISSUE THREAD

**Issue by Generosus** [GoogleChrome/lighthouse#15562]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.omniaaerospace.com

### What happened?

Approximately three days ago (i.e., 10/20/2023), every time we run PSI, we get a [red exclamation mark under Performance](https://pagespeed.web.dev/analysis/https-www-omniaaerospace-com/8oal0ib94u?form_factor=mobile) with the following message under Speed Index:

**Error! Chrome didn't collect any screenshots during the page load. Please make sure there is content visible on the page, and then try re-running Lighthouse. (NO_SCREENSHOTS)**

Details: https://pagespeed.web.dev/analysis/https-www-omniaaerospace-com/8oal0ib94u?form_factor=mobile

When we run our speed tests with GTMetrix, Pingdom, and WebPageTest, we have no issues (i.e., screenshots are displaying, etc.). Issue is only happening with PSI and Lighthouse.

No a biggie for us since PSI and Lighthouse seem to be the only Performance testers exhibiting this issue so, most likely, there's a bug with PSI and/or Lighthouse.

Help or feedback appreciated.

Thank you!

### What did you expect?

Performance test results and a score.

### What have you tried?

As part of our troubleshooting, we disabled all of our plugins and Cloudflare, but are still getting the same results (i.e., exclamation mark). We also contacted our host (SiteGround) and this is what they said:

```
I created a backup of the database and tried disabling plugins (I did not deactivate the theme), but the same behavior continued. Then, I noticed the following error that started appearing in the tool:

We failed to connect to Google servers, please try later

This error occurs when we have reached the limit for such tests via the Google servers. Please, consider allowing 24-48 hours and perform tests afterward - it should be working as expected then.
```

We waited over 72 hours before performing another PSI test, but the problem continues.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

11.0.0 

### Chrome Version

Version 118.0.5993.89 (Official Build) (64-bit)

### Node Version

No idea

### OS

Windows 10

**Comment by adamraine** [comment]
#15556
