### ISSUE TITLE
`NO_SCREENSHOTS` Performance (Speed Index) Error! in Chromium 118.x

### ISSUE THREAD

**Issue by l00sed** [GoogleChrome/lighthouse#15563]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://insights.sei.cmu.edu/blog/

### What happened?

This URL typically reports a high performance score. I ran a Lighthouse report on Chrome v117 and was able to get a decent performance score. However, running the report on Chrome v118 shows the `NO_SCREENSHOTS` error:
![image](https://github.com/GoogleChrome/lighthouse/assets/23065167/5c2a9ae8-aa00-4256-baee-2fc9e31aaeaa)

### What did you expect?

* A high performance metric and no error
* Screenshots and speed index metric

### What have you tried?

I tried running the report using the Firefox extension, but received the same results. Then, I attempted to run a report on another laptop and it worked. This laptop had an older version of Chrome (v117). I updated Chrome on this laptop to v118 and re-ran the report. This results in the error again. So, I'm thinking this is a new issue.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

11.0.0

### Chrome Version

118.0.5993.96

### Node Version

n/a

### OS

MacOS 14.0

### Relevant log output

```shell
Chrome didn't collect any screenshots during the page load. Please make sure there is content visible on the page, and then try re-running Lighthouse. (NO_SCREENSHOTS)
```

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/15460#issuecomment-1775760096

**Comment by l00sed** [comment]
Sorry I missed that, thanks.
