### ISSUE TITLE
Trigerring a navigation via user interaction google lighthouse

### ISSUE THREAD

**Issue by iamsethi** [GoogleChrome/lighthouse#15578]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

Company Internal Web Application

### What happened?

Following this [doc](https://github.com/GoogleChrome/lighthouse/blob/main/docs/user-flows.md#navigations-in-the-nodejs-api) to analyze and report on the entire page lifecycle via "user flows".

If i use below code in my application in navigating from one page to another then i get error. -

_LighthouseError [LHError]: NO_FCP at Timeout. (/Users/xxxx/node_modules/lighthouse/lighthouse-core/gather/driver/wait-for-condition.js:78:14) at listOnTimeout (node:internal/timers:573:17) at processTimers (node:internal/timers:514:7) { code: 'NO_FCP', friendlyMessage: 'The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)', lhrRuntimeError: true }_

```
// Interaction-initiated navigation via a callback function
   await flow.navigate(async () => {
     await page.click('a.link');
   });
```
If i refresh the page after navigating to 2nd page then i don't get any error in googlechrome-lighthouse

### What did you expect?

Google Lighthouse should not throw any error

### What have you tried?

If i refresh the page after navigating to 2nd page then i don't get any error in googlechrome-lighthouse

### How were you running Lighthouse?

node

### Lighthouse Version

9.6.8

### Chrome Version

118.0.5

### Node Version

20.1.0

### OS

Mac

### Relevant log output

```shell
LighthouseError [LHError]: NO_FCP at Timeout. (/Users/xxxx/node_modules/lighthouse/lighthouse-core/gather/driver/wait-for-condition.js:78:14) at listOnTimeout (node:internal/timers:573:17) at processTimers (node:internal/timers:514:7) { code: 'NO_FCP', friendlyMessage: 'The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)', lhrRuntimeError: true }
```

**Comment by adamraine** [comment]
Are you trying to audit a soft navigation? If so that feature is not supported yet #14573.

If not, can you please provide more details on how to reproduce this error.

**Comment by iamsethi** [comment]
That's correct,i am trying to do soft navigation
