### ISSUE TITLE
Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404)

### ISSUE THREAD

**Issue by nsaurabh548** [GoogleChrome/lighthouse#15584]
I am unable to check the lighthouse score for my home page of my website. While checking the lighthouse score it is showing me this following error "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404)". The lighthouse score is showing perfectly fine on  my other pages of website but not on my home page.
![Screenshot 2023-10-31 000222](https://github.com/GoogleChrome/lighthouse/assets/81461448/93910fba-06c5-4df2-8df0-4e3213a8212e)

**Comment by adamraine** [comment]
The message tells you what is going on. Your page returns a 404 status code.
