### ISSUE TITLE
Unhandled Rejection. Reason: ProtocolError: Protocol error (Target.getTargetInfo): Not allowed

### ISSUE THREAD

**Issue by adityadees** [GoogleChrome/lighthouse#15586]
This the docker config
```
RUN set -ex; \
  npm install npm@9.8.1 -g

RUN set -ex; \
  npm install -g laravel-echo-server lighthouse puppeteer@12.0.1; \
  npm cache clean --force
```

when I'm trying to run this
```
lighthouse  https://example.com/ --chrome-flags="--headless=new --no-sandbox --disable-gpu --disable-dev-shm-usage"  --output html --output json --output-path /var/www/html/path/test.html --preset=desktop
```

I got error issue
Unhandled Rejection. Reason: ProtocolError: Protocol error (Target.getTargetInfo): Not allowed

**Comment by adamraine** [comment]
I can't repro this, can you also provide:

- Chrome version
- Lighthouse version
- Operating system

**Comment by adityadees** [comment]
OS : Docker Alpine Linux
Lighthouse : 11.1.0
Chrome version : -

**Comment by adityadees** [comment]
<img width="1359" alt="image" src="https://github.com/GoogleChrome/lighthouse/assets/37553901/c11ea706-99ed-4b0e-a602-150fa33fa025">

working fine on my local
but not on ec2 server

<img width="1679" alt="image" src="https://github.com/GoogleChrome/lighthouse/assets/37553901/85a6a6b4-7775-4e12-bcb0-970edbc58fa9">

both running inside docker container

**Comment by adamraine** [comment]
That Chrome version is pretty old and not supported anymore. Please upgrade to the latest stable.
