### ISSUE TITLE
Enable JS Sampling in Lighthouse Timespan mode in DevTools

### ISSUE THREAD

**Issue by gilbertococchi** [GoogleChrome/lighthouse#15599]
Hello everyone, in the context of Developers troubleshooting Interactions for INP I believe it would be useful to enable "JS Samples" by default in Lighthouse in DevTools.

By doing so Developers would find all the Samples useful to identify what Script (1P or 3P) is actually responsible for a reproduced high INP scenario.

**Comment by alexnj** [comment]
https://github.com/GoogleChrome/lighthouse/pull/15542

**Comment by adamraine** [comment]
This can't be done in DevTools (yet), but something like this could work for the Node API:

```js
const flow = await startFlow(page);

// Enables JS samples for this flow step
await flow.startTimespan({additionalTraceCategories: 'disabled-by-default-v8.cpu_profiler'});
await page.click('button');
await flow.endTimespan();

const flowArtifacts = flow.createArtifactsJson();

// Get the trace for the first flow step
const trace = flowArtifacts.gatherSteps[0].artifacts.Trace;

fs.writeFileSync('trace.json', JSON.stringify(trace));
```
