### ISSUE TITLE
Running Lighthouse audit through CLI is not giving correct metrics and as I see on view map, login page is captured and metrics is collected but metrics should have captured from different page(specific) 

### ISSUE THREAD

**Issue by prashanthramanna** [GoogleChrome/lighthouse#15605]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://qatirehubonline.com

### What happened?

I tried running Lighthouse based on the steps mentioned here in the link - **https://github.com/GoogleChrome/lighthouse/blob/main/docs/authenticated-pages.md**

The set up is done as mentioned in the above link with the all the supporting softwares
installed node js v18.18, Lighthouse 11.0, chrome 119

1. open command prompt and navigate to folder where chrome-debug file is located
2. Run chrome-debug. This logs the debugging port of your Chrome instance.
3. Navigating to web application and log in.
4. In a separate terminal, I am run lighthouse with command using the port number from chrome-debug.
and the command is

**lighthouse <URL> --screenEmulation.disabled --throttling-method=provided --emulatedUserAgent--form-factor desktop --only-categories=performance --port <Port#>--view**

even though the session is logged in and above command uses the same session, still could see the page screen shot captured in view map of the report is showing the login page instead of specific page for which I need the results
also observed that the actual URL is getting replaced with denied URL at the top of the report

I am bit confused as the page screenshot and the URL seems to be irrelevant for me on seeing the lighthouse report

### What did you expect?

on running the Lighthouse audit through CLI should run and generate the report for different pages of my web application

### What have you tried?

tried the steps that I have mentioned above

tried to generate the lighthouse report by using the above command through CLI for this page
https://<domain>/customerconnect/account/
but URL captured in the report is something like this
https://<domain>/b2b/portal/login/access/denied/     which seems to be redirected to login page

Observed  **LH:CriConnection:warn Cannot create new tab; reusing open tab**. and 
 **LH:Navigation:error Provided URL did not match initial navigation URL +16s** on the CLI but that should not cause any error to run the lighthouse audit I hope

![Lighthousescreenshot1](https://github.com/GoogleChrome/lighthouse/assets/110041084/6a094207-53ed-410c-9791-016674ff2afc)

Not sure why the redirection is happening 
![image](https://github.com/GoogleChrome/lighthouse/assets/110041084/84566245-d4ca-4af5-afa0-3d68d1d26324)

### How were you running Lighthouse?

CLI

### Lighthouse Version

V 11.0

### Chrome Version

119

### Node Version

18.18

### OS

Windows

**Comment by prashanthramanna** [comment]
Can any one please let me know which this redirection issue occurring on running Lighthouse through CLI

**Comment by adamraine** [comment]
Can you please verify your Lighthouse version, the console log and screenshot you provided look like they were taken from Lighthouse v9.x or earlier.

You may also want to use the flag `--disable-storage-reset` as the documentation you linked indicates.
