### ISSUE TITLE
Using npm lighthouse with dynamic import

### ISSUE THREAD

**Issue by chaitanya1248** [GoogleChrome/lighthouse#15600]
**using lighthouse version 11.2.0**

Trying to import lighthouse using dynamic import in a typescript, node project.

Snippet:
Import('lighthouse').then(async () => {
const result = await lighthouse(url, flags, config);
// getting an error "this expression is not callable"
}

**Comment by chaitanya1248** [comment]
Even after adding param, it complains lighthouse is not callable. I had to explicitly use the default like:
Lighthouse.default(url, flags, config)
In order to make it work.

**Comment by adamraine** [comment]
Ah you're right, my bad. Forgot that's how node make you use the default param. Updated my comment.
