### ISSUE TITLE
@cypress-audit/lighthouse Plugin Opens a New Browser Tab When cy.lighthouse() Command Is Run

### ISSUE THREAD

**Issue by cihanaygunes** [GoogleChrome/lighthouse#15618]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://images.google.com/

### What happened?

I am working on implementing Cypress Lighthouse testing on my application with @cypress-audit/lighthouse plugin. 

I followed the steps in [here](https://mfrachet.github.io/cypress-audit/guides/lighthouse/installation.html#installing-the-dependency) for installation and configuration.

The issue that I am having is that when lighthouse command is run, it opens a new browser tab and lighthouse report gets generated by running against the second tab.

I am working on an application where 

1. I make a bunch of api calls to build a URL 
2. Then that URL redirects to an authentication page where I need to input credentials and pass few more steps
3. Then land on the page page where I run lighthouse command

I pass the first 2 steps in Cypress spec file. When it comes to step 3, lighthouse command is run, however it opens a new browser with above-mentioned built URL in step one, and it redirects back to authentication page. So, the lighthouse test runs against the authentication page but not my application page.

Cypress Main Tab
![Pasted Graphic 9](https://github.com/GoogleChrome/lighthouse/assets/74625769/3eec18db-e36c-4c4d-92a9-60d19f27f96d)

Second Tab
![Pasted Graphic 8](https://github.com/GoogleChrome/lighthouse/assets/74625769/fa4895bc-f0e7-45ea-bb7d-42f745afb9cb)

### What did you expect?

I expect lighthouse test to run within the same Cypress browser instead of running on a separate browser tab.

### How were you running Lighthouse?

Other

### Lighthouse Version

"@cypress-audit/lighthouse": "^1.4.2",

### Chrome Version

Chrome 119

### Node Version

v20.3.1

### OS

Mac

**Comment by adamraine** [comment]
We do not maintain the Cypress Lighthouse plugin. We support [auditing the page in an existing tab using puppeteer](https://github.com/GoogleChrome/lighthouse/blob/main/docs/puppeteer.md), but I do not know what this workflow would look like in Cypress.
