### ISSUE TITLE
`listbox` role is not recognized by axe

### ISSUE THREAD

**Issue by saraf-eb** [GoogleChrome/lighthouse#15630]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.eventbrite.com/checkout-external?eid=695245567207&alias=add-ons-event

### What happened?

When running Lighthouse with DevTools, the issue has been reported: "Values assigned to role="" are not valid ARIA roles" with a select element, specifically this element:
```
<select
                aria-invalid={hasError}
                aria-required={required}
                aria-labelledby={`${id}-label`}
                className="eds-field-styled__input eds-field-styled__select"
                data-automation={dataAutomation}
                role="listbox"
                value={selectedValue}
                disabled={disabled}
                id={id}
                name={name}
                onBlur={onBlur}
                onChange={onChange}
                onFocus={onFocus}
                {...extraAttrs}
            >
                {optionComponents}
            </select>
```
the role is not empty when I inspect the element. It's worth noting that we haven't made any modifications to the code. Furthermore, it was working perfectly fine before.

### What did you expect?

I expected to not find accessibility issues in this select, as no modifications have been made, and this has caused our accessibility score to decrease

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

11.1.0

### Chrome Version

Versión 119.0.6045.159

**Comment by adamraine** [comment]
Thanks, I can reproduce this. Even more interesting, I can't reproduce with just axe-core alone so this is probably an issue with Lighthouse somehow :/

**Comment by adamraine** [comment]
@saraf-eb this appears to be expected behavior as the select elements do not have have a `multiple` attribute or `size` attribute with value greater than 1

https://github.com/dequelabs/axe-core/issues/4256#issuecomment-1828332140
https://www.w3.org/TR/html-aria/#el-select-multiple-or-size-greater-1
