### ISSUE TITLE
Not working same as search console.

### ISSUE THREAD

**Issue by jy967845** [GoogleChrome/lighthouse#15642]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://visacent.com/consulate-general/egyptian-consulate-general-in-frankfurt-am-main-germany/

### What happened?

Search console showing 'Clickable elements too close together' issue under Mobile Usability section on this url. 
But when I checked in lighthouse to identify issue, there is not issue showing like this. Lighthouse should also show this issue on this url. 

### What did you expect?

If search console showing any error in website, lighthouse should show same issue/error. 
How can I identify which elements are creating issue?

### What have you tried?

I tried Chrome Lighthouse extension, as well Lighthouse on Developer Tool. 

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools

### Lighthouse Version

 11.0.0

**Comment by adamraine** [comment]
#12345 best captures our work to align our tap targets advice with current accessibility guidelines.
