### ISSUE TITLE
Are there any dangers in using Prefetch on a Shopify website for optimization?

### ISSUE THREAD

**Issue by remymedranda** [GoogleChrome/lighthouse#15652]
I have a website client that is using Shopify, and recently was told that a prefetch code used on his site would lead their site being slower, the seo being negatively impacted, and hurting quality rankings on paid traffic channels.  Also that the script was malicious. Can someone please help me look into these accusations for me because I don't believe one word of them. Our clients site has actually been doing really solid with performance so I just don't see this adding up.

![400769447_1499087717554104_5080653991685773838_n](https://github.com/GoogleChrome/lighthouse/assets/47356625/585f605c-d9c0-45ca-b10c-12d6cdb809c8)
![385557001_647332754236871_7173269589999077409_n (1)](https://github.com/GoogleChrome/lighthouse/assets/47356625/252d227d-5635-4f80-aa40-31451a8724d1)

Here's what's in our theme files:

 <head>
      {% unless template contains 'cart' %}
    {{ 'prefetch.js' | asset_url | script_tag }}
    {% endunless %} 

Here's a link to the code 
https://pastebin.com/wbcYi0BD

Is there anything malicious about this code that would harm the clients site?

**Comment by adamraine** [comment]
This isn't an issue with Lighthouse. We are aware of these types of scams but can't help you analyze your own code for you in this case.

**Comment by remymedranda** [comment]
Can you elaborate on the scam part?
