### ISSUE TITLE
Support traces where a FCP isn't found

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1567]
e.g. airhorner, our favorite contentless webapp.

Issue forked from https://github.com/GoogleChrome/lighthouse/pull/1549#discussion_r98312812

Will need some tweaks in `trace-of-tab.js`

**Comment by brendankenny** [comment]
We probably need a quick fix for master, as this is now a fatal error there. [`user-timings` doesn't have a `catch()`](https://github.com/GoogleChrome/lighthouse/blob/270f70bf2b7644b7f9103b3136aeb1ba8e012a87/lighthouse-core/audits/user-timings.js#L107), so if `requestTraceOfTab` throws then the LH run is cancelled.
