### ISSUE TITLE
Migrate TTI and EIL audits to using TraceOfTab

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1568]
and off their homegrown filter of trace events. Will require being able to identify top level slices ourselves.

**Comment by paulirish** [comment]
Also `getNavigationStartEvt` in pwmetrics-events.js could migrate onto the computed artifact


fwiw i've started the migration off traceviewer in this branch: [rmtraceviewer](https://github.com/GoogleChrome/lighthouse/tree/rmtraceviewer). it's incomplete.

**Comment by brendankenny** [comment]
fixed in #1858, #2347, etc etc
