### ISSUE TITLE
The PSI (PageSpeed Insights) Lighthouse score differs significantly from the Chrome Lighthouse DevTool score

### ISSUE THREAD

**Issue by suraj-sundariya** [GoogleChrome/lighthouse#15699]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.makemytrip.com/

### What happened?

The PSI Lighthouse score shows a significant difference compared to the Chrome Lighthouse DevTool score. Despite trying various iterations, the results remain same.

For instance, in PSI, the PWA score is approximately 54, while in Chrome DevTool, using the same Moto G Power device and 3G slow network configuration, the score is 91.

The PSI lighthouse scores for FCP and LCP are around 3.5 seconds, even though the server responds in just 600-700 milliseconds. I'm struggling to understand the root cause of this issue.
<img width="981" alt="Screenshot 2023-12-17 at 11 28 33 PM" src="https://github.com/GoogleChrome/lighthouse/assets/18225927/2d0ff9ad-ad02-42f9-8f63-94bd5db457d9">

### What did you expect?

<img width="1711" alt="Screenshot 2023-12-17 at 11 33 13 PM" src="https://github.com/GoogleChrome/lighthouse/assets/18225927/7de5c71b-597f-4abe-b465-5221db5ac41a">

### What have you tried?

I have tried running it multiple time in multiple devices. 

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools, WebPageTest

### Lighthouse Version

11.2.0

### Chrome Version

120.0

**Comment by suraj-sundariya** [comment]
Hey @brendankenny, it's been 2 days since I reported this issue, and I haven't seen any progress. Could you please provide an update?

I also have another question. Since PSI opens a headless browser to measure these metrics using Lighthouse, does it include the time spent invoking the headless browser and opening the site on that particular device in its measurements?.

**Comment by adamraine** [comment]
Please see #6708. This could also be just general [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md?rgh-link-date=2023-12-17T18%3A23%3A22Z) since I am getting reports like [this](https://googlechrome.github.io/lighthouse/viewer/?gist=e1f72c344d205f983248f82cd1de274e) locally.

> I also have another question. Since PSI opens a headless browser to measure these metrics using Lighthouse, does it include the time spent invoking the headless browser and opening the site on that particular device in its measurements?.

No. Lighthouse just uses the timings for loading the page.
