### ISSUE TITLE
Page Speed Insights auto triggers mouseover/scroll events?

### ISSUE THREAD

**Issue by JaJuMa** [GoogleChrome/lighthouse#15696]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://hyva.extension.jajuma.de/test

### What happened?

While checking a clients Magento store using Page Speed Insights we run into following issue:  

On this site we have two 3rd party scripts that cause a huge TBT.  
To avoid this TBT we delay these scripts until user interaction using this pattern:  

```
(events => {
  const loadMyLibrary = () => {
    events.forEach(type => window.removeEventListener(type, loadMyLibrary))
    // Load the library programatically here
  };
  events.forEach(type => window.addEventListener(type, loadMyLibrary, {once: true, passive: true}))
})(['touchstart', 'mouseover', 'wheel', 'scroll', 'keydown'])
```

This works fine on category pages as well as product detail page and also on other sites.  
However, on Homepage the huge TBT is still reported by Page Speed Insights due to these 2 scripts being loaded.  
(Somewhat randomly, every other test run shows the TBT to be ok and these 2 scripts are not loaded.)  

While investigating this issue, we run Page Speed Insights against this test site [https://hyva.extension.jajuma.de/test](https://hyva.extension.jajuma.de/test) 
that sends events to [here](https://webhook.site/#!/701e38ae-8b2b-4c1f-91db-759d89ceae9b/bc60c25f-7df0-43ab-aa44-d1424c5b3daa/1)
By this we found Page Speed auto-triggers a `mouseover` (and/or `scroll`?) event (maybe depending on http headers?)  

Normally this event is not doing anything as it is fired before HTML was parsed and event listeners are added by browser.
-> Defer 3rd party scripts as with snippet above works fine  

But in our case, we generate the CSS for each page on page load and inline all CSS.  
Effectively removing any render-blocking resources by inlineing all CSS  speeds up page rendering enough to make the event listener in above snippet to catch the `mouseover`/`scroll` event that is auto-triggered by Page Speed.  
-> Defer 3rd party scripts as with snippet above does not work anymore

This described behavior only happens in Page Speed Insights.
When using normal Browser Dev Tools or Lighthouse in Chrome, issue does not happen as there are no auto-triggered events.

(Note: There seem to be some more conditions such as DOM size to fully reproduce this. But leaving them out here to not over-complicate and focus on main issue)

### What did you expect?

1. As we understand, Page Speed Insights in general measures performance for a first load without user interaction  
(with some exceptions as for bfcache test).   
Maybe someone can share some insights about the purpose of these auto-triggered events for better understanding?

2. From a lab test tool, we would expect results as close as possible to the real-user experience with a normal browser.  
This seems to be not the case here?

3. We would also expect consistent test conditions and results, but with scenario above the time when these events are auto-triggered vary a lot and we are facing highly random results  

4. Any ideas on how to deal with this issue would be highly appreciated.  
As of now we found a simple workaround would be to add a small delay in above code snippet.   
However, this does not feel right as it would be a change only to satisfy Page Speed Insights, but not help the real user in any way...

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

11.0.0

### Chrome Version

HeadlessChromium 119.0.6045.199

**Comment by adamraine** [comment]
I was able to reproduce with this page:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin: 0;">
  <h1 style="height: 100vh; margin: 0">Change me on event</h1>
  <form style="margin-top: 100px;">
    <input/>
    <button>Button</button>
  </form>
  <script>
    function changeContent(e) {
      document.body.style.backgroundColor = 'red';
      console.log(e);
    }
    
    for (const type of ['touchstart', 'mouseover', 'wheel', 'scroll', 'keydown']) {
      window.addEventListener(type, changeContent, {once: true, passive: true})
    }
  </script>
</body>
</html>
```

The `scroll` event is triggered by Lighthouse in the tap targets gatherer [here](https://github.com/GoogleChrome/lighthouse/blob/8b119b143413bc3d3ea0384ec2f180f5a1f9f7a2/core/gather/gatherers/seo/tap-targets.js#L153). This shouldn't affect the audit results in PSI because the scroll happens after Lighthouse stops listening for network requests. However, there are implications for user flows which are discussed in #14336.

That being said, your page is extremely sensitive to user interactions so it's not surprising that this event listener gets triggered in passing. I would still expect many real users to trigger this condition early in the page lifecycle.
