### ISSUE TITLE
Lighthouse ERROR: net::ERR_TIMED_OUT)

### ISSUE THREAD

**Issue by SushilAarav** [GoogleChrome/lighthouse#15698]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.aaravinfotech.com

### What happened?

Diagnose results not showing
![Lighthouse issue](https://github.com/GoogleChrome/lighthouse/assets/153897210/d805c0d7-260c-4aef-89af-6d0fd7d5f90a)

### What did you expect?

A normal report was expected with each metrics which was showing a month before.

### What have you tried?

Tried different versions of URL, from different IPs and devices.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

11.0.0

### Chrome Version

120.0

### OS

Windows 10

### Relevant log output

```shell
Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_TIMED_OUT)
```

**Comment by SushilAarav** [comment]
Hello?
Is there any solution?

**Comment by adamraine** [comment]
I can't reproduce this, pagspeed shows a report for me: https://pagespeed.web.dev/analysis/https-www-aaravinfotech-com/fryig5wzgq?form_factor=mobile

Are you still seeing this?

**Comment by SushilAarav** [comment]
Hi Adam, thanks for your reply. The link shared by you works. But when we do it, it gives the above error. We have tried different browsers and IPs. Can you tell why this is happening with us? Will this affect our business website negatively?

**Comment by adamraine** [comment]
Can you please share a report where this is happening via the "Copy Link" button in the top right?

> Will this affect our business website negatively?

No. Pagespeed insight results *are not* used for search engine ranking.

**Comment by SushilAarav** [comment]
Hi Adam,

https://pagespeed.web.dev/analysis/https-www-aaravinfotech-com/mhpyck6aky?form_factor=mobile
https://pagespeed.web.dev/analysis/https-www-aaravinfotech-com/rzpo9tcy09?form_factor=mobile

Realtime data is showing but lab data(diagnostic) is showing error"Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_TIMED_OUT)"

Thank you for your response. Really appreciate it. We just want to find out why this is happening recently and solve any issues related to it.

**Comment by adamraine** [comment]
Looks like my PSI runs are using the North America server and yours are using the Asia server. Perhaps the page is inaccessible from the Asia server. Will need to investigate though.

**Comment by adamraine** [comment]
Using a VPN I was able to confirm that PSI in the Asia region gets this error.

**Comment by SushilAarav** [comment]
May we know why this is happening, is there anything we can do to fix this?

**Comment by adamraine** [comment]
> May we know why this is happening, is there anything we can do to fix this?

It looks like the site is not responding from the location PSI is testing from. Unfortunately, we can't provide much help beyond that.
