### ISSUE TITLE
Viewer: resize lh_logo_bg.png

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1569]
Currently lh_logo_bg.png is 707x707 and it's being resized to 140x140. Either we resize that, or switch to an SVG.

**Comment by ebidel** [comment]
I'm not too worried about perf on the viewer. The image is 26kb and the total transfer right now is 151kb. Most of that is the bundled js.

**Comment by XhmikosR** [comment]
Agreed, but still, it's redundant. Like 20KB redundant...

**Comment by brendankenny** [comment]
Closing in favor of #2591 tracking issue
