### ISSUE TITLE
INP score Issue in Lighthouse Time span mode for mobile device 

### ISSUE THREAD

**Issue by YogeshwaranR** [GoogleChrome/lighthouse#15700]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://about.google/intl/ALL_sg/products/

### What happened?

I am testing INP for mobile devices. I am using Lighthouse timespan mode with mobile device option, In this page, I am checking INP for expand and collapse of "For developers" section. That INP score is very high for mobile device compared with desktop mode.
![mobile](https://github.com/GoogleChrome/lighthouse/assets/12558929/36af8a6f-47c4-462c-bcaa-cbe5d61682da)
![Destop](https://github.com/GoogleChrome/lighthouse/assets/12558929/a7c1bb30-8287-480d-ad2e-155d3a501ed9)
 

### What did you expect?

Mobile INP Score should not this much high. I have tried Lighthouse Timespan with mobile option in various sites. It is always high compared with desktop. 

### What have you tried?

I have tested this with performance profiling for same scenario.
![performace-profiling](https://github.com/GoogleChrome/lighthouse/assets/12558929/4ea8d5d0-e935-4025-8bcc-f80c716b209c)

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

11.2.0

### Chrome Version

 120.0.6099.72

### OS

Windows

**Comment by adamraine** [comment]
Lighthouse actively [throttles](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md?rgh-link-date=2023-12-18T06%3A15%3A57Z) the page using testing timespan mode on a mobile device. For this reason, the INP value in Lighthouse will not always match the interaction delay produced with the performance panel.
