### ISSUE TITLE
Viewer: "Save as" doesn't work with Firefox

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1574]
Using Firefox 52b1, Export -> Save as html or json does nothing and no error is logged in console.

Using Chrome 56, it works fine.

**Comment by XhmikosR** [comment]
@ebidel: any ideas why this fails?

**Comment by ebidel** [comment]
Not sure. For me, it opens in the reader thing in 51:

<img width="1192" alt="screen shot 2017-02-02 at 12 42 27 pm" src="https://cloud.githubusercontent.com/assets/238208/22567541/3475443c-e945-11e6-8279-7488a6c59f97.png">

**Comment by XhmikosR** [comment]
Does Save As HTML / json work though? For me it doesn't work with the latest master.

**Comment by ebidel** [comment]
Doesn't look like it. I'm not sure what the reader thing is or how to turn it off.

**Comment by XhmikosR** [comment]
I don't have the reader open here so I can't help you with that. :/

**Comment by XhmikosR** [comment]
@ebidel: You can set `reader.parse-on-load.enabled` `false` on `about:config` to disable it.
