### ISSUE TITLE
Accessibility in https://pagespeed.web.dev/ showing exclamation mark

### ISSUE THREAD

**Issue by clouddevloper** [GoogleChrome/lighthouse#15750]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.edureka.co/devops-certification-training

### What happened?

While checking page speed for one of my pages it showing exclamation mark. It is showing only for desktop. What can be the reason for this?
![speed](https://github.com/GoogleChrome/lighthouse/assets/87369308/26ea13e2-b2c9-4e0a-ad76-d8dc9647026d)
![speed](https://github.com/GoogleChrome/lighthouse/assets/87369308/c3770cc1-747f-47ac-b854-030c777ffb54)

### What did you expect?

It was shwing 100 in the morning.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

11.2.0

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/15619

**Comment by clouddevloper** [comment]
@adamraine I am still not able to understand how to resolve this. It will be relally helpful if you can explain.

**Comment by adamraine** [comment]
This is a duplicate issue of https://github.com/GoogleChrome/lighthouse/issues/15619 which has not been fixed yet. There is a bug in an upstream dependency that needs to be fixed first.
