### ISSUE TITLE
"Links are not crawlable" should ignore if `aria-disabled="true"`

### ISSUE THREAD

**Issue by coliff** [GoogleChrome/lighthouse#15759]
Running Lighthouse (11.4.0) on https://getbootstrap.com/docs/5.3/examples/cheatsheet/ displays 'links are not crawlable' on some disabled links which are intentionally not crawlable links.

It'd be good if the regex for this audit ignored any links with `aria-disabled="true"`

**Comment by paulirish** [comment]
@coliff do you have any resource that states that area-disabled links aren't crawled?  
I'm not an expert around this so I don't know myself..

**Comment by adamraine** [comment]
I asked @AVGP internally. `aria-disabled="true"` links should still be crawled and therefore this is WAI.
