### ISSUE TITLE
performance.clearMeasures (and presumably performance.clearMarks) results in inconsistency between LH and other tools

### ISSUE THREAD

**Issue by andydavies** [GoogleChrome/lighthouse#15754]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://andydavies.github.io/agent-tests/usertiming/clearedmeasures.html

### What happened?

The page sets some User Timing marks and a measure, and then clears the measure after a delay

WebPageTest (https://www.webpagetest.org/result/240112_AiDcBH_827/), other tools don't report the measure as they're no longer in the Performance Timeline at the point WPT captures the data.

LH extracts the marks & measures from the Chrome trace and has no awareness of calls to `clearMarks` / `clearMeasures` so includes marks and measures that may have been removed

### What did you expect?

I'd expect LH to not include marks / measures that were removed but I can see the case for excluding them

The discrepancy does cause confusion (we have a SpeedCurve customer who raised this initially)

I'm OK if you want to close this as WAI but just wanted to document the issue for the next person who discovers this difference

### How were you running Lighthouse?

WebPageTest

### Lighthouse Version

11.4.0

**Comment by adamraine** [comment]
My initial thoughts are that this is WAI since we want the audit to document everything that happened. Performance panel in DevTools also appears to keep the performance timings visible.

Is there a use case for clearing the timings or was it just confusion as a result of differences with WPT?
