### ISSUE TITLE
SyntaxError: The "start lh:runner:gather" performance mark has not been set

### ISSUE THREAD

**Issue by kundan8239** [GoogleChrome/lighthouse#15774]
I am currently encountering a similar issue like this #15379 with specific domains.
The domains in question are https://www.chocolatechipcookies.co.uk/ , https://ailes.ez37m.com/.
Lighthouse: "11.2.0"
Chrome version: "118.0.5993.70-1".

code : 
```
this.chrome = await chromeLauncher.launch({
  chromeFlags: [
    '--no-first-run',
    '--headless=new',
    // '--single-process',
    '--no-zygote',
    '--disable-gpu',
    '--no-sandbox',
    '--disable-dev-shm-usage',
  ],
});
logger.debug(`Launched chrome on port ${this.chrome.port} and pid ${this.chrome.pid} for ${target} - ${correlationId}`);

const lhrs = [];
let demoReport = null;
for (let i = 0; i < iterations; i++) {
  logger.debug(`Running ${i} scan for ${target} - ${correlationId}`);
  const options = {
    logLevel: 'error',
    output: 'html',
    maxWaitForLoad: 60000,
    // skipAudits: ['full-page-screenshot'],
    onlyCategories: [
      'accessibility',
      'best-practices',
      'performance',
      'pwa',
      'seo',
    ],
    port: this.chrome.port,
    hostname: '127.0.0.1',
  };
  if (device.toLowerCase() === CONSTANT.DESKTOP) {
    options['screenEmulation'] = CONSTANT.DESKTOP_CONFIG.DESKTOP_EMULATION_METRICS;
    options['formFactor'] = CONSTANT.DESKTOP;
    options['throttling'] = CONSTANT.DESKTOP_CONFIG.THROTTLING.DESKTOP_DENSE_4G;
    options['emulatedUserAgent'] = CONSTANT.DESKTOP_CONFIG.EMULATED_USER_AGENT;
  } else {
    device = CONSTANT.MOBILE;
  }
  let timerObj;
  const runnerResult = await Promise.race([
    new Promise((resolve, reject) => {
      timerObj = setTimeout(async () => {
        reject(new Error('Max execution time exceeded'));
      }, 300000);
    }),
    lighthouse(target, options),
  ]);
  timerObj && clearTimeout(timerObj);

  demoReport = runnerResult;
  lhrs.push(runnerResult.lhr);
}

if (demoReport.lhr && demoReport.lhr.environment) {
  logger.debug(`Environment of scan result for ${target} - ${correlationId} - LH:${demoReport.lhr.lighthouseVersion} - NUA:${demoReport.lhr.environment.networkUserAgent} - HUA:${demoReport.lhr.environment.hostUserAgent}`);
}

const { mainDocumentUrl, audits, categories: categoryResults } = generateAverageReport(lhrs);
```

Error:

![image-20240119-050305 (1)](https://github.com/GoogleChrome/lighthouse/assets/26499928/1234a9ca-a928-40b9-ac46-2b53958763f3)

Question: How to fix this ?

**Comment by adamraine** [comment]
When you put `lighthouse()` into a `Promise.race` it will continue running even if the timeout promise finishes before it. This can lead to a situation where the first loop iteration reaches your timeout condition and then calls `lighthouse()` again before the first one finishes.

There isn't a way to cancel a call to `lighthouse()`, but you can adjust the `maxWaitForLoad` parameter on you `options` object instead of using a custom timeout with `Promise.race`.

**Comment by kundan8239** [comment]
I am configuring the 'maxWaitForLoad' parameter with a value of 60000, which is set to be less than the 'setTimeout' duration of 300000. In this context, the assumption is that during each iteration, the Lighthouse call is expected to complete first. However, if, for any reason, the Lighthouse call does not complete within the specified timeframe, an 'Max execution time exceeded' error is thrown. This error is caught in the associated catch block, where I terminate all open Chrome instances.
`const killChrome = await chromeLauncher.killAll();`
