### ISSUE TITLE
Report: move all CSS to `head`

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1578]
Apart from it not being valid HTML, it's hard to debug it as the style tags now appear through the whole `body`.

If you don't want to move everything to `report.css`, maybe a build step could take care of this instead.

**Comment by ebidel** [comment]
Personally, I've never found much benefit to being valid HTML 😛 . Is there a benefit for making sure the report is 100% valid?

I hear you about debugging though. Having multiple places in the output HTML define the same `<style>` is frustrating and wasteful.

The irony of HTML is that the spec also defines `<style scoped>`, which makes `<style>` in `<body>` a thing. Stylesheets are similar. Chrome is even [working a fix](https://www.chromestatus.com/features/5696805480169472) to make stylesheets in body non-render blocking b/c so many people don't follow the `<head>` rule.

**Comment by XhmikosR** [comment]
The reason I believe is good to be HTML valid is because it's another good way to prevent issues (see my #1575).

I'm aware of `style scoped` but still I'm personally old school in this regard and I prefer to have all styles in `head`.

**Comment by XhmikosR** [comment]
I mean, ideally, you should have the report tested with vnu.jar to make sure such things don't happen again in the future.
