### ISSUE TITLE
LCP Element is not visible when the LH Audit gets started programatically

### ISSUE THREAD

**Issue by S3gillu** [GoogleChrome/lighthouse#15782]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.cars24.com/au/

### What happened?

I'm programmatically utilizing Lighthouse to conduct audits, leveraging a server located in Australia to extract the LH Audit report. Additionally, I'm adjusting the Network Throttling settings and Device Screen Size parameters as part of the testing process.

<img width="1177" alt="Screenshot 2024-01-25 at 4 11 07 PM" src="https://github.com/GoogleChrome/lighthouse/assets/31066063/3833f142-23d3-4960-b751-dde318e9a9bc">
<img width="1289" alt="Screenshot 2024-01-25 at 4 08 47 PM" src="https://github.com/GoogleChrome/lighthouse/assets/31066063/2fac2d67-e6b6-450a-b1a1-4f1b80289889">

<img width="1440" alt="Screenshot 2024-01-25 at 4 14 36 PM" src="https://github.com/GoogleChrome/lighthouse/assets/31066063/ffb7a149-f21d-4550-b782-5a7a5b8e42bd">

### What did you expect?

In LH v11.4, the response should ideally include the LCP element, but I've observed that it's intermittently missing for certain URLs. This inconsistency is quite random, as sometimes the LCP element is present and other times it's not. Notably, this issue wasn't encountered prior to LH version 11.0, where everything functioned smoothly.

### What have you tried?

I am encountering an issue with the latest version (v11.4) of LH (Lighthouse) when programmatically testing various public URLs for performance. Specifically, I've noticed that the Largest Contentful Paint (LCP) element is intermittently not being detected for certain URLs. This behavior appears to be random.

To validate this problem, I conducted LH audits for the affected URLs using the LH section of Chrome DevTools. Unfortunately, I encountered the same issue.

<img width="1440" alt="Screenshot 2024-01-25 at 4 14 36 PM" src="https://github.com/GoogleChrome/lighthouse/assets/31066063/d5118bfd-c51e-46a4-bd11-12a6257d6e37">

### How were you running Lighthouse?

node, Chrome DevTools, Other

### Lighthouse Version

11.4.0

### Chrome Version

 120.0.6099.224

### Node Version

v18.15.0

### OS

Linux and Mac

### Relevant log output

```shell
The LH report should contain the LCP Element visibly displayed.
```

**Comment by adamraine** [comment]
I can't repro on this site but we have seen this issue before and filed an upstream bug with chrome: https://github.com/GoogleChrome/lighthouse/issues/14908

Also, I think I got rate limited/banned when testing the site :/

**Comment by S3gillu** [comment]
Maybe too much request, but you can always use your local machine and run lighthouse in Dev tools to reproduce it (if needed). Any Idea on the resolution timeline? @adamraine

**Comment by adamraine** [comment]
The root cause is upstream in Chrome so unsure of a timeline.

FWIW I was running LH in DevTools and the site started blocking me.
