### ISSUE TITLE
Unable to connect to Chrome

### ISSUE THREAD

**Issue by xxlifestyle** [GoogleChrome/lighthouse#15804]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.example.com

### What happened?

Unable to connect to Chrome

### What did you expect?

launch lighthouse

### What have you tried?

`lighthouse google.com --chrome-flags=”--headless” ` - same error

chrome installed with this commands
```
sudo apt-get install libxss1 libappindicator1 libindicator7
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install google-chrome-stable_current_amd64.deb
```

### How were you running Lighthouse?

CLI, node

### Lighthouse Version

8.3.0 

### Chrome Version

121.0.6167.160

### Node Version

v18.14.2

### OS

Linux Debian

### Relevant log output

```shell
$ lighthouse http://www.example.com --chrome-flags="--headless=new --no-sandbox"
  LH:ChromeLauncher Waiting for browser. +0ms
  LH:ChromeLauncher Waiting for browser... +2ms
  LH:ChromeLauncher Waiting for browser..... +509ms
  LH:ChromeLauncher Waiting for browser.....✓ +3ms
  LH:config:warn IFrameElements gatherer requested, however no audit requires it. +914ms
  LH:config:warn FormElements gatherer requested, however no audit requires it. +0ms
  LH:status Connecting to browser +82ms
  LH:CriConnection:warn Cannot create new tab; reusing open tab. +10ms
  LH:status Disconnecting from browser... +4ms
  LH:CriConnection:error sendRawMessage() was called without an established connection. +1ms
  LH:GatherRunner disconnect:error sendRawMessage() was called without an established connection. +0ms
  LH:ChromeLauncher Killing Chrome instance 3916787 +1ms
Unable to connect to Chrome
```

**Comment by adamraine** [comment]
> Lighthouse Version
> 8.3.0

That is a very old version of Lighthouse, can you try with the latest version?

**Comment by dehghani-mehdi** [comment]
Same here, I'm using the latest version (`11.5.0`)

```
lighthouse https://google.com

LH:ChromeLauncher Waiting for browser. +0ms
LH:ChromeLauncher Waiting for browser... +4ms
LH:ChromeLauncher Waiting for browser..... +540ms
LH:ChromeLauncher Waiting for browser.....√ +155ms <--- stuck here
```
