### ISSUE TITLE
Report: refactor handelbar helpers into static methods

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1581]
This will make them easier to test.

**Comment by brendankenny** [comment]
It might make sense to pull them out of `report-generator.js` and into their own file as a "default set of handlebar helpers" module. Would make testing clearer, at least, as the helper tests are pretty distinct from tests of the exact output of the report generator.

Bonus points if issue fixer moves `lighthouse-core/test/report/report-test.js` to `lighthouse-core/test/report/report-generator.js` at the same time :)

**Comment by sendilkumarn** [comment]
I will take a shot on this.
