### ISSUE TITLE
a11y gatherer hangs on https://almanac.httparchive.org/en/2021/ecommerce

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#15824]
This results in a PROTOCOL_TIMEOUT:

```
node cli https://almanac.httparchive.org/en/2021/ecommerce --only-categories=accessibility
```

Did not happen in 10.0

I bisected to: https://github.com/GoogleChrome/lighthouse/issues/15216

cc @tunetheweb

**Comment by tunetheweb** [comment]
FYI I have ` "identical-links-same-purpose": "off",` in my config.

Will try it with `target-size` turned off too...

**Comment by adamraine** [comment]
I think we should upstream this bug to axe if we can. Even though the audit is hidden, we eventually want to use it and I think disabling it completely will lose value in HTTPA runs (ironic that this happens on https://almanac.httparchive.org/en/2021/ecommerce tho haha).

**Comment by tunetheweb** [comment]
FYI, I also saw problems with https://almanac.httparchive.org/en/2021/webassembly

Both have a lot of web mentions (which we render at the bottom of the page). Turning this functionality off (https://almanac.httparchive.org/en/2021/webassembly?nowebmentions) allowed the page to pass Lighthouse runs.

So either the DOM's got too large with those, or axe doesn't handle a page with a lot of similar things. A lot of them do have the same "View Source" link despite pointing to different sources which might fail the new `identical-links-same-purpose` ([docs](https://dequeuniversity.com/rules/axe/4.7/identical-links-same-purpose)) audit?

<img width="350" alt="image" src="https://github.com/GoogleChrome/lighthouse/assets/10931297/ba965fb4-553b-490b-bf3b-2e60c52f5626">

**Comment by adamraine** [comment]
https://github.com/dequelabs/axe-core/issues/4360

We can disable the `target-size` rule temporarily. If axe fixes this issue or we decide to elevate `target-size` to the report UI then we should re enable it.

**Comment by adamraine** [comment]
This should be fixed now.
