### ISSUE TITLE
driver.disconnect/Protocol JSON API error

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1583]
After #1543, theres a killing-Chrome race condition going on, typified by a [`Protocol JSON API error`](https://github.com/GoogleChrome/lighthouse/blob/270f70bf2b7644b7f9103b3136aeb1ba8e012a87/lighthouse-core/gather/connections/cri.js#L89) when failing with an error (e.g. https://github.com/GoogleChrome/lighthouse/issues/1567#issuecomment-276212737).

It looks like this is the normal [`GatherRunner.disposeDriver` call](https://github.com/GoogleChrome/lighthouse/blob/111a519585841178b74d47e4c8150ab3c34d7a9d/lighthouse-core/gather/gather-runner.js#L328), but then the `dispose` -> `driver.disconnect` -> `connection.disconnect` -> JSON command is slower than the first few audits executing, getting to a throwing audit, exception bubbling up, and `ChromeLauncher` killing the Chrome instance. By the time the `close/${this._pageId}` command goes through, there's no Chrome to talk to.

**Comment by ebidel** [comment]
Here's what I get when I test `localhost:8080` and my server hasn't been started (e.g. LH tests the error page)

```
  gather-runner disconnect:error Error: Protocol JSON API error (close/f065db0c-f3eb-43da-a242-208ae524f95e), status: 500
    at IncomingMessage.response.on._ (/Users/ericbidelman/projects/github/GoogleChrome/lighthouse/lighthouse-core/gather/connections/cri.js:89:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +33ms
Unable to load the page. Please verify the url you are trying to review.
```
