### ISSUE TITLE
Mobile test should also emulate having a `coarse` pointer device.

### ISSUE THREAD

**Issue by romainmenke** [GoogleChrome/lighthouse#15885]
Currently `@media (any-pointer: coarse) {}` is false when running a mobile test in Lighthouse.

This affects the scoring for things like tap target checks.

see : https://web.dev/articles/accessible-tap-targets

As noted in the article is best to ensure appropriate tab targets when the pointer device is possibly `coarse`. 

> Instead of simply testing for viewport dimensions, and then guessing that small dimensions are likely to be phones or tablets, which in turn use a touchscreen, there are now more robust ways to adapt your design based on actual device capabilities.

However when using that approach we still fail the lighthouse test because the styles behind such a media query are never applied during the test.

----------

This contrasts with manually setting a mobile device in dev tools:

<img width="1060" alt="Screenshot 2024-03-25 at 18 27 20" src="https://github.com/GoogleChrome/lighthouse/assets/11521496/f62a11eb-e599-4ed4-b54c-610e64dedff8">

**Comment by adamraine** [comment]
During a Lighthouse run with mobile emulation enabled, I am seeing `window.matchMedia('(any-pointer: coarse)').matches` return `true`. Can you provide an example page where you are seeing this issue?

**Comment by romainmenke** [comment]
You can test with this example :

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>

	<style>
		a {
			display: block;
			margin: 0;
			padding: 0;
		}

		@media (any-pointer: coarse) {
			body {
				background-color: green;
			}
		}

		@media (any-pointer: coarse) {
			a {
				margin: 50px;
			}
		}

		/* @media (width <= 600px) {
			a {
				margin: 50px;
			}
		} */
	</style>
</head>
<body>
	<a href="#1">One</a>
	<a href="#2">Two</a>
</body>
</html>
```

-----

I expect to see a green background and a lot of white space around each anchor.

Instead I see a white background and no white space.

I also see this notice:
> Tap targets are not sized appropriately 0% appropriately sized tap targets

**Comment by adamraine** [comment]
Ah I see. I can reproduce using DevTools but I'm not seeing the issue with Lighthouse CLI

**Comment by romainmenke** [comment]
Thank you for checking again!
Interesting that it does work as expected in Lighthouse CLI.

**Comment by adamraine** [comment]
I made a minimum repro and filed an upstream bug in chrome:
https://issues.chromium.org/u/1/issues/331757596

**Comment by romainmenke** [comment]
Thank you for taking the time to make the repro and filing the upstream bug 🙇 

It's fine to close this, I can track the upstream issue :)
