### ISSUE TITLE
Excessive style recalcs caused by CSS usage tracking

### ISSUE THREAD

**Issue by Achchheweb** [GoogleChrome/lighthouse#15890]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.anoblepurpose.com/

### What happened?

Hi i'have update lighthouse version from 11.5 to 11.7 in this version i'm facing issue regarding low speed and full-screenshot.
Speed decrease from 35-25 and also full page screenshot of website not showing properly 
My Site url:
https://www.anoblepurpose.com/

it properly working on 11.5 after i upgrade 11.7 them facing issue.
lighthouse v11.7 screenshot and speed
![image](https://github.com/GoogleChrome/lighthouse/assets/141727306/1f31395a-dd2e-44ce-933f-22c1ec403133)
![image](https://github.com/GoogleChrome/lighthouse/assets/141727306/9c73ef1c-8d9c-4ac7-9924-19981f6ffb20)

lighthouse 11.5
![image](https://github.com/GoogleChrome/lighthouse/assets/141727306/f15851e6-2fbb-4f14-aa1d-8f969cf4cf45)
![image](https://github.com/GoogleChrome/lighthouse/assets/141727306/ec246a5b-a3c8-46fc-93e5-b5131bf0376c)

how can i resolve this issue suggest me.

### What did you expect?

If i upgrade v11.5 to v11.7 then data should more details and taking full-page screenshot
![image](https://github.com/GoogleChrome/lighthouse/assets/141727306/27f05b0e-6acd-4094-824c-3baf82ecf216)

### What have you tried?

i just change with v11.7 to v11.5 then it work properly

### How were you running Lighthouse?

node

### Lighthouse Version

11.7

### Chrome Version

114.0

### Node Version

18.17

### OS

Ubuntu 20.0

### Relevant log output

```shell
Full page-screenshot and data should be optimized.
But score and screenshot not working properly.
```

**Comment by adamraine** [comment]
After investigation, there is a significant performance impact on the page if the `CSS.enable` is called *before* the navigation starts. This is the behavior that changed in https://github.com/GoogleChrome/lighthouse/pull/15865.

This trace calls `CSS.enable` before navigating, there are a significant number of style recalcs that affect page performance:
https://trace.cafe/t/5YOOKGSdbX

This trace calls `CSS.enable` *after* navigating:
https://trace.cafe/t/AKRGmaVZDD

**Comment by adamraine** [comment]
https://issues.chromium.org/u/1/issues/331570801

**Comment by adamraine** [comment]
From the upstream issue:

> This seems to be working as intended, since the instrumentation to track rule usage is quite involved.

Seems like CSS usage tracking has a significant performance overhead. Before https://github.com/GoogleChrome/lighthouse/pull/15865 we were deferring the CSS usage tracking until the end of the run. This prevented the performance overhead from affecting the actual page load, however it would only check what CSS was used at the end of the page load. So any styles that were temporarily used during the load would not get counted.

After https://github.com/GoogleChrome/lighthouse/pull/15865, temporarily used CSS rules are counted but this introduces the performance overhead visible in the reported site.
