### ISSUE TITLE
Was filing bug report when site crashed multiple before I could get the first report in

### ISSUE THREAD

**Issue by nism385** [GoogleChrome/lighthouse#15912]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fgithub.com%2F&strategy=desktop&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext

### What happened?

Was on the sign in page of git hub to log in when the page froze up. I received the "not responding" window. 

### What did you expect?

For the single browser window to stay froze as has been my probem. 

### What have you tried?

I have tried to close the browser, keep browser information clear such as cookies, cashe. 

### How were you running Lighthouse?

web.dev

### Lighthouse Version

F12

### Chrome Version

Version 123.0.2420.65 (Official build) (64-bit) Edge

### OS

Windows 10 32 bit

**Comment by adamraine** [comment]
The viewer link isn't freezing for me. The page can freeze for any number or reasons, I don't really see how this is an issue with Lighthouse.

**Comment by nism385** [comment]
did you read the report
