### ISSUE TITLE
Unexpected changes on main thread work from 11.6.0 to 11.7.1

### ISSUE THREAD

**Issue by mathdecastilho** [GoogleChrome/lighthouse#15945]
I don't know if it is related to the issue: https://github.com/GoogleChrome/lighthouse/issues/15896#issue-2210370136

**Summary**
My team noticed a change in our page's score (which was decreased) on CalibreApp (a Saas that uses lighthouse to daily check page performance), it just happened from one day to another.
We investigated a lot and didn't find where this problem occurs in our code base. We also tried to roll back our app to an older version, from before the date that our score changed and it doesn't change it at all.
Investigating more we found that Calibre just upgraded the Lighthouse (with Chrome) to version 11.7.1 and the day before was used 11.6.0 to generate the score.
The main-thread working time is just taking twice as long as before.
We decided to test using the CLI on a Macbook Air M1 16GB and noticed the same pattern, changing from 11.6.0 to 11.7.1.
Here are some numbers:

| Description | 11.6.0 | 11.7.1 |
| - | - | - |
| Lighthouse cli | <img width="795" alt="Screenshot 2024-04-15 at 14 19 06" src="https://github.com/GoogleChrome/lighthouse/assets/31900327/d5db8d82-4273-499f-956c-cc3487f1e945"> | <img width="790" alt="Screenshot 2024-04-15 at 14 19 37" src="https://github.com/GoogleChrome/lighthouse/assets/31900327/38cbb3af-e950-42bb-8d06-362b65d21cb6"> |
| Lighhouse cli | <img width="800" alt="Screenshot 2024-04-15 at 14 19 24" src="https://github.com/GoogleChrome/lighthouse/assets/31900327/76c443d6-edfc-48cd-9825-87740e47caa2"> | <img width="796" alt="Screenshot 2024-04-15 at 14 19 50" src="https://github.com/GoogleChrome/lighthouse/assets/31900327/fe9ba9fe-aa03-41f4-bc7b-bb5c3fcc9f0a"> |
| CalibreApp | <img width="838" alt="Screenshot 2024-04-15 at 14 23 43" src="https://github.com/GoogleChrome/lighthouse/assets/31900327/15693e75-d832-4a62-97df-de32e8dc216d"> | <img width="830" alt="Screenshot 2024-04-15 at 14 23 56" src="https://github.com/GoogleChrome/lighthouse/assets/31900327/da32c62d-8541-4bbf-9176-18601369d9e1"> |

About our application: we use Vue 2, with Nuxt 2, in the latest version.
If you want to test using our app, you can create a trial account: https://app.zazos.com/en

**Comment by mathdecastilho** [comment]
> Can you double check your provided version numbers? Lighthouse is on 11.7.1

I'm sorry, it was a typo, I'm referring to versions 11.7.1 and 11.6.0

**Comment by adamraine** [comment]
Just running https://app.zazos.com/en using Lighthouse CLI locally doesn't produce a significant difference in TBT. Are you sure the Chrome version being used did not change as well?

That could be a contributing factor as seen in https://github.com/GoogleChrome/lighthouse/issues/15896

**Comment by mathdecastilho** [comment]
Update:
The version 12.0.0 solves the problem.
Thank you for the support! 🚀
