### ISSUE TITLE
Lighthouse LCP Issue

### ISSUE THREAD

**Issue by alexjwmoran** [GoogleChrome/lighthouse#15955]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.1stformations.co.uk/

### What happened?

When testing the URL above I get the error attached.  When looking for the definition I couldn't find the error anywhere online, it only happens on mobile, not desktop, and only on one page.  I believe it is recognising LCP as text (from webpagetest), not the image and therefore I am wondering if the error is because there is no 'LCP image'.

I just find the language confusing with little explanation 😐

![Screenshot 2024-04-17 165814](https://github.com/GoogleChrome/lighthouse/assets/57496431/758831d1-4008-4d56-9101-106d73ade863)

### What did you expect?

For it not to error on those items

### What have you tried?

Tried on mobile, desktop, other pages on the site (as described above only this page and mobile)
Tried searching for the error to see what it could be 
Tested via WebPage Test to get 'Largest Content'

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

Latest version used on Page Speed Insights

### Chrome Version

Version 124.0.6367.61

### OS

Windows 11

### Relevant log output

```shell
N/A
```

**Comment by adamraine** [comment]
Looks like #15870
