### ISSUE TITLE
Print stylesheet picked for Render-blocking resource

### ISSUE THREAD

**Issue by manzonif** [GoogleChrome/lighthouse#15969]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://pagespeed.web.dev/analysis/https-angular-dev/3inly8hhpn?hl=en&form_factor=mobile

### What happened?

I'd like to bring to your attention that Angular provides a feature called inlineCritical that allows server-side injection of critical CSS directly into the HTML code, thus avoiding render-blocking stylesheets. To ensure that the stylesheet is not considered render-blocking when this option is activated, developers include the stylesheet link as follows:

```<link rel="stylesheet" href="styles-IQDCL4WI.css" media="print" onload="this.media='all'">```

However, in the recent version of Lighthouse, there seems to be no longer a check for media="print", which previously bypassed the audit and prevented it from being flagged as render-blocking. As a result, it is now being reported as render-blocking https://github.com/GoogleChrome/lighthouse/pull/13288 .

Here a screenshot from PageSpeed Insight of the angular.dev website.

Thank you.
![Screenshot 2024-04-19 140637](https://github.com/GoogleChrome/lighthouse/assets/8948699/40639485-4da3-4004-af6b-3b0de0e02dd7)

### What did you expect?

Style with media=print should be ignored for render-blocking resource's audit. 

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

11.5.0

**Comment by adamraine** [comment]
This will not be the case in the next major release of Lighthouse. The changes from #15839 should correctly handle print media stylesheets in the render blocking resources audit.
