### ISSUE TITLE
Protocol error (Target.getTargetInfo): Protocol error (Target.getTargetInfo): 'Target.getTargetInfo' wasn't found

### ISSUE THREAD

**Issue by zanhk** [GoogleChrome/lighthouse#15972]
From https://github.com/harlan-zw/unlighthouse/issues/209

I m having trouble scanning the website https://antares.majestico.it/

On the dev tools with lighthouse I can scan the website correctly [about_blank.pdf](https://github.com/GoogleChrome/lighthouse/files/15052050/about_blank.pdf) 
[antares.majestico.it-20240421T151922.json](https://github.com/GoogleChrome/lighthouse/files/15052062/antares.majestico.it-20240421T151922.json)

but on https://pagespeed.web.dev/analysis/https-antares-majestico-it/0y6apb2qvm?form_factor=mobile and unlighthouse I get an error.

Running from pagespeed I get the error `"generic::internal: Empty extension result. RenderingException: [EXTENSION_ERROR]"`

On unlighthouse (that run with a github action) I get the error `"Protocol error (Target.getTargetInfo): Protocol error (Target.getTargetInfo): 'Target.getTargetInfo' wasn't found"`

See more on https://github.com/harlan-zw/unlighthouse/issues/209

What could be the problem that prevent the website from being scanned correctly?

Thanks

**Comment by joshfester** [comment]
I have having this exact same issue with one of my sites. DevTools works fine, pagespeed gives `"generic::internal: Empty extension result. RenderingException: [EXTENSION_ERROR]"`, and local lighthouse gives `"Protocol error (Target.getTargetInfo): Protocol error (Target.getTargetInfo): 'Target.getTargetInfo' wasn't found"`

**Comment by joshfester** [comment]
In my case this is due to #15739

**Comment by adamraine** [comment]
Looks like the same issue, merging into https://github.com/GoogleChrome/lighthouse/issues/15739
