### ISSUE TITLE
Incorrect user agent on pagespeed.web.dev

### ISSUE THREAD

**Issue by thomaswelton** [GoogleChrome/lighthouse#15971]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://pagespeed.web.dev/analysis

### What happened?

Running a lighthouse test via https://pagespeed.web.dev/analysis/ I can see from the UI that the user agent of the browser running the lighthouse test should be 
> User agent (network): "Mozilla/5.0 (Linux; Android 11; moto g power (2022)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36"

However, when I take a look at my server logs I can see the the user agent is reported as
> userAgent: "Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4590.2 Mobile Safari/537.36 Chrome-Lighthouse"

### What did you expect?

I can see from this issue https://github.com/GoogleChrome/lighthouse/issues/14917 that the words `Chrome Lighthouse` were removed here https://github.com/GoogleChrome/lighthouse/pull/14384 but from my server logs I can see that it is still present in the user agent.

Also instead of the expected `Chrome/119.0.0.0` I'm seeing `Chrome/94.0.4590.2 `

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

11.5.0

**Comment by dwsmart** [comment]
The older version of Chrome reported does seem to trip some sites up, [like this one](https://aspanishbite.es/) that came to the Google Search Central forums. Presumably they are blocking older browser versions, which given isn't a great idea, but would be good to see this have a more up-to-date user-agent string.

**Comment by adamraine** [comment]
I think this is already goal of https://github.com/GoogleChrome/lighthouse/issues/15829
