### ISSUE TITLE
CPU throttling is unstable

### ISSUE THREAD

**Issue by ZengTianShengZ** [GoogleChrome/lighthouse#15978]
**Summary**

I run performance testing on the server side. My server configuration is a fixed 4-core processor and 4GB of memory. I did a fixed 1.6x CPU throttling on Lighthouse. However, I found that the CPU throttling was unstable and fluctuated during performance testing. This will cause my test indicators to be inaccurate. I don't know if this is a bug in Lighthouse, or how I need to configure Lighthouse to avoid this. I want to have stable CPU throttling so that I can generate stable and reliable data during performance testing.

![image](https://github.com/GoogleChrome/lighthouse/assets/15622519/ef74c689-3800-4256-9ac0-fd4495862eb7)
![image](https://github.com/GoogleChrome/lighthouse/assets/15622519/e220559e-016c-47c6-90e6-b6cd180a8cd2)

**Comment by ZengTianShengZ** [comment]
Has anyone encountered a similar situation and has a good solution? 😭

**Comment by adamraine** [comment]
Fluctuating CPU performance can happen for a variety of reasons. Please see https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md
