### ISSUE TITLE
PSI API giving ERRORED_DOCUMENT_REQUEST error for some urls that worked recently

### ISSUE THREAD

**Issue by pushkarbh** [GoogleChrome/lighthouse#15989]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://www.realtor.com/realestateandhomes-search/Chicago_IL

### What happened?

The url https://www.realtor.com/realestateandhomes-search/Chicago_IL  and some other valid urls from the same domain have started failing in the PSI API calls. We used PSI API for these urls for long time successfully but seeing these errors for past couple of weeks. Here is the error:

[Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403)]

All these failing urls continue to work on https://pagespeed.web.dev. I checked bug reports for similar error but most of those are for lighthouse as opposed to PSI API. I see some possible causes listed in https://github.com/GoogleChrome/lighthouse/issues/2784, but curious why the same urls work successfully on the PSI site. We run the API from a Python script but same error can be reproduced by running the API on Postman as well.

Please suggest what can be done to resolve this.

### What did you expect?

As mentioned earlier, these urls worked till couple weeks ago. We expect it to give us web vital data using field and lab metrics very similar to what we can see even now on https://pagespeed.web.dev.

### What have you tried?

Tested different urls and validated on https://pagespeed.web.dev. Other urls from different sites we use in our test suite continue to work. Just the urls from this domain stopped working recently.

### How were you running Lighthouse?

PageSpeed Insights, Other

### Lighthouse Version

11.5.0

### Chrome Version

119.0.0.0

### OS

Linux & Mac

### Relevant log output

```sh
{
    "error": {
        "code": 400,
        "message": "Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403)",
        "errors": [
            {
                "message": "Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403)",
                "domain": "lighthouse",
                "reason": "lighthouseUserError"
            }
        ]
    }
}
```

**Comment by pushkar-bh** [comment]
I just tried using the endpoint we've been using "https://www.googleapis.com/pagespeedonline/v5/runPagespeed" and getting the same error still.

Here is the curl command - ```curl --location 'https://www.googleapis.com/pagespeedonline/v5/runPagespeed?key=<API-KEY>&url=https%3A%2F%2Fwww.realtor.com%2Frealestateandhomes-search%2FChicago_IL&strategy=mobile'```

**Comment by pushkar-bh** [comment]
Hopefully you're able to reproduce the issue. Let me know if not. Thanks!

**Comment by pushkar-bh** [comment]
I tried `curl https://www.realtor.com` and it returns an error page with `This page requires JavaScript!` mentioned in the html response.

I don't work for `realtor.com`, so I won't be able to find out what has changed. But it seems like they've recently added some defense to non-browser accesses. This used to work, so must be a recent change. 

Is there anyway to make this work by sending any custom headers to the PSI api? Thanks for looking into this.

**Comment by pushkar-bh** [comment]
I think the options of using PSI for the mentioned domain are limited given the bot control mechanism put in place. Can the CrUX API or CrUX History API be used to fetch the aggregated data from BigQuery without reaching the origin url?

**Comment by pushkar-bh** [comment]
It would be great to have PSI api to return CrUX part despite Lighthouse failures. Do you have a rough idea when these changes may be available? Is it like 1-2 quarters or longer?

For now I'm going to see if we can use the CrUX or CrUX History api. Thanks!

**Comment by paulirish** [comment]
> It would be great to have PSI api to return CrUX part despite Lighthouse failures. Do you have a rough idea when these changes may be available? Is it like 1-2 quarters or longer?

Unlikely. 

> For now I'm going to see if we can use the CrUX or CrUX History api. Thanks!

Good plan. :)
