### ISSUE TITLE
 LH:ChromeLauncher Waiting for browser

### ISSUE THREAD

**Issue by MuYi086** [GoogleChrome/lighthouse#15980]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://www.baidu.com

### What happened?

System: Win11  x64
After `npm i -g lighthouse`,
I have tried on cmd , git bash and wsl ubuntu bash 
when I use `lighthouse https://www.baidu.com`
the terminal show
`
 LH:ChromeLauncher Waiting for browser. +0ms
  LH:ChromeLauncher Waiting for browser... +0ms
  LH:ChromeLauncher Waiting for browser..... +505ms
  LH:ChromeLauncher Waiting for browser....... +501ms
  LH:ChromeLauncher Waiting for browser......... +502ms
  LH:ChromeLauncher Waiting for browser........... +501ms
  LH:ChromeLauncher Waiting for browser............. +501ms
  LH:ChromeLauncher Waiting for browser............... +501ms
  LH:ChromeLauncher Waiting for browser................. +502ms
  LH:ChromeLauncher Waiting for browser................... +501ms
  LH:ChromeLauncher Waiting for browser..................... +501ms
  LH:ChromeLauncher Waiting for browser....................... +501ms
  LH:ChromeLauncher Waiting for browser......................... +502ms
  LH:ChromeLauncher Waiting for browser........................... +501ms
  LH:ChromeLauncher Waiting for browser............................. +501ms
  LH:ChromeLauncher Waiting for browser............................... +502ms
  LH:ChromeLauncher Waiting for browser................................. +501ms
  LH:ChromeLauncher Waiting for browser................................... +502ms
  LH:ChromeLauncher Waiting for browser..................................... +501ms
`

### What did you expect?

run correct and show me the report

### How were you running Lighthouse?

node

### Lighthouse Version

12.0.0

### Chrome Version

124.0.6367.92

### Node Version

20.12.2

### OS

Win11

### Relevant log output

```sh
LH:ChromeLauncher Waiting for browser. +0ms
  LH:ChromeLauncher Waiting for browser... +0ms
  LH:ChromeLauncher Waiting for browser..... +505ms
  LH:ChromeLauncher Waiting for browser....... +501ms
  LH:ChromeLauncher Waiting for browser......... +502ms
  LH:ChromeLauncher Waiting for browser........... +501ms
  LH:ChromeLauncher Waiting for browser............. +501ms
  LH:ChromeLauncher Waiting for browser............... +501ms
  LH:ChromeLauncher Waiting for browser................. +502ms
  LH:ChromeLauncher Waiting for browser................... +501ms
  LH:ChromeLauncher Waiting for browser..................... +501ms
  LH:ChromeLauncher Waiting for browser....................... +501ms
  LH:ChromeLauncher Waiting for browser......................... +502ms
  LH:ChromeLauncher Waiting for browser........................... +501ms
  LH:ChromeLauncher Waiting for browser............................. +501ms
  LH:ChromeLauncher Waiting for browser............................... +502ms
  LH:ChromeLauncher Waiting for browser................................. +501ms
  LH:ChromeLauncher Waiting for browser................................... +502ms
  LH:ChromeLauncher Waiting for browser..................................... +501ms
```

**Comment by adamraine** [comment]
This is not reproducible for me, it likely has something to do with your environment try setting `CHROME_PATH` to a different version of chrome or using Puppeteer to launch Chrome and use the Node API:
https://github.com/GoogleChrome/lighthouse/blob/main/docs/puppeteer.md

**Comment by JoelLisenby** [comment]
Just in case it helps anyone in the future, I resolved this same error in WSL2 Ubuntu by adding this to the bottom of 

**~/.bash.rc**
`export CHROME_PATH="/usr/bin/google-chrome"`

The above works **after installing Google Chrome**, and you may need to close WSL, then fully shutdown WSL by running `wsl --shutdown` from a PowerShell terminal.

1. Change directories into the temp folder: `cd /tmp`
2. Use wget to download it: `wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`
3. Install the package: `sudo apt install --fix-missing ./google-chrome-stable_current_amd64.deb`
source: https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#install-google-chrome-for-linux
