### ISSUE TITLE
create local version of polymer shop for smoke testing?

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1599]
https://shop.polymer-project.org/ is down [again](https://github.com/GoogleChrome/lighthouse/pull/1491), breaking the smokehouse tests. Usually no big deal to fix, usually just kicking the server instance, but it is annoying when this happens, and we're dependent on the availability of folks who can get it going again.

It's a really helpful example of a PWA + h2 push, though, so maybe we should consider testing against a locally hosted version?

**Comment by patrickhulce** [comment]
I'm down for expanding the test suite with more sites that use a broader set of features and have some ideas about more integration testing. We already can pass a flag to ignore SSL cert errors right?

**Comment by paulirish** [comment]
locally hosting s.p-p requires a certificate and http2 hosting and push, which isn't trivial to setup, so i'm a little wary of it.

**Comment by brendankenny** [comment]
> locally hosting s.p-p requires a certificate and http2 hosting and push, which isn't trivial to setup, so i'm a little wary of it.

agreed, but here we are again :/

**Comment by brendankenny** [comment]
see #1656
