### ISSUE TITLE
Straightforward clientside Manifest gatherer

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#160]
something along these lines? https://gist.github.com/anonymous/f1009dcaedb41552e06c74df5ab63100

mostly rip out the contents of https://github.com/GoogleChrome/lighthouse/blob/master/gatherers/manifest.js otherwise.

**Comment by paullewis** [comment]
Fixed by 052a7f5dc33d5badaa92b90d7a95508221994082
