### ISSUE TITLE
Dev Tools Lighthouse score and Python Lighthouse score is not matching when running from PyCharm terminal

### ISSUE THREAD

**Issue by jeyapradeepBG** [GoogleChrome/lighthouse#16015]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://www.amazon.in/

### What happened?

**Description:**

When utilizing the Python Lighthouse library to run Lighthouse reports, discrepancies are observed in the scores compared to those obtained through the DevTools interface for individual categories. This variance poses a challenge in ensuring consistency between the scores obtained via DevTools and Python Lighthouse.

**Issue:**

Upon running Lighthouse reports via Python Lighthouse library in PyCharm terminal, significant score variations are noted in comparison to the scores acquired from DevTools when running individual categories (e.g., Performance or Best Practices) for desktop devices. The observed variations undermine the reliability and consistency of the scores obtained through Python Lighthouse, raising concerns about the accuracy of the reported metrics.

### What did you expect?

How can I ensure that the scores obtained from both DevTools and Python Lighthouse match exactly? Currently, most runs are producing inaccurate scores.

Below I have attached the screenshot score for performance, accessibility and best practices

**Devtool report for performance**

![Screenshot (2305)](https://github.com/GoogleChrome/lighthouse/assets/167805384/d3a0481a-6be2-4800-b3eb-3a40a0580629)

**Pycharm terminal score for performance**

![Screenshot (2306)](https://github.com/GoogleChrome/lighthouse/assets/167805384/f49b0896-afad-4958-8841-7c292b09a5d0)

**Devtool report for Accessibility**

![Screenshot (2307)](https://github.com/GoogleChrome/lighthouse/assets/167805384/28b7874e-ec54-4daf-bcbf-b8ebc4ca9bf4)

**Pycharm terminal score for Accessibility**

![Screenshot (2308)](https://github.com/GoogleChrome/lighthouse/assets/167805384/1600e224-b58d-41f0-8de7-86334e36a21c)

**Devtool report for best-practices**

![Screenshot (2309)](https://github.com/GoogleChrome/lighthouse/assets/167805384/bbc62e85-5729-4931-b561-2b8bcb5d374c)

**Pycharm terminal score for best-practices**

![Screenshot (2311)](https://github.com/GoogleChrome/lighthouse/assets/167805384/3cd62cd0-6afa-466a-baf4-61f0ce54b116)

### What have you tried?

I have tried to match with browser version, light house version and updated new node version.

### How were you running Lighthouse?

CLI, Chrome DevTools

### Lighthouse Version

11.6.0

### Chrome Version

124.0

### Node Version

v20.12.2

### OS

Windows 10 Enterprise

**Comment by adamraine** [comment]
This looks like normal variability, please see https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md
