### ISSUE TITLE
`aria-allowed-role` description is misleading

### ISSUE THREAD

**Issue by hamirmahal** [GoogleChrome/lighthouse#16023]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [ ] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://hamirs-filmfinder.vercel.app/

### What happened?

I got an ARIA violation, but, as far as I can tell, the flagged code doesn't violate any of the rules listed.

### What did you expect?

I should only get an ARIA violation if the code violates a rule.

### How were you running Lighthouse?

CLI

### Lighthouse Version

11.4.0

**Comment by hamirmahal** [comment]
https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1716840291297-34295.report.html may be helpful.

**Comment by hamirmahal** [comment]
I opened this issue in https://github.com/dequelabs/axe-core/issues/4480, first.

> [Also it looks like the Lighthouse summary of the rule is incorrect as well as that description looks like it fits aria-roles instead of aria-allowed-role. You might want to open an issue with Lighthouse and bring that up.](https://github.com/dequelabs/axe-core/issues/4480#issuecomment-2135296727)

**Comment by adamraine** [comment]
Yeah seems like a docs/description issue we should fix.
