### ISSUE TITLE
Duplicate recaptcha.js in Lighthouse treemap

### ISSUE THREAD

**Issue by DimiRot** [GoogleChrome/lighthouse#16074]
Hi, 
We've been trying to increase a websites score in Insights and checking the Lighthouse Treemap, we saw the https://www.gstatic.com/recaptcha/releases/.../recaptcha__en.js script loads twice. 
Checking the website code, we didn't find multiple instances of the script loading. It's just the <script> and an iframe.

However, when we run Lighthouse from the DevTools, I see just one instance of the recpatcha script loading.

Now, we are wondering, is it some kind of Lighthouse bug? Is it some setting of our websitre? How can we fix it?

Thank you in advance.

**Comment by DimiRot** [comment]
Hi,
I'm attaching a screenshot of lighthouse.
![lighthouse_shot](https://github.com/GoogleChrome/lighthouse/assets/172790863/7b35e00f-c486-465c-b061-1a8d0f2d054d)

Also, the recaptcha_en.js is not running on the website. It's the recaptcha_el.js that is running. 

I appologise if I have misunderstood something, but Page Speed and lighthouse really confuse me.

**Comment by DimiRot** [comment]
Oh sorry, I didn't know.
The site url is https://just4pets.gr/ and I have attached the json.
[just4pets.gr-20240617T093356.json](https://github.com/user-attachments/files/15862975/just4pets.gr-20240617T093356.json)

I find it odd that the reports from Page Speed Insights and LiDevTools Lighthouse are so different. The json I'm attaching is from the Lighthouse tool, while the duplicated reCaptcha js is visible only when testing in the Page Sped Insights.

**Comment by adamraine** [comment]
I can't reproduce this on PageSpeed insights, I don't see any recaptcha js files in the treemap at all:
https://pagespeed.web.dev/analysis/https-just4pets-gr/jyxof2niyb?form_factor=desktop

Using Lighthouse directly, I only see one recaptcha js like you said:
https://googlechrome.github.io/lighthouse/viewer/?gist=f869e5d0f8ee61993b3deb297a4a0272

We can reopen if this becomes reproducible again
