### ISSUE TITLE
Viewer: support uploading compressed reports

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1607]
The report file is getting pretty big for my upload speed, so I believe this could come handy. Support uploading of zip or even better 7z report files.

**Comment by patrickhulce** [comment]
Should file this one with GitHub API, `Content-Encoding` isn't an allowed header in their CORS OPTIONS response :)

**Comment by XhmikosR** [comment]
But isn't it possible to extract the archive on the browser and then send it to GitHub?

**Comment by patrickhulce** [comment]
Well since the extraction in the browser is happening client-side, the only part that slow upload speed would impact is uploading to GitHub.

**Comment by XhmikosR** [comment]
Duh :/ Sorry, hadn't enough coffee when I posted that.
