### ISSUE TITLE
 Lighthouse Calculator Not Working - Empty Screen and Console Errors

### ISSUE THREAD

**Issue by sukhbir-singh-ciir** [GoogleChrome/lighthouse#16075]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://googlechrome.github.io/lighthouse/scorecalc/#FCP=1952&LCP=1952&TBT=1098&CLS=0&SI=2686&TTI=7030&FMP=1952&device=mobile&version=12.0.0

### What happened?

I'm experiencing issues using the Lighthouse calculator. When I attempt to access it, I encounter an empty screen with only the title displayed. Additionally, there are errors present in the browser's console.
![image](https://github.com/GoogleChrome/lighthouse/assets/133486488/e79274e4-d871-43db-99ce-274e054e59b4)
![image](https://github.com/GoogleChrome/lighthouse/assets/133486488/6c5a12bd-2053-4d12-84a5-cb64fdbf1a7f)

### What did you expect?

The Lighthouse calculator should display the user interface elements for performing performance audits.

### What have you tried?

1. Open the Lighthouse calculator from the [Pagesense report](https://pagespeed.web.dev/analysis/https-www-google-com/new4cca0ml?form_factor=mobile).
2. Observe the empty screen with only the title.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

v12.0.0

### Chrome Version

124.0.6367.119

### OS

Windows

**Comment by adamraine** [comment]
Should be fixed now
