### ISSUE TITLE
Lighthouse emits incorrect `Values assigned to role="" are not valid ARIA roles.` message mismatching `axe-core`

### ISSUE THREAD

**Issue by TomerAberbach** [GoogleChrome/lighthouse#16087]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://tomeraberba.ch/avoid-layout-shifts-caused-by-web-fonts-with-postcss-fontpie

### What happened?

Got this error:
```
Values assigned to role="" are not valid ARIA roles.
```

For the `video` elements on the page, which have `role="img"`.

### What did you expect?

I expected Lighthouse to say that `role="img"` is not allowed instead of saying something weird about `role=""`.

I tested out what `axe-core` has to say about `<video role="img"></video>`, and it seems to give a proper message so I'm assuming that Lighthouse is doing something wrong:

<img width="675" alt="Screenshot 2024-06-23 at 8 06 45 PM" src="https://github.com/GoogleChrome/lighthouse/assets/23299544/711cedd5-2ee4-49f5-8629-fd3e9685df2c">

I also confirmed that a minimal repro containing `<video role="img"></video>` still triggers the weird Lighthouse error.

### What have you tried?

Seems pretty obvious that it's a Lighthouse bug. See above.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

12.0.0

### Chrome Version

Version 126.0.6478.114 (Official Build) (arm64)

### OS

MacOS

**Comment by adamraine** [comment]
This should be fixed in the most recent Lighthouse update https://github.com/GoogleChrome/lighthouse/pull/16042
