### ISSUE TITLE
Status code: 403 and code: ERRORED_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by Achchheweb** [GoogleChrome/lighthouse#16084]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://indianexpress.com/

### What happened?

i'm using lighhouse v12.0.0. i have setup lighthouse npm on server and local as well.
But on server i have get maximum URLs reports properly but for some site like: https://indianexpress.com/
getting issue :
There was an error running Lighthouse: `Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403)` (code: ERRORED_DOCUMENT_REQUEST)

chrome-launcher 
1.1.0

How to resolve this issue setup url is
https://frontend-lighthouse.webgarh.net/

### What did you expect?

i want to get the website reports.

### What have you tried?

i tried with extra header but i was not fixed.

### How were you running Lighthouse?

node

### Lighthouse Version

12.0.0

### Chrome Version

124.0.6367.91

### Node Version

18.17

### OS

Ubuntu 20.0

### Relevant log output

```sh
There was an error running Lighthouse: `Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403)` (code: ERRORED_DOCUMENT_REQUEST)
```

**Comment by adamraine** [comment]
The site is returning a 403 status code. Seems like the site is just blocking your server from connecting for some reason but that's all I can really say from this report.

Lighthouse CLI and PageSpeed insights both return results without this error.
