### ISSUE TITLE
`ci.yml` uses a `deprecated` version of `Node.js`

### ISSUE THREAD

**Issue by hamirmahal** [GoogleChrome/lighthouse#16094]
**Summary**

`ci.yml` uses a `deprecated` version of `Node.js`, and `a version of actions/upload-artifact that is scheduled for deprecation`.

**Comment by hamirmahal** [comment]
https://github.com/GoogleChrome/lighthouse/actions/runs/9568114661

**Comment by adamraine** [comment]
This should be fixed by https://github.com/GoogleChrome/lighthouse/pull/16191
