### ISSUE TITLE
all React sites are giving error that Your Docusaurus site did not load properly.

### ISSUE THREAD

**Issue by AshishZiniya** [GoogleChrome/lighthouse#16096]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://redux.js.org/

### What happened?

![Screenshot (44)](https://github.com/GoogleChrome/lighthouse/assets/98575396/285365a8-96ad-4861-a609-7ef9a4daa08b)

### What did you expect?

repaire site 

### How were you running Lighthouse?

Other

### Lighthouse Version

dont know

**Comment by AshishZiniya** [comment]
still only landing page is repaired. other pages are not working

**Comment by AshishZiniya** [comment]
and can you explain why this happened?

**Comment by paulirish** [comment]
I don't see what this has to do with Lighthouse.
