### ISSUE TITLE
Manifest contains start_url false positive

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1609]
Test case: https://meduza.io/

Their manifest looks like this:
```json
{
  "display": "standalone",
  "gcm_sender_id": "999059432363",
  "gcm_user_visible_only": true
}
```

But somehow we say it has a start_url

![image](https://cloud.githubusercontent.com/assets/39191/22570165/22cfccde-e94f-11e6-907e-e725f248a8bb.png)

**Comment by brendankenny** [comment]
Technically this is correct...if there's any error in the `start_url` value (or if it's missing) [the document URL is used as the `start_url`](https://w3c.github.io/manifest/#start_url-member).

We do have a `debugString` warning about the problem, though. Should we output that even though it passes?

We could also set the `displayValue`, maybe, so you'd have a chance to notice that it might be set to the document URL when you meant it to be something else.

**Comment by paulirish** [comment]
well then "manifest contains a start_url" text is incorrect.

and its more like.. "start_url location resolved"

**Comment by brendankenny** [comment]
yeah, good point

**Comment by brendankenny** [comment]
`start_url` is actually loaded now, not just checked for in the manifest
