### ISSUE TITLE
Having source maps in production is not a best practice. Then why the error?

### ISSUE THREAD

**Issue by alex-vukov** [GoogleChrome/lighthouse#16104]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

www.google.com

### What happened?

Whenever I test a website with Lighthouse I always see this error `Missing source maps for large first-party JavaScript`. It is a common (and best) practice not to enable source maps on production for security reasons. Why is this message always shown as an error under `Best Practices`?

### What did you expect?

I expect not to see this error because source maps should only be enabled on internal and test websites

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

12.0.0

### Chrome Version

126.0.6478.127

### OS

MacOS

**Comment by adamraine** [comment]
Valid source maps are only encouraged to make it easier to debug the page with Lighthouse. If you prefer not to expose source maps in production environments that's fine. The source maps audit will not affect your best practices score.
