### ISSUE TITLE
pwa lighthouse

### ISSUE THREAD

**Issue by sajadhzj** [GoogleChrome/lighthouse#16106]
of my idea best feature in lighthouse is pwa , but now is deprecated, and when i want install app i cant get apk install , how can fixed this , do google not support or have alternative?

**Comment by adamraine** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse [has removed the PWA category](https://github.com/GoogleChrome/lighthouse/pull/15455). For future PWA testing, please see the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/)
