### ISSUE TITLE
Page loads very slowly due to CSS.enable

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#16118]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

http://www.kennametal.com/store/us/en/kmt/login.html

### What happened?

The page is stuck loading for quite a while. Recording a trace shows that it's related to StyleEngine calls.

![Screenshot 2024-07-17 at 08 29 42](https://github.com/user-attachments/assets/a5c8bfe9-2204-44b5-8e8b-180a1883e651)

### What did you expect?

The page should load with a similar speed to visiting it normally in Chrome.

### What have you tried?

I tried bypassing any CSS.enable calls, and the page loads as expected.

Not sure if this is still related to this issue? https://github.com/GoogleChrome/lighthouse/issues/15890

### How were you running Lighthouse?

CLI

### Lighthouse Version

12.1.0

### Chrome Version

126

**Comment by Hayzlee11** [comment]
Im using my android phone believe it or not.

**Comment by Hayzlee11** [comment]
https://github.com/GoogleChrome/lighthouse/issues/16118#ref-pullrequest-2413988470

**Comment by Hayzlee11** [comment]
- [ ] thishttps://github.com/GoogleChrome/lighthouse/issues/16118#ref-pullrequest-2413988470 correct

**Comment by Hayzlee11** [comment]
I have no idea what you are talking about. This is driving me crazy. I do
not mean to ignore your emails. Thank you for contacting me but I need to
speak with someone directly to help me figure this out.
