### ISSUE TITLE
Provide two audit descriptions for use if they pass or fail

### ISSUE THREAD

**Issue by pavelfeldman** [GoogleChrome/lighthouse#1611]
After seeing this part of the report:

![css_savings](https://cloud.githubusercontent.com/assets/883973/22570895/387d4bb2-e952-11e6-8736-e533c6911266.png)

it is unclear to me that I failed to use 90% of CSS - my potential savings is coincidentally 90% as well to make things worse.

It be nice to have two versions of titles for each of the audits to humanize the report a bit:

[green] Uses 90% of its CSS rules on load
[ red ] Uses less than 90% of its CSS rules on load

**Comment by ebidel** [comment]
@samdutton said users at I/O mentioned this.

> Might be easier if Lighthouse could express audit failures as 'should'. For example: 'Background and foreground colors should have a sufficient contrast ratio' (for failure) versus 'Background and foreground colors have a sufficient contrast ratio' (for success).

**Comment by ev1stensberg** [comment]
Nearly implemented at #2418 🎉

**Comment by ev1stensberg** [comment]
@pavelfeldman Could you tell me a bit how you're testing CSS rules? Also, if applicable, which url?

**Comment by patrickhulce** [comment]
@ev1stensberg it used to be an audit but it got disabled a while back when the protocol methods changed, don't worry about chasing it down :)

**Comment by ev1stensberg** [comment]
So that means #2478 is done?

**Comment by paulirish** [comment]
fixed by #2478
