### ISSUE TITLE
error message for websites using websocket could be improved

### ISSUE THREAD

**Issue by SimonSiefke** [GoogleChrome/lighthouse#16137]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://websocket-example-0.glitch.me/

### What happened?

1. Try to analyze the url https://websocket-example-0.glitch.me/ with pagespeed insights
2. An error message is displayed `Error! The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again.`

![pagespeed-insights-0](https://github.com/user-attachments/assets/c64c1616-797a-4631-a40e-db2068c50cad)

### What did you expect?

An more helpful error message is displayed that websockets are not supported, e.g. `Error! Pagespeed Insights does not support websockets` 

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

the version pagespeed insights uses

### Relevant log output

```sh
First Contentful Paint
Error!
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
Largest Contentful Paint
Error!
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
Total Blocking Time
Error!
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
Cumulative Layout Shift
Error!
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
Speed Index
Error!
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
```
```


### Additional information

The error seems to occur only with pagespeed insights. When running lighthouse using chrome devtools, no error occurs.

**Comment by adamraine** [comment]
I don't think this error comes from using websockets, like you said it only happens using PageSpeed and not Lighthouse in DevTools.

After debugging this in pagespeed myself I think Lighthouse is accurately reporting that the page does not paint any content. Not sure why this is only happening in pagespeed but I expect the issue is with the site not rendering anything for certain clients.
