### ISSUE TITLE
Invert the report form for the discouraged API use

### ISSUE THREAD

**Issue by pavelfeldman** [GoogleChrome/lighthouse#1613]
Context:

![use_offline](https://cloud.githubusercontent.com/assets/883973/22571148/61e973d0-e953-11e6-9a4e-c86eeb6e55bc.png)

Providing a sharp actionable report would please the user more than repetitive praise for something they did not do. Consider inverting the report form here and listing / penalizing for the deprecated API use.

**Comment by pavelfeldman** [comment]
I see more of these:
- Avoids Mutation Events in its own scripts
- Avoids document.write()
- Avoids requesting the geolocation permission on page load

.. and many more.

but I did not avoid any of these...

**Comment by ebidel** [comment]
"Avoids" was introduced in https://github.com/GoogleChrome/lighthouse/pull/1598. "Does not use S..." was what we had before, but that was deemed confusing to see next to a green check. Discussion is here: https://github.com/GoogleChrome/lighthouse/pull/1598#pullrequestreview-19646677.

Either way, I'm not sure we can make everyone happy.

**Comment by pavelfeldman** [comment]
I have no problem with "Avoid" as a term when I did avoid. I just don't like it reported for about:blank. As the project scales, you'll have hundreds of violations to track and reporting them all as passed for about:blank would not be reasonable. I'm suggesting to only list violations in the dedicated violations group.

**Comment by ebidel** [comment]
How about something like this:

![screen shot 2017-02-02 at 4 09 42 pm](https://cloud.githubusercontent.com/assets/238208/22574161/169e85a0-e962-11e6-84d7-ac52f391b263.png)

For every section, passing all of the audits will give you an overall "pass" and hide the children. If you fail 1 or more, it'll open up and show the list.

**Comment by pavelfeldman** [comment]
That looks better, but still seems a bit silly to say "Uses modern offline features" for the site that does not support offline at all. Just because it did not use WebSQL...

**Comment by ebidel** [comment]
The subcategory names could probably use a rethinking, but I'm not sure the right answer without moving back to "Does not use...." headings. But I think the screenshot alleviates some of the original issue. Our new theme should be "less is more".

**Comment by paulirish** [comment]
> ## Things we don't want you to do.. and you didn't. \o/

> ...

> ## Things we don't want you to do, but you DID! >:| 

> ...

**Comment by ebidel** [comment]
Going to close this. The new report emphasizes what the user needs to improve on and hides the passing audits by default. There's still improvements to the language that we could make (https://github.com/GoogleChrome/lighthouse/issues/1611).

**Comment by paulirish** [comment]
Finally fixed by #2478
