### ISSUE TITLE
Total Blocking Time wrong

### ISSUE THREAD

**Issue by Unterpunkt** [GoogleChrome/lighthouse#16134]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://testshop.isarland.de/Impressum

### What happened?

In the course of a store relaunch, we try to optimize performance. When analyzing with Lighthouse, we noticed that there are drastic differences in the total blocking time depending on whether “simulated throttling” or “devtool throttling” is used.

In my opinion, this is an error because in both cases there are no larger tasks after the FCP.

I also have screenshots of my tests
<img width="1037" alt="lighthouse_sim_tasks" src="https://github.com/user-attachments/assets/18afbd50-3a0e-4f22-a433-d981fb86f101">
<img width="968" alt="lighthouse_sim" src="https://github.com/user-attachments/assets/f4791df9-d7a7-4577-a8f0-8a1cbe8b1011">
<img width="1025" alt="lighthouse_dev_tasks" src="https://github.com/user-attachments/assets/73a1289b-3420-4ffa-8f79-b2d19ed4bee0">
<img width="887" alt="lighthouse_dev" src="https://github.com/user-attachments/assets/58919485-0b63-497a-88db-787aef8d8445">

### What did you expect?

If i understand the Total Blocking Time correct there shouldn't be a difference with or without throttling

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

12.0.0

### Chrome Version

127.0.6533.72

### OS

Windows

**Comment by adamraine** [comment]
When using simulated throttling, the metric values will not match what you see in the raw trace output:
https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me
