### ISSUE TITLE
LCP over 22 000 ms at Lighthouse

### ISSUE THREAD

**Issue by majestica** [GoogleChrome/lighthouse#16149]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://informator.ua/uk

### What happened?

the main problem is that the site works fast, but the report in lighthouse and pagespeed report about very bad LCP metrics Largest Contentful Paint element 22,730 ms, 22,000 ms sounds like something unreal, maybe the problem is in how lighthouse analyzes the page? I will appreciate any help
![image](https://github.com/user-attachments/assets/5a0deee8-d3d8-44f3-a964-6f5670bb972f)

### What did you expect?

I want to get into the green zone in the lighthouse report, so the LSP should be less than 2x

### What have you tried?

I have done endless testing on real devices and could not find the cause of such anomalies in lighthouse.
I have been testing through DevTools in an attempt to find the cause of errors through the network, one of the hypotheses was that lighthouse does not work correctly with srsset when layloading and fech priority, but it seems that this was not confirmed

### How were you running Lighthouse?

node, PageSpeed Insights, Chrome DevTools

### Lighthouse Version

Lighthouse 12.0.0

### Chrome Version

126.0.6478.185

### OS

Windows

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me

Lighthouse computes performance metrics as they would appear for slower mobile devices on a 4G connection. So it is expected that the performance numbers will usually be larger than the perceived performance on your local computer.
