### ISSUE TITLE
No throw still

### ISSUE THREAD

**Issue by Tudayh1** [GoogleChrome/lighthouse#16146]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://pagespeed.web.dev/analysis/https-developer-chrome-com-blog-new-in-devtools-127/a0bexgy6h3?form_factor=desktop&category=performance&category=accessibility&category=best-practices&category=seo&hl=en-US&utm_source=lh-chrome-ext

### What happened?

exactly recieved request for throw still on august 8th two thousand twenty four 23 07:03:13 even when putting it on pause or not starting even one Running even less than 1 one won thing at a time send recieve transfer success question of how many times

### What did you expect?

Active Learner slomo pause send recieve transfer

### What have you tried?

Vibrance rpkc RainmakerPeaceKeeperCollective

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

LightHouse 12.0.0

### Chrome Version

Version 127.0.6533.90 (Official Build) (arm64)

### Node Version

22.6.0

### OS

macOS Sonoma 14.5

### Relevant log output

```sh
mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip-components 1 -C homebrew
or:

https://github.com/Homebrew/brew homebrew
then:

eval "$(homebrew/bin/brew shellenv)"
brew update --force --quiet
chmod -R go-w "$(brew --prefix)/share/zsh"
```

**Comment by Tudayh1** [comment]
:)

**Comment by adamraine** [comment]
Not sure what issue you are reporting or if it's related to Lighthouse
