### ISSUE TITLE
Unable to resolve <WEBSITELINK>  Try checking the URL for validity

### ISSUE THREAD

**Issue by website-speed-expert** [GoogleChrome/lighthouse#16156]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://pagespeed.web.dev/

### What happened?

I am getting always below error :
Unable to resolve <WEBSITELINK> . Try checking the URL for validity

For security reason I can not share website link.

### What did you expect?

How to get fix it?

### What have you tried?

Google Pagespeed Insights

### How were you running Lighthouse?

PageSpeed Insights, web.dev, Other

### Lighthouse Version

Latest version

### Chrome Version

latest version

### Node Version

latest version

### OS

Windows 7

### Relevant log output

```sh
I am getting error each time.
```

**Comment by web-software-developer** [comment]
![Screenshot 2024-08-19 at 16-03-21 PageSpeed Insights](https://github.com/user-attachments/assets/cdd2653b-6a5c-429f-8c3a-4edeed4eb484)

**Comment by adamraine** [comment]
This error can happen if the URL doesn't resolve to anything. Please make sure the URL is valid.

**Comment by web-software-developer** [comment]
The url is valid and open in the browser. But Google pagespeed  insights
still showing that error.

**Comment by adamraine** [comment]
Is there any way you can provide the URL you are testing so we can validate this behavior?
