### ISSUE TITLE
PageSpeed Insights Failed: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by Fudoshiki** [GoogleChrome/lighthouse#16168]
https://pagespeed.web.dev doesn't support `wss` requests, `user-agent` now useless for detection

How can I avoid error messages

![Снимок экрана 2024-08-26 в 18 50 23](https://github.com/user-attachments/assets/6cc5e190-4fd1-408f-8acb-7fef0307e939)

**Comment by rsmything** [comment]
The same issue

**Comment by adamraine** [comment]
Merging as duplicate of https://github.com/GoogleChrome/lighthouse/issues/12459
