### ISSUE TITLE
PageSpeed Insights Issue: "Lost Browser Connection" on Product URL

### ISSUE THREAD

**Issue by Dracoon89** [GoogleChrome/lighthouse#16172]
Hi,

I am experiencing an issue when trying to check the PageSpeed Insights for all product URLs: https://m.mirraw.com/designers/classiques/designs/light-blue-embroidered-semi-stitched-zari-work-and-thread-work-lehenga-choli-lehenga-choli--1f9d3ae7-27c1-4d28-a99d-969d2f29b108.
The diagnostic detail is showing a "Lost browser connection" error.

However, when I check the category URL: https://m.mirraw.com/store/lehengas, it displays the diagnostics correctly without any issues.

Can someone please help me understand what's going wrong with the product URL and how I can fix it?

Thanks in advance!

![m-site-connection-error](https://github.com/user-attachments/assets/c3e61ec9-36e8-4d26-87fc-e12c74750ba1)

**Comment by adamraine** [comment]
I can't reproduce this, are you still seeing the error.

Report for reference: https://pagespeed.web.dev/analysis/https-m-mirraw-com-designers-classiques-designs-light-blue-embroidered-semi-stitched-zari-work-and-thread-work-lehenga-choli-lehenga-choli--1f9d3ae7-27c1-4d28-a99d-969d2f29b108/lg4ygb98xq?form_factor=mobile

**Comment by Dracoon89** [comment]
We have solved it, This was happening due to the deal timer was updating in every interval
