### ISSUE TITLE
Filing an issue like recommended

### ISSUE THREAD

**Issue by youaregoddotorg** [GoogleChrome/lighthouse#16186]
**Summary**
English (United States)

Performance
Accessibility
Best Practices
SEO
0–49
50–89
90–100
There were issues affecting this run of Lighthouse:

There may be stored data affecting loading performance in this location: IndexedDB. Audit this page in an incognito window to prevent those resources from affecting your scores.
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
Performance
Values are estimated and may vary. The performance score is calculated directly from these metrics.See calculator.

Metrics
Collapse view
First Contentful Paint
Error!
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
Largest Contentful Paint
Error!
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
Total Blocking Time
Error!
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
Cumulative Layout Shift
Error!
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
Speed Index
Error!
The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)
Diagnostics
Preload Largest Contentful Paint image Error!
Image elements have explicit width and height Error!
Page didn't prevent back/forward cache restoration Error!
Minify CSS Error!
Minify JavaScript Error!
Serve images in next-gen formats Error!
Enable text compression Error!
Preconnect to required origins Error!
Use HTTP/2 Error!
Use video formats for animated content Error!
Uses efficient cache policy on static assets Error!
All text remains visible during webfont loads Error!
Lazy load third-party resources with facades Error!
Largest Contentful Paint image was not lazily loaded Error!
Uses passive listeners to improve scrolling performance Error!
Has a <meta name="viewport"> tag with width or initial-scale Error!
Eliminate render-blocking resources Error!
Properly size images Error!
Defer offscreen images Error!
Efficiently encode images Error!
Avoid multiple page redirects Error!
Remove duplicate modules in JavaScript bundles Error!
Avoid serving legacy JavaScript to modern browsers Error!
User Timing marks and measures Error!
Avoid large layout shifts Error!
Avoids document.write() Error!
Avoid non-composited animations Error!
Reduce unused CSS Error!
Reduce unused JavaScript Error!
Initial server response time was short Error!
Avoids enormous network payloads Error!
Avoids an excessive DOM size Error!
Avoid chaining critical requests Error!
JavaScript execution time Error!
Minimizes main-thread work Error!
Minimize third-party usage Error!
Largest Contentful Paint element Error!
Avoid long main-thread tasks Error!
More information about the performance of your application. These numbers don't directly affect the [Performance](https://googlechrome.github.io/lighthouse/viewer/#performance) score.
[Accessibility](https://googlechrome.github.io/lighthouse/viewer/#accessibility)
These checks highlight opportunities to improve the accessibility of your web app. Automatic detection can only detect a subset of issues and does not guarantee the accessibility of your web app, so manual testing is also encouraged.
Interactive controls are keyboard focusable Error!
Interactive elements indicate their purpose and state Error!
The page has a logical tab order Error!
Visual order on the page follows DOM order Error!
User focus is not accidentally trapped in a region Error!
The user's focus is directed to new content added to the page Error!
HTML5 landmark elements are used to improve navigation Error!
Offscreen content is hidden from assistive technology Error!
Custom controls have associated labels Error!
Custom controls have ARIA roles Error!
ARIA
[aria-*] attributes match their roles Error!
[aria-hidden="true"] is not present on the document <body> Error!
[role]s have all required [aria-*] attributes Error!
Elements with an ARIA [role] that require children to contain a specific [role] have all required children. Error!
[role]s are contained by their required parent element Error!
[aria-*] attributes have valid values Error!
[aria-*] attributes are valid and not misspelled Error!
ARIA IDs are unique Error!
button, link, and menuitem elements have accessible names Error!
ARIA attributes are used as specified for the element's role Error!
Elements with role="dialog" or role="alertdialog" have accessible names. Error!
[aria-hidden="true"] elements do not contain focusable descendents Error!
ARIA input fields have accessible names Error!
ARIA meter elements have accessible names Error!
ARIA progressbar elements have accessible names Error!
Elements use only permitted ARIA attributes Error!
[role] values are valid Error!
Elements with the role=text attribute do not have focusable descendents. Error!
ARIA toggle fields have accessible names Error!
ARIA tooltip elements have accessible names Error!
ARIA treeitem elements have accessible names Error!
Uses ARIA roles only on compatible elements Error!
Deprecated ARIA roles were not used Error!
These are opportunities to improve the usage of ARIA in your application which may enhance the experience for users of assistive technology, like a screen reader.
Names and labels
Buttons have an accessible name Error!
Image elements have [alt] attributes Error!
Input buttons have discernible text. Error!
<input type="image"> elements have [alt] text Error!
Document has a <title> element Error!
<frame> or <iframe> elements have a title Error!
Form elements have associated labels Error!
Links have a discernible name Error!
<object> elements have alternate text Error!
Select elements have associated label elements. Error!
No form fields have multiple labels Error!
Skip links are focusable. Error!
Image elements do not have [alt] attributes that are redundant text. Error!
These are opportunities to improve the semantics of the controls in your application. This may enhance the experience for users of assistive technology, like a screen reader.
Best practices
The document does not use <meta http-equiv="refresh"> Error!
[user-scalable="no"] is not used in the <meta name="viewport"> element and the [maximum-scale] attribute is not less than 5. Error!
Touch targets have sufficient size and spacing. Error!
These items highlight common accessibility best practices.
Audio and video
<video> elements contain a <track> element with [kind="captions"] Error!
These are opportunities to provide alternative content for audio and video. This may improve the experience for users with hearing or vision impairments.
Navigation
[accesskey] values are unique Error!
The page contains a heading, skip link, or landmark region Error!
No element has a [tabindex] value greater than 0 Error!
Heading elements appear in a sequentially-descending order Error!
These are opportunities to improve keyboard navigation in your application.
Contrast
Background and foreground colors have a sufficient contrast ratio Error!
Links are distinguishable without relying on color. Error!
These are opportunities to improve the legibility of your content.
Tables and lists
<dl>'s contain only properly-ordered <dt> and <dd> groups, <script>, <template> or <div> elements. Error!
Definition list items are wrapped in <dl> elements Error!
Lists contain only <li> elements and script supporting elements (<script> and <template>). Error!
List items (<li>) are contained within <ul>, <ol> or <menu> parent elements Error!
Cells in a <table> element that use the [headers] attribute refer to table cells within the same table. Error!
<th> elements and elements with [role="columnheader"/"rowheader"] have data cells they describe. Error!
Tables have different content in the summary attribute and <caption>. Error!
These are opportunities to improve the experience of reading tabular or list data using assistive technology, like a screen reader.
Internationalization and localization
<html> element has a [lang] attribute Error!
<html> element has a valid value for its [lang] attribute Error!
[lang] attributes have a valid value Error!
<html> element has an [xml:lang] attribute with the same base language as the [lang] attribute. Error!
These are opportunities to improve the interpretation of your content by users in different locales.
[Best Practices](https://googlechrome.github.io/lighthouse/viewer/#best-practices)
Trust and Safety
Uses HTTPS Error!
Redirects HTTP traffic to HTTPS Error!
Avoids requesting the geolocation permission on page load Error!
Avoids requesting the notification permission on page load Error!
Ensure CSP is effective against XSS attacks Error!
General
Avoids deprecated APIs Error!
Avoids third-party cookies Error!
No browser errors logged to the console Error!
No issues in the Issues panel in Chrome Devtools Error!
Detected JavaScript libraries Error!
Page has valid source maps Error!
User Experience
Allows users to paste into input fields Error!
Displays images with correct aspect ratio Error!
Serves images with appropriate resolution Error!
Has a <meta name="viewport"> tag with width or initial-scale Error!
Document uses legible font sizes Error!
Browser Compatibility
Page has the HTML doctype Error!
Properly defines charset Error!
[SEO](https://googlechrome.github.io/lighthouse/viewer/#seo)
These checks ensure that your page is following basic search engine optimization advice. There are many additional factors Lighthouse does not score here that may affect your search ranking, including performance on Core Web Vitals. Learn more about Google Search Essentials.
Structured data is valid Error!
Crawling and Indexing
Page isn’t blocked from indexing Error!
Page has successful HTTP status code Error!
Links are crawlable Error!
robots.txt is valid Error!
To appear in search results, crawlers need access to your app.
Content Best Practices
Document has a <title> element Error!
Document has a meta description Error!
Links have descriptive text Error!
Image elements have [alt] attributes Error!
Document has a valid hreflang Error!
Document has a valid rel=canonical Error!
Format your HTML in a way that enables crawlers to better understand your app’s content.
Captured at Sep 14, 2024, 7:42 AM EDT
Emulated Moto G Power with Lighthouse 12.1.0
Single page session
Initial page load
Slow 4G throttling
Using Chromium 128.0.0.0 with devtools
Generated by Lighthouse 12.1.0 | File an issue
[x.com_2024-09-14_07-42-45.json](https://github.com/user-attachments/files/17002173/x.com_2024-09-14_07-42-45.json)

**Comment by adamraine** [comment]
This is not enough information to understand your issue. [Please fill out a full bug report here](https://github.com/GoogleChrome/lighthouse/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml).
