### ISSUE TITLE
Is there a API or others can configure extension allow in incognito options in programming way?

### ISSUE THREAD

**Issue by stefanie0722** [GoogleChrome/lighthouse#16188]
Currently we click the 'allow in incognito' options manually to make extension enabled in incognito mode. In my case, I need to configure this option in my python program, so is there any API to support this option?

![image](https://github.com/user-attachments/assets/9ed536f7-83eb-41e0-9cc0-7e4afdfe8ced)

**Comment by adamraine** [comment]
That option is not specific to the Lighthouse extension. All extensions should have this option.

Unfortunately I don't know how to configure this option in Chrome via an api.
