### ISSUE TITLE
Consider providing simplified / primitive timeline in place of the performance metrics

### ISSUE THREAD

**Issue by pavelfeldman** [GoogleChrome/lighthouse#1618]
A simple timeline (one track) with the core timers (FMP, TTI, etc.) and screenshots would be more useful.

![pefr_metrics](https://cloud.githubusercontent.com/assets/883973/22571915/ba113ba8-e956-11e6-9796-498fa786fd39.png)

**Comment by paulirish** [comment]
fixed by @pavelfeldman here https://codereview.chromium.org/2861053003/

i'll be upstreaming this to Lighthouse

**Comment by patrickhulce** [comment]
completed by #2239 and #2256
