### ISSUE TITLE
set cookie unsupport playwright，only support puppeter

### ISSUE THREAD

**Issue by ljtyzx** [GoogleChrome/lighthouse#16185]
11.0.0

docs/recipes/auth/README.md
**Feature request summary**

i wan't set-cookie can be support by playwright
in docs/recipes/auth/README.md 
i can only see that it support puppeter in the doc，when i use playwright， it throw a error:
/node_modules/lighthouse/core/gather/driver.js:82
    const cdpSession = await this._page.target().createCDPSession();
                                        ^
TypeError: this._page.target is not a function

**What is the motivation or use case for changing this?**
first to be honest， in my department，suggest we use playwright to test our project
second the playwright project has 65.6 star，many project use it，it has many user

**How is this beneficial to Lighthouse?**
the playwright project has 65.6 star in GitHub，many project use it，it has many user，if it support， Lighthouse will have more user

**Comment by ljtyzx** [comment]
![image](https://github.com/user-attachments/assets/5cbd2630-32e1-4507-881b-29d1692509da)

this is my code

**Comment by ljtyzx** [comment]
![image](https://github.com/user-attachments/assets/55a6ed2d-c506-4cc3-9e51-975ebb6f4a43)

this is my code and  this is the error

/node_modules/lighthouse/core/gather/driver.js:82
    const cdpSession = await this._page.target().createCDPSession();
                                        ^
TypeError: this._page.target is not a function

**Comment by adamraine** [comment]
We don't officially support playwright, here is a previous discussion about it: https://github.com/GoogleChrome/lighthouse/discussions/13326
