### ISSUE TITLE
Performance Score mismatch the submetrics sum

### ISSUE THREAD

**Issue by immunity20** [GoogleChrome/lighthouse#16193]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://www.cakeshop.gr/vaptisi/donuts-me-epikalipsi

### What happened?

Performance Score shows 99 but when you hover the  mouse over it it shows max points for every metric (SI FCP LCP TBT CLS) 10,10,25,30,25 which equals to 100 not 99

![image](https://github.com/user-attachments/assets/8fa19c5c-de2e-4bcf-8460-ec8ae6bb7734)

### What did you expect?

show performance score 100

### What have you tried?

Just measured my website performance

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

12.1.0

### Chrome Version

128.0.6613.138

### OS

Windows

**Comment by adamraine** [comment]
This is probably just an artifact from rounding
