### ISSUE TITLE
Links to the minified source code are not user-friendly

### ISSUE THREAD

**Issue by pavelfeldman** [GoogleChrome/lighthouse#1619]
It points to location 2:13793... And it'll always be minified, hence ugly. How about you pretty-print the source and extract a fragment :P

![pretty_print](https://cloud.githubusercontent.com/assets/883973/22572462/189fef32-e959-11e6-9d09-f14de979d974.png)

**Comment by paulirish** [comment]
Currently not a problem, but we'll link directly into devtools for this in the future.

**Comment by brendankenny** [comment]
> Currently not a problem, but we'll link directly into devtools for this in the future.

dedupe into #3457
