### ISSUE TITLE
Accessibility contrast ratio between foreground/background returns incorrect result when a brightness filter is applied

### ISSUE THREAD

**Issue by nyoungstudios** [GoogleChrome/lighthouse#16209]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

local example

### What happened?

The Lighthouse Accessibility Contrast test `Background and foreground colors do not have a sufficient contrast ratio.` returns incorrect results when a brightness filter is applied.

Here is my minimal example. Name this file `index.html` and place in a folder called `test`. Then you can run a command like `python -m http.server -d test 3000` to serve the html file to run the Lighthouse test in Chrome.

```html
<html lang="en">
<head>
  <title>Lighthouse Accessibility Test</title>
</head>
<body>
  <!-- should pass, passes -->
  <h2 style="color: rgb(0, 0, 0)">Black with no brightness adjustment.</h2>
  <!-- should pass, passes -->
  <h2 style="color: rgb(147, 147, 147)">Middle gray with no brightness adjustment</h2>
  <!-- should fail, passes -->
  <h2 style="color: rgb(147, 147, 147); filter: brightness(1000%)">Middle gray with 1000% brightness</h2>
  <!-- should fail, fails -->
  <h2 style="color: rgb(241, 241, 241)">95% white with no brightness adjustment</h2>
  <!-- should pass, fails -->
  <h2 style="color: rgb(241, 241, 241); filter: brightness(0%)">95% white with 0% brightness</h2>
</body>
</html>
```

### What did you expect?

Here is what the rendered example looks like.
![image](https://github.com/user-attachments/assets/38f0cbf6-4d5c-4d6b-a25b-36c2411333be)

It is pretty clear that the first, second, and fifth lines should pass the Lighthouse contrast test. However, the first, second, and third lines are the ones that pass the Lighthouse contrast test.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

12.2.0

### Chrome Version

129.0.6668.72 (Official Build) (64-bit) (cohort: Control)

### OS

Windows 11

**Comment by adamraine** [comment]
This is reproducible with Axe outside Lighthouse, can you file a bug in [axe-core](https://github.com/dequelabs/axe-core)
