### ISSUE TITLE
missing references files from tsconfig.json

### ISSUE THREAD

**Issue by mjalav** [GoogleChrome/lighthouse#16214]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

locally

### What happened?

I did install lighthouse with npm install lighthouse and I see following references was not find in tsconfig.json

not found. The file is in the program because: Part of 'files' list in tsconfig.json
- /cli/test/fixtures/static-server.js
- /core/test/audits/bf-cache-test.js
- /core/test/audits/script-treemap-data-test.js
- /core/test/audits/third-party-cookies-test.js
- /core/test/computed/metrics/interactive-test.js
- /core/test/computed/tbt-impact-tasks-test.js
- core/test/fixtures/config-plugins/lighthouse-plugin-simple/plugin-simple.js

Also in references seems like we don't have treemap folder after installing packages. got an error //treemap' not found.
  "references": [
    {"path": "./types/lhr/"},
    {"path": "./report/"},
    {"path": "./report/generator/"},
    {"path": "./shared/"},
    {"path": "./treemap/"}, 
  ],

### What did you expect?

expected references manage properly in installed package.

### What have you tried?

I did try to download lighthouse project from github and overwrite missed file to my project. That resolved the issue.

### How were you running Lighthouse?

node

### Lighthouse Version

12.2.1

### Chrome Version

129.0.6668.90

### Node Version

v22.6.0

### OS

Windows

**Comment by adamraine** [comment]
How exactly are you using the Lighthouse package. Can you provide some specific repro steps?

**Comment by mjalav** [comment]
@adamraine you can create new folder in your computer and do
npm i typescript --save-dev
npm install lighthouse

Then go to node_modules\lighthouse\tsconfig.json
you can see in line 11 there is ./treemap/ folder which is not exist. same for other files that I mentioned earlier. 
![Screenshot 2024-10-11 102006](https://github.com/user-attachments/assets/86b102f7-867e-4de1-afa4-4e55989e8e6a)

**Comment by adamraine** [comment]
We don't publish those files in the NPM package, so a missing file in a code editor seems expected. Is this causing any other issues?

**Comment by mjalav** [comment]
@adamraine no it doesn't cause any other issue.

**Comment by adamraine** [comment]
I don't know if there is an easy fix, and I would prefer not to restructure or typescript setup unless there is a visible issue so I'm going to close as WAI.
