### ISSUE TITLE
CSS usage inline preview broken

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1621]
at some point very recently the preview has shifted to be next to the `inline` word instead of below it

![image](https://cloud.githubusercontent.com/assets/2301202/22574077/7211876c-e961-11e6-8596-7bafd232502c.png)

**Comment by patrickhulce** [comment]
Ah #1545 cleaned up the old flexbox display but introduced the issue seen above, will try to reconcile.

**Comment by ebidel** [comment]
Ah sorry!

**Comment by patrickhulce** [comment]
No worries @ebidel but you can review my fix :)
