### ISSUE TITLE
Is it possible to support running lighthouse user flow with playwright? 

### ISSUE THREAD

**Issue by yonatanai** [GoogleChrome/lighthouse#16246]
The Lighthouse user flow works internally with Puppeteer, but I'd like to know if it can be used with Playwright instead. 
We want to create user-flow e2e tests to prevent performance regression, and user flow is a good solution. However, we write our e2e tests using Playwright, so I'm wondering if we can integrate Lighthouse into our tests.

**Comment by adamraine** [comment]
Short answer is that this is not officially supported: https://github.com/GoogleChrome/lighthouse/discussions/13326
