### ISSUE TITLE
Incorrect translation in SEO audit

### ISSUE THREAD

**Issue by hakoyamah** [GoogleChrome/lighthouse#16274]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://pagespeed.web.dev

### What happened?

In the Lighthouse SEO audit, the message for "Structured data is valid" is incorrectly translated as "構造化データが無効です" ("Structured data is invalid"). This is an error, as the correct translation should be "構造化データは有効です" ("Structured data is valid").

Please update the translation to reflect the correct meaning.

### What did you expect?

"構造化データは有効です" 

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

v12.2.3

**Comment by adamraine** [comment]
Thanks for noticing this, I've filed a bug with our translators internally!
