### ISSUE TITLE
v.12.2.3 not available in npm registry

### ISSUE THREAD

**Issue by shakalandy** [GoogleChrome/lighthouse#16277]
**Summary**

Somehow the recent release v12.2.3 hasn't been released in the npm repository.
Is this because the package itself was not affected by the change?

Currently, 12.2.2 and 12.2.3-dev.20241205 and some other 12.2.3-dev* versions are available, but no final 12.2.3

https://www.npmjs.com/package/lighthouse?activeTab=versions

Thanks!

![image](https://github.com/user-attachments/assets/645f24ed-5aa2-4c42-82b0-8b56f00029c5)

**Comment by adamraine** [comment]
> Is this because the package itself was not affected by the change?

Yes, the change does not affect NPM

https://github.com/GoogleChrome/lighthouse/releases/tag/v12.2.3

**Comment by benschwarz** [comment]
@adamraine could it be published to NPM like normal anyway?

**Comment by adamraine** [comment]
> @adamraine could it be published to NPM like normal anyway?

What would be the reason, just to reduce confusion?

**Comment by benschwarz** [comment]
I use LR configs, but also yep, for completeness sake!

**Comment by adamraine** [comment]
Since the package did technically change I published v12.2.3 to NPM.
