### ISSUE TITLE
"Date.now()" warning should only appear if called multiple times

### ISSUE THREAD

**Issue by steffenweber** [GoogleChrome/lighthouse#1628]
Thank you for Lighthouse! I have found a minor aspect that could be improved. :smiley: 

My JavaScript code calls `Date.now()` once during/after pageload to get the current date/time. I think this use is legitimate. I'm not using it to measure performance (I understand that `performance.now()` is the appropriate way to do that).

Hence, would it be possible (with reasonable efforts) to show the warning "JavaScript: Site does not use Date.now() in its own scripts" only if `Date.now()` is called more than once?

Or is there a more appropriate way to get the date/time of a pageload? Afaik it is not possible to e.g. access the `Date` header sent by the server.

**Comment by ebidel** [comment]
Using `Date.now()` to get a date is definitely a legitimate use :). 

If you're interested in a timestamp for "page load", you could also consider the PerformanceTiming API. There are a lot of gems in there to get accurate information on different parts of pageload.

https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/navigationStart

**Comment by steffenweber** [comment]
I somehow thought that all timestamps of the PerformanceTiming API were relative to the pageload time and therefore useless for my purpose (maybe because `performance.now()` returns a relative timestamp).

That solves my problem, thank you!
