### ISSUE TITLE
Implement driver.sendCommands() (plural)

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1629]
It's possible to send a bunch of debugger protocol commands at once instead of waiting for each one to execute before sending the next one. In some cases (e.g. getting all event listeners) it makes sense to send a gatherer's commands all at once, then get a rush of them back instead of most of the execution time waiting on the overhead of the web socket connection.

This should be somewhat transparent to the user...still tracking command IDs so everything is in the right order, etc.

What would the return look like? Array of results? Named results on an object?

Would it be possible to group the convenience methods we've implemented on `Driver` so you wouldn't have to use just raw commands to take advantage of this?

**Comment by patrickhulce** [comment]
What are you envisioning about this implementation that would be substantively different from `Promise.all`?

**Comment by brendankenny** [comment]
> What are you envisioning about this implementation that would be substantively different from Promise.all?

that may be sufficient. We can do a quick trace with `all-event-listeners` set to run via `Promise.all` instead of a reduce chain and see if more is needed.

**Comment by paulirish** [comment]
I think doing the bare work with `Promise.all` inside the event listeners gatherer probably makes most sense for now. Seems like the ergonomics will be slightly awkward with a `sendCommands` helper method, but who knows.
