### ISSUE TITLE
Add progress bar for crx/devtools auditing

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1630]
It would be nice to have a progress bar when auditing the page. Similar to PSI and https://testmysite.thinkwithgoogle.com/. As we add more audits, this will become more important.

In the extension, we how the user the list of audits as they run. The progress could be a quick % completed: `(num audits done / total audits) * 100`.

**Comment by paulirish** [comment]
Relatedly the progress monitor in #815 was designed for keeping track of tasks, incomplete and complete.

**Comment by pavelfeldman** [comment]
Should I resurrect the patch?

**Comment by ebidel** [comment]
Sure! Not sure how much has changed since then. Looks like there is a bunch of rebasing that needs to take place.

**Comment by brendankenny** [comment]
possible dupe of streaming results
