### ISSUE TITLE
Proposal to refactor passes

### ISSUE THREAD

**Issue by pavelfeldman** [GoogleChrome/lighthouse#1631]
**Pass 1: fast pass, runs quickly, presents intermediate report to the user.** 
No throttling, but with security, a11y, appyness, coverage, discourage APIs use, potential savings, analysis. Uses mobile UA.

**Pass 2: throttled pass, network and CPU throttlings are enabled**. 
Performance report generated, timeline with screenshots presented. 

**Pass 3: offline pass,** 
Offline report generated, screenshots captured

------

No JavaScript => converted into parsing main resource and extracting innerText from there
HTTP redirect => convert into one-off report or backend implementation

**Comment by brendankenny** [comment]
Definitely like the idea of streaming in results and removing throttling during non-perf tests (though that might take some juggling...e.g. measuring usage or image responsiveness should probably happen in the first pass but average throughput would have to be calculated when throttled)

Would this clear storage between pass 1 and pass 2 to match current behavior wrt cold cache for measuring load and one page load before testing offline?

I also wonder about long term maintenance as the pressure will be to add more and more audits. #1690 to track how long it takes Lighthouse to run will help us stay disciplined on that, at least.

We also shouldn't lose sight that this is just for the default run and we still need to support custom configs :)

**Comment by brendankenny** [comment]
I believe this is mostly finished (with changes to meet reality of today (OYB/fast mode)) except streaming in results, which I believe is captured in another issue?
