### ISSUE TITLE
Link to PWA Checklist at end of PWA section in report

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1638]
https://developers.google.com/web/progressive-web-apps/checklist is great and has a number of things listed that we cannot write automated tests for.

**Comment by Rod911** [comment]
![image](https://user-images.githubusercontent.com/25589171/181288546-b4e10a80-f530-4ed5-93b5-649f6e4b1a37.png)
This link returns a 404

**Comment by adamraine** [comment]
@Rod911 this was just fixed https://github.com/GoogleChrome/lighthouse/pull/14240
