### ISSUE TITLE
Enable shop in smokehouse tests

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1656]
...when it is ready to be cooperative.

https://github.com/GoogleChrome/lighthouse/issues/1653 disabled it.

**Comment by brendankenny** [comment]
tempting to close this, but it is nice to have a PRPL/h2 push test site. We could maybe reenable and see how it does with one more chance. Could also find an alternative site to test using these features.

**Comment by brendankenny** [comment]
has been enabled and stable for quite some time :)
