### ISSUE TITLE
Output screenshots in consumable format

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1661]
WPT needs screenshots from the end of the pass and currently our `<FILE>.screenshots.html` is not programmatically consumable.

**Comment by patrickhulce** [comment]
No longer necessary for WPT, but still a nice feature to have :)

**Comment by brendankenny** [comment]
I believe now served by the saved screenshots JSON (in addition to the still saved old `screenshots.html`)
