### ISSUE TITLE
WPT compat: support cache warm run

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1664]
WPT performs a cache cold run and a cache warm run while LH always clears all storage for the origin and disables the network cache.

**Comment by brendankenny** [comment]
this implies a new pass with no perf-interfering gatherers?

**Comment by patrickhulce** [comment]
> this implies a new pass with no perf-interfering gatherers?

I'd start with the ability to run from CLI with the storage clearing/cache disabling off.

**Comment by paulirish** [comment]
>  I'd start with the ability to run from CLI with the storage clearing/cache disabling off.

Question.. should we have all these options available through the CLI or make a wpt-adapter.js in core that's a bit more custom

**Comment by patrickhulce** [comment]
I'm in favor of making most of these flags without coupling explicitly to WPT. I don't think it does anything too crazy aside from the video capture, and in some cases just brings nice functionality to all of Lighthouse.

**Comment by paulirish** [comment]
k.  i'm comfortable with both directions. just figured i'd ask. :)
