### ISSUE TITLE
Adopt Page.getAppManifest's errors object

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1666]
We currently don't listen to any of the errors and warnings that Chrome's native manifest parser spits back. It includes parsing errors (invalid JSON) as well as manifest correctness errors.

There's two levels of adoption really:

1. Consider the critical errors so we can reject early if Chrome knows it can't read the manifest. 
2. Consider the non-critical errors which overlap with the checks that manifest-parser does

Just #1 probably makes sense for the short term... FWIW here's an example of the sorts of errors we would be getting:

#### invalid json (critical)

![image](https://cloud.githubusercontent.com/assets/39191/22718884/bd16b968-ed57-11e6-94a1-a9fd5514dc05.png)

#### bad value for `display` property (non-critical)

![image](https://cloud.githubusercontent.com/assets/39191/22718895/ca5c624e-ed57-11e6-92f1-6b2abcb5751a.png)

#### bad value for `icons` property (non-critical)

![image](https://cloud.githubusercontent.com/assets/39191/22718911/d2218ad6-ed57-11e6-8819-2c9e0f96156d.png)

---------

Also see #823 and #1624 where we had some of this discussion

**Comment by brendankenny** [comment]
same-ish as #2348, PR up in #2349 (though controversial :)

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
