### ISSUE TITLE
Strip non-essentials from browserified bundles

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1670]
We current browser a bunch of extras (duplicate license headers, full package.json content) as part of the crx and viewer bundles. It would be nice to clean that up a bit.

![screen shot 2017-02-08 at 10 39 24 am](https://cloud.githubusercontent.com/assets/238208/22751865/12f83cc4-edeb-11e6-9e05-0c0ef2585013.png)
![screen shot 2017-02-08 at 10 39 49 am](https://cloud.githubusercontent.com/assets/238208/22751867/12fc2cc6-edeb-11e6-9ed1-8f515596ed1b.png)

**Comment by brendankenny** [comment]
I believe none of this is still in either bundle, except for the non-minified report renderer sources. I'm going to close this issue in favor of #2014 which captures that.
