### ISSUE TITLE
false denied state on GeolocationOnStart gatherer on some sites

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1676]
Haven't looked into this yet, so it may be something obvious. Discovered when testing `http://angularexpo.com/`, in the CLI or extension. I get:

`Required GeolocationOnStart gatherer encountered an error: Unable to determine if this permission was requested on page load because it had already been set. Try resetting the permission and running Lighthouse again.`

Checking the state, it's seeing the permission as `denied` even though this is a new blank Chrome profile.

Interestingly the `NotificationOnStart` gatherer has no issue with this page, even though it's querying the permission state in the same way.

**Comment by brendankenny** [comment]
(I was worried this was from #1641 with the change from -1 over to `throw new Error()`, but I can repro the problem on commits before that)

**Comment by brendankenny** [comment]
@ebidel has a fix to put a better error message for this, but he found the root cause was that the page isn't HTTPS, and [geolocation works only on secure origins as of m50](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only), so `navigator.permissions.query` will always returned `denied` for it on that page.

Since we check for that status before running the gatherer, pages without HTTPS will get this warning even if the page isn't actually asking for the permission.

**Comment by ebidel** [comment]
I've [filed a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=680832) against chromium to get the console log showing up in our deprecations/interventions audit.
