### ISSUE TITLE
Remove gulp-browserify

### ISSUE THREAD

**Issue by boopathi** [GoogleChrome/lighthouse#168]
+ gulp-browserify is a deprecated module.

A few questions before I send a PR regarding this.

+ Since we use only latest chrome, we could simply use es6 code in browser - why transpile ? (edit: no uglify for es6 )
+ And why browserify and rollup ?, if we have all our files as ES6 modules (transpile only es6 module stuff for node), it would be possible to use rollup along with rollup's commonjs, node-resolve, and json plugins. Or only have browserify and remove rollup ?

Would be happy to send a PR.

**Comment by paulirish** [comment]
> Since we use only latest chrome, we could simply use es6 code in browser - why transpile ? (edit: no uglify for es6 )

afaik, the browserify is mostly used because of the require().  

feel free to hack on this! we can probably remove one of the two, though I'm unsure which suits us better.

**Comment by paulirish** [comment]
@brendankenny you were looking at this. do you have work in flight, or shall @boopathi take this on?

for the record, this issue is about replacing gulp-browserify with browserify.

**Comment by brendankenny** [comment]
I was already looking at this since I was in the extension gulpfile, so I'm happy to take it if @boopathi doesn't already have something going

**Comment by paulirish** [comment]
yeah go for it
