### ISSUE TITLE
Add top-level warning for perf-affecting chrome extensions

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1689]
Disabled in https://github.com/GoogleChrome/lighthouse/pull/1687

Even though the setting was opt-in, the new permission was deemed too risky to add to the crx at this time. It disables Lighthouse and users need to reenable the extension and some extensions do not expect to be shut down like this.

We should create a profile with a bunch of developer extensions and test that this features has measurable impact. If not, we should probably just have banner messaging that suggestions running the extension in a clean profile.

**Comment by ebidel** [comment]
@patrickhulce also found https://developer.chrome.com/extensions/permissions#manifest (enable permissions at runtime).

**Comment by paulirish** [comment]
re-scoping this to warn if you have a given extension installed. We'll use a safelist of known bad extensions

**Comment by wardpeet** [comment]
It has been fixed in https://github.com/GoogleChrome/lighthouse/pull/5666. We show a warning when chrome extensions slow down our performance score.

Thank you for opening this issue.
