### ISSUE TITLE
Automation to track our build sizes

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1690]
For a number of our build assets, we'd like to keep track of how big they are over time.

* `lighthouse-background.js`: Used in both extension and devtools. 
* `viewer/main.js`: Used in the online viewer
* the tarball that's published to NPM

Relatedly.. we're also interested in tracking the **duration of doing a default lighthouse run**. Potentially against both a simple site (example.com) and a more complex one (chromestatus.com).

This is pretty wide open for implementation.

Some of this could be done based on our travis/smokehouse runs.
No preferences on where the data gets beaconed to, but something that's easy for the team and community to view.

**Comment by wardpeet** [comment]
We might beacon it to firebase database? As we already have the viewer on there.

**Comment by paulirish** [comment]
FWIW the [pwmetrics project](https://github.com/paulirish/pwmetrics/) has all the code necessary to publish results to google sheets. That'd be nice as we can make the data public and fairly hackable from there.

**Comment by wtgtybhertgeghgtwtg** [comment]
Something that might shave off a few megabytes would be replacing `handlebars`.  The package alone is about 2.5 MB; factor in its dependencies on `uglify-js`, `source-map`, and `async`, and the fact that the version of `yargs` in its dependency tree doesn't dedupe with the version `lighthouse` uses, and it adds up pretty quickly.

**Comment by paulirish** [comment]
@wtgtybhertgeghgtwtg 

Here's a treemap of our current build: https://cdn.rawgit.com/paulirish/d86e390c53e8de23511bf880fdffe1cd/raw/ac5e4188bf8cf4c835b3d9232b2ab000404d1782/lighthouse-build.html

![image](https://cloud.githubusercontent.com/assets/39191/23302618/39c6665e-fa44-11e6-966a-dbdc4f84fdc8.png)

handlebars isn't small, but it does only top out at 146kb of the overall build.

**Comment by wtgtybhertgeghgtwtg** [comment]
Sorry, I was looking at the version in `node_modules`.

**Comment by wardpeet** [comment]
@paulirish I could look at this if you like.

**Comment by wardpeet** [comment]
I have a working branch of this https://github.com/wardpeet/lighthouse/tree/feature/beacon

@paulirish should we close this one until we know what to do with this one?

**Comment by brendankenny** [comment]
https://github.com/siddharthkp/bundlesize could be helpful. Threshold limit and the status message mentions the delta of the PR (doesn't track over time, though)

**Comment by wardpeet** [comment]
we could store it in S3 and sync load the data and let master write the size
