### ISSUE TITLE
Switch to cross platofrm scripts for tests

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1691]
Currently tests require bash which isn't available by default on Windows.

After #1280 is merged we should use native node.js scripts with the help of shell.js or something similar so that scripts work out of the box everywhere.

**Comment by paulirish** [comment]
To be clear we're talking about converting these four bash scripts to JS:

* lighthouse-core/scripts/run-mocha.sh
* lighthouse-cli/test/smokehouse/dobetterweb/run-tests.sh
* lighthouse-cli/test/smokehouse/offline-local/run-tests.sh
* lighthouse-core/scripts/download-chrome.sh

**Comment by XhmikosR** [comment]
Yeah, those are all the shell scripts in the repo.

Shell.js should make things much easier but since you are strict about including a new dependency you might prefer doing it in pure node.js scripts.

**Comment by patrickhulce** [comment]
we're workin' on appveyor and we'll be rewriting the smokehouse run test scripts 👍
