### ISSUE TITLE
prevent debugger statements from tripping up Lighthouse

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1694]
from @pavelfeldman 

In the `all-event-listeners` we [use the `Debugger` domain to capture parsed scripts](https://github.com/GoogleChrome/lighthouse/blob/50b9943813f4ec6661bf90f1244c705506435463/lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js#L29). However, by default a `debugger;` statement in one of those scripts will pause execution until the page load hits the timeout (and then a bunch of weird buggy stuff happens with the protocol :)

The DevTools team is adding the ability to call `Debugger.setBreakpointsActive` with `{active:false}` *before* the domain is enabled, so that any `debugger` statements are skipped.

Until that lands, `Debugger.setSkipAllPauses` with `{skip: true}` before `Debugger.enable` will also work.

**Comment by pavelfeldman** [comment]
You can just land ``Debugger.setSkipAllPauses({skip: true})`` before Debugger.enable and live with it.

**Comment by paulirish** [comment]
we no longer use Debugger domain.
