### ISSUE TITLE
Extension Error: this.handleRawError is not a function

### ISSUE THREAD

**Issue by inian** [GoogleChrome/lighthouse#1696]
**Lighthouse Version**: 1.5.1
**Chrome Version**: 56.0.2924.87
**URL**: https://demo.theteamie.com/
**Error Message**: this.handleRawError is not a function
**Stack Trace**:
 ```TypeError: this.handleRawError is not a function
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:8769:33)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by brendankenny** [comment]
arg, missed this in #1474. Thanks for reporting.

**Comment by brendankenny** [comment]
If this bubbled all the way up to the error handler it means this didn't happen from a gatherer command (it would have been caught as a gatherer error in that case) or it was in a gatherer callback accidentally outside of the promise chain or it happened from something gatherRunner was doing.

If/when this error pops up again it'll at least throw the correct call stack and we'll hopefully see what command was being run at the time.
