### ISSUE TITLE
Report generated time is always in en-US

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1703]
```
C:\Users\xmr\Desktop>@systeminfo | @findstr /B /C:"System Locale" /B /C:"Input Locale" /B /C:"Time Zone"
System Locale:             el;Greek
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+02:00) Athens, Bucharest
```

Yet the date in the reports is always in English US format.

```
Generated by Lighthouse 1.5.1 on 2/12/2017, 2:13:03 PM GMT+2
```

I find it confusing being that I'm not used to the US date format.

**Comment by paulirish** [comment]
Aye. Confirming that in https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/report/v2/renderer/util.js we always render it in en-us, though we do use the local timezone.

It started here https://github.com/GoogleChrome/lighthouse/pull/206#r60298749

AFAIK there isn't a reason why we force en-us. We should leave it as undefined to pick up the local locale.

**Comment by wardpeet** [comment]
We can now run lighthouse for your locale by using the locale option in the cli.

`node lighthouse-cli/index.js https://www.paulirish.com --locale el-GR` or run lighthouse on pagespeed insights.

@paulirish we could enable multi locale support on lighthouse-viewer so people can override the defined locale?

**Comment by brendankenny** [comment]
Yeah, confirmed that with the explicit `--locale=el` the time is now correctly formatted.

I added bullet points to the i18n umbrella bug #7238 for being able to swap the locale in the viewer and investigate looking at system info for determining the locale to use automatically.
