### ISSUE TITLE
Image Optimisation - Which Tools to Use?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#1709]
Running the latest Lighthouse build over my side I'm getting an error on one my images where there is a 2% saving on a jpg image.

Are there recommendations for what tools to use to get to this saving? At the moment I'm using "gulp-imagemin".

**Comment by brendankenny** [comment]
If we stick with @patrickhulce's current proposal, after #1635 things offering ≤ 10% potential savings won't be called out anymore, which will ease some of this.

**Comment by patrickhulce** [comment]
Great that you're already using imagemin! That should capture what we're advocating here the 2% might just be a slight difference in the encoder quality handling. This is also getting loosened a bit in #1635.

**Comment by patrickhulce** [comment]
We now give much more leeway on image encoding and explicitly state expected quality settings. 👍
