### ISSUE TITLE
manifest test fails if manifest is linked with a path

### ISSUE THREAD

**Issue by petele** [GoogleChrome/lighthouse#171]
The manifest check fails in Lighthouse if the manifest link tag starts with `/`. 

Eg: `<link rel="manifest" href="/manifest.json">` 

In this case, Lighthouse tried to retrieve `https://udacity-ud811.firebaseapp.com//manifest.json`. If you remove the `/` from the href, it works fine.

You can try this on: https://udacity-ud811.firebaseapp.com/

**Comment by paullewis** [comment]
Thanks Pete, we have a few Manifest issues we are smoothing out ATM, hopefully this will get fixed in them. I'll keep this open to make sure.

**Comment by brendankenny** [comment]
So, on master, I'm now getting
```
Lighthouse results: https://udacity-ud811.firebaseapp.com/
Will Get Add to Homescreen Prompt: 75%
 -- Has a registered Service Worker: false
 -- Manifest exists: true
 -- Manifest contains start_url: true
 -- Manifest contains icons at least 144px: true
    Found icons of sizes: 144x144,192x192,256x256,384x384,512x512
 -- Manifest contains short_name: true
 -- App short_name won't be truncated on the homescreen: true

Will Launch With A Splash Screen: 100%
 -- Manifest exists: true
 -- Manifest contains name: true
 -- Manifest contains background_color: true
 -- Manifest contains theme_color: true
 -- Manifest contains icons at least 192px: true
    Found icons of sizes: 192x192,256x256,384x384,512x512

Omnibox Matches Brand Colors: 100%
 -- Manifest exists: true
 -- Manifest contains theme_color: true
 -- HTML has a theme-color <meta>: true (#2F3BA2)

Works Offline: 0%
 -- Has a registered Service Worker: false
 -- URL responds with a 200 when offline: false

Is Secure: 100%
 -- Site is on HTTPS: true

Is Performant: 100%
 -- Has a good first meaningful paint: 100 (636.64ms)

Is Mobile Friendly: 100%
 -- HTML has a viewport <meta>: true
```
Does this look right, @petele? The extension might need updating before it gets these same results.

**Comment by petele** [comment]
Looks much better, but it does have a service worker that supports offline, so not sure why it's reporting that it doesn't.

**Comment by samccone** [comment]
Fixed it :sparkles: 

![image](https://cloud.githubusercontent.com/assets/883126/14448258/da5a0540-001b-11e6-9eb2-f7023021b0f3.png)

**Comment by paulirish** [comment]
all fixed on master these days.

**Comment by karan101292** [comment]
Lighthouse fails even after removing '/' 
My code looks like this: `<link rel="manifest" href="manifest.json" />`

I am able to locate file in browser - `http://localhost:3000/manifest.json`
I am using Rails
