### ISSUE TITLE
Extension Error: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by pquiz** [GoogleChrome/lighthouse#1713]
**Lighthouse Version**: 1.4.1
**Chrome Version**: 56.0.2924.87
**URL**: https://www.telum.mx/cambaceov2
**Error Message**: Cannot read property 'children' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'children' of undefined
    at artifacts.requestCriticalRequestChains.then.chains (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:560:62)```

**Comment by brendankenny** [comment]
This should be fixed in the latest release of the extension (1.5.1). You can navigate to `chrome://extensions/` and hit "Update extensions now" to manually update if Chrome hasn't attempted to yet.

(duplicate of #1427)
