### ISSUE TITLE
Unrecognizable character on Windows console

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1715]
So, while trying to reproduce #1702, I noticed there's still a character that's not showing up right on Windows:

![ccc](https://cloud.githubusercontent.com/assets/349621/22898139/dbca7e2c-f22e-11e6-807a-560f8512cdf1.png)

It seems it's [this](https://en.wikipedia.org/wiki/Interrobang) but I can't find where it's used in the source code.

**Comment by patrickhulce** [comment]
We don't have the CLI printer anymore 👍
