### ISSUE TITLE
Driver: Clear out runtime caches between runs

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1716]
Backend is caching remoteObjects while the `Runtime` domain is enabled. So all the event listeners, etc that we ask for are being held on to by the backend. Between runs we should clear these caches. 

While we could flip Runtime.disable then Runtime.enable between runs. There looks to be a better way:
[
`Runtime.evaluate`](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#method-evaluate) takes an optional `objectGroup` property. If we set this to `"lighthouse"` we can later just do [`Runtime.releaseObjectGroup`](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#method-releaseObjectGroup)`({objectGroup: 'lighthouse'})` in between runs to clear this out.

Doing this allows the browser to GC some objects and free up extra memory.

**Comment by patrickhulce** [comment]
Paul: "close it, terrible"
