### ISSUE TITLE
README: add note that testing and results are done locally (no remote servers)

### ISSUE THREAD

**Issue by scunliffe** [GoogleChrome/lighthouse#1719]
I searched the docs on this extension and couldn't find a clear answer.

I regularly want to use tools like lighthouse to test content loaded in the browser from a in internal (Intranet) site that contains high security information that should not ever leave my offices walls.

Are all of the tests run locally in the browser? or is some of it processed externally?

If this is all run locally in the browser, can the documentation be updated to indicate as such?

**Comment by ebidel** [comment]
> Are all of the tests run locally in the browser? or is some of it processed externally?

Yes. Lighthouse runs its audits locally in a Chrome browser installed on your machine. Nothing is beaconed or processed on a remote server.

BTW, if you're only interested in that one metric, may I suggest the performance timing api. You could log DCL after page load:

    const DCL = performance.timing.domContentLoadedEventStart - performance.timing.navigationStart;

(or `performance.timing.domContentLoadedEventStart - performance.timing.domLoading;` if you only care about the time after the main page bytes are rev'd. IOW, how long it takes for the browser to parse the document.

We'll update the docs. Let us know if you have any other questions.
