### ISSUE TITLE
Improve node programmatic API

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1722]
Brought over from discussion in https://github.com/GoogleChrome/lighthouse/pull/1721#discussion_r101157061.

The example for how to use lighthouse programmatically is quite daunting for someone just getting started. Splitting out the chrome launcher (#1176) would take us pretty far, but also making basic usage possible without having to require specific files deep within the directory structure would be great.

**Comment by gauntface** [comment]
I ended up writing a small wrapper for downloading and starting chrome before using the lighthouse node module:

https://github.com/gauntface/gf-site/blob/v3/test/utils/lighthouse-wrapper.js

More than happy to move it out to a node module if it's useful.

**Comment by patrickhulce** [comment]
Another wrinkle as noted in #1744, the lighthouse results cannot be directly saved as the artifacts have a circular structure

**Comment by brendankenny** [comment]
I believe this is mostly complete?
 - `chrome-launcher` split to own package
 - don't need to require deep files

However, dealing with report/deleting artifacts is still kind of a pain. That part could be merged into the GAR issue.
