### ISSUE TITLE
Adopt toLocaleString for all our number output

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1723]
Over in #1647, **I discovered something amazing¹**:

```js
num.toLocaleString(undefined, {maximumFractionDigits: 1});
```
basically:
![image](https://cloud.githubusercontent.com/assets/39191/22953538/77aa4268-f2c6-11e6-8c09-bdde89f12de1.png)

It's great. Thousands separator and decimal place handling all in one. Best.

We should make sure whenever we output numbers (metric values, element count, diagnostics, kb sizes, etc) we should use this to make happier numbers.

---------

¹https://www.youtube.com/watch?v=T67AewxhBaQ

**Comment by TheAlbinoPanda** [comment]
Hey ! Can I try helping out with this ? I'm new to contributing to projects , so if you could guide me through my first project, I'd appreciate it !

**Comment by paulirish** [comment]
@TheAlbinoPanda sure

to start you can look at these docs:

https://github.com/GoogleChrome/lighthouse/blob/556b9b72e729f444bb7ba59aa567d53cd11749da/readme.md
https://github.com/GoogleChrome/lighthouse/blob/556b9b72e729f444bb7ba59aa567d53cd11749da/CONTRIBUTING.md
https://github.com/GoogleChrome/lighthouse/blob/556b9b72e729f444bb7ba59aa567d53cd11749da/docs/architecture.md

you should fork the repo to your user account, then clone locally and get a build up and running with the CLI. and then you can note the numbers in the HTML report (and the "pretty" CLI output) that need to change.. and then adapt the various "formatters" to use toLocaleString as appropriate.

Once you have things looking correct locally you can push a branch to your github repo. and initiate a pull request so we can have a look.

**Comment by TheAlbinoPanda** [comment]
Awesome thank you @paulirish. I'll start working on this tonight !

**Comment by arturmiz** [comment]
Hi, I have come across this beginner issue, did some debugging how it can be fixed and I noticed that there are already some changes introduced with #2295. I followed the pattern and used this utility helper across audits which I think required use of it. I created a PR #2553 with my changes, now waiting for any feedback 🤓
