### ISSUE TITLE
Critical Request Chains doesn't represent @import chains correctly

### ISSUE THREAD

**Issue by andydavies** [GoogleChrome/lighthouse#1729]
https://blog.hospodarets.com/pure-css-import-test/ references stylesheets from other stylesheets using @import e.g. main.css imports imports1.css etc.

Tree shown in Critical Request Chains doesn't reflect this relationship

![critical request chains](https://cloud.githubusercontent.com/assets/427052/22997388/163b8e9c-f3ca-11e6-868f-0269e432f5e6.png)

Guessing this is partly due to the initiator for @import'ed resources being marked as the parser rather than being identified as CSS (as Resource Timing does)

**Comment by paulirish** [comment]
Aye. This is likely an upstream bug.

However rather than fixing this i'd rather flag if any page is using css @import. Because if they are, we have bigger problems than accuracy of the dependency chain. :)

How's that sound?

**Comment by andydavies** [comment]
Yeh, given the upstream issue definitely more sense to take a pragmatic approach and just highlight @import in general

**Comment by paulirish** [comment]
given the rescoping, this is now a dupe of #11863  :)
