### ISSUE TITLE
Extension Error: Invalid string length

### ISSUE THREAD

**Issue by ca6sno** [GoogleChrome/lighthouse#1733]
**Lighthouse Version**: 1.5.2
**Chrome Version**: 56.0.2924.87
**URL**: https://ois-mtho-sit.orchard-systems.co.uk/
**Error Message**: Invalid string length
**Stack Trace**:
 ```RangeError: Invalid string length
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9574:27)```

**Comment by paulirish** [comment]
Thanks for reporting. 

I'll close this in favor of #1798, which I just filed with more details. Thank you!
