### ISSUE TITLE
Migrate discouraged API use audits to protocol-based violation report

### ISSUE THREAD

**Issue by pavelfeldman** [GoogleChrome/lighthouse#1737]
A [patch](https://chromium.googlesource.com/chromium/src/+/dbd9d48e4e782cd4830d971f273468599d1a2125 ) has landed in Chromium that should make it easier to collect information on:
- scroll-blocking listeners
- document.write
- Notification.requestPermission calls outside of user gesture
- navigator.geolocation calls outside of user gesture

Those are reported as `verbose` console messages with the `violation` source.

**Comment by paulirish** [comment]
For reference, this landed in m58 at rev 451102. 

We can't necessarily feature detect these, but we can just check the revision of the Chrome we're connected to and branch from that.

**Comment by ebidel** [comment]
Awesome!
