### ISSUE TITLE
flakiness on first run?

### ISSUE THREAD

**Issue by ezekielchentnik** [GoogleChrome/lighthouse#1738]
I seem to always have to run the lighthouse chrome extension twice to see consistent results.  

I'm not sure if I'm doing something wrong, or if it's something buggy, or just the nature of these things.  I can provide more details on my particular pwa ... but before I do, I'm wondering if others experience this same issue?

**Comment by patrickhulce** [comment]
@ezekielchentnik which particular metrics are the flakiest in your experience?

**Comment by ezekielchentnik** [comment]
usually it seems to be:

Perceptual Speed Index   
Audit error: No screenshots found in trace
N/A
Estimated Input Latency   
Audit error: No screenshots found in trace
N/A
Time To Interactive (alpha)   
Audit error: No screenshots found in trace

**Comment by ezekielchentnik** [comment]
i've also  encountered inconsistency with 
```
Avoids Date.now() in its own scripts   
Lighthouse was unable to determine the URL of some script executions. It's possible a Chrome extension or other eval'd code is the source.
```

on subsequent runs it passes, and obviously I've scoured code to make sure I'm not going nuts as well as removed chrome plugins (like redux devtools)

**Comment by ezekielchentnik** [comment]
Before I go down a rabbit hole in debugging; any word on this?

**Comment by wardpeet** [comment]
I'll have a look somewhere today :)

**Comment by patrickhulce** [comment]
@ezekielchentnik I've experienced similar issues with those metrics on various sites but have not been able to identify a pattern in the sites which present this behavior. I would guess it's a result of a site's interaction with DevTools/Lighthouse and not a specific bug you should be looking into on your end (there are other known cases where DevTools does not properly record screenshots which this may be an extension of).

Is there a public URL you'd be willing to share? I'd be interested in collecting a list of examples for us to better diagnose the underlying issue.

**Comment by Gufsky1** [comment]
@patrickhulce thx.  here is the my public URL:  https://preact-pwa.appspot-preview.com/

the app is also listed here:  https://pwa-directory.appspot.com/pwas/5154247687536640#t=Preact%20PWA&bg=%23f1f1f1&c=%23000000

cheers

**Comment by brendankenny** [comment]
This has likely changed quite a bit (all the `debugString`s above have changed since then, at least). I'm tempted to file under #2394 now? Or whatever that "list of sites LH does poorly on" bug is

**Comment by brendankenny** [comment]
> Or whatever that "list of sites LH does poorly on" bug is

#2293 :)

**Comment by patrickhulce** [comment]
we're gonna merge this into #3600
