### ISSUE TITLE
Is it time to deprecate the CLI report output?

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1739]
Personally I won't try to read the results of the CLI output and I always reach for the HTML report.

Maybe that should be the default setup?

Thoughts?

**Comment by ebidel** [comment]
+💯 

Personally, I never use the prettyprint CLI and find it cumbersome to author and maintain audits.

Another positive is that it would remove a BUNCH of code and tests.

**Comment by patrickhulce** [comment]
+1
Also is a giant pain for trying to read the log output, maybe bring back `--view` as a way to immediately open the report without bringing up a local server?

**Comment by ebidel** [comment]
Has anyone started this? I can take some/all of the audits.

**Comment by paulirish** [comment]
I guess i technically already deprecated output=pretty. (Did so by making it non-default.)

One can still use it.. I'm thinking the CI scenario is the most likely for it to be valuable.

I'm not 100% on removing _all_ support for pretty at this point, though I do think it'd be fine to stop investing in our pretty formatters (table, crit path, etc). Those aren't worth it for us to maintain (or keep).
