### ISSUE TITLE
Unable to generate report for working site

### ISSUE THREAD

**Issue by mblayman** [GoogleChrome/lighthouse#1745]
Hi, I was excited to try Lighthouse on the production site that I work on. Unfortunately, the tool is erroring 100% of the time for me when I try to run it. Every time I run it against https://storybird.com/, I get the following message:

![image](https://cloud.githubusercontent.com/assets/636865/23073960/45fce478-f505-11e6-9eba-3491172d37fc.png)

I've tried other pages on Storybird as well as authenticated and non-authenticated. Nothing I've tried was successful.

I installed the extension today and am running Chrome 56.0.2924.87 (64-bit) on OS X 10.11.6. As a sanity check, I also attempted to restart the browser after installing the extension. As an additional check, I ran the tool against https://www.google.com/ and that worked so I have confidence that the installation of the extension is correct.

I don't know if there are any logs to inspect what went wrong so I'm not sure how to fix whatever the problem is. I'd love to use Lighthouse so any insight would be appreciated. Thanks!

**Comment by mblayman** [comment]
As a bit of extra data, I tried to disable all but 1 option and ran three separate tests for three separate options to see if the problem was related to a single test. That failed.

Then I tried to run it with *all* of the options unchecked. That failed as well.

**Comment by patrickhulce** [comment]
So sorry you're having such trouble @mblayman ! That's strange as both the CLI and extension worked perfectly for me on that site first try (also Chrome 56 on OS X). The logs of the CLI tool are a bit more verbose for this category of error if you'd like to give that a try and see if you get the same results. You can also inspect the extension itself to see more logs (during a Lighthouse run, go to `chrome://inspect#extensions` and click inspect under the Lighthouse option).

Would you be able to try your site using the npm module and see if you get the same results?

**Comment by paulirish** [comment]
Does your site redirect to a subdomain or other domain? I was saying a similar thing yesterday on the CLI with "about:version" not working but it's post redirect "chrome://version" being fine. 
Either way.. it's our bug.

**Comment by mblayman** [comment]
@patrickhulce thanks, I was unaware of `chrome://inspect#extensions`. When I ran it again, I got this in the logs:

<img width="1380" alt="image" src="https://cloud.githubusercontent.com/assets/636865/23075640/404b5b8a-f50b-11e6-87d7-9ed06682a042.png">

When I watch Lighthouse run, it seems to die every time just after the "Loading page & waiting for onload: HTTPRedirect, HTTPWithoutJavaScript."

I'll see if I can get the npm version running to check the results there.

@paulirish No, Storybird does not redirect to a different domain. Everything stays rooted at storybird.com

**Comment by mblayman** [comment]
hmm... the npm version ran fine. It's weird that Chrome would behave fine via npm, but not directly from the extension. Could a separate extension be gumming up the works? ¯\\_(ツ)_/¯

**Comment by patrickhulce** [comment]
Hmm, strange. It seems like there's no network record for the page. Just to check, are you testing with just `https://storybird.com/` or are you on some deeper route that might be using `history.pushState`?

**Comment by mblayman** [comment]
I'm only testing `https://storybird.com`. There's no push state stuff going on.

I tried turning off all extensions except Lighthouse, closed the browser, started the browser, navigated directly to `https://storybird.com`, and click the "Generate Report" button in Lighthouse.

As far as I can tell, I am running things in the most basic way I can imagine.

**Comment by paulirish** [comment]
> I tried turning off all extensions except Lighthouse, closed the browser, started the browser, navigated directly to https://storybird.com, and click the "Generate Report" button in Lighthouse.

Thanks for trying that. I was going to ask about extra extensions, as well. :)

**Comment by wardpeet** [comment]
@mblayman  just looking at some old issues but do you still have issues running lighthouse?

**Comment by mblayman** [comment]
I was successful with the node version and I'm not really using lighthouse that much so I'm fine with closing the issue.
