### ISSUE TITLE
Viewer: wrong style when error happens

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1757]
So, I tried opening a report generated from master with the viewer and naturally it generates an error. The problem is that the style is broken, see the attached screenshot.

![aaa](https://cloud.githubusercontent.com/assets/349621/23161446/cd986bac-f832-11e6-8b13-f94a9ee4a76d.png)

Setting `report-body__header` display to none fixes the issue for me.

**Comment by ebidel** [comment]
Also kill `report-body__header` and give the body some padding:

<img width="328" alt="screen shot 2017-02-21 at 9 12 16 am" src="https://cloud.githubusercontent.com/assets/238208/23180542/da969db4-f815-11e6-86bf-14c746d130ef.png">

**Comment by brendankenny** [comment]
we no longer have this style of error log in the current viewer
