### ISSUE TITLE
Report: misaligned score badges on Firefox

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1762]
I'm using Firefox 52.0 beta. See the attached screenshot:

![screen shot 2017-02-22 at 10 32 40-fullpage](https://cloud.githubusercontent.com/assets/349621/23203524/851bc9e6-f8eb-11e6-943d-787da1c2d4ef.png)

The issue seems to come from `.aggregation__header :-moz-any(.aggregation__header__score)` rule.

**Comment by narendrashetty** [comment]
@wardpeet are you fixing this? I can go ahead and send PR for it

**Comment by wardpeet** [comment]
@narendrashetty was going to work on this one but feel free to take over ;)

**Comment by narendrashetty** [comment]
@XhmikosR it seems to work perfectly fine for me in Firefox stable 51.0.1

**Comment by XhmikosR** [comment]
Definitely happens for me with Firefox 52 beta.

**Comment by XhmikosR** [comment]
v51.0.1 works as expected. v53 has the same issue too so this isn't going to be fixed soon by FF if it's a bug in the first place.

**Comment by ebidel** [comment]
Here's what I see in FF 54a1 (2017-02-28), Mac:

<img width="1143" alt="screen shot 2017-02-28 at 9 17 50 am" src="https://cloud.githubusercontent.com/assets/238208/23416214/d72e645a-fd96-11e6-8ed8-33527c945297.png">

**Comment by XhmikosR** [comment]
Still not the same as with Chrome (the badges are shifted to the  top), but again you are using a bleeding edge version and if there are fixes it will take months for them to pass to stable...

**Comment by ebidel** [comment]
Exactly. The screenshot was to confirm FF hasn't fixed the bug. So we should fix it.

**Comment by XhmikosR** [comment]
OK, I was just expressing my opinion because of the approach with the toggle button.

**Comment by narendrashetty** [comment]
@XhmikosR @ebidel I have removed the specific rule for moz and used `top`. Have a look and let me know if this works or needs any change

**Comment by XhmikosR** [comment]
Works for me from a quick look.
