### ISSUE TITLE
Expose TypeScript typings

### ISSUE THREAD

**Issue by mohsen1** [GoogleChrome/lighthouse#1773]
I see some TypeScript files here and there... is this written in TypeScript? Even if it's not, all of JavaScript code is nicely annotated (Thanks Closure Compiler!). Can you expose the typings via `typings` key in `package.json`? It would be great for TypeScript users **and** VSCode editor users thanks to [Automatic Type Acquisition](http://code.visualstudio.com/updates/v1_7#_better-javascript-intellisense)

**Comment by ebidel** [comment]
Only the [CLI](https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-cli) is written in TS atm. Everything else is closure-based JS.

Almost no one on the core team has TS experience, so we'd love your help. @samccone also loves TS. Maybe he can help.

**Comment by wardpeet** [comment]
@ebidel do we want to move?

**Comment by samccone** [comment]
The idea was to test run ts w/ the CLI to start, and then reevaluate.
I currently do not work on lighthouse as much as I initially did, so this decision is more up to the maintainers of the lib ;)

**Comment by ebidel** [comment]
Right. I don't think we want to move anything else over given the state of
the team. There doesn't seem to be much benefit in moving more to TS atm.

**Comment by wardpeet** [comment]
I agree with @ebidel but might be good to put this on the next lighthouse meeting

**Comment by devrelm** [comment]
I'd like to ask that this be revisited. I'm using chrome-launcher in a typescript project, but am getting errors because the d.ts files are not included. It should be a fairly simple change to the tsconfig and package.json to make sure that those are produced and published — I'm more than willing to put in a PR (in fact, I'm in the process of forking & cloning the repo as we speak).

**Comment by samccone** [comment]
Hey @devrelm so, you can directly require the typescript code for the launcher (no need for d.ts), will this work for you?

```ts
import {launch} from 'chrome-launcher/chrome-launcher';
```

**Comment by devrelm** [comment]
@samccone Yeah, that'll work. Another alternative could be renaming `chrome-launcher.ts` to `index.ts`, or (to not break backwards compatibility with people already implementing your solution)  create a separate `index.ts` containing:

```
export * from './chrome-launcher';
```

Then update "main" in the `package.json` to point to index.js and everything _should_ work, at least for those who have their tsconfig set up with `"moduleResolution": "node"`.

Anyway, it's not a pressing issue now that I know the workaround.

Thanks!

**Comment by paulirish** [comment]
since folks have run into this twice in two days, i think doing the above makes sense. that work for you, @samccone?

**Comment by paulirish** [comment]
@devrelm the #2513 fix is shipped in chrome-launcher@0.1.3
thx very much for the suggestion!

**Comment by nicky-lenaers** [comment]
@paulirish @wardpeet @ebidel This is great. I can now use the typed interfaces for `chrome-launcher`. However, I use lighthouse to [programmatically test output scores.](https://github.com/GoogleChrome/lighthouse/blob/HEAD/docs/readme.md#using-programmatically) I came across [lighthouse-mocha-example](https://github.com/justinribeiro/lighthouse-mocha-example), but that's only available as a Docker container. I'm looking for a more integrated solution for rapid local development. So I implemented a `test-pwa-score.ts` file (ran with [ts-node](https://www.npmjs.com/package/ts-node)) that looks a lot like [the test file from the official Angular repository](https://github.com/angular/angular/blob/master/aio/scripts/test-pwa-score.js). Regarding this section:

```ts
const flags = { };

const scores = {
  'pwa': 90,
  'performance': 90,
  'accessibility': 90,
  'best-practices': 90
};

launchChromeAndRunLighthouse('http://localhost:8000', flags, null)
.then((results: any) => {
  results.reportCategories.forEach((cat) => {

    if (scores[cat.id]) {

      if (cat.score < scores[cat.id]) {
        console.log(`Score for '${cat.id}' expected to be ${scores[cat.id]}, but got ${cat.score}`);
      } else {
        console.log(`Score for ${cat.id} OK, ${cat.score} satisfies theshold ${scores[cat.id]}`);
      }
    }

  });
});
```
The `results` parameter in the Promise callback contains a huge JSON file, containing quite some levels of objects and arrays. Currently I am forced to type this as `any`, because I don't have an available interface for this to use with TS. The object is way too big to provide a quick interface myself.

Will this be available anytime soon?

**Comment by patrickhulce** [comment]
@brendankenny now that we've got everything nicely typed up what do you think the best strategy is?

It seems like there's different levels we could go with this that all have different exposure risk of breaking changes. I'd be inclined to go as small as possible and expose some LHR-lite style types for the response.

**Comment by arnold-fingerfood** [comment]
Thanks for bumping it back up, Patrick.
https://github.com/GoogleChrome/lighthouse/issues/7089

**Comment by brendankenny** [comment]
> I'd be inclined to go as small as possible and expose some LHR-lite style types for the response.

Yeah, agreed with this. We can start with the LHR and the callable interface to `lighthouse-core/index.js` and move on from there as needed (e.g. the primary audit interfaces may be helpful for anyone writing plugins)

**Comment by taji** [comment]
Sorry, is this fixed in lighthouse 4.1.0?   Looking at this project: 

https://github.com/AndrejsAbrickis/lighthouse-azure-devops

as described here:

https://medium.com/@andrejsabrickis/continuously-audit-web-apps-performance-using-google-s-lighthouse-and-azure-devops-3e1623372f79

He's using  an alpha version of 4.0.0 in his package.json:

```"lighthouse": "^4.0.0-alpha.2-3.2.1" ```

and he's importing as so:

```import lighthouse from 'lighthouse/lighthouse-core';``

But this isn't working in 4.1.0.  I'm thinking these alpha changes weren't rolled into the release?

**Comment by patrickhulce** [comment]
@taji that "alpha" version is actually identical to version `3.2.1`

In v4, you should be able to achieve the same effect by replacing

```js
/// <reference path="./node_modules/lighthouse/typings/externs.d.ts"/>
```
with
```js
/// <reference path="./node_modules/lighthouse/types/externs.d.ts"/>
```

We're hoping to offer a better solution sometime in the future that doesn't require this hacky reference though.

**Comment by alekseykulikov** [comment]
TS typing would be especially useful for plugins!

I tried hard to make it work in https://github.com/treosh/lighthouse-plugin-field-performance
But it's not possible without `"noImplicitAny": false` which breaks the purpose of types.

**Comment by ali-habibzadeh** [comment]
2020. Any updates?

**Comment by mb-jenks** [comment]
Also interested in this. Any way to export the current types in the repo or put into an @types package?

**Comment by wardpeet** [comment]
Moving to types repo gives us extra maintenance overhead so I think we don't want to go that route but exposing it from our package seems a good idea

**Comment by mohsen1** [comment]
if your types are not generated from code, I suggest keep the types in DefiantlyTyped. Almost every lib that decided to publish handwritten types has regretted it.

**Comment by connorjclark** [comment]
I don't think we were ever going to write types manually. We were waiting for [TS 3.7](https://voxpelli.com/2019/10/use-type-script-3-7-to-generate/) to generate types from JSDoc.

@brendankenny should we move on this now?

**Comment by brendankenny** [comment]
> I don't think we were ever going to write types manually. We were waiting for [TS 3.7](https://voxpelli.com/2019/10/use-type-script-3-7-to-generate/) to generate types from JSDoc.
> 
> @brendankenny should we move on this now?

it was still buggy the last time I tried it, but maybe it works now? We have a large amount of stuff we would probably not want to have in end-user types, but maybe there's also a nice way to do that.

We also need to move off types in a global namespace (we need to do that for a few reasons, actually), but I wasn't sure how well that would go over with y'all :)

**Comment by connorjclark** [comment]
> We also need to move off types in a global namespace (we need to do that for a few reasons, actually), but I wasn't sure how well that would go over with y'all :)

What would that look like? For example, to reference `LH.Artifacts`, would we require a module `artifacts.js`, or `lh.js` which would export `Artifacts`? I'm fine with either, btw.

Sounds like we are a few steps removed from doing this properly. For now, let's just upgrade to the latest TS.

**Comment by phenomnomnominal** [comment]
Would love to consume these types, is there anything I can do to help move this along?

**Comment by ali-habibzadeh** [comment]
Any updates?

**Comment by ali-habibzadeh** [comment]
Anything

**Comment by pan-alexey** [comment]
same issues

**Comment by Pagan-Idel** [comment]
2022 any updates on fully functional typescript'ed lighthouse?

**Comment by rdadoune** [comment]
Create a `lighthouse.d.ts` file and add this to it:
```typescript
/// <reference types="lighthouse/types/global-lh" />

declare module 'lighthouse' {
  function lighthouse(
    url: string,
    options: Partial<LH.CliFlags>,
  ): Promise<LH.RunnerResult>;
  export = lighthouse;
}
```

Then in your `tsconfig.json` file add `lighthouse.d.ts` to the `include` option. VSCode and `tsc` will pick it up automatically from there. If you also use `ts-node`, then you will also need to add `lighthouse.d.ts` to your `files` array, it will complain if you don't, I'm not sure why. 

```json
{
  "compilerOptions": {
    /* ... */
  },
  "files": ["lighthouse.d.ts", /* ... */],
  "include": ["lighthouse.d.ts", /* ... */]
}
```
