### ISSUE TITLE
Print -> Save as PDF : Pages truncated

### ISSUE THREAD

**Issue by ashrithkulai** [GoogleChrome/lighthouse#1780]
Click on export and select Print, in the chrome dialog chose save as PDF option. 
It is showing only 6 pages. 
The content after **"Using bytes efficiently"** is truncated in the saved pdf.

**Comment by wardpeet** [comment]
Thanks for reporting!

**Comment by ebidel** [comment]
I have a sneaky suspicion[ expanding the `<details>` before print](https://github.com/GoogleChrome/lighthouse/blob/9ac57cb05efd5b0aba6684047382fff670860ca0/lighthouse-core/report/scripts/lighthouse-report.js#L204-L221) is not fully working as expected. Especially as the report grow. 

Chrome appears to be generating the PDF before everything is expanded.
