### ISSUE TITLE
Lighthouse `npm` package up-to-date?

### ISSUE THREAD

**Issue by thomasdigby** [GoogleChrome/lighthouse#1782]
There are many recent changes visible in this repo that aren't showing up in the latest `npm` package, for example, the entire `byte-efficiency` directory is missing. https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/audits/byte-efficiency

I've set-up a local node script running Lighthouse, passing through a custom config (copied from `default.json`) as per the [README](https://github.com/GoogleChrome/lighthouse#custom-configurations-for-runs).

However I keep running into the following missing audit error, this happened with a bunch of missing audits not just `chrome-console-messages`
```
Error: Unable to locate audit: chrome-console-messages (tried to require() from '/private/var/www/perf-testing/node_modules/lighthouse/lighthouse-core' and load from '/private/var/www/perf-testing/chrome-console-messages')
```

**Comment by wardpeet** [comment]
No npm is now at 1.5.1 and is created 17 days ago.
To see a comparison: https://github.com/GoogleChrome/lighthouse/compare/3043cc3732bd6b9cfbc02d96579a6f21c86de08b...master

You can always do a git clone and `yarn/npm link` and use it. Another approach can be `npm install GoogleChrome/lighthouse`
