### ISSUE TITLE
TTI Audit fails on sites that do an amazing job

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1784]
Because we look for a 500ms window after fMP where the main thread isn't too busy, sites that do [an incredible job](https://preact-pwa.appspot-preview.com/) of loading quickly can fail the TTI audit (5/20 times on my machine) because the trace was closed too quickly. The effect will be even more extreme for those running on localhost without throttling.

Naive solution: set a 500ms timeout before closing the trace to ensure there's enough time at the end for the window to exist.

Example trace (there's 488ms after first paint): https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://dl.dropboxusercontent.com/u/54768288/preact-pwa.appspot-preview.com_2017-02-27_10-19-53-0.trace.json

**Comment by ebidel** [comment]
Somewhat related. Should we throw TTI in the user timings so it shows up in the trace?

![screen shot 2017-02-27 at 11 07 51 am](https://cloud.githubusercontent.com/assets/238208/23375390/137af000-fcdd-11e6-8ac8-fdbd8c5570a0.png)

**Comment by paulirish** [comment]
@eric, it would normally. just isn't in here as the TTI audit failed to
complete.​

**Comment by ebidel** [comment]
of course :p

**Comment by tdresser** [comment]
What heuristic do we use for how long we should keep recording the trace?

**Comment by paulirish** [comment]
@tdresser most of it is here: https://github.com/GoogleChrome/lighthouse/blob/46534830cc10df7840494edbe70bf5c607693266/lighthouse-core/gather/driver.js#L344-L466

essentially:

* both of these:
  * window onload fies
  * network idle - defined as there are no inflight net requests (from renderer POV. (Also, websocket, etc currently isn't filtered out)
* killswitch: if we're still waiting for those two at 25s after navigation, then just end the trace.
