### ISSUE TITLE
[suggest] move manifest "short_name" and "display" audits to "design is mobile friendly"

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#1787]
It looks like `Manifest's short_name won't be truncated when displayed on homescreen` and `Manifest's display property is set` were moved out of the `Installed web app will launch with custom splash screen` category (to a generic `other` category). `Other` categories bother me a lot, and are usually a cue to take another look at the IA.

I think these both can be moved to `Design is mobile-friendly` category. `short_name` is a pretty good fit. `display` less so, but still close enough

**Comment by brendankenny** [comment]
I believe obsolete due to Lighthouse 2.0 report
