### ISSUE TITLE
"cache contains start_url" intentionally missing from report?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#1788]
Was this audit disabled?

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/cache-start-url.js

Pretty sure it never shows up in reports

**Comment by paulirish** [comment]
yup. https://github.com/GoogleChrome/lighthouse/commit/f444703f115ce7cc1fa9f635b7092e3a25545665

currently unmaintained code.
the audit was unreliable so we just disabled it and left the code to rot. :) 

probably should remove entirely. good find

**Comment by ebidel** [comment]
@kaycebasques how do we better communicate changes like this to you for doc updates?

**Comment by brendankenny** [comment]
fixed by #2040 and follow ups
