### ISSUE TITLE
Chrome Speed Metrics - align with latest TTI definition

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#1800]
This issue is to track aligning Lighthouse's implementation of TTI with the latest draft version proposed by the Chrome Speed Metrics team (at a time when we feel comfortable making that change).

Change in definition: Google internal doc defining [firstInteractive](https://docs.google.com/a/google.com/document/d/1jbvwxj_GJtiTTqFM8dsVzCIy5XeKL5qtIAvuimcXb1o/edit?usp=drive_web)

The best definition so far was 'firstInteractive-FMP-ReverseSearchFromNetworkFirstInteractive', which does the reverse search from network first interactive.

WebPageTest [definition](https://github.com/WPO-Foundation/webpagetest/blob/master/docs/Metrics/TimeToInteractive.md) (closer to the above) from Pat Meenan

cc @tdresser

**Comment by tdresser** [comment]
@deepanjanroy

**Comment by paulirish** [comment]
done. we now employ both TTFI and TTCI.

we're deprecating the classic lighthouse definition of TTI
