### ISSUE TITLE
Fails to parse manifest in UTF-8 encoding

### ISSUE THREAD

**Issue by zmandel** [GoogleChrome/lighthouse#1811]
Hi. I believe this used to work OK in the past. Today I ran lighthouse on my PWA and had lots of errors related to failing to parse my manifest (Error at position zero). The manifest is correct, I verified it arrives OK using the network pane, with the intended format (UTF-8 with signature).

I changed back the manifest encoding to Windows and now lighthouse parses it OK (and my site again has 100/100 :)

**Comment by patrickhulce** [comment]
Might be related to https://github.com/GoogleChrome/lighthouse/issues/1702?

**Comment by wardpeet** [comment]
I'm closing this in favor of #1702
