### ISSUE TITLE
Chrome extension fails on specific-port pages

### ISSUE THREAD

**Issue by andrey-git** [GoogleChrome/lighthouse#1816]
I'm trying to run Lighthouse Chrome extension 1.6.0 on a site served at a non-standard port:
`https://mydomain.com:8123` (It's a home-assistant instance)

When lighthouse tries to load the **http** version `http://mydomain.com:8123` it stops as that URL gets
`The connection was reset.`  (Python aiohttp server with SSL socket on port 8123)

This happens no matter which checks I have selected in the options.

Would it be possible to either add an option not to make the `http` connection at all or change lighthouse to fail it gracefully?

**Comment by brendankenny** [comment]
possibly #2784

**Comment by patrickhulce** [comment]
merging into #1978
