### ISSUE TITLE
Tests failure with latest master

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1817]
https://ci.appveyor.com/project/paulirish/lighthouse/build/364

Noticed it when I rebased a branch of mine so I restarted the master branch build et voilà.

**Comment by patrickhulce** [comment]
@XhmikosR that looks like a link for a PR not master ;)

looks like the [real latest master failure](https://ci.appveyor.com/project/paulirish/lighthouse/build/364/job/7vmqjofpine4qrcf) was a flake on chromestatus removing a class from their biggest element, maybe we shouldn't be too reliant on the smoke test URLs changing 🤔

**Comment by XhmikosR** [comment]
https://ci.appveyor.com/project/paulirish/lighthouse/build/364

**Comment by paulirish** [comment]
fixed by #1824
