### ISSUE TITLE
Report: template is missing table/card/urllist formatters

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1820]
after running:

    npm run install-all
    npm run build-all

and running a report, we're missing the extended info `<details>` in audits. 

<img width="596" alt="screen shot 2017-03-06 at 9 26 18 am" src="https://cloud.githubusercontent.com/assets/238208/23618849/f88ffa02-024e-11e7-9718-f4bb585c0247.png">

@paulirish @patrickhulce can one of you guys take a look? I'm OOO until Wed.

**Comment by patrickhulce** [comment]
yeah I'll look into it @ebidel

**Comment by patrickhulce** [comment]
Looks like it's introduced by #1752, but not sure exactly what the fix is yet. 
Might just want to revert for now, so we can take our time digging @paulirish @sendilkumarn? My guess would be the precompiled doesn't play well with the `(lookup . name)` call

**Comment by patrickhulce** [comment]
However, the critical request chains formatter seems to work fine still, so might just be a simple fix we can patch to add the other formatters.
