### ISSUE TITLE
Extension: support disable device emulation flag

### ISSUE THREAD

**Issue by sowmyamanusani** [GoogleChrome/lighthouse#1822]
When I do generate report , it is always opening mobile version of the page however I entered page in desktop version. How can I change the settings to open a desktop version but not mobile

**Comment by patrickhulce** [comment]
@sowmyamanusani you can use the `--disable-device-emulation` flag on the CLI to run lighthouse without mobile emulation

**Comment by sowmyamanusani** [comment]
I am using google chrome plugin. I do not see any option to disable that mobile emulation

**Comment by patrickhulce** [comment]
Not all options available on the CLI are available in the extension yet, though it's a good first bug if you're so inclined :)

**Comment by ZZhaoTireless** [comment]
I would like to fix this.

**Comment by ZZhaoTireless** [comment]
@patrickhulce Could you tell me which file is responsible for the flag in extension folder? I did try to find the way to add flag in extension but I had no clue. I will be glad to help if there is a little hint. Thanks!

**Comment by Pines-Cheng** [comment]
That's cool!

**Comment by patrickhulce** [comment]
closing as dupe of #2838
