### ISSUE TITLE
Reevaluate stronger CSP for extension; remove `unsafe-eval`

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1823]
With the move to precompiled templates in #1752, we should be able to enable stronger CSP protection for the extension. At the least we can hopefully now remove [`unsafe-eval`](https://github.com/GoogleChrome/lighthouse/blob/d0f1f73999ba97339e0d0c78dc8be74f16bb3b60/lighthouse-extension/app/manifest.json#L31), but it would be nice to do a quick audit while in there to see what other protections we could enable/more strictly enforce.

**Comment by swagasoft** [comment]
Hey, I will like to take care of this, can you give me a hint on how to go about this?
