### ISSUE TITLE
Expose "Report issue" next to audit/gather failures.

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1825]
Now that we catch all non-fatal errors, it means that any exception during a gatherer or audit is caught and the user doesn't get the sweet github [`buildReportErrorLink()`](https://github.com/GoogleChrome/lighthouse/blob/07b8d3f16f39e2fd259261a39939682db6def510/lighthouse-extension/app/src/popup.js#L62-L89) action.

One option is we could surface such a link next to the red debugString in the report, to let the user file any bug leading to this error state.

This is a decent compromise until we have exception tracking in the wild.

**Comment by vinamratasingal** [comment]
Closing in favor of the umbrella issue.
