### ISSUE TITLE
Allow cli option to run specific audits

### ISSUE THREAD

**Issue by pedro93** [GoogleChrome/lighthouse#1828]
The title says practically everything. I don't think it is as of right now possible to tell lighthouse to run specific audits, is this something in the roadmap or not even considered? 

My use case is to use [pwmetrics](https://github.com/paulirish/pwmetrics) to have a simple and easy to obtain performance metrics. 

Having the option to select which ones I want, would further help me personalize the output to my situation. It is possible to filter out the results from [pwmetrics](https://github.com/paulirish/pwmetrics) and [lighthouse](https://github.com/GoogleChrome/lighthouse) but having an option directly at the source would be simpler :)

Thoughts?

**Comment by cheshrkat** [comment]
+1, although would also like better UI for re-running a single audit in the extension too :)

**Comment by wardpeet** [comment]
you have the `--perf` option which runs the following audits
* First meaningful paint
* speed index
* Estimated input latency
* Time to interactive
* user timings
* screenshots
* Critical request chains
* Unused css rules
* Uses optimized images
* Uses responsive images
* Dom size
* link blocking first paint
* script blockign first paint
see [perf.json](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/perf.json#L27-L41)

If that doens't fit your needs, you can create your own config.json and run it with `--config=<path to config>`

**Comment by paulirish** [comment]
In the short term, creating a custom config.json is a great solution.

In the medium term (next month or so) we plan to allow easy whitelisting of audits to run. In this case we'll want to optionally support culling the aggregations so a report can be created.

**Comment by brendankenny** [comment]
custom config with safe and block lists have been added. More info here: https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md#example-1
