### ISSUE TITLE
SW updating can cause hangs

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#183]
In some cases you can see this kind of output from the extension:

```
Page.frameStartedLoading Object {frameId: "59994.2"}
background.js:87 Network.requestWillBeSent Object {documentURL: "https://voice-memos.appspot.com/", frameId: "59994.2", initiator: Object, loaderId: "59994.45", request: Object…}
background.js:87 Network.loadingFailed Object {canceled: true, errorText: "", requestId: "59994.74", timestamp: 275573.705317, type: "Document"}
background.js:87 Page.frameStoppedLoading Object {frameId: "59994.2"}
background.js:87 Page.frameStartedLoading Object {frameId: "59994.2"}
background.js:87 Network.requestWillBeSent Object {documentURL: "https://voice-memos.appspot.com/", frameId: "59994.2", initiator: Object, loaderId: "59994.46", request: Object…}
background.js:87 ServiceWorker.workerVersionUpdated Object {versions: Array[1]}
```

The page seems to hang on `ServiceWorker.workerVersionUpdated`, and `Page.loadEventFired` never seems to fire. When this happens the load spinner stays on, and if you go into chrome://serviceworker-internals and try and unregister the SW it hangs. Not sure if our bug or Chrome's here.

**Comment by paullewis** [comment]
Interestingly if #179 happens, then this will happen immediately after. Which is to say if the XHR doesn't give back a 200 (for something with a valid SW) then when you try and run the extension or the CLI it will hang as described above.

**Comment by paullewis** [comment]
Annnnnnnd here's a repro:

1. Launch a new instance of Chrome
2. Visit https://voice-memos.appspot.com
3. Open a new tab to chrome://serviceworker-internals
4. Stop the SW for Voice Memos
5. Run the extension. Note #179 
6. Ask it to reload and get perf data. Chrome hangs.

**Comment by paullewis** [comment]
FWIW I can't repro this "directly" via DevTools itself. Not sure how I figure out what commands its sending.

**Comment by paullewis** [comment]
Looks like `Page.navigate` is the issue. Using `Page.reload` resolves the issue, though it makes our code more fiddly because we now need to figure out whether the Chrome instance we're talking to is blank or not.

**Comment by samccone** [comment]
A really interesting side effect here is the fact that when we issue a Page.reload it prevents the service worker from taking over... it is very interesting...
