### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by pjutard** [GoogleChrome/lighthouse#1834]
**Lighthouse Version**: 1.6.0
**Chrome Version**: 56.0.2924.87
**URL**: https://app.mural.ly/
**Error Message**: You must provide a url to the runner
**Stack Trace**:
 ```Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13600:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14685:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14711:18)```

**Comment by ebidel** [comment]
Looks like https://github.com/GoogleChrome/lighthouse/issues/1214 may not have addressed the problem entirely. As Paul mentioned, it's a hard one to repro and debug.

**Comment by awebdeveloper** [comment]
another duplicate bug https://github.com/GoogleChrome/lighthouse/issues/1819

**Comment by patrickhulce** [comment]
@centinel3 As a workaround are you able to successfully run against your site using the CLI?

**Comment by patrickhulce** [comment]
huge insight from @ev1stensberg in https://github.com/GoogleChrome/lighthouse/issues/2657#issuecomment-313866220

> FYI this happens if your initial URL fails and you try to rerun the extension straight away.

**Comment by patrickhulce** [comment]
more info from #2684 

> Always gets stuck on the HTTP Redirect test

**Comment by ev1stensberg** [comment]
Could I fix this @patrickhulce ?

**Comment by patrickhulce** [comment]
@ev1stensberg yeah that'd be awesome thanks!

**Comment by brendankenny** [comment]
@ev1stensberg would you mind writing up a few notes on what you plan to do before you start?

It's not clear to me, at least, what the root cause is or how best to fix it :) e.g. https://github.com/GoogleChrome/lighthouse/issues/1834#issuecomment-314174975 from above seems helpful for tracking it down, but doesn't give a lot of insight on its own into what needs fixing

**Comment by ev1stensberg** [comment]
Sure. I was planning to begin with this on monday, if that's fine? I've got an hypothesis now and that is that whenever the initial run fails ( first time you run the extension ) , the second time won't run properly, as it got stuck somewhere in the first instance. Doing a repro, which will give me more information. I get this pretty bug pretty often on my computer, so it's pretty easy to track down for me.

**Comment by ev1stensberg** [comment]
Actually, lemme show you @brendankenny @patrickhulce : 

https://www.youtube.com/watch?v=G3_EnydKi6A&feature=youtu.be

**Comment by ev1stensberg** [comment]
Makes my hypothesis wrong, it's stuck on HTTP Redirect.

**Comment by sambokai** [comment]
running into this issue as well..

**Comment by paulirish** [comment]
tracked by #5668 now.
