### ISSUE TITLE
Chrome version compatible with the extension

### ISSUE THREAD

**Issue by elabaume** [GoogleChrome/lighthouse#1842]
Hello,

The page https://developers.google.com/web/tools/lighthouse/ mentions that the lighthouse extension is compatible with Chrome 54 and above, but the extension page https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk tells me I need Chrome 56

**Comment by paulirish** [comment]
cc @kaycebasques

**Comment by brendankenny** [comment]
Maybe we should just start writing "stable Chrome" or the latest release or whatever so we don't have to keep updating the readme and various articles. Chrome itself will let folks know if they need to update.

**Comment by XhmikosR** [comment]
@brendankenny: that is what I wanted to suggest the other time v56 hit stable.

**Comment by ebidel** [comment]
ping @kaycebasques

**Comment by kaycebasques** [comment]
ok ok i fix

**Comment by kaycebasques** [comment]
The Node module also requires a specific version of Node. I guess I'll just link to the README and tell them to check there for which version of Node to install...

**Comment by brendankenny** [comment]
> The Node module also requires a specific version of Node. I guess I'll just link to the README and tell them to check there for which version of Node to install...

At least for now we're committed to using the [Node Long Term Support release](https://github.com/nodejs/LTS). You can also link to those docs which lists the current LTS release.

**Comment by kaycebasques** [comment]
fixed in https://github.com/google/webfundamentals#4352

**Comment by zahersi** [comment]
thanks

**Comment by zahersi** [comment]
thnks

**Comment by aalmekbel** [comment]
Great

**Comment by DefaaAbdullah** [comment]
we should just start  writing  the latest release "stable Chrome"

**Comment by adas121** [comment]
Excellent

**Comment by issamarmas** [comment]
good

**Comment by in22022** [comment]
Excellent job

**Comment by MauricioDeveloper** [comment]
good job !

**Comment by jjopatton** [comment]
Fantastic!

**Comment by LibyaGhoul** [comment]
Udacity People where are you

**Comment by paulirish** [comment]
Just to cut down on emails to everyone involved, I'm locking this issue. 😆 

❤️z and hugs to everyone.

**Comment by saleem-faeq** [comment]
A very good topic

**Comment by CherietSidAli** [comment]
bravo

**Comment by gabrielcaiana** [comment]
Very Good

**Comment by jubrannasser** [comment]
mype

**Comment by m-hemdan** [comment]
very good

**Comment by AbdelhakBoumezrag97** [comment]
for Teacher in Udacity : 
         Pythonier =Teacher + " think you for these courses" 
         print "from Abdelhak to " + Pythonier

**Comment by jacfuu1** [comment]
very good teaching

**Comment by jacfuu1** [comment]
i got new way of learning anything
thanks

**Comment by cmartman** [comment]
❤️ ... Cheers!

**Comment by AndreAgostinhoKumulus** [comment]
Cheers!

**Comment by nimraalam007** [comment]
testing comments - yay Udacity

**Comment by EslamGohar** [comment]
Hello!

**Comment by tt2g89** [comment]
Udacity

**Comment by carloswilsonperez** [comment]
Hello!

**Comment by dil2743** [comment]
udacity

**Comment by adas121** [comment]
Hello

**Comment by connorjclark** [comment]
internet's daily reminder why we can't have nice things. sorry.
