### ISSUE TITLE
Estimated Input Latency doesn't work on Chrome 57

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1848]
Works if I use the latest nightly from `https://download-chromium.appspot.com/dl/Win?type=snapshots`.

So, my question is, if this isn't supposed to be ready should it be taken into account for the score?

**Comment by patrickhulce** [comment]
Works fine on Chrome stable (57) for me. EIL isn't the soundest/most reliable of audits though in general, is there a specific URL that always fails for you?

**Comment by XhmikosR** [comment]
Weird, for me it works as long as I switch to the latest Chromium version but it might be what you say.

I saw this issue a lot of times when testing `https://mpc-hc.org/`.

**Comment by patrickhulce** [comment]
Hmmm, I'm 0/5 on repro for that URL. I'm going to chalk it up to the general flakiness (#1738) we experience with this metric, but if you have more specific errors or trace information please share!

**Comment by XhmikosR** [comment]
Well, I can repro 2/3 times. Anyway, thanks for the info.
