### ISSUE TITLE
Lighthouse vs. PageSpeed Insights

### ISSUE THREAD

**Issue by hightechguy** [GoogleChrome/lighthouse#1854]
Hi,

Playing with Lighthouse and trying to follow the guidelines, I've taken two CSS files off the HTML code. I.e. instead of inline CSS, made two calls to the preloaded via <link rel='preload' filename.css> CSS files.

Lighthouse is happy, but PageSpeed Insights is just the opposite: "Eliminate render-blocking JavaScript and CSS in above-the-fold content"

Would you recommend to ignore the last?

Thanks!

**Comment by patrickhulce** [comment]
Awesome you're using both to boost your page speed! Could you clear up what you mean by "made two calls to the preloaded via CSS files"?

Inline CSS should have been fine by Lighthouse in the first place. Have you switched them to <link rel="stylesheet"> or <link rel="preload" as="style" onload="this.rel='stylesheet'">?

**Comment by TrurlMcByte** [comment]
```<link rel="preload"``` not working in Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1222633)

**Comment by hightechguy** [comment]
Hi, patrickhulce

The situation before the change:
<html>
<head><style> /* All CSS comes here inline */ </style></head>
<body>
....

After the change:
<html>
<head><style>
	<link rel="stylesheet" type="text/css" href="style1.css" />
	<link rel="stylesheet" type="text/css" href="style2.css" />
</style></head>
<body>
....

Both style1.css & style2.css have been preloaded using HTTP Headers:
Link: <https://example.com/style1.css>; rel=preload; as=style
Link: <https://example.com/style2.css>; rel=preload; as=style

As I said before Lighthouse did like the chance. I guess users should benefit from it too, unless they are FF users (see the bug report above). 
PageSpeed Insights is down about 20(!) points, complaining "Eliminate render-blocking JavaScript and CSS in above-the-fold content". What speed optimization strategy would you recommend?

HTTP2 turns some optimization guidelines upside down, so what testing tool should we use if we have HTTP2 server? Is PageSpeed Insights good for HTTP and Lighthouse for HTTP2?

Thanks!

**Comment by patrickhulce** [comment]
Ah, so those are indeed render-blocking even though you're preloading them which is probably why tools are complaining. (did you mean to put them inside `<style>` though? Because then they shouldn't be valid links :) ) 

The best recommendation that should satisfy both PageSpeed and Lighthouse is to *inline* all critical CSS necessary to render just the above-the-fold content, and defer all other stylesheets using another method such as injecting them with script or [a similar strategy](https://github.com/filamentgroup/loadCSS).

**Comment by hightechguy** [comment]
Hi, patrickhulce

Sure <link rel="stylesheet" ... are outside <style>... typo....

Thanks a lot for the advice,
hightechguy

**Comment by irfanhussain77** [comment]
Is there any lighthouse plugin for WordPress?
