### ISSUE TITLE
Lighthouse score varies 

### ISSUE THREAD

**Issue by AswathyNath** [GoogleChrome/lighthouse#1859]
Hi team,

Could you please checkout the consistency of score, each time different score is showing.
https://googlechrome.github.io/lighthouse/viewer/?gist=0732717acb7fe04807e05ef850712970#progressive-web-app

this is our website
http://fuzecaresystem.com/

I have raised same issue on this ticket: 
https://github.com/GoogleChrome/lighthouse/issues/1815

**Comment by wardpeet** [comment]
i'm going to close this, found the bug. Trying to fix it but i'll use the other issue as reference
