### ISSUE TITLE
Extension Error: Cannot access contents of the page. Extension manifest mu...

### ISSUE THREAD

**Issue by stayshungry83** [GoogleChrome/lighthouse#1863]
**Lighthouse Version**: 1.6.0
**Chrome Version**: 56.0.2924.110
**URL**: data:text/html,chromewebdata
**Error Message**: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
**Stack Trace**:
 ```Error: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
    at Object.chrome.debugger.attach._ [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9244:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ebidel** [comment]
Lighthouse needs a real URL for testing. Were you just seeing if a data url would work?

**Comment by paulirish** [comment]
i believe `data:text/html,chromewebdata` is the URL of the dino offline page. So it's possible the run was interrupted and the dino page was up. and then the run was started again, and URL was never reset.

**Comment by ebidel** [comment]
If that's the case, it sounds related to https://github.com/GoogleChrome/lighthouse/issues/1091#issuecomment-292580868. Runs are being interrupted and we're not resetting state properly.
