### ISSUE TITLE
Entire trace was found to be busy. Audit: Key time-to-interactive

### ISSUE THREAD

**Issue by pedro93** [GoogleChrome/lighthouse#1869]
__Software__:
Chrome version: Chrome Canary v. 59.0.3043.0  (latest version as of March 16 2017)
Lighthouse version: 1.6.0
OS: Windows Server 2012 64 bit.
URL being tested: https://github.com (any url so far tested gives same error)

__Error__: Entire trace was found to be busy. Audit: Key time-to-interactive
![screen shot 2017-03-16 at 10 26 47](https://cloud.githubusercontent.com/assets/3718654/23991963/16fe1fa0-0a33-11e7-9430-4500fbc00801.png)

Running lighthouse through pwmetrics for run automation. Consistent error, not a 1 run occurence.

__Edit__:
![screen shot 2017-03-16 at 11 03 44](https://cloud.githubusercontent.com/assets/3718654/23993389/42729fee-0a38-11e7-8405-b5cfc13ec6f8.png)

When trying to just run lighthouse with an output-path specified no data is put onto file.
HTML report shows the same error:

![screen shot 2017-03-16 at 11 03 08](https://cloud.githubusercontent.com/assets/3718654/23993355/28e3a78a-0a38-11e7-891e-96d61f8e7bae.png)

**Comment by patrickhulce** [comment]
No longer use this version of TTI :)
