### ISSUE TITLE
Lighthouse fails report generation after running some subset of tests.

### ISSUE THREAD

**Issue by davmillar** [GoogleChrome/lighthouse#1877]
I used Lighthouse with success on the localhost version and stage version of my app. Now that the app is live, I tried running Lighthouse on the live edition. After a subset of tests run, the test stops with the following message:

> Unable to load the page. Please verify the url you are trying to review.

The last test item that appeared to be running I think was 'HTTP Redirect'.

Stage: https://beta.davesmapper.com
Prod: https://davesmapper.com

**Comment by wardpeet** [comment]
can you give us some more context.

What version of lighthouse are you using?
Are you running the cli or the extension?
You're talking about a subset, do you have custom config?

**Comment by davmillar** [comment]
Chrome extension v 1.6.0.
I'm using the default configs. By subset I mean that I can watch as the tests are running and the browser resizes and navigates while performing the tests, and I believe  'HTTP Redirect' was the last thing mentioned in the extension flyout before reverting to showing the 'Generate Report' button and the message in my original post.

**Comment by patrickhulce** [comment]
Is the behavior still occurring for you? 

The site exhibits some strange behavior during offline pass (I'm guessing a critical request is still being attempted which causes the load to timeout at 25s) and filed a bug for another issue I found :) but both extension and CLI complete successfully on my end, so having trouble debugging. 

Note that if your site doesn't have a server listening on port 80 at all or it is temporarily down then you would experience the issue you described but that doesn't seem to be your case.

**Comment by davmillar** [comment]
@patrickhulce sorry for the super-late response. I'll try again shortly and report back after doing so. I do know that the site isn't fully offline-capable yet, but I need to figure out what features make sense offline before doing any actual coding.

**Comment by brendankenny** [comment]
possibly #2784
