### ISSUE TITLE
Gracefully handle invalid URL in Unused CSS rules

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1879]
Errors the whole audit currently.
![image](https://cloud.githubusercontent.com/assets/2301202/24120899/82ec2200-0d73-11e7-9db5-fc0f43ed0060.png)

**Comment by patrickhulce** [comment]
discovered in #1877

**Comment by wardpeet** [comment]
perhaps if it's not parseable just prepend the hostname?

**Comment by patrickhulce** [comment]
I think it's more that it's just not a URL at all, but I'll investigate (we currently handle cases of null and empty string which reflect that it didn't have a URL/was inline/was injected, I'm guessing there's another special case I'm missing).

**Comment by wardpeet** [comment]
Probably a better idea 😃

**Comment by brendankenny** [comment]
nothing much reported since then, let's close instead of chill :)
