### ISSUE TITLE
WPT: incorrect emulation settings in report

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1884]
The report's emulation settings are not being set correctly by WPT:

<img width="945" alt="screen shot 2017-03-21 at 10 37 03 am" src="https://cloud.githubusercontent.com/assets/238208/24161725/703ac65c-0e22-11e7-85f4-0d630a787254.png">

Example run: https://www.webpagetest.org/lighthouse.php?test=170321_Y6_16T6&run=2

That run was created using the MotoG4_21 easy settings.

**Comment by patrickhulce** [comment]
@ebidel somewhat of a sticky situation given that Lighthouse is indeed not emulating or throttling anything (so in a sense it's reporting accurately. It's been run on a real device whose connection is being transparently throttled. I think a better approach to surface this might be to report some stats on the effective latency and CPU speed etc in addition to whether Chrome's emulation was used.

**Comment by ebidel** [comment]
Agreed. Wanted to flag this so we can get clearer sense of what needs to be done to support other runners like WPT and start discussing approaches. 

Right now, this UI is created from LH CI flags. That's clearly not going to work for WPT. But I still think there's value in showing the report's configuration. It gives good context for the data.

I'm unfamiliar with what information we're passed when starting a LH run on WPT.... If we do know the testing environment, perhaps we could come up with system to pipe through those strings to the report UI (if they're present)?

**Comment by patrickhulce** [comment]
> perhaps we could come up with system to pipe through those strings to the report UI (if they're present)?

I like the idea of adding a `context` field or something to the `report` property in config v2 where arbitrary information like this (or version of external driver, AWS machine ID, travis job, whatever) could be expressed and surfaced.

**Comment by paulirish** [comment]
our current handling of this is decent: 

![image](https://user-images.githubusercontent.com/39191/61746347-54034480-ad50-11e9-9ca7-fd4ba90a9890.png)
