### ISSUE TITLE
Clarify top-level Lighthouse scores in report

### ISSUE THREAD

**Issue by adewale** [GoogleChrome/lighthouse#1885]
At the moment if I get a score of 100 it's not clear if that means my PWA is perfect or if if there are additional checks that I'm failing.

If the score is a percentage then the UI should have % added to the score.

If the score is a number then we should indicate that scores above 100 are possible and likely.

**Comment by patrickhulce** [comment]
Thanks for the feedback @adewale! We're actually in the process of rethinking our scoring and making its components more explicit. Currently, you're right; it's essentially a percentage of the checks in the Progressive Web App category at the top and all other potential areas of improvement not taken into account.

**Comment by WDD-Marv** [comment]
I've had lighthouse checks where just having a barebones manifest.json bumps the score ~20 points, so clearly the scoring needs some rethinking :)

**Comment by vinamratasingal** [comment]
Closing in favor of the umbrella issue.
