### ISSUE TITLE
Caveat performance metrics & link to Web Page Test

### ISSUE THREAD

**Issue by tjsavage** [GoogleChrome/lighthouse#1888]
Partners & devs sometimes take the Lighthouse performance numbers as gospel. Until we can get more accurate real-device performance simulation, I think it'd be helpful to put in a caveat that our perf #'s won't necessarily reflect the real world, and point devs to WPT for a more accurate measurement. 

Something like:

<img width="380" alt="screen shot 2017-03-21 at 6 13 22 pm" src="https://cloud.githubusercontent.com/assets/348551/24177853/6f18405c-0e62-11e7-9624-8da588de024b.png">

**Comment by ebidel** [comment]
One thing to note is that we'd need to be careful about when/where to show this message. If you're running Lighthouse on WPT, the numbers will be real devices / accurate :)

Another thing that @paulirish just added was  "Page load is fast enough on 3G" audit for the new PWA section. It calls out when network latency may not be sufficiently realistic...although it still suffers from the limitations of emulation.

![screen shot 2017-03-22 at 4 24 40 pm](https://cloud.githubusercontent.com/assets/238208/24225139/1ceaa6de-0f1c-11e7-8a2c-3b790f04af30.png)

**Comment by wardpeet** [comment]
maybe we could sniff the useragent when device-emulation is disabled and see if we are a real device?

**Comment by addyosmani** [comment]
I was thinking about this the other day. I think there's value in the report calling out whether it was tested with an emulated setup (and perf numbers are approximates) vs on a real device.

**Comment by tjsavage** [comment]
Really like calling out whether it was tested emulated or on real device. Will help make you think twice before tweeting out a 99/100 emulated result :)

**Comment by wardpeet** [comment]
@addyosmani what's your take on this to get some data from the device?

**Comment by patrickhulce** [comment]
merging this into #3600 👍
