### ISSUE TITLE
audit: Network connection is secure

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#19]
Requirement: All assets served on HTTPS
Manual evaluation: Look at DevTools security panel to verify no problems, all green.

#### input:
* Use [Protocol Security domain](https://chromedevtools.github.io/debugger-protocol-viewer/Security/#event-securityStateChanged) securityStateChanged event

#### audit:
* to see if main origin is considered secure

#### when: 
* page loaded and in idle state

**Comment by paulirish** [comment]
@lgarron we want to identify if a page is secure via the protocol.

Can we just listen to `securityStateChanged`? It's per tab, not per frame, right?  Also, does the domain need to be enabled before the page load?

**Comment by paulirish** [comment]
v1 is done.
v2 on security domain remains.

**Comment by paullewis** [comment]
Can we close this now? I think so.

**Comment by paulirish** [comment]
yah sg.
