### ISSUE TITLE
Audit: Avoid large JavaScript bundle sizes

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#1902]
We currently have an audit for enormous network payloads (byte efficiency) which provides a baseline for understanding opportunities to reduce overall payload size:

![image](https://cloud.githubusercontent.com/assets/110953/24308954/335cd7f4-1087-11e7-8cbe-4ff3e33a48df.png)

**How would we feel about introducing an audit (or sub-audit) for large JS bundle sizes too?** 

If you're shipping more than ~170KB of script then we flag you. I've used some higher budgets just for illustrative purposes below since our understanding of what the medians and 99th percentiles were including JS wise have improved over time.

If we wanted to accomplish this as a UI treatment in the existing audit, we could highlight per-script budget breakers in red:

![image](https://cloud.githubusercontent.com/assets/110953/24309111/c321dd26-1087-11e7-8d27-fe767cd9e321.png)

..or we could look at the total sum of bytes for scripts with a '.js' extension and flag those:

![image](https://cloud.githubusercontent.com/assets/110953/24309213/29d1895e-1088-11e7-8edd-ec52f0434d3e.png)

and include some messaging about why we're flagging those scripts:

![image](https://cloud.githubusercontent.com/assets/110953/24309373/da77610c-1088-11e7-9f08-afe2cd2903b6.png)

Thoughts?

Side: Would totally love to have an audit like this for my I/O talk as bundle sizes (in particular for folks reusing bits in the React ecosystem) can be a challenge. 

Audit impacted: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/total-byte-weight.js

**Comment by patrickhulce** [comment]
I think it'd also be nice to express the cost here in terms of parse time in addition to network time. Can't really get that with CPU emulation today but maybe with calibration + trace we can estimate how long parse time would have been?

**Comment by ebidel** [comment]
Doing a sum of all the JS bytes might be confusing/tricky since we don't know what should be consider the user's "bundle". For example, we wouldn't want to include analytics.js.

That said, I think the key point we should raise to the user is that too much JS (> 450KB) is too much. We could highlight that target in the help text? Or, have another audit specific to JS size and use the amazing cards formatter. Thoughts?

<img width="741" alt="screen shot 2017-03-24 at 4 07 25 pm" src="https://cloud.githubusercontent.com/assets/238208/24316540/ffcc106a-10ab-11e7-80b3-4ccccab8fd45.png">

**Comment by addyosmani** [comment]
I totally haven't seen the cards formatter before. I like the idea of exposing an audit that highlights them there. 

Also agree that figuring out what is in their bundle would be hard. Best guess would be looking at what is coming from their origin but that would be inaccurate as some resources could be getting loaded off a CDN.

**Comment by paulirish** [comment]
Very related to #3105

**Comment by wardpeet** [comment]
We could try to figure out the cdn of the user?

We look for all resources that are done by the root document. See what origins they come from and if at least 20% of the requests come from that origin it's a cdn?

**Comment by wardpeet** [comment]
does this approach sounds reasonable?

**Approach 1 (separate audit):**
1) capture all js files that come from the mainOrigin and all of it's subdomains?
this would capture all js files of cnn.com, cdn1.cnn.com, cdn2.cnn.com
2) show a list of all files that exceed the 450kb threshold

**Approach 2 (editing payload size audit)**:
1) in the total-byte-weight audit we add an extra options to the table details generator.
```
const tableDetails = ByteEfficiencyAudit.makeTableDetails(headings, results, null, {flaggedColor: 'red', flagCondition: (details) => details.totalBytes > 460800});
```
2) in the viewer our details will have an extra field called flagged which can be true or false. When it's true we'll add a background-color of the flaggedColor to that row.

**Approach 3 (cards audit)**
this one is not used in lighthouse anymore for dom-size so it's probably going away.

**Comment by wardpeet** [comment]
@addyosmani @patrickhulce @paulirish @brendankenny 
So I experimented with this audit. Whenever I look for bundles > 450kb I could only find files from toysrus webpage. So it doesn't make much sense to only mark these ones.

So I added another commit to the PR to match all js and if the total of bytes exceeds 450kb I mark all JS files as flagged, if not I don't mark anything. Honestly I don't believe it's the best approach either as some js files happen at the end and might just be third party trackers, ... which aren't really a big problem. So my suggestion is to maybe only measure script tags that happen before TTI? As those scripts probably have impact on TTI or would that be a bold statement.

Happy for feedback, PR is up #5010

**Comment by patrickhulce** [comment]
I like @addyosmani's approach on reducing the threshold for large bundle sizes. 450kb gzipped is more than a meg to parse, which is *a lot*.  This also focuses the attention on what the beefiest JS bundles are that you should be fixing. I'm also all for adjusting the score of this audit for v3 if we want to incorporate JS size specifically into the score.

We recently decided to recalibrate our scores based on observed percentiles from HTTPArchive, setting the curve based on 90th = 75, 75th = 50. If we applied a similar rule here, the failure threshold for JS size would be, no joke, 168.8kb. So 170kb sounds 👌 💯 

I like what you're getting at @wardpeet with the notion of "hey just breaking up your bundle and shipping 15 169kb bundles isn't making things better", but it seems like this is a good enough start to get people thinking about code-splitting and removing dead code.

**Comment by addyosmani** [comment]
> it seems like this is a good enough start to get people thinking about code-splitting and removing dead code.

👍 👍 👍

**Comment by brendankenny** [comment]
between "Avoid enormous network payloads" (as mentioned), "Reduce JavaScript execution time" (which penalizes for execution *and* parse time), and now budgets, I'm going to close this. The remaining stuff we can highlight should be handled by whatever we decide about default budgets.
