### ISSUE TITLE
Add start_url_works_offline to "User can be prompted to Add to Homescreen"

### ISSUE THREAD

**Issue by tjsavage** [GoogleChrome/lighthouse#1903]
Chrome now looks to make sure there is a service worker with a fetch handler before allowing the Add to Homescreen prompt: https://codereview.chromium.org/2751343002/

Should we duplicate the "Responds with a 200 while offline" audit to also now go under "User can be prompted to Add to Homescreen," as it's now (roughly) a prerequisite for that as well?

**Comment by paulirish** [comment]
Pretty close, yeah.

I believe the discussion in SYD concluded that  we'll do the `works-offline-200` check but for `start_url` instead of the provided URL. And yes, this will be a requirement of a2hs/install-banner.

**Comment by paulirish** [comment]
This work is blocked by https://github.com/GoogleChrome/lighthouse/pull/1847

**Comment by paulirish** [comment]
Let's fix #1788 as part of this one.

**Comment by slightlyoff** [comment]
Via @brendankenny, current status is that the current URL is checked for offline behavior, not `start_url`, but the check is in place. Hooray!

**Comment by ebidel** [comment]
https://github.com/GoogleChrome/lighthouse/pull/2040 will check if the `start_url` works offline.

**Comment by patrickhulce** [comment]
fixed by #2040
