### ISSUE TITLE
CLI. Open new tab instead of launching new chrome

### ISSUE THREAD

**Issue by denar90** [GoogleChrome/lighthouse#1905]
In case if chrome already launched, I propose to open a new tab (if it's possible) instead of launching a new chrome process.

---
If we wanna measure page where user has to login, then launching new chrome will open a login form.
To not force users make their auth bot, which will login first, then run Lighthouse on a same chrome instance, we can open new tab instead. 
How will it help? 
If user already logged in, then he/she can just run Lighthouse via cli and get results avoiding login and stuff. 

All this stuff related just to cli, extension already covering this case. 

If you guys are interested in that, I'd like to take a look :)

**Comment by patrickhulce** [comment]
@denar90 if you've already got Chrome open with the specified remote debugging port given to lighthouse with `--port` (9222 by default) then this *should* be the current behavior. Are you seeing something else?

**Comment by brendankenny** [comment]
Lighthouse should already connect to an existing Chrome instance if Chrome was launched with `--remote-debugging-port=9222` (or any port, if you also supply the port number to Lighthouse with `--port`).

We also expose our Chrome launcher which handles that flag for the user (as well as [a number of other flags](https://github.com/GoogleChrome/lighthouse/blob/f7fe7d2081cdc676beeca461d64bcd59bca5071f/lighthouse-cli/chrome-launcher.ts#L65-L84) which help with reducing noise in performance measurements).

That launcher is available via `chrome-debug` if you install lighthouse globally or `npm run chrome` if you're dealing with a git checkout.

**Comment by denar90** [comment]
Thx for detailed info 👍 I have installed 2 chromes, regular one and canary. Running LH v1.6.3 (`lighthosue --remote-debugging-port=9222`) is always opening new canary instance, so if I have already opened canary with site where I logged in, then new instance with login form is opened...

**Comment by brendankenny** [comment]
sorry, have to run *Chrome* with `--remote-debugging-port=9222`, then just regular `lighthouse https://example.com` should connect to it and use it for the run

**Comment by denar90** [comment]
thx 🎉  🍺 from me :)
