### ISSUE TITLE
Improve user timing coloring

### ISSUE THREAD

**Issue by denar90** [GoogleChrome/lighthouse#1910]
I think it can be useful to have timings colors related to their scores.
e.g. if FMP, TTI scores 100 we can make it green and others - orange or smth.
So in timeline it will be easy identify bottle necks...

Right now it look like this
https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://drive.google.com/file/d//0B0c67TI7mLzEMFNhSENiVDhHWEE/view?usp=drivesdk
![image](https://cloud.githubusercontent.com/assets/6231516/24355122/6bb44722-12fd-11e7-9803-178c449040ed.png)

thoughts?

**Comment by paulirish** [comment]
yeah not a bad idea. :)

we could explore doing the hacking in timeline-viewer, as there is no support in timeline proper for tweaking the color used on the usertiming bar.

**Comment by denar90** [comment]
So, just stick to some const values, e.g FMP < 1600ms then green, otherwise default, etc?

**Comment by paulirish** [comment]
closing in favor of https://github.com/ChromeDevTools/timeline-viewer/issues/12
