### ISSUE TITLE
OffscreenImages: flag images with 0 area

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1914]
Testing https://www.chromestatus.com/features, I get a debugString in the offscreen images audit for an .svg file. 

![screen shot 2017-03-27 at 3 29 50 pm](https://cloud.githubusercontent.com/assets/238208/24380884/69e32a80-1302-11e7-929b-1f25dcd709a9.png)

Shall we ignore svgs in this auidt?

**Comment by patrickhulce** [comment]
heh, good catch but different fix. We skip the image (and show debug string) if the bounding rect area is 0 when we should flag it instead :)
