### ISSUE TITLE
Report: top-level warn if initialUrl and finalUrl are different

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1917]
We need to figure out some way of notifying the user if the `finalUrl` ended up on a different origin than the `initialUrl`. Mainly for the CLI and WPT cases where users can put in a URL. For the CRX / DT, users typically end up on the final URL before testing.

Separating this out from https://github.com/GoogleChrome/lighthouse/issues/715. @brendankenny said:

> Sounds good. To close the loop: another issue with initial vs final URL is clearing storage, which is done per origin. If a redirect goes cross origin the cache, SW, etc are not cleared.

> In the CLI this is only a problem if not using the default clean Chrome. In the extension you're usually already on the final (possibly redirected) URL, except when sites redirect you to a different origin due to mobile emulation.

**Comment by brendankenny** [comment]
HTTP -> HTTPS redirects should get this warning too (#2397)

**Comment by connorjclark** [comment]
I'm not sure we need to have different warnings if just the origin changes. Let's do just a generic warning if requested !== final.
