### ISSUE TITLE
Address PWA9to3 PR feedback from bckenny

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1920]
link: https://github.com/GoogleChrome/lighthouse/pull/1847#pullrequestreview-29333098

some good stuff in there I want to make sure I do (or respond to)

**Comment by brendankenny** [comment]
This feedback was primarily about my general animosity towards `MultiCheckAudit`.

My desire to remove it burns eternal and needs no tracking issue, so there's no need to keep open the rest of this mostly outdated code review.
