### ISSUE TITLE
Create infrastructure for measuring Lighthouse perf metrics

### ISSUE THREAD

**Issue by wwwillchen** [GoogleChrome/lighthouse#1924]
### Objective

Enable users to:
- export lighthouse results to the cloud
- query certain types of lighthouse results from the cloud (e.g. only sites X and Y with devtools-based throttling)
- visualize these lighthouse results locally

This will enable the lighthouse team to analyze both the accuracy (variance between various configs - WPT-based or DevTools-based network throttling) and precision (variance between runs with the same config)

### Querying
Example queries:
* All results from 3/28 - 3/29 for sites X and Y for all types of configuration

Dimensions for querying:
* Date range (when it was run)
* Browser version
* CPU Throttling type
* Network Throttling type
* Sites
* Platform (real device or emulated) or an overall systems performance metric (Ops/second)

Data model (probably Cloud Datastore)
```
{
  lighthouseVersion: "1.6.3",
  generatedTime: "2017-03-27T23:23:11.077Z",
  browserVersion: ''Chrome Canary 57.7",
  cpuThrottling: "", // enum of "DevTools", ?
  networkThrottling: "", // enum of "DevTools", "WebPageTest"
  platformType: "", // enum of "realDevice", "emulated"
  platform: "" // TBD
  url: "https://site.com",
  performanceMetrics: {
    firstMeaningfulPaint: {
     rawValue: float,
     score: int,
   }
  // other perf metrics...
  }
}
```

### Visualization
![image](https://cloud.githubusercontent.com/assets/7344640/24420080/61d7ecaa-13a6-11e7-9fda-eb2ef9b45386.png)

**Comment by pedro93** [comment]
A database of metrics? Doesn't webpage test have this? I admit the querying and visualization looks nice but from a users perspective it has to be opt-in AND they must have some incentive to do so (also have access to data)?

**Comment by patrickhulce** [comment]
> from a users perspective it has to be opt-in AND they must have some incentive to do so (also have access to data)?

Definitely, the goal of this IMO is to *enable* easily saving Lighthouse results to a central location (whether that's a publicly provided database, your private CI, a Google Sheet, a coveralls.io clone but for LH, etc). The Lighthouse team gets the added benefit of the reference implementation for *query-able* results compared to WPT individual files and visualizations.

**Comment by pedro93** [comment]
Right now one of the biggest features IMO of lighthouse is that it enables you to test local or vpn-accessable-only webpages. How would this feature work in those cases?

Let's assume a developer/company is ok with sharing with LH team but not globally, any suggestions to deal with that? I'm all for a coveralls version to perf, a11y & good practices just not sure about sharing "private" metadata

**Comment by wwwillchen** [comment]
Thanks for the feedback @pedro93. I'd like to propose three phases to this work:

1) Internal usage for Lighthouse team - while we're still working on the schema and figuring out how to handle usage limits for our cloud resources
2) External users can submit specific runs to Lighthouse's internal DB - this can be useful for bug reports (I'm not sure what the team's current practice is for gathering results & artifacts from users)
3) Plug your own Cloud Datastore instance  - this can either be a company running their own datastore for internal usage or a global community-based lighthouse DB.

Because this involves storing and retrieving large resources like trace files, we need to be careful about managing bad actors and avoiding unexpectedly high usage.

@paulirish - please chime in.

**Comment by paulirish** [comment]
Aye. I think our scope here is pretty small. We want to store a bunch of reports from our own dev machines/devices and Travis runs to understand and improve the metrics.

After talking with Will we agree that item 2 above isn't a big focus, it's all about 1. 

This effort is mostly to get some basic infrastructure in place so that this storage and analysis can be done manually.
