### ISSUE TITLE
Metrics: capture timestamps of NetworkIdle, CPUIdle, etc

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1926]
We were looking at some data of repeated lighthouse runs and the very wild variance of VC100%
![image](https://cloud.githubusercontent.com/assets/39191/24428942/e65a0292-13c4-11e7-9219-f6fcdb5aa233.png)

The next question i had was: "When did we stop tracing on all the runs where pink is not spiking?"  I'm guessing the trace stopped before this visual change (on a timer?) happened.  Just a guess though.  

So I think a few more datapoints would be really useful to broaden our understanding:

1. timestamp of when the trace ended (best solution: take the last `ts` in there)
1. timestamp of window load (used in our `_waitForFullyLoaded`)
1. timestamp of when driver calls `networkIdle`. (Will be tricky since it's not a time in the trace, but we could emit a userTiming mark ourselves to tag it.)
1. timestamp of when we hit the `maxWaitForLoadedMs` timeout, if we did actually hit it, natch.

For example, seeing wide variance in networkIdle is going to have big impact on reverseSearchTTI and VC100.

**Comment by brendankenny** [comment]
we didn't quite hit all of this, but between `diagnostics` and `metrics`, I think we have this well covered.
