### ISSUE TITLE
Add browserVersion to lighthouse results

### ISSUE THREAD

**Issue by wwwillchen** [GoogleChrome/lighthouse#1927]
Similar to `lighthouseVersion`, we should annotate the results with the `browserVersion`. We can use the information from http://localhost:9222/json/version  (e.g. "Chrome/59.0.3051.0")

**Comment by paulirish** [comment]
> We can use the information from http://localhost:9222/json/version

In the devtools and extension cases, we dont have this endpoint.

We _could_ fork based on the connection type... we could also evaluateScript to ask the page itself.. Maybe another option.. ?

**Comment by brendankenny** [comment]
> We could fork based on the connection type

yeah, could have a `driver.getChromeVersion()` or whatever, have it ask the connection and have the implementation in the subclasses.

The extension can just check `navigator.userAgent`, is there an equivalent for devtools that also supports remote debugging a device?

**Comment by paulirish** [comment]
remote debugging we have the /json/version endpoint so we're good there.

in devtools case we have the protocol, but not the /json/version endpoint.
AFAIK, we'll have to evaluateScript in this case.
