### ISSUE TITLE
Tested website stuck in Offline Mode

### ISSUE THREAD

**Issue by tomoguisuru** [GoogleChrome/lighthouse#1930]
Lighthouse stopped running during a test and now the site it was testing is stuck in Offline mode. Opening the same site in incognito or another website will show the site correctly

**Comment by wardpeet** [comment]
do you have an url to share? You can always send a PM if it can't be public

**Comment by patrickhulce** [comment]
feel free to comment here and we'll reopen if you're still experiencing this
