### ISSUE TITLE
Intermittent connection reset events

### ISSUE THREAD

**Issue by pmeenan** [GoogleChrome/lighthouse#1931]
It seems to only impact Windows but connecting to an already-running Chrome instance sometimes throws:

```
9:15:59.562 - lighthouse --disable-cpu-throttling --disable-network-throttling --port 9222 --output html --output json --verbose --output-path "C:\src\wptagent\work\pat\170329_DA_80229d364d611c8214cd12e32992d3c2.1.0\lighthouse.json" "http://www.webpagetest.org/?bare=1"
  Lighthouse CLI:verbose Using supplied port 9222 +0ms
  Lighthouse:warn The URL provided should be on HTTPS +253ms
  Lighthouse:warn Performance stats will be skewed redirecting from HTTP to HTTPS. +3ms
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1029:11)
    at TCP.onread (net.js:575:26)
```

It always throws at the same point and time (when initially connecting) and sometimes adding a delay before running lighthouse helps but sometimes not.

Right now WebPageTest polls the /json dev tools interface waiting for the browser to become available before launching lighthouse (otherwise it gets the same error reliably).

It might be worthwhile to add some redundancy to the initial connection establishment when passed an explicit port and retry for several seconds until it is successfully connected.

**Comment by patrickhulce** [comment]
+1, We only poll for Chrome to be ready when we launch it ourselves, but would be nice to support this for passed in ports too with a reasonable timeout.

**Comment by brendankenny** [comment]
We can replace `.isDebuggerReady()` with `.waitUntilReady()` [here](https://github.com/GoogleChrome/lighthouse/blob/bc87071b428b2d236715dfad88acd59a21db4a12/lighthouse-cli/bin.ts#L222), but I guess the question is how many retries to do. It is nice to fail immediately when running with `--skip-autolaunch` and you don't have Chrome open, but I guess that's not that common a use case

**Comment by wardpeet** [comment]
at the moment waitUntilReady is configured to retry 10 and poll on an interval of 500ms but we can easily make the retry count editable to support skip-autolaunch

**Comment by ebidel** [comment]
Also seeing this on Mac when running `--headless`:

```javascript
  const launcher = new ChromeLauncher({port: 9222, additionalFlags: [ '--headless']});

  launcher.run()
    .then(() => lighthouse(url, flags))
    .then(results => {
      return new Promise(resolve => {
        setTimeout(() => {
          resolve(results);
        }, 10); // Introduce slight delay before killing Chrome.
      });
    })
    .then(results => launcher.kill().then(() => results))
    .catch(err => {
      return launcher.kill().then(() => {
        throw err;
      });
    });
```

**Comment by paulirish** [comment]
Can likely dupe to ECONNECTREFUSED bug.. and resolved with https://github.com/GoogleChrome/lighthouse/compare/browserws

**Comment by paulirish** [comment]
Nearly certain this is fixed by now. Launcher is a lot more robust. Holler if its still an issue. :)
