### ISSUE TITLE
[Doc] Headless instructions fail

### ISSUE THREAD

**Issue by pedro93** [GoogleChrome/lighthouse#1932]
Hi I was attempting to run lighthouse in a docker container and was looking at the docs which I see has an option for headless chrome however it fails for me in this line.
```
apt-get install chromium-browser xvfb
```

I have checked and debian jessie OS does not have any repository for chromium, is there any specific non-default repo where I can download chromium from and if so could you update the docs accordingly? 

Thank you for reading this, its low priority but it would help a ton for CI/container-like environments.

**Comment by paulirish** [comment]
yah sounds good.

generally the solution is using https://download-chromium.appspot.com/

so something like

https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots  will do the download.

**Comment by ebidel** [comment]
I've had luck creating a docker image on ubuntu. You could switch this to using headless, but there are still bugs with it.

Dockerfile:
```
FROM ubuntu:latest

RUN apt-get update --fix-missing && apt-get -y upgrade &&\
apt-get install -y sudo curl wget unzip git

RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - &&\
sudo apt-get install -y nodejs

RUN apt-get install -y xvfb dbus-x11

# Install Chrome for Ubuntu
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - &&\
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\
sudo apt-get update &&\
sudo apt-get install -y google-chrome-stable

COPY etc/xvfb /etc/init.d/xvfb
RUN chmod +x /etc/init.d/xvfb
...
```

```
#!/bin/bash

export DISPLAY=:1
TMP_PROFILE_DIR=$(mktemp -d -t lighthouse.XXXXXXXXXX)

/etc/init.d/dbus start
/etc/init.d/xvfb start
sleep 1s

nohup google-chrome \
  --no-first-run \
  --disable-gpu \
  --no-first-run \
  --disable-translate \
  --disable-default-apps \
  --disable-extensions \
  --disable-background-networking \
  --disable-sync \
  --metrics-recording-only \
  --safebrowsing-disable-auto-update \
  --disable-setuid-sandbox \
  --user-data-dir=$TMP_PROFILE_DIR \
  --remote-debugging-port=9222 'about:blank' &

sleep 3s
...
```

I also found this for alpine:
https://github.com/MatthiasWinkelmann/lighthouse-chromium-alpine-docker/blob/master/Dockerfile

**Comment by pedro93** [comment]
https://github.com/MatthiasWinkelmann/lighthouse-chromium-alpine-docker/blob/master/Dockerfile works though it is not the easiest thing to adapt, perhaps the headless.md should be changed whilst [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=666865) isnt fixed and add either dockerfiles for a container solution.

**Comment by MatthiasWinkelmann** [comment]
@pedro93 I'll happily accept PRs. It should, in theory, just run lighthouse with whatever arguments provide, or run a test if you give none. But it's possible that Dockerfile, README, and the script that runs lighthouse have gotten out of sync when I last worked on it.

There's also too much noise on stderr/stdout for my liking, mostly related to graphics and sound. But those don't seem to impact the reports.

**Comment by pedro93** [comment]
@MatthiasWinkelmann I was looking into it but my knowledge of Docker, Unix and building Chrome is not good enough to offer any substantial help. I will continue to play around with it though, ill let everyone know if I find a good solution.

**Comment by ebidel** [comment]
Updated docs: https://github.com/GoogleChrome/lighthouse/blob/master/docs/headless-chrome.md

You can also use [chrome-launcher](https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher#continuous-integration) from CI. There are instructions there for downloading chrome using LH's download-chrome.sh script.
