### ISSUE TITLE
Catch and dimiss javascript dialogs/alerts/prompts

### ISSUE THREAD

**Issue by cedricbellet** [GoogleChrome/lighthouse#1939]
lighthouse http://jetcost.com

jetcost seems to call window.confirm during a lighthouse test, and so long as the window.confirm is open, lighthouse continues to wait. tested with 1.6.3

**Comment by ebidel** [comment]
Ugh. That's terrible.

Looks like this happens in mobile emulation. The double 'ugh' is tat the dialog translates to "Get the free Jetcost app for Android. The best deals for cheap flights in your pocket!"

`Page.handleJavaScriptDialog` might do the trick.

**Comment by paulirish** [comment]
Yeah good call @ebidel 

Interestingly there is no chrome --flag for this, but we can do it with [`Page.handleJavaScriptDialog`](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Page/#method-handleJavaScriptDialog)

We listen for the `'Page.javascriptDialogOpening'` event to fire and whenever it does, we can immediately do `sendCommand('Page.handleJavaScriptDialog', {accept: true})` and all is well. We might also want to supply a `promptText` property to the options in case the confirm prompt is asking for some text.

@cedricbellet do you want to give this a shot? It'd live completely in driver.js and just get setup once we're connected.

**Comment by ebidel** [comment]
Come to think of it, we might be able to also get a quick UX audit out of this for "Avoiding APIs that harm the user experience" :) No page in 2017 should be using dialogs/prompts like this.

**Comment by paulirish** [comment]
Very true!

**Comment by cedricbellet** [comment]
On honeymoon so have limited time but happy to take a look upon my return
