### ISSUE TITLE
Extension Error: Protocol error (Network.emulateNetworkConditions): Unknow...

### ISSUE THREAD

**Issue by PegasusT4** [GoogleChrome/lighthouse#1942]
**Lighthouse Version**: 1.6.0
**Chrome Version**: 57.0.2987.133
**URL**: https://blogs.oracle.com/geertjan/entry/solved_netbeans_debugger_is_debugging
**Error Message**: Protocol error (Network.emulateNetworkConditions): Unknown debugger protocol error.
**Stack Trace**:
 ```Error: Protocol error (Network.emulateNetworkConditions): Unknown debugger protocol error.
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9300:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by PegasusT4** [comment]
Get this error with any URL.

**Comment by wardpeet** [comment]
Did you try to install the extension again? It works fine on my machine. Downloaded the latest extension from the store.

**Comment by PegasusT4** [comment]
Yes, it is the current 1.6.0 version. It works fine on my Win 10 64bit Dell desktop, just not on my HP Spectre x360 with latest Win10 64 updates. Reinstalled several times with same results. In the right side Lighthouse box where you generate the report, I get "Protocol error (Network.emulateNetworkConditions): Unknown debugger protocol error." On the left side of window is  "HP Connection Error. Google Chrome cannot display the web page." Running HP network diagnostics show no problems. I believe the error message is talking about Chrome unable to display the Lighthouse report, since that is what should show up next.

**Comment by paidfocusgroups** [comment]
I turned the  HP Network Connection diagnostic extension off in my browser, and the error stopped.

**Comment by PegasusT4** [comment]
You got it paidfocusgroups. I turned off HP Network Connection diagnostic extension in Chrome and Lighthouse now works. Good catch! I didn't even know that extension had been installed by HP.

**Comment by paulirish** [comment]
okay so it sounds like either the `HP Network Connection diagnostic chrome extension` `HP Network Check Helper` are actively messing with Chrome's network connection. This will make Lighthouse fail.

This also implies that network throttling from inside of DevTools also doesn't work, but that's likely just a silent error.
