### ISSUE TITLE
Extension icon should be grayscale

### ISSUE THREAD

**Issue by DavidFrahm** [GoogleChrome/lighthouse#1945]
The extension toolbar icon should be grayscale, to keep a low profile during day-to-day browser use.

I can't seem to find the Google Chrome developer docs for this, but I do think it is a guideline. At the very least, it is a common courtesy.

Here's my extension icons which show this:

![screenshot 2017-03-31 at 7 37 39 am](https://cloud.githubusercontent.com/assets/889791/24552318/9447ff3a-15eb-11e7-9dad-66a11c7c6d7b.png)

**Comment by ebidel** [comment]
Hmm, I haven't seen that guideline before, but my own toolbar is littered with colorful icons :)

<img width="277" alt="screen shot 2017-03-31 at 9 58 08 am" src="https://cloud.githubusercontent.com/assets/238208/24560686/90991826-15f8-11e7-9fab-f15bf976f2f2.png">

Note: Chrome 49 changed the way browser and page action extensions appear in the toolbar. Namely, they get an icon now (see 19.) on https://developer.chrome.com/extensions/single_purpose). Those types of extension will have a grey icon when they're not on a page that's activating them, and colorize when they are. Perhaps that's what you're seeing for some of these?

**Comment by DavidFrahm** [comment]
Thanks for the info. Definitely some of my extensions fall under that category, but not all of them.

Looking at many examples and at Google's own design of Chrome, it seems like the right thing to do.

The best experience for Chrome users is not to have a mess of colors up there.

That said, it doesn't appear to be any kind of rule so if you're not interested we can  close this issue.

**Comment by paulirish** [comment]
Yup this is due to the new page action / browser action changes.  since lighthouse is invoked on demand, it will always have color.

afraid we can't really do much here.
