### ISSUE TITLE
Audit: warn if page uses library with known security vulnerabilities

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1948]
It would be nice to have an audit that warns users about library versions that
have security vulnerabilities. This could live as a **security audit**.

HTTPArchive is going to start recording the libraries uses on a page: https://github.com/HTTPArchive/httparchive/issues/77.

The Snyk database contains info on known vulnerabilities. e.g. jquery:
https://github.com/snyk/vulnerabilitydb/tree/master/data/npm/jquery

**Comment by igrigorik** [comment]
@guypod @tkadlec perhaps you can guy help with HA + LH integration? :-)

**Comment by tkadlec** [comment]
Nice! Was going to suggest HTTPArchive track it, so glad to see that's going to happen. :) I'll try to set aside some time this weekend to have a look through.

**Comment by igrigorik** [comment]
@tkadlec awesome, thanks! Let's start a new issue on HA repo to track this. /cc @rviscomi

**Comment by tlauinger** [comment]
For security audit purposes, see also [retire.js](https://github.com/RetireJS/retire.js), which has its own vulnerability DB and a more advanced detection methodology than what's being built into HTTPArchive. (As far as I remember, retire.js can detect the URL of vulnerable scripts, also checks inside frames, and should be able to detect duplicate inclusions of libraries.)

**Comment by ebidel** [comment]
retire.js looks interesting, but is that something that can run on a live site? It looks like the tool works similar to snyk, where you run it across a local codebase.

**Comment by tlauinger** [comment]
As far as I remember, Retire.js has multiple modules - one that checks NPM dependencies and needs access to the source code (which sounds similar to Snyk), but Retire.js also has browser extensions for Chrome and Firefox, which should work with live websites (something that Snyk doesn't seem to do).

**Comment by tkadlec** [comment]
Catching up...

>Retire.js also has browser extensions for Chrome and Firefox, which should work with live websites (something that Snyk doesn't seem to do).

FWIW, I had a look at the library detection method @ebidel is using in https://github.com/HTTPArchive/httparchive/issues/84 and Snyk would easily handle the output. It's true we don't have a browser extension (yet! ;) ), but there's an endpoint you could hit for each detected version that would return a JSON object of any known vulnerabilities.

**Comment by ebidel** [comment]
@tkadlec that would be awesome to experiment with. Is that a public endpoint. IOW, are you comfortable with us using it in an open source project? :)

**Comment by tkadlec** [comment]
Sorry for the radio silence! 

It's not really documented anywhere (yet!!) but I'd be happy to use it for Lighthouse. I'll hook it up in a PR. Not sure how you want to handle the mapping, as discussed in the HA issue https://github.com/HTTPArchive/httparchive/issues/84#issuecomment-292968079

**Comment by tkadlec** [comment]
So I _finally_ got some time to do this. https://github.com/GoogleChrome/lighthouse/pull/2372

It is NOT READY TO MERGE, and I've noted outstanding tasks that I thought should be more left up to the core Lighthouse team to determine, but functionality is there.

**Comment by igrigorik** [comment]
\o/ ... awesome, thanks Tim!

**Comment by rviscomi** [comment]
As long as LH is including the library detection code, WDYT of exposing all detected libraries in addition to specific vulnerabilities? With LH+HA integration that would make HA's own library detection code redundant and we could remove it.

**Comment by tkadlec** [comment]
@rviscomi How would you want that in the LH results? Technically, it's all there. The full list of libraries and versions is what I pass along to Snyk for checking, so it's just a matter of figuring out how you expose that.

**Comment by rviscomi** [comment]
@tkadlec anywhere in the results object there could be a 'js_libs' property (or similar) whose value is an array of objects with name/version members. For example:

```js
{
...
'js_libs': [
  {name: 'jQuery', version: '1.1.1'},
  {name: 'SPF', version: null}
],
...
}
```

Also see the [HA code](https://github.com/HTTPArchive/httparchive/blob/599d64ef4068be188d7d6fb21bb4cada198a6f5d/custom_metrics/third-parties.js#L16-L27) for reference.

**Comment by patrickhulce** [comment]
@tkadlec @rviscomi we generally put extra information like this in the `extendedInfo` property of the audit results, seems like a good place to put this and it would be available to consumes at `audits.no-vulnerable-libraries.extendedInfo.value`
