### ISSUE TITLE
why lighthouse remove chrome-remote-interface module

### ISSUE THREAD

**Issue by jasonChen1982** [GoogleChrome/lighthouse#1949]
just curious, so who can talk about the story or have some hole?

**Comment by ebidel** [comment]
https://github.com/GoogleChrome/lighthouse/commit/7062bfb5500f32d2df5d06b4a9eb61610932f0a4 removed it back in Oct in favor of the `ws` web sockets module. There wasn't a bug discussing the switch, but fewer levels of abstraction and more minimal dependencies might be one of the reasons. @brendankenny and @paulirish might remember.

Is there a particular reason you ask?

**Comment by paulirish** [comment]
We nuked it for simplicity.. and it came from the engineer who created the protocol and its first implementation. :)  

For nearly all other projects, I recommend using cri. It's excellent.
