### ISSUE TITLE
"Notifications permission on page load" does not fail on https://www.uol.com.br

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#1953]
As far as I can tell, this site doesn't have a manifest, but [the Lighthouse report](https://googlechrome.github.io/lighthouse/viewer/?gist=89135b5f085f00954532f9637f91b1f2) says it does: https://www.uol.com.br.

The site does use App Cache.

**Comment by ebidel** [comment]
**Manifest**

I ran LH a few times and got a positive check for a manifest (https://www.uol.com.br/manifest.json). It looks like they only include the meta tag when you're on mobile or emulating it:

<img width="1109" alt="screen shot 2017-04-02 at 10 41 21 am" src="https://cloud.githubusercontent.com/assets/238208/24589542/fccf81c6-1790-11e7-892f-fb0bb376daaf.png">

Not sure why it didn't show up for you though. Can you try 1-2 more runs and let us know?

**AppCache**
The usage is coming from one of their iframe'd add domains. You'll see console messages, but the site itself isn't using Appcache. 

<img width="804" alt="screen shot 2017-04-02 at 10 37 15 am" src="https://cloud.githubusercontent.com/assets/238208/24589527/b2e968ce-1790-11e7-9e51-bb5a51929296.png">

**Notifications prompt on page load**

I noticed the site prompts for notifications on page load. Looks like we're pretty flaky on this check. I got both positive and negative results.

<img width="520" alt="screen shot 2017-04-02 at 10 44 59 am" src="https://cloud.githubusercontent.com/assets/238208/24589581/875b4b4a-1791-11e7-823e-2994c6f3b09c.png">

We'll look into that.

**Comment by samdutton** [comment]
Thanks for quick response @ebidel!

> AppCache

Ah — good spot. I was just looking at Chrome DevTools, didn't go into the details.

> Manifest

Likewise — hadn't realised this was only on mobile :/. Lighthouse gets it right.

> Notifications prompt on page load

Yeah...

**Comment by wardpeet** [comment]
@ebidel do we consider this as a bug?

//cc @brendankenny @paulirish @patrickhulce

**Comment by ebidel** [comment]
Changing the title so we investigate the one issue: "Notifications prompt on page load" isn't failing on this site.
