### ISSUE TITLE
Audit: prompts for notifications on page load can be flaky

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1954]
site: https://www.uol.com.br

Running the LH 1.6.0 extension against https://www.uol.com.br can come back with passing result for this check:

<img width="520" alt="screen shot 2017-04-02 at 10 44 59 am" src="https://cloud.githubusercontent.com/assets/238208/24589586/b639cf22-1791-11e7-87d8-0ccf0c733c1b.png">

https://googlechrome.github.io/lighthouse/viewer/?gist=89135b5f085f00954532f9637f91b1f2

The site prompts for notification on page load, so this should always be failing.

**Comment by brendankenny** [comment]
We switched to using violations for this.
