### ISSUE TITLE
Missing firstMeaningfulPaint event

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1960]
This is mostly an upstream bug, but finally found a 100% reproducible case and wanted to file it.

`npm run fast -- https://www.websocket.org/demos/todomvc/run/index.html#/` causes all of our perf metrics to error

**Comment by tdresser** [comment]
Can you add some more details here? Are you running into issues with the metric definitions?

**Comment by patrickhulce** [comment]
@tdresser all of our metrics rely on fMP as the start of our window and this site is routinely missing fMP in the trace when run with Lighthouse. It must have to do with the specific combination of trace categories we use or some other setting specific to Lighthouse as I can't reproduce the behavior in Canary using the Performance tab. Also worth noting that screenshots are always missing as well.

Here's a sample trace from a run on that site, but every run of Lighthouse produces a similar result. 
https://drive.google.com/open?id=0B_6m1yW__xllclEwakp5clQyazA

**Comment by tdresser** [comment]
Thanks - if this is working in the performance tab, it probably doesn't make sense for me to dig in.

**Comment by patrickhulce** [comment]
Well this is considerably less exciting, my shell was adding a slash before the `#` whenever the URL was pasted causing `https://www.websocket.org/demos/todomvc/run/index.htm/#/` to be loaded instead which is indeed a blank page that does not have fMP fired.

🤦‍♂️
