### ISSUE TITLE
PWA-fast-enough throttling check can false positive

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1962]
Using the CLI:

```sh
lighthouse https://airhorner.com
```

I got this:

![image](https://cloud.githubusercontent.com/assets/39191/24673521/84ac7304-192d-11e7-8919-89b88fc6d81b.png)

You can see two requests with latency measured at 0.082 and 0.074 ms.
I attempted to repro within devtools (with throttling) but couldn't.

I'm almost certain the 0.08ms latency requests are the two reqs to google analytics. My guess is there's either something going on about QUIC or disk cache. Not sure which yet

**Comment by patrickhulce** [comment]
I'm still in favor of debug stringing but not failing :)

**Comment by paulirish** [comment]
> I'm still in favor of debug stringing but not failing :)

I'm open to that, but would like to attempt to be strict first.
