### ISSUE TITLE
Service Worker audit needs to test controlling scope

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1965]
Our current audit only checks for an activated SW on the test page's origin. We need to look specifically at the SW's scope to make sure it can actually control the test page (e.g. by default a service worker at `https://example.com/dir/sw.js` can only control pages under `./dir/` and can't be the SW for `https://example.com/`).

Looking at the [protocol response](https://chromedevtools.github.io/debugger-protocol-viewer/tot/ServiceWorker/#type-ServiceWorkerVersion), I'm not sure if we'll be able to test the scope directly and so we may need to resort to testing that the target page's `TargetID` is in `controlledClients`.

**Comment by mutdmour** [comment]
Was looking into working on this one. But I have yet to find a service worker in the wild that has any TargetIds in controlledClients. Thoughts?

**Comment by brendankenny** [comment]
fixed in #6609 and #6678
