### ISSUE TITLE
Extension Error: Cannot access a chrome-extension:// URL of different exte...

### ISSUE THREAD

**Issue by zvonkoveljovic2** [GoogleChrome/lighthouse#1966]
**Lighthouse Version**: 1.6.0
**Chrome Version**: 57.0.2987.98
**URL**: chrome-extension://invalid/
**Error Message**: Cannot access a chrome-extension:// URL of different extension
**Stack Trace**:
 ```Error: Cannot access a chrome-extension:// URL of different extension
    at Object.chrome.debugger.attach._ [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9244:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by wardpeet** [comment]
hey @zvonkoveljovic2 could you tell use more on how you got this error?
Do you get it sometimes or every time you run the extension?

**Comment by ebidel** [comment]
Lighthouse can't test extension URLs. That'll include pages generated by other extensions )option pages, new tag page, etc.)
