### ISSUE TITLE
waitForNetworkIdle gets hosed by main thread activity

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1969]
DevTools does not send `RequestStarted` events while the main thread is busy. This means that for a site that downloads a hefty script as its last resource, Lighthouse will stop recording if the parse and execution time exceeds our PAUSE_AFTER_LOAD value which is currently 500ms.

I have a host of example traces of `https://travis-ci.org/GoogleChrome/lighthouse/branches` where we normally stop recording ~8 seconds before the page is actually finished loading due to a 3s script execution that kicks off all of the actual page resources.

**Comment by wardpeet** [comment]
Is this a bug we will fix or rather wait for devtools/chrome?

**Comment by patrickhulce** [comment]
@wardpeet we're going to have to work around it, apparently from the DevTools side it's working as intended to keep overhead of instrumentation low. We still get the accurate timestamps of the network requests so it's really only for detecting how long to trace.

**Comment by patrickhulce** [comment]
not that big of a deal anymore
