### ISSUE TITLE
Speed Index Metric

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#197]
Let's consume speedline https://github.com/pmdartus/speedline 

And power it using our trace. (We already collect `'disabled-by-default-devtools.screenshot'` so we're all good)

**Comment by paulirish** [comment]
@samthor me and @samccone have been widdling away at speedline's dependencies, making it much more straightforward for us to pull in.

You ready to take a crack at this?

**Comment by samthor** [comment]
Definitely. Thanks - I've been busy with a few other things but will look
in the next couple of days.

**Comment by samccone** [comment]
I can also take a look, I have lots of time this weekend.

**Comment by pmdartus** [comment]
I have opened a [PR](https://github.com/pmdartus/speedline/pull/14) to allow to consume speedline as a module. Let me know, if you have extra concerns to integrate it.

**Comment by samthor** [comment]
@pmdartus that PR looks good to me.

**Comment by paulirish** [comment]
fixed by #239
