### ISSUE TITLE
Don't truncate actual text (file names)

### ISSUE THREAD

**Issue by jamesshannon** [GoogleChrome/lighthouse#1975]
Truncation of file names tends to make it really difficult to track down the source. For example:

![lighthouse_report__http___www_marketwatch_com_story_stock-markets-old-friend-volatility-threatening-to-make-a-glorious-return-2017-03-24](https://cloud.githubusercontent.com/assets/761381/24775291/311d4614-1aea-11e7-96a4-7807fdac93ee.png)

What file is that? Where did it come from? How can I view it?

You should rely on CSS to do the truncation, and probably set the title attribute for hovering purposes. I believe that when CSS-truncated text is copied then it copies correctly. Because it's important to be able to view the file contents for greater context. Maybe it should be a link?

**Comment by ebidel** [comment]
Using `title` to sho the full URL on hover is a good idea. We do that in a couple of other formatters: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/report/partials/cards.html#L5.

**Comment by patrickhulce** [comment]
Need better UX on displaying URLs as a whole.

**Comment by AymenLoukil** [comment]
Just a simple hover text would be fine to copy the url :https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_tooltip

**Comment by connorjclark** [comment]
These items are now anchor elements, so it's clear what the resource is now. Closing.
