### ISSUE TITLE
appveyor build broken on --perf smoketest

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#1976]
example run: https://ci.appveyor.com/project/paulirish/lighthouse/build/928/job/j34fb8vx4rwjh6rp

@patrickhulce it looks like you might have been trying to fix this [here](https://github.com/GoogleChrome/lighthouse/pull/1958/files#diff-b8e76f1137b1f350d675e8c5cc1ed3b6L5) by extending the trace long enough to find a quiet window, but no dice. Any insight?

**Comment by patrickhulce** [comment]
Looks like it's been broken ever since Paul added the perf config to smoke tests, so who knows how long it's actually been failing on Windows haha :)

**Comment by brendankenny** [comment]
ah, I had assumed you extended that to 5000ms to fix appveyor specifically :)

**Comment by patrickhulce** [comment]
Ha, no that was to allow enough room to still find the new TTI metrics too. 

Here's some progress https://ci.appveyor.com/project/paulirish/lighthouse/build/938/job/m3ga9cq732p9ce64

I'll open a PR for it.
