### ISSUE TITLE
 Site Redirects HTTP Traffic to HTTPS shouldn't stop the execution if failling

### ISSUE THREAD

**Issue by jandry** [GoogleChrome/lighthouse#1978]
Site Redirects HTTP Traffic to HTTPS shouldn't stop the execution if failling

Actually if you don't server http at all, the test is faillingbut it also stop the process and the report is not generated

See logs
[logLightHouse.txt](https://github.com/GoogleChrome/lighthouse/files/905585/logLightHouse.txt)

**Comment by ebidel** [comment]
This is unrelated to the "Site Redirects HTTP Traffic to HTTPS" audit.

In this case,`https://localhost:3002` is an invalid URL. e.g. it returns an error page if you visit it in the browser. That's why you see the "Unable to load the page. Please verify the url you are trying to review." error from LH.  We're unable to even begin auditing the page :)

Normally, LH returns a report if the site doesn't redirect from HTTP to HTTPs. e.g. `lighthouse http://example.com/` will fail that audit.

One thing we could do is try the HTTP version of the URL if users start with it and the HTTPs version fails right away. But then we're testing a different URL than they specified :)

**Comment by patrickhulce** [comment]
@ebidel, the behavior @jandry is referring to is accurate. If there's no server listening at all on http then the run is fatal (which is frequently the case when locally testing http2), and we are in fact "testing a different URL than they specified" for the purposes of the audit :)

Also related is #1217.

Thanks for filing @jandry! We've been hoping to take a totally different approach to this audit to eliminate the pass entirely and speed up the results too.

**Comment by ebidel** [comment]
Thanks for the context. `localhost` was a misleading example in the logs :)

To summarize, these produce slightly different errors:

```
lighthouse https://doesnt.serve.HTTPS.domainexists.com
...
GatherRunner:error net::ERR_CONNECTION_CLOSED
Unable to load the page. Please verify the url you are trying to review.
```

```
lighthouse https://doesnt.serve.HTTP.domainexists.com
...
GatherRunner:error net::ERR_EMPTY_RESPONSE
Unable to load the page. Please verify the url you are trying to review.
```

and we need to handle the second. The run shouldn't be fatal and no audits should be failing if you've disabled HTTP on the site (e.g. https://github.com/GoogleChrome/lighthouse/issues/1217).

Is there a good URL that serves https but not http? Would be nice to have tests for this.

**Comment by patrickhulce** [comment]
Unfortunately I haven't found one and end up using `localhost` to test, far too many sites have this situation the other way around with a server on http only and not https, haha :)

**Comment by jandry** [comment]
@ebidel localhost is used to develop a web site locally. So that's normal that you can't reach it, it's running on myPC
In my case I've something responding on https://localhost:3002 but nothing on http://localhost:3002 => so test crash and lighthouse doesn't generate the report... which is bad. It should simply say that the test failed and continue to generate the report.

Yes I think it's duplicated of #1217.

**Comment by jandry** [comment]
Even more, I not really sure the test should fail if you have no http at all. But that's another issue

**Comment by ebidel** [comment]
I'm aware of localhost :) Most people don't setup ssl for localhost so I thought that was the issue in your log example. On top of that, we have a similar error message (`"Unable to load the page. Please verify the url you are trying to review."` for cases where the start URL is unreachable. Ha.

> I not really sure the test should fail if you have no http at all. But that's another issue

Yea, don't think you should fail. We may want to warn instead (e.g. Lighthouse can't make the determination if the audit passes).

**Comment by jandry** [comment]
@ebidel  warning is a good idea. (Ok for localhost sound strange to me :) )

**Comment by CharlesOkwuagwu** [comment]
@jandry , @ebidel is there a temporary workaround for localhost?

The best I can think of for now is to serve both http and https from the same port using https://github.com/mscdex/httpolyglot

**Comment by andrewluetgers** [comment]
I just ran into a very confusing problem related to this testing on localhost. My node server was hosting http and https on different ports as usual. Lighthouse seems to expect http and https to be hosted on the same port. This was NON OBVIOUS. Please state this clearly somewhere.

My solution https://stackoverflow.com/questions/22453782/nodejs-http-and-https-over-same-port#answer-32665252

**Comment by lrn2prgrm** [comment]
If possible the tool should allow specifying localhost ports... that could help with this issue

**Comment by Stubenhocker1399** [comment]
#3541

**Comment by paulirish** [comment]
Patrick to look at if he can intuit what changes brendan wanted in #2461. If he can, he'll explore 'em.
