### ISSUE TITLE
Improve lighthouse results `extendedInfo` structure guarantee

### ISSUE THREAD

**Issue by wwwillchen** [GoogleChrome/lighthouse#1981]
Lighthouse results `extendedInfo` property tree is sometimes not defined. I came across this issue when working on plots, and I created a `safeGet` function as a workaround: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/traces/pwmetrics-events.js.

As @brendankenny is working on re-enabling closure compiler, we'll want to have a less hacky way of dealing this issue and still be type-checking friendly.

**Comment by paulirish** [comment]
dupe of #2165 basicallly
