### ISSUE TITLE
Plots: testing effect of launching (or not) a new Chrome for every test.

### ISSUE THREAD

**Issue by wwwillchen** [GoogleChrome/lighthouse#1982]
See #817 

* See what the overhead of starting Chrome is for each run as we throwaway the results from the first run due to concerns that it's not representative of later runs
* Does not opening a new chrome every time have a significant impact on metrics, since e.g. users don't (usually) open a new instance every time they want to test their site in devtools.

**Comment by wwwillchen** [comment]
Did some simple benchmarking on my computer:
~550-600 ms to start chrome
~200-250 ms to kill chrome

Given that the average run takes ~20 seconds, a <1 second overhead for a fresh Chrome doesn't seem too bad.

**Comment by patrickhulce** [comment]
Can we get a link to the data on what impact on the metrics that a fresh chrome vs. an already open chrome has for posterity? :) If only the https://github.com/GoogleChrome/lighthouse/issues/1982#issuecomment-293397141 analysis was done, maybe we can just leave open for now to track that research.

**Comment by wwwillchen** [comment]
There's evidence that the first run can take longer for some sites compared to subsequent runs. For example, see the line plots in and notice how run 0 is higher on average than run 1. https://googlechrome.github.io/lighthouse/plots/archive/20170411-run-from-japan/index.html
