### ISSUE TITLE
Lighthouse score badge for PWA GitHub repos

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChrome/lighthouse#2005]
(Not sure it is right place to submit this feature request.)

What about Lighthouse score badge (https://shields.io) for PWA GitHub repos? ;)

**Comment by patrickhulce** [comment]
I love it :) perhaps this could be added over in the [PWA directory](https://github.com/GoogleChrome/gulliver)

**Comment by FluorescentHallucinogen** [comment]
@patrickhulce, [PWA Directory](https://github.com/GoogleChrome/gulliver) is cool, but it runs Lighthouse only for registered PWAs.

I think it should be continuous integration (CI) task. In this case it can be used as a tool to test/prevent Lighthouse score degradation for pull requests.

Also I think it should be integrated into https://shields.io (https://github.com/badges/shields).

**Comment by ebidel** [comment]
@FluorescentHallucinogen we have a working prototype of scoring PRs with Lighthouse. Expect it in the Google I/O timeframe :)

**Comment by FluorescentHallucinogen** [comment]
GitHub has launched [GitHub Marketplace](https://github.com/marketplace): https://github.com/blog/2359-introducing-github-marketplace-and-more-tools-to-customize-your-workflow

Does it make sense to publish Lighthouse in GitHub Marketplace?

**Comment by pinkhominid** [comment]
Hi @ebidel. Is there an update on where that prototype can be found?

**Comment by pinkhominid** [comment]
Found it :) https://github.com/ebidel/lighthouse-ci

**Comment by emazzotta** [comment]
@FluorescentHallucinogen Shameless plug, I just created such a project: https://github.com/emazzotta/lighthouse-badges

Not sure if this should be integrated with Lighthouse or stay as its own repo, opinions?

**Comment by brendankenny** [comment]
We're still exploring the CI space (but so are lots of other folks), but in the meantime
- https://github.com/emazzotta/lighthouse-badges can generate badges through whatever build process you have today
- https://github.com/ebidel/lighthouse-ci has a github bot to comment on/block PRs based on thresholds. Maybe @ebidel would be receptive to adding an endpoint for badges :)

Closing this issue as at least the basics are covered. Feel free to comment/open a new issue if you have a more specific idea that can't currently be implemented.
