### ISSUE TITLE
Allow disabling storage reset in extension

### ISSUE THREAD

**Issue by xPaw** [GoogleChrome/lighthouse#2012]
Running lighthouse in Chrome extension resets all storage, which breaks authentication on a site I'm testing (stores in localstorage). Looking at the code, there is a `disableStorageReset` flag, but there is no such option in the extension.

-----

EDIT: related: #2599, #2838

**Comment by mgibas** [comment]
u can use cli for now:
`lighthouse https://google.com --disable-storage-reset --view`

**Comment by wardpeet** [comment]
Hey,

It seems like we're not going to consider this issue anymore. We currently have https://github.com/GoogleChrome/lighthouse/pull/9193 open to redoing the whole extension.

Thank you for understanding.
