### ISSUE TITLE
lighthouse-background contains un-minified report-renderer v2

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2014]

**Comment by brendankenny** [comment]
I assume this is because runner includes the v2 report generator, and the report generator `fs.readFileSync`s in all the report-renderer files

**Comment by brendankenny** [comment]
The extension is still going to need it for generating a viewable report, so maybe we need a flag for the extension gulpfile for whether or not to include the report renderer

**Comment by ebidel** [comment]
Yea same for Viewer.
