### ISSUE TITLE
Update outdated link for "Web App Install Banners" article

### ISSUE THREAD

**Issue by kosamari** [GoogleChrome/lighthouse#2035]
While looking at lighthouse and using resources it gives me as learning material, noticed ["Web App Install Banners"](https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android) article linked in **User can be prompted to Add to Homescreen** audit is out of date.  (canonical article in /web is [here](https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/))

Probably nice to directly link new article than having use click through 2 pages :)

- out-of-date article : https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android
- new article link : https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/

**Comment by ebidel** [comment]
Thanks for the bugs @kosamari. Keep'em coming!
