### ISSUE TITLE
Add "record my clicks before running tests" feature

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/lighthouse#2039]
Some websites require some user interaction to be able to unveil some new UI (such as clicking on a "play" button to play a video) and it would be great if Lighthouse support some kind of "start record / stop record" button that record all user interactions before running some audits / tests.

cc @samdutton

**Comment by ebidel** [comment]
Related: 
- "Live mode" pause on violation - https://github.com/GoogleChrome/lighthouse/issues/735
- https://github.com/GoogleChrome/lighthouse/issues/1769 - potentially not reloading the page. Get it in a state, and audit.

**Comment by paulirish** [comment]
Related: testing entire login route #2058

**Comment by paulirish** [comment]
duping into #1418
