### ISSUE TITLE
top level warning icons flash square

### ISSUE THREAD

**Issue by stramel** [GoogleChrome/lighthouse#2042]
This is probably low priority but just kills my OCD.

When clicking to expand/collapse an audit above an audit with a circle warning icon. All warning icons below the expanding audit switch to squares and back to circles.

Clicking the top audit here will trigger both warning circles below it to change to squares
![image](https://cloud.githubusercontent.com/assets/855184/25207127/0597f398-2532-11e7-991b-ed15f4256807.png)

**Before:**
![image](https://cloud.githubusercontent.com/assets/855184/25207155/3f9ff8ce-2532-11e7-86f7-c117c16328f5.png)

**During:** (Managed to screenshot it during the transition so y'all know I'm not some crazy dude.)
![image](https://cloud.githubusercontent.com/assets/855184/25207163/5671cb2c-2532-11e7-9dc1-76e0e0b4a2eb.png)

**After:**
![image](https://cloud.githubusercontent.com/assets/855184/25207233/a5610b6c-2532-11e7-970a-c24205f95ab5.png)

Site used to generate report: https://q-citrix.salesnext.com/login

**Comment by wardpeet** [comment]
we are reworking the report so we won't fix this anymore but we will make sure we won't have it on the new one ;)

thanks for reporting!

//cc @ebidel @paulirish
