### ISSUE TITLE
opinionated "unoptimized images" audit is opinionated

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#2044]
Just a general first impression of the "unoptimized images" audit now that I've dived into it

The comments in the audit source say that the audit fails when:

* a JPEG / bitmap can be at least 10KB smaller when canvas-encoded
* any image can be at least 100KB smaller when WebP-encoded
* total savings can be greater than 1MB by encoding all images with WebP

So really, the audit is mainly "look at how much you can save with WebP". But it still doesn't have support Firefox, Edge, or Safari, so that seems like a moot point for a solid chunk of our audience

Is there any way to optimize imgs using the original format? I know it's kinda arbitrary, b/c you could optimize the heck out of a JPEG, but if it looks like garbage, then the optimized version isn't valid. But for me personally, I'd be way more interested if LH said "here's an optimized version of your img, and this is how much you could save". Maybe LH could do a side-by-side right there so that the user can see whether the optimized version is valid.

Maybe another way to approach this would be to just flag images larger than some arbitrary size? Or to warn when the total amount of images exceeds some arbitrary limit?

**Comment by patrickhulce** [comment]
@kaycebasques it felt wrong adding those conditions at the time, and I still don't like them now. In report v2 there should be no notion of failure here at all, and only potential savings will be reported. I think it's valuable to call out that WebP has substantial savings and that by serving WebP/JPEG XR you'd be able to serve ~60% of global users considerably fewer bytes, but it's hard to identify what images users would want to save to their computer (which probably shouldn't use WebP) and if it's worth the considerable effort to re-encode to multiple formats. 

I'd propose splitting this into two audits in the new world of savings only where we only check for most glaring violations in one (quality=95 JPEG, PNG crush, etc), and more aggressive optimizations in the other (WebP quality=80).
