### ISSUE TITLE
Use yarn on travis rather than NPM

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2048]
for locked dependencies and smaller error text.

Would love an external contributor to help us out on this. Shouldn't be too bad.

I think we can just revert https://github.com/GoogleChrome/lighthouse/pull/994 .. Might be as simple as that!

**Comment by stramel** [comment]
@paulirish This can be closed now with #2051 and #2067 merged.

**Comment by paulirish** [comment]
thx!
