### ISSUE TITLE
Date.now() advice is wrong in certain cases

### ISSUE THREAD

**Issue by silverwind** [GoogleChrome/lighthouse#2053]
[This page](https://developers.google.com/web/tools/lighthouse/audits/date-now) says

> Replace each of these calls with `performance.now()`.

This will only work if the absolute timestamp is irrelevant to the application as `performance.now()` returns relative timestamps while `Date.now()` returns absolute ones. If this check stays (which seems kind of unnecessary to me as often, one does not need sub-second precision), a better advice for a `Date.now()` replacement would be

```js
Math.round(performance.timing.navigationStart + performance.now())
```

**Comment by patrickhulce** [comment]
audit is gone
