### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by mosh2151984** [GoogleChrome/lighthouse#2061]
**Lighthouse Version**: 1.6.5
**Chrome Version**: 57.0.2987.133
**URL**: https://moshtest.com/home
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9254:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by wardpeet** [comment]
did you cancel a trace before?

**Comment by mosh2151984** [comment]
yeah I tried to cancel it and run it again uninstall it and reinstall it on chrome canary works good on canary

**Comment by wardpeet** [comment]
thanks for reporting, more people have this issue. I'll be closing this one in favor of #1091 please follow that issue to get any updates.
