### ISSUE TITLE
Lighthouse doesn't clear browser cache before running

### ISSUE THREAD

**Issue by trueadm** [GoogleChrome/lighthouse#2064]
I'm building a benchmark runner tool that runs various different benchmark implementations through Lighthouse and compares the performance statistics. 

The issue I'm having is that it appears that Lighthouse has an aggressive cache, and returns the first benchmark each time – even though the backend is serving different content on the same URL (`http://localhost:8080` in this case).

If I tell Lighthouse to look at a different URL, this is no longer an issue (for example `http://localhost:8080/benchmark2`). The thing is, I don't want Lighthouse to cache anything when loading `http://localhost:8080`. If I load Chrome Canary locally and refresh the same URLs manually, I don't have this issue.

You can see how I'm setting up Lighthouse and using it on this fork:

https://github.com/trueadm/react/blob/add_benchmarking_infra/scripts/bench/benchmark.js#L98

Thank you!

**Comment by paulirish** [comment]
Hey @trueadm.. good to have you around these parts. :) Would love to help you out with this.

I'm getting things in place to repro your issue. I'll also hang in https://gitter.im/GoogleChrome/lighthouse if you wanna increase the communication throughput. ;)

**Comment by trueadm** [comment]
@paulirish Let me know if you want any more clarification. I can also confirm this bug is happening when the server cache control response is `no-cache`. I'll hang around in Gitter too :)

**Comment by paulirish** [comment]
turned out to be a bug with the `http-server` module and it not closing on demand. weirdness.

a fix is https://github.com/trueadm/react/pull/2

(and we also cleaned up chrome launching in https://github.com/trueadm/react/pull/1)


booyah!
