### ISSUE TITLE
Investigate why we have waitForLoaded in driver

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#207]
is anyone using this?

**Comment by brendankenny** [comment]
@paullewis added it originally, so may have had a plan there. Given the addition of/changes to the scheduler since then, I doubt we'll ever want this. Any sort of shenanigans there would be something more explicit in the scheduler rather than in the driver.

**Comment by paullewis** [comment]
100% in favor of removing it.

**Comment by paullewis** [comment]
I'll take this.
