### ISSUE TITLE
Perf audit: Inline the critical CSS

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2073]
While we currently look at blocking stylesheets and their size, we don't investigate wether the critical CSS for the above-the-fold content is inlined. 
We should! I think we can also estimate pageload time savings we'd expect (like our other perf audits).

see also: https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

Lots of ways to do this, especially with the new code coverage for CSS. 
This'll be a big one, and not trivial to implement, but it should provide a lot of insight.

Anyone interested?

**Comment by ev1stensberg** [comment]
Can I work on this in 2weeks or so @paulirish ?

**Comment by paulirish** [comment]
Sure, though i think you should get started in the codebase with something a tad easier...
for example https://github.com/GoogleChrome/lighthouse/issues/1798

**Comment by ev1stensberg** [comment]
Sure! 👌

**Comment by paulirish** [comment]
Our render blocking audit is prettty close to this but just hoists all the responsibility to the dev.

This idea would provide BETTER numbers, but really just making critical css extraction easier for developers is probably the most useful thing. Lighthouse mastering it for an implementation detail seems like overkill. ;)
