### ISSUE TITLE
report-styles.css are global

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2075]
A devtools integration item here. :)

These styles at the top of [report-styles.css](https://github.com/GoogleChrome/lighthouse/blob/8b47006efc2e4e27753d3eed5928f55652964447/lighthouse-core/report/v2/report-styles.css#L17-L53) end up applying to all of chrome devtools. :)
The `body` rule is the particular conflict.

@ebidel we could..

1. scope these to within the existing `.lh-report` element.
2. add a new `.lh-root` element to be a little more explicit.
1. something else? (like use [`unset`](https://developer.mozilla.org/en-US/docs/Web/CSS/unset) perhaps..)

**Comment by ebidel** [comment]
4. Shadow DOM!!!!!!!!!!!!!!!!!!!!

I like `.lh-root`. Here ya go: https://github.com/GoogleChrome/lighthouse/pull/2076
