### ISSUE TITLE
Adopt web components

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#2077]
Justification is getting fairly clear. Here's the data:

- We've already started modularizing JS/CSS/HTML by breaking up files.
- In https://github.com/GoogleChrome/lighthouse/pull/2000#issuecomment-296331228, Paul mentioned the word "component" appeared 5! The feedback discusses standalone UI components that expose a common API, fire custom events, and are able to swap out different underlying implementations based on context. **#that's a web component!**
- In https://github.com/GoogleChrome/lighthouse/pull/2057#discussion_r113511390, Pat brought up  the need for "distinct reusable components". **#that's a web component!**
- https://github.com/GoogleChrome/lighthouse/issues/2075 ran into styling collisions without our global css.
- Best reason yet...Yesterday I found out that DT already [registers](https://cs.chromium.org/search/?q=Node+file:%5Esrc/third_party/WebKit/Source/devtools/front_end/+registerCustomElement&type=cs) some 25+ custom elements. **#those ARE web components!**
- Filmstrip implements its own sparkline component. Now we have 2 sparklines. - https://github.com/GoogleChrome/lighthouse/issues/2077#issuecomment-300032654

<img width="923" alt="screen shot 2017-04-25 at 8 54 59 pm" src="https://cloud.githubusercontent.com/assets/238208/25453539/2c7bc6c8-2a7e-11e7-93b9-a83a5fff1e8d.png">

Lolz!! At this point it's pretty silly that we're avoiding custom elements.

**Comment by ebidel** [comment]
The **export button** is a great case study...

_templates.html_ is as usual:

```html
<template id="tmpl-lh-export-button">
  <div class="lh-export">
    <button class="report-icon report-icon--share lh-export__button" title="Export report"></button>
    <div class="lh-export__dropdown">
      <a href="#" class="report-icon report-icon--print" data-action="print">Print...</a>
      <a href="#" class="report-icon report-icon--copy" data-action="copy">Copy JSON</a>
      <a href="#" class="report-icon report-icon--download" data-action="save-html">Save as HTML</a>
      <a href="#" class="report-icon report-icon--download" data-action="save-json">Save as JSON</a>
      <a href="#" class="report-icon report-icon--open" data-action="open-viewer">Open in Viewer</a>
    </div>
  </div>
</template>
````

_export-button.js_

Most of the code in report-features.js goes bye bye and into the component:

```javascript
class LighthouseExportButton extends HTMLElement {
  get templateSelector() { return '#tmpl-lh-export-button'; }

  constructor() {
    super();
    this.items = this.querySelector('.lh-export__dropdown');
    this.addEventListener('click', this.show);
  }

  // Lifecycle methods come for free with custom elements. Will be great for our SPA stuff.
  disconnectedCallback() {
    this.removeEventListener('click', this.show);
  }

  useTemplate(tmpl) { // Support our template injection stuff.
    this._tmpl = tmpl;
    this.appendChild(tmpl);
  }

  // Create an common API that mimics devtools.
  appendItem(title, action, handler) {
    const a = document.createElement('a');
    a.className = `report-icon report-icon--${action}`;
    a.dataset.action = action;
    this.items.appendChild(a);
  }

  clearItems() {
    this.items.textContent = '';
  }

  show() {
    el.classList.toggle('active');
  }

  ... other code from report renderer ...
}

class DevToolsExportButton extends LighthouseExportButton {
  constructor() {
    super();
    this.clearItems();
    this.menu = UI.ContextMenu();
  }

  appendItem(title, handler) {
    this.menu.appendItem(title, handler);
  }

  show() {
    this.menu.show();
  }
}
```

Ok, here comes the neat part. Ready?!

For DevTools/<ANYONE ELSE>, all we have to do is **replace 1 line of code** to change how `<lh-export-button></lh-export-button>` behaviors, renders, styles itself, etc. Just register the tag with a different class:

```javascript
const ExportButtonClass = DEVTOOLS ? DevToolsExportButton : LighthouseExportButton;
window.customElements.define('lh-export-button', ExportButtonClass);
```

But we'd probably be creating it dynamically in report renderer:

** report-renderer.js**

```javascript
LH._renderReportHeader() {
  ...
  const button = this._dom.createElement('lh-export-button');
  button.useTemplate(this._dom.cloneTemplate(button.templateSelector, this._templateContext));
  button.appendItem('Item Three', e => { ... });

  return header;
}

DevTools._renderReportHeader() {
  ...
  const button = this._dom.createElement('lh-export-button');
  button.useTemplate(this._dom.cloneTemplate(button.templateSelector, this._templateContext));
  button.appendItem('Item One', e => { ... });
  button.appendItem('Item Two', e => { ... });
  button.appendItem('Item Three', e => { ... });

  return header;
}
```

**Comment by ebidel** [comment]
Let's look at our **Gauge** "component" since we reuse it a few times 

The render code would go from this:

```javascript
renderScoreGauge(category) {
  const tmpl = this._dom.cloneTemplate('#tmpl-lh-gauge', this._templateContext);
  this._dom.find('.lh-gauge__wrapper', tmpl).href = `#${category.id}`;
  this._dom.find('.lh-gauge__label', tmpl).textContent = category.name;

  const score = Math.round(category.score);
  const fillRotation = Math.floor((score / 100) * 180);

  const gauge = this._dom.find('.lh-gauge', tmpl);
  gauge.setAttribute('data-progress', score); // .dataset not supported in jsdom.
  gauge.classList.add(`lh-gauge--${calculateRating(score)}`);

  this._dom.findAll('.lh-gauge__fill', gauge).forEach(el => {
    el.style.transform = `rotate(${fillRotation}deg)`;
  });

  this._dom.find('.lh-gauge__mask--full', gauge).style.transform =
      `rotate(${fillRotation}deg)`;
  this._dom.find('.lh-gauge__fill--fix', gauge).style.transform =
      `rotate(${fillRotation * 2}deg)`;
  this._dom.find('.lh-gauge__percentage', gauge).textContent = score;

  return tmpl;
}
```

to a tight black box:

```javascript
renderScoreGauge(category) {
  const gauge = document.createElement('lh-gauge');
  gauge.score = 90;
  gauge.category = category;
  return gauge;
}
```

**Comment by ebidel** [comment]
annnnnnd another.

The filmstrip would be way nice as a component and could reuse sparkline subcomponents.
Mentioned "sharing code" in https://github.com/GoogleChrome/lighthouse/pull/2181/files/94d2384a10a5f2d102ce3816ab7cf189d677eb91#r115310384.

Now: 

```html
<div class="lh-timeline">
  <div class="lh-filmstrip">
    ...
    <div class="frame">
      <div class="time">700</div>
      <div class="thumbnail"><img src="data:image/jpg;base64,...</div>
    </div>
  </div>
  <div class="lh-timeline-marker">
    <div class="lh-timeline-bar" style="width: 94%;"></div><span>First contentful paint:</span> <span class="lh-timeline-subtitle">583&nbsp;ms</span>
  </div>
  ...
</div>
```

Could be:

```html
<lh-timeline>
   <lh-filmstrip>
    ...
    <lh-frame time="700" src="data:image/jpg;base64,..."></lh-frame>
  </lh-filmstrip>
  <lh-sparkline label="First contentful paint" percent="94" val="583 ms"></lh-sparkline>
</lh-filmstrip>
```

Calling code would be  reduced to a few lines:

```javascript
const timeline = document.createElement('lh-timeline');

const filmstrip = document.createElement('lh-filmstrip');
filmstrip.frames = [..., {time: 700, src: 'data:image/jpg;base64,...'}];
timeline.appendChild(filmstrip);

for (const metric of metrics) {
  const sparkline = document.createElement('lh-sparkline');
  sparkline.label = 
}
```

We could use standalone sparklines in other places throughout the report:

```
<lh-sparkline label="Reduce render blocking scripts" percent="94" val="10 ms" secondary="100kb savings"></lh-sparkline>
```

**Comment by benschwarz** [comment]
Theres definitely a case to improve the frontend code there @ebidel, I've been thinking that a bit recently myself. 

Should we bikeshed the component technology sometime after i/o? 😂

**Comment by abdonrd** [comment]
Totally in favor of this issue! 👍

**Comment by brendankenny** [comment]
this is the best thread ever and makes a compelling case for switching over. As the report has become more dynamic, it's getting clearer we need some kind of extra help beyond our homemade templating system.

But we don't need the bug open to consult it in the future, so I'm going to close ❤️ ❤️
