### ISSUE TITLE
Audit error: ... axe.run arguments are invalid

### ISSUE THREAD

**Issue by RichMorin** [GoogleChrome/lighthouse#2078]
When I run Lighthouse on this page:

  http://wiki.cfcl.com/Projects/AxArd/WebHome

All of the Accessibility checks get this nastygram:

  Audit error: Required Accessibility gatherer encountered an error: axe.run arguments are invalid

This seems a lot like a problem with the plugin, but it might be something wonky with the page.
How can we track this down?

-r

**Comment by paulirish** [comment]
This is a fascinating bug and we've certainly not run into it before. 

We'll keep an eye out and see if we can figure this out.

**Comment by stramel** [comment]
Also getting this, a big fat ZERO on accessibility... :sob: 

https://gist.github.com/stramel/de5976a460b432d80f51f0be9f6873a7

**Comment by paulirish** [comment]
Stramel, is it reproducible?

**Comment by stramel** [comment]
@paulirish Yes, I am able to reproduce in the following scenarios.

Accessibility paired with; PWA or Performance audits.

Seems like Best Practices works with it.

You can test on https://q-citrix.salesnext.com/login

**Comment by paulirish** [comment]
@stramel I'm seeing a different error in your gist:

> Required Accessibility gatherer encountered an error: Protocol error (Runtime.evaluate): Object reference chain is too long

Were you also seeing the `axe.run arguments are invalid` error?

**Comment by stramel** [comment]
/facepalm no, sorry, it's pretty late here maybe I need some sleep :sweat_smile: Would you like me to log as a separate bug in the morning?

**Comment by patrickhulce** [comment]
suspected resolved by axe roll
