### ISSUE TITLE
Result of performance metrics vary widely.

### ISSUE THREAD

**Issue by julianusti** [GoogleChrome/lighthouse#2080]
We are trying to integrating Lighthouse to our Jenkins pipeline, unfortunately the result of `performance metrics`, especially for `Time To Interactive` metric, vary widely based on way you run a test. 

**Software:**
Chrome version: Version 58.0.3029.81 (64-bit)
Lighthouse version: 1.6.5
OS: MacOS Sierra v.10.12.4

### 1. Using Lighthouse chrome extension:
![screen shot 2017-04-27 at 11 48 10](https://cloud.githubusercontent.com/assets/2780263/25477908/72d0e038-2b3f-11e7-9761-9aa144dc2f77.png)
`Time To Interactive`: 4903.9ms

### 2. Using Lighthouse api.
Example taken from:  https://github.com/GoogleChrome/lighthouse#using-programmatically

![screen shot 2017-04-27 at 11 39 30](https://cloud.githubusercontent.com/assets/2780263/25478011/d4da282a-2b3f-11e7-8d56-02375d7d0d07.png)
`Time To Interactive`: 15392.5ms

In many cases there is an issue with `Time To Interactive` metric:
![screen shot 2017-04-27 at 11 20 35](https://cloud.githubusercontent.com/assets/2780263/25478023/e2c1efd6-2b3f-11e7-925d-2d4e83d660a7.png)
`Time To Interactive`: nothing...

### 3. Using Lighthouse cli:
cli version produce more the less the same results, which is great.

![screen shot 2017-04-27 at 11 27 07](https://cloud.githubusercontent.com/assets/2780263/25478260/b49eaa12-2b40-11e7-8d54-8f24247d160e.png)
`Time To Interactive`: 2987.2ms

I have to admit that cli version is much more stable and doesn't  vary so widely as the other examples.

Any ideas how to debug or fix the second example (Lighthouse api) so it behaves like the last example (Lighthouse cli) ?

**Comment by patrickhulce** [comment]
Thanks for the report @julianusti! We've actually spent a lot of effort over the past several weeks working on our metrics, and we've got some new iterations in the upcoming release we're pretty stoked about that should be more reliable and representative of a user's experience. 

That being said, we definitely would like to dig in around variance between extension/CLI/programmatic. Is the site you're testing publicly available for us to take a look? There shouldn't be any fundamental differences between CLI and programmatic in node since the CLI calls lighthouse programmatically in node :) are you using the example verbatim?

**Comment by julianusti** [comment]
Hi @patrickhulce, sorry my bad, I forgot to include a link.
You can definitely access our website publicly :) In particular this [page](https://www.zalando.de/nike-performance-free-rn-laufschuhe-natural-running-n1241a0ez-q12.html), which is product details page.

>There shouldn't be any fundamental differences between CLI and programmatic in node since > the CLI calls lighthouse programmatically in node :)

That's what I was also thinking about :) I would spend a little bit more time on this issue, but for now, I just want to get at least a working version for our Jenkins pipeline, which I do have, by simply spawing the process and do some calculations based on previous test's result.
>are you using the example verbatim?

What is this about?

**Out of topic:**
 I know it's not subject related, but we besides storing the result to the **file system**, we also want to store it to **s3**. Do you think it make sense to contribute it directly to Lighthouse?

**Comment by benschwarz** [comment]
> Out of topic:
> I know it's not subject related, but we besides storing the result to the file system, we also want to store it to s3. Do you think it make sense to extend Lighthouse with this functionality?

Because this can be done with a one-liner: `aws s3 put reports/website-report.json s3://my-website-report-bucket/reports/today/report.json`, I don't think it really needs to make its way into LH.

**Comment by julianusti** [comment]
@benschwarz make sense.

**Comment by patrickhulce** [comment]
we've got all new shiny metrics that should be much better in this regard :)
