### ISSUE TITLE
'No screenshots found in trace' and 'Cannot read property 'ts' of undefined'

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#2082]
I get the following error running Lighthouse 1.6.5 on Chrome 57.0:

![image](https://cloud.githubusercontent.com/assets/205226/25481689/39428b3a-2b46-11e7-87d1-eaaf0978e92f.png)

Report uploaded [here](https://googlechrome.github.io/lighthouse/viewer/?gist=42f9913f4c70fde6c91af6e7dcd739c3).

**Comment by samdutton** [comment]
Second run works fine.

Third run I get this:

![image](https://cloud.githubusercontent.com/assets/205226/25481786/af85e134-2b46-11e7-9963-153f96fe4931.png)

Report [here](https://googlechrome.github.io/lighthouse/viewer/?gist=7ac894a2892010f245dcf92fb5d7add9).

**Comment by patrickhulce** [comment]
@samdutton we've been hunting a cause for this one down for a while, any additional environment information (OS, xvfb, etc) you can provide that might help us?

**Comment by samdutton** [comment]
Hi @patrickhulce.

OS is Mac 10.12.04.

Excuse my ignorance, but what's xvfb :)?

Let me know if anything else would help.

**Comment by patrickhulce** [comment]
Oh xvfb is a virtual display commonly used to run Chrome on servers. This just seems to happen more frequently when run on linux using virtual displays like xvfb (travis runs into this issue *a lot* but it's been hard to reproduce locally :/). Thanks for the info!

going to close and merge this with #1738
