### ISSUE TITLE
Can I configure how many times to run a test?

### ISSUE THREAD

**Issue by julianusti** [GoogleChrome/lighthouse#2084]
Currently, when you execute a test it runs two times.

 - Does it takes the average values/metrics from two tests and then provides the end values/metrics?
 - If the first assumption is valid then is this option configurable?

**Comment by patrickhulce** [comment]
Are you referring to seeing the page load multiple times on a single `lighthouse` invocation? Currently those are called `passes` of which we do several to collection *different* pieces information about the page, so no averaging is happening out of the box. If you're interested in collecting some aggregate metrics you might want to check out [pwmetrics](https://github.com/paulirish/pwmetrics) which uses lighthouse to do exactly what you're describing.

**Comment by julianusti** [comment]
@patrickhulce thanks a lot dude, it looks like what I need :)
