### ISSUE TITLE
Disk cache is disabled for the whole run

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2089]
We disable network cache at the beginning of the run (`setCacheDisabled` in driver) and never turn it back on.

Subsequent passes don't neccessarily need cache to be disabled, so we're just slowing those down.

1. why do we disable if we just cleared the whole thing? (i am not sure) ![image](https://cloud.githubusercontent.com/assets/39191/25505838/81bfaa02-2b58-11e7-8671-c1906b152394.png)
1. do we ever need it disabled? Probably for the service-worker offline, checks, but that's probably it.

**Comment by benschwarz** [comment]
Seems like a good candidate for removal

-- Otherwise, this could be done using the flag `--disable-cache`, then the cache wouldn't need to be cleared either.

**Comment by paulirish** [comment]
> -- Otherwise, this could be done using the flag `--disable-cache`, then the cache wouldn't need to be cleared either. 

yah though we want our defaults to do everything we can for a reproducible and solid benchmarking environment.  in the CLI case, we're in a clean profile, so not a big deal, but for devtools & extension, we have a full cache to acknowledge.

that aside, i believe we can either 

1. be very precise about disabling and undisabling the cache or 
2. we ignore that completely and are satisfied with blowing away the entire ache with `clearBrowserCache`

**Comment by benschwarz** [comment]
Ah. My bad. I always forget about the differences with the extension.

**Comment by paulirish** [comment]
no worries.

talking with allada it seems like option 1 ("be very precise about disabling and undisabling the cache") is best here
