### ISSUE TITLE
Audit: SEO best practices for SPAs

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#2091]
I often get questions about SEO best practices for SPAs. Generally, there are certain practices you should follow to maximize crawlability:

- use real anchors instead of click listeners. crawlers should be able to discover links.
- use real urls instead of ajax`/#!/` urls (deprecated: https://developers.google.com/webmasters/ajax-crawling/docs/getting-started)
- use `<link rel="canonical">`
- using native elements where possible (`<button>` instead of `<div class="button">`). Possibly more a11y.
- polyfill older features (should already be doing)

more ref: https://www.youtube.com/watch?time_continue=583&v=JlP5rBynK3E

<a href="https://www.youtube.com/watch?time_continue=583&v=JlP5rBynK3E">
<img src="https://cloud.githubusercontent.com/assets/39191/25508050/7e0f67b0-2b64-11e7-80ce-a9872a1d6b5b.png">
</a>

More stuff in https://webmasters.googleblog.com/2016/11/building-indexable-progressive-web-apps.html

**Comment by paulirish** [comment]
https://webmasters.googleblog.com/2016/11/building-indexable-progressive-web-apps.html is Google Search's most recent guidance on the topic (posted by John, so it matches the video p well)

The recommendations: 

 * Make Your Content Crawlable
 * Provide Clean URLs
 * Specify Canonical URLs
 * Design for Multiple Devices
 * Develop Iteratively
 * Use Progressive Enhancement
 * Test with Search Console
 * Annotate with Schema.org structured data
 * Annotate with Open Graph & Twitter Cards
 * Test with Multiple Browsers
 * Measure Page Load Performance

**Comment by RehanSaeed** [comment]
- Annotate with Schema.org structured data
- Annotate with Open Graph & Twitter Cards

These go in the HTML `head` section and require server side rendering. I've actually asked this as a StackOverflow question: ["How do you Handle HTML Metadata & SEO in Progressive Web Apps (PWA)"](https://stackoverflow.com/questions/44880720/html-metadata-seo-in-progressive-web-apps-pwa) a few days ago.

**Comment by igrigorik** [comment]
Would love to see this audit in LH! @ebidel @paulirish is this work prioritized and on the roadmap? Anything we can do to help nudge it along?

**Comment by rviscomi** [comment]
+1 to what Ilya said

It'd be great to be able to consume SEO audits from LH in HTTP Archive.

**Comment by brendankenny** [comment]
These are on our roadmap, but with @ebidel out on holiday this month, I'm not sure what the timeline looks like. I'd be happy to help someone else ramp up on writing these audits, though, if there's any interest :) 

The first steps would be to start outlining the answers to the audit criteria list we've started to put together in #2624. Basically, identify which of these are testable via Lighthouse, what would the audit(s) specifically test, what are the pass/fail states, etc.

**Comment by addyosmani** [comment]
> is this work prioritized and on the roadmap? Anything we can do to help nudge it along?

Following on from last week, I've offered the team an eng. contractor to work on implementing the SEO audits. Let's see how far we can get over the next quarter or two :)

> The first steps would be to start outlining the answers to the audit criteria list

👍  Agree with @brendankenny we should evaluate the list of audit criteria in #2624 and come up with a concrete MVP. I've seen some draft PRDs floating around so will circle back with @igrigorik and @rviscomi on them.

**Comment by rviscomi** [comment]
I can take this issue. On my immediate todo list:

- create SEO audit [config](https://github.com/GoogleChrome/lighthouse/blob/master/docs/recipes/custom-audit/custom-config.js#L25-L35)
- answer questions in #2624 

I may have some ramp-up questions :)

**Comment by paulirish** [comment]
https://github.com/GoogleChrome/lighthouse/milestone/6 now captures all the new SEO filed audits

**Comment by jdiapps** [comment]
Was this implemented?  Does lighthouse currently support SEO tests as part of it's default tests?

**Comment by kdzwinel** [comment]
[Yes](https://developers.google.com/web/updates/2018/01/lighthouse#seo) it first landed in v2.7. ATM it's available in Chrome Canary and in the extension.
