### ISSUE TITLE
Make the ChromeLauncher API into a real thing.

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2092]
<details>
<summary>
Here's a few incarnations I'm seeing of people using the ChromeLauncher API:
</summary>

![image](https://cloud.githubusercontent.com/assets/39191/25513433/e90fec4a-2b89-11e7-85b8-eaff641fd9b5.png)
![image](https://cloud.githubusercontent.com/assets/39191/25513435/ed717542-2b89-11e7-840d-a062a7b14b3e.png)
![image](https://cloud.githubusercontent.com/assets/39191/25513445/fe9a72ec-2b89-11e7-8b0f-64fbd9bd816f.png)
![image](https://cloud.githubusercontent.com/assets/39191/25513458/1c54209e-2b8a-11e7-8d21-33a5fd9bd501.png)
![image](https://cloud.githubusercontent.com/assets/39191/25513492/563ca20e-2b8a-11e7-9abd-9e4a0617969b.png)
![image](https://cloud.githubusercontent.com/assets/39191/25513503/612bfab6-2b8a-11e7-9ff5-a84890cf5ec2.png)
![image](https://cloud.githubusercontent.com/assets/39191/25513512/70a358e0-2b8a-11e7-80f0-cf4d31350bcd.png)

and this dude who's just like "wtf is autoselect?": https://github.com/siddharthkp/lighthouse-ci/blob/c3938a2523434f26ea7963b0546fb241d4f21d36/index.js

</details>

_(click above)_

and not to mention the example in lighthouse's readme [which is like whaaaaa.](https://github.com/GoogleChrome/lighthouse#using-programmatically).

There's a lot of variety and nothing I'm seeing in those snippets actually _looks correct._

**Feels like we could use chrome-launcher module that has a real first-class API.**

Something with a very clear API surface to handle launch, getting the port number (if set with 0), ability to kill.. 

It'd also be nice to have sigint [kill the process automatically as well](https://github.com/paulirish/pwmetrics/blob/4070b62ccc0e84c25fd81ce6e3e32c284f8e639b/lib/index.ts#L61-L71). (our poor manual-chrome-launcher doesn't have this currently).

wdyt?

+ @samccone @ebidel

**Comment by ebidel** [comment]
In!

**Comment by brendankenny** [comment]
> getting the port number (if set with 0), ability to kill

more on this: it's really handy to be able to run with `--port 0` to listen on a random available port, but Lighthouse needs to connect to the same port, so it needs to be able to get that information non-awkwardly...

maybe we should make a checklist of requirements :)

**Comment by benschwarz** [comment]
That'd be great! 

The Calibre Chrome launcher is really similar to the Lighthouse one, with a couple of exceptions: 

* It loads a couple of custom extensions (one for auth, one experimental one… and I've often thought about adding 'adblock' in certain circumstances — although, if chrome natively does this, that'd be even better)
* It returns a connected CRI instance with the browser (Essentially, you're not requesting a browser, but a means to talk to a browser)
* Set the start url as `run.calibreapp.com` (this resolves to localhost) — this is great because then custom extensions can be executed (although, this is probably not appropriate for LH)

Another reason this might be great to have in a module is that downstream `--headless` clients could use ChromeLauncher as a means to loading a testing environment… or a tonne of other things. Setting custom flags would be pretty great. 

I'm *very* much in support of this.

**Comment by samccone** [comment]
Seems useful.

**Comment by paulirish** [comment]
### usecase

launch for Lighthouse or Headless (via cri)

### features

feature: port (auto-)selection: 
  - if port provided as non-zero will attempt to use that port and fails if the port is unavailable
  - port as 0 will get available

feature: kill() method
feature: optional sigint-> kill ability
feature: use explicit path for chrome (otherwise we'll pick one we like)
feature: hopefully kill autoSelectChrome
feature: `WaitTillDebuggerReady` (-ish) can be used separately (on already launched Chrome)
feature: `chrome-debug` binary here too
feature: pass extra chrome flags
feature (2.0?): modify default chrome flags

### return and resolve

`launchAndConnect()` resolves ONLY when protocol is ready. (can have retry stuff built in for this)
return object - port, (pid?), (profilePath?)

### logistics
keep in repo, but publish as standalone module.

**Comment by Janpot** [comment]
Some prior discussion: https://github.com/GoogleChrome/lighthouse/issues/1176

For now I'v stepped away from lighthouse as a means to launch Chrome. I've used it for a while but solved this problem better with my container orchestrator. Also I didn't like pulling in the whole lighthouse package, just for launching a process. One feature I'd liked to have seen was pluggable logging.

**Comment by ngryman** [comment]
The features described by @paulirish would be perfect for [Speed Racer](https://github.com/ngryman/speedracer).

I would clarify a *multiple Chrome installation* use case. In my use case I need to prioritize Canary for the headless support (I think that's what Lighthouse already does right?). But others might want to prioritize mainstream Chrome.

I would prioritize Canary by default but let the user opt-out with something like this:
```js
const launcher = new ChromeLauncher({ canary: false })
```

**Comment by tomccabe** [comment]
I've been using lighthouse as a module and ham-fistedly added some of these (1, 2, 3, 4, 7 above) out of necessity to our very much in-development tool. I'd be happy to help with this, discuss our use cases, and/or add to the documentation @samccone @paulirish!

**Comment by paulirish** [comment]
This is now fixed. [chrome-launcher](https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher) is published on NPM and available:

```js
const chromeLauncher = require('chrome-launcher');

chromeLauncher.launch({
  chromeFlags: ['--show-paint-rects']
}).then(chrome => {
  console.log(`Chrome debugging port running on: ${chrome.port}`);
});
```

There is still some work remaining but please feel free to put it to use and report bugs. Thanks!
