### ISSUE TITLE
Integrate a11y audits

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#210]
https://github.com/GoogleChrome/accessibility-developer-tools/tree/master/src/audits are awesome, and I would love it if we could find a way to integrate them. At the moment they export to `goog` and require closure, but perhaps we can find a way to make it work.

**Comment by robdodson** [comment]
Nice! @alice any ideas on how to integrate the audits?

**Comment by paullewis** [comment]
I've got a path. I'm `npm i accessibility-developer-tools` and then I can try injecting `node_modules/accessibility-developer-tools/dist/js/axs_testing.js` to the page. Then pick up the evaluation and post it back to the page.... what could go wrong? (Don't answer that.)

**Comment by alice** [comment]
@paullewis They don't actually require closure (they require closure compiler, and pull one or two tiny closure utils, but the compiled version is standalone).

Your proposal seems good to me.

**Comment by alice** [comment]
s/one or two tiny closure utils/400 lines of closure utils/ ¯\_(ツ)_/¯

**Comment by paulirish** [comment]
We now have one a11y check in beta. Available from master
