### ISSUE TITLE
Required OptimizedImages gatherer encountered an error

### ISSUE THREAD

**Issue by pedro93** [GoogleChrome/lighthouse#2107]
This is an upstream report from https://github.com/paulirish/pwmetrics/issues/104.

using latest version

❯ pwmetrics https://bloomberg.com
Launching Chrome
  ✘ Error: Unable to complete run 1 of 1 due to Audit error: Required OptimizedImages gatherer encountered an error: not opened Audit key: uses-optimized-images.

@benschwarz mentioned bloomberg is a tricky page and it always errors. though this error is diff than what he was seeing:

>  ✘ Error: Sorry, Visually Complete 85% metric is unavailable.
> ✘ Error: Sorry, First Contentful Paint metric is unavailable.

anyway.. looks like grabbing the Lighthouse perf config might not be what we want for pwmetrics and we could afford to skip the optimizedimages bit. :)

**Comment by wardpeet** [comment]
quick debugging brought me here
```js
if (driver.online && (!mainRecord || mainRecord.failed)) {
      const message = mainRecord ? mainRecord.localizedFailDescription : 'timeout reached';
      log.error('GatherRunner', message);
      const error = new Error(`Unable to load the page: ${message}`);
      error.code = 'PAGE_LOAD_ERROR';
      throw error;
}
```

`mainRecord.failed` returns true but `mainRecord.localizedFailDescription = ""` so I guess timeout is reached?

**Comment by pedro93** [comment]
I'm not sure.... What is the current timeout value? I did not report this bug originally merely filling it in the appropriate repo. Tomorrow I'll try and test with the latest version of LH to see if I can repro. If it consistently times out what options do we have?

**Comment by wardpeet** [comment]
lighthouse default is set at 25seconds. you can change it in the source https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L34. 

I've setting it to 300 and it still didn't work so it must be something else, we'll have a look

**Comment by patrickhulce** [comment]
@pedro93 yeah FYI the new perf config is [super simple](https://github.com/GoogleChrome/lighthouse/blob/16b0b048db301c2841c7805529dbf356d9196f96/lighthouse-core/config/perf.json) and you can probably use your own with the `onlyAudits` property once we do a release (I thought there was an issue filed somewhere about this but I couldn't find it to notify and close 😄 )
