### ISSUE TITLE
Screenshots arent sized properly

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#2108]
Is this a known issue with emulation?

<img width="1175" alt="screen shot 2017-04-30 at 12 52 36 pm" src="https://cloud.githubusercontent.com/assets/238208/25567496/ecdbb4b4-2da3-11e7-9e9c-46ecfff0d344.png">

Launching chrome with a nexus 5x window size (`--window-size=412,732`) fixes the issue:

<img width="1175" alt="screen shot 2017-04-30 at 12 53 29 pm" src="https://cloud.githubusercontent.com/assets/238208/25567503/06ce13e4-2da4-11e7-9ca1-47ef705e6a58.png">

**Comment by benschwarz** [comment]
@ebidel Can you confirm the version of Chrome used when this error occurred. 
To my knowledge, something of this effect crept into Canary a few weeks ago, but AFAIK it has been since fixed.

**Comment by ebidel** [comment]
Running on 60.0.3086.0 (Official Build) canary (64-bit) using LH 1.6.5 in Node.

However, it looks like if I install master:

```
"lighthouse": "GoogleChrome/lighthouse#master"
```

 screenshots look fine and no need for the `--window-size=412,732`. 

The diff might be https://github.com/GoogleChrome/lighthouse/commit/f1aeb5813a56b2a3030ce2cbda2c089ba5c92fed. Not sure we cherry picked that into the 1.6.5.

@paulirish yea?

**Comment by benschwarz** [comment]
`Emulation.setVisibleSize` is required now, so if its not in `1.6.5`, then that'll be the answer.

**Comment by paulirish** [comment]
Yup. What ben said.​
