### ISSUE TITLE
Audit bug: Page load is fast enough on 3g is flaky

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#2109]
`npm run start -- --output=domhtml --output-path=results.html https://www.chromestatus.com/features` consistently fails this check on master:

<img width="1154" alt="screen shot 2017-04-30 at 1 30 49 pm" src="https://cloud.githubusercontent.com/assets/238208/25567737/46e6c8cc-2da9-11e7-8e4a-6dc56aca7b5b.png">

**Comment by brendankenny** [comment]
The extendedInfo includes data on the latencies of all requests it checks, so you can see what failed. Maybe preloaded or pushed assets?

**Comment by ebidel** [comment]
The request in question is a really small svg file. Not sure why there's no latency built into the request, but maybe we should set a min on the request size? Something this small is unlikely to do any damage.

```
 _url: 'https://www.chromestatus.com/static/elements/openinnew.svg',
  _parsedURL: 
   { isValid: true,
     url: 'https://www.chromestatus.com/static/elements/openinnew.svg',
     scheme: 'https',
     host: 'www.chromestatus.com',
     port: undefined,
     path: '/static/elements/openinnew.svg',
     queryParams: '',
     fragment: undefined,
     folderPathComponents: '/static/elements',
     lastPathComponent: 'openinnew.svg' },
  _documentURL: 'https://www.chromestatus.com/features',
  _frameId: '5144.1',
  _loaderId: '5144.3',
  _initiator: { type: 'other' },
  _issueTime: 100825.008248,
  _startTime: 100825.00856,
  _endTime: 100825.013688,
  _blockedReason: undefined,
  statusCode: 200,
  statusText: '',
  requestMethod: 'GET',
  requestTime: 0,
  protocol: 'h2',
  mixedContentType: 'none',
  _initialPriority: 'Low',
  _currentPriority: null,
  _resourceType: 
   { _name: 'image',
     _title: 'Image',
     _category: { title: 'Images', shortTitle: 'Img' },
     _isTextType: false },
  _contentEncoded: false,
  _pendingContentCallbacks: [],
  _frames: [],
  _eventSourceMessages: [],
  _responseHeaderValues: {},
  _remoteAddress: '172.217.6.51:443',
  _securityState: 'secure',
  _securityDetails: 
   { protocol: 'TLS 1.2',
     keyExchange: 'ECDHE_RSA',
     keyExchangeGroup: 'X25519',
     cipher: 'AES_128_GCM',
     certificateId: 0,
     subjectName: 'chromestatus.com',
     sanList: [ 'chromestatus.com', 'www.chromestatus.com' ],
     issuer: 'Google Internet Authority G2',
     validFrom: 1472691572,
     validTo: 1504137600,
     signedCertificateTimestampList: [] },
  connectionId: '0',
  hasNetworkData: true,
  _requestHeaders: 
   [ { name: 'Referer',
       value: 'https://www.chromestatus.com/features' },
     { name: 'User-Agent',
       value: 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36(KHTML, like Gecko) Chrome/59.0.3033.0 Mobile Safari/537.36' } ],
  _requestFormData: undefined,
  _wallIssueTime: 1493589172.8776,
  _responseReceivedTime: 100825.013104,
  _mimeType: 'image/svg+xml',
  _responseHeaders: 
   [ { name: 'date', value: 'Sun, 30 Apr 2017 21:52:45 GMT' },
     { name: 'content-encoding', value: 'gzip' },
     { name: 'server', value: 'Google Frontend' },
     { name: 'age', value: '7' },
     { name: 'etag', value: '"Eh5Siw"' },
     { name: 'content-type', value: 'image/svg+xml' },
     { name: 'status', value: '200' },
     { name: 'x-cloud-trace-context',
       value: '61ebd5c2004a7fe2046f23438d03fd71' },
     { name: 'cache-control', value: 'public, max-age=600' },
     { name: 'access-control-allow-origin', value: '*' },
     { name: 'content-length', value: '236' },
     { name: 'expires', value: 'Sun, 30 Apr 2017 22:02:45 GMT' } ],
  _transferSize: 0,
  connectionReused: false,
  _fetchedViaServiceWorker: true,
  _fromDiskCache: true,
  _timing: 
   { requestTime: 100825.00856,
     proxyStart: -1,
     proxyEnd: -1,
     dnsStart: -1,
     dnsEnd: -1,
     connectStart: -1,
     connectEnd: -1,
     sslStart: -1,
     sslEnd: -1,
     workerStart: 0.122999990708195,
     workerReady: 0.127999999676831,
     sendStart: 0.127999999676831,
     sendEnd: 4.44499999866821,
     pushStart: 0,
     pushEnd: 0,
     receiveHeadersEnd: 4.54399999580346 },
```

**Comment by ebidel** [comment]
Here's a list of requests that are made:

URL, `_fromDiskCache`, latency
https://www.chromestatus.com/features undefined 157.75399999984097
https://www.chromestatus.com/omaha_data true 163.7389999959846
https://www.chromestatus.com/static/img/ring.svg undefined 178.1449999980391
https://www.chromestatus.com/static/img/chrome_logo.svg undefined 168.84300000674557
https://www.chromestatus.com/static/elements/features-imports.vulcanize.html undefined 171.35800000687578
https://www.google-analytics.com/analytics.js undefined 177.757000012207
https://www.chromestatus.com/static/elements/features-imports.vulcanize.js undefined 161.67100000893677
https://www.chromestatus.com/static/img/crstatus_192.png undefined 179.6409999951717
https://www.chromestatus.com/static/elements/features-imports.vulcanize.js undefined 171.18000000482397
https://www.chromestatus.com/static/img/crstatus_128.png undefined 160.74199999275106
https://www.chromestatus.com/omaha_data undefined 161.66299999167643
https://www.chromestatus.com/features_v2.json undefined 376.7669999942878
https://www.chromestatus.com/static/elements/openinnew.svg undefined 157.58400000049738
https://www.chromestatus.com/static/img/crstatus_192.png undefined 150.51900000253187
https://www.chromestatus.com/static/elements/openinnew.svg true 0.12700000661426003

`openinnew.svg` is coming from the cache for the questionable request.  What's weird is that  one of the `omaha_data` requests comes from the cache, but it has ~160ms latency both times. Why doesn't that happen with `openinnew.svg`?

For this audit, we should probably ignore the requests that are coming from the cache. Yea?

**Comment by patrickhulce** [comment]
how is anything coming from the cache at all? aren't we disabling the cache entirely at the moment 😕

**Comment by ebidel** [comment]
Not really sure. Does network recording de-dupe requests like the DT frontend does? 

https://www.chromestatus.com/static/elements/openinnew.svg  at least, is used many times on the site. But then again,...I'd expect way more requests for that URL in the records.

**Comment by ebidel** [comment]
`omaha_data` might be showing up twice because it gets link rel="preload" and requested later via xhr.

**Comment by paulirish** [comment]
Fascinating. I don't see exactly where network panel decides to not show requests served from cache, but it makes sense as you never see that on a single page. But yet the disk cache (and memory cache) is indeed quite busy.

one guess:  omaha_data was doubly requested around the same time, so it wasnt yet in the disk cache yet. so the full latency on the response was applied to both.   whereas the svg's first response was placed into the disk cache before the 2nd one came around.

pretty neat though!
