### ISSUE TITLE
Integrate invalid Manifest `display` and mobile-friendly `display` debugStrings

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#211]
Currently in the [display audit](https://github.com/GoogleChrome/lighthouse/blob/a15674aab32e078c7ca587ae3a3e482671aa7c03/audits/mobile-friendly/display.js#L58), if you have an invalid `display` property in your manifest, you get a `debugString` from the parser but the invalid value is dropped and the property is set to `undefined`.

The audit is even more strict, looking only for `fullscreen` or `standalone` values. The audit warning should somehow include the information from the parser so the user can know their nonsense display is invalid.

One simple option may be to just use the `display.raw` value as the `rawValue`, so you'd get something like
```
 -- Manifest has suggested display property: false (nonsenseDisplayValue)
    Manifest display property should be standalone or fullscreen.
```
where currently `nonsenseDisplayValue` would, I believe, be `undefined`

**Comment by paulirish** [comment]
we sorted this out a few weeks back.
