### ISSUE TITLE
Category renderer basics for Perf category

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2111]
We'll need to group metrics and quantifiable perf audits separately so they can be rendered as expected:

![image](https://cloud.githubusercontent.com/assets/39191/25586388/fcaeba20-2e53-11e7-9630-b4a2b4dd9d27.png)

@patrickhulce the details of the rendering can be handled separately, but do you think you can lay some groundwork for this?

**Comment by patrickhulce** [comment]
definitely 👍

**Comment by patrickhulce** [comment]
closed by #2057
