### ISSUE TITLE
Quantifiable perf audit renderer w/ sparklines

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2112]
![image](https://cloud.githubusercontent.com/assets/39191/25586705/643b6d36-2e55-11e7-8cd6-3fa51c1a0088.png)

Blocked by: https://github.com/GoogleChrome/lighthouse/issues/2111

**Comment by ebidel** [comment]
@patrickhulce g2g?

**Comment by patrickhulce** [comment]
ah yes it is 👍
