### ISSUE TITLE
.timestamps should always be in microseconds

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2116]
We `x / 1000` in a number of places on these timestamp values.  It's a little odd. I asked patrick if he had a guess why and he shared this punctuation-free explanation:

> something (fmp maybe?) was exposed as ts / 1000 and as the metrics got collected they're all used that way but it's now this hideous monster of misunderstand why they're not the real timestamps

We should keep these integers in their original value.
We'll break pwmetrics with this change, but that's okay. :)

This is low-priority relative to everything else but we should include it in 2.0

**Comment by pedro93** [comment]
Cc @denar90 we should be aware of this issue when updating with the future version of LH
