### ISSUE TITLE
Quickstart guide mentions Chrome 52+ but README wants 56+

### ISSUE THREAD

**Issue by dandv** [GoogleChrome/lighthouse#2127]
README:

> Lighthouse requires Chrome 56 or later.

http://bit.ly/lighthouse-quickstart:

> Make sure Chrome is up-to-date with version 52 or higher.

**Comment by paulirish** [comment]
updated the doc:
![image](https://cloud.githubusercontent.com/assets/39191/25644736/2b110f8a-2f5d-11e7-9bf9-bacf76c273a3.png)

**Comment by paulirish** [comment]
thx for reporting this. :)
