### ISSUE TITLE
intermittent travis failures on "could not handle JavaScript dialog"

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#2141]
This is from the smoke test introduced in #2120. handleJavaScriptDialog

<img width="744" alt="screen shot 2017-05-03 at 12 35 30" src="https://cloud.githubusercontent.com/assets/316891/25685759/7be25fb0-301e-11e7-829e-bebda83dd2c9.png">

Behavior seems to be it fails, the promise rejection is unhandled ([intentionally](https://github.com/GoogleChrome/lighthouse/blob/134b9b0b2235ed34f80b40c75166d1652160cd8b/lighthouse-core/gather/driver.js#L847)), then the test sits there and spins until travis hits its 10 minute timeout.

I'm not sure how the protocol is failing to dismiss the dialog (and only on travis? or are we just not running `yarn smoke` enough locally?), but the only solution I know of right now is removing the `window.confirm` from `dbw_tester`, which would be unfortunate.

Any other ideas?

**Comment by patrickhulce** [comment]
😢  if there's not a simple timeout-like fix then I'm in favor of removing, we don't need to introduce even more noise to our travis runs in addition to screenshots... :/

**Comment by brendankenny** [comment]
ideally the real fix would be figuring out why the protocol can't dismiss a modal.

Agreed on the no-(new-)flakiness, but this would be a good thing to automatically not regress on. Most sites that we test normally don't do modal prompts.
