### ISSUE TITLE
Create copy/paste audit template

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#2157]
For IO...

Update https://github.com/GoogleChrome/lighthouse/blob/master/docs/architecture.md#audits with a copy and paste snippet to get started writing an audit. 

Should also look at https://github.com/GoogleChrome/lighthouse#creating-custom-audits--gatherers.

**Comment by brendankenny** [comment]
fixed in #2255 (and various docs additions since then)
