### ISSUE TITLE
create a driver.evalAsync helper

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#217]
Now with https://github.com/GoogleChrome/lighthouse/pull/216/ and my earlier work with service worker async js calls, it now makes sense to make a common helper. I will do this.

**Comment by paulirish** [comment]
Brendan got a technique from pavel and dgozman on how to handle this

basically:

* flip the commandlineAPI flag for runtimeeveluate
* save the `inspect` function early on
* at the end of async, use it with your return object
* you'll get an [inspectrequested](https://chromedevtools.github.io/debugger-protocol-viewer/Runtime/#event-inspectRequested) event holding the object reference

**Comment by paulirish** [comment]
Closing this because #247 is on its way..
