### ISSUE TITLE
📖 Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by alexleventer** [GoogleChrome/lighthouse#2174]
**Lighthouse Version**: 1.6.5
**Chrome Version**: 58.0.3029.96
**URL**: https://www.tred.com/sell-my-car
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
 ```Error: Protocol error (IO.read): Read failed
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9254:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by wardpeet** [comment]
Does this still happen on 2.0?

**Comment by uskay** [comment]
I'm seeing this still happening in an environment below.

- Error MSG: Protocol error (IO.read): Read failed
- Happens in either selecting "Performance" or "Progressive Web App"
- Browser: Both 65.0.3325.146 (Official Build) (64 bit) and Latest Canary
- OS: Windows 10
- Screenshot: https://drive.google.com/file/d/19mjaeiGPs-H4xVrUBnS4a1y1LCFtPbcc/view?usp=sharing

Any ideas on how we should fix this?
