### ISSUE TITLE
--mobile CLI flag is broken

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#218]
A few issues here

* the CLI describes the mobile flag as being on by default, but it's not.
* the flag is described as "--mobile" but it appears to be "--emulate-mobile-device", based on gather-scheduler.js

IMO we should use a flag to **disable** emulation, so we don't have to deal with weird default-on logic for flags. (this also affects the `load-page` flag)

**Comment by brendankenny** [comment]
it should be default true already?
https://github.com/GoogleChrome/lighthouse/blob/16ff07fbea326d5c1fe35e3f9e4d660d85e1834c/runner.js#L67

or are you talking about in the extension? I think it should be default true for the non-reload case there, too, but curious what others thing
https://github.com/GoogleChrome/lighthouse/blob/16ff07fbea326d5c1fe35e3f9e4d660d85e1834c/extension/app/scripts.babel/app.js#L26

**Comment by paullewis** [comment]
It was broken after the gatherer refactor. Should have been fixed by my earlier PR

**Comment by paulirish** [comment]
ah lewis fixed this a few hours back;

https://github.com/GoogleChrome/lighthouse/commit/ebd3b6adfa315b6a5dd6bee341038f730e2a9b49

**Comment by paulirish** [comment]
I still prefer disable-* flags for these situations, but we can handle that separately. 

boom
