### ISSUE TITLE
Extension Error: Cannot access a chrome:// URL

### ISSUE THREAD

**Issue by ct-murali** [GoogleChrome/lighthouse#2186]
**Lighthouse Version**: 1.6.5
**Chrome Version**: 58.0.3029.96
**URL**: chrome://newtab/
**Error Message**: Cannot access a chrome:// URL
**Stack Trace**:
 ```Error: Cannot access a chrome:// URL
    at Object.chrome.debugger.attach._ [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9198:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by wardpeet** [comment]
Do you still have an issue with extension 2.0.0?

**Comment by paulirish** [comment]
Yup. Still a problem in 2.0.0, just confirmed.

This is exclusive to the extension.
We can do an early check in the extensions's popup or lh-background methods to reject on a url that starts with `chrome://`.

Trying to run the ext on blob:chrome-extension already fails with "Cannot access contents of the page. Extension manifest must request permission to access the respective host." error written out. 

And the ext fails on CWS pages with our own message: 
> The Lighthouse extension cannot audit the Chrome Web Store. If necessary, use the Lighthouse CLI to do so.

We can just tweak that error message and reject with the same string.

@wardpeet wanna take this one?

**Comment by brendankenny** [comment]
the other error messages are done [here](https://github.com/GoogleChrome/lighthouse/blob/2d48f672e01c6e14cecd644608465c4015d8884d/lighthouse-extension/app/src/popup.js#L23-L34) and the check for error message with custom strings/no github link is done [here](https://github.com/GoogleChrome/lighthouse/blob/2d48f672e01c6e14cecd644608465c4015d8884d/lighthouse-extension/app/src/popup.js#L136-L142)

Poorly documented, but it checks if the error message includes the `NON_BUG_ERROR_MESSAGES` key, and if so, prints the string value. So for this one, it could be `'Cannot access a chrome': 'better error message'`

**Comment by vivekranjan92** [comment]
Hi, I am facing an issue. I have added the lighthouse extension to my chrome and when I am trying to generate the report it is saying that "The Lighthouse extension cannot audit the Chrome Web Store. If necessary, use the Lighthouse CLI to do so". So can any one help to get what else is required to fix it. I have tried to google it but not getting any clue.
Thanks
