### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by centinel3** [GoogleChrome/lighthouse#2187]
I'm trying to use the lighthouse tool on a small web app that is used within a native android app (served through a webview). I'm building it in chrome (faux url below). The web app depends on a query string in order to hit an api endpoint for the correct data. Lighthouse does not work for me. I tested this out on apple.com and it generated a report fine. Is there an issue with handling urls with query string params? The api call is with the Fetch API. The whole app is built with React and mobX. Any help would be appreciated. The tool looks great and would help out a lot in building a truly progressive, offline first experience. Sincerely, Chris

**Lighthouse Version**: 1.6.5
**Chrome Version**: 57.0.2987.133
**URL**: http://mytestapp:8074/?prodTourId=171493&individualId=42316

**Comment by patrickhulce** [comment]
Sorry you're running into this @centinel3! Let's move the discussion to #1834
