### ISSUE TITLE
Support inspection of mobile devices

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#219]
Currently Lighthouse is designed to run a local desktop browser that has its debugger agent exposed. It then emulates mobile characteristics.

We also want to support connecting to real devices, when available. We can then disable a good amount of our emulation.

---

I'm going to dump some notes that will be helpful to someone taking this on

Here's me trying to do classic remote debugging on the [legacy workflow](https://developer.chrome.com/devtools/docs/remote-debugging-legacy):

``` sh
adb devices -l
adb forward tcp:9222 localabstract:chrome_devtools_remote

chrome --allow-running-insecure-content # run with this to allow connecting to a localhost (insecure) websocket
# remote debugging works!
```

![image](https://cloud.githubusercontent.com/assets/39191/14684565/6a85b6a8-06e5-11e6-9fe4-e5a07aa7b59a.png)

So now that we can confirm that works, we know the protocol for that device is available. 

Confirming at http://localhost:9222/json … 
![image](https://cloud.githubusercontent.com/assets/39191/14684590/9110f706-06e5-11e6-95a4-66f1d5916088.png)

From this point, we should be able to use the existing chrome-remote-interface driver to run the show.

And as a quick smoke test. It appears that it works! 
(This screenshot are the results after the page was loaded on my nexus 5x)

![image](https://cloud.githubusercontent.com/assets/39191/14684725/2aebe516-06e6-11e6-8964-b08769f7b8ae.png)

---

TBH, things are looking good out of the box, that's great. I don't think we should add a `--mobile-device` flag because it'd be doing the same sort of work that `./launch-chrome.sh` is doing. 

If anything we're gonna make sure our device-emulation is turned off when we're in this mode (see #218), but I think people can manage that on their own.

**Comment by samccone** [comment]
this is really cool. :clap:

**Comment by gauntface** [comment]
Was there a reason for not spinning up a new chrome browser for each run of lighthouse from the CLI?

**Comment by paulirish** [comment]
^ matt edited and left a bunch of questions above, FYI.

**Comment by gauntface** [comment]
@paulirish when you say edits and bunch of Q's, I cannot see them . . . . .

I was digging through the old device lab code, I had a script that would open chrome on an android device and open the debug port but it seems a bit temperamental, but could be sured up. Worth investigating for lighthouse?

**Comment by paulirish** [comment]
> - Tabs that are opened are cleaned up, thats going to cause a problem for anyone leaving this running

did you mean **aren't** cleaned up? I am also feeling like we should clean up the new tabs we create.. yup.

> - Are there any plans to wrap or alter the shell script so that you can just run `lighthouse https://gauntface.com` and it start chrome and run the tests and close the browser?
>    - This would probably make it easier for the adb use case outlined above as well (i.e. if this arg exists, run a different start up script)

We've discussed it, but it would slow down development quite a bit, so we're deferring this until later. For CI, that pattern should be the default; so this is in the roadmap.

> - Whats the deal with the mobile emulation? What test is that needed for?

Flipkart and a few other apps serve different assets based on the mobile UA. We also want to make sure that if any feature detects based on touch events change behavior that we are representing a mobile device as close as possible.

> - What was the need for the force sw update? (i.e. what scenario requires the force update to be set)

@samccone can speak to this better. At this point, we may not need that setting and can rely on the new reload stuff? sam, your call.

> - One run I hit, the cli just stopped with no error. Are there any logs from Chrome / Lighthouse / something else I should look out for?

you can toss `--verbose` to the CLI. that's about it. If it's reproducible, lets get a bug filed.

> - The results could do with an id in addition to the name and score.

for the JSON results? No one has improved the JSON output at all, so whatever you want is fair game. 

> - I was digging through the old device lab code, I had a script that would open chrome on an android device and open the debug port but it seems a bit temperamental, but could be sured up. Worth investigating for lighthouse?

sounds interesting to me! Would want to know how it compares with the adb commands I dropped in above. Let's try it out.

**Comment by gauntface** [comment]
Commands are basically the same, just wrapped in a node helper (I think).

Will have a play next week to just have lighthouse running over and over, fixing some of the above as I go.

First thing will be the tab clean up.

**Comment by wardpeet** [comment]
Pretty sure we can close this in favor of #910
/cc @paulirish
