### ISSUE TITLE
Expose git hash to extension build - followup

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2190]
see this comment for updates: https://github.com/GoogleChrome/lighthouse/issues/2190#issuecomment-322321863

-------

The lighthouse-background.js file is built from some snapshot of master
But we dont have an easy wasy of finding out which commit it was. We want to know both in the chrome extension and in devtools.

For devtools, it seems sufficient to have something like this at the top of the file:

```js
// lighthouse, browserified. v2.0.0-alpha.3 (5dc01be664e883db58566f6358e9c15f67a03d6e)

```

we could probably live with that solution for the extension as well.

@wardpeet wanna try this out?

**Comment by wardpeet** [comment]
sure thing :)

**Comment by wardpeet** [comment]
#2236

**Comment by paulirish** [comment]
Some followups @brendankenny and i just talked about:

* create a `versioninfo.js` file that gets the __commithash__ rewrite done to it.
* in lighthouse-background, expose a `self.getVersionInfo()`. In DevTools we can then run this when we get an exception from the normal running of the LH run. (or running it beforehand is probably better). Commithash, lighthouse version and optionally extension version could be in the return object.

**Comment by wardpeet** [comment]
i'll improve this one if that's ok
