### ISSUE TITLE
TTFB Audit followup

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2192]
Forking from #2126 

@wardpeet added:

> I had a few changes ready to go, was fixing the details export of audit and cleaning up the criticalRequestChains but I can open an extra PR just for that 😄 

i am also seeing this in the new report
![image](https://cloud.githubusercontent.com/assets/39191/25870050/89584f40-34b7-11e7-8a2f-72f916857691.png)

and this in the old one:
![image](https://cloud.githubusercontent.com/assets/39191/25870064/9a76b406-34b7-11e7-937c-0c569b670ba7.png)

**Comment by ebidel** [comment]
Is "details export" adding a details rendering to the audit? FYI, I'm working on a criticalRequestChains details renderer.

**Comment by paulirish** [comment]
i _think_ so, but cc @wardpeet to be sure.

it'll just be a basic `table` renderer.

> i'm working on a criticalRequestChains details renderer.

awesome.

**Comment by paulirish** [comment]
Additional for @wardpeet: rename `time-to-firstbyte` to `time-to-first-byte`

**Comment by wardpeet** [comment]
I was looking into the gatherer as @patrickhulce mentioned:
> I was thinking just expose as a flattened property of the existing computed artifact so we don't bother with the computation twice although if you're feeling fancy we could refactor the existing one to call requestCriticalRequests and then build the tree :)

**Comment by wardpeet** [comment]
Just need a rebase and #2231 is ready.

Some records don't have _timing so I ignore them

**Comment by brendankenny** [comment]
closed by #2231
