### ISSUE TITLE
_renderPerfHintAudit should print debugString and exit

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2193]
On master the TTFB audit is throwing an error (cc #2192). But this ends up tanking the report completely.
In _renderPerfHintAudit we fail because `result.rawValue` is null and because `extendedInfo` is null.

![image](https://cloud.githubusercontent.com/assets/39191/25870280/6800734e-34b8-11e7-92cc-8b20e07370e6.png)

here's a gist with the JSON that can repro this: https://gist.github.com/anonymous/a086ec0e50a2b8621d1ced1f46645df2

**Comment by ebidel** [comment]
#need
