### ISSUE TITLE
artifact: parsedManifest

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#22]
A few audits rely on a parsedManifest..

#### gather:
  * protocol -> grab manifest file resource - horo@ has a canonical technique for this.
  * parse w/ https://github.com/mounirlamouri/manifest-validator

report errors in parsing to user

**Comment by brendankenny** [comment]
"report errors in parsing to user" => this should probably be part of the manifest audits/reporting. "You don't have a theme_color", but then differentiate between that's because they didn't include a `theme_color` or because they have an invalid color listed as their `theme_color`.
