### ISSUE TITLE
Improve readability of gather-scheduler

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#220]
@samccone can you make this easier to parse?

![image](https://cloud.githubusercontent.com/assets/39191/14686095/2d931c7a-06ec-11e6-9269-1ac1755046bf.png)

if its a line length issue perhaps we can rename the class, etc?

**Comment by brendankenny** [comment]
Current state is my fault :) I'll take a pass at it, let others judge me for once

**Comment by paulirish** [comment]
k thx dude

**Comment by samccone** [comment]
What I had prior:

![image](https://cloud.githubusercontent.com/assets/883126/14686518/e5e4f874-06ed-11e6-9776-bcbbb3cd9805.png)

(just a ref)
