### ISSUE TITLE
Flaky test: link-blocking-first-paint results === 4

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2201]
[This assertion of only 4 blocking stylesheets](https://github.com/GoogleChrome/lighthouse/blob/d0e0d35d7d8bceaedcb5925da5f9345e5324cb37/lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js#L62) on dbw_tester is failing sometimes.

Travis likes to think there are 5.

It includes [this guy](https://github.com/GoogleChrome/lighthouse/blob/d0e0d35d7d8bceaedcb5925da5f9345e5324cb37/lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html#L40-L41):

```html
<link rel="preload" href="./dbw_tester.css?delay=2000&async=true" as="style" onload="this.rel = 'stylesheet'">
```

probably the new link preload logic?

example travis runs:  
* https://travis-ci.org/GoogleChrome/lighthouse/jobs/230589047#L537
* https://travis-ci.org/GoogleChrome/lighthouse/jobs/230580380#L545

**Comment by patrickhulce** [comment]
well that really sucks, I can't repro this locally to investigate either :/

**Comment by patrickhulce** [comment]
wait, is travis using an old cache has anyone checked? it might have an old canary that didn't support isLinkPreload

**Comment by patrickhulce** [comment]
clearing the caches has gotten #2204 to pass 4 of 4 rebuilds (8 of 8 jobs) so I think we're good here 👍
