### ISSUE TITLE
Optimized images: compare quality/size of Chrome-encoded images to other encoders

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#2217]
The [current method](https://github.com/GoogleChrome/lighthouse/blob/3f22558aca0285b8b05585d4e1fa2597ef318ae1/lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js#L41) used to determine if an image is optimized is to get the resulting data URI of running the image through a `canvas` in the browser at a particular quality setting. However, I've observed that this quality setting does not necessarily track that of other encoders (such as the one used in GIMP for example, their ~90 is our ~85).

It'd be nice to compare and contrast the results of canvas encoding with popular encoders to inform our quality decisions and make sure we're being reasonable. Automating this so we can track it over time for regressions would be great too.

**Comment by brendankenny** [comment]
for jpg, from my reading we [pass off to `libjpeg-turbo` with a simple 0.8 -> 80% quality conversion](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/image-encoders/JPEGImageEncoder.cpp?gsn=Encode&l=192), so this might simplify to comparing `libjpeg-turbo`'s quality levels to popular image editors, `ImageOptim` defaults, etc

jpg encoding might be platform specific, but I believe this covers desktop, at least

**Comment by patrickhulce** [comment]
A recent [skia roll](https://chromium.googlesource.com/chromium/src/+/86074971b9640dbf59869071b4a18bec51c61424) has changed this, it looks like there are [3 possibilities](https://cs.chromium.org/chromium/src/ui/gfx/codec/jpeg_codec.cc?type=cs&l=47) it will delegate to?

**Comment by paulirish** [comment]
@patrickhulce is this all set with trace-event based details?

**Comment by patrickhulce** [comment]
the comparison is still worth knowing IMO to image opt even if it's fairly low priority
