### ISSUE TITLE
Critical req chains: ignore image/* mimeType

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2219]
Sites like http://veerle.duoh.com/ issue requests for images. Especially with favicons the devtools side doesn't identify them as `CategoryType === Image`.

See the screenshot in https://github.com/GoogleChrome/lighthouse/pull/2218 as evidence that this is still a problem. :)

So [over in isCritical](https://github.com/GoogleChrome/lighthouse/blob/3f22558aca0285b8b05585d4e1fa2597ef318ae1/lighthouse-core/gather/computed/critical-request-chains.js#L29-L55), we should exclude all requests that were sent with contentType `image/*`

@stramel wanna take this?

**Comment by stramel** [comment]
Sure, I will take a shot at it 👍 Thanks!
