### ISSUE TITLE
clean up after smoke test

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#222]
It's handy to be able to run the smoke test locally instead of just on travis, but the smoke test script should shut down its SimpleHTTPServer and delete the temporary `results` file it creates when complete.

Giving it to you, @samccone, but feel free to pass

**Comment by paulirish** [comment]
agree. i want to run this all the time.

@samccone can you make this work if we are rerunning it locally nonstop    ?

**Comment by samccone** [comment]
ya

**Comment by paulirish** [comment]
For me, the goal is to get these smoke tests running as part of the new [watch script](https://github.com/GoogleChrome/lighthouse/blob/master/package.json#L13).

Here's my WIP for that, which I'll merge your fixes into before putting up: https://github.com/GoogleChrome/lighthouse/compare/master...paulirish:brwoserifysmoketest
