### ISSUE TITLE
Need better a11y descriptions

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/lighthouse#2221]
I got a few complaints today because folks weren't sure how to fix their a11y errors. I need to see if i can sneak in some fixes in the descriptions asap.

**Comment by patrickhulce** [comment]
does this include updating the group descriptions as well? right now they're all the same "Screen readers and other assistive technologies require annotations to understand otherwise ambiguous content." :)

**Comment by robdodson** [comment]
oh i didn't even know that was a thing. yeah those should be updated too :\

**Comment by paulirish** [comment]
What's an example of one of these, and what would be useful?

**Comment by robdodson** [comment]
I think this is mostly covered by the learn more links now. Closing.
