### ISSUE TITLE
Use container-based infrastructure on Travis

### ISSUE THREAD

**Issue by ngryman** [GoogleChrome/lighthouse#2224]
Hey,

I'm just sharing my experience on the subject because I had a hard time making things work on Travis for Speed Racer. I basically took a lot of inspiration on what you do (thanks for that btw).

I'm just wondering why you would need `sudo`?

**Comment by ngryman** [comment]
If it was because `trusty` was not available container-based, it's now available: https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/?utm_source=trusty-container-based-beta-notice&utm_medium=banner&utm_campaign=trusty-container-based-beta.

**Comment by paulirish** [comment]
> I'm just wondering why you would need sudo?
> If it was because trusty was not available container-based, 

Yup looks like that's right: https://github.com/GoogleChrome/lighthouse/pull/264

**Comment by wardpeet** [comment]
i believe this is fixed
