### ISSUE TITLE
Extension Error: Cannot read property 'fatal' of null

### ISSUE THREAD

**Issue by vijayyadav06** [GoogleChrome/lighthouse#2250]
**Lighthouse Version**: 1.6.5
**Chrome Version**: 57.0.2987.133
**URL**: http://www.worldcat.org/
**Error Message**: Cannot read property 'fatal' of null
**Stack Trace**:
 ```TypeError: Cannot read property 'fatal' of null
    at promise.catch.err (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10466:7)```

**Comment by wardpeet** [comment]
Can you try out version 2.0.0 as I can't reproduce it with the latest version @vijayyadav06

**Comment by patrickhulce** [comment]
We're unable to reproduce this with the latest version, please re-comment with steps if you're still experiencing this!
