### ISSUE TITLE
Cleanup work to publish chrome-launcher

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#2251]
TODO:
https://github.com/GoogleChrome/lighthouse/commit/7673d156131a9cfc33c38b55ec0775326bd73524

Also:
Need to figure out how to share `log`

**Comment by paulirish** [comment]
also: make sure the mkdirp type will be exposed to projects consuming LH as a dep
https://github.com/paulirish/pwmetrics/pull/120#issuecomment-302119936

(should be automatic)

**Comment by paulirish** [comment]
> Need to figure out how to share log

one answer might be to pull in `"debug": "2.2.0",` as a dep of c-launcher and use that directly. I think the only gotcha is dealing with loglevel and our --verbose flag, etc?

**Comment by pedro93** [comment]
Any update on this?

**Comment by samccone** [comment]
I am working on it now :)

**Comment by jooj123** [comment]
@samccone any update on this one? Seems to be blocking: https://github.com/paulirish/pwmetrics/pull/120

**Comment by ebidel** [comment]
@jooj123, https://github.com/GoogleChrome/lighthouse/pull/2358/files is close. Just a few comments to address.

**Comment by samccone** [comment]
@jooj123 I have been working on this for a while now, a fair amount of work was required to correctly extract this in a non-debt inducing way

https://github.com/GoogleChrome/lighthouse/issues/2092

Hope to get this landed quite soon. Thanks

**Comment by paulirish** [comment]
Now published on npm as `chrome-launcher`.

docs: https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher

**Comment by brendankenny** [comment]
🎉 🎉 🌮 🎉 🎉 🎉 🎉 🎉

**Comment by jooj123** [comment]
awesome thanks guys 🎉

**Comment by ebidel** [comment]
Nice work!
