### ISSUE TITLE
Does it make sense to expose an option in lighthouse core to launch chrome?

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#2259]
The common use-case for using lighthouse programmatically is to launch chrome with it.. right now that is a nested promise with a bit of clean up at the end... The reason for most of this work boils down to the need to pass `port` from the launcher to lighthouse.. because of this I think it might be nice to do something like

```js
flags.launchChrome = true;
return Lighthouse(url, flags, config);
```

Which would take care of killing and launching chrome.

**Comment by wardpeet** [comment]
Fine by
cc @paulirish @ebidel @patrickhulce @brendankenny

**Comment by ebidel** [comment]
I like it. We need to cater better to the common cases like this.  One question I have is how we would handle lh flags, flags to the launcher, and `chromeFlags` Would everything go in `flags`?
