### ISSUE TITLE
[A11y Audit] Audit Error: ... Protocol error (Runtime.evaluate): Object reference chain is too long

### ISSUE THREAD

**Issue by stramel** [GoogleChrome/lighthouse#2265]
Transferring from details posted on an unrelated issue. 👎  (My Bad)

Getting a big fat ZERO on accessibility... :sob: 

Lighthouse: alpha.5
OS: Ubuntu 16.04
Chrome: 58.0.3029.68 beta (64-bit)

Steps to Reproduce:

1. Download the Canary Lighthouse extension
1. Navigate to https://q-citrix.salesnext.com/login
1. Under "Options", select "Accessibility" paired with; "PWA" or "Performance" audits.
1. Click "Generate Report"

Expected Result: Accessibility Audit results will be populated along with other selected audits

Actual Result: Accessibility Audit results in error. Exports HTML & JSON can be found in this Gist. https://gist.github.com/stramel/de5976a460b432d80f51f0be9f6873a7

Note: Seems like Best Practices works with it.

Transferred from #2078 (Sorry again 😅 )

**Comment by patrickhulce** [comment]
Are you still experiencing this @stramel? I'm not seeing it with any combination of categories on the latest canary extension

#2206 may have fixed it

**Comment by stramel** [comment]
Seems like it is fixed! Thanks for checking @patrickhulce
