### ISSUE TITLE
Increase Report density

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2269]
Currently the report within devtools is not very dense. It's a stark contrast to the rest of the devtools UI.

![image](https://cloud.githubusercontent.com/assets/39191/26119097/f4a5e0f0-3a20-11e7-8d52-8828ab5e53bf.png)

Already suggested was the the score gauge in the left column should slide into header component for each category. That way we can drop the left margin running along most of the report.

But there's also a number of other improvements possible.

cc @chowse

**Comment by patrickhulce** [comment]
many changes in this direction are bundled in #2256
