### ISSUE TITLE
Move postPageLoad gatherers to be after pageload

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#227]
Previously, we went -> load page, finish trace, run other gatherers (DOM, etc)

Now, we go -> load page, run other gatherers, finish trace.

As such our profile includes some of LH's clientside work, which is incorrect.

This is a scheduler issue, but we may want to make the function names clearer if we need to say that a phase is during profiling, etc.

![image](https://cloud.githubusercontent.com/assets/39191/14704586/4898d860-076a-11e6-80a2-9e7a9eaa807e.png)

**Comment by paulirish** [comment]
discovered when we were adding comments to the scheduler:
https://github.com/GoogleChrome/lighthouse/pull/223/files?w=1#diff-0e9f586a86b1aa17afa1c046d1e7d775R107

**Comment by paulirish** [comment]
@deepanjanroy i think this is closest to you.

**Comment by deepanjanroy** [comment]
How about `afterPageLoad =>  profiledPostPageLoad` and `afterTraceCollected => postProfiling`? All the current `afterPageLoad` phases can probably be safely moved to the `postProfiling` phase.

**Comment by paulirish** [comment]
👍 💯

**Comment by brendankenny** [comment]
fixed in #254
