### ISSUE TITLE
Report bug from report debugStrings

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2270]
If there's an exception or the user notes something looking bizarre, let's make sure it's straightforward for them to file a ticket here.

I think this is mostly in good shape, but I think we can:

1. test it by throwing errors in various places. 
2. confirm the "file an issue" links are present
3. confirm those links carry over whatever error stack and metadata we need.

**Comment by paulirish** [comment]
@wardpeet this issue isn't very well-defined, but if you're interested in poking at it, we could use the  help.

**Comment by wardpeet** [comment]
sure thing!

**Comment by wardpeet** [comment]
I'm still looking into this but I can already say that whenever we fail inside an audit / gatherer. we show an error message inside the report but there is no easy way to log an issue.

**Comment by brendankenny** [comment]
one issue is what defines an "odd" debugString. I guess we could just start with all debugStrings and see how it works from there?

**Comment by wardpeet** [comment]
Odd debug string wouldn't that be an audit or gather that throws an error?

**Comment by paulirish** [comment]
Not interested in this anymore, especially with Sentry.
