### ISSUE TITLE
DevTools: Add "view trace" to open our trace

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2273]
GIF of this [WIP patch](https://codereview.chromium.org/2884353002):
![viewtimeline](https://cloud.githubusercontent.com/assets/39191/26120365/51fffe9e-3a25-11e7-8952-5de4c7b8f086.gif)

This trace is the original, rather than our metric-annotated one.
But ideally we'd use that one.

**Comment by patrickhulce** [comment]
@paulirish already nailed this one 👍
