### ISSUE TITLE
support tuples as computed artifact input

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#2275]
this would allow moving [TTCI](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/consistently-interactive.js) to a computed artifact, as it needs both a `devtoolsLog` and a `trace` as input

**Comment by wardpeet** [comment]
Sorry to ask but what are Tuples?

**Comment by patrickhulce** [comment]
> Sorry to ask but what are Tuples?

ordered n-pairs, basically we want computed artifacts to be able to accept more than a single argument :)
