### ISSUE TITLE
Make page refresh optional?

### ISSUE THREAD

**Issue by minorninth** [GoogleChrome/lighthouse#2286]
One of my favorite features of the previous accessibility audit (via the extension) was being able to modify the site and then run the audit again.

Could you make the page refresh optional, or maybe even just skip refreshing automatically if you *only* select the accessibility audit?

**Comment by patrickhulce** [comment]
great feedback thanks @minorninth! there are a few other audits we could run without reloading the page too, would also go great with incremental reporting

**Comment by paulirish** [comment]
@minorninth yup. it makes a LOT of sense especially for a11y auditing. It's a feature we want, just havent gotten to yet.
Thanks v much for filing.

**Comment by brendankenny** [comment]
see also #1769

**Comment by wardpeet** [comment]
@paulirish @brendankenny @patrickhulce should we close this in favor of #1769

**Comment by paulirish** [comment]
good call. i updated its title. we'll pick up there.
