### ISSUE TITLE
Screenshots in extension including non-visible viewport

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2287]
![image](https://cloud.githubusercontent.com/assets/39191/26139086/f4e322f0-3a82-11e7-91a8-c7f52eb1feae.png)

Only affects extension. CLI & DevTools are fine.

Crbug: https://bugs.chromium.org/p/chromium/issues/detail?id=774311

**Comment by IagoLast** [comment]
Hi, I just downloaded the repo and i did:

`node lighthouse-cli/ http://www.google.com --view`. 

As you said, everything looks good using the `cli` while in the extension the screenshots are cropped.

But I just realized that this bug appears in the `cli` for some webpages.

`node lighthouse-cli/ https://iagolast.github.io/renfehorarios --view`

I would like to try to solve this bug, but perhaps it is more complicated than it seems, what do you think?

<img width="838" alt="captura de pantalla 2017-05-31 a las 16 41 56" src="https://cloud.githubusercontent.com/assets/2657897/26637584/2201e502-4620-11e7-8aa2-0614cb06d10e.png">
<img width="847" alt="captura de pantalla 2017-05-31 a las 16 42 03" src="https://cloud.githubusercontent.com/assets/2657897/26637587/2316a9e6-4620-11e7-91f2-5303f9ddfe07.png">

**Comment by wardpeet** [comment]
We're rebranding our extension and will run lighthouse through devtools instead. As stated devtools doesn't suffer from this thread so no reason to keep this open.

More info:
https://github.com/GoogleChrome/lighthouse/pull/9193

**Comment by connorjclark** [comment]
fyi @wardpeet we're actually gonna use PSI for the extension. but same conclusion regardless.

**Comment by wardpeet** [comment]
Haha thanks for the heads up! 👍
