### ISSUE TITLE
Friendlier message for multiple tabs to same origin

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#2299]
Taken from https://bugs.chromium.org/p/chromium/issues/detail?id=723411 (the issue is about it failing altogether, but the underlying problem for LH is that they have two new tab pages open which use the same service worker)

It'd be nice to create a new class of error would might provide some instructions and hides bug reporting in extension/devtools/etc. Could be something along the lines of "We can't audit a page that has an active service worker, make sure all pages to this origin are closed and try again"

**Comment by ev1stensberg** [comment]
Can't we just warn about it and close the tab that was opened first on the same origin? Could also close the service-worker if needed. 

Also, would like to work on this if you want me to :)

**Comment by patrickhulce** [comment]
Oh this was actually in fixed in Chrome already :) thanks though!

**Comment by ev1stensberg** [comment]
Sweet 🍰
