### ISSUE TITLE
audit: Can prompt recurring visitor to install to homescreen

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#23]
Manual evaluation: manifest has short_name,  144x144 png icon

##### input:
* parsed manifest - #22

##### audit:
- has a registered SW
- valid start_url
- valid name
- valid short_name
- icon of size >= 144x144 and png (either type `image/png` or filename ending in `.png`)

_update_: ^  Copied from brendan's comment below.

See also "PWA validator" bookmarklet - #17

docs:  [install-to-homescreen on /web](https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android?hl=en)  

##### when: 
* page loaded and in idle state

**Comment by paulirish** [comment]
from the docs: "Your icon declarations should include a mime type of image/png"

@brendankenny is going to verify in the source

**Comment by brendankenny** [comment]
currently required:
- manifest
- valid start_url
- valid name
- valid short_name
- icon of png (either type `image/png` or filename ending in `.png`)

**Comment by paulirish** [comment]
"valid". for url it's valid by chromium's gURL standards, right?   and then the two names it checks for exists and not empty?

**Comment by brendankenny** [comment]
for valid URL, it does appear that's correct. For the name checks, you may technically be able to get away with empty strings (it checks they aren't null), but I'm not sure. The manifest parse step may just covert empty strings to null.

**Comment by paulirish** [comment]
k cool​

**Comment by paulirish** [comment]
Nearly done, but we need to check for 144px icons instead of 192px. (But having 192 icons would allow the test to pass)

**Comment by paulirish** [comment]
@brendan  i have this alsmost complete in a branch on my fork. 1% battery. see you guys.

**Comment by brendankenny** [comment]
To add to this, on a macbook pro, I get a "256px square icon is required" in Chrome. The 256px appears to come from it not taking the emulated screen into account, but we may need to investigate the "square" part of that.

This seems to discard non-square icons:
https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/manifest/manifest_icon_selector.cc&rcl=1459883706&l=43

but this explicitly tests non-square is OK:
https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/banners/app_banner_data_fetcher_unittest.cc&sq=package:chromium&type=cs&q=%22Non-square%20is%20okay%22%20file:%5Esrc/chrome/browser/banners/

so not sure how these two worlds interact within Chrome.

**Comment by paulirish** [comment]
Fixed by the icons PR: https://github.com/GoogleChrome/lighthouse/pull/116

**Comment by paulirish** [comment]
Just verifying the check here:

source: https://cs.chromium.org/chromium/src/chrome/browser/installable/installable_manager.cc?type=cs&q=IsManifestValidForWebApp&sq=package:chromium&l=304

validity requires ALL of these:

1. manifest is not empty
1. manifest has valid start url
1. manifest has a valid name and valid shortname
1. manifest display property is either `standalone` or `fullscreen`
1. manifest contains icon that's a png and size >= `144`px
1. SW is registered, and it owns this page and the manifest's start url

Our audit is a little softer in its tests so far. It doesn't look at standalone/fullscreen and doesn't consider SW controlling the starturl. Also it checks for `shortname || name` when it should be `shortname && name`.

**Comment by brendankenny** [comment]
> manifest has a valid name and valid shortname

this one has been confusing because of the difference in context of use of the `short_name`. See #348, for instance. We should add a clear comment on this when we fix this :)

> It doesn't look at standalone/fullscreen

IMO we should get rid of the [manifest `display` audit](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/manifest-display.js) and rename it `chrome-a2hs-display.js` or whatever to make it clear what it is and test only for standalone/fullscreen

**Comment by paulirish** [comment]
Looked again at the current implementation ([installable_manager.cc](https://cs.chromium.org/chromium/src/chrome/browser/installable/installable_manager.cc) and [app_banner_manager.cc](https://cs.chromium.org/chromium/src/chrome/browser/banners/app_banner_manager.cc?g=0)): 


1. is secure
   * is either localhost or has a valid SSL Certificate
1. has a service worker
   * it must control the current url _and_ the manifest's start_url
1. valid_manifest
   * has a valid starturl
   * has either a name _or_ shortname (that isn't an empty string)
   * display is standalone/fullscreen/minimal-ui
1. has a satisfactory icon
   * must be a png
   * must be square
   * must be at least 72px, but chrome much prefers 144px or larger.
1. has sufficient engagement 
   * currently requires a `2`. see at chrome://site-engagement/
