### ISSUE TITLE
Big difference in perf measurement between Lighthouse and Chrome DevTools?!

### ISSUE THREAD

**Issue by Mika83AC** [GoogleChrome/lighthouse#2301]
Hello everyone,

not sure if it's correct to open an issue for that, if not, please forgive me ;)

I'm checking my PWA with Lighthouse and I'm getting a very big difference to its performance than to what the ChromeDevTools Performance tab tells me about it.

Here is the result of what the ChromeDevTools Performance tab tells (with Nexus 5 "emulation", Cache disabled, network throttled to "Good 3G"):
![image](https://cloud.githubusercontent.com/assets/3017748/26198392/26dd534a-3bc6-11e7-8b0d-6899e3209546.png)

What I read from this is: my PWA has finished the hard work and is fully displayed to the user after approx. 2 seconds. That's also what I observe in "real-life", that page loads fast (approx. 2 seconds) and is interactive to the user then.

Now Lighthouse:
![image](https://cloud.githubusercontent.com/assets/3017748/26198542/a5755928-3bc6-11e7-9cf6-561c2a182db5.png)

It tells me, that the first meaningful paint took place 6 (!) seconds after page load, which is definitely not what's going on and whats observable with bare eyes.

So my question is: who's wrong? Am I wrong and don't get something, is ChromeDevTools wrong, is Lighthouse wrong? ...

I'd be happy about ideas or advises what's the problem here.

Thx and best regards,
Michael

**Comment by patrickhulce** [comment]
The screenshot of the trace in the performance tab looks like network throttling has not been applied (perhaps a bug if this is reproducible for you?), and I would not trust those results. 

For the LH report, I see you're using 1.6.5 which uses much lighter throttling that isn't quite as representative of actual 3G speeds which we've addressed in our 2.0.0-alpha builds. The results of a quick run of that site for me with "Fast 3G" and "5x CPU throttling" in Chrome Canary (which Lighthouse will now match) results in a TTI on the order of ~20s (probably lower for you if the server is in Europe though :) ).

**Comment by Mika83AC** [comment]
@patrickhulce Oh, you're right. I had set the network throttling in the Network tab which does not affect the measurement on the Performance tab! Missed the hidden options there. Thx for your hint :)!
