### ISSUE TITLE
Extension Error: Invalid string length

### ISSUE THREAD

**Issue by ErstwhileWork** [GoogleChrome/lighthouse#2305]
**Lighthouse Version**: 1.6.5
**Chrome Version**: 59.0.3071.47
**URL**: http://mcdcc.org/
**Error Message**: Invalid string length
**Stack Trace**:
 ```RangeError: Invalid string length
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10076:17)
    at <anonymous>```

**Comment by XhmikosR** [comment]
Maybe try with version 2.0.0. I can't reproduce this v2.0.0 CLI.

**Comment by ErstwhileWork** [comment]
Works now after extension was updated to v2 automatically.  Tks

**Comment by paulirish** [comment]
Cheers. Usually has to do with a trace that's too big for JSON.parse to handle.

This is effectively a dupe of #1685
