### ISSUE TITLE
Wording issue --> "won't" should be "will"

### ISSUE THREAD

**Issue by glittle** [GoogleChrome/lighthouse#2311]
![image](https://cloud.githubusercontent.com/assets/85186/26259178/f7eb72a0-3c84-11e7-91a2-dbfd5fb29c15.png)

**Comment by patrickhulce** [comment]
related #1611 #1613

**Comment by morrme** [comment]
I'd like to make this change.

**Comment by paulirish** [comment]
fixed by #2478
