### ISSUE TITLE
Hash route is removed when running an Audit

### ISSUE THREAD

**Issue by yorchv** [GoogleChrome/lighthouse#2313]
Using 60.0.3104.0 (Official Build) canary (64-bit) built in Audit Dev Tool you are losing the state of the hash route when the audit begins.

Test Case:

Open a web page that contains a hash route:
IE: `www.example.com/index.html?queryParam=123#/hashRoute/secondParam`

Open Audit Developer Tool and Run a new Audit
Expected behavior:
Open the same URL Route that is currently active.
Actual Behavior:
Opens a url without the Hash Route
IE: `www.example.com/index.html?queryParam=123`

For Pages that use Routers Based on the Hash Values, this prevents the Audit to run specific PWA Routes or pages where Hash Routes determine the content/loading strategy.

**Comment by patrickhulce** [comment]
thanks for the report @yorchv I can confirm the issue! as a temporary workaround you can use the CLI or extension

filed https://bugs.chromium.org/p/chromium/issues/detail?id=724558

**Comment by patrickhulce** [comment]
fixed by https://codereview.chromium.org/2895913003, should be in tomorrow's Canary build
