### ISSUE TITLE
Should HTML element itself be subject to accessibility testing

### ISSUE THREAD

**Issue by fchristant** [GoogleChrome/lighthouse#2317]
Just checking if this is a false positive:

# Elements Describe Contents Well
## Screen readers and other assistive technologies require annotations to understand otherwise ambiguous content.

The element this is failing on:

`<html lang="en" data-template="empty" class="multiplebgs opacity rgba touchevents fontface textshadow backgroundsize flexbox flexboxlegacy objectfit object-fit no-ie no-ipad no-iphone no-ipod no-appleios wf-myriadpro-n7-active wf-myriadpro-n9-active wf-myriadpro-i6-active wf-myriadpro-n6-active wf-myriadpro-n4-active wf-myriadpro-n3-active wf-myriadpro-i9-active wf-myriadpro-i4-active wf-myriadpro-i7-active wf-myriadpro-i3-active wf-active">`

..which is just a normal HTML element that is annotated with Modernizr and font-loading state classes. How is this accessibility relevant? Is the HTML element itself read out loud in a screen reader? How is a developer to even solve this?

**Comment by patrickhulce** [comment]
@fchristant "Elements Describe Contents Well" is the overall audit group that contains a number of specific checks. If you could you send a screenshot or name of the specific audit that's failing, we'd be able to help more, but off the top of my head I might guess that it's the `bypass` audit that is failing which you can read more about in the [axe docs](https://dequeuniversity.com/rules/axe/1.1/bypass)

**Comment by fchristant** [comment]
@patrickhulce Thanks for responding. The text in my post is basically the exact output. 
You are right though that this was due to the bypass test. I simply added a H1 to the page and then it passes.

I do believe the wording and the specific element that is reported (the HTML element itself) is misleading, but now I understand why it failed, so thanks!

**Comment by patrickhulce** [comment]
Are the individual audits with explanations not showing up in your report? You should have seen an item that said "The page contains a heading, skip link, or landmark region" with a red X next to it. Looks like the below when passing. Please file another issue if you aren't seeing the details! :) Otherwise marking as closed

![image](https://cloud.githubusercontent.com/assets/2301202/26323590/567faf00-3ee4-11e7-9c38-c8f14ae68b69.png)

**Comment by fchristant** [comment]
Yes, I did see that. The only thing I found misleading is the actual item it is failing on, which was the HTML element itself. Without further explanation, this suggests that the HTML element itself needs some adjustment to pass the check, which is false. 

Could be that that is just my wrong interpretation though.

**Comment by alekseykulikov** [comment]
@fchristant I had similar issue, and thought that it's related with `<html lang="en-US">`
![image](https://cloud.githubusercontent.com/assets/158189/26551828/bec59e08-4484-11e7-8591-9dde72d0ed01.png)
I guess, after this PR https://github.com/GoogleChrome/lighthouse/pull/2370 goes live, it should be easier to figure out an actual issue.
