### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by obihill** [GoogleChrome/lighthouse#2318]
**Lighthouse Version**: 2.0.0
**Chrome Version**: 57.0.2987.133
**URL**: https://www.google.com.ng/search?q=lighthouse chrome error

**Comment by stramel** [comment]
Dupe of #1091

**Comment by obihill** [comment]
Ok, thanks. Sorry, I just clicked on report error without checking.

**Comment by stramel** [comment]
No problem :) Thanks for reporting
