### ISSUE TITLE
blob url shouldn't be flagged as insecure

### ISSUE THREAD

**Issue by shahraship** [GoogleChrome/lighthouse#2323]
when using Blob and window object url to load it, it flags it as an insecure request
for example:
`var blob = new Blob(['SOME JS WEB WORKER CONTENT']);
var worker = new Worker(window.URL.createObjectURL(blob));
worker.postMessage({});`
This loads a blob url in the browser network requests and is flagged as insecure.

**Comment by patrickhulce** [comment]
good catch thanks for the report @shahraship!

**Comment by paulirish** [comment]
@shahraship nice catch.
