### ISSUE TITLE
[user-scalable="no"] is not used in the <meta name="viewport"> even though its declared

### ISSUE THREAD

**Issue by oninross** [GoogleChrome/lighthouse#2326]
![screenshot_052217_094347_am](https://cloud.githubusercontent.com/assets/2233813/26288337/27da9ba8-3ed3-11e7-948c-4906f0498e55.jpg)

Am I missing something here?

**Comment by wardpeet** [comment]
thanks, might be a bug with our audit! Perhaps you have a real url we can test on?

**Comment by oninross** [comment]
Here you go
https://project-infinite-127eb.firebaseapp.com/#/hello/

**Comment by patrickhulce** [comment]
Ah @oninross @wardpeet this is a result of confusing help text :)

The audit is telling you to *not* use `user-scalable=no` and make sure your `maximum-scale` is greater than or equal to 5. Since you *are* disabling zoom by setting `user-scalable` to no and have a `maximum-scale` attribute less than 5, the audit failed.

**Comment by patrickhulce** [comment]
closing in favor of #1611

**Comment by oninross** [comment]
@patrickhulce thank you for the insights.  I thought it was standard to disable pinch zoom

**Comment by zwacky** [comment]
As I understood you shouldn't disable pinch-zoom for accessibility reasons (safarai on ios 10 even ignores the `user-scalable=no` bit).

Is there still a way to disable pinch zoom without getting penalized by lighthouse?

**Comment by patrickhulce** [comment]
@zwacky in short, no. 

You're correct disabling pinch-zoom harms accessibility as users with low vision could have trouble reading fine text. The accessibility score will always be docked for disabling pinch-zoom. You can read more about the check and the rationale at the [axe docs](https://dequeuniversity.com/rules/axe/1.1/meta-viewport).

If your app has specific modes with enhanced accessibility features such as GMail's high contrast theme and you wish to test it separately you can consider being selective about the audits/categories you run on each view.
