### ISSUE TITLE
Extension Error: Invalid string length

### ISSUE THREAD

**Issue by ErstwhileWork** [GoogleChrome/lighthouse#2329]
**Lighthouse Version**: 2.0.0
**Chrome Version**: 59.0.3071.61
**URL**: http://mcdcc.org/
**Error Message**: Invalid string length
**Stack Trace**:
 ```RangeError: Invalid string length
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12538:27)
    at <anonymous>```

Error easily reproducible by adding LightHouse extension to Chrome Beta .. still occurs consistently

**Comment by wardpeet** [comment]
is there any reason you are testing on Chrome Beta and not chrome canary?

**Comment by paulirish** [comment]
dupe of #1685

**Comment by ev1stensberg** [comment]
Working on a fix on this.

**Comment by ErstwhileWork** [comment]
Even -- when recently tested it appears that the google extension updated
to v 2.0.0 .. and the site in question (mcdcc.org) did successfully
complete.

FYI!

Thanks for your help!
Joseph
