### ISSUE TITLE
Errors in recorded traces

### ISSUE THREAD

**Issue by wwwillchen** [GoogleChrome/lighthouse#2333]
I've been running some benchmarking analysis for CPU throttling and came across some unusual trace from using Lighthouse to collect traces on an Android Nexus 4 device. 

The aggregated statistics (e.g. scripting) shows a negative value. I noticed there were numerous console errors from DevTools when loading these traces.

From caseq:

> It looks like it's due to a somewhat malformed trace we get from lighthouse, which is in turn likely due to poor timer resolution on Android combined with LH messing with traces by sorting the events using a non-stable sort.

**Comment by wardpeet** [comment]
Can this be related to https://github.com/GoogleChrome/lighthouse/issues/2336 ?

**Comment by wwwillchen** [comment]
@wardpeet - I don't think so because I saw it on pretty much every site with Nexus 4 and not all of them had redirects.

**Comment by brendankenny** [comment]
turns out this isn't Lighthouse messing with the trace, it's [`speedline`](https://github.com/paulirish/speedline/blob/31a398f798b0541ba5bb3dbe41ffc384cdf5b359/src/frame.js#L83) messing with the trace :)
