### ISSUE TITLE
Sites with redirects have wonky stats

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#2336]
I was puzzling over some recent metrics on a plots run of http://www.vkontakte.ru/ which reported traceEnd as 5s shorter than the length of the trace. This is because we take our stats relative to navstart which removes the time of the initial HTTP request, it seems we have inconsistent handling somewhere though because TTCI failed even though there is 5s of quiet.

Example Screenshot
![image](https://cloud.githubusercontent.com/assets/2301202/26331090/f9a9c606-3f03-11e7-92d2-a99fac18087a.png)

**Comment by patrickhulce** [comment]
Even more disturbing finding: traceviewer model does not give us timestamps that are relative to navstart but instead relative to TracingStartedInPage! This throws off *all* our timings and timestamps that use the traceviewer model, another great reason to get rid of it :)

**Comment by tdresser** [comment]
@deepanjanroy @benshayden

**Comment by patrickhulce** [comment]
Related: https://bugs.chromium.org/p/chromium/issues/detail?id=725301

LH-specific issues: We need to have consistent interpretation of task start/end timestamps by either remapping the times received from traceviewer model or remove it entirely and parse the trace ourselves

Overall metric questions: Which navstart in the trace is correct? `window.performance` identifies the beginning of the first request (the one that gets redirected) as startTime and the beginning of the final page request as requestStart. I'm inclined to prefer this interpretation as well so that sites with many potentially unnecessary redirects are penalized appropriately. 

Supposedly there are cases though where the first navstart is not particularly interesting or plain wrong which is why LH looked for the last one? cc: @paulirish

**Comment by patrickhulce** [comment]
The switch to use the last navstart occurred [here](https://github.com/GoogleChrome/lighthouse/commit/ea4561a42f1c750910c038aace4bf041b9eca4a1) in response to tracingStartedInPage being after navStart and to move in alignment with [traceviewer](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/system_health/loading_metric.html#L99), though I believe we could still use the first navstart but just use the frameId ffrom tracingStartedInPage

**Comment by deepanjanroy** [comment]
Since lighthouse usually takes in a url, and gives back some metrics on that url, I think it makes sense to include the time for redirects. If I want to know the stats for http://example.com, I care about the total time from when I click the link to when key user events happen. 

For traceviewer/chrome internal metrics, the story may be different - we'll have to think more about what makes sense.

**Comment by wardpeet** [comment]
going to link https://github.com/GoogleChrome/lighthouse/issues/2235 to this issue

**Comment by brendankenny** [comment]
> The switch to use the last navstart occurred [here](https://github.com/GoogleChrome/lighthouse/commit/ea4561a42f1c750910c038aace4bf041b9eca4a1) in response to tracingStartedInPage being after navStart and to move in alignment with [traceviewer](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/system_health/loading_metric.html#L99), though I believe we could still use the first navstart but just use the frameId from tracingStartedInPage

was there resolution on this? I don't remember the reasoning

**Comment by paulirish** [comment]
Lantern doesn't consider navStart, but essentially uses start of HTML request as the time origin for stats. This likely leads to reduced variance, but _some_ would argue the accuracy and/or truthiness is compromised.

**Comment by patrickhulce** [comment]
To clarify, Lantern uses the start of the very first request observed, not the start of the HTML request, and it is *navStart* approach that reduces the variance at the expense of accuracy/truthiness.

See the above trace screenshots for the example where the time spent in the http://www.vkontakte.ru/ request is ignored from all of our metric user timings.

**Comment by patrickhulce** [comment]
This is a duplicate of #8984 which is currently in progress.
