### ISSUE TITLE
Chromelauncher error on when killing instance

### ISSUE THREAD

**Issue by li-kai** [GoogleChrome/lighthouse#2337]
I've been trying to get headless chrome running, but I've been getting `Error: read ECONNRESET` which I've been able to reproduce consistently here:
```js
const lighthouse = require('lighthouse');
const chromeLauncher = require('lighthouse/chrome-launcher/chrome-launcher');

async function runLighthouse(url) {
  const opts = {
    chromeFlags: ['--headless'],
  };
  const chrome = await chromeLauncher.launch(opts);
  const flags = {
    output: 'json',
    port: chrome.port,
  };
  const results = await lighthouse(url, flags);
  await chrome.kill();
  return results;
}

runLighthouse('https://example.com');
```
Node versions used: 6.8.0 & 7.9.0
Lighthouse: 2.0.0
OS: Mac OS Sierra 10.12.4 & Ubuntu LTS 14.04 (Travis)

I've been able to fix this by either catching the `process.on('uncaughtException', ...` event in `chrome-launcher.js`, or setting a timeout on the `await chrome.kill();` code. Neither of which I believe is ideal since I'm quite new to Node.

**Comment by ebidel** [comment]
I've been seeing this too when using headless Chrome. We need to investigate.

Until then, the workaround is what you're doing...introduce a small delay before killing chrome. See also https://github.com/GoogleChrome/lighthouse/issues/1931#issuecomment-298247273.

**Comment by samccone** [comment]
Thanks for the test case, we will get to the bottom of this.

**Comment by samccone** [comment]
Confirmed this is 100% reproducible on headless but not on normal chrome.
Wrapping the code in a 2 second timeout fixes things, but that is not a real fix. My guess is that this is a behavior difference in lighthouse in headless, and is not related to launcher directly. 

```typescript
const lighthouse = require('lighthouse');

import {launch} from './chrome-launcher';

async function runLighthouse(url: string) {
  const opts = {
    chromeFlags: ['--headless'],
  };
  const chrome = await launch(opts);
  const flags = {
    output: 'json',
    port: chrome.port,
  };

  const results = await lighthouse(url, flags);

  process.on('uncaughtException', (e: any) => {
    console.log(e);
  });

  await chrome.kill();
  return results;
}

runLighthouse('https://example.com');
```

**Comment by ebidel** [comment]
Circling back. `--headless` should work without the delay now. Be sure to update to LH 2.1.0.

**Comment by samccone** [comment]
ack, the root of this bug was in lighthouse, headless just made it happen more 🗡

**Comment by bliu23** [comment]
Is this actually fixed? I'm launching headless chrome with chrome launcher v0.3.2 and running into this issue.

Should I instead be using lighthouse and importing the chrome-launcher module?
