### ISSUE TITLE
Launch Lighthouse Viewer 2.0

### ISSUE THREAD

**Issue by timgupta** [GoogleChrome/lighthouse#2338]
With the new output from the Lighthouse chrome extension, I'm getting an error in the online lighthouse report viewer:
Unknown formatter: url-list

Here's the report I'm trying to view:
https://googlechrome.github.io/lighthouse/viewer/?gist=9d2eb55e4969527cbfaa76c557ea9755

**Comment by ebidel** [comment]
Thanks for reporting. Viewer needs to be updated to work with 2.0's output. We'll be looking at this soon.

**Comment by timgupta** [comment]
Great thanks! By the way, the new 2.0 output is beautiful! :)

**Comment by emjayess** [comment]
I just encountered this as well, with json output from canary; any workarounds? - alternative viewer or a way to export pre-2.0 json for this viewer, until this is reconciled?

**Comment by ebidel** [comment]
@emjayess a temporary workaround would be to export the report as json (top right corner sharing button). Then, drag and drop that file onto Chrome Canary's Audit's panel. DevTools will load and display the Lighthouse. You won't get a permalink, but it's something :)

**Comment by emjayess** [comment]
> You won't get a permalink, but it's something :)

@ebidel I generated the report in (and saved the json from) canary's audit panel, and specifically am wanting something team-shareable, so I'll eagerly await the 2.0 viewer launch. Meanwhile I've grapped the lighthouse cli and will be trying the html output of that tool. Thanks!

**Comment by ebidel** [comment]
Yea, sorry about that. We wanted to get it updated for 2.0, but it slipped.

**Comment by emjayess** [comment]
* Incidentally, "Save as > Html" in the audit panel might be handy :)

**Comment by ebidel** [comment]
Tell me about it :) DevTools really just needs to adopt our standard button instead of doing it's own thing:

<img width="179" alt="screen shot 2017-05-25 at 9 06 59 am" src="https://cloud.githubusercontent.com/assets/238208/26458916/923c5ea2-4129-11e7-8671-ad513bdbe54a.png">

**Comment by ebidel** [comment]
@bckenny are you taking this then?

**Comment by brendankenny** [comment]
I'm getting it working again, then we can iterate to get it working well again :)

**Comment by ithinkihaveacat** [comment]
Is there any way to get the LH 1.x format JSON, so it can be shared via the viewer?
