### ISSUE TITLE
Improve cache start_url gatherer (strategy)

### ISSUE THREAD

**Issue by wardpeet** [GoogleChrome/lighthouse#2342]
There are a few issues with start_url being cached. 
1) of them is that the manifest is not cached and can not be retrieved.
2) Another is that the start_url is not yet cached by the service worker.

There are a couple of solutions that we went over

1) Cache manifest inside driver.js (getAppManifest). We cache the manifest during the main pass. And get it in the offline pass.
-- Downside is that we always need another pass (which is not ideal).
2) Offline pass should navigate to start_url instead of the current url. We fix both issues with this fix. -- lighthouse needs to know about the manifest inside the runner which makes lighthouse smarter than we probably want to know
3) Monitor the service worker and see what requests it caches
-- tricky to do as we need to use the SW as our debug target.
4) Read the requests inside the cache api.
-- Not sure if this will work

If anyone has more ideas please let me know

**Comment by paulirish** [comment]
Mostly outdated, but merging into #709
