### ISSUE TITLE
WebPageTest is using 2.0.0 w/ the old report

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2344]
Example: https://www.webpagetest.org/lighthouse.php?test=170523_CK_1C1G&run=1

Doesn't look all that bad, but we should flip the `html` default to the new report, so everybody has the new stuff, eh?

**Comment by patrickhulce** [comment]
@paulirish domhtml is the default now, but WPT explicitly requests HTML and JSON output I believe :)

**Comment by paulirish** [comment]
ah! let's give WPT a PR then!
