### ISSUE TITLE
New audit: Flag password fields that can't be pasted into

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2345]
Last week this article went around: https://www.ncsc.gov.uk/blog-post/let-them-paste-passwords
And it makes the case for password fields always being paste-able.

This is something we can test in Lighthouse without too much work.

While we could do this all on the protocol side, it seems rough: `DOM.querySelectorAll` for `input[type=password]`, then use `getEventListeners` on each node to see if there's a paste event handler. Look at the source of each handler to see if it mentions `preventDefault`. 😿 

### Proposal
In a big `evaluateAsync`, querySelectorAll in the page looking for these inputs. For each of them... construct a [new `paste` event](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/ClipboardEvent) and dispatch it on the element. see if `defaultPrevented` was flipped.

```js
event = new ClipboardEvent('paste', {cancelable: true})
elem.dispatchEvent(event);
event.defaultPrevented // ?!?!?!
```

Then in the audit we just report whichever elements had the event defaults prevented.

--------

Seems like a bit of fun, this one. 

A new contributor want to try it out?

**Comment by wardpeet** [comment]
+1 for new contributors!!! Ask away if you're having troubles.

**Comment by stramel** [comment]
@paulirish I wonder if it would be good to also add a check for the meta of autocomplete to it as well?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password#Allowing_autocomplete

**Comment by paulirish** [comment]
@stramel that one is tracked at https://github.com/GoogleChrome/lighthouse/issues/1639 ;)

you interested? :)

**Comment by stramel** [comment]
😓 I can give it a shot lol Thanks for pointing me to the right issue!

**Comment by robin-drexler** [comment]
Since https://github.com/GoogleChrome/lighthouse/issues/2366 is merged, can't this be closed?

**Comment by patrickhulce** [comment]
indeed @robin-drexler thanks again!
