### ISSUE TITLE
File structure refactor proposal

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#236]
I've been dreaming about some slight changes to the folder structure. A few motivations:

* clean up the root folder so we don't have legit source files astrewn with our dotfiles.
* codify some of the conventions we've found
* make the structure a bit more newb-friendly

Here's what i'm proposing

```md
- test/
- closure/
- typings/
- scripts/
  - launch_chrome.js
  - run-smoke-tests.sh
  - download_chrome.sh
- src/
  - index.js
  - scheduler.js
  - aggregator.js
  - auditor.js
  - runner.js
  - cli/
    - index.js
    - printer.js
  - lib/  (née helpers)
    - drivers/
  - gatherers/
  - audits/
  - aggregators/
  - metrics/
- extension/
- report/
- index.js (empty-ish)
- (all the dotfiles)
```

* CLI would now be via `node src/cli https://pwa.rocks.com` or continue to use `npm link` & `lighthouse`
* index.js would be the entry point that's shared across both CLI & extension. (it's close to what it is today, mostly deferring to runner.js)

Thoughts?

**Comment by samccone** [comment]
l
g
t
m

**Comment by gauntface** [comment]
+1

**Comment by paulirish** [comment]
@paullewis if you're keen, i'll put this up over the weekend so we minimize disruption of active development.

**Comment by paullewis** [comment]
Yeah it's cool. Go for it, sir!

**Comment by brendankenny** [comment]
LGTM. Make sure to `git mv` so history isn't lost :)

**Comment by sindresorhus** [comment]
@brendankenny http://stackoverflow.com/a/3010099/64949

**Comment by brendankenny** [comment]
> @brendankenny http://stackoverflow.com/a/3010099/64949

it depends on how much the file has to subsequently change to work with the refactor. If you move and then commit the delete/add and *then* make changes, that should always work, but then you might as well `git mv` :)

It's also partly working around github's interface. I don't think they support `--follow` for file history, so the first commit for a moved file would be the creation of it, not a move of it from somewhere else, but I'd love to be wrong there.
