### ISSUE TITLE
HTTP redirects to HTTPS audit doesn't work on android

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#2363]
When you run Lighthouse on WPT or on any Android device, the security domain does not work properly and thus fails the HTTP redirect check, [see this report as example](https://www.webpagetest.org/lighthouse.php?test=170525_5S_14TQ&run=1). 

We should do what we did for is on HTTPS and just check for the scheme.

**Comment by ev1stensberg** [comment]
Can work on this. Need more context around the meaning of `WPT`, as my best search results were 🎴  World Poker Tournament 🎴 . 

> We should do what we did for is on HTTPS and just check for the scheme. 

Mind clarifying with relevant links and some more details?

**Comment by brendankenny** [comment]
> World Poker Tournament

`WPT` is [WebPagetest](https://www.webpagetest.org/) :D

for background, see discussion and changes to `is-on-https.js` in #1918

**Comment by patrickhulce** [comment]
Sure :) WPT stands for https://www.webpagetest.org/ which is open source and does performance testing as a service. We have a Lighthouse integration there that enables you to get a LH report along with your regular report when you run it on one of their mobile devices. 

Unfortunately the [security domain we use](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/http-redirect.js#L45) to tell if you are on a https doesn't work on android. We encountered this with the `is-on-https` audit too which we switched to just parse the URLs and check if the scheme is `https` instead of using the security domain (see #1918). 

I'm thinking we do something similar for the `http-redirect` gatherer and don't use the security state but just check that the final URL has https scheme

**Comment by ev1stensberg** [comment]
Gotcha! Let me bring up a PR for that possibly due thursday. If you know where to fix at android I can do it there instead, either way is fine with me. ( If the android implementation is OSS )

**Comment by patrickhulce** [comment]
> If you know where to fix at android

I wish it were that simple :D either way we've going to have to work around this here in LH quickly since a fix for Android Chrome won't necessarily get pushed out soon even if we had one today. If you're curious though you can take a look at the [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=503216) and poke around the [Chromium code](https://cs.chromium.org/search/?q=securitystatechanged+-f:out&type=cs)

**Comment by ev1stensberg** [comment]
This one: https://github.com/GoogleChrome/lighthouse/blob/f03f287a37df872c763d81bc2e4c4d8f29e82c08/lighthouse-core/audits/is-on-https.js#L57

Fetches all urls from network, or?

**Comment by patrickhulce** [comment]
Right, that audit checks that all requests in the default pass used https. To fix this one though, you probably won't even need to mess with network records you could just check the final url in the `afterPass` method of `http-redirect` gatherer

**Comment by ev1stensberg** [comment]
Yep, doing it right now. Watching how you're building up audits to better know the source code while at it

**Comment by ev1stensberg** [comment]
Left it at #2396 , please, do an extensive review, this seems too simple and could break stuff

**Comment by paulirish** [comment]
The simple fix: in afterPass we evaluateAsync `new URL(window.location).protocol === 'https:'` instead of using Security domain.

I'm going to take this.

**Comment by kevmoo** [comment]
@paulirish – would *love* a fix here 😄
