### ISSUE TITLE
Testing on mobile devices no longer works

### ISSUE THREAD

**Issue by dandv** [GoogleChrome/lighthouse#2368]
I've upgraded to 2.0.0. and found that [testing on mobile devices](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#testing-on-a-mobile-device) no longer work. Lighthouse launches a new Chrome tab on my Goobuntu machine.

I've verified that port forwarding works by navigating in Chrome to localhost:9222:

![image](https://cloud.githubusercontent.com/assets/33569/26475265/8e158870-416b-11e7-8b71-af197ca372d4.png)

However, when I run `lighthouse --disable-device-emulation --disable-cpu-throttling https://google.com`, LH opens a new Chrome tab on my desktop, not on the Android device.

**Comment by ev1stensberg** [comment]
I can work on this if you'd like to 👍

**Comment by ev1stensberg** [comment]
There we go ✌️

**Comment by patrickhulce** [comment]
@dandv for now you'll have to manually specify the port `9222` as there was a breaking change to randomly select the port instead of always using `9222`

**Comment by ev1stensberg** [comment]
The PR sets to use 9222 if we are on mobile emulation

**Comment by ebidel** [comment]
Think we can close this. The solution is to use `--remote=9222` when running LH.
