### ISSUE TITLE
launcher/cli: coveralls isn't mapping back to TypeScript

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2374]
For example: https://coveralls.io/builds/11707972/source?filename=chrome-launcher%2Fchrome-finder.js

Because the coverage was gathered in JS. Need to remap to get type lines of TS accounted for.
https://www.sitepen.com/blog/2015/09/29/code-coverage-for-typescript-and-other-transpiled-languages/

**Comment by patrickhulce** [comment]
[nyc](https://www.npmjs.com/package/nyc) makes this a little easier FYI :) I use it on some typescript projects

basically
`nyc mocha`
`nyc report --reporter=text-lcov | coveralls`
