### ISSUE TITLE
Binary scoring modes returning numeric scores

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#2375]
In the following audits, a scoring mode of binary is given but a value of 100 is given instead of true or false.

```
Lighthouse binary scoring mode has 100 score: screenshot-thumbnails
Lighthouse binary scoring mode has 100 score: offscreen-images
Lighthouse binary scoring mode has 100 score: uses-webp-images
Lighthouse binary scoring mode has 100 score: uses-optimized-images
Lighthouse binary scoring mode has 100 score: uses-responsive-images
Lighthouse binary scoring mode has 100 score: link-blocking-first-paint
Lighthouse binary scoring mode has 100 score: script-blocking-first-paint
```

**Comment by ev1stensberg** [comment]
What do I need to do to test this in the CLI @gauntface ?

**Comment by patrickhulce** [comment]
@gauntface where are you seeing these messages/why are you interested in inspecting the individual score outside of the category? 😄 

currently, the meaning of `scoringMode` is pretty confusing and intended for display only (`typeof score` should eventually always be a number with `scoringMode` suggesting how to interpret that number), understanding your use case could help us shape it though

**Comment by gauntface** [comment]
I am using the lighthouse module in my unit tests.

Run page through lighthouse, pass / fail unit tests based on the score.

**Comment by paulirish** [comment]
We now explain this in detail: https://github.com/GoogleChrome/lighthouse/blob/master/docs/understanding-results.md#audits

I do sort of agree it's confusing, but hey.

**Comment by gauntface** [comment]
Maybe rename `scoringMode` to something like `displayMode`?
