### ISSUE TITLE
Remove references to target/optimalValue

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#2376]
For speed-index-metric I'm getting a rawValue which is lass than the optimal value but a score less than 100.

For example I can get the following info: `Value was 1222, the optimal value is < 1,250 but the score was 98`.

This get's more confusing when I can get values over 1250 and still have the same score of 98.

How is the scoring of this calculated and is the "optimal value" really worth even mentioning if hitting it doesn't mean 100.

**Comment by patrickhulce** [comment]
We've been removing the optimal value in other metrics due to confusion and emphasis on the timeline instead, +1 to removing it for the remaining metrics too 👍

**Comment by brendankenny** [comment]
death to `optimalValue`! The only thing going for it over just putting it in the text description if *really* needed is that it gets some nicer formatting. We could always expand the supported markdown if we wanted to keep that around.

**Comment by brendankenny** [comment]
As discussed last week:
- could delete `optimalValue` (`target` in the report)
- could also better explain target value/what score really means

**Comment by gauntface** [comment]
I'd say remove it.

**Comment by vinamratasingal** [comment]
Closed by #3774
