### ISSUE TITLE
HTTP->HTTPS redirect via JS fails redirects-http audit

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/lighthouse#2383]
I created a quick sample https://pwa.glitch.me/

I don't have control over the serving on the static site so I can't easily 30X redirect HTTP to HTTPS. Instead I have a little piece of javascript that changes the protocol from http to https.

According to the [docs] it should pass the test.

>How to pass the audit
>
> Use canonical links in the head of your HTML to help search engines figure out the best way to get to the page.
> 
> Configure your server to redirect HTTP traffic to HTTPS. See your server's documentation to figure out the best way to do this.
> ...
> Lighthouse changes the page's URL to http, loads the page, and then waits for the event from the Chrome Debugger that indicates that the page is secure. If Lighthouse does not receive the event within 10 seconds then the audit fails.

Not sure if it is the test that is broken, or the docs that need more clarification.

[docs]: https://developers.google.com/web/tools/lighthouse/audits/http-redirects-to-https

**Comment by patrickhulce** [comment]
This situation should also hopefully be fixed by #2396

**Comment by ev1stensberg** [comment]
Doable when we add the initial URL [here](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L535) and [here](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L66), later validating it the same way as we did at #2396

**Comment by ev1stensberg** [comment]
⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️  ⭐️ ⭐️ 
![skjermbilde 2017-06-01 kl 17 08 30](https://cloud.githubusercontent.com/assets/16735925/26686397/11d918c6-46ed-11e7-9fa0-1c3eeeb17b69.png)
⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️

**Comment by paulirish** [comment]
Closing due to low priority.
