### ISSUE TITLE
Confusion in Accessibility audit

### ISSUE THREAD

**Issue by panayotov** [GoogleChrome/lighthouse#2387]
I think there is mistake in the Accessibility audit:

I get **Accessibility 97** for the following reason:
### Meta Tags Used Properly
_Screen readers and other assistive technologies require annotations to understand otherwise ambiguous content._

[user-scalable="no"] is not used in the <meta name="viewport"> element and the [maximum-scale] attribute is not less than 5.

View failing elements
`<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,minimal-ui">`

My meta seems alright, what might be the problem?

**Comment by ev1stensberg** [comment]
https://css-tricks.com/probably-use-initial-scale1/ 

> And while initial-scale=1 is pretty useful, maximum-scale is bad news for accessibility.

I'd leave it like this, common pattern, adjustable in JS/CSS
![skjermbilde 2017-05-29 kl 23 18 10](https://cloud.githubusercontent.com/assets/16735925/26562283/468c5012-44c5-11e7-87ea-057cba5faf5c.png)

**Comment by eric30** [comment]
This link might also be helpful: https://dequeuniversity.com/rules/axe/1.1/meta-viewport

**Comment by patrickhulce** [comment]
@panayotov this is as expected, the audit is telling you to not use `user-scalable=no` and have a maximum scale of 5 or more, you have included `user-scalable=no` and set a maximum scale of 1, so it failed. See @eric30's link for more info and hopefully #2418 should clear up more of these issues

**Comment by aseem2625** [comment]
@patrickhulce What you're saying is correct, however the error message shown isn't correct. It showed me that `user-scalable=no` is not there even when it was there.

**Comment by patrickhulce** [comment]
@aseem2625 yes, right now *all* audit descriptions are consistent in that they tell you the state you *should* be in, not the state that you *are* in. There has been a lot of confusion around this though, and #2418 will change this to have the behavior you're expecting.

**Comment by ev1stensberg** [comment]
Just correcting @patrickhulce with a minor comment: New patch on this is at #2478 , as the prev branch had some rebasing issues
