### ISSUE TITLE
navigationStart was not found in the trace

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#2394]
Extension running Lighthouse 2.0.0.

**Issue**

A few of the apps on HNPWA.com run into issues with LH 2.0's performance metrics auditing where we didn't with 1.x. We see `Audit error: navigationStart was not found in the trace` exceptions leading to a 0 on performance 😢 

![image](https://cloud.githubusercontent.com/assets/110953/26602023/ef9817e2-4536-11e7-9032-a8c5f1d6e72f.png)

I remember flagging a similar issue a few weeks ago so this might be fixed in master but just waiting for a release. Is this a newer version of the issues from https://github.com/GoogleChrome/lighthouse/issues/753?

I wanted to drop a suggestion in here that it might be worth us highlighting that if a set of exceptions lead to a poor score in any bucket, we should provide a visible banner/message encouraging users to re-run the test 🔔 

I've had a few users ask us why the scores on site are so different between 1.x and 2.x and the above is what's been tripping folks up a lot of the time :)

**Comment by patrickhulce** [comment]
Hm this is an improved error message of what used to be #1253, we're actually casting a wider net in our ability to find navstart with 2.0 (#1895), so something else must be at play. @addyosmani any patterns you're seeing that might help narrow this down? particular frameworks, load strategies, etc?

+1 to flagging certain errors as prompting for a re-run

**Comment by addyosmani** [comment]
I've seen this happen more often on apps that are taking advantage of HTTP/2 Server Push but it's not been limited to those deployed with that setup. I might say apps using PRPL might be more susceptible.

Just tested Polymer Shop:

![image](https://cloud.githubusercontent.com/assets/110953/26607298/ae4e00d0-454a-11e7-8474-fc43e4fe3b46.png)

and Polymer News:

![image](https://cloud.githubusercontent.com/assets/110953/26607270/8ecc07f2-454a-11e7-9630-cdf806a0d5b5.png)

**Comment by mosh2151984** [comment]
Audit error: navigationStart was not found in the trace
the same problem
![screenshot 2017-07-06 at 6 36 50 pm](https://user-images.githubusercontent.com/24643535/27937066-259a269a-627a-11e7-8a9c-587d68a6bae1.png)

**Comment by alexd3d** [comment]
Hi! react-create-app deployed to firebase hosting also showed the same scores and error.

**Comment by 4selin** [comment]
I got that error on localhost after adding defer=defer to all scripts

**Comment by nnnikolay** [comment]
Now the audit app built in to the Chrome and I see the same.

**Comment by erikbaan** [comment]
I have the same problem for an AngularJS app.

**Comment by walles** [comment]
Getting this here:
https://walles.github.io/weatherclock/

Lighthouse invoked via Chrome 60's new Audit tab.

**Comment by shmool** [comment]
Deployed a simple Angular (4.3.5) app created with Angular-CLI (1.3.1) to Firebase without any service-worker or PWA enhancements.
Got 51 on performance.

Then added the package `@angular/service-worker` (1.0.0-beta.16) and `"serviceWorker": true` in .angular-cli.json, no additional configuration. Built and deployed to Firebase.
Got performance 0 with the same problem: `Audit error: navigationStart was not found in the trace.`

**Comment by patrickhulce** [comment]
@shmool does it happen every time or just occasionally?

@walles do you experience this every time as well? I'm unable to reproduce on that URL.

**Comment by elijahmurray** [comment]
Same issue, but specifically it's calling out `hotjar`.

![image](https://user-images.githubusercontent.com/3240306/29943206-a2016474-8e66-11e7-9439-009f731d9800.png)

**Comment by walles** [comment]
Turning off Adblock made this issue go away for me.

Anybody else running with Adblock enabled?

**Comment by walles** [comment]
For completeness, here's what I get in my console as well (with Adblock turned on):
```
elemHideEmulation.js:385 SyntaxError: Failed to parse Adblock Plus selector a:-abp-contains(Sponsored), invalid pseudo-class :-abp-contains().
    at ElemHideEmulation.parseSelector (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/elemHideEmulation.js:386:9)
    at ElemHideEmulation.parseSelector (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/elemHideEmulation.js:377:31)
    at getFiltersFunc.patterns (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/elemHideEmulation.js:513:30)
    at sendResponseAndClearCallback (extensions::messaging:366:9)
    at messageListener (extensions::messaging:398:11)
    at EventImpl.dispatchToListener (extensions::event_bindings:380:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:364:35)
    at EventImpl.dispatch (extensions::event_bindings:386:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:149:26)
parseSelector @ elemHideEmulation.js:385
parseSelector @ elemHideEmulation.js:377
getFiltersFunc.patterns @ elemHideEmulation.js:513
sendResponseAndClearCallback @ VM83 extensions::messaging:366
messageListener @ VM83 extensions::messaging:398
EventImpl.dispatchToListener @ VM76 extensions::event_bindings:380
publicClassPrototype.(anonymous function) @ VM82 extensions::utils:149
EventImpl.dispatch_ @ VM76 extensions::event_bindings:364
EventImpl.dispatch @ VM76 extensions::event_bindings:386
publicClassPrototype.(anonymous function) @ VM82 extensions::utils:149
dispatchOnMessage @ VM83 extensions::messaging:339
```

**Comment by maiermic** [comment]
> Anybody else running with Adblock enabled?

@walles Confirmed, it works if I tell [Adblock](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom?hl=de) not to run on the [page](http://cyclejs.github.io/todomvc-cycle/).

**Comment by patrickhulce** [comment]
Ah this is great additional info to help us figure out what's going on, thanks @walles and @maiermic!

**Comment by 4aficiona2** [comment]
@walles @maiermic  I can confirm this too! After disabling my Chrome AdBlocker extension everything worked as expected. Thanks!

**Comment by Slapbox** [comment]
I get this issue as soon as I switched my caching for my site to use PHP7-FPM with NGINX. Any thoughts?

**Comment by brendankenny** [comment]
@Slapbox do you get this consistently? Do you have a URL that's publicly accessible?

There's no obvious reason server-side changes should cause this error, but it is possible it does so indirectly and it would be good to investigate.

**Comment by paulirish** [comment]
Brendan indicates this error is present on 0.9% of pages.

**Comment by brendankenny** [comment]
> Brendan indicates this error is present on 0.9% of HA pages.

sorry, that was wrong, that's just the rate at which Lighthouse fails to find FMP, but that's now 100% due to ``No usable `firstMeaningfulPaint(Candidate)` events found in trace``.

I find 0 instances in HTTP Archive of `navigationStart was not found in the trace` (which should win over looking for the above `firstMeaningfulPaint(Candidate)` error), which seems to indicate that this is no longer an issue.

*However*, the above comments are all reported errors from the extension. I wonder if it's still an issue there while on the command line it's no longer a problem.

We should also probably mention AdBlock as a possible culprit along with virus scanners in #2674

**Comment by JohnRSim** [comment]
Audit error: No usable `firstMeaningfulPaint(Candidate)` events found in trace
I'm getting this when supplying async tag to <link/script> tags 
Running vuejs2/firebase project.

If I remove async then the error is no longer displayed

**Comment by patrickhulce** [comment]
@JohnRSim do you have a public URL where we can reliably reproduce?

**Comment by brendankenny** [comment]
This is a perennial trace issue that we're always dancing with. Since there hasn't been any movement in this particular thread for 1.5 years, going to close.
