### ISSUE TITLE
Don't include initial http route on HTTPS audits

### ISSUE THREAD

**Issue by ev1stensberg** [GoogleChrome/lighthouse#2397]
Tested this on an Google Pixel XL. Seems like the initial HTTP route gets audited instead of us redirecting to HTTPS if possible and auditing that.
![skjermbilde 2017-05-30 kl 23 44 33](https://cloud.githubusercontent.com/assets/16735925/26606576/bf02eeb6-4592-11e7-896f-d314e2c4dadd.png)
![skjermbilde 2017-05-30 kl 23 44 12](https://cloud.githubusercontent.com/assets/16735925/26606577/bf084f3c-4592-11e7-9484-b570c67ab599.png)

**Comment by patrickhulce** [comment]
@ev1stensberg could you be more specific? if you test an `http` url explicitly then failing these audits is expected even if it redirects to https, we could add a debug string similar to https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/works-offline.js#L47 for these though

**Comment by ev1stensberg** [comment]
I'd expect that we should try to audit the https if it's standard. If you're a pragmatic tester, you'd use a http protocol to ensure you get feedback. At least, that is how I'd think

**Comment by ebidel** [comment]
+1 on the debug string like https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/works-offline.js#L47. This is one of those gotchas that you only run into when using the CLI. When using the extension/DevTools, you'll already be at the redirected URL.

**Comment by brendankenny** [comment]
closing in favor of #1917
