### ISSUE TITLE
Update Readme for Instructions for running lighthouse cli for site with authentication.

### ISSUE THREAD

**Issue by mikerhyssmith** [GoogleChrome/lighthouse#2404]
The current instructions in the documentation for running lighthouse against a site where you need to login first are:

- Run chrome-debug
- navigate to and log in to your site
- in a separate terminal tab lighthouse http://mysite.com

However, from what I can see for this to work when you run the lighthouse command you would need to add --port and the port number the chrome-debug instance is running on otherwise it opens a new instance of Chrome.

Happy to open a PR if this is the best way but it might be there's a better way of doing this !

**Comment by ebidel** [comment]
Correct. The chrome launcher was changed to select a random port rather than defaulting to 9222. 

PR would be great which adds the `--port`!

cc @samccone @paulirish another case where a rando port makes things harder.

**Comment by brendankenny** [comment]
yeah, #2259 would fix a lot of those cases but not this one
