### ISSUE TITLE
plots: graph metrics over time (e.g. different lighthouse versions)

### ISSUE THREAD

**Issue by wwwillchen** [GoogleChrome/lighthouse#2413]
The Lighthouse team wants to see how performance metrics have evolved over time as lighthouse has changed.

### Phase 1 - Plots over time locally
* This allows you to select multiple out folders and creates a comparison chart

### Phase 2 - Nightly plots
* Does a nightly run on master and records the artifacts (in Google Cloud Storage or GitHub gh-pages?)
* Link to a site that shows plots over time

Part of https://github.com/GoogleChrome/lighthouse/issues/1980

**Comment by patrickhulce** [comment]
dupe of #3461
