### ISSUE TITLE
Headless Chrome: Serve images as WebP Audit does not return results

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#2414]
Full Chrome finds images to optimize:

<img width="831" alt="screen shot 2017-05-31 at 5 03 30 pm" src="https://cloud.githubusercontent.com/assets/238208/26659085/21bd1d2a-4623-11e7-8a48-e31243cbb12e.png">

Headless Chrome does not:
<img width="821" alt="screen shot 2017-05-31 at 5 04 22 pm" src="https://cloud.githubusercontent.com/assets/238208/26659105/38b09e8a-4623-11e7-8da1-c2bfdb01baf9.png">

**Comment by ev1stensberg** [comment]
Want me to work on this?

**Comment by ebidel** [comment]
Needs investigating. If you want to throw in some time/research and report back on this bug, that would be great. It could also be a bug with headless chrome.

**Comment by ev1stensberg** [comment]
I'll implement a fix for #2418 and move to this by next week! Got oral exams next week, so might need to delay this, but definitely up for the task

**Comment by ev1stensberg** [comment]
@ebidel Can you assign me to this issue so I don't forget it? Easier to navigate to 👍

**Comment by ebidel** [comment]
Unfortunately you can't assign issues to non-project members. Don't believe anyone has looked into this yet, so you should be ok to research.

**Comment by ev1stensberg** [comment]
Gotcha!

**Comment by ev1stensberg** [comment]
@ebidel Could you post a screenshot of how this looks with the new version of lighthouse? Can't get the same results as you at the extension or running from the cli directly. 

URL: https://www.theguardian.com/international

![skjermbilde 2017-07-08 kl 02 24 42](https://user-images.githubusercontent.com/16735925/27980957-a2a53548-6384-11e7-8808-42d8a655e326.png)

**Comment by paulirish** [comment]
Here's my attempt to repro:

```sh
# do these in separate tabs, naturally
chrome-debug --port=9223
lighthouse --perf https://paulirish.com --port=9223

# then, in headless..
chrome-debug --port=9223 --headless
lighthouse --perf https://paulirish.com --port=9223
```

However in both cases I saw the same images listed.

I THINK what's happening is the network throttling isn't applying, and as a result, some images aren't hitting the threshold required to remain in the list.

So that isn't specific to webP, just the overall network throttling bug.
