### ISSUE TITLE
Lighthouse fails to dismiss page dialogs

### ISSUE THREAD

**Issue by pmeenan** [GoogleChrome/lighthouse#2423]
Lighthouse is having issues with pages that have dialogs (at least some types of dialogs) and times out when loading the page.

FWIW, WebPageTest had similar issues and [now](https://github.com/WPO-Foundation/wptagent/blob/master/internal/devtools.py#L641) tries first to "accept": false the dialog and if that fails tries "accept": true.  Similar logic in Lighthouse should make it more robust for pages with dialogs.

Test page: http://www.dlsite.com/

Log:
```
  status Loading page & waiting for onload +7ms URL, Viewport, ViewportDimensions, ThemeColor, Manifest, ChromeConsoleMessages, ImageUsage, Accessibility, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, OptimizedImages, ResponseCompression, TagsBlockingFirstPaint, WebSQL
  Driver:warn confirm dialog opened by the page automatically suppressed. +4s
  method <= browser ERR:error Page.handleJavaScriptDialog +1ms 
```

**Comment by pmeenan** [comment]
It looks like Lighthouse only tries "accept":true and tries that first and it [intentional](https://github.com/GoogleChrome/lighthouse/blob/48b72a8537e233c873d68e923e2e224112adfcfd/lighthouse-core/gather/driver.js#L933).

**Comment by pmeenan** [comment]
At a minimum, the test should fast-fail when the dialog dismissal fails (whether or not it falls back to false).

**Comment by patrickhulce** [comment]
Ah thanks for the tip @pmeenan we've been struggling with this in CI too!
