### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by jinliming2** [GoogleChrome/lighthouse#2431]
**Initial URL**: https://ipv6.google.com/
**Chrome Version**: 61.0.3118.3
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@797341a0d5f7d8e7f4eb921be3edaccecc0498db/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by ev1stensberg** [comment]
Let's close this and resume the fun at #1091

**Comment by jinliming2** [comment]
OK... I just follow the browser's tip links me to here.

**Comment by ev1stensberg** [comment]
Yep, you did everything right, thanks for confirming this is an important issue 👍
