### ISSUE TITLE
README: add explainer blurb to "Related projects" section

### ISSUE THREAD

**Issue by englishextra** [GoogleChrome/lighthouse#2438]
Since they have no free plan for Open Source projects, please mention that it is advertising.

**Comment by ebidel** [comment]
The intention of https://github.com/GoogleChrome/lighthouse#lighthouse-integrations is to highlight early projects and tools that are using/adopting Lighthouse so developers can check them out if this wish.

**Comment by englishextra** [comment]
@ebidel That's what I am saying: 

You can add that in README.md:

```
It gives a place where developers can check out how the tool is being used, for instance, see how Calibre project uses Lighthouse
```
That  way it would be nicer.

**Comment by ebidel** [comment]
Sure thing. We can add a blurb if it helps clarify what that section is all about.

**Comment by englishextra** [comment]
@ebidel thanks a lot
