### ISSUE TITLE
Didn't Send Any Data - HTTP

### ISSUE THREAD

**Issue by homerjonathan** [GoogleChrome/lighthouse#2439]
My application must work over https://, thus on my test platform I only have that service running without an unsecure http://.  When testing I get an error message and the testing stops.

 **This page isn’t working**

 _myserver didn’t send any data.
 ERR_EMPTY_RESPONSE_

Whilst I understand that perhaps it may be unconventional not having an unsecure server that responds, shouldn't the lighthouse test scripts register this and continue testing?

**Comment by ebidel** [comment]
Is this from the CLI or extension?  Related: https://github.com/GoogleChrome/lighthouse/issues/1217, https://github.com/GoogleChrome/lighthouse/issues/1978?

**Comment by homerjonathan** [comment]
Using the extension.

**Comment by wardpeet** [comment]
Pretty sure it's #1978

**Comment by homerjonathan** [comment]
Agreed
