### ISSUE TITLE
Travis build takes a while

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2440]
We can probably wittle it back down a few minutes without too much work.

I opened a completed [build](https://travis-ci.org/GoogleChrome/lighthouse/jobs/239649108) and ran this:

```js
results = $$('span.duration').map(e => {
    var dur = parseFloat(e.textContent);
    var cmd = e.nextElementSibling.textContent;
    return { dur, cmd };
}).sort((a,b) =>  b.dur - a.dur)

console.table(results)
```

And we get 

![image](https://cloud.githubusercontent.com/assets/39191/26796060/d7b00a7c-49dc-11e7-94a4-2e38a01458a9.png)

-------

here's my personal assessment of these... going in descending order...

* 200 seconds -- `yarn smoke` 
  * we use the default 3-pass config on most of our tests in here. it looks like we could feed a custom config to most of these (like the DBW tests) and hopefully cut it to down to 1 or 2 passes.
* 101 seconds -- `yarn build-all` 
  * the paralelltasks PR was concocted mostly for this. should drop it considerably
* 90 seconds -- `yarn smokehouse`
  * nothing stands out to me. we test 4 diff sites and assert 7-8 audits each time. it's possible our config & assertions aren't matching up for maximum speed
* 59 seconds -- `yarn compile-devtools`
  * a whole minute to do this!  No obvious fixes here unless the travis cache would help. 
* 48 seconds -- "change detected" aka travis caching
  * it's detecting a change in node_modules thanks to the `compile-devtools` work.  We could either move these checkouts out of node_modules or `rm -rf` them after the task.  Fixing this means our node_modules should be the same each run so cache would be happy.
* 44s -- `yarn unit`
  * nothing immediate unless we want to run the core tests parallel against the others
* 32s -- `yarn install-all`
  * paralleltasks PR helps
* 32s -- `yarn coveralls` 
  * a few options here, but one is not running coveralls on every build on every PR. 
* 26s -- `yarn closure`
  * eh
* 71s -- everything else

**Comment by wardpeet** [comment]
@paulirish I can take this if you like

**Comment by paulirish** [comment]
Ya that'd be awesome. Also Patrick thinks the `sudo: true` adds a few
minutes as well.

**Comment by stramel** [comment]
@paulirish @wardpeet Can any of this stuff be run in parallel using a build matrix? https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

Like installing, building, and testing each part in parallel.

- launcher
- cli
- viewer
- core

Then running the rest sequentially?

**Comment by wardpeet** [comment]
I don't believe they have to @stramel, thanks I'll look into it.

**Comment by wardpeet** [comment]
I believe this are all the tasks for now:

- [ ] Run master on node 6,7,8
- [ ] Run PRs on just node 6. 3 concurrent.
- [ ] Share cache between build stages to speedup the tests (using cloud storage). Get shared across 3 concurrent workers.
- [ ] Speedup smoketests (only run the audits that are necessary)
- [ ] compile devtools only on one node env.

**Comment by wardpeet** [comment]
i'll give it some extra loving this week :)
