### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by tomi-vanek** [GoogleChrome/lighthouse#2457]
**Lighthouse Version**: 2.1.0
**Chrome Version**: 58.0.3029.110
**Initial URL**: http://192.168.99.100/
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9893:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)
```

**Comment by brendankenny** [comment]
hmm, #2279 may not have worked

**Comment by patrickhulce** [comment]
noooo :( 

@tomi-vanek since there you've run into this a couple times is there anything in particular that's interesting about the way you ran lighthouse?

**Comment by tomi-vanek** [comment]
Just wanted to give a try after watching a video from Google IO… without success. I have MacOS X 10.12.5, runns on Chrome Version 58.0.3029.110 (64-bit).

Machine is heavily overloaded - developing system with ~ 10 - 15 dockers running in Kubernetes, the machine is overheated and noisy like an old Windows machine, with 100% memory usage.. I used Lighthouse plugin in Chrome (least effort path :-), not the CLI version with Node (that would be the logical next step).

tomi


On 7 Jun 2017, at 18:57, Patrick Hulce <notifications@github.com> wrote:

noooo :(

@tomi-vanek <https://github.com/tomi-vanek> since there you've run into this a couple times is there anything in particular that's interesting about the way you ran lighthouse?

**Comment by patrickhulce** [comment]
Thanks for the additional info @tomi-vanek! We're goin' to fold this in to #1091 since it seems to be an internal Chrome state issue.
