### ISSUE TITLE
Unable to load the page: timeout reached - Server misconfigured

### ISSUE THREAD

**Issue by lungare** [GoogleChrome/lighthouse#2459]
**Initial URL**: https://mysite.mwhtools.com/mySiteApp/
This is in the new audit tool and all the options are checked

**Comment by patrickhulce** [comment]
thanks for the report @lungare! this looks like another case of #1978, let's pick up the conversation over there

**Comment by patrickhulce** [comment]
Wait, nevermind that seems to be unrelated my machine just wouldn't connect to your http site for some reason, is it possible you're having intermittent server issues?

**Comment by patrickhulce** [comment]
closing in favor of #2784
