### ISSUE TITLE
ECONNREFUSED When launching multiple Chrome instances

### ISSUE THREAD

**Issue by LucianoGanga** [GoogleChrome/lighthouse#2462]
Hello! 
I don't know why, but when I try to execute multiple instances of Chrome in a Linux env, I get this error: 

```
[ERROR] connect ECONNREFUSED 127.0.0.1:39537
at Object.exports._errnoException (util.js:1050:11)
at exports._exceptionWithHostPort (util.js:1073:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
```
I've been trying to find more information about this, but I don't know where to start from. 

Any idea about what may be the problem?

**Comment by patrickhulce** [comment]
How are you launching and consuming chrome? Lighthouse as a node module? `chrome-launcher` and your own connection to Chrome?

If you're using the latest chrome-launcher module, it should be [waiting until the port is available](https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/chrome-launcher.ts#L239) but you'll have to make sure you're awaiting for the promise resolution before connecting.

**Comment by LucianoGanga** [comment]
Thanks for your answer Patrick! 

I'm using the NPM version of lighthouse 2.0.0. 

Then, I'm launching chrome here: 
https://github.com/LucianoGanga/simple-headless-chrome/blob/beta/lib/browser.js#L149

Then I connect to that instance here: 
https://github.com/LucianoGanga/simple-headless-chrome/blob/beta/lib/browser.js#L183

(I use "Chrome Remote Interface" for that: https://github.com/cyrus-and/chrome-remote-interface)

**Comment by ezesculli** [comment]
So far, It appears to be an specific Linux problem (because it works fine in our macs, but not on our servers):

We're basically reproducing this on Linux when:

```
const chromeInstance = require('lighthouse/chrome-launcher')
chromeOptions = {
    port: 0,
    autoSelectChrome: true, // False to manually select which Chrome install.
    additionalFlags: ['--disable-gpu', '--headless', '--enable-logging']
  }

chromeInstance.launch(chromeOptions)
// Instance 1 -> Chrome Launched succesfully

chromeInstance.launch(chromeOptions)
// Instance 2 -> Chrome Launched succesfully

chromeInstance.launch(chromeOptions)
// Instance 3 -> Error: connect ECONNREFUSED 127.0.0.1:60520

chromeInstance.launch(chromeOptions)
// Instance 4 -> Error: connect ECONNREFUSED 127.0.0.1:40814
```

Can you help us to reproduce if you're getting the same error on your Linux env?

**Comment by ebidel** [comment]
@ezesculli it looks like you're using some old flags: `autoSelectChrome ` and `additionalFlags`.  

`autoSelectChrome` is gone in 2.0 and `additionalFlags` -> `chromeFlags`.

Can you try this:

```javascript
const CDP = require('chrome-remote-interface');
const chromeLauncher = require('lighthouse/chrome-launcher/chrome-launcher');

// Turn on logging for chromeLauncher.
// const log = require('lighthouse/lighthouse-core/lib/log');
// log.setLevel('info');

async function launchChrome(headless = true) {
  const chrome = await chromeLauncher.launch({
    // port: 9222, // uncomment to force a port of your choice.
    chromeFlags: [
      '--disable-gpu',
      '--enable-logging',
      headless ? '--headless' : '',
    ]
  });
  return chrome;
}

launchChrome(true).then(async chrome => {
  // Make sure to use the same debugging port that chromeLauncher used/selected.
  CDP({port: chrome.port}, DTP => {
     ...
  });
});
```

**Comment by LucianoGanga** [comment]
Thanks @ebidel ! 

We updated those parameters, but still getting the ECONNREFUSED error:

```
{ 
    Error: connect ECONNREFUSED 127.0.0.1:58333
        at Object.exports._errnoException (util.js:1050:11)
        at exports._exceptionWithHostPort (util.js:1073:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 58333 
}
```

**Comment by ebidel** [comment]
Hmm, ok. I'll have to test on Linux. Do you think you could post a snippet of code that repros the problem?

**Comment by LucianoGanga** [comment]
@ebidel I think that with the code that @ezesculli posted before it's enough, but I've launched a EC2 instance in AWS to test this (which gives me the ECONNREFUSED error even in the first attempt of launching a chrome instance). 

If you want, I can privately send you the access credentials so you can test it there.

**Comment by LucianoGanga** [comment]
I don't know if this helps, but on Linux I ran the code you gave us: 

```js
const CDP = require('chrome-remote-interface');
const chromeLauncher = require('lighthouse/chrome-launcher/chrome-launcher');

// Turn on logging for chromeLauncher.
const log = require('lighthouse/lighthouse-core/lib/log');
log.setLevel('info');

async function launchChrome(headless = true) {
  const chrome = await chromeLauncher.launch({
    // port: 9222, // uncomment to force a port of your choice.
    chromeFlags: [
      '--disable-gpu',
      '--enable-logging',
      headless ? '--headless' : '',
    ]
  });
  return chrome;
}

```

and then ran this several times: 
```js

launchChrome(true).then(async chrome => {
  // Make sure to use the same debugging port that chromeLauncher used/selected.
  CDP({port: chrome.port}, DTP => {
     console.log('DTP', DTP.port)
  });
});
```

and after a few runs, I've got this: 
```
> (node:1963) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by patrickhulce** [comment]
@LucianoGanga that EventEmitter leak is a known leak with the SIGINT handling (you can flip the `handleSIGINT` option to false to disable since you likely don't need it anyway), but shouldn't impact the CONNREFUSED you're seeing

I'm assuming with these cases that you're observing a significant delay while it waits for the port to be available and it finally fails sometime later? Or is it immediately returning CONNREFUSED (meaning that Chrome Launcher thinks it was able to connect but CRI failed to connect)?

**Comment by LucianoGanga** [comment]
@patrickhulce I just tested it again, It takes between 10 and 20 seconds since the chromeLauncher is excecuted until I get the error. 

I made some new tests in a new ubuntu server (instead of using the Heroku instance) and it fails after 10/15 new instances. In my mac, I can run it more than 30 times without any problem.

**Comment by ebidel** [comment]
@patrickhulce I lied. Wasn't able to take a look today and I'm gone tomorrow for a wedding. Feel free to test if you get a chance. Otherwise, I can get to it next week.

**Comment by LucianoGanga** [comment]
We added more and better hardware and the problem seems to be solved... I think there's a OS limitation that prevents the instances from opening ports on time, or something around that (I'm not an expert in OS). 

If you want, we can close this issue.

**Comment by patrickhulce** [comment]
Thanks for circling back around to let us know! That certainly would explain my difficulty reproing on a 64-core linux box :) 

Feel free to reach out again if you run into new issues!

**Comment by LucianoGanga** [comment]
Hi @patrickhulce !

We're having the issue again, but this time I can't even run one instance of chrome. 

This is the code: 

```js
const chromeLauncher = require('chrome-launcher');

chromeOptions = {
        port: 0,
        autoSelectChrome: true, // False to manually select which Chrome install.
        additionalFlags: ["--disable-gpu", "--headless", "--enable-logging"]
}

// Launch chrome
chromeLauncher.launch(chromeOptions)
```

Which gives me this error: 

```
(node:1223) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:36640
(node:1223) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: connect ECONNREFUSED 127.0.0.1:36763
```

Any ideas? 

The error seems to be happening here: 
```
Error code: ECONNREFUSED { Error: connect ECONNREFUSED 127.0.0.1:36640
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
From previous event:
    at Launcher.isDebuggerReady (/home/ubuntu/sirena/themisto/node_modules/chrome-launcher/chrome-launcher.js:153:16)
    at poll (/home/ubuntu/sirena/themisto/node_modules/chrome-launcher/chrome-launcher.js:178:26)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 36640 }
``` 

Any ideas? 

Thanks!
Luciano

**Comment by paulirish** [comment]
I  am able to reproduce this. here's the steps

### install travis node-js image 

```sh
docker run --name travis-debug -dit travisci/ci-garnet:packer-1496954857 /sbin/init
docker exec -it travis-debug bash -l
```

### setup things within the travis shell:

```sh
su - travis
mkdir tempproj && cd tempproj
yarn init
yarn add chrome-launcher
```
then create an index.js with the code from @LucianoGanga's comment above. and run:

    node index.js

**Comment by paulirish** [comment]
@LucianoGanga 

you have an error in your code when you upgraded to latest chrome-launcher.

heres the launch options you want:

```js
chromeOptions = {
        chromeFlags: ["--disable-gpu", "--headless", "--enable-logging"] 
}
```

you may also want `--no-sandbox` in there as well.. I just ran into requiring that.

**Comment by LucianoGanga** [comment]
@paulirish I feel really lame now... Sorry for the trouble!

The issue wasn't the name of the properties (I had them right in my production code), but the thing was that the "--headless" flag depended on a variable that was set to false. 

It didn't cause any kind of problem in my pc, but it did in Linux through command line (still don't know why)

I'm really sorry for this, really! You can close this issue.

Cheers, 
Luciano

PS: at least now you know the trick to get an extra piece of stack in an error ! :P

**Comment by joelgriffith** [comment]
I'm getting some reports in Navalia with similar error types. I haven't been able to repro myself, but I'll post in this issue if I uncover something 🐟

**Comment by svewag** [comment]
@LucianoGanga, you said after upgrading your hardware the problem was gone.
Can you remember what exactly made the point?

We are running into the exact same problems when doing more than four lighthouse runs in parallel.

```
(node:28) UnhandledPromiseRejectionWarning: Error: not opened
    at WebSocket.send (/builds/xxx/xxx-4.0/node_modules/lighthouse/node_modules/ws/lib/WebSocket.js:344:18)
    at CriConnection.sendRawMessage (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:157:14)
    at CriConnection.sendCommand (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:55:10)
    at Driver.sendCommand (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/driver.js:205:29)
    at Promise (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/driver.js:870:19)
    at new Promise (<anonymous>)
    at Driver.endTrace (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/driver.js:862:12)
    at pass.then._ (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:274:23)
    at <anonymous>
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:43219
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:395:9)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

Thank you for your feedback.

**Comment by ldllidonglin** [comment]
> @LucianoGanga, you said after upgrading your hardware the problem was gone.
> Can you remember what exactly made the point?
> 
> We are running into the exact same problems when doing more than four lighthouse runs in parallel.
> 
> ```
> (node:28) UnhandledPromiseRejectionWarning: Error: not opened
>     at WebSocket.send (/builds/xxx/xxx-4.0/node_modules/lighthouse/node_modules/ws/lib/WebSocket.js:344:18)
>     at CriConnection.sendRawMessage (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:157:14)
>     at CriConnection.sendCommand (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:55:10)
>     at Driver.sendCommand (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/driver.js:205:29)
>     at Promise (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/driver.js:870:19)
>     at new Promise (<anonymous>)
>     at Driver.endTrace (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/driver.js:862:12)
>     at pass.then._ (/builds/xxx/xxx-4.0/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:274:23)
>     at <anonymous>
> (node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
> (node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> events.js:165
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: connect ECONNREFUSED 127.0.0.1:43219
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
> Emitted 'error' event at:
>     at Socket.socketErrorListener (_http_client.js:395:9)
>     at Socket.emit (events.js:180:13)
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at process._tickCallback (internal/process/next_tick.js:178:19)
> ```
> 
> Thank you for your feedback.

I also get same problems
