### ISSUE TITLE
Unable to load the page: timeout reached - HSTS

### ISSUE THREAD

**Issue by tigerhawkvok** [GoogleChrome/lighthouse#2465]
**Initial URL**: https://amphibiandisease.org/dashboard.php
**Chrome Version**: 60.0.3112.21
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@946a8fb2f25915a1ec81b1b4fe2d51a00cae4607/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@946a8fb2f25915a1ec81b1b4fe2d51a00cae4607/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

It starts to work fine, but then toward the end (after getting a trace) it tries to load the page again and immediately craps out.

Possibly related to #1978, though the site is hosted with HSTS ( https://www.ssllabs.com/ssltest/analyze.html?d=amphibiandisease.org ) and I'd imagine this is seamless...

Another [HSTS site](https://www.ssllabs.com/ssltest/analyze.html?d=papayapythons.com) this fails on is [papayapythons.com](https://papayapythons.com/)

**Comment by brendankenny** [comment]
I'm not seeing a problem in Canary (Chrome 61) or when using the extension. Are you logged in or have some other sort of saved state that may contribute to what's going on?

**Comment by tigerhawkvok** [comment]
@brendankenny I wasn't, but replicated the issue in an extension-free incognito window anyway

Pre-fail: 

![image](https://user-images.githubusercontent.com/165937/26904954-73102642-4b99-11e7-9d92-9c3d1e632484.png)

Post-fail:

![image](https://user-images.githubusercontent.com/165937/26904967-7d59ba0a-4b99-11e7-9796-de0d9554fa1d.png)

I updated the original post while you commented to say:

>Possibly related to #1978, though the site is hosted with HSTS ( https://www.ssllabs.com/ssltest/analyze.html?d=amphibiandisease.org ) and I'd imagine this is seamless...
>
>Another [HSTS site](https://www.ssllabs.com/ssltest/analyze.html?d=papayapythons.com) this fails on is [papayapythons.com](https://papayapythons.com/)

**Comment by paulirish** [comment]
Just tested this on CLI and devtools. No problems, no exceptions. I believe this is fixed.
