### ISSUE TITLE
role=feed is marked as invalid

### ISSUE THREAD

**Issue by derekjohnson** [GoogleChrome/lighthouse#2468]
`role=feed` was introduced in ARIA 1.1 but is marked invalid in Lighthouse.

See https://www.w3.org/TR/wai-aria-1.1/#feed and http://www.ssbbartgroup.com/blog/differences-aria-1-0-1-1-additions-role/

**Comment by ebidel** [comment]
The a11y audits use the https://github.com/dequelabs/axe-core lib for auditing. Would you mind upstreaming this issue?

**Comment by derekjohnson** [comment]
Done, thanks :)
