### ISSUE TITLE
Persistent 'Audit error: The main thread was busy for the entire trace recording.' when running via webpagetest

### ISSUE THREAD

**Issue by chrisdwheatley** [GoogleChrome/lighthouse#2475]
As mentioned in #2434 I'm seeing an issue in Lighthouse when running via webpagetest that I'm hoping someone can help investigate.

Here's what I'm seeing https://www.webpagetest.org/result/170608_KH_4a8be412cf0ef89d56e3cb13a8eed676/ (this is running as Mobile - Faster 3G from https://www.webpagetest.org/easy)

Here's a similar test but using Mobile - Emerging Markets where the waterfall looks pretty similar but the Lighthouse results don't fail as much https://www.webpagetest.org/result/170607_PW_1d454612c736a65ddff058cf16b8842e/

The website is https://nextjs-hn.chrisdwheatley.com/, when running Lighthouse via the Chrome extension or in the devtools in Chrome Canary I'm unable to replicate the issue.

If you have any thoughts as to what's causing this issue it'd be much appreciated.

**Comment by chrisdwheatley** [comment]
Oh, looks like this is possibly taken care of in https://github.com/GoogleChrome/lighthouse/pull/2473.

**Comment by patrickhulce** [comment]
Thanks for filing the separate issue @chrisdwheatley! #2473 should indeed address this type of problem :)
