### ISSUE TITLE
noopener audit should also allow `noreferrer`

### ISSUE THREAD

**Issue by ngyikp** [GoogleChrome/lighthouse#2482]
Failing HTML:
```html
<a href="https://example.com" target="_blank" rel="noreferrer">text</a>
```

According to https://mathiasbynens.github.io/rel-noopener/ , using `noreferrer` by itself fixes the vulnerability too.

If `noreferrer` is enough, then wouldn't putting `noopener` next to it would be redundant?

**Comment by patrickhulce** [comment]
yep that's right good catch @ngyikp!

**Comment by ripsonowy** [comment]
not only noreferrer but also other, for example: nofollow, external etc...

**Comment by patrickhulce** [comment]
@ripsonowy I don't believe nofollow and external solve the performance and hijacking vulnerabilities that are targeted by this audit. Could you elaborate why you believe those also solve the issue?
