### ISSUE TITLE
Lighthouse unable to connect to chrome

### ISSUE THREAD

**Issue by kchoi01** [GoogleChrome/lighthouse#2490]
I am trying to run Lighthouse with headless Chrome on Ubuntu.
Chrome 59.0.3071.86
Lighthouse 2.1.0
Ubuntu 14.04

The command line is 
lighthouse --verbose --chrome-flags="--headless --disable-gpu --remote-debugging-port=9222" http://www.some.site

The verbose output shows that a chrome instance is successfully launched. Running the ps and lsof commands also shows that the chrome instance is listening to port 9222. 

Lighthouse is still unable to connect to chrome. It used to work when I was running an older version of lighthouse. Not sure how to resolve this.

**Comment by ebidel** [comment]
Try the `port` flag:

```
lighthouse --verbose --port=9222 --chrome-flags="--headless --disable-gpu" http://www.some.site
```

That should get handed off to the new ChromeLauncher in LH 2.0.0.

https://github.com/GoogleChrome/lighthouse#cli-options
