### ISSUE TITLE
Audit error: Required Accessibility gatherer encountered an error: j.split is not a function

### ISSUE THREAD

**Issue by richgps** [GoogleChrome/lighthouse#2501]
I'm getting a Zero on the Accessibility audit as it's throwing the following error for each check:

`Audit error: Required Accessibility gatherer encountered an error: j.split is not a function`

It's currently a non-public URL, so not able to share URL

Thanks!

**Comment by ev1stensberg** [comment]
Would you be able to show an stack trace of some sort?

**Comment by patrickhulce** [comment]
We don't use `.split` in our own code for that gatherer so this is likely an `axe-core` bug of some sort. Could you try runny just [axe](https://github.com/dequelabs/axe-core) on your site and see if that produces a more readable error that you could file with them?

**Comment by richgps** [comment]
Thanks - the same error is thrown in `axe-core`!

I have submitted the issue here: https://github.com/dequelabs/axe-core/issues/361

**Comment by brendankenny** [comment]
based on discussion in https://github.com/dequelabs/axe-core/issues/361, closing here as well
