### ISSUE TITLE
Performance inconsistent

### ISSUE THREAD

**Issue by gbowman2013** [GoogleChrome/lighthouse#2506]
Multiple tests return performance scores with wide variations in the same environment. I have attached JSON files (renamed .txt)  demonstrating the issue: 

1) Overall performance of 39 (ccserving.com_2017-06-15_08-04-34.json)
[ccserving.com_2017-06-15_08-18-20.json.txt](https://github.com/GoogleChrome/lighthouse/files/1077739/ccserving.com_2017-06-15_08-18-20.json.txt)

2) Overall performance score of 73 (ccserving.com_2017-06-15_08-18-20.json)
[ccserving.com_2017-06-15_08-04-34.json.txt](https://github.com/GoogleChrome/lighthouse/files/1077743/ccserving.com_2017-06-15_08-04-34.json.txt)

Some fix or explanation is needed.

**Comment by patrickhulce** [comment]
@gbowman2013 that first load looks like it was significantly different from the second load (it looks like the run ended prematurely, TTCI failed to compute which results in an automatic 0 and EIL is incredibly high suggesting there was not very much idle time after the first paint).

We'd really need the traces demonstrating the failure (the 39 in your example) to say more. You can collect a trace by running the CLI with `--save-assets` and uploading the .trace.json file. I've run Lighthouse several times against that URL and consistently get scores ~70.

**Comment by patrickhulce** [comment]
Without more information we're going to go ahead and close this, but feel free to comment with the traces if you're still experiencing this!

**Comment by warmhug** [comment]
Maybe this problem still exists...
