### ISSUE TITLE
Suggestion: Don't check for url twice, move the check to entry in core

### ISSUE THREAD

**Issue by ev1stensberg** [GoogleChrome/lighthouse#2507]
Doing some digging and found this:

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/index.js#L32

and later this

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gather-runner.js#L323

Can we move the check to `lighthouse-core/index` instead?

**Comment by paulirish** [comment]
the comment  in index points out the relationship there...  /index isn't used by the chrome extension or devtools build.

but perhaps it'd be fine to nuke the check in `/index` and keep the gather-runner one.

**Comment by ev1stensberg** [comment]
Gotcha, want me to send a PR?
