### ISSUE TITLE
Move download-chrome.sh to chrome-launcher and make easily callable

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#2510]
At one point we published the `download-chrome.sh` script with lighthouse that was handy for downstreamers to use when running in CI. It might be a nice feature of chrome-launcher to provide a similar mechanism to download/install chrome cross platform as well.

**Comment by busticated** [comment]
fwiw, it would be awesome to have something like https://github.com/Medium/phantomjs

using this, i simply add the `phantomjs-prebuilt` dependency to my package.json, `npm i` (w/ caching) in my CI env, and run tests. works great. would love to drop in a chrome-powered replacement.

**Comment by paulirish** [comment]
@busticated yeah true. we have no short term plans to make a production-ready `chrome-stable-prebuilt` npm package but we definitely see the value in it. 

If someone wants to start working on this, we'd be happy to see that!
