### ISSUE TITLE
Lighthouse won't load URLs on subdomains if the domain starts with a blocked pattern

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#2512]
Repro: Try running lighthouse against http://2015.cssconf.com.au/

Issue comes from our use of blockedUrlPatterns which [does not support full string matching](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/inspector/InspectorNetworkAgent.cpp?type=cs&l=107)

We can workaround by disabling the URL pattern blocking if the main URL matches any of the patterns

**Comment by benschwarz** [comment]
I'd love to see this end up being an improvement to blockedUrlPatterns 😢

**Comment by patrickhulce** [comment]
@benschwarz FYI I believe the current recommendation for complicated request blocking is to use [request interception](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-enableRequestInterception)

**Comment by paulirish** [comment]
it's possible (even likely) devtools team kills the `setBlockedURLs` protocol method completely in favor of adopting request interception.

**Comment by benschwarz** [comment]
Ah! That's even better. Great.

**Comment by patrickhulce** [comment]
still awaiting network request interception fix https://bugs.chromium.org/p/chromium/issues/detail?id=764505

this will be fixed by fixing #3516
