### ISSUE TITLE
Perceptual speed index not working well for animated content

### ISSUE THREAD

**Issue by wibblymat** [GoogleChrome/lighthouse#2514]
I've written an app that, on first load, shows a full screen video that is being fed by getUserMedia.

If I stick something over my camera I get a good score for perceptual speed index (1.3s), whereas if I run LH while the camera is uncovered and I'm waving my hands about, I get bad scores (4.7s is my worst)

Clearly the test is not measuring anything useful in this case and I wonder if it can be improved.

**Comment by ebidel** [comment]
Is this a flaw of the metric? I've seen similar issues on sites that have a continuous animation in the background (or a video). The I/O 2016 is an example where [SI gets pushed out](https://www.webpagetest.org/video/compare.php?tests=170616_HK_595b68590e189a63b214829b8663ae8a-r:1-c:0) b/c the animation keeps changing. WPT never sees the page as "visually complete".

**Comment by wibblymat** [comment]
Yes, I think it's a flaw in the module that is being used. I *think* it screenshots the page at intervals and waits for the difference between consecutive screenshots to be small.

**Comment by patrickhulce** [comment]
Yes this is a critical flaw of all metrics (SI and PSI) using a single target frame as the "ideal" or "idle" state and judging progress toward that frame. There are some other critical problems with PSI discussed over in speedline like https://github.com/paulirish/speedline/issues/52 and https://github.com/paulirish/speedline/issues/50. Plenty of work to do here :)

**Comment by ebidel** [comment]
Should we just close this issue? The problem lies in the metric and no LH :)

**Comment by brendankenny** [comment]
I know @patrickhulce wants to keep investigating improvements, though he can comment on timescale for that. It would be nice to have a tracking bug over here, though it may make sense to open a new one with clearer title and summary of current state and what could be improved.

**Comment by patrickhulce** [comment]
Yeah I'm not sure if any immediate progress well be made on this specific problem though since speed index is so well established as a thing at this point, at best we'll come up with a variant in a new metric. It might be fine to leave this open to coalesce anyone filing issues like #2607 :)

**Comment by brendankenny** [comment]
> Should we just close this issue? The problem lies in the metric and not LH :)

SG :)

> It would be nice to have a tracking bug over here

Sounds terrible, who writes things like this.
