### ISSUE TITLE
Audit bug: Blob urls being flagged as insecure

### ISSUE THREAD

**Issue by RandomDude777** [GoogleChrome/lighthouse#2523]
Bit of a difficult one to explain this one.. When a read from it shows as insecure in the audit, I don't seem to be able to properly explain this as the blob is secure.... 

https://i.imgur.com/0sP5s1H.png

**Comment by ebidel** [comment]
Interesting. This should have been addressed in https://github.com/GoogleChrome/lighthouse/commit/0d0e93f3458488a5155ea0d5b4bf280f4b0f1255. 

What version of LH are you using?

**Comment by RandomDude777** [comment]
Latest, I just updated 2 hours ago, It's also confusing me, the blob is read over TLS as I've confirmed manually. I post the blob for later use.

https://i.imgur.com/YiTsQsz.png

**Comment by kamleshchandnani** [comment]
I am also facing the same issue. Using LH CLI V2.1.0.

**Comment by ebidel** [comment]
Found it!

**Comment by RandomDude777** [comment]
Kickass! Awesome work guys!

**Comment by kamleshchandnani** [comment]
when this fix will be released as part of CLI/chrome extension?

**Comment by paulirish** [comment]
we'll get a new release out by tomorrow.
but you should be able to do a `npm install -g GoogleChrome/lighthouse` in the meantime for CLI.
and building extension ain't too bad. :)

**Comment by kamleshchandnani** [comment]
@paulirish Yup already doing that :) . This is just for the sake for our marketing team, because if they run lighthouse with the extension then our score will not be same as compared to the build on my system.

**Comment by paulirish** [comment]
@kamleshchandnani new extension was shipped last friday. 2.2.1

**Comment by kamleshchandnani** [comment]
@paulirish 
Oh that's great👍. Thanks a ton! 😊
