### ISSUE TITLE
Extension Error: Cannot access contents of the page. Extension manifest must 

### ISSUE THREAD

**Issue by pgsgoossens** [GoogleChrome/lighthouse#2525]
**Lighthouse Version**: 2.1.0
**Chrome Version**: 61.0.3132.0
**Initial URL**: view-source:chrome-extension://akdgnmcogleenhbclghghlkkdndkjdjc/linkinfo.html?id=e8b97e2a876941dc590bce68bd81e921
**Error Message**: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
**Stack Trace**:
```
Error: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
    at Object.chrome.debugger.attach._ [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9837:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by wardpeet** [comment]
@pgsgoossens can you tell us how you got to this url:
`view-source:chrome-extension://akdgnmcogleenhbclghghlkkdndkjdjc/linkinfo.html?id=e8b97e2a876941dc590bce68bd81e921`.

We only support real urls.
