### ISSUE TITLE
Release logger as its own module

### ISSUE THREAD

**Issue by westy92** [GoogleChrome/lighthouse#2526]
As mentioned in https://github.com/GoogleChrome/lighthouse/pull/2358#issue-231228347, "I vote that we pull out logger into a standalone module to consume to in both lighthouse and in launcher."

Currently `chrome-launcher` is pulling in the entirety of `lighthouse` just to use the logger.

The dependency is [here](https://github.com/GoogleChrome/lighthouse/blob/c20b28500d692393b8c4c32542c4471921a0fe61/chrome-launcher/chrome-launcher.ts#L16).

**Comment by paulirish** [comment]
@westy92 yah that sounds awesome.  Do you want to help with this? 

We can pull it to a top level folder.  And a package.json with the name 'lighthouse-log'. 
May not be too bad, actually.

**Comment by paulirish** [comment]
`html-pdf-chrome` looks great btw!

**Comment by westy92** [comment]
@paulirish I'd be able to do all the things you described, but I would need help publishing it to npm.
Thanks!

**Comment by wardpeet** [comment]
how do we feel about creating a lerna repo? Creating a monolith but seperate npm packages?

**Comment by westy92** [comment]
@wardpeet I don't have much experience with lerna, but that's what the [material components web team](https://github.com/material-components/material-components-web/blob/master/lerna.json) is using.

**Comment by paulirish** [comment]
`chrome-launcher@0.2.0` shipped without LH as a dep.

**Comment by westy92** [comment]
Thank you very much!
