### ISSUE TITLE
Lighthouse does not finish

### ISSUE THREAD

**Issue by miquelmasrieramrf** [GoogleChrome/lighthouse#2532]
* **Lighthouse Version**: 2.1.0
* **Chrome version**: 59.0.3071.104
* **url**: https://www.davidemaggio.it/
* **Error message**: none
* **Stack trace**: none

lighthouse is not triggering any error, but it does not finish.
using CLI + verbose it gets stuck at `Runtime.evaluate +1ms {"expression":"(function wrapInNativePromise`

**Comment by ebidel** [comment]
Couple of things I noticed about the page:
- large number of network requests: ~300
- huge number of DOM nodes: 11,180 to be precise. Lighthouse spends a lot time in evaluating getEventListeners for `ExternalAnchorsUseRelNoopenerAudit` and other related audits.

Added this site to the list of sites that give LH issues: https://github.com/GoogleChrome/lighthouse/issues/2293

**Comment by miquelmasrieramrf** [comment]
there are a lot of nodes but we are using shadow DOM

**Comment by ebidel** [comment]
It's still worth taking a look at lazy loading markup that you don't need. The browser has to parse, layout, and perform style calculations on all of that markup.

From https://www.webcomponents.org/community/articles/web-components-best-practices:

> Don't put too much in Shadow DOM: Shadow DOM allows you to stuff a bunch of complex junk out of sight. However, that's not an excuse to have as many DOM elements as you want in your shadow, as more elements will still lead to worse performance. In addition, try to keep your configuration and state visible by keeping anything semantic exposed in the logical DOM. Cruft goes in the Shadow; semantic stuff doesn't.

**Comment by miquelmasrieramrf** [comment]
Thanks a lot for checking it, and excuse me, my previous comment was not useful at all.

For the page that is giving the problem (https://www.davidemaggio.it) we are using AMP shadow DOM.
For a version of it that does not use it (https://www.davidemaggio.it/?marfeeltn=newspaperMarfeelAds) we have the same number of requests and DOM nodes, but lighthouse works fine.

So you think that using amp shadow DOM intensively might be an problem for lighthouse audits?
We are using lighthouse in a lot of sites made by my company and so far, this is the only case where it seems to be some kind of issue.
