### ISSUE TITLE
Gulp recipe does not support lighthouse 2.0

### ISSUE THREAD

**Issue by kevinfarrugia** [GoogleChrome/lighthouse#2533]
Following the changes to Lighthouse 2.0, the gulp recipe (`/docs/recipes/gulp`) is outdated.

Created a fork with the required changes: https://github.com/IncredibleWeb/lighthouse/tree/feature/update_gulp_recipe_lighthouse_2.0

**Comment by ebidel** [comment]
Good catch @kevinfarrugia. Interested in submitting a PR?

**Comment by kevinfarrugia** [comment]
Submitted https://github.com/GoogleChrome/lighthouse/pull/2537
