### ISSUE TITLE
Viewer fails to load JSON

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/lighthouse#2534]
The [Lighthouse viewer](https://googlechrome.github.io/lighthouse/viewer/) fails to load the attached JSON (generated via Chrome Canary).

The actual error is also not really visible.

![screen shot 2017-06-19 at 4 02 03 pm](https://user-images.githubusercontent.com/51244/27291729-07897ba2-5509-11e7-8d73-b2cf1f52d98d.png)

[weather.com-20170619T135231.json.txt](https://github.com/GoogleChrome/lighthouse/files/1085384/weather.com-20170619T135231.json.txt)

**Comment by ebidel** [comment]
Viewer 2.0 is tracking here: https://github.com/GoogleChrome/lighthouse/issues/2338
