### ISSUE TITLE
Suggestion: JavaScript Start-up Performance.

### ISSUE THREAD

**Issue by mixed** [GoogleChrome/lighthouse#2535]
Recently I have read a [awesome article](https://medium.com/reloading/javascript-start-up-performance-69200f43b201) of @addyosmani that improve page loading speed. This article suggest to some practices.
- **Heavy script should be running in Script Streaming thread**
  - I could find scripts that runs on Script Streaming thread in tracing data.
- **Heavy script should split unused code**
  - I could make guide that analyze unused code using code coverage.
- **Use parens hack for pre-parsing**
  - I could make guide that check to need parens hack using [optimize-js](https://github.com/nolanlawson/optimize-js)

If you interest to this feature that I could send PR.

**Comment by patrickhulce** [comment]
@mixed I'm already on JS code coverage which had a PR open a few months ago but was sidelined, should be coming soon :)

script streaming thread is a good boost, but as addy mentions there's not really an action to take there, so I'm not sure what our advice would be if we don't find it on the script streamer thread :/

RE: parens hack, if we can find a way to quantify the savings to them, then I'd love to present it as a perf hint audit (similar to the bloated images or compress text audits), but I'd want to avoid a simple pass/fail based on the lack of parens.

**Comment by mixed** [comment]
@patrickhulce 
Thank you for your response.

Ah.. I didn`t know you were working on code coverage. 👏

It only works in the script streaming thread if the size of the script is [over 30kb](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/bindings/core/v8/ScriptStreamer.cpp?dr=CSs&l=325). So in my opinion, if you show which scripts do not parse in the script streaming thread, the developer might think that the script streaming thread might handle it if it is an important script.

I think it would be helpful to show only the parens hack, but if you want more information, I would like to estimate the improved parse time based on the information in [link](https://medium.com/reloading/javascript-start-up-performance-69200f43b201). (For example, about 20%?)

![image](https://user-images.githubusercontent.com/22300/27386471-e4f6d5c0-56d0-11e7-80c7-301223606f7c.png)

rough design 😱

![image](https://user-images.githubusercontent.com/22300/27388366-3f5b6c88-56d6-11e7-86bb-04e3b1e71a65.png)

**Comment by paulirish** [comment]
@addyosmani can you merge what's in here into your bootup time issue?

**Comment by patrickhulce** [comment]
done
