### ISSUE TITLE
Check for Error before reporting

### ISSUE THREAD

**Issue by stramel** [GoogleChrome/lighthouse#2542]
The extension provides a way to report errors however it seems like a lot of duplicate errors are being logged. It would be cool to check for an existing error logged and possibly link to the existing error?

**Comment by paulirish** [comment]
Yah true. We're working on our bug triage process right now. :)

There should be less of these dupes these days.

**Comment by stramel** [comment]
@paulirish It would be nice to show a link to the issue if it exists similar to how Atom handles theirs.
