### ISSUE TITLE
Broken build: connect ECONNREFUSED

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2544]
I cleared the travis caches, which so far has revealed TWO bugs.

The first was fixed by changing our install command: #2543 
The second is this issue.

Any tests that rely on connecting to the browser appear to fail right now. Example build: https://travis-ci.org/GoogleChrome/lighthouse/jobs/244797088

Screenshotting the failures:
![image](https://user-images.githubusercontent.com/39191/27317350-9c644dfc-553a-11e7-8cc8-b688e97bbb16.png)
![image](https://user-images.githubusercontent.com/39191/27317355-a53cea24-553a-11e7-9c10-fa2e55a5500c.png)
![image](https://user-images.githubusercontent.com/39191/27317359-abf5381c-553a-11e7-8ee3-1d6a55c3ad44.png)

So far I'm in the blind on the fix. Ideas?

**Comment by paulirish** [comment]
@wardpeet [has been debugging](https://user-images.githubusercontent.com/39191/27348431-e402285a-55a8-11e7-9332-0b5537a4159f.png) this basically since I reported the bug.  **what a hero.**

He's been using the  travis-ci docker image  locally to debug.

I'm posting some of his debugging notes.

-------------

The first error encountered was this:
```sh
travis@4b833d423e4b:~/builds/GoogleChrome/lighthouse$ $(pwd)/chrome-linux/chrome

/home/travis/builds/GoogleChrome/lighthouse/chrome-linux/chrome: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 
`GLIBCXX_3.4.18' not found (required by /home/travis/builds/GoogleChrome/lighthouse/chrome-linux/chrome)`

/home/travis/builds/GoogleChrome/lighthouse/chrome-linux/chrome: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 
`GLIBCXX_3.4.19' not found (required by /home/travis/builds/GoogleChrome/lighthouse/chrome-linux/chrome)`
```

Ward fixed that via `sudo apt-get install libstdc++-4.9-dev`.

Second error was this:
```sh
/home/travis/builds/GoogleChrome/lighthouse/chrome-linux/chrome: 
undefined symbol: gdk_screen_get_monitor_scale_factor
```

This is only reproducible on latest chromium. Beta and stable chromium do not encounter this error.
Internet doesn't have much to say about this error.

Ward has got a reliable fix with https://github.com/GoogleChrome/lighthouse/pull/2547
We use Chrome stable (provided by [travis](https://docs.travis-ci.com/user/chrome)) and give xvfb some extra time to boot up.

**Comment by paulirish** [comment]
fixed by #2547. 🎉 🎉 🎉 🎉

**Comment by wardpeet** [comment]
Updated the comment to have
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
```

**Comment by patrickhulce** [comment]
awesome job hunting this down @wardpeet! also fixes #1480 :) are we just going to run into this problem when the current chrome hits stable though? is there a crbug tracking this?

**Comment by wardpeet** [comment]
It could be the way it's compiled? As chrome-stable is installed through a deb file and chromium through a zip file? Not sure what the difference is though. I don't believe we have a crbug yet.

about #1480 not sure it's considered close as we didn't really closed the discussion 😛

**Comment by paulirish** [comment]
> about #1480 not sure it's considered closed as we didn't really closed the discussion 😛

we closed the discussion of testing stable on travis. 
but in that issue you raised the idea of splitting the work in our travis matrix (i think). and doing different work (potentially with different chromes) on separate travis bots.  I think that's still open and worth considering yup!

**Comment by LucianoGanga** [comment]
I have this problem but when running on a Linux server. I'm installing Chrome with 
```
apt-get -y install chromium-browser
```

**Comment by LucianoGanga** [comment]
Here is more detail about the error: 

```
0|themisto | [ERROR] connect ECONNREFUSED 127.0.0.1:42049
0|themisto |
0|themisto |       at Object.exports._errnoException (util.js:1050:11)
0|themisto |       at exports._exceptionWithHostPort (util.js:1073:20)
0|themisto |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
0|themisto |   From previous event:
0|themisto |       at Launcher.isDebuggerReady (/home/ubuntu/sirena/themisto/node_modules/chrome-launcher/chrome-launcher.js:153:16)
0|themisto |       at poll (/home/ubuntu/sirena/themisto/node_modules/chrome-launcher/chrome-launcher.js:178:26)
0|themisto |       at runCallback (timers.js:672:20)
0|themisto |       at tryOnImmediate (timers.js:645:5)
0|themisto |       at processImmediate [as _immediateCallback] (timers.js:617:5)
0|themisto |   code: ECONNREFUSED
0|themisto |   errno: ECONNREFUSED
0|themisto |   syscall: connect
0|themisto |   address: 127.0.0.1
0|themisto |   port: 42049
0|themisto |   __error_callsites:
0|themisto |     - {}
0|themisto |     - {}
0|themisto |     - {}
0|themisto |   __stackCleaned__: true
0|themisto |   httpStatusMsg: Internal Server Error
0|themisto |   httpStatusCode: 500
0|themisto | [ERROR] connect ECONNREFUSED 127.0.0.1:33468
0|themisto |
0|themisto |       at Object.exports._errnoException (util.js:1050:11)
0|themisto |       at exports._exceptionWithHostPort (util.js:1073:20)
0|themisto |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
0|themisto |   From previous event:
0|themisto |       at Launcher.isDebuggerReady (/home/ubuntu/sirena/themisto/node_modules/chrome-launcher/chrome-launcher.js:153:16)
0|themisto |       at poll (/home/ubuntu/sirena/themisto/node_modules/chrome-launcher/chrome-launcher.js:178:26)
0|themisto |       at runCallback (timers.js:672:20)
0|themisto |       at tryOnImmediate (timers.js:645:5)
0|themisto |       at processImmediate [as _immediateCallback] (timers.js:617:5)
0|themisto |   code: ECONNREFUSED
0|themisto |   errno: ECONNREFUSED
0|themisto |   syscall: connect
0|themisto |   address: 127.0.0.1
0|themisto |   port: 33468
0|themisto |   __error_callsites:
0|themisto |     - {}
0|themisto |     - {}
0|themisto |     - {}
0|themisto |   __stackCleaned__: true
0|themisto |   httpStatusMsg: Internal Server Error
0|themisto |   httpStatusCode: 500
```

**Comment by paulirish** [comment]
@LucianoGanga btw how are you getting that `From previous event` stack? That's a really useful trick..

**Comment by LucianoGanga** [comment]
I'm using PM2 to run my app on a server with clusters... It adds that extra data on it :) 

Right now, I'm able tu reproduce that issue everytime I run the app in that server. so I can give access to anyone that will like to help me with the debugging. I'm running out of ideas here :(
