### ISSUE TITLE
Gulp lighthouse import conflicts with gulp-autoprefixer

### ISSUE THREAD

**Issue by kevinfarrugia** [GoogleChrome/lighthouse#2545]
I have encountered a strange issue and I am unsure on how to investigate this further. When both `gulp-autoprefixer` and `lighthouse` are imported into gulp (even, if in two separate files); `autoprefixer` does not run, nor does it return any errors.

Steps to replicate:
1. `npm install`
2. Setup a gulp task which executes `gulp-autoprefixer`
```js
gulp.task('styles', function() {
  return gulp.src('./style.css')
    .pipe(autoprefixer())
    .pipe(gulp.dest('./public'));
});
```
3. Running `gulp styles` in the command-line should run the above task and output the file style.css in the folder `public`
4. Import `lighthouse`
```js
const lighthouse = require('lighthouse');
```
5. Re-running `gulp styles` will no longer output any files.

I have created a fork to demonstrate further: https://github.com/IncredibleWeb/lighthouse/tree/feature/gulp_recipe_conflicts_with_autoprefixer/docs/recipes/gulp

**Comment by kevinfarrugia** [comment]
After further investigation, the issue seems to be arising from the globals declared in `web-inspector.js` but I am not able to investigate this further.

**Comment by paulirish** [comment]
> the issue seems to be arising from the globals declared in web-inspector.js 

@kevinfarrugia  very possible. thx for lookign into this.

**Comment by brendankenny** [comment]
> After further investigation, the issue seems to be arising from the globals declared in `web-inspector.js`

`web-inspector` has been eliminated!
