### ISSUE TITLE
Kill the codecov PR comments

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2558]
Yes they got annoying pretty quick. :)

3 hrs ago i added a `.codecov.yml` [to master](bfcbc302cb3598c79ce9564993972eeb531bd2ff) with this:

```yml
comment: off
```

It seems to have been ignored so far.

I did validate the yaml with this command:
```sh
cat .codecov.yml | curl --data-binary @- https://codecov.io/validate
```
 
And it's definitely valid. 

I'm awaiting their team to respond on this chat: 
![image](https://user-images.githubusercontent.com/39191/27360007-bbbdfdc6-55d3-11e7-879a-d3a018b10c08.png)

**Comment by paulirish** [comment]
Oh and it's still posting comments on branches that were created with this YAML file in place, so it's not a problem of older branches. :/

**Comment by stevepeak** [comment]
The path of `.codecov.yml` was not being picked up. I'll look into why, but I've fixed this for your project. Thanks

**Comment by paulirish** [comment]
thanks @stevepeak !
