### ISSUE TITLE
Document config file options

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#2572]
We  don't have proper docs on what you can do in a config. Best we have is the [example config](https://github.com/GoogleChrome/lighthouse/blob/master/docs/recipes/custom-audit/custom-config.js) recipe.

For example, `skipAudits` is being added but no one will know about it :(

@patrickhulce do you want to take this one? You're Mr. Config.

**Comment by patrickhulce** [comment]
ya I can take this :)
