### ISSUE TITLE
Video audit: check for correct aspect ratio

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#2578]
The aspect ratio of a video should match the aspect ratio of a video element used to play it, even if the dimensions are different.

Test by comparing video.videoWidth/video.videoHeight with video element  clientWidth/clientHeight.

Need to ensure video loadedmetadata event has fired before testing.

**Comment by ebidel** [comment]
Dupe of https://github.com/GoogleChrome/lighthouse/issues/2579

**Comment by samdutton** [comment]
#2579 is for images, this one's for video :).
