### ISSUE TITLE
Image audit: check for animated GIFs that could be videos

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#2586]
Video with muted autoplay can often be used instead of an animated GIF.

If an image element is found with GIF src (over, say, 20KB in file size) give a warning, something like: 'It appears that you might be using an animated GIFs. Consider using a video (with autoplay muted) instead.' If possible, link to video version of animated GIF and advice on transcoding.

**Comment by wardpeet** [comment]
It looks like we can do something like https://github.com/mailcharts/animated-gif-detector so we make sure it's an animated GIF.

I guess this audit should be placed under Do better web?

**Comment by paulirish** [comment]
> I guess this audit should be placed under Do better web?

eh. ideally our /audits/ folder is grouped by category a bit more...  kind of like https://github.com/Modernizr/Modernizr/tree/master/feature-detects

**Comment by paulirish** [comment]
animated-gif-detector looks great. yeah i think that'd work out nicely.

**Comment by brendankenny** [comment]
was fixed in #4885!
