### ISSUE TITLE
Launcher: Export a new option to toggle `disable-extensions`

### ISSUE THREAD

**Issue by ragingwind** [GoogleChrome/lighthouse#2594]
Nowadays, `disable-extensions` is a default flag that doesn't allow me have a test for extension app. It might be useful that user can turn on / off the flag vi an option from outside when to test a chrome extension with lighthouse/chrome-launcher. I usually use a chrome while extension testing like this

```
/Applications/Chromium.app/Contents/MacOS/Chromium --app=file:///chrome-extension/extended/test/index.html --system-developer-mode --load-extensi
on=./test/extension
```

**Comment by ebidel** [comment]
Does chromeFlags cover your use case? 

https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/README.md#launch-options

**Comment by ragingwind** [comment]
No, it doesn't work well. `disable-extensions` flag might prevent to load extension following flags `--load-extension=./test/extension`

**Comment by paulirish** [comment]
hah. turns out we predicted this was coming. :) 

https://github.com/GoogleChrome/lighthouse/pull/916#issuecomment-310222563

thanks for filing, @ragingwind! (and for creating chrome-launcher-cli!!)

maybe we expose a `enableExtensions` option on launcher? that seems pretty ok

**Comment by ragingwind** [comment]
@paulirish

**Comment by paulirish** [comment]
@ragingwind do you want to try contributing this to launcher? otherwise it's gonna be a little while till we get to this. :)

**Comment by ragingwind** [comment]
@paulirish sure. I will make a PR for this
