### ISSUE TITLE
Service Worker Enabled when JavaScript Disabled?

### ISSUE THREAD

**Issue by mikestead** [GoogleChrome/lighthouse#2595]
We have a setup where a server render is done on initial app load and then on future visits the SW uses an app shell page instead of going to the server. We're using [sw-precache](https://github.com/GoogleChrome/sw-precache) to help here, with its `navigateFallback` option.

What we're seeing is that the Lighthouse test which disables JavaScript doesn't seem to disable the service worker, meaning the app shell is returned. This doesn't contain much HTML so we get a low score here

    ❌  Contains some content when JavaScript is not available

What I would expect is for the SW to be bypassed when JS is disabled and the server render to kick in.

Can you confirm this should indeed be the case?

It looks like this may be the source of the issue, has anyone else come across this before? https://bugs.chromium.org/p/chromium/issues/detail?id=656516

Tested on Mac OSX 10.12.3 with Chrome Canary 61 & Chrome Stable 58

**Comment by patrickhulce** [comment]
Hey @mikestead thanks for the report we have an issue tracking this (#2096), and it is indeed a bug.

**Comment by mikestead** [comment]
@patrickhulce Thanks for confirming and sorry for missing the existing ticket. Feel free to close this as a duplicate.

**Comment by patrickhulce** [comment]
No worries it wasn't the easiest to find :) feel free to chime in over there if you think there's anything to add
