### ISSUE TITLE
Clarify on the Lighthouse home page if this tool sends any of your site data to remote servers (HIPAA/PHI violations)

### ISSUE THREAD

**Issue by scunliffe** [GoogleChrome/lighthouse#2598]
I work in the healthcare field, and as such many of the apps I work on are under tight restrictions as to who can see or collect data that is PHI (Private Health Information) etc.

As such if Lighthouse sends web page data to a remote server for processing, we can't use the service - but if it runs all of its tests locally, its fine.

Adding some clarification to the project home page as to how the tool works (all local, or sends data to a server) would thus make it endorse-able as a tool (if all local), or a clear "not for healthcare/financial work" tool (if sends to remote)

**Comment by ebidel** [comment]
Hi @scunliffe, we have a FAQ entry for this one: https://github.com/GoogleChrome/lighthouse#are-results-sent-to-a-remote-server. TLDR is everything is tested in the local browser. Nothing is sent to a remote server.

**Comment by scunliffe** [comment]
@ebidel awesome! I'm sorry I missed that. I'll dig right into it then!
