### ISSUE TITLE
metric: First meaningful paint (1.0)

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#26]
Ideally, the first paint where the user feels that _the primary content is visible_

This means paints with only the topnav don't qualify. Any primary text must be visible (and not waiting for fonts). If an image is critical to the page (e.g. e-commerce product page), then first meaningful paint requires it to be visible.

Manual evaluation:  Network Tab in DevTools timeline. Reload with screenshots/filmstrip enabled. Select the first screenshot with a meaningful view. 
##### Input:
- Use ksakamoto's work:
  - [First meaningful paint? - Google Groups](https://groups.google.com/a/chromium.org/forum/#!topic/loading-dev/ESF4e7vC6cU/discussion)
  - [First Meaningful Paint - manual 
    evaluation](https://docs.google.com/document/d/1eMA9YWTLFCJomyiKUO4Be4PeVIOBFMfXMdE8bpudL_o/edit#heading=h.oqp46zxwsqwh)
  - [Time-to-first-X-paint metrics: status and refinement 
    plans](https://docs.google.com/document/d/1Owfs6arciEnWgT2-8bWCcHdYRIKRKZ0Xj8UtqRx4c3k/edit#heading=h.nwfi9zag6eyn)
  - [&quot;Is it useful?&quot; metric (aka. First meaningful paint): layout-based approach - Google Groups](https://groups.google.com/a/chromium.org/forum/#!topic/loading-dev/GZyyd9IRqCU/discussion)
##### Audit Scoring
- Metric's value is milliseconds from navigationStarted until this paint hit `swapBuffers` from GPU/browser threads.
- Goal: first meaningful paint delivered from first 14K of the HTML document in 1000ms (on the reference device/network class)
- Metric's score will be expressed as n/100.
  - 100/100 score is fMP in <= 1000ms
  - 90/100 is ~= 3000ms
  - TBD: Determine curve of score down to 0/100.

**Comment by paulirish** [comment]
We need to adopt `firstContentfulPaint`. This'll match tracing and also make airhorner work. :)

**Comment by paulirish** [comment]
cc @brendankenny to poke into the negative values and filtering for main frame timings only.

**Comment by paulirish** [comment]
Our phase 1 implementation using firstContentfulPaint landed.

Now that ksakamoto has finished the spec of first meaningful paint, based on the layout sizes, we will track our phase 2 implementation with this ticket.

**Comment by paulirish** [comment]
Did the initial port: https://github.com/GoogleChrome/lighthouse/compare/master...paulirish:fmp1point0

However! This analysis relies on a few trace points that are not yet landed (https://codereview.chromium.org/1773633003), so we can't adopt it yet. I'll work with ksakamoto to move this forward.

**Comment by paulirish** [comment]
Update from ksakamoto. He's landing half of his CL this week. 
The second half (the fonts part) will have to wait until he returns from vacation (after May 8th). However the fonts part is something that we can calculate on our end, if need be, so it shouldn't be a problem. :)

**Comment by umaar** [comment]
Just a heads up: in the `report.html`, I get a `-1` for `Fast first paint of content (target value: 1,000ms )`.

**Comment by paulirish** [comment]
with this PR or just in general?

**Comment by umaar** [comment]
In general via the webstore extension, was commenting here because of the related title, oops

**Comment by paulirish** [comment]
all good. this PR will fix the bug. but thank you. :)

**Comment by dalimiane** [comment]
Hello, wanted to ask when will this be available in chrome. will these metrics be exposed through js api, do we kno details

**Comment by paulirish** [comment]
early work was done a while ago.
#618 picks up the remaining stuff.
