### ISSUE TITLE
bin.ts refactor for module usability & testing

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2601]
the bottom of bin.ts has some core functionality we want to expose. one primary usecase is to get the launch+runlighthouse+getresults flow is available to other modules (see https://github.com/addyosmani/webpack-lighthouse-plugin/issues/5)
other usecase is better tests of the CLI.. these methods arent testable as they sit in bin.ts which requires CLI interaction

----------

Here's the current summary of the two files:

#### -core/index

1. throw if missing URL
1. set logging defaults
1. generate config from provided json
1. set up CRI connection
1. call Runner.run()

#### -cli/bin.ts

1. call getFlags() and process early stdout exits
1. read configPath from disk
1. set logging defaults
1. set outputpath defaults
1. show errors, for a number of cases:
    1. console.error readable error
    1. process.exit w/ code
1. runLighthouse
    1. call launcher.launch()
    1. call -core/index
    1. call saveResults
    1. handle --interactive mode
    1. kill launcher
    1. call handleError
1. saveResults
    1. call saveArtifacts (which saves to disk)
    1. call saveAssets (which saves to disk)
    1. prepare filenames
    1. call Printer.write()
    1. call opn()

-----------

Ideally much of the items in `bin.ts` move into `index.js`. However when you dig into it, this refactor gets a little hairy. For example: `handleError` both logs a friendly error message and process exits. Half of this is appropriate when LH is a node dependency. Another example: Some webpack-lighthouse-plugin wants to use `save-assets` and have the report saved to disk but shouldn't get reminded to run LH with the `--view` flag.

None of this is particularly hard, but it would require time and testing to do it right.

I'm proposing an intermediate fix that will unblock webpack-lighthouse-plugin among others. This fix: move much of bin.ts into its own file that can be safely require()'d without any yargs interference. PR incoming..

**Comment by wardpeet** [comment]
@paulirish should we use the projects tab maybe? Or create separate tasks (issues) for this one?

I don't mind giving this my all, not sure what timeframe you're pointing at. Or if i'm the right person to do so 😝

**Comment by paulirish** [comment]
Fixed by  #2602
