### ISSUE TITLE
chrome-launcher: Maybe add a notification on 'Close' event?

### ISSUE THREAD

**Issue by ghost** [GoogleChrome/lighthouse#2609]
Greetings,

So, we're doing some unit testing of an application. One of such test is to launch a Chrome instance, run some JavaScript to close Chrome. After that, we have to test whether or not the Chrome is actually closed.

In current implementation of `chrome-launcher`, it's very hard to do so because there is no callback which will indicate a passive Chrome shutdown.

However, [it seems that](https://nodejs.org/api/child_process.html#child_process_event_exit) the `child_process` module is actually support `exit` event, so maybe it's possible to add a callback to notify the Chrome instance is gone?

**Comment by ebidel** [comment]
cc @samccone

**Comment by samccone** [comment]
seems like a good idea to me :)

**Comment by gwuhaolin** [comment]
@reinit I have [the same need](https://github.com/GoogleChrome/lighthouse/issues/2503) with you, I rewrite chrome-launcher to [chrome-runner](https://github.com/gwuhaolin/chrome-runner) which may be a perfect solution for your issue.

**Comment by reinit** [comment]
Thank you for telling me this @gwuhaolin. I started your project, and will give it a look when I have time. (I'm dealing with a more serious problem now, so...)

And.... Why you don't ... you know, add this feature to the `chrome-launcher`? I don't think they will take the whole project in.

BTW, The blog content of https://github.com/gwuhaolin/blog/issues/7:
> ....写e2e测试脚**步**注入....

I believe you were saying 

> ....写e2e测试脚**本**注入....

Don't trust your Pinyin IME :D

**Comment by gwuhaolin** [comment]
@reinit Thank you for pointing out my fault.

`chrome-launcher` built-in some lighthouse relative stuff which I don't need in my use case.

BTW: 你们这些老外的中文尽然都比我好,让我情何以堪😅

**Comment by reinit** [comment]
@gwuhaolin Well, if you take 5 seconds to check out my profile you will realize that I'm not a 老外 so LOL.

 Very good article though.
