### ISSUE TITLE
bug: report's userAgent is emulated userAgent

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#2612]
We added [`driver.getUserAgent`](https://github.com/GoogleChrome/lighthouse/blob/fadaef95137181aa41ed44fd78f17d3a8b85a2c3/lighthouse-core/gather/driver.js#L88-L90) so that we could capture the version of Chrome we're running in, however [we're calling it *after* we've set up device emulation](https://github.com/GoogleChrome/lighthouse/blob/fadaef95137181aa41ed44fd78f17d3a8b85a2c3/lighthouse-core/gather/gather-runner.js#L101-L106), so the report only includes the emulated userAgent (if emulating, obvs).

We should get the userAgent first thing (or however else to make sure it's independent of emulation).

As a bonus, we should probably also stick the emulated userAgent string in the report's [`runtimeConfig.environment`](https://github.com/GoogleChrome/lighthouse/blob/fadaef95137181aa41ed44fd78f17d3a8b85a2c3/lighthouse-core/runner.js#L324) since we do change that from time to time as new Chrome versions come out.

**Comment by paulirish** [comment]
> As a bonus, we should probably also stick the emulated userAgent string in the report's [`runtimeConfig.environment`](https://github.com/GoogleChrome/lighthouse/blob/fadaef95137181aa41ed44fd78f17d3a8b85a2c3/lighthouse-core/runner.js#L324) since we do change that from time to time as new Chrome versions come out.

@brendankenny I didn't fix this. should we reopen?

**Comment by brendankenny** [comment]
ha, I barely remember writing that. Would that be useful? It might be, though I don't know how much that would end up mattering when trying to interpret an old result. Maybe very old results (like http archive results from now when it's a year from now)
