### ISSUE TITLE
Brainstorm on criteria for adding a new audit

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#2624]
All new audits bring overhead—in runtime performance, development maintenance, and report overload—so it would be good to have a list of criteria that allow weighing tradeoffs before adding a new audit or gatherer to Lighthouse core. Not necessarily for basing inclusion on a threshold that must be passed, but ideally most of the items below should be answered and documented somewhere before an audit is accepted.

Here are a few starting criteria I'd like us to enforce. Feel free to add to it/clarify things/strike things out as too onerous.

- Audit goal
  - Does it measure something important?
   Easily measurable things are often not important, and many important things are very difficult to measure. Is it worth bringing to a developers attention? If a metric is being used as a proxy for the real goal of an audit, they should correlate well, demonstrated with real data.
  - What are the specific pass/fail states?
  - If it's going to be a perf metric, it must be quantifiable:
   How much does thing X hurt page performance? If a performance best practice doesn't actually have an effect we can measure, it may not be worth including (and may not actually be a performance best practice :)
- Runtime performance overhead
  - How much does it slow down a LH run on a typical page? What about on pathological pages (ones with many images or many event listeners or many long tasks, etc)?
  - Does it require a new gatherer pass?
   It can be difficult to schedule new gatherers if they have specific offline/throttling/serviceworker-initialized requirements, but adding a new pass (and an additional page load) is the very last resort, and may often be worse than not including the audit.
- Does it call out to third-party servers?
  - This is currently a strict no.
- Report noise
   The report needs to communicate clearly what Lighthouse thinks are top priorities, and we only have so much developer patience when reading our results.
  - Does it overlap with existing audits?
   Maybe we should refactor the existing audits so that we can have a single audit that provides more insight.
  - On how many sites is it relevant?
   If it only applies to a small subset of sites, is it just noise in the report for most people running Lighthouse? We've discussed one way of dealing with this, an audit that just won't show up in the report if it wasn't relevant (e.g. don't show `<video>` audit results if there were no `<video>`s in the page)

Some of these aren't always relevant. A best-practices audit may not have good answers for e.g. scorability but could still be included if it has minimal overhead. If a set of audits almost always passes, the extra noise in the report may be fine since they'll be hidden away in a "passed items" section.

If an audit/gatherer isn't appropriate for the default config, it still could live in the newly-created [full config](https://github.com/GoogleChrome/lighthouse/blob/1bf0e07cb568a1d54fe19f8a216115da47e05a4d/lighthouse-core/config/full-config.js), where for now our performance requirements are less strict.

We also shouldn't be afraid of starting to point new audit ideas at Lighthouse plugins, which can have their own domain-specific requirements for audits. However, plugins have the downside that they can't currently be loaded in Lighthouse in DevTools or in the extension.

**Comment by brendankenny** [comment]
Should add effect on `lighthouse-background` bundle size due to dependencies

**Comment by paulirish** [comment]
Great list.

* Is the audit definitely relevant to all people who care about this reportCategory?

**Comment by rviscomi** [comment]
> On how many sites is it relevant?
If it only applies to a small subset of sites, is it just noise in the report for most people running Lighthouse? We've discussed one way of dealing with this, an audit that just won't show up in the report if it wasn't relevant (e.g. don't show <video> audit results if there were no <video>s in the page)

Was this ever addressed? For example, let's say I have an audit that affects 1/1000 of pages. Is that too noisy or irrelevant? If the audit could be hidden when passed, that would be helpful because it may be be a significant but rare issue.

**Comment by patrickhulce** [comment]
It might be time to add support for flagging an audit result as not relevant for the page. It came up again recently as part of the image aspect ratio audit. As with other descriptions, it feels weird to tell you that all your images had proper aspect ratios when there were no images at all :)

**Comment by wardpeet** [comment]
hidden might not be the best case, maybe just somewhere below where it says. These audits were irrelevant for your webpage. The reason why I wouldn't hide them would be that people might not know we also audit those cases

**Comment by brendankenny** [comment]
before landing, there's a couple of things that should be checked in the PR as well. One thing we're forgetting almost every time is adding a smoke test
