### ISSUE TITLE
CLI hangs on "generating results..."

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2628]
with what's on master:

```sh
lighthouse --perf "chrome://version" --output=json > file2.json
```

![image](https://user-images.githubusercontent.com/39191/27754924-cc8c7cf6-5da1-11e7-8095-c910775e5da7.png)

Just hangs there indefinitely until this error:

> (node:49615) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: The asynchronous expression exceeded the allotted time of 60s
> (node:49615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by patrickhulce** [comment]
Hmmm, interesting latest master for me doesn't hang or crash, but there's a 50/50 chance of timing out on waiting for the page to load. Might be related to waiting for CPU idle?

**Comment by patrickhulce** [comment]
Well of course now I can't get it to timeout anymore. Looks like we're missing more `DOM.enable` calls though

![image](https://user-images.githubusercontent.com/2301202/27755245-6c0d22d4-5da3-11e7-8c85-50e0130d683a.png)
