### ISSUE TITLE
Audit: http -> https redirect in place

### ISSUE THREAD

**Issue by slightlyoff** [GoogleChrome/lighthouse#263]
Something we see some sites fail at is redirecting Chrome users to HTTPS. Would be good to make sure we audit for this.

**Comment by paullewis** [comment]
We do a second load, I wonder if we try and capture this then. It could jeopardize SW tests if we don't recover, but that seems doable.

**Comment by paullewis** [comment]
On second thought, I wonder if we just do this up front... Meh, one to ponder. Thanks for the bug though!

**Comment by paullewis** [comment]
Taking this on.
