### ISSUE TITLE
Audit: Attribute mainthread costs by framework

### ISSUE THREAD

**Issue by evenstensberg** [GoogleChrome/lighthouse#2631]
Don't know if this is possible, close if irrelevant or if this is implemented in some way.

## Summary

I think it would be convenient to include how much of the framework code is included in the FMP or TTI. This way, authors have more of an indication of what code they need to strip in order to gain a good audit on `TTI` or `FMP`. Tools that are reliant on lighthouse could also benefit from this, as you could with, for instance webpack, make sure to split your bundles into `vendor` chunks. Don't really know how to approach this problem though.

https://youtu.be/aCMbSyngXB4?t=2m55s

CC-ing in @addyosmani for more thoughts.

**Comment by tdresser** [comment]
I suspect we can do something like this.

We have approximate code coverage data - we just need to take a snapshot at FMP or TTI.

**Comment by ev1stensberg** [comment]
I think the hard part would be to split your code from the framework associated code, as this sometimes intersects. I may be wrong though

**Comment by patrickhulce** [comment]
This would be great! I also fear this falls into the problem of the more sophisticated the user (bundling assets where coverage data is difficult to disentangle, etc) the less likely we'll be able to accurately report this information, which is unfortunate since I suspect they're also the most likely to take action on it.

**Comment by tdresser** [comment]
Is splitting out framework logic necessary for this?

I would have thought just indicating what code had executed at the time of FMP/TTI would be pretty useful.

**Comment by brendankenny** [comment]
let's close and defer to a few other issues like
- bundle/source-map analysis: #9097 
- third-party wrapping attribution: #7005
- third-party identification improvements: #7474
etc
