### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by cuznerdexter** [GoogleChrome/lighthouse#2634]
**Initial URL**: https://0.0.0.0:8007/app/messaging/keywords
**Chrome Version**: 61.0.3148.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@155b257ae4cf8873f8561ec6a00c61ebec47548a/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

I opened a new Chrome Canary window (no previous process running)
Loaded my dev site (using webpack-dev-server --https)

Opened chrome inspector / audits tab - lighthouse
Run audit with only Progressive mode selected

Then after less than 1second it fails with the error
**"Protocol error (Tracing.start): Tracing is already started"**

**Comment by wardpeet** [comment]
Dupe #1091 
note: devtools not extension
