### ISSUE TITLE
[Feature Reqeust] Security Test

### ISSUE THREAD

**Issue by zhenyulin** [GoogleChrome/lighthouse#2635]
Would it be a good idea to integrate services like `https://securityheaders.io/` into lighthouse extension?

**Comment by ev1stensberg** [comment]
#2372 ongoing integration @zhenyulin :)

**Comment by paulirish** [comment]
2372 is analysis of js libraries used on the page. There are other security concerns like HSTS, CSP, etc... most of those are captured under the #277 ticket.

@zhenyulin we think it's worthwhile to integrate services like observatory or hardenize, but we also want to make sure users opt-in when we use an external service to analyze the page.

duping to #277
