### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by radum** [GoogleChrome/lighthouse#2646]
I'm not sure if a HTTP request is made also as part of the test, if it is and the local server doesn't serve anything via HTTP this might be the reason.

**Initial URL**: https://local.dev:4243/live.html
**Chrome Version**: 61.0.3149.0
**Error Message**: Unable to load the page: net::ERR_EMPTY_RESPONSE
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_EMPTY_RESPONSE
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@4485eb651f6f09c3183285927fe82d17fcd7a13e/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@4485eb651f6f09c3183285927fe82d17fcd7a13e/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by jamesseanwright** [comment]
I'm witnessing the same via the Lighthouse Chrome extension. It begins to audit a local instance of my app which is served with a self-signed certificate, but then it ultimately requests it again over HTTP.

Lighthouse has [an audit](https://github.com/GoogleChrome/lighthouse/blob/63b4ac14d0a871ade0630db2885edd7848843243/lighthouse-core/test/audits/redirects-http-test.js) that will fail if an app has no HTTP-to-HTTPS redirect, so it seems that this is a bug.

**Initial URL**: https://localhost:3001
**Chrome Version**: 59.0.3071.115 (64-bit)

**Comment by jamesseanwright** [comment]
I also see this with 1.6.5, so for now I've implemented a local redirect.

**Comment by patrickhulce** [comment]
thanks for the detailed report @jamesseanwright! this does indeed seem like an instance of #1978
