### ISSUE TITLE
SpeedIndex may not be accurate for slow pages with animation

### ISSUE THREAD

**Issue by pmeenan** [GoogleChrome/lighthouse#2647]
Dev Tool's screenshots [stop at 450 frames](https://bugs.chromium.org/p/chromium/issues/detail?id=739759) which can be hit really quickly for sites with loading spinners (7.5 seconds at 60fps).  In practice I've seen it consistantly stopping capture 15-20 seconds into a page load for a few slow sites with spinners that I looked at.

When that happens, the video will be truncated and the reported SpeedIndex will be artificially fast (using the animation spinner as the end state).

**Comment by paulirish** [comment]
This is awaiting upstream changes in screenshot collection in Chromium. @pavelfeldman maybe this fits in with the screenshot-from-surface approach you were discussing yesterday.

**Comment by brendankenny** [comment]
since it's unlikely we'll be getting any magic new screenshot method anytime soon, let's dedupe into screenshot throttling: #4713
