### ISSUE TITLE
Format hellper test failed in other timezone like Korea

### ISSUE THREAD

**Issue by ragingwind** [GoogleChrome/lighthouse#2648]
I'm not sure It needs to be fixed. But It shows me an error as do test every time. Here is the report from test:
```
 1) util helpers formats a date:

      AssertionError: false == true
      + expected - actual

      -false
      +true

      at Context.it (lighthouse-core/test/report/v2/renderer/format-helpers-test.js:22:12)
```
reason is that Unfortunately, Util.formatDateTime returns date with adding +9 hours, so date value is "Apr 29, 2017, 8:07 AM GMT+9" not "Apr 28, 2017, 8:07 AM GMT+9", which leads test get a failure:

```
it('formats a date', () => {
    const timestamp = Util.formatDateTime('2017-04-28T23:07:51.189Z');
    assert.ok(timestamp.includes('Apr 28, 2017'));
  });
```

**Comment by patrickhulce** [comment]
good point @ragingwind :) I believe @ev1stensberg had a fix for this test in a PR somewhere

**Comment by ev1stensberg** [comment]
I just added `||` for the day before and after at #2396

**Comment by paulirish** [comment]
Nice. I carried the patch over into #2653
