### ISSUE TITLE
I'm getting Audit Error, and I believe it's due to Stripe and Intercom scripts in my app

### ISSUE THREAD

**Issue by dekkofilms** [GoogleChrome/lighthouse#2649]
I'm getting this audit error on First Interactive and Consistently Interactive: 

***Audit Error: The main thread was busy for the entire trace recording. First Interactive requires the main thread to be idle for several seconds.

And I'm pretty sure it's coming from our Intercom and Stripe script running on the index page. When I took out those two from the index.html page my score jumps up by 30 points, and I don't get that Audit Error anymore.

I guess my question is ... is there anything I can do about this on my end to help our scores? I saw a related issue on here: https://github.com/GoogleChrome/lighthouse/issues/2434, and one of the answers was checking with Stripe to figure out if that is unexpected or a resolve needing to happen on their end. As far as integration goes on our end, it's just following their docs exactly, so I'm just not sure what else to do. 

Any thoughts, guidance, or help would be greatly appreciated!

**Comment by patrickhulce** [comment]
Are you using v2.2.1? A change went out with that release that should wait until the CPU is idle. If you are using 2.2.1 and it's still failing, is the load reaching the 30 second timeout (which would be indicative of the same issue as #2434)? 

In #2434, that version of stripe's script drastically impacted performance and the audit fails because the page legitimately never became interactive (there was a long task occurring regularly despite no input from the user), so a score of 0 is appropriate.

Do you have a public URL where the site is accessible or a trace file from a Lighthouse run with `--save-assets` we could look at?

**Comment by dekkofilms** [comment]
As far as version ... I am not using the CLI for Lighthouse, but the Google Chrome extension which is version 2.2.1. So I'm assuming that is the latest version. 

Yeah, as far as Stripe goes, I am using the same version that I presume causes that drastic performance issue in that related issue, and I can't upgrade to v3. I chatted with the Stripe guys, and apparently the new version doesn't allow bank account input, which is what our app needs. So there only recommendation was to stay on v2, unfortunately. :/ 

I don't currently have a public URL as this is mainly being tested on our staging site, but let me get production maybe up to date, or the trace file, and I'll respond shortly! Thanks @patrickhulce

**Comment by dekkofilms** [comment]
Here is my trace file for the audit:

[sandbox-editor-react-staging.herokuapp.com_2017-07-07_09-37-20-0.trace.json.zip](https://github.com/GoogleChrome/lighthouse/files/1131289/sandbox-editor-react-staging.herokuapp.com_2017-07-07_09-37-20-0.trace.json.zip)

**Comment by patrickhulce** [comment]
Thanks for sending that along, there are quite a few things going on here, but you're right that Intercom and Stripe are really dragging your site's performance down. 

![image](https://user-images.githubusercontent.com/2301202/27968787-583e9dc8-62fd-11e7-9068-d474076e0528.png)

Diving in deeper we can see that the Stripe long task timers (the smallish yellow boxes flagged with red in the timeline above) did eventually settle down at around 25s but another Intercom XHR callback took 400 (!!) ms and then Lighthouse timed out at 30s. First thing you can try to at least get a number to start with would be to run Lighthouse from the CLI with the `--max-wait-for-load` flag set to a higher number like `60000` (one minute). This will wait for as long as necessary for the page to quiet down when hopefully all the Stripe and Intercom activity has died down.

Ultimately though, these scripts do significant harm to your page's performance, and I'd encourage you to put some pressure on those vendors to address these issues. Feel free to refer them to this thread and those traces you've captured. We're happy to help them get to the bottom of this and make the web faster for everyone!

**Comment by dekkofilms** [comment]
Awesome thanks so much @patrickhulce for digging into that with me. This is all a little new for me, but I really appreciate the great info! I will definitely try to reach out to both Stripe and Intercom and see what conversation we can start there, as well as, using the CLI to set that `--max-wait-for-load` flag to something a bit higher to get a number. 

I would also love any other alarming things you see other than the two scripts. We are just now starting this optimization process and I'm currently still just going down the list and optimizing. Thanks again for your help, and feel free to close this issue!

**Comment by patrickhulce** [comment]
Great to hear @dekkofilms! 

The other thing that jumps out from this trace is the very large amount of JavaScript the page is loading. Your primary bundle is 2.6 MB uncompressed, which can take multiple seconds just to parse on a mobile device. When you add in the more than 4 seconds that's spent evaluating for the initial render, your first paint time is going to be pretty far out just based on this one resource.
![image](https://user-images.githubusercontent.com/2301202/27978728-10876c16-6326-11e7-901f-9df4851fa5cd.png)

This is a [really good article](https://medium.com/reloading/javascript-start-up-performance-69200f43b201) on understanding the cost JS bundles have on your load times and some best practices to follow.

**Comment by dekkofilms** [comment]
Awesome, thanks for the resource @patrickhulce ... that does intrigue me, cause when I just run performance in the devtools for page load, I can never seem to recreate that. I have that file gzipped at 635kb, and on the network it loads in 864ms. How are you getting this performance log, I guess is the question? ha. Thanks again!

![screen shot 2017-07-10 at 8 39 15 am](https://user-images.githubusercontent.com/14862852/28020836-50156d5c-654b-11e7-8270-64cc520f6f2b.png)

**Comment by patrickhulce** [comment]
@dekkofilms are you collecting a trace with the throttling settings on? Lighthouse runs its tests with the "Fast 3G" and "4x slowdown" settings you can find in Chrome Canary after clicking on the gear icon in the top right.
![image](https://user-images.githubusercontent.com/2301202/28031117-2707925e-655b-11e7-9993-133686c5fc23.png)
