### ISSUE TITLE
chrome-launcher launched google-emacs instead of google-chrome

### ISSUE THREAD

**Issue by pwwpche** [GoogleChrome/lighthouse#2652]
I am using node 6.11 and lighthouse 0.3.1. I found that every time I start lighthouse, google-emacs is launched instead of google-chrome-stable. 

I check the code in chrome-finder.ts in chrome-launcher. In `function linux()` before `const priorities: Priorities`, contents in `installations` was
```
[ '/opt/google/chrome/google-chrome',
  '/opt/google/chrome/google-chrome',
  '/opt/google/chrome/google-chrome',
  '/opt/google/chrome/google-chrome',
  '/opt/google/chrome/google-chrome',
  '/opt/google/chrome/google-chrome',
  '/opt/google/chrome/google-chrome',
  '/opt/google/chrome/google-chrome',
  '/usr/bin/google-emacs',
  '/usr/bin/google-chrome-beta',
  '/usr/bin/google-chrome-beta',
  '/usr/bin/google-chrome-beta',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/google-chrome' ]
```

after sorting it became
```
[ '/usr/bin/google-emacs',
  '/usr/bin/google-chrome-beta',
  '/usr/bin/google-chrome-stable',
  '/opt/google/chrome/google-chrome',
  '/usr/bin/google-chrome' ]
```

So I guess perhaps the priority of items in `installations` is not set correctly?

**Comment by brendankenny** [comment]
looks like [this is the offending regex](https://github.com/GoogleChrome/lighthouse/blob/9561330dc1b4924b423ed6ae75c4473b4218a7d2/chrome-launcher/chrome-finder.ts#L170)?

We can probably assume Chrome executables starting with `'google'` will always start with `'google-chrome'`.

@wardpeet if you have time for it :)

**Comment by wardpeet** [comment]
@brendankenny will have a look

**Comment by paulirish** [comment]
Looks like we never fixed this. PR is up  here https://github.com/GoogleChrome/chrome-launcher/pull/35
