### ISSUE TITLE
Lighthouse fails to finish the test, stalls on "ServiceWorker, Offline, StartUrl"

### ISSUE THREAD

**Issue by nhoizey** [GoogleChrome/lighthouse#2655]
Lighthouse fails to finish the test on https://nicolas-hoizey.com/2017/01/how-much-data-should-my-service-worker-put-upfront-in-the-offline-cache.html or any other page of my blog.

It stalls here:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/78213/27984134-db82a3e8-63cd-11e7-8dac-e84d9a511a70.png">

Using Chrome 59.0.3071.115 on macOS 10.12.5 and Lighthouse 2.2.1 [in a clean profile](https://twitter.com/owencm/status/883471915926511616).

**Comment by nhoizey** [comment]
Still can't audit my site, now in Chrome 60.0.3112.113 with Lighthouse included in the devtools.

It looks like it might be because of HSTS, as mentioned by @paulirish in #2784 

https://www.ssllabs.com/ssltest/analyze.html?d=nicolas-hoizey.com

**Comment by patrickhulce** [comment]
I can repro in Chrome Canary as well.

**Comment by brendankenny** [comment]
Moving to  #2784
