### ISSUE TITLE
Is the Performance rating reliable?

### ISSUE THREAD

**Issue by georgecm** [GoogleChrome/lighthouse#2664]
Hi, I just ran two tests on the same page to detect the effect of embedding some JS and CSS in the main files.

Embedded 
![image](https://user-images.githubusercontent.com/4643480/28011779-70274452-655b-11e7-95ce-b6134f2b9096.png)

Separate
![image](https://user-images.githubusercontent.com/4643480/28011791-7f6c704a-655b-11e7-9afe-d49855badcb1.png)

While the second one seems overall slower, the performance rating is higher! (44 vs 40)

Do I miss something?

Thanks

**Comment by patrickhulce** [comment]
@georgecm in the first case the Consistently Interactive audit errored and so was treated as a 0 for the overall performance score. In the second case, the audit succeedd and so you received what is likely around a 40 which brought your overall score up.

Separately, does the Consistently Interactive audit regularly error for you? What version of Lighthouse was this produced with? Based on the report I don't see any of the known issues at play that would make it fail in the latest version of LH, so we should file a separate bug if you can reproduce that error.
