### ISSUE TITLE
Decide on & document stable vs. experimental properties of the LHR

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#2668]
Currently audits need to maintain certain properties of their return object for backwards compatibility in DevTools/viewer (details, name, description, etc). However, it's not clear to external consumers what properties are safe to use within a major version and which are not (e.g. [we almost removed all of extendedInfo](https://github.com/GoogleChrome/lighthouse/pull/2596) in a patch version bump which people were likely using from previous versions).

We should decide and document which properties we're committed to keeping until v3 and make it easier to confidently consume LH results.

**Comment by brendankenny** [comment]
this would go well with whatever docs generator we come up with for #2463 :)

**Comment by patrickhulce** [comment]
Mostly done by #3495, future work might be reworking the extendedInfo to be more stable.
