### ISSUE TITLE
Document metric instability reasons (Interference with Virus Scanners)

### ISSUE THREAD

**Issue by patrickcollins12** [GoogleChrome/lighthouse#2674]
I'm noticing that Lighthouse is clashing with Virus scanners. Our score recently dropped from 94 to 73. Lighthouse runs very slowly, clashing with our antivirus tool, thus creating significant score drops.

I suspect that this new issue coincides with the latest release of v2.2.1.

Specifically, right now my company is using Sophos Central Endpoint v9.6.3. I'm fortunate to have an IT team that will allow me to temporarily disable the antivirus tool to run the lighthouse tool (but it violates our security policies to do so). By disabling our scanner I can get our score from 73 back up to 94.

I'm also aware that in my customer's corporate environment (Windows) that this problem occurs. Unfortunately for them they are not able to disable their virus scanner.

I strongly suggest some documentation and on-screen reminders to disable virus scanners.

**Comment by paulirish** [comment]
Very interesting. 

Can you export the JSON of both runs? That way we can see what tests are being affected.

**Comment by patrickhulce** [comment]
And maybe the trace file too? (using the `--save-assets` flag)

**Comment by paulirish** [comment]
Agree to document that antivirus can mess with results. and document other things (extensions) that may have such an effect.

**Comment by vinamratasingal** [comment]
I added some documentation to the scoring doc- do we need documentation on the main page as ell that tells people how to run it?

**Comment by brendankenny** [comment]
from https://github.com/GoogleChrome/lighthouse/issues/2394#issuecomment-326513484, we should probably also mention ad blockers possibly causing trace issues (though the CLI shouldn't have any issues with this since it doesn't allow any extensions by default)

**Comment by patrickhulce** [comment]
This is fairly well documented by https://docs.google.com/document/d/1BqtL-nG53rxWOI5RO0pItSRPowZVnYJ_gBEQCJ5EeUE/edit at this point, marking closed.
