### ISSUE TITLE
Issue performance warning if chromeFlags includes --headless

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2675]
[Headless doesn't support network throttling](https://github.com/GoogleChrome/lighthouse/issues/2008#issuecomment-305651781), so performance measurements aren't comparable against regular headful chrome.

I figure we can at least issue a warning to remind people of this until it's fixed in Chrome.

**Comment by ebidel** [comment]
@paulirish I think this is finally fixed :)

**Comment by ataylorme** [comment]
@ebidel to clarify the warning has been added to Lighthouse, not network throttling support with headless Chrome, correct? I saw the [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=728451) was marked fixed so thought it's worth asking.

**Comment by ebidel** [comment]
We did some testing on Friday. Turns out headless chrome now supports network throttling! It wasn't 100% clear from that bug.

Headless supports throttling as of Chrome 63. We're updating the warning to only complain when you use headless on an older version. See https://github.com/GoogleChrome/lighthouse/pull/4021.

**Comment by ataylorme** [comment]
@ebidel this is great news! I tested this out and ran headless Chrome 63 with Lighthouse and saw the same scores as running with the browser extension. Have this running as part of my CI process now!

**Comment by smanwaring** [comment]
@ataylorme Curious how you were able to specify a Chrome version for your CI? Running into the same issues on my end.

**Comment by ataylorme** [comment]
I just used the latest stable version of Chrome. At the time I built my Docker image that was `63`. You can check out the image [here](https://github.com/ataylorme/docker-node-Advanced-WordPress-on-Pantheon/blob/lighthouse/Dockerfile#L54:L59).

This is a good reminder to update my Lighthouse version!
