### ISSUE TITLE
compile-devtools currently failing

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2677]
This test is failing on Travis and locally. 

I've tracked down the root cause and filed an issue with the Chromium git infra team here: https://bugs.chromium.org/p/chromium/issues/detail?id=741105

**Comment by brendankenny** [comment]
I believe this has been resolved (though the crbug hasn't been)

**Comment by paulirish** [comment]
True. I will leave it open as I imagine it's very possible their mirroring infra can lag behind again sometime.
