### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by rcpcooper** [GoogleChrome/lighthouse#2679]
Hi,

When trying to install I get this message:

> **An error has occured**
> There was a problem adding the item to Chrome. Please refresh the page and try again.
> Image decode failed

I've tried several times and have gotten the same error. I also checked and saw that my pc is compatible.

**Comment by midzer** [comment]
@rcpcooper Did you install lighthouse extension directly from WebStore in Chome?

~3h ago i've installed lighthouse in Chromium v59 without any issues from there.

**Comment by rcpcooper** [comment]
@midzer Thanks for your reply. Yes, I tried installing from the webstore, here is the link https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en

**Comment by rcpcooper** [comment]
@midzer I figured it out. I'm in Brazil and when clicking to add to chrome, generates that error. I connected to a VPN to seem like I am in the US and did not have any issues.

**Comment by paulirish** [comment]
Very odd! But @rcpcooper thanks very much for (seemingly) joining Github just to report this issue! 

Really appreciate it.
