### ISSUE TITLE
launcher: Chrome-finder is grabbing old homebrew chromes

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2683]
I have a canary installed in this path: `/Users/paulirish/.homebrew/Caskroom/google-chrome-canary/latest/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary`

Unfortunately, this Canary is really old. And I have another Canary installed in `/Applications/` that is my primary and it's up to date.

Prioritization-wise, it'd make sense here to favor the `/Applications/` one above a homebrew install.  I do believe a previous @paulirish wanted the reverse which is why we're in this state. 😁

**Comment by wardpeet** [comment]
that's a quicky :)
