### ISSUE TITLE
Extension shows -1 for Speed Index

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#269]
Bit of digging suggests it's to do with the DevTools model stuff:

<img width="292" alt="screen shot 2016-05-04 at 12 30 38 pm" src="https://cloud.githubusercontent.com/assets/617438/15012901/1fae545e-11f4-11e6-8e6f-3b2b216c6921.png">

**Comment by paulirish** [comment]
Yup. devtools timeline model.

sorted out a few issues, but more remain.

Right now stuck here:

![image](https://cloud.githubusercontent.com/assets/39191/15039053/330ff240-125e-11e6-9a82-28d9a176e318.png)


fs.readfilesync isn't a function.

:/

This'll take some work.

**Comment by paullewis** [comment]
Taken a totally different route to fixing this >:]
