### ISSUE TITLE
Feature request: non-applicable audits

### ISSUE THREAD

**Issue by joeyparrish** [GoogleChrome/lighthouse#2690]
I would like to be able to write an audit which can be skipped in the report.  For example, I'm auditing JS libraries and looking for things that can be upgraded.  If those libraries are not used, it would be nice to be able to return a result with something like `skip: true` in it.  That audit would then not show up in the report.

Is there some way to do this today?  Would it be trivial to add a flag for this?  Is there another way I should be thinking about this problem?

CC: @hbengali

**Comment by patrickhulce** [comment]
Great idea @joeyparrish! We'll need to do some thinking about the appropriate UX here.

cc: @vinamratasingal

**Comment by joeyparrish** [comment]
Thanks!

**Comment by paulirish** [comment]
Idea: in addition to adding a `nonApplicable` flag to auditResults, I'm thinking we should provide a text `nonApplicableReason` so each can explain why. e.g. "No forms found on the page", etc.

**Comment by vinamratasingal** [comment]
Closing in favor of the umbrella issue.
