### ISSUE TITLE
Ignore assets from an extension in text compression audit

### ISSUE THREAD

**Issue by grappler** [GoogleChrome/lighthouse#2696]
I have the [Google Dictionary](https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja?hl=en) installed and when I run Lighthouse I get a message for `/content.min.css` text compression is not enabled.

It would be cool if Lighthouse could know what assets are being loaded by chrome extensions and which are being loaded by the site.

Lighthouse 2.2.1

**Comment by midzer** [comment]
Yeah, somehow installed extensions which alter DOM in any way interfere with lighthouse scanning process.

This might be not the case in Chromium 60 any more when lighthouse is directly integrated into the browser.

**Comment by patrickhulce** [comment]
good catch @grappler thanks for the report! It's not be possible to avoid false positives for all extension activity, but this is an easy case we're not covering.

We really just need to check that the scheme is not `chrome-extension` [here](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/uses-request-compression.js#L51) if anyone is interested in taking this up :)

**Comment by arturmiz** [comment]
I volunteer to take a look on this one :man_technologist:

**Comment by patrickhulce** [comment]
awesome @arturmiz let us know if you have any questions!
