### ISSUE TITLE
short_name shouldn't be required

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/lighthouse#2698]
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/webapp-install-banner.js#L49

If the `name` property is short enough, you don't need `short_name`. The test should reflect this.

This is either a regression of https://github.com/GoogleChrome/lighthouse/issues/348, or wasn't fixed.

**Comment by jakearchibald** [comment]
Also in https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/manifest-short-name-length.js

**Comment by patrickhulce** [comment]
Yeah looks like in the refactor into https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/computed/manifest-values.js the fixed logic stopped being used even though the code is still there, looks like all we need to do is replace `hasShortName` with `shortNameLength`?

**Comment by paulirish** [comment]
related bit: #686
