### ISSUE TITLE
Node version 4 and ES5 support?

### ISSUE THREAD

**Issue by bliu23** [GoogleChrome/lighthouse#2708]
Chrome Launcher does not support Node v4.8.1 nor does it support ES5. Are there plans for this or are there any workarounds for applications written in ES5?

**Comment by brendankenny** [comment]
We could explore workarounds (suggestions/advice welcome!) for those sticking to earlier versions of Node, but generally the policy is to keep support at the current [Node LTS version](https://github.com/nodejs/LTS) (currently Node v6).

**Comment by patrickhulce** [comment]
> We could explore workarounds for those sticking to earlier versions of Node (suggestions/advice welcome!)

Any objections to just flipping the target in tsconfig to es5?

**Comment by brendankenny** [comment]
oh, good point, just the launcher. The generated code is already pretty ugly, couldn't get much worse :)

**Comment by samccone** [comment]
we will need to add 4.x to our testing matrix.
https://github.com/GoogleChrome/lighthouse/blob/master/.travis.yml

I am -1 to supporting node version outside of LTS though and would prefer to be inline with lighthouse.

**Comment by wardpeet** [comment]
@bliu23 If you want I can help you setup chrome-launcher for node 4 so you can build it yourself, of course it would be some manual work you'll have to do each time we update the launcher

**Comment by bliu23** [comment]
That would be great actually. An upgrade to Node 6 is on the drawing board, but we'll definitely need a fix until then.
