### ISSUE TITLE
lighthouse opens chrome with about:blank tabs

### ISSUE THREAD

**Issue by guilhermevrs** [GoogleChrome/lighthouse#2711]
**Initial URL:** https://developers.google.com/web/tools/lighthouse/
**Chrome Version:** 61.0.3160.0

When lauching
`./node_modules/.bin/lighthouse https://developers.google.com/web/tools/lighthouse/`

I get the following:
```
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +2ms
  ChromeLauncher Waiting for browser...√ +510ms
```
But a chrome canary window opens with three tabs untitled tabs. The first with the path of my chrome executable (e.g. file:///C:/Users/username/AppData/Local/Google/Chrome%20SxS/Application/61.0.3160.0) and the rest with about:blank

![image](https://user-images.githubusercontent.com/1570567/28360493-dcb7bebe-6c75-11e7-830a-974c1f97e9a8.png)

I can't open the DevTools on it.
I have tried to use remote debugging, but the "Inspected pages" shows nothing.

I have tried using programatically, but no luck either. Same results

Windows 7 x64
Lighthouse version: 2.2.1
Node version: 6.10.3

**Comment by guilhermevrs** [comment]
Fixed using --chrome-flags="--no-sandbox"

**Comment by paulirish** [comment]
That's unexpected. I want to keep this open while we investigate more on windows.

Thanks!
