### ISSUE TITLE
Audit reports false compression hint in case auf brotli encoded content

### ISSUE THREAD

**Issue by skohlmann** [GoogleChrome/lighthouse#2712]
Chrome Version 59.0.3071.115 (Offizieller Build) (64-Bit), Mac OS 10.11.6 (15G1004) reports that gzip compression will reduce the size of the files by 91kb. As you see in the attached images Facebook served the files with brotli compression. Compresses with gzip the file has a size of 14103 byte with brotli of 12461 byte.

The current behavior can irritate and lead to incorrect measures.

Requested behavior: In case of brotli compression, don't report in the compression part of the audit.

![gzip compression optimisation](https://user-images.githubusercontent.com/12640595/28383660-3c96d9fe-6cc2-11e7-8bed-3ec559444ca7.jpg)
![network request with brotli](https://user-images.githubusercontent.com/12640595/28383661-3c9c36ec-6cc2-11e7-8ea2-82010cf40bf8.jpg)

**Comment by patrickhulce** [comment]
@skohlmann the screenshots you've shared are from the legacy audits panel that is not driven by Lighthouse, are you seeing the same issue with a report using Lighthouse? (Either with the extension, CLI, and Audits panel in Chrome Canary?)

**Comment by skohlmann** [comment]
HChecked it with Canary. No, problem is not there. Sorry for steeling your time. Doesn't know the difference.
