### ISSUE TITLE
Why is it necessary to use disabled attribute in link tags for Performance enhancement?

### ISSUE THREAD

**Issue by PhilipTheVictor** [GoogleChrome/lighthouse#2717]
What is the explanation behind the usage of disabled attribute on link tag to enhance performance according to lighthouse test reports? Will disabled not disable the link and styles will not be loaded ? Also by usage of media tag how will performance be optimized?

**Comment by paulirish** [comment]
You're talking about https://developers.google.com/web/tools/lighthouse/audits/blocking-resources ?

Not sure exactly what you're asking... 

If a `<link rel=stylesheet` has `disabled` on it, it's filtered out of consideration for the audit. So we ignore disabled stylesheets, just like the browser does.

:)

**Comment by PhilipTheVictor** [comment]
Yes. I am a bit confused as said in the documentation you mentioned above. If a link tag is disabled then it wouldn't work so if we don't want a link to work why would we include it into our project?
