### ISSUE TITLE
Performance inconsistency between Lighthouse and Chrome DevTools

### ISSUE THREAD

**Issue by govis** [GoogleChrome/lighthouse#2719]
Performance metrics from Lighthouse for a Polymer 2 app don't seem to reconcile with those from Chrome DevTools. For example lighthouse reports over 14,000ms to interactive whereas Performance tab in DevTools indicates completion of script execution and a full render at under 5,000ms. What could be a reason for such discrepancy? Attached zip contains both reports:
[report.zip](https://github.com/GoogleChrome/lighthouse/files/1163185/report.zip)

**Comment by patrickhulce** [comment]
@govis the trace you uploaded from DevTools doesn't seem to have the correct throttling enabled.
![image](https://user-images.githubusercontent.com/2301202/28437629-30dcf2a4-6d50-11e7-84cc-a6c860db308e.png)

The performance insights from Lighthouse are designed to show you how your site would perform in typical mobile conditions, and we apply the "Fast 3G" network and "4x Slowdown" CPU throttling settings you'll find in Canary's Performance tab.

**Comment by govis** [comment]
That makes sense, Thanks for explaining.
