### ISSUE TITLE
Un-explicable issue

### ISSUE THREAD

**Issue by Whiteseeker** [GoogleChrome/lighthouse#272]
When I use the chrome extension with this url:
https://whiteseeker.github.io/ everything is green

When I use it with that URL:
https://whiteseeker.github.io/mobile/game/2016/04/16/the-greedy-cave.html 
It complains the service worker doesn't register, but it does, and it's the same code on both pages :/

I can't spot the issue, maybe it's in the website but it really is the same code executing :/

**Comment by paullewis** [comment]
Thanks for the report. Looking into it.

**Comment by paullewis** [comment]
I think I've found the issue, just might take me a little while to get the PR in. On it, though.

**Comment by Whiteseeker** [comment]
Cool ! Thx for letting me know (^_^). I was worried something was wrong on the website. Again thank you very much (^_^)

**Comment by paullewis** [comment]
Tested this as part of #276; when it lands you should be good to go!
