### ISSUE TITLE
Online viewer no longer loads gists

### ISSUE THREAD

**Issue by timgupta** [GoogleChrome/lighthouse#2722]
I used to be able to load a report from a JSON blob stored in a github gist, like so (I had this URL saved in a historical performance document):
https://googlechrome.github.io/lighthouse/viewer/?gist=f6370e1779fba9c1243440b22e32083d

Now it says it "gist f6370e1779fba9c1243440b22e32083d does not contain a Lighthouse report". Is there a different way to format the URL now, or is something broken?

**Comment by patrickhulce** [comment]
The viewer will only currently accept gists that contain a file ending in ".lighthouse.report.json" but yours just has lighthouse-baseline.json (this was a breaking change from the previous behavior where the first file was always used)

**Comment by paulirish** [comment]
is it safe for us to support first .json file in the gist?

alternatively, we can always sort by priority with some more work.

**Comment by patrickhulce** [comment]
Seems fine to me, @brendankenny any insight on why the [change](https://github.com/GoogleChrome/lighthouse/pull/2521/files#diff-cafb418ca3e8be6bd144763f724ef00dR116) was made?

**Comment by brendankenny** [comment]
We could, but I made the change on purpose in case you have a trace in there too, for instance, and it happened to come first. However, we could do the real fix and inspect every json file in the gist and take the first one that looks like a lighthouse report.

Even if we change it, though, this gist still won't work because it's a 1.6.5 report and unfortunately we don't have backwards compatibility to 1.x reports (bug is covered by second top level checkbox in #2591).

**Comment by timgupta** [comment]
Ah ok, good to know about the filename @patrickhulce. Is this something we could add to the docs at https://developers.google.com/web/tools/lighthouse/#gists ? Otherwise, I'm not sure how people will know that the filename needs to now be in this format.

I'd be happy to add it and create a PR, but it seems maybe the docs are not an open source repo? If I'm wrong there, let me know and I'll create the PR.

**Comment by paulirish** [comment]
@timgupta how about the change i made in https://github.com/GoogleChrome/lighthouse/pull/2724 ?

**Comment by paulirish** [comment]
and fwiw here's the docs page you linked on github: https://github.com/google/WebFundamentals/blob/master/src/content/en/tools/lighthouse/index.md

**Comment by timgupta** [comment]
Ah yes @paulirish that will help a lot. If you don't mind I'll do a PR into the docs too.

**Comment by paulirish** [comment]
@timgupta yah sounds awesome to me. be sure to update the `updated_on` date at the top of the markdown. i always forget that part. :)
