### ISSUE TITLE
Full audit takes an inordinate amount of time to complete, and many audits fail

### ISSUE THREAD

**Issue by rafistrauss** [GoogleChrome/lighthouse#2723]
Hi, recent audits have taken between 5-15 minutes or longer to complete. This occurs both when running Audits through the extension and through the Audit tab in Chrome Canary.

I'm also getting the following audit errors:

- Audit error: trace not at least 5 seconds longer than FMP
- Audit error: Required Accessibility gatherer encountered an error: The asynchronous expression exceeded the allotted time of 60s
(All of the Accessibility checks failed with this error)

Here is the report: https://googlechrome.github.io/lighthouse/viewer/?gist=8b82c7175f39d304ab1b42674022e8ff

**Comment by patrickhulce** [comment]
@rafistrauss could you confirm you see run times of 15 *minutes*?

All of these errors indicate a very large and slow page, but nothing that should last 15 minutes.
The performance errors are all expected given the size of your assets. For example, there's a single SVG file that's over 8 MB which would take ~40 seconds to download on a fast 3G connection. Consider following the guidance in the "Opportunities" section to see improvement there.

For the accessibility gatherer issue, could you try running [axe](https://github.com/dequelabs/axe-core) on your page by itself and let us know if you experience a similar issue?

**Comment by rafistrauss** [comment]
@patrickhulce Confirmed - I just reran Lighthouse on https://shop.polymer-project.org/ to make sure it wasn't just my page and it clocked in at 14 minutes and 43 seconds. 

https://googlechrome.github.io/lighthouse/viewer/?gist=23e5ed1b5cfdd866113c089bb2ccfa14

As the Polymer Shop demo is one of the demonstrative examples of PWA's, I figure setting up axe for my page is unnecessary. 
I'm well aware that my page is still pretty far from achieving even halfway decent overall results and still has plenty of placeholder content - I just wanted to use Lighthouse to check certain metrics at this stage.

**Comment by patrickhulce** [comment]
Ah that same 8 MB svg strikes again :) what does the run time look like if you disable the "Emojione" extension that seems to be injecting massive data into the page?

**Comment by rafistrauss** [comment]
Wow... it shoots all the way back down. What a catch, thanks!!!
