### ISSUE TITLE
Add chrome host as parameter 

### ISSUE THREAD

**Issue by salvocanna** [GoogleChrome/lighthouse#2727]
I'm looking to use lighthouse (which is really well done) programmatically integrating it inside another node app and I'm having some issues as the node app and headless-chrome are running inside two different containers.

[This](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/connections/cri.js#L13-L26) assumes chrome is always located on `localhost` and allows you to change only the port.

Would it make sense to call the constructor with a config object like `{ host: DEFAULT_HOST, port: DEFAULT_PORT }` or I'm just doing something weird and there's another way to specify the host?

**Comment by patrickhulce** [comment]
Not doing anything wrong, I believe you're just the first request we've had for this :)

Makes sense to have as an option though it could be plumbed through as `port` is now. Any chance you'd want to take a swing at a PR?

**Comment by FrederickGeek8** [comment]
I believe the pull request I just created has fulfilled your request. You might want to check it out and make sure that everything is as you want it.

Additionally, you may want to note that the `hostname` is the second parameter of the constructor function. I made this choice as to not disrupt and current implementations of CriConnection.

**Comment by salvocanna** [comment]
Sorry for such a late answer.
From my point of view the host should take precedence over the port, so I just moved the config in the constructor to an object with defaults.
I've also made a pull request (#2793) - whichever makes more sense
