### ISSUE TITLE
Can't Scroll Lighthouse results

### ISSUE THREAD

**Issue by keithstric** [GoogleChrome/lighthouse#2731]
Using Google Canary Audits panel, perform a lighthouse audit. Unable to scroll the result page.

OS: MacOS 10.12.5
Browser: Google Canary 62.0.3165.0 64 Bit

**Comment by paulirish** [comment]
Thanks for reporting. :) 
upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=747231

Fix coming soon: https://chromium-review.googlesource.com/c/580500/

**Comment by keithstric** [comment]
Thanks Paul! I looked all over for a duplicate issue before submitting and didn't find it. Which I found odd that no one reported it.
