### ISSUE TITLE
Audit error: Required EventListeners gatherer encountered an error: Protocol error (DOM.resolveNode): No node with given id found

### ISSUE THREAD

**Issue by cyberixae** [GoogleChrome/lighthouse#2736]
Audit error: Required EventListeners gatherer encountered an error: Protocol error (DOM.resolveNode): No node with given id found

I get this error while auditing https://dwst.github.io/

**Comment by patrickhulce** [comment]
Thanks for the report @cyberixae! I'm unable to reproduce on the latest version, but it seems like it'd be a good idea to not fail the whole audit if a single DOM node ceased existing :)

Future bug fixers can probably just add a catch to the inner loop here
https://github.com/GoogleChrome/lighthouse/blob/bc6783b6d0f4ab94b0b90c2058d7dffa8f592db8/lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js#L103-L108

**Comment by webcarrot** [comment]
Same error on: https://www.cyclosport.pl
Lighthouse 3.0.0-beta.0
Chrome:  67.0.3396.62
OS: Linux

**Comment by brendankenny** [comment]
we don't have an `all-event-listeners.js` anymore, we moved to using console violations for this, so it's no longer an issue :)
