### ISSUE TITLE
Config: Add option for setting extra HTTP Headers

### ISSUE THREAD

**Issue by pmeenan** [GoogleChrome/lighthouse#2746]
It is useful to provide custom HTTP headers for configuring server settings (some accelerator providers use it to turn features on or off), to provide BASIC Auth headers or in some cases to provide session cookies to bypass a login.

It would be helpful to be able to pass a config of headers to override and if present pass it through to Network.setExtraHTTPHeaders when the emulation configs are done.

**Comment by patrickhulce** [comment]
related #1418

**Comment by kaycebasques** [comment]
Somebody requested this on SO: https://stackoverflow.com/questions/46584644/sending-headers-with-lighthouse

**Comment by paulirish** [comment]
now fixed via #3732  

Check out the docs for `--extra-headers` in the readme or `lighthouse --help`
