### ISSUE TITLE
Extension Error: Protocol error (Emulation.setCPUThrottlingRate): Unknown deb

### ISSUE THREAD

**Issue by ericis** [GoogleChrome/lighthouse#2752]
The error below is misleading. Please watch the [two-pass report generation video](https://youtu.be/u37QrsJ_BOQ) I made demonstrating the problem and how the resulting error changes, but is generally in the same logical area of generating the report.

**Lighthouse Version**: 2.3.0
**Chrome Version**: 59.0.3071.115
**Initial URL**: https://www.aa.com/homePage.do
**Error Message**: Protocol error (Emulation.setCPUThrottlingRate): Unknown debugger protocol error.
**Stack Trace**:
```
Error: Protocol error (Emulation.setCPUThrottlingRate): Unknown debugger protocol error.
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9907:25)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by ericis** [comment]
This was caused by having [HP Network Assistant](http://www8.hp.com/us/en/campaigns/hpsupportassistant/hpsupport.html) installed which adds the HP [Network Check Launcher extension](https://chrome.google.com/webstore/detail/hp-network-check-launcher/jkfpchpiljkaemlpmpebnglgkomamfeo) for Google Chrome.

Disabling the extension allowed the Lighthouse extension to generate the report successfully.

**Comment by brendankenny** [comment]
Interesting! Thanks for tracking this down.

I wonder if we can detect that an extension is preventing us from throttling the CPU so Lighthouse can warn.

**Comment by ericis** [comment]
Thanks @brendankenny. After further research, it's not actually related to the CPU Throttling function call. There are some redirects during the Lighthouse report generation and possibly AJAX calls and something appears to be failing.

I've added a video that shows two passes on the website and both fail with different errors. Hopefully the timing will help the team find where this is happening. Guessing there is a redirect or HTTP request to a URL that doesn't exist, HP Network Check Launcher complains with a valid HTML page, and Lighthouse doesn't expect the HTML content output from HP Network Check Launcher.

**Comment by brendankenny** [comment]
Looks like this is a different manifestation of #1942. Unfortunately not much we can do about that.
