### ISSUE TITLE
Will multi passes get multi audits results？

### ISSUE THREAD

**Issue by meixg** [GoogleChrome/lighthouse#2764]
the Lighthouse Configuration say that 

> Each entry in the passes array represents one load of the page

and i can see the multi `artifacts.devtoolsLogs` and `artifacts.traces`. but there is only one result per audits. I wonder which passes the audits are come from?

How can i generate multi audits from multi passes? thanks!

------

sorry to ask in here, btw.

**Comment by patrickhulce** [comment]
Great question. Unfortunately right now the devtoolsLogs and traces are special cased to support multiple passes (though no audit actually takes advantage of this fact yet), and you're correct the audits are a fixed list and not per pass. Additionally, you can only use a gatherer once across your passes.

If you want to report information from each pass as separate audits you'll have to manually create distinct audit entries that use the information from a distinct gatherer entry. You can read up more on adding a custom audit/gatherer [here](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit).

Alternatively, you can run Lighthouse multiple times with different configs [programmatically](https://github.com/GoogleChrome/lighthouse/tree/master/docs#using-programmatically). This is probably the simpler approach, but you will not receive all the information in the same report.
