### ISSUE TITLE
PassiveEventListeners Audit: remove dupe entries

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#2768]
Seeing duplicate entries in the passive event listener audit on chromestatus.com:

<img width="810" alt="screen shot 2017-07-26 at 9 07 33 am" src="https://user-images.githubusercontent.com/238208/28682531-fd1933d6-7305-11e7-8139-5bf1d4b54419.png">

@patrickhulce is this from the move to violation-audit? Are these actually different and we just don't have a col number?

**Comment by patrickhulce** [comment]
>  is this from the move to violation-audit? Are these actually different and we just don't have a col number?

Yeah we're reporting everything we get from the violations (doesn't report column) and there are many, if it's incorrect we should file a crbug
![image](https://user-images.githubusercontent.com/2301202/28689130-632dc84a-72c9-11e7-99f5-69e6632da0ee.png)

**Comment by paulirish** [comment]
We need column data in the violation. It's reported here: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/events/EventTarget.cpp?type=cs&q=add+non-passive+event&sq=package:chromium&l=297

**Comment by brendankenny** [comment]
well the good news is that this got deduped at some point on the Chrome side :)
