### ISSUE TITLE
[Feature] Pass traces programatically

### ISSUE THREAD

**Issue by guilhermevrs** [GoogleChrome/lighthouse#2769]
First of all, it's awesome you have thought about trace processing. That way we can do whatever interaction we need in the web app before running the audits. 

I have looked into the code and the Config class run a require.resolve for the traces. Also we can pass the config as an object when running lighthouse programmatically. 

Would it be possible to pass the traces programmatically as well?

That would enable us to run the whole process automatically without passing through the file system.  

_Sent from my Samsung SM-A500FU using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by paulirish** [comment]
@guilhermevrs this is interesting.

I suppose what you're suggesting is that you could include the trace contents inline within the config you pass to lighthouse?

This is probably not useful for most folks, so we're not going to set this as a high priority. If you're interested in writing the PR for it, please do. If you're not, we'll probably close this. SG?

**Comment by brendankenny** [comment]
The solution to this is now `-A` with a path pointing at the trace. See https://github.com/GoogleChrome/lighthouse#lifecycle-examples
