### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by Guymestef** [GoogleChrome/lighthouse#2776]
**Initial URL**: https://localhost:44384/todo-list
**Chrome Version**: 60.0.3112.78
**Error Message**: Unable to load the page: net::ERR_CONNECTION_RESET
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_CONNECTION_RESET
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by Guymestef** [comment]
The audit was working before I switched to https (vs2017 + IIS Express). The SSL certificate was auto-generated by vs2017. So I guess it's a problem with certificate validation...

**Comment by wardpeet** [comment]
@Guymestef can you reproduce with cli or extension?

Normally devtools shouldn't make a fuss about it if you "whitelisted" the ssl cert

**Comment by Guymestef** [comment]
With the extension the analysis start and after some time it's hanging up
![entension-hanging](https://user-images.githubusercontent.com/685890/28722056-a9b9bae6-73b2-11e7-870a-29335aea5573.png)

With the CLI, the analysis succeed to complete, but Progressive Web App and Performance are wrong.
On the console logs, we can see a "time out waiting for page load".

![image](https://user-images.githubusercontent.com/685890/28722161-13887d90-73b3-11e7-8f4c-2649ab811708.png)
![image](https://user-images.githubusercontent.com/685890/28722172-1d6ca020-73b3-11e7-9d32-f475e498d54a.png)
![image](https://user-images.githubusercontent.com/685890/28722223-47166190-73b3-11e7-8f33-ad93e1a35b9c.png)
![image](https://user-images.githubusercontent.com/685890/28722266-6e7a6286-73b3-11e7-9705-d5178dff145a.png)

I don't know what vs2017 did with the certificate, so I don't think it is whitelisted. I know that node is not accepting all the certificates accepted by chrome or other browsers. So the request is probably crashing with an error like CERT_UNTRUSTED or UNABLE_TO_VERIFY_LEAF_SIGNATURE.

**Comment by wardpeet** [comment]
Does iis also accept http requests or isn't it configured to host your site?

smells a bit like #1457

**Comment by Guymestef** [comment]
Only https but http is redirected to https with a code 301
