### ISSUE TITLE
Request: print summary/collapsed view

### ISSUE THREAD

**Issue by ScottBeeson** [GoogleChrome/lighthouse#2782]
The default view I'm presented with is about 2 pages and is perfect.  When I click print from the share menu, it is a 28 page document.

I would like an option to print the main/collapsed view.

**Comment by patrickhulce** [comment]
Feels like we should probably not auto-expand anything for File > Print/Share > Print, and change current print to Share > Print Expanded

**Comment by paulirish** [comment]
Anybody interested in implemented @patrickhulce's proposal above?

**Comment by karanjthakkar** [comment]
@paulirish I'd like to take that up. Wanted to confirm a few things:

1. <img width="216" alt="screen shot 2017-10-16 at 3 15 37 pm" src="https://user-images.githubusercontent.com/1824298/31605811-e6eb4766-b284-11e7-94c7-af63ed636dce.png">

^ the functionality for this will stay as is. Just the text will change from `Print...` to `Print Expanded`

2. The `Cmd + P`, etc. system print shortcut which currently expands, should not auto expand.

3. <img width="251" alt="screen shot 2017-10-16 at 3 17 40 pm" src="https://user-images.githubusercontent.com/1824298/31605893-2cf8e25e-b285-11e7-9899-3150fc093664.png">

^ This should also not auto expand. We don't have handling for this iiuc inside `lighthouse-core/report/v2/renderer/report-ui-features.js`. So this would just print whatever is expanded or collapsed on screen.

Sounds right? If yes, then I'll get 2 and 3 done and send across a PR :)

**Comment by patrickhulce** [comment]
That sounds reasonable to me @karanjthakkar! I'em not sure I understand your `3` though. Isn't that the same as `cmd + P`? Keeping report as is, whatever is expanded or collapsed on screen, sounds like reasonable behavior for default print 👍

**Comment by vinamratasingal** [comment]
To make sure I understand what's going on: we are changing the default print option to "print expanded" and then also ensuring that when a user does the system print, that they only print the summary view (i.e. 2 page report) and not the 28 page report, yes? 

If the above is true, I would love to see in the share menu both a "print summary view" (or "print current view") and "print expanded view." What additional information gets printed out in the expanded view @patrickhulce ?
