### ISSUE TITLE
Failures: Manifest start_url is not cached by a Service Worker.

### ISSUE THREAD

**Issue by mbj36** [GoogleChrome/lighthouse#2783]
Hello @paulirish

I am running this PWA in Production https://mbj36.github.io/community-app/?baseApiUrl=https://demo.openmf.org#/ and i am getting audit failure `Failures: Manifest start_url is not cached by a Service Worker.` while generating report on lighthouse

It seems that i have cached start_url but still it shows the audit failure 

![selection_053](https://user-images.githubusercontent.com/9936881/28738658-5ef79f04-7412-11e7-9e41-16b9a5a0c99a.png)

**Comment by patrickhulce** [comment]
@mbj36 it seems as though a service worker is not being requested or installed when I visit the page? No request for the `sw.js` is present in network panel either. Perhaps there's a conditional in your service worker registration logic that doesn't always pass?

![image](https://user-images.githubusercontent.com/2301202/31091198-092ae146-a75f-11e7-9f9c-e8a52685012c.png)

**Comment by mbj36** [comment]
I am able to solve this problem. I was not fetching so error occured. 

I have deployed another version on mentioned url
