### ISSUE TITLE
Speedindex reported as -1 

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#280]
Version 0.6.1 on events.google.com/io2016

<img width="908" alt="screen shot 2016-05-04 at 8 12 51 pm" src="https://cloud.githubusercontent.com/assets/238208/15035232/a56143c8-1234-11e6-88c7-cbb9070d0078.png">

**Comment by paullewis** [comment]
Dupe of #269. I think @paulirish is on this one :)
