### ISSUE TITLE
Output does not log all resources for 'Has enormous network payloads Diagnostic'

### ISSUE THREAD

**Issue by emilycoco** [GoogleChrome/lighthouse#2807]
The report for 'Has enormous network payloads' diagnostic lists several resources and their sizes, but not all resources loaded on the page. I can tell the resource in question is recognized by lighthouse because it is used in the 'Enable Text Compression' recommendation, but I would expect it to be part of the network payload check as well. Are only the largest resources listed there?

**Comment by patrickhulce** [comment]
@emilycoco you are correct only the [10 largest network payloads](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/total-byte-weight.js#L67) are displayed by this audit, but the total value reported is still the sum of every completed network request.

**Comment by emilycoco** [comment]
@patrickhulce thanks for clarifying!
