### ISSUE TITLE
Documentation: How is the optimal and the median value calculated?

### ISSUE THREAD

**Issue by jhnns** [GoogleChrome/lighthouse#2812]
Hey all 👋 ,

thanks for this awesome tool. When I started to try it out, I was wondering what values are considered to be "good". They are obviously related to the RAIL model, but some of the `optimalValue`s look like arbitrary values from my point of view. 

After digging the source code, I found [this comment about the audit parameters](https://github.com/GoogleChrome/lighthouse/blob/fadaef95137181aa41ed44fd78f17d3a8b85a2c3/lighthouse-core/audits/first-meaningful-paint.js#L12-L15). After doing a bit research, I concluded that CDF is the [cumulative distribution function](https://en.wikipedia.org/wiki/Cumulative_distribution_function).

Could you elaborate on the reasoning behind this formula? I could imagine that more developers are interested in this topic.

**Comment by addyosmani** [comment]
cc @kaycebasques 

A few folks have pinged me this week asking how the current medians are calculated and walking them through the source to our metric audits has been necessary. It would be 💯 if there was a note in the docs that clarify where LH uses the CDF and why _some_ of the numbers used are not quite so arbitrary.

**Comment by patrickhulce** [comment]
will be fixed by #3436

**Comment by vinamratasingal** [comment]
Given that we now have scoring docs, this question becomes obsolete... only question is, can we delete values to optimal/median values within the code itself?

**Comment by vinamratasingal** [comment]
Patrick will delete reference to optimal/median values within the code.
