### ISSUE TITLE
Chrome flag "--host-resolver-rules" ignored

### ISSUE THREAD

**Issue by AltF4Top** [GoogleChrome/lighthouse#2817]
When passing chrome flag 

> --host-resolver-rules='MAP www.example.org:443 127.0.0.1:8443'

to the --chrome-flags flag, lighthouse requests the original https://www.example.org/ as usual, simply ignoring the host-resolving rule.

I guess there is some code like split(' ') used so that flags which contain inner space will be divided and discarded.

I also wonder whether there is a way to bypass this problem.

**Comment by patrickhulce** [comment]
Hey there @AltF4Top thanks for the report! Indeed this is a current limitation and is captured by #2753, #2754 is in progress to address this.

**Comment by asilvas** [comment]
@AltF4Top ever get this working? `host-resolver-rules` seems to have no effect.
