### ISSUE TITLE
Weird behavior when running from DevTools Audits panel

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#2820]
1. Open a new tab and go to https://www.google.com
2. Go to the Audits panel in DevTools and run the LH audit

Half the time it audits google.com as expected but the other half of the time I get audits for `https://clients5.google.com/pagead/drt/dn/` which is also the URL I'm left on after the audit completes. That's also the URL of an iframe dynamically injected into the page.

Audit results: https://googlechrome.github.io/lighthouse/viewer/?gist=0c7ef00ba7ed5a1fb0dc587d432b50dd

The Chrome extension seems to behave normally.

**Comment by patrickhulce** [comment]
Also discussed in https://bugs.chromium.org/p/chromium/issues/detail?id=750325, should be fixed by https://chromium-review.googlesource.com/c/570921

**Comment by rileyjshaw** [comment]
*Chrome version:* 60.0.3112.101 (Official Build) (64-bit)

If you're looking for more test cases, I think the bug also occurs on https://www.khanacademy.org/science/physics/circuits-topic/circuits-resistance/v/circuits-part-1 (redirects to YouTube)

**Comment by patrickhulce** [comment]
Fixed in m61
