### ISSUE TITLE
Slow Completion Time w/ headless chrome-launcher on Windows

### ISSUE THREAD

**Issue by dk0r** [GoogleChrome/lighthouse#2822]
**Issue**:  Incurred long completion times for trivial/shallow dom traversal via chrome-launcher@0.3.2 and chrome-remote-interface@0.24.3 on chrome@60.0.3112.78beta (Windows 64-bit). 

**Solution**: Disable antivirus/firewall's ssl traffic monitoring:
**e.g.** Bitdefender > View Modules > Web Protection > Scan SSL
http://i.imgur.com/O4BLms7.gifv

**Comment by paulirish** [comment]
Your solution is indeed the right one.  :)

There's literally nothing we can do from the chrome-launcher side to help this. We can't opt-out of any system antivirus. :bowtie:
