### ISSUE TITLE
Do not use Emulation.setVisibleSize

### ISSUE THREAD

**Issue by dgozman** [GoogleChrome/lighthouse#2831]
It's not needed anymore, since setDeviceMetricsOverride does it automatically.
We are going to remove setVisibleSize soon, so we better stop calling it from lighthouse.

------

EDIT: dmitry indicates this was removed in m61, but we need to verify that.
verified that the protocol changes are in 61.0.3155.0

**Comment by brendankenny** [comment]
Hmm, was `setDeviceMetricsOverride` fixed after a screenshot bug a few months ago? We added `setVisibleSize` in #1839 when we our screenshots weren't cropped to the emulated viewport size. Not sure what the story was at the time (did we file a crbug? or is that WAI and we need to do something else for screenshots?)

@paulirish

**Comment by patrickhulce** [comment]
@brendankenny I think it was fixed recently to be unnecessary, so we might need to wait for m61 to hit stable before removing it entirely?

**Comment by dgozman** [comment]
That's correct, it was fixed recently. Might even have to wait for m62 to be on the safe side. I just filed this to not forget about cleanup opportunity.

**Comment by wardpeet** [comment]
@brendankenny @patrickhulce how do we feel to already beta test this with wrapping it around an if so we can test on canary or isn't this something we want.

```
if (chrome.version < 62) {
  setVisibleSize(...)
}
```
