### ISSUE TITLE
Request: chrome-launcher Change Log / Release

### ISSUE THREAD

**Issue by shellscape** [GoogleChrome/lighthouse#2833]
Just noticed that v0.4.0 of chrome-launcher was released 🎉  That's awesome! But I can't track down a changelog or release info for that version. And since the commit history for the repo is a mix of lighthouse and chrome-launcher, I'm struggling to put together a clear picture of what changed in the minor bump. Maybe I'm just a mook in this case (it's definitely possible), but an active changelog for the module would be fantastic. Food for thought?

**Comment by wardpeet** [comment]
That's not a problem at all, we can make one for sure.

I'll ask the others if we can set that up for ya.

**Comment by paulirish** [comment]
Aye! 

In the meantime, this URL is the best we got: https://github.com/GoogleChrome/lighthouse/commits/master/chrome-launcher

But, that said a proper changelog seems good.

**Comment by shellscape** [comment]
Thanks for getting to this folks! Much appreciated.
