### ISSUE TITLE
Blobs are being seen as insecure?

### ISSUE THREAD

**Issue by g5codyswartz** [GoogleChrome/lighthouse#2841]
I'm not sure where these are even coming from, but they're showing up to be "insecure" when I believe they shouldn't be.

Ex: `blob:https://sitename.com/9g7d6hd3-2de4-23fd-f6sj6g8uuy5t`

**Comment by patrickhulce** [comment]
@g5codyswartz what version of Lighthouse are you using? This should have been fixed by #2538

**Comment by g5codyswartz** [comment]
@patrickhulce I'm running Chrome v60 so that could surely be it as I imagine it hasn't been released into this version yet and will increment it's way out over time : ) 
```
Google Chrome | 60.0.3112.78 (Official Build) (64-bit)
-- | --
Revision | f901216ec1e383df23283fec9bc8f4e8b67aa0fb-refs/branch-heads/3112@{#671}
OS | Mac OS X
JavaScript | V8 6.0.286.44

```

**Comment by patrickhulce** [comment]
Ah yes that's a build of Lighthouse from May :) closing as this should be fixed (you can use Chrome Canary to get the latest behavior if you need to)
