### ISSUE TITLE
Is it possible to get audit values that match what is shown in the console network panel?

### ISSUE THREAD

**Issue by emilycoco** [GoogleChrome/lighthouse#2859]
When I run an audit, the load time for assets is very different from what I see in the console, (even on the same browser instance, page, user, etc) and I would like to know the differences in how those numbers are calculated, and if it's possible to get an audit that matches those values. I am using the total-byte-weight timing to compare to.

**Comment by benschwarz** [comment]
@emilycoco, by default Lighthouse will slow both the connection and CPU speed whilst performing an audit. 

If you want to run lighthouse without the slower cpu / network, you'll need to run it on your command line (`npm -g install lighthouse`). Use the `--disable-device-emulation` and / or `--disable-cpu-throttling`, `--disable-network-throttling` flags.

However, one of the motivations behind this is to have you testing sites with 'more real world conditions', so I'd encourage you to run with a mobile context more often.

**Comment by emilycoco** [comment]
@benschwarz Thanks for answering. I'm intending to use the throttling to get my final audit, but first I want to establish that I know what I'm measuring. Even running lighthouse with those flags in place, the end result seems pretty different for timing. Maybe it's a hard thing to calculate and has a wide margin of error?
Chrome Console:
<img width="1050" alt="screen shot 2017-08-06 at 5 26 08 pm" src="https://user-images.githubusercontent.com/5327571/29008486-c9dff1f2-7acc-11e7-98a8-dc0563b1d1f5.png">
Lighthouse result on same Chrome Instance:
lighthouse https://www.myurl.com --output json --port 51500 --perf --disable-device-emulation --disable-cpu-throttling --disable-network-throttling
 `
"total-byte-weight": {
      "score": 99,
      "displayValue": "Total size was 1,850 KB",
      "rawValue": 1894229,
      "optimalValue": "< 1,600 KB",
      "extendedInfo": {
        "value": {
          "results": [    
            {
              "url": ".../application.62108da8681fb430fd6e.js",
              "totalBytes": 299645,
              "totalKb": "293 KB",
              "totalMs": "620 ms"
            }
         ]
       }
     }
`

**Comment by patrickhulce** [comment]
@emilycoco the "total-byte-weight" audit timing is attempting to surface roughly how many milliseconds were spent *downloading* the bytes for the asset using your average total throughput. In the network panel screenshot above, this corresponds to what LH expects the blue portion of the bar to be on average (which is significantly less than the length of the entire bar reported in the "Time" column).

This is intended to line up with the rest of the perf opportunities reporting how much time you might shave off your load if you eliminated some bytes. We don't know that you can speed up your server response time or the distance of your servers to your users (everything that happens before the "content download" phase), but we know how your download time will be affected!

You can find out more about where time is spent for each network request by hovering over the bars in the waterfall to get a breakdown. On typical modern broadband connections, content download usually accounts for a small fraction of the overall request time.

![image](https://user-images.githubusercontent.com/2301202/29040504-299a4916-7b64-11e7-8585-2c49c9b42fad.png)

**Comment by emilycoco** [comment]
@patrickhulce Thanks for explaining, that makes sense.
