### ISSUE TITLE
ViewportDimensions gatherer should use built-in Promise.resolve

### ISSUE THREAD

**Issue by nightpool** [GoogleChrome/lighthouse#2871]
mac osx, lighthouse 2.3.0, chrome 62.0.3178.0 (Official Build) canary (64-bit), installed with `npm install -g lighthouse` and using `chrome-debug` to run canary

running with `lighthouse URL --port PORT --disable-device-emulation --disable-network-throttling --view`

port is the port I got from running chrome-debug.

here's the relevant log:

```
[...]
  status Evaluating: Content is sized correctly for the viewport +0ms
  Runner:warn ViewportDimensions gatherer, required by audit content-width, encountered an error: Promise.resolve is not a function +1ms
  content-width:warn Caught exception: Required ViewportDimensions gatherer encountered an error: Promise.resolve is not a function +0ms
[...]
  status Evaluating: Offscreen images +14ms
  Runner:warn ViewportDimensions gatherer, required by audit offscreen-images, encountered an error: Promise.resolve is not a function +0ms
  offscreen-images:warn Caught exception: Required ViewportDimensions gatherer encountered an error: Promise.resolve is not a function +0ms
[...]
  status Evaluating: Properly size images +0ms
  Runner:warn ViewportDimensions gatherer, required by audit uses-responsive-images, encountered an error: Promise.resolve is not a function +0ms
  uses-responsive-images:warn Caught exception: Required ViewportDimensions gatherer encountered an error: Promise.resolve is not a function +0ms
[...]
```

![audit failures](https://user-images.githubusercontent.com/233815/29048103-0471c3b0-7b9d-11e7-8ae5-38e7df3818f0.png)

**EDIT**: to be clear, I ran the same test on the same page using the Lighthouse chrome extension, and I didn't run into these errors (the audits returned information successfully)

**Comment by patrickhulce** [comment]
@nightpool does the URL you're running lighthouse on polyfill Promise incorrectly by chance?

**Comment by nightpool** [comment]
probably? It's not my site, which is why I didn't include it in the bug report

**Comment by nightpool** [comment]
I didn't notice this when running the same test with the chrome extension though

**Comment by nightpool** [comment]
ahhh it might be a difference in mobile/non-mobile js, since that was the other variable I was changing (and why I installed the CLI). 

let me test that....

**Comment by patrickhulce** [comment]
> However, the test runners should really be sandboxed in a way where a broken polyfill can't affect them, right?

Yes, this just diagnoses the error that it's not something more than the missing sandboxing. 👍

**Comment by patrickhulce** [comment]
For those who might want to jump in to fix this... :)

Short-term we can just use our cached native promise `window.__nativePromise.resolve` instead
Long-term we'll move over to [createIsolatedWorld](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-createIsolatedWorld) when the easy to use path hits Chrome stable.

**Comment by patrickhulce** [comment]
closing in favor of #2511
