### ISSUE TITLE
Devtools - Audit not working  

### ISSUE THREAD

**Issue by arangates** [GoogleChrome/lighthouse#2882]
Audits in Devtools is not working...It shows **Auditing your webpage** message and does not produce any result nor there are any errors.

**Comment by arangates** [comment]
Chrome Version (from the about:version page): Version 60.0.3112.78 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

Kernel version: Linux 4.10.0-30-generic
CPU architecture (32-bit / 64-bit): 64-bit

What steps will reproduce the problem?
(1)open Devtools 
(2)Navigate to Audits
(3)select Perform Audit

i did audit for this site https://vedhabase.firebaseapp.com

What is the expected result?

It should report with the audit results.

What happens instead?

Simply displays Auditing your webpage and nothing happens nor reports any error

**Comment by patrickhulce** [comment]
This happens every time for you? First run seemed to go smoothly

![image](https://user-images.githubusercontent.com/2301202/29087009-565a0318-7c29-11e7-94af-c92f8ac26130.png)

**Comment by arangates** [comment]
Perfect,..Alright... I'm really sorry the problem is with Chromium browser...Thank you.. I'm closing it now.
