### ISSUE TITLE
Audit error: Required Accessibility gatherer encountered an error: Unexpected anonymous AMD define.

### ISSUE THREAD

**Issue by thomas-darling** [GoogleChrome/lighthouse#2886]
When running Lighthouse on http://www.momondo.ie, we get this error for all Accessibility checks:

`Audit error: Required Accessibility gatherer encountered an error: Unexpected anonymous AMD define.`

The site is a SPA built on the Aurelia framework, and uses the System.js module loader.

**Comment by patrickhulce** [comment]
This will be resolved by #2511, closing in favor of that issue.
