### ISSUE TITLE
Diagnosis: Longest critical path chain

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#292]
Render-blocking resources that request additional render-blocking resources. (e.g. scripts that document.write()'s a script, which adds a stylesheet to the  head, which includes a @font-face rule)

Identifying the problem:

* Render-blocking resources == network requests with priority of {Medium, High, 
  VeryHigh}
* DevTools's [network request initiator 
  callstack](https://chromedevtools.github.io/debugger-protocol-viewer/Network/#type-Initiator) 
  indicates the initiating file.

Needs: critical path.

Calculating the total time cost:

* Grab all render-blocking resources. (Webfonts included with sync JS, and CSS)
* Identify dependency chains from DevTools initiator instrumentation.
* Each request's duration includes ExecuteScript or any subsequent RecalcStyle
* Chain durations == from first non-HTML blocking resources to last
* Last critical chain == last chain to complete before first meaningfulpaint. 
  Discard any following.
* Total duration == Activity time span inclusive of all dependency chains

Lighthouse output:

* What critical resource chains are > 2 long (more than just HTML + asset)?
* What resources/requests are they?
* starttime and duration of each chain.

**Comment by paullewis** [comment]
This looks great. I think outputting the chains will be invaluable for diagnosing long first paint times.
