### ISSUE TITLE
gulp-lighthouse task

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#294]
Standalone task for kicking off a lighthouse run.

@brendankenny what's your thinking on the shape of this?

**Comment by wardpeet** [comment]
@paulirish probably can shoot this?
We already have https://github.com/addyosmani/webpack-lighthouse-plugin

**Comment by paulirish** [comment]
sg. filed https://github.com/GoogleChrome/lighthouse/issues/1102 in return. :)
