### ISSUE TITLE
Long tasks audit

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#2955]
It would be useful to surface long tasks to the user. The Log domain has a `longTask` violation setting we can use in the ConsoleMessage gatherer.

**Comment by tdresser** [comment]
+1

**Comment by brendankenny** [comment]
let's close in favor of `cumulative-long-queuing-delay` (and, to some extent, `mainthread-work-breakdown`, `bootup-time`, #924, etc)
