### ISSUE TITLE
DevTools Error: You probably have multiple tabs open to the same origin.

### ISSUE THREAD

**Issue by NirobNabil** [GoogleChrome/lighthouse#2973]
**Initial URL**: https://www.youtube.com/embed/ow38nwq8ayg?

I was trying to audit shruto.org which contained iframes and the audit started popping up error.

**Comment by canarslan12** [comment]
close other tabs. probably one of them has youtube iframe

**Comment by Ap-Design** [comment]
close youtube tab and reload page - it solved

**Comment by patrickhulce** [comment]
@canarslan12 and @Ap-Design are correct, for more comprehensive information about this issue see #3024.
