### ISSUE TITLE
Restore to non-emulated view

### ISSUE THREAD

**Issue by ylavoie** [GoogleChrome/lighthouse#2996]
After audit exit, developer tools should be restored to standard view.

**Comment by patrickhulce** [comment]
@ylavoie on latest Chrome Canary the developer tools should be restored to whichever state they were in before you started the audit (if you were not emulating when you started it returns to not emulating, but if you were emulating it preserves that state). 

Is there a series of steps that you take that leads to this behavior or is it consistently wrong?

**Comment by ylavoie** [comment]
So if it failed or is run twice, it will stay in emulation forever?
There has to be a way to get out of that if the user decides that's what
he wanted.

I ran it once and cannot get out since then.

Le 2017-08-16 à 12:38:31, Patrick Hulce a écrit :

**Comment by patrickhulce** [comment]
@ylavoie does toggling device mode not do anything for you? The device mode toggle is the icon immediately to the left of "Elements" panel (highlighted blue in the below screenshot). 

If so, please post a clear series of steps that will allow us to reproduce (i.e. you can follow these steps in a fresh Chrome profile and observe the behavior you're talking about).

![image](https://user-images.githubusercontent.com/2301202/29759012-f973b380-8b6c-11e7-942c-efc63e1e9f9c.png)

**Comment by ylavoie** [comment]
Le 2017-08-28 à 00:18:55, Patrick Hulce a écrit :
>
> @ylavoie <https://github.com/ylavoie> does toggling device mode not do
> anything for you? The device mode toggle is the icon immediately to
> the left of "Elements" panel (highlighted blue in the below screenshot).
>
Thanks for the heads up, yes it does. I was expecting that button on the
left side, not on the right, or as a menu item

Yves

**Comment by patrickhulce** [comment]
Great! I'm going to go ahead and close this issue then, but feel free to comment again if you have clarifying questions. If you experience any further issues with just device mode not working, you can file an issue on crbug.com.
