### ISSUE TITLE
ServiceWorker registration and 200 while offline false negatives on punycoded URL

### ISSUE THREAD

**Issue by hypesystem** [GoogleChrome/lighthouse#3040]
I have been turning my website, [Mærkelex](https://xn--mrkelex-mxa.dk/), into a PWA. Right now, the following checks are failing in Lighthouse:

- Does not register Service Worker
- Does not respond with 200 when offline
- User will not be prompted to install the Web App

As far as I can tell (from debugging, running in offline, etc.) all of these are false negatives. A service worker is registered and it works with the "Offline" flag still.

The exact same code (at the time of writing; at least the exact same PWA-enabling code) is running here https://pwa--maerkelex.netlify.com/ where the tests all pass!

As far as I can tell, the only difference is that the URL for the main website is punycoded to contain the danish character "æ" (https://mærkelex.dk/ is punycoded as https://xn--mrkelex-mxa.dk/).

Any help is appreciated! Thanks :smile:

**Comment by patrickhulce** [comment]
Great sleuthing so far! :)

We've previously had issues in our URL parser not properly handling punycoded-like URLs (#1972 and somewhat waiting on resolution from https://github.com/whatwg/url/issues/53), but I'm actually seeing a 100 PWA score for your site in both the CLI and DevTools, so I'm not sure what's going on. It never reports success in your attempts or is it just flakey?

![image](https://user-images.githubusercontent.com/2301202/29467110-18fecda0-83f4-11e7-9cbc-13fb09bf4927.png)

![image](https://user-images.githubusercontent.com/2301202/29467117-249a4c7a-83f4-11e7-8f9a-1a907b9261fb.png)

**Comment by hypesystem** [comment]
Hey!

In my browser I consistently get the three above-mentioned errors, and consistently get 100 points (no errors!) on the alternate domain.

I've run it at least 5 times on each while pulling out my hair :smile:

I see that it works in my mobile browser: I am prompted to add the site to my homescreen, so I'm all good, personally :-)

Let me know if I can do anything else to help.

**Comment by hypesystem** [comment]
Just a quick update: the Chrome browser seems to not correctly trigger the "Add to homescreen" prompt for the website (I had a few friends try it out), but somehow my mobile browser, Brave, did.

**Comment by patrickhulce** [comment]
@hypesystem have they visited the site more than once? Part of the "Add to homescreen" prompt is a minimum [engagement score](https://www.chromium.org/developers/design-documents/site-engagement) which you can find at `chrome://site-engagement/`

**Comment by hypesystem** [comment]
@patrickhulce Yes, this is including people who have visited before and often.

**Comment by brendankenny** [comment]
I'm not seeing an issue today, so hopefully this hasn't been an issue for some time :)

(engagement criteria have also changed quite a bit, so hopefully that's working out as well)
