### ISSUE TITLE
Puppeteer vs lighthouse Chrome Launcher?

### ISSUE THREAD

**Issue by stramel** [GoogleChrome/lighthouse#3058]
Puppeteer also has a Chrome Launcher but isn't using this one. Is there a benefit to using one over the other? Or a reason that they should both exist?

https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js

**Comment by ebidel** [comment]
Can you file this over on https://github.com/GoogleChrome/puppeteer/issues/new? We've considered sharing the same launcher but I don't see a tracking but over there.
