### ISSUE TITLE
Create suite of pages that pass and fail LH audits

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#307]
In all manner of ways, so we can test that we get the right set of outputs.

**Comment by samccone** [comment]
https://github.com/GoogleChrome/lighthouse/tree/master/test/fixtures

**Comment by gauntface** [comment]
I'm going to have a crack at adding a few of these with the small refactor of tests.

**Comment by wardpeet** [comment]
@paulirish closing this, think we got this covered?

**Comment by paulirish** [comment]
dbw_tester is a good model for this. We don't have it everywhere. It'd be good to have more fixture sites, but at the moment I think we can defer that work.

So.. this idea is still good but i'm ok closing the long-open issue for now.
