### ISSUE TITLE
Mobile-only Analysis With Latest Version?

### ISSUE THREAD

**Issue by drobertsacbj** [GoogleChrome/lighthouse#3072]
Lighthouse used to give me both a "desktop" and a "mobile" tab for viewing my analysis. Now I see neither -- but it's clear that it's mobile-only. 

I'm guessing this is intentional but wanted to confirm.

**Comment by patrickhulce** [comment]
@drobertsacbj I'm not sure what "Desktop" tab you're referring to. Much of the advice is relevant for both desktop and mobile, but the site under test is indeed loaded with mobile emulation, network, and CPU throttling unless you run the CLI with `--disable-device-emulation --disable-network-throttling --disable-cpu-throttling`

See #1822 to follow along progress on adding this as an option to the extension and DevTools

**Comment by paulirish** [comment]
Accctually.... Page Speed Insights has the desktop/mobile tabs. :)  Lighthouse never had that split. 

They are different tools.. and PSI still has the same look. 

We are talking about aligning the two tools though!
