### ISSUE TITLE
No dogfood

### ISSUE THREAD

**Issue by Tsaukpaetra** [GoogleChrome/lighthouse#3074]
I clicked the lighthouse on https://developers.google.com/web/tools/lighthouse/
It epicly failed the page.

Heck, even https://www.google.com gave me abysmal results:

https://pastebin.com/XEKLKctP

What's going on here?

**Comment by patrickhulce** [comment]
@Tsaukpaetra those results for google.com look extremely unusual. Does it really take 17 seconds to load for you? In these cases it's almost always been another extension or antivirus software interfering with the run. A trace of your load (obtained via the CLI with the `--save-assets` flag) would be the best way for us to diagnose why it took so long.

The below results are what you should expect from google.com or any well-built site that hasn't been made a PWA.
![image](https://user-images.githubusercontent.com/2301202/29575861-a6a40426-871a-11e7-9ba4-ce349590765f.png)

![image](https://user-images.githubusercontent.com/2301202/29575839-98bef6f4-871a-11e7-9e3d-3fcb83437764.png)


This did help uncover a bug in one of our best practices audits though :) #3079

**Comment by VaultDwe11er** [comment]
Interestingly I just tested google.co.za, and it gives me similar results to google.com, except for a score of 69 on "Best Practices" (vs 77 on google.com). The difference seems to be that google.co.za has an additional failure for "Requests the geolocation permission on page load". There's nothing like free QA, right? 😉

**Comment by patrickhulce** [comment]
Heh the "Requests the geolocation permission on page load" is a dicey one for quite a few searches as well. It's starts entering arguable territory whether a search navigation is a user gesture where one might expect the prompt, not a page load. For example, if Google were an SPA that prompted you on entering into a search box instead of form submission, it'd pass the audit.

**Comment by VaultDwe11er** [comment]
I understand what you're saying, it's just interesting that google.com passes the audit but google.co.za does not, is all I'm saying 🤷‍♂️
