### ISSUE TITLE
Using lighthouse programatically doesn't generate output log

### ISSUE THREAD

**Issue by ev1stensberg** [GoogleChrome/lighthouse#3077]
## Summary 

When using lighthouse programatically with the `lighthouse-logger` dependency, it doesn't output the generated output path and keeps freezing at `generating results`

---

![skjermbilde 2017-08-22 kl 11 19 28](https://user-images.githubusercontent.com/16735925/29558240-cda9484a-872b-11e7-9bf6-ce0c8a7e5705.png)

## Steps to reproduce 

Invited ( now CC-ing ) @samccone to a private repro repo, can make public if anyone wants to give this a stab. 

Originally at @addyosmani 's `webpack-lighthouse-plugin`, Addy pulled the printer logic manually from the lighthouse repo, so in order to get it to work, I may need to do that. That being said, when including the logger dependency, it should provide the logic from the [printer module](https://github.com/GoogleChrome/lighthouse/blob/fadaef95137181aa41ed44fd78f17d3a8b85a2c3/lighthouse-cli/printer.ts). Previously, [this is where the printer module was dragged in](https://github.com/addyosmani/webpack-lighthouse-plugin/blob/master/src/lighthouse-bin.js#L29)

## Expected output

Expect the logic from `lighthouse-logger` to include output path

**Comment by patrickhulce** [comment]
@ev1stensberg what do you mean by freezing? "Generating results" is the last statement that's logged when you're using lighthouse programatically. The output is not written to a file when using programmatically (under the assumption we just returned the objects to you and you'll use them immediately or save them however you wish). 

If you want to see how to save the results the way the CLI does, you can take a look at that [code](https://github.com/GoogleChrome/lighthouse/blob/78a8bd75ae13173038cac60b6d9ae3498bbeaa71/lighthouse-cli/run.ts#L103-L147)

**Comment by ev1stensberg** [comment]
@patrickhulce What I meant was that it should output it when you pass in respective arguments to the dependency. So this is expected output, and I'd have to output that myself?

**Comment by paulirish** [comment]
@ev1stensberg if you can add the core team to have access to the repo, one of us might be able to debug what's happening.

hard to figure it out without running this. :)

**Comment by ev1stensberg** [comment]
Gotcha! Added @patrickhulce & you @paulirish, I'll give admin rights once you've accepted

**Comment by patrickhulce** [comment]
@ev1stensberg perhaps I'm missing something but that repo looks empty and it's importing webpack-lighthouse-plugin from a parent directory that's not under source control?

**Comment by ev1stensberg** [comment]
Yep, sorry, forgot to mention; Use this [PR](https://github.com/addyosmani/webpack-lighthouse-plugin/pull/7) in parent dir or change the import accordingly to where you clone the repo!

**Comment by ev1stensberg** [comment]
Fixed the "issue", could be considered a feature request.
