### ISSUE TITLE
rel=noopener audit should ignore href=javascript:.* 

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#3079]
discovered in #3074 

auditing google.com flags `<a href="javascript:void(0)" target="_blank">` as a failure

**Comment by ThisIzKp** [comment]
@patrickhulce I would love to take a look at this. Regex and filter, I suppose :)

**Comment by akonchady** [comment]
@patrickhulce Is this still an issue? Can I take this?

**Comment by paulirish** [comment]
@akonchady go for it. :)

**Comment by patrickhulce** [comment]
hey @akonchady were you still planning on taking this up? :)

**Comment by karanjthakkar** [comment]
Since I was involved in the initial PR that got this audit in #912, I was wondering if I could give this a shot if @akonchady hasn't already started working on it?

**Comment by akonchady** [comment]
Thanks @karanjthakkar for the PR. I wasn't able to take this up.
