### ISSUE TITLE
Report page is blank

### ISSUE THREAD

**Issue by amk221** [GoogleChrome/lighthouse#3093]
Running from both the command line and as a browser extension, everything is seemingly successful, but the results page is blank.

![screen shot 2017-08-23 at 12 32 13](https://user-images.githubusercontent.com/382061/29613707-2e6d904a-87ff-11e7-86af-aea82cb76c55.png)

**Comment by amk221** [comment]
Found a dodgy character in the generated JSON. Removed this and it fixed it.
Perhaps some more resilience could be added around this / an error explaining.

**Comment by patrickhulce** [comment]
Thanks for the report and finding the root cause @amk221!

**Comment by paulirish** [comment]
Can you give us the test URL or identify what character broke the JSON?

Thanks!

**Comment by amk221** [comment]
```
{
 "dodgy-char": "  " 
}
```

**Comment by patrickhulce** [comment]
For those also confused by GitHub's rendering the dodgy character is U+2028 LINE SEPARATOR
http://www.fileformat.info/info/unicode/char/2028/index.htm

Thanks for digging this back up @amk221 !

**Comment by patrickhulce** [comment]
Useful article from @brendankenny in https://github.com/GoogleChrome/lighthouse/pull/3442#discussion_r141956067 : http://timelessrepo.com/json-isnt-a-javascript-subset
