### ISSUE TITLE
audit suggestion: track runtime errors and warnings

### ISSUE THREAD

**Issue by alekseykulikov** [GoogleChrome/lighthouse#3109]
Tracking this, in the way Lighthouse tracks user timing metrics may help in different cases, for example:
- Having runtime exceptions can be a bad sign, that some javascript loaded on the pages fails, and time to load/parse is wasted.
- warnings (console.warn) may indicate that page uses deprecated/outdated technology, that may have vulnerabilities or hurt performance.

If this is a valuable suggestion, I can try to provide a PR.
This issue may also be related to #1512

**Comment by patrickhulce** [comment]
someone else thought so too :) #2836 

deprecations should already be surfaced by the "deprecations" audit that uses the console messages as the source.

**Comment by patrickhulce** [comment]
fixed by #2836
