### ISSUE TITLE
Wrong Chrome Canary Path

### ISSUE THREAD

**Issue by dvotion** [GoogleChrome/lighthouse#311]
When running the tool at first, it complained about a wrong Google Chrome Canary path. When replaced it in launch-chrome.sh to an absolute path, everything worked out fine

**Comment by paulirish** [comment]
paths are hard and we've done something not terribly robust.
Want to help us out with a PR for launch-chrome thats a bit smarter?

**Comment by dvotion** [comment]
Certainly don't mind helping out. But with no experience in shell scripts, I don't think I could make it more robust. :(

**Comment by boopathi** [comment]
@dvotion Can you share the Chrome Canary Path that you used ?

**Comment by wardpeet** [comment]
Cool cool, i can give it a shot :)

**Comment by dvotion** [comment]
Of course, the path:
CHROME_CANARY_PATH="/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary"
