### ISSUE TITLE
DevTools missing "Export" button

### ISSUE THREAD

**Issue by VanithaSnS** [GoogleChrome/lighthouse#3112]
Hi,
It would be really helpful if we are able to export Lighthouse Audit report. Currently We can view Audit report but unable to export Audit report.

Thanks,
Vanitha

**Comment by ebidel** [comment]
Sadly DevTools does not have the same export button that the chrome extension and CLI have. If you run LH using those other tools, there's a button in the top right corner with a couple of options:

<img width="486" alt="screen shot 2017-08-24 at 9 10 02 am" src="https://user-images.githubusercontent.com/238208/29676122-0a51ab62-88ac-11e7-88b0-0ca321f0eec4.png">

**Comment by VanithaSnS** [comment]
Thanks. It's pretty helpful.

**Comment by paulirish** [comment]
You can now export reports from devtools:

![image](https://user-images.githubusercontent.com/39191/30994098-15a92702-a467-11e7-89da-19a093e07045.png)

You can take this JSON and drag it into https://googlechrome.github.io/lighthouse/viewer/
