### ISSUE TITLE
[SEO Audits] Crawling and indexing group

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#3118]
**Group name:** Crawling and Indexing

**Description:** To appear in search results, crawlers need access to your app.

**Audits:**
- [x] [Page has successful HTTP status code](https://github.com/GoogleChrome/lighthouse/issues/3181)
- [x] [Page is not blocked from indexing](https://github.com/GoogleChrome/lighthouse/issues/3182)

**Comment by kdzwinel** [comment]
Both audits landed, we can close this section 👍
