### ISSUE TITLE
Crash when connect chrome://inspect on adb android chrome 

### ISSUE THREAD

**Issue by wrzosdev** [GoogleChrome/lighthouse#3127]
Well, when you connect android via adb, and statically enable webview debugging, then on chrome://inspect page you can choose webview site and then on new window start audit in lighthouse - it will crash every time on different devices so i mean it could be general problem, hope it helps, sorry for format i must hurry up im in work thx

**Comment by patrickhulce** [comment]
Thanks for the report @wrzosdev! This actually should be fixed by https://chromium-review.googlesource.com/c/chromium/src/+/630101 by preventing you from running an audit on anything but a regular tab :)
