### ISSUE TITLE
audit suggestion: track failed HTTP requests

### ISSUE THREAD

**Issue by alekseykulikov** [GoogleChrome/lighthouse#3128]
During page execution: ajax requests may fail, or images/js/css didn't exist and returned 404. That may be a solid recommendation to fix.
It's similar to the tracking of javascript errors #3109, 0 failed HTTP request is a valid expectation.

**Comment by patrickhulce** [comment]
HTTP failures result in console errors, so #2836 should actually address this as well.

**Comment by alekseykulikov** [comment]
@patrickhulce good point! I may try to extract changes from #2836 and provide new PR to add only this audit.

**Comment by patrickhulce** [comment]
fixed by #2836

**Comment by paulirish** [comment]
> and provide new PR to add only this audit.

@alekseykulikov you could do that, though we may then have some interesting overlap between the two. It's a little awkward so we favor keeping the 2836 audit all-together.  does that work for you?
