### ISSUE TITLE
Adding Mixed Content Auditing to Lighthouse

### ISSUE THREAD

**Issue by amirian28** [GoogleChrome/lighthouse#3164]
Hi Lighthouse folks,

I'm interested in adding a mixed-content checker into lighthouse, to help developers identify which resources on their page are HTTPS ready and which ones are not. Details can be found in [this document](https://docs.google.com/document/d/1Cpj7FRJFJA5Btgnp-98soXvtljW-b2JRsT5MiaJFMTI/edit?usp=sharing), but in a nutshell, I want to be able to 1) check the HTTPS version of each resource and 2) check Locksmith to see if there is an HTTPS version of that link or if that provider supports HTTPS.

I'm happy to field any feedback or notes; note that this document is being widely shared, so there are already some comments on there and it is open for anyone to comment.

**Comment by paulirish** [comment]
The latest and greatest: https://github.com/amirian28/lighthouse/tree/mixedcontent

**Comment by vinamratasingal** [comment]
I'll discuss with Adrienne to see whether they can commit to finishing this.

**Comment by vinamratasingal** [comment]
Just chatted with Adrienne- first PR should be landing in ~1 week, and they hope to close this by Thanksgiving.

**Comment by patrickhulce** [comment]
Landed! ✈️
