### ISSUE TITLE
[SEO Audits] Document has a meta description

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#3175]
**Audit group:** [Content best practices](https://github.com/GoogleChrome/lighthouse/issues/3117)
**Description:** Document has a meta description
**Failure description:** Document does not have a meta description
**Help text:** Meta descriptions may be included in search results to concisely summarize page content. Read more in the [Search Console Help page](https://support.google.com/webmasters/answer/35624?hl=en#1).

**Success condition:** Query selector `head > meta[name=description]` exists and has a non-empty content attribute.

Notes
- If short-circuiting the audit when `nosnippet` exists, use the audit description field to explain that the meta description is unused. Other `robots` directives that affect the meta description like `noindex` are covered in separate audits. _(not used)_

**Comment by kdzwinel** [comment]
Hi all 👋 I started working on this issue. Can I get assigned please? 😉

FYI there are couple of corner cases regarding "nosnippet" that are not mentioned in the task description:

- 'robots' metatag can have multiple values (e.g. `noarchive, nosnippet`)
- there can be multiple `<meta name="robots"` on page
- `name="robots"` can be replaced with a bot specific `name="googlebot"`
- directives can also be sent via X-Robots-Tag HTTP header
  - there can be multiple of these headers
  - they can have multiple values `X-Robots-Tag: noindex, nofollow`
  - they can refer to a specific bot `X-Robots-Tag: googlebot: nofollow`

*Other notes*: everything is non-case sensitive, comas are required, spaces after comas are optional

*Sources*:
- https://developers.google.com/search/reference/robots_meta_tag
- https://webmasters.googleblog.com/2007/03/using-robots-meta-tag.html
- http://searchengineland.com/meta-robots-tag-101-blocking-spiders-cached-pages-more-10665

**Comment by kdzwinel** [comment]
Per our discussion today, `name="googlebot"` and `googlebot:` are out of the picture for now since we are not focusing on search engine specific directives. This brings up a question: should we really support `nosnippet` since it's recognized only by a googlebot ([according to this](http://searchengineland.com/meta-robots-tag-101-blocking-spiders-cached-pages-more-10665))?

**Comment by rviscomi** [comment]
Yeah let's remove the `nosnippet` condition. I'll update the audit description.

I checked the [HTTP Archive data](https://bigquery.cloud.google.com/savedquery/226352634162:193c9ebf65624c4b838ad2134af43052) and that particular directive is only present in ~150 pages (of the 500k measured).

**Comment by kdzwinel** [comment]
👌

BTW I'm not sure how much we can depend on httparchive data regarding SEO, their robot [also follows the "robots" directives](https://archive.org/about/faqs.php#14) so the results may be skewed. On the other hand, if their robot does follow these directives, how did you get "noindex, nofollow" on the results of that query? 🤔

**Comment by rviscomi** [comment]
HTTP Archive runs as a totally separate crawl from the Internet Archive's Wayback Machine. We've talked about [respecting robots directives](https://github.com/HTTPArchive/httparchive/issues/127) but they're ignored for now.

**Comment by kdzwinel** [comment]
For the record: we've decided to trim the description before evaluating its length and to provide debugString's for audit failures (tag not found, empty value).

https://github.com/GoogleChrome/lighthouse/pull/3227#discussion_r136660967
