### ISSUE TITLE
[SEO Audits] Document has a valid rel=canonical

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#3178]
**Audit group:** [Content best practices](https://github.com/GoogleChrome/lighthouse/issues/3117)
**Description:** Document has a valid `rel=canonical`
**Failure description:** Document does not have a valid `rel=canonical` `({value})`
**Help text:** Canonical links suggest which URL to show in search results. Read more in [Use canonical URLs](https://support.google.com/webmasters/answer/139066?hl=en).

**Success conditions:**
- Query selector `head > link[rel=canonical]` doesn’t match any elements; otherwise
  - `href` value of canonical link is not set to the root; otherwise
    - origins of `href` and current page are different
    - `location.pathname` is not the root.
- `href` value of canonical link is absolute

Valid examples:
- URL `example.de/`, `<link rel="canonical" href="example.com/de/">`
- URL `example.com/de/`, `<link rel="canonical" href="example.de/">`

Invalid examples:
- URL `example.com/blog/`, `<link rel="canonical" href="example.com/">`
- URL `example.de/`, `<link rel="canonical" href="example.com/">`
- URL `example.com/de/`, `<link rel="canonical" href="/">`

**Comment by kdzwinel** [comment]
For the record: we agreed that we should also support canonical Link headers.

Questions: 
1) How do we deal with multiple canonicals? There can be multiple headers and/or tags. ATM I'm processing only the first one found (headers before tags). But according to [this](https://searchengineland.com/canonical-tags-easy-right-whats-worst-happen-274635) if there are multiple canonicals pointing to different URLs, search engines will ignore all of them.

2) How do we deal with invalid URLs? ATM I'm failing the audit when `new URL(href)` fails.

3) Where is this part coming from? I didn't found a rule that would explain this.

> href value of canonical link is not set to the root; otherwise
> origins of href and current page are different
> location.pathname is not the root.

Why `example.de/` can't have a canonical link to `example.com/`, but it can have one to `example.com/de/`?

4) Your examples indicate that canonical can point to different domain. [Official docs](https://support.google.com/webmasters/answer/139066?hl=en) seem to agree saying "With content syndication, it's also easy for content to be distributed to different URLs and domains entirely.". However, all the examples given in the docs show the same domain. Also, according to [yahoo](http://www.ysearchblog.com/2009/02/12/fighting-duplication-adding-more-arrows-to-your-quiver/) and [bing](https://blogs.bing.com/webmaster/2009/02/12/partnering-to-help-solve-duplicate-content-issues) different domains are not supported. Should we check that with John?

**Comment by rviscomi** [comment]
Good questions :)

> How do we deal with multiple canonicals?

We should fail the audit and specify the failure reason being conflicting canonical links.

> How do we deal with invalid URLs? ATM I'm failing the audit when `new URL(href)` fails.

Failing when invalid SGTM. Again, we should be clear about the failure reason.

> Where is this part coming from?

The advice came from an offline thread. Forwarding to you for context.

> Your examples indicate that canonical can point to different domain.

Yeah worth checking to be sure. It does seem like the docs use different domains, for example with/without the www subdomain, although having different TLDs may not be valid.

**Comment by kdzwinel** [comment]
Thanks for a quick response!

> The advice came from an offline thread. Forwarding to you for context.

Thanks! It does sound a bit GoogleBot specific, doesn't it?

> It does seem like the docs use different domains, for example with/without the www subdomain, although having different TLDs may not be valid.

Right, I meant TLDs. Sorry for the confusion.

----

I absolutely agree that we should show failure reason, especially that now we have couple of them. Should we just use the `displayValue` (it's the one appended to the end of the failure description)? Table feels like overkill here and `debugString` (red one) is rather used for audit failures.

ATM we have these failure reasons:
- "multiple conflicting URLs"
- "invalid URL"
- "relative URL"
- "points to a different TLD" (to be checked with John)
- "???" (one with canonical link set to root)

How that list looks to you? I'd appreciate a bit of help with a copy for the last one :)

**Comment by kdzwinel** [comment]
To sum up our email/hangouts discussion, we decided to fail in these cases:
1. multiple conflicting URLs
1. invalid URL
1. relative URL
1. current URL and canonical URL have different domains
1. current URL is not a root but points to a root of the same origin
1. current URL is a hreflang and canonical URL is a different hreflang

---

While writing tests I found two more edge cases:
1. current URL and canonical URL have different domains - I assume that the domain is last two parts of the hostname (e.g. test.**example.com**), unfortunately this assumption breaks for [second-level domains](https://en.wikipedia.org/wiki/Second-level_domain) (one.co.uk and two.co.uk will be considered having same domain). Only solution I can see here involves creating a safelist of all second-level domains, but this seems impractical. IMO we should keep current solution.

1. [This article](https://webmasters.googleblog.com/2013/04/5-common-mistakes-with-relcanonical.html) suggests that we should fail not only when multiple conflicting canonical URLs are found but *always* when multiple canonical URLs are found. I'll double check that with John.

**Comment by TimothyLoyer** [comment]
Maybe this? I'm not certain if they mean identical in this case, but it could make sense. Admittedly our duplicate is due to our using the SEOmatic plugin for Craft. If it seems likely Google would penalize us for this, we're more than happy to address it with the plugin authors.

> In cases of multiple declarations of rel=canonical, Google will likely ignore all the rel=canonical hints. Any benefit that a legitimate rel=canonical might have offered will be lost.

**Comment by kdzwinel** [comment]
> I'm not certain if they mean identical in this case

Yeah, I'm not 100% sure about that either. Maybe Rick will remember, and if not, we will double check with John.

**Comment by TimothyLoyer** [comment]
Also, in the second point of the conclusions.
> Check that rel=canonical is only specified once (if at all) and in the <head> of the page.

Thank you for all your help with this @kdzwinel. :)

**Comment by rviscomi** [comment]
I don't remember exactly, but rereading the doc, it does seem like we're doing the right thing. Please do reach out to John and confirm that having the same canonical URL in both a header and meta tag is invalid.

**Comment by khalwat** [comment]
> This article suggests that we should fail not only when multiple conflicting canonical URLs are found but always when multiple canonical URLs are found. I'll double check that with John.

Hello everyone, I'm the author of the [SEOmatic](https://github.com/nystudio107/craft-seomatic) plugin for Craft CMS 2 that @TimothyLoyer has referenced.

What I'm doing is adding the exact same canonical URL both as a tag, and also as a header.

I also do this for the `robots` tag and `X-Robots-Tag` neither was done for any specific reason, other than "why not?"

From the [linked article](https://webmasters.googleblog.com/2013/04/5-common-mistakes-with-relcanonical.html):

> Another issue is when pages include multiple rel=canonical links to different URLs. This happens frequently in conjunction with SEO plugins that often insert a default rel=canonical link, possibly unbeknownst to the webmaster who installed the plugin. In cases of multiple declarations of rel=canonical, Google will likely ignore all the rel=canonical hints. Any benefit that a legitimate rel=canonical might have offered will be lost.

To me this implies that there is only an issue if there are multiple _conflicting_ canonical URLs? If they are the same URL, whether appearing multiple times as a tag or one as a tag, another as a header... I'm not seeing anything stating this is an issue?

I'm happy to alter the plugin to do whatever best practices are, but on this topic, I wasn't able to find anything definitive one way or another?

**Comment by rviscomi** [comment]
IMO the ambiguity comes from this sentence:

> In cases of multiple declarations of rel=canonical, Google will likely ignore all the rel=canonical hints.

Out of context, it's not clear if "multiple" refers to any two canonical URLs. The previous sentence about different URLs could just be an example of a common cause of this type of error, or it could be the only case.

I reached out to my resident SEO expert and I'll update this thread with their guidance.

**Comment by khalwat** [comment]
Ultimately, what really matters is how Google, and to a lesser extent, other search engines handle this situation. I would think that as long as the canonical URLs are not in conflict, that it should be okay with it, but I have no knowledge of Google's internal workings on this front.

**Comment by auralon** [comment]
Given that it is highlighted as a problem by the Lighthouse tool (which is a Google product), I'd *guess* that it is recommended to only serve one canonical URL (be it via header or link tag).  However, multiple robots tags are not highlighted as an issue by the Lighthouse tool.

**Comment by khalwat** [comment]
@auralon That definitely could be; but Google is a big place, and the team that works on Lighthouse may or may not overlap the team that works on GoogleBot.

**Comment by auralon** [comment]
@khalwat true, true!

**Comment by rviscomi** [comment]
I got confirmation from John Mueller himself (praise be unto him) that this is a bug. We should only fail when there are multiple _different_ canonical URLs.

Reopening the issue. @TimothyLoyer @khalwat @auralon would either of you like to implement the fix? @kdzwinel is working on a higher priority issue (#4359) so this may not be fixed as quickly.

**Comment by khalwat** [comment]
Great, thanks for tracking this down!

**Comment by TimothyLoyer** [comment]
Thank you, all, for looking into this!
