### ISSUE TITLE
[SEO Audits] Anchors have descriptive text

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#3179]
**Audit group:** [Content best practices](https://github.com/GoogleChrome/lighthouse/issues/3117)
**Description:** Anchors have descriptive text
**Failure description:** `{#}` anchors do not have descriptive text
**Help text:** Descriptive anchor text is a useful signal to help search engines better understand your content. Avoid nondescript anchor text like “click here”.

**Success conditions:**
- No anchor’s `textValue` is included in the blacklist below; otherwise
  - Anchor has a `rel=“nofollow”` attribute
  - Anchor's `href` value does not link to another page (eg `"#"`, `"javascript:void(0);"`)

Blacklist:
  - click here
  - click this
  - go
  - here
  - this
  - start
 - right here
 - more
 - learn more

**Comment by paulirish** [comment]
How about

More
Learn more

**Comment by rviscomi** [comment]
"More" and "Learn more" SGTM. Added to the blacklist.

I've also added a custom metric in HTTP Archive that will be collecting anchor `textValue`s so we could run some analysis to find the most commonly used invalid values. That should be available in a few days when the September 1 crawl is complete.

Anecdotally, `<a href="#">More</a>` seems to be a common way to show truncated content. I wouldn't consider that a failure case for this audit since the href is not linking to another document. I added a requirement to the audit's success condition so that anchors with self-referential `href` values are excluded.

**Comment by robdodson** [comment]
> Anecdotally, <a href="#">More</a> seems to be a common way to show truncated content. I wouldn't consider that a failure case for this audit since the href is not linking to another document

I'm not sure if we're testing it yet, but it should be an accessibility failure. Opening the screen reader links menu and just seeing "More, More, More" is not useful.
