### ISSUE TITLE
[SEO Audits] Page has successful HTTP status code

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#3181]
**Audit group:** [Crawling and indexing](https://github.com/GoogleChrome/lighthouse/issues/3118)
**Description:** Page has successful HTTP status code
**Failure description:** `{status}` is not a successful HTTP response code
**Help text:** The HTTP status code tells crawlers whether a URL leads to a valid page or not. Pages with unsuccessful status codes may not be indexed properly. Learn more about the [HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).

**Success condition:** HTTP status code not in range `[400, 600)`

Notes:
- If there are one or more redirects, use the status code of the final response
- There are successful status codes that are not 200, so only known unsuccessful codes in 4xx, 5xx are blacklisted

**Comment by kdzwinel** [comment]
As far as I can see, looking at other audits, `failureDescription` shouldn't contain any variables. How about something more general like "Page doesn\'t have a successful HTTP response code" and showing more details in the `debugString` like so:

<img width="797" alt="screen shot 2017-09-05 at 17 04 47" src="https://user-images.githubusercontent.com/985504/30068850-4bfecccc-925f-11e7-9133-8df76f7aa480.png">

**Comment by rviscomi** [comment]
I've seen variables in other audits. For example:

![image](https://user-images.githubusercontent.com/1120896/30069487-d970c7bc-922e-11e7-88f7-3dfcb2f3128f.png)
![image](https://user-images.githubusercontent.com/1120896/30069518-ee60c514-922e-11e7-9d4c-3ee6533d0dc5.png)

That said, I'm ok with `debugString` as well. Does the LH team have a preference?

**Comment by patrickhulce** [comment]
@rviscomi @kdzwinel yes failureDescription is a static, generic string and the variables you see are in the "displayValue" which can be [dynamically constructed](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/dobetterweb/uses-http2.js#L61).

**Comment by kdzwinel** [comment]
thanks @patrickhulce! As far as I can see, `displayValue` gets appended to the end of `failureDescription` (and doesn't replace it as I initially thought).

<img width="820" alt="screen shot 2017-09-05 at 22 44 48" src="https://user-images.githubusercontent.com/985504/30082802-55ab59b6-928c-11e7-88c5-10b8688df09d.png">

We should rethink the wording if we want to go with `displayValue`, but TBH the `debugString` version looks much more readable to me.
