### ISSUE TITLE
Lighthouse Way Out of Whack Compared to Other Tools. 

### ISSUE THREAD

**Issue by michaelnorthern** [GoogleChrome/lighthouse#3226]
Just tried Lighthouse through Chrome dev tools. Why does Lighthouse consistently show first paint at some miserable number like 12 seconds, when Pingdom Tools and KeyCDN tools show loading around 1 second? Is Lighthouse disabling all caching? I don't get why there's an order of magnitude difference.

**Comment by paulirish** [comment]
Lighthouse loads a URL like a user on their phone who's never been to it before.

* The cache is emptied
* Network throttling of 3G is applied
* CPU is slowed down 4x to approximate a mobile phone

Do you have a URL I can look at? I can probably point to the reason why first paint takes so long.

**Comment by michaelnorthern** [comment]
Ah, that would explain it.  Please take a look at a typical URL:
https://doctormotors.com/cabin-air-filters/

This WordPress site relies on KeyCDN caching and KeyCDN's CDN network. The
theme minifies CSS and JS.

It seems Lighthouse is geared towards apps, not sites, but any feedback you
can send along would be appreciated. Thanks Paul!

**Comment by benschwarz** [comment]
@michaelnorthern, apart from what @paulirish mentioned, there's also the fact that lighthouse is running from your machine, rather than a machine with a dedicated data centre connection (that… might be closer to where the site is hosted too).

It might be that the "miserable" numbers that you're seeing are what some customers are seeing too!

**Comment by ThisIzKp** [comment]
I think lighthouse gives you the worst case scenario (like Big O in algorithms). May be we should mention about that in the lighthouse report.

**Comment by tozz** [comment]
I came here to ask the same question, I had my guesses but it's impossible to know from the report what kind of device/network/performace the test is being run with.
A lot of web devs are not building global sites either but have known markets, those markets are what you'd be interested in measuring tbh.

**Comment by ebidel** [comment]
@tozz the top of the report contains the emulation settings it was created with:

<img width="749" alt="screen shot 2017-09-05 at 11 59 52 am" src="https://user-images.githubusercontent.com/238208/30078360-c9c75ac6-9231-11e7-82e5-c972ae83d025.png">

**Comment by paulirish** [comment]
I saved a recording of Lighthouse's run of this site: https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=drive://0BxQDhwTm4jaFbXEteElOcXQxdTQ

Here's the look at it.

![image](https://user-images.githubusercontent.com/39191/30079716-06c7a83c-9236-11e7-8612-baceb55b71ba.png)

I see ~13 render blocking stylesheets, then 2 render blocking scripts in the `<head>` and 9 render blocking scripts at the bottom of the `<body>`. That's the big problem here. Luckily, this is indeed what the Lighthouse report calls out as the most important thing:

![image](https://user-images.githubusercontent.com/39191/30079872-876fbc4a-9236-11e7-90d8-fad5ed524936.png)

Minification won't have much benefit as long as all those requests sit in the critical path.

**Comment by tozz** [comment]
@ebidel Thanks for pointing that out, the grey on grey made it completely disappear for me.

Now the numbers are still way off, a page that is visible in <50ms from my location (most people experience it as instantly loaded) gets a 1.4second until first visible paint in the test, the page would have to load faster than 25ms to get a good enough score here, considering human perception and all that, that's a bit too extreme in my book at least.

**Comment by rwwagner90** [comment]
I'm also seeing some extremely bad numbers for my site in lighthouse. I used to get like a 3-4 second time to first interactive, and now I get like 10-15 seconds. What happened? My site is https://shipshape.io if anyone wants to take a look.

**Comment by patrickhulce** [comment]
@rwwagner90 let's continue discussion on the new issue you filed #3428 since these are expectation mismatches around throttling
