### ISSUE TITLE
Offline checking fooled by HTTP Cache

### ISSUE THREAD

**Issue by piotrswigon** [GoogleChrome/lighthouse#3237]
By accident I found today that Lighthouse gives my test website ([link](https://piotrswigon.github.io/pwa-demo/fullscreen/)) a positive result on "Responds with a 200 when offline". This is surprising because the SW it uses doesn't do any real work:

```javascript
self.addEventListener('install', function(e) {});
self.addEventListener('fetch', function(e) {e.respondWith(fetch(e.request));});
```

Some further investigation shown that this is probably because Github Pages gives 10 minute expiry through HTTP headers to everything it serves.

I'm not sure whether this is working as intended, but I think it's rather unfortunate.

**Comment by patrickhulce** [comment]
Yeah this is a bug. Coincidentally you've stumbled on some fascinating behavior, great find @piotrswigon! 

Performing the fetch from the service worker essentially circumvents Chrome's offline check and forces it to use the disk cache when the cache headers alone would have given you the offline dino.

Summary: simply adding those two lines does indeed make your app offline-proof during the cache header period but we still shouldn't pass you for it :)

**Comment by patrickhulce** [comment]
Note for future bug fixer, exploration with @paulirish found that simply disabling the disk cache of the service worker target addresses this issue.

**Comment by patrickhulce** [comment]
We're going to merge this one into #709 to mirror commands into service worker.
