### ISSUE TITLE
Could not install Lighthouse extension in Chrome

### ISSUE THREAD

**Issue by fmp72901** [GoogleChrome/lighthouse#3247]
Here's the error:
Could not install package: 'UTILITY_PROCESS_CRASHED_WHILE_TRYING_TO_INSTALL'. Could not install package because a utility process crashed. Try restarting Chrome and trying again.

OS: Centos 7 / 64bit

**Comment by brendankenny** [comment]
Perhaps check this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=251761 ? From the comments there it does appear that restarting Chrome will allow installing the extension again.

Closing for now as there's not much else we can do from the Lighthouse side of things.

**Comment by fmp72901** [comment]
thanks for the correction.



Powered by Zoho Mail






---- On Tue, 05 Sep 2017 11:19:15 -0700 Brendan Kenny &lt;notifications@github.com&gt; wrote ----




Closed #3247.

**Comment by fmp72901** [comment]
FYI. After uninstalling and then reinstalling Chrome, Lighthouse extension worked!


Powered by Zoho Mail






---- On Tue, 05 Sep 2017 11:19:13 -0700 Brendan Kenny &lt;notifications@github.com&gt; wrote ----




Perhaps check this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=251761 ? From the comments there it does appear that restarting Chrome will allow installing the extension again.

Closing for now as there's not much else we can do from the Lighthouse side of things.
