### ISSUE TITLE
Gulp task not available to run Lighthouse from command prompt

### ISSUE THREAD

**Issue by vishal918** [GoogleChrome/lighthouse#3248]
Not able to run lighthouse through automated Gulp task. I have set of Gulp task that I use to  compile my Less files and build my htmls. I want to run lighthouse through the same set of task whenever my html is build in my local server. Is there any way to get it running through Gulp task?

**Comment by patrickhulce** [comment]
Have you been following [the recipe](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/gulp)? We'd need a little more information if something is not working with the recipe to try and debug.

**Comment by ev1stensberg** [comment]
One common thing that may be causing this, is either a wrong `gulp` dependency or that gulp is installed locally and can't run through the global scope ( out of my own experience )

**Comment by patrickhulce** [comment]
Further gulp integrations are not on our roadmap, but feel free to comment here if you're finding issues with our docs!
