### ISSUE TITLE
Remove audit.meta.category

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#3252]
As discussed here https://github.com/GoogleChrome/lighthouse/pull/3227#discussion_r137057437 .. it's not needed and we can drop it.

**Comment by arturmiz** [comment]
I can take a look on this one and do the clean up :)

**Comment by Siilwyn** [comment]
I'm using the audit category, parsing the `audits`, maybe I should switch to only using what's under the `reportCategories` key...

How should I get the associated category given an audit now?

**Comment by patrickhulce** [comment]
@Siilwyn yes you should use the category it's associated with in `reportCategories`, the `audit.meta.category` was not the real "category" you see in the report and was a somewhat irrelevant and old display string :) sorry for the churn!

**Comment by Siilwyn** [comment]
@patrickhulce thank you for your reply! I already found it odd that it used different names, so I wrote a mapping function to convert them to the correct category. :)
