### ISSUE TITLE
Group all the load metric audits together?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#3263]
To people who are not well-versed in load performance, it can be confusing to see so many different metrics measuring the same thing. Or, they might not even realize that they're all load-related.

It could be helpful to group all of the load metrics, similar to how Lighthouse groups related a11y audits. The top-level help text could explain that each load metric covers a different aspect of the load experience, hence all of the different audits.

**Comment by vinamratasingal** [comment]
Chatted with Kayce, he'll add more details to this!

**Comment by vinamratasingal** [comment]
Closing in favor of the umbrella issue.
