### ISSUE TITLE
"network request latencies were not sufficiently realistic" due Service Workers?

### ISSUE THREAD

**Issue by oliverfernandez** [GoogleChrome/lighthouse#3268]
The site I'm testing is https://andro4all.com/ In failed audits, I get the following message

"First Interactive was found at 5,330 ms, however, the network request latencies were not sufficiently realistic, so the performance measurements cannot be trusted"

Indeed, if I open this audit I get a request that has a latency of 0.05ms

![screen shot 2017-09-07 at 11 04 40](https://user-images.githubusercontent.com/1696239/30155681-be625b12-93bd-11e7-940a-5899fbf1bbed.png)

But this request is so fast because is being cached by the Service Worker, as you can see here

![screen shot 2017-09-07 at 11 16 56](https://user-images.githubusercontent.com/1696239/30155812-18ca5b0e-93be-11e7-936b-dd743c8f75c0.png)

I suspect that this audit is being executed on second view, where Service Worker has some resources cached, and since this resources have a low latency make the audit think that something is wrong.

I want to validate this hypothesis and make sure that I'm not doing something wrong. 

Should Lighthouse consider when the requests is coming from the Service Worker?

**Comment by patrickhulce** [comment]
Hmm, I'm not reproducing, does this happen consistently for you? If so, how are you running LH (CLI, extension, devtools)?

The request timings are taken from the first run before the service worker should have been installed, so this shouldn't be the issue here unless some other bug is preventing the service worker from being unregistered.

**Comment by patrickhulce** [comment]
Unable to repro this on latest version. If you're still experiencing this, please feel free to comment here with reliable repro steps, and we'll investigate. Thanks!
