### ISSUE TITLE
chrome-finder fails with path error on Windows 32 bit

### ISSUE THREAD

**Issue by krystophv** [GoogleChrome/lighthouse#3270]
chrome-finder is explicitly sets up a set of path prefixes here: https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/chrome-finder.ts#L159 and then uses them directly in a `path.join` here: https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/chrome-finder.ts#L167.

On Windows 32 bit, `process.env['PROGRAMFILES(X86)']` is `undefined` and, thus, the `path.join` fails. In other places in the repository, accessing `process.env` variables which may not exist is often wrapped in an `if` block, so would something like:

```
const prefixes =
      [process.env.LOCALAPPDATA, process.env.PROGRAMFILES];

if (process.env['PROGRAMFILES(X86)']) {
  prefixes.push(process.env['PROGRAMFILES(X86)']);
}
```
be appropriate?

**Comment by brendankenny** [comment]
That seems good to me (maybe with a comment on when it won't be defined), but note that we're moving chrome-launcher stuff to https://github.com/GoogleChrome/chrome-launcher/, so the fix should go there and we can bring any changes back over here until it's moved to a proper lighthouse dependency

**Comment by brendankenny** [comment]
fixed by https://github.com/GoogleChrome/chrome-launcher/pull/20
