### ISSUE TITLE
chrome-launcher ECONNREFUSED From systemd

### ISSUE THREAD

**Issue by dsanders11** [GoogleChrome/lighthouse#3275]
`chrome-launcher` fails with the common `ECONNREFUSED` error when you try to use it from a script called by a `systemd` service unit. Example unit:

```
[Unit]
Description=ChromeLauncher

[Service]
Environment="DISPLAY=:0"
Environment="XAUTHORITY=/home/pi/.Xauthority"
ExecStart=/home/pi/ChromeLauncher.js
Restart=always
User=root
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=ChromeLauncher

[Install]
WantedBy=graphical.target
```

The annoying thing is it actually works - Chromium is launched. It's only the debugger connection that fails. Note that the user is `root`, so `--no-sandbox` is being used to allow this and it works fine for actually starting the browser.

The following from a terminal makes it work, if you manually invoke it after startup:

```
sudo systemctl stop ChromeLauncher
sudo systemctl start ChromeLauncher
```

So there's something about the service unit being started automatically at boot which is making it not work. Unfortunately that's exactly what I need - no manual intervention.

Various things I've tried to no avail:
1. Use `setTimeout` in the `nodejs` script to delay invoking `chrome-launcher` - makes no difference, no matter how long you delay it.
2. Use a `catch` on the launch promise to retry launching again - doesn't work, it will just sit there spamming new tabs and continuing to hit `ECONNREFUSED`
3. Various attempts at tweaking the `systemd` unit start order like adding `Requires=network-online.target` in case it was a problem with the network not being available yet. No difference. 1 and 2 suggest it isn't anything to do with timing, and this just seems to confirm it.

Any ideas? Is there a missing environment variable that might be stopping it? I can't explain why the unit doesn't work at boot but works fine if you manually stop/start it from a terminal.

**Comment by dsanders11** [comment]
I don't see the `ECONNREFUSED` error if I use the `--headless` flag to launch `chromium`, but I don't have that option as I need access to the webcam media stream, which throws an error if you try to access it in headless mode.

The dirty dirty hack I came up with to get around this issue - in the `catch` block for the launch promise, set a timeout of 10 seconds and throw an uncaught exception. This causes the service to crash and be restarted, at which point there is no longer an `ECONNREFUSED` error.

**Comment by patrickhulce** [comment]
That's quite the list of workarounds you've tried thanks for sharing your great research!

From your description it sounds like Chromium legitimately isn't binding to the port like it should be in which case we'll want to file an issue on crbug. Few more ideas to try to see if that's the in fact the case:

* What happens if instead of crashing your client in your dirty hack catch block, you kill Chrome and retry from scratch (attempting bullet 2 in your list but without the new tabs result)? 
* What happens if you try and connect to the port from another process (just via `require('net').createConnection()` while Chrome is open?
* You can also try manually increasing the interval for ECONNREFUSED to something much greater than 500ms as that seemed to have fixed the issue for others 
 (https://github.com/GoogleChrome/chrome-launcher/pull/19), though it sounds like that's just a variation on your bullet 1

**Comment by dsanders11** [comment]
> What happens if instead of crashing your client in your dirty hack catch block, you kill Chrome and retry from scratch (attempting bullet 2 in your list but without the new tabs result)?

I'm not sure how I can kill Chrome in this situation, without trying to do so by getting a PID and doing it at the OS level. In the examples the normal way to kill it would be:

```javascript
chromeLauncher.launch({
  startingUrl: 'https://google.com',
  chromeFlags: ['--disable-gpu']
}).then(chrome => {
  chrome.kill(); // Never gets here, so no access to chrome variable
});
```

> What happens if you try and connect to the port from another process (just via require('net').createConnection() while Chrome is open?

This works.

> You can also try manually increasing the interval for ECONNREFUSED to something much greater than 500ms as that seemed to have fixed the issue for others
(GoogleChrome/chrome-launcher#19), though it sounds like that's just a variation on your bullet 1

That's a bingo! It works beautifully if I increase `pollInterval` from 500ms to 10000ms.

I'm guessing it's different from bullet 1 because in that case I had no control over when `chrome-launcher` tried to connect to the launched Chrome instance. All I could do was delay when the Chrome instance was launched, working under the assumption that at boot time there was some resource not ready, and that delaying it might allow that to become ready. However I tried 20+ seconds of delay to no avail.

So the mystery I guess is why `pollInterval` needs to be longer when the `nodejs` process was started by `systemd` during boot (even when delayed until long after booting is done), rather than when it is created after booting has completed. Perhaps it has some sort of lower priority which slows it enough that 500ms isn't enough to make the connection, although with a localhost connection 500ms is pretty long, even if the process is low priority. This is also hard to explain because you'd imagine when using my dirty crash and restart hack it would still have whatever lower priority it previously had, since `systemd` is still the one starting it back up after it crashes. Might be a Linux quirk where the priority depends on how much CPU usage is going on at the time that it starts up, and the system is otherwise idle when the crash and restart occurs. Just pondering out loud here.

Thanks for the suggestion which works around the issue, now I can remove my dirty hack. Consider me a +1 for https://github.com/GoogleChrome/chrome-launcher/pull/19 as having the config option would be a viable workaround. I also didn't see that `chrome-launcher` had a separate repo (Google searches lead to the sub-directory in this repo) so apologies if this was the wrong repo to open the issue on.

**Comment by patrickhulce** [comment]
Oh that's great to hear it fixes the issue! 🎉 

And no worries we *just* split it out into it's own repo and are in the middle of a transition period, so handling issues on both for the time being 😄
