### ISSUE TITLE
without-javascript should bypass ServiceWorker

### ISSUE THREAD

**Issue by topaxi** [GoogleChrome/lighthouse#3276]
We are caching an empty `index.html` for `text/html` requests using a ServiceWorker. Lighthouse then reports "Does not provide fallback content when JavaScript is not available", even though we render HTML on our backend on normal HTTP requests.

**Comment by patrickhulce** [comment]
Hey @topaxi thanks for the report! We've got a tracking issue for this over in #2096 and is indeed a bug in Chrome. Closing this as a duplicate but feel free to comment over there with any new findings!
