### ISSUE TITLE
Expose ability to export a report to a shareable URL

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#328]
For most of the Lighthouse reports I've been generating, I need the ability to easily link to a snapshot of the report from slides/tweets/etc. Print/Save to PDF is currently supplied as an option, but this is a little cumbersome and doesn't have the same data sharing convenience of a URL. Use case: I'm claiming PWA score N or FMC M in a slide - I'd like to show the full breakdown of what the report said.

If this type of functionality is best left to tools like WebPageTest, happy to defer to when it might use Lighthouse. Just a suggestion :) I'm otherwise manually copy/pasta'ing reports to gists.

**Comment by brendankenny** [comment]
Yeah, I agree. Since the extension report is just a webpage, my first instinct is to copy and paste the url to share, which of course won't work :)

Right now it's simple enough that you could probably encode all the report information in the URL, but we're about to add a lot more information (like the critical network chains), so that will quickly stop being an option.

To do this right, I think we'd need some kind of save/load file functionality (like traces and profiles in DevTools) with all the pain that brings with sharing files and instructing people how to view them, or ideally an actual web service where these reports can be saved.

In the meantime we can make them easier to copy/paste into gists in a readable form if you are hitting any obvious pain points there.

**Comment by addyosmani** [comment]
A copy/paste mode that either outputs markdown or just the raw HTML being output would be super helpful. I was going to suggest a 'Post to JSBin' option (you can post HTML to their API to create new bins) but was unsure if that would be considered an abuse of the service :)

**Comment by kdzwinel** [comment]
Publishing markdown version of the report as a gist makes more sense to me and it is as simple as creating a bin:

```
fetch('https://api.github.com/gists', {
  method: 'POST',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    files: {
      'report.md': {
        content: 'Markdown goes here'
      }
    },
    description: 'Lighthouse report for http://example.com',
    public: false
  })
}).then(res => res.json()).then(data => console.log(data.html_url)).catch(e => console.error(e));
```

**Comment by addyosmani** [comment]
I would be down for a markdown version of the report. It's better than the current copy/pasta/format cycle :)

**Comment by wardpeet** [comment]
@addyosmani @paulirish Are we still wanting this?
If so what scenario? Just markdown export, push to gist/jsbin, ...

**Comment by paulirish** [comment]
I think we're always going to have a richer HTML report than whatever we do in markdown, etc. I'd prefer investing in that direction, despite the markdown/gist being easy to do.

---------------

I wonder if we could beam the JSON to moonlight and have that provide us a URL of the html report. cc @crhym3

**Comment by crhym3** [comment]
@paulirish it's an interesting suggestion, but wouldn't it collide with moonlight's own tests? I mean, how would that relate to the audits executed by moonlight.

This seems more of a storage question to me, where lighthouse could support different storage backends (or even just define and consume a storage API provided by plugins): S3, Google Cloud Storage, Drive, Dropbox, etc.

**Comment by paulirish** [comment]
Yup, it's totally a storage question. Admittedly it has nothing to do with the moonlight-driven audits. 

The ideal situation is that with no setup at all, we get a single URL for each run.

**Comment by crhym3** [comment]
That was in my next question :)
How much lighthouse audits are reproducible exactly based on the environment? E.g. OS, network conditions, available memory, CPU, etc.

**Comment by ebidel** [comment]
We've had report sharing for a while via the Viewer and Github.

---

In the next release, from an HTML report created using the CLI or Extension, you'll see an "Open in Viewer" button:

<img width="163" alt="screen shot 2017-01-19 at 10 29 02 pm" src="https://cloud.githubusercontent.com/assets/238208/22138693/c457a78e-de96-11e6-97d0-3e57856dbfb5.png">

Clicking that will open the repot in the Viewer (googlechrome.github.io/lighthouse/viewer/). From there, users can share their report by signing in to Github and saving the report as a gist.

<img width="226" alt="screen shot 2017-01-19 at 10 31 51 pm" src="https://cloud.githubusercontent.com/assets/238208/22138758/1967bf84-de97-11e6-9fa1-2f074c400208.png">

That will create a deep link, shareable to the world.
---
We'll probably figure out something slightly different for the future (e.g. webpagetest integration), but for now, sharing is caring!...and works :)

**Comment by joelhsmith** [comment]
FYI @addyosmani if you still need a markdown version of the report, me and a couple guys built something like that.  It imports a Lighthouse JSON file.  It is set up so you can create custom templates, so you can add custom boilerplate text for each issue. Another cool feature is that it takes screen shots of failing elements.

I am looking for Alpha testers. Its command line only for now, but it has a Dockerfile, so you can just build and run it without installing any requirements.
https://github.com/OpenAssessItToolkit/openassessit

**Comment by EdPike365** [comment]
I want to share a link with a "civilian" so that they can go to a page, dev tools will open, the lighthouse report will run and they will be impressed by the 100s and confetti animation. A third party URL that takes the site as a param and would imitate the experience would be cool. Actually, I could do this!
