### ISSUE TITLE
Reference Device & Network Conditions => Throttling & Emulation

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#33]
### Reference Device & Network Conditions

**Network Latency**
-  `150ms RTT` is a reasonable approximation for "typical mobile" 
  - First 14K [can be delivered with TCP/TLS handshakes 
    in](http://calendar.perfplanet.com/2015/tcp-download-breakpoints/) 4 round 
    trips.
  - 150ms is ~= 57th percentile mobile latency
    - Based on industry research data 
    - 57ms at 10th percentile. 135ms at 50th. 853ms at 90th.
    - 85ms to 280ms hits the quartiles. 
    - 150ms is memorable and representative. 
  - ( 150ms latency * 4 RTTs ) = 600ms 
  - 1000ms = 600ms transfer time + 100ms server response time + 150ms [control 
    plane](https://docs.google.com/presentation/d/1IRHyU7_crIiCjl0Gvue0WY3eY_eYvFQvSfwQouW9368/present?slide=id.gebc26cd7_8_0) + 150ms rendering
    - see also [Mobile Analysis in PageSpeed Insights](https://developers.google.com/speed/docs/insights/mobile#adapting-to-high-latency-mobile-networks)
- `500ms` (~85th percentile) would be a good approximation for "typical slow mobile"

**Network throughput**
- `1.6Mbps` download throughput
  - 1.6 is used in WebPageTest's 3g preset. WebPageTest experimented to find 
    its preset sweet spots and used 
    [facebook/augmented-traffic-control](https://github.com/facebook/augmented-traffic-control/tree/master/utils/profiles) 
    originally.
  - Still seeking improved numbers for typical and typical-slow mobile 
    throughput. 
    [crbug/590880](https://bugs.chromium.org/p/chromium/issues/detail?id=590880) 

**Device Class**
- `Nexus 5` for now.
  - [https://github.com/facebook/device-year-class](https://github.com/facebook/device-year-class) 
    approaches this problem. Others have looked at instruction count as a 
    proxy.

---
#### Implementation
- [`emulateNetworkConditions`](https://chromedevtools.github.io/debugger-protocol-viewer/Network/#method-emulateNetworkConditions) should be set for the page and SW
- [`setCPUThrottlingRate`](https://chromedevtools.github.io/debugger-protocol-viewer/Emulation/#method-setCPUThrottlingRate) can help us approximate. 
  - Until calibration is implemented on the devtools backend, we may need to do a calibration run ourselves. 
  - Let's doublecheck with @a1ph about Windows, as original commit says POSIX support only. 
  - Workers [may be blacklisted](https://bugs.chromium.org/p/chromium/issues/detail?id=436111#c13), let's also check about throttling service worker

**Comment by paulirish** [comment]
2586e69e91e2269f77af58bf470418444d45d9f3 flipped on latency and throughput throttling, so this is partially fixed.

**Comment by paulirish** [comment]
[[public] 2G Network Issues observed while in India - Google Slides](https://docs.google.com/presentation/d/1fZ7ftsJJ4adiPov4y_8AtV_zjqAmEASaSxRBHBwkiOw/edit?pref=2&pli=1#slide=id.g73cf3c208_0_158) will help inform for any presets we define for a "typical emerging market mobile user" persona

**Comment by addyosmani** [comment]
Support for CPU throttling came up in chat today and (as you've already pointed out), [setCPUThrottlingRate](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Emulation/#method-setCPUThrottlingRate) appears to be experimentally supported in the DevTools procotol. How feasible might it be for experimental CPU throttling to be explored? (keeping in mind the POSIX limitations may still be an issue)

**Comment by addyosmani** [comment]
Support for CPU throttling came up in chat today and (as you've already pointed out), [setCPUThrottlingRate](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Emulation/#method-setCPUThrottlingRate) appears to be experimentally supported in the DevTools procotol. How feasible might it be for experimental CPU throttling to be explored? (keeping in mind the POSIX limitations may still be an issue)

**Comment by addyosmani** [comment]
Support for CPU throttling came up in chat today and (as you've already pointed out), [setCPUThrottlingRate](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Emulation/#method-setCPUThrottlingRate) appears to be experimentally supported in the DevTools procotol. How feasible might it be for experimental CPU throttling to be explored? (keeping in mind the POSIX limitations may still be an issue)

**Comment by paulirish** [comment]
very feasible. 

hard part is mostly picking a multiplier that will be "mobileish" despite the machine running the test. We _could_ do a benchmarking pass to calibrate the machine and end up with a variable multiplier. 

But we can also save this for later, and just kick things off now with 5X. 

Along with adding CPU throttling, we should def  #568  ( communicating to users that network & cpu are being artificially throttled)

**Comment by addyosmani** [comment]
> hard part is mostly picking a multiplier that will be "mobileish" despite the machine running the test. We could do a benchmarking pass to calibrate the machine and end up with a variable multiplier.

Ooh. I like the idea of a calibration pass to supply a sensible mobile multiplier. 

> Along with adding CPU throttling, we should def #568 ( communicating to users that network & cpu are being artificially throttled)

I think most folks don't know (until they look at the source or old issues) what is and isn't throttled today, so better messaging this in the UI gets a big :+1:

**Comment by paulirish** [comment]
I think this is all set. As noted in another bug, we concluded that a calibrated CPU throttling rate actually has little effect on results.
