### ISSUE TITLE
Trailing comma - enable ESLint rule

### ISSUE THREAD

**Issue by kdzwinel** [GoogleChrome/lighthouse#3304]
It [looks like trailing comma is being prefered](https://github.com/GoogleChrome/lighthouse/pull/3227#discussion_r137820600), however it's not enforced by the current ESLint configuration. Should we [set it up](https://eslint.org/docs/rules/comma-dangle)?

**Comment by wardpeet** [comment]
Sounds great! @kdzwinel

**Comment by patrickhulce** [comment]
definitely! I believe @paulirish had a PR that did this once but it was around I/O and caused a ton of rebases, this is a quieter time that should be easier to do :)

**Comment by brendankenny** [comment]
qualified yes from me :P

I vaguely recall some cases where I didn't appreciate the new commas, but I can't think of what cases those would be now, so happy to see how it goes

**Comment by paulirish** [comment]
sg. let's do it.
