### ISSUE TITLE
Lighthouse: Feature Request

### ISSUE THREAD

**Issue by Jesna12** [GoogleChrome/lighthouse#3317]
Hi Team,

I was planning to use Lighthouse in my web Application which is used to test webpages.As of now, It is using google psi plugin to calculate the performance score of webpages.We are using google psi's api to call psi. As we cannot test performance of logged in pages using psi, we want to move from psi to lighthouse. But I came to know that there is no api available to call Lighthouse from my web App.
Is it possible to create one api for Lighthouse or that feature is already present?

Thanks In Advance!!

**Comment by patrickhulce** [comment]
@Jesna12 do you mean a REST API that you can call Lighthouse as a service without running it yourself?

There's a [node API](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically) you can use to get results locally, but if you're needing Lighthouse results based on an HTTP request you'll want to checkout some other [related integrations](https://github.com/GoogleChrome/lighthouse#lighthouse-integrations) ([treo.sh](https://treo.sh) is another new one that hasn't made it onto that list yet). WebPageTest is freely available for small scale testing and the others are paid services.

**Comment by ebidel** [comment]
https://github.com/ebidel/lighthouse-ci/#ci-backend-builder is an example of running Lighthouse on headless Chrome in the cloud. It has a REST API and spits back lighthouse JSON results.

While there's an endpoint you can test with, I recommend setting up your own server. Instructions [here](https://github.com/ebidel/lighthouse-ci/#running-your-own-ci-server).

**Comment by Jesna12** [comment]
Thank You so much @patrickhulce ,@ebidel .I will go through the examples you have mentioned.Hope that will solve my issue..

**Comment by patrickhulce** [comment]
Great! Feel free to come comment back here if you run into any issues.
