### ISSUE TITLE
Display in small dimension not in entire screen

### ISSUE THREAD

**Issue by LeMoussel** [GoogleChrome/lighthouse#3335]
Hi,
I'm using LightHouse programmatically like describe [here ](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically). It's run OK but I  got small display like this  

![image](https://user-images.githubusercontent.com/1816573/30438690-24d02456-9972-11e7-88c1-527339600756.png)

How can I get entire screen like this 

![image](https://user-images.githubusercontent.com/1816573/30438788-64a2fe6e-9972-11e7-9ff8-6ee48182efed.png)

Thanks for your help.

**Comment by patrickhulce** [comment]
@LeMoussel add the line `flags.disableDeviceEmulation = true` before you run lighthouse
