### ISSUE TITLE
Just Cannot run the demo: 'lighthouse https://airhorner.com/'

### ISSUE THREAD

**Issue by huangyingjie** [GoogleChrome/lighthouse#3343]
lighthouse version: 2.4
os: osx ei 10.11.6

````js
  status Retrieving devtoolsLog and network records +0ms
  GatherRunner:error no document request found http://airhorner.com/ +1ms
  status Disconnecting from browser... +0ms
````
It's strange that it only happens on my mac. Another mac that had set 'headless chrome' is all right.
I don't know whether this is the reason or not, and I'll try later.

**Comment by patrickhulce** [comment]
thanks for the report @huangyingjie! The problem is with Chrome Canary, there was a recent change to Chrome that broke this flow. You can use stable for now if you need to, but working in headless too is a great tip thanks!

**Comment by huangyingjie** [comment]
@patrickhulce My mac runs this normally has not installed Chrome Canary, thanks.
