### ISSUE TITLE
Custom audits in Chrome

### ISSUE THREAD

**Issue by codepodu** [GoogleChrome/lighthouse#3356]
I'm excited that Lighthouse is available by default as a part of Chrome browser!

As an author of development tools, I would like to build [custom audits](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit) as Chrome extensions, so that developers who use my tools can validate their usage by installing said extensions and running a regular Chrome audit.

I'd also like to chime in a +1 for #1532 because I'd like to validate across various screen sizes.

What do you folks think?

**Comment by chojar** [comment]
podkusilo mnie do instalacji u mnie chrome padlo po wgraniu narzedzia jak to usunac ?????????

**Comment by paulirish** [comment]
This sounds rad but we don't have plans to allow this sort of extensibility right now.

**Comment by chojar** [comment]
ok sprawa nieaktualna juz , udalo sie usunac to
