### ISSUE TITLE
Render-blocking script warnings should exclude <script type="module">

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/lighthouse#3359]
The logic here should be updated to check for the module attribute:
https://github.com/GoogleChrome/lighthouse/blob/63b4ac14d0a871ade0630db2885edd7848843243/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js#L32-L36

**Comment by paulirish** [comment]
Thx for filing. Good call.

**Comment by ThisIzKp** [comment]
Can I work on this?

FYI: I already merged my first feature to lighthouse sometime back. So, It is not actually `first bug` for me. Is it okay to work on these? I see a bunch of `first bug` lying around. I would love to do them all :)

**Comment by patrickhulce** [comment]
@ThisIzKp go for it! You're still early enough to take "good first bugs", and this one's high enough priority to not let it sit around :)

**Comment by paulirish** [comment]
@ThisIzKp are you taking this? no worries if not.. it's an easy one.

**Comment by ThisIzKp** [comment]
@paulirish You self assigned this to yourself, so I thought you're picking this up. I can work on it, if you haven't started it yet.

**Comment by ThisIzKp** [comment]
Small PR, so I'll do this today evening, will raise a PR by tomorrow :-)

**Comment by paulirish** [comment]
ok sounds good

**Comment by ThisIzKp** [comment]
@paulirish raised the PR, not sure about how to handle `nomodule` fallback. 
If `nomodule` fallback is `sync` by default then it is already covered by the existing code, but if `nomodule` fallback is `defer` (like type=`module`) then we need to handle that case also. 

Let me know your thoughts about that
