### ISSUE TITLE
Duplicated `DetailsRenderer.NodeDetailsJSON` type definition

### ISSUE THREAD

**Issue by kdzwinel** [GoogleChrome/lighthouse#3360]
https://github.com/GoogleChrome/lighthouse/blob/31bedc8ee298340c5aa41e4ae0a11ce12c75c0a7/lighthouse-core/report/v2/renderer/details-renderer.js#L337-L346

https://github.com/GoogleChrome/lighthouse/blob/31bedc8ee298340c5aa41e4ae0a11ce12c75c0a7/lighthouse-core/report/v2/renderer/details-renderer.js#L309-L318

**Comment by exterkamp** [comment]
This file doesn't exist anymore and modern details-renderer.js uses the new #7177 details typedefs.
