### ISSUE TITLE
Incorrect Audit error: Required OptimizedImages gatherer encountered an error:

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/lighthouse#3364]
I get the following errors under the sections "Optimize Images" and "Serve Images as WebP" whenever I run lighthouse (version 2.3.0) on my site ([philipwalton.com](https://philipwalton.com)).

> Audit error: Required OptimizedImages gatherer encountered an error: All image optimizations failed

![screen shot 2017-09-18 at 12 42 15 pm](https://user-images.githubusercontent.com/326742/30561328-7b26d156-9c6f-11e7-97c0-032fb288a24e.png)

Note: I don't get these errors when running lighthouse against other sites, so I'm not sure what it is about my site that's causing this. I've been noticing it for a few months now (not sure what version it started happening in unfortunately).

**Comment by philipwalton** [comment]
I tried to reduce this by commenting out certain portions of my HTML until the errors went away, and I was able to track down the root of the issue.

I'd generated a manifest via an online tool, and apparently the resulting files weren't optimized. When I remove these lines in the HTML, the errors went away.

```html
<link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
```

I still think there's room for improvement here though as it wasn't at all clear to me what the problem was. The UI made it look like it was a lighthouse runtime error rather than an issue with my source.

**Comment by patrickhulce** [comment]
thanks for the info here @philipwalton! it's probably an issue with multiple image frames in the icon PNG, I can look into it.

Are you running this in stable or canary?

**Comment by philipwalton** [comment]
I was seeing it in lighthouse 2.3.0, and I saw it in devtools and the extension, stable and canary, but it was always 2.3.0 IIRC.

**Comment by patrickhulce** [comment]
Hm, ok. It seems the latest method of resizing images in master has already fixed this.
![image](https://user-images.githubusercontent.com/2301202/30758413-04dd190e-9f6e-11e7-921e-2dc19a294bce.png)

**Comment by philipwalton** [comment]
Hmmm, but I've also already optimized and redeployed the optimized versions of those image.

Try this URL: I've deployed an old version of the site to my staging server and I'm seeing the errors in lighthouse 2.3.0: https://philipwalton-staging.firebaseapp.com/

**Comment by patrickhulce** [comment]
Yep still no issues on master, there was a render-blocking stylesheet on that older version, or is that a bug?

![image](https://user-images.githubusercontent.com/2301202/30766533-6ed5121c-9f91-11e7-8434-19d4030a7229.png)

**Comment by philipwalton** [comment]
Great! Yeah, that was a `<link rel="stylesheet">` in the head which I've since inlined, so that's why it's not showing up anymore.

So are the errors/warnings not showing up at all? Is that a problem (since it turned out that they actually *weren't* optimized)?

_[/me ...installing lighthouse locally, so I don't have to keep asking you things I could find out myself...]_

**Comment by patrickhulce** [comment]
Oh really? How big are those icon files? We ignore savings under 4kb so if it was minimal we'll still hide it.

**Comment by philipwalton** [comment]
Weird, because before optimizing:

```
➜  blog git:(master) ✗ ls -la assets/images | grep favicon
-rw-r--r--   1 philipwalton  eng   429 Aug  4 18:17 favicon-16x16.png
-rw-r--r--   1 philipwalton  eng   585 Aug  4 18:17 favicon-32x32.png
```

and after optimizing:

```
➜  blog git:(master) ✗ ls -la build/static | grep favicon
-rw-r--r--   1 philipwalton  eng     328 Sep 24 14:47 favicon-16x16-ba486c1ce6.png
-rw-r--r--   1 philipwalton  eng     486 Sep 24 14:47 favicon-32x32-b7d15bf8df.png
```

So while it was around a 24% and 17% savings, it's a lot less than 4K.

**Comment by patrickhulce** [comment]
Cool, gonna go ahead and mark this as closed then, since it's WAI in master 👍
