### ISSUE TITLE
Question about First Meaningful Paint

### ISSUE THREAD

**Issue by coryrylan** [GoogleChrome/lighthouse#3365]
Running lighthouse on a SSR Angular app I am working on has increased the First Meaningful Paint recently and I'm not quite sure why. My guess is it could be waiting on the icon fonts or lazy loaded images? Any guidance here would be appreciated. I'm not sure what to change to improve on the First Meaningful Paint test.  The html and css is rendered usually within the first few seconds but First Meaningful Paint is occurring much later. Sorry if this is not the correct place to ask this. If there is a community chat I'd be happy to post there.

![capture](https://user-images.githubusercontent.com/2021067/30562626-b9300cfa-9c84-11e7-9b44-c735ea7486b9.PNG)

https://www.estatesales.net/v2/IL/Chicago

**Comment by coryrylan** [comment]
Going to try adjusting the lazy loading of the images first and will reopen if necessary.

**Comment by paulirish** [comment]
FMP is mostly based around the number of elements getting layout. The layouts with the most stuff going on are going to be the most significant..  (more or less)

My guess is there's some other components on the page being lazily instantiated.
