### ISSUE TITLE
Performance audit lists opengraph image to optimize

### ISSUE THREAD

**Issue by nhoizey** [GoogleChrome/lighthouse#3371]
I performed an audit on this page:
http://www.20minutes.fr/politique/2127407-20170905-politique-sport-violent-assez-souvent-cruel-scandaleusement-injuste-francois-bayrou-sort-silence

It tells me to optimize this image:

`https://img.20mn.fr/1CZqNmMvSmSf-xC8gu40eA/648x360_l-ancien-ministre-de-la-justice-commente-pour-la-premiere-fois-les-raisons-de-sa-demission`

![image](https://user-images.githubusercontent.com/78213/30588328-94a6aa80-9d36-11e7-8a8a-6812cdec2eda.png)

But this image is not in the rendered page:
![image](https://user-images.githubusercontent.com/78213/30588174-03e19bf4-9d36-11e7-91c3-ce69a3501a7e.png)

It's the opengraph image for Facebook, Twitter and others:
![image](https://user-images.githubusercontent.com/78213/30588400-d58f045c-9d36-11e7-88cc-3087711e806e.png)

It should not be considered in a performance audit, IMHO.

**Comment by paulirish** [comment]
thanks for the detailed bug report. :) really good.

I'm seeing something a little different. I got these two images reported in "Properly size images":

![image](https://user-images.githubusercontent.com/39191/30627497-8e4f281c-9e0b-11e7-9190-feeb69200796.png)

TBH it's kind of a pain to get the real URL here. I opened devtools to extract the `title` attribute. Gross.. but yeah.

Here's the first: 
![image](https://user-images.githubusercontent.com/39191/30627529-bc1f42fe-9e0b-11e7-9037-96432d11b85a.png)

Here's the second: 
![image](https://user-images.githubusercontent.com/39191/30627517-adbfc134-9e0b-11e7-833f-a758a93fea1d.png)


For this and the other tests.... only images used in <img> tags and css backgrounds will be considered.

**Comment by nhoizey** [comment]
You're right, the same photo is loaded twice in the page (we will remove one soon).

On desktop:
- one 960 pixels wide
- one 1200 pixels wide

But the report told me a 648 pixels wide version needs to be optimized. This size is only used for opengraph.

So, this is an image used "in a tag", but not a tag that should be considered for the page's performance audit, IMHO.

**Comment by paulirish** [comment]
lol i wrote "`in <img> tags`" but ... it rendered it to HTML. whoooops :)

So our implementation should only be considering `<img>` tags and background images.. (So even if the opengraph one was downloaded randomly I wouldn't expect it to show up).

https://github.com/GoogleChrome/lighthouse/blob/c780dfac1efac2e3debe6ebd7958d48cf2e42721/lighthouse-core/gather/gatherers/image-usage.js#L92

Can you verify that the exact URL in the `[title]` tag in the lighthouse report is the exact same as the og:image (and not used elsewhere)?

**Comment by nhoizey** [comment]
Whooops indeed! ;-)

I checked several times that this image URL (the one in the `[title]`) is only used for opengraph's `og:image` and Twitter's `twitter:image` meta tags. This 648 pixels size is not part of our responsive images sizes.

I also checked it is never loaded with the network tab of the devtools.

You'll find the report's JSON attached, if it can help. Just look for `648` in it.
[www.20minutes.fr-20170920T104554.zip](https://github.com/GoogleChrome/lighthouse/files/1317129/www.20minutes.fr-20170920T104554.zip)

**Comment by patrickhulce** [comment]
@nhoizey the 648 version seems to be used in the page and is one of the first image network requests.

![image](https://user-images.githubusercontent.com/2301202/31090050-204554d2-a75b-11e7-8bb9-3f03575cd000.png)
![image](https://user-images.githubusercontent.com/2301202/31090063-2f1e9f9a-a75b-11e7-9684-04b2aecafb76.png)

As @paulirish states, we only pull images from `img` tags or CSS background images. Additionally, we throw out images that do not have a corresponding network request. If you're having trouble finding out where an image we're highlighting is, this is the snippet I used to find the reference in this case `[...document.querySelectorAll('img')].map(x => [x, x.src])`
