### ISSUE TITLE
Unable to locate and launch chrome canary.

### ISSUE THREAD

**Issue by hemanth** [GoogleChrome/lighthouse#339]
Two cases:

1. When the chrome installer is mounted.
2. Even after the chrome canary is installed.

First one can be fixed by enhancing the `grep` [RE](https://github.com/GoogleChrome/lighthouse/blob/master/scripts/launch-chrome.sh#L8) to check for `/Applications/`

`"$CHROME_CANARY_PATH` looks like: `/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary` looks like we needs some escaping here.

//cc @paullewis

**Comment by boopathi** [comment]
Already discussed here - https://github.com/GoogleChrome/lighthouse/issues/311
