### ISSUE TITLE
Using same browser for inspecting simultaneously multiple tabs.

### ISSUE THREAD

**Issue by sdeprez** [GoogleChrome/lighthouse#3393]
I encounter a bug when using the same browser and running multiple lighthouse on it (whether in the shell or through node package):

```
./chromium/chrome --remote-debugging-port=9222
lighthouse http://url-1.com --port=9222
# In another shell
lighthouse http://url-2.com --port=9222
```
Where chrome is the latest executable download from https://download-chromium.appspot.com/ (on Ubuntu x64 16.04)

Which yield issue #1091 

> Runtime error encountered: Error: Protocol error (Tracing.start): Tracing is already started
>     at callback.resolve.Promise.resolve.then._ (/home/seb/Madumbo/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:95:17)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> Error: Protocol error (Tracing.start): Tracing is already started
>     at callback.resolve.Promise.resolve.then._ (/home/seb/Madumbo/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:95:17)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

However it is possible to attach (programmatically) multiple agents on each tab (using https://github.com/cyrus-and/chrome-remote-interface for instance) and to manipulate them, so is it possible somehow to instruct Lighthouse to open a new tab for each url and do all the audits, but all on the same browser ?

My use case is to test multiple urls that require some settings of the browser (like authentification for instance) so that'd be much more convenient if I could use a single shared browser. 

Or it's not possible, do you see any workaround to avoid spanning a new browser for each test (and still do the test in parallel)?

Thanks in advance!

**Comment by patrickhulce** [comment]
Unfortunately tracing (required for several performance audits) is browser-wide and so cannot be started multiple times, hence the error you received. 

You might be able to run some subset of the audits in parallel with Lighthouse using the `settings.onlyAudits` property in your custom config to target the ones you're interested in that don't require tracing, but be aware that tabs running in the background behave differently than foreground tabs and YMMV w/r/t animations, screenshots, performance, etc. You could use the `--disable-background-timer-throttling` Chrome flag at least to attempt to mitigate some of these issues, but your best bet will be distinct Chrome instances on different ports.

**Comment by sdeprez** [comment]
Thanks for your answer, unfortunately it probably settles the issue, so as for me, it can be closed. I'll try your workarounds and give updates if successful!
