### ISSUE TITLE
make possible to disable chrome to offer saving password in chrome-launcher

### ISSUE THREAD

**Issue by ciekawy** [GoogleChrome/lighthouse#3394]
there was `--disable-save-password-bubble` which has been apparently removed: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1015

also I can see no option to set prefs as suggested in the above link

**Comment by patrickhulce** [comment]
@ciekawy thanks for the report! would you mind refiling this in the new separate chrome launcher repo? https://github.com/GoogleChrome/chrome-launcher thanks!
