### ISSUE TITLE
LightHouse not detecting service worker but add to home screen banner is coming on chrome

### ISSUE THREAD

**Issue by sarohiharsh4u** [GoogleChrome/lighthouse#3405]
I am getting add to home screen popup but lighthouse is showing no service worker. 
Url -https://www.fabhotels.com

**Comment by patrickhulce** [comment]
It appears that your service worker script is not always being served properly. This is what I got when trying to verify your service worker was functioning in Chrome.

![image](https://user-images.githubusercontent.com/2301202/31089449-f8fdbe2a-a758-11e7-867d-3c08ece8a109.png)

curling your service worker makes it look like it is redirecting to the main document instead?

```
curl -v https://www.fabhotels.com/service-worker.js
*   Trying 104.96.97.131...
* TCP_NODELAY set
* Connected to www.fabhotels.com (104.96.97.131) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.fabhotels.com
* Server certificate: GeoTrust SSL CA - G3
* Server certificate: GeoTrust Global CA
> GET /service-worker.js HTTP/1.1
> Host: www.fabhotels.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 302 Moved Temporarily
< Content-Type: text/html; charset=UTF-8
< Location: https://www.fabhotels.com/
```


Also friendly FYI, there seems to be a bug in your service worker. `event.request.url === '/'` is never true, and so the site doesn't respond with a 200

**Comment by sarohiharsh4u** [comment]
It is getting registered. Thats the reason we are getting App install banner.
![screen shot 2017-10-03 at 11 55 51 am](https://user-images.githubusercontent.com/30202644/31112537-e9bf70d2-a831-11e7-8ac7-99dc99412adb.png)
