### ISSUE TITLE
Add audit for Broken skip links 

### ISSUE THREAD

**Issue by joelhsmith** [GoogleChrome/lighthouse#3409]
If a "skip link to main content" link (which are also known as navigation skip mechanisms or [bypass blocks](https://webaim.org/standards/wcag/checklist#sc2.4.1)) is broken it could cause a keyboard-only user to tab through an entire menu to get to the content.  

Example of bypass block:

```
<a href="#main-content" class="element-invisible element-focusable">
Skip to main content
</a>
```
Can we test if the ID target of the bypass block exists elsewhere in the markup?

**Comment by paulirish** [comment]
Good idea... Looking at axe... it has `href-no-hash` described as "Ensures that href values are valid link references to promote only using anchors as links"... 

However it only looks to see the value isn't `=== '#'` and otherwise passes. Doesn't verify the in-page destination is present in the DOM.

Seems like it should, or there should be another.  Yah.

+@robdodson in case you know more..

**Comment by WilcoFiers** [comment]
@paulirish There's a best-practice rule that checks specifically for skiplinks: https://github.com/dequelabs/axe-core/blob/develop/lib/rules/skip-link.json There's also the bypass rule which checks for skiplinks, headings and landmarks. If any one of them is present it passes. https://github.com/dequelabs/axe-core/blob/develop/lib/rules/bypass.json

Does that cover the cases you're asking for? aXe doesn't test for all internal links that their target exists, which I think is correct as those aren't necessarily accessibility issues.

**Comment by joelhsmith** [comment]
I have tested this issue on both Axe and Lighthouse and they both miss the violation.

According to W3C "[Adding a link at the top of each page that goes directly to the main content area](https://www.w3.org/TR/WCAG20-TECHS/G1.html)" that functions is required.

> "If this is a sufficient technique for a success criterion, failing this test procedure does not necessarily mean that the success criterion has not been satisfied in some other way, only that this technique has not been successfully implemented and _can not be used to claim conformance._"

@WilcoFiers are you proposing that it works as designed because of the caveat at the end of the sentence?

If we are checking for _conformance_, IMO it should check if the first bypass block is missing its target, and it should be a violation.

I totally agree that we do not want to check for all internal links, just the link that is required to pass the success criterion.

**Comment by robdodson** [comment]
> According to W3C "Adding a link at the top of each page that goes directly to the main content area" that functions is required.

Just to clarify, I don't think adding a skip link is the only mechanism to satisfy WCAG here  because there are other ways of skipping to the main content. Using ARIA landmark roles, as noted in [the success techniques for 2.4.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html#navigation-mechanisms-skip-techniques-head) would work as well.

Having said that, I think checking that the id for the internal link exists could be a useful addition.

**Comment by WilcoFiers** [comment]
The `skip-link` rule is disabled by default. I think that was done to prevent requiring both skiplinks and landmarks. We're talking about changing that behaviour though. Have you tried running it with the `skip-link` rule turned on? Does that still not catch your particular testcase? If so, can you provide a code snippet of it?

https://github.com/dequelabs/axe-core/tree/develop/lib/checks

**Comment by joelhsmith** [comment]
> The skip-link rule is disabled by default. I think that was done to prevent requiring both `skiplinks` and landmarks. 

Landmarks are helpful for most assistive technologies and can be an alternate method of providing bypass-block functionality, but cannot be used to claim conformance with the 2.4.1 bypass-block success criterion. Some people who rely on keyboard accessibility do not use assistive technologies. If one of the options is not on by default for this success criterion, it should be Landmarks because Landmarks are not required to meet WCAG.

> Have you tried running it with the `skip-link` rule turned on?

Are there options in Lighthouse to enable/disable specific rules? I don't see any documentation of those options using the command line interface or the browser extension. 

@WilcoFiers thanks for cross-referencing the issue to Axe, I will subscribe to that thread.

**Comment by WilcoFiers** [comment]
@joelhsmith Our understanding of 2.4.1 is that there are different things you could do, any one of them allows you to pass 2.4.1. One of them is to [use skiplinks](https://www.w3.org/TR/WCAG20-TECHS/G1.html), another is to [use landmarks](https://www.w3.org/TR/WCAG20-TECHS/ARIA11.html). If you have either one of these, aXe will pass the `bypass` rule. If you enable the `skip-link` rule axe will fail if the page doesn't have a skiplink. I did propose we change that to just have it test that the skiplink points to a focusable (and existing) element. Is that what you mean also, or are we talking about an interpretation difference here?

**Comment by joelhsmith** [comment]
The most accessible thing to do is require `skip-link`s, even if there is a Landmark caveat to meeting 2.4.1.  I know you all have a ton of stuff to do, so I won't belabor the point any further :-) This is sorta bordering on a meta-issue at this point.

@WilcoFiers Thank you for referring the issue to the axe-core queue.  Since this request is in there, should this issue be closed?

**Comment by robdodson** [comment]
I'm ok with closing it. For now we're using the bypass rule, but if axe later decides to update that rule to require skiplinks it'll just get downstreamed into Lighthouse whenever they ship a new version.
