### ISSUE TITLE
Warn when devtools is open

### ISSUE THREAD

**Issue by boopathi** [GoogleChrome/lighthouse#343]
When trying to use lighthouse with devtools open, we will now get an error saying "Another debugger is attached". Would it be useful to display "You probably have devtools open or something else is debugging your current tab. Close them to use lighthouse".

I tried something and it ended up not so clean - https://github.com/boopathi/lighthouse/commit/75a66ac8a84f35cf46864134f87dcd832f512630

**Comment by paulirish** [comment]
This seems good.  left another comment on https://github.com/boopathi/lighthouse/commit/75a66ac8a84f35cf46864134f87dcd832f512630
