### ISSUE TITLE
iframes shouldn't be considered critical requests

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#3443]
While they are fetched at Highest priority, they are not render-blocking.

I can't think of a decent reason why we want to consider iframes "critical". Anyone else?

If no, I'll exclude them (and their children) from the CRC tree.

--------

Here's the yotuube iframe in the paulirish.com crc tree:
![image](https://user-images.githubusercontent.com/39191/31036518-6c15f98e-a521-11e7-9076-48e9cf607be1.png)

----

Side note **we should also remove data URI's**. They aren't really network requests as far as CRC cares. From washingtonpost's crc:

![image](https://user-images.githubusercontent.com/39191/31096862-3a3883f2-a772-11e7-9ba4-bf127979f669.png)

We can easily remove leaf node data uri's, but non-leaf probably have to remain.

**Comment by ThisIzKp** [comment]
I think, Iframe blocks the `onload` event of parent from firing. 
Will it not affect the parent in any way if the iframe resource takes too long to fetch ?

**Comment by paulirish** [comment]
> I think, Iframe blocks the onload event of parent from firing.

this is true.

> Will it not affect the parent in any way if the iframe resource takes too long to fetch?

Well it'll delay the onload event so any script bound to that event will be delayed. But usually that is all low priority stuff, so it's not important for us.
 
Aside from the onload event, iframes don't have any layout-blocking characteristics. They can conceivably add network contention and main thread contention, though.

**Comment by asolove-stripe** [comment]
Is there a way to set this back via config? Or a custom audit that allows waiting for and measuring iframe load performance? (I completely understand why this was the right decision for lighthouse in general, but happen to have a specific case where I'd love to get iframe-aware timings.)

**Comment by patrickhulce** [comment]
Nothing really can be done just config-wise for this @asolove-stripe, but writing a custom audit to take a look at the network records of iframes should be pretty straightforward :)

If you haven't already you can take a look at the [custom audit recipe](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit) and peruse our source for examples of `artifacts.devtoolsLogs[Audit.DEFAULT_PASS]` and `artifacts.requestNetworkRecords` for how to inspect network records

**Comment by asolove-stripe** [comment]
Great, thanks for the pointers on what to grep for!
