### ISSUE TITLE
Improved dynamic report width in DevTools

### ISSUE THREAD

**Issue by zhuangyin8** [GoogleChrome/lighthouse#3446]
![image](https://user-images.githubusercontent.com/20805894/31042769-04fcac90-a5e2-11e7-8d37-080040fdd543.png)

Version 63.0.3227.0 (Official Build) canary (64-bit)

Can not adapt the width of the development tool

**Comment by ThisIzKp** [comment]
@zhuangyin8 Am I missing something? I don't see any issue in the above image. 
Can you please give more information regarding the issue you're facing

**Comment by zhuangyin8** [comment]
Can not adapt the width of the development tool

**Comment by patrickhulce** [comment]
@zhuangyin8 is the request for the report to take up the full width of the DevTools window?

**Comment by zhuangyin8** [comment]
@patrickhulce yes,it should be.

**Comment by brendankenny** [comment]
it's always centered now, so...better at least :)
