### ISSUE TITLE
Question on running Lighthouse through cli with custom configuration

### ISSUE THREAD

**Issue by joelhsmith** [GoogleChrome/lighthouse#3455]
I see you can "Runs Lighthouse with your own configuration: custom audits, report generation, etc." by passing the `--config-path` flag.

Is there any documentation on what goes in the actual config file?

**Comment by patrickhulce** [comment]
Yessir there is! 

* [Configuration docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md)
* [Custom audit recipe](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit)

Feel free to chime in here again if there's something you want answered that isn't in those docs.
