### ISSUE TITLE
Audit: Resources are served minified

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#3459]
(Broken out from #909)

PSI currently considers HTML as well as CSS & JS. We can start with JS & CSS and later add support for considering HTML minification.

Required data:
* URLs lacking minification
* For each, potential byte savings 

More: https://developers.google.com/speed/docs/insights/MinifyResources

(Will likely take ~2 sprint to complete)

**Comment by vinamratasingal** [comment]
Patrick will research the JS part of this, Brendan will finish research/start implementation on the HTML/CSS part of this audit.

**Comment by patrickhulce** [comment]
looked into what's necessary for PSI-parity here. Bad news: they've built their own custom JS lexer and minifier that does some variation of what jsmin and uglify do. I see a few options here in increasing order of appeal...

* Build and maintain a PSI-equivalent JS parser and minifier - really don't want to have to do this, we're stretched thin enough as it is
* Use uglify2/babili/some other library for minification - this is going to be **really** slow, usually around 100-300kb/second so the average site with 1MB of JS will spend ~3-10 seconds in this audit alone. cnn.com for example has ~2MB of gzipped JS which explodes to ~6MB of raw JS which corresponds to ~18-60 seconds spent in this audit.
* Use some heuristics/simplified lexer to identify unminified JS - this is going to be much less accurate but if all we're really looking for is ballpark figures anyway we can probably get close enough here. A super simple lexer that just counts whitespace, comments, and local variable declarations might be good enough here.

I'd prefer to explore option 3 and see how it compares to uglify2 on some popular JS libraries.

**Comment by paulirish** [comment]
status: 

* #3950 handles JS
* we plan on doing CSS with whitespace stripping only. we'll evaluate how close these numbers are
* we currently don't plan to continue with HTML minification.
