### ISSUE TITLE
Evaluate metrics accuracy to Chrome UⓚⓜX Report data

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#3462]
With the dashboard from #3461, HTTP Archive data can be used to track the audits that error the most and the `debugString`s they produce, catching possible regressions and informing where to put effort into making audits more robust. The data and queries already exist, so we really just need to a place to display it (#3461).

We also discussed enabling Sentry for the HTTP Archive runs, which would allow much of that data to be collected automatically. If that happens, the HTTP Archive could instead be used for tracking more complicated errors than Sentry might allow (e.g. situations with failures more complicated than tracking Errors and explicitly emitted Sentry events).

----

We want to quantify:

* error rate via debugString, etc - will be handled by Sentry collection.
* metrics stability - drift to browser changes (plznavigate, etc) or our changes.

**Comment by vinamratasingal** [comment]
In addition, can we add the following analysis: 

- Correlating Lighthouse FCP, TTI, and FMP vs UKM FCP, TTI, FMP data (we can leverage Chrome UX report). 
- Correlating Lantern FCP, TTI, and FMP vs UKM FCP, TTI, FMP data (we can leverage Chrome UX report). 

Short term deliverable: doc. Let's worry about the long term solution lantern.

**Comment by patrickhulce** [comment]
Quick update here:

* extensive variability data and analysis for Lighthouse in DT/Lantern/Lighthouse on WPT available [here](https://docs.google.com/document/d/1D4z33t3YeVy2dP0lJmA8n2ySnrsZTov_Mp4RFZ9Ve_Q/edit)
* error rates via debugString we have from Sentry and HTTPArchive
* Metric stability via HTTPArchive probably isn't worth it given the variability we can expect from run to run with WPT throttling, we should dedicate a much smaller sample of URLs to 9+ runs after each release if we want to continue with this analysis
* Public Chrome UX report data is per-origin and also probably not worth it from accuracy standpoint, will look into UKM private access for this if necessary

**Comment by patrickhulce** [comment]
I'm going to go ahead and mark this particular issue as closed. Analysis has been done, and we'll need to find another method to support these conclusions 

from [internal analysis doc](https://docs.google.com/document/d/1uwHlG1s8H96RVEWOR6QH6WE4MFKCi8comU337XfuEGo/edit?ts=5a7761fd#)

> In practice, the relationship between median lab and field data is extremely weak. Furthermore, acquiring data with high enough fidelity on the necessary dimensions for meaningful analysis is quite difficult, requires substantial engineering investment, and carries significant privacy concerns. Additionally, it is not even clear what course of action would change even if more accurate data were obtained. 
For these reasons, I recommend no further investigation into the relationship between median lab metric data and field metric data at this time.


### High Level Reasons for Findings
* Broadness of Effective Connection Type
* Mixture of Device Class in Field Data
* Unique Pages Served for Identical URLs
* Intentional Lab Trade-offs
