### ISSUE TITLE
Extension Error: Protocol error (Emulation.setCPUThrottlingRate): Unknown deb

### ISSUE THREAD

**Issue by parknenok** [GoogleChrome/lighthouse#3468]
**Lighthouse Version**: 2.3.0
**Chrome Version**: 61.0.3163.100
**Initial URL**: https://rarejob.ph/
**Error Message**: Protocol error (Emulation.setCPUThrottlingRate): Unknown debugger protocol error.
**Stack Trace**:
```
Error: Protocol error (Emulation.setCPUThrottlingRate): Unknown debugger protocol error.
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9907:25)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by patrickhulce** [comment]
@parknenok was there anything notable about your environment or the steps you took before running Lighthouse?

**Comment by parknenok** [comment]
I was still browsing on a new window and I have 8 tabs open, also running xampp but the site that i was testing was already on a server

**Comment by patrickhulce** [comment]
Thanks for the additional info! We're lacking a good error message here, so not much more to do other than try to gather a better message and see what the real issue is next time around.

**Comment by brendankenny** [comment]
could be the same as #2752. @parknenok any chance you see "HP Network Check Launcher" if you visit `about:extensions` in your Chrome?

**Comment by parknenok** [comment]
Will check tomorrow when I can get a hold of my work laptop, thanks

**Comment by parknenok** [comment]
I had no extension like that, nor no application like that
