### ISSUE TITLE
manifest's "short_name" isn't required if "name" is short enough

### ISSUE THREAD

**Issue by NekR** [GoogleChrome/lighthouse#348]
See this thread for details: https://twitter.com/nekrtemplar/status/734483891071922182

Not sure about what is exactly "short enough", but 4 symbols seems to be.

**Comment by addyosmani** [comment]
Hopefully the ongoing work in https://github.com/GoogleChrome/lighthouse/pull/350 will nail this one down. Good find.

**Comment by NekR** [comment]
Great 👍
