### ISSUE TITLE
Run chrome as a part of lighthouse cli

### ISSUE THREAD

**Issue by boopathi** [GoogleChrome/lighthouse#349]
I've been trying some stuff with finding chrome and spawning it as a part of CLI.

`lighthouse <url>` 

1. When connection fails to Remote Debugger, try launch chrome
2. osx - find chrome and if there is more than 1 installation, use inquirer to let user select
3. I don't know how to tell when chrome remote-debugger is ready since I don't get any message or event that tells it's ready. So I poll(every 100ms) from the parent process(CLI) to connect to remote debugger and when it succeeds, we know that the remote-debugger is ready, then do lighthouse run.
4. Poll for fixed number of retries and then reject when it crosses the retry limit.
5. Kill chrome once everything is over - Only the chrome launched from the CLI is killed - not the one already running. 

Ported shell scripts to JS for finding and launching chrome. The code is here - https://github.com/GoogleChrome/lighthouse/compare/master...boopathi:launch-chrome-js 

Need some ideas and thoughts around this before I send a PR. Is this approach okay ? or do we want to keep running chrome as a separate foreground process?

Also, just curious, is there any other way to know that the remote-debugger has started when launched as a child process (instead of polling the port every 100ms)?

**Comment by wardpeet** [comment]
Probably better to wait for headless chrome?

**Comment by paulirish** [comment]
We should do this. #625 and #626 could definitely use it. And I feel better having a new fresh chrome for every run.

@boopathi your stuff here is **great**: https://github.com/GoogleChrome/lighthouse/compare/master...boopathi:launch-chrome-js is 

@hemanth and i have been talking about this recently too (over on pwmetrics). Do you two wanna tag team on this?

**Comment by boopathi** [comment]
Sure!  I'll get back to my laptop after my vacation and then rebase that branch and try something. :).

**Comment by paulirish** [comment]
awesome. :D

**Comment by hemanth** [comment]
Cool, it would be nice to tag team with Mr.Boopathi 🤓 

BTW digging for the same feature for [is-pwa](https://git.io/is-pwa) as well ;)

**Comment by paulirish** [comment]
fwiw: @wwchen of the devtools taem just wrote a little module along these lines: https://codereview.chromium.org/2337713002/  see `launch_chrome.js`

It's a little different as it only wants canary or chromium, but maybe theres something in there to steal. (Though admittedly the earlier patches here look pretty nice already :)

**Comment by hemanth** [comment]
> (Edited by paulirish. removed the gif cuz it creeped me out, sorry! :)

Heh heh, no problem! 

Nice on there with `launch_chrome` was planning to use [exude](https://github.com/hemanth/exude) 😇
