### ISSUE TITLE
Saving lighthouse run artifacts to disk

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#35]
Over [in my fMP pr I noted](https://github.com/GoogleChrome/lighthouse/pull/31#discussion-diff-56741741R21) it'd be valuable to save the trace to disk.. mostly so that I can verify the metrics and summarized data  is correct.

@brendankenny rightly pointed out that in addition to debugging, there's value for saving the artifacts locally for timeseries analysis (a la big-rig).  

Personally, I'd be happy to save all my runs artifacts until i want to free up the disk space.

Any ideas on what setup would make sense? cmd-line option -> something?

**Comment by samccone** [comment]
--save ... writes out a lighthousetrace-<timestamp>.json file

easyyyy

--load wold skip the gather phase and just run the audit :+1:

**Comment by paullewis** [comment]
+1 make it a flag, or two flags

**Comment by paulirish** [comment]
deep's upcoming patch starts to encroach on this one some more.

I think we can close this one until we have a need.
