### ISSUE TITLE
Handling lazy loaded images

### ISSUE THREAD

**Issue by midzer** [GoogleChrome/lighthouse#3508]
Hi all,
using LH v2.5 lazy loaded images above the fold are reported as "Properly size images" with 100% saving opportunity right now. I think this is misleading (or a bug) because those images are in correct dimension/size.

Furthermore those images result in a rather bad PSI pushing down overall performance rating. I read its value is calculated with all layout changes being done after initial page load. Maybe lazy loading elements above the fold has no point at all performance-wise? On the other hand, using lazy loading every heavy element FMP, FI and CI are fine :+1: 

Here is an example site showing the issue https://feuerwehr-eisolzried.de/

Thanks for this awesome tool and have a nice day
midzer

**Comment by patrickhulce** [comment]
Thanks for verifying @philipwalton. I believe we originally threw around the idea of calling this "invisible images" but thought that would be even more confusing 😆 we'll have to dig into some of theses edges and decide how we should handle them.

**Comment by tomayac** [comment]
This causes a lot of confusion, we need to rename this *urgently*. How about being very clear and just say “images that were loaded, but that aren’t being used on the page”?

**Comment by dtomaszewski** [comment]
I think it caused additional problem see on https://memoteka.pl/ that lazy loaded images are marked as "offscreen"

**Comment by kenhoward** [comment]
Like @neodigm, I set the lazy load to an absurd amount of time without change in results. I'm targeting the correct images that are in question.

**Comment by patrickhulce** [comment]
@kenhoward are you still seeing problems with 3.0.0-beta? If so, please file a new issue with repro steps :)

**Comment by neodigm** [comment]
I am no longer seeing this issue in the extension.
