### ISSUE TITLE
--no-mobile flag causes errors.

### ISSUE THREAD

**Issue by mgerakis** [GoogleChrome/lighthouse#351]
Using the --no-mobile flag causes various bugs to occur:
  - Using the query 'head meta['viewport']' on a document that lacks such a tag (like a desktop web app) will cause the cli to stall. Also, because driver.querySelector does not reject on elements that are not found (nodeIDs === 0), the catch block in **cli/index.js** on line 88 will also raise an error because no err is passed in and so err.code searches for a property in undefined. 

  - If checks are put in place, some sites will also fail due to the _ThemeColor_ gatherer class. This is because of the same issue, where some desktop sites do not have a meta tag for theme-color.

  - Finally, an error is raised for the _Accessibility_ gatherer, though I have not found out why just yet.

**Comment by mgerakis** [comment]
`// If this gets to 15s and it hasn't been resolved, reject the Promise.`
`asyncTimeout = setTimeout(reject, 15000);`

I believe this line causes the problem for accessibility. At least when testing kevlar/polymer on youtube, the site takes more than 15s to perform the aXe test. Since no reject handler is passed in, _asyncTimeout_ causes an error to propagate.

**Comment by paulirish** [comment]
It's been a while since we've run this flag, so I'm not too surprised it's regressed.

thanks for digging in here. Now peeking at your PR (#352)

**Comment by paulirish** [comment]
from offline conversation, this is now settled.
