### ISSUE TITLE
Report: update printing & clipboard logic to support beforeprint

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#3510]
`beforeprint`/`afterprint` are landing in chrome 63. 
https://www.chromestatus.com/feature/5700595042222080

We can simplify the report printing logic a bit: 

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/report/v2/renderer/report-ui-features.js#L289-L304

**Comment by ebidel** [comment]
There's also the new clipboard api: https://www.chromestatus.com/feature/5861289330999296

**Comment by brendankenny** [comment]
still no implementation or public signals from Safari, so probably isn't going to happen any time soon :/
