### ISSUE TITLE
Enable SEO audits without reporting in default config

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#3521]
We'd like to be able to have an audit that is not surfaced in the UI but available in the JSON results. For example, the SEO audits have a separate config and are not enabled by default. But we'd like to be able to get SEO results in HTTP Archive without necessarily displaying the incomplete audit category to users.

**Comment by patrickhulce** [comment]
@rviscomi this should already be true if you don't use the `onlyCategories` or `onlyAudits` fields, is it not working for you?

the action item here might just be move the audit definitions for SEO into the default config and keep the report items in the full config

**Comment by rviscomi** [comment]
Oh I see what you're saying. The thing that's not working for me is WAI; the SEO audits are not in the JSON results because their definitions are not in the default config.

Feel free to reassign to @kdzwinel if this isn't something you or Brendan want to do.
