### ISSUE TITLE
Add Remediation advice to each library vuln

### ISSUE THREAD

**Issue by benschwarz** [GoogleChrome/lighthouse#3524]
The `no-vulnerable-libraries` audit detects and lists security vulnerabilities, but is not able to be used "offline" because there is no remediation advice to go with the vulns. 

This means we're not able to format lighthouse 'advice' or 'opportunities' as we do elsewhere.

### Current output from `no-vulnerable-libraries` audit: 
<img width="633" alt="screen shot 2017-10-11 at 9 22 50 am" src="https://user-images.githubusercontent.com/924/31413607-d4e9f224-ae65-11e7-8e15-deef763cc354.png">

### Information we don't have in the audit but need:
<img width="696" alt="https snyk io partners api v2 vulndb clientside json 2017-10-11 09-57-42" src="https://user-images.githubusercontent.com/924/31414668-ce33caa4-ae6a-11e7-954f-fc26bc3c98b0.png">

Having the semver ranges would be useful, but we'd also need to know the current released version of a given library (Snyk vuln page): 

<img width="792" alt="cross-site scripting xss snyk 2017-10-11 09-27-46" src="https://user-images.githubusercontent.com/924/31414710-08cedb68-ae6b-11e7-81a2-11d790754e98.png">

If we can have the current released version of a given library added to the snyk client API, then I think we'll be able to do everything that we want. 

Ping @tkadlec

**Comment by paulirish** [comment]
Without explicit remediation advice in the JSON we can still do something similar. We can use the semver lib to interpret the affected version ranges. From that we can calculate the highest affected version. 

That means we couldn't necessarily say "You need to upgrade to version 3 or higher" but we could say something like "You gotta upgrade this lib to a version over 2.6.1". 

Good second/third bug here. :)  @benschwarz you interested in taking this?

**Comment by benschwarz** [comment]
Yep. Leaving it on my list

**Comment by evenstensberg** [comment]
@benschwarz if you're full I can take it

**Comment by 3Q5278** [comment]
good

**Comment by Hoten** [comment]
@benschwarz @evenstensberg any takers? :)

**Comment by evenstensberg** [comment]
Could woek on this in June. Wrapping up some other work first.

**Comment by evenstensberg** [comment]
I'll take it

**Comment by evenstensberg** [comment]
I've asked a guy that works at Snyk for any help regarding getting that prop from the vuln db, but what I think we could do, is to add the `fixedIn` property from the vulnDB and use that to figure out which actions to take. That prop is already present in the vuln db, along with semver ranges for unaffected versions. 

Should I go for that?

**Comment by patrickhulce** [comment]
Sounds great to me @evenstensberg! In fact, I actually think if we don't have any `fixedIn` value we shouldn't surface the vuln at all to prevent cases like #8409 #8748

**Comment by evenstensberg** [comment]
Yup. @lirantal from snyk is following up on this

**Comment by lirantal** [comment]
hey fellas, @evenstensberg @patrickhulce  👋 
notice that we (@aviadatsnyk) added a `fixedIn` field to the clientside.json file we're sending you so you should be able to use that to get more insights out in terms of available fixed version. 
Perhaps
