### ISSUE TITLE
CLI command not able to connect to Chrome Browser

### ISSUE THREAD

**Issue by sandeepkumar03** [GoogleChrome/lighthouse#3528]
Hi All,

Facing an issue, lighthouse is not able to connect to browser. Wanted to use CLI option has Chrome Dev or Extension tool is not allowing to run lighthouse for desktop.

**Env**
Chrome - Version 61.0.3163.100 (Official Build) (64-bit)
Windows 7
Node version  - v6.10.3
Lighthouse version - 2.5.0

**Steps**
1. Installed lighthouse cli using `npm install -g lighthouse`
2. Run command ` lighthouse https://www/google.com --perf --verbose`
3. New chrome window is getting launched.
4.  We see following in console logs

```
ChromeLauncher:verbose created C:\Users\Sandeep\AppData\Local\Temp\lighthouse.6
4925364 +0ms
  ChromeLauncher:verbose Launching with command:
  ChromeLauncher:verbose "C:\Users\Sandeep\AppData\Local\Google\Chrome\Applicatio
n\chrome.exe" --disable-translate --disable-extensions --disable-background-netw
orking --safebrowsing-disable-auto-update --disable-sync --metrics-recording-onl
y --disable-default-apps --mute-audio --no-first-run --remote-debugging-port=617
75 --user-data-dir=C:\Users\Sandeep\AppData\Local\Temp\lighthouse.64925364 about:
blank +14ms
  ChromeLauncher:verbose Chrome running with pid 21756 on port 61775. +25ms
  ChromeLauncher Waiting for browser. +1ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +2s
  ChromeLauncher Waiting for browser....... +2s
  ChromeLauncher Waiting for browser......... +2s
  ...
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:61775 +1s
  ChromeLauncher:error Logging contents of C:\Users\Sandeep\AppData\Local\Temp\li
ghthouse.64925364/chrome-err.log +2ms
  ChromeLauncher:error  +2ms`
  Unable to connect to Chrome
```
The error log file (chrome-err.log) mentioned in console logs is empty.Tried to telnet to port mention in console while process was running ` telnet localhost 61775` but that gave error 

```
Connecting To localhost...Could not open connection to the host, on port 64277:
Connect failed

```

Is there anything we are missing?

Thanks,
Sandeep

**Comment by vinamratasingal** [comment]
Hi Sandeep- thanks for reporting this. This is an issue we've previously seen, so we'll port this over to our umbrella bug here: https://github.com/GoogleChrome/chrome-launcher/issues/6
