### ISSUE TITLE
Text compression with HTTP2 tip

### ISSUE THREAD

**Issue by xliiv** [GoogleChrome/lighthouse#3548]
I'm wondering if hint:
* Performance > Opportunities > Enable text compression

is relevant while using HTTP2?
Or perhaps I misunderstand this tip? Then maybe more precise message could be shown?

![image](https://user-images.githubusercontent.com/298994/31540935-52b76fbc-b00d-11e7-9a6e-41913011fe12.png)

**Comment by vinamratasingal** [comment]
Hi! Thanks for filing an issue about this. 

I think what you're asking for is if HTTPS2 automatically does text compression, to which the answer is no. This audit is telling you to compress your responses.  HTTPS2 does not automatically compress your responses, so you still need to implement that optimization. For what it's worth, the total gain from this optimization is pretty small (only shave off 70 ms), so it's totally fine to focus on other optimizations! If you have any feedback around how we can make that less confusing, let us know

**Comment by xliiv** [comment]
According to [this](https://youtu.be/Mou17XxYRZk?list=PLJIvhAFA2pTEjZvlP3ZW2d5hpikS2VGaM&t=1681) (They're talking about [this](https://youtu.be/Mou17XxYRZk?list=PLJIvhAFA2pTEjZvlP3ZW2d5hpikS2VGaM&t=1050)).

When HTTPS2 is detected, message should be focused more on [preload](https://w3c.github.io/preload/#server-push-http-2)?

**Comment by patrickhulce** [comment]
@xliiv thanks for sharing the video! The speaker though is claiming that the benefits of CSS and JS *minification* are negligible when you're already using GZIP compression (within 1% file size), not that there is not a benefit to using text compression when serving assets over H2. Your recommendation on preload is a great point and in fact we're already on the case! (see #3450)

Lighthouse does not currently audit for minification, but when we do rest assured that in cases where the difference really is just 1% we would not surface that as a priority :)

**Comment by xliiv** [comment]
Thanks for clarification. I think we could close this issue then. :)
