### ISSUE TITLE
Twitter lite not showing as 100% PWA

### ISSUE THREAD

**Issue by deepurevu** [GoogleChrome/lighthouse#3553]
Twitter lite is inline with PWA. But lighthouse shows only 55

**Comment by vinamratasingal** [comment]
Hi- can you give us reproduction steps to how you measured Twitter Lite for the PWA rating?

**Comment by deepurevu** [comment]
I did install the plugin, generate report on by passing the twitter lite url.

**Comment by vinamratasingal** [comment]
What was the Twitter Lite URL that you used? Can you list out the exact steps (including other extensions you might have installed?)

**Comment by deepurevu** [comment]
Its https://lite.twitter.com/.

1. I opened the website.
2. Clicked on light house extension and generate the report.
3. It debugged the website and provided the below result.


Print...Copy JSONSave as HTMLSave as JSONOpen in Viewer
Lighthouse
Version: 2.5.0
Progressive Web App45Performance37Accessibility94Best Practices81
45
Progressive Web App
37
Performance
94
Accessibility
81
Best Practices

**Comment by deepurevu** [comment]
Print...
Copy JSON
Save as HTML
Save as JSON
Open in Viewer
Lighthouse
Version: 2.5.0
Progressive Web App
45
Performance
37
Accessibility
94
Best Practices
81
45
Progressive Web App
37
Performance
94
Accessibility
81
Best Practices

**Comment by wardpeet** [comment]
@deepurevu https://lite.twitter.com/ is not a PWA. it's their landing page and it's not running a Service worker. You should try https://mobile.twitter.com/home

**Comment by wardpeet** [comment]
@deepurevu https://lite.twitter.com/ is not a PWA as it's not running a service worker. I think you want to run lighthouse against http://mobile.twitter.com/home

**Comment by deepurevu** [comment]
Thanks for the information Ward.
