### ISSUE TITLE
Include docs on Firefox's a2HS trigger

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#356]
The [trigger logic for Firefox](https://twitter.com/Anti_Hype/status/727970196531625984):
- Nightly firefox
- enrolled in the experiment (currently 50/50 chance). [use this ext](https://addons.mozilla.org/en-US/android/addon/switchboard-experiments/)
- HTTPS
-  5+ visits
- 30secs <= last visit <= 10mins
- "once per URL"

video of the flow: https://t.co/iPjft2cQH6

---

I want to make sure this is documented either within lighthouse or at the resource(s) that we link to.

**Comment by vinamratasingal** [comment]
Pinged Owen (PM on Capabilities), will update with response!

**Comment by owencm** [comment]
I think that a manifest with specific contents (not sure of the rules) is required.

For example, Chrome ensures that developers provide icons of specific sizes, I would expect the same from Firefox. (probably fastest just to check their code to find out)

I support having something inside lighthouse that informs developers whether they meet the A2HS bar in Chrome, and in Firefox even though these are not the same bar.

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
