### ISSUE TITLE
no obvious way to print/save human readable version of report

### ISSUE THREAD

**Issue by marcacohen** [GoogleChrome/lighthouse#3564]
Feel like I must missing something but I've been using this tool to audit a site and an obvious scenario is to capture the output, annotate it, and email it to someone. But I can't find a way to extract a nice, human readable version. I see a download button but that results in an extension-less file that looks like it contains a json version of the report. I don't see an obvious way to download or print a text or static html version. Am I missing it? If so, maybe the feature could be displayed more prominently. If not, consider this a feature request.

**Comment by marcacohen** [comment]
Ah, I see the docs describe how to share reports (https://developers.google.com/web/tools/lighthouse/), so this was me not RTFMing, sorry. 

I would add that I think it would be good to make the sharing functionality more explicit apparent in the main UI flow, because I think it's a pretty common use case.

**Comment by vinamratasingal** [comment]
Thanks for the feedback! We'll take a look and prioritize this feature request accordingly :)

**Comment by vinamratasingal** [comment]
Question: could we use Puppeteer to do this?

**Comment by vinamratasingal** [comment]
Discussed with Paul: let's move forward and do a simple Save to PDF option for now. Marc, let me know if this doesn't work for you.

**Comment by paulirish** [comment]
Plan: Add the icon and two top menu items to devtools.


<img width="436" alt="screen shot 2018-01-08 at 2 28 48 pm" src="https://user-images.githubusercontent.com/39191/34695585-4a26c304-f480-11e7-9533-01b5a52b72fc.png">

**Comment by paulirish** [comment]
Alright, so unfortunately this is not trivial.

* If devtools is docked (it usually is), you cannot print it. Chrome doesn't support bringing up the print dialog for that docked pane.
   * Regardless, you don't want to print the audits panel, because you get the rest of the devtools UI, and its not scrollable.
* We can open a popup window, toss the report in there, and then trigger the print dialog.
    * However, it currently includes ALL devtools HTML, whereas we only want it to include the report HTML. Unfortunately splitting that out, handling the CSS, etc.. will be a week of work. Even then, I fear it will be too unmaintainable to commit to.

One alternative here is using the lighthouse viewer. We can easily "open in viewer" from devtools. Printing there is no problem at all. 

But there are product concerns with going the viewer route we should discuss.

**Comment by vinamratasingal** [comment]
Let's discuss this in the next Lighthouse sync.

**Comment by paulirish** [comment]
Will need to discuss if we want to pursue the Viewer approach.

However we can add "save as HTML" pretty painlessly.

**Comment by paulirish** [comment]
No plans to do this, as there's little demand

**Comment by uglyeoin** [comment]
+1 for demand.  I see little use if I can't show a client.  And they don't speak JSON.  Using the viewer worked but I expected the solution to be right there.  I can use this method if it's not accepted but I'm putting it out there that there might be demand.

**Comment by joelhsmith** [comment]
I'm working on a Python project that will convert a Lighthouse report output into Markdown.  You don't need to know Python to use it, just have Python 2.7 running on your computer and know a little CLI.

It might be ready by the end of the week or next week if you want to be an alpha tester.  Its not ready for prime time yet.  PM on Twitter or something and I will share a link.

**Comment by uglyeoin** [comment]
> I'm working on a Python project that will convert a Lighthouse report output into Markdown. You don't need to know Python to use it, just have Python 2.7 running on your computer and know a little CLI.
> 
> It might be ready by the end of the week or next week if you want to be an alpha tester. Its not ready for prime time yet. PM on Twitter or something and I will share a link.

Good effort.  But if I do that I may as well use Lighthouse Viewer.

**Comment by joelhsmith** [comment]
The viewer cannot be edited. We are converting to markdown so we can augment the content and add in screenshots of failing elements.

**Comment by joelhsmith** [comment]
Hi @uglyeoin , My Lighthouse to Markdown project is getting close to an alpha release.  It is much better than Lighthouse Viewer because it also takes screenshots of failing elements.  And you can template it to display any data available in the Lighthouse JSON file.  It is primarily focused on Accessibility stuff, but templates can be made for any audit.

https://github.com/OpenAssessItToolkit/openassessit

I'd love to get some feedback on it.  I added a Dockerfile, so if you have Docker installed it would only take you 2 minutes to spin it up and see if it would help you.

**Comment by uglyeoin** [comment]
@joelhsmith thank you for remembering me and coming back on this one.  I'm a bit busy now but I will try to find some time later.  I haven't used Docker - for my sins - but I definitely should have by now!

**Comment by joelhsmith** [comment]
np. I'd appreciate the feedback.  Docker can even be installed with a GUI with the links in the Readme.md file. You don't need to know how to use Docker to use it. If you or any people who find this thread try it out, ping me!

**Comment by whiskerandpaw** [comment]
> One alternative here is using the lighthouse viewer. We can easily "open in viewer" from devtools. 

[Lighthouse Viewer](https://googlechrome.github.io/lighthouse/viewer/) works really well for me, thank you!

**Comment by jbdoster** [comment]
> One alternative here is using the lighthouse viewer. We can easily "open in viewer" from devtools.

[Lighthouse Viewer](https://googlechrome.github.io/lighthouse/viewer/) works really well for me, thank you!

**Comment by jorangreef** [comment]
> No plans to do this, as there's little demand

Increasing demand...

**Comment by joelhsmith** [comment]
@jorangreef I have built something to do this, It converts it to Markdown or HTML.  It is command line only at the moment, but has a Docker version so you do not need to install anything other than Docker to try it.  I'd love to get more people to test it and make feature requests.

https://github.com/OpenAssessItToolkit/openassessit

**Comment by connorjclark** [comment]
BTW, the audits panel in DevTools now supports printing. In Canary. Will be released in Chrome 77.

![image](https://user-images.githubusercontent.com/4071474/63296161-45db1200-c283-11e9-89c9-892dd34363cc.png)

**Comment by uglyeoin** [comment]
@connorjclark awesome!  Then we can print to PDF :)
