### ISSUE TITLE
Need documentation for Lighthouse release process

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#3579]
Need documentation around how we do releases on Lighthouse explaining

- Cadence
- Responsibility of release master (pulling together release, release notes, writing and publishing the /updates blog post, announcing release on Twitter, etc.) 
- Putting together release master rotation calendar. 
- Adding cadence dates to internal Lighthouse calendar. 
- ... anything else.

**Comment by vinamratasingal** [comment]
Also, can you explain the naming convention (like why is it Lighthouse 2.5 vs 2.5.1)

**Comment by paulirish** [comment]
@vinamratasingal to review 4201. when good we'll close this.
