### ISSUE TITLE
Audit Closure annotations for codebase

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/lighthouse#358]
Let's check the codebase for type annotation completeness.

**Comment by brendankenny** [comment]
currently files are whitelisted for type checking [here](https://github.com/GoogleChrome/lighthouse/blob/fe9de41f24fef9f887a9b60e50a4a15b2e90e18e/closure/closure-type-checking.js#L29)

**Comment by paullewis** [comment]
Hero

**Comment by wardpeet** [comment]
so just remove them from whitelist and start fixing through pr?

**Comment by paulirish** [comment]
@samthor any update on this?

**Comment by samthor** [comment]
See #360.

Then I went on holidays. I'm back next week.

**Comment by paulirish** [comment]
sup!

**Comment by paulirish** [comment]
closing to keep our issues focused
