### ISSUE TITLE
Create generalized all-anchors gatherer

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#3581]
Something that could be shared with:

* anchor text audit: https://github.com/GoogleChrome/lighthouse/pull/3490
* anchor rel noooper audit: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js
* future anchors

Probably has to gather `innertext/textcontent`, `href`, `rel` and some other items?

-------

broken out from discussion here https://github.com/GoogleChrome/lighthouse/pull/3490/files#r143305681

**Comment by brendankenny** [comment]
hey, fun, we did this in #7101!
