### ISSUE TITLE
Make Lighthouse error string more user friendly

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#3598]
Lighthouse error strings are not very user friendly, especially for the timeout cases. Can we make it such that the error strings don't just dump out the debug string but tell users what they can do (if timeout, then tell them to try using the CLI and increase timeout, or if it's a tracing failure, then ask them to just rerun the trace).

**Comment by vinamratasingal** [comment]
Strings up at: https://docs.google.com/spreadsheets/d/1iWCjDjHBkollUbiezgHtzgSK9MCu4tD6LEuunrbNOZw/edit#gid=0

**Comment by paulirish** [comment]
Looking at these, I'm thinking we might want to use a lot more space to appropriately explain each error. One slight modification is that we give each error an error code and then link up some docs. 

For example, in Alice's old a11y extension, she'd link to https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_aria_02 for the explanation.  Giving each error a code that's googleable is also the approach chrome security takes for all the various certificate/tls issues.

So perhaps:


> Something went wrong with recording the trace during your page load (No domContentLoaded event found). Please try again. (Error code: [NO_DCL_EVENT_FOUND](https://github.com/GoogleChrome/lighthouse/SOMEDOCSLINK))

In the docs link we could expand a bit and link to various github issues or resolution recommendations.

**Comment by paulirish** [comment]
AFAIK, patrick, v and I are all happy with the strings in there now.

* [x] Strings and error codes are defined
* [ ] docs page for the various error codes. we will defer this for now?
* [ ] Land these string changes in LH. Optionally introduce the strings.js file for maintenance.

**Comment by paulirish** [comment]
over to @patrickhulce for the 3rd checkbox above.
