### ISSUE TITLE
How do audits safely report they didn't complete?

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#36]
What should an audit return for statuses like "test not applicable" or "metric couldn't be computed", etc?

It's not reporting a test failure, nor a runtime exception.. @samccone recommended a `result.fault` state, which is what i [tried out here](https://github.com/paulirish/lighthouse/blob/f637e14108310cc00cee9ea2fad11d353bbdc0f7/metrics/first-meaningful-paint/audit.js#L30-L34)

thoughts?

**Comment by samccone** [comment]
+1 fault for now, it can be under specified a bit until we have a few more fails to abstract a "pattern" from

:goat: :eight: :tada:

**Comment by paullewis** [comment]
So long as promises resolve I'm cool. We don't want rejects for anything other than exceptions. So we can resolve with a fault property if that works, though why not err?

**Comment by paulirish** [comment]
merging this into #61
