### ISSUE TITLE
Add toplevel warning when chrome-extension URLs are present

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#3600]
Given the variability of results that users might experience depending on the Chrome environment Lighthouse is being run in, we should surface to end users that their results could be different depending on extensions/anti-virus scanners installed on the machine (as per #2674 )

**Comment by vinamratasingal** [comment]
Given the fact this ties into existing work/is low hanging fruit (and would clear user confusion for a significant % of Lighthouse users), prioritizing this as a P1 for Sprint Tres.

**Comment by tdresser** [comment]
Should we try to identify cases where inconsistent ads cause variability?

**Comment by vinamratasingal** [comment]
Sure, although I'm not sure what you mean by inconsistent ads (I think we should try to explain any kind of variability to the end user)

**Comment by tdresser** [comment]
If my page includes a rotating display ad, then sometimes I'll load an add which chews up half a CPU, and downloads a meg of JS, and sometimes I'll load an add which is super light.

Which of these cases I land in can cause large variation in my testing.

This is tricky, because we don't want people to disable ads while their testing, because it results in a misrepresentation of the user experience.

**Comment by paulirish** [comment]
merging in #1888.. We'll also want to say that LH on WPT offers the most consistent measuring environment.

**Comment by addyosmani** [comment]
It would be ace if we could check if an audited site was non-local and offer a one-click option to directly test the experience on a Moto G4/Slow 3G on WebPageTest if you want the real-device experience. Just linking to WPT also works too :)

**Comment by vinamratasingal** [comment]
After discussion, we decided that if we detect resource requests from a Chrome extension within the trace, we would surface a top level warning saying something like "Other Chrome extensions you have installed might be interfering with the accuracy of the Lighthouse Report. Learn More." 

Learn more should link to a doc that explains the sources of the instability, and solutions (Use clean Chrome profile, run LH on WPT, etc.) 

Assigning to Kayce for the docs and Paul to decide who implements this!

**Comment by paulirish** [comment]
fixed by #5666
