### ISSUE TITLE
Move /web Lighthouse docs into lighthouse repo

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#3603]
Goal is to move management of content in [WebFundamentals/tools/lighthouse](https://github.com/google/WebFundamentals/tree/master/src/content/en/tools/lighthouse) into the Lighthouse repo itself. Current plan:
- Audits will have some kind of doc blocks at the top (maybe with a special jsdoc `@annotation` at the start) written in markdown (starting with what's already in /web). They can then be updated and written as audits are updated and added.
- Script extracts markdown comment and opens a PR on WebFundamentals to update content there.

workbox [just added a very similar pipeline for their docs](https://github.com/google/WebFundamentals/blob/a51d4eee0118127c094f86de2665ba5643c999e5/gulp-tasks/reference-docs.js#L200-L207)

TBD:
- where images/assets should live and how to reference them
- management/validation of special /web markup ([example](https://github.com/google/WebFundamentals/blob/58e98ba75b910a2ff04cfc5af5072888f5add400/src/content/en/tools/lighthouse/audits/address-bar.md))

Presumably most of these can be automated away (and Workbox likely has it already working). Workbox is also looking into automatically opening a docs update PR on new releases, which would be pretty sweet.

**Comment by paulirish** [comment]
Read kayce's thoughtful comments here: https://github.com/GoogleChrome/lighthouse/issues/758

**Comment by paulirish** [comment]
Pending /web docs strategy plan

**Comment by brendankenny** [comment]
Obsolete. Docs are moving to web.dev
