### ISSUE TITLE
getting `Runtime error encountered: Error: No Chrome Installations Found` with Chrome Canary installed on a mac

### ISSUE THREAD

**Issue by kenikall** [GoogleChrome/lighthouse#3607]
trying to run lighthouse from CLI but It looks like my system is unable to find chrome. I have Canary installed and have looked at other similar issues without finding a solution.

Here is some further information from the command line:
```
npm list chrome-devtools-frontend
lighthouse@2.5.1 /Users/username/lighthouse
├── chrome-devtools-frontend@1.0.422034
└─┬ devtools-timeline-model@1.1.6
  └── chrome-devtools-frontend@1.0.401423
```

**Comment by brendankenny** [comment]
Is Canary installed in `/Applications/` or somewhere else?

While we look into this, note that in the meantime you can manually tell it where to find Chrome by setting a `CHROME_PATH` environment variable to Chrome's path.

**Comment by kenikall** [comment]
Canary and Chrome are both in `/Applications`.

**Comment by brendankenny** [comment]
Hmm, can you run
```sh
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump | grep -i 'google chrome\( canary\)\?.app$' | awk '{$1=""; print $0}'
```
in the command line and share what it outputs? That's the command https://github.com/GoogleChrome/chrome-launcher uses to find Chrome on Macs.

**Comment by kenikall** [comment]
```
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump | grep -i 'google chrome\( canary\)\?.app$' | awk '{$1=""; print $0}'
 /Applications/Google Chrome.app
 /Applications/Google Chrome Canary.app
 /Volumes/Google Chrome Canary/Google Chrome Canary.app
```

**Comment by kenikall** [comment]
Any updates @brendankenny?

**Comment by paulirish** [comment]
This seems very weird.

But I think a fresh install of Lighthouse might solve this.

I hope so.
