### ISSUE TITLE
XVFB + headless doc is confusing

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#3609]
Not enough attention is given to the fact that throttling doesn't work and instructions on the XVFB path from node are missing.

related #3715

**Comment by wardpeet** [comment]
Thank you for surfacing this issue. I believe with landing headless chrome we don't actually need to think about this too much.

https://github.com/GoogleChrome/lighthouse/blob/e986d891abe6fc55eeb0686a062f66824cf507f7/docs/headless-chrome.md
