### ISSUE TITLE
Fails to start using SharedWorkers

### ISSUE THREAD

**Issue by kesne** [GoogleChrome/lighthouse#3619]
Applications that use shared workers run into issues when trying to run Lighthouse:

> Multiple tabs are being controlled by the same service worker.

Ideally, pages with 1 tab and SharedWorkers would be able to have audits run.

**Comment by patrickhulce** [comment]
Thanks for the report @kesne! This is a known issue with DevTools and extension, related #1335. As a temporary workaround you can run Lighthouse using the CLI.

**Comment by paulirish** [comment]
@kesne question: do you have a service worker on this page?

**Comment by kesne** [comment]
Yeah I have a ServiceWorker on the page as well as two SharedWorkers.

**Comment by brendankenny** [comment]
let's move into #1335
