### ISSUE TITLE
Question: Is there an overview of used API's over the Chrome Debugging Protocol?

### ISSUE THREAD

**Issue by auchenberg** [GoogleChrome/lighthouse#362]
Hypothetically, if other browsers, such as Edge, should be able to work with `Lighthouse` which API's would need to get implemented.

Is there an easy way to extract an overview?

**Comment by paullewis** [comment]
I made [a little patch](./363) for this just now to answer the question. I'll PR it in, but it might need a little wrangling before we land it.

In any case, the ones we use today are:
```
DOM.getAttributes
DOM.getDocument
DOM.getOuterHTML
DOM.querySelector
Emulation.setDeviceMetricsOverride
Emulation.setTouchEmulationEnabled
IO.read
Network.clearBrowserCache
Network.emulateNetworkConditions
Network.enable
Network.setCacheDisabled
Network.setUserAgentOverride
Page.addScriptToEvaluateOnLoad
Page.enable
Page.getNavigationHistory
Page.navigate
Runtime.enable
Runtime.evaluate
Security.disable
Security.enable
ServiceWorker.enable
ServiceWorker.setForceUpdateOnPageLoad
Tracing.end
Tracing.start
```

With each call's details being found here: http://chromedevtools.github.io/debugger-protocol-viewer/ (though I imagine you already know that exists!)

**Comment by paullewis** [comment]
Also it's worth noting that a lot of our performance metrics are heavily reliant on tracing data, i.e. save a Timeline JSON file and that's what we output. I'd be high fiving any other browser that supports a similar output, but without that data none of the perf stats can be calculated.

**Comment by wardpeet** [comment]
perhaps it's a good idea to consider somekind of strategy pattern so browsers don't have to use the chrome api methods but can use their own. Of course i'm all for one api :p

**Comment by paullewis** [comment]
Then you have a meta API on the APIs which is kinda no fun really 😞

**Comment by auchenberg** [comment]
Thanks! I wrote this tool to compare Chrome, Safari and Edge API support, and there's still some way for parity: https://remotedebug-compat-tables.herokuapp.com, but simple tests should be working.

Profiling data is indeed a challenge, but not unsolvable. Requires some more stability.
