### ISSUE TITLE
Look through URLs that produce failure and investigate

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#3639]
Based on the work that Alex Sung and his team have been doing, let's investigate a small set of the failure URLs to document high-level trends in the failure instance.

**Comment by brendankenny** [comment]
we also have the list of URLs in #2293

**Comment by vinamratasingal** [comment]
Yeah, it's worth considering whether we should merge investigation of the two. Let's talk about it in the next sprint planning meeting :)

**Comment by patrickhulce** [comment]
looked through the ~40 urls, 31 were fine but many needed longer than 30s, increasing to 45s did the trick for all but 3 so +1 to increasing the timeout a bit

a few useful nuggets out of this:

* 2 sites where axe fails
* a few good examples of poorly behaving sites we should try to work around
* a couple cases where we stop tracing too early that we should look into

**Comment by vinamratasingal** [comment]
Can we document an action plan around this or have a doc somewhere that consolidates these learnings? (perhaps with the WPT failures and the other a11y failures we've been noticing as well).

**Comment by patrickhulce** [comment]
yes that document is #2293, individual bugs are being filed for distinct issues 
WPT failures are totally different animal that we don't even know is within Lighthouse control at all will be discussed in #3719
