### ISSUE TITLE
Support User Timing

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#364]
This would be incredibly useful for libraries/frameworks and would be setup through client-side JS. Are lighthouse interested in exploring support for this @paulirish? 

From convo with @brendankenny 

> Basically you use the user timing api and the entries you make are stored in the trace we're already taking and then on your CI or test server or whatever, you just tell lighthouse to track trace events with your user timing names.  The simplest is just doing `window.performance.mark('element_I_care_about_loaded');` and lighthouse will have some functionality of tracking time from navigation to `element_I_care_about_loaded`.

**Comment by wardpeet** [comment]
this would be awesome!

**Comment by paulirish** [comment]
cc @mgerakis

**Comment by paullewis** [comment]
I'm interested in us doing this for sure, we should just outline what the appropriate mechanism is here, as well as how we think we should report it, so that anyone can apply it to their codes

**Comment by paulirish** [comment]
Here's the basic approach with the devtools-timeline-model

```js
tModel = model.timelineModel()
group = [...tModel.mainThreadAsyncEvents().keys()].find(group => group.title == "User Timing");
asyncEvents = tModel.mainThreadAsyncEvents().get(group)
```
![image](https://cloud.githubusercontent.com/assets/39191/15589198/a9371888-2346-11e6-92bc-29cafa6b8e1b.png)

**Comment by paulirish** [comment]
All set, thanks to @mgerakis's work.

screenshot:
![image](https://cloud.githubusercontent.com/assets/39191/15625088/d76de9e8-244f-11e6-8fc4-d41950a79b19.png)

**Comment by addyosmani** [comment]
Thanks so much for getting this through so quickly @mgeraki!
