### ISSUE TITLE
Miscalculation in Color Contrast Audit

### ISSUE THREAD

**Issue by jkantner** [GoogleChrome/lighthouse#3651]
I’m using `#ccbade` for `<h3>`, `#ffffff` for `<p>`, and `#333333` as a background for `<figcaption>`. I tested these on a color contrast checker such as [Hex Naw](https://hexnaw.com/), and both the `<h3>` and `<p>` colors pass with AAA.
```
<figcaption>
<h3>Heading 3</h3>
<p>Paragraph text</p>
</figcaption>
```
I tested the same with Lighthouse, but it keeps accusing the `<h3>` and `<p>` of not having sufficient contrast with the background. I tried slightly adjusting the text colors, but still nothing changed after retesting.
![screen shot 2017-10-25 at 11 13 59 am](https://user-images.githubusercontent.com/16387543/32006782-a96ca144-b975-11e7-8ea1-67be0354b4aa.png)
I have a feeling there’s something wrong with the contrast calculation.

**Comment by patrickhulce** [comment]
Can you reproduce this issue using just [axe](https://github.com/dequelabs/axe-core) @jkantner? If so, would you mind filing this issue with them? We can keep this open to track any necessary axe updates we may need.

**Comment by jkantner** [comment]
Unfortunately I have no idea how to use that to test color contrasts, but I’ll share this issue with them anyway.

**Comment by patrickhulce** [comment]
You can use their chrome extension (https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd) to test the same page you were running Lighthouse on. If the same issue is reproducible there, then you should file the issue with them.

**Comment by patrickhulce** [comment]
@jkantner any updates here? Were you able to reproduce with just axe or file an issue with them?

**Comment by jkantner** [comment]
Yep, I filed the issue with them.

**Comment by vinamratasingal** [comment]
Can we close this out? Not sure if there's anything needed on our end.

**Comment by Kinggregory** [comment]
Yes thanks

**Comment by Kinggregory** [comment]
Hey, can you sign this petition? http://chng.it/NXcN5vwx85

Thanks! - Gregory
