### ISSUE TITLE
Metrics: rename "First Interactive" and "Time To Consistently Interactive"

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#3655]
There has been interest in reducing the developer confusion introduced by having two interactivity metrics. The latest thinking has been:

* Rename "Time to consistently interactive" to just "Time to interactive" - it will be the headline metric
* Rename "First Interactive". There's been discussion around whether First Idle/First Idling would be more clear here but there may be a better option for naming.

At CDS, we shopped this idea around with a few developers. Main feedback was that the TTCI ➡️ TTI change sounds reasonable. The second (FI) was consistently followed up by questions asking for clarity e.g "...is this main thread idle we're talking about?" "..CPU idle?" etc.

I believe there may be a desire to keep discussing the second point here, but filed an issue to track the update anyway.

cc @paulirish @patrickhulce @brendankenny

**Comment by paulirish** [comment]
sg thx for filing this.

Over on the "Loading Metric Prioritization" doc, Patrick and I wanted to bikeshed "first idle" some more. :)

Also some potential other changes given this new framing:
* Add FCP and First Paint as first-class metrics
* Maybe remove FMP?
* Redo the weighting for perf category

**Comment by addyosmani** [comment]
Np. Just commented there :) I'd be interested in the idea of adding FCP and FP - were you thinking weighting for perf might factor TTI more heavily than it does today? or..smth else? :)

**Comment by vinamratasingal** [comment]
If we're going to adjust weighting, let's check in with xPA folks to make sure they're aware of the changes and adjustments in scoring that will happen. I'm going to shoot an email to some folks, but would be good to give others a heads up :)

**Comment by benschwarz** [comment]
> Maybe remove FMP?

Yah. TBH FMP isn't useful when you've got FCP.

> * Rename "Time to consistently interactive" to just "Time to interactive" - it will be the headline metric
> * Rename "First Interactive". There's been discussion around whether First Idle/First Idling would be more clear here.

From what I've seen, the distinction between the two causes nothing but difficulty for people to understand. These names (while they may receive a tonne more discussion) SGTM.

**Comment by patrickhulce** [comment]
Totally agree on reducing the confusion here and I like the overall shift in loading metric story 👍 

@benschwarz care to elaborate a bit more on...

> FMP isn't useful when you've got FCP.

I've frequently found FCP to be too early to express when useful content showed up and consider it as a useful addition to FP/FCP duo. I'm curious what your experience has been.

**Comment by paulirish** [comment]
little update here: there was consensus renaming FI to "First CPU Idle"

**Comment by addyosmani** [comment]
First CPU idle sgtm. With that locked in, what do you see as the timeline
for us making these changes in metric renaming?

**Comment by patrickhulce** [comment]
this has been fixed in v3 :)
