### ISSUE TITLE
Fork the Chrome extension to demo SEO audits

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#3656]
To get feedback on the SEO audits before release, we'd like to be able to give testers a link to install an extension that has all completed audits in the SEO category enabled in the UI.

**Comment by kdzwinel** [comment]
<img width="433" alt="popup" src="https://user-images.githubusercontent.com/985504/32339406-fe751684-bff7-11e7-953a-e90171a0ec4c.png">
<img width="1147" alt="result" src="https://user-images.githubusercontent.com/985504/32339407-fecc5782-bff7-11e7-8bb2-db3d161ce7ed.png">

**Comment by rviscomi** [comment]
Do you have a link to install?

**Comment by kdzwinel** [comment]
@rviscomi it's up! Extension is unlisted, only accessible with this link: https://chrome.google.com/webstore/detail/lighthouse-seo/ckjgeicnedpfbjkleiahadaopannahkj

I included https://github.com/GoogleChrome/lighthouse/pull/3657 which is waiting for merge , added a badge over the icon so this extension is easy to distinguish from the original one and removed all throttling because our audits don't need it.

![seo-ext-light](https://user-images.githubusercontent.com/985504/32522391-69a616ce-c417-11e7-9090-ca5095dd2d6a.png)

Let me know if I should change anything.

**Comment by vinamratasingal** [comment]
Small nit: can we say "These checks ensure search engine crawlers understand your website." This makes the language consistent with the other sections :)

**Comment by vinamratasingal** [comment]
Also @rviscomi- I think we're planning on doing a release of Lighthouse next week and another one later this month. When do you think this new section of the report could land?

**Comment by kdzwinel** [comment]
@vinamratasingal sorry, it looks like I haven't updated copy to the latest version yet. This description will say:
> These audits ensure that your page is optimized for search results. There are additional factors not able to be audited here that may also affect your search ranking. [Learn more](https://support.google.com/webmasters/answer/35769).

**Comment by vinamratasingal** [comment]
Ah OK, small nit on the copy. Can we say: (new changes highlighted in Italics)

These _checks_ ensure that your page is optimized for search _engine_ results. There are additional factors Lighthouse does not check that may affect your search ranking. Learn more.

**Comment by rviscomi** [comment]
> These checks ensure that your page is optimized for search engine results. There are additional factors Lighthouse does not check that may affect your search ranking. Learn more.

LGTM

**Comment by kdzwinel** [comment]
@vinamratasingal thanks! I updated the description in the [doc where we keep all copy](https://docs.google.com/document/d/1OavQffvvYpRKAPHofIUmzHnFyYmuk_QG7xm1AoE1qs0/edit#) so it doesn't get lost.

**Comment by vinamratasingal** [comment]
Amazing, thanks folks :) Looking awesome
