### ISSUE TITLE
Lantern: Predict Perceptual Speed Index

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#3672]
We should look into predicting perceptual speed index with the graphs generated by Lantern. Lots of crazy ideas here and ventures more into ML territory, but some function of load timestamps of all images and layout tasks seems like a good starting point.

**Comment by vinamratasingal** [comment]
Is this a dupe of #4639?

**Comment by patrickhulce** [comment]
well technically this is ~1000 issues before #4639 so that one is a dupe ;) but yes
