### ISSUE TITLE
Fix discoverability of drop downs and learn more

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#3696]
Based on CDS feedback, improve discoverability of drop downs and learn more in the audit report.

**Comment by patrickhulce** [comment]
In meeting today "Let’s put a question mark that link to the docs"

**Comment by paulirish** [comment]
Related, our use of "Learn more" means our report fails the new link-text SEO audit. :)
PSI doesn't use "learn more" and instead uses descriptive text. it's pretty nice, IMO:

![image](https://user-images.githubusercontent.com/39191/32914341-161a359e-caca-11e7-80e6-08ece5b47dc2.png)

**Comment by brendankenny** [comment]
deduping into more recent "Learn more" issue #5349
