### ISSUE TITLE
[perf] Introduce needsThrottling flag to audits

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#3698]
Currently if you only select the a11y category, we will still throttle the page load.

If audits can express that they need throttling, then we can disable throttling if it's unnecessary. 

(This flag may be the same thing as "needsReload".. which would also unlock the ability to not reload the page when testing a11y (#1769))

**Comment by brendankenny** [comment]
I wonder if it should be negatively phrased so audits opt in to not being throttled, e.g. `doesntNeedThrottling` (or maybe something better phrased :)

It would be easy to accidentally leave off `needsThrottling` and not notice it in testing, etc, while getting the audit to run faster would be good motivation to remember to notify that throttling isn't necessary

**Comment by wardpeet** [comment]
We have added `useThrottling` as a config option per pass instead of audit. I believe this fixes the issue.

Feel free to reopen this and comment if you would like to continue this discussion.
