### ISSUE TITLE
Stop DevtoolsTimelineModel from mutating trace; move to computed artifact

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#3702]
This is a followup from #3563 & #3520

DevtoolsTimelineModel mutates the trace. It should not be able to. One option is to deep `Object.freeze` the trace events, but we should examine the perf overhead.

It'd also make sense to move the big taskToGroup data into a shared `/lib/` file.

Also can you rename "Parsing DOM" to "Parsing HTML & CSS"

**Comment by wardpeet** [comment]
thanks for adding was going to add it just now!
