### ISSUE TITLE
[perf] reduce wasted time on about:blank

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#3707]
In total we spend ~1.2 seconds just sitting on about:blank. If we switched to an empty data URI as previously attempted, we could wait for `load` event and ditch the arbitrary setTimeout.

**Comment by paulirish** [comment]
The fix was reverted, so we'll have to reattempt.  The correct fix must handle #4466 and #4499. And we should have #4479 in place by then as well.

**Comment by Hoten** [comment]
Attempted to get this done. Ran into an issue that makes us want to punt it again. I unreverted the earlier changes, resolved conflicts, and got it working again in this branch: `undo-revert-datauri`. However, the following issue happened:

When using a data URI as a blank page, the "offline-ready.html" smoke test crashes (randomly!) We know that the process changes when going from data URI -> some other page (but does not when going from about:blank -> some other page). We are aware of a bug in DevTools where protocol messages crash the process if the session has expired. The theory is that going from data URI -> some other page causes not only a new process to be generated, but also a new session. Whatever the case, we'll punt #3707 a bit further now.

**Comment by paulirish** [comment]
Fixed by waitForNavigated.
Not pursuing data-uri soon.

**Comment by connorjclark** [comment]
updated the branch again https://github.com/GoogleChrome/lighthouse/compare/undo-revert-datauri

crash doesn't seem to happen anymore.

it's also slower.

```
node lighthouse-core/scripts/compare-runs.js --name baseline-about-blank --collect -n 10 --urls http://www.example.com
node lighthouse-core/scripts/compare-runs.js --name pr-empty-page --collect -n 10 --urls http://www.example.com
node lighthouse-core/scripts/compare-runs.js --name baseline-about-blank --name pr-empty-page --compare --filter='lh:gather:loadBlank'
```

![image](https://user-images.githubusercontent.com/4071474/85604655-56c48480-b606-11ea-9be9-e45515382b73.png)

any reason we'd prefer an empty page over `about:blank` at this point?

**Comment by patrickhulce** [comment]
about:blank also had some different characteristics wrt renderer process selection and unload/navigation timing but I don't think they're major. I think we can stick to the current strategy.

(curious what sparked this reinvestigation)

**Comment by connorjclark** [comment]
I was just tying up loose ends.
