### ISSUE TITLE
rel="noopener" audit should ignore href="mailto:x@y.com" links

### ISSUE THREAD

**Issue by Splaktar** [GoogleChrome/lighthouse#3714]
<img width="699" alt="screen shot 2017-11-01 at 2 34 04 pm" src="https://user-images.githubusercontent.com/3506071/32291560-c8efe24e-bf13-11e7-9f43-aebd77968668.png">

Following this suggestion for these `mailto:` links causes the links to break on Chrome for Android and iOS Safari. Unfortunately, we only found this issue in production :(

![screenshot_20171101-151030](https://user-images.githubusercontent.com/3506071/32292580-f4806d68-bf16-11e7-9b6e-22d545d529ef.png)

Reproduction:
```
<ul>
        <li>
          <a href="mailto:sales@marketamplified.com" target="_blank">
            <mat-icon>mail_outline</mat-icon>Sales
          </a>
        </li>
        <li>
          <a href="mailto:support@marketamplified.com" target="_blank" rel="noopener">
            <mat-icon>mail_outline</mat-icon>Support
          </a>
        </li>
</ul>
```
The support link fails as seen above on Chrome for Android. The sales link works fine and launches Gmail from Chrome for Android.

**Comment by patrickhulce** [comment]
Oh wow that's rough! That definitely seems like a Chrome bug, mail application is correctly opened for Chrome on macOS. It seems like Chrome generally doesn't like `target="_blank"` with mailto links though, it doesn't [seem to work at all on iOS](https://bugs.chromium.org/p/chromium/issues/detail?id=682783&q=mailto&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

From our side we should definitely ignore these too, but it seems like it's a good idea to remove target=_blank from mailto links in general 👍

**Comment by Splaktar** [comment]
That's really helpful @patrickhulce! I had no idea that `target="_blank" was not supported on iOS (and Android) for `mailto:` links. `target="_blank"` causes problems, but `target="_blank" rel="noopener"` is even worse on iOS and Android.

It does appear that `rel="noopener"` is working for me when `target="_blank"` is removed.

Perhaps there should be an audit to warn against using `target="_blank"` on `href="mailto:"` links instead since it works fine on Desktop but not on mobile.

**Comment by wardpeet** [comment]
@patrickhulce should we only do checks on http & https protocol?

**Comment by patrickhulce** [comment]
@wardpeet yeah seems like a good idea instead of playing whack-a-mole with everything we're forgetting :)

**Comment by sanjsanj** [comment]
Hey gang, big fan - awesome work!  I've gained a lot from looking through your codebase.

I had a quick look at this issue last night and I might be able to submit a PR for it, is it still available please?

**Comment by patrickhulce** [comment]
@sanjsanj yes please go for it! The latest approach we think we'd like here is just limiting this audit to looking at urls starting with `http` :)

**Comment by sanjsanj** [comment]
@patrickhulce Excellent, thank you!  I could happily do that but would that not miss relative URLs or ones without protocols?  Or am I missing something here in my understanding?

**Comment by patrickhulce** [comment]
Ah yes, the gatherer should already fully resolve the URLs for you so you don't have to worry about handling relative links

**Comment by sanjsanj** [comment]
Gotcha, cheers!
