### ISSUE TITLE
Aspect ratio audit fails on SVG

### ISSUE THREAD

**Issue by peterjanes** [GoogleChrome/lighthouse#3716]
The image aspect ratio audit appears to fail for SVG images. If you run a "best practices" audit on [the standalone HTML file in this zip](https://github.com/GoogleChrome/lighthouse/files/1435521/svg-test.zip) (unzip it and put it on a webserver) you'll see it includes

```
Does not uses Images with appropriate aspect ratio
Image displayed sizes should match their natural aspect ratio.
```

I've tried it with different combinations of width/height attributes and CSS, and none can make it pass the audit.

**Comment by patrickhulce** [comment]
Thanks for reporting @peterjanes! We ignore SVGs for responsive image savings but we should ignore them here too 👍 

For any potential first-time bug fixers, we just need to filter out based on mimeType here
https://github.com/GoogleChrome/lighthouse/blob/fbe3fda0d7203039e378c101e482a7974c2f9949/lighthouse-core/audits/image-aspect-ratio.js#L73-L78

**Comment by TejasQ** [comment]
On it!

**Comment by patrickhulce** [comment]
Thanks so much for volunteering @TejasQ but Peter beat you to the punch 😄  feel free to take a look at some of our other [good first issues](https://github.com/GoogleChrome/lighthouse/labels/good%20first%20issue)!

**Comment by TejasQ** [comment]
Thanks @patrickhulce! Missed the reference from @peterjanes!

**Comment by leonardorey1970** [comment]
Hi all, do you have any idea about when this changes will deployed to prod?.

Cheers!
Leo

**Comment by patrickhulce** [comment]
@leonardorey1970 should go out with our next release by end of this week in extension and CLI. Chrome stable will get it around end of January.

**Comment by leonardorey1970** [comment]
Thanks patrickhulce  for your reply!
