### ISSUE TITLE
DevTools Error: Unable to load page: failed document request ()

### ISSUE THREAD

**Issue by Bgshanoams** [GoogleChrome/lighthouse#3717]
**Initial URL**: https://rcwolf.us/images/DEMOON/BANER/galaxy/DEMOONWOLF-125px.gif
**Chrome Version**: 63.0.3239.18
**Error Message**: Unable to load page: failed document request ()
**Stack Trace**:
```
Error: Unable to load page: failed document request ()
    at Function.assertPageLoaded (chrome-devtools://devtools/remote/serve_file/@975787a36cf8dbe16eaf42134aaee20fe9504ba2/audits2_worker/audits2_worker_module.js:826:73)
    at pass.then._ (chrome-devtools://devtools/remote/serve_file/@975787a36cf8dbe16eaf42134aaee20fe9504ba2/audits2_worker/audits2_worker_module.js:830:224)
    at <anonymous>
```

**Comment by techy16** [comment]
any updates on this issue?

I am facing the below error 

Runtime error encountered: Your page failed to load. Verify that the URL is valid and re-run Lighthouse.
LHError: FAILED_DOCUMENT_REQUEST
    at Function.getPageLoadError (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:163:21)
    at pass.then._ (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:298:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by techy16** [comment]
Hi Patrick,

When i run on windows the same url it works but when i run it on linux with
headless browser it is not working. It will be a great help if you can
suggest any solution.

+ lighthouse --output html --output-path report.html
'--chrome-flags=--headless --no-sandbox
--ignore-urlfetcher-cert-requests --allow-insecure-localhost'
https://* <https://www.some-none-existing-domain.com/>**************
--view

Wed, 28 Mar 2018 20:59:34 GMT ChromeLauncher Waiting for browser.
Wed, 28 Mar 2018 20:59:34 GMT ChromeLauncher Waiting for browser...
Wed, 28 Mar 2018 20:59:35 GMT ChromeLauncher Waiting for browser.....
Wed, 28 Mar 2018 20:59:35 GMT ChromeLauncher Waiting for browser..... [32m✓ [0m
Wed, 28 Mar 2018 20:59:35 GMT status Initializing…
Wed, 28 Mar 2018 20:59:36 GMT status Loading page & waiting for onload
URL, Scripts, CSSUsage, Viewport, ViewportDimensions, ThemeColor,
Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage,
Accessibility, EventListeners, AnchorsWithNoRelNoopener,
AppCacheManifest, DOMStats, JSLibraries, OptimizedImages,
PasswordInputsWithPreventedPaste, ResponseCompression,
TagsBlockingFirstPaint, WebSQL, MetaDescription, FontSize,
CrawlableLinks, MetaRobots, Hreflang, EmbeddedContent, Canonical,
RobotsTxt, Fonts
Wed, 28 Mar 2018 20:59:42 GMT statusEnd Loading page & waiting for onload
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving trace
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving devtoolsLog and network records
Wed, 28 Mar 2018 20:59:42 GMT GatherRunner:error
FAILED_DOCUMENT_REQUEST https://*
<https://www.some-none-existing-domain.com/>***************
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: URL
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: Scripts
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: CSSUsage
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: Viewport
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: ViewportDimensions
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: ThemeColor
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: Manifest
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: RuntimeExceptions
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: ChromeConsoleMessages
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: ImageUsage
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: Accessibility
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: EventListeners
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: AnchorsWithNoRelNoopener
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: AppCacheManifest
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: DOMStats
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: JSLibraries
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: OptimizedImages
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving:
PasswordInputsWithPreventedPaste
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: ResponseCompression
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: TagsBlockingFirstPaint
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: WebSQL
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: MetaDescription
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: FontSize
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: CrawlableLinks
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: MetaRobots
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: Hreflang
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: EmbeddedContent
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: Canonical
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: RobotsTxt
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: Fonts
Wed, 28 Mar 2018 20:59:42 GMT status Loading page & waiting for onload
ServiceWorker, Offline, StartUrl
Wed, 28 Mar 2018 20:59:42 GMT statusEnd Loading page & waiting for onload
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving devtoolsLog and network records
Wed, 28 Mar 2018 20:59:42 GMT GatherRunner:error
FAILED_DOCUMENT_REQUEST https://
<https://www.some-none-existing-domain.com/>*************
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: ServiceWorker
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: Offline
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: StartUrl
Wed, 28 Mar 2018 20:59:42 GMT status Loading page & waiting for onload
HTTPRedirect, HTMLWithoutJavaScript
Wed, 28 Mar 2018 20:59:42 GMT statusEnd Loading page & waiting for onload
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving devtoolsLog and network records
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: HTTPRedirect
Wed, 28 Mar 2018 20:59:42 GMT status Retrieving: HTMLWithoutJavaScript
Wed, 28 Mar 2018 20:59:42 GMT status Disconnecting from browser...
Wed, 28 Mar 2018 20:59:42 GMT status Disconnecting from browser...
Wed, 28 Mar 2018 20:59:42 GMT CriConnection:warn disconnect() was
called without an established connection.
Wed, 28 Mar 2018 20:59:42 GMT ChromeLauncher Killing Chrome instance 32
Runtime error encountered: Your page failed to load. Verify that the
URL is valid and re-run Lighthouse.
LHError: FAILED_DOCUMENT_REQUEST
    at Function.getPageLoadError
(/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:163:21)
    at pass.then._
(/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:298:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by techy16** [comment]
My App url has both http and https version running on intranet. When i run with http it works fine but when i run with https i got the above error? 
Any suggestion or help would be great to resolve this issue

**Comment by Kaugar** [comment]
Hi could you solve this? I have the same problem, on windows it works, on linux not.

**Comment by patrickhulce** [comment]
As stated above and in the linked issue (#2784), this error means that the page's main document could not be loaded and is not a problem with Lighthouse. Usually this is because of a server configuration, network connectivity, or SSL certificate problem. Make sure you can load your URL in a clean Chrome profile without any security interstitial before trying to use Lighthouse.
