### ISSUE TITLE
Problems with multiple service workers

### ISSUE THREAD

**Issue by prash-mi** [GoogleChrome/lighthouse#3724]
Found few issues while using lighthouse for https://www.lenskart.com/

1. Says "Does not register a Service Worker" , whereas 'Application' tab shows service worker running.

2.  Spawns multiple service workers upon running lighthouse, I had run it twice and attached screenshot shows 3 SW running (1 while site load + 2 while running lighthouse)

Chrome version: Version 61.0.3163.100 (Official Build) (64-bit)
OS: Mac OSX 10.12.6

Attached screenshots.
<img width="1680" alt="3 sw running" src="https://user-images.githubusercontent.com/11733935/32319907-1089643a-bfe2-11e7-9b36-205b1279b31b.png">
<img width="1354" alt="sw issue" src="https://user-images.githubusercontent.com/11733935/32319908-10c2dd32-bfe2-11e7-843e-a8ad2c966e87.png">

**Comment by patrickhulce** [comment]
Thanks for raising this @prash-mi! There's definitely some strange behavior going on here. We'll have to dig into this.

**Comment by AymericG** [comment]
I have similar issue with https://next.weekplan.net

**Comment by balasacoe** [comment]
we too have similar issues with https://www.voot.com/

**Comment by paulirish** [comment]
Are you guys using some workbox/sw-toolkit stuff for your sw generation?

**Comment by Wqrld** [comment]
@paulirish Yes, I have this while using workbox

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
