### ISSUE TITLE
ImageUsage gatherer: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#3731]
Encountered in #2293 on https://www.victoriassecret.com/

Audit error: Required ImageUsage gatherer encountered an error: Cannot read property 'tagName' of null

![image](https://user-images.githubusercontent.com/2301202/32355407-a95b406c-bfeb-11e7-8042-0afad79b1495.png)

comes from line 48 where we grab the parentElement of the image 

should be `!!element.parentElement && element.parentElement.tagName === 'PICTURE'`
https://github.com/GoogleChrome/lighthouse/blob/cfc2afe07eb8e23b8ff07d90760b0cfbe24be85c/lighthouse-core/gather/gatherers/image-usage.js#L34-L52

**Comment by ThisIzKp** [comment]
@patrickhulce I'm picking up this
Hopefully.. I'll not get stuck this time 😜

**Comment by AkshayIyer12** [comment]
@patrickhulce I want to work on the issue.

**Comment by patrickhulce** [comment]
great thanks for volunteering @AkshayIyer12! Let us know if you run into any issues :)

**Comment by AkshayIyer12** [comment]
@patrickhulce I have done the change locally on my system
```!!element.parentElement && element.parentElement.tagName === 'PICTURE' ``` 
But I'm not sure how to proceed further.

**Comment by patrickhulce** [comment]
correct @AkshayIyer12 thanks for fixing!

next steps for you are to...

1. commit your code with appropriate message, `core(image-usage): add null check for parentElement` is fine
2. push your code to your fork on github, assuming you cloned from your fork the command would be something like `git push -u origin name_of_your_branch`, GitHub has some [intro git tutorials](https://try.github.io/levels/1/challenges/1) if you're unsure what the branch, fork, and push terms are
3. open a pull request on our repo pointing to the branch on your fork
4. wait for us to review and address any comments that come up
5. dance and celebrate your first 💡 🏠  contribution! 🎉  😄

**Comment by patrickhulce** [comment]
fixed in #3779

**Comment by atifwaqar** [comment]
I am getting the following error on Auditing my page : 
![image](https://user-images.githubusercontent.com/4388707/35200289-79443ad2-ff0b-11e7-88b8-9122d66cc4c0.png)

To me it looks like similar or same issue. And I ran the Audit from Chrome Dev tools. 

But when I install Chrome Extension `Lighthouse`, I do not get this error. But I see Accessibility 0, where as I had 100 when I Audited my page using Chrome DebTools. Thats why I'm not relying on Chrome Extension.

**Comment by patrickhulce** [comment]
@atifwaqar can you report the accessibility bug with a reproducible URL as a separate GitHub issue?

DevTools should be updated to current version of Lighthouse in Chrome 65, hits stable ~early March

**Comment by atifwaqar** [comment]
@patrickhulce Sure, I'll prepare the reproducible URL and create a separate GH issue this weekend. As of now, I have only a Production server where I can reproduce this issue, but I cant share that link on GH, so i'll create a new test app, where I reproduce the issue.
