### ISSUE TITLE
Network timestamps differ significantly from NetworkRecorder observed time

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#3734]
Discovered in #2293, on https://www.instagram.com/p/BNQ98s4BTEa/ but probably affects the other sites as well

Summary: we knew we received network events over the protocol later than the request started in cases where main thread was busy (and thus thought waiting for CPU idle would be sufficient), but it appears that network recorder routinely receives events significantly after the request has started. This leads to network recorder believing that fewer network requests are inflight than there really are (as end events are still delivered in a timely manner).

Simplified Example from Instagram

Network record A real start 9544ms `1 inflight, 0 observed inflight`
Network record A observed start: 10111ms `1 inflight, 1 observed inflight`
Network record B real start 10115ms `2 inflight, 1 observed inflight`
Network record A real end 10135ms  `1 inflight, 1 observed inflight`
Network record A observed end: 10137ms  `1 inflight, 0 observed inflight`
Network record B observed start: 10138ms  `1 inflight, 1 observed inflight`
Network record B real end 10139ms  `0 inflight, 1 observed inflight`
Network record B observed end: 10140ms  `0 inflight, 0 observed inflight`

**Comment by vinamratasingal** [comment]
[paul here]  Patrick, do you think we can use the new Page.lifecycleEvent's for netrequestsinflight? Would that resolve this?  Or should we hunt down the source of the timestamp skew?

**Comment by patrickhulce** [comment]
Yeah, we can migrate to that instead looks like it landed in 62. Might want to do some testing to make sure it fires at least as late as our current implementation

**Comment by patrickhulce** [comment]
actually @paulirish a hiccup with moving to the Page.lifecycleEvent is that we ignore `networkQuietThresholdMs`

what do you think about responding to a value of `networkQuietThresholdMs: 'browser'`, by using the lifecycle event but keeping the current logic intact for the other passes?
