### ISSUE TITLE
Not working full config.

### ISSUE THREAD

**Issue by mixed** [GoogleChrome/lighthouse#3740]
Hi. There. :)
When I use a [full-config](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/full-config.js) LH is not working. I saw below message.

```
(node:10706) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: CSS domain enabled when starting trace
(node:10706) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Currently When LH start trace It is not allow enabled status of `CSS/JS`.

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L814-L819

Is it known issue?

**Comment by patrickhulce** [comment]
Thanks for filing @mixed :)

I'm not seeing the same issue though, tracing is not enabled on the extraPass in the full-config that uses the CSS/DOM domains. My run with `yarn start --config-path=./lighthouse-core/config/full-config.js` completed successfully. Are you making any other changes to the config?

**Comment by mixed** [comment]
Thanks for your response. :)
Yes. I use custom [config and flag](https://github.com/GoogleChrome/lighthouse/files/1442031/options.zip). and I launch LH using programming.

```js
const chrome = await chromeLauncher.launch(flag);
flag.port = chrome.port;
const result = await lighthouse(url, flag, config);
await chrome.kill();  
```

**Comment by mixed** [comment]
Thanks. @patrickhulce 
I have found cause. I have merged `defalut config` with `full config`. So, It has occurred above problem.
