### ISSUE TITLE
Move to Node 8

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#3742]
Node 8 has now [hit LTS](https://github.com/nodejs/Release), so we should consider moving over to having that as the minimum supported version. 

We're of course already forward compatible, so anyone wanting e.g. perf improvements from Node 8 and 9 can already run Lighthouse there and get the benefits. However the language improvements [are significant](http://node.green/). Namely:
- `async`/`await` (maybe worth it for the clarity brought by this alone)
- `Object.entries` and `Object.values` (no more `Object.keys(obj).forEach(key => const value = obj[key];...` :)

along with a few other nice things like [object rest/spread](https://github.com/tc39/proposal-object-rest-spread), `String.padStart`, `String.padEnd`, the exponentiation operator, etc.

A mostly organic transition to async/await would probably be best, like we did when we moved to Node v6 and only really added destructuring where it made sense (of course) and where we had some other reason to touch code than just updating to new syntax. We have some tricky promise tricks we use at times and a mass migration could easily miss subtleties (though hopefully our tests won't). And promises and async/await play together nicely, so mixing them for the near future won't be much of an issue.

I'm personally very eager to move over, but it is worth noting that [last time](https://github.com/GoogleChrome/lighthouse/issues/449) we waited until January after the October LTS switch to move up versions, so prudence might have us wait.

**Comment by wardpeet** [comment]
I don't have anything against it. I can always get some babel transpilation going outside of this repo to still support node6

**Comment by patrickhulce** [comment]
Can't wait to do this 👏 

I'm against moving to it without publishing a transpiled version or doing a major version bump though. Dropping 6 & 7 support moves us from [~80% ecosystem coverage to ~35% ecosystem coverage](https://nodejs.org/metrics/) and doing it on a minor version bump would be a bad experience for those in the ~45% not yet moved over to latest LTS.

**Comment by paulirish** [comment]
We need a twitter poll to evaluate our node versions customers.
