### ISSUE TITLE
Overriding user agent using --chrome-flags adds additional quotes to user agent

### ISSUE THREAD

**Issue by orpx** [GoogleChrome/lighthouse#3744]
For example:
Using --chrome-flags="--user-agent=testing123"
Will result a request with the following user-agent: "testing123" (including the quotes), basically every useragent will be automatically surrounded with quotes.

**Comment by patrickhulce** [comment]
Thanks for catching @orpx!

Looks like we're doing some overeager escaping of chrome flags before we pass them off to chrome-launcher 👍
