### ISSUE TITLE
Honoring Chrome's Network Overrides

### ISSUE THREAD

**Issue by olostan** [GoogleChrome/lighthouse#3753]
There is a new feature on Google Chrome - "[Network Overrides"](https://umaar.com/dev-tips/162-network-overrides/) that allows to override resources from local files. 

Currently LightHouse ignore network overrides, however it would be extremely useful when optimising production web site.

**Comment by vinamratasingal** [comment]
Thanks for the suggestion olostan! We'll prioritize this feature request and get back to you :)

**Comment by paulirish** [comment]
This would be totally awesome, but it looks to be a large effort. We'll work towards this one.

**Comment by olostan** [comment]
Meanwhile, as workaround, I've created small tool that behaive like "network overrides" but is "lighthouse-friendly": https://github.com/olostan/overproxy
And here is a small post how to use that: https://medium.com/@olostan/overriding-production-websites-resources-with-local-ones-f3973131ec88

Ofcourse, waiting for Lighthouse nativly support overrides :)

**Comment by brendankenny** [comment]
deduping into #5423 as it captures more context and has a significantly more urgent priority somehow
