### ISSUE TITLE
Getting "method <= browser ERR:error Emulation.setVisibleSize " Error

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [GoogleChrome/lighthouse#3757]
input --> C:\Users\jmallick>lighthouse <url> and the output is
Output -->
 C:\Users\jmallick>lighthouse <url>
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +2ms
  ChromeLauncher Waiting for browser..... +2s
  ChromeLauncher Waiting for browser.....√ +503ms
  status Initializing. +643ms
  method <= browser ERR:error Emulation.setVisibleSize  +12ms
  status Disconnecting from browser... +2ms
  ChromeLauncher Killing Chrome instance 22908 +2ms
ERROR: The process "22908" not found.
  ChromeLauncher:warn Chrome could not be killed Command failed: taskkill /pid 2
2908 /T /F
  ChromeLauncher:warn ERROR: The process "22908" not found.
  ChromeLauncher:warn  +293ms

**Comment by patrickhulce** [comment]
I'm not able to reproduce this issue @JyotiPrakashMallick 

Could you add the details of how we might observe the same behavior? 

* Lighthouse version
* Chrome version
* OS
* URL audited
