### ISSUE TITLE
Unable to install Light house on latest Chrome

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [GoogleChrome/lighthouse#3758]
OS : Windows 7
Version 52.0.2743.116

I am getting "NOT COMPATIBLE" error while installing Lighthouse on chrome. Please refer the screenshot attached.

**Comment by vinamratasingal** [comment]
Hey Jyoti- 

Sorry you're seeing this issue :( Unfortunately, I can't see the screenshot. How were you installing Lighthouse on Chrome?

**Comment by patrickhulce** [comment]
@JyotiPrakashMallick you'll need to update your version of Chrome. Lighthouse requires a modern Chrome installation and 52 is quite old. You should be able to visit `chrome://settings/help` to trigger an update.

**Comment by JyotiPrakashMallick** [comment]
@vinamratasingal Let me re-frame my statement it is Chromium ant the version is correct and really don't know why you are not able to see the image but I have attached in the section provided.

**Comment by JyotiPrakashMallick** [comment]
So the question here, light house is it not supportable for Chromium ??

**Comment by vinamratasingal** [comment]
Hey Jyoti- I am still not able to see a screenshot. Can you give us the following info: 

- Lighthouse version
- Chrome version (can be found by going to chrome://chrome)
- OS
- URL audited

**Comment by JyotiPrakashMallick** [comment]
This issue can be closed as the problem with installing has been resolved.
