### ISSUE TITLE
images aspect ratio false warning when using SVGs

### ISSUE THREAD

**Issue by hamedbaatour** [GoogleChrome/lighthouse#3759]
⚠️  "Does not uses Images with appropriate aspect ratio" - **Bug Report**

this warning is always showing although the page I'm testing has no images whatsoever and it only uses inline HTML SVG tags. It is clearly a bug as if there were images with a wrong aspect ratio it should show a list them but when I expand the section of the warning nothing shows up as displayed in the image below.

![image](https://user-images.githubusercontent.com/5658460/32435950-88b6e64e-c2f3-11e7-9004-95b14acefe0d.png)

**Comment by joshvogt** [comment]
I'm seeing the same thing. Our page has a few SVG's but they're all inline.

**Comment by patrickhulce** [comment]
Thanks so much for the report @hamedbaatour! This has actually already been fixed by #3552 and will be out in the next release. The bug was that it always reports as failing even when it's passing :)
