### ISSUE TITLE
Angular js application in not supportable.

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [GoogleChrome/lighthouse#3769]
Trying to generate light house report on an angular js based enterprise web application.  And anytime I am running I am getting a blank page on report. So don't it support angular js based application.

**Comment by vinamratasingal** [comment]
Hi Jyoti- thanks for filing this! It seems like your issue could be related to #3758, so let's take the conversation there. I will close this bug for now.

**Comment by JyotiPrakashMallick** [comment]
@vinamratasingal  these two are separated issue. First one is the compatibility issue and this one is related to the web application being used by me. Question still open here is does light house support angular js based web application.
