### ISSUE TITLE
Will there be support for client certificates for 2 way ssl auth

### ISSUE THREAD

**Issue by dmmulroy** [GoogleChrome/lighthouse#3770]
I'm unable to use the Audit feature of devtools because the applications I work on require a user certificate to be loaded in the browser.  I tried searching through existing/closed issues but couldn't find anything, any chance this on the roadmap to be supported? Thanks!

**Comment by paulirish** [comment]
Can you load the user certificate with a command-line flag?  https://peter.sh/experiments/chromium-command-line-switches/

Perhaps you can just add `--ignore-certificate-errors` into the CLI's --chrome-flags option?

**Comment by paulirish** [comment]
You can also add the certificate into your OS's trusted certificates.

**Comment by brendankenny** [comment]
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen, but hopefully the advice above is sufficient.
