### ISSUE TITLE
Invalid properties found: {"viewport-fit":"cover"}.

### ISSUE THREAD

**Issue by krabbypattified** [GoogleChrome/lighthouse#3771]
This is an iOS optimization. Why should this make me fail the PWA checklist?

**Comment by dickeylth** [comment]
As of current latest lighthouse version `2.8.0`, the issue still occurs in the `SEO` part of the report:

![image](https://user-images.githubusercontent.com/2196373/35901681-dd4fa160-0c12-11e8-9904-4d85b48c3f3b.png)
