### ISSUE TITLE
Enable SEO audits in the UI

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#3772]
When the rest of the [SEO issues for Sprint Tres](https://github.com/GoogleChrome/lighthouse/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Sprint+Tres%3A+Oct+30+-+Nov+12%22+project%3AGoogleChrome%2Flighthouse%2F3) are completed, we should be in a good place to enable the SEO audits in the LH UI. We will continue to iterate on the remaining audits and add them to the UI as they become available.

The [SEO-only extension](https://github.com/GoogleChrome/lighthouse/issues/3656) also intended to make the SEO audits publicly accessible, so this change would replace it. The extension could still be useful in some cases when we want to get feedback on the SEO audits. The Audits panel of DevTools will still take a while to update and users can install the special purpose extension (or the full LH extension to demo all audits... but this would focus their attention only on SEO audits).

**Comment by vinamratasingal** [comment]
Hey Rick- thanks for the update. Is the SEO-only extension going to be publicly launched? Or just for internal testing?

**Comment by rviscomi** [comment]
Just for internal testing.
