### ISSUE TITLE
Link to scoring docs from the LH report

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#3773]
Let's externalize the scoring documentation in our docs section to the Lighthouse /dev documentation. Once the documentation is done, we can then add a "Learn More" link within the report to link to the documentation.

**Comment by paulirish** [comment]
This may be blocked by #3546, depending on how we want to do things

**Comment by vinamratasingal** [comment]
Kayce published the docs, but we still need to link the pushed doc from the report. Can we finish this in Sprint Seite?

**Comment by paulirish** [comment]
scoring doc published on the site now. 👍 
next up: paul links to it from the report.

**Comment by brendankenny** [comment]
> next up: paul links to it from the report.

This will be handled by #3773 :)

**Comment by brendankenny** [comment]
by which I mean #8717 :)
