### ISSUE TITLE
Detecting performance-affecting Chrome extensions

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#3776]
Given the fact that installed Chrome extensions might interfere with Lighthouse results, can we have an audit to detect installed Chrome extensions? My sense is that this might be tricky from a product perspective to explain as a performance optimization, but interesting idea, especially to move the ecosystem forward and aware of the extension issue.

**Comment by paulirish** [comment]
We look at bootup-time audit and if there are chrome extensions spending main thread time, then we add a topLevelWarning about them.

**Comment by paulirish** [comment]
duping into #4013
