### ISSUE TITLE
Chrome sandbox issues on Linux

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/lighthouse#378]
On Linux at least, it seems the sandbox is mis-named. It is provided as `chrome_sandbox` however, this causes a core dump at launch unless you launch with `--no-sandbox`. Renaming that file to `chrome-sandbox` fixes the problem.

Can we work-around this in our process until the problem can be investigated more within the builds itself? I'm thinking in our `update-chromium.sh` script we simply unzip and then move the file in there. Easy enough.

**Comment by youngdelaney** [comment]
O right

**Comment by Garbee** [comment]
I just talked this roadblock over with Torne on IRC a bit...

The sandbox file itself is not required on newer systems. The [check for it hasn't been removed](https://bugs.chromium.org/p/chromium/issues/detail?id=598454) which is causing the problems. However, older systems may still require it. The thing is, *renaming alone* is only enough to apparently make any errors silent (or will cause it to fail once something is hit.)

The **recommended** way to solve this is, move the sandbox into a static place, `sudo chown root chrome-sandbox; sudo chmod 4755 chrome-sandbox`, then set `CHROME_DEVEL_SANDBOX` as an environment variable to the sandbox.

If that env var is set, then regardless of what is in the folder itself it will be used and therefore cause no problems. So we have some options here:

1) Rename the file internally and just hope people are all running with newer kernels and not need the sandbox.
2) Don't rename the file and add to the install/setup procedure to do a download and setup the sandbox manually the first time you run. Just in case. :tm:
3) Combine 1 and 2. Do the rename and warn developers if things fail to try setting up the sandbox manually.

**Comment by brendankenny** [comment]
any reason not to just use `--disable-setuid-sandbox` [as we do on Travis](https://github.com/GoogleChrome/lighthouse/blob/c3bf95ba7ad07d6cd30d0882e98a2e2ea97d6590/.travis.yml#L18)? Reading through the bugs, the check does nothing anymore and the older systems that may be an issue sound like they aren't actually Chromium-supported systems anymore.

**Comment by Garbee** [comment]
Ah, didn't know that flag existed. Looking in the [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=245376) for it...

> Add a new --disable-setuid-sandbox flag to disable the setuid
  sandbox without disabling seccomp-bpf.

Looks good to me to go with this route, I'll update my PR accordingly.

**Comment by sam0104** [comment]
I have issues on Chrome version 66.0.3359.139 64 bit running on Ubuntu . 
It is not responding while I click on the icon. Also while I created a desktop launcher with command parameter : /usr/bin/google-chrome-stable %U   . It is not responding unless I change the parameter to 

working parameter : /usr/bin/google-chrome-stable %U --no-sandbox 

With --no-sandbox I am able to open Chrome browser but getting warning message "You are using an unsupported command-line flag: --no-sandbox. Stability and security will suffer. 

Please let me know if we have some fix for it.  My ubuntu version is Ubuntu 18.04 LTS  and it is running on a docker container.

**Comment by Garbee** [comment]
> My ubuntu version is Ubuntu 18.04 LTS and it is running on a docker container.

Docker is the problem here. If you get owned anyways, your attacker has root to go through any security boundary you have setup. You'd need to run Chrome within the container as a non-root user to get it to work with the sandboxing. [This post](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b) has some starting pointers on setting up a non-privileged user in a container to work with. So use that as a starting point to get your container to a working and more secure state.

**Comment by sam0104** [comment]
I am already using non-root user. Does sandboxing has some limitations if I am using sandboxing anyway ?

**Comment by Garbee** [comment]
Ah yea, looks like the root cause is Docker messing with [seccomp by default](https://github.com/jlund/docker-chrome-pulseaudio/issues/8). According to the referenced issue, you can loosen it in Docker v1.10+. So something along those lines might be worth a shot.
