### ISSUE TITLE
How to change the audit option from mobile emulated device to desktop emulated device ??

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [GoogleChrome/lighthouse#3783]
Step to execute:
1. Open an url in browser.
2. Open the web developer tool and navigate to "Audit" option.
3. Now in the emulated device option I changed it to "Desktop".
4. Clicked on "Perform and audit".

Still it run on the default device "Nexus 5X". Is there any way to change it to desktop version as my application is not support mobile platform.

**Comment by vinamratasingal** [comment]
Hi Jyoti- we don't have an option to do desktop emulation through the Extension or DevTools yet. You can use the CLI (I believe it's the --disable-device-emulation flag). 

Closing for now since I answered your question, feel free to reopen if other questions pop up. Thanks :)
