### ISSUE TITLE
Google Home Page - Accessibility

### ISSUE THREAD

**Issue by abupathan** [GoogleChrome/lighthouse#3784]

**Comment by vinamratasingal** [comment]
Hi Abupathan- can you add some more description to your request? I'm not quite sure what the bug is.

**Comment by carlenzoli** [comment]
Hi @vinamratasingal,
is a (now) standard Google problem with design and contrast, test with wonderful [AXE estension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd):

![selezione_203](https://user-images.githubusercontent.com/24408521/33241561-6eb178ca-d2c7-11e7-9517-79ba4a20efa2.png)

p.s.
AXE integrate by default in Lighthouse is good idea IMHO

Bye,
Yuri.

**Comment by vinamratasingal** [comment]
Hi Yuri- 

Thanks for writing in! We are using AXE under the hood with our accessibility integration (and it seems like you are screenshotting the accessibility section of the report in Lighthouse). Could you be a bit more specific with your request?

Vinamrata

**Comment by carlenzoli** [comment]
My mistake, Vinamrata, (AXE), developer tools is accetable, my screenshot come from developer tools.

Sorry,
Yuri.

**Comment by patrickhulce** [comment]
We're not seeing the same issue with aXe vs. Lighthouse anymore.

![image](https://user-images.githubusercontent.com/2301202/37182785-bf648d6e-22e7-11e8-8a08-0c02dde63fc5.png)
