### ISSUE TITLE
Write a help doc for the HTTP status code audit

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#3787]
The only audit that does not already have a help doc is https://github.com/GoogleChrome/lighthouse/issues/3181. It should live on d.g.co with the other Lighthouse audit documentation.

The docs will be really short and simple. Basically:

- all pages are served with an HTTP status code (200, 404, etc)
- pages with error statuses (4xx, 5xx) may not be indexed properly
- pages that visually appear to load successfully may have been served with an error status

**Comment by brendankenny** [comment]
You may have already talked with @kaycebasques about this, but if he doesn't currently have the time these all live in https://github.com/google/WebFundamentals/tree/master/src/content/en/tools/lighthouse/audits and can be added with a PR there

**Comment by rviscomi** [comment]
:-O didn't get an update that the PR was merged in WF! Thanks @kaycebasques!

https://developers.google.com/web/tools/lighthouse/audits/successful-http-code
