### ISSUE TITLE
Feature Request: Can you provide multiple urls?

### ISSUE THREAD

**Issue by george-nelson** [GoogleChrome/lighthouse#3788]
From the command prompt can you provide a list of URL's instead of one at a time?
From this:
lighthouse <url>

to
lighthouse <url1, url2, url3>

**Comment by benschwarz** [comment]
@george-nelson, right now lighthouse runs a single URL, but if you wanted to run a bunch of URL you could do so sequentially using a bash script or something like that?

**Comment by george-nelson** [comment]
Thanks for the quick response. That's how I have configured in Jenkins. My ultimate goal is have some sort of dashboard in a matrix format.
-------------------------------------------------------------
URL            Performance    Accessibility   Best Practices
-------------------------------------------------------------
Site1          0                       83                    63
Site2           10                     68                   90

**Comment by vinamratasingal** [comment]
Hey George- thanks for passing along this request! This is something we're definitely considering implementing, but need to prioritize accordingly. Keep watching the bug and we'll update it soon with the prioritization :)

**Comment by stevector** [comment]
@george-nelson some of the code in this package might help: https://github.com/emazzotta/lighthouse-badges

It takes a list of urls like you describe but produces badges with averages rather than a detailed matrix.

**Comment by george-nelson** [comment]
Will take a look at it - thank you for the follow up

Sent from my iPhone

On Feb 6, 2018, at 3:43 PM, Steve Persch <notifications@github.com<mailto:notifications@github.com>> wrote:


@george-nelson<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeorge-nelson&data=02%7C01%7C%7C4bc94e430acb417421d008d56daaaa84%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636535502122450838&sdata=cd4Ftahpy9MRJjHW1Mbm5n7e3ituSI7Dl8wjRJna0tY%3D&reserved=0> some of the code in this package might help: https://github.com/emazzotta/lighthouse-badges<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Femazzotta%2Flighthouse-badges&data=02%7C01%7C%7C4bc94e430acb417421d008d56daaaa84%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636535502122450838&sdata=tKUkRmFsAAdQe1nrTtI9CkCbXSVoQRRmU4mejfQ2bqk%3D&reserved=0>

It takes a list of urls like you describe but produces badges with averages rather than a detailed matrix.

**Comment by allthesignals** [comment]
I think we realized that the metric for "Unused CSS" might not be accurate for our SPA because certain views weren't being rendered for that just yet. Multiple URLs in a single `lighthouse` run would help give a better sense of that metric - but maybe reconciling those performance tests across multiple URLs is a much bigger task than I'm imagining!

**Comment by brendankenny** [comment]
Closing in favor of other tools. Can script on the command line (or in node) or try one of the many [integrations and related projects](https://github.com/GoogleChrome/lighthouse#lighthouse-integrations)

**Comment by githubjosh** [comment]
Does feel like enabling an array of URLs into the CLI tool should be pretty straight-forward and helpful

**Comment by patrickhulce** [comment]
Does feel like `cat urls.txt | xargs -I % lighthouse %` should be pretty straight-forward to do without unnecessarily complicating the core library.
