### ISSUE TITLE
Nit: tweak to warning text for problematic image aspect ratio

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#3796]
This might be better: 'Displays images with incorrect aspect ratio. Image display dimensions should match natural aspect ratio.'

![image](https://user-images.githubusercontent.com/205226/32619800-a3b6d242-c573-11e7-9cc3-7848d512933a.png)

**Comment by vinamratasingal** [comment]
Makes sense- Patrick, can you make the copy change as Sam suggestd?

**Comment by patrickhulce** [comment]
sure
