### ISSUE TITLE
Lighthouse (full) chrome extension

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#38]
#### Lighthouse full extension

We merge the two: LighthouseLite (#37) and Lighthouse-core.

* Swap in [chrome.debugger API](https://developer.chrome.com/extensions/debugger) in for chrome-remote-interface. 
  * E.g. Here's protocol via chrome.debugger: https://github.com/paulirish/emulation-popup-ext/blob/master/app/scripts/background.js#L95-L123
* Browserify lighthouse/extension.js, etc
* Redeploy on top of LHLite

**Comment by brendankenny** [comment]
should this be closed with #49? Work that still needs to be done now seems to fall into more specific issues (eg #59)

**Comment by paulirish** [comment]
We didn't yet redeploy but otherwise yes.
