### ISSUE TITLE
More robust smoke test testing

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#381]
building on existing [smoke test](https://github.com/GoogleChrome/lighthouse/blob/1548a45a0f172526110e7dd1cdeaf4d91cbb31de/scripts/run-smoke-tests.sh), separate from the unit tests. See also #307

**Comment by paulirish** [comment]
FTR we removed the smoke tests from the module unit tests:
https://github.com/GoogleChrome/lighthouse/commit/62adf05401f759abf54e5fce0346b2a775c51566#diff-eff7ed6076e98649f26365cd1701d25d

**Comment by brendankenny** [comment]
right, just to be clear, this is to track building on `run-smoke-tests.sh` since we removed the end-to-end tests from the unit tests in #375

**Comment by paulirish** [comment]
Somewhat fixed by #504 

Going to close for now until this is more specific
