### ISSUE TITLE
Incorrect aspect ratio warning on SVG images

### ISSUE THREAD

**Issue by TheDutchCoder** [GoogleChrome/lighthouse#3818]
It looks like that validator has issues with embedded SVG's.

The validator fires off a warning about incorrect ratios, but it doesn't actually tell which images are supposedly the culprit(s).

My test page has no `img` images, only embedded SVG's (through a `use`) and it fails on aspect ratios. Could this be due to rounding in the browser?

E.g. my SVG has a viewbox of `0 0 413 70` (aspect ratio 1:5.9), but the browser sizes it to 140x23.72 (aspect ratio 1:5.902).

**Comment by patrickhulce** [comment]
Thanks for reporting @TheDutchCoder! This has actually already been fixed by #3722 and should go out with the next release sometime this week.

**Comment by TheDutchCoder** [comment]
Gotcha, thanks.

I searched in issues but not in PR's, my bad!
