### ISSUE TITLE
Lighthouse / Wrong data on critical resource 

### ISSUE THREAD

**Issue by adardesign** [GoogleChrome/lighthouse#3832]
I am looking at [This page](https://www.adorama.com/ifjxt2.html) and [here is the lighthouse report](http://www.webpagetest.org/lighthouse.php?test=171116_VT_25a81b7a878073f7ec1b79ab4eb290a9&run=2)
 
I clearly see that `/plugins/like.php?href=` is deferred and even delayed
Why does it still show up as a critical resource?  

Please help.

**Comment by patrickhulce** [comment]
Thanks for filing @adardesign! The critical request chains audit is surfacing requests that Chrome issued with a high priority, not necessary ones that are render-blocking. We still need to update the wording in the report to make sure this is clear!

This work is tracked by #2324, but feel free to chime in there with any additional info that might help!
