### ISSUE TITLE
Document --no-enable-error-reporting and CI env var

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#3854]
https://github.com/GoogleChrome/lighthouse/blob/master/docs/error-reporting.md mentions the `--no-enable-error-reporting` but the readme and `lighthouse --help` do not list this flag.

That page also mentions as `CI` env variable. Needs examples and mention of that in  `--help`.

It may also be better to rename the flag `--disable-enable-error-reporting` to be consistent with the other disable flags.

**Comment by paulirish** [comment]
this all sounds good, yah.  can improve readme and --help.

> It may also be better to rename the flag --disable-enable-error-reporting to be consistent with the other disable flags.

yargs automatically adds a --no-* flag for any boolean flag that is mapped to `--enable-error-reporting=false`.

**Comment by ebidel** [comment]
Oh that's nice. I guess there's no way for someone to know that...we're
using yargs.

**Comment by paulirish** [comment]
ya totally agree. :) something we gotta make more clear

**Comment by brendankenny** [comment]
> It may also be better to rename the flag `--disable-enable-error-reporting` to be consistent with the other disable flags.

one issue we were trying to address here is to make sure the default value was still falsey, but since the default behaviors is to not enable logging without asking, that meant the flag needed to be phrased affirmatively. The downside is that leaves it phrased the opposite of all the `--disable-*` flags

**Comment by patrickhulce** [comment]
Yeah I'd argue the disable ones should have been labeled affirmatively as well and just leverage the `--no-*` benefits of yargs so this wouldn't be as foreign to folks. 

Seems like there's a balance here. I'm not convinced a fringe concern that's fairly well documented in its own file and linked from README and CLI itself should also be thoroughly explained in the --help output, but for sure the `--no-*` examples there would be great 👍

**Comment by wardpeet** [comment]
should we create a new issue to remove all disable cli options and move to --no-.. when we reach a new major?

We can for now start supporting both but only mention --no in help
