### ISSUE TITLE
Access denied configstore/lighthouse.json - Lighthouse 2.6.0

### ISSUE THREAD

**Issue by pmeenan** [GoogleChrome/lighthouse#3873]
WebPageTest is getting errors when running Lighthouse tests with the rollout of 2.6.0:

```
lighthouse --disable-network-throttling --disable-cpu-throttling --max-wait-for-load 80000 --port 9223 --output html --output json --output-path "/home/pmeenan/src/wptagent/work/VM9-01/171121_80_d734845debd314ef2a98045ce95942e1.1.0/lighthouse.json" --save-assets "http://www.webpagetest.org/"
(node:21334) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: EACCES: permission denied, open '/home/pmeenan/.config/configstore/lighthouse.json'
You don't have access to this file.

(node:21334) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

configstore is created with root permissions probably because the lighthouse install was installed through sudo (though certainly don't want to run lighthouse audits under sudo when running).

I have a work-around in place to change permissions but it's worth being aware of.

**Comment by wardpeet** [comment]
I believe `configstore/lighthouse.json` is created by the node process itself so if it runs on the the same user each time their shouldn't be an issue.

You can also look at `$XDG_CONFIG_HOME` to set a different folder

**Comment by pmeenan** [comment]
It had to have been created as part of the install which is done through:

```bash
sudo npm install -g lighthouse
```

That is the only time Lighthouse has root permissions on the WebPageTest agents.  Actually running the testing is done without sudo though and is what triggers the error.

**Comment by patrickhulce** [comment]
Ah, this is a good find thanks @pmeenan! Strange that the configstore directory would be created on install instead of on first run when the permissions would be correct though.

**Comment by paulirish** [comment]
Looking into it, I don't think it was from the `sudo npm install`.

This is the same bug, but upstream: https://github.com/yeoman/configstore/issues/34#issuecomment-171968299

Sindre indicates: 

> If the user has previously run a tool using `sudo` that does something in `.config` it might have changed the permission of that folder.

@pmeenan perhaps you could look at what else is in `~/.config` to give a clue?

**Comment by brendankenny** [comment]
Also we've used `update-notifier` since March, which uses configstore (`configstore/update-notifier-lighthouse.json` on my machine), so I'm surprised we haven't run into this before

**Comment by brendankenny** [comment]
> Also we've used update-notifier since March, which uses configstore, so I'm surprised we haven't run into this before

update-notifier try/catches the configstore call: https://github.com/yeoman/update-notifier/blob/38d5679f90b2490507071830362b5cc212971fa4/index.js#L45-L64

so that's probably why it hasn't been an issue so far. #3878 does the same for Lighthouse.

**Comment by pmeenan** [comment]
Could also be something messed up in my images that caused the configstore to get locked down to root.  I have a workaround in place so if it isn't an issue for anyone else  I am happy to close the issue.
