### ISSUE TITLE
Lighthouse prompts for reliability feedback - Lighthouse 2.6.0

### ISSUE THREAD

**Issue by pmeenan** [GoogleChrome/lighthouse#3874]
```
lighthouse --disable-network-throttling --disable-cpu-throttling --max-wait-for-load 80000 --port 9223 --output html --output json --output-path "/home/pmeenan/src/wptagent/work/VM9-01/171121_YP_b7a62bc27d0347176dad6b2285034704.1.0/lighthouse.json" --save-assets "http://www.webpagetest.org/?bare=1"

We're constantly trying to improve Lighthouse and its reliability.
  May we anonymously report runtime exceptions to improve the tool over time?
  Learn more: https://github.com/GoogleChrome/lighthouse/blob/master/docs/error-reporting.md (y/N)
```

It does look like it skips over the prompt after a delay and may only happen the first time.  Would be nice if there was a --headless flag or something to let Lighthouse know that there is no user at the keyboard to answer prompts and skip over them entirely.

**Comment by patrickhulce** [comment]
Thanks for the feedback, sorry about the lack of heads up again! 😞 

We tried to document the [various ways to opt-out](https://github.com/GoogleChrome/lighthouse/blob/master/docs/error-reporting.md) in that link, but for fear of scaring/confusing people with 'opt-out' it's mostly framed around opting-in which makes it a little less clear what you need to do in your situation.

We have some reasonable defaults at skipping for non-interactive sessions
https://github.com/GoogleChrome/lighthouse/blob/2182513f2c00ccb90bc762989c2344456352fa9b/lighthouse-cli/sentry-prompt.js#L24-L27

LH can be run with the `--[no-]enable-error-reporting` flag to skip the prompt entirely. We were hoping in WPT and HTTPArchive we might be able to turn it on for tests not marked as private, and potentially add support for tagging the run as coming from WPT.

**Comment by ebidel** [comment]
related: https://github.com/GoogleChrome/lighthouse/issues/3854

**Comment by brendankenny** [comment]
does #3876 seem sufficient to address this?

**Comment by pmeenan** [comment]
I'm good with turning it on all the time if it helps debug issues.  I just [flipped it on](https://github.com/WPO-Foundation/wptagent/commit/6424c7e1aca14997a81d32234258b3d4c4c38f49) and the agents will pick it up within the next hour.

**Comment by patrickhulce** [comment]
Awesome thanks @pmeenan!

**Comment by CIB** [comment]
Would be nice if it printed the name of the option right along with the prompt. I was looking for "telemetry", as that's what the option is called in nuxt.

**Comment by connorjclark** [comment]
Good idea @CIB!
