### ISSUE TITLE
Create more useful examples/guides

### ISSUE THREAD

**Issue by wardpeet** [GoogleChrome/lighthouse#3877]
I kinda forget that we had https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes  in our repository. Issue #3837 let me back to this folder. Perhaps we should use this issue to create a list of examples we want to add?

I can start with a few:
- Setting cookies/basic auth login
- Global example using puppeteer

**Comment by brendankenny** [comment]
we should definitely do this, but let's track individually (e.g. #8728, #6392, etc) and close this issue :)
