### ISSUE TITLE
check and penalize user-agent string restrictions

### ISSUE THREAD

**Issue by wanderview** [GoogleChrome/lighthouse#389]
It seems there is a some trend towards using UA strings checks in PWAs.  This is an anti-pattern that should be discouraged.  Progressive sites should really do feature detection and graceful fallback to normal site behavior.

It would be nice if lighthouse check for blatant UA checks that redirect to other sites, produce blocking interstitials, etc.

**Comment by zhaoz** [comment]
Unfortunately some things cannot be easily feature detected for without a lot of work, e.g. touch events.

Additionally, device performance classification is hard to do client side without penalizing the application in some way. You may want to serve a lower fidelity UI to the user based on the constraints of his/her device.

**Comment by paullewis** [comment]
I think we do want to check for interstitials for sure, they're bad UX. I am less sold on the redirection, here. While I do think they're less than ideal compared to a RWD site, there might be reasons why this is the case. But let me switch it around, what's the behaviour we would want to test for and advise against?

**Comment by wanderview** [comment]
A well behaved site does not redirect the client to the play store if they don't recognize the user-agent string.  A "progressive" site should be able to run in a browser even if the UA does not offer a prompt to add-to-homescreen.

**Comment by samccone** [comment]
ok so what if we did the following...

1. request the page with several U/A strings (safari / chrome / (others))
2. save the html for each one
3. compare them after the fact
4. if they are different... say something?

This would be a fun one to experiment with.. Obviously these steps are not bullet proof however this check would catch "blatant" redirections 


thoughts?

**Comment by boopathi** [comment]
> if they are different

I guess there is no right way to do this. If it was a content diff, it'll be turn out to be incorrect where the pages insert content based on UA - say meta tags, polyfills, different stylesheet, different classes, or styles, etc... Even if we are looking at % of diff, how much might be tough to answer. 

Visually similar - capture screenshot for different UA and compare the diff between these screenshots - this again might not be 100% correct.

**Comment by samccone** [comment]
yep I agree there is no sure fire way to do this, but an initial pass would at least give us some idea and a place for us to iterate from

**Comment by wardpeet** [comment]
What if you have a server redirect?

**Comment by paulirish** [comment]
Hello from 3 years later.  🚀 
This seems extremely challenging to do reliably and in a general way. We'd probably have a lot of false positives. 

Open to reconsidering if someone has a robust detection proposal. 
Cheers.
