### ISSUE TITLE
UI issue on report 

### ISSUE THREAD

**Issue by praveenvijayan** [GoogleChrome/lighthouse#390]
UI breaking with long content. 

<img width="1348" alt="screen shot 2016-05-28 at 11 01 02 pm" src="https://cloud.githubusercontent.com/assets/176655/15629356/1a418bde-2528-11e6-8fff-97780cd6fe8b.png">
<img width="1401" alt="screen shot 2016-05-28 at 10 51 43 pm" src="https://cloud.githubusercontent.com/assets/176655/15629357/1a41fca4-2528-11e6-8b95-605956e2cf9b.png">

**Comment by youngdelaney** [comment]
why wasn't anyone comment on your stuatus

**Comment by samccone** [comment]
This has been fixed. :)
