### ISSUE TITLE
Performance results are way different from the ones expected

### ISSUE THREAD

**Issue by Vermat99** [GoogleChrome/lighthouse#3908]
Hi, it's more a request of help than a real issue.
When i run the audit of my web app i always have the first meaningful paint time > 20sec, but that shouldn't be true. Looking at the screenshots of the Performance tool (same page, test repeated multiple times), i estimante that the first meaningful paint should be around 1100ms, which is way more reasonable than the 20 seconds given by lighthouse. 
I can see that while the test is performed the web page actually keeps >20sec to load, it isn't just the final score.
Am i doing something wrong? Are you applying some default throttles to the page?

I'm on Chrome Dev 63.0.3239.59

**Comment by benschwarz** [comment]
Hey @Vermat99, Lighthouse sets the viewport to be that of a nexus 5, then slows the network to a '3g ish' connection, as well as the CPU. 

If you'd like to try lighthouse without these settings there are some command line flags to turn off connection/device emulation 👍

**Comment by Vermat99** [comment]
@benschwarz Thank you! But an iPhone6 under 3g connection still keeps under 5 seconds to load, 20 seconds are really a lot of time IMO. It's just a vulcanized polymer web app... 

Anyway, if you think that it's still possible to have these results with the throttling you apply, you can close the issue, thank you again.

**Comment by patrickhulce** [comment]
@Vermat99 definitely still possible to experience those load times with some heavy JS bundles and our throttling settings. If you have a trace that you've recorded with Lighthouse CLI (using `lighthouse --save-assets https://your-url-here`), we can take another look to see if something squirrely is going on though.
