### ISSUE TITLE
Audit "Aw snap" error

### ISSUE THREAD

**Issue by nominalaeon** [GoogleChrome/lighthouse#3921]
Apologies, this should be a Stackoverflow question, but I didn't see many "Chrome Lighthouse" tags over there.

The short and sweet is: Lighthouse was working great for me and now it's not.

The JSON from the last successful audit says:

    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36",
    "lighthouseVersion": "2.3.0",
    "generatedTime": "2017-10-23T20:43:57.953Z"

When Chrome 62 came out (sorry, not sure if the Lighthouse version changed then too or not), my audits started just dropping me to a "Aw snap" view. The Audit locks my navigation so I can't check the console so I have no way of getting feedback if the error is something I introduced.

![aw-snap](https://user-images.githubusercontent.com/1110469/33271128-fb0d7556-d34b-11e7-8a60-f20e62ae94f7.png)

After that view happens, the audit just sits there and spins. Basically forever if I let it.

![spinning](https://user-images.githubusercontent.com/1110469/33271429-d49d64f2-d34c-11e7-8b10-22052e716780.png)

I'm auditing a localhost instance from a Node server from browser-sync. The error occurs the same way on our dev server which is serving https from IIS.

I'm really sorry, this issue breaks a lot of the guidelines but I am totally out of ideas here. I'm not looking for a rock solid answer, just some help with just usual suspect kind of starting points. Have you seen this happen before? Are there common runtime things that cause it? At this point I'd be happy to narrow this down to either JS or CSS ...or image assets or server config or etc.

Thank you so much!

**Comment by patrickhulce** [comment]
hey @nominalaeon thanks for reporting!

By any chance, could you give Chrome Canary a try to see if it works there? There was an unfortunate bug that leaked into Chrome 62 (fixed in 63+) that causes a very small percentage of pages to crash if they use bad CSS background images while tracing (which Lighthouse does).

**Comment by nominalaeon** [comment]
Winner winner, chicken dinner!

<img width="749" alt="screen shot 2017-11-27 at 11 47 10 am" src="https://user-images.githubusercontent.com/1110469/33280769-cc6b76ae-d368-11e7-9a12-03be949be1bd.png">

According to my Perf score, I'd say the background-image diagnosis is on point.

Thank you so so much for the assist!

**Comment by patrickhulce** [comment]
Awesome glad it's back on track! Sorry you ran into this! 

I'm going to go ahead and close for now, but feel free to reopen if there's something we missed here 👍
