### ISSUE TITLE
window.performance is empty

### ISSUE THREAD

**Issue by vcvetkovs** [GoogleChrome/lighthouse#3931]
When I launch evaluateAsync('window.performance') in Gatherer afterPass it returns me empty object. What I am doing wrong? Or how I can access pure timing information?

**Comment by paulirish** [comment]
Sometimes objects don't serialize well... how about....

```js
evaluateAsync('JSON.stringify(window.performance.toJSON())')
```

**Comment by vcvetkovs** [comment]
@paulirish it works, thanks!
