### ISSUE TITLE
Support --ignore-default-chrome-flags in CLI

### ISSUE THREAD

**Issue by ghost** [GoogleChrome/lighthouse#3946]
The command I tried is:
lighthouse <_URL_> --perf --output json --output-path=./report.json --save-assets --disable-cpu-throttling --disable-network-throttling --disable-device-emulation --verbose --chrome-flags="--load-extension=<PATH_TO_EXTENSION>"

This does not enable the extension as I can see in the logs that extensions are disabled by default:
ChromeLauncher:verbose "/usr/bin/google-chrome-stable" --disable-translate --disable-extensions ...

**Comment by patrickhulce** [comment]
Thanks for filing @sleepyCoder666! You're correct, currently there's no way to override the default flags from the CLI as the `--chrome-flags` property simple appends.

As a workaround for now, you can launch chrome yourself with the desired flags and pass in the `--port=X` parameter to Lighthouse.

**Comment by sleepyCoder666** [comment]
Thanks for the quick reply @patrickhulce. I want to run automated tests which load Websites using chrome and record various metrics (Lighthouse).  --port=X, as I understand, specifies the debugging port. Did you mean that I can keep Lighthouse running and record metrics via the debugging port as I continue to load multiple Websites using chrome? Is there a way to do that?

**Comment by patrickhulce** [comment]
Not 100% sure I understand what you're asking, but you can definitely leave Chrome open between Lighthouse runs if you're managing Chrome yourself.

If you start with the [Using Lighthouse programmatically](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically) example, you'd want to modify that function to only launch Chrome once, and then run your multiple Lighthouse runs before calling `.kill`.

**Comment by paulirish** [comment]
https://github.com/GoogleChrome/chrome-launcher/pull/70 has this. when it lands we can do this.
