### ISSUE TITLE
Node security advisory for ws@1.1.2

### ISSUE THREAD

**Issue by crimeminister** [GoogleChrome/lighthouse#3948]
Running `nsp check` on a project that includes `lighthouse@2.6.0` as a dependency results in [this security advisory](https://nodesecurity.io/advisories/550) against `ws@1.1.2`. The recommended remediation is to "Upgrade to version 3.3.1 or greater".

**Comment by patrickhulce** [comment]
Thanks so much for reporting @crimeminister!

**Comment by paulirish** [comment]
@crimeminister do you want to give us a PR for this upgrade? a bump to package.json and yarn.lock should hopefully be all that's required.

**Comment by crimeminister** [comment]
@paulirish Sure thing, PR incoming.
