### ISSUE TITLE
Lighthouse (programatically) seems to be giving me JSON output even when i set output: 'html'

### ISSUE THREAD

**Issue by Jayflux** [GoogleChrome/lighthouse#3958]
**Lighthouse Version**
2.5.0

**Node Version**
v8.9.1

This is my gulpfile
https://gist.github.com/Jayflux/967745795f7bc54ed5bccf82e0814783

on line 25 i run launchChromeAndRunLighthouse with the flag set to {logLevel: 'info', output: type}, in this case the type is 'html'.
For some reason i still get the JSON output coming out?

**Comment by patrickhulce** [comment]
Programmatic consumption only gives you the JSON, if you want the HTML report you use the ReporterGenerator class like the CLI does to give you the HTML as a string.

https://github.com/GoogleChrome/lighthouse/blob/3bdb56e80a17c2a02f73e678b906232f9a7eef02/lighthouse-cli/printer.js#L9
https://github.com/GoogleChrome/lighthouse/blob/3bdb56e80a17c2a02f73e678b906232f9a7eef02/lighthouse-cli/printer.js#L46

**Comment by Jayflux** [comment]
@patrickhulce do i have access to that class from outside the project?

**Comment by patrickhulce** [comment]
yes, you can do `require('lighthouse/lighthouse-core/report/v2/report-generator')`

In practice this file has never moved or changed APIs, but keep in mind this isn't the flow we're attempting to support, so we don't 100% guarantee its stability between versions. If we eventually refactor and its path changes you may need to update :)

**Comment by Jayflux** [comment]
@patrickhulce tried it, works wonderful, Thanks!

**Comment by patrickhulce** [comment]
great! will go ahead and close this then but feel free to chime back in if you feel there's more
