### ISSUE TITLE
Heroku lighthouse_chromium_path

### ISSUE THREAD

**Issue by CallaRudolph** [GoogleChrome/lighthouse#3961]
I've got an app set up to crawl a url and then run each url through Lighthouse. It works locally as expected, but when I deploy to Heroku after a Travis build and try to run Lighthouse on one of the crawled urls, I get this error in the Heroku build log:

`(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: The environment variable LIGHTHOUSE_CHROMIUM_PATH must be set to executable of a build of Chromium version 54.0 or later`

I've tried to find solutions from previous closed issues, but haven't found anything that works.

**Comment by patrickhulce** [comment]
I'm not sure heroku has a Chrome installation available to you by default. Have you looked into a [Chrome build pack](https://github.com/heroku/heroku-buildpack-xvfb-google-chrome)?

**Comment by CallaRudolph** [comment]
Thanks, running `heroku buildpacks:add --index 2 https://github.com/heroku/heroku-buildpack-google-chrome.git` worked
