### ISSUE TITLE
feature: download the optimized assets from opportunities

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#3966]
from mWeb black belt session: it'd be nice to be able to download the optimized assets like PSI does

**Comment by paulirish** [comment]
Would be totally awesome, but this is not something we're positioned to do in the next 18 months.

**Comment by asteriskmmt** [comment]
Not sure why they removed this functionality as it was a "Game changer" feature for me and one of the reasons I used this vs other tools. Please prioritize adding this feature back. 
Two other threads for this issue on Stack
https://stackoverflow.com/questions/53777917/download-optimized-images-from-pagespeed-insights
https://stackoverflow.com/questions/53854555/how-to-download-optimized-image-css-javascript-on-google-page-speed-insight
