### ISSUE TITLE
Making Lighthouse Audits comparable.

### ISSUE THREAD

**Issue by AGrunewald** [GoogleChrome/lighthouse#3968]
I am looking to use Lighthouse to evaluate how a website performs, the one area I am struggling with is understanding how Lighthouse is measuring the Performance of a Site. 

For example, the screenshot on https://developers.google.com/web/tools/lighthouse/ shows that https://shop.polymer-project.org/ has a performance score of 88. On my computer Windows 7 Enterprise, Chrome 62, Intel Core i7-6600U with 16GB ram I get a performance score of 53, So Different computers result in different performance scores. 
One of the benefits of the old PageSpeed Insights was that the audit was done centrally. 

How can we make Lighthouse results universal, so that every computer returns the same results?
https://googlechrome.github.io/lighthouse/viewer/?gist=28e31a512f1a2a5c3db41b55aeea3150#performance

**Comment by patrickhulce** [comment]
Thanks for reporting @AGrunewald! You shouldn't be seeing a 53 for polymer shop. Would you be able to upload the trace of the page load Lighthouse observed so we can see what's going on? You can do this with the CLI using the `--save-assets` flag.

**Comment by AGrunewald** [comment]
Hello, @patrickhulce I used the Chrome Extension. Any way I can get the same data from the Extension?

**Comment by AGrunewald** [comment]
Ding some more digging and trying the same test in an incognito window I have some more details.
It looks like 2 Extensions I have installed somehow affect the performance score significantly.

- Evernote Web Clipper https://chrome.google.com/webstore/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc
- Grammarly - https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen

Each Extension alone takes the score from 86 down to about 70; both together bring the score down to 55. So People have to know that they either have to turn off all their extensions, try incognito without extensions or maybe there is a way of running the Audit without extensions?

**Comment by patrickhulce** [comment]
Ah, yes anything interfering with page load can have a significant impact. We try to call this out in the [docs](https://github.com/GoogleChrome/lighthouse/blob/af0337004678bcc690ec31fd1fca2609568f967e/docs/scoring.md#what-performance-metrics-does-lighthouse-measure) and there's an option in the extension to automatically disable all other installed extensions (but this is a rather invasive measure, so we don't do it by default).

The CLI is currently the best bet for setting up a clean Chrome profile free of extensions and personal settings interfering. Either way though, yes, you'll just need to be aware of any software on your machine that will interfere with web browsing.

**Comment by AGrunewald** [comment]
That's good feedback thank you. This will make our testing more reliable

**Comment by patrickhulce** [comment]
Great! I'm going to go ahead and mark this as closed, but please feel free to chime in here if you find there's something we should be adding to the docs! :)

**Comment by AGrunewald** [comment]
I think adding this information to https://developers.google.com/web/tools/lighthouse/ would be fantastic. I wasn't even aware of the other documentation location. Maybe even in the step-by-step instructions suggest that people run it in incognito without extensions.
Another option could be having Lighthouse show a warning if it detects that there were extensions that might have impacted the performance test. 
To me it feels just updating that front page might be the lowest effort solution. Also linking to WebPagetest.org https://www.webpagetest.org/easy.php would be awesome I didn't know I could run a lighthouse test through them until today. It's almost like the old page speed insights.
