### ISSUE TITLE
lighthouse-logger is not node 4 compatible 

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#3981]
Since adding compilation to logger seems like a lot of overhead, I propose rewriting the code to not use es2015 syntax.

This will enable chrome-launcher to become node 4 compat.

See https://github.com/GoogleChrome/chrome-launcher/issues/8 for more info and rational why we should support node 4.

Thanks so much for your time.

**Comment by patrickhulce** [comment]
While I agree and too have pushed for supporting all the current LTS versions, I believe the @paulirish and @brendankenny established a policy for dropping support for an LTS as soon as the next LTS hits "Active".

Not a huge deal for just logger I suppose but seems inconsistent within the same repo to target for all of LH. At this point going back to node 4 across the code base seems awful when node 4 leaves maintenance in ~4 months?

**Comment by samccone** [comment]
I agree that adding 4 support for the entire project seems unneeded. Given the small amount of work required for updating logger (which I will gladly do) I think it is worth it.

Thanks for taking the time to respond.

**Comment by paulirish** [comment]
we closed the other one so we close this one.
🏡
