### ISSUE TITLE
Performance tests vary wildly 

### ISSUE THREAD

**Issue by D3MZ** [GoogleChrome/lighthouse#3983]
Hey - Just wanted to highlight this, and probably mark it as an important gotcha (bug?) for people, because it seems that performance scores are affected by the testing computer's resources (CPU, internet connection, etc), rather than just the server it is testing. 

You can quickly recreate this by testing sites in sequential order and compare the results by testing the same list of sites in parallel. 

[Google.ca tested at 2017-12-03_21-16-27](https://www.dropbox.com/s/zajt7eqxgz4v2gx/www.google.ca_2017-12-03_21-16-27.report.html?dl=0) gave a performance score of 74
[Google.ca tested 2 minutes later](https://www.dropbox.com/s/kwquc3jrnig4xo1/www.google.ca_2017-12-03_21-18-01.report.html?dl=0) gave a performance score of 86.
[Google.ca tested 20 minutes later](https://www.dropbox.com/s/vk6v6o7hltalws0/www.google.ca_2017-12-03_21-38-49.report.html?dl=0) gave a performance score of 92.

That's a pretty gnarly variance, and hampers automatic testing. My hack solution is to compare scores against google, so it'll be a relativistic answer rather than an absolute one.  All ears for any alternatives or how to address this. 

Worth noting that [there are a few issues on this subject but have been closed due to a lack of follow up from the OP](https://www.google.ca/search?q=lighthouse+perforamcne+inconsistent+github&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&dcr=0&ei=TLIkWsaOJ8yfXpGcppgE)

**Comment by vinamratasingal** [comment]
Hey D3MZ, thanks for following up. We have definitely seen this issue on our end and have documented this within our scoring docs [here](https://github.com/GoogleChrome/lighthouse/blob/master/docs/scoring.md). 

We also have more bugs assigned on our team to work on this- see [3600](https://github.com/GoogleChrome/lighthouse/issues/3600) and [2674](https://github.com/GoogleChrome/lighthouse/issues/2674) and [1449] (https://github.com/GoogleChrome/lighthouse/issues/1449). We also have an internal project in place to deal with these instability concerns, and will share on Github once we have the scoping complete!

Let me know if there are any other concerns on your end. Happy to put together a master bug if that's useful to track all these different variability projects.

**Comment by D3MZ** [comment]
@vinamratasingal thanks for the thorough and thoughtful reply! Those are excellent docs.

I've used to the CLI programmatically and found this issue (which is slightly different than the Anti-virus piece), though it seems like [network emulation isn't supported when going headless](https://bugs.chromium.org/p/chromium/issues/detail?id=728451). I'll perform a thorough re-test and loop back if I find anything.

**Comment by vinamratasingal** [comment]
Amazing. Closing this out for now. Feel free to reopen if any issues!
