### ISSUE TITLE
Use performance.timing API in Gatherer

### ISSUE THREAD

**Issue by Vwings** [GoogleChrome/lighthouse#3988]
I want to use **performance.timing** API in a custom Gatherer, but got an empty object.

```
afterPass(options) {
    const driver = options.driver;
    return driver.evaluateAsync('performance.timing').then(timing = >{
        console.log(JSON.stringify(timing)); //get {}
        return timing;
    });
}
```

**Comment by patrickhulce** [comment]
Hey @Vwings thanks for filing, seems to be a popular problem :) https://github.com/GoogleChrome/lighthouse/issues/3931

solution is to `return driver.evaluateAsync('JSON.stringify(window.performance.toJSON())')`

going to go ahead and close as a duplicate but let us know if that solution doesn't work out for you!
