### ISSUE TITLE
Lighthouse CLI hangs on certain websites 

### ISSUE THREAD

**Issue by D3MZ** [GoogleChrome/lighthouse#3993]
```
~ $ lighthouse http://nba.com
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +0ms
  ChromeLauncher Waiting for browser..... +609ms
  ChromeLauncher Waiting for browser.....✓ +2ms
  Lighthouse:warn The URL provided should be on HTTPS +436ms
  Lighthouse:warn Performance stats will be skewed redirecting from HTTP to HTTPS. +1ms
  status Initializing… +420ms
  status Loading page & waiting for onload URL, Viewport, ViewportDimensions, ThemeColor, Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage, Accessibility, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, WebSQL, MetaDescription, CrawlableLinks, MetaRobots +355ms
  Driver:warn Timed out waiting for page load. Moving on... +45s
  statusEnd Loading page & waiting for onload +2ms
  status Retrieving trace +1ms
  status Retrieving devtoolsLog and network records +9s

```
Hangs here:
![Imgur](https://i.imgur.com/PsXwJ76.gif)

**Comment by vinamratasingal** [comment]
Hi! We took a look at this and are not able to reproduce it- can you tell us what steps you took to get it to hang? Did you retry and did it work then?

**Comment by anagio** [comment]
If you're running lighthouse in a container you may need to increase `shm` when running the container. The NBA page is pretty heavy and crashed when I ran puppeteer ultimately chrome needed more memory. Maybe unrelated to your issue.

**Comment by ray-kim-12** [comment]
@anagio I passed the `--disable-dev-shm-usage` to puppeteer in hopes of trying to fix the `  Driver:warn Timed out waiting for page load. Moving on... +45s` message but I still get it. I'm guessing you're running on Docker. @patrickhulce, is there an equivalent for Jenkins ?

**Comment by ray-kim-12** [comment]
I'mm running locally on my MacOS 10.13 and still getting the `  Driver:warn Timed out waiting for page load. Moving on... +45s` after setting `kern.sysv.shmmax: 1610612736`

**Comment by patrickhulce** [comment]
@ray-kim-12 `Driver:warn Timed out waiting for page load. Moving on... +45s` is expected operation for slow loading sites. This bug is about LH hanging and never finishing to return a report. Is that what you're seeing? If so, please file a new bug with the URL and repro steps.

**Comment by ray-kim-12** [comment]
This is on localhost and a production build of the project.
The LH reports ARE generated but every time I run it, I have to wait 45 (additional) seconds  for each LH report. 
However, I do NOT see this when running this on Jenkins (on RHLS 7.4).
I would simply like to not have to wait 45 additional seconds 
```
  status Initializing… +8s
  status Loading page & waiting for onload Scripts, CSSUsage, Viewport, ViewportDimensions, ThemeColor, Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage, Accessibility, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, WebSQL, MetaDescription, FontSize, CrawlableLinks, MetaRobots, Hreflang, EmbeddedContent, Canonical, RobotsTxt, Fonts +348ms
  **Driver:warn Timed out waiting for page load. Moving on... +45s**
  statusEnd Loading page & waiting for onload +0ms
  ...
```

**Comment by patrickhulce** [comment]
You can use the `--max-wait-for-load=10000` to only wait 10s for example
