### ISSUE TITLE
Headless yielding much favoured results

### ISSUE THREAD

**Issue by lightheaded** [GoogleChrome/lighthouse#3997]
I want to run lighthouse benchmarks on my CI server, which implies headless mode of operation. I only care about Perceptual Speed Index (PSI) at the moment, so I want a single metric to be consistently measured. However once I set everything up, my numbers in CI come up all nice and low. For example

```bash
$ lighthouse --chrome-flags="--headless" --quiet --perf --output=json https://news.ycombinator.com/ | grep perceptualSpeedIndex | grep -o '[0-9]\+' | head -n1
1133
$ lighthouse --chrome-flags="--headless" --quiet --perf --output=json https://news.ycombinator.com/ | grep perceptualSpeedIndex | grep -o '[0-9]\+' | head -n1
1092
$ lighthouse --chrome-flags="--headless" --quiet --perf --output=json https://news.ycombinator.com/ | grep perceptualSpeedIndex | grep -o '[0-9]\+' | head -n1
706
```

Which is awesome. However when I go to someone and claim that the Lighthouse performance score is around 1k for https://news.ycombinator.com/, I get slapped in the face, because when you try that in the browser (i.e. not headless), the numbers will be much larger. 

```bash
$ lighthouse --quiet --perf --output=json https://news.ycombinator.com/ | grep perceptualSpeedIndex | grep -o '[0-9]\+' | head -n1
1745
$ lighthouse --quiet --perf --output=json https://news.ycombinator.com/ | grep perceptualSpeedIndex | grep -o '[0-9]\+' | head -n1
1702
$ lighthouse --quiet --perf --output=json https://news.ycombinator.com/ | grep perceptualSpeedIndex | grep -o '[0-9]\+' | head -n1
1721
```

With my particular site (which is not https://news.ycombinator.com/) the difference is around 4x. Lighthouse with headless chrome is reporting ~2k PSI and when run from Chrome developer tools or  with the latter command, which uses a headed browser, the results are vastly different. 

If running lighthouse in Chrome and getting the PSI of 1702ms, I can relate to that number – it shows me how quickly the contents of a page are visibly populated. What do the results when running in headless mode show? I understand that headless browsers "render" stuff differently, but that's a technical explanation. But from the user's perspective as I see it, measuring PSI with a headless browser is meaningless, if only for monitoring trends. 

Could you either confirm that you can't measure **real** perceptual speed index in headless mode or suggest how is it possible?

**Comment by patrickhulce** [comment]
Thanks for filing @lightheaded! Sorry to hear about the confusion! 🤕 👏  are never fun

Headless does not currently support network and CPU throttling which is why you're seeing such better numbers there. For server/CI environments we recommend using XVFB to fake a display and use regular, headful Chrome. You can read more about this approach in [the docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/headless-chrome.md#cli-xvfb).

#2675 tracks the work to add a helpful hint to the report, warning you about this since the docs aren't always easy to find :)

**Comment by lightheaded** [comment]
Great stuff! Thanks for the reply. Wanted to confirm that this is the case and I'm glad that #2675 is there. Will close :)
