### ISSUE TITLE
Lighthouse CLI on Circle CI scores higher than expected

### ISSUE THREAD

**Issue by ataylorme** [GoogleChrome/lighthouse#4003]
Using the Chome extension, in incognito mode with other extensions disabled, I am getting scores in the mid-80's.

I added Lighthouse to my continuous integration process tests running on the live website and a new environment created for pull requests. The idea being if the overall performance score is more than 5 points worse on the pull request the Circle CI build will fail, disallowing a merge on GitHub.

To test this is intentionally created a pull request that should receive a lower score by adding a large image to the page and disable Varnish full page cache so the response is served directly from WordPress.

As expected, the Lighthouse report run from my local machine using the Chrome extension returns a performance score of `86` with a first paint of`3,120ms`.

<img width="1392" alt="screen shot 2017-12-06 at 3 35 40 pm" src="https://user-images.githubusercontent.com/2133004/33691050-3a068eae-da9b-11e7-944c-aa4f7439ef4c.png">

Unexpectedly, [the Lighthouse report run on Circle CI using the CLI version](https://1060-51163820-gh.circle-artifacts.com/0/artifacts/lighthouse_results/pr-86/lighthouse.report.html) returns a performance score of `100` with a first paint of`770ms`.

<img width="1392" alt="screen shot 2017-12-06 at 3 43 18 pm" src="https://user-images.githubusercontent.com/2133004/33691252-3c181464-da9c-11e7-9d03-412561c79972.png">

The Circle CI log for the job running the Lighthouse test can be found [here](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/1060) and the main repository code is open source and available [here](https://github.com/ataylorme/Advanced-WordPress-on-Pantheon/).

I expected something running on a CI server to be slightly faster but the large discrepancy (`2,350ms`) in first paint time and the resulting perfect performance score, for a URL that has known issues, is causing my desired use case of checking the score as part of a CI process to be ineffective.

Any suggestions are most welcome.

**Comment by patrickhulce** [comment]
Thanks for reporting @ataylorme great to see you're adding Lighthouse to your CI! 🎉  👏 

It looks like your code is running Lighthouse on [headless](https://github.com/ataylorme/Advanced-WordPress-on-Pantheon/blob/ea82914b29adf40f3d3343463b321607bc6f9899/.circleci/lighthouse-performance-test.sh#L103) where throttling is not available. For this reason, we actually recommend running regular headful Chrome with XVFB in server environments ([see the docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/headless-chrome.md#cli-xvfb)).

Let us know if you run into any issues getting XVFB running or you find something in those docs to be unclear!

related #3997 #2008 #2675

**Comment by ataylorme** [comment]
Thanks, @patrickhulce for the quick reply! The scores make more sense with no throttling in headless mode. Is there a maintained Docker image with Chrome, Lighthouse and XVFB I can use?

**Comment by ebidel** [comment]
You can use https://github.com/ebidel/lighthouse-ci. Working on bringing this work in officially to this repo: https://github.com/GoogleChrome/lighthouse/issues/3715

**Comment by ataylorme** [comment]
Great, thanks @ebidel. I've subscribed to that thread. I was able to use https://github.com/ebidel/lighthouse-ci in the meantime. Thank you for the work there! Really comprehensive.

Once a Docker image comes out I'll switch over to running Lighthouse locally in Circle CI.
