### ISSUE TITLE
Add an "Export to HAR" option for dumping the network activity

### ISSUE THREAD

**Issue by chenyaoyi110** [GoogleChrome/lighthouse#4005]
I'm so sorry.can you help me?
i wanna get the network as HttpArchive File,what should i do?

**Comment by vinamratasingal** [comment]
Hi, I'm not sure I understand your question. Can you provide more details as to what you're confused about?

**Comment by chenyaoyi110** [comment]
hi @vinamratasingal , thx your reply;
we can use chrome(PC) DevTool's Network to see what are loaded in my pages.
as we can save those as a HTTP Archive(HAR) file too;
but i wanna use lighthouse to test my page on my android device meanwhile save the page network as HAR file like what can i do at Chrome DevTool;

**Comment by vinamratasingal** [comment]
Hi- Just to confirm, is your question that you are trying to use Lighthouse to test a website on an Android phone, and then save the report into a HAR?

**Comment by chenyaoyi110** [comment]
@vinamratasingal 
sorry,I'm not sure "the report" whether is what I need. 
I hope the HAR file is seems like that I got in Chrome Network;

**Comment by patrickhulce** [comment]
Ah, @chenyaoyi110 you want to be able to get a HAR file from the Lighthouse run, correct?

Right now it's a little tricky to do this but all the information you need to create a HAR file yourself is available to you in the `devtoolsLog` artifact of Lighthouse.

If you're brave and want to try to do this yourself, you can run Lighthouse from node or the CLI, use the devtools log artifact, and take a look at how [devtools creates a HAR file](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/network/HARWriter.js?type=cs&sq=package:chromium) from the network activity or [use a library](https://github.com/cyrus-and/chrome-har-capturer/tree/from-log#fromlogurl-log-options).

**Comment by paulirish** [comment]
FWIW here's an audit that builds the HAR using some chrome-har-capturer internals (instead of the public `fromLogs` method): https://gist.github.com/benschwarz/b1351f824f1ebd71cc5a2774e0095726

**Comment by chenyaoyi110** [comment]
@paulirish hi,paul.thanks for your help, and i am in trouble now.
I add har.js into the project path : `/lighthouse/docs/recipes/custom-audit/har.js`
and edit the **custom-config.js**
<pre>
...

  // 3. Add custom audit to the list of audits 'lighthouse:default' will run.
  audits: [
    //'searchable-audit',
    'har'
  ],

...
</pre>

and then I execute this command
<pre>
lighthouse --port=9222 --config-path=custom-config.js --disable-device-emulation --disable-cpu-throttling http://xxx.xxx.com
</pre>


but the lighthouse logger print 
<pre>
...
Fri, 08 Dec 2017 06:46:39 GMT status Evaluating: Produces a HAR
Fri, 08 Dec 2017 06:46:39 GMT har:warn Caught exception: Cannot read property 'entries' of undefined
...
</pre>

in your [har.js](https://gist.github.com/benschwarz/b1351f824f1ebd71cc5a2774e0095726)  - `createHar` method 
<pre>
logs.forEach(message => {
      try {
        page.processMessage(message)
      } catch (e) { }
    })
</pre>
I'm not sure if page has `processMessage` function

can you give me some information for this problem?thank you very much ^v^

**Comment by paulirish** [comment]
Alternatively, you can use `--save-assets` to get the devtoolslog and then build the HAR from that. That's something we could document somewhere.

**Comment by paulirish** [comment]
Not exploring any further. 

Current best approach would be to use --save-assets and feed the devtoolsLog into https://github.com/sitespeedio/chrome-har.

**Comment by geeky-biz** [comment]
Hi @paulirish how to get the devtoolslog when invoking lighthouse from node (programmatically)? I tried saveAssets: true but that doesn't seem to do the trick (I want to replicate exactly what --save-assets does via lighthouse cli)

**Comment by patrickhulce** [comment]
@geeky-biz the artifacts are returned to you in an object when invoking programmatically, so you'll have to write them to disk yourself if you don't plan to use them immediately

See https://github.com/GoogleChrome/lighthouse/tree/master/docs#differences-from-cli-flags
