### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by jeanetteranae** [GoogleChrome/lighthouse#4011]
**Initial URL**: https://prod02.kaxsdc.com/collect/sdk?m=100100

**Comment by jeanetteranae** [comment]
video doesnt load

**Comment by vinamratasingal** [comment]
Hi! I am going on the website but it seems like the website itself isn't working? Can you tell us the steps you took and whether retrying running the website fixed the issue?

**Comment by patrickhulce** [comment]
Thanks for filing @jeanetteranae this seems to be a case discussed in #2784, so feel free to chime in there if you still have questions.
