### ISSUE TITLE
Report: Highlight when affected resources are from 3P or extensions

### ISSUE THREAD

**Issue by fchristant** [GoogleChrome/lighthouse#4013]
Not a huge deal, but when doing a 'best practises' audit, I was reportedly violating the passive event listener test. Details listed content.js, 3 instances of them, each coming from an extension and not the web page itself. 

Since these content.js files don't even show up in the network panel, it's a bit misleading imho. Just as a check, the same page audited in incognito mode clears the false positives.

I'm thinking web extensions should be excluded from the report? Authors have no way to pass the check other than uninstalling the web extension. Or perhaps it is just misbehavior of specific extensions, I'm not sure.

**Comment by patrickhulce** [comment]
Thanks for the feedback @fchristant! This is a great point, and we plan to show a warning in the report if we observed extension activity suggesting the user run the report without extensions (in incognito mode, fresh profile, with CLI instead, etc). Some have actually found value in auditing how their extensions impact the page, so I'm not sure we'd want to completely ignore extension activity.

**Comment by paulirish** [comment]
Perhaps we should just clearly  indicate when scripts we call out are from chrome extensions? We are thinking about doing the same for 3rd party resources, too.  @fchristant sound good?

**Comment by fchristant** [comment]
@paulirish Sounds good. I'm fine with both the label or to just exclude them altogether, either is great.
Do web extension scripts in any way impact actual scores?

**Comment by paulirish** [comment]
> Do web extension scripts in any way impact actual scores?

Yeah they could if they do heavy work inside the page.

**Comment by fchristant** [comment]
@paulirish I never knew that. For now that would mean for me to only do performance analysis and audits in incognito mode, otherwise the results would be skewed towards my specific set of extensions (which are a lot, being a web developer). IMHO, one would always want an extension-neutral result, but maybe others disagree.

**Comment by paulirish** [comment]
#4733 wants this called out on the bootup-time audit.

**Comment by paulirish** [comment]
Current proposal:

1. We visually annotate rows in the report where the named resource is from a chrome extension. 
   - v2: we do the same for 3rd party domains
2. We look at the bootup-time audit and if there are chrome extensions spending "lots of" main thread time, then we add a topLevelWarning in the report for the user, including a recommendation to use incognito.

**Comment by brendankenny** [comment]
let's close in favor of #4516, which is in progress in #6351 :)
