### ISSUE TITLE
Audit - Entire Website vs Page in Focus

### ISSUE THREAD

**Issue by CalvoGraves** [GoogleChrome/lighthouse#4014]
This is a request, not "an issue" per se. 

Is there any discussion about further developing the audit function within Chrome's "Inspect" tool so that when an audit is requested lighthouse could audit the entire website as opposed to only the page in focus?

That would be awesome! # #

**Comment by patrickhulce** [comment]
Thanks for filing @CalvoGraves! You might be interested in GitHub's [lightcrawler](https://github.com/github/lightcrawler) project which does what you suggest :)

**Comment by digitaliteter** [comment]
Or lighthouse-report. Does what you ask for.

**Comment by paulirish** [comment]
Yes, lightcrawler is the proper solution for this. :)
