### ISSUE TITLE
Improve node selectors shown in the details table

### ISSUE THREAD

**Issue by kdzwinel** [GoogleChrome/lighthouse#4015]
In `is-crawlable` and `hreflang` audits nodes listed in the details table have no selector set eg.

```javascript
source: {
  type: 'node',
  snippet: `<meta name="robots" content="${artifacts.MetaRobots}" />`,
 //selector: ??
},
```

This causes resulting table item title to be set to 'undefined':

<img width="221" alt="undefined-title" src="https://user-images.githubusercontent.com/985504/33778637-ce82cf2a-dc49-11e7-9fd0-f5994d381857.png">

We should show element selector instead, just like axe-core audits do:

<img width="451" alt="axe-title" src="https://user-images.githubusercontent.com/985504/33778796-8aa02c48-dc4a-11e7-9d4a-2d5708ddca62.png">

However, to build a full selector we'd need class+id+nodeName for given node and all its ancestors which would require more work from the gatherers.

`font-size` audit is in a bit better situation because we do have all the data needed from the gatherer, however, we still can't reuse [`getSelector`](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/get-selector.js) from axe-core since we don't have real DOM nodes, but rather devtools protocol nodes.
I've put together a [simpler alternative](https://gist.github.com/kdzwinel/2e2f35af56d6da07fbfac12069bf5cff) that would work here, but it doesn't guarantee selectors to be pretty or unique. For now [we decided](https://github.com/GoogleChrome/lighthouse/pull/3533#discussion_r154702691) to show only id, class or node name of the parent element.

**Comment by patrickhulce** [comment]
Decided to do something simple here just using the class, id, and name/type attributes of the current node and not worry about parents

**Comment by brendankenny** [comment]
we fixed the `undefined` hover when we first added types to `details-renderer` in #5195, and #6683 and #8961 are taking up the mantle here, so I'm going to close.
