### ISSUE TITLE
Add tests for network recorder

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#402]
Coverage is pretty low atm:

![screen shot 2016-06-01 at 1 04 21 pm](https://cloud.githubusercontent.com/assets/617438/15708888/6e530c1a-27f9-11e6-8631-e78b63a369e4.png)

@brendankenny you okay to take a look at this?

**Comment by brendankenny** [comment]
I think there's [not really anything in here](https://github.com/GoogleChrome/lighthouse/blob/b1e091957e045a38b71d077eb6b161cfd394c02a/src/lib/network-recorder.js); it's just a dispatcher for CRI events -> WebInspector events. It is a good case for coverage from an end-to-end test. On a single run you'll get coverage of each line for each network request to load a page.

Mocking WebInspector would just be verifying that the mock was declared correctly. Mocking requests and actually pulling in WebInspector would make some sense, but, again, the file is so simple it would really just be testing if our request was mocked well enough to fool WebInspector :) Doing that for a scheduler + mocked driver test sounds more meaningful, though, and should still run much faster than a real lighthouse run.
