### ISSUE TITLE
"Does not use images with appropriate aspect ratio" reporting incorrectly

### ISSUE THREAD

**Issue by UltCombo** [GoogleChrome/lighthouse#4026]
I'm experiencing an incorrect "Does not use images with appropriate aspect ratio" error on Lighthose 2.5.1.

Lighthouse does not say what images are problematic, and the problem persists even after removing all images from the page (including SVGs and meta tags).

Here's a page example that reproduces the issue: https://ult.bitballoon.com/

**Comment by UltCombo** [comment]
I've striped the example code down to a very basic HTML page without any external resources:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>title</title>
</head>
<body>
</body>
</html>
```

And the error still persists. Any thoughts?

**Comment by patrickhulce** [comment]
thanks for reporting @UltCombo! This was a bug that has been fixed in 2.6 (#3551), so you should be good to go with the latest version 👍

**Comment by UltCombo** [comment]
@patrickhulce Awesome, thanks!

Do you have any idea when it hits Chrome stable/canary? Just wondering, is DevTools' Lighthouse updated automatically or only with Chrom(e|ium) releases?

Thanks for delivering this awesome tools. 😄

**Comment by patrickhulce** [comment]
Yes, it should be available in Canary shortly and go out with M65 which hits stable in ~Feb 2018.

Lighthouse in DevTools follows Chrome's release process which is a new version every ~6 weeks. The extension, CLI, and WPT versions are usually a bit ahead of DevTools for this reason :) glad you're enjoying the tool feel free to file any feature suggestions or improvement ideas you might have! 😄
