### ISSUE TITLE
Audit tests require strict mode

### ISSUE THREAD

**Issue by stuartlangridge** [GoogleChrome/lighthouse#403]
$ npm run unit
    > lighthouse@1.0.0 unit /home/aquarius/Programs/Others/lighthouse
    > mocha $(find ./test -name '*.js') --timeout 60000
    /home/aquarius/Programs/Others/lighthouse/test/src/audits/audit.js:22
    class A extends Audit {}
    ^^^^^
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

This is trivially solved by adding `"use strict"` to `test/src/audits/audit.js`, but perhaps that's not done because some other setting is expected somewhere? (Otherwise I don't understand why everyone hasn't had this failure every time.) Is node expected to be in strict mode by default for lighthouse or something? I'm using node v5.11.1.

**Comment by paulirish** [comment]
fixed by ec140b93670c96fcd27563fa5dbc7f1e77816724

**Comment by samccone** [comment]
Thanks @stuartlangridge :clap:

**Comment by paulirish** [comment]
Yes thanks for reporting! The bug was only there for 6 hours but you managed to hit it during that time. :)

**Comment by stuartlangridge** [comment]
ha! Story of my life. :)
