### ISSUE TITLE
Unreadable javascript libraries with vulnerabilities in dark theme

### ISSUE THREAD

**Issue by ryanyuyu** [GoogleChrome/lighthouse#4034]
When using the Dev Tools dark theme, the table generated for the audit called javascript libraries with vulnerabilities.  

See 

![2017-12-12 07_57_24-developer tools](https://user-images.githubusercontent.com/14897024/33888496-d7e10b92-df12-11e7-930f-53c47d8ae13c.png)

**Comment by paulirish** [comment]
I fixed this. It's fixed. 🎵
