### ISSUE TITLE
Issue count varies if i run from command line and from the Extension

### ISSUE THREAD

**Issue by Raj-chandru** [GoogleChrome/lighthouse#4040]
When i open a chrome browser and type the URL  say for example https://www.britishairways.com/travel/home/public/en_in ,  once page is loaded i will go to  my extensions and execute the google lighthouse extension(before executing i will just select the accessibility in the google light house options).   Once the execution is complete i am able to see the report. Now i will go to command line and execute the sample URL like
lighthouse  https://www.britishairways.com/travel/home/public/en_in .  Once the report is generated i see the the issue count is getting varied when compared to the previous run. For previous run i got nearly 50+ but for the later one i see only 14 issues. 

Can someone help here
thanks

**Comment by sanjsanj** [comment]
@Raj-chandru do you have any browser extensions running that could be interfering somehow?  Any console errors?

**Comment by patrickhulce** [comment]
Thanks for filing @Raj-chandru! In addition to @sanjsanj's questions would you mind clarifying what issue count you're referring to?

Right now it sounds like you run just the accessibility category in the extension but all categories from the CLI which one would expect to have more failures since there are more audits.

**Comment by Raj-chandru** [comment]
From  the CLI i executed only for the Accessibility by providing the configuration,  which i have attached here . Also currently i am using the chrome browser version Version 63.0.3239.84 (Official Build) (64-bit)




[myconfig.txt](https://github.com/GoogleChrome/lighthouse/files/1571651/myconfig.txt)

**Comment by patrickhulce** [comment]
Thanks for the config! It's very difficult to diagnose what's going on without seeing the resulting reports though. Could you please answer the questions we've posed so we can try to help here?

* What issue count are you referring to? Failed audits? Failed elements?
* Do you have any browser extensions running that could interfere?
* Did you observe any console errors in the page when auditing in Chrome?

**Comment by paulirish** [comment]
duping into #1426
