### ISSUE TITLE
Check for image aspect ratio under best practices fails even when there is no <IMG> tag in the page

### ISSUE THREAD

**Issue by raja-anbazhagan** [GoogleChrome/lighthouse#4044]
Expanding the failed audit, I'm surprised that there is not even a single piece of information that lets me know which tag or element which under the hood is causing the problem
![capture](https://user-images.githubusercontent.com/8947215/33953593-8008bc54-e05b-11e7-9799-cec0d64b487a.PNG)

**Comment by patrickhulce** [comment]
Thanks for reporting @raja-anbazhagan! This was actually fixed in 2.6, so latest versions of CLI and Chrome Extension should be good to go with fix hitting DevTools soon.
