### ISSUE TITLE
Perf: Add a single screenshot audit

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#4049]
For the fast-mode config, we still need a single screenshot of the page at the end of load, so we should create a new audit for just the last full resolution screenshot.

**Comment by paulirish** [comment]
Related, I've been thinking we should grab a screenshot of the page in case of failure. (especially if the page failed to load).

**Comment by benschwarz** [comment]
Yup. Super useful for failure runs.

**Comment by paulirish** [comment]
now done!  'final-screenshot' audit. :D
