### ISSUE TITLE
Update image format docs to move away from just suggesting WebP

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#4050]
Need to update https://developers.google.com/web/tools/lighthouse/audits/web to talk about JPEG 2000, JPEG XR, and WebP. 

This table could be useful to put in here: https://user-images.githubusercontent.com/39191/33581791-2066d46c-d907-11e7-971f-df0f62c725f2.png

**Comment by patrickhulce** [comment]
PR up at https://github.com/google/WebFundamentals/pull/5522

**Comment by patrickhulce** [comment]
done!
