### ISSUE TITLE
Closing the first tap when launching chrome which is a local path 

### ISSUE THREAD

**Issue by OmarAbdElNasser** [GoogleChrome/lighthouse#4053]
I wanna close the first tap and leave only the blank tap 
Here's a pic showing what i mean .
![untitled](https://user-images.githubusercontent.com/34121159/33984565-bb2845ce-e0c0-11e7-89bc-6011edddddff.png)

Here's my code
```
const fsExtra = require('fs-extra')
const chromeLauncher = require('lighthouse/chrome-launcher/chrome-launcher');
const CDP = require('chrome-remote-interface');
const fs = require('fs');
const windowWidth = 6200;
const windowHeight = 6060;

headless=false
const launchConfig = {
    chromeFlags: [
        `--window-size=${windowWidth},${windowHeight}`,
        '--disable-gpu',
     headless ? '--headless' : ''
	 ]
}

async function launchChrome(headless = true) {
  return await chromeLauncher.launch(launchConfig);
}
url = "D:/ImageProcessing/HTML_Images3/Image_"+1+".HTML";

const chrome =  launchChrome();
console.log(chrome)
```

**Comment by patrickhulce** [comment]
It seems like what you're trying to do might be better accomplished using a library like [puppeteer](https://github.com/GoogleChrome/puppeteer). Looking through their docs should help but you can reach out there if you think the docs need improvement!

Feel free to reach out again here if you have problems with the Lighthouse tool itself!
