### ISSUE TITLE
Use too many large size images may cause the Hybrid App to crash down

### ISSUE THREAD

**Issue by zack-lin** [GoogleChrome/lighthouse#4054]
In some business situation, our front developers often use too many large size images in a web page.
For example, an image tag may be set 18px * 18px, used by an image of 180px * 180px actual size. When the skia cache have been used to a certain threshold, this app may be crashed on some low-end machines.
So, we want to show to our developers why use so much large size images can be caused to the app crash down.
Can you give me more advice?

**Comment by patrickhulce** [comment]
Hey @zack-lin yes we do have advice wrapped up nicely in a handy audit called "Properly size images" which catches this case :)

![image](https://user-images.githubusercontent.com/2301202/34064653-a3a0a5dc-e1af-11e7-8828-e8ec192537c0.png)

The audit surfaces how many bytes could have been saved delivering the images over the network but your point about the skia cache and stability issues is an extra reason to follow the advice of this audit!

I'm going to close this as resolved, but feel free to re-open if you think there's something missing from this audit that could be improved.

**Comment by zack-lin** [comment]
@patrickhulce Should we tell the developers clearly why too many large size images result in the app's stability?

**Comment by patrickhulce** [comment]
We would generally put that kind of information in the documentation which lives over on [WebFundamentals](https://github.com/google/WebFundamentals). It's a rarer concern but seems worth mentioning 👍
