### ISSUE TITLE
Improve URL readability in tables

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#4059]
This code:

    <img src="http://placehold.it/100X100" width="100" height="50" />

Triggered this report:

<img width="821" alt="screen shot 2017-12-14 at 12 43 37 pm" src="https://user-images.githubusercontent.com/4713486/34013496-947fc47c-e0cc-11e7-9732-9ced30531155.png">

Seems like **URL** could/should be more descriptive. When I see `/100X100` I'm inclined to think it's a resource hosted on my site, when in reality it was external.
  
related #3827

**Comment by paulirish** [comment]
fixed by #4190
