### ISSUE TITLE
No images - Fail the "aspect ratio" audit.

### ISSUE THREAD

**Issue by Soaku** [GoogleChrome/lighthouse#4073]
My website failed the "Does not uses Images with appropriate aspect ratio" because it had no images.

Also, the name of this audit has a grammatical error ("uses" after "does"). And, why is "images" uppercase?

**Comment by patrickhulce** [comment]
thanks for filing @Soaku this has been fixed in 2.6+ so expect it in Chrome 65 or upgrade your extension/CLI to 2.6 or 2.7.
