### ISSUE TITLE
Audit is now disabled in sites not running http/https

### ISSUE THREAD

**Issue by KBPsystem777** [GoogleChrome/lighthouse#4075]
Hi, after updating my chrome to latest version, Audit functionality was disabled now to sites not having an http/https and even on sites sitting under development too. PWA Audits is very important especially when the site is on dev stage - it helps us identifying the possible performance issues.

**Comment by patrickhulce** [comment]
Thanks for filing @KBPsystem777 can you provide a bit more detail about your situation?

Over what protocol is your site served that you would deliver a service worker if not http(s)?

**Comment by KBPsystem777** [comment]
Hi @patrickhulce I am always running the Lighthouse audit on my local machine.
Sample browser address: `c:\users\kbpsystem\html\index.hml` But the audit don't work on this case now.

![image](https://user-images.githubusercontent.com/20304211/34410832-eab6ea72-ec0d-11e7-83ab-98d9d1e88182.png)

Thanks,

**Comment by patrickhulce** [comment]
Ah, yes `file://` development is not supported under the audits panel. We strongly encourage you to test on a development server as many aspects of file protocol differ from http which your site will ultimately be served under. If you really wish to audit a `file:` url though, you may try with the extension or the CLI.

Let us know if you have any more questions!
