### ISSUE TITLE
Extension requires eslint-config-google, doesn't install it.

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#41]
Wondering if we should add this to both the root package.json and the extension, or just the extension. WDYT?

**Comment by samccone** [comment]
Since the extension runs in a different context, I am OK with having it be separate since there will be quite a few rules that do not make sense in a node context.


+1 to add eslint-config-google to the extension (I guess i just forgot to add it)
+1 to get the extension lint tests running on CI

**Comment by addyosmani** [comment]
> +1 to add eslint-config-google to the extension

Yes, please!

**Comment by paulirish** [comment]
sam, assigning to you for both.

**Comment by samccone** [comment]
kk :+1:
