### ISSUE TITLE
Wrong first meaningful paint?

### ISSUE THREAD

**Issue by abdonrd** [GoogleChrome/lighthouse#4109]
In this Lighthouse report:

https://builder-dot-lighthouse-ci.appspot.com/report.1513957911311.html

I have these Performance statistics:

<img width="850" alt="screen shot 2017-12-22 at 16 57 04" src="https://user-images.githubusercontent.com/1007051/34304256-3a28b4b6-e739-11e7-9eff-5a6d1ab990b7.png">

The `First meaningful paint` should not be at ~3s?

**Comment by vinamratasingal** [comment]
Hi! Can you provide more explanation as to why the FMP should not be 3 seconds? It's showing in the report as 5 seconds?

**Comment by abdonrd** [comment]
@vinamratasingal Seeing the screenshots...

<img width="264" alt="screen shot 2017-12-22 at 22 37 40" src="https://user-images.githubusercontent.com/1007051/34313049-c71067f0-e768-11e7-8541-5e23834ee80b.png">

The skeleton is painted in 3s.

Does not that correspond to FMP?

**Comment by vinamratasingal** [comment]
It's a bit hard to correlate the film strip to FMP given that other heuristics are employed (such as when web fonts are loaded, etc.) to measure FMP. I'd recommend reading the documentation to learn more: https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint

**Comment by abdonrd** [comment]
Oh, okay! I misunderstood the report then. I assumed they were related.

**Comment by patrickhulce** [comment]
@abdonrd the filmstrip and metrics are indeed related and the line you see for each metric does correspond to point in time of the filmstrip above.

What @vinamratasingal is saying is that there are lots of things going on with a page that are not captured by the filmstrip (such as network activity, JavaScript execution, etc) that influence the metric values and so they won't always line up to the first frame that has visual completeness.

In this case though, FMP is when most of the above the fold elements have been rendered, a skeleton is not a "meaningful" paint, i.e. the user didn't come to your page to see the skeleton they came to see the content so 5s is WAI.

Please let us know if you have any more questions or ideas to make the docs links more accessible!
