### ISSUE TITLE
Missing Shadow DOM support

### ISSUE THREAD

**Issue by RyanAfrish7** [GoogleChrome/lighthouse#4111]
Getting error when used with Polymer. I guess it's because of the Shadow DOM.

![image](https://user-images.githubusercontent.com/9781909/34311639-b6ccd4e8-e784-11e7-8adf-f146b89a5d52.png)

**Comment by vinamratasingal** [comment]
Hi Ryan- can you give us the name of the website you audited so we can reproduce and followup?

**Comment by RyanAfrish7** [comment]
@vinamratasingal 
Oops. The website is in development and it is hosted locally. I can help you if there is somewhere I can extract detailed logs.

**Comment by patrickhulce** [comment]
@RyanAfrish7 this has been fixed by https://github.com/GoogleChrome/lighthouse/pull/3779 using the latest version of the extension or CLI should make this error go away.

Feel free to re-open if it's still happening to you with Lighthouse 2.7!
