### ISSUE TITLE
Image aspect ratio audit failed in pages with no images

### ISSUE THREAD

**Issue by afontcu** [GoogleChrome/lighthouse#4137]
Hi!

I've been testing a webpage that contains no images, and Lighthouse is still reporting a failed audit on "Does not use images with appropiate aspect ratio":

![image](https://user-images.githubusercontent.com/9197791/34441525-947b5d3c-ecbc-11e7-9644-54a7fd787a54.png)

You can check it out in http://fontcuberta.cat

I even added the `sizes="16x16" parameter in my favicon links, just in case.

thanks

**Comment by bishwashere** [comment]
What does the drop-down contain? It shows the list of items it inspected right?

**Comment by afontcu** [comment]
Hi! It's empty (sorry I didn't mention that). The picture shows it all.

Thanks and happy new year!

**Comment by wardpeet** [comment]
@afontcu is it possible to share the url so we can run it ourselves? Or give us a snippet of html we can try to reproduce

**Comment by vinamratasingal** [comment]
Hi- we fixed this issue with Lighthouse 2.6.0, and it's possible you're running an older version of Lighthouse. Can you try running it with the Extension to see whether it works now?

**Comment by kemalcany** [comment]
Hi! I am having the same issue. Here's a blank site you can inspect:

https://vuessrtest.com/
and the code can be found at
https://github.com/kemalcany/vue-ssr-starter

Thank you!!

**Comment by vinamratasingal** [comment]
Hi @kemalcany - please follow the fix outlined above. I ran it with the Extension and 2.7.0 and it worked :)

**Comment by afontcu** [comment]
Hi! 

Indeed, this has been fixed using the extension (v2.7.0)

Things I learned:
1) Lighthouse extension is not dead (and it's ahead of devtools).
2) There's a new SEO panel in 2.7! It looks great (but quite basic IMHO).

Thank you all for your time! I'll close.

**Comment by kemalcany** [comment]
@vinamratasingal fantastic! You've added SEO too! Cool. Thank you very much!!!
