### ISSUE TITLE
DevTools Error: Audit stuck at 'Retrieving trace'

### ISSUE THREAD

**Issue by bishwasmishra** [GoogleChrome/lighthouse#4147]
**Initial URL**: https://wotcco.com/
**Chrome Version**: 63.0.3239.84
**Error Message**: No error message
**Stack Trace**: No trace

Note: This is the first audit run for this website

![audit](https://user-images.githubusercontent.com/5249069/34460289-a9cc6c5a-edbe-11e7-9b8f-f4771f9102bd.PNG)

**Comment by bishwasmishra** [comment]
**Initial URL**: https://google.com/
**Chrome Version**: 63.0.3239.84
**Error Message**: No error message
**Stack Trace**: No trace

![image](https://user-images.githubusercontent.com/5249069/34460413-ece15e12-edc1-11e7-9384-e29b062a80e1.png)

**Comment by wardpeet** [comment]
@bishwasmishra could you give us more information about your system.
Mac? Windows? How long were you waited?

Is it possible to audit your site with the lighthouse extension?

**Comment by vinamratasingal** [comment]
Hi Bishwasmira- thanks for writing in! This is a bug with Chrome, and we recommend restarting Chrome if you see this error again. I'm going to close this out for now but if you still see the issue feel free to reopen.
