### ISSUE TITLE
<input class="whsOnd zHQkBf" jsname="YPqjbf" autocomplete="current-password" spellcheck="false" tabindex="0" aria-label="Passwort eingeben" name="password" autocapitalize="off" autocorrect="off" dir="ltr" data-initial-dir="ltr" data-initial-value="" badinput="false" aria-invalid="true" type="password">

### ISSUE THREAD

**Issue by Fax33** [GoogleChrome/lighthouse#4155]

**Comment by Fax33** [comment]
<input class="whsOnd zHQkBf" jsname="YPqjbf" autocomplete="current-password" spellcheck="false" tabindex="0" aria-label="Passwort eingeben" name="password" autocapitalize="off" autocorrect="off" dir="ltr" data-initial-dir="ltr" data-initial-value="" badinput="false" aria-invalid="true" type="password">

**Comment by vinamratasingal** [comment]
Hi- Can you tell us a bit more about the problem that you're facing?
