### ISSUE TITLE
DevTools Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by TheOfficialDoc** [GoogleChrome/lighthouse#4159]
**Initial URL**: https://newlandgaming.com/
**Chrome Version**: 63.0.3239.84
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@8f51ed0e633e109109762a3deb18a50e8c138819/audits2_worker/audits2_worker_module.js:694:516)
    at <anonymous>
```

**Comment by vinamratasingal** [comment]
Hi @TheOfficialDoc! We've seen this error before so we are going to close this bug and fold it into our umbrella issue #2448. If you have any followups, feel free to comment directly on that issue.
