### ISSUE TITLE
FontSize artifact isn't serializable

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#4184]
This causes a problem with running Lighthouse in -G mode (#3743)

It's because the artifact itself contains `WebInspector.CSSStyleDeclaration` objects. Without looking, the typical fix would be to create these objects either in the audit or in a computed artifact.

**Comment by kdzwinel** [comment]
Audit only uses couple of properties from `WebInspector.CSSStyleDeclaration`. WDYT about just limiting amount of data produced by gatherer to what audit actually needs (like this: https://github.com/kdzwinel/lighthouse/commit/71dba68780d672284668ad4b94751a3c629c5812) ?

BTW it might be a good idea to add a test for checking if all gatherers produce serializable results.

**Comment by paulirish** [comment]
> Audit only uses couple of properties from WebInspector.CSSStyleDeclaration. WDYT about just limiting amount of data produced by gatherer to what audit actually needs (like this: kdzwinel/lighthouse@71dba68) ?

yes looks perfect

> BTW it might be a good idea to add a test checking if all gatherers produce serializable results.

heh. was thinking the same.
https://github.com/GoogleChrome/lighthouse/compare/artifactserialization
interestingly the deepStrictEqual is failing in some cases. Gotta look into that since Map()s can be serialized but aren't parsed back into maps. :)
for another day!

**Comment by kdzwinel** [comment]
OK, PR opened 👍 

> interestingly the deepStrictEqual is failing in some cases. Gotta look into that since Map()s can be serialized but aren't parsed back into maps. :)

As far as I can see `JSON.stringify` serializes all Maps to `{}`. IMO anything other than numbers, strings, arrays and plain objects, shouldn't be allowed in artifacts, so it does make sense to fail here.

**Comment by paulirish** [comment]
>> interestingly the deepStrictEqual is failing in some cases. Gotta look into that since Map()s can be serialized but aren't parsed back into maps. :)

> As far as I can see JSON.stringify serializes all Maps to {}. IMO anything other than numbers, strings, arrays and plain objects, shouldn't be allowed in artifacts, so it does make sense to fail here.

Yeah agree. I'm pretty sure that dSE() is failing in cases unrelated to Map() right now. gotta look into it some more.
