### ISSUE TITLE
--save-assets: kill off screenshots.html/screenshots.json

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#4187]
AFAIK, we don't have any more customers of these.

@benschwarz @alekseykulikov

you guys good with this?

**Comment by benschwarz** [comment]
Yep. I'm not using the output of `--save-assets`.

**Comment by wardpeet** [comment]
@paulirish if we kill this of is their a manual way to get screenshots going?
Just wondering as I might need this in the future 😛

**Comment by patrickhulce** [comment]
@wardpeet yeah you'll still be able to fairly easily grab them from the trace :)

it's ~20 [lines](https://github.com/paulirish/speedline/blob/53b51d283fcbed69710eda58e8c3539f0fb9134d/src/frame.js#L90-L102)

**Comment by paulirish** [comment]
Yah. easy enough to restore the https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/computed/screenshots.js computed artifact later if we need it again.

**Comment by wardpeet** [comment]
thanks for explaining, didn't knew how it worked actually

**Comment by wardpeet** [comment]
@paulirish i believe we can close this?

**Comment by brendankenny** [comment]
Not yet :) https://github.com/GoogleChrome/lighthouse/blob/1ac7bd1176e21b3b836cbc0a67c14e42825e66d7/lighthouse-core/lib/asset-saver.js#L301-L307

(we really should delete)

**Comment by paulirish** [comment]
fixed by #6066
