### ISSUE TITLE
video playback error

### ISSUE THREAD

**Issue by Bluewolf1457** [GoogleChrome/lighthouse#4207]
when i watch my favorite bleach series it would keep saying its not supported but if i keep refreshing the page the video will some times comes up but i would like it if i don't refresh the page every 5 seconds to keep the video up. i want the site to at least have it to were the video can load and play for everyone without issues but it keeps doing it to me even though i've been on this site ever since it came out please fix JustDubs.org and there full bleach series so i can continue watching my bleach. it make me happy to watch it.

**Comment by paulirish** [comment]
this isn't the right bug tracker for your issue. sorry
