### ISSUE TITLE
Config in extension?

### ISSUE THREAD

**Issue by boopathi** [GoogleChrome/lighthouse#421]
[Question]

Lighthouse now requires a config object with `passes`, `audits` and `aggregations`. How to set this in extension? I'm not able to run the extension. This fails in `isValidConfig()`.

I see the only options passed from extension to lighthouse.js are - 

```
flags: {
        mobile: true,
        loadPage: true
      }
```

**Comment by paullewis** [comment]
Yeah I did a big refactor to make large parts of the Lighthouse flow generic, and #414 fixes the issues introduced by the change. Hopefully we'll land that soon.
