### ISSUE TITLE
Image aspect ratio, possible to list?

### ISSUE THREAD

**Issue by McCrisp** [GoogleChrome/lighthouse#4215]
Some times under "Best Practises" it will say that some images are not using their natural aspect ratio. It would be really helpful to get a list of the actual images, instead of having to look around for it!

**Comment by waffledonkey** [comment]
My page doesn't even have discrete images (`document.images` and `document.getElementsByTagName('img')` result in an empty HTMLCollection) and I still get an error about aspect ratio of images.  The page does use some background images but every one of them uses background-size property where one of either the width or height is *"auto"*. (eg. `background-size: 35px auto;`) I'd think that would ensure that the aspect ratio was maintained and yet I still fail the rule. I think the rule is bugged.

**Comment by DoroGi** [comment]
I have a site with no images at all. Not even as background. I still get the warning.

**Comment by paulirish** [comment]
Whoops sorry. This was originally filed as #3551 and fixed via #3552 

Chrome 65 has this fix. It'll take a bit to get to Chrome stable.
