### ISSUE TITLE
DevTools Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by rishabh09** [GoogleChrome/lighthouse#4225]
**Initial URL**: http://localhost:3000/venues
**Chrome Version**: 63.0.3239.132
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:694:516)
    at <anonymous>
```

**Comment by vinamratasingal** [comment]
Hi! We've seen this error before so we are going to close this bug and fold it into our umbrella issue #2448. If you have any followups, feel free to comment directly on that issue.
