### ISSUE TITLE
Remove SEO "Additional items to manually check: Page is mobile friendly"

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#4248]
Lighthouse does a number of checks for this - it feels like a redundant ask to "manually" check this.

**Comment by paulirish** [comment]
@rviscomi correct me if i'm wrong, but I think the plan is that we remove this once we implement and ship the Tap Targets audit, yah? This is planned for the next quarter.

When that's done we'll need to make sure we show all the relevant mobile-friendly audits within SEO, even though some may also be in PWA/bestpractices. That's straightforward for us, but might be a little odd for our users.

In the meantime, we may want to tweak our wording of this manual audit to communicate it's testing _slightly more_ stuff that LH isn't?

**Comment by rviscomi** [comment]
What Paul said.

Let's keep this issue open to find better wording so it's clear that the recommendation is to go off and check for things not covered in LH.

**Comment by gauntface** [comment]
I'm not sure what these "things" are, but being more explicit if it's more than - set a viewport, work on a 3G connection would be helpful - at the moment, the wording makes it borderline useless in the context of lighthouse :(

**Comment by rviscomi** [comment]
The MFT checks include:

- [ ] Flash usage
- [x] Viewport not configured
- [x] Fixed-width viewport
- [x] Content not sized to viewport
- [x] Small font size
- [ ] Touch elements too close

4/6 of these are already included in LH and we plan to implement the remaining two in the next iteration of SEO audits. Until then, we can change the wording to be more explicit, eg "Run the MFT to audit best practices not covered by Lighthouse including avoiding plugins and sizing tap targets appropriately."

WDYT?

**Comment by paulirish** [comment]
@rviscomi ❤️s all around. let's do that.

**Comment by rviscomi** [comment]
@kdzwinel let's change the audit description to this:

"Take the [Mobile-Friendly Test](https://search.google.com/test/mobile-friendly?url=http%3A%2F%2Fexample.com%2F) to check for audits not covered by Lighthouse, like sizing tap targets appropriately. [Learn more](https://developers.google.com/search/mobile-sites/)."

And the MFT name links to `https://search.google.com/test/mobile-friendly?url=http%3A%2F%2Fexample.com%2F` where `url=` is the encoded URL of the current page. Does that work?
