### ISSUE TITLE
"Works Offline" should simulate a navigation request

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/lighthouse#425]
The "works offline" audit [currently](https://github.com/GoogleChrome/lighthouse/blob/a0c8b05d4c706821535ae365c7ed2ac0cc3373a3/src/gatherers/offline.js#L29) performs the following:

```js
const requestPage = function() {
  const oReq = new XMLHttpRequest();
  oReq.onload = oReq.onerror = e => {
    // __returnResults is injected by driver.evaluateAsync
    __returnResults(e.currentTarget.status);
  };
  oReq.open('GET', '');
  oReq.send();
};
```

Some service worker implementations (like the one `sw-precache` [uses](https://github.com/GoogleChrome/sw-precache/blob/1ca4494e40da50364cce34b7daa01259c848f0a4/service-worker.tmpl#L120)) have logic in place to detect whether the incoming `fetch` event is associated with a `Request` whose `mode` is set to `'navigate'`, and take specific action when that's the case—like falling back to a cached `Response` representing the App Shell, allowing them to work offline.

I understand that using an `XMLHttpRequest` is much easier to script than properly triggering a navigation request, though. (Even if the code used `fetch()`, it's not possible to construct a `Request` with `mode` set to `'navigate'`.) Maybe there's something that could be done with creating an `<iframe>` and checking whether that loads properly? Or else scripting a navigation to the same URL and then detecting if that is successful? Any thoughts on those approaches?

**Comment by samccone** [comment]
the iframe approach sounds good. We could easily do that.

**Comment by paullewis** [comment]
@jeffposnick Do you fancy giving that PR a go?

**Comment by paullewis** [comment]
Nudge! How's this going, Jeff?

**Comment by jeffposnick** [comment]
It's not going yet!

But I still would like to do this, and should have some time to get it done soon-ish.

**Comment by wardpeet** [comment]
i'm up for this one as well, no rush :) @jeffposnick
