### ISSUE TITLE
Lighthouse hangs indefinitely on Retrieving Scripts

### ISSUE THREAD

**Issue by phani1kumar** [GoogleChrome/lighthouse#4258]
First of all, thank you for an excellent tool.

I am using the chrome extension of lighthouse for sometime. And being benefited by the insights that it gives on page analysis. But all of a sudden it started hanging at the "Retrieving Scripts" stage and never proceeds further. I have stopped all the other extensions on chrome and tried again. But still the same issue.

The site is publicly available: https://itsroo.com
Attached the complete log file here
[itsroo_com.log](https://github.com/GoogleChrome/lighthouse/files/1629963/itsroo_com.log)

**Comment by paulirish** [comment]
Yup I can reproduce this in the 2.8.0 extension on https://itsroo.com/

![image](https://user-images.githubusercontent.com/39191/35003972-6cd380bc-faa3-11e7-9e7e-7edfe4fc1929.png)

I can't repro it with the CLI, though, interestingly.

**Comment by ev1stensberg** [comment]
@paulirish can I work on this one?

**Comment by Rudloff** [comment]
I get the same issue on https://openvegemap.netlib.re with Chromium 63.0.3239.84 and Lighthouse 2.8.0.

**Comment by jerryzhoujw** [comment]
Got same issue with extension. So I use the Chrome’s DevTool / Audits, which works fine.

**Comment by alekbarszczewski** [comment]
Same issue :(

**Comment by lellefood** [comment]
For who is using @jerryzhoujw workaround, I would like to point out to you that there is an online lighthouse report viewer, that given a json report renders the report as html.  
You can find it here: [https://googlechrome.github.io/lighthouse/viewer](https://googlechrome.github.io/lighthouse/viewer/)

**Comment by MichalSuski** [comment]
Guys, don't you think it is a website related issue? I got the same problem on https://dreamteamtrips.com but when I make report for other websites then it works fine.

**Comment by Rudloff** [comment]
Yes, it only happens on some specific websites but I haven't figured out what is special about them.

**Comment by MichalSuski** [comment]
Thank you buddy, I think this may be a major issue, this page barely rank in google even when it's well optimized and got some links already. I will let you know when we figure out what's wrong.

**Comment by Belchona** [comment]
the same problem on our landing page. It's still relevant

**Comment by prescottprue** [comment]
Also seeing this, but only with one of our sites that has a few more scripts being loaded.
