### ISSUE TITLE
Best Practises could warn about using deprecated and obsolete HTML tags

### ISSUE THREAD

**Issue by coliff** [GoogleChrome/lighthouse#4265]
It'd be good if the Best Practises audit checked for deprecated and obsolete HTML tags being used; e.g. 
```
acronym, applet, basefont, big, dir, frame, frameset, isindex, listing, menu, multicol,
plaintext, strike, xmp, bgsound, blink, comment, embed, marquee, nobr, noembed, wbr
```

**Comment by paulirish** [comment]
Here is our new audit process, if you're interested in writing up the proposal for this one: https://github.com/GoogleChrome/lighthouse/blob/master/docs/new-audits.md

Specifically for this proposal.. the overall impact seems low compared to some of the other audit proposals we have: https://github.com/GoogleChrome/lighthouse/issues?q=is%3Aissue+is%3Aopen+label%3Anew-audit+sort%3Acomments-desc
