### ISSUE TITLE
Navigation of the web application

### ISSUE THREAD

**Issue by KathiresanRamkumar95** [GoogleChrome/lighthouse#4283]
During the lighthouse web page performance test, How to navigate my web application from homepage to another next page for accessibility and functionality testing and the login procss.
Is there any way to navigate my application during lighthouse audit.
Let me know all the possible ways to navigate my web application.

Thanks in advance!

**Comment by patrickhulce** [comment]
Thanks for filing @KathiresanRamkumar95! What you're asking for isn't very well supported today, but there's some discussion in #3837 that might be useful to you and Lighthouse/puppeteer support is our planned way of addressing this concern.

I'm going to go ahead and close this issue in favor of that one, but feel free to comment in there with any specific requirements you think you might have! 👍
