### ISSUE TITLE
Clean up the formatting style: accordion, first section default behavior/collapsibility, indentation

### ISSUE THREAD

**Issue by hwikyounglee** [GoogleChrome/lighthouse#4284]
- [ ] First section header
- [ ] First section collapsibility (do vs. don't)
- [ ] Way(s) to indicate failing tests (X, red text, header, etc)
- [ ] Indentation

First outcome is a set of mocks of exploration, then, narrow down to agreement. Then, spec/redline to be ready for implementation. This takes time!

**Comment by paulirish** [comment]
@hwikyounglee i think we can close this yah?

**Comment by hwikyounglee** [comment]
Yes.
