### ISSUE TITLE
Failed Audits (LINKS)

### ISSUE THREAD

**Issue by Ehud-Simhi** [GoogleChrome/lighthouse#4286]
Hello
I'm in the SEO section, I get 7 documents that don't have a meta description. Why I can't see problematic page links?  
Thanks.

**Comment by patrickhulce** [comment]
Thanks for filing @Ehud-Simhi but I'm not quite sure what you're asking. Do you have a public URL for us to look at or a copy of the report that demonstrates this issue?

**Comment by Ehud-Simhi** [comment]
Hi.
On the-  “SEO-->Failed Audits-->Document does not have a meta description”
I’m not spouse to see a link to the “Failed” page?

Thanks.

[cid:image001.png@01D3929C.4987DAF0]




[cid:image004.png@01D14230.85ECB100]

Ehud Simhi, SEO-DACH TEAM
• Phone: +972-54-447-7699  • Skype: ehudsimhi@gmail.com<mailto:ehudsimhi@gmail.com> • Email: ehud.s@webpals.com<mailto:ehud.s@webpals.com> • Website: www.webpals.com

**Comment by patrickhulce** [comment]
No you won't see different URLs there. The "failed page" is the page that you audited. Do you have a report or URL that demonstrates the issue you're describing?

**Comment by Ehud-Simhi** [comment]
Thanks
I thought I can get all the data per domain and not per page url

[cid:image004.png@01D14230.85ECB100]

Ehud Simhi, SEO-DACH TEAM
• Phone: +972-54-447-7699  • Skype: ehudsimhi@gmail.com<mailto:ehudsimhi@gmail.com> • Email: ehud.s@webpals.com<mailto:ehud.s@webpals.com> • Website: www.webpals.com
