### ISSUE TITLE
Lighthouse hangs indefinitely on "Loading page & waiting for onload"

### ISSUE THREAD

**Issue by nhoizey** [GoogleChrome/lighthouse#4287]
I'm using Chrome 63.0.3239.132 and testing with both the native audit and Lighthouse extension version 2.8.0. I'm using a profile with no other extension.

The "Progressive Wep App" test hangs indefinitely on the "Loading page & waiting for onload" step on this page (and all pages of my site): https://nicolas-hoizey.com/2017/01/how-much-data-should-my-service-worker-put-upfront-in-the-offline-cache.html

## Here are the options

Native audit:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/78213/35088265-8d28147c-fc33-11e7-911a-e15c23da907c.png">

Extension:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/78213/35087838-e007231a-fc31-11e7-8b8c-0c8662d5f866.png">

## Here's where is hangs

Native audit:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/78213/35088241-757c7066-fc33-11e7-8769-c9ca75a46c0b.png">

Extension:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/78213/35087900-0b56126a-fc32-11e7-97aa-3dc449b0f76c.png">

I already opened a similar issue 6 months ago (#2655), but it has been closed has a duplicate to #2784, which is still open.

I first thought the issue came from using HSTS, but @paulirish states in #2465 (and #2784) that the issue with HSTS has been fixed.

I don't think my issue is one of the 4 remaining:

1. Server failure with initial request URL
1. Server doesn't offer HTTP
1. about:blank
1. No document request found

How can I help find where this issue comes from?

**Comment by patrickhulce** [comment]
Thanks for (re-)filing @nhoizey and for the thorough research into existing issues! This definitely looks distinct from those, so we'll have to dig in here a bit.

**Comment by nhoizey** [comment]
@patrickhulce thanks!

**Comment by patrickhulce** [comment]
So turns out this is a bug with our `start-url` gatherer hanging, not actually the page loading as in #2784. I'm working on a PR now 👍
