### ISSUE TITLE
image naturel aspect ratio

### ISSUE THREAD

**Issue by tomtompy** [GoogleChrome/lighthouse#4288]
Hi,

I don't understand why LightHouse find image ratio is wrong. Search in HTML or CSS ? 
What's wrong in this page :
https://jenseign.com/a-propos/
I remove header -> wrong ratio
I remove post img -> wrong ratio
…

Any idea ?

**Comment by patrickhulce** [comment]
@tomtompy are you running Lighthouse in Chrome stable? 

There was a bug that was fixed in 2.6 where the audit always failed (#3551). Try running the audit with the extension, Chrome Canary, or the CLI.
