### ISSUE TITLE
Offscreen Images

### ISSUE THREAD

**Issue by compositor2** [GoogleChrome/lighthouse#4300]
Hi,

I just started using Lighthouse and think it's great, however one potential problem I have noticed is; I am serving images with a data-src attribute and later using the values to update a src attribute that is created on the fly.

For some reason Lighthouse is saying I should consider Lazy Loading but I was of the view that this technique is rather common.

**Comment by patrickhulce** [comment]
Thanks for raising this @compositor2! Do you have a public URL that we could take a look at? Regardless of the technique used, Lighthouse will still flag any images that are loaded before "first interactive" which may be why you're seeing this.
