### ISSUE TITLE
SVGs - Image displayed sizes should match their natural aspect ratio

### ISSUE THREAD

**Issue by 2kool2** [GoogleChrome/lighthouse#4315]
Why is this warning applied to SVGs?
Neither the viewbox attribute, nor width and height, make any difference.
Does it not defeat the purpose of using SVGs?
For example this page only uses SVGs: https://websemantics.uk/

Could the reported message be amended to be either more accurate or more descriptive?

**Comment by kdzwinel** [comment]
This was fixed in #3722 and seems to be working correctly in 2.8.0:

<img width="1440" alt="screen shot 2018-01-21 at 02 00 01" src="https://user-images.githubusercontent.com/985504/35189622-093a68ea-fe4f-11e7-82a4-1884015e1d68.png">

**Comment by patrickhulce** [comment]
@kdzwinel nailed it, this should be fixed in latest LH use Chrome Canary, CLI, or extension for the updates :)
