### ISSUE TITLE
Feature request: Export to CSV for Performance / Opportunities / Optimize image / View Details

### ISSUE THREAD

**Issue by Andrew-Cottrell** [GoogleChrome/lighthouse#4325]
In _Chrome Audits / Performance / Opportunities / Optimize image / View Details_, I can see extracts of the URIs of non-optimized images, but am unable to access the full URIs. This makes providing a list of those images that should be optimised very hard to do. It would be extremely useful if it was possible to export the table as a CSV file (ideally Microsoft Excel compatible).

**Comment by paulirish** [comment]
duping into #4481
