### ISSUE TITLE
Add PNG support to optimize-images

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#4334]
Currently optimized images gatherer re-encodes as JPEG and WebP but not PNG. We could add coverage for PNG.

**Comment by connorjclark** [comment]
Is this still relevant?

**Comment by patrickhulce** [comment]
Yeah still relevant and it would be really nice to have, just harder to do since it involves protocol updates.

**Comment by connorjclark** [comment]
`uses-webp-images` audit uses OptimizedImages artifact (the webp part of the artifact), and `uses-optimized-images` uses the same thing but looks at the jpeg size estimation ... Why are there two? Seems like currently both audits could show the same image resource... do we really want a third audit such that we could recommend an image be png, webp, and jpeg?

if the user keeps following the advice of one audit eventually they should reach a local minimum and all these audits would stop alerting on that image, but this doesn't seem ideal.

FYI seems the protocol already supports png. https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/inspector/inspector_audits_agent.cc;l=91;drc=ee9e7e404e5a3f75a3ca0489aaf80490f625ca27

**Comment by patrickhulce** [comment]
> Why are there two?

One is about converting to a format that is difficult for users to consume, and until very recently had extraordinarily poor browser support. Most Lighthouse users tended to dismiss it entirely as something they won't work on.

The other is about tuning settings on a format you are already using because it's bloated. It's something that should always be fixed and folks tended to respond to it quite well.

> do we really want a third audit such that we could recommend an image be png, webp, and jpeg?

We would never recommend converting a JPEG or WebP to PNG, this would just be for GIF -> PNG and PNG reencoding optimization. I think it's much lower priority than all the other image-based stuff we do though, which is why it's just sat here. IIRC I filed this because we were finding everything that old PSI did that Lighthouse didn't do. IMO, we would be better off spending our efforts updating the WebP audit and considering an AVIF one first before doing this even if it would be nice to have :)

> FYI seems the protocol already supports png. https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/inspector/inspector_audits_agent.cc;l=91;drc=ee9e7e404e5a3f75a3ca0489aaf80490f625ca27

Oh wow, I forgot I did this 😆

**Comment by adamraine** [comment]
> IMO, we would be better off spending our efforts updating the WebP audit and considering an AVIF one first before doing this even if it would be nice to have :)

What needs to be updated on the WebP audit? Are you saying AVIF would have its own audit?

**Comment by patrickhulce** [comment]
> What needs to be updated on the WebP audit?

Some strings to stop mentioning JPEG-XR and JPEG2000 now that WebP has broad cross-browser support.

> Are you saying AVIF would have its own audit?

I think so, but we should discuss it. I think AVIF is in the same position WebP was for the past several years (Limited browser support, very unconsumable and more difficult to implement, very long encoding times, low image CDN support, etc). For the same reason as earlier, it might make sense to segment the audits on reasonableness of implementation to avoid dismissal of WebP as an option.

**Comment by patrickhulce** [comment]
We want modern-formats audit to flag PNGs that are inefficient when compared to the WebP version (we think that might already be happening, if so can close).

**Comment by patrickhulce** [comment]
Yep, PNGs work as expected with uses-modern-formats 👍
