### ISSUE TITLE
SEO: Recognize rel="canonical" HTTP header

### ISSUE THREAD

**Issue by laukstein** [GoogleChrome/lighthouse#4343]
https://support.google.com/webmasters/answer/139066 says

> If you can configure your server, you can use rel="canonical" HTTP headers (rather than HTML tags) to indicate the canonical URL for non-HTML documents such as PDF files.

Lighthouse v2.8.0 ignores the **Link** header and shows SEO error 

> Document does not have a valid rel=canonical

Expected to check both, HTML <link> tag and HTTP Link header.

**Comment by kdzwinel** [comment]
Thank you for reporting! Canonical audit [does check the Link header](https://github.com/GoogleChrome/lighthouse/blob/bd499b3b597b90dcf773ba7b1dd28314bf531da7/lighthouse-core/audits/seo/canonical.js#L86-L91), so I'm not sure what is going on 🤔 Can you please share the URL, or the response headers, for which you are getting this false negative?

**Comment by laukstein** [comment]
It seems now fine in v2.8.0, would shows inn this case

> Points to a different domain (http://example2.com/)
