### ISSUE TITLE
Query on font-size check

### ISSUE THREAD

**Issue by benbrowning** [GoogleChrome/lighthouse#4348]
I am running lighthouse on a primarily desktop app, which follows google's material design guidelines (which specify a 14px body copy size). Lighthouse is telling me that 100% of my text is too small and should be a minimum of 16px. Given that Google's own apps such as Inbox, Drive, Docs, Calendar etc use smaller font-sizes than this, is there a reason for this differing advice?

**Comment by kdzwinel** [comment]
Thanks for reporting! We are considering changing these values. /cc @rviscomi

**Comment by rviscomi** [comment]
Note that this is mobile-specific advice. But yes, we are looking to calibrate the audit to balance legibility with consistency.

**Comment by svivian** [comment]
I wonder if it's worth scaling the scores with the font sizes? For example, say we have 70% of the text at 16px and 30% at 14%. That is surely much better than all of the text being 10px, right? Yet both appear to give you a score of 0/10.

Perhaps something like: if 75% of the text is at 16px you get 10/10 (current behaviour). If that fails, then if 75% of the text is at 14px or above you get 5/10.

**Comment by foiseworth** [comment]
FYI https://github.com/GoogleChrome/lighthouse/pull/4550

**Comment by paulirish** [comment]
Fixed in #4550
