### ISSUE TITLE
Interactive metric is wrong

### ISSUE THREAD

**Issue by armandn** [GoogleChrome/lighthouse#4365]
I have a web app that also has 2 AdSense banners above and below it.
Lighthouse says that First Interactive is 11.8 seconds, which is way out of whack even based on the screenshots. Basically the app becomes available upon First Meaningful Paint, at 3s.

I'm attaching a screenshot:
![untitled-1](https://user-images.githubusercontent.com/15320153/35434592-62867c3c-0290-11e8-8857-d0bae3cf2833.jpg)

**Comment by armandn** [comment]
Also, interestingly, if I remove the(standard) AdSense code and a Facebook Like button, the situation changes dramatically:
![untitled-1](https://user-images.githubusercontent.com/15320153/35438626-ec2a40c2-029f-11e8-8ec4-c2c654871d06.png)

I will experiment more with these libraries, but Lighthouse shouldn't wait for them anyway, since the page is clearly interactive long before.

**Comment by pedro93** [comment]
Lighthouse tests a page in a mobile scenario where CPU and Network are throttled [here is the doc.](https://github.com/GoogleChrome/lighthouse#how-does-lighthouse-use-network-throttling-and-how-can-i-make-it-better) 
When you say that
> Basically the app becomes available upon First Meaningful Paint, at 3s.

Is this in a mobile device as well?

**Comment by armandn** [comment]
You can see in the screenshots that the interface appears (and it's usable/clickable) at around 2.5-3s. (just after the blue splashscreen is hidden). 

I tested on an actual device (a midrange Samsung Galaxy A3) over a 4G connection at the site/app became usable after ~2 seconds (cleared cache). The server is in the US, I tested from Europe.

Anyway, even disregarding the actual device, why does Lighthouse assume the the site is not interactive until AdSense and Facebook have fully loaded (and possibly even after), even though the interface is visibly functional?

**Comment by patrickhulce** [comment]
@armandn interactivity is based on whether all potential input events could start to be handled in under 50 ms. See the relevant snippet and explainer 

https://github.com/GoogleChrome/lighthouse/blob/c225d0189f4ffc945168aff31523a20e7c6342ab/lighthouse-core/gather/computed/first-interactive.js#L25-L50

I didn't see a URL for your site, but I'm guessing that FB/AdSense have long-running JavaScript that delay interactivity. You can explore the impact of main thread activity in your page in the "Performance" tab in DevTools (example below, JS execution is in yellow).

![image](https://user-images.githubusercontent.com/2301202/35465099-90ae328a-02ae-11e8-8d89-5c9f724c7236.png)

**Comment by exterkamp** [comment]
This was based on the beta version of interactive, and I think @patrickhulce answered this pretty well.  Closing now, but feel free to reopen if another question comes up!
