### ISSUE TITLE
Create Lighthouse tests for browser compatibility

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/lighthouse#4377]
Recently, we had an MDN product advisory board meeting with many browsers attending.

One of the action items out of that meeting was to investigate the possibility of browser compatibility tests in Lighthouse. 

I realize there's a lot of fluidity to such a proposal. So in this issue, let's open it up for discussion.

**Comment by pedro93** [comment]
Related to #2406, as far as I know this is currently limited to browser's inter-compatibility at the debugging protocol level.

**Comment by patrickhulce** [comment]
I think this might be a bit different from #2406 @pedro93. @Meggin you're talking about checking for page features/issues that could cause cross-browser problems correct? 

I love this in theory. Though in some cases, the bleeding edge advice we give is in direct contradiction to this, depending on how far you take "cross-browser" to mean. Will need to be balanced for sure.

**Comment by paulirish** [comment]
We could detect cases where they're not using the right CSS prefixes. Webhint does something like this: https://webhint.io/docs/user-guide/hints/hint-compat-api/#hints (click into each of the four)

However in our experience, we don't see these as the bigger problems. 

The major problem is when a UA sniff is used to turn off a feature or show a "use a different browser" prompt. We don't have a reliable way to evaluate this. (We're not in the position to use NLP to see if a given div has a suggestion to change browsers, etc :)
