### ISSUE TITLE
screenshot gather/save broken

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#438]
[this line](https://github.com/GoogleChrome/lighthouse/blob/487744ec1da735715b0c5607592c7b299f655f4d/lighthouse-core/lib/asset-saver.js#L63) is resulting in `var shots = undefined;` in the saved *.screenshots.html, I assume because the artifact is actually on `artifacts.Screenshots`

**Comment by paullewis** [comment]
It's `artifacts.ScreenshotFilmstrip`
