### ISSUE TITLE
Lighthouse broken when CSP connect-src 'none'

### ISSUE THREAD

**Issue by laukstein** [GoogleChrome/lighthouse#4386]
Chrome v64 DEV Tools Audits hangs forever without returning result.
Lighthouse v2.8.0 extension would throw error:

> VM204:5 Refused to connect to 'http://example.com/' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
>
> \_\_nativePromise.resolve.then.\_ @ VM204:5
> Promise.then (async)
> (anonymous) @ VM204:5
> wrapInNativePromise @ VM204:3
> (anonymous) @ VM204:21
> VM204:5 Refused to connect to 'http://example.com/' because it violates the document's Content Security Policy.

`Content-Security-Policy: default-src 'none'; connect-src 'self'` would solve the issue, but I think Lighthouse mustn't break and depend on **connect-src 'self'**.

Once was open related issue https://github.com/GoogleChrome/lighthouse/issues/2319

**Comment by laukstein** [comment]
The same error also in `getRobotsTxtContent` (Lighthouse v3.0.3) resulting "robots.txt is not valid"

> Lighthouse was unable to download your robots.txt file

    Refused to connect to 'https://example.com/robots.txt' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

    getRobotsTxtContent @ VM1773:7
    __nativePromise.resolve.then._ @ VM1773:17
    Promise.then (async)
    (anonymous) @ VM1773:5
    wrapInNativePromise @ VM1773:3
    (anonymous) @ VM1773:31

![grabilla g10024](https://user-images.githubusercontent.com/183966/43094409-79f2f276-8ebb-11e8-9dae-70859bf103a2.png)

**Comment by laukstein** [comment]
Any ETA when this will be fixed.
https://web.dev/measure breaks on same error showing invalid message

![grabilla em5576](https://user-images.githubusercontent.com/183966/54479998-061f8280-482c-11e9-871f-c51809fdd561.png)

You mustn't say the error is in customer side when actually is Lighthouse incompatibility bug.

**Comment by patrickhulce** [comment]
No ETA, this requires fetching outside the context of the page which is not something Lighthouse can do in most environments at the moment.

**Comment by connorjclark** [comment]
#9458 would help?

**Comment by lukiffer** [comment]
It took a while to discover this issue and FWIW, a more descriptive error message would be helpful when the CSP blocks the request as opposed to an HTTP error response.

At a minimum, it would be helpful to add to the [documentation](https://web.dev/robots-txt/) for this check under "Common errors include:"

**Comment by patrickhulce** [comment]
This has been fixed by #12423 🎉

**Comment by jitendravyas** [comment]
I am on chrome canary 93 and still having this issue

**Comment by adamraine** [comment]
@jitendravyas do you have a public URL you can share?

**Comment by jitendravyas** [comment]
yes. i tested for https://vwo.com

**Comment by adamraine** [comment]
The issues reported in Lighthouse are related to SameSite cookie, not CSP. They are hidden by default in the DevTools issues panel:

<img width="980" alt="Screen Shot 2021-06-21 at 1 35 29 PM" src="https://user-images.githubusercontent.com/6752989/122804172-8d72c080-d295-11eb-8e71-e21d9c467846.png">

You can show them by clicking the "Include third-party cookie issues" checkbox.

**Comment by bogdy** [comment]
just add ["connect-src 'self'" CSP rule. I have tested for https://bogdanbiris.com
