### ISSUE TITLE
Bug: "Does not use HTTPS" when HTTPS-URL contains basic auth credentials

### ISSUE THREAD

**Issue by Schepp** [GoogleChrome/lighthouse#4389]
Lighthouse 2.8.0: When testing an URL that is HTTPS and that contains basic auth credentials, the PWA test seems not to recognize **relative resources** as being served over HTTPS. Therefore it throws an "Does not use HTTPS: [x] insecure requests found", as can be seen on the following result screen:

![image](https://user-images.githubusercontent.com/135141/35564335-1d4c3634-05ba-11e8-95f1-572b70bc2350.png)

**Steps to reproduce:**

1. Launch `lighthouse https://salzundbrot.com --view`
2. Launch `lighthouse https://test:test@salzundbrot.com --view`
3. Compare the results of the "Uses HTTPS" PWA test

**Comment by brendankenny** [comment]
not sure what was going on here (it should be noted these audits are testing two different things: whether the page will be redirected from http->https vs if all the resources of the page were loaded over https), but all seems good with the site today, so I'm going to close :)
