### ISSUE TITLE
Move any clientside JS functions to their own files

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#4395]
I noticed that during the `yarn coverage` run, there'd always be a timeout. ([example](https://travis-ci.org/GoogleChrome/lighthouse/jobs/334950696#L886)). Turns out its the cli's `run-test.js` that does full roundtrip of lighthouse. Digging in, it timed out in `driver.js` waiting for CPU idle... and eventually hits the 45s time limit.

So the current impact of this bug:
* incorrect code coverage stats for CLI
* an extra ~42 seconds of build time

----

## Details

I poked at the behavior and turns out the code running via `driver.evaluateAsync` has istanbul instrumentation:

![image](https://user-images.githubusercontent.com/39191/35600430-b26337f4-05e2-11e8-900b-bcb372b30920.png)

Also amusingly https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md says adding `istanbul ignore next` doesn't exclude it from instrumentation. So it's fair to assume istanbul instrumentation will break most of our `evaluateAsync` calls.

### Bonus details
1. We had a typo: `instanbul` -> `istanbul`
1. istanbul's `ignore next` regex doesn't match the statement if it's at the end of a jsdoc (or other flowerbox) comment. [it has to be at the start of a comment.](https://github.com/gotwarlost/istanbul/blob/bc84c315271a5dd4d39bcefc5925cfb61a3d174a/lib/instrumenter.js#L16)
1. Fixing both of these didn't fix the problem. But you can imagine I expected them to. :disappointed:

## Solutions

* A) Move any clientside JS functions to their own files. Maybe `xxxx-clientside.js` and then we can add a `--exclude *-clientside.js` to the `istanbul cover` command.
* B) Switch to using v8/devtools code coverage. Right now, the leading impl of this, [c8](https://github.com/bcoe/c8), only creates istanbul lcov json files. The project needs to mature a bit before it'll be a real option for istanbul/nyc. But I'm sure it will. 
    * Regardless, this will only work in node 9, which we're about to stop testing on travis. 😁 
* C) A hackier quick fix which I'm about to PR... 😛

**Comment by paulirish** [comment]
As discussed in #4396, the next action is to implement solution A.

> it might be nice to collect all our client-side run functions in a single place so it becomes clear what gets run where

**Comment by tollmanz** [comment]
As a nice side benefit of solution A, I've found that audits that inject code originating from a separate file are much easier to understand that ones that stringify code in the same file and inject it. I think it helps with the context switch and makes it easier to understand what code is meant for the server and what code is meant for the client.

**Comment by exterkamp** [comment]
page-functions.js is where this is now!
