### ISSUE TITLE
lighthouse isn't creating output file when called by puppeteer

### ISSUE THREAD

**Issue by jars99** [GoogleChrome/lighthouse#4411]
I'm using puppeteer to do an automated logged-in page test.  I can't seem to get lighthouse to write out to a file.  

Here's an example of how I'm calling lighthouse:

```javascript
var lhFlags = {logLevel: 'info', outputPath: './report.json', output: 'json', port: url.port};
var lightResults1 = await runLighthouse(lhRunSite, lhFlags, perfConfig);
console.log(lightResults1);
```
I see the output on the console, but I don't get any output file.  

Everything works as expected when I run lighthouse directly, but there seems to be a bug when calling it with puppeteer.

**Comment by patrickhulce** [comment]
Thanks for filing @jars99, those flags aren't available from programmatic usage since it's fairly trivial to add a `fs.writeFileSync('./report.json', JSON.stringify(lightResults1))`, #3587 tracks better documenting this fact
