### ISSUE TITLE
extension: add option to preserve localStorage

### ISSUE THREAD

**Issue by dskloetg** [GoogleChrome/lighthouse#4419]
I tried Chrome's Audit feature for the first time to find out what it is and it destroyed my localStorage without any warning. If I want to destroy my localStorage before running an audit, I can do that myself. But if I want to run an audit with localStorage in tact, there is no way to do that.

1. Destroying localStorage without even a warning causes data loss and is unacceptable.
2. Even with warning, destroying localStorage makes it impossible to audit with localStorage in tact, while not destroying localStorage keeps all options open.

**Comment by patrickhulce** [comment]
related [crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=806488) #1418 #2599

**Comment by MisterTicot** [comment]
I confirm this is annoying. As a developper I'm actually using the websites I'm coding on a daily basis. I think that the least one can do to ensure all works fine. I have no choice using another browser to do so. It could be argued that's a feature as it force me to navigate my websites with two different browsers. Also a good reset once in a while allow to check that everything is fine for first-time users :D.

No but seriously, as that tool is here to help us producing better code it seems appropriate to fix that quite annoying bug. I can't tell were a discussion would be needed, Saving the datas aside and load them back when auditing is finish shouldn't be too much challenging isn't it?

(By the way thank you for this tool it's good to have anyway :+1: )

**Comment by benschwarz** [comment]
> Even with warning, destroying localStorage makes it impossible to audit with localStorage in tact, while not destroying localStorage keeps all options open.

If you're using Lighthouse on the command line, there's a flag that will keep your storage intact, `--disable-storage-reset`.  If you're using the devtools edition there's a checkbox before you conduct the audit: 

<img width="837" alt="image" src="https://user-images.githubusercontent.com/924/43052775-069be4d0-8e6c-11e8-8e42-25e81d96fa51.png">

As for the extension, I'm not sure. I haven't used it in quite some time.

**Comment by Hoten** [comment]
Better captured here, duping: #2599
