### ISSUE TITLE
Incorrect Audit Information 

### ISSUE THREAD

**Issue by TomLeVine** [GoogleChrome/lighthouse#4429]
My site has a mobile version on a subfolder

mysite.com/m 

that page has a rel canonical link pointing to the desktop version

mysite.com

The SEO audit says thats a 'failed audit' because document does not have a valid rel=canonical. This is not accurate.

**Comment by rviscomi** [comment]
Thanks! Merging this with https://github.com/GoogleChrome/lighthouse/issues/4295.
