### ISSUE TITLE
Recalibrate the legible font sizes audit

### ISSUE THREAD

**Issue by pierreboulanger** [GoogleChrome/lighthouse#4448]
Apparently 85% of my site is not lisible because the font-size is smaller than 16px. Or the font size is almost everywhere 18px...and it is lisible on mobile

**Comment by rviscomi** [comment]
Hi @pierreboulanger thanks for the bug report. Could you share your website so I can reproduce the issue? Thanks!

**Comment by pierreboulanger** [comment]
Hi @rviscomi, I double checked and I have a lot of text at 15px so the audit was not wrong in the end. But personnaly, I feel that 15px still is a lisible font-size for mobile (except maybe for 50+ yo people with eyes problem). 

Hope I'm helping :)

**Comment by fchristant** [comment]
I too have run it on a few websites that I would consider perfectly legible, and seeing scores reporting > 90% is not legible. Maybe a correct number based on the technical treshold chosen, but if very typical websites would get these kind of awful scores, there's a risk the audit loses value. 

Case in point, the very text you're reading right now is 14px on desktop, 15px on mobile. Would you consider all of Github not legible :)

**Comment by rviscomi** [comment]
@kdzwinel let's change the calibration of the font sizes audit to be a lot more permissive. We'll follow up with this audit one more time after conducting some UX research to get a better idea of what users expect in terms of legibility.

**Minimum legible font size:** 12px (was 16px)
**Minimum percent legibility:** 60% (was 75%)
