### ISSUE TITLE
TypeError: Cannot read property 'src' of undefined

### ISSUE THREAD

**Issue by wardpeet** [GoogleChrome/lighthouse#4464]
https://sentry.io/google-lighthouse/lighthouse/issues/454184109/

```
TypeError: Cannot read property 'src' of undefined
  File "/usr/lib/node_modules/lighthouse/lighthouse-core/gather/gatherers/fonts.js", line 149, in loadedFonts.map.fontFace
    fontFace.src = fontFaceItem.src || [];
  ?, in Array.map
  File "/usr/lib/node_modules/lighthouse/lighthouse-core/gather/gatherers/fonts.js", line 147, in Promise.all.then
    return loadedFonts.map(fontFace => {
  File "internal/process/next_tick.js", line 135, in process._tickDomainCallback

TypeError: Cannot read property 'src' of undefined
```

**Comment by wardpeet** [comment]
some websites that use @import are not tracked by the css rules so the fontface rules are empty and it won't match the correct urls. I have a quickfix ready and another fix to make sure we also look into imported stylesheets.

**Comment by paulirish** [comment]
> some websites that use @import are not tracked by the css rules so the fontface rules are empty and it won't match the correct urls. I have a quickfix ready and another fix to make sure we also look into imported stylesheets.

I looked into this and didn't see @import'd stylesheets within document.styleSheets. :)  What are you thinking for a fix?
