### ISSUE TITLE
Lighthouse 2.9.0 Chrome extension is broken

### ISSUE THREAD

**Issue by ChrisJohn1990** [GoogleChrome/lighthouse#4466]
Hi,
Lighthouse does not stop showing "Lighthouse is debugging this browser" I get no report either.

Anyone else facing this issue?

**Comment by kdzwinel** [comment]
Thanks for a report. Can you please let us know:
- how are you running Lighthouse (extension, from DevTools, from console)?
- what version of Lighthouse are you running?
- what page are you trying to audit?
- does report pass if you disable 'accessibility' category?

**Comment by ChrisJohn1990** [comment]
Hi,

Replying point by point

1. Extension
2. 2.9.0
3. www.evolveback.com & www.coorgmisty.com
4. I do not have that option

Regards

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by coliff** [comment]
I too am having issues with the new extension from webstore (2.9.0). I'm on Windows 10 64bit, and Chrome  64.0.3282.140.
If I run the audit on google.com the URL changes to:
```
data:text/html,<!doctype html>%0A<html>%0A<meta charset="utf-8">%0A<meta name="viewport" content="width=device-width">%0A<title>Resetting page...</title>%0A<style>%0A  html, body {%0A    height: 100%;%0A    background: hsl(231, 99%, 99%);%0A    overflow: hidden;%0A  }%0A</style>%0A<body>
```
and it never completes.

I've also tested on my iMac (High Sierra) with latest Chrome and the latest Chrome extension update (2.9.0) and can no longer get it to complete at all. Stuck as 'Initializing'. Also tested in Incognito mode with no other extensions and still no joy.

**Comment by kdzwinel** [comment]
Sorry everyone, it looks like version 2.9 of the extension is broken. We are working on a fix.

**Comment by ChrisJohn1990** [comment]
Google Should pay me for this shiz.

Thanks Konrad!

**Comment by paulirish** [comment]
**I've shipped a new chrome extension version to CWS:  _2.9.0.280_**

It's a revert back to 2.8.0, while we sort out the issue. (@kdzwinel did most of the investigation already in #4470)

Holler if you're still encountering problems after you have 2.9.0.280!   Thanks very much everyone for reporting. Appreciate it.

Oh, and for @ChrisJohn1990: 💰💰💰💰💰 😜

**Comment by tvld** [comment]
_-   how are you running Lighthouse (extension, from DevTools, from console)?_
   Starting the Lighthouse extension from Chrome and Chromium. Tried both on Ubuntu 17.10 and Windows 8, both same freeze.
_-    what version of Lighthouse are you running?_
2.9.0
_-    what page are you trying to audit?_
breaks on any page, but focussing on https://www.lorinthe.com
_-    does report pass if you disable 'accessibility' category?_
No. Worse it freezes with **no category checked** even! 

**Settings**
![screenshot from 2018-02-08 17-56-48](https://user-images.githubusercontent.com/986182/35986488-78ebf146-0cf9-11e8-8319-8712ce4cfc7b.png)
**Forever freeze Result:**
![screenshot from 2018-02-08 17-55-39](https://user-images.githubusercontent.com/986182/35986490-790cb46c-0cf9-11e8-85e3-f4bea2abcad6.png)

**Comment by arjun0108** [comment]
#  IMPORTANT 
@kdzwinel  Its working fine, when using it with **_inspect element_**. **BUT not, when generating report directly through the extension icon**.

**Comment by kdzwinel** [comment]
@tvld @arjun0108 thanks for reporting. As Paul mentioned above the issue was fixed, please make sure that you have version `2.9.0.280` of the extension. (if needed, you can force update the extension as described [here](https://www.howtogeek.com/64525/how-to-manually-force-google-chrome-to-update-extensions/))

**Comment by tvld** [comment]
@kdzwinel  Thanks... can confirm that 2.9..0.280 is working again ;-) ))

**Comment by paulirish** [comment]
Killer. thanks for the update.

(And yes, `All image optimizations failed` is a separate issue. just filed it as #4483)

**Comment by derekshull** [comment]
Is `2.9.0.280` available for the npm package too?
