### ISSUE TITLE
Lighthouse is not Generating Any Report

### ISSUE THREAD

**Issue by taimoor1982** [GoogleChrome/lighthouse#4469]
The lighthouse is not generating any report since yesterday. Please help me.

See the snapshot below for better understanding:

![snaphsot](https://user-images.githubusercontent.com/36256897/35967782-be574afc-0ce3-11e8-9d63-bac4facdfbe8.jpg)

**Comment by tvld** [comment]
Same problem here, full freeze ``Lighthouse is debugging this browser```  Same on Ubuntu, Windows etc.

**Comment by GijsMolsbergen** [comment]
Having the same problem here

**Comment by wardpeet** [comment]
closing :) duplicate of #4466
