### ISSUE TITLE
Canonical URL domain with or without slash

### ISSUE THREAD

**Issue by fchristant** [GoogleChrome/lighthouse#4473]
I'm checking out the new SEO audits (very welcome feature btw!) and had the following finding:

**Page URL (fabricated):**
https://www.abc.com

**Inside the page, canonical value is set to:**
https://www.abc.com/

In the audit, this is reported as an invalid canonical value, for pointing to another domain. 
That seems wrong to me, it's the same domain. The slash at the end does not make it a different domain.

**Comment by kdzwinel** [comment]
Thank you for reporting. This seems to be a duplicate of #4440 . Audit does ignore the slash, the issue seems to be a bit more complicated - I'm looking into this.

**Comment by fchristant** [comment]
Thanks. Sorry, wasn't aware it was already reported. Closing this one.

**Comment by kdzwinel** [comment]
No worries, thank you for taking time to report this.
