### ISSUE TITLE
Connecting issue while run lighthouse inside a docker container

### ISSUE THREAD

**Issue by ganlanyuan** [GoogleChrome/lighthouse#4476]
Got the following issue when run lighthouse programmatically inside a docker container:
```
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:38055
(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Dockerfile
```dockerfile
FROM node:8-slim

# Install utilities
RUN apt-get update --fix-missing && apt-get -y upgrade

# Install latest chrome dev package.
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /src/*.deb

ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init

# Download latest Lighthouse from npm.
# cache bust so we always get the latest version of LH when building the image.
ARG CACHEBUST=1
RUN mkdir -p /home/chrome && \
    cd /home/chrome && \
    npm i lighthouse

# Add a chrome user and setup home dir.
RUN groupadd -r chrome && useradd -r -m -g chrome -G audio,video chrome && \
    mkdir -p /home/chrome/reports && \
    chown -R chrome:chrome /home/chrome

USER chrome

VOLUME /home/chrome/reports
WORKDIR /home/chrome/reports

EXPOSE 8080
```

Command:
```
node lh.js
```

lh.js
```javascript
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');
const ReportGenerator = require('lighthouse/lighthouse-core/report/v2/report-generator');
const log = require('lighthouse-logger');
const opts = {
  logLevel: 'info',
  output: 'html',
  chromeFlags: ['--show-paint-rects']
};

function launchChromeAndRunLighthouse(url, opts, config = null) {
  return chromeLauncher.launch({chromeFlags: opts.chromeFlags}).then(chrome => {
    opts.port = chrome.port;
    return lighthouse(url, opts, config).then(results =>
      chrome.kill().then(() => { return new ReportGenerator().generateReportHtml(results); }));
  });
}

launchChromeAndRunLighthouse('https://google.com', opts).then(results => {
  fs.writeFile('lighthouse/report.html', results, function(err) {
    if (err) { console.log(err); }
  });
});
```

**Comment by patrickhulce** [comment]
I don't have your setup replicated locally, so I can't tell for sure, but my best guess is that Chrome is not starting  properly because you don't have either `--headless` in your `chromeFlags` or a virtual display like `xvfb` setup. I'd try to debug without Lighthouse first (just starting Chrome with a remote debugging port and seeing if it starts successfully).

`google-chrome --remote-debugging-port=9222 --headless`

**Comment by ganlanyuan** [comment]
Still get the same error after add the `--headless` flag:
```javascript
const opts = {
  logLevel: 'info',
  output: 'html',
  chromeFlags: ['--show-paint-rects', '--headless']
};
```

**Comment by patrickhulce** [comment]
@ganlanyuan are you able to confirm that Chrome starts regardless of Lighthouse as I suggested?

If you can get Chrome working on its own and still have Lighthouse troubles we'll be happy to help :)

**Comment by ebidel** [comment]
I don't see a `CMD` or `ENTRYPOINT` in your dockerfile. How are you running the container?

These might be helpful:
https://github.com/ebidel/lighthouse-ci/blob/master/builder/Dockerfile
https://github.com/ebidel/lighthouse-ci/blob/master/builder/entrypoint.sh#L6

**Comment by ganlanyuan** [comment]
@patrickhulce thanks, will try it tmr and back to you.
@ebidel Hi, yes, I actually copied form you repo and run the image with a `docker-compose.yml` file.

**Comment by ganlanyuan** [comment]
I got the following error when do `google-chrome --remote-debugging-port=9222 --headless`:
```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Failed to generate minidump.
```

**Comment by ganlanyuan** [comment]
This was fixed after I used this command to start the container:
```
docker run -dit -p 8080:8080 --rm --name lighthouse_ci --cap-add=SYS_ADMIN lighthouse_ci
```
but got another error when I execute `google-chrome --remote-debugging-port=9222 --headless` in the container:
```
[0213/214617.885864:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9222/devtools/browser/d7c28a8f-8955-464a-bb12-4f2b35bb45c8
Fontconfig warning: "/etc/fonts/fonts.conf", line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
```

**Comment by patrickhulce** [comment]
`DevTools listening on ws://127.0.0.1:9222/devtools/browser/d7c28a8f-8955-464a-bb12-4f2b35bb45c8` is a great sign though, that likely means Chrome was able to get somewhat going at least

I'm assuming you also found and are trying out [some](https://github.com/jessfraz/dockerfiles/issues/65) of [these](https://github.com/karma-runner/karma-chrome-launcher/issues/125) [other](https://github.com/jessfraz/dockerfiles/issues/222) [fixes](https://stackoverflow.com/questions/43665276/how-to-run-google-chrome-headless-in-docker)?

**Comment by ganlanyuan** [comment]
@patrickhulce thanks,
Even through I still get errors on launching Chrome, but I'm able to run lighthouse programmatically inside docker now.
