### ISSUE TITLE
Make it easier to run a specific audit category from CLI

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#4478]
My use case is to run only the SEO audits from the LH CLI. Disabling non-SEO audits would help speed up the test. Additionally, disabling irrelevant things like network throttling could help with audit performance.

Strawman proposal: `--audit_categories=seo`, `--audit_categories=seo,perf`

cc @kdzwinel

**Comment by patrickhulce** [comment]
yeah would be fixed by the broader effort to unify the config and CLI settings which I've got a branch in progress to do :) it would look like

`--only-categories=seo --only-categories=performance --only-audits=works-offline` which would be equivalent of

```
{
  extends: 'lighthouse:default',
  settings: {
    onlyCategories: ['seo', 'performance'],
    onlyAudits: ['works-offline'],
  }
} 
```

**Comment by rviscomi** [comment]
@patrickhulce just checking, what's the status of your "broader effort"? Is this issue obsolete yet?

**Comment by patrickhulce** [comment]
Not obsolete yet, making progress in that direction with #4676 and some stuff we plan in #4333 :)

**Comment by lluia** [comment]
Hi 👋🏻

I was trying the flag `only-categories`  in your **CLI**, and I noticed the following format doesn't work:
```bash
ligthouse http://google.com --only-categories=performance,pwa,best-practices
```
but instead, it seems you support a much more tedious one:
```bash
ligthouse http://google.com --only-categories=performance --only-categories=pwa --only-categories=best-practices
```
Is there any scope/interest to change this? I would be happy to help with the change 🙋🏻‍♂️ 👨🏻‍💻 😊

**Comment by patrickhulce** [comment]
@lluia This is a built-in feature of yargs that does the repeated categories that way. How about you file an issue with the feature request for discussion, but I think we'd love your help :)
