### ISSUE TITLE
Investigate integration: sitespeed coach

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#448]
https://github.com/sitespeedio/coach
https://chrome.google.com/webstore/detail/coach-panel/olecfjmnejnkjipoicfpneceppjeaemo/

The results from paulirish.com: 
![image](https://cloud.githubusercontent.com/assets/39191/16144952/808c66cc-3476-11e6-8a38-2c854a0c18ec.png)

There's some nice stuff in here, so I'm sure we can leverage it, similar to our dependency on axe-core.

**Comment by wardpeet** [comment]
+1

**Comment by patrickhulce** [comment]
Not doing
