### ISSUE TITLE
Export from report to CSV

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#4481]
Suggested by https://twitter.com/SEO/status/961675925472665605

Is it possible to export Lighthouse results to Google Sheets? It begs the question how to arrange the results to fit the tabular format. For example, the first sheet could summarize the high level audit categories and their scores. Each subsequent sheet could be the individual audit category breaking down each audit and their results.

This would probably require authorizing Lighthouse to create a Sheet on the user's behalf. Maybe a more straightforward and portable option would be to export a raw CSV, which the user can open wherever they want?

**Comment by patrickhulce** [comment]
related #4325

**Comment by wardpeet** [comment]
Pwmetrics has this feature. Not sure it should be a lighthouse core feature though..

**Comment by paulirish** [comment]
Another usecase was the URLs in _Performance / Opportunities / Optimize image / View Details_

**Comment by paulirish** [comment]
fixed in #4912
