### ISSUE TITLE
All image optimizations failed

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#4483]
Found in audits like these:

```
Optimize images
Audit error: Required OptimizedImages gatherer encountered an error: All image optimizations failed

Serve images in next-gen formats
Audit error: Required OptimizedImages gatherer encountered an error: All image optimizations failed
```

This exception is in our top 10 on sentry. https://sentry.io/google-lighthouse/lighthouse/issues/408343828/

**Comment by patrickhulce** [comment]
We should definitely grab some of the URLs and take a look, but my guess is that these are mostly expected errors from ill-specified "images".

**Comment by tvld** [comment]
@patrickhulce https://www.lorinthe.com   ;)   

For now the error is there. We will report if we find a work-around, so to isolate.

**Comment by brendankenny** [comment]
I'm not seeing this at all in sentry anymore, so going to close for now. If folks are still running into this we can reopen or start a new issue.
