### ISSUE TITLE
Fonts gatherer can take a very long time

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#4486]
While debugging the offscreen images issue on https://feuerwehr-eisolzried.de/ I noticed `Fonts` gatherer took 13 seconds and https://us.norton.com/ took more than 60s (!!).

@wardpeet maybe we should put a timeout on that loadStylesheetWithCORS function? or find a way to do it over protocol without rerequesting if possible :)

**Comment by wardpeet** [comment]
Yeah I find a solution to make it faster. It's pretty slow when there are some CORS stylesheets. I'll fix that in a proper fix within the #4464 issue so we also load imported stylesheets

**Comment by patrickhulce** [comment]
SG! I'm also not sure what was going on haha, I've re-run both of those after adding some logging and now I can't get it to take more than 1s so maybe just something odd with my machine too 🤷‍♂️

**Comment by kdzwinel** [comment]
It's not just you 😉 I've run the extension quite a few times today and 'Fonts' was taking significant amount of time on non-trivial websites.

**Comment by paulirish** [comment]
fixed by #4488, we believe. let's reopen immediately if we're seeing Fonts gatherer take > 1000ms
