### ISSUE TITLE
move to requiring Node 6 when LTS

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#449]
With the release of 6.2.2, I think it may be time.
- Node 6 will be the [next LTS version](https://github.com/nodejs/LTS) (skipping 5)
- it will give us a [few more es6 features](http://node.green/) like
  - [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) (avoiding the `|| defaultValue` dance and especially eliminating the verbose cases of checking a value that may be falsy since default parameters always check against `undefined`)
  - [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) (allowing us to avoid noise like [this](https://github.com/GoogleChrome/lighthouse/blob/230cd56dc732ad951dabbcc872dc7a291cb091c3/lighthouse-core/driver/drivers/extension.js#L91-L94) and [this](https://github.com/GoogleChrome/lighthouse/pull/430/files#r67022456))
  - [`Array.prototype.includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)
  - [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) (which I'm a bit wary of because every person I've seen use it quickly starts abusing readability for the sake of cool destructuring, but there's no way up but through :)
- there are [no notable language changes in the pipeline for Node 7](http://node.green/) (sorry `**`), which means lighthouse devs can use node 6+ and any language feature used will be compatible with a node 6 baseline (modulo performance improvements). This has been a problem in a few PRs in the past, where someone running node 6 has to rewrite when their change breaks in testing on node 5. Only caveat here is `async`/`await`, which has enough demand that we may need to upgrade when that's turned on.
- I assume the new DevTools debugging? Is this going to be in 6 or skip to 7?

**Comment by wardpeet** [comment]
maybe add a .nvmrc file as well for the nvm users :)

**Comment by addyosmani** [comment]
> I assume the new DevTools debugging? Is this going to be in 6 or skip to 7?

I believe this is being skipped to 7

**Comment by paulirish** [comment]
I don't think we need to be in a rush here. A few folks who want to use Lighthouse are on v4 still, and v5 is a challenge for them.

Once LTS ships in october, we'll be in a better place for this sort of upgrade.  But until then, I'm in favor of staying with 5.

**Comment by brendankenny** [comment]
I'd be ok waiting on 6 until it hits LTS

**Comment by wardpeet** [comment]
@brendankenny @paulirish we have hit lts for node 6, should we move on?

**Comment by wardpeet** [comment]
i'll close this, we will move whenever we are ready :)

**Comment by brendankenny** [comment]
resurrecting this issue. I think we're ready to drop anything before v6.9. We don't want to go tooooo crazy with new features, but dropping older versions from Travis, dropping `$__node_harmony`, etc can proceed.

**Comment by brendankenny** [comment]
@XhmikosR hopefully this makes your life much easier :)

**Comment by XhmikosR** [comment]
Woo-hoo!

Looking forward to this as it will allow us to test everything on Windows.
Well, after we sort a couple of other minor issues :)

PS. Might be a good time to make sure the engines property is consistent in
all package.json files.
