### ISSUE TITLE
Question: Metric "Weights"

### ISSUE THREAD

**Issue by derekshull** [GoogleChrome/lighthouse#4501]
Looking through the API I see that there are weights for some of the metrics going from 0 to 5.  Can anyone speak to what the scale means?  Is it a 1 (being lowest priority) to 5 (being highest priority) scale with 0 being of no priority?  Or maybe 0 is the lowest priority?

**Comment by patrickhulce** [comment]
Each category score is a weighted average its composing audits. A weight of 0 means that the audit is not counted in the category's score at all. A weight of 5 means it is given 5x the impact of an audit with a weight of 1. You can read more about this in our [scoring documentation](https://github.com/GoogleChrome/lighthouse/blob/3e34af7c722e0a4dc9d1e46c1fac908b0ebde69b/docs/scoring.md) and try out our [scoring calculator](https://docs.google.com/spreadsheets/d/1dXH-bXX3gxqqpD1f7rp6ImSOhobsT1gn_GQ2fGZp8UU/edit?ts=59fb61d2#gid=0)

**Comment by derekshull** [comment]
Thanks @patrickhulce, very helpful!
