### ISSUE TITLE
Applying a 3rd party SSL Cert to a website in a multi-tenant environment w/no CSR access

### ISSUE THREAD

**Issue by ssparky9ss** [GoogleChrome/lighthouse#4505]
In the effort & spirit of sites across the web becoming secure (i.e., https://), my hosting provider has explained I must purchase a SSL Certificate from them only.  I cannot go to a 3rd party or CA, so I'm told.

While the technical challenges may have been true at some point, I'm told the reason is... They host a multi-tenant environment, so multiple tenants share the same public IP address as ours.  Therefore, purchasing my own certificate or trying to allow them to apply my 3rd party certificate is not feasible.  I get that.

Though I can manage my site's content, I do not have administrative access to any server and hence cannot generate a CSR.  Even if I could, I get their reasons.

On the one hand I understand the technical challenges and implications.  However, I find it difficult to believe the solution being proposing, is the only one.  Without evading or sacrificing security (for good reason), is there no way of circumventing the technical challenge(s) that face me by keeping this provider?

I am no webmaster and would like to think my lack of understanding of all the underpinnings & inter-workings would prevent from being forced down their path.  Maybe a solution exists, but would it not be possible to host a secure proxy webserver that could front end or redirect public traffic to/from my website that in essence allows my site to look or appear secure?  Maybe this is a no no but I'd like to understand what technically is or is not possible from an independent entity.  Can someone provide advice or direction?

Since this inquiry is not code related per se, if this is the wrong forum for such inquiries, please forgive me.  I was only hoping that such a forum could shed light.  Surely I cannot be the first to encounter this issue.

**Comment by Vhoakab84** [comment]
Thanks I was wondering and experiencing the same issue and could not find a solution either

**Comment by paulirish** [comment]
check out letsencrypt.

you shouldn't have to purchase a certificate through your hosting provider, but i understand why they want to convince you of that. ;)
