### ISSUE TITLE
Re-evaluate runtime perf thresholds 

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#4521]
For example mainthread-work-breakdown fails if work takes > 3s. Is that a reasonable result on all hardware, including production google-scale infra?

**Comment by patrickhulce** [comment]
I propose an alternative approach for this: we give the audit a score like we do for total byte weight. 

https://www.desmos.com/calculator/asrhnefjmn

100 <300ms
50 ~1500ms
20 ~3s
5 ~5s
 
![image](https://user-images.githubusercontent.com/2301202/36121860-5864f39a-0ffc-11e8-9352-fed0c22526d0.png)

**Comment by paulirish** [comment]
two separate outcomes from this:

1. **scoring/pass/fail of these audits:** we move them to be numeric rather than binary and apply a scoring curve like the above.
2. **handle different hardware:** we think its worthwhile to pursue CPU performance calibration, and use this for lantern's model

**Comment by paulirish** [comment]
> scoring/pass/fail of these audits: we move them to be numeric rather than binary and apply a scoring curve like the above.

We'll use this ticket

> handle different hardware: we think its worthwhile to pursue CPU performance calibration, and use this for lantern's model

reopening #820 to track that
