### ISSUE TITLE
custom configuration difficulties

### ISSUE THREAD

**Issue by KathiresanRamkumar95** [GoogleChrome/lighthouse#4526]
When I am using lighthouse programmatically, there is an only option in custom-config.js in passes field

> useThrottling:true

But actually I want ;
```
networkThrottling: Fast 3g;
cpuThrottling:4x slowdown;
deviceEmulation: disable
```

something like above.

Please give some examples to get the performance metrics value by given config.json what I am want.

Thank you !

**Comment by patrickhulce** [comment]
@KathiresanRamkumar95 those settings are currently controlled through flags, not the config (work is underway to unify the two I know it's a bit confusing right now)

to get the settings you want looks like

```js
const lighthouse = require('lighthouse')
const opts = {
  // CPU and Network throttling will be enabled by default
  disableDeviceEmulation: true,
}
lighthouse(url, opts, config)

**Comment by KathiresanRamkumar95** [comment]
@patrickhulce Thanks!
Then How I control the network throttling as slow 3G and CPU  throttling 6x Slowdown by using flags?
Please help me to control the full option by using flags.

**Comment by patrickhulce** [comment]
Unfortunately, there's no way from the flags to specify other throttling presets/speeds. []() is our recommended guide for advanced network throttling, and you want to follow #3837 and https://github.com/GoogleChrome/lighthouse/issues/4376 which tracks making it easier to control the browser with puppeteer.
