### ISSUE TITLE
YouTube integration & eating own dogfood

### ISSUE THREAD

**Issue by CymruUSA** [GoogleChrome/lighthouse#4531]
Hi all,

I have worked hard on my site to make it a PWA and have done pretty good overall. I constantly fail lighthouse, speedtests, etc whenever I try to add videos to the site via youtube. I don't know how to overcome this because it seems like google doesn't eat its own dogfood.  Things like this;

Error parsing header X-XSS-Protection:
.ytp-share-panel-error
Uses inefficient cache policy on static assets: 16 assets found (eg nv9bQbKEJk/maxresdefault.jpg(i.ytimg.com))
www-embed…/www-embed-player.js(www.youtube.com)
etc
Serve images in next-gen formats
Redirects to the likes of https://googleads.g.doubleclick.net/pagead/id?exp=nomnom

More errors on a single page that the rest of the site put together. Is there anyway to mitigate this? Thanks.

**Comment by paulirish** [comment]
gonna dupe this into #4516
