### ISSUE TITLE
Any plan to launch lighthouse for website on desktop?

### ISSUE THREAD

**Issue by ganlanyuan** [GoogleChrome/lighthouse#4535]
Seems lighthouse is only for mobile App, is there any plan for website on desktop?
Thanks

**Comment by patrickhulce** [comment]
thanks for filing @ganlanyuan! if you're using programmatically (which from #4476 it seems like you are 😉) you can use the `--disable-device-emulation` flag on CLI or `disableDeviceEmulation: true` in your flags object that's passed in to lighthouse function.

#2838 tracks enabling this in DevTools
