### ISSUE TITLE
Handle priority changes in network-recorder

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#454]
@deepanjanroy knows more abou this than me, but i think we have some TODOs here (now that the prioritychanged events landed in blink)..

1. bump our devtools-frontend module to a newer version
2. hook up the prioritychanged protocol event into network-recorder

deep, that about right?

**Comment by deepanjanroy** [comment]
Correct. I'll get on it.

**Comment by brendankenny** [comment]
one thing to watch with our dependencies going forward is the google3 import. If we bump chrome-devtools-frontend we need to make sure speedline is compatible with that version (but I assume most changes with chrome-devtools-frontend are backwards compatible?)

**Comment by paulirish** [comment]
fixed by #463
