### ISSUE TITLE
Inconsistent performance results same website across different computers

### ISSUE THREAD

**Issue by codingbart** [GoogleChrome/lighthouse#4567]
I have been testing a website, jagservice.nl, with Lighthouse (Audit in Chrome Developers Tools) on different computers.
 At home, on my HP i7, I am scoring between 75-80. At home, on my laptop, the same website consistently scores around 66-68. At work, it scores around 45-55 each time. 
All the time, the website has been totally unchanged. 
This 45 to 80(!) range makes it hard for me to determine which computer delivers the accurate result.

Would you have any idea how this could be possible?

**Comment by patrickhulce** [comment]
Thanks for reporting @codingbart!

The best way to debug this would be to look at what was happening during page load. You can collect traces of everything that Lighthouse was looking at by running with the CLI and adding the `--save-assets` flag. The `*.trace.json` file is what we're looking for.

As for what's going on, our [scoring guide]() tries to outline different sources of variability. The natural variability of performance metrics on identical hardware can lead to +/- 15 pts from run to run and different hardware of desktop i7 vs laptop could certainly help explain that. 

The work example is a little more abnormal. My best guess is that there is some proxy/security software/etc on your work network interfering with the loading of the page that has a radical effect on performance. If you can get us traces of the run then we'd be able to offer more concrete explanations.

**Comment by codingbart** [comment]
Dear @patrickhulce,
I have followed your instructions and attached the .trace file (as .txt file). 
The score on performance lighthouse via the Node CLI is around 63-65 by the way. 

[www.jagservice.txt](https://github.com/GoogleChrome/lighthouse/files/1732934/www.jagservice.txt)

 If you need anything else I am happy to hear it!

**Comment by codingbart** [comment]
Dear @patrickhulce,
I think I did not activate the caching plugin at my work situation, which caused around 1.5s server time and a large difference in performance score. 
Only thing that remains is an average 10 point difference between my not so fast laptop and fast desktop. But that was within the variation stated in the docs. Thanks for the help anyway!
