### ISSUE TITLE
PWA 'Redirects to HTTPS' test fails when run on mobile device

### ISSUE THREAD

**Issue by mattwomple** [GoogleChrome/lighthouse#4568]
The "Redirects HTTP traffic to HTTPS" test produces distinct results when run from desktop Chrome Dev Tools and when run from lighthouse 2.9.1 (installed via npm) on an Android 7.0 device via ADB. For cases where this test returns success on desktop Chrome, it always seems to report failure when tested on a mobile device. Testing https://google.com will reproduce the problem (github.com also works).

**OS:** Windows 10 x64
**Desktop Chrome:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
**Mobile Chrome:** Mozilla/5.0 (Linux; Android 7.0; Moto G (5) Plus Build/NPN25.137-93) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36
**ADB:** 1.0.39 (specific version 0.0.1-4500957)
**Lighthouse:** 2.9.1
Commands:

- `adb forward tcp:9222 localabstract:chrome_devtools_remote`
- `lighthouse --port=9222 --disable-device-emulation --disable-cpu-throttling --view "https://google.com"`

**Device:** Motorola Moto G5 Plus; Android 7.0; Build NPN25.137-93
[Sample JSON lighthouse report](https://gist.github.com/mattwomple/6af1b6dc8a97a7157b42f77da4ef05fd)

**Comment by patrickhulce** [comment]
Thanks very much for the report @mattwomple! You are correct this audit doesn't work properly on Android due to Chrome on Android internal differences from desktop Chromium. Slightly more detail available in #2363, so I'll merge this into that issue.

**Comment by mattwomple** [comment]
Ah, I didn't search well enough. Thanks for the update, I'll subscribe to that issue.
