### ISSUE TITLE
Lighthouse CL --view opens blank page

### ISSUE THREAD

**Issue by DavidScales** [GoogleChrome/lighthouse#4569]
Apologies if I'm missing something basic. I'm not able to the the `--view` flag to open my report:

```
node -v
// v8.9.4

npm install -g lighthouse
// success

lighthouse https://airhorner.com/ --view
// no errors - report generated airhorner.com_2018-02-16_15-06-20.report.html
// empty browser window opens
```

I can open the report by manually opening the generated file, but the `--view` flag simply opens my browser to the default home page - no report. 

I have Chrome 64.0.32 on Mac OS 10.13.3

Any ideas?

**Comment by wardpeet** [comment]
can you tell us which version of lighthouse you're running? 
`lighthouse --version`

**Comment by DavidScales** [comment]
sorry, yeah 2.9.1

**Comment by patrickhulce** [comment]
hm strange behavior I'm not sure I've seen this before. We're just using [opn](https://www.npmjs.com/package/opn) under the hood for this. Does this simple script work for you?

```js
const opn = require('opn')
opn('airhorner.com_2018-02-16_15-06-20.report.html')

**Comment by DavidScales** [comment]
The script wasn't working, and my coworker was able to run `--view` successfully, so like any debugging expert I basically just restarted Chrome and my mac, and that seems to have fixed it... haha. 

Sorry about that - should have tried that sooner.
