### ISSUE TITLE
constant intrusion using honeypot

### ISSUE THREAD

**Issue by smarescotti** [GoogleChrome/lighthouse#4575]

**Comment by smarescotti** [comment]
I keep finding code from my mac on several repositories. personal and corporate info used as testing ground for useless apps

**Comment by patrickhulce** [comment]
sorry to hear that @smarescotti! I'm not sure what this has to do with the Lighthouse repo though?

**Comment by paulirish** [comment]
sorry, but we don't have your data in our repo.
