### ISSUE TITLE
Resolve audit result values

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#458]
#### Currently...

* `result.value` - most of the time is actually === a score
* `result.rawValue` - many times its a string of "1232.32ms"  .. not exactly "raw"

#### Proposal 
* `result.score`
* `result.rawValue` - which is either a number or boolean, never a string
*  `result.displayValue` - which is a string

**Comment by brendankenny** [comment]
LGTM

**Comment by paullewis** [comment]
LGTM

**Comment by wardpeet** [comment]
I'm working on this ticket as we speak but what should happen with rawValue when it's a color? should it just say true?

**Comment by paulirish** [comment]
> I'm working on this ticket as we speak but what should happen with rawValue when it's a color? should it just say true?

Theme-color?  TBH it's kinda superfluous that we report it. The rawValue there should be boolean. Can move the color into `extendedInfo`

> What with score false? Should it convert to 0 and have a rawValue of false and displayValue of ''?

shrug...

**Comment by wardpeet** [comment]
I'll just prepare a pr and i'll just wait for feedback :p

**Comment by wardpeet** [comment]
Fixing some bugs, almost done so will have a pr ready today or tomorrow

**Comment by paulirish** [comment]
awesome! thanks for the update man
