### ISSUE TITLE
Validate that offline functionality is useful

### ISSUE THREAD

**Issue by carlenzoliyuri** [GoogleChrome/lighthouse#4591]
I see that Lightouse (in chrome) assign 100% PWA score at [service worker only offline](https://serviceworke.rs/offline-status.html).

But ... is offline, IMHO 100% is not good.

Sorry for english,
Yuri.

**Comment by patrickhulce** [comment]
I'm not sure I understand.

Lighthouse will give a 100 on PWA for a page that registers a service worker and responds with a 200 when offline.

Are you suggesting Lighthouse should not require responding with a 200 when offline in order to get a 100 on PWA?

**Comment by carlenzoli** [comment]
Response 200 when offline is good, but, example, one additional check to see if is website that work offline and not one static page IMHO is best, for PWA purpose.

**Comment by patrickhulce** [comment]
Ah ok! Yes, that's a good idea. Deciding if a site provides functionality that is "too simple" while offline can be difficult though so ideas welcome :)

**Comment by paulirish** [comment]
We don't know of a reliable mechanism to confirm the site is working and not just a "congrats you are offline, but we have a service worker" static page.

We'll keep this closed until someone has a proposal for this.

Again, good idea, but currently not feasiable.
