### ISSUE TITLE
Add not applicable to PWA, other audits when necessary

### ISSUE THREAD

**Issue by futureweb** [GoogleChrome/lighthouse#4599]
Even PWA checks are disabled - it will show a Warning that "Manifest's 'short_name' will be truncated when displayed on homescreen" within "Best Practices" Section.
Shouldn't be displayed when PWA check is disabled.

Andreas Schnederle-Wagner

**Comment by patrickhulce** [comment]
Thanks for filing @futureweb! Good point, and we have a plan to start adding "not applicable" to all sorts of audits. This is an ideal first candidate.

**Comment by brendankenny** [comment]
PWA audits were reworked for 4.0 to show less irrelevant info, so hopefully this is less of a distracting issue now
