### ISSUE TITLE
Unable to find chrome session started by Protractor

### ISSUE THREAD

**Issue by m2kannojiya** [GoogleChrome/lighthouse#4606]
I want to run lighthouse on complete flow. I can automate this with protractor or any other automation tool but when I am running lighthouse. It is opening new instance of Chrome driver and run like incognito window i.e. entirely new session. Is there any way we can get existing session so that we can audit entire flow of an application.

**Comment by patrickhulce** [comment]
I'm not super familiar with protractor, but from what I can tell it's based on Selenium/WebDriver which uses the same protocol Lighthouse does. Basic approach you'll want to follow is to make sure you tell protractor to tell selenium to use the same port option you're passing to Lighthouse.

[Headless chrome section on webdriver](https://developers.google.com/web/updates/2017/04/headless-chrome#drivers) might help. [Looks like you might want to use](https://github.com/angular/protractor/blob/master/docs/server-setup.md) `seleniumArgs` argument of protract to pass `--port=9222`?

@ebidel might be able to help a little more.

**Comment by m2kannojiya** [comment]
Unfortunately protractor can't use -remote-debugging-port which may help but that is used by chrome itself so it is not possible. @patrickhulce do you know any other automation tool which can be used with lighthouse? Do you ever come across this type of requirement by other users. I think this is very common scenario and there should be some way to achieve this.

**Comment by m2kannojiya** [comment]
Thanks Patrick for information

**Comment by Utsavutsavs** [comment]
can we use lighthouse with protractor for end to end flow??
please guide if yes
