### ISSUE TITLE
How to emulate on particular mobile device and network type ?

### ISSUE THREAD

**Issue by vikramvi** [GoogleChrome/lighthouse#4626]
Is it possible to emulate device other than Nexus 5X and network speed as well other than default ?

**Comment by vinamratasingal** [comment]
Hi Vikram- we currently don't support this functionality but are working to add device type emulation as part of #2838. Feel free to follow progress there, I will close this bug out to remove dupes.

**Comment by vikramvi** [comment]
@vinamratasingal #2838 is in Closed state, can you please re-open it
