### ISSUE TITLE
Perf Metrics & Scoring vNext

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#4629]
Some small changes we plan on making to the metrics we expose and how we score them

* [x] Add FCP to the LH results #3761
* [x] Metrics: rename "First Interactive" and "Time To Consistently Interactive" #3655
* [ ] Redo the weighting
* [x] TTI [moved to depending on FCP](https://docs.google.com/document/d/1yE4YWsusi5wVXrnwhR61j-QyjK9tzENIzfxrCjA1NAk/edit#heading=h.cdpn5719a7nc). we should follow
* [x] [Network Idle was adjusted](https://docs.google.com/document/d/1yE4YWsusi5wVXrnwhR61j-QyjK9tzENIzfxrCjA1NAk/edit#heading=h.3mu7z0sv880k). We can also filter out non-GET and Failed requests

proposal doc: [LH Performance Score 2018Q1 Revision](https://docs.google.com/document/d/1XiKdkLgWul0l40slhkCmQufNdjUiTlq3H_EAjrBH5Cw/edit)

cc #4333

**Comment by vinamratasingal** [comment]
Based on feedback from the LH scoring committee meeting, we have an overall preliminary LGTM but a) need to dig into the feedback a bit more and b) need to see how the new score shapes up on a few websites and dig into the traces a bit more. We're hoping to have this ready before the next scoring committee meeting in late March.

**Comment by paulirish** [comment]
* [ ] TTI [moved to depending on FCP](https://docs.google.com/document/d/1yE4YWsusi5wVXrnwhR61j-QyjK9tzENIzfxrCjA1NAk/edit#heading=h.cdpn5719a7nc). we should follow
* [ ] [Network Idle was adjusted](https://docs.google.com/document/d/1yE4YWsusi5wVXrnwhR61j-QyjK9tzENIzfxrCjA1NAk/edit#heading=h.3mu7z0sv880k). We can also filter out non-GET and Failed requests
