### ISSUE TITLE
Investigate Lantern predicting Speed Index

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#4639]
For the new Lighthouse performance score upgrade, we want to use Speed Index as a mid-load predictor. To make our story consistent, we need to make sure Lantern is able to predict this as well.

**Comment by patrickhulce** [comment]
wrote up a [doc](https://docs.google.com/document/d/1qJWXwxoyVLVadezIp_Tgdk867G3tDNkkVRvUJSH3K1E/edit?usp=sharing) and PR #4695 with findings

**Comment by patrickhulce** [comment]
I've updated the doc with my latest attempts, we can address the biggest concern and improve accuracy ~15% by adding in unthrottled speed index. This dramatically slows down lantern computation and introduces the dependency on screenshots but if we were planning on reintroducing it anyhow, then I suppose it's not that big a deal. I'm hesitant, but we can discuss in next meeting again.
