### ISSUE TITLE
Bogus "Does not redirect HTTP traffic to HTTPS" on webpagetest.org - v2.9.1

### ISSUE THREAD

**Issue by kevmoo** [GoogleChrome/lighthouse#4645]
See report here: https://www.webpagetest.org/lighthouse.php?test=180228_K4_25c25b64a9bb5075799efcb17212f702&run=3#pwa

For https://dart-hn.firebaseapp.com/

Seems bogus.

Hitting http://dart-hn.firebaseapp.com/ does the redirect as expected.

Using locally on chrome w/ v2.9.0.280 of the extension gives us a perfect 100.

**Comment by vinamratasingal** [comment]
Discussed with Pat offline and it seems like this is not a WPT issue. 

Kevmoo- it seems like you're running with 2.9.0 on the Extension but WPT is using 2.9.1. Can you try running both with 2.9.1 to see if you get the same results?

**Comment by patrickhulce** [comment]
Hey @kevmoo, does this only happen on Android devices for you? I'm betting it's a duplicate of https://github.com/GoogleChrome/lighthouse/issues/2363

**Comment by kevmoo** [comment]
Yup @patrickhulce – looks like a dupe.

Duplicated of https://github.com/GoogleChrome/lighthouse/issues/2363
