### ISSUE TITLE
Better UI warning when category has an audit failure

### ISSUE THREAD

**Issue by jessiehan** [GoogleChrome/lighthouse#4653]
I found that when audit run with error, the score is calculated with 0

```js
{ id: 'offscreen-images',
    weight: 1,
    group: 'perf-hint',
    result: 
     { score: null,
       displayValue: '',
       rawValue: null,
       error: true,
       debugString: 'Audit error: No domContentLoaded event in trace',
       extendedInfo: undefined,
       scoringMode: 'binary',
       informative: true,
       manual: undefined,
       name: 'offscreen-images',
       description: '避免首屏外的图片加载',
       helpText: '考虑懒加载首屏外的图像，以提高页面加载速度和可交互时间',
       details: undefined },
    score: 0 }
```

maybe should add a judge here? https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/scoring.js#L50

**Comment by patrickhulce** [comment]
Thanks for filing @jessiehan! This was an intentional decision to not be overly optimistic and present the user with an inflated score. We're working on better UI in the report to convey that an error occurred in the category instead of showing just the score as-is.

**Comment by paulirish** [comment]
@jessiehan does that make sense? We're trying to avoid saying you have a 100/100 if there were 10 audits in a category and 9 of them errored, leaving just 1 that passed.

We're thinking something like an Error badge on the category score to indicate "You got a 30/100, but there were errors that brought this score down".

Does that work for you?

**Comment by brendankenny** [comment]
We do this now! `null` for the category score and a performance gauge that indicates there was an error.
