### ISSUE TITLE
Audit appears to hang in Chrome Canary for https://meatscope.camera

### ISSUE THREAD

**Issue by cdata** [GoogleChrome/lighthouse#467]
Browser: Chrome Version 53.0.2777.0 canary (64-bit, OSX)

I tried to run the Lighthouse analysis on https://meatscope.camera. Unfortunately, towards the end of the audit the browser seems to hang, requiring the user to force-quit Canary to get back to a normal state.

![http://i.imgur.com/8zABdHk.gif](http://i.imgur.com/8zABdHk.gif)

**Comment by cdata** [comment]
Update: I would like to downgrade this issue a little. I let the Lighthouse analysis run for about ~10 minutes and it eventually finished. Still, this seems like an abnormally long time to expect a user to wait, and the analysis prevents Canary from closing in the mean time.

**Comment by paulirish** [comment]
Thanks, I've seen this hang when its on `about:blank`. 
I believe we've got a race condition while waiting for the load event or something along those lines..

**Comment by brendankenny** [comment]
I believe with our push to fix the extension a few weeks ago this is now fixed. Runs and completes correctly for me with current version 1.1.2

**Comment by paulirish** [comment]
Marking as fixed.
