### ISSUE TITLE
The percentage value is not displayed correctly

### ISSUE THREAD

**Issue by banhaserhij** [GoogleChrome/lighthouse#4693]
Steps:
1. Open page in browser
2. Open devtools
3. Start audits
4. Look at the tab "Opportunities > Serve images as WebP | Potential Savings
**Expected**: Display correct percentage
**Result**: Percentage value is displayed in reverse order
![image](https://user-images.githubusercontent.com/16404807/36980454-f3d5e586-2092-11e8-98bd-677c49390451.png)

**Comment by patrickhulce** [comment]
@banhaserhij what do you mean "Percentage value is displayed in reverse order"?

First item, original is 550, savings is 524 which is 95% of the original.
Second item, original is 91, savings is 20 which is 22% of the original.

The percentage is what percent of the resource is wasted, aka, the "Potential Savings"

**Comment by banhaserhij** [comment]
@patrickhulce 
It seems to me that in the "Potential Savings" must displayed  like:
First item, original is 550, savings is 524 which is 5% of the original.
Second item, original is 91, savings is 20 which is 78% of the original.
Becouse in first picture, i can't saving 95%, only 5% etc

**Comment by patrickhulce** [comment]
It seems like you might be misunderstanding what "savings" means

Savings is the number of bytes that could be removed from the resource. If the original was 550kb and savings is 524kb (i.e. you can save 524k and you could reduce the file size to 26kb), you can reduce the file size by 95%, the potential savings is 95%.

**Comment by patrickhulce** [comment]
Either way, we've removed the percentages and this won't be relevant anymore. :)
