### ISSUE TITLE
Only request pSI from speedline instead of all

### ISSUE THREAD

**Issue by pmeenan** [GoogleChrome/lighthouse#4694]
It looks like only the perceptual speed index is used but both pSI and SI are calculated by default by speedline (and one of the slower parts of the audit).  Passing Include.pSI as an option should restrict speedline to not calculate SI and speed up the audits.

Optionally, If SI is exposed in the UI, even though it is not part of the score aggregation it would be helpful to embedders to optionally not run the SI claculation.

**Comment by patrickhulce** [comment]
I believe we already made this optimization (#3845), but perhaps it's not working properly. Are you still seeing both computed in WPT?

**Comment by pmeenan** [comment]
Argh, sorry - misread the code.
