### ISSUE TITLE
Critical Request Chains with Rel=Preload

### ISSUE THREAD

**Issue by scottjehl** [GoogleChrome/lighthouse#4702]
This page uses `link[rel=preload]` to fetch a stylesheet asynchronously, then apply the stylesheet after loading via `onload="this.rel='stylesheet'; this.onload=null;"`. 

https://264-origin-loadcss.fgview.com/test/preload-control.html

Lighthouse flags that stylesheet as part of a "critical request chain," even though it loads without blocking page rendering, and in this test case even happens to contain no CSS styles, so it doesn't impact page layout in any way that would seem critical.

![image](https://user-images.githubusercontent.com/214783/37062228-728cdb78-215b-11e8-93f9-614f424b7d1b.png)

We are wondering about the criteria that deems this a "critical request" from Lighthouse's perspective. Is it the priority for `rel=preload` itself that happens to trigger it? Is Lighthouse advocating against this pattern or merely noting it as part of the feedback about page load?

_Note: the stylesheet has a 5 second server timeout to make visual testing easier._

Thanks! Related issue is here https://github.com/filamentgroup/loadCSS/issues/264

**Comment by paulirish** [comment]
Hey scott! thanks so much for filing this.

Yes this is definitely a bug. We actually have addressed this behavior in other audits. For example: https://github.com/GoogleChrome/lighthouse/blob/bc9efba9b7b5c40a2886d6f1d366e272f420afb2/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js#L15-L17

But in the case of Critical Request Chains we didn't filter out `rel=preload` resources. We'll fix this. :)


And thanks so much for making this minimal repro. Super useful.
