### ISSUE TITLE
Question: Is possible to run Lighthouse against group of page?

### ISSUE THREAD

**Issue by Danon9111** [GoogleChrome/lighthouse#4707]
Hi,

I'm wonder if in latest version of Lighthouse CLI is possible to do bulk run and generate audit report for each page? 

If not, is possible to parametrized somehow this part of command and provide source of links against which we would like to run tests? For example: `lighthouse list-of-urls.xml --disable-device-emulation --view`

Regards

**Comment by paulirish** [comment]
Hi, we decided to not support this natively, though there have been other efforts that try this out.

https://www.npmjs.com/package/lighthouse-batch
https://github.com/GoogleChrome/lighthouse/tree/master/plots

just doing a basic bash script is the recommended approach right now.
