### ISSUE TITLE
Background and foreground colors wrong definition

### ISSUE THREAD

**Issue by magtesyan** [GoogleChrome/lighthouse#4709]
Hi,
I get a failed point in audit: 
![image](https://user-images.githubusercontent.com/37150324/37100293-9e2b04de-2233-11e8-8907-fa7c4a419be2.png)

but these links and elements have quite contrast with background
![image](https://user-images.githubusercontent.com/37150324/37100404-e71dfd4a-2233-11e8-90f2-4d81014aef36.png)
![image](https://user-images.githubusercontent.com/37150324/37100448-06577092-2234-11e8-931f-886408f34204.png)
![image](https://user-images.githubusercontent.com/37150324/37100485-2465f752-2234-11e8-91fa-ea9dc4ae318a.png)

Tested site: https://sboravto.ru
Lighthouse v.:  2.9.0.280

**Comment by paulirish** [comment]
Wow this got interesting.

So, these elements have a contrast of 4.46. However the threshold for passing is  4.5. You can see these by running the [aXe Chrome extension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd/related) (which Lighthouse basically has bundled).

![image](https://user-images.githubusercontent.com/39191/37247767-7d52ba4c-2475-11e8-8809-f47a34fee4da.png)

IMO 4.46 is close enough to 4.5 to call it passing.
**But** apparently there have been debates about this and WCAG decided that rounding shouldn't apply: https://github.com/w3c/wcag/issues/200#issuecomment-256091343

IMO, that's pretty ridiculous. And there's a lot of other people that would agree.  But that's where things are right now. :/


The red color is currently `#F00000`. That maps to `hsl(0, 100%, 47%)`. And if you make it just one percent darker: (`hsl(0, 100%, 46%)`), it passes the color contrast check. So........... There you go. ;)

---
cc @WilcoFiers @alice

**Comment by alice** [comment]
Looks like aXe is detecting this as regular (not large) font, but the contrast ratio panel detects it as large font.
