### ISSUE TITLE
How to use CLI options programatically ?

### ISSUE THREAD

**Issue by vikramvi** [GoogleChrome/lighthouse#4715]
Please clarify how can I use CLI options like programatically ? 

```
 --disable-device-emulation    Disable Nexus 5X emulation                                                                                 [boolean]
  --disable-cpu-throttling      Disable CPU throttling 

  --view         Open HTML report in your browser   
```

I did check `Using programmatically section`  under README but didn't understand how to use above values inside 

```
const opts = {
  chromeFlags: ['--show-paint-rects']
};
```

**Comment by vikramvi** [comment]
@ebidel can you please clarify; I'm blocked and not finding anything in google :)

**Comment by patrickhulce** [comment]
@vikramvi most CLI options can be used in `opts` as camel-cased versions i.e.
```js
const opts = {
  disableDeviceEmulation: true,
  disableCpuThrottling: true,
  chromeFlags: ['--headless'],
}
```

#3587 tracks better documenting this fact

**Comment by paulirish** [comment]
https://github.com/GoogleChrome/lighthouse/tree/master/docs#using-programmatically is mostly on point

the camelCasing happens automatically so you can plug those directly into `opts` in the example. Gluck!

**Comment by vikramvi** [comment]
@patrickhulce @paulirish 

We tried below program but it did't work, can you please review

```
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');
// process.env.args = " --veiw --disable-network-throttling --disable-cpu-throttling"
// console.log(process.env.args);

function launchChromeAndRunLighthouse(url, opts, config = null) {
  return chromeLauncher.launch({chromeFlags: opts.chromeFlags}).then(chrome => {
    opts.port = chrome.port;
    console.log(lighthouse)
    return lighthouse(url, opts, config).then(results => {
      // The gathered artifacts are typically removed as they can be quite large (~50MB+)
      delete results.artifacts;
      return chrome.kill().then(() => results)
    });
  });
}

const opts = {
  output: 'json',
  disableDeviceEmulation: true,
  disableCpuThrottling: true,
  chromeFlags: ['--show-paint-rects']
};

// Usage:
launchChromeAndRunLighthouse('https://www.smava.de', opts).then(results => {
  console.log("HIiiiiiiii"); // Use results!
});

```

**Comment by patrickhulce** [comment]
@vikramvi the flags seem to be set properly. What is not working exactly? Do you see the emulation still being applied?

that script worked perfectly for me

**Comment by vikramvi** [comment]
@patrickhulce  I'm running above script ( saved in filename - lh.js ) on `Ubuntu OS 16.04` with `node version v9.2.0` and `npm version 5.5.1` with command `node lh.js`

As per script it should create a json after execution but it's not getting generated.

Just to clarify from command line these flags are working fine but I need to get it working through script, so that I can put the script in Jenkins

Is there log file to check for error / info ?

**Comment by vikramvi** [comment]
@patrickhulce  thanks for clarification. I made change in the script & now I'm using flag `--view ` , when I use this from command line it works but with script it's not. It doesn't creates html report & opens in browser once script execution is over

Please check 
https://gist.github.com/vikramvi/90f04717baf5bb7f348bb74ab75d8882

**Comment by patrickhulce** [comment]
I'll refer again to #3587, you're expecting CLI functionality from the node module which isn't there. We'll try and better document this in the future :)

**Comment by vikramvi** [comment]
@patrickhulce Thanks again for your input.  Is there any means to use lighthouse with Jenkins and integrate with CI, CD pipeline ?

Our objective is to make sure each of the release is not breaking in terms of performance and lighthouse should catch it well in advance.

**Comment by patrickhulce** [comment]
Yes definitely! 

For CI-specific use cases you might be interested in [lighthouse-ci](https://github.com/ebidel/lighthouse-ci) (cc @ebidel), but easiest path right now is mostly likely running lighthouse as CLI in your build script and then kicking off your own script to assert whatever you need to about the results. Does that make sense?

**Comment by vikramvi** [comment]
Thanks let me try these approaches @patrickhulce

**Comment by vikramvi** [comment]
@patrickhulce per your last comment; to do assertion how can I fetch result from  `lighthouse as CLI in your build script` ?

**Comment by patrickhulce** [comment]
right now you probably have something like

```
npm install
node ./run-lighthouse.js
// do something with the json output
```

since you don't seem to actually want the programmatic results and just want the file, it seems as though something more like 
```sh
npm install -g lighthouse
lighthouse --disable-device-emulation --output=json --output-path=./lighthouse.json http://the-url.com/
// do something with the json output
```

would be easier for you

**Comment by vikramvi** [comment]
Thanks for quick help.

**Comment by nothingismagick** [comment]
We are integrating lighthouse into the [quasar-framework](https://github.com/quasarframework/quasar-cli) as the fourth and final component of our new testing mode, and I have been looking literally way too long (3 hours?) for how to do get access to the opts. 
<details>
It got to the point where I started tracking the way that functions were passing variables within lighthouse core, and then I just caved and decided that before I file an issue I should search for it, because with this many stars I cannot be the first to have this problem. Low and behold, no - this has been an issue for over 6 months... :| 
</details>

### Anyway, I have several recommendations to resolve this.  
1. Make it clear that it is possible to access the CLI options via config files (for the CLI or the NODE interface). Explicitly give an example of this in a prominent place, such as in the README.md in the root folder of this repo.
2. Differentiate between **settings**, _options_ and _**configurations.**_ These are all so semantically similar, that I think the use of all three should be canonised with regard to how the Lighthouse project understands them and uses them. (If this has been done, please point me toward it!)
