### ISSUE TITLE
DevTools Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by LuXDAmore** [GoogleChrome/lighthouse#4719]
**Initial URL**: http://admin.venditegiudiziarieitalia.it/#/
**Chrome Version**: 64.0.3282.186
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@9611116ee79c63602f452e4fae2242a61cf0672d/audits2_worker/audits2_worker_module.js:694:516)
    at <anonymous>
```

**Comment by paulirish** [comment]
Thanks for reporting!

------

Odd. all the [other "Read failed" bugs](https://github.com/GoogleChrome/lighthouse/issues?q=is%3Aissue+Read+failed+is%3Aclosed) got duped into #2448, but that appears to be 404'ing now.
