### ISSUE TITLE
first meaningful paint is inaccurate

### ISSUE THREAD

**Issue by wensheng-yan** [GoogleChrome/lighthouse#4720]
I think lighthouse sometimes calculate wrong first meaningful paint time. 

Screenshot looks like below

<img width="666" alt="screen shot 2018-03-09 at 12 49 17 pm" src="https://user-images.githubusercontent.com/33325019/37221519-4fd24caa-2398-11e8-9c5a-8860a2cdcbb1.png">

I think the first meaningful paint should be around 1500ms instead of 14,420ms. According to the screenshot, everything is painted just waiting for the background image to load (the background image is just 70kb, and everything happen on localhost, i don't know why it cost 14s to load here)

here is the screenshot which calculate it correctly.

<img width="720" alt="screen shot 2018-03-09 at 12 46 10 pm" src="https://user-images.githubusercontent.com/33325019/37221428-ebf6466e-2397-11e8-830d-e5aa12147747.png">

Any help is much appreciate.

**Comment by paulirish** [comment]
Yeah I think you're right. Based on the screenshots I agree it should be much earlier. 

FMP basically relies on # of nodes in Layout, so I suspect the DOM is changing quite a bit late in the page, even if visually not much is happening.

But it's essentially a bug in the First meaningful Paint metric. Perceptual Speed Index will be a better metric for this site.

Can you share what URL this is?

**Comment by exterkamp** [comment]
Closing this for now, but if you see this issue come up again comment and we can reopen.
