### ISSUE TITLE
url shouldn't be required for --list-all-audits or --list-trace-categories

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#474]
with the move to yargs in #456, the url became a required argument for the cli. The downside of this is `lighthouse --list-all-audits` (or `--list-trace-categories`) now exits with "`Please provide a url`".

There may be a way to use yargs's `command()` to handle these, but I'm not sure how that works with grouping. Another option would be to drop the `demand` of the url and move the handling of it back to our own code.

**Comment by brendankenny** [comment]
@wardpeet do you want to take a look at this since you were already in the thick of it? Feel free to say no :)

**Comment by brendankenny** [comment]
fixed in #478

**Comment by wardpeet** [comment]
@brendankenny sorry had a busy weekend, looks like it's fixed :)
