### ISSUE TITLE
DevTools Error: The asynchronous expression exceeded the allotted time of 60

### ISSUE THREAD

**Issue by anyblodybanana** [GoogleChrome/lighthouse#4744]
**Initial URL**: https://listen.tidal.com/
**Chrome Version**: 65.0.3325.146
**Error Message**: The asynchronous expression exceeded the allotted time of 60s
**Stack Trace**:
```
Error: The asynchronous expression exceeded the allotted time of 60s
    at _ (chrome-devtools://devtools/remote/serve_file/@f926414266f7aecb5ec1bf1b5f93f8716976ceef/audits2_worker/audits2_worker_module.js:803:120)
```

**Comment by patrickhulce** [comment]
Thanks for reporting @anyblodybanana! I'm having trouble reproducing this in Chrome Canary. Does it consistently fail for you?

**Comment by anyblodybanana** [comment]
Than you for your reply @patrickhulce 
Well Tidal.com is still failing for me every time I try to listen to *HI-FI / Lossless* quallity and so far I haven't been able to locate any issues on my Centos 7 client.
I can however listen to lover streaming quallities like *standart* and *high*.

First thing I notice is a flash issue - flash allowed yet still act like it's blocked:
![chrome_on_listen tidal com_flash_allowed_and_blocked](https://user-images.githubusercontent.com/37348348/37615544-e0464ecc-2bad-11e8-8408-71ce8df23c3c.png)

I've tried to save some of the messages into text  documents - let me know if there is another way of saving logfiles from Chrome:

[4_errors_after_trying_to_play_hifi-lossless_listen.tidal.com-1521485714668.log](https://github.com/GoogleChrome/lighthouse/files/1826527/4_errors_after_trying_to_play_hifi-lossless_listen.tidal.com-1521485714668.log)
[Complete_log_listen.tidal.com-1521485896847.log](https://github.com/GoogleChrome/lighthouse/files/1826528/Complete_log_listen.tidal.com-1521485896847.log)
[Loging_in_@Tidal_listen.tidal.com-1521484730416.log](https://github.com/GoogleChrome/lighthouse/files/1826529/Loging_in_.Tidal_listen.tidal.com-1521484730416.log)
[Opening Chrome_1st_error_www.google.dk-1521484639712.log](https://github.com/GoogleChrome/lighthouse/files/1826530/Opening.Chrome_1st_error_www.google.dk-1521484639712.log)

Plz let me know if there is any  way I can provide you with more info relevant for you?

**Comment by patrickhulce** [comment]
Ah, if I'm understanding you correctly, you're trying to debug why Tidal is not working for you? 

The audits panel is primarily for helping developers follow best practices and staying on the well-lit path rather than bug hunting. While it can occasionally be helpful for that too, your best bet is more manual inspection through DevTools and reaching out to the site owners.

**Comment by anyblodybanana** [comment]
You are right about Tidal and it makes sence to reach out to Tidal.
 Thank you.
