### ISSUE TITLE
Travis: enable testing of node v4 + --harmony

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#475]
Thus bringing our test matrix to:

* v4 + harmony
* v5
* v6

Any takers?

**Comment by brendankenny** [comment]
emphasizing *not* running v5 with `--harmony`, which makes this a bit harder, but ensures we really do run on vanilla v5.

**Comment by mgerakis** [comment]
One solution that comes to mind would be to move the npm scripts into a Makefile. The scripts then become "make lint/smoke/etc". Inside the Makefile, we can check the version of node and if that version matches 4 we run files through node with the --harmony flag

**Comment by wardpeet** [comment]
make or any other helper is probably much easier but you could do something like this
`$(test $(node -v) =~ "^v5.*" && echo $(npm bin)"/mocha --harmony" || echo $(npm bin)"/mocha") $(find lighthouse-core/test -name '*.js') --timeout 60000` inside your package.json of course it's not really pretty. probably can be written even shorter

**Comment by wardpeet** [comment]
@paulirish @brendankenny what do you guys think? Do it native with bash or rather have something in between? I could do a pr with just a one liner and see what you guys think?

**Comment by brendankenny** [comment]
what about passing an argument into the npm scripts and let the `travis.yml` handle the node version detection part?

**Comment by wardpeet** [comment]
sounds better but no idea how to do that :)

**Comment by kyleholzinger** [comment]
What about using a more node friendly task runner like gulp or grunt? Might help with the node versioning as well

**Comment by paulirish** [comment]
fixed by #501
