### ISSUE TITLE
Fetch the gatheredTimestamp

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#4753]
Right now we add a `.generatedTime` timestamp to the LHR that marks when [runner is packaging up the LHR](https://github.com/GoogleChrome/lighthouse/blob/1fc455786ab30dfad8fabfb100e3ed34b7bbf4d2/lighthouse-core/runner.js#L105).

IMO, a more useful timestamp is when we start gathering; basically when we loaded the page. Beyond semantics, this probably only matters in the situations where gathering&auditing are done separately. Recently, I've been repeatedly regenerating the sample_v2.json, doing `-A` runs from the exact same artifacts. I'd argue it doesn't really make sense for the timestamp in the LHR to change. 

(Implementation-wise: Collecting in the gatherrunner right [when we grab the userAgent](https://github.com/GoogleChrome/lighthouse/blob/1fc455786ab30dfad8fabfb100e3ed34b7bbf4d2/lighthouse-core/gather/gather-runner.js#L103-L105) makes sense to me). 

A few questions:

1. Do ya'll agree this is a more useful timestamp?
1. If we start exposing this, should we stop exposing the current `.generatedTime`? (including for the LHR-Lite)
1. If we do that, we should probably rename this property. We could do just `.startTime`. And then the timings in #3745 would be treated just like navStart & resource timing. 

thoughts?

**Comment by patrickhulce** [comment]
1. Yes
2. Yes! #4333 :)
3. I'm not a huge fan of `.startTime`. It makes some sense to keep the run time measurements distinct from absolute datetime that the thing happened. This field was renamed `audit_time` internally, FWIW, but I'm not a huge fan of that either. In my experience these types of fields in APIs are generally named `*At`, `createdAt`, `auditedAt`, `fetchedAt`, `gatheredAt`, any of those feel good?

**Comment by brendankenny** [comment]
This definitely makes way more sense than LHR generation time. I'm fine with `fetchedAt` or `gatheredAt` or whatever variation, and they seem more self descriptive that `startTime` (`fetchedTime` or `gatheredTime` might better fit our existing style but I really don't care :).

Also agree with run time measurements being relative rather than absolute...I can't imagine why you would need an absolute time, and at worst you could reconstruct from the start time and elapsed times

**Comment by paulirish** [comment]
K. I'm also into `fetchedAt` the most and `gatheredAt` second. Groovy. Sounds like we're good here then.


@ev1stensberg wanna take this?

i think this is the sequence:

1. remove generatedTime from runner.
1. as i mention above, get a timestamp when we grab useragent. store it on `gathererResults`
1. where generatedTime is attached to the object in runner, place this timestamp as `fetchedAt`

**Comment by ev1stensberg** [comment]
Yep, picking this up. Thanks for letting me 👌
