### ISSUE TITLE
proposal: rename lighthouse-core/driver/ to lighthouse-core/gather/

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#476]
confusion is strong between the contents of driver/, contents of driver/drivers/, and driver/index.js (which contains class `Driver`) and driver/drivers/driver.js (which contains class `DriverBase`) :)

Really this directory is about running gatherers (via an interface to chrome) and producing artifacts, and a small rename could clear up some confusion, I think. One approach:

- renaming lighthouse-core/driver/ to lighthouse-core/gather
- renaming core/gather/index.js's class from `Driver` to `Gather`
- renaming core/gather/gatherers/gather.js to core/gather/gatherers/gather**er**.js (and changing its class name from `Gather` to `Gatherer`)
- possibly changing core/gather/drivers/driver.js's class name from `DriverBase` to just `Driver`, but I care less about that

opinions? I find myself confusing this all the time.

**Comment by paulirish** [comment]
yes definitely. 

Only thing I wonder about is if we should call the folder structure /artifacts/ and more or less s/gatherer/artifact/.   Noun-centric instead of verb-centric.   But just an idea.

**Comment by paullewis** [comment]
I'm all up for this. Brendan, are you happy to take this on? Feels like we want to get this sorted soon to minimize disruption.

**Comment by brendankenny** [comment]
fixed in #537
