### ISSUE TITLE
Plans for 2.9.2 ?

### ISSUE THREAD

**Issue by kevmoo** [GoogleChrome/lighthouse#4765]
Would love a release with this fix in

https://github.com/GoogleChrome/lighthouse/commit/231642d15eed
https://github.com/GoogleChrome/lighthouse/pull/4661

Thanks!

**Comment by paulirish** [comment]
fixed by #4782

https://github.com/GoogleChrome/lighthouse/releases/tag/v2.9.2

**Comment by kevmoo** [comment]
Thanks much!
