### ISSUE TITLE
false positive: Site is on HTTPS whilst the website is not.

### ISSUE THREAD

**Issue by pantaluna** [GoogleChrome/lighthouse#479]
The Lighthouse report lists a false positive for "Network connection is secure -> Site is on HTTPS" := Yes whilst the website is only on HTTP so it should report := No, right?

You can test it with this mobile website / webapp (I added the manifest today):
    http://m.feestdagen-belgie.be/

**Comment by brendankenny** [comment]
whoops, yes, that's a bug.

`git blame d'oh`, that's mine

**Comment by pantaluna** [comment]
Thanks for the quick action.
Hmm I reported a bug that will give my webapp less points :(, how honest can a man be.

**Comment by brendankenny** [comment]
ha, well, hopefully we can introduce a different bug that raises your score while fixing this one :)
