### ISSUE TITLE
Incorrect work of Lighthouse extension for Chrome browser

### ISSUE THREAD

**Issue by jiznelub** [GoogleChrome/lighthouse#4803]
Hello!
In the Lighthouse extension for the Chrome browser, everything was fine - 100%, and already 3 days shows 90%: "The page is blocked from indexing
Audit error: libUrl.parse is not a function of "
not only on my sites, but also on others, even on Google Maps ... What do you think, what is the reason for this?
Sincerely, Victoria

**Comment by CymruUSA** [comment]
Me too. Something new with no changes.

**Comment by valentynp** [comment]
URLs where the issue can be reproduced: 

http://www.jiznelub.com.ua/
https://www.ukr.net/

**Comment by hrdymchl** [comment]
+1 

Same problem - I was just about to start a new issue but found this thread.

<img width="844" alt="Audit error: libUrl.parse is not a function" src="https://user-images.githubusercontent.com/9407079/37604529-6b170876-2b4e-11e8-9fa1-e9d72b036c1c.png">

**Comment by patrickhulce** [comment]
thanks for filing folks! also a duplicate of #4794, let's continue discussion there :)
