### ISSUE TITLE
Port Clash Just Hangs

### ISSUE THREAD

**Issue by PivitParkour94** [GoogleChrome/lighthouse#4806]
I was trying to run the following command:
`sudo /usr/bin/lighthouse https://<my-secret-url>.com/ --port="<CLASHEDPORT>" --hostname="localhost" --max-wait-for-load="25000" --output="json" --chrome-flags="--headless --no-sandbox" --disable-cpu-throttling --verbose
`
and the ouput was
```
Driver:verbose Network.enable +0ms
method => browser:verbose Network.enable {} +1ms 
// hangs indefinitely
```

Doing some quick port scanning I found that that port actually clashed with another service. That can easily be solved by specifying a new port on the lighthouse command, but having some sort of port check in Lighthouse before making the request would be great so an exception could be thrown so other users don't fall into this trap.

Hopefully this is possible to add. I will also look into making a Pull Request for this, but someone much more familiar with Lighthouse can probably do it quicker ;)

**Comment by PivitParkour94** [comment]
Looking through the current development ideas, it looks like this will be a non-issue when port=0 is implemented (found from https://github.com/GoogleChrome/lighthouse/issues/2092#issuecomment-298071923)

**Comment by patrickhulce** [comment]
Hey @PivitParkour94 thanks for filing with the details! port=0 should already work today and is the default mode of operation. If you explicitly specify a port as in your example, then we respect that and wait until a browser shows up on it to respond :)

Aside from a global timeout on all protocol responses I'm not sure the story will improve much more from here.

**Comment by PivitParkour94** [comment]
Oh I didn't realise this change has already been rolled out. I should probably update and not specify the port, thanks for getting back to me so fast
