### ISSUE TITLE
SEO: libUrl.parse is not a function exception on indexing audit

### ISSUE THREAD

**Issue by igrigorik** [GoogleChrome/lighthouse#4810]
Running latest extension (2.9.2) against igvita.com, I see:

![image](https://user-images.githubusercontent.com/10652/37615529-cae21efa-2b6a-11e8-9f63-2299d7af08ad.png)

**Comment by rviscomi** [comment]
Reproduced the error and saved LHR to gist: https://googlechrome.github.io/lighthouse/viewer/?gist=93fae5a1e68dde3d3960de7006babf00

**Comment by patrickhulce** [comment]
thanks @igrigorik and @rviscomi! we're tracking this one over on #4794, some discussion about solutions already in progress :)
