### ISSUE TITLE
Audit error: Unable to identify the main resource

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#4814]
LHR: https://googlechrome.github.io/lighthouse/viewer/?gist=b5c490531c5e5d2a428152b10e98b7e6

URL tested: https://beta.httparchive.org/reports/state-of-the-web#pctHttps

![image](https://user-images.githubusercontent.com/1120896/37624525-d89cb8b4-2b9e-11e8-97e7-47b78f0d93c2.png)

Affects 4 SEO audits and 3 Performance audits.

cc @kdzwinel @patrickhulce

**Comment by patrickhulce** [comment]
thanks for reporting @rviscomi on a related note this page uncovered another [nasty bug](https://bugs.chromium.org/p/chromium/issues/detail?id=823544) we trip up on that needed Chrome filing, so double win! :D

**Comment by dannyrb** [comment]
FWIW, I'm receiving this same error in lighthouse v2.9.3 (chrome extension)
I also have:

> Audit Error: Cannot read property '_timing' of undefined

Under "Keep server response times low (TTFB)"

If there is any additional information I can provide, please let me know.

**Comment by janerikmai** [comment]
Seems hashtag related, can you try using cli and changing 
https://github.com/GoogleChrome/lighthouse/blob/275f5c7a33ad3f16fa93cebd1ea53f566f4ba04b/lighthouse-core/gather/computed/main-resource.js#L28

to 
`const mainResource = requests.find(request => request.url === artifacts.URL.finalUrl.indexOf('#') > -1 ? artifacts.URL.finalUrl.split('#')[0]: artifacts.URL.finalUrl);`

if that solved your problem?

**Comment by dannyrb** [comment]
Ahh @janerikmai that could be it. I'm also using hash routing, but with VueJS.

**Comment by janerikmai** [comment]
I guess the mainResource should be the "entry" domain for your application like mydomain.io where your virtual routes are like mydomain.io/#/route1?queryParam=1, so though the request url is parsed from requestNetworkRecords where no url fragments are available, the comparison in https://github.com/GoogleChrome/lighthouse/blob/275f5c7a33ad3f16fa93cebd1ea53f566f4ba04b/lighthouse-core/gather/computed/main-resource.js#L28 should ignore all url fragments by splitting at # for my taste. Agreement requested :) @brendankenny  @paulirish

**Comment by patrickhulce** [comment]
Yup, root cause is #5266
