### ISSUE TITLE
URL path on file name

### ISSUE THREAD

**Issue by rommelLenin79** [GoogleChrome/lighthouse#4823]
Is there anyway to add the URL path to the report (file) name?   I'm running lighthouse on a batch process and all my reports are coming back with the same domain and date.   I would like to differentiate them with the path.

**Comment by patrickhulce** [comment]
You can specify an `--output-path` for Lighthouse to use which can be whatever you wish.

`lighthouse --output-path=./page-1-report.html https://mydomain.com/page1`

**Comment by rommelLenin79** [comment]
Awesome, thank you @patrickhulce
