### ISSUE TITLE
Clean up patch-package hack after robots-parser update

### ISSUE THREAD

**Issue by kdzwinel** [GoogleChrome/lighthouse#4825]
Clean up after #4819

1. Open a PR against robots-parser
1. ⏳
1. Update robots-parser in LH
1. Have a browserify transform that swaps `require('url')`  with url-shim
1. Remove patch-package (+ robots-parser patch and a postinstall script)

**Comment by kdzwinel** [comment]
URL object is not the default export of the NodeJS 'url' module, so it has to be imported using `const URL = require('url').URL` or `const {URL} = require('url')`. That's different from url-shim that exports URLShim class as a default. It makes it a bit tricker to replace using browserify transform. I guess we can export URLShim as both: default export and named 'URL' export? Or just drop default export and update all code importing url-shim to do `{URL}` 🤔

**Comment by patrickhulce** [comment]
doing a simple `module.exports = URL; module.exports.URL = URL` seems a fine hack to me rather than have a bunch of churn :)

**Comment by kdzwinel** [comment]
@patrickhulce agreed 👍lets just keep in mind that this will only work for URL object, if any of the dependencies will try to `const { URL, URLSearchParams } = require('url')` or `require('url').parse('bla')` everything will 💥😱

**Comment by kdzwinel** [comment]
PR is up - https://github.com/samclarke/robots-parser/pull/8
