### ISSUE TITLE
[id] attributes on the page are not unique

### ISSUE THREAD

**Issue by shahraship** [GoogleChrome/lighthouse#4833]
Sometimes on a page you would find references to the unique id's. Lighthouse is reporting an error that they are not unique. Here is one example:
`
<svg version="1.1" id="logo_Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="73px" height="73px" viewBox="0 0 73 73" enable-background="new 0 0 73 73" xml:space="preserve">
   <g>
        <linearGradient id="C_SVGID_1_" gradientUnits="userSpaceOnUse" x1="16.1992" y1="14.8066" x2="8.4214" y2="25.7593">
		<stop  offset="0" style="stop-color:#676767"/>
		<stop  offset="1" style="stop-color:#343433"/>
	</linearGradient>
	<path opacity="0.9" fill="url(#C_SVGID_1_)" d="M24.601-0.022c0,0,15.349,0.148-2.998,16.77c0,0-8.461,7.406-12.344,14.248
		c0,0-8.545,14.754-9.111,7.911c0,0-0.359-1.599,0.101-5.213c0,0,0.116-1.289,0.936-3.488L13.422,6.964
		C13.422,6.964,16.67,0.935,24.601-0.022z"/>
   </g>
</svg>
`
Same would go with imagemaps and may be others.

**Comment by patrickhulce** [comment]
Thanks for filing @shahraship! I'm not sure I understand your issue. Are you saying that we should flag more elements? Increase our information on failure? You think you found a bug?

A public URL that demonstrates the issue you're observing would be helpful.

**Comment by shahraship** [comment]
Yes, I think I found a bug.

Try this link:
https://web-performance-dot-pwa-directory.appspot.com/lighthouse-viewer/?pwadir=5699203162963968

The error in Accessibility with id not being unique, I think is invalid. The error reported in there references to this link: https://coursables.com/assets/img/logo.svg

**Comment by patrickhulce** [comment]
There are duplicate elements with those IDs though?

![image](https://user-images.githubusercontent.com/2301202/37727407-f94e9134-2cf4-11e8-9f01-158b220b2ae1.png)

**Comment by shahraship** [comment]
I should have tested it like that. I've the image embedded on the page twice, which is resulting into the duplicate error. Now I'm wondering if I should embed the image in shadow dom, will the test still fail if I do that?

**Comment by patrickhulce** [comment]
Web best practice is to not use an ID for an element that isn't truly unique. Consider using a class if this is a repeatable element. If you prefer, from their [docs](https://dequeuniversity.com/rules/axe/1.1/duplicate-id), the suggestion is to rename repeat occurrences of the attribute to something unique.

**Comment by connorjclark** [comment]
https://github.com/dequelabs/axe-core/pull/1097 they already did this :)
