### ISSUE TITLE
404 page not found from "Learn more"

### ISSUE THREAD

**Issue by AndrewKGuan** [GoogleChrome/lighthouse#4840]
Lighthouse version 2.9.2
SEO > Page is blocked from indexing > Learn more
https://developers.google.com/lighthouse/audits/indexing
<img width="831" alt="screen shot 2018-03-21 at 3 21 31 pm" src="https://user-images.githubusercontent.com/31973638/37740681-d161b54e-2d1b-11e8-86af-491282b720fa.png">

**Comment by sdee3** [comment]
Getting the exact same thing over here for all of the websites I've been testing within the last 4 days.

**Comment by patrickhulce** [comment]
cc @kdzwinel was there a different doc URL we meant to link or has the page disappeared?

**Comment by kdzwinel** [comment]
Sorry, I'm not sure why it's 404, this link was last changed in #4678 by @kaycebasques

**Comment by patrickhulce** [comment]
Ah nice find! yeah looks like just missed web/tools :)
