### ISSUE TITLE
"First meaningful paint, "First Interactive" values  VS navigation-timing

### ISSUE THREAD

**Issue by vikramvi** [GoogleChrome/lighthouse#4846]
Please refer to https://www.w3.org/TR/navigation-timing/

5.1 Processing model

- In this is `domInteractive` equals `First Interactive`  ?

- What does  `First meaningful paint` equals to in the model diagram ?

**Comment by patrickhulce** [comment]
You won't find any of the metrics currently surfaced in w3 specs as they're very new and under discussion for how to standardize rather than already spec'd. You can find first contentful paint which we'll be surfacing soon in the [paint timing](https://www.w3.org/TR/paint-timing/) spec.

**Comment by vikramvi** [comment]
@patrickhulce  Thanks for quick clarification.
