### ISSUE TITLE
Best practices aspect ratio check doesn't say what

### ISSUE THREAD

**Issue by Enalmada** [GoogleChrome/lighthouse#4850]
I have alot of images on my site and there is a message saying displayed sizes should match their natural aspect ratio.  Please report which images violated the issue.

![image](https://user-images.githubusercontent.com/1892132/37792449-10122c9e-2dc9-11e8-9129-59a0f985d1df.png)

No big deal but note the grammar is off: "Does not uses Images"

**Comment by patrickhulce** [comment]
@Enalmada what version of Lighthouse are you using? This was a bug fixed in ~2.5.1

**Comment by Enalmada** [comment]
Hmmm...good question....

Chrome extension says 2.9.2:
![image](https://user-images.githubusercontent.com/1892132/37793031-c2abb752-2dca-11e8-9662-17765f844940.png)

But...I see at the bottom of the Audit Tab 2.5.1
![image](https://user-images.githubusercontent.com/1892132/37793148-07539ae6-2dcb-11e8-87d1-c27b42e68547.png)

**Comment by Enalmada** [comment]
Ok, when I run the extension I see the report from the newer version of Lighthouse.  Is there something I should/could be doing to make the audits tab lighthouse version more recent?

**Comment by patrickhulce** [comment]
You can try out [Chrome Canary](https://www.google.com/chrome/browser/canary.html) which is the latest build of Chrome built daily fresh off master :) 

If you're a little more comfortable sticking to stable and not dealing with the occasional bugs of canary, you can see if a new Chrome is available for download by visiting `chrome://settings/help`.
