### ISSUE TITLE
Changes in Section 508 compliance

### ISSUE THREAD

**Issue by jeandion** [GoogleChrome/lighthouse#4874]
We run reports with Lighthouse regularly. Recently, we've noticed a shift in compliance scores. Websites that once got compliant scores are now showing up as deficient. Has the algorithm been shifted, and if so, why?

**Comment by patrickhulce** [comment]
A few versions ago the weights of accessibility category were adjusted to more accurately reflect importance. Additionally, scores of 100 were no longer averaged in to your score when they were not applicable i.e. you don't get credit for having no image violations if your page didn't have any images to begin with. Both of these changes could impact overall scores quite significantly.

**Comment by paulirish** [comment]
Yup it was the change of introducing Not Applicable.
