### ISSUE TITLE
Lighthouse PWA audits pass even with a JPG icon

### ISSUE THREAD

**Issue by dfabulich** [GoogleChrome/lighthouse#4876]
Chrome "Improved A2HS" requires a PNG icon in the Web Manifest file, but Lighthouse doesn't mention this in its PWA audits.

To reproduce:
Create a PWA with a JPG icon in its `manifest.json`, like this:

```
{
  "name": "Example",
  "short_name": "Example",
  "icons": [
    {
      "src": "icon.jpg",
      "sizes": "1024x1024",
      "type": "image/jpg"
    }
  ],
  "scope": "https://www.example.com/my-url/",
  "start_url": "https://www.example.com/my-url/",
  "display": "standalone",
  "background_color": "#626160",
  "theme_color": "#626160"
}
```

Expected: Lighthouse PWA audit should flag this manifest as ineligible for Web App Install Banner, because there's no PNG icon in this manifest.

Actual: All audits pass

**Comment by patrickhulce** [comment]
Thanks for the report @dfabulich! We can do better on this check along with #789 too 👍
