### ISSUE TITLE
Surface which line in robots.txt is blocking indexing

### ISSUE THREAD

**Issue by russhuq** [GoogleChrome/lighthouse#4877]
CLI said the page is blocked for indexing but CDT said it isn't blocked, please see the video http://nimb.ws/oXGYa3.

**Comment by patrickhulce** [comment]
Thanks for the report and attached screencast @russhuq that really helps! ❤️ 

robots.txt files weren't checked until version [2.9.2](https://github.com/GoogleChrome/lighthouse/releases/tag/v2.9.2) which is why you're seeing it pass in 2.8

**Comment by russhuq** [comment]
Thanks for the reply @patrickhulce! 

Which specific robots.txt instruction is causing the page to get blocked would you guys consider adding this feature as well?

**Comment by patrickhulce** [comment]
@kdzwinel how difficult is it to add the blocking directive to the table like OP is wanting?

**Comment by kdzwinel** [comment]
Apparently @samclarke predicted that feature request, because he added [getMatchingLineNumber](https://github.com/samclarke/robots-parser#getmatchinglinenumberurl-ua) in robots-parser v2.1.0 🎉 I'll be happy to implement it as soon as #4875 lands.
