### ISSUE TITLE
DevTools: Allow text selection in the report

### ISSUE THREAD

**Issue by Eccenux** [GoogleChrome/lighthouse#4880]
Quick win. Would be helpful to be able to select text from some recommendation to either find out more about them (search in google) or copy example code (e.g. for the theme-color meta tag).

**Comment by patrickhulce** [comment]
Aye this is a DevTools limitation at the moment, the report from extension and CLI are both fully selectable if you want an immediate fix :)

![image](https://user-images.githubusercontent.com/2301202/38040477-72917dda-3264-11e8-8306-0a978ced5b6e.png)

**Comment by paulirish** [comment]
Verified still an issue in 68
But fixed in 70. (and probably 69)

\o/
