### ISSUE TITLE
Different audit results between Chrome versions?

### ISSUE THREAD

**Issue by strtw** [GoogleChrome/lighthouse#4887]
I noticed that there were some differences between the audit results in Chrome Canary and Chrome Stable  65.0.3325.181. I also saw differences between Canary and Stable vs 63.(some version). To limit my scope I audited on performance only.

I want to use Audits to improve performance but on the website I was testing there were such large differences between the browsers I wasn't sure which audit to trust. I was using Canary in the first place because using its local overrides feature I could modify the site html on their production site. 

I've attached two reports I ran on www.google.com which also displayed significant differences. I ran the reports several times and cleared cache between runs to see if the differences persisted and they did.

[google-canary.txt](https://github.com/GoogleChrome/lighthouse/files/1858157/google-canary.txt)
[google-stable.txt](https://github.com/GoogleChrome/lighthouse/files/1858158/google-stable.txt)

**Comment by patrickhulce** [comment]
@strtw in m67 we introduced a toggle to enable/disable throttling and it looks like you've disabled throttling in canary. Throttling was enabled by default in prior versions. Can you confirm this is the case?

**Comment by strtw** [comment]
@patrickhulce Thanks for the tip! Yes I did have throttling disabled, reran the audit with "clear storage" enabled and results were much closer - results attached. The canary report was much larger than the chrome report, just curious as to why.


[reports.zip](https://github.com/GoogleChrome/lighthouse/files/1858203/reports.zip)

**Comment by patrickhulce** [comment]
Canary also has the "View Trace" button which takes you over to the performance panel to view the details of the page load we examined, the trace is quite large (usually ~5-50 MB)

**Comment by strtw** [comment]
Thanks for the info feel free to close issue.

**Comment by univhack** [comment]
I am definitely seeing major differences in the lighthouse results between version 66 and 67 of chrome. Last week I took the following screenshot of lighthouse:


![image](https://user-images.githubusercontent.com/4080811/40818918-a71d1a5a-6527-11e8-842e-79c1e7b93712.png)



**Then even though the code is incredibly similar with no major changes here is what I am getting:**




![image](https://user-images.githubusercontent.com/4080811/40818985-fc28d890-6527-11e8-9a20-0c1db3e1e8d3.png)


It's saying the first meaningful paint is 12.5 secs and first interactive is 17.5 secs. However, in the network tab it says that the DomContentLoaded event was triggered at 143 ms and that the Load event was triggered at 793 secs and it's only loading 432 Kb which is very mobile and slow network friendly so I am totally puzzled as to what could be causing the new version of lighthouse to produce those results :/  



![image](https://user-images.githubusercontent.com/4080811/40819034-36309294-6528-11e8-9f93-48942fa4ee84.png)
