### ISSUE TITLE
link[rel=stylesheet] with incorrect media doesn't block first paint

### ISSUE THREAD

**Issue by nazar-pc** [GoogleChrome/lighthouse#4888]
Consider following:
```html
<link rel="stylesheet" href="dist/style.min.css?35990" media="async">
```

`[media=async]` is intentionally set to incorrect value, so that browser will load it, but will not block rendering (according to https://keithclark.co.uk/articles/loading-css-without-blocking-render/). Later in asynchronously loaded script I remove this attribute and everything is fine.

Audit for desktop works fine here, but audit for mobile devices still complains that stylesheet blocks first paint, while in fact it doesn't.

UPD: The same also happens for desktop.

**Comment by paulirish** [comment]
we think this was fixed in https://github.com/GoogleChrome/lighthouse/commit/d0d83efd263b3265a8d28b83e31ad58477e186f2

:)
