### ISSUE TITLE
font stops working after lighthouse

### ISSUE THREAD

**Issue by Enalmada** [GoogleChrome/lighthouse#4889]
After running lighthouse chrome plugin 2.9.3, a font stops working due to missing cors attributes until I Application > Clear site data.  My uneducated guess is that during lighthouse test, it is calling the font without crossorigin=anonymous which is corrupting the browser cache.

This may or may not be relevant but for full transparency...
I am preloading the css using [loadCSS](https://github.com/filamentgroup/loadCSS) method.  I also have a service worker runtime caching only non-opaque results.

You can try this yourself on https://www.gelltest.com/home (note the bell icon in the top right corner).

**Comment by patrickhulce** [comment]
Oh wow good find @Enalmada thanks for reporting! We should be automatically clearing the cache after we run to fix this 👍

**Comment by Enalmada** [comment]
Yes, automatically clearing the cache after a run would be perfect!

**Comment by paulirish** [comment]
cc @midzer wanna try this: clearing cache after the run?
it'll go in gather-runner.

**Comment by midzer** [comment]
Looks like an easy one. PR coming in a moment.
