### ISSUE TITLE
Properly account for non-top-level `toplevel` tasks for estimating input latency

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#489]
@skyostil says:

"The Blink scheduler runs several tasks within a single message loop iteration to reduce the overhead of going in and out of the loop. Here's an example:

![1d4d6c54-405a-4432-81f1-1acef5f731fb](https://cloud.githubusercontent.com/assets/316891/16472071/30cba0e0-3e16-11e6-9464-4bf47a177664.png)

There's just one `MessageLoop::RunTask` at the top, but three `TaskQueueManager::ProcessTaskFromWorkQueue`, i.e., three actual tasks that ran.

To avoid hardcoding too much I suggest you look for the innermost slices with the "toplevel" category. This should land you at `ProcessTaskFromWorkQueue` on the main thread and should also work with Lucky Luke on the browser side....

Input can sneak in at any time between `ProcessTaskFromWorkQueue`-- no need for it to go via the message loop."

**Comment by patrickhulce** [comment]
should be addressed by #2013
