### ISSUE TITLE
Running Lighthouse signs out the current user out of a Firebase App

### ISSUE THREAD

**Issue by MartinMikusat** [GoogleChrome/lighthouse#4890]
When I'm signed in using Google on my website and run the Lighthouse audit from the Dev Tools, it signs me out and runs the audit on the login page. Considering that page is basically empty, I get back a mostly useless audit. 

Here's the site
https://dashboard-1e74f.firebaseapp.com/

Did I miss something when running the test, is it related to Firebase or is it something completely different?

**Comment by patrickhulce** [comment]
You probably want to run with the flag `--disable-storage-reset` or in DevTools in Chrome Canary flip the dropdown from 'Clear storage' to 'Preserve storage'. We currently clear localstorage/indexeddb/etc before the run which is likely why you're being logged out.

**Comment by MartinMikusat** [comment]
Thanks, that works. At least the option of using Chrome Canary does. I tried using the CLI, but I'm not signed in using that in the first place and I didn't have time to figure how to sign in, if it's even possible.
