### ISSUE TITLE
Audits for contexts with connectivity, data cost, device, power and browser constraints

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#490]
A bug to gauge what Lighthouse could/should test for in contexts with any of the following constraints:

• Low bandwidth (poor 3G or worse) and high latency (RTT times).
• High data cost (such as data-roaming scenarios or contexts where data is expensive relative to median income).
• Low-spec devices (limited CPU, memory and storage).
• Small, low-spec screens (small viewports, low display quality, increased proportion interaction failures).
• Limited access to power (devices with limited battery life, contexts without access to a reliable, affordable power supply).
• 'Non-evergreen' browsers such as UC and IE8.

More detail about these concerns here: [developers.google.com/web/billions](https://developers.google.com/web/billions). 

Data, information and tools [here](https://docs.google.com/document/d/1LV55gzhvvfIvCTrn9yx6kvRrtXgjxIrzbQT-hSLcHZ0).

The audits I'm proposing are:
• Works well on browsers such as UC Browser and IE 8: fallbacks or alternatives for CSS calc(), semantic elements, etc.
• Page weight: warning for >xxMB total, with data for data (money) cost.
• Number of requests: warning for >xx requests total, with data for potential RTT time.
• Effective content design for small, low-spec screens (not just viewport size — see example [here](https://developers.google.com/web/fundamentals/design-and-ui/content/viewport)).
• Works well with limited CPU, memory and storage.
• Power (battery) consumption.

Hard to work out how to test for some of these — and not sure how best to prioritise.

**Comment by samccone** [comment]
> • Works well on browsers such as UC Browser and IE 8: fallbacks or alternatives for CSS calc(), semantic elements, etc.

^ are you considering that we have common gotchas that we scan for? such as missing css prefixes? using es2015 features ... using unsupported DOM apis?

Those three items are the most common issues that I have found when I have been working with UC browser.

**Comment by samdutton** [comment]
> are you considering that we have common gotchas that we scan for? such as missing css prefixes? using es2015 features ... using unsupported DOM apis?

Yes — my examples are HTML and CSS, but I was also thinking of unsupported JavaScript APIs and syntax.

**Comment by paulirish** [comment]
+1 for showing a diagnostic on total page weight:

* Total byte weight of page: 32,432Kb. ($$$$)


IMO the request count, limited CPU things should be addressed by other perf metrics. same with battery and memory efficiency.

**Comment by paulirish** [comment]
Here's how webpagetest integrates whatdoesmysitecost:

https://github.com/WPO-Foundation/webpagetest/blob/566e0c77b117412630cb047aab6b037b49c605bb/www/include/RunResultHtmlTable.php#L324-L339

**Comment by paulirish** [comment]
duping this into #584
