### ISSUE TITLE
Properly Sized Images -> Potential Savings 100%

### ISSUE THREAD

**Issue by alexckent** [GoogleChrome/lighthouse#4908]
Hello, most of my images are reporting a potential saving of 99% or 100%. 100% shouldn't be possible.
Site is: https://GoE.ac/
![image](https://user-images.githubusercontent.com/6452347/38190101-a803d518-365a-11e8-9496-db4c7452d9ae.png)

**Comment by midzer** [comment]
I think this is related to offscreen images and should have been fixed with https://github.com/googlechrome/lighthouse/pull/4487
What version of LH are you using, @alexckent ?

**Comment by alexckent** [comment]
@midzer LH 2.8.0  included with Chrome 65.0.3325.181 (Official Build) (64-bit)

**Comment by midzer** [comment]
This change comes with https://github.com/GoogleChrome/lighthouse/tree/v2.9.1
So either install latest LH extension manually or wait for new Chrome v66 which should upgrade LH version as well.

**Comment by alexckent** [comment]
Thanks @midzer - have installed LH as an extension and that appears to fix the problem.
