### ISSUE TITLE
refactor so browser driver isn't instantiated if not running gather stage

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#491]
it is convenient to be able to [inject it into the runner](https://github.com/GoogleChrome/lighthouse/blob/c81118b65d95dcc918b499393db65ca7d9f853af/lighthouse-core/index.js#L54) since we differentiate on extension vs CRI driver at that point, but anyone using lighthouse purely as an artifact processor is never going to need the driver.

Not a huge priority right now since the CLI version doesn't do much in the driver constructor, but this should probably go.

**Comment by paulirish** [comment]
Think this is closable. Our processor-only run is satisfactory for now.
