### ISSUE TITLE
Cross-reference Critical Rendering Path (CRP) resources in the redirects table

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#4911]
I did a quick perusal of the redirects audit source code, didn't look like it was doing any cross-references with the CRP. This would help developers prioritize what redirects to set up first. I'm just picturing another column in the table, with each cell having a boolean indicating whether it's part of the CRP.

**Comment by paulirish** [comment]
The Redirects audit only considers the request for the initial HTML document. If there are redirects for other subresources, we don't care about them right now.

So the audit only shows ONE file's request chain. And it is in the CRP because it's the most critical of all of them. :)
