### ISSUE TITLE
yargs throws errors for CLI

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#492]
@wardpeet This seems to be related to your work. I get

```node
TypeError: yargs.help(...).version(...).showHelpOnFail(...).usage(...).group is not a function
```

I've tried version 3.30.0 that's in the package.json, as well as upgrading to 4.7.1, but neither is playing ball. I'll keep plugging away, see if I can figure out what's what.

**Comment by paullewis** [comment]
Doing a quick sorted list of everything that yargs contains I get:

```js
[ '$0',
  'addHelpOpt',
  'alias',
  'argv',
  'array',
  'boolean',
  'check',
  'command',
  'completion',
  'config',
  'count',
  'default',
  'defaults',
  'demand',
  'describe',
  'epilog',
  'epilogue',
  'example',
  'exitProcess',
  'fail',
  'getCommandHandlers',
  'getDemanded',
  'getExitProcess',
  'getOptions',
  'getStrict',
  'getUsageInstance',
  'getValidationInstance',
  'help',
  'implies',
  'nargs',
  'normalize',
  'option',
  'options',
  'parse',
  'parsed',
  'require',
  'required',
  'requiresArg',
  'reset',
  'resetOptions',
  'showCompletionScript',
  'showHelp',
  'showHelpOnFail',
  'strict',
  'string',
  'terminalWidth',
  'usage',
  'version',
  'wrap' ]
```

Which doesn't include group... but group is listed [in their docs](https://github.com/yargs/yargs/tree/v3.30.0#groupkeys-groupname)... wat?

**Comment by paullewis** [comment]
Same, incidentally, for 'choices'.

**Comment by paullewis** [comment]
Ignore me... well, a fresh clone and npm install of Lighthouse seems to have resolved it. Score an 11 for weird.

**Comment by wardpeet** [comment]
ok np :) if it happends again just let me know than I can have a look.
