### ISSUE TITLE
First Interactive need an explanation

### ISSUE THREAD

**Issue by wizardnet972** [GoogleChrome/lighthouse#4923]
I'm trying to understand the logic of lighthouse.

There are three steps that indicate the performance right?
- First Meaningful Paint
- First Interactive
- Consistently Interactive

Let's talk about "First Interactive" state. when does lighthouse indicate that it's done waiting? when the all the scripts are loaded? when the DOMContentLoaded event starts firing/done? some other event? or maybe just after specific seconds?

**Comment by vinamratasingal** [comment]
Hi! We have some docs that might be able to help: 

CI: https://developers.google.com/web/tools/lighthouse/audits/consistently-interactive
FI: https://developers.google.com/web/tools/lighthouse/audits/first-interactive
FMP: https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint

Let us know if you have questions after reading the docs.

**Comment by paulirish** [comment]
@wizardnet972 this recent deck should also help: [Perf Metrics - #PerfMatters March 2018 - Google Slides](https://docs.google.com/presentation/d/1UcjvtuMT4VAmc-MySWOcc1rLkMNoDjt2DxIhvfHNRXg/present)

And the reference docs it mentions:

* [Time To Interactive Explainer](https://docs.google.com/document/d/1l50v3ljDeUmj9qBsfdPc3wKe_1CY5KFYI1baye2NhYk/edit)
* [Time to Interactive: v1.0](https://docs.google.com/document/d/1yE4YWsusi5wVXrnwhR61j-QyjK9tzENIzfxrCjA1NAk/edit)
* [Time to First Interactive - Task Cluster Definition](https://docs.google.com/document/d/12UHgAW2r7nWo3R6FBerpYuz9EVOdG1OpPm8YmY4yD0c/edit)

--- 

also sounds like Patrick answered your concerns on gitter.
