### ISSUE TITLE
Add option to switch between aXe's a11y WCAG tests and 508 tests

### ISSUE THREAD

**Issue by trycrmr** [GoogleChrome/lighthouse#4924]
Hi there! I am experimenting with using Lighthouse to audit our web applications for accessibility. In my line of work we use DHS's accessibility guidelines for meeting Section 508 compliance [(link to guidelines, PDF)](https://www.dhs.gov/sites/default/files/publications/DHS%20Section%20508%20Compliance%20Test%20Process%20for%20Applications%203.3.pdf) . 

In my initial review of Lighthouse it seems Lighthouse's Accessibility Audit uses the [W3C's Web Content Accessibility Guidelines (WCAG)](https://www.w3.org/TR/WCAG20/) to guide what it tests and how it reports. Is this assessment accurate or is there a way to run Lighthouse's Accessibility Audit against Section 508's guidelines and report the results in terms of Section 508 instead of WCAG? Thanks in advance, your assistance is much appreciated!

**Comment by robdodson** [comment]
Adding the ability to toggle between aXe's WCAG tests and 508 tests might be possible. We'd need to come up with some UI design.

**Comment by paulirish** [comment]
@trycrmr you can see here where Lighthouse says we want to use all the WCAG Level A and AA rules:
https://github.com/GoogleChrome/lighthouse/blob/90023e3d7badfde22afe8cfd7947fe4ce668ced8/lighthouse-core/gather/gatherers/accessibility.js#L19-L27

aXe also supports the `section508` tag: https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#options-parameter-examples

So I think what you're asking for is replacing the `wcag2a`&`wcag2aa` with `section508`. Indeed, the UI side of this is tricky, so it'll be a while till we can provide a good solution. In the meantime, you could run a local lighthouse CLI and make this small change.

**Comment by bgarrant** [comment]
We need to get this.  Are we any closer to being able to select the testing level in Dev Tools?

**Comment by patrickhulce** [comment]
@bgarrant no we are not. If you need a very specific set of a11y checks you should look into using axe directly.
