### ISSUE TITLE
Lighthouse stuck

### ISSUE THREAD

**Issue by masiama** [GoogleChrome/lighthouse#4930]
![screen shot 2018-04-05 at 14 59 42](https://user-images.githubusercontent.com/14037820/38364677-45476ff4-38e2-11e8-8cdd-a22d03fd2e06.jpg)

I started an audit, it fastly got till the moment on image above and stuck. I waited almost hour but no progress. Then I tried to run audit in new tab with different website and there I got this:

![screen shot 2018-04-05 at 15 04 50](https://user-images.githubusercontent.com/14037820/38364813-b649587a-38e2-11e8-8dcd-468fd14f9c20.jpg)
it also navigates to about:blank

And this:
![screen shot 2018-04-05 at 15 06 11](https://user-images.githubusercontent.com/14037820/38364871-e9d35420-38e2-11e8-94d4-c865f8d0606b.jpg)

**Comment by patrickhulce** [comment]
Sorry you ran into this @masiama! Sometimes Chrome hangs trying to collect a trace and there's not really anything LH can do about it; the only real fix is killing the process and restarting Chrome.
