### ISSUE TITLE
I/O PR Review Policy Proposal

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#4934]
This is a proposal to introduce a new PR label: "I/O-Expedite". Any PR with this label will have certain expectations around review timelines before it can just be merged without explicit approval. The goal of this is to ensure v3 priorities have proper chance for review while still enabling us to meet I/O timelines.

When a PR is first labelled as "I/O-Expedite", each member of core team has 8 working hours<sup>1</sup> to give their initial review. After feedback has been addressed and the author requests re-review, the reviewers have 4 working hours to request more changes.

A priority PR can be merged when Travis is green and one of the following conditions have been met:
* All reviewers<sup>2</sup> approve
* 8 working hours have elapsed without any feedback
* 4 working hours have elapsed since addressing/responding to all feedback<sup>3</sup> without further reviewer<sup>2</sup> comments

<hr>

<sup>1</sup> = M-F 10am-6pm PST
<sup>2</sup> = A reviewer is any person who provides feedback within the initial 8 working hour window
<sup>3</sup> = notice must be given in PR that feedback has been addressed and PR is ready for re-review

**Comment by patrickhulce** [comment]
@paulirish @brendankenny this SG?

**Comment by paulirish** [comment]
> M-F 9am-6pm PST

10-6? :)

> After feedback has been addressed and the author requests re-review, the reviewers have 4 working hours to request more changes.

Is this just for a re-review whether its approval or not?

**Comment by patrickhulce** [comment]
> 10-6? :)

ya :)

> Is this just for a re-review whether its approval or not?

Not 100% I understand the question, but I intended that sentence to mean that once an author has replied to all comments/made all requested changes, the reviewer has 4 hours to get back to them before the author is allowed to assume that the reviewer has given their approval :) If the reviewer gets back to them with more requested changes, then the clock resets

**Comment by paulirish** [comment]
It was a success.

Thanks @patrickhulce and also for everyone's participation.
