### ISSUE TITLE
The changes in the latest master branch haven't been released yet.

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [GoogleChrome/lighthouse#4946]
I have noticed there is a significant change of replacing `/lighthouse-core/config/perf.json` with `/lighthouse-core/config/perf-config.js` five days ago.
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/perf-config.js

However, the latest release version is the one released 14 days ago. https://github.com/GoogleChrome/lighthouse/releases/tag/v2.9.4

Could you please double-check and confirm if the new release is coming soon? 
So I can modify my project to use `perf-config.js`.

Regards,
Joe

**Comment by paulirish** [comment]
Hey Joe!

Technically you can always depend on what's in github master (or a specific SHA) from your `dependencies`.

We'd recommend using 2.9.4 until we have a beta release of 3.x ready. 
There are multiple breaking changes we will be documenting.


Can I ask how you're using the perf config?

**Comment by JoeRattanamaneesilp** [comment]
@paulirish I just changed the configuration file from `perf.json` to `full-config.js`. The existing test is working fine with that configuration file. All good now.
