### ISSUE TITLE
Is there a way to measure FPS while the page scrolling？

### ISSUE THREAD

**Issue by devrsi0n** [GoogleChrome/lighthouse#4947]
I search many source files, issues, docs in this repo, still can't find a way to measure  FPS(Frames Per Second) while the page scrolling. Any ideas? 
Thanks for your patience.

**Comment by midzer** [comment]
This might be interesting to measure. Especially mobile when JavaScript heavy code is executed on `onscroll` handler which might lead to laggy user experience.

You could check whether `requestIdleCallback()` is used for example with graceful downgrade to `requestAnimationFrame()` if first is not available.

**Comment by devrsi0n** [comment]
I resolved this problem by adding those commands to chrome flags

* --show-fps-counter
* --enable-logging
* --v=1
* --vmodule="head*=1"

those commands make chrome outputting page's FPS to log file, I just need to parse it.Thank you, guys.
