### ISSUE TITLE
false negative "Form elements do not have associated labels"

### ISSUE THREAD

**Issue by JustFly1984** [GoogleChrome/lighthouse#4993]
I have custom input type number in my form, I also use eslint-plugin-a11y. This is my html, which gives false negative on #date-year input/label pairs in lighthouse

```
<label class="_1DlQ3 _3R713" for="date-year">
  Year
  <div class="_1T1WW _21GYC">
    <button aria-label="minus" class="_37Bh1">
      <div class="_3CR_3 _3REq5 M9WNo">
        <svg viewBox="0 0 16 16">
          <path fill="currentColor" d="M0,7c16,0,16,0,16,0l0,0v2H0"></path>
        </svg>
      </div>
    </button>

    <input type="number" aria-live="polite" aria-atomic="true" id="date-year" class="_2I5TO _3bdCp _3waAi _3rENR" value="2018" min="2017" max="2020" step="1">
 
    <button aria-label="plus" class="_3qHF4">
      <div class="_3CR_3 _3REq5 M9WNo">
        <svg viewBox="0 0 16 16">
          <path fill="currentColor" d="M16,7c0,0-0.007,0-7,0V0H7v7C5.096,7,2.797,7,0,7v2h7v7h2V9h7V7z"></path>
        </svg>
      </div>
    </button>
  </div>
</label>
```

This is the link, you can see there is custom date-picker with 5 elements of this kind of inputs.
https://www.taximow.com/en/transfer/train-from/

**Comment by JustFly1984** [comment]
How come you are unable to load the url? It is publicaly available.

**Comment by paulirish** [comment]
dunno, here's what i see

![image](https://user-images.githubusercontent.com/39191/39031565-df5901ca-441d-11e8-9949-1827042ef79c.png)

this points to DNS resolving differently everywhere... 
![image](https://user-images.githubusercontent.com/39191/39031634-4d2e3e9a-441e-11e8-8d97-dc7cb2524c98.png)

weird.

**Comment by JustFly1984** [comment]
That is really weird, cos I host my website on netlify.com CDN, which in
turn based on AWS. I already had complains about access to my website from
Luxembourg ISP which is also weird. Can you please describe your location?
I need to investigate, why does my website is unaccessible in some
countries.

BTW Paul, I love your youtube videos, Thank you a lot!
PS. Can you try to visit my website from VPN or something?

2018-04-20 13:09 GMT+08:00 Paul Irish <notifications@github.com>:

**Comment by tekbasse** [comment]
@JustFly1984 Try wrapping the LABEL tag around the INPUT tag, or replacing LABEL with a FIELDSET and embedded LEGEND tag. There may be a conflict in wrapping a label around BUTTON and INPUT tags --a browser may have focus issues.  I had a similar issue that was resolved when I substituted FIELDSET/LEGEND in place of LABEL.

**Comment by khjohnson1972** [comment]
I am having this same issue. I have an input type="number", with a label. I am baffled.
You can view the page/form at https://www.minnesotaculligan.com. This is a simple form with a single input.
