### ISSUE TITLE
Lighthouse results not being displayed

### ISSUE THREAD

**Issue by pushkar-anand** [GoogleChrome/lighthouse#4994]
Results are not being displayed after running lighthouse. A blank page with only headers is opened.
Screenshot:

![screenshot from 2018-04-19 19-35-58](https://user-images.githubusercontent.com/13116715/38996502-f764bd8c-4408-11e8-8b28-767af31ad811.png)

> Runtime environment
> User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
> Device Emulation Nexus 5X: Enabled
> Network Throttling 562.5ms RTT, 1.4Mbps down, 0.7Mbps up: Enabled
> CPU Throttling 4x slowdown: Enabled

**Comment by pushkar-anand** [comment]
This is not necessarily a bug I hadn't selected any audit categories to include in the options when I faced this issue. I found this out later. Probably user should be notified or prompted if nothing is included.

**Comment by wardpeet** [comment]
sounds like a good idea, maybe we should put it in the report when no data can be found.

**Comment by pushkar-anand** [comment]
Exactly. I wasted a lot of time trying to figure out what went wrong before filing this issue and later realising I had not selected any tests to report.

**Comment by paulirish** [comment]
Fixed in the extension.
