### ISSUE TITLE
Lighthouse Audits Fail Incorrectly

### ISSUE THREAD

**Issue by visha78** [GoogleChrome/lighthouse#5004]
I run the Lighthouse audit on our website and it is failing in some areas where it shouldn't.

For example:

1.  In the Progressive Web App audit, it returns "Does not have a `<meta name="viewport">` tag with width or initial-scale" -
Our site has the following tag: `<meta name="viewport" content="width=device-width, initial-scale=1.0" />`

2.  In the SEO audit, it returns "Document does not have a meta description" -
Our site has the following tag: `<meta name="description" content="Our site's meta description is not empty. Lore Ipsum." />`

Is it a bug or are we doing something wrong?

**Comment by patrickhulce** [comment]
@visha78 is your site publicly available at a URL you're willing to share?

**Comment by visha78** [comment]
Yes: https://www.riamoneytransfer.com/

**Comment by patrickhulce** [comment]
Ah, yes it is a bug on your site. You've put these meta tags in the `body`, but they belong in the `head`.

**Comment by patrickhulce** [comment]
but they're not?
![image](https://user-images.githubusercontent.com/2301202/39065134-ae3e3db8-4485-11e8-86f7-16de944c2c8e.png)

**Comment by visha78** [comment]
@patrickhulce I see the tags within the `<head> </head>` while viewing source. Now I'm confused. Ok, thanks for pointing that out!

**Comment by patrickhulce** [comment]
oh wow, yikes! yeah something must be mucking with the source before the tags can be used. best of luck tracking that down!
