### ISSUE TITLE
Locale Support

### ISSUE THREAD

**Issue by sgryschuk-va** [GoogleChrome/lighthouse#5007]
Will lighthouse support different locales?

PageSpeed insights does and has a lot of the same content
https://developers.google.com/speed/docs/insights/v4/reference/pagespeedapi/runpagespeed

**Comment by ev1stensberg** [comment]
Willing to work on this, but what do you mean with locale? Formatting scores to be displayed for certain languages or formats?

**Comment by sgryschuk-va** [comment]
Specifically, translations for the explanations and instructions

**Comment by patrickhulce** [comment]
I think we need to do a bit of scoping before we jump in on impl for this one @ev1stensberg. 

A few things to figure out:
- What channels would this affect/how would it be distributed?
    - DevTools doesn't offer translations, so we wouldn't apply it there
    - Extension as an option based on Chrome lang?
- How does this impact linked docs/who maintains those?
- How does this impact our PR process for text changes?
- How high a priority is this/which languages are most urgent?

We'll try and tackle some of these questions in our next triage post-I/O :)

**Comment by zomars** [comment]
May I suggest starting with the [Lighthouse Report Viewer](https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-viewer) ? I think it would be the easiest to implement IMO. We can export download the json regardless of locale, uploaded to the report viewer and switch the locale in there. Am I crazy?

**Comment by paulirish** [comment]
We support locales now (in master branch). :)

This was tracked mostly by the #5719 ticket
