### ISSUE TITLE
Prestashop based site rarely produces a first meaningful paint

### ISSUE THREAD

**Issue by johanlantz** [GoogleChrome/lighthouse#5015]
**Issue**
I am testing various combinations of the Prestashop e-commerce platform and the normal result is a Performance score of 0 due to no meaningful first paint. Rarely I get a higher value around 50 but the majority of the time it gets a 0. I have the feeling that this have become worse since I tested lighthouse the first time a couple of months ago. I recall having decent values then.

**How to reproduce**
I run my tests using vanilla installations of Prestashop 1.7 and Thirtybees (which is a Prestashop 1.6 fork). You can test yourself by running Lighthouse on tbtest.givensa.com or oneseven.givensa.com

**Expectations**
The http://oneseven.givensa.com site has a 99% GTMetrix and 89% YSlow score.
Both instances performs well during normal use but Lighthouse usually says Performance 0 due to no FMP or infrequently produces a real score around 50. 

I have also tested the same Prestashop 1.7.3.1 installation on my Macbook using XAMPP and using the Lighthouse node-js tool towards localhost produces similar results.  If I just do a visual inspection, accessing the Prestashop installation on my localhost I have instant rendering (which makes sense). However when I point the Lighthouse node-js tool towards localhost it says the fmp is close to 7 seconds and first interactive beta is over 9 seconds ( is this due to 3g simulation).

I also tried accessing the site using a 3g connection on my iPhone and it has no problems rendering, I estimate it to take less than 3 sec.

Is it possible that something with Prestashop is causing Lighthouse to have issues with the first meaningful paint? Again, if I do not remember incorrectly, I got decent values for the same setup a few months back.

I tried some other sites from the Prestashop showcase list on their webpage and they also report a 0 performance score.

**Comment by johanlantz** [comment]
hmm, also tried my hosting provider which is a static webpage (www.loading.es) and that also givensa a 0 score with no fmp.

**Comment by patrickhulce** [comment]
Thanks for reporting @johanlantz I'm able to reproduce this! Really strange we'll have to dig into this a bit.

**Comment by johanlantz** [comment]
[Givensa.com](http://givensa.com) is the live site based on PS 1.5. Very old platform

Then I have setup the following test sites:

//This tests the Thirtybees platform based on prestashop 1.6
https://tbtest.givensa.com 

//This tests the latest 1.7 version of Prestashop
http://psos.givensa.com 

After running Lighthouse a couple of times, I no longer see the no meaningful paint issue (I notice Lighthouse has been updated since I last tried and I did not test in local, only on the hosting).

I will test some more but indeed it looks like something has been solved in Lighthouse since my last tests

**Comment by SpawnTree** [comment]
Despacito@@

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
