### ISSUE TITLE
issues during the streaming by soundcloud radio to facebook "live" sessions...

### ISSUE THREAD

**Issue by Lightoftheultimate1** [GoogleChrome/lighthouse#5043]

**Comment by Lightoftheultimate1** [comment]
I have archive to cast but not the thing I was expecting, could you give me a path to follow plz
Thanks

**Comment by patrickhulce** [comment]
@Lightoftheultimate1 what led you to posting here? I'm not sure why you believe this repo is the right place to be looking for soundcloud/facebook help 😄
