### ISSUE TITLE
Feature Request: Preview articles relative to categories on hover

### ISSUE THREAD

**Issue by ev1stensberg** [GoogleChrome/lighthouse#5093]
When hovering a headline/title it would be nice to show a link to a page that shows tips for the user if their lighthouse score is too low for a 75% threshold. 
<img width="752" alt="skjermbilde 2018-05-03 kl 02 11 35" src="https://user-images.githubusercontent.com/16735925/39555177-7c1848c8-4e77-11e8-820d-cf61059a1dbe.png">

From the screenshot, if the user hovers over the performance category, then he/she should have a quickview to an article that shows steps to improve their performance (if score is below 75%). 

WDYT?

**Comment by patrickhulce** [comment]
Interesting idea! It's our hope that the opportunities section can act as first steps to take to improve their performance, any ideas how to make that clearer? If you want a sneak peak at what's on the horizon we're adding number/steps to the opportunities :) 

Example report from #5115 https://lonely-lumber.surge.sh/cnn.html

**Comment by ev1stensberg** [comment]
Sounds like it's one option, but maybe a read about why it's important and how would make people act on it?

**Comment by patrickhulce** [comment]
Ah yeah, we've got some posts in the works for this we can eventually link to 👍
