### ISSUE TITLE
DevTools Error: The asynchronous expression exceeded the allotted time of 60

### ISSUE THREAD

**Issue by Richardchuah** [GoogleChrome/lighthouse#5097]
**Initial URL**: https://www.paypal.com/businessprofile/settings/name/edit#
**Chrome Version**: 66.0.3359.139
**Error Message**: The asynchronous expression exceeded the allotted time of 60s
**Stack Trace**:
```
Error: The asynchronous expression exceeded the allotted time of 60s
    at _ (chrome-devtools://devtools/remote/serve_file/@a020eddf0d85fe84d4a6787b304f50aafb670969/audits2_worker/audits2_worker_module.js:835:120)
```

**Comment by patrickhulce** [comment]
Hey @Richardchuah we're unable to reproduce this on Canary. Does it happen every run for you?

**Comment by povesma** [comment]
Happens to me on a heavy loaded computer (in Docker, headless mode, 8 cores, 16Gb RAM) OR when more than 1 instance of Chrome is launched with chrome-launcher.
How to reproduce:
Create docker with https://github.com/ebidel/lighthouse-ci/blob/master/builder/Dockerfile
Run 4+ concurrent instances of Lighthouse. Pretty fast you'll get it (weaker hardware, faster it happens).

**Comment by paulirish** [comment]
duping into #5625
