### ISSUE TITLE
Accessibility check doesn't include a check for background video/motion without controls

### ISSUE THREAD

**Issue by jenstrickland** [GoogleChrome/lighthouse#5104]
Tested a site with multiple uses of background video without controls and the report didn't mention anything about this. Inspecting the code, it appears it might be possible to set rules for the video element and whether or not controls are hidden or accessible. As a UX designer and front-end dev I am not as savvy about what can be done, but hoped to help by submitting an issue. Happy to help, provide the site url, if you like. Thank you so much for Lighthouse — I'm a huge fan!

**Comment by paulirish** [comment]
hiya @jenstrickland ! 

all our accessibility audits come via https://github.com/dequelabs/axe-core
see https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md

It doesn't looks like that has come up before in their issue tracker, but that's the right place to discuss it.  Can you do me a favor and file the same issue upstream there? :)

thanks

**Comment by patrickhulce** [comment]
thanks for filing it upstream @jenstrickland! closing this now, since we'll automatically pick it up when it appears in axe 🎉
