### ISSUE TITLE
Print or Save to PDF of a report only results in a single page.

### ISSUE THREAD

**Issue by mandclu** [GoogleChrome/lighthouse#5119]
I was looking at https://github.com/GoogleChrome/lighthouse/issues/3564 but I think I have an issue that is somewhat different. If I open my Lighthouse report in its own window I can go up to the File menu and select "Print" but the result is always a single page, when using either the Chrome print dialog or the MacOS print dialog. It is possible to manually scroll up and down the report and change what is on the printed/saved page (and therefore manually assemble a full printout, albeit with extra effort). It would be better if it was able to simply print or save to PDF the entire report, as one does with a standard web page.

**Comment by patrickhulce** [comment]
Hm, I don't see this behavior. This is the report from the extension or CLI?

Have you tried using the "Print Expanded" option from the share dropdown?
![image](https://user-images.githubusercontent.com/2301202/39637807-effcbdda-4f78-11e8-9929-f4af0f97f9b6.png)

![image](https://user-images.githubusercontent.com/2301202/39637716-b73e5292-4f78-11e8-8e23-02c4b151a8a5.png)
