### ISSUE TITLE
Clean up $harmony scripts

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#513]
@michaelgerakis I was thinking we could probably simplify the package.json scripts and travis config a bit.

The idea was: set an env variable in the node v4 case. 
It's set to `"--harmony"` if true, otherwise its and empty string `""`.

Would this work?

**Comment by michaelgerakis** [comment]
I believe in some cases it might be hard. Specifically for coveralls and mocha, we have to explicitly run the command through node (i.e "node mocha --harmony etc..") rather than through the packages themselves (i.e "mocha etc..")

**Comment by michaelgerakis** [comment]
An alternative I think would be helpful is to extract some of the scripts from package.json, which seems to be limited for customization, to a build runner like grunt or gulp or a makefile.

**Comment by wardpeet** [comment]
Let me know what you think, pretty nice cleanup in my opinion.

**Comment by wardpeet** [comment]
Can be closed 🔐 @paulirish
