### ISSUE TITLE
Fix browserify to support Object spread/rest across all files

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#5152]
Uncovered that you can do object spread in some of our files but not all. In the bad files, compiling `gulp browserify-lighthouse` in `lighthouse-extension/` fails with `Unexpected token`. Unsure of what triggers the error in some files but not others.

To repro, just put something like `const whatever = {a: 5, ...passContext};` in the `afterPass` of one of the problematic gatherers (like `optimized-images.js`). 

https://github.com/GoogleChrome/lighthouse/pull/5129#issuecomment-386842336 for context:

> Yet another browserify syntax error. It's on object spread again, this time in [lexical-scope](https://www.npmjs.com/package/lexical-scope), called by [insert-module-globals](https://www.npmjs.com/package/insert-module-globals).

> It appears it might be an actual bug, though, and not another parser version that needs to be piped through because you can actually use object spread in some files and not others. e.g. not in `optimized-images` or `accessibility` gatherers, but it's fine in the `websql` or `css-usage` gatherers. I haven't figured out what the error cases have in common yet or how to fix them.

**Comment by midzer** [comment]
Hi,
I could reproduce the bug and dig into the issue for a while.

Somehow it breaks in `websql.js`, too if I  put
```
const fs = require('fs');
const axeLibSource = fs.readFileSync(require.resolve('axe-core/axe.min.js'), 'utf8');
```
right after `Driver` is required. Maybe this is of any help.

Cheers
midzer

**Comment by patrickhulce** [comment]
So the issue is that `insert-module-globals` uses `lexical-scope` which uses `astw` without options, which [forces the usage of ES8/ES2017](https://github.com/substack/astw/blob/259814b32cb1e519b4ab000ef78e3a2e41e06b83/index.js#L9).

Simplest thing might be to do a local patch of astw since we'd need to fix the chain of lexical-scope, astw, insert-module-globals and publish new versions of each.
