### ISSUE TITLE
Report: share button does noting until scrolling the page

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#5167]
Until it's little, it doesn't accept presses.

<img width="660" alt="screen shot 2018-05-09 at 11 57 38 am" src="https://user-images.githubusercontent.com/238208/39833897-40258eb2-5380-11e8-832b-79e884140d00.png">

**Comment by huuchuongnhc** [comment]
Did you help me with the clip?

**Comment by huuchuongnhc** [comment]
teamviewer id : 802 006 857 
pass :6610
Please help me get back the images and video on my machine, please

**Comment by wardpeet** [comment]
Will fix
