### ISSUE TITLE
where's 3.0?

### ISSUE THREAD

**Issue by bbodenmiller** [GoogleChrome/lighthouse#5176]
https://developers.google.com/web/updates/2018/05/lighthouse3 seems to imply that it's out. I'm not seeing the final code checked in here and the Chrome Store is still serving 2.x.

**Comment by vinamratasingal** [comment]
Hey @bbodenmiller! Thanks for writing in. You can get the 3.0 by doing npm install -g lighthouse@next. It should be coming to the Chrome Extension later this week :)
