### ISSUE TITLE
aria-errormessage not support?

### ISSUE THREAD

**Issue by withzhaoyu** [GoogleChrome/lighthouse#5178]
This is jsx ：
`      <label for="startTime"> Please enter a start time for the meeting: </label>
      <input id='startTime' type="text" aria-errormessage="msgID" aria-invalid="true" value="11:30 PM"/>
      <span id="msgID" aria-live="assertive" style={{visibility:'visible'}}> 'sssstest' </span>`
when my code use aria-errormessage  attr ,will show this wrong:

> [aria-*] attributes are not valid or misspelled.

[aria-message example in w3c docs](http://www.w3.org/TR/wai-aria-1.1/wai-aria-1.1.html#aria-errormessage)

**Comment by patrickhulce** [comment]
thanks for filing @withzhaoyu! I get a 404 at the URL, but either way would you mind filing this issue with [axe-core](https://github.com/dequelabs/axe-core/)?

When it's fixed there, we'd automatically pickup their change :)

**Comment by withzhaoyu** [comment]
thx a lot
