### ISSUE TITLE
Break trace down into segments based on user_timings

### ISSUE THREAD

**Issue by michaelgerakis** [GoogleChrome/lighthouse#519]
There are certain situations that developers might be interested in that lighthouse currently doesn't have the capability of reporting on.
    Ex: A user clicks a button which activates a menu. What is the rendering time of that menu?

Proposed solution: Provide user the option to create user_timing events that label these event segments. Such timings would have to fall under a convention ( 'LifecycleInteraction:MenuRender'). Lighthouse can then grab these measure and create valuable metrics.

@paulirish mentioned rebasing metrics based on user provided ends for pageload, but I don't think measuring the start of page load to when a menu is rendered would be valuable. It also limits the test to one interaction, where multiple interactions or a chain of interactions would be more valuable (a test could watch for user timing events and proceed after certain ones are given to simulate a user's reaction). Breaking those interactions down into segments seems more valuable, imo. Thoughts?

**Comment by paulirish** [comment]
Will need to make sure FMP, etc can be 0'd against an arbitrary time and not dependent on navigationStart

**Comment by wardpeet** [comment]
+1 for the convention of using "LifecycleInteraction:" as a namespace for user_timings.

As an extra option I would add configuration to add a list of user timings to lighthouse so we can measure already existing timings without changing them in the application code with the LifecycleInteraction prefix

**Comment by brendankenny** [comment]
This will immediately work for imported traces, but we likely want to support this with traces collected by lighthouse itself, which will require being able to tell lighthouse to continue recording traces until some user_timing event(s) occur.

**Comment by wardpeet** [comment]
@brendankenny isn't it as simple as just setting up a convention like "LifecycleInteraction:finish". Unsure about the name though
