### ISSUE TITLE
Handle page load in extension

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#52]
I figure we can add a control that causes a full navigation of the page so we can capture page load traces and network events. This makes the extension less 'automatic', but the alternative would be to do the capture on every page load, which would be bad.

@paulirish wdyt? Am I missing something?

**Comment by paulirish** [comment]
Sg. Let's add a UI control to reload it later once we have something worthwhile to show for it.

**Comment by paulirish** [comment]
Discussions indicate the following:

1. Hitting the extension page action will kick off the popup.html and it'll immediately report on what it knows so far. 
  * AFAICT, even the manifest parts can still work without a reload. (even once #83 is landed) 
1. Performance metrics and any load-depdenent audits will show as "unknown" in the UI as an affordance to communicate that the full audit run wasn't done.
1. There's a button called "Reload & Run Full Analysis". (This is similar to DevTools' Audits panel ([screenshot](https://cloud.githubusercontent.com/assets/39191/14263326/e20c9594-fa6e-11e5-8ca2-abb550de4289.png))).
1. Clicking that reloads the page to do the full run.

This means gatherers need to indicate if they require the load or not. Luckily, @deepanjanroy is taking that part on with #81.

**Comment by paullewis** [comment]
This is done nao.
