### ISSUE TITLE
NO_DCL error when testing a website

### ISSUE THREAD

**Issue by pra85** [GoogleChrome/lighthouse#5208]
I am trying to run the Lighthouse Performance audit on the website https://lbmconstruction.com . But there is always a NO_DCL error. I have tried to use the Chrome extension as well but hasn't helped. The errors that I seen -

`Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_DCL)`

I am running this on Windows 10, Chrome 66.0.3359.170, Lighthouse 2.9.3

**Comment by patrickhulce** [comment]
Thanks for filing @pra85! I'm not seeing that error, but I am seeing other failures on this page (#5218), so thank you very much! It's possible these other failures are interfering with the ability to find DCL, so we may need to circle back around after those are fixed.
