### ISSUE TITLE
user-scalable="no" should not be tagged as error

### ISSUE THREAD

**Issue by evromalarkey** [GoogleChrome/lighthouse#5217]
I think user-scalable="no" is good option if you are doing your website as a regular app or pwa. You can't scale in regular native app neither. Good example is https://mobile.twitter.com/ which is pwa.

Maybe move this as a recommendation into "Additional items to manually check" section?

**Comment by patrickhulce** [comment]
Thanks for filing an issue @evromalarkey!

This is actually a critical part of accessibility and will not be changing. If you'd like further context, the [axe docs](https://dequeuniversity.com/rules/axe/1.1/meta-viewport) explain why this is important and highlights that it's a "MUST" for WCAG 2.0 AA.

**Comment by evromalarkey** [comment]
Didn't know it was a must in WCAG, anyway for a pwa, it's rather a drawback it that case. Maybe this could change with WCAG 2.1 in the future.

**Comment by webappslove** [comment]
I manage scaling in my apps, I have to use this. This option exist, and I use it for good... Not an error.
