### ISSUE TITLE
Audit: new dom nodes table is confusing

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#5220]
I'm not sure what the last line is telling me. It's identified two nodes, but they're not explained or lined up to anything.

<img width="872" alt="screen shot 2018-05-15 at 6 41 07 pm" src="https://user-images.githubusercontent.com/238208/40087206-9f6128de-586f-11e8-9b64-7e4cc05de42f.png">

**Comment by paulirish** [comment]
cc @hwikyounglee for ideas

**Comment by paulirish** [comment]
@exterkamps ive only seen [style] be a problem. my concern is that we'll strip some attributes that are useful. `[data-*]` come to mind.
but there could be others.

if we are subtractive then there's a much smaller risk that we effed up and removed important data.
and i presume it's more straightforward see that we need to remove another attribute than for people to tell us that we've excluded an attribute they need to identify the element.  🤷‍♂️

**Comment by exterkamps** [comment]
That's fair, and easier to implement.  I'll strip out just `style=".*"` tags then.

And did we want to make the stripping of snippets more generic, or put it into some lib/ file so that all snippets can use it? i.e. the accessibility snippets

**Comment by paulirish** [comment]
> And did we want to make the stripping of snippets more generic, or put it into some lib/ file so that all snippets can use it? i.e. the accessibility snippets

yah good call.
