### ISSUE TITLE
Wrong types in JSON report / missing quotes

### ISSUE THREAD

**Issue by astropanic** [GoogleChrome/lighthouse#5240]
In the JSON report the types are wrong, for example:

~~~
 {
      "type": "text",
      "text": 200
 },
~~~

Should be:

~~~
{
      "type": "text",
      "text": "200"
 },
~~~

**Comment by patrickhulce** [comment]
thanks for reporting @astropanic! we should double check to cast these before exporting 👍

**Comment by paulirish** [comment]
This is all diff now in LH 3.x
