### ISSUE TITLE
Extension Error: Protocol error (Emulation.setEmitTouchEventsForMouse): 'Emul

### ISSUE THREAD

**Issue by Jarestad** [GoogleChrome/lighthouse#5241]
**Lighthouse Version**: 2.10.0.3002
**Lighthouse Commit**: 632eb32688cf3fd0b2dd0158a712fd1d12ddd021
**Chrome Version**: 61.0.3163.100
**Initial URL**: https://github.com/GoogleChrome/lighthouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+
**Error Message**: Protocol error (Emulation.setEmitTouchEventsForMouse): 'Emulation.setEmitTouchEventsForMouse' wasn't found
**Stack Trace**:
```
Error: Protocol error (Emulation.setEmitTouchEventsForMouse): 'Emulation.setEmitTouchEventsForMouse' wasn't found
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17101:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by patrickhulce** [comment]
Hey there @Jarestad thanks for filing, Chrome 61 is quite old at this point. You'll need to update your Chrome version to be compatible with Lighthouse.
