### ISSUE TITLE
False positive: Document doesn't have a <title> element

### ISSUE THREAD

**Issue by ggennrich** [GoogleChrome/lighthouse#5249]
I am using Lighthouse CLI version 3.0.0-alpha.2. This is the command I am specifically running:
`lighthouse --chrome-flags='--headless' https://www.guidetoonlineschools.com/online-schools`
It is reporting that page as missing a title tag when it clearly isn't. Is this a known bug or am I missing something here?

**Comment by patrickhulce** [comment]
Interesting @ggennrich thanks for reporting I'm actually not able to get axe to finish running on this site at all! The entire accessibility category is just erroring 😕 

We might need to escalate to axe folks, here.

**Comment by ggennrich** [comment]
@patrickhulce Thanks for looking into this! Ya, the accessibility test hangs for a long time before finally moving on. The score for it in the HTML file just has a red question mark so I figured there was an issue with that, separate from the SEO title tag issue. Our homepage does not have the same accessibility issues. It has a score of 90. Also, there are no false positive title tag issues. So it appears that this only happens in specific cases and I haven't been able to figure it out.

**Comment by ggennrich** [comment]
@patrickhulce That is exactly what I am seeing. That totally makes sense. Why is it that the accessibility portion on this page errors then? Is that a separate issue or is there something wrong on this page that is causing that to happen?

**Comment by patrickhulce** [comment]
This is a bug with our integration with axe (the accessibility library that powers the audits). Typically it's because of a rare DOM structure on the page that axe isn't expecting, but either way we shouldn't take 60s of your time just to error so it's a bug to fix :)

**Comment by patrickhulce** [comment]
Filed the issue with axe 👍 https://github.com/dequelabs/axe-core/issues/908

**Comment by luckyscript** [comment]
I have the same issue when I try to using light house on my own blog: https://www.luckyscript.me
but I cannot figure out what's wrong on my HTML DOM.

**Comment by patrickhulce** [comment]
@luckyscript your issue is slightly different, would you mind filing an issue with [axe-core](https://github.com/dequelabs/axe-core/issues) if their Chrome extension fails on your site too?

**Comment by brendankenny** [comment]
FWIW the example page now passes (either changes in the page or in aXe updates), so I'm going to close. The underlying axe performance issue still exists; let's move tracking over to #5625
