### ISSUE TITLE
Configuration for extension

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#525]
We now have the plumbing available to expose a configuration in the chrome extension.

With this, you could _just_ test performance metrics or another configuration setup.

**Comment by wardpeet** [comment]
What configuration are you looking for? Everything the cli supports?

**Comment by paulirish** [comment]
Choosing which audits (and therefore which gatherer passes) should run.
They could be grouped into categories that match the aggregations

**Comment by wardpeet** [comment]
By configuration you mean an option page on the extension screen or rather have something fancy on the lighthouse screen itself?

**Comment by wardpeet** [comment]
I will just give it a spin in a few days

**Comment by paulirish** [comment]
It'd happen in the popup itself. Fancy sounds good. :)

I'm envisioning a config screen with checkboxes along these lines:

--------------
--------------


* [x] App can load on offline/flaky connections
* [x] Page load performance
* [x] Site is progressively enhanced
* [x] Network connection is secure
* [x] User can be prompted to Add to Homescreen
* [x] Installed web app will launch with custom splash screen
* [x] Address bar matches brand colors
* [x] Design is mobile-friendly

.

* [x] Best Practices
* [x] Performance Metrics

--------------
--------------

**Comment by wardpeet** [comment]
Something like this? Or am I in the wrong direction?
![Options button
](https://cloud.githubusercontent.com/assets/1120926/17339427/1ce93e70-58ec-11e6-99a8-e5d90071ce0c.png)
![Options panel](https://cloud.githubusercontent.com/assets/1120926/17339436/2445d9b2-58ec-11e6-8a44-0bc07b3a13ab.png)

**Comment by paulirish** [comment]
​That's right in line with what I was thinking, yup. :) Nice.

**Comment by brendankenny** [comment]
@paulirish I think we now hit all the points you wanted here
