### ISSUE TITLE
Custom report generates empty "reportCategories": []

### ISSUE THREAD

**Issue by joelhsmith** [GoogleChrome/lighthouse#5252]
Hopefully this is pretty simple fat-fingering. I am trying to create a custom report that uses audits from both Accessibility and Best Practices plus a custom Group called "Robust"

This is a stripped down version for testing:
https://gist.github.com/joelhsmith/1db89a45ec4b3ffbd77018b3ea51cd29

If I run the report on https://cats.com it generates a valid JSON file.
https://gist.github.com/joelhsmith/c4cefd8f69d5f399412496e04aa13f4b

But I have two problems:

1. The "reportCategories" is empty.
2. It just opens a blank page in the [lighthouse viewer](https://googlechrome.github.io/lighthouse/viewer/).

Am I doing something wrong that is making my "reportCategories" come up empty? Is that why it will not open up in the Lighthouse Viewer?

Thanks in advance.

**Comment by patrickhulce** [comment]
> Hopefully this is pretty simple fat-fingering

Hey there @joelhsmith! You're in luck 😉 Based on your config gist it looks like you've put the `.categories` property inside `.groups` in the config, moving it to the toplevel should get the job done 👍 

BTW, if you're mostly using default with some extras, you might want to consider extending the config instead so it's less to maintain, example...

```js
module.exports {
  extends: 'lighthouse:default',
  settings: {
    onlyCategories: ['best-practices', 'accessibility', 'my-category']
  },
  categories: {
    'my-category': {...},
  }
}

**Comment by joelhsmith** [comment]
Oh thank you! @patrickhulce I have updated the gist to fix the nesting goof. 
https://gist.github.com/joelhsmith/1db89a45ec4b3ffbd77018b3ea51cd29

Can I beg you one more question? After fixing the brackets, I get this error:
`
Runtime error encountered: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at Object.keys.forEach.categoryId (/usr/local/lib/node_modules/lighthouse/lighthouse-core/config/config.js:149:35)
    at Array.forEach (<anonymous>)
    at validateCategories (/usr/local/lib/node_modules/lighthouse/lighthouse-core/config/config.js:148:27)
    at new Config (/usr/local/lib/node_modules/lighthouse/lighthouse-core/config/config.js:347:5)
    at Promise.resolve.then._ (/usr/local/lib/node_modules/lighthouse/lighthouse-core/index.js:43:20)
    at <anonymous>
`
Everything looks spelled correctly and brackets are correct. I just can't figure out what is wrong.

P.S. I will try to see if I can achieve the same result as suggested, but I need to figure out what I did wrong, on principle :-)

**Comment by patrickhulce** [comment]
Oh sure :) looks like you're trying to use a 3.x style config with LH 2.x.

In 2.x the array of audits was called `.audits` in 3.x it changed to `.auditRefs`

Sorry the docs are mixed right now we're working on making everything aligned!

**Comment by joelhsmith** [comment]
I'm closer. Changing from 'auditRefs' to 'audits' made the 'Cannot read property..." go away, which allowed me to debug an issue of assigning audits to groups that did not exist.  I have updated my gist:
https://gist.github.com/joelhsmith/1db89a45ec4b3ffbd77018b3ea51cd29

It generates a valid JSON file:
https://gist.github.com/joelhsmith/c4cefd8f69d5f399412496e04aa13f4b 
without throwing an error...

But, when I drag the .json into the lighthouse viewer it flashes a "Cannot read property 'split' of undefined".  

Since that error is not overly helpful, I ran it generating .html instead, hoping for a better error message in the console. Which I got:

```
Uncaught TypeError: Cannot read property 'split' of undefined
    at DOM.convertMarkdownCodeSnippets (report.html:1887)
    at CategoryRenderer._populateScore (report.html:3101)
    at CategoryRenderer.renderCategoryScore (report.html:3120)
    at CategoryRenderer.render (report.html:3291)
    at ReportRenderer._renderReport (report.html:3769)
    at ReportRenderer.renderReport (report.html:3634)
    at window.addEventListener._ (report.html:3856)

```
So I took a look there:
https://github.com/GoogleChrome/lighthouse/blob/2bcc4ccdc51885fc02e70a36b07cfb91e9814dc5/lighthouse-core/report/html/renderer/category-renderer.js#L126-L131
and here:
https://github.com/GoogleChrome/lighthouse/blob/2bcc4ccdc51885fc02e70a36b07cfb91e9814dc5/lighthouse-core/report/html/renderer/category-renderer.js#L61-L66

And... I'm stuck. Any ideas?

**Comment by patrickhulce** [comment]
I think it's another case of 2.x vs. 3.x. If you want to build on 3.x you can just install 3.x and your original config with nesting fixed should work as expected`npm install lighthouse@next` :)

If you want to build on 2.x you'll want to look at the code from 2.x https://github.com/GoogleChrome/lighthouse/blob/branch2.x/lighthouse-core/config/default.js,
for categories, name -> title, audits -> auditRefs

**Comment by joelhsmith** [comment]
Yep, all good now. Thanks @patrickhulce
