### ISSUE TITLE
Lighthouse 3.0.0-alpha.2 - Performace Score 0 for ASP.NET Razor Pages

### ISSUE THREAD

**Issue by karthickinnova** [GoogleChrome/lighthouse#5255]
I was running Lighthouse with version 2 previously and was able to obtain the performance score(though it was 12 - 20). After the v3 update the performance score is always 0. I don't see any Audit error in the application too. Just the First meaningful paint is over 35000 ms.

**Comment by patrickhulce** [comment]
@karthickinnova do you have a public URL for us?

**Comment by karthickinnova** [comment]
Unfortunately the application is hosted in development server right now and proprietary as well. I tried resolving major issues from the report, still the score doesn't change. In 2.0 that score would show the difference with each improvisations. Now I'm confused the issue is with my application or with lighthouse. It would be helpful if the report indicates minimal score like may be 1 as poor performance and I'll be knowing the lighthouse works form my app. Thanks

**Comment by patrickhulce** [comment]
Audit errors in scored categories now appear as a `?` in place of the category score so if you're seeing a 0, it is a weighted average 0.

FMP of 35s is extremely high (roughly ~24s passed the score of 0 for FMP). If you could get us a trace of the page (run CLI with `--save-assets`) we could help more to see if there's a bug on our side. Keep in mind that if you're serving development assets from a non-production server it will be overly harsh as they generally aren't minified/compressed/over H2/etc.

**Comment by karthickinnova** [comment]
@patrickhulce Thanks for the info. I'll try to bring the FMPs to 24s and will observe the metrics. 

Also as I mentioned before there is no Audit Errors or ? on any category in the report.

**Comment by karthickinnova** [comment]
@patrickhulce I was able to bring down the FMP score to 18s, But still no improvement on the performance score.  Attached screenshot on Performance. Please let me know on the proceedings.

![lighthouse_error](https://user-images.githubusercontent.com/6780987/40257315-6601b3e2-5ab3-11e8-9755-9d5f436df6e3.PNG)

**Comment by patrickhulce** [comment]
Sorry my comment was that 35s is ~24s *beyond* what the score of 0 is for FMP. FMP >11s (35-24=11) receives a 0. You can use the [calculator](https://docs.google.com/spreadsheets/d/1Cxzhy5ecqJCucdf1M0iOzM8mIxNc7mmx107o5nj38Eo/edit#gid=283330180) to experiment with what performance score will be for different metric values.
All of your metrics get a score of ~0 based on the v3 curves.

Based on your metrics, it seems like there are *a lot* of heavy, render blocking resources. Are there not any remaining opportunities in the report?
