### ISSUE TITLE
SEO Evaluation Error - Robots.txt

### ISSUE THREAD

**Issue by strayangelfilms** [GoogleChrome/lighthouse#5261]
Current build claims an SEO reduction / penalty for many pages listing robots.txt as marking pages blocked from indexing when this is not the case at all when pages are tested with multiple crawlers and with Google Search Console.  Seems to be a bug in this build.

**Comment by ashishdhade** [comment]
this message display on my website report "Search engines are unable to include your pages in search results if they don't have permission to crawl them."

**Comment by ashishdhade** [comment]
please check this http://www.buildtrack.in/

**Comment by patrickhulce** [comment]
Thanks for sharing @ashishdhade!

I'm seeing a 100 for SEO on that site
![image](https://user-images.githubusercontent.com/2301202/40246613-3b502dac-5a7e-11e8-8251-7e5bdf149038.png)

**Comment by ashishdhade** [comment]
welcome @patrickhulce

**Comment by ashishdhade** [comment]
Hello @patrickhulce

**Comment by strayangelfilms** [comment]
Try www.strayangel.com or www.lockebridge.com as two examples of sites with valid robot.txt that Lighthouse claims are being blocked but are not.

**Comment by patrickhulce** [comment]
lockebridge is fine
![image](https://user-images.githubusercontent.com/2301202/40255137-eee51b18-5a9a-11e8-9bd8-361b2ea879ab.png)

for strayangel, LH is complaining about a meta tag explicitly saying noindex, not the robots.txt
![image](https://user-images.githubusercontent.com/2301202/40255214-310407e8-5a9b-11e8-958a-03b8686b01a9.png)

![image](https://user-images.githubusercontent.com/2301202/40255235-4889b7dc-5a9b-11e8-9cd8-7f3541f11630.png)

**Comment by strayangelfilms** [comment]
Wow, you really saved my butt on this, there was a WooCommerce setting that was inadvertently telling the home page not to index!  Very obscure and took 4 hours to track down.  And here I am reporting bugs that aren’t bugs at all.  Sorry!!!  Thanks Patrick!!!

**Comment by patrickhulce** [comment]
no prob, glad it worked out :)
