### ISSUE TITLE
Index template for elasticsearch

### ISSUE THREAD

**Issue by astropanic** [GoogleChrome/lighthouse#5262]
Please provide a subcommand to the Lighthouse cli which generates an [index template](https://discuss.elastic.co/t/indexing-json/132329) for elasticsearch, simplyfing storage of lighthouse reports in json format.

An example from [Filebeat](https://www.elastic.co/products/beats/filebeat) [(usage)](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-template.html#load-template-manually-alternate) :

`filebeat export template > filebeat.template.json`

 Later it's a matter of putting the resulting template into my ES instance.

Something similar would be good to have for the cli in Lighthouse, eg.

`lighthouse export template > lighthouse.template.json`

I've read how to [contribute](https://www.npmjs.com/package/lighthouse) and tried it do by myself, but somehow `yarn dev ` is not working for me (tried in a Docker container):

~~~~
root@0cf4e3acf527:/lighthouse# cd lighthouse-cli && yarn dev
yarn run v1.6.0
(node:354) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@0cf4e3acf527:/lighthouse/lighthouse-cli#
~~~~

I'm not so much into NodeJS, so I leave it only as an Idea for real NodeJS developers.

**Comment by astropanic** [comment]
@patrickhulce we can pairif you want, adding this feature should be a no-brainer, just not sure how to start with the workflow, let me now if you up for a remote pairing session.

**Comment by paulirish** [comment]
I think you're gonna have to build this on your own. Holler if we can answer any questions about getting a dev environment setup, but this feature req is out of our scope.

The docs are all updated for 3.x now.
