### ISSUE TITLE
`WebappInstallBanner` should depend on `WorksOffline` and `LoadFastEnough4Pwa` 

### ISSUE THREAD

**Issue by slightlyoff** [GoogleChrome/lighthouse#5264]
We [have always said](https://infrequently.org/2016/09/what-exactly-makes-something-a-progressive-web-app/) that one of the most important aspects of "PWAness" is that these experiences meet the expectations of users when it comes to reliably fast loading.

Therefore, I'd like for our ["installability" check](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/webapp-install-banner.js) to be gated on [working offline](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/works-offline.js) and [loading fast enough](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/load-fast-enough-for-pwa.js).

We're going to continue to raise the bar to this level on the Chrome (product) side, so LH getting there first would be a huge help.

Thanks!

**Comment by patrickhulce** [comment]
The good news the audit is already gated on a stricter criteria than working offline audit, the start URL must work offline.

https://github.com/GoogleChrome/lighthouse/blob/a99c07b890b104e2d51e3c4326edfee79c6f49e6/lighthouse-core/audits/webapp-install-banner.js#L90-L112

Loading fast enough is being considerably bumped in #5233 so the category won't be green until the app is fast enough. Visual badging needs discussion :)

**Comment by slightlyoff** [comment]
Ah! I hadn't understood [that it tested this](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/start-url.js#L14) rather than just looking for a match on the `scope`. Great!

Who needs to be involved to make the call on visual badging?

**Comment by paulirish** [comment]
duping into #5930
