### ISSUE TITLE
Add links to references while viewing audit progress pop-up

### ISSUE THREAD

**Issue by dmiyamasu** [GoogleChrome/lighthouse#5265]
While a LightHouse audit is running, I can see the progress bar pop-up which displays a rotating list of performance hints, such as:

> 75% of global mobile users in 2016 were on 2G or 3G [Source: GSMA Mobile]

![image](https://user-images.githubusercontent.com/508468/40244520-0fe67cda-5a91-11e8-85ac-eaa0e31375df.png)

I would love it if the "[Source: GSMA Mobile]" text were linked to view the article that published that information. 

My Browser info:
Mac OS X
Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by patrickhulce** [comment]
Hey @dmiyamasu thanks for the suggestion! We would love this as well and originally linkified them before realizing that opening up a new tab forces your existing one into the background and skews the results. 

Do you have any thoughts on the UX here? Perhaps showing a message that the link will be opened after the run completes?

**Comment by paulirish** [comment]
We don't have a way to allow you to look at these without impacting the performance of the results.
