### ISSUE TITLE
Is there a way to generate html report using lighthouse programmatically.

### ISSUE THREAD

**Issue by abhagupta** [GoogleChrome/lighthouse#5269]
Sorry if I missed this anywhere but I am trying to find how to generate the html using lighthouse using the example given in docs. https://github.com/GoogleChrome/lighthouse/blob/HEAD/docs/readme.md#using-programmatically

I could generate the html by calling lighthouse-cli directly but could not do it using above script.  My `opts` are: 

```
const opts = {
  chromeFlags: ['--show-paint-rects'],
  output: 'html',
  'output-path': './lighthouse-results.html',
  'save-assets': true
};
```

**Comment by patrickhulce** [comment]
Several of those flags are CLI only. You'd need to manually build the report similar to https://github.com/GoogleChrome/lighthouse/blob/58ed2868215f61f1cdd8adcb44b316f2c656c30d/docs/hacking-tips.md#iterating-on-the-v2-report

In 3.x, output is returned to you in a new `.report` property, but saving the assets is still up to you. You can give 3.x a spin by `npm install lighthouse@next`

**Comment by paulirish** [comment]
yup. the new .report property in LH 3.

**Comment by jbustamovej** [comment]
I did it like this:
```
const lighthouse = require('lighthouse');
const ReportGenerator = require('lighthouse/lighthouse-core/report/report-generator');

const report = await lighthouse(page.url(), { port: port }, config).then(results => {
  return results;
});
const html = ReportGenerator.generateReport(report.lhr, 'html')
````

MIght be worth it to update the docs for this.

**Comment by patrickhulce** [comment]
@jbustamovej the docs should be updated to say the below, is there somewhere else you found still telling you to use ReportGenerator?

```js
function launchChromeAndRunLighthouse(url, opts, config = null) {
  return chromeLauncher.launch({chromeFlags: opts.chromeFlags}).then(chrome => {
    opts.port = chrome.port;
    return lighthouse(url, opts, config).then(results => {
      // use results.lhr for the JS-consumeable output
      // https://github.com/GoogleChrome/lighthouse/blob/master/typings/lhr.d.ts
      // use results.report for the HTML/JSON/CSV output as a string
      // use results.artifacts for the trace/screenshots/other specific case you need (rarer)
      return chrome.kill().then(() => results.lhr)
    });
  });
}
```

**Comment by taytus** [comment]
@patrickhulce I'm getting a 404 https://github.com/GoogleChrome/lighthouse/blob/master/typings/lhr.d.ts

**Comment by patrickhulce** [comment]
@taytus they moved, see https://github.com/GoogleChrome/lighthouse/blob/520177b74202ac2ac5ca7e2f6daa2a7cc6bd5612/types/lhr.d.ts

**Comment by taytus** [comment]
@patrickhulce thank you for that!

I'm still confused and I did it work in a hacky way. All I want is to save the HTML reports in a specific location. This is my solution but I would love feedback if there is a better way to do this.

Thank you!!


`const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');
const fs = require('fs');
const log = require('lighthouse-logger');



function launchChromeAndRunLighthouse(url, opts, config = null) {
    return chromeLauncher.launch({chromeFlags: opts.chromeFlags}).then(chrome => {
        opts.port = chrome.port;
    return lighthouse(url, opts, config).then(results => {

        res=results.report;

    //workaround to save the report
    fs.writeFile("something.html", res, function(err) {
        if(err) {
            return console.log(err);
        }

    });
        return chrome.kill().then(() => results.lhr)
});
});
}

const opts = {
    output:'html',
    chromeFlags: ['--headless'],
    logLevel: 'info',
    onlyCategories: ['performance'],
    view:true

};

launchChromeAndRunLighthouse('https://roboamp.com', opts).then(results => {
    log.setLevel(opts.logLevel);
    console.log('report is done')
});`

**Comment by herobix** [comment]
@taytus Yours works perfectly fine for me. I am generating multiple reports, now I need to figure out how I can add a link to them all to link to each other :)

**Comment by idanen** [comment]
@patrickhulce The docs says that `results.report ` has HTML as a string, and it doesn't.

The `ReportGenerator` on the other hand, works great and generate the same report as other Lighthouse tools.

Is it safe to use it? Are you planning to deprecate it or something?

**Comment by patrickhulce** [comment]
@idanen `results.report` has the HTML as a string in the array when the output array includes `html`.

> Is it safe to use it? Are you planning to deprecate it or something?

No, generally speaking it is not safe to use. ReportGenerator is not part of our public API and could be moved/changed on any minor/patch version bump. `.report` has been around since v3 and is expressly intended for this use case.

**Comment by idanen** [comment]
Thanks for the response @patrickhulce.

Is the output array supported when using in Node?

**Comment by patrickhulce** [comment]
@idanen yes.

**Comment by LearningAbhi** [comment]
@taytus Sir is there anyway to run this for multiple urls. I am trying to call this function in a loop and passing the array of url. It seems to lunch the lighthouse but my problem is its only storing result for one url. Could u please help me out ?
for(var i=0;i<arr.length;i++)
{
launchChromeAndRunLighthouse(arr[i], opts).then(results => {
//some work
}

**Comment by paulirish** [comment]
@LearningAbhi for multiple URLs you might want to consider https://github.com/samdutton/multihouse or https://www.npmjs.com/package/lighthouse-batch

**Comment by LearningAbhi** [comment]
@paulirish thanks for your quick response. Sorry I missed your ping as I was out of town.
I know about lighthouse-batch , but its run through cli . I want programmatically.
I am trying to build an app which will accept a har file and run the lighthouse for each and every URL present in that har file. 
I am able to run lighthouse programmatically for single url, but for multiple url I am getting unhandledpromise error.
Any comments on this ?

**Comment by vigilanteone1** [comment]
> @patrickhulce thank you for that!
> 
> I'm still confused and I did it work in a hacky way. All I want is to save the HTML reports in a specific location. This is my solution but I would love feedback if there is a better way to do this.
> 
> Thank you!!
> 
> 
> ```
> ```javascript
> const fs = require('fs');
> const lighthouse = require('lighthouse');
> const chromeLauncher = require('chrome-launcher');
> const log = require('lighthouse-logger');
> 
> (async () => {
>   log.setLevel('info');
>   const chrome = await chromeLauncher.launch({chromeFlags: ['--headless']});
>   const options = {output: 'html', onlyCategories: ['performance'], port: chrome.port};
>   const runnerResult = await lighthouse('https://example.com', options);
> 
>   // `.report` is the HTML report as a string
>   const reportHtml = runnerResult.report;
>   fs.writeFileSync('lhreport.html', reportHtml);
> 
>   // `.lhr` is the Lighthouse Result as a JS object
>   console.log('Report is done for', runnerResult.lhr.finalUrl);
>   console.log('Performance score was', runnerResult.lhr.categories.performance.score * 100);
> 
>   await chrome.kill();
> })();
> ```

How to remove unnecessary items from report as I only want audits and it's numerical score nothing else want to remove all unnecessary data like time stamps,css..etc all categories
