### ISSUE TITLE
Extension Error: getCurrentTabURL returned empty string

### ISSUE THREAD

**Issue by AZiSTELLAR** [GoogleChrome/lighthouse#5279]
**Lighthouse Version**: 2.10.0.3002
**Lighthouse Commit**: 632eb32688cf3fd0b2dd0158a712fd1d12ddd021
**Chrome Version**: 66.0.3359.139
**Initial URL**: https://*.firebaseapp.com/
**Error Message**: getCurrentTabURL returned empty string
**Stack Trace**:
```
Error: getCurrentTabURL returned empty string
    at _queryCurrentTab.then.tab (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17062:7)
```

**Comment by wardpeet** [comment]
moving discussion to #5668
