### ISSUE TITLE
Failing running with config

### ISSUE THREAD

**Issue by denar90** [GoogleChrome/lighthouse#5292]
# Bug report
Hi guys, 
I've been trying to migrate pwmetrics to LH v3 and faced issue using [plots.config.js](https://github.com/GoogleChrome/lighthouse/blob/v3.0.0-alpha.2/lighthouse-core/config/plots-config.js)
Looks like it works fine for plots measurments, but wan't for me...
Method [filterCategoriesAndAudits](https://github.com/GoogleChrome/lighthouse/blob/v3.0.0-alpha.2/lighthouse-core/config/config.js#L469) recives `oldCategories` as `undefined` and crashes while [iterating `auditsToValidate`](https://github.com/GoogleChrome/lighthouse/blob/v3.0.0-alpha.2/lighthouse-core/config/config.js#L491) with error `Cannot convert undefined or null to object` which looks reasonable.
The problem why `oldCategories` were `undefined`.
This is all what I found so far, continue investigation tomorrow...
probably cc @patrickhulce 

**Provide the steps to reproduce.**
1. Run LH on https://www.paulirish.com/ (who's else website we can use, he-he ;) ) with `plots-config.js`

**Environment Information**:
Affected Channels:
- [x] Node Module

Lighthouse version: v3.0.0-alpha.2
Node.js version: v8
Operating System: macos

thanks)

**Comment by patrickhulce** [comment]
Oh whoops sorry @denar90 plots config isn't really used or tested, it looks like it's missing the `extends: 'lighthouse:default'` property, that should get things going

**Comment by denar90** [comment]
@patrickhulce thanks, It works)
I've sent PR for fixing this.
