### ISSUE TITLE
Best Practices - Mutation Events EventsListeners Audit Failure / Protocol error (DOM.resolveNode)

### ISSUE THREAD

**Issue by strayangelfilms** [GoogleChrome/lighthouse#5294]
When running a test on my own site, www.strayangel.com, using Lighthouse version 3.0.0-alpha.2, I get an error when evaluating Best Practices resulting in a ?.  Specifically, Mutation Events EventsListeners Failure / Error.  See screenshot.  Checked with totally clean latest Chrome install.  After further testing, this only happens after a fresh Chrome / Lighthouse evaluates the site for a **second** time.  The first test will not trigger the error, but a second evaluation run right after and most subsequent ones will.  However, every now and then I will get a clean result, maybe 1 out of 10 evaluations.  It does not happen with Lighthouse version 2.9.1.

"Audit error: Required EventListeners gatherer encountered an error: Protocol error (DOM.resolveNode): Node with given id does not belong to the document"

![image](https://user-images.githubusercontent.com/27704327/40333428-49a1e1e8-5d0d-11e8-82bb-9daa719edcd4.png)

Is this a possible reoccurrence of #2736?

**Comment by paulirish** [comment]
Thanks very much for reporting. We really appreciate it.


We've removed this audit now.
