### ISSUE TITLE
Extension Error: Protocol error (Emulation.setDeviceMetricsOverride): Invalid

### ISSUE THREAD

**Issue by manishkumbhkar** [GoogleChrome/lighthouse#5305]
**Lighthouse Version**: 2.10.0.3002
**Lighthouse Commit**: 632eb32688cf3fd0b2dd0158a712fd1d12ddd021
**Chrome Version**: 60.0.3112.101
**Initial URL**: https://www.google.co.in/search?q=Emulation.setDeviceMetricsOverride)%3A+Invalid+parametersReport+ErrorOptions+Generate+report&oq=Emulation.setDeviceMetricsOverride)%3A+Invalid+parametersReport+ErrorOptions+Generate+report&aqs=chrome..69i57.51595j1j7&sourceid=chrome&ie=UTF-8
**Error Message**: Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters
**Stack Trace**:
```
Error: Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17101:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by patrickhulce** [comment]
You'll need to update your Chrome version, 60 is old :)
