### ISSUE TITLE
name of the output file

### ISSUE THREAD

**Issue by amohideen** [GoogleChrome/lighthouse#533]
Is is possible to write the name of the outputfile to be the URL instead last-run-results.html. (I have not checked the code yet) It will also be good if lighthouse could dump the pages with all its resourses.

**Comment by paulirish** [comment]
> Is is possible to write the name of the outputfile to be the URL instead last-run-results.html. 

You could do this instead

```sh
lighthouse http://mysite.com --output=html --output-path=./mysite-results.html
```

> It will also be good if lighthouse could dump the pages with all its resourses.

the --save-assets flag saves the trace and screenshots. 

There's not a standard way for us to dump the entire page. (Would we dump it as delivered or the finished DOM after JS and all that). Because this gets pretty messy, we're avoiding it right now.
What question do you want to answer with these resources?

**Comment by amohideen** [comment]
Hi Thanks,

lighthouse http://mysite.com --output=html --output-path=./mysite-results.html

Thanks for that.

We woould like to run a PLT benchmarking on a local setup.. so if we
could dump all resources of a web page we will
be able to run a bunch of tests on our harness. At the moment we are
using dependency trees (jason HAR like files)
to reproduce all of it.

(We will be using lighhouse to study the depth of dependency of first
2000 Alexa top pages as part of producing sensible web models for
future benchmarking experiments)

and Ilya Grigorik who guided me to the tool.

Thanks.

Mohideen

Uni Aberdeen

NEAT EU Project.

**Comment by paulirish** [comment]
>  so if we could dump all resources of a web page we will be able to run a bunch of tests on our harness. 

I don't know of a good mechanism to dump the entire webpage/webapp such that it can reliably be run again. however WebPageRelay can at least capture/replay network traffic.

But I wonder if instead of dumping the page assets, you could do your analysis from within lighthouse itself. What additional answers do you want from the page?

**Comment by amohideen** [comment]
We would like to have a more controllable locally reproducible setup so
that we can tweak transport and app layer network parameters. I think I
will look more into lighthouse.

Thanks.

**Comment by paulirish** [comment]
@amohideen (In case you still want to try to save the page)....

I now see this API https://developer.chrome.com/extensions/pageCapture which can capture a page as MHTML
I don't know that we can trigger that via the protocol, but there may be another way.  Shrug.

**Comment by amohideen** [comment]
Thanks.. Paul,

I was thinking, would not it be nice if we could write the landing page
size (in KBs) as part of the output (if available) or is it already there
and iI did not spot it.

**Comment by paulirish** [comment]
@amohideen let's break that out into its own issue. However we should start with the problem you're trying to solve. I'm not sure the transfer size of the HTML document is a key metric. (facebook starts rendering to the user a few seconds before their HTML finishes transferring)

**Comment by amohideen** [comment]
The total size, number of resources, the size of those resources and
dependency between those resources are vital in measuring the PLT
benchmarking, However, first useful/meaningful paint
 would be a more appropriate measure (How to decide what is the
useful/meaningful byte is still a question). In our case, these matrices
are a baseline
for understanding the transport parameters and enhancements. We are testing
HTTP/1 over SCTP (multistreaming) as opposed to H2 and QUIC and it makes
sense to do so as H2 and QUIC borrow so much from SCTP.

What I'm trying to achieve is that is to create a representative model/s of
the current web so the research work can be more rational, insted of
running a set
of tests on number of Alexa ranked webpages in the wild. In that sense,
lighthouse is a very useful tool.

There are many recording and replaying tools (lkie http://mahimahi.mit.edu/),
but they do not serve my purpose.

In total I need to collect metrics on Total Page size (social sites like
facebook are special ones as there landing pages do not represent the real
load, I may have to sanitise the data),
number of resources, size of resources, depth of dependency etc.. so that I
can do clustering to produce some models. Any browser computations
(rendering) should be considered as
part of pageloading process, and AFAIK Chrome and Firefox does it the same
way.


Hope I did not confuse more..
