### ISSUE TITLE
Blobs URL seen as insecure in V2.9.1

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/lighthouse#5344]
Hello,

I am currently running Google Canary Version 68.0.3439.0 (Official Build). It has Lighthouse V2.9.1 I do release Lighthouse V3 is coming very soon!

I have been reading the past issues and it seems like this issue was fixed a year ago found here: [is-on-https: check record.protocol for blob urls #2538](https://github.com/GoogleChrome/lighthouse/pull/2538).

See screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/40505418-0197d67e-5f8c-11e8-9937-bcf7810f0a5d.png)

When I hover I see the following type of URL being flagged:

`blob:https://www.example.com/r54g76rf43-g53rt34-t345r3`

Please note this is being created by OneSignal API and the 'example' would actually be my domain not an external one.

Surely this is a false positive and `blob:https` should not be flagged still?

**Comment by patrickhulce** [comment]
Yes blob URLs should not be flagged right now, do you have a public URL where we can see this behavior?

**Comment by ayumihamsaki** [comment]
@patrickhulce public URL found here: https://www.asianspa.co.uk/dmca
Please use test setting for Desktop and not Mobile - as I currently have onesignal setup on the desktop version right now and that's where I am seeing this error.

**Comment by ayumihamsaki** [comment]
@patrickhulce After more investigation it seems to be an installed plugin called: "Adblock Plus" that is making the blob url from the website that has onesignal on it.

Lighthouse should have some extra code to ignore blob urls being created by installed plugins in the browser.

**Comment by ayumihamsaki** [comment]
Gonna close this issue due to third party issue.
