### ISSUE TITLE
Make "Learn more" links in report more descriptive

### ISSUE THREAD

**Issue by timj2** [GoogleChrome/lighthouse#5349]
**Summary**
"Links do not have descriptive text" error doesn't make sense if you are violating it yourself:)
![image](https://user-images.githubusercontent.com/39605488/40518306-c49d340c-5f6e-11e8-9b57-c42e306094ea.png)

**Comment by patrickhulce** [comment]
Our report is not meant to be indexed by search engines, so we're OK being docked 10 SEO points here ;) but yes we agree for a11y reasons and it's on the backlog to fix this https://github.com/GoogleChrome/lighthouse/issues/4494#issuecomment-388097162

**Comment by lazysoundsystem** [comment]
Another quick fix you can bundle with this one. 

I see 'go' is also on the blocklist: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/seo/link-text.js

Could you get your colleagues to rename the 'Go' programming language so links to golang resources can also pass this test. 

Thanks!

**Comment by brendankenny** [comment]
We don't have an explicit plan here beyond just always improving our description strings, so I'm going to close this issue. If folks have specific proposals in mind then please comment and we can reopen.
