### ISSUE TITLE
Feature Request - Copy to Clipboard and show error in source code

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/lighthouse#5359]
I would like to request the feature of copy to clipboard on selected errors and be able to click on the error and Chrome will redirect you to the location in the source so we can speed up the process of correcting things.

For example see screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/40560809-0d2b440e-6053-11e8-9eed-8398672b5f71.png)

I would like to click on the error I have highlighted and be able to copy to clipboard and/or go direct to the source code in the "Elements" Tab in Chrome.

Example of it going direct to the source code:

![untitled](https://user-images.githubusercontent.com/17784082/40561186-33b0c490-6054-11e8-918f-794c78cc7022.png)

Thanks.

**Comment by patrickhulce** [comment]
Thanks for filing @ayumihamsaki! This functionality is in fact already there, it's just buggy given the fact that we reload the page several times.

We're tracking progress in https://github.com/GoogleChrome/lighthouse/issues/2289

**Comment by ayumihamsaki** [comment]
@patrickhulce ok sorry, I did do a search but no results came up for clipboard etc.

**Comment by patrickhulce** [comment]
No worries, GitHub search isn't quite 🤖 🎓 yet :)
