### ISSUE TITLE
Pages with body set to opacity:0 list "meaningful paint" and "consistently interactive"

### ISSUE THREAD

**Issue by rcombs** [GoogleChrome/lighthouse#5375]
#### Provide the steps to reproduce
Run LH on a page using Google Optimize or Visual Website Optimizer, particularly if their scripts are blocked using an extension, proxy, DNS, or other tool.

#### What is the current behavior?
These tools do the opposite of what their names imply: they delay effective page load until they've finished running, effectively pessimizing pageload performance. This is particularly egregious in the case where the script fails to load (e.g. because it's blocked), and the page doesn't appear until 4 seconds(!) pass and a timeout triggers. This is the kind of behavior you'd want to catch in a website performance test.
None of this is measured by Lighthouse, because of the specific method these scripts use to blank the page: they set a style on the `<body>` or `<html>` element (either via a class or a tag rule), which sets its `opacity` to 0. This results in the page being unusable to the user, but still allows Lighthouse's "first meaningful paint", "first interactive", and "consistently interactive" measurements to fire up to 4 seconds before any content is actually displayed to the user.

#### What is the expected behavior?
Since a page with its root or `<body>` element set to fully transparent is useless, the "first meaningful paint", "first interactive", and "consistently interactive" measurements should be delayed until those elements are opaque.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 2.9.1
* Operating System: macOS 10.13

**Comment by patrickhulce** [comment]
Obsolete, we've moved on to LCP and these design decisions are intentional. Changes to LCP can be filed at the [WICG repo](https://github.com/WICG/largest-contentful-paint)
