### ISSUE TITLE
Preload key requests potential bug. Suggestion of preloading lighthouse blob: document

### ISSUE THREAD

**Issue by tomblackshire** [GoogleChrome/lighthouse#5380]
Lighthouse has suggested preloading key requests. The example appears to be very similar to the lighthouse report URL generated by the chrome extension. 

Report URL (Lighthouse 3.0.0-beta.0):

`blob:chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/37639f89-65c7-46a1-b15e-d5ba5f50916f`

Preload suggestion:

`blob:https://the-dots.com/337f5ca1-7a07-4ce3-bd72-985a13d750d3` 

![alt](http://res.cloudinary.com/tomblackshire/image/upload/v1527678496/Lighthouse_Report_oky3tn.png)

The URL I was testing was: [https://the-dots.com/users/search](https://the-dots.com/users/search)

Potentially a bug?

Tom

**Comment by wardpeet** [comment]
@tomblackshire thanks for reporting; It's indeed a bug!

**Comment by tomasvts** [comment]
It happens too with real time video using HLS or DASH

**Comment by wardpeet** [comment]
@tomasvts do you have an example site to test this on?

I'll fix it during the weekend.

**Comment by tomasvts** [comment]
Example site: https://mixer.com/Monstercat

![mixer-lighhouse](https://user-images.githubusercontent.com/4351937/40828456-f003c4c2-6580-11e8-88f9-44a550b139a8.png)
