### ISSUE TITLE
Extension Error: Couldn't resolve current tab. Check your URL, reload, and tr

### ISSUE THREAD

**Issue by espudaro** [GoogleChrome/lighthouse#5382]
Is possible run Lighthouse in localhost?

**Lighthouse Version**: 2.10.1.3000
**Lighthouse Commit**: 996c5d7ea19e1f7622fd4b2b2b85d6e60460a8d1
**Chrome Version**: 66.0.3359.181
**Initial URL**: http://localhost:3000/listas
**Error Message**: Couldn't resolve current tab. Check your URL, reload, and try again. Found 1 tab(s) with id(s) [277].
**Stack Trace**:
```
Error: Couldn't resolve current tab. Check your URL, reload, and try again. Found 1 tab(s) with id(s) [277].
    at Object.chrome.tabs.query.tabs [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17044:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by paulirish** [comment]
cc @brendankenny first one!

@espudaro yes that shouldn't be a problem. You've hit a bug of ours we're trying to resolve. If you reopen your chrome window and try again, there's a good chance it'll work.

**Comment by paulirish** [comment]
@wardpeet as discussed, we're thinking of using both approaches. If `activeTab` fails, try `lastFocusedWindow` approach. If neither, fail. 

Hypothetically the order could be reversed, but we dont know.

**Comment by espudaro** [comment]
It's works!!! thanks a lot!
