### ISSUE TITLE
False positive H2 audit in Chrome

### ISSUE THREAD

**Issue by ebizindia** [GoogleChrome/lighthouse#5396]
#### Provide the steps to reproduce
1. Run LH on <affected url>
URL: https://www.safestyle-windows.co.uk/mobile-landing/doors-landing/
#### What is the current behavior?
Reports H2 not used for 63 requests.

#### What is the expected behavior?
H2 is used for most of these, specially for resources in the same domain.

#### Environment Information
* Affected Channels: 
* Lighthouse version: 
Generated by Lighthouse 3.0.0-beta.0 |
* Node.js version: N/A
* Operating System: Windows Chrome canary

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for reporting @ebizindia  Strange, I'm seeing that audit passing for CLI but not in Canary
![image](https://user-images.githubusercontent.com/2301202/40852362-140c2c30-657f-11e8-8def-d533721c604e.png). We'll look into it!

**Comment by ebizindia** [comment]
It also reported Google analytics as not using gzip though it was using
gzip.

**Comment by patrickhulce** [comment]
This appears to be fixed in latest Chrome Canary DevTools.
