### ISSUE TITLE
Lighthouse Scoring sheet

### ISSUE THREAD

**Issue by AymenLoukil** [GoogleChrome/lighthouse#5401]
In the Lighthouse scoring sheet, first-cpu-idle weight is 3 instead of 2.
https://docs.google.com/spreadsheets/d/1Cxzhy5ecqJCucdf1M0iOzM8mIxNc7mmx107o5nj38Eo/edit#gid=0

**Comment by patrickhulce** [comment]
nice catch thanks @AymenLoukil should be fixed now!
