### ISSUE TITLE
lighthouse 3 regression in user-timings details

### ISSUE THREAD

**Issue by alekseykulikov** [GoogleChrome/lighthouse#5418]
## Bug report

Lighthouse v3 does not provide `startTime` value for user timing measures. This info is the part of `extendedInfo` but it was removed.

#### Provide the steps to reproduce
1. `lighthouse https://treo.sh`
2. Check JSON report:

```json
  "user-timings": {
      "id": "user-timings",
      "title": "User Timing marks and measures",
      "description": "Consider instrumenting your app with the User Timing API to create custom, real-world measurements of key user experiences. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/user-timing).",
      "score": null,
      "scoreDisplayMode": "informative",
      "rawValue": false,
      "displayValue": "2",
      "details": {
        "type": "table",
        "headings": [{
          "key": "name",
          "itemType": "text",
          "text": "Name"
        }, {
          "key": "timingType",
          "itemType": "text",
          "text": "Type"
        }, {
          "key": "time",
          "itemType": "ms",
          "granularity": 0.01,
          "text": "Time"
        }],
        "items": [{
          "name": "home did mount",
          "timingType": "Measure",
          "time": 49
        }, {
          "name": "boot",
          "timingType": "Mark",
          "time": 716.685
        }]
      }
    }
```

#### What is the current behavior?

The report contains only `time` value.

#### What is the expected behavior?

The report should contain `startTime` value for measures.

#### Environment Information
* Affected Channels: All (report)
* Lighthouse version: 3.0.0-beta.0

**Related issues**

#5402

**Comment by patrickhulce** [comment]
Are there any other properties from user timings you need?

https://github.com/GoogleChrome/lighthouse/blob/c9749e14297f3a2116cebb8c1feacef511121dc2/lighthouse-core/audits/user-timings.js#L70-L77

**Comment by alekseykulikov** [comment]
@patrickhulce No, only this one is missing. There are 4 properties for user timing: `name`, `type `, `startTime` and `duration`(only for measures).
