### ISSUE TITLE
Derived artifacts

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#542]
Screenshots, Speedline, etc. They are all generated from a trace, but do not need to interface with the protocol/browser.

This has caused some awkwardness ([for example](https://github.com/GoogleChrome/lighthouse/pull/538/files#diff-a6b18ac2e75e02d6c1e53d586a319643R180))

#### Strawman proposal

* create `/gather/derived/`
* Speedline, screenshots, critical-request-chains go in there
* devtooltimelinemodel and tracingmodel are created and go in there

in an audit we'd do something like this

```js
// artifacts.requestDerived('speedline').then(speedline =>  { 

artifacts.requestSpeedline.then(speedline =>  { 
   ...
});
```

This allows us to compute these artifacts lazily and cache them, as other audits will want to reuse them.

**Comment by brendankenny** [comment]
Nice. Should be an easy replace at https://github.com/GoogleChrome/lighthouse/blob/df6e013ae6e1cbf4e66199e32148121796476d43/lighthouse-core/driver/index.js#L209, putting in a class with the request* methods instead of the empty `{}`
