### ISSUE TITLE
Lighthouse audit does not take into account local overrides

### ISSUE THREAD

**Issue by katenickerson** [GoogleChrome/lighthouse#5423]
## Bug report
Lighthouse audit does not take into account local overrides.

#### Provide the steps to reproduce
1. Set up local overrides
2. Run LH on any URL
3. Make some local overrides to fix the problems revealed from Lighthouse
4. Run LH again

#### What is the current behavior?
The LH audit does not take into account the changes made from local overrides.

#### What is the expected behavior?
The LH audit should take into account the changes from local overrides, as demoed by Paul Irish at Google I/O.

#### Environment Information
* Affected Channels: Chrome DevTools (Version 67.0.3396.62)
* Operating System: macOS High Sierra 10.13.4

**Comment by paulirish** [comment]
This is true and it's a known issue.  (Thanks for filing though; we had meant to have one by now)

This requires some engineering work to make it happen, but we'd like to take it on!

**Comment by jasongilmour** [comment]
This would be extremely useful for testing how big a performance boost certain changes would make very quickly - without waiting for a production build processes to run or having to spark up a back end server. Is there an ETA on this bug fix?

**Comment by paulirish** [comment]
No ETA, but we want this too. :)

Dev note: Requires supporting multiclient protocol for Audits panel

**Comment by javgar66** [comment]
still not working in  canary Versión 72.0.3591.0

**Comment by alanbuxey** [comment]
still waiting for this essential help feature

**Comment by eduardosada** [comment]
It would be so nice to have this.

**Comment by wardpeet** [comment]
@paulirish is this something we can fix from Lighthouse end? If so feel free to brief me on this. I see the devtools label attached which makes me think this has to be done in devtools.

**Comment by cofinley** [comment]
In the meantime, a workaround can involve a local proxy like Charles or Fiddler to rewrite the server response(s). Was able to run audits on prod this way and didn’t notice any lag from the proxy’s interception.

**Comment by paulirish** [comment]
from #9095 

> reusing the same connection 

Joel started a CL for this last summer. https://chromium-review.googlesource.com/c/chromium/src/+/1132548 We could resurrect that. We'd get local overrides, blocked URLs, protocol monitor and a few other things. 

We'll also need to evaluate if emulation, etc state from devtools will apply during the LH run.

**Comment by connorjclark** [comment]
CL doing above: https://chromium-review.googlesource.com/c/chromium/src/+/1743411

Needed the multi-client changes to fix https://github.com/GoogleChrome/lighthouse/issues/9476.

> We'd get local overrides, blocked URLs, protocol monitor and a few other things.

Confirmed all those things work with the above CL.

**Comment by connorjclark** [comment]
The [multi-client](chromium-review.googlesource.com/c/chromium/src/+/1743411) CL just landed in Chromium. This issue will be resolved in the next canary Chrome. The first stable Chrome to resolve this issue will be Chrome 78, ETA Oct 22.

**Comment by qasimalyas** [comment]
I just ran into this issue and lovely to see it being fixed in canary, only two more days until its in stable. Great job 👍🏼

**Comment by connorjclark** [comment]
By my reckoning it's still 1 month away from landing in Stable. In Beta today tho!

**Comment by qasimalyas** [comment]
Too eager I guess 😋
