### ISSUE TITLE
Do audits need to know which pass their trace comes from?

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#543]
This is some followup from @surma's #531 that outlines a potential refactor that should clean things up.

Brendan pointed this out. I'm gonna _try_ to capture it here...
- each gather exists only in one reload pass.
- so we have a binding between that pass's trace and the gather.
- each audit declares which gathers they need

So, in theory, an audit could automatically get the trace it wants, by walking back through the required artifacts.

**Comment by brendankenny** [comment]
one kind of weird thing is artifact import, where it doesn't make much sense to talk about passes. However this was already introduced in #531 [here](https://github.com/GoogleChrome/lighthouse/pull/531/files#diff-a6b18ac2e75e02d6c1e53d586a319643R103), so we'll have to deal with the weirdness of that one way or the other.

**Comment by surma** [comment]
> * each audit declares which gathers they need

True. I can take a stab at extracting this data.

@brendankenny raises a good point tho. Do we ignore that for now?

**Comment by paulirish** [comment]
I _think_ we're safe if imported artifacts are always treated as defaultPass

**Comment by brendankenny** [comment]
also, ideally traces wouldn't need names at all with this change

**Comment by paulirish** [comment]
There's only one trace. Default pass. 

lol.
