### ISSUE TITLE
ZeroSSL problems with Wp site while changing records, I'm an amatuer but really am motivated and inspired by This amazing community

### ISSUE THREAD

**Issue by BrentDeanCunninghsm** [GoogleChrome/lighthouse#5432]
#### Provide the steps to reproduce
1. Run LH on <affected url>

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**
http://wckdanabolics.com/wp-admin/profile.php
it is the firsrt time I have struggled ever to het this right with Zero SSL and a website by WP'' and hosting wth Go daddy'.
Thanks you!

**Comment by patrickhulce** [comment]
If you're having problems with GoDaddy/WordPress, you can try reaching out to their support or StackOverflow.

Glad you find us an amazing community, but this is a place to discuss bugs/feature requests for Lighthouse 😄
