### ISSUE TITLE
Linkify paths to resources flagged in the report

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#5443]
## Feature request

**Summary**

Audits currently list paths to resources that may have an issue. Unfortunately, there is no way to 1) click the text for a path to display the resource in the Network/Sources panel or 2) click to view the full resource in a new tab (if 1. is not possible)

![image](https://user-images.githubusercontent.com/110953/41070306-e547b2d0-69a6-11e8-8ccc-343eeacf25c4.png)

![image](https://user-images.githubusercontent.com/110953/41070392-88c5fcb4-69a7-11e8-80da-6c5b6a5ff2f1.png)

This makes debugging a little trickier as you need to switch to a different panel in DevTools and manually filter down to find the resource you are after. It would be nice if this was something we made a little lower friction :)

**What is the motivation or use case for changing this?**

Time-saving. When LH flags a list of resources, it's currently cumbersome navigating back and forth to filter down different resources to dig in deeper to a problem. 

**How is this beneficial to Ligthhouse?**

Deeper integration with the rest of DevTools provides a smoother debugging experience for developers wanting to more closely analyze why a resource is problematic.

**Comment by patrickhulce** [comment]
Totally agree linking over to network panel in DT would be awesome 👍 the fact that we're looking at a different page load by the time the report is given to you though really complicates things.

Your 2nd suggestion (turning them into links to open the resource in a new tab) has come up a few times and could be done really quickly/easily, but I've always wondered the provided value. I guess the primary argument is that you can open the DevTools network tab on that resource to take a look at the same stats more easily even if looking at the JS itself isn't helpful? If so, I can do that today :)

Alternative approach would be something like https://github.com/GoogleChrome/lighthouse/issues/1975#issuecomment-394091169 where we show the full URL in a tooltip on hover for easy copying? Not sure which is better.

**Comment by addyosmani** [comment]
> Your 2nd suggestion (turning them into links to open the resource in a new tab) has come up a few times and could be done really quickly/easily, but I've always wondered the provided value. I guess the primary argument is that you can open the DevTools network tab on that resource to take a look at the same stats more easily even if looking at the JS itself isn't helpful? If so, I can do that today :)

I personally think there's a lot of value in this direction with the network panel (vs showing the full URL in a tooltip). With the tooltip approach, it would give you more of the path but there's then an exercise to be done navigating to the Network panel and still trying to filter down to it yourself. I think the idea above is a wee bit nicer :)

**Comment by paulirish** [comment]
Right now i'm thinking an icon (shown on hover) should be the click target to deliver you to network panel. And I'm still thinking we may need some expansion trick. I guess we'll figure it out for responsive mode.

**Comment by addyosmani** [comment]
I would be down for an icon displayed on hover enabling you to click to see the resource in the network panel. Came across a custom audit report today suffered from the same issue of non-clickable URLs and was reminded of this issue :)

**Comment by zephraph** [comment]
As a first pass, could we not just have the link be an actual link? Seeing it in the resource panel or linking to the network tab is definitely nice to have, but I'd settle for just being able to follow the link in the interim. 😅

**Comment by connorjclark** [comment]
> As a first pass, could we not just have the link be an actual link? Seeing it in the resource panel or linking to the network tab is definitely nice to have, but I'd settle for just being able to follow the link in the interim.

ya let's do this.

1) anchorify - just make it clickable, darnit!
2) Linkify - This is a devtools term for "link to a piece of content in DevTools". can do this later.

I'll begin on 1) today.
