### ISSUE TITLE
Example using opn library with Lighthouse report in Node?

### ISSUE THREAD

**Issue by koltclassic** [GoogleChrome/lighthouse#5450]
Hi!

I noticed that under the "Using programmatically" section of the docs, in the section describing the differences from the CLI flags [here](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#differences-from-cli-flags) that the `view` functionality is listed as `Ignored, use the opn npm module if you want this functionality.`

I was wondering if there is a good example of this available? I currently have my Lighthouse report being written to a JSON file, and then `opt` opening the Lighthouse Viewer in Chrome, but I wasn't sure if there was an easy way to open the actual JSON automatically, rather than having to click through and find it (or drag and drop) every time. Would it be best to do something like `await input.uploadFile(myFilePath);`, or is there a more elegant solution? 

Thank you for the help!

**Comment by patrickhulce** [comment]
So `--view` was only supported with the HTML output anyhow. You can get the HTML output programmatically with `flags.output = 'html'` or `flags.output = ['json', 'html']` if you want both

then you write the HTML to a file and call `opn`

```js
const fs = require('fs')
const opn = require('opn')
const lighthouse = require('lighthouse')

(async () => {
  const {report} = await lighthouse(...)
  fs.writeFileSync('report.html', report)
  opn('report.html')
})()
```

**Comment by patrickhulce** [comment]
(Note that this is all with v3, there's not a great workaround for 2.x you'll need to build the HTML report yourself, see https://github.com/GoogleChrome/lighthouse/tree/branch2.x/docs)
