### ISSUE TITLE
how to use existing audits inside a custom audit?

### ISSUE THREAD

**Issue by rustanacexd** [GoogleChrome/lighthouse#5466]
So I am using lighthouse for custom audits by extending the audits class. I am wondering if its possible to use another existing audits inside my custom audit class? or I have to rely only on gatherers.

**Comment by patrickhulce** [comment]
There's not really a blessed way to do this. Our strategy for reusing logic between audits is mostly using computed artifacts. Is there a particular audit you're wanting to use that we should consider a computed artifact?

As a workaround we've used in the past, you could require in the audit class and invoke the audit yourself. DISCLAIMER: the paths/impls might be brittle and aren't guaranteed between minor version bumps.

```js
const SpeedIndexAudit = require('lighthouse/lighthouse-core/audits/speed-index.js')

class MyAudit extends Audit {
  static async audit(artifacts, context) {
    const {rawValue} = await SpeedIndexAudit.audit(artifacts, context)
    ...
  }
}
```

**Comment by rustanacexd** [comment]
@patrickhulce thank you for this, definitely will help a lot!! awesome thanks.
