### ISSUE TITLE
how to calculate 'jpegSize' and 'webpSize' in lighthouse?

### ISSUE THREAD

**Issue by galaa2011** [GoogleChrome/lighthouse#5468]
I learned the code, but did not find the way.
Only found in `ws`, but without any other details.

**Comment by patrickhulce** [comment]
Could you be more specific?

The sizes are determined by the `OptimizedImages` gatherer, and there are two methods.

Via Protcool (new and fast)
https://github.com/GoogleChrome/lighthouse/blob/e02d517b62d3523592e26c2a6ab50c136184d4d8/lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js#L116-L120

Via JS (slow and old)
https://github.com/GoogleChrome/lighthouse/blob/e02d517b62d3523592e26c2a6ab50c136184d4d8/lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js#L33-L71

**Comment by galaa2011** [comment]
I read these codes, but I also did not find any details to calculate `encodedSize` in `_getEncodedResponse`.
I want to know how it handles the command `driver.sendCommand('Audits.getEncodedResponse', params)`

**Comment by patrickhulce** [comment]
https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/inspector/inspector_audits_agent.cc?sq=package:chromium&dr=CSs&g=0&l=29-61

**Comment by galaa2011** [comment]
thanks a lot!
