### ISSUE TITLE
LH stuck at retrieving IF maxWaitForLoad too high 

### ISSUE THREAD

**Issue by sambokai** [GoogleChrome/lighthouse#5469]
#### Provide the steps to reproduce
1. Run LH Node.js Module on [https://www.reishunger.de/wissen/article/41/unterschied-basmati-und-jasmin-reis](https://www.reishunger.de/wissen/article/41/unterschied-basmati-und-jasmin-reis)

Update: It definitely also doesn't work with other URLs that worked only 2 days ago. Neither the sites nor my environment has changed in the meantime.

#### What is the current behavior?
If the maxWaitForLoad is set "too high", in my case **above** around 4000ms, LH gets stuck at the following step:
```
Mon, 11 Jun 2018 14:44:28 GMT status Initializing…
Mon, 11 Jun 2018 14:44:29 GMT status Loading page & waiting for onload URL, Scripts, CSSUsage, Viewport, ViewportDimensions, ThemeColor, Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage, Accessibility, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, WebSQL, MetaDescription, FontSize, CrawlableLinks, MetaRobots, Hreflang, EmbeddedContent, Canonical, RobotsTxt, Fonts
Mon, 11 Jun 2018 14:44:44 GMT Driver:warn Timed out waiting for page load. Moving on...
Mon, 11 Jun 2018 14:44:44 GMT statusEnd Loading page & waiting for onload
Mon, 11 Jun 2018 14:44:44 GMT status Retrieving trace
Mon, 11 Jun 2018 14:44:44 GMT status Retrieving devtoolsLog and network records
```

If its **below** or around 4000ms the report sometimes work, but most of the time doesn't. But it always times out on page load. 

The chrome audit tab give the site a performance score of 0 with the following message, but at least it finishes the report:

`Something went wrong with recording the trace over your page load. Please run lighthouse again. (NO_FMP)`

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 2.9.4
* Node.js version: 6.1.0
* Operating System: Docker / MacOS / AWS Lambda using [lighthouse-lambda](https://github.com/joytocode/lighthouse-lambda)

chromeFlags:
```
exports.flags = [
  '--disable-gpu',
  '--headless',
  '--no-sandbox',
]
```

If `--no-zygote AND/OR` `--single-process` are added @ 10000ms maxWaitForLoad, i get this trace:

```
Mon, 11 Jun 2018 15:04:22 GMT status Initializing…
Mon, 11 Jun 2018 15:04:23 GMT status Loading page & waiting for onload URL, Scripts, CSSUsage, Viewport, ViewportDimensions, ThemeColor, Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage, Accessibility, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, WebSQL, MetaDescription, FontSize, CrawlableLinks, MetaRobots, Hreflang, EmbeddedContent, Canonical, RobotsTxt, Fonts
Mon, 11 Jun 2018 15:04:33 GMT Driver:warn Timed out waiting for page load. Moving on...
Mon, 11 Jun 2018 15:04:33 GMT statusEnd Loading page & waiting for onload
Mon, 11 Jun 2018 15:04:33 GMT status Retrieving trace
Mon, 11 Jun 2018 15:04:33 GMT status Disconnecting from browser...
2018-06-11T15:04:33.085Z	3a8b9826-ac72-189e-6fc8-54fef55152bc	Error: connect ECONNREFUSED 127.0.0.1:33451
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

```

**Related issues**
#4147
#3993
#4287

**Comment by patrickhulce** [comment]
I'm not seeing any of these problems and there have been no code changes to 2.9.4. All of this seems like your environment is causing Chrome to crash/OOM.

How much available memory do you observe while all of this is happening?
How much total memory are you allocating to Chrome/LH?

You mention Docker + MacOS + lambda, can you confirm that in all 3 of these environments you're giving enough resources to Chrome/LH?

**Comment by sambokai** [comment]
Thanks for the response.
I've dedicated 1.5GB of memory in Docker / Lambda. The highest max. memory usage Lambda reported was around 800MB. Can't say much about other types of resources.

Any ideas how i could track down the culprit?

**Comment by patrickhulce** [comment]
Hm, yeah that should be enough. Unfortunately this is the one step where LH doesn't really have any extra information to be logging, it would all be Chrome-side. When you launch Chrome in your environment you can have it dump its output somewhere useful that might give clues.

FWIW you can also enable verbose logging in LH though again, this issue is likely with Chrome logs `const flags = {logLevel: 'verbose'}`

**Comment by sambokai** [comment]
Thank you for the hint. I tried logLevel: 'debug' because i didn't find any documentation on the levels. Will try with verbose again. (Maybe update the docs? :) )

I "solved" the issue by not using the lighthouse-lambda library but the serverless chromeless plugin, but i'm still curious if this is solvable.

Thanks again. Will close this.

**Comment by baocancode** [comment]
@sambokai We updated `lighthouse-lambda` to use the binary of serverless-chrome recently. Your url runs ok now with lighthouse-lambda version 3.1 (or 2.1).

**Comment by nicholasvb89** [comment]
Ran into this issue, but we where able to work around it by removing PWA Audits from the LH run.
