### ISSUE TITLE
How to generate a Lighthouse Report on dynamic URL?

### ISSUE THREAD

**Issue by ray-kim-12** [GoogleChrome/lighthouse#5472]
You can create a lighthouse report by `node_modules/lighthouse/lighthouse-cli/index.js --chrome-flags='headless' localhost:3000` and if its a static url `like localhost:3000/login` that its fine; however, the problem arises when you create something in your app from a modal (for example) and that creates a dynamic url like `localhost:3000/view/jknasjdnajn2as`, which is an external url that is dynamically created. Is generating a lighthouse report on the dynamic url created by my app possible ?

**Comment by patrickhulce** [comment]
It seems like you're looking for something like #3837?

**Comment by ray-kim-12** [comment]
Hi @patrickhulce , don't think I was super clear.

Here is a clearer (hopefully) description of what I mean: 

For instance, I click a button in a modal, and the URL gets updated (without a refresh) as I'm using React. So the url goes from user to user/imsa1253421ido123masd (different every time the button is clicked). 
It also gets copied into the clipboard, but I think the first way is a more straightforward solution

**Comment by brendankenny** [comment]
Closing in favor of #3837
