### ISSUE TITLE
Lighthouse logs everything as error

### ISSUE THREAD

**Issue by pmajcher** [GoogleChrome/lighthouse#5477]
Hi all,

I have added lighthouse + puppeteer into my Jenkins pipeline. I've noticed that all logs from lighthouse have ERROR level. This is how my logs look like:

```
10:45:58 [ERROR] Tue, 12 Jun 2018 10:45:58 GMT status Initializing…
10:45:59 [ERROR] Tue, 12 Jun 2018 10:45:59 GMT status Loading page & waiting for onload Accessibility
10:46:17 [ERROR] Tue, 12 Jun 2018 10:46:17 GMT statusEnd Loading page & waiting for onload
10:46:17 [ERROR] Tue, 12 Jun 2018 10:46:17 GMT status Retrieving devtoolsLog and network records
10:46:17 [ERROR] Tue, 12 Jun 2018 10:46:17 GMT status Retrieving: Accessibility
10:46:18 [ERROR] Tue, 12 Jun 2018 10:46:18 GMT status Disconnecting from browser...
10:46:18 [ERROR] Tue, 12 Jun 2018 10:46:18 GMT status Analyzing and running audits...
10:46:18 [ERROR] Tue, 12 Jun 2018 10:46:18 GMT status Evaluating: `[accesskey]` values are unique
10:46:18 [ERROR] Tue, 12 Jun 2018 10:46:18 GMT status Evaluating: `[aria-*]` attributes match their roles
```

I've checked how logging are implemented in lighthouse. It looks that all 'status' logs should be saved with 'debug' level. It's worth mentioning that I'm getting expected lighthouse scan result and all my tests passes. Does anyone have idea why all lighthouse logs are read in my case?

**Comment by patrickhulce** [comment]
the `debug` package we use for logging outputs to stderr so you can do things like `lighthouse --output=json > report.json`

is your pipeline interpreting all stderr output as error level? the double timestamp makes it look like our raw logs are being reinterpreted by something else

**Comment by brendankenny** [comment]
Without more info, closing for now. If this is still an issue for you, please comment and we can reopen!
