### ISSUE TITLE
How to get HTML page size in kb? 

### ISSUE THREAD

**Issue by rustanacexd** [GoogleChrome/lighthouse#5478]
I don't see any existing artifacts or audits for this. `TotalByteWeight` audit returns kilobytes from network requests. `DOMSize` audit  and `DOMStats` gatherer returns number of nodes right?

**Comment by patrickhulce** [comment]
If the HTML page is in the top 10 heaviest requests you can use the details of the `total-byte-weight` audit to get the size in bytes. Alternatively, you can use the details of the `network-requests` audit to get the transferSize. 


```js
// DISCLAIMER: untested, fresh from
audits['network-requests'].details.items.find(request => request.mimeType === 'text/html' || request.resourceType === 'document').transferSize
```

**Comment by rustanacexd** [comment]
thanks a lot for this snippet btw. I got it with slight modification on where to find
```
const NetworkRequests = require('lighthouse/lighthouse-core/audits/network-requests');

const {extendedInfo} = await NetworkRequests.audit(artifacts);
const kb = extendedInfo.value.find(request => request.mimeType === 'text/html' || request.resourceType === 'document').transferSize;
```

**Comment by rustanacexd** [comment]
@patrickhulce  I am trying to re use some of Accessibility audits. but I am getting not applicable errors. I am using it just like the snippet above. Anything I'm missing here?

**Comment by walmello24** [comment]
Hello. I'm really stuck in this part of the solution. 
what the artifacts part of the script is?

I tried to run it but I got an error

**Comment by cba85** [comment]
If you need a complete code that works to get HTML page size:

```js
import * as chromeLauncher from "chrome-launcher";
import lighthouse from "lighthouse";

const url = "https://ipinfo.io/"; // Example url

const chrome = await chromeLauncher.launch({ chromeFlags: ["--headless"] });
const options = { output: "html", port: chrome.port };

const runnerResult = await lighthouse(url, options);

const htmlSize = runnerResult.lhr.audits["network-requests"].details.items.find((request) =>
      request.mimeType === "text/html" || request.resourceType === "document"
  ).transferSize;

console.log(htmlSize);
```

Hope it will help someone ☺️
