### ISSUE TITLE
Parsing trace file created using chrome driver performance logging mode

### ISSUE THREAD

**Issue by mangeshkakad** [GoogleChrome/lighthouse#5493]
Lighthouse GitHub page shows that it can be use as trace parser as well. I am struggling to make it work and always get empty report back.

Command: lighthouse --config-path=config.json --view http://dummy.com

**Comment by patrickhulce** [comment]
1. What does your config.json look like? 
The critical part of [the docs](https://github.com/GoogleChrome/lighthouse/tree/master/docs#lighthouse-as-trace-processor) to get this to work is the config file not the command :)

2. What audits are you trying to run?
There are only a few that can work with *just* a trace, trace + DevTools log can take you quite a bit further.

**Comment by mangeshkakad** [comment]
I am not 100% sure what config setting i should be using. Is there an example which i can refer to try with my trace file or to test with i can try with json trace file generated by lighthouse only.

My objective is logging all traces offline and then run lighthouse command offline to generate and store all reports.

**Comment by patrickhulce** [comment]
If that's what you're after, it'd be simplest to just use LH for all of this.

1. Run LH on the site and save the results `lighthouse https://example.com -G=./save-results-here`
2. Store the `./save-results-here` folder wherever you need to
3. Run LH on the folder `lighthouse https://example.com -A=./path-to-saved-results-folder`. Note that the while you still need to pass in a URL, LH is only checking to make sure it matches the artifacts, it won't load the site.

**Comment by mangeshkakad** [comment]
Thanks. I will try this tomorrow and will update comments.

**Comment by patrickhulce** [comment]
Yes, but you'll be able to do run the audits whose only artifacts are `traces`, which is just 6 audits. You can move your trace file to a folder and call it `my-other-tool-run/defaultPass.trace.json` now you should be able to pass `lighthouse -A=./my-other-tool-run`
