### ISSUE TITLE
mixed-content fix and smoke tests

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#5498]
Discovered by @patrickhulce in https://github.com/GoogleChrome/lighthouse/pull/5451#issuecomment-397116147

- [ ] request interception is currently broken for us, so the gatherer doesn't really work at all
- [ ] needs a smoke test to alert us to future breakage

**Comment by paulirish** [comment]
confirmed broken on example.com

**Comment by connorjclark** [comment]
This is working today.

```
node lighthouse-cli https://googlesamples.github.io/web-fundamentals/fundamentals/security/prevent-mixed-content/active-mixed-content.html  --preset=mixed-content --view
```

Still no smoke test.
