### ISSUE TITLE
reports.json doesn't give wastedMs per request anymore as compared to LH v2x

### ISSUE THREAD

**Issue by navinjoy** [GoogleChrome/lighthouse#5503]
In LHv2x we use to get the audit report which also gives the details of wastedMs for every call along with totalBytes, wastedBytes etc. But in LHv3 wastedMs is given only at summary level and not for every call.

**Example LH v2x**
`   "results": [
            {
              "url": "/haaaueei.js",
              "totalBytes": 298969,
              "wastedBytes": 140936,
              "wastedPercent": 47.140769689190435,
              "wastedKb": "138 KB",
              "wastedMs": "990 ms",
              "totalKb": "292 KB",
              "totalMs": "2,100 ms",
              "potentialSavings": "138 KB (47%)"
            }`

**Example LH v3**
` "items": [
          {
            "url": "abccdd.js",
            "totalBytes": 29604,
            "wastedBytes": 4209,
            "wastedPercent": 14.218511045338511
          }
        ],
        "summary": {
          "wastedMs": 0,
          "wastedBytes": 4209
        }`

**Comment by patrickhulce** [comment]
The wastedMs in v2 was a very basic linear formula based on the wastedBytes (i.e. if you're trying to prioritize the most important action items, sorting by wastedBytes will give you the same result) and not very accurate in many cases.

In v3, the wastedMs is computed using our actual expectation for the improvement on TTI/overall load which is only done taking all the resources into account.

What is your use case for the wastedMs per resource?

**Comment by brendankenny** [comment]
@navinjoy sounds like you're satisfied without the wastedMs field?

**Comment by navinjoy** [comment]
Yes 👍 
Thank you.
