### ISSUE TITLE
Extension Error: Couldn't resolve current tab. Check your URL, reload, and tr

### ISSUE THREAD

**Issue by ayrasys** [GoogleChrome/lighthouse#5508]
**Lighthouse Version**: 2.10.1.3000
**Lighthouse Commit**: 996c5d7ea19e1f7622fd4b2b2b85d6e60460a8d1
**Chrome Version**: 66.0.3359.181
**Initial URL**: http://localhost:3000/
**Error Message**: Couldn't resolve current tab. Check your URL, reload, and try again. Found 1 tab(s) with id(s) [147].
**Stack Trace**:
```
Error: Couldn't resolve current tab. Check your URL, reload, and try again. Found 1 tab(s) with id(s) [147].
    at Object.chrome.tabs.query.tabs [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17044:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by patrickhulce** [comment]
Did the steps help?

**Comment by wardpeet** [comment]
Thanks for reporting this bug! This bug should be fixed in the latest release of our chrome extension (version 3.0.2).

If the latest extension did not fix this issue for you please open a new bug ticket.

Thanks!
