### ISSUE TITLE
Audit or Gatherer for broken links?

### ISSUE THREAD

**Issue by rustanacexd** [GoogleChrome/lighthouse#5515]
Is there any Audit or Gatherer for broken links already?

**Comment by patrickhulce** [comment]
If by broken links you're referring to links that lead you to a 404/non-existent page, then no we don't have an audit for that. It's a little too close to crawler/site-wide territory for LH and would be rather slow to run per-page.

**Comment by rustanacexd** [comment]
Yes you are right that's what I mean. I'm thinking on writing a custom audit like uses fetch and then check for status then run through Promise.all. Is that bad inside lighthouse? should I write/use separate service outside of lighthouse and then just call it from inside lighthouse?

**Comment by patrickhulce** [comment]
You're free to implement it this way in custom audits, and it should work fine. It's just that if you're wanting to run it across an entire site, it'd be a good idea to cache the lookups you've made so you're not duplicating them on every page. It could be as simple as writing them to a local JSON file, but that bookkeeping would need to live on outside of the scope of LH is all, which is a non-goal for the generic default audits.

**Comment by rustanacexd** [comment]
I see thanks. globals like fetch, URL, location is accessible inside audit? or just gatherer

**Comment by patrickhulce** [comment]
*browser* globals like `fetch` will only be available in code that you execute in the context of the page with `driver.evaluateAsync`, e.g. `const href = await driver.evaluateAsync('window.location.href')`, all other code is run with node. 

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/viewport-dimensions.js is a good simple example of how to do this

**Comment by rustanacexd** [comment]
@patrickhulce  thanks, you are very helpful!
