### ISSUE TITLE
Extension Error: Couldn't resolve current tab. Check your URL, reload, and tr

### ISSUE THREAD

**Issue by tkentor** [GoogleChrome/lighthouse#5516]
I am unable to run Lighthouse on my site, even though it is my only open tab. This is a consistent problem. 

**Lighthouse Version**: 2.10.1.3000
**Lighthouse Commit**: 996c5d7ea19e1f7622fd4b2b2b85d6e60460a8d1
**Chrome Version**: 67.0.3396.87
**Initial URL**: https://www.washingtonpost.com/regional/?_=exc_remarryHeadline
**Error Message**: Couldn't resolve current tab. Check your URL, reload, and try again. Found 1 tab(s) with id(s) [2].
**Stack Trace**:
```
Error: Couldn't resolve current tab. Check your URL, reload, and try again. Found 1 tab(s) with id(s) [2].
    at Object.chrome.tabs.query.tabs [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17044:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by patrickhulce** [comment]
Few Q's:

1) Could you explain a bit more what you mean by a consistent problem? Happens to all sites? Just your site? Happens often, but not always? Always?
2) Is your site the Washington Post?

**Comment by wardpeet** [comment]
Thanks for reporting this bug! This bug should be fixed in the latest release of our chrome extension (version 3.0.2).

If the latest extension did not fix this issue for you please open a new bug ticket.

Thanks!
