### ISSUE TITLE
ideas on how to implement audit similar to LoadFastEnough4Pwa

### ISSUE THREAD

**Issue by rustanacexd** [GoogleChrome/lighthouse#5520]
I am trying to write an audit that is similar to  `LoadFastEnough4Pwa` but only for webpage’s HTML  but where load times for images, JS & CSS are not factored in. I am a looking at `artifact.requestInteractive` but not sure how to filter only for HTML.

**Comment by patrickhulce** [comment]
This gets a bit beyond the scope of standard issue questions ;) but if you're interested in simulated times, take a look at 
https://github.com/GoogleChrome/lighthouse/blob/aeda7c86ea1ff87db78afe6e9bc89e32f2f5ffec/lighthouse-core/gather/computed/metrics/lantern-interactive.js#L37-L58

if you're interested in observed times, take a look at
https://github.com/GoogleChrome/lighthouse/blob/aeda7c86ea1ff87db78afe6e9bc89e32f2f5ffec/lighthouse-core/gather/computed/metrics/interactive.js#L149-L177

that's how interactive is being computed in the two cases.

If you don't need a whole new metric and you just want to know when the main document finished, you can take a look at the graphs/network records for HTML resources. See below for an example of how to traverse them
https://github.com/GoogleChrome/lighthouse/blob/aeda7c86ea1ff87db78afe6e9bc89e32f2f5ffec/lighthouse-core/audits/byte-efficiency/render-blocking-resources.js#L74-L113

**Comment by rustanacexd** [comment]
I will take a look thank you!
