### ISSUE TITLE
Web Inspector crashes after trying to "Download Report" of audit

### ISSUE THREAD

**Issue by watravers** [GoogleChrome/lighthouse#5521]
#### Provide the steps to reproduce
1. Run the LH Performance Audit on a site that has a fairly large amount of issues (i.e. https://www.hertz.com/rentacar/reservation/). 
2. After audit is complete, click the Download Report button in the top left.
3. Wait a few seconds while it attempts to download the audit. 

#### What is the current behavior?
Crashes DevTools after a few seconds of trying to download. As I tried to replicate the issue on other large websites, I noticed that it causes DevTools to crash if the report size is too big.

#### What is the expected behavior?
Download JSON of audit.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 2.9.1
* Operating System: macOS Sierra 10.12.6

**Related issues**

**Comment by patrickhulce** [comment]
@watravers does this seem to happen when your machine is lower on memory? We had previous reports #5047 of similar behavior.

**Comment by watravers** [comment]
@patrickhulce no that's not the issue. I tried to replicate the issue again while making sure I had at least 4GB of memory free and it still closed the DevTools.

**Comment by noodles** [comment]
I am experiencing the same issue and I think it is the size of the JSON report files that is causing the developer tools to crash (~100MB).

- Audits are running OK and taking the usual amount of time
- Developer tools kept crashing when Download Report was clicked & no JSON file downloaded

This kept happening, even after restarting my browser and my laptop. After several more attempts, I was able to download the JSON report but the file size is close to 100MB.

Report generated using the command line tool is only a little over 1MB in size.

I first noticed this when trying to download a report for this site:
https://au.godaddy.com/offers/domains/godaddy-b?countryview=1

Experiencing same issue with: https://www.google.com.au/

Lighthouse 2.9.1
Chrome Version 67.0.3396.87 (Official Build) (64-bit)
macOD High Sierra 10.13.5

**Comment by patrickhulce** [comment]
Hm interesting, the report I downloaded for the GoDaddy link was ~255kb on Canary. Do you still experience the problem using Chrome Canary/LH 3.0?

**Comment by noodles** [comment]
Using Canary, the report downloaded without any issue and was 292 KB

- Lighthouse 3.0.0-beta.0
- Chrome Version 69.0.3468.0 (Official Build) canary (64-bit)

**Comment by patrickhulce** [comment]
We think we've fixed these issues with 3.0 and some recent Chrome-side changes, so I'll go ahead and close this. Please file something new with a specific URL and device configuration if you're unable to download in Chrome 69.0.3489.0 or later!
