### ISSUE TITLE
noopener audit reports issue for noreferrer when href contains absolute url

### ISSUE THREAD

**Issue by miksh7** [GoogleChrome/lighthouse#5522]
`noreferrer` issue was fixed in https://github.com/GoogleChrome/lighthouse/issues/2482 
but there is strange dependency on href value:

    <a target="_blank" href="www.google.com" rel="noopener">Passed</a>
    <a target="_blank" href="www.google.com" rel="noreferrer">Passed</a>
    <a target="_blank" href="www.google.com" rel="nofollow noopener">Passed</a>
    <a target="_blank" href="www.google.com" rel="nofollow noreferrer">Passed</a>

    <a target="_blank" href="https://www.google.com" rel="noopener">Passed</a>
    <a target="_blank" href="https://www.google.com" rel="noreferrer">FAILED</a>
    <a target="_blank" href="https://www.google.com" rel="nofollow noopener">Passed</a>
    <a target="_blank" href="https://www.google.com" rel="nofollow noreferrer">FAILED</a>

Tested in Lighthouse 2.9.1

**Comment by patrickhulce** [comment]
Hm, I'm not able to reproduce those failures in 3.0.0-beta.0.
![image](https://user-images.githubusercontent.com/2301202/41611803-d302c1a6-73a5-11e8-9ff1-b4d4b4fc95c6.png) [jsbin](https://jsbin.com/rumisobidu/edit?html,output)

Can you give latest extension/CLI/Chrome Canary a try?

**Comment by miksh7** [comment]
Chrome Canary (Version 69.0.3465.0 (Official Build) canary (64-bit)) seems to be fine
![image](https://user-images.githubusercontent.com/1747012/41617252-ff926be0-73cd-11e8-812d-8ee976b281f8.png)

**Comment by patrickhulce** [comment]
Cool beans
