### ISSUE TITLE
disabling Runtime Settings through NodeJS

### ISSUE THREAD

**Issue by dcr007** [GoogleChrome/lighthouse#5526]
## Disabling Runtime Settings through NodeJS

**Summary**
How do I enable these cli options through Node JS programmatically :?

  -- disable-device-emulation 
  --disable-cpu-throttling  
  --disable-network-throttling

**Comment by brendankenny** [comment]
If you're pulling from master, in Lighthouse 3.0 those flags have changed to `--disable-device-emulation --throttling-method=provided`. The node options are in general just the camel-cased versions of these, so it would be something like `const result = await lighthouse(url, {disableDeviceEmulation: true, throttlingMethod: 'provided'})`.

If you're working with Lighthouse 2.9.4 on npm, it's the flags you list but the same camel-case pattern: `{disableDeviceEmulation: true, disableCpuThrottling: true, disableNetworkThrottling: true}`
