### ISSUE TITLE
LH3:  does not register a service worker on first report.

### ISSUE THREAD

**Issue by kscm** [GoogleChrome/lighthouse#5527]
#### Provide the steps to reproduce
1. Run LH on https://kinoseed.com/

#### What is the current behavior?
LH does not register site's service worker **on the first run** ("generate report").
Running "Generate report" after the first run, performs as expected.

#### What is the expected behavior?
LH should register site's service worker on the first run.

#### Environment Information
* Affected Channels: 
* Lighthouse version: Lighthouse 3.0.0-beta.0
* Node.js version:
* Operating System:

Runtime settings
URL: https://kinoseed.com/
Fetch time: Jun 20, 2018, 11:54 AM GMT+3
Device: Emulated Nexus 5X
Network throttling: 150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
CPU throttling: 4x slowdown (Simulated)
User agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Generated by Lighthouse 3.0.0-beta.0 

**Related issues**
Since LH does not register the service worker, PWA checklist fails. Extract from the "report":

Progressive Web App
These checks validate the aspects of a Progressive Web App, as specified by the baseline PWA Checklist.
1
Does not register a service worker
2
Does not respond with a 200 when offline
3
User will not be prompted to Install the Web App
Failures: Site does not register a service worker.

**Comment by patrickhulce** [comment]
I'm not able to reproduce this behavior. On the first run, LH found a service worker.
![image](https://user-images.githubusercontent.com/2301202/41731707-f1ab8df6-7533-11e8-9163-8179fef373ed.png)

If you wait a while to register a service worker, then it could be flaky based on if your registration happened yet before we moved on.

**Comment by kscm** [comment]
@patrickhulce , in your case the "manifest" is missing?

I'm not sure what is going on, but this is what I get:
![lherror](https://user-images.githubusercontent.com/28153166/41734464-b29e57e0-758f-11e8-86a7-34824866297f.jpg)

**Comment by prash-mi** [comment]
+1 for this issue. Finding the same with https://m.jungleerummy.com/ . Lighthouse is reporting that the site doesn't register service worker, but in-fact it does on the landing page load itself. Attached the lighthouse report and SW registration registration screenshots.

![lighthouse report](https://user-images.githubusercontent.com/11733935/42024988-1c3853a8-7ae1-11e8-9d0f-5065338bc215.png)
![sw registration](https://user-images.githubusercontent.com/11733935/42024990-1c6d05a8-7ae1-11e8-8a65-499dc8702ea1.png)

**Comment by cyrilletuzi** [comment]
Same issue, and I confirm @adactio diagnostic. Using Chrome Canary 71 with Lighthouse 3.0.3, on the same app, the "no service worker is registered" error happens with default audit options (Simulated fast 3G...), while it's OK when using option "No throttling".

**Comment by cyrilletuzi** [comment]
This issue is now in Chrome stable (70). Any plans on fixing it?

**Comment by patrickhulce** [comment]
The behavior you're describing then @cyrilletuzi and @adactio is #599/#2924. The difference between those throttling options is how long we wait for the page to "settle" and in those cases it seems that the service worker doesn't have complete time to register.

**Comment by cyrilletuzi** [comment]
@patrickhulce OK. For info, the app I'm auditing is a small Angular app, so if it's already a problem in a small app, maybe there is something on the Angular side to manage better about the service worker?

**Comment by Hoten** [comment]
Related #6626

**Comment by gkalpak** [comment]
FWIW, we started running into this on [angular.io][1]. It happens intermittently on the locally served app (using [http-server][1]) - i.e. it doesn't happen when testing the app on Firebase hosting - and it happens much more often on CI than on my machine. (We are tracking this in angular/angular#29910.)

[angular.io][1] is using the Angular SW (obviously :grin:), which is intentionally [waiting for the app to stabilize][3] (as far as Angular in concerned) before registering.

##
Is there a way to specify a larger timeout for Lighthouse or something?

[1]: https://angular.io
[2]: https://www.npmjs.com/package/http-server
[3]: https://github.com/angular/angular/blob/9147092a156203d46cd1c865e06fa72a1e2d4137/packages/service-worker/src/module.ts#L47

**Comment by gkalpak** [comment]
**Update:** For us, it turned out to be related to old Chrome version on CI (v70). Switching to a new version of Chrome/Chromium (v75), via [puppeteer@1.14.0](https://www.npmjs.com/package/puppeteer), make the SW be reliably detected by Lighthouse.

**Comment by gkalpak** [comment]
**Update (2):** Or maybe not: https://github.com/angular/angular/pull/29921#issuecomment-483609596 😞

**Comment by gkalpak** [comment]
I have put any info I have in angular/angular#29910 (but it's mostly specific to the Angular repo/CI).
Any help debugging this would be very much appreciated :grin:

**Comment by patrickhulce** [comment]
> Is there a way to specify a larger timeout for Lighthouse or something?

@gkalpak yes! You can use a custom config that increases `pauseAfterLoadMs` in the `defaultPass`, the default is only 1s.

```js
{
  extends: 'lighthouse:default',
  passes: [
    {passName: 'defaultPass', pauseAfterLoadMs: 10000},
  ]
}

**Comment by gkalpak** [comment]
Thx, @patrickhulce ❤️
It worked 🎉 

<sub>(Is this documented somewhere? If not, it totally should, because I suspect most (if not all) of the many similar issues reported about SW not being detected would be solved by this.</sub>

**Comment by patrickhulce** [comment]
Anytime @gkalpak! :)

Yeah we might want to consider raising those specific docs up to a FAQ level of some sort as I've seen this fairly often with angular apps.

**Comment by Hoten** [comment]
Original URL (kinoseed.com) works in Chrome stable now.

https://www.jungleerummy.com/ (from @prash-mi) seems to no longer have a SW.

https://thesession.org/ (from @adactio) works in Chrome stable now.

https://angular.io/ works in Chrome (but the issue was only reported for local dev / CI).

@patrickhulce think we could detect angular on the page -> use a higher timeout for `pauseAfterLoadMs`? or is that crazy
