### ISSUE TITLE
How to grab/pass the 5 audit score categories

### ISSUE THREAD

**Issue by gsemfield** [GoogleChrome/lighthouse#5531]
**Summary**
Im trying to find the code related to audit scores of the following categories:
"id": "performance"
"id": "pwa"
"id": "accessibility"
"id": "Best-Practices"
"id": "seo"
I need to grab these audit score results and return them similarly to how the following metrics have functions to return their results. 
 - `ttfcp` - First Contentful Paint
 - `ttfmp` - First Meaningful Paint
 - `psi` - Perceptual Speed Index
 - `fv` - First Visual Change
 - `vc` - Visually Complete 100%
 - `ttfi` - First Interactive (vBeta)
 - `ttci` - Time to Consistently Interactive (vBeta)
 - `vc85` - Visually Complete 85%

Is there any existing code within the project that will help me accomplish this? Any recommendations on how I could accomplish this otherwise? I would like to get the five audit scores I mentioned above, in addition to the available metrics, and update a google spreadsheet with the scores after running the lighthouse test.

**Comment by patrickhulce** [comment]
Not 100% sure what you mean, but you can grab the category scores directly from the category objects.

v2
```js
const results = await lighthouse(...)
for (const category of results.reportCategories) {
  console.log(category.id, category.score)
}
```

v3
```js
const {lhr} = await lighthouse(...)
for (const [categoryId, category] of Object.entires(lhr.categories) {
  console.log(categoryId, category.score)
}
```

The `results` and `lhr` variables above are roughly the same as if you were saving the `lighthouse --output=json` to a file and reading that.

**Comment by gsemfield** [comment]
Thanks for clarifying that! Was having trouble finding them in the project code.
