### ISSUE TITLE
Extension Error: Couldn't resolve current tab. Check your URL, reload, and tr

### ISSUE THREAD

**Issue by twalve** [GoogleChrome/lighthouse#5534]
**Lighthouse Version**: 2.10.1.3000
**Lighthouse Commit**: 996c5d7ea19e1f7622fd4b2b2b85d6e60460a8d1
**Chrome Version**: 67.0.3396.87
**Initial URL**: https://www.sbs.com.au/
**Error Message**: Couldn't resolve current tab. Check your URL, reload, and try again. Found 1 tab(s) with id(s) [1779].
**Stack Trace**:
```
Error: Couldn't resolve current tab. Check your URL, reload, and try again. Found 1 tab(s) with id(s) [1779].
    at Object.chrome.tabs.query.tabs [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17044:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by patrickhulce** [comment]
Did the steps provided solve the problem @twalve?

**Comment by paulirish** [comment]
👋 @twalve!  thx for filing. :)

**Comment by twalve** [comment]
@patrickhulce I think the root cause was lack of feedback on progress so I got over-eager and started interacting with the page too quickly, before a full resolution of the tests. 

I didn't get any steps to resolve, but everything was fine on a refresh and restart.

@paulirish Happy to file if it helps. I'll keep a weather eye on future uses, in the hopes I can gather more relevant details. 

I'm going to `Close and comment`, knowing the issue can be reopened if I can help
