### ISSUE TITLE
LH times out waiting for page to load only in DevTools/Extension

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#5537]
#### Provide the steps to reproduce
1. Run LH on https://au.godaddy.com/offers/domains/godaddy-b?countryview=1

#### What is the current behavior? 

LH waits 45 seconds for page to load, and **THEN** spends ~30s retrieving the trace.

#### What is the expected behavior? 

LH waits ~10 seconds for page to load (as it does correctly with CLI)

#### Environment Information
* Affected Channels: Devtools, Extension
* Lighthouse version: 3.0.0-beta.0
* Node.js version: N/A
* Operating System: Mac OS X

**Related issues**
discovered in #5521

**Comment by paulirish** [comment]
We should see if this happens in LR too

**Comment by brendankenny** [comment]
whatever was happening isn't happening any more, so I'm closing :)
