### ISSUE TITLE
whats the difference between lighthouse vs puppeteer crawler?

### ISSUE THREAD

**Issue by rustanacexd** [GoogleChrome/lighthouse#5542]
Are they using the same crawler? can lighthouse  crawl the websites are built on such modern frontend frameworks as AngularJS, React and Vue.js? Thank you!

**Comment by patrickhulce** [comment]
> Are they using the same crawler? 

Lighthouse is not a crawler. Lighthouse will audit a single URL.

> can lighthouse crawl the websites are built on such modern frontend frameworks as AngularJS, React and Vue.js?

Lighthouse can load them, yes.

While we're here...you seem to come here a lot :) using LH is great! But some of these questions would be better suited to [StackOverflow](https://stackoverflow.com/questions/tagged/lighthouse) and are more application development how-to that folks other than core team could answer too.

**Comment by rustanacexd** [comment]
gotcha. thanks
