### ISSUE TITLE
Performance timing errors on extension 0.7.0

### ISSUE THREAD

**Issue by NickTulett** [GoogleChrome/lighthouse#555]
First meaningful paint
-1
Speed Index
-1
Estimated Input Latency
-1
Time To Interactive (alpha) (target: 1,700)
-1

Seems to be the same on our web app or even this very page

**Comment by brendankenny** [comment]
Generally that means there was some error when collecting data. -1 on Speed Index and First Meaningful Paint sometimes mean the page loaded so quickly that the sampling of page painting wasn't fast enough to yield any useful information, but I've never seen -1 on all of these before.

Is this still on an internal page not accessible to us?
What performance numbers are you seeing on a PWA like https://platform-status.mozilla.org/ for instance?

**Comment by NickTulett** [comment]
I get the same

**Comment by brendankenny** [comment]
I think this is an update in tracing format in Chrome (no `TracingStartedInPage` event in the trace). Currently only happening in Canary...I've bisected it and will follow up
