### ISSUE TITLE
"Background and foreground colors do not have a sufficient contrat ratio." Really?

### ISSUE THREAD

**Issue by Mlocik97-issues** [GoogleChrome/lighthouse#5559]
#### Provide the steps to reproduce
1. Run LH on any webpage (for example on youtube.com).

#### What is the current behavior?
I have this on my webpage:
![screenshot_186](https://user-images.githubusercontent.com/31345346/41911236-651f38de-794c-11e8-85cc-4be882f80049.png)
Lighthouse:
![screenshot_187](https://user-images.githubusercontent.com/31345346/41911241-679a8118-794c-11e8-94ac-c86c46afd002.png)

CSS:
```
div#warningbackground { background-color: #ff0000; }
span#warningtext {
    color: #ffffff;
    font-size: 20px;
}
span#warningtext a {
        background-color: #ffffff;
	padding: 2px 5px 4px 5px;
	color: #0000ff;
}
```

#### What is the expected behavior?
I think contrast ratio is more than OK.

#### Environment Information
* Affected Channels: 
*Chrome: 67.0.3396.99
a337fbf3c2ab8ebc6b64b0bfdce73a20e2e2252b-refs/branch-heads/3396@{#790}
* Operating System: Windows 10

V8 6.7.288.46
**Related issues**

**Comment by justinribeiro** [comment]
The color contrast check is extended from the `AxeAudit`, which verifies that foreground and background colors meet the WCAG 2 AA contrast ratio thresholds. In your case, the defined colors foreground `#ffffff` and background `#ff0000` only have a contrast ratio of `4.00:1`, which (correctly) does not pass the audit.

**Comment by patrickhulce** [comment]
Yup, @justinribeiro hit the nail on the head 👍

@Mlocik97-issues you can use a site like http://contrast-ratio.com/ to play around with colors that have sufficient color contrast.

**Comment by biwin** [comment]
Another resource to play around with is https://dequeuniversity.com/rules/axe/3.1/color-contrast

**Comment by englishextra** [comment]
@Mlocik97-issues Don't worry

[The Myths of Color Contrast Accessibility](https://uxmovement.com/buttons/the-myths-of-color-contrast-accessibility/)
![cca-bluebuttons](https://user-images.githubusercontent.com/537127/95136697-48424900-076f-11eb-962a-833feeac14ea.png)

**Comment by englishextra** [comment]
Well, this is outrageous:

#FFFFFF on #252E31  do not have a sufficient contrast ratio.

![2020-10-18_000601](https://user-images.githubusercontent.com/537127/96353580-04880180-10d6-11eb-8fff-8f2f9367ac8a.jpg)
![2020-10-18_000632](https://user-images.githubusercontent.com/537127/96353582-05b92e80-10d6-11eb-89cf-9e4e13eee060.jpg)
![2020-10-18_000645](https://user-images.githubusercontent.com/537127/96353583-05b92e80-10d6-11eb-927b-2a7201256d37.jpg)

**Comment by patrickhulce** [comment]
@englishextra that almost certainly is because of the offscreen slides that page has that mess up background color detection. Separate bug welcome though I don't know if we'll be able to do much about it (axe seems to just skip them now).

**Comment by justinribeiro** [comment]
@englishextra axe-core v4.x appears to resolve this issue (I can't duplicate the above issue in via @axe-core/cli on 4.0.2, as seen running the specific color-contrast rule on the cli below). 

![image](https://user-images.githubusercontent.com/643503/96617012-eda10500-12b7-11eb-8363-98ab3b184091.png)


Currently, we're pegged to 3.5.5, but this is on the v7 roadmap for update in #11207

**Comment by englishextra** [comment]
@justinribeiro Oh yeah, thanks a lot. Good news.
