### ISSUE TITLE
id attribute must be unique

### ISSUE THREAD

**Issue by bhargavgunreddy** [GoogleChrome/lighthouse#5561]
This issue showed up when running an audit for a page with content using ag-grid 
first id **borderLayout_eRootPane**l
second id **borderLayout_eGridPanel**

**Comment by patrickhulce** [comment]
Do you have a public URL for this page?

**Comment by paulirish** [comment]
Does the page use shadow DOM? we've seen this problem most commonly when different shadow roots contain the same ID.

**Comment by bhargavgunreddy** [comment]
Unable to upload snapshot or url as this is blocked by employer. I have checked DOM and the id's are given as above but I got this error in the audit. Ill try to replicate it in my machine and share the url

**Comment by paulirish** [comment]
If you have more info to share, we can reopen. CLosign for now
