### ISSUE TITLE
[BUG] Does not provide fallback content when JavaScript is not available

### ISSUE THREAD

**Issue by Mlocik97-issues** [GoogleChrome/lighthouse#5563]
#### Provide the steps to reproduce
1. Run LH on <affected url>

#### What is the current behavior?
If I use this code (example code):
```
<noscript>
	<iframe src="noscript.html" frameborder="0" style="height: 100%; width: 100%;"></iframe>
	<noframes>You maybe have disabled JavaScript and Frames, please enable JavaScript or frames in You browser. More info: <br>
		<a href="http://tutorial.com/how-to-enable-js">How to enable JavaScript</a> <br>
		<a href="http://tutorial.com/how-to-enable-frames">How to enable frames</a>
	</noframes>
</noscript>
```

![screenshot_192](https://user-images.githubusercontent.com/31345346/41937076-9a506bf2-798f-11e8-9b87-0ce234936045.png)

#### What is the expected behavior?
do not report warning

#### Environment Information
* Affected Channels: 
*Chrome: 67.0.3396.99
a337fbf3c2ab8ebc6b64b0bfdce73a20e2e2252b-refs/branch-heads/3396@{#790}
* Operating System: Windows 10

V8 6.7.288.46
**Related issues**

**Comment by patrickhulce** [comment]
I suppose it's arguable if an `iframe` is sufficient content when script is not enabled. Traversing the entire frame tree to find text is a lot of complexity to add for a minimally useful audit.

Aside: curious why not just redirect to the noscript page if the iframe is the only intended content?

**Comment by Mlocik97-issues** [comment]
that code was only for example,... but I think, it does not report warning when someone use code similiar to that in example.

**Comment by sekisanchi** [comment]
Phishtank needs this improvement, I guess.

**Comment by patrickhulce** [comment]
> Maybe lighthouse need only look if noscript tag is in webpage, and if it isn't empty.

That's a good idea 👍 the only point of the audit is to force the developer to consider the noscript case :)
