### ISSUE TITLE
Running Lighthouse in Browser using Browserify

### ISSUE THREAD

**Issue by Purus** [GoogleChrome/lighthouse#5569]
I am using the below lighthouse.js file to create bundle.js file using browserify.

```
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');

module.exports = function (url, opts, config = null) {

  return chromeLauncher.launch({
    chromeFlags: opts.chromeFlags
  }).then(chrome => {
    opts.port = chrome.port;
    return lighthouse(url, opts, config).then(results => {
      return chrome.kill().then(() => results.lhr)
    });
  });
}
```
In HTML page, I have the below JS.

```
    require('lighthouse')('https://google.com', {}).then(results => {
      console.log(results);
    });
```

I am getting the below issue when running it in browser. It's not able to find the platform/chrome path.

```
bundle.js:formatted:10657 Uncaught (in promise) TypeError: chromeFinder[utils_1.getPlatform(...)] is not a function
    at Launcher.<anonymous> (bundle.js:formatted:10657)
    at Generator.next (<anonymous>)
    at bundle.js:formatted:10524
    at new Promise (<anonymous>)
    at __awaiter (bundle.js:formatted:10503)
    at Launcher.launch (bundle.js:formatted:10646)
    at Object.<anonymous> (bundle.js:formatted:10564)
    at Generator.next (<anonymous>)
    at bundle.js:formatted:10524
    at new Promise (<anonymous>)
```

**Question**: Is it possible to run lighthouse as a web javascript library? If so how to proceed?

**Comment by patrickhulce** [comment]
> Is it possible to run lighthouse as a web javascript library?

Not really, we actually do do this as part of our build process for the extension and DevTools https://github.com/GoogleChrome/lighthouse/blob/281582439dbf7a45b00e3673840f0b93542d66aa/lighthouse-extension/gulpfile.js#L116-L166, but you won't be able to run LH on any old webpage. It requires a connection to the browser which is only given to you via `chrome.debugger` for Chrome Extensions and special-cased DevTools.

**Comment by Purus** [comment]
Following the gulp example, can it be converted to a JS file and executed using Bookmarklet (running it from google browser bookmark)?

**Comment by patrickhulce** [comment]
No, running as a bookmarklet would not be possible (but that's kinda what the Chrome extension is for 😄)

**Comment by paulirish** [comment]
@purus lighthouse requires a DevTools Protocol connection to do its work. so it can't run completely inside of the page.

**Comment by Purus** [comment]
Thanks for the details. I was hoping to find some ideas to use along with
selenium or via stand alone way. Please consider this issue closed.
