### ISSUE TITLE
blob url marked as insecure

### ISSUE THREAD

**Issue by shahraship** [GoogleChrome/lighthouse#5574]
#### Provide the steps to reproduce
1. Run LH on [https://coursables.com/](https://coursables.com/)

#### What is the current behavior?
It reports the blob url as insecure

#### What is the expected behavior?
blob url should be marked as secure

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 2.9.1
* Node.js version:
* Operating System: Mac OS High Sierra

**Comment by patrickhulce** [comment]
Thanks for filing @shahraship! Fixed in 3.0 :)

PS - if that's your site, nicely done on the 100s 😃 
![image](https://user-images.githubusercontent.com/2301202/42047401-f1b63f90-7ab4-11e8-829d-d55e9858ebf8.png)

**Comment by shahraship** [comment]
Thank you @patrickhulce ... Yes, it's my site. Now if only I can figure out how to get the performance to 100. Any suggestions.. would be greatly appreciated.
