### ISSUE TITLE
How to generate performance test report for Entire website(All URL's) using Lighthouse in a single command

### ISSUE THREAD

**Issue by MohamedRasool786** [GoogleChrome/lighthouse#5588]
I have been get with performance test report for a single URL
For Example : https://www.amazon.com
I can get result for this alone, But I need performance test report for All URL's inside that website using lighthouse.

**Comment by patrickhulce** [comment]
Good question! I think you're looking for a project like [lightcrawler](https://github.com/github/lightcrawler). LH won't do this for you out of the box.
