### ISSUE TITLE
Extension Error: Couldn't resolve current tab. Check your URL, reload, and tr

### ISSUE THREAD

**Issue by benfares** [GoogleChrome/lighthouse#5598]
**Lighthouse Version**: 3.0.0
**Lighthouse Commit**: d6aa4416d7b60beb47207c476a674b0149e58675
**Chrome Version**: 67.0.3396.87
**Initial URL**: https://range-tour.com/
**Error Message**: Couldn't resolve current tab. Check your URL, reload, and try again. Found 1 tab(s) with id(s) [806].
**Stack Trace**:
```
Error: Couldn't resolve current tab. Check your URL, reload, and try again. Found 1 tab(s) with id(s) [806].
    at Object.chrome.tabs.query.tabs [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17201:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by patrickhulce** [comment]
@benfares by chance were you double clicking or hitting enter soon after starting the run?

**Comment by wardpeet** [comment]
Thanks for reporting this bug! This bug should be fixed in the latest release of our chrome extension (version 3.0.2).

If the latest extension did not fix this issue for you please open a new bug ticket.

Thanks!
