### ISSUE TITLE
Unset globals in network helper

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#56]
https://github.com/GoogleChrome/lighthouse/blob/master/helpers/network-recorder.js#L21-L81

@brendankenny I think this is on you, sir. It's in case other people require('lighthouse') at some point in the future and we just, you know, stomp the global.

**Comment by paulirish** [comment]
I just did this in devtools-timeline-model and it was not fun. Let's defer this until later.

**Comment by paulirish** [comment]
FWIW here's how I sandboxed WebInpspector but still managed to make it work: https://github.com/paulirish/devtools-timeline-model#sandboxing-webinspector-for-node

@paullewis if you're okay with it i think we should close this for the moment. We'll incur decent churn every time we pull in more WebInspector pieces.

It's also possible there will be an upstream wrapper, and/or devtools will be more node-friendly by the time we really need this.

**Comment by paulirish** [comment]
Thinking we'll use ServiceWorkerManager.js for SWs, so going to close this for now until things settle down
