### ISSUE TITLE
[Best Practices] Failed Audits: does not use HTTPS (about:blank and blob)

### ISSUE THREAD

**Issue by vlptrs** [GoogleChrome/lighthouse#5600]
Hi, i have a issue with the report of lighthouse..
There are failed audits.

#### What is the current behavior?
https://drive.google.com/open?id=1Rvc0-BYrWWk3R0gE6ftmh_xcpfqfgfj4

#### What is the expected behavior?
1) **"about:blank"** always writing without protocol.
2) **"blob"** includes url with protocol.

#### Environment Information
* Lighthouse version: 2.9.1

**Comment by patrickhulce** [comment]
Thanks for filing @vlptrs! This should be fixed in 3.0.0.
