### ISSUE TITLE
Minimum chrome version

### ISSUE THREAD

**Issue by Blackop778** [GoogleChrome/lighthouse#5622]
**Summary**
I haven't seen any documentation about a minimum chrome version to run Lighthouse programmatically or through CLI, so I'm wondering if there is one. Apologies if I simply missed it somewhere. Thanks!

**Comment by jagaspehar** [comment]
Fuck off. Comprehended.

**Comment by patrickhulce** [comment]
It's in the output of the CLI `--help` and on our readme ;)

Currently you can get away with 66 or later, but our policy is to just support current stable + canary, so any environment where you are updating LH regularly, you should be sure to be updating Chrome regularly as well.
