### ISSUE TITLE
Some sites were not formatted while displaying under chrome

### ISSUE THREAD

**Issue by kirankbc** [GoogleChrome/lighthouse#5632]
Some sites were not formatted while displaying under chrome like for example www.lazada.com where as the same site is displayed perfectly under firefox / IE. Whats the issue actually? Please advice. Thanks

**Comment by patrickhulce** [comment]
This doesn't seem to be the right place to file your issue @kirankbc, I would try [StackOverflow](http://stackoverflow.com/) instead :)
