### ISSUE TITLE
Report Download Failure

### ISSUE THREAD

**Issue by fad250** [GoogleChrome/lighthouse#5638]
## Bug report
Report Download Failure
#### Provide the steps to reproduce
1. Run LH on <dashboard.zorbitsitsmath.com>
2. Clicked on download report

#### What is the current behavior?

 Fails and closes the developer tools.

#### What is the expected behavior?

Report downloaded

#### Environment Information
* Affected Channels:  DevTools 
* Chrome version: Version 67.0.3396.99 (Official Build) (64-bit)
* Node.js version: v8.11.2
* Operating System: Windows 10

**Comment by patrickhulce** [comment]
Is this happening for you with Chrome Canary too? We haven't seen any reports of this happening in v3 yet (Chrome 68+).

**Comment by fad250** [comment]
@patrickhulce It works on Chrome Canary fine.

**Comment by paulirish** [comment]
Thanks. And sorry for the bug!
