### ISSUE TITLE
Ensures all elements with a role attribute use a valid value Impact: critical(Axe audit fails)

### ISSUE THREAD

**Issue by sripalreddyadamala** [GoogleChrome/lighthouse#5639]
Hi All,
I am using ngx popover in my application and I am getting above role="popover" as critical error when I run audit reports with  light house and axe. This attribute is generated dynamically from
ng x bootstrap popover content. I am just @curious is this an issue with chrome audit findings or this is something should handled by bootstrap team. Technically we need role="popover" but for some reason chrome audit fails  as invalid aria attribute.

Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap:1.8.1
Angular:4.0.0
ngx-popover:0.0.16
![image](https://user-images.githubusercontent.com/17653691/42457872-8fc059fa-8366-11e8-91aa-f75d12693c7c.png)

**Comment by justinribeiro** [comment]
The audit is correct; `popover` is not a valid role value in the ARIA specification. I believe that you're most likely looking for [tooltip](https://www.w3.org/TR/wai-aria-1.1/#tooltip) for such a case, and that the `ngx-popover` element is your culprit (see [PopoverContent.ts#L13](https://github.com/pleerock/ngx-popover/blob/5de65e7d93098ef31da9d9197ad789ce78bbcda2/src/PopoverContent.ts#L13)).
