### ISSUE TITLE
Replace details tag in html report viewer to support jumping to a specific audit by id anchor

### ISSUE THREAD

**Issue by nmchau** [GoogleChrome/lighthouse#5640]
## Feature request

**Summary**

In html report viewer, each audit component has id element but many of them are inside the details tags. So, it's impossible to jump to a specific audit component by its id without expanding the parent details tags. 
For example, report.html#mobile-friendly link can't allow us to jump to 'mobile friendly' audit because this audit stays inside a details tag.

**What is the motivation or use case for changing this?**
Some people are just interested in some specific audits among many audits supported by Lighthouse. 

**How is this beneficial to Lighthouse?**
Links which allow jumping directly to different audits in report viewer can be bookmarked or shared easily.

**Comment by patrickhulce** [comment]
Neat idea! We might want to consider alternatives to support this, perhaps instead we could auto-open the parent with JS on navigation or something.

**Comment by paulirish** [comment]
solution: if targeted audit is within a collapsed details (or multiple of them), we open those with JS. maybe we also highlight background via `:target` CSS.

**Comment by brendankenny** [comment]
let's track in #6668
