### ISSUE TITLE
missing filmstrip speedline metric in LH 3.0.1 report ?

### ISSUE THREAD

**Issue by maaxobelix** [GoogleChrome/lighthouse#5647]
The report generated by running "**lighthouse https://www.google.com/ --view**" does not contain any filmstrip speedline metric above the screenshots in Performance section 
![ok1](https://user-images.githubusercontent.com/38969243/42524828-2df0ca90-84a4-11e8-8280-04616744f6eb.png)

which can be found in the sample report of https://googlechrome.github.io/lighthouse/reports/dbwtest-3.0.0-alpha.html.
![ok0](https://user-images.githubusercontent.com/38969243/42524843-39cc4fe2-84a4-11e8-98fc-a1d41795d3e4.png)

do I missing something?
[the test has been done with win10x64]

**Comment by patrickhulce** [comment]
Thanks for filing @maaxobelix! You're not going crazy it was removed with the introduction of simulation :) Basically the recorded screenshots we saw won't align with the simulated run we're reporting metrics on, and we thought it'd be confusing for folks.

We could bring it back on observed runs, but it'd be quite a bit of work to try to get something reasonable-looking for the default simulated case.

**Comment by maaxobelix** [comment]
Thanks Patrick for explaining.

It was very useful to see the progressive of page loading in visual with a "timing rule", even the screenshot is recorded with a frequency pre-defined, which is helpful is not to having exact timestamp but how the page evolved in time (ex. the first 3 sec). 
Ex. with a frequency of 300ms, the page showing blank (4 first screenshots) till 1200 ms then unchanged (again, 4 unchanged screenshot) till 2400 ms to fully loaded, etc...

![ok2](https://user-images.githubusercontent.com/38969243/42527943-a298bdc8-84ac-11e8-9b6a-dbb8673cb0b9.PNG)

**Comment by wardpeet** [comment]
👍 showing it on observed runs.

**Comment by paulirish** [comment]
duping into #5844
