### ISSUE TITLE
Is viewport parsing working correctly?

### ISSUE THREAD

**Issue by klessou** [GoogleChrome/lighthouse#5653]
Hello,

I've hard times to figure out why viewport tags is not detected on https://www.fondan.co

Here is the tag : 
<meta data-n-head="true" content="width=device-width,initial-scale=1" name="viewport">

Thx for your help,

Best,

**Comment by patrickhulce** [comment]
It seems to be working properly, I don't see a meta[name=viewport] on that site either.

![image](https://user-images.githubusercontent.com/2301202/42585340-2d772ef6-84ea-11e8-966f-baf09395b9a7.png)

**Comment by justinribeiro** [comment]
This doesn't appear specific to lighthouse. It looks like they're using Nuxt.js and have the meta tags injected in the SSR, as view source has them:

![image](https://user-images.githubusercontent.com/643503/42588376-861d2d0a-84f2-11e8-9fd9-6ac2c6029697.png)

However, when testing in Chrome and Firefox (I didn't test other things), those tags aren't there (`document.querySelectorAll("meta")` returns an empty NodeList).

![image](https://user-images.githubusercontent.com/643503/42588511-efd404c6-84f2-11e8-9c09-e183d7eb1155.png)

I'm not a vue expert, but my hunch is that vue-meta is mis-configured and updating the DOM, essentially removing the meta tags. According to the docs, you need to set `<html data-vue-meta-server-rendered>` to prevent this (see ["How to prevent the update on the initial page render"](https://github.com/declandewet/vue-meta#performance)).

**Comment by klessou** [comment]
Hello Guys,

Thanks a lot for your help! It really helped me figure out why I had weird issues regarding PWA...
Actually I used NUXT.JS and after some days I found out that there is an opened bug regarding that issue : https://github.com/nuxt-community/nuxt-i18n/issues/100

Meanwhile seo = false fix my issue, I hope nuxt-i18n will fix that soon.

Best !

**Comment by wardpeet** [comment]
@klessou I believe this issue is resolved on the lighthouse part so this ticket can be closed? If not please let me know

**Comment by klessou** [comment]
Indeed it can be closed. Thx
