### ISSUE TITLE
Manifest tests fail if manifest is behind HTTP basic authentication

### ISSUE THREAD

**Issue by nigelmcnie** [GoogleChrome/lighthouse#5658]
#### Provide the steps to reproduce
1. Enable HTTP basic authentication for a domain which has a manifest
2. Run LH against this domain with the "Best Practices" audit turned on

(sorry I can't provide an example one easily)

#### What is the current behavior?
![screen shot 2018-07-12 at 6 21 30 pm](https://user-images.githubusercontent.com/288723/42615951-7c8ab492-8600-11e8-9aa0-122888be9a2d.png)

LH logs that two console errors about the manifest are received. As these don't happen when I view the site without LH, I'm assuming that LH triggered those console errors itself, then reported on them. Chrome itself can get at the manifest just fine, if I browse to it directly in the same browser.

#### What is the expected behavior?
LH uses the basic auth credentials that chrome knows to download the manifest.

Alternatively if that is not possible, LH informs the person running the test that the manifest couldn't be checked.

#### Environment Information
* Affected Channels: DevTools (maybe others? idk)
* Lighthouse version: 2.9.1
* Node.js version: -
* Operating System: macOS Sierra

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @nigelmcnie!

When I load a site that has basic auth on a page and manifest, I see the same errors that LH does.
![image](https://user-images.githubusercontent.com/2301202/42647750-b9f26fb0-85b9-11e8-85d8-e239e31cdb42.png)

LH is just requesting the manifest through Chrome the same way it does in the Application tab, so it appears that manifests behind basic auth don't seem to work properly. Note that I can still navigate to the manifest and view it normally even though I can't request. What does the application tab show you for yours?

If it's also erroring, this bug belongs at [crbug.com](https://bugs.chromium.org/p/chromium/issues/list) :)

**Comment by nigelmcnie** [comment]
Huh, right you are! I'll file over there.

**Comment by wardpeet** [comment]
thanks for reporting @nigelmcnie ! I'm closing this one as lighthouse can't fix this issue.

**Comment by dominickng** [comment]
Update for posterity here: the manifest link tag must have `crossOrigin="use-credentials"` specified if the manifest is behind some sort of auth (requires cookies, HTTP auth, etc.). Otherwise, the web app manifest spec mandates that Chrome fetches the manifest without supplying any credentials that the browser currently has (in order to respect CORS).
