### ISSUE TITLE
List of css ressources in unused-css-rules seems trimmed

### ISSUE THREAD

**Issue by etnbrd** [GoogleChrome/lighthouse#5663]
I used Lighthouse 2.9.4 and 3.0.2, and in both versions, the result of the performance audit for `unused-css-rules` seems trimmed, and don't display all the css resources.
I have around 190 css files, but get reports for roughly half of them.
With around 20 css files, I fet reports for roughly half as well.

How are selected the files that show up in the report?
How could I get Lighthouse to analyze all the files I want it to analyze?

Back story:
I am trying to identify in a big sass code base, which module is used by which page.
So I built and included every sass module into its own css file so that Lighthouse can produce a detailed report on the code coverage of every individual module.

**Comment by patrickhulce** [comment]
@etnbrd we omit files from the output if they didn't have at least 2KB of wasted rules, if each file is relatively small that's probably why you're not seeing it.
https://github.com/GoogleChrome/lighthouse/blob/acea63d40a654441f982050a3dac43f8389580de/lighthouse-core/audits/byte-efficiency/unused-css-rules.js#L10

If you want a quick hacky solution to this, you could probably run something like

`sed -ibak "s/IGNORE_THRESHOLD_IN_BYTES = 2048/IGNORE_THRESHOLD_IN_BYTES = 0/" ./node_modules/lighthouse/lighthouse-core/audits/byte-efficiency/unused-css-rules.js`

and give it another whirl

**Comment by etnbrd** [comment]
Awesome. Thanks a lot :)
