### ISSUE TITLE
Extension: update to pptr 1.6's target.page()

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#5664]
pptr 1.6.0 added proper support for getting a background page via a target. We should switch to that over the current approach.

https://github.com/GoogleChrome/puppeteer/releases/tag/v1.6.0

**Comment by wardpeet** [comment]
Sounds neat, let me give it a go :)

**Comment by brendankenny** [comment]
turns out we couldn't use this because you still have to find the particular extension you want, and there's not a great way to do that. See my failed PR where I tried to fix this here: https://github.com/GoogleChrome/puppeteer/pull/3694

Closing as our current approach is good enough.
