### ISSUE TITLE
Expose both user agents in "Runtime settings"

### ISSUE THREAD

**Issue by Svenmay** [GoogleChrome/lighthouse#5665]
#### Provide the steps to reproduce
1. Run LH on any page. I used https://tolwin.spdns.org/index.html, but that is not important. You need access to the "access.log" of the webserver that is hosting the page under test.

#### What is the current behavior?
It is just a nit-picking, but probably worth mentioning. The Lighthouse report mentions the "UserAgent" in runtime settings. If you compare that user agent with the real user agent of the test requests, then they don't match.

I don't think this has any impact on the tests itself (at least not for me), but it is a little bit confusing to see requests with different user agents in your webserver's logfile coming from the same tool. Fixing this probably has no high prio, but maybe....if it is easy to fix....would be nice if this could be fixed/aligned.

I have attached two screenshots that hopefully illustrate the problem better. I was able to reproduce the issue on Lighthouse-Extension (3.0.2) and the build-in version of lighthouse in Chrome DevTools (3.0.0-beta.0), but this does NOT happen with the lighthouse test from webpagetest.org.   

#### What is the expected behavior?
The user agent used by lighthouse should be consistent and match with the user agent mentioned in the runtime settings. 

#### Environment Information
* Affected Channels: Lighthouse-Extension (3.0.2) and the build-in version of lighthouse in Chrome DevTools (3.0.0-beta.0)
* Lighthouse version:
* Node.js version:
* Operating System: CrOS Version 69.0.3473.0 (Offizieller Build) dev (64-Bit)
![useragents_lighthouse_extension](https://user-images.githubusercontent.com/39521568/42682206-2d54ad1c-868a-11e8-9408-36217ce9ac0b.png)
![useragents_lighthouse](https://user-images.githubusercontent.com/39521568/42682207-2d6f25fc-868a-11e8-9aa7-c9b8ad4d8277.png)

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for reporting @Svenmay!

This was actually intentional behavior because by default Lighthouse enables mobile emulation which uses all identical user agent strings. It's really reporting to you the user agent of the host device. Do you have thoughts on a better label that might communicate this? `Host user agent:`/`Generated by device with user agent:` or something?

**Comment by patrickhulce** [comment]
We discussed a bit offline and think the real need is both "What user agent did LH use to make the requests" and "What machine was this report generated on". Both of these seem worthwhile to expose.
