### ISSUE TITLE
App getting killed too soon

### ISSUE THREAD

**Issue by sakshij** [GoogleChrome/lighthouse#5675]
I have written some custom audits following examples here: https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit

Earlier lighthouse used to give enough time to my app such that I was able to set the custom load metrics in window object. If I remember correctly, I read somewhere that it will wait for the last API call to finish and then run the audits. 

However, after having migrated to 3.0.2, it is killing my app too soon. The `max-wait-for-load` is also not being honored. Due to this, all my custom audits are failing. Please help!

**Comment by patrickhulce** [comment]
Hey @sakshij thanks for filing!

If your audits require extra time you can increase the config setting for the defaultPass `pauseAfterLoadMs`.

Example:

```js
module.exports = {
  extends: 'lighthouse:default',
  // wait at least 10s after the page has loaded
  passes: [{passName: 'defaultPass', pauseAfterLoadMs: 10000}],
};
```

`max-wait-for-load`, OTOH, is for the **maximum** amount of time to wait, not the minimum so you can probably remove that from your setup :)

**Comment by sakshij** [comment]
It worked perfectly! Thanks :)

**Comment by bakiasib** [comment]
Hey @patrickhulce  Why does increasing pauseAfterLoadMs, or networkQuietThresholdMs lower the TBT time?

**Comment by adamraine** [comment]
> Hey @patrickhulce Why does increasing pauseAfterLoadMs, or networkQuietThresholdMs increase the TBT (Total Blocking Time) time? I thought it shouldn't affect it at all.

Can you file a separate issue for this with an example.
