### ISSUE TITLE
Report: no clear indication that results are for a 3g connection

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#568]
It's unclear that the results are for a simulated 3g connection. 

Description text at the top of the report would be helpful that indicates the report is for:
- the first run of the page
- on a 3g simulated connection, with the exact network conditions that were simulated
- anything else I'm forgetting.

**Comment by hsablonniere** [comment]
Should we also specify the device viewport that was "simulated"?

**Comment by ebidel** [comment]
Definitely. All the settings should be included in the description. When it
shows a report, there should be no questions on what it just did :)

**Comment by ebidel** [comment]
I think we should prioritize this now that the new report is in. https://github.com/GoogleChrome/lighthouse/pull/784 adds emulation info to the left nav, but I don't think that UI is ideal. 

@chowse would you be able to help us with designs? Perhaps some small text in the new top nav or n the footer?

**Comment by ebidel** [comment]
This info is now behind a dropdown at the top of the report:

![screen shot 2017-02-01 at 11 15 32 am](https://cloud.githubusercontent.com/assets/238208/22522249/c6ca013c-e86f-11e6-961a-1134854cf3f2.png)
