### ISSUE TITLE
Question: What's the difference between beforePass and pass in a gatherer

### ISSUE THREAD

**Issue by eduardosada** [GoogleChrome/lighthouse#5681]
Code says `beforePass` is called before navigation to target url:
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/gatherer.js#L33

But `beforePass` and `pass` are called one after each other: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gather-runner.js#L416

should we replace all `beforePass` with `pass`?

**Comment by patrickhulce** [comment]
@eduardosada you're looking at the `GatherRunner` named methods while the comments are referring to how the gatherers are called.


The comment section below should help here.
https://github.com/GoogleChrome/lighthouse/blob/098d28189ba33f292d4f06824d62116a372aa976/lighthouse-core/gather/gather-runner.js#L40-L54


In summary: 
* use `beforePass` if it has to happen before navigation
* use `pass` if you have to do something while still tracing (should be *very* rare)
* use `afterPass` for everything else that just looks at the page

**Comment by eduardosada** [comment]
You are right 😄. Thank you.
