### ISSUE TITLE
x-ms-bmp should be flagged under "serve images under next gen formats"

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#5687]
Discovered this while testing the `legacy-image-formats" feature policy, which warns developers about using legacy image formats like BMP. 

#### Provide the steps to reproduce
1. Run LH on https://feature-policy-demos.appspot.com/test

#### What is the current behavior?

LH does not recommend that a BMP image be served in another format.

#### What is the expected behavior?

There's a bmp image on that page (https://homepages.cae.wisc.edu/~ece533/images/sails.bmp) that should be flagged under the "serve images under next gen formats" audit:

<img width="774" alt="screen shot 2018-07-18 at 4 27 29 pm" src="https://user-images.githubusercontent.com/238208/42913040-82e056d4-8aa7-11e8-8a1c-f68f861101c1.png">

#### Environment Information
* Affected Channels: DevTools / all
* Lighthouse version: 3
* Node.js version: n/a
* Operating System: Mac os, canary 69.0.3495.0

**Comment by patrickhulce** [comment]
We target bitmaps but it looks like this one has a mime type of `image/x-ms-bmp`, we'll expand our regex :)
