### ISSUE TITLE
Report - user timeline results only show start of mark

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#569]
https://www.chromestatus.com/features uses the User Timing API to record metrics to the timeline. The report only shows the start of each mark, and not the measurement (total time it took):

![screen shot 2016-08-09 at 11 26 53 am](https://cloud.githubusercontent.com/assets/238208/17528533/b29ecbf0-5e24-11e6-93b8-fb478fecf17f.png)

**Comment by brendankenny** [comment]
Looks like this is an issue of waiting long enough for the page to consider itself loaded. The gather phase pauses for too short a time after page load ([500ms by default right now](https://github.com/GoogleChrome/lighthouse/blob/0269917f968214a8ac58b26246bf0927998af133/lighthouse-core/gather/drivers/driver.js#L29)) for the features on chromestatus to load and call `performance.measure()`, so the measures never show up in the trace we use.

A quick hacky solution would be to allow the pause after load time to be specified on the command line (though that doesn't help the extension without exposing it in the options as well). Less hacky would be to start working on https://github.com/GoogleChrome/lighthouse/issues/519#issuecomment-235953634 and have some way of specifying that the Lighthouse gatherers should wait until some user timing event has fired.

**Comment by ebidel** [comment]
FWIW, this seems to be working now for https://www.chromestatus.com/features. Probably because we've add a service worker and made it faster...which has changed timings?

**Comment by brendankenny** [comment]
ha, I assume so. We still only pause for 500ms after load

**Comment by ebidel** [comment]
I take that back, it's sporadic.

**Comment by ebidel** [comment]
I think this is fixed.

**Comment by paulirish** [comment]
closing then, feel free to reopen if you see it return.

**Comment by ebidel** [comment]
@brendankenny says this isn't fixed.

**Comment by brendankenny** [comment]
I don't think this is actually solved, we just may be taking long enough on that particular site for the site measurements to finish :) We really need #519 and/or #627 to fix this

**Comment by ebidel** [comment]
@brendankenny now that #627 is fixed, can we close?

**Comment by paulirish** [comment]
We good now. 

Merry christmas.
