### ISSUE TITLE
TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by wardpeet** [GoogleChrome/lighthouse#5701]
Some sites seems to override the URL property with a string or not a constructor which means our robots.txt cannot be fetched. We should guard us against URL injection like we do for promises.

https://sentry.io/google-lighthouse/lighthouse/issues/495524891/

```
TypeError: URL is not a constructor
  File "<anonymous>", line 6, in getRobotsTxtContent
  File "<anonymous>", line 16, in __nativePromise.resolve.then._

TypeError: URL is not a constructor
```

**Comment by brendankenny** [comment]
fixed in #5748!
