### ISSUE TITLE
Respect Referrer-Policy header

### ISSUE THREAD

**Issue by laukstein** [GoogleChrome/lighthouse#5709]
#### Provide the steps to reproduce
1. Run LH on https://laukstein.com/web/2011-tippers-widget

#### What is the current behavior?
LH recommendation for external links while has header `Referrer-Policy: no-referrer`
> Add `rel="noopener"` or `rel="noreferrer"` ...

![grabilla q15520](https://user-images.githubusercontent.com/183966/43095780-9942597e-8ebf-11e8-8faa-468c8c74b1b3.png)

#### What is the expected behavior?
If page has `Referrer-Policy: no-referrer` (spec https://w3c.github.io/webappsec-referrer-policy/) it expected to behavior as all links having `rel="noreferrer"` and not expected LH to specify it also as HTML attribute. Know that perhaps other Referrer-Policy values like `same-origin`, etc. must also fix this issue.

#### Environment Information
* Affected Channels: Extension
* Lighthouse version: 3.0.3
* Operating System: Win10 64-bit

**Comment by brendankenny** [comment]
since the header support unfortunately varies with [edge and mobile safari vs everyone else](https://caniuse.com/#feat=referrer-policy), we'll need to define the combinations that work cross browser

**Comment by brendankenny** [comment]
Though to be fair, apparently `rel="noopener"` [doesn't work in edge](https://caniuse.com/#feat=rel-noopener), which we don't flag as an issue today.

**Comment by laukstein** [comment]
@brendankenny if Edge isn't the issue and likely mobile Safari either (IE is depreciated), I see no problem in my proposal in browsers current state.

**Comment by brendankenny** [comment]
No problem, I'm just saying we'll want to encourage cross-browser support. § 11.1 of the spec [gives an example of providing a fallback for browsers on older specs](https://w3c.github.io/webappsec-referrer-policy/#unknown-policy-values).

**Comment by paulirish** [comment]
Agree we don't handle the header here.

We need to define what the cross-browser recommendation is, since browser support is all over the place. Can you help us define that, @laukstein ?

Once that's done, we can do the implementation. cc @ebidel

**Comment by paulirish** [comment]
also see discussion in #2485

**Comment by laukstein** [comment]
@paulirish all mine browsers that supports `rel=noopener` (except iOS Safari) supports also `Referrer Policy` header. If iOS Safari has no importance here then I guess it is needles to argue the browsers legacy.

Anyway I tested latest Chrome, Firefox, Edge, IE (supported on IE11), Safari, iOS Safari and all supports `<meta name=referrer content=never>` that acts like `Referrer Policy: no-referrer`.

I haven't yet heard any plans depreciating meta referrer **never** legacy value in browsers ([**spec**](https://html.spec.whatwg.org/multipage/semantics.html#meta-referrer), supported since [Chrome 21](https://www.chromestatus.com/feature/5126747842412544)). I predict this will not be removed before supported `Referrer Policy: no-referrer`.

For conclusions:
1. `<meta name=referrer content=never>` is fine (probably for next ~ 2 years)
2. `<meta name=referrer content=never>` + `Referrer Policy: no-referrer` is safest way to go making sure will work "forever"
3. for sure `rel="noreferrer"` is needles when used one of above options

Paul, do we need any more information?

**Comment by patrickhulce** [comment]
I agree on closing. The `Referrer-Policy` spec makes no mention of our desired behavior while [noreferrer link type](https://www.w3.org/TR/2014/REC-html5-20141028/links.html#link-type-noreferrer) specifically calls out its effect on the `opener` property that this audit is really about.

**Comment by laukstein** [comment]
cc @patrickhulce @brendankenny 
Attribute `rel="noreferrer"` delivers same result `Referrer-Policy: no-referrer` (only with header it aplies globally for all links) as is said in spec https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-no-referrer:

> ... would send no Referer header

I disagree with

> Since the audit goal is noopener behavior and not just to not have a referrer, I believe we should close this issue.

because it is not something Lighthouse says, but instead:
> Add `rel="nooper"` **or** `rel="noreferrer"`

**Comment by patrickhulce** [comment]
@laukstein the purpose of the audit is to prevent the global `opener` property, not to avoid the `Referrer` header being sent. We really don't care either way if the `Referrer` header is sent.

The spec you've linked to that @brendankenny quoted does not say that `rel="noreferrer"` is equivalent to `Referrer-Policy: no-referrer`. It says that `Referrer-Policy: no-referrer` will not send the referrer header and makes no mention of the `opener` property like `rel="noreferrer"` does.

> because it is not something Lighthouse says, but instead:

The title of the audit communicates this with `Links to cross-origin destinations are safe`, while Referrer may leak information, it's not inherently unsafe like `opener` is. The extended description that mentions `rel="noreferrer"` is indicating one of the ways to accomplish this goal. `Referrer-Policy: no-referrer` does not appear to be a spec-approved way of accomplishing this goal, so we shouldn't be checking for it.
