### ISSUE TITLE
PWA, Accessibility & SEO Score is Zero (0).

### ISSUE THREAD

**Issue by pateldevarsh** [GoogleChrome/lighthouse#5721]
Hello Tech Team, 

As per recent update from Google, we are trying to sort out our website with lattest update according to Optimization view.

Mean while on checking the entire website URL by URL we are receiving the PWA, Accessibility & SEO Score 0 in many URLs, starting with some of Service Pages and including with entire Case Study Section of website.

So can you guys please look in to this matter why we are receiving this kind of results.

For your consult here is URL of our Website, Please check it and let us update with the solution.

**Website URL : https://www.hitechbpo.com/**

Thanks.

**Comment by brendankenny** [comment]
closing for now. Please comment and we can reopen if you're still seeing this issue!
