### ISSUE TITLE
https://sites.google.com/view/world-heritage-minimin

### ISSUE THREAD

**Issue by DrGerberMd** [GoogleChrome/lighthouse#5729]
It does not work for my main key-words: camping, B&B, Fish Farm, Resto, ecotourism.

Thanks.

Jacques Gerard Berube

**Comment by patrickhulce** [comment]
Not sure I understand your issue. This is a place to discuss the Lighthouse auditing tool which doesn't really care what your keywords are. 

Are you dissatisfied with your search ranking on these keywords? If so, this isn't the right place for that :)
