### ISSUE TITLE
Performance bug

### ISSUE THREAD

**Issue by marekka** [GoogleChrome/lighthouse#5733]
Hi, is your tool really working?

Just tested my website, got A Grade on Tmetix and webpagetest.org, whilst lighthouse shows Performance = 0 ?

**Comment by paulirish** [comment]
Can you share your URL? We can help explain why Lighthouse is scoring it so low.

**Comment by marekka** [comment]
https://www.hedgehogdigital.co.uk/

**Comment by justinribeiro** [comment]
At the moment, I'm having trouble duplicating the 0 score on either WebPageTest or the Audits panel. Would you mind following the [bug report template](https://raw.githubusercontent.com/GoogleChrome/lighthouse/master/.github/ISSUE_TEMPLATE/Bug_report.md) to provide some additional information?

![image](https://user-images.githubusercontent.com/643503/43340333-d427b8c6-9190-11e8-9629-0ca01c437d35.png)
![image](https://user-images.githubusercontent.com/643503/43340337-d7fc7450-9190-11e8-9cde-f464cc0f22dc.png)

**Comment by wardpeet** [comment]
@marekka can you tell us how you're running Lighthouse? maybe a shareable url of the report? 
Do you have any extensions installed that interfere with performance?

I do not get a 0 but you're score is slow because of the download time of your stylesheets and fonts.

**Comment by drewmcmillan** [comment]
@paulirish Any information about why this issue was closed?
