### ISSUE TITLE
firstMeaningfulPaint vs. observedFirstMeaningfulPaint ?

### ISSUE THREAD

**Issue by ecumike** [GoogleChrome/lighthouse#5738]
**Summary**
Using Lighthouse CLI.. in report.audits.metrics there are several props that have an "observed" version, but the numbers are WAY different. Just want to understand what the difference is and which is the "normal" one you see in the timeline/perf console metrics:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/7328459/43300137-7cbdd9b8-912b-11e8-8e20-6d6ff1c7bc9d.png">

**Comment by patrickhulce** [comment]
Observed is what actually happened on the page load that we observed while the non-prefixed set are the metric values that were displayed in the report. When `--throttling-method=devtools|provided` they will be identical to their observed counterparts. They will be different when using simulated throttling which will take what was observed and "replay" it using different throttling settings (Fast 3G and 4x CPU slowdown by default). 

It's quite rare for the simulated values to be lower than the observed values though. What were the circumstances of your run? Is it possible Chrome window was hidden until around 8 seconds or your machine was on a very poor network connection?

**Comment by ecumike** [comment]
Hm ok. Yes.. we are using the CLI and running this as a script, headless.

**Comment by ecumike** [comment]
And assuming that is the case... sounds like we shouldn't use the "observed" ones and keep using the non-prefixed ones because those are the actual report metrics #s.

**Comment by ecumike** [comment]
Thanks!
