### ISSUE TITLE
Add Visually Complete 100% to group: 'metrics'

### ISSUE THREAD

**Issue by denar90** [GoogleChrome/lighthouse#5741]
Hi,
Does it make sense to add Visually Complete 100% to metrics group, it is for pwmetrics? It's kinda "delightful" indicator for loading perf. It's already present in `metricsDefinitions()` but used for assets savings.

cc @paulirish @patrickhulce

**Comment by paulirish** [comment]
not adding an audit for it.

the observed value in is the 'metrics' audit as `observedLastVisualChange`

**Comment by denar90** [comment]
Thx Paul, further discussion could be found [here](https://github.com/paulirish/pwmetrics/pull/178#discussion_r210146128).
