### ISSUE TITLE
Cache Control Header not parsed correctly when multiple headers with same field name returned

### ISSUE THREAD

**Issue by calumbrodie** [GoogleChrome/lighthouse#5742]
#### Provide the steps to reproduce
1. Run LH on https://www.hunterboots.com/gb/en_gb/ or https://www.hunterboots.com/us/en_us/ 

#### What is the current behavior?

Response from the domain 'media.hunterboots.com' are reported as failing the 'inefficient cache policy test' with a reported TTL of 'None'

Example

https://media.hunterboots.com/public/fetch/contentful/Ly9pbWFnZXMuY3RmYXNzZXRzLm5ldC9waHk2aWgxcHoyM3EvMXVtQkZsS1VvSVFNYXdTS3FxcWdFNC82MDkyMzAyNjlmMWNlY2Y5YWNhNWZiMDQwMDFjMzhiMS9NT0JJTEVfMTAwMFgxMDAwLmpwZw/w_480,q_76/MOBILE_1000X1000.webp

Despite these responses having the following two headers:

cache-control: max-age=25920000, public
cache-control: no-transform

#### What is the expected behavior?

Assets from this domain, with these headers should not fail the test.

Locally I've been able to test a response where the response ONLY contains 1 header:

cache-control: max-age=25920000, public

And the tests then pass. I believe the issue is that the parser isn't correctly interpreting the response when there are multiple cache control headers, which I believe is valid:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

#### Environment Information
* Affected Channels:  DevTools
* Lighthouse version: 3.0.0-beta.0
* Node.js version:
* Operating System: Version 70.0.3504.0 (Official Build) canary (64-bit) on OSX

**Related issues**

**Comment by calumbrodie** [comment]
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js#L184

This line assumes that each header field name is unique

**Comment by wardpeet** [comment]
@calumbrodie thanks for filling this bug! It is indeed our mistake to treat it as a unqiue header.
