### ISSUE TITLE
RFC: A few file renames

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#575]
Proposal for file renames in the codebase:

* All tests like `test/audits/icons.js` get a `-test` filename suffix so: `icons-test.js`
* `config/index.js` to `config/config.js`

I think that may be it. Any others people would like?

**Comment by wardpeet** [comment]
they stay in a test folder or will they be moved into src as well? (I rather have them separate)

**Comment by paulirish** [comment]
stay separate in `/test` yeah.

**Comment by wardpeet** [comment]
you may assign me if you like, I can go through the tests to see if I can cleanup a bit as well.

**Comment by brendankenny** [comment]
I'm good with this as well

**Comment by brendankenny** [comment]
`aggregator/index.js` could be renamed as well, but as discussed, it's so short it should probably just be inlined into its call site.

**Comment by paulirish** [comment]
@wardpeet sounds good! all yours. :)

If you do any cleanup in tests, make sure it's in a separate commit. One commit should be only the `git mv`s and nothing else.

**Comment by wardpeet** [comment]
sure thing :) I'll just create seperate pr's ;)
