### ISSUE TITLE
Add an audit to check form settings for autocomplete

### ISSUE THREAD

**Issue by martinschierle** [GoogleChrome/lighthouse#5768]
Done

Done

**Feature request summary**

Many ecommerce sites fail on implementing autocomplete forms correctly, which is bad UX for users and drives down conversion rates. We have a clear set of recommendations for this here:

https://developers.google.com/web/fundamentals/design-and-ux/input/forms/#top_of_page

Some might not be possible to check automatically, but then again many seem trivial to check (existence of autocomplete attribute and palceholder etc.). Also stuff like if the soft keyboard covers the input field etc.

Probably no time for that :-/

**What is the motivation or use case for changing this?**
Improve mobile UX for users.

**How is this beneficial to Ligthhouse?**
It is a clear recommendation from Google to build forms like this, so a Google-driven tool should check these things.

**Comment by paulirish** [comment]
This is all definitely true. :)  

We do have #1639 filed. That captures `autocomplete` attribute use and appropriate `type` attribute choices. 

Do you want to focus this issue on something else? Placeholder or keyboard overlapping?

**Comment by martinschierle** [comment]
Hi Paul, sorry for having missed this - I did a search first,  but maybe I screwed something up ;-)
The keyboard overlapping would be cool, but is probably rather a nice-to-have - the ones already listed in the other ticket are the more important ones. Feel free to close this out then!

**Comment by paulirish** [comment]
> Hi Paul, sorry for having missed this - I did a search first, but maybe I screwed something up ;-)

nooooooo worries dude. all good.

thanks for bringing it up! and if you're interested in contributing, we can give you some more tips to get you started. :) cheers
