### ISSUE TITLE
Support for WCAG 2.1 

### ISSUE THREAD

**Issue by jivanova** [GoogleChrome/lighthouse#5775]
Have you planned to provide support for the WCAG 2.1 compliance and could you give me approximate time frame when to expect it?

**Comment by robdodson** [comment]
Great question!

Under the hood Lighthouse just uses [the axe-core library](https://github.com/dequelabs/axe-core) to test. There are a handful of [open issues](https://github.com/dequelabs/axe-core/issues?q=is%3Aopen+is%3Aissue+label%3A%22wcag+2.1%22) in their repo related to adding more WCAG 2.1 tests.

Unfortunately an automated tool like Lighthouse / axe can't really test all of WCAG—there are some things a machine just can't detect. So while these tools are a useful guide, they're no substitute for additional human testing. We try to state this in the Lighthouse a11y report up at the top.

**Comment by jivanova** [comment]
Thanks :)
