### ISSUE TITLE
rttMs vs. requestLatencyMs?

### ISSUE THREAD

**Issue by ecumike** [GoogleChrome/lighthouse#5777]
We are trying to build custom 'real life' profiles for our automated testing (using Node) for our users and not quite sure the difference between these two settings:

```
--throttling.rttMs                   Controls simulated network RTT (TCP layer)
--throttling.requestLatencyMs        Controls emulated network RTT (HTTP layer)
```

Is there further documentation other than on https://github.com/GoogleChrome/lighthouse  about these somewhere, or can someone add clarity. For example.. if we ping a server or look at Verizon or Akamai data for "average latency"... which one of these two settings would that map to?

**Comment by justinribeiro** [comment]
Which flag to set depends on what method you want to use via `--throttling-method`; "devtools", "provided", or "simulate".

If you're using `simulate`, you're setting `--throttling.rttMs` and `--throttling.throughputKbps`.

If you're using `devtools`, you're setting `--throttling.requestLatencyMs` and `--throttling.downloadThroughputKbps`.

The primary difference is the that `simulate` is computed throttling after a trace has been recorded, while `devtools` is implemented within Chrome at the request-level. For an in-depth explainer as to the pros/cons of each and other methods that you might want to use, I recommend the [Throttling doc](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md) here in the repo. It has some additional details and resources that should help as you define your custom profiles.
