### ISSUE TITLE
It can't detect registered SW when run in Audits dev tools

### ISSUE THREAD

**Issue by maxinminax** [GoogleChrome/lighthouse#5782]
I have receive message when run test my site https://m.sosanhtaichinh.com/ in Audits chrome dev tools.
`Failures: Site does not register a service worker, Service worker does not successfully serve the manifest's start_url, No start URL to fetch: No usable web app manifest found on page https://m.sosanhtaichinh.com/.`

But when test by lighthouse extension, it don't have that problem.
Have any different between lighthouse in chrome dev tools and chrome extension?

**Comment by patrickhulce** [comment]
Hm, what versions of Lighthouse is it using in DevTools and in the extension? (Should say at the bottom of the report what LH version it was generated with)

**Comment by brendankenny** [comment]
Closing for now. If you can share the details asked for above, please comment here or in #5527 and we can continue investigating.
