### ISSUE TITLE
report: Lighthouse repeatedly returns 0 Performance score on m.bukalapak.com

### ISSUE THREAD

**Issue by maulshh** [GoogleChrome/lighthouse#5793]
running audit on Chrome Version 63.0.3239.108 (Official Build) (64-bit) for several pages at bukalapak.com mostly return performance index at 0.

we suspect that this also cause "fetch by google" crawler, and also google pagespeed insight to return an error, which highly damage our SEO.

this is some audit results from url,
- https://m.bukalapak.com/trend/xiaomi
- https://m.bukalapak.com/c/handphone

[m.bukalapak.com-20180807T122639.txt](https://github.com/GoogleChrome/lighthouse/files/2265103/m.bukalapak.com-20180807T122639.txt)
[m.bukalapak.com-20180807T112537.txt](https://github.com/GoogleChrome/lighthouse/files/2265104/m.bukalapak.com-20180807T112537.txt)

please kindly help :)

**Comment by justinribeiro** [comment]
I'm having a difficult time duplicating this consistently on M68 (stable) and LH 3.0.0. 

In the cases I can duplicate the performance 0 or ?, it appears that `speed-index` and `screenshot-thumbnails` score are set to `null` with a `NO_SCREENSHOTS` error. I can similarly duplicate this behavior _sometimes_ when just running a standalone trace.

Could be related to the attempted redirect to an app url (ala `bukalapak://m.bukalapak.com/trend/xiaomi?link_click_id=535829416988081073`), which seems prevalent in the mobile views, but that's just a hunch on my part.

![image](https://user-images.githubusercontent.com/643503/43851537-cb3e7a3e-9aef-11e8-8192-ccc1052928ac.png)

**Comment by maulshh** [comment]
thanks for the suggestion @justinribeiro, while filing this report we are also trying to fix some issues we suspect causing this performance errors at the moment.

but, is there any relation between this performance error and an error in fetch by google and also pagespeed insight? or is it just my suspicion?

**Comment by justinribeiro** [comment]
I can't say for certain as I don't have access to either Fetch as Google or PSI codebases. What I can say from previous experience is that those tools can error in similar ways if they have trouble rendering or downloading assets that your site relies on.

**Comment by patrickhulce** [comment]
Thanks for investigating @justinribeiro we've seen similar issues with pages using app URLs, so it might indeed be related. We'll have to dig in more.

**Comment by fad250** [comment]
I have been experiencing the same issue. Previous my website performance was around 37, now it either returns 0 or close to zero. I audited with other popular sites and I see very similar results. 

![image](https://user-images.githubusercontent.com/15860769/45487263-67a94c00-b738-11e8-8fc8-0621e9defc52.png)

![image](https://user-images.githubusercontent.com/15860769/45487284-768ffe80-b738-11e8-8ad0-5fdd19ec4d6c.png)

**Comment by wardpeet** [comment]
Is it possible to send us a full report so we can see what might go wrong.
@fad250 @maulshh

**Comment by fad250** [comment]
@wardpeet This is not happening anymore. My tests results are now back to normal.

**Comment by wardpeet** [comment]
thanks @fad250 for the update!

@maulshh  this looks like an really old lighthouse 2.5.1 and chrome version. Can you reproduce it in our latest version?

**Comment by maulshh** [comment]
we have already have some suspect as what justinriberio has suggested. thank for all the support.
