### ISSUE TITLE
Passing --quiet still outputs `which` failure to stdout

### ISSUE THREAD

**Issue by asayamakk** [GoogleChrome/lighthouse#5795]
#### Provide the steps to reproduce
1. Run LH on Docker

```
$cat Dockerfile
FROM centos:7

RUN yum update -y && \
    yum groupinstall -x ctags -y "Development Tools" && \
    yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

WORKDIR /root
RUN curl https://nodejs.org/dist/v8.11.3/node-v8.11.3-linux-x64.tar.xz -o /root/node-v8.11.3-linux-x64.tar.xz && \
    tar xf /root/node-v8.11.3-linux-x64.tar.xz

ENV PATH /root/node-v8.11.3-linux-x64/bin:$PATH

ADD google-chrome.repo /etc/yum.repos.d/google-chrome.repo

RUN yum install -y google-chrome-stable && \
    npm install -g lighthouse && \
    ln -s /root/node-v8.11.3-linux-x64/bin/lighthouse /usr/local/bin/
```

sorry for my messy Dockerfile. but now plz ignore it.

#### What is the current behavior?

when I run lighthouse with `--quiet` option, I expect only result will be output.
However error/warning message is shown on stdout

```
$docker run --rm -it lighthouse /root/node-v8.11.3-linux-x64/bin/lighthouse http://example.com --chrome-flags="--headless --no-sandbox --disable-gpu" --output=json --enable-error-reporting --quiet  > /tmp/out

$head -10 /tmp/out
which: no chromium-browser in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
which: no chromium in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
{
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/68.0.3440.84 Safari/537.36",
  "lighthouseVersion": "3.0.3",
  "fetchTime": "2018-08-07T08:19:52.765Z",
  "requestedUrl": "http://example.com/",
  "finalUrl": "http://example.com/",
  "runWarnings": [],
  "audits": {
```

#### What is the expected behavior?

surpress error/warning messages when `--quiet` is passed
or those messages should be shown on stderr

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 3.0.3
* Node.js version: v8.11.3
* Operating System: CentOS 7

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/1475

**Comment by patrickhulce** [comment]
Thanks for reporting @asayamakk! This looks like a bug with [chrome-launcher](https://github.com/GoogleChrome/chrome-launcher) not suppressing the output of the Chrome finding process. Would you mind filing this issue over there? 

Just the docker env and the bit about `which` output showing up in the stdout of the process should be sufficient with a link back to this issue :)
