### ISSUE TITLE
Hover background & tooltip not working together

### ISSUE THREAD

**Issue by BlitZz96** [GoogleChrome/lighthouse#5796]
#### Provide the steps to reproduce
1. Run LH on google.com
2. Hover over the performance metrics

#### What is the current behavior?
On hovering and moving mouse upward the different metrics, the tooltip cancels the background effect even tho tooltip is not displayed.
![Gif](https://i.gyazo.com/cbdcb56db8cca9231a9635ecc37c26cf.gif)

#### What is the expected behavior?
The hovered metric's background color should change the way you move your mouse downward.

#### Environment Information
* Affected Channels: DevTools 
* Lighthouse version: 3.0.0
* Node.js version: 10.6.0
* Operating System:  Mac OS 10.13.6

**Comment by paulirish** [comment]
me to fix with CSS pointer-events:none in the keyframe anim

**Comment by wardpeet** [comment]
@BlitZz96 it's fixed in current master. Thanks for reporting
