### ISSUE TITLE
Requests to Serve Next-Gen Image Formats > 2 of 3 formats are not supported by Chrome?

### ISSUE THREAD

**Issue by kavichouser** [GoogleChrome/lighthouse#5821]
Why does lighthouse request that I serve images in either WebP, JPEG 2000, or JPEG XR when Chrome only supports WepP? Why would you tell me to use an image format that the product I am currently using (your product!!!) does not support? This makes no logical sense whatsoever, not to mention the browser support for all three of these is TERRIBLE. Getting a 'slow' loading image is better than not getting one at all... 

https://developers.google.com/web/tools/lighthouse/audits/webp

**Comment by brendankenny** [comment]
Hi @kavichouser 

Yes, as mentioned in that help documentation, unfortunately images will have to be served differently depending on the browser if you want to take advantage of the newer formats.

That doc links to [How can I detect browser support for WebP?](https://developers.google.com/speed/webp/faq#how_can_i_detect_browser_support_for_webp), but you might also find [How do I serve WebP?](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization/#how-do-i-serve-webp) from @addyosmani's "Automating image optimization" article helpful for background on a number of ways to automate this process.
