### ISSUE TITLE
Text very hard to read in Google Dev Tools with dark theme

### ISSUE THREAD

**Issue by Aloso** [GoogleChrome/lighthouse#5822]
#### Provide the steps to reproduce
1. Open dev tools, click on the **··· menu** > **Settings** and select **Appearance** > **Theme** > **Dark**.
2. Perform an audit

#### What is the current behavior?
Some text is very hard to read (dark gray text on dark gray ground, light gray text on white ground)

#### What is the expected behavior?
All text is easily legible.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 3.0.0-beta.0
* Operating System: **Manjaro** with Linux 4.14.60-1 and KDE Plasma 5.13.4

**Comment by patrickhulce** [comment]
Thanks for reporting @Aloso! FWIW, a lot of the dark theme issues should be fixed in Chrome 69. If you try with a tip of tree Chromium or Chrome Canary, let us know if you're still finding issues!

**Comment by wardpeet** [comment]
These are screenshots taken from Canary:

audit panel:
![image](https://user-images.githubusercontent.com/1120926/44232457-64ef2180-a1a1-11e8-946e-7c583517f0de.png)

report:
![image](https://user-images.githubusercontent.com/1120926/44232564-bdbeba00-a1a1-11e8-8474-09f181e70caf.png)
![image](https://user-images.githubusercontent.com/1120926/44232575-c8794f00-a1a1-11e8-8464-b5bea0fbfd54.png)

looks all right to me, the red should maybe be a bit lighter but not bad.

i'm closing this, it will soon be available in chrome stable.
