### ISSUE TITLE
Download report button doesn't work

### ISSUE THREAD

**Issue by dodiku** [GoogleChrome/lighthouse#5823]
#### Provide the steps to reproduce
1. Run LH on http://www.drorayalon.com/ (using DevTools in Chrome)
2. Wait for the report to be shown
3. Click the 'download report' button

#### What is the current behavior?
Clicking the download report button makes the tab be frozen for a few seconds. Then, it closes the DevTools panel and clears the audit. A report is not being saved not downloaded.

#### What is the expected behavior?
A report should be saved.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version:
* Node.js version:
* Operating System: Mac OS X 10.13.6

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @dodiku! We believe this to have been fixed in latest Chrome. Could you try with Chrome Canary and let us know if you're still having issues?

**Comment by dodiku** [comment]
It works well on Canary.

btw -- it could have the capability to get the report in PDF format upfront (without using the viewer).

**Comment by patrickhulce** [comment]
Great! We'll go ahead and mark this as fixed then :)

Good question - we're tracking that work as part of #3564 so if you have more to add please feel free :)
