### ISSUE TITLE
MVC Startup loading js heap up to 34MB

### ISSUE THREAD

**Issue by lukawalid** [GoogleChrome/lighthouse#5825]
i have an problem in js-heap in my MVC site when i click on Performance it show me an JS-HEAP from 9MB to 31MB so what is the solution to optmize the startup of MVC site

**Comment by paulirish** [comment]
a 31MB js heap for a site isn't too huge.

**Comment by paulirish** [comment]
but here's some resources: https://developers.google.com/web/tools/chrome-devtools/memory-problems/

this is a better question for StackOverflow. Good luck.
