### ISSUE TITLE
feature-request: add reason to runtime error output

### ISSUE THREAD

**Issue by samfoot** [GoogleChrome/lighthouse#5838]
**Feature request summary**

When a `FAILED_DOCUMENT_REQUEST` error occurs the error message does not give the actual reason for this as it's not part of the stack trace for example:

`Runtime error encountered: Your page failed to load. Verify that the URL is valid and re-run Lighthouse.
LHError: FAILED_DOCUMENT_REQUEST
   at Function.getPageLoadError (/lighthouse/lighthouse-core/gather/gather-runner.js:168:21)
    at Function.afterPass (/lighthouse/lighthouse-core/gather/gather-runner.js:273:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

I am proposing to add the actual reason be displayed (if available) from the error, for example:

`Runtime error encountered: Your page failed to load. Verify that the URL is valid and re-run Lighthouse.
Reason: net::ERR_CERT_COMMON_NAME_INVALID
LHError: FAILED_DOCUMENT_REQUEST
    at Function.getPageLoadError (/lighthouse/lighthouse-core/gather/gather-runner.js:168:21)
    at Function.afterPass (/lighthouse/lighthouse-core/gather/gather-runner.js:273:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

I am willing to do the work to add this.

**What is the motivation or use case for changing this?**

Being able to determine what the actual error that caused the page to fail to load would better help me explain to my users why the audit failed.

**How is this beneficial to Ligthhouse?**

Better diagnostics for developers that use the CLI to programatically audit.

**Comment by samfoot** [comment]
necessarily-wide-alpaca

**Comment by paulirish** [comment]
@samfoot yeah this sounds great. Happy for you to take this.

**Comment by paulirish** [comment]
@patrickhulce do you remember why [we moved](https://github.com/GoogleChrome/lighthouse/pull/4280/files#diff-42278a7ee772120215ea8cfe1b0cb1b1R147-R167) the `errorReason` from the Error's message into a property?

@samfoot At the very least `showRuntimeError` in the CLI could also log `error.reason`. But I also think it's reasonable to change the message based on the errorReason. Let's see what patrick sez..

**Comment by brendankenny** [comment]
fixed in #6083, though the code currently doing this (using localization replacement) superseded that in #6457
