### ISSUE TITLE
LR vs CLI differences between Perf opps/diags

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#5839]
CLI: https://googlechrome.github.io/lighthouse/viewer/?gist=14953651fe14d886af18b9a8cc6729ab
LR: https://googlechrome.github.io/lighthouse/viewer/?gist=53d98df63e8483839b25a038c79a4132

Differences:

* LR has NO opportunities. none. 
* LR has no results for uses-long-cache-ttl
* FYI some diagnostics titles changed (bootup time, etc)

**Comment by paulirish** [comment]
artifacts from [this LR run](https://googlechrome.github.io/lighthouse/viewer/?gist=327f7d12dcee4cbb58e05c86e46de976): ➡️  [cnn_no_opportunities.zip](https://github.com/GoogleChrome/lighthouse/files/2291735/cnnnoopportunities.zip)


there is one opportunity, but none of the byte efficiency ones ever show up.

**Comment by patrickhulce** [comment]
From my investigation it seems like the byte efficiency opps are all missing because the `transferSize` of all network records is `0`. Inspecting the devtoolslog shows that the `encodedDataLength` for all messages is 0. Interestingly the `dataLength` is properly set making `resourceSize` accurate.

**Comment by paulirish** [comment]
@patrickhulce can you look into this while i'm out?

corp ticket: https://b.corp.google.com/issues/71833893#comment4

my initial patch:

```diff
diff --git a/lighthouse-core/lib/network-request.js b/lighthouse-core/lib/network-request.js
index fd5f2e9c..f435c419 100644
--- a/lighthouse-core/lib/network-request.js
+++ b/lighthouse-core/lib/network-request.js
@@ -227,6 +227,20 @@ module.exports = class NetworkRequest {
     this.responseReceivedTime = timestamp;
 
     this.transferSize = response.encodedDataLength;
+
+    // Hack for Lightrider's lack of content-length
+    if (
+      this.transferSize === 0 &&
+      response.headers['X-Original-Content-Length'] &&
+      response.headersText
+    ) {
+      const contentLengthBytes =
+        parseFloat(response.headers['X-Original-Content-Length']) + response.headersText.length;
+      this.transferSize = contentLengthBytes;
+      // Copy over content encoding, too.
+      response.headers['Content-Encoding'] = response.headers['X-Original-Content-Encoding'];
+    }
+
     if (typeof response.fromDiskCache === 'boolean') this.fromDiskCache = response.fromDiskCache;
 
     this.statusCode = response.status;
```

**Comment by patrickhulce** [comment]
👍will do boss man 🕴
