### ISSUE TITLE
Lighthouse is penalizing my page for an iframe nowhere to be found

### ISSUE THREAD

**Issue by Stefany93** [GoogleChrome/lighthouse#5868]
See attached below. It could be an AMP issue, idk, but I can't find that iframe when I go to view source. The page is AMP. Thanks. 

![image](https://user-images.githubusercontent.com/2403939/44349647-196b9a80-a463-11e8-8a8c-a58792ee812d.png)

**Comment by Stefany93** [comment]
Same with some image nowhere to be found:

![image](https://user-images.githubusercontent.com/2403939/44350389-db6f7600-a464-11e8-8c24-4116c9dcb079.png)

**Comment by patrickhulce** [comment]
Thanks for reporting @Stefany93 do you have a public URL for us to take a look?

**Comment by brendankenny** [comment]
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen.
