### ISSUE TITLE
Lighthouse is not capturing the data for multiple screens

### ISSUE THREAD

**Issue by JayashreeNagure** [GoogleChrome/lighthouse#5869]
#### Provide the steps to reproduce
1. Run LH on <affected url>

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
@JayashreeNagure please fully fill out the bug report template for us to be able to help!

**Comment by JayashreeNagure** [comment]
Basically i need the recommendations for each screen , how do i do it using lighthouse

**Comment by patrickhulce** [comment]
I think you're requesting functionality similar to https://github.com/GoogleChrome/lighthouse/issues/5187, is that right? 

We can discuss there, but tl;dr LH doesn't support user flows right now, you'll have to load each "screen" individually via a unique URL.

**Comment by JayashreeNagure** [comment]
since my url has the token key in it and i can not use for different screen and i get timeout errors when i do that. Also on what lighthouse version we can see the user flows

**Comment by rageshpayyan** [comment]
@JayashreeNagure , I want to use the same scenario, you found any solution.

**Comment by JayashreeNagure** [comment]
I have not found any solution yet

Sent from my iPhone

> On 15-Sep-2018, at 3:19 AM, rageshpayyan <notifications@github.com> wrote:
> 
> @JayashreeNagure , I want to use the same scenario, you found any solution.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
DISCLAIMER: This email message along with any attachments may contain 
information that is confidential or privileged. If you are not the intended 
recipient or responsible for delivering any of this transmission to an 
intended recipient, you are hereby notified that any dissemination, 
distribution, retention, copying or other use of this message or its 
attachments is prohibited. If you received this message in error, please 
notify the sender immediately and permanently delete all copies of this 
message and attachments. No representation is made that this email is free 
of viruses. Virus scanning is recommended and is the responsibility of the 
recipient. Thank you.
