### ISSUE TITLE
manifest start_url should be resolved relative to *manifest* url

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#587]
https://w3c.github.io/manifest/#start_url-member (step 4)

Currently we parse relative to the [page url](https://github.com/GoogleChrome/lighthouse/blob/88ad999bfcba06ad246972ec2a144a72d26f6ea5/lighthouse-core/audits/cache-start-url.js#L61), which will mislead if e.g. the manifest is in another directory (@ebidel just ran into this with PWAifying chromestatus).

Should probably happen in the manifest parser, where there happens to be some TODOs on this :)

One interesting thing: *all* urls are supposed to be resolved relative to the manifest location, including e.g. icon URLs. Unlike `start_url`, Chrome appears to accept icon `src`es relative to the manifest *or* the page itself. Unclear why it does that.

**Comment by paulirish** [comment]
`new URL(manifestStartURL, manifestURL)` works and is what the spec asks for. 

The spec then says if that URL fails then just use the document URL instead. :)
![image](https://cloud.githubusercontent.com/assets/39191/17728056/07a91d92-6412-11e6-907c-dd2d18a0404c.png)
