### ISSUE TITLE
convert page-functions to be exported as strings

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#5870]
**Summary**

In https://github.com/GoogleChrome/lighthouse/pull/5857#discussion_r211050626 @paulirish mentioned he liked the idea of page-functions exported as strings instead of functions that are `.toString`'d

**Comment by danushan1246** [comment]
https://github.com/GoogleChrome/lighthouse/pull/5902

**Comment by Abdulmanahtalib** [comment]
Support

**Comment by patrickhulce** [comment]
Fixed by #5902
