### ISSUE TITLE
Add top-level `error` property on LHR

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#5881]
To communicate if there were any errors during the run. We have to decide which errors should be considered for this. At the very least, a boolean that captures if there were any auditErrors.  

See PSI's error enum: https://goto.google.com/zhian

Property name is available for bikeshedding. ;)  `errorState`?

any takers?

**Comment by brendankenny** [comment]
What kind of error state is it trying to communicate?

- Numbers may not be trustworthy
- Something weird happened, you should try rerunning
- Something happened that rerunning won't fix, re-check how you've configured lighthouse

?

**Comment by paulirish** [comment]
as mentioned in the thread. i think we have 3 classes of errors.

1. the page couldnt be loaded correctly (bad TLS, 500 status, etc).  aka `getPageLoadError` returned truthy.
2. page was loaded but we couldn't collect necessary diagnostics (NO_TRACING_STARTED, NO_NAVSTART).
   * see [screenshot](https://screenshot.googleplex.com/LpKpCsxmdCP). If we're gonna mark ALL perf stuff as 'Error' then we should consider it an audit failure. The two above error codes definitely end up in this state. there may be more.
3. Individual audits had errors
   * some, but not _all_

Looks like we're about to have agreement the 1 single audit error shouldn't tank the run (and so we shouldnt report a toplevel failure). But classes 1 and 2 should both tank the run.

Relatedly, we need a `catch` in `runLighthouseForLR()` so we dont get unhandled rejections. And I guess we'll have to return something in this errorState to LR?

@brendankenny can you put together a PR for this while I'm out?

**Comment by paulirish** [comment]
Fixed. Some small followups done in #6071
