### ISSUE TITLE
eliminate config.loadPage

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#589]
one question that came up while writing #588 was the utility of `loadPage: true/false` in the config.

If a gatherer cares about what's in a page, obviously at least one pass loading that page will have to have already happened, and if the next pass is `loadPage: false`, the state of the page doesn't change, so the gatherer could just as easily put everything it needs in either `pass()` (if it needs to be traced) or `afterPass()` (if it doesn't) of the previous pass.

Any reason to keep `loadPage` around?

**Comment by paullewis** [comment]
If we remove it, are we saying that we will reload the page for every pass? 

The only reason I am hesitant is that we don't guarantee ordering within each pass (besides the beforePass, pass, afterPass functions). The passes are essentially that ordering, and if someone wants to know that a gatherer has run after some others (for whatever reason) but that the page _hasn't_ reloaded, the only way I can think to make sure that happens is to have separate passes, and allow them to set `loadPage` to `false`. For us, with our current set of gatherers, this is something we can probably orchestrate around (or is a non-issue), but with extensibility in mind we might cause issues.

So the net result is we probably don't need it, not in the short or even medium term, but with one eye on the future I'm hesitant to drop it unless it's causing huge amounts of complexity or overhead, which I don't think it currently is.

**Comment by brendankenny** [comment]
> if someone wants to know that a gatherer has run after some others (for whatever reason) but that the page *hasn't* reloaded, the only way I can think to make sure that happens is to have separate passes, and allow them to set `loadPage` to `false`.

As with the cases in the original comment, I believe this will fit into our [the execution order laid out in #588](https://github.com/GoogleChrome/lighthouse/pull/588#issue-170766802) without a flag. If for some reason a gatherer *has* to run after a set of other gatherers but without a page load in between, it can be run in `beforePass` of the following pass. Meanwhile eliminating `loadPage` cuts down on ways a gatherer can go wrong, since there are fewer combinations of state to track when writing your own gatherer since `beforePass`,` pass`, and `afterPass` would always act the same way wrt page loading.

> The only reason I am hesitant is that we don't guarantee ordering within each pass

Now that you mention that, I think we *should* guarantee ordering as specified in the config. There's no burden placed on lighthouse to enforce it (we already do it) and it would allow easier reasoning about even implicit dependencies between gatherers by folks writing config files.
