### ISSUE TITLE
Extra overhead caused by extensions

### ISSUE THREAD

**Issue by ishan123456789** [GoogleChrome/lighthouse#5891]
#### Provide the steps to reproduce
1. Run LH on Any website

#### What is the current behavior?
I'm running the audit on a blank project of node returning hello world. This is what the report says.

![issue_git](https://user-images.githubusercontent.com/23247168/44454477-4b266200-a619-11e8-8016-5bbfe6bb4567.PNG)

#### What is the expected behavior?
External extensions should not be affecting my web app's performance. I want to audit my app and not the environment. _A blank project is performing badly_ 

#### Environment Information
* Chrome version: 68.0.3440.106 (Official Build) (64-bit) (cohort: Stable)
* Node.js version: 8.9.4
* Operating System: Windows

_Update:_
**I am able to get expected behavior in incognito window**

**Comment by patrickhulce** [comment]
@justinribeiro is spot on. We consider this addressed by #5666. The reality is that if you're running your page with extensions interfering the performance is inseparable. Bloated extensions === bloated experience. The automatically disabling extensions solution frequently ends up losing user data (apparently extension authors don't expect to be switched off/on, go figure 😄) which wasn't an acceptable trade-off.
