### ISSUE TITLE
Failure on Gist creation

### ISSUE THREAD

**Issue by altayhunter** [GoogleChrome/lighthouse#5894]
#### Provide the steps to reproduce
1. Run LH on any URL and download the generated report.
2. Go to: https://googlechrome.github.io/lighthouse/viewer2x/
3. Upload the report, then choose "Save as Gist".

#### What is the current behavior?
A banner will appear saying "Failed to fetch" and the following errors will show up in the console:
```
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
Failed to load https://api.github.com/gists: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://googlechrome.github.io' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

#### What is the expected behavior?
A gist should be created.

#### Environment Information
* Lighthouse version: 2.9.1

**Comment by wardpeet** [comment]
I've been able to add a gist for lh 2.9.1
https://googlechrome.github.io/lighthouse/viewer2x/?gist=49bcc8bbe385fb7d3a9dac00bd401814
