### ISSUE TITLE
Drop transpilation for chrome extension

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#59]
We may want to get rid of the transpilation to make dev a bit more sane.

I'm curious about using https://github.com/JamesMGreene/breq (require() polyfill via sync xhr).

Thoughts?

-------

(Unrelatedly, doing the work in the background page will be easier to debug than doing it in popup.html).

**Comment by paullewis** [comment]
Yeah, I think the only thing we need transpilation for is the require step, so I'd be game for us switching it out.

**Comment by paulirish** [comment]
imagine the headlines when they realize that the performance advocates rely on synchronous network calls. :tongue:

**Comment by samccone** [comment]
I think it might looks something like this

![image](https://cloud.githubusercontent.com/assets/883126/13991825/ccf169e2-f0d6-11e5-9e62-0261bc554bbb.png)
