### ISSUE TITLE
move config validation/error catching to core/config/index.js

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#591]
Looking at #590, it seems like we should move most config validation to an earlier stage (like `core/config/index.js`), when the config is first loaded. Doing it there should make it easier to surface meaningful errors instead of e.g. deep in the score aggregator (as in that PR), and it means more errors will be caught _before_ running the whole pipeline only to bug out at the end.

**Comment by patrickhulce** [comment]
done
