### ISSUE TITLE
Mark SEO audits as "Not Applicable" whenever appropriate

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#5913]
See https://github.com/GoogleChrome/lighthouse/issues/3177#issuecomment-406344590

For example, for the hreflang audit, it should be not applicable if the page has no hreflang attribute. Similarly, other SEO audits should be deprioritized if they do not apply to the given page.

**Comment by brendankenny** [comment]
a number of SEO audits are now marked `notApplicable` when appropriate (`canonical`, `font-size`, `robots-txt`, `tap-targets`, etc). 🎉 🎉
