### ISSUE TITLE
Select and copy should be possible.

### ISSUE THREAD

**Issue by 1der1** [GoogleChrome/lighthouse#5918]
**Feature request summary**

I would love to have select and copy of text.

**What is the motivation or use case for changing this?**
The motivation of using Lighthouse is to optimize code.
If you could copy the "Failing Elements" description, you could search it in the code base.

**How is this beneficial to Ligthhouse?**
It should be as easy as possible to optimize apps.
BTW: A better integration into the debugger would be very helpful as well. Click to show a failing element in the elements section of the debugger for example.

**Comment by patrickhulce** [comment]
Thanks for filing @1der1! These seem to be duplicates of #4880 and #2289 :) 

Closing for now since you can add your thoughts to those issues, but if you think this is substantially different than those, comment back here and reopen
