### ISSUE TITLE
Migrate to Storage.clearDataForOrigin for clearing storage & SW

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#592]
Do we want to [clear storage](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Storage/) before we gather against a URL for the first time? Feels destructive (esp for the extension!), but we already clear SWs and force them to reinstall, and I'm figuring we could get skewed data if stuff already exists in LS, IDB, Caches etc.

Perhaps a config option to clear data before run? wdyt?

**Comment by paulirish** [comment]
>  but we already clear SWs and force them to reinstall

We don't currently clear SW's (but will when #598 lands). 

But yeah I'm in favor of wiping the origin.

Good spot on [`Storage. clearDataForOrigin`](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Storage/#method-clearDataForOrigin).. Didn't know it was so straightforward.  :)

**Comment by paulirish** [comment]
First, cross-ref of the findings in https://github.com/GoogleChrome/lighthouse/pull/598#issuecomment-240333046

We can kill our SW forceUpdateOnLoad and browser cache clearing and replace with clearDataForOrigin()

A call looks like this:

```js
 {"id":80,"method":"Storage.clearDataForOrigin","params":{"origin":"https://pwa.rocks","storageTypes":"appcache,cache_storage,cookies,indexeddb,local_storage,service_workers,websql"}}
```
