### ISSUE TITLE
PWA refactor/report refresh.

### ISSUE THREAD

**Issue by kusler** [GoogleChrome/lighthouse#5930]
**Feature request summary**

Want the PWA portion of the LH report to be refreshed to reflect that a PWA 'score' doesn't make sense (it should be badging - reflecting a more binary mechanism for evaluation).

No. I won't work on it myself. (AKA you don't want me working on this by myself)

**What is the motivation or use case for changing this?**
Allows for increased clarity on installability, and have easier paths toward exemplary PWAs.

**How is this beneficial to Lighthouse?**
Because.

**Comment by brendankenny** [comment]
Whoops, missed this. Closing in favor of #6395
