### ISSUE TITLE
Wrong best practices warning about manifest short_name when testing non-pwa websites

### ISSUE THREAD

**Issue by baharev** [GoogleChrome/lighthouse#5937]
I am checking ordinary static websites, **NOT** progressive web apps (not pwa), the Progressive Web App is NOT selected when I start the audit, but when the audit finishes I still get:

> Manifest's `short_name` will be truncated when displayed on homescreen

under the Best Practices. It does not matter whether I select desktop or mobile device; I still get this wrong warning. The warning does not make any sense to me: There is not any `short_name` since there is not any web app manifest, so the `short_name` cannot possible be truncated because there is not any.

In my opinion, the only case when this message could make sense is when I audit Progressive Web Apps.

**Comment by justinribeiro** [comment]
Hi thanks for the issue! One thing to keep in mind is that the Web App Manifest, while used in conjunction as part of building a PWA, can also be used on static sites as well to help offer a better mobile experience regardless of the additional technologies that make up a PWA. See https://medium.com/dev-channel/how-to-add-a-web-app-manifest-and-mobile-proof-your-site-450e6e485638 as an example of the progressive nature of the API, regardless of say a service worker.

Consider a mobile user manually adding your static site via the "Add to Homescreen" menu option; you can control that experience with just the a web app manifest and give them a better experience.

Taking into account this non-PWA case, the best practice is check is correct (though possibly some verbiage around why it's there would help better clarify the use case).

**Comment by baharev** [comment]
@justinribeiro Thanks for the prompt reply. Here is how I understand what you are saying.

Apparently even non-PWA static websites are supposed to have a web app manifest(?). In that case, under the Best Practices, I would like to see an error message saying that there isn't any web app manifest (although I made it very clear before the audit that the site is not a PWA, and I am testing for desktop devices and not mobiles). Complaining about a too long `short_url` is utterly confusing in my opinion. 

And why do we have the option NOT to select Progressive Web App if, apparently, now everything is supposed to behave like a PWA? Even if I am testing a non-PWA site for desktop devices?

Sorry, I don't agree with this best practice warning.

**Comment by justinribeiro** [comment]
> Apparently even non-PWA static websites are supposed to have a web app manifest(?).

It's a best practice audit; it's not saying you _have to_ have these things, it's just saying this offers a better experience to the end user using your site.

> And why do we have the option NOT to select Progressive Web App if, apparently, now everything is supposed to behave like a PWA? Even if I am testing a non-PWA site for desktop devices?

No one is specifically saying that your site should behave one way or the other. You can think of the Web App Manifest best practice as part of the progressive enhancement story when building for the web. For desktop devices, that story is still being worked out (one example: the notion of "Create Shortcut..." on Windows for non-PWA sites and what that means to a desktop user experience).

I agree that additional clarity around the language for that check when in running against desktop and evaluating the desktop usage of manifest going forward could stand to reason.

**Comment by baharev** [comment]
In my opinion, it is wrong to complain about the `short_url` (or about anything related to the web app manifest) when a **non**-PWA is tested. It doesn't matter whether mobile or desktop; if I say it is not a PWA then I really don't want to see any red errors in the report regarding the wep app manifest.

> No one is specifically saying that your site should behave one way or the other. 

Well, you sort of are telling me. I get a red error in the audit, and my scores dropped to 94. The client can also audit his/her website with lighthouse, and then sees that ugly red error in the report and the score being knocked down. If it is a non-technical client, I will have a hard time explaining it. And why do I have to? It was not supposed to be a PWA in the first place...

**Comment by brendankenny** [comment]
Good news, this was fixed in #4860, which shipped with Lighthouse 3.0 :) If you're running Lighthouse in DevTools, you shouldn't see this happen in current stable Chrome (m69).

**Comment by baharev** [comment]
@brendankenny Awesome, thank you!
