### ISSUE TITLE
"Content size" warning when devtools docked to left or right

### ISSUE THREAD

**Issue by jessehattabaugh** [GoogleChrome/lighthouse#5944]
## steps to reproduce
1. set dev tools to split the browser window horizontally instead of vertically
2. Run LH on any website

## current behavior?
I get a "content width" warning saying that my `window.innerWidth !== window.outerWidth`.
![lighthouse error](https://user-images.githubusercontent.com/17991/44963288-0edae780-aede-11e8-9f12-e58e0601463f.PNG)

## expected behavior?
When running the audit with the devtools docked to the bottom of the screen as is the default, instead of splitting the window to the left or right, there is no warning.  Lighthouse should give consistent results no matter how the user's devtools are configured. 

##Environment Information
* Affected Channels: DevTools
* Lighthouse version: 3.0.0
* Operating System: Windows

**Comment by justinribeiro** [comment]
Thanks for the issue! This sounds similar to issue #5558 which has a fix inbound with PR #5893.

**Comment by brendankenny** [comment]
Yes, let's dedupe into #5558
