### ISSUE TITLE
screenshot-thumbnails perf: cache more aggressively

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#5957]
this audit is one of our more expensive.

It's very likely we're doing repeated work. Often traces have very few screenshots in the first half of the trace, and lots in the second half. This audit wants 10 evenly spaced screenshots out of the trace, which means it can pick the same screenshot twice.  
 
e.g. a 10s long trace. it has screenshots at 1s, 2s, 5s, 6s, 6.5s, etc..  10s. The for loop in will result in a repeated `frameForTimeStamp` when `i` == 3 and 4.  

https://github.com/GoogleChrome/lighthouse/blob/e07a94bdd58c3da142dbaf5add15c32142072116/lighthouse-core/audits/screenshot-thumbnails.js#L118-L124

Interestingly we have a cache for jpeg encoding, but we have two other operations that are potentially costly and should be cached too. `getParsedImage` and `scaleImageToThumbnail`.  Basically we should use the `frameForTimestamp` as our cache key (and the keep the encoded base64 data as the cache value).

**Comment by midzer** [comment]
Hi,

I don't think we need extra cache for the other temporary data.
In the end we want to deliver our `base64Data` and can check early via already existing `cachedThumbnails` map whether to do expensive `getParsedImage()` and `scaleImageToThumbnail(imageData)` call:
```
let base64Data;
if (cachedThumbnails.has(frameForTimestamp)) {
  base64Data = cachedThumbnails.get(frameForTimestamp)
} else {
  const imageData = frameForTimestamp.getParsedImage();
  const thumbnailImageData = ScreenshotThumbnails.scaleImageToThumbnail(imageData);
  base64Data = jpeg.encode(thumbnailImageData, 90).data.toString('base64');
  cachedThumbnails.set(frameForTimestamp, base64Data);
}
thumbnails.push({
  timing: Math.round(targetTimestamp - speedline.beginning),
  timestamp: targetTimestamp * 1000,
  data: base64Data,
});
```
Can open up a PR to discuss things further, if this could be the way to go.

**Comment by paulirish** [comment]
@midzer yup!!!! this is exactly what i was trying to say (unsuccessfully)

perfect. let's do it. :)

**Comment by midzer** [comment]
I understood the issue with your information. So everything fine :)
