### ISSUE TITLE
report:  ✅ audits should be in Passed Audits

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#5959]
Can't really explain why the dom-size audit isn't in passed: 

![image](https://user-images.githubusercontent.com/39191/45064284-ce0eda00-b067-11e8-8ac5-c379b583cb0f.png)

i mean i can because i originally wanted it to work this way:

https://github.com/GoogleChrome/lighthouse/blob/e07a94bdd58c3da142dbaf5add15c32142072116/lighthouse-core/report/html/renderer/util.js#L145-L148

but its annoying and just leads to confusion.

 we should just use `RATINGS.PASS.minScore` instead.

**Comment by brendankenny** [comment]
Are we covering up the underlying bug? The 0ms results should always pass `Number(audit.score) === 1`, so it seems like something else is going on with LR.

(the other side of this, hiding passed audits under "Passed Audits" seems fine, though)

**Comment by paulirish** [comment]
@brendankenny afaik, that is a separate bug: https://github.com/GoogleChrome/lighthouse/issues/5956

**Comment by midzer** [comment]
@paulirish yes, I just opened PR https://github.com/GoogleChrome/lighthouse/pull/5983 for this one
