### ISSUE TITLE
Improve the lackluster CLI output

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#596]
The article at https://www.smashingmagazine.com/2016/08/a-beginners-guide-to-progressive-web-apps/ recommended trying out lighthouse but also mostly pointed to our CLI output, which is basically garbage, next to the HTML output.

IMO we should either invest in the CLI output or simplify it considerably and call out the HTML results very clearly.

Thoughts?

**Comment by samccone** [comment]
@paulirish i hear you like making things very fancy

**Comment by paulirish** [comment]
brendan and i walked through our current "pretty" CLI report and found a lot of things to clean up. Things like "found icons of size..." are reported as a debugString (which they aren't..) And a fair amount of detail in accessibility we don't need to expose. Also all the shrug results shouldn't be included at all. 

UI-wise it looks like it's free (dependency-wise) for us to use `cliui` and `colors`/`chalk`. 

![image](https://cloud.githubusercontent.com/assets/39191/17723256/8e7adcea-63ed-11e6-8682-814f4266f5d6.png)

**Comment by wardpeet** [comment]
Sounds good, would be handy for ci output as well.
Could help with outputting but you probably have it figured out already how you want it :D

**Comment by addyosmani** [comment]
I would be happy to help with this over the next week or two borrowing a few ideas from my last few CLI projects, but also totes :sunglasses: if @paulirish or someone else wants to knock this out.

**Comment by paulirish** [comment]
Addy, would love your experience on this! Yeahhh

**Comment by addyosmani** [comment]
:heart: baller. I'll prototype a few ideas for the output soonish.

**Comment by paulirish** [comment]
@addyosmani i got some early work up in #682, but this is still all yours if you wanna do more.

**Comment by paulirish** [comment]
Reopening for fun:

More work that'd make sense:

* Perf metrics could be reported a bit more visually like [pwmetrics](https://github.com/paulirish/pwmetrics/)
* Reduce formatters for accessibility and EIL
* Call out the HTML report more clearly.

**Comment by paulirish** [comment]
mostly done here.
