### ISSUE TITLE
Report: "e.computedStyleMap is not a function" error when viewing in Safari

### ISSUE THREAD

**Issue by mettamatt** [GoogleChrome/lighthouse#5966]
Using lighthouseVersion 3.0.3, when uploading or using gist to send a JSON file to the Lighthouse Report Viewer I receive the following errors in the console log of the browser:

```
[Error] Error: Error rendering report: e.computedStyleMap is not a function. (In 'e.computedStyleMap()', 'e.computedStyleMap' is undefined)
	(anonymous function) (viewer.js:16:169301) Line 770

[Error] Error: e.computedStyleMap is not a function. (In 'e.computedStyleMap()', 'e.computedStyleMap' is undefined)
	(anonymous function) (viewer.js:16:169301) Line 770
```

I've verified that the JSON file is valid JSON syntax, so I'm not sure what's happening. 

I'm using lighthouse from the command line on Ubuntu.

**Comment by mettamatt** [comment]
Closing this ticket. My problem was using the Lighthouse Viewer in Safari rather than Chrome. It seems so obvious after typing out this sentence...

**Comment by brendankenny** [comment]
Lighthouse uses Chrome to generate the results, but it seems perfectly reasonable to be able to view the report in Safari :)

Offending line is
https://github.com/GoogleChrome/lighthouse/blob/d3af6d0bbc6ae008431f26d001050834162c1f3f/lighthouse-core/report/html/renderer/report-ui-features.js#L134-L135

(we even have a TODO) and another a few lines below that, if anyone wants to take a look.
