### ISSUE TITLE
Hanging trace retrieval on LR

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#5968]
We have evidence that the loop of `_readTraceFromStream()` is stalling out and hanging indefinitely. 

1. we might want to add some timeouts
2. we could experiment with [not using a stream](https://github.com/GoogleChrome/lighthouse/blame/0e8982ab037d928a37d8dddd00aa7f1e913f5414/helpers/browser/driver.js) (in the LR case)
3. trace reduction #3596 will help but probably not fix

**Comment by wardpeet** [comment]
When looking at parse time we could go try out https://github.com/mafintosh/turbo-json-parse to see if it helps.
