### ISSUE TITLE
Remove audit whitelist?

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#597]
At this point I'm thinking the custom config is much preferred over specifying an audit whitelist on the cmd line. 

The ergonomics are roughly the same for the user. But I think we could reduce some code complexity by removing some of the pass/gather filtering that we do for the whitelist.  

What do yall think

**Comment by paulirish** [comment]
Brendan raised the point that as a user using custom config.. it's nice to not have to sort out which gatherers are required.  And yeah, I don't want to force that mapping onto them.

So in that case, we wouldn't get to remove too much.  :/

Closing..

**Comment by paullewis** [comment]
We filter unneeded gatherers anyway through requiredArtifacts, so they could leave the gatherer list alone and we would trim it for them.
