### ISSUE TITLE
Chrome 69 does not compute First CPU Idle or Time To Interactive when using devtools throttling via CLI

### ISSUE THREAD

**Issue by tollmanz** [GoogleChrome/lighthouse#5970]
#### Provide the steps to reproduce
1. Install Chrome 69
1. Install Lighthouse CLI 3.0.3
1. Run `lighthouse https://github.com --throttling-method=devtools --view`

#### What is the current behavior?

First CPU Idle, Time To Interactive, and Estimated Input Latency all show errors with the description of `Audit error: Could not find any top level events`

![screencapture-file-users-tollmanz-github-com_2018-09-05_15-25-19-report-html-2018-09-05-15_29_06](https://user-images.githubusercontent.com/921795/45119242-78e2cf00-b120-11e8-8038-5869f5d66d57.png)

#### What is the expected behavior?

First CPU Idle, Time To Interactive, and Estimated Input Latency should produce numeric results. Note that the Lantern throttling produces the desired results. Furthermore, devtools throttling from within Chrome DevTools works as expected. I've reproduced this bug on OS X and CentOS 7.4.x.

#### Environment Information
* Affected Channels: CLI, node
* Lighthouse version: 3.0.3
* Node.js version: 8.11.4
* Operating System: OS X 10.13.6, CentOS 7.4.x

**Comment by wildlyinaccurate** [comment]
I was seeing this on 3.0.3 as well, but it appears to be resolved in 3.1.0.

**Comment by brendankenny** [comment]
Yes, it was #5832. Sorry for the delay in getting a release out!

**Comment by tollmanz** [comment]
I confirm that 3.1.1 fixes the issue for me both on CentOS and OS X using the CLI and node module. Thanks for being on top of this @brendankenny!
