### ISSUE TITLE
Extension Error: Protocol error (Runtime.evaluate): Promise was collected

### ISSUE THREAD

**Issue by samu101108** [GoogleChrome/lighthouse#5973]
**Lighthouse Version**: 3.0.3
**Lighthouse Commit**: d1cae24fda4182406e02d3f4df6309d48878fc50
**Chrome Version**: 69.0.3497.81
**Initial URL**: https://cipher.ml/
**Error Message**: Protocol error (Runtime.evaluate): Promise was collected
**Stack Trace**:
```
Error: Protocol error (Runtime.evaluate): Promise was collected
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17443:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by paulirish** [comment]
thx for reporting. :)

**Comment by brendankenny** [comment]
This error is reported relatively often. We should investigate. It's not entirely clear [from the source of the message](https://cs.chromium.org/chromium/src/v8/src/inspector/injected-script.cc?type=cs&q=%22Promise+was+collected%22&sq=package:chromium&g=0&l=247) what this is trying to communicate :)

**Comment by patrickhulce** [comment]
From several of the duplicates it seems like this happens when JavaScript is disabled (I'm assuming globally). I'll try to repro.

**Comment by patrickhulce** [comment]
Can confirm that this happens on any page when JavaScript has been disabled from `chrome://settings`!

Not sure there's anything we can do about that other than test before we run and inform the user to re-enable JavaScript in order to audit?

**Comment by PrinsFrank** [comment]
Seems fair, enabling on a per-page basis lets you use lighthouse without enabling javascript globally. A clear warning that javascript needs to be enabled for the current page to use lighthouse would be nice.
