### ISSUE TITLE
SyntaxError: Unexpected token function at Object.

### ISSUE THREAD

**Issue by triptisbinnovations** [GoogleChrome/lighthouse#5987]
I am using lighthouse 3.0.3 version. My node version is 6.14.3.  I am using Centos.

I have installed the lighthouse on my server by npm install -g lighthouse command.  But when I run lighthouse https://airhorner.com/, I am getting a below-mentioned error: 

/usr/local/share/.config/yarn/global/node_modules/lighthouse/lighthouse-core/index.js:38
async function lighthouse(url, flags = {}, configJSON, connection) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/lighthouse/lighthouse-cli/commands/list-audits.js:8:20)

Please check the link for the screenshot http://prntscr.com/krlh8d.

**Comment by paulirish** [comment]
node 8 or higher is required.

**Comment by triptisbinnovations** [comment]
I have updated the node version and after running the lighthouse https://airhorner.com command, i am receiving the below-mentioned error:

[root@server217-174-249-28 ~]# lighthouse https://dev.punterescort.com
which: no google-chrome-stable in (/root/local/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/local/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
which: no google-chrome in (/root/local/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/local/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
which: no chromium in (/root/local/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/local/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +517ms
  ChromeLauncher Waiting for browser....... +503ms
  ChromeLauncher Waiting for browser......... +501ms
  ChromeLauncher Waiting for browser........... +502ms
  ChromeLauncher Waiting for browser............. +501ms
  ChromeLauncher Waiting for browser............... +501ms
  ChromeLauncher Waiting for browser................. +501ms
  ChromeLauncher Waiting for browser................... +502ms
  ChromeLauncher Waiting for browser..................... +501ms
  ChromeLauncher Waiting for browser....................... +502ms
  ChromeLauncher Waiting for browser......................... +501ms
  ChromeLauncher Waiting for browser........................... +502ms
  ChromeLauncher Waiting for browser............................. +501ms
  ChromeLauncher Waiting for browser............................... +502ms
  ChromeLauncher Waiting for browser................................. +501ms
  ChromeLauncher Waiting for browser................................... +501ms
  ChromeLauncher Waiting for browser..................................... +502ms
  ChromeLauncher Waiting for browser....................................... +501ms
  ChromeLauncher Waiting for browser......................................... +502ms
  ChromeLauncher Waiting for browser........................................... +501ms
  ChromeLauncher Waiting for browser............................................. +502ms
  ChromeLauncher Waiting for browser............................................... +501ms
  ChromeLauncher Waiting for browser................................................. +502ms
  ChromeLauncher Waiting for browser................................................... +501ms
  ChromeLauncher Waiting for browser..................................................... +502ms
  ChromeLauncher Waiting for browser....................................................... +501ms
  ChromeLauncher Waiting for browser......................................................... +502ms
  ChromeLauncher Waiting for browser........................................................... +501ms
  ChromeLauncher Waiting for browser............................................................. +502ms
  ChromeLauncher Waiting for browser............................................................... +501ms
  ChromeLauncher Waiting for browser................................................................. +502ms
  ChromeLauncher Waiting for browser................................................................... +501ms
  ChromeLauncher Waiting for browser..................................................................... +502ms
  ChromeLauncher Waiting for browser....................................................................... +508ms
  ChromeLauncher Waiting for browser......................................................................... +503ms
  ChromeLauncher Waiting for browser........................................................................... +501ms
  ChromeLauncher Waiting for browser............................................................................. +502ms
  ChromeLauncher Waiting for browser............................................................................... +501ms
  ChromeLauncher Waiting for browser................................................................................. +502ms
  ChromeLauncher Waiting for browser................................................................................... +501ms
  ChromeLauncher Waiting for browser..................................................................................... +502ms
  ChromeLauncher Waiting for browser....................................................................................... +501ms
  ChromeLauncher Waiting for browser......................................................................................... +502ms
  ChromeLauncher Waiting for browser........................................................................................... +501ms
  ChromeLauncher Waiting for browser............................................................................................. +502ms
  ChromeLauncher Waiting for browser............................................................................................... +501ms
  ChromeLauncher Waiting for browser................................................................................................. +502ms
  ChromeLauncher Waiting for browser................................................................................................... +502ms
  ChromeLauncher Waiting for browser..................................................................................................... +501ms
  ChromeLauncher Waiting for browser....................................................................................................... +501ms
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:38195 +2ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.cqUu51U/chrome-err.log +0ms
  ChromeLauncher:error [31251:31251:0907/103027.409289:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
  ChromeLauncher:error  +0ms

**Comment by triptisbinnovations** [comment]
I am using dzava/lighthouse-php API.  I am unable to audit results, there is a lighthouse audit error. 

Fatal error: Uncaught Dzava\Lighthouse\Exceptions\AuditFailedException: Audit of 'http://www.google.com' failed in /root/vendor/dzava/lighthouse/src/Lighthouse.php:41 Stack trace: #0 

Can you please suggest what is the issue with lighthouse library.

**Comment by paulirish** [comment]
towards the end of that output is the error that i think is breaking things.\

> [31251:31251:0907/103027.409289:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

try this:

```sh
lighthouse https://dev.punterescort.com --chrome-flags="--no-sandbox" 
```
