### ISSUE TITLE
Score Scale vs color-coded

### ISSUE THREAD

**Issue by piengeng** [GoogleChrome/lighthouse#5989]
#### Provide the steps to reproduce
1. Run LH on cv.piengeng.com

#### What is the current behavior?
Accessibility and SEO both scored 89, but given Orange, color scale is wrong?
#### What is the expected behavior?
color coded should be Green instead of Orange? 
https://developers.google.com/web/tools/lighthouse/v3/scoring 
says 75 to 100 (good): Green

#### Environment Information
* Affected Channels:  n/a
* Lighthouse version: 3.1.0 
* Node.js version: n/a
* Operating System: Windows

**Related issues**

**Comment by justinribeiro** [comment]
Hi thanks for the issue! The scale in v3.1.0 was recently changed in (https://github.com/GoogleChrome/lighthouse/pull/5831) and there is a patch incoming to resolve the inconsistency within the legend (https://github.com/GoogleChrome/lighthouse/pull/5985)

**Comment by piengeng** [comment]
Thanks for the quick feedback!
