### ISSUE TITLE
Wait for SW to finish installing

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#599]
Today we assume that a SW, if there is one, will have installed by the time the first pass finishes. For a large SW install that may not be the case.

I think we need something that watches for a SW to start installing and causes the pass to wait for it before moving to the next one.

Any takers?

**Comment by wardpeet** [comment]
Would this be enough to listen to the activate event of the sw? If no takers I could give it a spin

**Comment by sendilkumarn** [comment]
Can we have it in once the page loading completed. To check and wait till SW is activated. 
I would like to give it a shot.

**Comment by byronigoe** [comment]
With the LH extension I'm getting a checkmark for "Has a registered Service Worker" (I'm using sw-precache), but a false-positive failure for "URL responds with a 200 when offline". When I test manually, use Developer Tools and enable "Offline", all the network requests show a 200, and the page loads completely.

The URL is veggietables.org/app, and this is a decent size AngularJS webapp. My minified JS file is 580K, and I get a "First meaningful paint" of between 4 and 6 seconds. When running the test with version 1.4.1 of the LH extension, the page refreshes a bunch of times quite quickly. So, my hypothesis is that the SW is not done installing/precaching.

Any help would be appreciated.

**Comment by patrickhulce** [comment]
@byronigoe your situation might also be an artifact of #1296 which has been fixed in master but yet to be released in the extension, do you get the same problem running with a git checkout from command line?

**Comment by byronigoe** [comment]
Thanks for the tip, @patrickhulce 
The first time running the CLI from master it gave the same false positive. Subsequent runs correctly reported that it works offline. So, it seems that the recent fix (almost completely) solves the issue.

**Comment by wardpeet** [comment]
@byronigoe @patrickhulce should  I close this issue?

**Comment by byronigoe** [comment]
@wardpeet Yes, I think that's fine.

**Comment by patrickhulce** [comment]
@wardpeet do you happen to have a working example of this issue from before? I would assume that the waitForLoad logic that waits for network idle (introduced after this issue was created) has rendered it obsolete, but I'm not sure.

**Comment by wardpeet** [comment]
@patrickhulce no I did not, maybe ask @paullewis 😛

**Comment by paulirish** [comment]
I believe this is fixed as our second pass (where we do the sw gatherer) has a navigation to about:blank inbetween which gives the SW a chance to not only finish installing but activate

let's close, unless someone can repro this.
