### ISSUE TITLE
Invalid InterceptionId when running multiple instances simultaneously 

### ISSUE THREAD

**Issue by dr3** [GoogleChrome/lighthouse#5997]
When running multiple lighthouse checks asynchronously an error is thrown. It doesnt error every time however generally fails around 15% in my experience (testing on around 4500 urls, with 10 instances at a time.)

```
(node:41928) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.continueInterceptedRequest): Invalid InterceptionId.
    at Function.fromProtocolMessage (/Users/drew/dev/light-mc-crawler/node_modules/lighthouse/lighthouse-core/lib/errors.js:60:19)
    at callback.resolve.Promise.resolve.then._ (/Users/drew/dev/light-mc-crawler/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:89:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

#### Provide the steps to reproduce
1. Run LH on https://www.bbc.co.uk/news and urls below it
2. Queue up multiple runs using `async/queue`, running 10 instances at once.
3. Within 5-20 runs it will error.

Run using chrome flags `["--no-sandbox", "--user-data-dir", "--headless", "--disable-setuid-sandbox", "--disable-gpu", "--disable-dev-shm-usage"]`
and the mixed content audit `https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/mixed-content.js`

#### What is the current behavior?
When running multiple instances at once an error is thrown.

#### What is the expected behavior?
The error isnt thrown.

#### Environment Information
* Affected Channels: CLI, Node
* Lighthouse version: 3.0.3
* Node.js version: 8.10.0
* Operating System: MacOS 10.12.6

**Comment by connorjclark** [comment]
We don't recommend running LH concurrently, so I don't think it makes since for us to investigate this particular issue. However, if someone wants to open a _new issue_ with a script that still repros (this issue is pretty old), would be happy to take a look.
