### ISSUE TITLE
Processed 10K websites with Lighthouse - short summary and looking for a feedback

### ISSUE THREAD

**Issue by cigolpl** [GoogleChrome/lighthouse#6001]
Hello,

I've processed over 10K alexa rank top ecommerce websites in the last week by using `Lighthouse`. I was doing that with one company with purpose for creating a `market report`

My goal was to get lighthouse indicators like `seo`, `best_practices`, `accessibility`, `pwa` and `performance` and also `audits` suggestions like i.e. `https is not working`. 

Data has been processed by using dockerized Lighthouse (https://github.com/digestoo/lighthouse-api). It was done on a DigitalOcean with 8 GB RAM and 4 vCPUs located in Germany. You can see results here http://lighthouse.shoprank.co/?sort=alexa_rank. 

There is graphical distribution of lighthouse indicators for 16K websites in case the above website is out someday:

![selection_058](https://user-images.githubusercontent.com/1032493/45288861-012fee00-b4ec-11e8-98f2-5b93467f7909.png)

Not sure if the results are correct because I was getting different results by using Google Chrome plugin, https://developers.google.com/web/tools/lighthouse/run and API in Node.js. What is interesting the `SEO` indicator  is very good for most of the websites. I am wondering also if performance is the same if I test from USA, Germany or China server. I am also sharing results because maybe this experiment might be interesting for some of you. Looking forward for your feedback

**Comment by Hoten** [comment]
> I am wondering also if performance is the same if I test from USA, Germany or China server.

Nope! Performance audits are heavily dependent on CPU and the network. This explains why you see different results from the Chrome plugin (your own machine) and your DO droplet.

**Comment by cigolpl** [comment]
@Hoten well, that might be the point! Thanks for sharing ideas

**Comment by mewben** [comment]
Hi @cigolpl I'm wondering how long did it take to process 10k pages with those server specs?

(Sorry for off-topic)

**Comment by cigolpl** [comment]
Hello @mewben, I don't remember now but it was like: average time for processing one website x 10K pages. I didn't use async requests and another magic things for speeding this up. I wanted to process it rather slow to get accurate results

**Comment by patrickhulce** [comment]
@mewben FWIW we've got an internal GCE instance running LH tests and on the weakest non-burstable instance type runs take ~20s on average, so if you didn't parallelize this it'd take about 2 days to get through 10k URLs.

**Comment by mewben** [comment]
@cigolpl @patrickhulce Thanks for the info.

**Comment by brendankenny** [comment]
Thanks for sharing @cigolpl!

You may also find this document on expected types of Lighthouse variability interesting: https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md
