### ISSUE TITLE
HTTP-429 on Lighthouse reports when running via WebPageTest

### ISSUE THREAD

**Issue by abhagupta** [GoogleChrome/lighthouse#6002]
Some of out tests are breaking because of following error. This test was run via a private instance of WebPageTest. Unfortunately, I do not have access to the agent machine so I cannot find lighthouse version but since the WPT agent is itself updated pretty recently, I am assuming the version of lighthouse is fairly up-to-date.
```
lighthouse "https://www.walmart.com/ip/2-Pack-Cheerios-Gluten-Free-Cereal-Original-18-Oz-0-20-oz/654505036?_xf=0" --disable-network-throttling --disable-cpu-throttling --throttling-method provided --enable-error-reporting --max-wait-for-load 80000 --port 9231 --output html --output json --output-path "/home/wpt/wmt_wpt_agent/wptagent/work/raspberrypi/180910_QM_1ZG.1.0/lighthouse.json" --save-assets --disable-device-emulation
Mon, 10 Sep 2018 20:34:34 GMT status Initializing…
Mon, 10 Sep 2018 20:34:35 GMT status Disconnecting from browser...
raven@2.6.2 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting
Runtime error encountered: userAgent.split is not a function
TypeError: userAgent.split is not a function
    at Function.warnOnHeadless (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:175:37)
    at driver.assertNoSameOriginServiceWorkerClients.then.then.userAgent (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:106:22)
    at process._tickCallback (internal/process/next_tick.js:68:7
```
I get no lighthouse metrics or reports after this failure... Any insights will be  helpful.

**Comment by brendankenny** [comment]
That function (`GatherRunner.warnOnHeadless()`) was removed in Lighthouse 3.0 (in #5506), so if you can update your WPT dependencies that should eliminate the thrown exception.

The underlying issue looks like maybe `navigator.userAgent` was overridden in the page being tested?

**Comment by abhagupta** [comment]
Thanks. Will do.. we also found that our Chrome was version 51 which when upgraded, fixed the issue.
