### ISSUE TITLE
Warn if other tabs under control of your SW are open

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#601]
Following up from #598

If there are other tabs open, then we're unable to remove a serviceworker from play. It'll come back to life.

We'd like to warn the user to close any additional tabs that may be under control of the worker. We can use:

* [tabs API](https://developer.chrome.com/extensions/tabs#property-queryInfo-url) in the extension
* [`List` method](https://github.com/cyrus-and/chrome-remote-interface#modulelistoptions-callback) for CLI

And we'll be looking for other tabs that may be under control of the SW. We could use the registration's scopeURL and/or the site's origin and look for potential matches.

**Comment by paulirish** [comment]
the workerVersionUpdated event (i think) returns an array of clients for the SW. We can see if there are more clients connected.

**Comment by wardpeet** [comment]
I'm up for this one :)
