### ISSUE TITLE
Lighthouse PWA score not optimal due to it's own panel. 

### ISSUE THREAD

**Issue by silvandiepen** [GoogleChrome/lighthouse#6015]
#### Provide the steps to reproduce
1. Run LH on sleutelhoeve.netlify.com

#### What is the current behavior?
With the devtools open on the right side of my screen, I get a score on PWA of 96. With the reason: 
`The viewport size is 1052px, whereas the window size is 1764px.`
The viewport is less wide as the window, due to the devtools. 

#### What is the expected behavior?
I should get a PWA score of 100. LH should just check the size of the viewport and the size of the document, not the size of the window due to toolbars including it's own panel. 

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: in Chrome Version 69.0.3497.92
* Node.js version:v8.9.4
* Operating System: Mac OS 10.13.6

**Comment by midzer** [comment]
Hi @silvandiepen 
Posted site has issues on mobile. You can verifiy by using mobile view in Chromium Dev Console -> right now site doesnt fit perfectly in mobile viewport, you can slightly scroll to the right (I selected Samsung S5)

I did some debugging on this:
Apparently, there is a CSS issue in `<section class="intro bg-white" id="intro" data-v-dfd9daf8="">` (or children) element. When you delete this element. Site perfectly fits in viewport.

Good to have LH report this :) too bad, it doesnt detect (yet) where exactly in CSS there might be problems...

**Comment by justinribeiro** [comment]
Thanks for the issue! Based on your description, I can duplicate this issue using a desktop audit. This sounds similar to issue #5558 which has a fix inbound with PR #5893.

**Comment by brendankenny** [comment]
Agreed, let's close in favor of #5558
