### ISSUE TITLE
Serviceworker not registered issue

### ISSUE THREAD

**Issue by sudhiakki** [GoogleChrome/lighthouse#6016]
service worker getting registered in mobile browser but lighthouse audit showing unregistered service-worker issue . Can please specify User-Agent string used for Audit?

URL - https://m.navbharattimes.indiatimes.com/service-worker.js?v=63c5cc5ec935cbfb52cc

Error Page Screenshot
https://lh3.googleusercontent.com/-YIr6jfEJ6cw/W5pm2GCzc8I/AAAAAAAAAPg/mPXiqOmF5VgxiLg7-he-EgpSaDqdC7hlACL0BGAYYCw/h553/2018-09-13.png

**Comment by midzer** [comment]
Hi @sudhiakki I did not test mobile. But on my desktop browser service worker is not installed (see Application tab in Chromium). I think service worker should be installed for mobile and desktop to make things maintainable more easily.

**Comment by brendankenny** [comment]
Let's merge into #5527
