### ISSUE TITLE
Correctly parse manifest URLs and reject invalid ones

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#602]
The Web App Manifest spec requires invalid URLs to be discarded and some default used instead, e.g. [in the parsing of `start_url`](https://w3c.github.io/manifest/#start_url-member). Node's `url.resolve` is very lenient with what it accepts, and what throws as an error when passed to `new URL(...)` in the browser is accepted happily in node.

One option is using [whatwg-url](https://github.com/jsdom/whatwg-url) for URL parsing

In general, using it would be an improvement in predictability, since we would be parsing URLs in node the same as they would be in the browser.

Downside: three new dependencies, as whatwg-url depends on [webidl-conversions](https://github.com/jsdom/webidl-conversions) and [tr46](https://github.com/Sebmaster/tr46.js)

**Comment by wardpeet** [comment]
i'm not a fan but if it gives us more stability we should..

**Comment by brendankenny** [comment]
I've updated the issue to reflect what it's really about: correctly parsing URLs for the manifest parser. Using whatwg-url would probably help in other places, but that's the issue I was running into.

Until we have a better solution here, the manifest parser will technically be off spec, but that might not be the end of the world (especially if we can wait until node has native whatwg-style url parsing support)

**Comment by paulirish** [comment]
I'm a big fan of moving to whatwg url parser. It's more stable, has support for `.origin`. It's really just a polyfill until node lands the parser in nodejs core: https://github.com/nodejs/node-eps/blob/master/003-url.md & https://github.com/nodejs/node/pull/7448

We can exclude it from the bundle for clientside builds, and we'll be able to get rid of the url.js module from the browserify builds as well.

**Comment by wardpeet** [comment]
Agree!

**Comment by brendankenny** [comment]
fixed in #997!
