### ISSUE TITLE
Add 'displayValue' property in CSV output report

### ISSUE THREAD

**Issue by Scarlett-Truong** [GoogleChrome/lighthouse#6022]
It is great that Lighthouse has the option to export report in csv. But in the csv, there are only few data displayed (category, name, title, type, score) compares to the json file. Is it possible to get all the statistic data results, including the 'displayValue' field in csv as in the json?

**Comment by brendankenny** [comment]
This sounds like it would be easy to add and an easy win. We would just want to coordinate with anyone using the output (@nourikhalass, others?) to make sure it was strictly additive and doesn't end up a breaking change for anyone.

Relevant line would be
https://github.com/GoogleChrome/lighthouse/blob/6eaf51b4ee8df9796d7e1754b005b2aee5d413e9/lighthouse-core/report/report-generator.js#L77
I believe.

**Comment by brendankenny** [comment]
I don't see this in the immediate future of anyone in particular, so, open for any takers.

**Comment by paulirish** [comment]
@Scarlett-Truong whats an example of an audit where you'd like the displayValue?  most of the time those strings are represented elsewhere.. (like `audit.details.overallSavingsMs`)

**Comment by nourikhalass** [comment]
I'm fine with the proposed changes and think they would be a nice addition. I'm not aware of any infrastructure relying on CSV exporting so any changes made, now and in the future, are OK with me!

**Comment by brendankenny** [comment]
Closing since this doesn't seem to be an immediate need :)

Please comment if it's still needed and we can reopen.

**Comment by liamvictor** [comment]
The CSV files are only useful for immediate and isolated use. They don't contain the URL of the page tested so when comparing several CSVs to calculate averages over a site or section it soon becomes onerous.

All of the data is in the json file, but JSON lacks an easy interface to investigate the information. I believe that having that JSON data (especially the requestedUrl & finalUrl ) in the CSV would make the CSV output much more useful. 

In case it matters, I've been using the CLI to generate the files.

**Comment by axlright** [comment]
When using the cli, why does the csv output for Largest Contentful Paint show a score like 0.01 when the html output shows a time like 5.2s? My clients ask for numerous reports that are averaged, and the csv output would be great for easily automating this. My clients ask to see data like they are used to seeing in the web results, so they want to see the 5.2s not a score like 0.01.

Is it possible to add flags to have the csv output the same metrics that the html does?

Thanks!

**Comment by Spereicle** [comment]
> When using the cli, why does the csv output for Largest Contentful Paint show a score like 0.01 when the html output shows a time like 5.2s? My clients ask for numerous reports that are averaged, and the csv output would be great for easily automating this. My clients ask to see data like they are used to seeing in the web results, so they want to see the 5.2s not a score like 0.01.
> 
> Is it possible to add flags to have the csv output the same metrics that the html does?
> 
> Thanks!

Hi @axlright,

The value you are seeing in the CSV is the Metric Score not the Metric Value. The later is shown in the HTML. You can confirm this by clicking the 'See Calculator' link where both corresponding values are displayed.

**Comment by Spereicle** [comment]
@brendankenny 
As the requestedUrl	& finalUrl columns have now been added to the CLI CSV ouput, I'm hoping the addition of the 'displayValue' column will be revisited and implemented.

Usage Case: Large number of audits done using CLI and then processed using non JS friendly applications (Excel for instance) when the data handling would be made significantly easier via a more robust CSV file.

**Comment by Spereicle** [comment]
@Scarlett-Truong @liamvictor 

The following code, replacing the native function block in report-generator.js will do the trick:

```
  static generateReportCSV(lhr) {
    // To keep things "official" we follow the CSV specification (RFC4180)
    // The document describes how to deal with escaping commas and quotes etc.
    const CRLF = '\r\n';
    const separator = ',';
    /** @param {string} value @return {string} */
    const escape = value => `"${value.replace(/"/g, '""')}"`;
    /** @param {Array<string | number>} row @return {string[]} */
    const rowFormatter = row => row.map(value => value.toString()).map(escape);

    // Possible TODO: tightly couple headers and row values
    const header = ['requestedUrl', 'finalUrl', 'category', 'name', 'title', 'type', 'score', 'numericValue', 'numericUnit', 'displayValue', 'description'];
    const table = Object.keys(lhr.categories).map(categoryId => {
      const rows = [];
      const category = lhr.categories[categoryId];
      const overallCategoryScore = category.score === null ? -1 : category.score;
	    // Add Overall CategoryScore
      rows.push(rowFormatter([lhr.requestedUrl, lhr.finalUrl, category.title,
        `${categoryId}-score`, `Overall ${category.title} Category Score`, 'numeric',
        overallCategoryScore, 'n/a', 'n/a', 'n/a', 'n/a']));
      // Add discrete category value rows
      return rows.concat(category.auditRefs.map(auditRef => {
      const audit = lhr.audits[auditRef.id];
      // CSV validator wants all scores to be numeric, use -1 for now
      const numericScore = audit.score === null ? -1 : audit.score;
      // Add in: audit.numericValue, audit.numericUnit, audit.displayValue, audit.description
      const nV = audit.numericValue == null ? '<Null or Undefined>' : audit.numericValue;
      const nU = audit.numericUnit == null ? '<Null or Undefined>' : audit.numericUnit;
      const dV = audit.displayValue == null ? '<Null or Undefined>' : audit.displayValue;
      const desc = audit.description == null ? '<Null or Undefined>' : audit.description;
      // console.log([lhr.requestedUrl, lhr.finalUrl, category.title, audit.id, audit.title, audit.scoreDisplayMode, numericScore, nV, nU, dV, desc]);
		return rowFormatter([lhr.requestedUrl, lhr.finalUrl, category.title, audit.id, audit.title,
          audit.scoreDisplayMode, numericScore, nV, nU, dV, desc]);
      }));
    });
```

For those importing the resultant csv into excel, set your input encoding to utf-8

**Comment by connorjclark** [comment]
Hello csv users, we want to give the CSV output a rework for LH 10.0, feedback welcome: #13558

In general what @Spereicle shared above is how we'd expect things to work: the JSON has all the data and is pretty stable...CSV has limitations and can't nicely fit everything... so it's up to the user to transform from one domain to the other. but LH also provides a `csv` output which understandably muddies the water re: expectations here. None of us on the team has ever really liked the CSV output we generate, so we'd like to give it a rework. But I think it's likely that super-involved spreadsheet use cases of LH data will still involved some JS glue.
