### ISSUE TITLE
DevTools Error: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by StructByLightning** [GoogleChrome/lighthouse#6026]
**Initial URL**: https://www.parahumans.net/
**Chrome Version**: 69.0.3497.92
**Error Message**: Cannot read property 'value' of undefined
**Stack Trace**:
```
TypeError: Cannot read property 'value' of undefined
    at sendCommand.then.result (chrome-devtools://devtools/remote/serve_file/@eb2c6d16bcb960cc5c322243c1771713460c4bcf/audits2_worker/audits2_worker_module.js:1008:211)
```

**Comment by brendankenny** [comment]
Something went pretty wrong here. This is the `result` on the response from `sendCommand('Runtime.evaluate', ...)`, which should [always exist](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#method-evaluate), even if it was returning an error.

I don't see any other instances in the error logs for this. Are you still seeing this problem or was it transient?

**Comment by StructByLightning** [comment]
That's interesting. Trying to audit the page still gave me an error. If I clicked retry, again, same error. But if instead if I clicked cancel and went to the console, then went back and tried another audit, it worked. I checked to see if I could duplicate this behavior on a fresh tab but it worked perfectly the first time. There's definitely *something* wrong somewhere but if it can't be duplicated I guess there's nothing to be done.

**Comment by wardpeet** [comment]
@exterkamp is this one fixed? Seems you created a pr for it.

**Comment by exterkamp** [comment]
It is but it is not landed in production Chrome yet so audit panel users will still see this error for the time being.

**Comment by exterkamp** [comment]
Closing, because this should be in stable Chrome M71+ (v3.2.0+).  We can reopen if this still comes up!
