### ISSUE TITLE
How to test  page flow in Lighthouse 

### ISSUE THREAD

**Issue by rageshpayyan** [GoogleChrome/lighthouse#6028]
I have requested this issue couple of months back. I am using the latest version of a lighthouse, I have an application with n number of flows, Page 1-> Page 2 ->Page N. Which is automated using Node.js script,  how to run lighthouse on these pages ( page1, page2.. page N) . This is possible in the latest version of a lighthouse or this feature going to implement any future release!!

**Comment by justinribeiro** [comment]
Hi thanks for reaching out! If you have a node script that is already walking your page flows, you can programmatically use lighthouse in node to achieve what you're looking to do. Check out the documentation at ["Using LH programmatically"](https://github.com/GoogleChrome/lighthouse/tree/master/docs) for more information, as well as examples of integrating LH in ["Related Projects"](https://github.com/GoogleChrome/lighthouse#related-projects).

**Comment by rageshpayyan** [comment]
Can audit page N using lighthouse without refreshing, in my app if I audit page N, it loses all the browser state and going to the home page. So my question is can be able to use a lighthouse without page reload.

**Comment by justinribeiro** [comment]
This is a little bit tricker and the story on how to do this with LH isn't very well defined today. There is discussion ongoing on https://github.com/GoogleChrome/lighthouse/issues/3837 about how this might work within the context of Lighthouse/Puppeteer (the current planned way of addressing this concern). Right now, holding that state isn't something that LH is going to be able to accomplish.

**Comment by rageshpayyan** [comment]
@justinribeiro , Thanks for the update.

**Comment by brendankenny** [comment]
Definitely DIY right now, though it is somewhat possible. Let's close in favor of #3837 as the (eventual) real solution to this.
