### ISSUE TITLE
From Udacity

### ISSUE THREAD

**Issue by jjopatton** [GoogleChrome/lighthouse#6029]
**Summary**

**Comment by paulirish** [comment]
_Admin note_:

For those curious, a Udacity course features the Lighthouse repo to orient students in how Github repos and contributions work. 

https://github.com/GoogleChrome/lighthouse/issues/1842, in particular, is linked. You can see all the folks who've dropped a reaction. :)
![image](https://user-images.githubusercontent.com/39191/45600835-127b6d80-b9b8-11e8-9e2c-08bac3dee76a.png) 

Here's a PDF of relevant Udacity page: [udacity456-lighthouse.pdf](https://github.com/GoogleChrome/lighthouse/files/2387009/udacity456-lighthouse.pdf) It's pretty cool.
