### ISSUE TITLE
DevTools Error: Unsupported time zone specified undefined

### ISSUE THREAD

**Issue by brunoxd13** [GoogleChrome/lighthouse#6046]
**Initial URL**: http://localhost:3000/
**Chrome Version**: 69.0.3497.92
**Error Message**: Unsupported time zone specified undefined
**Stack Trace**:
```
RangeError: Unsupported time zone specified undefined
    at new DateTimeFormat (native)
    at Date.toLocaleTimeString (native)
    at new Audits2.ReportSelector.Item (chrome-devtools://devtools/bundled/audits2/audits2_module.js:242:460)
    at Audits2.Audits2Panel._buildReportUI (chrome-devtools://devtools/bundled/audits2/audits2_module.js:184:28)
    at Audits2.Audits2Panel._startAudit (chrome-devtools://devtools/bundled/audits2/audits2_module.js:192:181)
```

**Comment by wardpeet** [comment]
I believe @paulirish is the best man to answer this. I don't know the devtools pipeline about lighthouse.

the issues seems to be here https://cs.chromium.org/chromium/src/out/Debug/gen/devtools/audits2/audits2_module.js?q=_buildReportUI&sq=package:chromium&dr=C&l=242

**Comment by paulirish** [comment]
Ah this appears to be this upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=364374
It is fixed in Chrome, so Chrome Canary shouldn't be a problem. 

@brunoxd13 if you want to try again with Chrome Canary, please let us know if it's fixed there.

**Comment by brunoxd13** [comment]
@paulirish @wardpeet  I was able to solve the problem, it was my GTM configuration that was in manual mode, so I put automatic worked. Thaks a lot.

**Comment by wardpeet** [comment]
@brunoxd13 oh so we could easily reproduce this with gtm?

**Comment by brunoxd13** [comment]
@wardpeet I believe that manually changing.

**Comment by paulirish** [comment]
@brunoxd13 whats GTM? google tag manager?

**Comment by brunoxd13** [comment]
@paulirish I believe that @wardpeet  meant gmt, not gmt. Is it ok?

**Comment by wardpeet** [comment]
Hehe sorry I thought you meant Google tag manager TBH 🙈. It was weird that gtm would mess with datetime settings but we had weirder issues

**Comment by paulirish** [comment]
@brunoxd13 your GMT configuration was in manual mode? this is on windows?

**Comment by brunoxd13** [comment]
@paulirish My configurations were in manual mode, I was using Ubuntu Linux

**Comment by wardpeet** [comment]
i'll spin up an ubuntu vm and try it out

**Comment by wardpeet** [comment]
@brunoxd13 how do you set it to manual mode?
![image](https://user-images.githubusercontent.com/1120926/46108258-e349d500-c1dd-11e8-83c5-cf6aadf55a05.png)

are you editting /etc/timezone yourself?

**Comment by brunoxd13** [comment]
@wardpeet I edited through the interface, I did not use the file at any time. 
Change the timezone and try.

**Comment by wardpeet** [comment]
I did and no error.

Could you maybe step me through 
1) set timezone to.. ?
2) open chrome on a page
3) run lighthouse through the audit panel
4) lighthouse report has errors about timezone?

**Comment by brunoxd13** [comment]
@wardpeet I do not remember very well the configuration of my operating system, however I remember that when you use some website that used the time like WhatsApp, the time was changed.

**Comment by brendankenny** [comment]
closing in favor of #6691 (see https://github.com/GoogleChrome/lighthouse/issues/6691#issuecomment-448009363)
