### ISSUE TITLE
report details table right-alignment is ugly

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6049]
e.g. 
![image](https://user-images.githubusercontent.com/39191/45706726-d66c1800-bb31-11e8-9148-f67d286dba7a.png)

first column should always be left aligned. 

but ideally all text columns are left-aligned and all number columns are right-aligned.  not sure if we have the classes for this, but we might.

shane sez we should drop the centered TH's too. let's keep them always the same as the TDs

**Comment by wardpeet** [comment]
what do we assign as a number?
we currently have these types:
* `.lh-table-column--text`
* `.lh-table-column--bytes`
* `.lh-table-column--timespanMs`
* `.lh-table-column--ms`

I guess we align everything right except `.lh-table-column--text`
we end up with
![image](https://user-images.githubusercontent.com/1120926/45777171-53dc7900-bc55-11e8-9400-ea3d3f886208.png)

**Comment by brendankenny** [comment]
fixed? or 3/6 fixed

**Comment by wardpeet** [comment]
Fixed
