### ISSUE TITLE
HTTP -> HTTPS redirect can false positive if site using HSTS

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/lighthouse#607]
Lighthouse reports that the HTTP URL <http://billingsgazette.leeaws.com/pwa/#top-stories> redirects to HTTPS, however it (usually) doesn't.

<img width="448" alt="screen shot 2016-08-23 at 4 22 56 pm" src="https://cloud.githubusercontent.com/assets/51244/17897927/e4d6daf2-694d-11e6-865a-071f4cc86352.png">

(This can also be confirmed by viewing the headers with curl, etc.)

(However, note that this site can get into a state where the site is only ever loaded over HTTPS. This is probably something to do with the fact that it returns the header `Strict-Transport-Security: max-age=31536000` over HTTP; perhaps Lighthouse is unable to distinguish a server-provided HTTP -> HTTPS redirect from a redirect provided by Chrome?)

**Comment by brendankenny** [comment]
Ah, interesting. To (hopefully) clarify:

- a visit to `http://billingsgazette.leeaws.com/pwa/#top-stories` will not redirect to https. Just to be clear, when I test this URL with a clean profile it correctly fails the redirect audit.
- a visit to `https://billingsgazette.leeaws.com/pwa/#top-stories` will use an HSTS header and so future visits to the http URL will automatically redirect

The current audit runs the redirect check *after* loading the page once, so if testing the https URL Lighthouse will obey the HSTS directive and automatically load the secure page. To properly test how a first-time visitor would (or wouldn't) be redirected (which I believe is the intention of the audit), Lighthouse would either need to test on the first run or ignore the HSTS header for the test.

Perhaps we could have some nuance and still give a pat on the back for using HSTS, even if it isn't helping this issue.

**Comment by brendankenny** [comment]
I didn't realize @paulirish had already considered and come up with some options for handling HSTS in #277. Closing in favor of that issue.
