### ISSUE TITLE
Correctly emulate desktop in headless scenarios

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6092]
When we're run in headless (LR) and we want the desktop experience, the viewport behavior is quite undefined, leading to screenshots that are cut off:
![image](https://user-images.githubusercontent.com/39191/45911742-15b59580-bdcc-11e8-8a45-080e05ae7e80.png)

We think desktop "emulation" is the answer here. I've [tried it out](https://github.com/GoogleChrome/lighthouse/compare/not_applicable_viewport...desktopemu) and everything looks more expected in headless:
![image](https://user-images.githubusercontent.com/39191/45911762-5c0af480-bdcc-11e8-81eb-88493fb3d31f.png)

TBH our driver & emulation code don't nicely account for this scenario, so it'll need some thought.  @patrickhulce this seems up your alley. watcha thinkin?

**Comment by patrickhulce** [comment]
yeah I've been chewing on this idea too after #5893, I'm thinking an enum for `formFactor` or some such name instead of `disableMobileEmulation` :)

**Comment by paulirish** [comment]
> I'm thinking an enum for formFactor or some such name instead of disableMobileEmulation

that sounds **great**. `disableMobileEmulation` is an OK cli flag, but it's proven to be quite cumbersome in core.
