### ISSUE TITLE
[Project related with lighthouse] - Lighthouse github reporter

### ISSUE THREAD

**Issue by carlesnunez** [GoogleChrome/lighthouse#6097]
Hello everyone!

In order to improve my own software development pipe I decided to create an small tool that let us launch a lighthouse benchmark and with an small config by package.json or cli we can setup that this report end up on a comment on the PR that we decide:
https://www.npmjs.com/package/lighthouse-gh-reporter
https://github.com/carlesnunez/lighthouse-github-reporter

I'll be so happy if it gets added on the base lighthouse readme :)

Star if it helped you, this is on a really early stage and can be code improved so... I am really opened to PR's and improvements.

Hope it helps you as it helped me!!

**Comment by wardpeet** [comment]
@carlesnunez could you make the change yourself an shoot a PR for it?

**Comment by carlesnunez** [comment]
Off course! I’ll do it today or tomorrow :)

**Comment by carlesnunez** [comment]
Done! @wardpeet

**Comment by exterkamp** [comment]
This was fixed when #6307 merged.  Congrats on the merge!
