### ISSUE TITLE
lighthouse hang on url which keeps reload

### ISSUE THREAD

**Issue by liulangyu90316** [GoogleChrome/lighthouse#6108]
#### Provide the steps to reproduce
1. Run LH on http://m.7czw.com/xuexi/xxfw/20160802/25525.html

#### What is the current behavior?
cpu rise to 100%，and the process just hang

#### Environment Information
* Affected Channels: CLI, Node, Extension, DevTools
* Lighthouse version: newest
* Node.js version: 8/9
* Operating System: mac/linux

**Comment by justinribeiro** [comment]
This bug isn't specific to LH, but rather the detection that the site does in Chrome when the user agent is a mobile (it seems to spin and reload on a loop as noted in the ticket). I can also duplicate this behavior on mobile Safari and Firefox in mobile view.

**Comment by exterkamp** [comment]
Since this seems like it was a website issue + it is now 404ing, I am going to close this, but we can reopen if this is still an issue.
