### ISSUE TITLE
noindex, nofollow reduces score

### ISSUE THREAD

**Issue by ojemuyiwa** [GoogleChrome/lighthouse#6111]
#### Provide the steps to reproduce
1. add `<meta name="robots" content="noindex,nofollow" />` to your document

#### Indeed these sections of the site I would like blocked?

2. add Noindex for particular parent path in robots.txt

#### Environment Information
* Affected Channels: 
* Lighthouse version: 3.0.3
* Node.js version: 8.11.1
* Operating System: Mac OS High Sierra

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @ojemuyiwa! This is intentional. If you do not want your site to be seen by search engines, you don't really need to care at all about our SEO (search engine optimization) category. :)

Feel free to add more and re-open if I've misunderstood!

**Comment by ojemuyiwa** [comment]
I guess that's fine. Just the admin / auth sections of the site i'm seeing these. Was just wondering why some pages scored higher than others i.e. penalised (score lower) for non indexing or crawling directives.
