### ISSUE TITLE
Update Chrome Webstore Screenshots

### ISSUE THREAD

**Issue by coliff** [GoogleChrome/lighthouse#6112]
not really a big deal or anything but the [screenshots on the Chrome Webstore](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk) are of a very old version of the Lighthouse extension... would be nice to have updated ones so folks can see how great it looks now. :-)

**Comment by brendankenny** [comment]
we eventually get around to these things :)

Screenshots are updated: https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk
