### ISSUE TITLE
On a valid html webpage using valid attributes, Lighthouse returns an invalid `selector` in some scenarios

### ISSUE THREAD

**Issue by joelhsmith** [GoogleChrome/lighthouse#6115]
I put up and example website on Github Pages:
https://joelhsmith.github.io/debug-examples/date-selector-issue/date-selector-issue.html

#### Issue
On a valid html webpage using valid attributes, Lighthouse returns an invalid item `selector` on Accessibility audits in the following scenario:

If two or more elements have:
1. identical selectors 
2. identical attributes
3. one attribute's value (in this case `content`) is different.

Example of two elements causing the problem from the example website (note the `content` attributes are unique):

`<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2018-09-26T15:30:00-04:00">Wednesday, September 26</span>`

`<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2018-10-01T11:30:00-04:00">Monday, October 1</span>`

#### Provide the steps to reproduce

1. Run LH

`
lighthouse --only-categories accessibility https://joelhsmith.github.io/debug-examples/date-selector-issue/date-selector-issue.html --output=json --output-path=date-selector-issue.json
`

Result:
https://raw.githubusercontent.com/joelhsmith/debug-examples/master/date-selector-issue/date-selector-issue.json

#### Problem
Returns invalid items > node > selector by encoding the `selector`

```
        "items": [
          {
            "node": {
              "type": "node",
              "selector": "span[content=\"\\32 018-09-26T15\\:30\\:00-04\\:00\"]",
              "path": "1,HTML,1,BODY,1,DIV,1,SPAN",
              "snippet": "<span class=\"date-display-single\" property=\"dc:date\" datatype=\"xsd:dateTime\" content=\"2018-09-26T15:30:00-04:00\">Wednesday, September 26</span>",
              "explanation": "Fix any of the following:\n  Element has insufficient color contrast of 2.37 (foreground color: #ff847d, background color: #ffffff, font size: 30.0pt, font weight: normal). Expected contrast ratio of 3:1"
            }
          },
          {
            "node": {
              "type": "node",
              "selector": "span[content=\"\\32 018-10-01T11\\:30\\:00-04\\:00\"]",
              "path": "1,HTML,1,BODY,3,DIV,1,SPAN",
              "snippet": "<span class=\"date-display-single\" property=\"dc:date\" datatype=\"xsd:dateTime\" content=\"2018-10-01T11:30:00-04:00\">Monday, October 1</span>",
              "explanation": "Fix any of the following:\n  Element has insufficient color contrast of 2.37 (foreground color: #ff847d, background color: #ffffff, font size: 30.0pt, font weight: normal). Expected contrast ratio of 3:1"
            }
          }
        ],
```
I speculate that Axe tries to return a unique-ish `selector` by latching onto the one attribute that has a unique value, the `content` attribute.  Then returns it using a pseudo selector, but might be getting processed in Lighthouse

`span[content=\"\\32 018-09-26T15\\:30\\:00-04\\:00\"]`

It looks like it is getting escaped for some reason. But even if it was done on purpose its not valid. Note it turns `2018` to `\\32 018`.

Expected behavior is to return: (EDIT: probably does not need escaped at all)

`span[content="2018-09-26T15:30:00-04:00"]`

#### Use case for needing the `selector` fixed:
If a person wants to look up the element Chrome's "Find by string, selector, or XPath".
In my case, I wrote a Python script that takes screenshots of every element that fails accessibility audits using selenium. 

#### Not an edge case

Those unusual DC [attributes](http://dublincore.org/documents/dcq-html/) are often used on dates.  Almost every Drupal website's date element has these attributes. So every list of events on the website will return a pile of invalid `selector`. I suspect other CMS platforms do this also.

#### Environment Information
node: 8.9.1
lighthouse: 3.0.3
os: Mac OS 10.12.6

**Comment by justinribeiro** [comment]
I can duplicate the issue running the axe-cli, so my suspicion is that this is upstream (but I wasn't able to find a relevant ticket):

![image](https://user-images.githubusercontent.com/643503/46101994-1f4f4c80-c182-11e8-9bff-fbd49771d638.png)

**Comment by joelhsmith** [comment]
Thanks @justinribeiro I will follow up in the Axe core issue queue.
