### ISSUE TITLE
All pageloads hit the 45 second timeout in Canary

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6119]
version 71.0.3562.0 (Official Build) canary

turns out `Page.addScriptToEvaluateOnLoad` is broken so our perf observer didnt register, etc.

cc @patrickhulce 

* https://chromium-review.googlesource.com/c/chromium/src/+/1244460 from @pavelfeldman landed yesterday at 5:30PM and just barely slipped into today's canary build. 
* It was reverted
* https://chromium-review.googlesource.com/c/chromium/src/+/1246597 was a reland which is submitted. 
* That's reverted as well?
* A CL-to-be will fix things?

rest assured pavel will sort things out quickly. :)

-----

On our side, theres not a LOT we could do except wait. We _could_ see if we get a heartbeat signal from the PO and if we don't, take evasive maneuvers.  Or we just drop this approach and begin issuing our own protocol events for long tasks.

**Comment by patrickhulce** [comment]
In my investigating I added some error logging with `__lastLongTask` was undefined. At least locally we would be able to tell pretty obviously. I think the basic runtime assertions for pages would help catch regressions like this too.

**Comment by paulirish** [comment]
Today's canary is good. Tomorrow _should_ be good, too.
