### ISSUE TITLE
NO_FCP, cannot measure performance

### ISSUE THREAD

**Issue by SergeyShablenko** [GoogleChrome/lighthouse#6134]
#### Provide the steps to reproduce
I`m running LH on website via ip, have problems with domain name at the moment
It is served via https, certificate is generated by myself, it is not valid (during test), in future will get a valid one.

#### What is the current behavior?

Currently I`m having next results

![image](https://user-images.githubusercontent.com/13334277/46194853-42f1ce80-c30b-11e8-8e35-0bb0716b2be6.png)

#### What is the expected behavior?

Expect LH to evaluate performance and check pwa checklist  

#### Environment Information
* Affected Channels: Extension 
* Lighthouse version: 3.2.0
* Node.js version:
* Operating System: Ubuntu 18 LTS

**Related issues**

**Comment by SergeyShablenko** [comment]
But why it cannot just ignore certificate?

**Comment by patrickhulce** [comment]
You can use [chrome flags](https://peter.sh/experiments/chromium-command-line-switches/) to ignore web security issues, but it's definitely not recommended.

**Comment by SergeyShablenko** [comment]
I'll try, just want to test website even with invalid certificate

**Comment by serge22** [comment]
Does not work for me neither. Valid certificate, domain www.google.com

Lighthouse 3.2.0
OS Ubuntu 18.04.1

![screenshot](https://user-images.githubusercontent.com/5090641/46304246-f7bc1200-c5cf-11e8-92b8-a69a613ff8d5.png)

**Comment by patrickhulce** [comment]
@serge22 that's almost certainly different. If it's reproducible, could you file a separate issue with a bit more detail of the error and your steps?

**Comment by wardpeet** [comment]
This seems to work:
`lighthouse <url> --chrome-flags="--ignore-certificate-errors"`
