### ISSUE TITLE
Lighthouse Reports Filenames

### ISSUE THREAD

**Issue by maptxa** [GoogleChrome/lighthouse#6135]
Hi! 

I just have a quick question. The question is, that is there any way to "customize" the filenames when they get saved? By default it's the domain name and date, but is it even possible to change the saving name rather than renaming it manually later? :) Maybe it's possible but I just missed the solution. 

Thanks in advance!

**Comment by patrickhulce** [comment]
Yep! Take a look at the `--output-path` option in the CLI :)

![image](https://user-images.githubusercontent.com/2301202/46214410-be9a4e00-c300-11e8-815f-7f42a8369118.png)

PS: `lighthouse --help` can come in handy sometimes ;)

**Comment by maptxa** [comment]
Yes, I know that, I tried it, but it changes all the filenames to the one I set, but I'm interested in saving each file with a different name. If that's possible :)

**Comment by patrickhulce** [comment]
Would you mind clarifying what you mean by `each file`? Are you using multiple outputs? Is it the trace file? Are you running multiple times? It should use the same output-path you're setting, but with unique suffixes to distinguish different file types (unavoidable or you'd only get 1 of the N files you requested).

**Comment by maptxa** [comment]
Okay, so. I'm using a batch script to continuously run lighthouse on a urls text file. It saves them in a folder as soon it's done running it on one url (www.example.com_*date* is the default). I'm curious if it's possible to make it save each file with the original url(like if I ran lighthouse on www.example.com/whatever-is-this, then is it possible for it to save the report with this name?) 
Doing my best explanation, sorry if confusing. :) 

Thanks!

**Comment by patrickhulce** [comment]
Yes, you can use `--output-path` in your script and just change what you're passing into it. In this case, you want to pass the sanitized URL you're giving LH also as the `--output-path`.

**Comment by maptxa** [comment]
Okay, thank you! I'm going to play around with it some more :)

**Comment by kud** [comment]
Hello,

It's a shame we can't define a folder instead of a filename.

Because if I specify a folder, it doesn't work, and if I specify a filename, I can't save multiple reports because the filename is strict.

I'd like to add a date so I will probably add this date via my shell but it could be included in this cli.

**Comment by kud** [comment]
For the moment I will use `npx lighthouse --view --chrome-flags='--headless' --output-path='./__tests__/lighthouse/'$(date +%Y-%m-%d-%H-%M-%S)'.html'` but it doesn't take the host. :/

**Comment by patrickhulce** [comment]
You know the URL you're passing to lighthouse, why not just use it in your `--output-path`?

```
ORIGIN_PART=$(echo $THE_URL | sed -E 's|https?://([^/]*)/.*|\1|g' | sed -E 's|[^a-z0-9]+|_|g')
DATE_PART=$(date +%Y-%m-%d-%H-%M-%S)
OUTPUT_PATH="./__tests__/lighthouse/$ORIGIN_PART-$DATE_PART.html"

**Comment by kud** [comment]
Well to be fair, I'd like to do something like

`--output-path=./my/dir/` and it keeps the way you write already the filenames by default. :)

I know what I'm passing as url but it makes it redundant.

Thank you for your snippet!
