### ISSUE TITLE
Incorrect Tooltip Information in Audits Tab

### ISSUE THREAD

**Issue by nurul3101** [GoogleChrome/lighthouse#6137]
In the device section of Audit tab, there are two options Mobile and Desktop. When you hover over **Desktop** it says *"**Apply mobile emulation during auditing**"* which shouldn't be the case. That message should be specified when hovered over Mobile options only. For Desktop option there should be a different tooltip.

**Comment by patrickhulce** [comment]
Thanks for reporting @nurul3101. I believe this is a duplicate of #5747. @paulirish's explanation there is still solid 👍
