### ISSUE TITLE
Exploring perf results in Timeline

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#616]
While the [pwmetrics](https://github.com/paulirish/pwmetrics/) project gives a UI for the perf results, it's more valuable to see them against the timeline. I started an initial spike on this and wanted to share.

This is a trace of theverge.com loading, recorded w/ Lighthouse:

![lh metrics in timeline - theverge](https://cloud.githubusercontent.com/assets/39191/18024950/6c8eeb48-6bcd-11e6-94f4-8f3ca1606ad7.png)

The following metrics are in here: `First contentful paint`, `First meaningful paint`, `First visual change`, `Visually complete`, `Perceptual Speed Index`, `Time to Interactive`
- Lighthouse patch: https://github.com/GoogleChrome/lighthouse/compare/exportmetricstotrace
- DevTools patch: https://codereview.chromium.org/2283793005

The basic flow: With `--save-assets` on, we take our metrics and turn them into fake trace events. We then inject them into the trace right before we save it to disk. Then, loading it in Timeline, we spot those and create markers. (UX-wise the markers are kind of a pain to deal with, so we can definitely think about smarter UI.)

**Comment by paulirish** [comment]
If you want to try the devtools patch out, you can try it via the new fancy devtools contrib workflow:

```sh
# clone the standalone devtools frontend repo
git clone https://github.com/ChromeDevTools/devtools-frontend/
cd devtools-frontend
git checkout -b metrikz

# grab the unified patch of CL 2283793005
wget https://codereview.chromium.org/download/issue2283793005_1.diff
# adjust the paths, as our git clone is a subtree..
sed -i -e "s/third_party\/WebKit\/Source\/devtools\///" issue2283793005_1.diff
# apply the diff to working folder
git apply issue2283793005_1.diff

# start the _new_ devtools hacker webserver
npm start server
# open the standalone devtools (don't really need to debug a page)
open "http://localhost:8090/front_end/inspector.html?experiments=true"

# and now drag in a metrics-adorned trace into Timeline panel. 
# Profit!
```

_Attached: A zip of the trace I screenshotted above:_ [www.theverge.trace.json.zip](https://github.com/GoogleChrome/lighthouse/files/440468/www.theverge.com_2016-08-27T03-12-00.842Z0.trace.json.zip)

**Comment by addyosmani** [comment]
This works **really nice** using the above workflow. Took just a few mins to setup.

![screen shot 2016-08-26 at 10 09 05 pm](https://cloud.githubusercontent.com/assets/110953/18025277/cb0032f2-6bd9-11e6-97d7-50ff4275ec32.jpg)

Paul wins all the internet 🌟 🌟 🌟 today.

**Comment by paulirish** [comment]
New, improved implementation (on the [exportmetricstotrace branch](https://github.com/GoogleChrome/lighthouse/tree/exportmetricstotrace)). Just using straight up measures means no devtools-side changes. :)


![image](https://cloud.githubusercontent.com/assets/39191/19011259/a3696d4e-8745-11e6-853d-dfad1eff8ae8.png)

**Comment by addyosmani** [comment]
Damn, that's slick. You're grouping them in to user timings? Just as useful as the other view :)
