### ISSUE TITLE
Decrease PWA rating when icons are not available

### ISSUE THREAD

**Issue by misupov** [GoogleChrome/lighthouse#6164]
#### What is the current behavior?

When all PWA criteria are met, except icon paths in manifest.json point to wrong locations, Lighthouse still shows 100% coverage.

#### What is the expected behavior?

Lighthouse should not show 100% PWA compatibility when manifest icons point to inexistent location.

#### Environment Information
* Affected Channels: DevTools

**Comment by patrickhulce** [comment]
Thanks for filing @misupov! I'm going to go ahead and de-dupe this into #789 but feel free to add more there if you'd like :)
