### ISSUE TITLE
Clean up aXe audits

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6169]
The axe gatherer is now frequently one of the slowest parts of our run. A few of their checks are particularly slow, including `color-contrast` and `td-has-header` Due to the response on the [`td-has-header` item](https://github.com/dequelabs/axe-core/issues/908),  I started looking into disabling the td-has-headers check for now. But this turned out to be more amusing... Follow along. 👇  

--------------

I figured I'd disable it in the [axeConfig](https://github.com/GoogleChrome/lighthouse/blob/9bfcf91494a712aded65da8809b08d61bc11b7a7/lighthouse-core/gather/gatherers/accessibility.js#L24-L41) and then remove the audit file.

**However**, there's no audit js file. :) 
_Yes, that means we've been incurring the cost of this check and not even showing the results._ 😭

Apparently that audit [file was removed](https://github.com/GoogleChrome/lighthouse/pull/1768/commits/f421253f899983c3597d0eac4b6b399ae0bc43c3) partway through the [PR](https://github.com/GoogleChrome/lighthouse/pull/1768) that added most axe audits. 

--------

I compared what audit files we have vs the results that aXe currently returns and found a few cases where we're doing unnecessary work:

### No LH audit file for existing aXe result 

* td-has-header
* table-fake-caption (also removed in that PR)
* marquee (??)

My preferred action is to disable the above to start. We can add them back in as necessary. OK with you, @robdodson?

**Comment by robdodson** [comment]
sgtm, though I'm a bit surprised by a few of these. All of the ones mentioned in the right column never return an axe result?

**Comment by paulirish** [comment]
fixed by #6180
