### ISSUE TITLE
Redirect console.warn to log.warn

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#617]
Sometimes the DevTools code we rely on will use console.warn to whine about `TracingStartedInPage event not found.` or `Event RendererMain.START_MSG_LOOP has already been started`

It looks a little odd, so the idea was to redefine `console.prototype.warn` (or whathaveyou) and send it to our `log.warn` utility. sg?

**Comment by brendankenny** [comment]
SGTM. need to turn off redirect when we're done, obvs
