### ISSUE TITLE
Icon sizes in manifest / custom splash screen

### ISSUE THREAD

**Issue by seantje** [GoogleChrome/lighthouse#6192]
1. LH, when given a manifest with icons of 32px and 192px reports "Is not configured for a custom splash screen".
2. Add `{ "src": "icon-192.png", "sizes": "512x512", "type": "image/png" }` to the manifest.
3. The report states "Configured for a custom splash screen".

**Comment by patrickhulce** [comment]
Yep, this is intentional. 512x512 is [required as per the docs](https://developers.google.com/web/tools/lighthouse/audits/custom-splash-screen). More background is in https://github.com/GoogleChrome/lighthouse/issues/291.

**Comment by seantje** [comment]
I get the idea of the check. But a manifest stating (faking) a 192px image as 512px (and thus seemingly sufficient) could be convicted by checking the given image.

**Comment by patrickhulce** [comment]
Ah sorry for the misunderstanding! Yes, we don't look at the images at all right now, I'll go ahead and de-dupe this into https://github.com/GoogleChrome/lighthouse/issues/789.
