### ISSUE TITLE
scoreDisplayMode incompatable with proto enum: not-applicable

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#6201]
#### What is the current behavior?
An audit's `scoreDisplayMode` can be `not-applicable` which is fine in json, but invalid for a proto enum name because of the hyphen.

**Comment by exterkamp** [comment]
@brendankenny brought up a good point to sidestep this issue.  We can rename `not-applicable` to something that can be consistent in both proto and LHR e.g.
- `notapplicable`
- `notApplicable`
- `auditplicable`

something like that.  Thoughts?

**Comment by patrickhulce** [comment]
> auditplicable
😆 we obviously gotta go with this one now, right? 

I like `notApplicable`, personally.

**Comment by paulirish** [comment]
notApplicable wfm
