### ISSUE TITLE
icons.isPNG() should not test extension

### ISSUE THREAD

**Issue by feliperohdee** [GoogleChrome/lighthouse#6208]
This issue is related to this code segment:

https://github.com/GoogleChrome/lighthouse/blob/6a10dd46aab1d7f220761afbe2921e1804d3c3c6/lighthouse-core/lib/icons.js#L75

For systems which generates PWA's and uses dynamic icon generation, via image url's arguments (like: https://somecdn.com/iconsrc/192x192), are having their score reduced at PWA section. Even using PNG images, with the right size, but without ".png" extension.

Lighthouse should consider just typehint, but not extension.

**Comment by patrickhulce** [comment]
It seems like this was a recent, purposeful change (#6024), though I agree it seems odd that we say the icon *must* have a `.png` extension. @exterkamp were there some extra circumstances we're missing? :)

**Comment by exterkamp** [comment]
Thanks for calling this out.  In the changes I made I think I tried to match the filtering conditions as they were, but we had made an effort to match Chrome but must have missed this edge case.  Opened a PR to fix!

[Relevant Chrome code](https://cs.chromium.org/chromium/src/chrome/browser/installable/installable_manager.cc?sq=package:chromium&dr=CSs&g=0&l=88)

**Comment by feliperohdee** [comment]
Cool! Thank you guys!
