### ISSUE TITLE
DevTools Error: an unexpected driver error occurred

### ISSUE THREAD

**Issue by izifortune** [GoogleChrome/lighthouse#6227]
**Initial URL**: https://tlrbbdg64b.execute-api.eu-central-1.amazonaws.com/production/ie/en/trip/flights/passengers
**Chrome Version**: 69.0.3497.100
**Error Message**: an unexpected driver error occurred
**Stack Trace**:
```
Error: an unexpected driver error occurred
    at sendCommand.then.result (chrome-devtools://devtools/remote/serve_file/@8920e690dd011895672947112477d10d5c8afb09/audits2_worker/audits2_worker_module.js:1008:252)
```

**Comment by exterkamp** [comment]
This has been fixed in #6089 but isn't in Chrome yet.  If you are still seeing this error you can try this in Chrome canary and see if it persists or run Lighthouse with the CLI or extension which should already have these changes.  Thanks!
