### ISSUE TITLE
Lighthouse stuck using Chrome from incorrect location

### ISSUE THREAD

**Issue by caraya** [GoogleChrome/lighthouse#625]
I'm running lighthouse in Node 6.0 and 6.5. When I try to run 

`npm explore -g lighthouse -- npm run chrome`

I get the following error:

```
Using Chrome Canary from path /Users/caraya/.Trash/Google Chrome Canary.app
You must install Google Chrome Canary to use lighthouse
You can download it from https://www.google.com/chrome/browser/canary.html
```

I've tried multiple solutions:

Remove the Trash folder
Uninstall and reinstall Chrome

Neither of them fix the problem. 

Is there any way to reset the location of Chrome for Lighthouse?

**Comment by paullewis** [comment]
Interesting, looks like we use lsregister (https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/scripts/launch-chrome.sh#L6) to locate the correct version of Chrome. I imagine it's a case of flushing that somehow, but I'm not at all sure how. I'll see if I can find anything.

**Comment by caraya** [comment]
managed to get it running by killing and reseeding the lsregister database (drastic, I know but I need Lighthouse working more than I need to open SVG files right now) . 

Now I get this error and Lighthouse hangs in the terminal. 

```
$ npm explore -g lighthouse -- npm run chrome

> lighthouse@1.1.2 chrome /Users/caraya/.nvm/versions/node/v6.0.0/lib/node_modules/lighthouse
> lighthouse-core/scripts/launch-chrome.sh

Using Chrome Canary from path /Volumes/Google Chrome Canary/Google Chrome Canary.app
2016-08-31 15:53:59.213 Google Chrome Canary[2181:12378] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7ff75bf2c370>. Break on NSLog to debug.
2016-08-31 15:53:59.213 Google Chrome Canary[2181:12378] Call stack:
(
    "+callStackSymbols disabled for performance reasons"
)
```

**Comment by paulirish** [comment]
> npm explore -g lighthouse -- npm run chrome

...will run chrome, but not fork it into a different process, so you'd have to ctrl-c to get your prompt back. ;)

so, you'll want to run that in a diff terminal tab or whathaveyou :)

thanks for reporting your issues though! we'll get you up and running.

**Comment by wardpeet** [comment]
We could add another check when lsregister fails to see if we can do some manual steps to find chrome?

**Comment by paulirish** [comment]
yah sg.

there are other "launch chrome" npm modules, though i think they are all fairly naive. cc @hemanth

**Comment by hemanth** [comment]
Time to make a node module? 🤔  [Probally two: `chrome-canary-path`; `launch-chrome-debug` ?]

For now putting in the `bg` like: `npm explore -g lighthouse -- npm run chrome&` would avoid us from switching tabs?

**Comment by wardpeet** [comment]
background would be nice :)

**Comment by caraya** [comment]
If I run lighthouse from a second terminal it works. Opening a second window is not an intuitive solution.  I don't recall this happening in earlier versions. 

I'll document the workaround and wait for a full fix :-)
