### ISSUE TITLE
Error running Lighthouse from the command line

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#626]
Running `npm explore -g lighthouse -- npm run chrome` I get the following:

```
> lighthouse@1.1.2 chrome /usr/local/lib/node_modules/lighthouse
> lighthouse-core/scripts/launch-chrome.sh

Using Chrome Canary from path /Applications/Google Chrome Canary.app
2016-09-01 10:36:39.054 Google Chrome Canary[4679:24648] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7f8d06f8e220>. Break on NSLog to debug.
2016-09-01 10:36:39.054 Google Chrome Canary[4679:24648] Call stack:
(
    "+callStackSymbols disabled for performance reasons"
)
```

...and then after a while, I get this:

`lighthouse-core/scripts/launch-chrome.sh: line 5:  4679 Illegal instruction: 4  "$CHROME_CANARY_EXEC_PATH" --remote-debugging-port=9222 --no-first-run --user-data-dir=$TMP_PROFILE_DIR $CHROME_ARGS "about:blank"`

Have I missed something, or is this a bug?

**Comment by wardpeet** [comment]
first thing is correct. What do you mean after a while? Just keeping it open or are you using chrome canary?

**Comment by samdutton** [comment]
I run `npm explore -g lighthouse -- npm run chrome`, I get the (first) message, then a window opens in Canary. 

In the terminal I don't get back to a prompt in the terminal (should I?)

After a couple of minutes, I get the error message.

Just realised I can get this to work by pressing Ctrl-C after `pm explore -g lighthouse -- npm run chrome`.

**Comment by brendankenny** [comment]
Hopefully this is clearer now after #628

**Comment by paulirish** [comment]
We're also looking into launching chrome as a background process and tearing it down afterwards. 

Will make for a cleaner experience.
