### ISSUE TITLE
Sites hitting 45s pageload timeout

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6272]
These URLs pulled from some LR logs. They all reliably hit the 45 timeout

* http://asiaherbassociation.com/en/ (maybe its the 8 youtube embeds?)
* http://www.freedirectory.yonola.com (looks like there's a hanging network request that never times out)
* https://www.expedia.com/Las-Vegas-Hotels-Mandarin-Oriental.h3016186.Hotel-Information?chkin=10/14/2018&chkout=10/20/2018&rm1=a2
* https://www.eltern.de
* http://www.skimmelfrit.dk
* http://www.jessicaadams.com
* http://ouc.com
* http://nosybesesiles.com/galleries/radama-lodge/
* http://ceylonskiychay.ru
* http://autotintexpress.ca
* ~https://ilkayuyarkaba.av.tr/tag/istifaya-zorlanan-iscinin-kidem-tazminati NET::ERR_CERT_SYMANTEC_LEGACY prevents the load. But we don't recognize the problem and we hang permanently at "Retrieving devtoolsLog and network records"~  split out as #6287

**Comment by patrickhulce** [comment]
I've gone through the URLs and think a generic 10s max TTFB timeout would solve most of this class of problems, i.e. if we hear nothing back from a request for 10s we treat it as failed for the purposes of network quiescence. Unfortunately, that doesn't work for the case where a page needs a script for DCL. Not really sure what to do about it other than some separate DCL timeout that's much less than 45 seconds.

Details of each URL found below (lots were not reproducible on my machine on master, @paulirish were these logs taken from the version of LH that didn't have the frame hanging fix already?)


> http://asiaherbassociation.com/en/

Intermittently reproducible. When it does hang, it is indeed the 8 youtube embeds not receiving any response.

> http://www.freedirectory.yonola.com 

Never reaches DCL, http://stats.extrawatch.com/agent.js.php?projectId=3967&env=ExtraWatchNoCMSEnv never responds.

> https://www.expedia.com/Las-Vegas-Hotels-Mandarin-Oriental.h3016186.Hotel-Information?chkin=10/14/2018&chkout=10/20/2018&rm1=a2

Unable to reproduce locally.

> https://www.eltern.de

Unable to reproduce locally, though it is slow loading.

> http://www.skimmelfrit.dk

Unable to reproduce locally.

> http://www.jessicaadams.com

Unable to reproduce locally.

> http://ouc.com

Unable to reproduce locally.

> http://nosybesesiles.com/galleries/radama-lodge/

Unable to reproduce locally.

> http://ceylonskiychay.ru

Unable to reproduce locally.

> http://autotintexpress.ca

Unable to reproduce locally, though it is slow loading.

**Comment by patrickhulce** [comment]
I'm still going through some, but I'm afraid most of this is LR-specific. Only 2 of the first 70 in @paulirish's bigger list even take 45s or more for the entire LH run locally, let alone just waiting for page load. In fact, 50% finish the entire LH run with all categories in under 20s, and 82% finish in under 30s.

### Interesting Cases so Far
- http://silvertipp.ca, just wrecks all our audits (appcachemanifest gatherer takes 23s??) before it just dies on optimized images
- http://hayunalesbianaenmisopa.com/, takes ~60s for the LH run, HELLA slow loading root document
- https://www.newnetmarket.com/, RobotsTxt and StartURL gatherers take ~5s each

**Comment by Hoten** [comment]
@patrickhulce, how did you bulk run + gather timing details for all the URLs?

**Comment by patrickhulce** [comment]
```bash
#!/bin/bash

for url in $(cat url-list.txt); do
  echo "URL is: $url";
  echo "Running...";

  exec 3>&1 4>&2
  time_taken=$( { time yarn start $url 1>&3 2>&4; } 2>&1 )  # Captures time only.
  exec 3>&- 4>&-

  echo "Time taken: $time_taken"
  echo "$url $time_taken" >> results.txt
done
```

**Comment by patrickhulce** [comment]
Alright ran the entire batch @paulirish gave me that failed in LR. Here's the breakdown.

43% complete in under 20s
83% complete in under 30s
97% complete in under 45s

Of the new cases that didn't finish in under 45s...

- http://www.despachoidc.com/, one render-blocking script never returns so it waits on FCP real long time
- https://sinaloa.gob.mx/, main document takes ~15s to reply, just hella slow page
- https://www.check24.de/handytarife/allnet-flat, page takes 20s to load, axe takes 30s+
- https://www.iconshock.com/icons/5_1_speaker_system-icon.html, page takes 40s to load, axes takes 1m+

I'll dig into the axe specific slowness and file bugs upstream, but there's no more obvious hanging network quite issues like the iframe and cert ones :/

**Comment by patrickhulce** [comment]
I've filed a few axe issues to capture the offenders here, but the 45s timeout appears to be LR-specific. I consider this investigation closed, but if there's more I can do here, please let me know :)
