### ISSUE TITLE
TTI Metric in PWA & performance reports do not match

### ISSUE THREAD

**Issue by mdiblasio** [GoogleChrome/lighthouse#6284]
#### Provide the steps to reproduce
1. Run LH on https://swipelife.tinder.com/

#### What is the current behavior?
TTI in [PWA report (11s) and performance report (5s)](https://www.webpagetest.org/lighthouse.php?test=181002_RA_de2324bbe18d4bbf3f3f5790456d08b9&run=1#pwa) do not match, making it unclear if the metric is measured different in each report (e.g. is throttling different? Does TTI in performance not take into account network requests?)

#### What is the expected behavior?
TTI should match

#### Environment Information
* Affected Channels: 
* Lighthouse version:  3.2.0 
* Node.js version:
* Operating System:

**Comment by patrickhulce** [comment]
Thanks for filing! How did you run lighthouse @mdiblasio? The audit is making sure your TTI is fast enough *on mobile networks* so if you didn't run with one of our approved presets the numbers will be different.

**Comment by exterkamp** [comment]
We might want a visual indication between the two TTI's if they are derived with different methods.  I know I was confused by this since they are different.  Something like this on the audit's TTI explanation:
`Interactive (on Simulated Mobile Network) at 11s` vs just `Interactive at 11s`

**Comment by cheneytsai** [comment]
This was run through WPT (Moto G4, Chrome, 3G, Dulles) which under my understanding should run LH with the same conditions which in this case is a 3G network. This results in the following metrics:

First Interactive (WPT): >5.9s
Time to Interactive (LH - Performance): 5.0s
Interactive on 3G (LH - PWA): 11s

[Webpagetest Link](https://www.webpagetest.org/result/181002_RA_de2324bbe18d4bbf3f3f5790456d08b9/)

**Comment by patrickhulce** [comment]
Thanks for sharing the report @cheneytsai! 

#6162 and #6286 should help with some of the problems here. Locally, simulated performance reflect WPT results quite accurately, but in the load-fast-enough-for-pwa we're double throttling the CPU which is probably what's inflating the numbers. I'll do a followup to #6286 to fix this.

![image](https://user-images.githubusercontent.com/2301202/47055068-34b10880-d17b-11e8-9c02-2990ab9c7e3d.png)
