### ISSUE TITLE
Site receiving errors for Performance metrics on mobile

### ISSUE THREAD

**Issue by WackoMako** [GoogleChrome/lighthouse#6291]
My site moving2ireland.com receives errors for every metric under performance when testing for mobile. Why doesn't it audit my site properly?

**Comment by WackoMako** [comment]
Here is the JSON file 
[moving2ireland.com-20181016T134124.zip](https://github.com/GoogleChrome/lighthouse/files/2483077/moving2ireland.com-20181016T134124.zip)

**Comment by patrickhulce** [comment]
@WackoMako thanks for filing! I'm able to get a clean run of that URL. The error you're seeing can sometimes occur if the page is occluded by other windows or if Chrome messes up recording the information we need. How are you running LH? CLI/DevTools/Extension? Are you doing so in a clean Chrome profile?

![image](https://user-images.githubusercontent.com/2301202/47022711-b5441a80-d123-11e8-9217-c40a337d7046.png)

**Comment by exterkamp** [comment]
I can get clean runs on v4.0.0-beta.  As well as on pagespeed and on web.dev, is this reproducible?
