### ISSUE TITLE
Lighthouse batch run unable to kill children 🗡👶🗡

### ISSUE THREAD

**Issue by RemcoTensen** [GoogleChrome/lighthouse#6306]
I'm trying to run a simple Lighthouse batch, but warnings appear at random, cancelling the output of the URL it's currently working on, then moving on to the next URL in the list.

Like I said: the timing and URL's are completely random. It might run a batch without errors, or that same batch might decide to throw errors.

We used all the different versions of node and Lighthouse, and ran the script on several systems. We also used different URL formats and checked if anything went wrong during the specific audit.

Odd thing is: I've got one Windows 10 system that DOESN'T appear to get these errors. There's nothing special about it and it uses the exact same install, network, user rights, versions, script and URL list as far as I can tell (I checked with the system administrator). I'm lost here?

It's a bit annoying, because I want to run the batch myself without missing files.

The script is a simple .bat script that reruns the Lighthouse process using an URL list textfile. There are no errors in it, no spaces, wrong minusses or other things that shouldn't be in there and we used lighthouse --help.

Here are the warnings from the command console in full view:

```
ChromeLauncher Killing Chrome instance 10784 +44ms

ERROR: The process with PID 8384 (child process of PID 10784) could not be terminated.

Reason: There is no running instance of the task.

ERROR: The process with PID 11208 (child process of PID 10784) could not be terminated.

Reason: There is no running instance of the task.

  ChromeLauncher:warn Chrome could not be killed Command failed: taskkill /pid 10784 /T /F

  ChromeLauncher:warn ERROR: The process with PID 8384 (child process of PID 10784) could not be terminated.

  ChromeLauncher:warn Reason: There is no running instance of the task.

  ChromeLauncher:warn ERROR: The process with PID 11208 (child process of PID 10784) could not be terminated.

  ChromeLauncher:warn Reason: There is no running instance of the task.

  ChromeLauncher:warn  +201ms

  ChromeLauncher Killing Chrome instance 10784 +1ms

ERROR: The process with PID 10912 (child process of PID 10784) could not be terminated.

Reason: There is no running instance of the task.

ERROR: The process with PID 9396 (child process of PID 10784) could not be terminated.

Reason: There is no running instance of the task.

ERROR: The process with PID 8384 (child process of PID 10784) could not be terminated.

Reason: There is no running instance of the task.

ERROR: The process with PID 11208 (child process of PID 10784) could not be terminated.

Reason: There is no running instance of the task.

ERROR: The process with PID 10784 (child process of PID 10900) could not be terminated.

Reason: There is no running instance of the task.

  ChromeLauncher:warn Chrome could not be killed Command failed: taskkill /pid 10784 /T /F

  ChromeLauncher:warn ERROR: The process with PID 10912 (child process of PID 10784) could not be terminated.

  ChromeLauncher:warn Reason: There is no running instance of the task.

  ChromeLauncher:warn ERROR: The process with PID 9396 (child process of PID 10784) could not be terminated.

  ChromeLauncher:warn Reason: There is no running instance of the task.

  ChromeLauncher:warn ERROR: The process with PID 8384 (child process of PID 10784) could not be terminated.

  ChromeLauncher:warn Reason: There is no running instance of the task.

  ChromeLauncher:warn ERROR: The process with PID 11208 (child process of PID 10784) could not be terminated.

  ChromeLauncher:warn Reason: There is no running instance of the task.

  ChromeLauncher:warn ERROR: The process with PID 10784 (child process of PID 10900) could not be terminated.

  ChromeLauncher:warn Reason: There is no running instance of the task.

  ChromeLauncher:warn  +265ms

(node:10900) UnhandledPromiseRejectionWarning: Error: Chrome could not be killed Command failed: taskkill /pid 10784 /T /F

ERROR: The process with PID 10912 (child process of PID 10784) could not be terminated.

Reason: There is no running instance of the task.

ERROR: The process with PID 9396 (child process of PID 10784) could not be terminated.

Reason: There is no running instance of the task.

ERROR: The process with PID 8384 (child process of PID 10784) could not be terminated.

Reason: There is no running instance of the task.

ERROR: The process with PID 11208 (child process of PID 10784) could not be terminated.

Reason: There is no running instance of the task.

ERROR: The process with PID 10784 (child process of PID 10900) could not be terminated.

Reason: There is no running instance of the task.

 

    at Promise (C:\Users\remco\AppData\Roaming\npm\node_modules\lighthouse\node_modules\chrome-launcher\dist\chrome-launcher.js:255:28)

    at new Promise (<anonymous>)

    at Launcher.kill (C:\Users\remco\AppData\Roaming\npm\node_modules\lighthouse\node_modules\chrome-launcher\dist\chrome-launcher.js:237:16)

    at Object.<anonymous> (C:\Users\remco\AppData\Roaming\npm\node_modules\lighthouse\node_modules\chrome-launcher\dist\chrome-launcher.js:58:29)

    at Generator.next (<anonymous>)

    at C:\Users\remco\AppData\Roaming\npm\node_modules\lighthouse\node_modules\chrome-launcher\dist\chrome-launcher.js:12:71

    at new Promise (<anonymous>)

    at __awaiter (C:\Users\remco\AppData\Roaming\npm\node_modules\lighthouse\node_modules\chrome-launcher\dist\chrome-launcher.js:8:12)

    at Object.kill (C:\Users\remco\AppData\Roaming\npm\node_modules\lighthouse\node_modules\chrome-launcher\dist\chrome-launcher.js:53:28)

    at potentiallyKillChrome (C:\Users\remco\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\run.js:184:29)

(node:10900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

(node:10900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by wardpeet** [comment]
Could you maybe show us your bat file or tell us how your call lighthouse so we could try to reproduce it.

Which chrome version are you trying or which should we try? Can you try to run it in sequence instead of parallel.

**Comment by patrickhulce** [comment]
FWIW, we also intermittently experience similar error messages in our appveyor tests that don't seem to have a rhyme or reason for their occurrence :/

It's been relatively difficult and painful for us to debug appveyor though, so if you've got a reproducible environment where this is happening any extra info like what @wardpeet was asking for would be great!

**Comment by RemcoTensen** [comment]
We used this in a bat:

@echo on
for /f "delims=" %%a in (.\urlList.txt) DO (
ECHO Line is: %%a
lighthouse --quiet --output json --output html --output-path=./%%~nxa.json --chrome-flags="--headless" %%a
)

We tried all sorts of things. Changed every variable we could come up with, including browser and node versions. Also tried script changes like for example: wmic process where name="chrome.exe" call terminate

Just ran this on my Windows 10 laptop with latest versions of Chrome and node LTS and admin rights, and after several hours of running it consistently threw the warning and just stopped output at 350 files.

Our sys admin checked and the system that runs it without problems seems to use almost exactly the same setup. He couldn't find relevant differences in versions etc.

It might be worth noting that we had to include HTML file output, otherwise it wouldn't produce the named JSON files like we asked.

I tried lighthouse-batch but due to the char limit in command I decided to go this way.

**Comment by RemcoTensen** [comment]
I'll try running in sequence and give the exact version numbers for the system I'll be using tomorrow. I'm from the Netherlands so it'll have to wait.

**Comment by wardpeet** [comment]
> It might be worth noting that we had to include HTML file output, otherwise it wouldn't produce the named JSON files like we asked.
that's interesting

 > I'll try running in sequence and give exact version numbers tomorrow. I'm from the Netherlands so it'll have to wait.
No worries, I'm from belgium so I might be able to answer during daytime

**Comment by RemcoTensen** [comment]
Currently I'm sitting behind:
Lighthouse version 3.2.1
Chrome 69 on Windows 10
node.js 8.12.0 LTS

I'll now update Chrome to 70, let's see if that changes anything.

Thanks for helping my zuiderbuur!

**Comment by patrickhulce** [comment]
@RemcoTensen, I wonder if it's just the Chrome process juggling it's having a problem with or it's something more nefarious that this error is just masking.

Do things improve if you launch Chrome yourself oncee and just tell Lighthouse to use the port that's open?

It'd probably look something like 

### Separate window to inspect logs
`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222 --user-data-dir=some-madeup-temp-folder`

### Replace LH call in your script
`lighthouse --port=9222 <url>`

Make sure you'd be doing this serially as @wardpeet suggested.

**Comment by RemcoTensen** [comment]
The good news is: the warnings didn't show.
The bad news is: I got no file output either, and exception warnings popped up randomly.

Example: offscreen-images:warn Caught exception: NO_FCP

**Comment by patrickhulce** [comment]
Hm, no file output? Like there was an error on completion, or LH didn't log the file path at all, or LH did log the file path but the file wasn't there?

NO_FCP is a gnarly beast that has been popping up more and more lately on newer versions of Chrome. That's probably an unrelated issue, but if we resolve the file output and this is only intermittently present I'd bet that's a separate investigation and you're setup is mostly OK.

**Comment by RemcoTensen** [comment]
Everything else seemed ok. Just the files missing.

**Comment by patrickhulce** [comment]
LH didn't log the file path at all? Or LH did log the file path but the file wasn't where it said it would be?

**Comment by RemcoTensen** [comment]
I didn't notice anything different about how the process was displayed, apart from what I've told you, but it could be that I overlooked it. I'll double check when I'm back at the office.

**Comment by wardpeet** [comment]
i've tested your script with around 30 urls and no errors here :'(

I copied your bat file and just ran it's running on canary though.

**Comment by RemcoTensen** [comment]
Not at a workstation today. I'll check in tomorrow.

**Comment by Olti-B** [comment]
Same error here, to me it is happening when i am trying to run multiple instances, kind of multiple audits

**Comment by paulirish** [comment]
This is a bug for lighthouse-batch. please file with that project. @mikestead

**Comment by justingolden21** [comment]
@paulirish  was this ever fixed? I'm still encountering this on latest lighthouse in 2021.

**Comment by alitoufighi** [comment]
Any 2022 solutions to kill children?!
