### ISSUE TITLE
configSettings.output can be list or string

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#6309]
#### What is the current behavior?
LHR `configSettings.output` can be either a string or a list.  For convergence with proto it needs to be one or the other.

**Comment by brendankenny** [comment]
it's [always an array from the CLI](https://github.com/GoogleChrome/lighthouse/blob/3d5037ade1b0b62b6bfe89642ba0e20904809df2/typings/externs.d.ts#L156), so we'd just need to correct the module uses. It's marginally more annoying to use an array there, but not so bad.

It looks like all the client entry points all use the string version, and we'd need to update the default in `constants.js`.

**Comment by patrickhulce** [comment]
I'd also argue if we're converting it to always array that we should change the name to `reports` :)
