### ISSUE TITLE
lighthouse-logger improvments

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#6313]
It's kind of annoying to update lighthouse-logger, but there are some rough edges that we'd like to smooth out. Came up in #6297:

- [x] Some way to query what the logging level is. Not usually needed, but sometimes you really want to skip work for `verbose`-only logs (e.g. querying things, slicing strings, etc) when it's not needed.
- [ ] logging level in between `verbose` and `default` (`debug` or `info` perhaps?) that doesn't contain every protocol message

**Comment by Hoten** [comment]
+1 for the first point. I was going to add some verbose timing around driver.sendCommand, but saw that I couldn't query the log level to prevent creating Dates unnecessarily.

**Comment by brendankenny** [comment]
one other design idea:
the method mentioned above, it could be used like
```js
if (logger.level === 'verbose') { // or whatever
  const logValue = expensiveCalculation();
  log.verbose('Thing', logValue);
}
```

or we could extend logger to take functions that are only called by lighthouse-logger itself
```js
log.verbose('Thing', _ => expensiveCalculation());
```
and if not at a verbose level, then that function would never be run

The benefit would be (I think) less work on the caller side. The downside is it might obscure what's going on. It might also just be unusual enough that it's dumb :)

@patrickhulce if you have thoughts

**Comment by Hoten** [comment]
I will also expose the time entries to help with #3745.

**Comment by brendankenny** [comment]
First one is long done, haven't needed the second one since then, so no need to track it with an issue :)
