### ISSUE TITLE
cli: fix --help/readme to say output paths for multiple report types is supported

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6333]
Ran into this limitation when I was a LH user. There is currently no way to specify the output path if you wish to receive multiple report formats.

Suggested interface:

```
lighthouse https://www.cnn.com --output json,html --output-path out/my-lhr.json,out/my-other-lhr.csv
```

**Comment by brendankenny** [comment]
you can specify a path for all of them, just not individual paths. If calling on the CLI, it seems trivial to do `--output-path path/my-lhr` and get `path/my-lhr.report.json`, `path/my-lhr.report.csv`, `path/my-lhr.report.html`, then move them if you really want a completely custom name.

**Comment by brendankenny** [comment]
oh, ha, yeah :( that's hilariously out of date
