### ISSUE TITLE
Lighthouse doesn't handle OOPIFs

### ISSUE THREAD

**Issue by oddui** [GoogleChrome/lighthouse#6337]
This is a question and maybe an issue.

I was looking at chrome devtools websocket connection to chrome and noticed it does some target discovery work to get request data for iframes. The image below shows chrome devtools uses `Target.sendMessageToTarget` to send `Network.enable` to a discovered target. It then receives data in `Target.receivedMessageFromTarget` event.

![image](https://user-images.githubusercontent.com/720036/47135703-12df8f00-d2fd-11e8-94ee-03033f7b9b48.png)

I also tried to look at source code in the `lighthouse/lighthouse-core/gather` folder but i couldn't see it doing the target discovery thing.

Does that mean lighthouse can only see and analyse requests from the maim frame?

**Comment by oddui** [comment]
@patrickhulce that's great to hear.

Can I ask why you specifically say **out-of-process-iframes**? Are there any in-process-iframes?

The reason I ask is that sometimes I do seem to get requests from iframes by just sending `Network.enable` to a target, using the chrome-remote-interface library. However I don't get those requests from iframes using the chrome extension debugger API. 😕

**Comment by patrickhulce** [comment]
You can [read a little more](https://www.chromium.org/developers/design-documents/site-isolation) about [OOPIFs](https://www.chromium.org/developers/design-documents/oop-iframes) if you're curious, but basically cross-origin frames have been slowly moved to their own separate processes distinct from the main frame's process (site isolation). A couple of wins from this are isolating performance from misbehaving frames and security benefits to mitigate spectre-style attacks.

When the frames were all in the same process, we got all the network information just be listening to the main target/process. Now that they are separate processes we need to be listening to all the targets to get all the network information. AFAIK, we should still be getting information from frames that aren't OOP.

**Comment by paulirish** [comment]
@patrickhulce i spoke with dgozman and he said it's not ready yet. Currently the Browser domain is flattened, but Page is still in progress. ~4w from now we can check in again.

Here's the implementation issue: https://bugs.chromium.org/p/chromium/issues/detail?id=775132

**Comment by paulirish** [comment]
update: dgozman sez the implementation is good enough for us to use the new flattened target mgmt.

He does note the structure of service worker targets will change soon, though.
