### ISSUE TITLE
DevTools Error: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by wertpokler** [GoogleChrome/lighthouse#6345]
**Initial URL**: https://www.myfreecams.com/
**Chrome Version**: 69.0.3497.95
**Error Message**: Cannot read property 'value' of undefined
**Stack Trace**:
```
TypeError: Cannot read property 'value' of undefined
    at sendCommand.then.result (chrome-devtools://devtools/bundled/audits2_worker/audits2_worker_module.js:1008:211)
```

**Comment by exterkamp** [comment]
This error is a duplicate of #6026. I am closing it as such, but if the problem persists comment and we can reopen.
