### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by mkjekk** [GoogleChrome/lighthouse#6375]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 70.0.3538.67
**Initial URL**: chrome-extension://jifpbeccnghkjeaalbbjmodiffmgedin/crxviewer.html?crx=https%3A%2F%2Fclients2.google.com%2Fservice%2Fupdate2%2Fcrx%3Fresponse%3Dredirect%26os%3Dwin%26arch%3Dx86-64%26os_arch%3Dx86-64%26nacl_arch%3Dx86-64%26prod%3Dchromecrx%26prodchannel%3Dunknown%26prodversion%3D70.0.3538.67%26acceptformat%3Dcrx2%2Ccrx3%26x%3Did%253Dmekpfngodchodemgmkhinohkfjefjeea%2526uc&zipname=mekpfngodchodemgmkhinohkfjefjeea.zip
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by patrickhulce** [comment]
Can't audit a chrome-extension with a chrome extension friend :) use audits panel in DevTools instead!
