### ISSUE TITLE
Make updating the golden JSON not painful

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#6405]
This has gotten pretty bad now :)

For many changes, you have to have `protobuf` compiled and installed and run `yarn update:sample-json` and `yarn update:proto`. For any changes to the default config, you also have to run `jest lighthouse-cli/test/cli/index-test.js -u`.

Some ideas:
1) Add `update:proto` to `update:sample-json`. Both json files have to be updated at the same time anyways
2) Sub idea: rename `update:proto` and `build-proto`. It's not updating or building the proto, it's updating the roundtripped sample json :)
3) Remove `protobuf` requirement. Most changes to Lighthouse are going to need to touch the sample json, and asking folks to install this is going to eliminate a lot of potential contributors.
    - @exterkamp mentioned we could have a web service that takes a `sample_v2.json` and returns the proto roundtrip result. We could still verify the valid result in CI (which we really need to do anyways).
    - we could also investigate wasm compiles of protobuf and check the result in. https://github.com/kwonoj/protobuf-wasm has been continually updated to track the latest protobuf release
4) make `sample_v2_round_trip.json` ephemeral, created only to test that it round trips correctly (I believe this was/is the plan for it). We don't generally want to have two identical files checked in, just makes PRs longer and makes it easier to miss stuff.

**Comment by paulirish** [comment]
Great thoughts here.

> Add update:proto to update:sample-json

yes. very much

> Sub idea: rename update:proto and build-proto.

+1 to renaming build-proto to `proto-roundtrip`. 

> make sample_v2_round_trip.json ephemeral

I have a branch where instead of checking in the full pyproto_roundtrip.json we check in the diff of (the pyproto_roundtrip vs samplev2json). It'll be an empty file when the preprocessor is gone.

**Comment by patrickhulce** [comment]
> make sample_v2_round_trip.json ephemeral, created only to test that it round trips correctly

+10 :) can't wait to see the branch @paulirish

**Comment by exterkamp** [comment]
Another idea, we can check-in the generated `_pb2.py` generated proto python file.  Then it wouldn't require installing proto to update the round trip.  Just having python.

**Comment by brendankenny** [comment]
> we can check-in the generated _pb2.py generated proto python file

is that sufficient? We should definitely do that, then! :)

**Comment by brendankenny** [comment]
> is that sufficient?

It looks like not quite. We'd still need `google.protobuf.json_format` and its sub dependencies (but maybe that's doable with just a npm dependency on the protobuff github repo with no compile step)

**Comment by exterkamp** [comment]
Update: 
 - [protobufjs](https://github.com/dcodeIO/protobuf.js) doesn't support well known types [#1042](https://github.com/dcodeIO/protobuf.js/issues/1042)
 - [protobuf/js](https://github.com/protocolbuffers/protobuf/tree/d9ccd0c0e6bbda9bf4476088eeb46b02d7dcd327/js) maps things outside of the [proto3 JSON naming spec](https://github.com/protocolbuffers/protobuf/issues/1904) (e.g. `audit` -becomes-> `auditMap`) and things like that when autogenerating the file and converting to and from objects.

**Comment by brendankenny** [comment]
Heyyyy, we did all this, finished off in #10557
