### ISSUE TITLE
core: show time diffs of pr vs master marks

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6409]
Could collect the timings from the smoke tests, and print out the diff (of the averages) w/ master at the end of the Travis CI build.

Not sure how best to maintain master's timings. Would be annoying to need to update the timings every PR.

**Comment by patrickhulce** [comment]
so uh #6152 might be kinda interesting to ya 😉

**Comment by brendankenny** [comment]
Good to close in favor of #6152 (DZL), then?

Lighthouse runs are noisy enough that I think we'll really need that infrastructure to compare any numbers between two commits.
