### ISSUE TITLE
Viewport description isn't clear why it's failing

### ISSUE THREAD

**Issue by lucas42** [GoogleChrome/lighthouse#641]
I'm getting a "No" for "HTML has a viewport <meta>" despite the site containing:
 `<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />`

Only on inspecting the source code do I see that it's [explicitly looking](https://github.com/GoogleChrome/lighthouse/blob/eb5f0f69c0c9f6102b6fda6a8373dd2a5543e7cf/lighthouse-core/audits/viewport.js#L40) for "width="

Could this be made clearer, so users know what they need to fix?

I also don't fully understand the practical purpose of specifying the width in the viewport.  My PWAs usually look fine just using "initial-scale=1.0".

**Comment by wardpeet** [comment]
This is a fairly good explanation about why width property matters ([A tale of two viewports](http://www.quirksmode.org/mobile/viewports2.html))
Correct me if I'm wrong but the main reason to add width is to make sure that all media queries and viewport calculations are done right with no wrong interpretation by a specific browser

**Comment by lucas42** [comment]
I still can't really work out the practical difference between "initial-scale=1.0" and "initial-scale=1.0, width=device-width" (that article doesn't mention initial-scale) - perhaps my CSS is too simplistic to see any distinction.

**Comment by wardpeet** [comment]
Oh I wasn't talking about initial-scale=1.0 only about width. Initial-scale has nothing to do with viewport width, it only tells the browser how to scale a web page. I think initial-zoom keeps the zoom level intact while rotating (but not sure...)
http://stackoverflow.com/a/22778172

**Comment by dracos** [comment]
I have just come across this because I have a viewport of “initial-scale=1” and Lighthouse says I don’t have a viewport. I did some research into this with the help of others, the conclusion is at https://github.com/h5bp/html5-boilerplate/issues/1099#issuecomment-12215210 – in summary width=device-width is basically not a requirement and was actually the cause of confusion of rotational issues because people did not realise that device-width was fixed to the portrait width in iOS (yet overridden by initial-scale).

I have a viewport and it is fine, so I think Lighthouse should not fail this test :) PR at #1267 that also updates the error message, and allows spacing.

**Comment by ebidel** [comment]
One interesting thing about `width=device-width` (and perhaps why we check for it) is that Chrome Android <= 53 required it to hit GPU Rasterization fast paths. As of Chrome 54, any meta viewport will work! CSS `@viewport` can also be used.

https://www.chromium.org/developers/design-documents/chromium-graphics/how-to-get-gpu-rasterization

**Comment by dracos** [comment]
"Chrome Android <= 53 required it to hit GPU Rasterization fast paths” – hohum :-/ (Lighthouse is not checking for minimum-scale being set, so I don’t think it can be that.)
"As of Chrome 54, any meta viewport will work!” – goodo!

**Comment by ebidel** [comment]
Right. I only mention it because there seemed to be some controversy about
using width but it was actually a really good thing for performance. At
least in chrome. Now that you can you any viewport settings, we can
probably be more flexible about what we check.

**Comment by wardpeet** [comment]
maybe we should just check on one of these values (https://drafts.csswg.org/css-device-adapt/#viewport-meta) and @viewport rules like @ebidel mentioned. 

// cc @paullewis
