### ISSUE TITLE
Add a net-internals gatherer

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#643]
Not sure how we get this data, however it would be very valuable.

**Comment by deepanjanroy** [comment]
I think that's netlog. It's available through tracing data, if we turn on the category `netlog`. You can see it in chrome://tracing: 
![screen shot 2016-09-13 at 6 19 38 pm](https://cloud.githubusercontent.com/assets/3505637/18493509/f0400eee-79de-11e6-998e-a92b722c9c7d.png)

**Comment by paulirish** [comment]
Aye. adding "netlog" into the categories in driver/driver.js get us a bunch of data. I'm not 100% sure it's the exact same as an export from net-internals, but in all likelihood it is.

What do we do with the data once we have it?

**Comment by deepanjanroy** [comment]
(Aside: just verified it is indeed the same data. https://cs.chromium.org/chromium/src/net/log/trace_net_log_observer.cc?l=25 adds the netlog observer, and https://www.chromium.org/developers/design-documents/network-stack/netlog talks about chrome://net-internals)
