### ISSUE TITLE
Error on FCP, FMP, and TTI

### ISSUE THREAD

**Issue by ohnananaomi** [GoogleChrome/lighthouse#6430]
**Summary**
Experiencing an issue where "Error!" is always displayed on FCP, FMP, and TTI, regardless of the actual website and response rate of the website being audited, but only with the specific device and environment mentioned below. Tried to run the test on a different Ubuntu device without dual boot, as well as Windows and Mac and actual values were displayed.

Replicated the issue on the device both with the same and different network connections and on different time of the day. Observed the issue for about a month now. (_please see sample screenshot of the issue below_)

![image](https://user-images.githubusercontent.com/6814455/47706974-853d6100-dc65-11e8-9c80-2c6b64c08ad5.png)

**Environment**
OS: Ubuntu 16.04 LTS
Chrome version: 69.0.3497.100 (Official Build) (64-bit)
Device: ASUS VivoBook X405U (with dual boot - Windows/Linux

**Steps to replicate**
1. Launch Chrome on Ubuntu (device should be on dual boot instead of VM)
2. Visit any website (target website to test is http://edukasyon.ph/)
3. Run Lighthouse
- Device: Desktop
- Audits: Performance and Best practices
- Throttling: No throttling
- Clear storage: yes
4. Run audit

**Expected output**
Values (in milliseconds) should be displayed after running the audit on different websites if it hasn't reached timeout. (_please see sample screenshot below_)
![image](https://user-images.githubusercontent.com/6814455/47711274-d0f50800-dc6f-11e8-969d-ca7234281201.png)

**Actual output**
Please see summary above

**Comment by patrickhulce** [comment]
Thanks for reporting @ohnananaomi! We've also struggled to replicate what seems to be this normally rare error occurring regularly in certain environments. Could you try downloading latest Chromium and seeing if that fixes the issue? https://download-chromium.appspot.com/

**Comment by ohnananaomi** [comment]
Thanks for the assistance, @patrickhulce! I'm happy to let you know that the suggested solution worked. Values are now displayed for FCP, FMP, and TTI. I'll be using Chromium instead of Chrome on Linux moving forward. Thanks again! :)
