### ISSUE TITLE
report(font-size): improve how inline style tags are displayed

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#6435]
```
lighthouse https://www.haaretz.com/ --only-audits=font-size
```

![image](https://user-images.githubusercontent.com/4071474/47820193-07875d00-dd1a-11e8-8144-92d911e49003.png)

```
/:48:272
```

refers to the 48th line, 272nd column of _some_ inline `style` tag. Which? who nose.

**Comment by connorjclark** [comment]
ditto https://github.com/GoogleChrome/lighthouse/issues/5626#issuecomment-569371039

**Comment by paulirish** [comment]
its good now thx to connor's source-location. 
![image](https://user-images.githubusercontent.com/39191/114465717-577dd580-9b9c-11eb-879e-10bd763ec38c.png)
