### ISSUE TITLE
Reports not rendering in Edge

### ISSUE THREAD

**Issue by codepo8** [GoogleChrome/lighthouse#6444]
#### Provide the steps to reproduce
1. Run LH on christianheilmann.com (or whatever)

#### What is the current behavior?

The generated report doesn't render on Edge as there is a JavaScript error
![lighthouse-bug](https://user-images.githubusercontent.com/13508/47838519-ec672c80-ddaf-11e8-80ea-5b6afe890ba7.PNG)
![renderer](https://user-images.githubusercontent.com/13508/47838518-ebce9600-ddaf-11e8-9603-db22fe8825cd.png)

#### What is the expected behavior?

You can read the report

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 3.2.1
* Node.js version: 10.9.0
* Operating System: Windows 10

**Related issues**

**Comment by paulirish** [comment]
@codepo8 thanks for reporting. We're fixing this along with a few more Edge compat issues.

FWIW, This particular item stems from a spec violation on exceptions thrown from the `URL()` constructor. I've filed here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19498561/

**Comment by codepo8** [comment]
Excellent, thank you!
