### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache

### ISSUE THREAD

**Issue by techtic-mukesh** [GoogleChrome/lighthouse#6450]
**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 70.0.3538.77
**Initial URL**: https://www.alexandersparks.com/
**Error Message**: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18402:11)
```

**Comment by patrickhulce** [comment]
Thanks for reporting @techtic-mukesh!

**Comment by patrickhulce** [comment]
deduping into #6512

**Comment by charlesmorgan40** [comment]
Network.clearBrowserCache
