### ISSUE TITLE
core: expand timings for LR/CLI entry points

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6458]
`timing.total` is set to the duration of `lh:runner:run` in `lighthouse-core/runner.js`. However, this misses  some things in the CLI / Extension / LR entry points, such as configuration parsing and proto stuffs.

1) add more timing marks for each client's entry point, including one that is all encompassing
2) overwrite `timing.total` with the all encompassing mark for each entry point

**Comment by Hoten** [comment]
Broadening the `timing.total` coverage will help us determine how much time the render server takes doing LH stuff, vs doing other things. We feel like there isn't too much work being done outside LH, but want to measure and be sure.

**Comment by brendankenny** [comment]
right, total makes sense. It's the other timing marks I'm wondering about.

Is this just for LR, then?

**Comment by Hoten** [comment]
There doesn't seem to be a good way to do this, because the timings are collected in `runner.js` which is a few layers away from the CLI/LH entries.

I've considered:

a) allow for disabling collection of timings in the runner, for purposes of doing the work after calling `lighthouse-core`, so that the additional timings are collected. Basically, call `_getTiming` in the entry point module.

b) manually push additional timings into `lhr.timing.entries`, which is problematic since marky uses [an internal timing method](https://github.com/nolanlawson/marky/blob/master/src/now.js#L13) that the module does not export.

**Comment by Hoten** [comment]
Closing because more trouble than it's worth :)
