### ISSUE TITLE
Double device emulation when using Lighthouse against a device

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#646]
[Lighthouse w/ mobile devices](https://github.com/GoogleChrome/lighthouse/blob/master/readme.md#lighthouse-w-mobile-devices) works well.

However if you leave out `--mobile false` then we'll emulate the DPR and viewport of a mobile device **while we're on** a mobile device. weird but it actually works. No severe concerns, though I bet compositing performance suffers some.

`--mobile false` fixes this, but it also disables network throttling.  It shouldn't.

our `enableNexus5X()` does a few things: 
1. spoofs the UA
2. emulates touch screen
3. fixes ontouchstart evt handlers
4. sets device metrics (dpr, viewport, overlay scrollbars etc)

If we're actually on a mobile device, we shouldn't do any of these 4 things. And network throttling should be handled separately.
#### Proposal:
- remove `mobile` flag from CLI and lighthouse API
- add `disableDeviceEmulation` to both. Defaults to false. Setting to true means we don't do `enableNexus5X()`.
- (optional) add extra `disableThrottling` flag for network (and soon CPU) throttling.

thoughts?

**Comment by wardpeet** [comment]
+1 for the proposal.
Not sure if you should set `disableDeviceEmulation` to false on default? Depends if we want lighthouse to be a mobile first citizen...
Perhaps we should broughten the `disableThrottling` flag to  connection types? (none, 4g, 3g, 2g, gprs). Perhaps not all of them. For example `--networkThrottling=3g` which is by default 3g.

**Comment by addyosmani** [comment]
I personally wouldn't mind seeing: `--disable-cpu-throttling` and `--disable-network-throttling` as atomic flags for cases where you might want to throttle one but not the other. +1 to removing the `mobile` flag, though :)

**Comment by paulirish** [comment]
yeah splitting them WFM.

**Comment by wardpeet** [comment]
@paulirish closing cause it's done.

**Comment by paulirish** [comment]
perf. thanks
