### ISSUE TITLE
Understanding/debugging NO_FCP exceptions

### ISSUE THREAD

**Issue by csvan** [GoogleChrome/lighthouse#6463]
I use the lighthouse CLI and Chrome 70 to audit an internal webpage, so unfortunately I cannot provide an URL to reproduce this on. 

The gist is that the audit completely fails to collect performance issues due to NO_FCP exceptions, e.g.

`offscreen-images:warn Caught exception: NO_FCP +0ms` 
`unminified-javascript:warn Caught exception: NO_FCP +278ms`

Other Lighthouse audits work fine.

My Google-fu is probably weak, but I can find very little information about what this exception is or what raises it - let alone how to debug it. Can anyone share some light on this?

It should be noted that the page being audited works fine by itself, loading properly and throwing no JS exceptions.

**Comment by brendankenny** [comment]
not sure what you want here, @paulirish

**Comment by guaka** [comment]
This may help someone: `NO_FCP` means "no First Contentful Paint".
(Took me couple minutes to find.)

**Comment by mcornella** [comment]
This also happens to me, I'm using Chrome 76 and testing a website I maintain that I'd rather not give out in public. It is (admittedly) very old and still uses frames, but will be updated to HTML5 soon. I would expect though that passing `--enable-error-reporting` would show me the thrown exception so I can at least debug this further, but it doesn't.

Anyway if you need the URL of the website so you can test this and anymore information let me know, I'm very interested in measuring its performance before the upgrade. Thanks!

**Comment by patrickhulce** [comment]
We consider this solved by #11579
