### ISSUE TITLE
DevTools Error: The asynchronous expression exceeded the allotted time of 60

### ISSUE THREAD

**Issue by NicciCz** [GoogleChrome/lighthouse#6464]
**Initial URL**: https://www.facebook.com/groups/798283386871142/files/
**Chrome Version**: 70.0.3538.77
**Error Message**: The asynchronous expression exceeded the allotted time of 60s
**Stack Trace**:
```
Error: The asynchronous expression exceeded the allotted time of 60s
    at _ (chrome-devtools://devtools/remote/serve_file/@0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9/audits2_worker/audits2_worker_module.js:1000:120)
```

**Comment by patrickhulce** [comment]
Thanks for filing @NicciCz! I'm not able to reproduce this error on that page, does it happen every time for you?
