### ISSUE TITLE
Chrome Plugin result do not match with API

### ISSUE THREAD

**Issue by KaranjitGitHub** [GoogleChrome/lighthouse#6468]
Lighthouse API results for Accessibility Test do not match with the ones generated by the chrome plugin.

**Comment by patrickhulce** [comment]
Thanks for filing @KaranjitGitHub! Would you mind filling out more of the details in our bug report template? i.e. which URLs, which audits are different, etc

**Comment by exterkamp** [comment]
Going to close if we can't get more details :cry:
