### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Network.emulateNetworkConditions

### ISSUE THREAD

**Issue by sandeepyohans** [GoogleChrome/lighthouse#6470]
**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 70.0.3538.77
**Initial URL**: http://mobiledtp.charislms.com/login.php
**Error Message**: PROTOCOL_TIMEOUT Method: Network.emulateNetworkConditions
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Network.emulateNetworkConditions
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18402:11)
```

**Comment by Da13Harris** [comment]
I'm running into the same issue on an internal app, seems like the same versions of everything:

**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 70.0.3538.77
**Initial URL**: (Internal URL. Sorry, not for public consumption)
**Error Message**: PROTOCOL_TIMEOUT Method: Network.emulateNetworkConditions
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Network.emulateNetworkConditions
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18402:11)
```

**Comment by RaceProUK** [comment]
I'm seeing this too.

**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 70.0.3538.77
**Initial URL**: https://localhost:44312/Sales/AffiliateInventoryOffers
**Error Message**: PROTOCOL_TIMEOUT Method: Network.emulateNetworkConditions
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Network.emulateNetworkConditions
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18402:11)
```

**Comment by patrickhulce** [comment]
Thanks folks! We're deduping this into #6512 to keep investigating.
