### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Storage.clearDataForOrigin

### ISSUE THREAD

**Issue by railsfactory-robin** [GoogleChrome/lighthouse#6472]
**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 67.0.3396.99
**Initial URL**: http://localhost:5000/
**Error Message**: PROTOCOL_TIMEOUT Method: Storage.clearDataForOrigin
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Storage.clearDataForOrigin
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18402:11)
```

**Comment by patrickhulce** [comment]
deduping into #6512
