### ISSUE TITLE
Properly size images passed when shouldnt

### ISSUE THREAD

**Issue by liorg2** [GoogleChrome/lighthouse#6473]
#### Provide the steps to reproduce
1. Run LH on https://www.terminalx.com/

#### What is the current behavior?
Properly size images passed on lighthouse 3.2 / 4.0 alpha

#### What is the expected behavior?
on lighthouse 3.0.3, it gives a list of images to resize

#### Environment Information
* Affected Channels: 
* Lighthouse version: 4.0 alpha OR 3.2
* Node.js version:8.11.3
* Operating System: ubuntu

**v3.03**

**Related issues**
![image](https://user-images.githubusercontent.com/1691647/47987550-708b1e00-e0e8-11e8-8f26-1e3ef8ef1341.png)

*v4.0 alpha*

![image](https://user-images.githubusercontent.com/1691647/47987596-96b0be00-e0e8-11e8-82f4-42469bf61a60.png)

**Comment by patrickhulce** [comment]
Thanks for filing @liorg2! This is not a difference between Lighthouse versions, this is a difference between the desktop and mobile versions of the page. The mobile version has sized images properly while the desktop version of the page has not.

Running with `--disable-device-emulation` or the "Desktop" type from DevTools in 4.0.0-alpha gives you the errrors you're expecting.

![image](https://user-images.githubusercontent.com/2301202/48003082-05831c80-e0d3-11e8-909f-5e75724e0126.png)

**Comment by liorg2** [comment]
thanks @patrickhulce
