### ISSUE TITLE
Proposal: Increase generic protocol timeout to 10s

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#6475]
We're getting a trickle of bug reports for timeouts on random commands (#6450 #6470 #6472). 5s seems somewhat arbitrary and it might be that 10s increases chances of completion? Perhaps there's something else going on though and these are just surfacing other connection problems. If we think that's the case, we should probably dig a little and try to surface a different error message?

WDYT @Hoten ?

**Comment by Hoten** [comment]
Let's bump it to 10s, and if there are still some errors coming through we can give them a closer look.
