### ISSUE TITLE
Report thresholds are not consistent: First Contentful Paint

### ISSUE THREAD

**Issue by krillesv** [GoogleChrome/lighthouse#6476]
When I ran the performance audit the report showed a green checkmark for First Contentful Paint (2 820 ms).
I saved the report and opened it up in Lighthouse Report viewer and now it shows orange warning instead of green checkmark. The report thresholds are not consistent.
https://googlechrome.github.io/lighthouse/viewer/

**Comment by patrickhulce** [comment]
Thanks for reporting @krillesv! The threshold for green was changed from 0.75 to 0.9 recently which is why you're seeing the discrepancy. The latest version of Lighthouse should also show the orange warning.
