### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache

### ISSUE THREAD

**Issue by olyzhuk** [GoogleChrome/lighthouse#6478]
**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 72.0.3595.2
**Initial URL**: https://34travel.me/
**Error Message**: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18402:11)
```

**Comment by patrickhulce** [comment]
duplicate #6450
