### ISSUE TITLE
Lighthouse is hanging up on a website

### ISSUE THREAD

**Issue by methyl** [GoogleChrome/lighthouse#6479]
#### Provide the steps to reproduce
1. Run LH on http://www.deco-sun.pl/produkty/rolety-rzymskie

#### What is the current behavior?
Hangs with high CPU usage

#### What is the expected behavior?
Should work correctly or at least timeout.

#### Environment Information
* Affected Channels: Node, DevTools
* Lighthouse version: DevTools, 4.0.0-alpha0
* Node.js version: 10
* Operating System: OSX, Linux

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for reporting @methyl! Visiting that site at all with mobile emulation seems to crash Chrome entirely. I'm not sure there's much we can do on the Lighthouse side at that point, but worth noting.

**Comment by paulirish** [comment]
theres an infinite loop due to a matchMedia check if i remember.
our page_hung fix should also take care of this.
