### ISSUE TITLE
Upgrade puppeteer

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6480]
We're rocking a chrome that's a few months old.

Let's bump up to latest!

**Comment by wardpeet** [comment]
actually we are running on chrome-stable that travis gives us as we skip Puppeteer download. i'll upgrade puppeteer nevertheless
.travis.yml
```
 # if our e2e tests fail in the future it might be that we are not compatible
  # with the latest puppeteer api so we probably need to run on chromimum
  # @see https://github.com/GoogleChrome/lighthouse/pull/4640/files#r171425004
  - export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
```
```
addons:
  chrome: stable
```

**Comment by paulirish** [comment]
@wardpeet oh that's true.

well locally we use pptr's chromium, which is a bit old.

**Comment by kud** [comment]
Hello.

Excuse-me but starting this: `npx lighthouse --view --chrome-flags='--headless'` runs which browser exactly? My canary? My puppeteer?

**Comment by kud** [comment]
Thank you @patrickhulce :)

Do you think it's possible to specify a particular browser like I can do on `backstopjs`:

```
engine: "puppeteer",
```

**Comment by wardpeet** [comment]
You can set an environment variable called CHROME_PATH=<path to chrome> on Linux and Mac to set a custom chrome

**Comment by kud** [comment]
Thank you @wardpeet but it would be applied on any project/tool which needs a chrome, no?

**Comment by wardpeet** [comment]
Not exactly. Everything that uses [Chrome Launcher](https://github.com/GoogleChrome/chrome-launcher) under the hood would. For example [puppeteer](https://github.com/GoogleChrome/puppeteer) doesn't because it has it's own mechanism. You can define a custom path `const browser = await puppeteer.launch({executablePath: '/path/to/Chrome'});`

**Comment by kud** [comment]
Oh! Okay, thank you. :)
