### ISSUE TITLE
claims that the ID's aren't unique

### ISSUE THREAD

**Issue by mgifford** [GoogleChrome/lighthouse#6489]
#### Provide the steps to reproduce
1. Run LH on https://cnib.ca

#### What is the current behavior?

I get thes failing elements - [id] attributes on the page are not unique

Failing Elements
--
`<g id="Group_128" transform="translate(-275 -39)">
<g id="Group_39" transform="translate(258.743 34.688)">
<path class="icon phone" d="M34.2 34.3c-1.4 0-2.8-.2-4.1-.8-5.8-2.5-10.5-7.1-13-13-1.5-3.4-.8-6.5 1.2-9.4.3-.4.6-.8 1-1.1 1.2-1.1 3-1.2 4.3-.2 1.5 1.2 2.4 3.1 2.4 5 0 .8-.4 1.5-1.1 2-.5.3-1 .8-1.4 1.3-.6.8-.8 1.9-.3 2.9.2.5.5.9.8 1.3 1.2 1.5 2.6 2.9 4.1 4.1.5.5 1.2.9 1.9 1 1.3.3 2.6-.3 3.3-1.5 1-1.5 2.4-1.7 4-1.2.9.3 1.8.7 2.5 1.3 1 .8 1.6 2 1.5 3.2 0 .4-.1.8-.3 1.1-.2.4-.5.7-.8 1-1.6 1.8-3.7 2.8-6 3z" id="Path_277">
<path class="icon phone" d="M46.1 16.3c0 1.2 0 1.2-1.1 1.2-.8 0-.8 0-.9-.9-.1-5.7-4.8-10.4-10.6-10.3h-.1c-.5 0-.5-.1-.5-.6 0-1.5 0-1.5 1.5-1.4C40.2 4.7 45 9 45.9 14.8c.1.5.1 1 .2 1.5z" id="Path_278"></path>
<path class="icon phone" d="M32.8 10.1c-1 0-1 0-1-1 0-1.1 0-1.1 1.1-1 4.4.2 8.2 3.3 9.2 7.6.2.8.3 1.6.3 2.4 0 .4-.1.6-.5.5-.5 0-1 .1-1.3-.1-.4-.2-.1-.8-.2-1.2-.3-3.6-3-6.6-6.6-7.2h-1z" id="Path_279"></path>
<path class="icon phone" d="M37.4 19.9c-.9 0-.9 0-1-.9-.1-2.9-2.6-5.1-5.5-5-.5 0-.5-.1-.5-.5v-1c0-.4.1-.5.5-.5 3.4-.1 6.4 2.2 7.3 5.5.1.6.2 1.3.2 1.9 0 .5-.1.7-.6.6-.1-.1-.2-.1-.4-.1z" id="Path_280"></path>
<svg id="search-icon-submit" xmlns="http://www.w3.org/2000/svg" role="icon" viewBox="0 0 100 99.8" aria-label="icon-search-title icon-search-description">`

#### What is the expected behavior?

None of these look like duplicate ids so the test should have passed.

#### Environment Information
* Affected Channels: Extension
* Lighthouse version: 3.3.0.4000
* Operating System: MacOSX

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @mgifford! It looks like `Group_128` is repeated on that page though?

![image](https://user-images.githubusercontent.com/2301202/48091044-2f6d3980-e1ce-11e8-9459-bffcfb319281.png)

**Comment by primozs** [comment]
<img width="430" alt="Screenshot 2020-10-28 at 22 30 29" src="https://user-images.githubusercontent.com/1006789/97498872-3a967280-196d-11eb-8264-252a3b8d8ebb.png">
<img width="273" alt="Screenshot 2020-10-28 at 22 30 13" src="https://user-images.githubusercontent.com/1006789/97498876-3bc79f80-196d-11eb-977b-c440fc9e6c61.png">
<img width="370" alt="Screenshot 2020-10-28 at 22 29 54" src="https://user-images.githubusercontent.com/1006789/97498879-3c603600-196d-11eb-9761-c647beeb7cb3.png">

**Comment by patrickhulce** [comment]
@primozs if you have a reproducible issue that is not replicated with [axe alone](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US), a new issue with the [bug report template reproduction details](https://github.com/GoogleChrome/lighthouse/issues/new/choose) would be appreciated :)
