### ISSUE TITLE
consider lighter weight replacements for yargs and handlebars

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#649]
http://npm.anvaka.com/#/view/2d/lighthouse

![image](https://cloud.githubusercontent.com/assets/883126/18500495/ca8c743a-79fc-11e6-8b88-90a295ccd8fa.png)

**Comment by paulirish** [comment]
yargs aint so bad and is already in google3, were we have deployments, too.

handlebars i can see us replacing. Lots of possible directions to go there, too. But would def want something that can run node-only.

**Comment by ebidel** [comment]
We've used https://www.npmjs.com/package/swig on other projects but it appears unmaintained. https://www.npmjs.com/package/nunjucks looks like a good replacement and is also modeled off jinja2/djano, which I know some contributors have experience in. 

Both are not in g3.

**Comment by wardpeet** [comment]
nunjucks is awesome! :)

**Comment by wardpeet** [comment]
@samccone @paulirish can we close this?

**Comment by paulirish** [comment]
ya
