### ISSUE TITLE
Include links with no text as "non-descriptive" in SEO audit

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#6495]
**Summary**
Split out from https://github.com/GoogleChrome/lighthouse/pull/6483#discussion_r231270784 per @rviscomi 's request. We should consider including all links that don't have any text content in our non-descriptive check. A link that doesn't have any text at all is just as non-descriptive as these other links :)

I think the main concern is that this will start including a bunch of things we don't foresee.

**Comment by rviscomi** [comment]
Thanks for filing this @patrickhulce! Will investigate.

**Comment by rviscomi** [comment]
Assigning to Matt to start implementing and testing on popular sites. Let's see what the new failure rate is before releasing it.

**Comment by mattzeunert** [comment]
Ran on 100 sites [from here](https://moz.com/top500).

| | Before | After |
| -- | ------ | ------ |
| Failure rate | 38% | 81% |
| Average warning count | 0.75 | 10.5 |
| Median warning count | 0 | 3 |

Right now the `AnchorElements` artifact uses `innerText` as the link text, which means the text is empty if the link is hidden. I've used `textContent` for now. If we don't want to count invisible elements we can detect that in the gatherer.

**Comment by rviscomi** [comment]
Hmm I think we should probably ignore hidden text to be consistent with the users' experience.

I'm concerned about the big spike in the failure rate though. Can you remind me when a warning gets triggered as opposed to a failure? Looked at the audit source code but didn't see a distinction. It might be worthwhile to warn about empty anchors rather than failing the audit. Not sure.

**Comment by mattzeunert** [comment]
Sorry, I meant items rather than warnings. Having one item in the audit result will cause the audit to fail.

Most of the time the images contain an image instead of text, sometimes with an `aria-label`.

**Comment by rviscomi** [comment]
Maybe we should be ignoring `a > img` cases? If they were to cause the audit to fail, what would the recommended fix even be: replace the image with text? put text next to the image? Not sure if `img[alt]` attributes are used instead, but I do know that `aria-label` attributes are not. I'll consult the WTAs.

**Comment by rviscomi** [comment]
Martin (@AVGP) suggested that if the anchor contains an image, we fall back to its alt text. Could we see how the failure rate changes with that implementation?

**Comment by mattzeunert** [comment]
This is if we include count image alt attributes as text:

| | Before | After |
| -- | ------ | ------ |
| Failure rate | 37% | 70% |
| Average item count | 0.74 | 7.0 |
| Median item count | 0 | 1.5 | 

Actually both of those numbers are inflated because I removed the visibility check. This is the result if we ignore invisible elements again:

| | Before | After |
| -- | ------ | ------ |
| Failure rate | 27% | 63% |
| Average item count | 0.57 | 3.0 |
| Median item count | 0 | 1 |

**Comment by paulirish** [comment]
I'm pretty scared to make this policy change.  We'd have to look at all the possible failures and determine if adding text is a reasonable solution for them all.

Would this be an improvement for accessibility or SEO? And why?

It seems like no one is strongly advocating for it right now, so let's shelve it?

**Comment by AVGP** [comment]
To be frank the high failure rate makes me nervous, too.

The benefits are that it's a consequent follow up for the audit on
meaningful link text and for accessibility and SEO its quite important to
have context for images, i.e. alt text except for decorative images and
those probably should not be the only affordance for whatever destination
the link is providing... so I'm advocating for it, but I think I would like
to better understand where the big chunk of failures are, maybe we need to
educate the community better first.

I will try to find some time in the upcoming weeks to take a look at the
cause of these issues. sounds good?

Paul Irish <notifications@github.com> schrieb am Mo., 25. Feb. 2019, 21:38:

**Comment by rviscomi** [comment]
SGTM. This is a low priority change so we have time to vet it properly.

**Comment by mattzeunert** [comment]
[Here's the output from running the script.](https://gist.github.com/mattzeunert/04c2204566e3fa5efda9272c4bf95c75)

Quite a few of them have an `aria-label` or a `title`, but I guess those don't count for SEO?

**Comment by connorjclark** [comment]
@AVGP @umaar is this still a priority in your opinions?

**Comment by AVGP** [comment]
We figured it isn't that pressing of an issue. If in doubt, I'd skip this.

**Comment by brendankenny** [comment]
Great, thanks! We can always revisit if it turns out we do have a blindspot here.
