### ISSUE TITLE
What version of WCAG 2.1 is supported in default Audit?

### ISSUE THREAD

**Issue by bgarrant** [GoogleChrome/lighthouse#6503]
I would like to see a switch so we can change the testing from WCAG 2.1 A or AA or Section 508.  In meantime, what version is scanned with the default Auth in Chrome Dev Tools?  A or AA?

**Comment by patrickhulce** [comment]
We'll de-dupe this into #4924 which you've already found, but we run both `wcag2a` and `wcag2aa` tags.

**Comment by bgarrant** [comment]
It shows errors and warnings by default I assume for A and AA? So if we need anything higher like AAA or Section 508 we should just run Axe directly then?
