### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Storage.clearDataForOrigin

### ISSUE THREAD

**Issue by SeanColombo** [GoogleChrome/lighthouse#6509]
**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 70.0.3538.77
**Initial URL**: http://localhost:8080/
**Error Message**: PROTOCOL_TIMEOUT Method: Storage.clearDataForOrigin
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Storage.clearDataForOrigin
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18402:11)
```

**Comment by wardpeet** [comment]
@SeanColombo thanks for filling this issue. Could you be some kind to give us some more info.

Does this happen everytime you run with the extension? Could you try devtools and see if you can reproduce It there as well. It would be super handy if we can get an external url of the site to see ourselves what's going on.

**Comment by patrickhulce** [comment]
Indeed thanks @SeanColombo! I'm going to dedupe this into #6512, but extra info you have would be great :)
