### ISSUE TITLE
add a user timing gatherer

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#651]
I think this makes sense as a gatherer but basically..
pull all the user timing events that happened on a page into a tidy little dict for someone to consume

Something like this would be swell

```
{
   timingEvent: {
       start:
       stop: 
       duration:
   }
   ...
}
```

**Comment by paulirish** [comment]
small tweak but this would land as a ["computed artifact"](https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/gather/computed)

But I like the idea of having a cleaner representation of these measures. 👍

**Comment by paulirish** [comment]
And it probably means we move most of this https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/user-timings.js into it.

**Comment by wardpeet** [comment]
If you like I could prep this ^^
