### ISSUE TITLE
Cross browser report issues (edge & safari)

### ISSUE THREAD

**Issue by wardpeet** [GoogleChrome/lighthouse#6510]
**Safari** 
1) issue with the dropdown of our action button. It's behind the scores box.
![image](https://user-images.githubusercontent.com/1120926/48222474-f3380580-e394-11e8-8b7d-fd51293e04bb.png)

**Edge**
Edge has an issue with opening the viewer. It opens the viewer but no report.

**Comment by wardpeet** [comment]
> Edge
Edge has an issue with opening the viewer. It opens the viewer but no report.

Sadly there is a bug with edge which makes window.opener undefined when changing origins:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11324352/

should we do an edge workaround where we do not do the postmessage dance for chrome and use a setTimeout.

**Comment by exterkamp** [comment]
fixed by #6546 

@paulirish we need to roll this into the hosted viewer I think, and roll to LR.

**Comment by exterkamp** [comment]
Rolled into hosted viewer and LR! :tada:
