### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Network.enable

### ISSUE THREAD

**Issue by dehciappina** [GoogleChrome/lighthouse#6511]
**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 72.0.3606.1
**Initial URL**: https://planilhacessivel.com.br/sec_pages/controle_financeiro/index.html
**Error Message**: PROTOCOL_TIMEOUT Method: Network.enable
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Network.enable
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18402:11)
```

**Comment by patrickhulce** [comment]
deduping into #6512
