### ISSUE TITLE
Include non-SEO best practices in the best practices category as well

### ISSUE THREAD

**Issue by Malvoz** [GoogleChrome/lighthouse#6514]
When a document is being "Blocked from indexing" as a result of `X-Robots-Tag` or `<meta name="robots">` I believe requiring a canonical link is redundant.

**Comment by patrickhulce** [comment]
Thanks for filing @Malvoz! If you're document is *intentionally* being blocked from indexing, you should really be ignoring the entire SEO category, but seeing as the SEO category is intended for folks who want their page to be indexed, I think we'll want to keep this check.

**Comment by Malvoz** [comment]
Thanks @patrickhulce Yes, I'm referring to cases where you don't want a document indexed by search engines, but still conform to some of the best practices within the SEO category, such as "_Document uses legible font sizes_" or "_Links have descriptive text_" (which I personally feel belongs to the accessibility category just as much).

**Comment by patrickhulce** [comment]
Point taken I think we should definitely surface the audits in SEO that are generally applicable in other categories as well! 👍

**Comment by wardpeet** [comment]
This actually refers back to the UX category where the "non" seo audits can live. At this point I don't think it's worth the effort to show the same audits on different places unless we already do 😛 .

**Comment by patrickhulce** [comment]
@wardpeet I forgot about our UX category dreams 😆 this is a good fit there, do you remember an issue #?

I only found #1639

**Comment by wardpeet** [comment]
Yeah "dreams". Sadly no issue, we had some discussions about it during some eng or sync meeting an half year ago

**Comment by paulirish** [comment]
No plans to surface audits in multiple places even if semantically that sorta makes sense.
