### ISSUE TITLE
Error: "Form elements do not have associated labels" for two labels

### ISSUE THREAD

**Issue by petrzpav** [GoogleChrome/lighthouse#6520]
Following code generates accessibility error. It seems to be caused by two labels associated to the same input.

- Error
```
Form elements do not have associated labels
--
Failing Elements
--
<input type="text" pattern=".*(\d\D*){9,}" id="contactform-basic-telephone" placeholder="+420 777123456" name="telephone">
```

- Code
```html
<form id="contactform-basic" class="fillable validable editable" method="post" action="/">
    <dl>
      <dt><label for="contactform-basic-telephone">Telefon</label></dt>
      <dd><input type="text" pattern=".*(\d\D*){9,}" id="contactform-basic-telephone" placeholder="+420 777123456" name="telephone"></dd>
      <dd><label for="contactform-basic-telephone">Nechte prázdné nebo napište aspoň 9 číslic.</label></dd>
    </dl>
</form>
```

**Comment by petrzpav** [comment]
@patrickhulce Thank you for the answer. We will use aria attributes, it make sense.

**Comment by robdodson** [comment]
This looks like it may be an axe issue. I haven't checked the HTML spec, but it looks like Chrome will properly compute the accessible name of an element with two labels if they're using the `for` attribute.

```
<label for="foo">Hello</label>
<input type="text" id="foo">
<label for="foo">World</label>
```

![image](https://user-images.githubusercontent.com/1066253/49049987-35838400-f196-11e8-815e-b0e3b0966345.png)

@WilcoFiers do you know if this is allowed?
