### ISSUE TITLE
Incorrectly reporting not supporting http/2

### ISSUE THREAD

**Issue by AlexNodex** [GoogleChrome/lighthouse#6539]
it says "Does not use HTTP/2 for all of its resources 6 requests not served via HTTP/2", but the server is correctly using h2

#### Environment Information
* https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.nodex.co.uk
* Lighthouse version: 4.0.0-alpha-0

------

EDIT(admin): This bug affects anything served by the PageSpeed API. (including web.dev). Root issue: b/32022322

**Comment by patrickhulce** [comment]
Thanks for reporting @AlexNodex! This appears to be web.dev specific as everything works as expected locally.

**Comment by AlexNodex** [comment]
Any idea how I report to them directly?

**Comment by patrickhulce** [comment]
We're probably ultimately the people to talk to, so you did the right thing, just more as an FYI :)

**Comment by PHPGangsta** [comment]
Same here. Hope you can fix it quickly.

**Comment by paulirish** [comment]
Internal ticket discussing h2: b/32022322

**Comment by thiscodeworks** [comment]
I have same problem .. network showing h2 in all requests, web.dev showing http/1.1 on all 79 requests

**Comment by manniL** [comment]
For all Googlers: `web.dev` uses Lighthouse version: ´4.0.0-alpha.0` but the issue is fixed in `4.0.0-alpha.1`. So just be patient ☺️

**Comment by paulirish** [comment]
Update: The HTTP2 audit is now being skipped and not reported via the API/web.dev. This rolled out just now. cc @robdodson @ebidel 


We have some infrastructure work to complete before we can rely on its result.

**Comment by manniL** [comment]
@paulirish Can second this 🙌 

Thanks for the fast fix 👍
