### ISSUE TITLE
Confusing interface and more

### ISSUE THREAD

**Issue by danielsedlacek** [GoogleChrome/lighthouse#6540]
#### Provide the steps to reproduce
1. Run LH on <https://uk.wikibudgets.org/w/united-kingdom-budget-2015>

#### What is the current behavior?
The SEO section score is 100 points.
The Crawling and Indexing says "robots.txt is valid", yet there is a red triangle icon with an exclamation mark. Why?
The Content Best Practices section says "Document has a valid rel=canonical", yet there is a red triangle icon with an exclamation mark.

#### What is the expected behavior?
If something is ok or 100 point score I don't expect a red triangle icon with an exclamation mark.
When I see a red triangle icon with an exclamation mark, I expect a rollover text or other explanation of what is wrong. 

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @griii2! I'm not seeing this behavior, do you have a copy of the report handy we could look at?

![image](https://user-images.githubusercontent.com/2301202/48420255-9daa8280-e71f-11e8-9f48-5b0d86004fbd.png)

The only situation I'm thinking of where you'd get a green 100 but a failure-ish looking audit is when there is a warning but that should have bold text right below explaining why.

**Comment by griii2** [comment]
I am coming from https://web.dev/

to

https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://uk.wikibudgets.org/w/united-kingdom-budget-2015#seo

![image](https://user-images.githubusercontent.com/2312983/48432897-f4db4200-e775-11e8-8642-c010563d7328.png)

**Comment by patrickhulce** [comment]
Ah thanks very much for the link @griii2! This is a bug in the web.dev UI. These audits should be rendered as "Not Applicable" but instead are being shown as failing :)

**Comment by brendankenny** [comment]
I think this is a proto or web.dev backend issue. The LHR has `scoreDisplayMode` `'not_applicable'` instead of `'not-applicable'` for all the not applicable audits.

@exterkamp @ebidel

**Comment by exterkamp** [comment]
This is a rendering issue I think.  Since a proto LHR is slightly different, the renderer might not be able to handle the small edge cases like this dash vs. underscore difference.

It definitely seems like an easy fix for the renderer.  But I'm not sure if making the renderer take fuzzier LHRs is a sustainable solution.
