### ISSUE TITLE
Create a terminology guide

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#6548]
I think I'm a bit out-of-sync with the core team's terminology. E.g. I use the word "audit" to refer to each individual thing that Lighthouse tests. But I think you all are using the word "test" for this thing now.

We can improve communication across all of the teams that rely on Lighthouse by creating a terminology guide that describes each of these things.

Guide should probably live in this repo, as this is the most definitive source of truth.

**Comment by brendankenny** [comment]
https://github.com/GoogleChrome/lighthouse/blob/master/docs/architecture.md has the start of this, though it's primarily concerned with the architecture of lighthouse itself, and not as much documenting the use of lighthouse or interpretation of the results

**Comment by paulirish** [comment]
Googlers can access the Lighthouse UI glossary: https://docs.google.com/spreadsheets/d/1YYeuzaOFYa0R57ivRLrb9qm_eFUYiXyo6vyIfjDmDjI/edit#gid=0
