### ISSUE TITLE
lighthouse launch-chrome --additional --flags --passed --too --chrome

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#655]
This way someone can use our chrome launcher w/o having to copy launch_chrome.sh

**Comment by wardpeet** [comment]
I believe you can already do this.
you can already do this with the  `npm run chrome -- (your extra stuff)`or `sh launch_chrome.sh (args)`

**Comment by samccone** [comment]
Ah I mean npm I lighthouse ... Then lighthouse chrome ....

**Comment by wardpeet** [comment]
Not 100% sure what you mean by your latest comment. You could use the `--no-launch-chrome` flag and have a copy of chrome running yourself on 9222 with your own arguments using the command above.

When looking at PR #642 it looks if any chrome is already running on 9222 so you probably don't even need the flag.

**Comment by samccone** [comment]
simply put:

I want an additional bin command in lighthouse or command to lighthouse that will only launch chrome and do nothing else.

Make sense?
