### ISSUE TITLE
Custom protocols treated as insecure requests

### ISSUE THREAD

**Issue by AidHamza** [GoogleChrome/lighthouse#6551]
#### Provide the steps to reproduce
1. Run LH on https://www.tayara.tn
2. Check the `Best Practices` section

#### What is the current behavior?
It is considering the deeplink `sch.tayara://listings://open?link_click_id=591024402604455640` as insecure URL

#### What is the expected behavior?
I guess if the app is linked to the website, the deeplink should not considered as insecure

#### Environment Information
* Affected Channels: web.dev
* Lighthouse version: 4.0.0-alpha.0
* Node.js version: N/A
* Operating System: N/A

**Comment by patrickhulce** [comment]
Thanks for reporting @AidHamza! This is an interesting one.

On the one hand, it's somewhat impossible to know how information over a custom protocol is being treated, and it'd be nice to know if one was happening unexpectedly. On the other hand, this network request is being aborted anyhow and nothing is really compromising the use of HTTPS on the site. Maybe a separate audit is in order for custom protocols?
