### ISSUE TITLE
Lighthouse Audits on Multiple SPA pages with only 1 unique URL

### ISSUE THREAD

**Issue by EnlightenMeee** [GoogleChrome/lighthouse#6555]
4.0.0 alpha

**Feature request summary**

Lighthouse audits multiple view/pages within Single Page Application with only 1 url

 no

**What is the motivation or use case for changing this?**
 SPA auditing

**How is this beneficial to Lighthouse?**
It will add features and flexibility

**Comment by EnlightenMeee** [comment]
Our project is SPA using ReactJS is there a way to audit page flows using lighthouse. example, page1 -> page 2-> page N. If I use lighthouse to audit page N, single page going page1 instead of page.

**Comment by patrickhulce** [comment]
Page flows are going to be covered by #3837. Feel free to add any additional use cases you think are missing over on that issue! :)
