### ISSUE TITLE
Error: 500 from Lighthouse API: Internal Server Error

### ISSUE THREAD

**Issue by armandomedrano** [GoogleChrome/lighthouse#6557]
#### Provide the steps to reproduce
1. Run LH on https://solmail.bancosol.com.bo

#### What is the current behavior?
Error: 500 from Lighthouse API: Internal Server Error
#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by ebidel** [comment]
Should be fixed now in the web.dev UI. We're forwarding errors from the LH API to our own UI.
