### ISSUE TITLE
lighthouse w/ an empty aggregations: [] config fails :(

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#656]
> Error: The config must provide passes and audits, artifacts and audits, or auditResults

**Comment by brendankenny** [comment]
are you talking about a config with only
```javascript
{
  "aggregations": []
}
```

in it, or e.g. the default config with an empty `aggregations` array? The second one works fine for me.

**Comment by samccone** [comment]
hmm seems to be a manifestation of something else, still digging in, will close this for now.3
