### ISSUE TITLE
PWA audits always come back negative on web.dev

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/lighthouse#6566]
#### Provide the steps to reproduce
1. Run LH 4.0.0-alpha.0 on web.dev and audit http://shop.polymer-project.org

#### What is the current behavior?
PWA score is 65—says things like service worker are missing.

#### What is the expected behavior?
PWA score should be 100

#### Environment Information
* Affected Channels: web.dev
* Lighthouse version: 4.0.0-alpha.0
* Node.js version: any
* Operating System: any

We've since disabled the PWA audits so web.dev no longer requests them. Speaking to @paulirish it sounded like this was caused by the infrastructure the LH service is being run on. Sounds like maybe it is bailing early during the offline testing phase.

**Comment by Hoten** [comment]
Lightrider fails for all pages with a SW or a websocket connection - with the same issue. See internal bug: b/116839144

**Comment by Hoten** [comment]
This was fixed Apr 4 in LR.
