### ISSUE TITLE
Report Renderer: Performance section Passed Audits

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#6568]
#### What is the current behavior?
Changes introduced in #6460 need to be discussed with a focus on UX.

**Comment by patrickhulce** [comment]
Also the opportunities icon is missing :)

![image](https://user-images.githubusercontent.com/2301202/48529854-ad7ab180-e85a-11e8-95fe-ecce941e8c1b.png)

**Comment by exterkamp** [comment]
I think this has been sufficiently handled in LH and PSI :smile:
