### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Storage.clearDataForOrigin

### ISSUE THREAD

**Issue by allania7med11** [GoogleChrome/lighthouse#6571]
**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 70.0.3538.102
**Initial URL**: https://effectivewebapp.com/Tutorials/TrussStructure
**Error Message**: PROTOCOL_TIMEOUT Method: Storage.clearDataForOrigin
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Storage.clearDataForOrigin
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18402:11)
```

**Comment by patrickhulce** [comment]
duplicate #6512
