### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache

### ISSUE THREAD

**Issue by viewouts** [GoogleChrome/lighthouse#6572]
**Lighthouse Version**: 3.3.0.4001
**Lighthouse Commit**: 66100367e39d970f8208bd30c10bd97cc7240784
**Chrome Version**: 70.0.3538.102
**Initial URL**: https://xfhat.com/
**Error Message**: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18993:11)
```

**Comment by patrickhulce** [comment]
duplicate #6512
