### ISSUE TITLE
npm has v4.0.0-alpha.1 as latest

### ISSUE THREAD

**Issue by zeman** [GoogleChrome/lighthouse#6575]
@paulirish npm has v4.0.0-alpha.1 as the "latest" version rather than v3.2.1. WebPageTest uses the npm version so all tests now run the alpha version. Shouldn't it be on 3.2.1 rather than the alpha?

https://www.npmjs.com/package/lighthouse

**Comment by paulirish** [comment]
Yes. Very sorry for publishing the alpha. I meant to publish it via `lighthouse@next` but made a mistake.

https://github.com/GoogleChrome/lighthouse/releases describes what happened, but we've now reshipped 3.2.1 to NPM as `v4.0.0-alpha.2-3.2.1` so anyone with `lighthouse@latest` (like WPT) will get it automatically.

**Comment by zeman** [comment]
Thanks for sorting that out so quickly!
