### ISSUE TITLE
Desktop Audit of Construct3 fails

### ISSUE THREAD

**Issue by petele** [GoogleChrome/lighthouse#6584]
#### Provide the steps to reproduce
1. Run LH **DESKTOP** audit on https://editor.construct.net/ 

#### What is the current behavior?
Hangs - sits at the testing modal dialog the whole time

#### What is the expected behavior?
Complete the test

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: Generated by Lighthouse 3.2.0
* Node.js version:
* Operating System: MacOS

**Comment by patrickhulce** [comment]
Thanks for filing Pete :) 

I'm not able to reproduce in Canary or CLI with latest lighthouse with desktop or mobile audit :/ Any other info we might need to know about this?

**Comment by patrickhulce** [comment]
I partially take it back! I just re-ran everything and was able to get an intermittent `PROTOCOL_TIMEOUT Method: Storage.clearDataForOrigin` failure on the mobile CLI run.

**Comment by petele** [comment]
Nothing special to know... Running Chrome Beta on my Mac it happens consistently. I haven't been able to get a test to complete. Running the mobile audits works fine, but desktop fails. It visually fails after the no javascript tests, but that's it.

**Comment by exterkamp** [comment]
Tested this again on v4.0.0-beta and it _seems_ to work.  I did get 1 NO_FCP error from devtools, but I couldn't get it to happen again.  Seems to work fine from CLI, from pagespeed, and from web.dev.

Can you still repro this?

**Comment by paulirish** [comment]
works fine now. please holler if you run into another hang bug. we def want to fix those.

🍻
