### ISSUE TITLE
Reorganise the Performance Metrics section

### ISSUE THREAD

**Issue by pet-ro** [GoogleChrome/lighthouse#6587]
Lighthouse and its documentation are great. Thank you.

Here a transparency improvement suggestion:

IMHO the Performance Metrics section of the Lighthouse Viewer could do a better presentation job.
I'm a newbie to this topic, may this does matter to professionals.

I would prefer a presentation which makes transparent  that the 6 metrics
can be grouped into two groups (category A and categorie B).

**What is the motivation or use case for changing this?**
I found the current grouping not transparent.

Current | Grouping
-------- | -----------
Cat A | Cat A 
Cat A | Cat B 
Cat B | Cat B 

**How is this beneficial to Lighthouse user?**

Newbies can more intuitively grasp the grouping of the metrics

Paint related  | Interactivity related   
--------------- | -----------------------
 FCP               | **FCI**  |
 FMP              |  TTI |
|**SIP**           | **ELI**   |  

**SIP** is a new acronym; **Speed Index of Paint**
Now all _paint related_ metrics use the suffix '**P**'.

Similar it might be possible to use the suffix '**I**'  for all _interactivity  related_ ones.
new **FCI** short for **First CPU Idle**
new **ELI** short for **Estimated Latency of Input**

**Feature request summary**

Just give all _Paint related_ metrics a suffix **P**
and  _Interactivity related_ metrics a suffix **I**.

Currently there are 3 _Paint related_ metrics and  3_Interactivity related_ metrics.
Present each metric type in its own column  
in the  _Performance_  section of  report rendered by the  LightHouse Viewer in Chrome.

**Comment by patrickhulce** [comment]
Thanks for the suggestions @pet-ro! To give a bit of insight into why they're currently grouped the way they are...

The ones on the left have the most weight in the score and are the most important metrics we care about. The ones on the right are mostly used in diagnosing why the ones on the left aren't doing so well. Admittedly we never ended up labeling them this way and so what's left is fairly confusing, but that was the original rationale :)

**Comment by centminmod** [comment]
@patrickhulce curious why you don't order the metrics by their weights ? TTI, Speedindex, FCP on the left side ?

**Comment by brendankenny** [comment]
These are being reorganized somewhat (and some replaced) under #8185 and #8331
