### ISSUE TITLE
Better labelling / warning for alpha tests?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#659]
I'm looking at the "Cache contains start_url from manifest" audit which is supposed to make sure that a PWA can properly launch from homescreen. However, what it actually does is check if the cache contains a resource that matches the start_url exactly, rather than asking the service worker to resolve the request. So if the cache contains a value that matches start_url but in reality the service worker redirects to a non-existent page, you can get a false positive result. Or, no start_url resource exists, but in reality the service worker successfully redirects to a different resource, and you get a false negative.

That seems like a pretty big gotcha? I get now why the test is labeled "alpha", but maybe there should be more of a warning if that's what "alpha" means?

**Comment by brendankenny** [comment]
> However, what it actually does is check if the cache contains a resource that matches the start_url exactly, rather than asking the service worker to resolve the request

just fyi, that particular bug is #566 

but yes, definitely agree that many people miss the "(alpha)", and even those that do see it don't realize it's describing the state of the test and not some modifier to the name of the test or some kind of data returned *from* the test :)

**Comment by paulirish** [comment]
Addressed. New bug is #2576
