### ISSUE TITLE
INSECURE error not working as expected

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6595]
`lighthouse https://zach.diemer.codes/`

This should return an LHR with a runtimeError set to the INSECURE_DO CUMENT_REQUEST

Instead:

1. we first wait for Page.navigate to timeout. (kind of a bummer..)
2. the timeout of Page.navigate triggers a rejection which is unhandled
3. it bails completely instead of making an LHR

**Comment by brendankenny** [comment]
> it bails completely instead of making an LHR

I believe this is WAI/#6336 for the CLI

**Comment by paulirish** [comment]
> I believe this is WAI/#6336 for the CLI

Certainly related, but FAILED/ERRORED_DOC_REQ dont bail out like that.

**Comment by paulirish** [comment]
@Hoten 	to rebase the new error handling from Shane.

**Comment by Hoten** [comment]
I forgot @exterkamp bailed on that in #6671 :(

**Comment by Hoten** [comment]
Looks like just throwing the error when the security issue is first found will be OK now that Shane fixed LR's error handling in #6739. groovy
