### ISSUE TITLE
Make image links clickable

### ISSUE THREAD

**Issue by jadjoubran** [GoogleChrome/lighthouse#6598]
**Feature request summary**
In audits relating to images, it would be nice to make the image links **clickable** which automatically takes to the image that's failing the audit. 
![screen shot 2018-11-17 at 13 24 28](https://user-images.githubusercontent.com/2265232/48661042-45031e80-ea6c-11e8-8f4b-fce91b29e6a6.png)
Another alternative would be to have a "link opens in new tab" (top-right arrow) icon that will open the image

I would love to work on this new feature

**What is the motivation or use case for changing this?**
When debugging sites with large and/or dynamic images, this makes it much easier to find (and get a link) of the image that's failing the audit.
Most of the times, image links are quite long so they get trimmed and you can't copy them and then you have to find them in the Network tab

**How is this beneficial to Lighthouse?**
Improved Developer Experience 😄

**Comment by patrickhulce** [comment]
Should be easy enough thanks for filing and volunteering @jadjoubran !

The code you're looking for is 
https://github.com/GoogleChrome/lighthouse/blob/7f55977b2a8aa13633c95a1d97b546b0bd74c8be/lighthouse-core/report/html/renderer/details-renderer.js#L193-L206

You'll probably want to wrap that in an `a` and set the href/target to the URL/_blank.

**Comment by jadjoubran** [comment]
maybe then it makes sense to link the **trimmed link** (screenshot below) to the image (opens in a new tab)
<img width="177" alt="screen shot 2018-11-19 at 12 57 26" src="https://user-images.githubusercontent.com/2265232/48705864-b670d780-ebfa-11e8-9dc1-e9bdfff76226.png">

and then a future PR would link the **image preview** (screenshot below) to the DOM element
<img width="42" alt="screen shot 2018-11-19 at 12 57 29" src="https://user-images.githubusercontent.com/2265232/48705890-c8eb1100-ebfa-11e8-9bbf-7667bc1c6e33.png">

What do you think?

**Comment by patrickhulce** [comment]
We've been thinking about making the trimmed link link out for a while now across the board, so that'd be cool!

Linking to the DOM element has always been somewhat trickier but very useful. Definitely start with the trimmed link, and we can handle DOM element next :)

**Comment by jadjoubran** [comment]
Sounds good, just to double check and avoid confusion (because you linked me to the thumbnail)
trimmed link => should link to the image in a new tab
correct?

**Comment by Hoten** [comment]
https://github.com/GoogleChrome/lighthouse/pull/6625#issuecomment-470675315
> there has been even more rethinking about how to linkify URLs in the report, so let's close for now and reopen when we nail down exactly what we want to do.

we should just make all urls in detail items clickable, ya?

**Comment by Hoten** [comment]
duping into #5443
