### ISSUE TITLE
The score of a 17MB+ website is 75 where as a 600KB+ website scoring 98

### ISSUE THREAD

**Issue by webdevron** [GoogleChrome/lighthouse#6602]
I have test
ed two websites. One is about 17MB+ and other is less than 1MB. In the previous version of PageSpeed Insights the score of the 17MB+ website was 0 (in desktop mode). But now the score is 75.
Is there any explanation of that? Ii have attached the previous result with the post.

<img width="326" alt="20" src="https://user-images.githubusercontent.com/8216116/48666573-06fb0e80-eaef-11e8-9d89-ee207e468d50.png">

**Comment by patrickhulce** [comment]
If most of the 17MB is images or other resources that don't affect the primary performance metrics, then it will likely score high. There should definitely be audit failures elsewhere in the performance section for such enormous payloads, but those don't affect the score.

Having a specific URL for this page would be helpful.

**Comment by centminmod** [comment]
@patrickhulce shouldn't the size of the page be a factor in calculating the score in v5 insights ? especially as it relates to optimising 3G mobile profile user experience and optimal mobile data transfers ?

**Comment by paulirish** [comment]
Our metrics are designed to be sensitive to perceived performance. Currently we do not punish you if your site is heavy (as long as you're fast).

related #6231
