### ISSUE TITLE
DevTools Error: The asynchronous expression exceeded the allotted time of 60

### ISSUE THREAD

**Issue by quocbinhnguyen** [GoogleChrome/lighthouse#6604]
**Initial URL**: https://joe-furnitures.myshopify.com/
**Chrome Version**: 70.0.3538.102
**Error Message**: The asynchronous expression exceeded the allotted time of 60s
**Stack Trace**:
```
Error: The asynchronous expression exceeded the allotted time of 60s
    at _ (chrome-devtools://devtools/remote/serve_file/@4bbeebac88fdc09c97265e47c205868bbd190497/audits2_worker/audits2_worker_module.js:1000:120)
```

**Comment by patrickhulce** [comment]
Thanks for filing @quocbinhnguyen! This page crashes Chrome though, so there's not much more we can do other than #6497.
