### ISSUE TITLE
Performance metrics not working in chrome V70.0.3538.67

### ISSUE THREAD

**Issue by KathiresanRamkumar95** [GoogleChrome/lighthouse#6610]
We use lighthouse for getting performance metrics during CI by lighthouse using programmatically.
After update chrome version 70.0 we unable to get the metrics.

Getting error something like below ,

debugString: "Audit error: TracingStartedInPage was not found in the trace"
description: "Consistently Interactive (beta)"
displayValue: ""
error: true
helpText: "Consistently Interactive marks the time at which the page is fully interactive. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/consistently-interactive)."
name: "consistently-interactive"
rawValue: null
score: null
scoringMode: "numeric"

and it works well in chrome v67.0.

After a deep analyze we get another error message like 
> disabled-by-default-devtools.timeline

Please help me to solve this ASAP

Thank you in advance!

**Comment by KathiresanRamkumar95** [comment]
@benschwarz

**Comment by KathiresanRamkumar95** [comment]
@brendankenny  @paulirish

**Comment by patrickhulce** [comment]
@KathiresanRamkumar95 have you updated your Lighthouse version too? It doesn't look like it with the metric name `Consistently Interactive (beta)` 

As Chrome makes internal changes you'll need to update LH too to keep up.

**Comment by patrickhulce** [comment]
If you've mucked around with Lighthouse yourself I'm afraid we don't know what you could have done, so you're on your own for that.

As for updating lighthouse and starting fresh.

```bash
rm -rf node_modules/ # this will delete all your node_modules but you shouldn't be making manual changes to these anyway
npm install lighthouse
