### ISSUE TITLE
 Document does not have a valid rel=canonical

### ISSUE THREAD

**Issue by AnthonybVH** [GoogleChrome/lighthouse#6613]
**Hello all, I tried pulling a report on Lighthouse and noticed we had an SEO issue where the audit was pulling multiple canonical tags. One was a partial url and the other full length. Please see flagged issue below: 

Document does not have a valid rel=canonical
Multiple conflicting URLs (/conditions/sciatica/what-you-need-know-about-sciatica, https://www.spine-health.com/conditions/sciatica/what-you-need-know-about-sciatica)

This is the URL we were trying to audit. 
https://www.spine-health.com/conditions/sciatica/what-you-need-know-about-sciatica

Any help is greatly appreciated. 
**

**Comment by patrickhulce** [comment]
Have you tried looking at the [audit documentation](https://developers.google.com/web/tools/lighthouse/audits/canonical)? It gives you a link to see how to resolve duplicate rel canonical links.

https://support.google.com/webmasters/answer/139066
