### ISSUE TITLE
Improper pattern matching for "Links do not have descriptive text" SEO metric

### ISSUE THREAD

**Issue by booleanbetrayal** [GoogleChrome/lighthouse#6616]
#### Provide the steps to reproduce
1. Run LH on `https://smart.ly`

#### What is the current behavior?

Report presents the following non-descriptive text links:
```
/corporate-training(smart.ly) | LEARN MORE
/candidates/join-career-network(smart.ly) | LEARN MORE
```

#### What is the expected behavior?

The pattern appears to be too greedy. These links are actually single-element links with the following text values,`Contact us to learn more`, `Looking to hire talent? Learn more` which are pretty descriptive.

#### Environment Information
* Affected Channels: web.dev
* Lighthouse version:  4.0.0-alpha.0
* Node.js version: NA
* Operating System: NA

**Related issues**

**Comment by patrickhulce** [comment]
It's not flagging the ones in that sentence. It's flagging the one that just says learn more with an arrow

Example:
![image](https://user-images.githubusercontent.com/2301202/49039326-12040d80-f185-11e8-900a-797537fde0ef.png)

**Comment by booleanbetrayal** [comment]
My mistake. Sorry for any confusion.
