### ISSUE TITLE
Falsy meta description alert

### ISSUE THREAD

**Issue by kirill-chirkov-at-clouty** [GoogleChrome/lighthouse#6624]
#### Provide the steps to reproduce
1. Run LH on https://www.clouty.ru/shop/women/clothing
2. SEO -> Document does not have a meta description

#### What is the expected behavior?
Since `<meta name="description" content="...">` element is present in head, there should be no such message

#### Environment Information
* Affected Channels: 
* Lighthouse version: Lighthouse 3.2.1
* Node.js version: 10.13.0
* Operating System: Windows 10 Pro x64

**Comment by patrickhulce** [comment]
I'm not sure what you mean, I don't see one and neither does `document.querySelector`.
![image](https://user-images.githubusercontent.com/2301202/48856194-653c2180-ed7b-11e8-995b-50c16ed5bb78.png)

**Comment by kirill-chirkov-at-clouty** [comment]
So yeah, I see, thank you @patrickhulce. That opened eyes on some fatal problem with our site, that we were using `<alternate>` element (what the heck even is this? Could not find any info on this), which moved all subsequent head elements into body. I wonder if this could be included in Lighthouse? Anyway, this issue is solved, thanks again.
