### ISSUE TITLE
core(service-worker): SWs registered on page load not noticed

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6626]
auditing https://www.pinterest.com/ results in

```
Does not register a service worker
```

However, the Applications panel does show a SW is registered. Inspection of the code suggests that it is registered on the "load" event, which LH perhaps cannot recognize at the moment.

**Comment by Hoten** [comment]
We could examine the code closer (assuming it's controlled via just client code) - or perhaps we may get lucky pinging some Pintrest devs :)

@pfarejowicz @bradencanderson We are trying to determine if there is a flaw in how we detect SW registration for purposes of PWA auditing. Might one of you be able to affirm or refute @patrickhulce's conjecture?

**Comment by pfarejowicz** [comment]
Hey @Hoten and @patrickhulce thanks for the ping! I'm going to redirect you to @bishwei and @zackargyle who know a lot more about our SW setup for our PWA. Hopefully they can answer your questions.

Thanks for keeping Pinterest in mind! 💯

**Comment by patrickhulce** [comment]
Thanks for chiming in @pfarejowicz @zackargyle that's really useful to know! 

Now I'm running into a slightly different issue though.

When I visit www.pinterest.com in a clean Chrome profile with DevTools mobile emulation enabled (Pixel 2 for example), the page *never* registers a service worker. This is the same behavior I'm seeing in Lighthouse. I can increase our waiting for the service worker to 60s and still see nothing. When I turn off mobile emulation, it registers properly as you've described and it passes the audit.

**Comment by zackargyle** [comment]
Looks like the team decided to not register the service worker if you aren't logged in which is what you're seeing. I can look into why that is. Probably has to do with the app shell caching user information.

**Comment by patrickhulce** [comment]
Ah, ok. Thanks! 

Seems like we can close this then @Hoten? I'm not able to reproduce any unexpected behavior.

**Comment by Hoten** [comment]
Yeah, seems like LH is working as expected here. Thanks for the information @zackargyle.
