### ISSUE TITLE
When i Run lighthouse with puppeteer Multiple instance of Chromium will open in parallel

### ISSUE THREAD

**Issue by EnlightenMeee** [GoogleChrome/lighthouse#6649]
#### Provide the steps to reproduce
1. Run LH on my project

#### What is the current behavior?
     Run Lighthouse with Puppeteer on a single URL but it opens multiple Chromium browser in parallel
![image](https://user-images.githubusercontent.com/45029535/48993900-5be7f600-f17b-11e8-990c-d5ac179bafd0.png)

#### What is the expected behavior?
   Run Lighthouse with Puppeteer on a single URL and audits that single URL

#### Environment Information
* Affected Channels: 
* Lighthouse version: 6.4.1
* Node.js version:
* Operating System: windows 10

**Related issues**

**Comment by patrickhulce** [comment]
@EnlightenMeee we'll need more specific repro information, both projects will try to launch Chrome by default so you'll need to use very particular flags to use them together successfully.

**Comment by paulirish** [comment]
@EnlightenMeee can you provide us your code to run all this?  thx
