### ISSUE TITLE
Can't update the lighthouse with latest lighthouse

### ISSUE THREAD

**Issue by KathiresanRamkumar95** [GoogleChrome/lighthouse#6650]
Still get below error
>npm WARN lighthouse@1.0.0 No description
>npm WARN lighthouse@1.0.0 No repository field.

Even after delete the node_module using rm -rf 

Help me to solve this

@patrickhulce

**Comment by patrickhulce** [comment]
This seems to just be #6610, I'm closing in favor of that.
