### ISSUE TITLE
Test urls with Various network and cpu with login

### ISSUE THREAD

**Issue by KathiresanRamkumar95** [GoogleChrome/lighthouse#6651]
If the lighthouse much better when the default config contains the option to set the 
No throttling, 
4X throttling,
6X throttling CPU slowdown, and 
Slow 3G, 
Fast 3G and 
4G network speed, 
With and without cache combinations 

with login options.

Also, find the long network and request stalls because of long-running scripts 

Thanks in advance

@patrickhulce

**Comment by patrickhulce** [comment]
Duplicate #6610.

You don't need to modify Lighthouse for any of this behavior, you can use the [CLI options](https://github.com/GoogleChrome/lighthouse#cli-options) or a custom config for this purpose. 

In future issues, please try and include more detail on what you've already tried and why the methods outlined in [our documentation](https://github.com/GoogleChrome/lighthouse/tree/master/docs) aren't enough for your use case.
