### ISSUE TITLE
API: https://www.ig.com/uk throws backend error.

### ISSUE THREAD

**Issue by stmoreau** [GoogleChrome/lighthouse#6656]
I am trying to run audit against my company's website but after loading for ever I am getting the following error:
Error: Lighthouse returned error: generic::internal: APP::1: Exhausted render retries.

The url I am trying is: https://www.ig.com/uk

I am not too sure if that is intended or a known issue for some reason I am not aware of 😕

**Comment by Hoten** [comment]
Works in the DevTools extension + in [PSI](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.ig.com%2Fuk). I don't know what that suggests, but that's how it is :)

**Comment by stmoreau** [comment]
Yeah I know, it is just not working on https://web.dev/

On the DevTools it's working fine.
Thanks anyway 😄

**Comment by Hoten** [comment]
Actually, more likely it's related to the websocket. There are some issues with our internal infrastructure RE: websockets/service workers. PSI and web.dev use the same backend service, so it's quite unexpected that only one would be erroring.

Internal bug: b/119875011
Related LH issue: #6566

Closing this as it's well tracked elsewhere.

**Comment by stmoreau** [comment]
Sure @Hoten ! Thank you for that.

Is there any way of me tracking that issue?
I would like to know when I'll be able to start using web.dev to run & track my audit.

**Comment by Hoten** [comment]
Sure, just follow #6566.
