### ISSUE TITLE
I think font-display is not recognized even if is declared in CSS

### ISSUE THREAD

**Issue by standoski** [GoogleChrome/lighthouse#6657]
Hi,

1. I think in Lighthouse 4.0.0-alpha.1, font-display is not recognized even if it is declared in CSS and the test returns that: "Ensure text remains visible during webfont load".

2. And i have a question: if I have hosted the fonts on the same server (not loaded from google fonts server or other CDN) and imported in the CSS should I use the <link rel=preload> ? Is there any advantages because i have it now like this:

```
@font-face{font-family:Raleway;font-display:swap;font-style:normal;font-weight:400;src:local(Raleway),local(Raleway-Regular),url(myserver/assets/fonts/raleway-400.woff2) format("woff2")}
@font-face{font-family:Raleway;font-display:swap;font-style:normal;font-weight:600;src:local('Raleway SemiBold'),local(Raleway-SemiBold),url(myserver/assets/fonts/raleway-600.woff2) format("woff2")}
@font-face{font-family:Poppins;font-display:swap;font-style:normal;font-weight:400;src:local('Poppins Regular'),local(Poppins-Regular),url(myserver/assets/fonts/poppins.woff2) format("woff2")}
```

**Comment by patrickhulce** [comment]
Thanks for reporting @standoski! It passes our smoke tests, so there must be something strange going on with that URL. Do you have a public URL for us to take a look at?

**Comment by robdodson** [comment]
Possibly related to #6628?

**Comment by multiformeingegno** [comment]
I have the same issue. I have font-display: fallback but I still get the same error. URL: bombacarta DOT com

**Comment by paulirish** [comment]
duping into #6628
