### ISSUE TITLE
request with `intent:` protocol was treated  as network request

### ISSUE THREAD

**Issue by echopi** [GoogleChrome/lighthouse#6660]
**Summary**

Shalt we preload the `intent:` request? 

![image](https://user-images.githubusercontent.com/16034964/49057191-85675700-f239-11e8-93e1-b7414e4028ec.png)

**Comment by patrickhulce** [comment]
Nope, this shouldn't be flagged as a key request. Thanks for filing this @echopi!

**Comment by midzer** [comment]
I have time to look at this one, if noone else wants to contribute as a newcomer.
