### ISSUE TITLE
Accuracy of CLI tool vs one that's on the developer tools on chrome

### ISSUE THREAD

**Issue by aprilmintacpineda** [GoogleChrome/lighthouse#6666]
#### Provide the steps to reproduce
1. Run LH on a URL using developer tools on chrome.
2. Run LH on the same URL using CLI available on NPM.

#### What is the current behavior?

Results are drastically different.

- I got 91 on performance which I was not expecting because using the developer tools on chrome I got only 66.
- Using dev tools on chrome, I got *TTFB* = *ERROR!*. Using the CLI, I didn't.

The only difference is with the performance. The rest are the same.

#### What is the expected behavior?

LH should show accurate performance measurement using CLI and Dev tool.

#### Environment Information
- Affected Channels: CLI, DevTools
- Lighthouse version:  On my dev tool, it says *3.0.3*. CLI is 4.0.0-alpha.2-3.2.1.
- Node.js version: v11.2.0
- Operating System: Mac OS

**Comment by patrickhulce** [comment]
We're going to need a little more information here. You're using two different versions of Lighthouse with unknown settings on an unknown URL. Do you think you could help fill in the blanks a bit?

**Comment by aprilmintacpineda** [comment]
About the difference in version, I did not install lighthouse on my devtool. I actually just saw it there. Should have I updated it? how do I update it?

About the url part, you can use https://stackoverflow.com/ as url, it doesn't really matter. I just tested it now on my computer using https://stackoverflow.com/ as the url. I suggest not logged in.

This image is the lighthouse on devtools.

![image](https://user-images.githubusercontent.com/21032419/49125636-a8f2d600-f2fb-11e8-85d9-845f0a733aef.png)

This image is the lighthouse on CLI using Lighthouse Report Viewer.

![image](https://user-images.githubusercontent.com/21032419/49125675-d6d81a80-f2fb-11e8-9e84-13050ce2de02.png)

**Comment by patrickhulce** [comment]
Thanks for sharing that @aprilmintacpineda! Was there something obscuring your Chrome window for some of the time in the CLI case? All of my runs (DevTools, Extension, and CLI) are similar to your DevTools run and not your CLI run.

There are *many* reasons why metrics can vary. We've [documented the most common factors](https://docs.google.com/document/d/1BqtL-nG53rxWOI5RO0pItSRPowZVnYJ_gBEQCJ5EeUE/edit), but not every page load will be identical.

**Comment by aprilmintacpineda** [comment]
I don't think there is.

Differences in performance in each run is understandable since network speed is also a factor and its speed fluctuates. But the differences shouldn't be that big, right?

I don't know why the SEO are also different. Using CLI it shows 80 while on DevTool it shows 70.

The color coding are also different. Accessibility at 79 shows green on DevTool. Accessibility on CLI shows orange on the Viewer. This could just be the viewer itself.

Also, in the case above it shows my CLI is slower than the DevTool. On the site that I am developing, which I'm sorry but you can't access since it's exclusive to the office network. The performance is low on DevTool but and high on CLI. This is consistent.

This is using DevTool.

![image](https://user-images.githubusercontent.com/21032419/49131944-19f2b780-f315-11e8-9803-1b1e4c1b9ac0.png)

This is using CLI.

![image](https://user-images.githubusercontent.com/21032419/49131962-342c9580-f315-11e8-9bc9-d74e64dbe174.png)

Result on measuring the performance is also very consistent with only 2 - 5 points differences each run.

**Comment by aprilmintacpineda** [comment]
BTW.

Here's the options I use for DevTool

![image](https://user-images.githubusercontent.com/21032419/49132119-d9e00480-f315-11e8-8da6-e95580cd19fa.png)

On CLI, I only do `lighthouse <link> --output json --output-path test.json`.

**Comment by aprilmintacpineda** [comment]
How do I update the lighthouse devtool to its latest version? I thought it's suppose to automatically update since my chrome's auto update is enabled.

**Comment by patrickhulce** [comment]
@aprilmintacpineda it does update automatically, but it runs behind the CLI by quite a bit to go through Chrome's release process. Current latest version of LH will likely hit Chrome stable around January-February.

**Comment by aprilmintacpineda** [comment]
> applied throttling in some cases can be quite different from simulated throttling, the more direct comparison on the CLI would be using --throttling-method=devtools.

You we're right. I tried running my devtool using Simulated throttling and it gave me the same range, 91-93 on performance. Why isn't there an option to do Applied throttling using the CLI?

**Comment by patrickhulce** [comment]
Applied throttling *is* `--throttling-method=devtools`. The differences between CLI and DevTools are just down to Chrome profile and any potential extensions you might have (an adblocker or antivirus extension perhaps?)

**Comment by aprilmintacpineda** [comment]
I don't have those kinds of extensions. The CLI also opens chrome browser and navigates to the given link. So I assume it's using the browser's environment as well, similar to running lighthouse on the DevTool, yes?

I checked out lighthouse chrome extension. It's version is the same as the one I have on my DevTool.
