### ISSUE TITLE
HTML Report: support deep linking

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#6668]
For web.dev, we have the request for users to be able to deep link into sections of the HTML report. Each section, currently has an `id=AUDIT_NAME`, but loading the report does not always scroll properly to that section during page load or the section is hidden under by the top fixed banner. Also need to expand the details element when users are deep linking into a section.

Example: 
https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://ericbidelman.com#errors-in-console

Items to handle:
- [x] include ids on all audit line items
- [ ] detect anchor target on page load and delay (smooth) scroll to section. Include offset so section isn't hidden under top nav.
- [ ] auto-expand the audit's details dropdown so users can drill right in. 

b/119882633

**Comment by brendankenny** [comment]
Does web.dev include `report-ui-features.js`? If so, take a look at #5915 and see if it fits what you need :)

**Comment by patrickhulce** [comment]
Sounds like you want #5915 :)

**Comment by brendankenny** [comment]
> Include offset so section isn't hidden under top nav

Is still an issue, though

**Comment by Meggin** [comment]
Just wanted to add a comment that yes, this is something that we still need for web.dev-- the ability to deep link into a specific audit result.

**Comment by paulirish** [comment]
This works well enough for now.
