### ISSUE TITLE
How to identify lighthouse report got error while running from CLI?

### ISSUE THREAD

**Issue by ssivanatarajan** [GoogleChrome/lighthouse#6669]
I am running lighthouse CLI (version 3.2.1), sometimes I am getting an error like "Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)" , I have to re-run this if it got failed,  How can I identify it from lighthouse JSON result

**Comment by patrickhulce** [comment]
Each audit has an `errorMessage` and `scoreDisplayMode` property that will reflect any error status.

Example
```js
const {report} = await lighthouse(...)
if (report.audits['first-contentful-paint'].errorMessage) rerunLighthouse()
```


You might find [the docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/understanding-results.md#audits) useful here.

**Comment by ssivanatarajan** [comment]
thanks @patrickhulce
