### ISSUE TITLE
When download , write in file name mobile or desktop

### ISSUE THREAD

**Issue by yourchoice** [GoogleChrome/lighthouse#6674]
When download , write in file name mobile or desktop.

Same on the already generated reports, write to know it's from mobile or desktop

**Comment by patrickhulce** [comment]
Thanks for filing @yourchoice! Just to make sure I understand, you're suggesting that we put in the filename of the report whether it was a mobile or desktop viewport?

Is this for CLI or DevTools or viewer or extension?

There are a lot of runtime settings that affect the results we could theoretically put into the filename, and our focus is definitely on emphasizing mobile tests, so I'm not quite sold on why we'd prioritize this one, but it's something to think about.

**Comment by yourchoice** [comment]
Chrome DevTools

And when I load a json file to see report, I would like to know if report was for mobile or desktop (maybe exists, but not seen by me)

**Comment by exterkamp** [comment]
I'm a little confused, do you want to know the report was for mobile/desktop in the filename or just if it was mobile/desktop at all?  Because that is in the `configSettings` and should be generated for every report. As defined in [externs](https://github.com/GoogleChrome/lighthouse/blob/master/types/externs.d.ts#L106) iirc
```
  "configSettings": {
    ...
    "emulatedFormFactor": "mobile",
    ...
  },
```

**Comment by paulirish** [comment]
@yourchoice the report (and JSON) indicate if its mobile or desktop

![image](https://user-images.githubusercontent.com/39191/50117596-51f96600-0202-11e9-814d-71d2733b51aa.png)

either that or "Emulated desktop"

It's not in the filename, but we're not ready to do that now.

**Comment by yourchoice** [comment]
Hi, 

I understand, I reffer to the selectbox, near to the download button.... If there I have many reports generated it's hard to know if was generated for mobile or desktop (these need opened...)
