### ISSUE TITLE
Preload audit on lazy iframe

### ISSUE THREAD

**Issue by kirill-chirkov-at-clouty** [GoogleChrome/lighthouse#6675]
#### Provide the steps to reproduce
Run LH on https://www.clouty.ru/shop-item/9cedcb77-e064-40a5-9765-1e79152d83bc/jackets-zhaket-emporio-armani

#### What is the current behavior?
Audit suggests me to `Preload key requests` on iframe with src `https://www.clouty.ru/toshop?id=9cedcb77e06440a597651e79152d83bc&type=iframe`.
Iframe is injected lazily via js, some time after `onload` browser event and serves pure technical needs.

#### What is the expected behavior?
Preloading this specified iframe would ruin the lazy behavior, but preload audit lowers score significantly

#### Environment Information
* Affected Channels:
* Lighthouse version: 4.0.0-alpha.2-3.2.1, 4.0.0-alpha.1, 3.2.1 and 3.0.3 (Chrome Lighthouse audit)
* Node.js version: 10.13.0
* Operating System: Windows 10 Pro 64-bit

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/4425#issuecomment-442416040

**Comment by wardpeet** [comment]
@patrickhulce I did some research on this and when looking into devtools we get a resourceType of undefined back because it's a 302 so my suggestion is to also hide undefined from critical resources.

**Comment by patrickhulce** [comment]
Yeah I think that's a good call @wardpeet! 👍

**Comment by patrickhulce** [comment]
Oh I just realized that might be because of OOPIFs (#6337), still makes sense to do your filter I think though until we have the protocol support we're waiting on.

**Comment by brendankenny** [comment]
fixed in #6704 and verified that it no longer shows up in the report for this site. Additional preload improvements will continue to happen in #4425
