### ISSUE TITLE
DevTools Audit panel integration

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#668]
Lighthouse audits should be totally accessible to the devtools user. So yeah, let's do that. :)

---
### WIP implementation

<a href="https://gfycat.com/UnevenInfatuatedAmericanwarmblood">
<img src="https://thumbs.gfycat.com/UnevenInfatuatedAmericanwarmblood-size_restricted.gif">
</a>

![image](https://cloud.githubusercontent.com/assets/39191/18649427/4854d5f8-7e74-11e6-9ea7-d5fd6f4eaa00.png)

I have an early work-in-progress spike:

Lighthouse branch here: https://github.com/GoogleChrome/lighthouse/compare/devtoolsintegration
DevTools branch: https://github.com/ChromeDevTools/devtools-frontend/compare/master...paulirish:lh
#### impl notes
- It uses a custom config for now. Being fairly conservative in what's running
- Meet the _devtools driver_. It wraps a base devtools connection channel to hijack events as they come in. It doesn't disconnect from the page because it's always sharing the connection that devtools already has. Other than that, pretty basic. 
- web-inspector.js will point to the live devtools if we're in that situation, otherwise it'll use our mock one (now in `-impl`)
- `build-for-devtools.sh` will do the browserify run
- `devtools-lighthouse-runner` is totally basic (and like our extension one). 
#### To try it out
1. check out the two branches
2. change the destination path in `lighthouse-extension/devtools/build-for-devtools.sh` to match where your devtools checkout is.
3. run the `build-for-devtools.sh` script.
4. in the devtools checkout, run `npm run start` and follow the instructions
5. that should mostly do it.

---
#### Next steps
- Reporting. This is the big one. 
  - Lots of options here; completely changing the Audits panel report UI is an option.
- Get multiple passes & service worker tests to run successfully
- Lots of cleanup

**Comment by paulirish** [comment]
Lots of work on this recently

* https://github.com/GoogleChrome/lighthouse/pull/908
*  https://bugs.chromium.org/p/chromium/issues/detail?id=663085

**Comment by paulirish** [comment]
WIP chromium CL: https://codereview.chromium.org/2502853002  
Uses lighthouse master.

**Comment by paulirish** [comment]
BOOYAH

**Comment by patrickhulce** [comment]
done 🎉
