### ISSUE TITLE
user-scalable=no is usually not an accessibility issue

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/lighthouse#6681]
_From @agamemnus on November 28, 2018 2:9_

````
[user-scalable="no"] is used in the <meta name="viewport"> element or the [maximum-scale] attribute is less than 5.

Disabling zooming is problematic for users with low vision who rely on screen magnification to properly see the contents of a web page.
````

My web-app was designed with a few features to handle that. Further, enabling the user scaling through touch zoom would break critical functionality.

_Copied from original issue: GoogleChrome/web.dev#492_

**Comment by patrickhulce** [comment]
Thanks @TimvdLippe!

@agamemnus, if you're separately handling screen magnification, great! We also want to make sure that the path *to enabling those accessibility features* still abides by all the guidance, so hopefully you're still supporting zoom there. 

This rule comes straight from axe, and there's no automatic way of telling that you're zooming functionality is as accessible as the browser's, so we won't be removing this rule from the accessibility category. For more details on the motivation behind this you can take a look at the [docs](https://dequeuniversity.com/rules/axe/2.2/meta-viewport?application=lighthouse).
