### ISSUE TITLE
"Background and foreground colors do not have a sufficient contrast ratio." bug

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/lighthouse#6682]
_From @agamemnus on November 28, 2018 2:7_

It identified "failing elements" as my share buttons, which have a high contrast (e.g.: white against black, etc.). Probably a problem of the code not being able to figure out the background correctly:
````
<div> <--- background-color set here
 <div> <--- background: inherit tried. Didn't work to fix this issue.
  <div>share</div> <--- the element it complains about.
 <div>
</div>
````

_Copied from original issue: GoogleChrome/web.dev#491_

**Comment by patrickhulce** [comment]
@agamemnus if you can provide a URL that has this failure and reproduce it with [axe](https://github.com/dequelabs/axe-core/issues), we'd love if you filed the bug with them. When they update their library we'll pickup the fix too.
