### ISSUE TITLE
Improve how HTML elements are displayed in the results table

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#6683]
A few things that could be improved:
- UX: hide irrelevant info, make sure important info is shown (like the text content)
- Reduce result size (by hiding irrelevant info)
- Be more consistent across different audits (different data sources might make this difficult, e.g. expression evaluated in page, `driver.getNodesInDocument`, or aXe)

Here are two example results:

![](https://user-images.githubusercontent.com/1303660/49245767-307b3a80-f40b-11e8-9074-51c011f6ff5e.png)

![](https://user-images.githubusercontent.com/1303660/49245766-2fe2a400-f40b-11e8-9b5c-399587a51bca.png)

Related ticket about the node selectors we show on hover - might also benefit from some standardization: https://github.com/GoogleChrome/lighthouse/issues/4015

cc @rviscomi @patrickhulce

**Comment by Hoten** [comment]
Related to this - linking to the actual element if the page is still open. Some audits do this, some don't. There's just one ticket atm for font-size: #6436

**Comment by mattzeunert** [comment]
Just playing around a bit... showing the textContent and outerHTML.

@rviscomi What do you think about how we can improve this?

Master branch:

![Screenshot 2019-03-10 at 15 11 20](https://user-images.githubusercontent.com/1303660/54087002-d0b7f800-4346-11e9-929b-71071da513e0.png)

![Screenshot 2019-03-10 at 15 16 43](https://user-images.githubusercontent.com/1303660/54087096-8b47fa80-4347-11e9-98cc-6fcf6f91d088.png)


Experiment:

![Screenshot 2019-03-10 at 15 09 45](https://user-images.githubusercontent.com/1303660/54087001-d0b7f800-4346-11e9-9faf-7fdcdccd8f26.png)

![Screenshot 2019-03-10 at 15 15 47](https://user-images.githubusercontent.com/1303660/54087079-6e132c00-4347-11e9-9081-0e081a5cc486.png)

**Comment by rviscomi** [comment]
Text content LGTM!

In the case where the anchor content is an image, I wonder if we could/should render a thumbnail of the image?? cc @AVGP

**Comment by mattzeunert** [comment]
@paulirish @hwikyounglee How do you feel about showing text content for node elements in the details table?

**Comment by mattzeunert** [comment]
> Be more consistent across different audits (different data sources might make this difficult, e.g. expression evaluated in page, driver.getNodesInDocument, or aXe)

Some relevant discussion [here](https://github.com/GoogleChrome/lighthouse/pull/8133#discussion_r274146345).

Also, seems like lots of `type: 'node'` details renderer types don't have a `path`/`selector` at all right now.

**Comment by hwikyounglee** [comment]
> @paulirish @hwikyounglee How do you feel about showing text content for node elements in the details table?

Are we referring to the black text e.g. Vasil, help, blocking, etc., compared to not showing them but just tags in green? The proposed design LGTM. Thanks Matt!

**Comment by mattzeunert** [comment]
@hwikyounglee Yeah, exactly. Latest screenshot is [here](https://github.com/GoogleChrome/lighthouse/pull/8961) – same thing but looks a bit different because it's after the report redesign.

**Comment by brendankenny** [comment]
@mattzeunert does #8961 close this out or are there other proposals you'd like to see here?

**Comment by mattzeunert** [comment]
There's element screenshots as well, but I think [this ticket](https://github.com/GoogleChrome/lighthouse/issues/7327) best matches that.

I created [another ticket for some `node.snippet` tweaks we want to do](https://github.com/GoogleChrome/lighthouse/issues/9062).
