### ISSUE TITLE
Report: should contain what version of lighthouse ran the report

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#669]
The extension and cli are producing different output for me. It would be useful to see the version of lighthouse on the report card.

**Comment by brendankenny** [comment]
should the version be documented or should the extension and the CLI just be reporting the same results? Performance results may always be slightly different, but things like the PWA checks *should* match (starting to fix this is one of the goals of smokehouse).

**Comment by ebidel** [comment]
I think they should be reporting the same results (as close as possible at least).

But I can also imagine generating a few report.html files locally and stashing them over time. When you open those, you have no idea what version lighthouse created it.

**Comment by juliantoledo** [comment]
@ebidel @brendankenny Should the version also be included in the JSON report?

**Comment by ebidel** [comment]
Yea probably should be there too somewhere. Can you open a new issue?

**Comment by juliantoledo** [comment]
cool, done #748
