### ISSUE TITLE
Getting Driver:warn Timed out waiting for page load. Moving on...

### ISSUE THREAD

**Issue by pkamran** [GoogleChrome/lighthouse#6690]
#### Provide the steps to reproduce
1. Run LH on a non public URL.  The LH was hit using WPT ec2 Private agent.

#### What is the current behavior?
For some URL Lighthouse break in between the result shows : 
Mon, 26 Nov 2018 10:45:43 GMT status Retrieving: EmbeddedContent
Mon, 26 Nov 2018 10:45:43 GMT status Retrieving: Canonical
Mon, 26 Nov 2018 10:45:43 GMT status Retrieving: RobotsTxt
Mon, 26 Nov 2018 10:46:43 GMT status Retrieving: Fonts
Mon, 26 Nov 2018 10:46:48 GMT status Loading page & waiting for onload ServiceWorker, Offline, StartUrl
Mon, 26 Nov 2018 10:46:48 GMT statusEnd Loading page & waiting for onload
Mon, 26 Nov 2018 10:46:48 GMT status Retrieving devtoolsLog and network records
Mon, 26 Nov 2018 10:46:48 GMT status Retrieving: ServiceWorker
Mon, 26 Nov 2018 10:46:48 GMT status Retrieving: Offline
Mon, 26 Nov 2018 10:46:48 GMT status Retrieving: StartUrl
Mon, 26 Nov 2018 10:46:48 GMT status Loading page & waiting for onload HTTPRedirect, HTMLWithoutJavaScript
Mon, 26 Nov 2018 10:48:08 GMT Driver:warn Timed out waiting for page load. Moving on...
Mon, 26 Nov 2018 10:48:08 GMT statusEnd Loading page & waiting for onload
Mon, 26 Nov 2018 10:48:08 GMT status Retrieving devtoolsLog and network records
Killed

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 2.9.4
* Node.js version:
* Operating System: LInux ubuntu
lighthouse "<URL>/za/en/articles/skin-types/eczema-how-to-care-for-hands-and-feet.html" --disable-network-throttling --disable-cpu-throttling --throttling-method provided --enable-error-reporting --max-wait-for-load 80000 --port 9239 --output html --output json --output-path "/home/ubuntu/wptagent/work/ip-172-31-26-135/181126_0J_5e3e5f24c0891621901b42539ecd6ad6.1.0/lighthouse.json" --disable-device-emulation --chrome-flags="--user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/70.0.3538.110 Safari/537.36 PTST/181121.201107'"

**Related issues**

**Comment by patrickhulce** [comment]
@pkamran it doesn't look like you gave Lighthouse a URL, it looks like you gave it a file path? `file:` URLs don't work so well in practice, so you'll want to setup a server that's listening on `http`.

**Comment by pkamran** [comment]
Hi Patrick,

Thanks for responding. I just replaced the actual url with <URL> in the post here, as I can not share the private url publicaly.

Thanks & Regards
Pankaj Kamran

**Comment by patrickhulce** [comment]
Ah, gotcha. Is it an HTTPS URL that isn't also listening over HTTP/port 80? Hanging there is typically a sign that there was no HTTP server even though there was an HTTPS one.

**Comment by brendankenny** [comment]
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen.

**Comment by EXPEpaher** [comment]
I am seeing a similar issue while loading a https URL on aws lambda for lighthouse audit. Any pointers on what could be the issue?

`Driver:warn Timed out waiting for page load. Checking if page is hung...`
