### ISSUE TITLE
Critical Request Chains report 0.00KB transfers

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#670]
<img width="654" alt="screen shot 2016-09-19 at 2 47 40 pm" src="https://cloud.githubusercontent.com/assets/238208/18650112/189a3c14-7e78-11e6-92e6-3c18e9fe92f2.png">

**Comment by paulirish** [comment]
Thx for reporting. we'll take a look.  Extension or CLI?

**Comment by ebidel** [comment]
Extension. CLI from source from master looks good.

**Comment by wardpeet** [comment]
Extension 1.1.4 what version are you using?
![image](https://cloud.githubusercontent.com/assets/1120926/18738396/96e057fa-809b-11e6-8f6f-efbb9d8a0b8d.png)

**Comment by ebidel** [comment]
I can't repo this anymore :\
