### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Network.emulateNetworkConditions

### ISSUE THREAD

**Issue by bnikom** [GoogleChrome/lighthouse#6720]
**Lighthouse Version**: 3.3.0.4001
**Lighthouse Commit**: 66100367e39d970f8208bd30c10bd97cc7240784
**Chrome Version**: 69.0.3497.100
**Initial URL**: https://www.invaluable.com/auction-lot/egon-schiele-lithograph-heavy-wove-paper-circa-19-ea24b9287a
**Error Message**: PROTOCOL_TIMEOUT Method: Network.emulateNetworkConditions
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Network.emulateNetworkConditions
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18993:11)
```

**Comment by patrickhulce** [comment]
duplicate #6512
