### ISSUE TITLE
Lighthouse  network-requests audit results are not same for every run 

### ISSUE THREAD

**Issue by ssivanatarajan** [GoogleChrome/lighthouse#6727]
I am using lighthouse CLI to monitor some set of URLs in my product. The results of "Network-requests" are not the same for every run, even there is no code change those pages.  

Some network requests are missing and for some N/w requests,  getting size as 0 Bytes. (these are random issues for the next run I am getting the size and request also available)

**Comment by patrickhulce** [comment]
We'll need more specifics here to be able to help. What URLs are you monitoring? What requests are missing?

If a request isn't in the `network-requests` audit that means that Chrome never issued it (unless it was inside a crossorigin iframe that was out of process, see #6337).

**Comment by ssivanatarajan** [comment]
@patrickhulce  I am using Lighthouse API for monitoring our product in the test environment. so it can't be accessible outside.  Those requests are not inside an iframe. This issue happening in the random run.

**Comment by patrickhulce** [comment]
OK, well without more information and repro steps I'm afraid we can't really do anything about it :/

**Comment by ssivanatarajan** [comment]
@patrickhulce  ,Below is the JSON result of network-request audit of that request . This may helps. why it's status is "-1" and mimeType is empty.
mimeType: ""
resourceType: "Stylesheet"
startTime: 28583.233000710607
statusCode: -1
transferSize: 0

**Comment by patrickhulce** [comment]
That just means Chrome never got a response. It didn't know the status code/mime type/transfer size because there was no response :)
