### ISSUE TITLE
PWA report UI nits in dark mode

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6729]
The group icons should be lighter colored. Performance category already got this treatment.
And the light-on-dark aliasing of the PWA badge is a little awkward. @hwikyounglee 	 any suggestions or leave as it?

![image](https://user-images.githubusercontent.com/39191/49532203-d5b16b00-f870-11e8-9929-532e3b23bca3.png)

**Comment by brendankenny** [comment]
aliasing as in just the contrast in colors at the edge and how the browser is handling the transition? Since it's svg the renderer is picking the particular antialiasing strategy.

**Comment by paulirish** [comment]
Colors at the edge yeah. I'm only thinking we could apply some shadow/border to soften it? Dunno, it just feels a bit unpolished.

**Comment by hwikyounglee** [comment]
Can we use #9D9D9D instead of black for the PWA icons inside circles? 

![darktheme-group-badges](https://user-images.githubusercontent.com/7561395/49568861-1a77e900-f8e7-11e8-84e9-13d0abc6edf0.png)

**Comment by brendankenny** [comment]
those icons are data urls...I guess we could just double them up and have a dark mode version for each. 

@paulirish, is there a css selector we can use to see if we're in dark mode? Or some other way?

**Comment by paulirish** [comment]
yah there's a selector.. and you can see the things we've done before for this:

https://cs.chromium.org/chromium/src/third_party/blink/renderer/devtools/front_end/audits2/audits2Panel.css?q=audits2panel+css&sq=package:chromium&dr&l=19

**Comment by brendankenny** [comment]
Part of #8185 and fixed in #8425
