### ISSUE TITLE
0 Performance Scores

### ISSUE THREAD

**Issue by xxTigerlilyxx** [GoogleChrome/lighthouse#6731]
When my internet connection is low (around 10mbps in this case) I tend to get a lot more 0 scores in the performance audit. Attached is an excel file showing a few different internet speeds and how they affect the performance score in lighthouse audits. Not sure if these 0 scores are an error or if the performance of the sites audited was bad because of my internet connection used.

Running Lighthouse v3 through the command prompt, then parsing the JSON to Excel.
[COX URL Lighthouse Scores.xlsx](https://github.com/GoogleChrome/lighthouse/files/2651390/COX.URL.Lighthouse.Scores.xlsx)

**Comment by patrickhulce** [comment]
Thanks for filing @xxTigerlilyxx and thank you very much for the detailed data! A few questions that would help us.

What settings are you using to run lighthouse? Simulated performance? Throttled performance? No throttling?

Do you happen to know your latency changes on these different connection types? Latency will tend to have a much greater impact on page load performance than throughput, especially at 10+ mbps ranges.

**Comment by xxTigerlilyxx** [comment]
I'm running Lighthouse-CLI via Windows 10 Command Prompt on default throttling settings - I did not specify any throttling settings 

> The mobile network throttling preset
This is the standard recommendation for mobile throttling:

Latency: 150ms
Throughput: 1.6Mbps down / 750 Kbps up.
Packet loss: none.
These exact figures are used as Lighthouse's throttling default and represent roughly the bottom 25% of 4G connections and top 25% of 3G connections. They are identical to the WebPageTest "Mobile 3G - Fast" preset and, due to a lower latency, slightly faster for some pages than the WebPageTest "4G" preset.

Throttling basics
Simulated throttling, which Lighthouse uses by default, is computed throttling after a trace has been recorded which makes it very fast and deterministic. However, due to the imperfect nature of predicting alternate execution paths, there is inherent inaccuracy that is summarized in this doc: Lighthouse Metric Variability and Accuracy. The TLDR: while it's roughly as accurate or better than DevTools throttling for most sites, it suffers from edge cases and a deep investigation to performance should use Packet-level throttling tools.

[https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md](url)

I do not know my latency changes on these different connection types.

**Comment by patrickhulce** [comment]
Thanks @xxTigerlilyxx! If you're using default simulated throttling then there shouldn't be that significant of an impact by network throughput changes. I'm not sure what's going on. My best guess is that your latency and RTT to the origin's servers are changing along with the throughput, and that is what's causing the discrepancy.

**Comment by brendankenny** [comment]
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen.
