### ISSUE TITLE
Network and CPU Throttling "Unknown"

### ISSUE THREAD

**Issue by mdiblasio** [GoogleChrome/lighthouse#6734]
#### Provide the steps to reproduce
1. Run any LH test via [web.dev](web.dev)
2. View LH report

#### What is the current behavior?
"Network throttling" and "CPU throttling" unknown ([example report](https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://m.shop.nordstrom.com/
)):

![image](https://user-images.githubusercontent.com/17748781/49588980-2d65da00-f936-11e8-8d96-7673fb504885.png)

#### What is the expected behavior?
"Network throttling" and "CPU throttling" should be defined as this can affect metrics and overall score.

#### Environment Information
* Affected Channels: web.dev
* Lighthouse version: 4.0.0-alpha.1
* Node.js version:
* Operating System:

**Comment by patrickhulce** [comment]
Thanks very much for reporting @mdiblasio! This is captured by #6654, so we'll keep tracking it there. Feel free to subscribe to that issue for updates!
