### ISSUE TITLE
Make PWA N/A badge look less like a score placeholder

### ISSUE THREAD

**Issue by jonchenn** [GoogleChrome/lighthouse#6738]
The new PWA badge on Chrome Canary looks good, but it's a bit confusing when there's nothing on the badge, i.e. the N/A status.

When nothing passes in PWA criteria, the badge shows a horizontal dash "--" inside the round PWA badge. However, when it appears altogether with other LH scores, e.g. performance, best practices, or SEO, the PWA N/A badge looks like a score placeholder but just without a number.

When I see the PWA n/a badge, I would expect some numbers show up after making some improvement.

![image](https://user-images.githubusercontent.com/1644724/49608186-fe675c80-f965-11e8-8d8d-c4d02b307589.png)

It will be helpful if the n/a badge looks a bit less like score placeholder. An explanation page (or a skill tree in many video games) would be helpful to understand what to expect.

**Comment by patrickhulce** [comment]
cc @hwikyounglee for her thoughts

**Comment by cheneytsai** [comment]
@kusler FYI

In addition, I was initially confused when I saw the partial badge by itself in the top row (The installable one), since there was a color filled in for the "+" circle, it felt like I was passing the the "PWA" check already when if you scroll down it shows in the details I don't actually meet the requirements.

If I had full knowledge of the 5 types of badges (from NA -> PWA), then it might make sense, but as standalone, it's hard to tell that I was missing something.

**Comment by hwikyounglee** [comment]
Thanks @jonchenn and @cheneytsai for sharing confusion areas. 

We can/should continue to improve going forward. 
- badge explanations:   a short tooltip and a small diagram are likely to be added per discussions so far. To build on to the skill tree idea, I'll look into a detail/graphical tooltip.  
- n/a status badge:   i'll continue to look into ways to make it clearer while maintaining neutral treatment
- incremental progress:  the current direction is to use the detail audit list to see the incremental progress (i.e. inline checkmarks) and to use the badge to celebrate a completion of a meaningful group of criteria. I'd like us to take more time to see how this intention is received. 
- color filled badges:  The most trickiest part so far on the problem! The challenge we're working with is different goals on apps. The badge design intends to communicate a completion of an aspect (vs. lacking of the aspect). Please allow this some time to learn from more perspectives.

**Comment by paulirish** [comment]
You can get this badge even if you're 85% of the way there (just missing a single audit in each group).

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
