### ISSUE TITLE
Chrome extension version outdated

### ISSUE THREAD

**Issue by frlinw** [GoogleChrome/lighthouse#6741]
Chrome stable audit tab: v3.0.3
Chrome Canary audit tab: v4.0.0-beta
Chrome extension: v4.0.0-alpha.1

Is it possible to have the latest lighthouse version with the Chrome extension ?

**Comment by patrickhulce** [comment]
Yep, we'll be publishing Chrome extension with latest 4.0.0 release soon!

**Comment by gdarko** [comment]
This is outdated again. Version 4.1.0 is live in https://web.dev
