### ISSUE TITLE
Minification estimation erroneously reports very large savings

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/lighthouse#6744]
While `minification-estimator.js` currently correctly [ignores license comments](https://github.com/GoogleChrome/lighthouse/blob/54c2b5df7fdcbc289c2ac5942e2d17efa5a8194c/lighthouse-core/lib/minification-estimator.js#L108), it seems like JavaScript and Cascading Style Sheets source mapping comments like `//# sourceMappingURL=foo.min.js.map` or `/*# sourceMappingURL=foo.css.map */` are still counted, which seems incorrect.

**Comment by patrickhulce** [comment]
Thanks for filing @tomayac! I'm curious, have you run into any cases where we start flagging code as unminified just because of the source map comments? I would've expected them to be pretty small compared to license comments :)

**Comment by tomayac** [comment]
They are pretty small, indeed :-) I have a user complaint regarding [this file](https://static.parastorage.com/services/santa/1.5597.7/app/main-r.min.js).

**Comment by patrickhulce** [comment]
Ah, thanks for sharing the file. There must be a different bug here since we think it could be 62% smaller and the source map comment definitely isn't responsible for that :)
