### ISSUE TITLE
Minification audit early exits on string interpolation

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6746]
```
const world = 'world';
`${`hello ${world}`}`;
```

**Comment by Hoten** [comment]
Would require a large refactor of the parser, since the current implementation only tracks two characters at a time + various binary states, but fixing this issue (and similar) would require using a pushdown automata, since JS is [(mostly) a CFG](https://stackoverflow.com/a/30698970/2788187).

**Comment by paulirish** [comment]
Mostly fixed by #6745. Let's ignore the edgecases. :)
