### ISSUE TITLE
How do you view the full URLs?

### ISSUE THREAD

**Issue by chromio69** [GoogleChrome/lighthouse#6765]
How do you view or export the full "problem URLs" in the report? When you click on it you get a preview...but how do you copy that?

Apologies if this has been covered, I did some searching but came up empty.

**Comment by Hoten** [comment]
Do you mean the various URLs that show up in tables across various audits? If so, [we just got someone on that](https://github.com/GoogleChrome/lighthouse/pull/6625#issuecomment-445877043).

**Comment by chromio69** [comment]
Yes, the various URLs for pretty much every issue. Thanks!
