### ISSUE TITLE
Save as PDF doesn't include pass/fail icon for each section

### ISSUE THREAD

**Issue by bozzmedia** [GoogleChrome/lighthouse#6769]
#### Provide the steps to reproduce
1. Run LH on any site

#### What is the current behavior?

When viewing the report in Lighthouse viewer, the score symbol (pass/fail - checkmark / x) does not appear when printing or saving as PDF. This is one of the more important features of a report as it provides a clear pass/fail score for each segment.

#### What is the expected behavior?

Pass/fail symbols are included in PDF/print outs, just as Save as HTML works.

How it looks:
![screenshot_121018_084511_pm](https://user-images.githubusercontent.com/4435114/49778914-57175c00-fcbc-11e8-8da5-16d2a6168892.jpg)

How it should look (notice green icons):
![screenshot_121018_084641_pm](https://user-images.githubusercontent.com/4435114/49778963-829a4680-fcbc-11e8-8c97-942bbc48a659.jpg)

#### Environment Information
* Affected Channels: Devtools
* Lighthouse version: 3.03
* Node.js version:
* Operating System: Windows 10

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @bozzmedia! I'm not able to reproduce this behavior though :/ I tried both with version 3.0.3 and latest 4.0.0-beta. Any specific steps you're taking that might've been left out?

![image](https://user-images.githubusercontent.com/2301202/49805491-db003100-fd1a-11e8-815e-1b4282e3fce8.png)

**Comment by bozzmedia** [comment]
Whoops I did miss a step! I used Firefox for this step - Can confirm it works fine in Chrome. Sorry for overlooking that important detail :0
