### ISSUE TITLE
Config: rawValue -> expectedValue

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#677]
The [config uses](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/default.json#L110) the name "rawValue" to set expected values for an artifact. This is pretty confusing b/c an Audit has specifies a "rawValue" in its output.

These should probably be renamed "expectedVal" (config) and "actualVal" (audit artifact).

**Comment by paulirish** [comment]
👍

**Comment by ebidel** [comment]
TBH, I'm not 100% sure what the values in config.json are for. They appear to not be used and the ones set in the artifact/audit are. Related: https://github.com/GoogleChrome/lighthouse/issues/672

**Comment by paulirish** [comment]
I believe they're used here: https://github.com/GoogleChrome/lighthouse/blob/9f7f87adb7de16c6c5d3d84bc70e018ba9de369a/lighthouse-core/aggregator/aggregate.js#L73-L109

If that is indeed the case, then the values themselves are discarded and only the `typeof` is used.

**Comment by brendankenny** [comment]
closing in favor of the more general #688
