### ISSUE TITLE
Lighthouse DevTools ignores flags in m71+

### ISSUE THREAD

**Issue by LeonDWong** [GoogleChrome/lighthouse#6772]
**Summary**
I had generated an audit report in Chrome 70.xxx which is fine. But the TTI in report is much longer than previous one which is generated by latest chrome 71.0.3578.80 in same page(without any code update). Then i try to audit gmail web site, it generated similar bad performance report while web should perform better in real world.
gmail web site in chrome 71.0.3578.80 lighthouse:
![image](https://user-images.githubusercontent.com/17465046/49804620-fce6cb80-fd8d-11e8-8195-3a8996743317.png)

![image](https://user-images.githubusercontent.com/17465046/49804546-c446f200-fd8d-11e8-9e6e-43672423d77b.png)
Could anyone help? Thx in advance.

**Comment by patrickhulce** [comment]
Thanks for filing @LeonDWong! Do you have a URL for your page you're willing to share?

A few things to note:

1. The metrics are computed by simulating a user's typical hardware (a Nexus 5X on slow 4G is our standard target). From your Runtime Settings I can see you're running the audit on a pretty fast Mac, so it's expected that the metrics reported will be higher than what you get loading the page yourself.
2. I don't see any page screenshots in the filmstrip of the report you shared. Are you sure the page is loading correctly/fully?

**Comment by hueyhe** [comment]
In Chrome 71 audit used a mobile user agent even if i chose `Desktop` as device. It works fine with the previous 70 version.

**Comment by LeonDWong** [comment]
@patrickhulce Hello, thx for your reply. Then page i test is [gmail](https://mail.google.com/), just login needed. 
And for the things you noted, the time for simulating a user's typical hardware (a Nexus 5X on slow 4G is our standard target) in chrome 70 version is much shorter than 10s. And the page is loading correctly thought the screen i share first shows empty. 
And i find out that fetching time takes 6s, is there any problem in network simulation in chrome 71 version ?
![image](https://user-images.githubusercontent.com/17465046/49844716-0d835a00-fdff-11e8-99cd-ddd2590b92ce.png)

**Comment by LeonDWong** [comment]
> In Chrome 71 audit used a mobile user agent even if i chose `Desktop` as device. It works fine with the previous 70 version.

+1

**Comment by Erbenos** [comment]
I am currently experiencing same issue.

**Comment by AlexMoore94** [comment]
I also experiencing the same issue on Chrome 71. Even on dev (72) and canary (73) channels.
And also Mobile agent used even when I choose desktop.

My performance score was 100 on Chrome 70 and speed index was about 1.2 sec.
On Chrome 71 now performance score is about 50 and speed index is about 5 seconds.
There were no changes in the code.
Although, network shows that DOMContentLoad event fires after around 1.3s.

**Comment by patrickhulce** [comment]
Thanks all! I can confirm the Desktop issue as well. If the page is loading different content this is likely the explanation for the jump in scores.

**Comment by patrickhulce** [comment]
We've found the culprit, but it'll require a Chrome-side fix.

Note that it's not just Mobile/Desktop, but the throttling settings and clear storage options are also being ignored at the moment which would explain all of the performance score differences.

**Comment by paulirish** [comment]
Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=914387

It's fixed on ToT and we're working on getting a merge to 71 and 72.

**Comment by woodsba** [comment]
Any idea when the update will be merged into 71, or when chrome 72 will be released with the fix in place?

**Comment by FarhanSolaiman** [comment]
The desktop audit runs mobile emulation. even the tooltip says it will run mobile emulation.
![issue](https://user-images.githubusercontent.com/40680452/50950839-36723a00-14e6-11e9-987b-ca03c86918a5.png)

**Comment by patrickhulce** [comment]
@FarhanSolaiman that's actually a separate UX confusion item we're working that doesn't affect the functionality here. The labels only apply to the entire `<input>` group which is the "Device"

**Comment by patrickhulce** [comment]
@dryleaf yes it's been fixed. You can use Canary or Beta today for the fix. 72 should hit stable [in roughly 8 days](https://www.chromestatus.com/features/schedule)

**Comment by mssodhi** [comment]
@patrickhulce still receiving errors in Canary. Here's an attached screen shot from www.yahoo.com site audit. Tested on Version 73.0.3681.0 (Official Build) canary (64-bit).
<img width="1920" alt="screen shot 2019-01-23 at 4 49 04 pm" src="https://user-images.githubusercontent.com/8364496/51646811-00de3f80-1f2f-11e9-94dc-3380004fb7c5.png">

**Comment by patrickhulce** [comment]
@mssodhi that is a different error best described by https://github.com/GoogleChrome/lighthouse/issues/1091. This issue was about the options/checkboxes being silently ignored.

**Comment by mssodhi** [comment]
@patrickhulce thanks! Appreciate it!

**Comment by Hoten** [comment]
Fix is in stable Chrome. If you still see this, make sure you are on 72+ (`chrome://settings/help`). If you are and the issue persists, please open a new issue.

**Comment by zihad7** [comment]
Running lighthouse (Chrome Audit) switches into mobile emulation automatically #6772

**Comment by jkeappock** [comment]
this issue still occurs, any network throttling selections or clear storage selection made is overrided and report applies throttling regardless of selection made

**Comment by Hoten** [comment]
@jkeappock can't repro. you on latest chrome? chrome://version/

**Comment by jkeappock** [comment]
@Hoten thanks I see it has been resolved with version 72
