### ISSUE TITLE
font-display audit resolves URLs relative to document instead of stylesheet

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#6781]
#### Provide the steps to reproduce
1. Run LH on https://www.blue2blond.nl/sitemap.html

#### What is the current behavior?
Lighthouse reports that the `woff2` files are missing font-display

#### What is the expected behavior?
Lighthouse reports that `woff2` files have proper font-display

**Related issues**
 https://github.com/GoogleChrome/lighthouse/issues/6628#issuecomment-446614239

**Comment by blue2blond** [comment]
Thank you Patrick for submitting!

As I now know the the cause of this notification, I changed the CMS in such a way, url's are being made absolute during minifying -relative url's would reduce kilobytes and thus latency, so as soon as it is fixed, I revert the CMS edit ;) -.

As a result, issue can't be reproduced with above url. I made a static page which reproduces this issue:
https://www.blue2blond.nl/projects/pagespeed/lighthouse/relative-font.html
