### ISSUE TITLE
Defer offscreen images issues

### ISSUE THREAD

**Issue by devasick** [GoogleChrome/lighthouse#6797]
i have added lazy load but still showing error but help me and website score is very low

[https://theelitecars.com/Capture.PNG](url)

**Comment by devasick** [comment]
I have added lazy load images but Defer offscreen images will not affect on lighthouse
Please check below URL 
https://theelitecars.com/

**Comment by exterkamp** [comment]
Looked into this a little bit more, seems like the total overall payload of images is high, but it also seems like the JS is holding up the main thread causing a long pull on TTI and performance.
![image](https://user-images.githubusercontent.com/6392995/50188693-4461e000-02d7-11e9-9380-acdf4486c756.png)
Running a performance check on the site (with 4x CPU slowdown and Fast 3G) shows a heavy amount of script work being done on the main thread.  This might be the culprit around the low performance along with the large amount of images being loaded.
![image](https://user-images.githubusercontent.com/6392995/50188731-68252600-02d7-11e9-87fb-f3f686c70eb3.png)

**Comment by brendankenny** [comment]
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen

**Comment by DouradoLuxuryCar** [comment]
You need to install, one more "LiteSpeed Cache" plugin to improve speed. 
**Exotic Supercars for Sale in Dubai UAE** https://douradocars.com/luxury-cars-for-sale-dubai/
