### ISSUE TITLE
Modify Accept header to not include WebP

### ISSUE THREAD

**Issue by andrewb273** [GoogleChrome/lighthouse#6805]
I want to test a site's performance for when the browser doesn't support WebP images - specifically Safari. This site delivers WebP images when `image/webp` is in the `accept` header, otherwise it delivers PNG or JPEG. As such, I want to remove `image/webp` from the `accept` header.

Is this possible? Happy to even jump into the code if someone can point me in the right direction. Though I'm concerned it may not be possible given leveraging off Chrome.

**Comment by andrewb273** [comment]
Hoping there's something easier than forking Chromium and tweaking the accept header there - https://github.com/chromium/chromium/blob/2ca8c5037021c9d2ecc00b787d58a31ed8fc8bcb/services/network/loader_util.cc#L25

We're wanting to run these tests on public cloud instances (was hoping functions but probably will be docker containers), so the more simple the setup, the better.

**Comment by patrickhulce** [comment]
You can do what you're talking about with requestInterception and the puppeteer api (https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue). See #3837 for a bit of discussion on getting it to work with Lighthouse.

**Comment by andrewb273** [comment]
Ah ok fantastic, that's encouraging to see. Would be great to provide an example of the integration, maybe I could do a PR if I end up undertaking this. I'd think that testing for performance without WebP support would be a pretty common objective.
