### ISSUE TITLE
Head childs doesn't have to be evaluated in Maximum Child Elements

### ISSUE THREAD

**Issue by marcmrf** [GoogleChrome/lighthouse#6806]
#### Provide the steps to reproduce
1. Run LH on https://andro4all.com/
2. Check "Avoid an excessive DOM size" point on Diagnostics.

#### What is the current behavior?
Right now is failing due to Maximum Child Elements, 79, which is bigger than the 60 recommended. The parent element is the head.

#### What is the expected behavior?
Most of the elements placed in the head are metas, pre-connects, fetch's... As the number of the elements in the head doesn't affect to rendering performance, they have to be omitted in this check.

#### Environment Information
* Affected Channels: Devtools
* Lighthouse version: Lighthouse 4.0.0-beta
* Operating System: macOS

**Comment by patrickhulce** [comment]
A fair point thanks for filing @marcmrf! 

@ebidel any reason you can remember that you included the `head` elements long, long ago? :)

**Comment by midzer** [comment]
So it seems we're only looking for render relevant nodes under `<body>`. Might be an idea to filter them by using `nodeInBody(node)` function located right now in `font-size.js`

**Comment by ebidel** [comment]
The original goal of the audit was to raise awareness to apps that create excessive DOM trees which can put a burden on layout/style recalcs and the general advise we got from the Chrome team was < 60 nodes per parent. I'm not sure there was any reason in particular we included `<head>` elements, other than for completeness. Possibly call out usage of old school meta/link tags which are no longer needed.

**Comment by ebidel** [comment]
The other thing might be to avoid loads of markup in head. Means more markup to parse on a slow mobile connections, possible blocking inline scripts and other resources, and a slower first render. But those things could be captured in other perf audits.

**Comment by paulirish** [comment]
Yeah lets only include elements inside the body.

**Comment by patrickhulce** [comment]
Sounds good @midzer thanks!

**Comment by brendankenny** [comment]
Fixed by #7241
