### ISSUE TITLE
Canary/Dev Chrome errors for Performance/PWA categories

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6811]
Latest Canary/Dev returns error'd results for Performance and PWA categories. The error is `Could not find any top level events`.

Root cause is a new feature behind a trial period, so not all clients will encounter it.  A refactor to some scheduler stuff in Blink has removed a tracing event that Lighthouse expects, and thus many audits fail fantastically. Running Canary Chrome with `--enable-features=BlinkMainThreadUsesSequenceManager` will enable the new feature.

**Comment by paulirish** [comment]
Thread on scheduler-dev: https://groups.google.com/a/chromium.org/d/topic/scheduler-dev/L8bH-sE43X4/discussion

Also looks like it's running at ~half in canary and dev, but I'm not sure.

**Comment by Hoten** [comment]
I'm not seeing this anymore. @paulirish can you confirm?

**Comment by paulirish** [comment]
Ayup.  This was fixed via:

https://chromium-review.googlesource.com/c/chromium/src/+/1378815 and
https://chromium-review.googlesource.com/c/chromium/src/+/1383146
