### ISSUE TITLE
Performance stays 0

### ISSUE THREAD

**Issue by UisgeBeatha436** [GoogleChrome/lighthouse#6814]
I'm running the Lighthouse test over and over, but the score for performance stays at 0, no matter what improvement I make. 

> Runtime settings
> URL: https://bit.ly/2UO4ETA
> Fetch time: Dec 15, 2018, 11:22 AM GMT+1
> Device: Emulated Nexus 5X
> Network throttling: 150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
> CPU throttling: 4x slowdown (Simulated)
> User agent (host): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3639.1 Safari/537.36
> User agent (network): Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3559.0 Mobile Safari/537.36
> CPU/Memory Power: 1056

Any help is highly appreciated! In case more info is needed, please let me know.

**Comment by patrickhulce** [comment]
That's because your main page is 3.5MB which takes 18+ seconds to download on a mobile network. You need to make your initial payload much, *much* smaller to see improvement in the performance metrics. Move the things you don't absolutely need to deliver a first paint into other resources that can be loaded later.

**Comment by UisgeBeatha436** [comment]
Thanks. I'll investigate. I noticed after my post while working on Accessibility and Best Practische, the performance sometime shows a number between 33 and 40 and sometime showing a '?'. I.o.w. the figure shown is not constantly the same. 

Do you perhaps have suggestions on how to investigate the initial payload? If I look up the site on my mobile, connected via wifi, I don't count to 18seconds, only takes a couple of seconds and the site is there.

**Comment by patrickhulce** [comment]
>  connected via wifi

Performance is not measured with a wifi connection, it's measured on a simulated slow 4G connection. Move the things you don't absolutely need to deliver a first paint into other resources that can be loaded later.
