### ISSUE TITLE
Bakend Error

### ISSUE THREAD

**Issue by RealDotNetDave** [GoogleChrome/lighthouse#6820]
When I use my website http://dotNetTips.com to try to process, I get this error:

Error: Backend Error

If I use, https://dotnettips.wordpress.com, that doesn't work either.

**Comment by ebidel** [comment]
I can repro this using http://dotnettips.com/ on web.dev/measure. The error I get from  LH API is "exhausted render retries".

<img width="877" alt="screen shot 2018-12-16 at 12 48 22 pm" src="https://user-images.githubusercontent.com/238208/50058709-fca15400-0130-11e9-8122-f6a3538ee75a.png">

**Comment by Hoten** [comment]
Thanks for reporting @RealDotNetDave. I'll look into this.

Some notes so far;

Testing Lighthouse in DevTools in Chrome stable (71.0.3578.98):

Logs from Lighthouse:
```
Request Network.setRequestInterception failed. {"code":-32601,"message":"'Network.setRequestInterception' wasn't found"}
```

Logs from target page:
```
Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details

onloadwff.js:79 Uncaught TypeError: Cannot read property 'teardown' of undefined
    at onloadwff.js:79 ---- (maybe not relevant)
```

FWIW, I confirmed that Lighthouse CLI works for this page, for master and `3.2.0`.

**Comment by Hoten** [comment]
Scratch that last line - it does not work in `3.2.0`

```
npx -p lighthouse@3.2.0 lighthouse http://dotnettips.com/ --view # NO_TRACING_STARTED
npx -p lighthouse@4.0.0-beta lighthouse http://dotnettips.com/ --view # NO_TRACING_STARTED
```

But, it does work in master. So let's chill this ticket and circle back when we deploy 4.0.0 to the backend for PSI/web.dev.

**Comment by brendankenny** [comment]
This is working on master and web.dev/measure now. Closing in favor of the more general issues around improving handling and communication of errors.
