### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Emulation.setCPUThrottlingRate

### ISSUE THREAD

**Issue by thescenela504** [GoogleChrome/lighthouse#6824]
**Lighthouse Version**: 3.3.0.4001
**Lighthouse Commit**: 66100367e39d970f8208bd30c10bd97cc7240784
**Chrome Version**: 71.0.3578.98
**Initial URL**: https://www.bandlab.com/mix-editor
**Error Message**: PROTOCOL_TIMEOUT Method: Emulation.setCPUThrottlingRate
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Emulation.setCPUThrottlingRate
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18993:11)
```

**Comment by exterkamp** [comment]
deduping to #6512
