### ISSUE TITLE
Jquery main library and adding passive scroller to it? 

### ISSUE THREAD

**Issue by halukkaramete** [GoogleChrome/lighthouse#6825]
**Summary**

This is what I have in the things to fix list and could someone tell me what's needed here? 

This is what prevents from scoring 100%! on the best practices. 
/jquery-3.3.1.min.js(code.jquery.com) | line: 1
Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance. Learn more.

**Comment by midzer** [comment]
Hi @halukkaramete 
somewhere in your app scroll performance can be improved by setting scroll event listener to passive. Check out https://developers.google.com/web/updates/2016/06/passive-event-listeners
