### ISSUE TITLE
no manifests fetched 

### ISSUE THREAD

**Issue by halukkaramete** [GoogleChrome/lighthouse#6826]
**Summary**

I'm unable to see what's wrong here? ( please take a look at the last line, the one that I starred) and be informed that all this is properly doctyped html head tag. And yet, I get this as failing audit. Could you show me what's wrong here? 

Address bar does not match brand colors  Failures: No manifest was fetched.

```
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=5, "/>
**<meta name="theme-color" content="#424345"/>**
```

**Comment by exterkamp** [comment]
Hi, and thanks for filing this issue, I have an idea what might be going wrong, but it'd be helpful to get some more background.  

- What Lighthouse version are you using?
- What tool are you using?  (devtools audits panel, cli, extension)
- What is the URL you are testing?

**Comment by brendankenny** [comment]
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen.
