### ISSUE TITLE
GoogleAnalytics as a culprit?

### ISSUE THREAD

**Issue by halukkaramete** [GoogleChrome/lighthouse#6827]
**Summary**

Thank you Lighthouse team for this great too. I'm just asking to learn ( not as a criticism at all).  I find it odd to see this notice when the script in subject happens the Google's very own analytics script. What can I do pass this audit? 

Thank you...

Culprit: https://www.google-analytics.com 
Avoid multiple, costly round trips to any origin

Consider adding preconnect or dns-prefetch resource hints to establish early connections to important third-party origins. Learn more.

**Comment by paulirish** [comment]
IMO you should use link rel=preconnect with that origin.

**Comment by halukkaramete** [comment]
Thanks Paul. But Google is a script, No? Your suggestion of "rel=preconnect" is a CSS link. 
But I may also be is-interpreting the original warning which is "Avoid multiple, costly round trips to any origin.... Consider adding preconnect or dns-prefetch resource hints to establish early connections to important third-party origins. "....  

But then, the only thing I got on the page ( that has to do with the analytics ) is the [script][/script] way of including analytics with 0 .css ref in it. So I'm unable to understand where this warning pointing me to look into.

**Comment by patrickhulce** [comment]
> Your suggestion of "rel=preconnect" is a CSS link.

`rel=preconnect` is not a CSS link, it's a directive instructing the browser that you will be making requests to a particular origin (any request: image/XHR/script/CSS/etc) and that it should connect to it early.

Protip: The learn more link in the report explains what each audit is about (in this case, https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect)

**Comment by regulus33** [comment]
First of all many thanks to everyone contributing to this tool, It has improved my work immensely and taught me a lot as well. But I have also had a consistent issue with google vendor code and my performance score.

Lighthouse is still dinging me for a long TTI when adding Google Tag Manager. (no custom html) I've tested in lighthouse dev tools and subtracting all html, css, images and js **except** for GTM, the test will render almost identical results!

 I've optimized everything else I possibly can(code splitting, defering images, static cacheing etc.) I'm getting marked down for code written by Google itself and I'm not sure how to proceed. Has anyone else encountered a similar issue? any suggestions?

**Comment by patrickhulce** [comment]
Google Tag Manager, while convenient and useful, adds a layer of indirection to your site that delays when scripts will execute. It's generally a trade-off between convenience and performance that needs to be made on a case-by-case basis. 

Do you have an example public URL where GTM alone is causing significant impact like forcing a site into the red?
