### ISSUE TITLE
WIP: LH Issue Runner Testing Issue

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6830]
test my url: https://hoten.cc/blog/

**Comment by Hoten** [comment]
LH Runner Go! http://www.example.com

**Comment by Hoten** [comment]
LH Runner Go! https://www.paulirish.com/

**Comment by Hoten** [comment]
LH Runner Go! https://www.paulirish.com/

**Comment by Hoten** [comment]
^ master has a page load time out set, so when LH hangs on an insecure page (#6608 not merged yet) it times out in master. but all the other versions just hang forever and the bot script just gives up eventually :)

**Comment by Hoten** [comment]
LH Runner Go! https://zach.diemer.codes/

**Comment by Hoten** [comment]
LH Runner Go! https://hoten.cc/blog/

**Comment by Hoten** [comment]
Set up a timeout around each run, so if LH hangs the bot still reports something

**Comment by connorjclark** [comment]
I ran Lighthouse for https://hoten.cc/, here's what I found.

[index](http://lh-issue-runner-6830.surge.sh)
✅ [html](http://lh-issue-runner-6830.surge.sh/lighthouse@7.0.0.report.html) [json](http://lh-issue-runner-6830.surge.sh/lighthouse@7.0.0.report.json) [output](http://lh-issue-runner-6830.surge.sh/lighthouse@7.0.0.output.txt) lighthouse@&#8203;7.0.0
✅ [html](http://lh-issue-runner-6830.surge.sh/lighthouse@6.5.0.report.html) [json](http://lh-issue-runner-6830.surge.sh/lighthouse@6.5.0.report.json) [output](http://lh-issue-runner-6830.surge.sh/lighthouse@6.5.0.output.txt) lighthouse@&#8203;6.5.0
✅ [html](http://lh-issue-runner-6830.surge.sh/lighthouse@5.6.0.report.html) [json](http://lh-issue-runner-6830.surge.sh/lighthouse@5.6.0.report.json) [output](http://lh-issue-runner-6830.surge.sh/lighthouse@5.6.0.output.txt) lighthouse@&#8203;5.6.0
✅ [json](http://lh-issue-runner-6830.surge.sh/PSI.report.json) [output](http://lh-issue-runner-6830.surge.sh/PSI.output.txt) PSI
✅ [html](http://lh-issue-runner-6830.surge.sh/lighthouse@master-96eda6.report.html) [json](http://lh-issue-runner-6830.surge.sh/lighthouse@master-96eda6.report.json) [output](http://lh-issue-runner-6830.surge.sh/lighthouse@master-96eda6.output.txt) lighthouse@&#8203;master-96eda6
