### ISSUE TITLE
Bot: LH Issue Runner

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6831]
Code is here: https://github.com/Hoten/lh-issue-runner

Example run here: https://github.com/GoogleChrome/lighthouse/issues/6830

Currently, the bot runs

1. if an issue has the label `needs-lh-runnner`
2. if a comment requests it, via `LH Runner Go!`

Open questions:
1. Could this be extended to post a comment when a URL is missing? What about issues that don't have a particular URL (like this one! but are there many?) - should there be a "don't bug me about a url" substring that is in the default issue template (kinda gross)?
2. Could this be done automatically, without requiring a label?
3. How could the DevTools entry point be tested? Is it possible to use puppeteer to run LH via the Audits panel?
4. ditto for the extension
5. any suggestions for the comment template?

Once these questions are resolved we can set it up on the same machines running DZL :)

**Comment by brendankenny** [comment]
> 3. How could the DevTools entry point be tested? Is it possible to use puppeteer to run LH via the Audits panel?
> 4. ditto for the extension

- maybe for devtools?
- yes for extension. We do that in [`extension-test.js`](https://github.com/GoogleChrome/lighthouse/blob/51d204762ea6865e8de28ce4b54e36e058833a5d/clients/test/extension/extension-test.js)

**Comment by Hoten** [comment]
Paul nearly got it working for devtools, but kept finding gremlins.

Found a way to pull down the latest LH extension and test that entrypoint.
