### ISSUE TITLE
Non-descriptive link text in Lighthouse reports

### ISSUE THREAD

**Issue by rodoch** [GoogleChrome/lighthouse#6834]
When measuring website performance via web.dev, I noticed links in the sites being scanned were getting penalised under the following best practice in the SEO category:

> ## Links do not have descriptive text
> Descriptive link text helps search engines understand your content. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/descriptive-link-text).

<img width="846" alt="screen shot 2018-12-18 at 14 54 56" src="https://user-images.githubusercontent.com/5305694/50161919-f4821980-02d4-11e9-98a7-a92a76e3d919.png">

Reading the information provided via the 'Learn more' link I saw that Lighthouse flags generic link descriptions including... 'Learn more'. (See also #4494)

Apart from being slightly ironic, might it be worth reviewing the naming of 'Learn more' links in Lighthouse reports for consistency and to avoid confusion for developers? (Personally, I think this particular rule is over-strict as the naming of links - once semantically correct and as part of well-structured HTML - is often context-dependent, but if it's going to be enforced consistency is good.)

Thanks!
R.

**Comment by exterkamp** [comment]
We appreciate the irony! :smile:  And are working on it in issue #5349
