### ISSUE TITLE
support request blocking in devtools

### ISSUE THREAD

**Issue by cheneytsai** [GoogleChrome/lighthouse#6838]
**Feature request summary**

WPT and CDT all have abilities to block specific resources in order to determine impact of inclusion/removal on page performance. It'd be useful to be able to define what resources to block for a given set of LH runs to then compare potential impact of a resource on your resulting LH metrics. 

Maybe =)

**What is the motivation or use case for changing this?**
Devs often wonder what's the impact of a certain set of changes. This will help them validate opportunities to pursue. 

**How is this beneficial to Lighthouse?**
It improves the ability of LH to provide continued insight to performance enhancements with a tighter feedback cycle (vs. creating a build that LH can be run against)

**Comment by jumpalottahigh** [comment]
Second this. It could be nice if there was an option in Lighthouse to take into consideration resources blocked in the `Request blocking` tab. Could help greatly for quick testing potential changes.

**Comment by rjgotten** [comment]
Would _very_ much want this to be able to snapshot performance with/without 'tag management systems' affecting pages.

**Comment by patrickhulce** [comment]
Sorry I must have missed this, but this has already been a feature for a long time.

From the CLI, `--blocked-url-patterns='*.png' --blocked-url-patterns='*.jpg'`
From the config, it's setting `settings.blockedUrlPatterns` to an array of patterns `['*.png', '*.jpg']`

**Comment by Hoten** [comment]
@patrickhulce I just confirmed that the network request blocking (via devtools) is not honored by Lighthouse.

**Comment by patrickhulce** [comment]
That's true we could manually grab the blocked URL patterns and just repeat those.

The larger effort part is referring to the other way of solving this (and the only way to solve the network overrides piece) which is reusing the same connection in DevTools so all settings are respected instead of creating our own connection.

**Comment by paulirish** [comment]
related: #5423 local overrides support

**Comment by brendankenny** [comment]
deduping into #5423 as the remaining part of this is DevTools specific and of the related issues, #5423 has the lowest priority and most labels :)

**Comment by brendankenny** [comment]
> lowest priority

and by lowest, I mean highest priority, lowest number :)
