### ISSUE TITLE
Should icons audit check that icon actually exists?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#684]
I noticed that the audit that makes sure the manifest references a 192-pixel icon doesn't actually check if the icon exists in the cache. It just parses the manifest and makes sure that it defines a 192x192 size icon.

**Comment by brendankenny** [comment]
@paulirish you mentioned devtools has to do some tricky thing to get these in the application panel. Worth doing?

**Comment by ebidel** [comment]
Marking as dupe of https://github.com/GoogleChrome/lighthouse/issues/789.
