### ISSUE TITLE
Rename "manifest contains icons at least 192px" to more user-friendly name

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#685]
When I read that audit title, I was only able to guess at why it was important because I was already familiar with icons and A2HS.

I suggest renaming this to "Manifest contains optimal icon for Android homescreens".

This has the added bonus of calling out the fact that [the audit is really only suited for Android](https://github.com/GoogleChrome/lighthouse/issues/291#issuecomment-217352310). Other OSs may require different icon sizes for optimal presentation.

**Comment by paulirish** [comment]
It's called 'installable-manifest' now. Thanks for the suggestion. :)
