### ISSUE TITLE
<html> not full screen while auditing

### ISSUE THREAD

**Issue by liyuanqiu** [GoogleChrome/lighthouse#6850]
#### Provide the steps to reproduce
1. Run LH on <affected url>
https://www.google.com/
#### What is the current behavior?
![image](https://user-images.githubusercontent.com/24999464/50258714-d08d1800-043b-11e9-9f20-7544127bce1a.png)
![image](https://user-images.githubusercontent.com/24999464/50258725-dd117080-043b-11e9-97dd-c8a3ef9acb31.png)

#### What is the expected behavior?
The web page should be in full screen while auditing.

#### Environment Information
* Affected Channels: 
Chrome DevTools [Chrome Version 71.0.3578.98 (Official Build) (64-bit)]
* Lighthouse version:
Lighthouse 3.2.0
* Node.js version:
None
* Operating System:
macOS Mojave 10.14

**Related issues**

**Comment by patrickhulce** [comment]
This is because it's running mobile emulation due to #6772, a fix is pending a merge to stable.
