### ISSUE TITLE
"Manifest contains short_name" audit is misleading

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#686]
It checks for `short_name` or `name`. Is the goal to just make sure that some name is provided for the app? In which case maybe the audit should be renamed to something more generic?

**Comment by kaycebasques** [comment]
Actually, just noticed that we also have an audit for `name`...

**Comment by brendankenny** [comment]
We could clarify this, but for some background, see #348 (and linked twitter thread)

**Comment by Onset** [comment]
In addition `Manifest's short_name will be truncated when displayed on homescreen` is misleading too if you haven't any manifest.

**Comment by paulirish** [comment]
duping into  #2698
