### ISSUE TITLE
DevTools Error: PROTOCOL_TIMEOUT Method: Emulation.setScriptExecutionDisable

### ISSUE THREAD

**Issue by robinwilson16** [GoogleChrome/lighthouse#6868]
This happens when trying to run the Lighthouse auditing tool in Windows 10 - asked me to file a bug so I said yes and it posted the text below:

**Initial URL**: https://localhost:44322/
**Chrome Version**: 73.0.3649.0
**Error Message**: PROTOCOL_TIMEOUT Method: Emulation.setScriptExecutionDisabled
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Emulation.setScriptExecutionDisabled
    at setTimeout (chrome-devtools://devtools/remote/serve_file/@aa4dee7b03e76387c8264d3f2a9c8f2dce3bc729/audits2_worker/audits2_worker_module.js:998:210)
```

**Comment by patrickhulce** [comment]
duplicate #6512

**Comment by robinwilson16** [comment]
It only happens if running Lighthouse on localhost I believe as seems fine if run against a published website. Maybe you are not supposed to run it locally.

Does the error happen as the remote dev tools cannot access the local resource?
Still I suppose ideally it should check if initiated from localhost and then not go any further or skip this part of the assessment if it would not work.
I actually meant to run it on the published site but had too many Chrome windows open!
