### ISSUE TITLE
renaming confusing config properties

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#688]
The config file was put together very quickly and has evolved somewhat haphazardly, so it's time to take a look at cleaning it up. Here's a list of properties in [the config file](https://github.com/GoogleChrome/lighthouse/blob/8c17a100a724a47ca57ed2237862c97f2f1e1f08/lighthouse-core/config/default.json) I've witnessed confuse some users, and a suggestion for how they could be changed. Feel free to bikeshed away and add more. After this we can start documenting re: #672 

Note that if we change these, anyone with a custom config will be broken, so we probably want to do this right once and then stick to them until LH2.0.
- [ ] `passes` -> `gathererPasses`
  
  [Example](https://github.com/GoogleChrome/lighthouse/blob/8c17a100a724a47ca57ed2237862c97f2f1e1f08/lighthouse-core/config/default.json#L2). "What is a pass?" We need to make clear this is for the gathering stage, but no need to nest within another object. @paulirish also had some notion around a name that makes it clearer these are each a page reload.
- [x] `network` -> `recordNetwork`
  
  [Example](https://github.com/GoogleChrome/lighthouse/blob/8c17a100a724a47ca57ed2237862c97f2f1e1f08/lighthouse-core/config/default.json#L3). Needs to be clear that this isn't offline/online, but about getting a record of the network requests at the end of the pass. If not present, defaults to `false`.
- [x] `trace` -> `recordTrace`
  
  [Example](https://github.com/GoogleChrome/lighthouse/blob/8c17a100a724a47ca57ed2237862c97f2f1e1f08/lighthouse-core/config/default.json#L4). Less necessary, but useful to be parallel to `recordNetwork`. Defaults to `false`.
- [x] `loadPage` -> 💥
  
  [Example](https://github.com/GoogleChrome/lighthouse/blob/8c17a100a724a47ca57ed2237862c97f2f1e1f08/lighthouse-core/config/default.json#L5). I'd [still argue](https://github.com/GoogleChrome/lighthouse/issues/589) that `loadPage` isn't necessary, and the extra option is more overhead for devs using LH and for us testing LH. We haven't run into an audit that needs it or has used it yet. Moreover, it's actually non-functional right now, and fixing it would take as much effort as implementing it in the future if someone ever actually needed it. Removing it would involve deleting [a single conditional](https://github.com/GoogleChrome/lighthouse/blob/8c17a100a724a47ca57ed2237862c97f2f1e1f08/lighthouse-core/gather/gather-runner.js#L125) and then from the various config files we have lying around. Currently defaults to `true` if not present, which violates assumptions about truthy/falsy.

Under `aggregations`:
- [ ] `categorizable` -> ?
  
  [Example](https://github.com/GoogleChrome/lighthouse/blob/8c17a100a724a47ca57ed2237862c97f2f1e1f08/lighthouse-core/config/default.json#L75). It would be nice to have a more descriptive name. This is only(?) for report generation, but not at all clear from the name what it does or if it's necessary when writing a custom aggregation. It's possible documenting it may be sufficient.
- [x] `criteria` -> `audits`?
  
  [Example](https://github.com/GoogleChrome/lighthouse/blob/8c17a100a724a47ca57ed2237862c97f2f1e1f08/lighthouse-core/config/default.json#L79). Not completely sure what we should use here, but when writing his own config, @ebidel wondered if these are just audits, why not just call them that. Would make it clear that the keys inside refer to audit names.
- [ ] `items` -> ?
  
  [Example](https://github.com/GoogleChrome/lighthouse/blob/8c17a100a724a47ca57ed2237862c97f2f1e1f08/lighthouse-core/config/default.json#L76). Something more descriptive. Current choice might as well be `things` or `arrayValues` :)
- [x] `rawValue` -> `expectedValue`
  
  [Example](https://github.com/GoogleChrome/lighthouse/blob/8c17a100a724a47ca57ed2237862c97f2f1e1f08/lighthouse-core/config/default.json#L81). From #677. I think the intention was to make the name parallel to `auditResult.rawValue`, but `rawValue` doesn't mean anything to you inside the config file.

Any other ones?
- [ ] documenting config properties

**Comment by ebidel** [comment]
for `rawValue -> expectedValue`, I think @paulirish mentioned these are for figuring out the value type for the report. Maybe it should be `rawValue -> valueIsOfType`? IDK

**Comment by wardpeet** [comment]
In my opinion rawValue is a good choice. The value is raw => whatever comes out of the audit. In config i'm ok with expectedValue in config.

What might also help is maybe a config generator which we once discussed when @paulirish had to leave. Where more information can be given as well for each property

**Comment by brendankenny** [comment]
> In my opinion rawValue is a good choice. The value is raw => whatever comes out of the audit. In config i'm ok with expectedValue.

Yes, this is for the config file only, where `expectedValue` is much clearer to someone writing a custom config. Agreed that `rawValue` on the audit result itself is still a good choice.

**Comment by patrickhulce** [comment]
done enough
