### ISSUE TITLE
Runtime error encountered: [Error: No Chrome Installations Found]

### ISSUE THREAD

**Issue by mauricedb** [GoogleChrome/lighthouse#689]
Trying to use the Lighthouse NPM CLI package on Windows 10 with Chrome 53.0.2785.116 fails for me with the error:

> Runtime error encountered: [Error: No Chrome Installations Found]

I noticed in [chrome-finder.js](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-cli/chrome-finder.js#L70) that it looks for Chrome only in the _Chrome SxS_ folder. I don't have Chome Canary installed and the readme doesn't list this as a requirement.

Should the code also be checking for the regular Chrome or should there be a requirement for Chrome Canary listed?

**Comment by wardpeet** [comment]
should also work with regular chrome but not sure if the cli supports it.
This is definitely a bug

**Comment by mauricedb** [comment]
Add a PR #690 to fix the issue.

**Comment by nivv** [comment]
I get the same error on OSX. I guess there is no support?

**Comment by mauricedb** [comment]
I added support for on Windows which was simple enough, check the PR for my
changes.

Not running OSX so can't do the same and test it there.

Maurice

On Fri, Oct 7, 2016, 11:32 Albin N <notifications@github.com> wrote:

I get the same error on OSX. I guess there is no support?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleChrome/lighthouse/issues/689#issuecomment-252195384>,
or mute the thread

**Comment by nivv** [comment]
@mauricedb 

I installed Canary on OS X. Works fine :)
