### ISSUE TITLE
Code snippet details renderer type

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#6901]
We're building this primarily for [JSON-LD validation results](https://github.com/GoogleChrome/lighthouse/issues/4359), but are hoping to re-use it elsewhere eventually.

The type looks like this: 

```
interface DetailsRendererCodeSnippetItem {
      type: "code-snippet",
      code: string,
      title: string,
      highlights: {
          line: number | null,
          message: string
      }[]
} 
```

Two rendered items:

![screenshot 2018-12-31 at 21 38 53](https://user-images.githubusercontent.com/1303660/50568368-9c253000-0d48-11e9-9990-bfa6ed337d38.png)

--- 

Putting the `code-snippet` items into a single-column table looks bad. I'm planning to create another item type `code-snippet-list` to render them. Does that sound reasonable?

I guess it could also be called `lh-list` since it's really just a list with padding between items.

Not sure if we'd ever want it to be part of a table – [here's how that would look like right now](https://user-images.githubusercontent.com/1303660/50568467-2cb04000-0d4a-11e9-990a-3f75a8d8320d.png).

What do you think about how to structure the item types here?

**Comment by exterkamp** [comment]
I like this look, I definitely agree that a 1 column table would look odd.  Definitely like the look of a full width code-snippet list.

I feel like this could be an `lh-list` or maybe `lh-full-width-list`?

Does each snippet contain the full JSON-LD file for expansion?  Should it be a fixed # of lines, I don't see why we would need to include an expansion on each snippet as long as we would preserve the overall global line numberings.  Just like the +/- 2 lines from the error.

@hwikyounglee thoughts on the look and feel?  Stylistically I might want the gray outlines to go away to match the full width tables' style.

**Comment by mattzeunert** [comment]
@rviscomi brought up linking the JSON-LD item to the node in the DevTools elements panel.

The linking works by [looking for `.lh-node` elements](https://github.com/ChromeDevTools/devtools-frontend/blob/da0e4c607c6bbab206b32d406259daa196869fa7/front_end/audits2/Audits2ReportRenderer.js#L39), so we could render one of those and slightly restyle it. Or we can tweak the DevTools code to pick up `data-path` attributes.

Do we want the UI to look something like this? 

![screenshot 2019-01-06 at 09 42 56](https://user-images.githubusercontent.com/1303660/50734465-81fbaf80-1197-11e9-84ed-e175aa0105f3.png)

**Comment by Hoten** [comment]
> Or we can tweak the DevTools code to pick up `data-path` attributes.

The DT code already uses [`data-path`](https://github.com/ChromeDevTools/devtools-frontend/blob/da0e4c607c6bbab206b32d406259daa196869fa7/front_end/audits2/Audits2ReportRenderer.js#L45) to link to a node.

![image](https://user-images.githubusercontent.com/4071474/50791437-b2fee180-1276-11e9-9ec7-a5021b50933f.png)

Or are you suggesting the DT code just looks for any element (not just `.lh-node`) for `data-path`?

**Comment by mattzeunert** [comment]
> Or are you suggesting the DT code just looks for any element (not just .lh-node) for data-path?

Yeah. Not sure what the final UI will be for the JSON-LD snippets, but I feel it'd be better to avoid `lh-node` rather than overriding its styles.

**Comment by mattzeunert** [comment]
**Current status**

Got some design feedback from @hwikyounglee [https://jsonld-display.glitch.me/#seo](https://jsonld-display.glitch.me/#seo)

![screenshot 2019-01-13 at 11 46 27](https://user-images.githubusercontent.com/1303660/51084867-e505bd00-1728-11e9-8edf-316be0a8e8d3.png)

**Limiting snippet size**

I started truncating the snippets, currently storing 20 lines around each highlight, with a max line length of 200.

New details renderer data:

```
export interface DetailsRendererCodeSnippet {
  type: "code-snippet",
  lines: DetailsRendererCodeSnippetLine[],
  title: string,
  highlights: DetailsRendererCodeSnippetHighlight[]
  lineCount: number
}

export interface DetailsRendererCodeSnippetHighlight {
  /** Line number, starting from 1 */
  lineNumber: number | null,
  message: string
}

export interface DetailsRendererCodeSnippetLine {
  content: string
  /** Line number, starting from 1 */
  number: number
  truncated?: boolean
}
```

**Linking to elements panel**

Going to put this next to the title, but only show it in DevTools.

Will just use `.lh-node` instead of having DevTools pick up `[data-path]`.

**Comment by hwikyounglee** [comment]
Thanks Matt!

Pasting follow-up comments, and feel free to take the ones only that make sense. 
1. For the following case, i.e. error message before code
![image](https://user-images.githubusercontent.com/7561395/51091745-8437ae00-1743-11e9-9437-9aa189a8138c.png)
Does it make sense to swap the order so an error message always come after code?
2. Would we wrap the error message to see it without scrolling? 
Mock for 1 and 2:
![image](https://user-images.githubusercontent.com/7561395/51091762-ccef6700-1743-11e9-827a-6d54131af448.png)
3. For JSON in a single line
![image](https://user-images.githubusercontent.com/7561395/51091771-f6a88e00-1743-11e9-9b47-5f7159f07d19.png)
Does it make sense to do some kind of pretty-print by wrapping at commas?

**Comment by mattzeunert** [comment]
Thanks Hwi!

> Does it make sense to swap the order so an error message always come after code?

If the message appears below a specific line it feels like it belongs to that particular line, even though all lines are highlighted. I'd prefer keeping error messages that don't belong to a particular line at the top.

>Would we wrap the error message to see it without scrolling?

I've partially implemented this. If the code itself is scrollable the error text still scrolls, will see if I find a clean way to prevent that in CSS.

![screenshot 2019-01-15 at 14 15 16](https://user-images.githubusercontent.com/1303660/51185965-6481c080-18d0-11e9-89ad-d03c190b8363.png)

> For JSON in a single line – Does it make sense to do some kind of pretty-print by wrapping at commas?

That would be nice to have 95% of the time, but it's tricky to get right. If we just put a line break after each comma we'd also put line breaks in the middle of strings that contain commas, and the user might think those line breaks are why the JSON is invalid. Given that the JSON is invalid I don't think we can find a 100% safe way to prettify it.

What would be helpful here is a column index for the error or a better error message. I'll check with @rviscomi, but got the feeling that'll be lower priority.

**Comment by hwikyounglee** [comment]
Got it! Thanks for ramping me up on all these points. Thanks Matt!
