### ISSUE TITLE
CPU/Memory Power is different on each run 

### ISSUE THREAD

**Issue by ashuanindian** [GoogleChrome/lighthouse#6907]
Lighthouse Audit gives a completely different result for performance on multiple runs.

The only thing which is different between each run is CPU/Memory Power.

Machine MacBook Pro (Retina, 15-inch, Mid 2014)
Chrome Version 71.0.3578.98
Lighthouse version 3.2.0.
CPU/Memory Power: 1372, 1320, 992

Machine MacBook Pro (Retina, 15-inch, Mid 2014)
Chrome Version 73.0.3658.0
Lighthouse 4.0.0-beta.
CPU/Memory Power: 1329, 1278

web.dev 
Lighthouse version 4.0.0-alpha.1
CPU/Memory Power: 886, 736

All tests are run with the following settings 

Device - Mobile,
Throttling - Simulated Fast 3G, 4x CPU slowdown
The same configuration is used by web.dev https://github.com/GoogleChrome/lighthouse/issues/6654#issuecomment-441732448

#### What is the expected behavior?

It is very difficult to analyze the results because post improvements results are positive on one run and negative on another. 

I believe throttling CPU 4x means throttling the CPU on which lighthouse is running by 4x.
Isn't it possible to simulate CPU used in nexus 5X on web.dev.
1.8 GHz hexacore (4x1.4 GHz Cortex-A53 + 2x1.8 GHz Cortex-A57) 64-bit ARMv8-A

Both Images are from web.dev

<img width="909" alt="screen shot 2019-01-02 at 5 04 55 pm" src="https://user-images.githubusercontent.com/16077116/50590371-c0038580-0eb0-11e9-8937-38ef1bc59d9e.png">

<img width="947" alt="screen shot 2019-01-02 at 5 05 15 pm" src="https://user-images.githubusercontent.com/16077116/50590436-00fb9a00-0eb1-11e9-9338-a713aa30091e.png">

Below scores are from MacBook Pro (Retina, 15-inch, Mid 2014) and Chrome Version 73.0.3658.0

<img width="840" alt="screen shot 2019-01-02 at 5 17 50 pm" src="https://user-images.githubusercontent.com/16077116/50590830-859ae800-0eb2-11e9-859a-81d75a689fb6.png">
<img width="790" alt="screen shot 2019-01-02 at 5 18 00 pm" src="https://user-images.githubusercontent.com/16077116/50590834-8af83280-0eb2-11e9-8f40-c27bfce1e9bd.png">

We are actively working on Performance and this variation of Scores from 37 to 62 is making it very difficult for us to set a benchmark.

**Comment by exterkamp** [comment]
Thanks for submitting an issue!  I ran this site across pagespeed-insight, web.dev, locally in node, and in the extension.  The scores seemed very consistent in PSI, web.dev, and in node (35-45ish).  But when run in the extension it gets >60.  Are you running from the MBP with the extension?  If you run with the node-cli does it still vary widely?

The CPU/Memory Power numbers are an estimated debug statistic and shouldn't effect the score in these ways, when I run locally with power >1200 it generates consistent results with PSI/web.dev which has power ~600.

**Comment by Hoten** [comment]
Let's give the bot I wrote a spin.

LH Runner Go! https://www.makaan.com/delhi-property/uttam-nagar-flats-for-sale-51195

**Comment by Hoten** [comment]
The above bot ran on my machine, and shows PSI scoring 84, node getting 53 and the chrome extension getting 50. So that's wild.

**Comment by patrickhulce** [comment]
If PSI really does get down to ~600 CPU power, then it's probably worth pushing on #6162. That *could* have a meaningful impact on performance numbers.

**Comment by benschwarz** [comment]
Calibre is seeing very consistent benchmark indexes as well as metrics. I know that’s anecdotal “evidence”, but I’d be happy to share some specific details on request

**Comment by ashuanindian** [comment]
@exterkamp I have seen the score from 32 to 60 varying on web.dev itself in multiple runs.

**Comment by patrickhulce** [comment]
It's within the expected range for live sites. Normal-ishly distributed with a max range of ~25 is a fairly reasonable range for sites that aren't making explicit efforts to be stable for measurement. It's a tad high in our post-lantern world, but not shocking.

(Histogram below for those who might find it easier to interpret the data that way 😃)

![image](https://user-images.githubusercontent.com/2301202/50667496-2eaf1480-0f7f-11e9-9376-3eba95704c15.png)

For reference, with DevTools throttling the 95% confidence interval for most sites was typically +/- 15 on the performance score. Lantern is roughly half that for most sites +/- 8. For curious visitors, you can [read more about variance in our comprehensive doc](https://docs.google.com/document/u/2/d/1BqtL-nG53rxWOI5RO0pItSRPowZVnYJ_gBEQCJ5EeUE/edit?usp=sharing)

**Comment by ashuanindian** [comment]
Thanks, @patrickhulce for sharing the document.
Its will help us in moving forward for our performance goals.

**Comment by paulirish** [comment]
Plan is to set a fixed multiplier in PSI where we have a benchmarkindex of ~800, which is 1/2 of a typical laptop.

**Comment by exterkamp** [comment]
@patrickhulce is exploring this more and capturing some data on it here #9085

**Comment by exterkamp** [comment]
Deduping for #9085

**Comment by kirthikasimi** [comment]
Why does the CPU power differ everytime we run lighthouse report on chrome web devtools , is it the user machine CPU power (ranges from 1200-1500)  and everytime we run pagespeed insights is it the google server CPU power(800-1000)?
