### ISSUE TITLE
Local Storage is cleared even if the the "Clear Storage" box is unchecked

### ISSUE THREAD

**Issue by LaurentRos** [GoogleChrome/lighthouse#6908]
#### Provide the steps to reproduce
1. Run LH on _any web app using local storage. Particularly for their authentication =)_

#### What is the current behavior?

- When running an audit with the "Clear Storage" box unchecked, the local storage is cleared anyway
    - Impact: We are unable to test pages with authentication

#### What is the expected behavior?

- When running an audit with the "Clear Storage" box unchecked, the local storage is not cleared

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: N/A
* Node.js version: N/A
* Operating System: Ubuntu 16.04 + MacOS Mojave 10.14.2

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @LaurentRos! This seems like a duplicate of #6772. Can you try out Chrome Canary?

**Comment by emilhein** [comment]
I had the same issue in version Version 71.0.3578.98 of chrome. I triede the chrome canary, which seems to fix the issue. So i assume it will come as a later fix

**Comment by patrickhulce** [comment]
Yep, fixed in m72+

**Comment by arinmis** [comment]
Same issue in version  100.0.4896.88.

**Comment by adamraine** [comment]
@arinmis this issue is pretty old, can you file a new bug with reproducible steps

**Comment by arinmis** [comment]
@adamraine thank you for your interest, I have fixed my issue. It wasn't about storage. Should I delete my comment?
