### ISSUE TITLE
PAge speed Issue

### ISSUE THREAD

**Issue by Niharikakeju** [GoogleChrome/lighthouse#6914]
Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. net::ERR_TIMED_OUT.

Why this Issue showing ?

**Comment by paulirish** [comment]
net::ERR_TIMED_OUT means the webserver didn't respond with any HTML.
