### ISSUE TITLE
make a --dobetterweb flag

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#693]
to fulfill @samccone's [prophecy](https://github.com/GoogleChrome/lighthouse/pull/663#issuecomment-247504829), let the flag bloat begin! Right now to test dobetterweb you have to add something like `--config-path=lighthouse-core/config/dobetterweb.json`. It would be nice to have a `--dobetterweb` flag for it.

(alternatively, it may be time to just go with his `--preset perf`, `--preset dobetterweb` idea from that thread)

**Comment by samccone** [comment]
:goat:

**Comment by ebidel** [comment]
Didn't see this, but I did https://github.com/GoogleChrome/lighthouse/pull/696 for quick testing. I think we can do a flag later when dbw™️ is more official. WDYT?

**Comment by brendankenny** [comment]
closing for #696
