### ISSUE TITLE
Lighthouse unable to recognize service worker

### ISSUE THREAD

**Issue by AKPMultimedia** [GoogleChrome/lighthouse#6935]
Google Lighthose is sometimes unable to recognize the properly installed Service Worker. Sometimes it works and sometimes it doesn't.

https://www.ackeller.ch/

**Comment by patrickhulce** [comment]
Thanks for filing @AKPMultimedia! Any details on how you're running Lighthouse? DevTools? Extension? Node CLI? What's your environment?

If you could fill out the environment questionnaire in our [bug report template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) that'd be great!

**Comment by AKPMultimedia** [comment]
1. Run LH on 
Google Chrome Lighthouse Extension
#### What is the current behavior?
Sometimes: Does not register a service worker
#### What is the expected behavior?

#### Environment Information
* Affected Channels: 
* Lighthouse version: 3.3.0.4001
* Node.js version: 10.15.0 LTS
* Operating System: W10

**Comment by pairmix** [comment]
I've got the same issue.

**Comment by exterkamp** [comment]
I think this is a duplicate of #6342 the bug behavior seems quite similar and they seem related.
