### ISSUE TITLE
Unstable Mobile Score 

### ISSUE THREAD

**Issue by chadd19** [GoogleChrome/lighthouse#6956]
I have seen in many forums and discussion room where every developer, user, web-owners are having a similar concern as I do.

Why the current version of Google PageSpeed report is not giving an ideal report? (especially in the mobile version). 

I've tested my [inner page](https://www.speedboost.xyz/blog/why-do-you-need-to-eliminate-render-blocking-css-js/)  in many tools (such as GTmetrix, Pingdom, testmysite.thinkwithgoogle.com. and more.

Any one facing similar issues?.

**Comment by patrickhulce** [comment]
Thanks for filing @chadd19! Could you be a little more specific about what you mean by "not giving an ideal report"?

**Comment by chadd19** [comment]
Hi Patrick,

The results - performance grade was not even in every analysis I made. I've studied about the [FCP](https://www.speedboost.xyz/blog/know-about-first-paint-time-contentful-meaningful-and-time-to-interactive/) and how it impacts the User Experience greatly. Still, I can see the huge variation of scores each time I use the current version of [PageSpeed.
](https://developers.google.com/speed/pagespeed/insights/)

I've even shared some of the discussions about the issues being faced by the developers and web analyst. 

![14](https://user-images.githubusercontent.com/46485673/50877621-abffdc80-13f8-11e9-8abc-90dec2ee1586.png)

![groups google com_forum__utm_medium email utm_source footer](https://user-images.githubusercontent.com/46485673/50877625-b15d2700-13f8-11e9-969d-70d2a268b325.png)

![very inconsistent results](https://user-images.githubusercontent.com/46485673/50877635-bc17bc00-13f8-11e9-953b-a0305078f582.PNG)

**Comment by patrickhulce** [comment]
Was the page you linked the page you're talking about fluctuating? https://www.speedboost.xyz/blog/why-do-you-need-to-eliminate-render-blocking-css-js/

I see PSI scores of: 81 84 81 80 82 86 82 85
Is this the type of variation you're specifically talking about?

You might find the discussions in #6907 #6931 and our [LH variability and accuracy analysis doc](https://docs.google.com/document/d/1BqtL-nG53rxWOI5RO0pItSRPowZVnYJ_gBEQCJ5EeUE/edit) interesting.

Public example URLs with high variance are always appreciated.

**Comment by chadd19** [comment]
Since I've done most of the optimizations in maximum web pages of [SpeedBoost](https://www.speedboost.xyz), now the issues seem to be normal currently. 

Also, I'll let you know about some of my related websites which are having similar issues.

Meanwhile thanks to you.

**Comment by brendankenny** [comment]
Looks resolved, so closing for now. If it's not, please comment and we can reopen!
