### ISSUE TITLE
next gen file recommendation needs more insight

### ISSUE THREAD

**Issue by halukkaramete** [GoogleChrome/lighthouse#6964]
**Summary**

In [this page](https://developers.google.com/web/tools/lighthouse/audits/webp), there is a recommendation about using the next-gen formats ( webp, jpeg 2000 or jpeg xr ). When we read about it, we learn that there is a dramatic lack of browser-support for each recommended format. That raises a big question in pretty much everyone's mind as to what to do then? Follow the recommendation and deal with the browser issues or what? If I save my pics in one of these formats, would not I end up making my page to be less compatible?

I think we deserve more insight in this aspect so we know what the best practice really is for this matter.

At this time, I will have to bite the bullet and go with the good-old png/jpg, compress approach which we know rock solid, and accept failing on that audit. :(

**Comment by patrickhulce** [comment]
Thanks for filing @halukkaramete!

The documentation needs to be updated, but the current state of the world is that latest Chrome, Edge, and Firefox all support WebP, so we're doing a bit better on browser support these days.

Additionally, the suggestion is definitely not for you to pick one format and forsake all others! You can use the [`<picture>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) to gracefully support multiple image formats at once. Browsers that support the more efficient encoding will use it automatically and those who don't will fallback to standard JPEG/PNG you provide. I had thought we linked the approriate 

Finally, only the metrics in the performance section affect the score. Everything else (opportunities and diagnostic audits) are there just to help guide you when improving your metrics. If the opportunity savings of converting all the images to WebP is fairly low, then by all means move on to bigger problems! :)

**Comment by benschwarz** [comment]
I'd like to add that image CDN's are a great way of offering better image compression to your customers. Many of these services are able to detect if the client can for example accept a webp image. It'll respond with the most relevant image format. Pretty good hey?

**Comment by halukkaramete** [comment]
Excellent feedback. Thank you Ben.

**Comment by halukkaramete** [comment]
Thanks for the clarification @patrickhulce After your explanations, it totally makes sense. The moment you guys shed the same sort of light on that particular doc, I think it will be so much better. Your last note on "only the metrics in the performance section affect the score" is also GOLD and I feel that needs to be communicated well on the surface level UI. Thank you!

**Comment by exterkamp** [comment]
So I'm hearing that there are two tasks here:
1. Add better docs for WebP & optimize images
2. Add better docs _and_ UX for metrics vs. opportunities vs. diag in perf not effecting score

I'm curious if there are any good ideas on how to expose the performance UX part @hwikyounglee

**Comment by hwikyounglee** [comment]
> So I'm hearing that there are two tasks here:
> 
> 1. Add better docs for WebP & optimize images

A related plug might be:  https://web.dev/fast#topic-Optimize-your-images (feedback to the content can be filed [here](https://github.com/GoogleChrome/web.dev/issues/new/choose), which is much appreciated) 

> 2. Add better docs _and_ UX for metrics vs. opportunities vs. diag in perf not effecting score
> 
> I'm curious if there are any good ideas on how to expose the performance UX part @hwikyounglee

Does it make sense to add a link to [the scoring guide doc](https://developers.google.com/web/tools/lighthouse/v3/scoring) from "Score scale" as a quick fix?
Longer term: we need a clearer link placement e.g. when reading each section, there should be a noticeable UI element, such as a link or a tooltip, to learn about scoring.

**Comment by paulirish** [comment]
Also we shouldnt' recommend JPEG-XR. #6899
