### ISSUE TITLE
Unable to connect to Chrome

### ISSUE THREAD

**Issue by kaihendry** [GoogleChrome/lighthouse#698]
I'm on Archlinux with uptodate packages. Have I got the path wrong?

```
~$ LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/chromium; lighthouse --verbose http://example.com
Launching Chrome...
created /tmp/lighthouse.uwsFWRJ
Chrome running with pid = 5376
Waiting for browser.......................
Unable to connect to Chrome
If you're using lighthouse with --skip-autolaunch, make sure you're running some other Chrome with a debugger.
~$ LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/google-chrome-unstable; lighthouse --verbose http://example.com
Launching Chrome...
created /tmp/lighthouse.DrHDAju
Chrome running with pid = 7547
Waiting for browser.......................
Unable to connect to Chrome
If you're using lighthouse with --skip-autolaunch, make sure you're running some other Chrome with a debugger.
~$ google-chrome-unstable --version
Google Chrome 55.0.2859.0 dev
~$ chromium --version
Chromium 53.0.2785.116
```

**Comment by boopathi** [comment]
Seems like a bug.

Maybe for some reason Chrome is not able to bind remote debugging interface to port 9222. Chrome starts even if it's not able to bind to a port. Can you check the chrome log (if there is some error in binding to the port) from your tmp directory? - these files

+ `/tmp/lighthouse.uwsFWRJ/chrome-out.log` 
+ `/tmp/lighthouse.uwsFWRJ/chrome-err.log`

or 

+ `/tmp/lighthouse.DrHDAju/chrome-out.log` 
+ `/tmp/lighthouse.DrHDAju/chrome-err.log`

or if you run lighthouse again, the tmp directory can be found on the second line from the console like so -

```js
created /tmp/lighthouse.xxxxxxx
```

**Comment by kaihendry** [comment]
```
~$ telnet localhost 9222
Trying ::1...
Connection failed: Connection refused
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
~$ man google-chrome-unstable
~$ LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/google-chrome-unstable; lighthouse --verbose http://example.com
Launching Chrome...
created /tmp/lighthouse.ZFQiy9h
Runtime error encountered: Error: The environment variable LIGHTHOUSE_CHROMIUM_PATH must be set to executable of a build of Chromium version 52.0 or later.
    at Object.linux (/home/hendry/.node_modules/lib/node_modules/lighthouse/lighthouse-cli/chrome-finder.js:62:11)
    at Promise.resolve.then (/home/hendry/.node_modules/lib/node_modules/lighthouse/lighthouse-cli/chrome-launcher.js:91:61)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Error: The environment variable LIGHTHOUSE_CHROMIUM_PATH must be set to executable of a build of Chromium version 52.0 or later.
    at Object.linux (/home/hendry/.node_modules/lib/node_modules/lighthouse/lighthouse-cli/chrome-finder.js:62:11)
    at Promise.resolve.then (/home/hendry/.node_modules/lib/node_modules/lighthouse/lighthouse-cli/chrome-launcher.js:91:61)
    at process._tickCallback (internal/process/next_tick.js:103:7)
~$ google-chrome-unstable --version
Google Chrome 55.0.2859.0 dev
~$ export LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/google-chrome-unstable; lighthouse --verbose http://example.com
Launching Chrome...
created /tmp/lighthouse.CSzkzS5
Chrome running with pid = 5853
Waiting for browser.......................
Unable to connect to Chrome
If you're using lighthouse with --skip-autolaunch, make sure you're running some other Chrome with a debugger.
~$ vim /tmp/lighthouse.CSzkzS5/chrome
chrome-err.log  chrome-out.log  chrome.pid
~$ vim /tmp/lighthouse.CSzkzS5/chrome-err.log
~$ vim /tmp/lighthouse.CSzkzS5/chrome-out.log
~$ cat /tmp/lighthouse.CSzkzS5/chrome-err.log
[5853:5853:0926/110850:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

**Comment by kaihendry** [comment]
This is related to https://github.com/GoogleChrome/lighthouse/issues/378 but I don't understand how to work around the issue. Lunching `chromium --no-sandbox` & then `export LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/chromium; lighthouse --verbose http://ex
ample.com` didn't work.

**Comment by wardpeet** [comment]
try `export LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/chromium; npm run chrome-debug --no-sandbox` open another tab and run`lighthouse --verbose http://ex ample.com`

**Comment by kaihendry** [comment]
http://s.natalian.org/2016-10-06/1475724269_2548x1380.png
Hmm, bit confused.

**Comment by wardpeet** [comment]
Sorry wrong command  'export LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/chromium;  npm run chrome -- --no-sandbox' will test it in 30 min

**Comment by kaihendry** [comment]
Still: http://s.natalian.org/2016-10-06/confused.txt

**Comment by wardpeet** [comment]
How did you install lighthouse?

**Comment by kaihendry** [comment]
`npm install -g GoogleChrome/lighthouse` is how I initially installed it according to my bash history.

I just did a `sudo yarn global add lighthouse` and ran {lighthouse,chrome-debug} from `~/.yarn-cache/.global/node_modules/.bin/` but no dice!

http://s.natalian.org/2016-10-15/lighthouse.txt
Btw my [google-chrome-unstable](https://aur.archlinux.org/packages/google-chrome-dev/) is 55, so I am not sure why it thinks it's not "Chromium version 52.0 or later".

**Comment by wardpeet** [comment]
@kaihendry does this PR #856 fixes your issue?

**Comment by DavidScales** [comment]
I am using Debian in Docker with [this Chromium in Docker tool](https://github.com/mark-adams/docker-chromium-xvfb), but having the same issue. Tried the newest version of lighthouse but no luck. I'm able to run Karma tests but not Lighthouse. Any new ideas?

**Comment by paulirish** [comment]
@DavidScales might want to try @justinribeiro's headless chromium docker image: https://hub.docker.com/r/justinribeiro/chrome-headless/  he's been running lighthouse in it. :)

**Comment by DavidScales** [comment]
@paulirish Thanks Paul! I got in touch with @justinribeiro and he actually has a [Lighthouse Docker image](https://hub.docker.com/r/justinribeiro/lighthouse/) that works perfectly!

**Comment by ebidel** [comment]
Closing stale issues. 

Also check out https://github.com/ebidel/lighthouse-ci/blob/master/builder/Dockerfile.nonheadless for an example Dockerfile that installs Chrome and runs lighthouse.
