### ISSUE TITLE
Ability to test a single audit

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/lighthouse#6981]
**Feature request summary**

This is a request to add the ability to be able to test a single failed audit. With the click of a button, a developer could test whether or not a single audit is failing on a URL and get specific information relating to their URL on that failed audit, without having to see the kitchen sync.

**What is the motivation or use case for changing this?**
This is a request for the web.dev team. We are working on guidance off of the measure section. And we want to eventually make that guidance as personal and interactive as possible.

Developers can go into guidance on fixing a failed audit based on their URL entered on the mesure page-- see specifics on the failed audit, and re-test the audit at any time from the guidance for that audit to confirm if it is still failing.

This more focused view will make it easier for developers to work step-by-step to make their sites better.

**How is this beneficial to Lighthouse?**
We will be able to measure shifts in failing/passing audits, directly tying them to guidance that we've provided.

**Comment by brendankenny** [comment]
In the CLI this is possible today! You can run `lighthouse --only-audits works-offline https://example.com` and it'll limit itself to only that audit.

We don't expose this in DevTools or the extension since the UI is (possibly) a ton of options for something we weren't sure there would be demand for.

Do you have thoughts on how you would want to make that interaction loop nicely usable?

**Comment by Meggin** [comment]
Oh wow. That's the best kind of issue-- one that is already working as needed!

Yes, I do!

Basically in web.dev, we have this measure section: .

At the moment, we are creating a todo list off of failed audits.

And we link to guides that aren't very personal.

The idea would be to personalize the guidance more-- so that when you go into guidance for a failed audit-- we will bring in your actual details about what might be causing the problem.

And as well as that, we could add a re-test button to the guidance for that failed audit-- which would allow developers to confirm if their fix worked.

I believe the ability to see personal problem along with guidance in a per audit view could make it a lot clearer for developers to see what they could change, change it, and confirm their success.

**Comment by paulirish** [comment]
This ends up being a feature request for the PageSpeed API (and lightrider) to add an onlyAudits field.

**Comment by Meggin** [comment]
Is there a better place to submit the feature request?

**Comment by paulirish** [comment]
Not sure if we'll get to this soon.. In the meantime you can rerun with just the category and hide the results from the other audits, or whatever. :)

**Comment by Meggin** [comment]
Yeah, that may actually be the best option, given the dependencies of audits.

**Comment by paulirish** [comment]
K. Then we'd recommend rerunning specific categories and filtering the results on your side.

I'll close this feature request.
