### ISSUE TITLE
DevTools Error: The asynchronous expression exceeded the allotted time of 60

### ISSUE THREAD

**Issue by voronaivan93** [GoogleChrome/lighthouse#6988]
**Initial URL**: https://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&source=mailto&to=orangebook@fda.hhs.gov
**Chrome Version**: 70.0.3538.102
**Error Message**: The asynchronous expression exceeded the allotted time of 60s
**Stack Trace**:
```
Error: The asynchronous expression exceeded the allotted time of 60s
    at _ (chrome-devtools://devtools/remote/serve_file/@4bbeebac88fdc09c97265e47c205868bbd190497/audits2_worker/audits2_worker_module.js:1000:120)
```

**Comment by patrickhulce** [comment]
Thanks for filing! This specific error is no longer possible in latest version of Lighthouse, and I'm no longer able to reproduce. Check out the upcoming 4.0 release in Chrome Canary for the fix.
