### ISSUE TITLE
Meta description missing error

### ISSUE THREAD

**Issue by witamine** [GoogleChrome/lighthouse#7004]
Hi,

I've read precedent issues about meta description errors, and I think there is another one. 

On my homepage I've this meta (in HEAD section) : 
![image](https://user-images.githubusercontent.com/46682478/51126121-a0f6e300-1822-11e9-9b4b-657f907a226b.png)

![image](https://user-images.githubusercontent.com/46682478/51126068-7f95f700-1822-11e9-8953-19b7bdd44db3.png)

I think it's because of the id attribute. But I think it shouldn't be listed in the SEO issues.

**Comment by patrickhulce** [comment]
That's because when visiting your page on mobile you redirect to a page that lacks a `meta[name=description]` if you audit your desktop page it will pass as expected.

(Note if you're using Chrome 71 you might be suffering from #6772, use Canary for now)

**Comment by witamine** [comment]
Oh, I didn't know about this : 

> In Chrome 71 audit used a mobile user agent even if i chose Desktop as device. It works fine with the previous 70 version.

> use Canary for now

Ok I will. Thanks for your help :)
