### ISSUE TITLE
Settings not correct

### ISSUE THREAD

**Issue by tigris22** [GoogleChrome/lighthouse#7009]
#### Provide the steps to reproduce
1. Run LH on <affected url>

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by tigris22** [comment]
Just ran a Lighthouse test in Chrome (using the inspect tool) and I notice my scores were much lower than 7 days ago. I double checked the setting were were set to Desktop > Performance > No Throttling. At the end of the results I see the following:

Fetch time: Jan 14, 2019, 3:45 PM MST
Device: Emulated Nexus 5X
Network throttling: 150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
CPU throttling: 4x slowdown (Simulated)
User agent (host): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
User agent (network): Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36(KHTML, like Gecko) Chrome/71.0.3559.0 Mobile Safari/537.36
CPU/Memory Power: 1374

Whereas 7 days ago I ran the same test and got
Fetch time: Jan 7, 2019, 8:44 PM MST
Device: No emulation
Network throttling: Provided by environment
CPU throttling: Provided by environment
User agent (host): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/70.0.3538.110 Safari/537.36

I see the test is now defaulting to a Nexus mobile device and simulated throttling.

**Comment by patrickhulce** [comment]
Thanks for filing! This is a bug in Chrome 71, see #6772 for details. It's been fixed in Canary if you'd like to use that for the time being.
