### ISSUE TITLE
A11y i18n

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#7010]
#### Provide the steps to reproduce
As of #7008 there are some gaps in a11y translation:
- title, and category description
![image](https://user-images.githubusercontent.com/6392995/51146336-5f0e7280-180b-11e9-9716-c3971a1408c0.png)
- Manual Audits
![image](https://user-images.githubusercontent.com/6392995/51146361-70f01580-180b-11e9-89cb-10464325b855.png)

**Comment by paulirish** [comment]
> As of #7008 there are some gaps in a11y translation:

We could bring back https://github.com/GoogleChrome/lighthouse/pull/5726/files#diff-4bcfedf0736e1cd08b26fe659537ad90 to help avoid this.

**Comment by patrickhulce** [comment]
> We could bring back https://github.com/GoogleChrome/lighthouse/pull/5726/files#diff-4bcfedf0736e1cd08b26fe659537ad90

Huzzah!! Yes please :D

**Comment by brendankenny** [comment]
> We could bring back https://github.com/GoogleChrome/lighthouse/pull/5726/files#diff-4bcfedf0736e1cd08b26fe659537ad90 to help avoid this.

wait, is that to make it easier to spot when we've missed some strings when manually testing? Is it that different than just loading in russian and looking for english?

**Comment by patrickhulce** [comment]
@brendankenny you have to wait for the translations to come back though, that bit was us programmatically generating it so you could notice as you're going.

**Comment by exterkamp** [comment]
Well we can't load new russian until after its translated.  We need the script to load in the en-XA to see that it's bad before we send it to be translated afaik.

**Comment by paulirish** [comment]
I also want to comment in this thread right now.

**Comment by brendankenny** [comment]
> We need the script to load in the en-XA to see that it's bad before we send it to be translated afaik.

Cool. But I do predict the exact same pace of people actually loading another locale to check if we've missed something :P

**Comment by exterkamp** [comment]
Well now I have to leave a comment.
