### ISSUE TITLE
Consistent style for lh-warnings

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#7011]
Mentioned in #6989.  I think the lh-warnings style looks out of place with the report style e.g.
![image](https://user-images.githubusercontent.com/6392995/51146678-608c6a80-180c-11e9-9d2d-386318470f8e.png)

My suggestion is to replace the 1px border with a light orange background (#fff5e3):
![image](https://user-images.githubusercontent.com/6392995/51146759-9d586180-180c-11e9-9206-1bcdc18b37ab.png)

Would love some thoughts. @hwikyounglee

**Comment by paulirish** [comment]
@yuinchien is looking at this.

**Comment by hwikyounglee** [comment]
Su^per late - 

@exterkamp 's suggestion on using the bg color instead of border looks good to me while we're currently looking at a longer term approach in a separate effort.

**Comment by exterkamp** [comment]
I'm gonna give this to @Hoten as part of the report-redesign :smile:
