### ISSUE TITLE
Buggy I cannot trust the report

### ISSUE THREAD

**Issue by ojemuyiwa** [GoogleChrome/lighthouse#7016]
#### Provide the steps to reproduce
1. Run LH on <localhost>

#### What is the current behavior?
I select desktop it emulates nexus 5

Says there no noscript tag. Its the first tag under the body tag

suggests link rel=preload should be used. When I use css doesn't load, false information and not standard in all browsers

Does not redirect http traffic. All traffic is redirected and also have canonical links.

After this I cannot take the tool seriously as most recommendations and grading is false

#### Environment Information
* Affected Channels: angular cli v7.0.6
* Lighthouse version:  3.2.0
* Node.js version: 6.5.0
* Operating System: Mac OS 10.14.2

**Related issues**

**Comment by patrickhulce** [comment]
Do you have a URL for us to test? Also the angular CLI does not directly use Lighthouse AFAICT are you running through devtools?

> I select desktop it emulates nexus 5

If you're using DevTools and not the extension or CLI, this is a bug that's been fixed (#6772). Next Chrome update should resolve this.

> suggests link rel=preload should be used. When I use css doesn't load, false information and not standard in all browsers

You shouldn't be replacing your existing links with `preload` links, it's purely additive. There is no scenario in which properly executed `rel=preload` links will make CSS stop loading in any browser.

> Does not redirect http traffic. All traffic is redirected and also have canonical links.
> Says there no noscript tag. Its the first tag under the body tag

Difficult to help with these without a URL.

> After this I cannot take the tool seriously as most recommendations and grading is false

Is this just referring to the above or are there more "false grading" issues?

**Comment by ojemuyiwa** [comment]
Sadly I'm optimising and running in localhost before release.

I'm using chrome devtools: inpect->audits->run audits

where single-page application and css is generated server side for graph with animations rel=preload does not work, but reduces score of application.

Sadly I became skeptical about the rest of the reds as screen-shot is all I can attach here.

<img width="554" alt="usehttpsonly" src="https://user-images.githubusercontent.com/13540819/51193777-8b94be00-18e1-11e9-8421-0f1fcdb0c684.png">
<img width="586" alt="noscript" src="https://user-images.githubusercontent.com/13540819/51193785-90597200-18e1-11e9-9fc8-11837bc8eed5.png">

Anyways I believe next release may resolve some of these issues along with deploying to staging environment and re-testing.

Thanks so much for taking the time out to respond, I appreciate it.

**Comment by patrickhulce** [comment]
Thanks @ojemuyiwa! Please let us know if these still persist using updated Chrome on a real production/staging server.
