### ISSUE TITLE
Unable to audit anything after login page

### ISSUE THREAD

**Issue by pavle-lekic-htec** [GoogleChrome/lighthouse#7018]
I'm unable to test any page after the login page on my SPA. Even if I unselect "Clear storage" checkbox it is still not able to collect access and refresh tokens from localstorage therefore logging me out from the app and auditing only the login page. Is there a way to go past the login page and audit some other page of the SPA? I'm using JWTs stored in localstorage.

Thanks.

**Comment by patrickhulce** [comment]
Thanks for filing! You're probably suffering from #6772, give Canary a whirl and see if it fixes the issue. Stable should be fixed on the next major version bump.

**Comment by paulirish** [comment]
Fixed in m73 which should be out March 12th.
