### ISSUE TITLE
Extension Error: INSECURE_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by donalturrentine** [GoogleChrome/lighthouse#7023]
**Lighthouse Version**: 3.3.0.4001
**Lighthouse Commit**: 66100367e39d970f8208bd30c10bd97cc7240784
**Chrome Version**: 71.0.3578.98
**Initial URL**: REDACTED
**Error Message**: INSECURE_DOCUMENT_REQUEST
**Stack Trace**:
```
LHError: INSECURE_DOCUMENT_REQUEST
    at Function.assertNoSecurityIssues (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:20163:7)
    at Function.afterPass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:20298:6)
```

**Comment by donalturrentine** [comment]
I'm not sure if this is a real lighthouse issue, I just followed the prompts and it seemed to want to create an issue on GitHub........ There is a real issue though, that my site keeps showing up as Insecure even though there don't seem to be any insecure document requests happening, so if lighthouse is causing this, well, then there you go. Thanks!

**Comment by patrickhulce** [comment]
Thanks for filing @donalturrentine! I'm not able to reproduce this though :/

**Comment by donalturrentine** [comment]
This spontaneously resolved itself. Thank you!
