### ISSUE TITLE
How to get mobile and desktop metrics at the same time differently

### ISSUE THREAD

**Issue by n3pixowe** [GoogleChrome/lighthouse#7035]
**Summary**

I want to use Lighthouse for getting metrics of a website with mobile and desktop at the same request. There is an options for this,

`--emulated-form-factor "mobile", "desktop", "none"`

This option can split mobile from dekstop, but I want to get mobile and desktop metrics seperately at one request, how to do that?

**Comment by patrickhulce** [comment]
You can't; you'll need to make two requests. The mobile and desktop pages have different characteristics, so there's no way around loading the page twice to get two reports.
