### ISSUE TITLE
DBW: helpText should provide browser share for suggested API

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#704]
Using the caniuse API:
http://caniuse.com/jsonp.php?callback=caniusecallback

There's also https://www.npmjs.com/package/caniuse-api, but I suspect we won't be able to pull that into g3.

**Comment by paulirish** [comment]
In [Web Platform Feature Availability](http://paulirish.github.io/web-feature-distribution/) I have the code to get a 0-100% browser share distribution number for each caniuse feature.. however the code is a bit cray, so it may be better to do greenfield. :)

**Comment by ebidel** [comment]
👍 or rip, rinse, and repeat :)

**Comment by paulirish** [comment]
Cool idea, but we don't have a lot of situations where this would provide much value. 

But we'll revisit when appropriate.
