### ISSUE TITLE
Move unused CSS to a computed artifact

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#7042]
**Summary**
We use the unused CSS audit result in a few places. Moving it to a computed artifact would make our usage cleaner.

*Note:* Created from a TODO in code so it can be more visible and properly prioritized

**Comment by mattzeunert** [comment]
Does this basically mean moving `determineContentPreview` into a separate file instead of it being a static method on the audit?

**Comment by patrickhulce** [comment]
No sorry for the vagueness here :) 

It means that the entire logic of the audit and the computation should be moved to a computed artifact so it can be reused by both the render blocking scripts audit *and* the unused CSS audit without require'ing in the audit itself.
