### ISSUE TITLE
Refactor simulator so the states are clearer

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#7048]
**Summary**

In https://github.com/GoogleChrome/lighthouse/pull/6900#discussion_r245142581, @brendankenny suggested refactoring away the last compromise of `_nodes[state]`.

*Note:* Created from a TODO in code so it can be more visible and properly prioritized

**Comment by brendankenny** [comment]
this will be a thing (or it won't) next time someone not-patrick tries to figure out why there is a active but non-functional state, so let's leave it until then :)
