### ISSUE TITLE
Update sample artifacts

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#7055]
It's been a while and we've only done it sporadically as we've added new gatherers. Could do it wholesale or just do a strategic update, not touching things that don't need to be (e.g. network timestamps) or things that depend on matching the paired devtoolsLogs/traces.

**Comment by paulirish** [comment]
+1 for wholesale update.

**Comment by brendankenny** [comment]
A lot of this was done in #8243. We should probably update the traces at some point, but not an emergency (probably some new trace event requirement will eventually force it more naturally)
