### ISSUE TITLE
DBW: define metadata for linking to your docs

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#706]
- [ ] chromestatus entries
- [ ] docs, articles
- [ ] samples
- [ ] caniuse data (https://github.com/GoogleChrome/lighthouse/issues/704)

**Comment by brendankenny** [comment]
if you're going to be thinking about this, it would be nice to add support for this for the core report as well

**Comment by paulirish** [comment]
We added learn more links to docs. Several weeks ago. :P
