### ISSUE TITLE
why the tab which open by lighthouse is high cpu usage

### ISSUE THREAD

**Issue by wuyx0914** [GoogleChrome/lighthouse#7074]
#### Provide the steps to reproduce
1. Custom gatherer
```
import * as bluebird from "bluebird";
class CustomGatherer extends Gatherer {
  async beforePass(passContext) {
    let driver =passContext.driver;
    let ws = await driver.wsEndpoint();
    let browser = await puppeteer.connect({
        headless: false,
        defaultViewport: null,
        browserWSEndpoint: ws,
        ignoreHTTPSErrors: true
      });
     let page = await browser.newPage();
     await bluebird.delay(10000);
  }

  afterPass(passContext) {
    return {};
  }

  pass(passContext) {}
}
```

2. Put CustomGatherer in the first , such as : 
```
config.passes[0].gatherers.unshift({
      instance: new CustomGatherer()
});
```

3. Open task manager of chrome
![image](https://user-images.githubusercontent.com/46918672/51520467-afff1600-1e5e-11e9-8b75-ec59e65d7a70.png)
All tabs are about:blank, but 66647 CPU usage is 81%!!!

4. In 10s, close second tab manually will throw error
```
Error: not opened
    at WebSocket.send (${projectDir}/node_modules/ws/lib/WebSocket.js:344:18)
    at CriConnection.sendRawMessage (${projectDir}/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:172:14)
    at CriConnection.sendCommand (${projectDir}/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:65:10)
    at Driver._innerSendCommand (${projectDir}/node_modules/lighthouse/lighthouse-core/gather/driver.js:315:29)
    at Promise (${projectDir}/node_modules/lighthouse/lighthouse-core/gather/driver.js:289:35)
    at new Promise (<anonymous>)
    at Driver.sendCommand (${projectDir}/node_modules/lighthouse/lighthouse-core/gather/driver.js:282:12)
    at Driver.cleanBrowserCaches (${projectDir}/node_modules/lighthouse/lighthouse-core/gather/driver.js:1219:17)
    at Function.pass (${projectDir}/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:252:33)
    at Function.run (${projectDir}/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:469:28)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

Error: connect ECONNREFUSED 127.0.0.1:51773
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1121:14)
```

Lighthouse Version: 4.0.0-beta
Chrome Version: 72.0.3617.0

**Comment by patrickhulce** [comment]
I'm not 100% sure what you're trying to accomplish by opening a different tab with puppeteer (seems like you'd want to connect to the same page Lighthouse is auditing, not a new one or what's the point of integrating with LH, ya know? 😃), but in general, backgrounding the tab Lighthouse is actively trying to audit will cause problems.

Maybe there's another way around this we can find if you're willing to share your use case?

**Comment by wuyx0914** [comment]
> I'm not 100% sure what you're trying to accomplish by opening a different tab with puppeteer (seems like you'd want to connect to the same page Lighthouse is auditing, not a new one or what's the point of integrating with LH, ya know? 😃), but in general, backgrounding the tab Lighthouse is actively trying to audit will cause problems.
> 
> Maybe there's another way around this we can find if you're willing to share your use case?

Thank you for your answer.First tab is open default  by puppeteer.. Second tab is open by LH.
In third tab, I want to do something before LH, such as login and pre load resources. The tab will close after then.

Case workflow:
1. login and wait for page load completed. (third tab)
2. forward to {my_site} , LH start gatherer metrics and  audit(second tab)
3. monitor tab's memory and cpu usage.

problem:
Visit {my_site} by chrome directly, the cpu usage 20-30%, but use LH, in gatherer stage, the cpu usage 100-120%.How I avoid it?

**Comment by wuyx0914** [comment]
> Ah, OK! Does it work as expected if you login to your page with puppeteer _before_ doing anything with Lighthouse? You can handoff the same debugger port you launched with puppeteer.

There is no problem with lighthouse/puppeteer integration. And I can authentication before lighthouse.
What puzzles me is why cause higher cpu usage during lighthouse gatherer stage.

**Comment by patrickhulce** [comment]
> What puzzles me is why use lighthouse will cause higher cpu usage .

I'm not sure either. Unless you're observing it during our benchmark (which spikes CPU to 100% temporarily to gauge CPU power), while gathering we are just waiting on the results of the gatherer and not trying to evaluate anything in the page.

**Comment by wuyx0914** [comment]
> I'm not sure either. Unless you're observing it during our benchmark (which spikes CPU to 100% temporarily to gauge CPU power), while gathering we are just waiting on the results of the gatherer and not trying to evaluate anything in the page.

Thanks you anyway.

**Comment by wuyx0914** [comment]
The reason :
```
config {
     throttlingMethod: 'devtools',
     passes: [{
         useThrottling: true
     }]
}
```

Solution
set `throttlingMethod: 'simulate'` or `useThrottling: false`

**Comment by patrickhulce** [comment]
Strange. Thanks for letting us know!
