### ISSUE TITLE
lighthouse Https problem

### ISSUE THREAD

**Issue by likka7** [GoogleChrome/lighthouse#7076]
Hello to everyone!

Lighthouse version: 4.0.0
Google Chrome version: 71
Node.js version: 8.9.0

I'm running lighthouse in CMD. I did "npm install lighthouse" and then "lighthouse "url"". When I run lighthouse on http sites, everything is ok, but as soon as I try to run it on https lighthouse starts running and then I'm getting this:

```
events.js:183
           throw er; // Unhandled 'error' event

Error: read ECONNRESET
      at _errnoException <util.js:1024:11>
      at TCP.onread <net.js:615:25>
```

I installed ionic and ws as well, but nothing helped.
I'll be happy, if someone can help with it. 
thanks in advance.

**Comment by patrickhulce** [comment]
Hmmm, that looks like it's coming from within node, so that's more likely LH's connection to the browser being reset, not the connection to the page. Is there anything more you can tell us about your repro steps?

Is it really...

1. `npm install -g lighthouse`
2. `lighthouse https://example.com`
3. All sites that start with `https` throw this error now.

Does it only happen on a specific URL?

**Comment by likka7** [comment]
hello @patrickhulce.

  I forgot to remain one important fact. I'm working on close service. It means that I have no internet connection to different sites, such as Google, Github, etc. When I use lighthouse from Google Chrome (I mean from icon near URL bar) everything works fine. 
  To your question if it happens on a specific URL - no it happens with every URL that starts with https.
I rechecked all node modules that are required in lighthouse package.json and everything is up to date.
Is there some more information that I can provide?

thanks for your attention.

**Comment by patrickhulce** [comment]
I'm a little confused, you're mentioning your package.json, but you say you're running Lighthouse from "the icon near URL bar". 

Are you using the Lighthouse Chrome Extension?

**Comment by likka7** [comment]
@patrickhulce I need to use them both. As node module and as Chrome Extension. Is this a problem?

**Comment by patrickhulce** [comment]
No it's not a problem it just makes it difficult to understand what specific problem you're facing :)

So let me get this straight...

- When you audit `https://example.com` **from the Chrome Extension** it works fine.
- When you audit `http://example.com` **from the node module** it works fine.
- When you audit `https://example.com` **from the node module** you receive the error `Error: read ECONNRESET` **every time**.

Is that correct? 

Could you also answer the following?
- When you audit `http://example.com` **from the CLI** (i.e. `lighthouse http://example.com`), what happens?
- When you audit `https://example.com` **from the CLI** (i.e. `lighthouse https://example.com`), what happens?

**Comment by emazzotta** [comment]
I'm having a very similar problem for my [lighthouse-badges](https://github.com/emazzotta/lighthouse-badges) project.
It occurred for the first time once I upgraded to lighthouse version `4.0.0`.

Basically I test via TravisCI that `lighthouse-badges` produces an `.svg`-image and an `html`-report based on the `lighthouse` CLI output.

TravisCI runs this command:
`/home/travis/build/emazzotta/lighthouse-badges/node_modules/.bin/lighthouse --chrome-flags='--headless --no-sandbox --no-default-browser-check --no-first-run --disable-default-apps' --output=json --output-path=stdout --quiet http://127.0.0.1:8080`

and fails with this error:
```
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:399:9)
    at Socket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

http://127.0.0.1:8080 is a node server which I start ad-hoc before running the test. 
Previously I was running the test on https://google.com but I changed to aforementioned local server hoping it would fix the issue, however both fail. 

This is actually the commit which broke the build: https://github.com/emazzotta/lighthouse-badges/commit/1d1a7a9148459807142597e55c72192b4deff2dd
As you can see, I just upgraded from `4.0.0-alpha.2-3.2.1` to `4.0.0`

Any hints are greatly appreciated. 👍

**Comment by emazzotta** [comment]
> Interestingly, the run inside docker on Travis seems to work fine too.

Yes, it does indeed. Sorry, forgot to mention that.

Okay, I did a run without the `--quiet`-flag, here's the output:
```
ue, 29 Jan 2019 15:35:29 GMT ChromeLauncher Waiting for browser.
Tue, 29 Jan 2019 15:35:29 GMT ChromeLauncher Waiting for browser...
Tue, 29 Jan 2019 15:35:30 GMT ChromeLauncher Waiting for browser.....
Tue, 29 Jan 2019 15:35:30 GMT ChromeLauncher Waiting for browser.......
Tue, 29 Jan 2019 15:35:30 GMT ChromeLauncher Waiting for browser.......✓
Tue, 29 Jan 2019 15:35:30 GMT status Connecting to browser
Tue, 29 Jan 2019 15:35:31 GMT status Resetting state with about:blank
Tue, 29 Jan 2019 15:35:31 GMT method <= browser ERR:error Page.setLifecycleEventsEnabled 
Tue, 29 Jan 2019 15:35:31 GMT status Disconnecting from browser...
Tue, 29 Jan 2019 15:35:31 GMT ChromeLauncher Killing Chrome instance 5140
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:399:9)
    at Socket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

Full log: https://travis-ci.org/emazzotta/lighthouse-badges/builds/485962461

**Comment by patrickhulce** [comment]
Are you sure you're running with latest Chrome @emazzotta? That looks like Chrome is dying because it can't handle a newer protocol method we use.

We only officially support running with latest stable Chrome.

**Comment by emazzotta** [comment]
Huh, well that was almost too easy 😎 

Adding this to my `.travis.yml` fixed it:
```
addons:
  chrome: stable
```

I didn't know something changed with the protocol method. Thanks @patrickhulce! 🎉

**Comment by brendankenny** [comment]
Seems like everything is good now :)
