### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by punyasc** [GoogleChrome/lighthouse#7082]
**Lighthouse Version**: 4.0.0
**Lighthouse Commit**: bfa10f1ac4ba8cdf95c809858d8bc4c8ac1c1da8
**Chrome Version**: 71.0.3578.98
**Initial URL**: https://punyachatterjee.com/
**Error Message**: PROTOCOL_TIMEOUT
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT
    at setTimeout (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:19252:11)
```

**Comment by patrickhulce** [comment]
duplicate #6512
