### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by rizkysaskiaputra** [GoogleChrome/lighthouse#7087]
**Lighthouse Version**: 4.0.0
**Lighthouse Commit**: bfa10f1ac4ba8cdf95c809858d8bc4c8ac1c1da8
**Chrome Version**: 73.0.3679.0
**Initial URL**: https://rizkysaskiaputra.blogspot.com/
**Error Message**: PROTOCOL_TIMEOUT
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT
    at chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:19252:11
```

**Comment by patrickhulce** [comment]
duplicate #6512
