### ISSUE TITLE
Are the axe-core more info links correct?

### ISSUE THREAD

**Issue by dylanb** [GoogleChrome/lighthouse#7088]
It looks like lighthouse is using version 3.x of axe-core but the links in the issue descriptions point to pages on http://dequeuniversity.com that reference version 2.2.

It should be possible to get these links dynamically from the axe-core library. What is the cause of this and can we help out in any way to fix this so that users are getting to the correct information pages?

**Comment by patrickhulce** [comment]
Thanks @dylanb! We updated axe and the links to 3.1 9 days ago. In Lighthouse 4.0.0, they should be accurate and pointing to the 3.1 docs.

**Comment by dylanb** [comment]
That is great news. When is that release?

**Comment by dylanb** [comment]
Excellent - thanks. I was not aware of the lag in the devtools which is where I was testing it. Where can we track the Chrome devtools release?

**Comment by patrickhulce** [comment]
https://www.chromestatus.com/features/schedule
https://www.chromium.org/developers/calendar

It will likely go out with Chrome 74, so ~Apr 23.
