### ISSUE TITLE
Embed a report in a page

### ISSUE THREAD

**Issue by StefanoChiodino** [GoogleChrome/lighthouse#7097]
Hello, I'd like to embed the report in a page, so that the user can run another one without navigating.

At the moment I'm trying to add the html output as html in an iframe but it's a bit of a responsive nightmare.

Is there any other way that I'm missing? Like a function that renders the html for the JSON report in a div or something like that.

**Comment by StefanoChiodino** [comment]
I've found since that I may be able to use the report rendered by passing the container.

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/report/html/renderer/report-renderer.js#L47

May be nice to document how to do this

**Comment by patrickhulce** [comment]
If you wanted to writeup a how-to guide on this, we'd gladly accept the contribution. Several of the platforms I'm aware of using Lighthouse make use the report-renderer code, so yes you're on the right track.

**Comment by paulirish** [comment]
Very happy for someone to write a short doc on this!
