### ISSUE TITLE
DBW: support source maps for JS audits

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#710]
this would help for all LH audits in the future, but specifically for audits like #707, it would be great to support source maps so we can do the translation back to original source locations for the user.

**Comment by ebidel** [comment]
👍

**Comment by paulirish** [comment]
Seems cool. [sourcemapped-stacktrace](https://github.com/novocaine/sourcemapped-stacktrace) has the basic pattern in there, at least for error stacks.

**Comment by paulirish** [comment]
Lack of user demand.
