### ISSUE TITLE
Is PSI documented anywhere?

### ISSUE THREAD

**Issue by vifird** [GoogleChrome/lighthouse#7106]
**Is PSI documented anywhere?**
I only found the [SI](https://developers.google.com/web/tools/lighthouse/audits/speed-index) document, and the reports of lighthouse(plugin of Chrome) have no *PSI* data.

**Comment by patrickhulce** [comment]
Are you referring to *Perceptual Speed Index* as PSI? If so, that was removed in Lighthouse v3 in favor of plain old *Speed Index*. You can find more rationale on that [in this PR](https://github.com/GoogleChrome/lighthouse/pull/4980#issue-182279707).

If you're referring to *PageSpeed Insights*, there's more linked documentation on the [PageSpeed main page](https://developers.google.com/speed/pagespeed/insights/).

**Comment by vifird** [comment]
Thanks a lot, it means Perceptual Speed Index, got it.
