### ISSUE TITLE
Lighthouse error in Chrome 72

### ISSUE THREAD

**Issue by Phoenixy** [GoogleChrome/lighthouse#7112]
#### Provide the steps to reproduce
1. Run LH on ANY URL, but I was testing https://hearthstonehungary.hu/
then https://developers.google.com/web/updates/2018/05/lighthouse3

#### What is the current behavior?
Performance and PWA shows error on every website in Chrome 72. It worked fine in Chrome 71 (Lighthouse version 3.2.0). Also mysteriously the Lighthouse version in Chrome 72 is 3.0.0-beta.0 (though it's probably just a typo and it's 4.0.0-beta0 in reality, but I'm not entirely sure).
![lighthouse-bug](https://user-images.githubusercontent.com/801036/51944522-89bc1600-241c-11e9-99f6-5fabc0245880.png)
#### What is the expected behavior?
Performance and PWA should work as intended.

#### Environment Information
* Affected Channels: Chrome 72 (Stable - 72.0.3626.81) DevTools > Audits
* Lighthouse version: 3.0.0-beta.0
* Node.js version:
* Operating System: Windows 10

**Related issues**

**Comment by Hoten** [comment]
the great @paulirish fixed it recently. Restarting Chrome should fix it! let us know if it doesn't.

**Comment by Phoenixy** [comment]
It is indeed fixed now. Lighthouse version is back to 3.2 again.
