### ISSUE TITLE
evaluate new axe audits for inclusion

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#7127]
When updating axe in #7020, I noticed there were some axe audits that are running but don't have audits to show them in the report. We should look at them and see if we should be showing them in the report or if we should disable them to save gathering time. We should also see if there are any other tests we should add from the more comprehensive axe of today.

**The current list of running tests with no LH audits:**

1. `aria-dpub-role-fallback`: Ensures unsupported DPUB roles are only used on elements with implicit fallback roles.
2. `aria-hidden-body`: Ensures aria-hidden='true' is not present on the document body.
3. `duplicate-id-active`: Ensures every id attribute value of active elements is unique.
4. `duplicate-id-aria`: Ensures every id attribute value used in ARIA and in labels is unique.
5. `html-xml-lang-mismatch`: Ensure that HTML elements with both valid lang and xml:lang attributes agree on the base language of the page.
1. [`aria-hidden-focus`](https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus): ensures aria-hidden elements do not contain focusable elements.
1. [`form-field-multiple-labels`](https://dequeuniversity.com/rules/axe/3.2/form-field-multiple-labels): Ensures form field does not have multiple label elements.
1. [aria-input-field-name](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/aria-input-field-name.json) Ensures every ARIA input field has an accessible name
1. [aria-toggle-field-name](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/aria-toggle-field-name.json) Ensures every ARIA toggle field has an accessible name

On the other side of things, we don't appear to have any audits that don't have results somewhere in the axe results, so that's good :)

----

Updated April 17: merged in shane's descriptions. Paul added 6,7 from #8370. Patrick added 8, 9 from #9343

**Comment by exterkamp** [comment]
A little more color to these since I was kinda lost:

1. `aria-dpub-role-fallback`: Ensures unsupported DPUB roles are only used on elements with implicit fallback roles.
2. `aria-hidden-body`: Ensures aria-hidden='true' is not present on the document body.
3. `duplicate-id-active`: Ensures every id attribute value of active elements is unique.
4. `duplicate-id-aria`: Ensures every id attribute value used in ARIA and in labels is unique.
5. `html-xml-lang-mismatch`: Ensure that HTML elements with both valid lang and xml:lang attributes agree on the base language of the page.

I feel like 2-5 are all quick hit and good audits that would be valid if we're running them anyway, but 3 &4 might be expensive under the hood or on large DOM sites.  I don't really get the first one without looking into it more.

**Comment by robdodson** [comment]
I agree with @exterkamp's assessment. Does Lighthouse have a way of doing perf A/B tests to see how expensive some of those checks could be?

**Comment by patrickhulce** [comment]
@robdodson we do, but the variance in LH perf and runtime is so massive that it rarely yields anything conclusive at the moment.

it can certainly check if there's something *very* wrong with enabling them though :) 

just comment "DZL, do a barrel roll!" on a PR and it'll run it automatically when there are changes

**Comment by robdodson** [comment]
> DZL, do a barrel roll!

that's amazing.

**Comment by brendankenny** [comment]
bumping to p1 for post I/O :)

**Comment by brendankenny** [comment]
In  #9120, @a11ySherpa asked to include
- [`heading-order`](https://dequeuniversity.com/rules/axe/3.2/heading-order): Heading levels should only increase by one

though it's a `best-practice` not one of the `wcag*` rules.

If the axe implementation isn't too heavyweight, it could be included and serve double duty as the gatherer for the hierarchy idea in #7208 (however, I don't know if axe checks that a header exists at all, the original suggestion in that issue).

**Comment by Hoten** [comment]
>  I don't know if axe checks that a header exists at all, the original suggestion in that issue

[it doesn't](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/navigation/heading-order-after.js)

**Comment by robdodson** [comment]
Suggested categorization:

---

**Navigation**
- duplicate-id-active
- heading-order

**Names and labels**
- form-field-multiple-labels

**ARIA**
- duplicate-id-aria
- aria-hidden-focus
- aria-hidden-body
- aria-dpub-role-fallback

**Internationalization and localization**
- html-xml-lang-mismatch

**Comment by paulirish** [comment]
@robdodson we've updated this issue. we have a few new audits coming from axe that we could include. We'd love your call on which of them we should include, and what weighting.

Perhaps you could take a look at this by late next week?

**Comment by robdodson** [comment]
@paulirish I've tried to organize all of the audits in the comment above. I removed the dpub one because I'm not sure how often that really comes up. Is there anything else you need on my end?

**Comment by kaycebasques** [comment]
@robdodson & @paulirish:

* Did you decide on the weighting for these audits?
* Are they all being surfaced in the report?

**Comment by brendankenny** [comment]
> * Are they all being surfaced in the report?

yes

> * Did you decide on the weighting for these audits?

@robdodson moved us to a system based on the axe minor/serious/critical impact ratings, which are given a weight of 1/3/10, respectively.

**Comment by mfriesenhahn** [comment]
I'm starting the docs for these audits. Is there a branch I can use to take screenshots, get the correct failure titles, etc.? (A quick search didn't turn anything up.)

**Comment by patrickhulce** [comment]
@mfriesenhahn I actually don't think they've been implemented yet as most of them are disabled in the gatherer.

https://github.com/GoogleChrome/lighthouse/blob/61f3ee448c9c38f69d4af24439217d8affad63b5/lighthouse-core/gather/gatherers/accessibility.js#L44-L51

**Comment by mfriesenhahn** [comment]
Thanks, @patrickhulce. Just checking: are they still planned to land for CDS? If so, I can write the docs based on the relevant axe pages and add screenshots and fix up anything else once the audits are done.

**Comment by brendankenny** [comment]
was just putting together #9798 :)
