### ISSUE TITLE
Yeoman generator for new audits

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#713]
Per a convo with @brendankenny, I'm getting tired of creating the same 3-4 files with name changes. A generator could really help!

Opening this bug for tracking.

**Comment by samccone** [comment]
We could also figure out a change that would require less scaffolding to create a new audit.

**Comment by paulirish** [comment]
I think there's some infra work we could do first. For example, in audits we handle -1 and undefined in the artifacts, but we could move that into the `runner.js` fairly easily. 

But perhaps after that. I can see the convenience of using a generator. Though there's only dozens of us audit authors (so far)..

**Comment by paulirish** [comment]
@ebidel still want this? 
I still don't, so I'd prefer to close the issue. :) But your call!

**Comment by ebidel** [comment]
lol naw. What about good first bug though?

**Comment by paulirish** [comment]
nah lets close and reopen if new contributors feel it'd help.
