### ISSUE TITLE
background_color and theme_color fail for most named colours

### ISSUE THREAD

**Issue by bennypowers** [GoogleChrome/lighthouse#7139]
#### Provide the steps to reproduce
1. Run LH on manifest with `"background_color": "rebeccapurple"`

#### What is the current behavior?
test fails:

<img width="877" alt="screenshot 2019-02-02 22 01 08" src="https://user-images.githubusercontent.com/1466420/52168869-3a395b00-2738-11e9-9719-71f132de35e6.png">
<img width="320" alt="screenshot 2019-02-02 22 00 57" src="https://user-images.githubusercontent.com/1466420/52168870-3a395b00-2738-11e9-80f6-81eb0e60af24.png">

#### What is the expected behavior?
Test passes

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**
This fails because a dependency of lighthouse has an incomplete enum of css color names. Relevant PR:
https://github.com/jsakas/CSSStyleDeclaration/pull/74

**Comment by patrickhulce** [comment]
Thanks @bennypowers and for working on that PR! If you could let us know when that gets through we will happily update :)

**Comment by exterkamp** [comment]
I was too aggressive on that `waiting-on-upstream`, it is merged, but still waiting on release afaict.

**Comment by bennypowers** [comment]
1.2.0 is out now

https://github.com/jsakas/CSSStyleDeclaration/pull/74#issuecomment-464279459
