### ISSUE TITLE
JavaScript Useragent doesn't include "Lighthouse" reference on PSI tool

### ISSUE THREAD

**Issue by peixotorms** [GoogleChrome/lighthouse#7140]
I'm not 100% sure if this bug is specific to PSI, or something that comes from the developers tools emulation it uses, but here's the situation:

#### Provide the steps to reproduce
`https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpeixotorms.github.io%2Ftests%2FPSI%2Fjs.html&tab=desktop`

Check the screenshot on the `Desktop tab` for the useragent that is detected with javascript.
PHP will correctly detect the intended useragent.

Compare with `https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://peixotorms.github.io/tests/PSI/js.html`

#### What is the current behavior?
When we use the PSI tool via https://developers.google.com/speed/pagespeed/insights/ to test a website... PHP will detect the correct useragent, which includes a reference to Lighthouse.

However, if we use javascript to detect the useragent, it reports the networkUserAgent instead of the same useragent that PHP detects. 

#### What is the expected behavior?
The useragent that is detected by javascript, should match the one that PHP detects.
Could be a javascript engine bug on chrome, or something is not set right on the PSI tool.

#### Environment Information
https://developers.google.com/speed/pagespeed/insights/

**Comment by patrickhulce** [comment]
Thanks for filing @peixotorms! 

So the tl;dr is that the user agent sent over the network does not match the user agent from javascript, correct?

Sounds like we'd want to match the user agent that LR is sending in LH-core @exterkamp can you think of any easy ways to sync that up?

**Comment by peixotorms** [comment]
Indeed, but synchronizing them also has to make sure that we have an unique useragent identifier appended to the emulated device. 

It's fine to emulate iphone, nexus or mac devices, however, the useragent should include 
"Chrome-Lighthouse" or "Page Speed" or "Headless" identifier in the useragent.

Example, in previous versions, the PSI tool used to include the "Google Page Speed Insights" string in its User-Agent HTTP header. Later it has changed to "Chrome-Lighthouse" but still, there was an unique identifier.

So, it's important not only to match the useragent on both the HTTP request that is read by PHP, but also ensure that it stays consistent on JavaScript, both on mobile and desktop versions (there is a difference).

Furthermore, adding the appropriate identifier to the useragent is also important.

Thanks @patrickhulce

**Comment by exterkamp** [comment]
Hi! Thanks @peixotorms for bringing this up! 

So this is a known issue with our user agent-ing on the PSI side.  PSI still includes a "Chrome-Lighthouse" string in it's ua, but when accessed from inside the page's js only the Lighthouse networkUserAgent can be seen (with no "Chrome-Lighthouse") because it is [reset](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/emulation.js#L79) by Lighthouse iirc.  

We have some possible ideas for syncing them up, but I'm curious what kind of issue this would be causing on your end.  Thanks!

**Comment by peixotorms** [comment]
Hi! Thanks @exterkamp 

It's about "consistency" as well as to cover for specific cases where we are dealing with html static pages or doing something with javascript that requires the useragent.

For example, a static site may include a stats module that collects parts of the useragent using javascript and use it somewhere on the code to add, change or remove elements.

I may want to display only certain images to certain browsers or certain platforms by relying on the javascript useragent, but I don't think those conditional images which are supposed to load only for MAC users, should be considered by PSI on it's score calculation.

Likewise, I may want to test excluding or including portions of html / js / css code on the page and evaluate the impact on the PSI page.  

I can also imagine some developer calling the api every minute to check the score during development, later go on holiday for 2 weeks and forget about it, only to realize later that his stats (collected by JS) are all messed up, because there is a surge in MAC users but nobody bough any MAC related product. 
If his stats showed the correct Lighthouse useragent, he would know something was wrong and probably remember what he forgot.

As a programmer, I have to deal with sometimes ridiculously coded software that does things in a roundabound way. I happened to see some situations as the above... so at least, if possible, synchronizing the useragent for consistency would be ideal.

Security checks can also be done, for example if we match the useragent we received via http with the one on javascript. Some bots do not read javascript and some others fake the http header but use another useragent for javascript navigation.
I would probably block a bot like this under certain situations... but since we don't have the PSI ip addresses to whitelist and I don't want to automatically block the PSI tool, this is out of question.

We would expect the useragent from any good bot (or user) to remain consistent, either using HTTP headers or JavaScript.

Thanks

**Comment by joeyvandijk** [comment]
@exterkamp I am having the issue that I cannot detect if the Pagespeed Insights bot needs to be shown a cookiewall or not. This is done client-side, but I cannot detect if it is an bot or not.

So I think this is the same issue @peixotorms has but a different use-case. Am I correct that the userAgent is changed again with now a `HeadlessChrome` string in it?

**Comment by paulirish** [comment]
Let's put ' Chrome-Lighthouse' in all JS and network UAs.

**Comment by joeyvandijk** [comment]
@paulirish I see that #7297 is merged into master and a new release has the `Chrome-Lighthouse` useragent 👍, but when can we expect that it is deployed to [Pagespeed Insights](https://developers.google.com/speed/pagespeed/insights/)? Is that connected to the Github repository or needs a manual ✅approval? 

I ask this because I am whitelisting Chrome-Lighthouse useragent, but still see a cookiewall being popped up and want to know what to expect with a release on this repository. 😉

**Comment by exterkamp** [comment]
This has now been released!  All users agents in PSI should have `Chrome-Lighthouse` in them.  Feel free to re-open if this isn't the case, but this should be g2g.
