### ISSUE TITLE
Avoid enormous network payloads / Defer unused CSS doesn't consider compression

### ISSUE THREAD

**Issue by peixotorms** [GoogleChrome/lighthouse#7141]
#### Provide the steps to reproduce
Test any website with a large CSS/JS file on https://developers.google.com/speed/pagespeed/insights/

Example:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpeixotorms.github.io%2Ftests%2FPSI%2Fdemo%2Fcompression.html

#### What is the current behavior?
big.min.css weights roughly 1.5 MB uncompressed, but gzip compressed is only about 208 KB.
If there are other resources in the HTML page, PSI will trigger multiple warnings, such as Avoid enormous network payloads, Defer unused CSS, etc.
In this example, PSI triggers the `Eliminate render-blocking resources` and `Defer unused CSS`, which is normal... however, the Size (KB) | Potential Savings (ms) reported, is for the uncompressed values, rather than the gzip values: `http://prntscr.com/mfwg6i`

The score drops drastically if we were to download 1.5MB CSS uncompressed, but not that much if the file is only 208 KB compressed.
Nevertheless, PSI passes the compression test, but it stopped using compressed sizes in its calculations.

#### What is the expected behavior?
As with just a few days before, PSI should be downloading compressed assets and consider that gzip/brotli size in the calculations.

#### Environment Information
https://developers.google.com/speed/pagespeed/insights/

**Comment by patrickhulce** [comment]
Thanks for filing @peixotorms! 

Seems like our workaround for missing transferSize information has stopped working at some point. Any ideas on this one @exterkamp? This could certainly explain the increased metric values you were seeing if all the compressed sizes suddenly got inflated to uncompressed sizes.

possible duplicate #7138

**Comment by milansimek** [comment]
I experience the same issue and it seems that it only happens when using the online Google PageSpeed tool.

When using the latest lighthouse cli or lighthouse chrome extension, the compressed values are used correctly.

**Comment by ScottTravisHartley** [comment]
I can also confirm the issue is tied to the online Page Speed Insights tool, not the LightHouse audit built into chrome.

**Comment by peixotorms** [comment]
Indeed, this has been fixed:
https://docs.google.com/document/d/16tc7V4pwLPhC0ChWRCwKvWl-OQ5P1wxtqIkeZhQM78c/edit#heading=h.czbhz4i1b200
