### ISSUE TITLE
PROTOCOL_TIMEOUT (Method: Page.getAppManifest)

### ISSUE THREAD

**Issue by curtchan** [GoogleChrome/lighthouse#7147]
#### Provide the steps to reproduce
1. Run LH on `https://seo4.net` or `https://krakowskakancelaria.pl/`

#### What is the current behavior?
Error: Lighthouse returned error: PROTOCOL_TIMEOUT. Waiting for DevTools protocol response has exceeded the allotted time. (Method: Page.getAppManifest) (PROTOCOL_TIMEOUT)

#### What is the expected behavior?
No errors.

#### Environment Information
* Affected Channels: Pagespeed API returns 500, web.dev and pagespeedinsights return issue.
* Lighthouse version: ?
* Node.js version: ?
* Operating System: ?

#### Extra info
Issues started to occur since thursday, no action were performed on website, we tried modifying appmanifest but it doesn't seem to be the issue as it is valid and working.
~100 other websites we are tracking regularly do have manifest and they work fine.

**Comment by patrickhulce** [comment]
Thanks for filing @curtchan! I'm able to reproduce this as described on web.dev/PSI and not the CLI 👍

**Comment by curtchan** [comment]
@patrickhulce sorry, by CLI i meant pagespeed's api endpoint - `/pagespeedonline/v5`, just tested it manually, same result.

**Comment by anoblet** [comment]
Experiencing this issue on: https://my-project-75792.firebaseapp.com/

**Comment by gustawdaniel** [comment]
I experienced it 

> https://developers.google.com/speed/pagespeed/insights/?hl=pl&url=https%3A%2F%2Ficsd.shop%2F

This ia s page that uses:
- vue on aws as frontend
- dockerized meteor on vps as backend

Sthe o role of websockets is important.

**Comment by Hoten** [comment]
PSI runs LH on infrastructure that does not yet support certain types of requests:

1. Service workers
2. App manifests
3. Websockets

I know for certain that the first type has never worked.

I assumed the second didn't either, @curtchan are you certain that v5 of PSI at one point didn't return `(Method: Page.getAppManifest) (PROTOCOL_TIMEOUT)`? I think the request never would have worked, so perhaps something changed LH-side in 4.1 (which we updated PSI to last Wednesday). @patrickhulce I see that `driver.getAppManifest` was changed/edited 20 days ago. So that jells.

AFAIU the third is a huge task and there are no plans currently to implement.

**Comment by patrickhulce** [comment]
Yeah @Hoten we now always try to fetch the manifest, not just in the gatherer! 

I didn't realize calling `getAppManifest` is always guaranteed to hang the run in LR 😱

**Comment by Hoten** [comment]
Luckily it seems if the page does not have a manifest, Chrome will return from the `Page.getAppManifest` protocol call with no data. Otherwise Chrome demands a request that we can't resolve, and it just hangs :(

This is probably serious enough to consider a quick fix + PSI push. Let's discuss in chat.

**Comment by Hoten** [comment]
Determined that https://github.com/GoogleChrome/lighthouse/issues/7147#issuecomment-461069829 is a bit wrong. App manifest files are served just fine in our infra. The problem sites all have websockets - currently their mere existence on a page causes PSI to hang. That certainly is not ideal, and while we may not be able to fully support them yet, we should prioritize preventing a hang.

**Comment by Hoten** [comment]
Dug in a bit more. A page can actually use WebSockets (although a connection will always fail). The issue looks to be the long polling. I made a minimal repro here: http://uninterested-badge.surge.sh/index4.html

Without the manifest file, PSI runs fine (no protocol timeout). With the manifest file, it times out.

**Comment by curtchan** [comment]
@Hoten tested again via api explorer for v5:
https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https%3A%2F%2Fseo4.net&strategy=mobile

`{
error: {
errors: [
{
message: "Lighthouse returned error: PROTOCOL_TIMEOUT. Waiting for DevTools protocol response has exceeded the allotted time. (Method: Page.getAppManifest) (PROTOCOL_TIMEOUT)"
}
],
code: 500,
message: "Lighthouse returned error: PROTOCOL_TIMEOUT. Waiting for DevTools protocol response has exceeded the allotted time. (Method: Page.getAppManifest) (PROTOCOL_TIMEOUT)"
}
}`

It clearly returns server 500 error.

**Comment by paulirish** [comment]
Can also reproduce on https://www.toyota.com/camry/ and https://www.toyota.com/ (both of which have a websocket)

**Comment by paulirish** [comment]
@hoten Let's fix in LH and push to LR prod.... on Friday? :) Or.. Thursday!

**Comment by brendankenny** [comment]
>[paulirish](/paulirish) closed this

New issue to track the failure without the timeout?

**Comment by paulirish** [comment]
Deployed to PageSpeed Insights production. Toyota now works (usually)

**Comment by gustawdaniel** [comment]
@brendankenny I confirmed. In my case, it works. Thank you @Hoten and @paulirish.

**Comment by lrusik** [comment]
The same here http://77.68.7.68/
