### ISSUE TITLE
Network payloads reporting post-gzip decompression sizes

### ISSUE THREAD

**Issue by mikesherov** [GoogleChrome/lighthouse#7151]
This is very similar to a bug I reported a while ago (#3588), but is now doing the same for (at least) JS payload sizes: 

#### Provide the steps to reproduce
1. Run https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.skillshare.com&tab=desktop

#### What is the current behavior?
2. Notice the "enormous payloads" advice mentions 0.....js with a 4MB payload size:
![image](https://user-images.githubusercontent.com/364532/52228090-74614480-287f-11e9-9af3-9e2151635242.png)

#### What is the expected behavior?
3. The value reported is the size sent over the wire, as per devtools:
![image](https://user-images.githubusercontent.com/364532/52228128-90fd7c80-287f-11e9-9065-7d99b0c797d9.png)

#### Environment Information
* Affected Channels: PageSpeed Insights
* Lighthouse version: *unknown*
* Node.js version: N/A
* Operating System: N/A

**Related issues**
#3588 which was fixed last year, and was the same bug, but for documents instead of javascript.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/pagespeed-insights-discuss/luQUtDOnoik

**Comment by patrickhulce** [comment]
Thanks @mikesherov! This is the same issue as #7141 and it's being investigated.

**Comment by mikesherov** [comment]
Thanks. I'll close mine then.
