### ISSUE TITLE
Running lighthouse multiple times consecutively 

### ISSUE THREAD

**Issue by santoshjoseph99** [GoogleChrome/lighthouse#7152]
**Summary**
Using the code below to do multiple lighthouse runs.

The output is this:
```
{ startTime: 998.562896,
  name: 'lh:init:config',
  duration: 128.00724400000001,
  entryType: 'measure' }
{ startTime: 9198.33562,
  name: 'lh:init:config',
  duration: 22.31878400000096,
  entryType: 'measure' }
```

So it doesn't look like lighthouse is resetting the `startTime` (or I'm doing something incorrect in how I'm launching lighthouse)?  Is there a flag to reset?

```
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');

async function launchChromeAndRunLighthouse(url, flags = {}, config = null) {
  const chrome = await chromeLauncher.launch(flags);
  flags.port = chrome.port;
  const results = await lighthouse(url, flags, config)
  await chrome.kill();
  return results;
}

const flags = {
  chromeFlags: ['--headless'],
};

async function start() {
  for(let i = 0; i < 2; i++) {
    let results = await launchChromeAndRunLighthouse('https://www.google.com', flags)
    console.log(results.lhr.timing.entries[0]);
  }
}

start();

```

**Comment by santoshjoseph99** [comment]
thanks @patrickhulce.  I was looking at the wrong place.
My use case: I'm running lighthouse multiple times to average the results...seems there is some variance between runs.

**Comment by patrickhulce** [comment]
Indeed there is. You can read more about that [in our variance and accuracy doc](https://docs.google.com/document/d/1BqtL-nG53rxWOI5RO0pItSRPowZVnYJ_gBEQCJ5EeUE/edit).

I'm going to go ahead and consider this closed, but feel free to chime in again if there's a specific issue you're facing.
