### ISSUE TITLE
Shows "Does not use HTTP/2 for all of its resources" tip when files are loaded from service worker via http/1.1 protocol

### ISSUE THREAD

**Issue by asistapl** [GoogleChrome/lighthouse#7158]
#### Provide the steps to reproduce
1. Run LH on https://www.anthonydesigner.com/

#### What is the current behavior?
All files are served with H2 initially but it still shows "Does not use HTTP/2 for all of its resources" tip because files are loaded from service worker via http/1.1 protocol.

#### What is the expected behavior?
I think it should show that tip only if files aren't served with H2 initially, not when service worker is used.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 3.2.0
* Operating System: Mac OSX

**Comment by wardpeet** [comment]
related issue https://github.com/gatsbyjs/gatsby/issues/11123

I'm putting up a PR for it.

**Comment by wardpeet** [comment]
@asistapl PR is up might giving this a spin yourself?

**Comment by asistapl** [comment]
@wardpeet I launched cli from "bug/sw-h2" branch and it works for me! Thank you 🎉

**Comment by paulyabsley** [comment]
@patrickhulce Do you know when this bug fix will be released?
