### ISSUE TITLE
New audit: CSP policy evaluation

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#7159]
This idea has been brought up a few time and deserves it's own issue (split out from #277).

https://csp-evaluator.withgoogle.com/ is the most robust CSP evaluation tool I've seen. (Roughly on par with [whatever report-uri uses](https://report-uri.com/home/analyse/https%3A%2F%2Fwww.paulirish.com%2F) and better than hardenize.com)

This tool is also open source: https://github.com/google/csp-evaluator

It gives detail like so:
![image](https://user-images.githubusercontent.com/39191/52304244-23b51e80-2947-11e9-9ad0-4b98751c7bff.png)

To start, we could use this to flag problems in your existing CSP. Essentially repackage their [findings](https://github.com/google/csp-evaluator#example-usage).

And later on, figure out how to tell sites without CSP to adopt it.

**Comment by verseopl** [comment]
I acctualy rewrite 
[https://github.com/voorhoede/lighthouse-security](https://github.com/voorhoede/lighthouse-security)
as a custom audits for LH, for now is about 11 additional audits (include CSP) grouped as new section called Security. 
voorhoede archived this repo.
I don't know why voorhoede don't sent pull request to add this audits to official LH repo and decided to run as a separate project.

But I can rewrite it again and add to LH as normal audits and gatheres. Only one think is hard to change, one of gatherers require "request" module to get response headers. It is possible to get response headers without "request" module?

**Comment by patrickhulce** [comment]
Indeed you have access to response headers of the network requests that were made during page load. If there are audits/gatherers that require additional requests that the page didn't make on its own, we'd likely be very careful about adding such an audit to core. 

I wouldn't want you to have any wasted work though @verseopl would you mind filing this great idea as an issue here, so the team can properly respond with priority and comment on available bandwidth? :)

**Comment by lweichselbaum** [comment]
I'm the maintainer of CSP evaluator and love the idea of integrating the evaluator logic into lighthouse.
In case you need any help or have questions regarding the integration feel free to ping me.
Also we already have a Chrome extension that uses the library, so maybe you can copy or re-use some of that logic [1].
For the light house integration it would make sense to make sure that analyzing multiple CSPs on a single response is implemented correctly (i.e. every CSP is enforced independently by the browser and therefore only the intersection of issues of all CSPs are relevant)

[1] https://chrome.google.com/webstore/detail/csp-evaluator/fjohamlofnakbnbfjkohkbdigoodcejf

**Comment by Seirdy** [comment]
If Lighthouse does end up with a CSP audit, it should support `connect-src: none` and `default-src: none`. Currently, such a CSP causes issues:

- [Issue 4386: Lighthouse broken when CSP connect-src ‘none’](https://github.com/GoogleChrome/lighthouse/issues/4386)
- [Issue 10225: Lighthouse unable to download robots.txt](https://github.com/GoogleChrome/lighthouse/issues/10225)
