### ISSUE TITLE
Running lighthouse on gmail triggers gmail mobile

### ISSUE THREAD

**Issue by idontusenumbers** [GoogleChrome/lighthouse#7164]
When running Lighthouse on gmail, with device emulation set to desktop within lighthouse, the mobile version of gmail is loaded and rendered.

**Comment by patrickhulce** [comment]
Thanks @idontusenumbers! I can't reproduce this on stable or canary Chrome though. There was a bug like this in an older version of Chrome have you updated recently? (navigate to `chrome://chrome` to force an update)

**Comment by idontusenumbers** [comment]
That was it! Thanks for the quick response!
