### ISSUE TITLE
Extract used CSS

### ISSUE THREAD

**Issue by adamseoul** [GoogleChrome/lighthouse#7169]
**Summary**

In Chrome this is shown marked in green for used CSS etc, can we just get what is used spat out? Instead of marking it red/green? 
If this is not the right place or my best avenue to find out how to do this then please if I could get some pointers?

**Comment by patrickhulce** [comment]
This isn't usually the best avenue since there can be rules that are used on hover/click/interaction/etc that you might not have triggered yet. Tools like https://github.com/uncss/uncss and https://github.com/purifycss/purifycss are pretty good options for doing this at build time.

**Comment by paulirish** [comment]
Yup
