### ISSUE TITLE
Lighthouse looks for event that never fires in --single-process mode

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#7171]
Chrome 72.0.3626.81
```
npx -p lighthouse@4.1.0 lighthouse https://www.hoten.cc --view --chrome-flags=--single-process
```

[This fix](https://github.com/GoogleChrome/lighthouse/issues/6968#issuecomment-461046015) might work.

**Comment by Hoten** [comment]
Tried the fix, but Lighthouse never even gets to computing `trace-of-tabs` in my testing:

```
ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +509ms
  ChromeLauncher Waiting for browser.....✓ +2ms
  status Connecting to browser +132ms
  status Resetting state with about:blank +604ms
  status Benchmarking machine +116ms
  status Initializing… +511ms
  status Loading page & waiting for onload Scripts, CSSUsage, ViewportDimensions, RuntimeExceptions, ChromeConsoleMessages, Accessibility, ImageElements, LinkElements, MetaElements, AnchorsWithNoRelNoopener, AppCacheManifest, Doctype, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, CrawlableLinks, Hreflang, EmbeddedContent, Canonical, RobotsTxt, TapTargets +17ms
```

**Comment by patrickhulce** [comment]
Are there any important use cases that require single process mode? I'm somewhat skeptical that all of the performance logic we've had and tested would necessarily hold true in such a different context.

**Comment by Hoten** [comment]
Explicitly stating we do not support this is an attractive solution.

**Comment by alekseykulikov** [comment]
One of the valid cases that require `--single-process` is AWS Lambda https://github.com/adieuadieu/serverless-chrome/issues/15 

But with a custom Chrome build like `serverless-chrome`, Lighthouse works without any modification.
So, Lighthouse actually supports `--single-process` but user needs a custom Chrome build that handles it :)

**Comment by paulirish** [comment]
We dont officially support --single-process, though yes the binary that @alekseykulikov points out may resolve things, but that's not in our purview.
