### ISSUE TITLE
OptimizedImages gatherer can take >20s

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#7173]
Locally, I see it take 30s when running LH on https://www.portuguesetrails.com/en
On LR, that's enough to hit our 60s render timeout and fail the entire run. (Which it does)

I think 15s is a decent time budget for this gatherer. (And probably all gatherers).

1. We can look into speeding up this gatherer.
2. We can enforce a deadline for all gatherers.

Thoughts? @patrickhulce

**Comment by brendankenny** [comment]
We could also sort by some filesize/image size ratio (aka possibility of needing optimization) and cut off after a certain number of images/certain amount of time.

Is the problem many many images or certain images or...?

**Comment by patrickhulce** [comment]
>Is the problem many many images or certain images or...?

That page re-encodes 175 images, 100 of which take <100ms each but the top ones can take 1-3s.

> We could also sort by some filesize/image size ratio (aka possibility of needing optimization) and cut off after a certain number of images/certain amount of time.

This sounds reasonable to me.

I'd also be on board if an image is enormous enough just saying, "OMG this image is huge, there's no reason for it to be this big" and not even trying to re-encode it. JPEG bytes/pixel should be ballpark X, WebP bytes/pixel should be ballpark Y, call it a day.

**Comment by patrickhulce** [comment]
Aside @paulirish was this the type of site you had in mind when you said we needed to take another look at image savings? In this case the numbers are all extreme but the site's horribleness is even more extreme. On our throttling settings it'd take 3+ minutes to download all these ridiculous images.

**Comment by paulirish** [comment]
> Aside @paulirish was this the type of site you had in mind when you said we needed to take another look at image savings? 

I just pulled it at random from the LR logs. Someone out there wants it to work on PSI, so ... yeah I guess i'd like it to work as well. :)

**Comment by patrickhulce** [comment]
> I just pulled it at random from the LR logs. Someone out there wants it to work on PSI, so ... yeah I guess i'd like it to work as well.

Haha oh no, I was going slightly off-topic from this issue with that question. We will definitely make the gatherer work on all sites :)

I was asking about the image audit opportunity savings amounts being higher than you expected.
