### ISSUE TITLE
Extension Error: PAGE_HUNG

### ISSUE THREAD

**Issue by FredPZ** [GoogleChrome/lighthouse#7179]
**Lighthouse Version**: 4.0.0
**Lighthouse Commit**: bfa10f1ac4ba8cdf95c809858d8bc4c8ac1c1da8
**Chrome Version**: 71.0.3578.98
**Initial URL**: https://www.lulli-sur-la-toile.com/saint-valentin.html
**Error Message**: PAGE_HUNG
**Stack Trace**:
```
LHError: PAGE_HUNG
    at chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:19851:7
```

**Comment by patrickhulce** [comment]
This error means that the page stopped responding. The solution here is to re-run. If the error repeats, the page has an infinite loop and needs to be fixed.
