### ISSUE TITLE
DBW: audit to check if app is respecting `Save-Data: on` header

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#718]
Audit could include:
- If the app is using images that are way too big
- Overall transferred bytes is > X. Need to define X.
- SW doesnt cache > X bytes when the header is present. See also https://github.com/GoogleChrome/sw-precache/issues/145
- ???

Simple: We could also try a  run with the header and without the header to see if the same number of bytes are transferred.

**Comment by addyosmani** [comment]
A while back I tried doing this using a regular check of data from BigQuery/HTTPArchive on the average size of images used in webpages. It's not as scientific as it could be, but allows an "X is larger than this number is should definitely be smaller than" type check.

**Comment by ebidel** [comment]
Big query:

```
SELECT AVG(bytesTotal) FROM [httparchive:runs.latest_pages_mobile] LIMIT 1000
```

**Comment by paulirish** [comment]
This kind of ties in to perf budgets as we're asserting on transfer sizes...

But in order see that the site respects this, we'd have to load the site twice.

value: good.
implementation feasibility: good.
effect on LH run latency: bad.
