### ISSUE TITLE
Default GZIP compression ratio is pessimistic for CSS

### ISSUE THREAD

**Issue by Anwardo** [GoogleChrome/lighthouse#7180]
#### Provide the steps to reproduce
1. Run LH with Google Pagespeed on https://mopinion.com/test-pagespeed/
Note: the page is not otherwise optimized for speed.

#### What is the current behavior?
Our 3rd party javascript tool fetches it's styles via gzipped json and then appends it in a style tag to the DOM. 
Pagespeed is reporting a size of 80kb and a potential savings of +- 70kb under 'Defer unused CSS' when the total configuration fetched by our tool is only around 20kb gzipped. 
This regarding the following entry:
<img width="929" alt="schermafbeelding 2019-02-07 om 15 56 41" src="https://user-images.githubusercontent.com/5699234/52420017-8813e180-2af1-11e9-8ebe-d00af199b568.png">

#### What is the expected behavior?
Calculated scores and savings should be based on actually fetched resources, size in dom does not perse reflect actual data fetched.

#### Environment Information
* Affected Channels: Pagespeed
* Lighthouse version:-
* Node.js version:-
* Operating System:-

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/7141

**Comment by patrickhulce** [comment]
Thanks for filing @Anwardo! I'm seeing a completely different set of styles in PSI now though :/ We should be taking into account gzip if the resource that it was attributed to was gzipped. 

![image](https://user-images.githubusercontent.com/2301202/52423041-e8d4f700-2abc-11e9-97ff-51c7d471a754.png)

**Comment by patrickhulce** [comment]
Also note if you were testing a few days ago, there was a bug in PSI that was ignoring all gzipped sizes.

**Comment by Anwardo** [comment]
Thanks for your response @patrickhulce! I was testing on the day I commented. I think the results you got from PSI were because some of our servers didn't sync with latest version of the repo yet. Because those results are related to an older version of our tool. I think if you try again you should get the correct results. 

Also here some screenshots of the actual request, the requested css content causing the problem.

<img width="1020" alt="schermafbeelding 2019-02-11 om 08 57 56" src="https://user-images.githubusercontent.com/5699234/52551236-e2f05600-2ddb-11e9-9e5e-dbabb7e78e78.png">
<img width="910" alt="schermafbeelding 2019-02-11 om 09 00 12" src="https://user-images.githubusercontent.com/5699234/52551235-e257bf80-2ddb-11e9-9202-ea2bca30783e.png">
<img width="799" alt="schermafbeelding 2019-02-11 om 09 01 21" src="https://user-images.githubusercontent.com/5699234/52551233-e257bf80-2ddb-11e9-9e3e-b7cf6007e149.png">

**Comment by Anwardo** [comment]
@patrickhulce thanks for your quick action! I noticed an update was merged, but I didn't see any change in our calculated saving size. I waited a couple of days to account for possible caching but still don't see any change. Are the changes for a more optimistic GZIP ratio live on PSI yet and if so should I not be seeing at least somewhat of an improvement in calculated savings?

**Comment by patrickhulce** [comment]
@Anwardo it's been merged but not in a new LH release. It will definitely take some time before this version of LH makes its way to all the stable channel.
