### ISSUE TITLE
An error occurs on running Lighthouse as a node module for several pages in parallel

### ISSUE THREAD

**Issue by vermi1ion** [GoogleChrome/lighthouse#7187]
#### Environment Information
* Affected Channels: Node
* Lighthouse version: 4.1.0, 4.0.0, 4.0.0-beta
* Node.js version: 8.11.3
* Operating System: Windows 10 Pro

**Steps**
1. Run Lighthouse as a node module for multiple pages
` node test_lh.js`

test_lh.js
`
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');
var fs = require('fs');
const minimist = require('minimist');
const arguments = minimist(process.argv.slice(2));

function launchChromeAndRunLighthouse(url, opts, config = null) {
  return chromeLauncher.launch({chromeFlags: opts.chromeFlags}).then(chrome => {
    opts.port = chrome.port;
    return lighthouse(url, opts, config).then(results => {

      return chrome.kill().then(() => results.lhr)
    }).catch((err) => console.log(err));;
  });
}
var pages = [
                {"label":"first", "url": "https://www.google.com/"},
                {"label":"second", "url": "https://www.google.com/doodles/"},
                {"label":"third", "url": "https://www.google.com/doodles/clara-rockmores-105th-birthday"}
      ];
const opts = {
    chromeFlags: ['--show-paint-rects', '--headless']
};

if(arguments['type'] == 'simple')
{
    launchChromeAndRunLighthouse(
        pages[0].url, opts).then(results => {
        fs.writeFileSync(`${pages[0].label}_report.json`, JSON.stringify(results), 'utf8');
    }); 
}
else
{
    pages.forEach(page => {
        launchChromeAndRunLighthouse(
            page.url, opts).then(results => {
            fs.writeFileSync(`${page.label}_report.json`, JSON.stringify(results), 'utf8');
        }); 
    });
}
`

**Expected**
3 JSON files with data are created

**Actual**
3 files are created - the first one with the report data, other contain "undefined"
An error in the console log, the process isn't completed
` C:\Git\LightHouse.Test>node test_lh.js
{ Error: no known mark: lh:gather:afterPass:RobotsTxt
    at Object.exports.stop (C:\Git\LightHouse.Test\node_modules\marky\lib\marky.cjs.js:76:13)
    at Function.timeEnd (C:\Git\LightHouse.Test\node_modules\lighthouse-logger\index.js:128:11)
    at Function.afterPass (C:\Git\LightHouse.Test\node_modules\lighthouse\lighthouse-core\gather\gather-runner.js:341:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) friendlyMessage: undefined }
{ Error: no known mark: lh:gather:afterPass:Accessibility
    at Object.exports.stop (C:\Git\LightHouse.Test\node_modules\marky\lib\marky.cjs.js:76:13)
    at Function.timeEnd (C:\Git\LightHouse.Test\node_modules\lighthouse-logger\index.js:128:11)
    at Function.afterPass (C:\Git\LightHouse.Test\node_modules\lighthouse\lighthouse-core\gather\gather-runner.js:341:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) friendlyMessage: undefined }
`
Running Lighthouse for 1 test page doesn't cause an error `node test_lh.js --type simple`
The issue with multiple pages isn't reproduced on Lighthouse version v4.0.0-alpha.2-3.2.1

**Comment by patrickhulce** [comment]
Thanks for filing @vermi1ion! We highly recommend against running multiple instances of LH at once on the same machine as they tend to interfere with the results. If you've got a crazy beefed up machine with plenty of cores and memory, we'd recommend parallelizing in different processes.

**Comment by FahdJamy** [comment]
@patrickhulce then what is the solution for running lighthouse for multiple pages.
Are you suggesting one should always create multiple files to run different pages?
Isn't that repetitive???????

**Comment by connorjclark** [comment]
The recommendation is do each LH run in a separate process. What do you mean "always create multiple files"?
