### ISSUE TITLE
role="figure" marked as invalid, Axe reports it as valid

### ISSUE THREAD

**Issue by jessebrack** [GoogleChrome/lighthouse#7213]
#### Provide the steps to reproduce
1. Run LH on https://www.jessebrack.com/figure

#### What is the current behavior?
`figure` is flagged as an invalid value for the attribute `role`, i.e. `role="figure"`.

#### What is the expected behavior?
`figure` should be a valid value for `role` ([W3 Spec](https://www.w3.org/TR/wai-aria-1.1/#figure)). Axe treats it as a valid value.

#### Environment Information
* Affected Channels: DevTools
* Chrome version: 72.0.3626.96
* Operating System: Mac OSX

**Comment by patrickhulce** [comment]
Thanks @jessebrack! Do you happen to know the version of axe that treats it correctly?

**Comment by exterkamp** [comment]
According to [axe's docs](https://github.com/dequelabs/axe-core/blob/develop/doc/aria-supported.md) they don't support `figure` roles.  Someone with more background could maybe give context as to why @patrickhulce @paulirish 

This might be more appropriate as an issue filed to them, as the upstream.

**Comment by exterkamp** [comment]
@patrickhulce does any version treat it correctly?  I think he is saying the _expected_ behavior is that it should, but none do.

**Comment by patrickhulce** [comment]
Oooooh, I misunderstood then. Yeah, this should be filed upstream with [axe-core](https://github.com/dequelabs/axe-core/issues) then. I didn't see an open issue for it, but they'd probably know much better than me :)

**Comment by jessebrack** [comment]
@patrickhulce Chrome extension v3.7.0

@exterkamp Thanks for finding that doc reference, this explains it for me!

I believe the error is on my part during my initial testing, retesting with Axe does now show that `figure` is not a valid value.

This might be a good opportunity to clarify the wording in the violation which I'll take upstream.

Thank you everyone!
