### ISSUE TITLE
Error : Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by irfanshafi1** [GoogleChrome/lighthouse#7218]
**Summary**

I have adjusted the ‘font-display’ then i thought that is optional or fallback as explained in the documentation, but still the same i  get ‘Ensure text remains visible during webfont load‘ performance warning.
 help!

**Comment by patrickhulce** [comment]
You're probably in the same situation as #6628. 

#7191 is pending to make it looser.

**Comment by paulirish** [comment]
fixed by #7191
