### ISSUE TITLE
Is it possible run lighthouse audit for the resources loaded in on-demand.

### ISSUE THREAD

**Issue by ssivanatarajan** [GoogleChrome/lighthouse#7219]
**Summary**
i want to run the lighthouse audit for the resources(css,js etc) which are loaded in on-demand.  Example "Minify CSS" audit for the css files which are loaded on-demand.

Is there any way to run lighthouse like recording performance in dev-tools?  we can open the browser and start the audit then do some operations in the browser, then stop the audit.

**Comment by patrickhulce** [comment]
Not really at the moment. 

#3837 tracks efforts to make this possible programmatically.

What I think you're looking for is mostly captured in #5187.
