### ISSUE TITLE
Running Lighthouse from the Extension incorrectly reports missing form labels

### ISSUE THREAD

**Issue by calder12** [GoogleChrome/lighthouse#7224]
#### Provide the steps to reproduce
1. Run LH on https://calder.io from the Chrome Browser Extension.
2. Run LH from Chrome developer tools Audit tab

#### What is the current behavior?
When running from the Extension, Lighthouse reports that the form elements have no associated labels (they do), but when running from developer tools LH reports correctly.

#### What is the expected behavior?
Both the extension, and the developer tools audit, show produce the same results.

#### Environment Information
* Lighthouse version: 4.0.0 (the one giving the wrong report from the extension)
* Lighthouse version: 3.2.0 (the one running from Chrome dev tools)
* Operating System: Windows 10

**Comment by patrickhulce** [comment]
Thanks @calder12! I can confirm this behavior with axe-core 3.1.2. Would you mind filing this in the appropriate repository (https://github.com/dequelabs/axe-core/issues)?

AFAICT axe should be saying these are valid unless there's something I'm missing.
![image](https://user-images.githubusercontent.com/2301202/52655416-b874ca80-2eb9-11e9-876f-757c063425af.png)

**Comment by calder12** [comment]
> Thanks @calder12! I can confirm this behavior with axe-core 3.1.2. Would you mind filing this in the appropriate repository (https://github.com/dequelabs/axe-core/issues)?
> 
> AFAICT axe should be saying these are valid unless there's something I'm missing.
> ![image](https://user-images.githubusercontent.com/2301202/52655416-b874ca80-2eb9-11e9-876f-757c063425af.png)

Turns out there has been an issue open on this in axe-core since October.
https://github.com/dequelabs/axe-core/issues/1176

**Comment by brendankenny** [comment]
Unclear exactly when this shipped in axe-core, but looks all good in latest Lighthouse.
