### ISSUE TITLE
Downloading a report should be vaguely useful

### ISSUE THREAD

**Issue by kaihendry** [GoogleChrome/lighthouse#7229]
Use case: Lighthouse identifies issues, now you need to convey these findings to the developers in a clear manner.

Currently there is an option to download the report, which looks a little like https://s.natalian.org/2019-02-13/1550024949_2560x1440.png How is anyone supposed to use that?

Expectation was a PDF or something that could be talked about in the context of an email.

**Comment by brendankenny** [comment]
@kaihendry there are two options, "Save as HTML" and "Save as JSON". It looks like maybe you did the JSON option?

If you want a PDF, you can instead select the "Print Expanded" from that dropdown and use the system print dialog to select printing to a PDF.

**Comment by kaihendry** [comment]
https://s.natalian.org/2019-02-13/73.mp4

**Comment by brendankenny** [comment]
Ah, sorry, this was in DevTools :)

As a workaround, you can drag that file into https://googlechrome.github.io/lighthouse/viewer/ to get an HTML report again, then those options I mention above will be available from the share icon (as well as a "Save as Gist" option to save to your gists and get a permalink if you'd rather share that way).

@paulirish for the DevTools UI side of things

**Comment by kaihendry** [comment]
Still I'm a bit puzzled how am I supposed to share this report. https://s.natalian.org/2019-02-13/share.mp4

I remember the old days when you would used to able to use a URL to share information.

**Comment by Hoten** [comment]
You can use [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) for now.

**Comment by brendankenny** [comment]
> I remember the old days when you would used to able to use a URL to share information.

You do indeed have to approve the github prompt to let it save as a gist to get a shareable URL. The lighthouse viewer doesn't have any storage or anything, it's just a report viewer. Saving to a gist, however, will update the URL to a permalink that you can share (revisiting that URL will load the gist into the viewer). You can also do the "Save as HTML" thing [mentioned above](https://github.com/GoogleChrome/lighthouse/issues/7229#issuecomment-463034303) and host that wherever too (it's a single self-contained file).

This was a product decision to not get into the service side of things and keep lighthouse just a tool. As @Hoten mentioned, though, PageSpeed Insights is more of a service in that direction (as are other external services, e.g. [WebPageTest](https://www.webpagetest.org/lighthouse)).

**Comment by BigBlueHat** [comment]
It would be great to get the "Save as HTML" option added to the DevTools Lighthouse. Hosting that is easy enough, and sense it's self contained, even emailing it works fine.

**Comment by Hoten** [comment]
DevTools will export HTML when this lands: https://chromium-review.googlesource.com/c/chromium/src/+/1575021

**Comment by brendankenny** [comment]
let's move tracking over to #9134, as it has the specific steps needed to turn this on in DevTools.
