### ISSUE TITLE
feature_request(next-gen_formats): Slick + WebP support

### ISSUE THREAD

**Issue by Kristinita** [GoogleChrome/lighthouse#7245]
### 1. Summary

**If** I use [**Slick**](http://kenwheeler.github.io/slick/) + [**WebP**](https://developers.google.com/speed/webp/):

    I get “Serve images in next-gen formats” in PageSpeed Insights.

### 2. Details

I use Slick — popular library, [**more than 23000 stars**](https://github.com/kenwheeler/slick) on GitHub — for sliders and image galleries. I use WebP format [**and fallback images**](https://css-tricks.com/using-webp-images/#article-header-id-3), if user browser [**doesn't support webp**](https://caniuse.com/#search=webp). But PageSpeed Insights show, that I need “serve images in next-gen formats”.

PageSpeed Insights works as expected for [**basic `picture` tag for WebP usage**](https://stackoverflow.com/a/44918916/5951529).

### 3. MCVE

+ [**Sources on CodePen**](https://codepen.io/Kristinita/pen/LqBBVN)

+ HTML:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>
        Slick + WebP demo
    </title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel/slick/slick.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel/slick/slick.css" />
</head>

<body>
    <div class="KiraSlider">
        <picture>
            <source data-lazy-srcset="https://kiraslickwebppagespeedinsights-non-validimageformat--kristinita.repl.co/KiraNose.webp" type="image/webp">
            <img data-lazy="https://kiraslickwebppagespeedinsights-non-validimageformat--kristinita.repl.co/KiraPigeon.png" alt="KiraNose" />
        </picture>
        <picture>
            <source data-lazy-srcset="https://kiraslickwebppagespeedinsights-non-validimageformat--kristinita.repl.co/KiraRiver.webp" type="image/webp">
            <img data-lazy="https://kiraslickwebppagespeedinsights-non-validimageformat--kristinita.repl.co/KiraPigeon.png" alt="KiraRiver" />
        </picture>
    </div>
</body>

</html>

```

+ Stylus:

```stylus
body
    background-color papayawhip

img
    margin auto
```

+ CoffeeScript:

```coffee
#########
# Slick #
#########
# JQuery carousel and/or slideshow:
# http://kenwheeler.github.io/slick/
# Options:
# http://kenwheeler.github.io/slick/#settings
$(document).ready ->
    $('.KiraSlider').slick
        lazyLoad: 'ondemand'
        autoplay: true
        variableWidth: false
        adaptiveHeight: true
        slidesToShow: 1
        fade: true
        speed: 1000
        arrows: false
        slidesToScroll: 1
        autoplaySpeed: 2000
        pauseOnFocus: false
        pauseOnHover: false
    return

# srcset support:
# https://github.com/kenwheeler/slick/pull/1661#issuecomment-386572834
$('.KiraSlider').on 'lazyLoaded', (evt) ->
    $(evt.currentTarget).find('source').each (i, source) ->
        $source = $(source)
        $source.attr 'srcset', $source.data('lazy-srcset')
        return
    return

```

Please, pay attention to [**`srcset` support for Slick**](https://github.com/kenwheeler/slick/pull/1661#issuecomment-386572834).

### 4. Demonstration

+ [**Live demo**](https://kiraslickwebppagespeedinsights-non-validimageformat--kristinita.repl.co/)

+ Browser, that support WebP — Windows 10, Firefox 65 (64-bit):

![Firefox](https://i.imgur.com/jeHnrvS.gif)

+ Browser, that not support WebP — macOS Mojave, Safari 12 (via BrowserStack):

![Mojave](https://i.imgur.com/Bs7zWhi.gif)

`picture` + `srcset` works in browsers [**as expected**](https://css-tricks.com/using-webp-images/#article-header-id-3): WebP for supported browsers, fallback image for non-supported.

### 5. Expected behavior

No “Serve images in next-gen formats” opportunity in PageSpeed Insights.

### 6. Actual behavior

+ [**PageSpeed Insights for demo**](https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fkiraslickwebppagespeedinsights-non-validimageformat--kristinita.repl.co%2F&tab=desktop):

![Next-gen formats](https://i.imgur.com/j13KL3j.png)

> Image formats like JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG, which means faster downloads and less data consumption.

Thanks.

**Comment by patrickhulce** [comment]
Thanks for the detailed report @Kristinita!

But I think Lighthouse is doing the right thing here. When I visit your demo URL and open the network tab in Chrome, the PNG is still downloaded for `Pigeon`, even if the other images are WebP. I'm not sure if it's how the library is being used or a bug in the libraries handling of the `picture` tag, but something is forcing the PNG to be downloaded and Lighthouse is appropriately catching it.

![image](https://user-images.githubusercontent.com/2301202/52794365-4aeda900-3035-11e9-9b55-1ccd1c0dcb45.png)


My best guess is that the library is setting the `src` of the `img` before the `src` of the other `source` elements and so the browser first thinks it needs to download the image before realizing it can use the other `source`, but I'm not a slick expert 🤷‍♂️

**Comment by brendankenny** [comment]
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen.
