### ISSUE TITLE
False does not use HTTP/2 report for resources loaded through service workers

### ISSUE THREAD

**Issue by khaledosman** [GoogleChrome/lighthouse#7247]
#### Provide the steps to reproduce
1. Run LH on https://github-search-lem91qir2.now.sh/ via the audits tab

#### What is the current behavior?
Lighthouse reports "Does not use HTTP/2 for all of its resources" in Best Practices even though these resources were actually loaded through the service worker.

If I unregister the service worker from the Applications tab then run lighthouse again, it passes the Best Practices test with a 100 score.

#### What is the expected behavior?
Lighthouse should not report the HTTP/2 rule if the resources were loaded through service worker

**Comment by patrickhulce** [comment]
Thanks for filing @khaledosman! A fix is in progress #7197!

duplicate #7158
