### ISSUE TITLE
DevTools Error: Runtime.evaluate response did not contain a "result" object

### ISSUE THREAD

**Issue by nov44l** [GoogleChrome/lighthouse#7248]
**Initial URL**: http://pk88.lobbyroom88.com/lobby-tournament/index.php?tablecode=ljqwLeR8KyNlhvm9Xyeq2WUXEhR%2FJ52qGbRr6uBNk1ZokbhXNcCBceFUwXgGHgoF%2FEMzKSqaVO%2FjwklIsRHcB1D8a%2F7ZtaJaodntNRPpByLHyGghrmmPOQxseYl10xPg8Sq7VR6gBKwM9g%2FQA6ZtKQ%3D%3D&rid=2774&lang=id
**Chrome Version**: 72.0.3626.109
**Error Message**: Runtime.evaluate response did not contain a "result" object
**Stack Trace**:
```
Error: Runtime.evaluate response did not contain a "result" object
    at sendCommand.then.response (chrome-devtools://devtools/remote/serve_file/@fae8db7ab9280fa6704a59980263c804f809ebd5/audits2_worker/audits2_worker_module.js:1044:47)
```

**Comment by patrickhulce** [comment]
duplicate #6869
