### ISSUE TITLE
PWA in chrome Beta version not reporting score

### ISSUE THREAD

**Issue by dryleaf** [GoogleChrome/lighthouse#7253]
Not an issue, rather a question requesting clarification.

**Summary**
I have just noticed that my chrome beta version app is not reporting the PWA score, only the recommendations are displayed. 
I tried to search for the beta release change-list manual as to the reason this change was made.

My question is:
- Is there any reason as to why the PWA score value has been removed from the lighthouse dev-tools (in chrome beta version)?

😕

**Comment by exterkamp** [comment]
Hi, thanks for the question!

The PWA section was refactored, so I assume you are talking about the features found in #6486 and #6526 tracked by #6395.  These refactors are starting to hit beta versions of Chrome, and should be the norm moving forward.  

The PWA section still has a numeric score underlying it and can be seen if you run the CLI tool and generate JSON reports, or download the devtools report and look at the JSON.

@brendankenny correct me if I'm lying here.
