### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by prahlad1** [GoogleChrome/lighthouse#7257]
**Lighthouse Version**: 4.0.0
**Lighthouse Commit**: bfa10f1ac4ba8cdf95c809858d8bc4c8ac1c1da8
**Chrome Version**: 72.0.3626.81
**Initial URL**: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Ftellmeor.co.in%2F
**Error Message**: PROTOCOL_TIMEOUT
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT
    at setTimeout (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:19252:11)
```

**Comment by patrickhulce** [comment]
duplicate #6512
