### ISSUE TITLE
NO_TRACING_STARTED only in LightRider

### ISSUE THREAD

**Issue by danman1234** [GoogleChrome/lighthouse#7276]
https://developers.google.com/speed/pagespeed/insights/ 
when i check my site https://www.igeodate.com

Was working fine for this pagina before.
But now it just give me the error (NO_TRACING_STARTED) and nothing is checked?

Well, no clear error, when will they fix it?

**Comment by patrickhulce** [comment]
Thanks for filing @danman1234 I can reproduce this. Locally Lighthouse is able to run just fine.

cc @Hoten @exterkamp for their LR expertise.

**Comment by danman1234** [comment]
o there is no solution? cause?

**Comment by patrickhulce** [comment]
The issue is with the API. The workaround right now is to get results locally instead of using PSI. 

Use Chrome DevTools Audits panel, the Lighthouse chrome extension, or the `lighthouse` CLI module on npm.

**Comment by danman1234** [comment]
I got that. But why does it work fine with other sites? What makes the
difference?

**Comment by patrickhulce** [comment]
If we knew that already, it wouldn't be broken 😉 it will take some investigation @danman1234 hold tight.

**Comment by paulirish** [comment]
@danman1234 

does this look familiar? :)

```js
window.location = 'https://www.igeodate.com:443/';
```

<img width="1008" alt="screen shot 2019-02-20 at 1 38 50 pm" src="https://user-images.githubusercontent.com/39191/53089331-f8205f80-3514-11e9-8833-fb81e20e641b.png">

That's an infinite loop when loading. It's going to cause some problems.. :)

**Comment by danman1234** [comment]
Yeah, but it is commented±

//window.location = '';   as seen in the source.
I guess when u not logged u see that, but it it just goes in there once,
but when cookies are off then it will be a loop yes, i have removed this.

Now it is 39% while in the older version i got 92. pfff
ok does this really seem important?

**Comment by exterkamp** [comment]
I can't repro this anymore in `PSI` so I think this is fixed?  Site seems to get a consistent 35-45 Mobile/65-75 Desktop.  Feel free to open again if this is still an issue for you.
