### ISSUE TITLE
Chrome Dev Audit always 100

### ISSUE THREAD

**Issue by bflopez** [GoogleChrome/lighthouse#7291]
#### Provide the steps to reproduce
1. Run LH on www.hunterdouglas.com or any website using Chrome Dev Tools.

#### What is the current behavior?
Result is always 100 when using audit in Chrome Dev Tools, even in Incognito mode.

#### What is the expected behavior?
To match the PageSpeed insights webpage or at least be closer to those results

#### Environment Information
* Affected Channels: Chrome DevTools
* Lighthouse version: 3.2.0
* Node.js version: 8.9.4
* Operating System: Mac OS 10.14
* Chrome Version: Version 72.0.3626.109 (Official Build) (64-bit)

#### Lighthouse Test Settings: 
* Device: Mobile
* Audit: Performance
* Throttling: No throttling
* Clear Storage: Checked

**Comment by Hoten** [comment]
No throttling in your local run explains the differences. Please see this doc: https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md

**Comment by bflopez** [comment]
Interesting. I did try running it with throttling and it didn't work either. I have been running it without throttling for some time now and it was giving me a more reasonable results within a 5-10 point range of PageSpeed Insights. I will definitely check out the link regardless.

**Comment by bflopez** [comment]
I did look into running again with other throttling options and to my surprise it worked. I might be remembering this wrong but I do have memory of it working with No Throttling. Maybe the changes I made fixed the scores...Anyways thank you. Can close.
