### ISSUE TITLE
Cache of mobile phone is not cleared

### ISSUE THREAD

**Issue by gottlike** [GoogleChrome/lighthouse#7303]
#### Provide the steps to reproduce
1. Run LH on any URL after [connecting an actual mobile](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#testing-on-a-mobile-device)
2. Run LH again on the same URL

#### What is the current behavior?
Cache and cookies of the remote Chrome are not cleared.

#### What is the expected behavior?
Cache and cookies are cleared - same as with usage on local device.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 4.1
* Node.js version: 8.10
* Operating System: Ubuntu 18.04

**Comment by patrickhulce** [comment]
Thanks for filing! We never clear cookies, so that part isn't surprising. Would you mind providing a bit more information about how you know the cache isn't being cleared?

We send all the same commands regardless, so there might be just a narrow set of circumstances this occurs in.

**Comment by gottlike** [comment]
> We never clear cookies, so that part isn't surprising.

That's strange. I assumed they were cleared, because when I start LH on my PC it starts Chrome and I see the tested page - then I click on a "yes I accept cookies" overlay to close it. Next LH run on the same URL will display the cookie message again. This indicated to me that cookies are not saved (or cleared afterwards/before).

> Would you mind providing a bit more information about how you know the cache isn't being cleared?

I just noticed the cookie overlay thingy not popping up again, but that's okay if it's expected behaviour to not clear cookies. This, plus a seemingly quicker page load after the first run, led me to believe the cache isn't being cleared. But it was probably just the usual variance then.

Thanks for the quick feedback!
