### ISSUE TITLE
Extension Error: Cannot attach to this target.

### ISSUE THREAD

**Issue by raghavddps2** [GoogleChrome/lighthouse#7308]
**Lighthouse Version**: 4.0.0
**Lighthouse Commit**: bfa10f1ac4ba8cdf95c809858d8bc4c8ac1c1da8
**Chrome Version**: 72.0.3626.109
**Initial URL**: http://ieeeritb.in/
**Error Message**: Cannot attach to this target.
**Stack Trace**:
```
Error: Cannot attach to this target.
    at chrome.debugger.attach (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18781:15)
```

**Comment by patrickhulce** [comment]
duplicate #6990
