### ISSUE TITLE
DevTools Error: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by chenqiwei123** [GoogleChrome/lighthouse#7313]
**Initial URL**: https://mp.weixin.qq.com/s?__biz=MjM5MjAxNDM4MA==&mid=414293326&idx=1&sn=3d95dfb8e6bc4219a5714fbce89a8fc4&mpshare=1&scene=23&srcid=02245KJvVrwF3BVaUjhBMx9r#rd
**Chrome Version**: 72.0.3626.81
**Error Message**: PROTOCOL_TIMEOUT
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT
    at setTimeout (chrome-devtools://devtools/remote/serve_file/@ac8b982e05014492d1bd7d317628a4f22a97ffa0/audits2_worker/audits2_worker_module.js:1027:210)
```

**Comment by patrickhulce** [comment]
duplicate #6512
