### ISSUE TITLE
is-on-https audit shouldn't count deeplink

### ISSUE THREAD

**Issue by tyohan** [GoogleChrome/lighthouse#7315]
Hi,
I'm using the WPT Lighthouse `httparchive.lighthouse.2019_01_01_mobile` report from http archive dataset  and I saw Lighthouse is counting deeplink as non secure. Below is the JSON audit result that I pull from bigquery for https://m.tokopedia.com.

```
"is-on-https":{
"description":"All sites should be protected with HTTPS, even ones that don't handle sensitive data. HTTPS prevents intruders from tampering with or passively listening in on the communications between your app and your users, and is a prerequisite for HTTP/2 and many new web platform APIs. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/https).",
"title":"Does not use HTTPS",
"score":0,
"details":{
  "items":[{"url":"tokopedia://home?link_click_id=616859343595600920"}],
  "type":"table",
  "headings":[{"text":"Insecure URL","itemType":"url","key":"url"}]
},
"displayValue":"1 insecure request found",
"scoreDisplayMode":"binary",
"id":"is-on-https",
"rawValue":false}
```
From the audit result above the url tokopedia://home?link_click_id=616859343595600920 is treated as non https and it failed the audit. I think deeplink shouldn't counted as non secure URL and the audit should be pass.

Below is the query to pull the data from HA bigquery dataset

```
SELECT
  url,
  JSON_EXTRACT(report, "$.audits['service-worker'].rawValue") AS service_worker,
  JSON_EXTRACT(report, "$.audits['works-offline'].rawValue") AS works_offline,
  JSON_EXTRACT(report, "$.audits['without-javascript'].rawValue") AS without_javascript,
  JSON_EXTRACT(report, "$.audits['is-on-https'].rawValue") AS is_on_https,
  JSON_EXTRACT(report, "$.audits['redirects-http'].rawValue") AS redirects_http,
  JSON_EXTRACT(report, "$.audits['load-fast-enough-for-pwa'].rawValue") AS load_fast_enough_for_pwa,
  JSON_EXTRACT(report, "$.audits['webapp-install-banner'].rawValue") AS webapp_install_banner,
  JSON_EXTRACT(report, "$.audits['splash-screen'].rawValue") AS splash_screen,
  JSON_EXTRACT(report, "$.audits['themed-omnibox'].rawValue") AS themed_omnibox,
  JSON_EXTRACT(report, "$.audits['viewport'].rawValue") AS viewport,
  JSON_EXTRACT(report, "$.audits['appcache-manifest'].rawValue") AS appcache_manifest,
  JSON_EXTRACT(report, "$.audits['no-websql'].rawValue") AS no_websql,
  JSON_EXTRACT(report, "$.audits['uses-http2'].rawValue") AS uses_http2,
  JSON_EXTRACT(report, "$.audits['uses-passive-event-listeners'].rawValue") AS uses_passive_event_listeners,
  JSON_EXTRACT(report, "$.audits['no-mutation-events'].rawValue") AS no_mutation_events,
  JSON_EXTRACT(report, "$.audits['no-document-write'].rawValue") AS no_document_write,
  JSON_EXTRACT(report, "$.audits['geolocation-on-start'].rawValue") AS geolocation_on_start,
  JSON_EXTRACT(report, "$.audits['no-vulnerable-libraries'].rawValue") AS no_vulnerable_libraries,
  JSON_EXTRACT(report, "$.audits['notification-on-start'].rawValue") AS notification_on_start,
  JSON_EXTRACT(report, "$.audits['deprecations'].rawValue") AS deprecations,
  JSON_EXTRACT(report, "$.audits['manifest-short-name-length'].rawValue") AS manifest_short_name_length,
  JSON_EXTRACT(report, "$.audits['password-inputs-can-be-pasted-into'].rawValue") AS password_inputs_can_be_pasted_into,
  JSON_EXTRACT(report, "$.audits['errors-in-console'].rawValue") AS errors_in_console,
  JSON_EXTRACT(report, "$.audits['image-aspect-ratio'].rawValue") AS image_aspect_ratio
FROM
  `httparchive.lighthouse.2019_01_01_mobile` AS LH
WHERE
  url = 'https://m.tokopedia.com/'
```

**Comment by patrickhulce** [comment]
Thanks for filing!

I wonder if it's time to flip this audit and finally just flag URLs that start with `http`...

**Comment by brendankenny** [comment]
how does this work? What kind of resource was this? When I try to load a link like that Chrome treats it as insecure as well

![screen shot 2019-02-25 at 14 48 12](https://user-images.githubusercontent.com/316891/53364266-706b9400-390c-11e9-852e-75f75b16705a.png)

So it seems somewhat reasonable for Lighthouse to do the same. If you have a protocol handler set does it act differently?

I also swear we were just looking at another request to support application-specific protocols, but can't find it now.

**Comment by paulirish** [comment]
+1 to only flag URLs that start with `http:`

**Comment by tyohan** [comment]
> how does this work? What kind of resource was this? When I try to load a url like that (as a script, cause 🤷‍♂️) Chrome treats it as insecure as well
> 
> ![screen shot 2019-02-25 at 14 48 12](https://user-images.githubusercontent.com/316891/53364266-706b9400-390c-11e9-852e-75f75b16705a.png)
> 
> So it seems somewhat reasonable for Lighthouse to do the same. If you have a protocol handler set does it act differently?
> 
> I also swear we were just looking at another request to support application-specific protocols, but can't find it now.

Seems it's not a script. May be they're trying to do something to detect if the app installed on device or not like on [this SO thread](https://stackoverflow.com/questions/13044805/how-to-check-if-an-app-is-installed-from-a-web-page-on-an-iphone). I found it from HttpArchieve dataset so not sure what actually they're trying to do. But if I audit their site directly from Chrome, the Lighthouse passed the audit. So can't reproduce it on their live site.

**Comment by brendankenny** [comment]
Since we can't reproduce and we never saw it in a live run, I'm going to close. We can always reopen or start a new issue if it comes up again.
