### ISSUE TITLE
Visual audit reporting

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#7327]
**Feature request summary**

Visually convey why applicable audits are failing by highlighting affected UI in the context of the page, either statically overlaid on a screenshot or interactively on the page itself.

The [VisBug](https://github.com/GoogleChromeLabs/ProjectVisBug) project is already well-positioned to handle the visualization of audit failures so it's worth exploring possible integration points between that and LH. For example, perhaps VisBug could run LH audits under the hood and highlight audit failures based on the JSON LHR. cc @argyleink

**What is the motivation or use case for changing this?**

Many of the audits are inherently visual in nature. They are testing that visible parts of the page behave as expected. When Lighthouse identifies elements that fail the audit, we show their innerHTML or selector to convey what is failing and rely on text to explain why it failed.

By showing the results visually, it's much easier to convey both what is failing and why. For example, the tap targets SEO audit checks for overlapping links/buttons. The results are a table of elements and box sizes. In addition to this easily serializable format, it would be helpful for users to be able to see these elements overlapping on the page so it's not only obvious what the issue is but also how to fix it.

Prototype of a visual report of overlapping tap targets:

![image](https://user-images.githubusercontent.com/1120896/53444292-c1968900-39db-11e9-88d1-00c0483a8fea.png)

Contrast that with the text-based approach:

![image](https://user-images.githubusercontent.com/1120896/53444268-b0e61300-39db-11e9-886f-7c5c90d6bbd0.png)

Here is a list of audits that are candidates for this visual reporting approach:

- Performance
  - properly size images
  - defer offscreen images
  - efficiently encode images
  - serve images in next-gen formats
  - use video formats for animated content
- Accessibility
  - all text remains visible during webfont loads
  - form elements do not have associated labels
  - image elements do not have [alt] attributes
  - some elements have a [tabindex] value greater than 0
  - links do not have a discernible name
  - buttons have an accessible name
  - background and foreground colors have a sufficient contrast ratio
  - [id] attributes on the page are unique
  - [accesskey] attributes on the page are unique
  - `<input type="image">` elements have [alt] text
  - `<object>` elements have [alt] text
  - `<video>` elements contain a `<track>` element with [kind="captions"]
  - `<video>` elements contain a `<track>` element with [kind="description"]
- Best Practices
  - displays images with correct aspect ratio
- SEO
  - document doesn't use legible font sizes
  - links have descriptive text
  - document doesn't have overlapping tap targets

**How is this beneficial to Lighthouse?**

Visual reporting will make it easier for LH users to make sense of the results and fix issues.

**Comment by argyleink** [comment]
thanks for the shout out =) i'd love to help facilitate a collab, here's a few thoughts!
- visbug's just custom elements, some of them with 0 deps (highlight, bounding boxes, etc). you may be able to use them right away if i published them to npm. most of them just need a setter called with a bounding box object
- visbug's got a plugin system that can invoke script or apply css to a page. if y'all make your scripts as simple as a function call, i can integrate it quickly. here's a PR with a pending plugin addition that the bundle just executes within the page https://github.com/GoogleChromeLabs/ProjectVisBug/pull/299
- a couple of visbug's plugins overlap with features y'all are looking to employ, namely accessibility audits and some HTML validation (ping me if you want a demo or instruction on how to test/preview them)

i think applying visual tips for visual tasks is a great idea! let me know what else I can do to help 👍

**Comment by mattzeunert** [comment]
I was looking at https://github.com/GoogleChrome/lighthouse/issues/6683 and I also really like the idea of showing a screenshot on hover, if we capture a full-page screenshot and the element's bounding box:

![Screenshot 2019-03-10 at 14 14 40 (3)](https://user-images.githubusercontent.com/1303660/54086183-12dd3b80-433f-11e9-805c-1d5806d0448d.png)

So if we have the page open we can highlight the element there, otherwise use a screenshot.

**Comment by mattzeunert** [comment]
Made a prototype: http://mattzeunert.surge.sh/visual-report/twitter.html

![twitter-visual-report](https://user-images.githubusercontent.com/1303660/54541905-b8715a00-4992-11e9-949a-07f4a27b7cda.gif)

**Comment by Hoten** [comment]
that is so so nice

**Comment by patrickhulce** [comment]
@mattzeunert that is epic! 🤩    

We should make this a priority IMO. Massive improvement for all the a11y audits too! 🎉

**Comment by mattzeunert** [comment]
Tried adding an inline thumbnail, and it [looks pretty good](https://lighthouse-2ibghgiyw.now.sh/#seo).

![Screenshot 2019-05-22 at 15 06 07](https://user-images.githubusercontent.com/1303660/58181140-28f26b00-7ca3-11e9-825c-e1c44bdc3a22.png)

I think we can do this and then show a modal on click/tap. (Not implemented yet in the prototype.)

Another idea that came up in the meeting was to show prev/next button in the modal. I wonder how useful this would be if we already have the inline thumbnail. Might be pretty complex to implement if we also need to show some kind of audit message alongside the screenshot.

**Comment by mattzeunert** [comment]
@hwikyounglee Here's a [prototype with inline thumbnails and a primitive modal](https://lighthouse-ofbnpvng8.now.sh/#seo).

**Comment by paulirish** [comment]
The element-screenshots functionality that Matt started and Connor completed addresses this feature request. Shipped ~ April 2021.

https://twitter.com/____lighthouse/status/1387134884225900550

before:

![](https://user-images.githubusercontent.com/1120896/53444268-b0e61300-39db-11e9-886f-7c5c90d6bbd0.png)

after: 

![image](https://user-images.githubusercontent.com/39191/172920770-5f6752db-2e4e-4bbe-8f9d-940f5e58d4d1.png)
