### ISSUE TITLE
HTML Report not rendering due to LHR

### ISSUE THREAD

**Issue by MKM1104** [GoogleChrome/lighthouse#7336]
#### Provide the steps to reproduce
1. Run LH on an internal site via the node module and puppeteer. 
2. Generate JSON results and convert to HTML via the lighthouse core ReportGenerator. 

#### What is the current behavior?
The generated HTML report doesn't render, it throws the following error 
Uncaught TypeError: Cannot read property 'locale' of undefined
    at Function.prepareReportResult (compiled-reportrenderer.js:54)
    at ReportRenderer.renderReport (compiled-reportrenderer.js:3123)
    at window.addEventListener._ (report.html:5401)

This seems to be due to the lhr object in the JSON, the report is looking for configSettings directly in the JSON instead of lhr.configSettings. 

![image](https://user-images.githubusercontent.com/48061846/53502502-7f8a4780-3aae-11e9-99d2-7021d2703ca1.png)

![image](https://user-images.githubusercontent.com/48061846/53502893-40a8c180-3aaf-11e9-99fe-d4e3ce628f70.png)

when I try modifying the HTML with the below code (after the LH JSON is fetched) it renders properly. 

window.__LIGHTHOUSE_JSON__ = window.__LIGHTHOUSE_JSON__.lhr; 

#### What is the expected behavior?
The HTML report should render without any issues. 

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 4.1.0
* Node.js version: 6.4.1
* Operating System: Windows 10

**Related issues**

**Comment by patrickhulce** [comment]
This seems like you're using the report renderer incorrectly. The report generator expects the JSON report (LHR as JSON), not the entire node response.

**Comment by paulirish** [comment]
@MKM1104 	Adding on, just use `obj.lhr` instead of `obj`. I think that should sort you out. :)
