### ISSUE TITLE
SEO score of 99 without further details

### ISSUE THREAD

**Issue by rentalh0sting** [GoogleChrome/lighthouse#7338]
We really like using LH (https://web.dev/measure) in helping us fix various issues on our websites and we consistently can get an SEO score of 100 for all of our websites, except for https://chiceventrentals.com/ where LH shows a score of 99 and without any further details on why it's not 100.   Can you please let me know why LH is not showing what needs to be corrected?

![image](https://user-images.githubusercontent.com/10382057/53513667-b8102e00-3a7a-11e9-8903-8bbc5a7ce752.png)

**Comment by patrickhulce** [comment]
Thanks for filing @rentalh0sting. The failure is with tap targets.

![image](https://user-images.githubusercontent.com/2301202/53513995-8a77b480-3a7b-11e9-85b1-25831dcfbbd5.png)

cc @rviscomi @mattzeunert it is a bit weird that we'll sweep it into "Passing" if the score is high enough. Maybe we should keep it below 90 if there are any?

**Comment by mattzeunert** [comment]
Agreed that that the failures should be more prominent. Thanks @rentalh0sting for letting us know!

The other SEO/Accessibility audits don't have this problem because they return a binary pass/fail result rather than returning a score. E.g the font audit size has a 40% illegible text threshold before failing. But having a score for tap targets makes sense, since it rewards fixing individual problems.

> Maybe we should keep it below 90 if there are any?

Yeah, multiplying the score by 0.89 if it's below 100 sounds good. An alternative would be to keep the score at 100 if more than 90% of tap targets pass, but that feels like sweeping problems under the rug.

**Comment by mattzeunert** [comment]
I talked to @rviscomi and he'd prefer if there was a way to show the results without affecting the score. Maybe we can vary the pass threshold per audit, or do we have ways to highlight "passing but score < 90" in the audit somehow?

If not, multiplying by 0.89 is ok too.

**Comment by patrickhulce** [comment]
> I talked to @rviscomi and he'd prefer if there was a way to show the results without affecting the score

@rviscomi as in you want the audit to be passing, but shown along with the other failing results?

Our position is that if it's passing it means it is not worth looking at, i.e. it should be collapsed by default and shown with the other hidden by default passing audits. If there's something that needs to be looked at, it should be failing. I'd say go with `* .9`/`Math.min(score, .89)`/`targets.length ? 0 : 1` if each and every failure should be looked at.

**Comment by rviscomi** [comment]
To clarify, IMO any tap targets score less than 100% should cause the audit to be expanded so users can see and fix the outstanding issues. If the score is 90-99% I'd like to see a UI treatment similar to the orange "warning" style (for example see below). If the score is less than 90% it should fail.

![image](https://user-images.githubusercontent.com/1120896/53652041-e8400400-3c15-11e9-9ff1-9c7a0b596488.png)

Matt's suggestion to multiply by 0.89 is one way to ensure the audit is expanded for the 90-99% case. I believe that would qualify as a failure and show the audit in red. Like I said, I think "warning" is a better UI in this case, but I understand if it throws a wrench in the implementation so I'll defer to you guys on the best approach.

**Comment by patrickhulce** [comment]
If you set the score display mode of tap targets audit to `numeric` then when `0.5 < score < 0.9` it will get the same treatment as `Minimize main-thread work` in that example. Red is for `< 0.5` and passing is `> 0.9`

**Comment by rviscomi** [comment]
Are those thresholds configurable per-audit?

**Comment by patrickhulce** [comment]
Not currently

https://github.com/GoogleChrome/lighthouse/blob/67539909facf70653fcfd7fa3f6d0802634b7a99/lighthouse-core/report/html/renderer/util.js#L23-L30

**Comment by mattzeunert** [comment]
@rviscomi Let's go ahead with `* 0.89` then?

**Comment by rviscomi** [comment]
Yeah SGTM
