### ISSUE TITLE
Documentation around config presets needs to be clearer

### ISSUE THREAD

**Issue by gidztech** [GoogleChrome/lighthouse#7344]
**Background:**
You can extend the default Lighthouse config like so:

```
{
        extends: 'lighthouse:default',
        settings: {
          emulatedFormFactor: 'desktop',
          ...
        },
}
```
This can be passed as an object to the Lighthouse node API. 

I found a number of presets (`default`, `full`, `lr-desktop`, `lr-mobile`, `mixed-content`, `perf`) in [lighthouse-core/config](https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/config). **It's not clear from the documentation how these are meant to be referenced.** 

I had to dive into the source code to see how they were loaded ([lighthouse-core/config/config.js](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/config.js#L353)). It's now clear to me that only `lighthouse:default` and `lighthouse:full` are loaded in this way. All the other configs in that directory may just be there as examples.

Therefore, my understanding is that you either have to extend one of the two presets and add your own settings, audits etc. to it, or you create the full config from scratch. 

If you are using the CLI, you can import config from a file with the `--config-path` flag (as described [here](https://github.com/GoogleChrome/lighthouse/blob/master/docs/recipes/custom-audit/readme.md), which incidentially took me a while to find). You can reference those presets inside the Lighthouse repository directly or copy them into the your own repository. 

However, the documentation for the CLI also has a `preset` flag with a different set of options (`full`, `perf`, `mixed-content`). So now it's getting more confusing because I don't know what would happen if you used both `config-path` and `preset` flags together.

**Conclusion**
I think some improvements are needed regarding the documentation of the presets for both the Node API and the CLI. I'm happy to help, but I'd need some clarification first.

**Comment by patrickhulce** [comment]
Thanks for filing @gidztech! We would love some help clarifying the docs around this :)

> All the other configs in that directory may just be there as examples.

Yes, they are there because they are used in various environments and tests. They can also be used via `presets` but aren't meant to be extended because they are rather specific to their respective use cases.

> Therefore, my understanding is that you either have to extend one of the two presets and add your own settings, audits etc. to it, or you create the full config from scratch.

Correct!

> However, the documentation for the CLI also has a `preset` flag with a different set of options (`full`, `perf`, `mixed-content`) So now it's getting more confusing because I don't know what would happen if you used both `config-path` and `preset` flags together.

Any file in the config folder can be referenced as a preset instead of using `config-path`. If you specify a `config-path` preset will be ignored.

**Comment by gidztech** [comment]
Thanks for clarifying the details @patrickhulce . I'll look to do a PR to improve the documentation on this soon.
