### ISSUE TITLE
[Pagespeed insights] Pagespeed score is very inconsistent

### ISSUE THREAD

**Issue by snake-345** [GoogleChrome/lighthouse#7348]
Hello there.
I'm trying make our pagespeed score better. And first of all I decided improve our TTI(Time to Interactive) because it has more weight for score.

I looked to performance tab with parameters Fast 3G and 4x CPU slowdown in chrome tools and find some really long tasks. It was tasks which working 1s each. I fixed that tasks and check pagespeed score again and sometimes I could get result even worse.

Only when I run test 10 times and calculate average score I could see that score got better(but only for first fix). But I can't explain it to our clients who just run pagespeed once, got the worst result and wrote emails to us.

**Links:**
[Page with problems](https://snake-345.github.io/PSI-Testing/bundled)
[Page where I fixed one long task ~1s](https://snake-345.github.io/PSI-Testing/experimental-bundled)
[Page where I fixed second long task ~1s more](https://snake-345.github.io/PSI-Testing/experimental-bundled-without-carousels)

**Results of testing:**
![2019-02-28 12 37 29](https://user-images.githubusercontent.com/3379833/53560712-ad769700-3b55-11e9-936a-0bb643584829.png)

Current I just can't improve our results, because I can't test my fixes normally.
Any offers/ideas? Do you have any plans for fix it?

**Comment by patrickhulce** [comment]
Thanks for filing @snake-345! Do you see the same variability from the CLI or DevTools? Or primarily PSI?

Related #6708 and [variability docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md).

**Comment by snake-345** [comment]
@patrickhulce I tested Lighthouse from DevTools and results right here:
![2019-02-28 17 33 34](https://user-images.githubusercontent.com/3379833/53577917-2f2eea80-3b7f-11e9-85de-d19bb4514cd5.png)

It's really more consistent, but still have some anomalies. I singled out the worst anomaly on the screenshoot.

Lighthouse from DevTools can be helpful for speed optimization. But it useless when our clients can't see it, because for them matters only PageSpeed Insights score, and unfortunately this score is very inconsistent.

**Comment by ARTunchained** [comment]
Thanks for sharing, same issue here since January 2019. This is a very big deal for us as a small business.

**Comment by Limoncelo** [comment]
I am experiencing the same issues, my score can go from 80 on mobile one day, down to 45 the next day, without any changes on my part... The change is difficult to explain to our clients, and it's hard to figure out what does or doesn't make a difference. Thanks!

**Comment by brendankenny** [comment]
Let's close this in favor of the discussion in #6708
