### ISSUE TITLE
Live mode: Pause on violation

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#735]
Currently the LH workflow flow is: gather > audit > report.   Some users want the ability report audit violations as they happen. The flow becomes: continuous gatering/audting | report).

With https://github.com/GoogleChrome/lighthouse/commit/62d8d9660b6511348b00dc1d77b89a41bfb7f64b, we have the ability to report JS-based audit violations with a stacktrace after they happen. For certain violations, reporting violations has they happen can make things more actionable. Users can poke around the live page at the point something goes wrong.

Supporting a "live mode" where violations are caugh/reported as they happen might be a useful flag to add. I can see this being extremely useful for DBW. Such a "live mode" would likely only work for JS-based features.

Impl ideas:

The [Debugger](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Debugger/) and DOMDebugger would be good for this. We could implement a `--live-reporting` flag that pauses the debugger(s) on violations.

**Comment by paulirish** [comment]
Big +1 to this. 

The [DevTools Live Lint](https://docs.google.com/document/d/1ERpzMVdhEZF3JVv_cKk4t68AQeZOjC8eh4-NqRZyXyU/edit) feature idea was along these lines. Report proactively on things observed, rather than entering into a record-start-stop state.

Lighthouse is moving into DevTools frontend to replace the Audits panel. and that's a perfect scenario for live reporting of issues.

While yeah, we're somewhat limited in what's observable live, it's also entirely reasonable for us to add new methods to the protocol to facilitate more realtime observation. :)

**Comment by paulirish** [comment]
To clarify, I think we could break this apart into two separate features here:

-1. **Live listening.** Live-ish analysis of the page, where the user is not explicitly starting an analysis run. As long as the user is OK with us doing this, it allows us to message them with "hey, so I noticed some things...". 

With DevTools integration, it could look something like..

![image](https://cloud.githubusercontent.com/assets/39191/19051502/2066c516-8968-11e6-986f-98de936d2cee.png)

DOM elements, network requests, javascript expressions can be annotated with warnings:
![image](https://cloud.githubusercontent.com/assets/39191/19051405/d2334928-8967-11e6-93c9-dd3a019959d0.png)
![image](https://cloud.githubusercontent.com/assets/39191/19051463/fd671912-8967-11e6-8af1-cee4710358a7.png)
Alternatively, click on the warnings count to view all findings:
![image](https://cloud.githubusercontent.com/assets/39191/19051555/428cb664-8968-11e6-8636-2d7d4a2df099.png)

-2. **Pause on Violation.** A stronger mode of live listening where I want to pause execution at each violation so I can inspect everything. Makes a lot of sense for JavaScript centric problems. Others, like repaint-on-scroll might work better with a realtime log.

FWIW, I think these are also worthwhile without DevTools integration, so we need not consider that a dependency.

**Comment by mdittmer** [comment]
Live listening/reporting sounds really useful as an execution model for Lighthouse as it is today.

What would pause-on-violation look like without DevTools integration? Does the paused-in-debugger overlay appear when remote debuggers use the API to pause execution? How much can be gleaned from Lighthouse CLI if it pauses a script?

**Comment by paulirish** [comment]
yeah sorry. Pause on violation isn't entirely valuable without DevTools attached. The user will need a UI. :)

But yes the paused overlay can show up while another debugger is attached and pausing it (and it can even display a string saying who is pausing the page)

**Comment by paulirish** [comment]
Pause on violation is still a possibility, but that is a devtools feature, and would use violations reported from within blink. Should be reported on crbug.com
