### ISSUE TITLE
0 Accessebility

### ISSUE THREAD

**Issue by gasyoun** [GoogleChrome/lighthouse#7355]
https://www.deque.com/axe/ does not open. This site can’t be reached

#### Provide the steps to reproduce
1. Run LH on https://www.homeyou.com/

#### What is the current behavior?
0 Accessibility, even on such points that when checked manually are present.

#### What is the expected behavior?
At least 1 point.

![errorr](https://user-images.githubusercontent.com/80761/53647694-21489a80-3c4f-11e9-97c1-ec698fc9a7ee.PNG)

**Comment by patrickhulce** [comment]
Thanks I can repro, it's been filed upstream https://github.com/dequelabs/axe-core/issues/1397
