### ISSUE TITLE
DBW: `CSS.getStyleSheetText` does not accept valid `styleSheetId`s

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#736]
I'm attempting to write an audit for CSS `will-change` that collects stylesheets using `CSS.styleSheetAdded` events and reads their content using `CSS.getStyleSheetText. However, passing these styleSheetIds result in an error:

<img width="881" alt="screen shot 2016-10-01 at 9 16 53 am" src="https://cloud.githubusercontent.com/assets/238208/19054548/b091a6cc-8974-11e6-9d69-73f0746d3278.png">

Here's what I'm doing: 
https://github.com/GoogleChrome/lighthouse/commit/db5039219035b7f843598f3b4febcbeefddad96c#diff-99ebf6049dff383295940e4dc7b63754R63

To test:
1. checkout https://github.com/GoogleChrome/lighthouse/compare/willchange
2. run `npm run dbw https://www.chromestatus.com/features`

The console will output the `stylesheetId`s that were found and attempt to `getStyleSheetText` for each.

**Comment by paulirish** [comment]
@ashlushnikov Hmm.. can you help? anything stand out to you already?

**Comment by ebidel** [comment]
cc @aslushnikov

**Comment by aslushnikov** [comment]
If you listen to the styleSheetRemoved events as well, you'll be able to avoid querying for text of stylesheets which were removed.

For the rest of the stylesheets, the getStyleSheetText works just fine.

**Comment by ebidel** [comment]
Ah, so those sheets have been removed! Makes sense. The URLs I've been testing on use Polymer, which shims styles and moves them to the main document. That would explain the removals.

Not sure why I'm not seeing content for the other sheets. Possibly b/c one of the fetches is being rejected and the `Promise.all()` is rejecting in aggregate. 

Anyways, moving to a model where only the page's active sheets are fetched and removing the `Promise.all()` usage works. Getting content back now.

Thanks @aslushnikov and @paulirish
