### ISSUE TITLE
[feature] More granular API for report rendering

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/lighthouse#7372]
This feature request is to make it possible to do more with the LHR than just view the HTML output.

In particular, the web.dev project would like to be able to consume parts of the report. For example, we may want to show details on our measure page (https://web.dev/measure) specifically relating to failed audits-- extracting directly from the report. We'd also like to show details for a failed audit inside a specific guide for that audit.

**What is the motivation or use case for changing this?**

Currently, web.dev links off to the Lighthouse report for a URL measured from our measure page. It also parses the JSON for a Lighthouse run in unnecessarily complicated ways to be able to show a list of opportunities. It would be much more practical to be able to consume parts of the report on our measure page, rather than re-inventing the wheel.

**How is this beneficial to Lighthouse?**

Being able to re-use parts of a Lighthouse report is a great way to parse report information into manageable and relevant chunks, rather than all or nothing. This could be a very beneficial API for services that help developers monitor the health of their site over time, without getting information overload. It's also good practice, being able to extract information from the report-- without having to do unnecessarily complex stuff with JSON (regex'ing it like a string to get specific content).

Some use-cases:

* A developer runs Lighthouse on a URL, and off of that gets a list of failed audits. That list of failed audits is generated by calling the LHR API. When the developer clicks on the failed audit, the opportunities for that failed audit can be pulled into the advice on how to fix that failed audit, also by calling the LHR API.

* Lighthouse monitoring could be added to a site's Travis integration. When an audit fails over time, it could easily report details about that failed audit to developer, calling LHR API.

**Comment by brendankenny** [comment]
Hmm, is this asking to be able to generate subparts of the HTML report or to more easily access subparts of the output JSON? The JSON output format should be relatively stable and (hopefully) shouldn't require regexes to parse.

Maybe clarifying: we generally refer to the JSON output as the LHR and use "HTML report" for the viewable report.

**Comment by Meggin** [comment]
I'm talking about an API for the viewable report. One of the benefits of this, is you can render the report in pieces, rather than having to render the whole thing. 

Otherwise, you have to basically create your own 'renderer' from the JSON itself. It feels like an anti-pattern.

**Comment by Meggin** [comment]
Custom audits is another good reason for this API. Custom audit authors might want more granular control over report rendering for their audits. (Thanks, Paul Irish for better naming.)

**Comment by paulirish** [comment]
> A developer runs Lighthouse on a URL, and off of that gets a list of failed audits. That list of failed audits is generated by calling the LHR API. When the developer clicks on the failed audit, the opportunities for that failed audit can be pulled into the advice on how to fix that failed audit

TBH I think the current API of the report renderer mostly makes this pretty doable. Just need to know where to look.

e.g. here's how you can render just the render-blocking audit right now:

```js
// set up renderer.. (this bit could be easier, but it doesn't seem _too_ terrible)
const dom = new DOM(document);
const detailsRenderer = new DetailsRenderer(dom);
const perfCatRenderer = new PerformanceCategoryRenderer(dom, detailsRenderer);


// grab an individual audit from the LHR
const report = Util.prepareReportResult(__LIGHTHOUSE_JSON__);
const renderblockingAudit = report.categories.performance.auditRefs.find(ref => ref.id === "render-blocking-resources");


// render just this dude and add into the DOM.. 
const elem = perfCatRenderer._renderOpportunity(renderblockingAudit)
document.body.prepend(elem);
```

![image](https://user-images.githubusercontent.com/39191/53843049-14c98800-3f56-11e9-92ab-f979c4af5ba2.png)

So let's say this is already 85% doable already. :) 

The remaining 15% could be cleaning up the API, but we can hold off on that until the product requirements are very firm and well defined. ✌️

**Comment by Meggin** [comment]
Is there a design doc template that the team likes to follow?

**Comment by paulirish** [comment]
here's a few more examples for anyone interested in granular rendering of the report:


```js
// set up
const dom = new DOM(document);
const detailsRenderer = new DetailsRenderer(dom);
const catRenderer = new CategoryRenderer(dom, detailsRenderer);
const perfCatRenderer = new PerformanceCategoryRenderer(dom, detailsRenderer);
const pwaCatRenderer = new PwaCategoryRenderer(dom, detailsRenderer);
// __LIGHTHOUSE_JSON__ == the pagespeedApiResponse.lighthouseResult
const reportResult = Util.prepareReportResult(__LIGHTHOUSE_JSON__);

// 1) render a single perf opportunity
const renderblockingAudit = reportResult.categories.performance.auditRefs.find(ref => ref.id === "render-blocking-resources");
const rbelem = perfCatRenderer._renderOpportunity(renderblockingAudit)
document.body.prepend(rbelem);

// 2) render all best practices results
// TODO: use catRenderer._getClumpIdForAuditRef() to filter to just the failing results
const bpAudits = reportResult.categories['best-practices'].auditRefs;
for (const audit of bpAudits) document.body.prepend(catRenderer.renderAudit(audit))

// 3) render the PWA score gauge
const pwaCat = reportResult.reportCategories.find(cat => cat.id === 'pwa');
const elem = pwaCatRenderer.renderScoreGauge(pwaCat, reportResult.categoryGroups);
document.body.prepend(elem);
```

As you can see, there's methods for rendering most components individually. The source lives here: https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/report/html

You'll also have to include the `report-styles.css` and probably `setTemplateContext()` depending on how you include `templates.html` into the webapp.

**Comment by brendankenny** [comment]
I think we're going to go in a slightly different direction, looking to make it a bit easier/cleaner to embed report content as @paulirish outlined above.

Closing this issue in favor of work over in web.dev.
