### ISSUE TITLE
Extension Error: PAGE_HUNG

### ISSUE THREAD

**Issue by livehealth-Akshay** [GoogleChrome/lighthouse#7378]
**Lighthouse Version**: 4.0.0
**Lighthouse Commit**: bfa10f1ac4ba8cdf95c809858d8bc4c8ac1c1da8
**Chrome Version**: 72.0.3626.119
**Initial URL**: http://0.0.0.0:8000/providers/
**Error Message**: PAGE_HUNG
**Stack Trace**:
```
LHError: PAGE_HUNG
    at chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:19851:7
```

**Comment by patrickhulce** [comment]
Page hung means that the page has stopped responding. Try running again and ensuring there are no infinite loops in the site's code.
