### ISSUE TITLE
Lighthouse as trace processor or Lighthouse as listener

### ISSUE THREAD

**Issue by murali0286** [GoogleChrome/lighthouse#7380]
We are trying to reuse our functional test cases (Selenium or Nightwatch) to create Lighthouse reports for all the web pages our UI test cases traverses through. 

We are thinking of 3 approaches

1. Use Lighthouse as a trace processor and have our Functional test cases generate traces and dev tools logs [(Reference)](https://github.com/GoogleChrome/lighthouse/issues/422)
But, Going by this approach, we see only 5-6 reports coming up.
![image](https://user-images.githubusercontent.com/6481445/53799200-e05ac980-3f5f-11e9-9d9a-6ae677b1b9be.png)

![image](https://user-images.githubusercontent.com/6481445/53799230-efda1280-3f5f-11e9-85f6-bbc939b7dfb0.png)

2. We are thinking of a way to ask Lighthouse to listen on port 9222 and run my functional test cases in the same port so, Our Functional TCs operate on the same browser session where LH is listening and while the TCs is running, LH can capture the artifacts, dev tools, and Traces to generate reports at the end of each test. I am not sure if that is feasible. **Need your inputs here**.

3. Adding a listener to TCs so, at every page navigation, I capture the URL and pass it on to LH to relaunch the URL in the same browser session to get LH reports. But, not all flows are working out going by this approach especially when we have a URL that has one-time unique ids or pages that require cookies to be set already. 

Our idea is to seamlessly integrate LH into our functional test suite. Please share your thoughts on how we can try this.

**Comment by patrickhulce** [comment]
Lighthouse is still very focused on initial page loads (you've already bumped into some of the weirdness due to this fact).

> Use Lighthouse as a trace processor 

Basically only the performance metrics will work with this approach as you've discovered.

> We are thinking of a way to ask Lighthouse to listen on port 9222 and run my functional test cases in the same port

A pretty promising way to go about it, more discussion on this type of approach in #6813  #3837 #1418 

>  I capture the URL and pass it on to LH to relaunch the URL in the same browser session to get LH reports

You can reuse the same Chrome profile even if you don't reuse the same port to make sure cookies come through. If you're using other forms of storage you can `--disable-storage-reset`

**Comment by murali0286** [comment]
thanks, @patrickhulce.

**Comment by brendankenny** [comment]
Closing as everything looks good here. If not, please comment and we can reopen!
