### ISSUE TITLE
fs.readFileSync is not a function

### ISSUE THREAD

**Issue by Diferno** [GoogleChrome/lighthouse#7382]
Hi, I created a Vuejs project to load an URL and test it with lighthouse.

Just added an @click event to fire the method shown in the docs:
```const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');

function launchChromeAndRunLighthouse(url, opts, config = null) {
  return chromeLauncher.launch({chromeFlags: opts.chromeFlags}).then(chrome => {
    opts.port = chrome.port;
    return lighthouse(url, opts, config).then(results => {
      // use results.lhr for the JS-consumeable output
      // https://github.com/GoogleChrome/lighthouse/blob/master/types/lhr.d.ts
      // use results.report for the HTML/JSON/CSV output as a string
      // use results.artifacts for the trace/screenshots/other specific case you need (rarer)
      return chrome.kill().then(() => results.lhr)
    });
  });
}

const opts = {
  chromeFlags: ['--show-paint-rects']
};

// Usage:
launchChromeAndRunLighthouse('https://example.com', opts).then(results => {
  // Use results!
});
```
But when loading the vue app, the console.log shows 

![image](https://user-images.githubusercontent.com/710360/53802161-6a476a00-3f41-11e9-86e3-758a31053bc8.png)

Tryed installing fs and fs-extra, but with same result

Thx in advance!

#### Environment Information
* Lighthouse version: "^4.1.0",
* Vue: "^2.6.6"
* Operating System: Windows
* "fs-extra": "^7.0.1"

**Related issues**

**Comment by patrickhulce** [comment]
Lighthouse is a node module @Diferno, it needs to be run from the node-side, not within a browser. You'll want to setup some server with an endpoint that runs Lighthouse, use the PageSpeed Insights API, or build a Chrome extension if you want a web UI for getting Lighthouse results.
