### ISSUE TITLE
Protocol mismatch between devtools network pane and Lighthouse report

### ISSUE THREAD

**Issue by derekjohnson** [GoogleChrome/lighthouse#7383]
I ran a lighthouse audit on my personal site https://nostrongbeliefs.com/. Before running it I unregistered the service worker and cleared cache storage.

In the best practice section it said 2 resources were served over HTTP/1.1.
<img width="726" alt="screenshot 2019-03-05 at 11 52 13" src="https://user-images.githubusercontent.com/1506941/53804782-4df6fd80-3f40-11e9-9f14-5061f154f62f.png">

I checked in the network pane and they were both h2 there.
<img width="1196" alt="screenshot 2019-03-05 at 11 51 58" src="https://user-images.githubusercontent.com/1506941/53804820-649d5480-3f40-11e9-8ea1-60ebb4d6b0c7.png">
<img width="1196" alt="screenshot 2019-03-05 at 11 51 34" src="https://user-images.githubusercontent.com/1506941/53804850-7848bb00-3f40-11e9-967c-4e1c499a2617.png">

I realise this could be caused by different things, but after a chat on Slack (https://webperformance.slack.com/archives/C04BK7K1X/p1551786913040200 for those of you who are on the webperf slack) I'm asking here in case it is with lighthouse.

**Comment by patrickhulce** [comment]
Thanks for filing @derekjohnson!

Given the WPT timing relative to service worker and the fact it's a manifest I'm suspecting it's related to  #7158/#7197. In the screenshot you shared, did you have the "bypass for network" box checked in the service worker options? I see those two requests as being handled by a service worker on my end.

**Comment by derekjohnson** [comment]
Hey @patrickhulce :) 

The "bypass for network" was unchecked.

**Comment by paulirish** [comment]
[fixed in 4.3.0](https://github.com/GoogleChrome/lighthouse/blob/master/changelog.md#430-2019-04-08) by #7197

**Comment by paulirish** [comment]
@derekjohnson really well done btw: 
![image](https://user-images.githubusercontent.com/39191/56308392-3dc46780-6115-11e9-81f1-b0445b980d46.png)


super impressive.
