### ISSUE TITLE
DevTools Error: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by AshwinKheta** [GoogleChrome/lighthouse#7385]
**Initial URL**: https://www.google.com/sorry/index?continue=https://www.google.co.in/search%3Fq%3Ddifference%2Bcode%26oq%3Ddifference%2Bcode%26aqs%3Dchrome..69i57j0l5.25305j0j7%26sourceid%3Dchrome%26ie%3DUTF-8&q=EgRn5RseGK6I-uMFIhkA8aeDS02ZwCqdHbOYfL7d2d0MvFUoflaFMgFy
**Chrome Version**: 74.0.3717.0
**Error Message**: PROTOCOL_TIMEOUT
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT
    at eval (chrome-devtools://devtools/remote/serve_file/@e48a205ce06f6d1452398d1863108a3b4ca56909/audits2_worker/audits2_worker_module.js:1027:210)
```

**Comment by patrickhulce** [comment]
duplicate #6512
