### ISSUE TITLE
Target other browser vendors

### ISSUE THREAD

**Issue by mdittmer** [GoogleChrome/lighthouse#740]
It would be great if Lighthouse could be deployed against other browser. @paulirish pointed out that several other vendors implement some of Chrome's [remote debugging API](http://compatibility.remotedebug.org/). Dealing gracefully with gaps in the API when they're found would allow developers to use Lighthouse in more context, and possibly run interoperability-driven audits that wouldn't be possible deploying only to Chrome.

**Comment by paulirish** [comment]
Edge now supports a subset of the devtools protocol that enables some portion of LH to work. We'd be happy to see someone explore this.
