### ISSUE TITLE
Consider refactoring presets config into repo/package

### ISSUE THREAD

**Issue by gidztech** [GoogleChrome/lighthouse#7406]
**Summary**
Following a discussion with @brendankenny on configuring Lighthouse, I improved the docs a little recently around using and extending presets with the node module programmatically. (https://github.com/GoogleChrome/lighthouse/pull/7354)

You can currently extend a preset like so:

```js
{
    extends: 'lighthouse:default',
    settings: {
        emulatedFormFactor: 'desktop',
        ...
    },
}
```

The limitation is that you can only use `lighthouse:default` or `lighthouse:full` in this way. I clarified this limitation in the docs after I was unable to extend one of the other presets I found in the [`lighthouse-core/config`](https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/config) directory.

**Option 1:**
We could update the logic to allow you to extend any preset found in the [`lighthouse-core/config`](https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/config). However, the problem with that is you have to make sure the configs are named in a particular format to be picked up. It's also not very visible to the user about what presets are available. The fact I went looking in Lighthouse internals is a bit of a red flag here.

The other big issue for me is that we're basically re-inventing object composition. In JavaScript, we extend objects with `Object.assign` (or using spread operator), so it seems totally unnecessary to be building our own `extends` logic here.

So I'm not super keen on this personally.

**Option 2:**

What if we created a `lighthouse-presets` repository or at least a package that contains a number of useful preset configs that you can import into your own project?  `lighthouse-core` could also bring it in interally as a dependency so it's all managed in one place.

At that point, if a user wants to extend any of those presets, they can import one and do an object merge with their own config, rather than relying on the `extends` property. It seems like a much more natural way to me to do in my opinion.

```js
const lighthouse = require('lighthouse');
const desktopPreset = require('lighthouse-presets/desktop'); 

const myConfig = Object.assign({}, desktopPreset, {
    cpuSlowdownMultiplier: 5
});

await lighthouse(url, opts, myConfig);

```

I don't know how many presets we're likely to have, but with more and more settings being available, there's a chance we could see a lot more standard variations, and with a separate repository or package, there's more visibility of what's available. 

**Option 3:**

We don't think configs will scale and the current mechanism is good enough, provided we remain clear in the docs. This is still a perfectly valid option.

I'm happy to help around this.

**Comment by patrickhulce** [comment]
Thanks for filing for discussion @gidztech!

> Option 1

I think this is fairly promising. We'd just have to make sure we have stable names for `extends: 'lighthouse:blah'` and make them better documented.

> In JavaScript, we extend objects with Object.assign (or using spread operator), so it seems totally unnecessary to be building our own extends logic here.

There are a few more things going on with extension beyond `Object.assign` :) 

There are several levels of nested properties to merge, array concatenation, de-duping and merging of passes with the same name, etc. So....

> Option 2

I'm not a huge fan of this option. It's another repository to manage and keep in sync and the complexity of extending these yourself is easy to be overlooked (for reasons above).

> Option 3

This, of course, also works for me :) though I think I like the look of Option 1

**Comment by gidztech** [comment]
> Option 1 

> I think this is fairly promising. We'd just have to make sure we have stable names for extends: 'lighthouse:blah' and make them better documented.

It's a reasonable option, but the more implicit nature of the string form still gets to me a little. I have a natural inclination to do <kbd>Cmd</kbd> + <kbd>Click</kbd> on the base config to see what's in it. I can't because it's just a string, so I have to go into the repository internals to find out what I'm getting.

Perhaps, we could make `extends` take either a string or a `LH.Config.Json` type. If it's a string, look up the config as normal (including any in the directory). If the config object is passed in, use that as the base config and continue to merge that and the user's config internally.

For example, you can explicitly import your base config from the (internal) package :

```js
const desktopPreset = require('lighthouse/lighthouse-presets/desktop'); 

{
    extends: desktopPreset,
    settings: {
        cpuSlowdownMultiplier: 5
        ...
    },
}
```

> Option 2

> There are several levels of nested properties to merge, array concatenation, de-duping and merging of passes with the same name, etc. So....

Ah yes, I just saw the [deepCloneConfigJson](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/config.js#L284) function. I guess the exending logic could be exported as a `buildConfig` function that returns the final config. However, the user would need to know to import that, so it becames less convenient. Therefore, this option is probably not so viable.

> I'm not a huge fan of this option. It's another repository to manage and keep in sync

Sure. It could just be a package inside the main repository instead (like my updated Option 1 example above). Or just have a shortcut export to the configs directory.

**Comment by gidztech** [comment]
@patrickhulce Any thoughts on the above?

**Comment by patrickhulce** [comment]
> If it's a string, look up the config as normal (including any in the directory). If the config object is passed in, use that as the base config and continue to merge that and the user's config internally.

This sounds good to me! 

> Or just have a shortcut export to the configs directory.

This also works for me. I'm a big fan of export aliases 👍 

It seems like there are a few concrete steps then to make this happen:

- Add support for recursively extending configs. (Fairly difficult and complicated)
- Add support for extends to use any preset, not just `lighthouse:default`/`lighthouse:full`. (Relatively easy)
- Add support for accepting an object as the `extends` property. (Relatively easy)
- Add folder for aliasing and exporting the presets. (Relatively easy)

The recursive extension is definitely the hardest step in here. What are we going to do when multiple configs have `onlyAudits` for example, concat them or override? Lots to think through here for each property that we didn't have to worry about when it's just full configs that are being extended.

This step in particular seems like work that would require a decent amount of care in implementing, so I think it makes sense to validate this need is broad enough to prioritize before getting started.

Open call for +1s if you've needed this functionality before repo watchers :)

**Comment by brendankenny** [comment]
I'm definitely on board with

> Add support for extends to use any preset, not just lighthouse:default/lighthouse:full. (Relatively easy)

as well as adding support for any path for extension here (like [eslint](https://eslint.org/docs/user-guide/configuring#extending-configuration-files) and [tsconfig](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends), etc do with `extends`), or is that part of one of the other options?

> What are we going to do when multiple configs have `onlyAudits` for example, concat them or override? Lots to think through here for each property that we didn't have to worry about when it's just full configs that are being extended.

This is a really good point. I already ran into some logical but somewhat unexpected interactions from default config + extended config + plugin(s) while writing tests for plugins, and it's only going to get harder to understand what's happening as you get more layers of inheritance in there :)

**Comment by Hoten** [comment]
We could allow for both:

```
{
extends: "...",
collate: {
onlyAudits: "combine" | "replace"
},
settings: {onlyAudits: [...]}
}
```

**Comment by connorjclark** [comment]
We're open to making the config more extensible, but probably not gonna put these files in a separate repo. (`extends` implies more than is possible atm)
