### ISSUE TITLE
Lighthouse: drop-in script for browser

### ISSUE THREAD

**Issue by mdittmer** [GoogleChrome/lighthouse#741]
Somewhat related to #740, it would be great if Lighthouse understood how to package itself up for use as a library (reports to the console, maybe? Rest API? ...). This would be useful for browsers that don't support Chrome's [remote debugging API](http://compatibility.remotedebug.org/), and for developers interested in doing interoperability audits through automation such as BrowserStack + Selenium.

**Comment by brendankenny** [comment]
>  would be great if Lighthouse understood how to package itself up for use as a library

To clarify somewhat (my first thought was that it does work as a library :), you mean as a library for the browser that can be included as a script in a page and give a report on that page?

**Comment by mdittmer** [comment]
Yes. That's my meaning.

**Comment by wardpeet** [comment]
We have an extension, don't really see why you want to include it in  a script?

**Comment by mdittmer** [comment]
This would be useful for deploying in browsers other than Chrome.

**Comment by wardpeet** [comment]
Correct but currently we are heavily depended on the chrome driver/devtools.
Not sure if other browsers have the same info for grabs.

**Comment by brendankenny** [comment]
@wardpeet this would be for the subset of audits that would work purely in-browser, without the debugging protocol. E.g. @ebidel's recent audits looking just for usage of outdated or bad API use. 

An example might be, I'm on a development team for some site and add a library that uses `document.write` to our site. Maybe Lighthouse on our CI server would catch that, but it could be helpful that our development server has the in-browser version that immediately alerts me (via #716) to what I've done.

**Comment by ebidel** [comment]
ATM though, the DoBetterWeb audits do heavily depend on the DevTools protocol to return results.

**Comment by brendankenny** [comment]
yes, not saying it would be trivial, just saying that in theory those audits could in theory run purely in the browser :) I think your point gets to what @mdittmer was suggesting on separating "triggers" from how they're tested (the audits). Not sure how far down that path we need to go...we could also investigate some clever `driver.js` shimming

**Comment by wardpeet** [comment]
@brendankenny what if we tweak the extension so it can run in watch mode or whatever?

**Comment by patrickhulce** [comment]
not exploring this right now, thanks
