### ISSUE TITLE
Low performance score

### ISSUE THREAD

**Issue by Mridul-GIT** [GoogleChrome/lighthouse#7411]
Google lighthouse suggesting to make all non-critical JS as async to improve the performance score. I have added asycn to all JS. The score was really promising however my page rendering is failing in mobile devices. Is there any way to handle async solution without hampering page rendering?

**Comment by patrickhulce** [comment]
You are correct your code needs to be able to handle asynchronous scripts before marking as `async`. The answer on how to do that is highly specific to your setup though. I'd recommend [reading up](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/adding-interactivity-with-javascript#parser_blocking_versus_asynchronous_javascript) on what it means to apply [async or defer](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/#use_async_or_defer) to scripts and try asking for more specific help on StackOverflow.
