### ISSUE TITLE
Extension Error: NO_FCP

### ISSUE THREAD

**Issue by lrmmoreira** [GoogleChrome/lighthouse#7415]
**Lighthouse Version**: 4.2.0
**Lighthouse Commit**: 35b285b87d681905777ed2545e48292312910485
**Chrome Version**: 72.0.3626.121
**Initial URL**: http://www.ianaalimentos.com.br/site/
**Error Message**: NO_FCP
**Stack Trace**:
```
LHError: NO_FCP
    at setTimeout (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:21525:8)
```

**Comment by patrickhulce** [comment]
Thanks for filing! This page seems to take too long to paint content, and Lighthouse gives up on waiting. If you need to change this behavior, you can run Lighthouse from the command line with a custom config modifying `maxWaitForFcp`.
