### ISSUE TITLE
DevTools Error: The asynchronous expression exceeded the allotted time of 60

### ISSUE THREAD

**Issue by Brianenr** [GoogleChrome/lighthouse#7419]
**Initial URL**: https://raw.githubusercontent.com/Microsoft/nodejstools/1bb20aa7ed8b8ace307825ed7072ea54fb7ff40d/Nodejs/Tests/TestData/NpmSearchData/npmsearchfullcat_npm143.txt
**Chrome Version**: 72.0.3626.121
**Error Message**: The asynchronous expression exceeded the allotted time of 60s
**Stack Trace**:
```
Error: The asynchronous expression exceeded the allotted time of 60s
    at _ (chrome-devtools://devtools/remote/serve_file/@da3787ba355f18db7db52abf75c42afb408d656f/audits2_worker/audits2_worker_module.js:1034:120)
```

**Comment by patrickhulce** [comment]
Lighthouse should only be run on webpages, not text files @Brianenr. Were you trying to run an audit on a URL other than https://raw.githubusercontent.com/Microsoft/nodejstools/1bb20aa7ed8b8ace307825ed7072ea54fb7ff40d/Nodejs/Tests/TestData/NpmSearchData/npmsearchfullcat_npm143.txt?
