### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by lyricslover** [GoogleChrome/lighthouse#7423]
**Lighthouse Version**: 4.2.0
**Lighthouse Commit**: 35b285b87d681905777ed2545e48292312910485
**Chrome Version**: 72.0.3626.121
**Initial URL**: https://lyricslover.org/angreji-gaalan-lyrics-armaan-bedil-surinder-shinda-2019/
**Error Message**: PROTOCOL_TIMEOUT
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT
    at setTimeout (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:21240:11)
```

**Comment by patrickhulce** [comment]
duplicate #6512
