### ISSUE TITLE
Read cookies

### ISSUE THREAD

**Issue by rudiedirkx** [GoogleChrome/lighthouse#7434]
Since Lighthouse is on the target page for a while, collecting all kinds of statistics, it could also collect the page's cookies. Might be interesting to know. Maybe as part of the Performance category. Even if it doesn't factor into the score.

I haven't seen the lighthouse code yet, but I'll try a PR.

**Comment by patrickhulce** [comment]
Thanks for filing @rudiedirkx! Before working on a PR, mind filling out the [new audit questions](https://github.com/GoogleChrome/lighthouse/blob/master/docs/new-audits.md#process-for-creating-a-new-audit)?

**Comment by rudiedirkx** [comment]
Oof. I have not thought about implementation at all. I did come across custom gatherers and audits, so I'll look into that first. If I can make it as a separate package, I can answer those questions.

**Comment by brendankenny** [comment]
Going to close this as no one has moved on it. If you end up developing some new audit ideas, definitely open a proposal for them!
