### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by rizaldy899** [GoogleChrome/lighthouse#7436]
**Lighthouse Version**: 4.2.0
**Lighthouse Commit**: 35b285b87d681905777ed2545e48292312910485
**Chrome Version**: 75.0.3730.0
**Initial URL**: https://www.akhirnp.online/
**Error Message**: PROTOCOL_TIMEOUT
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT
    at chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:21240:11
```

**Comment by patrickhulce** [comment]
duplicate #6512
