### ISSUE TITLE
rel="noopener" audit should ignore links to subdomain

### ISSUE THREAD

**Issue by jfbrennan** [GoogleChrome/lighthouse#7445]
In the Best Practices audit, you get dinged for missing `rel="noopener"` on links to your own subdomains. Looks like `reexternal-anchors-use-rel-noopener.js` is where this is done. Should links to subdomains really require noopener? If so, please explain. If not, please modify the audit.

Even google's own home page get's dinged for this:

<img width="721" alt="Screen Shot 2019-03-10 at 11 02 22 PM" src="https://user-images.githubusercontent.com/1817868/54103157-9bcc9500-4388-11e9-897d-95f859e41f66.png">

**Comment by patrickhulce** [comment]
Yes they should. Please refer to our [documentation](https://developers.google.com/web/tools/lighthouse/audits/noopener). It is not only a security concern but [a performance concern](https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/) as well.

In fact if anything, I think auditing only cross-origin links is too lenient as the same performance concerns apply to same-origin links. 
http://noopener-demo.surge.sh/

**Comment by brendankenny** [comment]
On the security side there's no reason to assume that a page on a subdomain is controlled by the same folks controlling the domain (they're commonly used for completely different sites, e.g. the default for hosted wordpress sites is to use subdomains of `wordpress.com`).

**Comment by jfbrennan** [comment]
Didn't know about the perf benefits of noopener. Thanks
