### ISSUE TITLE
Modules requires the defer tag to avoid warnings

### ISSUE THREAD

**Issue by christofferartmannmrf** [GoogleChrome/lighthouse#7448]
#### Provide the steps to reproduce
Add a script tag with the type `module`.

**Example**
https://github.com/christofferartmannmrf/lighthouse-defer-example

#### What is the current behavior?

Lighthouse audits gives an error that script that's loaded as a module is being loaded with high priority if the defer attribute is not present.

![screen shot 2019-03-08 at 18 52 00](https://user-images.githubusercontent.com/42038074/54109090-f47a4d00-43dd-11e9-9e9e-0d6c7c17eb14.png)

#### What is the expected behavior?

When a script tag is of the type module it's loading is defered implicity and the defer attribute should not be needed.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
https://developers.google.com/web/fundamentals/primers/modules

**Comment by patrickhulce** [comment]
Thanks for filing @christofferartmannmrf!

Apologies for the confusion, "deferring" here is referring to the general concept of loading later in page load, not necessarily using the `defer` attribute. 

The audit is accurate from the Chrome-perspective that modules are loaded with a "High" network priority and will be prioritized over other resources. 
![image](https://user-images.githubusercontent.com/2301202/54133403-06f78500-43e4-11e9-8b2b-3e203977e973.png)

Note that data showing up in the Diagnostics section is not intended to be "an error" (though it looks like the other audits had a Lighthouse runtime "Error!", maybe a separate bug report is necessary if we don't already have one for your error message?). 

It's perfectly valid to load a module with a high priority and the help text is suggesting reducing the length of the chains and total download size of the resources. In this case, the length of the chain and the total download size of the resources is small, so no action necessary.

**Comment by christofferartmannmrf** [comment]
Thanks for taking the time to reply :)
