### ISSUE TITLE
Remove automatic bug reporting

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#7457]
As discussed in chat, we think the automatic bug reporting is too noisy. So it's time to remove the easy link to file a new issue.

Motivated users will still come to the repo and search/file with us.

This applies to both DevTools and the Extension.

**Comment by paulirish** [comment]
Here's what I have staged in https://chromium-review.googlesource.com/c/chromium/src/+/1515275

![image](https://user-images.githubusercontent.com/39191/54137117-45884200-43da-11e9-8533-be19310d2a22.png)

**Comment by brendankenny** [comment]
looks good to me.

We should make sure to get the error `friendlyMessage` on screen (especially for `PROTOCOL_TIMEOUT`) so it's clearer what failed. We don't do that in the current auto reports from devtools or the extension.

**Comment by paulirish** [comment]
The new devtools bug reporting experience is landed on 75 and merged back to 74.  
74 is supposed to ship around April 23, so just under 4 weeks from now. \o/

**Comment by brendankenny** [comment]
Fixed on the extension side in #8294, will be going out with 4.3.1 when #8750 is good to go.
