### ISSUE TITLE
Report PWA results in terms of Initial/Baseline/Showcase definition sets

### ISSUE THREAD

**Issue by jmadler** [GoogleChrome/lighthouse#746]

**Comment by brendankenny** [comment]
is there a description of these levels we can include here?

**Comment by addyosmani** [comment]
The public version of these levels was included in the [what exactly makes a PWA](https://infrequently.org/2016/09/what-exactly-makes-something-a-progressive-web-app/) doc by @slightlyoff IIRC.

**Comment by addyosmani** [comment]
@jmadler When you say adjust to match the definition sets, are you referring to better representing these levels in the final report?

**Comment by addyosmani** [comment]
Owen has since published a checklist breakdown here: https://developers.google.com/web/progressive-web-apps/checklist

**Comment by hemanth** [comment]
Nice, I am happy to contribute to this idea and would also amend https://www.npmjs.com/package/is-pwa to a more meaningful cli app 🤘

**Comment by ebidel** [comment]
https://github.com/GoogleChrome/lighthouse/pull/2032 adds a iPWA boolean that also annotates the report to stay if the PWA sections meetings the "Baseline" Requirements. 

We have no plans to check for the exemplar and showcase checks. Many of them are manual. We can revisit that later on if the needs arises.
