### ISSUE TITLE
Add concurrent user requests

### ISSUE THREAD

**Issue by TarunKDas2k18** [GoogleChrome/lighthouse#7479]
**Feature request summary**
I would like to run tests via node js in such a manner that for example i can get the audit report when 1000 users visit a website concurrently. Of course, website will be hosted on a serverless environment like Akamai cloud

Yes

**What is the motivation or use case for changing this?**
My organisation have this requirement

**How is this beneficial to Lighthouse?**
Most of the companies who purchases off the shelf software will come to Lighthouse to have this

**Comment by paulirish** [comment]
@TarunKDas2k18 We're having a hard time understanding what you're asking for.

Lighthouse is a tool for evaluating the quality of a given web page.

It's unrelated to actual user traffic or user load of a site.
If you want a load testing product, Lighthouse isn't it. :)

**Comment by patrickhulce** [comment]
@TarunKDas2k18 sounds like you're looking for [ab](https://httpd.apache.org/docs/2.4/programs/ab.html) or [siege](https://linux.die.net/man/1/siege)

**Comment by Hoten** [comment]
I like https://github.com/mcollina/autocannon for this sort of thing.
