### ISSUE TITLE
display: browser; on manifest.json gives failure on LightHouse report

### ISSUE THREAD

**Issue by FrontEndStudio** [GoogleChrome/lighthouse#7485]
#### Provide the steps to reproduce
1. Run LH [x] Progressive Web App on: https://avbadhoevedorp.nl

#### What is the current behavior?

* User will not be prompted to Install the Web App
Failures: Manifest's `display` value is not one of: minimal-ui | fullscreen | standalone, Site does not register a service worker.

#### What is the expected behavior?

No failure on display: browser.

According to the web-app-manifest display documentation valid parameters for display are:
fullscreen | standalone | minimal-ui | browser

See reference page: https://developers.google.com/web/fundamentals/web-app-manifest/#display

#### Environment Information

Google Lighthouse from the Chrome developer toolbar (Version 70.0.3538.110 (Official Build) (64-bit))

**Comment by paulirish** [comment]
display:browser doesn't provide the user with a PWA experience. minimal-ui
is somewhat similar and our recommendation if you want the URL bar, etc.

**Comment by brendankenny** [comment]
See old discussion in #495
