### ISSUE TITLE
Image reports incorrect aspect ratio when using background-size: cover

### ISSUE THREAD

**Issue by nightpool** [GoogleChrome/lighthouse#7487]
#### Provide the steps to reproduce
1. Run LH on https://brash-mall.glitch.me/

#### What is the current behavior?

https://googlechrome.github.io/lighthouse/viewer/?gist=be9ae189af3e81cfbdca5a117d0c0f18

> Displays images with incorrect aspect ratio
> Image display dimensions should match natural aspect ratio.
> 
> | URL | Aspect Ratio (Displayed) | Aspect Ratio (Actual)
> | -- | -- | --
> | /500/500(placekitten.com) | 105 x 60 (1.75) | 500 x 500 (1.00)

#### What is the expected behavior?

Lighthouse ignores images that use background-size: cover to crop.

#### Environment Information
* Affected Channels: Tested with Lighthouse CLI
* Lighthouse version: 4.2.0
* Node.js version: v11.11.0
* Operating System: Mac OS High Sierra 10.13.6 (17G4015)

**Comment by patrickhulce** [comment]
Thanks for filing @nightpool! We filter out `<img>` elements that use `object-fit` but we're missing the condition for CSS images. Would be a good first issue to tackle, if you're so inclined :)

https://github.com/GoogleChrome/lighthouse/blob/bec96a6630998ce9d442a852fe0a0d2f13c6f437/lighthouse-core/gather/gatherers/image-elements.js#L52-L57

https://github.com/GoogleChrome/lighthouse/blob/bec96a6630998ce9d442a852fe0a0d2f13c6f437/lighthouse-core/gather/gatherers/image-elements.js#L92-L95

**Comment by Abdulmanahtalib** [comment]
Support

**Comment by Abdulmanahtalib** [comment]
Mute the thread
