### ISSUE TITLE
Setup instructions unclear on VM at CLI

### ISSUE THREAD

**Issue by cliveb** [GoogleChrome/lighthouse#750]
Using a Chomebook at #pwaroadshow. I spun up a GCE Debian VM and installed NPM and Node 6.7 with ES6 for Lighthouse at CLI. Thereafter Lighhouse help / git setup instructions are unclear. Do I need to install Chromium or Chrome? What do I need to add to my path to run Lighthouse? 

clive_boulton@instance-1:~$ lighthouse https://gdgseattle.org
Launching Chrome...
created /tmp/lighthouse.31Kn2kD
Runtime error encountered: Error: The environment variable LIGHTHOUSE_CHROMIUM_PATH must be set to executable of a build of Chromium v
ersion 52.0 or later.
    at Object.linux (/usr/lib/node_modules/lighthouse/lighthouse-cli/chrome-finder.js:62:11)
    at Promise.resolve.then (/usr/lib/node_modules/lighthouse/lighthouse-cli/chrome-launcher.js:91:61)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Error: The environment variable LIGHTHOUSE_CHROMIUM_PATH must be set to executable of a build of Chromium version 52.0 or later.
    at Object.linux (/usr/lib/node_modules/lighthouse/lighthouse-cli/chrome-finder.js:62:11)
    at Promise.resolve.then (/usr/lib/node_modules/lighthouse/lighthouse-cli/chrome-launcher.js:91:61)
    at process._tickCallback (internal/process/next_tick.js:103:7)
clive_boulton@instance-1:~$ 
- Try to install Chromium \* 

clive_boulton@instance-1:~$ sudo apt-get install chromium chromium
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Package chromium is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  chromium-bsu:i386 chromium-bsu
E: Package 'chromium' has no installation candidate
E: Package 'chromium' has no installation candidate
clive_boulton@instance-1:~$

**Comment by brendankenny** [comment]
Hi Clive! Looks like we do need to cover that in the readme.

- The first step is to make sure Chrome or Chromium (doesn't matter which) of at least version 52 can be run on that machine.

   For testing Lighthouse, we actually avoid dealing with a package manager and just download a recent snapshot build directly from https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots (note that, as a snapshot build, it'll be even less tested than Canary, but we've used it in our CI tests and haven't really had a problem for months). That may make sense for your use case too, if you're just going to be running this on an ephemeral VM instance.

- Then, as the error message says, `LIGHTHOUSE_CHROMIUM_PATH` should be set to the chromium executable path.

At that point, it should work. Here's the relevant part of our travis.yml file that drives this: [.travis.yml](https://github.com/GoogleChrome/lighthouse/blob/3dd1caca56f2edc74ab638378920a0f36b5ccc17/.travis.yml#L16-L19)

**Comment by cliveb** [comment]
Thank you. I am trying to pioneer for college students and others how to use Chromebooks for full stack web dev ($200 CB vs $1200 Mac) hence the  ephemeral VM instance and my use case. I will try with your doco.

**Comment by wardpeet** [comment]
@cliveb anyluck?

**Comment by cliveb** [comment]
@wardpeet Slipped my attention. I'll try this week. A coda http://diginomica.com/2016/11/02/as-new-machines-from-apple-microsoft-eschew-mainstream-business-users-its-time-to-revisit-virtual-desktops/#comments

**Comment by paulirish** [comment]
cool. holler with a new ticket if you have more questions! :)
