### ISSUE TITLE
PWA Scoring

### ISSUE THREAD

**Issue by harringtonp** [GoogleChrome/lighthouse#7504]
I believe the time to interactive in PWAs is not always represented correctly. Please see

https://stackoverflow.com/questions/55141228/lighthouse-scoring-for-progressive-web-app

for an example and full details

**Comment by patrickhulce** [comment]
Which version is deployed there now? Everything seems fine at the moment.

![image](https://user-images.githubusercontent.com/2301202/54360814-afe7ef00-4633-11e9-8aa0-893891ab4dd5.png)


Note it's definitely discouraged to ask for permissions on load though without any user context for what it's going to be used for. Fixing this might also fix the PWA issue as a byproduct.

**Comment by harringtonp** [comment]
The issue is still there, I just scored a 73 with 19 seconds to interactive which is too long to meet banner install requirements. 

What's happening I think Patrick is that you are in a region where there are no feeds so a location based download is not occurring on startup.

**Comment by harringtonp** [comment]
PS.  I realize asking for location permissions on load is discouraged and understand why. I had changed the code to only look when the "Locate the Nearest Stops" button was pressed. This was slow as only then does the browser try to determine location and download the feed and i suspect I may have lost some users as a result. As a result I switched back. 

This webapp like most transit apps is location based and I suspect most users will know as soon as they enter the site why their location is being asked for.

**Comment by paulirish** [comment]
> PS. I realize asking for location permissions on load is discouraged and understand why. .....
> 
> This webapp like most transit apps is location based and I suspect most users will know as soon as they enter the site why their location is being asked for.


https://github.com/GoogleChrome/lighthouse/issues/3836 tracks support for auto-allowing location permission while auditing


as far as the "Background download" mentioned in SO, we allow up to 2 network requests to be happening while we find the TTI. So we'll only push out TTI to be later if you have >= 3 network requests.  So with just 1 background network request, TTI shouldn't be affected.
