### ISSUE TITLE
Integrating LH reference docs into reports

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#755]
I've got pretty much all of the reference docs finished for the Lighthouse audits. They're living at /web/tools/lighthouse/audits.

I'd like to start discussing how to add them into reports. I don't mind working on this myself, as a means to get some practice in learning the LH source.

For context, the idea is that each of the audits link off to these docs to provide a well-lit path for solving failing audits.

I saw @ebidel's PR to add a help icon next to the audits in the Chrome Extension version. Clicking on the icon reveals additional help text for that audit. Maybe we can piggy back off that?
- If the audit contains a dedicated reference doc, link off to that.
- Else, show the inlined help text.

In terms of how LH references the docs, I was thinking of adding a field to the `meta` function in the audit files:

```
static get meta() {
  return {
    category: 'Accessibility',
    name: 'aria-allowed-attr',
    description: 'Element aria-* roles are valid',
    requiredArtifacts: ['Accessibility'],
    doc: 'https://developers.google.com/web/tools/lighthouse/audits/aria-allowed-attr'
  };
}
```

And then I'll figure out how to pipe this info through the reports.

Sound OK?

**Comment by brendankenny** [comment]
@ebidel might have been thinking about this with https://github.com/GoogleChrome/lighthouse/issues/706

**Comment by patrickhulce** [comment]
accomplished with markdown
