### ISSUE TITLE
PWA: draggable atribute not works

### ISSUE THREAD

**Issue by pyummm** [GoogleChrome/lighthouse#7554]
#### Provide the steps to reproduce
1. Run LH on <affected url>

#### What is the current behavior?
PWA application not allow native html5 drag and drop feature.
If at app page put element with draggable="true" atribute, in chrome browser mode, it will be draggable, at application mode drag stucks at first moment of ghost movement

#### What is the expected behavior?
probably PWA site version of site have maintain native html5 drag and drop feature same as browser site version

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:
MacOS 10.14.4

**Related issues**

**Comment by patrickhulce** [comment]
Hey @pyummm thanks for filing, but this is the repository for bugs in Lighthouse, the auditing tool in Chrome, not general web development. I'd suggest trying StackOverflow.
