### ISSUE TITLE
report generated from Lighthouse command line does not contain user timing marks and measures

### ISSUE THREAD

**Issue by greengalaxy2016** [GoogleChrome/lighthouse#7565]
Lighthouse version: 4.2.0
NPM version: 6.4.1
Node version: 10.13.0
NG version: 6.2.8

#### Provide the steps to reproduce
1. run lighthouse from command line to generate performance report on http://localhost:4200/boc-operations/edit/15001900007
` lighthouse http://localhost:4200/boc-operations/edit/15001900007 --port 59020 --output json --output-path=perf-moi-list.json --preset=perf --view --throttling-method provided --disable-storage-reset true --emulated-form-factor desktop --max-wait-for-load 5000`

#### What is the current behavior?
in the generated report, user timing marks and measures in my applications are missing. However, the report generated from running Lighthouse in Chrome DevTools contains the marks and measures. 
#### What is the expected behavior?
I have following code in my component
`window.performance.mark('product-list-init')`
the report should contain the user timing item such as: 
` {
            "name": "product-list-init",
            "startTime": 578.116,
            "timingType": "Mark"
          }
`

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 4.2.0
* Node.js version: 10.13.0
* Operating System: Windows 10

**Comment by patrickhulce** [comment]
Thanks for filing @greengalaxy2016! Do you have this page available on a public URL somewhere we can see? We have trouble following repro step `1`/auditing your localhost ;)

**Comment by greengalaxy2016** [comment]
@patrickhulce I don't have the public URL for this project. I will try to create a public project on GitHub so that you can download.

**Comment by greengalaxy2016** [comment]
@patrickhulce I updated the two reports generated via CLI and DevTools so that you can see the difference under "user timings" section. simply remove the .TXT extension and you can open them in Lighthouse Report Viewer. 

[perf-report-via-cli.json.txt](https://github.com/GoogleChrome/lighthouse/files/2980761/perf-report-via-cli.json.txt)
[perf-report-via-devtools.json.txt](https://github.com/GoogleChrome/lighthouse/files/2980762/perf-report-via-devtools.json.txt)

**Comment by patrickhulce** [comment]
Thanks @greengalaxy2016 for the reports, but those are generated after the part we would need to investigate. 

Right now it just sounds like the CLI is just auditing the login page instead of the actual application that has the timing marks. Are you sure you are successfully logging in from the CLI before you run Lighthouse and that the report is actually of the logged in page that produces the timings?

**Comment by greengalaxy2016** [comment]
@patrickhulce from the rendering path of the report, I am sure the report is NOT on the login page, but on the specified page. I can also see when lighthouse is running, it does log in and navigate to the specified page.

**Comment by patrickhulce** [comment]
Glad you figured it out! `max-wait-for-load` at `5000` is *very* short. It means "hey lighthouse, it doesn't matter if the page looks like it still needs to load, give up after 5s of waiting and start auditing anyway".

It sounds like this is the total opposite of what you want, so I'm not sure what prompted that argument but you should definitely make that number larger. If you want to wait even longer, then you can create a custom config and in the `defaultPass` set the `pauseAfterLoadMs` to some high number such that you are sure the page is done loading.
