### ISSUE TITLE
DBW: report on deopt

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#757]
V8 has a flags for this we might be able to utilize:

https://github.com/thlorenz/v8-flags/blob/master/flags-0.11.md#trap_on_deopt-false-boolean
https://github.com/thlorenz/v8-flags/blob/master/flags-0.11.md#trap_on_stub_deopt-false-boolean

This starts to get in the territory of DevTools though. May want to avoid.

**Comment by paulirish** [comment]
turbofan doesn't deopt anymore.
