### ISSUE TITLE
Lighthouse reports a 31 day expiry for files that expire in 1 year

### ISSUE THREAD

**Issue by PodClay** [GoogleChrome/lighthouse#7586]
We ran an audit on the following site...
https://www.timberfy.com.au/

Under "Serve static assets with an efficient cache policy" reported jpg and jpeg files as having a Cache TTL expiry of 31d.

However when I check the Response Headers for these files I find the "expires" is set to: Thu, 19 Mar 2020 01:25:37 GMT

Which matches the caching policy set...
  ExpiresByType image/jpg "access 1 year"
  ExpiresByType image/jpeg "access 1 year"

Is there something I am missing here?

Thanks,
Clay

**Comment by patrickhulce** [comment]
The expires header is a year but `cache-control` takes precedence when it's set and the max-age there is 31 days. 

`cache-control: max-age=2678400, public`

From the [spec](https://tools.ietf.org/html/rfc7234#section-5.3)...

> If a response includes a Cache-Control field with the max-age
   directive (Section 5.2.2.8), a recipient MUST ignore the Expires
   field.
