### ISSUE TITLE
User timing marks show negative numbers (1.1.5)

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#762]
<img width="440" alt="screen shot 2016-10-10 at 6 12 42 pm" src="https://cloud.githubusercontent.com/assets/238208/19255660/27e874c6-8f15-11e6-9e6c-1a9407a64d14.png">

Running the extension on: https://www.chromestatus.com/features

**Comment by ebidel** [comment]
Still seeing this in 1.1.7

**Comment by XhmikosR** [comment]
This still happens with 1.4.1. Note that the CLI doesn't have this issue.
