### ISSUE TITLE
If all audits in a category are `not applicable` the category should be marked `not applicable`

### ISSUE THREAD

**Issue by jburger424** [GoogleChrome/lighthouse#7623]
**Feature request summary**
Currently, if n - 1 audits in a category are marked `not applicable`, the category score is based on the one applicable audit. If n audits are marked `not applicable` then the category has a score of 0. This feels like the wrong behavior to me, as the site is not necessarily doing anything incorrectly.

One option could be to set a category score as 100 if no audits are applicable, but this also feels wrong as the website is not necessarily doing anything correctly either in this case.

I propose that in this situation we simply display 'N/A' as the category score with a grey circle.

I'd be happy to implement this myself.

**What is the motivation or use case for changing this?**
While I'm unaware of any cases where this would happen with current core categories, I think it is very applicable to plugins. This would specifically be true in the case of mistakenly scanning a site using a plugin for a specific technology, when that technology is not being used on the site.

CC: @brendankenny

**Comment by patrickhulce** [comment]
Oh yeah great point @jburger424! 👍 I agree "N/A" seems like a good solution here.

**Comment by brendankenny** [comment]
> One option could be to set a category score as 100 if no audits are applicable, but this also feels wrong as the website is not necessarily doing anything correctly either in this case.

But they also didn't do anything wrong :)

But, agreed, it's weird to not count notApplicable audits in the score until the last one (and we don't want to count the earlier notApplicable audits either), so SGTM!

> I propose that in this situation we simply display 'N/A' as the category score with a grey circle.

my main concern is i18n. I'm not sure how well we can get this to translate, or if we need to think of another way to express this. Greyed out sounds good, though (and I believe fits into our UI harmonization effort).

@hwikyounglee @yuinchien

**Comment by jburger424** [comment]
> > I propose that in this situation we simply display 'N/A' as the category score with a grey circle.
> 
> my main concern is i18n. I'm not sure how well we can get this to translate, or if we need to think of another way (symbol?) to express this. Greyed out sounds good, though (and I believe fits into our UI harmonization effort).

Good point about i18n. Perhaps it's best to do "—" instead of N/A, in a style that matches the existing "Not Applicable" icon.
![w8NK8XN5Dth](https://user-images.githubusercontent.com/3991915/54948296-afdcce80-4f12-11e9-8b4d-033bf195f732.png)

**Comment by exterkamp** [comment]
We have a consensus on the design https://github.com/GoogleChrome/lighthouse/issues/9803#issuecomment-540771705

@jburger424 do you want to take this on?

**Comment by saavan-google-intern** [comment]
Hi, is this issue still open to be worked on?

**Comment by jburger424** [comment]
> Hi, is this issue still open to be worked on?

@saavan-google-intern Yes, this is still open (@exterkamp to confirm this is still worth implementing). I was still planning to take this on at some point, but happy to pass the issue if you wanted to take it over as it isn't something I'll be able to do right now.

**Comment by connorjclark** [comment]
@saavan-google-intern feel free to grab this, thanks!

**Comment by saavan-google-intern** [comment]
@jburger424 thanks! I'll try it out.

**Comment by jburger424** [comment]
@connorjclark Looks like this was resolved with https://github.com/GoogleChrome/lighthouse/pull/11024?

**Comment by jburger424** [comment]
Resolved in https://github.com/GoogleChrome/lighthouse/pull/11024
