### ISSUE TITLE
Displays images with incorrect aspect ratio - BUG

### ISSUE THREAD

**Issue by davidlower** [GoogleChrome/lighthouse#7643]
Hi,

I have a background image I am using as a fixed image on my site - bit like a parallax affect. Lighthouse is reporting a bug 'Displays images with incorrect aspect ratio' - ratio in question is when the image crops to a much thinner image on mobile - understandable I suppose. This is the dimension it is reporting 412 x 1289. See screenshot.

The problem I can't get my head around - even when I upload an image with identical image dimensions it is still filing a complaint. Again see screenshots. You can see my image is almost perfectly the same size and ratio. So what is this error actually reporting? Is this a bug or am I completely miss-understanding the purpose of this particular check?

Thanks in advance for the help.

![Screenshot 2019-03-22 at 19 49 57](https://user-images.githubusercontent.com/29481254/54849364-f5fc1d00-4cdb-11e9-9f45-32454f8ba277.png)

![Screenshot 2019-03-22 at 19 54 34](https://user-images.githubusercontent.com/29481254/54849531-7753af80-4cdc-11e9-9edd-89a171e94841.png)

**Comment by patrickhulce** [comment]
Hm that's really odd @davidlower what version of Lighthouse were you using? 

I think this issue was fixed a very long time ago, but it's possible it's a new one.

**Comment by davidlower** [comment]
Hi @patrickhulce I believe I am using the latest 4.2 version.

**Comment by patrickhulce** [comment]
Can you give us a URL where we can reproduce this?

**Comment by davidlower** [comment]
@patrickhulce sure - http://springconsultancy.com

**Comment by patrickhulce** [comment]
Thanks @davidlower! That page never loads for me at the moment though, the server never responds and Chrome times out.

**Comment by davidlower** [comment]
@patrickhulce oh I’m really sorry. I did a typo. My bad. Apologies for wasting your time. I edited the original url I posted. So now it is correct.

**Comment by patrickhulce** [comment]
Thanks for the update, I don't see that failure on that page though. There's just one failure for that audit of a different image that is indeed squished a bit.

![image](https://user-images.githubusercontent.com/2301202/54868437-75c8cc80-4d5a-11e9-95a6-f4311e714784.png)

**Comment by davidlower** [comment]
@patrickhulce I don't understand how you are seeing this image. This image is only showing on desktop via a media query. I have cleared the cache on my server, on chrome and chrome is tick with cache settings off. This is what I am getting (please see screenshot).

Either way let's say this is the image in question. Why is it throwing an error? Is lighthouse so fussy over 11px. For me this in itself is an error. I can't for the life of me understand or see why this should even be a part of such a great piece of software, in the sense that an error is thrown due to a 0.03 difference in ratio aspect.

Perhaps I am miss-understanding what this test is trying to achieve. I have never seen it cause a problem like this before. I appreciate the help here.
![Screenshot 2019-03-24 at 19 47 29](https://user-images.githubusercontent.com/29481254/54884936-997d3700-4e6e-11e9-8a30-029958e60402.png)

**Comment by patrickhulce** [comment]
Ah I see, we've fixed this bug very recently that's why I wasn't able reproduce it :) (see #7516) 

The next time Lighthouse rolls out a release to Chrome this should go away on its own 🎉
