### ISSUE TITLE
How do non applicable audits work?

### ISSUE THREAD

**Issue by quetzalsly** [GoogleChrome/lighthouse#7660]
Lighthouse is saying that these are non applicable:

* `robots.txt is valid`
* `Document has a valid rel=canonical`

And it shows a green tick for them, at first I thought it did those audits and it passed but I realised this is not the case?

Why does it determine that those are not applicable? aren't they kind of important for SEO?
I am running the test on webpack-dev-server in 127.0.0.1 not sure if that's anything to do with it.
Ideally I want lighthouse to force me to have the website 100% perfect for SEO and not just classify some things as non applicable?

Are the non applicable audits less important?

This is my config:

```
"use strict";

module.exports =
{
  extends: 'lighthouse:default',
  settings:
  {
    skipAudits: ['redirects-http', 'uses-http2', 'dom-size', 'duplicate-id', 'critical-request-chains']
  }
};
```

**Comment by patrickhulce** [comment]
An audit that's not applicable means that there's a case where this audit's advice just doesn't apply and so it doesn't factor into the score.

Not all sites need a robots.txt, and it's not like arbitrarily blocking some of your URLs will improve your SEO, but if you do have one and it's broken, that's an SEO problem.

Not all sites have a different canonical URL to specify, and it's not like arbitrarily picking another URL to be the canonical version of an unrelated page will improve your SEO, but if you do specify one and it's invalid, that's an SEO problem.

**Comment by quetzalsly** [comment]
Thanks for explaining. Is there a way to force all audits? also why does it leave a green checkmark even though it didn't run the audit?

**Comment by patrickhulce** [comment]
>  Is there a way to force all audits? 

I'm not sure what you mean. If you didn't have a robots.txt/whatever was not applicable there is nothing to run for it :)

> lso why does it leave a green checkmark even though it didn't run the audit?

It leaves a green checkmark because you are "passing" in the sense that there is nothing for you to fix. You're doing everything right according to the audit.

**Comment by quetzalsly** [comment]
By force, I meant to make all audits run regardless if I have a robots.txt or not, like to get the maximum possible value of lighthouse by checking everything at once. The way you described it, I guess this audit is not very important, still it would be nice to have a lh config like 'lighthouse-maximum'. But I will close this issue anyway, thanks.

**Comment by brendankenny** [comment]
> I meant to make all audits run regardless if I have a robots.txt or not, like to get the maximum possible value of lighthouse by checking everything at once.

As @patrickhulce said, the audit absolutely *does* run so it can know to mark itself `notApplicable`.

`notApplicable` audits also don't hurt the Lighthouse score. They aren't applicable for this site, so the aren't included in the score.

> The way you described it, I guess this audit is not very important

The audit *is* important if a site has a `robots.txt` file, but this particular site didn't have a one, so it's not important *for this particular site*.

Without a `robots.txt` file, there's no danger for SEO on this front, and the Lighthouse UI assumes the user won't want to hear about how the `robots.txt` file they don't have isn't causing any errors, because they don't have one.
