### ISSUE TITLE
Tinder PWA won't stay logged in

### ISSUE THREAD

**Issue by drjamiwe** [GoogleChrome/lighthouse#7665]
Tinder PWA wont let me stay logged in on my phone.

1. Run Tinder PWA
2. Logg in with Phone Number
3. Swipe and have fun
4. Close or only leave app
5. reopen app
6. You have to sign in again

iPhone X, iOS 12.1.4, clean install

**Comment by patrickhulce** [comment]
You might want to file this with Tinder then, it's not really the responsibility of the Lighthouse project :)
