### ISSUE TITLE
Can't find the font lighthouse is showing me to fix

### ISSUE THREAD

**Issue by halilozanyilmaz** [GoogleChrome/lighthouse#7674]
Hi,

Lighthouse says: "Ensure text remains visible during webfont load" and shows me the following underneath:

![what_is_this_font](https://user-images.githubusercontent.com/25062864/54888721-bd616c80-4eb0-11e9-9ec2-395c9efe9137.JPG)

I disabled all my plugins. The page source code doesn't contains "woff" keyword. My theme doesn't contains "woff" keyword. How can I find the source of this thing? I am not able to fix it if I can't find it.

**Comment by patrickhulce** [comment]
Are you willing to share the URL of your page?

Have you used the network search feature of DevTools to try to find it? (Hit Ctrl/Cmd+F while in the "Network" tab)

![image](https://user-images.githubusercontent.com/2301202/54889067-8cf9de00-4e70-11e9-88a0-319b8272652e.png)

**Comment by halilozanyilmaz** [comment]
I can find it in dev tools. However even using chrome developer tools, I can't what is causing this font the download, and which part of my website causes it. 

Here my site: tisort.ist

**Comment by halilozanyilmaz** [comment]
The issue is not related to lighthouse. It was coming from dashicons.min.css. This is a core wordpress file, I am not sure how can I fix it but I will look for ways.
