### ISSUE TITLE
Add HTTPS test to Add to Homescreen (A2HS) section

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#770]
It's one of the criteria:

https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/#what-are-the-criteria

**Comment by paulirish** [comment]
it does work on localhost, even without HTTPS: https://bugs.chromium.org/p/chromium/issues/detail?id=487609#c10

so, IMO we can keep this to just requiring a service worker, which comes with its own "secure origin" requirements. seems a bit simpler for the user.
