### ISSUE TITLE
Update time-to-interactive scoring to <5000ms

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#780]
This is more representative of achievable TTIs on 3G when testing on real-world devices and also aligns with Alex Russell's [what exactly makes a PWA doc](https://infrequently.org/2016/09/what-exactly-makes-something-a-progressive-web-app/).

He was specifically calling out being interactive in <5s pre-Service Worker installation and <2s post.

**Comment by paulirish** [comment]
(Currently, the fast-enough-for-pwa audit wants TTFI <= 10s.)

**Comment by paulirish** [comment]
closing in favor of #4629
