### ISSUE TITLE
[Page Speed Api] Reduce payload size for data studio reports by using `fields` key in api ( similar to v4)

### ISSUE THREAD

**Issue by grantkemp** [GoogleChrome/lighthouse#7800]
**Feature request summary**

I would like to have the ability in the  v5 Api to replicate the standard `fields` parameter that we had in the v4  PagesSpeeds Api. By returning just the data I am interested in, it will:

- reduce the resources needed for a PS report as some audits that won't be returned might not need to be run 
- reduce the download time for a page speed report ( Kind of what Page speed recommends!) 

** How this would work:
I would add a `fields` key ( similar to v4) and only return the data specified. 

![image](https://user-images.githubusercontent.com/751115/55222760-91bde980-5204-11e9-8ad1-5b7400142297.png)

```
curl -X GET \
  'https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://www.domain.com&strategy=mobile&key=IAMNOTTELLINGYOU&fields=ruleGroups,formattedResults&category=performance&locale=en_GB' \

```

eg If I wanted to just return speed index I could add fields= audit-speed-index.  (You could standardise use of the JSON field to describe it so it would be self documenting and extensible for new audits)

I wouldn't know where to start ref doing the API work( if I was given pointers on where to make the changes  I don't mind having a go) - otherwise I am happy to support testing efforts -and could generate Data studio reports to test the api across several websites automatically.

**What is the motivation or use case for changing this?**
Since I am updating the [Data Studio - Page Speed insights connector to v5](https://github.com/googledatastudio/community-connectors/pull/138) that lots of users will use via Data Studio - I want it to be fast performing so users will choose to surface PS data in their internal dashboards.  

If I have a `fields` key in the api, I would be able to only surface certain data reports and make it faster to load.   I am planning to adding caching - but the speed of the initial download is key ( just like you say in the PS reports)

**How is this beneficial to Lighthouse?**
- More novice and non-technical people will use the Lighthouse data in a clean and easy to configure method. 
-  It can be automatically surfaced into senior reporting via the Data Studio connector.  We are using it at our work - and it now goes to team heads as part of regular reporting.

**Comment by grantkemp** [comment]
This should help resolve https://github.com/googledatastudio/community-connectors/issues/145

**Comment by Hoten** [comment]
All of the required changes for this would be internal to Google (PSI) - fortunately LH and its config already supports narrowing the work done / response size just fine via the config (`onlyAudits`, `onlyCategories`).

We are still have discussions internally on if a custom config should be accepted by PSI (which would allow you to give your own `onlyAudits` value). An alternative would be a new field `audits` in PSI that gets passed to `onlyAudits` in LH.

**Comment by grantkemp** [comment]
Good approach @Hoten  - that sounds sensible.  
Potentially to keep complexity down - it might be easier to treat the audit flag as a facade initially which despite the fact the work is going on the background in LH/ PSI, only the relevant reports are returned.  This would keep the data consistent - and result in having to do less logic/ error handling in PSI.  
Based on the amount of users making use of this feature - it could help to plan the backlog and determine feature usage.

**Comment by brendankenny** [comment]
> reduce the download time for a page speed report 

can you give some idea of the expected savings for this? For instance:

> Since I am updating the Data Studio - Page Speed insights connector to v5 that lots of users will use via Data Studio - I want it to be fast performing so users will choose to surface PS data in their internal dashboards.

What's the bottleneck for this? Is the connector run remotely within Data Studio? If so, it doesn't seem like savings would help much when transfering from Google server to Google server. Or is some of it run locally before uploading back to Data Studio? Or are there many reports being loaded and every bit helps?

**Comment by grantkemp** [comment]
I did an experiment and setup 6 seperate urls in the report - it seems to run all the queries in parralel -and when I compare the results against straight calls to the API from my desktop - I noticed that the scores were wildly off.  

I am not sure if this is down to 
1. Lighthouse, 
2. Some sort of balancing that happens in the way that Data studio loads content
3. The urls themselves being under load and reporting different values. 

The numbers seem to return a lower value from my local desktop calling to the api than they do from data studio. 

Do you have a recommended set of 3-6  that I can setup a test with - that you know return relatively consistently from PSI.

**Comment by paulirish** [comment]
A few thoughts on this feature request for the pagespeed API: 

* We currently allow you to select which categories you are interested in. Fewer categories will typically allow the API to respond quicker.
* We're not going to introduce a new mechanism to select a subset of audits within a category.  It adds some complexity we're not interested in supporting.
* Having this extra data in the API response doesn't substantially change your download time of the data, so that shouldn't be a big consideration.  You can ignore the extra data on your side. :)

@grantkemp your last message is about variance. That seems to be a separate concern. Take a look at https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md

**Comment by grantkemp** [comment]
Thanks @paulirish  I think that makes sense - I think the approach for Data Studio is going to be probably just to have better cacheing. 

In terms of the variability I am seeing - I think its because I have been looking at a react page that the speed index has varied so much.  I am not sure if its Page nondeterminism or just React-being-difficult-ism ( might be another category for your docs) 

Lets close this based on your advice above.
