### ISSUE TITLE
http errors in errors in console audit

### ISSUE THREAD

**Issue by hassaans** [GoogleChrome/lighthouse#7862]
**Summary**
I'm using `$.ajax` for API calls. When the user is logged out, this error is logged in the console by chromium: `GET http://localhost:8080/api/user/info 401 (Unauthorized)  jquery.js:9600`

There's no way to suppress this. Shouldn't lighthouse ignore these errors?

**Comment by Hoten** [comment]
Probably not.

You didn't provide your version of jquery, but perhaps you need to update. Or look into potential cross-domain issues. just some resources you should look at: [1](https://stackoverflow.com/questions/22196089/why-i-am-always-getting-401-unauthorized-error-in-case-jquery-ajax) [2](https://stackoverflow.com/questions/29782222/jquery-ajax-call-results-in-401-unauthorized-response-when-in-chrome-or-firefo)

**Comment by hassaans** [comment]
jquery version: 3.3.1
Additional Resources: [1](https://stackoverflow.com/questions/4500741/suppress-chrome-failed-to-load-resource-messages-in-console) [2](https://stackoverflow.com/questions/41515732/hide-401-console-error-in-chrome-dev-tools-getting-401-on-fetch-call)

**Comment by lisaweathers** [comment]
Hi Connor Clark, i would of provided any info. if i knew how, lol i don't
know anything about computers and do not understand
the technology of any of it, so i apologize , can u still help, i just need
to speed up computer, its says to render,javascript and css
i don't have a clue...thank u

**Comment by brendankenny** [comment]
The console errors are just advisory to let you know that something might be going on in the page that you didn't expect. Just having a console error will have no effect on the Lighthouse score on its own (though the underlying issue may or may not have an effect on the speed of the page, of course).

Closing for now, but please comment if you feel this doesn't address things and we can reopen.

**Comment by bergkvist** [comment]
Actually, getting a 401 Unauthorized does affect the lighthouse score (Best practices) on its own:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/410028/178122888-4c89a733-d7a1-47fe-8b98-c8fb7774cea0.png">

**Comment by connorjclark** [comment]
" the Lighthouse score" just means the performance score, FYI. The response in #9481 is still our position.
