### ISSUE TITLE
Error: You probably have multiple tabs open to the same origin. : ( puppeteer + lighthouse )

### ISSUE THREAD

**Issue by ankurgpt6719** [GoogleChrome/lighthouse#7876]
Hi, 

I understand that the above mentioned issue ( in headline ) is already discussed and resolved here : https://github.com/GoogleChrome/lighthouse/issues/3024
But I am trying to use lighthouse programmatically integrated with puppeteer and here I am encountering this issue `Error: You probably have multiple tabs open to the same origin.`.
Please help me on how can I resolved this issue programmatically.

Thank you

**Comment by ankurgpt6719** [comment]
Yup the already file issue is my reference to resolve it manually but I need to do it programmatically.

**Comment by ankurgpt6719** [comment]
necessarily-wide-alpaca

**Comment by patrickhulce** [comment]
Can you give us a little more info on your setup? The error, as its message implies, means that you probably have more than one tab open :) 

Note that depending on your Chrome version some web features like `prerender` can also trigger this if you have the page already open.

**Comment by ankurgpt6719** [comment]
yup true.

I am using puppeteer to launch chromium `<Version 74.0.3723.0 (Developer Build) (64-bit)>` in Mac.
Versions :
`"lighthouse": "^4.1.0", "puppeteer": "^1.13.0"`

I noticed there are Iframes in the website and as mentioned in the issue https://github.com/GoogleChrome/lighthouse/issues/3024 is one of the cause of the error...but how can I make it working programatically ?

one solutions which I tried was to eliminate the Iframe from the DOM using puppeteer programatically but then control transfers to LH and it loads the entire page in new tab for it operation and fails with the above mentioned error.

**Comment by patrickhulce** [comment]
So it's fine if the page creates new tabs/iframes/etc *while* Lighthouse is running, it's just a problem if they exist before Lighthouse is called.

I'm assuming you're using puppeteer to do some sort of setup (login or whatever), so if you navigate away from your page or close the tab before Lighthouse is called, you should be able to get around the error.

**Comment by ankurgpt6719** [comment]
@patrickhulce suggested solution is definitely one of the working solution.
But this would not meet the case if the data needs to be retained during the LH run ( we lose the content when page is navigated or closed ).
Haven't explored much around the passes in configuration , would this be helpful ?

**Comment by patrickhulce** [comment]
@ankurgpt6719 the content on the page is never retained with Lighthouse at the moment anyhow, we always reload the page.

Glad you got it working! See #1769 if you have input on not requiring the refresh.

I'll go ahead and close this for now since you got it working, but feel free to reopen if there's more to add.
