### ISSUE TITLE
Ligthouse checks for an icon in the manifest but does not try to load it

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/lighthouse#789]
While collection few PWA examples I have found that many manifest have icon URLs but they are actually broken, 404 or errors in the relative path.

I think that "Manifest contains icons at least 144px" should not be true if the URL is broken, or at least have another way to point it out in the report.

**Comment by brendankenny** [comment]
The DevTools fetches the icons for display in the Application panel. It doesn't appear to go through the page itself, though, as the icon fetch doesn't show up in the network panel like the fetch of the manifest itself does.

@paulirish any idea where the Application panel gets those? Is it something Lighthouse can piggyback on?

**Comment by paulirish** [comment]
Application panel just reads the icon URLs and does a `new URL(iconURL, manifestURL)` and `image.src`'s it:

![image](https://cloud.githubusercontent.com/assets/39191/25461026/81520280-2a9b-11e7-9fe3-c92d4fb96394.png)

but yeah we should validate these icons don't 404.

we probably want to request from inside the host page.. (however devtools doesn't use any fancy auth)

**Comment by bitterjug** [comment]
I ran into this today. Lighthouse says "User can be prompted to Install the Web App" but no A2HS appears on my phone and I ended up inspecting it via remote debug tools and triggering the A2HS to see "The site cannot be installed: icon downloaded from the manifest was empty or corrupted" errors.

**Comment by docluv** [comment]
I am getting a similar error as bitterjug. 

Error while trying to use the following icon from the Manifest: http://localhost:57661/meta/android/android-launchericon-144-144.png (Download error or resource isn't a valid image)
11:00:24.067 localhost/:1 Site cannot be installed: icon downloaded from the manifest was empty or corrupted

The image loads fine in any image editor and browser. The URL returns the image, etc. So I am wondering what triggers this error and how to correct it.

**Comment by filt3rek** [comment]
Hej guys !

I still have this error when launching an audit with devtools : (Download error or resource isn't a valid image) when trying to load the android-144x144 image
Is it a bug or do I miss something please ?

**Comment by connorjclark** [comment]
DT release cycle is long. Will be months before it is fixed there. fix is in master, we are about to do a 6.0 release to npm, but DT is longer b/c of Chromium release cycle
