### ISSUE TITLE
LIGHTHOUSE_CHROMIUM_PATH can be identified automatically on Linux

### ISSUE THREAD

**Issue by nazar-pc** [GoogleChrome/lighthouse#791]
Having Chrome/Chromium installed on Linux typically means that there are `*.desktop` files corresponding to installed application.
Global files are likely located as `/usr/share/applications/*.desktop` and local to user as `~/.local/share/applications/*.desktop`.

So in most cases it is possible to scan files at those directories and try to find something with `/chrome` in `Exec` key. This wouldn't work in case when Chromium was extracted into some directory and no desktop file was created, but otherwise it might improve convenience of using lighthouse by not requiring to specify `LIGHTHOUSE_CHROMIUM_PATH` explicitly (which is boring).

**Comment by wardpeet** [comment]
will have a look on a vm with a few distros

**Comment by wardpeet** [comment]
@nazar-pc can you look into #856 if that works for you.

**Comment by nazar-pc** [comment]
Commented in PR

**Comment by jeanleonino** [comment]
Just installed `lighthouse` on `Linux Ubuntu 16.04.1`, `node 6.9.1`, and `zsh 5.1.1` and had the same issue.

**Comment by wardpeet** [comment]
@jeanleonino thanks we have a pr open that fixes this issue without setting the chromium path. (#856)

**Comment by paulirish** [comment]
fixed by #856
