### ISSUE TITLE
Unable to detect form label

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/lighthouse#796]
When run on  https://cdn.rawgit.com/ithinkihaveacat/8577d6d00eb08f48b4a6e3fd015c379d/raw/f943193a01bff03ea7df37b9bf4ef206d9f2486c/index.html Lighthouse complains that the #s form element is missing a label:

![screen shot 2016-10-19 at 2 35 57 pm](https://cloud.githubusercontent.com/assets/51244/19520829/765ba9d4-9609-11e6-92d0-ab91e3483d29.png)

This element does actually have a label:

![screen shot 2016-10-19 at 2 37 00 pm](https://cloud.githubusercontent.com/assets/51244/19520864/8dc5841e-9609-11e6-89db-e7d86fffb594.png)

(Sorry about the big test case; I tried reducing it to just the form itself but for some reason the label is correctly detected in this case.)

**Comment by brendankenny** [comment]
We us [axe](https://github.com/dequelabs/axe-core) for testing accessibility, so this may be an upstream issue. We're also using a version that's over a year old, so it's possible this has been fixed on master.

Is it possible to try out the page after inserting axe as described here: https://github.com/dequelabs/axe-core#getting-started

It should hopefully be as straightforward as described in those docs.

**Comment by brendankenny** [comment]
(you might also try `npm install axe-core@1.1.1` (our current version) to verify that it's axe causing the issue and not our use of it)

**Comment by ithinkihaveacat** [comment]
Seems to be a bug in axe. To reproduce, load <https://cdn.rawgit.com/ithinkihaveacat/8577d6d00eb08f48b4a6e3fd015c379d/raw/f943193a01bff03ea7df37b9bf4ef206d9f2486c/index.html> then paste the following into the console:

```js
function loadScript(src) {
  return new Promise(resolve => {
    const e = document.createElement("script");
    e.src = src;
    e.onload = resolve; 
    document.head.appendChild(e);
  });
}

loadScript("https://unpkg.com/axe-core/axe.min.js").then(() => {;
  axe.a11yCheck(document, r => console.log(r.violations[2]));
});
```

It outputs a `Form elements must have labels` error on the element `<input class="gp-offline-disable" type="search" name="s" id="s" placeholder="Search" value="">`. I'll create an issue on the axe repo.

**Comment by ithinkihaveacat** [comment]
Reported as https://github.com/dequelabs/axe-core/issues/242.

**Comment by brendankenny** [comment]
Thanks!

Based on the discussion in https://github.com/dequelabs/axe-core/issues/242, I'm going to close this since it appears they have it correct. Let me know if we should actually keep it open.
