### ISSUE TITLE
Allow interrupting the audit gracefully

### ISSUE THREAD

**Issue by pavelfeldman** [GoogleChrome/lighthouse#797]
Typically it is implemented by means of a cancelable progress indicator. Prior to any activity, each step is querying whether the progress has been canceled and if so, bails out. Otherwise it ticks the progress and continues. I can try adding something like that into the runner.

**Comment by brendankenny** [comment]
SGTM

**Comment by paulirish** [comment]
see also Add progress bar for crx/devtools auditing #1630

**Comment by paulirish** [comment]
We think it's the same to the user either way, so we're not going to take this on rn.

**Comment by Kikobeats** [comment]
@paulirish 

is there any way to "cancel" the current report generation, even it isn't gracefully?

<img width="1440" alt="Screenshot_2020-05-19_at_22_00_49" src="https://user-images.githubusercontent.com/2096101/82372751-d2864c80-9a1c-11ea-8efc-a0ca4e2ac967.png">

Looks like lighthouse can't be interrupted, even the browser instance (puppeteer in this case) used for getting the report doesn't exist anymore.

I thought that killing the browser was forcing lighthouse prematurely, but it was a totally wrong assumption 🤔

**Comment by connorjclark** [comment]
Ctrl-C should do it. May need to then manually kill Chrome, if it launched an extra window.

**Comment by paulirish** [comment]
https://github.com/GoogleChrome/chrome-launcher#launchopts has `handleSIGINT` which defaults to `true` (and that's how Lighthouse typically instantiates chrome-launcher)

it's implemented to terminate the chrome process and then call `process.exit()`. so, like @connorjclark said.. ctrl-c should work fine for you..


it is true that if the Chrome process is terminated while Lighthouse is operating.. Lighthouse doesn't necessarily panic and quit. We never added handling for that

**Comment by Kikobeats** [comment]
@connorjclark I can't do a Ctrl-C in a production server

**Comment by paulirish** [comment]
sigint is the handler for ctrl-c, btw.

hmmm how is the browser instance being killed?

or perhaps the other thing to explore here is the use of timeouts. Lighthouse has a few.

`maxWaitForLoad` is probably what you want. it defaults to 45 seconds. you could reduce that if you dont like Lighthouse taking too long. note: this just covers the wait of one pageload, not the entire run.

**Comment by Kikobeats** [comment]
@paulirish using `maxWaitForLoad` was enough for my use case, thanks for that 👍
