### ISSUE TITLE
Bad Dom sizes

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#7972]
**Summary**
Hi
I´m not a developer so can´t say much more about this.
In a web I manage, running LH i get Avoid an excessive DOM size. Reading the recomended sizes it says:  fewer than ~1,500 DOM nodes / a tree depth < 32 elements / fewer than 60 children/parent element
The sizes reported are:

Total DOM Nodes |   | 902
Maximum DOM Depth |  | 20
Maximum Child Elements |  | 37

So these are lower than the recomended. Why LH trow this in diagnostics?
Url to test: https://intersindicalrm.org/ensenanza/

**Comment by patrickhulce** [comment]
Hi @Lofesa! Those specific DOM size numbers aren't a big concern. The diagnostics are trying to flag *potential* reasons the metrics aren't green and would be helpful for a developer to look into, but aren't problems on their own and do not affect the score.

**Comment by Lofesa** [comment]
Hi @patrickhulce , Thx for your response. But why if the numbers sound reasonable don´t put this on the passed audits (green)? If LH show this in orange users trend to think is to look into this.

**Comment by patrickhulce** [comment]
Well the numbers aren't *good*, so it's not green. But they also aren't *really bad*, so it's not red. Orange strikes the balance of "not terrible, but also not good". If you were going to address performance issues, it's the next thing to look at after the heavy main thread work, so putting it as the second diagnostic feels about right. 

I was trying to say that orange in a diagnostic is not a large concern on its own, the diagnostics aren't scored, and the metrics (First Contentful Paint, Time To Interactive, etc) are what matter, so focus on those.
