### ISSUE TITLE
Problem: Render-blocking JavaScript

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#80]
Non-async script resources that are layout-blocking. 

##### Calculating the total time cost:
* Grab all blocking JS requests (script net requests with priority of {Medium, High, VeryHigh})
* Duration of each script == from fetchStart though responseEnd until ExecuteScript finishes. 
* Last critical script == last script to executescript before first meaningful paint. Discard any following.
* Total duration == Activity time span from first script's start to last script's finish. 

##### What we report:
* What are the resources
* Their individual times of (network + main thread)
* Total activity time span.

**Comment by paullewis** [comment]
Can we orientate this more towards the user? I mean, it's good data to have, but it feels like it's in support of FMP. If you're blocked because of resources (JS, styles), then when we surface your first paint we should attach what data we know from CRP?

**Comment by brendankenny** [comment]
I believe that's the intention. @paulirish can say more, but looking at the mocks, it's: "Your FMP is pretty slow, here's the set of things you're doing during that time"

**Comment by brendankenny** [comment]
https://docs.google.com/document/d/1V95VD-8UNxPEc2ciu1Q4TCRJOuBdEhgOXgRXp2oLkkw/edit is the one I'm talking about

**Comment by paulirish** [comment]
After further discussion, it makes sense to defer the perf diagnoses implementations. This will give us the bandwidth to nail PWA audits and top-level perf metrics.
