### ISSUE TITLE
Form elements do not have associated labels

### ISSUE THREAD

**Issue by joedag32** [GoogleChrome/lighthouse#8073]
I think we're getting a false positive with a recent update to Lighthouse (4.0) in the Chrome browser:

![Screen Shot 2019-04-08 at 3 53 44 PM](https://user-images.githubusercontent.com/393691/55752652-86de3280-5a16-11e9-99b6-8f43cfef796a.png)

on the following page:
https://www.stockton.edu/about-stockton/index.html

**Comment by patrickhulce** [comment]
Interesting, latest LH (about to launch as 4.3.0) gives that site a 100 in accessibility.

![image](https://user-images.githubusercontent.com/2301202/55753007-ef291600-5a0e-11e9-83f9-b34dad5f8323.png)

Perhaps we already fixed whatever it was with an axe update :)

**Comment by joedag32** [comment]
nice! Thanks for the quick response. Look forward to 4.3.0!

**Comment by patrickhulce** [comment]
Cool cool 😎
