### ISSUE TITLE
Gather scheduling strawman

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#81]
```js
const LIFECYCLE = {
 InititalBinding: 1,
 BeforePageload: 2,
 AfterPageLoad: 3,
 AtRest: 4, 
… 


class Thingthing extends Gather {

  static gather(opts) {

    driver.waitFor(LIFECYCLE.BeforePageload)
    .then(_ => …)
    .then(_ => …)
    .then(_ => driver.waitFor(LIFECYCLE.AtRest)
    .then(_ => …)
 ```

Disclaimer: All the names are definitely wrong. 

But that said, I'm thinking this seems a nice way of managing scheduling of all gather work, so we don't step on toes and minimize repetitive work.

All gathers MUST start with a `waitFor`. It's possible they have a second.

Thoughts?

**Comment by paullewis** [comment]
I like it. How do we guarantee ordering? (You could put at rest before initial), and how do we order within the set of gathers scheduled for a given lifecycle point? Last question: who instructs the driver to move to the next stage?

**Comment by samccone** [comment]
I am pretty convinced that some gather operations will be destructive (cause the browser to be in a state where no other gathers can run)

For now, allowing the gather to do whatever will continue to work, I think this is a deep deep rabbit hole if we start trying to optimize the gather phase. I am totally with you that the more times we revisit the page the more variance we will get (if we gather the same number twice) But I am not so convinced of the upside of trying to optimize the gather phase to reduce the number of reloads given the complexity cost of this task.

So long as each gather phase exits cleanly everything should be "OK"

For drool, i setup basic life-cycle hooks that you could put logic in for each memory test, that seemed to work out pretty OK for me.

https://github.com/samccone/drool/blob/master/docs/api.md#flow

**Comment by paulirish** [comment]
Tried to capture a few usecase for timing in this doc: https://v.etherpad.org/p/MCiOMkGOcf

@deepanjanroy was thinking it may make more sense to have gathers extend a base class that has these lifecycle events defined.. e.g. setup, beforeLoaded, pageLoaded, teardown.

This is in line with how Telemetry does it, in fact. In [key_silk_cases.py](https://code.google.com/p/chromium/codesearch#chromium/src/tools/perf/page_sets/key_silk_cases.py&sq=package:chromium) see `__init`` `RunNavigateSteps`, `RunPageInteractions` `PerformPageInteractions`

**Comment by paullewis** [comment]
There's already a gather base class IIRC so we should be gtg there.

**Comment by paullewis** [comment]
Yyyyyyyeah https://github.com/GoogleChrome/lighthouse/blob/master/gatherers/gather.js
