### ISSUE TITLE
Update README / CLI help to mention that it can handle multiple URLs?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#810]
I'm walking through the source right now and it looks like the CLI can handle multiple URLs. Is that right? If so, should we document that? Or is it not ready?

**Comment by addyosmani** [comment]
Yep. We added that a few weeks ago. Should be good to doc.

**Comment by paulirish** [comment]
kayce can you put up a PR for this?

**Comment by brendankenny** [comment]
support now removed again :)
