### ISSUE TITLE
Red icons mean fail. PWA optimized score is confusing. 

### ISSUE THREAD

**Issue by jorange94010** [GoogleChrome/lighthouse#8112]
Looks like there was a change to a badging system for Lighthouse Scores for PWA. I like the new system, but the icon that is associated with PWA Optimized is red. Each time I see the badge appear, it makes me think that we failed the test. Red traditionally means failure or error, so I would request that a different color is used.

**Comment by patrickhulce** [comment]
cc @hwikyounglee for her thoughts on this :)

**Comment by hwikyounglee** [comment]
Thanks for the feedback, @jorange94010 -- yes to address the exact issue you describe, the icon colors are to be updated. Not an immediate fix yet, but, a fix is coming.

**Comment by jorange94010** [comment]
Great! Thanks!

**Comment by patrickhulce** [comment]
The latest version of Lighthouse has implemented the design in https://github.com/GoogleChrome/lighthouse/issues/8112#issuecomment-481374846 that does not have a red optimized icon 🎉

**Comment by jorange94010** [comment]
Awesome!
