### ISSUE TITLE
PAGE_HUNG on cnn

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#8113]
```sh
node lighthouse-cli https://www.cnn.com --view
```

@hoten and I get this on master this morning.

**Comment by paulirish** [comment]
It's a chromium bug.. or more specifically.. a v8 bug.

https://bugs.chromium.org/p/v8/issues/detail?id=9105

**Comment by Hoten** [comment]
This is fixed in Canary now. PSI won't get the fix until the next time we update WRS.
