### ISSUE TITLE
Audit proposal: polyfills

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#8120]
originally in #6730, available in the [ext-polys](https://github.com/GoogleChrome/lighthouse/tree/ext-polys) branch.

Moving the discussion from the PR to here as we're not quite ready for our next-gen JS payload analysis audits yet.

See also #3862

<hr>
original post from @Hoten 

I imagine this will go through a few iterations.

![image](https://user-images.githubusercontent.com/4071474/49537660-65a9e180-f87e-11e8-8059-86f9b43c1f84.png)

@paulirish had the idea to surface what polyfills are in use, and suggest removing them. It sounded like fun so I took pass at it.

First, let's talk detecting polyfills. I thought about a few ways to do it, but just two were viable. We could parse out an AST to extract where native functions were being redefined. But, that's likely to be slow, and would add quite a large dependency. Instead, I opted for somewhat-simple regex parsing. The grammar for setting a property (either `=` or `Object.defineProperty`) is fairly simple to grok for, and ought to be much faster. So I went with regex.

Second, let's talk what suggestions to make. I'm not sure we can concretely suggest removing _any_ pollyfills. Developers often must support an audience that uses old browsers, so suggesting removing polyfills for features present in the newest browsers would not be found agreeable. Even if a feature is found in browsers going back to IE8, it can still be the wrong call for some sites. So I suggest not attaching any score to this audit, and keeping the language non-prescriptive. Instead, we can just surface what pollyfils exist and suggest that they consider researching what they actually need.

Some things worth talking about:

1. Detecting modules that reimplement native JS features, but don't actually pollyfil anything. For example, bundling `lodash/startsWith` for a web target, and using that instead of `String.prototype.startsWith`. Bundlers tend to strip module names in production, so such detection likely requires source maps. Otherwise, we're left with analyzing what these modules look like minified. This could certainly be explored further in a separate feature.

2. If a polyfill appears multiple times from multiple scripts, I display a counter in the report. I imagine this would only be actionable if the polyfills are coming from the same origin - if two third party scripts are pollyfilling the same thing, there's nothing really to be done. Should we suggest action only if multiple pollyfills are coming from the same origin? If so, what's a good way to present that suggestion?

3. The location in the script that the pollyfill occurs is provided in the report. Usually, this script is minified, so really it's just an index into an unreadable buffer... Is this useful at all? Should this be removed and only added back with source map support?

4. I grabbed a list of features that can be pollyfilled from [here](https://www.npmjs.com/package/mdn-polyfills#supported-polyfills). Certainly not exhaustive. From where should we source this list?

Related: #3862

**Comment by Hoten** [comment]
Closing because we didn't _actually_ discuss anything here :)

I've reopened the PR.
