### ISSUE TITLE
Add DBW and smokehouse to CI

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#814]
- [x] smokehouse (PWA tests)
- [x] DBW tests

Will help prevent regressions like #808

**Comment by brendankenny** [comment]
first step is in #824.

@ebidel you can take the DBW part or we could discuss and I can try to write something up

**Comment by ebidel** [comment]
Do I just need a config and expectations file?

**Comment by brendankenny** [comment]
yes, then do `npm run smokehouse -- --config-path=path/to/config.js --expectations-path=path/to/expectations.js` (where path is relative to lighthouse root directory)

the config file can just be the default DBW config (that way you don't have another config file you have to update as you add new audits)

Main thing to watch out for is speed, as this will be running on every travis run. We might want to write some local example page tests like the [offline/online example pages](https://github.com/GoogleChrome/lighthouse/tree/88cad9e62b84a8efb2b92278304ebcfa0963f7fc/lighthouse-cli/test/fixtures) used for `npm run smoke`

**Comment by ebidel** [comment]
Awesome. I have a mega test page that's configurable and hits different
edge cases. I'll just check that in as a smoke test.

**Comment by wardpeet** [comment]
Checked smokehouse checkbox because of PR #824
