### ISSUE TITLE
Deploy the updated report to the web after every push

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#8159]
We have a bunch of report UI changes upcoming.. the first of which from @hoten updates the gauges (#8121).

[Zeit/now.sh has an integration with GitHub](https://zeit.co/docs/v2/integrations/now-for-github/) nowadays that makes this very straightforward. (Last year, I had a real hacky solution for this, which is no longer necessary yay!)

Please check it out in action here: https://github.com/paulirish/test-lh-for-now/pull/3

* It'll create new deployment items and create a commit status entry (or two) to communicate status of the deployment:
![image](https://user-images.githubusercontent.com/39191/55911874-650bb980-5b96-11e9-9a7f-ff1f330425ee.png)
* Click on `View Deployment` and you'll be brought to something like https://test-lh-for-now-8viv2go5c.now.sh/

These live forever and are free. The report deployment is usually up in ~30s after the commit push. 

Considerations:
1. We can't block the deployment from starting. So we can't really say "only do this on report-affecting PRs". The best we could do is fail a deployment because we don't want it to finish.
1. The GoogleChrome org needs to approve the Now github application.

I think this would be super helpful for review of upcoming report redesign PRs. We could also incorporate stackpacks or plugins if we wanted to always see those too. 

What do folks think? Good stuff or annoying?

**Comment by patrickhulce** [comment]
it's dope and super necessary IMO as we work on total report redesign!

**Comment by paulirish** [comment]
@addyosmani can you help us enable the Now github app for this org? 
I _think_ this is the url: https://github.com/organizations/GoogleChrome/settings/installations

**Comment by paulirish** [comment]
Feature requests:

* PSI UI
* Other reports with different states.. 
  * cnn, lots-of-errors.html

**Comment by connorjclark** [comment]
now is now now

I think we can close this. improving what we put on now will be an ongoing endeavor, hopefully. (like #10151)
