### ISSUE TITLE
Perf numbers are much faster with a warm chrome

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#817]
If there's no debugable chrome open (in the CLI case) then we launch one, wait for it, and then start profiling. It appears we're getting overhead from a new profile bootup that's having a big effect on the numbers.

Looking at `https://example.com/` which is a superfast site..
### Cold chrome:

![image](https://cloud.githubusercontent.com/assets/39191/19630181/ce1067fe-9939-11e6-8698-956d5e40de21.png)
### Warm chrome:

Running `chrome-debug` and letting it sit for like 5 seconds.
![image](https://cloud.githubusercontent.com/assets/39191/19630188/dea770b2-9939-11e6-9df2-9b9e9dc88fcc.png)

On chat we discovered there's 200kb of data transferred on a cold chrome, seemingly for malware. In addition, there is likely some CPU cost overhead for initializing an empty profile.

_Edit_:  I believe "downloading proxy config" is also responsible for a fair bit of it

I bet a little delay injected in there before the profiling starts would sort this out.

**Comment by brendankenny** [comment]
(somewhat related to #775, though that's no longer outright affecting us)

**Comment by wardpeet** [comment]
we could let the cli sleep for a few seconds and show them a message. Warming up chrome :D

**Comment by addyosmani** [comment]
> I bet a little delay injected in there before the profiling starts would sort this out.

Ooof. Yes please.

**Comment by wardpeet** [comment]
How many seconds are we talking about?

**Comment by paulirish** [comment]
Discussed this with @caseq and think proxy config is likely a concern here.

Best looking fix at the moment is as follows:

Load http://connectivitycheck.gstatic.com/hello_lighthouse and wait for load. Once loaded, proceed.
(Alternatively, could run our own webserver and put up a basic/blank page.)

**Comment by paulirish** [comment]
confirmation that it's proxy config:

![image](https://cloud.githubusercontent.com/assets/39191/20118037/e0309410-a5b7-11e6-8602-a9fbf50b0a94.png)

**Comment by patrickhulce** [comment]
tracked by #1982
