### ISSUE TITLE
Report redesign for v5

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#8185]
Design reference: https://yuinchien.github.io/sandbox/lighthouse/

- [x] gauges
- - [x] light fill color (#8121)
- - [x] bigger (#8121)
- - [x] separator removed between normal categories and the PWA (#8121)
- - [x] plugin icon (#8307)
- - [x] gauge order: default, pwa, plugins (#8529)
- [x] score scale (#8121, #8590)
- - [x] center
- - [x] round border
- - [x] reverse order
- [x] opportunities
- - [x] hide savings estimate bar in mobile (#8562)
- [x] audit results
- - [x] sections have a line separator (#8121)
- - [x] category description is centered and larger (#8121)
- - [x] bold audit group title with inline description (#8222 #8592)
- - [x] remove audit result numbering (#8222)
- - [x] change audit count to be grouped with title (#8222)
- [x] move score icons to the left (in metrics, opportunities, audit results) (#8222)
- [x] colors (#8222)
- [x] icons
- - [x] use simple shapes for score icons (#8222)
- - [x] green PWA icons (#8532)
- - [x] remove icons from audit group headers (#8329)
- - [ ] doublecheck gray circle for resource summary audit (all informative)
- [ ] fonts
- [x] metric description toggle
- [x] whitespace (#8531, #8591)
- [x] remove old lighthouse header (#8300)
- [ ] sticky topbar
- - [x] LH icon in top left (#8300)
- - [x] followed by url (#8300)
- - [x] score gauge sticky header
- - - [x] appears when scrolling past score scale (#8524)
- - - [x] current category in view is underlined (#8524)
- - - [x] clicking category scrolls to it (#8720)
- [ ] dark mode 
- - [x] styles (#8425)
- - [ ] persist
- [ ] clients
- - [ ] Devtools
- - [x] PSI
- [x] runtime settings (#8229)
- - [x] alternating background colors for rows
- - [x] style like a table
- [x] browser compatibility (#8653)
- - [x] stable Firefox
- - [x] stable Safari
- - [x] Edge 17/18
- [ ] cleanup

Likely punting till after I/O

- [ ] logo
- [ ] run config
- [ ] error messaging
- [x] fireworks (#8660)
- [ ] full bleed thumbnail images

Feel free to edit with anything else.

**Comment by Hoten** [comment]
> Likely punting till after I/O
> > logo

@paulirish hmmmm i did kill it already. ok?

**Comment by mattzeunert** [comment]
Seems like [adding `word-break: break-word;`](https://github.com/GoogleChrome/lighthouse/pull/8229/files#diff-f8838d243bb796c2800f4eceab80b7ddR226) is causing a layout issue in the tap targets table: 

![Screenshot 2019-04-25 at 14 38 32](https://user-images.githubusercontent.com/1303660/56739993-ec952300-6767-11e9-91c7-558678f4a055.png)

**Comment by warrengm** [comment]
I've noticed word wrapping issues in the failure title.

For example: 
![r7VRZU8gr5m](https://user-images.githubusercontent.com/5326842/58344607-2e2af380-7e24-11e9-906c-ae35ecd6eb16.png)

**Comment by Hoten** [comment]
> I've noticed word wrapping issues in the failure title.
> 
> For example:


Fixed w/ #9030, will land in next release.

**Comment by brendankenny** [comment]
I don't think we're tracking this issue anymore (and we have separate issues for remaining report problems), so I'm going to close. @connorjclark feel free to correct me if I'm wrong :)
