### ISSUE TITLE
Bad character in theme color in manifest makes lighthouse report that no manifest exists

### ISSUE THREAD

**Issue by LuzianW** [GoogleChrome/lighthouse#819]
I accidentally had a double '#' in the `theme_color` attribute of the webapp manifest. 

Lighthouse then reported that no manifest exists, instead of reporting a bad (or undefined) theme color.

Sample bad manifest that caused the problem:
```
{
	"short_name": "app name",
	"name": "app name",
	"icons": [{
		"src": "icon-tiny.png",
		"sizes": "20x20",
		"type": "image/png"
	}, {
		"src": "icon-medium.png",
		"sizes": "144x144",
		"type": "image/png"
	}, {
		"src": "icon-big.png",
		"sizes": "200x200",
		"type": "image/png"
	}],
	"background_color": "#374466",
	"theme_color": "##66ccdd",
	"start_url": "/index.html",
	"display": "standalone"
}
```
(json is valid, https://manifest-validator.appspot.com/ reports theme_color as undefined)

**Comment by brendankenny** [comment]
Hmm, I'm not able to replicate the problem. Do you have a public example that I can look at that demonstrates this?

- [manifest-parser.js](https://github.com/GoogleChrome/lighthouse/blob/88cad9e62b84a8efb2b92278304ebcfa0963f7fc/lighthouse-core/lib/manifest-parser.js) correctly parses the above manifest, reporting `theme_color` as `undefined`.
- When I do a full run of Lighthouse with a manifest `theme_color` of `'##66ccdd'`, I get
<img width="612" alt="screen shot 2016-10-24 at 09 11 45" src="https://cloud.githubusercontent.com/assets/316891/19653645/2265735e-99ca-11e6-8696-ef901ed039f0.png">
which is what I would expect. Maybe there is some other issue at work with the page you're testing?

**Comment by LuzianW** [comment]
I don't have a public one right now, but consistently get the same result locally (manifest exists=✘ with extra '#', manifest exists=✔ when removing the extra '#').

I'm running Lighthouse extension on Chrome (Version 54.0.2840.71) on Ubuntu, maybe the problem is specific to my system/environment?

I could redeploy the 'bad' version if it helps...

**Comment by brendankenny** [comment]
> I'm running Lighthouse extension (Version: 1.1.6) on Chrome (Version 54.0.2840.71) on Ubuntu, maybe the problem is specific to my system/environment?

It's possible, but I'm not able to recreate the problem in the extension, either.

> I could redeploy the 'bad' version if it helps...

That would be helpful, but you definitely shouldn't break a live site just for this :) Is it possible to push a simple html page + manifest somewhere, see if it still causes this issue for you, and post a link here?

**Comment by LuzianW** [comment]
- extra '#' in "theme_color", Lighthouse reports no manifest https://stage.kittysplit.com/webapp-test1/index.html
- fixed "theme_color", Lighthouse reports manifest ok https://stage.kittysplit.com/webapp-test2/index.html

These two are exactly the same, except for the extra character '#' in "theme_color" in the **first** manifest) (https://stage.kittysplit.com/webapp-test1/manifest.json vs https://stage.kittysplit.com/webapp-test2/manifest.json )

2 generated reports attached:
- [lighthouse_webapp-test1_index.pdf](https://github.com/GoogleChrome/lighthouse/files/548632/lighthouse_webapp-test1_index.pdf)
- [lighthouse_webapp-test2_index.pdf](https://github.com/GoogleChrome/lighthouse/files/548633/lighthouse_webapp-test2_index.pdf)

**Comment by brendankenny** [comment]
Thanks for those!

I can confirm the issue...looks like we're giving up at first error [here](https://github.com/GoogleChrome/lighthouse/blob/88cad9e62b84a8efb2b92278304ebcfa0963f7fc/lighthouse-core/gather/gatherers/manifest.js#L41). Not sure when the debugger protocol started returning parsing errors in that array, but should be an easy fix.
