### ISSUE TITLE
Lack of transparency about Page Speed Insights errors

### ISSUE THREAD

**Issue by timker** [GoogleChrome/lighthouse#8195]
**Summary**
Every second post in the PSI google group is about backend errors
https://groups.google.com/forum/#!forum/pagespeed-insights-discuss

Unfortunately there is no guidance on why this is happening

Some people guess the the target sites are slow...
web.dev does not seem to have this problem so maybe it's the pwa step?

Whatever it is, It would be great to post that you are/are not working on the issue(s)

**Comment by exterkamp** [comment]
Hi, thanks for making a gh issue for this.  This is a known issue, and we are looking at options of how to better expose errors and maybe issue some better guidance.

@paulirish I know that PSI error guidance and reporting has been on my wish list for awhile, can we get it prioritized? :smile:

**Comment by exterkamp** [comment]
I'm going to de-duplicate this issue and fold into #9137 and hopefully address these concerns there!  Comment there, or reopen this if you want to.
