### ISSUE TITLE
Add to Desktop Not Showing in Manifest Section

### ISSUE THREAD

**Issue by Hoodlum-Z** [GoogleChrome/lighthouse#8196]
In Lighthouse audit, I'm scoring full marks for PWA 3/3,  3/3,  6/6, but can't see the add-to-desktop button in the manifest section of Lighthouse. (I've seen this on various Google screenshots.)

Has it been removed or am I missing something?

I've read about listening for firing events and prompting people, then read on the contrary that PWAs will decide when to offer the feature so I'm a bit confused about the current situation.

The sites that I've put a demo on with a basic service worker are:
- https://sonicseo.co.uk/
- https://gossiplolly.com/
- https://parallaxsite.com/

![Parallax-PWA-Audit-Lighthouse](https://user-images.githubusercontent.com/5571357/55994834-b9a05900-5caa-11e9-8877-a844382aeef2.jpg)

Thanks in advance for any advice.

**Comment by patrickhulce** [comment]
Here's what I see on latest Lighthouse


sonicseo - passing all, gets icon 👍 
![image](https://user-images.githubusercontent.com/2301202/55995364-ee47ec80-5c79-11e9-88d2-9e145c632f5d.png)

gossiplolly - failing start URL offline, gets partial icon 👍 
![image](https://user-images.githubusercontent.com/2301202/55995419-091a6100-5c7a-11e9-8b94-ac008afa4c3e.png)

parallaxsite - failing start URL offline, gets partial icon 👍 
![image](https://user-images.githubusercontent.com/2301202/55995496-4252d100-5c7a-11e9-9343-f3723706fee7.png)


Everything seems to be working as expected icon-wise. Are you seeing something else? Your screenshot does not include the PWA section in it, so it's hard to tell.

**Comment by Hoodlum-Z** [comment]
Thanks for the swift reply, Patrick. The first screen shot that I added had a perfect score on the PWA section. However, I've noticed that sometimes you can run a site through numerous times and get slightly different results. 

Most of the time all my icons are getting picked up. 

I've posted this at a bad time, typically, because I've been having issues with my sites - turned too many security features on and locked myself out of my sites and now some pages are missing/not showing correctly. Hopefully it's just a caching issues - I've got a backup anyway. Embarrassing when I've linked to them all on here. Such is life, eh? :)

This image contains the Add to Homescreen link I am talking about.

![Add-to-Homescreen](https://user-images.githubusercontent.com/5571357/55997638-1869d080-5cb3-11e9-9c1d-303a5717f30f.PNG)

**Comment by Hoodlum-Z** [comment]
@patrickhulce the thing is, green lights and high scores are nice, but they don't mean much in the real world. It's speed and actions that matter.

Have you managed to convert any web pages or build a PWA yourself yet?

**Comment by patrickhulce** [comment]
> This image contains the Add to Homescreen link I am talking about.

That was removed from Chrome in December and replaced with the installability warnings which is only visible when there are issues that would prevent the homescreen prompt from triggering for a real user (see https://chromium-review.googlesource.com/c/chromium/src/+/1370371). 

Also note, that is not Lighthouse. Lighthouse is what can be seen in the "Audits" tab in DevTools. The Application tab, including the Manifest section, is just part of DevTools. In the future, if you don't like the way something is handled in DevTools, please use the Chromium issue tracker and not this repo.
