### ISSUE TITLE
The README should say what this project is for.

### ISSUE THREAD

**Issue by jyasskin** [GoogleChrome/lighthouse#82]
Right now it looks like it might be an auditing tool?

**Comment by paulirish** [comment]
Yeah sorry Jeffrey.

Right now it's lacking details on the readme so we can stay in quiet mode a bit longer. Just trying to manage expectations.

Googlers can read the details at https://goto.google.com/project-lighthouse 

For the moment, everyone else will have to build the app/extension to get a feel for the project. Soon we'll have a proper description of the project available.
