### ISSUE TITLE
Calibration for cpu throttling

### ISSUE THREAD

**Issue by wardpeet** [GoogleChrome/lighthouse#820]
When running lighthouse in emulation mode we have static values for cpu throttling and network throttling.
CPU throttling has the biggest bottleneck because it is dependend on system hardware. (5x slower)

It would be nice if we could add a calibration service that we can compare our results too.

Related issues:
[Issue #33](https://github.com/GoogleChrome/lighthouse/issues/33)
[PR #747](https://github.com/GoogleChrome/lighthouse/pull/747)

**Comment by pedro93** [comment]
Hello,

Just wanted to say something regarding calibration runs. I have been doing performance audits at work and noticed a large variability on performance-related metrics between "simulated runs" and real devices. 

As a suggestion/idea perhaps it would be best to have something like 10 mobile simulated lighthouse runs and compare the average with 10 real mobile devices runs using the remote debugging protocol (if a user has one) and adjust the throttling rates (both CPU and network) to each user's hardware?

At least at my work, our mid level device is not a nexus 5X and it would be great if we could adjust the throttling to our case (without needing the device after the calibration) and even pass those values to our CD servers for continuous performance analysis.

**Comment by paulirish** [comment]
@pedro93 just curious.. is it possible to share your data? privately would be fine.

we're also building out some tools of our own to measure the variability but it's not operational just yet.

Your idea is right on point, by the way. :)

**Comment by paulirish** [comment]
research by @wwwillchen  indicated that this isn't necessary.  http://go/devtools-cpu-throttling

**Comment by paulirish** [comment]
Somewhat related: speedcurve is using some estimates for their CPU throttling presets. The data is based off [Geekbench](https://www.geekbench.com/) values, which may or may not represent browser performance. :) http://support.speedcurve.com/synthetic-settings/cpu-throttle

**Comment by paulirish** [comment]
We now think it's worthwhile to do this for lantern runs.
Breaking this out from #4521

**Comment by patrickhulce** [comment]
This was deeply investigated and concluded with #9085. See that issue for more discussion.
