### ISSUE TITLE
Lazyload images

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#8211]
Hi
web.dev report that images must be lazyloaded but images are allways in the viewport and don´t need to be lazyloaded. With LH in Chrome these images are not reported.
Url to test: https://intersindicalrm.org/
Reported images:
https://intersindicalrm.org/wp-content/uploads/2016/01/xHeaderinter.png.pagespeed.ic.xgDv2cQfEw.webp
https://intersindicalrm.org/wp-content/uploads/2018/10/xVCongreso1.jpg.pagespeed.ic.Yea4QqDleN.webp

**Comment by patrickhulce** [comment]
Thanks for filing @Lofesa! I can reproduce and confirm this is a bug.

A tricky one to nail down but a fix is one the way :)
