### ISSUE TITLE
Feature request(report): Clicking on category or group title in report expands/collapses all child audits.

### ISSUE THREAD

**Issue by jburger424** [GoogleChrome/lighthouse#8214]
**Feature request summary**
I propose that when clicking a category or group title, all child audits are expanded or collapsed. Possible behavior could be to always expand, except for case where all audits are already expanded, in which case all could be collapsed.

I would be happy to implement this feature.

**What is the motivation or use case for changing this?**
If you are interested in deeply exploring a category or group, it is tedious to click to expand each individual audit. An option to do this more quickly would be appreciated.

**Comment by paulirish** [comment]
Hmmm! tbh, We're not sure about adding UI in the report for expanding each group or category. 

But... We currently have these in the menu:

![image](https://user-images.githubusercontent.com/39191/114467063-2d2d1780-9b9e-11eb-952c-2325d8de0c1c.png)

We could change these to be 

* Print report
* Expand all

and probably that second bullet point satisfies your request?

**Comment by jburger424** [comment]
@paulirish That seems to make sense to me!

**Comment by connorjclark** [comment]
Seems like we don't need this. Please comment if that's not right :)
