### ISSUE TITLE
Adopt new Page.getInstallabilityErrors method for PWA checks

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#8223]
https://chromium-review.googlesource.com/c/chromium/src/+/1560533
https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getInstallabilityErrors

It tests against the real implementation, so we won't have a gap.
https://cs.chromium.org/chromium/src/chrome/browser/installable/installable_logging.cc?l=15-57

This also means we can probably drop manifest parser, manifest-values, etc. 
Their offline check is a little different though. 

The strings returned are hardcoded english.. but then again so are our current strings. ;)

**Comment by Hoten** [comment]
Won't be able to drop manifest-values completely, as many checks aren't handled via the protocol. Example - background color, theme color, icons >= 512px.

**Comment by connorjclark** [comment]
see: https://docs.google.com/document/d/1vRjvfLRm7IgqTDf_wza01UJ9nTo-tbaSfY5wlVZAV4c/edit#

**Comment by paulirish** [comment]
now a dupe of #10515
