### ISSUE TITLE
Lighthouse report detecting service worker response as http 1.1 .

### ISSUE THREAD

**Issue by smileycreations15** [GoogleChrome/lighthouse#8249]
#### Provide the steps to reproduce
1. Run Lighthouse on https://smileycreations15.com while <kbd>Clear storage</kbd> is unchecked.
2. Wait for the audit to finish... (throttling applied or simulated)

#### What is the current behavior?
Detects requests are from HTTP 1.1 because the service worker sends the response instead of the network.

#### What is the expected behavior?
The responses from the service worker should be ignored.

#### Environment Information
* Affected Channels: Devtools
* Lighthouse version: 4.0.0 (Chrome Version 73.0.3683.103 (Official Build) (64-bit))
* Node.js version: v11.8.0
* Operating System: MacOS Mojave

**Related issues**
#7158

**Comment by patrickhulce** [comment]
Thanks @smileycreations15 you already found the correct related issue which has been closed because it's fixed :)

**Comment by smileycreations15** [comment]
Duplicate of #7158
