### ISSUE TITLE
Allow disabling Nexus 5X simulation when using extension

### ISSUE THREAD

**Issue by Caffeinix** [GoogleChrome/lighthouse#828]
In the Lighthouse CLI, you can pass `--mobile=false` to stop Lighthouse from emulating a Nexus 5X when it connects.  There is no analogous option in the Chrome extension.  This would be a very useful feature to expose there.

**Comment by wardpeet** [comment]
@paulirish perhaps we need to have a look at the UI of the extension to have a cleaner settings panel ^^

**Comment by Caffeinix** [comment]
Any update on this?  It looks like the Settings panel UI has changed since I filed this, but there's still no way to pass this option.

**Comment by szeck87** [comment]
I'm giving this a try. I forked and created a branch to learn the code for Lighthouse and will see if I can do this.

**Comment by wardpeet** [comment]
@szeck87 at the moment we have no plans to update the settings panel for now.
