### ISSUE TITLE
aXe evaluateAsync timeout

### ISSUE THREAD

**Issue by NithinGCC** [GoogleChrome/lighthouse#8287]
Hi,
For one of our pages https://www.blinds.com/p/blindscom-2-deluxe-wood-blind/503440 we are seeing that the lighthouse is having issues with accessibility and SEO.

![image](https://user-images.githubusercontent.com/43421891/56156121-2a34c780-5f82-11e9-9d47-5c26c2b05680.png)

"Document doesn't have a <title> element" error is shown but we do have the title tag in the DOM. Also, other SEO tools are seeing the page and tags properly.

I read in some other threads about a possible Lighthouse-axe integration issue.
Would you be able to direct me here please?

Thanks,
Nithin

**Comment by patrickhulce** [comment]
Thanks for filing @NithinGCC yes this is an issue with axe failing on that page!

For future reference, when the audit has the "Error!" label it means that some analyze in Lighthouse failed/errored and not the page, if you hover you should see a more descriptive error message. This is also what the `?` in the score is attempting to communicate :)

![image](https://user-images.githubusercontent.com/2301202/56157101-4b96b300-5f84-11e9-8f36-f53b3044f79d.png)


Upstream issue that @NithinGCC kindly filed is https://github.com/dequelabs/axe-core/issues/1497

**Comment by Hoten** [comment]
In the meantime, LH 3.2.1 will work.

**Comment by Hoten** [comment]
Should we add a rather complex page to audit for accessibility to our smoke tests, so that we catch perf regressions in axe?

**Comment by NithinGCC** [comment]
> In the meantime, I know LH 3.2.1 and 4.1 will work.

How do I go back to 4.1? My team is using the Audit option with in Chrome Dev tools

**Comment by Hoten** [comment]
Use [PSI](https://developers.google.com/speed/pagespeed/insights/) or the Node CLI.

**Comment by NithinGCC** [comment]
Thank you. 
Just curios on which version PSI is on? 3.2 or 4.1?

**Comment by Hoten** [comment]
4.1 as of now. I recommend using the Node CLI, as PSI can upgrade without notice.

**Comment by NithinGCC** [comment]
Got it. Thank you. Will you be able to include this fix in your next Lighthouse release? Will be helpful if you have a timeline to share.

**Comment by NithinGCC** [comment]
Update: I tired with 4.1 using Node CLI and it gives me the same error
with 3.2.1 it works

**Comment by NithinGCC** [comment]
Is axe's accessibility time out causing the issue? just wondering what is the breaking change from 3.2.1 to 4.1

**Comment by patrickhulce** [comment]
@NithinGCC yes it's an issue with an axe update, we updated our axe integration between those versions.

**Comment by NithinGCC** [comment]
Thank you for the responses. 
Is this issue causing inconsistencies in PSI as well? 
We are using PSI to to base line our application performance metrics and we've been getting inconsistent results. 
I've seen this reported by a lot of folks (two of them below)
https://github.com/GoogleChrome/lighthouse/issues/6708
https://github.com/GoogleChrome/lighthouse/issues/7348

**Comment by brendankenny** [comment]
axe should be considerably faster now.

For the PSI issues, see #6708.
