### ISSUE TITLE
artifact: fetch manifest based on triggered network request

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#83]
Calling [`requestAppBanner`](https://chromedevtools.github.io/debugger-protocol-viewer/Page/#method-requestAppBanner) will fetch the manifest, which we can pick up in the network requests record. 

This avoids the DOM dance and make sure we're testing the same manifest that Chrome does.

for now you need `--enable-add-to-shelf` for this to work

**Comment by paulirish** [comment]
Once https://codereview.chromium.org/1835063002/ lands, enable-add-to-shelf will not be required.
Star https://bugs.chromium.org/p/chromium/issues/detail?id=540491 for updates.

In the meantime, we can force the flag for node, but not for extension.

**Comment by paulirish** [comment]
This will also mean we can clean up the depedency on `request` and the localized requires here

![image](https://cloud.githubusercontent.com/assets/39191/14093640/300146b6-f504-11e5-84a1-a84a23191609.png)

**Comment by paulirish** [comment]
Okay another bug we'll get resolved...  on https://operasoftware.github.io/pwa-list/ things fail because it's in a subfolder and our browser fetching assumes manifest is at domain root.

There's a fix for it but I think I'd rather rely on the real thing.

![image](https://cloud.githubusercontent.com/assets/39191/14131756/31f3858e-f5f3-11e5-8647-d47849f763a7.png)

**Comment by paulirish** [comment]
@brendankenny when do you think you'll have a PR up for this?

**Comment by brendankenny** [comment]
Aiming for tomorrow

**Comment by paulirish** [comment]
@brendankenny sounds good thank ya

**Comment by brendankenny** [comment]
so, one additional development here seems to be that in Canary, if you have `Add to shelf` enabled in about:flags, Chrome now fetches the manifest on navigation. Is this coming sooner than we expected?

**Comment by paulirish** [comment]
try https://jakearchibald.github.io/svgomg/ with your PR. i get invalid JSON errors with the extension currently.
