### ISSUE TITLE
ublock audit

### ISSUE THREAD

**Issue by tidbitsnbytes** [GoogleChrome/lighthouse#8309]
#### Provide the steps to reproduce
1. Run LH on <affected url>

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by tidbitsnbytes** [comment]
I have an SLQ injection and had entered code to seek out and destroy it but I am still getting redirected and on loop. I opened LH to try and find where the issue is but am unsuccessful. Any advice? I am going to try "Angry IP Scanner", Metasploit, and/or NMAP. What would you suggest I do. A copied url from the developer mode console is below. 

chrome-extension://maafkmigbnfgoknpahhpcpccchemkhih/asset-viewer.html?u

![image](https://user-images.githubusercontent.com/48900830/56184255-aeb13580-5fd6-11e9-94f9-f6be30e5f86f.png)

![image](https://user-images.githubusercontent.com/48900830/56184298-cf798b00-5fd6-11e9-89bb-f0202e0c8efa.png)

![image](https://user-images.githubusercontent.com/48900830/56184450-47e04c00-5fd7-11e9-9c16-3f45d7016978.png)

**Comment by patrickhulce** [comment]
That looks like AVG Adblock is just trying to pass off uBlock as its own with some modifications. I would just uninstall it and use real uBlock.

This isn't the best place for advice like that though, try StackExchange, or AVG forums.
