### ISSUE TITLE
smoke tests often time out on travis

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#833]
Quite common to see Travis jobs go for ~10 minutes, at which point Travis kills the run. More end-to-end tests with smokehouse and now four versions of node increases the chance of these flakey tests.

**Comment by addyosmani** [comment]
Travis will timeout if a job produces no logged output for 10m (perhaps there's something we could do to log progress/a thing to keep it alive?). Jobs otherwise get killed if they take longer than 50m on travis-ci.org or on OSX infra.

**Comment by brendankenny** [comment]
With some initial expanded logging, it's clear this is happening somewhere after Chrome has started up but Lighthouse has not begun:

![screen shot 2016-10-26 at 16 36 18](https://cloud.githubusercontent.com/assets/316891/19749014/7a2fadf8-9b9a-11e6-85bb-7cc749d2a0f4.png)

(and then it times out)

**Comment by samccone** [comment]
I think we can add a MAX_CONNECTION_TIMEOUT and then simply retry :)

thoughts?

**Comment by brendankenny** [comment]
> thoughts?

I want to know why this is happening :)

**Comment by brendankenny** [comment]
but yeah, I'm fine with that too

**Comment by brendankenny** [comment]
so, the deepest cause I've found so far is that the http GET request we do to [get the URL for the web socket debugger connection](https://github.com/GoogleChrome/lighthouse/blob/c4a303973cee0b7afb901625b1a4991e3531c68a/lighthouse-core/gather/connections/cri.js#L51) sometimes simply never gets a response.

It's not clear to me yet why this only seems to happen on Travis, and why [the connection  made here](https://github.com/GoogleChrome/lighthouse/blob/c4a303973cee0b7afb901625b1a4991e3531c68a/lighthouse-cli/chrome-launcher.ts#L147) is successful while the later GET request is not.

Simple work around for now: we can add a `timeout` to the request and `reject()` if it's called. 

- Would we rather have a quick failure and set up some kind of Travis retry in that case?
- Alternatively, some kind of fancy thing to re-run smokehouse in the case of that kind of failure?

**Comment by brendankenny** [comment]
and if anyone has any ideas about why that request doesn't work (but also doesn't fail) and if there's anything we can do to fix it, please chime in :)
