### ISSUE TITLE
Offline Page Doesn’t Works while Lighthouse shows 100%

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [GoogleChrome/lighthouse#8349]
**Summary**

Offline page for staging.bhadoomail.com is not working while the lighthouse shows that the PWA is 100 percent correct and installed.

**Comment by patrickhulce** [comment]
Thanks so much for filing! This is the same root issue as #709 (and related issues like #4556 and #2725). We finally have some of the internal architecture pieces in place to make that happen, so it should be coming soonish :)
