### ISSUE TITLE
Better inform users about CPU throttling being enabled

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#836]
Perhaps via `log.verbose` per @brendankenny. Trying to enable this via the API atm and it's a little unclear how to tell if it's enabled.

**Comment by brendankenny** [comment]
#784 does add this info to the report/json output, so at least it's recorded there. It would likely still be helpful in the log, though.

**Comment by wardpeet** [comment]
would be handy if we could ask chrome what emulations it has going? With the 784 PR I save it.. But rather just have a gatherer do it for me.

I'll add some logging to that pr in cli too. Where do you want to see it? at the start of lighthouse?

**Comment by brendankenny** [comment]
I don't think it should be too complicated. The emulation options will be on the `options` object from the CLI. `runner` will have access to it, where it can then write it to the final results object (which can then be exposed in the report).

**Comment by wardpeet** [comment]
just showing network Throttling: on/off for instance

**Comment by addyosmani** [comment]
> The emulation options will be on the options object from the CLI. runner will have access to it, where it can then write it to the final results object (which can then be exposed in the report).

This seems reasonable and I appreciate the reminder about the info being available in the JSON output (had not noticed that before).

**Comment by peter-mouland** [comment]
I've just started to look into this tool and noticed the option to disable throttling.  I assume this means it is enabled by default.  

Could this throttling information be added to the html output somewhere?  I did a search for it in the JSON output (as mentioned above) but could not find it, are you sure it is there?

thanks

**Comment by patrickhulce** [comment]
done
