### ISSUE TITLE
Stuck on status Initializing 

### ISSUE THREAD

**Issue by jstrating** [GoogleChrome/lighthouse#837]
I’m using Lighthouse cli on OSX to test my PWA from command line.  Running version  1.1.6. After using `lighthouse [url] ` it gets stuck on `status Initializing… +x ms`. I've tried multiple url's including https://www.google.com, but no succes. The chrome extension however works fine.

The log looks like this:
```
Launching Chrome...
created /var/folders/0g/_9tqwjd14mzg1sx_d6_lb20h0000gn/T/lighthouse.XXXXXXX.9Uik2AB7
Chrome running with pid = 1199
Waiting for browser.....✓
  status Initializing… +0ms
```

**Comment by wardpeet** [comment]
are you using chrome canary?

**Comment by jstrating** [comment]
Right now I am using 56.0.2901.0 canary with lighthouse.

**Comment by wardpeet** [comment]
I have a fix ready for ya :)

**Comment by paulirish** [comment]
837 is totes reasonable to me, but I'm a bit surprised it fixes this issue. You sure? :)

**Comment by wardpeet** [comment]
Yes I have the same issue on my canary.

**Comment by jstrating** [comment]
Sadly, it didn't fix the issue for me.
