### ISSUE TITLE
DBW: <link rel=stylesheet> in head will block first paint 

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#838]
Per @samccone: https://twitter.com/samccone/status/791665852454100997

> A friendly reminder that any `<link rel="stylesheet">` in your `<head>` will block first paint 🎨 until _all_ of them are done downloading.

We could probably write a DBW audit to remind folks to move their stylesheets to the document `<body>` so the browser can still paint while fetching.

**Comment by TheLarkInn** [comment]
Awwww yissssss.

**Comment by giovanni0918** [comment]
Yeah, buddy. 👌

**Comment by samccone** [comment]
Detect num of stylesheets and overall size of them + time to download all of them.

Then complain if it is over a threshold.

**Comment by ebidel** [comment]
Complaining about _any_ stylesheets in the head (regardless of size and download time) would be good too.

Suggested:

1. Find stylesheets in `<head>`
2. Complain that they block FP and say by how much: "`<link>` blocked first paint by X ms". Where X is the time it took to download the stylesheets.

This audit could also be extended to HTML Imports `<link rel="import">` that do not have the `async` attribute. Those block FP too.

**Comment by igrigorik** [comment]
FWIW, not all stylesheets block rendering.. Only stylesheets that match. 

Old, but relevant: https://www.igvita.com/2012/06/14/debunking-responsive-css-performance-myths/

**Comment by TheLarkInn** [comment]
Is there maybe a 'budget' or max size that can be acceptable in the head for a stylesheet that would be _ok_? If so, maybe this is also taken into consideration.

**Comment by ebidel** [comment]
Also, we should be considering all `<link>` that block rendering. Not just the ones in `<head>`. Yea?

**Comment by igrigorik** [comment]
@ebidel yeah. 

A couple of relevant resources:
- https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css (overview)
- https://developers.google.com/web/fundamentals/performance/critical-rendering-path/optimizing-critical-rendering-path (minimize critical bytes)

@TheLarkInn I wouldn't allocate a CSS only budget, what's important is the total byte size of critical resources (measured in number of RTTs). Ideally, your critical bytes fit into a single RTT, which is.. <14KB.

**Comment by brendankenny** [comment]
@ebidel is this covered now?

**Comment by ebidel** [comment]
Yep.
