### ISSUE TITLE
SEO Score not affected by img without alt attribute

### ISSUE THREAD

**Issue by andreabisello** [GoogleChrome/lighthouse#8393]
#### Provide the steps to reproduce
1. Run LH on https://www.w3schools.com/code/tryit.asp?filename=G37S02M71XEE . This page contains this code

```
<!DOCTYPE html>
<html>
<body>

<p>
An image that is a link:
<a href="https://www.w3schools.com">
<img src="smiley.gif" width="42" height="42" border="0">
</a>
</p>

</body>
</html>
```

2. Search for SEO score
3. No warning about the missing alt attribute 

#### What is the current behavior?

LH say nothing about img without alt tag

#### What is the expected behavior?

LH should warn about img without alt tag . Google in this document https://support.google.com/webmasters/answer/114016?hl=en says to use descriptive alt text

#### Environment Information
* Affected Channels: DevTools 
* Lighthouse version: 4.0.0
* Node.js version: 6.4.1
* Operating System: updated windows 10

**Comment by patrickhulce** [comment]
Thanks @andreabisello good catch! We flag this in accessibility but not SEO. 

cc @rviscomi / @AVGP for their blessing

**Comment by AVGP** [comment]
Yes, very good catch!
