### ISSUE TITLE
Enable text compression - false positive

### ISSUE THREAD

**Issue by LlamaFarma** [GoogleChrome/lighthouse#8398]
Running Lighthouse on my webpage in Chrome, I get a performance score of 16 and it falsely reports text compression as not being enabled. 

If I run Lighthouse using Brave browser (chromium based) on the same PC, I get a performance score of 64 and it correctly doesn't flag text compression as an issue. 

I've run the tool using Devtools and also the Chrome extension and get the same result. 

I'm using Chrome 73 on Windows 10 64 bit. 
Lighthouse version 4.0.0

Thanks

**Comment by patrickhulce** [comment]
Are you willing to share your URL @LlamaFarma? We can't do much without a repro case.

**Comment by LlamaFarma** [comment]
Hi Patrick. Thanks for your reply. The site is www.simcardgeek.com

**Comment by patrickhulce** [comment]
Hm, I'm not seeing the described behavior in latest Lighthouse in Devtools, CLI, or Extension.

![image](https://user-images.githubusercontent.com/2301202/56903067-32e8cb80-6a61-11e9-8baf-b1bf3a15c501.png)

**Comment by brendankenny** [comment]
hopefully this was resolved. Closing, but can reopen if you're still seeing a problem.
