### ISSUE TITLE
[id] attributes on the page are not unique and noscript tag

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#8399]
Hi
I have a web that run the [pagespeed module](https://github.com/apache/incubator-pagespeed-mod) , These module has a filter to inline the css critical path and delay the load of all other css stuff.
To make this delay, the module put all css stuff (css files and inlined css) between noscript tags with a class (psa_add_styles) and the result is that the css elements with ID appear 2 times.
Can it be considered that the IDs are duplicated when they appear between noscript labels?
URL to test https://intersindicalrm.org/
This fails on LH in Chrome and in web.dev.

Thx in advance

**Comment by patrickhulce** [comment]
Thanks for filing @Lofesa but Lighthouse seems to be accurate here.

I see two copies of this ID on that page outside of `<noscript>` regions.

![image](https://user-images.githubusercontent.com/2301202/56372726-280e7b00-61c5-11e9-8a18-92a40eb871ae.png)

![image](https://user-images.githubusercontent.com/2301202/56372746-3492d380-61c5-11e9-9b65-0dec01e68dcf.png)

**Comment by Lofesa** [comment]
Hi
Thx you @patrickhulce for the time....
Is a pagespeed module fail, it must remove all inlined styles and put it on a nonscript tag and then inject the critical css path and delay the load of the rest off css files and inlined styles, but in this case it make a copy of the inlined css in the noscript tag and don´t delete the original so it get 2 inlined styles, the original and the delayed. I will fire a bug to the pagespeed module team.
Again, thx you
