### ISSUE TITLE
first run experience with TS cli

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#840]
@pavelfeldman attempted to demo lighthouse yesterday and was thwarted as `tsc` wasn't run.

Probably a few options... run `tsc` in a postinstall hook.. or probably better.. a bootstrapping script which will run the ts compiler if the CLI .js files aren't already present.

@samccone what do you think?

**Comment by samccone** [comment]
I added a readme not**e** here 
https://github.com/GoogleChrome/lighthouse/commit/81e2774d4fbbb5d74fdc2be0caa957f3c1abc1b2

A bootstrap script or a guard around the require bit in the code that would tell you that you need to compile is fine. -1 to postinstall script as it will impact end users.

This is a dev only problem right now and will never impact users directly. So whatever you want to do is cool.

**Comment by paulirish** [comment]
A guard telling you to compile sgtm.
