### ISSUE TITLE
Desktop audit fails for https://app.ft.com/index_page/home

### ISSUE THREAD

**Issue by petele** [GoogleChrome/lighthouse#8406]
#### Provide the steps to reproduce
1. Run a DESKTOP audit with LH on https://app.ft.com/index_page/home

#### What is the current behavior?
Fails with error: 

> Ah, sorry! We ran into an error.
>
> Try to navigate to the URL in a fresh Chrome profile without any other tabs or extensions open and try again."

Page seems to be stopped at the JavaScript disabled state.

#### What is the expected behavior?
Lighthouse to finish ;)

#### Environment Information
* Affected Channels: DevTools in Chrome for Mac Version 74.0.3729.75 (Official Build) beta (64-bit)

**Comment by patrickhulce** [comment]
Thanks Pete! I can repro this too :)

It appears this is the extension HTTP failure manifesting in DevTools. We're failing with INSECURE_DOCUMENT_REQUEST on the HTTP redirect pass.

![image](https://user-images.githubusercontent.com/2301202/56373252-34470800-61c6-11e9-81c6-7363569efa92.png)

**Comment by patrickhulce** [comment]
#8338 *should* fix this

**Comment by exterkamp** [comment]
This seems fixed to me! Reopen if it is still affecting you!
