### ISSUE TITLE
CLI: dbw audits cause "converting circular structure" error when using --output=json

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#841]
Running json output on the dbw config yields circular reference errors:

<img width="867" alt="screen shot 2016-10-27 at 1 46 58 pm" src="https://cloud.githubusercontent.com/assets/238208/19784847/2b838118-9c4c-11e6-8799-2f51ebe6fffe.png">

`npm run start -- --config-path=lighthouse-core/config/dobetterweb.json --disable-device-
emulation --disable-cpu-throttling --disable-network-throttling --output=json URL`

@paulirish didn't you fix this in the .js days?

**Comment by brendankenny** [comment]
what URL are you seeing this on? I don't see this on master with `node lighthouse-cli/index.js --config-path=lighthouse-core/config/dobetterweb.json --disable-device-emulation --disable-cpu-throttling --disable-network-throttling --output=json https://www.chromestatus.com/features`

**Comment by brendankenny** [comment]
oh, https://example.com repros

**Comment by ebidel** [comment]
Interesting. Yea I'm using a localhost url.

I blame .ts.

**Comment by brendankenny** [comment]
disabling the `uses-http2` audit fixes it, so looks like the problem is there

**Comment by paulirish** [comment]
Looks like there's a networkRequest object in the extendedInfo. netrequests have a lot of properties and end up pointing at much of the WebInspector namespace. So you'll probably want to sanitize the request so something whitelisted.

**Comment by paulirish** [comment]
![image](https://cloud.githubusercontent.com/assets/39191/19785721/598b9a20-9c4f-11e6-8ea6-775d5053d16d.png)
