### ISSUE TITLE
Deprecation warning: nomnom@1.8.1 no longer supported

### ISSUE THREAD

**Issue by dustinsoftware** [GoogleChrome/lighthouse#8420]
I'm seeing this warning when running `yarn install`:

```
warning lighthouse > jsonlint-mod > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
```

Looks like `jsonlint-mod` was added as a dependency roughly 10 days ago: https://github.com/GoogleChrome/lighthouse/commit/3f15b67d23735aac4a9796846480c6cd43cb0e47#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R145

The warning appears to be coming directly from NPM, which flagged the package as unmaintained: https://www.npmjs.com/package/nomnom

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 4.3.0
* Node.js version: 11.12.0
* Operating System: Windows 10 64-bit

**Related issues**

**Comment by paulirish** [comment]
@finom who maintains jsonlint-mod

nomnom is a CLI arg parser, which we definitely don't even need.

**Comment by Hoten** [comment]
@finom would you accept a PR that resolves this issue? Could either update to some other parser (yargs?), or split the current npm package to two - a lib and a cli.

**Comment by BasJan81** [comment]
I also got a deprecated warning **(after updating Lighthouse 5.2.0)**

![CleanShot 2019-07-25 at 11 02 16](https://user-images.githubusercontent.com/10583358/61861364-090e3c00-aecc-11e9-80a4-98bd7acace63.png)

Is it possible we can fix this?

**Comment by finom** [comment]
@connorjclark yep, sure. `yargs` would be fine! But I wouldn't like to split the package into two different packages.

**Comment by finom** [comment]
Guys, I've upgraded jsonlint-mod so the warning disappeared. Feel free to upgrade to 1.7.5.
