### ISSUE TITLE
Manifest not found with startUrl with queryParams

### ISSUE THREAD

**Issue by juanpicuervo** [GoogleChrome/lighthouse#844]
In my manifest i have this start url:

 "start_url": "/?utm_source=home"

If i leave it like that the report says that Manifest not exists.

When i change it for /index.html it works fine.

**Comment by brendankenny** [comment]
This should be fixed in [the latest release](https://github.com/GoogleChrome/lighthouse/releases/tag/1.1.7). Please try it out and reopen if it's still not working.
