### ISSUE TITLE
Lazyload images

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#8441]
Hi
Seems that the bug #8211 he´s back

EDIT: Some times yes and some not......
![Captura](https://user-images.githubusercontent.com/22342793/56426327-37babc00-62b8-11e9-9ccb-d35375494b58.PNG)
![Captura1](https://user-images.githubusercontent.com/22342793/56426329-37babc00-62b8-11e9-924b-e2d934936a75.PNG)

**Comment by patrickhulce** [comment]
We haven't pushed the version of the code that contains the fix for #8211 to web.dev yet :)

It should be fixed in the next couple of weeks there as we make our final changes for 5.0.
