### ISSUE TITLE
Ship Lighthouse 4.3.1

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#8447]
- including the latest snyk roll
   - #8409 to avoid flood of up-to-date jQuery users being very confused.
- anything else?

We'll have to merge into beta branch in DevTools.

**Comment by brendankenny** [comment]
Maybe #8334

**Comment by paulirish** [comment]
maybe #7122

**Comment by Hoten** [comment]
Need #8338 to fix https://bugs.chromium.org/p/chromium/issues/detail?id=956457

**Comment by Hoten** [comment]
#8294

**Comment by brendankenny** [comment]
Should we add #8294 to start cutting back on auto-reported bugs?

**Comment by brendankenny** [comment]
oh, haha, already added it :)
