### ISSUE TITLE
Update README / Lighthouse w/ mobile devices

### ISSUE THREAD

**Issue by cassshh** [GoogleChrome/lighthouse#845]
In the [Lighthouse w/ mobile devices](https://github.com/GoogleChrome/lighthouse#lighthouse-w-mobile-devices) section it uses the cmd:
`$ lighthouse --disable-device-emulation --disable-cpu-throttling https://mysite.com`

However this produces the following:

``` shell
$lighthouse --disable-device-emulation --disable-cpu-throttling https://mysite.com
Please provide a url

Specify --help for available options
```

**It should be:**
`$ lighthouse https://mysite.com --disable-device-emulation --disable-cpu-throttling`

**Comment by wardpeet** [comment]
Fixed in version 1.1.7
