### ISSUE TITLE
Console error about about:blank being insecure origin hurts Best Practice score

### ISSUE THREAD

**Issue by tehshane** [GoogleChrome/lighthouse#8459]
#### Provide the steps to reproduce
1. Run LH on https://shanelawrence.ca (also tested on https://www.google.ca)
1. Look under "Best Practices" section
1. Note penalty:
![image](https://user-images.githubusercontent.com/3360089/56451921-dbb95d00-62e2-11e9-93b4-105c920c88f9.png)

#### What is the current behavior?
`about:blank` is loaded during the testing process, triggering the insecure origin error and improperly affecting the Best Practices score.

#### What is the expected behavior?
Errors relating to `about:blank` should be discarded or not factored into the BP score.

#### Environment Information
* Affected Channels: DevTools (Chrome 73.0.3683.103)
* Lighthouse version: 4.0.0
* Node.js version: N/A
* Operating System: Windows 10 (1803, Build 17134.706)

**Related issues**
* (None that I could find)

**Comment by patrickhulce** [comment]
Thanks for filing @tehshane! This seems like an error with a Chrome extension you might have installed though. I see no such error, and the fact that it's happening on two sites that do not have any iframes at all is revealing.

![image](https://user-images.githubusercontent.com/2301202/56452117-c9e0b580-62f4-11e9-8cec-aa4017b57603.png)

**Comment by tehshane** [comment]
Whoops, thanks for reminding me about extensions! I'd forgotten to use `--disable-extensions` before submitting the report.

However, even with all extensions disabled and in a fresh profile, I'm still getting the penalty, and when I watch the tab during testing, I see `about:blank` flash a few times:

(GIF)
![lighthouse-about-blank](https://user-images.githubusercontent.com/3360089/56453838-cc470d80-62fc-11e9-8a7b-cf39f68a6a62.gif)

Something else I could be missing?

Thanks again! 😃

**Comment by tehshane** [comment]
So I don't know if this is relevant or not, but I enabled _Preserve log_ in the Console to see if I could see the about:blank error myself, but I didn't actually see it appear.

However, what I did see was an unrelated error about an image asset that appears in the console, but doesn't show in the Best Practices summary.

![sshot-2019-04-19-23-50-51](https://user-images.githubusercontent.com/3360089/56453941-4af07a80-62fe-11e9-93e6-11569b6a55df.png)
![sshot-2019-04-19-23-51-13](https://user-images.githubusercontent.com/3360089/56453942-4b891100-62fe-11e9-8094-79f13e914d66.png)

🤷‍♂️ 

I'll fix the image error and see if that changes the score.

**Comment by patrickhulce** [comment]
Hm, not sure what we can do if we can't replicate it 😕 

To address your concern about the flashing `about:blank`, we navigate to `about:blank` between every page load to have a fresh baseline, and that particular logic has been unchanged for several years. The recent change that seems to be throwing your runs is the web app installability criteria in Chrome.

I'm not sure how you could possibly run into this on `google.ca` though since they don't even have a manifest. That makes me think *something* is injecting a manifest into pages that shouldn't have one, like `about:blank` and `google.ca`. If extensions were disabled, is it possible there's some other anti-virus/malware/other enterprise policy that could be interfering with page loads? 

(We've seen some really weird stuff, even an HP Printer plugin that messes with Chrome for unknown reasons 😆)

**Comment by tehshane** [comment]
@patrickhulce That's bizarre. Well, if it's just happening to me, that's good at least. 😊 My inner completionist will just have to accept that I got an honorary 100% on that section.

Will try on my work laptop and a fresh VM to make double sure, but other than that, I'll withdraw my report.

**Comment by tehshane** [comment]
![EC2-Capture](https://user-images.githubusercontent.com/3360089/56536035-f32a5d00-6511-11e9-9e8c-9fbf2f937f38.PNG)

Spun up a fresh VM and tested the site again, confirmed issue doesn't appear to be happening outside of my original machine. Bizarre!

Closing ticket. Thanks for your help! 🙌

**Comment by divall** [comment]
I have replicated this “about:blank”-issue and it will occur if you enable chrome://flags/#bypass-app-banner-engagement-checks

Try disable that flag, or reset all the Chrome flags to default, and “Best Practices” in Lighthouse will score 100 for https://shanelawrence.ca

**Comment by EmpireJones** [comment]
The workaround from @divall fixed this issue for me. Should this issue be re-opened to address this?
