### ISSUE TITLE
port `chrome-debug` onto ChromeLauncher

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#849]
The chrome-debug bin uses `launch-chrome.sh` to kick off chrome. I'm encountered problems with the shell script:
![image](https://cloud.githubusercontent.com/assets/39191/19824375/a9c593fe-9d23-11e6-81f6-d1c86896fa25.png)

..so it's probably a good time to leverage the solid work in `ChromeLauncher.ts` instead.

@samccone, seem good?

**Comment by brendankenny** [comment]
bonus points for an `--extensions` flag that will *enable* extensions so I can keep using this to test the extension in a chrome with a fresh profile :)

**Comment by addyosmani** [comment]
Sounds like a good time to do this 👍

**Comment by paulirish** [comment]
fixed by #898
