### ISSUE TITLE
Font display doesn't handle styles with relative/invalid sourceURL comments

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#8534]
#### Provide the steps to reproduce
1. Run LH on https://weston.ruter.net/

#### What is the current behavior?
Font display audit fails

#### What is the expected behavior?
Font display audit doesn't fail

I've traced this down to to the inline style which comes through with an invalid/relative `source.header.sourceURL`, this throws because it's not a valid URL and we don't end up whitelisting the font URL.

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/7708#issuecomment-485598419

**Comment by westonruter** [comment]
@patrickhulce The source URL is coming from the last line of `style[amp-custom]`:

```css
/*# sourceURL=amp-custom.css */
```

This was put in place based on a tip from @paulirish, as without it the CSS in the `style` element fails to appear in Coverage.

**Comment by patrickhulce** [comment]
Ohhhhh, that makes way more sense I missed that 😆 

Thanks @westonruter!
