### ISSUE TITLE
Lighthouse gives an error and doesn't work, in Google Chrome DevTools

### ISSUE THREAD

**Issue by cronus00101110** [GoogleChrome/lighthouse#8541]
#### Provide the steps to reproduce
1. Run LH on https://whatjobasaid.herokuapp.com/

#### What is the current behavior?
I run the lighthouse from the Google Chrome Dev DevTools, it's giving me the error below.
```
NO_FCP

Channel: DevTools
Initial URL: https://whatjobasaid.herokuapp.com/
Chrome Version: 75.0.3766.2
Stack Trace: LHError: NO_FCP
    at eval (chrome-devtools://devtools/remote/serve_file/@7615124e7fa821b6ec8c849f9505252188e902d0/audits2_worker/audits2_worker_module.js:1219:206)
```

#### What is the expected behavior?
I wanna see a report about my web app, I think?

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: I have no idea, I'm using Lighthouse from Google Chrome Version 75.0.3766.2 (Official Build) dev (64-bit)
* Node.js version: Mine is 11.12.0 but my web app's hosting site(heroku) has 10.15.3
* Operating System: Windows 10

**Comment by admiral2** [comment]
Hi, I have the same issue in Chrome Version: 74.0.3729.169 :
1. I running Audits on localhost
2. When I Open site in browser, open DevTools and run audits => all work file
3. But if I stay opened DevTools and switch browser to another tab and restart the same audits from step (2)  I reproducing issue. => Issue
4. If I switch back to my tab and again restart Audition all work fine


**Seems audition not work if Tab with site "not active"**

**Comment by JoeMorgan** [comment]
I am suddenly getting this error regardless of which page I try to audit. I updated from a previous version of Chrome to Version 76.0.3809.87 and still have the same issue.

**Comment by JoeCodeswell** [comment]
I just now got 

> 
**Lighthouse Version**: 5.2.0
**Lighthouse Commit**: ba1e1591dd83fe411f058df31a994df76796f646
**Chrome Version**: 76.0.3809.132
**Initial URL**: https://rt.joecodeswell.com/
**Error Message**: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.clearBrowserCache)
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT
    at chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:22728:11
```

**Comment by S-Kaushik** [comment]
I was having the same issue but it got resolved after I updated my Chrome.
Right now, it's at `Version 77.0.3865.120 (Official Build) (64-bit)` and the extension's working fine after the update.

**Comment by JoeMorgan** [comment]
Same. This is no longer an issue for me.

**Comment by amkayondo** [comment]
> Hi,
> I think it is needed to reopen issue and it is easy to reproduce.
> I have the same issue in Chrome Version: 74.0.3729.169 :
> 
> 1. I running Audits on localhost
> 2. When I Open site in browser, open DevTools and run audits => all work file
> 3. But if I stay opened DevTools and switch browser to another tab and restart the same audits from step (2)  I reproducing issue. => Issue
> 4. If I switch back to my tab and again restart Audition all work fine
> 
> **Seems audition not work if Tab with site "not active"**

I tried this out and it worked 🎉🎉🎉

**Comment by BerenOneHand** [comment]
Hello,

I get a similar issue when I try to run lighthouse with the devtools popped out of the chrome window.

**Comment by vladimir-marek** [comment]
Can your problems be caused by [#11722 ](https://github.com/GoogleChrome/lighthouse/issues/11722)?
