### ISSUE TITLE
Lighthouse reports page is blocked from indexing, but it is not.

### ISSUE THREAD

**Issue by gituser227** [GoogleChrome/lighthouse#8585]
#### Provide the steps to reproduce
1. Run LH on https://983fmtheword.com/
2. Observe results under SEO - Crawling and Indexing

#### What is the current behavior?
LH reports the page is blocked from indexing.

![image](https://user-images.githubusercontent.com/3066210/56677089-b97e6100-668d-11e9-885e-500451660543.png)

#### What is the expected behavior?
LH should not report the page as blocked. 
Google Search Console reports indexing is allowed.

![image](https://user-images.githubusercontent.com/3066210/56677223-0c581880-668e-11e9-9f0b-706e982543ba.png)

**Comment by patrickhulce** [comment]
Has something changed? That site shows up as passing for me at the moment.

![image](https://user-images.githubusercontent.com/2301202/56679420-a61dc680-668a-11e9-90ab-d491c2d6b48c.png)


I see that the 
```
#User-agent: *
#Disallow: /
```

lines have been commented out. If those were active previously, that would fail this rule. Even if Googlebot was allowed to crawl, it would prevent lesser known search engines from crawling your page.

**Comment by gituser227** [comment]
Those lines were commented out after.  If blocking any non-Googlebot engines will trigger failure of that rule, then that was clearly what was going on, and there's no issue after all.  Maybe it would help if the failure message were more precise.
