### ISSUE TITLE
Total timing is equal to 0 always via API

### ISSUE THREAD

**Issue by jmartinezpoq** [GoogleChrome/lighthouse#8638]
When im running lighthouse report via API the result in the JSON  'lighthouseResult' -> 'timing' -> 'total' is always 0

1. Run LH on https://www.google.com

2. https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://www.google.com&strategy=desktop&category=accessibility&category=performance&category=pwa&category=best-practices&category=seo

3. Response
![image](https://user-images.githubusercontent.com/47970682/56790159-1ac84080-6804-11e9-8f58-f11a0850da51.png)

#### What is the current behavior?
The response for all the websites is always 0

#### What is the expected behavior?
This is happening since April 17th, before it returned the total time in millis

#### Environment Information
* Lighthouse version: 4.3.0

**Comment by exterkamp** [comment]
So I can confirm this.  I'll take a deeper look into it.

**Comment by Hoten** [comment]
Corresponds with 4.3 in LR.

**Comment by walterfrancis** [comment]
Thank you @jmartinezpoq I had been seeing this too and had not had time to investigate why a test tool of mine using PSI was failing.

**Comment by jmartinezpoq** [comment]
any updates?

**Comment by jmartinezpoq** [comment]
any updates? @exterkamp

**Comment by paulirish** [comment]
@exterkamp this is a valuable signal. Let's get a fix in prod for this soon.

**Comment by jmartinezpoq** [comment]
hi, 
this is still happening.
@exterkamp @paulirish

**Comment by paulirish** [comment]
It's now fixed for PSI.
