### ISSUE TITLE
Is this possible to suppress the rules from lighthouse report

### ISSUE THREAD

**Issue by vbpradeep** [GoogleChrome/lighthouse#8645]
Is this possible to suppress the rules from lighthouse report?

if so can you share the sample code on that.

**Comment by patrickhulce** [comment]
@vbpradeep could you clarify what you mean by suppress?

You're probably looking for our configuration documentation. https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md

**Comment by vbpradeep** [comment]
Hi @patrickhulce,

This was i looking for, 'skipAudits', thanks

**Comment by patrickhulce** [comment]
Great glad you found it!
