### ISSUE TITLE
How should we handle content changing when scrolling down the page?

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#8647]
When a gatherer scroll down the page it can change the page layout, e.g. due lazy loading or infinite scroll loading more content. That might matter because:

- page content varies between gatherers, so whether the page has been scrolled can affect the scores of audits that look at the DOM
- [the new tap targets gatherer](https://github.com/GoogleChrome/lighthouse/pull/7778) first collects elements location and then scrolls through the page to call `elementFromPoint`. If an element moves while scrolling down the page the gatherer will think the tap target is invisible
- if we take a full page screenshot it should match what other gatherers see so we correctly identify elements on it

The accessibility gatherer used to run early on and it scrolled to the bottom of the page. [Moving it to run last](https://github.com/GoogleChrome/lighthouse/pull/8216) had a [minor impact on some sites' scores](https://gist.github.com/mattzeunert/79cb7605e6388c76f4090b7124a64482).

Should we do anything to make this more consistent and predictable?
- can we scroll all the way to the bottom of the page once before running any gatherers?
- maybe after scrolling down once we could get the height of the page and if the page grows again we ignore content beyond that page height? That page height could also be the max height of the full page screenshot.

cc @patrickhulce

**Comment by patrickhulce** [comment]
Discussed this the other day with @mattzeunert (Thanks for filing it!) and I think it would be a great followup to #8625 to scroll to the bottom of the current page height before all the afterPass runs to address most of this.

The ignoring all elements that get created seems a little tricker to enforce on gatherers, so I'm more willing to punt that for now/let individual gatherers handle that on a case-by-case basis.

**Comment by paulirish** [comment]
> - [the new tap targets gatherer](https://github.com/GoogleChrome/lighthouse/pull/7778) first collects elements location and then scrolls through the page to call `elementFromPoint`. If an element moves while scrolling down the page the gatherer will think the tap target is invisible
> - if we take a full page screenshot it should match what other gatherers see so we correctly identify elements on it

Looks like @connorjclark resolved these concerns with the #11536 and #11118 :D   


> - page content varies between gatherers, so whether the page has been scrolled can affect the scores of audits that look at the DOM

this part is still unresolved, but i'm gonna close the issue for now as there's no action plan on the horizon.
