### ISSUE TITLE
Background Image (using Cover) reporting aspect ratio failure

### ISSUE THREAD

**Issue by BenGriffiths** [GoogleChrome/lighthouse#8666]
When running the audit the tool is once again listing images as having the wrong aspect ratio despite being set to `background-size: cover;` (Which of course displays the image at it's native aspect ratio within the element it's been added to) - This was pointed out in issue https://github.com/GoogleChrome/lighthouse/issues/7487 and apparently fixed but seems to be showing up again for me.

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/1621106/56849923-129afe80-68f3-11e9-9afc-3f1070cdd362.png)

![image](https://user-images.githubusercontent.com/1621106/56849930-25adce80-68f3-11e9-9e72-ba1072ba192a.png)

#### Environment Information
* Lighthouse version: 4.2.0
* Operating System: Mac OS 10.14.4

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/7487

**Comment by patrickhulce** [comment]
Thanks for filing @BenGriffiths! That fix went out with 4.3.0, use latest Lighthouse for the update 👍

**Comment by BenGriffiths** [comment]
Oh sweet, thanks!

**Comment by tvld** [comment]
@patrickhulce  running at this too.. .wish DevTools used latest version of Lighthouse instead of 4.2.0 as it is now ;-)

**Comment by patrickhulce** [comment]
Updates take 6-12 weeks to make their way through Chrome's release process @tvld. It should be updated in Chrome 76.
