### ISSUE TITLE
DBW: suggest CSS flexbox instead of oldschool techniques

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#868]
negative margins, floats, and centering hacks are old school!

**Comment by ebidel** [comment]
Old school:

```
.horizontally-centered {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
  white-space: nowrap;
}
```

**Comment by graph1994** [comment]
I'd like to try to take this on if possible!

**Comment by ebidel** [comment]
Do you want to come up with a plan of attack? The example I gave is probably one of many things we can look for.

**Comment by graph1994** [comment]
I was thinking about first dealing with the negative margin piece by itself then go from since I'm new, I'll have a PR soon!

**Comment by AdrianoCahete** [comment]
Why not suggest [Display Grid](http://caniuse.com/#feat=css-grid) and postpone that fix for March 2017?

**Comment by ebidel** [comment]
Grid has different use cases and is a ways off as far as browser support. We could suggest grid for other uses cases, but the original intent of this issue was to raise awareness on how to to use modern CSS to center elements.

**Comment by paulirish** [comment]
can't really detect and be useful in our suggestions. too hard. :/
also requires parsing CSS which is a performance bottleneck for us.
