### ISSUE TITLE
Deprecate the Lighthouse Chrome extension

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#8690]
The Chrome extension has a number of challenging issues. It's similar to DevTools as a client, but we can't have nice integration like "view trace" or "click through on node to Elements panel"

Also bugs like #4451  (distorted screenshots)

We've wanted to drop the Chrome extension for a while.

The proposal is that hitting the Browser Action icon would just immediately open DevTools Audits panel. 

Implementation-wise: we'll need either protocol-level support to make this happen, an extension API that's exclusive to the LH chrome extension.

**Comment by Hoten** [comment]
> Implementation-wise: we'll need either protocol-level support to make this happen, an extension API that's exclusive to the LH chrome extension.

Extension API seemed the most straightforward. I'm not sure how to make an API private to an extension, but maybe `activeTab` / `tab` permissions are enough?

[Got a work in progress](https://chromium-review.googlesource.com/c/chromium/src/+/1610314).

![killext](https://user-images.githubusercontent.com/4071474/57672816-81a07480-75ce-11e9-95a9-da1660ff90a3.gif)

```
chrome.browserAction.onClicked.addListener(function(tab) {
  chrome.tabs.openDevTools(undefined, 'audits2');
});
```

**Comment by benjamingr** [comment]
As an extension author I would really prefer fixing the extension API to support three things

**Comment by benjamingr** [comment]
:(
