### ISSUE TITLE
Dom Size fails when no body present

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#8725]
This issue #6806 brought up counting elements in the HEAD, and this PR was made #7241.  But it fails to count dom elements in a website like this:

```html
<html>Content</html>
```

Where there are no `<body>` tags present, but there are nodes to count.

**Comment by patrickhulce** [comment]
Nice catch!!

FWIW, this also fails when `body` *is* present. It just fails when there are no elements at all to count :)

**Comment by connorjclark** [comment]
I was trying to upload a repro for this to surge but Chrome keeps being smart.

```
<html>who needs a body with html like mine?</html>
```
![image](https://user-images.githubusercontent.com/4071474/60375148-adc85700-99bc-11e9-81fc-5bc973cc5cee.png)



```
<html>Content<span>hi</span><span>hi2</span><span>hi3</span></html>
```

![image](https://user-images.githubusercontent.com/4071474/60375114-8ffaf200-99bc-11e9-8302-1e732e3f8ddc.png)

**Comment by connorjclark** [comment]
> Chrome keeps being smart.

Rather, the html parser spec is very particular about what to do here: http://w3c.github.io/html/syntax.html#the-before-head-insertion-mode

initial -> before html -> before head -> in head -> after head -> in body -> voila.

**Comment by connorjclark** [comment]
Anyways, my point is, how are you guys even getting this error to happen? I can't audit a document without a body, because apparently the spec never allows Chrome to make such a document.

**Comment by brendankenny** [comment]
> Anyways, my point is, how are you guys even getting this error to happen? I can't audit a document without a body, because apparently the spec never allows Chrome to make such a document.

yes, one is automatically created. @patrickhulce pinpointed the actual issue (an *empty* body)
