### ISSUE TITLE
Google Chrome - Offline Usage of Lighthouse

### ISSUE THREAD

**Issue by orbiton21** [GoogleChrome/lighthouse#8738]
Hi There,

I'd like to use Lighthouse on disconnected Enviorments.
Is it Possible?

If not, could you please provide me the servers and ports that are needed to make this tool functional.

**Operating System**: Windows 7 \ Windows 10
**Google Chrome Version**: 74.0.3729.108

Thanks,

**Comment by patrickhulce** [comment]
Yes Lighthouse does not reach out to any servers. Just run it locally on your localhost/internal network pages.

**Comment by orbiton21** [comment]
If so, could please explain why I'm getting the following message while:
1. Computer not connected to Internet
2. Computer is on disconnected Enviorments.

**Auditing www.google.co.il/

Lighthouse is warming up...**

The message won't disapper

**Comment by patrickhulce** [comment]
Ah, they are completely disconnected as in they've never had a network connection? Lighthouse isn't directly bundled with Chrome so the *first* time you use it in each Chrome version the code needs to be downloaded from the CDN. You can install Lighthouse separately in those environments (CLI/node/extension), but to use Lighthouse in DevTools the machine will at some point need to be connected to the internet for the initial download.
