### ISSUE TITLE
DBW: Suggestion rel="noopener" for external links

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#874]
This one may be controversial. But links that open in a new tab should use `<a target="_blank" rel="noopener">` so the opening page's perf does not suffer.

https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/

**Comment by karanjthakkar** [comment]
@ebidel I'd love to help out with this. Could you point me to where I can start?

**Comment by ebidel** [comment]
Sweet! I added some notes to https://github.com/GoogleChrome/lighthouse#do-better-web on where the dbw tests/audits/gatherers live.

To start, you could write a gatherer for `<a>` using `querySelectorAll()` ([example](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/theme-color.js)  and thing write an audit that filers that artifact result by checking that links with `target="_blank"` also have `rel="noopener"`. Similar to https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/image-alt.js
