### ISSUE TITLE
DBW: suggest the use of client hints

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#876]
e.g. if the device 400px wide, "why are you sending a 1200px wide image?"

https://www.chromestatus.com/features/5504430086553600

How? Grab all images loading by off the network, check their instrinsic size. Determine if they are too big given the DPR and size of the viewport tested.

e.g. Given a 2 DPR device and a 600px viewport, the appropriate image should be  600px * 2 = 1200px. Anything else is wasteful.

**Comment by olingern** [comment]
Hey @ebidel, I'd like to jump in on this one!

**Comment by ebidel** [comment]
Sweet! This one might be more involved than a "good first bug" :\ It'll involve a couple of gatherers and some promise magic.  There are a couple that might be even easier to start with:
https://github.com/GoogleChrome/lighthouse/issues/871
https://github.com/GoogleChrome/lighthouse/issues/718

Let us know what you'd like to tackle.

**Comment by olingern** [comment]
I like a challenge, but #871 sounds like a good stepping stone to this one. I'll pick up over there and see if I can send over a PR sometime soon

**Comment by patrickhulce** [comment]
addressed by #1497
