### ISSUE TITLE
DBW: suggest webp images if the client supports it

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#877]
.webp images can be much smaller in filesize, saving bandwidth. Safari and Firefox are also experimenting with webp.

Since we'd be auditing the page in Chrome, the client will support it :) We can simply detect if any images from the network are .webp. If not, suggest the developer look into using webp. Perhaps we can also come up with a "you would have saved X bytes" by using webp images"

Chrome [sends](https://developers.google.com/speed/webp/faq#server-side_content_negotiation_via_accept_headers) `image/webp` in the Accept header to advertise the client supports webp":

`Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`

**Comment by ThisIzKp** [comment]
@ebidel I would love to take a look at this.

**Comment by brendankenny** [comment]
I believe this was already closed by #2216. Sorry!

**Comment by ThisIzKp** [comment]
@brendankenny never mind, there are tonnes of issues to fix. Anyways this issue was closed because I commented over here, that's also a contribution 😛
