### ISSUE TITLE
Facing Issue | in report

### ISSUE THREAD

**Issue by pkamran** [GoogleChrome/lighthouse#8774]
Using LIghthouse  4.3.0, triggering test using WPT and with lighthousethrottle set to 1.

We are increasing getting error in the report which says "something went wrong please re run the test"

one example is 

http://34.193.48.242/result/190501_84_1c0e69483aa1578bcc28e94b6a675c9b/
--

Please can you suggest what can we change to avoid this.

Thanks & Regards
Pankaj Kamran

**Comment by patrickhulce** [comment]
Thanks for filing @pkamran! This is a bug in Chrome 74 that recently went stable. v4.3.1 (#8750) has workarounds that will fix this issue, and should be published soon.

**Comment by pkamran** [comment]
Thanks Patrick, Any specific date we have for 4.3.1 going live. As we will also need to inform Patrick from WPt to pick the latest lighthouse.

**Comment by patrickhulce** [comment]
No need to inform pmeenan specifically, I believe WPT picks up latest LH automatically.

My guess would be within the next week for 4.3.1 going live.

**Comment by pkamran** [comment]
It seems after 4.3.1 , another defect surfaced where reports are not getting genrated via WPT. Please see the stack trace : 
http://34.193.48.242/lighthouse.php?test=190508_N8_b91b8320b6a2ac0c71d048d9bee63b1e&run=1
we are getting a similar stack trace for all tests using WPT.

**Comment by patrickhulce** [comment]
Hm that seems to be a bug in WPT, the logs indicate the report is getting generated just fine.

**Comment by connorjclark** [comment]
Please reopen if you still see this.
