### ISSUE TITLE
DBW: suggest <template>

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#878]
We could look for patterns of reusable markup (`id="tmpl"`) uses of stuff like `<script type="x/handlebars">`.  This one could be noisy, but over communicating for DBW audits is not a bad thing IMO.

**Comment by paulirish** [comment]
While detecting nonvalid script types is pretty reasonable, that pattern is less common these days and templates ship within a bundle file. Handling that case is much harder. :/
