### ISSUE TITLE
Trim duplicate checks?

### ISSUE THREAD

**Issue by dandv** [GoogleChrome/lighthouse#880]
Would it make sense to omit the second occurrence of validations that are part of two larger checks?

Below, green rectangles highlight the first occurrence, and red ones highlight the second.

![image](https://cloud.githubusercontent.com/assets/33569/19875177/cb205eba-9f87-11e6-9d23-90ac5eba7e7e.png)

**Comment by ebidel** [comment]
Note: This will also be exacerbated when we start running the DBW audits by default. That collection reuses some of the audits already in the PWA suite.

**Comment by paulirish** [comment]
The "technology" view of the report is better if you don't want duplicates:
![image](https://cloud.githubusercontent.com/assets/39191/19876402/0a9c11e6-9f93-11e6-9b98-b7f14e20239d.png)

But as long as the report starts with user features as top-level, there will be some shared dependencies (like "has a service worker") for a few things. 

That said.. I'm willing to deal with "manifest exists" in some other way; I don't think it *needs* to be exposed to the user if it's passing.

**Comment by paulirish** [comment]
@dandv do you see yourself using the Technology view? Im thinking about removing it.  :)

**Comment by dandv** [comment]
@paulirish: I wouldn't miss it :)
