### ISSUE TITLE
artifacts.HTMLWithoutJavaScript.trim is not a function

### ISSUE THREAD

**Issue by atomikolex** [GoogleChrome/lighthouse#884]
debuggiing stops shortly before producing the report with this error message.

extension version 1.1.7 on Chromium 53.0.2785.143, Ubuntu 16.04 LTS.

**Comment by samccone** [comment]
@atomikolex how are you running lighthouse?

**Comment by atomikolex** [comment]
browser extension, all options on.

**Comment by brendankenny** [comment]
looks like the audit doesn't handle the case where there's an error fetching information from the browser. I have a fix

**Comment by brendankenny** [comment]
Thanks for reporting!
