### ISSUE TITLE
Google Pagespeed Insights downloading both webm/mp4 formats (Avoid enormous network payloads)

### ISSUE THREAD

**Issue by peixotorms** [GoogleChrome/lighthouse#8847]
#### Provide the steps to reproduce
Use the tool at https://developers.google.com/speed/pagespeed/insights/ to measure an html page, where a similar code exists:

```
<video width="1800" height="700"  preload="auto" loop autoplay muted>
<source src="https://domain.com/home.webm" type="video/webm">
<source src="https://domain.com/home.mp4"  type="video/mp4">
</video>
```

#### What is the current behavior?
It downloads both the mp4 and webm formats (Google Chrome doesn't do this, so it's just an issue with the pagespeed insights tool).
It triggers the "Avoid enormous network payloads" recommendation.
http://prntscr.com/nk8hx3

#### What is the expected behavior?
It should only download the webm format and skip the mp4.
There should be no "Avoid enormous network payloads" message, unless needed.

**Comment by brendankenny** [comment]
@peixotorms I'm not able to reproduce it on a page like this. I used https://www.html5rocks.com/en/tutorials/video/basics/, which has essentially the same markup for the videos as your suggestion, and only the webm videos show up as downloaded (https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.html5rocks.com%2Fen%2Ftutorials%2Fvideo%2Fbasics%2F).

Maybe it was a temporary issue or something else was going on with the page?

If you have a url we could test that would also be very helpful.

**Comment by peixotorms** [comment]
This has bee fixed on previous lighthouse updates, sorry about that.

**Comment by brendankenny** [comment]
No problem at all, we're glad it's fixed!

**Comment by jcrist1027** [comment]
When both an mp4 and a webm version are specified, Lighthouse uses the mp4 instead of the smaller webm version of the file.  Is this by design assuming a "lowest common denominator" on browser capability?  Otherwise why choose the larger files when smaller versions are available?

**Comment by geeworthington** [comment]
This issue/bug is still apparent.

I have a video running in the background / banner of my website homepage and I have two versions. A webm and an mp4. Google insights is detecting and penalizing my score (triggering the "Avoid enormous network payloads" warning) as it is downloading both?!

Has this bug resurfaced? Or am I doing something wrong that is blindingly obvious?!

I have almost idential markup as  @peixotorms 

`
<video loop="" autoplay="" muted="" playsinline="">
    <source src="https://mysite.co.uk/myvideo.webm" type="video/webm">
    <source src="https://mysite.co.uk/myvideo4.mp4" type="video/mp4">
</video>
`

**Comment by masiorama** [comment]
Same problem @geeworthington was esperiencing...

**Comment by connorjclark** [comment]
If you are still seeing this: please open a new issue and fill out the bug template. Most importantly, pleases provide a URL.
