### ISSUE TITLE
DBW: suggest Shadow DOM over css scoping / BEM

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#885]
The CSS scoping provided by Shadow DOM makes tools like CSS module, traditional class prefixing, and BEM obsolete. It would be nice to drive awareness of Shadow DOM if we can audit a page to look for these things.

**Comment by paulirish** [comment]
Relevant:

- https://nolanlawson.com/2022/06/22/style-scoping-versus-shadow-dom-which-is-fastest/
- https://twitter.com/slightlylate/status/1567750410781470721
