### ISSUE TITLE
DBW: use custom elements!

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#886]
Pages that reuse repetitive markup/css could benefit from reusable components. 

Things to look for in the audit:
- `HTMLUnknownElement` custom markup (e.g. `<dropddown>`)
- custom element tags that are never upgraded (`<my-nav>`). We have to be careful here, b/c in some cases, developers may be lazy-upgrading the custom element on purpose.
- jquery-like plugins / placeholder markup that gets populated by the plugin
- sections of repetitive markup

**Comment by paulirish** [comment]
Hard to be prescriptive here, as there are many opinions and ways to build a good site.
