### ISSUE TITLE
Calculate Best Practices Scoring rule 

### ISSUE THREAD

**Issue by SirPhemmiey** [GoogleChrome/lighthouse#8864]
Hi, I'm using Lighthouse programmatically and I've searched all over how to calculate the Best practices scoring rule, all to no avail. 

Actually, I am not using the other audit references. I'm just interested in only the Best practices audit reference. And I would like to know how the score is determined so as for me to embed it into my app.

Thanks in anticipation.

**Comment by patrickhulce** [comment]
All of the audits in best practices are weighted equally.

https://github.com/GoogleChrome/lighthouse/blob/24fe98250b81410e7567a9cb379b8fbb19ea3f2d/lighthouse-core/config/default-config.js#L465-L479

There are 14 audits so failure each is worth ~7 pts.

**Comment by SirPhemmiey** [comment]
I quite understand that they are weighted equally. But i don't know how to calculate the percentage kind of thing. In the lighthouse CLI i used, i got the best practices result of 71. I want to know how it was calculated and derived. 

Then agai, In the core file [default-config.js], there are 14 audits but in the docs there are 18 audits. I'm a little bit confused about it right now.

**Comment by SirPhemmiey** [comment]
I don't quite understand this statement "There are 14 audits so failure each is worth ~7 pts."

**Comment by patrickhulce** [comment]
There are 14 audits in the latest version that have a non-zero weight. 

```
100 / 14 = 7.14
100 - 71 = 29
29 / 7.14 = 4
```

Conclusion: You must have failed 4 scored audits to get a score of 71

Example: What is the score for failing 6 audits?

```
100 - (6 * 7.14) =  57
```

**Comment by SirPhemmiey** [comment]
Awesome. Got it.
