### ISSUE TITLE
CLI: accept multiple config files

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#887]
We'd like to eventually integrate DBW so it runs by default when you audit a page. There are open questions on doing so (gatherer pollution, how the new DevTools reporting will look).

Questions aside, the proposal here is to figure out how to run the tests together. I'd like to keep the existing dobetterweb.json config separate from the core default.json to maintain flexibility and not create/overload a monolithic config.

If the CLI accepted multiple configs, a default run of LH could look something like this under the hood:

    npm run start -- --config-path=lighthouse-core/config/default.json --config-path=lighthouse-core/config/dobetterweb.json ...

Thoughts?

**Comment by paulirish** [comment]
IMO selecting which gatherers happen in each pass is a really tricky thing. I don't think we can guarantee any two configs can work next to eachother unless we reset state completely and pretty much generate two separate reports based off different loads.

I'm more interested in creating a monolithic config. :)

**Comment by ebidel** [comment]
What if we programmatically combine the passed in configs and use the result as the actual run? IOW the monolithic config is virtual. As we get more collections of audits, it's going to be a lot easier to not create one big thing.

**Comment by brendankenny** [comment]
closing as we're sticking with monolithic configs for now, though that does not rule out mixins/inheritance at some future date.
