### ISSUE TITLE
Possible to show score card/ graph?

### ISSUE THREAD

**Issue by muuvmuuv** [GoogleChrome/lighthouse#8877]
On https://web.dev/measure when I ran an audit multiple times it generates a score card for each category. It would be nice if lighthouse itself supports this.

![Bildschirmfoto 2019-05-06 um 14 33 14](https://user-images.githubusercontent.com/11534760/57225413-913b1e80-700c-11e9-9f8f-4d60fed6b328.png)

In my case I store the output as JSON and HTML in my projects (just in case this feature is/will be available). So it would be so nice to see how I perform over time.

My suggestion how we could implement this:

Add a new option `previousScores` which is a glob (or maybe a function too?) to files that contain previous data e.g.: `option.previousScores: 'reports/**/lighthouse.json'`. We would then check how many lighthouse.json we find, parse them and put them into a graph per category.

![Bildschirmfoto 2019-05-06 um 14 40 41](https://user-images.githubusercontent.com/11534760/57225803-b4b29900-700d-11e9-8113-b8435518602a.png)

Problems:

- Some may change their categories/settings over time which could cause errors on parsing old data(?)

**Comment by Hoten** [comment]
Thanks for the suggestion! :)

@paulirish and I discussed something like this before. Something like a local LH server that serves LHRs (kinda what you suggested, but would allow for more interoperability - example, a company could host a LHR server on their intranet). Could also quickly switch between different reports without explicitly rendering each one w/ the CLI.

It's a pretty large feature, and brings LH closer to becoming an application experience. We'll probably have to wait a couple weeks (post-5.0) to discuss this further.

**Comment by paulirish** [comment]
I think this would be super cool, but until we have a more fleshed out CI product, the best solution here is writing a new node module that can read a directory of lighthouse JSON files and outputs various charts, etc.

feel free to take the `historical-lighthouse` npm module name if you wanna take a crack at this.
