### ISSUE TITLE
Best Practices Audits does not tally

### ISSUE THREAD

**Issue by SirPhemmiey** [GoogleChrome/lighthouse#8879]
Hello guys,
There's something i don't understand clearly. 

In the docs, https://developers.google.com/web/tools/lighthouse/ under the "Best practices" category there are 19 audit references. But when i run lighthouse via the CLI or Programmatically, it returns 14~15 audit references. What could be the issue? Am i missing something?

**Comment by patrickhulce** [comment]
The docs still have pages for the audits that have been removed from Lighthouse in latest version. They are still there because older reports still link to those URLs.

cc @kaycebasques for considering restructuring the table of contents so they are not as visible.

**Comment by SirPhemmiey** [comment]
Okay cool. So the audits that the CLI returns in JSON is the new audits in
the last version right?

**Comment by SirPhemmiey** [comment]
Okay cool. So the audits that the CLI returns in JSON are the new audits in
the last version right?

**Comment by patrickhulce** [comment]
Correct with the code that's in currently in GitHub master being the soon-to-be-released v5.

**Comment by kaycebasques** [comment]
I can mark old docs as deprecated, which grays them out like this:

![image](https://user-images.githubusercontent.com/4713486/57259106-4cff4c80-7013-11e9-8a8e-11b4cad0f6cc.png)

**Comment by SirPhemmiey** [comment]
Okay, thanks @kaycebasques. 

Would be expecting the update.
