### ISSUE TITLE
Extension: 1.1.7 reports FMP as Infinity

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#890]
![screen shot 2016-11-01 at 2 39 04 pm](https://cloud.githubusercontent.com/assets/238208/19908539/07bf55f6-a041-11e6-8912-33f190515e36.png)

Run is from https://airhorner.com/. CLI output is correct:

<img width="316" alt="screen shot 2016-11-01 at 2 40 09 pm" src="https://cloud.githubusercontent.com/assets/238208/19908558/1cf9e0ee-a041-11e6-874f-ea9c38b67c35.png">

**Comment by brendankenny** [comment]
not always, just sometimes. Probably just need to implement #618

**Comment by SebastianBoyd** [comment]
Same problem when I run it on my site

**Comment by paulirish** [comment]
fixed by #1066
