### ISSUE TITLE
Speed Index not stable 

### ISSUE THREAD

**Issue by crabvn** [GoogleChrome/lighthouse#8900]
**Summary**

Hi,

I am using lighthouse(google insights) to test this url  
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpromotion.thairath.co.th%2Ftraveloka-coupons%2F

Sometime I get very slow speed index score but almost high score.
![image](https://user-images.githubusercontent.com/14814576/57357195-f590e600-71a4-11e9-98eb-433b25cdc0ea.png)
![image](https://user-images.githubusercontent.com/14814576/57357220-03466b80-71a5-11e9-99e4-4ae52a0f4477.png)

Anyone faced this problem like me?

**Comment by patrickhulce** [comment]
The screenshots seem to indicate there was indeed a problem in the first run where the page did not render properly until very late. I'm not able to reproduce locally, so this might require some investigation.

**Comment by crabvn** [comment]
> The screenshots seem to indicate there was indeed a problem in the first run where the page did not render properly until very late. I'm not able to reproduce locally, so this might require some investigation.

It happened also on the "th" run time not first run. I meant sometime it getting slow indexed.

**Comment by patrickhulce** [comment]
Apologies @crabvn but would you mind explaining what you mean by `"th" run time not first run`? I'm not sure I understand.

**Comment by crabvn** [comment]
@patrickhulce yes.

the slow of speed index happened not only at the first time. In the past 3 weeks I worked on the improving performance and then I faced this issue few times/day.

**Comment by brendankenny** [comment]
You might find some helpful advice in the variability docs: https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md

If you're still experiencing a notable problem, please comment and we can reopen.
