### ISSUE TITLE
Wrong value in the type of "score" in the "Understanding result" documentation

### ISSUE THREAD

**Issue by khalyomede** [GoogleChrome/lighthouse#8901]
**Explaination**
I noticed your documentation is mentionning the `score` of one of the key `report.lhr.categories.{}.score` as `String`, but it appears in my console as `Number`.

**Reproduce the issue**

1. Go to the documentation : [https://github.com/GoogleChrome/lighthouse/blob/master/docs/understanding-results.md#categoryentry-properties](https://github.com/GoogleChrome/lighthouse/blob/master/docs/understanding-results.md#categoryentry-properties)
2. See that the type of the `score` cell is `String` 

**Expected result**
The documented type should be `Number` instead of `String`.

**Note**
I noticed it when I printed the score of the "performance" key for one of my lighthouse run for my website.

**Comment by patrickhulce** [comment]
Thanks @khalyomede! Interested in a PR? :)

**Comment by khalyomede** [comment]
Sure @patrickhulce! On my way. :)

**Comment by kaushikchaubal** [comment]
@khalyomede / @patrickhulce - i have created a PR for this. This is my first PR to this community so if anything looks wrong, please shout out.
