### ISSUE TITLE
Cannot read property 'args' of undefined

### ISSUE THREAD

**Issue by natew** [GoogleChrome/lighthouse#8916]
Related to #2339. I updated to new versions and it still has the same error. Tried a few different configs with no luck.

#### Provide the steps to reproduce

Run this repo:

https://github.com/natew/CSS-IN-JS-Benchmarks

```
yarn install
npx lerna bootstrap
yarn benchmark
```

#### What is the current behavior?

`packages/tests/index.js` runs into an error on line `93` reading extendedInfo.

#### What is the expected behavior?

Should return it.

**Comment by brendankenny** [comment]
`extendedInfo` was removed in [Lighthouse 3.0](https://github.com/GoogleChrome/lighthouse/releases/tag/v3.0.0).

The v3 migration guide has suggestions for how to deal with these changes: https://developers.google.com/web/tools/lighthouse/v3/migration (though note that [4.0](https://github.com/GoogleChrome/lighthouse/releases/tag/v4.0.0) and [5.0](https://github.com/GoogleChrome/lighthouse/releases/tag/v5.0.0) have been released in the meantime).

**Comment by natew** [comment]
The issue is the error that comes up which is output into the actual JS, which doesn't have to do with reading extendedInfo.

I still get this:

```
{ score: null,
  displayValue: '',
  rawValue: null,
  error: true,
  debugString: 'Audit error: Cannot read property \'args\' of undefined',
  optimalValue: undefined,
  extendedInfo: undefined,
  informative: true,
  name: 'user-timings',
  category: 'Performance',
  description: 'User Timing marks and measures',
  helpText:
   'Consider instrumenting your app with the User Timing API to create custom, real-world measurements of key user experiences. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/user-timing).' }
```

Weirdly the object returned shows `lighthouseVersion: 1.6.5`, but my node_modules says it is lighthouse `5.0.0`.

**Comment by natew** [comment]
Note the `debugString` value. You can run the repo to see.

**Comment by patrickhulce** [comment]
Hm @natew that's strange that would only happen if something crazy unexpected happened with the artifact, what version of Chrome are you using?

**Comment by natew** [comment]
74 is my installed version.

**Comment by connorjclark** [comment]
We think your environment might be messed up, causing you to use an older version of LH. Can you try `which lighthouse` or perhaps list the globally installed modules for `yarn` / `npm`?

**Comment by paulirish** [comment]
The object we see in https://github.com/GoogleChrome/lighthouse/issues/8916#issuecomment-491113900 is definitely from LH 1.6.5 .... but yes everything looks good with your package.json and yarn.lock... so its not clear why some stale LH is sneaking in.

**Comment by brendankenny** [comment]
Closing since there hasn't been any movement on this, but if you're still having a problem please comment and we can reopen!
