### ISSUE TITLE
[Lightwallet] Support timings in budgets UI

### ISSUE THREAD

**Issue by Danon9111** [GoogleChrome/lighthouse#8917]
**How timings budgets are shown in case when they are not met?**

Could you please confirm that currently budget for timings metrics are working properly? As I see right now in html report is no clear information about if the budget have been met. 

Budget definition:
![image](https://user-images.githubusercontent.com/4902552/57514655-40c80780-7311-11e9-9f17-f465eb75d5f7.png)

***Steps to reproduce***
1. Run ` lighthouse https://youtube.com --budget-path=lighthouse-core/test/fixtures/simple-budget.json` in console (CMD or GitBash on Windows)
2. Open generated report

***Current behavior:***
Generated HTML report does not have clear information about timings budget, like for resourceSizes. 

Report:
![image](https://user-images.githubusercontent.com/4902552/57515007-f85d1980-7311-11e9-97b7-ec7f22f38b47.png)

***Question:***
Is described behavior an expected one? Or for timings should be also displayed table with information about current value of metric and expected budget, defined in json file like in case of resources?

**Comment by patrickhulce** [comment]
Budgets only assert on the file sizes at the moment, metric timings are pending so stay tuned :)

**Comment by Danon9111** [comment]
Cool stuff! 

Thank you for answer @patrickhulce ! 

Do you have any public roadmap to view what features can come next months?

**Comment by patrickhulce** [comment]
@Danon9111 not that's neatly organized into releases but you can take a look at issues with the `P1` and `P1.5` label to get an idea :)

**Comment by connorjclark** [comment]
fixed by https://github.com/GoogleChrome/lighthouse/pull/9925
