### ISSUE TITLE
New audit: "Image cropped"

### ISSUE THREAD

**Issue by Zolszabo** [GoogleChrome/lighthouse#8929]
**Feature request summary:**
Add new audit in best practices:  "not all image content visible" OR "Image cropped"

**Why?:**
When a background image is set for a div which scales according to content and screen size we can set proper CSS rules to keep aspect ratio and let the background crop "e.g. background size: cover" etc... If we do so a false positive: "display images with incorrect aspect ratio" error is reported. The aspect ratio is just right the image isn't stretched so the before mentioned NEW error could be reported instead. Or just don't report it at all, as anyhow the extra bytes downloaded for nothing counts in the performance section!

**What is the motivation or use case for changing this?**
Make a proper better lighthouse, and avoid confusion by a false error.

**How is this beneficial to Lighthouse?**
This way its more understandable, more clearish to everyone!

Tested in Chrome dev. tools 11 May 2019, Lighthouse 2.4.0

**Comment by patrickhulce** [comment]
Thanks @Zolszabo! We've already stopped applying that audit to CSS background images because of the many intentional corner cases with background position, sprite sheets, cover/contain, etc.

Maybe if you try with v5 you'll see the result you'd like?

**Comment by Zolszabo** [comment]
Dear Patric

Thank you for your kind and prompt reply.
Consider this issue resolved

All best
  Zoltan Szabo

**Comment by patrickhulce** [comment]
Köszönöm hogy írtál!

A családom nagy része Magyarországról származik. A nagybátyám neve is Szabo Zoltán! :)

**Comment by Zolszabo** [comment]
Szervusz,

Mégiscsak kicsi ez a világ :-)
Köszi a választ

Üdv,
  Zoli
