### ISSUE TITLE
Does not run. It says Lighthouse ran into an issue and cancel Button gets  highlighted.

### ISSUE THREAD

**Issue by Csavitha** [GoogleChrome/lighthouse#8943]

**Comment by Hoten** [comment]
Url?

**Comment by Csavitha** [comment]
its a internal website

**Comment by Csavitha** [comment]
is there a way to screen share and let you know the problem

**Comment by patrickhulce** [comment]
Please fill out the entire new bug report template @Csavitha. You can share a screenshot if that would help illustrate the issue but we need all the information in https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md to be able to act on it.
