### ISSUE TITLE
Hi when lighthouse runs it says immediately that it ran into error and cancel button gets enabled

### ISSUE THREAD

**Issue by Csavitha** [GoogleChrome/lighthouse#8946]

**Comment by Csavitha** [comment]
![lighthouse](https://user-images.githubusercontent.com/50594753/57653955-f0a6aa80-7587-11e9-98bf-151c0de7e66d.PNG)

**Comment by patrickhulce** [comment]
Thanks @Csavitha we're traced the DevTools Canary issues to the root of the issue and @Hoten is on the case!

**Comment by Csavitha** [comment]
Please help to resolve the issue

**Comment by Csavitha** [comment]
okie thank you

**Comment by Csavitha** [comment]
Hi how can i know what the resolution to this issue?

**Comment by patrickhulce** [comment]
This has been fixed for Canary Chrome. Try running your page in Canary.

In the future, **please fill out the entire bug report template** before expecting resolution to your issue.

**Comment by ZLTM** [comment]
Any news? I'm running into the same problem, I'm using Chrome: Versión 74.0.3729.169 (Build oficial) (64 bits), testing a web app deployed using vagrant
