### ISSUE TITLE
Chrome Version 74.0.3729.131 when audit is run , it runs into an error

### ISSUE THREAD

**Issue by Csavitha** [GoogleChrome/lighthouse#8947]

**Comment by Csavitha** [comment]
![lighthouse](https://user-images.githubusercontent.com/50594753/57659572-ab8a7480-7597-11e9-9c47-2b77cd860ea1.PNG)

**Comment by patrickhulce** [comment]
Please stop filing new issues for this @Csavitha. Hundreds of people receive an email every time you do this.

**If you cannot provide a reproducible case with the latest version of Lighthouse and/or in Chrome Canary, we cannot help you.**
