### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jpjitendrapal** [GoogleChrome/lighthouse#8958]
**Summary**: Tried 4-5 times every time chrome is giving this error:
<img width="1258" alt="Screen Shot 2019-05-15 at 12 33 42 PM" src="https://user-images.githubusercontent.com/6689741/57755296-2d9ca980-770e-11e9-883a-e35a372d36f1.png">

**Comment by cherscarlett** [comment]
Try unchecking "clear storage"

**Comment by gilbertococchi** [comment]
Can you please share the URL you were testing?

I also have similar errors on Incognito or not, on new Profile as well on some URLs like https://amp.campmor.com/c/s/clothing/womens-clothing/womens-rainwear

**Comment by jeremyfoster88** [comment]
> Try unchecking "clear storage"

I was running into the same problem, unchecked "clear storage" and it worked.

**Comment by jpjitendrapal** [comment]
I was checking www.snapdeal.com

**Comment by exterkamp** [comment]
This is a `PROTOCOL_TIMEOUT` by the looks of that error message #6512 for some more details.

I can't repro this anymore, and @brendankenny added `pending-close` almost 2w ago, so I'm going to go ahead and close.  Reopen if this is still happening.
