### ISSUE TITLE
ttfb

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChrome/lighthouse#8959]
**How to improve TTFB ?**

The lighthouse report indicates 100 for performance, accessibility, best practices and SEO for my site but 0.12s, in red, for the TTFB.

1°) What would be a good TTFB ?

2°) TTFB depends a lot of the location of the hosting and in my case the hosting is in Europe and when I try my site in https://www.webpagetest.org/, I see big differences. How can I reduce these differences ?

======================
Links : 

[Lighthouse report](https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.koolsol.com/)

[WebPageTest report from Paris, France, TTFB=0.129s, all green on the top of the page](https://www.webpagetest.org/result/190515_A3_66bfc8ed1b0cd36420bc955b568c4826/)

[WebPageTest report from California, USA, TTFB = 0.866s, all green but not TTFB](https://www.webpagetest.org/result/190515_Z7_9a61f34a5096e8f913d2490e162d7b8c/)

[pwa koolsol ( international solitaire game )](https://www.koolsol.com)
note : win two games to see the country list of the players

**Comment by patrickhulce** [comment]
> What would be a good TTFB?

Our audit is looking for anything less than 600 ms, but a *good* TTFB is in the <200ms range, ideally <100ms.

> How can I reduce these differences ?

If you're asking how you can reduce differences for your users, the answer would be CDNs/edge servers closer to your users :)

If you're asking how you can run tests closer to your infrastructure, it's something the PSI team is aware of and thinking about. 

Also worth noting that the TTFB audit won't impact your performance score specifically. It's just pointing out one of the major components of your metric that could be improved. If you're managing to get green scores without following its advice, great!

**Comment by hugues-koolsol** [comment]
Thanks for your precise answer.

Sorry, I got confused because in the [Lighthouse report](https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.koolsol.com/), 
there is only the estimated saving but not the TTFB itself.
