### ISSUE TITLE
Chrome's Translation prompt kills Lighthouse

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#896]
Running Lighthouse CLI over adb, I've run into a pretty consistent bug where it dies (possibly times out) when it hits a site that triggers the Google Translate prompt. The bug persists unless you allow or deny automatic translation. 

I wonder if there's a way for us to disable translation somehow.

**Comment by brendankenny** [comment]
apparently there is! [`--disable-translate`](http://peter.sh/experiments/chromium-command-line-switches/#disable-translate)
