### ISSUE TITLE
DevTools bug template goes outside dialog bounds

### ISSUE THREAD

**Issue by Quiet1129** [GoogleChrome/lighthouse#8974]
![image](https://user-images.githubusercontent.com/1068997/57877010-99911780-77cb-11e9-932f-32bb045e326e.png)

**Comment by patrickhulce** [comment]
Thanks @Quiet1129! NO_FCP means that the page has not painted any content. We can't audit a page that doesn't have any content.

**Comment by patrickhulce** [comment]
Separately, we should probably fix that whitespace issue where it goes outside the bounds of the window :)

**Comment by Quiet1129** [comment]
Well, this page did have content and have ran lighthouse many times before.

![image](https://user-images.githubusercontent.com/1068997/57936368-a586e300-7878-11e9-8d0d-d945d5bf2137.png)

**Comment by Quiet1129** [comment]
@patrickhulce

**Comment by patrickhulce** [comment]
@Quiet1129 

This is what I see in Chrome Canary for that URL.

![image](https://user-images.githubusercontent.com/2301202/57944042-543c1b00-789b-11e9-99d4-6499562dde07.png)


You're never able to get past the NO_FCP error?

Note that if it just takes too long to paint you'll also see the error.

**Comment by Quiet1129** [comment]
@patrickhulce 
My Canary version of chrome seems to be working fine. Seems like it's just my regular version of chrome that does it.

**Comment by patrickhulce** [comment]
Alright well we'll consider that bug fixed in latest version then, this bug still tracks the UI brokenness of the bug report going outside its bounds :)

**Comment by connorjclark** [comment]
We think this is fixed.
