### ISSUE TITLE
Lightouse on Canary + standard chrome can not audit Vue PWA

### ISSUE THREAD

**Issue by Decntdefalt** [GoogleChrome/lighthouse#8980]
Title explains the issue, image shows the issue. I tried 3 times separately on each browser.
<img width="926" alt="Screenshot 2019-05-17 at 16 19 37" src="https://user-images.githubusercontent.com/41927878/57935134-6a5cd200-78c1-11e9-9691-8118761a24db.png">
Chrome Version 74.0.3729.157 (Official Build) (64-bit)
Chrome canary Version 74.0.3729.157 (Official Build) (64-bit)

I built my PWA based on the vue-cli pwa template. Don't understand why lighthouse can not audit. The PWA url is http://logima.io, give me a feedback if this is happening for you as well! Then the problem is on my end. But as of now, seems like the only ones I can't conduct audits are on my pwas logima.io and logima.no.

Could it be issues with lighthouse not being able to test the service workers or? Because I've never had a problem like this before with lighthouse audits and PWAs, but it is my first time building on the vue-cli template. However, again, the PWAs work fine and as expected so this leads me to believe there is some clash with lighthouse. 

The PWA's are being served as static content through nginx webserver after production build so they're in production mode.

**Comment by patrickhulce** [comment]
Hm your page does not load for me in Canary. It is just a blank white screen. If that's what you see too then Lighthouse can't audit an empty page which is the error you're getting.

![image](https://user-images.githubusercontent.com/2301202/57935536-a410e700-7887-11e9-823c-fa6367be67d4.png)


From the CLI I was able to audit your page successfully with v5.

![image](https://user-images.githubusercontent.com/2301202/57935528-99565200-7887-11e9-834e-3239d8c3248e.png)

**Comment by Decntdefalt** [comment]
Strange, I have no explanation for why it loads blank for you. I see the snaps of the app under first meaningful paint there. I've loaded it on safari as well as having cleared storage on chrome since it's a pwa. I can see it loading clearly as i want but can not conduct any lighthouse tests.

But good news is that if it works for you then the problem is on my end somehow! Thanks :)
