### ISSUE TITLE
Lighthouse reports are supposed to return stable results?

### ISSUE THREAD

**Issue by cbcaio** [GoogleChrome/lighthouse#8981]
Hello Lighthouse team,

I'm auditing this website `https://www.catho.com.br/educacao/graduacao/busca` using various tools to check ways we can improve our score, however the performance results are not stable at all, I get score in a range between 20 to 50 in performance, the times we solved some of the issues listed in the results the messages disappeared but other times it show again as a unsolved issue.

Here are the ways I tried:
- using lighthouse chrome built-in feature
- using https://www.webpagetest.org/lighthouse
- using https://www.webpagetest.org with custom config (but same network speed and region Brazil)
- https://developers.google.com/speed/pagespeed/insights/ 

Is there anything I'm missing? Could this be related to something we are doing wrong in our page? Thanks in advance.

Kind regards,
Caio

**Comment by patrickhulce** [comment]
Thanks for filing @cbcaio!

Have you already read through https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md?

**Comment by cbcaio** [comment]
thanks @patrickhulce I did not see that before, its quite useful.
I thought using webpagetest was supposed to mitigate the impact of all these variability factors but it looks its way more complex to do that than I thought!
