### ISSUE TITLE
False alarm on robots.txt

### ISSUE THREAD

**Issue by technion** [GoogleChrome/lighthouse#8987]
#### Provide the steps to reproduce
1. Run LH on https://lolware.net/

#### What is the current behavior?
Reports "robots.txt is not valid"
#### What is the expected behavior?
According to this test tool it's entirely valid:

https://www.google.com/webmasters/tools/robots-testing-tool?pli=1&siteUrl=https://lolware.net/

#### Environment Information
* Affected Channels: Chrome Devtools
* Lighthouse version: Version 74.0.3729.157 (Official Build) (64-bit)
* Operating System: Windows 10

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @technion!

Specifically Lighthouse says "Lighthouse was unable to download a robots.txt file"

This is due to the page's CSP and is a duplicate root issue of https://github.com/GoogleChrome/lighthouse/issues/4386, so we'll track there.
