### ISSUE TITLE
Measure load time from A to B

### ISSUE THREAD

**Issue by stefanspirkl** [GoogleChrome/lighthouse#8992]
First off, I love lighthouse. 

However, I don't just want to measure the time it takes to load page B; I would like to measure how long it takes to load page B, **provided I am already on page A**.

Ideally I'd fire a click event on the link to page B.

From all I see, this can't be done with Lighthouse && Node ?

**Comment by patrickhulce** [comment]
You're mostly correct it's not really possible to do exactly what you've described, but you can get kinda close.

1. Open Chrome yourself with remote debugging enabled.
2. Navigate to Page A
3. Run Lighthouse on Page B by passing the port of your opened Chrome and `disableStorageReset: true`.

Lighthouse will still create a new tab and navigate to Page B separately, but at least your cache state/cookies/localStorage/etc will be as if the user just came from Page A. Note that `sessionStorage` will be different though.


Related discussions you might find helpful #1418, #3837

**Comment by stefanspirkl** [comment]
Thanks Patrick,

I chose to implement against the Performance Web API and then simulate things like clicks with RobotJS.
