### ISSUE TITLE
v5 installation fails with yarn 1.15.2 and node 8.15.0

### ISSUE THREAD

**Issue by anselmbradford** [GoogleChrome/lighthouse#8998]
The error:
```
Command failed: yarn add lighthouse@5.0.0
error lighthouse@5.0.0: The engine "node" is incompatible with this module. Expected version ">=10.13". Got "8.15.0"
error Found incompatible module
```

#### Provide the steps to reproduce
1. Check that yarn 1.15.2 is installed and that node 8.15.0 is installed.
1. Run `yarn add lighthouse@5.0.0` 

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 5
* Yarn version: 1.15.2
* Node.js version: 8.15.0
* Operating System: OSX 10.12.6

**Comment by anselmbradford** [comment]
Err, actually, I just realized that error is saying that node needs to be higher than 8 🤦‍♂

**Comment by Hoten** [comment]
🚀
