### ISSUE TITLE
Translation messing up linked docs in dom-size

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#9000]
Run LH with `--locale=`:fr: and look @ dom-size:
![image](https://user-images.githubusercontent.com/6392995/58040836-5694b400-7aeb-11e9-8679-8f31fffcaf62.png)

This highlights a larger problem with embedded HTML content in translated strings.  Which should be removed from the translated part and added in on our end at report-time (maybe?) so that this doesn't happen and we stop paying to translate these links that aren't really translated.

**Comment by patrickhulce** [comment]
> Which should be removed from the translated part and added in on our end at report-time (maybe?) so that this doesn't happen and we stop paying to translate these links that aren't really translated.

Not sure I follow this one. Seems like the translators just need to learn how to use markdown though so we know which words to actually link? Markdown or some other annotation format that seems more complicated cuz markdown is as simple as it gets :)

**Comment by brendankenny** [comment]
kind of part of #6945.

There is a recommended `<a>` format (at least it's in a lot of the docs). We could translate to it and back for string submission.

**Comment by exterkamp** [comment]
This was fixed in #8999 manually, but we need to re-upload it to translation for official correction in the tc/ system.

**Comment by exterkamp** [comment]
Collapsing into #9197 since it is the same thing and will be closed with that resolving soon.
