### ISSUE TITLE
Tab Target Sizes for Desktop makes no sense

### ISSUE THREAD

**Issue by rvetere** [GoogleChrome/lighthouse#9014]
#### Provide the steps to reproduce
1. Choose "Device: Desktop"
2. Select "Audits: SEO" as only option
3. Run LH on https://www.galaxus.ch/de/s1/product/apple-iphone-xs-max-650-256gb-dual-sim-12mp-space-grey-mobiltelefon-9581544

#### What is the current behavior?
It reports a very bad result for "proper tab target sizes".. Well, first of all - tab targets on a Desktop only Test-Environment? Wrong.. They are click-targets on Desktop (i'm not even having a touch-enabled System here)

Secondly - tab targets should be sized 48x48px... This is a good value on Mobile, yes, but not on Desktop! On Desktop this is waaaaay too big for many (nice, existing) designs out there.

I can see that the Audit is reporting different results for tab-targets when switching between Mobile/Desktop.. So this is considered correctly..

#### What is the expected behavior?
I would expect that tab-target-sizes on Desktop are defined much smaller than 48x48px... I remember the mighty "48px" value comes from the average size a human fingertip has...

A mouse cursor of a Deskopt-Mouse is much much smaller to be honest :-P If i would now follow the audit's suggestion and make all targets appropriate size -> it would break our whole design very badly... But i really want to make it trough your audits!

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: Chrome Version 74.0.3729.157 (i'm using Lighthouse in DevTools)
* Node.js version: v10.15.1
* Operating System: Windows 10 Professional

**Comment by patrickhulce** [comment]
Thanks for filing! Your expectations are correct and this is a bug, duplicate #8967.
