### ISSUE TITLE
Strange styling at different zooms for LH in DevTools

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9018]
This is your Goldilocks state (zoom level is juuuuuust right): 

![image](https://user-images.githubusercontent.com/4071474/58145186-09593500-7c06-11e9-816a-ce2fa2066f66.png)

But, you zoom out a bit:

![image](https://user-images.githubusercontent.com/4071474/58145198-11b17000-7c06-11e9-9dde-9bb694769e08.png)

Or zoom in a bit:

![image](https://user-images.githubusercontent.com/4071474/58145202-183fe780-7c06-11e9-84b7-a3a0e91aa741.png)

**Comment by Hoten** [comment]
I can't even tell what zoom I'm at. I want to be at 100% - how?

**Comment by brendankenny** [comment]
> I can't even tell what zoom I'm at. I want to be at 100% - how?

cmd/ctrl-0

@connorjclark is this something we're realistically going to fix? It seems like a larger DevTools issue (e.g. the checkboxes in the Network panel have the same styling behavior when zooming)

**Comment by connorjclark** [comment]
If it's not restricted to the Audits panel, let's move to DT's bug tracker.

https://bugs.chromium.org/p/chromium/issues/detail?id=982490
