### ISSUE TITLE
DevTools report redesign

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9019]
I collected some screenshots of what master looks like now in DevTools. Not pretty (yet) :)

This is what 4.2 (in stable) looks like now (yes, DevTools LH had dark mode already):
<img width="733" alt="lh-4 2" src="https://user-images.githubusercontent.com/4071474/58145899-bf258300-7c08-11e9-97b7-0ac5d92550e3.png">

Dark mode, master (I zoomed out a lot here):
<img width="730" alt="lh-5 0-before-dark" src="https://user-images.githubusercontent.com/4071474/58145919-d6647080-7c08-11e9-9aa2-c03fc3843ce8.png">

Light mode, master (same zoom settings as 4.2 img):
<img width="725" alt="lh-5 0-before-light" src="https://user-images.githubusercontent.com/4071474/58145929-debcab80-7c08-11e9-847f-775176e4c52f.png">
<img width="726" alt="lh-5 0-before-light-2" src="https://user-images.githubusercontent.com/4071474/58145936-e419f600-7c08-11e9-9435-966894a42ccb.png">

--

Dark mode is messed up b/c it was implemented (in DT) with a theme - a bunch of custom CSS overwriting the pre 5.0 stuff. Figure we just need to remove most (or all) of what that theme is doing.

Chromium changes: https://chromium-review.googlesource.com/c/chromium/src/+/1623894

**Comment by Hoten** [comment]
Metric error state looks odd w/o an icon:
![image](https://user-images.githubusercontent.com/4071474/58146987-58ef2f00-7c0d-11e9-9020-1f81c0d0f4cd.png)

**Comment by Hoten** [comment]
Mouse over "Error" in metrics doesn't show the error.
![image](https://user-images.githubusercontent.com/4071474/58197458-2e3ebe00-7c81-11e9-8193-1946438567d8.png)

**Comment by Hoten** [comment]
Oh, you'd have to toggle the pill meant for metric descriptions to see the error..

**Comment by brendankenny** [comment]
fixed! (modulo other open report rendering issues)
