### ISSUE TITLE
PSI audit list shape alignment issue

### ISSUE THREAD

**Issue by yuinchien** [GoogleChrome/lighthouse#9020]
#### Provide the steps to reproduce
Ran PSI to see LH report.
https://developers.google.com/speed/pagespeed/insights/?url=chrome.com&tab=desktop

#### What is the current behavior?
The shapes in Field Data audit list are not vertically center. 

<img width="745" alt="Screen Shot 2019-05-21 at 8 45 21 PM" src="https://user-images.githubusercontent.com/406636/58146145-b2555f00-7c09-11e9-8631-26e117361a38.png">

#### What is the expected behavior?
Shape and title should align

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by exterkamp** [comment]
Missing an `align-items: center` :face_with_head_bandage:  shame.

```css
.field-data .field-metric {
    ...
    align-items: center;
    ...
}
```

**Comment by exterkamp** [comment]
Coming to a PSI near you, next rollout!

**Comment by exterkamp** [comment]
Done.
![image](https://user-images.githubusercontent.com/6392995/62984624-d11e5880-bde8-11e9-82be-b604f0dd3ebf.png)

**Comment by connorjclark** [comment]
![image](https://user-images.githubusercontent.com/4071474/62985141-c2d13c00-bdea-11e9-99d3-c695d2f0d8b0.png)

dat release cadence :)
