### ISSUE TITLE
PSI Mobile view style guffaws

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9026]
I snapped these from PSI, but they should be issues in LH too.

![image](https://user-images.githubusercontent.com/4071474/58201148-3e5a9b80-7c89-11e9-9589-24d1db81d48b.png)

![image](https://user-images.githubusercontent.com/4071474/58201161-4581a980-7c89-11e9-9b28-5af4abfa5489.png)

**Comment by Hoten** [comment]
LH looks like this (disclaimer in the wrong spot)

![image](https://user-images.githubusercontent.com/4071474/58215193-85f31e80-7cad-11e9-958d-c462947f1e7b.png)

**Comment by brendankenny** [comment]
is this fixed now? "Values are estimated and may vary" fixed in #9030, filmstrip in #8563. Other issues?

**Comment by Hoten** [comment]
The margin issue on the metrics table is PSI-only. Think that's all that remains.

**Comment by exterkamp** [comment]
Fixed in PSI, waiting on next deploy :smile: surely that will be very quick.

**Comment by exterkamp** [comment]
SURELY this is happening soon :sweat_smile:

**Comment by exterkamp** [comment]
Done w/5.2!
![image](https://user-images.githubusercontent.com/6392995/62984592-a92ef500-bde8-11e9-84e8-2e13f436e50f.png)

**Comment by connorjclark** [comment]
neat
