### ISSUE TITLE
TTFB opportunity can show with nothing actionable.

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9034]
![image](https://user-images.githubusercontent.com/4071474/58280602-d1610780-7d55-11e9-8e3f-fe35e1e372e6.png)

![image](https://user-images.githubusercontent.com/4071474/58280616-d9b94280-7d55-11e9-9617-c7aec2a9b1c5.png)

@patrickhulce says:

> Well that one is a pretty dumb audit. There are never items and savings is excess of 600ms of whatever
> Not dumb in useful sense just not very complicated :)

(got this from https://willstocks.co.uk/, but only in LR).

**Comment by brendankenny** [comment]
this issue report is also not actionable :P

What are you thinking in terms of what to do with it?

**Comment by Hoten** [comment]
Sure it is! I just haven't suggested an action, was moving on to something else for a sec my bad.

We could not show opportunities under a specific savings threshold. 0.1s is probably a bit high - maybe we could show hundredths and hide anything < 0.01s?

Also, the displayText value is not shown anywhere in the report. And it suggests that it took 600ms to get the first doc - ok, but why isn't the doc in the details table?

**Comment by patrickhulce** [comment]
> 0.1s is probably a bit high - maybe we could show hundredths and hide anything < 0.01s?

IMO we could reasonably be showing `x - 100` as the "opportunity" and just only flag things that take 600 ms to avoid this problem entirely.

**Comment by brendankenny** [comment]
> IMO we could reasonably be showing x - 100 as the "opportunity" and just only flag things that take 600 ms to avoid this problem entirely.

Yeah, this makes sense to me. It's silly to display time over a moderately bad ttfb as the opportunity instead of time over a pretty good ttfb (even though it still makes sense to score the other way)

**Comment by patrickhulce** [comment]
De-duping into #9671.
