### ISSUE TITLE
DevTools v5 roll

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#9035]
Couple things we gotta do, this issue is to track them.

Fix some log snooping: https://github.com/GoogleChrome/lighthouse/pull/9029#issuecomment-495367760

Styles: https://github.com/GoogleChrome/lighthouse/issues/9019
* including removing the previous dark theme impl in Chromium

**Comment by brendankenny** [comment]
closing cause this happened :)
