### ISSUE TITLE
Failed to load resource: net::ERR_ACCESS_DENIED

### ISSUE THREAD

**Issue by ThomasWT** [GoogleChrome/lighthouse#9038]
Resource is accessable, even though web.dev says it is not.

![image](https://user-images.githubusercontent.com/1246641/57847901-ee3a8f80-77d7-11e9-8def-5b88493cf032.png)

edit: replaced image because sensitive data.

**Comment by patrickhulce** [comment]
Tracked as part of #9137

**Comment by TDurrr1** [comment]
I'm also experiencing this issue when testing https://monicajean.photography. Both `/stylesheets/main.css` and `/stylesheets/print.css` cause `Failed to load resource: net::ERR_ACCESS_DENIED` errors on web.dev, but neither has ever given me an issue using Chrome's built-in auditing (or any other time, for that matter).

**Comment by ThomasWT** [comment]
Still an issue.
Lighthouse reports them as ERR_ACCESS_DENIED, but no problem in the browser itself.
I have the JSON report but I'd rather not share it without anonymizing the content, so PM me for it.

![image](https://user-images.githubusercontent.com/1246641/68612336-98138400-04bc-11ea-9804-d2bc4105e5f1.png)
![image](https://user-images.githubusercontent.com/1246641/68612494-f0e31c80-04bc-11ea-8f02-b90173c10e0d.png)
![image](https://user-images.githubusercontent.com/1246641/68612519-fe98a200-04bc-11ea-8207-2350d6514222.png)
![image](https://user-images.githubusercontent.com/1246641/68612544-0ce6be00-04bd-11ea-8120-e6318ecf0880.png)

**Comment by kevinegstorf** [comment]
I had the same issue while running the lighthouse chrome extension, but running lighthouse from audit in devtools it worked fine for me.
