### ISSUE TITLE
Performance 0 suddenly

### ISSUE THREAD

**Issue by kristojurisson** [GoogleChrome/lighthouse#9039]
Hi, I'm wondering if there has been anything changed lately to the performance measurement on https://web.dev/measure?

My site's performance has hovered around high 30 - 50s for quite a long while, I have also set up daily lighthouse scoring on my own server with simulated 3g + cpu slowdown that has gotten the score pretty close to the web.dev one (still off some points). 

Right now though (since this week), without any significant change to the site, the web.dev reports 0 for performance. I still get the "accurate" reporting from my server and devtools though. 

Additionally, the TTI reported is ~100sec while the test itself took ~45sec, is that a questimate?

![Screen Shot 2019-05-14 at 5 13 53 pm](https://user-images.githubusercontent.com/2729040/57678410-73089a80-766c-11e9-9670-fe23a4c410d5.png)

Anyone else ever experienced this? Hope i'm reporting this to the correct place. 🤞

**Comment by exterkamp** [comment]
This (roughly) corresponds to upgrading the LR infra to [Lighthouse 5.0](https://docs.google.com/document/d/11hXs4zZXxGdxRFYueWh1JDh45wiSzMc9TQ9z6NVqB0g/preview) so that might have been affecting this? Is this still an issue?  We need a URL to debug this.

**Comment by brendankenny** [comment]
Closing as there hasn't been any movement on this issue, but if you're still seeing a problem please comment and we can open back up!
