### ISSUE TITLE
Need a way for a passes to request incognito launch of chrome

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#904]
This would be useful for permission-based APIs (geolocation, notifications, media access) that show a permission bar at the top of the page.  If we can come up with a way for specific passes to request their gatherers/audits be ran in an incognito window, we could guarantee the permissions are always in their initial "prompt" state.

I didn't see a way in the protocol to reset permissions...

Example:
The geolocation audit. It's a poor user experience to request that API on page load, but after the user has already granted permission, it's perfectly fine to call that API on page load b/c 1.) the user has already said "yes" and 2.) there won't be a permission bar. The same applies for similar APIs.

**Comment by brendankenny** [comment]
@ebidel it seems like you have a [better solution](https://github.com/GoogleChrome/lighthouse/blob/01665e662f3c99046fd1f97dbc35b2f59723c2cf/lighthouse-core/gather/gatherers/dobetterweb/geolocation-on-start.js#L36-L45) for the permissions use case in particular. Is there still a strong need for an incognito tab beyond that or is it worth closing this for now?

**Comment by ebidel** [comment]
We can probably close for now but this is still an open issue.

If the user has already granted the permission, there's no way for us to know if the page asks for that permission on page load. Not sure what to do about this without an 1.) an incognito run or 2.) `navigator.permission.revoke` (https://bugs.chromium.org/p/chromium/issues/detail?id=510405)

**Comment by oMaten** [comment]
@ebidel maybe you can rewrite `${TMP_PROFILE_DIR}/Default/Preferences` file like
```json
{
  "profile": {
    "content_setting": {
      "exceptions": {
        "geolocation": { "${YOUR_SITE}": { "setting": 3 } },
      }
    }
  }
}
```

**Comment by ebidel** [comment]
@oMaten interesting idea. Any pointer links?

**Comment by paulirish** [comment]
We also have [`Target.createBrowserContext`](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Target/#method-createBrowserContext) which says

> Creates a new empty BrowserContext. Similar to an incognito profile but you can have more than one.

We can then `createTarget` to open new tabs within that.

HOWEVER. this is only supported in headless. It could be supported in browser, but it's work. and it might be better to do the protocol work on permissions instead.

**Comment by oMaten** [comment]
@ebidel https://www.chromium.org/administrators/policy-list-3#DefaultGeolocationSetting, it is not official guide of Preference, but useful

**Comment by patrickhulce** [comment]
No longer in distinct pass
