### ISSUE TITLE
Why not download report as pdf?

### ISSUE THREAD

**Issue by TomasHurtz** [GoogleChrome/lighthouse#9041]
Why not download report as pdf?

**Comment by patrickhulce** [comment]
We feel that it's fairly straightforward today to take the HTML report and print to PDF.

As we add more interactivity to the HTML report, the "print" parallel for PDF will only become even more appropriate. If you have anything further to add, feel free to fill out our feature request issue template regarding resourcing, benefits, etc. :)

**Comment by TomasHurtz** [comment]
>take the HTML report and print to PDF.   ??

Or at least allow a print function?  Now Have to screen dump

**Comment by Hoten** [comment]
![image](https://user-images.githubusercontent.com/4071474/58308316-1ddc2f80-7db6-11e9-8951-86c98e3b8384.png)

====

![image](https://user-images.githubusercontent.com/4071474/58308243-e40b2900-7db5-11e9-8059-47a794b597fe.png)
