### ISSUE TITLE
Use the final url for the "is-on-https" audit

### ISSUE THREAD

**Issue by daannijkamp** [GoogleChrome/lighthouse#9044]
#### Provide the steps to reproduce
1. Run LH on http://www.google.com or any other non-https url with a https redirect (using pagespeedonline).
2. https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=http://www.google.com&strategy=mobile&category=best-practices

#### What is the current behavior?

- requestedUrl: ```http://www.google.com/```
- finalUrl: ```https://www.google.com/?gws_rd=ssl```
- is-on-https audit score: 0, because: 1 insecure request found: ```http://www.google.com/```

#### What is the expected behavior?

- although the requestedUrl is not secure, the finalUrl is.
- use the finalUrl for the is-on-https audit 

#### Environment Information
* Affected Channels: pagespeedonline, probably more 
* Lighthouse version: 5.0.0
* Node.js version: -
* Operating System: -

**Comment by patrickhulce** [comment]
Thanks for filing @daannijkamp! This is best summarized and discussed in https://github.com/GoogleChrome/lighthouse/issues/3417 so we'll continue tracking there.
