### ISSUE TITLE
Update axe-core

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#9045]
We are hitting this error https://github.com/twbs/bootstrap/issues/28795. We reported it upstream on https://github.com/dequelabs/axe-core/issues/1578 and it's fixed in axe-core 3.2.0.

I'm opening this to track the update.

**Comment by patrickhulce** [comment]
Hm, @XhmikosR we've already updated to 3.2.2, what version of Lighthouse were you testing with?

**Comment by XhmikosR** [comment]
That I don't know either, it's a user supplied report. But if the latest version has the updated axe-core version, we can close this issue too :)

**Comment by patrickhulce** [comment]
Ah OK gotcha, sounds good feel free to circle back around if you think something's not right :)

**Comment by chrisblakley** [comment]
I originally reported it in the Bootstrap repo. The version of Lighthouse appears to be 4.2.0 within Chrome 74:

![Screen Shot 2019-05-24 at 10 51 55 AM](https://user-images.githubusercontent.com/6349678/58336624-1185c000-7e12-11e9-8b20-b26c781642d2.png)

**Comment by XhmikosR** [comment]
This should be fixed in v5.0.0 judging from the [commits](https://github.com/GoogleChrome/lighthouse/commit/02b50ff957b957c1d69c414d8b984a000eac9985#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).
