### ISSUE TITLE
Why is budget.json an array?

### ISSUE THREAD

**Issue by ireade** [GoogleChrome/lighthouse#9046]
An example `budget.json`:

```json
[
  {
    "resourceCounts": [
      {
        "resourceType": "third-party",
        "budget": 10
      }
    ]
  }
]
```

Why is it an array of "budgets" instead of just one? e.g.:

```json
  {
    "resourceCounts": [
      {
        "resourceType": "third-party",
        "budget": 0
      }
    ]
  }
```

Is there support for multiple types of budgets or specifying a url? I can't seem to find any information suggesting that in [the docs](https://developers.google.com/web/tools/lighthouse/audits/budgets)

**Comment by patrickhulce** [comment]
You can read more about the history and planned future for budgets in https://github.com/GoogleChrome/lighthouse/issues/6053, but the gist is that we intend to support `path` descriptors and `profile`/`environment` options in the future in a single file. The array format keeps this extensible which would enable these features.

**Comment by ireade** [comment]
Ah that makes sense, thanks @patrickhulce !
