### ISSUE TITLE
Report not generated, instead error message displayed. Refer the screenshot for more details.

### ISSUE THREAD

**Issue by Prakash0989** [GoogleChrome/lighthouse#9047]
Lighthouse report is not generated when i click on 'Run Audits'.I am getting error message .Please refer the screenshot attached and provide us the solution. 
<img width="1310" alt="Screen Shot 2019-05-24 at 4 23 41 PM" src="https://user-images.githubusercontent.com/45254050/58323240-04cc9080-7e41-11e9-8201-ec12b1c5202e.png">

**Comment by patrickhulce** [comment]
Thanks for filing @Prakash0989. The error is obscured, so it's hard to tell what's going on, but the fact that your screen is completely blank suggests that we failed to audit the page because the page failed to load.

This isn't a Lighthouse bug, but something that needs to be fixed in the page.

**Comment by connorjclark** [comment]
Please reopen if this still happens for you. ty
