### ISSUE TITLE
Avoid an excess DOM size goes "Error!"

### ISSUE THREAD

**Issue by Westbrook** [GoogleChrome/lighthouse#9048]
When auditing https://westbrook.github.io/minesweeper/ the "Avoid an excess DOM size" returns `Error!`.

#### Provide the steps to reproduce
1. Visit https://westbrook.github.io/minesweeper/
2. Run DevTools audit
3. See "Avoid an excess DOM size" report

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/1156657/58328417-07f35c80-7e00-11e9-82c2-bceda3ed4d75.png)

#### What is the expected behavior?
It tells me something useful... right?

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: Stable & Canary
* Operating System: Mac OS

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @Westbrook!

The full error message can be seen on hover, and this is indeed a bug!

![image](https://user-images.githubusercontent.com/2301202/58336537-830d4080-7e09-11e9-8a52-1cb9922452d7.png)

**Comment by Westbrook** [comment]
Oh, great! Thanks for pointing that out, it will be super helpful if I run into future issues.

I would never have caught that bubble interaction, however. Seems like there might be room for some UI/X love on that (being the visuals tell me to toggle, not hover).

If there is anything else I can do to support clearing up this issue, please let me know.

**Comment by patrickhulce** [comment]
For anyone that might want to take this on, the error is being thrown here

https://github.com/GoogleChrome/lighthouse/blob/df85d681886d1ae163798c715fd29c72cc96c58f/lighthouse-core/lib/page-functions.js#L115-L126

A good fix might be to simply `try/catch` and return `<${node.localName}>` if we can't determine the full outerHTML :)

**Comment by NickolasBenakis** [comment]
I would like to work on this

**Comment by Hoten** [comment]
thanks @NickolasBenakis!

Tried to assign you but I guess only project members can be assigned to issues :)

**Comment by NickolasBenakis** [comment]
seems harder than I thought, I tried the `try/catch` senario but it gives me the same error again...
I am still working on this

**Comment by NickolasBenakis** [comment]
I fixed it!

**Comment by brendankenny** [comment]
Fixed by #9079
