### ISSUE TITLE
Fireworks don't work for solo category

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#9058]
```
node lighthouse-cli https://exterkamp.codes --view --only-categories=seo
```

b/c we do all the fireworks magic in the score header. Which has zero height in solo category mode.

**Comment by patrickhulce** [comment]
At one point once upon a time (in the same `hue-rotate` discussion 😆) we tossed around the idea that fireworks would only happen on all category 100s anyhow, so we might want to do that instead of fixing this? 🤷‍♂

**Comment by Hoten** [comment]
ya I could buy that. But in this post-plugin world, who are we to say what constitutes "all" categories? :P

jk, we could do fireworks -> only if 100s on all core categories.
