### ISSUE TITLE
chrome: audit not starting

### ISSUE THREAD

**Issue by vishwaspaikra007** [GoogleChrome/lighthouse#9063]
![Screenshot from 2019-05-26 01-44-38](https://user-images.githubusercontent.com/44310959/58374230-659abc80-7f58-11e9-9d4e-aec9ad44ed31.png)

it appeared while i was about to test my web app

**Comment by vishwaspaikra007** [comment]
can anybody tell me why it happened

**Comment by patrickhulce** [comment]
Chrome stopped responding to our commands. (See canonical issue #6512).

You can try unchecking the "Clear storage" option to see if it clears things up as Chrome is unable to clear storage in certain cases for unknown reasons.
