### ISSUE TITLE
More word breaking issues

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9078]
![image](https://user-images.githubusercontent.com/4071474/58590545-2a7ae080-8219-11e9-97f3-4834ecb98a67.png)

```
                      (l
ocalhost)
```

```
32
2
```

____

![image](https://user-images.githubusercontent.com/4071474/72845266-11fd8180-3c53-11ea-80e7-a22d17461e3b.png)

**Comment by brendankenny** [comment]
I'm sure there are more, but the two screenshotted here might be fixed?

See e.g. https://lighthouse-ousxikjp0-googlechrome.vercel.app/english/

**Comment by patrickhulce** [comment]
When we find a specific word breaking issue to fix, we'll reopen this.
