### ISSUE TITLE
core(budget): add resource type `initial-document`

### ISSUE THREAD

**Issue by csabapalfi** [GoogleChrome/lighthouse#9080]
**Feature request summary**

I'd like to add a new resource type to Lighthouse performance budgeting called `initial-document`. This will allow setting a resource size budget that only includes the initial document.

I'm happy to work in this myself.

**What is the motivation or use case for changing this?**

The initial document is much more important to set a budget for then later document requests (sometimes even by third-parties).

**How is this beneficial to Lighthouse?**

It'll allow users to set more targeted budgets.

**Comment by patrickhulce** [comment]
Neat idea thanks for filing @csabapalfi!

cc @khempenius for her thoughts.

FWIW, elsewhere in lighthouse we refer to this as the "root document" or "main resource", just to throw other competing labels for `initial-document`

**Comment by paulirish** [comment]
Closing as this is dependent on the upstream action.
