### ISSUE TITLE
Lighthouse Warmup Hangs in Canary devtools

### ISSUE THREAD

**Issue by patrick-mcdougle** [GoogleChrome/lighthouse#9094]
#### Provide the steps to reproduce
1. Run LH on any url

#### What is the current behavior?
Lighthouse hangs on warmup.

#### What is the expected behavior?
Lighthouse runs.

#### Environment Information
* Affected Channels: Devtools (Canary)
* Lighthouse version: ?
* Node.js version: N/A
* Operating System: OSX

**Related issues**

**Comment by patrick-mcdougle** [comment]
I'm not seeing any error messages, besides it just not working. Let me know if there's any way I can provide more details. I know this is a really vague bug report...

**Comment by patrickhulce** [comment]
Thanks for reporting @patrick-mcdougle! This is known Chromium issue, see https://bugs.chromium.org/p/chromium/issues/detail?id=968425 to follow along 👍

**Comment by patrick-mcdougle** [comment]
Thank you @patrickhulce!

**Comment by exterkamp** [comment]
Upstream Fixed!
