### ISSUE TITLE
FR - Integrate DevTools blocked requests with LH reports ran from Audits tab

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/lighthouse#9095]
Note: this FR is for the LH integration in DevTools ("Audits" tab). For that reason, it might be a "joint" FR for DevTools and Lighthouse.

**Summary**

If a user blocks a resource in DevTools and then runs LH from the Audits tab, that resource shouldn't be considered when calculating load times and showing opportunities and suggestions for optimizations.

**Motivation**

One of the ways to identify and demonstrate the impact of resource loading in load times (specially third party JS), is to use the [Block requests feature](https://developers.google.com/web/updates/2017/04/devtools-release-notes#block-requests) in DevTools.

For example: Blocking a resource in DevTools, and running [the Profiler](https://developers.google.com/web/updates/2016/12/devtools-javascript-cpu-profile-migration) can help developers understand the overall impact of load times of such resource. It's also a great communication tool to describe internally to different teams (i.e: marketing), the impact things like trackers have on page load times.

If the the developer then goes to "Audits" and runs LH he/she will obtain the report that belongs to the original page (not the page with the blocking resource).

This not only makes the blocking resource feature less useful, but can be perceived as inconsistent for users.

**Comment by Hoten** [comment]
Thanks for filing. We want this too. See #5423 for previous discussion.

AFAIU, we can do this easily by [setting `settings.blockedUrlPatterns` in the Audits panel.](https://github.com/GoogleChrome/lighthouse/issues/6838#issuecomment-460791723). Easy.

But we also eventually want to support local overrides, which requires reusing the same connection to the page that DevTools creates, in Lighthouse. This would get us request blocking from DT for free.

So we should consider how large of an effort the connection sharing would be (I don't have insight on this). Only if it's too high or will take a long time should we consider the easy approach for url blocking.

**Comment by brendankenny** [comment]
let's dedupe into #5423
