### ISSUE TITLE
Disable third party filter when no third parties present

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9096]
In #8966 we remove the third party filter if all items are third party.

This creates this (unenjoyable) experience:

Run Lighthouse, see 6 issues. Check the third party filter box. Oh cool, I got 2 things to do.

Fix the 2 issues.

Run Lighthouse. See no checkbox and 4 items, but no indication (other than you parsing the URL) that they are third party.

Maybe we could style third party rows differently? What symbol would indicate "third party"?

**Comment by patrickhulce** [comment]
Instead of removing the filter checkbox, maybe we just disable it when everything is third-party?
