### ISSUE TITLE
Remove audit list focus ring 

### ISSUE THREAD

**Issue by yuinchien** [GoogleChrome/lighthouse#9099]
#### Provide the steps to reproduce
1. Run LH on https://www.google.com/chrome/

#### What is the current behavior?
The default focus ring behavior is visible, according to the recent review, I recalled the decision was to use :focus-visible(only show the ring when focus via keyboard for accessibility). The rationale is that the focus ring creates bounding box that excludes the selected content (dropdown), and can be confusing to read, it also doesn't look pretty. 

<img width="919" alt="Screen Shot 2019-05-31 at 3 32 50 PM" src="https://user-images.githubusercontent.com/406636/58738150-677dd900-83b9-11e9-9765-d80fab375b46.png">

<img width="914" alt="Screen Shot 2019-05-31 at 3 32 47 PM" src="https://user-images.githubusercontent.com/406636/58738159-6d73ba00-83b9-11e9-89b4-3a2bc39fe8f5.png">

#### What is the expected behavior?
<img width="800" alt="Screen Shot 2019-05-31 at 3 45 17 PM" src="https://user-images.githubusercontent.com/406636/58738548-1ff84c80-83bb-11e9-8056-c18004bbb81f.png">

<img width="798" alt="Screen Shot 2019-05-31 at 3 45 14 PM" src="https://user-images.githubusercontent.com/406636/58738551-21c21000-83bb-11e9-920e-31ced0c62820.png">

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.1.0
* Node.js version:
* Operating System:

**Related issues**

**Comment by Hoten** [comment]
[:focus-visible](https://caniuse.com/#search=%3Afocus-visible) is not ready for use yet - only in FF behind a vendor prefix, and Chrome behind an opt in flag.

Polyfill: https://github.com/WICG/focus-visible

**Comment by brendankenny** [comment]
Focus ring is still sort of there, but has changed since this was filed (maybe most recently in #13249?). Closing as stale
