### ISSUE TITLE
Implement android chrome launcher

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#910]
Running lighthouse currently on an android phone is pretty tedious.

Ideally a user should be able to run lighthouse and pick a connected android phone to run chrome on and run the selected audits.

Implementations steps.

1. detect if adb is in the path or set via ADB_PATH
2. `adb devices -l` to get the connected devices 
3. present the list of devices to pick from
4. detect is chrome canary installed, if not bail.
4. launch chrome canary on the device 
5. setup port forwarding from device 
`adb forward tcp:9222 localabstract:chrome_devtools_remote`
6. run lighthouse 💃

**Comment by paulirish** [comment]
I think we _could_ exclude support for multiple devices for the moment. I personally get nervous to have multiple devices connected over adb and trust that the right commands will go to the right phone, so I always unplug the one i'm not working with.  But if you'd rather keep it in scope, then sure. :)

How do you want to handle getting a clean baseline? Clean chrome profile? Can we do user-data-dir via flag on android? Do we only use Canary and say "We'll be wiping your storage and SWs, FYI!"?

**Comment by wardpeet** [comment]
Pretty sure we can close this in favor of #910
/cc @paulirish

**Comment by paulirish** [comment]
moved to https://github.com/GoogleChrome/chrome-launcher/issues/31
