### ISSUE TITLE
SPA perf

### ISSUE THREAD

**Issue by ir135** [GoogleChrome/lighthouse#9108]
Have a spa.
lighthouse showing that FCP & FMP r higher on a checkout pg w/ zero images (than on the home pg).

Wondering if lighthouse measures FCP & FMP metrics correctly for a non-home page of a spa. 
thanks lots.

**Comment by patrickhulce** [comment]
It depends on how your SPA loads, but if you're essentially doing quite a bit of logic to setup the page, and then you end up "redirecting" to your sub-page and rerender everything again, then it would be expected that loading a non-homepage of an SPA would have adverse impact on the metrics.

Without example URLs and reports it is difficult to say anything more. Also see [our variability docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) for general notes on fluctuations.

**Comment by ir135** [comment]
![spa_home](https://user-images.githubusercontent.com/51313035/58818082-16046280-85e2-11e9-9228-5dd81bab6667.PNG)
![spa_checkout](https://user-images.githubusercontent.com/51313035/58818083-169cf900-85e2-11e9-8017-6dbaabdedddc.PNG)

thanks lots Patrick; appreciate your detailed response.
first one is home; next one is checkout step 1.

maybe i am doing something wrong.
using chrome incognito running lighthouse thru chrome extension (generate report).
on one incognito tab generated report for the home page.
on same tab moved from home page to checkout step 1 page; then generated report.

considering its a spa, do i need to run lighthouse in some other way such that spa benefits are captured in the report

**Comment by patrickhulce** [comment]
Thanks @ir135! Those numbers are very close and well within expected variability (see [docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md)).

It looks like your checkout page executes more Javascript than your homepage which could contribute to the difference you are seeing in addition to variance. (3.8s vs 4.5s) Hope this helps!

**Comment by ir135** [comment]
Thanks lots Patrick.
If you pls don't mind, wrt below image:
device was  Nexus 5x but what was the browser (or for all the browsers under user agent (host) test was done and the times, e.g., FCP time, are average time for all the browsers).  Also, where was the test done from?
Deeply appreciate if you can help.
 
![image](https://user-images.githubusercontent.com/51313035/58999377-5a4a5b00-87ba-11e9-9320-e54b161a7c31.png)

**Comment by patrickhulce** [comment]
> what was the browser

`User agent (host)` is the user agent of the browser that was used on. In this case the one on your machine.

> Also, where was the test done from?

Your machine! When you run CLI/DevTools/Extension/node it's always run from your machine, your data is not sent anywhere.
