### ISSUE TITLE
Lighthouse in Chrome Canary Version 77.0.3814.1 won't run (=hangs)

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/lighthouse#9117]
#### Provide the steps to reproduce
1. Run LH on <affected url>
Open Chrome Canary Version 77.0.3814.1
Navigate to google.com
Run Lighthouse with all selections checked, either mobile or desktop, any level of throttling
#### What is the current behavior?
It hangs and does not progress past the "warming up" message; the browser locks up and has to be closed to exit out of the process.
#### What is the expected behavior?
The expected audit sequence

#### Environment Information
* Affected Channels: 
* Lighthouse version: I can't tell because it never finishes. It's whatever is shipped with the current Canary.
* Node.js version:
* Operating System: Windows 8.1

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @tmb-github! See #9094 for details.
