### ISSUE TITLE
Enable text compression inaccurate

### ISSUE THREAD

**Issue by priyankinfinnov** [GoogleChrome/lighthouse#9119]
Running an audit for https://cutshort.io/jobs/startup-jobs url on chrome 74 windows 10.

The page requires https://cdn.cutshort.io/public/webassets/6.0.177/unauth_min.js which while uploading to cdn is gzipped and then uploaded. Hence, irrespective of the request accept-encoding header it will return a gzipped file.

Lighthouse should not mark it is non-compressed.

**Comment by patrickhulce** [comment]
Thanks for filing @priyankinfinnov! I'm not able to reproduce this issue with latest version of Lighthouse (or in stable Chrome for that matter).

![image](https://user-images.githubusercontent.com/2301202/58898155-8f25b780-86bf-11e9-89ce-fbb9166a1d67.png)

**Comment by priyankinfinnov** [comment]
I checked from a different machine and it works. Not sure what's wrong with mine.
Will close the issue. Thanks again.
