### ISSUE TITLE
Add Accessibility Test For Mis-ordered Headings

### ISSUE THREAD

**Issue by a11ySherpa** [GoogleChrome/lighthouse#9120]
As Lighthouse accessibility tests are from Deque aXe, please add test support for proper heading structure as they have.  
![AxeHeadings](https://user-images.githubusercontent.com/13452692/58899024-ef215b80-86c9-11e9-8913-7b0996fb2a68.PNG)
![LighthouseHeadings](https://user-images.githubusercontent.com/13452692/58899029-f183b580-86c9-11e9-9b1e-eb3e3e8d7f42.PNG)

**Comment by brendankenny** [comment]
[`heading-order`](https://dequeuniversity.com/rules/axe/3.2/heading-order) is a Deque "Best Practice" rule, while Lighthouse generally only [includes the rules tagged as `wcag2a` and `wcag2aa`](https://github.com/GoogleChrome/lighthouse/blob/5debdde366042724dc102a6a5a75fd1f38f7222a/lighthouse-core/gather/gatherers/accessibility.js#L24-L50). I don't know if I see us expanding the scope of the tests to include all the possible aXe rules, but I'll add `heading-order` to the list of rules being considered for addition in #7127.

#7208 is also circling around a similar check.
