### ISSUE TITLE
Google page speed cached

### ISSUE THREAD

**Issue by Razorrank** [GoogleChrome/lighthouse#9125]
We used Google Page Insight on one of our client's domains. Recently we installed a plugin to merge CSS files. When we open the client website in the incognito window we see one single CSS file but Google page insight is still showing the old version with many CSS files. First I thought it is a cache. Now it is more than 3days and still Google page insight showing multiple CSS files on the site that we can't see them in the browser inspector or source code.

**Comment by patrickhulce** [comment]
What is the URL? Are you testing with the same user-agent that PageSpeed sends? `Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse`

**Comment by Razorrank** [comment]
@patrickhulce , I tried Googlebot but I wasn't sure what is the exact user-agent. I just tested with the user agent provided by you and it seems the plugin is responding differently to that. 
I need to follow up with the author of the plugin. We can close this issue. Thank you
