### ISSUE TITLE
Enable tools menu in DevTools

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9134]
We currently disable the export menu in DevTools:

```
/*
      Some features in the export drop down menu don't work in the DevTools
      client. They could with some tweaks, but currently they don't. For example:
      Saving as HTML/JSON - does not bring up a file dialog, as one would expect in DevTools.
                            also, it saves the AuditsPanel HTML, which is funky.
    */
    .lh-devtools .lh-export__button {
      display: none;
    }
```

Need to:

1. Override _saveFile in Audits panel, and use the DevTools save functionality instead. Difference being that the system file dialog prompt will open.
2. `getReportHtml` currently causes the entire DevTools app's HTML to be saved. Could change `this._document.documentElement` to `_getScrollParent` - but, it wouldn't create a well-formed HTML file. I think we'd have to override `getReportHtml` in DevTools, and regenerate the report but with `Lighthouse.ReportGenerator.generateReportHtml` - that uses `report-template.html`, which the normal DevTools flow _does not_.

For 1, maybe we could just change the normal report to open with a file system dialog?

With this, do we want to scratch [this Chromium change](https://chromium-review.googlesource.com/c/chromium/src/+/1575021) - and remove the "save" action from the Audits panel?

**Comment by brendankenny** [comment]
> For 1, maybe we could just change the normal report to open with a file system dialog?

not sure what this means...normal report like in `report-ui-features.js`?

>  I think we'd have to override getReportHtml in DevTools, and regenerate the report but with Lighthouse.ReportGenerator.generateReportHtml

this is the approach `viewer-ui-features.js` takes, so would be good to match unless we come up with something better for there, too

**Comment by Hoten** [comment]
> not sure what this means...normal report like in report-ui-features.js?

yeah, the default behavior of the regular report experience

**Comment by brendankenny** [comment]
I don't believe it's possible to open the "Save As" dialog from normal js. The best we can do is what it's currently doing, using an `<a href="bloburl" download="report.html">` to trigger the download.

Or do you mean "change the normal report to open with a file system dialog" like change it when in devtools (though a `devtools-ui-features.js` or whatever)? If so, I apologize for drawing this all out :)

**Comment by Hoten** [comment]
I'd prefer to change the default behavior to the "Save As" dialog. If that's not possible, we can override `_saveFile` in DevTools. We used to override ReportUIFeatures [here](https://cs.chromium.org/chromium/src/third_party/blink/renderer/devtools/front_end/audits/AuditsReportRenderer.js?sq=package:chromium&dr=CSs&g=0), but it was removed. Can just add it back.

**Comment by patrickhulce** [comment]
Oh boy, yeah now I'm confused too. I thought @Hoten was saying we get rid of the download button and make the normal `ui-features` aka "tools dropdown" now in devtools trigger the filesystem. 

I'm not aware of a way to force a "Save as..." dialog from JS either. If you were talking about changing our non-devTools flow.

**Comment by Hoten** [comment]
> Oh boy, yeah now I'm confused too. I thought @Hoten was saying we get rid of the download button and make the normal ui-features aka "tools dropdown" now in devtools trigger the filesystem.

I _am_ saying that :p

i've managed to confuse everyone :(

**Comment by Hoten** [comment]
I was hoping the fix for 1. would involve changing `report-ui-features`, instead of overriding it in DevTools. But it seems we can't "save as" in pure js (need a server  component, some response with `attachment` disposition)

**Comment by patrickhulce** [comment]
> need a server component, some response with attachment disposition

Not to derail but now I'm curious, does that work? I've been under the impression if the user has the "Ask where to save each file before downloading" unchecked it will still just automatically download to downloads folder no matter how hard you try. Otherwise `download=` should give us the same behavior as the server `attachment` approach.

**Comment by Hoten** [comment]
huh, never realized that was based on a browser user setting too. apparently, neither does anyone else online discussing how to do a "save as" :/

**Comment by Hoten** [comment]
> With this, do we want to scratch this Chromium change - and remove the "save" action from the Audits panel?

btw we are scratching this.

**Comment by patrickhulce** [comment]
> btw we are scratching this.

Scratching the Chromium change? Or scratching the scratch of the Chromium change? :)

**Comment by Hoten** [comment]
I've abandoned the Chromium change.

BTW I failed to realize that printing also needs to be supported differently. More deets soon when I open the PRs.

**Comment by BigBlueHat** [comment]
So...if I'm following all this correctly, the existing JSON export feature is being removed and theirs now only a print option for the report?

**Comment by Hoten** [comment]
The existing button for "save as json" will go away, but it's functionality will move to the tool menu (which is currently hidden in DevTools):

![image](https://user-images.githubusercontent.com/4071474/59211064-d4386680-8b63-11e9-941d-bad6fa5d72e0.png)

**Comment by connorjclark** [comment]
https://chromium.googlesource.com/chromium/src/+/05ecc20fecdd57fcb7f1a8c6c7b72713e6011ddf

Will be enabled in the next canary. Will be in stable M77 Sep 10.
