### ISSUE TITLE
RPC::SERVER_ERROR from PSI

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#9136]
>Guys google can't crawl and index almost half of my links, so my visitors became half of less since 1st of April.
>
>In my last clue, I noticed, even pagespeed can't crawl it:
>
>https://www.ajibtarin.com/facts/3556/%d8%ad%d9%82%db%8c%d9%82%d8%aa-%d8%b4%da%af%d9%81%d8%aa-%d9%86%d9%88%d8%b2%d8%a7%d8%af%d8%a7%d9%86/
>
>https://web.dev/measure
>https://developers.google.com/speed/pagespeed/insights/
>
>I get this error:
>Lighthouse returned error: RPC::SERVER_ERROR: Client could not parse server reply; initialization error is: ''
>
>Is there any solution for this?

Making this a new issue.

_Originally posted by @amiremami in https://github.com/GoogleChrome/lighthouse/issues/6802#issuecomment-482668211_

**Comment by exterkamp** [comment]
> I could understand the issue, however, my developer couldn't fix the conflict yet.
> 
> The issue is because of 2 code snippets I am using. Each of these codes separately causes the conflict that google can't crawl my site and I don't know why!
> 
> First one:
> 
> https://i.imgur.com/hj2WfOp.png
> 
> Second one:
> 
> https://i.imgur.com/cJrPIt1.png
> 
> The second one is not so important for me. But the first one is critical. It is a redirection.
> 
> For example this link is redirecting:
> 
> https://www.ajibtarin.com/strange-nature/13766/
> 
> To: (To prevent duplicate content)
> 
> https://www.ajibtarin.com/strange-nature/13766/%D8%B4%DA%AF%D9%81%D8%AA%DB%8C-%D8%B7%D8%A8%DB%8C%D8%B9%DB%8C-%D8%A8%D8%B1%D8%AA%D8%B1-%D8%AC%D9%87%D8%A7%D9%86/
> 
> When I enable this, google can't analyze the site in pagespeed insight and returns:
> 
> "Error: Lighthouse returned error: RPC::SERVER_ERROR: Client could not parse server reply; initialization error is: ''
> 
> So, the google bot also can't crawl the site. Half of my links dropped from google search and not possible to request indexing for them. When I disable these codes, google can crawl the site.
> 
> Do you have any idea?

(Follow up post from @amiremami )

**Comment by connorjclark** [comment]
Can't repro. Please open if this is still occurring.
