### ISSUE TITLE
⛱️ PSI Error-Handling

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#9137]
### Summary
PSI Errors are not helpful to the users :sob:, so let's make em' more useful!

### Issues Where Errors are Just Straight Up Not Having A Good Time
* #6802
* #8557
* #9136
* #8195 (de-duped for this issue)
* #7011 lh-warning styling in report kind of bleeds in

PSI g/ threads:
* [no_fcp](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/GCsNFm4lfHI)
  * [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/1Y7bEu1dnLM), [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/U88ykV9cdiI), [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/VHL5UWgTrsI)
* [err_doc](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/TSnyCcYoEdc)
  * [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/z6NRL2B0rv8)
* [fal_doc](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/pYh4OFX07-s)
* [backend_err :cry: ](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/ODHsc5KA7Vo)
  * [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/nia-xmts9A4), [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/NHHWUwXnviI), [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/FiuxeZhlRHM), [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/mvCLIRCu42s), [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/YMk1UN7_5ao), [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/1dNhxNPH_Bg), [more](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/UI9EAUZJd9U), #9146
* [APP::5: Rendering Canceled - timeout](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/4ZlI9ZW7Zhs)

Errors within audits that are confusing:
* net::ERR_ACCESS_DENIED/net::ERR_FAILED
  * #9038
  * #9033
  * #9276

Other Opportunities
* #7326 <- highlights need of FAQ for known issues
  * #7725 another good FAQ issue
* #8812 Interesting error catching
* [CrUX FAQ](https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/xxQBy33O8FI)

### What Do Errors Look Like?
* Runtime Errors != []
![image](https://user-images.githubusercontent.com/6392995/59071502-c76df700-8873-11e9-8eb4-f936abe013fe.png)

* 1 Form Factor errored, but the other didn't
![image](https://user-images.githubusercontent.com/6392995/59071574-1e73cc00-8874-11e9-8b75-c2dd56f1ee42.png)

* Infamous Backend Error
![image](https://user-images.githubusercontent.com/6392995/59071584-2c295180-8874-11e9-899b-7092d940f1f4.png)

### Recommendations
_In Progress_
* Better Docs on using PSI in general to avoid common pitfalls
* PSI FAQ for v5+ known errors + a reminder to check FAQ before making an issue

**Comment by Hoten** [comment]
I can audit https://www.tensorflow.org/ directly with LR via the demo app. It takes 80+ seconds.

PSI has a 60 second timeout, so of course it doesn't make the cut. But the error I get is just `Backend Error`.

grr

**Comment by connorjclark** [comment]
PSI doubles codes in error messages. ex: `(NO_FCP) (NO_FCP)`

**Comment by jazyan** [comment]
@connorjclark and I found that the [above comment](https://github.com/GoogleChrome/lighthouse/issues/9137#issuecomment-506843912) is not reproducible :slightly_smiling_face:

**Comment by connorjclark** [comment]
We're happy with how we _present_ errors in PSI today. and this is old ui.
