### ISSUE TITLE
Audit icon guffaws, square is not a rectangle

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#9140]
This little square is claustrophobic
![image](https://user-images.githubusercontent.com/6392995/59072161-65fb5780-8876-11e9-807a-013e7e244cf0.png)

@hwikyounglee @Hoten has this been fixed in the LH side and I didn't notice?

1. the square is super skinny i.e. not a square
2. it should be up by the text not centered

**Comment by Hoten** [comment]
just looking at the now deployment...

![image](https://user-images.githubusercontent.com/4071474/59072449-6c3e0380-8877-11e9-9b62-e1e05a62c48a.png)

maybe? there is no warning in the opportunities for the now deployment, so it could be an issue still. got a url?

**Comment by exterkamp** [comment]
That was https://sfgate.com/ iirc

**Comment by brendankenny** [comment]
Closing for #9098
