### ISSUE TITLE
Scrolling via dragging scroll bar causes flicker

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9141]
Grab the scroll bar with your mouse and move it across the sticky header browser. You'll see a nasty flicker as the height of the page toggles back and forth.

Reported from https://bugs.chromium.org/p/chromium/issues/detail?id=971582#c1

**Comment by rchod** [comment]
![Peek 2019-10-10 17-19](https://user-images.githubusercontent.com/623771/66582756-933c7700-eb82-11e9-81e0-5935a020b5b9.gif)

**Comment by brendankenny** [comment]
This issue is open because #9955 didn't address the issue in DevTools. Another report in https://bugs.chromium.org/p/chromium/issues/detail?id=1306442

However, I can't reproduce in DevTools anymore; is it possible it's fixed from all the changes since last year?

**Comment by connorjclark** [comment]
Yeah, looks fixed.
