### ISSUE TITLE
When I check my site(https://www.mangalkeshav.com) for page speed in the tool - Pagespeed insights -  I get Backend error.

### ISSUE THREAD

**Issue by mangalkeshav** [GoogleChrome/lighthouse#9146]
#### Provide the steps to reproduce
1. Run LH on <affected url>

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks, added to #9137
