### ISSUE TITLE
 Irregular "...not respond with a 200 when offline":  depends on throttle

### ISSUE THREAD

**Issue by tvld** [GoogleChrome/lighthouse#9165]
On our  [site](https://www.qrespi.com) created with Vue CLI 3.0, we get:

**With Dev options> Audit, LH 4.2.0:**

1.  No throttling >> PWA is ok
2.  Applied & Simulated Fast 3G and  >>  PWA **fails** on two tests: ` 2- Current page does not respond with a 200 when offline`  and `3 start_url does not respond with a 200 when offline`

**Using the with extension LH 5.1.0:**

1. Simulated throttle(faster) checkmark >> PWA fails with same issue as above
2. Without this checkmark >>  PWA success

To add to the confusion: another app I created  exactly like this site, same service-worker, Docker and Nginx proxy, succeeds always...

**Comment by patrickhulce** [comment]
This is likely because the app takes a bit of time before registering the service worker. In the throttling modes you've described Lighthouse only gives the page 1 second after load/network quiet/CPU quiet to finish up while in the modes where it works we give up to 5 seconds. 

You can control this behavior from the CLI with a custom config (`pauseAfterLoadMs` pass setting), or be sure to call `register` early enough in your application that Lighthouse can detect it and wait for the service worker.

**Comment by tvld** [comment]
Thank you, when I read your answer it sounded really hopeful:))

But now it does not seem to make a difference: I now register the SW first thing and results are the same.  Somehow it takes some time before `` register('service-worker.js', {})`` calls `` registered ()``  I will think more.

That said, I think LH is wrong to report the test message with "does not respond", while it could have mentioned that the response was coming in late: "responded too late" ... would have saved me a couple of hours for sure)))

**Comment by patrickhulce** [comment]
@tvld Your page passes the PWA check using latest Lighthouse for me, but your service worker takes *2 minutes* to install which is probably why other versions gave up. It looks like the service worker is precaching an extraordinary amount (175MB on the first visit is *way* too much, the user definitely doesn't need both `.webm` and `.mp4` full-length hi-res videos cached without their consent).

![image](https://user-images.githubusercontent.com/2301202/59281740-62c4ea80-8c2d-11e9-9fba-46c6c012ed29.png)


Regarding the "does not respond" vs. "responded too late" for registration, if we knew that the app registered a service worker later we wouldn't need to caveat it at all :) The point is just that we never saw a service worker within our time window and the case where a site registers after we're done and never registers at all are identical from our perspective. 

Hope this helps clarify things!

**Comment by tvld** [comment]
Ah. You very right of course. No need to cach any video at all ! ))). Specially not on mobile ))
My bad, thank you ))
