### ISSUE TITLE
Dual focus b/wn sticky header score gauge + highlighter

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#9167]
![image](https://user-images.githubusercontent.com/4071474/59212427-3fd00300-8b67-11e9-9e96-b174b4ccc4d1.png)

From: https://bugs.chromium.org/p/chromium/issues/detail?id=972504#c1

**Comment by brendankenny** [comment]
It seems like the focus ring is revealing the underlying problem of our dom structure being weird (having the highlighter be a child of the first score gauge instead of the sticky header). We put it there for convenience, but I wonder if we can fix it on that level, independent of styling changes?

**Comment by paulirish** [comment]
fixed by #9186
