### ISSUE TITLE
Unable to set cookies when they are added as "--extra-headers"

### ISSUE THREAD

**Issue by mariuspahontu** [GoogleChrome/lighthouse#9178]
Hi,

I'm facing an issue regarding setting cookies using **--extra-headers** option.

I added multiple request headers in the JSON file, everyone of them is set correctly apart of cookie header.

The command which i'm using to set the extra headers is 
`lighthouse --throttling-method=provided --emulated-form-factor=none  https://www.google.com  --extra-headers=path\to\file\headers.json`

The contents of the headers json is below
`{
  "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
  "Accept-Encoding": "gzip, deflate, br",
  "Accept-Language": "en-US,en;q=0.9",
  "Cache-Control": "max-age=0",
  "Connection": "keep-alive",
  "Cookie": "newCookie=True",
  "Host": "www.example.com",
  "Domain": "www.example.com",
  "Upgrade-Insecure-Requests": "0",
  "If-Range": "\"68028a-125f89-58b04205e822f\""
}`

Can you please specify what am I doing wrong and how to set the cookies?

Thanks,
Marius

**Comment by patrickhulce** [comment]
Thanks for filing! This is actively being worked on, see https://github.com/GoogleChrome/lighthouse/pull/9170 and https://github.com/GoogleChrome/lighthouse/issues/6207#issuecomment-500247138 for discussion and progress.
