### ISSUE TITLE
☂️ 👣 Breaking changes for v6

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#9180]
**Summary**

No time like the present to get started on our next breaking changes list :)

- [ ] Remove path support for `--extra-headers` (and possibly `budget-path`?) as now users can use `cli-flags-path`

Possibly:
- [ ] remove `maxWaitForFcp` timeout and look directly for the early load-failure cases (DNS, bad cert, etc) - https://github.com/GoogleChrome/lighthouse/pull/9509#issuecomment-518408375

**Comment by exterkamp** [comment]
Idea: refactor i18n section in proto to use `Map<string, string>` instead of `RendererFormattedStrings`

**Comment by exterkamp** [comment]
Why is `benchmark_index` a DoubleValue in proto when it isn't nullable in ts?

**Comment by connorjclark** [comment]
> Why is benchmark_index a DoubleValue in proto when it isn't nullable in ts?

![image](https://user-images.githubusercontent.com/4071474/62989923-e1413280-bdfe-11e9-93df-1173f3d5fa4b.png)

https://github.com/GoogleChrome/lighthouse/pull/6332

:)

**Comment by patrickhulce** [comment]
That PR is confusing to me, it seems like the conversation all agreed it should be an int but we merged the change to double...?

**Comment by connorjclark** [comment]
lol yeah why did we _round it_ and also _double it_ ...

**Comment by exterkamp** [comment]
Hm, that is weird 😕 😕

**Comment by brendankenny** [comment]
this didn't get long (we probably have forgotten some stuff :), so closing in favor of #9774
