### ISSUE TITLE
Conform to a11y standards for our tools menu

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9183]
See https://github.com/GoogleChrome/lighthouse/pull/9169#issuecomment-500927299

**Comment by patrickhulce** [comment]
Specifically we just need to implement the aria roles piece of https://www.w3.org/TR/2019/NOTE-wai-aria-practices-1.1-20190207/#menubutton, tabbing and popup already work.

**Comment by exterkamp** [comment]
I think #9433 was supposed to close this?
