### ISSUE TITLE
Unused javascript audit title is misleading

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#9189]
**Proposal**:
The `Remove Unused Javascript` title is misleading as it is auditing for unused javascript on page load. 

I propose updating the title from 
`Remove unused JavaScript` to `Defer unused onload JavaScript` 
to remove any communication confusion around exactly what this audit is quantifying.

*I am open to any bikeshedding of the term that communicates that this is measuring `on load` and not JS payload for the entire app functionality*.

code:
https://github.com/GoogleChrome/lighthouse/blob/7750fe465d818a5bfd191ce7d959d82a2052eb8c/lighthouse-core/audits/byte-efficiency/unused-javascript.js#L13

**Comment by sebmck** [comment]
Throwing another suggestion into the mix: "Maximize initial JavaScript usage". The goal being to drive up the amount of used JavaScript on first load. The intention not being to increase actual usage, but to move code outside of the main bundle. I feel that this better encapsulates the original intent "don't ship unnecessary code" while avoiding ambiguity around loading defered code.

**Comment by patrickhulce** [comment]
Thanks for filing! :)

While I mostly agree here and in fact our CSS corollary audit started this way, most users saw "Defer" in the title and had significant confusion with how this is different from deferring below the fold content/removing render blocking resources. We actually moved *from* `Defer unused CSS` *to* `Remove unused CSS` for this reason and settled on the description being responsible for explaining the details of "if this is used on interaction, you're all set, but it's prolly unused"

Good suggestion @sebmck! I like that it sidesteps the confusing defer issue. Although I'm not sure I love the idea of having "Maximize" in the title for similar reasons. We don't really want devs to maximize the amount of anything on the page and I'm worried the fact that it's the *usage* we want them to maximize might get lost :/

The other point I'll try to make with these two audits is that no matter what they will not be able to automatically and efficiently compute what is truly unused in any near-term future. This means that the manual process of identifying the truly unused bits using other tooling is going to happen anyway and *that* seems like the right place to be very careful about this distinction. As a rough cut, "hey go look at this large chunk of unused stuff with another specific tool" it feels right that the typical action will be *removing* that code from the assets that are visible to Lighthouse.

</hopefully-useful-history> :)

**Comment by patrickhulce** [comment]
Also I'm assuming this was sparked by https://twitter.com/katiehempenius/status/1138454313276256257 so linking it here for other readers :)

**Comment by addyosmani** [comment]
I agree a tweak to wording is needed here after reading the thread. Adding more bikeshed ideas:

- Defer JavaScript unused on initial load
- Lazy-load JavaScript unused on initial load 
- Ensure JavaScript loaded is necessary

**Comment by paulirish** [comment]
FWIW in devtools the title was changed from "x bytes used' to "x bytes used so far".
https://bugs.chromium.org/p/chromium/issues/detail?id=97396

**Comment by brendankenny** [comment]
close after #12281?
