### ISSUE TITLE
Report bug from extension popup

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#919]
In cases where we error and immediately quit, we show the exception message, but users don't know how to report this bug

![image](https://cloud.githubusercontent.com/assets/39191/20070430/297f4294-a4d5-11e6-95ff-4cb1273fa204.png)

Let's add a "file bug" link after the exception message?

**Comment by olingern** [comment]
How does something like this sound?

<img width="393" alt="screen shot 2016-11-15 at 7 02 34 am" src="https://cloud.githubusercontent.com/assets/1470297/20305111/d920fcd8-ab01-11e6-8daf-46b2745dc2b1.png">

The report link would prefill a new issue like so:

<img width="861" alt="screen shot 2016-11-15 at 7 02 02 am" src="https://cloud.githubusercontent.com/assets/1470297/20305115/de0811d2-ab01-11e6-94a3-8da0f6444f6c.png">

If that all looks good, I have a PR open over here at #944 with the additions.
