### ISSUE TITLE
Use lighthouse cli behind proxy

### ISSUE THREAD

**Issue by dehghani-mehdi** [GoogleChrome/lighthouse#9190]
Hi,

**Feature request summary**
I don't use Chrome, but I like to use Lighthouse,
I didn't see any proxy option, so is there any solution for it?

**How is this beneficial to Lighthouse?**
Lighthouse become usable to people like me!

Thank you!

**Comment by patrickhulce** [comment]
I'm not sure what you mean exactly by proxy option. Is it just that you want to run Lighthouse without installing Chrome?

If so, you can use [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) or [web.dev](https://web.dev) to get results over the web.

If you meant an HTTP proxy that you want to install Chrome somewhere other than your local machine, you can use `--hostname` and `--port` flags of the CLI to specify the address of the remote machine has Chrome running with a debug port.

**Comment by dehghani-mehdi** [comment]
@patrickhulce by proxy I mean using some sort of VPN, also I have Chrome installed on my machine, I just don't use it/open it. I like to use Lighthouse cli and I know it needs Chrome.

That `--hostname` and `--port` flags sounds great, I'll test that and get back to you asap!

**Comment by patrickhulce** [comment]
Oh, I see now. You mean that you want your local Chrome to use your VPN/proxy settings when navigating to the URL that you give Lighthouse?

You'll want to set Chrome's proxy settings when you start Lighthouse (see [Chromium documentation](https://www.chromium.org/developers/design-documents/network-settings#TOC-Command-line-options-for-proxy-settings)). Example: `lighthouse <example url> --chrome-flags='--proxy-server="proxyhost:8080"'`

**Comment by dehghani-mehdi** [comment]
@patrickhulce thanks for the comment, it works great. maybe you should add this to the readme or something.
