### ISSUE TITLE
can i configure axe rules somehow

### ISSUE THREAD

**Issue by dagda1** [GoogleChrome/lighthouse#9191]
I can see the axe rules defined [here](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/accessibility.js#L34) in the lighthouse source.

Can I provide a custom config file that I specify in the config-path argument?

I'd like do enable and disable my own rules but struggling to know how to this in lighthouse.

**Comment by exterkamp** [comment]
Those are the gather rules which setup gathering config to power those a11y audits.  You probably want to look into the [`Default-Config a11y section`](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/config/default-config.js#L405) as a jumping off place for a custom config.  And the [config README.md](https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md), which explains more about the config that LH uses.

Yeah you should be able to add a custom config with the config-path flag:
```
lighthouse --config-path=path/to/custom-config.js https://example.com
```

**Comment by patrickhulce** [comment]
@exterkamp's excellent custom config suggestion will let you receive fewer of our a11y audit results and let you run your own audits and gatherers to collect whatever you need. If you're hoping to change what *our invocation* of `axe` is running under the hood though, that's currently not possible. You will need to create a custom gatherer that runs axe separately with the extra rules you want, and then create custom audits for each rule you enable.

**Comment by dagda1** [comment]
Thank you for the answers. I am really struggling with how to create my own accessibility audit.

Do you have an example file?

**Comment by patrickhulce** [comment]
Yes see our [custom audit recipe](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit) @dagda1

**Comment by connorjclark** [comment]
Let us know if our docs are unclear on how to proceed. thanks.

But perhaps you'd find more value in the Axe browser extension.
