### ISSUE TITLE
Inconsistent results across pages with the same issues.

### ISSUE THREAD

**Issue by BadRecordLength** [GoogleChrome/lighthouse#9196]
**Summary**
Hi,
I'm testing a site with a consistent navbar across all pages, with a sub-menu that opens on hover and contains images. On some pages of the site it fails the "properly size images" audit with the navbar images being picked up whereas on others it doesn't. It appears to flag this as an issue on pages with less images overall, with pages that have more images in the body not being flagged. Is this due to some kind of weighting (i.e pages with greater issues to fix will not have smaller issues flagged)?
Thanks.

**Comment by patrickhulce** [comment]
Do you have some URLs for us to take a look?

In general, the opportunity will be visible when there is noticeable savings to some important load metric, and hidden when there is not. Individual resources though should be present in the table either way.

**Comment by brendankenny** [comment]
Closing as there hasn't been recent movement on this issue. If you're still seeing a problem, please comment and we can reopen.
