### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#920]
![image](https://cloud.githubusercontent.com/assets/39191/20070430/297f4294-a4d5-11e6-95ff-4cb1273fa204.png)

Reported over email.

I was able to repro locally (ping me if you want the URL) and it's in one of the accessibility audits:

![image](https://cloud.githubusercontent.com/assets/39191/20070614/eed4e0a8-a4d5-11e6-8ace-715b40f6d864.png)

![image](https://cloud.githubusercontent.com/assets/39191/20070546/a7eeb4f2-a4d5-11e6-87bc-a6a083de322d.png)

A few ways to fix this; anybody want to take it?

**Comment by jillesme** [comment]
I'll take this one 😁
