### ISSUE TITLE
Unchecked audits in Extension options leads to error 

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#921]
I unchecked "Best Practices" 
![image](https://cloud.githubusercontent.com/assets/39191/20070724/5da06408-a4d6-11e6-8ac5-47ff56c9ac87.png)

but at the end of the run, it failed with this message 
![image](https://cloud.githubusercontent.com/assets/39191/20070751/7d5bbfae-a4d6-11e6-9c0a-478e0071112c.png)

Pretty sure this is coming from the new https://github.com/GoogleChrome/lighthouse/pull/914 so we'll need to adjust things to allow this usecase.

@wardpeet can you look at this?

**Comment by paulirish** [comment]
Also let's treat this as a blocker for any new extension release.

**Comment by brendankenny** [comment]
Yeah, this isn't completely fixed.

**Comment by wardpeet** [comment]
@brendankenny should I have a look?

**Comment by brendankenny** [comment]
> should I have a look?

I have a fix (needed to filter the aggregations in addition to the audits), but will wait for the morning to push
