### ISSUE TITLE
Audit for preventing mismatched mime types (x-nosniff)

### ISSUE THREAD

**Issue by michaelWoe** [GoogleChrome/lighthouse#9214]
#### Provide the steps to reproduce
1. Run LH on [https://developers.google.com/speed/pagespeed/insights](https://developers.google.com/speed/pagespeed/insights)
2. Audit a page which set `Content-Type: image/webp` on `jpg` and/or `png` images

#### What is the current behavior?
1. Page passes `Serve images in next-gen formats` test even though it doesn't serve images in next-gen formats
2. Pages which deliver `jpg` and `png` images with `Content-Type: image/webp` get better results

#### What is the expected behavior?
1. Audit detects `jpg` or `png` images with `Content-Type: image/webp` are no next-gen formats (e.g. check if the file extension of those images is `webp`)
2. Consider adding penalty points in ranking at pages which deliver no next-gen images but cheat by delivering images with a wrong `Content-Type`

**Comment by connorjclark** [comment]
```
Audit detects jpg or png images with Content-Type: image/webp are no next-gen formats (e.g. check if the file extension of those images is webp)
```

This is where we gather from Chrome what the file size would be, given the response were encoded in jpeg vs webp: [click](https://github.com/GoogleChrome/lighthouse/blob/7750fe465d818a5bfd191ce7d959d82a2052eb8c/lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js#L99)

This is where we audit for next-gen formats: [click](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/uses-webp-images.js#L88)

It seems we don't look at the content headers for anything here, so it's unclear at first glance how lying about the `Content-Type` would affect this audit. Do you have a repro you could share?

```
Consider adding penalty points in ranking at pages which deliver no next-gen images but cheat by delivering images with a wrong Content-Type
```

We don't deal with page rank :)

I'm curious how Chrome handles wrong content types. Maybe it ignores them? Do the images still load correctly? Are there any errors in the console? A repro would help us rule some things out.

**Comment by patrickhulce** [comment]
Also worth noting here that we will ignore any results that appear to have inconsequential savings by converting to WebP. We don't want developers to convert to WebP just for the sake of it, we only want them to do it when there's a substantial win to be had! :)

**Comment by michaelWoe** [comment]
Unfortunatly I don't have a repo to share but was able to reproduce the behaviour.

**Steps to reproduce the behavior**
1. If you add the following to the `htaccess` file of an Apache from a page which doesn't pass the `Serve images in next-gen formats` test
```
<IfModule mod_headers.c>
   SetEnvIfNoCase Accept image/webp HAVE_Accept_webp
   <FilesMatch "\.(jpe?g)$">
      Header set Content-Type "image/webp" env=HAVE_Accept_webp
   </FilesMatch>
</IfModule>
```
2. Audit the page again and it will pass the `Serve images in next-gen formats` test even if there would be a substantial win if the images were 'real' `webp` images.

The images, of a page which set `Content-Type: image/webp` on `jpg` and/or `png` images and I don't want to mention here, load correctly and there are no errors in the console.
If I copy the image url in Internet Explorer the `Content-Type` header is `image/jpg` for a `jpg` or `image/png` for a `png`.

I also downloaded a `png` image of that page and opened it with [https://squoosh.app](https://squoosh.app) to test the original `png` image vs. a `wepb` image with 90% quality.
The potential savings for that image would be 92% and it still passed the test.

**Comment by brendankenny** [comment]
> Pages which deliver jpg and png images with `Content-Type: image/webp` get better results

It's important to note that the performance score is based *only* on the metrics for how the page loaded. The results in the "Opportunities" section (like `next-gen formats`) are just suggestions by Lighthouse on how to improve page load time.

If there is a bug here and Lighthouse is being fooled, sites that use this technique are only affecting the suggestions Lighthouse offers, not their score in any way.

**Comment by brendankenny** [comment]
> If I copy the image url in Internet Explorer the Content-Type header is image/jpg for a jpg or image/png for a png.

This is presumably because of the `SetEnvIfNoCase Accept image/webp` line. Internet Explorer doesn't support webp.

**Comment by brendankenny** [comment]
> @connorjclark 
> EDIT: I take that back. we check mimeType [here](https://github.com/GoogleChrome/lighthouse/blob/7750fe465d818a5bfd191ce7d959d82a2052eb8c/lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js#L54) which ignores webp.

Just confirmed this happens by forcing our test `static-server.js` to always use `'image/webp'` and running the byte-efficiency smoke test, and all the lying jpgs are indeed filtered out on that line.

> If the images still load correctly, I'd expect mimeType to really be `png/jpg` despite the `Content-Type` header (would show that Chrome ignores the header). If the images don't load, then the mimeType would be `webp`, and thus would explain the better scores.

The images do load, and the debugger protocol will happily report the `'image/webp'` mimeType it was told via `Content-Type` , it's just that the renderer doesn't care and renders them regardless of reported mime type (because why not if it knows how to render them).

I don't see anything in the protocol traffic that could help us identify the mismatch (I assume this is why the DevTools network panel shows the same thing), so there's not much we can do on that end.

Possible options:
1) Don't care, fix your server :)
2) Add something to the protocol to figure out the *actual* image type. Maybe something like this already exists, it just has to be called manually (it might not be known yet when `Network.responseReceived` is emitted)
3) Don't filter out webp images and try optimizing them regardless of type in the `OptimizedImages` gatherer.

(2) would be nice, if only because audits using `OptimizedImages` or `ImageElements` might benefit from knowing what type an image actually is.

**Comment by patrickhulce** [comment]
1 and 2 are the options I prefer :)

I would be against 3 for the same reason we filter out other explicit actions against our advice. If you've taken the time to move to WebP and you wanted a quality setting higher than our threshold, just go for it, we shouldn't bother.

**Comment by patrickhulce** [comment]
We've decided this is best solved by an audit that flags requests that are served with a mismatched mime type to their content.

**Comment by brendankenny** [comment]
> We've decided this is best solved by an audit that flags requests without x-nosniff. If anyone would like to write this complete audit proposal, be our guest :)

Turns out we have another suggestion for this over in #2585 :) Deduping there, though it also needs a complete proposal.
