### ISSUE TITLE
Report Download Format

### ISSUE THREAD

**Issue by MarcusMorba** [GoogleChrome/lighthouse#9215]
**Feature request summary**

A report download when using chrome - audit report which I can immediately share and forward to developers or managers in a better human readable format like PDF.
 

**What is the motivation or use case for changing this?**
I want to share the issues in a human readable format.

**How is this beneficial to Lighthouse?**
A better UX for your users.

**Comment by MarcusMorba** [comment]
I would directly love to download a PDF of this view: https://googlechrome.github.io/lighthouse/viewer/

**Comment by connorjclark** [comment]
dupe #9134

the Lighthouse changes have already landed, and the Chromium changes are pending. I'd expect it in stable M77 (sept 10) / canary by perhaps next week.

**Comment by connorjclark** [comment]
In the meantime, you could use https://developers.google.com/speed/pagespeed/insights/

**Comment by brendankenny** [comment]
See the issue @connorjclark linked for printing in DevTools, but for PDF in particular we rely on the system to provide this. Select "Print", then the system print dialog will usually have an option of printing to a PDF (if you run Windows < 10 you may need to manually install a PDF printer).
