### ISSUE TITLE
Pagespeed Insights suddenly started giving a score of 0

### ISSUE THREAD

**Issue by Sagart-cactus** [GoogleChrome/lighthouse#9221]
Our page https://www.editage.jp/ earlier used to score a decent rank in higher 80s for desktop. Now I know that the score differs on every run, but a sudden score of 0 is a bit of shock to me. The result has shown that my style.css which is of mere 74KB took 8 seconds to load. Another thing which is weird that every time I run the PSI I get the same timing of 18.2 sec in all the metrics (First Meaningful Paint, First Contentful Paint, Speed Index). Have tried to search a lot in the existing issues but everything is related to some bug in Lighthouse which is already fixed. Can anyone help me in this regard? 
![PageSpeed Insights (2)](https://user-images.githubusercontent.com/7487200/59614714-e5bed700-913e-11e9-8f03-86fa712eb95f.png)

**Comment by connorjclark** [comment]
Hi @Sagart-cactus, thanks for the report and sorry you're seeing such drastic differences now.

I noticed this error:
```
Fatal trace logic error - expected start event, got X
```
May not be the culprit, but I'll link to the issue for this, so there's a good repro for it: #7764.

I also notice a very large render blocking script, that seems to actually be unused (the `style.css`):

![image](https://user-images.githubusercontent.com/4071474/59631345-6c05f980-90fc-11e9-993e-8bc7caf24bde.png)

Can you confirm if this resource was present before your scores fell to zero?

**Comment by Sagart-cactus** [comment]
Thanks for the reply @connorjclark. Well, I am not proud of the CSS written in style.css but yes the score was around 80s on Thursday(13 Jun) and Friday(14 Jun) with no code changes in style.css. And for some reason, the page load time during the PSI test is really very high.

**Comment by Sagart-cactus** [comment]
After checking the logs I was able to pinpoint the exact reason for this error. It was related to some PWA setting which resulted in some hits from PSI being served through serviceworker.js, for now, I disabled the PWA settings and everything is back to normal. @connorjclark thank you for your help.

**Comment by MrCarlLister** [comment]
@Sagart-cactus PWA settings were the reason I was experiencing a similar issue.
