### ISSUE TITLE
ERRORED_DOCUMENT_REQUEST (500)

### ISSUE THREAD

**Issue by aaaroaaa** [GoogleChrome/lighthouse#9228]
#### Provide the steps to reproduce:
1. go to https://developers.google.com/speed/pagespeed/insights/?hl=en
2. type in url -  https://www.meinprospekt.de/angebote/cola/lidl
3. press 'analyse'

#### What is the current behavior?
You can observe the error:
Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 500)

#### What is the expected behavior?
I'm able to see 'insights'.

#### more info 
I've saw [this bug description](https://github.com/GoogleChrome/lighthouse/issues/2784)
but all suggested solutions seems to be implemented already, but I still get this error.

is there a way to solve this issue ? 

Btw, this site is working with lighthouse audit (from devtools in chrome). Don't know if it can help you.

**Comment by aaaroaaa** [comment]
necessarily-wide-alpaca

it seems to be a different one

**Comment by aaaroaaa** [comment]
necessarily-wide-alpaca

**Comment by patrickhulce** [comment]
@aaaroaaa this case is well described in #2784 and isn't substantially different. 

The page is replying with a server error status code (`500 Internal Server Error`) and not a real page. PSI will only audit non-error pages.

**Comment by brendankenny** [comment]
@aaaroaaa we're working on ways to make the error shown a little more helpful (like a link to an faq) in #9137

**Comment by aaaroaaa** [comment]
oh, yeah. it is because of problem with cookies on the server side. As I found out - localy I had required cookies and everything worked smoothly.
Thank you a lot and sorry for disturbing.

**Comment by thomwoz** [comment]
Hello,
my issue is very similar. I can successfully perform test using Pagespeed UI or when I request data from my application run locally, but when try to perform test and request from my AWS server, pagespeed responds with ERRORED_DOCUMENT_REQUEST. 
So I guess there is some issue on my AWS server, I am able to get the results requesting from other places. 
Do you have any idea what might be wrong?

**Comment by reubano** [comment]
I'm getting a similar error, but curl works fine

Oops! Something went wrong.
Lighthouse returned error: `ERRORED_DOCUMENT_REQUEST`. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403)

```bash
curl -vvvv https://loa.nerevu.com
*   Trying 3.232.242.170:443...
* Connected to loa.nerevu.com (3.232.242.170) port 443 (#0)
* ALPN, offering http/1.1
*  CAfile: /opt/local/share/curl/curl-ca-bundle.crt
*  CApath: none
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=loa.nerevu.com
*  start date: Nov  8 00:10:48 2021 GMT
*  expire date: Feb  6 00:10:47 2022 GMT
*  subjectAltName: host "loa.nerevu.com" matched cert's "loa.nerevu.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET / HTTP/1.1
> Host: loa.nerevu.com
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: Cowboy
< Connection: keep-alive
< X-Dns-Prefetch-Control: off
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=15552000; includeSubDomains
< X-Download-Options: noopen
< X-Content-Type-Options: nosniff
< X-Xss-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Expires: -1
< Accept-Ranges: bytes
< Last-Modified: Fri, 29 Oct 2021 18:10:40 GMT
< Etag: W/"a30-17ccd3f2500"
< Content-Type: text/html; charset=UTF-8
< Content-Length: 2608
< Vary: Accept-Encoding
< Date: Mon, 22 Nov 2021 02:56:09 GMT
< Via: 1.1 vegur
```
