### ISSUE TITLE
Getting ChromeLauncher Waiting for browser 

### ISSUE THREAD

**Issue by VishalShahare** [GoogleChrome/lighthouse#9239]
steps followed:
1. installed chrome version. {version 75.0.3770.100 (Official Build) (64-bit)}
1. installed latest version of node. {10.16.0}
2. version of npm. {6.9.0}

after running command : 
I am getting below output and nothing is happening after chrome launch:

C:\Users\ABCD>lighthouse http://www.sustainablesites.org --verbose --output=json --output-path=report.json
  ChromeLauncher:verbose created C:\Users\ABCD\AppData\Local\Temp\lighthouse.46360315 +0ms
  ChromeLauncher:verbose Launching with command:
  ChromeLauncher:verbose "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-translate --disable-extensions --disable-background-networking --safebrowsing-disable-auto-update --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --remote-debugging-port=33244 --user-data-dir=C:\Users\ABCD\AppData\Local\Temp\lighthouse.46360315 about:blank +8ms
  ChromeLauncher:verbose Chrome running with pid 49140 on port 33244. +48ms
  ChromeLauncher Waiting for browser. +1ms
  ChromeLauncher Waiting for browser... +0ms
  ChromeLauncher Waiting for browser..... +2s
  ChromeLauncher Waiting for browser....... +2s
  ChromeLauncher Waiting for browser......... +2s
  ChromeLauncher Waiting for browser........... +2s
  ChromeLauncher Waiting for browser............. +2s
  ChromeLauncher Waiting for browser............... +2s
  ChromeLauncher Waiting for browser................. +2s
  ChromeLauncher Waiting for browser................... +2s
  ChromeLauncher Waiting for browser..................... +2s
  ChromeLauncher Waiting for browser....................... +2s
  ChromeLauncher Waiting for browser......................... +2s
  ChromeLauncher Waiting for browser........................... +2s
  ChromeLauncher Waiting for browser............................. +2s
  ChromeLauncher Waiting for browser............................... +2s
  ChromeLauncher Waiting for browser................................. +2s
  ChromeLauncher Waiting for browser................................... +2s
  ChromeLauncher Waiting for browser..................................... +2s
  ChromeLauncher Waiting for browser....................................... +2s
  ChromeLauncher Waiting for browser......................................... +2s
  ChromeLauncher Waiting for browser........................................... +2s
  ChromeLauncher Waiting for browser............................................. +2s
  ChromeLauncher Waiting for browser............................................... +2s
  ChromeLauncher Waiting for browser................................................. +2s
  ChromeLauncher Waiting for browser................................................... +2s
  ChromeLauncher Waiting for browser..................................................... +2s
  ChromeLauncher Waiting for browser....................................................... +2s
  ChromeLauncher Waiting for browser......................................................... +2s
  ChromeLauncher Waiting for browser........................................................... +2s
  ChromeLauncher Waiting for browser............................................................. +2s
  ChromeLauncher Waiting for browser............................................................... +2s
  ChromeLauncher Waiting for browser................................................................. +2s
  ChromeLauncher Waiting for browser................................................................... +2s
  ChromeLauncher Waiting for browser..................................................................... +2s
  ChromeLauncher Waiting for browser....................................................................... +2s
  ChromeLauncher Waiting for browser......................................................................... +2s
  ChromeLauncher Waiting for browser........................................................................... +2s
  ChromeLauncher Waiting for browser............................................................................. +2s
  ChromeLauncher Waiting for browser............................................................................... +2s
  ChromeLauncher Waiting for browser................................................................................. +2s
  ChromeLauncher Waiting for browser................................................................................... +2s
  ChromeLauncher Waiting for browser..................................................................................... +2s
  ChromeLauncher Waiting for browser....................................................................................... +2s
  ChromeLauncher Waiting for browser......................................................................................... +2s
  ChromeLauncher Waiting for browser........................................................................................... +2s
  ChromeLauncher Waiting for browser............................................................................................. +2s
  ChromeLauncher Waiting for browser............................................................................................... +2s
  ChromeLauncher Waiting for browser................................................................................................. +2s
  ChromeLauncher Waiting for browser................................................................................................... +2s
  ChromeLauncher Waiting for browser..................................................................................................... +2s
  ChromeLauncher Waiting for browser....................................................................................................... +2s
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:33244 +1s
  ChromeLauncher:error Logging contents of C:\Users\ABCD\AppData\Local\Temp\lighthouse.46360315/chrome-err.log +4ms
  ChromeLauncher:error  +1ms
Unable to connect to Chrome

Please suggest.

**Comment by patrickhulce** [comment]
By "nothing is happening after chrome launch" do you mean that you can't see Chrome launched at all, or that Chrome launches but then it just sits there waiting for browser?

**Comment by VishalShahare** [comment]
I can see chrome is getting launched successfully but then lighthouse is waiting for browser.As mentioned above in output we are getting message "ChromeLauncher Waiting for browser......."

**Comment by patrickhulce** [comment]
What happens if you run 

`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-translate --disable-extensions --disable-background-networking --safebrowsing-disable-auto-update --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --remote-debugging-port=33244 --user-data-dir=C:\Users\ABCD\AppData\Local\Temp\lighthouse.46360315 `

and then visit in another browser `http://localhost:33244/json/list`?

**Comment by VishalShahare** [comment]
Hi Patrick,

I am getting below message after running above chrome launch command and visiting another browser with URL http://localhost:33244/json/list.

Message -->
This site can’t be reached localhost refused to connect.
Search Google for localhost 33244 json list
ERR_CONNECTION_REFUSED

**Comment by patrickhulce** [comment]
Ah, this is not a problem with Lighthouse then. You'll need a fully working version of Chrome on your machine in order to run Lighthouse.

Try to get Chrome launching with that `/json/list` URL working before trying to run Lighthouse programmatically.
