### ISSUE TITLE
Consistent long frame warning.

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#924]
After looking at:
http://electionlandtrends.appspot.com/

and wondering what lighthouse could do to warn against the perf problems here, I think that we could have an audit that would look at N number of frames and complain if a given % of them were over a fixed number... which would be indicative of many "long frames" aka jank.

**Comment by paulirish** [comment]
This would be useful as a diagnostic for understanding your TTI, as well.
This is also quite easy, as we already have all the long tasks.

**Comment by paulirish** [comment]
duping into #9921
