### ISSUE TITLE
What could be the reason for "scripting" to equal 0?

### ISSUE THREAD

**Issue by radical-edo** [GoogleChrome/lighthouse#9250]
Hello,

have a bit of conundrum. All the 3 measurements for `bootup-time` metric (`scripting`, `total`, `scriptParseCompile` are working for most of my scripts in my site. However, there is one, quite important one, that the `scripting` metric is equal `0`.
My questions is - what could be a possible reason for not being able to measure that metric?
The `scriptParseCompile` is measured if that could suggest some sort of answer to this specific problem.

**Comment by patrickhulce** [comment]
Certain types of async work are not attributable to any script given the way we currently instrument the page. If the script does mostly this type of work, then you might end up seeing `0 ms` of script execution for it. We want to try to close this loophole, but it is at least several months away as the workaround is quite expensive.

If it's not doing any async work and it's pretty much all in a single EvaluateScript that we aren't capturing, then a repro URL would be super helpful :)

**Comment by brendankenny** [comment]
let's move conversation into #9200
