### ISSUE TITLE
FontSize Gatherer fails with "Could not find node with given id"

### ISSUE THREAD

**Issue by PostaliDan** [GoogleChrome/lighthouse#9255]
#### Provide the steps to reproduce
1. Run LH on https://www.custislawpc.com/
  

#### What is the current behavior?
FontSize Gatherer fails with "Required FontSize gatherer encountered an error: Protocol error (CSS.getMatchedStylesForNode): Could not find node with given id"

Google displays '?' most of the time when running report.
![image](https://user-images.githubusercontent.com/44680753/59930322-b7781a80-9410-11e9-9d50-9f758561f24c.png)
![image](https://user-images.githubusercontent.com/44680753/59930376-cb238100-9410-11e9-90a4-482f96d75ad6.png)

#### What is the expected behavior?
SEO category score is given, FontSize gatherer does not fail.

#### Environment Information
* Affected Channels: Extension, Devtools
* Lighthouse version: 5.1.0.1
* Node.js version:
* Operating System: WIndows 10, Apple Laptop

**Related issues**

**Comment by brendankenny** [comment]
I'm not able to repro. @patrickhulce from your change, does that mean you are able to get the error?

**Comment by patrickhulce** [comment]
Oh yes I was able to repro on that URL. This sort of error is quite likely to be intermittent though, so that's certainly possible in this case.

**Comment by connorjclark** [comment]
Can still repro.

**Comment by connorjclark** [comment]
There is an element `Remaining Time` that gets re-made frequently (it is counting down). This is just a timing issue - we learn about a node, but only ask for more data about it later. In between the page could have deleted the node.
