### ISSUE TITLE
opn is deprecated, switch to open 

### ISSUE THREAD

**Issue by jamesgeorge007** [GoogleChrome/lighthouse#9265]
**Summary**
[opn](https://www.npmjs.com/package/opn) is deprecated and renamed to [open](https://www.npmjs.com/package/open). But, it isn't compatible with node-js version 6.

**Comment by patrickhulce** [comment]
Thanks @jamesgeorge007! Interested in moving us there? :)

For any potential implementers, node version 6 compat is not an issue for us because we only support node 10 LTS moving forward.

**Comment by jamesgeorge007** [comment]
@patrickhulce As I'm unfamiliar with the code-base it would be great if you could point me to the files hainv an entry of `opn` :clap:

**Comment by patrickhulce** [comment]
Looks like just `lighthouse-cli/run.js`! Though we apparently reference it in our README as well.

```bash
> grep -rE "\bopn\b" --exclude-dir=node_modules .
./changelog.md:* b2ccdfcb Allow opn & update-notifier CLI deps to be optional. (#2150)
./changelog.md:- Add [`opn`](https://www.npmjs.com/package/opn) - #1130
./docs/readme.md:| `view` | Ignored, use the `opn` npm module if you want this functionality. |
./yarn.lock:"@types/opn@^3.0.28":
./yarn.lock:  resolved "https://registry.yarnpkg.com/@types/opn/-/opn-3.0.28.tgz#097d0d1c9b5749573a5d96df132387bb6d02118a"
./yarn.lock:    opn "4.0.2"
./yarn.lock:opn@4.0.2:
./yarn.lock:  resolved "https://registry.yarnpkg.com/opn/-/opn-4.0.2.tgz#7abc22e644dff63b0a96d5ab7f2790c0f01abc95"
./package.json:    "@types/opn": "^3.0.28",
./package.json:    "opn": "4.0.2",
./lighthouse-cli/run.js:const opn = require('opn');
./lighthouse-cli/run.js:        opn(outputPath, {wait: false});
