### ISSUE TITLE
Browser errors were logged to the console

### ISSUE THREAD

**Issue by progr000** [GoogleChrome/lighthouse#9276]
Resource is accessable, even though web.dev says it is not.

URL | Description
-- | --
…css/style_00.css?v=154…(pvtbox.net) | Failed to load resource: net::ERR_ACCESS_DENIED
…css/style_01.css?v=156…(pvtbox.net) | Failed to load resource: net::ERR_ACCESS_DENIED
…css/style_02.css?v=154…(pvtbox.net) | Failed to load resource: net::ERR_ACCESS_DENIED
…css/style_03.css?v=154…(pvtbox.net) | Failed to load resource: net::ERR_ACCESS_DENIED
…css/style_04.css?v=154…(pvtbox.net) | Failed to load resource: net::ERR_ACCESS_DENIED
…css/style_05.css?v=156…(pvtbox.net) | Failed to load resource: net::ERR_ACCESS_DENIED
…css/style_06.css?v=156…(pvtbox.net) | Failed to load resource: net::ERR_ACCESS_DENIED

**Comment by patrickhulce** [comment]
Thanks @progr000 this is tracked as part of #9137.

**Comment by exterkamp** [comment]
I think this is actually separate.  Has to do with the css not being loaded properly in the rendering infra I think.  This might be handled as part of #9137, but is also something to look at within LR.

**Comment by patrickhulce** [comment]
Hm @exterkamp should we split out the whole `Errors within audits that are confusing:

net::ERR_ACCESS_DENIED/net::ERR_FAILED` section from #9137 then?

**Comment by exterkamp** [comment]
Oh yeah!  This should go in that section, u right.  I'll close this as part of that then.
