### ISSUE TITLE
PROTOCOL_TIMEOUT with bsd.sos.in.gov/publicbusinesssearch

### ISSUE THREAD

**Issue by andykar33** [GoogleChrome/lighthouse#9277]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by andykar33** [comment]
![image](https://user-images.githubusercontent.com/49259310/60113273-04246400-9737-11e9-8609-80416c2facc9.png)

**Comment by patrickhulce** [comment]
Thanks @andykar33, this is tracked over in #6512.
