### ISSUE TITLE
Recommendation: Optimize for search indexability

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#928]
Nice document of recommendations from Search: https://webmasters.googleblog.com/2016/11/building-indexable-progressive-web-apps.html

Rather than trying to detect these things, I think we can just link to the document and tell users to do what's appropriate.

**Comment by patrickhulce** [comment]
@rviscomi FYI if you want to incorporate any of the notes here in SEO audits and prioritize accordingly? We're fine with closing if you're not interested.

**Comment by rviscomi** [comment]
@patrickhulce thanks for flagging this for me.

After reviewing the page, everything mentioned there was addressed in some way during our exploration of potential audits. So this issue should be good to close now.

**Comment by patrickhulce** [comment]
Awesome thanks for taking a look @rviscomi !
