### ISSUE TITLE
Page Speed Insight scores do not match Lighthouse scores in chrome dev tools

### ISSUE THREAD

**Issue by nragan34** [GoogleChrome/lighthouse#9286]
Page Speed Insight scores do not match Lighthouse scores in chrome dev tools - https://cavanalchiropractic.com . Mobile scores are all I am concerned with and reflect the reason for this issue.

**Comment by ueltonVeslei** [comment]
Duplicate from #8997

**Comment by exterkamp** [comment]
Duplicate of #6708
