### ISSUE TITLE
Don't allow auditing PDF

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9297]
#### Provide the steps to reproduce
1. Run LH on http://www.orimi.com/pdf-test.pdf
  

#### What is the current behavior?

NO_FCP

#### What is the expected behavior?

"you can't do that"

**Related issues**

#9245
https://bugs.chromium.org/p/chromium/issues/detail?id=979175

**Comment by brendankenny** [comment]
can we combine this with #9245 and have a "warn and abort if auditing unsupported media" and make a list of stuff to do that for?

At least PDF and XML will likely be done the same way (and does this happen for video, images, etc?)
