### ISSUE TITLE
Like a Coverage Test on Build Project

### ISSUE THREAD

**Issue by dulcetti** [GoogleChrome/lighthouse#9298]
### Describe what you want to be added
One feature to execute after builds of a project. Example, my project runs the build and execute the lighthouse cli after the task of build. This before a push, for example, using the git hooks.

If the scores are bellow the 80th, block the git push.

### Are you willing to work on this yourself?
I dont't know how =/

### What is the motivation or use case for changing this?
Break the changes with decrease of actual score

### How is this beneficial to Lighthouse?
A feature to improve the cotnious quality of software

**Comment by patrickhulce** [comment]
Thanks for filing @dulcetti! It sounds like you want Lighthouse as part of your CI process and to start failing a build based on Lighthouse scores. You might be interested in our [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci) project we're working on. 

It's early, but feedback is welcome :)

I'll go ahead and close this issue but if you have specific requests for Lighthouse CI, please file them in the other repo.
