### ISSUE TITLE
Protocol timeout on "your first PWA" codelab example

### ISSUE THREAD

**Issue by TheKaddarikRepository** [GoogleChrome/lighthouse#9304]
#### Provide the steps to reproduce
1. Run LH on <affected url>
Hello,
I was just trying the tutorial for PWA from codelabs.

#### What is the current behavior?
Hello,
I was just trying the tutorial for PWA from codelabs.
When launching the audit as prescribed in :
https://codelabs.developers.google.com/codelabs/your-first-pwapp/#2

I get this Error for Mobile :
`PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: http://localhost:8000/
Chrome Version: 75.0.3770.100
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (chrome-devtools://devtools/remote/serve_file/@cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0/audits2_worker/audits2_worker_module.js:1190:210)
````

I get this Error for Desktop :
`NO_FCP
```
Channel: DevTools
Initial URL: http://localhost:8000/
Chrome Version: 75.0.3770.100
Stack Trace: LHError: NO_FCP
    at eval (chrome-devtools://devtools/remote/serve_file/@cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0/audits2_worker/audits2_worker_module.js:1219:206)
````
#### What is the expected behavior?

https://codelabs.developers.google.com/codelabs/your-first-pwapp/#2

#### Environment Information
* Affected Channels: 
* Lighthouse version: DevTolls Chrome 75
* Node.js version: node-v10.16.0-x64
* Operating System: Win7

**Related issues**
#8833

**Comment by connorjclark** [comment]
Re-opening because it has a repro.

**Comment by rickjjones** [comment]
I am having the same error. 

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://googlecodelabs-your-first-pwapp-4991.glitch.me/
Chrome Version: 75.0.3770.100
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (chrome-devtools://devtools/remote/serve_file/@cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0/audits2_worker/audits2_worker_module.js:1190:210)
```

**Comment by exterkamp** [comment]
PROTOCOL_TIMEOUT happens (#6512) and is often flaky.  I.e. I can't repro right now.  You should be able to follow the advice in that issue and resolve this, thanks!
