### ISSUE TITLE
Error auditing a site in Mobile mode (and sometimes in Desktop)

### ISSUE THREAD

**Issue by vynarim** [GoogleChrome/lighthouse#9318]
Hello,

Trying to audit https://group.accor.com/fr-FR in Mobile mode about performances, I had the following error message

![image](https://user-images.githubusercontent.com/20367460/60425771-8b6c4e80-9bf3-11e9-9506-9e223c037215.png)

In desktop mode, I succeded but sometimes, launching again the audit I also had this message

![image](https://user-images.githubusercontent.com/20367460/60425487-eb162a00-9bf2-11e9-9389-6ff417f099a4.png)

**Comment by patrickhulce** [comment]
I'm not able to reproduce this on that page. Does the page look rendered to you? If the page doesn't render content, then Lighthouse can't audit it.

**Comment by vynarim** [comment]
Sorry, this morning I had this issue several times an I just launched it on desktop and mobile and everything  is ok.
