### ISSUE TITLE
Suggest that app should adapt to network changes

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#932]
A nice audit may be to see if the app detects network connection speed changes by setting up listeners for `navigator.connection.onchange` events and `online` and `offline` events on window.

http://wicg.github.io/netinfo/#the-networkinformation-interface

**Comment by rajzshkr** [comment]
This is open for a long time. Shall I work on this?

**Comment by paulirish** [comment]
Hmmmm... 

I could argue (if i had to) that this doing this could result in a bad user experience sometimes. the "Lie-Fi" case wouldn't trigger these changes.   And handling that well means cache-first-then-fetch SW policy.   

So is checking for cache-first what we want here?


@rajzshkr there are probably other available audits that require less conversation. :)

**Comment by paulirish** [comment]
Probably too difficult to be accurate. :/
