### ISSUE TITLE
false positive report

### ISSUE THREAD

**Issue by marekka** [GoogleChrome/lighthouse#9320]
Hi, on https://www.zoedale.co.uk/ the https://web.dev/measure reports "Does not have a <meta name="viewport"> tag with width or initial-scale"

But the viewport is defined, so what can be the reason?

**Comment by patrickhulce** [comment]
Yes, @marekka your viewport is not defined in the `head` which is required for the audit to pass. Also see [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) on this topic.
