### ISSUE TITLE
Manifest display audit shows "should set display property" debugString even if one is set

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#933]
Current master shows a `debugString` for manifest display when it should not:

<img width="431" alt="screen shot 2016-11-12 at 12 21 42 pm" src="https://cloud.githubusercontent.com/assets/238208/20240653/94357896-a8d2-11e6-96bf-8f6d4caf81da.png">

Run:

    npm run fast -- --output=html --output-path=results.html https://www.chromestatus.com/features

manifest in question has a `display` property: https://www.chromestatus.com/static/manifest.json

**Comment by olingern** [comment]
I opened up a PR for this over at #950
