### ISSUE TITLE
Link with nested role text results in error 'Links do not have a discernible name'

### ISSUE THREAD

**Issue by greenc05** [GoogleChrome/lighthouse#9337]
When a link has a nested element with ```role="text"``` (added to stop 'text splitting' in VoiceOver iOS https://axesslab.com/text-splitting/) such as:

```
<a href="myurl.com">
    <span role="text">
        <span class="VisuallyHiddenText">Audio, </span>
        <span>Today's headlines</span>
        <span class="VisuallyHiddenText">, 1 minute 3 seconds</span>
    </span>
</a>
```

This causes the following error when running an audit in Lighthouse Accessibility 'Links do not have a discernible name'. 

This error should not occur as the link does have a discernible name with the presence of ```role="text"```. See related issue: https://github.com/GoogleChrome/lighthouse/issues/9075

**Comment by patrickhulce** [comment]
Is this actually different from #9075?

From my limited understanding it seems like it's the same root axe issue https://github.com/dequelabs/axe-core/issues/1597

**Comment by greenc05** [comment]
It would certainly seem to be related, whether it's the same issue I guess axe can only answer that? I wasn't sure as it gives a different error.

**Comment by greenc05** [comment]
@patrickhulce how to I find out what version of axe Lighthouse is using? https://github.com/dequelabs/axe-core/issues/1597#issuecomment-509790954

**Comment by greenc05** [comment]
So interestingly I just ran a Lighthouse (Lighthouse 4.3.1) audit using the 'Audit' tab in the Chrome browser (Version 75.0.3770.100 Official Build 64-bit) and it gives the error 'Links do not have a discernible name' however when I run an 'Audit' using the Lighthouse browser extension (Lighthouse 5.1.0) I do not get that error. How do I ensure I'm using the latest version of Lighthouse in the web inspector 'Audit' tab? Which I believe is the recommended way to run this tool?

**Comment by patrickhulce** [comment]
The version of Lighthouse in Audits panel of stable Chrome runs a bit behind because of Chrome's release process. To use latest, you can use the CLI (`npm install -g lighthouse`), extension, or Chrome Canary.

Not a particularly easy way to tell what version of axe we're using outside of the source. It's on 3.2.2 currently and in 5.1.0.

https://github.com/GoogleChrome/lighthouse/blob/4c658d272705cc68f1b55a898a2c7fb5f881b57c/package.json#L140

**Comment by patrickhulce** [comment]
Looks like we need to update to 3.3.0 then!

**Comment by patrickhulce** [comment]
Do you have a repro URL for this page @greenc05?

**Comment by greenc05** [comment]
Thanks @patrickhulce Do I have a repro URL for which page? The page I was testing?

**Comment by patrickhulce** [comment]
Nevermind I created one with the repro, just curious if the page with the example code you provided was in the wild somewhere :)

**Comment by greenc05** [comment]
It will be live on Monday! Can send it then if useful.
