### ISSUE TITLE
Performance Metrics are different in LH node module as compare to Chrome Dev Tool

### ISSUE THREAD

**Issue by InfobyteTarun** [GoogleChrome/lighthouse#9341]

**Comment by patrickhulce** [comment]
Please fill out the [bug report template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) with details about what specifically is different and how we can reproduce the issue (runtime settings, URLs, etc).

**Comment by InfobyteTarun** [comment]
**Steps to reproduce:-**
---Calculate via Chrome Dev Tool:
Calculate the performance of page : - https://www.drupal.com/ using Chrome(Version 75.0.3770.100 ) Dev Tool
![image](https://user-images.githubusercontent.com/17821114/61053958-30650380-a40c-11e9-810e-bdc2abecf5cc.png)

**Result is :** 
![image](https://user-images.githubusercontent.com/17821114/61054085-686c4680-a40c-11e9-84c6-733bd81fb4f3.png)

--Calculate via Node Module 
-Node Version Used: 6.1.0
-Npm Lighthose Version: "lighthouse": "^5.1.0"
-Chrome(Version 75.0.3770.100 ) 
-Options: 
const opts = {
    output: 'html',
    chromeFlags: ['--headless'],
    emulatedFormFactor: 'desktop',
    logLevel: 'info',
    onlyCategories: ['performance'],
    view: true,
    useThrottling: true,
    throttlingMethod: 'devtools'

};

**Result is** 
First Contentful Paint = 2263.997 ms (~2.2 s)
Speed Index = 11735 ms
Time to Interactive = 13195.898 ms

There is difference between both results for the same page.

**Comment by patrickhulce** [comment]
You are using different environment settings between the two runs which is causing the mismatch.

In one case it's using headful Chrome and simulated throttling while the other is using headless and applied throttling. While many sites behave similarly with applied vs. simulated and headful vs. headless, some sites behave differently under those different conditions and the same settings have to be used in order to make direct comparisons.

Hope this helps!

**Comment by InfobyteTarun** [comment]
Thanks for replying!

Now I run in headful manner with below options 

const opts = {
    output: 'html',
    emulatedFormFactor: 'desktop',
    logLevel: 'info',
    onlyCategories: ['performance'],
    view: true,
    throttlingMethod: 'devtools'

}   

Getting the same result i.e.
First Contentful Paint = 2209.766 ms
Speed Index = 11512 ms
Time to Interactive = 12663.113 ms

Could you please provide the opts , so that I can get the same result. Really I shall be thankful to you as I got blocked due to this.

**Comment by patrickhulce** [comment]
```js
const opts = {
  output: 'html',
  emulatedFormFactor: 'desktop',
  logLevel: 'info',
  onlyCategories: ['performance'],
  view: true,
  throttlingMethod: 'simulate' // <-- this is the important change
}
```

**Comment by InfobyteTarun** [comment]
Thanks for providing the solution!

Tried with this opts, but still getting the same result, performance metrics are different w.r.t. to chrome dev tool. You can run at your end and see...
Result got via node module:
First Contentful Paint = 2240.2200000000003 ms
Speed Index = 6810.975818905025 ms
Time to Interactive = 8095.67 ms

**Comment by patrickhulce** [comment]
I'm not seeing those numbers when I run with `simulate`, those are the numbers I see for `devtools`.

This is the report I get with `simulate`
![image](https://user-images.githubusercontent.com/2301202/61139134-5fbc5480-a48e-11e9-9140-7fc0ae9fa6a5.png)

Those also match the results I get in Devtools for "Simulated" and "Applied" throttling respectively.

**Comment by InfobyteTarun** [comment]
![image](https://user-images.githubusercontent.com/17821114/61141533-688f4380-a4eb-11e9-8569-5ba13516ca83.png)

I am getting this result with ops
const opts = {
  output: 'html',
  emulatedFormFactor: 'desktop',
  logLevel: 'info',
  onlyCategories: ['performance'],
  view: true,
  throttlingMethod: 'simulate' // <-- this is the important change
}

in node module. This result is different w.r.t. dev tool.

**Comment by InfobyteTarun** [comment]
@patrickhulce  Can we have a short zoom call so that I can showcase you the same, if time persists you.

**Comment by exterkamp** [comment]
Can't repro.
