### ISSUE TITLE
Update styling for third party checkbox to conform to redesign

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9345]
See https://github.com/GoogleChrome/lighthouse/pull/9299#issuecomment-510190625

existing:
![image](https://user-images.githubusercontent.com/4071474/60852335-22b14300-a1ac-11e9-96de-7c7d2f7e4c69.png)

mock
![image](https://user-images.githubusercontent.com/4071474/61007135-e4896000-a320-11e9-900f-7cb6f8d703fe.png)

**Comment by connorjclark** [comment]
what about a rocker

![image](https://user-images.githubusercontent.com/4071474/61746607-f0c5e200-ad50-11e9-851e-ea359c59e35e.png)

**Comment by connorjclark** [comment]
or a depressed button

![image](https://user-images.githubusercontent.com/4071474/61746732-34205080-ad51-11e9-93a9-eda2fbb5a304.png)

**Comment by paulirish** [comment]
nah
