### ISSUE TITLE
Error when the server-side request is very slow.

### ISSUE THREAD

**Issue by arturskovrigo** [GoogleChrome/lighthouse#9348]
![image](https://user-images.githubusercontent.com/52778163/61033431-2fac7d00-a3cc-11e9-9c46-f2da272edf09.png) 
There is a problem with this page, i am using laravel and, long story short, i got a huge database, and the requests from it are very slow, i want to know which request is the slowest, but when i run lighthouse it shows me this...

**Comment by arturskovrigo** [comment]
I solved the problem on my end, with the long loading time, things that were wrong: i had two returns in my laravel controller
       return view('downtime',compact('usernames'));
       return view('downtime');
and i had an unnecessary query  in the same controller which made everything much slower.
Still, i hope that this information can help you iron out this error.

**Comment by patrickhulce** [comment]
Thanks @arturskovrigo, this error means the page took too long to paint any content which must be solved on the user's side, so you took the correct steps. 👍
