### ISSUE TITLE
Reduce JavaScript execution time: view what's inside `Other`

### ISSUE THREAD

**Issue by cesarvarela** [GoogleChrome/lighthouse#9352]
**Feature request summary**
 I would like to see which scripts are included inside `Other`

**What is the motivation or use case for changing this?**
This group or whatever is it is taking the most in execution time

**How is this beneficial to Lighthouse?**
Clearer reports.

**Comment by patrickhulce** [comment]
Thanks for filing @cesarvarela! This boils down to https://github.com/GoogleChrome/lighthouse/issues/8526. It's in the backlog, and we'd like to tackle it in the future.

**Comment by tonydehnke** [comment]
I'd like to see this too as for me it shows 3,411ms but no idea what it is that is taking that long.
