### ISSUE TITLE
Let us download the report in PDF or an Online format so we can share it with anyone

### ISSUE THREAD

**Issue by ADixit1289** [GoogleChrome/lighthouse#9358]
**Feature request summary**

**What is the motivation or use case for changing this?**

**How is this beneficial to Lighthouse?**

**Comment by patrickhulce** [comment]
@ADixit1289 thanks for the report, the way to accomplish this now is to Print to PDF using the 3 dots menu in top right of the HTML report.

![image](https://user-images.githubusercontent.com/2301202/61132410-ea965280-a480-11e9-9bcf-76c939d7073d.png)


duplicates #9215 #9041 #3564
