### ISSUE TITLE
Test site with invalid SSL certificate fails

### ISSUE THREAD

**Issue by Mef45** [GoogleChrome/lighthouse#9359]
#### Provide the steps to reproduce
1. Run LH CLI on <https://expired.badssl.com/> 
`lighthouse https://expired.badssl.com/ --chrome-flags='--ignore-certificate-errors'`
  

#### What is the current behavior?
Test fail with error
`Insecure document request: The URL you have provided does not have a valid security certificate. This site is missing a valid, trusted certificate (net::ERR_CERT_DATE_INVALID).`
#### What is the expected behavior?
Test website with invalid SSL cert & `--chrome-flags='--ignore-certificate-errors'` flag must complete

#### Environment Information
* Affected Channels:CLI 
* Lighthouse version: 5.1.0
* Node.js version: 12.5.0
* Operating System: Ubuntu 18.04

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing!

The fix for this landed June 3 (https://github.com/GoogleChrome/lighthouse/pull/8865) and there has just not been a release yet. It will be fixed in the upcoming version.

**Comment by Mef45** [comment]
Thanks for quick reply. I'll wait for the new version with impatience.
