### ISSUE TITLE
I18N not used for numeric displayValues

### ISSUE THREAD

**Issue by fbatschi** [GoogleChrome/lighthouse#9360]
**Summary**

Currently numeric values in a audit result's `displayValue` are not correctly formatted as to the used locale for the lighthouse report.

For instance take an example audit result generated with locale 'de':

```
    "interactive": {
      "id": "interactive",
      "title": "Zeit bis Interaktivität",
      "description": "Die Zeit bis Interaktivität entspricht der Zeit, die vergeht, bis die Seite vollständig interaktiv ist. [Weitere Informationen](https://developers.google.com/web/tools/lighthouse/audits/consistently-interactive).",
      "score": 0.03,
      "scoreDisplayMode": "numeric",
      "numericValue": 18709.598999999995,
      "displayValue": "18.7 s"
    },
```

The `displayValue` is `18.7 s` - but as it is a German locale, the number needs to be formatted as `18,7 s` 

`,` instead of `.`.

**Comment by patrickhulce** [comment]
Thanks very much for filing @fbatschi! 

Does your node version have [ICU locales](https://nodejs.org/api/intl.html#intl_options_for_building_node_js) installed? If it doesn't you'll need to install the optional `intl` dependency. i.e. `yarn add intl`. This was moved to be a core dependency of Lighthouse in the upcoming version (https://github.com/GoogleChrome/lighthouse/pull/9309), but for now you'll need to add it yourself.

This is how it looks for me with the `intl` package added.

![image](https://user-images.githubusercontent.com/2301202/61133746-abb5cc00-a483-11e9-979b-50c59745ac04.png)

**Comment by fbatschi** [comment]
@patrickhulce thank you, adding `intl` did the trick.
