### ISSUE TITLE
Failing to run audits if the host is not defined.

### ISSUE THREAD

**Issue by ghk829** [GoogleChrome/lighthouse#9370]
#### Provide the steps to reproduce
1. Run LH on <affected url>
 
I did a test for a web-page, It doesn't have domain-name yet. (ex : XXX.XXX.XXX.XXX:XXXX)

#### What is the current behavior?

It can't be tested on "the specific host" IP:HOST

#### What is the expected behavior?

I should be tested on every server 

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.1.0.1
* Node.js version: v10.15.0
* Operating System: windows 7 

**Related issues**

**Comment by patrickhulce** [comment]
Sorry @ghk829 but this isn't enough information to reproduce the issue. Would you be able to be more specific?

A domain is not a requirement to run, we run tests on IP address-only hosts routinely, so something else must be the issue.

**Comment by brendankenny** [comment]
Closing as there hasn't been movement in some time. Please comment and we can reopen if you're still seeing this issue.
