### ISSUE TITLE
Hide audit from report

### ISSUE THREAD

**Issue by fbatschi** [GoogleChrome/lighthouse#9375]
**Feature request summary**

Currently you can return different scoring modes for an audit, like `numeric`, `informative` and  `NOT_APPLICABLE`, which means that the audit has been run but for some reason the audit does not apply to the website.

There is currently no possibility to hide an audit from the report. Returning an empty result from audit() shows an error in the report.

**What is the motivation or use case for changing this?**

We want to have specific audits that should only be in the report depending on the certain values from a gatherer (for instances whether or not the Stacks Gatherer shows that this is a Wordpress site we are looking at). We don't want to show that several dozens of audits are not applicable, we want to completely hide them from the report.
We don't know during config time whether or not the site is a Wordpress site so we cant do any conditional inclusion of the audits at that point.

**Comment by brendankenny** [comment]
@fbatschi this was pretty much the exact use case `notApplicable` was designed to address.

Definitely understand wanting to get the noise out of the way when audits don't apply, but could you explain why you find collapsing under a "Not applicable" section insufficient?

**Comment by fbatschi** [comment]
Basically yes, it is about the noise in the report. The  HTML report is only one way where the result gets rendered (and yes a collapsed section might be fine). We mostly gather results as JSON and I don't  want to include all the audits in there that could not be run due to a logic condition. 

@brendankenny Do you see any other way to include/exclude an audit during runtime depending on a condition that comes out of a Gatherer?

**Comment by patrickhulce** [comment]
@fbatschi `notApplicable` is exactly for excluding an audit during runtime depending on a condition that comes out of a gatherer. 

> yes a collapsed section might be fine

The not applicable results are already collapsed by default in the report to minimize the noise, so I think this is exactly what you're looking for. Unless a user starts intentionally digging into the not applicable audits, we would expect most report consumers to never even notice that they were there.
