### ISSUE TITLE
Report needs visible indicator of mobile or desktop run 

### ISSUE THREAD

**Issue by andreamoro** [GoogleChrome/lighthouse#9379]
Unless mistaken, I didn't see this reported before. 

For better UX, I'd suggest to move the Runtime settings panel returned after an audit at the top, perhaps in a collapsed panel.
Alternatively, and this is the main goal, make it clear whether an audit ran using a desktop or mobile mode.

**Comment by patrickhulce** [comment]
It used to be at the top but was specifically relocated to the bottom for other UX priorities (namely the URL and the category scores being the most urgent visual priorities compared to runtime environment details which are typically unchanged between different reports). 

Your primary concern is desktop vs. mobile? I can see this being important information to convey along with the performance score, perhaps there's a way we could work in a form factor device icon or something front and center.

cc @hwikyounglee @yuinchien

**Comment by paulirish** [comment]
@andreamoro can you talk a little about why you want the mobile/desktop signal up front? is it because you forgot the settings that were used? or you're toggling between two reports?

**Comment by brendankenny** [comment]
let's track over in #9438

**Comment by paulirish** [comment]
As desktop scoring is a big thing now, this is much higher priority than before.

I also favor the idea of a lil device icon, perhaps within the score gauge.

**Comment by paulirish** [comment]
cc @jimoong

**Comment by paulirish** [comment]
![image](https://user-images.githubusercontent.com/39191/89338536-904ecd80-d651-11ea-8806-cae00b4e733e.png)

**Comment by paulirish** [comment]
merging into #8178
