### ISSUE TITLE
Runtime settings: throttling settings to match the network panel

### ISSUE THREAD

**Issue by andreamoro** [GoogleChrome/lighthouse#9380]
**Feature request summary**
Throttling settings to match, or to be extended as per the network panel (giving more flexibility)

**What is the motivation or use case for changing this?**
Auditing a website often requires multiple pass, and changing the settings in several panels can be daunting but also prone to errors.

Being able to set the network throttling via the "Network panel", and making Lighthouse inheriting the settings would speed us the configuration as well as ensure consistency in the result, which at the moment cannot be guaranteed as the two features are running on parallel non-matching trails. 

In an ideal scenario, Lighthouse should get the same settings in the main network panel and use to run the audit.
![image](https://user-images.githubusercontent.com/5256583/61270315-943b5380-a7a1-11e9-8387-61afc5c804f0.png)

**How is this beneficial to Lighthouse?**
Flexibility and consistency are the keywords here. This will make the product more robust, but would open up an avenue for you to infer data from different network condition and use to inform the average results.

**Comment by connorjclark** [comment]
this will be solved when we implement connection sharing b/wn devtools and lighthouse. see these issues for more: https://github.com/GoogleChrome/lighthouse/issues/9095#issuecomment-497863554 #5423

**Comment by andreamoro** [comment]
It seems there's quite a few of an overlap, but I'll not exclude to make this as separate point and avoid assumptions

**Comment by paulirish** [comment]
In devtools there are multiple bundled throttling presets, plus you can add custom ones.

Technically the throttling we apply uses the same characteristics as the "fast 3g" preset you see in devtools. 

We don't want to defer to the current selected devtools throttling preset, as it would mean less consistency from machine to machine.
