### ISSUE TITLE
Site Audit: lherror: no_fcp Page load time too high

### ISSUE THREAD

**Issue by startupflux** [GoogleChrome/lighthouse#9381]
Our site ico.ambcrypto.com is loading very slow. So i tried to run a site audit on it. But it shows LHerror: No_FCP
Please help me figure out this issue. How can i run the audit?

**Comment by patrickhulce** [comment]
If the page is loading so slowly that it passes the Lighthouse default timeout, you can manually increase the paint timer by running with the CLI.

```bash
npm install -g lighthouse
lighthouse <url> --max-wait-for-fcp=45000 # wait up to 45s for the page to paint instead of just 15s

**Comment by exterkamp** [comment]
Reopen if you are still having issues!
