### ISSUE TITLE
Unused CSS does not take <noscript> into account

### ISSUE THREAD

**Issue by developit** [GoogleChrome/lighthouse#9382]
The "Unused CSS" audit seems to include CSS loaded conditionally within a `<noscript>`.
Here's an example snippet that triggers the audit:

```
<link href="style.css" rel="preload" as="style" onload="this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="style.css"></noscript>
<style>.fa{ /* inlined critical styles */ }</style>
```

See GoogleChromeLabs/critters#36 for original report.

#### Provide the steps to reproduce

1. Run LH on https://social.preactjs.com using `Applied Slow 4G, 4x CPU Slowdown`
  
#### What is the current behavior?

Unused CSS audit is triggered.

#### What is the expected behavior?

Unused CSS audit should ignore `<link rel=stylesheet>` within `<noscript>`.

Ideally it could also ignore inlined CSS rules matching those from an asynchronously-loaded external stylesheet. I don't know if it's the root cause of this rule being triggered, but for multipage websites it's often bad for caching/network performance to remove critical-inlined CSS rules from external stylesheets, since the set of rules to be extracted differ by page.

#### Environment Information

* Lighthouse version: 5.1.0
* Node.js version: 10.15.0
* Operating System: MacOS 10.14.5

**Comment by patrickhulce** [comment]
Thanks @developit :)

I'm not sure what the `<noscript>` has to do with anything though. The stylesheet is being loaded by the `rel="preload"` `link` and set to an active stylesheet there. The existence of the `<noscript>` should not have any affect on the unused status of the `<link rel=preload>` sheet. DevTools also flags this coverage issue.

![image](https://user-images.githubusercontent.com/2301202/61306685-a83b8100-a7b2-11e9-9bc4-bc5492aa34bf.png)


To address your second point, we don't flag duplicate CSS as being unused, so if the rule matches anything on the page, it should be safe 👍

**Comment by brendankenny** [comment]
Closing according to what @patrickhulce said. Please comment and we can reopen if you're still thinking this is an issue.
