### ISSUE TITLE
Categories - get overall score for all categories 

### ISSUE THREAD

**Issue by avivco** [GoogleChrome/lighthouse#9389]
Hi all,

**Lighthouse - 5.1.0**

What's the best practice to collect the overall score for all relevant categories:

- Accessibility 

- Performance

- Best practice

- SEO 

?
I'm using the Node CLI. From my understanding, the JS code is running in the browser to accumulate all audits. The html file that created in my file explorer is not containing the scores of the categories

**Comment by patrickhulce** [comment]
The LHR (the file that results from `--output=json` in the CLI, and is inlined into the HTML file as the global variable `__LIGHTHOUSE_JSON__`) has the category scores readily available.

[Read the docs](https://github.com/GoogleChrome/lighthouse/blob/31f7142257e844fa0f6cb1e5fa43dc551b94731d/docs/understanding-results.md#lighthouse-result-object-lhr) on how to process the results for more.
