### ISSUE TITLE
Allow default chrome flags to be ignored

### ISSUE THREAD

**Issue by Gudahtt** [GoogleChrome/lighthouse#9390]
**Feature request summary**
Lighthouse allows additional Chrome flags to be passed to Chrome Launcher, but the default flags used by Chrome Launcher cannot be overridden or ignored via the lighthouse CLI.

To accommodate this case, Chrome Launcher accepts a flag to ignore default Chrome flags. It is typically used with the `defaultFlags()` method, to allow disabling specific default flags while preserving the rest ([see here](https://github.com/GoogleChrome/chrome-launcher/pull/70)). It's not clear how to best expose that functionality via the lighthouse CLI though. Alternatives were discussed in [this Chrome Launcher issue](https://github.com/GoogleChrome/chrome-launcher/issues/65).

**What is the motivation or use case for changing this?**
The default flags are sensible for most test cases, but there are edge cases they are incompatible with. For example, testing a site that requires audio to be enabled, or testing a browser extension.

Some users might also prefer to disable all default flags, for more complex test scenarios. This might be easier than tracking which flags need to be overridden, especially as the defaults might change over time.

**How is this beneficial to Lighthouse?**
This would allow using the lighthouse CLI directly in cases where one or more default chrome flag must be unset. This is far more convenient than the workaround of writing a wrapper script that invokes Chrome Launcher programmatically with the appropriate flags before invoking lighthouse.

**Comment by Gudahtt** [comment]
My preferred solution would be to use the approach described in [this issue] as _CLI vGamma API_. e.g.

`lighthouse --chrome-flags="--disable-extensions=false"` would eliminate the `disable-extensions` default flag. To accomplish this, we'd need call the Chrome Launcher `defaultFlags()` method, and compare each flag with the user-specified flags.

This wouldn't require an API change, and would make it essentially do what a user might reasonable expect it to have done in the first place.

Second, it would be nice to have an `--ignore-default-chrome-flags` flag as well, to make disabling all flags easier.

**Comment by Gudahtt** [comment]
I'm having second thoughts about using the _CLI vGamma API_. It doesn't work well for flags with values.

For example, one of the default flags proposed in [this PR](https://github.com/GoogleChrome/chrome-launcher/pull/23) is `--password-store=basic`. How should that be negated?

We could go with `--password-store=false`. But that wouldn't work if the default flag value is _already_ false, which is a possibility in the future. We could go with `--password-store=false=false`, but that would require parsing the flags in a strange way (as demonstrated by the test failure in #9401).

The _CLI vBeta API_ would be a lot more straightforward to implement. I don't believe it has any problematic edge cases, though it does have one case that looks a bit strange from the user's perspective (disabling a flag that begins with `no` already).

For the `--password-store=false` case, that would be negated with `--no-password-store`. An example of the strange case would be the flag `--no-pings`, which would be negated with `--no-no-pings`.

I'm not sure I understand the feedback about that style of negation being too magical or hard to explain - maybe somebody could elaborate?

**Comment by connorjclark** [comment]
we did `--ignore-default-chrome-flags`
