### ISSUE TITLE
Allow auditing chrome-extension:// pages

### ISSUE THREAD

**Issue by Gudahtt** [GoogleChrome/lighthouse#9402]
**Feature request summary**
I would like Lighthouse to allow auditing pages belonging to other Chrome extensions.

The project [exthouse](https://github.com/treosh/exthouse) is great for measuring the impact of an extension upon _other_ pages, but it isn't meant to be used to test Chrome extension user interfaces in isolation. I would like to test a `chrome-extension://` URL as if it were any other web page. This would be helpful in measuring the performance of chrome extensions.

**Comment by Gudahtt** [comment]
The first obstacle I encountered when trying to do this was the `--disable-extensions` Chrome flag, which is set by default. While it would be nice to disable that flag (related issue: #9390), you can launch Chrome Launcher with custom flags before invoking lighthouse as a workaround for that issue.

After working around that issue, I then kept encountering the error `NO_NAVSTART`. It looks like it was due to a regular expression that looked for URLs starting with `chrome:/`, `http:/`, or `https:/`. After adjusting that regex, it appeared to work. So I'm not entirely sure whether this is a bug, or whether this was never intended to be used this way.

**Comment by patrickhulce** [comment]
Thanks for the issue @Gudahtt! For some historical context, Lighthouse previously supported auditing `chrome-extension` pages but repeated internal changes to Chrome kept breaking support for them (some trace assumptions no longer hold, subtle navigation behavior differences between regular pages and chrome extensions, inability to navigate back and forth between about:blank, etc). We didn't have the bandwidth or strong use case to continue fixing, so support was dropped (and the fact that it hasn't come up again until now, is somewhat supportive of the idea that few users are trying 😄 ).

While it seems good that a few of those issues might be fixed to get LH to run on chrome-extensions again, the original rationale for disabling them probably still holds. Is it prohibitive to test the extension pages on a local server with Chrome APIs mocked?

**Comment by Gudahtt** [comment]
Thanks for providing that context! That all makes perfect sense. It's no surprise this isn't an especially popular request, what with extensions being much less common than websites, and most of them having pretty simple UIs.

Testing the extension pages on a local server with mocked Chrome APIs would certainly be possible. I could make do with that solution. Testing using the real Chrome APIs would be preferred though, to get audit results more analogous to real usage.

**Comment by nickmccurdy** [comment]
I'm still able to run Chrome audits in `chrome-extension` pages, but I get warnings for things like network speed, mobile support, and browser support, which aren't relevant to Chrome extension development. Could we potentially have lighthouse filter/disable checks based on the protocol?

**Comment by connorjclark** [comment]
Currently get "NO_NAVSTART" when I try auditing an extension page in devtools.

**Comment by connorjclark** [comment]
There's a lot of random things we'd have to change inside Lighthouse to make this possible, and there's a big unknown effort involved re: DevTools to work with emulation/extensions, more surface areas to test against for a small use case... in short the complexity we think is not worth the effort.
