### ISSUE TITLE
`yarn update:sample-json` doesn't work on windows.

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9403]
~~`assert-golden-lhr-unchanged.sh` is not OS-independent.~~

This blocks most contributions from developers using Windows.

**Comment by brendankenny** [comment]
> assert-golden-lhr-unchanged.sh is not OS-independent.

that seems true, but shouldn't block `yarn update:sample-json`?

**Comment by connorjclark** [comment]
Oh, I see.

That collect strings script requires every `.js` file. Even `lighthouse-core\scripts\cleanup-LHR-for-diff.js` which is meant to run as a script. That script checks the args passed in - the number of which differs on windows? On windows I get:

```
[ 'C:\\Program Files (x86)\\nodejs\\node.exe',                                                                                                                                        'C:\\Users\\Connor\\code\\lighthouse\\lighthouse-core\\scripts\\i18n\\collect-strings.js' ]
```

while on Mac I get (...one sec)

**Comment by connorjclark** [comment]
> that seems true, but shouldn't block yarn update:sample-json?

Sorry, I got that file mixed up. ignore that

**Comment by connorjclark** [comment]
Issue is w/ the ignore path components. Mac properly ignores it during the collecting phase - the output I shared was actually just the script really being run later in the command :)

**Comment by exterkamp** [comment]
Good fix.  Ran into this too.  `collect-strings` kept running Ultradumb benchmark and I was super confused.  That PR works on windows.
