### ISSUE TITLE
Reproducible auditing error 

### ISSUE THREAD

**Issue by ArchimedusIII** [GoogleChrome/lighthouse#9407]
#9059 ## Provide the steps to reproduce
1. Run LH on http://ctf.infosecinstitute.com/img/leveltwo.jpeg

This page contains a corrupt image (by design), which apparently makes Lighthouse fail.

#### What is the current behavior?

"Channel: DevTools
Initial URL: http://ctf.infosecinstitute.com/img/leveltwo.jpeg
Chrome Version: 75.0.3770.80
Stack Trace: LHError: NO_FCP
    at eval (chrome-devtools://devtools/remote/serve_file/@9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2/audits2_worker/audits2_worker_module.js:1219:206)" 
```
#### What is the expected behavior?

Succesful (relatively simple) audit

**Comment by brendankenny** [comment]
> This page contains a corrupt image (by design), which apparently makes Lighthouse fail.

Lighthouse isn't designed to audit images. The failure `NO_FCP` means that nothing was painted to screen, at least anything that Chrome considered rendering the page.

The failure itself is fine (and can be more or less considered WAI), but we could definitely improve the error message. For non-html documents in particular, that would be covered by #9245. For NO_FCP errors in particular, #6154 is probably your best bet.
