### ISSUE TITLE
Is it possible to use distinct Chrome instances on different ports?

### ISSUE THREAD

**Issue by LeMoussel** [GoogleChrome/lighthouse#9408]
Is it possible to attach (programmatically) multiple lighthouse audit on distinct Chrome instances on different ports?
My use case is to test multiple urls that require some settings of the browser.

I do this :
```
(async () => {
  const startDate = new Date().getTime();

  const promisesBrowsers = [];
  for (let numBrowser = 0; numBrowser < 2; numBrowser += 1) {
    promisesBrowsers.push(new Promise(async () => {
      const browser = await puppeteer.launch({ headless: false, args: ['--no-sandbox', '--disable-background-timer-throttling'] });
      console.log(`browser wsEndpoint: ${browser.wsEndpoint()}`);
      console.log(`browser port: ${URL.parse(browser.wsEndpoint()).port}`);

      const lighthouseReport = await lighthouse(
        'http://example.com',
        {
          port: URL.parse(browser.wsEndpoint()).port,
          disableDeviceEmulation: true,
        },
        lighthouseConfig,
      ).then(results => results);
      
      await browser.close();
    }));
  }
  await Promise.all(promisesBrowsers);

  console.log(`Time elapsed ${Math.round((new Date().getTime() - startDate) / 1000)} s`);
})().catch(e => {
  console.error(e);
  process.exit(1);
});
```

But I got following error:

> browser wsEndpoint: ws://127.0.0.1:62216/devtools/browser/5d26e63b-ea96-44e3-91d4-145101c5bec5
> browser port: 62216
> browser wsEndpoint: ws://127.0.0.1:62218/devtools/browser/eb3c1735-1b42-49a0-b0b7-cf6d93435c39
> browser port: 62218
> (node:11896) UnhandledPromiseRejectionWarning: Error: no known mark: lh:driver:cleanBrowserCaches
>     at Object.exports.stop (D:\Developpement\NodeJS\AuditUp\node_modules\marky\lib\marky.cjs.js:76:13)
>     at Function.timeEnd (D:\Developpement\NodeJS\AuditUp\node_modules\lighthouse-logger\index.js:128:11)
>     at Driver.cleanBrowserCaches (D:\Developpement\NodeJS\AuditUp\node_modules\lighthouse\lighthouse-core\gather\driver.js:1492:9)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:11896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:11896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>

Thanks in advance!

**Comment by patrickhulce** [comment]
Thanks for filing @LeMoussel!

It is not supported to run multiple `lighthouse` instances inside the same process at once. It is also strongly advised to not have more than 1 lighthouse run going on at a time on the same machine at the risk of affecting the performance results even if they are in separate processes. If performance stability is not a concern for your use case, run each lighthouse instance in a separate process in order to parallelize results. Hope this helps!
