### ISSUE TITLE
 ERRORED_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by Kosmart** [GoogleChrome/lighthouse#9415]
hi, once we try to run a page speed test (for https://kosmart.eu) we always get following error:

Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403)Dismiss

however, if we run test for https://kosmart.eu/index.php or another website on the same server - it doesn't give this error. Hosting compamy chekced server parameters, cleaned blocked IP's. and web developer didn't find anything wrong on the web, anyone imagines why this issue might appear ? (all other online speed tests works fine). We can run test locally, but we want to understand that maybe this might impact our page indexing as well and fix it ?

**Comment by Kosmart** [comment]
necessarily-wide-alpaca

**Comment by patrickhulce** [comment]
This problem is almost definitely on the server side and #2784 appropriately captures it (your server responded with a 403 to the request that PSI sent). You should be able to check in your server logs to see what happened. It could be determining that the request is a bot and preventing it from continuing with a 403?

Either way, I'm able to PSI results for that URL at the moment.

![image](https://user-images.githubusercontent.com/2301202/61542212-b5e94480-aa06-11e9-9dbc-6d306b798f6b.png)

**Comment by Kosmart** [comment]
Hi, Patrick, thank you so much for your reply. Did i understand correctly that you were able to get results for page speed with such URL  https://kosmart.eu/ <https://kosmart.eu/> ? (like in your screen) ? Because we are still trying to do so, but we get the same error with all regular urls and title page url for example: 

(these don't work)
https://kosmart.eu <https://kosmart.eu/>
https://kosmart.eu/hair-barrettes-and-hair-clips/1892-22775-medium-size-rectangular-shape-hair-barrette-in-white-and-black.html <https://kosmart.eu/hair-barrettes-and-hair-clips/1892-22775-medium-size-rectangular-shape-hair-barrette-in-white-and-black.html>


Our hosting provider tested our web with following URLS:
https://developers.google.com/speed/pagespeed/insights/?url=https://kosmart.eu/admin899odnnkv/ <https://developers.google.com/speed/pagespeed/insights/?url=https://kosmart.eu/admin899odnnkv/>
https://developers.google.com/speed/pagespeed/insights/?url=https://kosmart.eu/phpinfo.php <https://developers.google.com/speed/pagespeed/insights/?url=https://kosmart.eu/phpinfo.php>

And they both are ok, they also checked Apache and didn’t find any log with error there and they tell that problem comes from our web code, but our IT don’t find why it could happen from the web code as on other page speed testers everything works. Maybe you can give me any further suggestion how we could find the issue ?



Domas Lygnugaris
Kosmart.eu <http://kosmart.eu/>
+370 677 11566
info@kosmart.eu <mailto:info@kosmart.eu>
Kosmart Hair Accessories
beauty in the details!

Distribution center:
LTD. KOSMART
VAT: LT100007536619
ID: 302603950
V. Pietario street 8, Vilnius
Lithuania

 <https://www.pinterest.com/KosmartEU/>  <https://www.pinterest.com/KosmartEU/> <https://www.facebook.com/kosmart.fr/>  <https://www.facebook.com/kosmart.fr/> <https://www.youtube.com/channel/UCzIq-EH01YhbIh3TwhpBEfg>  <https://www.youtube.com/channel/UCzIq-EH01YhbIh3TwhpBEfg>
 <https://www.instagram.com/kosmart.eu/>

 <https://www.instagram.com/kosmart.eu/>





 <https://www.pinterest.com/KosmartEU/>

 <https://www.pinterest.com/KosmartEU/>	


 <https://www.pinterest.com/KosmartEU/>
 <https://www.pinterest.com/KosmartEU/>
 <https://www.pinterest.com/KosmartEU/>

**Comment by patrickhulce** [comment]
Hm, I'm still able to audit the homepage just fine through Page Speed Insights, so it must be something specific to the way the request is being handled from the EU.

![image](https://user-images.githubusercontent.com/2301202/61721093-89e30180-ad2d-11e9-88c9-ff27bba06eab.png)


cc @exterkamp do you have any suggestions for how to simulate a request coming from EU PSI to help debug? A regular curl request with the PSI UA string in the US doesn't seem to replicate the issue.

@Kosmart this is the command to do a simple request with the Chrome-Lighthouse user agent you can try to see if it returns a 403.

```
curl https://kosmart.eu -vvvv -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse' | head

**Comment by Kosmart** [comment]
hi, Patrick,

Thank you for your note, i see now that if i make inquiry with IP from USA, then it shows me the results as well. Any ideas what might cause this ?



Domas Lygnugaris
Kosmart.eu
+370 677 11566
info@kosmart.eu
Kosmart Hair Accessories
beauty in the details!

Distribution center:
LTD. KOSMART
VAT: LT100007536619
ID: 302603950
V. Pietario street 8, Vilnius
Lithuania

 <https://www.pinterest.com/KosmartEU/>  <https://www.pinterest.com/KosmartEU/> <https://www.facebook.com/kosmart.fr/>  <https://www.facebook.com/kosmart.fr/> <https://www.youtube.com/channel/UCzIq-EH01YhbIh3TwhpBEfg>  <https://www.youtube.com/channel/UCzIq-EH01YhbIh3TwhpBEfg>
 <https://www.instagram.com/kosmart.eu/>

 <https://www.instagram.com/kosmart.eu/>





 <https://www.pinterest.com/KosmartEU/>

 <https://www.pinterest.com/KosmartEU/>	


 <https://www.pinterest.com/KosmartEU/>
 <https://www.pinterest.com/KosmartEU/>
 <https://www.pinterest.com/KosmartEU/>
