### ISSUE TITLE
Suggest adding async/defer to scripts in head

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#943]
Upon re-examining the head script/style order audit in Dev Tools, which seemed to be based on outdated logic, thought it might be better to just warn when the number of tags in the head is approaching the same-origin in-flight request cap instead.

Set suggested number to 6 initially per [this post](http://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser), [Chrome source](https://cs.chromium.org/search/?q=kMaxNumDelayableRequestsPerHost&sq=package:chromium&type=cs), and testing done on [cuzillion](https://stevesouders.com/cuzillion/)

**Comment by Janpot** [comment]
Or suggest to serve them with HTTP 2 instead?

**Comment by patrickhulce** [comment]
Actually yeah there's already a `uses-http2` audit that suggests using h2 to load same-origin resources, so maybe not worth doing at all. @ebidel @brendankenny Paul and I seemed to overlook that existing audit yesterday when this got created, makes sense to scrap altogether? Or maybe expand the check to include not just the same host but all high criticality/blocking external resources as well?

**Comment by ebidel** [comment]
Yea, I think we might want to add an audit that checks for blocking scripts in the head, similar to our rendering blocking links audit. WDYT?

**Comment by patrickhulce** [comment]
Sounds good, maybe also expand the use-http2 to check for multiple requests to the same origin?

**Comment by ebidel** [comment]
That feels like another audit to me that we'd combine with the results from `use-http2`.

**Comment by patrickhulce** [comment]
This was addressed by #965
