### ISSUE TITLE
Lighthouse not working for authenticated pages when tried through command line?

### ISSUE THREAD

**Issue by dileep524** [GoogleChrome/lighthouse#9445]
When installed globally via npm i -g lighthouse or yarn global add lighthouse, chrome-debug is added to your PATH. This binary launches a standalone Chrome instance with an open debugging port.

->Run chrome-debug. This will log the debugging port of your Chrome instance
->Navigate to your site and log in.
->In a separate terminal tab, run lighthouse url --port port-number using the port number from chrome-debug.

Tried in the above manner but i was getting following errors:
```
status Connecting to browser +0ms
  CriConnection:warn Cannot create new tab; reusing open tab. +17ms
  status Disconnecting from browser... +4ms
  CriConnection:error sendRawMessage() was called without an established connection. +1ms
  GatherRunner disconnect:error sendRawMessage() was called without an established connection. +3ms
Runtime error encountered: Protocol JSON API error (list), status: 404
Error: Protocol JSON API error (list), status: 404
    at IncomingMessage.response.on (C:\Users\sujith\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\connections\cri.js:107:18)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
I think it's not taking the port number that i have given can i find a solution?
can i change the default port number:9222 ?

**Comment by patrickhulce** [comment]
Thanks for filing @dileep524! I'm not able to reproduce this with Chrome stable on Mac, but it appears that Chrome Canary is temporarily broken (crashes on startup), so if you have Canary installed, that would explain this behavior.

I'm afraid we won't be able to help without more environment info and a clear repro case.

**Comment by dileep524** [comment]
Sorry my problem was just that i forgot to add --disable-storage-reset flag and entered the wrong chrome debug port. it's working fine now.

**Comment by bharathkr1** [comment]
Hi..

> Sorry my problem was just that i forgot to add --disable-storage-reset flag and entered the wrong chrome debug port. it's working fine now.

Could u share me the updated file, if u have

**Comment by raphaellueckl** [comment]
In my case I had to the set a debug port for puppeteer and then route the lighthouse `port` to that same port.

```
// Puppeteer starting chromium
const option: LaunchOptions = {
        args: ['--remote-debugging-port=9222'] // <=====================
    };
const browser = await launch(option);

// Using lighthouse

  const options = {
    logLevel: "info",
    output: "html",
    onlyCategories: ["performance", "seo", "accessibility", "best-practices"],
    port: 9222, // <=====================
  };
  const lighthouseChecks = await lighthouse("http://localhost:3000/", options);
