### ISSUE TITLE
artifacts.HTMLWithoutJavaScript.trim is not a function

### ISSUE THREAD

**Issue by lucasecdb** [GoogleChrome/lighthouse#945]
Error while trying to generate report on chrome version 53.0.2785.92 (64-bit) and lighthouse version 1.1.7

![screenshot from 2016-11-15 16-28-05](https://cloud.githubusercontent.com/assets/10223856/20320490/c3759eb2-ab50-11e6-9edb-59d8b671ae20.png)

**Comment by lucasecdb** [comment]
I believe the error is somewhere in [here](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/without-javascript.js#L48`)

**Comment by brendankenny** [comment]
Sorry about that. This was fixed in #891, just after 1.1.7 was released, and will be included in the next release.
