### ISSUE TITLE
Offline pass doesn't always go offline

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#9450]
#### Provide the steps to reproduce
1. Run LH on https://www.bhphotovideo.com/
 

#### What is the current behavior?

Lighthouse reports that the start URL does not load offline but the current page does.

You can observe that in the offline pass, the desktop version of the page is loaded, and upon inspecting lighthouse internals see that the `fromServiceWorker` and `fromDiskCache` flags on all network requests are `false`. This shouldn't be possible when offline.

#### What is the expected behavior?

Lighthouse reports that the start URL loads offline. A page like the below should be visible during the offline pass, not the desktop version of the site.

![image](https://user-images.githubusercontent.com/2301202/61826719-a1eb7b80-ae28-11e9-88c7-6145188e8763.png)

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 5.2.0
* Node.js version: v10.15.3
* Operating System: macOS

**Related issues**
brought over from https://github.com/GoogleChrome/lighthouse/issues/2688#issuecomment-514738794

**Comment by brendankenny** [comment]
possibly the same as #6502?

**Comment by brendankenny** [comment]
well, almost the opposite situation, actually, but the same underlying cause? :)

**Comment by patrickhulce** [comment]
I don't *think* so, I found this root cause of this one and am working on a PR now. It was introduced ~February of this year by me :)

but could be more to unravel here!

**Comment by martinschierle** [comment]
stargames.de is having the same problem - page loads well offline, but Lighthouse states it wouldn't:

https://www.webpagetest.org/lighthouse.php?test=190827_Z0_86c8da0d29fd514bd77a00b7b760bb5b&run=3
