### ISSUE TITLE
Audit fail into "We ran into an error"

### ISSUE THREAD

**Issue by aungzanbaw** [GoogleChrome/lighthouse#9456]
#### Provide the steps to reproduce
1. Run LH on <https://www.telenor.com.mm/my>
  

#### What is the current behavior?
Ah! Sorry! We ran into an error.

#### What is the expected behavior?
Redirect to audit report page

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.2.0
* Node.js version: v12.6.0
* Operating System: Mac 10.15 beta
* Chrome: 75

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @aungzanbaw! I'm not able to reproduce this error. 

![image](https://user-images.githubusercontent.com/2301202/61880865-46b69900-aebb-11e9-9e75-fb2dad98f8b6.png)

Anything else you can tell us?

**Comment by aungzanbaw** [comment]
Hi @patrickhulce thanks for your reply,  I've tried on Windows & Ubuntu to same test page and found similar error. Then i though due to chrome extensions so i did try on incognito mode & removing all of them, terms out same error.

**Comment by patrickhulce** [comment]
@aungzanbaw there should be additional error information presented to you along, perhaps with a stack trace? Without this and without a repro, I'm afraid there's not much we can do.

For now, [PSI seems to work for that URL](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.telenor.com.mm%2Fmy).

**Comment by aungzanbaw** [comment]
[Link](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.telenor.com.mm%2Fmy) to pagespeed works but I can see following message 

> Lighthouse returned error: NO_FCP. Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP) (NO_FCP) 

Audits on my chrome trigger following sometime but when i refresh it's working most the time now, i will close the issue.  
````
Channel: DevTools
Initial URL: https://www.telenor.com.mm/my
Chrome Version: 75.0.3770.142
Stack Trace: LHError: NO_FCP
    at eval (chrome-devtools://devtools/remote/serve_file/@8d93477bd18154c67a70a67019cb8032382c55dd/audits2_worker/audits2_worker_module.js:1219:206)
````

![image](https://user-images.githubusercontent.com/1712561/62343118-84e13780-b50f-11e9-9018-4c802a16af20.png)

**Comment by aungzanbaw** [comment]
@waqaramjad check your internet speed if you used local lighthouse, you can try on [here](https://developers.google.com/speed/pagespeed/insights/) too
