### ISSUE TITLE
~3 seconds difference for Time to Interactive

### ISSUE THREAD

**Issue by Birowsky** [GoogleChrome/lighthouse#9457]
Sup folks! You have given me a nice couple of weeks of optimizations :}

#### What is the current behavior?
Lighthouse measures 11.4s Time to Interactive for [this app](https://gotaguydev.com).
<img width="589" alt="image" src="https://user-images.githubusercontent.com/3199950/61901628-777ce980-af20-11e9-8e36-afbd66db1ed3.png">

However, analysing the trace gives us an indicator that the app is interactive at less than 2s:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/3199950/61905134-a303d200-af28-11e9-9ca7-5e54bad96b25.png">

#### What is the expected behavior?
Time to Interactive should be closer to 2s. This should in turn, move Speed Index to that same range. Please advice if I should open another issue for that.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.1.0
* Operating System: Mac 10.14.6

----------------------------------------------------
The link provided is for the dev version, so fell free to mess around.

**Comment by patrickhulce** [comment]
Thanks @Birowsky! Are you running with simulated throttling?

Simulated throttling loads the page as quickly as possible (i.e. in 2 seconds) and then *simulates* what it would've been like under different conditions (Slow 4G + Mid-tier mobile phone hardware by default). If this was the case for you.

**Comment by EternalReign** [comment]
We ran into this issue too but we are executing lighthouse in pipeline. We didn't have this issue when we used 3.0.0. However, When we upgraded lighthouse into 5.0.0+, time to interactive increase drastically. We run this in simulated throttling(fast 4g 4x cpu slow down).

**Comment by Birowsky** [comment]
Darn it. You're right, I didn't care to understand that option. Now the metrics are way closer to one another. Thanx!

Now I'm measuring 3 second difference for Time to Interactive:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/3199950/61944681-915d1180-af9e-11e9-84a7-8b733f5cca39.png">

<img width="1136" alt="Screen Shot 2019-07-26 at 12 14 07" src="https://user-images.githubusercontent.com/3199950/61944996-3841ad80-af9f-11e9-858f-60fbf3a7c238.png">

The Audit says 9s, but on the trace, I can see that the Main becomes available at around 6s:
<img width="1137" alt="Screen Shot 2019-07-26 at 12 14 32" src="https://user-images.githubusercontent.com/3199950/61945042-54dde580-af9f-11e9-8ec6-3d85e3a9f1bf.png">

Could you help me understand whether there is something else holding up the Main? 
Thanx!

**Comment by patrickhulce** [comment]
@Birowsky TTI needs more than a ~400ms gap of main thread availability. TTI marks the time at which the page is *reliably* interactive, and as your screenshot shows, the page still has quite a bit of JavaScript activity past 6 seconds. The page does not quiet down until around ~8.8 seconds which is the same value as the metric. TTI requires a 5 second window without a long task before the page is deemed interactive.

@EternalReign I'm not sure what you're referring to. There were several bug fixes in simulated metrics between 3.x.x and 5.x.x, so it's possible you're bumping into one of those. If you believe you have a found a reproducible bug then a separate issue with repro steps would be much appreciated :)

**Comment by Birowsky** [comment]
@patrickhulce alrighty then, I got my answers. Thank you! Back to work.
