### ISSUE TITLE
Devtools and extension output different tap targets result.

### ISSUE THREAD

**Issue by castilloandres** [GoogleChrome/lighthouse#9463]
Hey Lighthouse team!

#### Provide the steps to reproduce
1. Run LH on https://www.quaino4.ca/

#### What is the current behavior?
Lighthouse devtools (mobile and desktop) give different tap target results in comparison with the extension for https://www.quaino4.ca/

### Devtools desktop
<img width="1090" alt="devtools-desktop" src="https://user-images.githubusercontent.com/16306312/61940112-0fb4b600-af95-11e9-873b-f6f606a818ef.png">

### Devtools mobile
<img width="1108" alt="devtools-mobile" src="https://user-images.githubusercontent.com/16306312/61940451-bbf69c80-af95-11e9-96dd-43ece50e6f71.png">

### Extension
<img width="944" alt="extension" src="https://user-images.githubusercontent.com/16306312/61940485-cf096c80-af95-11e9-8183-4b24e1e2acde.png">

#### What is the expected behavior?
To have the same tap target audit/result in Lighthouse devtools and extension?

#### Environment Information
* Affected Channels:  Extension, DevTools
* Lighthouse version: 5.1.0.1
* Node.js version:
* Operating System:

**Comment by patrickhulce** [comment]
Thanks for filing @castilloandres!

It looks like you're comparing two different Lighthouse versions and the tap targets implementation has changed slightly since then. (It looks like you're using 4.3.1 in DevTools, the Lighthouse version is listed at the bottom of the report.)

**Comment by castilloandres** [comment]
@patrickhulce you are totally correct! My bad. Closing this ticket immediately.
