### ISSUE TITLE
Getting "Form elements do not have associated labels" even though they are present

### ISSUE THREAD

**Issue by gulatigautam** [GoogleChrome/lighthouse#9472]
#### Provide the steps to reproduce
1. Run LH on www.americanexpress.com
  

#### What is the current behavior?
Getting "Form elements do not have associated labels" even though they are present
#### What is the expected behavior?

Should not be Getting "Form elements do not have associated labels" since  they are present

<img width="882" alt="Screen Shot 2019-07-26 at 4 10 31 PM" src="https://user-images.githubusercontent.com/13562914/61979116-f9245400-afc0-11e9-88f8-c5369b8a3285.png">
<img width="1049" alt="Screen Shot 2019-07-26 at 4 10 42 PM" src="https://user-images.githubusercontent.com/13562914/61979128-017c8f00-afc1-11e9-9b9a-afee3d18b872.png">

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @gulatigautam!

Do you have a chance to follow the advice in the bug report template?

>  Before creating an Accessibility issue please test that it is reproducible upstream with axe (https://www.deque.com/axe/) first and file the issue there if necessary.

**Comment by gulatigautam** [comment]
@patrickhulce Thanks! Analyzed with axe and seems to be happening there too. Created an issue there.
