### ISSUE TITLE
Lighthouse 5.2.0 mistakes browser window width for device width in mobile audit

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/lighthouse#9476]
Lighthouse version: 5.2.0
Chrome: Version 78.0.3868.0 (Official Build) canary (64-bit)
OS: Windows 8.1

When performing a mobile audit, Lighthouse measures the mobile agent width against the browser window width and throws an error in the PWA audit:

> Content is not sized correctly for the viewport
> The viewport size is 412px, whereas the window size is 1366px [or current browser window width].
> 

#### Provide the steps to reproduce

1) Navigate to any website...even https://www.google.com
2) Open Lighthouse and select Mobile device
3) Select Progressive Web App audit
4) Run audit, then check PWA results. "Content is not sized correctly for the viewport" should be an error.
5) It will complain that the viewport size is 412px but the window size is the width of the browser window.
6) Now resize the width of the browser window and repeat steps 4-5. The "window width" in the report will correspond to the browser width, not the device width.
  

#### What is the current behavior?

It incorrectly measures the viewport size against the actual browser window width.

#### What is the expected behavior?

It should compare the viewport size to the simulated device width.

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.2.0
* Node.js version:
* Operating System: Windows 8.1

* Chrome: Version 78.0.3868.0 (Official Build) canary (64-bit)

**Related issues**

**Comment by connorjclark** [comment]
@paulirish 	this kinda looks like that Chromium test case that was erroring, that we attributed to the content shell test harness ...

**Comment by connorjclark** [comment]
Couldn't repro on my mac. Will have to try again on my Windows machine later today. Or - can you confirm this is not specific to Windows?

Could you provide the exact command you use to run LH (if using the CLI) - or are you using DevTools Audits panel?

**Comment by tmb-github** [comment]
I used the DevTools Audits panel and originally discovered it while auditing https://thomasbrodhead.com . I then discovered the same results obtained while auditing https://www.google.com, etc.

**Comment by onur-celik** [comment]
same problem here [https://piyasa.paratic.com](url)

**Comment by hugues-koolsol** [comment]
Hello,

Same problem with the mobile audit with https://www.koolsol.com/, 
but not with the desktop audit.

With the precedent version of lighthouse, it was the opposite ( message on desktop but not with mobile ).

By the way, https://www.koolsol.com fits inside the screen size in any case so I do not see why this error should appear. Perhaps because there is a timeout() on the resize event and lighthouse does this detection before the timeout fires.

Audit runs on Version 78.0.3872.0 (Build officiel) canary (64 bits) windows10.

**Comment by patrickhulce** [comment]
I'm able to repro this on mac @connorjclark. Perhaps something with our new emulation handoff isn't working properly? 

The screen definitely appears to be mobile but for some reason `window.outerWidth` is still evaluating to the width of the browser window.

**Comment by connorjclark** [comment]
@patrickhulce yeah me too. For some reason my canary wasn't updating to the latest version. Definitely related to the  latest changes in the emulation handoff :(

**Comment by connorjclark** [comment]
The innerWidth is correctly set to 412px, but the outerWidth always reverts back to w/e the outerWidth is without any emulation.

I thought there might be a race condition b/wn applying emulation and starting the audit, so I added a wait for 10s, but that didn't do anything.

DevTools emulation itself is perfectly fine. Emulating Nexus 5x shows the correct values:
```
[window.innerWidth, window.outerWidth]
(2) [412, 412]
```

**Comment by connorjclark** [comment]
Using `window.screen.{width,height}` in `ViewportDimensions` (instead of `window.outer{width,height}` works.

**Comment by connorjclark** [comment]
The protocol suggests that outerWidth is not covered: https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setDeviceMetricsOverride

**Comment by connorjclark** [comment]
`screen` is technically the entire screen (whereas `outerWidth` is the OS's window), but I've tested using it instead with various sizes of Chrome. It is always equal to `innerWidth` for pages that define a proper viewport.

**Comment by connorjclark** [comment]
nvm `screen` doesnt work, I was using `v5.2.0` instead of `dt-520`. only the latter has the `deviceScreenEmulationMethod` flag. 

this DT emulation business needs to be revisited.

**Comment by connorjclark** [comment]
The DT frontend ends up sending `Emulation.setDeviceMetricsOverride` ~8 times. each change to the emulation model does one. [relevant code](https://cs.chromium.org/chromium/src/third_party/blink/renderer/devtools/front_end/audits/AuditsPanel.js?l=266&rcl=d33364e67c193ae669b3ff9fca35ee320449722d)

![image](https://user-images.githubusercontent.com/4071474/62583832-81cfa980-b877-11e9-8f3a-ae8d3a6abab1.png)

i thought all that craziness might be causing our issue, so I circumvented the frontend abstractions and sent `Emulation.setDeviceMetricsOverride` directly (exactly what LH would send if it were doing the emulation). Still broken. I suppose we blame the connection handoff at this point.

**Comment by connorjclark** [comment]
After digging through some IPCs and printf'ing some stack traces, I've learned that as soon as the audit starts a `WidgetMsg_DisableDeviceEmulation` ipc is sent, as part of the `DevToolsUIBindings::Reattach` -> `content::DevToolsAgentHostImpl::DetachClient` -> `content::DevToolsSession::Dispose` -> `content::protocol::EmulationHandler::Disable()` series of calls.

**Comment by connorjclark** [comment]
I believe @JoelEinbinder's [multi-client](https://chromium-review.googlesource.com/c/chromium/src/+/1132548) changes will fix this issue (all the agents won't get disposed for multi-clients, but in the current impl. "there can only be one" client and agent state is lost during handoff).

**Comment by connorjclark** [comment]
CL: https://chromium-review.googlesource.com/c/chromium/src/+/1743411/

**Comment by connorjclark** [comment]
The [multi-client](chromium-review.googlesource.com/c/chromium/src/+/1743411) CL just landed in Chromium. This issue will be resolved in the next canary Chrome. The first stable Chrome to resolve this issue will be Chrome 78, ETA Oct 22.
