### ISSUE TITLE
Different audit results between DevTools and Node module

### ISSUE THREAD

**Issue by rainergp** [GoogleChrome/lighthouse#9478]
#### Provide the steps to reproduce
1. I'm running LH on Chrome Canary (Version 78.0.3866.0 (Official Build) canary (64-bit)) using the DevTools with the following settings:

![image](https://user-images.githubusercontent.com/795937/62074551-0a639f80-b211-11e9-9389-59a050321547.png)

2. I'm running LH programmatically using chrome-launcher, here my dependencies:

- lighthouse 5.2.0
![image](https://user-images.githubusercontent.com/795937/62074947-df2d8000-b211-11e9-9408-2d6955e4fc42.png)

The code:

`
import * as ChromeLauncher from "chrome-launcher";
import * as lighthouse from 'lighthouse';
import * as LighthouseLogger from 'lighthouse-logger';
import * as ReportGenerator from 'lighthouse/lighthouse-core/report/report-generator';
import {DeviceType} from "../models/device-type.enum";
import TrackingUrlService from "./api/tracking-url.service";
import Report from "../models/api/report.model";
import EventEmitterHandler from "../helpers/eventEmitterHandler";

export default class LighthouseService {

    constructor() {
    }

    public static async launchHeadlessChromeAndRunLighthouse(config = null) {

        /**
         * Adjustments needed for DevTools network throttling to simulate
         * more realistic network conditions.
         * @see https://crbug.com/721112
         * @see https://docs.google.com/document/d/10lfVdS1iDWCRKQXPfbxEn4Or99D64mvNlugP1AQuFlE/edit
         * @see https://github.com/WPO-Foundation/webpagetest/blob/master/www/settings/connectivity.ini.sample
         */
        const DEVTOOLS_RTT_ADJUSTMENT_FACTOR = 3.75;
        const DEVTOOLS_THROUGHPUT_ADJUSTMENT_FACTOR = 0.9;
        const TARGET_LATENCY = 70;
        const TARGET_DOWNLOAD_THROUGHPUT = Math.floor(12 * 1024);
        const TARGET_UPLOAD_THROUGHPUT = Math.floor(12 * 1024);

        let flagsDesktop: any = {
            logLevel: 'info',
            throttlingMethod: 'provided',
            // disableDeviceEmulation: true,
            // disableCpuThrottling: true,
            disableStorageReset: true,
            emulatedFormFactor: 'desktop',
            port: null,
            throttling: {
                rttMs: 0,
                throughputKbps: 0,
                requestLatencyMs: 0,
                downloadThroughputKbps: 0,
                uploadThroughputKbps: 0,
                cpuSlowdownMultiplier: 0,
            }
        };

        let flagsMobile: any = {
            logLevel: 'info',
            throttlingMethod: 'devtools',
            // disableDeviceEmulation: false,
            // disableCpuThrottling: false,
            disableStorageReset: true,
            emulatedFormFactor: 'mobile',
            port: null,
            throttling: {
                rttMs: TARGET_LATENCY,
                throughputKbps: TARGET_DOWNLOAD_THROUGHPUT,
                requestLatencyMs: TARGET_LATENCY * DEVTOOLS_RTT_ADJUSTMENT_FACTOR,
                downloadThroughputKbps: TARGET_DOWNLOAD_THROUGHPUT * DEVTOOLS_THROUGHPUT_ADJUSTMENT_FACTOR,
                uploadThroughputKbps: TARGET_UPLOAD_THROUGHPUT * DEVTOOLS_THROUGHPUT_ADJUSTMENT_FACTOR,
                cpuSlowdownMultiplier: 4,
            }
        };

        LighthouseLogger.setLevel('info');

        let trackingUrlsList = await TrackingUrlService.getTrackingUrls();

        if (trackingUrlsList && trackingUrlsList.length > 0) {

            let chrome: any = await ChromeLauncher.launch({chromeFlags: ['--headless', '--no-sandbox', '--disable-setuid-sandbox', '--window-size=1366,768']});

            try {

                flagsDesktop.port = chrome.port;
                flagsMobile.port = chrome.port;

                for (let i = 0; i < trackingUrlsList.length; i++) {

                    let results = [];
                    let parsedData = [];
                    const url = trackingUrlsList[i].requestedUrl;
                    const trackingId = trackingUrlsList[i].trackingId;

                    console.log('--- Auditing desktop on ', url);
                    results.push({result: await lighthouse(url, flagsDesktop, config), device: DeviceType.Desktop, trackingId});
                    console.log('--- Auditing mobile on ', url);
                    results.push({result: await lighthouse(url, flagsMobile, config), device: DeviceType.Mobile, trackingId});

                    results.forEach(async (data: any) => {
                        console.log('Generating html report...');
                        let html = ReportGenerator.generateReport(data.result.lhr, 'html');
                        console.log('Parsing data...');
                        parsedData.push({data: LighthouseService.parseData(data), html});

                    });

                    EventEmitterHandler.getInstance().emit('reportsReadyForProcessing', parsedData);
                }

                await chrome.kill();
            } catch (e) {
                chrome.kill().then(
                    () => {
                        throw e;
                    },
                    console.error
                );
            }
        }
    }

    private static parseData(data): any {
       ...
    }
}
`

#### What is the current behavior?
There is a big difference between both TTI:

![image](https://user-images.githubusercontent.com/795937/62075365-e0ab7800-b212-11e9-8828-21f1afab32cb.png)

The runtime settings are the same fro both:

![image](https://user-images.githubusercontent.com/795937/62075489-2ff1a880-b213-11e9-80ac-bb89d67b1165.png)

#### What is the expected behavior?
I expected to get similar results in both cases and that's not the case;

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.2.0
* Node.js version: 11.10.0
* Operating System: macOS Mojave 10.14.6

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @rainergp! Could you be more specific though? 

- What is the current behavior?
- What behavior are you expecting?
- What settings are you using in node?

**Comment by rainergp** [comment]
I'm sorry @patrickhulce I pushed the unfinished description by mistake. Now is up to date

**Comment by patrickhulce** [comment]
It looks like you have the "Clear storage" box unchecked in DevTools. Are the results similar if you check it? 

By default in node you'll be getting a fresh Chrome instance every time, while in DevTools you're currently on the page and will experience the benefit of what is essentially a refresh instead of a cold load.

**Comment by rainergp** [comment]
If I uncheck it the TTI goes up, but I need the results using the cache. Actually keeping the cache it's something that I was trying to achieve programmatically, that's why I'm using "disableStorageReset: true".

**Comment by patrickhulce** [comment]
It is intended for that purpose but if you're not navigating to the page first and navigating from *there* then the experience will essentially be a cold load regardless. It's only disabled clearing an already empty cache at that point :)

**Comment by rainergp** [comment]
Ohhh I got it. I've seen some examples using puppeteer, is there a way of doing it just with chrome -launcher and lighthouse?. Can you please provide me with some documentation or an example? Thank you in advance.

**Comment by patrickhulce** [comment]
You could get most of the way there by setting the `startingUrl` option in your `ChromeLauncher.launch` args and then waiting for some portion of time for the page to load first before navigating.

Anything more complex to close the remaining gap though is going to require `puppeteer`, [custom gatherers](https://github.com/GoogleChrome/lighthouse/tree/8a07c7b428624c39ec11a7cf548a838c4627cfc1/docs/recipes/custom-audit), or future lighthouse work (https://github.com/GoogleChrome/lighthouse/issues/3837#issuecomment-510893121).

**Comment by rainergp** [comment]
Thank you so much @patrickhulce . Yes for what I need I must use puppeteer, so far this is handling the issue:

```
let chrome: any = await ChromeLauncher.launch({
  chromeFlags: ['--no-sandbox', '--disable-setuid-sandbox', '--window-size=1366,768']
});

const resp = await util.promisify(request)(`http://localhost:${chrome.port}/json/version`);
const {webSocketDebuggerUrl} = JSON.parse(resp.body);
const browser = await puppeteer.connect({browserWSEndpoint: webSocketDebuggerUrl});

const page = (await browser.pages())[0];
await page.goto('https://www.test.com', {waitUntil: 'networkidle2'});

await lighthouse(page.url(), flags, config)
```
I'm closing the issue, thank you for your help.
