### ISSUE TITLE
LH shouldn't report 401s as "Browser errors were logged to the console"

### ISSUE THREAD

**Issue by juanpin** [GoogleChrome/lighthouse#9481]
#### Provide the steps to reproduce
1. Run LH on https://business.apple.com
  

#### What is the current behavior?

LH is reporting 401 as a browser error in the console. 401 responses are not errors.

#### What is the expected behavior?
It shouldn't classify a response as an error.

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.2
* Node.js version:
* Operating System: MacOS

**Related issues**
#7862

**Comment by patrickhulce** [comment]
Thanks for filing @juanpin! A 401 response is logged to the DevTools console as an error and for consistency it is classified as an error from Lighthouse's perspective as well.

We won't be excluding errors ad-hoc by default in Lighthouse but when #9480 lands you'll be able to ignore these yourself.

Also just as a reassurance and as you've already discovered in #7862

> The console errors are just advisory to let you know that something might be going on in the page that you didn't expect. Just having a console error will have no effect on the Lighthouse score on its own
