### ISSUE TITLE
 LHError: NO_FCP

### ISSUE THREAD

**Issue by x5engine** [GoogleChrome/lighthouse#9490]
NO_FCP
```
Channel: DevTools
Initial URL: http://localhost:3000/
Chrome Version: 75.0.3770.142
Stack Trace: LHError: NO_FCP
    at eval (chrome-devtools://devtools/remote/serve_file/@8d93477bd18154c67a70a67019cb8032382c55dd/audits2_worker/audits2_worker_module.js:1219:206)
```

**Comment by x5engine** [comment]
might be related
https://github.com/GoogleChrome/lighthouse/issues/6154#issuecomment-509639918

**Comment by x5engine** [comment]
not duplicate WTF

**Comment by patrickhulce** [comment]
Thanks for filing! This page seems to take too long to paint content, and Lighthouse gives up on waiting. If you need to change this behavior, you can run Lighthouse from the command line with a custom config modifying `maxWaitForFcp`.

Also note that if you've obscured the Chrome window certain operating systems will pass this signal and the page will be kept from painting while backgrounded.
