### ISSUE TITLE
Score page

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChrome/lighthouse#9498]
Hello, when I see the 4 first pwas in the score page : 
https://pwa-directory.appspot.com/pwas/score

I notice that there are some apps that do not always give a score of 100 results for the lighthouse score when I run audit on my computer. 

Furthermore, score for other audits ( performance, accessibility , ...) are in some cases medium.

Could you refine the score page so that it reflects a really good global score.

Thanks.

**Comment by patrickhulce** [comment]
Thanks for filing! 

We don't manage the PWA directory though @hugues-koolsol. I believe it's just showing when the page scores 100 in the PWA category as there is no longer a concept in Lighthouse of an overall page score, just category scores.

If you'd like to contribute to updating the directory to show more of these other categories you should be able to go take a look over at its repo https://github.com/GoogleChromeLabs/gulliver.

**Comment by hugues-koolsol** [comment]
OK, sorry I should not have post this comment there.
Thank you for your reply !
