### ISSUE TITLE
 LHError: NO_FCP  (when devtools are on a different desktop)

### ISSUE THREAD

**Issue by deeKay93** [GoogleChrome/lighthouse#9499]
Run LH on localhost with the demo from PWA codelabs:
https://codelabs.developers.google.com/codelabs/pwa-offline-quickstart/index.html?index=..%2F..dev-pwa-training#2

NOTE:  I'm using the macOS spaces to manage the windows.
The error only occurs when the actual website is not displayed.

#### What is the current behavior?
Error:

NO_FCP
```
Channel: DevTools
Initial URL: http://localhost:8081/
Chrome Version: 75.0.3770.142
Stack Trace: LHError: NO_FCP
    at eval (chrome-devtools://devtools/remote/serve_file/@8d93477bd18154c67a70a67019cb8032382c55dd/audits2_worker/audits2_worker_module.js:1219:206)
```

#### What is the expected behavior?
Actual results as described in the codelabs

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: Not sure (chrome version 75.0.3770.142)
* Node.js version: v10.15.0
* Operating System: macOS Mojave

**Comment by brendankenny** [comment]
@deeKay93 this is expected, unfortunately, because the browser tries to optimize by doing less work if it's not visible. See this thread for background: https://github.com/GoogleChrome/lighthouse/issues/6154#issuecomment-509763416

> There's not much we can do here: if the browser decides to lazily render only when the tab becomes visible again, Lighthouse can't reliably measure when it would have rendered if the tab had been visible.
