### ISSUE TITLE
Unexplainable high loading times of manifest json 

### ISSUE THREAD

**Issue by Enngage** [GoogleChrome/lighthouse#9505]
Hey!

I've been struggling with this for a few days and I can't figure out what might be going on. When running Lighthouse either by using Page Speed Insights or by https://web.dev/measure I get following critical path:

```
Maximum critical path latency: 12,240 ms
Initial Navigation
/ (ennfit-prod.azurewebsites.net)
…8/polyfills-es2015.7770c47….js (ennfit-akamai.azureedge.net) - 110 ms, 12.94 KB
/css?family=Roboto:300,400,500&display=swap (fonts.googleapis.com) - 10 ms, 1.19 KB
…8/main-es2015.12ec53a….js (ennfit-akamai.azureedge.net)
…v48/flUhRq6tz….woff2 (fonts.gstatic.com) - 150 ms, 59.84 KB
…v20/KFOlCnqEu….woff2 (fonts.gstatic.com) - 140 ms, 11.35 KB
…v20/KFOlCnqEu….woff2 (fonts.gstatic.com) - 140 ms, 11.23 KB
/icon?family=Material+Icons&display=swap (fonts.googleapis.com) - 10 ms, 0.87 KB
…8/runtime-es2015.ffe52fe….js (ennfit-akamai.azureedge.net) - 100 ms, 1.45 KB
…8/styles.3505e52….css (ennfit-akamai.azureedge.net) - 110 ms, 11.6 KB
/pwa-manifest.json (ennfit-prod.azurewebsites.net) - 9,770 ms, 1.26 KB
```

Notice how the `pwa-manifest.json` takes `9,770ms` to load. When requesting this file directly I get a response times in the range of `100-150ms`. Loading the page in browser is also very quick. 

 Chrome lighthouse addon downloads the manifest properly within the `100-150ms` range too. 

Google page speed gives me a score of `1` or `2` which is not very good. 

Removing the manifest file fixes the issue and I get > 90 score for desktop. 

Is there anything I could check or do? I'm gonna keep the site live for some time in case someone would like to take a look ->

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fennfit-prod.azurewebsites.net%2F

Thank you for any suggestions.

**Comment by patrickhulce** [comment]
Thanks for filing @Enngage! A manifest definitely shouldn't be having this sort of effect on your page. There are two bugs going on here.

1. PSI fetching the manifest takes an extraordinary amount of time. Locally with the same PSI user-agent the server readily responds in ~100ms. cc @exterkamp for ideas on why this might be happening. For the internal team, the reason this ends up affecting the performance score is because it greatly inflates lantern's estimate for the server response time to that origin and the root document is the only other request on the same origin, so it's request time in FCP is incorrectly inflated.
2. We shouldn't be flagging manifest files in `Critical Request Chains` at all, though in this case it was extremely helpful for debugging why the performance score was so high :)
2.

**Comment by connorjclark** [comment]
IDK but maybe this is related to internal googlers-only bug b/124008171. The jist is that fetching the manifest seems to be affected by other fetches preceding it.

**Comment by Enngage** [comment]
Thanks for the responses! Is there something I could do or change on my end? 

I'm trying to optimize the app as much as can (within the limits of Angular 8), but score of 1 or 2 leaves me a bit worried as how google will index the site eventually.

**Comment by Enngage** [comment]
This is really weird, but for some reasons setting `startUrl` property of the manifest to:

> /index.html

instead of

> /

fixed the issue and I now get reasonable scores of ~90 for desktop and ~70 for mobiles. Maybe this helps investigating the issue.

**Comment by connorjclark** [comment]
Wow, that's really unusual, thanks for sharing! Seems like a great repro.

My first guess is that the latter case doesn't even fetch the start url, as it may be seen as "out of scope" (if you load `www.example.com/`, `www.example.com/` is in scope by `www.example.com/index.html` isn't!) If you use the PSI API, you'll get the PWA audits too, and I'd expected `offline-start-url` to say `/index.html` wasn't loaded.

I'm not yet sure why requesting the start url (we do it offline - the service worker responds) results in degraded performance score.

**Comment by Enngage** [comment]
@connorjclark sorry, I just deleted my previous post :/ It seems to have been some sort of fluke - once I changed the paths it worked 2 or 3 times when running PSI, but then it stopped working and went back to the usual 1/2 scores. 

I'll try several alternatives to see if the paths have any effect, including changing the path in service worker configuration.

**Comment by connorjclark** [comment]
No worries! BTW, I just edited my comment, I am less convinced it is a scoping issue, but please let me know what you find.

**Comment by Enngage** [comment]
I've just tried running the API using `https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://ennfit-prod.azurewebsites.net&key=x`, but I didn't see any prop with the name `offline-start-url`. Is there something else I could check?

**Comment by connorjclark** [comment]
The default only runs Performance. See https://developers.google.com/speed/docs/insights/v5/reference/pagespeedapi/runpagespeed for how to pick other categories.

**Comment by Enngage** [comment]
Thank you, didn't know see this before. The start url does not seem to be working:

```
 "offline-start-url": {
                "id": "offline-start-url",
                "title": "start_url does not respond with a 200 when offline",
                "description": "A service worker enables your web app to be reliable in unpredictable network conditions. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/http-200-when-offline).",
                "score": 0.0,
                "scoreDisplayMode": "binary",
                "explanation": "Timed out waiting for fetched start_url.",
                "warnings": []
            },
```

I'm guessing there is something wrong with the service worker configuration (this may be causes by changes I'm trying currently though) as I've tested the site offline before and it worked.

**Comment by connorjclark** [comment]
Is that for start url = `/` or `/index.html`?

**Comment by Enngage** [comment]
I don't see that in the report, but currently the live site uses `/index.html` as `startUrl` so unless there is some caching done by the PSI, it should use this one. 

I've switched from CDN to Azure blob for this testing so there shouldn't be any caching now.

**Comment by Enngage** [comment]
Seems that critical path for manifest does not affect score at all - I disabled service worker & used invalid manifest only to find out that my score remained high (again ~90 for desktop) while the critical path still showed around `12 secs`.

With that said, I've narrowed the issue down to the service worker itself. Still not sure why it doesn't work in PSI, but works fine locally.

**Comment by patrickhulce** [comment]
Oh sorry if my comment wasn't clear earlier @Enngage! You are correct that the critical request chains audit result has no impact on the performance score. 

My guess for why disabling the service worker fixes the performance score is because it eliminates one more request on the origin that is slow and so the `median` server response time we use for the performance simulations becomes fast again.

**Comment by enableds** [comment]
Yeap! Can confirm the same issue. The manifest.json file is creating havoc both on Page Insights and GTMetrix. Removing them increases the score. Has anyone found a solution for this?

**Comment by paulirish** [comment]
This remains pretty interesting.

Our fullyLoaded logic depends on "network quiet". We've discussed making networkQuiet smarter. Related: #10810 #3748 

The manifest fetch is definitely not important, so we shouldn't consider that a blocker for "quiet".

**Comment by enableds** [comment]
This would be great if it could be implemented in the PageInsights algorithm and the results updated accordingly. It's quite hard to explain to customers that the manifest.json doesn't affect his score when the score is lower because of it.

Any chance to see an update on this? ( happens both in PageInsights and Lighthouse ) 

Cheers Paul, thanks for your attention! :)

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
