### ISSUE TITLE
"Document uses legible font sizes" and "Tap targets are sized appropriately" always "Not applicable"

### ISSUE THREAD

**Issue by siliconforks** [GoogleChrome/lighthouse#9506]
#### Provide the steps to reproduce
1. Run LH on any URL with SEO audit checked.
  

#### What is the current behavior?

"Document uses legible font sizes" and "Tap targets are sized appropriately" always show up under "Not applicable".

#### What is the expected behavior?

I would expect these audits to either pass or fail.  I wouldn't ever expect these audits to be "not applicable" (unless perhaps the document had no text or no clickable elements at all).

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.1.0
* Operating System: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36

**Comment by patrickhulce** [comment]
Thanks for filing @siliconforks! This was due to a mismatch in DevTools and Lighthouse emulation settings which should be fixed in Chrome Canary. Let us know if you're still running into this there so we can reopen!
