### ISSUE TITLE
Is lighthouse penalizing for a setTimeout() call?

### ISSUE THREAD

**Issue by jaredstanley** [GoogleChrome/lighthouse#9517]
**setTimeout used to 'polite load' content counts toward total load time**

1. site loads in 3000ms
2. to defer a script, like a chat window, `setTimeout(10000, chatRequest)` is called
3. does lighthouse count the page's load time as 3s or 13s? 

devtools appears to count the total time, assuming we are getting penalized for that but can't find a clear answer in the docs anywhere. 

**Assumption:** all code that is fired with no user-triggered event (such as a setTimeout that makes network calls called on load) gets counted toward total load time. In an effort to optimize the user experience by reducing load time we are actually hurting our score. 
Normally lazy- or polite-loading strategies apply to items 'below the fold', or items that are not in the viewport or not currently needed; this is a case where we are deferring something that is part of the main experience (chat).  

if we _are_ getting penalized, what is the best practice?

**Options:**

- load everything on initial load, eliminate network activity from setTimeout
- wait until user scrolls to fire chat

thanks!  

-

**Comment by patrickhulce** [comment]
The short answer: it depends, but probably not.

The long answer: 

Lighthouse waits for the conditions of [TTI](https://github.com/WICG/time-to-interactive#definition) to be satisfied before we stop observing page load. If your polite load waits long enough after TTI before registering (10 seconds would be long enough), then Lighthouse is certainly not penalizing you for this strategy.

If your polite load is not sufficiently far out though, then there's a decent chance that the chat script will push out TTI and affect your performance score. For example, if you're doing a `setTimeout(loadExpensiveThing, 10000)` but your page spends the next 10 seconds executing script and loading more resources, then the `loadExpensiveThing` isn't really separate from the page load experience, it's a seamless transition and it would be included in your metric values.

Does this make sense?

As for the recommendations, if the lazily/politely loaded resource is integral to the core experience of the page, don't defer it. If, however, it's an optional upgrade to the page experience, then deferring it to prioritize other content and let the user take an action without incurring the cost of the optional extra is a smart perf and user-friendly decision :)

**Comment by jaredstanley** [comment]
okay this makes sense. thank you!
