### ISSUE TITLE
Some Page will not fire event of Page.loadEventFired, This may cause SpeedIndex not accurate

### ISSUE THREAD

**Issue by kkdev163** [GoogleChrome/lighthouse#9527]
#### Provide the steps to reproduce
1. Run LH on https://mp.music.163.com/5c9c3a0ec91fac1390052994/pages/song/song.html?songId=1374061028&canBack=1

#### What is the current behavior?
when testing this page the cli always prints this log: 'Driver:warn Timed out waiting for page load. Checking if page is hung', I find this was caused by the event of  'Page.loadEventFired' not fired.  In console of devtools, I can find even this page is completed print and the document.readyState is 'complete', but the event of 'Page.loadEventFired' will not fire.

#### What is the expected behavior?
I want to know why the event 'Page.loadEventFired' not fired,  is the reason caused by page or devtools ? 
May we choose a candidate event when  'Page.loadEventFired' not fired to let the promise generate by _waitForLoadEvent be resolved?

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 5.2.0
* Node.js version: v10.16.0
* Operating System: macOS 10.14.3
* Google Chrome: 76.0.3809.100
**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @kkdev163! I'm not able to reproduce this issue though. That URL fires the load event and Lighthouse completes in under 20s for me.

Is it possible there is a different page based on geography/IP?

**Comment by kkdev163** [comment]
Sorry, I forget an extra condition. This Page was host in Mobile App, So It has some code logic depend on the  UserAgent. 

To reproduce this issue, we need to append an extra User-Agent to the file lighthouse-core/lib/emulation.js -> NEXUS5X_USERAGENT

after append the extra User-Agent the code will like:
```
const NEXUS5X_USERAGENT = 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse NeteaseMusic/5.9.0'
```
In my forked repo, I add a ci params of --extra-emulated-user-agent  to append extra User-Agent to emulated User-Agent, you can see this feature in this [commit](https://github.com/kkdev163/lighthouse/commit/1859ed6d2d1cacb60269dd861ead663e799a2547), I don't is this a commonly required feature, if you like this,  I can give a PR.

**Comment by patrickhulce** [comment]
I'm still not able to reproduce after that modification @kkdev163 :/ (Also as a general rule if a page refuses to load because it is served a particular user agent we would tend to consider that a bug of the page rather than the browser)

**Comment by kkdev163** [comment]
I agree with this bug is caused by the page. I also use the chrome extension named "tampermonkey" to insert a userscript to this page that confirmed the "onload" event is truly not fire.

It is the first time I know that "onload" event will be impacted by page logic which is normally displayed. This Page is not developed by me, and the author also curious about this. Can you give me some advice about what's logic may impact "onload", this will help us to find out this bug, thanks.

**Comment by patrickhulce** [comment]
Lots of things can delay the load event indefinitely, but roughly it's that there are resources that are still being loaded. Perhaps there is an infinite loop of some sort or the resources just take a very, very, very long time to finish loading?


Here's a screenshot from the [spec](https://html.spec.whatwg.org/multipage/parsing.html#delay-the-load-event) of the various references.

![image](https://user-images.githubusercontent.com/2301202/62874799-76510800-bce7-11e9-87a9-eabd5d633b57.png)

Hope this helps!

**Comment by kkdev163** [comment]
Thank your @patrickhulce, it helps a lot.

**Comment by brendankenny** [comment]
Looks like this was addressed. If not, please comment and we can reopen.
