### ISSUE TITLE
 Does not use HTTP/2 for all of its resources 80 requests not served via HTTP/2

### ISSUE THREAD

**Issue by rinasethia** [GoogleChrome/lighthouse#9529]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Would you mind filling out the rest of the template @rinasethia? We need that information in order to help. Thanks!

**Comment by brendankenny** [comment]
Closing as there hasn't been movement in some time. Please comment and we can reopen if you're still seeing this issue.
