### ISSUE TITLE
Single-use event listener improvements

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#953]
https://github.com/GoogleChrome/lighthouse/pull/937 adds an audit for single use (`{once: true}`) event listeners.

We should consider using the call site collection method for `removeEventListener()` and compare to the event listener's handler.

This has the added benefit of also catching library calls (jquery `unlisten()`) etc.

**Comment by paulirish** [comment]
#937 was closed so we wont need to explore this one any longer.
