### ISSUE TITLE
Mobile score is 0 ?

### ISSUE THREAD

**Issue by altenide** [GoogleChrome/lighthouse#9543]
I tested this site https://www.groupeidec.com/ Systematically mobile results are 0 out of 100. Is this normal? thank you so much

**Comment by altenide** [comment]
the test was done on https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fwww.groupeidec.com%2F&tab=mobile

**Comment by patrickhulce** [comment]
That's correct @altenide that page has several dozen render blocking resources that weigh in at several MB and on a mobile connection it will take nearly 20 seconds to first paint which earns a score of 0.

**Comment by haroldelfring** [comment]
![image](https://user-images.githubusercontent.com/9468805/63340804-22c66600-c348-11e9-850b-2ecd815a565f.png)

**Comment by altenide** [comment]
ok thank
