### ISSUE TITLE
PSI input should add the inputmode=url attribute

### ISSUE THREAD

**Issue by coliff** [GoogleChrome/lighthouse#9548]
This issue is regarding PageSpeed Insights site-https://developers.google.com/speed/pagespeed/insights/

I'd like the input to use `inputmode=url` so touch-screen users get the keyboard optimised for url entry (but without the annoyance of url validation). I use this site quite a bit on my iPad so this could be quite helpful.

REF:
- https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/#article-header-id-5

**Comment by patrickhulce** [comment]
Great suggestion thanks @coliff!

**Comment by coliff** [comment]
Hi - I just checked https://developers.google.com/speed/pagespeed/insights/ now and see that ` inputmode=url` has been added. Thanks - I'll close this issue now 👍
