### ISSUE TITLE
Running lighthouse on Nodejs server

### ISSUE THREAD

**Issue by marvinjude** [GoogleChrome/lighthouse#9549]
I'm trying to run lighthouse audit on a Nodejs server, I've tried different code samples in the docs but it's not working for me.

Basically, I'm trying to create an API that returns the lighthouse result for a website

```
const chromeLauncher = require('chrome-launcher');
const puppeteer = require('puppeteer');
const lighthouse = require('lighthouse');
const request = require('request');
const express = require('express');
const util = require('util');

const app = express();

const asyncMiddleware = fn => (req, res, next) => {
  Promise.resolve(fn(req, res, next)).catch(next);
};

async function launchChromeAndRunLighthouse() {
  const URL = 'https://www.chromestatus.com/features';

  const opts = {
    chromeFlags: ['--headless'],
    logLevel: 'info',
    output: 'json'
  };

  // Launch chrome using chrome-launcher.
  const chrome = await chromeLauncher.launch(opts);
  opts.port = chrome.port;

  // Connect to it using puppeteer.connect().
  const resp = await util.promisify(request)(
    `http://localhost:${opts.port}/json/version`
  );
  const { webSocketDebuggerUrl } = JSON.parse(resp.body);
  const browser = await puppeteer.connect({
    browserWSEndpoint: webSocketDebuggerUrl
  });

  // Run Lighthouse.
  return lighthouse(URL, opts, null).then(async result => {
    await browser.disconnect();
    await chrome.kill();
    return result.lhr;
  });
}

app.get(
  '/',
  asyncMiddleware(async (req, res, next) => {
    const results = await launchChromeAndRunLighthouse('https://google.com');
    res.json(results);
  })
);

app.listen(process.env.PORT || 8080, () => console.log('Running'));

```

**Comment by patrickhulce** [comment]
*General Lighthouse-as-a-API Advice* You definitely want to run Lighthouse in a child process if you're going to be doing this in a long-lived node context, lighthouse assumes it is being thrown away once it is done and will not support simultaneous runs in the same process. I'd also caution you that the performance results will be quite volatile if you intend to run more than one test at once. Unless the machine running this is *very* beefy, 1 run at a time is best for performance measurements.

As to the "it's not working for me", you'd have to be more specific for us to help. I don't see many log statements in there, at which point is something failing? Is this a local server? Can you see Chrome being launched if you try it without headless? What debugging steps have you already tried, etc?

**Comment by marvinjude** [comment]
Thanks for the insight @patrickhulce 

It works pretty nicely in my local environment with or without the `--headless`  flag, however, when I push to Heroku, It causes an internal server error `500`.  here is the log:

![logs](https://user-images.githubusercontent.com/17142206/63086905-bab9ef00-bf05-11e9-97fd-7995f381651b.PNG)

**Comment by patrickhulce** [comment]
This is venturing into general debugging advice @marvinjude which isn't what the Github issues are intended for. If you find a specific bug with Lighthouse, please feel free to come back with a fresh issue.


*PS - the logs say `ChromePathNotSetError` so I'm guessing you haven't set the Chrome path in heroku*

**Comment by marvinjude** [comment]
Thanks @patrickhulce 

For anyone experiencing this issue with heroku, I fixed it by adding a Google Chrome buildpack to my deployment ;)

https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-google-chrome#buildpack-instructions

**Comment by andreidiaconescu** [comment]
> _General Lighthouse-as-a-API Advice_ You definitely want to run Lighthouse in a child process if you're going to be doing this in a long-lived node context, lighthouse assumes it is being thrown away once it is done and will not support simultaneous runs in the same process. I'd also caution you that the performance results will be quite volatile if you intend to run more than one test at once. Unless the machine running this is _very_ beefy, 1 run at a time is best for performance measurements.
> 
> As to the "it's not working for me", you'd have to be more specific for us to help. I don't see many log statements in there, at which point is something failing? Is this a local server? Can you see Chrome being launched if you try it without headless? What debugging steps have you already tried, etc?

And how could i run the lighthouse in a separate process ?

**Comment by doooom2018** [comment]
I and I put all my bank accounts in a breach or hacked the final scan. You
still talked to me now. I stood what I do. Explain the preparation.

في الخميس، 7 يناير 2021 5:17 م Andrei Diaconescu <notifications@github.com>
كتب:
