### ISSUE TITLE
Support async/await in viewer

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9558]
Requires [uglify-es >= 3.0.17](https://github.com/mishoo/UglifyJS2/issues/1789#issuecomment-308821881). we are on 3.0.15.

Will do after #9546.

**Comment by wardpeet** [comment]
do we want to move to terser instead? uglify-es isn't activily being worked on. I can pick this up if you like.

**Comment by brendankenny** [comment]
if it's a drop-in solution SGTM. I mostly don't want to increase complexity since the only goal is a simple minification, and it would be great to be using something being actively developed.

**Comment by wardpeet** [comment]
Yes, it is. I'll create a PR, feel free to throw it away if it's too complex but it's more or less s/uglify-es/terser

**Comment by connorjclark** [comment]
terser should do the trick.
