### ISSUE TITLE
runtime errors in dark mode looks bad

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9559]
![image](https://user-images.githubusercontent.com/4071474/63052823-33349780-be95-11e9-9376-ea45964dc843.png)

**Comment by wardpeet** [comment]
Do we have a color scheme we would like? Do we just want to invert it?

CC @hwikyounglee

**Comment by hwikyounglee** [comment]
How would inverting look?

> Do we have a color scheme we would like? Do we just want to invert it?
> 
> CC @hwikyounglee

**Comment by baseeee** [comment]
Hello,

I'm interested in working on this, I'm trying to get more exposure to frontend development. 

In my local repo I've change the top-level warning background color in dark mode and it looks like this:
![image](https://user-images.githubusercontent.com/13604740/76022434-0faf6800-5f1f-11ea-9840-06929c77c134.png)

Is this along the lines of what you're looking for? Let me know your thoughts (and correct me if I'm doing anything wrong).

Thanks

**Comment by connorjclark** [comment]
Thanks for taking this @baseeee. We'll want some contrast with the background of the page, just like the lightmode has. It should be clear that this is a warning. I've pinged our designer Jiwoong to give his opinion on what color we should use.

**Comment by hwikyounglee** [comment]
Hello team, 

Wondering if we can use colors from the following (not the sidebar, but the color themes):

![image](https://user-images.githubusercontent.com/7561395/77139774-8d519880-6a34-11ea-80d9-946617880d15.png)

![image](https://user-images.githubusercontent.com/7561395/77139782-97739700-6a34-11ea-9788-ec3766c81d80.png)

https://yuinchien.com/sandbox/lighthouse/
Click the (i) on the top right corner, and also hit 'd' to toggle dark and light
![image](https://user-images.githubusercontent.com/7561395/77139854-ce49ad00-6a34-11ea-9a88-b1de65821de6.png)

Would it work?

**Comment by connorjclark** [comment]
I think that looks great! thanks @hwikyounglee 

@baseeee are you still available to help with this? Would also be nice to reduce the margin for the bullet points (more like the mock from Hwi)

**Comment by baseeee** [comment]
That looks perfect.

@connorjclark I'm still able to help, I'll reply here when I find time to make the change

**Comment by baseeee** [comment]
![image](https://user-images.githubusercontent.com/13604740/77252863-9e75f180-6c4e-11ea-8b3d-b70fc57d58f8.png)

![image](https://user-images.githubusercontent.com/13604740/77252870-aafa4a00-6c4e-11ea-9dd8-a67b53103f43.png)

I've now updated the colors and reduced the margin on the bullet list. I think it looks good, let me know if you're all happy with it and I'll submit a pr :)

**Comment by connorjclark** [comment]
Looks good to me color wise. Could you also look into reducing the margin of the entire box (just a little bit) and rounding the corners (like the mock)?

PR is good at this point :)

**Comment by connorjclark** [comment]
fixed by #10636
