### ISSUE TITLE
Hide network throttling configuration behind a settings tab

### ISSUE THREAD

**Issue by egsweeny** [GoogleChrome/lighthouse#9561]
We would like to remove the option to configure the throttling settings in the primary DevTools audit panel screen.

We still want users to have the option to change the throttling settings, but we don't want the options to be presented to the user so prominently in the primary configuration screen.

**What is the motivation or use case for changing this?**
We want to communicate to users through the UI that we feel strongly that the 'Simulated Slow 4G, 4x CPU Slowdown' default setting is what you should be optimizing your pages against. By putting it behind a settings tab/button, we are still providing flexibility while being more opinionated about what we know to be most reflective of how the average user experiences your page.

Furthermore, it helps to address issues with score variance. More specifically - if somebody has changed the default throttling setting in DevTools away from Simulated Slow 4G, there is a higher likelihood of them using LH in a different product surface and getting a different score --> and not necessarily understand why there is a delta.

**How is this beneficial to Lighthouse?**
Helps Lighthouse to be clear with users about the run configurations they feel are best for testing.

![image](https://user-images.githubusercontent.com/40670445/63055616-23b84d00-be9b-11e9-93aa-489348d429a2.png)

**Comment by patrickhulce** [comment]
I like this proposed change a lot! There is a lot of inadvertent mismatch of settings that leads to many issues filed here and folks confused about what settings equal what other settings. 

I'll go once step further and say that the fact that this radio button setting is sticky makes the "default" much less powerful than before. I'd also love to see a little flag or warning somewhere in the UI when you select something other than the default that "Hey it looks like you're not on the default LH settings, this may cause a mismatch with other environments, Want to reset it to the recommending settings?"

**Comment by connorjclark** [comment]
we need to square this with the new design for the audits panel

![image](https://user-images.githubusercontent.com/4071474/63453694-18ff3a00-c3fe-11e9-957e-e8e3269b9d22.png)

fyi @hwikyounglee

**Comment by connorjclark** [comment]
we moved this to a settings bar.
