### ISSUE TITLE
CHROME_INTERSTITIAL_ERROR throws on iframes

### ISSUE THREAD

**Issue by benschwarz** [GoogleChrome/lighthouse#9562]
#### Provide the steps to reproduce
1. Run LH on https://lh-iframe-interstitial.glitch.me/
  
#### What is the current behavior?
Lighthouse throws `CHROME_INTERSTITIAL_ERROR`

#### What is the expected behavior?
A successful test

#### Environment Information
* Affected Channels: All
* Lighthouse version: 5.2.0 (works in 5.1.0)
* Node.js version: 11.15.0
* Operating System: Mac OSX, Linux

I ran lighthouse with `ndb` to get a deeper look in: 

In `gather-runner.js`, #getInterstitialError: 

```
const interstitialRequest = networkRecords.find(record => record.documentURL.startsWith('chrome-error://'))
```

Returns a single network record, which appears to be a base64 encoded image of the chrome dino error states.

![image](https://user-images.githubusercontent.com/924/63073892-26d03d80-bf6e-11e9-9313-7c2d142cfc21.png)

![image](https://user-images.githubusercontent.com/924/63073834-e53f9280-bf6d-11e9-9f94-b570610a41fd.png)

**Comment by patrickhulce** [comment]
Thanks @benschwarz! I'm not able to reproduce this locally or with PSI though. Do you know if this page is employing geo-based content differentiation?

**Comment by benschwarz** [comment]
@patrickhulce Not sure about geo-based content differentiation, but I did notice that we did not see the interstitial error when adblocking was turned on. 

I think there's an ad/third party somewhere in there that throws one of the chrome-errors that's then identified in the network records. Does that sound plausible?

**Comment by benschwarz** [comment]
I was able to reproduce this every time. I could share the trace information from `--gather-mode` if that's useful for re-pro?

**Comment by patrickhulce** [comment]
No worries I made my own :) https://lh-iframe-interstitial.glitch.me/
