### ISSUE TITLE
Add stack traces back to driver.captureFunctionCallSites

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#957]
These had to be removed in #958 as we want a unique entry for each call site, not for each call stack (where you can have multiple call stacks that lead to the same call site).

However, storing each call stack that leads to that site *could* be useful for future audits (`callSite.stackTraces()` or whatever). Punting on this until we have an actual use case to motivate the design.

**Comment by patrickhulce** [comment]
captureFunctionCallSites is no longer used
