### ISSUE TITLE
Lighthouse wrongly detects head for phone devices.

### ISSUE THREAD

**Issue by Grizzlijs** [GoogleChrome/lighthouse#9573]
Hello,
From last update 2 weeks ago - Lighthouse is broken for us. Seems like it sends wrong head when launch audits test. I do test mobile devices but it reads desktop files and just makes it responsive. We are using userAgent ( Desktop / Tablet / Phone ) to detect diffrent devices.

**Comment by patrickhulce** [comment]
Thanks for filing! Could you explain a little bit more though? If you're referring to our user agent, we haven't changed the user agent in ~6 months.

If you're referring to mobile testing in Chrome DevTools then that's most likely covered by #9476

**Comment by Grizzlijs** [comment]
> Thanks for filing! Could you explain a little bit more though? If you're referring to our user agent, we haven't changed the user agent in ~6 months.
> 
> If you're referring to mobile testing in Chrome DevTools then that's most likely covered by #9476

For example if you run audits test for https://www.meinfoto.de/ Mobile in result you will see it shows error for page-desktop etc and in preview shows desktop template in responsive mode...
when you run same test on https://developers.google.com/speed/pagespeed/insights/ it works fine and detect correct page-mobile for mobile ...

**Comment by patrickhulce** [comment]
> For example if you run audits test

Where? **Are you referring to Lighthouse in Chrome DevTools?**

**Comment by Grizzlijs** [comment]
> > For example if you run audits test
> 
> Where? **Are you referring to Lighthouse in Chrome DevTools?**

Yes.
Chrome Version 76.0.3809.100
DevTools -> Audits
Device : Mobile

**Comment by patrickhulce** [comment]
Thanks! Then this is covered by #9476, follow along there for updates.
