### ISSUE TITLE
No LightHouse scores on some pages with WebPageTest.

### ISSUE THREAD

**Issue by pmd-bgermain** [GoogleChrome/lighthouse#9575]
#### Provide the steps to reproduce
1. Run a webpagetest on https://www.capital.fr or go to https://www.webpagetest.org/result/190819_8Q_aadf1661f1cd53525217b82c539cb54e/
2. Run a webpagetest with a script blocking all domains except capital.fr prismamedia.com prismaconnect.fr prismamediadigital.fr prismamediadigital.com capital.fr tra.scds.pmdstatic.net cap.img.pmdstatic.net or alternatively go to this test https://www.webpagetest.org/result/190819_QK_da88f3d697febd4be11cadcb2b298f96/1/details/#waterfall_view_step1

To help here is the WPT Script :
`// Block third party
blockDomainsExcept	www.capital.fr prismamedia.com prismaconnect.fr prismamediadigital.fr capital.fr pmdstatic.net prismamediadigital.com prismashop.fr tra.scds.pmdstatic.net cap.img.pmdstatic.net
navigate	https://www.capital.fr/`
 
#### What is the current behavior?
On the first test case you can see a lighthouse score on the top right (at least for PWA)
On the second test case you don't have that score.

#### What is the expected behavior?
You should see the score on the second test case

#### Environment Information
* Affected Channels: CLI, DevTools and tools like Webpagetest using lighthouse
* Lighthouse version: latest
* Node.js version: -
* Operating System: Linux, MacOS

#### More investigation on the issue
I looked at the WPT logs for Lighthous and saw : "Runtime error encountered: Chrome prevented page load with an interstitial. Make sure you are testing the correct URL and that the server is properly responding to all requests."
But I can't see any popin/interstitial on that page ...

**Comment by patrickhulce** [comment]
Thanks for filing with such detail @pmd-bgermain! This ends up being the same root issue as #9562 which we are working on :) Feel free to follow along there for updates.

**Comment by pmd-bgermain** [comment]
Hi @patrickhulce any idea when the #9576 (root to this issue and #9562) will be pushed in production ?

**Comment by patrickhulce** [comment]
@pmd-bgermain it should have already gone out with v5.4.0 a few days ago.

**Comment by pmd-bgermain** [comment]
Oh my !! I missed it... I checked just the day before 🤣  

Thanks @patrickhulce
