### ISSUE TITLE
Thinkwithgoogle test update, and how to report issue?

### ISSUE THREAD

**Issue by peixotorms** [GoogleChrome/lighthouse#9581]
Hello,

This is probably the wrong place to ask about this, but I cannot find any other information on where to report it. Please let me know if you can discuss it internally on google, or if you know somewhere else where to report this situation.

I have a client that scores 93 on Lighthouse / Pagespeed / web.dev tests.

However, on google ads, its mobile speed score shows up as 1/10.
http://prntscr.com/oux3t7

This new mobile speed score on google ads seems to have been introduced last month, but it doesn't come from google pagespeed insights or lighthouse.
https://support.google.com/google-ads/answer/9069088

It appears instead, to come from:
https://www.thinkwithgoogle.com/feature/testmysite/

And this tool, is also listed here:
https://developers.google.com/web/fundamentals/performance/speed-tools/

---

I need to report some issues with 
https://www.thinkwithgoogle.com/feature/testmysite/

Please redirect me to the correct place, or please forward it internally.

Thinkwithgoogle (just a couple months ago) used to report that a loading time under 5 seconds was a top performer, and anything under 3 seconds was excellent: http://prntscr.com/oux7kd

Please note, that it was already very difficult to make a page, no matter how simple it was, to load at 3 seconds on thinkwithgoogle (they always measure things much slower than other tests). 
This is probably due to some issue on webpagetest, since they have used it under the hood.

With the new Google Ads update showing the mobile score, it seems that thinkwithgoogle tests were updated, without considering the tool capabilities.

Now if you want to be a fast site, you need to load under 1 second.
Average pages start to load in 1 to 2.5 seconds, and anything above 2.5 seconds is slow.

I agree with these speeds, but thinkwithgoogle seems to have limitations and is measuring the minimum speed at 1.1 second, thus making it impossible to have a fast site.

Furthermore, on that test page you have a rating at the top showing your speed on 4G in the United States, but further down you have a different speed and score on another section.

For example, try to test google.com:

We get 1.1 seconds, average speed (seems to come from webpagetest or something else):
http://prntscr.com/ouxa41

And further down, we get 2.1 seconds (seems to come from lighthouse, maybe)
http://prntscr.com/ouxabp

So we have different scores on the same page.

But the real issue, happens when we test an HTML page with only the text saying OK.
This is a static html file, with "OK" in it, served from the USA on a cloud server and nginx... so it should load instantly.

It so happens than even a 2 char html page, still loads at 1.1 seconds on thinkwithgoogle:
http://prntscr.com/ouxba2
http://prntscr.com/ouxbgn

In addition, a lot of pages on thinkwithgoogle are missing (404), when you try to check for more information on those metrics.

So to recap, 

a) Google Ads mobile speeds are artificially low, and
b) this seems to be because of thinkwithgoogle

I need to report this information to google, but I cannot find anywhere else to report it.

I'm thinking that the google ads team and the thinkwithgoogle team might be interested in this.
I'm not sure if google ads is using thinkwithgoogle (though they recommend it) and neither I am sure if thinkwithgoogle is also using lighthouse (seems like, at least on the recommendations part).

I'm guessing that the initial 1.1 second delay is because thinkwithgoogle is testing the http version and then being redirected to https.
I tested the https version, but once I email myself their report, it seems like it requests the http version: http://prntscr.com/ouxcoa

If the lighthouse team has any idea on this, please let me know if you can handle it internally, or where can I send this to.

Thanks,

Raul Peixoto

**Comment by brendankenny** [comment]
ping @egsweeny

**Comment by peixotorms** [comment]
Anyone looking into this after 6 months?

**Comment by egsweeny** [comment]
Hello @peixotorms - so, a [new version of the Test My Site tool](https://blog.google/products/ads/new-ads-innovations-grow-business) was just launched last week - let me know if you're still experiencing the issues?

**Comment by peixotorms** [comment]
@egsweeny thanks, but still something looks odd.

Google loads in 1.3 seconds and get's Good / Green.
A small one page site I own loads in 1.2 seconds and it needs improvement / yellow.

https://i.imgur.com/jTSfycO.png
https://i.imgur.com/Z5wjB0W.png

This doesn't fit the description here:
https://i.imgur.com/qISWKq5.png

And not even google loads under 1 second, so the good/needs improvement rating, is not about the loading time as measured by the tool, but rather the CRuX reports or something else.

**Comment by paulirish** [comment]
Sorry we never got this resolved, @peixotorms. We've always appreciated your bug reports.

Holler if this is still an issue for you. But I imagine you've moved on. 

Heh. and apparently TMS is also done: 
![image](https://user-images.githubusercontent.com/39191/186248247-463143e8-c562-46f7-bf02-5c567fdae8bf.png)

cheers
