### ISSUE TITLE
Lighthouse audit in devtools doesn't use a mobile useragent

### ISSUE THREAD

**Issue by awexfwex** [GoogleChrome/lighthouse#9582]
#### Provide the steps to reproduce
1. Run LH, selecting mobile from the device drop down.
  
#### What is the current behavior?
Once the audit completes, inspect the user-agent used at the bottom of the report. It will be the real browser user-agent.

eg. 

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

#### What is the expected behavior?
The user-agent should be that of an emulated mobile device.

#### Environment Information
* Affected Channels: DevTools
* Chrome version: 76.0.3809.100 64 bit
* Lighthouse version: 5.1.0
* Node.js version: v10.13.0
* Operating System: OSX 10.13.6

**Related issues**

**Comment by connorjclark** [comment]
This will be fixed in Chrome 77. Sorry for the inconvenience. Should work in beta/canary Chrome.
