### ISSUE TITLE
Images broken after running Lighthouse

### ISSUE THREAD

**Issue by lbelling** [GoogleChrome/lighthouse#9585]
After I'm done running lighthouse all the images on my site are broken.  Usually I can get them to come back by clearing the browser cache and restarting the browser several times, but that's no longer working now.  How do I reset Chrome back to where it was before running Lighthouse?

![image](https://user-images.githubusercontent.com/10965310/63395400-3a720e80-c389-11e9-89be-1b89533bd5af.png)

**Comment by paulirish** [comment]
(It appears image serving is broken sporadically on your site. Just opening the page in incognito windows can reproduce this.)

(It appears you know this already.)

(cheers)

(😘)

**Comment by lbelling** [comment]
yup - it's not you, it's me :)

**Comment by lbelling** [comment]
Actually, it's cloudflare.  Something Lighthouse is doing is messing up the cloudflare cache.
