### ISSUE TITLE
Audit process fails after navigating away form the site

### ISSUE THREAD

**Issue by aviationfan** [GoogleChrome/lighthouse#9599]
Running lighthouse on the site we are testing would be a great benefit to the project but for some reason the process fails to complete. We see the site load then a navigation away from the site and a blank browser as it is doing some audit that ultimately fails.

Would a run with --verbose help debug this?

#### Provide the steps to reproduce
1. 
`lighthouse 'https://qa2.peoples.com/openaccount/acs?region=2&externalProductCodes=001' --emulated-form-factor desktop`
  
NOTE: This site is only available to US based IP addresses from 9am to 5pm eastern time

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.2.0
* Node.js version: 12.9.0
* Operating System: Mac OS 10.13.6 High Sierra
[lighthouse-out-qa2.peoples.com.txt](https://github.com/GoogleChrome/lighthouse/files/3535004/lighthouse-out-qa2.peoples.com.txt)

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing! It looks like your server does not respond to `http` at all? We timeout while waiting for the response to our request that checks if the page redirects to `https`.

The report is still generated with everything else we could find out about the page, so from our perspective I think this is WAI. Perhaps a slightly more specific error message that the warning occurred *while on the HTTP redirects pass*?

**Comment by aviationfan** [comment]
Thank you for that information. By skipping that audit, the process completes and I get a report

`lighthouse 'https://qa2.peoples.com/openaccount/acs?region=2&externalProductCodes=001' --emulated-form-factor desktop --skip-audits redirects-http`

How did you know that was the failing audit so I can know that in the future?

It seems like a better tool behavior would be to detect the failure to accept http at all and report it.

**Comment by patrickhulce** [comment]
You're welcome @aviationfan!

> How did you know that was the failing audit so I can know that in the future?

1. I ran Lighthouse on the URL and saw the toplevel warning + `?` category score.

![image](https://user-images.githubusercontent.com/2301202/63624838-5f51c600-c5c3-11e9-80b9-ab9a5eaf3b64.png)

2. I clicked on the `?` category score and saw the "Error!" for "Redirects HTTP traffic to HTTPS".

![image](https://user-images.githubusercontent.com/2301202/63624935-b2c41400-c5c3-11e9-8d30-7cecbd40821e.png)


> It seems like a better tool behavior would be to detect the failure to accept http at all and report it.

That's what the "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_TIMED_OUT)" warning plus the audit failure for "Redirects HTTP traffic to HTTPS" is intended to indicate. Do you have a suggestion for an alternative?

**Comment by aviationfan** [comment]
`PROTOCOL_TIMEOUT` is a new error that showed up when I tried it from within Chrome instead of at the command line. I was thinking that the tool could detect that a site does not accept requests using HTTP on port 80 without failing the flow. We could leave the `PROTOCOL_TIMEOUT` to other bug reports.

Do I need to update my installation?
```lighthouse --version
5.2.0```

Can I provide some verbose output piped to a file in some way to help in the research?

**Comment by patrickhulce** [comment]
> I was thinking that the tool could detect that a site does not accept requests using HTTP on port 80 without failing the flow

It does. 

> The reason I opened this issue is because Lighthouse fails when run at the command line and no report is produced.

On closer inspection this does not seem to be accurate. The logs you provided even print the path that the HTML report was written to "/Volumes/Big3_1/work/lighthouse-tests/qa2.peoples.com_2019-08-23_08-35-39.report.html"

For example, this is the report I just generated using a fresh installation of version 5.2.0 and have reconfirmed it working in Chrome Canary, https://googlechrome.github.io/lighthouse/viewer/?gist=56e8a72211f5a377e0418c0ae22f1de9.

**Comment by aviationfan** [comment]
I am going to close this issue as I can no longer reproduce the problem which tells me it works fine now. Thanks for all the help and patience.
