### ISSUE TITLE
5.3

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#9601]
I really want to deploy the new i18n translations to PSI/LR so that they can stop having messed up markdown and such. Anyone have any issues with a new patch version?

My requested minimal diff: https://github.com/GoogleChrome/lighthouse/compare/f3a22306f...8333f2a

Diff with some extra goodies: https://github.com/GoogleChrome/lighthouse/compare/f3a22306f...d17ce87af

@brendankenny @paulirish @connorjclark @patrickhulce

**Comment by connorjclark** [comment]
Sounds like a good chance for you to do your first release :)

**Comment by benschwarz** [comment]
Patch release sounds great @exterkamp. There's also the interstitial issue that I'm sure if giving a lot of folks grief! From what I can tell, that was a pretty far-reaching issue.
