### ISSUE TITLE
New Audit: Avoid file versioning for certain file types

### ISSUE THREAD

**Issue by Malvoz** [GoogleChrome/lighthouse#9607]
Developers should avoid versioning the URLs (as otherwise commonly used for cache-busting) of both service workers and web app manifest files as described in:

- https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#avoid-url-change
- https://github.com/w3c/manifest/issues/446#issuecomment-351368893

/cc @jeffposnick

**Comment by jeffposnick** [comment]
It's a good thing to avoid, but it seems super-hard to detect, though? If someone does decide to, e.g., add a hash into a service worker file, how many characters will that hash have? What will separate the hash from the file name? All of that is up to the developer and is hard to generalize.

**Comment by Malvoz** [comment]
You're totally right, there are some conventions that could be looked for however. I think the most prominent convention for file versioning is `<filename>(./-)<hash>.<extension>` and query strings e.g. <br>`<filename>.<extension>?=<hash>`.

Plus developers are free to name the files anything they want, too. I think service workers are mostly named `sw.js`, or `service(-/_)worker.js`. While manifests `(web)manifest.json` and `*.webmanifest`.

It may be that it isn't worth the effort of implementing such an audit, especially considering there's no guarantee to catch all the mistakes. I also don't have any data that suggests that this is even all that common of a mistake, to support this audit request.

**Comment by Malvoz** [comment]
FWIW, the [`Sec-Fetch-Dest`](https://w3c.github.io/webappsec-fetch-metadata/#sec-fetch-dest-header) HTTP header exposes the request destination, in which both `manifest` and `serviceworker` is defined.

**Comment by Malvoz** [comment]
This is a duplicate issue of https://github.com/GoogleChrome/lighthouse/issues/2570, closing.
