### ISSUE TITLE
iframe title attribute

### ISSUE THREAD

**Issue by MickyLee3** [GoogleChrome/lighthouse#9609]
Chrome DevTool audit recommends Title attribute for <iframe>, but that attribute isn't in HTML5 or is it?

**Comment by MickyLee3** [comment]
My Chrome DevTool ran an audit on one of my web pages.  It complained that the <iframe> had no Title attribute.  My source, https://www.w3schools.com/tags/tag_iframe.asp , does not include Title in its list of HTML5 iframe attributes.  There is a Name attribute.  

Is Lighthouse correct in its audit?

**Comment by patrickhulce** [comment]
Yes, Lighthouse is correct here. You can refer to the [linked documentation](https://web.dev/frame-title/) for each audit to learn more about it.

Also, w3schools is not a very reliable reference. I'd encourage you to use [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) instead when researching DOM APIs which has support from and is maintained by multiple browser vendors.

**Comment by MickyLee3** [comment]
Thanks for the MDN reference. It's interesting that MDN's list of attributes, including global ones, does not include Title, but several of its own examples show the use of Title.  So, I'm still a bit confused.  Is Title some very special attribute?
