### ISSUE TITLE
LH is not reporting offscreen images

### ISSUE THREAD

**Issue by dooman87** [GoogleChrome/lighthouse#9610]
#### Provide the steps to reproduce
1. Run LH on http://www.midday.coffee/original/cups.html
  
#### What is the current behavior?

Offscreen images audit is marked as passed

#### What is the expected behavior?

I would expect to offscreen images audit to fail as there are many images below the viewport.

#### Environment Information
* Affected Channels: CLI, DevTools
* Lighthouse version: 5.2.0
* Node.js version:12.7.0
* Operating System:MacOS Mojave

**Related issues**

**Comment by Malvoz** [comment]
To clarify, because I thought the description was a bit vague; the website does not lazy-load images, but the it still passes the "Defer offscreen images" audit.

**Comment by Malvoz** [comment]
To clarify, because I thought the description was a bit vague; the website does not lazy-load images, but it still passes the "Defer offscreen images" audit.

**Comment by dooman87** [comment]
Thanks @Malvoz for clarifying. Will try to do better next time, sorry.

@patrickhulce Thank you for an explanation! I was trying to demo failed "Offscreen Images" behaviour on the page from the issue. On older version of LH it was failing, but I think algorithm has been changed since then. Is there any docs about critical network requests or sources would be the best place to look?

Thanks a lot for helping!

**Comment by dooman87** [comment]
Yeah, it was a very old version thats been a plugin for Chrome at that time. I used the page for my blog article as an example. Thanks a lot for the link.

I'll play around with the page. Maybe if I do images actionable (links?) then it will contribute to TTI.

**Comment by brendankenny** [comment]
Looks like this issue was addressed. If not, please comment and we can reopen.
