### ISSUE TITLE
PSI makes multiple requests for the same resources.

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9613]
Related: #8990

![image](https://user-images.githubusercontent.com/4071474/63726099-29098600-c811-11e9-8005-80d8d26e8a4e.png)

https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fwww.gatsbyjs.org%2F&tab=desktop

Doesn't happen in CLI 5.2.0 (PSI is currently on that version).

devtools log for gatsby run in PSI: https://gist.github.com/connorjclark/743798781bb7dd03f1964c006e163ed0

Just look at the defaultPass - I see three requests for `https://www.gatsbyjs.org/app-23b7faf83f106071a101.js`.

First is the expected request.
Second is one from the service worker (the script is requesting itself - see the callFrames).
Third - idk why?

**Comment by connorjclark** [comment]
this is what it looks like now

![image](https://user-images.githubusercontent.com/4071474/65551522-02557280-ded7-11e9-9f18-5d413b00c856.png)

**Comment by brendankenny** [comment]
@connorjclark should we close and merge with #8990?
