### ISSUE TITLE
Audit accessibility for pages with dialog

### ISSUE THREAD

**Issue by samifahmy** [GoogleChrome/lighthouse#9618]
hi there,
i'm trying to used chrome dev toolbar audit function (lighthouse 4.3.1) to check web app accessibility
and i have this scenario  
i have a page that have couple of buttons to open different model dialogues (Data entry Forms) , audit doesn't capture any errors in these dialogue as once page refresh dialog disappear -initial page reload-.
any suggestions for work around will be appreciated

**Comment by brendankenny** [comment]
Looks like this issue was addressed. If not, please comment and we can reopen.
