### ISSUE TITLE
An ability to pass HTML file instead of URL

### ISSUE THREAD

**Issue by constantant** [GoogleChrome/lighthouse#9625]
**Feature request summary**
While testing a11y on our projects we need to test not only simple pages but SPA with complex functionality which is not possible to do with the current Lighthouse.

**What is the motivation or use case for changing this?**
It is not possible to check dynamic added DOM: modal windows, dropdowns, tabs, etc

What we do for now:
- Using Protractor to get needed state of an app (Angular)
- Getting snapshot as a HTML file
- Putting the file on a separate HTTP server
- Passing needed URL of the file to Lighthouse
- Getting the result

**How is this beneficial to Lighthouse?**
Will be nice if Lighthouse does all those dancing with the separate HTTP server form a box.

**Comment by paulirish** [comment]
If I understand your feature request, your 5 steps would reduce to just 4 as you wouldn't have to do "Putting the file on a separate HTTP server".  Is that right?

Web browsers treat file:// protocol very differently than http/https so thats why we don't encourage testing pages on file:// protocol. (Admittedly the accessibility tests won't differ at all, but others would)

**Comment by constantant** [comment]
Also I do not need have extra HTTP server and store extra settings for that.

Of course will be much better if you provide a plugin for Protractor which allows to check a11y just with a simple function.

While waiting for the plugin will be great to have at least this ability.

**Comment by paulirish** [comment]
> Of course will be much better if you provide a plugin for Protractor which allows to check a11y just with a simple function.

https://github.com/angular/protractor-accessibility-plugin

there ya go

**Comment by constantant** [comment]
The last commit about 3 years ago... I will die during approving that 😁
