### ISSUE TITLE
i18n: untranslated strings in font-size

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9632]
`Add\'l illegible text`
`Legible text`

**Comment by adamraine** [comment]
Should we add these strings to the issue?
https://github.com/GoogleChrome/lighthouse/blob/e68ef0ef7b940103fa73e3334c33258e72a25684/lighthouse-core/audits/seo/font-size.js#L271-L276

**Comment by adamraine** [comment]
Gonna make the above changes
