### ISSUE TITLE
Lighthouse encounters error when trying to audit website on my local server.

### ISSUE THREAD

**Issue by vanianignacio** [GoogleChrome/lighthouse#9634]
I'm trying to audit a website on our staging environment to compare the performance between same website on our production environment. Running Lighthouse on the production environment is okay but when I try to run the audit on our staging environment Lighthouse keeps on running into an error while starting up. I already tried running the audit in incognito mode without any extensions or other tabs.
![Capture1](https://user-images.githubusercontent.com/38095275/64152729-ce4eda80-ce5f-11e9-9976-d51bf7ce3b4a.JPG)

**Comment by wardpeet** [comment]
Hi vanianignacio!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to share your codebase or a way to reproduce this.

Thanks for using Lighthouse! 💜

**Comment by brendankenny** [comment]
Without a new update, closing this issue. Please comment if you're still having a problem and we can reopen.
