### ISSUE TITLE
Smokehouse: add deeper audit result comparisons

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#964]
Want it to still be simple if wanted, still opt-in on what to compare based on what's provided in expectations file, but we need the ability to be able to compare not just `score` but `rawValue`, `extendedInfo`, etc so we can do things like count of failures, match line/column numbers of errors, etc

**Comment by brendankenny** [comment]
I'm thinking the expectations file can be something like

- if you provide a primitive value in the expectations file it'll do a direct comparison with `score` (as it does now)
- if it's an object, it'll do a deep comparison, but only on the fields provided in the expectations file, ignoring anything else. This allows not having a super-verbose expectations file and matching only on the things that really matter

this will still be strict equality, so still not a good system for comparing floating point numbers or doing something like a regex on a string. Not sure of a non-hairy way to allow specifying a comparator for everything.

**Comment by ebidel** [comment]
For me, the most important thing for catching DBW bugs is automating the manual checking of dbw_tester.html results. That page currently has a bunch of edge cases that are harder to cover with unit tests. Being able to compare the audit's `extendedInfo.value.length` against an expected value would be marvelous.

**Comment by patrickhulce** [comment]
anything wrong with accepting a function there and catching arbitrary `AssertionError`s?

**Comment by brendankenny** [comment]
> That page currently has a bunch of edge cases that are harder to cover with unit tests. Being able to compare the audit's extendedInfo.value.length against an expected value would be marvelous.

Yeah, definitely, I just want to avoid overfitting.

I think the instinct will be to do complete deep equals comparisons on results. It's good to check that the report will get an object in the format it expects, for instance, but I'm not sure if that's necessarily good for smokehouse, as the expectations file will quickly get unwieldy and we'll have a lot of churn with each change to an audit. If we have to regenerate test expectations for every PR, we quickly lose them as a good diagnostic.

e.g. we check that a DBW audit returned 6 violations and that the line and column numbers for them are correct but *not* that the line and column numbers are formatted correctly in the `label` or that the `helpText` is included in the audit result. We really want to leave that sort of thing up to unit tests and (*ahem*) type checking, and rely on smokehouse more for end-to-end things and stuff that's difficult to mock, like driver and browser behavior.

**Comment by ebidel** [comment]
> ...formatted correctly in the `label` or that the `helpText` is included in the audit result.

Agreed. I see smokehouse has continuing to be a "yes/no", "did it pass?" check. In the case of the DBW audits, it extends that to verifying "you passed/failed x number of times" for this audit.

**Comment by ebidel** [comment]
@brendankenny can you take this? I just ran into another issue that would have been caught :\

**Comment by brendankenny** [comment]
Yes, currently in progress :)

**Comment by brendankenny** [comment]
done
