### ISSUE TITLE
Repeatedly getting 0 on the Lighthouse tests for https://www.globalforestwatch.org/ 

### ISSUE THREAD

**Issue by etelai** [GoogleChrome/lighthouse#9647]
Hi, I keep getting a 0 on the Lighthouse tests for this website: https://www.globalforestwatch.org/ 

As per this page https://developers.google.com/web/tools/lighthouse/scoring:
"A 0 score usually indicates an error in Lighthouse. If you see a 0 score repeatedly, please file a bug on the Lighthouse repo." 

Attached is a report for reference.
[Lighthouse Report-gfw-2019-09-07.pdf](https://github.com/GoogleChrome/lighthouse/files/3587987/Lighthouse.Report-gfw-2019-09-07.pdf)

Is there something I can do to be able to test the speed? Thank you.

**Comment by exterkamp** [comment]
Thanks for filing!  

First off, @kaycebasques @paulirish, seems like the base [scoring link](https://developers.google.com/web/tools/lighthouse/scoring) goes to v2, and not the current [v3](https://developers.google.com/web/tools/lighthouse/v3/scoring), any way to fix that? It can be confusing.

@etelai I ran this site again and get a consistent 0/100 in performance. With a TTI of 40s+ and an FCP of 30s I think that this 0 is valid. Looking at the CrUX data for this site as well,  97% of Chrome users are getting a slow first paint on this page, with it's 90th percentile being 18.6s [PSI link check out "Field Data"](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.globalforestwatch.org%2F).

If you want to test speed I recommend going to DevTools (F12) and running a performance analysis in the performance panel, this will give you a lot of data about what is going on in the load ([guide](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/)). And to see an approximation of what Lighthouse is loading the page like, go to the network panel and turn on the throttling settings to "Fast 3G" ([how to](https://developers.google.com/web/tools/chrome-devtools/network/#throttle)), it definitely makes this site take 30s+ for me to load/paint anything.

Hope that helps!

**Comment by etelai** [comment]
This is excellent, thank you so much for looking into this @exterkamp. I will study the resources your shared I will work on improving the site's speed with the dev team. Thank you!

**Comment by exterkamp** [comment]
Sounds great! Good luck!
