### ISSUE TITLE
No manifest was fetched

### ISSUE THREAD

**Issue by zealguy** [GoogleChrome/lighthouse#9648]
Runtime settings
URL: https://zealguy.de/
Fetch time: Sep 9, 2019, 5:20 PM GMT
Device: Emulated Nexus 5X
Network throttling: 150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
CPU throttling: 4x slowdown (Simulated)
User agent (host): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/76.0.3809.100 HeadlessChrome/76.0.3809.100 Safari/537.36
User agent (network): Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3559.0 Mobile Safari/537.36
CPU/Memory Power: 156

**Comment by zealguy** [comment]
Runtime settings
URL: https://zealguy.de/
Fetch time: Sep 9, 2019, 5:20 PM GMT
Device: Emulated Nexus 5X
Network throttling: 150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
CPU throttling: 4x slowdown (Simulated)
User agent (host): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/76.0.3809.100 HeadlessChrome/76.0.3809.100 Safari/537.36
User agent (network): Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3559.0 Mobile Safari/537.36
CPU/Memory Power: 156

**Comment by patrickhulce** [comment]
This is expected when the page does not register a manifest.

![image](https://user-images.githubusercontent.com/2301202/64557892-2d04d000-d308-11e9-9434-84375c095a03.png)
