### ISSUE TITLE
Why the change from 3G to 4G? Add possibility to pick?

### ISSUE THREAD

**Issue by OZZlE** [GoogleChrome/lighthouse#9656]
Before creating an feature request please make sure you are using the latest: 
✅ 

**Feature request summary**
Add also 3G in Audit

**Describe what you want to be added:**
Option to use 3G as before OR 4G or a fair explanation of why it changed.

Are you willing to work on this yourself?
⛔️ 

**What is the motivation or use case for changing this?**
End-customers having 3G, measure their performance

**How is this beneficial to Lighthouse?**
🤷‍♂

**Comment by patrickhulce** [comment]
Thanks for filing!

If you're referring to the default throttling settings, the change from "Fast 3G" to "Slow 4G" was in name only and no throttling settings under the hood were actually changed. The observed percentile latency and bandwidth in Chrome data between ~85th percentile 4G and ~25th percentile 3G are quite similar.

We've discussed offering multiple throttling profiles in the past, but it's not on our radar for the near future at this time.

**Comment by OZZlE** [comment]
Big thank you for the fast response!! Not sure why it needed to change name but good to know! :)

I think the industry standard has been to measure Fast 3G since a couple of years back but yeah then this is the same with another name :D
