### ISSUE TITLE
URL used to "Run Audit" and URL within the "View Report" do not match

### ISSUE THREAD

**Issue by 142504** [GoogleChrome/lighthouse#9659]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by connorjclark** [comment]
url?

**Comment by connorjclark** [comment]
we display the finalurl in the report. so if any redirects happens, you'll see a different url than you inputted.

**Comment by connorjclark** [comment]
#10157 will help.
