### ISSUE TITLE
xhtml doctype - lighthouse

### ISSUE THREAD

**Issue by jcrm70** [GoogleChrome/lighthouse#9660]
Hi there!

When i check an xhtml page that starts with '<! DOCTYPE html PUBLIC "- // W3C // DTD XHTML 1.0 Strict // EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict .dtd ">', lighthouse says ' doctype disappeared' or 'you don't have doctype' (something similar).

Then i read that the document should be served as of the type 'application/xhtml+xml', and i have set Apache to serve that type, but lighthouse, continues by saying that the document has no doctype.

I need the document to be xhtml in order to include iso-8859-1, since the html entities do not serve my purpose, and I have a little confusion because according to the w3c xhtml it is valid as html5.

Does this have a known solution?.
Thank for read.

**Comment by patrickhulce** [comment]
I'm not really sure how to respond @jcrm70.

1. I don't know why you still believe that `utf-8` forces you to author using HTML entities. It doesn't. Most of the search results for avión and avion are `utf-8`. 
1. Obviously no one searches for `avi&oacute;n`. Ironically, most of the search results I get for `avi&oacute;n` are mistakes by the website developer that didn't know how to use a proper encoding.
1. None of this discussion has actually raised an issue with following the doctype recommendation at all. If you have such a problem with `utf-8`, you're still free to override the utf-8 default in HTML5 with `<meta charset="iso-8859-1">`  and/or the content-type header.

We won't be removing our audit to check for an HTML5 doctype. The entire point of Lighthouse is enforcing best practices to build better websites. All the documentation from all major bodies obviously encourages this practice, if anything your screenshots have shown why it's important to enforce, and it won't be changing.

Best of luck solving your issue.

**Comment by jcrm70** [comment]
After reading you, I may have understood something wrong. You say I use meta charset iso-8859-1 with html5, so I must be doing something wrong. Please tell me how I can use it without errors. And why here tells me that the only value allowed is utf-8?

![iso88591_an_html5](https://user-images.githubusercontent.com/53938793/64877664-29e44980-d652-11e9-902e-8d451b593cd3.jpg)

**Comment by nayuki** [comment]
> why here tells me that the only value allowed is utf-8?

If you use `<meta charset="...">`, the value **must** be `UTF-8`. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attributes).

For non-UTF-8 character encodings, use the old syntax like this:

    <meta http-equiv="Content-Type" value="text/html; charset=ISO-8859-1">

**Comment by nayuki** [comment]
> why here tells me that the only value allowed is utf-8?

If you use `<meta charset="...">`, the value **must** be `UTF-8`. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attributes).

For non-UTF-8 character encodings, you can use the old syntax like this:

    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
