### ISSUE TITLE
xhtml doctype - lighthouse (2)

### ISSUE THREAD

**Issue by jcrm70** [GoogleChrome/lighthouse#9669]
I have read your answer, but I have some doubts, and how you closed it, I can open another one because I don't know if you will read my answer in which you closed, so I take the liberty of repeating it here.

After reading you, I may have understood something wrong. You say I use meta charset iso-8859-1 with html5, so I must be doing something wrong. Please tell me how I can use it without errors. And why here tells me that the only value allowed is utf-8?

![iso88591_an_html5](https://user-images.githubusercontent.com/53938793/64879396-2fdc2980-d656-11e9-951a-ac1d31d57350.jpg)

**Comment by patrickhulce** [comment]
Apologies @jcrm70 the living standard has been updated this is not actually valid. I updated my comment accordingly. The rest of the rationale for utf-8 still stands.
