### ISSUE TITLE
TTFB Reporting Incorrectly

### ISSUE THREAD

**Issue by hecktarzuli** [GoogleChrome/lighthouse#9671]
In this run, the report says TTFB was 0.03s, and that it was too long.  In reality it was too long (~630ms, but certainly not 0.03s)

THE WEIRD RESULT
https://wpt1.speedcurve.com/lighthouse.php?test=190911_C8_a09d5ef039e903e4387bec9754b9c65c&run=1

3 TESTS
https://wpt1.speedcurve.com/result/190911_C8_a09d5ef039e903e4387bec9754b9c65c/

#### Environment Information
* Affected Channels: ?
* Lighthouse version: 5.2.0
* Node.js version: ?
* Operating System: ?

**Comment by patrickhulce** [comment]
Thanks for filing @hecktarzuli it's actually trying to tell you that it was `0.03 s` *too* long. This is admittedly confusing but consistent with the rest of the opportunities that tell you how much time you could save if you followed the advice (which in this case is to keep it under 600 ms).

Perhaps this should be moved to a diagnostic Lighthouse core team?

**Comment by hecktarzuli** [comment]
LOL, time for me to stop working today :)

**Comment by brendankenny** [comment]
Keep an opportunity but add a dom-size-like table to better summarize what's going on.

**Comment by brendankenny** [comment]
From @patrickhulce in #9034

> IMO we could reasonably be showing x - 100 as the "opportunity" and just only flag things that take 600 ms to avoid this problem entirely.

**Comment by patrickhulce** [comment]
Plan: 
- Add a details table for the ttfb audit with details about the request
- report savings as if our target were 100ms since 600ms is really just a DevTools throttling limitation and we would really want to do 100ms if we could
