### ISSUE TITLE
xhtml doctype - lighthouse (3)

### ISSUE THREAD

**Issue by jcrm70** [GoogleChrome/lighthouse#9675]
Thank you for modifying your answer. Although I think that now that you know that html5 is only compatible with utf-8, I think this paragraph also needs to be modified:

"I don't know why you still believe that utf-8 forces you to author using HTML entities. It doesn't. Most of the search results for avión and avion are utf-8."

I think now you know why utf-8 forces you to author using HTML entities when the language is not English.

So, we have any html5 (utf-8) page with the word 'avión' is a mistake.  And that to write in a non-English language, iso-8859-1 is needed for the rest of the world, which is currently supported by xhtml and w3c.

I think you may have already realized that it is not possible to write non-English text in HTML5 without errors, which many messages ago I told you. And if you want to write well 'avión' it must be in xhtml that supports iso-8859-1.

And, are you sure that it is a good idea to write in utf-8 and that no search engine finds you when users search for normal text? or maybe you believe that people go to put 'avi&amp;oacute;n' 
for satisfy your desire of utf-8 required.

The html5 documents will technically be more modern, but people look for normal text not html entities, and obviously follow your standard outside of English-speaking countries, it is the same as giving up on the search engine results, because the search engine of googe dont' work like you propouse. So I think someone You will realize that it is bad for the rank of search engines by google words non english.

And see that it is easy eh, because the same website you change the declaration of xhtml to html5 and you already give it good, without doing anything more than that (and remove type = "application / ecmascript" and type = "text / css" by html5).

Answer me directly please, and we're done:

You understand that your currently standard is contrary to all non-English languages and therefore is not very good and you must adapt it to the entire world (google search included).

**Comment by paulirish** [comment]
it sounds like you don't like this tool. please stop using it. 

also, please stop filing issues here.
