### ISSUE TITLE
lighthouse

### ISSUE THREAD

**Issue by ajayshrivas** [GoogleChrome/lighthouse#9678]
How can i solve issue , because desktop is good Performance like 89-91 score but mobile on 30-42.

There different system different result like gtmetrix on show 91 page score .

**Comment by ahmadalfy** [comment]
Maybe read the recommendation and apply it? This repository is for reporting bugs on the tool

**Comment by HebaHeba1991** [comment]
حد يترجملي
بتاريخ ١٥‏/٠٩‏/٢٠١٩ ٣:١٨ م، كتب "Ahmad Alfy" <notifications@github.com>:
