### ISSUE TITLE
PWA badge missing the checkmark

### ISSUE THREAD

**Issue by hwikyounglee** [GoogleChrome/lighthouse#9679]
**When the report is loaded, the checkmark is missing**
![image](https://user-images.githubusercontent.com/7561395/64911996-bbe56400-d6dd-11e9-9586-e546e808cf63.png)

**When scrolled, it correctly appears**
![image](https://user-images.githubusercontent.com/7561395/64912033-46c65e80-d6de-11e9-8de4-224dd44db0f4.png)

**Comment by connorjclark** [comment]
#9139 should have fixed this...

what version of the report is this? from devtools?

**Comment by hwikyounglee** [comment]
Cool beans. You're right 5.2.0 on Canary doesn't have the issue. 
It was 5.1.0  from DevTools.
