### ISSUE TITLE
Highlight multiple gauges in scores header

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9680]
We currently only highlight the "last category that starts above the middle of the window" https://github.com/GoogleChrome/lighthouse/blob/1a45e86c1cfaa8893bd49c74c44d52d4a524b681/lighthouse-core/report/html/renderer/report-ui-features.js#L599

![image](https://user-images.githubusercontent.com/4071474/64929277-24653b80-d7d9-11e9-8f95-9660bb64c4eb.png)

Instead, what if we highlight the 2 categories visible? for an example, see mozilla's docs: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/WebReplay

@hwikyounglee 	whatcha think

**Comment by AndresContreras96** [comment]
Hello is this issue still open?

**Comment by SIVASHANKAR-S** [comment]
Hi  Guys , issues still open for new contributors

**Comment by connorjclark** [comment]
:(
