### ISSUE TITLE
Expose ID of scripts in ScriptElements

### ISSUE THREAD

**Issue by umair66** [GoogleChrome/lighthouse#9681]
**Feature request summary**
Add an id key to the script objects in the ScriptElements array which is requested in the audit.

Currently available keys are `type, src, async, defer, source, devToolsNodePath, content, requestID`
Request to add the `id` key as well.

**What is the motivation or use case for changing this?**
This will make it easy to work with the specific script element of interest and a convenient way to select it.

**How is this beneficial to Lighthouse?**
Ease of use when working with `ScriptElements` while writing an audit.

**Comment by paulirish** [comment]
sure adding the `id` is fine. this is for a plugin?

you wanna write the pull request?

**Comment by umair66** [comment]
Yessir it's for a plugin. I'll write the pull request 👍
