### ISSUE TITLE
Consistently getting error when running Lighthouse audits from dev tools

### ISSUE THREAD

**Issue by pizzachip** [GoogleChrome/lighthouse#9689]
STR
1) Open google.com in Chrome Version 76.0.3809.132 (Official Build) (64-bit)
2) Open dev tools and Audit
3) See selections in image

This error has appeared on 3 different web sties 

![Screen Shot 2019-09-17 at 5 37 45 PM](https://user-images.githubusercontent.com/12566929/65084768-e64f4f80-d971-11e9-92db-5292cc68661f.jpg)

**Comment by connorjclark** [comment]
can't repro,  but this does look like just another instance of #6512. Does it happen every time or just once?
