### ISSUE TITLE
Inconsistent Performance score depending on computers performance

### ISSUE THREAD

**Issue by OZZlE** [GoogleChrome/lighthouse#9691]
I don't work with this website but it's just an example that happens on many sites I've tested.

Using incognito mode Audit without any (active in incognito mode) plugins to Chrome.

#### Provide the steps to reproduce
On MacOS High Sierra (don't think OS matters but just in case), Chrome v. (76.0.3809.132 - 64bits):
1. Close down as many apps on your computer as possible so the CPU/fan is idle.
2. Run LH "Simulated Slow 4G, 4x CPU Slowdown" on https://www.amazon.com/ take note of the score, run multiple times and take the average if it varies (and fan stays calm).
3. Open up a lot of heavy applications so the fan/CPU is like a nuclear power plant.
4. Run same LH test again.

#### What is the current behavior?
Performance score drops when computer is under heavy load.

#### What is the expected behavior?
Performance score shouldn't differ between when your computer is under heavy load or not.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: ? Chrome v. (76.0.3809.132 - 64bits)
* Node.js version: ?
* Operating System: MacOS High Sierra

**Related issues**

**Comment by brendankenny** [comment]
Hi!

> Performance score shouldn't differ between when your computer is under heavy load or not.

Unfortunately that's the nature of benchmarking. The `Simulated` throttling is able to counteract some of the contention caused by the high CPU load, but in the end Lighthouse uses measurements of a real page load as the foundation of the simulation, and if that load is distorted by other things running on the machine, the simulation results will be similarly affected.

You might find some useful information in https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md

**Comment by OZZlE** [comment]
@brendankenny Alright I see, but couldn't more be done for this?

For example: 
1. If I go to: m.youtube.com 
1. In Dev tools select "Nexus 5X" (which is the same as the Audit tool seems to use)
1. Press Audit for performance mobile 4G simulated throttling

Potential issues:
- It seems to load: https://www.youtube.com/?app=desktop instead, is it really auditing the correct version of pages?
- It seems to trigger a lot of resize events(?), from adding "the wrapping phone around the screen", after pressing the Audit button which could decrease the performance score if a site does heavy operations on resize. Of course it's not awesome for performance to do heavy operations on resize but some sites rely on this to show mobile/desktop versions. You could for example only use resize event on desktop devices and orientationchange on mobile - but since the tool seems to report desktop in User Agent string it could throw off the results especially on mobile. To me this is not a page load affecting measurement but rather a potential "Usage of the site performance measurement". Non technical stakeholders will not understand the difference unless explained.
- If I do an Audit quickly after the first our website nearly always gets a higher score..

Also, maybe I am a bit naive, but couldn't Chrome check current total CPU usage and take that into account at least for the simulated version?

**Comment by OZZlE** [comment]
Also if the results vary so much, why not just run the audit 5-10 times in a row and report the average from those test? (so I don't have to do it manually)

**Comment by OZZlE** [comment]
Tbh you could make your own websites or several that should score 100. For example maybe one that takes js parsing to the maximum allowed time for 100 score, etc. And then each test run on a device it runs against these first and then on the actual website and it could offset any variability of the device ;)
