### ISSUE TITLE
Performance test return with error

### ISSUE THREAD

**Issue by TesterNeovibe** [GoogleChrome/lighthouse#9696]
#### Provide the steps to reproduce
1. Run LH on https://gmail.tvsan.in/
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
![Screenshot from 2019-09-19 10-56-29](https://user-images.githubusercontent.com/55525462/65215770-4fe37100-dacc-11e9-8fe6-567957235b90.png)

* Node.js version:v10.15.3

* Operating System:Linux Mint 19.1 Cinnamon

**Related issues**

**Comment by exterkamp** [comment]
What version of Lighthouse is this?  Scroll to the bottom of the report and there should be a version number.

On Chrome stable I get a score w/o error:
![image](https://user-images.githubusercontent.com/6392995/65267861-c1222480-daca-11e9-8770-ae43051b9de4.png)

**Comment by TesterNeovibe** [comment]
I am using Lighthouse 3.2.0

**Comment by MarioOrtizAntoranz** [comment]
Same here. Generated by Lighthouse 5.1.0

**Comment by pranavidandu** [comment]
I have run the same with google light house 5.2.0.
I think it might be based on the throttling option selected.
This current behavior(**Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)**) is arising for me only when I select "**Applied slow 4G, 4 x CPU slowdown**".

**Comment by connorjclark** [comment]
dupe https://github.com/GoogleChrome/lighthouse/issues/7415
