### ISSUE TITLE
Lighthouse report with --extra-headers not working properly?

### ISSUE THREAD

**Issue by dileep524** [GoogleChrome/lighthouse#9697]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by dileep524** [comment]
My json file which i was passing in --extra-headers is below

{"label":"Info",
"desc":"Description",
"enabled":true,
"mandatory":true,
"icon":"circle",
"buttonText":"Configure",
"route":"Alive",
"locale":"en_US",
"nextRoute":"Run",
"animate":true,
"component":[ 
   { 
      "name":"form",
      "label":"Form",
      "validation":false,
      "validationLabel":"Enable validation"
   },
   { 
      "name":"stepper",
      "label":"Stepper",
      "vertical":false,
      "orientaionLabel":"Vertical",
      "orientaion":[ 
         { 
            "label":"Horizontal",
            "name":"horizontal"
         },
         { 
            "label":"Vertical",
            "name":"vertical"
         }
      ]
   }
]
}

I was getting the following error
Runtime error encountered: Protocol error (Network.setExtraHTTPHeaders): Invalid header value, string expected

**Comment by dileep524** [comment]
I tried having entire json in string but it doesn't work

**Comment by exterkamp** [comment]
Hi, thanks for filing!

So `--extra-headers` expects a `string: string` only, as it specifies in it's typedef:
```javascript
export interface Headers {
    [key: string]: string;
}
```
So having `"component": [...]` is invalid and throws a Protocol Error. Afaik the [devtools protocol](https://chromedevtools.github.io/devtools-protocol/tot/Network#method-setExtraHTTPHeaders) will only accept a map of `string: string`.

We might be able to make a better error message and catch this before sending this protocol message though to catch this earlier and give a better error message.
