### ISSUE TITLE
Custom Gatherer : Protocol Error Runtime.evalute object reference chain is too long

### ISSUE THREAD

**Issue by apurvaojas** [GoogleChrome/lighthouse#9698]
**Summary**
I am writing a custom gatherer and custom audit for our scenario. And I am getting an 
ERROR: 
Protocol Error (Runtime.evalute) object reference chain too long.

```
'use strict';

const { Gatherer } = require('lighthouse');


function performance() {
  return new Promise((res) => {
     let interval = setInterval(()=>{
        if(window.todosPerformance){
             clearInterval(interval)
             res(window.todosPerformance)
        }
     }, 100)
  });
}


class TodosGatherer extends Gatherer {
  beforePass(options) {
    const driver = options.driver;
    return driver.evaluateScriptOnNewDocument(`(${performance.toString()})()`)
  }

  afterPass(options) {
    const driver = options.driver;
    return driver.evaluateAsync('window.todosPerformance')
  }
}

module.exports = TodosGatherer;
```
I want to wait for metrics to be available then run my Gatherer. Is there a way to increase a timeout time for gatherer.

**Comment by paulirish** [comment]
in general that error indicates the size of the JS object that you're pulling is too unwieldy. you may want to JSON.stringify your payload just to see what's being attached? you'd see this error if `window` or `document` were connected to your object.

can you explain what data you're collecting in todosPerformance?

looking at the code:
the `beforePass` phase is done before the page is loaded.. and it should resolve fairly quickly. so i wouldn't expect to see this promise resolve so late.

**Comment by apurvaojas** [comment]
Got it Thanks. I was add reference of DOM node. 
Fixed.
