### ISSUE TITLE
How to do lighthouse testing for components that arrives after click on the page(means it will not be there on pageload)?

### ISSUE THREAD

**Issue by dileep524** [GoogleChrome/lighthouse#9699]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @dileep524!

You'll have to write a custom gatherer or make it revealed via the URL  (i.e. when you go to `http://my-site.com/my-page#reveal-the-modal-that-I-want-a11y-score-on` have it trigger whatever UI you want LH to audit).

There's additional discussion and information about this in #3837 #4403 #1418 [custom audit docs](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit)
