### ISSUE TITLE
JS, main-thred & 3rd party 'ERROR!'

### ISSUE THREAD

**Issue by Lagicrus** [GoogleChrome/lighthouse#9700]
#### Provide the steps to reproduce
1. Run LH on https://talesbazaar.com
a. Desktop, 5 audits, no throttle and Clear Storage enabled/ticked

#### What is the current behavior?
In Diagnostics I see the following image
![image](https://user-images.githubusercontent.com/24227350/65236098-c635a280-dacf-11e9-8221-76b6b3cda7a3.png)
(Ignoring the text warning, thats not "broken" like this)

#### What is the expected behavior?
To see actual data instead of "Error!"

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.2.0
Taken from `chrome://version`
Google Chrome: 77.0.3865.90 (Official Build) (64-bit) (cohort: 77_90_Win)
Revision: 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS: Windows 10 OS Version 1903 (Build 18362.295)
JavaScript: V8 7.7.299.11

**Comment by pmd-bgermain** [comment]
Seems to be a known bug and linked to #7764. I also wrote a ticket earlier : #9668 

Hope you'll find more helpful informations on these issues.

**Comment by brendankenny** [comment]
@Lagicrus what do you see when hovering over the `Error!` text?

**Comment by Lagicrus** [comment]
> @Lagicrus what do you see when hovering over the `Error!` text?

![image](https://user-images.githubusercontent.com/24227350/65292819-cd50c500-db50-11e9-97e1-870d05fd1673.png)
![image](https://user-images.githubusercontent.com/24227350/65292825-d3df3c80-db50-11e9-82c7-ef52ab07596a.png)
![image](https://user-images.githubusercontent.com/24227350/65292832-da6db400-db50-11e9-923f-935a0b1b75f7.png)

**Comment by brendankenny** [comment]
Ah, thanks, then yes, @pmd-bgermain is correct and #7764 is the issue to look at.

**Comment by Lagicrus** [comment]
> Ah, thanks, then yes, @pmd-bgermain is correct and #7764 is the issue to look at.

Thanks
