### ISSUE TITLE
Project list using lighthouse: lightmon

### ISSUE THREAD

**Issue by LarsKumbier** [GoogleChrome/lighthouse#9701]
Hi there,
we've been working with one of our clients on continuous monitoring of their web performance and build a tool for that called *Lighthouse Monitor* (or lightmon for short). It features
* running lighthouse against a set of URLs with a set of presets (e.g. desktop, smartphone on fast connection, smartphone on slow connection),
* distributing the results to different places (e.g. prometheus feeding graphana or chatbots),
* saving the complete reports (including all traces),
* a webpage to compare any two saved reports with each other side-by-side, and
* automatic cleanup of saved data (e.g. to reduce the number of reports from hourly to daily or from daily to weekly after a specific timespan)

Lightmon can perform evaluations in parallel by sharding the data across different worker nodes (instead of the internal parallel option, which we found often skews the results) and therefore and has been running at Verivox for about a year now.

**Comment by paulirish** [comment]
That sounds pretty incredible. 

Ah this is it, yes? https://github.com/Verivox/lighthouse-monitor

**Comment by LarsKumbier** [comment]
...I knew I forgot some important point. :joy: 
yes, that one. Would you add it to the mainpage? I'd like to get some momentum going with it, think it helps companies with bringing web performance more in focus.

**Comment by connorjclark** [comment]
neat. feel free to open a PR adding your project to the readme
