### ISSUE TITLE
new audit: autofill

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9704]
For inspiration, see: https://cloudfour.com/thinks/an-html-attribute-potentially-worth-4-4m-to-chipotle/

Forms can either be a zero-friction experience or the bane of all web users. Proper HTML semantics are necessary for autofill to work correctly.

I don't have much knowledge of autofill atm, so I am holding off on the typical "new audit proposal" format until I do some research.

**Comment by paulirish** [comment]
I _think_ #1639 generally covers this topic, though it doesn't mention using maxlength when appropriate, which seems to be a big takeaway from the article.

see also grigsby's earlier amazing article on the topic: https://cloudfour.com/thinks/autofill-what-web-devs-should-know-but-dont/

**Comment by brendankenny** [comment]
> I _think_ #1639 generally covers this topic

#1639 does seem to match the ["Lessons for your web forms"](https://cloudfour.com/thinks/an-html-attribute-potentially-worth-4-4m-to-chipotle/#lessons-for-your-web-forms section)

> though it doesn't mention using maxlength when appropriate, which seems to be a big takeaway from the article.

I don't know how we're going to wade into that, though. Guessing if a field is a year and if it should be two or four digits...

**Comment by brendankenny** [comment]
closing in favor of #1639
