### ISSUE TITLE
Is it possible to produce a complete lighthouse report for a page if any component on that page is called on api call?

### ISSUE THREAD

**Issue by dileep524** [GoogleChrome/lighthouse#9707]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by dileep524** [comment]
lighthouse usually refreshes the page where the components which will be called on api call are not loaded. So is there any solution to produce a complete report so that it covers the component which is called on api call as well.

**Comment by connorjclark** [comment]
Sounds like you want to have Lighthouse audit a page that has undergone some user interaction. You'll find these docs useful:

https://github.com/GoogleChrome/lighthouse/blob/master/docs/puppeteer.md
https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/auth
