### ISSUE TITLE
CLI Error Reporting Prompt Appears After Multiple Runs but not on First Run

### ISSUE THREAD

**Issue by jcpsimmons** [GoogleChrome/lighthouse#9709]
#### Provide the steps to reproduce
1. Run LH via os library in Python 3.6

#### What is the current behavior?
Lighthouse CLI issues the following prompt:

```
We're constantly trying to improve Lighthouse and its  Learn more: https://github.com/GoogleChrome/lighthouse/blob/master/docs/error-reporting.md 
```

#### What is the expected behavior?
I'm using this in an automation setup - I think it's not good practice to put prompts like this in the CLI during script run - or at least have it show up on first-run instead of later run, as this risks messing up automation pipelines. This is about the 20th time I've used the tool and the prompt hasn't appeared until today.

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System: Ubuntu 18:10

**Related issues**

**Comment by brendankenny** [comment]
hmm, nothing has changed here for a long time. It should only run the first time, saving the result. At worst in an automated run it will timeout after 20 seconds and default to false. At best you can set `--enable-error-reporting`/`--enable-error-reporting=false` ([depending on if you want to report errors](https://github.com/GoogleChrome/lighthouse/blob/master/docs/error-reporting.md)) and not be prompted at all.

Is it possible files were cleared in the setup you're running? Internally the prompt uses https://github.com/yeoman/configstore to store the preference under `$XDG_CONFIG_HOME` or `~/.config`

**Comment by jcpsimmons** [comment]
@brendankenny I will set up the command to run with a flag just to be safe. I don't think I modified anything in ~/.config, but maybe another script did for some reason. 

Thanks for your help!
