### ISSUE TITLE
Create and ship source map for better extension stack traces

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#972]
With the new "report error" link in the extension, we've already started getting quite a few more [bugs reported](https://github.com/GoogleChrome/lighthouse/issues/969). It would be great if we could do better on the stack traces, though, and have the specific file instead of the browserified `lighthouse-background.js:5535:17` or whatever.

We may want to intentionally cut out library code if the size is too big, especially the traceviewer/devtools deps, or the devtools version can simply not ship the source map, as size in the extension is somewhat less of a concern.

**Comment by wardpeet** [comment]
Was looking into some sourcemap plugins but none of them seem to work correctly. Will create a pr with source-map itself. Or if anyone has a good node module that actually works with browserify sourcemaps.

**Comment by Janpot** [comment]
@wardpeet Not 100% sure if this applies and whether you tested it yet but recently came across https://github.com/stacktracejs/stacktrace.js

**Comment by brendankenny** [comment]
closing as infeasible (for now). See #995 for details.
