### ISSUE TITLE
'Aw, snap' in lighthouse performance audit

### ISSUE THREAD

**Issue by nl-igor** [GoogleChrome/lighthouse#9720]
#### Provide the steps to reproduce
1. Run LH on https://nl-tower-web-staging.herokuapp.com/compare
  

#### What is the current behavior?
I'm unable to check performance score of the site due to 'Aw, snap' page appears after some time. 
Checked cli - same result. 
Audit fails in incognito with all extensions disabled, both on Mac (chrome 75), Windows (chrome 74) and Linux (chrome 76, 77)
PageSpeedInsights shows next error: Lighthouse returned error: generic::internal: APP::1: Abnormal renderer termination, status = crashed exit_code = 1
Windows chrome showed this error: 
![image](https://user-images.githubusercontent.com/54166344/65448824-582c0b00-de42-11e9-8f45-021e9e1c6e51.png)

#### What is the expected behavior?
Both page speed insights and lighthouse gives performance score without any errors and 'aw, snap' pages

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.2.0
* Operating System: Linux 18.04.3

**Related issues**

**Comment by connorjclark** [comment]
oh boy this is no good.

happens for performance panel reload too.

internal crash report: https://crash.corp.google.com/browse?stbtiq=f7560e973f103257

![image](https://user-images.githubusercontent.com/4071474/65450132-51c17300-ddf1-11e9-98e6-59f1e99b295f.png)

**Comment by connorjclark** [comment]
So, this is a Blink issue, and we (Lighthouse) won't be able to do anything. But this ticket will get into the right hands. Thanks for the report! b/1006872

**Comment by nl-igor** [comment]
Hi @connorjclark !
Thank you for quick reaction. Lighthouse is amazing tool for web development and I would like to thank the whole team for it!
