### ISSUE TITLE
Failed to load resource: net::ERR_ACCESS_DENIED on CSS

### ISSUE THREAD

**Issue by TDurrr1** [GoogleChrome/lighthouse#9739]
(I commented on [Lighthouse issue #9038](https://github.com/GoogleChrome/lighthouse/issues/9038) with this issue as well, but it had already been closed. I believe this is the first time I’ve ever reported an issue with anything on Github, so if this isn’t the way it’s done, let me know and I’d be happy to fix it.)

### Description
On web.dev/measure, using https://monicajean.photography as the URL, I receive a 92 instead of a 100 for best practices because of the following two browser errors which “were logged to the console”:

URL | Description
-- | --
[/stylesheets/main.css](https://monicajean.photography/stylesheets/main.css) (monicajean.photography) | `Failed to load resource: net::ERR_ACCESS_DENIED`
[/stylesheets/print.css](https://monicajean.photography/stylesheets/print.css) (monicajean.photography) | `Failed to load resource: net::ERR_ACCESS_DENIED`

When I run Chrome’s built-in Lighthouse tests, I do not receive these errors, nor do I have any issues while navigating to [the site itself](https://monicajean.photography), nor clicking straight through to the stylesheets. I wouldn’t expect to see them here either.

### To Reproduce

1. On web.dev/measure, enter https://monicajean.photography for the URL and click Run Audit.
2. In the results, the best practices score is 92. An error labeled “Browser errors were logged to the console” is listed.

### Expected Behavior

1. On web.dev/measure, enter https://monicajean.photography for the URL and click Run Audit.
2. In the results, the best practices score is 100. No console errors were logged, so this issue is not listed.

**Comment by connorjclark** [comment]
web.dev uses Lightrider, which runs on internal Google services. Is is possible that your site employs some "bot detection", and is blocking these requests?

**Comment by TDurrr1** [comment]
Would my robots.txt be the culprit then? Otherwise, I’m pretty sure I don’t
have anything like that.

**Comment by connorjclark** [comment]
No, that wouldn't affect anything.

I tried running against `https://monicajean.photography/stylesheets/main.css` too, and that worked, which was surprising.

**Comment by TDurrr1** [comment]
Interesting update: I was trying out adding a `Cache-Control: public, max-age=600` header to every request, and now my best practices score is 100. It’s still 92 with `private`.

**Comment by TDurrr1** [comment]
Never mind, I guess—it worked a few times, but now I’m back down to 92. What does appear to work, however, is adding a cachebuster to the URL in conjunction with the `Cache-Control` header.

**Comment by naveedahmed1** [comment]
I am also having same issue when testing my website https://www.mustakbil.com on web.dev

**Comment by JustPlainHigh** [comment]
Experiencing the same issue on https://apps.rodel.co.za. When I visit the site, there are no errors.

<table class="lh-table lh-details"><thead><tr><th class="lh-table-column--url"><div class="lh-text">URL</div></th><th class="lh-table-column--code"><div class="lh-text">Description</div></th></tr></thead><tbody><tr><td class="lh-table-column--url"><div class="lh-text__url" title="https://apps.rodel.co.za/ui/js/validator.js" data-url="https://apps.rodel.co.za/ui/js/validator.js"><a rel="noopener" target="_blank" href="https://apps.rodel.co.za/ui/js/validator.js">…js/validator.js</a><div class="lh-text lh-text__url-host">(apps.rodel.co.za)</div></div></td><td class="lh-table-column--code"><pre class="lh-code">Failed to load resource: net::ERR_ACCESS_DENIED</pre></td></tr><tr><td class="lh-table-column--url"><div class="lh-text__url" title="https://apps.rodel.co.za/ui/css/flatly/template.css?v=9" data-url="https://apps.rodel.co.za/ui/css/flatly/template.css?v=9"><a rel="noopener" target="_blank" href="https://apps.rodel.co.za/ui/css/flatly/template.css?v=9">…flatly/template.css?v=9</a><div class="lh-text lh-text__url-host">(apps.rodel.co.za)</div></div></td><td class="lh-table-column--code"><pre class="lh-code">Failed to load resource: net::ERR_ACCESS_DENIED</pre></td></tr><tr><td class="lh-table-column--url"><div class="lh-text__url" title="https://apps.rodel.co.za/ui/css/font-awesome.css" data-url="https://apps.rodel.co.za/ui/css/font-awesome.css"><a rel="noopener" target="_blank" href="https://apps.rodel.co.za/ui/css/font-awesome.css">…css/font-awesome.css</a><div class="lh-text lh-text__url-host">(apps.rodel.co.za)</div></div></td><td class="lh-table-column--code"><pre class="lh-code">Failed to load resource: net::ERR_ACCESS_DENIED</pre></td></tr><tr><td class="lh-table-column--url"><div class="lh-text__url" title="https://apps.rodel.co.za/ui/css/bootstrap-select.css" data-url="https://apps.rodel.co.za/ui/css/bootstrap-select.css"><a rel="noopener" target="_blank" href="https://apps.rodel.co.za/ui/css/bootstrap-select.css">…css/bootstrap-select.css</a><div class="lh-text lh-text__url-host">(apps.rodel.co.za)</div></div></td><td class="lh-table-column--code"><pre class="lh-code">Failed to load resource: net::ERR_ACCESS_DENIED</pre></td></tr><tr><td class="lh-table-column--url"><div class="lh-text__url" title="https://apps.rodel.co.za/ui/css/component.css" data-url="https://apps.rodel.co.za/ui/css/component.css"><a rel="noopener" target="_blank" href="https://apps.rodel.co.za/ui/css/component.css">…css/component.css</a><div class="lh-text lh-text__url-host">(apps.rodel.co.za)</div></div></td><td class="lh-table-column--code"><pre class="lh-code">Failed to load resource: net::ERR_ACCESS_DENIED</pre></td></tr><tr><td class="lh-table-column--url"><div class="lh-text__url" title="https://apps.rodel.co.za/ui/js/jquery.js" data-url="https://apps.rodel.co.za/ui/js/jquery.js"><a rel="noopener" target="_blank" href="https://apps.rodel.co.za/ui/js/jquery.js">…js/jquery.js</a><div class="lh-text lh-text__url-host">(apps.rodel.co.za)</div></div></td><td class="lh-table-column--code"><pre class="lh-code">TypeError: $(...).validator is not a function
    at HTMLDocument.&lt;anonymous&gt; (https://apps.rodel.co.za/ui/js/main_form_validation.js?v=9:26:15)
    at j (https://apps.rodel.co.za/ui/js/jquery.js:2:29999)
    at k (https://apps.rodel.co.za/ui/js/jquery.js:2:30313)</pre></td></tr></tbody></table>

**Comment by exterkamp** [comment]
This is resolved now :tada: 

Read the summary post mortem in https://github.com/GoogleChrome/lighthouse/issues/9902#issuecomment-556414195
