### ISSUE TITLE
Dependencies between browser generated and cl generated scores

### ISSUE THREAD

**Issue by PatchOnKnee** [GoogleChrome/lighthouse#9740]
#### Provide the steps to reproduce
```
const chromeLauncher = require('chrome-launcher')
const lighthouse = require('lighthouse/lighthouse-core')
const ReportGenerator = require('lighthouse/lighthouse-core/report/report-generator')

const run = async (url, options) => {
    const chrome = await chromeLauncher.launch({ chromeFlags: options.chromeFlags });
    options.port = chrome.port;
    try {
        const results = await lighthouse(url, options);
        const jsonReport = ReportGenerator.generateReport(results.lhr, 'json');
        const report = JSON.parse(jsonReport)
        const metrics = [
            report.categories.accessibility.score,
            // report.categories.performance.score,
            report.categories.seo.score,
            report.categories.pwa.score,
            report.categories['best-practices'].score
        ]
        console.log('report for', url)
        console.log('accissibility', report.categories.accessibility.score)
        console.log('performance', report.categories.performance.score)
        console.log('seo', report.categories.seo.score)
        console.log('pwa', report.categories.pwa.score)
        console.log('best practices', report.categories['best-practices'].score)
    } catch (error) {
        throw new Error(error);
    } finally {
        await chrome.kill();
    }
}


const options = {
    chromeFlags: ['--headless'],
    // logLevel: 'info',
    // onlyCategories: ['accessibility'],
}


const urls = ['http://url1.com', 'http://url2.com']

async function main() {
    for (const url of urls) {
        await run(url, options)
    }
}


main()
```  
#### What is the current behavior?

Running Lighthouse through node causes discrepancies between scores and running in a normal browser. Similarly performance score is always 0. 

#### What is the expected behavior?

Matching the output generated in a browser. As well as being able to generate a performance score.

#### Additional
This is basically a script that will be run in a pipeline to test a series of pages for a bunch of different metrics. Is there a more efficient way to do this?

**Comment by patrickhulce** [comment]
Thanks for filing!

> through node causes discrepancies between scores and running in a normal browser. Similarly performance score is always 0.

You're going to have to be more specific here @PatchOnKnee. We run thousands of reports through node everyday with valid performance scores and reports :) Can you fill out the rest of the bug template? What is your specific environment? What URLs are you testing? etc.

**Comment by PatchOnKnee** [comment]
Hey mate thanks for the reply!

I've worked out the performance issue, and I've moved over to a different solution utilising lighthouse-batch. I'm still getting altering scores. The urls are a local development server and I unfortunately can't make the repo public. When testing in browser I'm using: Opera - Version:63.0.3368.94. I'm guessing we can go ahead and close this issue. For future reference what would be valuable to include next time?

**Comment by patrickhulce** [comment]
Glad you got it sorted out!

For the future, the questions in the bug report template are good background info to provide.

* Affected URL
* Lighthouse version
* Node.js version
* Chrome version
* Operating System

As for altering scores, you might want to give https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md a readthrough if you haven't already.
