### ISSUE TITLE
Can Lighthouse Plugins specify URL query parameters

### ISSUE THREAD

**Issue by t-kelly** [GoogleChrome/lighthouse#9754]
**Summary**
Want to expose additional HTML page attribution needed for Lighthouse plugin audits. Thought a query parameter would be the easiest way of triggering this. Can a Lighthouse Plugin:

a) Execute on an independent page load instance so these additional attribution doesn't impact other audits (e.g don't want additional HTML bytes to impact performance audits)?
b) Modify the input URL as needed (e.g. add query parameters)?

**Comment by connorjclark** [comment]
You could define a new pass in your config, and have a gatherer run some JS to redirect the page. doing that in `driver.evaluateScriptOnNewDocument` on the beforePass should cause the page to load with your special query params before the browser spends much effort loading the page.

or, you could forget the extra pass, and just have your gatherer call `fetch` in page w/ the special query param.

**Comment by patrickhulce** [comment]
@connorjclark I think @t-kelly was hoping to do this in a plugin though, so the short answer is we do not plan on enabling plugins to do this outside of the `fetch` method Connor mentioned. A custom config would be required to add a new pass and a gatherer that modifies the pass url, which is just a simple `beforePass` that modifies the `passContext.url` to whatever you'd like (see https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/http-redirect.js#L26 for an example)

**Comment by t-kelly** [comment]
> I think @t-kelly was hoping to do this in a plugin though, so the short answer is we do not plan on enabling plugins to do this outside of the fetch method Connor mentioned.

This is true. And trying to stay away from custom configs so that using the plugin is as easy as specifying it/enabling it.

> or, you could forget the extra pass, and just have your gatherer call fetch in page w/ the special query param.

I like this because it's simple and should work. The audits don't need to observe browser behaviour with this additional page attribution, just access specific page content which is totally achievable with an extra request.

Thanks all!
