### ISSUE TITLE
LightHouse tells me to preload a font that is already preloaded...

### ISSUE THREAD

**Issue by resistdesign** [GoogleChrome/lighthouse#9755]
#### Provide the steps to reproduce
1. Run LH on https://dolls.lol
  

#### What is the current behavior?

It suggests that I preload `https://dolls.lol/Assets/Fonts/pacifico-regular.woff2?2acf061c1b1d8f699521` even though I already am: `<link rel="preload" href="/Assets/Fonts/pacifico-regular.woff2?2acf061c1b1d8f699521" as="font">`

#### What is the expected behavior?

It shouldn't tell me to preload a font that is already preloaded.

#### Environment Information
* Affected Channels: DevTools (???)
* Lighthouse version: 5.2.0
* Node.js version: N/A
* Operating System: Mac OS 10.14.6

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @resistdesign!

That page preloads a version that has a query string, but the page later requests the font without the query string, so the preloaded version is not used and the request is reissued. 

Lighthouse is telling you to preload the URL without the query string.

**Comment by resistdesign** [comment]
@patrickhulce Ah, you know what, I had tried it with the hash on both but just found out now that it was a different hash in each request!

Sorry about this!
