### ISSUE TITLE
Add a html-only gatherer

### ISSUE THREAD

**Issue by benschwarz** [GoogleChrome/lighthouse#9756]
**Feature request summary**

At the moment custom plugins aren't able to create their own gatherers, and there isn't a gatherer to retrieve the final HTML that a page produced. 

Ref: ampproject/amp-toolbox#509

My proposal is to add a gatherer that returns `document.documentElement.outerHTML`, or something like it. 

**What is the motivation or use case for changing this?**

Plugins are unable to retrieve the document HTML from the browser. 

**How is this beneficial to Lighthouse?**

Ergonomic plugin authoring

**Comment by brendankenny** [comment]
I think the amp validator would need the initial html, wouldn't it? So this could be calling `driver.getRequestContent` with the main resource request.

A side benefit is that most of the time the html request would be of pretty reasonable size (at least compared to many ScriptElements), a lot better than the easily monstrous (css in js, etc etc) outerHTML.

**Comment by benschwarz** [comment]
> So this could be calling driver.getRequestContent with the main resource request.

Yah. That'd also account for redirections etc etc 👍 

> I think the amp validator would need the initial html, wouldn't it? 

I'm not really qualified to say whether amp would want the initial HTML or the fully realised result, but I'm sure @alabiaga or @cramforce could add some guidance here

**Comment by ithinkihaveacat** [comment]
The AMP validator wants the equivalent of Chrome's "view page source." So `driver.getRequestContent` would be the right thing in this case?

**Comment by patrickhulce** [comment]
Ah yeah the initial HTML document is a much easier ask than the final rendered HTML content :)

This sounds doable as a default gatherer IMO!

**Comment by brendankenny** [comment]
The AMP plugin can now use `artifacts.MainDocumentContent` on master/next release
