### ISSUE TITLE
Required LinkElements "Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by bemyhre** [GoogleChrome/lighthouse#9764]
#### Provide the steps to reproduce
1. Run LH on https://sundaysuppermovement.com/
  

#### What is the current behavior?
It has a Preconnect to Required Origins error that throws a specific "Required LinkElements gatherer encountered an error: Cannot read property 'toLowerCase' of undefined" item.

#### What is the expected behavior?

That not to show up.

#### Environment Information
* Affected Channels:  GPSI page and Chrome Dev tools
* Lighthouse version:
* Node.js version:
* Operating System: Mac

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @bemyhre I'm able to reproduce this 👍

**Comment by brendankenny** [comment]
ah, in the `evaluateAsync()`, but it's easily reproducible on the page itself with just a querySelectorAll. Looks like the root issue is `problemLink.constructor.name === 'SVGElement`, so our assumptions about the properties don't hold true in that case.

What to do about getAttribute not necessarily reflecting properties and whether svg link preloads and whatnot work the same way are a whole research project, though :/

**Comment by patrickhulce** [comment]
> What to do about getAttribute not necessarily reflecting properties and whether svg link preloads and whatnot work the same way are a whole research project, though :/

I think the solution here is much simpler and already started, just check if we've actually got a LinkElement :)
