### ISSUE TITLE
New related project - Gradle Lighthouse Plugin

### ISSUE THREAD

**Issue by pun-ky** [GoogleChrome/lighthouse#9769]
fyi https://github.com/Cognifide/gradle-lighthouse-plugin
it would be nice if this tool will be also listed in "Related projects" section. 

greetings, Krystian

**Comment by patrickhulce** [comment]
Interested in working on a PR that does this @pun-ky? :)

**Comment by pun-ky** [comment]
Sure

**Comment by dpacassi** [comment]
As there wasn't any further activity, I created a PR for this, check #9789
