### ISSUE TITLE
Can't print report

### ISSUE THREAD

**Issue by aprystai-vesta** [GoogleChrome/lighthouse#9773]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
You'll have to be more specific @aprystai-vesta. Can you fill out the questions of the bug template you left blank in this issue?
