### ISSUE TITLE
DBW: site uses responsive images

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#978]
## Tracked Features
- [X] ~Detect`img` elements that use assets that are too large for their displayed size (#1497)~
- [ ] Detect images used in CSS that are too large for their displayed size

## ORIGINAL
It would be nice to have an audit for testing if a site sends responsive images. We could test for different common viewports and DPR and see if the images served by the page vary in size.

Suggest techniques like `<img srcset>`, css `image-set()`, and `<picture>`.

Perhaps it could share a gatherer with https://github.com/GoogleChrome/lighthouse/issues/718

**Comment by wardpeet** [comment]
which viewports & dpr are you referring to?

viewport: mobile, ipad, desktop?
dpr: 1, 2, 3 ?

**Comment by patrickhulce** [comment]
Also potentially sharing overlap with #876? Perhaps that just becomes a proposed solution to a failed responsive image audit

**Comment by ebidel** [comment]
@wardpeet yea, I was thinking reasonable defaults for each of those.  I think we'd have use device emulation for the DPR. Checking dpr 1 vs. 2 would be good for starters. 

@patrickhulce  There's probably overlap. Possibly a shared gatherer for the image stuff. 

I filed separate bugs b/c #876 is also closely related to https://github.com/GoogleChrome/lighthouse/issues/718. They could be the start to a set of audits for initial page load perf. NBU, reduce bytes transferred, awesome.

**Comment by patrickhulce** [comment]
k i'll get started on some of these

**Comment by ebidel** [comment]
Cool. I'll take https://github.com/GoogleChrome/lighthouse/issues/718 from the "save bandwidth" side
