### ISSUE TITLE
Port performance measurements to a JS library for the browser

### ISSUE THREAD

**Issue by Malkiz** [GoogleChrome/lighthouse#9780]
I'm very new to Lighthouse so I hope this makes sense to ask this here.

I'm working on a project that's meant to be used as a 3rd-party library on websites that I don't own. I want to use the high-level user-oriented performance measurements you defined in Lighthouse, such as "time to interactive", but I want to record it on real end-users of my library in "production" environments.

However, I've been reading your code and it seems that most measurements need to use data that isn't available to JS running inside the browser.

1. Is my analysis correct?
2. Can we rewrite the code / redefine these measurements, in a way that will use only data that is accessible from JS in the browser to allow what I want?

If you think this is possible I would be interested to discuss further details.
For example: How can we code the "time to interactive" as defined [here](https://docs.google.com/document/d/1GGiI9-7KeY3TPqS3YT271upUVimo-XiL5mwWorDUD4c/edit#) from JS in the browser? We need a way to access the timing info for all JS tasks that are running on the main thread. Is that possible? If not - is there a reasonable alternative?

My end goal is to be able to measure these things in real-life on real end-users, and send meaningful measurements back to my server for monitoring and analysis.

**Comment by connorjclark** [comment]
yup, there's a polyfil for this. see: https://developers.google.com/web/fundamentals/performance/user-centric-performance-metrics

**Comment by Malkiz** [comment]
@connorjclark Amazing, thanks! That's exactly what I was looking for :)
