### ISSUE TITLE
Site has viewport meta tag. Results differ

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#98]
Small bug noticed when demoing lighthouse: The extension and CLI report different numbers for this item. Likely a problem in the gatherers.

![image](https://cloud.githubusercontent.com/assets/39191/14116143/2ab9fb8c-f593-11e5-8b22-fd93b1cc14a1.png)

**Comment by brendankenny** [comment]
This now works for me, so not sure if this has just been fixed since then

<img width="907" alt="screen shot 2016-03-31 at 16 33 36" src="https://cloud.githubusercontent.com/assets/316891/14193990/af9c33f2-f75e-11e5-8f58-d25301c01492.png">

**Comment by paulirish** [comment]
Thx will see if I can repro

**Comment by paulirish** [comment]
seems good.
