### ISSUE TITLE
Plugin vs ChromeDevTool Performance difference

### ISSUE THREAD

**Issue by McSparta** [GoogleChrome/lighthouse#9805]
I noticed that when I run the plugin version of Lighthouse, I get a significantly lower score than when I run the DevTool version of lighthouse. I am wondering what the difference is between the two and which one is more reliable?

**Comment by patrickhulce** [comment]
Thanks for filing @McSparta! Could you explain what you mean by "plugin version of Lighthouse"? 

Lighthouse has 4 primary channels: DevTools, Extension, CLI, PageSpeed Insights

There are lots of settings that can be set inconsistently across them too, so a URL and the specific settings used are really necessary to answer.

**Comment by McSparta** [comment]
My apologies, I mean the extension version. I tried them both just at standard settings with no throttling on desktop and got different results. There definitely could be more settings that I am missing though, I am pretty new to using this tool.

**Comment by patrickhulce** [comment]
> with no throttling on desktop 

It's not possible to run the extension without *any* throttling, so this would explain the difference. Extension with "Simulated throttling" unchecked should be equivalent to "Applied throttling" option in DevTools.

**Comment by McSparta** [comment]
You are right I get the same score when I use the "Applied throttling" option. Thank you for clarifying that.
