### ISSUE TITLE
Orphan time label in Opportunities 

### ISSUE THREAD

**Issue by yuinchien** [GoogleChrome/lighthouse#9811]
<img width="977" alt="Screen Shot 2019-10-09 at 8 02 07 PM" src="https://user-images.githubusercontent.com/406636/66516347-ac1b2e80-ea95-11e9-98be-cd9c19111e91.png">

Can we keep the time label in one line instead of wrapping to the next line? Thanks!

**Comment by connorjclark** [comment]
dupe #9078
