### ISSUE TITLE
Pagespeed display font swap not considered

### ISSUE THREAD

**Issue by Ibrahim-cs** [GoogleChrome/lighthouse#9813]
#### Provide the steps to reproduce
1. Run LH on https://www.gilaridgedental.com/
  

https://fonts.googleapis.com/css?family=Fjalla+One&display=swap

#### What is the current behavior?
As I am using display "swap" on font link provided by google, but still it is showing me to fix it: 
Here is the URL to reproduce it: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.gilaridgedental.com%2F
https://fonts.googleapis.com/css?family=Fjalla+One&display=swap 
#### What is the expected behavior?
Ideally it should not come in opportunities section as I am using display swap properties in font link

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by Ibrahim-cs** [comment]
@patrickhulce ,
Run this URL https://www.gilaridgedental.com/

![gilaridge](https://user-images.githubusercontent.com/21018313/67176863-807b3b00-f3e9-11e9-9885-86e56f8087b1.PNG)

**Comment by Ibrahim-cs** [comment]
@patrickhulce , this font url https://fonts.googleapis.com/css?family=Fjalla+One&display=swap is still not considered for page speed. I am using latest dispaly=swap properties

**Comment by patrickhulce** [comment]
That audit is not telling you to use `display: swap` for the font (you're already doing that and the other audit related to this is already passing); this audit is telling you to make the CSS stylesheet not render-blocking. 

[Example article](https://www.filamentgroup.com/lab/async-css.html) discussing one of the strategies for this.
