### ISSUE TITLE
Runtime Error Design Update

### ISSUE THREAD

**Issue by yuinchien** [GoogleChrome/lighthouse#9820]
<img width="1280" alt="75" src="https://user-images.githubusercontent.com/406636/66617100-77d46a80-eb88-11e9-98b8-0a4700ea7573.png">
<img width="1280" alt="76" src="https://user-images.githubusercontent.com/406636/66617101-77d46a80-eb88-11e9-86a8-12670d14800b.png">

**Comment by exterkamp** [comment]
Note for when we fix this: Fix the i18n of `Error` for the metrics, and maybe pull the same string?
![image](https://user-images.githubusercontent.com/6392995/66617616-b4a16100-eb8a-11e9-9154-60c8a1460af9.png)

**Comment by paulirish** [comment]
thicc bang

**Comment by yuinchien** [comment]
<img width="1280" alt="76" src="https://user-images.githubusercontent.com/406636/66769158-45b55800-ee69-11e9-9cdd-bedfa50c5f40.png">

Here is a zip for the error icons in svg: [ic_errors.zip](https://github.com/GoogleChrome/lighthouse/files/3725544/ic_errors.zip)

**Comment by rahulpatel596** [comment]
@yuinchien I'd like to work on this issue. Just to confirm, its simply to update all current error icons with new design in lighthouse performance report, Right?

**Comment by patrickhulce** [comment]
Thanks @rahulpatel596! Basically.

We want to replace the red triangle with the new red exclamation icon for all audits that *error*. 

Sidenote for Lighthouse team, what do you think about changing the text from "Error" to "Exception Thrown"? I feel like that might clear up most of the confusion around whether this is their failure or ours.

**Comment by rahulpatel596** [comment]
Hey @patrickhulce 
I am working on this and I just wanted to confirm that I am making changes in correct place because current production version has a quite different UI. 
<img width="1439" alt="Screen Shot 2020-11-07 at 9 26 12 PM" src="https://user-images.githubusercontent.com/33618437/98456215-7afda980-2140-11eb-8a2e-a228a3d69a32.png">

**Comment by patrickhulce** [comment]
We *don't* want to replace the legend one, other than that yes those 3 places would have the exclamation instead of the question mark/triangle *and* the regular audits below this as well. Keep in mind that this exclamation design should only apply when there has been an error and the score is `null`.

**Comment by rahulpatel596** [comment]
Has anyone come across this issue where it shows svg in dev tools but not on website.
<img width="1440" alt="Screen Shot 2020-11-11 at 2 12 36 PM" src="https://user-images.githubusercontent.com/33618437/98859794-55b2b900-2428-11eb-8375-771c9e94d211.png">

**Comment by rahulpatel596** [comment]
Hey @patrickhulce Is there a specific method or way to follow which can generate report with an error and/or with null score?

**Comment by patrickhulce** [comment]
Yes @rahulpatel596, every PR has a [sample error report deployed](https://lighthouse-638sz3brb.vercel.app/error/) and you can replicate it on your local machine with `yarn now-build`

**Comment by patrickhulce** [comment]
Some good progress was made in https://github.com/GoogleChrome/lighthouse/pull/11670 but this is available again if anyone would like to pick it up.

**Comment by tannerdolby** [comment]
I'm happy to work on this, but it seems there is already a PR (https://github.com/GoogleChrome/lighthouse/pull/9272) that addresses the error icons.

**Comment by adamraine** [comment]
@tannerdolby that PR is very old, you are welcome to submit your own :)

**Comment by tannerdolby** [comment]
@adamraine sounds good, I will start working on this and submit a PR soon :)
