### ISSUE TITLE
Lighthouse not calculating the result for some pages

### ISSUE THREAD

**Issue by prateek552** [GoogleChrome/lighthouse#9825]
There are some pages for which we are not able to get the lighthouse score. This happens randomly , sometimes we don't.
One of those pages is https://www.lynxexpression.com/home.html.
On 9th October we didn't get any score (PFA for screenshot). For the same page we got the score on 10 Oct . Here is the result url - http://34.193.48.242/result/191009_DT_200/

![result](https://user-images.githubusercontent.com/22009661/66646255-48ceff00-ec43-11e9-9b1a-d4d8081a54a2.png)

**Comment by patrickhulce** [comment]
On the public instance of WPT, the Lighthouse log is kept so you can debug it when it fails (link is right next to "View Test Log" on webpagetest.org). Is that something you could enable for this private instance?

**Comment by prateek552** [comment]
Hi @patrickhulce , Here are the logs for the concerned Date i.e 9th Oct.
[4K4.zip](https://github.com/GoogleChrome/lighthouse/files/3724418/4K4.zip)

**Comment by patrickhulce** [comment]
Thanks @prateek552 but those appear to be the WPT log artifacts for the WPT runs, not the lighthouse logs.

The lighthouse log is named `lighthouse.log.gz` and looks like this https://www.webpagetest.org/viewlog.php?test=191014_60_d820dce8693344070082258b7da72789&lighthouse=1

**Comment by prateek552** [comment]
Hi @patrickhulce , For some reason the lighthouse logs are not created whenever we got this error . These are the only logs that we got for that date.

**Comment by prateek552** [comment]
We have double checked it and whenever we got this error the light house logs are not created. Is there any other naming convention or any other place where the logs can be created on getting this error ?

**Comment by patrickhulce** [comment]
That sounds like Lighthouse is never even being run then. This a WPT setup issue which is really outside the scope of this repo here. Sorry we can't be of more help! 

If you end up getting Lighthouse setup on your private WPT instance and run into a error that *Lighthouse* produces feel free to chime back in here to reopen :)
