### ISSUE TITLE
Lighthouse not detecting gzip or brotli compression

### ISSUE THREAD

**Issue by sainikbiswas** [GoogleChrome/lighthouse#9826]
**Summary**

Hi, I recently setup a website journalof.tech. I am using BunnyCDN which has Brotli enabled on their CDN. When I check the resources served by the CDN, all resources are returning the compressed version but the Lighthouse report is not detecting the text compression. I have checked brotli and gzip compression on the resources and both are reporting the correct compression in other tools. Can you please take a look?

[Lighhouse-journalof.tech.zip](https://github.com/GoogleChrome/lighthouse/files/3717207/Lighhouse-journalof.tech.zip)

**Comment by connorjclark** [comment]
Can you provide a URL? I am hesitant to download a zip file.

**Comment by sainikbiswas** [comment]
No Problem, here you go 

[Website Link](https://journalof.tech)
[Lighthouse Report Link](https://codepen.io/sainikbiswas/pen/JjjGoZG)

**Comment by patrickhulce** [comment]
Thanks for the extra info @sainikbiswas! That's strange I'm not able to reproduce that result in CLI or DevTools. Are there are any steps you take when running Lighthouse we need to know to be able to reproduce this?

**Comment by sainikbiswas** [comment]
@patrickhulce Hi Patrick. I am running this Lighthouse test on a Windows 10 PC. I get the same report on both Google Chrome and Google Chrome Canary. I only have Ublock Origin, Roboform Chrome extensions installed and the Chrome accounts are signed in to my GSuite domain. I tried clearing the entire browser cache and disabled the extensions and then reran the Lighthouse Audit but got the same results. Can this be a caching issue?

**Comment by patrickhulce** [comment]
I wouldn't expect caching to be an issue here, though CDNs have been known to do weird things with geo+UA combinations before. Do you have a bash-like environment on your PC? (WSL, Git Bash, etc)

Does 
```
curl -vvvv -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse' https://journalof.tech/ --compressed > /dev/null
``` 

give you a compressed `content-encoding` response? That's the UA that Lighthouse uses by default.

**Comment by sainikbiswas** [comment]
Hi @patrickhulce As far as I see an Accept-Encoding with gzip was returned when I ran this command in WSL. Here is the output.

curl -vvvv -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse' https://journalof.tech/ --compressed > /dev/null                                                                                * Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 13.234.145.4...
* Connected to journalof.tech (13.234.145.4) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
*        subject: CN=journalof.tech
*        start date: 2019-09-28 09:16:04 GMT
*        expire date: 2019-12-27 09:16:04 GMT
*        subjectAltName: journalof.tech matched
*        issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*        SSL certificate verify ok.
> GET / HTTP/1.1
> Host: journalof.tech
> Accept: */*
> Accept-Encoding: deflate, gzip
> User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse
>
< HTTP/1.1 200 OK
< Date: Mon, 14 Oct 2019 10:31:31 GMT
* Server Apache is not blacklisted
< Server: Apache
< x-cache-handler: wp
< X-Frame-Options: sameorigin
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: no-referrer-when-downgrade
< Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
< Upgrade: h2,h2c
< Connection: Upgrade
< Last-Modified: Fri, 11 Oct 2019 11:01:07 GMT
< Vary: Accept-Encoding
< Content-Encoding: gzip
< Content-Length: 5379
< Content-Type: text/html; charset=UTF-8
<
{ [data not shown]
100  5379  100  5379    0     0  11486      0 --:--:-- --:--:-- --:--:-- 11493

**Comment by patrickhulce** [comment]
Hm, well I am thoroughly stumped @sainikbiswas! Unfortunately, if we can't reproduce it I'm not sure how we'll be able to fix it :/

I appreciate all the effort thusfar @sainikbiswas I'm sorry we can't seem to see the same bug on our end :( If anyone else is able to repro this maybe they could chime in with some helpful extra context?

**Comment by mcluseau** [comment]
Hi there, I wonder if it's not something in the environment of the viewer (or the google's pagespeed insights), like a proxy decompressing responses. You can try on https://www.lecaracol.fr.

In the viewer:
```
    "uses-text-compression": {
      "id": "uses-text-compression",
      "title": "Enable text compression",
      "description": "Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes. [Learn more](https://web.dev/uses-text-compression).",
      "score": 0.39,
```

When using lighthouse CLI from my computer:
```
    "uses-text-compression": {
      "id": "uses-text-compression",
      "title": "Enable text compression",
      "description": "Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes. [Learn more](https://web.dev/uses-text-compression).",
      "score": 1,
```

In both cases, on the server side, content is sent compressed:
```
UA: Chrome-Lighthouse | AE: gzip,deflate,br | encoding:       br | path: css/styles.min.60d5937d24f852bbb1e7bac86d3861539f850b08abb491208aa6e3e4aa232120.css
```

**Comment by mcluseau** [comment]
it seems to be OK through HTTP/2, so it ok for me.

**Comment by gigioSouza** [comment]
I'm testing right now and it seems to check for compressed versions when running for Desktop but not checking for compressed versions when running for Mobile.

Localhost running for Desktop:
![image](https://user-images.githubusercontent.com/4052932/100305813-aaa21380-2f80-11eb-98ac-2a8c04e28d81.png)

Localhost running for Mobile:
![image](https://user-images.githubusercontent.com/4052932/100305847-b8f02f80-2f80-11eb-83e7-9014aee2462a.png)

**Comment by zachnicodemous** [comment]
I am having this issue too. I'm testing a website locally and I am not getting a text compression issue flag on either desktop OR mobile, however, my client located 600 miles away in Canada is getting a text compression warning for mobile which is adding 5.2 seconds and lowering the score they see.  I have Cloudflare enabled on the site but even when disabling, I am getting the same issue. Has anyone figured out a solution for why text compression flags in some cases but not others?

**Comment by andersfloor** [comment]
I experienced the same, but after hours of researching I found out that my antivirus software (in my case ESET) was interfering with the Cloudflare-headers. Pausing the antivirus made the difference.

**Comment by sainikbiswas** [comment]
@andersfloor It is exactly what was causing the issue, ESET Internet Secuirty, disabling it solved the problem. Thanks 👍

**Comment by joloco** [comment]
Apologies for the "me too" message but I had exactly the same set-up and problem -- BunnyCDN, CloudFlare, compression enabled but Lighthouse not detecting it.

I also have ESET security software installed, and disabling the "Web access protection" feature solved the Lighthouse issue. So I guess ESET is inflating the content for sniffing before sending it (still inflated) to the browser.

Thanks to all who added their input here, very useful! :)

**Comment by connorjclark** [comment]
re ESET that should have been fixed with #13176, LH v8.6.0

**Comment by MatinT-SA** [comment]
@andersfloor
I had the same issue and by pausing my antivirus software, Kaspersky, it didn't consider this audit as an unoptimized thing anymore while i generated a Lighthouse report for my Mobile devices.
So it seems in this case the antivirus software is causing an issue.

**Comment by connorjclark** [comment]
Provide us a report and there may be a chance we can resolve the issue.
