### ISSUE TITLE
smokehouse: modify to allow to be run from the module with custom dfns file.

### ISSUE THREAD

**Issue by jburger424** [GoogleChrome/lighthouse#9827]
In order to use smokehouse in its current state, I needed to do several hacky workarounds to move files into the hard-coded locations. See: https://github.com/googleads/publisher-ads-lighthouse-plugin/pull/137/files#diff-405aff372b55a2dc030266d6127da496R38

I'd be happy to implement this myself.

**Comment by brendankenny** [comment]
@jburger424 I'm working on a change right now that will allow this so plugins can do smoke tests too

**Comment by brendankenny** [comment]
I was thinking we can expose a bin command and point to a set of test definitions? Would that work for you?

**Comment by jburger424** [comment]
Oh perfect, hadn't realized that. 

That definitely seems like it would work for our use case.

**Comment by connorjclark** [comment]
@jburger424 can you take a look at the new smokehouse runner and let us know if you have any issues with it?

```
node lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js --help
```

**Comment by brendankenny** [comment]
`yarn smoke --tests-path plugin-test-dfns.js`

:)
