### ISSUE TITLE
lantern: data uris include server response time

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#9833]
I  noticed in the simulator that non-network URLs get treated, I believe, as actual network requests that will use a connection, etc.

Clearly there shouldn't be any server response time, though I think a non-zero RTT makes sense.. probably more like 5-10ms ish.

@patrickhulce can you help me think about how we'd fix this?  Looking through the lantern code I'm not sure where we'd handle this case.

![image](https://user-images.githubusercontent.com/39191/66706889-8c7e4300-eced-11e9-80f5-72fa752dbffc.png)

**Comment by patrickhulce** [comment]
Ooooo, yikes, yes let's fix that in `simulateDownloadUntil`! Check if it's a non-network protocol and have some constant/option for dealing with the RTT/server response time

https://github.com/GoogleChrome/lighthouse/blob/d50ef9e3c9caee2e73221c7a03d6aabdeb32ef9b/lighthouse-core/lib/dependency-graph/simulator/tcp-connection.js#L112-L123

**Comment by patrickhulce** [comment]
Given #9834 too we should probably do an audit of our network request usage for data URI mistakes and/or add more data URIs to our smokes :)
