### ISSUE TITLE
Data URI should not be counted as "third party"

### ISSUE THREAD

**Issue by Krinkle** [GoogleChrome/lighthouse#9834]
#### Provide the steps to reproduce
1. Run LH on `https://timotijhof.net/`
2. Expand the "Keep request count low section" under "Performance".

#### What is the current behavior?

Data URIs are counted as "Third party" requests.

| Lighthouse | Network DevTools
|--|--
| <img alt="Lighthouse report" src="https://user-images.githubusercontent.com/156867/66726855-885c3d80-ee33-11e9-9d0b-326381b1ddd7.png" width="500"> |<img width="450" alt="Screenshot of Network DevTools" src="https://user-images.githubusercontent.com/156867/66726856-885c3d80-ee33-11e9-877b-edc96e1040e4.png">

#### What is the expected behavior?

For data URIs to not be counted, or to be counted as regular same-origin requests.

#### Environment Information
* Lighthouse 5.2.0
* Google Chrome 77.0.3865.90
* macOS 10.14

**Related issues**
* https://github.com/GoogleChrome/lighthouse/issues/9833

**Comment by patrickhulce** [comment]
This was fixed in third-party-web 0.11.0 🎉  https://github.com/patrickhulce/third-party-web/releases/tag/v0.11.0

(and lighthouse 6.0)
