### ISSUE TITLE
DevTools Error: Protocol Timeout

### ISSUE THREAD

**Issue by libra7oct** [GoogleChrome/lighthouse#9835]
I am facing problems regarding page audit screen shot attached
![image](https://user-images.githubusercontent.com/49521413/66735641-5cb37480-ee80-11e9-9a98-52b70219d8b0.png)

DevTools Error: Protocol Timeout

**Comment by schroef** [comment]
I also see this on this address; http://promotiespullen.web2printsoftware.nl/

![Screen Shot 2019-10-14 at 15 25 12](https://user-images.githubusercontent.com/6923008/66777372-df472e80-ee96-11e9-93db-581468da98fc.png)

Seem like its time-out to soon, some website take longer to load intially. Thats already kind of bad ofcourse. But we cant run Audits on these site now

**Comment by deepshet** [comment]
Same error 
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://www.bio-rad-antibodies.com/
Chrome Version: 80.0.3987.163
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@e7fbe071abe9328cdce4ffedac9822435fbd3656/audits_worker/audits_worker_module.js:1268:229)

![image](https://user-images.githubusercontent.com/42215259/78507107-fd4d6780-7732-11ea-894d-34b12d223439.png)

**Comment by Renato66** [comment]
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://renato66.github.io/
Chrome Version: 80.0.3987.163
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@e7fbe071abe9328cdce4ffedac9822435fbd3656/audits_worker/audits_worker_module.js:1268:229)
```

**Comment by basheerOct** [comment]
I'm getting this too on Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by Beytoven** [comment]
Closing as a duplicate. Please see #6512.
