### ISSUE TITLE
Unable to audit site with authentication

### ISSUE THREAD

**Issue by YM-KA** [GoogleChrome/lighthouse#9840]
Hi! I am unable to run lighthouse on a site (https) with authentication [using the method described in the documentation. ](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#testing-on-a-site-with-authentication)

OS: Windows 10 (1093 Build 18362.418)
Node.js: 10.16.3
Lighthouse 5.5.0

**Steps to replicate.**
1. Open a terminal and run "chrome-debug"
2. Login to site (app.mytest.se)
3. Take note of port in terminal (123456)
4. Open a new terminal 
5. Type "lighthouse https://app.mytest.se --port 123456"

Lighthouse ignores the --port argument and opens a new tab that **is not logged in**. 
This behavior is identical to typing "lighthouse https://app.mytest.se" - the --port argument has no effect. 

I have tried running the terminals (git bash and PowerShell) in elevated mode with the same result. Is any details about this method missing in the documentation? 

Kind regards
Kazuyuki

**Comment by patrickhulce** [comment]
How do you store your credentials for login? Does running with the `--disable-storage-reset` flag work as expected?

We have [additional documentation specifically on authenticated pages](https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md) have you read through those to see if they apply to your situation?

**Comment by YM-KA** [comment]
Hi @patrickhulce - thank you for the prompt reply!
I am not storing my credentials, I type them in manually. 
Unfortunately the  <code>--disable-storage-reset</code> flag has no visible effect - at least not as far as I can see.  

I tried using Puppeteer, but had some trouble setting up my environment. 
Lighthouse requires Node >= 10.13 so I have upgraded to 10.16.3. 
The dependencies in <code>package.json</code> does not work with Node 10.16.3. 

Modules express-session, morgan and puppeteer all reports:  
<code>error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".</code>

When downgrading to Node 9.10.1 I cannot install Lighthouse.
<code>error lighthouse@5.6.0: The engine "node" is incompatible with this module. Expected version ">=10.13".</code>

This causes a catch 22, the [documentation for Puppeteer](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/auth) is unclear about how to setup the environment and resolve dependency issues. 

UPDATE: 
By installing Lighthouse 4.3.1 I managed to install my environment. 
Could there maybe be examples of how to set up Puppeteer + Lighthouse for different Node versions? :)

**The Puppeteer script does not work** 
I have edited the script to login and write the output to file, but lighthouse does still not run on the logged in site. 

Steps to reproduce
1. nvm use 9.10.1
2. install all dependencies (express, puppeteer, lighthouse@4.3.1)
3. download and edit [example-lh-auth.js](https://github.com/GoogleChrome/lighthouse/blob/master/docs/recipes/auth/example-lh-auth.js) to meet you requirements 
4. node example-lh-auth.js
5. Chrome opens and logs in - ok!
6. Lighthouse runs in a separate tab, **still not logged in** :'(

Why does not lighthouse pick up the session? 
My site is using Firebase Auth (JWT, Local storage). 

See attached example code --> [Puppeteer.txt](https://github.com/GoogleChrome/lighthouse/files/3747711/Puppeteer.txt)

Kind regards
Kazuyuki

**Comment by patrickhulce** [comment]
> I am not storing my credentials, I type them in manually.

I meant how does the application store credentials :) but it sounds like you use firebase auth and `localStorage`?

You will definitely need the `--disable-storage-reset` flag then or `disableStorageReset: true` added to your `{port: XXXX}` object if you're running from node.

@connorjclark we should probably mention this in the auth docs somewhere as it's essential for everything other than cookie-based auth

**Comment by YoomiAB** [comment]
Hi @patrickhulce! LoL, yes I use Firebase Auth. 🤓 

Yay, <code>disable-storage-reset</code> did the trick - Lighthouse now works as expected. 🍾 🎉 
I changed the line to read
<code>const result = await lighthouse(url, {port: PORT, disableStorageReset: true});</code>

Many thanks! 😄

**Comment by YM-KA** [comment]
Hi @patrickhulce! LoL, yes I use Firebase Auth. 🤓 

Yay, <code>disable-storage-reset</code> did the trick - Lighthouse now works as expected. 🍾 🎉 
I changed the line to read
<code>const result = await lighthouse(url, {port: PORT, disableStorageReset: true});</code>

Many thanks! 😄

**Comment by asghar153** [comment]
ok
