### ISSUE TITLE
Update images in the docs

### ISSUE THREAD

**Issue by chrisdeveloperit** [GoogleChrome/lighthouse#9841]
A PWA score does not display, even though 9/11 items under Progressive Web App tests are positive.  Scores display for all other tests.
[MDEV-Property-VideoIntro.pdf]
(pdf removed)

**Comment by patrickhulce** [comment]
@chrisdeveloperit the PWA category has sections to complete that represent the different aspects of being a PWA, the numeric score is not really meaningful and is *never* displayed to the user. Upon completion of all 11 items it changes to a checkmark.

![image](https://user-images.githubusercontent.com/2301202/66769761-8ae28580-ee7b-11e9-867c-f2f12fc4a82f.png)

**Comment by chrisdeveloperit** [comment]
Thank you @patrickhulce .  The Lighthouse Scoring Guide lead our team to think that our Lighthouse Report should look like the image displayed in their documentation.  https://developers.google.com/web/tools/lighthouse/v3/scoring
![LighthouseUI](https://user-images.githubusercontent.com/10872195/66771790-050d0d00-ee70-11e9-968a-af7cc7349785.png)

**Comment by patrickhulce** [comment]
Ah thanks for the explanation @chrisdeveloperit! That is the scoring guide for v3 which used a numeric system for PWA. From v4 onward (on v5.5.0 currently), the PWA scoring system is the one you see in the pdf you filed 👍

**Comment by connorjclark** [comment]
We should update all these stale images.
