### ISSUE TITLE
Explore re-enabling unused JS audit by default

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/lighthouse#9853]
We previously [explored](https://github.com/GoogleChrome/lighthouse/issues/1852#issuecomment-306900595) implementing JS code coverage as an audit, but did not turn it on by default due to concerns about how costly this was over CDP. After a recent discussion about function-level coverage being almost free, I would love for us to re-explore turning this on for **everyone** :)

Benedikt confirmed that function-level coverage should have little to no impact on JS execution time, since it uses the same counter that we use for the optimizing compiler. It does enforce the early allocation of this counter though, and it keeps all functions around, which means that it needs a bit more memory, but that shouldn't matter for short runs, and even with longer runs might easily disappear within noise of a regular application.

Regarding the audit, Patrick noted that we ran [experiments](https://github.com/GoogleChrome/lighthouse/pull/6728) again in Jan 2019 and concluded that the impact coverage had on performance numbers was not discernible from regular run variance. We apparently didn't move it then because of the relatively low confidence in the variance breadth at the time but since then we've understood our variance a little better and he was comfortable enough to bring it up again.

caseq noted the overhead of gathering the coverage data should be relatively small as long as we don't poll too frequently, and gathering data just once at the end should be good for LH. CDP overhead shouldn't be an issue here, since LH probably only needs final coverage data and can retrieve coverage after other measurements have been taken.

With that in mind, if @paulirish is cool with it, I'd love for this to be explored by @patrickhulce

**Comment by brendankenny** [comment]
> V8 confirmed that function-level coverage should have little to no impact on JS execution time

we also probably need to verify the effect on inlining and the whole "works reliably and has no rough edges left" caveat :)

**Comment by connorjclark** [comment]
Been looking forward to having this enabled. There's some neat stuff we can do w/ source maps + this audit. https://docs.google.com/document/d/1Lo2xwW4iwXYh2QaBtx-P8LLbOKxGsBfpwxV4DBVjQAg/edit?ts=5da516ef

**Comment by addyosmani** [comment]
🚀
