### ISSUE TITLE
Installation from 'npm' fails

### ISSUE THREAD

**Issue by ramlmn** [GoogleChrome/lighthouse#986]
OS: `Windows 10 Pro`
Terminal: `Git Bash`
Node: `v6.9.1`
NPM: `v3.10.8`

A normal installation from npm using `npm install -g GoogleChrome/lighthouse` fails with:
``` bash
$ npm install -g GoogleChrome/lighthouse
C:\Users\ramlmn\AppData\Roaming\npm\lighthouse -> C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\index.js
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "GoogleChrome/lighthouse"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\manual-chrome-launcher.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\manual-chrome-launcher.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\manual-chrome-launcher.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ramlmn\npm-debug.log
```
[Complete npm debug log file](https://gist.github.com/ramlmn/3d651b6ab8fa7905683ee97e3e138681)

I also tried to clone and install lighthouse globally with
``` bash
$ git clone https://github.com/GoogleChrome/lighthouse.git
$ cd lighthouse
$ npm install
$ (cd lighthouse-cli && npm install && npm run build)
$ npm install -g
```
which gives the same error.

But running `npm start {url}` works after installing dependencies and building cli.

**Comment by wardpeet** [comment]
Please do `npm install -g lighthouse`

**Comment by ramlmn** [comment]
@wardpeet Yes that works, but previously `npm install -g GoogleChrome/lighthouse` used to work perfectly containing the source and everything (stopped working from exactly 12 days ago).

Please look into that because a few people still use the above method and do a manual lighthouse-cli build.

But since beginning ligthouse is doing this:
```
...
  ChromeLauncher Killing all Chrome Instances +487ms
C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:312
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\ramlmn\AppData\Local\Temp\lighthouse.35898675'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:886:18)
    at rmkidsSync (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:342:11)
    at rmdirSync (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:332:7)
    at Function.rimrafSync [as sync] (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:303:9)
    at ChromeLauncher.destroyTmp (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\chrome-launcher.js:182:20)
    at ChildProcess.chrome.on (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\chrome-launcher.js:164:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
```

This error occurs to me since the I started using lighthouse on my Windows machine, didn't try on others but it still gives me the same error after the total audit (Glad atleast it saves the audit file). It happens even though when I run console as Administrator. Please have a look into it.

**Comment by samccone** [comment]
Perhaps related to this commit:
https://github.com/GoogleChrome/lighthouse/commit/2fed83361df6212dbe48d7492deaaa9e1663a027

**Comment by wardpeet** [comment]
@ramlmn I believe these are 2 separate issues. Thanks we will look into this.
@samccone Looks like regression of #854

**Comment by ramlmn** [comment]
Oh actually I didn't notice that you changed the installation to just `lighthouse` since release 1.1.7

@wardpeet Should I make another issue for the directory removal error?

**Comment by wardpeet** [comment]
@ramlmn yes please
