### ISSUE TITLE
Typo on Chrome Extension listing

### ISSUE THREAD

**Issue by coliff** [GoogleChrome/lighthouse#9861]
Typo on: https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk

![image](https://user-images.githubusercontent.com/1212885/67075732-ba202c00-f1c6-11e9-9f1f-55a677b88fd2.png)

GitHub capitalisation issue.

**Comment by paulirish** [comment]
@coliff thanks man!

fixed. should be published within an hour.

**Comment by connorjclark** [comment]
Should be up within an hour.
