### ISSUE TITLE
Javascript audits failing

### ISSUE THREAD

**Issue by fchristant** [GoogleChrome/lighthouse#9865]
#### Provide the steps to reproduce
1. Lighthouse 5.2.0
2. Chrome 77
3. Windows 10
4. Incognito mode
5. Any domain
6. Javascript execution time, Minimizes main thread work, and Third party usage audits always result in "Error!"
  

#### What is the current behavior?
Given the above environment, all the mentioned JS audits are consistenly giving "Error!" as the audit output, across domains.

#### What is the expected behavior?
JS audits providing meaningful output

#### Environment Information
* Affected Channels: DevTools 
* Lighthouse version: 5.2.0
* Node.js version: n/a
* Operating System: Windows 10

**Comment by patrickhulce** [comment]
Thanks for filing @fchristant! This is a result of late Chromium changes that spit out invalid traces. 5.6.0 has our workarounds that (mostly) fix the issue which will be coming in later Chrome versions.

ref #9786 #9785 #9491 #9230
