### ISSUE TITLE
Content is not sized correctly for the viewport?

### ISSUE THREAD

**Issue by fchristant** [GoogleChrome/lighthouse#9867]
I'm having issues with the audit mentioned in the title. Running this on known responsive sites (example: google.com) always fails this audit:

Content is not sized correctly for the viewport. The viewport size is 412px, whereas the window size is 3440px

The sites I tested are responsive, have the proper meta viewport tag. Am I using this wrong?

Environment:
- Lighthouse 5.2.0
- Chrome 77
- Windows 10

**Comment by connorjclark** [comment]
This will be fixed in 78: https://github.com/GoogleChrome/lighthouse/issues/9476#issuecomment-524424060

**Comment by fchristant** [comment]
Thank you, sorry for the dupe.
