### ISSUE TITLE
Request blocking is not working with Chrome Audit tool

### ISSUE THREAD

**Issue by vinodgoudk** [GoogleChrome/lighthouse#9870]
Hi,

I want to see page performance metrics difference for requests with and without third party JS. I have blocked third-party JS with chrome request blocking tool and then when I ran the chrome audit tool, it is still considering the blocked requests while calculating the metrics. Is there an open issue with the audit tool or am I performing the test incorrectly?

Please take a look at the following screenshot.

![Screen Shot 2019-10-21 at 10 24 14 AM](https://user-images.githubusercontent.com/1296268/67227916-0f3d8700-f3ed-11e9-8bbd-6f871ead07bf.png)

Thanks

**Comment by connorjclark** [comment]
This only began working in Chrome 78, which is still in beta. Are you using stable?

**Comment by vinodgoudk** [comment]
Yes, I am using Version 77.0.3865.120 (Official Build) (64-bit). Let me try Chrome 78. Thanks

**Comment by vinodgoudk** [comment]
Perfect!! It works fine in Version 78.0.3904.70 (Official Build) beta (64-bit). Thanks.

**Comment by connorjclark** [comment]
awesome! happy hacking
