### ISSUE TITLE
Switch to Moto G4 for mobile emulation

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9876]
see: https://github.com/GoogleChrome/lighthouse/pull/9662#issuecomment-542887197

- [x] Add device frame to DevTools
- [x] Change UA string

**Comment by ozcoder** [comment]
@connorjclark Is there docs/reasoning behind this change that I could read please?
Doesn't GoogleBot use a Nexus5 equivalent, which will become especially important come September 2020?

**Comment by connorjclark** [comment]
It's correct that GoogleBot does use Nexus 5 for mobile screen emulation. However, Lighthouse's purview is performance testing, not matching GoogleBot. We use a slightly older generation phone for our baseline mobile profile. For awhile, the standard phone for that purpose in the performance community was Nexus 5. For a few years now it has been Moto G4, so this change was a bit overdue.

That said, I wouldn't expect this slight change in screen emulation to result in any performance differences in Lighthouse.

**Comment by mguentge** [comment]
@connorjclark  now since core web vitals were announced to May 2021 what will be the plan to evaluate scores by GoogleBot.
Will the GoogleBot change it's user agent to Moto G4 -or- will be the scoring evaluated based on Nexus 5X user agent (afaik only weblight uses the older Nexus 5)?

**Comment by connorjclark** [comment]
We don't know anything really about GoogleBot or their plans, sorry.
