### ISSUE TITLE
Duplicated stack packs

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#9881]
Repro.: run lighthouse or PSI on https://abcnews.go.com/  and open Minify JavaScript

----------

![image](https://user-images.githubusercontent.com/39191/67442906-7c9d1380-f5b7-11e9-9449-e93d77734fb2.png)
![image](https://user-images.githubusercontent.com/39191/67443023-f92ff200-f5b7-11e9-9d58-39d1a4985ffa.png)

-------

This is due to the addition of the new "Fast Path" checks landed in [js-lib-detector here](https://github.com/johnmichel/Library-Detector-for-Chrome/pull/140). (In general I like the idea. :) We then [rolled into Lighthouse here](https://github.com/GoogleChrome/lighthouse/pull/9797).

There's actually two bugs here. 

1. We have two stack packs. 
   - My preferred fix is to add real `id` properties into js-library-detector and then we can upgrade [this superloose coupling](https://github.com/GoogleChrome/lighthouse/blob/dab020167000860c2b8fc43ee76963eb83d63a94/lighthouse-core/lib/stack-collector.js#L83). @housseindjirdeh can you help out with this?
1. We're showing these new experimental `React (Fast Path)` entries to users within the bestpractices/js-libraries audit. [Screenshot here](https://github.com/johnmichel/Library-Detector-for-Chrome/pull/140#issuecomment-545685789).  I don't think anybody intended these to be user-visible. :)
   -  @anniesullie I imagine you're planning to collect this data from the `httparchive:lighthouse` tables?
   - Pending that answer, I'm wondering if we can continue to expose the signals in the JSON, but hide it from the user. TBH I don't think we have a great mechanism for that, but it's something we can noodle on.

**Comment by anniesullie** [comment]
> @anniesullie I imagine you're planning to collect this data from the httparchive:lighthouse tables?
> Pending that answer, I'm wondering if we can continue to expose the signals in the JSON, but hide it from the user. TBH I don't think we have a great mechanism for that, but it's something we can noodle on.

Yep, only planning to collect from httparchive:lighthouse tables. Hiding from the user is totally okay with me!

**Comment by paulirish** [comment]
@anniesullie groovy. thanks

**Comment by housseindjirdeh** [comment]
@paulirish Updated the detector so each lib has an `id` property: https://github.com/johnmichel/Library-Detector-for-Chrome/pull/149

PR #9888 fixes the loose coupling and updates the version of the library-detector

**Comment by housseindjirdeh** [comment]
> Pending that answer, I'm wondering if we can continue to expose the signals in the JSON, but hide it from the user. 

We could add a `secondary` flag in the library-detector and then filter directly in the js-libraries audit. Could something like that work?

**Comment by paulirish** [comment]
> We could add a `secondary` flag in the library-detector and then filter directly in the js-libraries audit. Could something like that work?

Well.. we need the items in the js-libraries audit details for annie's collection to work.  But it needs to be hidden in the UI.

Hmmm...

----------------------

I dont see a way around filtering items like this out in detailsRenderer's `_renderTable`. @brendankenny do you have any ideas?  Changing details shape to add details.hiddenitems??  🤢

**Comment by housseindjirdeh** [comment]
> Well.. we need the items in the js-libraries audit details for annie's collection to work. But it needs to be hidden in the UI.

Ah got it, yep was referring to the UI - but for some reason thought it was tightly coupled to the audit itself

> Changing details shape to add details.hiddenitems?? 🤢

Sounds like we would most probably still need an identifier to distinguish which items should be hidden, and I can definitely add a flag if that's necessary 🙏

**Comment by brendankenny** [comment]
> I dont see a way around filtering items like this out in detailsRenderer's `_renderTable`. @brendankenny do you have any ideas? Changing details shape to add details.hiddenitems?? 🤢

sorry, just saw this.

All audit details (and most of the properties nested within audit details) can have an extra `debugData` property on them, meant for this sort of thing. We use this for e.g. [data not to be visible in the accessibility-audit details tables](https://github.com/GoogleChrome/lighthouse/blob/7fab7e2b9a34bd69bb7fb78326ab3d6a77ed9f8c/lighthouse-core/audits/accessibility/axe-audit.js#L67-L83) ([example in `sample_v2.json`](https://github.com/GoogleChrome/lighthouse/blob/7fab7e2b9a34bd69bb7fb78326ab3d6a77ed9f8c/lighthouse-core/test/results/sample_v2.json#L1693-L1733)), which is somewhat similar to this case.

It does take a little more parsing effort for http archive queries, but it shouldn't be too bad? `debugData` could also contain all the libraries (duplicating the ids of the libraries in the main table) so any queries wouldn't have to combine the main table and the debugData.

**Comment by paulirish** [comment]
oh perfect. @housseindjirdeh wanna take a stab at that too?

**Comment by brendankenny** [comment]
> `debugData` could also contain all the libraries (duplicating the ids of the libraries in the main table) so any queries wouldn't have to combine the main table and the debugData.

so it would be something like
```js
"js-libraries": {
  "id": "js-libraries",
  // ...
  "details": {
    "type": "table",
    "headings": [{
      // ...
    }],
    "items": [
      // ...
    ],
    "debugData": {
      "type": "debugdata",
      "allIds": [
        "jquery",
        "jquery-fast",
        "wordpress"
      ]
    }
  }
}
```
for some value of `allIds` :)
