### ISSUE TITLE
Provided value "protocolMethod" does not match any placeholder in ICU message 

### ISSUE THREAD

**Issue by antonpresn** [GoogleChrome/lighthouse#9882]
#9424 ## Provide the steps to reproduce
1. Run LH on https://ochkarik.ru

#### What is the current behavior?
Got an error

Provided value "protocolMethod" does not match any placeholder in ICU message "An internal Chrome error occurred. Please restart Chrome and try re-running Lighthouse."
```
Channel: DevTools
Initial URL: https://ochkarik.ru/
Chrome Version: 79.0.3941.4
Stack Trace: Error: Provided value "protocolMethod" does not match any placeholder in ICU message "An internal Chrome error occurred. Please restart Chrome and try re-running Lighthouse."
    at _preformatValues (devtools://devtools/remote/serve_file/@40e19e7eec526237f481660571fd72d7fb078754/audits_worker/audits_worker_module.js:1605:7)
    at _formatIcuMessage (devtools://devtools/remote/serve_file/@40e19e7eec526237f481660571fd72d7fb078754/audits_worker/audits_worker_module.js:1609:189)
    at _resolveIcuMessageInstanceId (devtools://devtools/remote/serve_file/@40e19e7eec526237f481660571fd72d7fb078754/audits_worker/audits_worker_module.js:1620:452)
    at Object.getFormatted (devtools://devtools/remote/serve_file/@40e19e7eec526237f481660571fd72d7fb078754/audits_worker/audits_worker_module.js:1617:104)
    at Function.run (devtools://devtools/remote/serve_file/@40e19e7eec526237f481660571fd72d7fb078754/audits_worker/audits_worker_module.js:1967:917)
```
#### What is the expected behavior?
run without errors

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 
* Chrome version: 79.0.3941.4 dev (64 bit)
* Node.js version:
* Operating System: Linux (Fedora release 30 (Thirty), Linux version 5.3.6-200.fc30.x86_64)

**Related issues**

**Comment by connorjclark** [comment]
I've been seeing this all the time lately. Seems to start when a new Chrome is initially installed / updated, and eventually goes away. Restarting Chrome / DevTools may or may not help.

@exterkamp I don't the root cause is related to i18n, but it's unusual that the error message can't be shown properly.

@antonpresn does it work after restarting Chrome a couple times?

**Comment by patrickhulce** [comment]
@connorjclark I believe this is just PROTOCOL_TIMEOUT but with outdated locale messages.

**Comment by connorjclark** [comment]
> @connorjclark I believe this is just PROTOCOL_TIMEOUT but with outdated locale messages.

I was getting these errors immediately when starting the audit.

**Comment by patrickhulce** [comment]
Oops, yeah sorry. `TRACING_ALREADY_STARTED` is the case where it fails immediately. Looks like we need to cleanup that path to stop passing `protocolMethod` to it

**Comment by paulirish** [comment]
@robdodson just got this as well

![image](https://user-images.githubusercontent.com/39191/68335646-b5e28280-0091-11ea-89cc-c0dd243aa130.png)

**Comment by dskoziol** [comment]
I'm getting it now on Chrome 80.0.3955.4

**Comment by brendankenny** [comment]
I already looked into this so I can just do the easy fix

**Comment by exterkamp** [comment]
> @exterkamp I don't think the root cause is related to i18n, but it's unusual that the error message can't be shown properly.

I was wrong :open_mouth:
