### ISSUE TITLE
Lighthouse unable to generate report with newer chromium on centos7

### ISSUE THREAD

**Issue by LarsKumbier** [GoogleChrome/lighthouse#9883]
After re-provisioning a lighthouse VM, I noticed that I was unable to run lighthouse against www.verivox.de. After a day of debugging and bisecting versions, I found that lighthouse does not work with chromium-headless in versions >71 on centos7, but *only* for centos and *only* for https://www.verivox.de.

I am unsure on how to proceed in debugging this further - any hints appreciated.

#### Provide the steps to reproduce

**Last known good version, that works**
A0. Install centos 7, node 12 and finally lighthouse: `npm i -g lighthouse@5.6.0`
A1. Install EPEL repository: `yum install -y epel-release`
A2. Install chromium-headless-71.0.3578.98-2.el7: `yum install -y chromium-headless-71.0.3578.98-2.el7 ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc`
A3. Make sure lighthouse picks up the chrome-headless: `export CHROME_PATH="/usr/lib64/chromium-browser/headless_shell"`
A4. Run lighthouse against verivox.de: `lighthouse --chrome-flags="--headless --no-sandbox --disable-gpu" --logLevel=debug "https://www.verivox.de"`

Notice that you get a report as expected. Now repeat the steps with any chromium-browser version greater than 71.

**Steps to reproduce with a bad version**
B0. Remove old versions: `yum remove -y chromium-headless chromium-common`
B1. List available versions: `yum --showduplicates list chromium-headless`
B2. Choose any version after 71 and install: `yum install -y chromium-headless-73.0.3683.86-2.el7 ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc`
B3. Make sure lighthouse picks up the chrome-headless: `export CHROME_PATH="/usr/lib64/chromium-browser/headless_shell"`
B4. Now run lighthouse against verivox.de: `lighthouse --chrome-flags="--headless --no-sandbox --disable-gpu" --logLevel=debug "https://www.verivox.de"`

You'll notice that lightmon gets stuck:
```
  ChromeLauncher Waiting for browser. +0ms                                                                                                                                                                         
  ChromeLauncher Waiting for browser... +0ms                                                                                                                                                                       
  ChromeLauncher Waiting for browser..... +508ms                                                                                                                                                                   
  ChromeLauncher Waiting for browser.....✓ +3ms                                                                                                                                                                    
  status Connecting to browser +177ms                                                                                                                                                                              
  status Resetting state with about:blank +25ms                                                                                                                                                                    
  status Benchmarking machine +41ms                                                                                                                                                                                
  status Initializing… +508ms                                                                                                                                                                                      
  status Resetting state with about:blank +34ms                                                                                                                                                                    
  status Setting up network for the pass trace +13ms                                                                                                                                                               
  status Cleaning browser cache +3ms                                                                                                                                                                               
  status Beginning devtoolsLog and trace +5ms                                                                                                                                                                      
  status Loading page & waiting for onload CSSUsage, ViewportDimensions, RuntimeExceptions, ConsoleMessages, AnchorElements, ImageElements, LinkElements, MetaElements, ScriptElements, AppCacheManifest, Doctype, 
DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility +6ms
  Driver:warn Timed out waiting for page load. Checking if page is hung... +45s
  Driver:warn Page appears to be hung, killing JavaScript... +1s
  status Disconnecting from browser... +30s
  ChromeLauncher Killing Chrome instance 23618 +14ms
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)
LHError: PROTOCOL_TIMEOUT
    at Timeout._onTimeout (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:409:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

#### Further investigation

Ensure that the browser can actually reach the page and dump the dom: 

```
# ${CHROME_PATH} --headless --no-sandbox --disable-gpu --dump-dom --logLevel=debug "https://www.verivox.de"
[1024/120935.641993:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.
[1024/120935.686825:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
[1024/120935.700129:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
<!DOCTYPE html>
<html lang="de"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
[...]
```

I further found, that this problem is *only* for www.verivox.de - this works fine: `lighthouse --chrome-flags="--headless --no-sandbox --disable-gpu" --logLevel=debug "https://kumbier.it"` -- You'll get a valid report.

I tried to reproduce the problem under Ubuntu 19 and was unable to.

The problem also exists with the current latest chromium-browser in the epel-release of centos 7 (77.0.3865.90-2.el7).

The problem does affect chromium-headless as well as the normal `chromium`-package - reproduce by running the same commands above with chromium instead of chromium-headless.

The VM is headless and is hosted on a vsphere cluster.

#### Environment Information
* Affected Channels: lighthouse
* Lighthouse version: reproducible from 5.2 until 5.6 - I stopped testing below 5.2
* Chrome version: see above
* Node.js version: 12.13.0
* Operating System: centos 7

**Related issues**

**Comment by LarsKumbier** [comment]
@paulirish @connorjclark Hey guys, sorry for disturbing. I think this issue is different from #6512 - could you please check and reopen, if appropriate? thanks.

**Comment by patrickhulce** [comment]
Thanks @LarsKumbier! This is indeed slightly different than the common case in #6512 even though we get the same root error :)

**Comment by LarsKumbier** [comment]
Nothing that I know of - I've already tried to run lighthouse with logLevel=debug and am unsure, how to dig deeper. The strange thing is, that I was unable to reproduce the issue on my Ubuntu desktop machine - I do not know if centos does source-patching like Debian does time to time, which would cause the different behavior.

Is it possible to get a stacktrace or an undocumented development feature to get down further? 

If not I'll start a remote debugger and start that way.

**Comment by connorjclark** [comment]
> The problem also exists with the current latest chromium-browser in the epel-release of centos 7 (77.0.3865.90-2.el7).

Whenever 78 is available on that channel, can you update us?

Could you try doing a bisect (use `-a linux64`) on centos? see: https://www.chromium.org/developers/bisect-builds-py

the command will be something like

```
tools/bisect-builds.py --use-local-cache -a linux64 -g 599034 -b X --not-interactive -c 'bash -c "CHROME_PATH=%p lighthouse"'
```

where x is either
```
625896 (for 73.0.3683.86)
693954 (for 78.0.3904.70)
```

**Comment by LarsKumbier** [comment]
@connorjclark 

I will update with results from 78.

I tried a bisect, but I cannot reproduce the bug with the bisect - just as I cannot reproduce it on Ubuntu. Who's packaging for centos? Do they perform some source-patching before packaging and releasing in centos or the EPEL repository?

I can workaround by pinning the version for now or using the prebuilt archives to get to the higher versions - or move to ubuntu server instead, so I can manage.

Do you still want me to proceed in investigating / does it help you in any way?

**Comment by LarsKumbier** [comment]
Since there has not been any answer, I'll close this and don't dig further.
