### ISSUE TITLE
Disparate Report Scores

### ISSUE THREAD

**Issue by FiveOaks** [GoogleChrome/lighthouse#9884]
I've run a Lighthouse scan on www.CriminalDefenseLex.com and got a performance score of 22. A colleague in another city ran a Lighthouse scan on the same website and got a performance score of 100. All other scores were identical on both reports.

Any idea why this might be the case? What factors might affect these scores?
![2019-10-24_9-40-41](https://user-images.githubusercontent.com/8268310/67491928-a56aea80-f643-11e9-812d-5e32bffd12ef.png)
![lighthouse_performance_results_no_throttling (002)](https://user-images.githubusercontent.com/8268310/67491929-a56aea80-f643-11e9-9bef-dc51c6791b82.png)

**Comment by patrickhulce** [comment]
Well for starters it looks like 

> There were issues affecting this run of Lighthouse:
Chrome extensions negatively affected this page's load performance. Try auditing the page in incognito mode or from a Chrome profile without extensions.

Did you try auditing the page in incognito mode or from a Chrome profile without extensions?

Other things to check:
- Were you using the same throttling settings?
- Were you using the same desktop/mobile settings?
- Were you auditing the same page? (Login page/server errors/etc, check the screenshots if it looks like it should)

**Comment by Morgan-Marshall** [comment]
Along with lighthouse extension, builtin audits tab, and pagespeed insights never having the same score as they should, after updating to Chrome Version 78.0.3904.70, I've had a lot of inaccurate score issues with the audits tab.
