### ISSUE TITLE
Preconnect to required origins suggestion keeps coming even after adding the origins

### ISSUE THREAD

**Issue by gulatigautam** [GoogleChrome/lighthouse#9894]
#### Provide the steps to reproduce
1. Run LH on https://qwww.americanexpress.com
  

#### What is the current behavior?

Running the report earlier was showing these urls under "Preconnect to required origins":
 
  | <link rel="preconnect" href="https://nexus.ensighten.com" crossorigin>
  | <link rel="preconnect" href="https://www.aexp-static.com">
  | <link rel="preconnect" href="https://cdaas.americanexpress.com">
  | <link rel="preconnect" href="https://aug.americanexpress.com">
  | <link rel="preconnect" href="https://aexp.demdex.net" crossorigin>
 
We added these and ran the report again and now we are being shown 6 more origins. We are trying to understand how does this work? How do we know which are the "important third-party origins." and good candidate for adding preconnects? We read somewhere we can only add up to 6 preconnects. Is that correct? If yes, why does Lighthouse keeps suggesting these even after we have added them?

![Screen Shot 2019-10-28 at 10 53 16 AM](https://user-images.githubusercontent.com/13562914/67689168-4b369600-f971-11e9-9a28-7f600c45fa04.png)

#### What is the expected behavior?
Shouldn't the report not show this suggestion when the origins have been added?

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @gulatigautam! Good find, we should stop suggesting origins once 6 have been added. 👍

**Comment by patrickhulce** [comment]
If anyone is interested in helping us out with this, it'd be adding something along the lines of 

```js

if (preconnectLinks.length >= 6) {
  return {score: 1, warnings: preconnectLinks.length >= 8 ? [str_(UIStrings.tooManyPreconnectLinksWarning)] : []};
}

right at
https://github.com/GoogleChrome/lighthouse/blob/2953c0c1b62afe7cf88ba8718a221d74962d6640/lighthouse-core/audits/uses-rel-preconnect.js#L135-L139

**Comment by gulatigautam** [comment]
Thanks @patrickhulce Even before we made the change, we noticed that the report shows different urls every time we run it. We picked the most common ones and added those. Just curious, How does Lighthouse pick the ones to show in this suggestion? Does it depend on that specific run of the report and that's why the suggestions might change every time?

**Comment by piotrzarycki** [comment]
Ok, i will take care of it

**Comment by rockeynebhwani** [comment]
@patrickhulce  - Can I clarify if the limit is 6 OR 3 ? Please see this twitter thread -  https://twitter.com/_tbansal/status/1197600095824306176?s=12

**Comment by patrickhulce** [comment]
If Tarun says it's 3, I believe him :) Seems like we should update #9903

**Comment by piotrzarycki** [comment]
Ok @patrickhulce , so should change 6 to 3 ? :)

**Comment by piotrzarycki** [comment]
done @patrickhulce  :)
