### ISSUE TITLE
Graceful recovery when no manifest is present

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#99]
![image](https://cloud.githubusercontent.com/assets/39191/14117515/d99694de-f599-11e5-9e94-85f4558a1163.png)

I suppose there's a few cases that we shouldn't bomb on.

* link rel manifest not found in DOM
* link rel manifest found, but it 404s
* manifest asset retrieved but it's invalid JSON
* manifest members are missing, and all that.

I think we have decent coverage here, but we may need to bulk up tests for the manifest gatherer. 

@brendankenny wanna take a stab here?

**Comment by samccone** [comment]
1) gatherer should be in a fault state
2) audits should fail because the gatherer key is in an invalid state
3) each audit should show an error message as to why it is borked.

4) all done :tada:
