### ISSUE TITLE
Running lighthouse from the command line (ReferenceError: URL is not defined)

### ISSUE THREAD

**Issue by tikoms** [GoogleChrome/lighthouse#9906]
Provide the steps to reproduce
1. Run LH on <www.medium.com> but i find that the problem persists regardless of the url. 
 
Environment Information
* Affected Channels: 
* Lighthouse version: 5.6.0
* Chrome version: 
* Node.js version: node-v12.13.0-linux-x64
* Operating System: Linux (Ubuntu)

**Related issues**
Getting the following error when I try to run lighthouse audit from the command line:

/usr/local/lib/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:36
class URLShim extends URL {
                      ^

ReferenceError: URL is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:36:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/lib/network-request.js:14:13)
    at Module._compile (module.js:652:30)

**Comment by patrickhulce** [comment]
Are you 100% positive you're running node 12? That error is exactly what you would get if you were running with a node version of <10, which is the minimum required by Lighthouse.

**Comment by tikoms** [comment]
Hi Patrick,

Thanks for responding.

I am 100% certain, when I visit the Node,js website I am presented with 2
options for downloading Node.js for Linux(x64), 12.13.0 LTS (Recommended
for Most Users) and 13.0.1 Current (Latest Features). I opt for the first
one (12.13.0 LTS), download and install it.

Having said that, on inspecting the folder after the download and install
it shows the version as node-v10.16.3-linux-x64 which should still be okay.
Done everything by the book and spent the whole day battling with it but no
joy.

What's even more bizarre is that I've got 2 systems running on Linux and I
get the same error when I try the lighthouse audit from the command line,
this is after downloading and installing the same version of Node.js on
both.


Warm regards,
George

**Comment by brendankenny** [comment]
@tikoms can you provide the command you're running to execute Lighthouse from the command line? (feel free to https://example.com or whatever for the site to test)

And just to double check, can you paste in the output of running `node --version`, please?

**Comment by connorjclark** [comment]
Use 12.

**Comment by tikoms** [comment]
Hey guys,

Managed to resolve the issue.

Linux (Ubuntu) comes with version 8 of Node.js in it's default
repositories, I think that's the reason why even though I was downloading
and installing version 12 from the Node.org website, it wasn't registering
or being picked up by the system (hence getting version 8 when I execute
node --version on the command line).

Uninstalled the current version and re-installed Node.js using a PPA.

Lighthouse now works as it should.

Cheers guys and thanks.
