### ISSUE TITLE
Chrome prevented page load with an interstitial

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9909]
All gatherers fail to run for https://oldnavy.gap.com/ in Chrome stable (78.0.3904.70, LH 5.2). 

```
GatherRunner:error Chrome prevented page load with an interstitial. Make sure you are testing the correct URL and that the server is properly responding to all requests. +54ms https://oldnavy.gap.com/
```

5.2.0 (current Chrome stable) results in this error. But it doesn't happen for master (from CLI)

**Comment by brendankenny** [comment]
I believe that's #9576 (interstitial in an iframe somewhere)
