### ISSUE TITLE
Page is marked as not crawlable if it contains an iframe with a noindex meta tag 

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#9914]
#### Provide the steps to reproduce

1. Run LH on http://mattzeunert.surge.sh/iframe-noindex/index.html (seems like Surge always blocks indexing, so this sample page doesn't actually demo the issue)

#### What is the current behavior?

Lighthouse says "Page is blocked from indexing", which hurts the SEO score.

#### What is the expected behavior?

Since the page itself can be indexed it should be marked as crawlable, even if it contains a non-indexable iframe.

#### Solution?

The `MetaElements` gatherer uses the `getElementsInDocument` function, which also includes tags that are in a shadow DOM. Maybe shadow DOM/iframe meta elements could be marked in some way in the artifact, and then filtered out by the `IsCrawlable` audit?

Or `getElementsInDocument` could have an argument to exclude shadow DOM elements, and we use that for the `MetaElements` gatherer. Do we care about validating meta tags in iframes?

**Comment by patrickhulce** [comment]
Ah great catch @mattzeunert thanks :)

**Comment by piotrzarycki** [comment]
can i take this bug?

**Comment by patrickhulce** [comment]
sure @piotrzarycki if you're feeling up to it! :)

I think the most straightforward approach would be to just ignore meta elements in shadow DOM/frames and do a simple qSA instead of `getElementsInDocument`

**Comment by piotrzarycki** [comment]
ok, thx

**Comment by mattzeunert** [comment]
I can't replicate this right now. `getElementsInDocument` doesn't look at the IFrame `contentWindow`, so I don't see why it would pick up the meta elements from the IFrame.

Surge always blocks indexing via robots.txt, so my original demo doesn't make sense. I set up this [Glitch demo](https://broad-money-0ludhlqamu.glitch.me/) and Lighthouse doesn't say indexing is blocked.

I think you can close this issue, unless you see some way this could happen?

**Comment by connorjclark** [comment]
glitch demo is gone btw

are we comfortable closing this?

**Comment by patrickhulce** [comment]
We're going ahead and closing this. If anyone can reproduce this issue, please feel free to chime in with the reproduction details and we'll reopen :)
