### ISSUE TITLE
Surface main-thread-tasks in report

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#9921]
For people debugging their TTI and TBT, knowing about all the long tasks is pretty critical. We should provide that in the report. 

We have [main-thread-tasks](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/main-thread-tasks.js) and I think the first step is making visible in diagnostics.

It's also not not terribly helpful... just sharing the startTime & duration. Ideally we'd also indicate some attribution, but I was thinking that since it's surfacing the trace's toplevel tasks, we'd have to do quite a bit of work to summarize the kind of work (and related URLs) that's happening within, right?

**Comment by paulirish** [comment]
Oh also relevant to mpFID, which is likely going zero-weighted for v6. 

Since mpFID is just the longest task after FCP, this table will end up sharing the exact same timing.

**Comment by patrickhulce** [comment]
>  I was thinking that since it's surfacing the trace's toplevel tasks, we'd have to do quite a bit of work to summarize the kind of work (and related URLs) that's happening within, right?

We're already doing that work in bootup time, so I don't think it's that far fetched to move it to computed artifact and surface it here as well, though it will make more sense to list *all* the URLs that were responsible for it rather than just the "root" one.

**Comment by connorjclark** [comment]
dupe #10705
