### ISSUE TITLE
artifact.value.trim is not a function

### ISSUE THREAD

**Issue by natekonimbo** [GoogleChrome/lighthouse#993]
Tested web-app: [Link](https://nate-pwa.firebaseapp.com/)

**Lighthouse Version**: 1.2.0
**Chrome Version**: 53.0.2785.143
**Error Message**: artifact.value.trim is not a function
**Stack Trace**:
 ```TypeError: artifact.value.trim is not a function
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:3452:24)```

**Comment by patrickhulce** [comment]
Duplicate #967
