### ISSUE TITLE
(canceled) isn't cause/context specific

### ISSUE THREAD

**Issue by jeffreytgilbert** [GoogleChrome/lighthouse#9941]
**Feature request summary**
In the network tab, (canceled) tells me the request was abandoned, but there is no indicator what the origin or cause of that cancelation was. The data included in the Timing tab shows "Stalled" with no duration (similar for all requests) and then no additional information. What would be handy is knowing if the cancelation was due to user navigation, fetch timeout, window.stop() call, etc. Instead, a very generic "(canceled)" message is included, so it's not possible to grok what caused the cancelation. 

**What is the motivation or use case for changing this?**
Primarily, this would help when debugging, triaging, and developing new software and services.

**How is this beneficial to Lighthouse?**
Doesn't fit anywhere else.

**Comment by connorjclark** [comment]
I think you want to file this at crbug.com
