### ISSUE TITLE
*Element artifacts should have `devtoolsNodePath`

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9947]
This allows for linking within DevTools.

Should probably tackled #2289 first. May be that we come up with something better than `devtoolsNodePath`.

**Comment by connorjclark** [comment]
brain dump on all things devtools node path:

## element gatherers that are missing devtools node path

I think it's just `IframeElement`.

## audits that use nodes but not devtools node paths

AFAICT, these are all the audits that use `node` types but not devtools node path. None use any *Element gatherers.

* password-inputs-can-be-pasted-into
* * uses `PasswordInputsWithPreventedPaste` ... i've literally never seen this before ...
* font-size
* * doesn't use any element artifacts, 100% custom protocol stuff from `font-size` gatherer. would need to calculate the path somehow once all the failing nodes are found in https://github.com/GoogleChrome/lighthouse/blob/ab19f289e6265bc82c6e35a7c899a9d01ddbcd5b/lighthouse-core/gather/gatherers/seo/font-size.js#L216 . tbh this is probably not worth the effort, b/c the only time the `node` type is used in `font-size` audit is when the small font is from inline element styles `<p style="font-size: 5px">...</p>` or `<font size=5>`, which is not very common

## node path leads to flaky linkifying

referring to:

> Should probably tackled #2289 first. May be that we come up with something better than devtoolsNodePath.

I still think we can come up with a selector that is less fragile than devtools node path, but let's not consider it a blocker for any of these other improvements.


## Name consistency

Most artifacts name this path `devtoolsNodePath`. However, some just use `path`. We should change these outliers to be `devtoolsNodePath`.

gatherers that use `path`: `tap-targets`, `accessibility`.

The Node AuditDetails type uses `path`, but changing that would be a breaking change, so let's not bother changing that. At the least there should be a comment saying it is the devtools node path here https://github.com/GoogleChrome/lighthouse/blob/5b9a37ae0f1601d699d9eeb16fd1cd38ff94bec9/types/audit-details.d.ts#L206



## sample json test coverage

kinda interesting to see which audits are missing test coverage for node path. if we want to take any action here we should consider smoke tests in the "is there any coverage" check.

```js
const audits = Object.values(require('./lighthouse-core/test/results/sample_v2.json').audits);

const auditsWithNodes = audits
  .filter(a => a.details && a.details.items)
  .filter(a => a.details.items.some(i => JSON.stringify(i).includes('"type":"node"')))
  .map(a => a.id);

const auditsWithNodePaths = audits
  .filter(a => a.details && a.details.items)
  .filter(a => a.details.items.some(i => JSON.stringify(i).includes('"path":"')))
  .map(a => a.id);

const diff = auditsWithNodes.filter(a => !auditsWithNodePaths.includes(a));

console.log({auditsWithNodes, auditsWithNodePaths, diff});
```

```js
{
  auditsWithNodes: [
    'largest-contentful-paint-element',
    'layout-shift-elements',
    'unsized-images',
    'color-contrast',
    'html-has-lang',
    'image-alt',
    'label',
    'link-name',
    'object-alt',
    'external-anchors-use-rel-noopener',
    'password-inputs-can-be-pasted-into',
    'crawlable-anchors',
    'tap-targets'
  ],
  auditsWithNodePaths: [
    'largest-contentful-paint-element',
    'layout-shift-elements',
    'color-contrast',
    'html-has-lang',
    'image-alt',
    'label',
    'link-name',
    'object-alt',
    'external-anchors-use-rel-noopener',
    'crawlable-anchors',
    'tap-targets'
  ],
  diff: [ 'unsized-images', 'password-inputs-can-be-pasted-into' ]
}
```

**Comment by brendankenny** [comment]
@adrianaixba is this fixed now? Or fixed with #11474?

**Comment by adrianaixba** [comment]
@brendankenny so-so! node info is standardized amongst all 'devtools node' gatherers and audits, except font-size. This and 'flaky linkifying' weren't resolved, maybe these could be handled as separate issues if there is still interest? @connorjclark

**Comment by connorjclark** [comment]
I think we can close this when  #11474 lands. the other big item is the flaky stuff, but is captured in #2289

**Comment by connorjclark** [comment]
Will land #11474 for v7, then close this issue.
