### ISSUE TITLE
Lighthouse Not Working on Ubuntu 19.04

### ISSUE THREAD

**Issue by assunluis80** [GoogleChrome/lighthouse#9956]
I'm using Google Chrome v78.0.3904.97 on Ubuntu 19.04 and I'm trying to run some tests on Lighthouse, but it's not working. It stays on warming up state, forever!

One important thing: I don't have connection to the Internet. Do I need to run Lighthouse? 

![LightHouse](https://user-images.githubusercontent.com/8853276/68579862-0defff00-046d-11ea-9d40-5603b7131bad.png)

**Comment by connorjclark** [comment]
Lighthouse downloads lazily the first time you open devtools so you will need a connection initially
