### ISSUE TITLE
ChromeLauncher Waiting for browser instead of run tests

### ISSUE THREAD

**Issue by Mef45** [GoogleChrome/lighthouse#9960]
#### Provide the steps to reproduce
1. Run LH on <example.com>
  

#### What is the current behavior?
"ChromeLauncher Waiting for browser" message and nothing else.

Then error 
```ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:34951 +2ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.I00OmXf/chrome-err.log +0ms
  ChromeLauncher:error [7719:7719:1112/101403.938841:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
  ChromeLauncher:error  +0ms
Unable to connect to Chrome
```
#### What is the expected behavior?
Run lighthouse tests for example.com

#### Environment Information
* Affected Channels: CLI 
* Lighthouse version: 5.6.0
* Chrome version: 78.0.3904.97 
* Node.js version: v12.9.1
* Operating System: Debain 10 buster

**Related issues**
![image](https://user-images.githubusercontent.com/26562037/68643906-13188100-0535-11ea-8f1f-c69452ca3910.png)
![image](https://user-images.githubusercontent.com/26562037/68643959-3fcc9880-0535-11ea-978b-d4ec20699d64.png)

**Comment by patrickhulce** [comment]
Have you tried the advice printed in the console?

>   ChromeLauncher:error [7719:7719:1112/101403.938841:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

`lighthouse --chrome-flags="--no-sandbox"`

**Comment by connorjclark** [comment]
could you provide more info @Mef45 ?
