### ISSUE TITLE
Add all element attributes for the MetaElements artifacts

### ISSUE THREAD

**Issue by roelfjan** [GoogleChrome/lighthouse#9964]
**Feature request summary**
Now for the MetaElements artifact the properties `name` and `content` are provided (see: [types](https://github.com/GoogleChrome/lighthouse/blob/master/types/artifacts.d.ts#L75)). I would like to get all attributes on the `<meta>` element. 

Facebook uses the attribute `property` instead of `name` for their tags, like this:
```html
<meta property="og:description" content="[description]" />
```
Which results in the MetaElements like this:
```js
 { name: "", content: "[description]" }
```

I would like to receive something like this for a Facebook meta tag:
```js
 { property: "og:description", content: "[description]" }
```

**What is the motivation or use case for changing this?**
I am creating a Lighthouse plugin for an audit on social sharing tags like Twitter and Facebook present on the page. This feature is needed for a check on Facebook tags.

**How is this beneficial to Lighthouse?**
This feature provides a better representation of the audited page. Which will provide Lighthouse users with more information.

**Comment by patrickhulce** [comment]
I'm not sure about *all* the attributes but `property` definitely sounds good! I'd welcome such a PR :)

**Comment by connorjclark** [comment]
fyi https://stackoverflow.com/questions/22350105/whats-the-difference-between-meta-name-and-meta-property
