### ISSUE TITLE
Show a top level warning when the requested url is redirected

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9969]
@patrickhulce and I thought we were doing this, but apparently not. No message in 4.0 or 5.0 either.

This is the only indication that there was a page redirect:

![image](https://user-images.githubusercontent.com/4071474/68803926-87c2ec80-0615-11ea-99fe-c3e1b35a130d.png)

This is too low in the report.

The warning should have a CTA to run Lighthouse again with the redirected URL

**Comment by brendankenny** [comment]
#1917 :)

**Comment by brendankenny** [comment]
(P1.5 :)
