### ISSUE TITLE
Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)

### ISSUE THREAD

**Issue by Sysnetgits** [GoogleChrome/lighthouse#9970]

**Comment by Khnaz35** [comment]
Hi am also facing the same issue when am trying to audit my website.
have  a look into the screenshot.  http://prntscr.com/py2zj9

i try to audit incognito the error is still same. please suggest what should i do.

**Comment by LorenAmelang** [comment]
Guess I have the same problem, in the web Lighthouse: 
https://developers.google.com/speed/pagespeed/insights/?url=http://www.psychoros.com/

The Chrome User Experience Report does not have sufficient real-world speed data for this page.

Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP) - For every item! 

Same result in Chrome, Firefox, or Vivaldi. 

But https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.pacific.net
works - still no real-world speed, but tests all work. 

And https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.mendocinosheriff.com%2F
supposedly hosted by the same company as Psychoros, totally works! 

Psychoros is ancient pure HTML in a text editor - does that matter?

**Comment by connorjclark** [comment]
@Khnaz35 please open a new issue with the url and issue template filled out

@LorenAmelang unfortunately we don't inspect much inside of frames. since that page is all frames, we basically see nothing
