### ISSUE TITLE
If Gatherer fails, Gatherers in separate Pass do not run

### ISSUE THREAD

**Issue by fbatschi** [GoogleChrome/lighthouse#9973]
I have a problem with Lighthouse, which I am not quite sure if this expected behaviour.
I researched the problem to the best of my knowledge.

I am running LH against a webserver that is unfortunately wrongly configured.
When accessing the server via HTTP (let's say it's `http://www.example.com/`) it redirects via 301 to https and a non existant domain (`https://www.example.nonexistant/`)

The `redirects-http` audit (or rather the `HTTPRedirect` gatherer?) fails here with a `dnsFailure` and does not run.

First problem is that - as this `redirects-http` audit is grouped into the `pwa` category - the whole `pwa` category gets no score and the failed audit leads to a general error for the whole `pwa` category, shown as `?` in an html report. I would rather expect, that the error audit gets put into the list of failed audits and calculation goes on anyways, but I think, this is the way Lighthouse is supposed to work. 

My bigger problem is, that i have extended the default LH configuration and added a set of custom audits and gatherers. Two of these custom gatheres are supposed to run in a separate pass after Lighthouse's default load (pass) of gatherers.

But in this case, when the `redirects-http` audit or rather the `HTTPRedirect` Gatherer fails, the Gatherer after that are not run as well and I can't see why. They have no dependency on the `HTTPRedirect` Gatherer.

If I run Lighthouse with `--skip-audits=redirects-http`, everything works fine against this specific server.

## Provide the steps to reproduce
Have a server that issues a 301 Redirect on Port 80 to a non existant domain 
Run Lighthouse against this server/page.

#### What is the current behavior?

The HTTPRedirect Gatherer fails. Gatherers that should run in a pass after that, do not run.

#### What is the expected behavior?

If a HTTPRedirect Gatherer fails, Gatherers that should run in a pass after that, should run.

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 5.6.0
* Chrome version: 78
* Node.js version: 12
* Operating System: Linux

**Comment by connorjclark** [comment]
Can you share your custom config? Which pass are your gatherers configured for - a new one, or augmenting a pass from the default config?

**Comment by connorjclark** [comment]
any update @fbatschi?

**Comment by brendankenny** [comment]
There hasn't been any movement on this issue since last November, so I'm going to close for now. If you think it's still worth pursuing, please comment with more details and we can reopen!

**Comment by brendankenny** [comment]
And, actually reading closer now :)

For anyone coming across this in the future, head over to #11459 to see ways we're exploring fixing this.
