### ISSUE TITLE
How to get logged-page audit！

### ISSUE THREAD

**Issue by zxf-nobug** [GoogleChrome/lighthouse#9976]
I want to test some pages after already logged in,how to enter the correct url.
whether  it have any Options to let browser does not close？

**Comment by zxf-nobug** [comment]
If I want to take option--extra-headers XXXX，i can see the page a little second，then get a 403 page
and console show “status Loading page & waiting for onload ServiceWorker, Offline, StartUrl +1ms”.
There are ways around this time delay?

**Comment by patrickhulce** [comment]
Have you already read the [authenticated pages docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md)?
