### ISSUE TITLE
my website is not working correctly and has these issues

### ISSUE THREAD

**Issue by editorials4u217** [GoogleChrome/lighthouse#9994]
[`#<!--`](url
![PERFORMANCE](https://user-images.githubusercontent.com/48893501/69250189-d5d77300-0b74-11ea-9561-e384918aab11.PNG)
) Before creating an issue please make sure you are using the latest version and have checked for duplicate issues. -->

#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
This is not the correct forum for general website development help. Try [StackOverflow](http://stackoverflow.com/) with a more specific question.
