### ISSUE TITLE
filesystem: uri's are treated as non-HTTPS

### ISSUE THREAD

**Issue by EionRobb** [GoogleChrome/lighthouse#9996]
#### Provide the steps to reproduce
1. Store a file using the window.requestFileSystem API
2. Output the file URI to an `<img src="..."/>`

#### What is the current behavior?
The app is treated as non-installable
![image](https://user-images.githubusercontent.com/1063865/69263034-61124080-0c29-11ea-9b3a-aad54e8de604.png)

#### What is the expected behavior?
filesystem: URI's (and potentially blob:'s, or other non-http URI's) should be excluded from this check

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.2.0
* Chrome version: 78.0.3904.108
* Node.js version:
* Operating System: Windows 10 64-bit

**Related issues**
Nothing found

**Comment by paulirish** [comment]
Here's a lil snippet to generate filesystem resources in a page: 

```js
function onInitFs(fs) {
  fs.root.getFile(`empty-${Math.random()}.png`, {create: true, exclusive: true}, function (fileEntry) {
    const img = document.createElement('img');
    img.src = fileEntry.toURL();
    document.body.appendChild(img);
    console.log('filesystem image added to DOM', img);
  }, console.error);
}
  
window.webkitRequestFileSystem(window.TEMPORARY, 1024 * 1024, onInitFs, console.error); 
```
